AQI calculator for HM3301
OttoWinter/esphomeyaml pull request #1011
Opened 2020-04-06 19:22 UTC by freekode

## Description:
This adds new sensor to platform hm3301. The sensors shows value of air quality based on PM 2.5 and PM 10.0 values. There are two implementations for now AQI (USA air quality standard), CAQI (Europe air quality standard)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-04-07 07:37 UTC, freekode commented
This sensors could be created as abstraction for air quality devices.
I'm not sure is it good idea and can I do it at all.

2020-06-05 10:49 UTC, freekode commented
Review somone?

2020-06-09 02:46 UTC, glmnet commented on esphome/components/hm3301/hm3301.cpp
> +    this->aqi_sensor_->publish_state(aqi_value);
there are nullptr checks, those exists because the sensors are optional in the yaml, if they are not declared they are nullptr and `publish_state` should not be called on them!
This code as is crashes with some combinations.

2020-06-09 02:56 UTC, glmnet requested changes
Please see possible crash while updating sensors

2020-06-09 07:45 UTC, freekode commented on esphome/components/hm3301/hm3301.cpp
> +    this->aqi_sensor_->publish_state(aqi_value);
There are NP checks for sensors. If sensor is null, then value will be -1. Later if value -1 (we already know this could be in situation when sensor is null), then don't publish state.
-1 here means that value doesn't exits, so we don't need to do anything.

2020-06-09 11:53 UTC, glmnet commented on esphome/components/hm3301/hm3301.cpp
> +    this->aqi_sensor_->publish_state(aqi_value);
Looks like you’re right. Dunno what I’ve thinking. 
However if you don’t provide a sensor for 2,”.5 or 10 and you do ask for aci it will not work as expected.

2020-06-09 12:18 UTC, freekode commented on esphome/components/hm3301/hm3301.cpp
> +    this->aqi_sensor_->publish_state(aqi_value);
There is check for it, line 67. If AQI is not null and value 2.5 not -1 (so it means sensor is enabled and we already have value) and value 10 not -1 (the same, sensor exists and value presented).
If all this true, we calculate info and set variable `aqi_value` from -1 to some not -1.
Later we also check this variable, is it not -1, it means it has some value

2020-06-09 12:27 UTC, glmnet commented on esphome/components/hm3301/hm3301.cpp
> +    this->aqi_sensor_->publish_state(aqi_value);
I see that, However if you don’t provide a sensor for 2,”.5 or 10 and you do ask for AQI it will not work as expected.

2020-06-09 19:44 UTC, freekode commented on esphome/components/hm3301/hm3301.cpp
> +    this->aqi_sensor_->publish_state(aqi_value);
if 2.5 or 10 sensors will not be provided then vars pm_2_5_value or pm_10_0_value will have -1, so aqi will not be calculated on line 68.
but ok, I added NP checks for this if

2020-06-09 23:47 UTC, glmnet commented on esphome/components/hm3301/hm3301.cpp
> +    this->aqi_sensor_->publish_state(aqi_value);
That shuldn't work that way, this configuarion:

```yaml
    sensor:
      - platform: hm3301
        aqi:
          name: "AQI"
          type: "CAQI"
```

should work as expected... as it is now, it seems the value will never be updated.

2020-06-10 08:09 UTC, freekode commented on esphome/components/hm3301/hm3301.cpp
> +    this->aqi_sensor_->publish_state(aqi_value);
added validation for AQI sensor,
if you have other comments, please let me know what should be changed

2020-06-10 13:08 UTC, glmnet approved these changes

2020-06-12 02:14 UTC, merged