Uart improvments
OttoWinter/esphomeyaml pull request #1024
Opened 2020-04-16 13:29 UTC by 0hax

## Description:

This adds support for setting parity and number of bits in uart component.
It also adds support for begin() and end() methods.
Both functionalities will be used in a new component I'm adding and that I will send in a different review request.
This other component is named "teleinformation" and let you get details about power consumption from French electrical counter using Uart.

I didn't updated documentation yet. I would like to have some feedback beforehand.

## Checklist:
  - [*] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-04-23 19:40 UTC, Mynasru commented
Can you also add a boolean configuration to invert the UART in the begin() function? see [this](https://github.com/tbrasser/esphome/commit/e8d86c31cdc6b19dc8dc2671f6ea122bd5d84c20)

2020-04-25 11:55 UTC, 0hax commented
> Can you also add a boolean configuration to invert the UART in the begin() function? see [this](https://github.com/tbrasser/esphome/commit/e8d86c31cdc6b19dc8dc2671f6ea122bd5d84c20)

I'm not sure to get the commit you shared.
`invert` option is passed to the ESP8266SoftwareSerial.setup() in uart.h but it's not used anywhere in uart.cpp.
We could implement this in another PR once this PR is merged if needed.

2020-04-25 21:15 UTC, Mynasru commented
> > Can you also add a boolean configuration to invert the UART in the begin() function? see [this](https://github.com/tbrasser/esphome/commit/e8d86c31cdc6b19dc8dc2671f6ea122bd5d84c20)
> 
> I'm not sure to get the commit you shared.
> `invert` option is passed to the ESP8266SoftwareSerial.setup() in uart.h but it's not used anywhere in uart.cpp.
> We could implement this in another PR once this PR is merged if needed.

Sorry if I was unclear. This commit hardcodes this option (which is not what we want). The invert uart option in the serial setup is only available for esp32. I'll make a fix myself for this issue, thank you for your effort.

2020-05-03 13:27 UTC, 0hax commented
> Sorry if I was unclear. This commit hardcodes this option (which is not what we want). The invert uart option in the serial setup is only available for esp32. I'll make a fix myself for this issue, thank you for your effort.

Ok, let me know if I can help.
Anything special I should do to have this reviewed?

2020-05-18 23:08 UTC, glmnet requested changes
could you also organize a bit the files? all cpp files will be copied and compiled so I'd like to have two new files 
- uart_esp8266.cpp
- uart_esp32.cpp

so you put the specific methods for them there

Thanks!

2020-05-18 23:08 UTC, glmnet commented on esphome/components/uart/uart.cpp
> +  /* TODO: Should we check parity? Or is it too slow for nothing added..*/
An idea would be to mark component with warning / error so user will get a notification something is wrong?
See https://esphome.io/components/status_led.html which uses this https://github.com/esphome/esphome/blob/4f2e2fa297070e4d7f55a37175359f4d8f74c0f0/esphome/core/component.cpp#L116-L116

2020-05-20 21:16 UTC, 0hax commented
> could you also organize a bit the files? all cpp files will be copied and compiled so I'd like to have two new files
> 
>     * uart_esp8266.cpp
> 
>     * uart_esp32.cpp
> 
> 
> so you put the specific methods for them there
> 
> Thanks!

Just checking before doing everything, should I do the split between esp8266 and esp32 here or in another pull request?

2020-05-20 22:05 UTC, glmnet commented
Here is ok.

2020-05-22 12:38 UTC, 0hax commented on esphome/components/uart/__init__.py
> +CONF_NR_BITS = 'nr_bits'
That actually means "Number of bits" used to transmit Data.
I can rename it to CONF_DATA_BITS_NUMBER

2020-05-22 12:38 UTC, 0hax commented on esphome/components/uart/uart.cpp
> +#define UART_PARITY_EVEN 0 << 0
Ok I will change this. What is the reason for using `static const uint8_t` out of curiosity ?

2020-05-22 13:02 UTC, 0hax commented on esphome/components/uart/__init__.py
> +    cv.Optional(CONF_PARITY, default="none"): cv.one_of("none", "even", "odd", lower=True),
Good idea, I will use an enum.

2020-05-23 13:52 UTC, 0hax commented on esphome/components/uart/uart.cpp
> +  /* TODO: Should we check parity? Or is it too slow for nothing added..*/
I'm thinking we should add a simple warning when user register SWserial with parity.
Or better, maybe we should prevent this with an error and add a warning in the documentation saying it's not supported.?

2020-05-23 17:25 UTC, 0hax commented on esphome/components/uart/uart.cpp
> +#define UART_PARITY_EVEN 0 << 0
I had to use `uint32_t` at the end.

2020-05-24 21:09 UTC, glmnet commented on esphome/components/uart/uart.cpp
> +#define UART_PARITY_EVEN 0 << 0
I don't know exactly what had Otto in mind when deciding this, but I've seen him review (my own code) this kind of stuff this way, so I ask you too more because of consistency.
There are pros and cons of course: https://stackoverflow.com/questions/1637332/static-const-vs-define

2020-05-24 21:42 UTC, glmnet commented
Ok, I've just changed some param name. Thanks for this! looks nice!

2020-05-24 21:59 UTC, merged

2020-05-25 15:25 UTC, 0hax commented
> Ok, I've just changed some param name. Thanks for this! looks nice!

Thanks!

2020-07-24 17:58 UTC, OttoWinter commented
@0hax What are the `begin()` and `end()` functions for?

The design of the uart component is that it starts listening as soon as you the parent component is set up, which should not be a problem for any component code and prevents messy Arduino-like code with `begin()` and `end()` used everywhere (and keeping track of what state the uart parent is currently in).

2020-07-25 12:59 UTC, 0hax commented
> @0hax What are the `begin()` and `end()` functions for?
> 
> The design of the uart component is that it starts listening as soon as you the parent component is set up, which should not be a problem for any component code and prevents messy Arduino-like code with `begin()` and `end()` used everywhere (and keeping track of what state the uart parent is currently in).

I'm using it in https://github.com/esphome/esphome/pull/1108 for example where the electrical counter is sending data over UART every few seconds and there is no flow control.
So to be sure we are getting latest data, I'm using begin()/end() method to reset UART internal buffers and be sure to start with empty buffers.