RGBWW - added channel interlock for RGB vs white
OttoWinter/esphomeyaml pull request #1042
Opened 2020-05-01 12:14 UTC by peq123

## Description:
so that the RGB doesn't affect white colour temp interlocks RGB channels against white value 
white value is now set to either 0.0f or 1.0f so that brightness value and colour temp is now the only value controlling % of white channels. 

**Related issue (if applicable):** fixes <link to issue>
https://github.com/esphome/issues/issues/1180
**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [x ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).
(no added/changed)

2020-06-12 15:21 UTC, Skaronator commented
Maybe it would make sense to have this optional as a config parameter similar how the constant_brightness was implemented in #1007?

2020-06-12 15:57 UTC, peq123 commented
Honestly I haven't seen a use case to make it optional (though obviously I don't own every bulb out there). the reason why I made this pr was as follows: Google Home doesn't offer a separate white level specific for the white leds (colour temp provided but this is different), it assumes the bulbs brightness is controlled by the brightness control regardless of the leds used. The situation arose that brightness was at max but the white level at minimum and therefore the bulbs were not lit. In home assistant, this would mean extra clicks to make sure all the settings were correct after a call by Google or as I have seen several posts on home assistant forums people use HA automations or node red to address this (and to avoid extra bars). this pr addresses (and imo corrects) this behaviour. furthermore, this behaviour is how tasmota handles these types of bulbs.

2020-06-12 18:42 UTC, glmnet commented
So with these changes you cannot turn on CW WW and RGB channels at same time?
If this is changing that I'd like to have a new option for this, we don't know how many people is using the old behavior and people naturally doesn't like changes

2020-06-12 20:29 UTC, peq123 commented
@glmnet "people naturally doesn't like changes" true true, I will add and test on my local bulbs before I re-commit

2020-06-12 22:50 UTC, peq123 commented
ok so I have added the optional flag and have tested on my bulbs. Just needs to pass Travis

2020-06-12 22:51 UTC, Skaronator commented
Thanks, I'll give this a try tomorrow.

2020-06-12 23:01 UTC, peq123 commented
@Skaronator noticed there was a commit for the gamma fixing while I was doing this, could you check my pr contains the fixes

2020-06-16 20:07 UTC, Platzii commented
Tested this PR with my RGBWW bulb and seems to do the job 👍

2020-06-18 22:55 UTC, glmnet commented
So this will need a small entry in docs for `color_interlock`

2020-06-20 11:15 UTC, peq123 commented
https://github.com/esphome/esphome-docs/pull/653

2020-06-21 21:54 UTC, Skaronator requested changes

2020-06-21 21:54 UTC, Skaronator commented on esphome/components/light/light_color_values.h
> +      *blue = gamma_correct(this->state_ * this->brightness_ * this->blue_, gamma);
There is a lot of duplicated code above. You could simplify by applying the `this->state_ * this->brightness_ * (1.0f - this->white_)` to a variable and reuse that in the red, green and blue calculation.

The big `if` could also be minimized by just applying the logic once to the unified variable.

2020-06-28 21:39 UTC, glmnet commented
@peq123 would you like to apply the suggestion above?

2020-06-29 11:10 UTC, peq123 commented
Certainly, will start to address it this evening.

2020-06-29 13:09 UTC, kll commented
I'm testing this on a Feit Electric A19 RGBWW that uses a combo of PWM and an SM16716 and it looks to be working exactly like I need it to. This particular bulb also has the diffuser cut off so I can see the individual LEDs and I've visually verified the interlock behavior. :+1:

2020-07-09 23:29 UTC, merged

2020-08-23 20:22 UTC, CarlosGS commented
This is very helpful. Lights definitely had an undesired blue tone.

But most importantly, the bulbs were getting *extremely* toasty. I even capped all PWMs at 60% and bulbs were still getting burning hot.

I know it's "breaking", but **please consider enabling this setting by default.**