Max7219 new
OttoWinter/esphomeyaml pull request #1053
Opened 2020-05-09 12:53 UTC by rspaargaren

## Description:

**Related issue (if applicable):** fixes 
https://github.com/esphome/feature-requests/issues/14#

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#577

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-05-27 00:24 UTC, glmnet commented
a link in index.rst is missing

2020-05-27 15:14 UTC, rspaargaren commented
index.rst has been added to the documentation

2020-05-27 15:54 UTC, glmnet requested changes
Looking good!

2020-05-27 15:54 UTC, glmnet commented on esphome/components/max7219digit/README.md
> +https://user-images.githubusercontent.com/10338724/81001535-2c491d00-8e48-11ea-86f2-2b0bb60eacb0.jpeg
remove this file, we don't add readmes for components, they all have their docs in their place, if some info here is relevant it should be included in the docs.

2020-05-27 15:54 UTC, glmnet commented on esphome/components/max7219digit/display.py
> +    cv.Optional(CONF_SCROLL_DWELL, default=1000): cv.int_range(min=0),
these should be time type, see https://deploy-preview-585--esphome.netlify.app/guides/configuration-types.html#config-time and examples https://github.com/esphome/esphome/blob/fed37b48a107dbf01b4cf53b3906b8a3a5e64c46/esphome/components/time_based/cover.py#L18

2020-05-27 15:54 UTC, glmnet commented on esphome/components/max7219digit/display.py
> +    cv.Optional(CONF_SCROLL_MODE, default=0): cv.int_range(min=0, max=1),
these should be an enum

2020-05-27 15:54 UTC, glmnet commented on tests/max7219-2.yaml
> +esphome:
remove unrelated files, only 1 test file is required for this integration, the goal is to have the cpp code being compiled, not much testing is possible with different yamls

2020-05-27 15:54 UTC, glmnet commented on tests/nextion/partitions.csv
> +nvs,      data, nvs,     0x009000, 0x005000,
remove this

2020-05-27 15:54 UTC, glmnet commented on esphome/components/max7219digit/max7219digit.h
> +  uint16_t scroll_speed_ = 250;
remove all default values, defaults are in the py file and all setters are called. Cpp code is not supported without py generation

2020-05-27 15:54 UTC, glmnet commented on esphome/components/max7219digit/max7219digit.cpp
> +void MAX7219Component::set_scroll_mode(uint8_t mode) { this->scroll_mode_ = mode; }
you can implement all this in the h if you want

2020-05-31 19:27 UTC, rspaargaren commented on esphome/components/max7219digit/README.md
> +https://user-images.githubusercontent.com/10338724/81001535-2c491d00-8e48-11ea-86f2-2b0bb60eacb0.jpeg
Readme file has been removed. This was not up to date anyhow...

2020-05-31 19:28 UTC, rspaargaren commented on esphome/components/max7219digit/display.py
> +    cv.Optional(CONF_SCROLL_DWELL, default=1000): cv.int_range(min=0),
Type has been adjusted to time_period and default values have been updated to new format

2020-05-31 19:28 UTC, rspaargaren commented on tests/max7219-2.yaml
> +esphome:
Only one test file MAX7219.yaml has been left over in test dir

2020-05-31 19:29 UTC, rspaargaren commented on tests/nextion/partitions.csv
> +nvs,      data, nvs,     0x009000, 0x005000,
REMOVED was left over from previous edit

2020-05-31 19:29 UTC, rspaargaren commented on esphome/components/max7219digit/max7219digit.h
> +  uint16_t scroll_speed_ = 250;
Default values which are set in Python config have been removed from the file.

2020-05-31 19:30 UTC, rspaargaren commented on esphome/components/max7219digit/max7219digit.cpp
> +void MAX7219Component::set_scroll_mode(uint8_t mode) { this->scroll_mode_ = mode; }
These have  been moved to the h file.

2020-05-31 20:22 UTC, rspaargaren commented on esphome/components/max7219digit/display.py
> +    cv.Optional(CONF_SCROLL_MODE, default=0): cv.int_range(min=0, max=1),
It was a bit of searching on how to do but enum types have been added and the doc files have been updated.

2020-06-07 00:40 UTC, glmnet requested changes

2020-06-07 00:40 UTC, glmnet commented on esphome/components/max7219digit/display.py
> +    cv.Optional(CONF_ROTATE_CHIP, default='CONT'): cv.enum(CHIP_MODES, upper=True),
default value is not a CHIP_MODES value, is causing to fail when default value is tried to be used.

2020-06-07 00:40 UTC, glmnet commented on esphome/components/max7219digit/display.py
> +    'CONT': 0,
change to CONTINUOUS

2020-06-07 00:40 UTC, glmnet commented on tests/test1.yaml.save
> +esphome:
what's this file? save?

2020-06-07 00:40 UTC, glmnet commented on tests/max7219.yaml
> +esphome:
just an entry on any of the test123.yaml files is ok, we don't use this, all we validate is the cpp code is compiled ok

2020-06-07 00:40 UTC, glmnet commented on esphome/components/max7219digit/max7219digit.cpp
> +  // ESP_LOGCONFIG(TAG, "  Offset: %u", this->offset_chips_);
we is commented? is it going to be added in the future?

2020-06-13 16:28 UTC, rspaargaren commented on tests/test1.yaml.save
> +esphome:
no use is removed

2020-06-13 16:30 UTC, rspaargaren commented on esphome/components/max7219digit/max7219digit.cpp
> +  // ESP_LOGCONFIG(TAG, "  Offset: %u", this->offset_chips_);
No this was left over from past, removed

2020-06-13 16:34 UTC, rspaargaren commented on esphome/components/max7219digit/display.py
> +    cv.Optional(CONF_ROTATE_CHIP, default='CONT'): cv.enum(CHIP_MODES, upper=True),
changed to 0

2020-06-14 11:48 UTC, rspaargaren commented on esphome/components/max7219digit/display.py
> +    'CONT': 0,
done

2020-06-14 16:23 UTC, rspaargaren commented on tests/max7219.yaml
> +esphome:
entry has been added to test3.yaml

2020-06-14 20:59 UTC, glmnet commented
@igg I'm checking this component and it works with CS_PIN set, this code does not seem to do anything with the cs_pin explicitely, so I just tested it with the cs_pin to gnd and to +vcc and none of them works, it only works if it is connected.
This PR is ok because is requesting the cs pin to be connected, but I'm wondering if we didn't something wrong by changing other components too.

2020-06-14 23:01 UTC, glmnet requested changes
Try all your methods which are in your docs, the one of the image does not work, some lines are rendered off buffer. I'm not going to add review on docs yet, but there are changes needed too.

2020-06-15 11:13 UTC, rspaargaren commented on esphome/components/max7219digit/max7219digit.cpp
> +  if (this->invert_) {
I don't fully understand your remark. Why should I use the color info for drawing a pixel? In the display buffer the Draw pixel routine in only called if a pixel has to be drawn. And the max7219 draws a pixel independently of the color as it has no gradient... The routine works...

2020-06-15 11:16 UTC, rspaargaren commented on esphome/components/max7219digit/max7219digit.cpp
> +    this->send64pixels(i, pixels);  // Send the data to the chip
Some of the not always logic spaces etc is to keep travis happy...
I can remove some commend, but to my opinion they are usefull to understand what is happening for future editing...?
I will check in the invert routine. This did not have to much focus

2020-06-15 15:08 UTC, glmnet commented
Try the image example.  The smiley

2020-06-15 17:33 UTC, igg commented
> This PR is ok because is requesting the cs pin to be connected, but I'm wondering if we didn't something wrong by changing other components too.

If there is no writing to the CS pin, then how can it matter if it is connected to ground or connected to a pin which is set to output 0. It's probably worth trying to figure out why it makes a difference.
Some pins on the ESP undergo a transition from reset/boot to running code. Does the max7219 datasheet say anything about required transitions on the CS pin like the as3935?

2020-06-15 21:17 UTC, rspaargaren commented
> Try the image example. The smiley

Yes, understood. Indeed removed the color during coding not realizing that a image was actually using it... repaired it in the current code.

Invert work now simple but the code needs some clean up...

2020-06-15 21:18 UTC, rspaargaren commented on esphome/components/max7219digit/max7219digit.cpp
> +  if (this->invert_) {
See remark below. Repaired did not use those function for a while.

2020-06-15 21:19 UTC, rspaargaren commented on esphome/components/max7219digit/max7219digit.cpp
> +void MAX7219Component::invert_on_off(bool on_off) {
Will clean up the invert code. As routine is now simple and does not require these codes

2020-06-15 21:21 UTC, rspaargaren commented
> Try all your methods which are in your docs, the one of the image does not work, some lines are rendered off buffer. I'm not going to add review on docs yet, but there are changes needed too.

Can you give me a hint what needs to be changed on the docs. So I can work on that in parallel...

2020-06-15 21:25 UTC, glmnet commented
I’ve already made some changes. 
But the examples are wrong. 
Let me comment there ...

2020-06-16 20:14 UTC, rspaargaren commented on esphome/components/max7219digit/max7219digit.cpp
> +    this->send64pixels(i, pixels);  // Send the data to the chip
I have cleaned up a bit but most of the formatting is dictated by travis to make it pass

2020-06-16 20:15 UTC, rspaargaren commented on esphome/components/max7219digit/max7219digit.cpp
> +void MAX7219Component::invert_on_off(bool on_off) {
invert code is now very simple and buffer is just buffer. Thanks for point me on that.

2020-06-16 20:15 UTC, rspaargaren commented on esphome/components/max7219digit/max7219digit.cpp
> +  if (this->invert_) {
The color bit 1 or 0 is now used for writing the buffer as it is supposed to do...

2020-06-26 23:30 UTC, glmnet requested changes
Please also check my comments on the docs, PR.
It's almost there!!!

2020-06-27 19:45 UTC, rspaargaren commented on .gitignore
> +.gitignore
I have reverted the changes to .gitignore

2020-06-27 19:46 UTC, rspaargaren commented
> Please also check my comments on the docs, PR.
> It's almost there!!!

Yes hopefully final round ;-)

2020-06-28 20:33 UTC, merged