Vl53 long range
OttoWinter/esphomeyaml pull request #1055
Opened 2020-05-10 20:52 UTC by rspaargaren

## Description:

**Related issue (if applicable):** fixes 
https://github.com/esphome/feature-requests/issues/724#

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> Will be submitted

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-05-27 13:30 UTC, rradar approved these changes

2020-06-07 02:36 UTC, glmnet commented
can you check the test yaml changes? they don't seem related to this sensor

2020-06-07 02:37 UTC, glmnet requested changes

2020-06-07 02:37 UTC, glmnet commented on tests/test2.yaml
> +  on_ble_advertise:
unrelated

2020-06-07 02:37 UTC, glmnet commented on tests/test1.yaml
> +    on_turn_on:
unrelated

2020-06-14 17:04 UTC, rspaargaren commented on tests/test2.yaml
> +  on_ble_advertise:
changes are indeed unrelated and due to github push and pulls. Removed

2020-06-14 17:05 UTC, rspaargaren commented on tests/test1.yaml
> +    on_turn_on:
changes are unrelated and due to github push and pulls removed

2020-06-14 23:43 UTC, glmnet commented
cc @rradar 

 I was about to ask @rspaargaren to test my change but I see here https://github.com/esphome/feature-requests/issues/724 he doesn't have the device either.

I've just pushed a commit which takes into account the signal_rate_limit, seems like it was not initialized which could cause unexpected behavior.

So if @rradar can test everything works ok (both with long_range true and false) then I'll merge this which also fixes that bug

2020-06-18 04:55 UTC, rspaargaren commented
@glmnet I have ordered one at Ali. So couple of weeks and I can test for myself.

2020-06-27 20:58 UTC, rspaargaren commented
> @glmnet I have ordered one at Ali. So couple of weeks and I can test for myself.

@randybb / @Svrbinek / @onlineguz

Is one of you able to test this part of the code?

2020-06-28 15:04 UTC, rradar commented
Just tested with custom_component and the [latest code](https://github.com/rspaargaren/esphome/tree/VL53-long-range) on 1.14.5 but now I get this:

```yaml
Failed config

sensor.vl53l0x: [source vl53l0x.yaml:28]
  platform: vl53l0x
  name: ToF Distance
  update_interval: 10s
  
  [long_range] is an invalid option for [sensor.vl53l0x]. Did you mean [on_value_range]?
  long_range: True
```

compiling without long_range works like expected

2020-06-28 15:14 UTC, rradar reviewed
works like expected when set to `true` or `false`

2020-06-28 15:15 UTC, rradar approved these changes

2020-06-28 16:07 UTC, rspaargaren commented
Tnx! Good to hear now I saw in other request to set the i2c adres

2020-06-28 21:47 UTC, merged