Add MCP3008
OttoWinter/esphomeyaml pull request #1057
Opened 2020-05-12 21:54 UTC by SenexCrenshaw

## Description:
Added support for MCP3008. There is a component for the SPI device and then the inputs are used as sensors. Example:
spi:
  clk_pin: D5
  miso_pin: D6
  mosi_pin: D7
  
mcp3008:
  - id: 'mcp3008_hub'
    cs_pin: D8

sensor:
  - platform: mcp3008
    update_interval: 1s
    mcp3008: 'mcp3008_hub'
    id: freezer_temp_source
    name: "Freezer Temp"
    number: 0
  - platform: mcp3008
    update_interval: 1s
    mcp3008: 'mcp3008_hub'
    name: "FridgeTmep"
    number: 1
  - platform: resistance
    id: resistance_sensor
    sensor: freezer_temp_source
    configuration: DOWNSTREAM
    resistor: 10kOhm
    name: Resistance Sensor
  - platform: ntc
    id: freezer_temp
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: NTC Temperature

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#591

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-05-19 02:40 UTC, glmnet requested changes

2020-05-19 02:40 UTC, glmnet commented on esphome/components/mcp3008/mcp3008.cpp
> +void MCP3008Sensor::setup() { ESP_LOGCONFIG(TAG, "Setting up MCP3008 Sensor '%s'...", this->get_name().c_str()); }
Use LOG_SENSOR here, see https://github.com/esphome/esphome/blob/4f2e2fa297070e4d7f55a37175359f4d8f74c0f0/esphome/components/adc/adc_sensor.cpp#L26-L26

2020-05-20 17:50 UTC, SenexCrenshaw commented on esphome/components/mcp3008/mcp3008.cpp
> +void MCP3008::dump_config() { LOG_PIN("  CS Pin: ", this->cs_); }
Would this work? I only need a cs pin

void MCP3008::dump_config() {
  ESP_LOGCONFIG(TAG, "MCP3008:");
  LOG_PIN("  CS Pin: ", this->cs_);
}

2020-05-28 19:03 UTC, SenexCrenshaw commented
Is there anything else you need me to do?

2020-06-15 01:42 UTC, merged