MCP23SXX I/O Expander - SPI
OttoWinter/esphomeyaml pull request #1068
Opened 2020-05-20 12:44 UTC by SenexCrenshaw

## Description:
SPI versions of the MCP230xx I/O Expander. Was thinking I could write a base class and then modify the devices to match but i cant test all the devices and i figured to leave his code alone. I did however mirror it as much as possible for folks to not relearn different approaches if they need to dig into the code.

I also added 10MHZ to the SPI speeds. theses devices can easily handle that even at their lowest min voltage.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-10-13 09:28 UTC, Sabesto commented
Confirmed working on a PRODINo ESP32 Ethernet with mcp23s08

2020-10-13 09:39 UTC, AdamN1 commented
@Sabesto will you resolve conflicts in this PR so we can marge this to master?

2020-10-14 11:56 UTC, SenexCrenshaw commented
Sorry. for the delay! I will work on this today/tomorrow.

2020-10-15 12:19 UTC, Sabesto commented
> Sorry. for the delay! I will work on this today/tomorrow.
> 
> I have added a mcp3008 module in esphome as well and added a reference voltage line. Basically it returns the voltage value mimicking the ADC component in esphome ( value_v = (value_v * this->reference_voltage_) / 1023;) Ill add it to this one as well.

One PR for each component would make more sense

> Last thing. What exactly do you want to test? A yaml file and that the code generated compiles? If so where do you want this? any examples?

Look at my PR: esphome/esphome#1324 specifically tests/test1.yaml

2020-10-15 17:46 UTC, Sabesto commented on esphome/components/mcp23S08/__init__.py
> +mcp23S08_ns = cg.esphome_ns.namespace('mcp23S08')
I think namespace should be lowercase, mcp23s08, not mcp23S08

2020-10-23 11:48 UTC, SenexCrenshaw commented on esphome/components/mcp23S08/__init__.py
> +mcp23S08_ns = cg.esphome_ns.namespace('mcp23S08')
ill have a more robust patch in today or tomorrow. clearly i wont be doing the ref voltage thing since these are digital and not ADC....

2020-11-20 09:27 UTC, jesserockz requested changes
A few changes to line up with other pin devices please

2020-11-20 09:27 UTC, jesserockz commented on esphome/components/mcp23s08/mcp23s08.cpp
> +  ESP_LOGCONFIG(TAG, "  CS Pin: %u", this->cs_->get_pin());
```suggestion
  LOG_PIN("  CS Pin: ", this->cs_);
```

2020-11-20 09:27 UTC, jesserockz commented on esphome/components/mcp23s17/__init__.py
> +    yield mcp23S17GPIOPin.new(parent, config[CONF_NUMBER], config[CONF_MODE], config[CONF_INVERTED])
The `..._PIN_SCHEMA`s do not use an `_ID` suffix

```suggestion
CONF_MCP23S17 = 'mcp23s17'

mcp23S17_OUTPUT_PIN_SCHEMA = cv.Schema({
    cv.GenerateID(CONF_MCP23S17): cv.use_id(mcp23S17),
    cv.Required(CONF_NUMBER): cv.int_,
    cv.Optional(CONF_MODE, default="OUTPUT"): cv.enum(mcp23S17_GPIO_MODES, upper=True),
    cv.Optional(CONF_INVERTED, default=False): cv.boolean,
})
mcp23S17_INPUT_PIN_SCHEMA = cv.Schema({
    cv.Required(CONF_MCP23S17): cv.use_id(mcp23S17),
    cv.Required(CONF_NUMBER): cv.int_range(0, 15),
    cv.Optional(CONF_MODE, default="INPUT"): cv.enum(mcp23S17_GPIO_MODES, upper=True),
    cv.Optional(CONF_INVERTED, default=False): cv.boolean,
})


@pins.PIN_SCHEMA_REGISTRY.register(CONF_MCP23S17,
                                   (mcp23S17_OUTPUT_PIN_SCHEMA, mcp23S17_INPUT_PIN_SCHEMA))
def mcp23S17_pin_to_code(config):
    parent = yield cg.get_variable(config[CONF_MCP23S17])
    yield mcp23S17GPIOPin.new(parent, config[CONF_NUMBER], config[CONF_MODE], config[CONF_INVERTED])
```

2020-11-20 09:27 UTC, jesserockz commented on esphome/components/mcp23s08/__init__.py
> +    yield mcp23S08GPIOPin.new(parent, config[CONF_NUMBER], config[CONF_MODE], config[CONF_INVERTED])
The `..._PIN_SCHEMA`s do not use an `_ID` suffix

```suggestion
CONF_MCP23S08 = 'mcp23s08'

mcp23S08_OUTPUT_PIN_SCHEMA = cv.Schema({
    cv.GenerateID(CONF_MCP23S08): cv.use_id(mcp23S08),
    cv.Required(CONF_NUMBER): cv.int_,
    cv.Optional(CONF_MODE, default="OUTPUT"): cv.enum(mcp23S08_GPIO_MODES, upper=True),
    cv.Optional(CONF_INVERTED, default=False): cv.boolean,
})
mcp23S08_INPUT_PIN_SCHEMA = cv.Schema({
    cv.GenerateID(CONF_MCP23S08): cv.use_id(mcp23S08),
    cv.Required(CONF_NUMBER): cv.int_range(0, 7),
    cv.Optional(CONF_MODE, default="INPUT"): cv.enum(mcp23S08_GPIO_MODES, upper=True),
    cv.Optional(CONF_INVERTED, default=False): cv.boolean,
})


@pins.PIN_SCHEMA_REGISTRY.register(CONF_MCP23S08,
                                   (mcp23S08_OUTPUT_PIN_SCHEMA, mcp23S08_INPUT_PIN_SCHEMA))
def mcp23S08_pin_to_code(config):
    parent = yield cg.get_variable(config[CONF_MCP23S08])
    yield mcp23S08GPIOPin.new(parent, config[CONF_NUMBER], config[CONF_MODE], config[CONF_INVERTED])
```

2020-11-20 09:27 UTC, jesserockz commented on esphome/components/mcp23s17/mcp23s17.cpp
> +  ESP_LOGCONFIG(TAG, "  CS Pin: %u", this->cs_->get_pin());
```suggestion
  LOG_PIN("  CS Pin: ", this->cs_);
```

2020-11-20 09:27 UTC, jesserockz commented on tests/test1.yaml
> +      mcp23s08_id: mcp23s08_hub
```suggestion
      mcp23s08: mcp23s08_hub
```

2020-11-20 09:27 UTC, jesserockz commented on tests/test1.yaml
> +      mcp23s17_id: mcp23s17_hub
```suggestion
      mcp23s17: mcp23s17_hub
```

2020-11-20 09:27 UTC, jesserockz commented on tests/test1.yaml
> +      inverted: False
```suggestion
    pin:
      mcp23s08: mcp23s08_hub
      # Use pin number 0
      number: 0
      mode: OUTPUT
      inverted: False
```

2020-11-20 09:27 UTC, jesserockz commented on tests/test1.yaml
> +      mcp23s17_id: mcp23s17_hub
```suggestion
      mcp23s17: mcp23s17_hub
```

2020-11-24 14:23 UTC, SenexCrenshaw commented on esphome/components/mcp23s08/mcp23s08.cpp
> +  ESP_LOGCONFIG(TAG, "  CS Pin: %u", this->cs_->get_pin());
Ok

2020-11-24 14:27 UTC, SenexCrenshaw commented on esphome/components/mcp23s08/__init__.py
> +    yield mcp23S08GPIOPin.new(parent, config[CONF_NUMBER], config[CONF_MODE], config[CONF_INVERTED])
Ok!

2020-11-24 14:35 UTC, SenexCrenshaw commented
@jesserockz Thanks for the tips. I committed your changes and appreciate the help!

2020-11-24 18:41 UTC, jesserockz approved these changes
Looks good, thanks

2020-12-06 17:43 UTC, merged

2020-12-27 11:18 UTC, Melkor82 commented
@SenexCrenshaw can you make the spi speed an option to configure? Now it is configured as DATA_RATE_10MHZ but i would like to try to reach bigger distances using lower speed rate

2020-12-31 17:17 UTC, SenexCrenshaw commented
@Melkor82 I dont believe that can be changed from a configuration. Id suggest downloading the git repo and modifying to your needs. 
@jesserockz  @glmnet  - Am I correct? SPI speeds cant be changed, right?

2020-12-31 17:40 UTC, glmnet commented
I don't know of any spi component which would allow to do that. Sounds like a core requirement to support this

2021-02-03 22:43 UTC, makkie2002 commented
> Confirmed working on a PRODINo ESP32 Ethernet with mcp23s08

That is really fantastisch! I was hoping for this integration. I also have a Prodino. Can you please post an example of a working configuration file so that I can get started. Thanks!

2021-02-04 17:54 UTC, SenexCrenshaw commented
This was added to the latest release. Here are the docs
https://esphome.io/components/mcp23sxx