Nextion sensor and switch
OttoWinter/esphomeyaml pull request #1079
Opened 2020-06-01 20:26 UTC by rspaargaren

## Description:

**Related issue (if applicable):** fixes:
https://github.com/esphome/feature-requests/issues/201
https://github.com/esphome/feature-requests/issues/91

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-06-01 20:32 UTC, rspaargaren commented
Readme will be converted into documentation

2020-06-01 20:34 UTC, rspaargaren commented
@glmnet Can you have a quick look if this basis is OK. If so I will prepare documentation.

2020-07-13 21:06 UTC, OttoWinter commented on esphome/components/nextion/display.py
> +AUTO_LOAD = ['sensor']
This would need to be
```suggestion
AUTO_LOAD = ['switch', 'sensor']
```
with the current syntax you're just redefining the variable

2020-07-13 21:07 UTC, OttoWinter commented on esphome/components/nextion/nextion.cpp
> +  // }
No commented out code please (or put a reason for why it might be needed later at the top of the comment)

2020-07-13 21:07 UTC, OttoWinter commented on esphome/components/nextion/README.md
> +In this way the binary sensor registers the state of the button instead of registering the actual push.
This should go in the esphome-docs repository instead (even if it's not 100% complete yet, but here nobody will find it)

2020-07-30 20:54 UTC, gitolicious reviewed
I was just looking for this feature today... After seeing that currently only sending data to the display is possible I was close to ditching ESPHome for my upcoming Nextion project, but this PR might be a reason to stay.

2020-07-30 20:54 UTC, gitolicious commented on esphome/components/nextion/README.md
> +printh 90 <-- 90 is special code I created to register feedback from witch
small typo
```suggestion
printh 90 <-- 90 is special code I created to register feedback from switch 
```

2020-07-30 20:54 UTC, gitolicious commented on esphome/components/nextion/nextion.cpp
> +      case 0x89:    // start SD card upgrade
Need to break here as otherwise `0x90` instructions will be called
```suggestion
      case 0x89:    // start SD card upgrade
        break;
```

2020-07-30 20:54 UTC, gitolicious commented on esphome/components/nextion/nextion.cpp
> +      case 0x70:    // string variable data return
Any idea how we could get the variable from Nextion and store it in a text sensor? Maybe a periodic poll as it is done with the lambda?

2020-07-30 20:54 UTC, gitolicious commented on esphome/components/nextion/nextion.cpp
> +      case 0x86:    // device automatically enters into sleep mode
Can we add a trigger option for this?
```
display:
  - platform: nextion
      on_sleep:
        [...]
      on_wake:
        [...]
```

2020-07-30 20:57 UTC, rspaargaren commented on esphome/components/nextion/nextion.cpp
> +      case 0x86:    // device automatically enters into sleep mode
Hi I was just getting into finalizing this PR as it has been open for a while.
I will look into your request as well!

2020-07-30 20:58 UTC, rspaargaren commented
@gitolicious Hi I will work on this PR in the comming days to finalize and take your input into account.

2020-07-31 05:35 UTC, gitolicious commented
Great to hear you are still working on this. Once I understood the code better, maybe I can contribute some parts as well. Until then I am happy to assist with testing and functional reviews.

2020-08-01 18:13 UTC, gitolicious commented
I saw you are using custom codes outside the standard [Nextion Instruction Set](https://nextion.tech/instruction-set/) specification. In my previous implementations I did the same for sending arbitrary strings from the display to the host. As I was too lazy to mess around with component IDs in my code, I simply sent easily parsable JSON like the following
```
printh 74
print "{\"event\":\"button\",\"obj\":\"bMyButton\"}"
printh ff ff ff
```
This could be assigned an Input Text or made available via a trigger. What are your thoughts about it?

2020-08-02 19:38 UTC, rspaargaren commented
> I saw you are using custom codes outside the standard [Nextion Instruction Set](https://nextion.tech/instruction-set/) specification. In my previous implementations I did the same for sending arbitrary strings from the display to the host. As I was too lazy to mess around with component IDs in my code, I simply sent easily parsable JSON like the following
> 
> ```
> printh 74
> print "{\"event\":\"button\",\"obj\":\"bMyButton\"}"
> printh ff ff ff
> ```
> 
> This could be assigned an Input Text or made available via a trigger. What are your thoughts about it?

Hi, I think we should try to stay as much as possible to the core of nextion and use little or preferable no code to program the nextion. Although it would make live much more easy on the esp side...!

2020-08-02 20:03 UTC, rspaargaren commented on esphome/components/nextion/nextion.cpp
> +      case 0x89:    // start SD card upgrade
No need to break here, there is no action in 0x89 so we just skip over to 0x90 case

2020-08-02 20:10 UTC, rspaargaren commented on esphome/components/nextion/nextion.cpp
> +      case 0x70:    // string variable data return
In what cases do you need to get the string back and send it in a text sensor? Text shown in the nextion is fed by the esp, and already known? 
Of course I can create a text-sensor in the same way as I have enable a sensor / switch.

2020-08-02 20:19 UTC, gitolicious commented
> I think we should try to stay as much as possible to the core of nextion and use little or preferable no code to program the nextion. Although it would make live much more easy on the esp side...!

Totally with you on this one. We should stick to the defaults wherever possible. But only getting object IDs and not even object names made it really cumbersome to work with the displays from day one to me. So a single extension of the protocol for arbitrary  strings was the least intrusive, most flexible solution I could come up with.

2020-08-02 20:21 UTC, rspaargaren commented
> > I think we should try to stay as much as possible to the core of nextion and use little or preferable no code to program the nextion. Although it would make live much more easy on the esp side...!
> 
> Totally with you on this one. We should stick to the defaults wherever possible. But only getting object IDs and not even object names made it really cumbersome to work with the displays from day one to me. So a single extension of the protocol for arbitrary strings was the least intrusive, most flexible solution I could come up with.

2020-08-02 21:11 UTC, rspaargaren commented on esphome/components/nextion/nextion.cpp
> +      case 0x86:    // device automatically enters into sleep mode
I dont think the on sleep and on wake will be possible with the current code of ESP to trigger. But we could attach a switch or binary sensor to the sleep statement. Then you can connect the action to this sensor.

2020-08-03 05:07 UTC, gitolicious commented on esphome/components/nextion/nextion.cpp
> +      case 0x86:    // device automatically enters into sleep mode
Fine for me. I just saw it being used with other devices and thought it would be a nice interface. Switch or binary sensor is totally fine.

2020-08-08 09:47 UTC, gitolicious commented on esphome/components/nextion/nextion.cpp
> +      case 0x70:    // string variable data return
Depending on implementation, variable values can also be set by the logic within the display.

2020-10-25 20:05 UTC, Andoramb commented
How nice! as soon as this is merged, I'll also start updating my project 👍 Thanks guys

2020-10-26 06:32 UTC, gitolicious commented
Unfortunately no activity by @rspaargaren in the last weeks... I am unsure if this is ready to be merged.

2020-11-07 11:37 UTC, rspaargaren commented
> Unfortunately no activity by @rspaargaren in the last weeks... I am unsure if this is ready to be merged. 

Hi yes let me have a look on it and try to push for a merge. Lost a bit of focus on this one but should be (almost) ready to merge!

2020-11-22 10:57 UTC, jesserockz requested changes
A few changes below please. Also would like to hear from @ssieb on this.

2020-11-22 10:57 UTC, jesserockz commented on esphome/components/nextion/nextion.cpp
> +      case 0x89:    // start SD card upgrade
I think this break should be there. We don't want 0x90 code to be executed for the previous commands

2020-11-22 10:57 UTC, jesserockz commented on esphome/components/nextion/nextion.cpp
> +  // }
Please address this @rspaargaren

2020-11-22 10:57 UTC, jesserockz commented on esphome/components/nextion/nextion.cpp
> +  // this->loop();
Please delete it this is not needed

2020-11-22 10:57 UTC, jesserockz commented on esphome/components/nextion/nextion.cpp
> +    ESP_LOGW(TAG, "Sensor state published");
This probably should not be a warning log. Please change to debug or verbose. Sensor state changes are already logged by the base sensor class too

2020-11-22 10:57 UTC, jesserockz commented on esphome/components/nextion/switch.py
> +CONF_NEXTION_ID = 'nextion_id'
Can we move this to the `__init__.py` file please and reuse?

2020-11-22 11:53 UTC, rspaargaren commented on esphome/components/nextion/nextion.cpp
> +    ESP_LOGW(TAG, "Sensor state published");
Correct, changed it to Debug info.

2020-11-22 11:53 UTC, rspaargaren commented on esphome/components/nextion/nextion.cpp
> +  // this->loop();
Correct, deleted

2020-11-22 11:58 UTC, rspaargaren commented on esphome/components/nextion/nextion.cpp
> +  // }
Commented code removed. Command is sent without ACK so code to catch ACK is not required.

2020-11-22 17:39 UTC, rspaargaren commented on esphome/components/nextion/nextion.cpp
> +      case 0x89:    // start SD card upgrade
Yes you are right, I will insert the break.

2020-11-22 18:12 UTC, rspaargaren commented on esphome/components/nextion/switch.py
> +CONF_NEXTION_ID = 'nextion_id'
Ok CONF_NEXTION_ID = 'nextion_id' has been moved to init.py for the binary, switch & sensor.py

2021-07-28 03:46 UTC, jesserockz commented
@rspaargaren  can this be closed because #1464 was merged?

2021-07-28 09:55 UTC, rspaargaren commented
This PR can be closed. The PR of Senex has been integrated.

2021-07-28 10:17 UTC, closed without merging