Use suitably scoped char for log newline stripping
OttoWinter/esphomeyaml pull request #1098
Opened 2020-06-22 03:42 UTC by buxtronix

Fixes a crash that sometimes occurs in this function.

The FORMAT_COPY variable is declared static, however it gets referenced across threads of the underlying freertos code. This is unsafe usage, leading to the type of crash shown below. Instead malloc space per call.

WARNING Decoded 0x40092094: invoke_abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:707
WARNING Decoded 0x400922c5: abort at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:707
WARNING Decoded 0x4008e0c7: xQueueCreateCountingSemaphore at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:2520
WARNING Decoded 0x4011d689: static_init_prepare() at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/cxx/cxx_guards.cpp:56
WARNING Decoded 0x4011d6d6: __cxa_guard_acquire at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/cxx/cxx_guards.cpp:134
WARNING Decoded 0x400ddc0c: esphome::esp_idf_log_vprintf_(char const*, __va_list_tag) at /config/esphome/atom1/src/esphome/core/log.cpp:59 (discriminator 1)
WARNING Decoded 0x4008453e: esp_log_write at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/log/log.c:215
WARNING Decoded 0x400fb495: _mdns_send_rx_action at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/mdns/mdns.c:4526
WARNING Decoded 0x400fd521: _udp_recv at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/mdns/mdns_networking.c:169
WARNING Decoded 0x4013fb5d: udp_input at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/core/udp.c:401
WARNING Decoded 0x40144bd5: ip4_input at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/core/ipv4/ip4.c:740
WARNING Decoded 0x40149ebe: ethernet_input at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/netif/ethernet.c:184
WARNING Decoded 0x40135733: tcpip_thread at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/lwip/lwip/src/api/tcpip.c:483
WARNING Decoded 0x4008e7dd: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)

2020-06-23 01:00 UTC, glmnet commented
Have you considered using a critical section instead?

2020-06-23 01:50 UTC, buxtronix commented
> Have you considered using a critical section instead?

Happy to test and report back. Why would this be preferred here? Memory fragmentation?

2020-06-23 02:16 UTC, glmnet commented
Ohh, it was actually more a question. I really don't like much doing malloc/new when it can be avoided.
Also we assume the underlying function is thread safe, but it's going to use some kind of sync at the end.

2020-06-23 02:39 UTC, buxtronix commented
So I just tried wrapping with a portENTER_CRITICAL / portEXIT_CRITICAL...and got the original crash.

So it's not quite something of this type of concurrency problem. After restoring with the malloc/free, the code is stable again.

I do still suspect there's a bunch of concurrency problems with BLE enabled. Probably because without it we're effectively single-threaded with the Wifi radio, but BLE provides for extra callback/interrupt points.
So it might not quite be re-entrant behaviour in this static string at this point, though this PR makes things much more stable than before anyway.

2020-06-24 12:38 UTC, buxtronix commented
So it turns out not to be a concurrency issue at all, but plain old memory exhaustion, seems to be from MDNS.

See https://github.com/esphome/issues/issues/1234 for details. The solution here addresses it (gracefully handles the malloc failing), though the cause is different.

2020-06-24 13:22 UTC, glmnet requested changes
I don't like it doing malloc everytime, see old code does it only when string ends in `\n`

If you're going to swallow the messages when you cannot log them, may be it will be nice to log it with the unmodified message which includes the `\n` it might not look nice but there will be still info available.

Also per your comments this method seems not to be used much unless esp itself wants to log something? how ugly will it be to just let `\n` print? Is this affecting api/mqtt logs too or just serial logs? if the latter I'd vote to just log all with the `\n` 

Unless the problem is inside the vprintf function and your malloc is mostly kind of a guarantee that if it succeeds the  vprintf won't crash, but I don't know.

2020-06-24 23:53 UTC, buxtronix commented
If I remove all of the newline stripping code, and trigger a crash with the MDNS packets, the results are mixed.

For serial-only logging, I get this (basically logs ok but with the extra blank line)

[08:25:54][D][esp-idf:000]: E (192187) MDNS: Cannot allocate memory (line: 2571, free heap: 368 bytes)
[08:25:54]
[08:25:54][D][esp-idf:000]: E (192190) MDNS_Networking: Cannot allocate memory (line: 123, free heap: 380 bytes)
[08:25:54]
[08:25:54][D][esp-idf:000]: E (192198) MDNS_Networking: Cannot allocate memory (line: 123, free heap: 380 bytes)
[08:25:54]

However API logging causes it to crash, due to failure in the API code allocating memory. The AP connection just drops without any messages, but the OOM is logged over serial:

[D][esp-idf:000]: E (1636473) MDNS_Networking: Cannot allocate memory (line: 123, free heap: 264 bytes)

[D][esp-idf:000]: E (1636475) lwip_arch: thread_sem_init: out of memory

[D][esp-idf:000]: E (1636481) lwip_arch: thread_sem_init: out of memory

[D][esp-idf:000]: E (1636488) lwip_arch: thread_sem_init: out of memory

ets Jun  8 2016 00:22:57

rst:0x8 (TG1WDT_SYS_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4

So any attempt to log OOM will always fail over API as there's a lot of places in the code where
memory is allocated.

So we are left with a few options:

1. Use the changes in the PR here, but all IDF-logged OOMs will be suppressed.
2. Just not strip newline. But then there will be a crash if any API clients are logging.
3. Try to identify if an OOM is being logged and suppress API logging (hackish, needs string matching).
4. Check free heap and if too low, suppress any API logging (but keep serial).

I'm leaning towards combining (2) and (4). Implementing 4 is just a matter of adding a heap check
prior to the API logger callback. In logger.cpp:log_message_:

  if (xPortGetFreeHeapSize() > 2048)
    this->log_callback_.call(level, tag, msg);

I don't think there is any perfect solution, so I think we have to go with whatever allows for stable operation with the simplest changes.

2020-06-25 01:06 UTC, glmnet commented
Excellent job here!! I really don’t know and agree with you. It’d be nice that some logs of warning low memory be there? Or may be leave a comment there pointing to this PR for future reference. 
May be the issue itself is mdns stuff

2020-06-25 04:10 UTC, buxtronix commented
I don't think there is a problem with MDNS per se, but a burst of memory allocations is naturally going to overwhelm a memory constrained device given the right conditions. It's just that MDNS is most liable to do just that here.

I've update the PR to skip non-serial logging when memory constrained. There will still be a serial log though (if enabled).

2020-06-26 22:13 UTC, merged