Adding support for the Inkbird IBS-TH1 Mini sensor
OttoWinter/esphomeyaml pull request #1099
Opened 2020-06-24 03:59 UTC by fkirill

## Description:

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-06-28 22:09 UTC, glmnet requested changes
This is good, docs are ok too, just apply those changes and they'll get added. Thanks!

2020-06-28 22:09 UTC, glmnet commented on .gitignore
> +esp32/
why this?

2020-06-28 22:09 UTC, glmnet commented on esphome/components/inkbird_ibsth1_mini/inkbird_ibsth1_mini.cpp
> +// sss
be quiet :)

2020-06-28 22:09 UTC, glmnet commented on tests/inkbird_ibsth1_mini.yaml
> +        name: "Inkbird IBS-TH1 Battery Level"
move these entries to test1.yaml and delete this file, (this will remove the need for you ignoring the esp32 folder too)
We have just test1..4.yaml so the CI builds those files and the code compilation is checked automatically.

2020-06-28 23:23 UTC, fkirill commented on .gitignore
> +esp32/
When I do `esphome xxx.yaml run` it creates a lot of itermediate files in esp32 folder that is not currently ignored.
What happens is that git UI client that I use shows lots and lots of files added to the work tree.
Seems like it is a mistake not to include `esp32` to the .gitignore.

2020-06-28 23:27 UTC, fkirill commented on esphome/components/inkbird_ibsth1_mini/inkbird_ibsth1_mini.cpp
> +// sss
oopsie... Sorry for that.
Actually forgot to rename a couple of things.

2020-06-28 23:29 UTC, fkirill commented on tests/inkbird_ibsth1_mini.yaml
> +        name: "Inkbird IBS-TH1 Battery Level"
right, okay. Will do.

2020-06-28 23:50 UTC, glmnet commented on .gitignore
> +esp32/
that folder is named after your node name in your test file

```
esphome:
  name: esp32 # <-- this value gives the folder name
```

if you want, you can put your custom yaml in the config folder which is already ignored for this purpose

2020-06-30 01:39 UTC, fkirill commented on .gitignore
> +esp32/
Oh, I see... It seems to be a bit counterintuitive. if it was me, I would probably create this under some pre-ignored directory. But anyways, removing for now.

2020-10-04 07:28 UTC, jesserockz approved these changes

2020-10-05 22:54 UTC, fkirill commented
> This is good, docs are ok too, just apply those changes and they'll get added. Thanks!

Sorry, missed it, what do you mean by "apply those changes"? What changes?

2020-10-06 10:42 UTC, dcec commented
Working also with IBT-6X?

2021-01-07 23:14 UTC, caesar1987sk commented
Are you still working on this? I'm thinking about buying some od these sensors when they will be available to use with esphome.

2021-01-10 20:12 UTC, jesserockz requested changes

2021-01-10 20:12 UTC, jesserockz commented on esphome/components/inkbird_ibsth1_mini/sensor.py
> +DEPENDENCIES = ['esp32_ble_tracker']
Please add youself to the CODEOWNERS and then run `script/build_codeowners.py`

```suggestion
CODEOWNERS = ['@fkirill']
DEPENDENCIES = ['esp32_ble_tracker']
```

2021-02-01 06:36 UTC, fkirill commented on esphome/components/inkbird_ibsth1_mini/sensor.py
> +DEPENDENCIES = ['esp32_ble_tracker']
Hey Jesse, added CODEOWNERS, regenerated the codeowners index.

2021-02-01 17:59 UTC, jesserockz approved these changes

2021-02-01 18:27 UTC, glmnet approved these changes
just some cosmetic details

2021-02-01 18:27 UTC, glmnet commented on esphome/components/inkbird_ibsth1_mini/inkbird_ibsth1_mini.cpp
> +  // It i sentirely possible that some of that may be inaccurate or incomplete
```suggestion
  // It is entirely possible that some of that may be inaccurate or incomplete
```

2021-02-01 18:27 UTC, glmnet commented on esphome/components/inkbird_ibsth1_mini/inkbird_ibsth1_mini.cpp
> +  esphome::esp32_ble_tracker::ServiceData mnfData = device.get_manufacturer_datas()[0];
does it really need `esphome` for namespace?
you could also use `auto`
```suggestion
  esp32_ble_tracker::ServiceData mnfData = device.get_manufacturer_datas()[0];
```

2021-02-01 18:27 UTC, glmnet commented on esphome/components/inkbird_ibsth1_mini/inkbird_ibsth1_mini.cpp
> +  if (device.get_manufacturer_datas().size() != 1) {
can get the value in a local here so don't call the method twice

2021-02-02 22:00 UTC, fkirill commented on esphome/components/inkbird_ibsth1_mini/inkbird_ibsth1_mini.cpp
> +  if (device.get_manufacturer_datas().size() != 1) {
Sure.
The method just returns a structure member, I would imagine the compiler would inline it anyway.

2021-02-06 04:04 UTC, merged