Add MCP9808 temperature sensor
OttoWinter/esphomeyaml pull request #1169
Opened 2020-07-17 07:01 UTC by k7hpn

## Description: Add the MCP9808 temperature sensor.
**Related issue (if applicable):** fixes esphome/feature-requests#214

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-07-17 08:55 UTC, pkuehne commented on esphome/components/mcp9808/mcp9808.cpp
> +  if (!this->read_byte_16(MCP9808_REG_MANUF_ID, &manu, 0) || manu != 0x0054) {
Could these magic numbers `0x0054` also be made constants at the top? That would be a bit more descriptive.

2020-07-17 08:55 UTC, pkuehne commented on esphome/components/mcp9808/mcp9808.cpp
> +  if ((msb & 0x10) == 0x10) {
Here also, a named constant would be clearer as to what is being checked for.

2020-07-17 08:55 UTC, pkuehne commented on esphome/components/mcp9808/mcp9808.cpp
> +  uint8_t msb = (uint8_t)((raw_temp & 0xff00) >> 8);
In C++ code, I would use C++ style casts
```suggestion
  uint8_t msb = static_cast<uint8_t>((raw_temp & 0xff00) >> 8);
```

2020-07-17 08:55 UTC, pkuehne commented on esphome/components/mcp9808/sensor.py
> +    if CONF_TEMPERATURE in config:
Maybe I'm misunderstanding something about the flow, but isn't the *temperature* key required for the sensor?

2020-07-17 12:20 UTC, OttoWinter commented on esphome/components/mcp9808/sensor.py
> +    if CONF_TEMPERATURE in config:
Agree.

If this sensor only provides one measurement value (temperature), then it should not have that in a sub-key. Look for example at `max6675` for an example where the sensor config is together with device config.

2020-07-17 12:21 UTC, OttoWinter commented on esphome/components/mcp9808/mcp9808.cpp
> +  uint8_t msb = (uint8_t)((raw_temp & 0xff00) >> 8);
@pkuehne In pure C++ project's I'd agree, but for ESPHome it's fine. We can't expect all contributors to know C++ perfectly, especially when most do not come from C++ backgrounds.

2020-07-18 03:55 UTC, k7hpn commented on esphome/components/mcp9808/mcp9808.cpp
> +  if (!this->read_byte_16(MCP9808_REG_MANUF_ID, &manu, 0) || manu != 0x0054) {
Thanks for the suggestion, I've made them all constants!

2020-07-18 03:55 UTC, k7hpn commented on esphome/components/mcp9808/sensor.py
> +    if CONF_TEMPERATURE in config:
Thanks so much for the feedback, `max6675` was a good reference. I think I've made these changes!

2020-07-18 03:56 UTC, k7hpn commented on esphome/components/mcp9808/mcp9808.cpp
> +  if ((msb & 0x10) == 0x10) {
I moved as much as I could into named constants so that the code is easier to read.

2020-07-18 04:48 UTC, glmnet requested changes
Some log levels needs updates

2020-07-18 04:48 UTC, glmnet commented on esphome/components/mcp9808/mcp9808.cpp
> +    ESP_LOGCONFIG(TAG, "%s manufacuturer id failed, device returned %X", this->name_.c_str(), manu);
Log error instead of config

2020-07-18 04:48 UTC, glmnet commented on esphome/components/mcp9808/mcp9808.cpp
> +  ESP_LOGCONFIG(TAG, "Setting up %s...", this->name_.c_str());
Log info here

2020-07-18 18:00 UTC, k7hpn commented on esphome/components/mcp9808/mcp9808.cpp
> +    ESP_LOGCONFIG(TAG, "%s manufacuturer id failed, device returned %X", this->name_.c_str(), manu);
Thanks for pointing this out! I've changed these two error conditions during setup to use `LOGE`.

2020-07-18 18:01 UTC, k7hpn commented on esphome/components/mcp9808/mcp9808.cpp
> +  ESP_LOGCONFIG(TAG, "Setting up %s...", this->name_.c_str());
I've changed this logging during setup to use `ESP_LOGI`.

2020-07-23 23:51 UTC, k7hpn commented
Hey @glmnet @OttoWinter let me know if there's anything else I need to do on this!

2020-07-25 02:26 UTC, glmnet commented on esphome/components/mcp9808/mcp9808.cpp
> +  ESP_LOGI(TAG, "Setting up %s...", this->name_.c_str());
```suggestion
  ESP_LOGCONFIG(TAG, "Setting up %s...", this->name_.c_str());
```
Actually this one is config, -- sorry for the back and forth

2020-07-25 02:30 UTC, glmnet approved these changes

2020-08-01 04:17 UTC, k7hpn commented on esphome/components/mcp9808/mcp9808.cpp
> +  if (temp == NAN) {
@OttoWinter thanks so much for the feedback, I appreciate it. I've believe I've fixed this!

2020-10-03 10:11 UTC, mathieu-mp commented on esphome/components/mcp9808/sensor.py
> +}).extend(cv.polling_component_schema('60s')).extend(i2c.i2c_device_schema(0x18))
Hi @k7hpn, any chance you'd provide an optional 'address' configuration variable to override default 0x18 i2c address ?

2020-10-04 15:25 UTC, OttoWinter commented on esphome/components/mcp9808/sensor.py
> +}).extend(cv.polling_component_schema('60s')).extend(i2c.i2c_device_schema(0x18))
@mathieu-mp the i2c_device schema already handles that :)

2020-10-26 18:24 UTC, merged