BLE client support on ESP32
OttoWinter/esphomeyaml pull request #1177
Opened 2020-07-22 06:31 UTC by buxtronix

## Description:

Provides a BLE (Bluetooth Low Energy) client for ESPHome, allowing connecting to many types
of BLE devices and querying values from them. A cookbook example (in the docs pr) is also provided showing
how to use a cheap keyring BLE tag as a binary_sensor.

Video demo: https://youtu.be/YTfGFnJP8y4

Changes made:

- Modify esp32_ble_tracker to handle GATT clients.
- Use an event queue for processing GAP/GATTC events gracefully within loop().
- Update UUID handling.
- Add a ble_client component to manage the connection to a BLE device, including automation for on_connect/on_disconnect
- Allow MULTI_CONF to specify maximum stanzas (esp32 stack has a 3 client limit)
- Add a sensor platform under this for getting/exposing values from a BLE client's services/characteristics, including handling notifications.

Further enhancements are in the pipeline for future PRs:

- Write to BLE characteristics (an output platform)
- Custom devices (am43 blinds, Anova, more)
- Handle LinkLoss behaviour

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ X] The code change is tested and works locally.
  - [ X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-07-31 11:53 UTC, OttoWinter reviewed
Hi, thanks for this PR, this looks like an awesome feature!

I've had a quick look at the changes and added some comments. It would be great if you could review them and implement the changes/explain why it should stay that way.

written from my phone so I might not have caught everything yet.

(alos sorry for commenting with such delay, i understand that can be frustrating)

2020-07-31 11:53 UTC, OttoWinter commented on esphome/components/ble_client/sensor/__init__.py
> +}).extend(cv.polling_component_schema('30s')).extend(ble_client.BLE_CLIENT_SCHEMA))
Is there a reason for using 30s update interval here? ESPHome usually uses 60 seconds, and using a different value cam be confusing to users (and would be a bit inconsistent).

2020-07-31 23:23 UTC, buxtronix commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +            esp_ble_gap_stop_scanning();
So the ESP32 stack cannot connect to a device whilst still scanning. Scanning needs to be stopped first (or wait until scan end, 5 minutes!).

Once the connection is established, scanning resumes for further devices. I typically can get multiple devices connected within a few seconds this way.

2020-08-01 00:05 UTC, buxtronix commented on esphome/components/ble_client/ble_client.h
> +  int gattc_if_;
Actually these need to be accessible by the BLEClientNodes that are children of this class (rather than inheriting from it).

2020-08-01 00:21 UTC, buxtronix commented on tests/test5.yaml
> +substitutions:
Fixed up. I made test5 as the compile failed with too big a binary. But I fixed this with a platformio option.

2020-08-01 00:21 UTC, buxtronix commented on esphome/config.py
> +            if not isinstance(comp.is_multi_conf, bool) and len(conf) > comp.is_multi_conf:
Done

2020-08-01 00:21 UTC, buxtronix commented on esphome/components/esp32_ble_tracker/queue.h
> +  uint8_t notify_data[64];
Done.

2020-08-01 00:21 UTC, buxtronix commented on esphome/components/ble_client/sensor/ble_sensor.h
> +namespace espbt = esphome::esp32_ble_tracker;
Done.

2020-08-01 00:21 UTC, buxtronix commented on esphome/components/ble_client/sensor/ble_sensor.cpp
> +  ESP_LOGCONFIG(TAG, "  Notifications      : %s", this->notify_ ? "yes" : "no");
Done.

2020-08-01 00:22 UTC, buxtronix commented on esphome/components/ble_client/sensor/ble_sensor.cpp
> +        this->publish_state(NAN);
Fixed.

2020-08-01 00:22 UTC, buxtronix commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +    delete[] ble_event;
Fixed.

2020-08-01 00:22 UTC, buxtronix commented on esphome/components/ble_client/sensor/__init__.py
> +CONF_CHAR_UUID = 'char_uuid'
Done.

2020-08-01 00:25 UTC, buxtronix commented on esphome/components/ble_client/__init__.py
> +MULTI_CONF = 3
I added a comment. Basically the espressif-idf ESPHome uses is compiled with BLE_MAX_CONN set to 3. Which may be a memory issue (it's already pretty tight)

2020-08-01 00:25 UTC, buxtronix commented on esphome/components/ble_client/ble_client.cpp
> +  ESP_LOGE(TAG, "Cannot parse characteristic value of type 0x%x", value[0]);
Fixed.

2020-08-01 00:26 UTC, buxtronix commented on esphome/components/ble_client/ble_client.cpp
> +      BLEService *bleService = new BLEService();
Fixed.

2020-08-01 00:26 UTC, buxtronix commented on esphome/components/ble_client/ble_client.cpp
> +    BLEDescriptor *bDesc = new BLEDescriptor();
Fixed.

2020-08-01 00:26 UTC, buxtronix commented on esphome/components/ble_client/ble_client.h
> +class BLEClient : public espbt::ESPBTClient, public Component, public Nameable {
Fixed. I think it was from some earlier development phase.

2020-08-01 00:27 UTC, buxtronix commented on esphome/components/ble_client/sensor/__init__.py
> +}).extend(cv.polling_component_schema('30s')).extend(ble_client.BLE_CLIENT_SCHEMA))
Fixed, I wasn't aware that 60s was convention.

2020-09-29 00:01 UTC, buxtronix commented
Hi, any chance for further review and/or merge on this one? Thanks.

2020-10-15 06:32 UTC, pixeldublu commented
Any updates ? Really looking forward on the enhancements of this. Specially the AM43 usage 👍 

Thanks @buxtronix for the work !

2020-10-27 15:05 UTC, kvvoff commented
I'm also waiting for it

2020-11-25 08:09 UTC, jpljonkman commented
Waiting for this one to go live....

2021-01-16 17:36 UTC, jaxer commented
Bumping this up. Hope it gets more attention. Let me know if i can help with testing.

2021-02-13 09:46 UTC, nightz123 commented
Bump, please merge this

2021-02-14 08:48 UTC, jpljonkman commented
bump, bump

2021-02-15 21:50 UTC, buxtronix commented
@jesserockz can I assign to you for review?

2021-02-22 19:14 UTC, nightz123 commented
Can anyone help? More than half a year and still no reaction?

2021-02-22 19:24 UTC, jesserockz reviewed
I have not looked through it all yet

2021-02-23 05:04 UTC, buxtronix commented on esphome/components/ble_client/ble_client.h
> +  int gattc_if_;
done - I updated visibility as appropriate for numerous class members.

2021-02-23 05:05 UTC, buxtronix commented on esphome/components/ble_client/ble_client.cpp
> +    bChar->parse_descriptors();
done

2021-02-23 05:05 UTC, buxtronix commented on script/test
> +esphome tests/test5.yaml compile
removed as i got my test to fit in 'test1'.

2021-03-08 23:21 UTC, stratus-ss commented
is there anything I can do to help this along. Regular user eagerly awaiting this PR :dancers:

2021-03-19 10:54 UTC, jesserockz commented on esphome/components/sensor/sensor.h
> +#include "esphome/components/sensor/sensor.h"
Including itself?

2021-03-21 03:39 UTC, buxtronix commented on esphome/components/sensor/sensor.h
> +#include "esphome/components/sensor/sensor.h"
fixed.

2021-03-25 09:38 UTC, nickrout commented
Looking forward to this!

2021-04-09 11:21 UTC, nightz123 commented
bump

2021-04-10 21:06 UTC, nickrout commented
Is this going to be merged?

2021-04-12 14:07 UTC, timdonovanuk commented
So close...

2021-04-18 06:41 UTC, jetijeti commented
oh wow, this looks promising! anything we can support to get this going?

2021-04-27 00:36 UTC, buxtronix commented
> Is there any work in progress I can test for writing attributes? I have a "Lumin+" bluetooth mood light, which I just need to write a little string including the RGB values to a given characteristic to set the color, and I was hoping to get this handled thru esphome, at least before I realized there was no write support in its BLE features.

You can use the source fork directly, I think HA can be configured to use ESPhome from any Github repo.

2021-04-27 18:58 UTC, rpavlik commented
> > Is there any work in progress I can test for writing attributes? I have a "Lumin+" bluetooth mood light, which I just need to write a little string including the RGB values to a given characteristic to set the color, and I was hoping to get this handled thru esphome, at least before I realized there was no write support in its BLE features.
> 
> You can use the source fork directly, I think HA can be configured to use ESPhome from any Github repo.

Yes, I see that, I just don't see any way to **write** attributes, only to **read** them, so I was wondering if anybody had started work on **writing** attributes.

2021-04-27 21:02 UTC, buxtronix commented
This fork uses this client to write to a ble.client, it should help:

https://github.com/buxtronix/esphome/blob/am43/esphome/components/am43_cover/am43_cover.cpp

2021-04-28 06:37 UTC, pixeldublu commented
> This fork uses this client to write to a ble.client, it should help:
> 
> https://github.com/buxtronix/esphome/blob/am43/esphome/components/am43_cover/am43_cover.cpp

@buxtronix 

Could you share also a sample config for the am43 ? 

Thanks!

2021-04-30 03:37 UTC, jesserockz requested changes
All looking good. a couple of comments/questions below, then all good to merge.
Working fine with my phone emulating a ble sensor.

2021-04-30 03:37 UTC, jesserockz commented on esphome/components/esp32_ble_tracker/__init__.py
> +
What is this intended for? It doesn't seem to be used anywhere?

2021-04-30 03:37 UTC, jesserockz commented on tests/test1.yaml
> +
Some unrelated test code?
```suggestion

```

2021-04-30 03:37 UTC, jesserockz commented on esphome/components/ble_client/__init__.py
> +DEPENDENCIES = ["esp32_ble_tracker"]
Please add yourself as a codeowner and run `script/build_codeowners.py`
```suggestion
CODEOWNERS = ["@buxtronix"]
DEPENDENCIES = ["esp32_ble_tracker"]
```

2021-05-02 12:43 UTC, buxtronix commented on esphome/components/esp32_ble_tracker/__init__.py
> +
removed.

2021-05-02 21:51 UTC, jesserockz approved these changes
Cheers

2021-05-02 23:10 UTC, merged

2021-05-03 04:25 UTC, pixeldublu commented
Finally 🎉 🥂 🙌

2021-05-03 10:31 UTC, OttoWinter reviewed
Whoops, sorry for the late review; Just had a quick look over the code and there are a couple of minor things
  1. a lot of log message have the wrong log level
  2. The class model for BLESensorNotifyTrigger looks wrong (both instance of `BLESensor`, but also takes one as a parameter?)
  3. The switch-block needs to have length checking to prevent a security issue.

2021-05-03 10:36 UTC, jesserockz commented
:man_facepalming: Thanks @OttoWinter

2021-05-03 12:32 UTC, buxtronix commented on esphome/components/ble_client/switch/__init__.py
> +    var = cg.new_Pvariable(config[CONF_ID])
Not sure what would be a better choice. Suggestions?

2021-05-03 13:04 UTC, buxtronix commented on esphome/components/ble_client/ble_client.h
> +  std::vector<BLEService *> services_;
I will look into this one further.

2021-05-03 13:05 UTC, buxtronix commented on esphome/components/ble_client/sensor/automation.h
> +  explicit BLESensorNotifyTrigger(BLESensor *sensor) { sensor_ = sensor; }
I'll check further. I'm sure there was some issue that necessitated this, though I can't recall without reproducing.

2021-05-08 01:37 UTC, Tuckie commented
Just wanted to express my excitement for future write support.

2021-05-11 01:10 UTC, jhansche commented
@buxtronix just wondering if I missed it in this, but is there any way to get text from a characteristic (received as a byte array of ASCII characters)? From what I can tell, sensor.platform=ble_client appears to only support float, and I don't see any way to support text_sensor. Or for that matter, any other way to process a byte array (unpack it as a data structure)?

2021-05-11 17:29 UTC, jetijeti commented
Hi guys, thanks for this awesome dvelopment! sadly i get with my heartrate monitor following error:

> [18:55:36][W][ble_sensor:082]: Error reading char at handle 16, status=2

where is the place to look for my mistake?

2021-05-14 20:01 UTC, jetijeti commented
> Ah, I'll try out template to see if that helps.
> 
> I noticed the value was showing up in Home Assistant pretty sporadically, but it was only showing the ASCII value of the first character of the string (string starts with "J" and the value in HA was "74"). And that makes sense because at https://github.com/esphome/esphome/pull/1177/files#diff-e704b8e66ea03345e393283b2c079fb50ec912e2aa90c7e405957135a4e225feR87 it's passing `value[0]`. I'm not sure what I should be looking for to find out if the rest of the data would be accessed anywhere else, for a template to use. This tells me that it's always only publishing the first byte of data, and the template wouldn't get access to the full byte array?

I just learned that I am facing the same question as @jhansche as I want to read data from a heart rate sensor which is composed not in a float but a  certain pattern of bits: https://www.bluetooth.com/specifications/specs/heart-rate-service-1-0/
Is this the right place to start this implementation?
I got my information from another user:
https://community.home-assistant.io/t/ble-heartrate-monitor/300354/29?u=jeti

2021-05-14 21:06 UTC, jhansche commented
> composed not in a float but a certain pattern of bits

The param->read.value[] array is `uint8_t *`:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_gattc.html#_CPPv4N24esp_ble_gattc_cb_param_t25gattc_read_char_evt_paramE
So if your value can be unpacked from the first uint8_t of that pointer/array, then you can use a template like @buxtronix suggested. If it's longer than `uint8_t`, then you won't be able to unpack it because you'll only receive the first byte.

2021-05-14 22:22 UTC, jhansche commented
I'm going to copy @buxtronix 's response in that HA thread above <https://community.home-assistant.io/t/ble-heartrate-monitor/300354/32>, because it answers some of the points/questions we raised here:

> The ble_client component is designed to be pretty generic and extendable.
> 
> The initial inclusion of the sensor reads pure numeric values, though extending it to heart rate sensors and other non numeric formats seems easy.
> 
> However, given that heart rate sensors have standard uuids, it seems worthwhile to create a new ble_heartrate component that only needs to have a ble_client reference.
> The same goes for other standard BLE types.

In my case I was hoping to use it to talk to my BedJet. I have done quite a bit of reverse engineering to learn the service/characteristic/descriptor UUIDs and the format of each characteristic payload. But the characteristics are not simple one-byte numeric values, so it'll take more work to integrate.

I'll do read up on esphome though (and stop cluttering this thread), to see what it takes to make a new custom component (local only). I don't know that it makes sense to try to include that as an esphome component, because it's such a specialized device type. You mentioned "standard BLE types", but I also see some fairly specialized components in esphome as well... So not sure if that makes sense to contribute here.

Though if it's too much of a hassle, I might just give one of my Android Things dev units a purpose to handle this, since I already know how to do it in Android, and it'll be easier to pipe the results into MQTT.

2021-05-15 02:43 UTC, Tuckie commented
> In my case I was hoping to use it to talk to my BedJet. I have done quite a bit of reverse engineering to learn the service/characteristic/descriptor UUIDs and the format of each characteristic payload. But the characteristics are not simple one-byte numeric values, so it'll take more work to integrate.

Small world; I'm hoping for the same! Although you've definitely done more than I have. I'm not sure if you've come across this, but should help on the write side of things: https://github.com/vimalb/BedJetController

2021-05-20 21:11 UTC, dkisselev commented on esphome/components/ble_client/switch/__init__.py
> +    var = cg.new_Pvariable(config[CONF_ID])
[I'm just a passer-by interested in this functionality, I don't have any authority over the project and this is just a suggestion]

BLEClientEnable?