Fix rf_bridge send and receive
OttoWinter/esphomeyaml pull request #1180
Opened 2020-07-22 17:31 UTC by vicfergar

## Description:
Some fixes for send and receive in rf_bridge component:

- Send: Proposal from issue comments has been included
- Receive: Parsing routine changed using modbus component as template

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/1259

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-07-23 01:37 UTC, glmnet commented
cc @jesserockz (#896)

2020-07-23 03:56 UTC, jesserockz commented
I have flashed this to my RF bridge but now I mostly get no codes received from the Sonoff RM433 remote, or a different code than known before if it does come through.

This is pressing the same button on the remote, the code was consistently `0xB4820C` before and it looks like the order is also different. `B482` is unique to the remote I believe and the last byte is the button being pressed.

```txt
[15:52:56][D][rf_bridge:054]: Received RFBridge Code: sync=0xA41C low=0xF200 high=0xFA02 code=0xE4B482
[15:52:58][D][rf_bridge:054]: Received RFBridge Code: sync=0xA41C low=0xD401 high=0x0E02 code=0xC6B482
[15:53:00][D][rf_bridge:054]: Received RFBridge Code: sync=0xA41D low=0x0601 high=0x0402 code=0xDAB482
[15:53:01][D][rf_bridge:054]: Received RFBridge Code: sync=0xA41C low=0xFC01 high=0x0402 code=0xDAB482
[15:53:02][D][rf_bridge:054]: Received RFBridge Code: sync=0xA41C low=0xF200 high=0xFA02 code=0xE4B482
[15:53:03][D][rf_bridge:054]: Received RFBridge Code: sync=0xA41C low=0xF201 high=0x0402 code=0xDAB482
[15:53:04][D][rf_bridge:054]: Received RFBridge Code: sync=0xA41C low=0xFC01 high=0x0402 code=0xDAB482
[15:53:05][D][rf_bridge:054]: Received RFBridge Code: sync=0xA41C low=0xFC01 high=0x1802 code=0xC6B482
```

2020-07-23 04:30 UTC, jesserockz requested changes
I fixed the problem with the above inconsistent codes.
I did not add the `RF_CODE_START` to the buffer but you did, therefore all bytes are 1 further into the buffer. Also need to change the `RF_MESSAGE_SIZE` to 10, I cannot code suggest that as it is not close to the changed lines.

2020-07-23 04:30 UTC, jesserockz commented on esphome/components/rf_bridge/rf_bridge.cpp
> +
```suggestion
      data.sync = (raw[2] << 8) | raw[3];
      data.low = (raw[4] << 8) | raw[5];
      data.high = (raw[6] << 8) | raw[7];
      data.code = (raw[8] << 16) | (raw[9] << 8) | raw[10];
```

2020-07-23 04:31 UTC, jesserockz commented
I also realised I do have another device now to receive RF codes now and the transmit function is working perfectly.

2020-07-23 05:58 UTC, vicfergar commented on esphome/components/rf_bridge/rf_bridge.cpp
> +
Hi @jesserockz, you are completely right I have commited the suggested changes and know everiting is working great. Thanks!

2020-07-23 05:59 UTC, jesserockz approved these changes

2020-07-23 13:27 UTC, merged

2021-03-22 21:20 UTC, nmsoares commented
@rspaargaren is this fixed in 1.16.2 ? 
I'm running esphome 1.16.2 in two sonoff rf bridges and it seams that it's don't working. In one bridge I have: [21:17:44][D][rf_bridge:147]: Sending code: sync=0x0700 low=0x0800 high=0x1000 code=0xABC123
[21:17:45][D][rf_bridge:036]: Action OK
and on a second bridge I dont see any code received.
Can you help *