Add the ability to do a forced recalibration on the SCD30
OttoWinter/esphomeyaml pull request #1237
Opened 2020-08-02 05:15 UTC by zeroping

## Description:

The SCD30, like the MH-Z19, can be calibrated with a gas with a known CO2 value (like outside air), but there wasn't a way to trigger that forced calibration (called a 'forced re-calibration', or FRC, in their docs). Since you can specify the ppm value used (unlike the MH-Z19), that's also added as a configuration option.

The functionality is modeled from how it is done for the MH-Z19.

I'm a little new at this, so please give any suggestions.

One point of discussion: the configurable baseline value used for the forced re-calibration is specified as a configuration option, not as an argument to the action. I can figure out how to change that if requested, but I assumed that most people would be regularly calibrating with a single known value, like 410 ppm for outside air.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation:** esphome/esphome-docs#<havenotsubmittedityet>

## Checklist:
  - [x] The code change is tested and works locally. 
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-08-02 13:34 UTC, Sizurka reviewed
I haven't had time to actually test this, so this is just from inspection.

2020-08-02 13:34 UTC, Sizurka commented on esphome/components/scd30/scd30.h
> +  void play(Ts... x) override { this->scd30_->asc_enable(); }
I haven't had time to actually test this, but on inspection: shouldn't this be `asc_disable();`

2020-08-02 13:34 UTC, Sizurka commented on esphome/components/scd30/scd30.h
> +  SDC30ASCLogic asc_boot_logic_{SCD30_ASC_NONE};
This doesn't seem to actually be used.  I assume the idea was to leave ASC in it's previous state if not set in the configuration.  

I made it turn it on by default because my sensor had issues until I explicitly did, but that may have been from my other futzing before.  So if you've tested on a fresh sensor that it's on by default and works correctly, that kind of logic may be fine.

2020-08-02 13:34 UTC, Sizurka commented on esphome/components/scd30/scd30.h
> +  void play(Ts... x) override { this->scd30_->asc_enable(); }
Shouldn't this be `asc_disable();`?

2020-08-02 15:09 UTC, zeroping commented on esphome/components/scd30/scd30.h
> +  SDC30ASCLogic asc_boot_logic_{SCD30_ASC_NONE};
Absolutely. I guess the en's and dis's started blurring together last night. I've now tested these actions and watched the output while triggering them.

2020-08-02 15:09 UTC, zeroping commented on esphome/components/scd30/scd30.h
> +  void play(Ts... x) override { this->scd30_->asc_enable(); }
Absolutely. I guess the en's and dis's started blurring together last night. I've now tested these actions and watched the output while triggering them.

2020-08-02 15:21 UTC, zeroping commented on esphome/components/scd30/scd30.h
> +  SDC30ASCLogic asc_boot_logic_{SCD30_ASC_NONE};
My SCD30 came from Mouser, and it demonstrated the same behavior that I think you saw when powered yours up the first time - it seemed like GET_DATA_READY_STATUS always returned non-ready. I agree - ACS being off seems like the cause. 

Sensirion does say "when [ASC is] activated for the first time a period of minimum 7 days is needed so that the algorithm can find its initial parameter set for ASC," yet when I set it on, it started reporting values immediately. They also explicitly state that the ASC enable state is stored in nonvolatile memory, and is disabled by default.

I switched to the development branch (with your fixes) and it came right up.

I think it's reasonable to set a known state for ASC on startup. It's less confusing than keeping it in a mystery "not yet set by ESPHome" state. I've taken that extra state logic completely out.

2021-08-03 08:06 UTC, OttoWinter commented
Thanks for this pull request, and sorry for the long review delay. I've just taken a look and updated it for the latest upstream changes. I also changed the name of the options to make them more descriptive (longer) - that matches with the existing `automatic_self_calibration` config option.

Could you take a look if it still works? Thanks!

CC @valordk - you originally implemented this platform, could you take a look too? thanks!

2021-08-04 15:16 UTC, valordk commented
@OttoWinter we are moving atm and all of my sensors are packed away, unfortunately

2021-10-27 14:40 UTC, zeroping commented
@OttoWinter Well, I failed to notice your comment for a few months, so I'm slowing things down too.

There was some conversation about this PR and https://github.com/esphome/esphome/pull/1402, and it looks like 1402 is simpler. Unfortunately, it's been sitting around for a year as well.

That said, it sounds like @geoffrey-vl and I have use cases for this, so I'd love to see one of the two PR's merged. Want to join in the conversation there before that PR is auto-closed?

2022-01-17 21:39 UTC, Maco65 commented
Hello. I will be happy to have such option in ESPHome. Is there any chance that this PR will be available ?

2022-01-18 11:00 UTC, RomainD2 commented
I also would love this feature !

2022-01-19 22:01 UTC, jesserockz requested changes
Would it make more sense for the `scd30.start_forced_recalibration` action to take the calibration number as a variable, allowing it to be changed without recompiling and uploading? Or will it always be the same, and its just a case of calling `scd30.start_forced_recalibration` again at some point with the same value?

Also a few things below regarding the default value.

2022-01-19 22:01 UTC, jesserockz commented on esphome/components/scd30/sensor.py
> +            cv.Optional(CONF_FORCED_CALIBRATION_BASELINE): cv.int_range(
Please set the default here and remove from the cpp code.
```suggestion
            cv.Optional(CONF_FORCED_CALIBRATION_BASELINE, default=410): cv.int_range(
```

2022-01-19 22:01 UTC, jesserockz commented on esphome/components/scd30/sensor.py
> +
This can then be changed
```suggestion
    cg.add(
        var.set_forced_calibration_baseline(
            config[CONF_FORCED_CALIBRATION_BASELINE]
        )
    )

```

2022-01-19 22:01 UTC, jesserockz commented on esphome/components/scd30/scd30.h
> +  int forced_calibration_baseline_ = 410;
```suggestion
  uint16_t forced_calibration_baseline_;
```

2022-02-11 19:22 UTC, anoblet commented
Is there any update on this?

2022-02-15 21:21 UTC, Maco65 commented
I would also support the activity in this topic.
It was fairly easy to use Tasmota to do forced calibration and I do believe it is essential feature for this sensor.

2022-02-18 15:18 UTC, jcastro commented
Looking forward to this PR as well. Is there an easy way to test it from an esphome installation?

2022-02-18 16:04 UTC, jcastro commented
> Looking forward to this PR as well. Is there an easy way to test it from an esphome installation?
> 
> EDIT: Answering myself here. You can test the PR by adding this code
> 
> ```
> external_components:
>   # replace 1234 with the number of the Pull Request
>   - source: github://pr#1237
>     components:
>       # list all components modified by this Pull Request here
>       - scd30
> ```
> 
> From https://esphome.io/guides/faq.html#how-can-i-test-a-pull-request

umm nope, doesn't seem to work (?)

2022-02-18 20:32 UTC, OttoWinter commented
Friendly ping (lol) @zeroping

Could you apply the suggestions in the review (https://github.com/esphome/esphome/pull/1237#pullrequestreview-857407004)? Thanks!

2022-02-18 20:36 UTC, anoblet commented
I'm receiving the following error when trying to test the PR:

```
[forced_calibration_baseline] is an invalid option for [sensor.scd30].
```

2022-02-18 20:38 UTC, valordk commented
> 

You will have to build your esphome from [this](https://github.com/zeroping/esphome/tree/scd30_forced_calibration)

2022-02-18 20:54 UTC, anoblet commented
I was able to get the PR up and running, though I saw no difference when adding `forced_calibration_baseline: 410` to my config.

2022-02-19 08:25 UTC, jcastro commented
> 

looks like you need to call an action that use that setting to calibrate it

2022-05-29 00:45 UTC, closed without merging