Image bit dephts
OttoWinter/esphomeyaml pull request #1241
Opened 2020-08-04 02:25 UTC by glmnet

## Description:
I totally missed this, its fixing image, this must be on 1.15, please give feedback. I'm still testing this, grayscale did not work for me and I still haven't looked into it 

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-08-04 02:32 UTC, glmnet commented
Off: Btw, just added needs-docs to the branch protection rules

2020-08-05 00:32 UTC, glmnet commented
@kbx81 would you like to test this one on your displays?
It changes the number option on type by proper enum values, also GRAYSCALE images are supported on color displays and BINARY images can be set custom colors foreground/background

2020-08-05 01:50 UTC, kbx81 commented
Works beautifully on everything I tried it on: SSD1327 (shown), SSD1352, ST7789. I love it -- much more polished than what I had hacked in there. 😄
![image](https://user-images.githubusercontent.com/21233191/89362677-155ad680-d694-11ea-9023-260b991fca69.jpeg)

2020-08-05 01:55 UTC, kbx81 commented
One thought: instead of `bit_depth`, might it be better/more accurate to use `color_depth`?

2020-08-06 15:15 UTC, OttoWinter commented on esphome/components/image/__init__.py
> +    cv.Optional(CONF_COLOR_DEPTH, default='BINARY'): cv.enum(COLOR_DEPTH, upper=True),
That would be a breaking change, please leave CONF_TYPE with `cv.invalid("This option is deprecated. [explain why]")`

2020-08-06 15:21 UTC, OttoWinter requested changes
Hmm, maybe in the future we will want to add support for other color encodings as well (16 bit color space for example, because some displays don't more depth).

Also the name `color_depth` isn't great IMO, accoring to [Wikipedia](https://en.wikipedia.org/wiki/Color_depth) color depth refers to `number of bits used to indicate the color of a single pixel`, which is not what is implemented here.

I think `type` was good enough already, and it's intuitive binary, grayscale, and rgb are options (plus supporting alternative color encodings would be easy to add later as well)

2020-08-06 15:28 UTC, glmnet commented
Great. I was doing docs now. So back to `type` and I'll rename RGB to RGB24 so we can have other types later

2020-08-06 18:08 UTC, glmnet commented on esphome/components/image/__init__.py
> +    cv.Optional(CONF_COLOR_DEPTH, default='BINARY'): cv.enum(COLOR_DEPTH, upper=True),
Actually TYPE or COLOR_DEPTH both are new in v1.15

2020-08-11 13:27 UTC, OttoWinter commented on esphome/components/display/display_buffer.cpp
> +void DisplayBuffer::image(int x, int y, Image *image, Color color_on, Color color_off) {
We'll likely want to change the `Image` class later to be an abstract class with subclasses like `BinaryImage`, `GrayscaleImage` etc. Then we can make the `image()` function only accept the color parameters for the right image types.

This is fine as-is too, because the user-facing code remains the same.

2020-08-11 13:27 UTC, OttoWinter approved these changes
LGTM, thanks!

Ah and yes sorry I didn't realize this was supposed to go in the 1.15 release (and hence is not a breaking change)

2020-08-11 13:28 UTC, merged