WIP: Add new sntp.synchronized condition
OttoWinter/esphomeyaml pull request #1255
Opened 2020-08-18 12:55 UTC by ashmckenzie

## Description:

This PR adds the `sntp.synchronized` condition which can be used as part of a [wait_until](https://esphome.io/guides/automations.html#wait-until-action) action, e.g.

```yaml
script:
  - id: on_boot
    then:
      - logger.log:
          level: INFO
          format: "Starting on_boot.."
      - script.execute: prevent_sleep
      - logger.log:
          level: INFO
          format: "Waiting for WIFI, MQTT and NTP.."
      - wait_until:
          - mqtt.connected:
          - sntp_time.synchronized:
      - logger.log:
          level: INFO
          format: "WIFI, MQTT and NTP up!"
      - script.execute: mqtt_ping
      - script.execute: do_work
```

**Related issue (if applicable):** fixes N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-09-15 15:18 UTC, OttoWinter commented
Please change this to `time.has_time` (because this is not just for sntp, but all time platforms). So move the condition in C++ and Python code to the `time` module and rename it.

2020-09-16 01:32 UTC, ashmckenzie commented
> Please change this to `time.has_time` (because this is not just for sntp, but all time platforms). So move the condition in C++ and Python code to the `time` module and rename it.

OK, thanks @OttoWinter 👍

2020-09-16 05:41 UTC, ashmckenzie commented
@OttoWinter, as requested I've updated this PR to now be `time.has_time`. May you please take a look when convenient? 🙏

2020-09-16 10:19 UTC, OttoWinter requested changes
Ah sorry I think I wasn't clear enough.

There's already a method to check if time is valid/has been set in the ESPTime struct: `is_valid()` (before a time has been set, the ESP will default to 1 jan 1970).

I've added a comment on what I think would be best. This way, the time components don't need to know that the `has_time_` variable has been set.

2020-09-16 10:19 UTC, OttoWinter commented on esphome/components/time/real_time_clock.h
> +  bool check(Ts... x) override { return this->parent_->has_time(); }
```suggestion
  bool check(Ts... x) override { return this->parent_->now()->is_valid(); }
```

2020-09-18 07:05 UTC, ashmckenzie commented on esphome/components/time/real_time_clock.h
> +  bool check(Ts... x) override { return this->parent_->has_time(); }
Thanks @OttoWinter, I believe I've addressed this 🙂

2020-09-18 07:06 UTC, ashmckenzie commented
@OttoWinter, thanks for the feedback, I believe this is ready for another look 🙂 🙏

2020-09-27 23:21 UTC, glmnet approved these changes

2020-09-27 23:21 UTC, glmnet commented
GTM when docs added

2020-09-28 13:06 UTC, ashmckenzie commented
> GTM when docs added

Thanks @glmnet, I've created https://github.com/esphome/esphome-docs/pull/782 🙂

2020-10-04 00:02 UTC, motwok approved these changes

2020-10-04 15:21 UTC, OttoWinter approved these changes

2020-10-04 15:22 UTC, merged