Sdm220m
OttoWinter/esphomeyaml pull request #1260
Opened 2020-08-24 04:00 UTC by polyfaces

## Description:

Add support for SDM220M energy meter

**Related issue (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-08-24 08:57 UTC, dcec commented
Have sense to use all SDM library https://github.com/reaper7/SDM_Energy_Meter?

2020-08-24 09:49 UTC, polyfaces commented
> 
> 
> Have sense to use all SDM library https://github.com/reaper7/SDM_Energy_Meter?

I am opened to use the SDM library.  However, in my point of view, I think it is better to reuse existing modbus components in esphome.

2020-08-24 10:34 UTC, dcec commented
I found this request: https://github.com/esphome/feature-requests/issues/289.
have sense to add the support of all SDM family and start with the more popolar  SDM120/SDM630.
I'm available to test with SDM120 if you want

2020-12-22 20:16 UTC, jesserockz requested changes, later dismissed
Thanks, only 2 things below then it's ready to merge.

2020-12-22 20:16 UTC, jesserockz commented on esphome/components/sdm220m/sdm220m.cpp
> +  ESP_LOGD(TAG,
This probably does not need to be a debug message.

```suggestion
  ESP_LOGV(TAG,
```

2020-12-22 20:16 UTC, jesserockz commented on esphome/components/sdm220m/sensor.py
> +AUTO_LOAD = ['modbus']
Please add yourself as a codeowner and then run `script/build_codeowners.py`

```suggestion
AUTO_LOAD = ['modbus']
CODEOWNERS = ['@polyfaces']
```

2020-12-22 20:29 UTC, reaper7 commented
why do you limit addon (at least in terms of nomenclature) to 220m ?

I've prepared a list of registries in a table form:
https://github.com/reaper7/SDM_Energy_Meter/blob/master/SDM.h#L95

Maybe you will choose common registers and prepare a more general version?

2021-02-05 07:25 UTC, dcec commented
@reaper7  is also possible to use rs232<->rs485 converter with additional pins for flow control, like MAX485 with esphome?

2021-02-05 09:02 UTC, reaper7 commented
@dcec - why not, You can try with custom component: https://github.com/reaper7/esphome_sdm_custom

Remember to specify which pin will be responsible for flow control:

uncomment this line and replace NOT_A_PIN with the correct pin number
https://github.com/reaper7/esphome_sdm_custom/blob/master/custom_components/sdm/SDM_Config_User.h#L52

and replace NOT_A_PIN with the correct pin number(the same as above) in this line:
https://github.com/reaper7/esphome_sdm_custom/blob/master/custom_components/sdm/sdm_esphome.h#L5

2021-02-18 17:08 UTC, corvis commented
+1 for making this more generic and adding more registers/sensors at least in the future. E.g. I have SDM220 and SDM630 (3 phases). Both are currently connected directly to the home assistant via USB<>ModBus converer but it would be geart to connect them to the esphome.

@polyfaces are there any wiring instructions how to connect to esphome? It's modbus, so I some hardware converter is required. Maybe it makes sence to cover this in docs?

2021-03-05 21:29 UTC, nikito7 commented
https://github.com/esphome/esphome/pull/1571

2021-05-15 04:54 UTC, jesserockz commented
@polyfaces I hope you don't mind, I made a few changes to this component...

`sdm220m` is now `sdm_meter` and it supports sensors for the 3 phases which allows support for the sdm6XX series.

@reaper7 @corvis if you guys could test this out, that would be great. I have the SDM230M here working fantastically with this.

I also added a `flow_control_pin` to the `sdm_meter` as I personally have a `max485` connected.

Cheers, Jesse

2021-05-31 04:00 UTC, jesserockz approved these changes

2021-05-31 04:05 UTC, merged

2021-05-31 17:49 UTC, reaper7 commented
work ok for me (sdm220) but I see one error:
```
[19:41:32][E][uart:054]:   Invalid stop bits: Integration requested stop_bits 2 but you have 1!
```
my uart config:
```
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  stop_bits: 1
```

sdm meter is also set to 1 stop bit...

I remember that somewhere in the esphome-> modbus code 2 stop bits were permanently set

2021-05-31 18:34 UTC, jesserockz commented
Good point, I think I will remove that and leave it up to the individual component to verify the settings.