enable the use of 16 bit address registers in I2C
OttoWinter/esphomeyaml pull request #1268
Opened 2020-09-01 12:47 UTC by torwag

## Description:
Currently, the address registers are fixed to 8 bit. Some devices however use 16 bit address registers. The PR implements the usage of 16 bit address registers.
It tries to be as non-invasive as possible. Devices with 8bit address registers will not see any difference in terms of communication.

!!! This PR is not intended for merging yet. It compiles but was not tested yet. It should enable a discussion and further development !!!

**Related issue (if applicable):** fixes <link to issue>
<https://github.com/esphome/feature-requests/issues/875>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-09-02 07:10 UTC, jesserockz requested changes
Take a look at the [checks](https://github.com/esphome/esphome/pull/1268/checks) as they can help you fix the linting issues and compile errors.
Not sure on the overall structure of this though, surely there is a better and more DRY way of doing this.

2020-09-02 07:10 UTC, jesserockz commented on esphome/components/i2c/i2c.cpp
> +}
You are overloading the methods with an ambiguous signature. You will need to name the new ones something different.

2020-09-02 19:56 UTC, torwag commented on esphome/components/i2c/i2c.cpp
> +}
Ok, my first attempt is not working as I did not realize that people call those functions with other types and C can't guess whether the casting should go into uint8_t or uint16_t. Thus, we have an ambiguous overloading... 
Back to the drawing board and start from scratch :)

2020-09-03 10:55 UTC, jesserockz commented on esphome/components/i2c/i2c.cpp
> +  (a_register_width == 8) ? this->raw_write(address, (uint8_t*)&a_register, 1) : this->raw_write_16(address, &a_register, 1);
Might make sense to wrap these in an `if` for readability

2020-09-03 11:41 UTC, torwag commented on esphome/components/i2c/i2c.cpp
> +  (a_register_width == 8) ? this->raw_write(address, (uint8_t*)&a_register, 1) : this->raw_write_16(address, &a_register, 1);
Can do this, was asked in another project to do vice versa... just a personal preference of style I guess :)
I can fix the lint errors as well if I could figure out how to get the report with the git-diff out of github.

2020-09-03 11:54 UTC, torwag commented on esphome/components/i2c/i2c.cpp
> +  (a_register_width == 8) ? this->raw_write(address, (uint8_t*)&a_register, 1) : this->raw_write_16(address, &a_register, 1);
btw. I am a bit concerned about this part 
``(uint8_t*)&a_register``
the functions write_raw expect a pointer to an uint8_t object, as it is usually data in form of 8 bit packages. 
Now the register address has become 16 bit. If only the first 8 bit get used (as before) we need to send one byte done by 
``this->raw_write(address, (uint8_t*)&a_register, 1)`` whereas address is the device address, a_register is the register to be addressed and the pointer should point to a single byte (the address of the register). As the a_register is a 16 bit value, it needs to get dereferenced to get the pointer and then be casted into a pointer for unsigned 8 bit. 
Not sure I have done this right. Would be glad if someone with more skills in pointer and casting would comment on this.

2021-09-14 08:49 UTC, closed without merging