Mcp3008
OttoWinter/esphomeyaml pull request #1270
Opened 2020-09-04 15:40 UTC by SenexCrenshaw

## Description:
Updated the sensor to return the voltage read to match how the ADC component works. 

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-09-15 15:37 UTC, OttoWinter requested changes
Hi, thanks for the new feature.

Some comments to make the code cleaner (and remove a breaking change).

2020-09-15 15:37 UTC, OttoWinter commented on esphome/components/mcp3008/sensor.py
> +    cv.Required(CONF_MCP3008): cv.use_id(MCP3008),
Please revert to what was here before. With this change you're removing the `mcp3008_id` parameter and adding a new required `mcp3308` parameter.

2020-09-15 15:37 UTC, OttoWinter commented on esphome/components/mcp3008/sensor.py
> +                           config[CONF_REFERENCE_VOLTAGE])
You're already setting the reference voltage variable below (see `set_reference_voltage`) -> duplicate setting of reference voltage.

Either remove the parameter from the constructor or remove the set method call please (I'd prefer the latter).

2020-09-15 15:37 UTC, OttoWinter commented on esphome/components/mcp3008/mcp3008.cpp
> +  return (data_msb << 8 | data_lsb);
Please revert to previous `return data / ...` (but with 1023 as you correctly identified).
The conversion from raw uint16 to float should happen in this function, not the caller.

2020-09-15 15:37 UTC, OttoWinter commented on esphome/components/mcp3008/mcp3008.cpp
> +void MCP3008Sensor::setup() {
This is the wrong method to print config information in. Please see `::dump_config()`

2020-10-23 01:39 UTC, SenexCrenshaw commented on esphome/components/mcp3008/mcp3008.cpp
> +  return (data_msb << 8 | data_lsb);
Sounds good. i didnt do a pull b4 i applied this patch..

2020-10-23 01:40 UTC, SenexCrenshaw commented on esphome/components/mcp3008/sensor.py
> +    cv.Required(CONF_MCP3008): cv.use_id(MCP3008),
I didnt pull the latest and overwrote some changes. Fixed

2020-10-23 02:03 UTC, SenexCrenshaw commented on esphome/components/mcp3008/mcp3008.cpp
> +void MCP3008Sensor::setup() {
@OttoWinter  thank you for the feedback. I didnt do a pull before so some changes since were lost. Everything should be buttoned up. Ill update the docs to match

2020-10-23 12:48 UTC, SenexCrenshaw commented
@OttoWinter 
I am a little at a loss with the test. The mcp component 
mcp3008:
  - id: 'mcp3008_hub'
    cs_pin: GPIO12
works without issue. if i add a simple sensor it fails to compile. this works if im just using mcp and without the other tests though. during the esphome compile i get this:

[36mDEBUG Adding: //   platform: mcp3008
//   update_interval: 5s
//   mcp3008_id: mcp3008_hub
//   id: freezer_temp_source
//   reference_voltage: 3.19
//   number: 0
//   mqtt_id: mqtt_mqttsensorcomponent_2
//   force_update: false
//   name: freezer_temp_source
//   internal: true

Not sure where it is getting the mqtt_id or force_update from. Can you point me in the right direction?

2020-10-23 15:47 UTC, SenexCrenshaw commented on esphome/components/mcp3008/sensor.py
> +                           config[CONF_REFERENCE_VOLTAGE])
i reverted my changes

2020-10-23 15:47 UTC, SenexCrenshaw commented on esphome/components/mcp3008/mcp3008.cpp
> +  return (data_msb << 8 | data_lsb);
fixed

2020-10-23 15:48 UTC, SenexCrenshaw reviewed
Should be good to go. thanks for the help

2020-11-18 06:38 UTC, jesserockz commented on esphome/components/mcp3008/mcp3008.cpp
> +  ESP_LOGCONFIG(TAG, "  CS Pin: %u", this->cs_->get_pin());
Why change this from `LOG_PIN`?

2020-11-18 06:43 UTC, jesserockz commented on esphome/components/mcp3008/mcp3008.cpp
> +void MCP3008Sensor::setup() {
@SenexCrenshaw This still shouldn't be in `setup()`.

2020-11-18 12:44 UTC, SenexCrenshaw commented on esphome/components/mcp3008/mcp3008.cpp
> +  ESP_LOGCONFIG(TAG, "  CS Pin: %u", this->cs_->get_pin());
Mistake on my part. I submitted a new PR. thanks for the feedback!

2020-11-20 08:32 UTC, jesserockz commented
While you are modifying this, maybe make it extend `voltage_sampler::VoltageSampler` which just needs to implement the `sample` method which reads and returns the voltage. This makes this usable by other sensors that use the `adc`/`ads1115` sensors

2020-11-20 09:07 UTC, jesserockz requested changes
A couple of extra tests seemed to make it into this PR. Optionally the voltage_sampler additions would be nice too =)

2020-11-20 16:01 UTC, closed without merging

2020-11-20 16:54 UTC, SenexCrenshaw commented
so sorry. i reset hard... in some ways it was good to start fresh with the already committed changes. I added in the requested changes here
#1387 1387