Add addressable_light_display display platform
OttoWinter/esphomeyaml pull request #1272
Opened 2020-09-07 06:06 UTC by justfalter

- Adds addressable_light_display, which allows any addressable_light
component to be made available as a display.

## Description:

Adds `addressable_light_display` as a supported `display` platform. This allows any component derived from `AddressableLight` (ex: `fastled_clockless`, `neopixelbus`, etc) to be used as a display.  I wrote the code initially for a 64-led WS2812B strip arranged in an 8x8 matrix. My next project is to build a lametric-inspired clock/weather/notification display using an 8x32 WS2812B matrix.

Notes:
- `addressable_light_display` requires an `AddressableLight`-derived light be defined, and supplied via the `addressable_light_id` property. 
- The display may be enabled or disabled via `set_enabled(bool)` -- allowing one to switch control back and forth between the Display mode and that of the light (maybe you want to be able to flip between lighting effects and displaying images/text/etc).

Here's an example of my 8x8 using some of the `display` component functionality to draw a bulls-eye pattern:
```
esphome:
  name: ledbox01
  platform: ESP32
  board: esp32doit-devkit-v1
  on_boot:
    priority: -10
    then:
      - switch.turn_on: control_display

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO4
    num_leds: 64
    rgb_order: GRB
    name: "led_matrix"
    id: led_matrix
    default_transition_length: 0s
    color_correct: [50%, 50%, 50%]
    internal: false
    restore_mode: ALWAYS_ON

display:
  - platform: addressable_light_display
    id: my_display
    addressable_light_id: led_matrix
    width: 8
    height: 8
    rotation: 180°
    update_interval: 16ms
    lambda: |-
      Color red = Color(0xFF0000);
      Color green = Color(0x00FF00);
      Color blue = Color(0x0000FF);
      it.rectangle(0, 0, 8, 8, red);
      it.rectangle(1, 1, 6, 6, green);
      it.rectangle(2, 2, 4, 4, blue);
      it.rectangle(3, 3, 2, 2, red);

switch:
  - platform: template
    id: control_display
    name: "Control Display"
    turn_on_action:
      - lambda: |-
          id(my_display).set_enabled(true);
    turn_off_action:
      - lambda: |-
          id(my_display).set_enabled(false);
```

![bullseye](https://user-images.githubusercontent.com/120545/92350862-d8716d80-f09f-11ea-8496-79f807ee5e51.png)

**Related issue (if applicable):** 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-09-07 06:08 UTC, justfalter commented
I'll get documentation written up and submitted, tomorrow.

2020-10-07 02:09 UTC, justfalter commented
Hi there,
Just wondering if I'm missing anything that might hold up this PR? I don't know what the timeline for merging/review typically is with esphome, but any feedback would be greatly appreciated!

2021-02-13 09:53 UTC, jesserockz commented
@justfalter Sorry nobody has replied on this PR. I myself am waiting for an 8x32 led matrix to arrive and will be testing this out when it does. Will update you once I have it running (or having issues).

2021-02-13 12:21 UTC, docteurzoidberg commented
will try it on my 25x35 matrix and tell!

2021-02-13 14:41 UTC, docteurzoidberg commented
test on a 8x32 matrix. with untouched width and height : https://i.imgur.com/Oyxxx1K.png
test on a 8x32 matrix, when setting 8 and 32 in height/width: https://i.imgur.com/YDO1JPd.png

2021-02-13 18:04 UTC, justfalter commented
Since creating this PR, I had picked up one of those 8x32 ws2812b matrixes. I've got some additional changes that I need to push up that allow you to specify a custom pixel-mapper lambda from the yaml configuration.

2021-02-13 19:41 UTC, justfalter commented
I still have to update the documentation, but I hope that diff around the `pixel_mapper` makes it apparent what is going on for testing purposes 

The 8x32 ws2812b matrix that I have kind of snakes down, up, down .... starting from the upper left.
```
    X
    0  1  2  3  4
Y 0 *  |--|  |--|
  1 |  |  |  |  |
  2 |  |  |  |  |
  3 |  |  |  |  |
  4 |  |  |  |  |
  5 |  |  |  |  |
  6 |  |  |  |  |
  7 |--|  |--|  |--(etc)
```
In my case, the following worked for pixel mapping my matrix:
```
    pixel_mapper: |-
      if (x % 2 == 0) {
        return (x * 8) + y;
      }
      return (x * 8) + (7 - y);
```

2021-02-13 19:42 UTC, docteurzoidberg commented
perfect. will test and report ! many thanks for the update

2021-02-13 20:12 UTC, docteurzoidberg commented
seems to work nice with the provided  pixel mapper lambda for my 8x32 matrix too! (round one sorry): https://i.imgur.com/759tZOu.png

2021-02-13 20:13 UTC, docteurzoidberg commented
> 
> 
> I still have to update the documentation, but I hope that diff around the `pixel_mapper` makes it apparent what is going on for testing purposes
> 
> The 8x32 ws2812b matrix that I have kind of snakes down, up, down .... starting from the upper left.
> 
> ```
>     X
>     0  1  2  3  4
> Y 0 *  |--|  |--|
>   1 |  |  |  |  |
>   2 |  |  |  |  |
>   3 |  |  |  |  |
>   4 |  |  |  |  |
>   5 |  |  |  |  |
>   6 |  |  |  |  |
>   7 |--|  |--|  |--(etc)
> ```
> 
> In my case, the following worked for pixel mapping my matrix:
> 
> ```
>     pixel_mapper: |-
>       if (x % 2 == 0) {
>         return (x * 8) + y;
>       }
>       return (x * 8) + (7 - y);
> ```

many thanks!

2021-02-13 22:55 UTC, justfalter commented
I've updated the [docs PR](https://github.com/esphome/esphome-docs/pull/755) to include details on the `pixel_mapper`.

Thanks for checking out my PR, I'm glad it's working for more than just myself!

2021-03-08 19:43 UTC, jesserockz requested changes
@justfalter I am still waiting for my matrix to arrive, but all is looking good Just a few points:
- Could you add yourself as a CODEOWNER as below and run `script/build_codeowners.py`
- Also please reformat the python file using `black`

2021-03-08 19:43 UTC, jesserockz commented on esphome/components/addressable_light_display/display.py
> +
```suggestion
CODEOWNERS = ["@justfalter"]

```

2021-03-09 14:09 UTC, justfalter commented
@jesserockz Done! Thanks, again, for keeping this going!

2021-03-10 05:56 UTC, jesserockz requested changes
I was just thinking, I don't like the `_display` on the end. Maybe rename it to just be `addressable_light` I know it might sound confusing because of the addressable lights, but basically this is just the display platform for those, so it does make sense:

```yaml
display:
  - platform: addressable_light
     ...
```

2021-03-17 14:10 UTC, docteurzoidberg commented
@justfalter : I use your component a lot !thanks for your work, it's working pretty well ! I have a tons of thing to show you on my matrices :)

2021-03-17 14:16 UTC, docteurzoidberg commented
@justfalter @jesserockz i wrote a "DisplayEffects" concept like in leds effets but for 2d display, but since it use a lot of maths on some effects. maybe it should be restricted to addressable light displays (because small resolutions) and become AdresseLightDisplayEffects ?

2021-03-18 01:02 UTC, jesserockz commented
Sorry about the test size, you could try to move to test4.yaml which has a lot less in it.

2021-03-18 02:42 UTC, jesserockz commented on esphome/components/addressable_light/addressable_light_display.cpp
> +static const char* TAG = "display.addressable_light";
Sorry, this is something that needs a little bit of tidy up in the whole repo, but it should be the other way around
```suggestion
static const char *TAG = "addressable_light.display";
```

2021-03-18 02:48 UTC, justfalter commented
@jesserockz All done!

2021-03-18 02:53 UTC, jesserockz approved these changes

2021-03-18 02:55 UTC, jesserockz commented on esphome/components/addressable_light/addressable_light_display.cpp
> +static const char* TAG = "addressable_light.display";
Interesting, most of the codebase has it on the right, oh well =)

2021-03-18 02:55 UTC, justfalter commented on esphome/components/addressable_light/addressable_light_display.cpp
> +static const char* TAG = "addressable_light.display";
You win some, you lose some.

2021-03-18 06:08 UTC, merged

2021-03-18 09:33 UTC, docteurzoidberg commented
🥇

2021-05-04 20:42 UTC, escoand commented
Are there some ideas to fix the flicker when turning the light output on and off? Setting `transition_length: 0s` doesn't avoid this problem completely and is also just some hacky workaround.

2021-05-25 01:55 UTC, k-w-1 commented
> Are there some ideas to fix the flicker when turning the light output on and off? Setting `transition_length: 0s` doesn't avoid this problem completely and is also just some hacky workaround.

For what it's worth, I've noticed on ESP8266 you need to use the RXD pin (3) (for DMA support, apparently) with ws2812s. It doesn't get rid of the transition flicker entirely, but I was getting tons of flickering on any display updates. For me, switching to pin 3 did reduce the on/off flicker (with the 0s bodge).