Add support for ATC_MiThermometer
OttoWinter/esphomeyaml pull request #1291
Opened 2020-09-20 09:43 UTC by ahpohl

## Description:

This patch adds support for the [ATC MiThermometer](https://github.com/atc1441/ATC_MiThermometer) custom firmware, which replaces the stock firmware in Xiaomi LYWSD03MMC Temperature/Humitity sensors. The main advantage of the custom firmware compared to the Xiaomi stock firmware is that the payload is not encrypted and there is no [bindkey](https://esphome.io/components/sensor/xiaomi_ble.html#obtaining-the-bindkey) necessary.

**Note:** This patch (i.e. the new `atc_mithermometer` component) specifically requires the custom firmware to be operated in "custom" advertising mode. The firmware also has a "Mi Like" advertising mode, which is already fully supported by the `xiaomi_lywsd03mmc` component (with a dummy bindkey still necessary in the config).

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/877

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-09-24 03:30 UTC, glmnet reviewed
It'd be nice if you add CODEOWNERS to all your contributions, that will ease issue handling, thanks

2020-09-24 03:30 UTC, glmnet commented on esphome/components/atc_mithermometer/sensor.py
> +
```suggestion

CODEOWNERS = ['@ahpohl']
```

2020-09-24 03:30 UTC, glmnet commented on esphome/components/atc_mithermometer/atc_mithermometer.h
> +  bool report_results(const optional<ParseResult> &result, const std::string &address);
I would mark those protected, but it's ok too

2020-11-02 21:12 UTC, jesserockz requested changes
Looking good, a few minor change please =)

2020-11-02 21:12 UTC, jesserockz commented on requirements.txt
>  tzlocal==2.1
Please don't bump the dependencies if it is unrelated to your changes in the PR

2020-11-02 21:12 UTC, jesserockz commented on esphome/components/atc_mithermometer/sensor.py
> +CODEOWNERS = ['@ahpohl']
Could you move this to near the top of the file before `DEPENDENCIES` for consistency with other files and easy to read/find. Thanks

2020-11-02 21:12 UTC, jesserockz commented on esphome/components/xiaomi_lywsd03mmc/sensor.py
> +CODEOWNERS = ['@ahpohl']
Could you move this to near the top of the file before `DEPENDENCIES` for consistency with other files and easy to read/find. Thanks

2020-11-03 17:33 UTC, jesserockz approved these changes
Thanks

2020-11-03 17:36 UTC, merged