Fix Xiaomi merged packet parsing
OttoWinter/esphomeyaml pull request #1293
Opened 2020-09-21 10:42 UTC by Alex9779

## Description:
fixes parsing of Xiaomi merged packets

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/1500

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-09-22 05:40 UTC, ahpohl requested changes

2020-09-22 05:40 UTC, ahpohl commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +    return true;
Why do you return after each if statement? It is enough to return true at the end of the function as each block is executed only if the the if condition is true.

2020-09-22 05:40 UTC, ahpohl commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +      ESP_LOGVV(TAG, "parse_xiaomi_message(): payload data point has wrong size (%d)!", datapoint_length);
What is the purpose of this debug message? Currently it warns me that the data point has the wrong size (0), but then the data point is parsed and reported correctly. Doesn't make sense to me.
```
[07:36:33][VV][xiaomi_ble:298]: decrypt_xiaomi_payload(): authenticated decryption passed.
[07:36:33][VV][xiaomi_ble:300]:   Plaintext : 06.10.02.23.02 (5), Packet : 64
[07:36:33][VV][xiaomi_ble:127]: parse_xiaomi_message() 3: payload data point has wrong size (0)!
[07:36:33][D][xiaomi_ble:312]: Got Xiaomi LYWSD03MMC (A4:C1:38:BC:B9:B2):
[07:36:33][D][xiaomi_ble:318]:   Humidity: 54.0%
[07:36:33][V][sensor:013]: 'Kitchen Humidity': Received new state 54.000000
[07:36:33][D][sensor:092]: 'Kitchen Humidity': Sending state 54.00000 % with 0 decimals of accuracy
```

2020-09-22 06:09 UTC, Alex9779 commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +    return true;
Yeah well, just copied and didn't think about improvement...

2020-09-22 06:13 UTC, Alex9779 commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +      ESP_LOGVV(TAG, "parse_xiaomi_message(): payload data point has wrong size (%d)!", datapoint_length);
No idea, maybe there is some miscalculation or data residue with encrypted data leading for the loop to be executed and all other checks still pass, from what I see is that you can get there if you data_length is 3 after a loop, then it is executed again but there is no data after the initial 3 bytes...

2020-09-23 05:29 UTC, ahpohl commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +      ESP_LOGVV(TAG, "parse_xiaomi_message(): payload data point has wrong size (%d)!", datapoint_length);
the data residue is another frame counter and the bind token appended to the payload. unfortunately the frame counter always has 00 where the data point length is expected. hence the length check fails and the debug message is issued.

I suggest checking for a valid data point based on the fixed byte 0x10. If this is not found, parsing of data points is complete. I have prepared an improved version in my repo on the multi_values branch for you to test. I made an number of improvements, mainly renaming the variables to improve code readability.

2020-09-23 14:44 UTC, ahpohl commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +      ESP_LOGVV(TAG, "parse_xiaomi_message(): payload data point has wrong size (%d)!", datapoint_length);
the data residue consists of another frame counter and the bind token. This is only for encrypted sensors such as the LYWSD03MMC. I am working to improve your PR and added a check for the fixed byte 0x10. If that is not found then multi value parsing has been completed. I still need to test the code.

2020-09-23 15:30 UTC, ahpohl commented
@Alex9779  The code works for me, but I do not have a sensor which broadcasts multiple values at once like the CGG1 so I cannot fully test. You can download my changes from here: https://github.com/ahpohl/esphome/tree/multi_values.

I do not fully understand how the multi values are actually being reported. `parse_xiaomi_value` fills the results structure, which gets overwritten as soon as `parse_xiaomi_value` is called again for the next value. `report_xiaomi_results` is only called once per service data so it would report only the last value in my understanding. Could you explain this?

2020-09-23 15:36 UTC, Alex9779 commented
I saw you branch this morning looked over it bit didn't have time to really think through and answer.
My code works for me and since I use it on my devices I get all data again from the devices which do send those combined messages. Not all of my CGG1s do this.
Regarding your question how this works I al not the best C/C++ programmer but you pass just an address of the result and if it is a different type if message then a different property is written...

2020-09-23 16:39 UTC, Alex9779 commented
I reviewed your code, I could rename the variables, but I am still not sure about the checks, not mine and not yours actually, when entering the loop and just before...

So what do you expect now? Shall I take some changes and commit them to my PR? Shall I withdraw and you create a new one?

2020-09-23 16:50 UTC, ahpohl commented
Most sensors will cleanly process the payload and will not enter the loop again when all data is processed (`payload_length = 0`). But for those which append some other data the checks are necessary and make sense (esp. checking for the fixed byte 0x10).

> Shall I take some changes and commit them to my PR? Shall I withdraw and you create a new one?

I have PR #1291 still pending. If you agree, I could easily extend it to include issue https://github.com/esphome/issues/issues/1500.

2020-09-23 18:28 UTC, ahpohl commented
> I do not fully understand how the multi values are actually being reported. 

I checked the multi value reporting with the dummy payload `50.30.47.03.5C.DB.52.10.34.2D.58.06.10.02.EC.01.0A.10.01.5B` from CGG1. You cannot report the same value twice. But it is perfectly fine to report a temperature together with a battery level, for example. `report_xiaomi_results` is called only once and sends all the values which are populated (actually the value are sent by the device class itself, but the same applies here as well).

This answers my last question and I am fine to go ahead with either of our code versions.

2020-09-23 18:51 UTC, Alex9779 commented
> But it is perfectly fine to report a temperature together with a battery level, for example.

Yeah and that is what is happening. When initially discovered it was just the battery level which is appended, there are no other reports yet but we decided to make it robust so it will be future proof if there might be other devices doing this with several different types of values.

I updated my code with your changes to values and length checking, test were successful and I still get the battery level from the devices which use that.

I just have one doubt regarding the initial check in the loop, this will be only reached if you have that residual data with encrypted payloads and not for normal devices. So on a normal parse I will never see that "value parsing is complete". Maybe a different message might make more sense?

2020-09-23 18:54 UTC, Alex9779 commented
Oh btw:
> I have PR #1291 still pending. If you agree, I could easily extend it to include issue [esphome/issues#1500](https://github.com/esphome/issues/issues/1500).

I don't think we should mix those two topics... :D

2020-09-23 19:25 UTC, ahpohl requested changes

2020-09-23 19:25 UTC, ahpohl commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +      ESP_LOGVV(TAG, "parse_xiaomi_message(): value parsing complete.");
> Maybe a different message might make more sense?

How about "parse_xiaomi_message(): fixed byte not found. stop parsing residual data."

2020-09-23 19:25 UTC, ahpohl commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +bool parse_xiaomi_data_byte(uint8_t value_type, const uint8_t *data, uint8_t payload_length,
Btw, have you declared this new function `parse_xiaomi_data_byte` in https://github.com/Alex9779/esphome/blob/fix_xiaomi_merged_packets/esphome/components/xiaomi_ble/xiaomi_ble.h?

2020-09-23 19:29 UTC, ahpohl commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +bool parse_xiaomi_data_byte(uint8_t value_type, const uint8_t *data, uint8_t payload_length,
Ahm, I now I am getting picky here, but you are actually parsing more than one byte with this function (to be precise up to 4 bytes). Hence I renamed this function to `parse_xiaomi_value` (value == measurement (but this was too long to write everywhere))

2020-09-23 19:31 UTC, Alex9779 commented
oops, missed that :)

2020-09-23 19:31 UTC, ahpohl commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +bool parse_xiaomi_data_byte(uint8_t value_type, const uint8_t *data, uint8_t payload_length,
and the payload means the concatenated values all together. Hence here you are just parsing the value (or as you called in data point. So `payload_length` would need to be renamed to `value_length` as well.

2020-09-23 19:34 UTC, Alex9779 commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +bool parse_xiaomi_data_byte(uint8_t value_type, const uint8_t *data, uint8_t payload_length,
> Btw, have you declared this new function `parse_xiaomi_data_byte` in

Nope, as said, I am not so good in C++ :), don't think of headers that much. Still works here because declared first and just used later in the same file...

2020-09-23 19:36 UTC, Alex9779 commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +bool parse_xiaomi_data_byte(uint8_t value_type, const uint8_t *data, uint8_t payload_length,
going to change that...

2020-09-23 19:36 UTC, ahpohl commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +bool parse_xiaomi_data_byte(uint8_t value_type, const uint8_t *data, uint8_t payload_length,
I know it "works", but that doesn't mean its correct. :-)

2020-09-23 19:46 UTC, Alex9779 commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +bool parse_xiaomi_data_byte(uint8_t value_type, const uint8_t *data, uint8_t payload_length,
> I am getting picky here

yes really :D :D for something you actually broke...

2020-09-23 19:48 UTC, ahpohl approved these changes
Looks good. I think that's it.

2020-09-23 20:02 UTC, ahpohl commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +bool parse_xiaomi_data_byte(uint8_t value_type, const uint8_t *data, uint8_t payload_length,
Do I really need to apologize for this? You had plenty of time to review PR https://github.com/esphome/esphome/pull/1027 before it was eventually pulled into dev. There was a very lively discussion about every change to the code and every new device which was added in the issue thread https://github.com/esphome/feature-requests/issues/552. I didn't here a beep from you at the time, and now after many month this patch has been pulled you notice that something isn't working for you anymore.

> @ahpohl did you miss that? You just killed the loop...

Instead of complaining that I broke your beautiful code, you could have just politely asked me to put this functionality back.  Then we wouldn't need to have this ugly discussion and could focus on something more productive.

2020-09-23 20:17 UTC, Alex9779 commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +bool parse_xiaomi_data_byte(uint8_t value_type, const uint8_t *data, uint8_t payload_length,
Sorry, don''t misunderstand me, no offense... I write up an issue, then think about it and then I think "just try to fix it, I want this now..."
But don't expect me to monitor any repo with software I use, especially this very active one... Did miss that PR, from time to time I look over some issues but nothing more.
I told in the issue I realized that there was a problem but didn't have time to look deeper into it, I changed some device configs and used the new version and so the the values were gone...
So I am really sorry if I occupied your time, it's done now, and again, no offense meant, just wanted to get it done as I felt I was near the solution when I examined the problem with my devices...

2020-09-23 20:34 UTC, ahpohl commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +bool parse_xiaomi_data_byte(uint8_t value_type, const uint8_t *data, uint8_t payload_length,
ok, all good. thanks for clarifying.

2020-10-13 02:06 UTC, merged