Wifi basic coop
OttoWinter/esphomeyaml pull request #1306
Opened 2020-09-30 22:19 UTC by motwok

## Description:
Make the wifi component a bit cooperative to other wifi based protocols like ESP-now and ESP-mesh.

Basic means just replace/remove all disabeling of WIFI_STA mode because this removes configuration and disables the other protocol.

To do so the component that needs this simple defines WIFI_BASIC_COOP.

This is mandatory for #1290 to work correctly, due to problems with resources (namely cryptograpy) it is needed that ESP-Now is initialized before Wifi.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [-] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [-] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-09-17 10:36 UTC, motwok commented
Push for the first annual

2022-01-03 02:29 UTC, d3wy commented
Attempting to compile on latest dev branc comes up the following errors:
`src/esphome/components/network/util.cpp: In function 'esphome::network::IPAddress esphome::network::get_ip_address()':
src/esphome/components/network/util.cpp:36:56: error: could not convert 'esphome::wifi::WiFiComponent::get_ip_address()()' from 'IPAddress' to 'esphome::network::IPAddress'
     return wifi::global_wifi_component->get_ip_address();
                                                        ^
*** [.pioenvs/espnowserver/src/esphome/components/network/util.cpp.o] Error 1`

Is it possible some other PRs have broken this?

2022-01-21 19:05 UTC, martgras requested changes
LGTM in general but wifi_component_esp_idf and wifi_component_esp32_arduino the same modifications. 
Since the PR is older it's based on pre idf refactoring efforts. Needs updating to the new structure

2022-01-21 19:05 UTC, martgras commented on esphome/components/wifi/wifi_component_esp32.cpp
> +#ifndef WIFI_BASIC_COOP
esphome/components/wifi/wifi_component_esp32.cpp no longer exists. 
It was split in wifi_component_esp32.cpp and wifi_component_esp32_arduino

2022-02-08 23:54 UTC, motwok commented on esphome/components/wifi/wifi_component_esp32.cpp
> +#ifndef WIFI_BASIC_COOP
i see... this will be fixed with a general change soon

2022-05-17 00:45 UTC, closed without merging