Fix ligt trigger
OttoWinter/esphomeyaml pull request #1308
Opened 2020-09-30 22:51 UTC by MartinWelsch

## Description:

The trigger `on_turn_on` now triggers immediately when the light is turned on.
The trigger `on_turn_off` now triggers after the light is actually off.

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/1521

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-10-01 01:02 UTC, glmnet commented on esphome/components/light/light_transformer.h
> +  bool publish_at_end() override { return true; }
This makes publish at end true in all (2) overriden cases

2020-10-02 03:57 UTC, MartinWelsch commented on esphome/components/light/light_transformer.h
> +  bool publish_at_end() override { return true; }
I can't find any classes deriving from this but i guess that this does not match with the documented behavior of `add_new_remote_values_callback`, so i added the callback `target_state_reached_callback_` which does not involve publishing.

2020-10-05 19:40 UTC, MaartenKleijwegt commented
Just did some quick tests, but this also seems to fix https://github.com/esphome/issues/issues/1534. With the quick tests I've done I'm not seeing the erratic behavior anymore

might this also fix https://github.com/esphome/issues/issues/1526 ?

2020-10-05 23:58 UTC, glmnet requested changes
On turn off is not working properly

2020-10-05 23:58 UTC, glmnet commented on esphome/components/light/light_state.cpp
> +      ESP_LOGD(TAG, "Reached the target state of %.5f.", this->current_values.get_state());
Will need to change to lower verbosity or remove before merge

2020-10-05 23:58 UTC, glmnet commented on esphome/components/light/automation.h
> +    this->last_on_ = a_light->current_values.is_on();
This should still happen on `new_remote_values_callback` otherwise this state is not updated if light is turned on -> turned off before it fully turns on and hence `should_trigger` does not set

2020-10-06 20:14 UTC, MartinWelsch commented on esphome/components/light/automation.h
> +    this->last_on_ = a_light->current_values.is_on();
The problem with `new_remote_values_callback` in case of `LightTurnOffTrigger` is that it is called before `a_light->current_values` is updated (due to transitions), so `a_light->current_values.is_on()` returns `true` when the light is turned off. If the remote value is used, the trigger would get triggered too early (before the transition finishes).
Your statement regarding not triggering for rapid switching is correct, missed that while testing.

It turns out that because of `target_state_reached_callback` being only called when a transition finishes, keeping track of the last on/off-state is not needed because there is no transition to `off` that does not result in the light emitting no light.

2020-10-11 01:50 UTC, glmnet commented on esphome/components/light/automation.h
> +    this->last_on_ = a_light->current_values.is_on();
Thanks, this clears up possible breaking changes and now it seems more streamlined.
Note that on_turn_on might re - trigger if you turn off then quickly back turn on again, however I don't think this is a problem.

2020-10-11 01:50 UTC, merged