Midea climate support
OttoWinter/esphomeyaml pull request #1328
Opened 2020-10-11 12:18 UTC by dudanov

## Description:
Added initially support for Midea UART Protocol climate devices (air conditioners).

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-11-23 13:32 UTC, Lumpusz commented on esphome/components/midea_ac/midea_frame.h
> +enum MideaFanMode : uint8_t {
My Midea AC actually supports 6 fan modes: 20%, 40%, 60%, 80%, 100%, auto. How this is being supported?

2020-11-23 18:32 UTC, dudanov commented on esphome/components/midea_ac/midea_frame.h
> +enum MideaFanMode : uint8_t {
This component is unofficial.  It appeared thanks to the work of several people who were engaged in reverse engineering of the UART protocol.  Therefore, at the moment, not all features are supported.  The main problem is that each has its own air conditioner model, usually for household use.  If you have the necessary skills and can understand your air conditioner modification, provide the necessary data and ideas, then you are welcome.  Here is a link to a Telegram group dedicated to this topic, created by @mac-zhou

2020-11-23 20:56 UTC, Lumpusz commented on esphome/components/midea_ac/midea_frame.h
> +enum MideaFanMode : uint8_t {
Don't get me wrong, I did not mean to criticize. I think what you did is amazing, and thank you for the hard work. I have already joined your telegram. But to give it a thorough test I need to have your harware dongle manufactured and soldered. This is a very good start. We may be able to add more to it. Other thing I was wondering about is have you ever tried to read the power consumption? My unit reports it and I can see it in the Midea app. I would be interested to know how you reverse engineered the UART protocol.

2021-03-07 15:32 UTC, jcam commented
@dudanov It looks like you (and others) put a *lot* of work into this. Do you know what would be needed to get it merged? Anything another random sometimes-python-coder on the internet could help with?

2021-03-07 19:48 UTC, dudanov commented
> @dudanov It looks like you (and others) put a _lot_ of work into this. Do you know what would be needed to get it merged? Anything another random sometimes-python-coder on the internet could help with?

Thanks for mention. I have corrected the code to reflect the new upstream changes. Now it's up to the maintainers. @jesserockz

2021-03-07 20:00 UTC, jesserockz commented on esphome/components/midea_ac/midea_climate.cpp
> +}
Are all AC units the same in terms of features they support and min/max or should these be configurable via yaml?

2021-03-07 20:04 UTC, dudanov commented on esphome/components/midea_ac/midea_climate.cpp
> +}
The basic functionality is hardcoded into the code. Advanced functions that are found in expensive models are configured via yaml. As new features are requested, the optional parameters will expand.

2021-03-07 20:30 UTC, jesserockz commented on esphome/components/midea_ac/midea_climate.cpp
> +}
ok
Perhaps don't hardcode the visual temps though, as it would allow people to change their frontend/HA to show a smaller range, or only move in 1 step (not 0.5) if they wanted. 
You can still hard limit the min to 17 with config validation, same for max and steps.

2021-03-07 20:36 UTC, dudanov commented on esphome/components/midea_ac/midea_climate.cpp
> +}
Okay. You are right, it will be more convenient. I'll add options and mention you. Thanks.

2021-03-07 21:17 UTC, dudanov commented on esphome/components/midea_ac/midea_climate.cpp
> +}
@jesserockz 
This hardcoded parameters already may be overriden by Climate Core component.
Need just add in this case
```
midea_ac:
  visual:
    min_temperature: 18 °C
    max_temperature: 25 °C
    temperature_step: 0.1 °C
```
to midea_ac component configuration.
I verified, it works.

2021-03-07 21:39 UTC, jesserockz commented on esphome/components/midea_ac/midea_climate.cpp
> +}
Ah ok just looked into climate and it overrides them after fetching `MideaAC::traits()`

2021-03-16 06:38 UTC, Lumpusz commented
@dudanov @jesserockz @glmnet What is still missing to get this PR merged, along with the related ones?

2021-03-17 15:03 UTC, glmnet requested changes
Please see inline comments, thanks

2021-03-17 17:44 UTC, dudanov commented on esphome/components/midea_ac/__init__.py
> +from esphome.components import climate, sensor
Done.

2021-03-17 17:44 UTC, dudanov commented on esphome/components/midea_ac/__init__.py
> +AUTO_LOAD = ["climate", "sensor"]
Done.

2021-03-17 17:45 UTC, dudanov commented on esphome/components/midea_ac/midea_climate.h
> +  sensor::Sensor *power_sensor_;
Done.

2021-03-17 17:45 UTC, dudanov commented on esphome/components/midea_ac/__init__.py
> +            cv.Optional(CONF_SWING_BOTH): cv.boolean,
Done.

2021-03-17 17:45 UTC, dudanov commented on esphome/components/midea_ac/midea_climate.h
> +  uint8_t request_num_;
Done.

2021-03-17 17:48 UTC, dudanov commented on esphome/components/midea_dongle/midea_frame.h
> +  Frame() = delete;
The default constructor has been removed, since the only field in the class is a pointer to a buffer. It cannot be nullptr. It is initialized with an other explicit constructor.

2021-03-17 17:57 UTC, glmnet commented
I'm adding needs-tests label, this is you modify one of the testn.yaml files to include your component with a default configuration, this way code is compiled on the CI

2021-03-17 18:56 UTC, glmnet approved these changes

2021-03-17 19:02 UTC, jesserockz commented
Your dongle requires WiFi, but you added the tests to test4 which only has ethernet. Try `test1.yaml` or `test3.yaml`

2021-03-17 19:04 UTC, glmnet commented
> Your dongle requires WiFi, but you added the tests to test4 which only has ethernet. Try `test1.yaml` or `test3.yaml`

Does it really need wifi?

2021-03-17 19:07 UTC, jesserockz commented
Also should this be restricted to a device that has wifi? Or should it just fake that data if someone wanted to do it with ethernet for example?

I just looked at the hardware dongle, very cool

2021-03-17 19:08 UTC, glmnet commented
FYI @dudanov ESPHome also supports ethernet connectivity, in that case wifi component is not loaded. You just happened to choose a test file configured with ethernet

2021-03-17 19:17 UTC, glmnet commented
> `Too many candidates found for 'uart_id' type 'uart::UARTComponent' Some are 'uart0', 'adalight_uart'.`

🥰

2021-03-17 19:32 UTC, dudanov commented
Thanks, @glmnet , @jesserockz 👍

2021-03-17 19:37 UTC, glmnet commented on esphome/components/midea_dongle/midea_dongle.cpp
> +      wifi_stretch = this->notify_.get_signal_stretch();
is this really meant to be `stretch` or `strength` ?

2021-03-17 19:42 UTC, dudanov commented on esphome/components/midea_dongle/midea_dongle.cpp
> +      wifi_stretch = this->notify_.get_signal_stretch();
Fixed :)

2021-03-17 19:58 UTC, jesserockz commented on esphome/components/midea_dongle/midea_frame.h
> +  uint8_t get_signal_stretch() const { return this->pbuf_[12]; }
Do you want to rename these two methods as well?

2021-03-17 20:00 UTC, dudanov commented on esphome/components/midea_dongle/midea_frame.h
> +  uint8_t get_signal_stretch() const { return this->pbuf_[12]; }
You read my mind. Done.

2021-03-17 20:08 UTC, dudanov commented
Sorry for my bad english.

2021-03-17 20:24 UTC, jcam commented
This is a world-wide project! No apologizing :D

2021-03-17 20:27 UTC, glmnet commented
Thanks @dudanov too much back and forth (I'm a terrible reviewer) but it's good now!

2021-03-17 20:27 UTC, merged