Add MHO-C401 BLE smart hygrometer support
OttoWinter/esphomeyaml pull request #1329
Opened 2020-10-12 00:14 UTC by vevsvevs

## Description:

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#806

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-10-13 20:54 UTC, nikito7 approved these changes

2020-11-04 03:52 UTC, nikito7 commented
When merged?

2020-11-04 05:30 UTC, jesserockz requested changes

2020-11-04 05:30 UTC, jesserockz commented on esphome/components/xiaomi_mhoc401/sensor.py
> +AUTO_LOAD = ['xiaomi_ble']
Please add yourself as a codeowner and run `script/build_codeowners.py`
```suggestion
CODEOWNERS = ['@vevsvevs']
DEPENDENCIES = ['esp32_ble_tracker']
AUTO_LOAD = ['xiaomi_ble']
```

2020-12-05 21:29 UTC, vevsvevs commented
@jesserockz I've applied suggested changes, but now check fails with `CODEOWNERS file is not up to date`. Running locally `script/build_codeowners.py` also fails for me, so now I'm stuck :(

2021-01-23 19:59 UTC, nikito7 commented
New PR here: https://github.com/esphome/esphome/pull/1486

2021-01-27 07:14 UTC, closed without merging