Add climate.hitachi_ac344
OttoWinter/esphomeyaml pull request #1336
Opened 2020-10-27 02:25 UTC by honomoa

## Description:

Add support Hitachi A/C for 344 bits protocol(tested with RAS-22YK1, RAS-25YK1, RAS-36YK1), and RF10T1 controller.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#822

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-11-09 02:43 UTC, glmnet requested changes
please clean up commented code and review log levels

2020-11-09 02:43 UTC, glmnet commented on esphome/components/hitachi_ac344/hitachi_ac344.cpp
> +    //       *(ptr + i), *(ptr + i));
please remove commented code

2020-11-09 02:43 UTC, glmnet commented on esphome/components/hitachi_ac344/hitachi_ac344.cpp
> +  // remote_state_[HITACHI_AC344_TEMP_BYTE] = temp << HITACHI_AC344_TEMP_OFFSET;
please remove

2020-11-09 02:43 UTC, glmnet commented on esphome/components/hitachi_ac344/hitachi_ac344.cpp
> +  // remote_state_[HITACHI_AC344_FAN_BYTE] = (new_speed << 4) | get_mode_();
remove

2020-11-09 02:43 UTC, glmnet commented on esphome/components/hitachi_ac344/hitachi_ac344.cpp
> +  // HITACHI_AC344_SWINGV_OFFSET);
remove

2020-11-09 02:43 UTC, glmnet commented on esphome/components/hitachi_ac344/hitachi_ac344.cpp
> +  //          remote_state[HITACHI_AC344_SWINGV_BYTE], swing_modev);
remove

2020-11-09 02:43 UTC, glmnet commented on esphome/components/hitachi_ac344/hitachi_ac344.cpp
> +  // remote_state[HITACHI_AC344_BUTTON_BYTE] = HITACHI_AC344_BUTTON_POWER
remove

2020-11-09 02:43 UTC, glmnet commented on esphome/components/hitachi_ac344/hitachi_ac344.cpp
> +  // this->parse_mildewproof_(recv_state);
remove

2020-11-09 02:43 UTC, glmnet commented on esphome/components/hitachi_ac344/hitachi_ac344.cpp
> +  // remote_state_[HITACHI_AC344_MODE_BYTE] = (remote_state_[HITACHI_AC344_MODE_BYTE] & 0xF0) | (new_mode & 0xF);
remove

2020-11-09 02:43 UTC, glmnet commented on esphome/components/hitachi_ac344/hitachi_ac344.cpp
> +    ESP_LOGV(TAG, "Header fail");
```suggestion
    ESP_LOGVV(TAG, "Header fail");
```

Change those to very verbose, this will be logged even when stuff not related to this integration is received.

2020-11-12 03:41 UTC, honomoa commented
I cleaned up the comment and changed the log verbosity.

2020-11-13 20:46 UTC, glmnet approved these changes

2020-11-18 01:05 UTC, merged