Added heatpumpir support
OttoWinter/esphomeyaml pull request #1343
Opened 2020-10-29 07:42 UTC by rob-deutsch

## Description:
The heatpumpir platform supports dozens of manufacturers and hundreds of AC units by utilising the Arduino-HeatpumpIR library.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#826

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-11-01 23:35 UTC, rob-deutsch commented
@jesserockz , are you the right person to ask this question to?

Are there some tools I can/should use to automatically format the code correctly? Or do I need to go through and do it by hand?

2020-11-02 01:17 UTC, jesserockz commented
If you have the environment set up and run `script/quicklint` it can make the fixes for you to commit.
If you have docker, inside the esphome directory `docker run -it --rm -v $(pwd):/esphome esphome/esphome-lint:latest script/quicklint`

2020-11-11 06:30 UTC, rob-deutsch commented
Thanks @jesserockz .

I've fixed almost all of the issues. Except I can't figure out why the linting tests can't find `<IRSender.h>` despite being able to find `<HeatpumpIRFactory.h>` which is supplied by the same package.

Any suggestions?

2020-11-18 01:00 UTC, glmnet requested changes
Moving the protocol instantiation code to a place where it is executed once might be way better.

On the other hand, I believe this library will not be very well accepted in ESPHome, usually we don't allow libraries integrations and just run our own implementation of much stuff.

Exceptions are there, e.g. NeoPixel, FASTLed, TinyGPS, etc. 
This one is quite good in the sense it uses ESPHome IR api inside to adapt the library so I like it.

Many of the protocols of this library are already supported by native ESPHome components, so for those there will be two options now.

I would rather like the contribution to be on your own AC, this way you contribute code you know works and maintain 100% of it, this way it is a source of dead code may be, an we rely on maintenance of the library.

I guess we can make the exception for now, but of course we cannot support any third party library.

Did not check docs yet, but they should state this relies on a library not supported by ESPHome

2020-11-18 08:31 UTC, rob-deutsch commented on platformio.ini
> +    IRremoteESP8266@2.7.11
IRremoteESP8266 is needed just to allow the CI linting checks to pass, because one of the HeatpumpIR header files we use here includes (unfortunately) a header file from IRremoteESP8266, but it isn't explicitly listed as a dependency.

I have submitted a PR to HeatpumpIR to include this library as a dependency so it doesn't have to be explicitly mentioned by esphome.

For now I will move this library to the esp8266 section of the platformio.ini file.

2020-11-18 08:32 UTC, rob-deutsch commented on esphome/components/heatpumpir/heatpumpir.cpp
> +  HeatpumpIR *heatpump_ir = protocol_constructor->second();
Thanks. I have done so and will submit new commits.

2020-11-20 01:02 UTC, rob-deutsch commented
@glmnet, thanks for your review and feedback. I have made all the adjustments you suggested, and it is ready to be merged.

I understand and agree with all your thoughts on third party libraries.

Fyi I am currently using this code to control my Mitsubishi Heavy aircon.

2021-08-03 08:38 UTC, OttoWinter commented
This is indeed an interesting case.

Normally, I'd not be in favor of this because with external libraries we can't use our own IR abstractions (and thus get anything from features implemented there, like RMT peripheral for ESP32).

But in this case the sending is done by a IRSenderESPHome, which looks like a very nice solution.

Because this adds a lot of value, I agree we should add this :+1: As @glmnet said, we should make clear though that if a platform is already implemented by another "native" integration, users should use that instead.

Seems like the issue with the library include is not fully fixed. From my side it's ok to include it to platformio.ini for the time being (but add a comment that this is only a temporary hack, and other integrations shouldn't use that lib)

2021-08-21 13:40 UTC, rob-deutsch commented
Thank you for the comments @OttoWinter, I will look into the issue during the week and amend the PR.

2021-08-22 04:27 UTC, rob-deutsch commented
@OttoWinter @jesserockz @glmnet I've updated all the changes as requested, including the PR to esphome-docs (esphome/esphome-docs#826)

Could you please merge this?

2021-08-25 19:49 UTC, nrehn commented
Hi,

I need support for Panasonic heatpump, 
I have IR reciver etc. up and running. Tell me what to provide you with and I will send it.

BR N

2021-08-25 19:59 UTC, jesserockz commented
> Hi,
> 
> I need support for Panasonic heatpump, 
> I have IR reciver etc. up and running. Tell me what to provide you with and I will send it.
> 
> BR N

@nrehn it would be good if you could test https://github.com/esphome/esphome/pull/1998

2021-08-26 07:38 UTC, nrehn commented
> > Hi,
> > I need support for Panasonic heatpump,
> > I have IR reciver etc. up and running. Tell me what to provide you with and I will send it.
> > BR N
> 
> @nrehn it would be good if you could test #1998

Thanks.
I have esphome dev installed in HA but I still get "Platform not found"
![image](https://user-images.githubusercontent.com/22245798/130921105-f1a8def6-adf7-4ab4-b593-00adac611c12.png)

What do I do wrong ?

BR N

2021-08-26 16:58 UTC, nrehn commented
> > > Hi,
> > > I need support for Panasonic heatpump,
> > > I have IR reciver etc. up and running. Tell me what to provide you with and I will send it.
> > > BR N
> > 
> > 
> > @nrehn it would be good if you could test #1998
> 
> Thanks.
> I have esphome dev installed in HA but I still get "Platform not found"
> ![image](https://user-images.githubusercontent.com/22245798/130921105-f1a8def6-adf7-4ab4-b593-00adac611c12.png)
> 
> What do I do wrong ?
> 
> BR N

Should I use external_components ?

I have tried adding the following without any luck.

external_components:
  - source:
      type: git
      url: https://github.com/WeekendWarrior1/esphome
      ref: panasonic_climate
    components: [ climate ]

still don't work..

2021-09-16 04:28 UTC, WeekendWarrior1 commented
> Should I use external_components ?


The component is (currently) simply called "panasonic", so try this:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/WeekendWarrior1/esphome
      ref: panasonic_climate
    components: [ panasonic ]
    
climate:
  - platform: panasonic
    name: "Lounge AC"
    receiver_id: rcvr
    supports_horizontal_swing: true
```

2021-09-22 14:53 UTC, oxan approved these changes
I've merged in the dev branch and fixed the resulting compile/analysis errors that arised from conflicting changes in the meantime. Hope you don't mind :)

I think this is indeed ready to be merged now.

2021-10-03 12:25 UTC, nrehn commented
> > Should I use external_components ?
> 
> The component is (currently) simply called "panasonic", so try this:
> 
> ```yaml
> external_components:
>   - source:
>       type: git
>       url: https://github.com/WeekendWarrior1/esphome
>       ref: panasonic_climate
>     components: [ panasonic ]
>     
> climate:
>   - platform: panasonic
>     name: "Lounge AC"
>     receiver_id: rcvr
>     supports_horizontal_swing: true
> ```

Unfortunately still the same ,,  :(

![image](https://user-images.githubusercontent.com/22245798/135753517-cc3f1a86-02d9-42f8-881f-c5d007c114e8.png)

Anyone else have an idea ?

2021-10-12 18:36 UTC, jesserockz approved these changes

2021-10-12 18:38 UTC, merged