[WIP] Separate temperature_multiplier to current/target multiplier
OttoWinter/esphomeyaml pull request #1345
Opened 2020-10-30 21:49 UTC by Yarikx

## Description:
Some Tuya thermostats have different multipliers for current and target temperatures.
So the current approach (having a single `temperature_multiplier`) cannot handle both cases.

This is breaking change, it introduces separate multipliers for both values

**Related issue (if applicable):

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-10-30 22:55 UTC, jesserockz requested changes
Please make this non-breaking by making the original still available in yaml. 
You can make the config schemas exclusive and just set the 2 values in cpp to be the same if the existing config option is used.

2020-11-08 03:12 UTC, jesserockz requested changes
I made some suggested changes you can apply below to make this a non-breaking change. 
It allows either `temperature_multiplier` **OR** (`current_temperature_multiplier` **AND** `target_temperature_multiplier`) and will just default to 1.0 or both if none are supplied.
Thanks

2020-11-08 03:12 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
> +    cv.Optional(CONF_TARGET_TEMPERATURE_MULTIPLIER, default=1): cv.positive_float,
```suggestion
    cv.Optional(CONF_TEMPERATURE_MULTIPLIER): cv.positive_float,
    cv.Optional(CONF_CURRENT_TEMPERATURE_MULTIPLIER): cv.positive_float,
    cv.Optional(CONF_TARGET_TEMPERATURE_MULTIPLIER): cv.positive_float,
```

2020-11-08 03:12 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
>      CONF_TARGET_TEMPERATURE_DATAPOINT, CONF_SWITCH_DATAPOINT))
```suggestion
    CONF_TARGET_TEMPERATURE_DATAPOINT, CONF_SWITCH_DATAPOINT), validate_temperature_multipliers)
```

2020-11-08 03:12 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
> +    cg.add(var.set_target_temperature_multiplier(config[CONF_TARGET_TEMPERATURE_MULTIPLIER]))
```suggestion
    if CONF_TEMPERATURE_MULTIPLIER in config:
        cg.add(var.set_target_temperature_multiplier(config[CONF_TEMPERATURE_MULTIPLIER]))
        cg.add(var.set_current_temperature_multiplier(config[CONF_TEMPERATURE_MULTIPLIER]))
    else:
        cg.add(var.set_current_temperature_multiplier(config[CONF_CURRENT_TEMPERATURE_MULTIPLIER]))
        cg.add(var.set_target_temperature_multiplier(config[CONF_TARGET_TEMPERATURE_MULTIPLIER]))
```

2020-11-08 17:00 UTC, Yarikx commented
@jesserockz Thank you for the suggestions!
I made similar changes in local branch, but using voluptuous Exclusive.
But with your approach, the custom error messages are more user friendly.
Thanks!

2020-11-08 18:01 UTC, jesserockz approved these changes
I tried with voluptuous Exclusive but could not work out how to make the existing exclusive to both the split ones. What did you do locally?

2020-11-09 08:00 UTC, Yarikx commented
I used two separate "exclusive" groups, like:
```python
    cv.Exclusive(CONF_TEMPERATURE_MULTIPLIER, CONF_CURRENT_TEMPERATURE_MULTIPLIER, CONF_TARGET_TEMPERATURE_MULTIPLIER): cv.positive_float,
    cv.Exclusive(CONF_CURRENT_TEMPERATURE_MULTIPLIER, CONF_CURRENT_TEMPERATURE_MULTIPLIER): cv.positive_float,
    cv.Exclusive(CONF_TARGET_TEMPERATURE_MULTIPLIER, CONF_TARGET_TEMPERATURE_MULTIPLIER): cv.positive_float,
```

and then in `to_code`:

```python
    current_temperature_multiplier = 1.0
    target_temperature_multiplier = 1.0
    if CONF_TEMPERATURE_MULTIPLIER in config:
        current_temperature_multiplier = config[CONF_TEMPERATURE_MULTIPLIER]
        target_temperature_multiplier = config[CONF_TEMPERATURE_MULTIPLIER]
    else:
        if CONF_CURRENT_TEMPERATURE_MULTIPLIER in config:
            current_temperature_multiplier = config[CONF_CURRENT_TEMPERATURE_MULTIPLIER]
        if CONF_TARGET_TEMPERATURE_MULTIPLIER in config:
            target_temperature_multiplier = config[CONF_TARGET_TEMPERATURE_MULTIPLIER]

    cg.add(var.set_current_temperature_multiplier(current_temperature_multiplier))
    cg.add(var.set_target_temperature_multiplier(target_temperature_multiplier))
```

2020-11-11 17:31 UTC, merged