Adding ADE7953 irq_pin
OttoWinter/esphomeyaml pull request #1359
Opened 2020-11-06 16:31 UTC by djwmarcx

## Description:

**Related issue :** fixes https://github.com/esphome/issues/issues/1529

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation:** esphome/esphome-docs#836

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-11-08 07:02 UTC, jesserockz requested changes
This code can be a lot simpler. Take a look below at my suggestions =)

2020-11-08 07:02 UTC, jesserockz commented on esphome/components/ade7953/ade7953.h
> +  }
```suggestion
  void set_irq_pin(GPIOPin *irq_pin) {
    this->irq_pin_ = irq_pin;
  }
```

2020-11-08 07:02 UTC, jesserockz commented on esphome/components/ade7953/ade7953.cpp
> +  }
```suggestion
  if (this->irq_pin_ != nullptr) {
    LOG_PIN("  IRQ Pin: ", this->irq_pin_);
  }
```

2020-11-08 10:17 UTC, djwmarcx commented
Thanks for your suggestions, Jesse!

I understand the reason are you proposing those changes. It was my initial approach actually. The problem is that the IRQ pin in the ADE7953 IRQ pin is pulled to HIGH and using the full pin schema can lead to someone setting the pin as INPUT_PULLDOWN causing the overheating problem I'm trying to avoid with my changes. In the Shelly 2.5 specifically, this is not possible because the GPIO doesn't have internal pull down resistor, but in different setups

2020-11-15 19:59 UTC, jesserockz approved these changes
Ok we can leave it as is.

2020-11-15 20:30 UTC, merged