Add action to force-recalibrate the SCD30
OttoWinter/esphomeyaml pull request #1402
Opened 2020-12-01 17:13 UTC by bobobo1618

## Description:

Adds an automation action to force-recalibrate the SCD30 sensor.

Note: this is my first contribution to this repository so I expect the PR not to be ready as-is. I'd like to leave updating the docs until the PR has seen at least preliminary review.

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-12-01 22:38 UTC, jesserockz commented on esphome/components/scd30/sensor.py
> +    yield var
Im not sure there is any point in making the value optional as its the whole point of the action...
Other than that, just fix up the lint issues and it should be good.

2020-12-02 10:39 UTC, lukasleitsch commented
I have looked for a way to force calibrate the SCD30. Thanks for your PR. It seems there is also a PR to achieve a force calibration. Maybe there is way to merge the two PRs.

https://github.com/esphome/esphome/pull/1237

2020-12-02 17:15 UTC, bobobo1618 commented on esphome/components/scd30/sensor.py
> +    yield var
Good point, I didn't think too much about that. Done.

2020-12-02 17:16 UTC, bobobo1618 commented
I made a separate PR for docs: https://github.com/esphome/esphome-docs/pull/866

2020-12-02 17:20 UTC, bobobo1618 commented
> I have looked for a way to force calibrate the SCD30. Thanks for your PR. It seems there is also a PR to achieve a force calibration. Maybe there is way to merge the two PRs.
> 
> #1237

I had a look at the PR and I don't think there's much to merge. @zeroping can comment if he thinks otherwise but I think the main differences between my PR and his are that I'm adding just the action and the action takes the CO2 concentration as an argument, while his also adds actions for the ASC.

He seemed to think that an argument would be a good idea but didn't know how to do it, so I think that's a good thing to keep.

As for the ASC actions, I don't think they make sense, as the ASC setting is reset to whatever is in the configuration on every boot. Unless there's a way to persist the ASC change across reboots, I think it's more confusing than anything.

2020-12-02 18:01 UTC, zeroping commented
Hunh. You know, I'm not actually sure if the ASC setting is kept across reboots. I think I saw this line in the datasheet:

> ASC status is saved in non-volatile memory. When the sensor is powered down while ASC is activated SCD30 will continue with automatic self-calibration after repowering without sending the command.
... and just assumed they meant the value for ASC enable. Maybe they mean the calculated ASC parameters? I'm not sure I've actually tested it.

@bobobo1618, can you confirm if the ASC enable value gets reset to '1' on a power cycle? Mine is a bit tied up, although I might be able to perform a test in the coming weeks.

Point is, if it is stored in persistent memory inside the module, it might be worth keeping asc_disable and asc_enable. Or maybe just setting it every time on power-up, to be sure of the state, although that would be a breaking change for some current SDC30 users.

Either way, I hope one of these two gets merged - but I don't care much which one. @bobobo1618, thanks for poking at this feature with me, even if it's in parallel. I have a system that is doing forced recalibration using outside air and a tiny air pump, and once something is merged, I'd like to add a write-up to the wiki about it, since baseline calibration is so important for CO2 sensors.

2020-12-02 18:22 UTC, bobobo1618 commented
> I'm not actually sure if the ASC setting is kept across reboots

The _SCD30_ persists it across reboots, _esphome_ does not.

> Or maybe just setting it every time on power-up, to be sure of the state, although that would be a breaking change for some current SDC30 users

That's the current behaviour: https://github.com/esphome/esphome/blob/3afb564a486b7f4744d58639b073575113b7314b/esphome/components/scd30/scd30.cpp#L64

I think leaving the esphome configuration as the source of truth makes sense. That's the easiest logic to reason about: "it does what I say in the config".

2020-12-02 18:34 UTC, zeroping commented
> That's the current behaviour:
Yep. I had forgotten that. Then we don't risk breaking anything for anyone!
> I think leaving the esphome configuration as the source of truth makes sense.
Totally agree.

In that case, it sounds like you PR is simpler, but has everything we really need anyways. I guess it would be helpful if I tested your PR against my hardware setup here?

2020-12-02 19:10 UTC, bobobo1618 commented
By all means, feel free! I have tested it on my own as well though.

2021-03-19 11:25 UTC, jesserockz requested changes

2021-03-19 11:25 UTC, jesserockz commented on esphome/components/scd30/automation.h
> +    }
If it is `required` in config validation, then no need to check if it has a value here
```suggestion
    this->scd30_->set_forced_recalibration_value(this->forced_recalibration_value_.value(x...));
```

2021-03-19 19:47 UTC, bobobo1618 commented on esphome/components/scd30/automation.h
> +    }
Done

2021-03-19 19:53 UTC, jesserockz commented on esphome/components/scd30/scd30.cpp
> +  this->set_timeout(1000, [this]() {
Why have you wrapped the whole setup function in a timeout?
If you want it to initialize later on in the cycle you just need to change [the setup priority](https://github.com/esphome/esphome/pull/1402/files#diff-5644f5351ceeef961b3f9ba95cf6165608054f226eba0d7ab6e737d6cdbfd0f3R27)
```

2021-07-28 13:18 UTC, geoffrey-vl commented
I may need this feature. How can I help to it merged?

2021-10-27 14:47 UTC, zeroping commented
IIRC, @bobobo1618 and I both made an attempt at this independently, with my attempt over in https://github.com/esphome/esphome/pull/1237. I think we determined that this version looked better than mine.

I still have this hardware running in a window, so I can test. I think we should get this PR merged, as calibration is so important for CO2 sensors.

@bobobo1618, do you have time to fix the branch up? Should I do anything to try to help?

2021-10-28 06:39 UTC, bobobo1618 commented
I no longer feel motivated to contribute to ESPHome after the way this PR and https://github.com/esphome/esphome/pull/1561 were handled, I'm just going to maintain a small fork for my own use. 

If you want, feel free to clone my branch and create a new PR or take any of my changes into yours.

2021-10-28 06:39 UTC, closed without merging