teleinfo: use text_sensor and sensor.
OttoWinter/esphomeyaml pull request #1403
Opened 2020-12-02 20:10 UTC by 0hax

## Description:

Create a Teleinfo platform and add possibility to define sensor or
text_sensor separately.
Without this commit there was no way to read a Teleinfo label returning
text instead of numbers.
Now that text_sensor is supported, once can publish state about 'text'
information too.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-12-30 10:21 UTC, jesserockz requested changes
Just one small change i came across

2020-12-30 10:21 UTC, jesserockz commented on esphome/components/teleinfo/teleinfo.h
> +  virtual void dump_config(){};
```suggestion
  virtual void publish_val(std::string val);
```

2021-01-01 17:57 UTC, 0hax commented on esphome/components/teleinfo/teleinfo.h
> +  virtual void dump_config(){};
Don't we need dump_config() in `TeleInfoListener` class as it is used in `TeleInfo::dump_config()` via `element->dump_config();`
The function is defined in `esphome/components/teleinfo/sensor/teleinfo_sensor.cpp` for example.

2021-01-02 01:49 UTC, jesserockz commented on esphome/components/teleinfo/teleinfo.h
> +  virtual void dump_config(){};
`TeleInfoListener` does not need it. `Component` defines it for all components. 
You don't need to `dump_config` manually for any child sensor as the method will be called by the core code. This way would mean each sensor is dumped twice.

2021-01-02 19:46 UTC, 0hax commented on esphome/components/teleinfo/teleinfo.h
> +  virtual void dump_config(){};
Ah right, thanks for explaining.

2021-01-04 12:02 UTC, 0hax commented
@jesserockz I have applied your suggestion and rebased to latest dev.

2021-01-15 20:25 UTC, glmnet approved these changes

2021-01-28 13:06 UTC, 0hax commented
Should I fix the conflict or you are going to do that?

2021-01-28 14:00 UTC, glmnet commented
Ahh please keep it ready to merge

2021-01-28 14:13 UTC, 0hax commented
> Ahh please keep it ready to merge

Ok I will rebase it

2021-01-28 18:46 UTC, jesserockz approved these changes

2021-01-28 18:48 UTC, jesserockz commented
@glmnet Considering this is a `breaking change`, do you want it in `1.16.0` as the original code is only there too so if this was merged and released, then its not breaking to stable, only within dev/beta

2021-02-15 16:22 UTC, 0hax commented
Did you merge this somewhere at the end ?
It would be good to have it in the final release with the update on the doc as well: #871

2021-03-19 17:20 UTC, 0hax commented
Any news on this guys? @jesserockz @glmnet 
I think it would be good to merge this

2021-05-19 10:44 UTC, 0hax commented
Hi @jesserockz @glmnet
Do you need anything from me before merging this ?

2021-05-19 10:47 UTC, jesserockz commented
> Hi @jesserockz @glmnet
> Do you need anything from me before merging this ?

Merge conflicts by the looks 😉
But otherwise I think I was happy. Will give a quick look over after the conflicts are fixed

2021-05-19 20:14 UTC, 0hax commented
> > Hi @jesserockz @glmnet
> > Do you need anything from me before merging this ?
> 
> Merge conflicts by the looks wink
> But otherwise I think I was happy. Will give a quick look over after the conflicts are fixed

Ahah sorry I was thinking you were not sure about merging it.
I have fixed the merge conflicts, not sure why but the lint test is failing during the test whereas it's ok locally.
Known issue?
Running `black sphome/components/teleinfo/__init__.py` is fine locally

2021-05-19 22:46 UTC, jesserockz commented
It's the sensor and text_sensor init files not the component init file that need black.

2021-05-20 07:07 UTC, 0hax commented
> It's the sensor and text_sensor init files not the component init file that need black.

Ah right, should be fine now. Thank you

2021-06-01 01:32 UTC, merged

2021-06-05 00:48 UTC, damienclaveau commented
@0hax I have deployed the dev branch with your evolution today, and it's working like a charm.
Thank you for your work on the teleinfo component.

and thank you jesserocks for this awesome project.

2021-06-07 12:19 UTC, 0hax commented
> @0hax I have deployed the dev branch with your evolution today, and it's working like a charm.
> Thank you for your work on the teleinfo component.
> 
> and thank you jesserocks for this awesome project.

Thanks for your feedback, I'm happy to hear it's useful not only for me :)