Fix errors on feit dimmers when commands are sent too quickly
OttoWinter/esphomeyaml pull request #1404
Opened 2020-12-03 02:19 UTC by stubs12

## Description:

This change attempts to fix command/response corruption seen on feit wall dimmers.   The fix in https://github.com/esphome/esphome/pull/1344#issue-513279964 to enforces COMMAND_DELAY between certain commands, this change enforces it between all commands sent to the MCU by queuing commands (including heartbeats) and feeding them out one by one with COMMAND_DELAY between them. Feit wall dimmers seem particularly sensitive to command timing, and corrupt commands/responses when commands are sent too quickly.  The way heartbeats are scheduled eventually a heartbeat and a different message will occur too close together and cause corruption.  This log from @tijeff shows the corruption:

```
> 00275.438,Mcu,Check:OK.,Data:55,AA,03,00,00,01,01,04,
> 00276.430,Esp,Check:OK.,Data:55,AA,00,00,00,00,FF,
> 00276.439,Mcu,Check:OK.,Data:55,AA,03,00,00,01,01,04,
> 00277.432,Esp,Check:OK.,Data:55,AA,00,00,00,00,FF,
> 00277.440,Mcu,Check:OK.,Data:55,AA,03,00,00,01,01,04,
> 00278.430,Esp,Check:OK.,Data:55,AA,00,00,00,00,FF,
> 00278.439,Mcu,Check:Bad,Data:55,AA,03,07,00,05,01,01,
> 00278.439,Mcu,Check:OK.,Data:55,AA,03,00,00,01,01,04,
> 00279.430,Esp,Check:OK.,Data:55,AA,00,00,00,00,FF,
> 00279.439,Mcu,Check:OK.,Data:55,AA,03,00,00,01,01,04,
> 00280.431,Esp,Check:OK.,Data:55,AA,00,00,00,00,FF,
```

Since the issue happens very infrequently, it's hard to tell if this resolves the issue or not -- it at least doesn't seem to break anything on the two devices I have (feit wall dimmer and dm_wf_mdv4 dimmer module).  

@jesserockz, @ssieb, @Yarikx, do you see anything here that might cause issues in other devices or break something in the local_time changes?

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-12-31 21:26 UTC, stubs12 commented
Quick update: this change has been rock solid on my tuya devices for the last month -- zero cases of commands lost, and normally my front porch light would have missed a turn on event by now.

Any chance this could get merged so others can benefit?  I know @tijeff was having the same problems with the feit dimmers, and others would benefit as well.

2021-01-22 11:18 UTC, trvrnrth commented
I've got a project on the go to free an [ET-61 thermostat](https://www.ahjiahong.com/thermostat/wifi-thermostat/) from the shackles of tuya. As part of that endeavour I'm intending on adding the option to send periodic time updates which neccessitated a more reliable way to queue up periodic commands. I've pulled these changes in to my dev environment and they seem to be working out nicely :)

One core command handling change I also made was to change the heartbeat to 10 seconds as noted in the official docs rather than 1. I'd be curious to know if that works for your device as it sounds like it has a particularly fussy MCU.

I've got some other fixes in the works as well including for multibyte bitmap/bitmask/fault datapoints and wifi state statuses for MCUs running the v0 protocol that I'll wrap up in a PR in due course.

2021-02-01 03:48 UTC, ic3man5 commented
I have this issue also, I'll test soon and report back

2021-02-02 04:07 UTC, ic3man5 commented
I've installed this PR on majority of my dimmers, I'll report back if I have any issue. Usually takes anywhere from a day to a week to run into the issue.

2021-02-03 17:37 UTC, stubs12 commented
@trvrnrth I know @tijeff on discord lowered the frequency of heartbeats in his testing and had no issues, I can adjust mine to 10s and see if there are any issues.

@MattW2, @ic3man5 your issues sound exactly like the ones this PR resolved for me -- occasional dropped commands, and mashing the buttons leading to an unresponsive MCU.  If the fix works for you we need to make some noise about getting this merged, seems like it's dropped off the radar, not sure why.

2021-02-04 04:17 UTC, ic3man5 commented
> @trvrnrth I know @tijeff on discord lowered the frequency of heartbeats in his testing and had no issues, I can adjust mine to 10s and see if there are any issues.
> 
> @MattW2, @ic3man5 your issues sound exactly like the ones this PR resolved for me -- occasional dropped commands, and mashing the buttons leading to an unresponsive MCU. If the fix works for you we need to make some noise about getting this merged, seems like it's dropped off the radar, not sure why.

2 days so far and no failures yet but too soon to say its good. I have a lot of confidence this is going to work, I thought the same thing and attempted something similar but your implementation is 1000 times better.

2021-02-04 04:24 UTC, ic3man5 commented
Is it possible #1491 will be the actual merged branch?

2021-02-10 16:57 UTC, nuttytree commented
I built a custom Tuya light component that adds a bunch of features [Tuya Light Plus](https://github.com/nuttytree/ESPHome-Devices/blob/master/custom/tuya_light_plus.h).  My testing showed everything was working great so I rolled it out to all my Feit dimmers.  Since then I have I have had nothing but issues with random lost communication between the ESP and Tuya MCU.  My component blasts a lot of extra commands at the Tuya MCU so I am hoping this PR will resolve my issue.  I am going to try and test it on one of the most problematic dimmers to see how it goes.

2021-02-13 23:51 UTC, ssieb requested changes

2021-02-13 23:51 UTC, ssieb commented on esphome/components/tuya/tuya.cpp
> +  // otw buffer data and start scheduling queue processing if needed
otw?

2021-02-13 23:51 UTC, ssieb commented on esphome/components/tuya/tuya.h
> +  std::deque<TuyaCommand> command_queue_;
I would prefer sticking with vector instead of bringing in a new data structure.  You're almost always only going to have one item in the list anyway.

2021-02-14 00:08 UTC, jesserockz commented on esphome/components/tuya/tuya.h
> +  std::deque<TuyaCommand> command_queue_;
Also maybe instead of setting and cancelling an interval everytime, just check last command time in loop and process the first message if the time has elapsed?

2021-02-14 00:18 UTC, ssieb commented on esphome/components/tuya/tuya.h
> +  std::deque<TuyaCommand> command_queue_;
Good point.  The interval is a lot of overhead when the loop is already available.

2021-02-16 22:03 UTC, stubs12 commented on esphome/components/tuya/tuya.h
> +  std::deque<TuyaCommand> command_queue_;
If we don't do a full on queue, how should we handle the cases (rare as they may be) when we do need more than one command queued?  Drop the oldest or the newest?  I've never actually looked at the code, is the deque implementation really terrible?

I can look into bypassing the buffer if the delay has already elapsed since the last command, shouldn't be too hard.

2021-02-16 22:36 UTC, ssieb commented on esphome/components/tuya/tuya.h
> +  std::deque<TuyaCommand> command_queue_;
std::vector is a queue too.  The bigger issue is to avoid the use of set_interval.  It's not necessary, you can just use the loop() to watch for elapsed time.  It will reduce the overhead and make the code a lot simpler.

2021-02-17 04:05 UTC, nuttytree commented on esphome/components/tuya/tuya.cpp
>  }
I wonder if upon failing to validate a message if it makes sense to trigger a DATAPOINT_QUERY command in case the garbled message was a datapoint message?

2021-02-17 17:06 UTC, stubs12 commented on esphome/components/tuya/tuya.cpp
> +  // otw buffer data and start scheduling queue processing if needed
Otherwise.  Removed in lastest updates.

2021-02-17 17:09 UTC, stubs12 commented on esphome/components/tuya/tuya.h
> +  std::deque<TuyaCommand> command_queue_;
I changed to a std::vector, checked if COMMAND_DELAY has already elapsed and bypass the buffer if so, and removed set_interval in favor of just checking each time through the loop.

2021-02-17 17:15 UTC, stubs12 commented on esphome/components/tuya/tuya.cpp
>  }
I'm not sure exactly what you're on to here -- this PR doesn't attempt to recover from corruption, it avoids it in the first place by spacing out messages to the embedded MCU in time.  Many times once the collision occurs the embedded MCU becomes completely unresponsive, the only means of recovery is a power cycle.  Is there another failure mode you're seeing?

2021-02-17 17:44 UTC, trvrnrth commented
Great to see activity on this! @stubs12 Did you get a chance to test with a 10s heartbeat?

2021-02-17 19:59 UTC, kaechele commented
Looks like you tried to merge dev onto your branch rather than rebasing and that created a little bit of a mess with regards to commits.

2021-02-18 20:57 UTC, stubs12 commented
Can anyone offer advice how to clean up my branch/merge/rebase?  I'm not sure what happened . . . still getting up to speed on git/github coming from clearcase/svn

2021-02-18 21:08 UTC, kaechele commented
@stubs12 slightly off topic, but check this out: https://blog.carbonfive.com/always-squash-and-rebase-your-git-commits/

2021-02-18 21:15 UTC, stubs12 commented
I'm not sure of the etiquette, do I need to request review again or just wait?

2021-02-18 21:19 UTC, ssieb commented
I'm not sure what state your repo is in right now, but usually you just need to make sure your dev branch is up to date and then rebase your working branch to that.
```
git switch dev
git pull upstream dev
git switch mybranch
git rebase dev
```
I think I've seen that there's a way to update a branch that you're not currently on, but this is a simple method anyway.  Check `git log` to make sure you haven't added any merge commits.  If you did, you'll want to remove them.  Worst case, make a copy of the files you've been working on, delete the branch and create it again.

2021-02-18 21:23 UTC, kaechele commented
> I'm not sure of the etiquette, do I need to request review again or just wait?

For now I believe it's fine. You may be asked to squash your commits into one commit before the final merge, as the reformatting commits technically are only there to perfect your code for final submission and don't add much value in the broader context of the project.
Doing perfect git commits is both a science and a religion, so different views exist ;-) I found this document useful in trying to perfect my style: https://sethrobertson.github.io/GitBestPractices/
But generally looking at the past commit messages in the repository and seeing if there is a CONTRIBUTING.md is always a good first starting point. In fact, ESPHome does have some info on this here: https://esphome.io/guides/contributing.html#setting-up-git-environment

2021-02-18 21:24 UTC, ssieb commented
> I'm not sure of the etiquette, do I need to request review again or just wait?

A comment that it's ready for review is a good idea.  It wasn't clear if you had made some changes or were just trying to bring the branch up-to-date with dev.  I'm assuming the latter.

2021-02-18 22:36 UTC, ic3man5 commented
> I've installed this PR on majority of my dimmers, I'll report back if I have any issue. Usually takes anywhere from a day to a week to run into the issue.

16 days later and can say it works perfectly fine. The release firmware (not this branch) messed up about 10-20 times.

2021-02-18 23:00 UTC, stubs12 commented
Well, that cleanup didn't work, I'm not sure why the ota files are being included.  Have to go for a while, will pick up again in a few hours.

2021-02-18 23:00 UTC, ssieb commented
You didn't get it quite right.  You shouldn't have a commit for the merge at all, either for adding or removing it.  And there's still a commit that isn't yours.

2021-02-18 23:31 UTC, nuttytree commented on esphome/components/tuya/tuya.cpp
>  }
I just figure it is one more safe guard against ESPHome/Home Assistant being out of sync with the actual state of the light.  However I admit this comment is probably more appropriate on #1491.

2021-02-23 18:54 UTC, stubs12 commented
Finally got the mess cleaned up, I think this is ready to go at last!

2021-02-24 01:54 UTC, MattW2 commented
@stubs12 , thanks for all the hard work to get this into a mergeable state. I've been running https://github.com/stubs12/esphome/tree/tuya_enforce_delay_between_commands on afew of my switches and https://github.com/TheEebb/tasmota-tuyamcu-fix on a few others and as much as I don't like tasmota. The custom version of tasmota has not failed once in over a week. Whereas I had a single failure running this PR.

2021-02-24 17:06 UTC, stubs12 commented
@MattW2, thanks for trying this out -- I'll go take a look at the tasmota fix and see if there's learning to take advantage of.  Out of curiosity, for the switch that failed is it a single location or are multiple dimmers connected together (3-way or 4-way)?  I had a couple that are connected together as 3-way flake out on me, so the bug hunt continues.

I still think it would be worth merging this PR as is, as it greatly reduces the incidence of failure, and esphome is really unusable on these feit dimmers without the fix.  As we learn more additional PRs can be generated.

2021-02-24 18:31 UTC, jesserockz commented on esphome/components/tuya/tuya.cpp
> +           hexencode(command.payload.data(), command.payload.size()).c_str(), this->init_state_);
This can be simplified as the `hexencode` function has an override to accept a vector directly
```suggestion
           hexencode(command.payload).c_str(), this->init_state_);
```

2021-02-24 18:33 UTC, jesserockz approved these changes
Apart from one optional change above, this looks good to me now

2021-02-25 05:26 UTC, ssieb requested changes
As a general comment, `this->` is optional (as long as the following identifier is not ambiguous) and you've been very inconsistent with your use of it.  In all new code I write, I don't use it at all now.  Just something to keep in mind for any future code you write.

2021-02-25 05:26 UTC, ssieb commented on esphome/components/tuya/tuya.cpp
> +  uint8_t len_lo = (uint8_t) command.payload.size() >> 0;
This should really be `& 0xff` instead.

2021-02-25 05:26 UTC, ssieb commented on esphome/components/tuya/tuya.cpp
> +}
This function could be replaced by:
```
command_queue_.push_back(command);
process_command_queue_();
```

2021-02-25 18:32 UTC, ssieb requested changes

2021-02-25 18:32 UTC, ssieb commented on esphome/components/tuya/tuya.cpp
> +  uint8_t len_lo = (uint8_t)(command.payload.size() >> 0) & 0xFF;
Sorry, I guess I should have been more clear.
```
uint8_t len_hi = (uint8_t)(command.payload.size() >> 8);
uint8_t len_lo = (uint8_t)(command.payload.size() & 0xFF);
```

2021-02-25 23:51 UTC, ssieb approved these changes

2021-02-25 23:52 UTC, merged

2021-07-25 06:34 UTC, fake-name commented
This PR, specifically the change of `send_empty_command()` from the old implementation:

```c++
void send_empty_command_(TuyaCommandType command) { this->send_command_(command, nullptr, 0); }
```
to the new implementation 

```c++
void Tuya::send_empty_command_(TuyaCommandType command) {
  send_command_(TuyaCommand{.cmd = command, .payload = std::vector<uint8_t>{0x04}});
}
```
causes the heartbeat to no longer operate on at least some tuya devices.

The old implementation sends empty commands with a zero-length body (which is what the spec says you're supposed to do).
The new implementation sends "empty" commands with a non-empty body containing the literal byte `0x04`. @stubs12 - Was there a reason for the change?

2021-07-25 06:35 UTC, fake-name commented
See https://github.com/esphome/issues/issues/2265