Added I2CMultiplexer in generel and the TCA9548A in special
OttoWinter/esphomeyaml pull request #1410
Opened 2020-12-06 22:02 UTC by andreashergert1984

## Description:
This features adds the possibility to use I2C multiplexer. 
It adds a I2CMultiplexer Class (derived from I2CDevice) to add more known multiplexer.
The famous TCA9548A is included.
on I2CDevices Parameters to activate the channel on a multiplexer was added.
Usage:
Define the TCA9548A as a normal I2CDevice would be: (don´t forget to give it a proper id)
tca9548a:
  - address: 0x70
    id: multiplex0
    i2c_id: i2c0
    scan: True
Add Multiplexer Parameter at any I2CDevice:
  - platform: bmp280
    multiplexer:
      id: multiplex0
      channel: 0
    temperature:
      name: "Outside Temperature 0"
      oversampling: 16x
    pressure:
      name: "Outside Pressure 0"
    address: 0x76
    update_interval: 10s
  - platform: bme280
    multiplexer:
      id: multiplex0
      channel: 5
    temperature:
      name: "Outside Temperature 5"
      oversampling: 16x
    pressure:
      name: "Outside Pressure 5"
    address: 0x76
    update_interval: 10s
  - platform: mpu6050
    multiplexer:
      id: multiplex0
      channel: 5
    address: 0x68
...

**Related feature request :** https://github.com/esphome/feature-requests/issues/807

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#880

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-12-13 21:39 UTC, jesserockz commented
Just a thought, maybe the multiplexer code could be wrapped in an `#ifdef I2C_MULTIPLEXER` so that it does not get compiled in when people are not using it?

2020-12-13 23:22 UTC, andreashergert1984 commented
> Just a thought, maybe the multiplexer code could be wrapped in an `#ifdef I2C_MULTIPLEXER` so that it does not get compiled in when people are not using it?

Good idea, but i wouldn´t know how. At least in void set_i2c_multiplexer(I2CMultiplexer *multiplexer, uint8_t channel); it will be dependend.

2020-12-21 21:14 UTC, jesserockz reviewed
Please add yourself to CODEOWNERS in `esphome/components/tca9548a/__init__.py` and run `script/build_codeowners.py`

2021-01-07 20:36 UTC, badbadc0ffee commented on esphome/components/i2c/i2c.h
> +  void check_multiplexer();
Does this need to / make sense to be public?

2021-01-07 20:45 UTC, badbadc0ffee commented on esphome/components/tca9548a/tca9548a.h
> +  bool scan_;
This appears to be unused?

It looks like scanning the I2C bus will not work with this MUX in place.
The component and / or the base I2C component should issue a warnig when a configuration demands scanning of the I2C bus while a mux is also configured.

2021-01-07 20:54 UTC, badbadc0ffee commented on esphome/components/i2c/i2c.h
> +  void check_multiplexer();
Could this be made `const`?

2021-01-07 22:29 UTC, andreashergert1984 commented on esphome/components/i2c/i2c.h
> +  void check_multiplexer();
> Does this need to / make sense to be public?
set_i2c_multiplexer: this is called in the  register_i2c_device.. so from "outside".. 
check_multiplexer is not protected.

about const i´m not sure as it potentially modifies multiple multiplexers (as tested locally)

2021-01-07 22:30 UTC, andreashergert1984 commented on esphome/components/tca9548a/tca9548a.h
> +  bool scan_;
scanning (incl. all busses attached) can be activated in the configuration.
so it is easy to see on which channel which addresses are visible.. and for sure.. it switches channel and uses the scan-function of the bus.. so all devices currently "connected" are seen.

2021-01-07 22:50 UTC, andreashergert1984 commented on esphome/components/tca9548a/tca9548a.h
> +  bool scan_;
fixed: added the check for the scan_ ...

2021-01-08 20:32 UTC, andreashergert1984 commented
added to test1.yaml

2021-01-26 18:04 UTC, jesserockz commented on esphome/components/tca9548a/__init__.py
> +TCA9548AComponent = tca9548a_ns.class_('TCA9548AComponent', cg.PollingComponent, i2c.I2CDevice)
Shouldn't this be `I2CMultiplexer`?

```suggestion
TCA9548AComponent = tca9548a_ns.class_('TCA9548AComponent', cg.PollingComponent, i2c.I2CMultiplexer)
```

2021-01-27 07:30 UTC, jesserockz requested changes
A couple of minor changes. 

I just want to make sure we are not going to break I2C for everything once this goes stable.

2021-01-27 07:30 UTC, jesserockz commented on esphome/components/i2c/__init__.py
> +    cv.Required(CONF_ID): cv.use_id(I2CDevice),
We want this to specifically be a multiplexer id.

```suggestion
    cv.Required(CONF_ID): cv.use_id(I2CMultiplexer),
```

2021-01-27 07:30 UTC, jesserockz commented on esphome/components/i2c/i2c.cpp
> +  if (this->multiplexer_) {
To keep consistency with other code that checks for `nullptr`

```suggestion
  if (this->multiplexer_ != nullptr) {
```

2021-01-27 09:43 UTC, jesserockz commented on esphome/components/i2c/__init__.py
> +I2CMultiplexer = i2c_ns.class_('I2CMultiplexer')
I don't understand the amazing codegen enough to argue as to why the parent classes are always listed here as per the c++ code...

```suggestion
I2CMultiplexer = i2c_ns.class_('I2CMultiplexer', I2CDevice)
```

2021-01-27 10:01 UTC, jesserockz approved these changes
I think this looks good now, but I am going to wait for another approval before merging it in.

2021-01-27 16:46 UTC, glmnet requested changes
I agree with @jesserockz this should be less intrusive, when multiplexers are not used which is the norm.

There are a few options, 
* c++ inheritance, this is what I would have done first, easy to understand but adds inheritance overhead (vtable etc)
* static polymorphism might be used but adds much complexity, also if using a device both with a multiplexer and without then it might not be good idea
* this one is nice unless you don't need it, specifically adds 
  - a check on every call to read / write
  - a multiplexer and channel field on each i2c device
  
  the above doesn't seem much but there are already people hitting the memory limits of the esps

please look for `cg.add_define(` in the code and add `USE_I2C_MULTIPLEXER`

2021-01-27 16:46 UTC, glmnet commented on esphome/components/tca9548a/tca9548a.cpp
> +  return true;
why making this always return true

2021-01-27 16:46 UTC, glmnet commented on tests/test1.yaml
> +
may be also adding a device to use the multiplexer could catch unexpected issues

2021-01-27 16:46 UTC, glmnet commented on esphome/components/tca9548a/tca9548a.cpp
> +  this->write_byte(0x70, channelbyte);
wouldn't it make sense to keep track of the active channel and change only if necessary?

2021-01-27 16:46 UTC, glmnet commented on esphome/components/i2c/__init__.py
> +        cv.Optional(CONF_MULTIPLEXER): cv.Schema(I2CMULTIPLEXER_SCHEMA),
I2CMULTIPLEXER_SCHEMA is already a schema
```suggestion
        cv.Optional(CONF_MULTIPLEXER): I2CMULTIPLEXER_SCHEMA,
```

2021-01-27 16:46 UTC, glmnet commented on esphome/components/i2c/i2c.cpp
> +    ESP_LOGVV(TAG, "Multiplexer present setting channel to channel %d", this->channel_);
```suggestion
    ESP_LOGVV(TAG, "Multiplexer setting channel to %d", this->channel_);
```

2021-02-20 22:35 UTC, dougle03 commented
Any plans for this to be released anytime soon?

2021-02-22 09:10 UTC, andreashergert1984 commented
> Any plans for this to be released anytime soon?

as here is as requested some work to do .. to not effect non-multiplexer users as far as possible.. and a lack of time on my side.. it will need some further. time.. feel free to make those changes and make a PR. ;)

2021-02-22 09:38 UTC, dougle03 commented
> > Any plans for this to be released anytime soon?
> 
> as here is as requested some work to do .. to not effect non-multiplexer users as far as possible.. and a lack of time on my side.. it will need some further. time.. feel free to make those changes and make a PR. ;)

I really wish I had the skillset to do this, alas I wait in eternal hope that you find the time in the near future. best

2021-02-22 19:58 UTC, Casino commented
> 
> 
> > > Any plans for this to be released anytime soon?
> > 
> > 
> > as here is as requested some work to do .. to not effect non-multiplexer users as far as possible.. and a lack of time on my side.. it will need some further. time.. feel free to make those changes and make a PR. ;)
> 
> I really wish I had the skillset to do this, alas I wait in eternal hope that you find the time in the near future. best

Yes, I'm also looking forward to see this feature merged! Unfortunatelly, best I can do is to test the multiplexer locally. Until now it works quite fine with my esp8266. Thanks a lot for your work! Best whishes

2021-03-28 21:15 UTC, glmnet requested changes

2021-03-28 21:15 UTC, glmnet commented on esphome/components/i2c/i2c.h
> +  uint8_t channel_;
Wrap in #ifdef to save memory

2021-03-28 21:21 UTC, andreashergert1984 commented on esphome/components/tca9548a/tca9548a.cpp
> +  return true;
removed ;)

2021-03-28 21:24 UTC, andreashergert1984 commented on tests/test1.yaml
> +
check ... added a second one "after" the first.. like in my real-life application

2021-03-28 21:24 UTC, andreashergert1984 commented on esphome/components/tca9548a/tca9548a.cpp
> +  this->write_byte(0x70, channelbyte);
done

2021-03-28 22:36 UTC, glmnet commented on esphome/components/i2c/i2c.h
> +  uint8_t channel_;
You will need to `#include "esphome/core/defines.h"`

2021-03-29 09:46 UTC, andreashergert1984 commented on esphome/components/i2c/i2c.h
> +  uint8_t channel_;
done

2021-03-29 14:43 UTC, glmnet approved these changes

2021-03-29 19:50 UTC, merged