added slow mode and detach time to servo
OttoWinter/esphomeyaml pull request #1413
Opened 2020-12-09 12:29 UTC by andreashergert1984

## Description:
This pull add the functionality to tell servos a time after reaching there target to detach automaticly.
Additional a run_duration is added to slow the movement down.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#882

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-12-14 00:20 UTC, glmnet requested changes
Works on my curtain!!! Thanks

Please check my code comments

2020-12-14 00:20 UTC, glmnet commented on esphome/components/servo/servo.cpp
> +  this->save_level_(level);
this will cause a lot of saves to flash memory when using transitions, you usually want to save just the target value

2020-12-14 00:20 UTC, glmnet commented on esphome/components/servo/servo.h
> +  long long start_millis_ = 0;
please use `uint32_t` to store values returned by `millis()`

2020-12-19 15:21 UTC, andreashergert1984 commented on esphome/components/servo/servo.h
> +  uint8_t state_;  // current state of servo: 0:detached, 1:moving, 2:target reached
done

2020-12-19 15:21 UTC, andreashergert1984 commented on esphome/components/servo/servo.h
> +  void set_keep_on_time(uint32_t keep_on_time) { keep_on_time_ = keep_on_time; }
done

2020-12-19 15:21 UTC, andreashergert1984 commented on esphome/components/servo/servo.h
> +  void set_run_duration(uint32_t run_duration) { run_duration_ = run_duration; }
switched

2020-12-19 15:21 UTC, andreashergert1984 commented on esphome/components/servo/servo.cpp
> +    if (millis() > this->start_millis_ + this->keep_on_time_) {
untangled

2020-12-19 15:21 UTC, andreashergert1984 commented on esphome/components/servo/servo.cpp
> +  if (this->keep_on_time_ && this->start_millis_ && this->state_ == 0) {
also untangled

2020-12-19 15:22 UTC, andreashergert1984 commented on esphome/components/servo/servo.cpp
> +  this->save_level_(level);
fixed

2020-12-19 15:22 UTC, andreashergert1984 commented on esphome/components/servo/servo.h
> +  long long start_millis_ = 0;
done

2021-01-03 20:57 UTC, glmnet commented
Thank you

2021-01-03 20:57 UTC, merged