Safe Mode Brick Option
OttoWinter/esphomeyaml pull request #1420
Opened 2020-12-15 21:47 UTC by alexyao2015

## Description:
Adds safe mode brick option

**Related issue (if applicable):** fixes esphome/feature-requests#1039

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#890

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-12-16 00:14 UTC, glmnet commented
So this basically adds option to store the boot loop counter in permanent flash instead of rtc mem.

How does this differ from ESP32 normal behavior? At least it should be explained in docs if this affects esp8266 only.

What do you mean by brick? for me this term is not adequate as it is at least ambiguous of what software is running (if any is running at all)
Could you do some test and check if ESP32 stays in Safe Mode even after a power cycle after entering safe mode? I'd bet it does.

2020-12-16 00:32 UTC, alexyao2015 commented
Hmm good questions. 

As to the esp32, I'm not sure if/what will happen or if the default behavior on the esp32 is to store the counter on flash. I don't currently own one to test that. Would you be able to potentially try it?

By brick, I mean the device is effectively rendered useless until it has been OTA'd where the preference will be reset. Again, I'm not sure about esp32 or if the bootloop counter will reset with an OTA. I do know it resets on the esp8266 after an OTA. The device will go into a state where it is permanently locked in safe mode and will not proceed further in boot regardless of a power cycle.

2020-12-16 00:36 UTC, alexyao2015 commented
The other thing this changes is it prevents the preference from being cleaned after entering safe mode if the setting is enabled. This is where the brick comes into play. Since the preference isn't being cleared, it will always enter safe mode once it enters it the first time.

2020-12-16 00:59 UTC, alexyao2015 commented
It occurred to me that this will still have an effect on esp32 in that it will still "brick" the device.

2020-12-16 01:07 UTC, glmnet commented
I just read the code so far, to my understanding now this has no effect at all on ESP32. Will do some tests later

2020-12-16 01:09 UTC, alexyao2015 commented on esphome/components/ota/ota_component.cpp
> +    if (!store_bootloops_in_flash_and_brick) {
This line is the only effect it will have on an esp32. This is where brick comes from.

2020-12-16 02:08 UTC, napieraj commented
What is the purpose of bricking the device when we have a configurable safe mode OTA window? getting back into safe mode is trivial enough if you miss the first opportunity, no?

in keeping with the move in naming convention from `rtc` to `prefs`, `clean_rtc()` should also be renamed, as it stands there is ambiguity between `clean_rtc()` and the other functions which now use the prefs nomenclature

2020-12-16 02:14 UTC, alexyao2015 commented
Imagine this scenario. You write some lambda that when run, the whole esp freezes. This results in the ESP not bootlooping, but freezing, requiring a full power cycle to unfreeze. Due to a power cycle being required, the boot loop counter is lost. 

In the case of catching the safe mode, its extraordinarily hard to catch it if you're in the situation where the ESP does freeze. You may not know what boot loop counter you are currently on while you are manually power cycling it. Bricking it would ensure you would be able to access safe mode quickly without having to potentially cycle it hundreds of times and reduces frustration. Especially since it typically would never reach 10 cycles during normal operation. After the set time, the boot counter would be reset normally. 

And good catch, will rename that as well.

2020-12-16 02:35 UTC, glmnet commented
How can you freeze the esp? The watchdog should reset it and enter in safe mode by itself

2020-12-16 02:42 UTC, alexyao2015 commented
Hmm I'm not sure then. I'm almost sure I've had times when it did freeze. Either way, this provides a more sure-fire way to ensure you can get into safe mode.

2020-12-16 03:42 UTC, alexyao2015 commented
Even with watchdog, you would normally need to sit there and wait x amount of time for the esp to reset 10 times. And once you wait that time, you only have a 5 minute interval to OTA it before you would be forced to wait that all over again. This lets you let the device reset on its own and you can come back to OTA it. Or you can forcibly induce it through power cycles. Its unlikely for it to reach 10 unhandled boots on its own anyways. If it does, you likely should OTA it anyway.

2020-12-23 16:24 UTC, napieraj commented
> You may not know what boot loop counter you are currently on while you are manually power cycling it.

You do not have to "catch" it at exactly the number of failed `num_attempts`, all it takes is to cycle it 10-or-so times, it can be 15, it can be 20 (with a few seconds inbetween) and you can be reasonably certain it goes into safe mode. I see no need to semi-permanently brick the device and require and complete firmware reflash.

In short: the option to store failed boot loops in flash could be useful for some users, but bricking causes more harm than it brings benefit. Imagine the scenario in which a child is playing with the light switch controlling a smart bulb with the brick option enabled, or some kind of power fault/brownout that would cause the esp to temporarily bootloop and once again require a complete reflash to return to operation

2020-12-23 16:31 UTC, alexyao2015 commented
Then don't enable the feature for those devices? It's turned off by default and has a pretty detailed note explaining that it does brick the device in the docs as well as in the setting name.

And no you can't really be certain it's in safe mode. If say it's on bootloop 5 and you decide to power cycle it, you have no clue if it's on bootloop 5 or 1. So you're just sitting there praying and hoping you hit the magic number of powercycles. Hit the wrong number and you start over again. And you don't have a clue when you're starting over with the bootloop counter either.

2020-12-23 16:35 UTC, napieraj commented
That's the issue, you're cramming two features into a single parameter -- what if I do want to store failed boot loops in flash but not risk bricking my devices?

we already have the `esp8266_restore_from_flash` param, would it not be sensible to use this value to determine where to store failed boot loops as well, and potentially add the brick option as its own option if someone really wants that?

2020-12-23 16:37 UTC, alexyao2015 commented
If you do toggle `esp8266_restore_from_flash`, it will automatically save the bootloops to flash same if you have an esp32. That's how esphome works underneath it all.

2020-12-23 16:43 UTC, napieraj commented
This is not my understanding, the previous code calls `.make_preference` with the *in_flash* bool set to false, regardless of `esp8266_restore_from_flash` setting -- there is no check in the preference handler, see: https://esphome.io/api/preferences_8cpp_source.html#l00185

2020-12-23 16:48 UTC, alexyao2015 commented
Hmm I'll have to test that then. Pretty sure from my testing, it stored in flash anyways

2021-01-08 15:28 UTC, badbadc0ffee requested changes
Deliberately *bricking* a device does not make any sense.

At least the wording is very awkward and must be changed to something like *power_cycle_recovery* if that is what you are specifically aiming at. (That is also a common terminology as seen [here](https://tasmota.github.io/docs/Device-Recovery/#fast-power-cycle-device-recovery).)

Generally, I have the feeling that the *safe_mode*, which is already in place already does its job. I don't understand why another *bricked_mode* would be necessary or useful. I'd definitely *not* want to permanently lock the device in such a mode which could be reached by error as well: a timeout after which the system would try to return to normal mode would be indispensable - which leads us back to the existing *safe_mode*.

2021-01-08 18:28 UTC, alexyao2015 commented
[This](https://github.com/esphome/esphome/pull/1420#issuecomment-745717871) is a prime use case for the feature. Although a new suggestion is to force it into safe mode until it can cleanly exit after the default duration of 5 minutes. The Tasmota feature linked is effectively the same as it completely resets the entire device and forces a reconfiguration. In ESPHome, we don't have reconfiguration, but a device can be "reconfigured" through an OTA.

2021-01-09 07:09 UTC, alexyao2015 commented
Heres an update on some of the changes and reasons for a full-on permanent safe mode.

1) In order to preserve the flash, we must ultimately land the user permanently in safe mode. 
2) Enabling esp8266_restore_from_flash should only affect components that the user may adjust. Linking this to that setting would potentially allow a user to destroy their flash if it bootloops when that setting is on. Consider the device bootlooping for a day or more before a user realizes. The device would likely be toast by then.
3) I've now included full validation for all setting so an incompetent user cannot enter settings that will brick the device.
4) Alternating between safe mode/normal mode results in [too much code being changed for little benefit](https://github.com/alexyao2015/esphome/commit/28f27dfc752b79c05fe69b6d46bf624f27c0fec0). Ultimately, we still need to enter a permanent safe mode to preserve flash.
5) Should a user face issues with a child flicking a light switch, they may either choose to not enable this setting or simply enable the bootcounter to a number that would avoid this issue since OTA is now configurable. 
6) Since Tasmota has a feature similar to this as pointed out by @badbadc0ffee, it likely will not be a major impact.


Future Todos:

1) Perhaps make this the default behavior to enter safe mode unless deep sleep has been enabled. 
2) This should either be not allowed if deep sleep is enabled or a large warning should be placed in the documentation since it will write to flash on every wakeup. Not sure of which is better atm.
3) Rename feature to something else? Suggestions? IMO this resembles the definition of soft brick pretty well.

2021-01-10 13:51 UTC, badbadc0ffee commented
I still find the wording very inapropriate.

And I want to point out that the Tasmota feature differs sustantially: it tries to avoid the necessity for firmware updates for the normal user by all means. Tasmota tries to help end users. This aims at developers where I'd be comfortable to accept when someone needs to open a device to reflash it because he shot himself into his knee by putting a blocking loop into an on_boot trigfer or similar things.

I do totally agree that this must be very thoroughly tested to avoid introducing bugs in this critical system phase. What I don't see yet is the automated test suite that would reflect that. ;-)

2021-01-10 16:02 UTC, alexyao2015 commented
The issue is here that we don't have a config. We have safe mode which is pretty similar to wiping the config. In safe mode, we sit and wait for a new config to come through OTA. Ultimately, I see this as an important last resort to catch any code that may have otherwise fully bricked the device, causing the user to have to discard the device (in my case since it was tuya) or have to open it up and reflash it. I've had to throw away two otherwise perfectly fine devices simply because they were bootlooping without a real way to enter safe mode.

There may always be bugs that cause a bootloop or freeze but we need a safety net to catch anything that falls through. @glmnet mentioned placing a while loop in a lambda that would 1) Freeze the device without tripping watchdog 2) block OTA since the device is stuck in a while loop. Point being is there may be more cases like this that we may not be able to think of now but need a failsafe for it. In this case, it's a purposefully bricking while loop, next time, it's a user that forgot to place break inside the while loop, then it's a user that bricks it in a way we cant foresee today. The fact that we have lambdas makes it possible to brick the device in all kinds of ways we cant foresee. 

The wording can easily be changed, but support for the feature is important.

2021-01-10 16:08 UTC, alexyao2015 commented
> And I want to point out that the Tasmota feature differs sustantially: it tries to avoid the necessity for firmware updates for the normal user by all means. 

If you use ESPHome, it's expected that you know how to OTA because there is no other way you're changing the configuration. You cannot say you use ESPHome without knowing how to do an OTA. Setting up for someone else who doesn't know how to OTA? Either 1) disable the feature beforehand like in Tasmota or 2) teach them how to OTA/reconfig like they would have to in Tasmota if the config got reset.

What's the point of avoiding an OTA besides it being annoying? I find it on the same level of annoying (perhaps a little less annoying) as having to re-setup the wifi, templates, and settings in Tasmota. There is no difference.

2021-01-10 16:17 UTC, glmnet commented
There is one thing this attempt to fix:

Device doesn't reboot itself, it halts, this can be done with poor code, watchdog doesn't reset it and no services (OTA) is attended. 
Here we could reset the device with the reset button, this has two issues:
1. We don't know how many times we have to push the button to stay in safe mode, as if we overshot then it will start count again 
2. We might not have access to the reset button, we can full power cycle the device but now we need to store the count in flash, storing the count in flash is a problem as we don't want to wear it 

We can't fix 2 but we can't limit it, how? Just don't write too much:
Let's assume default setting of 10 loops to enter safe mode and 5 mins of safe mode time before auto reboot. 
Stuff goes wrong for any reason and device is rebooted, after 10 loops device enters safe mode. 
As soon as this happens the loop counter is reset to zero, this is ok if OTA goes thru or user is actively watching logs and testing something. Otherwise we can make sure the counter does not go to zero until
OTA is done or the 5 mins _during_ safe mode elapses complete. This fixes 1.

If OTA does not happen we still want to attempt a normal boot (this is legacy behavior), we can then reset boot count to zero, this will likely cause another 10 loops and a 5 minute in safe mode, and cycle forever. To minimize flash usage I propose 
a) just decrease boot loop 1, so 1 attempt to clan boot will be tried and then will enter in safe mode again, so two writes every 5 minutes, undetermined count but not many
b) keep increasing boot count, try to boot on odd counts and enter safe mode in even counts. This is same as a but once count reaches 20, after the restar time elapses do not reboot, just reset counter to zero. Flash wear will be preserved, at least until **user** power cycles or resets the device. Without user intervention flash is written 20 times, this can be default
c) disbale auto reboot by timeout if store in flash is enabled, I wouldn't like this as I'd like store in flash be default. 

We cannot store in flash we are going to safe mode permanently (soft brick)
a) that's a breaking change 
b) it's not smart (can be read as it's stupid)
c) when there is life there is hope

a not so common reason this can happen if an attached device to esp is in fault condition which would cause the esp to boot loop, replacing the device might get the thing operational again 

A faulty grid power issues / power supply/ a bad wire / a child playing with a switch etc. can power cycle the device many times with no reason being a fault in the device itself causing the device to self destroy (to the end users POV)

In any case storing in flash should default to false if we are using deep sleep as rebooting is normal device behavior.

2021-01-10 17:01 UTC, alexyao2015 commented
I agree that 2 is a pretty tricky issue that is hard to fix. 

The potential fix outlined with alternate booting between safe mode and normal mode is a potential solution. The issue I see with this is it's very complex and requires many changes. With each change, there is room for an increased amount of bugs, increased chance for user error, increased work to implement, and increased maintenance. The less code and complexity around safe mode results in lower chances for bugs and higher chances of a user recovering their device. I would take a forced OTA that lets me save my device over an uncaught bug that ultimately kills my device due to complex code anyday. Keep it Super Simple or KISS is important for safe mode where we cannot afford any bugs. (I started implementing the feature and realized how much code this really requires and caught many potential bugs along the way. Ex. I made a PR for OTA setting validation that fixes a potential permanent brick caused by changing a simple config option. Think about the bugs that may come with this as it's a substantially more involved feature)

Ultimately, the main benefit we get is simply we are not permanently booting into safe mode, but we risk bugs causing devices to hard brick permanently rather than soft brick. 

This solution, while breaking, is simplistic, requiring substantially less code. We could also make it not breaking by not enabling it by default, but it's typically meant to be an underlying feature that a user will never notice.

Downsides such as issues with the power supply, child, etc can be avoided through 1) increasing the boot count before permanently entering safe mode. 2) disabling this feature. In any case, here I would argue that if a user does have these problems where the device has such a poor power supply or a switch-crazy child that it constantly reboots 10 or 20 times consecutively without being stable for 1 minute between, they should disable this feature to avoid wearing the flash. Even with the proposed solution of alternating between bootloop, we still cannot protect a user from wearing the flash if they have issues like this and it's beyond our control. All we can do is simply suggest to disable the feature to avoid wearing the flash.

I understand that this solution may not be ideal, but I don't see a better way that it can be done while also staying simple.

2021-01-11 05:05 UTC, alexyao2015 commented
TLDR of ^
1) I don't feel comfortable making large amounts of changes and being 100% sure there are no bugs
2) The alternative still doesn't fix flash wear issues due to power supply, child, etc. while a brick does.

2021-01-11 07:41 UTC, badbadc0ffee commented
> 1. I don't feel comfortable making large amounts of changes and being 100% sure there are no bugs
But you *are* 100% sure that the changes you suggest are bug-free although there are no tests in place?

> 2. The alternative still doesn't fix flash wear issues due to power supply, child, etc. while a brick does.
I don't think that wear that is potentially occuring because of a malfunctioning power supply or a child flicking the switch - literally - every second for a full day are out of the scope of the firmware.

2021-01-11 13:33 UTC, alexyao2015 commented
Yes, I can be 100% sure there are no bugs because there is effectively a change of 2 lines here (storing in flash and changing bootloop reset). Compare that to the hundreds of lines that would need to be changed for such a feature to be implemented. If there were a bug in that, it's unlikely to be caught as well with or without tests.

2021-01-11 17:29 UTC, badbadc0ffee commented
I am looking forward to reviewing another PR with two changed liens of code then.

2021-01-11 19:15 UTC, badbadc0ffee requested changes

2021-01-11 19:15 UTC, badbadc0ffee commented on esphome/components/ota/__init__.py
> +        cv.Range(max=TimePeriod(milliseconds=4294967295)),
This does not belong here - as I already stated in the other PR - and is also incorrect.

2021-01-11 19:19 UTC, badbadc0ffee commented
I'll stop reading this PR now. You can notify me when you get it down to the two lines of code you prefigured before instead of bloating it with additional incorrect changes.

2021-01-11 19:25 UTC, alexyao2015 commented
Its not bloated? If you actually read the changes, you would see the bulk of it is a result of renaming rtc to prefs due to the change in usage. Thats literally the only reason it has extended lines...

2021-01-11 19:30 UTC, alexyao2015 commented
To sum things up:
1) I added 1 new config option. Validation is ported from another pr.
2) I pass that config option into a preexisting function
3) The config option configures the prefs such that its stored on flash or in rtc.
4) Added 1 if statement to check if the config option is on or off. 
5) Renamed all instances of rtc to prefs so that it makes sense given the new use case.

2021-01-11 19:41 UTC, glmnet commented on esphome/components/ota/__init__.py
> +    CONF_PORT, CONF_STORE_BOOTLOOPS_IN_FLASH_AND_BRICK, CONF_REBOOT_TIMEOUT,
I'll join @badbadc0ffee  and stop following this PR too until I stop reading BRICK, I'll merge the time fix now so you can rebase this

2021-01-11 19:43 UTC, alexyao2015 commented on esphome/components/ota/__init__.py
> +    CONF_PORT, CONF_STORE_BOOTLOOPS_IN_FLASH_AND_BRICK, CONF_REBOOT_TIMEOUT,
I can change the working of brick easily. My question to you is, if I do change said working to say `power_cycle_recovery`, will you accept the PR?

2021-01-11 20:24 UTC, glmnet commented on esphome/components/ota/__init__.py
> +    CONF_PORT, CONF_STORE_BOOTLOOPS_IN_FLASH_AND_BRICK, CONF_REBOOT_TIMEOUT,
Of course not, I said I will not follow the PR 
We can work it out until it's clean code, not likely buggy and of course will not brick the device permanently. Many of us already agreed on that behavior, If you are not ok with that I'm afraid this is not going to happen.

2021-01-11 20:39 UTC, alexyao2015 commented on esphome/components/ota/__init__.py
> +    CONF_PORT, CONF_STORE_BOOTLOOPS_IN_FLASH_AND_BRICK, CONF_REBOOT_TIMEOUT,
I'm really not sure what to make of this. If I recreate this to do what you mentioned, code complexity increases greatly, resulting in potential bugs due to untested areas. Of course, I will do my best to make it bug free and it will be reviewed and tested, but those tests only cover so many cases. 

Even with a small PR like #1393, there were still bugs that got through the cracks requiring #1457. That was a change of a total of 15 lines. Consider a PR to safe mode with hundreds of lines of change. A bug that slips through a PR that is 15 lines changed will almost definitely slip through one that is hundreds of lines of changes. Considering that this is safe mode, it doesn't make sense to essentially refactor the entire thing to implement such a feature given that we know that safe mode as it is now is tried and true. 

A bug in safe mode bricks the device and likely results in it going to a landfill. A bug in a component or any other non-core component bricks the device temporarily into safe mode where a user can OTA.  

The choice is either:
1) Have a disclaimer on this feature as there is now and default it to off so a user cannot unintentionally harm their device.
2) Implement a new way to handle safe mode and risk tons of bugs in the process and devices going to the landfill. 

I simply cannot understand why this is such a controversial feature given that it's an optional feature that is defaulted to off. Someone that turns it on will know exactly what they are doing because there is very clear documentation surrounding it. 

Maybe the suggestion you had is fit for a complete overhaul of OTA, changing how it currently functions today such that the new functionality is a default on. It's out of scope for the issue I'm trying to solve with this PR.

2021-01-11 20:57 UTC, alexyao2015 commented
I've updated the description of the PR to provide a summary of the comments.

2021-01-11 21:15 UTC, alexyao2015 commented
Another simple idea/thought to make this better and stay simple. Instead of permanently bricking the device, it:
1) is set to default enabled, but is default disabled for deep sleep
2) once entering safe mode, it permanently enters safe mode until it can cleanly exit safe mode (only couple lines to change to make this a reality)
 + also prevents fast power cycling from destroying the flash
3) no longer permanently in safe mode
4) resolves issues mentioned for creating this PR

2021-01-15 05:35 UTC, alexyao2015 commented
Last note here. Lots of other iot devices sold to normal consumers use a power cycle as a way of a complete factory reset. Personally, I have Yeelights which will fully reset after 5 power cycles. It's more or less equivalent to this... 

Those with kids or whoever thinks this would be an issue, shouldn't buy any normal hardware sold to the general public is the consensus here....

2021-01-15 14:56 UTC, badbadc0ffee commented
The very big difference is that others don't brick their devices but reset the configuration in a way that an end user can recover it without special tooling. That is in particular also the case for Tasmota where you can bring the device into a state where any smartphone can be used to connect to the device in this recovery state, put in the wifi credentials and other configuration parameters, restart and be ready to go again. That is the _opposite_ of bricking a device.

On the other hand, if you change the Tasmota code - to stick with that example that you have also cited by yourself - you can also easily shoot yourself into your knee there and put in or change code that _bricks_ the device if you break the recovery mode countermeasures that are put into place to save you.

As a general rule of thumb, I'd say that if you use a special tool such as a compiler in a way that leads to a '_bricked_' device, it is just fair that another special tool such as a screwdriver or even soldering iron is needed to recover. If you only use a general purpose tool such as a web browser on your phone (or even just the power switch) and accidentally change the configuration in a way that the device appears to be '_broken_', countermeasures such as a power-cycle-recovery procedures should be in place to be able to recover into a safe state and explicitly _avoid_ the '_brick_'.

As this PR is after all of this lengthy discussion still explicitly aiming at '_bricking_' the device even though that can - as we all agree - also happen accidentally just by regular user interaction such as a child flicking a switch a couple of times too often, it seems like it as no perspective to get merged into ESPHome.

If you feel better with such a development feature in place while working on a configuration for a device that cannot be easily be accessed to reflash when something goes wrong, it is of course a pretty neat idea to bring in some countermeasure to save you from _bricking_ your device. I can perfectly understand that. Go ahead, do that on your branch! That is good practice, I'd say.

But this does not belong into the production software. I'd suggest you close this PR now.

2021-01-15 15:46 UTC, alexyao2015 commented
@badbadc0ffee Did you read this new comment about the direction for this PR? I think this is a good compromise.
https://github.com/esphome/esphome/pull/1420#issuecomment-758229572

2021-01-16 17:47 UTC, badbadc0ffee commented
> @badbadc0ffee Did you read this new comment ...

I did.

2021-01-16 17:49 UTC, alexyao2015 commented
If you did in fact read it, you would realize your comments about bricking the device do not make sense and are irrelevant.

2021-01-24 14:24 UTC, badbadc0ffee requested changes
You are wasting my time. Nothing changed.

2021-01-24 16:19 UTC, alexyao2015 commented
Here's a potential pitfall to the alternating boots suggestion from @glmnet. Another user in the issues section found a situation where safe mode fails to start at all. Suppose that the boot loop counter was stored in flash like required for that feature, the device would boot loop into eternity and destroy the flash in the process, counting up and resetting with each boot.

This solution protects against that. I'm willing to discuss the alternative I suggested, but haven't received any feedback. The changes I made were to simply rebase this onto the dev version.

2021-03-21 18:25 UTC, OttoWinter commented
I don't have time to read through the entire comment history, but still trying to understand what this is for.

Could you answer this question:

1. What concrete problem does this solve? 

2. Has such a problem provenly ever happened in real environments? 

3. And How does this PR solve that?

2. Why is the config option include "brick"? As [Merriam webster's suggests](https://www.merriam-webster.com/dictionary/brick#:~:text=Definition%20of%20brick%20(Entry%202,hacking%2C%20or%20software%20changes)%20%E2%80%A6), bricking is the process of _permanently_ destroying a device (as in not recoverable even after a software fix). That is the opposite of what should happen.

It would interest me when the current logic would _not_ work. Especially the hardware watchdog prevents pretty much all issues.

2021-03-21 20:12 UTC, alexyao2015 commented
I don't think this really makes sense anymore, given some consideration and after #1393. 

The one major issues with safe mode currently is that it can still fail to start with too many entities in the YAML as in esphome/issues#1723, which I had thought this would fix but now realize that it doesn't. Even though the entities are not being added to `App`, it still fails to load.

2021-03-21 20:12 UTC, closed without merging