added st7920 display,
OttoWinter/esphomeyaml pull request #1440
Opened 2020-12-30 16:43 UTC by marsjan155

Added ST7920 LCD graphic display, tested on 128x64 model

## Description:

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#907

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-01-11 08:36 UTC, Misiu commented
@marsjan155 I have this display laying around so I can test this, but I need to know how to do that. I have Home Assistant running on Pi4 (standard setup).
@jesserockz can this be cherry-picked to 1.6 beta3? This way we'll be able to use it and test from Home Assistant.

2021-01-11 08:59 UTC, jesserockz commented
It cannot be cherry picked until merged into Dev.
You can test a branch on the ha add-on with this add-on config:
```
esphome_version: "marsjan155:st7920"
```

2021-01-11 09:36 UTC, Misiu commented
I'll set up dev env and will try to test this. Hopefully, this can be merged into dev and cherry-picked before 1.6 will be released.
I didn't know we can select a specific version of ESPHome like this. Thanks for the tip 🙂

2021-01-11 10:30 UTC, mdepa-cl commented
@Misiu It'll be great if someone else confirms it's working

2021-01-11 10:53 UTC, marsjan155 commented
@Misiu It'll be great if someone else confirms it's working

2021-06-01 11:30 UTC, jesserockz requested changes
Since this is an SPIDevice, why does it need a separate `RS` pin? The built in `cs_pin` does this job with `this->enable()` / `this->disable()` and if you need it to be high instead of low, you can invert the pin in yaml.

If this is the case, please remove the rs_pin from the code and the docs.

2021-06-02 23:32 UTC, marsjan155 commented
@jesserockz right but for st7920 will be always inverted, will not conflict with other SPI devices? Maybe can be inverted programmatically before each transmission?

2021-06-03 00:15 UTC, jesserockz commented
So the best place to invert is in the yaml, otherwise a user might invert it, then the code will invert it too.
Which means you just need to update the docs to inform users that the pin should be inverted in their config

2021-08-19 20:53 UTC, marsjan155 commented
@jesserockz
I found some free time and pushed changes as suggested. It works and please check it

2021-08-20 19:49 UTC, oxan reviewed
I've some suggestions for minor issues (you can commit them all at once from the "Files changed" tab), otherwise this looks good!

2021-08-20 19:49 UTC, oxan commented on esphome/components/st7920/st7920.cpp
> +  byte i, j, b;
`byte` is an Arduino-ism, we prefer standard C++.
```suggestion
  uint8_t i, j, b;
```

2021-08-20 19:49 UTC, oxan commented on esphome/components/st7920/st7920.cpp
> +void ST7920::fill(Color color) { memset(this->buffer_, 0, this->get_buffer_length_()); }
This ignores the `color` argument. I presume it should be something like this:
```suggestion
void ST7920::fill(Color color) { 
  memset(this->buffer_, color.is_on() ? 0xFF : 0x00, this->get_buffer_length_()); 
}
```

2021-08-20 19:49 UTC, oxan commented on esphome/components/st7920/st7920.cpp
> +  ESP_LOGD(TAG, "  Width: %d", this->width_);
```suggestion
  ESP_LOGCONFIG(TAG, "  Height: %d", this->height_);
  ESP_LOGCONFIG(TAG, "  Width: %d", this->width_);
```

2021-08-20 19:49 UTC, oxan commented on esphome/components/st7920/st7920.cpp
> +  this->fill(COLOR_OFF);
```suggestion
  this->clear();
```

2021-08-20 19:49 UTC, oxan commented on esphome/components/st7920/st7920.cpp
> +  if (this->writer_local_.has_value())  // insert Labda function if available
```suggestion
  if (this->writer_local_.has_value())  // call lambda function if available
```

2021-08-20 19:49 UTC, oxan commented on esphome/components/st7920/st7920.cpp
> +void ST7920::loop() {}
This is unnecessary, you can just leave the function out if you don't need it.
```suggestion
```

2021-08-20 19:49 UTC, oxan commented on esphome/components/st7920/st7920.cpp
> +    ESP_LOGW(TAG, "Posiotion out of area: %dx%d", x, y);
```suggestion
    ESP_LOGW(TAG, "Position out of area: %dx%d", x, y);
```

2021-08-20 19:49 UTC, oxan commented on esphome/components/st7920/st7920.cpp
> +  ESP_LOGCONFIG(TAG, "displayInit...");
```suggestion
  ESP_LOGD(TAG, "Initializing display...");
```

2021-08-20 19:49 UTC, oxan commented on esphome/components/st7920/st7920.h
> +const Color COLOR_ON(1, 1, 1, 1);
With my previous suggestion, these aren't used anymore:
```suggestion
```

2021-08-20 19:49 UTC, oxan commented on esphome/components/st7920/st7920.h
> +  void loop() override;
```suggestion
```

2021-08-20 20:01 UTC, marsjan155 commented
@oxan I'm learning cpp in my free time and learned something new from your review, thanks a lot
only need to pass checks :)

2021-08-20 20:04 UTC, oxan commented
> only need to pass checks :)

And check whether it works ;) (Though I'd be surprised if any of my suggestions broke it, but you never know).

2021-08-20 20:35 UTC, marsjan155 commented
yeah, small changes can be dangerous :) checked also on device - still works

2021-08-20 20:40 UTC, oxan approved these changes

2021-08-26 02:32 UTC, jesserockz approved these changes

2021-08-26 02:33 UTC, merged