Fix OTA Config Validation
OttoWinter/esphomeyaml pull request #1457
Opened 2021-01-10 06:10 UTC by alexyao2015

## Description:
Properly validates all OTA config options to prevent a user from bricking the device

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-01-10 12:58 UTC, badbadc0ffee commented on esphome/components/ota/__init__.py
> +    if config[CONF_REBOOT_TIMEOUT].total_milliseconds > 4294967295:
I'd rather change the ckeck below in the `CONFIG_SCHEMA` definition to

    cv.Optional(CONF_REBOOT_TIMEOUT, default='5min'): 
      cv.All(cv.positive_time_period_milliseconds, cv.Range(max=TimePeriod(milliseconds=4294967295))),

if that is necessary. On the other hand - if that check is indeet necessarty for timestamps, it dows not belong into this check but rather into the `positive_time_period` check defined in [config_validation.py](https://github.com/esphome/esphome/blob/dev/esphome/config_validation.py:515#L515).

2021-01-10 20:21 UTC, alexyao2015 commented on esphome/components/ota/__init__.py
> +    if config[CONF_REBOOT_TIMEOUT].total_milliseconds > 4294967295:
That doesn't seem to work... Doing that seems to make it no longer recognize ota as a component.

2021-01-11 17:45 UTC, badbadc0ffee commented on esphome/components/ota/__init__.py
> +    if config[CONF_REBOOT_TIMEOUT].total_milliseconds > 4294967295:
Works on my machine. ;-)
Have a look at https://github.com/esphome/esphome/pull/1461/checks.
Test 1 fails as by design - the timeout was deliberately a fraction of a second too long.
Test 2-4 pass as expected.

2021-01-11 17:47 UTC, alexyao2015 commented on esphome/components/ota/__init__.py
> +    if config[CONF_REBOOT_TIMEOUT].total_milliseconds > 4294967295:
No I mean esphome no longer functions. If you load up the dashboard in dev, it no longer recognizes ota as a component. Not talking about tests here.

2021-01-11 18:24 UTC, glmnet commented on esphome/components/ota/__init__.py
> +    if config[CONF_REBOOT_TIMEOUT].total_milliseconds > 4294967295:
Usually when ESPHome does not recognize a component is because you screw up something in the python, it will keep working partially

2021-01-11 18:25 UTC, alexyao2015 commented on esphome/components/ota/__init__.py
> +    if config[CONF_REBOOT_TIMEOUT].total_milliseconds > 4294967295:
I'm not sure what the case is, but I literally copied that code and pasted it in. It simply no longer recognized the ota component, so I can't make this fix.

2021-01-11 18:39 UTC, badbadc0ffee commented on esphome/components/ota/__init__.py
> +    if config[CONF_REBOOT_TIMEOUT].total_milliseconds > 4294967295:
That fix won't be necessary and should not be applied anyways: the check does not belong here but into `esphome/config_validation.py` instead.

Oh and - it works on my machine. Yes, I have tested it on a D1 mini just to be 100% sure.

2021-01-11 18:46 UTC, alexyao2015 commented on esphome/components/ota/__init__.py
> +    if config[CONF_REBOOT_TIMEOUT].total_milliseconds > 4294967295:
If it was applied there, you would need to rework the entirety of it to validate timestamps against all c++ variable types such that the number will not overflow... Thats not a task that I would be willing to take on atm. Its either this fix or risk a user overflowing the integer value and bricking their device. 

I don't know how else to explain that it doesn't work besides the fact that I literally copy-pasted that code in, and it simply did not work. The entire ota component failed validation after applying that.

2021-01-11 18:55 UTC, alexyao2015 commented on esphome/components/ota/__init__.py
> +    if config[CONF_REBOOT_TIMEOUT].total_milliseconds > 4294967295:
Finally saw it. Didn't import TimePeriod. Thanks for the suggestion!

2021-01-11 19:12 UTC, badbadc0ffee requested changes

2021-01-11 19:12 UTC, badbadc0ffee commented on esphome/components/ota/__init__.py
> +        cv.Range(max=TimePeriod(milliseconds=4294967295)),
This does not belong here. And it must be less then, not up to 4294967295 btw. because 4294967295 is used to encode the special value 'never'.

2021-01-11 19:21 UTC, alexyao2015 commented on esphome/components/ota/__init__.py
> +        cv.Range(max=TimePeriod(milliseconds=4294967295)),
As mentioned, I'm not going to refactor the entirety of config_validation.py, I simply do not have to time or energy to do such a thing. If you would like to refactor the entire thing so that timeperiods support c++ integers, please feel free to. In the meantime, I would just like this patched so an unknowing user does not brick their device.

2021-01-11 20:17 UTC, glmnet commented
I don't get it what is the issue tries to fix:
if num attempts or reboot timeout is given, it will be just ignored
if timeout is large value, thats actually never? in that case this is a feature, we shoud accept the keyword never here, so the device stays in ota forever without rebooting itself.

also, as there are default values for num attempts, and timeout, this PR actually makes impossible to set safe_mode to false as the validation would never pass.

2021-01-11 20:25 UTC, alexyao2015 commented
> if num attempts or reboot timeout is given, it will be just ignored

Ideally, I would want ESPHome to follow the strict validation that is mentioned in the contributing documentation. Silently ignoring the setting isn't very user friendly. It should be marked as invalid if that setting exists without safe mode.

> also, as there are default values for num attempts, and timeout, this PR actually makes impossible to set safe_mode to false as the validation would never pass.

Thanks for this catch! What would you suggest to fix it? Perhaps, I could remove the default value and add the default into the validation step if not set? Not sure what is the best method to overcome this issue.

2021-01-11 22:46 UTC, badbadc0ffee requested changes

2021-01-11 22:46 UTC, badbadc0ffee commented on esphome/components/ota/__init__.py
> +        cv.Range(max=TimePeriod(milliseconds=4294967294)),
This does not belong her.
As simple as that.

2021-01-18 20:59 UTC, alexyao2015 commented on esphome/components/ota/__init__.py
> +        cv.Range(max=TimePeriod(milliseconds=4294967294)),
This isn't helpful as mentioned in my previous comments.

2021-09-14 08:48 UTC, closed without merging