Nextion upload and sensors
OttoWinter/esphomeyaml pull request #1464
Opened 2021-01-12 00:01 UTC by SenexCrenshaw

## Description:
This is a large PR of multiple outstanding/stale PRs and feature requests.  Namely:
#912
#1110
#1079

[esphome/feature-requests#201](url)
[esphome/feature-requests#91](url)
[esphome/feature-requests#201](url)

This is "almost" a complete rewrite. Lots of additions and functionality have been added. The document PR will go over most of these. 

Notably:
- Sensors/binary sensors/switch/text sensors and touch have all been added.
- Over the air TFT file upload
- Polling has been added to all the components
- Display on_wake/on_sleep
- Many API helpers (get_string/get_int) have been added

This makes the Nextion extremely useful and very easy to program. My thermostat does not have anything in the display lambda. Everything is updated on the fly as sensors change. 

**Breaking Change** there is one. NextionTouchComponent functionality has been moved into NextionBinarySensor.  A recompile of a yaml will produce the proper code. However if someone for some reason is using NextionTouchComponent as a class then there will be trouble. Renaming to NextionBinarySensor is all that is needed. 

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-01-12 00:19 UTC, kbx81 commented
I just wanted to be the first to comment and say that I am quite excited about this. Testing it up to this point has proven that it works well, although I still need to play with it more. Hopefully some others will jump in to test, too! 😁🚀

2021-01-12 08:31 UTC, rspaargaren commented
I have been testing the Nextion code on the fly as the code was developing. As far as I am concerned we have been able to eliminate (most of) the bugs and it works very well.

2021-01-12 18:04 UTC, SenexCrenshaw commented
I added the doc PR:
esphome/esphome-docs#934

I know this is a lot of work for the devs to check and we all thank you!!!

2021-01-20 18:58 UTC, GeneralLuzi commented
Hi,
cannot wait until it is merged. When will it happen? How can we help?
Best regards!

2021-01-20 19:02 UTC, SenexCrenshaw commented
> Hi,
> cannot wait until it is merged. When will it happen? How can we help?
> Best regards!

Did you test out this PR? Thats a big help. This is a big one and the folks are looking at it and will need time.

2021-01-20 19:13 UTC, GeneralLuzi commented
Nope, but if it helps, I will give this PR a try asap

2021-01-20 19:32 UTC, SenexCrenshaw commented
> Nope, but if it helps, I will give this PR a try asap

the more folks who validate this PR the better!

2021-01-25 20:17 UTC, glmnet commented on esphome/components/nextion/text_sensor.py
> +CONFIG_SCHEMA = cv.All(
why cv.All(cv.Schema ???

2021-01-25 21:49 UTC, SenexCrenshaw commented on esphome/components/nextion/text_sensor.py
> +CONFIG_SCHEMA = cv.All(
because it worked! i am not a python guru and did my best.

2021-01-25 22:37 UTC, kbx81 commented on esphome/components/nextion/text_sensor.py
> +CONFIG_SCHEMA = cv.All(
I'm also not familiar with how the schema stuff works -- but I'd love to know/learn more. I read some of the voluptuous documentation at one point but I don't think I know enough about it all for the docs to really make sense. 🙃

2021-01-25 23:28 UTC, SenexCrenshaw commented on esphome/components/nextion/text_sensor.py
> +CONFIG_SCHEMA = cv.All(
In all seriousness I believe I need cv.All for has_at_least_one_key to work.

2021-02-18 04:37 UTC, kbx81 commented
It just keeps getting better and better...just wanted to put a public "thank you" up here -- lots going on here, lots of work...but it is sooooo worth it! 🍻

2021-02-26 15:46 UTC, hanerd commented
Started testing this out last night and was having issues with the update crashing the ESP 

wemos d1 mini
Rx D5
Tx D7

NX483K035_011

I saw you pushed some changes this morning, but still no go.

First call to upload gives me:
`[15:43:03][D][nextion_upload:228]: preparation for tft update failed 0 ""`

Second crashes the board.

```[15:43:24]--------------- CUT HERE FOR EXCEPTION DECODER ---------------
[15:43:24]
[15:43:24]Soft WDT reset
[15:43:24]
[15:43:24]>>>stack>>>
WARNING Found stack trace! Trying to decode it
[15:43:24]
[15:43:24]ctx: cont
[15:43:24]sp: 3ffffa80 end: 3fffffc0 offset: 01a0
[15:43:24]3ffffc20:  00003000 3ffe9eca 401009ea 2d4fdf3b  
INFO Need to fetch platformio IDE-data, please stand by
INFO Running:  platformio run -d /config/nextion -t idedata
WARNING Decoded 0x401009ea: millis
[15:43:27]3ffffc30:  00000000 3ffe9eca 3ffffdac 402255be  
WARNING Decoded 0x402255be: esphome::uart::UARTDevice::available()
[15:43:27]3ffffc40:  00000000 00000000 3ffffdac 4020704c  
WARNING Decoded 0x4020704c: esphome::nextion::Nextion::recv_ret_string_(String&, unsigned int, bool)
[15:43:27]3ffffc50:  40105af1 00dd840c 3ffffc80 3ffffc00  
WARNING Decoded 0x40105af1: ets_timer_arm_new
[15:43:27]3ffffc60:  00000000 0000b598 000007d0 00000001  
[15:43:27]3ffffc70:  3fff26d4 00000000 3ffffdac 40221748  
WARNING Decoded 0x40221748: String::copy(char const*, unsigned int)
[15:43:27]3ffffc80:  00003000 3ffffdac 3ffea7d2 00041760  
[15:43:27]3ffffc90:  00003000 3ffe9eca 3fff26bc 40209491  
WARNING Decoded 0x40209491: esphome::nextion::Nextion::upload_tft()
[15:43:27]3ffffca0:  00000000 00000000 3fff3a9c 3fff3a2c  
[15:43:27]3ffffcb0:  000b000f 00ffffff ff011fbb 3f001388  
[15:43:27]3ffffcc0:  3fff4264 0013001f 00ff1b20 70747468  
[15:43:27]3ffffcd0:  3fff1600 84000000 3fff43a4 0000002f  
[15:43:27]3ffffce0:  00000000 3fff3d4c 0011001f 001059ad  
[15:43:27]3ffffcf0:  00000000 3fff434c 80ff3f5c 3fff4240  
[15:43:27]3ffffd00:  00000001 00000000 ffffffff 3fff4301  
[15:43:27]3ffffd10:  00000001 3fff0003 3fff1500 40237b94  
WARNING Decoded 0x40237b94: etharp_output_LWIP2 at /local/users/gauchard/arduino/arduino_esp8266/esp8266-lwip/tools/sdk/lwip2/builder/lwip2-src/src/core/ipv4/etharp.c:885
[15:43:27]3ffffd20:  80000000 00000000 00000000 696d6877  
[15:43:27]3ffffd30:  6972772d 36322073 38323138 3531312c  
[15:43:27]3ffffd40:  2c303032 00000031 00000005 40101e54  
WARNING Decoded 0x40101e54: pp_post
[15:43:27]3ffffd50:  3ffeb3b5 40105107 3ffeee40 00000006  
WARNING Decoded 0x40105107: lmacRxDone
[15:43:27]3ffffd60:  401029eb 3ffeee40 3ffeee40 40235219  
WARNING Decoded 0x401029eb: rcReachRetryLimit
WARNING Decoded 0x40235219: tcp_create_segment at /local/users/gauchard/arduino/arduino_esp8266/esp8266-lwip/tools/sdk/lwip2/builder/lwip2-src/src/core/tcp_out.c:190
[15:43:27]3ffffd70:  00000003 02aa31ea 3ffef810 40102bcc  
WARNING Decoded 0x40102bcc: rcReachRetryLimit
[15:43:27]3ffffd80:  3ffebc48 00000000 00000000 402386ac  
WARNING Decoded 0x402386ac: ip4_output_if_opt at /local/users/gauchard/arduino/arduino_esp8266/esp8266-lwip/tools/sdk/lwip2/builder/lwip2-src/src/core/ipv4/ip4.c:1577
[15:43:27]3ffffd90:  00000003 02aa31ea 4010308e 00000100  
WARNING Decoded 0x4010308e: wDev_ProcessFiq
[15:43:27]3ffffda0:  3ffebc48 7fffffff 00002200 676e6100  
[15:43:27]3ffffdb0:  00000065 80000080 3fff18b4 0006001f  
[15:43:27]3ffffdc0:  00febc48 3ffe9ef8 0000a963 02aa31ea  
[15:43:27]3ffffdd0:  00000000 2c9f0300 3fff3a9c 00000001  
[15:43:27]3ffffde0:  40102db0 3fffc200 00000022 00000000  
WARNING Decoded 0x40102db0: wDev_ProcessFiq
[15:43:27]3ffffdf0:  00000000 3fff234c 3fff2ee4 4021040b  
WARNING Decoded 0x4021040b: std::_Function_handler<void (), setup::{lambda()#1}>::_M_invoke(std::_Any_data const&) at main.cpp
[15:43:27]3ffffe00:  40100901 02aa399a 0000000d 402103f0  
WARNING Decoded 0x40100901: ets_post
WARNING Decoded 0x402103f0: esphome::LambdaAction<>::play()
[15:43:27]3ffffe10:  0000000d 3fff3eaf 00000005 40225a48  
WARNING Decoded 0x40225a48: esphome::Action<>::play_complex()
[15:43:27]3ffffe20:  000012cc 3fffc6fc 00000000 40225a7c  
WARNING Decoded 0x40225a7c: esphome::api::UserServiceTrigger<>::execute()
[15:43:27]3ffffe30:  3fff3eaf 3ffffe90 00000005 40210e3e  
WARNING Decoded 0x40210e3e: esphome::api::UserServiceBase<>::execute_service(esphome::api::ExecuteServiceRequest const&)
[15:43:27]3ffffe40:  40100901 02aa399a 0000000d 00000000  
WARNING Decoded 0x40100901: ets_post
[15:43:27]3ffffe50:  3ffffe70 3fff3c00 00000001 00000003  
[15:43:27]3ffffe60:  3ffffe90 3fff22b0 3fff22b0 402247f1  
WARNING Decoded 0x402247f1: esphome::api::APIConnection::execute_service(esphome::api::ExecuteServiceRequest const&)
[15:43:27]3ffffe70:  00000005 3ffffe90 3fff3bf4 40224d06  
WARNING Decoded 0x40224d06: esphome::api::APIServerConnection::on_execute_service_request(esphome::api::ExecuteServiceRequest const&)
[15:43:27]3ffffe80:  00000005 40226d98 3fff3bf4 40205217  
WARNING Decoded 0x40226d98: precache
WARNING Decoded 0x40205217: esphome::api::APIServerConnectionBase::read_message(unsigned int, unsigned int, unsigned char*)
[15:43:27]3ffffe90:  40226d98 8f4cbd7c 00000000 00000000  
WARNING Decoded 0x40226d98: precache
[15:43:27]3ffffea0:  00000000 000034d1 3fff25dc 00000002  
[15:43:27]3ffffeb0:  00000008 00000005 3fff3bf4 40201ccf  
WARNING Decoded 0x40201ccf: esphome::api::APIConnection::parse_recv_buffer_()
[15:43:27]3ffffec0:  00000001 00000000 0000002a 00000000  
[15:43:27]3ffffed0:  00000001 00000000 00000005 00000000  
[15:43:27]3ffffee0:  00000001 4bc6a7f0 0000b10e 4020b868  
WARNING Decoded 0x4020b868: esphome::wifi::WiFiComponent::is_connected()
[15:43:27]3ffffef0:  00000000 3fff3a48 3fff3bf4 3fff25dc  
[15:43:27]3fffff00:  3fff3a48 3fff3a48 3fff3bf4 40201d70  
WARNING Decoded 0x40201d70: esphome::api::APIConnection::loop()
[15:43:27]3fffff10:  00000000 00000000 4bc6a7f0 00000000  
[15:43:27]3fffff20:  3fff3a60 00000002 3fff25dc 4020571e  
WARNING Decoded 0x4020571e: esphome::api::APIServer::loop()
[15:43:27]3fffff30:  3fff3a64 00000002 3fff0cf8 40225810  
WARNING Decoded 0x40225810: esphome::Component::call_loop()
[15:43:27]3fffff40:  3fff3a64 00000002 3fff0cf8 402258a5  
WARNING Decoded 0x402258a5: esphome::Component::call()
[15:43:27]3fffff50:  3fffdad0 00000002 3fff0cf8 4020dd23  
WARNING Decoded 0x4020dd23: esphome::Application::loop()
[15:43:27]3fffff60:  007a1200 dc55de38 feefef00 feefeffe  
[15:43:27]3fffff70:  3fff3a68 feefeffe 3fff234c feefeffe  
[15:43:27]3fffff80:  00000000 00000000 00000001 3fff1078  
[15:43:27]3fffff90:  3fffdad0 00000000 3fff1038 402104b4  
WARNING Decoded 0x402104b4: loop
[15:43:27]3fffffa0:  3fffdad0 00000000 3fff1038 40222b2c  
WARNING Decoded 0x40222b2c: loop_wrapper() at core_esp8266_main.cpp
[15:43:27]3fffffb0:  feefeffe feefeffe 3ffe8520 40100861  
WARNING Decoded 0x40100861: cont_wrapper
[15:43:27]<<<stack<<<
[15:43:27]
[15:43:27]--------------- CUT HERE FOR EXCEPTION DECODER ---------------```

2021-02-26 16:23 UTC, SenexCrenshaw commented
I think there is an issue with esp 8266. I wont be able to debug until this
weekend. Soft WDT reset is the watch dog kicking in.

Thanks for testing!

On Fri, Feb 26, 2021 at 10:46 AM hanerd <notifications@github.com> wrote:

> Started testing this out last night and was having issues with the update
> crashing the ESP
>
> wemos d1 mini
> Rx D5
> Tx D7
>
> NX483K035_011
>
> I saw you pushed some changes this morning, but still no go.
>
> First call to upload gives me:
> [15:43:03][D][nextion_upload:228]: preparation for tft update failed 0 ""
>
> Second crashes the board.
>
> [15:43:24]
> [15:43:24]Soft WDT reset
> [15:43:24]
> [15:43:24]>>>stack>>>
> WARNING Found stack trace! Trying to decode it
> [15:43:24]
> [15:43:24]ctx: cont
> [15:43:24]sp: 3ffffa80 end: 3fffffc0 offset: 01a0
> [15:43:24]3ffffc20:  00003000 3ffe9eca 401009ea 2d4fdf3b
> INFO Need to fetch platformio IDE-data, please stand by
> INFO Running:  platformio run -d /config/nextion -t idedata
> WARNING Decoded 0x401009ea: millis
> [15:43:27]3ffffc30:  00000000 3ffe9eca 3ffffdac 402255be
> WARNING Decoded 0x402255be: esphome::uart::UARTDevice::available()
> [15:43:27]3ffffc40:  00000000 00000000 3ffffdac 4020704c
> WARNING Decoded 0x4020704c: esphome::nextion::Nextion::recv_ret_string_(String&, unsigned int, bool)
> [15:43:27]3ffffc50:  40105af1 00dd840c 3ffffc80 3ffffc00
> WARNING Decoded 0x40105af1: ets_timer_arm_new
> [15:43:27]3ffffc60:  00000000 0000b598 000007d0 00000001
> [15:43:27]3ffffc70:  3fff26d4 00000000 3ffffdac 40221748
> WARNING Decoded 0x40221748: String::copy(char const*, unsigned int)
> [15:43:27]3ffffc80:  00003000 3ffffdac 3ffea7d2 00041760
> [15:43:27]3ffffc90:  00003000 3ffe9eca 3fff26bc 40209491
> WARNING Decoded 0x40209491: esphome::nextion::Nextion::upload_tft()
> [15:43:27]3ffffca0:  00000000 00000000 3fff3a9c 3fff3a2c
> [15:43:27]3ffffcb0:  000b000f 00ffffff ff011fbb 3f001388
> [15:43:27]3ffffcc0:  3fff4264 0013001f 00ff1b20 70747468
> [15:43:27]3ffffcd0:  3fff1600 84000000 3fff43a4 0000002f
> [15:43:27]3ffffce0:  00000000 3fff3d4c 0011001f 001059ad
> [15:43:27]3ffffcf0:  00000000 3fff434c 80ff3f5c 3fff4240
> [15:43:27]3ffffd00:  00000001 00000000 ffffffff 3fff4301
> [15:43:27]3ffffd10:  00000001 3fff0003 3fff1500 40237b94
> WARNING Decoded 0x40237b94: etharp_output_LWIP2 at /local/users/gauchard/arduino/arduino_esp8266/esp8266-lwip/tools/sdk/lwip2/builder/lwip2-src/src/core/ipv4/etharp.c:885
> [15:43:27]3ffffd20:  80000000 00000000 00000000 696d6877
> [15:43:27]3ffffd30:  6972772d 36322073 38323138 3531312c
> [15:43:27]3ffffd40:  2c303032 00000031 00000005 40101e54
> WARNING Decoded 0x40101e54: pp_post
> [15:43:27]3ffffd50:  3ffeb3b5 40105107 3ffeee40 00000006
> WARNING Decoded 0x40105107: lmacRxDone
> [15:43:27]3ffffd60:  401029eb 3ffeee40 3ffeee40 40235219
> WARNING Decoded 0x401029eb: rcReachRetryLimit
> WARNING Decoded 0x40235219: tcp_create_segment at /local/users/gauchard/arduino/arduino_esp8266/esp8266-lwip/tools/sdk/lwip2/builder/lwip2-src/src/core/tcp_out.c:190
> [15:43:27]3ffffd70:  00000003 02aa31ea 3ffef810 40102bcc
> WARNING Decoded 0x40102bcc: rcReachRetryLimit
> [15:43:27]3ffffd80:  3ffebc48 00000000 00000000 402386ac
> WARNING Decoded 0x402386ac: ip4_output_if_opt at /local/users/gauchard/arduino/arduino_esp8266/esp8266-lwip/tools/sdk/lwip2/builder/lwip2-src/src/core/ipv4/ip4.c:1577
> [15:43:27]3ffffd90:  00000003 02aa31ea 4010308e 00000100
> WARNING Decoded 0x4010308e: wDev_ProcessFiq
> [15:43:27]3ffffda0:  3ffebc48 7fffffff 00002200 676e6100
> [15:43:27]3ffffdb0:  00000065 80000080 3fff18b4 0006001f
> [15:43:27]3ffffdc0:  00febc48 3ffe9ef8 0000a963 02aa31ea
> [15:43:27]3ffffdd0:  00000000 2c9f0300 3fff3a9c 00000001
> [15:43:27]3ffffde0:  40102db0 3fffc200 00000022 00000000
> WARNING Decoded 0x40102db0: wDev_ProcessFiq
> [15:43:27]3ffffdf0:  00000000 3fff234c 3fff2ee4 4021040b
> WARNING Decoded 0x4021040b: std::_Function_handler<void (), setup::{lambda()#1}>::_M_invoke(std::_Any_data const&) at main.cpp
> [15:43:27]3ffffe00:  40100901 02aa399a 0000000d 402103f0
> WARNING Decoded 0x40100901: ets_post
> WARNING Decoded 0x402103f0: esphome::LambdaAction<>::play()
> [15:43:27]3ffffe10:  0000000d 3fff3eaf 00000005 40225a48
> WARNING Decoded 0x40225a48: esphome::Action<>::play_complex()
> [15:43:27]3ffffe20:  000012cc 3fffc6fc 00000000 40225a7c
> WARNING Decoded 0x40225a7c: esphome::api::UserServiceTrigger<>::execute()
> [15:43:27]3ffffe30:  3fff3eaf 3ffffe90 00000005 40210e3e
> WARNING Decoded 0x40210e3e: esphome::api::UserServiceBase<>::execute_service(esphome::api::ExecuteServiceRequest const&)
> [15:43:27]3ffffe40:  40100901 02aa399a 0000000d 00000000
> WARNING Decoded 0x40100901: ets_post
> [15:43:27]3ffffe50:  3ffffe70 3fff3c00 00000001 00000003
> [15:43:27]3ffffe60:  3ffffe90 3fff22b0 3fff22b0 402247f1
> WARNING Decoded 0x402247f1: esphome::api::APIConnection::execute_service(esphome::api::ExecuteServiceRequest const&)
> [15:43:27]3ffffe70:  00000005 3ffffe90 3fff3bf4 40224d06
> WARNING Decoded 0x40224d06: esphome::api::APIServerConnection::on_execute_service_request(esphome::api::ExecuteServiceRequest const&)
> [15:43:27]3ffffe80:  00000005 40226d98 3fff3bf4 40205217
> WARNING Decoded 0x40226d98: precache
> WARNING Decoded 0x40205217: esphome::api::APIServerConnectionBase::read_message(unsigned int, unsigned int, unsigned char*)
> [15:43:27]3ffffe90:  40226d98 8f4cbd7c 00000000 00000000
> WARNING Decoded 0x40226d98: precache
> [15:43:27]3ffffea0:  00000000 000034d1 3fff25dc 00000002
> [15:43:27]3ffffeb0:  00000008 00000005 3fff3bf4 40201ccf
> WARNING Decoded 0x40201ccf: esphome::api::APIConnection::parse_recv_buffer_()
> [15:43:27]3ffffec0:  00000001 00000000 0000002a 00000000
> [15:43:27]3ffffed0:  00000001 00000000 00000005 00000000
> [15:43:27]3ffffee0:  00000001 4bc6a7f0 0000b10e 4020b868
> WARNING Decoded 0x4020b868: esphome::wifi::WiFiComponent::is_connected()
> [15:43:27]3ffffef0:  00000000 3fff3a48 3fff3bf4 3fff25dc
> [15:43:27]3fffff00:  3fff3a48 3fff3a48 3fff3bf4 40201d70
> WARNING Decoded 0x40201d70: esphome::api::APIConnection::loop()
> [15:43:27]3fffff10:  00000000 00000000 4bc6a7f0 00000000
> [15:43:27]3fffff20:  3fff3a60 00000002 3fff25dc 4020571e
> WARNING Decoded 0x4020571e: esphome::api::APIServer::loop()
> [15:43:27]3fffff30:  3fff3a64 00000002 3fff0cf8 40225810
> WARNING Decoded 0x40225810: esphome::Component::call_loop()
> [15:43:27]3fffff40:  3fff3a64 00000002 3fff0cf8 402258a5
> WARNING Decoded 0x402258a5: esphome::Component::call()
> [15:43:27]3fffff50:  3fffdad0 00000002 3fff0cf8 4020dd23
> WARNING Decoded 0x4020dd23: esphome::Application::loop()
> [15:43:27]3fffff60:  007a1200 dc55de38 feefef00 feefeffe
> [15:43:27]3fffff70:  3fff3a68 feefeffe 3fff234c feefeffe
> [15:43:27]3fffff80:  00000000 00000000 00000001 3fff1078
> [15:43:27]3fffff90:  3fffdad0 00000000 3fff1038 402104b4
> WARNING Decoded 0x402104b4: loop
> [15:43:27]3fffffa0:  3fffdad0 00000000 3fff1038 40222b2c
> WARNING Decoded 0x40222b2c: loop_wrapper() at core_esp8266_main.cpp
> [15:43:27]3fffffb0:  feefeffe feefeffe 3ffe8520 40100861
> WARNING Decoded 0x40100861: cont_wrapper
> [15:43:27]<<<stack<<<
> [15:43:27]
> [15:43:27]--------------- CUT HERE FOR EXCEPTION DECODER ---------------```
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/1464#issuecomment-786726705>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIPTPLNZ5C3IPSLM6MBPUOLTA667BANCNFSM4V6MMYGA>
> .
>

2021-02-27 00:24 UTC, hanerd commented
@kbx81 figured out that on the esp8266 (d1 mini) specifying the `bauds=115200` in program.cs fixes a bunch of issues I was having with this branch not working at all (nextion would never actually get succesfully setup)

I can confirm that the tft update works from your changeset this morning with the baud rate being specified.

2021-02-27 11:57 UTC, SenexCrenshaw commented
Oh yes. Thats in the latest docs for this PR. Sorry I didnt realize you
were at that point. I lurk around our discord channel and if you need more
help you can ping me there or PM me.

On Fri, Feb 26, 2021 at 7:24 PM hanerd <notifications@github.com> wrote:

> @kbx81 <https://github.com/kbx81> figured out that on the esp8266 (d1
> mini) specifying the bauds=115200 in program.cs fixes a bunch of issues I
> was having with this branch not working at all (nextion would never
> actually get succesfully setup)
>
> I can confirm that the tft update works from your changeset this morning
> with the baud rate being specified.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/1464#issuecomment-786963886>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIPTPLO3Z4ORZMOHPTJUQC3TBA3ULANCNFSM4V6MMYGA>
> .
>

2021-03-07 09:47 UTC, tomjmul commented
TFT Upload doesnt work for me at all. I'm getting `[nextion_upload:212]: preparation for tft update failed 0 ""` on a Wemos D1 Mini

Adding a little debbugging, I see that the bytes I receive after the `whmi-wris` command are `00 00 FF FF FF 88 FF FF FF 05`. If I do hold off uploading until the 0x05, Then I get a `Check Error`

2021-03-07 13:41 UTC, SenexCrenshaw commented
Thanks for the

> TFT Upload doesnt work for me at all. I'm getting `[nextion_upload:212]: preparation for tft update failed 0 ""` on a Wemos D1 Mini
> 
> Adding a little debbugging, I see that the bytes I receive after the `whmi-wris` command are `00 00 FF FF FF 88 FF FF FF 05`. If I do hold off uploading until the 0x05, Then I get a `Check Error`

Thanks for the report. What model nextion? What is the filesize of the tft file? I will look into this during this coming week.

2021-03-07 16:51 UTC, tomjmul commented
> Thanks for the report. What model nextion? What is the filesize of the tft file? I will look into this during this coming week.

Thanks for looking into it when you get a chance. The tft is 236748 bytes and The Nextion model is NX3224TO24_011R

2021-03-12 00:10 UTC, SenexCrenshaw commented
> TFT Upload doesnt work for me at all. I'm getting `[nextion_upload:212]: preparation for tft update failed 0 ""` on a Wemos D1 Mini
> 

Please give the latest code a try. Warning on a 8266 (D1 Mini) you have to use the hardware UART or things just wont work right. Use RX/TX pins and if you need serial logging use UART1 (D4) for that.

2021-03-21 00:21 UTC, ielbury commented
Hey @SenexCrenshaw, I am having a problem compiling the latest bits and am not sure if it's my problem or a problem with the latest commit. Is it a problem for you or is this a merge issue for me?

The script:
```
esphome:
  name: nextion_test
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "MySSID"
  password: "MyPassword"

logger:

api:

ota:

switch:
  platform: gpio
  id: reset_display
  pin: D6
  restore_mode: ALWAYS_ON

uart:
  id: uart1
  rx_pin: D7
  tx_pin: D4
  baud_rate: 115200

display:
  - platform: nextion
    id: nextion1
    uart_id: uart1
```

And the errors:
```
INFO Reading configuration /config/esphome/nextion_test.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/nextion_test
Processing nextion_test (board: d1_mini; framework: arduino; platform: espressif8266@2.6.2)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20704.0 (2.7.4) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Library Manager: Installing Update
Library Manager: Already installed, built-in library
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266HTTPClient> 1.2
|   |-- <ESP8266WiFi> 1.0
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/components/nextion/nextion.cpp.o
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/components/nextion/nextion_commands.cpp.o
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/components/switch/switch.cpp.o
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/components/text_sensor/text_sensor.cpp.o
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/components/uart/uart.cpp.o
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/components/uart/uart_esp32.cpp.o
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/components/uart/uart_esp8266.cpp.o
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/components/wifi/wifi_component.cpp.o
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/components/wifi/wifi_component_esp32.cpp.o
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/core/application.cpp.o
src/esphome/components/nextion/nextion_commands.cpp: In member function 'virtual void esphome::nextion::Nextion::set_component_background_color(const char*, esphome::Color)':
src/esphome/components/nextion/nextion_commands.cpp:44:45: error: 'display' has not been declared
                                             display::ColorUtil::color_to_565(color));
                                             ^
src/esphome/components/nextion/nextion_commands.cpp: In member function 'virtual void esphome::nextion::Nextion::set_component_pressed_background_color(const char*, esphome::Color)':
src/esphome/components/nextion/nextion_commands.cpp:54:45: error: 'display' has not been declared
                                             display::ColorUtil::color_to_565(color));
                                             ^
src/esphome/components/nextion/nextion_commands.cpp: In member function 'virtual void esphome::nextion::Nextion::set_component_font_color(const char*, esphome::Color)':
src/esphome/components/nextion/nextion_commands.cpp:64:45: error: 'display' has not been declared
                                             display::ColorUtil::color_to_565(color));
                                             ^
src/esphome/components/nextion/nextion_commands.cpp: In member function 'virtual void esphome::nextion::Nextion::set_component_pressed_font_color(const char*, esphome::Color)':
src/esphome/components/nextion/nextion_commands.cpp:74:45: error: 'display' has not been declared
                                             display::ColorUtil::color_to_565(color));
                                             ^
src/esphome/components/nextion/nextion_commands.cpp: In member function 'void esphome::nextion::Nextion::fill_area(int, int, int, int, esphome::Color)':
src/esphome/components/nextion/nextion_commands.cpp:146:45: error: 'display' has not been declared
                                             display::ColorUtil::color_to_565(color));
                                             ^
src/esphome/components/nextion/nextion_commands.cpp: In member function 'void esphome::nextion::Nextion::line(int, int, int, int, esphome::Color)':
src/esphome/components/nextion/nextion_commands.cpp:153:45: error: 'display' has not been declared
                                             display::ColorUtil::color_to_565(color));
                                             ^
src/esphome/components/nextion/nextion_commands.cpp: In member function 'void esphome::nextion::Nextion::rectangle(int, int, int, int, esphome::Color)':
src/esphome/components/nextion/nextion_commands.cpp:160:45: error: 'display' has not been declared
                                             display::ColorUtil::color_to_565(color));
                                             ^
src/esphome/components/nextion/nextion_commands.cpp: In member function 'void esphome::nextion::Nextion::circle(int, int, int, esphome::Color)':
src/esphome/components/nextion/nextion_commands.cpp:167:45: error: 'display' has not been declared
                                             display::ColorUtil::color_to_565(color));
                                             ^
src/esphome/components/nextion/nextion_commands.cpp: In member function 'void esphome::nextion::Nextion::filled_circle(int, int, int, esphome::Color)':
src/esphome/components/nextion/nextion_commands.cpp:174:45: error: 'display' has not been declared
                                             display::ColorUtil::color_to_565(color));
                                             ^
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/core/component.cpp.o
src/esphome/components/nextion/nextion.cpp:1039:6: error: redefinition of 'void esphome::nextion::Nextion::set_writer(const nextion_writer_t&)'
 void Nextion::set_writer(const nextion_writer_t &writer) { this->writer_ = writer; }
      ^
src/esphome/components/nextion/nextion.cpp:1035:6: error: 'void esphome::nextion::Nextion::set_writer(const nextion_writer_t&)' previously defined here
 void Nextion::set_writer(const nextion_writer_t &writer) { this->writer_ = writer; }
      ^
src/esphome/components/nextion/nextion.cpp:1041:6: error: redefinition of 'void esphome::nextion::Nextion::set_wait_for_ack(bool)'
 void Nextion::set_wait_for_ack(bool wait_for_ack) { ESP_LOGW(TAG, "This command is depreciated"); }
      ^
src/esphome/components/nextion/nextion.cpp:1037:6: error: 'void esphome::nextion::Nextion::set_wait_for_ack(bool)' previously defined here
 void Nextion::set_wait_for_ack(bool wait_for_ack) { ESP_LOGW(TAG, "This command is depreciated"); }
      ^
Compiling /data/nextion_test/.pioenvs/nextion_test/src/esphome/core/controller.cpp.o
*** [/data/nextion_test/.pioenvs/nextion_test/src/esphome/components/nextion/nextion_commands.cpp.o] Error 1
*** [/data/nextion_test/.pioenvs/nextion_test/src/esphome/components/nextion/nextion.cpp.o] Error 1
========================== [FAILED] Took 1.96 seconds ==========================
```

2021-03-21 00:25 UTC, ielbury commented
Is it possible to add a font attribute to the various sensors so that we don't have to write lambda's to set the font?

For example:

```
text_sensor:
- platform: nextion
  nextion_id: nextion1
  name: text0
  id: text0
  update_interval: 4s
  component_name: text0
  font: 4
```

2021-03-21 00:26 UTC, ssieb commented
You should be setting the font in the designer.  The lambda is only for an option to change the font at runtime.

2021-03-21 00:29 UTC, ielbury commented
> You should be setting the font in the designer. The lambda is only for an option to change the font at runtime.

I am trying to replicate the HASPlateOne functionality and, yes I could do this in the designer but I would like to use a "common" template and just switch fonts. I realize you guys don't like "sugar" but IMHO this is a value add and I can guarantee you someone else is going to ask for this.

2021-03-21 00:36 UTC, ssieb commented
Those compile problems must be something you've done.  How did you get the code?
I disagree with adding that option, it's something that you should be doing in the designer.  And I can't find any reference to "HASPlateOne", what is that?

2021-03-21 00:39 UTC, ielbury commented
> "HASPlateOne", what is that?

My bad ...

https://github.com/HASwitchPlate/HASPone

That's fine, I will code it in lambda's.

2021-03-21 00:40 UTC, ielbury commented
> Those compile problems must be something you've done. How did you get the code?

I merged them from @SenexCrenshaw's branch into my own. That's ok, I will sort it out myself.

Thanks!

2021-03-21 01:08 UTC, ielbury commented
> I disagree with adding that option, it's something that you should be doing in the designer.

Sorry, but I disagree!

To be clear, I want ONE Nextion image flashed on all my plates and then I want to be able to tailor each plate with different entities displayed on each page. 

Your worldview is correct but so is mine.

2021-03-21 01:13 UTC, ssieb commented
So you're making a generic layout that is the same on all devices and then defining the content and style in the yaml?

2021-03-21 01:20 UTC, ielbury commented
> So you're making a generic layout that is the same on all devices and then defining the content and style in the yaml?

Yes and all the bits are there to declaratively define what is rendered (Visibility, Color's etc) except Font.

2021-03-21 01:52 UTC, ielbury commented
OTA uploads of the Nextion display image is not something you want to do frequently as it's easy to brick the display if the update fails either due to a network failure or power issue. If the display bricks, you have no recourse but to take display out of the wall and use SDCard to reflash.

My thinking is to have a "template" Nextion image that is the same across all the "plates" and the yaml does the customization and can be updated anytime with little risk,

There are some issues with HASPlateOne:

- It does not support static IP's.
- I would like to use a TOF sensor like the Vl53XX to detect someone standing in front of the "plate".
- It's a monolithic piece of code that has so many yields, delays and wdt trips that it's never going to be reliable.
- The user of Blueprints makes the automations unwieldy after more than 2 "plates".
- There is no way to define a menu structure that can be shared between "plates". I think using packages to define each page, each "plate" can it's pages defined once and shared. For example, I could define a "common/weather.yaml" that would be included into multiple "plates". When I change weather,yaml, all the plates would be updated.

2021-03-21 08:52 UTC, ssieb requested changes

2021-03-21 19:20 UTC, SenexCrenshaw commented on esphome/components/nextion/base_component.py
> +                "character and numbers. The character '{}' cannot be used"
Fixed

2021-03-21 19:22 UTC, SenexCrenshaw commented on esphome/components/nextion/base_component.py
> +    raise cv.Invalid("Must be less than 29 characters")
Fixed

2021-03-21 19:24 UTC, SenexCrenshaw commented on esphome/components/nextion/binary_sensor/nextion_binarysensor.cpp
> +void NextionBinarySensor::process_bool(std::string variable_name, bool on) {
I agree. Fixed

2021-03-21 19:42 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +          NextionComponentBase *nextion_queue = this->nextion_queue_.front();
agreed

2021-03-21 19:50 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
>        case 0x66:  // sendme page id
Done

2021-03-21 19:54 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.h
> +  void add_sleep_state_callback(std::function<void(bool)> &&callback);
Ah. good point. removed

2021-03-21 20:06 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +        // if the length is < 4 than its a negative.
It copies the number data in the previous block and if < 4 is received that means its a negative and fill in with 255 where needed.
There wont be bytes left over on the next command. I send commands delimited by the delimiter.

2021-03-21 20:07 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +void Nextion::send_command_no_ack(const char *command) {
Not sure why?

2021-03-21 20:18 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +          for (auto &i : this->nextion_queue_) {
> OTA uploads of the Nextion display image is not something you want to do frequently as it's easy to brick the display if the update fails either due to a network failure or power issue. If the display bricks, you have no recourse but to take display out of the wall and use a SDCard to reflash.
> 
> My thinking is to have a "template" Nextion image that is the same across all the "plates" and the yaml does the customization and can be updated anytime with little risk,
> 
> There are some issues with HASPlateOne:
> 
> * It does not support static IP's.
> * I would like to use a TOF sensor like the Vl53XX to detect someone standing in front of the "plate".
> * It's a monolithic piece of code that has so many yields, delays and wdt trips that it's never going to be reliable.
> * The use of Blueprints makes the automations unwieldy after more than 2 "plates".
> * There is no way to define a menu structure that can be shared between "plates". I think using packages to define each page, each "plate" can it's pages defined once and shared. For example, I could define a "common/weather.yaml" that would be included into multiple "plates". When I change weather,yaml, all the plates would be updated.

Not sure what HASPlateOne is but I will add the font in. Also my OTA code is tight. 100% follows the nextion protocol/api. I havne bricked it at all with the new code. but yes, if things go wrong you have to reload with the sd card.

Wouldnt it be great if it defaulted on an error to reading from the sd (if inserted) or opens up the serial line waiting for a TFT file!

2021-03-21 20:28 UTC, SenexCrenshaw commented
Not sure what HASPlateOne is but I will add the font in. Also my OTA code is tight. 100% follows the nextion protocol/api. I havet bricked it at all with the new code. but yes, if things go wrong you have to reload with the sd card.

Wouldnt it be great if it defaulted on an error to reading from the sd (if inserted) or opens up the serial line waiting for a TFT file!

2021-03-21 20:29 UTC, SenexCrenshaw commented
> Is it possible to add a font attribute to the various sensors so that we don't have to write lambda's to set the font?
> 
> For example:
> 
> ```
> text_sensor:
> - platform: nextion
>   nextion_id: nextion1
>   name: text0
>   id: text0
>   update_interval: 4s
>   component_name: text0
>   font: 4
> ```

its there the setting is:
``font_id:``

2021-03-22 14:20 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +        // if the length is < 4 than its a negative.
Fixed. I grab any 0xFF from the top of the buffer. Works nicely!

2021-03-22 17:08 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +          for (auto &i : this->nextion_queue_) {
Not for the addt command. The nextion needs to prep before it tells it to send the data so the Q might not exactly be in sync. I have tested this a bit..

2021-03-23 13:52 UTC, pashdown commented
Does this handle pic and picc properly?

2021-03-23 15:08 UTC, SenexCrenshaw commented
That is not in this current PR but i can add it

On Tue, Mar 23, 2021 at 9:52 AM pashdown ***@***.***> wrote:

> Does this handle pic and picc properly?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/1464#issuecomment-804920421>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIPTPLOTGFPIGNEXJRO7XV3TFCMK3ANCNFSM4V6MMYGA>
> .
>

2021-03-23 20:32 UTC, pashdown commented
> That is not in this current PR but i can add it

I'd be most grateful. Thank you.

2021-03-23 20:52 UTC, rarroyo6 commented
I am very interested in testing this, but I have never installed from a PR.
How do I install this into ESPHome in order to test it?
Is there a time frame on when this will be merged into the ESPHome?
I'm new at doing this, so any help is appreciated.

Thank you.

2021-03-24 15:23 UTC, SenexCrenshaw commented
Its being reviewed now and might be better to wait. Hopefully it will make
its way into dev soon.

On Tue, Mar 23, 2021 at 4:53 PM rarroyo6 ***@***.***> wrote:

> I am very interested in testing this, but I have never installed from a PR.
> How do I install this into ESPHome in order to test it?
> Is there a time frame on when this will be merged into the ESPHome?
> I'm new at doing this, so any help is appreciated.
>
> Thank you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/1464#issuecomment-805246872>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIPTPLKBLMS4VA655WYM7EDTFD5THANCNFSM4V6MMYGA>
> .
>

2021-03-24 15:41 UTC, SenexCrenshaw commented
> > That is not in this current PR but i can add it
> 
> I'd be most grateful. Thank you.

``void Nextion::set_component_pic(const char *component, uint8_t pic_id)``
and
``void Nextion::set_component_picc(const char *component, uint8_t pic_id) ``
have been added. I dont check if the command is being sent to a valid component but it will complain in the logs.

2021-03-24 22:48 UTC, rarroyo6 commented
I am still interested in using this. I'm getting ready to convert my old thermostat (D1 mini with Nextion display, using the Venstar protocol to communicate with HA) into ESPHome, since it now supports Climate, which it didn't have back then.
I would like to start using this, so I don't have to re-write it twice.
Once it gets merged, I can do an OTA update, with the new changes.
Right now to do any changes, I have to pull it off the wall, and plug it in on my bench to upload the software.
If the merge will happen soon, I'll wait. Otherwise I would like to start implementing it.
I don't mind dealing with a few bugs, if it's anything that I can't work around, then I can always install back the old software in the mean time.
Thanks,

2021-03-25 12:24 UTC, SenexCrenshaw commented
> I am still interested in using this. I'm getting ready to convert my old thermostat (D1 mini with Nextion display, using the Venstar protocol to communicate with HA) into ESPHome, since it now supports Climate, which it didn't have back then.
> I would like to start using this, so I don't have to re-write it twice.
> Once it gets merged, I can do an OTA update, with the new changes.
> Right now to do any changes, I have to pull it off the wall, and plug it in on my bench to upload the software.
> If the merge will happen soon, I'll wait. Otherwise I would like to start implementing it.
> I don't mind dealing with a few bugs, if it's anything that I can't work around, then I can always install back the old software in the mean time.
> Thanks,

I am not sure how you are running esphome to give advice. You could drop into the discord channel # general-support and im sure someone can help.

2021-03-28 00:28 UTC, ssieb commented on esphome/components/nextion/base_component.py
> +                "character and numbers. The character '{}' cannot be used"
Did this change get lost?  It's still the same in the current version.

2021-03-29 16:14 UTC, rarroyo6 commented
I just need to know which files to copy where, to make this available in ESPHome, so I can start trying it.
I can deal with any bugs, since my project is not going on-line right away. I will have some time to develop it and test it.

Thanks,

2021-04-01 03:17 UTC, rarroyo6 commented
Thanks, I'll give it a try.

2021-04-02 15:48 UTC, SenexCrenshaw commented
Rebase off of latest dev

2021-04-06 11:25 UTC, OttoWinter commented on esphome/components/nextion/nextion_base.h
> +#define ESP_LOGN(tag, ...) esph_log_vv(tag, __VA_ARGS__)
```suggestion
#define ESP_LOGN(tag, ...) ESP_LOGVV(tag, __VA_ARGS__)
```

I believe that should work (maybe with small modifications). Anyway, integrations shouldn't use `esph_log_*` functions directly as we only want to expose the `ESP_LOG*` macros.

2021-04-06 11:27 UTC, OttoWinter commented on esphome/components/nextion/nextion_base.h
> +#define ESP_LOGN(tag, ...) esph_log_d(tag, __VA_ARGS__)
Macros are global (and main.cpp will load this header), please instead use something like `NEXTION_LOG(xyz)` here to not pollute the global macro names.

2021-04-06 11:27 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion_base.h
> +#define ESP_LOGN(tag, ...) esph_log_vv(tag, __VA_ARGS__)
I dont mind removing it. I kept it in to help with debugging the protocol and queue handling. Nice to see you!

@ssieb and I have been working on this. I believe he has a review he is working on.

2021-04-06 11:28 UTC, OttoWinter commented on esphome/components/nextion/nextion_base.h
> +  virtual void add_no_result_to_queue_with_set(std::string variable_name, std::string variable_name_to_send,
```suggestion
  virtual void add_no_result_to_queue_with_set(const std::string &variable_name, const std::string &variable_name_to_send,
```

nit: with the current code, the string buffer will be copied on each invocation. With const references, only the reference is passed and no copying takes places (applies to other methods here too)

2021-04-06 11:31 UTC, OttoWinter commented on esphome/components/nextion/nextion_component_base.h
> +static const char *NextionQueueTypeStrings[] = {"SENSOR",      "BINARY_SENSOR",   "SWITCH",
Declaring static variables in header files has caused some problems before (haven't looked into why, but if the header is included in a lot of places the global var will be in the firmware multiple times). Please move this to a cpp file (translation unit).

2021-04-06 11:32 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion_base.h
> +  virtual void add_no_result_to_queue_with_set(std::string variable_name, std::string variable_name_to_send,
For some reason I thought C++ would always pass by reference on the backend since this is not a simple type. I can update these

2021-04-06 11:34 UTC, OttoWinter commented on esphome/components/nextion/nextion_upload.cpp
> +int Nextion::upload_by_chunks_(HTTPClient *http, int range_start) {
I'm not a fan of this. We really shouldn't use http client directly in this class, as that breaks modularity. Would it be possible to use the http client module built into esphome? Or does that lack some feature?

2021-04-06 11:36 UTC, OttoWinter commented on esphome/components/nextion/nextion.cpp
> +  ESP_LOGCONFIG(TAG, "  Baud Rate:        %d", this->parent_->get_baud_rate());
Why do we need to print this here? The uart bus already prints this in its own dump_config method.

2021-04-06 11:49 UTC, OttoWinter reviewed
Hi, thanks for this work! I don't know nextion well, so I can only comment on the code/modularity parts.

I've left you some comments about the code. One thing I'm not so happy about is that this component is getting enormous - it's ok for now but maybe in the future some of the communication could be offloaded to an external library (with overridable hal, so that we can use our own UART abstractions)? 

Also, while the nextion_upload feature is nice, I don't really like that it interacts directly with the HttpClient - we've had plenty of issues with the network stack, and all official integrations should go through our own interfaces for networking. Maybe we can keep the upload feature of this PR for now/move it to an external integration (see also #1630)

(In the future, please try to keep PRs to a managable size. This PR is way too big to review well. For example in the future you could split up into refactoring into the new BaseComponent, then add functionality in steps.)

2021-04-06 12:20 UTC, SenexCrenshaw commented
> Hi, thanks for this work! I don't know nextion well, so I can only comment on the code/modularity parts.
> 
> I've left you some comments about the code. One thing I'm not so happy about is that this component is getting enormous - it's ok for now but maybe in the future some of the communication could be offloaded to an external library (with overridable hal, so that we can use our own UART abstractions)?
> 
> Also, while the nextion_upload feature is nice, I don't really like that it interacts directly with the HttpClient - we've had plenty of issues with the network stack, and all official integrations should go through our own interfaces for networking. Maybe we can keep the upload feature of this PR for now/move it to an external integration (see also #1630)
> 
> (In the future, please try to keep PRs to a managable size. This PR is way too big to review well. For example in the future you could split up into refactoring into the new BaseComponent, then add functionality in steps.)

this started as just the OTA upload piece and then just blew up with all the features/bugs that were out there. 

Were you talking about the ``http_request`` component? Where are those network interfaces. I ended up using HttpClient since whatever happens with the OTA the MCU reboots which will clear out any issues (if at all). 
I thought about splitting out the communication piece and what not but this PR is old and I just kept plugging away. I outpaced any review/guidance (months now) for sure.

My have another display PR that is large as well. I am not a professional developer and glmnet was kind enough to mention PRs of PRs which if I do another PR here I will certainly use.

Thanks for all the help!

2021-04-06 12:27 UTC, rspaargaren commented
@OttoWinter This PR has been tested by some key user and during testing the whish list grew. Unfortunately the review speed of this PR was not very fast so @SenexCrenshaw kept developping the interaction with the Nextion until perfect. I really hope this PR gets approved as it is now as I and many other users are waiting for it for a long time! And the OTA has to stay as this is the key feature and it works like a charm.

2021-04-06 12:29 UTC, SenexCrenshaw commented
I dont mind splitting things out. @ssieb still is reviewing and once that's done I can clean things up and see where everything is.

2021-04-06 12:41 UTC, OttoWinter commented
Sure yeah I understand @rspaargaren - also with the late PR reviews that of course made things harder. It's ok for this PR :), splitting it up now would just lead to much more work. I'm just mentioning it for the future, as otherwise it gets almost impossible to review the code accurately.

-----

About the nextion upload feature: Yes sorry I mean the http_request component. Ok so if the device reboots afterwards it's probably ok :)

2021-04-06 14:26 UTC, SenexCrenshaw commented
> Sure yeah I understand @rspaargaren - also with the late PR reviews that of course made things harder. It's ok for this PR :), splitting it up now would just lead to much more work. I'm just mentioning it for the future, as otherwise it gets almost impossible to review the code accurately.
> 
> About the nextion upload feature: Yes sorry I mean the http_request component. Ok so if the device reboots afterwards it's probably ok :)

I will look into it. I started to use it but for some reason moved away. Thanks!

2021-04-07 06:10 UTC, ssieb requested changes

2021-04-07 06:10 UTC, ssieb commented on esphome/components/nextion/nextion_component.h
> +#endif
I might have missed it, but I didn't see any api usages.  What is this for?

2021-04-07 10:16 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +  this->goto_page("0");
I left that in from the pervious PR so there wont be any un-expected behaviors. Ill remove it though since this should be set in the tft file.

2021-04-07 10:20 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +    delay(250);  // NOLINT
I cleaned it up

2021-04-07 10:29 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion_upload.cpp
> +#endif
it complains during the lint with lines like the below but compiles and runs fine. I found multiple articles online about this and this work around.

``Error while processing /esphome/esphome/components/nextion/nextion_upload.cpp.
/esphome/esphome/components/nextion/nextion_upload.cpp:34:9: error: no member named 'setFollowRedirects' in 'HTTPClient' [clang-diagnostic-error]
  http->setFollowRedirects(HTTPC_STRICT_FOLLOW_REDIRECTS);``

2021-04-07 10:32 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion_upload.cpp
> +    }
good catch

2021-04-07 11:17 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +          }
I fixed up the logic. ``reset_`` was something I was considering on doing if the queue seemed out of order. I removed those calls for now but can always re-add if it is needed for stability/error recovery.

2021-04-07 11:24 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +    return;
I cleaned up this logic and add in some warnings if the user tries setting with a queue type that doesnt make sense

2021-04-07 11:36 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +    if (binarysensortype->get_variable_name().rfind(page, 0) == 0)
cleaned up
``.find(prefix, 0) != std::string::npos)``

2021-04-07 11:37 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +  this->add_no_result_to_queue_(variable_name);
I moved the empty check to the first if

2021-04-07 11:43 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +void Nextion::set_nextion_sensor_state(int queue_type, std::string name, float state) {
This and ``set_nextion_text_state`` are helper functions. This is how I used it:
```
api:
  services:
    - service: set_nextion_sensor
      variables:
        nextion_type: int
        name: string
        state: float
      then:
        - lambda: |-
            id(n1).set_nextion_sensor_state(nextion_type,name,state);
    - service: set_nextion_text
      variables:
        name: string
        state: string
      then:
        - lambda: |-
            id(n1).set_nextion_text_state(name,state);
```
I call this API from HASS to set states from code. Comes in handy for folks who want to manually set states from automations/code.

2021-04-07 11:48 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.h
> +  void set_auto_wake_on_touch_internal(bool auto_wake_on_touch) { this->auto_wake_on_touch_ = auto_wake_on_touch; }
moved to protected.

These are called from the python code generator if the user sets them. The non internal functions will try to communicate with the Nextion and I need to make sure the Nextion is setup before any commands are sent.

2021-04-07 12:02 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.h
> +  char flash_size_[64];
converted to ``std::string``

2021-04-07 12:26 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +uint16_t Nextion::recv_ret_string_(std::string &response, uint32_t timeout, bool recv_flag) {
I need the delay for the OTA upload functions. I changed the main code to not use the delay but to track when the loop is called. 
``this->recv_ret_string_(response, 0, false);``

2021-04-07 14:05 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion_component_base.h
> +static const char *NextionQueueTypeStrings[] = {"SENSOR",      "BINARY_SENSOR",   "SWITCH",
Even with ``#pragma once`` ?

2021-04-07 18:41 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +        }
it could! I updated the code.

2021-04-07 18:52 UTC, ssieb commented on esphome/components/nextion/nextion_upload.cpp
> +#endif
ok, then please add a comment about that

2021-04-07 18:57 UTC, ssieb commented on esphome/components/nextion/nextion_component_base.h
> +static const char *NextionQueueTypeStrings[] = {"SENSOR",      "BINARY_SENSOR",   "SWITCH",
If it's not needed in the header, it should go in the cpp file anyway.

2021-04-07 19:09 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +          }
With deque ``this->nextion_queue_.pop_front()`` does erase the first item.
``nextion_queue`` is a vector of pointers to components and only the no_result types need to be removed. they are allocated dynamically as needed. the other types are real components we cant delete. There is no memory leak as long as no_results are deleted.

2021-05-13 20:58 UTC, Andoramb commented
Fingers crossed :crossed_fingers:

2021-05-19 08:28 UTC, ssieb commented
I haven't had time to get back to reviewing this yet.

2021-06-19 15:14 UTC, rspaargaren commented
@SenexCrenshaw Keep up the good work. Really hope this now gets pushed into dev as we have been waiting very long for this excellent improvement!

2021-06-24 03:27 UTC, jesserockz requested changes

2021-06-24 03:27 UTC, jesserockz commented on esphome/components/nextion/base_component.py
> +@coroutine
This is not needed

2021-06-24 03:27 UTC, jesserockz commented on esphome/components/nextion/nextion.cpp
> +  this->dump_ran_ = true;
`dump_config` is supposed to run for each new log connection. This would run it after the first successful `check_connect` and then it would not run anymore Which could easily be missed if doing an OTA install and viewing logs OTA too

2021-06-24 03:27 UTC, jesserockz commented on esphome/components/nextion/sensor/__init__.py
> +        )
Please move this to an actual validation, otherwise this is just a crash.

2021-07-08 19:46 UTC, mihaiblaga89 commented
@SenexCrenshaw any updates on the requested changes? I would do them myself if I knew what I was doing 😄

2021-07-10 13:57 UTC, SenexCrenshaw commented on esphome/components/nextion/nextion.cpp
> +  this->dump_ran_ = true;
Just remove
```
if (!this->get_is_connected_() || this->dump_ran_)
    return;
  this->dump_ran_ = true;
  ```
 ?

2021-07-10 14:31 UTC, SenexCrenshaw commented on esphome/components/nextion/sensor/__init__.py
> +        )
Can you give an example on how to check for ``CONF_COMPONENT_ID`` from a validator? I am limited on time and not very proficient in voluptuous. 
I have this so far:
```
def wave_id_(value):
    value = cv.int_(value)
    if value < 0 or value > 3:
        raise cv.Invalid("Valid range for {CONF_WAVE_CHANNEL_ID} is 0-3")
    return value


def wave_id_check():
    return wave_id_
 ```

2021-07-10 16:20 UTC, glmnet commented on esphome/components/nextion/sensor/__init__.py
> +        )
Check line 257 of components wifi __init__.py for example

Sorry I'm mobile.

2021-07-10 19:42 UTC, jesserockz commented on esphome/components/nextion/nextion.cpp
> +  this->dump_ran_ = true;
Pretty much

2021-07-10 20:40 UTC, SenexCrenshaw commented on esphome/components/nextion/sensor/__init__.py
> +        )
Perfect! I forgot how much I like working with you all :)

2021-07-15 00:50 UTC, jesserockz approved these changes

2021-07-15 00:51 UTC, merged

2021-07-24 21:14 UTC, OptimusGREEN commented
This merge seems to have broke my esphome nextion. I've been trying to find out what broke it and so far I've narrowed it down to 1.20.0b2, b1 works ok and when this merge is introduced I can no longer access my esp. A downgrade fixes it.

I'm getting no errors on compile and once uploaded I dont get any logs in the console. I see loads was changed in this so I have no idea how to narrow it down.

I have an issue raised [here](https://github.com/esphome/issues/issues/2254).

Any help would be greatly appreciated as I'm desperate for the ota tft feature.