Add preset, custom_preset and custom_fan_mode support to climate
OttoWinter/esphomeyaml pull request #1471
Opened 2021-01-13 07:14 UTC by Lumpusz

## Description:
The climate schema on the HA side has changed. This PR is to incorporate those changes into esphome and to add support for presets, custom_presets and custom_fan_modes to climate. There is also CLIMATE_HEAT_COOL mode which was missing from esphome. Thi PR is part of a bundle, as aioesphome as well as HA esphome component needs an update.
Other related PRs:
- https://github.com/esphome/aioesphomeapi/pull/24
- HA esphome is still WIP, I will update this once it is ready.

Please note, that there was initial climate preset support with the away bool flag. I left it there for now, to be more backward compatible, but once the preset support is merged in component owners could migrate to it, and get rid of using the away flag, so it could be removed entirely.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-03-19 18:26 UTC, dudanov requested changes
Be more attentive to objects. You don't use references or pointers at all. Read code comments. This is C++. ;)
Review your code again and optimize.

2021-03-19 18:26 UTC, dudanov commented on esphome/components/midea_ac/midea_frame.cpp
> +void PropertiesFrame::set_custom_fan_mode(std::string mode) {
Prefer passing objects by reference (without copy), and where the object does not change, use constant references.

2021-03-19 18:26 UTC, dudanov commented on esphome/components/climate/climate_traits.cpp
> +void ClimateTraits::set_supported_custom_fan_modes(std::vector<std::string> supported_custom_fan_modes) {
Be more attentive to objects. You don't use references at all. Here, in general, the object is copied twice. Pass a constant reference to the object, the assignment will call the copy constructor once, not two. Then, I haven't looked at the code above yet. If the source object is not destroyed, but is in memory, then use pointers, why copy it once more. Review your code again and optimize.

2021-03-20 08:48 UTC, Lumpusz commented on esphome/components/midea_ac/climate.py
> +    cg.add(var.set_custom_fan_modes(config[CONF_CUSTOM_FAN_MODES]))
It is, thanks

2021-03-20 09:08 UTC, Lumpusz commented on esphome/components/climate/climate_traits.cpp
> +void ClimateTraits::set_supported_custom_fan_modes(std::vector<std::string> supported_custom_fan_modes) {
I come from Java, with little to no C++ knowledge. I can read the code, but I am not familiar with these differences.

2021-03-20 19:45 UTC, OttoWinter commented on esphome/components/api/api.proto
> +  CLIMATE_MODE_HEAT_COOL = 6;
I see you changed the `AUTO` enum value in HA to map to `AUTO`. That would be a semi-breaking change (I assume the HA frontend displays it differently).

To avoid a breaking change, could we do the following:

- rename `CLIMATE_MODE_AUTO` enum value to `CLIMATE_MODE_HEAT_COOL` in esphome codebase, but leave int value 1.
- map the `CLIMATE_MODE_AUTO` enum value here to int value 6

with protobuf, only the int value is transported over the wire, so old esphome clients would be unaffected, and thus this wouldn't be a breaking change

2021-03-22 06:17 UTC, Lumpusz commented on esphome/components/api/api.proto
> +  CLIMATE_MODE_HEAT_COOL = 6;
I see why you would want to do that, but on the HA side it is the other way around: See here: https://github.com/esphome/aioesphomeapi/pull/24/files#diff-14008b45e808f05655e27655b1487f3255d688a74f39dd511fd5ef77d611589dR672
So if we do what you suggest, we will map `HEAT_COOL` to `AUTO` and vice-versa, which is very confusing. Do you really want to do that?

2021-03-22 09:47 UTC, OttoWinter commented on esphome/components/api/api.proto
> +  CLIMATE_MODE_HEAT_COOL = 6;
Ok my previous message was not that clear. No I don't want that confusing naming.

What I suggested could be summarized as: do a project-wide Find&Replace of all old occurences of `CLIMATE_MODE_AUTO` and replace it with `CLIMATE_MODE_HEAT_COOL` (including all components, ha/aioesphomeapi codebases). But do not change the associated enum values.

Then, all esphome integrations use the same name as HA for referring to climate modes, and all old clients connected to HA still show up as "heat cool" in the frontend. This is because the protobuf wire format stays the same (value 0 refers to heat/cool in the frontend), only the old esphome integrations are updated to use the new naming.

2021-03-22 12:53 UTC, Lumpusz commented on esphome/components/api/api.proto
> +  CLIMATE_MODE_HEAT_COOL = 6;
> What I suggested could be summarized as: do a project-wide Find&Replace of all old occurences of CLIMATE_MODE_AUTO and replace it with CLIMATE_MODE_HEAT_COOL (including all components, ha/aioesphomeapi codebases). But do not change the associated enum values.

These enums are part of the proto file only, in other places they are referred to by different names.

> (value 0 refers to heat/cool in the frontend)

0 is `NONE`

I am sorry, but you completely lost me on this.  I have been trying to wrap my head around what you said for at least an hour, and I still don't see how it would help. Probably my understanding of this is not as deep as yours. 

If we put `HEAT_COOL` as 1, and `AUTO` as 6 in both proto files, wouldn't that solve the issue?

2021-03-23 08:25 UTC, Lumpusz commented on esphome/components/api/api.proto
> +  CLIMATE_MODE_HEAT_COOL = 6;
I think I got it now, you want `HEAT_COOL` to stay on enum value 1, so until only HA is upgraded they are unaffected. I pushed the commits for these. Please re-review.

2021-03-26 08:51 UTC, Lumpusz commented
@OttoWinter @dudanov can you do another round of review

2021-04-08 07:02 UTC, Lumpusz commented
@glmnet @jesserockz What is still pending for this PR to be merged in? Original reviewers have not shown activity for more than 2 weeks. Happy to incorporate feedback and changes to get this rolling. Thanks.

2021-04-08 09:17 UTC, OttoWinter reviewed
Hi, just had another look at the PR. I'm wondering now if we really should add support for "custom" fan modes/presets etc. This custom logic introduces quite a bit of complexity (any code that works with fan modes will both have to deal with custom settings and the builtin ones).

Are there enough custom fan modes/presets that we can't anticipate to warrant adding this complexity? I mean we can add new enum values for freeze protection etc, as that adds little complexity.

Obviously, adding new enum value is some work (PRs in esphome, aioesphomeapi, and HA core), but we can add all commonly used ones in this PR.

2021-04-08 09:33 UTC, Lumpusz commented
> Hi, just had another look at the PR. I'm wondering now if we really should add support for "custom" fan modes/presets etc. This custom logic introduces quite a bit of complexity (any code that works with fan modes will both have to deal with custom settings and the builtin ones).
> 
> Are there enough custom fan modes/presets that we can't anticipate to warrant adding this complexity? I mean we can add new enum values for freeze protection etc, as that adds little complexity.
> 
> Obviously, adding new enum value is some work (PRs in esphome, aioesphomeapi, and HA core), but we can add all commonly used ones in this PR.

This change reflects the schema of HA. Essentially it works with the enums HA works with. Wherever HA mentions support for custom values, ENUMs should be dynamically extensible. This is what I was trying to do. I personally don't agree with limiting ourselves, and diverging from the HA schema, as later on we might regret it. The goal here is to support the future development of custom values of vendor specific devices. One vendor calls boost 'Boost', others call it 'Turbo'. I understand that there are dedicated naming for some in HA, but anything more than that standard should be as close to the vendor naming convention as possible. If we introduce further enums, it will be much more effort to add yet another one later on, if there is a new device and it lacks the ones that are already there. This way the future change will be local to esphome, without the need to update HA core, and aioesphomeapi.

2021-04-08 09:38 UTC, Lumpusz commented on esphome/components/climate/climate.h
> +  optional<ClimateFanMode> fan_mode;
optional.has_value() drives the logic. The best would be to make it a union, but for std::string it is a no go.

2021-04-13 10:38 UTC, Lumpusz commented
@OttoWinter what is still missing for the merge?

2021-04-13 15:42 UTC, glmnet commented on esphome/components/climate/climate.h
> +  optional<ClimateFanMode> fan_mode;
couldn't `custom_fan_mode.has_value()` be checked instead?
For existing code `fan_mode` can still work as is

2021-04-13 16:00 UTC, Lumpusz commented on esphome/components/climate/climate.h
> +  optional<ClimateFanMode> fan_mode;
> couldn't `custom_fan_mode.has_value()` be checked instead?
> For existing code `fan_mode` can still work as is

The reason I did not do it, is because these two are mutually exclusive, and it is legit for fan_mode to not have a value in case custom_fan_mode has. Dealing with optional, which was designed for these kind of scenarios, seems to be much cleaner to me.

2021-04-13 16:04 UTC, glmnet commented
Agree with @Lumpusz this API is always getting a PR to add something missing that HA does. Making it 1:1 will give less space to have to adapt stuff later.
Also, since `CLIMATE_MODE_AUTO` value changed from 1 to 6, now HA would understand most climate devices are in AUTO instead of HEAT_COOL, so all occurrences of `CLIMATE_MODE_AUTO` in components should be changed to `CLIMATE_MODE_HEAT_COOL`

2021-04-14 07:09 UTC, Lumpusz commented
> Agree with @Lumpusz this API is always getting a PR to add something missing that HA does. Making it 1:1 will give less space to have to adapt stuff later.
> Also, since `CLIMATE_MODE_AUTO` value changed from 1 to 6, now HA would understand most climate devices are in AUTO instead of HEAT_COOL, so all occurrences of `CLIMATE_MODE_AUTO` in components should be changed to `CLIMATE_MODE_HEAT_COOL`

It seems like this meant to be a comment on the PR opened for HA core, if not then I got the wrong end of the stick.

2021-04-19 12:50 UTC, Lumpusz commented
Can this PR be merged? There are other related PRs as well. What is going to be the merge order? When can we expect the functionality to be available across the board?

2021-05-13 07:51 UTC, dudanov approved these changes

2021-05-13 08:04 UTC, Lumpusz commented
@glmnet @OttoWinter @jesserockz can we merge this PR, along with its dependencies?

2021-05-13 20:38 UTC, jesserockz commented on esphome/components/climate/__init__.py
> +        cv.Optional(CONF_CUSTOM_PRESET): cv.string_strict,
Should `fan_mode`/`custom_fan_mode` and `preset`/`custom_preset` be validated as exclusive?

2021-05-13 22:18 UTC, jesserockz requested changes
A few things below and one above I hit the wrong button on

2021-05-13 22:18 UTC, jesserockz commented on esphome/components/midea_ac/climate.py
> +CONF_CUSTOM_PRESETS = "custom_presets"
These probably should be in `const.py`, and the `PRESET_...` ones below

2021-05-13 22:18 UTC, jesserockz commented on esphome/components/midea_ac/midea_frame.h
> +  void set_freeze_protection_mode(bool state) { this->set_bytemask_(31, 0x80, state); };
Some inconsistencies here with the semis after the functions?

2021-05-14 06:55 UTC, Lumpusz commented on esphome/components/climate/__init__.py
> +        cv.Optional(CONF_CUSTOM_PRESET): cv.string_strict,
If you mean mutually exclusive, then I thing they shouldn't. There can be units who only support one or the other, or both. My midea unit supports a few built in presets, as well as a few custom one.

2021-05-14 07:03 UTC, Lumpusz commented on esphome/components/climate/automation.h
> +    call.set_custom_preset(this->custom_preset_.optional_value(x...));
Those are not needed. Internally these try to convert it into a built in enum, if that is not possible, try to validate the value as a custom one, nad potentially set it as a custom mode if it matches any of the supported custom modes.

2021-05-14 07:13 UTC, jesserockz commented on esphome/components/climate/__init__.py
> +        cv.Optional(CONF_CUSTOM_PRESET): cv.string_strict,
But this is the control action, surely you cant select two modes at once? Also the cpp code resets "the other" one

2021-05-14 07:46 UTC, Lumpusz commented on esphome/components/climate/__init__.py
> +        cv.Optional(CONF_CUSTOM_PRESET): cv.string_strict,
Got it, fixed.

2021-05-14 08:02 UTC, jesserockz commented on tests/test4.yaml
> -    components: ["sntp"]
Not sure what happened here?

2021-05-14 08:49 UTC, Lumpusz commented on tests/test4.yaml
> -    components: ["sntp"]
Accidental delete, I put it back.

2021-05-14 09:56 UTC, Lumpusz commented
@jesserockz I updated the PR, and also fixed a bug, which was casued by one of the suggested changes. Now it is all tested and works. Can we merge it in?

2021-05-16 09:53 UTC, jesserockz commented on esphome/components/climate/automation.h
> +    call.set_custom_preset(this->custom_preset_.optional_value(x...));
You missed fixing these lines up, either changing them to use `set_fan_mode` and `set_preset`.
Could you add a test to the test yaml to call climate.control with the custom_fan_mode/custom_preset. 
It will fail with this code as is because `call` is a `ClimateCall` and does not have `set_custom_fan_mode` or `set_custom_preset` functions

2021-05-17 07:15 UTC, Lumpusz commented on esphome/components/climate/automation.h
> +    call.set_custom_preset(this->custom_preset_.optional_value(x...));
Got you, fixed. I also updated the relevant section of the docs about climate control in the linked PR.

2021-05-17 10:03 UTC, jesserockz approved these changes

2021-05-17 10:36 UTC, Lumpusz commented
@jesserockz thanks for the review, when can we merge this PR, what is going to be the order of merges into the upstream repos?

2021-05-23 20:32 UTC, jesserockz requested changes
@Lumpusz Some core changes just merged which changed from `yield` to `await` syntax. Can you merge dev and update your changes?

2021-05-25 07:05 UTC, Lumpusz commented
> @Lumpusz Some core changes just merged which changed from `yield` to `await` syntax. Can you merge dev and update your changes?

@jesserockz Done.

2021-05-25 20:24 UTC, jesserockz approved these changes

2021-05-31 08:03 UTC, Lumpusz commented
@jesserockz @glmnet Not sure how long getting a second opinion takes, can you take a look at this PR? I am happy to resolve merge conflict if you think this is good enough to be merged in.

2021-06-04 10:04 UTC, merged

2021-06-04 11:05 UTC, Lumpusz commented
Thanks, this was quite a journey. 🎉

2021-06-04 11:46 UTC, kroimon commented
This still requires the other two related PRs to be merged to be usable, correct?

2021-06-04 11:48 UTC, Lumpusz commented
> This still requires the other two related PRs to be merged to be usable, correct?

Correct, I am just happy, as updating these PRs was a continuous effort.

2021-06-17 21:35 UTC, jesserockz commented on esphome/components/api/api.proto
> +  CLIMATE_MODE_HEAT_COOL = 6;
> What I suggested could be summarized as: do a project-wide Find&Replace of all old occurences of CLIMATE_MODE_AUTO and replace it with CLIMATE_MODE_HEAT_COOL (including all components, ha/aioesphomeapi codebases). But do not change the associated enum values.

This was missed and is now causing all sorts of issues with the release

2021-06-18 06:59 UTC, Lumpusz commented on esphome/components/api/api.proto
> +  CLIMATE_MODE_HEAT_COOL = 6;
Apologies to anyone who this PR has caused inconveniences.