Tuya improvements
OttoWinter/esphomeyaml pull request #1491
Opened 2021-01-24 19:27 UTC by trvrnrth

## Description:
- Incorporates command queueing changes in #1404 which are working well for me
- Reduces heartbeat interval to every 10 seconds per the official specs to cut down chatter
- Adjusts log levels/placement to make operation clearer (less noise in debug; clearer order in verbose)
- Periodic WiFi status updates so the device can better reflect connection state (eg. thermostat display)
- Pushes of local time when the time is synched so the device stays up to date
- Tuya climate support to respect an optional MCU reported datapoint that reports active state (I'll add a doc PR for this if the approach here looks sensible)
- Support for multi-byte bitmasks/bitmaps/fault datapoints
- Support for string datapoints taken from #1488
- Simplified methods to set datapoint values that uses the already known datapoint info to greatly ease use in lambdas

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-01-24 22:03 UTC, jesserockz commented on esphome/components/tuya/tuya.cpp
> +      wifi_command.payload = std::vector<uint8_t>{0x04};
Could this be if there is an active `api` or `mqtt` connection?

2021-01-24 22:27 UTC, trvrnrth commented on esphome/components/tuya/tuya.cpp
> +      wifi_command.payload = std::vector<uint8_t>{0x04};
That would be nicer if it's easy enough to query. Although I confess I've no idea if it brings any real world improvement to any devices. I've not looked into it but if it's simple enough why not!

2021-01-24 22:30 UTC, trvrnrth commented on esphome/components/tuya/climate/tuya_climate.h
> +  float hysteresis_{1.0f};
The idea of bringing this out here was that it would be easy to add a config to set it. My thermostat actually has it available as a (slightly awkward) enum but support to read from that didn't seem sensible as I would imagine any device providing the value as a datapoint will also provide the active state which is more useful.

2021-02-04 04:26 UTC, ic3man5 commented
I'm currently testing #1404 and was wonder if this will become the actual merged branch for the issue. If so, what needs to happen to make this pull request happen? Tests need to be written?

2021-03-19 15:50 UTC, trvrnrth commented on esphome/components/tuya/tuya.cpp
> +      wifi_command.payload = std::vector<uint8_t>{0x04};
Took the approach from the status component and added.

2021-04-03 16:31 UTC, kroimon commented on esphome/components/tuya/tuya.cpp
> +  }
Are there returns missing in these cases to abort setting the value?

2021-04-03 17:13 UTC, kroimon commented
Would be great to get this merged.

I think it provides a few good improvements and also allows the tuya switch component to switch enum type datapoints due to the new value setting logic relying on known datapoints and their types.

2021-04-03 21:28 UTC, trvrnrth commented on esphome/components/tuya/tuya.cpp
> +  }
@kroimon Indeed there were! Updated now :)

2021-04-03 23:47 UTC, kroimon approved these changes

2021-04-04 15:49 UTC, kroimon commented on esphome/components/tuya/climate/tuya_climate.cpp
> +    } else if (this->active_state_ == this->active_state_cooling_value_) {
`active_state_heating_value_` and `active_state_cooling_value_` are optional and might not have a value assigned here.
You should check for `has_value()` here and also add proper validation to the Python code generation.

2021-04-04 18:44 UTC, trvrnrth commented on esphome/components/tuya/climate/tuya_climate.cpp
> +    } else if (this->active_state_ == this->active_state_cooling_value_) {
Good idea. I've beefed up the checks here and in the validation. The active heating value does default to 1 as that seemed like an obvious choice (for my use case/device at any rate) but I've left all the checks in place anyway. I was sort of on the fence about having a default for that at all but I figured it would do no harm.

2021-04-06 12:03 UTC, OttoWinter reviewed
Thanks! I had a look at this code, but unfortunately posted the comments in the wrong PR. Please see the comments here: #1669. They also apply here.

(for the future, please split such larger code changes into multiple PRs; for example, new features to the climate component should be separate from sending time periodically; otherwise reviewing PRs gets hard)

2021-04-06 12:24 UTC, trvrnrth commented
> Thanks! I had a look at this code, but unfortunately posted the comments in the wrong PR. Please see the comments here: #1669. They also apply here.
> 
> (for the future, please split such larger code changes into multiple PRs; for example, new features to the climate component should be separate from sending time periodically; otherwise reviewing PRs gets hard)

Yeah; this grew a few extra legs that I wasn't originally planning. I'll address the comments.

2021-04-06 12:44 UTC, kroimon requested changes

2021-04-06 12:44 UTC, kroimon commented on esphome/components/tuya/climate/tuya_climate.cpp
>        this->target_temperature = datapoint.value_int * this->target_temperature_multiplier_;
Swap these lines to get the debug message right.

2021-04-06 12:44 UTC, kroimon commented on esphome/components/tuya/climate/tuya_climate.cpp
>        this->current_temperature = datapoint.value_int * this->current_temperature_multiplier_;
Swap these lines to get the debug message right.

2021-04-06 13:20 UTC, kroimon commented on esphome/components/tuya/climate/tuya_climate.cpp
>      this->mode = *call.get_mode();
Another thing I just noticed while working with the code:
It is unnecessary to set `this->mode` and `this->this->target_temperature` and call `compute_state_()` and `publish_state()` in `TuyaClimate::control()` as they will be updated in the listeners once the MCU reports back the changed datapoints.

2021-04-06 13:38 UTC, trvrnrth commented on esphome/components/tuya/climate/tuya_climate.cpp
>      this->mode = *call.get_mode();
True. It's probably more accurate to wait until that happens and prevents any possible flip-flopping.

2021-04-06 13:41 UTC, kroimon commented on esphome/components/tuya/climate/tuya_climate.cpp
>      this->mode = *call.get_mode();
Then also replace the assignment of `mode` and `target_temperature` with local const variables.

2021-05-03 19:49 UTC, trvrnrth commented
As an example of usage here's an [example configuration for an an ET61-W thermostat](https://pastebin.com/qatJjG97) which covers the primary functionality.

2021-05-31 04:37 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
> +        )
Considering there is a `default=1` for this config, this code will never execute

2021-05-31 05:09 UTC, jesserockz requested changes

2021-05-31 06:01 UTC, jesserockz commented
Following on from this, I have flashed these changes to my tuya heater and now I cannot control it, because the datapoints are not sent from the heater to the ESP on startup and they are not in `this->datapoints_` which means when it tries to send the datapoint, it does not know the type/length to send.

2021-06-01 09:56 UTC, trvrnrth commented on esphome/components/tuya/fan/tuya_fan.cpp
> +      }
I think the goalposts have moved since I wrote this. I'll check the current restrictions in dev and amend accordingly.

2021-06-01 09:58 UTC, trvrnrth commented on esphome/components/tuya/climate/__init__.py
> +        )
I was a little on the fence about that default and didn't have it to start with hence this validation being in place. But I think it's safe enough and a fairly sane default so I'll take this out.

2021-06-01 10:00 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
> +        )
I am happy either way, default with this removed, or no default and this check exists.

2021-06-01 10:36 UTC, trvrnrth commented on esphome/components/tuya/fan/tuya_fan.cpp
> +      }
Yep, bad merge. Corrected now.

2021-06-01 10:38 UTC, jesserockz commented
The issue with bailing out on unknown datapoints is that I will not be able to control my heater...

The heater/tuyaMCU only sends the current temperature every 10 seconds, and the other datapoints only if they are changed (either via datapoint settings, or via pressing the buttons on the heater itself). So in an ideal automated world, I would not touch those buttons on the heater, therefore the datapoints would never be sent/recognised by ESPHome...

2021-06-01 10:42 UTC, trvrnrth commented
> The issue with bailing out on unknown datapoints is that I will not be able to control my heater...
> 
> The heater/tuyaMCU only sends the current temperature every 10 seconds, and the other datapoints only if they are changed (either via datapoint settings, or via pressing the buttons on the heater itself). So in an ideal automated world, I would not touch those buttons on the heater, therefore the datapoints would never be sent/recognised by ESPHome...

That latest commit was just me fixing the behaviour for the current setup. Does your device not report the current datapoints when requested during the init phases in response to the `DATAPOINT_QUERY`? My understanding of the specs is that this should return all current values (and it does on my thermostat device at any rate).

2021-06-01 10:45 UTC, trvrnrth commented
Is it possible that your device isn't making it through all the init stages and not getting as far as the datapoint query? Perhaps getting stuck at the wifi stage for some reason? I've not read the full conversation on discord but it seems like having a list of all the datapoints and there values to be able to work with later would help with some other issues!

2021-06-01 10:48 UTC, jesserockz commented
The issue with the setup stage is that I cannot attach to the logs at setup. But let me try this branch again and see what happens.

2021-06-01 10:53 UTC, jesserockz commented
Ok, stupid me... At the same time I changed to this branch, I updated my yaml to packages and the logger baud_rate was not getting overridden correctly... All working fine now :facepalm:

2021-06-01 11:09 UTC, jesserockz approved these changes

2021-06-01 11:12 UTC, jesserockz commented
> I've not read the full conversation on discord but it seems like having a list of all the datapoints and their values to be able to work with later would help with some other issues!

Nah, I have two different tuya based heaters, one uses this component just fine (I wrote the climate for it when I purchased it) but my newer ones (talked about in discord) use a totally different protocol that is not yet on the internet. Its almost completely incompatible with this component and I have duplicated `tuya` and started writing a `tuya-new` so I could try to figure it out.

2021-06-02 00:14 UTC, jesserockz commented on esphome/components/tuya/tuya.cpp
> +  this->set_interval("heartbeat", 10000, [this] { this->send_empty_command_(TuyaCommandType::HEARTBEAT); });
The scheduler is set up in a way that it executes the first time now-ish
So this results in 2 heartbeats.

```suggestion
  this->set_interval("heartbeat", 10000, [this] { this->send_empty_command_(TuyaCommandType::HEARTBEAT); });
```

2021-06-02 05:13 UTC, kroimon commented on esphome/components/tuya/tuya.cpp
> -  this->send_empty_command_(TuyaCommandType::HEARTBEAT);
Will this delay the whole initialization by 10 seconds?

2021-06-02 05:16 UTC, kroimon commented on esphome/components/tuya/tuya.cpp
> -  this->send_empty_command_(TuyaCommandType::HEARTBEAT);
Sorry, didn't see your comment that the first interval will be shorter than what is given as the argument.

2021-06-02 05:36 UTC, jesserockz commented on esphome/components/tuya/tuya.cpp
> -  this->send_empty_command_(TuyaCommandType::HEARTBEAT);
The scheduler sets the `last_execution` at now - interval, so its immediately scheduled

2021-06-02 08:09 UTC, trvrnrth commented on esphome/components/tuya/tuya.cpp
> +  this->set_interval("heartbeat", 10000, [this] { this->send_empty_command_(TuyaCommandType::HEARTBEAT); });
Ah, cool. That makes that a bit neater. I didn't even think to check!

2021-06-02 09:31 UTC, merged