Add support for PMSA003i
OttoWinter/esphomeyaml pull request #1501
Opened 2021-01-30 02:07 UTC by sjtrny

## Description:

Adds support for the PMSA003i sensor, which is an i2c version of similar particulate sensors from Plantower.

Original implementation here https://github.com/sjtrny/pmsa003i

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 
- pending
- documentation mostly written, just needs to be copied across from https://github.com/sjtrny/pmsa003i
- esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ **YES** ] The code change is tested and works locally.
  - [ **NO** ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [  **N/A** ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-03-14 01:54 UTC, glmnet requested changes
Please rebase as this would fail marging on dev.

Thanks

2021-03-14 01:54 UTC, glmnet commented on esphome/components/pmsa003i/pmsa003i.h
> +  sensor::Sensor *pm_size_sensor_{nullptr};
Where is this used?

2021-03-14 01:54 UTC, glmnet commented on esphome/components/pmsa003i/sensor.py
> +                                                   ICON_CHEMICAL_WEAPON, 2),
this needs rebase from dev, now sensor.sensor_schema requires 4 arguments

2021-03-14 01:54 UTC, glmnet commented on esphome/components/pmsa003i/pmsa003i.cpp
> +    ESP_LOGD(TAG, "Read success. Updating sensors.");
```suggestion
    ESP_LOGV(TAG, "Read success. Updating sensors.");
```

2021-03-14 01:54 UTC, glmnet commented on esphome/components/pmsa003i/pmsa003i.cpp
> +    ESP_LOGD(TAG, "Read failure. Skipping update.");
you can use https://github.com/esphome/esphome/blob/08998caabc7d592ef07bb1bdc7386ae4e697b4a0/esphome/core/component.h#L117 to set a warning here, you then need to clear it on success reads

2021-03-16 11:02 UTC, sjtrny commented on esphome/components/pmsa003i/pmsa003i.h
> +  sensor::Sensor *pm_size_sensor_{nullptr};
Nowhere. I've removed it.

2021-03-16 11:02 UTC, sjtrny commented on esphome/components/pmsa003i/sensor.py
> +                                                   ICON_CHEMICAL_WEAPON, 2),
Done

2021-03-16 11:04 UTC, sjtrny commented on esphome/components/pmsa003i/pmsa003i.cpp
> +    ESP_LOGD(TAG, "Read success. Updating sensors.");
Done

2021-03-16 11:04 UTC, sjtrny commented on esphome/components/pmsa003i/pmsa003i.cpp
> +    ESP_LOGD(TAG, "Read failure. Skipping update.");
I've added this. Let me know if I made a mistake.

2021-08-03 14:06 UTC, OttoWinter reviewed
Thanks for this contribution! Code looks good to me. Just one minor thing about the `struct`, can you have a look at it

2021-08-03 14:06 UTC, OttoWinter commented on esphome/components/pmsa003i/pmsa003i.h
> +using PM25AQIData = struct PMSAQIdata {
```suggestion
struct PM25AQIData {
```

(typedef/using struct not needed in C++)

2021-08-10 08:58 UTC, OttoWinter approved these changes

2021-08-10 09:00 UTC, merged