Sgp40
OttoWinter/esphomeyaml pull request #1513
Opened 2021-02-05 16:37 UTC by SenexCrenshaw

## Description:
Implements SGP40 VOC sensor

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#985

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-02-10 16:46 UTC, SenexCrenshaw commented
I received and email form Sensirion with a potential cleaner way to do this and a cleaner library. I am going to investigate.

2021-02-15 14:09 UTC, glmnet commented on esphome/components/sgp40/sensirion_voc_algorithm.h
> +#define VocAlgorithm_MEAN_VARIANCE_ESTIMATOR__FIX16_MAX (32767.)
use static constexpr

2021-02-15 15:35 UTC, glmnet requested changes
I'm not reviewing the algorithm, but seems just calculations.
Please see inline reviews.
Thanks

2021-02-15 15:35 UTC, glmnet commented on esphome/components/sgp40/sgp40.h
> +static const uint8_t SGP40_I2CADDR_DEFAULT = 0x59;
this should only be on the py as a default passed in the i2c base schema

2021-02-15 15:35 UTC, glmnet commented on esphome/components/sgp40/sgp40.cpp
> +  delay(250);  // NOLINT
this is a really long delay, you should rework this so you return from the setup() function and set a state variable so you know you should keep waiting e.g. 250 ms before doing the code that follows this line.

2021-02-15 15:35 UTC, glmnet commented on esphome/components/sgp40/sgp40.cpp
> +  auto *buf = new uint8_t[num_bytes];
can you do this with `std::vector<uint8_t>` ?

2021-02-15 15:40 UTC, SenexCrenshaw commented on esphome/components/sgp40/sgp40.h
> +static const uint8_t SGP40_I2CADDR_DEFAULT = 0x59;
Removed since the schema was doing this anyway

2021-02-15 15:59 UTC, SenexCrenshaw commented on esphome/components/sgp40/sgp40.cpp
> +  auto *buf = new uint8_t[num_bytes];
I converted it to std::vector

2021-02-15 16:00 UTC, SenexCrenshaw commented on esphome/components/sgp40/sgp40.cpp
> +  delay(250);  // NOLINT
I changed the logic to using ``this->set_timeout(250)``

2021-02-15 17:48 UTC, glmnet requested changes
Just see this

2021-02-15 17:48 UTC, glmnet commented on esphome/components/sgp40/sgp40.cpp
> +    ESP_LOGD(TAG, "Sensor has not collected enough samples yet. (%d/%d) VOC index is: %u", ++this->samples_read_,
This will not work increment the variable inside the log call. 

If log level is info or log disabled the value will never change

2021-02-16 10:30 UTC, SenexCrenshaw commented on esphome/components/sgp40/sgp40.cpp
> +    ESP_LOGD(TAG, "Sensor has not collected enough samples yet. (%d/%d) VOC index is: %u", ++this->samples_read_,
OMG, what a miss! Thanks for catching that!

2021-04-03 20:24 UTC, kbx81 commented
Finally got around to testing this...and it is wonderful! Mergey mergey! 😁

2021-04-09 01:40 UTC, merged