Add support for ILI9486 Display
OttoWinter/esphomeyaml pull request #1523
Opened 2021-02-07 20:59 UTC by MasterTim17

## Description:
I added the support for the 3.5" Raspberry Display with the display controller ILI9486. 
The display buffer is splitted, so it can be allocated in the RAM

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-03-05 02:16 UTC, jesserockz commented on esphome/components/wifi/wifi_component.cpp
> -          this->state_ = WIFI_COMPONENT_STATE_STA_CONNECTING;
Why is this line being removed?

2021-03-05 02:35 UTC, jesserockz requested changes

2021-03-05 02:35 UTC, jesserockz commented on esphome/components/ili9486/display.py
> +    cv.Optional(CONF_LED_PIN): pins.gpio_output_pin_schema,
Can you remove the LED pin from the display?
It can be added simply as another gpio switch in yaml. 
Your method also offers no control over it and just forces it on all the time.

2021-03-05 09:58 UTC, MasterTim17 commented on esphome/components/wifi/wifi_component.cpp
> -          this->state_ = WIFI_COMPONENT_STATE_STA_CONNECTING;
it was from a older commit which doesnt got merged into main.
im new to git

2021-03-05 09:58 UTC, MasterTim17 commented on esphome/components/ili9486/display.py
> +    cv.Optional(CONF_LED_PIN): pins.gpio_output_pin_schema,
conf_led_pin is optional, but im gonna remove it because it dont get used

2021-03-26 07:52 UTC, drewp commented
https://github.com/drewp/esphome/commit/c160835738d36949bec7b70ec860ad01cb8ea5e4 adds a version of this modified for the 8-bit parallel output mode. Perhaps we should put most of it in ili9486_base and then derive from SPI or implement the parallel mode in two more devices?

2021-04-13 20:03 UTC, danyboy666 commented
is this blocked?

2021-04-13 21:13 UTC, jesserockz commented
> is this blocked?

Considering there are failing tests, yes this is blocked...

2021-04-13 21:15 UTC, danyboy666 commented
> > is this blocked?
> 
> Considering there are failing tests, yes this is blocked...

I'm testing this componant right now anything I can do to help? Right now i'm stuck with compiling tho.

2021-04-13 21:37 UTC, MasterTim17 commented
fixed the ability to compile by writing a color convert function.
i dont know how i should fix the failed checks

2021-07-04 19:07 UTC, workingmanrob commented
Error: /__w/esphome/esphome/esphome/components/display/display_buffer.h:321:12: error: invalid case style for protected method 'display_buffer_part' [readability-identifier-naming,-warnings-as-errors]
  uint32_t display_buffer_part(uint32_t x);

If somebody could explain to MasterTim17 what case this needs to be in for the linter to be happy I bet he could fix it.  I have no idea...

I have this working on an esp32 with a little hello world displayed.  Works great.  Thanks Tim!

2022-02-02 01:36 UTC, closed without merging