Device class attribute for sensor component
OttoWinter/esphomeyaml pull request #1525
Opened 2021-02-09 00:29 UTC by marecabo

## Description:

This is a simple copy-paste/adaption of the `device_class` code from the [binary_sensor](https://github.com/esphome/esphome/tree/dev/esphome/components/binary_sensor) component/class to the [sensor](https://github.com/esphome/esphome/tree/dev/esphome/components/sensor) component class. It is not tested, as I still have to figure out how to do that in my HA instance. Help and hints are appreciated and anyone faster at this, feel free to build upon this pr.

Todo:
- [ ] Test this change
- [ ] Copy [this line](https://github.com/esphome/aioesphomeapi/blob/887f44eaa4007498eebe9091f47f77b92fc0c03e/aioesphomeapi/model.py#L46) from the binary sensor to the [sensor section](https://github.com/esphome/aioesphomeapi/blob/887f44eaa4007498eebe9091f47f77b92fc0c03e/aioesphomeapi/model.py#L150).
- [ ] update doc
- [ ] (more?)

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/553

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> *(not yet)*

## Checklist:
  - [ ] The code change is tested and works locally. *(not yet)*
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs). *(not yet)*

2021-02-09 18:31 UTC, sermayoral commented
Wow! Great PR!! Thanks for implementing it. I think you have to do changes in https://github.com/esphome/aioesphomeapi as well, in order to transfer device_class attribute to HA.

2021-02-10 17:20 UTC, marecabo commented on esphome/components/mhz19/sensor.py
> +    cv.Optional(CONF_TEMPERATURE): sensor.sensor_schema(UNIT_CELSIUS, ICON_EMPTY, 0, DEVICE_CLASS_TEMPERATURE),
I removed the explicit specification of the temperature icon because the device_class in HA will set the icon accordingly. Specifying an icon *and* a device_class might potentially cause irritation, if HA changes the icons assigned to a device_class.

2021-02-10 20:45 UTC, marecabo commented on esphome/components/mhz19/sensor.py
> +        UNIT_CELSIUS, ICON_EMPTY, 0, DEVICE_CLASS_TEMPERATURE),
I removed the explicit specification of the temperature icon because the device_class in HA will set the icon accordingly. Specifying an icon and a device_class might potentially cause irritation, if HA changes the icons assigned to a device_class.

2021-02-10 21:26 UTC, marecabo commented on esphome/components/sensor/__init__.py
> +def sensor_schema(unit_of_measurement_, icon_, accuracy_decimals_, device_class_=DEVICE_CLASS_NONE):
I added a default argument the the new `device_class_` argument to be compatible with the many existing components calling this method.

Are you fine with this pr not yet updating *all* existing components and creating separate prs for that?

2021-02-12 19:37 UTC, jesserockz commented on esphome/components/sensor/__init__.py
> +def sensor_schema(unit_of_measurement_, icon_, accuracy_decimals_, device_class_=DEVICE_CLASS_NONE):
I have not reviewed the code yet, but this would be acceptable without updating every component in this PR.

2021-02-13 07:56 UTC, jseidl commented
This is awesome, thanks so much for this contribution!

2021-02-14 18:58 UTC, marecabo commented
The HA esphome integration also needs to be updated for HA to pick up the new `device_class` attribute of the esphome sensor component: https://github.com/home-assistant/core/compare/dev...marecabo:esphome-sensor-device-class

Then device classes properly appear in HA! 🎉

2021-02-14 21:45 UTC, jesserockz requested changes
Looks good to me apart from one below comment on tests.

2021-02-14 21:45 UTC, jesserockz commented on tests/component_tests/sensor/test_sensor.py
> +    assert "s_1->set_device_class(\"voltage\");" in main_cpp
While it would be nice to have a test suite for the python side of ESPHome, just adding the new config options to an existing test file is enough for now. Those tests files are compiled to verify there are just no compile errors.

2021-02-14 23:14 UTC, glmnet commented on tests/component_tests/sensor/test_sensor.py
> +    assert "s_1->set_device_class(\"voltage\");" in main_cpp
Hmm guess you never tried to run the tests. It'd be nice to have them run in the CI script. I'm not a fan of Github Actions so... don't expect it from me. But `pytest` is there.

2021-02-14 23:24 UTC, glmnet commented on esphome/components/sensor/__init__.py
> +        cv.Optional(CONF_DEVICE_CLASS, default=device_class_): device_class,
setting a default here with value `CONF_DEVICE_CLASS_NONE` will make epshome to always emit code (`cg.add(var.set_device_class(config[CONF_DEVICE_CLASS]))`) I don't know if this is your intention, did not check how HA handles that. Anyway we can merge this and fix it later on your other PR

2021-02-15 01:59 UTC, marecabo commented on esphome/components/sensor/__init__.py
> +        cv.Optional(CONF_DEVICE_CLASS, default=device_class_): device_class,
Thanks for the suggestion, I also prefer to not create unused code or empty attributes. I made the arguments optional and now only add them to the config if they differ from the default values. However, this still results in empty entity attributes in HA (which HA just ignores, but do not look neat).
<img src="https://user-images.githubusercontent.com/23156476/107896973-2f754b80-6f38-11eb-9149-7737d9c5765d.png" width="80%">
But this in turn can be fixed with [this commit in the HA esphome integration](https://github.com/home-assistant/core/commit/784b7341a1968a3e0987d6e3e8de58e8f1ebb0bc).

2021-02-15 15:18 UTC, glmnet commented on esphome/components/sensor/__init__.py
> +        cv.Optional(CONF_DEVICE_CLASS, default=device_class_): device_class,
yeah, the other stuff (e.g.binary_sensor) does the same

2021-02-15 15:19 UTC, glmnet commented
https://github.com/esphome/aioesphomeapi/pull/25 is done and [v2.6.5](https://pypi.org/project/aioesphomeapi/) is ready for link to the HA pr.

2021-02-15 15:49 UTC, merged

2021-02-20 02:49 UTC, nareddyt commented on esphome/components/sensor/__init__.py
> +device_class = cv.one_of(*DEVICE_CLASSES, lower=True, space='_')
I see you added some strict validation of the device class here.

Is this intended? My concern is how updating device classes will work - If HA introduces new device classes, we need to update the ones here as well. It will block esphome users from using the new device class until someone updates and a new release is made.

Maybe that's fine. I doubt HA will add new device classes often, and the validation on esphome side will be useful to prevent typos. Wondering if you have any thoughts.

2021-02-20 03:23 UTC, jesserockz commented on esphome/components/sensor/__init__.py
> +device_class = cv.one_of(*DEVICE_CLASSES, lower=True, space='_')
This would be a very small PR to add new classes and would be merged and released quickly.

2021-02-20 09:07 UTC, marecabo commented on esphome/components/sensor/__init__.py
> +device_class = cv.one_of(*DEVICE_CLASSES, lower=True, space='_')
The issue is already present with the binary_sensor component, which uses the same validation:
https://github.com/esphome/esphome/blob/25924ca4e83dc9645b1c072efd6c7d64923c50d6/esphome/components/binary_sensor/__init__.py#L183