Added Waveshare 2.90inch V2
OttoWinter/esphomeyaml pull request #1538
Opened 2021-02-16 14:35 UTC by K-r-i-s-t-i-a-n

## Description:
Added support for Waveshare 2.90inch Version 2 e-ink display

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-02-16 21:23 UTC, jesserockz approved these changes
LGTM

2021-02-17 03:48 UTC, nikito7 requested changes
Maybe is better

if == v2
else
all others

better future approach ?

2021-02-17 03:53 UTC, jesserockz requested changes
As @nikito7 mentioned, consistency is key and allows other screens to add their own paths if needed

2021-02-17 03:53 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +
```suggestion
  if (this->model_ == WAVESHARE_EPAPER_2_9_IN_V2) {
    this->data(full_update ? 0xF7 : 0xFF);
  } else {
    this->data(0xC4);
  }

```

2021-02-17 03:53 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.h
> +    }
```suggestion
    if (this->model_ == WAVESHARE_EPAPER_2_9_IN_V2) {
      // COMMAND DEEP SLEEP MODE
      this->command(0x10);
      this->data(0x01);
    } else {
      // COMMAND DEEP SLEEP MODE
      this->command(0x10);
    }
```

2021-02-17 18:10 UTC, jesserockz approved these changes

2021-02-17 18:12 UTC, merged