MCP23XXX Refactor
OttoWinter/esphomeyaml pull request #1560
Opened 2021-02-22 18:55 UTC by jesserockz

## Description:

This refactors the `MCP23008`, `MCP23017`, `MCP23S08` and `MCP23S17` to remove duplicate code and inherit from new base classes.

It also removes the duplicate pin schemas and consolidates all 4 into a single new schema with key `mcp23xxx` for the component id.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-02-28 04:24 UTC, kbx81 commented
@jesserockz this is looking good! I want to test it out but time keeps getting away from me. I rolled through the code, though, and I like how you've (re)arranged things. 😄

2021-03-05 13:36 UTC, glmnet commented on esphome/components/mcp23016/__init__.py
> +)
Are you modifying just the formatting on these? Why?

2021-03-05 13:39 UTC, glmnet requested changes
This pr has lots of changes with files with almost the same name and reviewing file changes with just formattings is quite annoying waste of time. I've seen other people already do this and asked him to rollback the format change, I'm ok with a formatter update on the codebase but that will be another PR

2021-03-05 21:31 UTC, jesserockz commented
> This pr has lots of changes with files with almost the same name and reviewing file changes with just formattings is quite annoying waste of time. I've seen other people already do this and asked him to rollback the format change, I'm ok with a formatter update on the codebase but that will be another PR

Yeah sorry, I just ran `black mcp*`

2021-03-06 00:12 UTC, jesserockz commented on esphome/components/mcp23016/__init__.py
> +)
I reverted the mcp23016 file =)

2021-03-07 19:23 UTC, merged