Modbus sensor
OttoWinter/esphomeyaml pull request #1571
Opened 2021-03-01 22:48 UTC by madron

# What does this implement/fix? 

A generic modbus sensor that can be configured to read a lot of currently unsupported modbus device.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuraiton files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [x] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [x] Linux

## Example entry for `config.yaml`:
This configuration mimics the already existing pzemac component
```yaml
# Example config.yaml
uart:
  rx_pin: GPIO16
  tx_pin: GPIO17
  baud_rate: 9600

sensor:
  - platform: modbus_sensor
    address: 1
    register: 0
    sensors:
      - name: voltage
        unit_of_measurement: V
        device_class: voltage
        accuracy_decimals: 1
        filters:
          multiply: 0.1
      - name: current
        length: 2
        unit_of_measurement: A
        device_class: current
        accuracy_decimals: 3
        filters:
          multiply: 0.001
      - name: power
        length: 2
        unit_of_measurement: W
        device_class: power
        accuracy_decimals: 1
        filters:
          multiply: 0.1
      - name: energy
        length: 2
        unit_of_measurement: Wh
        device_class: energy
        accuracy_decimals: 0
      - name: frequency
        unit_of_measurement: Hz
        accuracy_decimals: 1
        filters:
          multiply: 0.1
      - name: power_factor
        device_class: power_factor
        accuracy_decimals: 2
        filters:
          multiply: 0.01
```

# Explain your changes

I wrote this component for my own use.  
If you think it may be useful to someone else out there, I'll try to improve it and add some documentation.
I'll use it for a test bench for the next step: a component for the Eastron SDM family (SDM120, SDM220, SD630)
There's already some effort ( #745 ) but unluckily it supports the only sensor that I don't need !  ;-) 

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-03-02 04:26 UTC, nikito7 commented
Only read one register?

2021-03-02 14:01 UTC, glmnet requested changes
Adding a generic component like this is not as adding a simple i2c sensor, please mind design effort required in it.

Here are some ideas to make this component easier to understand and use.

Please also consider maintaining docs at the same time, it's hard doing it the first time but then helps a lot even on review phase.

2021-03-02 14:39 UTC, madron commented on esphome/components/modbus_sensor/modbus_sensor.h
> +  uint16_t register_;
What about start_register_ or start_register_address_ and change the parameter name accordingly ?
It contains the address of the first register only.

2021-03-02 14:42 UTC, madron commented on esphome/components/modbus_sensor/modbus_sensor.h
> +  void set_sensor(sensor::Sensor *sensor) { sensors_.push_back(sensor); }
Yes, much better.

2021-03-02 14:43 UTC, madron commented on esphome/components/modbus_sensor/sensor.py
> +    cv.Optional(CONF_LENGTH, default=1): cv.int_range(min=1, max=2),
This is a very good idea !

2021-03-02 15:09 UTC, madron commented on esphome/components/modbus_sensor/sensor.py
> +CONFIG_SCHEMA = cv.Schema({
I did not dare to poke around the already existing modbus component, but your idea makes sense.
Maybe it get to complex for a single configuration ?  Every device can have several registers sensors but we can put up to 255 device on a single bus.
And maybe better to prepare for future write support.  A lot to think about.
Please feel free to provide a schema as a an idea of the feature we'd like: it would be a great help.

If you think that there is some interest for modbus I can try to improve and add some documentation: I didn't try to document the component because it is useless if I am the only one using this component in my own fork !  ;-)

2021-03-02 15:22 UTC, nikito7 commented
You can check this:

https://tasmota.github.io/docs/Smart-Meter-Interface/

But it's too complex to do

2021-03-02 15:26 UTC, nikito7 commented
Or home assistant style

https://github.com/tiagofreire-pt/Home_Assistant_EDP_Box/blob/master/Home%20Assistant/configuration-direto.yaml

2021-03-02 19:43 UTC, madron commented on esphome/components/modbus_sensor/sensor.py
> +CONFIG_SCHEMA = cv.Schema({
Here's a draft for a more generic configuration:
```yaml
modbus:
  - uart_id: xxx
    devices:
      - modbus_address: 0x01
        readings:
          # A contiguous set of data (coils, inputs or registers) read by a single command.
          - start_address: 10001
            # for addresses below 19999 only binary register_type should be permitted
            # https://en.wikipedia.org/wiki/Modbus#Modbus_object_types
            update_interval: 10s
            registers:  # Can I call them registers even if they are coils ? 
                        # Or maybe better to switch to a more generic name ?  Variables ?
              - register_type: binary
                binary_sensors:
                  - name: device_on
                    bit: 0
                  - name: device_warm
                    bit: 2
          - start_address: 30001
            update_interval: 120s
            registers:
              - register_type: 16bit
                sensor:
                  name: single_16bit_register
              - register_type: 32bit
                sensor:
                  name: 32bit_register
              - register_type: 32bit_reversed
                sensor:
                  name: 32bit_reversed_register
              - register_type: binary
                binary_sensors:
                  - name: alarm
                    bit: 15

```
Any thoughts ?

2021-03-02 21:18 UTC, madron commented
> Or home assistant style
> 
> https://github.com/tiagofreire-pt/Home_Assistant_EDP_Box/blob/master/Home%20Assistant/configuration-direto.yaml

This one is very nice but it doesn't support contiguous reads that are much more efficient than reading one register at a time.
In my second draft I tried to support binary sensors too but I'not satisfied.  It's quite hard to find a simple and flexible configuration.

Here is my second attempt:
```yaml
modbus:
  - uart_id: xxx
    devices:
      - modbus_address: 0x01
        readings:
          # A contiguous set of data (coils, inputs or registers) read by a single command.
          - start_address: 10001
            # for addresses below 19999 only binary register_type should be permitted
            # https://en.wikipedia.org/wiki/Modbus#Modbus_object_types
            update_interval: 10s
            registers:  # Can I call them registers even if they are coils ? 
                        # Or maybe better to switch to a more generic name ?  Variables ?
              - register_type: binary
                binary_sensors:
                  - name: device_on
                    bit: 0
                  - name: device_warm
                    bit: 2
          - start_address: 30001
            update_interval: 120s
            registers:
              - register_type: 16bit
                sensor:
                  name: single_16bit_register
              - register_type: 32bit
                sensor:
                  name: 32bit_register
              - register_type: 32bit_reversed
                sensor:
                  name: 32bit_reversed_register
              - register_type: binary
                binary_sensors:
                  - name: alarm
                    bit: 15

```
This one supports sensors, binary_sensors and contiguous reads but it's not very simple to explain/understand.

2021-03-02 23:16 UTC, madron commented on esphome/components/modbus_sensor/modbus_sensor.h
> +  uint16_t register_;
Fixed in a3c3f189940476b8ea2f1765ccb7420f35d87092

2021-03-02 23:16 UTC, madron commented on esphome/components/modbus_sensor/modbus_sensor.h
> +  void set_sensor(sensor::Sensor *sensor) { sensors_.push_back(sensor); }
Fixed in a3c3f189940476b8ea2f1765ccb7420f35d87092

2021-03-02 23:17 UTC, madron commented on esphome/components/modbus_sensor/sensor.py
> +    cv.Optional(CONF_LENGTH, default=1): cv.int_range(min=1, max=2),
Fixed in a3c3f189940476b8ea2f1765ccb7420f35d87092

2021-03-04 01:19 UTC, nikito7 commented
If you want support a meter.

```
+1,14,m,1,9600,EB1,5,30,r010400010001,r0104006C0007,r010400730007,r0104007B0005,r010400260003,r010400160002,r010400180004

; 01

1,01040cxxxxxxxxxxuu@i0:1,Clock ,h,Clock_H,16
1,01040cxxxxxxxxxxxxuu@i0:1,Clock ,m,Clock_M,16
1,01040cxxxxxxxxxxxxxxuu@i0:1,Clock ,s,Clock_S,16
```
Baud Rx Tx
8N1 8N2 8E1 8E2 selection
Already in uart I think

(This is from tasmota)

r0104006C0007

01 - slave id
04 - function code
006C - begin register
0007 - number of consecutive registers to retrieve 

Now the answer and decoding

01040cxxxxxxxxxxuu@i0:1

01 id
04 function
0c byte count
xx ignore byte
...
and... "types"

- xx = ignore value (1 byte) or xN = ignore N bytes
- ss = extract a signed byte
- uu = extract an unsigned byte
- UUuu = extract an unsigned word (high order byte first)
- uuUU = extract an unsigned word (low order byte first)
- UUuuUUuu = extract an unsigned long word (high order byte first)
- SSss = extract a signed word (high order byte first)
- ssSS = extract a signed word (low order byte first)
- SSssSSss = extract an signed long word (high order byte first)
- ffffffff = extract a float value
- FFffFFff = extract a reverse float value

2021-03-04 01:28 UTC, nikito7 commented
Send to meter: r0104006C0007

Decoders

; 6C

1,01040eUUuu@i1:10,Tensão L1 ,V,Voltage_L1,1
1,01040exxxxxxxxUUuu@i1:10,Tensão L2 ,V,Voltage_L2,1
1,01040exxxxxxxxxxxxxxxxUUuu@i1:10,Tensão L3 ,V,Voltage_L3,1

1,=h<hr>

1,01040exxxxxxxxxxxxxxxxxxxxxxxxUUuu@i1:10,Corrente Total ,A,Current_Sum,17

1,01040exxxxUUuu@i1:10,Corrente L1 ,A,Current_L1,17
1,01040exxxxxxxxxxxxUUuu@i1:10,Corrente L2 ,A,Current_L2,17
1,01040exxxxxxxxxxxxxxxxxxxxUUuu@i1:10,Corrente L3 ,A,Current_L3,17

---

You can read request several registers 
But then you will need some sort of index

Because the answer will be all the registers asked in one line/answer

2021-03-04 01:54 UTC, nikito7 commented
02:40:27.933 > 01 04 00 6c 00 07 71 d5 
02:40:28.200 : 01 04 0e 09 6c 00 01 09 67 00 01 09 5e 00 0e 00 11 76 f8 

```
modbus: 
  uart0:
    interval: 5s
    send: 010400400002
       - sensor: 
         register_index: 1
         type: 
         precision:
       - sensor: 
         register_index: 2
         type: 
         precision:
    send: 010400500001
       - sensor: 
         register_index: 1
         type: 
         precision:
 ```

2021-03-04 04:16 UTC, nikito7 commented
```
modbus: 
  uart0:
    interval: 5s
    send_serial: 010400400002
       - sensor: 
         position: 1 // in answer or 2-3 if two bytes...
         type: byte or word...
         precision: <- filter multiply work for this
         name: Voltage
```

For efficiency the loop should be based in request/answer.

Only one device can answer at one time in bus

You can have multiple devices/id's

So some sort of raw stuff is easier

request 010400AA0001 // id 01
decode
request 020400AA0001 // id 02 other device 
decode

2021-03-04 18:01 UTC, abrilevskiy commented
Would it be possible to use this sensor with T67xx CO2 sensors: https://www.mouser.com/pdfDocs/AAS-916-142A-Telaire-T67xx-CO2-Sensor-022719-web.pdf ?

Arduino sketch could looks like:

`int readSensor(){
    Wire.beginTransmission(T6713_Address);
    Wire.write(0x04);
    Wire.write(0x13);
    Wire.write(0x8B);
    Wire.write(0x00);
    Wire.write(0x01);
    Wire.endTransmission();
    delay(2000);
    Wire.requestFrom(T6713_Address, 4); //Request 4 bytes from the sensor
    data[0] = Wire.read();
    data[1] = Wire.read();
    data[2] = Wire.read();
    data[3] = Wire.read();
    Serial.println("FUNCTION CODE >");
    Serial.println(data[0], HEX);
    Serial.println("");
    Serial.println("BYTE COUNT > ");
    Serial.println(data[1], HEX);
    Serial.println("");
    Serial.println("MOST SIGNIFICANT BIT > 0x");
    Serial.println(data[2],HEX);
    Serial.println("");
    Serial.println("LEAST SIGNIFICANT BIT > 0x");
    Serial.println(data[3],HEX);
    ppmValue = (((data[2] & 0x3F ) << 8) | data[3]);
}`

2021-03-04 18:40 UTC, nikito7 commented
Will be possible if done :-)

esphome modbus component looks like that

The hard stuff (for me) is understand config yaml interaction 

---

Writing something like this on config yaml will be cool

```
serial_send: "01/04/007C/0001" 
    sensor:
           ....
    sensor
           .....
```

Separate ID Function Registers Count

Will create too much indent in yaml....

2021-03-04 20:50 UTC, madron commented
> The hard stuff (for me) is understand config yaml interaction

I felt the same at the very beginning with yaml format then I fell in love !  ;-)

> Writing something like this on config yaml will be cool
> 
> ```
> serial_send: "01/04/007C/0001" 
>     sensor:
>            ....
>     sensor:
>            .....
> ```
It's not a valid yaml. As a bare minimum you should write:
```yaml
send_serial: 
  command: "01/04/007C/0001" 
  sensors: 
    - name: ...
      ...
    - name: ...
      ...
```
Keep in mind that we should try to expand the existing modbus module that already supports multiple uarts like this:
```yaml
modbus:
  - uart_id: uart0
    other_uart0_related_configs: ...
  - uart_id: uart1
    other_uart1_related_configs: ...
```
Btw thanks very much for your contributions !

2021-03-04 20:55 UTC, madron commented
> Would it be possible to use this sensor with T67xx CO2 sensors: https://www.mouser.com/pdfDocs/AAS-916-142A-Telaire-T67xx-CO2-Sensor-022719-web.pdf ?

I don't know that sensor but the datasheet states that it supports both i2c and modbus... so maybe it will work...  if this component will be implemented !  ;-)

2021-03-04 21:01 UTC, nikito7 commented
command: "01/04/007C/0001"

You will parse this in your code to adapt to esphome core

Just to make yaml more easy

2021-03-04 21:06 UTC, madron commented
@glmnet
> Adding a generic component like this is not as adding a simple i2c sensor, please mind design effort required in it.
> Please also consider maintaining docs at the same time, it's hard doing it the first time but then helps a lot even on review phase.

You are absolutely right on both points !
When I opened this pull request I just wanted to share a piece of code that was already useful to me but now I think it can be and should be much better than this.
So I'm thinking about dropping this request and start over in docs repository just to discuss the design.
What do you think about it ?  Should I open a pull request in docs repository or is there a better way to discuss the design ?

2021-03-04 21:35 UTC, glmnet commented
The best place will be a discussion in this repo

2021-03-04 21:48 UTC, glmnet commented on esphome/components/modbus_sensor/sensor.py
> +CONFIG_SCHEMA = cv.Schema({
Writes should be handled with actions (like servo.write for example) so “readings” is unnecessary as this will be binary sensors or sensors. What you have at the beginning is ok

An entry in modbus can be used for a reading which can have
Start address 
Update interval 
Function 
Device
And list of sensors

you can have same device and function with different interval of address... why not?
May be sensors could have address too. e.g you might want to skip some address but still do one big read to fill all sensors at once

2021-03-04 22:05 UTC, nikito7 commented on esphome/components/modbus_sensor/sensor.py
> +CONFIG_SCHEMA = cv.Schema({
Update interval should be related to uart.
How avoid collisions if two sensors have diferent interval.
Uart already have some lock bus?

Voltage for exemple 5s
Total Energy 60s.

Uart have queue?

For my device I need, configurable per sensor:
- ID - I can change it with broadcast 00 address
- Function - 04 read - 06 write or other
- Start Register
- Register Count - to retrieve 
- type 16bit etc
- position in data received, if multiple registers in one request
- normal sensor stuff name icon filters

The main anchor is the bus, not the device ID

2021-03-04 22:13 UTC, nikito7 commented on esphome/components/modbus_sensor/sensor.py
> +CONFIG_SCHEMA = cv.Schema({
1F0400010001
This will output all data/time stuff
For exemple I need several sensors to extract: hour minutes seconds year month....

1F04006C0007
Seven sensors Voltage/current
...
For 7 requests, I need 20 sensors entries :-)

We can have thousands xD

There are limits: 255 bytes etc

2021-03-04 22:23 UTC, nikito7 commented
```yaml
send_serial: 
  command: "01/04/007C/0001" 
    registers: 
      - name: ...
        ...
  command: "01/04/0099/0002" 
    registers: 
      - name: ...
        ...
      - name: ...
        ...
  command: "A1/04/0088/0002" 
    registers: 
      - name: ...
        ...
      - name: ...
        ...
```

2021-03-06 14:33 UTC, madron commented
This pull request needs to go back to design phase, so I just opened a a new discussion #1588

2021-03-06 14:33 UTC, closed without merging