Add Heap Sensors - free/max block/fragmentation
OttoWinter/esphomeyaml pull request #1578
Opened 2021-03-03 21:33 UTC by micronen

# What does this implement/fix? 

Heap sensors can be used to detect memory leakage of heap fragmentation which can lead to ESP resets.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuraiton files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [ ] ESP32
- [X] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:
```yaml
# Example config.yaml snippet
sensor:
  - platform: heap
    update_interval: 5s
    free:
      name: Heap Free
    fragmentation:
      name: Heap Fragmentation
    block:
      name: Heap Max Block
```

# Explain your changes

Some network and / or configuration problems leads to heap being very low, and eventually to ESP reset.
This sensor allows online monitoring and logging of the all ESPHome nodes state from home-assistant to  helps debugging the issues leading to heap shortage

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-03-07 00:04 UTC, glmnet commented
Maybe this can be moved to the debug component

2021-03-07 17:28 UTC, micronen commented
Sounds good. It will make the debug a poling sensor. Should it stay in misc, or move to sensors? Any other data should be reported by the new debug sensor? 

As a side note - clang-tidy fails because it uses an old framework, maybe it is time to upgrade it? I don't like using ifndef clang-tidy.

2021-04-22 23:29 UTC, nikito7 commented
Only in logger? No sensors?

2021-04-28 03:31 UTC, micronen commented
@nikito7 It adds sensors to the debug component. 
* Text sensor to show the device information which was reported to the log. 
* Main loop time duration sensor
* Heap free/max block/fragmentation sensors

It was a separate component but merged with the debug component as per @glmnet suggestion.

2021-06-01 19:44 UTC, micronen commented
A note on the last commit - when calling the heap status functions from within loop() the ESP resets every few hours. To prevent this I moved the heap sampling from loop() to update(). The down side is that when the heap fills for a short time, the event might be missed.

2021-06-02 00:12 UTC, glmnet reviewed
Some partial review. Seems ok

2021-06-02 00:12 UTC, glmnet commented on esphome/core/config.py
> +        version = find_item(CORE.raw_config, CONF_ARDUINO_VERSION)
This can find the key in the right place not in any place on the tree

2021-06-02 00:12 UTC, glmnet commented on esphome/components/debug/debug_component.cpp
> +	// calculate loop time - from last call to this one
You can calculate the loop time with a simple subtraction and let overflow do it's thing. 

I recommend you this question - self answered https://arduino.stackexchange.com/questions/12587/how-can-i-handle-the-millis-rollover

2021-06-06 21:37 UTC, micronen commented on esphome/const.py
> +UNIT_MILISECOND = "mSec"
fixed

2021-06-06 21:45 UTC, micronen commented on esphome/const.py
> +DEVICE_CLASS_ESPHOME = "esphome"
Removed DEVICE_CLASS_ESPHOME from the code
Changed to component to use DEVICE_CLASS_EMPTY like in uptime component

2021-06-06 21:48 UTC, micronen commented on esphome/const.py
> +DEVICE_CLASS_MEMORY = "memory"
How do you suggest to call it? 
Why is 'battery: Percentage of battery that is left.' on the list, but 'memory' doesn't fit?

2021-06-06 21:57 UTC, micronen commented on esphome/core/config.py
> +        version = find_item(CORE.raw_config, CONF_ARDUINO_VERSION)
I had problems when the yaml contains packages, and thus added a full tree search,
The CONF_ARDUINO_VERSION might be defined inside a package, and not on the root level.
I use a 'config' package with all the common definitions for my devices.

2021-06-06 22:17 UTC, micronen commented on esphome/components/debug/debug_component.cpp
> +	// calculate loop time - from last call to this one
Removed loopover check

2021-07-05 11:10 UTC, OttoWinter commented on esphome/core/config.py
> +        version = find_item(CORE.raw_config, CONF_ARDUINO_VERSION)
The problem with this validator is that it doesn't work well with substitutions/packages. As of two weeks ago, fortunately there's a clean solution that does exactly this. See `get_arduino_framework_version` in `final_validate.py` (see for example also the usage in `http_request`)

2021-08-20 22:00 UTC, oxan commented on esphome/components/debug/debug_component.cpp
> +  //  device_info += "|Heap " + to_string(this->free_heap_);
```suggestion
```
No commented code, please.

2021-08-20 22:00 UTC, oxan commented on esphome/components/debug/debug_component.cpp
> +  device_info += features.c_str();
```suggestion
  device_info += features;
```

2021-08-20 22:00 UTC, oxan commented on esphome/const.py
> +UNIT_MILISECOND = "ms"
```suggestion
UNIT_MILLISECOND = "ms"
```

2021-08-20 22:00 UTC, oxan commented on esphome/const.py
> +DEVICE_CLASS_MEMORY = "memory"
The problem is that the device classes used by ESPHome have to supported by HA. Thus, we can't just make up our own device class without adding it to HA as well. 

I'd suggest just using the default, empty device class.

2021-08-20 22:00 UTC, oxan commented on esphome/components/debug/__init__.py
> +            UNIT_MILISECOND, ICON_TIMER, 1, DEVICE_CLASS_EMPTY
```suggestion
            UNIT_MILLISECOND, ICON_TIMER, 1, DEVICE_CLASS_EMPTY
```

2021-08-29 19:24 UTC, micronen commented on esphome/const.py
> +DEVICE_CLASS_MEMORY = "memory"
OK, removed the class

2021-08-29 20:23 UTC, micronen commented on esphome/core/config.py
> +        version = find_item(CORE.raw_config, CONF_ARDUINO_VERSION)
OK. Changed to suggested validator

2021-09-11 12:06 UTC, oxan requested changes
Great, just some minor style things remaining:

2021-09-11 12:06 UTC, oxan commented on esphome/components/debug/__init__.py
> +
You already have `cv.only_on_esp8266`, so this isn't necessary.
```suggestion
```

2021-09-11 12:06 UTC, oxan commented on esphome/components/debug/debug_component.cpp
> +  LOG_SENSOR("  ", "Max Block", this->block_sensor_);
Might be nice to give a bit more information about what these sensors are:
```suggestion
  LOG_SENSOR("  ", "Free space on heap", this->free_sensor_);
#ifdef ARDUINO_ARCH_ESP8266
  LOG_SENSOR("  ", "Heap fragmentation", this->fragmentation_sensor_);
  LOG_SENSOR("  ", "Largest free heap block", this->block_sensor_);
```

2021-09-11 12:06 UTC, oxan commented on esphome/components/debug/__init__.py
> +            "please check esphome->arduino_version"
```suggestion
            "This sensor is not supported on Arduino framework versions below 2.5.2, "
            "please change esphome->arduino_version or remove this sensor."
```

2021-09-11 12:06 UTC, oxan commented on esphome/components/debug/debug_component.cpp
> +  // NOTE: Requires arduino_version 2.5.2 or above
With the newly-updated dev branch you merged in, we can actually check the Arduino version now:
```suggestion
#if defined(ARDUINO_ARCH_ESP8266) && ARDUINO_VERSION_CODE >= VERSION_CODE(2, 5, 2)
```

2021-09-11 12:06 UTC, oxan commented on esphome/components/debug/debug_component.h
> +#include "esphome/core/helpers.h"
which requires the `macros.h` header
```suggestion
#include "esphome/core/macros.h"
#include "esphome/core/helpers.h"
```

2021-09-11 12:06 UTC, oxan commented on esphome/components/debug/debug_component.h
> +#ifdef ARDUINO_ARCH_ESP8266
```suggestion
#if defined(ARDUINO_ARCH_ESP8266) && ARDUINO_VERSION_CODE >= VERSION_CODE(2, 5, 2)
```

2021-09-11 12:06 UTC, oxan commented on esphome/components/debug/debug_component.h
> +#ifdef ARDUINO_ARCH_ESP8266
```suggestion
#if defined(ARDUINO_ARCH_ESP8266) && ARDUINO_VERSION_CODE >= VERSION_CODE(2, 5, 2)
```

2022-01-09 19:52 UTC, oxan approved these changes

2022-01-09 19:54 UTC, oxan commented
Sorry, this one got lost between all other PRs. 

I've merged in the current `dev` branch and added support max free block size sensor on ESP32. If CI doesn't come up with any other issues, this can be merged once the documentation is ready.

2022-01-09 23:54 UTC, jesserockz commented on esphome/components/debug/debug_component.cpp
> +  device_info += ESPHOME_VERSION;
Is this necessary? (just adding more bytes to this device text_sensor) We already have a version text_sensor...

2022-01-10 15:31 UTC, micronen commented on esphome/components/debug/debug_component.cpp
> +  device_info += ESPHOME_VERSION;
It is sent one time only. I find it conveniet to have all the information in one place. But you can remove this line in the merge if you think it is redundant.

2022-01-12 01:54 UTC, jesserockz commented on esphome/components/debug/debug_component.cpp
> +  device_info += ESPHOME_VERSION;
Its fine I guess.

2022-01-25 18:18 UTC, merged

2022-01-25 18:18 UTC, oxan commented
Thanks! Sorry this one took so long.