Extend 'uart:' with 'invert:'
OttoWinter/esphomeyaml pull request #1586
Opened 2021-03-05 10:46 UTC by needspeed

# What does this implement/fix? 

This allows to configure the uart data lines to be logically inverted.
Only possible in hardware for ESP32.
ESP8266 does not support inverting in hardware.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

**Related issue or feature (if applicable):** fixes [#1145](https://github.com/esphome/feature-requests/issues/1145)
**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation:** esphome/esphome-docs#1039
  
# Test Environment
- [x] ESP32

## Example entry for `config.yaml`:
```yaml
uart:
  - rx_pin: GPIO21
    baud_rate: 115200
    id: p1_bus    
    invert: true
```

# Explain your changes

Sometimes uart peripherals have inverted logic levels (see linked issue).
This enables us to use those peripherals without hardware changes.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-03-05 13:09 UTC, glmnet requested changes
This could be extended for bit bang serial on the esp8266 however that will need test and if you're not going to do it then this will be accepted ok as is.
Lets just work on the validation of the `invert:` option, thanks

2021-03-05 13:09 UTC, glmnet commented on esphome/components/uart/__init__.py
> +    cv.Optional(CONF_INVERT, default=False): cv.boolean,
make invalid for esp8266, see `cv.only_on_esp32`

2021-03-05 17:31 UTC, needspeed commented
> This could be extended for bit bang serial on the esp8266 however that will need test and if you're not going to do it then this will be accepted ok as is.
> Lets just work on the validation of the `invert:` option, thanks

Added the esp32only flag. I have indeed no esp8266 to test with atm.
Should be indeed easy to add to the softserial in the future in a separate PR.

2021-03-06 00:11 UTC, jesserockz reviewed
Looks good to me.
Maybe wrap the invert cpp code in `#ifdef ARDUINO_ARCH_ESP32` so it doesn't get compiled and use space on esp8266s, which are already strapped for bytes sometimes =)

2021-03-06 00:25 UTC, glmnet commented
> Maybe wrap the invert cpp code in `#ifdef ARDUINO_ARCH_ESP32` so it doesn't get compiled and use space on esp8266s, which are already strapped for bytes sometimes =)

Agree 

I don't know why we don't use private members so they can be maybe optimized

2021-03-06 09:01 UTC, needspeed commented
> > Maybe wrap the invert cpp code in `#ifdef ARDUINO_ARCH_ESP32` so it doesn't get compiled and use space on esp8266s, which are already strapped for bytes sometimes =)
> 
> Agree
> 
> I don't know why we don't use private members so they can be maybe optimized

Afaik class member variables are not optimized out in c++ no matter the visibility (just like struct fields in c).

2021-03-06 09:39 UTC, jesserockz commented on esphome/components/uart/uart_esp32.cpp
> +  this->hw_serial_->begin(this->baud_rate_, get_config(), rx, tx, this->invert_);
You missed adding the #ifdef here with an else to call without the param entirely

2021-03-06 09:52 UTC, needspeed commented on esphome/components/uart/uart_esp32.cpp
> +  this->hw_serial_->begin(this->baud_rate_, get_config(), rx, tx, this->invert_);
Why is uart_esp32.cpp compiled if the target is ESP8266 in the first place?

2021-03-06 09:56 UTC, needspeed commented on esphome/components/uart/uart_esp32.cpp
> +  this->hw_serial_->begin(this->baud_rate_, get_config(), rx, tx, this->invert_);
It's actually not compiled.
There is already an [ifdef](https://github.com/esphome/esphome/blob/58a7376d8a5ac83a3c862e498bc9a661b8ec793d/esphome/components/uart/uart_esp32.cpp#L1).
Thus we don't need another one.

2021-03-06 09:59 UTC, jesserockz commented on esphome/components/uart/uart_esp32.cpp
> +  this->hw_serial_->begin(this->baud_rate_, get_config(), rx, tx, this->invert_);
Sorry I was reviewing on my phone and did not pay attention to it being the esp32 specific file

2021-03-06 10:01 UTC, jesserockz approved these changes

2021-03-06 13:25 UTC, merged