Add monochromatic effects: Pulse, Random
OttoWinter/esphomeyaml pull request #1616
Opened 2021-03-17 12:23 UTC by ferbar

# What does this implement/fix? 

Add monochromatic ligth effects pulse and random, add RGB light effect pulse.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
*missing* will come if there is interest in this patch.
  
# Test Environment

- [ ] ESP32
- [x] ESP8266
- [ ] Windows
- [ ] Mac OS
- [x] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
  - platform: monochromatic
[snip]
    effects:
      - pulse:
          transition_length: 1s
      - random:
```

# Explain your changes

Adding a pulse effect, add random effect to monochromatic light;
Adding the pulse effect to rgb light, too.

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-03-18 07:16 UTC, jesserockz requested changes

2021-03-18 07:16 UTC, jesserockz commented on esphome/components/light/effects.py
> +@register_monochromatic_effect(
`@register_monochromatic_effect` also adds to the RGB registry so you don't need both. Same for pulse

2021-03-18 07:16 UTC, jesserockz commented on esphome/components/light/base_light_effects.h
> +    if (now - this->last_color_change_ < this->transition_length_) {
I think this is supposed to be `update_interval_`
```suggestion
    if (now - this->last_color_change_ < this->update_interval_) {
```

2021-03-20 07:46 UTC, ferbar commented on esphome/components/light/effects.py
> +@register_monochromatic_effect(
Thanks, fixed

2021-03-20 08:05 UTC, ferbar commented on esphome/components/light/base_light_effects.h
> +    if (now - this->last_color_change_ < this->transition_length_) {
Fixed.

2021-03-20 08:32 UTC, jesserockz approved these changes

2021-03-20 08:33 UTC, jesserockz commented
Looking good thanks. Just needs a docs PR please =)

2021-03-20 10:20 UTC, ferbar commented
Added doc PR
Thanks

2021-04-28 03:05 UTC, merged