iBeacon presence support
OttoWinter/esphomeyaml pull request #1627
Opened 2021-03-20 20:46 UTC by ignisf

# What does this implement/fix? 

Quick description 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/1912, fixes https://github.com/esphome/issues/issues/1913

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** **TODO**
  
# Test Environment

- [x] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [x] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esp32_ble_tracker:

binary_sensor:
  - platform: 'ble_presence'
    ibeacon_uuid: 77a6438d-ea95-4522-b46c-cb2b4412076f
    ibeacon_major: 100
    ibeacon_minor: 1
    name: "Jane's Phone"

```

# Explain your changes

Describe your changes here to communicate to the maintainers **why we should accept this pull request**.
Very important to fill if no issue linked

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-03-20 21:48 UTC, ignisf commented on esphome/components/ble_presence/binary_sensor.py
> +            cv.Optional(CONF_IBEACON_UUID): esp32_ble_tracker.ibeacon_uuid,
Could I have a suggestion how to enforce `ibeacon_uuid` is set in case any of `ibeacon_major` and `ibeacon_minor` are set?

2021-03-20 23:07 UTC, ignisf commented on esphome/components/ble_presence/binary_sensor.py
> +            cv.Optional(CONF_IBEACON_UUID): esp32_ble_tracker.ibeacon_uuid,
Of course this is assuming that all those identifiers have a hierarchy... I could change it so either of iBeacon UUID/Major/Minor can be specified to perform iBeacon presence detection to keep it simple.

2021-04-04 10:37 UTC, rdehuyss commented
Would love to have this merged as it currently requires extra work in ESPHome. If I just specify the service_uuid for the binary sensor ble_presence, this does not work.

This is how it should be:
```
    - platform: ble_rssi
      service_uuid: '3e5c314b-17d9-4cad-b0db-052cf2de34ee'
      name: Ronald GSM BLE $devicename_friendly
```

This is how I now do it:
```
esp32_ble_tracker:
  on_ble_advertise:
    - then:
        - lambda: |-
            if(x.get_ibeacon().has_value()) {
              auto ibeacon = x.get_ibeacon().value();
              if(strcmp(ibeacon.get_uuid().to_string().c_str(), "C3:D1:26:E2:7E:B1:43:EF:AE:59:82:48:D5:33:17:1C") == 0) {
                id(my_rssi).publish_state(x.get_rssi());
              }
            }

sensor:
  - platform: template
    id: my_rssi
    name: "$Ronald GSM BLE RSSI $devicename_friendly"
    icon: "mdi:mdi-signal-distance-variant"
    update_interval: never
    unit_of_measurement: "dBm"
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
```

2021-04-06 22:40 UTC, ignisf commented on esphome/components/ble_presence/binary_sensor.py
> +            cv.Optional(CONF_IBEACON_UUID): esp32_ble_tracker.ibeacon_uuid,
I added a `validate` function similar to:
https://github.com/esphome/esphome/blob/808ce6eecba4b086670f87ceb5de1a710a7f4d67/esphome/components/hm3301/sensor.py#L23-L28

2021-04-06 22:46 UTC, ignisf commented
I've enhanced the config validation and have rebased on the latest `dev`.

2021-04-14 12:02 UTC, federicoodorizzi commented
When will this feature be available? Thanks!

2021-04-19 12:07 UTC, marcinbauer85 commented
Any ETA on when this will be live? 🙏

2021-04-28 15:06 UTC, flyize commented
@rdehuyss Until this gets merged, any way you can explain your fix a bit? Your UUID in the first code block doesn't appear to be represented in your second code block.

Am I just being a bit too literal?

2021-04-28 15:30 UTC, alexd321 commented
My semi-working example, using UUID from the App of _'A4:B5:A3:B5:AC:C5:03:EA:F3:2C:9E:36:A6:E6:A2:B6'_ (leave out major and minor parts)

```
esp32_ble_tracker:
  on_ble_advertise: 
    - lambda: |- 
        if(x.get_ibeacon().has_value()) 
          { auto ibeacon = x.get_ibeacon().value(); 
        if(strcmp(ibeacon.get_uuid().to_string().c_str(), "A4:B5:A3:B5:AC:C5:03:EA:F3:2C:9E:36:A6:E6:A2:B6") == 0) 
          { id(ble_rssi).publish_state(x.get_rssi());
          ESP_LOGD("ble_adv", "My Phone found");            
          }

sensor:
  - platform: template 
    id: ble_rssi
    name: "My BLE RSSI" 
    icon: "mdi:signal-distance-variant" 
    update_interval: never 
    unit_of_measurement: "dBm" 
    filters: 
      - median: 
          window_size: 5 
          send_every: 1
#    on_value:
#      - script.stop: start_ble
#      - script.execute: start_ble
```

I haven't been able to get the RSSI to 'expire' reliably, even when using a script

```
binary_sensor:
  - platform: template
    id: my_ble_presence
    name: My BLE Presence
    device_class: occupancy
    lambda: |-
      if (id(ble_rssi).state > -90) {
        // BLE Present.
        return true;
      } else {
        // BLE Absent.
        return false;
      }


script:
  - id: start_ble
    mode: restart
    then:
      - logger.log: "starting iBeacon presence script"
      - delay: 30s
      - logger.log: "Resetting iBeacon presence"
      - binary_sensor.template.publish:
           id: ble_presence
           state: OFF
      - sensor.template.publish:
         id: ble_rssi
         state: NaN
```

2021-05-11 00:22 UTC, jesserockz requested changes

2021-05-11 00:22 UTC, jesserockz commented on esphome/components/esp32_ble_tracker/__init__.py
> +    raise cv.Invalid("iBeacon UUID must be in '{}' format".format(ibeacon_uuid_format))
Could you not just use `cv.uuid` instead of writing this?

2021-05-11 00:22 UTC, jesserockz commented on esphome/components/ble_presence/binary_sensor.py
> +            cv.Optional(CONF_IBEACON_UUID): esp32_ble_tracker.ibeacon_uuid,
```suggestion
            cv.Optional(CONF_IBEACON_UUID): cv.uuid,
```

2021-05-11 00:22 UTC, jesserockz commented on esphome/components/ble_presence/binary_sensor.py
> +def validate(config):
Please rename this function to be specific.

This is mainly because there is an upcoming change that specifically looks for `validate` functions in components

2021-07-04 18:21 UTC, federicoodorizzi commented
Has this been implemented?

2021-07-10 01:03 UTC, alexd321 commented on esphome/components/ble_presence/ble_presence_device.h
>    void on_scan_end() override {
I'm fairly new to this, so sorry I am wrong. I've been testing this PR, I think this would mean state returns to false at the end of _scan_parameterrs: duration_, correct?
would the be any benefit to having a custom configurable "off time"? or making the duration clear in the docs?

2021-07-10 20:00 UTC, ignisf commented
Hello @jesserockz and thank you for the review. I did not expect this PR to be so popular. I've addressed your feedback and am currently waiting for CI and testing the changes on a device.

2021-07-10 20:09 UTC, ignisf commented on esphome/components/ble_presence/ble_presence_device.h
>    void on_scan_end() override {
> this would mean state returns to false at the end of scan_parameters: duration, correct?

This is my understanding as well.

> would the be any benefit to having a custom configurable "off time"

Well... The off time is already configurable by setting `scan_parameters.duration`?

> or making the duration clear in the docs?

I support this, we need confirmation from someone with more experience with `esp32_ble_tracker` to weigh in though.

2021-08-05 18:12 UTC, maxiangelo commented
Great work, this is really needed to get rid of unneeded apps beside the companion app!

2021-09-01 23:42 UTC, jesserockz approved these changes

2021-09-01 23:46 UTC, jesserockz commented
Sorry for the delay :rocket:

2021-09-01 23:46 UTC, merged