add xiaomi mccgq02hl
OttoWinter/esphomeyaml pull request #1645
Opened 2021-03-27 15:58 UTC by morph027

# What does this implement/fix? 

Add support for Xiaomi MCCGQ02HL based on @kar-vin-nen work in https://github.com/esphome/feature-requests/issues/978

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/978

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [x] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:

```yaml
binary_sensor:
  - platform: xiaomi_mccgq02hl
    name: door sensor
    mac_address: MA:C_:AD:DR:ES:S1
    bindkey: "bind_key"
    battery_level:
      name: "Door sensor battery level"
    light:
      name: "Door sensor light"
    opening:
      name: "Door sensor open"
```

# Explain your changes

Port of feature request to pull request.

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-03-28 11:30 UTC, morph027 commented
Working sensors within my Homeassistant:

![Screenshot from 2021-03-28 13-30-19](https://user-images.githubusercontent.com/600106/112750611-cae2ed00-8fc9-11eb-9307-7b7459d7e95e.png)

![Screenshot from 2021-03-28 13-30-05](https://user-images.githubusercontent.com/600106/112750613-cae2ed00-8fc9-11eb-8b66-a28227033085.png)

2021-04-02 15:44 UTC, shohart commented
WTF guys just merge that stuff, it works!

2021-04-06 12:50 UTC, OttoWinter commented on esphome/components/xiaomi_mccgq02hl/binary_sensor.py
> +                        CONF_DEVICE_CLASS, default="light"
Please declare this constant as `DEVICE_CLASS_LIGHT` in `binary_sensor/__init__.py`. I see some other xiaomi device also uses literals instead of constants, but that is not correct.

2021-04-06 12:52 UTC, OttoWinter commented on esphome/components/xiaomi_mccgq02hl/binary_sensor.py
> +            cv.Optional(CONF_LIGHT): binary_sensor.BINARY_SENSOR_SCHEMA.extend(
So about the naming of these options. Can we rename this to `has_light` or something like that? That would make more clear that this is a binary sensor (and not for example a light entity like an neopixel _light_).

Same for opening: -> `is_open` (I'm guessing the sensor reads if something _is_ open, not whether it's in the _process_ of opening?)

2021-04-06 12:53 UTC, OttoWinter reviewed
Thanks! Code looks good to me, just some minor things about how the config options should be named.

2021-04-06 13:35 UTC, morph027 commented
Thanks for the review, i'v adjusted the code. Seems i'm stumbling over sorting issue of constants which are in wrong order even without my changes. Any clue how to automatically order them without doing by hand?

2021-04-24 22:27 UTC, maciak commented
Hi, Is there still any hope for this?

2021-09-22 10:38 UTC, oxan requested changes

2021-09-22 10:38 UTC, oxan commented on esphome/components/xiaomi_mccgq02hl/binary_sensor.py
> +                    cv.Optional(DEVICE_CLASS_LIGHT): binary_sensor.device_class,
The aim here was to use a constant for the default value, not to change the configuration option's name.
```suggestion
                    cv.Optional(CONF_DEVICE_CLASS, default=DEVICE_CLASS_LIGHT): binary_sensor.device_class,
```

2021-09-22 10:38 UTC, oxan commented on esphome/components/xiaomi_mccgq02hl/binary_sensor.py
> +                        CONF_DEVICE_CLASS, default="opening"
Same here.
```suggestion
                        CONF_DEVICE_CLASS, default=DEVICE_CLASS_OPENING
```

2021-10-14 04:46 UTC, reno-pensando commented
any chance this pr will be merged? thx

2021-10-14 08:41 UTC, oxan commented
> any chance this pr will be merged? thx

Someone needs to fix my review comments & test whether it still works.

2022-01-13 07:57 UTC, morph027 commented
Uh, forgot about this. Will try to fix the comments.

2022-01-13 17:51 UTC, ahpohl commented on esphome/components/xiaomi_mccgq02hl/binary_sensor.py
> +    DEVICE_CLASS_LIGHT,
It fails to compile if not at least the device class opening is imported. The others for consistency with other Xiaomi sensors sending a battery status.

```suggestion
    DEVICE_CLASS_LIGHT,
    DEVICE_CLASS_OPENING,
    STATE_CLASS_MEASUREMENT,
    ENTITY_CATEGORY_DIAGNOSTIC
```

2022-01-13 17:54 UTC, ahpohl commented on esphome/components/xiaomi_mccgq02hl/binary_sensor.py
> +            cv.Optional(CONF_BATTERY_LEVEL): sensor.sensor_schema(
For constency with other Xiaomi sensors sending a battery status:
```suggestion
            cv.Optional(CONF_BATTERY_LEVEL): sensor.sensor_schema(
                unit_of_measurement=UNIT_PERCENT,
                accuracy_decimals=0,
                device_class=DEVICE_CLASS_BATTERY,
                state_class=STATE_CLASS_MEASUREMENT,
                entity_category=ENTITY_CATEGORY_DIAGNOSTIC
            ),
```

2022-04-22 19:42 UTC, cdu913 commented
Sorry, i am not really experienced with the process here. What is the next step on this integration ? Does the current state means that it will be given up ?

2025-11-05 00:50 UTC, closed without merging