Support direct relay state feedback for tuya climate component
OttoWinter/esphomeyaml pull request #1668
Opened 2021-04-06 10:09 UTC by kroimon

# What does this implement/fix? 

**This PR is based on #1491 which should be merged first, so currently marked as a draft.**

Most available tuya thermostats do not report back the current state of the output relays via the serial protocol.
The currently already implemented workaround is to calculate the active state from the current and target temperatures and a guessed hysteresis.

This adds support to directly monitor the state of the output relays. For most thermostats, this will require a minor hardware hack, but as soldering is required anyhow to flash those devices, this is something most users can quickly implement.
For a description of the required modification, see https://github.com/klausahrenberg/WThermostatBeca/issues/17.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** WIP 
  
# Test Environment

- [ ] ESP32
- [X] ESP8266
- [ ] Windows
- [ ] Mac OS
- [X] Linux (Home Assistant Addon)

## Example entry for `config.yaml`:
```yaml
climate:
  - platform: tuya
    name: "Thermostat"
    switch_datapoint: 1
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    temperature_multiplier: 0.5
    heating_state_pin: GPIO5
    cooling_state_pin: GPIOx
```

# Explain your changes

See above.

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-06-02 13:51 UTC, kroimon commented
Rebased onto latest dev.
Documentation is still missing.

2021-06-03 12:08 UTC, kroimon commented
Added documentation in esphome/esphome-docs#1215.

2021-08-20 19:06 UTC, oxan requested changes
Hi, thanks for your contribution! Sorry it took so long!

2021-08-20 19:06 UTC, oxan commented on esphome/components/tuya/climate/__init__.py
> +            cg.add(var.set_cooling_state_pin(cooling_state_pin))
If `CONF_HEATING_STATE_PIN` and `CONF_COOLING_STATE_PIN` can only be used when there's no `CONF_ACTIVE_STATE_DATAPOINT`, that should be enforced by the config validation using `cv.Exclusive`.

2021-08-20 19:06 UTC, oxan commented on esphome/components/tuya/climate/__init__.py
> +            )
If `CONF_ACTIVE_STATE_HEATING_VALUE` and `CONF_ACTIVE_STATE_COOLING_VALUE` can only be used when `CONF_ACTIVE_STATE_DATAPOINT` is set, that should be enforced by the config validation.

2021-08-31 21:59 UTC, kroimon commented on esphome/components/tuya/climate/__init__.py
> +            cg.add(var.set_cooling_state_pin(cooling_state_pin))
I think I can't just mark those three as `cv.Exclusive` as this would also prevent `CONF_HEATING_STATE_PIN` and `CONF_COOLING_STATE_PIN` to be used at the same time, correct?
I will add a custom validation function for that.

2021-08-31 22:00 UTC, kroimon commented on esphome/components/tuya/climate/__init__.py
> +            )
Although this was present before, I will add a check for this, too.

2021-09-15 07:22 UTC, kroimon commented
@oxan I added the configuration checks you suggested, can you have another look, please?

2021-09-15 08:10 UTC, jesserockz commented on esphome/components/tuya/climate/tuya_climate.cpp
> +    LOG_PIN("  Cooling State Pin: ", this->cooling_state_pin_);
The nullptr check is not needed as the macro has one already
```suggestion
  LOG_PIN("  Heating State Pin: ", this->heating_state_pin_);
  LOG_PIN("  Cooling State Pin: ", this->cooling_state_pin_);
```

2021-09-15 08:14 UTC, jesserockz approved these changes

2021-09-15 08:23 UTC, merged