Bme680 sec sample rate
OttoWinter/esphomeyaml pull request #1688
Opened 2021-04-12 17:43 UTC by SenexCrenshaw

# What does this implement/fix? 
Moved sample_rate from the parent config to per sensor
Fixed USE name - This was causing warnings in the build log
Added tests

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Configuration change (this will require users to update their yaml configuration files to keep working)
  
# Test Environment

- [X] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:

```yaml
- platform: bme680_bsec
    temperature:
      id: bme680_temp
      sample_rate: LP
    humidity:
      id: bme680_humidity
      sample_rate: LP
    pressure:
      id: bme680_pressure
      sample_rate: LP
    gas_resistance:
      id: bme680_gas_resistance
      sample_rate: ULP
    iaq:
      id: bme680_iaq
      sample_rate: ULP
    co2_equivalent:
      id: bme680_co2_equivalent
      sample_rate: ULP
    breath_voc_equivalent:
      id: bme680_breath_voc_equivalent
      sample_rate: ULP
```

# Explain your changes
Currently only one sample rate is used. This PR allows each sensor to have its own allowing for each to have its own update interval. sample_rate has been removed from the parent component which is a breaking change.

Tests have been added as well.

The docs have not be updated nor have they been merged ( i believe ) so maybe @trvrnrth can update them to match.

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-04-12 19:33 UTC, trvrnrth commented on tests/test2.yaml
> +bme680_bsec:
I'm afraid because of the licensing restrictions adding this to the tests is a no-go. https://github.com/esphome/esphome/pull/1313#discussion_r606678773

2021-04-12 19:46 UTC, SenexCrenshaw commented on tests/test2.yaml
> +bme680_bsec:
Makes sense. I will remove the tests.

2021-04-12 19:51 UTC, trvrnrth commented on esphome/components/bme680_bsec/bme680_bsec.cpp
> +    ESP_LOGD(TAG, "co2_equivalent_sensor_ %f %f", sample_rate, co2_equivalent_sensor_sample_rate_);
Probably don't really need these logs as all the info is in the config dump.

2021-04-12 19:51 UTC, SenexCrenshaw commented on esphome/components/bme680_bsec/bme680_bsec.cpp
> +    ESP_LOGD(TAG, "co2_equivalent_sensor_ %f %f", sample_rate, co2_equivalent_sensor_sample_rate_);
hmm. left over debug

2021-04-12 19:54 UTC, trvrnrth commented on esphome/components/bme680_bsec/bme680_bsec.h
> +  void set_temperature_sensor(sensor::Sensor *temperature_sensor, esphome::bme680_bsec::SampleRate sample_rate) {
I don't think there's any benefit to having the entire namespace here. Just `SampleRate` would suffice?

2021-04-12 19:57 UTC, trvrnrth commented on esphome/components/bme680_bsec/bme680_bsec.h
> +  float temperature_sensor_sample_rate_{SAMPLE_RATE_LP};
This should be `BSEC_SAMPLE_RATE_LP` or  `BSEC_SAMPLE_RATE_ULP` to init to the correct float value.

2021-04-12 19:58 UTC, SenexCrenshaw commented on esphome/components/bme680_bsec/bme680_bsec.h
> +  float temperature_sensor_sample_rate_{SAMPLE_RATE_LP};
ill fix those up

2021-04-12 20:06 UTC, trvrnrth commented
This looks pretty sane to me and I don't think the BC break is too big a deal. The alternative would be to have a default at platform level and overrides at sensor level but that's not quite as clear so I think on balance this is probably better.

The docs are merged into the `next` docs branch from https://github.com/esphome/esphome-docs/pull/793 if you're able to update them too.

It's a shame the tests can't be included but alas that can't be helped.

One testing question I have as I've not yet taken it for a spin on my dev board is do things behave if the IAQ rate is LP but the gas resistance rate is ULP? I'm not sure how the library will handle the heater operation in that setup.

Thanks for taking the time to put this together. It has been on my todo list for a while now!

2021-04-12 20:07 UTC, trvrnrth commented on esphome/components/bme680_bsec/bme680_bsec.h
> +  float temperature_sensor_sample_rate_{SAMPLE_RATE_LP};
Leaving out the init altogether is probably clearer 👍

2021-04-12 20:11 UTC, trvrnrth commented on esphome/components/bme680_bsec/bme680_bsec.cpp
> +    virtual_sensors[num_virtual_sensors].sample_rate = iaq_sensor_sample_rate_;
This may be personal preference but I would prefix these with `this->iaq_sensor_sample_rate_` to make it clear that we're using an object member here. From what I've seen that does seem to be the general convention elsewhere in the project too.

2021-04-12 20:13 UTC, trvrnrth commented on esphome/components/bme680_bsec/bme680_bsec.cpp
> +  ESP_LOGCONFIG(TAG, "    Sample Rate: %s", this->temperature_sensor_sample_rate_ == SAMPLE_RATE_ULP ? "ULP" : "LP");
This should be checking against `BSEC_SAMPLE_RATE_ULP`

2021-04-12 20:17 UTC, trvrnrth commented on esphome/components/bme680_bsec/bme680_bsec.h
> +  float temperature_sensor_sample_rate_{SAMPLE_RATE_LP};
Having these as floats will probably use a few extra bytes each but it's probably not worth worrying about if it makes things simpler later.

2021-04-12 21:08 UTC, SenexCrenshaw commented on esphome/components/bme680_bsec/bme680_bsec.h
> +  void set_temperature_sensor(sensor::Sensor *temperature_sensor, esphome::bme680_bsec::SampleRate sample_rate) {
Im verbose sometimes. I cleaned it up

2021-04-12 21:10 UTC, SenexCrenshaw commented on esphome/components/bme680_bsec/bme680_bsec.h
> +  float temperature_sensor_sample_rate_{SAMPLE_RATE_LP};
BSEC_SAMPLE_RATE_ULP and BSEC_SAMPLE_RATE_LP are floats.

2021-04-12 21:12 UTC, SenexCrenshaw commented on esphome/components/bme680_bsec/bme680_bsec.cpp
> +    virtual_sensors[num_virtual_sensors].sample_rate = iaq_sensor_sample_rate_;
agreed

2021-04-12 21:13 UTC, SenexCrenshaw commented on esphome/components/bme680_bsec/bme680_bsec.cpp
> +  ESP_LOGCONFIG(TAG, "    Sample Rate: %s", this->temperature_sensor_sample_rate_ == SAMPLE_RATE_ULP ? "ULP" : "LP");
Fixed

2021-04-12 21:27 UTC, trvrnrth commented on esphome/components/bme680_bsec/bme680_bsec.h
> +  float temperature_sensor_sample_rate_{SAMPLE_RATE_LP};
What I meant was if the object members were defined as `SampleRate` as the previous single member was then there's the possibility they could be stored in a single byte. Although doing a bit of reading it may have been using an int previously anyway in which case there's no difference. And given the fairly hefty memory requirements of the library anyway pretty irrelevant really anyway.

2021-04-12 21:32 UTC, SenexCrenshaw commented
Added in docs
https://github.com/esphome/esphome-docs/pull/1099

2021-04-12 21:45 UTC, trvrnrth commented on esphome/components/bme680_bsec/bme680_bsec.cpp
>      this->update_subscription_(BSEC_SAMPLE_RATE_LP);
There's no need for the `sample_rate` arg on this method anymore as it's not being used. There can then be a single call with no args outside of this if/else.

2021-04-14 18:47 UTC, trvrnrth commented on esphome/components/bme680_bsec/bme680_bsec.cpp
> +    virtual_sensors[num_virtual_sensors].sample_rate = iaq_sensor_sample_rate_;
Doesn't look like you changed these?

2021-04-14 18:48 UTC, trvrnrth commented on tests/test2.yaml
> +bme680_bsec:
Still got the platform in the tests...

2021-04-14 18:49 UTC, trvrnrth requested changes
Just the tests to remove and `this` to add now I think.

2021-04-14 19:07 UTC, trvrnrth commented
> One testing question I have as I've not yet taken it for a spin on my dev board is do things behave if the IAQ rate is LP but the gas resistance rate is ULP? I'm not sure how the library will handle the heater operation in that setup.

Just tested this and the BSEC library errors out with `BSEC_E_SU_MULTGASSAMPLINTVL` ([docs](https://github.com/BoschSensortec/BSEC-Arduino-library/blob/7a9357566c75048331c15b55a4eb20f1de14f36e/src/inc/bsec_datatypes.h#L306)) so it would be good to guard against that in the config validation as it's not very clear unless you know what's going on what the problem is.

2021-04-14 19:39 UTC, trvrnrth commented
> > One testing question I have as I've not yet taken it for a spin on my dev board is do things behave if the IAQ rate is LP but the gas resistance rate is ULP? I'm not sure how the library will handle the heater operation in that setup.
> 
> Just tested this and the BSEC library errors out with `BSEC_E_SU_MULTGASSAMPLINTVL` ([docs](https://github.com/BoschSensortec/BSEC-Arduino-library/blob/7a9357566c75048331c15b55a4eb20f1de14f36e/src/inc/bsec_datatypes.h#L306)) so it would be good to guard against that in the config validation as it's not very clear unless you know what's going on what the problem is.

One way around this would be to simplify and just have a separate `gas_sample_rate` config at root level. That would maintain backwards compatibility but does sacfrifice a bit of flexibility in terms of not being able to set differing sample rates for the non-gas sensors which I guess some people might want?

To retain maximum flexibility as you have here we'd need to add an extra bit of custom config validation to ensure that the sample rate matches for all gas-related sensors:
- iaq
- gas_resistance
- co2_equivalent
- breath_voc_equivalent

2021-04-14 19:39 UTC, trvrnrth commented on esphome/components/bme680_bsec/bme680_bsec.cpp
> +  if (this->iaq_sensor_sample_rate_ == SAMPLE_RATE_ULP) {
```suggestion
  if (this->iaq_sensor_sample_rate_ == BSEC_SAMPLE_RATE_ULP) {
```

2021-04-15 10:06 UTC, SenexCrenshaw commented on esphome/components/bme680_bsec/bme680_bsec.cpp
> +  if (this->iaq_sensor_sample_rate_ == SAMPLE_RATE_ULP) {
I will address this line and work out a cv check for the sample rate.

2021-04-16 08:24 UTC, trvrnrth commented
You've got a mismatch between this and the docs at the moment. The changes here put the gas sample rate config at root sensor level, whereas the docs note it as being at root platform level.

But I think you're on to something with the general plan. Maybe the original platform level `sample_rate` could be left as-was and used for the main BSEC config and gas-dependent sensor sample rate. The temperature, pressure and humidity sensors would then use whatever this was set to by default, but could optionally be overridden to a per-sensor value if specified in the config.

That would:
- maintain backwards compat
- allow a single point of config for anyone who wants the simplest setup
- allow maximum control for anyone wanting it
- ensure all gas sensors have a matching rate as required

2021-04-21 18:49 UTC, trvrnrth commented
I've taken this and run with it in #1710 which also resolves an input timestamp issue causing the heat compensation not to work properly.

2021-07-10 21:27 UTC, SenexCrenshaw commented
Closing, RE #1710

2021-07-10 21:27 UTC, closed without merging