Add sm2135 component
OttoWinter/esphomeyaml pull request #1736
Opened 2021-05-02 20:35 UTC by BoukeHaarsma23

# What does this implement/fix? 

This implements a SM2135 component. I found the code on @NURDspace repo. However, apparently he does not found the time to create a PR. That's why I'm creating this one. I removed some unused includes and this has been running for almost half a year for me.

I would like to take this opportunity to return something for the community here. So please let me know if something needs to be improved 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/443

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [ ] ESP32
- [x] ESP8266
- [ ] Windows
- [ ] Mac OS
- [x] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
output:
  - platform: sm2135
    id: output_red
    channel: 0
  - platform: sm2135
    id: output_green
    channel: 1
    max_power: 0.46
  - platform: sm2135
    id: output_blue
    channel: 2
    max_power: 0.3
  - platform: sm2135
    id: output_white
    channel: 3
    max_power: 0.8
  - platform: sm2135
    id: output_warmwhite
    channel: 4
    max_power: 0.8
```

# Explain your changes

Implements a SM2135 support. Has been working fine for me with the color_interlock feature.

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-05-05 18:53 UTC, jesserockz requested changes
A few things below

2021-05-05 18:53 UTC, jesserockz commented on esphome/components/sm2135/__init__.py
> +AUTO_LOAD = ["output"]
Please add yourself as a Codeowner and run `script/build_codeowners.py`

```suggestion
AUTO_LOAD = ["output"]
CODEOWNERS = ["@BoukeHaarsma23"]

```

2021-05-05 18:53 UTC, jesserockz commented on esphome/components/sm2135/sm2135.cpp
> +  ESP_LOGCONFIG(TAG, "  Total number of channels: 5");
Static value here?

2021-05-05 18:53 UTC, jesserockz commented on esphome/components/sm2135/sm2135.h
> +  uint8_t num_channels_;
`num_channels_` does not seem to be actually used anywhere?

2021-05-05 18:53 UTC, jesserockz commented on tests/test3.yaml
> +
Please also add some test lines for the `output`

2021-05-05 19:21 UTC, BoukeHaarsma23 commented on esphome/components/sm2135/sm2135.cpp
> +  ESP_LOGCONFIG(TAG, "  Total number of channels: 5");
Yes, the SM2135 always has 5 channels as I am aware of

2021-05-05 19:31 UTC, BoukeHaarsma23 commented on esphome/components/sm2135/sm2135.h
> +  uint8_t num_channels_;
Indeed, will remove!

2021-05-05 19:36 UTC, BoukeHaarsma23 commented on tests/test3.yaml
> +
Done!

2021-05-06 01:36 UTC, jesserockz approved these changes

2021-05-06 17:38 UTC, glmnet commented on esphome/components/sm2135/sm2135.cpp
> +  ESP_LOGCONFIG(TAG, "  Total number of channels: 5");
Then this is no a configuration option, hence no point in printing it out?

2021-05-06 17:47 UTC, BoukeHaarsma23 commented on esphome/components/sm2135/sm2135.cpp
> +  ESP_LOGCONFIG(TAG, "  Total number of channels: 5");
Yeah that makes sense. I have removed the line.

2021-05-12 19:14 UTC, merged