Modbus controller
OttoWinter/esphomeyaml pull request #1779
Opened 2021-05-13 18:53 UTC by martgras

# What does this implement/fix? 

Implements a generic modbus controller to control modbus slaves. 
This PR replaces  #1256 with a generic implementation that isn't limit to EPEVER. 
#1256 required modifications to the exiting 'modbus' component while this version only needs UART.  The modbus specifics are included in the code. The existing 'modbus' component is limited  to input registers and adding support to write data to the slave required a fair amount of changes.   

The implementation has been tested with a couple of modbus slaves including EPEVER Solar Charger, Heidelberg Wallbox (implemented by @derwolff)  , PZEM-017.   The example folder contains these definitions. 

@nikito7 implemented support for the EDP BOX that seems to be popular in Portugal (see https://github.com/nikito7/edp_box_modbus/blob/dev/esphome/edpbox1.yaml  ) 

Sensors, Binary Sensors, Text Sensors and Switches are implemented. 
Writing non boolean data to the slave can be done from a lambda see the epever.yaml  for an example.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [x] ESP32
- [x] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: solarstation
  platform: ESP32
  board: esp32dev

substitutions:
  updates: 30s

wifi:
  ssid: !secret wifi_sid
  password: !secret wifi_password
  reboot_timeout: 5min

time:
  - platform: sntp
    id: sntp_time
    timezone: "CET-1CEST,M3.5.0,M10.5.0/3"
    servers: pool.ntp.org

uart:
  id: mod_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 115200
  stop_bits: 1

modbus_controller:
  uart_id: mod_bus
  # ctrl_pin: 5    # if you need to set the driver enable (DE) pin high before transmitting data configure it here
  command_throttle: 0ms
  id: traceranx
  ## the Modbus device addr
  address: 0x1
  update_interval: 30s

text_sensor:
  - platform: modbus_controller
    name: "rtc clock test 2"
    id: rtc_clock_test2
    internal: true
    modbus_functioncode: read_holding_registers
    address: 0x9013
    offset: 0
    register_count: 3
    hex_encode: true
    response_size: 6

switch:
  - platform: modbus_controller
    modbus_controller_id: traceranx
    id: reset_to_fabric_default
    name: "Reset to Factory Default"
    modbus_functioncode: write_single_coil
    address: 0x15
    bitmask: 1

sensor:
  - platform: modbus_controller
    modbus_controller_id: traceranx
    id: array_rated_current
    name: "array_rated_current"
    address: 0x3000
    offset: 2
    unit_of_measurement: "V"
    modbus_functioncode: "read_input_registers"
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: traceranx
    id: manual_control_load
    modbus_functioncode: read_coils
    address: 2
    offset: 0
    name: "manual control the load"
    bitmask: 1

```

# Explain your changes

There are a couple of feature requests for general modbus support. e.g. https://github.com/esphome/feature-requests/issues/952 
https://github.com/esphome/feature-requests/issues/670

This is a new implementation allows a declarative implementation for modbus slaves using RTU. Actually support the PZEM-0xx devices that use modbus can be implemented without writing more code

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).
Working on it : https://github.com/martgras/esphome-docs . 
The readme.md file also contains an overview how to use this component

2021-05-13 19:17 UTC, nikito7 requested changes
Run ```script/build_codeowners.py```

2021-05-13 20:53 UTC, nikito7 approved these changes

2021-05-13 20:57 UTC, nikito7 requested changes
```js
[hex_encode] is an invalid option for [text_sensor.modbus_controller]. Did you mean [raw_encode]?
  hex_encode: True [source tests/test4.yaml:193]
```

2021-05-13 23:31 UTC, nikito7 approved these changes

2021-05-14 11:57 UTC, nikito7 commented
@glmnet can you check this? Regards

2021-05-14 19:22 UTC, nikito7 approved these changes

2021-08-09 07:18 UTC, syssi commented on esphome/components/modbus_controller/modbuscontroller.cpp
> +  ESP_LOGCONFIG(TAG, "EPSOLAR:");
```suggestion
  ESP_LOGCONFIG(TAG, "ModbusController:");
```

2021-08-09 07:23 UTC, syssi commented on esphome/components/modbus_controller/modbuscontroller.h
> +  WRITE_SINGLE_REGISTER = 0x6,
```suggestion
  WRITE_SINGLE_REGISTER = 0x06,
```

2021-08-09 07:23 UTC, syssi commented on esphome/components/modbus_controller/modbuscontroller.h
> +  READ_EXCEPTION_STATUS = 0x7,   // not implemented
```suggestion
  READ_EXCEPTION_STATUS = 0x07,   // not implemented
```

2021-08-09 07:23 UTC, syssi commented on esphome/components/modbus_controller/modbuscontroller.h
> +  DIAGNOSTICS = 0x8,             // not implemented
```suggestion
  DIAGNOSTICS = 0x08,             // not implemented
```

2021-08-09 07:28 UTC, syssi commented on esphome/components/modbus_controller/modbuscontroller.cpp
> +#include "modbuscontroller.h"
Did you choose the filename by intention? I would expect `modbus_controller.{cpp,h}` here.

2021-08-10 07:53 UTC, OttoWinter reviewed
Could you elaborate why this can't be put into the existing modbus integration?

I really don't think we should have two integrations implementing the same thing, as that just gets super confusing for users and developers.

The existing `modbus` is only used in a couple integrations anyway, if we need to change the base design we can do that.

2021-08-10 07:53 UTC, OttoWinter commented on esphome/components/modbus_controller/examples/test.yaml
> +esphome:
We should not commit these examples, they're huge files that can become outdated quickly

2021-08-10 07:53 UTC, OttoWinter commented on esphome/components/modbus_controller/__init__.py
> +            cv.Optional("sensors"): cv.All(
Use constant names here like `CONF_SENSORS` - if they're not in const.py you can define them in this module.

2021-08-10 07:53 UTC, OttoWinter commented on esphome/components/modbus_controller/__init__.py
> +        conf = config["binary_sensors"]
What is the difference between this and the `binary_sensor` platform you have defined?

2021-08-10 07:53 UTC, OttoWinter commented on esphome/components/modbus_controller/modbusbase.cpp
> +#define DUMP_LOG() \
We have the `hexencode` helper method for this

2021-08-10 07:53 UTC, OttoWinter commented on esphome/components/modbus_controller/modbusbase.h
> +    static GPIOPin PIN(ctrl_pin, OUTPUT);
No, this should be passed in as a GPIOPin directly, see for example `switch.gpio` platform

2021-08-10 07:53 UTC, OttoWinter commented on esphome/components/modbus_controller/readme.md
> +## A fork of [esphome](https://github.com/esphome/esphome) adding support for monitoring a modbus device
Stale comment, and we document in the docs repo, not here.

2021-08-10 07:53 UTC, OttoWinter commented on esphome/components/modbus_controller/modbuscontroller.h
> +  static std::atomic_bool sending_;  // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
ESPHome is single-threaded, so atomics are unneeded (plus bools are atomic on pretty much all architectures anyway for the way it is used here)

2021-08-11 15:34 UTC, martgras commented on esphome/components/modbus_controller/__init__.py
> +        conf = config["binary_sensors"]
Kind of historic  :) 
The code started with hardcoded registers for an epever device and then I was convinced to turn it into a more generic component.  

There are 2 different ways to define a sensor. Either inline like here (this was the original approach I started with) 

````yaml
modbus_controller:
  - id: modbus_controller_test
    address: 0x2
    modbus_id: mod_bus1
    sensors:
      - id: battery_voltage
        name: "Battery voltage"
        address: 0x331A
        offset: 0
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
      - id: battery_current
        name: "Battery current"
        address: 0x331B
        offset: 2
        modbus_functioncode: "read_input_registers"
        value_type: U_WORD
````
or using the "traditional" way 

````yaml
switch:
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_test
    id: reset_to_fabric_default
    name: "Reset to Factory Default"
    address: 0x9008
    modbus_functioncode: write_single_coil
````

Both variants generate the same C++ Code . In my opinion the first variant is easier to write if you have a lot registers.
Especially when more than one register is read in single command.  The code detects that there are 2 consecutive addresses and sends a read multiple register command instead 2 read single register commands

2021-08-11 15:37 UTC, martgras commented on esphome/components/modbus_controller/modbuscontroller.h
> +  static std::atomic_bool sending_;  // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
Thanks for the review.   My main motivation  for not using the existing component was making it easier to use the component without having to change the existing one.   My approach here didn't work for more than one modbus device on a single bus and therefore I have kept working on an improved version.   
It's now in a new branch at https://github.com/martgras/esphome/tree/multidev

@syssi  and your suggestions are implemented in that branch . Examples and readme's removed but instead I modified the original modbus component to handle writes and not only reads.  

Not sure how to proceed. Should I create a new PR or merge everything from my mutidev branch into the one used for this PR

2021-08-12 12:27 UTC, martgras commented on esphome/components/modbus_controller/examples/test.yaml
> +esphome:
reverted to use modbus

2021-08-25 14:30 UTC, hnykda commented
Just curious - is there anything a random esphome user who wants this can help to get this merged? :eyes:

2021-08-29 05:34 UTC, clomads commented
Seconding as a random ESPHome user who's looking forward to this for use with an EPEVER Tracer. Anything I can do to help?

2021-08-31 02:39 UTC, jesserockz commented on esphome/components/modbus_controller/__init__.py
> +        conf = config["binary_sensors"]
I don't think there should be multiple places to define `sensors` etc. I would prefer for the config to be the traditional ESPHome way (second option above only) with the code in subfolders and less `AUTO_LOAD`ing in the main file which will allow for cutting down on binary size, as right now just including the modbus controller will include all of the sensor, binary, text, switch code in various places.

2021-08-31 06:21 UTC, jesserockz commented
@martgras Please take a look at https://github.com/martgras/esphome/pull/29

2021-09-20 13:45 UTC, martgras commented on esphome/components/modbus_controller/__init__.py
> +        conf = config["binary_sensors"]
changed as proposed.

2021-09-21 19:53 UTC, jesserockz requested changes

2021-09-21 19:53 UTC, jesserockz commented on esphome/components/modbus/modbus.cpp
> +   */
Don't leave commented code in please =)
```suggestion
```

2021-09-21 19:53 UTC, jesserockz commented on esphome/components/modbus_controller/__init__.py
> +    return reg_type
Considering this is a new component, this cannot be deprecated already

2021-09-21 19:53 UTC, jesserockz commented on esphome/components/modbus_controller/output/modbus_output.h
> +#include "esphome/components/modbus_controller/sensor/modbus_sensor.h"
This wont work if the user does not have any modbuscontroller sensors as the file will not be copied to the generated project.

Individual platforms should not rely on each other, only the parent component that is in the `DEPENDENCIES`

2021-09-21 19:53 UTC, jesserockz commented on esphome/components/modbus_controller/text_sensor/modbus_textsensor.cpp
> +  this->publish_state(result);
I don't think the lambdas should be responsible for publishing the state, they should just transform the value only.

**Same for all types, not just text_sensor**

2021-09-21 19:53 UTC, jesserockz commented on esphome/components/modbus_controller/output/__init__.py
> +CONF_MODBUS_SENSOR_ID = "modbus_sensor_id"
Is this used?

2021-09-21 20:08 UTC, jesserockz requested changes
While reading the docs I realised I missed this:

Number should not publish to a Sensor, the Number itself should change to the value read from the controller and should be independent.

2021-09-21 20:16 UTC, martgras commented
If Numbers had filters that would be my preference as well. 
They are a good fit for read/write registers
But they lack filters so to decouple them from sensor I'd have  at least provide a lambda for publishing the value . Maybe another multiply property...
The best option is adding filters to numbers ( for publish and write to device)

2021-09-21 21:12 UTC, jesserockz commented
Maybe the `lambda` options should be consistently used for converting the register value to the desired frontend value, and for things like number (and select if you decide to implement that) could have a second lambda `write_lambda` which converts to the register value.

2021-09-22 09:46 UTC, martgras commented on esphome/components/modbus_controller/__init__.py
> +    return reg_type
true but there are already a couple of users working with it from my repo. 
https://github.com/martgras/esphome/discussions/11
I will remove it once the PR is ready for merge

2021-09-22 10:00 UTC, martgras commented on esphome/components/modbus_controller/output/modbus_output.h
> +#include "esphome/components/modbus_controller/sensor/modbus_sensor.h"
fixed

2021-09-22 10:00 UTC, martgras commented on esphome/components/modbus_controller/output/__init__.py
> +CONF_MODBUS_SENSOR_ID = "modbus_sensor_id"
no

2021-09-22 10:05 UTC, nikito7 commented
Change link to: https://github.com/nikito7/edpbox/tree/dev/esphome

2021-09-22 10:17 UTC, martgras commented on esphome/components/modbus_controller/text_sensor/modbus_textsensor.cpp
> +  this->publish_state(result);
I can't find anymore from which component I copied this concept :)
Basically the idea is that a return {} from the lambda means  stop processing after the lambda: "everything has been taken care of" - but  yes maybe not really required here. 
I just followed the pattern from the number lambda  where it makes sense to give you the chance to handle more complex scenarios
I'm a bit undecided: 
-  remove that code path or 
- change the log message something like  " ESP_LOGV(TAG, "Empty return from lambda - no further processing");

2021-09-22 10:38 UTC, nikito7 commented
@martgras you re-added support for 4 bytes registers?

```yaml
  - platform: modbus_controller
    name: "${dev} T1 Vazio"
    address: 0x0026
    offset: 0
    modbus_functioncode: "read_input_registers"
    value_type: U_DWORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
```

2021-09-22 10:48 UTC, martgras commented
> you re-added support for 4 bytes registers?
> ```yaml
>  - platform: modbus_controller
>     name: "${dev} T1 Vazio"
>     address: 0x0026
>     offset: 0
>     modbus_functioncode: "read_input_registers"
>     value_type: U_DWORD
>     accuracy_decimals: 1
>     filters:
>       - multiply: 0.001
>     unit_of_measurement: "kWh"
>     device_class: energy
>     state_class: total_increasing
> ```

Yes  but then you have to set register_count: 1.
The code assumes 2 registers for DWORD therefore you have to override it
(Please have a look at https://github.com/martgras/esphome/blob/testing/esphome/components/modbus_controller/readme.md#note-sep15 since there a couple of other changes)

```yaml
 - platform: modbus_controller
    name: "${dev} T1 Vazio"
    address: 0x0026
    register_type: "read"
    value_type: U_DWORD
   register_count: 1
   accuracy_decimals: 1
   filters:
     - multiply: 0.001
   unit_of_measurement: "kWh"
   device_class: energy
   state_class: total_increasing
> ```

2021-09-22 10:51 UTC, jesserockz commented on esphome/components/modbus_controller/text_sensor/modbus_textsensor.cpp
> +  this->publish_state(result);
Like I said, I would prefer if the lambda was only used for transformation, and publishing was done in the component code. I see no real reason to have a user publish inside the lambda and will end up causing confusion/issues.

2021-09-22 10:56 UTC, martgras commented on esphome/components/modbus_controller/text_sensor/modbus_textsensor.cpp
> +  this->publish_state(result);
ok will remove it

2021-09-22 10:58 UTC, martgras commented
> Maybe the `lambda` options should be consistently used for converting the register value to the desired frontend value, and for things like number (and select if you decide to implement that) could have a second lambda `write_lambda` which converts to the register value.

Technically agreed  but unsure about the naming

For incoming data (filter) I keep the name 'lambda'
For number , output and (in the future select the name) will be 'write_lambda' for  write to device actions.

ok?

2021-09-23 09:42 UTC, nikito7 approved these changes
From my needs. All is working

2021-09-23 14:12 UTC, martgras commented on esphome/components/modbus_controller/__init__.py
> +    return reg_type
removed

2021-09-26 19:06 UTC, jesserockz commented on esphome/components/modbus_controller/switch/modbus_switch.cpp
> +  // value isn't required
```suggestion
  // value isn't required
```

2021-09-26 19:08 UTC, jesserockz approved these changes
LGTM! Great job =)

2021-09-26 20:27 UTC, merged

2021-09-26 20:42 UTC, reaper7 commented
how this implementation will affect the SDM energy meter component ?

2021-09-26 22:43 UTC, jesserockz commented
> how this implementation will affect the SDM energy meter component ?

It does not affect it. This is a new component that allows generic access to any modbus device without building it in native ESPHome code. Native ESPHome components will still provide a minimal/less confusing way for people to use those devices though (like SDM)