Initial ufire-ce board
OttoWinter/esphomeyaml pull request #1796
Opened 2021-05-17 15:17 UTC by pvizeli

# What does this implement/fix? 

Add support for uFire EC board: https://ufire.co/products/isolated-ec-probe-interface

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [x] ESP32
- [ ] ESP8266
- [x] Windows
- [ ] Mac OS
- [x] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

# Explain your changes

Add support for the ufire-ec isolated board which can have multiple sensors and action for calibrating the sensors on it.

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-05-18 20:02 UTC, jesserockz commented on esphome/components/ufire_ec/__init__.py
> +            cv.Optional(CONF_TEMPERATURE_COMPENSATION, default=25.0): cv.float_,
There is a helper to validate temperatures correctly in yaml
```suggestion
            cv.Optional(CONF_TEMPERATURE_COMPENSATION, default=25.0): cv.temperature,
```

2021-05-19 02:45 UTC, jesserockz requested changes

2021-05-19 02:45 UTC, jesserockz commented on esphome/components/ufire_ec/ufire_ec.h
> +  }
This will read the temperature sensor at setup not when the action is run. You should either store the temperature sensor pointer and read in play, or remove this and expose the templatable `temperature` to read the sensor in yaml
```
- ufire_ec.calibrate_probe:
    solution: 7.0
    temperature: !lambda "return id(temperature_sensor).state;"
```

2021-05-25 20:01 UTC, jesserockz commented on esphome/components/ufire_ec/ufire_ec.cpp
> +void UFireECComponent::dump_config() {}
Do you want to fill this out?

2021-05-26 13:13 UTC, pvizeli commented on esphome/components/ufire_ec/ufire_ec.cpp
> +void UFireECComponent::dump_config() {}
what is that?

2021-05-26 13:32 UTC, jesserockz commented on esphome/components/ufire_ec/ufire_ec.cpp
> +void UFireECComponent::dump_config() {}
Haha. It's a function that is run when you connect to the logs. The pink text that dumps most of your configuration to the logs. I left it empty because there was nothing to log at the time. Now you have 2 sensors. `LOG_SENSOR(...)`

2021-05-26 20:03 UTC, jesserockz commented on esphome/components/ufire_ec/ufire_ec.cpp
> +    LOG_SENSOR("  ", "Temperature Sensor external", this->temperature_sensor_external_)
The `if` are not needed as the `LOG_SENSOR` macro includes a check already
```suggestion
  LOG_SENSOR("  ", "EC Sensor", this->ec_sensor_)
  LOG_SENSOR("  ", "Temperature Sensor", this->temperature_sensor_)
  LOG_SENSOR("  ", "Temperature Sensor external", this->temperature_sensor_external_)
```

2021-05-31 19:34 UTC, jesserockz approved these changes

2021-10-20 01:38 UTC, closed without merging