Add cover toggle support
OttoWinter/esphomeyaml pull request #1809
Opened 2021-05-20 21:24 UTC by dtmuller

# What does this implement/fix? 

Adds support for cover operation with single push button, cycling through the states close/stop/open/stop... with
each button press.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [ ] ESP32
- [x] ESP8266
- [ ] Windows
- [x] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

cover:
  - platform: time_based
    id: cover_1
    open_duration: 10s
    close_duration: 10s
binary_sensor:
  - platform: template
    id: switch_1
    on_press:
      then:
        - cover.toggle: cover_1
```

# Explain your changes

The toggle action allows the cover to be operated with a single push button. Cycling through the sequence 
close/stop/open/stop... Opening the cover when fully closed, closing the cover when fully opened.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-05-21 19:29 UTC, OttoWinter commented on esphome/components/cover/cover.cpp
> +      this->parent_->last_operation = CoverOperation::COVER_OPERATION_OPENING;
A `CoverCall` object shouldn't modify the parent's state directly, the cover implementation itself should set this attribute.

Also this logic _should_ be in `:perform()` because the construction of the `CoverCall` object may happen at a different time than it is actually `perform()`ed.

2021-05-22 12:38 UTC, dtmuller commented on esphome/components/cover/cover.cpp
> +      this->parent_->last_operation = CoverOperation::COVER_OPERATION_OPENING;
Moved the logic to `perform()` as suggested.

However I don't see an easy way to set the `last_operation` flag from the cover implementation. To my understanding I would need to do that for every integration, which IMO is a bit unlucky - I'd rather keep the toggle logic together.

Any suggestion? Maybe better implement the toggle as a cover trait and have each integration support it or not?

2021-07-17 07:13 UTC, dtmuller commented
@OttoWinter Is there more to do for me on this pull request?

2021-07-26 07:28 UTC, OttoWinter commented on esphome/components/cover/cover.cpp
> +        this->parent_->last_operation = CoverOperation::COVER_OPERATION_OPENING;
This is a red flag - a call shouldn't set properties on the instance it's operating on.

I get how this feature is useful, but I don't think we can put all the logic in `CoverCall`, there's just too many things to consider. I would recommend adding this as a new capability attribute in traits, and have each integration deal with toggle on their own (they also have more information what toggle should do)

2021-09-03 21:38 UTC, dtmuller commented on esphome/components/cover/cover.cpp
> +        this->parent_->last_operation = CoverOperation::COVER_OPERATION_OPENING;
Made the toggle command a cover trait as suggested. Implemented it for time-based cover.

2021-09-22 10:24 UTC, oxan requested changes
Hi, sorry this stalled for so long. I see you already noticed that we deprecated the open/close/stop methods on Cover. It doesn't make much sense to add a new toggle() method and deprecate it immediately, so just leave that. 

Other than that this looks good for me.

2021-09-22 10:24 UTC, oxan commented on esphome/components/cover/automation.h
> +  void play(Ts... x) override { this->cover_->toggle(); }
```suggestion
  void play(Ts... x) override { this->cover_->make_call().set_command_toggle().perform(); }
```

2021-09-22 10:24 UTC, oxan commented on esphome/components/cover/cover.h
> +  void toggle();
```suggestion
```

2021-09-22 10:24 UTC, oxan commented on esphome/components/cover/cover.cpp
> +}
```suggestion
```

2021-09-26 17:06 UTC, oxan approved these changes

2021-09-27 20:31 UTC, merged

2021-09-27 20:31 UTC, oxan commented
Thanks!