Adds support cpp to vscode
OttoWinter/esphomeyaml pull request #1828
Opened 2021-05-24 17:20 UTC by dentra

# What does this implement/fix? 

It is revision of #914 and it additionally adds support of CPP to VSCode devcontainer development. It only affect this development environment.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

* #914

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [ ] ESP32
- [ ] ESP8266
- [ ] Windows
- [x] Mac OS
- [x] Linux

# Explain your changes

It is only for development purpose.

It adds:
* clang-format-7 and configure VSCode to use it
* clang-tidy to manually run script/clang-tidy
* nano for comfort work with git command
* configures two CPP configurations: ESP8266 and ESP32
* install all necessary python dependencies (pylint, black,flake8, pexpect) to use it by vscode and from cmd line
* exclude python compiled files from navigator view
* fix deprecated terminal.integrated.shell.linux config parameter
* adds vscode extensions for CPP, editorconfig, comments and braces

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-05-24 18:42 UTC, OttoWinter reviewed
Thanks! This could make the devcontainer experience better :star_struck: 

I left you some comments about the included extensions, and the Dockerfile.

2021-05-24 18:42 UTC, OttoWinter commented on .devcontainer/devcontainer.json
> +    "jeff-hykin.better-cpp-syntax",
This is not needed, the cpptools package already ships this syntax (and appears to be maintained better)

From the [readme](https://github.com/jeff-hykin/cpp-textmate-grammar)
> This used to be a fix, but then VS Code started using it as the official source for C and C++ highlighting.

2021-05-24 18:42 UTC, OttoWinter commented on .devcontainer/devcontainer.json
> +    "aaron-bond.better-comments",
ESPHome doesn't use these comment styles, so this can be dropped (a preference thing, but I think devcontainer.json should only include what is really needed/useful)

2021-05-24 18:42 UTC, OttoWinter commented on .devcontainer/devcontainer.json
> +    "coenraads.bracket-pair-colorizer-2",
IMO, we should only include extensions that add utility (like cpptools), not theme/looks extensions, as those depend much on the preferences of the developer.

2021-05-24 18:42 UTC, OttoWinter commented on .gitignore
> +!.vscode/c_cpp_properties.json
Hmm, this will cause issues for people who use VSCode without the devcontainer unfortunately.

For example, for me the platformio installed the pinned version of the xtensa toolchain in `.platformio/packages/toolchain-xtensa@1.40802.0` - not `toolchain-xtensa` (that directory contains the most recent version, not the pinned one).

The command `pio init --ide vscode` should generate that file, can we run that when starting the container?

2021-05-24 18:42 UTC, OttoWinter commented on docker/Dockerfile.dev
>  FROM esphome/esphome-base-amd64:3.0.0
Huh, weird that this container is using `esphome-base` as the base image - we also have [`esphome/esphome-lint`](https://hub.docker.com/r/esphome/esphome-lint) that already ships the `clang-format/tidy/etc` packages (built here: [Dockerfile1](https://github.com/esphome/esphome/blob/dev/docker/Dockerfile.lint), [Dockerfile2](https://github.com/esphome/esphome-docker-base/blob/master/Dockerfile.lint)).

Maybe there's a reason for using that base image, but can you check if it works by just changing this line to
```suggestion
FROM esphome/esphome-lint:latest
```

Then the devcontainer start process would also be much faster, as the packages don't need to be installed first.

2021-05-24 19:08 UTC, dentra commented on .devcontainer/devcontainer.json
> +    "jeff-hykin.better-cpp-syntax",
Ok. Will fix.

2021-05-24 19:09 UTC, dentra commented on .devcontainer/devcontainer.json
> +    "aaron-bond.better-comments",
Ok. Will fix.

2021-05-24 19:09 UTC, dentra commented on .devcontainer/devcontainer.json
> +    "coenraads.bracket-pair-colorizer-2",
Ok. Will fix.

2021-05-24 19:12 UTC, dentra commented on .gitignore
> +!.vscode/c_cpp_properties.json
Thanks for idea. I will try it.

2021-05-24 19:13 UTC, dentra commented on docker/Dockerfile.dev
>  FROM esphome/esphome-base-amd64:3.0.0
Thanks. I will check it

2021-06-05 12:55 UTC, agners requested changes

2021-06-05 12:55 UTC, agners commented on docker/Dockerfile.dev
> +FROM esphome/esphome-lint:latest
The `esphome-lint` container is also versioned so I think I would keep versioning here.

Also you need to adjust the script `script/bump-docker-base-version.py`.

2021-06-05 12:55 UTC, agners commented on esphome/automation.py
> +@register_condition("lambda", LambdaCondition, cv.returning_lambda)
This seems a rather unrelated change, can you get rid of it?

2021-06-05 12:55 UTC, agners commented on docker/Dockerfile.dev
> -COPY . .
I am not really sure what the intent of this copy was, but from what I can tell sources are bind mounted by default:
https://code.visualstudio.com/docs/remote/containers-advanced#_changing-the-default-source-code-mount

I think removing this is fine!

2021-06-05 13:01 UTC, agners commented on script/devcontainer-post-create
> +    pio init --ide vscode
This leads to the standard pio init message:
```
The current working directory /workspaces/esphome will be used for the project.

The next files/directories have been created in /workspaces/esphome
include - Put project header files here
lib - Put here project specific (private) libraries
src - Put project source files here
platformio.ini - Project Configuration File

Project has been successfully updated including configuration files for `vscode` IDE.
```

I think this is a bit confusing in this case. There is `--silent` to suppress the message. Maybe an echo would still be good:

```suggestion
echo "Initializing PlatformIO..."
pio init --ide vscode --silent
```

2021-06-05 23:23 UTC, dentra commented on esphome/automation.py
> +@register_condition("lambda", LambdaCondition, cv.returning_lambda)
It is merged change not mine. It is equals to dev. I will check again.

2021-06-05 23:25 UTC, dentra commented on docker/Dockerfile.dev
> +FROM esphome/esphome-lint:latest
This change (-lint:latest) suggested by @OttoWinter. 

Okay, I’ll look in script/bump-docker-base-version.py

2021-06-06 15:20 UTC, agners commented on docker/Dockerfile.dev
> +FROM esphome/esphome-lint:latest
Yeah I think Otto was mostly about using the lint instead of the base container. I would suggest to keep the version.

2021-06-08 09:04 UTC, OttoWinter commented on docker/Dockerfile.dev
> +FROM esphome/esphome-lint:latest
@agners `esphome-lint` is not versioned (only `esphome-lint-base`). And using `esphome-lint` is likely better because then the python+platformio reqs are already installed (and only the locally changed ones need to be reinstalled)

2021-06-08 15:30 UTC, dentra commented on esphome/automation.py
> +@register_condition("lambda", LambdaCondition, cv.returning_lambda)
checked. changes equals to dev

2021-06-08 16:12 UTC, dentra commented on docker/Dockerfile.dev
> +RUN export DEBIAN_FRONTEND=noninteractive \
`nano` is not necessary but useful with `git` for example.

Now when we removed `RUN` then our `Dockerfile.dev` will contain only one line `FROM esphome/esphome-lint:latest`. So maybe we can remove this file and use lint image directly from `devcontainer.json`:
```yaml
...
"image": "esphome/esphome-lint:latest"`
...
```

2021-06-08 17:53 UTC, agners approved these changes

2021-06-08 21:35 UTC, agners requested changes

2021-06-08 21:35 UTC, agners commented on .devcontainer/devcontainer.json
> +    "C_Cpp.clang_format_path": "/usr/bin/clang-format-7",
Now that clang-11 is available you can use clang-format-11 here (see https://github.com/esphome/esphome/pull/1846).

2021-06-08 21:35 UTC, agners commented on docker/Dockerfile.dev
> +FROM esphome/esphome-lint:latest
It turned out that esphome-lint needs versioning for bigger changes like moving to a new clang version (see https://github.com/esphome/esphome/pull/1877).

So this should be using the latest version `esphome/esphome-lint:1.1`

```suggestion
FROM esphome/esphome-lint:1.1
```

2021-06-10 15:40 UTC, dentra commented on .devcontainer/devcontainer.json
> +    "C_Cpp.clang_format_path": "/usr/bin/clang-format-7",
done

2021-06-10 15:41 UTC, dentra commented on .devcontainer/devcontainer.json
> +    "C_Cpp.clang_format_path": "/usr/bin/clang-format-7",
done

2021-06-10 18:00 UTC, agners approved these changes

2021-06-11 17:21 UTC, dentra commented
@OttoWinter @agners What should I do next, to get meged this PR to dev?

2021-06-14 22:45 UTC, jesserockz approved these changes
LGTM

2021-06-14 22:45 UTC, merged