Add optional lambda to BLESensor for raw data parsing
OttoWinter/esphomeyaml pull request #1851
Opened 2021-05-31 19:30 UTC by torfbolt

# What does this implement/fix? 

This expands on the recently merged BLE GATT client functionality, which only used the first byte of each data message. Since many BLE devices use messages with more than one byte of payload and a wide variety of data encodings, converting these with a user-defined lambda seems the most practical way forward. This pull request introduces such a lambda function as an optional configuration parameter, with fallback to the current way of using just the first data payload byte.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/556#issuecomment-845488558

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [X] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [x] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

esp32_ble_tracker:

ble_client:
  - mac_address: F5:FF:58:7E:04:73
    id: smartgadget_0473

sensor:
  - platform: ble_client
    ble_client_id: smartgadget_0473
    name: "RH_0473"
    service_uuid: '00001234-B38D-4985-720E-0F993A68EE41'
    characteristic_uuid: '00001235-B38D-4985-720E-0F993A68EE41'
    device_class: "humidity"
    lambda: !lambda |-
      return *((float*)(&x[0]));

```

# Explain your changes

see above

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-05-31 23:28 UTC, buxtronix commented
Much more useful than the original, thanks!

2021-06-01 03:38 UTC, jesserockz approved these changes

2021-06-01 03:41 UTC, jesserockz requested changes

2021-06-01 03:41 UTC, jesserockz commented on esphome/components/ble_client/sensor/__init__.py
> +            cv.Optional(CONF_LAMBDA): cv.lambda_,
```suggestion
            cv.Optional(CONF_LAMBDA): cv.returning_lambda,
```

2021-06-01 09:46 UTC, jesserockz approved these changes

2021-06-01 09:46 UTC, merged