Add away state to tuya climate component
OttoWinter/esphomeyaml pull request #1860
Opened 2021-06-03 11:13 UTC by kroimon

# What does this implement/fix? 

This adds support for the "away" state to the tuya climate component.

My tuya climate controller, the BHT-3000, has a so-called "eco mode" that fixes the target temperature to a lower "eco temperature".  
The "eco mode" state (on/off) can be read by a tuya datapoint.  
The "eco temperature" defaults to 20 °C and can only be changed via the controllers' buttons. This setting is hidden in a system menu and is unlikely to be changed by the user once configured. As the eco temperature setting is not made available as a tuya datapoint by the MCU, it needs to be statically configured.

Although my controller calls this "eco mode", no "eco" preset is currently available via esphome, so I made use of the "away" functionality. We might want to revise this later when #1471 is finally merged.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** WIP
  
# Test Environment

- [ ] ESP32
- [X] ESP8266
- [ ] Windows
- [ ] Mac OS
- [X] Linux (Home Assistant Addon)

## Example entry for `config.yaml`:

```yaml
climate:
  - platform: tuya
    name: "Thermostat"
    switch_datapoint: 1
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    temperature_multiplier: 0.5
    away_datapoint: 5
    away_temperature: 20
```

# Explain your changes

When setting my tuya climate controller anything but manual mode, the target temperature is currently not correctly reported back to home assistant as the component only respects the setpoint used for manual mode.
This PR fixes that at least for the eco mode of the controller.
I am also working on code to evaluate the scheduling data for automatic mode and will provide a PR for that at some point in the future.

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-06-03 12:30 UTC, kroimon commented
Added documentation in esphome/esphome-docs#1216.

2021-08-20 17:49 UTC, oxan commented
Hi! Sorry it took this long. In the meantime #1471 has been merged and the `away` option has been deprecated. Could you update this PR to make use of that functionality instead? Thanks!

2021-08-31 22:10 UTC, kroimon commented
I will update the PR to make use of the "eco" preset instead of the deprecated "away" option.

2021-09-01 23:58 UTC, jesserockz commented
> I will update the PR to make use of the "eco" preset instead of the deprecated "away" option.

There is still an `away` preset, its just set in a different way now.

2021-09-15 07:20 UTC, kroimon commented
I updated the PR to use the new CLIMATE_PRESET_ECO preset instead of the old away functionality. Docs have also been updated.

@oxan and @jesserockz: Can you do another review, please?

2021-09-15 16:29 UTC, oxan approved these changes
LGTM, but I'm not too familar with both the Tuya and climate code, so would like a second review before merging :)

2021-09-15 17:58 UTC, jesserockz requested changes

2021-09-15 17:58 UTC, jesserockz commented on esphome/components/tuya/climate/tuya_climate.cpp
> +  }
`this->eco_temperature_` will always have a value if you have set the eco datapoint because it has a default in config. It is set as an `optional` in c++ so would be nice to remove the default from `CONF_ECO_TEMPERATURE` and then only set it from `to_code` if the user has set it. 

Personally I can use the eco datapoint on my heater, but it does not change the temperature setting, only the heat strength (1000W vs 2000W)

2021-09-15 17:58 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
> +        cg.add(var.set_eco_temperature(config[CONF_ECO_TEMPERATURE]))
```suggestion
        if CONF_ECO_TEMPERATURE in config:
            cg.add(var.set_eco_temperature(config[CONF_ECO_TEMPERATURE]))
```

2021-09-15 17:58 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
> +            cv.Optional(CONF_ECO_TEMPERATURE, default=20): cv.temperature,
```suggestion
            cv.Optional(CONF_ECO_TEMPERATURE): cv.temperature,
```

2021-09-15 19:29 UTC, kroimon commented on esphome/components/tuya/climate/tuya_climate.cpp
> +  }
Good suggestion. I didn't think it would be useful to have eco mode without a temperature setpoint, but your heater proves me wrong 😉

2021-09-19 21:01 UTC, kroimon commented
@jesserockz Should be ready for merging now :)

2021-09-19 21:16 UTC, jesserockz approved these changes

2021-09-19 21:17 UTC, merged