Add support for more EZO sensor commands
OttoWinter/esphomeyaml pull request #1865
Opened 2021-06-05 12:50 UTC by thomasdelaet

# What does this implement/fix? 

Add support for calibrating EZO probes and for setting probe type (relevant for EC probe). Calibration can happen using a single value or multi-point calibration (support varies across probe types)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

# Test Environment

- [ ] ESP32
- [x] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

# Explain your changes

There have been various debates to support more commands (specifically calibration) on these sensors since this needs to happen every couple of months. Currently support for EZO commands was limited to temperature compensation. This PR adds support for:
- Setting the probe type (relevant for EC probes)
- Single-point calibration
- Multi-point calibration

Note that this is my first time writing C++ code. So happy to get feedback.

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

2021-08-03 06:45 UTC, OttoWinter commented
Friendly ping @ssieb - can you take a look at this? :)

Code LGTM :+1:

2021-08-03 07:14 UTC, ssieb requested changes

2021-08-03 07:14 UTC, ssieb commented on esphome/components/ezo/ezo.cpp
> +static const uint16_t CAL_HIGH = 3;
Please change this to an enum and move it to the .h file.

2021-08-03 07:16 UTC, ssieb commented
Add descriptions of the new methods to the doc page.

2021-08-24 13:32 UTC, auredor commented
> Add descriptions of the new methods to the doc page.

@ssieb Thank you for the improvement. Any commitment on when the documentation will be updated. ?

2021-12-01 01:38 UTC, closed without merging