waveshare_epaper: add support for ttgo t5 b74 variant display
OttoWinter/esphomeyaml pull request #1869
Opened 2021-06-07 18:34 UTC by osresearch

![image](https://user-images.githubusercontent.com/3068843/121070324-db37f500-c7ce-11eb-93ae-6d767bdba6b4.png)

# What does this implement/fix? 

This patch adds support for ttgo t5 b74 variant 2.13" e-ink display.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [X] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [X] Linux

## Example entry for `config.yaml`:

```yaml
esphome:
  name: ttgo-t5-display
  platform: ESP32
  board: featheresp32

wifi:
  ssid: "testnet"
  password: "password"

time:
  - platform: sntp
    id: ntp

font:
  - file: 'IBMPlexMono-Bold.ttf'
    id: din_big
    size: 50

spi:
  clk_pin: 18
  mosi_pin: 23
  # miso_pin unused

display:
  - platform: waveshare_epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 2.13in-ttgo-b74
    update_interval: 1s
    full_update_every: 30
    rotation: 270
    lambda: |-
      it.strftime(125, 14, id(din_big), TextAlign::TOP_CENTER, "%H:%M:%S", id(ntp).now());

```

# Explain your changes

The GxGDEM0213B74 is similar to the b73 variant, although it
does not use a LUT waveform when doing full or partial updates,
and adds a command for the border waveform.

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-06-09 08:32 UTC, osresearch commented
![image](https://user-images.githubusercontent.com/3068843/121320977-f65d4e80-c90d-11eb-8a1b-0681fa113641.png)

The display is showing lots of degradation when exposed to sunlight. This is likely due to not being powered off after refresh, which the example code from TTGO seems to do.

2021-06-09 09:36 UTC, nikito7 approved these changes
Good work

2021-06-09 10:04 UTC, osresearch commented
![image](https://user-images.githubusercontent.com/3068843/121332881-8f916280-c918-11eb-941c-a45673cdafb6.png)

The fading in the previous example is almost instant when exposed to sunlight; elsewhere I've read that this is due to the high voltage driver being left on after an update.  I'm experimenting with turning off the display after a draw cycle since that is what the TTGO example code does.  This does preserve the image when exposed to sunlight, especially the parts that were not updated, although it also takes several updates for the static parts of the image to be correctly displayed. It is like the display needs a sleep timeout before shutting off.

2021-06-09 10:16 UTC, nikito7 commented
You can try fill all screen before, just for testing

2021-06-09 10:19 UTC, nikito7 requested changes
Maybe add something here

2021-06-09 10:30 UTC, nikito7 commented
```c
void GxGDEM0213B74::_PowerOff(void){    _writeCommand(0x10);    _writeData(0x01);    // _writeCommand(0x20);    // _waitWhileBusy("_PowerOff");}
```

After update add a small delay and power off

But I don't know where 😅

2021-07-05 21:15 UTC, Viper780 commented
Whats the status here?
Does anyone fixes the two flailed checks?

2021-08-07 16:14 UTC, nikito7 commented
To be fixed here: https://github.com/esphome/esphome/pull/2135

2021-08-08 20:12 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +     this->reset_pin_->digital_write(1);
```suggestion
     this->reset_pin_->digital_write(false);
     delay(10);
     this->reset_pin_->digital_write(true);
```

2021-08-08 20:15 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +  }
```suggestion
  if (this->model_ == TTGO_EPAPER_2_13_IN_B74) {
    this->reset_pin_->digital_write(false);
    delay(10);
    this->reset_pin_->digital_write(true);
    delay(10);
    this->wait_until_idle_();

    this->command(0x12);  // SWRESET
    this->wait_until_idle_();
  }
```

2021-08-08 20:56 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +      //BorderWaveform
```suggestion
      // BorderWaveform
```

2021-08-08 20:56 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +    //this->data(0xC7);
```suggestion
    // this->data(0xC7);
```

2021-08-08 21:54 UTC, nikito7 approved these changes

2021-08-08 21:58 UTC, nikito7 commented
Closes https://github.com/esphome/feature-requests/issues/1167

2021-08-10 08:09 UTC, OttoWinter approved these changes
Thanks!

2021-08-10 08:09 UTC, merged