Add bl0940 component used by e.g. tuya devices
OttoWinter/esphomeyaml pull request #1904
Opened 2021-06-13 15:43 UTC by tobias-

# What does this implement/fix? 

Adds BL0940 component support for e.g. the tuya device Blitzwolf BW-SHP10.

https://github.com/esphome/feature-requests/issues/770 

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

TBD

## Test Environment

TBD

- [ ] ESP32
- [X] ESP8266

## Example entry for `config.yaml`:
Need help here. Not sure

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-06-13 17:11 UTC, tobias- commented
Code is based on custom sensor I wrote with lots of looking at the tasmota implementation: https://gist.github.com/tobias-/aacfa017d9a1287e5e41a11d2588a0f2

2021-08-20 17:18 UTC, oxan requested changes
Hi, thanks for your contribution! Sorry it took this long before somebody got to your PR.

I've left a few comments on the code, could you take a look at them?

2021-08-20 17:18 UTC, oxan commented on esphome/components/bl0940/bl0940.h
> +static const float BL0940_EREF = 3.6e6 / 297;
Where are the values of these constants coming from? They don't seem to match the values in the [datasheet](https://www.belling.com.cn/media/file_object/bel_product/BL0940/datasheet/BL0940_V1.1_en.pdf).

From the datasheet, I'd expect PREF = 4046/1.218^2 = 2727 (W), UREF = 79931/1.218 = 65624 (V), IREF = 324004/1.218 = 266013 (A), EREF = 3600*4046/(1638.4\*256\*1.218^2) = 23.41 (Wh) (or possibly a factor of 1000 larger if t_CF is given in milliseconds).

2021-08-20 17:18 UTC, oxan commented on esphome/components/bl0940/bl0940.h
> +  // Caveat if you measure power in both directions as there is no
This comment seems to be truncated.

2021-08-20 17:18 UTC, oxan commented on esphome/components/bl0940/bl0940.h
> +} __attribute__((packed));
If you define this as an union, you don't have to cast from/to `uint8_t` pointers all the time (which technically violates strict aliasing rules):
```cpp
union DataPacket {
   uint8_t raw[35];
   struct {
      // ...
  };
}
```

2021-08-20 17:18 UTC, oxan commented on esphome/components/bl0940/bl0940.cpp
> +               sensor->get_name().c_str(), sensor->get_state(), converted_temp);
This can be logged at info or warning level, I think.

2021-08-20 17:18 UTC, oxan commented on esphome/components/bl0940/bl0940.cpp
> +           total_energy_consumption, tps1, tps2);
This is more suitable for the verbose log level.

2021-08-20 17:18 UTC, oxan commented on esphome/components/bl0940/bl0940.cpp
> +  LOG_SENSOR("", "TempExt", this->external_temperature_sensor_);
```suggestion
  LOG_SENSOR("", "Internal temperature", this->internal_temperature_sensor_);
  LOG_SENSOR("", "External temperature", this->external_temperature_sensor_);
```

2021-08-20 17:18 UTC, oxan commented on esphome/components/bl0940/bl0940.h
> +  void received_package_(DataPacket *data) const;
These two methods can also take a const reference as parameter, I think.

2021-08-20 17:18 UTC, oxan commented on esphome/components/bl0940/sensor.py
> +                UNIT_WATT_HOURS,
According to the comments in the code, the value for this sensor is in kilowatthours, not watthours.

2021-08-20 17:18 UTC, oxan commented on esphome/components/bl0940/sensor.py
> +            # TODO This isn't the right CONF. What to use instead?
You can define two new CONF settings in this file, `CONF_INTERNAL_TEMPERATURE` and `CONF_EXTERNAL_TEMPERATURE`.

2021-08-23 12:00 UTC, tobias- commented on esphome/components/bl0940/bl0940.cpp
> +               sensor->get_name().c_str(), sensor->get_state(), converted_temp);
It's very common to leave the  sensor unconnected and then it will have a floating value meaning this is spammed in the logs. I'm actually considering just removing it altogether

2021-08-23 12:00 UTC, tobias- commented on esphome/components/bl0940/bl0940.cpp
> +           total_energy_consumption, tps1, tps2);
OK!

2021-08-23 12:01 UTC, tobias- commented on esphome/components/bl0940/sensor.py
> +            # TODO This isn't the right CONF. What to use instead?
OK!

2021-08-23 12:02 UTC, tobias- commented on esphome/components/bl0940/bl0940.h
> +  void received_package_(DataPacket *data) const;
OK!

2021-08-23 12:09 UTC, tobias- commented on esphome/components/bl0940/bl0940.h
> +static const float BL0940_EREF = 3.6e6 / 297;
It's been a while since I wrote this, but _IIRC_, 
EREF is measured for 230V, as the values I got when using it (the load was a fan on constant speed drawing ~140W and compared to another power measurer).
The UREF, PREF and IREF values are all from Tasmota iirc.

2021-08-23 12:09 UTC, tobias- commented on esphome/components/bl0940/bl0940.h
> +  // Caveat if you measure power in both directions as there is no
Will fix!

2021-08-23 12:10 UTC, tobias- commented on esphome/components/bl0940/bl0940.h
> +} __attribute__((packed));
Yes, that would simplify the validation.

2021-08-23 12:17 UTC, tobias- commented
Give me a day or two to fix this. All looks easy enough except for testing the Watt hour and the reference values.

Please note that these values are afaik only valid with 230V, and that's why I've made them configurable.

2021-08-24 21:36 UTC, oxan commented on esphome/components/bl0940/bl0940.cpp
> +               sensor->get_name().c_str(), sensor->get_state(), converted_temp);
Ah okay, yeah then it's fine.

2021-08-24 21:50 UTC, oxan commented on esphome/components/bl0940/bl0940.h
> +static const float BL0940_EREF = 3.6e6 / 297;
The reason I'm asking is that values like this are usually cargo-culted, and the original source isn't always credible. Especially for power values the power factor is often ignored, or there's confusion between real and apparent power. The numbers from Tasmota seem to be last changed in [this](https://github.com/arendst/Tasmota/commit/56ea7279bd32cfa688e15543552a34b4da5cb52c) commit, with an unrelated commit message and no motivation behind the change. That doesn't give me confidence their values are correct.

It's good that they're configurable, but good defaults would be great too :)

2021-09-14 10:25 UTC, tobias- commented on esphome/components/bl0940/bl0940.h
> +static const float BL0940_EREF = 3.6e6 / 297;
UREF, PREF and IREF are all verified to give sane values (I'm guessing well below 1% error, at least for UREF)

2021-09-14 11:44 UTC, tobias- commented on esphome/components/bl0940/bl0940.h
> +static const float BL0940_EREF = 3.6e6 / 297;
(sane compared to my incoming power box provided by the electric company itself)

2021-09-14 12:02 UTC, tobias- commented on esphome/components/bl0940/bl0940.h
> +  // Caveat if you measure power in both directions as there is no
Caveat no longer applies. I used to have a `power < 0 do nothing`

2021-09-14 15:06 UTC, tobias- commented
This is not done yet. I need to test it again.

2021-09-14 19:08 UTC, oxan commented
> This is not done yet. I need to test it again.

I've converted this PR to draft to reflect that, you can convert it back to ready once you're done :)

2021-11-02 13:52 UTC, langestefan commented
> This is not done yet. I need to test it again.

Hi, thanks for this PR. Do you need any help with testing? I have a couple of these plugs and they are currently running Tasmota until this PR gets merged :)

2021-12-17 15:18 UTC, frankiboy1 commented
I've been using this new feature for a couple of days now with great success. Is there a reason why it's still marked as draft?  Would be great to see this feature in the next release. :)

2021-12-27 06:00 UTC, tobias- commented
> I've been using this new feature for a couple of days now with great success. Is there a reason why it's still marked as draft? Would be great to see this feature in the next release. :)

@frankiboy1 Great! Only reason is I managed to brick my test-plug, fixed it, tested on another plug and then changed everything around and was afraid I might've made some more errors and wanted to revive my plug before testing again and ran into some snags/time issues doing that. I'll fix the conflicts and start the process anew.

2021-12-27 06:01 UTC, tobias- commented
> > This is not done yet. I need to test it again.
> 
> Hi, thanks for this PR. Do you need any help with testing? I have a couple of these plugs and they are currently running Tasmota until this PR gets merged :)

@langestefan I just got help. Reviving the PR this afternoon if I get the time.

2021-12-27 20:02 UTC, tobias- commented
@oxan Please review again. @frankiboy1 says he has tested it, and I've rebased from master, updated docs etc.

2021-12-27 21:09 UTC, frankiboy1 commented
Just to give a more proper feedback.

I'm using this PR (on top of 2021.12.1) on a Blitzwolf SHP-10. Voltage, current, power and energy looks like I would expect. The internal_temperature is slightly higher than expected (34C) with fairly low load (a monitor and USB-C PD charger) in a cool room (19C). The external_temperature is way too high (137C). Not sure if BL0940 relies on external HW and would require tuning of parameters for this smart plug.

I don't use the temperature for anything, so I don't mind about temperature being incorrect. I do, however, see a use case for automatic shutdown if temperature rises above a certain level.

2021-12-27 21:24 UTC, tobias- commented
> Just to give a more proper feedback.
> 
> I'm using this PR (on top of 2021.12.1) on a Blitzwolf SHP-10. Voltage, current, power and energy looks like I would expect. The internal_temperature is slightly higher than expected (34C) with fairly low load (a monitor and USB-C PD charger) in a cool room (19C). The external_temperature is way too high (137C). Not sure if BL0940 relies on external HW and would require tuning of parameters for this smart plug.

Yes, the internal temperature is high, but I'm not sure if it's actually too high. After sawing it apart, I can tell it's bloody cramped inside the SHP-10. Temperature seems stable though in my experience, so I'm not worried about it.

The external temperature is not connected at all in the SHP-10 configuration, so it just floats which is annoying at best. Imho they could at least have pulled it to ground, but it IS cheap, so...

> 
> I don't use the temperature for anything, so I don't mind about temperature being incorrect. I do, however, see a use case for automatic shutdown if temperature rises above a certain level.

Agreed. I'm not sure if there should be a recommended configuration that monitors it and turns the power off in case of over-temp. I would argue the latter, as there may be other configurations that would see it running hot without it being a problem. More important for SHP-10 would be having over-current protection. Not sure if there's any extra safety built in that cut's power, but my gut tells me that the only over-current protection is flames coming out of it..

2022-01-03 17:40 UTC, oxan approved these changes

2022-01-04 09:38 UTC, merged