Feature/rtsp server
OttoWinter/esphomeyaml pull request #1905
Opened 2021-06-13 22:05 UTC by crossan007

# What does this implement/fix? 

Adds an RTSP Server implementation to support using the camera outside of HomeAssistant

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/960

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1240

## Test Environment

- [X] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
rtsp_server:
  port: 8675
  camera: cam1

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-06-13 22:07 UTC, crossan007 commented on esphome/components/esp32_camera/__init__.py
> +#DEPENDENCIES = ["api"]
Is there a way to mark an `OR` set of dependencies?  With this component, the camera now depends on `api` _OR_ `rtsp_server` (kind of; it's a weird way to note a dependency IMHO)

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/esp32_camera/__init__.py
> +#DEPENDENCIES = ["api"]
There is not. However, it's ok if we remove this line now that there are multiple streaming targets.

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/rtsp_server/__init__.py
> +DEPENDENCIES = ["network"]
```suggestion
DEPENDENCIES = ["network", "esp32_camera"]
```

Now `esp32_camera` _should_ be a dependency, as `rstp_server` relies directly on it (see the `#include`s)

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/rtsp_server/__init__.py
> +        cv.Required("camera"): cv.use_id(esp32_camera.ESP32Camera),
1. Config keys should be in constants, like `CONF_CAMERA` (for example below `AUTO_LOAD` line).
2. There's no need for `Required`, esphome can auto-wire the camera if there's only one in the config (which is likely the case for all configs). 
```suggestion
        cv.GenerateID(CONF_CAMERA): cv.use_id(esp32_camera.ESP32Camera),
```

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/rtsp_server/__init__.py
> +@coroutine_with_priority(65.0)
No need for `@coroutine_with_priority` here (it's only used for some components that specifically need some code to be placed in the generated cpp file early)

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/rtsp_server/rtsp_server.h
> +    dimensions parseCameraDimensions(camera_config_t config);
See also the lint warnings, esphome's naming style would be `parse_camera_dimensions_`

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/rtsp_server/rtsp_server.h
> +#include "esphome/core/component.h"
The .h/.cpp files will likely need to be wrapped in a `#ifdef ARDUINO_ARCH_ESP32`, otherwise the (esp8266-toolchain based) clang-tidy linter will try to load it and spew errors.

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/rtsp_server/rtsp_server.cpp
> +  catch (...) {
ESPHome's builds have cpp exceptions disabled, so this `try-catch` can be removed/should be replaced by return code based error handling.

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/rtsp_server/rtsp_server.cpp
> +    this->mark_failed();
Missing return after this statement.

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/rtsp_server/rtsp_server.cpp
> +  ESP_LOGCONFIG(TAG, "Beginning to set up RTSP server listener");
```suggestion
  ESP_LOGD(TAG, "Beginning to set up RTSP server listener");
```

config log level is only for things written in `dump_config`

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/rtsp_server/rtsp_server.cpp
> +     ESP_LOGCONFIG(TAG, "Error: Unable to obtain reference to camera");
```suggestion
     ESP_LOGD(TAG, "Error: Unable to obtain reference to camera");
```

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/rtsp_server/rtsp_server.cpp
> +#include <StreamString.h>
```suggestion
```

I don't see this used anywhere, can we remove it?

2021-06-14 16:18 UTC, OttoWinter commented on esphome/components/rtsp_server/rtsp_server.cpp
> +    this->server->pushFrame(data, length);
Unfortunately this code will not always work. ESPHome handles the lifetime of image buffers through the `shared_ptr`, as soon as the `shared_ptr` is deallocated (goes out of scope), the `esp32_camera` integration assumes the buffer is ready to be used for the next frame.

By accessing the data buffer directly, and not forwarding the shared pointer, this can end up with a race condition (camer integration writes to buffer, because it thinks it's no longer in use, while the RTSP server still uses it).

I'd recommend storing the `shared_ptr` instance in this class, until the buffer is no longer needed (see also `CameraImageReader`, with `set_image` and `return_image`)

2021-06-14 16:19 UTC, OttoWinter commented
Thanks for the RTSP library btw! With that the RTSP integration should be possible finally :star_struck:

2021-06-14 16:26 UTC, crossan007 commented
Thank you so much for the detailed code review!  I'll try to get to it early this week (competing priorities and all) :slight_smile:

With that said - the RTSP library I wrote may also contain some similar C++ "oopses"   If you're wiling, I'd appreciate bug reports (MRs too) on that repo  😄

2021-06-15 04:51 UTC, jesserockz commented on esphome/components/rtsp_server/rtsp_server.cpp
> +  ESP_LOGCONFIG(TAG, "Beginning to set up RTSP server listener");
> config log level is only for things written in dump_config

We might need to clean up the codebase then =)

2021-06-26 13:24 UTC, crossan007 commented
I haven't forgotten about making the changes on this - Just been busy with life lately and haven't had much time for hobby stuff.

2021-08-01 17:37 UTC, Bascht74 commented
Really looking forward to it! Hopefully you get some time in the future.

2021-08-07 01:55 UTC, crossan007 commented
I've been working on with @tobix99 over Twitter a little bit, and he has made some progress on the timestamp bug I was stuck on.

Getting there!

2021-11-06 10:15 UTC, Bascht74 commented
@crossan007 Hi, I hope you can finish your work as it would be a really nice addition and solution in many ways!!!

2021-12-20 22:14 UTC, crossan007 commented
I know a lot of folks have been waiting for this, and I believe I finally have it to a working state! 🎊🎉

I still need to clean up some formatting issues, and there are certainly some improvements to be made to the underlying RTSP library I wrote for this purpose, which I'll track separately.

- https://github.com/crossan007/ESPAsyncRTSPServer-esphome/issues/2
- https://github.com/crossan007/ESPAsyncRTSPServer-esphome/issues/3

At this time, I published 0.1.0 of the Async RTSP library to PIO (https://platformio.org/lib/show/12429/ESPAsyncRTSPServer-esphome/installation), so anyone should be able to pull _this branch_ and build a ESP32 firmware.elf locally

2021-12-23 02:52 UTC, crossan007 commented
@OttoWinter @jesserockz  I think this is ready for review again :-)

2022-01-31 01:20 UTC, jesserockz requested changes
Yet to test latest version but a few things below to change

2022-01-31 01:20 UTC, jesserockz commented on esphome/components/rtsp_server/__init__.py
> +    cg.add_library("ESPAsyncRTSPServer-esphome", "^0.1.3")
I know it makes it easier, but ESPHome pins to a specific version.
Also please add username prefix in case someone else publishes the package with same name.

```suggestion
    cg.add_library("crossan007/ESPAsyncRTSPServer-esphome", "0.1.3")
```

2022-01-31 01:20 UTC, jesserockz commented on esphome/components/rtsp_server/__init__.py
> +    cg.add_define("USE_ESPASYNCRTSP")
This is not required and can be removed from the code files too.
```suggestion
```

2022-01-31 01:20 UTC, jesserockz commented on platformio.ini
> +    ESPAsyncRTSPServer-esphome@0.1.2 ; rtsp_server
```suggestion
    crossan007/ESPAsyncRTSPServer-esphome@0.1.3 ; rtsp_server
```

2022-01-31 01:32 UTC, crossan007 commented on esphome/components/rtsp_server/__init__.py
> +    cg.add_define("USE_ESPASYNCRTSP")
I had to add this to get the espressif IDF CI build to pass.

2022-04-02 04:52 UTC, stuartwishart commented
@crossan007 Hi, it would be great to see this feature merged into project.

2022-04-02 15:09 UTC, crossan007 commented
@stuartwishart  I've got this branch deployed on my ESP32's and it's _mostly_ working.  There's an intermittent reboot issue that I think is caused by something in the UDP stack, but it works otherwise.

I'll rebase on the latest develop sometime this week and seed if that fixes anything.

2022-04-03 11:30 UTC, stuartwishart commented
> I'll rebase on the latest develop sometime this week and seed if that fixes anything.

@crossan007 - Thanks for all your hard work in creating this library.

I've been testing it out over the weekend.  One issue that I've had is that it doesn't close the RTSP stream when you stop/disconnect the viewer.  This means that you can't restart the stream on the original viewer or a different one with having to restart the device.

2022-05-03 10:27 UTC, pastukhov commented
Any news?

2022-06-02 04:26 UTC, baerrs commented
I would love to see this implemented.  I would be willing to test if you are at that point.

2022-06-02 12:28 UTC, crossan007 commented
> I would love to see this implemented. I would be willing to test if you are at that point.

I have been running this on one of my ESP32 Cam's for a while now;  it does have a random (like, every 5 minutes) reboot issue which I believe is related to the UDP send routine; but otherwise, I think it's "ready".  I have not been actively working on it though, since it's "mostly working"

I'm sure there are missing features, but it's certainly an MVP

I'll try to get this rebased on the latest develop branch in the next day or two

2022-09-01 07:36 UTC, Bascht74 commented
@crossan007 I hope you will complete this because you are sooo close…

2022-12-05 03:18 UTC, pastukhov commented
That is sad

2023-03-07 13:48 UTC, crossan007 commented
@jesserockz  thanks for updating this MR and keeping it alive.

On a related note: now I have some serious guilt about having not yet finished it 😅😂

2023-05-11 21:35 UTC, max246 commented
Do you need help on finish this? I could grab a esp32_camera and help out. @crossan007

2023-07-27 00:02 UTC, caliKev commented
Is there a way to get the incomplete component?

2025-04-10 15:00 UTC, flubshi commented
Ohh, nearly two years and still not merged. I think it would be a great feature.
@jesserockz can you please take it further?

2025-05-26 19:46 UTC, DjordjeMandic commented
> Is there a way to get the incomplete component?

https://esphome.io/components/external_components.html

2025-11-03 10:31 UTC, Nejern commented
Any news?

2025-11-27 17:12 UTC, KoStard commented
This would be great!

2026-06-22 16:49 UTC, Ardumine commented
Any update?

2026-07-30 12:20 UTC, swoboda1337 commented
Closing this out: changes were requested back in January 2022 and were never addressed, and there's been no development here since — the comments since then show plenty of demand, but the camera stack has been substantially reworked in the intervening years, so this would need a ground-up redo against current dev regardless. An RTSP server would still be a genuinely welcome feature — if anyone wants to take it on, a fresh PR is the way, and there's a feature request tracker at https://github.com/esphome/feature-requests for registering interest in the meantime.

2026-07-30 12:20 UTC, closed without merging

2026-07-30 16:06 UTC, max246 commented
I feel sorry to come now but I was meant to make one last week since I saw the ticket... my current camera is not working but I should get a new esp tomorrow to fully test it: https://github.com/max246/esphome/tree/max246/rtsp-server