Climate component for Ballu air conditioners with remote model YKR-K/002E
OttoWinter/esphomeyaml pull request #1939
Opened 2021-06-18 08:43 UTC by bazuchan

# What does this implement/fix?

Climate component for Ballu air conditioners with remote model YKR-K/002E.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [*] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [*] ESP32
- [ ] ESP8266

Model of AC tested with is Ballu BSWI-12HN1/EP/15Y.
IR transceiver tested with is https://github.com/AdamKGoddard/XiaomiIR_ESPHome

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
climate:
  - platform: ballu
    name: "Living Room AC"
    receiver_id: rcvr1  # optional
```

## Checklist:
  - [*] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-06-25 22:38 UTC, glmnet requested changes
Thanks for this!
Looks good overall

2021-06-25 22:38 UTC, glmnet commented on esphome/components/ballu/climate.py
> +}
Do you plan to add more models in the near future?
While this doesn't cause much harm, maintaining models for future might just make stuff harder to maintain, so I'd say remove this and add it when needed.

2021-06-25 22:40 UTC, glmnet commented
Docs PR for this is just a new entry in the IR table models list, here: https://github.com/esphome/esphome-docs/blob/current/components/climate/ir_climate.rst

2021-06-28 08:52 UTC, bazuchan commented
Removed model, runned linter

2021-06-28 19:26 UTC, glmnet approved these changes

2021-06-28 19:26 UTC, glmnet commented
Thanks 🦙

2021-06-28 19:26 UTC, merged

2021-08-01 14:47 UTC, nightmare04 commented
Great, thx!!! Please add SLEEP button