Add stepper.set_acceleration and stepper.set_deceleration to stepper component
OttoWinter/esphomeyaml pull request #1977
Opened 2021-07-04 03:25 UTC by WeekendWarrior1

# What does this implement/fix? 

Adds set_acceleration and set_deceleration actions to the stepper component, basically exact same implementation as "stepper.set_speed".

I have a stepper motor powered blind that I send different speeds to, based on the time of day and room occupancy, and it is nice to also control the accel/decel based on the speed.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [https://github.com/esphome/feature-requests/issues/580](https://github.com/esphome/feature-requests/issues/580)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
close_action:
      - if:
          condition:
              switch.is_on: quietmode
          then:
              - stepper.set_speed:
                  id: secondaryStepper
                  speed: 300 steps/s
              - stepper.set_acceleration:
                  id: secondaryStepper
                  acceleration: 60 steps/s^2
              - stepper.set_deceleration:
                  id: secondaryStepper
                  deceleration: 60 steps/s^2
      - stepper.set_target:
          id: secondaryStepper
          target: 23200

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-07-04 19:46 UTC, jesserockz requested changes

2021-07-04 19:46 UTC, jesserockz commented on esphome/components/stepper/__init__.py
> +    template_ = await cg.templatable(config[CONF_ACCELERATION], args, cg.int32)
Ignore the fact that `speed` is an int above (Or change it too maybe)...
But the config validation and the c++ code expects a float, so the template should allow a float here too. Also below in deceleration

```suggestion
    template_ = await cg.templatable(config[CONF_ACCELERATION], args, cg.float_)
```

2021-07-05 00:40 UTC, WeekendWarrior1 commented
Replaced speed, acceleration and deceleration, seems to work fine.

2021-07-05 01:18 UTC, jesserockz approved these changes

2021-07-05 01:22 UTC, merged