Add support for IBS-TH1 External Sensor
OttoWinter/esphomeyaml pull request #1983
Opened 2021-07-04 16:35 UTC by MikkoTervala

# What does this implement/fix? 

IBS-TH1 Mini was already implemented. This update will add support for non mini models and external sensor with full backwards combability. 
IBS-TH1 and IBS-TH1 Mini send the exact same payload with internal sensors. IBS-TH1 identifies data from the external sensor with a flipped bit (mnfData.data[2] in code)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1289

## Test Environment

- [X] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-07-05 01:42 UTC, jesserockz submitted a review, later dismissed

2021-07-05 01:49 UTC, jesserockz commented
Considering you wrote:

> If an external temperature sensor is connected to the IBS-TH1, measurement from the internal sensor is not sent.
    Only one sensor will work at a time.

in the docs PR. Why do we need to have a separate `external_temperature`. Why not just publish to the same `temperature` sensor?

2021-07-07 19:04 UTC, MikkoTervala commented
Hi @jesserockz ! Thanks for taking a look at the PR.

The internal and external sensors are logically two separate sensors and can be located in different environments.
The external sensor is easily disconnected. For example in my use case the external sensor is measuring a water bath temperature, and if I disconnect the external sensor by accident the internal sensor readings should not get mixed to readings that are from the external sensor.

My latest commit has the changes recommended by lint-clang-format.

2021-07-07 20:31 UTC, jesserockz commented
@MikkoTervala that makes perfect sense then.

2021-07-07 21:53 UTC, jesserockz requested changes
Final request, then will merge =)

2021-07-07 21:53 UTC, jesserockz commented on esphome/components/inkbird_ibsth1_mini/sensor.py
> +CONF_EXT_TEMPERATURE = "ext_temperature"
Please use full names (`external_temperature`) for config options, there is no point in shortening it.

2021-07-12 11:46 UTC, MikkoTervala commented
> Final request, then will merge =)

@jesserockz Thanks for the feedback! Changes have been implemented and tested.

2021-07-12 19:57 UTC, jesserockz approved these changes
Thanks

2021-07-12 20:55 UTC, merged