Add support for the HRXL MaxSonar WR series sensors
OttoWinter/esphomeyaml pull request #2020
Opened 2021-07-15 10:35 UTC by netmikey

# What does this implement/fix? 

This adds support for the HRXL MaxSonar WR Series Ultrasonic Sensors by MaxBotix.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** n/a

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1308

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
uart:
  rx_pin: 36
  baud_rate: 9600

sensor:
  - platform: "hrxl_maxsonar_wr"
    name: "Rainwater Tank"
    filters:
      - sliding_window_moving_average:
          window_size: 12
          send_every: 12
      - or:
        - throttle: "20min"
        - delta: 0.02
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-07-15 11:49 UTC, oxan requested changes
Thanks for your contribution! Looks good, just a few minor comments below.

2021-07-15 11:49 UTC, oxan commented on esphome/components/hrxl_maxsonar_wr/hrxl_maxsonar_wr.cpp
> +  String buffer;
We prefer to use `std::string` over the Arduino `String` class in ESPHome.

2021-07-15 11:49 UTC, oxan commented on esphome/components/hrxl_maxsonar_wr/hrxl_maxsonar_wr.cpp
> +  this->flush();
Given that this sensor only reads from the UART bus, I don't think this is necessary?

2021-07-15 11:49 UTC, oxan commented on esphome/components/hrxl_maxsonar_wr/hrxl_maxsonar_wr.cpp
> +  // As specified in the sensonr's data sheet
Typo in sensor.

2021-07-15 15:00 UTC, netmikey commented on esphome/components/hrxl_maxsonar_wr/hrxl_maxsonar_wr.cpp
> +  this->flush();
Yes, right.

2021-07-15 15:00 UTC, netmikey commented on esphome/components/hrxl_maxsonar_wr/hrxl_maxsonar_wr.cpp
> +  // As specified in the sensonr's data sheet
Fixed.

2021-07-15 15:01 UTC, netmikey commented on esphome/components/hrxl_maxsonar_wr/hrxl_maxsonar_wr.cpp
> +  String buffer;
I replaced it with the `std::string`.

2021-07-15 15:30 UTC, oxan approved these changes

2021-07-26 09:10 UTC, OttoWinter commented on esphome/components/hrxl_maxsonar_wr/hrxl_maxsonar_wr.cpp
> +    std::string buffer;
The buffer should be stored inside the component - otherwise the read will fail if the loop just happens to fall in the middle of a transmission.

2021-07-26 09:10 UTC, OttoWinter commented on esphome/components/hrxl_maxsonar_wr/hrxl_maxsonar_wr.cpp
> +    for (int i = 0; i < MAX_DATA_LENGTH_BYTES; i++) {
Instead of this loop, then you can just keep appending to the component `buffer`, and when `buffer.length()` equals the constant, read it. See for example how cse7766 does it.

2021-07-28 15:36 UTC, netmikey commented on esphome/components/hrxl_maxsonar_wr/hrxl_maxsonar_wr.cpp
> +    std::string buffer;
Right, I fixed that.

2021-07-28 16:00 UTC, netmikey commented on esphome/components/hrxl_maxsonar_wr/hrxl_maxsonar_wr.cpp
> +    for (int i = 0; i < MAX_DATA_LENGTH_BYTES; i++) {
Since each data block from this sensor ends with `ASCII_CR`, I used that to determine when the read is done and the buffer needs to be cleared. Like in the cse7766 component, I moved the parsing / checking logic to its own method.

2021-07-29 09:07 UTC, OttoWinter approved these changes
Code LGTM, thanks :+1: 

One thing I missed before: Please also add it to one of the configs in the tests folder (that only tests if the component compiles)

2021-07-29 09:29 UTC, netmikey commented
> Please also add it to one of the configs in the tests folder (that only tests if the component compiles)

Sure, done. Thanks for your time 👍

2021-07-29 09:37 UTC, merged