Nexa433
OttoWinter/esphomeyaml pull request #2037
Opened 2021-07-19 05:59 UTC by GruffyPuffy

# What does this implement/fix? 

Support for Nexa (433MHz) devices using remote receiver/transmitter by implementing a new Nexa codec.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/934

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs# COMING SOON

## Test Environment

- [ ] ESP32
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
esphome:
   name: nexa_bridge
   platform: ESP8266
   board: esp01_1m

wifi:
   ssid: "YOUR SSID"
   password: "YOUR PASSWD"

# Enable logging
logger:

web_server:
  port: 80

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

remote_receiver:
   pin:
     number: 4
   dump:
   - nexa
   filter: 50us
   idle: 4ms

remote_transmitter:
  pin: 5
  carrier_duty_percent: 100%

binary_sensor:
  - platform: remote_receiver
    name: "Nexa Remote 2 Open"
    internal: yes
    nexa:
      device: 0x4C1C12
      state: 1
      group: 0
      channel: 1
      level: 0
    on_press:
      - binary_sensor.template.publish:
          id: NexaRemote2
          state: ON
  - platform: remote_receiver
    name: "Nexa Remote 2 Closed"
    internal: yes
    nexa:
      device: 0x4C1C12
      state: 0
      group: 0
      channel: 1
      level: 0
    on_press:
      - binary_sensor.template.publish:
          id: NexaRemote2
          state: OFF
  - platform: template
    name: "NexaRemote2 State"
    device_class: window
    id: NexaRemote2

output:
  - platform: template
    id: tilda_slinga_output
    type: binary

    write_action:
      - if:
          condition:
            light.is_on: tilda_slinga_light
          then:
            remote_transmitter.transmit_nexa:
              device: 0x38DDB4A
              state: 1
              group: 0
              channel: 15
              level: 0
              repeat: 5
          else:
            remote_transmitter.transmit_nexa:
              device: 0x38DDB4A
              state: 0
              group: 0
              channel: 15
              level: 0
              repeat: 5

  - platform: template
    id: vardagsrum_dimable_slinga_output
    type: float

    write_action:
      - if:
          condition:
            lambda: return (state > 0);
          then:
            remote_transmitter.transmit_nexa:
              device: 0x19A5470
              state: 2
              group: 0
              channel: 0
              level: !lambda return state*15;
              repeat: 5
          else:
            remote_transmitter.transmit_nexa:
              device: 0x19A5470
              state: 0
              group: 0
              channel: 0
              level: 0
              repeat: 5

light:
  - platform: binary
    name: "Tilda Slinga"
    id: tilda_slinga_light
    output: tilda_slinga_output

  - platform: monochromatic
    name: "Vardagsrum Slinga"
    id: vardagsrum_dimable_slinga_light
    output: vardagsrum_dimable_slinga_output
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-07-29 17:13 UTC, wt4711 commented
@GruffyPuffy, just tried your modified receiver (dump and sensor platform) on a Sonoff RFR3 (data output from the radio chip wired to GPIO4). It works fine with Nexa WT-2 (two button battery wall switch) and a Nexa MRYT-1805 (battery wall dimmer)!

Some on/off events from the wall switch are missed, but this happens only when I click the buttons a very short time, and I believe the sender is to blame in those cases.

Great and much needed work! I hope this will be included in the distribution soon. I'm not familiar with the development of ESPhome, but are willing to help with more tests.

2021-07-29 17:25 UTC, GruffyPuffy commented
> @GruffyPuffy, just tried your modified receiver (dump and sensor platform) on a Sonoff RFR3 (data output from the radio chip wired to GPIO4). It works fine with Nexa WT-2 (two button battery wall switch) and a Nexa MRYT-1805 (battery wall dimmer)!
> 
> Some on/off events from the wall switch are missed, but this happens only when I click the buttons a very short time, and I believe the sender is to blame in those cases.
> 
> Great and much needed work! I hope this will be included in the distribution soon. I'm not familiar with the development of ESPhome, but are willing to help with more tests.

Thanx for testing! 
I have two of the Sonoff RF-bridge and they behave a little different. There are lots of spikes in RX on one of them and that one is a little worse...however it usually works. I do think that what must be improved is the filtering in the IRQ. Hopefully I get some time for this. If you like, you can play with the RX timings in the source and see if you find better values etc.

2021-08-10 23:50 UTC, jesserockz requested changes
There is a lot of commented code here. Can you either remove it or make it functional? The logs can be made VV or V, but other stuff should be removed please.

2021-08-10 23:50 UTC, jesserockz commented on esphome/components/remote_base/nexa_protocol.cpp
> +  // ESP_LOGD(TAG, "1 ");
Please don't add commented code. You can add this (and all the rest) as `ESP_LOGVV` so its activated with the log level.

2021-08-10 23:50 UTC, jesserockz commented on esphome/components/remote_base/nexa_protocol.cpp
> +  ESP_LOGD(TAG, "ENCODE NEXA: Done");
This should not really be any higher than VERBOSE
```suggestion
  ESP_LOGV(TAG, "ENCODE NEXA: Done");
```

2021-08-12 17:17 UTC, Swiftwork commented on esphome/components/remote_base/nexa_protocol.cpp
> +  // dst->mark(BIT_HIGH_US);
Why did you choose to send a final ZERO bit instead of a PAUSE bit? I would imagine that if a user configures the "repeat" value they would need to specify the time of at least `TX_HEADER_HIGH_US * 40 - TX_BIT_ZERO_LOW_US` instead of 0.

2021-08-12 17:54 UTC, GruffyPuffy commented on esphome/components/remote_base/nexa_protocol.cpp
> +  ESP_LOGD(TAG, "ENCODE NEXA: Done");
Will do! I used a lot during dev, but it is not needed anymore.

2021-08-12 17:57 UTC, GruffyPuffy commented on esphome/components/remote_base/nexa_protocol.cpp
> +  // dst->mark(BIT_HIGH_US);
The specifications I saw, and my testing, as well as when I captured Nexa devices on my oscilloscope showed  that it should end with a zero. I tested various stuff and forgot to remove non-used code. Will clean up the code. The pause (i.e. silence) is controlled by the calling layer above this.

2021-08-12 19:18 UTC, Swiftwork commented on esphome/components/remote_base/nexa_protocol.cpp
> +  // dst->mark(BIT_HIGH_US);
Ah I see, I think I have been referring to the old Nexa protocol. You can disregard this :)

2021-08-12 19:21 UTC, Swiftwork commented
I have added this PR to my esphome using external components and can verify that it works for both my Nexa devices and my Telldus which uses the same protocol. Well done!

2021-11-16 09:01 UTC, wt4711 commented
I have been running this since July (the receiver), and it has been working flawlessly! Would be really nice to have this included in the distribution. I'm sure it would be useful for a lot of people who might just give up using Nexa RF devices otherwise.

2021-11-16 18:52 UTC, jesserockz commented on esphome/components/remote_base/__init__.py
> +
```suggestion

```

2021-11-17 03:25 UTC, jesserockz commented on esphome/components/remote_base/__init__.py
```suggestion
    }
)


```

2022-01-10 09:58 UTC, jesserockz commented on esphome/components/remote_base/__init__.py
```suggestion
    }
)


```

2022-01-10 10:02 UTC, jesserockz commented on esphome/components/remote_base/nexa_protocol.cpp
> +      // return {};
```suggestion
```

2022-01-10 10:02 UTC, jesserockz approved these changes

2022-01-10 10:35 UTC, merged