Add SDP3x sensor
OttoWinter/esphomeyaml pull request #2064
Opened 2021-07-25 05:16 UTC by Azimath

# What does this implement/fix? 

Adds a component to support the SDP3x sensor, an I2C differential pressure sensor useful for measuring small pressure differences like the drop across an HVAC filter.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
  - platform: sdp3x
    name: "HVAC Filter Pressure drop"
    id: filter_pressure
    update_interval: 5s
    accuracy_decimals: 3
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-07-25 22:15 UTC, jesserockz requested changes

2021-07-25 22:15 UTC, jesserockz commented on esphome/components/sdp3x/sdp3x.cpp
> +  this->set_timeout("pressure", 5, [this]() { this->read_pressure_(); });
I don't really see the need for this?

```suggestion
  this->read_pressure_();
```

2021-07-25 22:15 UTC, jesserockz commented on esphome/components/sdp3x/sensor.py
> +DEPENDENCIES = ["i2c"]
Please add yourself as a codeowner and run `script/build_codeowners.py`
```suggestion
CODEOWNERS = ["@Azimath"]
DEPENDENCIES = ["i2c"]
```

2021-07-25 22:15 UTC, jesserockz commented on esphome/components/sdp3x/sensor.py
> +    yield sensor.register_sensor(var, config)
**Optional** change but a good place to inform you of the async changes in the codebase =)
```suggestion
async def to_code(config):
    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)
    await i2c.register_i2c_device(var, config)
    await sensor.register_sensor(var, config)
```

2021-07-25 22:15 UTC, jesserockz commented on esphome/components/sdp3x/sensor.py
> +    sensor.sensor_schema(UNIT_HECTOPASCAL, ICON_EMPTY, 3, DEVICE_CLASS_PRESSURE)
Also makes this a statistic that has min/max/average in Home Assistant (needs the import above too)
```suggestion
    sensor.sensor_schema(
        UNIT_HECTOPASCAL, 
        ICON_EMPTY, 
        3, 
        DEVICE_CLASS_PRESSURE, 
        STATE_CLASS_MEASUREMENT,
    )
```

2021-07-25 22:15 UTC, jesserockz commented on esphome/components/sdp3x/sensor.py
> +    UNIT_HECTOPASCAL,
```suggestion
    STATE_CLASS_MEASUREMENT,
    UNIT_HECTOPASCAL,
```

2021-07-25 22:15 UTC, jesserockz commented on esphome/components/sdp3x/sdp3x.cpp
> +  int16_t pressure_raw = (int16_t)((data[0] << 8) | data[1]);
```suggestion
  int16_t pressure_raw = encode_uint16(data[0], data[1]);
```

2021-07-25 22:15 UTC, jesserockz commented on esphome/components/sdp3x/sdp3x.cpp
> +}
```suggestion
void SDP3XComponent::dump_config() {
  LOG_SENSOR("  ", "SDP3X", this);
  LOG_I2C_DEVICE(this);
  if (this->is_failed()) {
    ESP_LOGE(TAG, "  Connection with SDP3X failed!");
  }
  LOG_UPDATE_INTERVAL(this);
}
```

2021-07-25 23:11 UTC, Azimath commented on esphome/components/sdp3x/sensor.py
> +    UNIT_HECTOPASCAL,
Done, not sure why github says otherwise

2021-07-25 23:12 UTC, Azimath commented on esphome/components/sdp3x/sensor.py
> +DEPENDENCIES = ["i2c"]
Done, github doesn't see it as outdated for some reason

2021-07-26 05:29 UTC, jesserockz approved these changes

2021-07-26 08:47 UTC, OttoWinter commented on esphome/components/sdp3x/sdp3x.cpp
> +  ESP_LOGD(TAG, "Got raw pressure=%d, scale factor =%.3f ", pressure_raw, pressure_scale_factor_);
```suggestion
  ESP_LOGV(TAG, "Got raw pressure=%d, scale factor =%.3f ", pressure_raw, pressure_scale_factor_);
```

Nit: should be v log level

2021-07-26 08:48 UTC, OttoWinter reviewed
LGTM :+1: Thanks!

2021-07-29 08:57 UTC, merged