Implement AS3935 calibration and antenna trimming
OttoWinter/esphomeyaml pull request #2084
Opened 2021-07-28 16:26 UTC by marek-obuchowicz

# What does this implement/fix? 

AS3935 sensor provides automatic calibration and antenna trimming mode. This change implements support for those features.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/451

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
[...]pending - let me know if you're going to accept this PR; if yes - i'm going to add documentation and update this PR accordingly.

## Test Environment

- [X] ESP32

## Example entry for `config.yaml`:
```yaml
as3935_i2c:
  irq_pin: GPIO5
  indoor: False
  noise_level: 1
  spike_rejection: 2
  mask_disturber: False
  div_ratio: 0
  capacitance: 0
  watchdog_threshold: 2
  trim_antenna: False
  calibration: True
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  I might need assistance with that part...

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-07-28 18:45 UTC, oxan requested changes

2021-07-28 18:45 UTC, oxan commented on esphome/components/as3935/as3935.cpp
> +    ESP_LOGCONFIG(TAG, "  Antenna trimming: ENABLED - lighting detecion is not working in this mode");
```suggestion
    ESP_LOGCONFIG(TAG, "  Antenna trimming: ENABLED - lightning detecion is not working in this mode");
```

2021-07-28 18:45 UTC, oxan commented on esphome/components/as3935/as3935.cpp
> +  ESP_LOGI(TAG, "Starting oscillators calibration...");
I think it makes more sense to log before writing to the register, that way, if the write fails it's clear what it's related to.

2021-07-28 18:45 UTC, oxan commented on esphome/components/as3935/as3935.cpp
> +      this->calibrate_oscillator();
```suggestion
  } else if (this->calibration_) {
    this->calibrate_oscillator();
```

2021-07-28 18:45 UTC, oxan commented on esphome/components/as3935/as3935.cpp
> +  reg_val &= ~DIV_MASK;
There's the `read_register_` method, so that you don't have to do this masking manually everywhere:

```suggestion
  uint8_t reg_val = this->read_register_(INT_MASK_ANT, DIV_MASK);
```

2021-07-28 18:45 UTC, oxan commented on esphome/components/as3935/as3935.cpp
> +  return ((reg_val &= ~CAP_MASK) * 8);  // Multiplied by 8pF
```suggestion
  uint8_t reg_val = this->read_register_(FREQ_DISP_IRQ, CAP_MASK) * 8;  // Multiplied by 8pF
```

2021-07-28 18:45 UTC, oxan commented on esphome/components/as3935/as3935.cpp
> +  }
```suggestion
  this->write_register(FREQ_DISP_IRQ, OSC_MASK, _state, 4 + osc);
```

Given that this is always called with constant arguments, the check on `osc` isn't necessary and this could probably be inlined in the callers.

2021-07-28 18:45 UTC, oxan commented on esphome/components/as3935/as3935.cpp
> +  reg_val_trco >>= 6;
I think it's cleaner to define a new `CALIB_NOK_MASK = 0xBF` and use `read_register_`, so this bit-fiddling isn't necessary and it's clear that you're checking the NOK flag instead of the DONE flag.

2021-07-28 18:45 UTC, oxan commented on esphome/components/as3935/__init__.py
> +        cv.Optional(CONF_TRIM_ANTENNA, default=False): cv.boolean,
Maybe it's better to call this antenna tuning to be consistent with the datasheet.

2021-07-28 18:45 UTC, oxan commented on esphome/components/as3935/as3935.h
> +  uint8_t get_div_ratio();
For consistency with the existing `write_div_ratio` method, this should probably be `read_div_ratio`.

2021-07-28 18:45 UTC, oxan commented on esphome/components/as3935/as3935.h
> +  uint8_t get_tune_cap();
Same here, should probably be `read_capacitance`.

2021-07-29 09:28 UTC, marek-obuchowicz commented on esphome/components/as3935/as3935.cpp
> +    ESP_LOGCONFIG(TAG, "  Antenna trimming: ENABLED - lighting detecion is not working in this mode");
Thanks for deep review, @oxan - I'll get back to this PR with your suggested fixes 👍

2021-07-29 09:29 UTC, marek-obuchowicz commented on esphome/components/as3935/__init__.py
> +        cv.Optional(CONF_TRIM_ANTENNA, default=False): cv.boolean,
Shall we use "Antenna tune" or "Antenna tuning" form?

2021-07-29 09:31 UTC, oxan commented on esphome/components/as3935/__init__.py
> +        cv.Optional(CONF_TRIM_ANTENNA, default=False): cv.boolean,
The configuration option and methods should be named `tune_antenna`, what you do in log messages doesn't matter that much.

2021-11-04 01:35 UTC, closed without merging