Added graphing component
OttoWinter/esphomeyaml pull request #2109
Opened 2021-08-02 09:45 UTC by synco

# What does this implement/fix? 
Adds the ability to plot some sensor data on the actual hardware screen. eg.
![graph_screen](https://user-images.githubusercontent.com/386352/127839907-d9af1224-4a60-4a95-8177-8debee922030.png)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP8266

```yaml
graph:
  - id: small_temperature_graph
    sensor: my_temperature
    update_interval: 24s
    width: 151
    height: 51
  - id: small_pressure_graph
    sensor: my_pressure
    update_interval: 24s
    width: 151
    height: 51
    border: false
    line_type: DOTTED
    min_range: 2
    x_grid: 25.0    # pixels/div
    y_grid: 1.0     # hPa/div
```
(not sure image matches config exactly anymore)

```yaml
display:
  - platform: ...
    # ...
    lambda: |-
      // Draw the graph at position [x=10,y=20]
      it.graph(10, 20, id(small_temperature_graph));
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-08-02 22:46 UTC, jesserockz commented on esphome/components/display/display_buffer.h
> +class Graph : public PollingComponent {
Why do you have the `Graph` class in here and not in the `components/graph` folder?

2021-08-02 22:46 UTC, jesserockz commented on esphome/components/display/display_buffer.h
> +class Graph : public PollingComponent {
Same for HistoryData (should be in with graph)

2021-08-02 22:49 UTC, synco commented on esphome/components/display/display_buffer.h
> +class Graph : public PollingComponent {
I used the "Image" as example, and thought I'd get head-aches trying to work out the build system.

2021-08-02 22:50 UTC, synco commented on esphome/components/display/display_buffer.h
> +class Graph : public PollingComponent {
Is it easy?? -since I'm new at this.

2021-08-02 22:51 UTC, jesserockz commented on esphome/components/display/display_buffer.h
> +class Graph : public PollingComponent {
Ah ok, thats fine.

2021-08-02 23:05 UTC, jesserockz commented on script/build_codeowners.py
> +            f"Cannot find component {name}. Make sure current path is pip installed ESPHome, or pip3 uninstall esphome"
Please don't change this line as a part of this PR.

The issue you faced also shows that you need to use virtualenvs for your different environments, dev or pip instlaled version

```suggestion
           f"Cannot find component {name}. Make sure current path is pip installed ESPHome"
```

2021-08-02 23:28 UTC, jesserockz commented on script/build_codeowners.py
> +           f"Cannot find component {name}. Make sure current path is pip installed ESPHome"
```suggestion
            f"Cannot find component {name}. Make sure current path is pip installed ESPHome"
```

2021-08-03 00:14 UTC, jesserockz requested changes
A few things below, and also If you could change some of the LOG levels to be VERBOSE perhaps, especially because they are in the redraw.

Also instead of polling the sensor, you can attach to its callbacks 
```c++
this->sensor_->add_on_state_callback([this](float state) { this->data_->take_sample(state); });
``` 

to get notified when there is new data and then you dont need this to be a polling component, but only calculate the pixels when a display renders it.

2021-08-03 00:14 UTC, jesserockz commented on esphome/components/graph/__init__.py
> +        cv.Optional(CONF_Y_GRID, default=float("nan")): cv.float_,
(1/3) Don't use `nan` defaults, just use no default and check if the key is in the config, and initialize the variables to NAN in c++ (see other comments/suggestions)
```suggestion
        cv.Optional(CONF_MIN_VALUE): cv.float_,
        cv.Optional(CONF_MAX_VALUE): cv.float_,
        cv.Optional(CONF_MIN_RANGE): cv.float_,
        cv.Optional(CONF_MAX_RANGE): cv.float_,
        cv.Optional(CONF_LINE_THICKNESS, default=3): cv.positive_int,
        cv.Optional(CONF_LINE_TYPE, default="SOLID"): cv.enum(LINE_TYPE, upper=True),
        cv.Optional(CONF_X_GRID): cv.float_,
        cv.Optional(CONF_Y_GRID): cv.float_,
```

2021-08-03 00:14 UTC, jesserockz commented on esphome/components/graph/__init__.py
> +                    cv.Optional(CONF_MAX_RANGE, default=float("nan")): cv.float_,
Same here

2021-08-03 00:14 UTC, jesserockz commented on esphome/components/graph/__init__.py
> +    cg.add(var.set_min_value(config[CONF_MIN_VALUE]))
(2/3) Like this, but for all optional fields with no defaults

```suggestion
    if CONF_MIN_VALUE in config:
        cg.add(var.set_min_value(config[CONF_MIN_VALUE]))
```

2021-08-03 00:14 UTC, jesserockz commented on esphome/components/display/display_buffer.h
> +  float min_value_;
(3/3) And set these to be NAN by default.
```suggestion
  float min_value_{NAN};
```

2021-08-03 00:14 UTC, jesserockz commented on esphome/components/display/display_buffer.cpp
> +    : length_(length), count_(0), min_(NAN), max_(NAN), recent_min_(NAN), recent_max_(NAN) {
Dont initialize these from static variables, use similar to below with:
```c++
  int count_{0};
  float min_{NAN};
```

2021-08-03 04:03 UTC, synco commented on esphome/components/graph/__init__.py
> +        cv.Optional(CONF_Y_GRID, default=float("nan")): cv.float_,
Is that:
a) no defaults in *.py, (happy - with that)
b) no float("nan") yet other defaults ok. (I find that confusing)
c) other

2021-08-03 04:29 UTC, synco commented on esphome/components/graph/__init__.py
> +        cv.Optional(CONF_Y_GRID, default=float("nan")): cv.float_,
I like the idea of using a sensor callback, yet suspect using a callback on sensor state would cause issues -as sensor poll rate is most likely different to the graph sampling rate.

2021-08-03 12:06 UTC, OttoWinter commented on esphome/components/graph/__init__.py
> +        cv.Optional(CONF_Y_GRID, default=float("nan")): cv.float_,
> I like the idea of using a sensor callback, yet suspect using a callback on sensor state would cause issues -as sensor poll rate is most likely different to the graph sampling rate.

I agree we should use sensor callback, then we also don't need the `update_interval` option because it just uses what the sensor has itself.

Yes the sensor/display refresh rates won't match, so I think we should add an option to control the x-scaling (essentially, how long in time units the history should be).

2021-08-03 12:12 UTC, OttoWinter reviewed
Thanks, this looks like a very useful feature for displays!

I left you some comments, can you take a look?

Especially for the way the x-scaling is done I think we can improve things - for users it's much more natural to say "I want to display the last 1h of data". Perhaps we can implement it that way too. If needed I can also help and write some code for that, let me know.

2021-08-03 12:12 UTC, OttoWinter commented on esphome/components/display/display_buffer.cpp
> +      this->draw_pixel_at(x + img_x, y + img_y, graph->get_pixel(img_x, img_y) ? color_on : color_off);
Hmm, this seems inefficient (having the `Graph` store the data internally as an image). Why not just compute the pixel data in here like it's currently done in `Graph::redraw_`?

2021-08-03 12:12 UTC, OttoWinter commented on esphome/components/graph/__init__.py
> +    # await cg.register_component(var, config)
Yes you should use register_component. Note the error is likely because `Graph_ = display.display_ns.class_("Graph")` is incorrect (should have `cg.PollingComponent` added because that's the C++ class's parent class)

2021-08-03 12:12 UTC, OttoWinter commented on esphome/components/graph/__init__.py
> +        cv.Optional(CONF_MIN_RANGE): cv.float_,
What's the difference between range and value?

2021-08-05 11:48 UTC, synco commented on esphome/components/graph/__init__.py
> +        cv.Optional(CONF_MIN_RANGE): cv.float_,
Min and max values can be used the set the upper and lower limits of the y-axis, Range is used to limit the relative span on the y-axis. eg. Barometric values can range from 970 - 1040 hPa, yet usually only a +-3 hPa change is usual per day. If min/max was used you'd probably not see much fluctuation in a day, so setting max_range to say 5 (and not setting min_value or max_value) will allow you to see the smallest fluctuations. If min_range was set to 5 as-well, the grid will be fixed spacing, making it easy to see if there is abnormal fluctuations, (at the chance some data may be clipped).

2021-08-05 23:54 UTC, synco commented on esphome/components/graph/__init__.py
> +        cv.Optional(CONF_Y_GRID, default=float("nan")): cv.float_,
Done

2021-08-10 19:30 UTC, jesserockz commented on esphome/components/graph/graph.cpp
> +}
```suggestion
void Graph::dump_config() { ESP_LOGCONFIG(TAG, "Graph for sensor %s", sensor_->get_name().c_str()); }
```

2021-08-10 19:30 UTC, jesserockz approved these changes

2021-08-20 15:48 UTC, oxan reviewed
This is a cool feature! Two small things I noticed.

2021-08-20 15:48 UTC, oxan commented on esphome/components/graph/__init__.py
> +    #     cg.add(var.set_axis(axes))
If nothing is done with the `CONF_AXES` setting yet, it shouldn't be accepted yet. It can only confuse users :)

2021-08-20 15:48 UTC, oxan commented on esphome/components/graph/graph.cpp
> +HistoryData::~HistoryData() { delete (this->data_); }
```suggestion
HistoryData::~HistoryData() { delete[] (this->data_); }
```

2021-08-25 10:28 UTC, synco commented on esphome/components/graph/__init__.py
> +    #     cg.add(var.set_axis(axes))
Removed the unused CONF_AXES.

2021-08-25 10:33 UTC, synco commented on esphome/components/graph/graph.cpp
> +HistoryData::~HistoryData() { delete (this->data_); }
Thanks for catching that.

2021-09-11 12:33 UTC, oxan requested changes

2021-09-11 12:33 UTC, oxan commented on esphome/components/display/display_buffer.h
> +#include "esphome/components/sensor/sensor.h"
Why is this one necessary?

2021-09-11 12:33 UTC, oxan commented on esphome/components/graph/__init__.py
> +        cv.Optional(CONF_COLOR): cv.use_id(color.ColorStruct),  # FIX
Fix what? :smile:

2021-09-11 12:33 UTC, oxan commented on esphome/components/graph/__init__.py
> +    return _relocate_fields_to_subfolder(config, CONF_TRACES, GRAPH_TRACE_SCHEMA)
I'm wondering, is it actually useful to allow the traces to be specified directly in the top-level schema, or will it just be confusing for users? It certainly causes a lot of complication here. 

Personally I lean towards it being unnecessarily confusing, but maybe someone has a good argument for having it?

2021-09-11 12:33 UTC, oxan commented on esphome/components/graph/__init__.py
> +    # await cg.register_component(var, config)           # Needed?
Yes, this is needed, otherwise `setup()` won't get called, and `dump_config()` won't be called on new API connections.

2021-09-11 12:33 UTC, oxan commented on esphome/components/graph/graph.h
> +  };
```suggestion
  }
```

2021-09-11 12:33 UTC, oxan commented on esphome/core/defines.h
> +
This seems to be a merge error, these are already defined higher up in the file.

2021-09-15 11:10 UTC, synco commented on esphome/components/graph/__init__.py
> +    # await cg.register_component(var, config)           # Needed?
Confused, it seems to work just fine with it commented out, and causes this error when included.
``` yaml
  File "/home/synco/projects/esp/esphome-git/esphome/components/graph/__init__.py", line 155, in to_code
    await cg.register_component(var, config)   # FIX: confused - causes issues yet some say it's needed
  File "/home/synco/projects/esp/esphome-git/esphome/cpp_helpers.py", line 54, in register_component
    raise ValueError(
ValueError: Component ID temperature_graph was not declared to inherit from Component, or was registered twice. Please create a bug report with your configuration.

```

2021-09-15 16:05 UTC, oxan commented on esphome/components/graph/__init__.py
> +    # await cg.register_component(var, config)           # Needed?
That error is because you haven't defined the `Graph` class to inherit from `Component` in Python. Line 38 should be this instead:
```python
Graph_ = graph_ns.class_("Graph", cg.Component)
```

The reason it works fine with it commented out is that the only thing your `setup()` does is call `trace->init()`, but you also call that from `add_trace`; so not calling `setup()` doesn't hurt anything currently. You'll notice that `dump_config()` isn't ran on new API connections though.

2021-09-16 10:22 UTC, synco commented
What has changed causing this to fail the checks?? - what's the solution?

2021-09-16 10:24 UTC, synco commented on esphome/components/graph/__init__.py
> +    return _relocate_fields_to_subfolder(config, CONF_TRACES, GRAPH_TRACE_SCHEMA)
I allow all top-level configuration, in-case you only have a signal trace.

2021-09-16 10:38 UTC, oxan commented
> What has changed causing this to fail the checks?? - what's the solution?

We've enabled the `cppcoreguidelines-owning-memory` check (see #1891) to discourage the use of manual memory management, as that makes it easy to introduce memory leaks or use-after-free bugs (for example, your `HistoryData` object accesses freed memory if it's copy-constructed from a object that's then deleted). Instead, you should use smart pointers or STL containers. 

In your case, I would just convert the `data_` member of `HistoryData` to be a `std::vector<float>`. (That loses the graceful out-of-memory error, but it didn't work properly anyway, as `Graph::draw` unconditionally reads from the `data_` array, which would be a null pointer dereference in a out-of-memory situation).

2021-09-18 12:52 UTC, oxan approved these changes
Thanks! It looks good now, just one minor thing I noticed:

2021-09-18 12:52 UTC, oxan commented on esphome/components/graph/graph.h
> +  }
Traces are also initialized in `setup()`. To me it _seems_ harmless to initialize them twice, but it's cleaner to not do it:
```suggestion
  void add_trace(GraphTrace *trace) { traces_.push_back(trace); }
```

2021-09-20 07:27 UTC, jesserockz approved these changes

2021-09-20 07:29 UTC, jesserockz approved these changes

2021-09-20 07:29 UTC, merged