Add initial support for m5stack_4relay
OttoWinter/esphomeyaml pull request #2112
Opened 2021-08-02 23:40 UTC by brotherdust

Signed-off-by: Jarad Olson <brotherdust@gmail.com>

# What does this implement/fix? 

Adds support for the [M5Stack 4Relay](https://docs.m5stack.com/en/unit/4relay?id=description)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [X] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:
```yaml
m5stack_4relay:
  i2c_id: i2c_1
  address: 0x26
switch:
  - platform: m5stack_4relay
    id: relay_1
    channel: 0
    name: ${disp_name} Relay 1
  - platform: m5stack_4relay
    id: relay_2
    channel: 1
    name: ${disp_name} Relay 2
  - platform: m5stack_4relay
    id: relay_3
    channel: 2
    name: ${disp_name} Relay 3
  - platform: m5stack_4relay
    id: relay_4
    channel: 3
    name: ${disp_name} Relay 4
  - platform: restart
    name: ${disp_name} Restart

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-08-03 11:58 UTC, OttoWinter reviewed
Hi, thanks for the contribution!

I left you some comments. Can you also check the errors the lint system found in the files tab and fix those, thanks (you can run those tests also locally with `script/quicklint`, see contribution guides of how to run that)

2021-08-03 11:58 UTC, OttoWinter commented on esphome/components/m5stack_4relay/m5stack_4relay.h
> +    extern uint8_t component_status;
Move this into the `M5STACK4RELAYSwitchComponent` class as a class member. We shouldn't use global variables for this (so that for example multiple of these boards work connected to one device)

2021-08-03 11:58 UTC, OttoWinter commented on esphome/components/m5stack_4relay/m5stack_4relay.h
> +        //   delay(conversion);
No commented out code please

2021-08-03 11:58 UTC, OttoWinter commented on esphome/components/m5stack_4relay/__init__.py
> +    # cg.add_library("adafruit/Adafruit M5STACK4RELAY", "1.0.7")
No commented out code please

2021-08-03 11:58 UTC, OttoWinter commented on esphome/components/m5stack_4relay/m5stack_4relay.cpp
> +      // this->address_;
No commented out code please.

2021-08-03 11:58 UTC, OttoWinter commented on esphome/components/m5stack_4relay/m5stack_4relay.cpp
> +      return c;
```suggestion
      return new M5STACK4RELAYChannel(this, channel);
```

2021-08-03 11:58 UTC, OttoWinter commented on esphome/components/m5stack_4relay/m5stack_4relay.cpp
> +      // We'll just remap it here. The best way to do this would probably be a lshift(channel) mod(4).
Or... `channel = 3 - channel` :wink:

2021-08-03 11:58 UTC, OttoWinter commented on esphome/components/m5stack_4relay/m5stack_4relay.cpp
> +      if (!this->parent_->write_byte(this->address_, RELAY_CONTROL_REG, component_status))
```suggestion
      return this->parent_->write_byte(this->address_, RELAY_CONTROL_REG, component_status);
```

2021-08-03 11:58 UTC, OttoWinter commented on esphome/components/m5stack_4relay/m5stack_4relay.h
> +      } error_code_{NONE};
This isn't used anywhere

2021-08-19 19:04 UTC, brotherdust commented on esphome/components/m5stack_4relay/m5stack_4relay.h
> +    extern uint8_t component_status;
Done

2021-08-19 19:04 UTC, brotherdust commented on esphome/components/m5stack_4relay/__init__.py
> +    # cg.add_library("adafruit/Adafruit M5STACK4RELAY", "1.0.7")
Done

2021-08-19 19:04 UTC, brotherdust commented on esphome/components/m5stack_4relay/m5stack_4relay.h
> +        //   delay(conversion);
Done

2021-08-19 19:04 UTC, brotherdust commented on esphome/components/m5stack_4relay/m5stack_4relay.cpp
> +      // this->address_;
Done

2021-08-19 19:04 UTC, brotherdust commented on esphome/components/m5stack_4relay/m5stack_4relay.cpp
> +      return c;
Done

2021-08-19 19:05 UTC, brotherdust commented on esphome/components/m5stack_4relay/m5stack_4relay.cpp
> +      if (!this->parent_->write_byte(this->address_, RELAY_CONTROL_REG, component_status))
Done

2021-08-19 19:05 UTC, brotherdust commented on esphome/components/m5stack_4relay/m5stack_4relay.cpp
> +      // We'll just remap it here. The best way to do this would probably be a lshift(channel) mod(4).
Done

2021-08-19 19:05 UTC, brotherdust commented on esphome/components/m5stack_4relay/m5stack_4relay.h
> +      } error_code_{NONE};
Fixed

2021-09-13 18:49 UTC, oxan requested changes

2021-09-13 18:49 UTC, oxan commented on esphome/components/m5stack_4relay/m5stack_4relay.h
> +  uint8_t component_status;
I don't see why this variable has to be public, or even why it has to be a member variable at all. All usages seem to be able to safely be converted to a local variable.

2021-09-13 18:49 UTC, oxan commented on esphome/components/m5stack_4relay/m5stack_4relay.h
> +  M5STACK4RELAYSwitchComponent() {}
Empty constructor can be left out.

2021-09-13 18:49 UTC, oxan commented on esphome/components/m5stack_4relay/m5stack_4relay.h
> +  void get_status(uint8_t *state);
Can't this just return `uint8_t`?

2021-09-13 18:50 UTC, oxan commented
Additionally, could you please run `script/build_codeowners.py`, so that the `CODEOWNERS` file is up-to-date? :)

2021-12-20 01:39 UTC, closed without merging