Add get_safe_mode_boot_count method
OttoWinter/esphomeyaml pull request #2115
Opened 2021-08-03 21:50 UTC by alexyao2015

# What does this implement/fix? 
Allows public access to boot count to allow for automations based on the current boot count. 

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-08-03 22:32 UTC, jesserockz requested changes

2021-08-03 22:32 UTC, jesserockz commented on esphome/components/ota/ota_component.cpp
> +uint32_t OTAComponent::get_safe_mode_boot_count() { return this->safe_mode_rtc_value_; }
```suggestion
uint32_t OTAComponent::get_safe_mode_boot_count() const { return this->safe_mode_rtc_value_; }
```

2021-08-03 22:32 UTC, jesserockz commented on esphome/components/ota/ota_component.h
> +  uint32_t get_safe_mode_boot_count();
```suggestion
  uint32_t get_safe_mode_boot_count() const;
```

2021-08-03 22:41 UTC, jesserockz approved these changes

2021-08-04 02:57 UTC, alexyao2015 commented
Just realized this won't work with power cycling as the boot counter isn't stored in the flash, so it don't really make sense to expose this. Probably need to instead create a global variable to store boot count and restore from flash instead...

2021-08-04 02:59 UTC, alexyao2015 commented
An alternative is we could remove the static false here to allow it to follow the normal flash storage procedure. https://github.com/esphome/esphome/blob/d9f09a7523e4a31b7498fdd63283987f42aff090/esphome/components/ota/ota_component.cpp#L375

2021-08-10 09:20 UTC, OttoWinter commented
> Just realized this won't work with power cycling as the boot counter isn't stored in the flash, so it don't really make sense to expose this. Probably need to instead create a global variable to store boot count and restore from flash instead...

For what use case do you need to know the persisted boot counter?

Making it persist to flash is wrong IMO, and can mess some of the flash writing logic up too:

1. If you power cycle a device (plug it in/out), you don't want it to go into safe mode because nothing is actually wrong with the device (nothing crashes, you just re-plugged it too often)
2. If you've got a device that is going into OTA safe mode and you don't immediately notice, then this _could_ actually be a case where you wear out the flash (10x writes each time it crashes, plus a bit of a pause when its in safe mode)
3. It can get hairy with the Updater too - after a successful update the counter is reset to 0. If the area we're writing to for the boot counter is _inside_ where the new code section goes (for example if binary grew and flash offsets changes), we'll write garbage into the code section

2021-08-10 13:54 UTC, alexyao2015 commented
The original thought for this was for a light bulb. If a light bulb is set to restore from flash and happened to be turned off when power is lost, I would like for there to be a way to turn on the light even without wifi/ha, by power cycling the light and using some automation to work off boot counter. Seems that this may be more problematic than I had initially thought though.

2021-08-10 14:08 UTC, OttoWinter commented
Maybe there's another way. Just define a global var with restoring enabled, then in on_boot increment the counter, etc

2021-08-10 14:15 UTC, alexyao2015 commented
This PR doesn't really make sense all things considered then. The solution is just a global variable.

2021-08-10 14:15 UTC, closed without merging