Add Dish Network protocol
OttoWinter/esphomeyaml pull request #2117
Opened 2021-08-03 22:48 UTC by ianchi

# What does this implement/fix? 

Adds *Dish Network* protocol for IR receiver/transmitter

`transmit_dish` is validated
The receiver triggers are untested as Dish uses a different carrier frequency and my hardware doesn't support it.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
    - service: transmit_dish
      variables:
        address: int
        command: int
      then:
        - remote_transmitter.transmit_dish:
            address: !lambda "return address > 0 ? address : 1;"
            command: !lambda "return command;"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-08-05 00:16 UTC, jesserockz requested changes

2021-08-05 00:16 UTC, jesserockz commented on esphome/components/remote_base/__init__.py
> +Dish_SCHEMA = cv.Schema(
This should be capitalized as it is a constant
```suggestion
DISH_SCHEMA = cv.Schema(
```

2021-08-05 00:16 UTC, jesserockz commented on esphome/components/remote_base/__init__.py
> +@register_binary_sensor("dish", DishBinarySensor, Dish_SCHEMA)
```suggestion
@register_binary_sensor("dish", DishBinarySensor, DISH_SCHEMA)
```

2021-08-05 00:16 UTC, jesserockz commented on esphome/components/remote_base/dish_protocol.h
> +  uint16_t command;
Considering the config schema is limiting the address to `1-16` and the command to `0-63`, do you need a `uint16_t`? Could this not be downsized to a `uint8_t`?

This would need to change in `dump` `dish_action` and the `TEMPLATABLE_VALUE`

2021-08-05 14:37 UTC, ianchi commented on esphome/components/remote_base/__init__.py
> +@register_binary_sensor("dish", DishBinarySensor, Dish_SCHEMA)
Changed

2021-08-05 14:38 UTC, ianchi commented on esphome/components/remote_base/dish_protocol.h
> +  uint16_t command;
Changed

2021-08-05 14:39 UTC, ianchi commented
Updated with requested changes

2021-08-08 20:59 UTC, jesserockz commented on esphome/components/remote_base/__init__.py
> +    template_ = await cg.templatable(config[CONF_COMMAND], args, cg.uint16)
```suggestion
    template_ = await cg.templatable(config[CONF_ADDRESS], args, cg.uint8)
    cg.add(var.set_address(template_))
    template_ = await cg.templatable(config[CONF_COMMAND], args, cg.uint8)
```

2021-08-08 21:09 UTC, jesserockz commented on esphome/components/remote_base/dish_protocol.cpp
> +  for (uint i = 0; i < 4; i++) {
The remote base code has `send_times` as an option on all actions making this code somewhat unneeded...
```yaml
- remote_transmitter.transmit_dish:
    command: ...
    address: ...
    repeat:
      times: 4
```

2021-08-09 00:31 UTC, ianchi commented on esphome/components/remote_base/dish_protocol.cpp
> +  for (uint i = 0; i < 4; i++) {
The problem is that with the Dish protocol the header needs to be sent only once and then repeat 4 times the data and the trailing.
With the std repeat everything is repeated 4 times.
That’s why I included it here. You can see in the code that the header is left outside of the loop.

2021-08-09 00:33 UTC, jesserockz commented on esphome/components/remote_base/dish_protocol.cpp
> +  for (uint i = 0; i < 4; i++) {
Ah ok then. No problem with this then. I did actually notice that and saw the footer was inside the loop and thought maybe one was in the wrong place.

2021-08-09 00:51 UTC, jesserockz approved these changes

2021-08-10 01:26 UTC, merged