Support component tsl2591
OttoWinter/esphomeyaml pull request #2131
Opened 2021-08-06 02:18 UTC by wjcarpenter

# What does this implement/fix? 

This adds support for the AMS TSL2591 ambient light sensor, which is the replacement for the TSL2561

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [*] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>
https://github.com/esphome/feature-requests/issues/267

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1370

## Test Environment

- [ ] ESP32
- [*] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
i2c:
  # ...
spi:
  # ...
sensor:
  - platform: tsl2591
    id: "my_tls2591"
    name: "TSL2591 Ambient Light"
    address: 0x29
    update_interval: 60s
    visible:
      name: "TSL2591 visible light"
    infrared:
      name: "TSL2591 infrared light"
    full_spectrum:
      name: "TSL2591 full spectrum light"
    calculated_lux:
      name: "TSL2591 Lux"
```

## Checklist:
  - [*] The code change is tested and works locally.
  - [*] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [*] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-08-06 02:37 UTC, wjcarpenter commented
FYI, I changed a file under nextion due to a complaint from one of the PR CI checks. I defined CONF_VISIBLE in consts.py, but nextion had it defined locally.

2021-08-06 21:32 UTC, oxan reviewed
Thanks for your contribution!

Aside from the (minor) comments I've left, I see one issue: ESPHome has its own I2C abstraction layer (which provides e.g. support for multiplexers). I'm not sure using the global `Wire` instance, as the Adafruit library does is compatible with that. Maybe someone a bit more experienced with that can give input on that issue.

2021-08-06 21:32 UTC, oxan commented on esphome/components/tsl2591/sensor.py
> +    cg.add_library("Adafruit TSL2591 Library", "^1.4.0")
```suggestion
    cg.add_library("adafruit/Adafruit TSL2591 Library", "^1.4.0")
```

PlatformIO wants libraries to have an owner nowadays :)

2021-08-06 21:32 UTC, oxan commented on esphome/components/tsl2591/sensor.py
> +TSL2591IntegrationTime = tsl2591_ns.enum("TSL2591IntegrationTime")
```suggestion
TSL2591IntegrationTime = cg.global_ns.enum("tsl2591IntegrationTime_t")
```

This should allow you to get rid of the duplication.

2021-08-06 21:32 UTC, oxan commented on esphome/components/tsl2591/sensor.py
> +TSL2591Gain = tsl2591_ns.enum("TSL2591Gain")
```suggestion
TSL2591Gain = cg.global_ns.enum("tsl2591Gain_t")
```

(Note that the Adafruit constants have different names than what you're using below).

2021-08-06 21:32 UTC, oxan commented on platformio.ini
> +    463@1.4.0 ; Adafruit TSL2591 Library
```suggestion
    adafruit/Adafruit TSL2591 Library@1.4.0
```

The IDs are only necessary if there are duplicate libraries on the PlatformIO registry.

2021-08-06 21:32 UTC, oxan commented on esphome/components/tsl2591/tsl2591.cpp
> +  if (!this->tsl2591_.begin()) {
You should pass the configured address here, so that it works if the user provides a non-default address.

2021-08-06 21:32 UTC, oxan commented on esphome/components/tsl2591/sensor.py
> +DEPENDENCIES = ["i2c", "spi"]
Are you sure about? It'd be unfortunate to require everyone using this sensor to waste a bunch of pins to an SPI bus that isn't used.

2021-08-06 21:48 UTC, wjcarpenter commented on esphome/components/tsl2591/sensor.py
> +DEPENDENCIES = ["i2c", "spi"]
It's definite that ESPHome won't accep the config without an `spi:` block. However, it doesn't have to use any real pins. For example, in my config I have:
```
spi:
  clk_pin: 0
  mosi_pin: 0
```

2021-08-06 21:54 UTC, wjcarpenter commented on esphome/components/tsl2591/tsl2591.cpp
> +  if (!this->tsl2591_.begin()) {
Oh, yeah, that's my mistake. Thanks.

I'm actually a little conflicted about making the address configurable at all. The spec sheet for the device says it's 0x29 (and also uses 0x28) and can't be changed. So, you're not going to have more than one of these devices on a single I2C bus. I guess with a mux or some other kind of hardware in the middle you could change the address, so that justifies the configurability.

2021-08-06 21:59 UTC, wjcarpenter commented
When I first started working on this, I thought it was going to be pretty trivial to just go with the Adafruit library, so I didn't bother with the ESPHome I2C abstraction. In retrospect, it took a lot more time than I had planned (something something software development :-))

I will give the ESPHome I2C stuff another look to see how much bother it would be to change over. As with any I2C device, there's a certain amount of register and bit fiddling, but I can benefit from the Adafruit code that already works.

2021-08-07 20:52 UTC, wjcarpenter commented on esphome/components/tsl2591/sensor.py
> +TSL2591IntegrationTime = tsl2591_ns.enum("TSL2591IntegrationTime")
moot

2021-08-07 20:52 UTC, wjcarpenter commented on esphome/components/tsl2591/sensor.py
> +TSL2591Gain = tsl2591_ns.enum("TSL2591Gain")
moot

2021-08-07 20:55 UTC, wjcarpenter commented
I took @oxan's suggestion and reimplemented this using ESPHome I2C, as reflected in the current PR code. That caused some ripple effect changes because I discovered a big delay loop in the Adafruit library. You can see details of that in my commit comments for https://github.com/esphome/esphome/pull/2131/commits/babb9a389e1e6f1730c45c4d927846a979818a4c

2021-08-08 12:45 UTC, oxan requested changes
Thanks! Overall this looks fairly good now, just some relatively minor cleanups left :)

2021-08-08 12:45 UTC, oxan commented on esphome/components/tsl2591/tsl2591.cpp
> +  }
Given that `disable()` already checks if the power save mode is enabled, this method seems unnecessary?

If that's the case, it might be nice to make it clear from the name of `disable` that it only disables if powersaving is on, so e.g. `disable_if_power_saving()` / `enter_power_saving()` / `device_idle()` / something like that.

2021-08-08 12:45 UTC, oxan commented on esphome/components/tsl2591/tsl2591.cpp
> +    ESP_LOGD("ERROR", "Could not find a TSL2591 Sensor. Did you configure I2C with the correct address?");
It might be useful to log the `id` result here as well. In the past (for other components) we've had users with a counterfeit/fake chip that had a different device id. Logging the `id` will make it easier to diagnose such issues.

2021-08-08 12:45 UTC, oxan commented on esphome/components/tsl2591/tsl2591.cpp
> +  ESP_LOGCONFIG(TAG, "  Power save mode enabled: %s", this->power_save_mode_enabled_ ? "True" : "False");
```suggestion
  ESP_LOGCONFIG(TAG, "  Power save mode enabled: %s", ONOFF(this->power_save_mode_enabled_));
```
For consistency with what other components use :)

2021-08-08 12:45 UTC, oxan commented on esphome/components/tsl2591/tsl2591.cpp
> +  disable_internal_();
This method gets called very early in startup, before e.g. the I2C multiplexer is setup, so you shouldn't do communication here. Instead, only set the `integration_time_` variable here, and actually write that command to the device in `setup()`. That also avoids a redundant enable/disable cycle for setting both integration time and gain.

2021-08-08 12:45 UTC, oxan commented on esphome/components/tsl2591/tsl2591.cpp
> +  this->disable_internal_();
Same here.

2021-08-08 12:45 UTC, oxan commented on esphome/components/tsl2591/tsl2591.cpp
> +  // Wait x ms for ADC to complete and signal valid.
If I understand correctly, this delay will only happen if powersaving mode is enabled, right? It would be nice to add that to the comment.

2021-08-08 12:45 UTC, oxan commented on esphome/components/tsl2591/tsl2591.h
> +/// ESPHome uses the term "illuminance", as does the TLS2591 datasheet.
This comment is now obsolete.

2021-08-08 12:45 UTC, oxan commented on esphome/components/tsl2591/tsl2591.h
> +   * call `getCombinedIlluminance()` and pass that value to the companion
```suggestion
   * call `get_combined_illuminance()` and pass that value to the companion
```

2021-08-08 12:45 UTC, oxan commented on esphome/components/tsl2591/tsl2591.h
> +  boolean is_adc_valid();
```suggestion
  bool is_adc_valid();
```
`boolean` is an Arduino-ism.

2021-08-08 12:58 UTC, oxan commented
Btw, it's also possible to implement the safe-delay scripting you talk about in the component directly. It's fine to leave that out for now (you can do a follow-up PR if you're interested), but for future reference I'll detail the implementation here:

* Move the logic to read from the sensors to a separate method (e.g. `process_update()`)`
* In `update`, if the ADC is valid, call `process_update()` and return.
* If the ADC isn't valid, set an interval using `set_interval()`. 
* In the interval function, check if the ADC is valid, if so, cancel the interval and call `process_update()`.
* You can use either a static variable or `millis()` to check how often the interval was invoked and ensure it doesn't run forever.

2021-08-08 17:03 UTC, wjcarpenter commented on esphome/components/tsl2591/tsl2591.h
> +  boolean is_adc_valid();
what's an arduino? :-)

2021-08-08 17:06 UTC, wjcarpenter commented on esphome/components/tsl2591/tsl2591.cpp
> +  }
Just a careless mistake. I copied the method but neglected to remove the check from the original.

2021-08-08 17:48 UTC, wjcarpenter commented on esphome/components/tsl2591/tsl2591.cpp
> +    ESP_LOGD("ERROR", "Could not find a TSL2591 Sensor. Did you configure I2C with the correct address?");
Good suggestion. When I went to make that change, I realized that none of the logging from my setup() is showing up anywhere. (I also changed logging the error to ESP_LOGE.) Maybe it's because I'm testing with OTA? Or maybe it's something related to the start-up sequence and it doesn't show up for anybody?

I'm going to leave the logging in there in case it's something environmental that prevents it showing up for me

2021-08-08 17:51 UTC, wjcarpenter commented on esphome/components/tsl2591/tsl2591.cpp
> +    ESP_LOGD("ERROR", "Could not find a TSL2591 Sensor. Did you configure I2C with the correct address?");
Since i2c.cpp logs I2C problems with ESP_LOGI, I guess I'll do the same thing for the chip ID mismatch.

2021-08-08 18:12 UTC, wjcarpenter commented on esphome/components/tsl2591/tsl2591.cpp
> +  // Wait x ms for ADC to complete and signal valid.
good suggestion

2021-08-08 18:16 UTC, oxan commented on esphome/components/tsl2591/tsl2591.cpp
> +    ESP_LOGD("ERROR", "Could not find a TSL2591 Sensor. Did you configure I2C with the correct address?");
Yes, errors during setup() are logged before the network connection is made, so if you look at the logs through wifi, you won't see them. They're present on the serial bus though.

You should log the error using `ESP_LOGE` (the last letter is the severity of the message, E = error, W = warn, I = info, D = debug). You should also use the `TAG` constant as the first parameter, that labels the log message with the integration.

2021-08-08 20:34 UTC, wjcarpenter commented on esphome/components/tsl2591/tsl2591.cpp
> +    ESP_LOGD("ERROR", "Could not find a TSL2591 Sensor. Did you configure I2C with the correct address?");
Agreed. I copied this section from some other integration. It will now be ESP_LOGE(TAG, ...

2021-08-08 20:38 UTC, wjcarpenter commented on esphome/components/tsl2591/tsl2591.cpp
> +  disable_internal_();
I didn't know that, but I'm making this change. Since the actual I2C transaction sets them both into the same register, I've changed the exposed API to require both params. A nice side effect is that I can do the power management thing inside this combined setter method to avoid bogus ADC values on the next read.

2021-08-08 23:55 UTC, wjcarpenter commented
Great suggestion about using intervals, @oxan. I much prefer taking care of it by default rather than having to bother each user to think about it. I implemented that and changed the default for power_save_mode to be enabled.

BTW, I really appreciate the effort you are putting into reviewing the code. You have an eye for detail and an attitude for quality. (And, somehow, you are able to read my mind and know when I am being lazy or careless. :-) )

2021-08-09 09:24 UTC, oxan approved these changes
Nice work! Looks good now :tada: I appreciate the extensive comments you've included :)

2021-08-09 09:24 UTC, oxan commented on esphome/components/tsl2591/tsl2591.cpp
> +#define interval_name "tsl2591_interval_for_update"
Intervals are namespaced to components, so the prefix isn't really necessary, but it doesn't hurt either :)

2021-08-09 09:24 UTC, oxan commented on esphome/components/tsl2591/tsl2591.h
> +  const char *name_;  // TODO: extend esphome::Nameable
Meh, I wouldn't do that, as `Nameable` has grown beyond just being a name and has all sorts of irrelevant stuff now. You technically don't even need a name for this component (only sensors need to be named), though I can see why it's useful if you've got multiple sensors connected.

2021-08-09 15:34 UTC, wjcarpenter commented on esphome/components/tsl2591/tsl2591.cpp
> +#define interval_name "tsl2591_interval_for_update"
Are they also scoped to the component instance? If I have two instances of this class, will they both try to use the interval with that fixed name?

2021-08-09 15:37 UTC, wjcarpenter commented on esphome/components/tsl2591/tsl2591.h
> +  const char *name_;  // TODO: extend esphome::Nameable
It just seemed a little ragged to me to require names for sensors and not even allow them for the component. (I first tried to use inheritance from Nameable, but ran into some problems.) I am more used to a model where things have an machine-friendly ID that is immutable after creation and a human-friendly name that is mutable.

Anyhow, it didn't cost much :-).

2021-08-10 01:56 UTC, wjcarpenter commented on esphome/components/tsl2591/tsl2591.cpp
> +#define interval_name "tsl2591_interval_for_update"
I had a look at the interval stuff in Component.cpp. I see that it is keyed by component instance, so there would be no interference from multiple instances of a component class.

2021-08-10 07:24 UTC, OttoWinter approved these changes
Thanks!

2021-08-10 08:48 UTC, merged