Add support for Daly Smart BMS
OttoWinter/esphomeyaml pull request #2156
Opened 2021-08-14 20:52 UTC by s1lvi0

# What does this implement/fix? 

Add support for Daly Smart BMS over UART

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1390

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
  uart:
      tx_pin: GPIO1
      rx_pin: GPIO3
      baud_rate: 9600
      
    daly_bms:
      update_interval: 20s
      
    sensor:
      - platform: daly_bms
        voltage:
          name: "Battery Voltage"
        current:
          name: "Battery Current"
        battery_level:
          name: "Battery Level"
        max_cell_voltage:
          name: "Max Cell Voltage"
        max_cell_voltage_number:
          name: "Max Cell Voltage Number"
        min_cell_voltage:
          name: "Min Cell Voltage"
        min_cell_voltage_number:
          name: "Min Cell Voltage Number"
        max_temperature:
          name: "Max Temperature"
        max_temperature_probe_number:
          name: "Max Temperature Probe Number"
        min_temperature:
          name: "Min Temperature"
        min_temperature_probe_number:
          name: "Min Temperature Probe Number"
        remaining_capacity:
          name: "Remaining Capacity"
        temperature_1:
          name: "Temperature 1"
        temperature_2:
          name: "Temperature 2"

    text_sensor:
      - platform: daly_bms
        status:
          name: "BMS Status"
          
          
    binary_sensor:
      - platform: daly_bms
        charging_mos_enabled:
          name: "Charging MOS"
        discharging_mos_enabled:
          name: "Discharging MOS"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-08-18 08:28 UTC, jesserockz requested changes
A couple of inline suggestions, but also please change all `unsigned char` to `uint8_t`

2021-08-18 08:28 UTC, jesserockz commented on esphome/components/daly_bms/__init__.py
> +DalyBmsComponent = daly_bms.class_("DalyBmsComponent", uart.UARTDevice, cg.Component)
```suggestion
DalyBmsComponent = daly_bms.class_("DalyBmsComponent", cg.PollingComponent, uart.UARTDevice)
```

2021-08-18 08:28 UTC, jesserockz commented on esphome/components/daly_bms/__init__.py
> +)
```suggestion
CONFIG_SCHEMA = (
    cv.Schema({cv.GenerateID(): cv.declare_id(DalyBmsComponent)})
    .extend(uart.UART_DEVICE_SCHEMA)
    .extend(cv.polling_component_schema("30s"))
)
```

2021-08-18 08:28 UTC, jesserockz commented on esphome/components/daly_bms/daly_bms.cpp
> +                    (float) ((data[8] << 24) | (data[9] << 16) | (data[10] << 8) | data[11]) / 1000);
There is also a helper for `encode_uint16` that could be used for the values using 2 bytes if you want to change.
```suggestion
                    (float) encode_uint32(data[8], data[9], data[10], data[11]) / 1000);
```

2021-08-18 11:09 UTC, s1lvi0 commented on esphome/components/daly_bms/daly_bms.cpp
> +                    (float) ((data[8] << 24) | (data[9] << 16) | (data[10] << 8) | data[11]) / 1000);
Thank you for all suggestions

2021-08-20 15:32 UTC, oxan requested changes

2021-08-20 15:32 UTC, oxan commented on esphome/components/daly_bms/__init__.py
> +BSM_DALY_ID = "bms_daly_id"
Generally these variables are prefixed with `CONF_`, and there's a typo (BSM instead of BMS).

2021-08-20 15:32 UTC, oxan commented on esphome/components/daly_bms/daly_bms.cpp
> +  ESP_LOGCONFIG(TAG, "DALY_BMS:");
```suggestion
  ESP_LOGCONFIG(TAG, "Daly BMS:");
```

2021-08-20 15:32 UTC, oxan commented on esphome/components/daly_bms/daly_bms.cpp
> +    this->read_array(&get_battery_level_data[0], available_data);
```suggestion
    this->read_array(get_battery_level_data.data(), available_data);
```

2021-08-20 15:32 UTC, oxan commented on esphome/components/daly_bms/daly_bms.cpp
> +void DalyBmsComponent::decode_data(uint8_t *data, int length) {
This method has a weird signature, why not pass the vector directly instead of a bare pointer with a length?

2021-08-20 15:32 UTC, oxan commented on esphome/components/daly_bms/daly_bms.cpp
> +        data = nullptr;
You can just `return;` or `break;` here. I'd also recommend inverting these checks, so that you don't have to indent 8 levels deep.

2021-08-20 15:32 UTC, oxan commented on esphome/components/daly_bms/daly_bms.cpp
> +        }
There's an infinite loop here if the checksum doesn't match.

2021-08-20 15:32 UTC, oxan commented on esphome/components/daly_bms/daly_bms.cpp
> +      if (length >= 13 && data[1] == 0x01) {
If you pass the vector as an argument, all this manual bookkeeping can be replaced with iterators:
```cpp
  auto it = data.begin();
  while ((it = std::find(it, data.end(), 0xA5)) != data.end()) {
    if (data.end() - it >= 13 && it[1] == 0x01) {
      // ...
      
      std::advance(it, 13);
    }
  }
```
(might need to `#include <algorithm>`).

2021-08-20 15:32 UTC, oxan commented on esphome/components/daly_bms/daly_bms.h
> +    max_cell_volatge_number_ = max_cell_volatge_number;
```suggestion
  void set_max_cell_voltage_number_sensor(sensor::Sensor *max_cell_voltage_number) {
    max_cell_voltage_number_ = max_cell_voltage_number;
```

2021-08-20 15:32 UTC, oxan commented on esphome/components/daly_bms/daly_bms.h
> +  sensor::Sensor *max_cell_volatge_number_{nullptr};
```suggestion
  sensor::Sensor *max_cell_voltage_number_{nullptr};
```

2021-08-22 10:41 UTC, s1lvi0 commented on esphome/components/daly_bms/daly_bms.h
> +  sensor::Sensor *max_cell_volatge_number_{nullptr};
Thank you for all suggestions, very appreciated

2021-08-22 11:06 UTC, oxan approved these changes
Thank you!

2021-09-13 18:35 UTC, oxan commented
@s1lvi0 Could you add an example of the usage of this component to one of the YAML files in `tests`? That way the code gets compile-tested in the CI.

I think after that it can be merged :+1:

2021-09-22 10:03 UTC, merged