Add support for all device classes defined in `const.py`
OttoWinter/esphomeyaml pull request #2164
Opened 2021-08-16 15:32 UTC by jurriaan

# What does this implement/fix? 

While setting up a custom P1 sensor for the gas meter I got the following error:

> Unknown value 'gas', valid options are '', 'battery', 'carbon_monoxide', 'carbon_dioxide', 'current', 'energy', 'humidity', 'illuminance', 'signal_strength', 'temperature', 'timestamp', 'power', 'power_factor', 'pressure', 'voltage'.
>     device_class: gas

When looking in the esphome source code I noticed that not all `DEVICE_CLASS`es where included in the validation logic, so this PR adds them so they can be used in the YAML configuration files.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:
```yaml
# Example config.yaml
sensors:
  - platform: custom
    lambda: '....'
    sensors:
    - name: "Gas Meter M3"
      device_class: gas
      state_class: measurement
      unit_of_measurement: m³
      accuracy_decimals: 3
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-08-16 17:15 UTC, jesserockz submitted a review, later dismissed

2021-08-17 01:32 UTC, jesserockz requested changes
@jurriaan We cant just accept all, device classes for sensors need to match Home Assistant's list: https://github.com/home-assistant/core/blob/dev/homeassistant/components/sensor/__init__.py#L62

There do look to be a few recent missing from the list in HA though

2021-08-17 09:43 UTC, frenck commented on esphome/components/sensor/__init__.py
> +    DEVICE_CLASS_GARAGE_DOOR,
This PR is actually incorrect. It mixes up device classes from sensors with the ones from binary sensors.

2021-08-17 11:12 UTC, jurriaan commented on esphome/components/sensor/__init__.py
> +    DEVICE_CLASS_GARAGE_DOOR,
Ah yes, will fix the PR today and add all relevant documented device classes to the sensor and binary_sensor

2021-08-17 11:17 UTC, closed without merging