Optionally set direction on fan.turn_on action
OttoWinter/esphomeyaml pull request #2171
Opened 2021-08-17 13:23 UTC by WeekendWarrior1

# What does this implement/fix? 

Makes sense to be able to set the direction of a fan component from the fan.turn_on action using esphome, since you can already set the speed, etc.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
      - fan.turn_on:
          id: exhaust_fan
          speed: 50
          direction: reverse
      - fan.turn_on:
          id: intake_fan
          speed: 50
          direction: forward
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-08-17 13:41 UTC, oxan requested changes

2021-08-17 13:41 UTC, oxan commented on esphome/components/fan/__init__.py
> +            ),
If this is meant to be templatable, you need to wrap the enum inside a `cv.templatable`.

2021-08-17 13:41 UTC, oxan commented on esphome/components/fan/__init__.py
> +        template_ = await cg.templatable(FAN_DIRECTION_ENUM[config[CONF_DIRECTION]], args, FanDirection)
I think the lookup of the enum value here is unnecessary.

2021-08-17 14:05 UTC, WeekendWarrior1 commented on esphome/components/fan/__init__.py
> +            ),
Thank you for the feedback
I have almost no experience or understanding around voluptuous, or what is meant by "templatable", so really appreciate your insight.

2021-08-17 14:10 UTC, WeekendWarrior1 commented on esphome/components/fan/__init__.py
> +        template_ = await cg.templatable(FAN_DIRECTION_ENUM[config[CONF_DIRECTION]], args, FanDirection)
You are correct, worked perfectly fine without it

2021-08-17 14:11 UTC, oxan commented on esphome/components/fan/__init__.py
> +            ),
templatable means you can use a [lambda](https://esphome.io/guides/automations.html#templates-lambdas) for the value. In the `fan_turn_on_to_code` method you process the value for this option as if it's templatable, but that also requires you to add `cv.templatable()` around the enum definition here (like the previous options have).

2021-08-17 14:19 UTC, WeekendWarrior1 commented on esphome/components/fan/__init__.py
> +            ),
Thanks for the explanation!

2021-08-17 14:34 UTC, oxan approved these changes

2021-08-24 10:55 UTC, jesserockz commented on esphome/components/fan/__init__.py
> +            cv.Optional(CONF_DIRECTION, default="FORWARD"): cv.templatable(
This really should not have a default if it is supposed to be optional. With a default of forward, it can have a side effect of changing the direction if the user does not specify direction when changing the speed while it is in reverse mode.

```suggestion
            cv.Optional(CONF_DIRECTION): cv.templatable(
```

2021-08-25 09:05 UTC, WeekendWarrior1 commented on esphome/components/fan/__init__.py
> +            cv.Optional(CONF_DIRECTION, default="FORWARD"): cv.templatable(
Good catch, thanks!

2021-08-25 22:24 UTC, jesserockz approved these changes

2021-08-25 22:25 UTC, merged