Add ble_client binary_output
OttoWinter/esphomeyaml pull request #2200
Opened 2021-08-24 16:02 UTC by tekmaven

# What does this implement/fix? 
Adds ble_client binary_output.  

Quick description and explanation of changes
Allows you to write binary values to BLE Characteristics.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1417

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
    esp32_ble_tracker:
    ble_client:
      - mac_address: FF:FF:20:00:0F:15
        id: itag_black
    output:
      - platform: ble_client
        ble_client_id: itag_black
        service_uuid: "10110000-5354-4F52-5A26-4249434B454C"
        characteristic_uuid: "10110013-5354-4f52-5a26-4249434b454c"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-08-25 05:35 UTC, buxtronix requested changes

2021-08-25 05:35 UTC, buxtronix commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +    auto stateAsUint = (uint8_t) state;
Should there be a config setting or even template support to allow writing values aside from 0/1? There may be devices that expect other values for on/off etc.

2021-08-25 05:35 UTC, buxtronix commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +  switch (event) {
Is it worth adding ESP_GATTC_WRITE_CHAR_EVT and checking the status? The write call only enqueues the write, you would need to listen this this event for whether it successfully was sent to the device.

2021-08-25 14:57 UTC, anduchs commented on esphome/components/ble_client/ble_client.cpp
> +void BLECharacteristic::write_value(uint8_t newVal) {
I'd prefer a function allowing a byte array to be written. This would provide more flexibility for other outputs in the future; e.g.:
```
void BLECharacteristic::write_value(uint8_t *newVal, size_t newValSize)
```

2021-08-25 15:40 UTC, tekmaven commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +    auto stateAsUint = (uint8_t) state;
Thanks for reviewing this buxtronix.  Appreciate all your contributions to esphome.    This is something I also considered.   How can a 0-1 float (which is the other option for `output`) convert to a `uint8_t` (what the SDK takes for ble writes) in a more useful way?  Wouldn't all values cast to 0 or 1 anyway?

2021-08-25 15:42 UTC, tekmaven commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +  switch (event) {
I will give this a shot.  Thanks for the suggestion!

2021-08-25 17:13 UTC, anduchs commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +    auto stateAsUint = (uint8_t) state;
I guess he means that e.g. some BLE device might expect the strings "TurnOn"/"TurnOff" or "on"/"off" or 255 and 0 instead of 1 and 0 for being turned on and off...

Hence also my comment about the write_value() below.

2021-08-25 17:31 UTC, tekmaven commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +    auto stateAsUint = (uint8_t) state;
I am open to expanding the functionality.  Could you provide an example of how to write strings to a characteristic?  I'm new to BLE and ESP.

2021-08-26 00:58 UTC, tekmaven commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +  switch (event) {
See the latest commit.  Hopefully this is what you were thinking of.  Otherwise, open to further suggestions.

2021-08-26 01:43 UTC, buxtronix requested changes

2021-08-26 01:43 UTC, buxtronix commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +        ESP_LOGD(TAG, "[%s] Write complete, status=%d", this->char_uuid_.to_string().c_str(), param->write.status);
I'd be inclined to only log if the status indicates an error, else there will be a lot of log chatter. It might also be more useful to log the client name/mac as it doesnt differentiate if there are multiple similar clients.

2021-08-26 12:57 UTC, tekmaven commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +        ESP_LOGD(TAG, "[%s] Write complete, status=%d", this->char_uuid_.to_string().c_str(), param->write.status);
I changed the log line to a warning, only if there is an error.  I'm not really sure how to access client name, so any tips are welcomed 👍.

2021-08-26 12:58 UTC, tekmaven commented on esphome/components/ble_client/ble_client.cpp
> +void BLECharacteristic::write_value(uint8_t newVal) {
I've modified the method to this exact signature!

2021-08-30 02:14 UTC, buxtronix commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +        ESP_LOGD(TAG, "[%s] Write complete, status=%d", this->char_uuid_.to_string().c_str(), param->write.status);
Client name is harder, but you can get the mac with `this->parent_->address_str().c_str()`

2021-08-30 02:17 UTC, buxtronix commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +    auto stateAsUint = (uint8_t) state;
A string is just a char array. You provide this array (and its length) to the write_value function that you added.

2021-10-13 00:14 UTC, jesserockz commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +    auto stateAsUint = (uint8_t) state;
I would suggest adding a `write_lambda` or similar to allow the user to convert 0-255 to a uint_8 vector

2021-11-07 04:20 UTC, bjeanes commented
Is this abandoned or still cooking away? I am attempting to integrate with [a product which has Bluetooth](https://www.aliexpress.com/item/1005002707585119.html) to get sensor readings but I need to write to a characteristic before it will start sending sensor readings.

In my case I _do_ have to write more than just a boolean:

`0x0003000000144414` has to be written to `0xffe1` characteristic for `0xffe0` service. Only then will the `0xffe1` value start changing to reflect sensor readings. Based on some code I'm looking at, I may also have to send `0x01` to the `0xffe2` service too. It's very undocumented, I'm afraid.

<small>Annoyingly (but unrelated to this PR), it re-uses the same characteristic for all 3 sensors, so I'll have to do some awkward `lambda` stuff to update 3 different ESPHome `text_sensors` (at least I think this will be the way forward...).</small>

I'd be happy even with some functions exposed to use in the `on_connect` automation to fire these, but some kind of output sensor could work too, I think?

2021-11-07 06:26 UTC, bjeanes commented
I was able to start receiving updates by doing:

```yml
ble_client:
  - mac_address: '7C:01:0A:43:4E:9E'
    id: ph_260bd
    on_connect:
      then:
        - wait_until: # wait until characteristic is discovered
            lambda: |-
              esphome::ble_client::BLEClient* client = id(ph_260bd);
            
              auto service_uuid = 0xFFE0;
              auto char_uuid = 0xFFE1;
              
              esphome::ble_client::BLECharacteristic* chr = client->get_characteristic(service_uuid, char_uuid);
              
              return chr != nullptr;
        - lambda: |-
            ESP_LOGD("ble_client.on_connect", "Connected to PH-260BD");
            
            //esphome::ble_client::BLESensor* sensor = id(ph_260bd_sensor);
            esphome::ble_client::BLEClient* client = id(ph_260bd);
            
            auto service_uuid = 0xFFE0; // can't get it off `sensor` because it is protected
            auto char_uuid = 0xFFE1;    // can't get it off `sensor` because it is protected
            
            esphome::ble_client::BLECharacteristic* chr = client->get_characteristic(service_uuid, char_uuid);
            
            if (chr == nullptr) {
                ESP_LOGW("ble_client.on_connect", "[0xFFE1] Characteristic not found.  State update can not be written.");
            } else {
              unsigned char newVal[8] = {
                0x00, 0x03,  0x00, 0x00,
                0x00, 0x14, 0x44, 0x14
              };
              int status = esp_ble_gattc_write_char(
                client->gattc_if,
                client->conn_id,
                chr->handle,
                sizeof(newVal),
                newVal,
                ESP_GATT_WRITE_TYPE_NO_RSP,
                ESP_GATT_AUTH_REQ_NONE
              );

              if (status) {
                ESP_LOGW("ble_client.on_connect", "Error sending write value to BLE gattc server, status=%d", status);
              }
            }
```

Non-ideal, but at least this PR's code helped and unblocked me, so thank you! 

A lot more to do to actually make the values received useful, but that's the fault of this device maker being lazy and using a single characteristic for everything :\

2021-11-07 09:24 UTC, TroySK commented
I would also appreciate seeing this get merged as it will help me add multiple BLE devices using ESP32s.

> Is this abandoned or still cooking away?

2021-11-07 19:39 UTC, jesserockz reviewed
Just one small change and I think this is good to go.

2021-11-07 19:39 UTC, jesserockz commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +#ifdef ARDUINO_ARCH_ESP32
```suggestion
#ifdef USE_ESP32
```

2021-11-07 19:39 UTC, jesserockz commented on esphome/components/ble_client/output/ble_binary_output.h
> +#ifdef ARDUINO_ARCH_ESP32
```suggestion
#ifdef USE_ESP32
```

2021-11-07 19:47 UTC, jesserockz reviewed
Lint Fixes

2021-11-07 19:47 UTC, jesserockz commented on esphome/components/ble_client/ble_client.cpp
> +  auto status = esp_ble_gattc_write_char(client->gattc_if, client->conn_id, this->handle, newValSize, newVal,
```suggestion
void BLECharacteristic::write_value(uint8_t *new_val, int16_t new_val_size) {
  auto client = this->service->client;
  auto status = esp_ble_gattc_write_char(client->gattc_if, client->conn_id, this->handle, new_val_size, new_val,
```

2021-11-07 19:47 UTC, jesserockz commented on esphome/components/ble_client/ble_client.h
> +  void write_value(uint8_t *newVal, int16_t newValSize);
```suggestion
  void write_value(uint8_t *new_val, int16_t new_val_size);
```

2021-11-07 19:47 UTC, jesserockz commented on esphome/components/ble_client/output/ble_binary_output.h
> +  void gattc_event_handler(esp_gattc_cb_event_t event, esp_gatt_if_t gattc_if, esp_ble_gattc_cb_param_t *param);
```suggestion
  void gattc_event_handler(esp_gattc_cb_event_t event, esp_gatt_if_t gattc_if, esp_ble_gattc_cb_param_t *param) override;
```

2021-11-07 19:47 UTC, jesserockz commented on esphome/components/ble_client/output/ble_binary_output.h
> +  void write_state(bool state);
```suggestion
  void write_state(bool state) override;
```

2021-11-14 21:56 UTC, jesserockz approved these changes

2021-11-16 18:29 UTC, jesserockz approved these changes

2021-11-16 18:30 UTC, merged