Make flash pulse bright and back
OttoWinter/esphomeyaml pull request #2201
Opened 2021-08-24 18:08 UTC by alexyao2015

# What does this implement/fix? 
Makes flash pulse the color, dimmer, back the the original, and finally back to the original state. This makes flash act more in line with commercial light products light Yeelight and Hue. 

Also fixes flash not restoring state properly. 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-08-25 00:06 UTC, oxan requested changes
I'm not sure whether unconditionally using the default transition length here is a good idea. It wouldn't surprise me if there are people that want to keep the old behaviour.

2021-08-25 00:06 UTC, oxan commented on esphome/components/light/transformers.h
> +        this->transformer_ = nullptr;
`stop()` should be called here.

2021-08-25 00:06 UTC, oxan commented on esphome/components/light/transformers.h
> +    if (this->last_transition_p_ < p) {
`last_transition_p_` is used uninitialized.

2021-08-25 00:06 UTC, oxan commented on esphome/components/light/transformers.h
> +      } else if (p >= 0.5f && p < 1.0f) {
This starts the transition back to the start value after 50% of the flash, which will cut the flash short if the transition duration is less than half of the flash length.

2021-08-25 00:12 UTC, alexyao2015 commented on esphome/components/light/transformers.h
> +      } else if (p >= 0.5f && p < 1.0f) {
Good catch! Thanks.

2021-08-25 21:32 UTC, oxan reviewed
Now that flashes support transitions, we should support setting the transition length for an individual flash through a `LightCall` as well (though that could be left for a follow-up PR).

2021-08-25 21:32 UTC, oxan commented on esphome/components/light/transformers.h
> +      }
This whole logic here seems unnecessarily complicated now. Can we setup the first transition in `start()`, and the second one in a `if (millis() > this->start_time_ + this->length_ - this->transition_length_)`? That way the whole dance with `last_transition_p_` and `transition_back_p_` can be dropped, which is less code and makes it more obvious what's going on as well, imo.

2021-08-26 00:41 UTC, alexyao2015 commented on esphome/components/light/transformers.h
> +      }
There still needs to be a way to mark the secondary transition as having already occurred. I can do that, but I would need another boolean to mark as true once its done or there will be an infinite transition loop.

2021-08-29 10:19 UTC, oxan approved these changes

2021-08-29 10:19 UTC, oxan commented on esphome/components/light/transformers.h
> +      }
Why? When the second transition is finished, the flash transformer would be finished, so it'd never start a third transition.

2021-08-31 02:18 UTC, merged