Adds MQ Sensor Series
OttoWinter/esphomeyaml pull request #2221
Opened 2021-08-30 18:36 UTC by nonameplum

# What does this implement/fix? 

Added support for MQ Sensor Series.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1434

## Test Environment

- [x] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
sensor:
    - platform: mq
      model: MQ9
      pin: A0
      rl: 10
      r0: 0.95
      update_interval: 30s
      sensor_lpg:
        name: Sensor LPG
      sensor_ch4:
        name: Sensor CH4
      sensor_co:
        name: Sensor CO
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-08-31 07:36 UTC, nonameplum commented
I would like to fix the lint issues but I have no idea how to fix them for now:
1.  `clang-tidy` doesn't see the third party library `MQUnifiedsensor` (any idea?)
2. `clang-tidy` probably runs into the issue related to this https://stackoverflow.com/questions/64680769/c-core-guidelines-for-static-member-variables
3. `lint-python ` - `Error: Process completed with exit code 1.` can I get more details on what is actually an issue?

2021-09-02 00:28 UTC, jesserockz requested changes
You have basically dumped the MQ library into the folder alongside the ESPHome code. What you need to do is use the library code as a reference, and write the functionality into the ESPHome sensor code so it doesn't have the dependency.

2021-09-04 20:15 UTC, nonameplum commented
@jesserockz I have done what you suggested and fixed all of the PR checks.

2021-09-13 08:18 UTC, OttoWinter commented on esphome/components/mq/mq.cpp
> +    avg += analogRead(this->pin_->get_pin());  // NOLINT
We should ideally not use `analogRead` directly because it makes the code less portable (on ESP32, you can't set attenuation which can be useful, and external ADCs can't be used). Fortunately we already have an abstraction for just that: `voltage_sampler`.

Can you update this to use `voltage_sampler` instead? See also `ct_clamp` as an example

2021-09-13 08:19 UTC, OttoWinter commented on esphome/components/mq/mq.cpp
> +    delay(RETRY_INTERVAL);
Hmm, in effect this will be a 40ms block of the main thread, which is too much unfortunately.

Could you update this to use a `set_timeout` function to schedule the next delay, thanks!

2021-09-13 08:22 UTC, OttoWinter commented on esphome/components/mq/sensor.py
> +                filter(lambda elem: "sensor_" in elem[0].lower(), config.items())
This `sensor_` check feels dangerous. If the sensor base schema at any point introduces a `sensor_` key this will break.

Could you instead create a global list of all sensor keys and filter by that?

2021-09-13 08:23 UTC, OttoWinter commented on esphome/components/mq/sensor.py
> +            cv.Optional(CONF_RL, default=10.0): cv.positive_float,
Is this supposed to be a resistance value? If so we have `cv.resistance`

2021-09-13 08:23 UTC, OttoWinter commented on esphome/components/mq/sensor.py
> +    ).extend(cv.polling_component_schema("10s")),
```suggestion
    ).extend(cv.polling_component_schema("60s")),
```

I'd strongly suggest to use 60s as the default update interval for consistency unless there's a reason you really need lower ones.

2021-12-20 01:39 UTC, closed without merging