Fix UARTComponent hardware vs software UART0 conflict
OttoWinter/esphomeyaml pull request #2229
Opened 2021-09-02 18:30 UTC by ferbar

# What does this implement/fix? 

Fix for using UARTComponent with logger and pins 1/3 or 15/13.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [ ] ESP32
- [X] ESP8266 (only ESP8266 is affected)

## Example entry for `config.yaml`:

```yaml
uart:

# Use same RX and TX pins & baud rate as the logger does per default, logger is still working UARTComponent will use UART0, component can use RX as input.
  - rx_pin: RX
    tx_pin: TX
    baud_rate: 115200
    id: uart_logger

# Will always use Software Serial.
  - rx_pin: GPIO14
    tx_pin: GPIO12
    baud_rate: 9600
    id: uart_senseair

# Will use hardware UART0 only if it's free.
  - rx_pin: GPIO13
    tx_pin: GPIO15
    baud_rate: 9600
    id: uart_sds011

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-09-02 20:08 UTC, oxan requested changes
Thanks for your contribution! I've some minor clean-up suggestions left, otherwise it looks good:

2021-09-02 20:08 UTC, oxan commented on esphome/components/uart/uart_esp8266.cpp
> +bool UARTComponent::serial0InUse = false;
To suppress the clang warning:
```suggestion
bool UARTComponent::serial0InUse = false;  // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
```

2021-09-02 20:08 UTC, oxan commented on esphome/components/uart/uart_esp8266.cpp
> +  if (!esphome::uart::UARTComponent::serial0InUse && this->tx_pin_.value_or(1) == 1 &&
You don't actually need a fully qualified name here:
```suggestion
  if (!UARTComponent::serial0InUse && this->tx_pin_.value_or(1) == 1 &&
```

2021-09-02 20:08 UTC, oxan commented on esphome/components/uart/uart_esp8266.cpp
> +      && !(logger::global_logger->get_hw_serial() == &Serial && (IOSWAP & (1 << IOSWAPU0)))
We don't need to poke around in internals to detect swap state here, we can just use the `get_uart()` method of the logger:
```suggestion
      // we will use UART0 if logger isn't using it in swapped mode
      && logger::global_logger->get_uart() != logger::UART_SELECTION_UART0_SWAP
```

2021-09-02 20:08 UTC, oxan commented on esphome/components/uart/uart_esp8266.cpp
> +    esphome::uart::UARTComponent::serial0InUse = true;
```suggestion
    UARTComponent::serial0InUse = true;
```

2021-09-02 20:08 UTC, oxan commented on esphome/components/uart/uart_esp8266.cpp
> +  } else if (!esphome::uart::UARTComponent::serial0InUse && this->tx_pin_.value_or(15) == 15 &&
```suggestion
  } else if (!UARTComponent::serial0InUse && this->tx_pin_.value_or(15) == 15 &&
```

2021-09-02 20:08 UTC, oxan commented on esphome/components/uart/uart_esp8266.cpp
> +             && !(logger::global_logger->get_hw_serial() == &Serial && !(IOSWAP & (1 << IOSWAPU0)))
```suggestion
             // we will use UART0 swapped if logger isn't using it in regular mode
             && logger::global_logger->get_uart() != logger::UART_SELECTION_UART0
```

2021-09-02 20:08 UTC, oxan commented on esphome/components/uart/uart_esp8266.cpp
> +    esphome::uart::UARTComponent::serial0InUse = true;
```suggestion
    UARTComponent::serial0InUse = true;
```

2021-09-03 05:07 UTC, jesserockz approved these changes
Logic looks sound to me

2021-09-03 12:23 UTC, oxan approved these changes
Looks good to me too.

2021-09-04 02:49 UTC, merged

2021-09-04 06:05 UTC, ferbar commented
Tanks oxan & jesserocks