Add `esp32_camera_web_server:` to expose mjpg/jpg images
OttoWinter/esphomeyaml pull request #2237
Opened 2021-09-04 11:24 UTC by ayufan

# What does this implement/fix? 

This uses a `esp32` built-in web-server after the https://github.com/easytarget/esp32-cam-webserver.
This works well for various reasons:

- in general passing `mjpg` stream is bandwidth intensive, so server working in a single threaded mode
   ensures that ESP32 is not overloaded with requests, rather they backlog
- the separate snapshot server is proposed due to above limitation, as: a single stream is allowed, but a snapshot
   is fast to execute so requests for snapshot can be backlogged on a socket
- the separate snapshot server makes it possible to send stream and occasionally from time to time offer a snapshot
   for asking client
- the data are accessed via `GET http://<ip>:<port>/`
- a binary semaphore is used to not use sleep-loop-wait approach
- the `esp32` built-in webserver runs on a `core 0` so no additional synchronization is needed

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/960

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> (to be added)

## Test Environment

- [x] ESP32

## Example entry for `config.yaml`:

```yaml
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-09-13 08:10 UTC, OttoWinter commented on esphome/components/esp32_camera_web_server/web_server.h
> +class WebServer : public Component {
```suggestion
class CameraWebServer : public Component {
```

Would be better to prevent confusion with the `web_server` component.

2021-09-13 08:11 UTC, OttoWinter commented on esphome/components/esp32_camera_web_server/web_server.cpp
> +#endif
This include isn't used anywhere

2021-09-13 08:14 UTC, OttoWinter commented on esphome/components/esp32_camera_web_server/web_server.cpp
> +    xSemaphoreTake(this->semaphore_, IMAGE_REQUEST_TIMEOUT / portTICK_PERIOD_MS);
Does the web server execute in another task or does this block the main task?

If it's the latter, we should spawn the http server in a separate task (on ESP32 we have those).

2021-09-13 08:16 UTC, ayufan commented on esphome/components/esp32_camera_web_server/web_server.cpp
> +    xSemaphoreTake(this->semaphore_, IMAGE_REQUEST_TIMEOUT / portTICK_PERIOD_MS);
It runs separate task. It still runs processing on core 0, but due to extensive yielding since most of code is doing reads/writes it works well with esphome in non-interruptive way.

2021-09-13 08:18 UTC, ayufan commented on esphome/components/esp32_camera_web_server/web_server.cpp
> +    xSemaphoreTake(this->semaphore_, IMAGE_REQUEST_TIMEOUT / portTICK_PERIOD_MS);
Unrelated to this discussion, but there's a few people that tried that already in different scenarios: https://github.com/esphome/feature-requests/issues/960#issuecomment-914965129.

2021-09-13 09:28 UTC, OttoWinter commented on esphome/components/esp32_camera_web_server/web_server.cpp
> +    xSemaphoreTake(this->semaphore_, IMAGE_REQUEST_TIMEOUT / portTICK_PERIOD_MS);
Ah nice, sounds good!

2021-09-20 07:58 UTC, jesserockz commented
I have been running this on an esp32cam for a week or so with no issues. Frigate is able to detect and record with it =)

Please address the comments above and add docs so we can get this in =)

2021-10-04 09:45 UTC, ayufan commented
@jesserockz Will do, you need to wait about 2-3 more weeks till I get back home :)

2021-11-07 10:07 UTC, ayufan commented
@OttoWinter @jesserockz This PR is updated with latest fixes to avoid usage of chunked encoding. Some clients do not like it. 

I integrated all changes (retaining original commits) from https://github.com/esphome/esphome/pull/2543. This is also why we see the @jesserockz changes made to `esp32_camera` adding `internal:` modifier.

Tested on my ESP32. Continues to work fine. Now back to docs.

2021-11-09 22:54 UTC, jesserockz requested changes
A couple of things can be reverted in the camera file, but otherwise good to go.

2021-11-09 22:54 UTC, jesserockz commented on esphome/components/esp32_camera/__init__.py
> +        cv.Optional(CONF_DISABLED_BY_DEFAULT, default=False): cv.boolean,
These can actually be removed from here now as they are in `cv.ENTITY_BASE_SCHEMA`
```suggestion
```

2021-11-09 22:54 UTC, jesserockz commented on esphome/components/esp32_camera/__init__.py
> +    cg.add(var.set_internal(config[CONF_INTERNAL]))
This can be reverted as handled in `setup_entity`

```suggestion
    var = cg.new_Pvariable(config[CONF_ID])
    await setup_entity(var, config)
```

2021-11-09 22:54 UTC, jesserockz commented on esphome/components/esp32_camera/__init__.py
> +    CONF_NAME,
Not needed after other changes
```suggestion
    CONF_FREQUENCY,
    CONF_ID,
```

2021-11-09 22:59 UTC, ayufan commented
@jesserockz Pushed commit with revert of `__init__.py` items.

2021-11-10 00:09 UTC, jesserockz approved these changes
Thanks, LGTM

2021-11-10 00:10 UTC, merged