t6615: tolerate sensor dropping commands
OttoWinter/esphomeyaml pull request #2255
Opened 2021-09-07 18:36 UTC by jasstrong

The Amphenol T6615 has a built-in calibration system which means that
the sensor could go away for a couple of seconds to figure itself out.
While this is happening, commands are silently dropped.

This caused the previous version of this code to lock up completely,
since there was no way for the command_ state machine to tick back to
the NONE state.

Instead of just breaking the state machine, which might be harmful on
a multi-core or multi-threaded device, add a timestamp and only break
the lock if it's been more than a second since the command was issued.

The command usually doesn't take more than a few milliseconds to
complete, so this should not affect things unduly.

While we're at it, rewrite the rx side to be more robust against
bytes going missing.

Instead of reading in the data essentially inline, read into a buffer
and process it when enough has been read to make progress.

Reset the buffer index when you issue a new command.  If data stops
coming when we expect it to, have a timeout that sends a new command.

## Types of changes

- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ x ] ESP8266

## Checklist:
  - [ x ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-09-07 18:51 UTC, tylermenezes commented
Interesting, I have not had this problem with my board. I can validate against mine next week if you want me to double-check that it doesn't cause any new problems.

2021-09-07 18:53 UTC, jasstrong commented
Possibly mine has different firmware in it.

> On Sep 7, 2021, at 11:51, Tyler Menezes ***@***.***> wrote:
> 
> 
> Interesting, I have not had this problem with my board. I can validate against mine next week if you want me to double-check that it doesn't cause any new problems.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/esphome/esphome/pull/2255#issuecomment-914543504>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAWOVE3T53VHNHU6AKR4YRTUAZNLTANCNFSM5DS6XF5Q>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
>

2021-09-07 19:48 UTC, jasstrong commented
I've actually run this over the weekend on my sensor and it seems to be completely reliable.  It also won't hold up loop() for long periods of time in case electrical noise causes characters on the serial line to be dropped.

2021-09-07 20:51 UTC, jasstrong commented
@tylermenezes I've fixed up all the formatting nits, PTAL.

2021-09-07 22:22 UTC, tylermenezes commented
I have no insight or permission to merge your PR, sorry

2021-09-09 18:38 UTC, oxan commented on esphome/components/t6615/t6615.cpp
> +      this->write_array(T6615_COMMAND_GET_PPM, sizeof(T6615_COMMAND_GET_PPM));
This duplicates code from `query_ppm_()`. I'd move the `if` that's in there to `update` and call that one instead here.

2021-09-09 18:38 UTC, oxan commented on esphome/components/t6615/t6615.cpp
> +  }
I'm not too fond of the manual partial reads and buffer management. Instead, would it be possible to do something like this?
```
if (available < length of response) {
  if (command issued too long ago) {
    read all available bytes from uart;
    issue new command;
  }
  return;
}

response = read_array(length of response);
handle response;
```

2021-09-09 19:37 UTC, kbx81 commented on esphome/components/t6615/t6615.cpp
> +    if (this->command_ == T6615Command::GET_PPM && millis() - this->command_time_ > T6615_TIMEOUT) {
I've run into unexpected behavior when combining comparisons, boolean operators, and math operations such as this. I strongly encourage use of parenthesis in statements like this. I suggest this:

`if ((this->command_ == T6615Command::GET_PPM) && ((millis() - this->command_time_) > T6615_TIMEOUT))`

...Of course, I'm assuming this is what you actually want of it. 😄

2021-09-09 19:39 UTC, kbx81 commented on esphome/components/t6615/t6615.cpp
> +  if (this->response_buffer_[0] != T6615_MAGIC || this->response_buffer_[1] != T6615_ADDR_HOST) {
Same as my comment above. I assume you mean this:

`if ((this->response_buffer_[0] ≠ T6615_MAGIC) || (this->response_buffer_[1] != T6615_ADDR_HOST))`

2021-09-09 19:40 UTC, jasstrong commented on esphome/components/t6615/t6615.cpp
> +  if (this->response_buffer_[0] != T6615_MAGIC || this->response_buffer_[1] != T6615_ADDR_HOST) {
yes, operator precedence actually makes it evaluate this way in any case but it doesn't hurt to make it more explicit.

2021-09-11 04:27 UTC, jasstrong commented on esphome/components/t6615/t6615.cpp
> +      this->write_array(T6615_COMMAND_GET_PPM, sizeof(T6615_COMMAND_GET_PPM));
I think it's cleaner just to extract it as a function and call it in both places.

2021-09-11 04:51 UTC, jasstrong commented on esphome/components/t6615/t6615.cpp
> +  }
Yes, that's a good idea.  I wasn't sure if this would lead to us losing responses due to loop() polls happening while data were still arriving, but we can always just fire another command if that happens.

2021-09-11 04:52 UTC, jasstrong commented on esphome/components/t6615/t6615.cpp
> +  if (this->response_buffer_[0] != T6615_MAGIC || this->response_buffer_[1] != T6615_ADDR_HOST) {
I think I'm going to leave it the way it is, because I think the formatting makes it clear what's going to happen.

2021-09-11 04:53 UTC, jasstrong commented on esphome/components/t6615/t6615.cpp
> +      this->write_array(T6615_COMMAND_GET_PPM, sizeof(T6615_COMMAND_GET_PPM));
...and I've actually added a third place where it can be called, so that works out nicer.

2021-09-11 05:14 UTC, jasstrong commented
@oxan I fixed it up to take your suggested changes into account.  I've tested it and the code appears to work as expected.

2021-09-11 11:19 UTC, oxan commented on esphome/components/t6615/t6615.cpp
> +      this->write_array(T6615_COMMAND_GET_PPM, sizeof(T6615_COMMAND_GET_PPM));
Yeah, that's fine too, it's basically the same anyway except for the update() -> query_ppm() call.

2021-09-11 11:22 UTC, oxan commented on esphome/components/t6615/t6615.cpp
> +  }
If `loop()` gets called while data is still arriving, there won't be enough data available to handle it and it'll just return. It gets called every 16ms, so there's plenty of chances to read the data before another command is issued.

2021-09-11 11:28 UTC, oxan requested changes
Great, looks good. Just some minor comments remaining.

2021-09-11 11:28 UTC, oxan commented on esphome/components/t6615/t6615.cpp
> +        this->read_byte(this->response_buffer_);
We don't care about these bytes, so let's not bother storing it.
```suggestion
      while (this->available())
        this->read();
```

2021-09-11 11:28 UTC, oxan commented on esphome/components/t6615/t6615.cpp
> +  this->read_array(this->response_buffer_, 5);
As `this->response_buffer_` is only used in this function, we can just put it on the stack instead:
```suggestion
  uint8_t response_buffer[6];
  this->read_array(this->response_buffer, 5);
```
(This also needs changes further down, and the removal of the `response_buffer_` class member).

2021-09-11 11:28 UTC, oxan commented on esphome/components/t6615/t6615.cpp
> +    ESP_LOGW(TAG, "Got bad data from T6615!");
Historically we've sometimes seen fake copies of sensors that send different magic, it might be useful to log the mismatching part of the response:
```suggestion
    ESP_LOGW(TAG, "Got bad data from T6615, response started with %02X %02X!", response_buffer[0], response_buffer[1]);
```

2021-09-11 17:52 UTC, jasstrong commented on esphome/components/t6615/t6615.cpp
> +  }
I guess that if we want to add support for other commands we'll have to have a table of their expected response lengths and index into that here, but that's okay, we burn that bridge when we come to it.

2021-09-11 17:54 UTC, jasstrong commented on esphome/components/t6615/t6615.cpp
> +  this->read_array(this->response_buffer_, 5);
I don't think I need the `this->` in that case either, so I'll remove it.

2021-09-11 17:55 UTC, jasstrong commented on esphome/components/t6615/t6615.cpp
> +        this->read_byte(this->response_buffer_);
Done.

2021-09-11 17:55 UTC, jasstrong commented on esphome/components/t6615/t6615.cpp
> +    ESP_LOGW(TAG, "Got bad data from T6615!");
I separated out the magic and address to make it clearer what's different.

2021-09-11 18:18 UTC, oxan approved these changes
Nice work!

2021-09-11 18:18 UTC, oxan commented on esphome/components/t6615/t6615.cpp
> +  this->read_array(this->response_buffer_, 5);
Yeah, definitely, you're right, I missed changing that in the suggestion.

2021-09-13 07:54 UTC, merged