Feat nonaddressable light partition
OttoWinter/esphomeyaml pull request #2256
Opened 2021-09-08 03:55 UTC by paulmonigatti

# What does this implement/fix? 

This PR allows non-addressable lights to be included as a segment in an addressable light partition.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:
```yaml
# Example configuration entry
light:
  - platform: partition
    name: "Partition Light"
    segments:
      - id: light1
        from: 0
        to: 9

      # Add light2 as the 11th light in the partition
      - id: light2

  # Example Addressable Light
  - platform: fastled_clockless
    id: light1
    # Other settings

  # Example Non-addressable Light
  - platform: rgb
    id: light2
    # Other settings
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-09-08 05:28 UTC, jesserockz reviewed
Nice work. 

I feel like the validation needs to be a bit more robust to stop a bad config for an addressable from failing over to a non-addressable light config.

2021-09-08 06:13 UTC, paulmonigatti commented
Thanks Jesse! I've removed the unnecessary fields from the schema. Would it be preferable to require lights to be explicitly marked as non-addressable?

2021-09-08 07:27 UTC, jesserockz reviewed
Awesome!

Not sure of the best way to stop the addressable falling down since `light.AddressableLightState` extends `light.LightState`.

Perhaps a validation to say it must be a `light.LightState` but not a `light.AddressableLightState` type?

2021-09-08 09:27 UTC, oxan requested changes
I was also working on this, took the more involved approach of eliminating `get_view_internal` and converting it to a call-based interface though (also for other reasons). But that is quite a bit more work and is not ready yet :laughing: 

This seems to be an acceptable albeit somewhat hacky solution in the interim.

2021-09-08 09:27 UTC, oxan commented on esphome/components/light/addressable_light_wrapper.h
> +    call.set_color_brightness_if_supported(1.0f);
I think `brightness` should be set to color brightness instead. For example if RGB = 0.5, W = 1, currently brightness will be set to 0.5 so the output for the white channel will be 0.5 instead of the requested 1.

2021-09-08 09:27 UTC, oxan commented on esphome/components/partition/light.py
> +                    cv.All(
```suggestion
                    cv.Schema(
```

2021-09-08 10:06 UTC, jesserockz commented
> This seems to be an acceptable albeit somewhat hacky solution in the interim.

Yeah the internals are easier to change later, it's the schema that we want to get right so people don't have to keep changing yaml =)

2021-09-08 10:08 UTC, paulmonigatti commented
Cheers Oxan! Good spotting. I've made the changes. I definitely agree that it's not the most elegant solution; I look forward to seeing the results of the overhaul!

There's still the question of whether `light.AddressableLightState` should be allowed by the validator when `from` and `to` are not specified. As is, the wrapper will be applied and hence treat the light as if it weren't addressable. This may be a valid use case if individual LED control of a particular segment is not desired.

2021-09-08 10:10 UTC, jesserockz commented
Perhaps we can change the FROM and TO to be optional and just include the full range if it is not specified?

2021-09-08 10:35 UTC, paulmonigatti commented
> Perhaps we can change the FROM and TO to be optional and just include the full range if it is not specified?

I had thought this too, perhaps having `FROM` default to zero and `TO` being the final LED in the segment so that neither, one, or both of these could be specified as needed.

2021-09-13 07:46 UTC, OttoWinter commented on esphome/components/partition/light.py
> +                cv.Any(
This matching logic needs to be updated.

If `cv.Any` throws an invalid error, only the last error is shown to the user. Meaning if the user uses the "normal" style but `validate_from_to` fails, they would only get the error message from the second schema.

Perhaps it's better to make it more explicit like instead of `id` have `single_light_id: my_light`. Then we can know which type the user wanted.

2021-09-13 07:47 UTC, OttoWinter commented on esphome/components/partition/light.py
> +            await cg.register_component(light_state, conf)
If `register_component` is called the schema should also extend `.extend(cv.COMPONENT_SCHEMA)` above

2021-09-16 07:57 UTC, paulmonigatti commented on esphome/components/partition/light.py
> +                cv.Any(
Oh that makes sense. I've updated it to use single_light_id to more accurately guess the user's intentions.

2021-09-16 07:58 UTC, paulmonigatti commented on esphome/components/partition/light.py
> +            await cg.register_component(light_state, conf)
Done!

2021-09-22 01:57 UTC, jesserockz approved these changes

2021-09-22 01:59 UTC, merged