Tuya: add cover component
OttoWinter/esphomeyaml pull request #2279
Opened 2021-09-12 13:15 UTC by marmarek

# What does this implement/fix? 

Add support for simple Tuya cover (tested on M515EGWT).
This one is a basic support for just position id.

Initially I tried tuya light + template cover for this, but couldn't solve feedback loop issue (light reported current "brightness" value, and then it saved it back as the new target value, basically stopping the motion). It turns out, adding proper "cover" component wasn't that hard.

My device has also a switch datapoint, but I couldn't figure out what it does.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1466

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
cover:
  - platform: "tuya"
    name: "Cover"
    position_datapoint: 2
    max_value: 100
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-09-13 07:31 UTC, OttoWinter reviewed
LGTM, but I don't know tuya well. can you check @jesserockz if the tuya part is ok?

2021-09-15 17:06 UTC, kroimon requested changes

2021-09-15 17:06 UTC, kroimon commented on esphome/components/tuya/cover/__init__.py
> +        cg.add(var.set_position_id(config[CONF_POSITION_DATAPOINT]))
`CONF_POSITION_DATAPOINT` is required, no need for the `if`.

```suggestion
    cg.add(var.set_position_id(config[CONF_POSITION_DATAPOINT]))
```

2021-09-15 17:06 UTC, kroimon commented on esphome/components/tuya/cover/__init__.py
> +            cv.Optional(CONF_MAX_VALUE): cv.int_,
From [Contributing / Config Validation](https://esphome.io/guides/contributing.html#config-validation):
> All default values should be defined in the schema (and not in C++ codebase or other code parts).

So add the defaults of 0 and 100 here instead.

```suggestion
            cv.Optional(CONF_MIN_VALUE, default=0): cv.uint32_t,
            cv.Optional(CONF_MAX_VALUE, default=100): cv.uint32_t,
```

2021-09-15 17:06 UTC, kroimon commented on esphome/components/tuya/cover/__init__.py
> +        cg.add(var.set_max_value(config[CONF_MAX_VALUE]))
If the defaults are in the schema, you don't need to check if they are set here:
```suggestion
    cg.add(var.set_min_value(config[CONF_MIN_VALUE]))
    cg.add(var.set_max_value(config[CONF_MAX_VALUE]))
```

2021-09-15 17:06 UTC, kroimon commented on esphome/components/tuya/cover/tuya_cover.cpp
> +      auto pos = float(datapoint.value_uint) / this->max_value_;
This doesn't respect `this->min_value_`!

2021-09-15 21:44 UTC, marmarek commented on esphome/components/tuya/cover/tuya_cover.cpp
> +      auto pos = float(datapoint.value_uint) / this->max_value_;
Oh, actually the whole min_value handling is broken. It should make position (0.0, 1.0) range be translated to (min_value, max_value) range linearly, instead of just cutting it at min_value (which with min_value for example 30, would mean positions 0.0-0.3 would be dead).

2021-09-15 23:44 UTC, marmarek commented
I've force pushed update that addresses the above, including proper min_value handling.

2021-09-22 09:45 UTC, oxan approved these changes
Code LGTM, but could use feedback from someone a bit more familar with the Tuya code. @jesserockz ?

2021-09-22 09:45 UTC, oxan commented on esphome/components/tuya/cover/tuya_cover.h
> +  bool invert_position_ = false;
Just a style thing, we generally don't intiailize members by assignment:
```suggestion
  uint32_t min_value_{0};
  uint32_t max_value_{100};
  uint32_t value_range_;
  bool invert_position_{false};
```

2021-09-28 20:41 UTC, jesserockz commented on esphome/components/tuya/cover/tuya_cover.h
> +  bool invert_position_ = false;
I am fine with either. `=` is more familiar to a lot of people =)

2021-09-28 20:41 UTC, jesserockz approved these changes
LGTM

2021-09-28 20:52 UTC, kroimon commented on esphome/components/tuya/cover/tuya_cover.h
> +  bool invert_position_ = false;
According to the guidelines on esphome.io, initialization should not happen in code. All default values should only be part of the python configuration schema...

2021-09-28 21:02 UTC, merged

2021-09-28 22:56 UTC, jesserockz commented on esphome/components/tuya/cover/tuya_cover.h
> +  bool invert_position_ = false;
#2415 =)