convert SCD30 into Component, polls dataready register
OttoWinter/esphomeyaml pull request #2308
Opened 2021-09-14 20:36 UTC by geoffrey-vl

# What does this implement/fix? 

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2410

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

sensor:
  - platform: scd30
    co2:
      name: "Slaapkamer CO2"
      accuracy_decimals: 1
    temperature:
      name: "Slaapkamer Temperature"
      accuracy_decimals: 2
    humidity:
      name: "Slaapkamer Humidity"
      accuracy_decimals: 1
    address: 0x61
    i2c_id: bus_a
    update_interval: 120s
    temperature_offset: 1.5 °C
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-09-16 17:51 UTC, geoffrey-vl commented
Debug output showing device is running with 120s interval:

```
[18:36:50][I][logger:170]: Log initialized
[18:36:50][C][status_led:014]: Setting up Status LED...
[18:36:50][C][ota:378]: There have been 0 suspected unsuccessful boot attempts.
[18:36:50][I][app:029]: Running through setup()...
[18:36:50][C][adc:058]: Setting up ADC 'Wireless CO2 sensor battery voltage'...
[18:36:50][C][scd30:024]: Setting up scd30...
[18:36:50][D][scd30:044]: SCD30 Firmware v3.66
[18:36:50][C][wifi:037]: Setting up WiFi...
[18:36:50][D][wifi:380]: Starting scan...
[18:36:50][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.16V
[18:36:50][D][sensor:131]: 'Wireless CO2 sensor battery voltage': Sending state 3.74174 V with 2 decimals of accuracy
[18:36:50][D][scd30:172]: Got CO2=972.93ppm temperature=22.43°C humidity=72.31%
[18:36:50][D][sensor:131]: 'Slaapkamer CO2': Sending state 972.93463 ppm with 1 decimals of accuracy
[18:36:51][D][sensor:131]: 'Slaapkamer Temperature': Sending state 22.42831 °C with 2 decimals of accuracy
[18:36:51][D][sensor:131]: 'Slaapkamer Humidity': Sending state 72.30956 % with 1 decimals of accuracy
[18:36:52][D][wifi:395]: Found networks:
[18:36:52][I][wifi:250]: WiFi Connecting to ''...
[18:36:54][W][wifi_esp32:438]: Event: Disconnected ssid='' reason='Probe Request Unsuccessful'
[18:36:54][W][wifi:560]: WiFi network can not be found anymore.
[18:36:54][W][wifi:585]: Restarting WiFi adapter...
[18:36:54][I][wifi:250]: WiFi Connecting to ''...
[18:36:55][I][wifi:513]: WiFi Connected!
[18:36:55][C][wifi:359]:   SSID: ''
[18:36:55][C][wifi:360]:   IP Address: 
[18:36:55][C][wifi:362]:   BSSID: 
[18:36:55][C][wifi:363]:   Hostname: 'wireless-air-quality-sensor'
[18:36:55][C][wifi:367]:   Signal strength: -53 dB ▂▄▆█
[18:36:55][C][wifi:371]:   Channel: 11
[18:36:55][C][wifi:372]:   Subnet: 
[18:36:55][C][wifi:373]:   Gateway: 
[18:36:55][C][wifi:374]:   DNS1: 
[18:36:55][C][wifi:375]:   DNS2: 
[18:36:55][D][wifi:522]: Disabling AP...
[18:36:55][C][ota:029]: Over-The-Air Updates:
[18:36:55][C][ota:030]:   Address: wireless-air-quality-sensor.local:3232
[18:36:55][C][ota:032]:   Using Password.
[18:36:55][C][api:022]: Setting up Home Assistant API server...
[18:36:55][I][app:060]: setup() finished successfully!
[18:36:55][I][app:106]: ESPHome version 2021.8.2 compiled on Sep 14 2021, 18:34:02
[18:36:55][C][status_led:019]: Status LED:
[18:36:55][C][status_led:020]:   Pin: GPIO5 (Mode: OUTPUT)
[18:36:56][C][wifi:499]: WiFi:
[18:36:56][C][wifi:359]:   SSID: ''
[18:36:56][C][wifi:360]:   IP Address: 
[18:36:56][C][wifi:362]:   BSSID: 
[18:36:56][C][wifi:363]:   Hostname: 'wireless-air-quality-sensor'
[18:36:56][C][wifi:367]:   Signal strength: -52 dB ▂▄▆█
[18:36:56][C][wifi:371]:   Channel: 11
[18:36:56][C][wifi:372]:   Subnet: 
[18:36:56][C][wifi:373]:   Gateway: 
[18:36:56][C][wifi:374]:   DNS1: 
[18:36:56][C][wifi:375]:   DNS2: 
[18:36:56][C][i2c:028]: I2C Bus:
[18:36:56][C][i2c:029]:   SDA Pin: GPIO21
[18:36:56][C][i2c:030]:   SCL Pin: GPIO22
[18:36:56][C][i2c:031]:   Frequency: 50000 Hz
[18:36:56][I][i2c:033]: Scanning i2c bus for active devices...
[18:36:56][I][i2c:040]: Found i2c device at address 0x61
[18:36:56][C][logger:189]: Logger:
[18:36:56][C][logger:190]:   Level: DEBUG
[18:36:56][C][logger:191]:   Log Baud Rate: 115200
[18:36:56][C][logger:192]:   Hardware UART: UART0
[18:36:56][C][adc:072]: ADC Sensor 'Wireless CO2 sensor battery voltage'
[18:36:56][C][adc:072]:   Device Class: 'voltage'
[18:36:56][C][adc:072]:   State Class: 'measurement'
[18:36:56][C][adc:072]:   Unit of Measurement: 'V'
[18:36:56][C][adc:072]:   Accuracy Decimals: 2
[18:36:56][C][adc:081]:   Pin: 35
[18:36:56][C][adc:093]:  Attenuation: 11db (max 3.9V)
[18:36:56][C][adc:099]:   Update Interval: 60.0s
[18:36:56][C][scd30:100]: scd30:
[18:36:56][C][scd30:101]:   Address: 0x61
[18:36:56][C][scd30:119]:   Altitude compensation: OFF
[18:36:56][C][scd30:123]:   Automatic self calibration: ON
[18:36:56][C][scd30:124]:   Ambient pressure compensation: 0mBar
[18:36:56][C][scd30:125]:   Temperature offset: 1.50 °C
[18:36:56][C][scd30:126]:   Update Interval: 120.0s
[18:36:56][C][scd30:127]:   CO2 'Slaapkamer CO2'
[18:36:56][C][scd30:127]:     State Class: 'measurement'
[18:36:56][C][scd30:127]:     Unit of Measurement: 'ppm'
[18:36:56][C][scd30:127]:     Accuracy Decimals: 1
[18:36:56][C][scd30:127]:     Icon: 'mdi:molecule-co2'
[18:36:56][C][scd30:128]:   Temperature 'Slaapkamer Temperature'
[18:36:56][C][scd30:128]:     Device Class: 'temperature'
[18:36:56][C][scd30:128]:     State Class: 'measurement'
[18:36:56][C][scd30:128]:     Unit of Measurement: '°C'
[18:36:56][C][scd30:128]:     Accuracy Decimals: 2
[18:36:56][C][scd30:129]:   Humidity 'Slaapkamer Humidity'
[18:36:56][C][scd30:129]:     Device Class: 'humidity'
[18:36:56][C][scd30:129]:     State Class: 'measurement'
[18:36:56][C][scd30:129]:     Unit of Measurement: '%'
[18:36:56][C][scd30:129]:     Accuracy Decimals: 1
[18:36:56][C][captive_portal:148]: Captive Portal:
[18:36:56][C][ota:029]: Over-The-Air Updates:
[18:36:56][C][ota:030]:   Address: wireless-air-quality-sensor.local:3232
[18:36:56][C][ota:032]:   Using Password.
[18:36:56][C][api:095]: API Server:
[18:36:56][C][api:096]:   Address: wireless-air-quality-sensor.local:6053
[18:36:57][D][api.connection:730]: Client 'Home Assistant 2021.4.4 ()' connected successfully!
[18:37:42][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.16V
[18:37:42][D][sensor:131]: 'Wireless CO2 sensor battery voltage': Sending state 3.74010 V with 2 decimals of accuracy
[18:38:07][D][scd30:172]: Got CO2=970.24ppm temperature=22.41°C humidity=72.10%
[18:38:07][D][sensor:131]: 'Slaapkamer CO2': Sending state 970.23895 ppm with 1 decimals of accuracy
[18:38:07][D][sensor:131]: 'Slaapkamer Temperature': Sending state 22.40813 °C with 2 decimals of accuracy
[18:38:07][D][sensor:131]: 'Slaapkamer Humidity': Sending state 72.09640 % with 1 decimals of accuracy
[18:38:42][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.17V
[18:38:42][D][sensor:131]: 'Wireless CO2 sensor battery voltage': Sending state 3.75822 V with 2 decimals of accuracy
[18:39:42][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.18V
[18:39:42][D][sensor:131]: 'Wireless CO2 sensor battery voltage': Sending state 3.76316 V with 2 decimals of accuracy
[18:40:07][D][scd30:172]: Got CO2=958.89ppm temperature=22.37°C humidity=72.13%
[18:40:07][D][sensor:131]: 'Slaapkamer CO2': Sending state 958.88702 ppm with 1 decimals of accuracy
[18:40:07][D][sensor:131]: 'Slaapkamer Temperature': Sending state 22.36981 °C with 2 decimals of accuracy
[18:40:07][D][sensor:131]: 'Slaapkamer Humidity': Sending state 72.12508 % with 1 decimals of accuracy
[18:40:42][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.17V
[18:40:42][D][sensor:131]: 'Wireless CO2 sensor battery voltage': Sending state 3.75987 V with 2 decimals of accuracy
[18:41:42][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.18V
[18:41:42][D][sensor:131]: 'Wireless CO2 sensor battery voltage': Sending state 3.76646 V with 2 decimals of accuracy
[18:41:50][I][ota:046]: Boot seems successful, resetting boot loop counter.
[18:42:07][D][scd30:172]: Got CO2=954.75ppm temperature=22.28°C humidity=72.49%
[18:42:07][D][sensor:131]: 'Slaapkamer CO2': Sending state 954.75385 ppm with 1 decimals of accuracy
[18:42:07][D][sensor:131]: 'Slaapkamer Temperature': Sending state 22.27975 °C with 2 decimals of accuracy
[18:42:07][D][sensor:131]: 'Slaapkamer Humidity': Sending state 72.49324 % with 1 decimals of accuracy
[18:42:42][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.18V
[18:42:42][D][sensor:131]: 'Wireless CO2 sensor battery voltage': Sending state 3.76975 V with 2 decimals of accuracy
[18:43:42][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.18V
[18:43:42][D][sensor:131]: 'Wireless CO2 sensor battery voltage': Sending state 3.77470 V [...]

2021-09-22 09:34 UTC, oxan commented on esphome/components/scd30/scd30.cpp
> +  });
Maybe I'm missing something, but how does this work? On setup this timeout it set, which rearms itself as long as there's no data ready. When there's data ready, `update()` is called, which reads the data, but doesn't rearm this timeout. Won't that result in just one sample being read?

2021-09-22 12:27 UTC, geoffrey-vl commented on esphome/components/scd30/scd30.cpp
> +  });
I've based that part of the implementation on the [cs5460a](https://github.com/esphome/esphome/blob/501f88ca8645ef0e7ca3e537e2e69688636e6e90/esphome/components/cs5460a/cs5460a.cpp) component which does something likewise. 
But you're correct it seems like an error, I also concluded that earlier this week when I reviewed my own code. I need to dig deeper on what part of ESPHome triggers the update() method after all. **For now don't merge this PR**!

2021-09-22 12:33 UTC, oxan commented on esphome/components/scd30/scd30.cpp
> +  });
`update()` is only automatically called for `PollingComponent`s (every update_interval). As this component no longer is a PollingComponent, update() won't ever be called automatically now -- that's your responsibility now. 

I would suggest making this an interval.

> I've based that part of the implementation on the cs5460a component which does something likewise.

The cs5460a component unconditonally re-arms the timeout.

> For now don't merge this PR!

I've marked this PR as a draft to make that clear, you can convert it back when it is ready.

2021-09-22 18:39 UTC, geoffrey-vl commented on esphome/components/scd30/scd30.cpp
> +  });
@oxan , I've noticed that the src files that make the firmware are being generated, and that the generated header and source files for SCD30 were still based upon the `PollingComponent`. So I guess that explains why the code wasn't producing errors. I've removed the generated folder and rebuild but I'm getting the same result: PollingComponent. Any clue what is going on here?

2021-09-23 19:37 UTC, oxan commented on esphome/components/scd30/scd30.cpp
> +  });
> So even though I'm mapping my working dir into the container it now seems be only required for passing through the .yaml file into the container, and nothing else. Correct me if I'm wrong.

Yes, that's correct, the Docker container contains its own copy of the source code.

> I was hoping not to have to contaminate my host os with all sorts of python dependencies, I hoped the docker container would give me an isolated dev environment.

I think that's possible with the devcontainer, but I'm not too familar with how all that works.

2021-09-23 20:12 UTC, geoffrey-vl commented on esphome/components/scd30/scd30.cpp
> +  });
Now that I'm all setup and done I've noticed that there is indeed a problem with the implementation. As we both concluded, `update()` gets called only once. That aside checking if data was ready was also not going well. I've now solved those issues. Underneath is a log output. I've added an extra log line (cfr. `SCD30 update()` that indicates that I'm indeed running the code that I've adjusted myself. I've however excluded that line when committing.

My first though is that it is running fine. The update interval is set to 120s. One thing I notice is that the interval is not always exactly 120s. I believe that's something with the sensor itself though.

```
INFO Starting log output from /dev/ttyUSB0 with baud rate 115200
[21:46:26][I][logger:174]: Log initialized
[21:46:26][C][status_led:014]: Setting up Status LED...
[21:46:26][C][ota:379]: There have been 0 suspected unsuccessful boot attempts.
[21:46:26][I][app:029]: Running through setup()...
[21:46:26][C][adc:058]: Setting up ADC 'Wireless CO2 sensor battery voltage'...
[21:46:26][C][scd30:024]: Setting up scd30...
[21:46:26][D][scd30:044]: SCD30 Firmware v3.66
[21:46:26][C][wifi:037]: Setting up WiFi...
[21:46:26][I][wifi:250]: WiFi Connecting to ''...
[21:46:26][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.37V
[21:46:26][D][sensor:121]: 'Wireless CO2 sensor battery voltage': Sending state 4.10587 V with 2 decimals of accuracy

[21:46:27][D][scd30:145]: SCD30 update()
[21:46:27][D][scd30:179]: Got CO2=926.93ppm temperature=21.84°C humidity=65.27%
[21:46:27][D][sensor:121]: 'Slaapkamer CO2': Sending state 926.92731 ppm with 1 decimals of accuracy
[21:46:27][D][sensor:121]: 'Slaapkamer Temperature': Sending state 21.83788 °C with 2 decimals of accuracy
[21:46:27][D][sensor:121]: 'Slaapkamer Humidity': Sending state 65.27382 % with 1 decimals of accuracy
[21:46:29][I][wifi:510]: WiFi Connected!
[21:46:29][C][wifi:359]:   SSID: ''
[21:46:29][C][wifi:360]:   IP Address: 
[21:46:29][C][wifi:362]:   BSSID: 
[21:46:29][C][wifi:363]:   Hostname: 'wireless-air-quality-sensor'
[21:46:29][C][wifi:365]:   Signal strength: -53 dB ▂▄▆█
[21:46:29][C][wifi:369]:   Channel: 11
[21:46:29][C][wifi:370]:   Subnet: 
[21:46:29][C][wifi:371]:   Gateway: 
[21:46:29][C][wifi:372]:   DNS1: 
[21:46:29][C][wifi:373]:   DNS2: 
[21:46:29][D][wifi:519]: Disabling AP...
[21:46:29][C][ota:029]: Over-The-Air Updates:
[21:46:29][C][ota:030]:   Address: wireless-air-quality-sensor.local:3232
[21:46:29][C][ota:032]:   Using Password.
[21:46:29][C][api:023]: Setting up Home Assistant API server...
[21:46:29][D][main:161]: Checking sleep
[21:46:29][D][main:010]: OnBoot
[21:46:29][C][deep_sleep:013]: Setting up Deep Sleep...
[21:46:29][I][app:060]: setup() finished successfully!
[21:46:29][I][app:102]: ESPHome version 2021.10.0-dev compiled on Sep 23 2021, 21:44:39
[21:46:29][C][status_led:019]: Status LED:
[21:46:29][C][status_led:020]:   Pin: GPIO5 (Mode: OUTPUT)
[21:46:30][C][wifi:496]: WiFi:
[21:46:30][C][wifi:359]:   SSID: '
[21:46:30][C][wifi:360]:   IP Address: 
[21:46:30][C][wifi:362]:   BSSID: 
[21:46:30][C][wifi:363]:   Hostname: 'wireless-air-quality-sensor'
[21:46:30][C][wifi:365]:   Signal strength: -53 dB ▂▄▆█
[21:46:30][C][wifi:369]:   Channel: 11
[21:46:30][C][wifi:370]:   Subnet: 
[21:46:30][C][wifi:371]:   Gateway: 
[21:46:30][C][wifi:372]:   DNS1: 
[21:46:30][C][wifi:373]:   DNS2: 
[21:46:30][C][i2c:029]: I2C Bus:
[21:46:30][C][i2c:030]:   SDA Pin: GPIO21
[21:46:30][C][i2c:031]:   SCL Pin: GPIO22
[21:46:30][C][i2c:032]:   Frequency: 50000 Hz
[21:46:30][I][i2c:034]: Scanning i2c bus for active devices...
[21:46:30][I][i2c:041]: Found i2c device at address 0x61
[21:46:30][C][logger:193]: Logger:
[21:46:30][C][logger:194]:   Level: DEBUG
[21:46:30][C][logger:195]:   Log Baud Rate: 115200
[21:46:30][C][logger:196]:   Hardware UART: UART0
[21:46:30][C][adc:072]: ADC Sensor 'Wireless CO2 sensor battery voltage'
[21:46:30][C][adc:072]:   Device Class: 'voltage'
[21:46:30][C][adc:072]:   State Class: 'measurement'
[21:46:30][C][adc:072]:   Unit of Measurement: 'V'
[21:46:30][C][adc:072]:   Accuracy Decimals: 2
[21:46:30][C][adc:081]:   Pin: 35
[21:46:30][C][adc:093]:  Attenuation: 11db (max 3.9V)
[21:46:30][C][adc:099]:   Update Interval: 60.0s
[21:46:30][C][scd30:112]: scd30:
[21:46:30][C][scd30:113]:   Address: 0x61
[21:46:30][C][scd30:131]:   Altitude compensation: OFF
[21:46:30][C][scd30:135]:   Automatic self calibration: ON
[21:46:30][C][scd30:136]:   Ambient pressure compensation: 0mBar
[21:46:30][C][scd30:137]:   Temperature offset: 1.50 °C
[21:46:30][C][scd30:138]:   Update interval: 120s
[21:46:30][C][scd30:139]:   CO2 'Slaapkamer CO2'
[21:46:30][C][scd30:139]:     State Class: 'measurement'
[21:46:30][C][scd30:139]:     Unit of Measurement: 'ppm'
[21:46:30][C][scd30:139]:     Accuracy Decimals: 1
[21:46:30][C][scd30:139]:     Icon: 'mdi:molecule-co2'
[21:46:30][C][scd30:140]:   Temperature 'Slaapkamer Temperature'
[21:46:30][C][scd30:140]:     Device Class: 'temperature'
[21:46:30][C][scd30:140]:     State Class: 'measurement'
[21:46:30][C][scd30:140]:     Unit of Measurement: '°C'
[21:46:30][C][scd30:140]:     Accuracy Decimals: 2
[21:46:30][C][scd30:141]:   Humidity 'Slaapkamer Humidity'
[21:46:30][C][scd30:141]:     Device Class: 'humidity'
[21:46:30][C][scd30:141]:     State Class: 'measurement'
[21:46:30][C][scd30:141]:     Unit of Measurement: '%'
[21:46:30][C][scd30:141]:     Accuracy Decimals: 1
[21:46:30][C][captive_portal:148]: Captive Portal:
[21:46:30][C][ota:029]: Over-The-Air Updates:
[21:46:30][C][ota:030]:   Address: wireless-air-quality-sensor.local:3232
[21:46:30][C][ota:032]:   Using Password.
[21:46:30][C][api:132]: API Server:
[21:46:30][C][api:133]:   Address: wireless-air-quality-sensor.local:6053
[21:46:30][C][deep_sleep:020]: Setting up Deep Sleep...
[21:46:30][C][deep_sleep:023]:   Sleep Duration: 300000 ms
[21:46:30][C][deep_sleep:026]:   Run Duration: 3600000 ms
[21:46:30][C][deep_sleep:030]:   Wakeup Pin: GPIO32 (Mode: INPUT, INVERTED)
[21:46:31][D][api:096]: Accepted 192.168.0.102
[21:46:31][D][api.connection:735]: Home Assistant 2021.4.4 (192.168.0.102): Connected successfully
[21:47:09][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.38V
[21:47:09][D][sensor:121]: 'Wireless CO2 sensor battery voltage': Sending state 4.11411 V with 2 decimals of accuracy
[21:48:09][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.38V
[21:48:09][D][sensor:121]: 'Wireless CO2 sensor battery voltage': Sending state 4.11575 V with 2 decimals of accuracy

[21:48:28][D][scd30:145]: SCD30 update()
[21:48:28][D][scd30:179]: Got CO2=924.25ppm temperature=21.77°C humidity=65.54%
[21:48:28][D][sensor:121]: 'Slaapkamer CO2': Sending state 924.25043 ppm with 1 decimals of accuracy
[21:48:28][D][sensor:121]: 'Slaapkamer Temperature': Sending state 21.77262 °C with 2 decimals of accuracy
[21:48:28][D][sensor:121]: 'Slaapkamer Humidity': Sending state 65.54207 % with 1 decimals of accuracy
[21:49:09][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.38V
[21:49:09][D][sensor:121]: 'Wireless CO2 sensor battery voltage': Sending state 4.11411 V with 2 decimals of accuracy
[21:50:09][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.38V
[21:50:09][D][sensor:121]: 'Wireless CO2 sensor battery voltage': Sending state 4.11246 V with 2 decimals of accuracy

[21:50:41][D][scd30:145]: SCD30 update()
[21:50:41][D][scd30:179]: Got CO2=928.35ppm temperature=21.76°C humidity=65.66%
[21:50:42][D][sensor:121]: 'Slaapkamer CO2': Sending state 928.35187 ppm with 1 decimals of accuracy
[21:50:42][D][sensor:121]: 'Slaapkamer Temperature': Sending state 21.76354 °C with 2 decimals of accuracy
[21:50:42][D][sensor:121]: 'Slaapkamer Humidity': Sending state 65.65794 % with 1 decimals of accuracy
[21:51:09][D][adc:104]: 'Wireless CO2 sensor battery voltage': Got voltage=2.38V
[21:51:09][D][sensor:121]: 'Wireless CO2 sensor battery voltage': Sending s [...]

2021-09-29 21:30 UTC, oxan commented on esphome/components/scd30/scd30.cpp
> +  });
> My first though is that it is running fine. The update interval is set to 120s. One thing I notice is that the interval is not always exactly 120s. I believe that's something with the sensor itself though.

The oscillator in the sensor probably isn't as accurate as the one in the ESP. I agree it's not a big problem.

2021-09-29 21:39 UTC, geoffrey-vl commented on esphome/components/scd30/scd30.cpp
> +  });
I've been running it for few days now without issues.
I also wanted to keep the configuration of the sensor untouched so that nothing gets broken for users that upgrade. What's your take upon that?

2021-09-30 13:06 UTC, oxan commented on esphome/components/scd30/scd30.cpp
> +  });
> I also wanted to keep the configuration of the sensor untouched so that nothing gets broken for users that upgrade. What's your take upon that?

Yeah, that's a good idea. 

Is there anything else that needs to be changed for this PR? If not, please mark it as ready for review again :)

2021-09-30 13:30 UTC, geoffrey-vl commented on esphome/components/scd30/scd30.cpp
> +  });
One thing: according to the datasheet... 

> The sampling interval can be set to any integer value between 1 second and 1800 seconds

Is that something we should guard in the code? Is it a compile time check? Or rather runtime check? What happens when the value is out of scope?  Or do you normally keep this for the docs only?

2021-10-12 15:20 UTC, oxan commented on esphome/components/scd30/scd30.cpp
> +  });
We should check that during config validation, e.g. by using something like this:
```python
cv.Optional(CONF_UPDATE_INTERVAL): cv.All(
   cv.time_period_seconds, 
   cv.Range(min=TimePeriod(seconds=1), max=TimePeriod(seconds=1800)
)
```

2021-10-12 18:14 UTC, geoffrey-vl commented on esphome/components/scd30/scd30.cpp
> +  });
Added that, here is the validator at work:

```
INFO Reading configuration config/wireless-air-quality-sensor.yaml...
Failed config

sensor.scd30: [source config/wireless-air-quality-sensor.yaml:57]
  platform: scd30
  co2: 
    name: Slaapkamer CO2
    accuracy_decimals: 1
    on_value: 
      then: 
        - if: 
            condition: api.connected
            then: 
              - delay: 2s
              - deep_sleep.enter: deep_sleep_esp32
  temperature: 
    name: Slaapkamer Temperature
    accuracy_decimals: 2
  humidity: 
    name: Slaapkamer Humidity
    accuracy_decimals: 1
  address: 97
  i2c_id: bus_a
  
  value must be at most 1800s.
  update_interval: 12000s [source config/wireless-air-quality-sensor.yaml:77]
  temperature_offset: 1.5 °C
```

```
INFO Reading configuration config/wireless-air-quality-sensor.yaml...
Failed config

sensor.scd30: [source config/wireless-air-quality-sensor.yaml:57]
  platform: scd30
  co2: 
    name: Slaapkamer CO2
    accuracy_decimals: 1
    on_value: 
      then: 
        - if: 
            condition: api.connected
            then: 
              - delay: 2s
              - deep_sleep.enter: deep_sleep_esp32
  temperature: 
    name: Slaapkamer Temperature
    accuracy_decimals: 2
  humidity: 
    name: Slaapkamer Humidity
    accuracy_decimals: 1
  address: 97
  i2c_id: bus_a
  
  value must be at least 1s.
  update_interval: 0s [source config/wireless-air-quality-sensor.yaml:77]
  temperature_offset: 1.5 °C
```

I'll fix the CI errors and mark it ready for review.

2021-10-13 16:15 UTC, oxan requested changes
Thanks! Looks good to me, just some suggestions for minor cleanups.

2021-10-13 16:15 UTC, oxan commented on esphome/components/scd30/scd30.cpp
> +  this->schedule_next_check_();
Instead of continuously setting a new timeout, I would suggest using an interval instead:
```suggestion
  // check each 500ms if data is ready, and read it in that case
  this->set_interval("status-check", 500, [this]() {
    if (this->is_data_ready_())
      this->update();
  });
```

2021-10-13 16:15 UTC, oxan commented on esphome/components/scd30/scd30.cpp
> +
This method can then be dropped:
```suggestion
```

2021-10-13 16:15 UTC, oxan commented on esphome/components/scd30/scd30.cpp
> +  return is_data_ready[0] == 1;
An array with a single item is unnecessary:
```suggestion
  uint16_t is_data_ready;
  if (!this->read_data_(&is_data_ready, 1)) {
    return false;
  }
  return is_data_ready == 1;
```

2021-10-13 16:15 UTC, oxan commented on esphome/components/scd30/scd30.h
> +  void schedule_next_check_();
```suggestion
```

2021-10-13 17:58 UTC, oxan approved these changes
Thanks!

2021-10-13 18:43 UTC, geoffrey-vl commented
Thank you for helping out. I've compiled these final changes and ran it in my device and found no further issues:

```
[20:31:03][D][scd30:187]: Got CO2=876.93ppm temperature=23.12°C humidity=59.08%
...
[20:33:17][D][scd30:187]: Got CO2=847.04ppm temperature=23.13°C humidity=59.22%
...
[20:35:31][D][scd30:187]: Got CO2=849.86ppm temperature=23.20°C humidity=59.12%
...
[20:37:44][D][scd30:187]: Got CO2=850.25ppm temperature=23.58°C humidity=58.34%
...
[20:39:58][D][scd30:187]: Got CO2=867.07ppm temperature=23.58°C humidity=58.38%
```

2021-10-13 19:43 UTC, jesserockz requested changes

2021-10-13 19:43 UTC, jesserockz commented on esphome/components/scd30/sensor.py
> +        cg.add(var.set_update_interval(config[CONF_UPDATE_INTERVAL]))
You have a default in the schema so no need to check `if` it is there. 
```suggestion
    cg.add(var.set_update_interval(config[CONF_UPDATE_INTERVAL]))
```

2021-10-13 19:43 UTC, jesserockz commented on esphome/components/scd30/scd30.h
> +  uint16_t update_interval_{0xFFFF};
Can also remove the default `{0xFFFF}` from the header as set_update_interval will always be called

```suggestion
  uint16_t update_interval_;
```

2021-10-14 07:29 UTC, geoffrey-vl commented on esphome/components/scd30/scd30.h
> +  uint16_t update_interval_{0xFFFF};
I prefer to have the config validation correctly as it was designed.

2021-10-30 14:09 UTC, geoffrey-vl commented
@jesserockz is there anything that I should do?

2021-10-31 02:29 UTC, jesserockz approved these changes

2021-10-31 02:29 UTC, merged