get changed files from direct upstream of current branch
OttoWinter/esphomeyaml pull request #2333
Opened 2021-09-17 16:49 UTC by martgras

fixes https://github.com/esphome/issues/issues/2439

# What does this implement/fix? 
Use direct upstream path to find the changed files

Quick description and explanation of changes

the quicklint script [hardcodes ](https://github.com/esphome/esphome/blob/8f3a739da77e06b5ef18115248ee469ed0caa95f/script/helpers.py#L68)comparing against the dev branch in the first remote it finds. 
On my fork the branch is called testing and the correct merge-base  is `refs/remotes/origin/testing` but quicklint uses `refs/remotes/origin/dev`. Because I don't have a dev branch quick-lint fails. 
But even if the branches exists quicklint tries `upstream` fist instead of `origin` and compare too many files or against the wrong branch. 
To get the upstream ref this command can be used
````
git for-each-ref --format='refs/remotes/%(upstream:short)' $(git symbolic-ref -q HEAD)
````

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2439

## Checklist:
  - [x ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-09-17 17:16 UTC, martgras commented
needs some tweaking to run the command correctly - will update tomorrow

2021-09-19 16:39 UTC, OttoWinter approved these changes
Thanks! tried these commands locally and it appears to work.

2021-09-19 16:45 UTC, OttoWinter requested changes
Hmm, this doesn't appear to work for me.

I have `origin` pointing to https://github.com/esphome/esphome.git

If I'm on my local `esp-idf` branch (commit https://github.com/esphome/esphome/commit/bd75a334c4065a848b6fc62e4e22611b0bad7d3c) and go through these commands:

- `git symbolic-ref -q HEAD` -> `refs/heads/esp-idf`
- `git for-each-ref --format "refs/remotes/%(upstream:short)" refs/heads/esp-idf` -> `refs/remotes/origin/esp-idf`
- `git merge-base refs/remotes/origin/esp-idf HEAD` -> [`bd75a334c4065a848b6fc62e4e22611b0bad7d3c`](https://github.com/esphome/esphome/commit/bd75a334c4065a848b6fc62e4e22611b0bad7d3c)

Running `git diff bd75a334c4065a848b6fc62e4e22611b0bad7d3c HEAD` is empty because HEAD _is_ `bd75a...`

but it should have been https://github.com/esphome/esphome/commit/dd3f2f6c7ebca5eb1bc2561d651b989154596ef9 (where esp-idf branched off) for comparing what files have changed against the `dev` branch

I don't quite understand what these new commands do, maybe there's something I overlooked or there's an easy fix?

2021-09-19 17:25 UTC, martgras commented
Not sure I cover all scenarios
goal:
- find the current branch
- compare to next upstream

My setup 
origin  https://github.com/martgras/esphome.git (fetch)
origin  https://github.com/martgras/esphome.git (push)
upstream        https://github.com/esphome/esphome.git (fetch)
upstream        https://github.com/esphome/esphome.git (push)


git symbolic-ref -q HEAD => refs/heads/testing  
   ok that the my branch
git for-each-ref --format "refs/remotes/%(upstream:short)" refs/heads/testing  => refs/remotes/origin/testing
   ok  => git push would go to https://github.com/martgras/esphome.git
git merge-base refs/remotes/origin/testing HEAD
when everything is fully sync => no changed files
open a local file and change it 

git diff d121c20a62c5f25a3e8901bfed3fb822c998b7d3
diff --git a/script/helpers.py b/script/helpers.py
index d32e0eaf..9d9da248 100644
--- a/script/helpers.py
+++ b/script/helpers.py
...

But for testing I created a branch from upstream esp-idf without having that branch origin : this fails because then I only get "ref/remote" back.

So I guess my commands work well in my scenario but I probably have not covered everything

2021-09-19 18:43 UTC, oxan commented
>  goal:
>     * find the current branch
>     * compare to next upstream

The problem with this approach is that when working with feature branches, I'm usually not interested in files that have changed w.r.t. the upstream branch, but in files that have changed w.r.t. the branching point. 

For example, if I create a branch, add some commits to that, and then push that branch to my fork, then the branch in my fork has become the upstream. However, if I run the lint scripts, I'm not interested in checking what has changed locally compared to what I already pushed, but I'm interested in checking all changes I made in that branch.

2021-09-20 12:50 UTC, martgras commented
@oxan I see your point. 
Although I'm rather liniting against origin before I push to my own  fork I understand that comparing to esphome upstream/dev might be more useful for others. 
At the end of the day it doesn't matter if 10 files or 1 file is checked from a performance point of view.
Closing the PR with this

2021-09-20 12:50 UTC, closed without merging