Add SML (Smart Message Language) platform
OttoWinter/esphomeyaml pull request #2396
Opened 2021-09-26 14:11 UTC by alengwenus

# What does this implement/fix? 

This PR adds support for the Smart Message Language (SML). The protocol is a common standard for most energy smart meters in Germany.

Usually those smart meters transmit the telegrams using an infrared optical interface.
A suitable photo transistor (e.g. BPW40) connected to the ESP's UART can be used as a sensor.

Although the SML protocol is well defined, it gives a lot of freedom to the manufacturers how to store
and identify the transmitted data. Within a telegram the physical values are identified by OBIS codes
(Object Identification System). If it is known which code the manufacturer assigns to the physical value,
the corresponding value can be extracted.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/feature-requests/issues/1041

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1493

## Test Environment

- [x] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example configuration entry
uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

sml:
  id: mysml
  uart_id: uart_bus

sensor:
  - platform: sml
    name: "Total energy"
    sml_id: mysml
    server_id: "0123456789abcdef"
    obis: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    filters:
      - multiply: 0.0001

text_sensor:
  - platform: sml
    name: "Manufacturer"
    sml_id: mysml
    server_id: "0123456789abcdef"
    obis: "129-129:199.130.3"
    format: text
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-09-26 23:21 UTC, jesserockz requested changes
Overall I would also prefer if `using namespace std;` was not used as it makes the code harder to understand where those things are defined, and makes it harder for people to use this code as a reference.

Also would be more consistent if `uint8_t` was used instead of `unsigned char`

2021-09-26 23:21 UTC, jesserockz commented on esphome/components/sml/__init__.py
> +sml_ns = cg.esphome_ns.namespace("esphome::sml")
```suggestion
sml_ns = cg.esphome_ns.namespace("sml")
```

2021-09-26 23:21 UTC, jesserockz commented on esphome/components/sml/text_sensor/sml_text_sensor.h
> +  SmlTextSensor(const char *server_id, const char *obis, const char *format);
```suggestion
  SmlTextSensor(std::string server_id, std::string obis, std::string format);
```

2021-09-26 23:21 UTC, jesserockz commented on esphome/components/sml/text_sensor/sml_text_sensor.cpp
> +}
This probably needs formatting as I wrote it on GitHub =)
```suggestion
SmlTextSensor::SmlTextSensor(std::string server_id, std::string obis, std::string format) : server_id(std::move(server_id)), obis(std::move(obis)), format_(std::move(format)) {}
```

2021-09-26 23:21 UTC, jesserockz commented on esphome/components/sml/sensor/sml_sensor.cpp
> +}
Change this to similar to the text_sensor suggestion

2021-09-26 23:21 UTC, jesserockz commented on esphome/components/sml/sensor/sml_sensor.h
> +  SmlSensor(const char *server_id, const char *obis);
Same as text_sensor here

2021-09-27 06:56 UTC, oxan commented on esphome/components/sml/sml_parser.cpp
> +  return code_stream.str();
We usually prefer using `sprintf` for things like this to avoid having to pull in the whole *stream libraries, which are fairly heavy (and it's more readable as well, imo).

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/__init__.py
> +CONF_OBIS = "obis"
```suggestion
CONF_OBIS_CODE = "obis_code"
```

Nit: From what I can gather "obis" (object identification system) is the name of the _system_; the individual codes should then be called `obis_id`

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/sml.cpp
> +    this->incoming_buffer_[k - 1] = this->incoming_buffer_[k];
```suggestion
  std::rotate(incoming_buffer_, incoming_buffer_ + 1, incoming_buffer_ + 8);
```

Nit: could be more idiomatic C++ (might have to pull in `#include <algorithm>`)

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/sml_parser.h
> +  const unsigned int startpos_;
```suggestion
  const size_t startpos_;
```

To keep the compiler from complaining when we support 64bit devices

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/sml_parser.h
> +  SmlBase(const bytes &buffer, unsigned int &pos);
```suggestion
  SmlBase(const bytes &buffer, size_t pos);
```

(and no need for the reference from the looks of it)

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/sml_parser.h
> +  SmlNode(const bytes &buffer, unsigned int &pos);
```suggestion
  SmlNode(const bytes &buffer, size_t &pos);
```

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/sml_parser.cpp
> +  unsigned int idx = 0;
```suggestion
  size_t len = buffer.size() - 2;
  size_t idx = 0;
```

There should also be a check for underflow of `len` here

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/sml_parser.cpp
> +  while (len--) {
```suggestion
  for (size_t i = 0; i + 2 < buffer.size(); i++) {
```

Maybe I'm missing something but why not just a simple for loop here?

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/sml_parser.cpp
> +  while (len--) {
same here

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/sml_parser.cpp
> +  uint16_t crc_received = (buffer.at(buffer.size() - 2) << 8) | buffer.at(buffer.size() - 1);
possible underflow (ok `at` would catch that, but it would result in a panic and not be good)

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/sml_parser.cpp
> +      obis_info.emplace_back(ObisInfo(server_id, val_list_entry));
```suggestion
      obis_info.emplace_back(server_id, val_list_entry);
```

(`emplace_back` calls the type's constructor, so the `ObisInfo` here is superfluous and would result in an additional move)

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/sml_parser.cpp
> +  while (pos < this->buffer_.size() - 8) {
```suggestion
  for (size_t pos = 8; pos + 8 < this->buffer_.size(); pos++) {
```

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/text_sensor/__init__.py
> +SmlSensor = sml_ns.class_("SmlTextSensor", text_sensor.TextSensor, cg.Component)
```suggestion
SmlTextSensor = sml_ns.class_("SmlTextSensor", text_sensor.TextSensor, cg.Component)
```

typo

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/text_sensor/__init__.py
> +        cv.Optional(CONF_FORMAT, default=""): cv.string,
Is this used like an enum? From `sml_text_sensor.cpp` it looks like it's used that way. Then we should validate here the list of valid options (see `cv.enum` usages) and use an enum in Cpp also to store the format.

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/text_sensor/sml_text_sensor.cpp
> +      publish_state(std::string(obis_info.value.begin(), obis_info.value.end()));
```suggestion
      publish_state(std::string(obis_info.value.begin(), obis_info.value.end()));
```

`text_sensor` can effectively only represent UTF-8 data (MQTT, native API clients both transport it that way and would throw errors if non-UTF8 is received)

Does OBIS specify that the incoming data must be UTF-8/ASCII?

2021-10-02 13:53 UTC, OttoWinter commented on esphome/components/sml/sml_parser.cpp
> +    pos += 1;
A constructor _really_ shouldn't modify it's passed in value.

Can we change this to a static method maybe that either
1. takes a pointer (so it's visible from the calling code that it may be modified)
2. returns the number of bytes consumed (calling code will have to add it itself)

2021-10-04 18:42 UTC, alengwenus commented on esphome/components/sml/__init__.py
> +CONF_OBIS = "obis"
Changed it.

2021-10-04 18:42 UTC, alengwenus commented on esphome/components/sml/sml.cpp
> +    this->incoming_buffer_[k - 1] = this->incoming_buffer_[k];
Done

2021-10-04 18:43 UTC, alengwenus commented on esphome/components/sml/sml_parser.h
> +  const unsigned int startpos_;
Done

2021-10-04 18:48 UTC, alengwenus commented on esphome/components/sml/sml_parser.cpp
> +  unsigned int idx = 0;
I added a check for the buffer size (which contains the CRC in the last two bytes) in `check_sml_data`. A pointer to the buffer data is then passed to the functions which calculate the CRC. This way we avoid unneccessary buffer copy and an undeflow shouldn't occur.

2021-10-04 18:49 UTC, alengwenus commented on esphome/components/sml/sml_parser.cpp
> +  while (len--) {
Replaced with a for loop.

2021-10-04 18:49 UTC, alengwenus commented on esphome/components/sml/sml_parser.cpp
> +  uint16_t crc_received = (buffer.at(buffer.size() - 2) << 8) | buffer.at(buffer.size() - 1);
see above

2021-10-04 18:54 UTC, alengwenus commented on esphome/components/sml/sml_parser.cpp
> +  while (pos < this->buffer_.size() - 8) {
I would prefer to keep the while loop. I usually use a for loop if the number of cycles is known (or can be determined) at the beginning of the loop. That's not the case here as it turns out while parsing the SML data.
Anyway, incrementing the `pos` parameter here gives a different result and is not needed.

2021-10-04 18:55 UTC, alengwenus commented on esphome/components/sml/text_sensor/sml_text_sensor.cpp
> +      publish_state(std::string(obis_info.value.begin(), obis_info.value.end()));
The protocol specifications do not say anything about encodings. The only "datatype" given is a byte sequence (which they call an "octet string").
What data is tranported and how it should be interpreted differs from manufacturer and from device to device.
Unfortunatley it's up to the user to find the right interpretation.

2021-10-04 18:56 UTC, alengwenus commented on esphome/components/sml/sml_parser.cpp
> +    pos += 1;
Changed this to a static factory method which returns `SmlNode` objects. Also passed `pos` as a pointer.

2021-10-04 19:03 UTC, alengwenus commented on esphome/components/sml/text_sensor/__init__.py
> +        cv.Optional(CONF_FORMAT, default=""): cv.string,
Changed to cv.enum. I tried to follow the other usages. Hope it's used the right way because I wasn't able to follow the whole magic.

2021-10-04 19:25 UTC, OttoWinter commented on esphome/components/sml/text_sensor/sml_text_sensor.cpp
> +      publish_state(std::string(obis_info.value.begin(), obis_info.value.end()));
:+1: 

If there _is_ non-UTF-8 data sent by the device, the user can still select `HEX` output mode and it will just print the hex encoding of the byte sequence, right? (just so we have a fallback if someone does hit that as an error)

2021-10-04 19:26 UTC, OttoWinter commented on esphome/components/sml/sml_parser.cpp
> +  while (pos < this->buffer_.size() - 8) {
Works for me, as long as an underflow isn't possible :)

2021-10-04 19:29 UTC, alengwenus commented on esphome/components/sml/text_sensor/sml_text_sensor.cpp
> +      publish_state(std::string(obis_info.value.begin(), obis_info.value.end()));
Yes, that's the way it works. If necessary, the user can do whatever he wants with the hex representation using templates on the HomeAssistant side.

2021-10-04 19:30 UTC, OttoWinter commented on esphome/components/sml/text_sensor/__init__.py
> +        cv.Optional(CONF_FORMAT, default=""): cv.string,
Looks good to me :+1:

2021-10-05 17:12 UTC, alengwenus commented on esphome/components/sml/sml_parser.cpp
> +  while (pos < this->buffer_.size() - 8) {
Admittedly there is a small risk of a segmentation fault if the smart meter sends data in a structure which does not comply with the SML standard (but still with a correct checksum).
However, I revised the code and added a check if the parser exceeds the buffer limits due to such a case.

2021-10-12 11:51 UTC, N-Schaef commented
Hey, I know this may be a fringe usecase, but would it be possible to configure two SML platforms?

I have two energy meters right next to each other and would like to only use one device.
I can configure two UART buses, but only one SML platform.

2021-10-12 18:46 UTC, alengwenus commented
> I can configure two UART buses, but only one SML platform.

@N-Schaef Added the missing MULTI_CONF constant. Should work now by defining multiple SML platforms as list.

2021-11-03 06:30 UTC, alengwenus commented
> Overall I would also prefer if `using namespace std;` was not used as it makes the code harder to understand where those things are defined, and makes it harder for people to use this code as a reference.
> 
> 
> 
> Also would be more consistent if `uint8_t` was used instead of `unsigned char`

@jesserockz I already implemented all your review comments. I just wanted to kindly ask if there is anything left I have to do from your perspective so your requested changes get approved?

2021-11-30 13:19 UTC, Syntoxr commented
I'm also quite interested in what is missing in order to get this approved.
Thanks

2021-12-02 22:52 UTC, jesserockz requested changes

2021-12-02 22:52 UTC, jesserockz commented on esphome/components/sml/__init__.py
> +        raise vol.Invalid(f"{value} is not a valid OBIS code")
Can remove the import after changing this.
```suggestion
        raise cv.Invalid(f"{value} is not a valid OBIS code")
```

2021-12-02 22:52 UTC, jesserockz commented on esphome/components/sml/sensor/__init__.py
> +SmlSensor = sml_ns.class_("SmlSensor", sensor.Sensor, cg.Component)
This gives a better config error if they miss the main component.
```suggestion
from .. import CONF_OBIS_CODE, CONF_SERVER_ID, CONF_SML_ID, Sml, obis_code, sml_ns

DEPENDENCIES = ["sml"]

SmlSensor = sml_ns.class_("SmlSensor", sensor.Sensor, cg.Component)
```

But also since the component has no real config, you could auto load it instead:

```suggestion
from .. import CONF_OBIS_CODE, CONF_SERVER_ID, CONF_SML_ID, Sml, obis_code, sml_ns

AUTO_LOAD = ["sml"]

SmlSensor = sml_ns.class_("SmlSensor", sensor.Sensor, cg.Component)
```

2021-12-02 22:52 UTC, jesserockz commented on esphome/components/sml/sml_parser.cpp
> +  return std::string(repr);
```suggestion
  return str_sprintf("%d-%d:%d.%d.%d", this->code[0], this->code[1], this->code[2], this->code[3], this->code[4]);
```

2021-12-02 22:52 UTC, jesserockz commented on esphome/components/sml/sml_parser.cpp
> +    repr += buf;
```suggestion
    repr += str_sprintf("%02x", value & 0xff);
```

2021-12-02 22:52 UTC, jesserockz commented on esphome/components/sml/text_sensor/__init__.py
> +
Same here as above for `DEPENDENCIES` or `AUTO_LOAD`

2021-12-02 22:52 UTC, jesserockz commented on esphome/components/sml/sml.cpp
> +  int i = 0;
Not used 
```suggestion
```

2021-12-02 22:52 UTC, jesserockz commented on esphome/components/sml/text_sensor/sml_text_sensor.cpp
> +void SmlTextSensor::dump_config() { LOG_TEXT_SENSOR("  ", "SML", this); }
Perhaps you should dump the `SmlListener` fields here too and for `sensor`?

2021-12-03 14:12 UTC, alengwenus commented on esphome/components/sml/__init__.py
> +        raise vol.Invalid(f"{value} is not a valid OBIS code")
Done

2021-12-03 14:13 UTC, alengwenus commented on esphome/components/sml/sensor/__init__.py
> +SmlSensor = sml_ns.class_("SmlSensor", sensor.Sensor, cg.Component)
Added the AUTO_LOAD

2021-12-03 14:13 UTC, alengwenus commented on esphome/components/sml/text_sensor/sml_text_sensor.cpp
> +void SmlTextSensor::dump_config() { LOG_TEXT_SENSOR("  ", "SML", this); }
Done

2022-01-06 18:44 UTC, unaiur requested changes

2022-01-06 18:44 UTC, unaiur commented on esphome/components/sml/constants.h
> +    0x3de3, 0x2c6a, 0x1ef1, 0x0f78};
There are several implementations of CRC16-X25 / CRC16-Kermit that could share this table, like https://github.com/esphome/esphome/blob/607601b3a4be5f8e5941d59744f438177c015815/esphome/components/pipsolar/pipsolar.cpp.

Has you considered contributing CRC16-X25 functions to the EspHome core?

2022-01-06 18:44 UTC, unaiur commented on esphome/components/sml/sml.cpp
> +  return 0;
This method can be optimized to save memory and CPU.

You are only interested in 4 kinds of characters: 0x1b (escape), 0x01 (start) & 0x1a (stop) and anything else.
Instead of storing 8 bytes in an array, you can store 8 pair of bits in an uint16_t.

First, you need to convert the input bytes to the internal codes:
```
    constexpr uint8_t ESCAPE_BYTE = 0x1B;
    constexpr uint8_t START_BYTE = 0x01;
    constexpr uint8_t END_BYTE = 0x1A;
    
    constexpr int get_code(uint8_t byte)
    {
        switch (byte)
        {
        case ESCAPE_BYTE:
            return 1;
        case START_BYTE:
            return 2;
        case END_BYTE:
            return 3;
        default:
            return 0;
        }
    }
```

Then you can write a function that updates the boundary or mark detector state:
```
    constexpr uint16_t update_mark_state(uint16_t state, uint8_t byte)
    {
        return (state << 2) | get_code(byte);
    }
```

Then you can define the mark_states that identifies the start and end marks:
```
    constexpr uint16_t update_mark_state_x4(uint16_t state, uint8_t byte)
    {
        state = update_mark_state(state, byte);
        state = update_mark_state(state, byte);
        state = update_mark_state(state, byte);
        return update_mark_state(state, byte);
    }
    constexpr uint16_t ESCAPE_MARK_STATE = update_mark_state_x4(0, ESCAPE_BYTE);
    constexpr uint16_t START_MARK_STATE = update_mark_state_x4(ESCAPE_MARK_STATE, START_BYTE);
    constexpr uint16_t END_MARK_STATE = update_mark_state(ESCAPE_MARK_STATE, END_BYTE);
```

Note: Since all methods are constexpr, it is executed at compile type.

Finally, we can have an optimized checkStartEndBytes_ method like:
```
        mark_state = update_mark_state(mark_state, byte);
        if (mark_state == START_MARK_STATE)
        {
            return START_BYTES_DETECTED;
        }
        if ((mark_state >> 6) == END_MARK_STATE)
        {
            return END_BYTES_DETECTED;
        }
        return 0;
```

2022-01-06 18:44 UTC, unaiur commented on esphome/components/sml/sml.cpp
> +        this->sml_data_.assign(START_BYTES, START_BYTES + 8);
Adding the START_BYTES at the beginning of the buffer is causing you a lot of pointer math that can be optimized.
Instead, you can redefine your CRC functions to accept an initial state and pass it instead of adding the START_BYTES at the beginning of the buffer. See my comments in the CRC functions.

2022-01-06 18:44 UTC, unaiur commented on esphome/components/sml/sml_parser.cpp
> +uint16_t calc_crc16_x25(const bytes &buffer) {
It is not good idea to mix protocol logic (substracting - 2 because the CRC is at the end) with the CRC calculation logic.  I would write completely generic functions like these in its own file. Also, since both kermit and x25 share the same polynomial, you can share the main code between both.

```
    /* This function implements the CRC16 algorithm for the 0x1021 polynomial (used by both X25 & Kermit) */
    uint16_t crc16_1021(const_ptr_t begin, const_ptr_t end, uint16_t crcsum)
    {
        while (end - begin > 0)
        {
            crcsum = (crcsum >> 8) ^ CRC16_X25_TABLE[(crcsum & 0xff) ^ *begin++];        }
        }
        return crcsum;
    }
    inline uint16_t crc16_x25(const_ptr_t begin, const_ptr_t end, uint16_t crcsum = 0)
    {
        return crc16_1021(begin, end, crcsum ^ 0xFFFF) ^ 0xFFFF;
    }
    inline uint16_t crc16_kermit(const_ptr_t begin, const_ptr_t end, uint16_t crcsum = 0)
    {
        return crc16_1021(begin, end, crcsum);
    }
```

Finally, these functions allow you calculate the CRC16 of the file without storing the start header in the buffer:
```
   crc16_kermit(buffer.begin(), buffer.end() - 2, 0xED50);
   crc16_x25(buffer.begin(), buffer.end() - 2, 0x6E23);
```

I used https://crccalc.com/?crc=1b1b1b1b01010101&method=crc16&datatype=hex&outtype=hex to calculate the CRC16 of the start header.

2022-01-06 18:44 UTC, unaiur commented on esphome/components/sml/sml.cpp
> +  SmlFile sml_file = SmlFile(sml_data);
If you strip the padding and end headers before calling the SmlFile constructor, the logic in that method will become simpler.

2022-01-06 18:44 UTC, unaiur commented on esphome/components/sml/sml_parser.cpp
> +char check_sml_data(const bytes &buffer) {
I would move this function to the Sml.cpp file, where all other SmlFile extraction happens.

2022-01-06 18:44 UTC, unaiur commented on esphome/components/sml/sml_parser.cpp
> +      this->nodes.emplace_back(SmlNode(this->buffer_, pos));
You are building a tree with all the SML message, but only using a super small set of fields (obis code and value).
This approach is simple, but consumes a lot of memory that is scarce in the ESP8266 chip. I would try to avoid all the memory overhead using procedural parsing of the message.

But it can be implemented in a later CR. For this CR I think that is not needed.

2022-01-07 15:51 UTC, fitim7 commented
Is it possible to use this also with devices which need to be triggered? Tasmota has this implemented too, and i would love to see that also in ESPHome.
In Tasmota you have this optional variables:
![image](https://user-images.githubusercontent.com/49379347/148569428-f4b46624-5f9b-4453-9b86-78b34a5b7324.png)

2022-01-20 16:09 UTC, tunip commented
@jesserockz Are there any outstanding tasks related to this PR? As a user I still run the SML custom_component from @alengwenus since months without any stability issues. Would be great to extend the HA energy management official with more power meters in the field👍 .

2022-01-30 05:33 UTC, alengwenus commented on esphome/components/sml/constants.h
> +    0x3de3, 0x2c6a, 0x1ef1, 0x0f78};
I guess that should be addressed in a separate PR as it is not directly related to the SML component.

2022-01-30 05:37 UTC, alengwenus commented on esphome/components/sml/sml.cpp
> +        this->sml_data_.assign(START_BYTES, START_BYTES + 8);
Looks like you're commenting an outdated PR. This has already been changed due to a former review.

2022-01-30 05:37 UTC, alengwenus commented on esphome/components/sml/sml_parser.cpp
> +uint16_t calc_crc16_x25(const bytes &buffer) {
Looks like you're commenting an outdated PR. This has already been changed due to a former review.

2022-01-30 05:40 UTC, alengwenus commented on esphome/components/sml/sml.cpp
> +  SmlFile sml_file = SmlFile(sml_data);
Stripping the headers/footers will result in additional copies of `sml_data`. So, I decided against that. The logic isn't much heavier. In addition the headers/footers are part of the SML data. Therefore, for me it makes perfectly sense to pass them to the parser, too.

2022-01-30 05:43 UTC, alengwenus commented on esphome/components/sml/sml_parser.cpp
> +char check_sml_data(const bytes &buffer) {
`sml_parser.cpp` is meant to deal with the sml data on bytes level. `sml_file.cpp` deals with the parser on a higher level. I would leave it as it is.

2022-01-30 05:48 UTC, alengwenus commented on esphome/components/sml/sml_parser.cpp
> +      this->nodes.emplace_back(SmlNode(this->buffer_, pos));
Agreed. At least the current solution only needs memory for the object tree. The buffer data is always passed by reference.

2022-01-31 09:01 UTC, unaiur commented on esphome/components/sml/sml_parser.cpp
> +char check_sml_data(const bytes &buffer) {
You should respect the layers defined in the specification of a protocol. This CRC is defined in the section "8.1 SML-Transport-Protokoll V1", page 67 of the SML 1.04 specification, together with the header and the footer and it is not part of the SML file format.

Handling it here violates encapsulation principle and creates issues like the possible overflow reported by OttoWinter. Handling it in the transport layer, it is easier to reason about the code and understand it is impossible for it to happen.

2022-01-31 09:01 UTC, unaiur commented on esphome/components/sml/constants.h
> +    0x3de3, 0x2c6a, 0x1ef1, 0x0f78};
I agree.

2022-01-31 09:01 UTC, unaiur commented on esphome/components/sml/sml.cpp
> +        this->sml_data_.assign(START_BYTES, START_BYTES + 8);
The code might have changed, but you are still passing all the bytes received by transport layer. Code is easier to maintain when the protocol layers are correctly encapsulated.

2022-01-31 09:01 UTC, unaiur commented on esphome/components/sml/sml_parser.cpp
> +uint16_t calc_crc16_x25(const bytes &buffer) {
Most of the comments still apply. Both CRC methods can share most of the code and it is useful to expose the initial value to allow incremental CRC calculations.

2022-01-31 09:01 UTC, unaiur commented on esphome/components/sml/sml.cpp
> +  SmlFile sml_file = SmlFile(sml_data);
I do not understand why. You should avoid writing the header to the buffer and remove the footer (which can be done without any copy).

The idea is to separate the transport protocol from the file format instead of intermixing them.

Encapsulation is one of the key principles for maintainable code.

2022-02-06 14:47 UTC, alengwenus commented on esphome/components/sml/sml.cpp
> +  return 0;
Thanks for the idea! I didn't use the `constexpr` but calculated the start and end masks and defined them as constants.
I think it is more understandable.

2022-02-06 14:48 UTC, alengwenus commented on esphome/components/sml/sml.cpp
> +        this->sml_data_.assign(START_BYTES, START_BYTES + 8);
I removed the start bytes from the buffer and fixed the parsing accordingly.

2022-02-06 14:48 UTC, alengwenus commented on esphome/components/sml/sml_parser.cpp
> +uint16_t calc_crc16_x25(const bytes &buffer) {
Done.

2022-05-10 07:52 UTC, hanzoh commented
Except that one failed test where the logs for it are gone, is there anything pending to merge this?
It is working fine for me for several months and it is a great contribution to energy management in HA.

2022-05-10 09:05 UTC, jesserockz approved these changes

2022-05-10 09:05 UTC, merged

2022-05-10 09:11 UTC, Bouni commented
🤩 Finally!
Thanks everybody involved in this PR for making it into ESPHome 🥳