Add cd74 hc4067 multiplexer
OttoWinter/esphomeyaml pull request #2431
Opened 2021-10-03 13:25 UTC by asoehlke

# What does this implement/fix? 

Addition of component/sensor for CD74HC4067 analog multiplexer

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/feature-requests#85

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
cd74hc4067:
  pin_s0: D0
  pin_s1: D1
  pin_s2: D2
  pin_s3: D3     

sensor:
  - platform: adc
    id: adc_sensor
    pin: A0
    update_interval: 3600s
  - platform: cd74hc4067
    id: solar_1_raw
    number: 0
    sensor: adc_sensor
    update_interval: 3600s
  - platform: cd74hc4067
    id: solar_2_raw
    number: 1
    sensor: adc_sensor
    update_interval: 3600s
  - platform: ct_clamp
    name: "SolarPower1"
    sensor: solar_1_raw
    update_interval: 5s
    unit_of_measurement: "A"
    filters:
        - multiply: 36000
  - platform: ct_clamp
    name: "SolarPower2"
    sensor: solar_2_raw
    update_interval: 5s
    unit_of_measurement: "A"
    filters:
        - multiply: 36000
      
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-10-03 19:56 UTC, OttoWinter commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +#include <Arduino.h>
This include won't work on esp-idf based builds; I don't see it used anywhere, so let's remove it

2021-10-03 19:57 UTC, OttoWinter commented on esphome/components/cd74hc4067/sensor.py
> +CONF_cd74hc4067_ID = "cd74hc4067_id"
```suggestion
CONF_CD74HC4067_ID = "cd74hc4067_id"
```

Those CONF_ names are always uppercase in esphome

2021-10-03 20:21 UTC, asoehlke commented on esphome/components/cd74hc4067/sensor.py
> +CONF_cd74hc4067_ID = "cd74hc4067_id"
changed

2021-10-03 20:23 UTC, asoehlke commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +#include <Arduino.h>
Thanks for the utra fast review, the import is removed. 
Was a remainder of accessing the pin directly.

2021-10-14 20:19 UTC, asoehlke commented
Sorry, false alert for code owner @jeromelaban, @ncareau, @Syndlex, @OttoWinter, @trvrnrth, @esphome/core, the bot was faster than me cleaning up some mess in this branch. Your components are not changed!

2021-11-04 08:17 UTC, ekorsanov01 commented
When will this component be added to the master?

2021-11-04 21:34 UTC, asoehlke commented
> When will this component be added to the master?

For me: anytime :-)
A second review from @jesserockz is still pending and then I hope one of the maintainers can merge it.
If you like you can also clone from my fork (https://github.com/asoehlke/esphome) and try it out.

2021-12-13 15:28 UTC, csk06 commented
@asoehlke 

Hi Andreas, 

I need to use this unit in my project, so for that it seemed to change the esphome_version to your repo. But it seems like esphome has removed that esphome_version from configuration page. 

Can you please tell me what i need to do in order to "integrate" your codes to my setup. 

Thanks

2021-12-13 19:04 UTC, jesserockz commented
@csk06 Until this is merged you can get it in by using this then the documented method for the component:

```yaml
external_components:
  - source: github://pr#2431
    components: ["cd74hc4067"]
```

2022-01-10 11:04 UTC, jesserockz requested changes

2022-01-10 11:04 UTC, jesserockz commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +void CD74HC4067Sensor::setup() { LOG_SENSOR("", "Setting up CD74HC4067 Multiplexer Channel", this); }
No need for a whole setup function that just sends a log message...

2022-01-10 11:04 UTC, jesserockz commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +}
Can remove all references to `name` as it is set by the internal EntityBase code

2022-01-10 11:04 UTC, jesserockz commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +float CD74HC4067Sensor::get_setup_priority() const { return parent_->get_setup_priority() - 1.0f; }
Consistency with use of `this->` please
```suggestion
float CD74HC4067Sensor::get_setup_priority() const { this->return parent_->get_setup_priority() - 1.0f; }
```

2022-01-10 11:04 UTC, jesserockz commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +  return source_->sample();
```suggestion
  this->parent_->activate_pin(this->pin_);
  return this->source_->sample();
```

2022-01-10 11:04 UTC, jesserockz commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +std::string CD74HC4067Sensor::unique_id() { return get_mac_address() + "-" + to_string(pin_); }
This should at least match the format of the default unique id please, but really shouldn't need overriding at all to keep the code cleaner.

```
std::string get_default_unique_id(const std::string &component_type, EntityBase *entity) {
  return App.get_name() + component_type + entity->get_object_id();
}
```

2022-01-10 11:04 UTC, jesserockz commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +}
```suggestion
void CD74HC4067Sensor::dump_config() {
  LOG_SENSOR(TAG, "CD74HC4067 Sensor", this);
  ESP_LOGCONFIG(TAG, "  Pin: %u", this->pin_);
  LOG_UPDATE_INTERVAL(this);
}
```

2022-01-10 11:04 UTC, jesserockz commented on esphome/components/cd74hc4067/cd74hc4067.h
> +  CD74HC4067Sensor(CD74HC4067Component *parent, const std::string &name, uint8_t pin);
Please remove the name and pin from the constructor and use the `set_pin` setter function below from `to_code` too.

Could also remove the constructor definition altogether and extend `public Parented<CD74HC4067Component>` too and use `await cg.register_parented(var, config[CONF_CD74HC4067_ID])`

```suggestion
  CD74HC4067Sensor(CD74HC4067Component *parent);
```

2022-01-10 11:04 UTC, jesserockz commented on esphome/components/cd74hc4067/sensor.py
> +    )
As per above
```suggestion
    var = cg.new_Pvariable(config[CONF_ID], parent)
```

2022-01-10 11:04 UTC, jesserockz commented on esphome/components/cd74hc4067/sensor.py
> +        device_class=DEVICE_CLASS_POWER,
Shouldn't this be a `UNIT_VOLT` and `DEVICE_CLASS_VOLTAGE` by default?

2022-01-10 11:04 UTC, jesserockz commented on esphome/components/cd74hc4067/sensor.py
> +    sens = await cg.get_variable(config[CONF_SENSOR])
```suggestion
    cg.add(var.set_pin(config[CONF_NUMBER]))

    sens = await cg.get_variable(config[CONF_SENSOR])
```

2022-01-10 11:04 UTC, jesserockz commented on tests/test3.yaml
> +  pin_s3: D3
Not sure about the rest of the file, but please use GPIOx pins not Dx pins as they are board specific.

2022-01-10 21:15 UTC, asoehlke commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +void CD74HC4067Sensor::setup() { LOG_SENSOR("", "Setting up CD74HC4067 Multiplexer Channel", this); }
Removed

2022-01-10 21:16 UTC, asoehlke commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +}
Name handling removed

2022-01-10 21:19 UTC, asoehlke commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +float CD74HC4067Sensor::get_setup_priority() const { return parent_->get_setup_priority() - 1.0f; }
corrected, I hope I got all places.

2022-01-10 21:19 UTC, asoehlke commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +  return source_->sample();
corrected

2022-01-10 21:23 UTC, asoehlke commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +std::string CD74HC4067Sensor::unique_id() { return get_mac_address() + "-" + to_string(pin_); }
removed, should really not be necessary with the name set correctly.

2022-01-10 21:38 UTC, asoehlke commented on esphome/components/cd74hc4067/sensor.py
> +        device_class=DEVICE_CLASS_POWER,
Yes, these are better defaults, changed.

2022-01-10 21:39 UTC, asoehlke commented on esphome/components/cd74hc4067/cd74hc4067.h
> +  CD74HC4067Sensor(CD74HC4067Component *parent, const std::string &name, uint8_t pin);
changed

2022-01-10 21:42 UTC, asoehlke commented on esphome/components/cd74hc4067/sensor.py
> +    sens = await cg.get_variable(config[CONF_SENSOR])
changed

2022-01-10 22:20 UTC, asoehlke commented on tests/test3.yaml
> +  pin_s3: D3
changed

2022-01-10 22:37 UTC, asoehlke commented
Updated the device with the changed version, looks good, but I would like to wait for the sun to rise here (Berlin time) to check whether the values are as expected.

2022-01-11 02:40 UTC, jesserockz requested changes

2022-01-11 02:40 UTC, jesserockz commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +CD74HC4067Sensor::CD74HC4067Sensor(CD74HC4067Component *parent) : PollingComponent(1000), parent_(parent) {}
I missed this before
```suggestion
CD74HC4067Sensor::CD74HC4067Sensor(CD74HC4067Component *parent) : parent_(parent) {}
```

2022-01-11 02:40 UTC, jesserockz commented on esphome/components/cd74hc4067/cd74hc4067.cpp
> +  this->parent_->activate_pin(pin_);
```suggestion
  this->parent_->activate_pin(this->pin_);
```

2022-01-11 03:48 UTC, jesserockz approved these changes

2022-01-11 03:59 UTC, merged