Add pressure compensation during runtime
OttoWinter/esphomeyaml pull request #2493
Opened 2021-10-12 09:32 UTC by martgras

Allow pressure and altitude compensation during runtime

# What does this implement/fix? 

**Add required delay after stop_periodic_measurement**
According to the [datasheet](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/9.5_CO2/Sensirion_CO2_Sensors_SCD4x_Datasheet.pdf) a 500 ms delay is required after a stop_periodic_measurement command.
Without this delay initialization may fail with 
```
[11:13:39][D][scd4x:044]: Sensor has data available, stopping periodic measurement
[11:13:39][E][scd4x:056]: Failed to write get serial command
[11:13:39][E][component:103]: Component scd4x.sensor was marked as failed.
```

**Add pressure compensation during runtime**
To increase the measurement accuracy ambient pressure compensation can used. 
With this change ambient pressure compensation can be used from a lambda instead of a fixed value during setup. 
Main use case is using a pressure sensor to provide up to date pressure information to scd4x

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1526

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: scd4x
    id: scd41
    i2c_id: bus_a
    co2:
      name: co2
      id: co2

  - platform: bme280
    pressure:
      name: "BME280-Pressure"
      id: bme280_pressure
      oversampling: 1x
      on_value:
        then:
          - lambda: "id(scd41)->set_ambient_pressure_compensation(x / 1000.0);"

```
Or set another sensor as the source for the pressure data 
```yaml
   sensor:
  - platform: scd4x
    setup_priority: -10
    id: scd41
    i2c_id: bus_a
    altitude_compensation: 418m
    co2:
      name: co2
      id: co2
    ambient_pressure_compensation_source: bme280_pressure
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-10-12 09:52 UTC, sjtrny commented
> With this change ambient pressure/altitude compensation can be used from a lambda instead of a fixed value during setup.

Perhaps instead it should follow the established convention that other sensors use for continuous compensation? For example the [SGP30](https://esphome.io/components/sensor/sgp30.html) just needs the sensor ID.

2021-10-12 10:20 UTC, davet2001 requested changes
A few small comments.  Thanks for the PR👍

2021-10-12 10:20 UTC, davet2001 commented on esphome/components/scd4x/scd4x.cpp
> +      esphome::delay(500);  // NOLINT
This seems ok as long as no other activites are running in this task, or the calling function doesn't mind waiting this long.  But if there are this might block them or delay unnecessarily.

Could it be done with a timestamp and then vTaskDelayUntil()?

2021-10-12 10:20 UTC, davet2001 commented on esphome/components/scd4x/scd4x.cpp
> +    ESP_LOGE("main lambda", "Error setting altitude compensation.");
I assume the first param should be TAG here (below also).

2021-10-12 10:20 UTC, davet2001 commented on esphome/components/scd4x/scd4x.cpp
> +    ESP_LOGE("main lambda", "Error setting ambient pressure compensation.");
See above

2021-10-12 10:20 UTC, davet2001 commented on esphome/components/scd4x/scd4x.h
> +    // setting an ambient pressure overrides altitude compensation
Might be helpful to generate a log message if the command is being ignored for a reason.

2021-10-12 10:26 UTC, martgras commented on esphome/components/scd4x/scd4x.cpp
> +      esphome::delay(500);  // NOLINT
Not sure - I don't like the delay here either 
@jesserockz ,@OttoWinter , @oxan  any suggestions on this?

2021-10-12 10:28 UTC, martgras commented on esphome/components/scd4x/scd4x.cpp
> +    ESP_LOGE("main lambda", "Error setting altitude compensation.");
thx

2021-10-12 10:28 UTC, martgras commented on esphome/components/scd4x/scd4x.cpp
> +    ESP_LOGE("main lambda", "Error setting ambient pressure compensation.");
fixed

2021-10-12 10:30 UTC, OttoWinter commented on esphome/components/scd4x/scd4x.cpp
> +      esphome::delay(500);  // NOLINT
you can use `set_timeout` which is a non-blocking delay

(also, please don't tag many maintainers unless they were already involved in the PR; we'll review the PR eventually when going through the open PRs)

2021-10-12 11:29 UTC, martgras commented on esphome/components/scd4x/scd4x.h
> +    // setting an ambient pressure overrides altitude compensation
done

2021-10-12 11:29 UTC, martgras commented on esphome/components/scd4x/scd4x.cpp
> +      esphome::delay(500);  // NOLINT
Thanks Otto and sorry - should have used discord :) 
@sjtrny  good idea 
@davet2001  implemented the suggested changes

2021-10-12 12:58 UTC, davet2001 approved these changes
LGTM

2021-10-12 15:38 UTC, oxan requested changes

2021-10-12 15:38 UTC, oxan commented on esphome/components/scd4x/scd4x.cpp
> +    float pressure = this->pressure_sensor_->state / 1000.0;
We use single-precision floats in ESPHome:
```suggestion
    float pressure = this->pressure_sensor_->state / 1000.0f;
```

2021-10-12 15:38 UTC, oxan commented on esphome/components/scd4x/scd4x.cpp
> +      set_ambient_pressure_compensation(this->pressure_sensor_->state / 1000.0);
```suggestion
      set_ambient_pressure_compensation(this->pressure_sensor_->state / 1000.0f);
```

2021-10-12 15:38 UTC, oxan commented on esphome/components/scd4x/scd4x.cpp
> +    if (this->altidute_sensor_ != nullptr) {
altidute -> altitude (everywhere).

2021-10-12 15:38 UTC, oxan commented on esphome/components/scd4x/scd4x.cpp
> +        set_ambient_pressure_compensation(this->altidute_sensor_->state);
```suggestion
        set_altitude_compensation(this->altidute_sensor_->state);
```
(did you test this?)

2021-10-12 15:38 UTC, oxan commented on esphome/components/scd4x/sensor.py
> +            ),
There is already an altitude compensation option above. We should move them to be under compensation as well.

2021-10-12 15:44 UTC, martgras commented on esphome/components/scd4x/scd4x.cpp
> +    if (this->altidute_sensor_ != nullptr) {
oh man - I thought I corrected that already :)

2021-10-12 15:45 UTC, martgras commented on esphome/components/scd4x/sensor.py
> +            ),
OK makes sense - but this would be a breaking change for anyone using the component already

2021-10-12 17:02 UTC, martgras commented on esphome/components/scd4x/scd4x.cpp
> +    if (this->altidute_sensor_ != nullptr) {
removed that part

2021-10-12 17:04 UTC, martgras commented on esphome/components/scd4x/sensor.py
> +            ),
Just noticed that altitude compensation during runtime is not recommended by sensirion and only possible when the sensor is idle. Therefore I removed it  and  use `ambient_pressure_compensation_source`  for the pressure sensor attribute

2021-10-13 15:53 UTC, oxan requested changes

2021-10-13 15:53 UTC, oxan commented on esphome/components/scd4x/scd4x.cpp
> +void SCD4XComponent::set_ambient_pressure_compensation(float pressure) {
Could we add a comment with the unit for the parameter? I had to read through the code twice to be sure it was correct.

2021-10-13 15:53 UTC, oxan commented on esphome/components/scd4x/scd4x.cpp
> +  // remove millbar from comparison to avoid frequent updates +/- 10 millbar doesn't matter
```suggestion
  // remove millibar from comparison to avoid frequent updates, +/- 10 millibar doesn't matter
```

2021-10-13 15:53 UTC, oxan commented on esphome/components/scd4x/scd4x.cpp
> +        if (!this->write_command_(SCD4X_CMD_AMBIENT_PRESSURE_COMPENSATION, ambient_pressure_compensation_)) {
Shouldn't this write `ambient_pressure_` instead? Even better is to just call `update_ambient_pressure_compensation_` instead.

2021-10-13 15:53 UTC, oxan commented on esphome/components/scd4x/scd4x.h
> +  void set_pressure_sensor(sensor::Sensor *pressure) { pressure_sensor_ = pressure; }
I would prefer to put this method next to `set_ambient_pressure_compensation` and to call it `set_ambient_pressure_source`, and to rename the `pressure_sensor_` field to `ambient_pressure_source_`. Makes it a bit more clear that this isn't an output sensor provided by the SCD4X component, but a sensor it uses as input.

2021-10-13 17:29 UTC, martgras commented on esphome/components/scd4x/scd4x.cpp
> +        if (!this->write_command_(SCD4X_CMD_AMBIENT_PRESSURE_COMPENSATION, ambient_pressure_compensation_)) {
true - tried not to touch existing code :)

2021-10-13 17:31 UTC, oxan commented on esphome/components/scd4x/scd4x.cpp
> +        if (!this->write_command_(SCD4X_CMD_AMBIENT_PRESSURE_COMPENSATION, ambient_pressure_compensation_)) {
yeah, I think this is a pre-existing bug, but would be nice to fix it while we're at it :)

2021-10-13 17:38 UTC, martgras commented on esphome/components/scd4x/scd4x.h
> +  void set_pressure_sensor(sensor::Sensor *pressure) { pressure_sensor_ = pressure; }
done

2021-10-13 17:53 UTC, oxan approved these changes
Thanks!

2021-10-14 09:24 UTC, merged