siml800l fixes and new functionality
OttoWinter/esphomeyaml pull request #2500
Opened 2021-10-12 19:15 UTC by dz0ny

# What does this implement/fix? 

- RSSI exposed as sensor
- On Network connected automation
- Delete all SMSes trigger
- Multiline SMS support
- Fix for response header parsing bug, where the last SMS would never be processed due to state machine removing SMS header

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

**Related issue or feature (if applicable): /

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable): once set is agreed upon

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
sim800l:
  rssi:
    name: "GSM Signal"
    id: gsm_rssi
  on_registration:
    - logger.log:
        format: "Registered to the network"
switch:
  - platform: template
    name: "Delete all messages"
    lambda: |-
      return false;
    turn_on_action:
      - logger.log: "Deleting all messages"
      - sim800l.delete_sms:
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-10-12 21:21 UTC, jesserockz requested changes

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/__init__.py
> +CONF_ON_CONNECTED= "on_registration"
```suggestion
CONF_ON_CONNECTED = "on_registration"
```

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/__init__.py
> +CONF_RSSI= "rssi"
```suggestion
CONF_RSSI = "rssi"
```

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/__init__.py
>  DEPENDENCIES = ["uart"]
This is required otherwise the sensor cpp code will not be added to the firmware.
```suggestion
AUTO_LOAD = ["sensor"]
DEPENDENCIES = ["uart"]
```

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/sim800l.h
> +  void set_rssi_(sensor::Sensor *rssi_);
Public methods do not end with `_`
A bit more descriptive name. (It is not setting the rssi)

```suggestion
  void set_rssi_sensor(sensor::Sensor *rssi);
```

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/sim800l.h
> +  CallbackManager<void()> callback_reg;
Protected variables need to end with `_`

```suggestion
  CallbackManager<void()> callback_reg_;
```

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/sim800l.cpp
> +        this->message_.append(message.c_str());
```suggestion
        this->message_ += message;
```

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/sim800l.cpp
> +        this->message_.append("\n");
```suggestion
        this->message_ += "\n";
```

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/sim800l.cpp
> +void Sim800LComponent::set_rssi_(sensor::Sensor *rssi) { rssi_ = rssi; }
```suggestion
void Sim800LComponent::set_rssi_sensor(sensor::Sensor *rssi) { this->rssi_ = rssi; }
```

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/sim800l.cpp
> +          this->callback_reg.call();
```suggestion
          this->callback_reg_.call();
```

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/sim800l.h
> +  void add_on_connected_callback(std::function<void()> callback) { this->callback_reg.add(std::move(callback)); }
```suggestion
  void add_on_connected_callback(std::function<void()> callback) { this->callback_reg_.add(std::move(callback)); }
```

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/__init__.py
> +        cg.add(var.set_rssi_(sens))
```suggestion
        cg.add(var.set_rssi_sensor(sens))
```

2021-10-12 21:21 UTC, jesserockz commented on esphome/components/sim800l/sim800l.cpp
> +  ESP_LOGCONFIG(TAG, "  RSSI: %f dB", this->rssi_->get_state());
This needs a nullptr check, or preferably, store the rssi locally in the class to print out regardless of whether the user has the sensor.

2021-10-13 07:53 UTC, dz0ny commented on esphome/components/sim800l/sim800l.cpp
> +        this->message_.append(message.c_str());
Isn't it better to use functions and leave optimization to the compiler? Or is this a specific case? Just trying to understand :)

2021-10-13 12:54 UTC, oxan commented on esphome/components/sim800l/sim800l.cpp
> +        this->message_.append(message.c_str());
for performance it doesn't matter whether you use `append()` or `+=` (though the second one is more readable, imo), but the problem here is the unnecessary call to `c_str()`. You can append `std::string`s to `std::string`s without the need to go through C strings.

2021-10-15 02:29 UTC, jesserockz commented on esphome/components/sim800l/sim800l.cpp
> +        this->message_.append(message.c_str());
Yeah sorry for making 2 change suggestions at once here with no explanation...haha

2022-01-22 01:30 UTC, closed without merging