OTA firmware MD5 check + password support for esp-idf
OttoWinter/esphomeyaml pull request #2507
Opened 2021-10-13 13:00 UTC by mmakaay

# What does this implement/fix? 

This PR adds OTA password support and MD5 checksum validation for uploaded firmware for the esp-idf framework. 

## TODO

- [x] Implement OTA password support
- [x] Implement MD5 checksum validation for uploaded firmware

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
ota:
  password: this-now-works-for-all-three-targets
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-10-14 09:06 UTC, oxan requested changes

2021-10-14 09:06 UTC, oxan commented on esphome/components/ota/__init__.py
> +        cv.Optional(CONF_PASSWORD): cv.All(cv.string),
```suggestion
        cv.Optional(CONF_PASSWORD): cv.string,
```

2021-10-14 09:06 UTC, oxan commented on esphome/components/ota/ota_backend_esp_idf.cpp
> +  if (!this->md5_.equals_hex((char *) this->expected_bin_md5_)) {
This cast seemingly unnecessarily drops constness.

2021-10-14 09:06 UTC, oxan commented on esphome/components/ota/ota_component.cpp
> -#ifdef USE_OTA_PASSWORD
Unrelated to this PR, but can we add this define to `defines.h`?

2021-10-14 09:06 UTC, oxan commented on esphome/core/md5.cpp
> +}
There is `parse_hex` in `helpers.h` that does this already.

2021-10-14 09:06 UTC, oxan commented on esphome/components/ota/ota_backend_esp_idf.h
> +  const char *expected_bin_md5_[32];
Was this intended to be a pointer-to-array (which is pointer-to-pointer)? It doesn't seem to be used as such.
```suggestion
  const char expected_bin_md5_[32];
```

2021-10-14 09:06 UTC, oxan commented on esphome/core/md5.h
> +  void add(uint8_t *data, size_t len);
`data` here can be const.

2021-10-14 09:06 UTC, oxan commented on esphome/core/md5.h
> +  void add(char *data, size_t len) { this->add((uint8_t *) data, len); }
This overload is unnecessary, as the next one is always a candidate as well when this one is.

2021-10-14 09:06 UTC, oxan commented on esphome/core/md5.h
> +  bool equals_hex(const char *expected);
I'm not too fond of these methods writing to C-style string pointers, it's too easy to get it wrong and create a buffer overflow. I can see why it's done to avoid changing too much in the OTA API, which brings me to my next point: is it justified for this to be a global API? I don't see any other MD5 users in the tree, and for new users I'd encourage usage of SHA as that's both more secure and can be hardware-accelerated. 

So personally I would move this to the `ota` component, but let's see what the others think.

2021-10-14 09:16 UTC, OttoWinter commented on esphome/core/md5.h
> +#pragma once
Let's move this file to a new module like `md5` or `hashlib`. We already have a great modularization system in esphome, so let's use it :P

(OTA would then just auto_load that)

2021-10-14 09:34 UTC, mmakaay commented on esphome/components/ota/__init__.py
> +        cv.Optional(CONF_PASSWORD): cv.All(cv.string),
LOL, right :-)

2021-10-14 09:40 UTC, mmakaay commented on esphome/components/ota/ota_component.cpp
> -#ifdef USE_OTA_PASSWORD
I assumed it already was added in there.
I just added the define.

2021-10-14 09:45 UTC, mmakaay commented on esphome/components/ota/ota_backend_esp_idf.h
> +  const char *expected_bin_md5_[32];
Nope, that was just sleep typing ;-) I'll fix that.

2021-10-14 09:46 UTC, mmakaay commented on esphome/core/md5.cpp
> +}
Cool, I'll use that function. 
I'll be back in about 2 hours, then I can continue on this.

2021-10-14 09:47 UTC, mmakaay commented on esphome/core/md5.h
> +#pragma once
In fact, I started with an md5 module that I autoloaded, so I'll move back to that 😄

2021-10-14 11:47 UTC, mmakaay commented on esphome/components/ota/ota_backend_esp_idf.cpp
> +  if (!this->md5_.equals_hex((char *) this->expected_bin_md5_)) {
Yes, a left-over from an earlier iteration. Removed the cast.

2021-10-14 11:47 UTC, mmakaay commented on esphome/core/md5.cpp
> +}
Switched to using `parse_hex(...)`.

2021-10-14 11:55 UTC, mmakaay commented on esphome/components/ota/ota_backend_esp_idf.h
> +  const char *expected_bin_md5_[32];
Fixed.

2021-10-14 11:57 UTC, mmakaay commented on esphome/core/md5.h
> +  void add(char *data, size_t len) { this->add((uint8_t *) data, len); }
Indeed, it's gone now.

2021-10-14 12:00 UTC, mmakaay commented on esphome/core/md5.h
> +  void add(uint8_t *data, size_t len);
It can and it will be. Updated.

2021-10-14 12:03 UTC, mmakaay commented on esphome/core/md5.h
> +  bool equals_hex(const char *expected);
Below there's a remark by @OttoWinter to move md5 to its own component. I will do that.

I agree on the use of C-style pointers. I did stay as close to the original code as possible though, to not possibly introduce issues when this gets into the beta. I would very much applaud eliminating the C-string pointers, but it seems better to do that for 2021.10.1 or so. Agreed?

2021-10-14 12:18 UTC, oxan commented on esphome/components/ota/ota_component.cpp
> -#ifdef USE_OTA_PASSWORD
thanks!

2021-10-14 12:20 UTC, oxan commented on esphome/core/md5.h
> +  bool equals_hex(const char *expected);
yeah, agreed it's good to limit changes, and I don't mind that much if it's put in a separate component. i've slightly higher standards for core code than random components ;)

2021-10-14 15:13 UTC, mmakaay commented on esphome/core/md5.h
> +#pragma once
Done!

2021-10-14 15:25 UTC, mmakaay commented on esphome/core/md5.h
> +  bool equals_hex(const char *expected);
And when handling OTA, that standard might even have to be raised a bit above that ;-)

2021-10-14 19:41 UTC, jesserockz commented on esphome/components/md5/__init__.py
> +CONFIG_SCHEMA = cv.Schema({})
A config schema is not needed
```suggestion
```

2021-10-14 20:38 UTC, mmakaay commented on esphome/components/md5/__init__.py
> +CONFIG_SCHEMA = cv.Schema({})
Ah, because it's not used in the YAML config, but only from `AUTO_LOAD`?
I removed it from the code and it still compiles fine on all three targets, so good riddance! :-)

2021-10-15 02:33 UTC, jesserockz commented on esphome/components/md5/__init__.py
> +CONFIG_SCHEMA = cv.Schema({})
> Ah, because it's not used in the YAML config, but only from `AUTO_LOAD`?

Exactly

2021-10-15 14:54 UTC, oxan approved these changes

2021-10-15 20:06 UTC, OttoWinter approved these changes

2021-10-15 20:06 UTC, merged