Feature/sensor cse7761
OttoWinter/esphomeyaml pull request #2546
Opened 2021-10-18 16:46 UTC by berfenger

# What does this implement/fix? 

Adds CSE7761 power sensor component, a power sensor present on Sonoff Dual R3 v1.x 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1151

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1541

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
uart:
  tx_pin: GPIO25
  rx_pin: GPIO26
  baud_rate: 38400
  parity: EVEN
  stop_bits: 1

sensor:
  platform: cse7761
  voltage:
    name: 'CSE7761 Voltage'
  current_1:
    name: 'CSE7761 Current 1'
  current_2:
    name: 'CSE7761 Current 2'
  active_power_1:
    name: 'CSE7761 Active Power 1'
  active_power_2:
    name: 'CSE7761 Active Power 2'
  update_interval: 5s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-10-21 20:21 UTC, oxan requested changes
Hi, thanks for your contribution! A few comments:

2021-10-21 20:21 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +#define CSE7761_CMD_ENABLE_WRITE 0xE5           // Enable write operation
Why the mix between defines and static constants? I'd like all of them to be static consts.

2021-10-21 20:21 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +uint32_t cse7761ref(uint32_t unit, CSE7761DataStruct *data) {
I think this can be a member function and access `data` through `this`.

2021-10-21 20:21 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +  }
This state machine for initialization in `loop()` seems really weird. Can't we sequentially initialize in `setup()` instead?

2021-10-21 20:21 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +float CSE7761Component::get_setup_priority() const { return setup_priority::DATA; }
I think this should be `HARDWARE` instead.

2021-10-21 20:21 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +void CSE7761Component::write_(uint32_t reg, uint32_t data) {
Only the lower byte of `reg` is used, and the upper two bytes of `data` are always ignored, so they should be `uint8_t` and `uint16_t` respectively (and that change should cascade through to the other methods calling `write_`).

2021-10-21 20:21 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +  while (!time_reached(timeout) && (rcvd <= size)) {
`read()` already blocks for up to 100 milliseconds, so this timeout is pointless.

2021-10-21 20:21 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +  if (rcvd > 5) {
Since `size` is never more than 4, this check can never trigger.

2021-10-21 20:21 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +  return value;
This causes the previous value to be republished when the read fails, which is not desirable. Why is the fallback (and retry logic, for that matter) needed at all?

2021-10-21 20:21 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +                                                       // positive and negative signal
I think this comment is incorrect, we're definitely not Tasmota :)

2021-10-21 20:21 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +  this->data_.active_power[0] = (0 == this->data_.current_rms[0]) ? 0 : (value & 0x80000000) ? (~value) + 1 : value;
I think it's much nicer to just do a reinterpret_cast to interpret it as a signed number.

2021-10-22 22:52 UTC, berfenger commented on esphome/components/cse7761/cse7761.cpp
> +#define CSE7761_CMD_ENABLE_WRITE 0xE5           // Enable write operation
Changed to static consts.

2021-10-22 22:53 UTC, berfenger commented on esphome/components/cse7761/cse7761.cpp
> +uint32_t cse7761ref(uint32_t unit, CSE7761DataStruct *data) {
Moved to member function.

2021-10-22 22:54 UTC, berfenger commented on esphome/components/cse7761/cse7761.cpp
> +  }
Moved init logic to setup(). The state machine does not seem to be needed in esphome.

2021-10-22 22:57 UTC, berfenger commented on esphome/components/cse7761/cse7761.cpp
> +float CSE7761Component::get_setup_priority() const { return setup_priority::DATA; }
Changed. I used the same value as other sensors like the cse7766.

2021-10-22 22:57 UTC, berfenger commented on esphome/components/cse7761/cse7761.cpp
> +void CSE7761Component::write_(uint32_t reg, uint32_t data) {
Changed

2021-10-22 22:57 UTC, berfenger commented on esphome/components/cse7761/cse7761.cpp
> +  while (!time_reached(timeout) && (rcvd <= size)) {
Removed pointless timeouts

2021-10-22 22:58 UTC, berfenger commented on esphome/components/cse7761/cse7761.cpp
> +  if (rcvd > 5) {
Removed

2021-10-22 22:58 UTC, berfenger commented on esphome/components/cse7761/cse7761.cpp
> +  return value;
Fallback functions does not seem to be needed. Removed.

2021-10-22 23:01 UTC, berfenger commented on esphome/components/cse7761/cse7761.cpp
> +  this->data_.active_power[0] = (0 == this->data_.current_rms[0]) ? 0 : (value & 0x80000000) ? (~value) + 1 : value;
Changed the way to convert negative numbers to uint32_t. Sometimes the cse7761 reports the value as a negative number that should be converted to a positive number.

2021-10-23 17:08 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +float CSE7761Component::get_setup_priority() const { return setup_priority::DATA; }
Oh, sorry about that, I confused `DATA` and `PROCESSOR`, `DATA` is indeed correct here. I've reverted this change.

2021-10-23 17:17 UTC, oxan approved these changes
Thanks!

2021-10-23 17:17 UTC, oxan commented on esphome/components/cse7761/cse7761.cpp
> +  }
Maybe a log message would be nice here in the unlikely event that reading fails thrice:
```suggestion
  while (!result && retry > 0) {
    retry--;
    if (this->read_once_(reg, size, &value))
      return value;
  }
  ESP_LOGE(TAG, "Reading register %hhu failed!", reg);
```

2021-10-28 18:58 UTC, merged