Add Mopeka BLE and Mopeka Pro Check BLE Sensor
OttoWinter/esphomeyaml pull request #2618
Opened 2021-10-23 06:44 UTC by spbrogan

# What does this implement/fix? 

Add support for Mopeka Pro Check LP BLE sensor and adds generic component that helps find the BLE MAC address.  
This is a similar pattern to other BLE advertisement based sensors.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <https://github.com/esphome/feature-requests/issues/1445>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1564

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
sensor:
  # Example using 20lb vertical propane tank.
  - platform: mopeka_pro_check
    mac_address: D3:75:F2:DC:16:91
    tank_type: 20LB_V
    temperature:
      name: "Propane test temp"
    level:
      name: "Propane test level"
    distance:
      name: "Propane test distance"
    battery_level:
      name: "Propane test battery level"

  # Custom example - user defined empty / full points
  - platform: mopeka_pro_check
    mac_address: D3:75:F2:DC:16:91
    tank_type: CUSTOM
    custom_distance_full: 40cm
    custom_distance_empty: 10mm
    temperature:
      name: "Propane test temp"
    level:
      name: "Propane test level"
    distance:
      name: "Propane test distance"
    battery_level:
      name: "Propane test battery level"

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-10-23 06:49 UTC, spbrogan commented
I have done minor refactor since it was last functionally tested.  I will run tests to make sure both components work before checking that task off.

2021-10-25 03:33 UTC, spbrogan commented
> I have done minor refactor since it was last functionally tested. I will run tests to make sure both components work before checking that task off.

this works for me locally.  I think the PR is ready to go.  Please provide any feedback.

2021-11-02 05:07 UTC, spbrogan commented
do you want me to resolve the conflict as it is just the test code which should be trivial?  I assume when you are ready to merge you would resolve the conflicts (as more could come up before you choose to merge this).

2021-11-22 05:50 UTC, spbrogan commented
What needs to happen to get this merged?  Is there a step in the process I am missing?

2021-12-06 17:20 UTC, sdellysse commented
echoing @spbrogan's comment: I'm building a system with a few ESPHome devices, and having this in-main would be really nice

2021-12-23 22:11 UTC, spbrogan commented
I just force pushed to the PR.  Only 2 changes.  
1. rebased on latest dev to remove old merge commits
2. updated the defined values for min/max for standard US propane tanks so that the percent calculation more closely aligns with the sensor supplied app.

2021-12-24 01:45 UTC, spbrogan commented
can this get merged.  I just got notified my documentation PR will be closed if no activity.  Is there something more that is needed?

2022-01-28 04:22 UTC, spbrogan commented
This has been done since Oct.  Tested, documented, and even requested by other community members.  I can't figure out what needs to happen to get this merged or how to draw the necessary attention to it.  I have noticed plenty of similar new integrations have been merged much faster so again I am looking for some feedback for how this project prioritizes contributions and pull requests.  Should I ask on discord? Do the "maintainers" not have BBQs and thus don't track their propane levels?  :)

2022-02-14 17:41 UTC, helenclarko commented
Who needs to see this to get it merged in?

2022-02-14 18:40 UTC, jesserockz commented on esphome/components/mopeka_pro_check/sensor.py
> +    return meters * 100
`cv.distance` takes care of all conversions. You just need to multiply the value by 1000 to get mm at the end.

2022-02-14 19:41 UTC, spbrogan commented on esphome/components/mopeka_pro_check/sensor.py
> +    return meters * 100
My understanding: cv.distance() only supports meters.  that means a user must enter the values in meters which is awkward.  
https://github.com/esphome/esphome/blob/0ec84be5dacb1a9d0c3cc5c5da5de9a3e9b14df9/esphome/config_validation.py#L848

So the small_distance function allows a user to enter in mm, cm, or meters. 

Am i reading it wrong?

2022-02-14 19:44 UTC, spbrogan commented on esphome/components/mopeka_pro_check/sensor.py
> +    return meters * 100
regardless...there is a bug in that line 48 is only doing meters * 100.  So if a user had entered the distance in meters they would not get the right values.  I'll fix that once we have alignment on the above.  Thanks

2022-02-14 22:49 UTC, jesserockz commented on esphome/components/mopeka_pro_check/sensor.py
> +    return meters * 100
> Am i reading it wrong?

Yes :smile: 

It means that the base unit and returned value is meters. A user can still put `500mm`, and then the validator will return `0.5` as the actual value (which is why you need the `* 1000`

2022-02-14 22:49 UTC, jesserockz commented on esphome/components/mopeka_pro_check/sensor.py
> +    return meters * 100
`float_with_unit` handles prefixes and multiplications on the `m` (for meters)

2022-02-17 21:05 UTC, jesserockz commented on esphome/components/mopeka_pro_check/sensor.py
> +
```suggestion


```

2022-02-20 02:44 UTC, helenclarko commented
Good to go now then?

2022-02-21 00:31 UTC, jesserockz approved these changes

2022-02-21 00:51 UTC, jesserockz requested changes

2022-02-21 00:51 UTC, jesserockz commented on esphome/components/mopeka_pro_check/sensor.py
> +            ),
I actually noticed this stand out more when reading the docs PR, should there even be a default here? I think should be required for everyone.
```suggestion
            cv.Required(CONF_TANK_TYPE): cv.enum(
                CONF_SUPPORTED_TANKS_MAP, upper=True
            ),
```

2022-02-26 06:21 UTC, helenclarko commented
What does this need now?

2022-02-28 04:15 UTC, jesserockz approved these changes

2022-02-28 22:30 UTC, merged