Optionally show internal components on the web server
OttoWinter/esphomeyaml pull request #2627
Opened 2021-10-25 06:09 UTC by mechanarchy

# What does this implement/fix? 

I would like to be able to restart a node or view its signal strength, but I have no need for these entities to be added to my Home Assistant installation. While components can be marked `disabled_by_default`, this still pollutes the Hass database and adds unnecessary overhead.

This change adds a new `include_internal` boolean option to the `web_server` component. By default, this is set to `false` and the behaviour of ESPHome is unchanged. If the user opts-in to the new feature by setting the option to `true`, internal entities will be displayed on the node's web server.

## Types of changes

- Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Other

~~**Related issue or feature (if applicable):** n/a~~

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1572

## Test Environment

- [x] ESP32
- ESP32 IDF
- ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml, snippet only
web_server:
  include_internal: true

switch:
  - platform: shutdown
    id: node_shutdown
  - platform: restart
    id: node_restart
  - platform: safe_mode
    id: node_safe_mode
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-10-27 19:02 UTC, jesserockz commented on esphome/components/web_server/web_server.cpp
> +
This is always defined by code_generation. For development purposes you can add it to `esphome/core/defines.h`

2021-10-29 07:04 UTC, mechanarchy commented on esphome/components/web_server/web_server.cpp
> +
I have moved the default to `defines.h` instead.

2021-11-01 20:26 UTC, oxan requested changes
I'm not too fond of this option, but I guess there are usecases where it can be useful. Can we set it as a propery on the webserver object though, instead of a define? We usually only use defines for parameters that are necessary deep inside other components (and we try to limit that as much as possible).

2021-11-10 17:15 UTC, oxan requested changes

2021-11-10 17:15 UTC, oxan commented on esphome/components/web_server/__init__.py
> +        cv.Optional(CONF_INCLUDE_INTERNAL): cv.boolean,
We prefer setting defaults in the schema:
```suggestion
        cv.Optional(CONF_INCLUDE_INTERNAL, default=True): cv.boolean,
```

2021-11-10 17:15 UTC, oxan commented on esphome/components/web_server/__init__.py
> +        cg.add(var.set_include_internal(config[CONF_INCLUDE_INTERNAL]))
So that this can be unconditional (probably better to move it up as well):
```suggestion
    cg.add(var.set_include_internal(config[CONF_INCLUDE_INTERNAL]))
```

2021-11-10 19:03 UTC, jesserockz commented on esphome/components/web_server/web_server.cpp
> +  this->setup_controller(true);  // always include internal entities here, as we filter them later
Why not use this here?
```suggestion
  this->setup_controller(this->include_internal_);
```

2021-11-10 20:02 UTC, mechanarchy commented on esphome/components/web_server/web_server.cpp
> +  this->setup_controller(true);  // always include internal entities here, as we filter them later
Using `this->include_internal_` will require reinitialising the entire webserver component when the value changes.

The `Controller::setup_controller` function runs `add_on_state_callback` for each component; however there is no corresponding `remove_on_state_callback` function we can use to un-hook internal entities, if we decide to later stop showing them.

2021-11-15 14:51 UTC, oxan commented on esphome/components/web_server/web_server.cpp
> +  this->setup_controller(true);  // always include internal entities here, as we filter them later
> Using this->include_internal_ will require reinitialising the entire webserver component when the value changes.

That's fine, we don't support configuration changes at runtime anyway.

2021-11-16 20:59 UTC, nagyrobi commented
+1 for this, I was thinking on how to achieve this just today!!!!

2021-11-17 08:02 UTC, nagyrobi commented
...and the reason I was thinking about just happened. Had a power outage due to which the PI running HA wouldn't boot. Not a problem to fix, but that took a while - _until_ HA was back up and running, it would have been super useful to access the some directly on the device's web interface...!

2021-11-23 08:51 UTC, oxan commented on esphome/components/web_server/web_server.cpp
> +    return;
These `if`s (in `on_*_update`) can be removed now that we pass `include_internal_` to `setup_controller`, I think.

2021-11-29 09:13 UTC, mechanarchy commented on esphome/components/web_server/web_server.cpp
> +    return;
Good point! Rectified in 7d96fe1d

2021-11-29 09:41 UTC, nagyrobi commented
@mechanarchy please note that there's a Webserver v2 work in progress: https://github.com/esphome/esphome/pull/2688
Maybe worth to prepare that one too for this functionality...

2021-11-29 09:52 UTC, mechanarchy commented
> @mechanarchy please note that there's a Webserver v2 work in progress: #2688 Maybe worth to prepare that one too for this functionality...

Thanks for the heads up - I had not yet seen that. Once this is merged for the original web server code I will look into getting it added to v2. It seems there will be a lot of merge errors, but hopefully it will be easy to resolve...

2021-11-29 10:25 UTC, jesserockz approved these changes
LGTM

2021-11-29 10:25 UTC, jesserockz commented on esphome/components/web_server/web_server.h
> +
Extra blank line?
```suggestion
```

2021-11-29 10:31 UTC, mechanarchy commented on esphome/components/web_server/web_server.h
> +
Looks like that was introduced erroneously while merging in the primary `dev` branch. Removed now :+1:

2021-11-29 10:34 UTC, oxan approved these changes

2021-11-29 15:52 UTC, merged

2021-11-29 15:52 UTC, oxan commented
Thanks!

2021-11-30 02:27 UTC, wilberforce commented
@jesserockz @mechanarchy 

I'll merge these changes into my branch....