CAP1188 Capacitive Touch Sensor Support
OttoWinter/esphomeyaml pull request #2653
Opened 2021-11-02 02:31 UTC by MrEditor97

# What does this implement/fix? 
This adds the ability to use a CAP1188 Capacitive Touch Sensor with ESPHome.
It allows up to 8 touch channels to be used on the I2C bus.

_I have not added support for SPI as of yet, but if it gets requested, I can look into it._

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
i2c:
  sda: 21
  scl: 22
  scan: true

cap1188:
  id: cap1188_component
  address: 0x29
  allow_multiple_touches: 0x80
  touch_threshold: 0x40
  reset_pin: 14
  
binary_sensor:
  - platform: cap1188
    id: touch_key0
    cap1188_id: cap1188_component
    channel: 0
    name: "Touch Key 0"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-03 16:54 UTC, oxan requested changes
Thanks for your contribution! I've a few comments below.

2021-11-03 16:54 UTC, oxan commented on esphome/components/cap1188/__init__.py
> +            ),
With only two allowed options, and the phrasing of the option, I think a boolean makes more sense here.

2021-11-03 16:54 UTC, oxan commented on esphome/components/cap1188/cap1188.h
> +  void write_state(bool state) override { this->pin_->digital_write(state); }
Why does this component need to be an output if it just forwards the output to the reset pin? Users that want an output to reset the device (why though?) can just use a GPIO output on the same pin.

2021-11-03 16:54 UTC, oxan commented on esphome/components/cap1188/cap1188.h
> +  GPIOPin *pin_;
Naming this `reset_pin_` helps readability.

2021-11-03 16:54 UTC, oxan commented on esphome/components/cap1188/cap1188.cpp
> +  if ((cap1188_product_id != 0x50) || (cap1188_manufacture_id != 0x5D) || (cap1188_revision != 0x83)) {
Is it really necessary to pin this component to a single revision?

2021-11-03 16:54 UTC, oxan commented on esphome/components/cap1188/cap1188.h
> +  friend class CAP1188Component;
There's not actually anything in `CAP1188Component` that uses protected members of `CAP1188Channel`, so either this declaration can be dropped or `process` should be made protected.

2021-11-03 16:54 UTC, oxan commented on esphome/components/cap1188/cap1188.h
> +  optional<uint8_t> touch_threshold_{};
This threshold doesn't seem to actually be used anywhere?

2021-11-03 19:37 UTC, MrEditor97 commented on esphome/components/cap1188/__init__.py
> +            ),
I shall adjust it to a boolean value for ease. As you say the phrasing is more pointing towards a true or false situation rather than the value required by the CAP1188.

This is my first time helping with a project, so I definitely appreciate the time taken by you to correct any mistakes and any advice on how to further progress the feature.

2021-11-03 23:27 UTC, MrEditor97 commented on esphome/components/cap1188/cap1188.h
> +  void write_state(bool state) override { this->pin_->digital_write(state); }
So here if I understand correctly, I believe that removing this below:
```suggestion
```
In favour of directly interfacing with the GPIO Pin by using the built in methods (using this below when required):
```c++
this->pin_->digital_write(state);
```
I believe I should be changing it to a optional addition - as it isn't required to function properly. Although, it is within the Adafruit CAP1188 Library which can be found [here](https://github.com/adafruit/Adafruit_CAP1188_Library/blob/fad505c68f5e29027d68553c7f3d10a9b690d0ae/Adafruit_CAP1188.cpp#L107-L115). It's method of use can be found within the [documentation](https://cdn-shop.adafruit.com/datasheets/CAP1188.pdf) for the device too.
It is used to reset the registers which I found useful during development.

2021-11-04 00:51 UTC, MrEditor97 commented on esphome/components/cap1188/cap1188.cpp
> +  if ((cap1188_product_id != 0x50) || (cap1188_manufacture_id != 0x5D) || (cap1188_revision != 0x83)) {
I am limiting it to a single revision as I believe that it is the only one that is currently available. Within the Adafruit CAP1188 Library they have also limited it to only this revision. That can be found [here](https://github.com/adafruit/Adafruit_CAP1188_Library/blob/fad505c68f5e29027d68553c7f3d10a9b690d0ae/Adafruit_CAP1188.cpp#L128-L132).

2021-11-04 03:11 UTC, MrEditor97 commented on esphome/components/cap1188/cap1188.h
> +  optional<uint8_t> touch_threshold_{};
Yes, I agree. The CAP1188 doesn't have the ability to change each channels individual sensitivity, so this is not required.
```suggestion
```

2021-11-04 03:14 UTC, MrEditor97 commented on esphome/components/cap1188/cap1188.h
> +  void set_touch_threshold(uint8_t touch_threshold) { this->touch_threshold_ = touch_threshold; };
Can be removed. CAP1188 does not have the ability to change individual channel sensitivities.
```suggestion
```

2021-11-04 18:20 UTC, oxan reviewed
Thanks! This looks pretty good now, just one thing remaining.

2021-11-04 18:20 UTC, oxan commented on esphome/components/cap1188/cap1188.cpp
> +  if ((cap1188_product_id != 0x50) || (cap1188_manufacture_id != 0x5D) || (cap1188_revision != 0x83)) {
> it is the only one that is currently available.

That might not always be the case, and it would be nice if newer revisions would work out of the box. Revisions usually don't have a changed interface.

It would also be nice to log the detected product and manufacturer ID when the check fails, so that in the future other variants can easily be identified and possibly added.

2021-11-04 18:20 UTC, oxan commented on esphome/components/cap1188/cap1188.cpp
> +      ESP_LOGE(TAG, "Communication with CAP1188 failed!");
As far as I can see this error code is only set when the manufacturer ID check fails, so this error message isn't really correct.

2021-11-10 17:10 UTC, oxan requested changes

2021-11-10 17:10 UTC, oxan commented on esphome/components/cap1188/cap1188.cpp
> +    this->reset_pin_->pin_mode(esphome::gpio::FLAG_OUTPUT);
You should setup the pin instead, the code generator takes care of setting the output mode.
```suggestion
    this->reset_pin_->setup();
```

2021-11-10 17:52 UTC, merged

2021-11-10 17:53 UTC, oxan commented
Thanks for your contribution!