Add max_telegram_length option to dsmr
OttoWinter/esphomeyaml pull request #2674
Opened 2021-11-07 00:53 UTC by mmakaay

# What does this implement/fix? 

This PR adds a `max_telegram_length` option to the dsmr component, making it possible to accept telegrams that are beyond the previously hard-coded size of 1500 bytes.
WIthout this fix, DSMR would fail with `Error: Message larger than buffer` on telegrams > 1500 bytes.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2393

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
dsmr:
  max_telegram_length: 3000
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-10 17:30 UTC, oxan requested changes

2021-11-10 17:30 UTC, oxan commented on esphome/components/dsmr/dsmr.cpp
> +  }
Why `char` for one and `uint8_t` for the other?

2021-11-10 17:30 UTC, oxan commented on esphome/components/dsmr/dsmr.cpp
> +  }
So, if I'm right, `set_decryption_key` gets added by codegen when the `decryption_key` setting is present, and thus called before `setup()`. `setup()` in turn allocates its own buffer, causing a memory leak here. 

Setters for settings really shouldn't do as much as this one does. I think just the conversion to binary should remain here, the rest should be done in `setup` instead.

2021-11-10 17:30 UTC, oxan commented on esphome/components/dsmr/dsmr.cpp
> +}
Furthermore, did you realize this doubles heap usage, as the encrypted telegram was previously only placed on the stack in `receive_encrypted_`. I'm not sure if anyone uses DMSR with 8266's, but I've seen them have way less than 1500 free bytes on the heap.

2021-11-10 18:18 UTC, mmakaay commented on esphome/components/dsmr/dsmr.cpp
> +  }
I followed the existing types for those. I noticed that too, but assumed that the reason was that the decryption libraries were in favor of uint8_t[], making that the logical choice.

2021-11-10 18:27 UTC, mmakaay commented on esphome/components/dsmr/dsmr.cpp
> +  }
The thing is that people can setup the YAML without encryption key for DSMR, in which case you don't want to create the encrypted telegram buffer at setup time. This setter was implemented by - I think - @glmnet to allow for setting the encryption key at runtime. That is a requirements for smart meters that occasionally roll over the encryption key, requiring a call to an API service on the ESPHome device to update the key. What was already built-in before my change, is that the encryption key can also be removed fully from such service call.

So, while it looks a lot like the type of configuration setter function that you see with other components, in this component is actually a function that is expected to be called during the runtime. 

You are right that `set_decryption_key(...)` is called from the Python `to_code(...)` function, so that makes the allocation from the `setup()` redundant indeed. I will remove that one.

2021-11-10 18:45 UTC, mmakaay commented on esphome/components/dsmr/dsmr.cpp
> +  }
Committed a change with no allocation from setup().

2021-11-10 19:06 UTC, mmakaay commented on esphome/components/dsmr/dsmr.cpp
> +}
DSMR is mainly used with ESP8266 even. I haven't seen other designs.

There's an underlying reason for moving to heap with this. The current implementation does read the full encrypted telegram from within the read function. While this currently should work well with my latest changes, the use of a buffer on stack closes down the route to improve the read function in upcoming changes (where improving means: allowing the `loop()` to return now and then, instead of blocking it until the telegram is read completely).

A couple of considerations for this:
- Is the heap solution breaking for ESP8266? If yes, then it's a bad idea by definition.
- Do encrypted telegrams > 1500 bytes exist? If not, then there's no need to make it configurable.
- Is it okay to not optimize the encrypted read and to block `loop()`? If yes, then also no need to make it configurable.

2021-11-10 21:26 UTC, oxan commented on esphome/components/dsmr/dsmr.cpp
> +  }
Hmm, okay, that makes sense. I still would prefer having the configuration setter do (almost) nothing and then do the actual work in a separate method called from `setup()`, but I don't think this will break anything.

2021-11-10 21:33 UTC, oxan commented on esphome/components/dsmr/dsmr.cpp
> +}
> Is the heap solution breaking for ESP8266? If yes, then it's a bad idea by definition.

What I'm concerned about is that I've seen lots of reports from people running out of memory on ESP8266's. When that happens it's pretty ugly, as OTA's are one of the things that require relatively much RAM, so upgrading becomes very hard. Generally we have a bit more stack space than heap space available on ESP8266's (theoretically we could make it possible to change that divide, but that would require a deep dive into how Arduino sets this up...). 

Memory usage more or less scales with how many components you use though, and I guess people don't use that much stuff on DMSR readers, so it's probably fine. It has gotten better since I fixed a bunch of memory eaters a release or two ago as well.

> Do encrypted telegrams > 1500 bytes exist? If not, then there's no need to make it configurable.

That's a question for you to answer :)

> Is it okay to not optimize the encrypted read and to block loop()? If yes, then also no need to make it configurable.

I agree it'd be nice not to block loop().

2021-11-10 21:34 UTC, oxan commented on esphome/components/dsmr/dsmr.cpp
> +  }
Hmm, okay, that makes sense. I still would prefer having the configuration setter do (almost) nothing and then do the actual work in a separate method called from `setup()`, but I don't think this will break anything.

2021-11-10 21:45 UTC, mmakaay commented on esphome/components/dsmr/dsmr.cpp
> +  }
Yes, I would prefer that too, following the principle of not doing much work at construct time, but the main thing is that this is not only for setup-time, but also for run-time key changes. When at setup-time it would be always 100% clear if encrypted data is to be read, then it would be okay to simply setup the encrypted buffer and forget about it. However, within the current code, it is allowed to start without encryption and upgrading to encryption later on using a service call for example. That breaks the perfect setup-methodology here.

Don't know if you know about this dynamic key management that I'm referring to. If you don't they you can check out [Zuidwijk's SlimmeLezer YAML](https://github.com/zuidwijk/dsmr/blob/main/slimmelezer.yaml) in which this is applied in `on_boot` and an `api` service.

2021-11-10 21:54 UTC, mmakaay commented on esphome/components/dsmr/dsmr.cpp
> +}
> That's a question for you to answer :)

Hehe, if only I were the expert on this! I haven't seen them, but logic tells me that if we do see unencrypted telegrams of about 3000 bytes, that we might expect them in encrypted form at some point too. There's no reason why encryption and only-small-telegrams would be correlated.

You are right about the number of components. For DSMR, I do use an I2C display myself, which is already quite exotic, and I use a pin for controlling the P1 Data Request pin (separate PR coming up for that). Users might possibly add something like a pulse meter for water measurements, since that's often nearby, and I know that @jsuanet has a display and PIR connected (where the PIR triggers the display activation).

What I will do: I will setup a device with all of the above, enryption and a telegram size of 3000 bytes. If that works, I think we can be pretty sure that things are okay. If not... well fingers crossed!

2021-11-10 23:07 UTC, mmakaay commented on esphome/components/dsmr/dsmr.cpp
> +}
- Standard components: esphome, wifi, api, ota, logger
- UART debugging added as external component and activated
- i2c, font, display platform ssd1306_i2c
- dsmr with encryption, `max_telegram_size = 5000` (very big!), all Dutch sensors active
- a gpio switch used to control the P1 Data Request pin

Using all this, after parsing an encrypted telegram `API.getFreeHeap()` reported 10280 bytes free.

So based on this, I say that we can get away with these heap allocations.

2021-11-14 15:19 UTC, oxan commented on esphome/components/dsmr/dsmr.cpp
> +  }
> but the main thing is that this is not only for setup-time, but also for run-time key changes

My idea was to split that into two different methods ;) But it's fine.

2021-11-14 15:37 UTC, oxan approved these changes
I'd really rather not have all this manual memory management and usage of raw arrays, but that seems to require a bigger refactor of this whole component, so this is okay for now.

Noticed one memory leak though (perfect example why I don't want manual memory management).

2021-11-14 15:37 UTC, oxan commented on esphome/components/dsmr/dsmr.cpp
> +      delete encrypted_telegram_;
```suggestion
      delete[] encrypted_telegram_;
```

2021-11-14 15:42 UTC, mmakaay commented on esphome/components/dsmr/dsmr.cpp
> +      delete encrypted_telegram_;
Thanks, I don't like manual memory management either, for obvious reasons ;-)
No problems with that in pure C, and no problems with languages that don't do allow for that at all.
But in C++, it's quite easy to slip because of the hybrid nature :-/

2021-11-14 15:46 UTC, oxan commented on esphome/components/dsmr/dsmr.cpp
> +      delete encrypted_telegram_;
Yeah, definitely, though the CI check you've to suppress should be a hint it's not the best solution ;-)

2021-11-14 18:53 UTC, mmakaay commented on esphome/components/dsmr/dsmr.cpp
> +      delete encrypted_telegram_;
That was simply imitation of existing other code ;-) I never actually saw a hint.

2021-11-17 17:24 UTC, merged