Modbus_controller: Add custom command.
OttoWinter/esphomeyaml pull request #2680
Opened 2021-11-08 11:23 UTC by martgras

# What does this implement/fix? 
Add custom commands to modbus controller items 
Move duplicate python code to  functions in modbus_controller __init__.py

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:
```yaml
# demonstrate how to use custom_command and  proces raw results in lambda.
# both examples just reimplement reading FP32 from registster 0x156 and 0x158
  - platform: modbus_controller
    modbus_controller_id: sdm
    name: "Total active energy"
    id: total_energy
    #    address: 0x156
    #    register_type: "read"
    ## reimplement using custom_command
    # 0x1 : modbus device address
    # 0x4 : modbus function code
    # 0x1 : high byte of modbus register address
    # 0x56: low byte of modbus register address
    # 0x00: high byte of total number of registers requested 
    # 0x02: low byte of total number of registers requested
    custom_command: [ 0x1, 0x4, 0x1, 0x56,0x00, 0x02]
    value_type: FP32
    unit_of_measurement: kWh
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: sdm
    name: "Total reactive energy"
    #   address: 0x158
    #   register_type: "read"
    custom_command: [0x1, 0x4, 0x1, 0x58, 0x00, 0x02]
    ## the command returns an float value using 4 bytes
    lambda: |-
      ESP_LOGD("Modbus Sensor Lambda","Got new data" );
      union {
        float float_value;
        uint32_t raw;
      } raw_to_float;
      if (data.size() < 4 ) {
        ESP_LOGE("Modbus Sensor Lambda", "invalid data size %d",data.size());
        return NAN;
      }
      raw_to_float.raw =   data[0] << 24 | data[1] << 16 | data[2] << 8 |  data[3];
      ESP_LOGD("Modbus Sensor Lambda", "FP32 = 0x%08X => %f", raw_to_float.raw, raw_to_float.float_value);
      return raw_to_float.float_value;
    unit_of_measurement: kVArh
    accuracy_decimals: 1
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-09 22:37 UTC, jesserockz commented on esphome/components/modbus_controller/binary_sensor/__init__.py
> +        ModbusItemBaseSchema.extend(
Try not to nest the extends, you can just extend again afterwards to add the specific fields

2021-11-10 08:27 UTC, martgras commented on esphome/components/modbus_controller/binary_sensor/__init__.py
> +        ModbusItemBaseSchema.extend(
Better now?

2021-11-15 11:35 UTC, martgras commented
Sorry messed up merging and caused unrelated notifications

2021-11-17 17:54 UTC, oxan requested changes

2021-11-17 17:54 UTC, oxan commented on esphome/components/modbus_controller/__init__.py
> +    # A CONF_BYTE_OFFSET setting overrides CONF_OFFSET
Then it shouldn't be possible to specify both in the config. Take a look at `cv.Exclusive`.

2021-11-17 17:54 UTC, oxan commented on esphome/components/modbus_controller/__init__.py
> +        if [CONF_ADDRESS] not in config:
I don't think the brackets here are correct, now it check if a list with `CONF_ADDRESS` as its only item is in `config` (which can't happen, I think).

2021-11-17 17:54 UTC, oxan commented on esphome/components/modbus_controller/__init__.py
> +            hash_ = int(hashlib.md5(value).hexdigest()[:4], 16)
If we need a 16-bit integer, MD5 and a roundtrip conversion with a hex-encoding is overkill.
```suggestion
            hash_ = int.from_bytes(hashlib.shake_128(d).digest(2), "little")
```
Or since I don't think this has to be cryptographically strong, could also use CRC32.

2021-11-17 17:54 UTC, oxan commented on esphome/components/modbus_controller/switch/__init__.py
> +    validate_modbus_register,
No nested extends, please.

2021-11-17 17:54 UTC, oxan commented on esphome/components/modbus_controller/switch/__init__.py
> +    if CONF_WRITE_LAMBDA in config:
Maybe I'm being blind, but I don't see `CONF_WRITE_LAMBDA` in the schema.

2021-11-17 18:38 UTC, martgras commented on esphome/components/modbus_controller/switch/__init__.py
> +    validate_modbus_register,
Is this schema ok?
https://github.com/esphome/esphome/blob/8cf4e89eea01be5287bdb095dc17de6c80c42a7d/esphome/components/modbus_controller/binary_sensor/__init__.py#L31

Otherwise  I need a bit help how to avoid nested schema

2021-11-17 18:38 UTC, oxan commented on esphome/components/modbus_controller/switch/__init__.py
> +    validate_modbus_register,
Yes, that one's fine.

2021-11-18 08:40 UTC, martgras commented on esphome/components/modbus_controller/switch/__init__.py
> +    if CONF_WRITE_LAMBDA in config:
thanks - all suggestions implemented

2021-11-18 08:42 UTC, martgras commented on esphome/components/modbus_controller/__init__.py
> +    # A CONF_BYTE_OFFSET setting overrides CONF_OFFSET
done

2021-11-18 08:44 UTC, martgras commented on esphome/components/modbus_controller/__init__.py
> +    # A CONF_BYTE_OFFSET setting overrides CONF_OFFSET
done

2021-11-18 12:03 UTC, martgras commented on esphome/components/modbus_controller/__init__.py
> +        if [CONF_ADDRESS] not in config:
of course not correct

2021-11-18 15:06 UTC, oxan approved these changes

2021-11-25 23:48 UTC, merged