Make OTA function switchable in web_server component
OttoWinter/esphomeyaml pull request #2685
Opened 2021-11-09 21:13 UTC by lazlyhu

# What does this implement/fix? 

This PR provide a new argument for `web_server` component for turn off OTA feature because security reasons. For example if the authentication not enabled, or the node accessable from the internet directly because some reason.

I would prefer keep this feature turned off by default, but in this case this change would be a breaking change. Let me know what do you think.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
web_server:
  ota: false
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-09 22:31 UTC, jesserockz requested changes
Please change to `USE_WEBSERVER_OTA`

Also please add `#define USE_WEBSERVER_OTA` into `esphome/core/defines.h` which activates it for development purposes.

2021-11-10 17:18 UTC, oxan commented
> Please change to `USE_WEBSERVER_OTA`

I think we don't even need a define, just a member field on the webserver object should be fine here. We really only use defines when a setting needs to be accessed deep inside another component.

2021-11-10 19:30 UTC, jesserockz approved these changes

2021-11-10 19:31 UTC, merged

2021-11-10 19:33 UTC, lazlyhu commented
@jesserockz Thank you for the review and implementing too :bow: