Improve DSMR read timeout handling
OttoWinter/esphomeyaml pull request #2699
Opened 2021-11-11 10:37 UTC by mmakaay

# What does this implement/fix? 

This PR contains some ideas for improving the DSMR read code. It's very much a draft now, simply because there are a few other DSMR changes in the pipeline and this will need manual merging eventually.

The eventual goals for this PR are:
[x] Code cleanup: deduplicate the read timeout handling, because the logic for encrypted and unencrypted telegrams is very much the same
[x] Code cleanup: implement a telegram reset method, that can be called whenever reading a telegram must be stopped. Right now, various spots in the code set field values to arrange this, but it's easy to forget setting the correct fields this way.
[x] Bugfix: stop reading a telegram fully when a read timeout occurs, so next loop iterations won't wait for the full timeout time on followup loop iterations. This reportedly could result in an un-ping-able device, because the dsmr component keeps blocking other components on every iteration.
[ ] Bugfix: Don't use the blocking read loop when the UART `rx_buffer_size` is large enough to hold a telegram. In that case there is no risk in overflowing the buffer and as a result, the blocking read loop is not needed to prevent that. This will give some more air to other components.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-25 21:23 UTC, oxan requested changes
The DSMR part LGTM.

2021-11-25 21:23 UTC, oxan commented on esphome/components/uart/uart_debugger.cpp
> +  delay(10);
Have you tried a `yield()` here? That might be able to flush the buffers as well, without these costly delays.

2021-11-25 21:55 UTC, mmakaay commented on esphome/components/uart/uart_debugger.cpp
> +  delay(10);
Yield is basically a delay(0), right? That wouldn't work I think, because I also tried a delay(5) and that one gave only partly successful results.

2021-11-29 15:40 UTC, oxan commented on esphome/components/uart/uart_debugger.cpp
> +  delay(10);
Hmm, ok. Still not happy with it, but I also can't think of another way to avoid this problem, so let's merge this for now and see if we can work out something better long-term.

2021-11-29 15:40 UTC, oxan approved these changes

2021-11-29 15:40 UTC, merged