Provide an option to select unique_id generator
OttoWinter/esphomeyaml pull request #2701
Opened 2021-11-11 18:55 UTC by kbialek

# What does this implement/fix? 

Provides fully backwards compatible option to specify alternative unique_id generator.
The existing generator is retained, and used as the default one.
Additionally a new, mac-address based generator is implemented.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes
* https://github.com/esphome/esphome/pull/2280
* https://github.com/esphome/issues/issues/1637

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:
```yaml
# Default
mqtt:
  discovery_unique_id_generator: legacy

# mac-address based
mqtt:
  discovery_unique_id_generator: mac
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-11 21:30 UTC, jesserockz requested changes
Please change this to use an enum, not a string

2021-11-12 03:08 UTC, jesserockz requested changes

2021-11-12 03:08 UTC, jesserockz commented on esphome/components/mqtt/mqtt_client.cpp
> +void MQTTClientComponent::set_discovery_info(std::string &&prefix, MQTTDiscoveryUniqueIdGenerator &&unique_id_generator,
```suggestion
void MQTTClientComponent::set_discovery_info(std::string &&prefix, MQTTDiscoveryUniqueIdGenerator unique_id_generator,
```

2021-11-12 03:08 UTC, jesserockz commented on esphome/components/mqtt/mqtt_client.h
> +  void set_discovery_info(std::string &&prefix, MQTTDiscoveryUniqueIdGenerator &&unique_id_generator, bool retain,
```suggestion
  void set_discovery_info(std::string &&prefix, MQTTDiscoveryUniqueIdGenerator unique_id_generator, bool retain,
```

2021-11-13 08:21 UTC, jesserockz approved these changes

2021-11-13 14:34 UTC, oxan commented
If we're gonna change the unique_id generation, I'd like to get it right, specifically esphome/issues#2028 (non-Latin characters are stripped in the `default_object_id`). I think allowing non-ASCII characters into the unique id is asking for problems, so it's probably best if we hash the name and use that.

2021-11-13 14:49 UTC, kbialek commented
@oxan This goal of this PR is to add an option to generate more distinct `unique_id`s, by using `mac-address` where `ESP` string was used so far. It does not support setting any free text as the `unique_id`.

2021-11-13 14:53 UTC, oxan commented
I understand that, but changing the `unique_id` algorithm is a massive pain, so if we do that, I'd like to fix all issues with it at once instead of having to do it again later on. Both the old and your proposed new algorithm include user input in the form of the entity name in the unique_id through the `default_object_id`.

2021-11-13 15:05 UTC, kbialek commented
As far as I understood from the comments in the linked PR/issue, changing the existing `unique_id` generation is not an option. This means, that the problem you linked cannot be fully resolved. 
@oxan What the new generator should use instead of `default_object_id` in your opinion?

2021-11-13 15:15 UTC, oxan commented
I think a hex-encoded FNV-1 hash of the name would be fine, though maybe we should use a 64-bit or 128-bit hash instead.

2021-11-13 15:30 UTC, kbialek commented
I found `fnv1_hash` function in the codebase. Is that what you mean?

2021-11-13 15:36 UTC, oxan commented
Yes.

2021-11-13 17:02 UTC, kbialek commented
@oxan I've implemented the change. Now the `unique_id` looks like this `807d3a3c2190-switch-d3a92fe4` for example. Please review. The documentation is not yet updated.

2021-11-13 17:05 UTC, oxan requested changes

2021-11-13 17:05 UTC, oxan commented on esphome/components/mqtt/mqtt_component.cpp
> +            sprintf(object_id_hash, "%08x", fnv1_hash(this->get_default_object_id_()));
This doesn't work, as `get_default_object_id()` already strips non-Latin characters. We should hash the raw name instead:
```suggestion
            sprintf(object_id_hash, "%08x", fnv1_hash(this->friendly_name()));
```

2021-11-14 14:44 UTC, oxan approved these changes
LGTM, though I'd like a second opinion on whether we maybe should use a 64-bit or 128-bit hash instead.

2021-11-14 15:29 UTC, kbialek commented
Documentation PR updated https://github.com/esphome/esphome-docs/pull/1610/commits/1faf373c85fffc061d45146668847e0bd03544d0

2021-11-14 19:12 UTC, jesserockz approved these changes
> LGTM, though I'd like a second opinion on whether we maybe should use a 64-bit or 128-bit hash instead.

I don't think we need to go further with the hash. Just making it longer is not going to make it more unique.

2021-11-14 19:15 UTC, oxan commented
> Just making it longer is not going to make it more unique.

Why not? There's (usually) more than 32 bits of entropy in the names, so longer hashes should've less collisions.

2021-11-14 19:54 UTC, jesserockz commented
Yeah, I just mean in this case, do you really think you will get a clash of the `friendly_name` hash within a single ESP device?

I am not against changing it btw, just a thought.

2021-11-14 19:58 UTC, oxan commented
Yeah fair enough, that's probably quite unlikely.

2021-11-15 14:49 UTC, merged

2021-11-15 14:49 UTC, oxan commented
Thanks!