Add integration hydreon_rgxx
OttoWinter/esphomeyaml pull request #2711
Opened 2021-11-13 14:14 UTC by functionpointer

# What does this implement/fix? 

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1616

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:
  uart:
	  rx_pin: GPIO16
	  tx_pin: GPIO17
	  baud_rate: 9600

  # Example RG-9 entry
  sensor:
	  - platform: hydreon_rgxx
		  model: "RG_9"
		  update_interval: 1s
		  moisture:
			  name: "rain"
			  expire_after: 30s	

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-19 12:06 UTC, functionpointer commented
Any idea when this will be reviewed? The associated [docs pull request](https://github.com/esphome/esphome-docs/pull/1616) got flagged as stale.

Maybe @jesserockz could take a look?

2022-03-21 02:16 UTC, functionpointer commented
Once again the [associated docs pull request](https://github.com/esphome/esphome-docs/pull/1616) got flagged as stale.
I don't mean to sound impatient, but this PR is now four months old and hasn't received any feedback. Maybe @OttoWinter could take a look?

2022-04-03 20:30 UTC, jesserockz requested changes

2022-04-03 20:30 UTC, jesserockz commented on esphome/components/hydreon_rgxx/sensor.py
> +    .extend(cv.polling_component_schema("1s"))
Please default this to 60s.
```suggestion
    .extend(cv.polling_component_schema("60s"))
```

2022-04-03 21:38 UTC, functionpointer commented on esphome/components/hydreon_rgxx/sensor.py
> +    .extend(cv.polling_component_schema("1s"))
Oh right!

2022-04-03 21:52 UTC, jesserockz commented on esphome/components/hydreon_rgxx/binary_sensor.py
> +        ),
```suggestion
        cv.Optional(CONF_TOO_COLD): binary_sensor.binary_sensor_schema(
            device_class=DEVICE_CLASS_COLD
        ),
```

2022-04-03 22:58 UTC, jesserockz requested changes
I just realised that you need to wrap every piece of binary_sensor code in this otherwise someone who has no binary sensors, but does have the sensors will not be able to compile.

```c++
#ifdef USE_BINARY_SENSOR
...
#endif
```

Also add this include to `hydreon_rgxx.h`
```c++
#include "esphome/core/defines.h"
```

2022-04-11 02:50 UTC, jesserockz approved these changes

2022-04-11 02:50 UTC, merged