Ignore secrets yaml on command line
OttoWinter/esphomeyaml pull request #2715
Opened 2021-11-13 18:27 UTC by cvwillegen

# What does this implement/fix? 

When ``esphome`` is run from the CLI to update a subset of the configuration files, or all of them, the ``secrets.yaml`` file - when specified - yields an error. This makes it hard to do, for instance, ``esphome upload *yaml``. This code makes sure to skip the files ``secrets.yaml`` and ``secrets.yml`` when specified on the command line.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-14 14:09 UTC, oxan requested changes

2021-11-14 14:09 UTC, oxan commented on esphome/__main__.py
> +            ):
This check is too lenient, we only want to exclude the literal filename `secrets.yaml`, not any path that contains that.

2021-11-14 14:09 UTC, oxan commented on esphome/__main__.py
> +                )
This is not very descriptive, might be nice to add a note why this file is being skipped.

2021-11-14 14:09 UTC, oxan commented on esphome/__main__.py
> +
It's probably easier to do this in the for loop below, something like this:
```python
    for conf_path in args.configuration:
      if any(basename(conf_path) is x for x in CONF_SECRETS):
        _LOGGER.warning("skipping secrets file")
        continue
```
This also has the advantage that the `hasattr(args, "configuration")` is not necessary.

2021-11-14 14:09 UTC, oxan commented on esphome/const.py
> +CONF_SECRETS = ["secrets.yaml", "secrets.yml"]
This shouldn't be a `CONF_` constant, as those are for keys in the configuration YAML.

2021-11-14 20:11 UTC, cvwillegen commented on esphome/__main__.py
> +            ):
Used your example code to skip files, thanks!

2021-11-15 14:41 UTC, oxan approved these changes

2021-11-15 14:41 UTC, oxan commented
@jesserockz I think this is a good idea for usability, but it's technically a breaking change as you can no longer have a config named `secrets.yaml`. I don't think that's much of a problem, but thoughts?

2021-11-15 18:04 UTC, jesserockz approved these changes
That's fine. I would not expect people to have that anyway.

2021-11-15 19:06 UTC, merged

2021-11-15 19:07 UTC, oxan commented
Thank you for your contribution!

2021-11-15 19:45 UTC, cvwillegen commented
This has been an itch to scratch, but you're welcome! My second addition to esphome, both personal itches, but probably useful in the wild!