add retry handler
OttoWinter/esphomeyaml pull request #2721
Opened 2021-11-14 20:04 UTC by martgras

# What does this implement/fix? 

adds a retry handler to Component similiar to set_timeout and set_interval.   Retrying a operation from a component without using `delay()` is currently quite tedious. This function makes retries easier and allows exponential backoff

**Signature**:
`  void set_retry(uint32_t inital_wait_time, uint8_t max_retries, std::function<RetryResult()> &&f,
                 float backoff_increase_factor = 2.0f); `

`inital_wait_time` is the delay for the first retry. 
`max_retries` how often to retry 
`f` the function to retry.   If `f` returns `RETRY`  then it will be called again. `DONE` stops the retries
`backoff_increase_factor` defines how the time between the retries changes (initial_wait_time is multiplied with it) 

To make testing a bit easier and allow using the function from yaml I  made set_timeout,set_interval and set_retry public members of `esphome::Component`  - actually I don't see a reason why they should be protected. 

The existing implementation for Scheduler::SchedulerItem uses `std::function<void>()` for the callbacks. 
To avoid breaking exiting code set_retry wraps the `std::function<RetryResult>()` callback in a void function. 
Not sure if there is an easier approach here.  All 'more elegant' version I tested crashed :)

Feedback about different function signatures or any improvement is welcome :) 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
substitutions:
  devicename: retry-test
esphome:
  name: ${devicename}
  on_boot:
    ## configure controller settings at setup
    ## make sure priority is lower than setup_priority of modbus_controller
    priority: -100
    then:
      - lambda: |-
          auto sensor = id(dummy);
          // retry 10 times and increase the interval by 2.5 for each iteration 
          sensor->set_retry(500,10, []() {
            static auto last = millis();
            static int counter = 1 ; 
            ESP_LOGI("RETRY DEMO", "RETRY Count=%u last invocation = %u ms",counter++, millis()-last);
            last = millis();
            if (counter < 6)
              return RETRY;
            else {
              ESP_LOGI("RETRY DEMO","retry stopped by lambda");
              return DONE;
            }
          },2.5f);
esp32:
  board: esp32dev
  framework:
    type: arduino
logger:
  level: VERY_VERBOSE
sensor:
  - platform: template
    id: dummy
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-14 21:01 UTC, jesserockz requested changes
`inital_wait_time` needs to have spelling fixed everywhere to `initial_wait_time`.

2021-11-14 21:01 UTC, jesserockz commented on esphome/core/component.h
> +   * f should return RetryResult::DONE if no repeat is required. The inial wait time will be increased
```suggestion
   * f should return RetryResult::DONE if no repeat is required. The initial wait time will be increased
```

2021-11-14 21:01 UTC, jesserockz commented on esphome/core/component.h
> +   * @return Whether an retry functions was deleted.
```suggestion
   * @return Whether a retry function was deleted.
```

2021-11-14 21:01 UTC, jesserockz commented on esphome/core/component.h
> +   * loop() and therefore can be significantly delay.
```suggestion
   * loop() and therefore can be significantly delayed.
```

2021-11-14 21:01 UTC, jesserockz commented on esphome/core/component.h
> +
Can you explain why the set/cancel methods above should be public instead of protected? I don't think there would be any cases when you would need to set one of these from outside the component itself.

2021-11-14 21:07 UTC, martgras commented on esphome/core/component.h
> +
The idea was to be able to use it from a lambda as in my example. Probably not a strong use case . I can move it back to protected

2021-11-14 21:17 UTC, jesserockz commented on esphome/core/component.h
> +
Would be better to keep as is. It's only for developing components anyway.

2021-11-14 21:43 UTC, martgras commented on esphome/core/component.h
> +
done

2021-11-14 21:46 UTC, jesserockz approved these changes

2021-11-15 14:09 UTC, oxan requested changes

2021-11-15 14:09 UTC, oxan commented on esphome/core/scheduler.cpp
> +    this->cancel_interval(component, name);
```suggestion
    this->cancel_retry(component, name);
```

2021-11-15 14:09 UTC, oxan commented on esphome/core/scheduler.cpp
> +    offset = (random_uint32() % initial_wait_time) / 2;
This randomization of the first run (used to avoid having all intervals run at the same time) doesn't make any sense for retries, imo.

2021-11-15 14:09 UTC, oxan commented on esphome/core/scheduler.cpp
> +          *type_ptr = "interval";
Why are you using an indirection to write to `type`?

This whole block probably should also be a helper function instead of duplicated.

2021-11-15 14:09 UTC, oxan commented on esphome/core/scheduler.cpp
> +        if (item->type == SchedulerItem::RETRY)
```suggestion
      } else if (item->type == SchedulerItem::RETRY) {
```
(+ indent fix)

2021-11-15 14:09 UTC, oxan commented on esphome/core/scheduler.cpp
> +                item->last_execution_major++;
This duplicates a lot of code from the case for `INTERVAL`, those cases can be merged.

2021-11-15 14:09 UTC, oxan commented on esphome/core/scheduler.h
> +    RetryResult retry_result{};
I'm not too fond of this whole wrapper stuff. I think a better approach is:
* Make `f` a union between `std::function<void()>` and `std::function<RetryResult()>`, and drop both `retry_result` and `retry_wrapper` from this struct (to reduce memory overhead of this feature for timeouts/intervals).
* Make the call to `f` conditional and store the result in a local variable, and check that flag before requeuing the retry.

2021-11-15 14:09 UTC, oxan commented on esphome/core/component.cpp
> +  return App.scheduler.cancel_interval(this, name);
```suggestion
  return App.scheduler.cancel_retry(this, name);
```

2021-11-15 15:43 UTC, martgras commented on esphome/core/scheduler.cpp
> +    offset = (random_uint32() % initial_wait_time) / 2;
removed

2021-11-15 19:14 UTC, oxan requested changes

2021-11-15 19:14 UTC, oxan commented on esphome/core/scheduler.cpp
> +              item->next_execution(), item->next_execution_major());
Something went wrong here, I don't think this loop should be removed and all the indenting and function boundaries for the rest of the file are all messed up now.

2021-11-15 19:39 UTC, martgras commented on esphome/core/scheduler.cpp
> +              item->next_execution(), item->next_execution_major());
fixed

2021-11-16 12:55 UTC, oxan requested changes

2021-11-16 12:55 UTC, oxan commented on esphome/core/scheduler.cpp
>        // Warning: During f(), a lot of stuff can happen, including:
```suggestion
      // Warning: During the callback, a lot of stuff can happen, including:
```

2021-11-16 12:55 UTC, oxan commented on esphome/core/scheduler.cpp
> +        }
I think we don't need to duplicate the timing logic here:
```cpp
      if ((item->type == SchedulerItem::INTERVAL) ||
          (item->type == SchedulerItem::RETRY && retry_result != RetryResult::DONE && --item->retry_countdown > 0)) {
        if (item->interval != 0) {
          const uint32_t before = item->last_execution;
          const uint32_t amount = (now - item->last_execution) / item->interval;
          item->last_execution += amount * item->interval;
          if (item->last_execution < before)
            item->last_execution_major++;
        }
        if (item->type == SchedulerItem::RETRY)
          item->interval *= item->backoff_multiplier;
        this->push_(std::move(item));
      }
```

2021-11-16 12:55 UTC, oxan commented on esphome/core/scheduler.h
> +          return "INVALID TYPE!";
This is a waste of memory for a string that should never get used.
```suggestion
          return "";
```

2021-11-16 12:55 UTC, oxan commented on esphome/core/component.cpp
> +void Component::set_retry(const std::string &name, uint32_t initial_wait_time, uint8_t max_retries,
One last thing I'm thinking about, does it make sense to rename `max_retries` to `max_attempts`?

2021-11-16 12:57 UTC, oxan commented on esphome/core/scheduler.h
> +          return "INVALID TYPE!";
Actually, all users of this function are inside `#ifdef ESPHOME_DEBUG_SCHEDULER`, so we can wrap this function inside that condition as well.

2021-11-16 13:58 UTC, martgras commented on esphome/core/scheduler.cpp
>        // Warning: During f(), a lot of stuff can happen, including:
done

2021-11-16 14:28 UTC, oxan commented on esphome/core/scheduler.cpp
> +        }
Any particular reason you split out the result checking to after the timing math? Now the timing calculation is executed even if the retry is done and the result is discarded. It's a bit nitpicky, but this is some of the hottest code we have.

2021-11-16 14:40 UTC, martgras commented on esphome/core/scheduler.cpp
> +        }
no special reason - changed it

2021-11-16 14:53 UTC, oxan commented on esphome/core/scheduler.cpp
> +      this->push_(std::move(item));
This should be moved back into the previous `if`, as now every timeout behaves like an interval as well, and retries go on forever.

2021-11-16 15:08 UTC, oxan approved these changes

2021-11-17 22:59 UTC, merged