Add number/tuya support.
OttoWinter/esphomeyaml pull request #2765
Opened 2021-11-18 23:26 UTC by frankiboy1

# What does this implement/fix? 

This PR adds support for Tuya Number. Tuya devices have currently only support for binary_sensor, climate, cover, fan, light, sensor and switch. Without number support, it's not possible to support generic devices without trying to map them into one of the existing types. With number support, it should be possible to support any tuya device using the generic types binary_sensor, sensor, switch and number.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
  - platform: "tuya"
    name: "MyNumber"
    number_datapoint: 102
    min_value: 0
    max_value: 17
    step: 1
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-19 08:15 UTC, oxan commented
See also #2311.

2021-11-19 08:38 UTC, frankiboy1 commented
> See also #2311.

I wasn't aware of this PR. I had a quick look at that PR and it's mostly doing the same as mine. My version supports both integer and enum datapoints, which should be a requirement.

2021-11-19 08:42 UTC, frankiboy1 commented
This PR should close this feature request:

https://github.com/esphome/feature-requests/issues/1328

Not sure how to link the feature request to the pull request, or if this happens automatically due to this mention.

2021-12-16 19:51 UTC, frankiboy1 commented
Not sure what happened here. I tried to rebase my changes and somehow it ended up as part of the PR. I'll try to clean up after me..

2021-12-16 20:19 UTC, frankiboy1 commented
I have reverted the rebase I recently made, so I think everything should be correct now. I can see that some labels were not removed, and some assignees/reviewers are still on the list. Sorry for screwing this up! ;(

2021-12-19 19:52 UTC, jesserockz requested changes
Just one thing

2021-12-19 19:52 UTC, jesserockz commented on esphome/components/tuya/number/__init__.py
> +    return config
You are not using this validation

2021-12-19 20:24 UTC, frankiboy1 commented on esphome/components/tuya/number/__init__.py
> +    return config
Should be fixed with the new commit.

2021-12-20 01:34 UTC, jesserockz approved these changes

2021-12-20 01:35 UTC, merged