Draft: MLX90393
OttoWinter/esphomeyaml pull request #2770
Opened 2021-11-19 23:33 UTC by functionpointer

# What does this implement/fix? 

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: mlx90393
    oversampling: 1
    filter: 0
    gain: "3X"
    x-axis:
      name: "mlxxaxis"
    y-axis:
      name: "mlxyaxis"
    z-axis:
      name: "mlxzaxis"
    temperature:
      name: "mlxtemp"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-10 11:39 UTC, jesserockz requested changes

2022-01-10 11:39 UTC, jesserockz commented on esphome/components/mlx90393/sensor.py
> +            cv.Optional(CONF_TEMPERATURE): sensor.sensor_schema(
The temperature sensor is not used in codegen, and not published to in c++?

2022-01-10 11:39 UTC, jesserockz commented on esphome/components/mlx90393/sensor.py
> +            ),
Since the 3 axis are the same, can you extract this schema value into a variable and just reuse it for all 3 to stop code repetition?

Edit: I actually see Z have 16bit instead of 19Bit, you could make a validator generator function that takes the resolution as an arg and makes the config validation from that.

2022-01-10 11:39 UTC, jesserockz commented on esphome/components/mlx90393/sensor.py
> +    .extend(cv.polling_component_schema("1s"))
Any reason for the 1s update time? Generally we try to make them 60s and the user can make it faster if they want.

2022-01-10 11:39 UTC, jesserockz commented on esphome/components/mlx90393/sensor_mlx90393.cpp
> +                             size_t response_size) {                                          // NOLINT
What are you `NOLINT`ing here?

2022-01-10 17:11 UTC, functionpointer commented on esphome/components/mlx90393/sensor_mlx90393.cpp
> +                             size_t response_size) {                                          // NOLINT
The linter was complaining for no good reason here, so i added `NOLINT`. Apparently it doesnt anymore so i removed it again.

2022-01-10 17:13 UTC, functionpointer commented on esphome/components/mlx90393/sensor.py
> +            cv.Optional(CONF_TEMPERATURE): sensor.sensor_schema(
Damn i totally forgot that! I have now added and tested it.

2022-01-16 06:51 UTC, jesserockz requested changes

2022-01-16 06:51 UTC, jesserockz commented on esphome/components/mlx90393/sensor.py
> +        cg.add(var.set_filter(config[CONF_FILTER]))
Conditionals not needed as you have defaults in the schema
```suggestion
    cg.add(var.set_gain(GAIN[config[CONF_GAIN]]))
    cg.add(var.set_oversampling(config[CONF_OVERSAMPLING]))
    cg.add(var.set_filter(config[CONF_FILTER]))
```

2022-01-16 06:51 UTC, jesserockz commented on esphome/components/mlx90393/sensor_mlx90393.h
> +  uint8_t filter_ = 0;
Same as above, defaults will always be set from codegen so no need to set to 0 (except for osr2_).
```suggestion
  uint8_t gain_;
  uint8_t osr_;
  uint8_t osr2_ = 0;
  uint8_t filter_;
```

2022-01-16 06:51 UTC, jesserockz commented on esphome/components/mlx90393/sensor_mlx90393.h
> +  uint8_t osr2_ = 0;
Also maybe rename the osr2 to make it clear it is for temperature?

2022-01-17 11:53 UTC, functionpointer commented
Should i make a `1.0.0` release for the library `functionpointer/arduino-MLX90393` ?

2022-01-17 20:04 UTC, jesserockz commented
> Should i make a `1.0.0` release for the library `functionpointer/arduino-MLX90393` ?

Up to you =)

2022-02-04 22:09 UTC, functionpointer commented
Merge conflict solved.

2022-02-08 04:32 UTC, jesserockz requested changes

2022-02-08 04:32 UTC, jesserockz commented on esphome/components/mlx90393/sensor.py
> +    cg.add_library("functionpointer/arduino-MLX90393", "^1.0.0")
```suggestion
    cg.add_library("functionpointer/arduino-MLX90393", "1.0.0")
```

2022-02-08 07:39 UTC, jesserockz approved these changes

2022-02-08 07:42 UTC, merged