Fix distorted gif frames when resizing
OttoWinter/esphomeyaml pull request #2774
Opened 2021-11-20 11:08 UTC by davet2001

# What does this implement/fix? 
Further to #2750, when scaling animaged gif images using the `resize` config, anything after the first frame seemed to be corrupted, with a distorted image.

This seemed to be caused by the `image.thumbnail()`, which appeared to damage the 2nd and following frames in the pillow image object.

The proposed solution is to use the `thumbnail()` function on a copy to get the size, then call `resize()` on each frame just before saving it to the buffer.  This works reliably for me on `RGB24`, `BINARY`, `GRAYSCALE` image types.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** relates to #2750 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-20 12:33 UTC, Syndlex requested changes

2021-11-20 12:33 UTC, Syndlex commented on esphome/components/animation/__init__.py
> +        image_copy.thumbnail(config[CONF_RESIZE])
I think using `transform` would yield in a more permanent solution.
But i am not sure how the image will be processed. 
@davet2001 can you please test how it is behaving? 

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.transform

2021-11-20 12:33 UTC, Syndlex commented on esphome/components/animation/__init__.py
> +                    f"Unexpected number of pixels in frame {frameIndex}: ({len(pixels)} != {height*width}"
can you add the gif name here. When working with multiple gifs it will be a nightmare to get what gif is broken.

2021-11-20 12:33 UTC, Syndlex commented on esphome/components/animation/__init__.py
> +                    f"Unexpected number of pixels in frame {frameIndex}: ({len(pixels)} != {height*width}"
can you add the gif name here. When working with multiple gifs it will be a nightmare to get what gif is broken.

2021-11-20 12:39 UTC, davet2001 commented on esphome/components/animation/__init__.py
> +                    f"Unexpected number of pixels in frame {frameIndex}: ({len(pixels)} != {height*width}"
Done.

2021-11-20 12:39 UTC, davet2001 commented on esphome/components/animation/__init__.py
> +                    f"Unexpected number of pixels in frame {frameIndex}: ({len(pixels)} != {height*width}"
Done.

2021-11-20 12:49 UTC, davet2001 commented on esphome/components/animation/__init__.py
> +        image_copy.thumbnail(config[CONF_RESIZE])
@Syndlex `transform()` seems to be doing more complicated things than just resize.  I don't see how it is a more permanent solution.  I can test it if you like, but what 'mode' should be used?

2021-11-20 16:38 UTC, davet2001 commented on esphome/components/animation/__init__.py
> +                    f"Unexpected number of pixels in frame {frameIndex}: ({len(pixels)} != {height*width}"
I should add, it's not a fault with the gif that would cause this. More like the resize code not working as expected.

2021-11-20 21:58 UTC, davet2001 commented on esphome/components/animation/__init__.py
> +        image_copy.thumbnail(config[CONF_RESIZE])
I have now updated with a `resize()` and some extra lines that preserve the aspect ratio.  I have tested this and it works ok.

2021-11-21 20:44 UTC, oxan approved these changes
LGTM.

2021-11-23 08:20 UTC, merged