Add Sonoff D1 Dimmer support
OttoWinter/esphomeyaml pull request #2775
Opened 2021-11-20 15:25 UTC by anatoly-savchenkov

# What does this implement/fix? 

Adds standard Light component for Sonoff D1 Dimmer.
Docs still to be be added.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** implements https://github.com/esphome/feature-requests/issues/611

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esp8266:
  board: esp01_1m
  restore_from_flash: true

uart:
    tx_pin: TX
    rx_pin: RX
    baud_rate: 9600

light:
  - platform: sonoff_d1
    use_rm433_remote: False
    name: Sonoff D1 Dimmer
    id: dim_light
    restore_mode: RESTORE_DEFAULT_OFF
    gamma_correct: 0.0
    default_transition_length: 1s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-17 22:34 UTC, dbrand666 commented
👍 seems to work around both the ghost switching and also the instability at extreme dim/bright levels.

2022-02-17 20:21 UTC, jesserockz requested changes

2022-02-17 20:21 UTC, jesserockz commented on esphome/components/sonoff_d1/sonoff_d1.cpp
> +bool SonoffD1Output::control_dimmer_(const bool binary, const int brightness) {
The brightness does not need to be an `int` when it is only 0-100. Please change in other places too.
```suggestion
bool SonoffD1Output::control_dimmer_(const bool binary, const uint8_t brightness) {
```

2022-02-17 20:21 UTC, jesserockz commented on esphome/components/sonoff_d1/sonoff_d1.cpp
> +  for (unsigned int i = 0; i < len; i++) {
The type should match the max value you are comparing to.
```suggestion
  for (size_t i = 0; i < len; i++) {
```

2022-02-17 20:21 UTC, jesserockz commented on esphome/components/sonoff_d1/sonoff_d1.cpp
> +  unsigned int garbage = 0;
```suggestion
  size_t garbage = 0;
```
or
```suggestion
  uint32_t garbage = 0;
```

2022-02-17 20:21 UTC, jesserockz commented on esphome/components/sonoff_d1/sonoff_d1.cpp
> +  unsigned int pos = 0, buf_len = sizeof(ref_buffer);
```suggestion
  uint32_t pos = 0, buf_len = sizeof(ref_buffer);
```

2022-02-17 20:21 UTC, jesserockz commented on esphome/components/sonoff_d1/sonoff_d1.cpp
> +  const int calculated_brightness = std::round(brightness * 100);
```suggestion
  const uint8_t calculated_brightness = std::round(brightness * 100);
```

2022-02-17 20:21 UTC, jesserockz commented on esphome/components/sonoff_d1/light.py
> +        cg.add(var.set_max_value(config[CONF_MAX_VALUE]))
Defaults in schema mean no need to conditionally check
```suggestion
    cg.add(var.set_use_rm433_remote(config[CONF_USE_RM433_REMOTE]))
    cg.add(var.set_min_value(config[CONF_MIN_VALUE]))
    cg.add(var.set_max_value(config[CONF_MAX_VALUE]))
```

2022-04-12 04:45 UTC, jesserockz requested changes

2022-04-12 04:45 UTC, jesserockz commented on esphome/components/sonoff_d1/sonoff_d1.cpp
> +
Not needed
```suggestion
```

2022-04-12 04:45 UTC, jesserockz commented on esphome/components/sonoff_d1/sonoff_d1.cpp
> +  cmd[7] = this->remap_(brightness, 0, 100, this->min_value_, this->max_value_);
This exists in `esphome/core/helpers.h` (It might not have when you created this code though)
```suggestion
  cmd[7] = remap(brightness, 0, 100, this->min_value_, this->max_value_);
```

2022-04-12 04:45 UTC, jesserockz commented on esphome/components/sonoff_d1/sonoff_d1.cpp
> +    const uint8_t new_brightness = this->remap_(cmd[7], this->min_value_, this->max_value_, 0, 100);
```suggestion
    const uint8_t new_brightness = remap(cmd[7], this->min_value_, this->max_value_, 0, 100);
```

2022-04-12 04:45 UTC, jesserockz commented on esphome/components/sonoff_d1/sonoff_d1.h
> +  int remap_(int value, int min, int max, int min_out, int max_out);
```suggestion
```

2022-04-12 04:50 UTC, jesserockz commented on esphome/components/sonoff_d1/sonoff_d1.cpp
> +  cmd[7] = remap(brightness, 0, 100, this->min_value_, this->max_value_);
```suggestion
  cmd[7] = remap<uint8_t, uint8_t>(brightness, 0, 100, this->min_value_, this->max_value_);
```

2022-04-12 04:50 UTC, jesserockz commented on esphome/components/sonoff_d1/sonoff_d1.cpp
> +    const uint8_t new_brightness = remap(cmd[7], this->min_value_, this->max_value_, 0, 100);
```suggestion
    const uint8_t new_brightness = remap<uint8_t, uint8_t>(cmd[7], this->min_value_, this->max_value_, 0, 100);
```

2022-04-12 04:59 UTC, jesserockz approved these changes

2022-04-12 05:03 UTC, merged

2022-04-12 05:09 UTC, anatoly-savchenkov commented on esphome/components/sonoff_d1/sonoff_d1.cpp
> +  cmd[7] = this->remap_(brightness, 0, 100, this->min_value_, this->max_value_);
I cannot check this change now (travelling) but I suspect the first multiplicaion will cause integer overflow inside esphome/core/helpers.h as it will be done in uint8_t.