INA260 Current and Power Sensor support
OttoWinter/esphomeyaml pull request #2788
Opened 2021-11-23 14:46 UTC by MrEditor97

# What does this implement/fix? 

Adding of INA260 Current and Power sensor support to ESP Home.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1649

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
i2c:
  sda: 21
  scl: 22
  scan: true

sensor:
  - platform: ina260
    address: 0x40
    current:
      name: "INA260 Current"
    power:
      name: "INA260 Power"
    bus_voltage:
      name: "INA260 Voltage"
    max_current: 15A
    update_interval: 60s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-24 23:51 UTC, jesserockz requested changes

2021-11-24 23:51 UTC, jesserockz commented on esphome/components/ina260/ina260.cpp
> +};
Can you move these to `static const uint8_t` please?

2021-11-24 23:51 UTC, jesserockz commented on esphome/components/ina260/ina260.cpp
> +  delay(2);  // NOLINT
Don't need to unnecessarily bypass lint here.

```suggestion
  delay(2);
```

2021-11-24 23:51 UTC, jesserockz commented on esphome/components/ina260/ina260.cpp
> +  config |= 0b0000000000000111;
If this is not configurable, you should just make it a const to save memory on the variable.

2021-11-24 23:51 UTC, jesserockz commented on esphome/components/ina260/ina260.h
> +  float max_current_amp_{15};
Not used anywhere?

2021-11-24 23:51 UTC, jesserockz commented on esphome/components/ina260/sensor.py
> +            ),
Not used?

2021-11-24 23:51 UTC, jesserockz commented on esphome/components/ina260/ina260.cpp
> +    this->current_sensor_->publish_state(current_ma);
Is this mA or A? You have Amps in the python config and mA here...

2021-11-24 23:51 UTC, jesserockz commented on esphome/components/ina260/ina260.cpp
> +    this->power_sensor_->publish_state(power_mw);
Is this mW or W? You have Watts in the python config and mW here...

2021-11-25 14:52 UTC, MrEditor97 commented on esphome/components/ina260/ina260.cpp
> +};
I have changed them over to `static const uint8_t`.
However, can I ask your reasoning for this change? Any knowledge you have would be greatly appreciated. Thanks 👍

2021-11-25 15:01 UTC, MrEditor97 commented on esphome/components/ina260/ina260.cpp
> +  config |= 0b0000000000000111;
Sorted this, merged all values into one and placed it directly where the config parameter was being used (It is only used once).

2021-12-03 22:36 UTC, MrEditor97 commented
Accidentally closed the pull request, so managed to reopen it. Will update it again now it has failed the checks.

2021-12-30 11:37 UTC, MrEditor97 commented
Is there something else that I need to change on this for it to be implemented?

2021-12-31 08:58 UTC, jesserockz commented on esphome/components/ina260/ina260.cpp
> +};
Consistency with the rest of the codebase =)

2021-12-31 09:04 UTC, jesserockz approved these changes
LGTM, thanks for making the changes and sorry it took so long to get back to it.

2021-12-31 09:08 UTC, merged