ESP32 Deep Sleep: correct level value
OttoWinter/esphomeyaml pull request #2812
Opened 2021-11-27 12:59 UTC by jhamhader

Upon registering for ESP32 deep sleep, DeepSleepComponent::begin_sleep
calculates the level value to wake up on.
As part of PR #2303, the level was changed to be based on `inverted`
instead of `!inverted`:
Before:
https://github.com/esphome/esphome/blob/1e8e471dec19ceafba1997b1d9663f7912f244a2/esphome/components/deep_sleep/deep_sleep_component.cpp#L76
After:
https://github.com/esphome/esphome/blob/2b04152482da3e9faaa4f6d0fd3370134d792fd1/esphome/components/deep_sleep/deep_sleep_component.cpp#L80

The level argument to `esp_sleep_enable_ext0_wakeup(pin, level)` [0]
should be 0 when the inverted property is true (low triggers wakeup),
and 1 when inverted property is false (high triggers wakeup).

[0]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#_CPPv428esp_sleep_enable_ext0_wakeup10gpio_num_ti

# What does this implement/fix? 

Inverted property of deep sleep is wrong (true means high wakes up, while expected low to take up).

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-11-29 15:49 UTC, oxan requested changes
I think this breaks the `INVERT_WAKEUP` mode for `wakeup_pin_mode`. If the pin is inverted and low, and that option is set, then it should wake up for a high signal, but now it'll configure a wakeup on the low signal (which will happen immediately). So the `digital_read()` in the next line needs to be flipped as well. That's also consistent with how the code was pre-#2303.

2021-11-29 19:11 UTC, jhamhader commented
Done. I suspect `INVERT_WAKEUP` might still have issues. After this PR, will try to test and send a fix if required.

2021-11-30 14:28 UTC, oxan approved these changes

2021-12-01 07:20 UTC, jhamhader commented
Thanks for the review. I don't have permissions to merge.

2021-12-01 08:38 UTC, merged