New Midea IR component, improvements and fixes
OttoWinter/esphomeyaml pull request #2847
Opened 2021-12-01 19:36 UTC by dudanov

# What does this implement/fix? 

1. New component ``midea_ir`` based on the ``ClimateIR`` class.
2. Added support for presets in the ``ClimateIR`` class.
3. The Coolix protocol is separated from the ``coolix`` component in the ``remote_base``.
4. Processing of received IR packets in the ``coolix`` component is made static for use in other components that support the Coolix protocol such as ``midea_ir``.
5. Added functions ``float celsius_to_fahrenheit(float)`` and ``float fahrenheit_to_celsius(float)``  for converting between Celsius and Fahrenheit in ``core/helpers.h``.
6. Some minor changes and fixes.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
climate:
  - platform: midea_ir
    name: AC01
    id: my_climate
    receiver_id:
    use_fahrenheits: true

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-06 07:25 UTC, dudanov commented
@jesserockz @OttoWinter @oxan Please see and review this PR.

2021-12-12 22:33 UTC, jesserockz requested changes

2021-12-12 22:33 UTC, jesserockz commented on esphome/components/midea_ir/climate.py
> +        cg.add(var.set_fahrenheit(config[CONF_USE_FAHRENHEITS]))
You have a default, so the key is always present
```suggestion
    cg.add(var.set_fahrenheit(config[CONF_USE_FAHRENHEIT]))
```

2021-12-12 22:33 UTC, jesserockz commented on esphome/components/midea_ir/climate.py
> +)
```suggestion
CONF_USE_FAHRENHEIT = "use_fahrenheit"

CONFIG_SCHEMA = climate_ir.CLIMATE_IR_WITH_RECEIVER_SCHEMA.extend(
    {
        cv.GenerateID(): cv.declare_id(MideaIR),
        cv.Optional(CONF_USE_FAHRENHEIT, default=False): cv.boolean,
    }
)
```

2021-12-12 22:33 UTC, jesserockz commented on tests/test1.yaml
> +    use_fahrenheits: True
```suggestion
    use_fahrenheit: true
```

2021-12-12 22:33 UTC, jesserockz commented on esphome/core/helpers.h
> +static inline float fahrenheit_to_celsius(float value) { return (value - 32.0f) * 0.555555582f; }
Why not make this just the opposite of above?
```suggestion
static inline float fahrenheit_to_celsius(float value) { return (value - 32.0f) / 1.8f; }
```

2021-12-13 06:38 UTC, dudanov commented on esphome/core/helpers.h
> +static inline float fahrenheit_to_celsius(float value) { return (value - 32.0f) * 0.555555582f; }
Ok, I agree. Maybe I shouldn't trust the compiler that I myself replace the division operation with a less expensive multiplication. :smile:

2021-12-19 19:43 UTC, jesserockz approved these changes

2022-01-09 22:47 UTC, merged

2022-01-09 22:58 UTC, oxan commented on esphome/core/helpers.h
> +static inline float fahrenheit_to_celsius(float value) { return (value - 32.0f) / 1.8f; }
FYI, `static inline` is pointless, as `static` gives the function internal linkage (i.e. it is not visible from outside the current translation unit), while `inline` only has effect on functions with external linkage. `constexpr` is probably best here.

2022-01-10 03:08 UTC, dudanov commented on esphome/core/helpers.h
> +static inline float fahrenheit_to_celsius(float value) { return (value - 32.0f) / 1.8f; }
The ''inline'' directive is just a tip for the compiler and is optional.  ''static'', on the other hand, indicates specifically that this function should be internal in a given translation unit. Since this header file is used in the compilation of many source files, the ''static'' keyword is by no means redundant.  ''constexpr'' will only work for static data that is known at compile time and will fail when using dynamic data. In the case of ''static inline'', the compiler will, if possible, perform calculation and optimization at compile time using literals or other data known at compile time, ''constexpr'' just is a guarantee for the programmer that this should be the case.

2022-01-10 08:29 UTC, oxan commented on esphome/core/helpers.h
> +static inline float fahrenheit_to_celsius(float value) { return (value - 32.0f) / 1.8f; }
> The `inline` directive is just a tip for the compiler and is optional

That's the case in C, but in C++ the `inline` specifier means that a function may have more than one definition in the program (usually coming from different translation units), and the linker should keep one and discard the others, instead of throwing an error. Compilers _may_ use it as an hint to inline the function, but that's because they have total freedom to implement as-if optimizations, and they may inline functions that aren't marked `inline` as well (iirc clang does raise the inlining cost threshold when `inline` is applied, but gcc does not).

This is also why `static inline` makes no sense: they're both different ways around the one definition rule. `static` marks the function as internal to a translation unit, while `inline` allows multiple definitions, but that will never happen because the function is marked `static`.

> `constexpr` will only work for static data that is known at compile time and will fail when using dynamic data.

That's true for variables, but for functions it means that a function _can_ be evaluated at compile time if the arguments are known at compile time, but it doesn't require _all_ invocations of the function to be compile-time evaluated. It can also be used at runtime with non-constant arguments. `constexpr` implies `inline` to allow you to have multiple definitions of a `constexpr` function.

2022-01-10 10:47 UTC, dudanov commented on esphome/core/helpers.h
> +static inline float fahrenheit_to_celsius(float value) { return (value - 32.0f) / 1.8f; }
I have just read articles on these topics.
There is no fundamental difference between these ads, but there are nuances. And yet the universal way is to declare it as ``static inline``. This gives the compiler the freedom to discard unused inline functions from the object code of each translation unit, since functions are not exported. Yes indeed it is allowed that the exported inline function is duplicated in different object files. But why do you need duplicate code? After all, it turns out how many translation objects we have, the same number of duplicates of the code of these inline functions in them. Above, I said about the advantage in this case of the ``static`` keyword.
For ``constexpr`` functions, I'd better insert the one requirement from the [cppreference.com](https://en.cppreference.com/w/cpp/language/constexpr) site: **each of its parameters must be a ``LiteralType``**, but our parameters are not only not necessary, but as a rule they are not literals, since they are used in functions with runtime variables.

I am not insisting on this, just using the ``static inline`` combination I tell the compiler clear instructions, helping it, and at the same time paying tribute to the traditional foundations of the C/C++ language. What is out of date in this?

2022-01-10 11:11 UTC, dudanov commented on esphome/core/helpers.h
> +static inline float fahrenheit_to_celsius(float value) { return (value - 32.0f) / 1.8f; }
Understood in more detail. Indeed, the ``constexpr`` specifier is more suitable. Since this is practically the same as ``static inline``, just more modern and shorter.

2022-01-10 12:39 UTC, oxan commented on esphome/core/helpers.h
> +static inline float fahrenheit_to_celsius(float value) { return (value - 32.0f) / 1.8f; }
> I am not insisting on this

Me neither, just wanted to inform you about it :) It's fine to leave it like this for now.