Different run duration for non-timer wakeup
OttoWinter/esphomeyaml pull request #2861
Opened 2021-12-04 16:26 UTC by jhamhader

In some cases, it useful to set different run durations according to
the wakeup cause, which can be found in ESP32.

For example, a sleep duration of 10 minutes to conserve power. When
waking because of timer, only run for 10 seconds. However, if waking up
due to touch or gpio, stay awake for longer (be available for action,
wait for OTA, etc.)

# What does this implement/fix? 

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** -

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** will be done later

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
deep_sleep:
  run_duration:
    default: 20s
    gpio: 10s
    touch: 15s
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-05 15:49 UTC, oxan requested changes
I like the idea, a few nits about the implementation though:

2021-12-05 15:49 UTC, oxan commented on esphome/components/deep_sleep/deep_sleep_component.cpp
> -  ESP_LOGCONFIG(TAG, "Setting up Deep Sleep...");
This breaks the convention of all components logging this setup message in the same style.

2021-12-05 15:49 UTC, oxan commented on esphome/components/deep_sleep/deep_sleep_component.cpp
> +  }
So to follow the convention, I'd suggest this: (+ restore the log message above, but GitHub doesn't allow suggestions on deletions :disappointed:)
```suggestion
  if (run_duration.has_value()) {
    ESP_LOGI(TAG, "Scheduling Deep Sleep to start in %u ms", *run_duration);
    this->set_timeout(*run_duration, [this]() { this->begin_sleep(); });
  } else {
    ESP_LOGD(TAG, "Not scheduling Deep Sleep, as no run duration is configured");
  }
```
(I also lowered the priority in the `else`-branch, as it's perfectly fine to not schedule a run duration).

2021-12-05 15:49 UTC, oxan commented on esphome/components/deep_sleep/deep_sleep_component.cpp
> +#ifdef USEESP32
```suggestion
#ifdef USE_ESP32
  if (wakeup_pin_ != nullptr)
    LOG_PIN("  Wakeup Pin: ", this->wakeup_pin_);
```
No reason to drop the logging of the wakeup pin.

2021-12-06 17:53 UTC, jhamhader commented
Fixed.
Also rename 'gpio' and 'touch' to 'gpio_wakeup_reason' and 'touch_wakeup_reason'.

Will test on a device and send a documentation update soon.

2021-12-06 18:41 UTC, jesserockz approved these changes
Looks good to me, just needs docs

2021-12-06 18:48 UTC, oxan approved these changes

2021-12-06 20:16 UTC, jhamhader commented
Tested locally, sent docs PR in esphome/esphome-docs#1705

2021-12-06 22:30 UTC, merged