Add new component - Emporia Vue
OttoWinter/esphomeyaml pull request #2871
Opened 2021-12-06 01:32 UTC by Maelstrom96

# What does this implement/fix? 

Add support for the Emporia Vue 2.

The documentation is not quite ready yet, but we're pushing this out early so we can get some feedback on the code and implement changes if needed.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz
  id: i2c_a
  
sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a
        input: BLACK
        voltage: 
          name: "Phase A Voltage"
      - id: phase_c
        input: RED
        voltage: 
          name: "Phase C Voltage"
    ct_clamps:
      - name: "A"
        phase_id: phase_a
        input: "A"
      - name: "C"
        phase_id: phase_c
        input: "C"
      - name: "1"
        phase_id: phase_a
        input: "1"
      - name: "2"
        phase_id: phase_a
        input: "2"
      - name: "3"
        phase_id: phase_a
        input: "3"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-06 01:42 UTC, Maelstrom96 commented
Not sure why the checks are failing, it seems to be code out of this PR scope.

2021-12-06 08:17 UTC, oxan commented
The CI failure is caused by this error:
```
Error: /home/runner/work/esphome/esphome/esphome/components/emporia_vue/emporia_vue.h:14:10: error: 'freertos/FreeRTOS.h' file not found [clang-diagnostic-error]
#include <freertos/FreeRTOS.h>
```

If you solve that one, the others will probably also go away (compiler errors tend to be unreliable after the first one).

2021-12-06 15:44 UTC, Maelstrom96 commented
@oxan Here, it is fixed now.

2021-12-06 15:50 UTC, oxan reviewed
Before I look at the code in detail, why do you need your own task to periodically poll the device, instead of being a [PollingComponent](https://github.com/esphome/esphome/blob/dev/esphome/core/component.h#L260)?

2021-12-06 15:59 UTC, Maelstrom96 commented
> Before I look at the code in detail, why do you need your own task to periodically poll the device, instead of being a [PollingComponent](https://github.com/esphome/esphome/blob/dev/esphome/core/component.h#L260)?

I was just writing a comment about that. The reason is that the co-processor we're reading makes the power readings available every ~250-500ms and if you miss them, your total power readings will become less accurate. I've already hit a case where the `update()` function wasn't called fast enough, causing readings to be missed. I know that right now, the sensor reading queue is only of size one, but the goal would be to expand it and add a function to average all sensor readings in the queue, keeping the power usage accurate.

There's also the fact that `i2c->read()` is blocking for ~30ms since we're pulling so many bytes, and that's exacerbated if a user set's a lower i2c baud rate. The task is currently setup so it's on CPU0, a different one than the main loop task (which is CPU1).

2021-12-08 02:03 UTC, krconv requested changes
Proposal here to remove the FreeRTOS task: https://github.com/Maelstrom96/esphome/pull/6

2021-12-08 02:03 UTC, krconv commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
(reposting because I put my review on the wrong PR)
I think that the FreeRTOS task is more hassle than it's worth, and will make this harder to maintain and debug in the long run. I think using a more traditional loop/polling approach is easier to understand and won't require the FreeRTOS dependency, global variable, nor specialized OTA setup.
The drawback is that the I2C read takes a while, ~23ms from my testing, which will slow down the `loop()` by that much every ~0.25s. Considering this hardware is specialized, I think that is ok.

_Originally posted by @krconv in https://github.com/Maelstrom96/esphome/pull/3#discussion_r763041743_

2021-12-08 02:03 UTC, krconv commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
> I'm not sure I understand why you say that it's more hassle than it's worth. It's already implemented and it's working as intended. 

> The main problem I was trying to alleviate with the task is missing readings. Using `loop()` or `update()` [has no guarantee with the execution time](https://esphome.io/api/classesphome_1_1_polling_component.html). I was able to see this first hand when testing yesterday when `loop()` function of the emporia_vue component was not running fast enough when putting the logger option to `VERY_VERBOSE`, missing multiple sensor readings. That means that the other components could slow the main sensor loop enough that we would be missing power readings.

> Right now, I'm only writing a single sensor reading to the queue, but my goal is to eventually add a way to handle a slow `loop()` and average all the sensor readings in the queue before publishing them, allowing `total_daily_energy` to still have a very accurate reading.

_Originally posted by @Maelstrom96 in https://github.com/Maelstrom96/esphome/pull/3#discussion_r763126028_

2021-12-08 02:03 UTC, krconv commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
Do you have a config where it's missing readings? I didn't realize that was a concern, I'm glad to test it out too (I have my Vue set up with 18 CT clamp and daily energy sensors, which I'm thinking is close to the most stress the `loop()` will have)

_Originally posted by @krconv in https://github.com/Maelstrom96/esphome/pull/3#discussion_r763959273_

2021-12-08 03:36 UTC, Maelstrom96 commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
@krconv So I think I was dupped by some of my logs from earlier tests, since calling `ESP_LOGV()` from both the main loop task and the i2c task doesn't always write correctly to the serial output, but it looked like the loop was called fast enough in most cases. However, here is a valid configuration that is missing messages, and also blocking the loop task for way too long ~0.9s.

```
substitutions:
  voltage_filter_trottle: 60s
  ct_power_filter_send_every: "2"
  ct_current_filter_trottle: 1s

time:
  - platform: sntp
    id: sntp_time

i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 100kHz
  id: i2c_a

sensor:
  - platform: total_daily_energy
    name: "Total Daily Energy - A"
    power_id: ct_a
  - platform: total_daily_energy
    name: "Total Daily Energy - B"
    power_id: ct_b
  - platform: total_daily_energy
    name: "Total Daily Energy - C"
    power_id: ct_c
  - platform: total_daily_energy
    name: "Total Daily Energy - 1"
    power_id: ct_1
  - platform: total_daily_energy
    name: "Total Daily Energy - 2"
    power_id: ct_2
  - platform: total_daily_energy
    name: "Total Daily Energy - 3"
    power_id: ct_3
  - platform: total_daily_energy
    name: "Total Daily Energy - 4"
    power_id: ct_4    
  - platform: total_daily_energy
    name: "Total Daily Energy - 5"
    power_id: ct_5
  - platform: total_daily_energy
    name: "Total Daily Energy - 6"
    power_id: ct_6
  - platform: total_daily_energy
    name: "Total Daily Energy - 7"
    power_id: ct_7
  - platform: total_daily_energy
    name: "Total Daily Energy - 8"
    power_id: ct_8
  - platform: total_daily_energy
    name: "Total Daily Energy - 9"
    power_id: ct_9
  - platform: total_daily_energy
    name: "Total Daily Energy - 10"
    power_id: ct_10
  - platform: total_daily_energy
    name: "Total Daily Energy - 11"
    power_id: ct_11
  - platform: total_daily_energy
    name: "Total Daily Energy - 12"
    power_id: ct_12
  - platform: total_daily_energy
    name: "Total Daily Energy - 13"
    power_id: ct_13
  - platform: total_daily_energy
    name: "Total Daily Energy - 14"
    power_id: ct_14
  - platform: total_daily_energy
    name: "Total Daily Energy - 15"
    power_id: ct_15
  - platform: total_daily_energy
    name: "Total Daily Energy - 16"
    power_id: ct_16

  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_1
        input: BLACK
        voltage: 
          name: Phase 1 Voltage
          filters:
            - throttle: $voltage_filter_trottle
      - id: phase_2
        input: RED
        voltage: 
          name: Phase 2 Voltage
          filters:
            - throttle: $voltage_filter_trottle
      - id: phase_3
        input: BLUE
        voltage: 
          name: Phase 3 Voltage
          filters:
            - throttle: $voltage_filter_trottle
    ct_clamps:
      - phase_id: phase_1
        input: A
        power:
          id: ct_a
          name: "A Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "A Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_2
        input: B
        power:
          id: ct_b
          name: "B Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "B Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_3
        input: C
        power:
          id: ct_c
          name: "C Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "C Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_1
        input: "1"
        power:
          id: ct_1
          name: "1 Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "1 Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_1
        input: "2"
        power:
          id: ct_2
          name: "2 Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "2 Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_1
        input: "3"
        power:
          id: ct_3
          name: "3 Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "3 Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_1
        input: "4"
        power:
          id: ct_4
          name: "4 Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "4 Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_1
        input: "5"
        power:
          id: ct_5
          name: "5 Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "5 Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_1
        input: "6"
        power:
          id: ct_6
          name: "6 Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "6 Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_1
        input: "7"
        power:
          id: ct_7
          name: "7 Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "7 Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_1
        input: "8"
        power:
          id: ct_8
          name: "8 Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "8 Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_1
        input: "9"
        power:
          id: ct_9
          name: "9 Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "9 Current"
          filters:
            - throttle: $ct_current_filter_trottle
      - phase_id: phase_1
        input: "10"
        power:
          id: ct_10
          name: "10 Power"
          filters:
            - sliding_window_moving_average:
                window_size: $ct_power_filter_send_every
                send_every: $ct_power_filter_send_every
        current:
          name: "10 Current"
          filters:
            - throttle: $ct_current_filter_trottle
   [...]

2021-12-08 04:30 UTC, Maelstrom96 commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
Just checked and the log functions are not using the esp-idf "logger.h" and don't use a mutex on the ESP32, so it's not safe to call logging from another CPU task. I might implement a mutex later to allow logging to work correctly.

2021-12-08 14:18 UTC, krconv commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
@Maelstrom96 Is that using the FreeRTOS task? If it is missing readings with that approach, then why is it more beneficial than a simpler `loop()` based approach?
FWIW, I tested [this config](https://gist.github.com/krconv/cb335fbb829cf8e18f4fdd9dcf3b246b) with every sensor in the component enabled but at INFO level with the `loop()` based polling, and am not missing any readings.

2021-12-08 17:18 UTC, Maelstrom96 commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
The reason is that for MVP, I wanted to test with a single item queue and confirm that everything was working as expected. In most cases, the loop should be ran fast enough to not miss any messages, but in some cases, it could happen. The sensor readings wouldn’t be read in time and we would just push a new message to the queue. The receiver in the loop would then be able to pull 2 sensor readings and sum them up so we don't loose any accuracy. This task is to handle that edge case and I agree that in most cases, using the loop to process the i2c request would be fine, but I would expect the component to perform as accuratly as possible, and as accurately as the Emporia firmware.

2021-12-09 00:18 UTC, krconv commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
I think we both agree the loop is simpler, and works just as accurately as the task; why can't we use that approach and switch to the task + queue only if we find that we need to?

2021-12-09 01:06 UTC, Maelstrom96 commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
I didn't agree - I said that in most cases it would work, but that it's suboptimal if we're aiming to achieve the best accuracy the coprocessor sensor data provides. I'm also looking at doing a custom implementation of the `Total_daily_energy` for the component, since there's no way to inject a fixed update rate to average the power consumption precisely. Right now, the timing is calculated from the previous `publish_value()` to the current `publish_value()`, which is not accurate in our case. The sensor data that as pulled on i2c is not "current" and is instead an average power draw over 510ms.

2021-12-09 12:44 UTC, krconv commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
That's a great idea!

2021-12-09 12:50 UTC, krconv commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
Well, @oxan I don't think we will come to an agreement on the best way for this component. Feel free to review as is!
@Maelstrom96 Mind removing me as a code owner? This is not what I want to do in my free time

2021-12-09 18:57 UTC, Maelstrom96 commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
> Well, @oxan I don't think we will come to an agreement on the best way for this component. Feel free to review as is! @Maelstrom96 Not as motivated to help maintain this anymore; mind removing me as a code owner?

I want to say that I'm sorry that you feel that way - I'm only trying to discuss what's the best way to get the most out of the Emporia Vue 2 hardware. I was mainly waiting on maintainers input on what they think is the best fit with the ESPHome codebase and pointing out why I think an i2c read task makes the most sense. I really value your point of view on the subject and I even added the other changes you suggested regarding the configuration layout since they were good points.  It wasn't my goal make you feel unmotivated to keep contributing. 

Furthermore, I really would like to wait on inputs from the maintainers before removing you as code owner. If you still want to be removed afterwards, I will do as you wish.

2021-12-20 21:46 UTC, oxan commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
Sorry for the long delay in the response, it's been busy and I've been somewhat torn on this PR. I understand your arguments for wanting to use a task here, but in the end I agree with @krconv that the FreeRTOS task is probably more hassle than it's worth.

My thoughts boil down to this:
* Having a FreeRTOS task in a component will be an ongoing maintainence burden. As you discovered, currently OTA interferes with it, but other issues might pop up or be introduced in the future. It's an unusual pattern in ESPHome, and when hidden in a component, it's not something people will consider when working on the core. I agree that architecturally it's a good solution, and its functionality is something I would like to eventually have integrated in the core, but I don't it works well in a component.
* While I appreciate your desire to get the best measurements, missing a sample doesn't seem like a huge problem here. You'll miss a bit of resolution when integrating total power usages, but it won't influence measurements. I also don't think the task approach is bulletproof, as it still polls the coprocessor, so it could miss a reading. The second core isn't always idle anyway either, it can block for a while in e.g. the wifi task. 
* If you also need to replace the `total_daily_energy` component, this becomes an increasingly big amount of code for a single device. That's not necessarily a bad thing, but it begs the question whether this should be in ESPHome core. Maintaining the full stack for this device as an external component might be less work for both parties.

2021-12-20 22:40 UTC, Maelstrom96 commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
@oxan Thank you for the input - I've been thinking about how I would go about making it work optimally without using the FreeRTOS task and I think I've come up with a satisfactory solution that I'll be trying to implement shortly.

I have comments on parts of your input:

> While I appreciate your desire to get the best measurements, missing a sample doesn't seem like a huge problem here. You'll miss a bit of resolution when integrating total power usages, but it won't influence measurements.

This is overall wrong, as missing a measurement will affect the precision of the total power usage. This device's whole purpose is to precisely measure power on branch and main circuits, and making sure it's as close to the real values is the whole point. The coprocessor averages the power draw over each update it makes available (which we poll). If we miss the message, that consumption is lost and the power consumption will not be as accurate. 
Example: message `#1` has 3000W and `#2` 0W for P[V1], it would mean that for the entire time span (~1020ms), we pulled on average 750W, but if we didn't get the message `#1`, we will average the consumption of that ~1s to 0kWh, while it should've increased the power consumption by 0.2125Wh. It doesn't look like much, but over time, with devices with variable duty cycles, like voltage-line heating baseboards, it will skew the data if messages are often missed. We could imagine a case where the device duty-cycle is ~0.5s and we end up having power data like this : `#1 - 3000W, #2 - 0W, #3 - 3000W, #4 - 0W`. In this case, if we discard half the message, we could end up way overshooting the power consumption (2x) or just registering no power consumption. This is the worst case scenario and in real world usage, we most likely would be close-ish to the real power consumption, but it's just to show that loosing messages can greatly affect the overall total power consumption in great ways.

> I also don't think the task approach is bulletproof, as it still polls the coprocessor, so it could miss a reading. The second core isn't always idle anyway either, it can block for a while in e.g. the wifi task.

With the way the FreeRTOS scheduler works, subtasks shouldn't actually block the execution of other subtasks (in this case the i2c_read_task), since all tasks are given CPU cycles depending on their priority. Even if the wifi tasks waits or blocks, the i2c task will be given CPU time to process the i2c read correctly and on time. We're pulling each 240ms (same logic as the Emporia firmware) while the co-processor is updating each ~510ms to make sure we're not missing any readings. Even putting the task on the same core as the loop task should result in it firing at the right interval.

>That's not necessarily a bad thing, but it begs the question whether this should be in ESPHome core. Maintaining the full stack for this device as an external component might be less work for both parties.

I was actually debating if it made sense to make it as an external component instead, but the main reason that made me want to merge it in the main ESPHome repository is for visibility. Right now, it doesn't look like you would accept documentation to be added to the ESPHome-docs if they're not natively in the ESPHome repository. If I'm mistaken, please let me know.

Again, thank you very much for your time and for maintaining to the ESPHome project!

2021-12-28 15:52 UTC, flaviut commented on esphome/components/emporia_vue/emporia_vue.cpp
> +EmporiaVueComponent *global_emporia_vue_component = nullptr;
From a practical (admittedly n=1) perspective, using the FreeRTOS task has led to frequent drop-outs. I've found that I get much more stable results with @krconv's branch:

![2021-12-28-104526_1093x432_scrot](https://user-images.githubusercontent.com/5213469/147583313-0854349f-ade2-46fc-8886-279c9ac62010.png)

In addition, I've kept the log open via the dashboard for the last 17 hours, and the only time I saw the "Detected 1 missing reading(s)," warning was when I started viewing the log & it printed out the super long config. I do have

```
logger:
  logs:
    # don't log on each sensor reading, that's way too loud
    sensor: INFO
```

set though, since seeing the sensor readings didn't seem very useful, and there were **so** *many* of those lines that it froze up my browser.

<details>
 <summary>My full config</summary>

```
esphome:
  name: emporiavue2

external_components:
  - source: github://krconv/esphome@remove-freertos-task
    components: [ emporia_vue ]

esp32:
  board: d-duino-32
  framework:
    type: esp-idf
    version: recommended

logger:
  logs:
    # don't log on each sensor reading, that's way too loud
    sensor: INFO

# Enable Home Assistant API
api: {"password": "3hvPAWtULJRG"}
ota: {"password": "3hvPAWtULJRG"}

wifi:
  ssid: "entire-fact"
  password: "nutty watch"

# Example configuration entry
i2c:
  sda: 21
  scl: 22
  scan: false
  frequency: 200kHz  # recommended range is 50-200kHz
  id: i2c_a

time:
  - platform: sntp
    id: my_time

sensor:
  - platform: emporia_vue
    i2c_id: i2c_a
    phases:
      - id: phase_a
        input: BLACK
        voltage:
          name: "Phase A Voltage"
          filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } }
      - id: phase_b
        input: RED
        voltage:
          name: "Phase B Voltage"
          filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } }
    ct_clamps:
      - phase_id: phase_a
        input: "A"
        power:
          name: "Phase A Power"
          id: phase_a_power
          device_class: power
          filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } }
      - phase_id: phase_b
        input: "B"
        power:
          name: "Phase B Power"
          id: phase_b_power
          device_class: power
          filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } }
      - { phase_id: phase_a, input:  "1", power: { name:  "Circuit 1 Power", id:  cir1, filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } } } }
      - { phase_id: phase_b, input:  "2", power: { name:  "Circuit 2 Power", id:  cir2, filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } } } }
      - { phase_id: phase_a, input:  "3", power: { name:  "Circuit 3 Power", id:  cir3, filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } } } }
      - { phase_id: phase_a, input:  "4", power: { name:  "Circuit 4 Power", id:  cir4, filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } } } }
      - { phase_id: phase_a, input:  "5", power: { name:  "Circuit 5 Power", id:  cir5, filters: [ multiply: 2, sliding_window_moving_average: { window_size: 6, send_every: 6 } ] } }
      - { phase_id: phase_a, input:  "6", power: { name:  "Circuit 6 Power", id:  cir6, filters: [ multiply: 2, sliding_window_moving_average: { window_size: 6, send_every: 6 } ] } }
      - { phase_id: phase_a, input:  "7", power: { name:  "Circuit 7 Power", id:  cir7, filters: [ multiply: 2, sliding_window_moving_average: { window_size: 6, send_every: 6 } ] } }
      - { phase_id: phase_b, input:  "8", power: { name:  "Circuit 8 Power", id:  cir8, filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } }} }
      - { phase_id: phase_b, input:  "9", power: { name:  "Circuit 9 Power", id:  cir9, filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } }} }
      - { phase_id: phase_b, input: "10", power: { name: "Circuit 10 Power", id: cir10, filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } }} }
      - { phase_id: phase_a, input: "11", power: { name: "Circuit 11 Power", id: cir11, filters: [ multiply: 2, sliding_window_moving_average: { window_size: 6, send_every: 6 } ] } }
      - { phase_id: phase_a, input: "12", power: { name: "Circuit 12 Power", id: cir12, filters: [ multiply: 2, sliding_window_moving_average: { window_size: 6, send_every: 6 } ] } }
      - { phase_id: phase_a, input: "13", power: { name: "Circuit 13 Power", id: cir13, filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } }} }
      - { phase_id: phase_a, input: "14", power: { name: "Circuit 14 Power", id: cir14, filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } }} }
      - { phase_id: phase_b, input: "15", power: { name: "Circuit 15 Power", id: cir15, filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } }} }
      - { phase_id: phase_a, input: "16", power: { name: "Circuit 16 Power", id: cir16, filters: { sliding_window_moving_average: { window_size: 6, send_every: 6 } }} }
  - platform: template
    name: "Total Power"
    lambda: return id(phase_a_power).state + id(phase_b_power).state;
    update_interval: 1s
    id: total_power
    unit_of_measurement: "W"
  - platform: total_daily_energy
    name: "Total Daily Energy"
    power_id: total_power
    accuracy_decimals: 0
  - { power_id:  cir1, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 1 Daily Energy" }
  - { power_id:  cir2, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 2 Daily Energy" }
  - { power_id:  cir3, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 3 Daily Energy" }
  - { power_id:  cir4, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 4 Daily Energy" }
  - { power_id:  cir5, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 5 Daily Energy" }
  - { power_id:  cir6, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 6 Daily Energy" }
  - { power_id:  cir7, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 7 Daily Energy" }
  - { power_id:  cir8, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 8 Daily Energy" }
  - { power_id:  cir9, platform: total_daily_energy, accuracy_decimals: 0, name:  "Circuit 9 Daily Energy" }
  - { power_id: cir10, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 10 Daily Energy" }
  - { power_id: cir11, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 11 Daily Energy" }
  - { power_id: cir12, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 12 Daily Energy" }
  - { power_id: cir13, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 13 Daily Energy" }
  - { power_id: cir14, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 14 Daily Energy" }
  - { power_id: cir15, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 15 Daily Energy" }
  - { power_id: cir16, platform: total_daily_energy, accuracy_decimals: 0, name: "Circuit 16 Daily Energy" }
```

</details>

2022-01-09 21:32 UTC, flaviut commented
Hey, I'd like to keep this moving forward. I'm  thinking doing the following:

- merge the krconv:remove-freertos-task branch into this
- update the documentation to match that branch's configuration changes

@Maelstrom96 How does this sound to you? Would you like me to make these changes in your forks, or should I start a new PR?

@oxan Are there any other major concerns on this?

2022-01-09 22:09 UTC, Maelstrom96 commented
@flaviut I was mostly waiting on input for external component discovery / documentation, since it would make sense maintenance wise to use the external component feature.

I haven't had much time to work on the component lately but I should be able to put some time to implement some of the feature I wanted to do in the next week.

2022-01-10 12:11 UTC, flaviut commented
> @flaviut I was mostly waiting on input from @oxan for external component discovery / documentation, since it would make sense maintenance wise to use the external component feature.

In this case, the correct place for it would be https://esphome.io/guides/diy.html.

What other feature work do you have in mind?

I do still have severe connection instability when using the task-based system, but I'll try and get to the root cause this weekend.

2022-04-18 00:47 UTC, closed without merging