Support inverted tm1637 display
OttoWinter/esphomeyaml pull request #2878
Opened 2021-12-06 18:44 UTC by jlsjonas

# What does this implement/fix? 
Support inverting the tm1637 display

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1703

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  platform: tm1637
  id: tm1637_display
  clk_pin: GPIO16
  dio_pin: GPIO17
  inverted: true
  length: 4
  lambda: |-
    it.print("0234");
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-06 19:11 UTC, jlsjonas commented
Will update the log lines in ~1hr, moved to draft until I'm able to (AFK)

2021-12-07 08:45 UTC, oxan requested changes

2021-12-07 08:45 UTC, oxan commented on esphome/components/tm1637/tm1637.cpp
> +  ESP_LOGCONFIG(TAG, "  LENGTH: %d", this->length_);
Not sure why the one that was there is all-caps, but we generally don't do that:
```suggestion
  ESP_LOGCONFIG(TAG, "  Intensity: %d", this->intensity_);
  ESP_LOGCONFIG(TAG, "  Inverted: %d", this->inverted_);
  ESP_LOGCONFIG(TAG, "  Length: %d", this->length_);
```

2021-12-07 08:45 UTC, oxan commented on esphome/components/tm1637/tm1637.cpp
> +    for (auto i = this->length_ - 1; i >= 0; i--) {
I prefer being explicit about the type here, as if `auto` deduces an unsigned type, the loop will never terminate. It works fine currently because of the usual arithmetic conversions, but that's fragile (e.g. if `1` gets changed to `1u` it breaks).
```suggestion
    for (uint8_t i = this->length_ - 1; i >= 0; i--) {
```

2021-12-07 11:29 UTC, jlsjonas commented
@oxan was trying to remain consistent indeed.

If _you_ prefer a rebase to single-commit the changes, let me know and I'll rebase this evening.

2021-12-07 11:59 UTC, oxan commented
> If _you_ prefer a rebase to single-commit the changes, let me know and I'll rebase this evening.

Nah, this is fine, because of GitHub's non-existing support for versioning PR's I actually prefer it, as it's the only way I can see a diff since my last review (and ESPHome squash-merges).

2021-12-07 11:59 UTC, oxan approved these changes

2021-12-15 17:44 UTC, jlsjonas commented
Is anything preventing this from getting merged? :thinking:

2021-12-15 21:44 UTC, oxan commented
See [my comment](https://github.com/esphome/esphome-docs/pull/1703#pullrequestreview-824956271) on the docs PR.

2021-12-20 08:30 UTC, merged

2021-12-20 08:30 UTC, oxan commented
Thanks!

2021-12-20 12:30 UTC, jlsjonas commented on esphome/components/tm1637/tm1637.cpp
> +    for (auto i = this->length_ - 1; i >= 0; i--) {
Looks like we caused what we tried to avoid ;)
See https://github.com/esphome/esphome/pull/2929