quantile filter support
OttoWinter/esphomeyaml pull request #2900
Opened 2021-12-09 21:24 UTC by konikvranik

# What does this implement/fix? 

Implemented quantile filter for sensor.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1543

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1715

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
  - platform: template
...
    filters:
      - quantile:
          window_size: 120
          send_every: 12
          send_first_at: 6
          quantile: .7
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-12 22:00 UTC, jesserockz approved these changes
Could you add this to `tests/test3.yaml` please?

2021-12-13 17:30 UTC, oxan requested changes

2021-12-13 17:30 UTC, oxan commented on esphome/components/sensor/filter.cpp
> +      size_t position = ceill(queue_size * this->quantile_) - 1;
No reason to use `long double` (which utterly kills performance) here.
```suggestion
      size_t position = ceilf(queue_size * this->quantile_) - 1;
```

2021-12-13 17:30 UTC, oxan commented on esphome/components/sensor/filter.h
> + * Takes the median of the last <send_every> values and pushes it out every <send_every>.
Copy/paste error.

2021-12-13 17:30 UTC, oxan commented on esphome/components/sensor/filter.h
> +   * @param window_size The number of values that should be used in median calculation.
Copy/paste error.

2021-12-14 09:37 UTC, oxan approved these changes

2021-12-14 18:43 UTC, merged