create shutdown and safe_mode button
OttoWinter/esphomeyaml pull request #2918
Opened 2021-12-15 17:12 UTC by jsuanet

# What does this implement/fix? 

New buttons for shutdown and safe_mode, can be used as replacement for shutdown and safe_mode switches.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
button:
  - platform: safe_mode
    name: my_device safe_mode button
  - platform: shutdown
    name: my_device shutdown button

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-19 19:31 UTC, jesserockz requested changes

2021-12-19 19:31 UTC, jesserockz commented on esphome/components/safe_mode/button/__init__.py
> +    .extend(cv.COMPONENT_SCHEMA)
The icon can be set in the `button_schema()`

2021-12-19 19:31 UTC, jesserockz commented on esphome/components/safe_mode/button/safe_mode_button.cpp
> +static const char *const TAG = "safe_mode_button";
Tags should always be separated with a `.`

```suggestion
static const char *const TAG = "safe_mode.button";
```

2021-12-19 19:31 UTC, jesserockz commented on esphome/components/shutdown/button/__init__.py
> +)
Move icon into `button_schema` and remove device_class as it does not match.

2021-12-19 20:20 UTC, jsuanet commented on esphome/components/safe_mode/button/__init__.py
> +    .extend(cv.COMPONENT_SCHEMA)
done

2021-12-19 20:20 UTC, jsuanet commented on esphome/components/shutdown/button/__init__.py
> +)
done

2021-12-20 00:16 UTC, jesserockz approved these changes
LGTM

2021-12-20 21:23 UTC, oxan approved these changes
At some point we can also deprecate the old switches.

2021-12-20 21:25 UTC, merged

2021-12-20 21:25 UTC, oxan commented
Thanks!