Add turn_on/off trigger to slow_pwm
OttoWinter/esphomeyaml pull request #2921
Opened 2021-12-16 16:11 UTC by martgras

# What does this implement/fix? 

Adds triggers to slow_pwm. These triggers can be used to turn on/off any other compoment and slow_pwm is not longer limited to GPIO. 

- change 'pin'  to optional.
- add  `toggle_action`, `turn_on_action` and `turn_off_action` trigger
- if pin is configured it will be executed regardless if the turn_on/off_action triggers are defined to avoid breaking existing code
-  `toggle_action` and `turn_on/off_action` can be used togther. `toggle_action` is called before `turn_on/off_action`. It's recommended to use either `toggle_action` or `turn_on/off_action` to change the state of an output. Using both automations together is only recommended for monitoring. Both variants are provided for easy of use. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1548

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1730

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: testing
  on_boot:
    priority: -100
    then:
      output.set_level:
        id: my_slow_pwm
        level: 25%
          
output:
  - platform: template
    id: output1
    type: binary
    write_action:
      - then:
          - lambda: ESP_LOGD("Template Output","set state to %d",state);

  - platform: slow_pwm
    id: my_slow_pwm
    period: 15s
    # pin: 5
    # toggle_action:
    #  - lambda: |-
    #      ESP_LOGD("SLOW PWM","toggle to state %d",state);
    #      auto *out1 = id(output1);
    #      if (state)
    #        out1->turn_on();
    #      else
    #        out1->turn_off();
    turn_on_action:
      - lambda: |-
          auto *out1 = id(output1);
          out1->turn_on();
    turn_off_action:
      - output.turn_off: output1
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-16 16:56 UTC, nagyrobi commented
Awesome, thank you.

2021-12-20 21:23 UTC, oxan commented on esphome/components/slow_pwm/output.py
> +        )
What's the need for the toggle action? Having a toggle option with a state parameter is not a common pattern in ESPHome, usually it's either just turn_on/turn_off (e.g. template switch) or toggle without a parameter that should go to the opposite of the current state (covers & fans).

2021-12-21 08:51 UTC, martgras commented on esphome/components/slow_pwm/output.py
> +        )
Toggle action is not required and the name could be like state_change_action.
I added it for actions where you want to do more or less the same when the state changes.  Just as a short cut for not having to write a turn on and turn off action

2021-12-22 02:42 UTC, jesserockz requested changes

2021-12-22 02:42 UTC, jesserockz commented on esphome/components/slow_pwm/output.py
> +    if CONF_TURN_OFF_ACTION in config:
Because of the `Inclusive`, you can put both under the first condition.
```suggestion
```

2021-12-22 02:42 UTC, jesserockz commented on esphome/components/slow_pwm/slow_pwm_output.cpp
> +    LOG_PIN("  Using pin: ", this->pin_);
The macro already has a condition for nullptr pins
```suggestion
  LOG_PIN("  Using pin: ", this->pin_);
```

2021-12-22 07:27 UTC, martgras commented on esphome/components/slow_pwm/output.py
> +        )
renamed it to `state_change_action`

2021-12-22 11:16 UTC, nagyrobi commented
Using this with `external_components` as we speak, it's great to be able to set a binary sensor template in the actions, to actually monitor what's really happening behind the scenes.

2021-12-22 19:17 UTC, jesserockz approved these changes
LGTM now

2022-01-05 20:25 UTC, oxan requested changes

2022-01-05 20:25 UTC, oxan commented on esphome/components/slow_pwm/slow_pwm_output.cpp
> +  static bool current_state = false;
This should be an instance variable, this doesn't work correctly if you have multiple `slow_pwm` outputs.

2022-01-05 20:25 UTC, oxan commented on esphome/components/slow_pwm/slow_pwm_output.cpp
> +  LOG_PIN("  Using pin: ", this->pin_);
I think we can just leave it be `Pin:`, that's consistent with how we phrase it everywhere.

2022-01-05 20:25 UTC, oxan commented on esphome/components/slow_pwm/slow_pwm_output.h
> +  void set_state_(bool state);
Maybe `set_output_` or `set_output_state_` is a better name.

2022-01-05 20:25 UTC, oxan commented on esphome/components/slow_pwm/slow_pwm_output.h
> +  GPIOPin *pin_{nullptr};
Please put all variables after all methods.

2022-01-05 20:25 UTC, oxan commented on esphome/components/slow_pwm/slow_pwm_output.h
> +    if (!turn_on_trigger_)
Prefixing all these accesses with `this->` would be nice.

2022-01-05 20:25 UTC, oxan commented on esphome/components/slow_pwm/slow_pwm_output.h
> +  float state_;
This still needs an initialization, I think.
```suggestion
  float state_{0};
```

2022-01-05 21:02 UTC, martgras commented on esphome/components/slow_pwm/slow_pwm_output.h
> +  float state_;
thanks all applied

2022-01-06 15:38 UTC, oxan approved these changes

2022-01-09 16:43 UTC, nagyrobi commented
Please add this to next release. Thank you.

2022-01-09 18:49 UTC, merged