Add growatt modbus sensor
OttoWinter/esphomeyaml pull request #2922
Opened 2021-12-17 15:07 UTC by leeuwte

# What does this implement/fix? 

Adds the growatt modbus sensor

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1732

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:
# Example configuration entry
    uart:
      - id: uart1
        baud_rate: 9600
        tx_pin: GPIO1
        rx_pin: GPIO3

    modbus:
      uart_id: uart1
      flow_control_pin: GPIO4

    sensor:
      - platform: growatt_solar
        update_interval: 10s
        
        inverter_status:
          name: "Growatt Status Code"

        phase_a:
          voltage:
              name: "Growatt Voltage Phase A"
          current:
              name: "Growatt Current Phase A"
          active_power:
              name: "Growatt Power Phase A"
        phase_b:
          voltage:
              name: "Growatt Voltage Phase B"
          current:
              name: "Growatt Current Phase B"
          active_power:
              name: "Growatt Power Phase B"
        phase_c:
          voltage:
              name: "Growatt Voltage Phase C"
          current:
              name: "Growatt Current Phase C"
          active_power:
              name: "Growatt Power Phase C"

        pv1:
          voltage:
              name: "Growatt PV1 Voltage"
          current:
              name: "Growatt PV1 Current"
          active_power:
              name: "Growatt PV1 Active Power"

        pv2:
          voltage:
              name: "Growatt PV2 Voltage"
          current:
              name: "Growatt PV2 Current"
          active_power:
              name: "Growatt PV2 Active Power"

        active_power:
          name: "Growatt Grid Active Power"

        pv_active_power:
          name: "Growatt PV Active Power"

        frequency:
          name: "Growatt Frequency"

        energy_production_day:
          name: "Growatt Today's Generation"
          
        total_energy_production:
          name: "Growatt Total Energy Production"

        inverter_module_temp:
          name: "Growatt Inverter Module Temp"

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-19 20:03 UTC, jesserockz requested changes
Mostly looks good, just a few minor things

2021-12-19 20:03 UTC, jesserockz commented on esphome/components/growatt_solar/growatt_solar.cpp
> +      sensor->publish_state(value);
This way it doesnt need to encode even if the sensor is not set. (Same for the next one too)
```suggestion
    if (sensor == nullptr)
      return;
    float value = encode_uint16(data[i * 2], data[i * 2 + 1]) * unit;
    sensor->publish_state(value);
```

2021-12-19 20:03 UTC, jesserockz commented on esphome/components/growatt_solar/growatt_solar.h
> + protected:
For consistency, can you move the `protected` block under the `public` one

2021-12-19 20:03 UTC, jesserockz commented on esphome/components/growatt_solar/growatt_solar.h
> +    bool setup{false};
Please remove as you don't use the `setup` bools

2021-12-19 20:03 UTC, jesserockz commented on esphome/components/growatt_solar/growatt_solar.h
> +    bool setup{false};
Same here

2021-12-19 20:24 UTC, leeuwte commented on esphome/components/growatt_solar/growatt_solar.cpp
> +      sensor->publish_state(value);
done!

2021-12-19 20:24 UTC, leeuwte commented on esphome/components/growatt_solar/growatt_solar.h
> + protected:
ok :D

2021-12-19 20:24 UTC, leeuwte commented on esphome/components/growatt_solar/growatt_solar.h
> +    bool setup{false};
of course (copy paste 🤦 )

2021-12-19 20:25 UTC, leeuwte commented on esphome/components/growatt_solar/growatt_solar.h
> +    bool setup{false};
of course (copy paste 🤦 ) 2

2021-12-20 01:12 UTC, jesserockz approved these changes

2021-12-20 01:30 UTC, merged