Add mqtt for idf
OttoWinter/esphomeyaml pull request #2930
Opened 2021-12-20 14:13 UTC by martgras

# What does this implement/fix? 

Adds mqtt support for esp-idf. 
Requires: https://github.com/esphome/esphome/pull/2844 because json is a dependency. 

- SSL isn't working yet 
- disconnectReason is not populated
- need lint exceptions for AsyncMqttClient method names
- marked as a draft

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:
```
esphome:
  name: testing

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: VERBOSE

wifi:
  ssid: !secret wifi_sid
  password: !secret wifi_password

mqtt:
  broker: 192.168.1.114
  port: 1883
  discovery: true
  discovery_prefix: homeassistant
  on_message:
    topic: testing/sensor/uptime_sensor/state
    qos: 0
    then:
      - lambda: |-
          ESP_LOGD("Mqtt Test","testing/sensor/uptime_sensor/state=[%s]",x.c_str());

sensor:
  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 10s
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

## Todo:
  - [ ] SSL.
  - [ ] Clean-up.

2021-12-29 14:24 UTC, misery commented
Nice, I like to see mqtt with esp-idf. I tried your branch here and get an error.

```
Compiling .pioenvs/testing/src/esphome/components/mqtt/mqtt_component.o
In file included from src/esphome/components/mqtt/mqtt_client.cpp:1:
src/esphome/components/mqtt/mqtt_client.h:12:10: fatal error: AsyncMqttClient.h: No such file or directory

*************************************************************************
* Looking for AsyncMqttClient.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:AsyncMqttClient.h"
* Web  > https://platformio.org/lib/search?query=header:AsyncMqttClient.h
*
*************************************************************************

 #include <AsyncMqttClient.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/testing/src/esphome/components/mqtt/mqtt_client.o] Error 1
```

2021-12-29 14:31 UTC, martgras commented
That doesn't seem to be the correct code or maybe git didn't delete the files I remaned .  mqtt_client.h and mqtt_client.cpp have been renamed to mqttclient. You shouldn't have mqtt_client.* in the directory anymore

2021-12-29 15:30 UTC, misery commented
> That doesn't seem to be the correct code or maybe git didn't delete the files. I renamed mqtt_client.h and mqtt_client.cpp to mqttclient. You shouldn't have mqtt_client.* in the directory anymore

Yeah, I thought that, too. I multiple deleted the whole build directory and used a fresh virtualenv for esphome.

2022-01-02 13:41 UTC, martgras commented
@misery I updated the PR based on the latest dev changes 


For testing you can use:
```yaml
external_components:
  - source: github://pr#2979
    components: ["json"]
  - source: github://pr#2930
    components: ["mqtt"]
```
try esphome clean  <yaml> if see compilation errors about missing includes
Also make sure you are using the dev branch and it is up to date

2022-01-02 14:19 UTC, misery commented
Thanks! I tried external_component and had an include problem again. So I cleaned anything again and cherry-picked the changes to the dev branch. That worked! Maybe dirty working directory or something like this even it was a fresh installation. But I have ESP32-S2 with idf mqtt now! Yeah!

It looks a little bit slow in logging. It take one seconds for each line. But it finally works. :-)

2022-01-02 15:05 UTC, martgras commented
Interesting I even see a larger delay (~20 seconds sometimes). 
I just added  the  `idf_send_async` option to mqtt .  If true (default)  publish happens on the mqtt task and will be delayed 
If false publish will happen immediately  but thread can be blocked for up to 10 seconds (network timeouts)

If you want to try add `refresh: 1h` to external_components otherwise it will take a day before your client syncs again with github

```
external_components:
  - source: github://pr#2979
    components: ["json"]
  - source: github://pr#2930
    refresh: 1h
    components: ["mqtt"]
mqtt:
  broker: 192.168.1.114
  port: 1883
  discovery: true
  discovery_prefix: homeassistant
  idf_send_async: false
  on_message:
    topic: testing/sensor/uptime_sensor/state
    qos: 0
    then:
      - lambda: |-
          ESP_LOGD("Mqtt Test","testing/sensor/uptime_sensor/state=[%s]",x.c_str());
```

2022-01-17 03:20 UTC, flaviut requested changes
Generally looks good to me! I'm very happy to see CA support here, and thanks for doing the work.

2022-01-17 03:20 UTC, flaviut commented on esphome/components/mqtt/mqtt_client_idf.cpp
> +  if (this->username_.empty()) {
things seem to work fine, which confuses me, since this only sets the username if there's nothing in it.

If this isn't supposed to do anything, it ought to be deleted, otherwise can you drop in a comment explaining how it works?

2022-01-17 03:20 UTC, flaviut commented on esphome/components/mqtt/mqtt_client_idf.cpp
> +      // TODO is there a way to get the disconnect reason?
There is not :(

https://github.com/espressif/esp-mqtt/blob/026253d802473ac9afd4cc747e2632e96f71acbb/mqtt_client.c#L700-L712

2022-01-17 03:20 UTC, flaviut commented on esphome/components/mqtt/mqtt_client_idf.cpp
> +      if (data_len == 0)
Did you run into problems with testing here? If not, we should trust `data_len` if it is zero, since it is always set: https://github.com/espressif/esp-mqtt/blob/026253d802473ac9afd4cc747e2632e96f71acbb/mqtt_client.c#L996

In any case, we shouldn't use strlen, we should be defensive & bail out, rather than potentially working with corrupt data.

2022-01-17 03:24 UTC, flaviut commented
> @oxan said in https://discord.com/channels/429907082951524364/524177279270780928/922595211484491816
>
> i think it might be cleaner if we just define our own interface for an MQTT client, and create implementations based upon the Arduino lib and IDF though, instead of mimicking the Arduino lib with an IDF implementation

I'm mildly against using a different interface than the Arduino one. The existing interface isn't perfect--the issues I see are:

- the use of raw strings in https://github.com/esphome/esphome/pull/2930/files#diff-a6f0409da74bdf8195008586e72677896ee42155f02e40efb02197648a23e556R42
- extra QOS parameter in https://github.com/esphome/esphome/pull/2930/files#diff-a6f0409da74bdf8195008586e72677896ee42155f02e40efb02197648a23e556R39
- the use of a different method naming convention than ESPHome.

But I don't feel like those changes outweigh the minuscule advantages of keeping the interface the same (mostly familiarity).

It's your project so your decision, but I'd be OK with the way things are here if this was my project.

2022-01-17 21:22 UTC, oxan commented
My biggest problem with imitating the Arduino interface is that it's bound to get ugly when the featureset isn't equal. If Arduino implements a feature we don't, we need to provide an empty method that does nothing, which is a great way for a future developer to lose an hour wondering why his code that looks perfectly fine doesn't work. If IDF has a feature that Arduino doesn't, we can't add that to the Arduino class. Using the Arduino interface also creates the expectation that the Arduino library is used, which again might be a surprise for future developers looking at this.

The other thing is that the Arduino interfaces usually aren't great, to say it diplomatically. That also caused that comment, but now that I've actually looked at the interface, it's not _that_ bad. That helpers implementing our own interface as well though, since it can mostly be a 1:1 translation.

That said, I don't think creating a wrapper interface will be that much work and that it'll be worth it, but I don't feel _too_ strongly about it. Having it like this is probably still better than having nothing on IDF.

2022-01-17 21:24 UTC, oxan commented
Looking at the PR itself, do we actually need to rename `mqtt_client.h`? I would expect that `#include <mqtt_client.h>` would always pick the IDF one as our own directory isn't on the bracketed-include search path. It's just a bit ugly to have that one file follow a different naming convention.

2022-01-17 22:23 UTC, flaviut commented
> I would expect that #include <mqtt_client.h> would always pick the IDF one as our own directory isn't on the bracketed-include search path.

I'd find that confusing. C++ has enough weird things and my brain is already full enough that I don't want to remember the difference between `""` and `<>`.

> That helpers implementing our own interface as well though, since it can mostly be a 1:1 translation.
>
> That said, I don't think creating a wrapper interface will be that much work and that it'll be worth it, but I don't feel too strongly about it.

I did some work on @martgras's wrapper PR at https://github.com/flaviut/esphome/tree/mqtt-refactor. I don't think the code there is any better, it still has to deal with differences between the ESP-IDF and Arduino versions. For example, the "rep" parameter, which does nothing for ESP-IDF.

Of the 3 issues I mentioned with the current API, the wrapper is able to fix two. The first one can be fixed with `std::string_view`, but it looks like we're using C++11, so that can't be done.

We also still need to know the concrete type of the MQTT provider. The arduino interface and the ESP-IDF interface use totally different methods of doing MQTTS. Doing a wrapper doesn't save us from that.

But anyway, take a look at the other branch and see what you think of it!

2022-01-20 10:52 UTC, OttoWinter commented
> I would expect that `#include <mqtt_client.h>` would always pick the IDF one as our own directory isn't on the bracketed-include search path.

Unfortunately the `esphome` dirs _are_ included in the bracketed-include search paths as well (see for example generated compile_commands.json). That's an artifact of the weird way we use the build system in repo setup.

2022-01-20 10:55 UTC, OttoWinter commented on esphome/components/mqtt/__init__.py
> +if KEY_CORE in CORE.data and CORE.using_esp_idf:
This is not going to work unfortunately.

It does work when just running `esphome run ...`, but with this the dashboard validation would be broken.

The dashboard validation keeps the modules around after they've been imported (so as to not having to reload them each time you type in a character in the editor, which would make it very slow). But if you switch to another file the modules are still loaded, but with a different config.

So we can't access any `CORE.` values during module loading, only in validation functions because those are re-run every time.

2022-01-20 10:57 UTC, OttoWinter commented on esphome/components/mqtt/__init__.py
> +        cg.add(var.set_skip_cert_cn_check(config[CONF_SKIP_CERT_CN_CHECK]))
This key is optional in the schema. If you only set `CONF_CERTIFICATE_AUTHORITY` in the config but don't set `CONF_SKIP_CERT_CN_CHECK`, it would pass validation but fail with an exception here. Either make it so both have to be set together, or set defaults for this value.

2022-01-20 10:58 UTC, OttoWinter commented on esphome/components/mqtt/__init__.py
> +        cg.add_define("IDF_MQTT_USE_ENQUEUE")
We usually name defines `USE_<COMPONENT_NAME>_<SUFFIX>` to more easily identify them as defines and see where they're from.

2022-01-20 10:59 UTC, OttoWinter commented on esphome/components/mqtt/mqtt_client_base.h
> +class MqttClientBase {
Inconsistent naming, we should either go for `MQTT` or ´Mqtt`, personally I'd be for `MQTT` as that's what we've used in the past too (I think)

2022-01-20 11:02 UTC, OttoWinter commented on esphome/components/mqtt/mqtt_client_idf.cpp
> +        callback((int) event->msg_id);
From what thread is the IDF event handler called? If it's not from the main thread (which I think is the case), then we'd need to post these events into a queue and run the callbacks in the main thread. Otherwise we end up with lots of issues as ESPHome's code expects to be run from a single thread, and there's no synchronization.

2022-01-20 11:12 UTC, martgras commented on esphome/components/mqtt/__init__.py
> +if KEY_CORE in CORE.data and CORE.using_esp_idf:
Can I just remove the check and keep async_tcp in AUTO_LOAD
The only downside is that it's copied to the build  path.  Correct?

2022-01-20 11:19 UTC, OttoWinter commented on esphome/components/mqtt/__init__.py
> +if KEY_CORE in CORE.data and CORE.using_esp_idf:
Not 100% sure, but I think the `async_tcp` component itself validates that it can only be loaded in arduino environments (as the libraries it uses are only compatible with arduino)

2022-01-21 16:05 UTC, martgras commented on esphome/components/mqtt/__init__.py
> +if KEY_CORE in CORE.data and CORE.using_esp_idf:
Moved adding async_tcp to `to_code()`. 
I am not happy hardcoding library versions here  but since `AsyncMqttClient-esphome` is already hardcoded it doesn't make things worse IMHO :)

2022-01-21 16:06 UTC, martgras commented on esphome/components/mqtt/mqtt_client_idf.cpp
> +        callback((int) event->msg_id);
Depends - see https://github.com/espressif/esp-mqtt/blob/b86d42c130ac64a916ce6cf299d99f9756692394/mqtt_client.c#L1565

But I implemented a queue and use a semaphore  for synchronization

2022-01-21 16:07 UTC, martgras commented on esphome/components/mqtt/mqtt_client_idf.cpp
> +  if (this->username_.empty()) {
fixed

2022-01-21 16:07 UTC, martgras commented on esphome/components/mqtt/mqtt_client_idf.cpp
> +      // TODO is there a way to get the disconnect reason?
ok thanks

2022-01-21 16:07 UTC, martgras commented on esphome/components/mqtt/mqtt_client_idf.cpp
> +      if (data_len == 0)
removed it

2022-01-21 23:11 UTC, flaviut commented on esphome/components/mqtt/mqtt_client_idf.h
> +  void set_client_id(const char *client_id) override { this->client_id_ = client_id; }
No big deal, but I used `final` elsewhere to assist the compiler in devirtualizing these method calls.

2022-01-22 10:20 UTC, martgras commented on esphome/components/mqtt/mqtt_client_idf.h
> +  void set_client_id(const char *client_id) override { this->client_id_ = client_id; }
Thanks

2022-01-22 13:49 UTC, oxan commented
> I'd find that confusing. C++ has enough weird things and my brain is already full enough that I don't want to remember the difference between `""` and `<>`.

`<>` is for system libraries and `""` is for our own code. I find that a clearer and more explicit distinction than the filename having an underscore or not.

> Unfortunately the `esphome` dirs _are_ included in the bracketed-include search paths as well (see for example generated compile_commands.json). That's an artifact of the weird way we use the build system in repo setup.

The root directory might be, but I don't think `esphome/components/mqtt` is?

2022-01-22 13:50 UTC, oxan commented on esphome/components/mqtt/__init__.py
> +if KEY_CORE in CORE.data and CORE.using_esp_idf:
It seems like we can remove the explicit AsyncTCP library dependencies as `AsyncMqttClient-esphome` depends on them, so PlatformIO adds them automatically.

2022-01-22 16:32 UTC, oxan reviewed
Looks to be in pretty good shape now, I've just two questions remaining. 

I'm still not happy with the renaming of `mqtt_client.h`, but I'll leave that to @jesserockz to decide.

2022-01-22 16:32 UTC, oxan commented on esphome/components/mqtt/mqtt_backend.h
> +};
This enum seems to be unused, can we delete it?

2022-01-22 16:32 UTC, oxan commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> +    // this->mqtt_cfg_.lwt_qos = this->lwt_qos_;
Should this be commented?

2022-01-22 16:35 UTC, flaviut commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> +  if (this->username_.empty()) {
looks like the not disappeared here again.

2022-01-22 16:37 UTC, martgras commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> +  if (this->username_.empty()) {
:) thanks

2022-01-22 16:38 UTC, martgras commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> +    // this->mqtt_cfg_.lwt_qos = this->lwt_qos_;
fixed

2022-01-22 17:06 UTC, martgras commented
@jesserockz feel free to pick a different name for mqttclient.h/cpp and commit directly . I don't have a strong opinion on the name except that it shouldn't be mqtt_client to avoid the errors / confusion with the mqtt_client.h file from idf

2022-01-22 17:06 UTC, martgras commented on esphome/components/mqtt/mqtt_backend.h
> +};
done

2022-01-28 11:56 UTC, jesserockz approved these changes
Mostly looks good to me.

2022-01-28 11:56 UTC, jesserockz commented on esphome/components/mqtt/mqtt_client.h
> +#endif
Just for consistency
```suggestion
#if defined(USE_ESP_IDF)
#include "mqtt_backend_idf.h"
#elif defined(USE_ARDUINO)
#include "mqtt_backend_arduino.h"
#endif
```

2022-01-28 11:56 UTC, jesserockz commented on esphome/components/mqtt/mqtt_client.h
> +#endif
Same as above
```suggestion
#if defined(USE_ESP_IDF)
  MQTTBackendIDF mqtt_backend_;
#elif defined(USE_ARDUINO)
  MQTTBackendArduino mqtt_backend_;
#endif
```

2022-03-22 22:46 UTC, Bascht74 commented
Hi @martgras, do you have an idea if/when this PR will get merged or what is preventing that?
I am looking forward to use mqtt with esp-idf directly...

Seb

2022-03-25 11:21 UTC, Bascht74 commented
Hi @jesserockz, do you have an idea if/when this PR will get merged or what is preventing that?
I am looking forward to use mqtt with esp-idf directly...

Seb

2022-04-03 23:07 UTC, merged