add get_level() function to float output
OttoWinter/esphomeyaml pull request #2935
Opened 2021-12-21 09:15 UTC by swifty99

# What does this implement/fix? 

Float output entities have a set_level() function naturally. A light component would set output level to get light. 
Now it is almost impossible to know at what exact level the float output actually is. There are gamma conversions, effects and what so ever going on changing the float output.
I would like to maeasure as accurate as possible the power consumption. I know how much power the full on light needs, now I need to know the PWM dimming value. And this can not be calculated reasonably on light control values.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
output:
  - platform: ...
    id: my_output_id

sensor:
  - platform: template
    name: "GetLevel Sensor"
    lambda: |-
      return id(my_output_id).get_level();;
   

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-22 02:33 UTC, jesserockz requested changes
I don't think this is a good idea. Especially since `get_level()` after `set_level(1.0)` might not even return `1.0` based on where you are setting `state_`. 

I think for your use case, you might need to do the calculation using filters or lambdas on template sensors and it does not justify exposing this potentially confusing API on an `output`.

2021-12-22 16:26 UTC, swifty99 commented
Alright, although I disagree. So far I do not see any solution to get the actual power level of for example a light. By power I mean the real electrical power and not some brightness effect reverse calculation vodoo. 

You are right about the excecution order to write state_. Well spotted, I fixed that.

As long as there is no other useful way to get the desired information I pledge to implement this change.

2021-12-22 20:51 UTC, jesserockz commented
Just a thought, you can actually get the gamma corrected values with something like this in a lambda?
```c++
float brightness;
id(light_id).current_values_as_brightness(&brightness);
```

These are the values that are sent to `FloatOutput::write_state(...)`

https://esphome.io/api/classesphome_1_1light_1_1_light_state.html#a889d5be6c6373ded425190fc7be9c34a

2021-12-23 11:41 UTC, swifty99 commented
Thank you for the hint. I did not know this function.

However, it does not solve the problem. Well it does for a simple one channel light, but not for fancier RGB or RGBwhatever light. 
If knowing the actual state of an output is really unwanted, a light could calculate the power itself. To start and play with I still whish to know the actual PWM level of an output.
Maybe we could settle this topic a little. If I am really the only one who thinks to need it, we should forget about it. I have seen quirky code on the search for a solution to come around this not knowing. Mabe there are better ways to get_level(), maybe not.

2022-03-31 02:05 UTC, closed without merging