Add ENS210 Humidity & Temperature sensor component
OttoWinter/esphomeyaml pull request #2942
Opened 2021-12-22 07:33 UTC by itn3rd77

# What does this implement/fix? 

Add initial implementation for the ENS210 relative humidity and temperature i2c sensor

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1745

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example configuration entry
sensor:
  - platform: ens210
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-22 08:57 UTC, itn3rd77 commented
> Hey there @itn3rd77, Thanks for submitting this pull request! Can you add yourself as a codeowner for this integration? This way we can notify you if a bug report for this integration is reported. In `__init__.py` of the integration, please add:
> 
> ```python
> CODEOWNERS = ["@itn3rd77"]
> ```
> 
> And run `script/build_codeowners.py`
> 
> (message by NeedsCodeownersLabel)

Executing `script/build_codeowners.py` results in the following error. Is this broken or maybe I am simply to stupid 😖

```
`
Traceback (most recent call last):
  File "./script/build_codeowners.py", line 7, in <module>
    from esphome.helpers import write_file_if_changed
ModuleNotFoundError: No module named 'esphome'

``

2021-12-22 09:03 UTC, jesserockz commented
@itn3rd77 are you running in a docker container? The docker containers are currently broken.

2021-12-22 09:15 UTC, itn3rd77 commented
> @itn3rd77 are you running in a docker container? The docker containers are currently broken.

Hi Jesse, yes I am running a docker container. Are the any other "simple" options?

2021-12-22 09:22 UTC, jesserockz commented
Try running using an older image - `esphome/esphome:2022.1.0-dev20211220`

2021-12-22 09:44 UTC, jesserockz commented
I actually just repushed the `dev` tag to be in a working state, you will need to `pull` it though

2021-12-22 10:12 UTC, itn3rd77 commented
> I actually just repushed the `dev` tag to be in a working state, you will need to `pull` it though

Ok thanks. But I not able to get this passing. Always getting the result `CODEOWNERS file is not up to date`

2021-12-22 10:34 UTC, jesserockz commented on esphome/components/ens210/sensor.py
> +DEPENDENCIES = ["i2c"]
```suggestion
CODEOWNERS = ["@itn3rd77"]
DEPENDENCIES = ["i2c"]
```

2022-02-06 12:48 UTC, itn3rd77 commented
Hi,

is there anything I might or should do to get this merged?

Thanks and best regards
Ingo

2022-02-07 22:22 UTC, jesserockz requested changes

2022-02-07 22:22 UTC, jesserockz commented on esphome/components/ens210/ens210.cpp
> +  delay(ENS210_SINGLE_MEASURMENT_CONVERSION_TIME_MS);
This should not delay for so long. If you need to wait 130ms then use `set_timeout()` to wrap the rest of this function and create an async callback.

2022-02-07 22:22 UTC, jesserockz commented on esphome/components/ens210/ens210.cpp
> +}
If this is just for logging, take a look at `LogString` (examples are in codebase)

2022-03-27 13:42 UTC, itn3rd77 commented on esphome/components/ens210/ens210.cpp
> +}
Added review comments. Sorry for the long time to resolve.

2022-04-03 20:00 UTC, jesserockz commented on esphome/components/ens210/ens210.cpp
> +    delay(ENS210_SINGLE_MEASURMENT_CONVERSION_TIME_MS);
You still have this big delay here. The `set_timeout` should use `ENS210_SINGLE_MEASURMENT_CONVERSION_TIME_MS` as the delay time, then it can execute without any delays inside it. 
A timeout function is not truly asynchronous, it is just executed later in a future loop by the scheduler.

2022-04-04 08:26 UTC, itn3rd77 commented on esphome/components/ens210/ens210.cpp
> +    delay(ENS210_SINGLE_MEASURMENT_CONVERSION_TIME_MS);
Thanks again for review.

Just to be sure I'll got it right before the next commit. It should look like that, right?

```
  // Wait for measurement to complete
  this->set_timeout("data", uint32_t(ENS210_SINGLE_MEASURMENT_CONVERSION_TIME_MS), [this]() {
    int temperature_data, temperature_status, humidity_data, humidity_status;
    uint8_t data[6];
    uint32_t h_val_data, t_val_data;
    // Set default status for early bail out
    temperature_status = ENS210_STATUS_I2C_ERROR;
    humidity_status = ENS210_STATUS_I2C_ERROR;
    
    # DELETE THE NEXT LINE
    #delay(ENS210_SINGLE_MEASURMENT_CONVERSION_TIME_MS);
```

2022-04-10 23:04 UTC, jesserockz commented on esphome/components/ens210/ens210.cpp
> +    delay(ENS210_SINGLE_MEASURMENT_CONVERSION_TIME_MS);
Sorry for the delayed response, But yes.

`set_timeout` schedules the inner function to be executed `ENS210_SINGLE_MEASURMENT_CONVERSION_TIME_MS` in the future.

2022-04-14 01:10 UTC, jesserockz requested changes

2022-04-14 01:10 UTC, jesserockz commented on esphome/components/ens210/ens210.cpp
> +      this->humidity_sensor_->publish_state(humidity);
```suggestion
      if (this->humidity_sensor_ != nullptr) {
        float humidity = (humidity_data & 0xFFFF) / 512.0;
        this->humidity_sensor_->publish_state(humidity);
      }
```

2022-04-14 01:10 UTC, jesserockz commented on esphome/components/ens210/ens210.cpp
> +      this->temperature_sensor_->publish_state(temperature);
```suggestion
      if (this->temperature_sensor_ != nullptr) {
        float temperature = (temperature_data & 0xFFFF) / 64.0 - 27315L / 100.0;
        this->temperature_sensor_->publish_state(temperature);
      }
```

2022-04-14 06:03 UTC, itn3rd77 commented on esphome/components/ens210/ens210.cpp
> +      this->humidity_sensor_->publish_state(humidity);
👍

2022-04-14 06:03 UTC, itn3rd77 commented on esphome/components/ens210/ens210.cpp
> +      this->temperature_sensor_->publish_state(temperature);
👍

2022-04-14 06:34 UTC, jesserockz approved these changes

2022-05-09 05:23 UTC, merged