Add qr code support for displays
OttoWinter/esphomeyaml pull request #2952
Opened 2021-12-24 23:54 UTC by wjtje

# What does this implement/fix? 

This PR adds support for displaying QR codes on display.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1251

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1748

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
qr_code:
  - id: homepage_qr
    value: https://esphome.io/index.html

display:
  - platform: ...
    lambda: |-
      it.qr_code(0, 0, id(homepage_qr));
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-19 23:02 UTC, jesserockz requested changes

2022-01-19 23:02 UTC, jesserockz commented on esphome/components/qr_code/__init__.py
> +    cg.add_platformio_option("build_unflags", "-fno-exceptions")
Please don't change the build flags of ESPHome. You will need to properly fork and modify the library to not use exceptions.

2022-01-24 03:13 UTC, jesserockz requested changes

2022-01-24 03:13 UTC, jesserockz commented on esphome/components/qr_code/__init__.py
> +    cg.add_library("https://github.com/wjtje/QR-Code-generator-esphome", "1.7.0")
Could you please publish this library on platformio with the version? 
Just so we have an immutable reference instead of a branch/tag on github which can be moved at any time.

2022-01-25 09:38 UTC, oxan requested changes
LGTM otherwise.

2022-01-25 09:38 UTC, oxan commented on esphome/components/qr_code/__init__.py
> +    cg.add_library("wjtje/qr-code-generator-library", "^1.7.0")
Can you add this dependency to `platformio.ini` as well, so that CI will pass?

2022-01-25 15:20 UTC, oxan approved these changes

2022-01-26 09:20 UTC, jesserockz approved these changes

2022-01-26 09:20 UTC, merged