Ipv6 idf
OttoWinter/esphomeyaml pull request #2953
Opened 2021-12-25 14:07 UTC by HeMan

# What does this implement/fix? 

Add IPv6 support for esp-idf framework.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1749

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
wifi:
  enable_ipv6: true
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-02 11:05 UTC, agners requested changes

2022-01-02 11:05 UTC, agners commented on esphome/components/wifi/wifi_component_esp_idf.cpp
> +  return buf;
You can't return `buf` here, buf is on the stack... Use the following to create a copy on the heap.

```suggestion
  return std::string(buf);
```

2022-01-02 11:38 UTC, HeMan commented on esphome/components/wifi/wifi_component_esp_idf.cpp
> +  return buf;
Should I modify the `format_ip4_addr` in the same way?

2022-01-03 11:50 UTC, agners commented on esphome/components/wifi/wifi_component_esp_idf.cpp
> +  return buf;
Uh yes, that seems to be a bug.

2022-01-03 16:32 UTC, oxan commented on esphome/components/wifi/wifi_component_esp_idf.cpp
> +  return buf;
Actually, it works fine because `buf` is a `char*` and the return type is `std::string`, so C++ does a copy initialization using the conversion constructor of `std::string`... but yes, being explicit about it is much better.

2022-01-03 18:18 UTC, agners commented on esphome/components/wifi/wifi_component_esp_idf.cpp
> +  return buf;
Oh I see. Today I learned :smile:

2022-01-04 08:41 UTC, HeMan commented
I don't think my PR enabling IPv6 should contain that change.

2022-01-04 09:58 UTC, oxan requested changes
Can we implement this without a preprocessor define? We generally only use those to limit code size, but that doesn't seem relevant here.

2022-01-04 09:58 UTC, oxan commented on esphome/components/wifi/__init__.py
> +            cv.Optional(CONF_ENABLE_IPV6): cv.boolean,
This seems to only be implemented for ESP-IDF, so it should only be configurable when using IDF:
```suggestion
            cv.SplitDefault(CONF_ENABLE_IPV6, esp32_idf=False): cv.All(cv.only_with_esp_idf, cv.boolean),
```

2022-01-04 09:58 UTC, oxan commented on esphome/components/wifi/__init__.py
> +        )
Use three separate calls here, but I think the CONFIG_LWIP_* flags are better set through sdkconfig instead.

2022-01-04 09:58 UTC, oxan commented on esphome/components/wifi/__init__.py
> +            cg.add_build_flag("-DPIO_FRAMEWORK_ARDUINO_LWIP2_IPV6_LOW_MEMORY")
This is unreachable then.

2022-01-04 12:00 UTC, HeMan commented
> Can we implement this without a preprocessor define? We generally only use those to limit code size, but that doesn't seem relevant here.

It works if I change to always use `AF_INET6` and `sockaddr_in6` in setup, but debug logs show's IPv4 address in an IPv6-format:
```
[12:49:07][D][api:097]: Accepted ::FFFF:C0A8:2B3
[12:49:10][VV][api.socket:796]: ::FFFF:C0A8:2B3: Connection closed
[12:49:10][W][api.connection:082]: ::FFFF:C0A8:2B3: Connection closed
[12:49:10][V][api:109]: Removing connection to ::FFFF:C0A8:2B3
```

2022-01-04 12:16 UTC, oxan commented
Yeah, I think that's fine. We can always add a helper function to format it in traditional IPv4 format if it turns out to be a problem.

2022-01-04 13:29 UTC, HeMan commented
> > Can we implement this without a preprocessor define? We generally only use those to limit code size, but that doesn't seem relevant here.
> 
> It works if I change to always use `AF_INET6` and `sockaddr_in6` in setup, but debug logs show's IPv4 address in an IPv6-format:

Bugger, it didn't work with ESP8266 without IPv6 support.

2022-01-05 11:07 UTC, oxan commented
I've been thinking a bit more about this, and I think we should move the creation of a "wildcard" socket that listens on all addresses to the `socket` component. API is not the only place that creates a socket (see e.g. `ota`), and I don't want to have to put `#ifdef USE_IPV6` conditionals everywhere. Something like this:

```cpp
// functions in socket
std::unique_ptr<Socket> socket_ip(int type, int protocol);
void set_sockaddr_any(struct sockaddr *addr, uint16_t port);

// usage in api
socket_ = socket::socket_ip(SOCK_STREAM, 0);
struct sockaddr_storage addr;
socket::set_sockaddr_any((struct sockaddr *) &addr, this->port_);
socket_->bind((struct sockaddr *) &addr, sizeof(addr));
```
That function can then also properly set `sin6_addr` to `in6addr_any` instead of leaving it empty like it's now.

Furthermore, I think putting the `enable_ipv6` setting under wifi is the wrong choice. Enabling IPv6 is a global property of the TCP/IP stack, not only of the wifi stack. E.g. on ESP32 using ethernet we could also enable IPv6, but the whole wifi component isn't even loaded there. Instead, I think we should put it under the `network` component.

2022-01-05 12:09 UTC, HeMan commented
That looks like a good solution, I think it could also solve what I'm trying to accomplish in https://github.com/esphome/esphome/pull/2977 as well.

I can't find the `network` component, should I put it under core `esphome`?

2022-01-05 13:10 UTC, agners commented
This might be a bit repetitive/you might already know. I just wanted to make sure we agree on terminology and how IPv6 support should be implemented exactly :smile:  

> I've been thinking a bit more about this, and I think we should move the creation of a "wildcard" socket that listens on all addresses to the socket component. API is not the only place that creates a socket (see e.g. ota), and I don't want to have to put #ifdef USE_IPV6 conditionals everywhere. Something like this:

Agreed, if not necessary (and currently there seems to be no reason), I'd try to use dual-stack socket if IPv6 is (compile-time) enabled and use regular IPv4 if not in our socket component, and abstract all away from higher level.

> That function can then also properly set sin6_addr to in6addr_any instead of leaving it empty like it's now.

Afaik, `in6addr_any` is zero anyway, so if the struct was empty, it should be the same. But using it explicitly is nicer of course.

> It works if I change to always use `AF_INET6` and `sockaddr_in6` in setup, but debug logs show's IPv4 address in an IPv6-format:
> 
> ```
> [12:49:07][D][api:097]: Accepted ::FFFF:C0A8:2B3
> [12:49:10][VV][api.socket:796]: ::FFFF:C0A8:2B3: Connection closed
> [12:49:10][W][api.connection:082]: ::FFFF:C0A8:2B3: Connection closed
> [12:49:10][V][api:109]: Removing connection to ::FFFF:C0A8:2B3
> ```
> 
> This will be true if you enable IPv6 but connects via IPv4, but my guess is that people that enables IPv6 could be more used to reading addresses in this format so that it won't be much of a problem.

These are [IPv4-mapped IPv6 addresses](https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses) and make the magic work to use a single socket to communicate with IPv4 and IPv6 clients. Whenever using this addresses, the lower layer make sure to actually generate a IPv4 package (instead of a IPv6).

That said, to avoid confusion, I think we should make sure to format those in IPv4 format when logging, otherwise we will end up with issue reports and whatnot :) LwIP has a macro to detect those: `IP_IS_V4MAPPEDV6`.

2022-01-05 13:39 UTC, oxan commented
> I can't find the `network` component, should I put it under core `esphome`?

There is, see `esphome/components/network`. It doesn't currently have a config schema, but you can add it.

> Agreed, if not necessary (and currently there seems to be no reason), I'd try to use dual-stack socket if IPv6 is (compile-time) enabled and use regular IPv4 if not in our socket component, and abstract all away from higher level.

Yes, agreed, especially on abstracting it away.

> Afaik, `in6addr_any` is zero anyway, so if the struct was empty, it should be the same. But using it explicitly is nicer of course.

Ah yeah, you're right about that, so disregard that comment.

> That said, to avoid confusion, I think we should make sure to format those in IPv4 format when logging, otherwise we will end up with issue reports and whatnot :) LwIP has a macro to detect those: IP_IS_V4MAPPEDV6.

Yeah, agreed. Can be implemented in `std::string Socket::getpeername()`, I think.

2022-01-07 21:36 UTC, agners commented
> > Can we implement this without a preprocessor define? We generally only use those to limit code size, but that doesn't seem relevant here.
> 
> It works if I change to always use `AF_INET6` and `sockaddr_in6` in setup, but debug logs show's IPv4 address in an IPv6-format:

What works? Compiling without IPv6 and use `AF_INET6`? Looking at lwIP, this shouldn't be working

https://github.com/espressif/esp-lwip/blob/2.1.2-esp/src/include/lwip/sockets.h#L81

If it really works, I am actually worried what definition of `AF_INET6` and `sockaddr_in6` we are using :cold_sweat: 

> Can we implement this without a preprocessor define? We generally only use those to limit code size, but that doesn't seem relevant here.

In the last version @HeMan took this a bit too literary I think. @oxan given above findings, I don't think it will be possible entirely without preprocessor defines, I think? I'd say we should limit ifdef's to a generic socket abstraction layer (as you outlined in https://github.com/esphome/esphome/pull/2953#issuecomment-1005591195).

2022-01-08 08:28 UTC, HeMan commented
Just noted that esp-idf is always built with `CONFIG_LWIP_IPV6`, even without my changes. Adding `add_idf_sdkconfig_option("CONFIG_LWIP_IPV6", False)` to mainline will make it fail.

2022-01-08 11:39 UTC, agners commented
> Just noted that esp-idf is always built with `CONFIG_LWIP_IPV6`, even without my changes. Adding `add_idf_sdkconfig_option("CONFIG_LWIP_IPV6", False)` to mainline will make it fail.

Ok, that explains why it works using `AF_INET6`.

I guess the question is if that's the case for all configuration (ESP32 Arduino, ESP8266). If not, we probably still need to have the option.

2022-01-09 17:10 UTC, oxan commented
To be explicit about it, my goals on this topic are three-fold (aside from getting IPv6 working, obviously):
* Keep the behaviour of the BSD socket API as close to the standard as possible. It might not be the best designed API, and deviating from the standard can be convenient, but it's a well-known API with well-known behaviour, and changing that'll only hurt us in the future when it causes unexpected breakage because people don't expect us to behave different from the rest of the world.
* Move as much logic for compatibility with both IPv4 and IPv6 into the socket component, so that all consumers can be kept relatively simple. Where this can't be done using the BSD sockets API, we can add additional wrapper/helper functions.
* If it's possible, I would like to avoid introducing our own preprocessor define for IPv6 support. Using pre-existing defines from IDF/lwIP to check what's available is fine, as long as we can limit it to the socket component.

From that perspective, this PR is fine with me, except that it obviously depends on #3015 to keep working on IPv4, and see my comment there.

2022-01-17 23:00 UTC, oxan requested changes

2022-01-17 23:00 UTC, oxan commented on esphome/components/api/api_server.cpp
> +#endif
Can we move this (and the creation of the socket) into helper functions? We'll need to do this logic for any component support IPv6, and I don't want to have to litter `#ifdef IPV6_ENABLE` over the whole code.

2022-01-17 23:00 UTC, oxan commented on esphome/components/network/__init__.py
> +            cv.GenerateID(): cv.declare_id(NetworkComponent),
This isn't necessary (and incorrect, as there's no class `NetworkComponent` on the C++ side).

2022-01-17 23:00 UTC, oxan commented on esphome/components/network/__init__.py
> +        add_idf_sdkconfig_option("CONFIG_LWIP_IPV6_AUTOCONFIG", True)
We'll probably need to actually define `ENABLE_IPV6` as well... 

Please name it `USE_IPV6` and add it to `esphome/core/defines.h` as well.

2022-01-22 18:54 UTC, oxan approved these changes

2022-01-24 22:32 UTC, jesserockz approved these changes
I don't have ipv6 in my network, but my test device still works if I enable this :tada:

2022-01-25 08:55 UTC, merged

2022-01-25 09:00 UTC, oxan commented
Thanks!