Add new Lock core component
OttoWinter/esphomeyaml pull request #2958
Opened 2021-12-28 06:44 UTC by kbickar

# What does this implement/fix? 
Home Assistant has "[lock](https://www.home-assistant.io/integrations/lock/)" domain which has some differences from other domains like "switch" or "cover" such as extra security restrictions.

For smart locks made with an ESPx, it is useful to have this as a separate component that is then available natively in HomeAssistant

Added a template lock and a generic output lock to go along with it

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/612

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 
esphome/esphome-docs#???
esphome/aioesphomeapi#???

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

output:
  - platform: gpio
    pin: D8
    inverted: true
    id: lockpin
    
lock:
 - platform: output
   output: lockpin
   name: Test Lock

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2021-12-31 10:43 UTC, jesserockz commented on docker/Dockerfile
> -        python3=3.9.2-3 \
Please remove the Dockerfile changes from the PR

2022-01-01 17:40 UTC, kbickar commented
Just a note on the new modes I added -
HomeAssistant internally has support for lock states other than LOCKED/UNLOCKED, however the MQTT component does not

2022-01-03 16:24 UTC, oxan requested changes
Thanks for working on this! 

Don't let me comments discourage you, overall it looks fairly good, but I like to get new platforms like this right the first time, since changing them later is often painful for both us and our users.

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/__init__.py
> +        cv.Optional(CONF_INVERTED): cv.boolean,
This doesn't seem to be used.

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/__init__.py
> +@automation.register_action("lock.open", OpenAction, LOCK_ACTION_SCHEMA)
Implementation missing.

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/automation.cpp
> +}  // namespace esphome
This file can be left out.

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/automation.h
> +    return false;
This is dead code, a bool has just two possible values :) I would either drop the second if (and maybe invert the order then), or do something like this:
```c++
    auto check_state = this->state_ ? LockState::LOCK_STATE_LOCKED : LockState::LOCK_STATE_UNLOCKED;
    return this->parent_->state == check_state;
```

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/lock.cpp
> +  ESP_LOGD(TAG, "'%s' LOCKING.", this->get_name().c_str());
```suggestion
  ESP_LOGD(TAG, "'%s' Locking.", this->get_name().c_str());
```

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/lock.cpp
> +  ESP_LOGD(TAG, "'%s' UNLOCKING.", this->get_name().c_str());
```suggestion
  ESP_LOGD(TAG, "'%s' Unlocking.", this->get_name().c_str());
```

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/lock.cpp
> +    ESP_LOGD(TAG, "'%s' Does not support Open.", this->get_name().c_str());
```suggestion
    ESP_LOGW(TAG, "'%s' Does not support Open.", this->get_name().c_str());
```

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/lock.cpp
> +uint32_t Lock::hash_base() { return 3129890955UL; }
This should be a different number from the one used for switches.

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/lock.h
> +   * The input value is inverted if applicable. Then the internal value member is set and
Inapplicable comment.

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/lock.h
> +  bool requires_code{false};
We don't implement these kind of static properties with a public member, since those are writable for everyone. Instead, we use a traits object, which also allows us to more cleanly add additional properties later on. See e.g. how the `number` component handles the min/max value.

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/lock.h
> +  virtual bool assumed_state();
This should also be in the traits.

2022-01-03 16:24 UTC, oxan commented on esphome/components/mqtt/mqtt_lock.cpp
> +    }
Braces for all or none of the branches, please (I should add a CI check to catch that).

2022-01-03 16:24 UTC, oxan commented on esphome/core/controller.h
> +#endif
I'd like a state parameter here for consistency.

2022-01-03 16:24 UTC, oxan commented on esphome/components/lock/lock.cpp
> +}
The reason we have the `LogString` machinery is so that strings that are only used for logging can be stored in flash instead of in valuable RAM. However, if we then include a second copy of those strings in RAM, that didn't gain us anything. Initially I suggested to just drop the non-LogString version, but I see it's being used for MQTT. Eventually I want to create a proper `FlashString` class that allows conversion to `std::string` for that, but for now just drop the `LogString` version.

Please change the return type to `const char *` though, creating a `std::string` here is unnecessary most of the time.

2022-01-03 16:24 UTC, oxan commented on docker/Dockerfile
> +    /var/lib/apt/lists/*
Please remove the unrelated whitespace changes to this file.

2022-01-03 16:24 UTC, oxan commented on esphome/components/api/api.proto
> +  LockState  state = 2;
```suggestion
  LockState state = 2;
```

2022-01-03 16:24 UTC, oxan commented on esphome/components/api/api.proto
> +  string code_format = 11;
These don't seem to be set anywhere?

2022-01-04 01:05 UTC, kbickar commented on esphome/components/lock/automation.h
> +    return false;
That's a bit clearer of a way to do it

2022-01-04 01:19 UTC, kbickar commented on esphome/components/api/api.proto
> +  string code_format = 11;
Added `supports_open` to api_connection.cpp. The other two are there to match the API that @jesserockz used in esphome/aioesphomeapi#158

2022-01-04 01:26 UTC, kbickar commented on esphome/core/controller.h
> +#endif
It's a bit of a pain to use the state there since it's not a native type.  It's consistent with fan, light, cover, and climate.  Seems to be a bit of a redundant parameter as it just uses the state of the object for the others

2022-01-04 03:08 UTC, kbickar commented on esphome/components/lock/automation.cpp
> +}  // namespace esphome
The compiler is requiring it

2022-01-04 03:08 UTC, kbickar commented on esphome/components/lock/__init__.py
> +@automation.register_action("lock.open", OpenAction, LOCK_ACTION_SCHEMA)
Are the implementations not in automation.h?  They seem to work

2022-01-04 10:34 UTC, oxan commented on esphome/components/lock/__init__.py
> +@automation.register_action("lock.open", OpenAction, LOCK_ACTION_SCHEMA)
The Python function to convert these to code is missing. Right now it uses `lock_is_on_to_code`, since that's the function these decorators are on, but that one doesn't work, as it gets an extra constructor parameter.

2022-01-04 10:34 UTC, oxan commented on esphome/components/lock/automation.cpp
> +}  // namespace esphome
What do you mean?

2022-01-04 10:35 UTC, oxan commented on esphome/core/controller.h
> +#endif
I don't see why having `LockState` here would be problematic, but good point about the others also missing it.

2022-01-04 10:36 UTC, oxan commented on esphome/components/api/api.proto
> +  string code_format = 11;
Ah, okay. As long as they aren't implemented, they can be removed imo, but let's at least add a comment that they aren't used yet.

2022-01-05 20:25 UTC, kbickar commented on esphome/components/lock/automation.cpp
> +}  // namespace esphome
Disregard, was just still listed in the git cache

2022-01-06 17:01 UTC, oxan requested changes
Looks pretty good overall, just some minor mistakes I spotted.

2022-01-06 17:01 UTC, oxan commented on esphome/components/lock/__init__.py
> +icon = cv.icon
This is unused.

2022-01-06 17:01 UTC, oxan commented on esphome/components/lock/__init__.py
> +    for conf in config.get(CONF_ON_OPEN, []):
The config option for this doesn't actually seem to exist.

2022-01-06 17:01 UTC, oxan commented on esphome/components/lock/lock.h
> +   */
Wild comment.

2022-01-06 17:01 UTC, oxan commented on esphome/components/template/lock/__init__.py
> +            "Either optimistic mode must be enabled, or turn_on_action and turn_off_action must be set, "
```suggestion
            "Either optimistic mode must be enabled, or lock_action and unlock_action must be set, "
```

2022-01-19 01:06 UTC, jchang10 commented
I hope the powers that be can get this thru. I am surprised that "lock" is not supported by esphome at this time already. Great work so far! Let's hope this gets done soon!

2022-01-19 22:54 UTC, jesserockz requested changes
I feel like even though it will be very simple now, I would like there to be a `LockCall` similar to the other components, which is called from actions, api/mqtt commands etc and does validation (future for when `code` is supported)

The rest of the code looks good to me.

2022-01-19 22:54 UTC, jesserockz commented on esphome/components/api/api_connection.cpp
> +  resp.state = (enums::LockState) state;
To be consistent with other code in here
```suggestion
  resp.state = static_cast<enums::LockState>(state);
```

2022-01-29 20:27 UTC, kbickar commented
> I feel like even though it will be very simple now, I would like there to be a `LockCall` similar to the other components, which is called from actions, api/mqtt commands etc and does validation (future for when `code` is supported)

@jesserockz , I updated it with LockCall and changed the `write_state()` to `control()` since it doesn't really make sense to require both

2022-01-31 01:48 UTC, jesserockz approved these changes

2022-01-31 02:14 UTC, jesserockz requested changes
Actually one thing I missed and noticed while reading the docs PR

2022-01-31 02:14 UTC, jesserockz commented on esphome/components/template/lock/__init__.py
> +            cv.Required(CONF_STATE): cv.templatable(LockState),
```suggestion
            cv.Required(CONF_STATE): cv.templatable(validate_lock_state),
```

2022-01-31 02:14 UTC, jesserockz commented on esphome/components/template/lock/__init__.py
> +
```suggestion

LOCK_STATES = {
    "LOCKED": LockState.LOCK_STATE_LOCKED,
    "UNLOCKED": LockState.LOCK_STATE_UNLOCKED,
    "JAMMED": LockState.LOCK_STATE_JAMMED,
    "LOCKING": LockState.LOCK_STATE_LOCKING,
    "UNLOCKING": LockState.LOCK_STATE_UNLOCKING,
}

validate_lock_state = cv.enum(LOCK_STATES, upper=True)
```

2022-01-31 08:23 UTC, OttoWinter commented on esphome/components/lock/lock.cpp
> +  ESP_LOGD(TAG, "'%s' Locking.", this->get_name().c_str());
This debug log should be in LockCall::perform instead, as otherwise we'd have inconsistent logging if the call executed by manually creating a LockCall

2022-01-31 08:23 UTC, OttoWinter commented on esphome/components/template/lock/template_lock.h
> +using namespace esphome::lock;
We shouldn't have using namespace in header files, as now the lock namespace gets included in the template_ namespace for all files that include this file, but it really is more of an implementation detail.

2022-01-31 17:15 UTC, kbickar commented on esphome/components/template/lock/template_lock.h
> +using namespace esphome::lock;
It allows templates with lambda statements like `return LOCK_STATE_LOCKED;` which is a little more user friendly.  I wasn't able to see how to include that namespace there otherwise

2022-02-01 19:04 UTC, jesserockz commented on esphome/components/template/lock/template_lock.h
> +using namespace esphome::lock;
All platform components add their namespace with `cg.add_global(lock_ns.using)` in the `to_code` function.

https://github.com/esphome/esphome/pull/2958/files#diff-d195c5a59ace2a6f8e8ecfa2666f71deda7c37b06330e27d6259f5602ec4b53aR99-R102

2022-02-02 02:06 UTC, kbickar commented on esphome/components/template/lock/template_lock.h
> +using namespace esphome::lock;
If I remove that line then it doesn't seem to work though

2022-02-02 23:50 UTC, jesserockz commented on esphome/components/template/lock/template_lock.h
> +using namespace esphome::lock;
Ah, move it to `template_lock.cpp` (See `template_cover.cpp`)

2022-02-03 03:16 UTC, jesserockz requested changes
One last change sorry =)

2022-02-03 03:16 UTC, jesserockz commented on esphome/components/template/lock/template_lock.cpp
> +    this->publish_state(LOCK_STATE_UNLOCKED);
I don't think triggering an open should publish the state? 
If the door is locked and you try open it, it doesn't try to unlock, and there is no logic preventing the lock from trying to open while locked. So I think just remove these lines. There doesn't need to be feedback for the `opening` of a lock as it is just a side function. 
```suggestion
```

2022-02-03 03:44 UTC, kbickar commented on esphome/components/template/lock/template_lock.cpp
> +    this->publish_state(LOCK_STATE_UNLOCKED);
That part I just added to be consistent with the HA MQTT component: https://www.home-assistant.io/integrations/lock.mqtt/

> If the lock is in optimistic mode, it will change states to unlocked when handling the open command.

2022-02-03 03:57 UTC, jesserockz approved these changes

2022-02-03 18:24 UTC, merged