Make IPv6-binds bind on IPv4 as well.
OttoWinter/esphomeyaml pull request #3015
Opened 2022-01-06 22:24 UTC by HeMan

# What does this implement/fix? 
- Change ip.type from IPADDR_TYPE_V6 to IPADDR_TYPE_ANY so that it binds
  to both IPv6 and IPv4.
- Fix checks for address sizes.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-06 23:06 UTC, HeMan commented
I'm not sure the check for addrlen needs to be there. Can't really figure out when it could happen.

2022-01-07 21:58 UTC, agners commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
> +    if ((family != AF_INET) && (family != AF_INET6)) {
`AF_INET6` is only defined when `LWIP_IPV6` is set, so I think the previous code was correct here, see https://github.com/espressif/esp-lwip/blob/2.1.2-esp/src/include/lwip/sockets.h#L240

2022-01-08 08:11 UTC, HeMan commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
> +    if ((family != AF_INET) && (family != AF_INET6)) {
Looks like it's `AF_UNSPEC` but I see your point.

2022-01-09 17:35 UTC, oxan commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
>      ip.addr = addr4->sin_addr.s_addr;
This won't work. If you set `family` to `AF_INET6`, you should pass a `sockaddr_in6` as `name`, and this code treats it as a `sockaddr_in`, which has an incompatible layout. Furthermore, by doing this, `getpeername` and `getsockname` also return IPv4 addresses for a socket opened with `AF_INET6`, which isn't how these functions usually behave. 

I think we just shouldn't open an IPv4 socket when the user explicitly requests an IPv6 socket. We can add an helper functtion that creates an IPv4 or IPv6 socket depending on what's available for users that don't care which type of socket they get.

2022-01-09 17:35 UTC, oxan commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
> +      ip.type = IPADDR_TYPE_ANY;
Similarly, I would think that this could also result in actual IPv4 addresses (instead of IPv6-mapped IPv4-addresses) being returned for an IPv6 connection, but I haven't tested that.

2022-01-09 17:35 UTC, oxan commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
> +      if (addrlen != sizeof(sockaddr_in)) {
I prefer to keep this less-than check, so that if you use struct sockaddr_storage you can pass its length, instead of having to determine which type of address is stashed in it and using the appropriate size.

2022-01-12 12:08 UTC, HeMan commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
> +      ip.type = IPADDR_TYPE_ANY;
Added IPv6-support to getpeername and getsockname which solves this.

2022-01-12 15:27 UTC, oxan requested changes

2022-01-12 15:27 UTC, oxan commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
> +    if (family == AF_INET) {
This isn't correct, it should use the family of the socket, not that of `name` (which is only an output parameter, so it won't be initialized).

2022-01-12 15:27 UTC, oxan commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
> +      inet6_addr_from_ip6addr(&addr->sin6_addr, ip_2_ip6(&pcb_->remote_ip));
`ip_2_ip6` is a macro that only reads the IPv6 address field from the `ip_addr` struct, but it doesn't do any checking or conversions, so this assumes that `pcb_->remote_ip` will always be a IPv6 address. I'm still not convinced that's correct, given that for `AF_INET6` sockets we never tell lwIP that we want IPv6 addresses. Did you test whether this works properly for IPv4 connections to IPv6 sockets?

2022-01-12 15:27 UTC, oxan commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
> +    if (family == AF_INET) {
Same issue here, this should use the family of the socket instead.

2022-01-12 20:25 UTC, HeMan commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
> +      inet6_addr_from_ip6addr(&addr->sin6_addr, ip_2_ip6(&pcb_->remote_ip));
I tested with both IPv6 and IPv4 connections to the socket that have AF_INET6 and it works. I also tested to leave one connection open and connect via the other type and it also works.

2022-01-17 22:56 UTC, oxan approved these changes

2022-01-18 09:36 UTC, agners commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
>      return 0;
You should return what `ip2sockaddr_` returns:

```suggestion
    return this->ip2sockaddr_(&pcb_->local_ip, pcb_->local_port, name, addrlen);
```

2022-01-18 09:36 UTC, agners commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
>      return 0;
Same here

```suggestion
    return this->ip2sockaddr_(&pcb_->local_ip, pcb_->local_port, name, addrlen);
```

2022-01-18 09:36 UTC, agners commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
>      return std::string(buffer);
Probably a bit theoretical, but we should not leak buffer if not used, e.g.:

```suggestion
    char buffer[50];
    if (IP_IS_V4_VAL(pcb_->remote_ip)) {
      inet_ntoa_r(pcb_->remote_ip, buffer, sizeof(buffer));
      return std::string(buffer);
    }
#if LWIP_IPV6
    else if (IP_IS_V6_VAL(pcb_->remote_ip)) {
      inet6_ntoa_r(pcb_->remote_ip, buffer, sizeof(buffer));
      return std::string(buffer);
    }
#endif
    return nullptr;
```

2022-01-18 09:37 UTC, agners commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
>      return std::string(buffer);
Or maybe an empty string? Thoughts @oxan ?

2022-01-18 11:24 UTC, oxan commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
>      return 0;
Yes, good catch, I forgot to change that when I moved the `addrlen` validation to `ip2sockaddr_`.

2022-01-18 11:27 UTC, oxan commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
>      return std::string(buffer);
I don't see how this can actually trigger until we get IPv8 (and ESP8266's will be obsolete long before that happens), but it should be an empty string, as `nullptr` won't even compile since we're returning `std::string` by value.

2022-01-19 09:32 UTC, agners commented on esphome/components/socket/lwip_raw_tcp_impl.cpp
>      return std::string(buffer);
Maybe just:

```suggestion
    char buffer[50] = {};
    if (IP_IS_V4_VAL(pcb_->remote_ip)) {
      inet_ntoa_r(pcb_->remote_ip, buffer, sizeof(buffer));
    }
#if LWIP_IPV6
    else if (IP_IS_V6_VAL(pcb_->remote_ip)) {
      inet6_ntoa_r(pcb_->remote_ip, buffer, sizeof(buffer));
    }
#endif
    return std::string(buffer);
```

2022-01-19 21:05 UTC, agners approved these changes

2022-01-21 09:08 UTC, merged