Wake on lan legacy
OttoWinter/esphomeyaml pull request #3030
Opened 2022-01-10 11:25 UTC by willwill2will54

# What does this implement/fix? 

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** [implements feature request 126 (kinda)](https://github.com/esphome/feature-requests/issues/126)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1775

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF (n/a)
- [ ] ESP8266 (I need someone else to make sure that this works)

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: wol-esp

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "e933df78ec0367a9403d0a95e99bf5c2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wol-Esp Fallback Hotspot"
    password: "4yIZT0HlHsVR"

captive_portal:

button:
  - platform: wake_on_lan
    target_mac_address: E9:48:B8:CA:58:A1
    name: SomeServer
    id: some_server

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      mode:
        pulldown: true
        input: true
    name: "Pin 27"
    on_press:
      - button.press:
          id: some_server
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-12 01:49 UTC, jesserockz requested changes
You need to add `cv.only_with_arduino` as an extra validator on the component

Also needs to be added to a test file

2022-01-12 01:49 UTC, jesserockz commented on esphome/components/wake_on_lan/button.py
> +    cv.ENTITY_BASE_SCHEMA.extend(button.BUTTON_SCHEMA)
The BUTTON_SCHEMA already extends ENTITY_BASE_SCHEMA
```suggestion
    button.BUTTON_SCHEMA
```

2022-01-14 09:34 UTC, willwill2will54 commented
> You need to add `cv.only_with_arduino` as an extra validator on the component
> 
> 
> 
> Also needs to be added to a test file

@jesserockz I have implemented your changes. Could you re-review.

2022-01-16 06:33 UTC, jesserockz requested changes
Can you also add the yaml to `tests/test3.yaml`, which tests for compile errors and accidental configuration breakages down the line.

2022-01-16 06:33 UTC, jesserockz commented on esphome/components/wake_on_lan/button.py
> +DEPENDENCIES = ["wifi"]
In case someone uses ethernet instead of wifi
```suggestion
DEPENDENCIES = ["network"]
```

2022-01-16 06:33 UTC, jesserockz commented on esphome/components/wake_on_lan/wake_on_lan.cpp
> +    uint8_t prefix[6] = {255, 255, 255, 255, 255, 255};
better as a static const?

2022-01-16 06:33 UTC, jesserockz commented on esphome/components/wake_on_lan/wake_on_lan.h
> +  uint8_t macaddr_[6] = {0, 0, 0, 0, 0};
```suggestion
  uint8_t macaddr_[6];
```

2022-01-19 12:51 UTC, willwill2will54 commented on esphome/components/wake_on_lan/wake_on_lan.cpp
> +    uint8_t prefix[6] = {255, 255, 255, 255, 255, 255};
done

2022-01-21 03:26 UTC, jesserockz requested changes
Some minor changes, otherwise good to go.

2022-01-21 03:26 UTC, jesserockz commented on esphome/components/wake_on_lan/wake_on_lan.cpp
> +  ESP_LOGCONFIG(TAG, "wake_on_lan:");
```suggestion
  LOG_BUTTON("", "Wake on LAN Button", this);
```

2022-01-21 03:26 UTC, jesserockz commented on esphome/components/wake_on_lan/wake_on_lan.cpp
> +  ESP_LOGI(TAG, "Sending Wake On Lan Packet...");
```suggestion
  ESP_LOGI(TAG, "Sending Wake On LAN Packet...");
```

2022-01-21 03:26 UTC, jesserockz commented on esphome/components/wake_on_lan/wake_on_lan.cpp
> +    ESP_LOGE(TAG, "Sending Wake On Lan Packet Failed!");
```suggestion
    ESP_LOGE(TAG, "Sending Wake On LAN Packet Failed!");
```

2022-01-22 11:12 UTC, jesserockz approved these changes

2022-01-22 11:13 UTC, merged