Add USB_CDC logger option for esp-idf platform.
OttoWinter/esphomeyaml pull request #3049
Opened 2022-01-14 07:48 UTC by unaiur

# What does this implement/fix? 

ESP32S2 and ESP32C3 have a builtin USB controller that
can be used for logging.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [*] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>
https://github.com/esphome/feature-requests/issues/1598

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [*] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
esphome:
  name: test-logger

external_components:
  - source:
      type: local
      path: esphome/esphome/components
    components: [ logger ]

esp32:
  board: featheresp32-s2
  framework:
    type: esp-idf
    version: recommended

# Enable logging
logger:
  level: VERY_VERBOSE
  hardware_uart: USB_CDC

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "TestWifi"
  password: "***"

sensor:
  - platform: uptime
    name: Uptime Sensor
```

## Checklist:
  - [*] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [PENDING] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-16 06:57 UTC, jesserockz commented
From what I have seen, and tried locally, the C3 doesnt use this flag, and only supports the `CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG` flag, which also is only in idf master branch, not in any released version.
Happy to have this though if you restrict to the S2.

2022-01-16 12:39 UTC, unaiur commented
> From what I have seen, and tried locally, the C3 doesnt use this flag, and only supports the `CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG` flag, which also is only in idf master branch, not in any released version.
> Happy to have this though if you restrict to the S2.

I only tested it with an ESP32S2, so I was not aware if the required functionality is also available in ESP32C3. I assumed that, since C3 also has integrated USB support, it was the same that S2. But it seems that C3 has a reduced and incompatible feature set. Therefore, and since I do not have C3 hardware to test, I have ensured the USB_CDC is only enabled for S2.

2022-01-16 21:45 UTC, oxan requested changes

2022-01-16 21:45 UTC, oxan commented on esphome/components/logger/logger.cpp
> +#else
Can we make this depend on the actual configuration setting instead of the feature define? If we do it like this, when some other component or the user enables this config setting, the logger will use it too, even if the logger is explicitly configured to use an UART.

2022-01-16 21:46 UTC, oxan requested changes

2022-01-16 21:46 UTC, oxan commented on esphome/components/logger/__init__.py
> +            raise EsphomeError("USB_CDC is only supported in esp-idf platform.")
This should be checked in the config validator instead.

2022-01-20 08:28 UTC, unaiur commented
I am awaiting for a esp32 board I order some weeks ago and should arrive today to perform tests in all major platforms (esp8266, esp32s2) in addition to esp32s2.

2022-01-20 21:13 UTC, rbray89 commented
So I have a vested interest in this :)

I'm looking at implementing something similar but for the HOST version of this (https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/cdc/cdc_acm_host && https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/cdc/common/cdc_acm_host)

I'm currently exploring options for different ways to implement this and would love to discuss it further.

2022-01-22 17:28 UTC, unaiur commented
After thinking about it, I think this proposal mixes two different things:
- Writing logs to stdout 
- Configure ESP-IDF to redirect stdout to the USB CDC device

I think that we should instead add the first option (write logs to stdout) and configure stdout using the facilities that already exists.

I will cancel this proposal.

2022-01-22 18:12 UTC, closed without merging