Pvvx mithermometer add reed switch
OttoWinter/esphomeyaml pull request #3050
Opened 2022-01-14 14:58 UTC by penright

# What does this implement/fix? 
Exposes what Pvvx calls a "reed_switch. This is exposed via soldering wires to pin on the back of a LYWSD03MMC.
Documents Pull Request: Pvvx mi add reed switch #1801Pvvx mi add reed switch #1801

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

    reed_switch:
      name: 'PVVX Reed-Switch'
```yaml
# Example config.yaml
  - platform: atc_mithermometer
    mac_address: 'A4:C1:38:4E:16:78'
    temperature:
      name: 'ATC Temperature'
    humidity:
      name: 'ATC Humidity'
    battery_level:
      name: 'ATC Battery-Level'
    battery_voltage:
      name: 'ATC Battery-Voltage'
  - platform: pvvx_mithermometer
    mac_address: 'A4:C1:38:4E:16:78'
    temperature:
      name: 'PVVX Temperature'
    humidity:
      name: 'PVVX Humidity'
    battery_level:
      name: 'PVVX Battery-Level'
    battery_voltage:
      name: 'PVVX Battery-Voltage'
    reed_switch:
      name: 'PVVX Reed-Switch'
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-16 07:27 UTC, jesserockz reviewed
The only issue I have with this is naming it `reed_switch` when technically it is just a binary flag that could be any open/close circuit on `P8` - `GND`

2022-01-16 07:27 UTC, jesserockz commented on .devcontainer/devcontainer.json
> +  "xaver.clang-format"
Why did you add this? VSCode with the cpptools extension will do clang-formatting of the files on save.

2022-01-16 17:53 UTC, pasiz requested changes
I see no point of logging complete flag value that consist of 5 bits.
Also datatype is changed from uint_8t to int, still pvvx code hasn't changed...

Please correct those.

2022-01-16 17:53 UTC, pasiz commented on esphome/components/pvvx_mithermometer/pvvx_mithermometer.cpp
> -  int         flags;          // details below     [14]
Any reason to integer for 5 bits?
pvvx git shows type of uint_8t, why change comment to integer for flags?

Payload contains byte, not integer. Please check your commenting.

https://github.com/pvvx/ATC_MiThermometer

```
uint8_t     flags;  // GPIO_TRG pin (marking "reset" on circuit board) flags: 
                    // bit0: Reed Switch, input
                    // bit1: GPIO_TRG pin output value (pull Up/Down)
                    // bit2: Output GPIO_TRG pin is controlled according to the set parameters
                    // bit3: Temperature trigger event
                    // bit4: Humidity trigger event
```

2022-01-16 17:53 UTC, pasiz commented on .devcontainer/devcontainer.json
> +  "xaver.clang-format"
Cannot understand that too

2022-01-16 17:53 UTC, pasiz commented on esphome/components/pvvx_mithermometer/pvvx_mithermometer.cpp
> +  LOG_SENSOR("  ", "Flag Value", this->flag_value_);
What improvement homeassistant should have on flag value? Could you elaborate how user would use flag value on esphome log side?

2022-01-16 17:53 UTC, pasiz commented on esphome/components/pvvx_mithermometer/pvvx_mithermometer.cpp
> +      this->flag_value_->publish_state(*res->flag_value);
Same, where we need flag value what consists bits. How this is going to help on esphome

2022-01-16 17:53 UTC, pasiz commented on esphome/components/pvvx_mithermometer/pvvx_mithermometer.h
> +  void set_flag_value(sensor::Sensor *flag_value) { flag_value_ = flag_value; }
Read comments before...

2022-01-17 13:35 UTC, penright commented on .devcontainer/devcontainer.json
> +  "xaver.clang-format"
> The only issue I have with this is naming it `reed_switch` when technically it is just a binary flag that could be any open/close circuit on `P8` - `GND`
I struggle with that name for all the reasons mentioned. The only reason I picked it, is because that is what Victor (pvvx) called it in his documentation. https://github.com/pvvx/ATC_MiThermometer#reed-switch-on-gpio-pa6-label-on-the-p8-pin Should we call it Pin8, P8, p8_gnd, or something else?



> Why did you add this? VSCode with the cpptools extension will do clang-formatting of the files on save.
> Cannot understand that too
That is my inexperience with git. I was using Xaver's Clang-Format and could not get it to work. To find the issues I had to use notepad and then recommit. So that is why I was saying that. What is the exact extension that does clan-format on save?

2022-01-17 13:39 UTC, penright commented on esphome/components/pvvx_mithermometer/pvvx_mithermometer.cpp
> -  int         flags;          // details below     [14]
> Any reason to integer for 5 bits? pvvx git shows type of uint_8t, why change comment to integer for flags?
> 
> Payload contains byte, not integer. Please check your commenting.
That was just how I got it to work, I assume it should work as unit8_t. I will test that and make that change.

2022-01-17 13:43 UTC, penright commented on esphome/components/pvvx_mithermometer/pvvx_mithermometer.cpp
> +  LOG_SENSOR("  ", "Flag Value", this->flag_value_);
I think the .devcontainer was changed when I was trying to get clang-format working. I will put that back.


> What improvement homeassistant should have on flag value? Could you elaborate how user would use flag value on esphome log side?
Only debugging. If there is no value I can remove it from the sensor, should I leave it on debugging?
Should I remove the flag sensor altogether?

2022-01-17 13:45 UTC, penright commented on esphome/components/pvvx_mithermometer/pvvx_mithermometer.h
> +  void set_flag_value(sensor::Sensor *flag_value) { flag_value_ = flag_value; }
Answered above. Thank you and Jesse for all the input. I am new and want to learn a good pull request form. :-)

2022-01-17 19:58 UTC, jesserockz commented on .devcontainer/devcontainer.json
> +  "xaver.clang-format"
The `ms-vscode.cpptools` that is already installed and configured will format.

I think maybe `p8_gnd`?

2022-01-19 13:37 UTC, penright commented
I thought there may have been an issue, but it turned out I had another board that was intercepting the wi-fi and keeping HA from connecting to the API. I thought it was strange that I broke something with just the change I did. It ran all night and was still updating HA within expectations (the BLE advertisements timing)

2022-01-20 06:06 UTC, pasiz commented on esphome/components/pvvx_mithermometer/pvvx_mithermometer.cpp
> -  int         flags;          // details below     [14]
So you cannot get something work with specification given? And that is just ok if you can get it work differently somehow. On data payloads I suggest keeping strict on specification given, if not working as described, please pr victor (pvvx firmware maintainer)

2022-01-20 13:20 UTC, penright commented on esphome/components/pvvx_mithermometer/pvvx_mithermometer.cpp
> -  int         flags;          // details below     [14]
> So you cannot get something work with specification given?

I should have said, that was how I found to make it work. IOW after searching, that was the example and it worked. I did make the change to unit8_t.  And as I was typing this I was going to include the code snippet for you, I notice that I missed where I was converting the data[14]. I just fixed it and committed it. Good catch. Thanks.

`  /*
  All data little endian
  uint8_t     size;   // = 19
  uint8_t     uid;    // = 0x16, 16-bit UUID
  uint16_t    UUID;   // = 0x181A, GATT Service 0x181A Environmental Sensing
  uint8_t     MAC[6]; // [0] - lo, .. [5] - hi digits
  int16_t     temperature;    // x 0.01 degree     [6,7]
  uint16_t    humidity;       // x 0.01 %          [8,9]
  uint16_t    battery_mv;     // mV                [10,11]
  uint8_t     battery_level;  // 0..100 %          [12]
  uint8_t     counter;        // measurement count [13]
  unit8_t     flags;          // details below     [14]
                              // flags bit0: Reed Switch, input
                              // flags bit1: GPIO_TRG pin output value (pull Up/Down)
                              // flags bit2: Output GPIO_TRG pin is controlled according to the set parameters
                              // flags bit3: Temperature trigger event
                              // flags bit4: Humidity trigger event
  */

  const uint8_t *data = message.data();
  const int data_length = 15;

  if (message.size() != data_length) {
    ESP_LOGVV(TAG, "parse_message(): payload has wrong size (%d)!", message.size());
    return false;
  }

  // int16_t     temperature;    // x 0.01 degree     [6,7]
  const int16_t temperature = int16_t(data[6]) | (int16_t(data[7]) << 8);
  result.temperature = temperature / 1.0e2f;

  // uint16_t    humidity;       // x 0.01 %          [8,9]
  const int16_t humidity = uint16_t(data[8]) | (uint16_t(data[9]) << 8);
  result.humidity = humidity / 1.0e2f;

  // uint16_t    battery_mv;     // mV                [10,11]
  const int16_t battery_voltage = uint16_t(data[10]) | (uint16_t(data[11]) << 8);
  result.battery_voltage = battery_voltage / 1.0e3f;

  // uint8_t     battery_level;  // 0..100 %          [12]
  result.battery_level = uint8_t(data[12]);

  // int         flag_value      //                   [14]
  result.flag_value = uint8_t(data[14]);

  // Checking bit 0 on flag byte [14]
  result.p8_gnd = uint8_t(data[14]) & 1;
  return true;
}
`

2022-03-18 15:05 UTC, glmnet commented on esphome/components/pvvx_mithermometer/pvvx_mithermometer.cpp
> +                              // flags bit0: Reed Switch, input
```suggestion
                              // flags bit0: p8, input
```

2022-08-16 00:47 UTC, closed without merging