Perform merges when substituting dict keys
OttoWinter/esphomeyaml pull request #3062
Opened 2022-01-17 09:35 UTC by joshuaspence

# What does this implement/fix? 

Substitutions are performed on `dict` keys but destructively.

I have many Shelly devices and I created `output1` and `output2` packages that are included depending on which Shelly device is being used. When using substitutions in the keys of the `output1` and `output2` packages, I end up with less components than I am expecting due to this current behaviour.

I can explain my use case a bit more if it helps, but I managed to produce a minimal configuration to reproduce the problem (see below).

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
---
substitutions:
  a_component: 'switch'
  a_platform: 'output'
  b_component: 'switch'
  b_platform: 'output'

packages:
  a:
    ${a_component}:
      - platform: '${a_platform}'
        output: 'output1'
        name: 'Output 1'
  b:
    ${b_component}:
      - platform: '${b_platform}'
        output: 'output2'
        name: 'Output 2'

esphome:
  name: 'test'
  platform: 'ESP8266'
  board: 'esp01_1m'

output:
  - platform: 'gpio'
    pin: 'GPIO1'
    id: 'output1'
  - platform: 'gpio'
    pin: 'GPIO2'
    id: 'output2'
```

Compiling this configuration produces only a single `switch` component:

```yaml
switch:
- platform: output
  output: output1
  name: Output 1
  disabled_by_default: false
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-17 09:37 UTC, joshuaspence commented
Some additional context: https://github.com/joshuaspence/home-assistant-config/commit/c6ded336209d2a283e9a35f34ff1484e2b31d4be is what I was trying to do.

2022-01-17 09:38 UTC, joshuaspence commented
I did want to add test coverage but I am not really sure how the current tests are laid out and where the new test coverage should go.

2022-01-17 23:21 UTC, oxan commented
I honestly don't see why you'd ever want the platform type to be a substitution; you can't just swap one platform for another, the keys under it need to be changed as well.

2022-01-17 23:27 UTC, joshuaspence commented
In my case the only platforms I am using are `switch`, `fan` and `light`. All of these platforms support `output`, `name`, `restore_mode` and `internal`, which are the only properties I use.

I was curious whether substitutions would work in dict keys and suspected they wouldn't. But the code seems to intentionally handle this case, which made me think that it is a supported use case.

I'll admit that my current solution is kludgy. I believe that a better solution would be to allow non-string substitutions, although I don't think that would fully solve this problem for me.

2022-01-22 14:40 UTC, oxan requested changes
Ah, I understand now. Yes, this indeed seems strange behaviour, though I don't think it'll be relevant often in practice.

That said, we can fix this, but I don't like using a private function from the `packages` component in the `substitutions` one. I think we should move that function to `config_helpers.py` instead.

2022-01-24 19:48 UTC, oxan approved these changes

2022-01-24 22:46 UTC, merged

2022-01-24 23:27 UTC, joshuaspence commented
One thing I noticed whilst testing this is that `substitutions` isn't really a component in that it can't be loaded via `external_components`. This wasn't obvious to me although I suppose nothing in the documentation suggests that `substitutions` is a component, only the code.