ESP32-C3 deep sleep fix
OttoWinter/esphomeyaml pull request #3066
Opened 2022-01-17 19:09 UTC by Troublebrewing

# What does this implement/fix? 

Wakeup pin validation fixed to allow RTC pins as listed in ESP32-C3 technical reference manual.

Deepsleep pin enable function has changed from esp_sleep_enable_ext0_wakeup to esp_deep_sleep_enable_gpio_wakeup

C3 variant is not capable of wakeup from ext1 or touch when in deepsleep.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [https://github.com/esphome/issues/issues/2298](url)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-17 23:18 UTC, oxan requested changes
One minor comment, LGTM otherwise.

2022-01-17 23:18 UTC, oxan commented on esphome/components/deep_sleep/__init__.py
> +        valid_pins = [0, 1, 2, 3, 4, 5]
I would prefer something like this, which'll allow us to easily add more variants when they inevitably are introduced:
```
WAKEUP_PINS = {
  VARIANT_ESP32: [0, 2, 4, 12, 13, 14, 15, 25, 26, 27, 32, 33, 34, 35, 36, 37, 38, 39]
  VARIANT_ESP32C3: [0, 1, 2, 3, 4, 5]
}

def validate_pin_number(value):
  valid_pins = WAKEUP_PINS.get(get_esp32_variant(), VARIANT_ESP32)
```

2022-01-18 12:47 UTC, OttoWinter commented on esphome/components/deep_sleep/deep_sleep_component.h
> +#if defined(USE_ESP32) && !defined(USE_ESP32_VARIANT_ESP32C3)
If this not supported on ESP32-C3, we should also check that when validating the config here: https://github.com/esphome/esphome/pull/3066/files#diff-4b75ce4b24cc681d980a0e245d276688c481c3b9a64e292d3503c94761814569R100

2022-01-18 15:15 UTC, Troublebrewing commented
I think I've implemented the pin validation and config validation as @oxan and @OttoWinter had commented.

Also test1 and test2 files were modified to get the PR checks to pass but I'm not sure if that is the proper way to do things.  Let me know if I should do this differently. 

FYI this is my first time contributing so sorry for my ignorance.

2022-01-22 14:26 UTC, oxan requested changes

2022-01-22 14:26 UTC, oxan commented on esphome/components/deep_sleep/__init__.py
> +    valid_pins = WAKEUP_PINS.get(get_esp32_variant(), VARIANT_ESP32)
My bad, this should be:
```suggestion
    valid_pins = WAKEUP_PINS.get(get_esp32_variant(), WAKEUP_PINS[VARIANT_ESP32])
```

2022-01-22 14:26 UTC, oxan commented on esphome/components/deep_sleep/__init__.py
> +        config[CONF_RAW]
What does this check? There doesn't seem to be a `raw` option in the config schema.

2022-01-22 14:26 UTC, oxan commented on esphome/components/deep_sleep/__init__.py
> +        and config.get(CONF_ESP32_EXT1_WAKEUP, None) is not None
```suggestion
        and CONF_ESP32_EXT1_WAKEUP in config
```

2022-01-22 14:26 UTC, oxan commented on esphome/components/deep_sleep/__init__.py
> +        and config.get(CONF_TOUCH_WAKEUP, None) is not None
Same here.

2022-01-24 14:39 UTC, Troublebrewing commented on esphome/components/deep_sleep/__init__.py
> +        config[CONF_RAW]
This is intended to verify the config does not include unsupported wakeup methods for any ESP32C3 based boards. Specifically EXT1 or Touch based wakeup are not supported. I will remove the `config[CONF_RAW]` condition. This was from when I copied code from elsewhere.

2022-02-19 14:13 UTC, OttoWinter approved these changes
Thanks!

2022-02-19 14:13 UTC, merged