Esp32 touch patch
OttoWinter/esphomeyaml pull request #3080
Opened 2022-01-20 08:39 UTC by larsenglund

# What does this implement/fix? 

Adds support for ESP32S2 touch pins in the esp32_touch component

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-20 12:28 UTC, OttoWinter commented on esphome/components/esp32_touch/binary_sensor.py
> +    if value not in TOUCH_PADS[variant]:
We should check before that we support the given variant at all
```python
        if variant not in TOUCH_PADS:
            raise cv.Invalid(some_msg)
```

2022-01-20 12:29 UTC, OttoWinter commented on esphome/components/esp32_touch/esp32_touch.cpp
>    if (this->iir_filter_enabled_()) {
Is it correct that the esp32s2 does not support the IIR filter? If so, we should catch that in validation

2022-01-20 12:31 UTC, OttoWinter commented on esphome/components/esp32_touch/esp32_touch.cpp
> +      touch_pad_config(child->get_touch_pad());
Same for wakeup threshold, is it supported on ESP32S2?

2022-01-20 22:16 UTC, larsenglund commented on esphome/components/esp32_touch/esp32_touch.cpp
>    if (this->iir_filter_enabled_()) {
No, it does support both a common noise filter (which is enabled in my pr) and a IIR filter. The IIR for the ESP32S2 seems to be implemented differently than the ESP32 though. It takes in a struct with a bunch of parameters for the filter, the difference can be seen in the manual for the touchpad; 
ESP32S2: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/touch_pad.html
ESP32: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/touch_pad.html
I got good results with just the common noise filter enabled so I didn't implement code to handle the IIR filter.

2022-01-20 22:21 UTC, larsenglund commented on esphome/components/esp32_touch/esp32_touch.cpp
> +      touch_pad_config(child->get_touch_pad());
It seems to support it by looking at the docs for the touchpad but it seems to be implemented slightly different and I had no need for it so I haven't implemented it.
ESP32S2: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/touch_pad.html
ESP32: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/touch_pad.html

2022-01-20 22:23 UTC, larsenglund commented on esphome/components/esp32_touch/binary_sensor.py
> +    if value not in TOUCH_PADS[variant]:
Indeed, good suggestion.

2022-01-20 22:25 UTC, larsenglund commented on esphome/components/esp32_touch/binary_sensor.py
> +    if value not in TOUCH_PADS[variant]:
I added that.

2022-01-28 12:07 UTC, jesserockz requested changes
In the `esp32_touch.cpp` file, you don't need to have `#if defined(USE_ESP32)` as the first condition as the whole file is esp32 only.

2022-01-28 12:07 UTC, jesserockz commented on esphome/components/esp32_touch/binary_sensor.py
>      return value
I think if you change this, you don't need to look up the variant in to_code and can directly set my suggestion in my below comment. (Please do test this theory)
```suggestion
    return cv.enum(TOUCH_PADS[variant])(value)
```

2022-01-28 12:07 UTC, jesserockz commented on esphome/components/esp32_touch/binary_sensor.py
> +        TOUCH_PADS[variant][config[CONF_PIN]],
As per above, you would get the `cg.global_ns.TOUCH_PAD_NUMx` value here directly like this.
```suggestion
        config[CONF_PIN],
```

2022-04-29 06:41 UTC, larsenglund commented on esphome/components/esp32_touch/binary_sensor.py
>      return value
Thanks for the feedback! I got a bit sidetracked with other stuff but will fix this soon (if it's not already fixed in the main branch by now)

2022-04-29 06:41 UTC, larsenglund commented on esphome/components/esp32_touch/binary_sensor.py
> +        TOUCH_PADS[variant][config[CONF_PIN]],
Thanks for the feedback! I got a bit sidetracked with other stuff but will fix this soon (if it's not already fixed in the main branch by now)

2022-05-07 00:46 UTC, closed without merging