Generic H-Bridge driver + H-Bridge switch implementation
OttoWinter/esphomeyaml pull request #3086
Opened 2022-01-22 14:04 UTC by FaBjE

feature/hbridge
--------------------

# What does this implement/fix? 

This pull request combines several (partial) h-bridge driver implementations into one generic h-bridge driver.
I added proper DC motor transition/breaking implementation to this hbridge driver.
Currently it is a reusable software class and not usable as a instance to end users but this could be added.

I ported the H-Bridge fan and H-Bridge light component to the new generic H-bridge driver implementation for code-reuse.

I also added a "H-Bridge switch" component. This component can abstract linear actuators / motorized valve controllers as a switch. (See documentation pull request for more info)
This greatly simplifies using them in home-assistant.

I've had to make one breaking change resolving this issue: https://github.com/esphome/issues/issues/2871
All other changes are backwards compatible.

I've not claimed ownership of the H-Bridge fan and H-Bridge light component. 
I changed them a fair bit. But I wasn't sure if I should do so. Please advise.

## Types of changes

- [X] Bugfix [Kinda with issue #2871]
- [X] New feature [Add H-Bridge switch + generic HBridge driver]
- [X] Breaking change [Removed "decay mode" from fan component. See #2871]
- [ ] Other

**Related issue or feature (if applicable):**
fixes https://github.com/esphome/issues/issues/2871

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 
esphome/esphome-docs#1835

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

(I have no ESP32 available sorry, I wrote the code with ESP32 compatibility in mind. I expect no issues as nothing directly uses low level hw functions)

## Example entry for `config.yaml`:

```yaml

# Output list
output:
  - platform: esp8266_pwm
    id: output_fan_a
    pin: D1
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: output_fan_b
    pin: D2
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: output_fan_enable
    pin: D3
  - platform: gpio
    id: output_fan_oscillating
    pin: D4
  - platform: esp8266_pwm
    id: output_light_a
    pin: D5
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: output_light_b
    pin: D6
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: output_switch_a
    pin: D7
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: output_switch_b
    pin: D8
    frequency: 1000 Hz

# Light test config
light:
  - platform: hbridge
    id: hbridge_light
    name: "H-Bridge Light"
    pin_a: output_light_a
    pin_b: output_light_b

# Fan test config
fan:
  - platform: hbridge
    id: hbridge_fan
    name: "H-Bridge Fan"
    pin_a: output_fan_a
    pin_b: output_fan_b
    enable_pin: output_fan_enable
    oscillation_output: output_fan_oscillating
    transition_delta_per_ms: 0.001
    transition_short_buildup_duration: 5000ms
    transition_full_short_duration: 3000ms

# Switch test config    
switch:
  - platform: hbridge
    id: hbridge_switch
    name: "H-Bridge switch"
    pin_a: output_switch_a
    pin_b: output_switch_b
    duration: 10000ms

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-22 21:29 UTC, oxan reviewed
Thanks! This looks like a good improvement. I didn't check the transition logic, but I'll assume you tested it :)

Some comments inline:

2022-01-22 21:29 UTC, oxan commented on esphome/components/hbridge/__init__.py
>  hbridge_ns = cg.esphome_ns.namespace("hbridge")
The new `HBridge` parent class should be properly reflected in the code generation phase:
* Define the class here using `HBridge = hbridge_ns.class_("HBridge")`
* Add an ID of that type to the config schema: `cv.GenerateID(): cv.declare_id(HBridge)`
* All child classes should also inherit from the HBridge class: `HBridgeFan = hbridge_ns.class_("HBridgeFan", fan.FanState, hbridge.HBridge)`

This allows the config validation phase to check whether IDs reference the correct types and objects.

2022-01-22 21:29 UTC, oxan commented on esphome/components/hbridge/__init__.py
> +async def hbridge_config_to_code(config, var):
The usual convention is:
```suggestion
async def setup_hbridge(var, config):
```

2022-01-22 21:29 UTC, oxan commented on esphome/components/hbridge/hbridge.h
> +};
Can we change this to use scoped enumerations? We can also drop the long prefix then.

2022-01-22 21:29 UTC, oxan commented on esphome/components/hbridge/hbridge.h
> +  void loop();
You need to inherit from `Component` for these methods to be usable.

2022-01-22 21:29 UTC, oxan commented on esphome/components/hbridge/hbridge.cpp
> +    // this->current_relative_dutycycle_);
We don't want commented code. If this is still useful, it should be logged at e.g. the very verbose level (`ESP_LOGVV`), otherwise it should be dropped.

2022-01-22 21:29 UTC, oxan commented on esphome/components/hbridge/hbridge.cpp
> +  // dutycycle_delta_per_ms, shorting_buildup_duration_ms, full_short_duration_ms);
Same here.

2022-01-22 21:29 UTC, oxan commented on esphome/components/hbridge/hbridge.cpp
> +  }
Maybe clamp it to (-1, 1) instead? 
```c++
relative_dutycycle = clamp(relative_dutycycle, -1.0f, 1.0f);
```

2022-01-22 21:29 UTC, oxan commented on esphome/components/hbridge/light/hbridge_light_output.h
> +      this->direction_a_update_ = false;
Can you just merge this into `loop()` and drop this method and the `PollingComponent` parent class? it gets called with the same frequency anyway.

2022-01-22 21:29 UTC, oxan commented on esphome/components/hbridge/switch/hbridge_switch.cpp
> +  ESP_LOGCONFIG(TAG, "Setting up Valve Actuator: '%s'...", this->name_.c_str());
```suggestion
  ESP_LOGCONFIG(TAG, "Setting up H-Brdige Switch: '%s'...", this->name_.c_str());
```

2022-01-22 21:29 UTC, oxan commented on esphome/components/hbridge/switch/hbridge_switch.cpp
> +void HBridgeSwitch::loop() { HBridge::loop(); }
If you make `HBridge` inherit from `Component`, this can be dropped.

2022-01-23 12:37 UTC, FaBjE commented
Thank you for your extensive and valid feedback! I have second to none experience in Python so it is very much appreciated.

I will process your points and update this branch. I've added some comments per-point to clarify.

2022-01-23 12:39 UTC, FaBjE commented on esphome/components/hbridge/light/hbridge_light_output.h
> +      this->direction_a_update_ = false;
I will do that, the original component was build this way. I assumed it was for a reason but it seemed a bit odd to me as well.

2022-01-23 12:48 UTC, FaBjE commented on esphome/components/hbridge/switch/hbridge_switch.cpp
> +void HBridgeSwitch::loop() { HBridge::loop(); }
I was not sure to let HBridge itself inherit from component or the child classes. As HBridge is more of an abstract class at the moment.

The function here is pretty useless I agree, but HBridgeFan and HBridgeLight both use the loop function for their own functionality.

If I were to override that I would override/remove the function from HBridge (base) .
I would need to add a call to the base/HBridge class as well. Which brings me pretty much back to the state it is now.

Should we leave it this way or do the override + base class call method?

2022-01-23 12:52 UTC, FaBjE commented on esphome/components/hbridge/__init__.py
> +async def hbridge_config_to_code(config, var):
I used a different function name on purpose as the hbridge class cannot be used directly and this was more of an "helper function"

2022-01-23 14:43 UTC, oxan commented on esphome/components/hbridge/__init__.py
> +async def hbridge_config_to_code(config, var):
Yes, that's true, but e.g. the `Climate` or `Fan` class also can't be used on it's own, and they do follow the `setup_` pattern. It's not really important, just a nice bit of consistency :)

2022-01-23 14:43 UTC, oxan commented on esphome/components/hbridge/light/hbridge_light_output.h
> +      this->direction_a_update_ = false;
Yes, this isn't related to your changes, but a nice bit of cleanup while we're at it :)

2022-01-23 14:47 UTC, oxan commented on esphome/components/hbridge/switch/hbridge_switch.cpp
> +void HBridgeSwitch::loop() { HBridge::loop(); }
My view here is that the `HBridge` class requires `loop()` to be called, so child classes must inherit from `Component`. Why force all users to do it manually, instead of doing it in `HBridge` already and removing that burden from child classes that don't need it?

You're right that for the fan/light it doesn't make any difference as they override it themselves as well. I don't think that's an issue.

2022-01-23 15:12 UTC, FaBjE commented on esphome/components/hbridge/switch/hbridge_switch.cpp
> +void HBridgeSwitch::loop() { HBridge::loop(); }
Agreed. I'll change it.

2022-01-23 18:40 UTC, FaBjE commented on esphome/components/hbridge/switch/hbridge_switch.cpp
> +void HBridgeSwitch::loop() { HBridge::loop(); }
I'm trying to implement this but I run into all kinds of ambiguity errors.

For example, i have the `HBridge ` class inherit from `Component` now, but I get ambiguity errors in HBridgeFan because `fan::FanState` also inherits from `Component`
I can't think of anything how to solve this than letting every child class inherit from `Component` when needed.
Any suggestions?

2022-01-23 18:48 UTC, FaBjE commented on esphome/components/hbridge/__init__.py
>  hbridge_ns = cg.esphome_ns.namespace("hbridge")
I'm trying to implement this, but whenever i put `cv.GenerateID(): cv.declare_id(HBridge)` in the HBridge base class it runs into problems. I either get errors that components are "Not registered to inherit from Component or registered twice" or, the generated C++ main code sees every instance as C++ HBridge type and tries to create that as an instance. which fails because it is not a child-class type.

I've put `cv.GenerateID(): cv.declare_id(xxxx)` in every child-class config and that works fine.

Is this what you meant?

2022-01-24 19:50 UTC, oxan commented on esphome/components/hbridge/__init__.py
>  hbridge_ns = cg.esphome_ns.namespace("hbridge")
> I either get errors that components are "Not registered to inherit from Component or registered twice"

Ah yes, if we also change `HBridge` to inherit from `Component`, that should be done in the class definition here as well:

```python
HBridge = hbridge_ns.class_("HBridge", cg.Component)
```

2022-01-24 19:54 UTC, oxan commented on esphome/components/hbridge/switch/hbridge_switch.cpp
> +void HBridgeSwitch::loop() { HBridge::loop(); }
Ah, yeah, this is a problem because the fan component was a bit of a mess; entities such as `FanState` shouldn't inherit from `Component`. That has been fixed in #2848, which is now merged into dev, but unfortunately also changed the H-Bridge fan.

It's probably the best option if you could merge `dev` into your branch first.

2022-01-25 17:48 UTC, FaBjE commented
I rebased my feature on the dev branch and did a bit of a cleanup.
I processed all your feedback points and verified the workings :)

It is all working now except for the `cv.GenerateID(): cv.declare_id(HBridge)` line. 
When I leave that in the sourcecode generated uses all `HBridge` types instead of `HBridgeSwitch` etc.
I removed it in the last commit https://github.com/esphome/esphome/pull/3086/commits/56a816cc0de8f526734d619f046d3905eb7f759b
Could you check if this is what you intended?


I changed the codeowner marker to myself as well. I changed so much that it seems the right thing to do.
If anyone wants it back no problem ;)

2022-02-20 03:19 UTC, WeekendWarrior1 commented
https://github.com/esphome/issues/issues/2871#issuecomment-1046149764

While I think that creating a generic h-bridge parent component is useful, the Decay mode issues mentioned in this issue are not issues at all, but working as intended, and definitely should not be removed/changed.

https://deploy-preview-1835--esphome.netlify.app/components/fan/hbridge.html#transitions-explained
> Fortunately you can electrically brake a motor by shorting its windings. Just as driving a car the slamming on the brakes is not very pleasant experience for your circuit.

Are there any citations available for this statement?

2022-02-20 15:57 UTC, FaBjE commented
Thank you for your reply and explanation @WeekendWarrior1 both here and in the issue I opened.
My goal is to provide a solid universal hbridge driver. As I didn't receive a response on my issue at the time I continued under the impression it was not supposed to be this way.

I've read the articles you linked and did some research of my own. 
And I'm at the point I'm not sure if we use different terminology for the same thing, or I'm misunderstanding something.
So let me ask you really blunt (trying to learn something here)

Is the decay mode supposed to be applied on each PWM cycle (when driving the motor at a steady speed)? or is the decay mode the strategy you apply when "not driving the motor" anymore?
I think you mean the first but I can't find any hard-statements for that in the articles I read.

> Are there any citations available for this statement?
No. Seeing this now I should phrase that differently.

2022-02-20 23:29 UTC, WeekendWarrior1 commented
> Is the decay mode supposed to be applied on each PWM cycle (when driving the motor at a steady speed)? or is the decay mode the strategy you apply when "not driving the motor" anymore?
I think you mean the first but I can't find any hard-statements for that in the articles I read.

Yes, the first.
Decay mode is specific to when a motor is being PWM speed controlled, and should occur every PWM cycle.

I would also suggest rethinking and simplifying your `transition_delta_per_ms`, `transition_short_buildup_duration` and `transition_full_short_duration` variables to simply `acceleration`/`deceleration` (possibly in the unit of `speed percentage/second`). I think the simplicity would be nice for end users.

Finally, from your docs:
>Trying to speed up the motor inertia will require to motor to use large amounts of current to get things going. You can reduce the current/load on your system by gradually increasing the speed.

I do not believe that gradually increasing the speed reduces the current required to get the motor spinning (and please also consider that a H-Bridge pin is really only ever fully on, or fully off, so there will always be current spikes).
Another complication is that depending on how small/short the pulses are at the start of acceleration (eg 1% speed),
![image](https://user-images.githubusercontent.com/5209758/154869098-656ab3dd-6569-4681-8dbc-e2503181534d.png)
The small pulses will be initially completely ineffective (on the graph above, up until 20% speed) and just cause unnecessary load and heat.

2022-02-21 18:22 UTC, FaBjE commented
> Yes, the first.
>Decay mode is specific to when a motor is being PWM speed controlled, and should occur every PWM cycle.

I've restored/re-implemented the decay mode functionality.

> I would also suggest rethinking and simplifying your transition_delta_per_ms, transition_short_buildup_duration and transition_full_short_duration variables to simply acceleration/deceleration (possibly in the unit of speed percentage/second). I think the simplicity would be nice for end users.

I agree this is not the most userfriendly option. In a way the "delta_per_ms" already a percentage to a time limit.
But renaming/adding a "ac/de-celeration speed" parameter sounds good. Let me give it some thought.

> I do not believe that gradually increasing the speed reduces the current required to get the motor spinning (and please also consider that a H-Bridge pin is really only ever fully on, or fully off, so there will always be current spikes).

I removed the claim to be sure.

> Another complication is that depending on how small/short the pulses are at the start of acceleration (eg 1% speed),
> The small pulses will be initially completely ineffective (on the graph above, up until 20% speed) and just cause unnecessary load and heat.

True, but it depends on the circuit/motor where the "cutoff" is that they are not effective anymore.
So I'm hesitant to limit them.


> PS. Apologies for the delay on commenting on your Github issue as well. In theory I should get notifications when an issue is tagged on a component I codeown, but that wasn't the case.

Thats ok. I think the problem was the name "WeekendWarrior" instead of "WeekendWarrior1" was in the codeowners file.

2022-03-25 08:54 UTC, FaBjE commented
@oxan Should I do anything for you to be able to review? Or just wait patiently? 😉

2022-04-03 22:06 UTC, jesserockz requested changes
A few minor changes

2022-04-03 22:06 UTC, jesserockz commented on esphome/components/hbridge/fan/__init__.py
> +HBridgeFan = hbridge.hbridge_ns.class_("HBridgeFan", fan.FanState, hbridge.HBridge)
```suggestion
HBridgeFan = hbridge.hbridge_ns.class_("HBridgeFan", fan.Fan, hbridge.HBridge)
```

2022-04-03 22:06 UTC, jesserockz commented on esphome/components/hbridge/switch/__init__.py
> +        cg.add(var.set_switching_duration(config[CONF_DURATION]))
Default exists so it is always in the config
```suggestion
    cg.add(var.set_switching_duration(config[CONF_DURATION]))
```

2022-04-03 22:06 UTC, jesserockz commented on esphome/components/hbridge/__init__.py
> +        )
All of these have defaults
```suggestion
    cg.add(var.set_hbridge_decay_mode(config[CONF_DECAY_MODE]))

    # Transition settings
    cg.add(
        var.set_setting_transition_delta_per_ms(
            config[CONF_TRANSITION_DELTA_PER_MS]
        )
    )

    cg.add(
        var.set_setting_transition_shorting_buildup_duration_ms(
            config[CONF_TRANSITION_SHORT_BUILDUP_DURATION]
        )
    )

    cg.add(
        var.set_setting_transition_full_short_duration_ms(
            config[CONF_TRANSITION_FULL_SHORT_DURATION]
        )
    )
```

2022-04-04 15:03 UTC, FaBjE commented
Thank you for your review and valid points @jesserockz
I have changed them and verified the workings.

2022-04-04 15:10 UTC, FaBjE commented on esphome/components/hbridge/__init__.py
>  hbridge_ns = cg.esphome_ns.namespace("hbridge")
I removed the line as I was unable to get it working with it.

2022-04-08 03:45 UTC, WeekendWarrior1 commented
>>Another complication is that depending on how small/short the pulses are at the start of acceleration (eg 1% speed), The small pulses will be initially completely ineffective (on the graph above, up until 20% speed) and just cause unnecessary load and heat.

>True, but it depends on the circuit/motor where the "cutoff" is that they are not effective anymore.
So I'm hesitant to limit them.

If it's dependent on the circuit/motor, then it makes perfect sense to have it user configurable, eg. `min_speed`? Or `starting_speed`?
The reason why this is important is if someone has a slow acceleration (over 10s), but their motor is stalled until it's reached 50% speed, it's going to burn out the motor very fast (I have done this on a few TT DC plastic gearbox motors lol).


---
https://deploy-preview-1835--esphome.netlify.app/components/fan/hbridge.html#transition-configuration

All the transition configuration seems so needlessly complex and challenging to understand (I have plenty of experience with DC motors and I find it a little puzzling/confusing)

> Use the transition_delta_per_ms parameter for this. This will increment the speed with the set value every millisecond until the set speed has been reached.

> For example use 0.001 to stretch a 0 (still) to 1 (full speed) increment over 1 second.

There has to be a nicer way for the average end-user to configure this (and word it)
I still believe having it configurable as:
- `acceleration`: speed percentage/second (eg. )
or
- `acceleration`: seconds (eg. takes 1 second to ramp from 0%-100%)
Would be a massive improvement.

---
>- transition_short_buildup_duration (Optional, float): duration in milliseconds to buildup from no to full short. Defaults to 0 (no shorting/braking = coasting)

> - transition_full_short_duration (Optional, float): duration in milliseconds to apply full short (after optional buildup). Defaults to 0 (no shorting/braking = coasting)

Can you explain these a bit more?
Do they apply every PWM cycle?
Or just when using the brake action? (if yes, maybe they should just be an optional variable on the brake action?)
Is `transition_short_buildup_duration` some sort of deceleration setting that works the same as `transition_delta_per_ms`?
Is `transition_full_short_duration` just emulating how slow decay mode works?

2022-04-08 04:56 UTC, WeekendWarrior1 commented
Okay found your much better explanation in the code:
https://github.com/esphome/esphome/blob/2b71b76a04810d9b0eb238b311c43f840c0ae497/esphome/components/hbridge/hbridge.cpp#L128
```c++
  // --- Behaviour Examples:
  // Transition - Direction A 100% to Direction A 20% (No shorting is applied regardless of values):
  // |           A100% >> A20%            |
  // |< ---  transition_duration_ms  --- >|
  //
  // Transition - Direction A 100% to Direction B 100%, No shorting (duration set to 0):
  // | A100% >> A0% | Idle | B0% >> B100% |
  // |< ---   transition_duration_ms --- >|
  //
  // Transition - Direction A 100% to 0%, With shorting (duration set > 0):
  // | A0% |  Shorting 0% >> Shorting 100%  |       Shorting 100%      |
  //       |< shorting_buildup_duration_ms >|
  //                                        |< full_short_duration_ms >|
  //
  // Transition - Direction A 100% to Direction B 100%, With shorting (duration set > 0):
  // | A0% |  Shorting 0% >> Shorting 100%  |       Shorting 100%      |       B0% >> B100%       |
  //       |< shorting_buildup_duration_ms >|
  //                                        |< full_short_duration_ms >|
  //                                                                   |< transition_duration_ms >|

```
Okay, so basically the hbridge.brake action, but can automatically be applied at the end of travel.

So could the wording be more like:
- `brake_when_stopped`: optional, default 0s

eg. `brake_when_stopped`: .5s = 500ms of braking after hbridge has stopped

2022-04-18 08:56 UTC, FaBjE commented
@WeekendWarrior1
I agree on your proposal for the config options. I will start to work on implementing them.

2022-04-23 12:46 UTC, FaBjE commented
I have changed the configuration parameters as @WeekendWarrior1 suggested. (with some minor tweaks)

-  `acceleration` (time) <- time from 0-100%
-  `deceleration` (time)<- time from 100-0%
-  `brake_when_stopped` (time)
-  `brake_buildup_when_stopped` (time) _For "Fast current decay" mode, ignored in "Slow current decay" mode_
-  `min_speed` (dutycycle) _Because this is more in-line with the [output component](https://esphome.io/components/output/index.html) "min_power" option_

And it is indeed much easier to config/use now :)
The code has been tested, and the documentation has been updated (https://github.com/esphome/esphome-docs/pull/1835)

See first post for the new example/test configuration.

I also had an idea to improve/reduce the flickering in the hbridge light implementation, I added that as well.

2022-06-23 07:27 UTC, FaBjE commented
The documentation pull request has automatically been marked as stale due to inactivity 😞 

I've put a lot of work into this. It would be unfortunate if it were all for nothing...

Please let me know what is keeping you from merging so I can fix it.

2022-07-01 14:26 UTC, FaBjE commented
Merged dev branch to keep "up-to-date"

2022-09-30 10:48 UTC, FaBjE commented
@ssieb Thanks for the label. 
If any action is needed from me let me know.

2023-04-21 00:45 UTC, closed without merging