Change write type for BLE binary output
OttoWinter/esphomeyaml pull request #3091
Opened 2022-01-22 18:12 UTC by AshtonKem

# What does this implement/fix? 

Was having an issue with my ESP32 not actually changing BLE characteristic values. Changing the write type from NO_RSP to RSP fixed it. Not entirely sure why.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
switch:
  - platform: template
    id: ashton_ooler_power
    name: "Ashton Ooler Power"
    turn_on_action: 
     - output.turn_on: ashton_ooler_power_output
    turn_off_action: 
      - output.turn_off: ashton_ooler_power_output
    lambda: |-
      if (id(ashton_ooler_power_internal).state > 0) {
        return true;
      } else {
        return false;
      }

output: 
  - platform: ble_client
    ble_client_id: ashton_ooler
    id: ashton_ooler_power_output
    service_uuid: 5C293993-D039-4225-92F6-31FA62101E96
    characteristic_uuid: 7A2623FF-BD92-4C13-BE9F-7023AA4ECB85

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-23 03:10 UTC, buxtronix commented
I *think* this should work as it's pretty standard in BLE to expect a response, and I confess I don't have a good reason as to why this was done with NO_RSP.
However we'd need to look carefully for any incoming bugs in case this breaks some devices.

2022-01-23 05:26 UTC, AshtonKem commented
Yeah, I didn't see any documentation that explained the difference, but then again I also didn't look very hard. In theory it shouldn't make a difference, but then again in theory it shouldn't have fixed my issue either. 🤷

2022-01-23 05:48 UTC, jesserockz requested changes
This would be device specific and should become a config parameter

2022-01-23 21:20 UTC, AshtonKem commented
Seems reasonable, I’ll make that change. 

—
Ashton Kemerling

Sent from my iPhone. 

> On Jan 22, 2022, at 10:48 PM, Jesse Hills ***@***.***> wrote:
> 
> ﻿
> @jesserockz requested changes on this pull request.
> 
> This would be device specific and should become a config parameter
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.

2022-01-24 15:04 UTC, AshtonKem commented
I'll update the docs once everyone is happy with the code changes.

2022-01-28 12:13 UTC, jesserockz requested changes

2022-01-28 12:13 UTC, jesserockz commented on esphome/components/ble_client/output/ble_binary_output.h
> +  bool is_response_required() const { return this->require_response_; }
I wouldn't worry about exposing a getter for this, and just use it as `this->require_response_` above in `write_state`
```suggestion
```

2022-01-28 12:13 UTC, jesserockz commented on esphome/components/ble_client/output/ble_binary_output.cpp
> +  if (this->is_response_required()) {
```suggestion
  if (this->require_response_) {
```

2022-01-28 12:13 UTC, jesserockz commented on esphome/components/ble_client/output/__init__.py
> +        cg.add(var.set_require_response(config[CONF_REQUIRE_RESPONSE]))
Default is `False` so conditional not needed
```suggestion
    cg.add(var.set_require_response(config[CONF_REQUIRE_RESPONSE]))
```

2022-01-28 12:13 UTC, jesserockz commented on esphome/components/ble_client/output/ble_binary_output.h
> +  bool require_response_{false};
No default here as it is set in config validation/codegen
```suggestion
  bool require_response_;
```

2022-01-31 01:29 UTC, jesserockz approved these changes
LGTM. @buxtronix ?

2022-01-31 02:31 UTC, buxtronix commented
LGTM also, pending docs update

2022-01-31 15:20 UTC, AshtonKem commented
https://github.com/esphome/esphome-docs/pull/1869

2022-02-08 08:30 UTC, merged