Http follow requests
OttoWinter/esphomeyaml pull request #3100
Opened 2022-01-23 15:15 UTC by guillempages

# What does this implement/fix? 

Add the possibility to configuring "follow redirects" for HTTP requests.

In my setup, I am doing a HTTP request to an apache virtual host and it sends a redirect response (HTTP code: 300).
In order for the request to actually succeed, the "FOLLOW_REDIRECTS" option needs to be set to the HTTPClient instance.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>
No issue (that I am aware of). If needed I can create one.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#
Not created yet; will create a documentation PR once this PR is in a "mergeable" state.

## Test Environment

- [x] ESP32   (inkplate 10)
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
http_request:
  follow_redirects: true
  redirect_limit: 15
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-01-23 15:19 UTC, guillempages commented on esphome/components/http_request/__init__.py
> +            cv.Optional(CONF_REDIRECT_LIMIT, 10): cv.int_,
10 is the default in ESP HTTPClient; I thought keeping the same default would make sense here

2022-01-23 15:19 UTC, guillempages commented on esphome/components/http_request/http_request.h
> +          this->client_.setFollowRedirects(HTTPC_FORCE_FOLLOW_REDIRECTS);
In the HTTPClient headers, there is also the HTTPC_STRICT_FOLLOW_REDIRECTS option; which would only follow some redirects (i.e. the ones that do not need to be confirmed by the user).
Opinions welcome: Should I change this to "STRICT", keep "FORCE", or use a string instead of a boolean and let the user choose (-> the latter might be unclear to people not familiar with HTTP)

2022-01-23 15:41 UTC, oxan requested changes

2022-01-23 15:41 UTC, oxan commented on esphome/components/http_request/__init__.py
> +            cv.Optional(CONF_REDIRECT_LIMIT, 10): cv.int_,
Actually, ESPHome uses a limit of 3, but I think increasing that to 10 is fine.

2022-01-23 15:41 UTC, oxan commented on esphome/components/http_request/http_request.h
> +  }
Setting the properties on the `client_` object here means they'll be overwritten by the `send()` method (see [here](https://github.com/esphome/esphome/blob/dev/esphome/components/http_request/http_request.cpp#L44)). Can you change that code to take the `follow_redirects_` and `redirect_limit_` values into account instead?

2022-01-23 15:43 UTC, oxan commented on esphome/components/http_request/http_request.h
> +          this->client_.setFollowRedirects(HTTPC_FORCE_FOLLOW_REDIRECTS);
I think using force by default is fine.

2022-01-23 15:50 UTC, guillempages commented on esphome/components/http_request/__init__.py
> +            cv.Optional(CONF_REDIRECT_LIMIT, 10): cv.int_,
Ok, I couldn't find the default on esphome, so I looked at the upstream repo. I don't care either way, I can set it to 3.
I just thought, if I add the "follow redirects" option, I can also at the possibility to change the limit 😉

2022-01-23 15:51 UTC, guillempages commented on esphome/components/http_request/http_request.h
> +  }
Ok. I'm afk now, will do it tomorrow.

2022-01-23 15:55 UTC, guillempages commented on esphome/components/http_request/__init__.py
> +            cv.Optional(CONF_REDIRECT_LIMIT, 10): cv.int_,
Regarding the default, I can change this of course. On my esp32 it was not on by default (that's the whole point of the pr), that's why I set the default to false. Will change this.

2022-01-23 16:19 UTC, oxan commented on esphome/components/http_request/__init__.py
> +            cv.Optional(CONF_REDIRECT_LIMIT, 10): cv.int_,
Ah yes, seems it was only enabled on ESP8266 by default.

2022-01-23 17:03 UTC, guillempages commented on esphome/components/http_request/http_request.h
> +  }
I hadn't seen that before :-( That feels much better now, thanks

2022-01-23 17:05 UTC, guillempages commented on esphome/components/http_request/__init__.py
> +            cv.Optional(CONF_REDIRECT_LIMIT, 10): cv.int_,
Changed the default enablement and the retries limit.

2022-01-24 19:59 UTC, oxan requested changes
Two minor nits, looks good otherwise.

2022-01-24 19:59 UTC, oxan commented on esphome/components/http_request/http_request.cpp
> +#if defined USE_ESP32 || ARDUINO_VERSION_CODE >= VERSION_CODE(2, 7, 0)
Let's add some braces to make it a bit more clear that we only check the version on ESP8266:
```suggestion
#if defined(USE_ESP32) || (defined(ESP8266) && ARDUINO_VERSION_CODE >= VERSION_CODE(2, 6, 0))
#if defined(USE_ESP32) || ARDUINO_VERSION_CODE >= VERSION_CODE(2, 7, 0)
```

2022-01-24 19:59 UTC, oxan commented on esphome/components/http_request/http_request.cpp
> +#elif USE_ESP8266
You need to check whether the constant is defined in the `#elif`, as it has a falsy value (yeah, that's something we might want to fix at some point). For consistency I also change the `#ifdef USE_ESP32`:
```suggestion
#if defined(USE_ESP32)
  begin_status = this->client_.begin(url);
#elif defined(USE_ESP8266)
```

2022-01-25 08:15 UTC, guillempages commented on esphome/components/http_request/http_request.cpp
> +#elif USE_ESP8266
You are right. I saw that in the above cases, but somehow I missed this one.

2022-01-25 08:53 UTC, merged

2022-01-25 08:53 UTC, oxan commented
Thanks!