Analog threshold
OttoWinter/esphomeyaml pull request #3190
Opened 2022-02-12 23:42 UTC by ianchi

# What does this implement/fix? 

New component: `analog_threshold` binary sensor platform allows you to convert analog values (sensor readings) into boolean values, using a threshold as a reference.

It provides some options to reduce instability when the source signal is noisy: *hysteresis* (using different limits depending on the current state) and *delay* (only change after a new state has been kept a minimum time).

This allows the sensor to be translated into a tracking state for automations, as input for other components or to easily display in HA UI.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** It could help in esphome/feature-requests#953

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
    binary_sensor:
      - platform: analog_threshold
        name: "Garage Door Opening"
        sensor_id: motor_current_sensor
        threshold: 0.5
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-02-15 23:33 UTC, jesserockz requested changes
Instead of checking in every loop, it would be better to wait for a change with `sensor->add_on_state_callback(...)` 
And instead of the `delay` configs, users could just add `delayed_on` or `delayed_off` filters in yaml.

2022-02-16 14:24 UTC, OttoWinter commented on esphome/components/analog_threshold/analog_threshold_binary_sensor.cpp
> +  this->last_above_ = this->sensor_->get_state() >= (this->lower_threshold_ + this->upper_threshold_) / 2.0f;
This code doesn't seem to deal with the case that the sensor state is `NAN` (the sensor is not set up yet, or there was a reading error).

We probably need to store such a case somewhere to not trigger the binary sensor when the sensor state is `NAN` intermittently.

2022-02-16 14:24 UTC, OttoWinter commented on esphome/components/analog_threshold/analog_threshold_binary_sensor.cpp
> +  return this->sensor_->get_state() >= (this->last_above_ ? this->lower_threshold_ : this->upper_threshold_);
Same here

2022-02-17 01:01 UTC, jesserockz requested changes

2022-02-17 01:01 UTC, jesserockz commented on esphome/components/analog_threshold/analog_threshold_binary_sensor.h
> +  float get_setup_priority() const override { return setup_priority::HARDWARE; }
This probably should not be HARDWARE as the sensor it is attaching to might not be setup yet
```suggestion
  float get_setup_priority() const override { return setup_priority::DATA; }
```

2022-02-17 01:01 UTC, jesserockz commented on esphome/components/analog_threshold/binary_sensor.py
> +    await binary_sensor.register_binary_sensor(var, config)
```suggestion
    var = await binary_sensor.new_binary_sensor(config)
    await cg.register_component(var, config)
```

2022-02-17 01:01 UTC, jesserockz commented on esphome/components/analog_threshold/binary_sensor.py
> +    cg.add(var.set_sensor(bin))
Not sure what `bin` means?? No need to use short/confusing names
```suggestion
    sens = await cg.get_variable(config[CONF_SENSOR_ID])
    cg.add(var.set_sensor(sens))
```

2022-02-17 01:02 UTC, jesserockz commented on esphome/components/analog_threshold/analog_threshold_binary_sensor.h
> +  float get_setup_priority() const override { return setup_priority::HARDWARE; }
I see you just changed this..haha

2022-02-17 01:04 UTC, ianchi commented
Hi @jesserockz / @OttoWinter,
PR updated with requested changes:
+ use callback instead of loop
+ remove some redundant config options (and use filters)
+ use DATA priority
+ handle NaN sensor values. I used a fixed, simple approach that should fit many use cases. I don't know if there some cases that need a specific config option ( `nan_mode`) to define a mode to handle this (ignore / as false / as true)?

I also updated docs and tests accordingly.

2022-02-17 01:05 UTC, ianchi commented on esphome/components/analog_threshold/analog_threshold_binary_sensor.h
> +  float get_setup_priority() const override { return setup_priority::HARDWARE; }
Thought the same and has just pushed and update

2022-02-17 02:15 UTC, ianchi commented
@jesserockz I had some problems with the constructor when changing with the suggested code generation changes.
I think now everything is set.

2022-02-17 03:04 UTC, jesserockz commented
Ah yes I know why. The name in constructor is actually redundant and needs to be removed.

2022-02-17 03:36 UTC, ianchi commented
Ok, it's clear.
I can just drop the last commit then.
But without your fix merged, it will fail the tests.
Do I update this PR anyhow?

2022-02-17 04:04 UTC, jesserockz commented
I merged that PR so you can rebase/merge dev in

2022-02-17 04:48 UTC, ianchi commented
done

2022-02-17 10:29 UTC, jesserockz approved these changes

2022-02-17 20:14 UTC, merged