Add support for QMP6988 Pressure sensor
OttoWinter/esphomeyaml pull request #3192
Opened 2022-02-13 10:22 UTC by andrewpc

# What does this implement/fix? 

This change adds support for the QMP6988 Pressure and Temperature sensor. This sensor is found in the M5Stack ENVIII alongside the SHT30 (which is already supported in esphome).

Datasheet can be found here: https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/datasheet/unit/enviii/QMP6988%20Datasheet.pdf

Code reworked to be esphome native from arduino example provided in the following github repo: https://github.com/m5stack/UNIT_ENV 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

Docs PR WIP, will complete soon.

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
- platform: qmp6988
   temperature:
     name: "Wine Temperature External QMP6988 M5 ESP32"
     oversampling: 64x
   pressure:
     name: "Wine Pressure External M5 ESP32"
     oversampling: 1x
   address: 0x70
   update_interval: 60s
   iir_filter: 2x
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-02-13 13:11 UTC, randybb commented
Nice!
```
[13:56:36][D][sensor:125]: 'DEV 1 SHT30 Temperature': Sending state 22.35638 °C with 1 decimals of accuracy
[13:56:36][D][sensor:125]: 'DEV 1 SHT30 Humidity': Sending state 37.43801 % with 1 decimals of accuracy
[13:57:18][D][sensor:125]: 'DEV 1 BME280 Temperature': Sending state 21.68000 °C with 1 decimals of accuracy
[13:57:18][D][sensor:125]: 'DEV 1 BME280 Pressure': Sending state 1010.89648 hPa with 1 decimals of accuracy
[13:57:18][D][sensor:125]: 'DEV 1 BME280 Humidity': Sending state 37.98145 % with 1 decimals of accuracy
[14:02:16][D][sensor:125]: 'DEV 1 QMP6988 Temperature': Sending state 22.53906 °C with 1 decimals of accuracy
[14:02:16][D][sensor:125]: 'DEV 1 QMP6988 Pressure': Sending state 1009.96124 hPa with 1 decimals of accuracy
```

2022-02-17 20:57 UTC, jesserockz requested changes

2022-02-17 20:57 UTC, jesserockz commented on esphome/components/qmp6988/qmp6988.cpp
> +}
Why create functions that do not add any extra value? Just use the `write_byte` and `read_register` in the code and check for `!= i2c::ERROR_OK`.
It makes it more confusing this way, espeically when you basically flipped the return value `i2c::ERROR_OK` is `0`

2022-02-17 20:57 UTC, jesserockz commented on esphome/components/qmp6988/qmp6988.cpp
> +uint8_t QMP6988Component::device_check_() {
This could easily be a `bool` return value

2022-02-17 20:57 UTC, jesserockz commented on esphome/components/qmp6988/qmp6988.cpp
> +int QMP6988Component::get_calibration_data_() {
This could be `bool` too

2022-02-17 20:57 UTC, jesserockz commented on esphome/components/qmp6988/qmp6988.cpp
> +void QMP6988Component::set_power_mode_(int power_mode) {
```suggestion
void QMP6988Component::set_power_mode_(uint8_t power_mode) {
```

2022-02-21 02:32 UTC, andrewpc commented on esphome/components/qmp6988/qmp6988.cpp
> +}
Ok, functions removed, thanks

2022-03-04 11:44 UTC, andrewpc commented
@jesserockz Any update on this one? All the changes you requested should now be there. Thanks

2022-03-13 19:12 UTC, jesserockz approved these changes

2022-03-14 19:09 UTC, merged