CAN bus: support remote transmission request flag for canbus.send
OttoWinter/esphomeyaml pull request #3193
Opened 2022-02-14 12:22 UTC by felixstorm

# What does this implement/fix? 

Support remote transmission request flag for sending CAN bus messages. The CAN bus component already supports the flag in its internal structures but it has not been available for use from outside yet.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** n/a

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** Will be happy to add docs PR if this code PR is generally acceptable.

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
on_...:
  - canbus.send:
      can_id: 24
      remote_transmission_request: true
      data: []
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-03-06 15:26 UTC, felixstorm commented
@jesserockz As there seems to be no reaction from the maintainers, would you mind to also merge this PR (as you did with two other CAN bus related PRs from me (#3194 and #3196) a few days ago)? By now I also prepared the corresponding docs PR (esphome/esphome-docs#1948) for the code PRs here.

Thanks!

2022-03-09 08:23 UTC, danielschramm commented
Hello @felixstorm,

is it also tested for mcp2515 interface?
From the documentation PR i would read it as it works for ESP32 and mcp2515.

If we add this feature it should work an all CAN-Interfaces otherwise it would be too confusing for the users.

Thanks,

Daniel

2022-03-09 08:28 UTC, felixstorm commented
@danielschramm Thanks for your reply. I did physically test it on an ESP32 but unfortunately I do not have an MCP2515 here to do the same, but from the code it seems that it should work the same as on the ESP32 as the MCP2515 flag `RTR_MASK` is being explicitely set if `remote_transmission_request` is `true`: https://github.com/esphome/esphome/blob/0af1edefffbd283f1a40425a11e3d4c6e3a94000/esphome/components/mcp2515/mcp2515.cpp#L240

2022-03-09 08:49 UTC, danielschramm commented
Thanks for your reply.
We should definetly do a real test for mcp2515 before merging it finally.
I will check if I can do it in the next days.

2022-03-09 09:48 UTC, felixstorm commented
@danielschramm To be honest, I would personally be fine with trusting the datasheet (it's page 25 there) instead of having to test it out physically. Feel free to test this out and merge if you like, but I will not push this any further but stay with my personal working implementation.

2022-03-09 09:51 UTC, felixstorm commented
I am pretty much disillusioned by now. After already having had a working solution for my personal requirements, I spent several hours more to create 4 PRs including tests and documentation - hoping that this might also be helpful for the community. None of the maintainers showed any reaction - @jesserockz himself merged two of the PRs. After asking again after 3 weeks for the two remaining PRs, one of the maintainers answers, but IMHO there seems to be more interest in protecting stuff by not changing anything and trying to come up with very special reasoning (i.e. that a change may have disadvantages if the user does not know what he is doing, see https://github.com/esphome/esphome/pull/3195#issuecomment-1060436627). I spend another 1 or 2 hours time for the discussions and further research from my side and still have to wait on further delays since the maintainer does not seem to trust a datasheet.  

To be honest, since I think it's generally a great project, I will continue to supprt ESPHome with my recurring financial donation, but I will for sure not try to contribute any code or documentation for it again. Community contribution can only work if reactions are timely and are interested in progress, not in stagnancy.
CC @OttoWinter @jesserockz @danielschramm

2022-03-09 10:03 UTC, danielschramm commented
Hello @felixstorm,

one one hand you do not want to change anything for backward compatibility to not effect existing installations.
On the other hand you want to merge untested functionality.

I also work only on hobby on this and only code owner and not a paid maintainer as I took over a stalled branch. It initially took a couple of month to get canbus integrated for the initial author and me.

It will always be a discuassion between testing depth and speed of integration. 
The decision to this will be on the side of the maintainers.
I just vote for giving us a week more for testing to keep away any problems from less skilled users. 
I offered to do it, but I also only have the time once either for complaining here or doing the work.

Daniel

2022-03-09 10:09 UTC, felixstorm commented
@danielschramm I know that most or all of the people working on this project do this in their spare time and it was not my primary intention to criticize or even insult you personally.  
It was just my personal and subjective reflection and conclusion on the situation as I had the chance to observe it in the past weeks.

2022-03-13 19:17 UTC, jesserockz requested changes

2022-03-13 19:17 UTC, jesserockz commented on esphome/components/canbus/__init__.py
> +        config[CONF_REMOTE_TRANSMISSION_REQUEST], args, cg.uint32
Why is this set to `cg.uint32`?
```suggestion
        config[CONF_REMOTE_TRANSMISSION_REQUEST], args, bool
```

2022-03-13 19:17 UTC, jesserockz commented on esphome/components/canbus/canbus.cpp
> +    ESP_LOGD(TAG, "send extended id=0x%08x rtr=%d size=%d", can_id, remote_transmission_request, size);
```suggestion
    ESP_LOGD(TAG, "send extended id=0x%08x rtr=%s size=%d", can_id, TRUEFALSE(remote_transmission_request), size);
```

2022-03-13 19:17 UTC, jesserockz commented on esphome/components/canbus/canbus.cpp
> +    ESP_LOGD(TAG, "send extended id=0x%03x rtr=%d size=%d", can_id, remote_transmission_request, size);
```suggestion
    ESP_LOGD(TAG, "send extended id=0x%03x rtr=%s size=%d", can_id, TRUEFALSE(remote_transmission_request), size);
```

2022-03-13 20:27 UTC, danielschramm commented
Hello, I just setup a test system with both can interfaces at the same ESP32 to test all config options.

With his fork I currently cannot get any communication running at all so I have no results in testing the feature.
I will try again within the next days. 
Might be an issue with my windows installation need to try again.

2022-03-14 06:27 UTC, danielschramm commented
I just want to confirm that it is working for both controllers.

@jesserockz  Please merge.

2022-03-14 08:37 UTC, felixstorm commented
@jesserockz Thanks for your input - `cg.uint32` was probably just a copy and paste error on my side and concerning the logging I was just not aware of the existence of these macros. I am certainly fine with your suggestions.

Another idea that came to my mind: Would you prefer for me to add another class member method `send_data` with the old signature pointing to the changed `send_data` for backwards compatibility or are these kind of member methods considered internal and therefore anyway subject to change?

2022-03-15 22:09 UTC, jesserockz approved these changes
Yeah it could be good to have that method for compatibility, but not strictly necessary

2022-03-17 08:24 UTC, felixstorm commented
Thanks and sorry for the delay - will try to look into this over the weekend!

2022-03-20 15:57 UTC, felixstorm commented
@jesserockz I did add a `send_data` method with the old signature now, so it should now even be safe with any older code using this internal method.

2022-04-03 23:15 UTC, merged

2022-04-04 08:34 UTC, felixstorm commented
Thanks!