feedback cover: create component
OttoWinter/esphomeyaml pull request #3253
Opened 2022-02-25 02:25 UTC by ianchi

# What does this implement/fix?

This started as a custom cover, for my DIY project to add smart capabilities to an existing gate opener.
It needed both endstop sensors from `endstop_cover` and a variation of the movement sensor capabilities of `current_based` cover. But those components where very specific to a narrow hardware configuration.

Thus a made a new cover component that generalize this features, and allows greater flexibility, and unifies features.

The ``feedback`` cover platform allows you to create covers with position control that 
can optionally have feedback from sensors to detect the fully-open and fully-closed states (endstops), 
and from sensors to detect actual movement (opening/closing). In all the cases the current
position is approximated with the time the cover has been moving in a direction.

It supports *open*, *close*, *stop* and *toggle* actions. Tilt control is not supported.

The associated doc PR has a more thorough explanation.

In order to unify codebase al three covers (`time_based`, `endstop` and `current_based`) could be deprecated and eventually removed, as all their functionality is kept, unified and expanded. In the future, any new feature will be available to all covers.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes 
esphome/feature-requests#1329
esphome/feature-requests#778

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

    cover:
      - platform: feedback
        name: "Gate"

        open_action:
          - switch.turn_on: open_cover_switch
        open_duration: 2.1min
        open_endstop: open_endstop_binary_sensor
        open_sensor: open_movement_binary_sensor

        close_action:
          - switch.turn_on: close_cover_switch
        close_duration: 2min
        close_endstop: close_endstop_binary_sensor
        close_sensor: close_movement_binary_sensor

        stop_action:
          - switch.turn_off: open_cover_switch
          - switch.turn_off: close_cover_switch
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-03-04 03:07 UTC, ianchi commented
Hi, any comments/suggestions on this?

2022-03-16 21:26 UTC, ianchi commented
Hi, friendly ping.
Any comments on this?

2022-04-04 00:30 UTC, ianchi commented
Hi @jesserockz any chance to review this?

2022-04-25 02:58 UTC, ianchi commented
Hi any comments on this?

2022-04-26 20:17 UTC, jesserockz commented
Sorry @ianchi, I did start looking at this PR, and I will get to it again. I think its a good idea, I am just not familiar with all of the cover platforms so might take some time.

2022-04-27 01:37 UTC, ianchi commented
Great to hear that!
Please, let me know if I can help in any way.

2022-08-04 03:46 UTC, jesserockz requested changes
One thing I just noticed is missing, is `#ifdef USE_BINARY_SENSOR` around any code accessing binary sensor code as all of the binary sensors are optional in the config

2022-08-09 02:23 UTC, ianchi commented
Hi @jesserockz, 
I added the conditional compilation of binary sensors.

2022-08-09 03:52 UTC, jesserockz approved these changes

2022-08-09 05:21 UTC, merged