Pid new deadband
OttoWinter/esphomeyaml pull request #3254
Opened 2022-02-27 12:36 UTC by patrickcollins12

# What does this implement/fix?

I'm excited to contribute my first change to esphome.

I've been using the PID climate component for a few months as outlined in [this article](https://github.com/patrickcollins12/esphome-fan-controller). It works OK... but it has insufficient features to prevent hysteresis when the sensor gets close to the set point. Other PID controllers I've been looking at include features like deadband, deadband gain, derivative filtering and output filtering. So I've built those features, tested them and adding some tests too. Rather than explain in detail here these features, I suggest taking a look at the documentation updates I propose.

I welcome feedback and hope you approve of the change.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 
Yes I've created a pull request in esphome-docs. Will update it here.

esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:
```yaml
climate:
  - platform: pid
    name: "Console Fan Thermostat"
    id: console_thermostat
    sensor: console_fan_temperature
    default_target_temperature: 30°C
    cool_output: console_fan_speed

    # See the README for setting up these parameters.
    control_parameters:
      kp: 0.3
      ki: 0.001
      kd: 6
      max_integral: 0.0
      output_samples: 5      # << NEW!
      derivative_samples: 5  # << NEW!

    deadband_parameters:     # << NEW!
      threshold: 0.4
      kp_multiplier: 0.08
      ki_multiplier: 0.08
      kd_multiplier: 0.0
      output_samples: 15
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-03-03 09:59 UTC, nagyrobi commented
Thank you for this I've been thinking for a while how to implement these for my central heating of the entire house.

2022-04-24 14:17 UTC, patrickcollins12 commented
any interest in including this in the next release @OttoWinter ?

2022-05-30 18:22 UTC, nagyrobi commented
This is a useful contribution

2022-06-13 14:01 UTC, OttoWinter commented on esphome/components/pid/pid_controller.h
> +  std::list<float> derivative_list_;
Small optimization: don't use a list (which is implemented as doubly-ended queue), but rather a deque (or probably int array would work too since the size is constant). A list like this with many small objects can (and has in the past) result in slowly fragmenting the heap.

2022-06-13 14:06 UTC, OttoWinter commented on esphome/components/pid/climate.py
> +                    cv.Required(CONF_THRESHOLD_LOW): cv.temperature,
Unless I have something wrong, this fails when the user doesn't set `deadband_parameters` in their config (as the default above makes it validate the empty dict against these required keys)

2022-06-13 14:07 UTC, OttoWinter commented on esphome/components/pid/climate.py
> +                    cv.Required(CONF_THRESHOLD_LOW): cv.temperature,
In general, it's unintuitive too to have required keys inside optional config sections. I haven't looked at the meaning of these settings yet, but can't we just set them to 0 by default?

2022-06-13 14:08 UTC, OttoWinter commented on esphome/components/pid/climate.py
> +            cv.Optional(CONF_DEADBAND_PARAMETERS, default={}): cv.Schema(
```suggestion
            cv.Optional(CONF_DEADBAND_PARAMETERS): cv.Schema(
```

(removing {} here fixes the issue)

2022-06-20 17:50 UTC, OttoWinter commented on esphome/components/pid/climate.py
> +                    cv.Optional(CONF_STARTING_INTEGRAL_TERM, default=0.0): cv.float_,
This doesn't appear to be documented in the docs

2022-06-20 17:50 UTC, OttoWinter commented on esphome/components/pid/pid_controller.h
> +  /// Proportional gain K_p.
IMO these fields should be protected/private, not public

2022-06-20 17:50 UTC, OttoWinter commented on esphome/components/pid/climate.py
> +CONF_OUTPUT_SAMPLES = "output_samples"
```suggestion
CONF_OUTPUT_AVERAGING_SAMPLES = "output_averaging_samples"
```

I don't really like the name, as it doesn't tell you what it actually does. Perhaps adding `averaging` is better?

2022-06-22 06:05 UTC, patrickcollins12 commented on esphome/components/pid/climate.py
> +            cv.Optional(CONF_DEADBAND_PARAMETERS, default={}): cv.Schema(
perfect, thanks i missed that.

2022-06-22 14:20 UTC, patrickcollins12 commented
I think ready to merge.

2022-06-23 03:48 UTC, patrickcollins12 commented
@OttoWinter I resolved all of your issues. The only thing I did not agree with is, in the documentation I have kept the threshold_low/threshold_high in the example because I think a +/-0.5ºC deadband is a sensible default for the majority of PID controllers.

2022-08-02 12:37 UTC, patrickcollins12 commented
@jesserockz or @OttoWinter wondering if I could bother you to pass your eye over this and merge it. I'm confident it is working. But it we leave it longer it will go stale again. I'll happily resolve any bugs raised from others.

2022-08-07 20:14 UTC, jesserockz approved these changes
Please remove commented code.

2022-08-07 20:14 UTC, jesserockz commented on esphome/components/pid/climate.py
> +
I know this can be helpful to keep in for later, but we prefer no commented code please.

2022-08-14 22:47 UTC, jesserockz commented on .pre-commit-config.yaml
> +        files: ^((esphome|script|tests)/.+)?[^/]+\.py$
Please change in its own PR.

```suggestion
    - id: black
      args:
        - --safe
        - --quiet
      files: ^((esphome|script|tests)/.+)?[^/]+\.py$
```

2022-08-14 22:58 UTC, jesserockz requested changes

2022-08-14 22:58 UTC, jesserockz commented on esphome/components/pid/pid_controller.h
>  #pragma once
I think that this file has gotten big enough that it needs the function contents moved to a .ccp file please.

2022-11-29 21:56 UTC, jesserockz approved these changes

2022-11-29 21:58 UTC, merged