[RFC] Online PNG image support
OttoWinter/esphomeyaml pull request #3255
Opened 2022-02-27 19:33 UTC by guillempages

# What does this implement/fix?

This PR implements the possibility of downloading PNG images at runtime and showing them in a compatible display.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** partially fixes https://github.com/esphome/feature-requests/issues/1463

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
Not done yet; still too early

## Test Environment

- [x] ESP32 (Inkplate10)
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
online_image:
  - url: "https://www.example.org/image.png"
    id: example_image
    format: PNG

display:
  # ...
  lambda: |-
    it.image(0, 0, id(example_image));

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-02-27 19:34 UTC, guillempages commented
The code is still not 100% ready; when the images are big (i.e. the download takes too long), the ESP is rebooted by the watchdog before it has the change to display the image.

It would be nice, if someone familiar with the core workings of the firmware has some suggestions on how to improve / avoid the reboot.

2022-02-27 21:24 UTC, jesserockz commented
I am actually current rewriting the `http_request` component to be reusable inside other components to fetch remote data. This is mostly for ESP-IDF as the Arduino libs dont work there. This will allow other components to easy send a request and get the response and should help with this component.

2022-02-28 10:12 UTC, guillempages commented
@jesserockz I'm not sure it would help much here. Since the amount of RAM is limited, downloading the whole image into RAM and then decoding it would probably not work either, that's why the download and decoding is being done chunck-wise here. Or do you plan some sort of callbacks as well, so that the downloaded data can be processed while being downloaded instead of afterwards?

2022-03-02 03:42 UTC, jesserockz commented
I see, I didnt actually look at the code before commenting.
I don't think that it would be a good idea to download the image in the `draw` function though which is called during the display lambda. But I do not really see an alternative way right now tbh.

2022-03-03 13:19 UTC, nagyrobi commented
@guillempages how is this intended to work? One shot at boot, ie. download the image and then display it from memory and that's all?

Is there an action to re-download at runtime? For example, could be useful to refresh a remote image periodically and display it.

2022-03-05 15:09 UTC, guillempages commented
@nagyrobi The current implementation actually re-downloads the image every time it is displayed, since I wanted to use as little RAM as possible, and (especially if the image is big) the downloaded image might not fit in memory.
So the use case you mention (refresh periodically and displaying) is actually the only use case implemented ;-)

2022-04-03 21:10 UTC, osos commented
Is it possible to update the url dynamically e.g. based variables of status, mqtt messages etc?

2022-04-10 16:00 UTC, guillempages commented
@osos No, with the current implementation the URL is fixed at compile time. At least it is not something I have tried/implemented by design.
It might work (but haven't tried and as I said, it's not by design), by using some template on the URL part and updating that, since the image is downloaded anew every time.

2022-04-15 22:06 UTC, lux4rd0 commented
@guillempages - hello! And thank you for this! I've been looking to try something like this for a little while now!! However, I pulled your PR into my configuration and I'm not able to get it to display an image. Each time it goes to refresh, I get a reboot - even with a tiny image. My config:


```
substitutions:
  devicename: esp13
esphome:
  name: '${devicename}'
esp32:
  board: featheresp32
  variant: esp32
debug:
  update_interval: 60s
time:
  - platform: homeassistant
    id: ntp
external_components:
  - source: 'github://pr#3255'
    components:
      - display
      - online_image
logger:
  baud_rate: 0
  level: VERBOSE
switch:
  - platform: restart
    name: '${devicename} Restart'
  - platform: gpio
    pin:
      number: 21
      inverted: 'yes'
    id: '${devicename}_reset_switch'
    internal: true
    name: '${devicename} Display Reset Pin'
api:
  reboot_timeout: 1min
ota:
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: '${devicename}'
    password: !secret wifi_password
  power_save_mode: none
spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15
display:
  - platform: waveshare_epaper
    id: '${devicename}_display'
    cs_pin: GPIO12
    busy_pin: GPIO33
    reset_pin: GPIO21
    dc_pin: GPIO27
    model: 7.50inV2
    update_interval: 60s
    reset_duration: 2ms
    lambda: |-
      // Start
      it.image(0, 0, id(example_image));
button:
  - platform: template
    name: '${devicename} Refresh'
    icon: 'mdi:update'
    on_press:
      then:
        - component.update: '${devicename}_display'
online_image:
  - url: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png'
    id: example_image
    format: PNG

```

Any suggestions on where to look?

Thanks!

2022-04-17 11:58 UTC, guillempages commented
@lux4rd0 thanks for trying this out. Unfortunately, from the logs it looks like you encountered the issue I mentioned above, where the downloading takes longer than the watchdog timeout, and the device is tested before the image can be actually displayed 😔
I tried manually pinging the watchdog while downloading, but this feels like a hack and it did not fix the issue completely either.

I'm not sure if my approach will ever work or is compatible with the esphome philosophy, that's why I'd welcome comments/suggestions from a senior esphome developer.

In your case, if the image is small (and by that I mean download size, not number of pixels) maybe your esp is too far away from the router, so that it takes to long to download.

But as I said, the root cause it's the watchdog, and, I have no idea how to fix that at the moment 😢

2022-04-17 15:27 UTC, lux4rd0 commented
@guillempages thanks for the confirmation! The image in question is tiny - like 7kb - but the overall response time seems to be the culprit. :) I'm all for trying hacks LOL :) But I agree - it needs to fit into the esphome effort. I don't know enough to be much help there - just somebody who's enjoying the e-ink displays and wanting a dynamic way to update images at runtime.

I'll play around with it some more. Hopefully, somebody can pick up your efforts and help out.

Thanks again!!

2022-04-30 14:08 UTC, guillempages commented
@lux4rd0 sorry for the late reply; somehow I missed your edit. I had tried manually pinging the watchdog with "esp_task_wdt_feed()", and now I tried both the vTaskDelay mentioned in your link, and the "App.feed_wdt()" call I saw in some other ESPhome component.
When I try bigger images, I often see the final "xyz bytes decoded" from my code, and then immediately after the watchdog kicks in; I'm not sure if the problem is in my loop, or on the actual component that does the rendering afterwards. It might even be a combination of both.

2022-04-30 14:54 UTC, guillempages commented
@lux4rd0 I think I did it :-) 
Can you try the latest code? It looks like I was petting the watchdog at the wrong place; now I managed to test with a big online image, that took almost 5 Minutes! to download, but the watchdog did not kick in.
So now I think the code is finally ready for review :-)

2022-04-30 21:23 UTC, lux4rd0 commented
@guillempages I tried using a local network image and I succeeded in getting a black box the size of the expected image. Not sure how to [define the image](https://esphome.io/components/display/index.html?highlight=image#images) as black and white like other types of images.

I also tried to pull in other images and it seemed to get stuck in an out-of-memory loop but my debugging logs were somewhat sketchy as I kept losing access to the UART.

I think we're certainly closer!! Do you have a recommendation for getting the image to present properly? (maybe an example YAML or image that we could work on together?)

Thanks!

2022-04-30 22:00 UTC, lux4rd0 commented
```
[D][button:013]: 'esp13 Refresh' Pressed.
E (30807) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (30807) task_wdt:  - loopTask (CPU 1)
E (30807) task_wdt: Tasks currently running:
E (30807) task_wdt: CPU 0: IDLE
E (30807) task_wdt: CPU 1: loopTask
E (30807) task_wdt: Aborting.

abort() was called at PC 0x400f00a5 on core 0


Backtrace:0x400836c1:0x3ffbe9dc |<-CORRUPTED




ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:12776
load:0x40080400,len:3032
entry 0x400805e4
```



I'm using this configuration:

```
substitutions:
  devicename: esp13
esphome:
  name: '${devicename}'
  platformio_options:
    build_flags:
      - '-DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768'
esp32:
  board: featheresp32
  variant: esp32
  framework:
    type: arduino
    version: 2.0.2
    source: 'https://github.com/espressif/arduino-esp32.git#2.0.2'
    platform_version: >-
      https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
external_components:
  - source: 'github://pr#3255'
    components:
      - display
      - online_image
    refresh: 0s
debug:
  update_interval: 60s
time:
  - platform: homeassistant
    id: ntp
logger:
  baud_rate: 115200
  level: DEBUG
switch:
  - platform: restart
    name: '${devicename} Restart'
  - platform: gpio
    pin:
      number: 21
      inverted: 'yes'
    id: '${devicename}_reset_switch'
    internal: true
    name: '${devicename} Display Reset Pin'
api:
  reboot_timeout: 1min
ota:
  password: ota_password
wifi:
  ssid: wifi_ssid
  password: wifi_password
  ap:
    ssid: '${devicename}'
    password: wifi_password
  domain: .tylephony.com
  power_save_mode: none
spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15
display:
  - platform: waveshare_epaper
    id: '${devicename}_display'
    cs_pin: GPIO12
    busy_pin: GPIO33
    reset_pin: GPIO21
    dc_pin: GPIO27
    model: 7.50inV2
    update_interval: 60s
    reset_duration: 2ms
    lambda: |-
      it.image(0, 0, id(example_image_1));
      it.image(210, 0, id(example_image_2));
      it.image(420, 0, id(example_image_3));

button:
  - platform: template
    name: '${devicename} Refresh'
    icon: 'mdi:update'
    on_press:
      then:
        - component.update: '${devicename}_display'
online_image:
  - url: 'https://picsum.photos/200'
    id: example_image_1
    format: PNG
  - url: 'https://picsum.photos/200'
    id: example_image_2
    format: PNG
  - url: 'https://picsum.photos/200'
    id: example_image_3
    format: PNG
```

2022-04-30 22:53 UTC, lux4rd0 commented
A little more testing on this - was able to make a simple grayscale image - save it as PNG and link to it. It displayed correctly. Took another black and white image - and it just showed up as a black box. Either binary, grayscale, etc. - still a black box. I'm not sure what the differences are between what works and what doesn't. :)

2022-04-30 23:42 UTC, lux4rd0 commented
After a little more work - it looks like if I use an image with a transparent background - I'll get something to display.

![forecast](https://user-images.githubusercontent.com/30187533/166126078-664ef92f-76dc-4f4e-8076-4f15c892a3c5.jpg)

It doesn't seem to convert images to grayscale. It's binary black and white only. :)

In the image above I did a diffusion dither and then reset the transparency. Probably not the easiest pipeline but it's certainly working within some of the limitations of the display.

I'll do a little more testing and see what I can do... A few of the times I was playing with other images my esp32 did lock up and reset - so there's certainly something, not 100% - but I'll share what I find.

2022-05-01 00:38 UTC, lux4rd0 commented
Made a little more progress with an offline image converter...

![strikes](https://user-images.githubusercontent.com/30187533/166127232-b8ed3be7-2ac9-417c-9504-dc51dce59dfb.jpg)

The good news is that it's consistently pulling the image every 60 seconds :)

2022-05-01 13:20 UTC, guillempages commented
@lux4rd0 actually I had only tried with color images, some self-generated ones, a jpeg converted to PNG with imagemagik, and some downloaded from wikimedia.org (e.g.: https://upload.wikimedia.org/wikipedia/commons/d/d3/PSNR-example-base.png [warning: HUGE image; takes very long to download] or https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png and found no issues with them.
(My display is also black-and-white/greyscale; it's doing the conversion automatically. Maybe this is the difference?)
Do you have an example of a pure black and white image I could test with?

As for the question "Not sure how to [define the image](https://esphome.io/components/display/index.html?highlight=image#images) as black and white like other types of images.", I hadn't foreseen that. Other types of images are converted offline and uploaded as bitmaps into code; the PNG decoder I am using does not support those options AFAIK (should be able to handle all kinds of images though).

2022-05-01 14:27 UTC, guillempages commented
I think I might have found the reason why in some cases you only get black boxes: I've configured my display to "binary" (instead of greyscale), and then it treats all pixels as "white" as long as a single bit of the 32 bit color is "1". Meaning for (half-)transparent images, the alpha channel makes all pixels "on". 
I'm not sure how to proceed here. I could use the "color_on" and "color_off" parameters, and try converting color images to black&white (by using a threshold => no graphics processing or dithering), but to do that the decoder would need to know whether to use a "color" or a "monochrome" algorithm. And I don't think that specifying this on every image is the way to go.
Maybe the "display_buffer" class could offer this information? (Currently as far as I could see it is implemented on the child classes; it might be worth it to create some generic methods in the base class, that the children can use.) But IMHO this would have to be a separate PR.

@OttoWinter Sorry to bother you, but as far as I can see, the "display" component has no official code owner, and a lot of commits by you; what's your opinion on this? (Making display_buffer aware of its "color" mode, i.e. BINARY, GRAYSCALE, COLOR or similar). I'm not asking you to *do* that; just whether it's something worth pursuing, or you think it is not a good idea.

2022-05-01 16:41 UTC, lux4rd0 commented
@guillempages what kind of display do you have? I've been only using my Waveshare 7.5" (7.50inV2) - which is supposed to be grayscale - but is really (at least with what I've seen) - black and white. If I use an RGB image (or BW) - as long as it has a transparent background - it'll convert it to black and white (not grayscale). But since I can't effectively use grayscale images, only black and white - I need to dither, then apply a transparent background (most of the time, white). 

If I use your example image of the boats, I only get a black box. (but it does load!! Even if it takes a little while!) If I use the PNG transparent example - it shows the outline of the dice - but at least not a solid black box. :) But still - monochrome. (Looks like Mickey Mouse!)

I really wish I could get grayscale out of this Waveshare device... :)

2022-05-02 12:12 UTC, guillempages commented
@lux4rd0 I have an inkplate 10; which has a monochrome and a 3bit grayscale mode.
From what I could see in the code, the waveshare component only supports monochrome.

2022-05-02 14:48 UTC, lux4rd0 commented
@guillempages makes sense :) Appreciate the effort here! I tested on my Lilygo T5-4.7 inch with a grayscale driver and the images worked well as is, including transparent images. It seems that the monochromatic drivers are what's tripping up a bit here. Would be cool to see if there was an automatic dithering process to black and white... :)

2022-05-07 14:41 UTC, guillempages commented
@lux4rd0 I've implemented something for using monochrome displays. No dithering (I don't think we should misuse the processing power of the ESP32 to do onboard dithering, and also I am not an imaging expert, that could implement this here), but at least it can now display color/grayscale images with some sort of detail; not just black rectangles. Could you give it a try?

2022-05-09 11:09 UTC, Chief-T1 commented
Hi @guillempages 

Thanks for your work on this, it really will be a useful feature to have!
I'm getting a 3 colour e-ink display (black, white and red) later this week. 

I just wanted to confirm my understanding of how this currently works. 

So it can take a colour or B&W image from the web but during the download process it converts it to monochrome for the e-ink display?

Is this something where I would be able to do my own image processing to map the colours after it has been downloaded or would this not be possible due to it converting to monochrome during the download?

Thanks in advance for your help.

2022-05-09 12:47 UTC, guillempages commented
@Chief-T1 I haven't tested with multi-color e-ink displays; I have only tested with a grayscale e-ink that can also be run in monochrome mode (inkplate). I theory, for (full-)color displays, the code should also run out-of-the-box.
In your particular case, I'm not sure how the standard display handling works; my code might work in "color" mode, or it might produce very funny results.
Currently the color mode is automatically configured by displays in the core repository; it will probably not work (not even compile) for displays used as custom components.

The conversion to monochrome is only done, if the display is configured as a monochrome display; otherwise it tries to draw the image "as is", and lets the display driver do any needed color conversions.
The image "processing" is not configurable, currently it is just a very simple "convert color to grayscale and check if the value is > 127" method called basically for every pixel while the PNG is decoded.

2022-05-10 02:44 UTC, lux4rd0 commented
@guillempages I had a chance to pull a new build to test out the monochrome efforts you put together and I'm getting a build problem related to my Waveshare:

```
src/main.cpp: In function 'void setup()':
src/main.cpp:310:64: error: invalid new-expression of abstract class type 'esphome::waveshare_epaper::WaveshareEPaper7P5InV2'
   esp13_display = new waveshare_epaper::WaveshareEPaper7P5InV2();
                                                                ^
In file included from src/esphome.h:48:0,
                 from src/main.cpp:3:
src/esphome/components/waveshare_epaper/waveshare_epaper.h:330:7: note:   because the following virtual functions are pure within 'esphome::waveshare_epaper::WaveshareEPaper7P5InV2':
 class WaveshareEPaper7P5InV2 : public WaveshareEPaper {
       ^
In file included from src/esphome.h:18:0,
                 from src/main.cpp:3:
src/esphome/components/display/display_buffer.h:389:23: note: 	virtual esphome::display::DisplayType esphome::display::DisplayBuffer::get_display_type()
   virtual DisplayType get_display_type() = 0;
                       ^
Compiling /data/esp13/.pioenvs/esp13/lib64d/WiFi/WiFiGeneric.cpp.o
*** [/data/esp13/.pioenvs/esp13/src/main.cpp.o] Error 1
```

I'll try it with one of my Lilygos as soon as I can.

@Chief-T1 - I think in order for what you're asking to do, image processing will need to be done somewhere (similar to my ask about dithering...) Right now, in order for my images to work well, I have to map the color with something like ImageMagic. I'm using the method [outlined here](https://learn.adafruit.com/preparing-graphics-for-e-ink-displays/)...

2022-05-10 02:52 UTC, lux4rd0 commented
@guillempages same outcome, different display:

```
src/main.cpp: In function 'void setup()':
src/main.cpp:381:55: error: invalid new-expression of abstract class type 'esphome::lilygo_t5_47::LilygoT547Display'
   esp17_display = new lilygo_t5_47::LilygoT547Display();
                                                       ^
In file included from src/esphome.h:30:0,
                 from src/main.cpp:3:
src/esphome/components/lilygo_t5_47/display/lilygo_t5_47_display.h:13:7: note:   because the following virtual functions are pure within 'esphome::lilygo_t5_47::LilygoT547Display':
 class LilygoT547Display : public PollingComponent, public display::DisplayBuffer {
       ^
In file included from src/esphome.h:21:0,
                 from src/main.cpp:3:
src/esphome/components/display/display_buffer.h:389:23: note: 	virtual esphome::display::DisplayType esphome::display::DisplayBuffer::get_display_type()
   virtual DisplayType get_display_type() = 0;
                       ^
Compiling /data/esp17/.pioenvs/esp17/lib64d/WiFi/WiFiMulti.cpp.o
*** [/data/esp17/.pioenvs/esp17/src/main.cpp.o] Error 1
```

2022-05-14 13:28 UTC, guillempages commented
@lux4rd0 The compilation error is expected if you use custom display components; I've adapted all displays I could find in core and the waveshare one should actually be there :-( Very strange.

On the lilygo display, I cannot find the "display" subdirectory that is not working for you on my tree; maybe I am using an old version, or you might be using a beta one.

If you have the source code of the display component you are using, you could add 
```
display::DisplayType get_display_type() override { return display::DisplayType::DISPLAY_TYPE_MONOCHROME; }
```
to the header file implementing your display (lilygo_t5_47_display.h if I am seeing this right).
 
That said, maybe having this change as a breaking change is not the right way to go; I've asked for guidance from the senior developers on the other PR and on the dev channel; waiting for feedback. Nevertheless, if you could manually add the line and check, it would help a lot.

2022-05-14 14:13 UTC, guillempages commented
@lux4rd0 I've just tried compiling the first configuration you posted above (https://github.com/esphome/esphome/pull/3255#issuecomment-1100436248), and was able to compile without issues; I'm not sure what would be wrong with the waveshare configuration :-(

2022-05-14 15:30 UTC, lux4rd0 commented
Yikes. Thanks for testing. Let me try again and see what happens with that bare configuration.

2022-05-14 17:20 UTC, lux4rd0 commented
@guillempages I did a clean build on esphome prod and dev and still getting those errors. I'll need to dig in and see what's different...

2022-05-14 19:06 UTC, geiseri commented on esphome/components/online_image/online_image.h
> +  OnlineImage(const char *url, uint16_t width, uint16_t height, ImageFormat format)
Could this just be a subclass of `display::Image`?  Since it is only used as a pointer  virtual functions are an option.

2022-05-14 19:11 UTC, geiseri commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, DisplayBuffer *display, Color color_on, Color color_off) {
Having draw use http every time would cause some serious issues if there happened to be an error, or a hang.  It would be better to use a specialized component that would maintain the image.  That way the component can async load and decode the image while the draw is isolated.

2022-05-14 19:12 UTC, geiseri commented on esphome/components/online_image/__init__.py
> +    if CORE.is_esp8266 and not config[CONF_ESP8266_DISABLE_SSL_SUPPORT]:
Can you use the `http_request::HttpRequestComponent` for this?  It already handles this.

2022-05-14 19:17 UTC, geiseri commented on esphome/components/online_image/online_image.h
> +class ImageDecoder {
This actually might want to be the component.  You create a `ImageDecoder` component, and then pass is the `OnlineImage` and `HttpRequestComponent` ids.  Then as the request component is updated the image will be updated.  Then the display lambda will do the drawing as a normal image.

2022-05-14 19:19 UTC, geiseri commented on esphome/components/online_image/online_image.h
> +      : url_(url), width_(width), height_(height), format_(format){};
I would make the `url` a different method.  This could open up the ability to use locally stored images.  This would be nice on my inkplate.

2022-05-14 19:23 UTC, geiseri commented on esphome/components/online_image/__init__.py
> +IMAGE_FORMAT = {"PNG": ImageFormat.PNG}  # Add new supported formats here
At one point I asked @jesserockz about platforms.  Maybe we want something that allows for different decoders.  That way if someone wants TGA or some wacky format the core components are bloated.

2022-05-15 13:26 UTC, guillempages commented
@lux4rd0 I think I have found why it builds for me and not for you (and how to fix that ;-) )
In the latest versions of the PR, I have modified all the display components, so that they use the new method. This means, that in your "external_components" section, you need to specify "waveshare_epaper" in addition to "display" and "online_image".
After doing that, it builds fine as well for me. (And the reason it was building before was, because I was using my modified source tree, and not a pure "dev" branch).

2022-05-15 13:31 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, DisplayBuffer *display, Color color_on, Color color_off) {
The whole implementation is actually based on decoding during download. The image is not cached, since the amount of memory needed to store the image (without using psram; which might not be available on all devices) might be too big. Especially storing the decoded image is not feasible.

2022-05-15 13:33 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +    if CORE.is_esp8266 and not config[CONF_ESP8266_DISABLE_SSL_SUPPORT]:
My first tries on the feature were actually with the http_request, but I could not find a way of meaningfully add a callback while downloading (as said before; the decoding needs to happen during download, and not afterwards). So I put the download code in the png handling.

Also, the http_request component is actually the source of this code; I just copy&pasted it from there ;-)

2022-05-15 13:34 UTC, guillempages commented on esphome/components/online_image/online_image.h
> +class ImageDecoder {
As mentioned above, this might cause memory issues. Decoding is done "on the fly" while downloading.

2022-05-15 13:36 UTC, guillempages commented on esphome/components/online_image/online_image.h
> +      : url_(url), width_(width), height_(height), format_(format){};
I'm not sure what do you mean exactly by "make the ``url`` a different method".
I agree that having the possibility of using locally stored images would be a good thing to have, but i'd prefer to leave this functionality for a separate future PR, once the first implementation is done.
That change could be done in a backwards compatible way IMHO (the existing configurations/yaml files would not need to be changed; only the internal code).

2022-05-15 13:39 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +IMAGE_FORMAT = {"PNG": ImageFormat.PNG}  # Add new supported formats here
My approach was to have the different decoders on separate classes (I also have a JPEG decoder in mind, but haven't started on that implementation yet), and guarded by ``#ifdef ... #endif`` blocks, so that if they are not used, they are not compiled either. So it would "only" bloat the sources, but not cause additional flash usage; which IMHO would be ok.

OTOH, I'm not sure what you exactly mean by "platforms", so I might have totally misunderstood what you wanted to say ;-)

2022-05-15 14:03 UTC, lux4rd0 commented
@guillempages Thanks for the debugging assistance. Adding "waveshare_epaper" to the configuration and it compiled correctly. Will continue testing as soon as I can attach my esp32 to test. Thanks!

2022-05-15 18:48 UTC, guillempages commented on esphome/components/online_image/online_image.h
> +  OnlineImage(const char *url, uint16_t width, uint16_t height, ImageFormat format)
IIRC (it is a while since I started working on this), that was my first idea at the begining, but the ``display::Image`` class has too many methods and fields that would be unused then (the only common thing would be the name).
Also, the ``draw`` method on the ``display::DisplayBuffer`` component needs to handle both kind of images differently, so there is not really an advantage in having a common subclass.

2022-05-15 20:14 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, DisplayBuffer *display, Color color_on, Color color_off) {
Your comment made me think about the "failure cases" though, so I tested some of those and added some error handling code/error messages to the relevant code paths (i.e. during download).
Thanks!

2022-05-31 15:36 UTC, mmakaay commented
One idea, as a side-note to all this, is to make an external service responsible for doing the heavy lifting, in the form of a smart proxy. It's not a general solution, because not everybody will be able to host such a proxy, but it can be a nice addition in case one tries to display big photo files for example. 

I don't have the code for this anymore, but in the past I did create a proxy webservice (on a rpi in the LAN), which was used by an MCU to request photo files from the network. The proxy webservice took care of whacking the big photo files into the correct format (scaling, color reduction, dithering, the works), so all the MCU basicallly had to do was write the output of this service to the connected display. Thinking back, I think it could even have been streamed, taking up very little memory and CPU.

This type of offloading could be a solution direction for cases where the MCU cannot process the image because of resource issues.

2022-06-03 07:05 UTC, guillempages commented
@mmakaay I'm not sure where the bottleneck is, if it is in the decoding, or in the downloading of the images. I haven't done any detailed measurements, but from my experience, the download of the PNG takes longer than the decoding and displaying, and since PNG is already compressed, having to just push all the pixels through the network would probably cost more than it gains.
OTOH, if you are referring to some pre-processing like e.g. dithering or resizing (downsizing), then yes, it would probabably better to have a proxy service.

2022-06-03 11:39 UTC, mmakaay commented
> if you are referring to some pre-processing like e.g. dithering or resizing (downsizing), then yes, it would probabably better to have a proxy service.

Yeah, definitely. The idea was not to get down to the pixel level and send a raw pixel array to the device. The idea was to offload required pre-processing when needed, since that can overload the MCU easily. I mainly mentioned it for those who want to use (too) big images from the network. When implemented, it would of course be a totally separate project (and it wouldn't surprise me if there are loads of those available already).

2022-06-03 13:16 UTC, lux4rd0 commented
Exactly this. I have a script that runs the image fetch and dithering to a monochrome image that tosses it on a web server. Then I point this feature at that image rather than the original image. Works great! Can't wait to see this merged up! Nice job!

2022-06-03 13:29 UTC, guillempages commented
The first step in getting this merged is done; the dependency PR was merged today :-) @lux4rd0 this means, that once 2022.6 is out, you won't need the "waveshare" part on the "external_components" part, but also means that your lilygo component will stop compiling even without this PR in. I've submitted a PR to two of the repos mentioned in the lilygo thread, but it's a complex scheduling thing; that's the best I can do. At least there is an easy fix for that, if the external component repository is being actively maintained.

I'm not sure if the "needs-test" label is preventing this from being reviewed, or it's just that the reviewers with merge powers haven't had time yet to look into this. From my side, the PR is ready for a "serious" review ;-)

2022-06-05 21:57 UTC, lux4rd0 commented
Thanks again for your work on this @guillempages - most of my displays have now switched over to the Lilygo devices so I'll need to wait for them to make the appropriate updates. I'll see about using your PR on those as external references in the meantime! Thanks!

2022-06-06 12:55 UTC, guillempages commented
@lux4rd0 I created the PRs on two other repos; this was the third one on the thread, and I missed it :-D
Here you go: https://github.com/ashald/esphome/pull/1
I'm not sure whether this will work/compile; depends on the setup, since those repos are using an older version of ESPHome (i.e. not up to date with upstream).

2022-06-06 15:30 UTC, lux4rd0 commented
@guillempages It doesn't look like I can use pull requests from non-esphome git in the configuration. But I really appreciate you placing that in there for review. When I have a few extra minutes, I'll pull the file myself and see about testing it manually.

2022-06-06 22:04 UTC, jesserockz commented
@lux4rd0 you can test using the format: `source: github://<github_user>/<repo>@branch`

2022-06-06 22:53 UTC, lux4rd0 commented
@guillempages I'm using:

```
external_components:
  - source: 'github://ashald/esphome@lilygo-t5-47'
    components:
      - lilygo_t5_47
    refresh: 0s
  - source: 'github://pr#3255'
    components:
      - display
      - online_image
    refresh: 0s
```

But there's no way to link to the pull request until they merge it, correct?

2022-06-07 07:49 UTC, guillempages commented
@lux4rd0 Haven't tried that myself; just a shot in the dark based on jesse's comment, but you might want to try
``external_components:
  - source: 'github://guillempages/esphome@patch2'
    components:
      - lilygo_t5_47
    refresh: 0s
  - source: 'github://pr#3255'
    components:
      - display
      - online_image
    refresh: 0s
``
instead (replacing ashald's repo with my fork of it where I proposed the patch from).

2022-06-27 05:03 UTC, sdwilsh commented
I tried testing this out on my inkplate 10 device, as asked in #1463, but unfortunately, I'm getting a crash loop from the task watchdog once I try to use it.  My config can be found [here](https://gist.github.com/sdwilsh/fd0a52b755d065ffd698c1c8cbc6338f), and this is what the logs show:
```
[I][logger:243]: Log initialized
[C][ota:461]: There have been 3 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving preferences to flash...
[I][app:029]: Running through setup()...
[I][i2c.arduino:161]: Performing I2C bus recovery
[C][mcp23017:010]: Setting up MCP23017...
[D][binary_sensor:034]: 'Living Dashboard Status': Sending initial state OFF
[C][wifi:037]: Setting up WiFi...
[I][wifi:248]: WiFi Connecting to 'gravemind'...
E (7302) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (7302) task_wdt:  - loopTask (CPU 1)
E (7302) task_wdt: Tasks currently running:
E (7302) task_wdt: CPU 0: IDLE0
E (7302) task_wdt: CPU 1: loopTask
E (7302) task_wdt: Aborting.
abort() was called at PC 0x40158970 on core 0

ELF file SHA256: 0000000000000000

Backtrace: 0x4008e274:0x3ffbf890 0x4008e4ed:0x3ffbf8b0 0x40158970:0x3ffbf8d0 0x40089f61:0x3ffbf8f0 0x401909b3:0x3ffbc160 0x4015a27b:0x3ffbc180 0x40090cad:0x3ffbc1a0 0x4008f4f2:0x3ffbc1c0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
```

I'm using the ESPHome addon for Home Assistant, so I don't see a way for me to use esp-idf to symbolicate that, unfortunately.  Notably, if I remove the `lambda` from `display`, it does not trigger the task watchdog, so I suspect it's related to this PR.

2022-06-27 08:47 UTC, guillempages commented
@sdwilsh At a first glance, I cannot see anything wrong with your posted configuration :-( I have a very similar one.
The main differences I have spotted are, that I have a DHCP setup instead of a manually configured IP address (but I don't think this is an issue), and the I have 1800s as update interval on the display, instead of your 60s. Maybe this can cause an issue; the image is re-downloaded before it actually finished downloading the whole time, and it somehow misses to pet the watchdog.

What I find strange is, that I don't even see the log "Downloading image from xyz"; which should be printed after opening the http connection but before starting to download. I assume so, but it doesn't hurt to ask anyway: If you just comment out the "it.image()" line in your lambda; is the problem gone? Just to make 100% sure that the problem is with the online image downloading (again, I don't see where else it could be, but just to be completely sure).

I'll also try to reproduce it myself with your configuration, but I cannot commit on any timeslot for that.

2022-06-28 13:12 UTC, sdwilsh commented
> If you just comment out the "it.image()" line in your lambda; is the problem gone?

The problem does go away (tested with 1800 seconds update interval).

> I have 1800s as update interval on the display, instead of your 60s. Maybe this can cause an issue; the image is re-downloaded before it actually finished downloading the whole time, and it somehow misses to pet the watchdog.

I tried with:
* 120 seconds: problem persists
* 300 seconds: problem persists
* 1800 seconds: problem persists

It looks like the timeout doesn't matter.  It is interesting that the task watchdog always triggers trying to connect to wifi with this showing up just before in the logs:
```
[C][wifi:037]: Setting up WiFi...
[I][wifi:248]: WiFi Connecting to 'gravemind'...
```
In working builds, the next line would normally be:
```
[I][wifi:505]: WiFi Connected!
```

2022-07-02 13:20 UTC, guillempages commented
@sdwilsh I've just tried your configuration (copy&pasted it as-is; removed the "manual_ip" part to work with my network setup (I have DHCP running), and I was able to see the image; I am not getting any reset.

I'll have to dig deeper into this, but at the moment, I have no clue whatsoever why is is not working in your case :-(

2022-07-21 17:12 UTC, osos commented
Just tried with ILI9341 and esp32 dev board. Works a charm. However, png conversions seem slow.

Would it be possible to have a "RAW" format where the URL is treated like a data directly ready for the display.

like:
```
# Example config.yaml
online_image:
  - url: "https://www.example.org/image.ili.raw"
    width: 100
    height: 50
    id: example_image
    format: RAW
```
The raw file could then simply be bitbanged to the display based on the provided dimensions.

2022-07-25 01:14 UTC, velijv commented
Awesome project! But added to current config on my 
```yaml
esphome:
  comment: 'LILYGO TTGO T-Display st7789v (135x240) + BLE'
esp32:
  board: esp32dev
  framework:
    type: arduino
```

with multiple pages

```yaml
    pages: # screen size: 240x135 
      - id: page0
        lambda: |-    
...
      - id: page1
        lambda: |-    
```

it downloads the image, then crashes - device goes offline and physical buttons dont work. No log except device goes offline after download...

2022-08-09 09:42 UTC, velijv commented
> it downloads the image, then crashes - device goes offline and physical buttons dont work. No log except device goes offline after download...

Tried it on an empty **LILYGO TTGO T-Display st7789v** - but still using pages it crashes, even if the image is smaller than display resolution, and even 2kb in size.

2022-08-09 10:22 UTC, guillempages commented
Sorry, I haven't been able to look at this lately, and it will be at least
two weeks before I can. I also have a lilygo display, I'll try with that
one.

Veli Veromann ***@***.***> schrieb am Di., 9. Aug. 2022,
11:42:

> it downloads the image, then crashes - device goes offline and physical
> buttons dont work. No log except device goes offline after download...
>
> Tried it on an empty *LILYGO TTGO T-Display st7789v* - but still using
> pages it crashes, even if the image is smaller than display resolution, and
> even 2kb in size.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/3255#issuecomment-1209154020>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAS6VEYK34GUUYCXAKGJYALVYIRZ3ANCNFSM5PPLBLVQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-28 14:35 UTC, guillempages commented
@osos Sorry for the late reply.
Having additional image formats is something on my todo list (working on JPEG at first, but progress is very slow). But I'd like to get the basic component in, before adding more options to it. Having a RAW format might be a good idea in some cases; I hadn't thought about that.

2022-08-28 14:38 UTC, guillempages commented
@velijv I still have no clue what could be wrong in your case. Do you have many other components in your configuration? Have you tried a simple example just showing an image without any pages?

I'm not sure if this would be it, but one possible cause for the reset might be if you have a slow connection and the image takes too long to download, or if the memory gets exhausted.
I've added an option to configure the download buffer size; could you try playing with it? (e.g. setting the buffer size to 512 or 256, to allow the watchdog to be petted more often, and also reduce the RAM footprint).
You should just add ```buffer_size: 256``` to the image configuration.

2022-08-29 04:55 UTC, osos commented
This is what I have been using in another platformio project with an ILI9341 display:

Here the functions I used to build a imageproxy in PHP, which converts any image to a stream of raw pixels for the ili9341.
```

/**
 * converts images to 16-bit RGB565 raw data stream suitable for ILI9341 and similar
 * format:
 *  [ width (uint16) | height (uint16) | pixel stream (uint16 array[width*height]) ]
 *
 * @param [string:  $srcfilename]         url or local path to image file
 * @param [string:  $dstfilename]         local path to save raw stream to
 */
function saveRGB565($srcfilename, $dstfilename, $max_width = 240, $max_height = 320, $littleEndian = false) {
  $image = createImageFromFile($srcfilename);

  if (!$image)
    return;

  $file_w = fopen($dstfilename, 'w+');

  $width = imagesx($image);
  $height = imagesy($image);

  if ($width > $max_width || $height > $max_height) {
    $image = resizeImage($image, $max_width, $max_height);
    $width = imagesx($image);
    $height = imagesy($image);
  }

  $data = array();
  //fwrite( $file_w, pack('n', ) );
  //fwrite( $file_w, pack('n', $height) );
  fwrite( $file_w, pack('n', $width) );
  fwrite( $file_w, pack('n', $height) );

  for ($y = 0; $y < $height; $y++) {
    $y_array = array();
    for ($x = 0; $x < $width; $x++) {
      $rgb = imagecolorat($image, $x, $y);
      //echo $rgb." = ".decbin($rgb),"<br>";
      //$r = ($rgb >> 16) & 0xFF;
      //$g = ($rgb >> 8) & 0xFF;
      //$b = $rgb & 0xFF;
      $transparency = ($rgb >> 24) & 0x7F;
      // opacity*original + (1-opacity)*background = resulting pixel
      // 5-bit transparency
      $r = ((((127-$transparency) * (($rgb >> 16) & 0xFF)) / 127) & 0xF8) << 8; // + $transparency*0x000000; // (black)
      $g = ((((127-$transparency) * (($rgb >> 8) & 0xFF)) / 127) & 0xFC) << 3;  // + $transparency*0x000000; // (black)
      $b = ((((127-$transparency) * (($rgb) & 0xFF)) / 127) ) >> 3;             // + $transparency*0x000000; // (black)

      if (!$littleEndian)
        fwrite( $file_w, pack('n', $r | $g | $b) );
      else
        fwrite( $file_w, pack('v', $r | $g | $b) );
    }
  }
  //print_r($colors);
  fclose($file_w);
}

function createImageFromFile($filename, $use_include_path = false, $context = null, &$info = null)
{
    if (!$context)
      $context = stream_context_create(array( 'http' => array("timeout" => 15, 'protocol_version' => 1.1, 'header' => array('Connection: close') ) ) );
    // fetches fileconten from url and creates an image ressource by string data
    // if file is not readable or not supportet by imagecreate FALSE will be returnes as $imageRes
    $imageRes = imagecreatefromstring(file_get_contents($filename, $use_include_path, $context));

    if (!$imageRes)
      $imageRes = imagecreatefromstring(file_get_contents("questionmark.png", $use_include_path, $context));
    // export $http_response_header to have this info outside of this function
    if(isset($http_response_header)) $info["http"] = $http_response_header;

    imagepalettetotruecolor($imageRes); // ensure the image is RGB
    return $imageRes;
}

function resizeImage($image, $max_width, $max_height)
{
    $orig_width = imagesx($image);
    $orig_height = imagesy($image);

    $width = $orig_width;
    $height = $orig_height;

    # taller
    if ($height > $max_height) {
        $width = ($width * $max_height) / $height;
        $height = $max_height;
    }

    # wider
    if ($width > $max_width) {
        $height = ($height * $max_width) / $width;
        $width = $max_width;
    }

    $image_p = imagecreatetruecolor($max_width, $max_height);

    imagecopyresampled($image_p, $image, ($max_width-$width)/2, ($max_height-$height)/2, 0, 0,
                                     $width, $height, $orig_width, $orig_height);

    return $image_p;
}

```

On the esp ( I am sure this can be done much better):

```

// Images webproxy
const char* imageproxyurl = "http://some.domain.tld/espimages.php";

// Function to draw bitstream from espimages.php raw format.
//   first 16 bit = width of image
//   next  16-bit = height of image
//   rest         = raw bit-stream 565 rgb format for the ILI9341
bool drawImage(String imageurl, uint16_t x = 0, uint16_t y = 0, uint16_t max_width = 240, uint16_t max_height = 320) {
  if (imageurl.length() <= 4)
    return false;

  const unsigned int buffersize = 128;
  // create buffer for read
  uint8_t buff[buffersize] = { 0 };

  unsigned long startdraw = millis();
  bool returnval = false;
  HTTPClient http;
  uint8_t retry = 3;
  while (retry) {
    retry--;
    // configure server and url
    http.begin(imageproxyurl + String("?maxw=") + String(max_width) + String("&maxh=") + String(max_height) + String("&imgurl=") + imageurl);

    Serial.println("[HTTP] GET...");
    // start connection and send HTTP header
    http.setTimeout(10000); // milliseconds
    int httpCode = http.GET();

    if(httpCode > 0) {
      // file found at server
      if(httpCode == HTTP_CODE_OK) {
        // get lenght of document (is -1 when Server sends no Content-Length header)
        int total = http.getSize();
        int len = total;

        // get tcp stream
        WiFiClient * stream = http.getStreamPtr();

        int c = stream->readBytes(buff, 2);
        uint16_t width = (uint16_t)(buff[0])<<8 | (uint16_t)(buff[1]);
        len -= c;
        c = stream->readBytes(buff, 2);
        uint16_t height = (uint16_t)(buff[0])<<8 | (uint16_t)(buff[1]);
        len -= c;

        Serial.println( "DrawImage: Width=" + String(width) + "; Height=" + String(height) + "; http.getsize=" + String(total) );

        tft.setAddrWindow(x, y, x+width-1, y+height-1);

        uint32_t lastread = millis();
        size_t size;
        // read all data from server
        while(http.connected() && (len > 0 || len == -1)) {
            // get available data size
            size = stream->available();

            if(size > 1) {
                // read up to 128 byte
                c = stream->readBytes(buff, ( (size > buffersize) ? buffersize : size - (size % 2) ));

                //Serial.println("ImageBytes read: " + String(c));

                // write it to Serial
                //f.write(buff, c);
                tft.pushColors( (uint16_t*)buff, c/2, false);

                if(len > 0) {
                    len -= c;
                }
                lastread = millis();
            } else if ( millis() - lastread > 3000 )
              break;
            //else
            //  Serial.println("Size=" + String(size) + " len=" + String(len));

            yield();
        }
        if (len < 10) {
          retry = 0;
          returnval = true;
        } else {
          Serial.println(" [DrawImage failed] WiFi: RSSI=" + String(WiFi.RSSI()) + " vcc=" + String(ESP.getVcc()) );
        }
      } else {
        Serial.println(" [HTTP] httpCode:" + String(httpCode));
      }
    } else {
      Serial.println(" [HTTP] httpCode:" + String(httpCode));
    }
    http.end();
  } //while retry
  Serial.println( " [DrawImage] Total time: " + String(millis() - startdraw) + "ms");
  return returnval;
}
```

2022-09-09 18:34 UTC, Electronlibre2012 commented
> Just tried with ILI9341 and esp32 dev board. Works a charm. However, png conversions seem slow.
> 
> Would it be possible to have a "RAW" format where the URL is treated like a data directly ready for the display.
> 
> like:
> 
> ```
> # Example config.yaml
> online_image:
>   - url: "https://www.example.org/image.ili.raw"
>     width: 100
>     height: 50
>     id: example_image
>     format: RAW
> ```
> 
> The raw file could then simply be bitbanged to the display based on the provided dimensions.

that would be great! ;)

2022-09-15 19:01 UTC, guillempages commented
The Raw image implementation that @osos posted might work for the specific hardware that you have, but I'm not sure it can be done in a generic enough way (besides drawing pixel-by-pixel; which might still have performance drawbacks) by just using the current display_buffer abstraction. 
In any case, as I mentioned before, the first thing would be to get this merged, and afterwards, add support for additional formats.
JPEG is the next one on my list, but since the PR has been open for 7 months already, I'm not sure if it will ever be merged, and thus, my motivation to follow up on this is dwindling.

@Electronlibre2012 I agree that having some sort of lambda/template for the URL (i.e. being able to change the URL based on some dynamic information) would be great. But for this functionality, I don't even know how/where to start. And it should be a separate PR as well, to not over-complicate things (this is already complex enough; that might be the main reason why it's not being reviewed)

2022-09-17 12:16 UTC, Electronlibre2012 commented
hello @guillempages 

thanks for your feedback...so bad to read that "motivation to follow up on this is dwindling"...because its a nice idea to have make this platform 
```
online_image:
```
is potentially very usefull to add some nice preview to all display project in EspHome...there actually only possibility to add still image, in the flash memory, and ESP8266 and ESP32 has very limited flash memory...and SDCARD is not implemented yet in EspHome and perhaps will ne never, so there is no other solutions, instead of your work, to do that....

So bad there is not a lot of people interested in your work...perhaps some beers or coffees wouldnt have dwindling your motivation... ;)

Thanks for this work anyway! not usefull for me at this time because i will expect some lambda rendering for local http local adress as i explained above...

have a good day

2022-09-17 13:50 UTC, nielsnl68 requested changes

2022-09-17 13:50 UTC, nielsnl68 commented on esphome/components/online_image/online_image.h
> +class OnlineImage {
When you make OnlineImage inherent of Image you do not need to add new overrides to allow to display Online Images in the Display_Buffer. Possible that we need to change to the DisplayBuffer::Image() to start  your download procces.

2022-09-18 12:43 UTC, Electronlibre2012 commented
hello,

i found a way to convert .jpg to .png with imagemagik ([https://community.home-assistant.io/t/imagemagick/68390/6?u=olivier974](url) 
and it work fine, then i copy the image.png to /local/ folder of HA, and put
```
online_image:
  - url: 'http://192.168.1.50:8123/local/mynewfile.png'
    id: example_image
    format: PNG
```
but the esp32 reboot...just after buffer = 2042

i try to resize to 64x64 pixels...not luck...reboot

but this esp32 is a media_player and i think when its playing mp3 stream its to much for the ram...

Even if its not streaming music, the esp32 reboot

2022-09-18 13:11 UTC, guillempages commented on esphome/components/online_image/online_image.h
> +class OnlineImage {
When I started the implementation, inheriting from Image was the first thing I did. But then I found out, that it does not make much sense, since the image is never fully stored in memory, and thus the whole "get_XXX_pixel" methods in the Image class cannot return meaningful values.

The only thing that OnlineImage and Image have in common is that both have a width and height; otherwise they do not share any code. Also the way the image is drawn on the frame buffer is also completely different from the normal images (which go through the memory pixel-by-pixel). That's the main reason for the overload.

2022-09-18 15:05 UTC, guillempages commented
@Electronlibre2012 I don't think that the memory is the problem. I have a memory monitoring component running on my development inkplate (which I am using to develop and test the online image component), and the difference in memory between using online images, or not using the display at all, is just 40 KB (from 250KB free to 215KB Free in the worst case I have seen).

It might be that the watchdog kicks in, if the download of the current chunk takes too long, or if the display takes too long to process the pixels.
There is an option "buffer_size" that you can set in the image (like the url), the default is 2048, but maybe setting this to a lower value (256 is the minimum accepted) might allow the watchdog to be petted more often, and hopefully avoid the resets. Could you try that? (or have you already?)

Another reboot cause that I have found is in some displays, the code does not check for out of bounds (i.e. if the code tries to draw a pixel above the max height or max width). But if you resize your image to something smaller than the display, this shouldn't be the cause.
The online_image component was not checking for out-of-bounds itself and relying on the underlying display component to do that, in order to avoid doing the check twice when the display does check, but to be on the safe side, I've implemented the check now.

2022-09-18 17:32 UTC, Electronlibre2012 commented
Hello @guillempages 

thanks a lot for your efforts!

i have try with buffer_size :
```
online_image:
  - url: 'http://192.168.1.xx:8123/local/mynewfile.png'
    id: example_image
    format: PNG
    buffer_size: 256

[21:30:05][D][online_image:067]: Downloading image from http://192.168.1.50:8123/local/mynewfile.png
[21:30:05][D][online_image.png:046]: Buffer size: 256
INFO 192.168.1.75: Ping timed out!
INFO Disconnected from ESPHome API for 192.168.1.75
WARNING Disconnected from API
```

but still no luck and its a 64x64 pixel png image...

2022-09-18 20:11 UTC, guillempages commented
@Electronlibre2012 I don't know what else can be wrong :-( 
Have you tried a local image? (i.e. using just "image" instead of "online_image", and adding the test PNG to your local build). I suppose this would work, but who knows.

Also, could you try (if you haven't done so yet) just the very basic configuration? Just reading the online image and putting it into the display; without any music playing related component even configured?

How's your WiFi connection? Can it be, that it is a very slow connection (maybe the location of your ESP is not "ideal" in a Wireless sense) and thus the download rate is very slow?

Do you see the device reboot physically, or does it just lose the connection to the development machine (i.e. the online logs are not readable anymore). In some cases, the connection to the homeassistant/esphome instance is lost for a moment while downloading the image, but then it reappears. (But this shouldn't really happen for a small 64x64 image).

Do you have the possibility of getting the serial (i.e. not the wireless) logs and see the reboot reason?

2022-09-18 20:22 UTC, guillempages commented
@Electronlibre2012 Just to check if the issue is related to the watchdog, I have created a draft PR (#3823) that pings the watchdog really often. Could you try with this one (and add ´slow_drawing: True´ to the online_image configuration)? I don't think this will fix the issue, but might be worth a try.

2022-09-19 05:18 UTC, Electronlibre2012 commented
thanks @guillempages for your time,

its doesnt work better or worth.

For the wifi, i have an AP near to the ESP (5m, same room, no wall) so i dont think its related.

For the config, you are probably right, i mean, it has work on time with a https adress for an icon online...seems to be related to my media_player config.

i have made a test without media_player and sensors deleted before and it has worked...the bad is i need the media_player config...because this esp is a media player ;)

I can paypal you some 5 - 7€, depend on the place you live, the delivery is about 2€ and the ST7735 1.44" 128x128 is about 3€. Give me your Paypal name if you are interested to ;) [https://fr.aliexpress.com/item/1005003797803015.html?spm=a2g0o.order_list.0.0.12ad5e5bBt5vcc&gatewayAdapt=glo2fra](url)

2022-09-19 14:21 UTC, Electronlibre2012 commented
i prepare a very simple yaml : no sensors at all, only the display and fonts and color.

i try with PR (https://github.com/esphome/esphome/pull/3823) it works on ili9341 but it takes 1 minute to display the 64x64 png and crash after, no more connexion wifi, need to unplug the esp32.
```
[18:04:02][D][online_image:067]: Downloading image from http://192.168.1.50:8123/local/mynewfile.png
[18:04:02][D][online_image.png:045]: Buffer size: 256
INFO 192.168.1.27: Ping timed out!
INFO Disconnected from ESPHome API for 192.168.1.27
WARNING Disconnected from API
WARNING Can't connect to ESPHome API for 192.168.1.27: Hello timed out
INFO Trying to reconnect to 192.168.1.27 in the background
```


i try  with PR 3255
work after 2 minutes but crash after buffer_size and never reconnect : 
```
[17:56:50][D][online_image:067]: Downloading image from http://192.168.1.50:8123/local/mynewfile.png
[17:56:50][D][online_image.png:045]: Buffer size: 2048
INFO 192.168.1.27: Ping timed out!
INFO Disconnected from ESPHome API for 192.168.1.27
WARNING Disconnected from API
WARNING Can't connect to ESPHome API for 192.168.1.27: Hello timed out
INFO Trying to reconnect to 192.168.1.27 in the background
```

so no difference with all the config and simple config. Perhaps the problem is with the API of esphome, like the watchdog, if no response, the API disconnect...?? sorry i am not a developper like you.

one thing i notice is the 1st time your online_image is called, wifi is not yet connected and : 
```
[18:11:16][E][WiFiClient.cpp:232] connect(): connect on fd 54, errno: 118, "Host is unreachable"
[18:11:16][E][online_image:058]: Could not download image from http://192.168.1.50:8123/local/mynewfile.png. Error code: -1
```
perhaps that why it crash. After 3 secondes the wifi is connected : 
```
[18:11:19][I][wifi:505]: WiFi Connected!
```
and then, the 10s of the display update : 
```
[18:11:22][D][online_image:067]: Downloading image from http://192.168.1.50:8123/local/mynewfile.png
[18:11:22][D][online_image.png:045]: Buffer size: 256
[18:12:37][D][online_image:070]: Decoded 3342 bytes
[18:12:37][D][api:102]: Accepted ::FFFF:C0A8:132
```
and it reset API again : 
[18:16:22][D][esp32.preferences:113]: Saving 1 preferences to flash...
[18:16:22][D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[18:16:22][I][ota:105]: Boot seems successful, resetting boot loop counter.
[18:16:22][D][esp32.preferences:113]: Saving 1 preferences to flash...
[18:16:22][D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[18:16:22][D][api:102]: Accepted ::FFFF:C0A8:132
[18:16:22][W][api.connection:078]: Home Assistant 2022.9.5 (::FFFF:C0A8:132): Connection reset
```
and after that it seems to work:
```
[18:17:37][D][online_image:070]: Decoded 3342 bytes
[18:17:37][D][esp32.preferences:113]: Saving 1 preferences to flash...
[18:17:37][D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[18:17:37][D][api:102]: Accepted ::FFFF:C0A8:132
[18:17:37][D][api:102]: Accepted ::FFFF:C0A8:132
[18:17:37][W][api.connection:078]: Home Assistant 2022.9.5 (::FFFF:C0A8:132): Connection reset
[18:17:37][D][sensor:127]: 'Luminosite Digicode Ili9341': Sending state 754.38000 lux with 2 decimals of accuracy
[18:17:37][W][light:218]: 'Display Backlight Digicode Ili9341' - Brightness value 1.08 is out of range [0.0 - 1.0]!
[18:17:37][D][light:035]: 'Display Backlight Digicode Ili9341' Setting:
[18:17:37][D][light:050]:   Brightness: 100%
[18:17:37][D][light:084]:   Transition length: 1.0s
[18:17:37][D][online_image:067]: Downloading image from http://192.168.1.50:8123/local/mynewfile.png
[18:17:37][D][online_image.png:045]: Buffer size: 256
[18:18:52][D][online_image:070]: Decoded 3342 bytes
[18:18:53][D][esp32.preferences:113]: Saving 1 preferences to flash...
[18:18:53][D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[18:18:53][D][api:102]: Accepted ::FFFF:C0A8:132
[18:18:53][W][api.connection:080]: Home Assistant 2022.9.5 (::FFFF:C0A8:132): Connection closed
[18:18:53][W][api.connection:078]: Home Assistant 2022.9.5 (::FFFF:C0A8:132): Connection reset
[18:18:53][D][sensor:127]: 'Luminosite Digicode Ili9341': Sending state 699.92999 lux with 2 decimals of accuracy
[18:18:53][D][light:035]: 'Display Backlight Digicode Ili9341' Setting:
[18:18:53][D][light:050]:   Brightness: 100%
[18:18:53][D][light:084]:   Transition length: 1.0s
[18:18:53][D][online_image:067]: Downloading image from http://192.168.1.50:8123/local/mynewfile.png
[18:18:53][D][online_image.png:045]: Buffer size: 256
```

but it takes 1 minutes and 15 secondes to decode the image of 64x64 pixel...seems to be a problem...too long for the api perhaps

2022-09-19 15:16 UTC, Electronlibre2012 commented
i put logger in very_verbose : 
```
[19:14:00][D][online_image:067]: Downloading image from http://192.168.1.50:8123/local/mynewfile.png
[19:14:00][D][online_image.png:045]: Buffer size: 256
[19:15:15][D][WiFiClient.cpp:514] connected(): Disconnected: RES: 0, ERR: 128
[19:15:15][D][online_image:070]: Decoded 3342 bytes
[19:15:15][D][HTTPClient.cpp:400] disconnect(): tcp is closed
[19:15:15]
[19:15:15][V][component:199]: Component ili9341.display took a long time for an operation (75.15 s).
[19:15:15][V][component:200]: Components should block for at most 20-30ms.
[19:15:15][VV][scheduler:196]: Running interval '' with interval=60000 last_execution=35108 (now=156652)
[19:15:15][VV][scheduler:196]: Running interval 'update' with interval=20000 last_execution=78353 (now=156652)
```

2022-09-19 17:44 UTC, nielsnl68 commented
> i put logger in very_verbose :
> 
> ```
> [19:14:00][D][online_image:067]: Downloading image from http://192.168.1.50:8123/local/mynewfile.png
> [19:14:00][D][online_image.png:045]: Buffer size: 256
> [19:15:15][D][WiFiClient.cpp:514] connected(): Disconnected: RES: 0, ERR: 128
> [19:15:15][D][online_image:070]: Decoded 3342 bytes
> [19:15:15][D][HTTPClient.cpp:400] disconnect(): tcp is closed
> [19:15:15]
> [19:15:15][V][component:199]: Component ili9341.display took a long time for an operation (75.15 s).
>

I see that you are using the ili9341 display a sort while i go i found some issues with displaying the content (*moving buffer to the display)  Could you do the same test as you did with that PR as well? Maybe that resolves your issue

2022-09-20 08:47 UTC, Electronlibre2012 commented
thanks @guillempages for your time again ;)

i already try : 
```
online_image:
  - source: 'github://pr#3823'
    components:
      - display
      - online_image
    refresh: 0s
```
with
```
online_image:
  - url: 'http://192.168.1.50:8123/local/mynewfile.png'
    id: example_image
    format: PNG
    buffer_size: 256
    slow_drawing: true
```

the error log are with this PR, is that you mean i was suppose to try?

if so, already try with PR 3255 and 3823...same result

2022-09-21 23:09 UTC, landonr commented
I have it displaying on a lilygo tdisplay but it takes around 10s to load a 50x50 png

2022-12-06 16:14 UTC, marcrleonard commented
Curious if there has been any movement on this. I'd love this feature!

2022-12-06 16:26 UTC, Electronlibre2012 commented
yes me too...so bad...its a very nice feature!

2022-12-06 17:23 UTC, landonr commented
Is there a better file format for esp32 to display? We could use a imgproxy docker to optimize the files on a server

2022-12-08 19:54 UTC, guillempages commented
Thanks everyone for your interest.
When I started working on that almost one year ago I was fully motivated and thought it would help the community if I shared my implementation. Since then, there hasn't been an interest from the ESPHome maintainers, besides one review that basically asked for a big rewrite.
Unfortunately, private life has also taken a lot of my free time, so that I cannot commit to the re-implementation needed there.

Thanks a lot for the people who tested this and found issues. I was not able to reproduce them, and I'm not that familiar with how the whole ESPHome platform works to be able to find what the root cause of those issues are. It might be as @landonr mentiones that the pngle library is too slow (although it is the one used in the official inkplate SDK and works pretty well on mine).

 I tried splitting the (png-) decoding code to a separate class, so that it should be easy to support additional formats. If someone wants to try that, feel free.

2022-12-08 20:31 UTC, osos commented
@guillempages, just want to give you a big thank you.

I am already relying on this feature which has greatly simplified my setup. I hope you will be able to help keep it working, and that someone can help out to get it stabilized.

2023-01-19 16:55 UTC, ChristianFFB commented
![IMG_4025](https://user-images.githubusercontent.com/36458789/213506424-aa952349-6e52-4f4f-b3bb-f831f31ec2af.jpeg)
@guillempages - Thank you for your great work - love it ;) I was really struggling to get a graph with historic data on my display /w deep sleep.


online_image:
  - url: 'http://192.168.1.224/weewx/daywind.png'
    id: windbild
    format: PNG
  - url: 'http://192.168.1.224/weewx/daytempdew.png'
    id: tempbild
    format: PNG

it.image(310, 195, id(tempbild), COLOR_OFF, COLOR_ON);
it.image(310, 340, id(windbild), COLOR_OFF, COLOR_ON);

2023-01-22 20:45 UTC, krkeegan commented
Ugh, it is a shame it looks like this won't be supported in mainline releases.

Luckily, setting up an inkplate to display online images using arduino isn't too complicated.

2023-01-24 05:24 UTC, landonr commented
@ChristianFFB great work around!

is png support necessary? it might be easier to work with bmp files and use an imgproxy docker to convert the files on demand. bmp files without compression would be easier because its a pixel matrix which we can draw directly onto the screen

2023-02-24 15:34 UTC, marcrleonard commented
🎉

2023-04-19 22:16 UTC, guillempages commented
At anyone that might still be interested in this PR:

I did find the time to do another try on that; by following the recommendations I got from the different reviewers.

Since it is a very big rewrite of the code, I've created a new PR for that, instead of rewriting this one. It is still work-in-progress, but I (mostly) got it working for me. So if you want to try the next implementation (which at least has a non-zero chance of getting into mainline at some point, as opposed to this one ;-) ), the new pr is #4710.

It works in a slightly different way as this one; the image needs to be declared *and updated* in order to be displayed. By default it does not download the image, and then it won't display anything.

Also, as someone requested here, I've implemented an automation to be able to change the URL at runtime:
```
online_image.update_url:
  url: "https://www.example.com/new_image.png"
  id: image_id
```

I'll keep this PR open for a while, in case some people are still using it, but I plan to close that in the mid-term, and move on to the new one.

2023-08-01 01:43 UTC, nielsnl68 commented
ping

2023-08-02 11:00 UTC, guillempages commented
@nielsnl68 Actually I was waiting for the stale robot to mark this as stale, before closing; this PR is obsolete and has been replaced by #4710

2023-08-02 11:00 UTC, closed without merging

2023-08-02 13:42 UTC, nielsnl68 commented
> @nielsnl68 Actually I was waiting for the stale robot to mark this as stale, before closing; this PR is obsolete and has been replaced by #4710

Ha okay, i was not sure that was the case. Good that you close it now.