Tcs34725 auto
OttoWinter/esphomeyaml pull request #3258
Opened 2022-03-01 21:51 UTC by swifty99

# What does this implement/fix?

Bugfix: math behind gain factor was wrong by a magnitude. pow instead of multiply is needed.
Feature: add an auto mode for integration time and gain factor. The algorithm tries to achieve high accuracy with good dynamics. The sensor now can deliver proper lux and color temperature from below 1 lux up to 30k lux! 

For my needs I wanted to measure outdoor light with proper color temperature from direct sunshine to almost complete dark. The sensor can deliver, now the software can too.

## Types of changes

- [x ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
update of doc pending

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ x] ESP8266

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: tcs34725
    red_channel:
      name: "TCS34725 Red Channel"
    clear_channel:
      name: "TCS34725 Clear Channel"
    illuminance:
      name: "TCS34725 Illuminance"
    color_temperature:
      name: "TCS34725 Color Temperature"
    integration_time: auto
    address: 0x29
    update_interval: 2s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-03-01 21:55 UTC, dcousens commented on esphome/components/tcs34725/tcs34725.cpp
> +    integration_time_auto_ = false;
```suggestion
    this->integration_time_auto_ = false;
```

See https://esphome.io/guides/contributing.html#codebase-standards

2022-03-01 21:56 UTC, dcousens reviewed
A few code standard nits

2022-03-01 21:56 UTC, dcousens commented on esphome/components/tcs34725/tcs34725.cpp
> +    integration_time_auto_ = true;
```suggestion
    this->integration_time_auto_ = true;
```
```suggestion
    this->integration_time_auto_ = false;
```

See https://esphome.io/guides/contributing.html#codebase-standards

2022-03-01 21:56 UTC, dcousens commented on esphome/components/tcs34725/tcs34725.cpp
> +    if (!integration_time_auto_){
```suggestion
    if (!this->integration_time_auto_) {
```
```suggestion
    this->integration_time_auto_ = false;
```

See https://esphome.io/guides/contributing.html#codebase-standards

2022-03-01 22:21 UTC, swifty99 commented
@[dcousens](https://github.com/dcousens) thx for the comments, I will review and update tomorrow.

2022-03-02 18:51 UTC, swifty99 commented on esphome/components/tcs34725/tcs34725.cpp
> +    if (!integration_time_auto_){
fixed in https://github.com/esphome/esphome/pull/3258/commits/1972d5e78f768fc501c80b33c09e107b8739a577

2022-03-02 21:48 UTC, swifty99 commented
oh, boy, I need a better clang workflow.

2022-04-13 18:54 UTC, swifty99 commented
Hi everyone.

Could someone please have a look at this PR?
It works stable since weeks now, I do not see any reason to delay merging.

Jan

2022-04-14 01:32 UTC, jesserockz requested changes

2022-04-14 01:32 UTC, jesserockz commented on esphome/components/tcs34725/tcs34725.cpp
> +  if (integration_time == 0x100) {
```suggestion
  if (integration_time == TCS34725_INTEGRATION_TIME_AUTO) {
```

2022-04-14 01:32 UTC, jesserockz commented on esphome/components/tcs34725/tcs34725.h
> +  uint16_t integration_reg_{TCS34725_INTEGRATION_TIME_AUTO};
```suggestion
  uint16_t integration_reg_;
```

2022-04-14 21:31 UTC, jesserockz approved these changes

2022-05-12 04:53 UTC, merged