Implement unprevent deep sleep
OttoWinter/esphomeyaml pull request #3282
Opened 2022-03-10 19:01 UTC by rubdos

# What does this implement/fix?

`DeepSleepComponent::unprevent_deep_sleep()`, sets the prevention of deep sleep again to false.

Example use case: when the weather is sunny, the ESP runs on solar power, and I don't need deep sleep. When the weather becomes less perfect, re-enable the deep sleep timer.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes (none that I know)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
text_sensor:
  - platform: homeassistant
    name: "Weather From Home Assistant/OWM"
    entity_id: sensor.openweathermap_condition
    id: weather_condition
    on_value:
      then:
        - lambda: |-
            if (id(weather_condition).state == "sunny") {
              id(deep_sleep_1).prevent_deep_sleep();
            } else {
              id(deep_sleep_1).unprevent_deep_sleep();
            }
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

---

I still have to test this and push the documentation changes. The idea is that I also contribute those, right? Thanks for this great project!

2022-03-11 07:30 UTC, rubdos commented
I have this running now at home, Unprevent came up in the morning, seems to work fine. This should probably also get an action callable from yaml, I suppose?

2022-03-11 09:36 UTC, jesserockz requested changes
`allow_deep_sleep` sounds a little better.

Yes, please add a yaml action for this too.

2022-03-11 23:55 UTC, rubdos commented
I've pushed the other method name, I'll add the some time action next week.

2022-05-10 23:44 UTC, jesserockz approved these changes

2022-05-10 23:44 UTC, merged