Use the new update interval in PollinComponent::set_update_interval
OttoWinter/esphomeyaml pull request #3294
Opened 2022-03-14 21:42 UTC by fraxinas

# What does this implement/fix?

I tried modifying the update_interval of a display component by using the `set_update_interval` method without success.
It turns out that the PollingComponent base class only saves the update_interval variable in this method, but it is never used.
I changed it so that it cancels the original update interval and creates a new one with the new value.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
  - lambda: 'id(my_display).set_update_interval(5000);'
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-03-14 22:23 UTC, jesserockz requested changes
This should not directly set the interval in this function as it is only a setter and is called before the application code that actually sets up all component update schedules.

 Maybe a simpler function that just does the cancel and reschedule?
 
 ```c++
void PollingComponent::reschedule_update() {
  this->cancel_interval("update");
  this->set_interval("update", this->get_update_interval(), [this]() { this->update(); });
}
```

2022-03-15 08:45 UTC, fraxinas commented
Thank you for your review and suggestion, @jesserockz. I've done it a little differently, so that the new update interval could be set and re-registered with a one-liner command if desired.

2022-03-15 15:46 UTC, OttoWinter commented
Hmm, I don't think this is a good way to go about this issue. IMO it feels wrong to expose this directly to the user (especially when there's two methods now, `reschedule` and `set` update interval).
For one, the user would expect the next update after this call to happen after the newly given update interval, but in reality the `set_interval` function randomly schedules the first call (reason: so that the components don't get updated all at the same time).
I think the proper way to do this from the user side would be to disable the internal update interval by setting `update_interval: never`, and then use an `interval` component to do the updates manually with `component.update`.

2022-03-15 15:47 UTC, OttoWinter commented on esphome/core/component.cpp
> +  if (update_interval > 0)
Why only set it for update interval >0? Update interval 0 makes the `set_interval` execute the update as often as possible (every app cycle)

2022-03-15 15:53 UTC, fraxinas commented on esphome/core/component.cpp
> +  if (update_interval > 0)
the `update_interval` argument defaults to 0 in the header, so if `reschedule_update` is not explicitly called with a positive `update_interval` argument, it will then use the internal `update_interval` that had previously been set with `set_update_interval` and make that come into effect the way that @jesserockz had suggested.

2022-03-15 15:55 UTC, fraxinas commented on esphome/core/component.cpp
> +  if (update_interval > 0)
i wasn't aware a zero update_interval made any sense at all. but it could still be achieved by doing `set_update_interval(0) `followed by `reschedule_update()`

2022-03-15 18:51 UTC, jesserockz commented
@OttoWinter You are right and yeah we usually do tell people to use interval logic to alter the update_interval "on the fly". That slipped my mind when reviewing this and I do think that is the better option.

2022-03-15 20:48 UTC, ssieb commented
You could put a comment about that initial first update delay, this function is only going to be visible to someone checking the source code anyway.  It is definitely a useful function for some reasonably common use cases and the interval method can be somewhat complicated.  I don't think `reschedule` is a good name since it does imply that it specifically sets when the next time will happen.  And the check for the 0 parameter suggests that that was actually the intent here as well.  This function should change the stored update interval and recreate the interval timer.

2022-06-22 00:45 UTC, closed without merging