Support for MS8607 PHT (Pressure Humidity Temperature) sensor
OttoWinter/esphomeyaml pull request #3307
Opened 2022-03-16 21:47 UTC by e28eta

# What does this implement/fix?

The MS8607 ([datasheet](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FMS8607-02BA01%7FB3%7Fpdf%7FEnglish%7FENG_DS_MS8607-02BA01_B3.pdf%7FCAT-BLPS0018)) is a combined Pressure, Humidity, and Temperature sensor. It communicates over i2c, and has two different addresses (one for PT & the other for H).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/feature-requests#932

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

I don't know why it wouldn't work on all of these, but I don't have an ESP8266, and I haven't done anything with ESP32 IDF.

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: ms8607
    temperature:
      name: Temperature
    humidity:
      name: Humidity
    pressure:
      name: Pressure
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] **TODO:** Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-03-16 22:17 UTC, e28eta commented
Known next steps:

- [ ] pass CI checks ❤️ 
- [ ] pass code review
- [ ] create esphome/esphomedocs pull request
- [ ] verification that addition to `test5.yaml` is sufficient for "writing tests" step
- [ ] change PR if e28eta/esphome#1 is accepted

2022-03-16 22:40 UTC, e28eta commented on esphome/components/ms8607/ms8607.cpp
> +  this->humidity_i2c_device_ = make_unique<I2CDevice>();
I think I've correctly created the `I2CDevice`. clang-tidy yelled at me for using `new`.

This is being done in C++ instead of the generated code from `sensor.py` because I didn't want it to be possible to give them different `i2c_bus` objects. The two `I2CDevices` are literally connected to the same pins on the MS8607, but respond to different addresses.

2022-03-16 22:40 UTC, e28eta commented on esphome/components/ms8607/ms8607.cpp
> +        // 15ms delay matches datasheet, Adafruit_MS8607 & SparkFun_PHT_MS8607_Arduino_Library
The datasheet says "on startup, send reset, wait 15ms, then you can interact".

My first pass at this just had `delay(15); //NOLINT`, but when I looked at what it'd take to use `set_timeout` + skipping `update()` until finished, it didn't seem that bad.

It also allowed `set_retry` to be woven in pretty easily. I like that because I **have** seen occasional `NACK` to the initial reset commands, and that's why I put this PR on the back burner for ~18 months: it worked, but not always, and I haven't been able to figure out why. The esphome device almost never restarts, and so it was workable for me but not "production-ready"

2022-03-16 22:40 UTC, e28eta commented on esphome/components/ms8607/ms8607.cpp
> +// ms8607 supports 6 different settings
I don't actually plan to do this anytime (soon? ever?)... but it is possible.

2022-03-16 22:40 UTC, e28eta commented on esphome/components/ms8607/ms8607.cpp
> + * and it differs from the crc8 implementation that's already part of esphome.
I really wanted to just use the existing implementation of `crc8`, especially since I think they're both using [CRC-8-Dallas/Maxim](https://en.wikipedia.org/wiki/Cyclic_redundancy_check#Polynomial_representations_of_cyclic_redundancy_checks) in different forms ("reversed" vs "reversed reciprocal" based on the polynomials on wikipedia).

https://github.com/esphome/esphome/blob/e621b938e36b0b6ede82d14419a4830529789659/esphome/core/helpers.cpp#L50-L64

However, I don't actually understand much of what I was reading, and couldn't figure out how to used the existing `crc8` function on the bytes returned from the humidity sensor to verify the CRC provided. 😞

2022-03-16 22:40 UTC, e28eta commented on esphome/components/ms8607/ms8607.cpp
> +    ESP_LOGE(TAG, "Humidity status bit was not set to 1?");
I had trouble deciding whether to leave this log message in, fail the reading if it doesn't match, or skip the comparison completely since a failure is essentially ignored.

But this is where I ended up

2022-04-04 07:01 UTC, e28eta commented on esphome/components/ms8607/sensor.py
> +DEPENDENCIES = ["i2c"]
Any guidance on whether this should be `DEPENDENCIES` or `AUTO_LOAD`?

I see that most/all of the `I2CDevice` components use `DEPENDENCIES`, but since it works with _just_ `i2c:` in the yaml file it seems like this could/should be `AUTO_LOAD` to me.

2022-04-10 23:06 UTC, jesserockz commented on esphome/components/ms8607/sensor.py
> +DEPENDENCIES = ["i2c"]
We prefer to have these main busses as `DEPENDENCIES` so that people know what they are configuring.

2022-04-10 23:16 UTC, jesserockz commented on esphome/components/ms8607/ms8607.cpp
> +  this->humidity_i2c_device_ = make_unique<I2CDevice>();
This looks fine.

2023-01-18 03:32 UTC, e28eta commented
Needs minor update for #4251 being merged

2023-01-18 04:19 UTC, e28eta commented
Update completed in fdbde5a, ready for review again

2023-04-19 02:42 UTC, e28eta commented
Still waiting on review, afaik

2023-12-06 20:24 UTC, e28eta commented
Hi @jesserockz,

I just wanted to make sure this hadn’t fallen into a gap. Maybe a missing label, or something else that means you wouldn’t have seen it. I assume your main priorities are bugs & features that align with the project’s strategic goals, and that makes perfect sense to me. Based on 180 open PRs, I also assume that you’ve got a really long TODO list and I don’t envy you.

 I _think_ this is in good shape and ready to merge, but if there’s anything further _I_ can do I’d love to know it.

2023-12-21 04:50 UTC, jesserockz requested changes

2023-12-21 04:50 UTC, jesserockz commented on esphome/components/ms8607/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_TEMPERATURE])
```suggestion
    if temperature_config := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_config)
```

2023-12-21 04:50 UTC, jesserockz commented on esphome/components/ms8607/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_PRESSURE])
```suggestion
    if pressure_config := config.get(CONF_PRESSURE):
        sens = await sensor.new_sensor(pressure_config)
```

2023-12-21 04:50 UTC, jesserockz commented on esphome/components/ms8607/sensor.py
> +        cg.add(var.set_humidity_sensor_address(config[CONF_HUMIDITY][CONF_ADDRESS]))
```suggestion
    if humidity_config := config.get(CONF_HUMIDITY):
        sens = await sensor.new_sensor(humidity_config)
        cg.add(var.set_humidity_sensor(sens))
        # C++ class creates the I2CDevice object, using I2C bus already provided to the object
        cg.add(var.set_humidity_sensor_address(humidity_config[CONF_ADDRESS]))
```

2023-12-21 04:50 UTC, jesserockz commented on esphome/components/ms8607/ms8607.cpp
> +  this->humidity_i2c_device_ = make_unique<I2CDevice>();
After coming back to this PR, I think I would prefer if the humidity sensor had its own class that extended I2CDevice and it was created from codegen using `i2c.register_i2c_device`. I don't think the end user will give the two sensors a different I2CBus, and I would rather avoid small "hacks" like this in the codebase that might cause issues later on.

2024-03-04 01:08 UTC, jesserockz approved these changes

2024-03-04 21:49 UTC, merged

2024-03-04 23:08 UTC, e28eta commented
Thanks @jesserockz!