Allow to set user defined characters on LCD
OttoWinter/esphomeyaml pull request #3322
Opened 2022-03-22 20:30 UTC by numo68

# What does this implement/fix?

The LCD displays driven by lcd_base support the definition of user defined characters. This PR allows the user to use this feature.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  - platform: lcd_pcf8574
    id: my_lcd
    dimensions: 20x4
    address: 0x27
    user_characters:
      - position: 0
        data: [ 0x00, 0x0a, 0x00, 0x04, 0x04, 0x11, 0x0e, 0x00 ]
      - position: 7
        data: [ 0x00, 0x0a, 0x00, 0x04, 0x04, 0x00, 0x0e, 0x11 ]
      - position: 4
        data: [ 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01 ]
    lambda: |-
      it.print("Hello, world \x08 \x04 \x07!");

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-03-22 22:14 UTC, jesserockz commented
Kind of a duplicate of https://github.com/esphome/esphome/pull/3279

2022-03-22 22:29 UTC, jesserockz requested changes

2022-03-22 22:29 UTC, jesserockz commented on esphome/components/lcd_base/__init__.py
> +        cv.Optional(CONF_USER_CHARACTERS): cv.ensure_list(
This list should validate `cv.Length(max=8)`

And really should validate that position is unique, but that would be a custom validation

2022-03-23 09:48 UTC, numo68 commented on esphome/components/lcd_base/__init__.py
> +        cv.Optional(CONF_USER_CHARACTERS): cv.ensure_list(
added the validation including detection of duplicates

2022-03-24 06:37 UTC, jesserockz approved these changes

2022-03-24 06:37 UTC, merged