Add support for pvvx mithermometer display via ble client
OttoWinter/esphomeyaml pull request #3333
Opened 2022-03-25 12:32 UTC by puuu

# What does this implement/fix?

Add a pvvx_mithermometer display platform that allows to use devices running the [ATC_MiThermometer firmware](https://github.com/pvvx/ATC_MiThermometer) by pvvx as display drivers with ESPHome.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
esp32_ble_tracker:

ble_client:
- mac_address: "A4:C1:38:B1:CD:7F"
  id: pvvx_ble_display

display:
- platform: pvvx_mithermometer
  ble_client_id: pvvx_ble_display
  lambda: |-
    it.print_bignum(23.1);
    it.print_unit(pvvx_mithermometer::UNIT_DEG_C);
    it.print_smallnum(33);
    it.print_percent(true);
    it.print_happy(true);
    it.print_bracket(true);
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-03-26 11:44 UTC, nagyrobi commented
How do you ensure that the screen of the device is not overwirtten with local data?
AFAIK by default `pvvx` firmware Xiaomi Mijia LYWSD03MMC refreshes periodically the screen with its own sensors data. Is there a way for the user to know that the currently displayed information comes from the local sensor of the pvvx device or from a remote sensor through ESPHome?

2022-03-26 14:40 UTC, puuu commented
@nagyrobi Yes the pvvx firmware refresh the screen periodically (can be configured as minimum LCD refresh rate). You can configure different modes and the display will change between this modes with the LCD refresh rate, e.g. displaying the battery percentage or a clock. In addition, the pvvx firmware supports external data that is provided via BLE.

You can change all the configurations with a browser: [TelinkMiFlasher.html](https://pvvx.github.io/ATC_MiThermometer/TelinkMiFlasher.html). This tool also allows to set external data. The external data has a  validity time of how long this external data should be shown. The firmware switches then between the different views including the external data.

You can not directly recognizes if the data shown is local or external data, but by changing the smiley (e.g. no brackets) or the units it can be made somehow obviously. Also enabling the clock makes it more  obviously, then the cycles are: local data, clock, external data, clock and so on.

This platform only send the external data (and optional a timestamp) via BLE to the pvvx device. Configuration (like enabling the clock and refresh rate) of the pvvx device must be done by the user via e.g. browser.

I hope this answers your question. Thank you for asking, I will add some more information about this to the documentation.

2022-03-26 17:43 UTC, nagyrobi commented
Yes, that's why I was asking. The pvvx repo's documentation is not quite obvious (the guy is not a native English speaker) so imho we should add more detail here, related to this functionality.

2022-03-27 12:08 UTC, pasiz approved these changes
By me looks good so far. Please test it with different configurations to ensure all previous functionality is not affected in any means.

-Pasi

2022-03-30 09:56 UTC, puuu commented
@pasiz Thank you. I have this code running for weeks with 4 LYWSD03MMC. The configuration is similar to the examples in the documentation for this display platform. If by "previous functionality" you mean the sensor part, yes, that is not affected at all as long as the automatic disconnection is not disabled.

2022-04-03 19:55 UTC, jesserockz requested changes
Just a couple of minor changes, otherwise looks good.

2022-04-03 19:55 UTC, jesserockz commented on esphome/components/pvvx_mithermometer/display/__init__.py
> +        cg.add(var.set_auto_clear(config[CONF_AUTO_CLEAR_ENABLED]))
A default is provided so the config options is always there
```suggestion
    cg.add(var.set_auto_clear(config[CONF_AUTO_CLEAR_ENABLED]))
```

2022-04-03 19:55 UTC, jesserockz commented on esphome/components/pvvx_mithermometer/display/__init__.py
> +        cg.add(var.set_validity_period(config[CONF_VALIDITY_PERIOD].total_seconds))
Same here
```suggestion
    cg.add(var.set_validity_period(config[CONF_VALIDITY_PERIOD].total_seconds))
```

2022-04-23 07:13 UTC, puuu commented
@jesserockz  Sorry for my late reply.  The last commit introduces your minor changes.

2022-05-21 12:27 UTC, seeschloss commented
Great, I was working on the same kind of thing but using the 0x60 message (to choose each segment instead of sending higher-level data, because I wanted to display a few letters as well).

But I don't have time to make it clean enough to release it, so I'm glad you did this and I hope it gets merged soon. When I have time (not before a few months though) I might add a way to use the 0x60 to this component.

Anyway thanks for your work!

2022-06-10 05:46 UTC, puuu commented
@seeschloss thank you for your comment. I was not aware about the 0x60 message, but isn't it overwritten on every display refresh?

@jesserockz  what is the problem with this pull request? Why isn't it merged? I've made all the requested changes and the documentation has also been improved a long time ago.

2022-06-10 05:56 UTC, nagyrobi commented
@puuu he's alone doing it

2022-06-10 08:30 UTC, seeschloss commented
@puuu the 0x60 message stays displayed until you send a 0x61. A problem with it though that I just thought about, is that segments are different between devices so it would be complicated to use in a generic way (I didn't really have the problem since I only have one kind of device).

2022-08-13 00:59 UTC, puuu commented
Unfortunately, this pull request is IMHO ready to merge, but nothing happens. The bot was already trying to close the documentation pull request again, so I will pump this pull request as well.

2022-08-14 22:31 UTC, jesserockz approved these changes

2022-08-14 22:56 UTC, merged