Add support for TM1638 Led and Key component
OttoWinter/esphomeyaml pull request #3340
Opened 2022-03-27 23:25 UTC by skykingjwc

# What does this implement/fix?

Adds a component for the TM1638 Led and Key PCB

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs# 1991

## Test Environment

- [X ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

display:
    platform: tm1638
    id: tm1638_display
    stb_pin: 5
    clk_pin: 18
    dio_pin: 23
    intensity: 5
    update_interval: 5s
    lambda: |-
      it.print("0123");

switch:
   - platform: tm1638
     id: MyLed
     led: 0

#Pressing the left most button will turn on the left most LED.
binary_sensor:
  - platform: tm1638
    name: "My Button"
    id: MyButton
    key: 0
    filters:
      - delayed_on: 10ms
    on_press:
     then:
        - switch.turn_on: MyLed
    on_relase
     then:
        - switch.turn_off: MyLed

```

## Checklist:
  - [X ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-03-28 00:03 UTC, skykingjwc commented
This isn't for the TM1637.  Not sure why that label was added.

2022-04-03 23:55 UTC, ssieb requested changes
Why is the `tm1637` directory included in this PR?
I've tested this and it works.

2022-04-03 23:55 UTC, ssieb commented on esphome/components/tm1638/tm1638.cpp
> +      this->buffer_[pos] = data;
There's a valid compile warning at this line.  `data` won't be initialized if the character is outside of the range in line 175.

2022-04-03 23:55 UTC, ssieb commented on esphome/components/tm1638/tm1638.cpp
> +      this->buffer_[pos] |= 0b10000000;  // handles the decimal point or period
What happens if there is more than one `.` in a row?  You will collapse them all into a single dot.

2022-04-14 17:58 UTC, skykingjwc commented on esphome/components/tm1638/tm1638.cpp
> +      this->buffer_[pos] |= 0b10000000;  // handles the decimal point or period
Just pushed a fix.
https://github.com/esphome/esphome/pull/3340/commits/a91bed1c140802ee598e1c44ed7bd5b388405f7d

2022-04-14 18:00 UTC, skykingjwc commented on esphome/components/tm1638/tm1638.cpp
> +      this->buffer_[pos] = data;
I agree that this needs to be addressed, but I am not seeing a compiler warning when I build using the command
`esphome run ..\tests\TM1638test.yaml  --device COM3`

TM1638text.yaml is the config file I'm using for testing.

How are you getting the warning to display?  I'll want to reproduce is, so I can verify that it is fixed.

2022-04-14 20:07 UTC, ssieb commented on esphome/components/tm1638/tm1638.cpp
> +      this->buffer_[pos] = data;
I just did `esphome compile` (or `run`):
```
Compiling .pioenvs/switchtest/src/esphome/components/tm1638/tm1638.cpp.o
src/esphome/components/tm1638/tm1638.cpp: In member function 'uint8_t esphome::tm1638::TM1638Component::print(uint8_t, const char*)':
src/esphome/components/tm1638/tm1638.cpp:198:26: warning: 'data' may be used uninitialized in this function [-Wmaybe-uninitialized]
  198 |       this->buffer_[pos] = data;
      |       ~~~~~~~~~~~~~~~~~~~^~~~~~
```

2022-04-15 15:49 UTC, skykingjwc commented on esphome/components/tm1638/tm1638.cpp
> +      this->buffer_[pos] = data;
Got it.  Fixed has been pushed to the repo.
https://github.com/esphome/esphome/pull/3340/commits/cca3408856e91266842173000788c21569400750

2022-04-15 15:53 UTC, skykingjwc commented on esphome/components/tm1638/tm1638.cpp
> +      this->buffer_[pos] = data;
> Hey there @glmnet, mind taking a look at this pull request as it has been labeled with an integration (`tm1637`) you are listed as a [code owner](https://github.com/esphome/esphome/blob/dev/CODEOWNERS#L204) for? Thanks! (message by CodeOwnersMention)

How can we get the TM1637 tag removed?  The TM1637 has nothing to do with this PR.

2022-04-15 17:26 UTC, skykingjwc commented on esphome/components/tm1638/tm1638.cpp
> +      this->buffer_[pos] = data;
I merged from dev, and it seems to have resolved the TM1637 issue

2022-04-17 20:26 UTC, skykingjwc commented
Addressed all clang issues, linked documentation PR, added tests for new component in tests folder.

2022-08-06 23:36 UTC, ssieb approved these changes

2022-08-25 03:58 UTC, jesserockz commented on esphome/components/tm1638/output/tm1638_led.cpp
> +  //ASK SSIEB about this
```suggestion
  LOG_BINARY_OUTPUT("", "TM1638 LED", this);
```

2022-08-30 03:17 UTC, skykingjwc commented on esphome/components/tm1638/output/tm1638_led.cpp
> +  //ASK SSIEB about this
Removed comments

2022-08-30 22:00 UTC, jesserockz commented on esphome/components/tm1638/output/tm1638_led.cpp
> +  //ASK SSIEB about this
You missed the point of my suggestion, it was to change to LOG_BINARY_OUTPUT, not just remove the comments...

2022-08-30 22:02 UTC, jesserockz commented on tests/tm1638test.yaml
> +esphome:
You need to add to an existing test file (1,2,3,4,5), new files are ignored

2022-08-31 00:22 UTC, skykingjwc commented on esphome/components/tm1638/output/tm1638_led.cpp
> +  //ASK SSIEB about this
My bad,  must have been getting tired. 
Added LOG_BINARY_OUTPUT
c0f9d8b

2022-08-31 00:22 UTC, skykingjwc commented on tests/tm1638test.yaml
> +esphome:
Will do

2022-08-31 01:46 UTC, jesserockz commented on tests/tm1638test.yaml
> +esphome:
Dont forget to delete this yaml file too

2022-08-31 01:51 UTC, jesserockz requested changes

2022-08-31 01:51 UTC, jesserockz commented on esphome/components/tm1638/switch/__init__.py
> +TM1638SwitchLed = tm1638_ns.class_("TM1638SwitchLed", switch.Switch)
```suggestion
TM1638SwitchLed = tm1638_ns.class_("TM1638SwitchLed", switch.Switch, cg.Component)
```

2022-08-31 01:51 UTC, jesserockz commented on esphome/components/tm1638/switch/__init__.py
> +)
```suggestion
).extend(cv.COMPONENT_SCHEMA)
```

2022-08-31 01:51 UTC, jesserockz commented on esphome/components/tm1638/switch/__init__.py
> +    await switch.register_switch(var, config)
```suggestion
    var = await switch.new_switch(config)
    await cg.register_component(var, config)
```

2022-08-31 01:51 UTC, jesserockz commented on esphome/components/tm1638/output/__init__.py
> +TM1638OutputLed = tm1638_ns.class_("TM1638OutputLed", output.BinaryOutput)
```suggestion
TM1638OutputLed = tm1638_ns.class_("TM1638OutputLed", output.BinaryOutput, cg.Component)
```

2022-08-31 01:51 UTC, jesserockz commented on esphome/components/tm1638/output/__init__.py
> +)
```suggestion
).extend(cv.COMPONENT_SCHEMA)
```

2022-08-31 01:51 UTC, jesserockz commented on esphome/components/tm1638/output/__init__.py
> +    await output.register_output(var, config)
```suggestion
    await output.register_output(var, config)
    await cg.register_component(var, config)
```

2022-09-01 00:35 UTC, skykingjwc commented on tests/tm1638test.yaml
> +esphome:
Deleted tm1638test.yaml from repo

2022-09-04 07:36 UTC, ssieb requested changes

2022-09-04 07:36 UTC, ssieb commented on esphome/components/tm1638/binary_sensor/__init__.py
> +    await binary_sensor.register_binary_sensor(var, config)
```suggestion
    var = await binary_sensor.new_binary_sensor(config)
```

2022-09-04 07:36 UTC, ssieb commented on esphome/components/tm1638/tm1638.cpp
> +void TM1638Component::reset_(bool on_off) {
I don't see anywhere that this is called with `true`, so you can remove the parameter.

2022-09-04 07:36 UTC, ssieb commented on tests/tm1638test.yaml
> +esphome:
It's still here.  You need to `git rm` it.

2022-09-04 22:24 UTC, skykingjwc commented on esphome/components/tm1638/tm1638.cpp
> +void TM1638Component::reset_(bool on_off) {
Removed unnecessary parameter

2022-09-12 07:27 UTC, ssieb approved these changes

2022-09-12 07:37 UTC, ssieb commented
I will commit after verifying something with the contributor.

2022-09-12 15:30 UTC, merged