Enhances number component, allows to increment by value and toggle to min/max values, adds same feature to web_api for number
OttoWinter/esphomeyaml pull request #3352
Opened 2022-04-03 14:13 UTC by Araminog

# What does this implement/fix?

* Implements increment and toggle calls for the number component, in addition to existing set_value call.
* Adds the same features to web_api for control via http POST requests

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
esphome:
  name: rgbwone

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "***"
  password: "***"
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "***"
    password: "***"

captive_portal:

number:
  - platform: template
    name: "WhiteBrightness"
    optimistic: true
    min_value: 0
    max_value: 255
    step: 1
    on_value:
      then:
        - light.turn_on:
            id: trial_lights
            transition_length: 0.1s
            white: !lambda "return x/255.0;"
  - platform: template
    name: "RGBBrightness"
    optimistic: true
    min_value: 0
    max_value: 255
    step: 1
    on_value:
      then:
        - light.turn_on:
            id: trial_lights
            transition_length: 0.1s
            color_brightness: !lambda "return x/255.0;"

light:
  - platform: rgbw
    id: trial_lights
    name: "TrialLights"
    red: red_component
    green: green_component
    blue: blue_component
    white: white_component

output:
  - platform: esp8266_pwm
    id: red_component
    pin: D0
  - platform: esp8266_pwm
    id: green_component
    pin: D1
  - platform: esp8266_pwm
    id: blue_component
    pin: D2
  - platform: esp8266_pwm
    id: white_component
    pin: D3

web_server:
  port: 80
  version: 2
  local: true
```
The above can be controlled like this with POST requests via http:

`curl -i -X POST "http://rgbwone.local/number/whitebrightness/inc?value=-10"`
`curl -i -X POST "http://rgbwone.local/number/rgbbrightness/inc?value=-10"`
Reduces white or rgb brightness by 10.

`curl -i -X POST "http://rgbwone.local/number/whitebrightness/inc?value=10"`
`curl -i -X POST "http://rgbwone.local/number/rgbbrightness/inc?value=10"`
Increases white or rgb brightness by 10.

`curl -i -X POST "http://rgbwone.local/number/whitebrightness/set?value=128"`
`curl -i -X POST "http://rgbwone.local/number/rgbbrightness/set?value=128"`
Sets white or rgb brightness to 50%.

`curl -i -X POST "http://rgbwone.local/number/whitebrightness/tog"`
`curl -i -X POST "http://rgbwone.local/number/rgbbrightness/tog"`
Toggles white or rgb brightness between min and max values (all off or all on)

## Checklist:
  - [x] The code change is tested and works locally.

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

Will update the documentation soon and then update this pull request with the pull request for documentation accordingly.

2022-04-03 16:26 UTC, nagyrobi commented
Like the increase possibility. I use something similar to control [volume level](https://github.com/nagyrobi/home-assistant-configuration-examples/blob/main/esphome/samsung_amiko_ir_to_linkplay_volume.yaml) but with lambdas.

2022-04-03 19:34 UTC, jesserockz requested changes
Please use long proper names for the classes, `NumberIncrementAction` `NumberToggleAction`

2022-04-03 19:34 UTC, jesserockz commented on esphome/components/number/__init__.py
> +NumberTogAction = number_ns.class_("NumberTogAction", automation.Action)
You didn't actually define these classes?

2022-04-09 09:18 UTC, Araminog commented on esphome/components/number/__init__.py
> +NumberTogAction = number_ns.class_("NumberTogAction", automation.Action)
Yes, sorry, that is my bad. I added the class definitions (and changed their names). I have also add a second yaml file in the main comment of the pull request which i used to test the number actions tog and inc.

BTW, did you want me to change the action names, too? I have refrained from doing that for now because then i have to change the documentation as well ... but can do if required ;)

I also removed one commit from the pull request branch that was there accidentally (from pull request #3325).

And i ran clang-format (that was new to me, electrical engineer here, you always learn something when you do something for the first time) and it is clean now (still have to do that for the other pull request though).

2022-04-10 20:55 UTC, jesserockz requested changes

2022-04-10 20:55 UTC, jesserockz commented on esphome/components/number/__init__.py
> +    "number.inc",
Please do change these and update the docs PR
```suggestion
    "number.increment",
```

2022-04-10 20:55 UTC, jesserockz commented on esphome/components/number/__init__.py
> +    "number.tog",
```suggestion
    "number.toggle",
```

2022-04-15 15:57 UTC, Araminog commented on esphome/components/number/__init__.py
> +    "number.tog",
Implemented now. Had to recreate the pull request for the documentation update because i messed up switching to the correct branch next instead of current. But this change is now reflected in the new pull request esphome/esphome-docs#2021 . Also changed the web_api strings inc and tog to increment and toggle, so stuff is consistent.

2022-04-15 15:57 UTC, Araminog commented on esphome/components/number/__init__.py
> +    "number.inc",
Implemented and documented.

2022-04-18 19:36 UTC, jesserockz commented on esphome/components/web_server/web_server.cpp
> +        (!request->hasParam("value") && (match.method == "set" || match.method == "increment"))) {
This feels to me like it should be a different error in the case that `value` is missing, maybe a `400` or a `422`

2022-04-19 07:51 UTC, Araminog commented on esphome/components/web_server/web_server.cpp
> +        (!request->hasParam("value") && (match.method == "set" || match.method == "increment"))) {
Implemented.

2022-05-15 16:21 UTC, Araminog commented
Since there is a different pull request improving the number implementation (#3429) and the toggle feature can most likely be added with a lambda, i shall close this pull request :)

2022-05-15 16:21 UTC, closed without merging