Add support for MPL3115A2 Pressure/Altitude and Temperature Sensor
OttoWinter/esphomeyaml pull request #3371
Opened 2022-04-10 19:18 UTC by kbickar

# What does this implement/fix?

Adds support for the MPL3115A2 Pressure/Altitude and Temperature Sensor
https://www.adafruit.com/product/1893
https://www.nxp.com/docs/en/data-sheet/MPL3115A2.pdf

Note that this is dependent on https://github.com/esphome/esphome/pull/3370

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/771

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
 - platform: mpl3115a2
    temperature:
      name: "MPL3115A2 Temperature"
    pressure:
      name: "MPL3115A2 Pressure"
    update_interval: 10s
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-04-10 22:00 UTC, jesserockz requested changes

2022-04-10 22:00 UTC, jesserockz commented on esphome/components/mpl3115a2/mpl3115a2.h
> +#define MPL3115A2_ADDRESS (0x60)  ///< default I2C address 1100000
This can be deleted
```suggestion
```

2022-04-10 22:00 UTC, jesserockz commented on esphome/components/mpl3115a2/mpl3115a2.h
> +#define MPL3115A2_REGISTER_STARTCONVERSION (0x12)  ///< start conversion
Not used?
```suggestion
```

2022-04-10 22:00 UTC, jesserockz commented on esphome/components/mpl3115a2/mpl3115a2.cpp
> +  }
Could be better to do `set_timeout(100, ...)` that does a single status check and continues or returns? Instead of blocking execution for up to 100ms?

2022-04-10 22:00 UTC, jesserockz commented on esphome/components/mpl3115a2/mpl3115a2.cpp
> +    int32_t alt = uint32_t(buffer[0]) << 24 | uint32_t(buffer[1]) << 16 | uint32_t(buffer[2]) << 8;
```suggestion
    int32_t alt = encode_uint32(buffer[0], buffer[1], buffer[2], 0);
```

2022-04-10 22:00 UTC, jesserockz commented on esphome/components/mpl3115a2/mpl3115a2.cpp
> +    uint32_t p = uint32_t(buffer[0]) << 16 | uint32_t(buffer[1]) << 8 | uint32_t(buffer[2]);
```suggestion
    uint32_t p = encode_uint32(0, buffer[0], buffer[1], buffer[2]);
```

2022-04-10 22:00 UTC, jesserockz commented on esphome/components/mpl3115a2/mpl3115a2.cpp
> +  int16_t t = uint16_t(buffer[3]) << 8 | uint16_t(buffer[4]);
```suggestion
  int16_t t = encode_uint16(buffer[3], buffer[4]);
```

2022-04-10 22:44 UTC, kbickar commented on esphome/components/mpl3115a2/mpl3115a2.cpp
> +  }
In my experience, it's always ready immediately, so I changed it to just wait 10ms if it's not ready, then give up if it still isn't

2022-04-10 23:01 UTC, jesserockz commented on esphome/components/mpl3115a2/mpl3115a2.cpp
> +  }
Does the if block here mean you can only have altitude **or** pressure?
Currently if you have both configured then the pressure sensor will never get a state?

2022-04-10 23:04 UTC, kbickar commented on esphome/components/mpl3115a2/mpl3115a2.cpp
> +  }
Yes, the result will either be an altitude or pressure depending on the flag set at the beginning of the function

2022-04-11 01:15 UTC, jesserockz commented on esphome/components/mpl3115a2/mpl3115a2.cpp
> +  }
Ah, I was looking for something like that and missed it somehow.
It would be good then to configure a validation to only allow one or the other in python so a user cannot configure both and expect both to update.

2022-04-11 01:16 UTC, jesserockz commented on esphome/components/mpl3115a2/mpl3115a2.cpp
> +  }
There is `cv.Exclusive` for this use case

2022-06-10 21:09 UTC, kbickar commented
@jesserockz is there anything else needed for this?

2022-09-09 04:06 UTC, kbx81 approved these changes

2022-09-09 05:18 UTC, merged