Issue with data-request-handling solved
OttoWinter/esphomeyaml pull request #3388
Opened 2022-04-13 22:12 UTC by matthias882

# What does this implement/fix?

Issue https://github.com/esphome/issues/issues/3086: Not all Data fom BMS could be received:
Problem was stuck in RX because of sending all requests to DalyBMS at one Time.
Solution: Buildet a state-machine in loop to sende one request after the other. First request triggert by update.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-04-13 22:57 UTC, jesserockz requested changes
My review only addresses the formatting issues for now

2022-04-13 22:57 UTC, jesserockz commented on esphome/components/daly_bms/daly_bms.h
> +  uint8_t next_request;
trailing underscore for protected members
```suggestion
  bool trigger_next_;
  uint8_t next_request_;
```

2022-04-13 22:57 UTC, jesserockz commented on esphome/components/daly_bms/daly_bms.cpp
> +            break;
```suggestion
            case 7:
            default:
            break;
```

2022-04-13 22:57 UTC, jesserockz commented on esphome/components/daly_bms/daly_bms.cpp
> +    }
```suggestion
    if ((now - last_transmission_ >= 250) && !trigger_next) {
      //last transmittion loger than 0.25s ago -> trigger next request
      last_transmission_ = now;
      trigger_next = true;
    }
```

2022-04-13 22:57 UTC, jesserockz commented on esphome/components/daly_bms/daly_bms.cpp
> +    }
```suggestion
    while (available()) {
      uint8_t c;
      read_byte(&c);
      if (!receiving_) {
        if (c != 0xa5)
          continue;
        receiving_ = true;
      }
      data_.push_back(c);
      if (data_.size() == 4)
          data_count_ = c;
      if ((data_.size() > 4) and (data_.size() == data_count_ + 5)) {
        this->decode_data_(data_);
        data_.clear();
        receiving_ = false;
      }
    }
```

2022-04-14 05:42 UTC, matthias882 commented
The formatting should be pretty now...

2022-06-15 21:19 UTC, h3po commented
The code works on my esp32 as well. But with or without the patch, I'm getting this warning message:
```
[21:19:16][V][component:199]: Component daly_bms took a long time for an operation (0.11 s).
[21:19:16][V][component:200]: Components should block for at most 20-30ms.
```

2022-07-19 10:06 UTC, frenck commented
@matthias882 There is still an CI error happening. Could you take a look?

2022-10-18 21:08 UTC, h3po commented
> @matthias882 There is still an CI error happening. Could you take a look?
I don't see a ci error, it's just @jesserockz is marked as reviewer for the formatting changes

2023-01-18 00:57 UTC, jesserockz requested changes

2023-01-18 00:57 UTC, jesserockz commented on esphome/components/daly_bms/daly_bms.cpp
> +      }
```suggestion
      } else {
        ESP_LOGW(TAG,"Checksum-Error on Packet %x", it[4]);
      }
```

2023-01-18 00:57 UTC, jesserockz commented on esphome/components/daly_bms/daly_bms.cpp
> +  last_transmission_ = now;
```suggestion
    last_transmission_ = now;
```

2023-04-27 04:35 UTC, matthias882 commented
Thanks for nothing

2023-08-08 02:28 UTC, jesserockz commented
Hi @matthias882 Apologies for the very long delay on this PR. 

I have pushed some extra changes into the branch that should not change the functionality, but adjusts the code style slightly.

2023-08-08 11:46 UTC, matthias882 commented
Hi @jesserockz 
I tried to put the new code to my daly-bms-controller to test it, but the compilation stopped with several errors...
`INFO Reading configuration /opt/iobroker/iobroker-data/esphome.0/daly-smartbms-1.yaml...
INFO Updating https://github.com/matthias882/esphome.git@patch-4
INFO Generating C++ source...
INFO Compiling app...
Processing daly-smartbms-1 (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/daly-smartbms-1/src/esphome/components/daly_bms/daly_bms.cpp.o
Compiling .pioenvs/daly-smartbms-1/src/main.cpp.o
In file included from src/esphome/components/daly_bms/daly_bms.cpp:1:
src/esphome/components/daly_bms/daly_bms.h:26:14: error: 'voltage' has not been declared
   26 |   SUB_SENSOR(voltage);
      |              ^~~~~~~
src/esphome/components/daly_bms/daly_bms.h:26:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   26 |   SUB_SENSOR(voltage);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:27:14: error: 'current' has not been declared
   27 |   SUB_SENSOR(current);
      |              ^~~~~~~
src/esphome/components/daly_bms/daly_bms.h:27:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   27 |   SUB_SENSOR(current);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:27:3: error: 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)' cannot be overloaded with 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
src/esphome/components/daly_bms/daly_bms.h:26:3: note: previous declaration 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
   26 |   SUB_SENSOR(voltage);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:28:14: error: 'battery_level' has not been declared
   28 |   SUB_SENSOR(battery_level);
      |              ^~~~~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:28:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   28 |   SUB_SENSOR(battery_level);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:28:3: error: 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)' cannot be overloaded with 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
src/esphome/components/daly_bms/daly_bms.h:26:3: note: previous declaration 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
   26 |   SUB_SENSOR(voltage);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:29:14: error: 'max_cell_voltage' has not been declared
   29 |   SUB_SENSOR(max_cell_voltage);
      |              ^~~~~~~~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:29:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   29 |   SUB_SENSOR(max_cell_voltage);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:29:3: error: 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)' cannot be overloaded with 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
src/esphome/components/daly_bms/daly_bms.h:26:3: note: previous declaration 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
   26 |   SUB_SENSOR(voltage);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:30:14: error: 'max_cell_voltage_number' has not been declared
   30 |   SUB_SENSOR(max_cell_voltage_number);
      |              ^~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:30:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   30 |   SUB_SENSOR(max_cell_voltage_number);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:30:3: error: 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)' cannot be overloaded with 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
src/esphome/components/daly_bms/daly_bms.h:26:3: note: previous declaration 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
   26 |   SUB_SENSOR(voltage);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:31:14: error: 'min_cell_voltage' has not been declared
   31 |   SUB_SENSOR(min_cell_voltage);
      |              ^~~~~~~~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:31:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   31 |   SUB_SENSOR(min_cell_voltage);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:31:3: error: 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)' cannot be overloaded with 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
src/esphome/components/daly_bms/daly_bms.h:26:3: note: previous declaration 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
   26 |   SUB_SENSOR(voltage);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:32:14: error: 'min_cell_voltage_number' has not been declared
   32 |   SUB_SENSOR(min_cell_voltage_number);
      |              ^~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:32:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   32 |   SUB_SENSOR(min_cell_voltage_number);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:32:3: error: 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)' cannot be overloaded with 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
src/esphome/components/daly_bms/daly_bms.h:26:3: note: previous declaration 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
   26 |   SUB_SENSOR(voltage);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:33:14: error: 'max_temperature' has not been declared
   33 |   SUB_SENSOR(max_temperature);
      |              ^~~~~~~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:33:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   33 |   SUB_SENSOR(max_temperature);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:33:3: error: 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)' cannot be overloaded with 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
src/esphome/components/daly_bms/daly_bms.h:26:3: note: previous declaration 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
   26 |   SUB_SENSOR(voltage);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:34:14: error: 'max_temperature_probe_number' has not been declared
   34 |   SUB_SENSOR(max_temperature_probe_number);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:34:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   34 |   SUB_SENSOR(max_temperature_probe_number);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:34:3: error: 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)' cannot be overloaded with 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
src/esphome/components/daly_bms/daly_bms.h:26:3: note: previous declaration 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
   26 |   SUB_SENSOR(voltage);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:35:14: error: 'min_temperature' has not been declared
   35 |   SUB_SENSOR(min_temperature);
      |              ^~~~~~~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:35:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   35 |   SUB_SENSOR(min_temperature);
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:35:3: error: 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)' cannot be overloaded with [...]

2023-08-08 19:48 UTC, jesserockz commented
Oops, fixed by removing the semi colons that were auto added =)

2023-08-08 21:10 UTC, jesserockz approved these changes

2023-08-08 21:28 UTC, matthias882 commented
Oh no, bad news. The semi colon was not the problem. The errors are the same not, but in addition that a semi colon would be expected where you removed it ;)

```
Compiling .pioenvs/daly-smartbms-1/src/esphome/components/daly_bms/daly_bms.cpp.o
Compiling .pioenvs/daly-smartbms-1/src/main.cpp.o
In file included from src/esphome/components/daly_bms/daly_bms.cpp:1:
src/esphome/components/daly_bms/daly_bms.h:26:14: error: 'voltage' has not been declared
   26 |   SUB_SENSOR(voltage)
      |              ^~~~~~~
src/esphome/components/daly_bms/daly_bms.h:26:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   26 |   SUB_SENSOR(voltage)
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:26:21: error: expected ';' at end of member declaration
   26 |   SUB_SENSOR(voltage)
      |                     ^
      |                      ;
src/esphome/components/daly_bms/daly_bms.h:27:14: error: 'current' has not been declared
   27 |   SUB_SENSOR(current)
      |              ^~~~~~~
src/esphome/components/daly_bms/daly_bms.h:27:3: error: ISO C++ forbids declaration of 'SUB_SENSOR' with no type [-fpermissive]
   27 |   SUB_SENSOR(current)
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:27:21: error: expected ';' at end of member declaration
   27 |   SUB_SENSOR(current)
      |                     ^
      |                      ;
src/esphome/components/daly_bms/daly_bms.h:27:3: error: 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)' cannot be overloaded with 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
   27 |   SUB_SENSOR(current)
      |   ^~~~~~~~~~
src/esphome/components/daly_bms/daly_bms.h:26:3: note: previous declaration 'int esphome::daly_bms::DalyBmsComponent::SUB_SENSOR(int)'
   26 |   SUB_SENSOR(voltage)
      |   ^~~~~~~~~~```

2023-08-08 21:55 UTC, matthias882 commented
The Problem should be on my side. I think the "SUB_SENSOR()" macro in the sensor.h is perhaps to new and not in my (beta state) ESPHOME-Integration in iobroker. I try to update this and then we will see.
PS: great idea with this marco, it saves much lines and much copy/paste on creating new sensor-values!

2023-08-09 19:35 UTC, jesserockz commented
`SUB_SENSOR` was added many months ago now and released in 2023.2.0.

2023-08-09 21:44 UTC, matthias882 commented
Yes, that's the problem. My esphome is currently on v2022.10.0😅 I currently try to update and then let's see...

2023-08-10 05:05 UTC, merged