Add support for Infinion XENSIV PAS CO2 sensor
OttoWinter/esphomeyaml pull request #3412
Opened 2022-04-21 16:32 UTC by martgras

# What does this implement/fix?

Add support for Infinion XENSIV PAS CO2 sensor

https://www.infineon.com/cms/en/product/sensor/co2-sensors/pasco2v01/

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
  - platform: pas_co2
    co2:
      name: "CO2"
      id: co2
    ambient_pressure_compensation: 1031
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-05-10 08:31 UTC, jesserockz requested changes

2022-05-10 08:31 UTC, jesserockz commented on esphome/components/pas_co2/pas_co2.cpp
> +void PasCo2Component::start_foced_calibration() {
typo?
```suggestion
void PasCo2Component::start_forced_calibration() {
```

2022-05-10 08:31 UTC, jesserockz commented on esphome/components/pas_co2/pas_co2.h
> +  void start_foced_calibration();
```suggestion
  void start_forced_calibration();
```

2022-05-10 08:31 UTC, jesserockz commented on esphome/components/pas_co2/pas_co2.h
> +  void play(Ts... x) override { this->pas_co2_->start_foced_calibration(); }
```suggestion
  void play(Ts... x) override { this->pas_co2_->start_forced_calibration(); }
```

2022-05-10 08:31 UTC, jesserockz commented on esphome/components/pas_co2/sensor.py
> +PasCo2BackgroundCalibrationAction = pas_co2_ns.class_(
```suggestion
PerformForcedCalibrationAction = pas_co2_ns.class_(
```

2022-05-10 08:31 UTC, jesserockz commented on esphome/components/pas_co2/sensor.py
> +    PasCo2BackgroundCalibrationAction,
```suggestion
    PerformForcedCalibrationAction,
```

2022-05-17 09:13 UTC, martgras commented
My test sensor is not responding anymore. I'll have to check if it's code or hw related

2022-08-24 00:46 UTC, closed without merging