Corrected nvs key calculation by eliminating current_offset from ESP32Preferences.make_preference()
OttoWinter/esphomeyaml pull request #3416
Opened 2022-04-24 11:40 UTC by cinadr

# What does this implement/fix?

Corrected nvs key calulation which was based on current_offset increasing with each preference data length. Due to ESP32 nvs management is key based there is no need for tracking any offset in nvs. Generating key based on this offset makes key string somehow random as the order of writes influences the key itself.
For single read/writes this issue remains hidden as the first write is always gets offset as 0. Multiple writes messes up key generation.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

See this issue [here](https://github.com/esphome/issues/issues/3006)

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

# Example config.yaml
```yaml
switch:
  - platform: template
    name: ${device_name} Sw 1
    optimistic: true
    id: sw_1
    restore_state: true
  - platform: template
    name: ${device_name} SW 2
    id: sw_2
    optimistic: true
    restore_state: true
  - platform: template
    name: ${device_name} SW 3
    id: sw_3
    optimistic: true
    restore_state: true
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-05-17 08:28 UTC, martgras requested changes
While the proposed changes look correct it's a breaking change because a new key is generated

2022-05-17 08:28 UTC, martgras commented on esphome/components/esp32/preferences.cpp
> +  // uint32_t current_offset = 0;   // not needed
please remove instead of commenting out.

2022-05-17 08:28 UTC, martgras commented on esphome/components/esp32/preferences.cpp
> +    uint32_t keyval = type;  // removed current_offset from calculation
same here - the comment isn't useful anymore once the code is committed.
Applies to the all other change related comments as well. 
```suggestion
    uint32_t keyval = type;
```

2022-05-17 08:28 UTC, martgras commented on esphome/components/esp32/preferences.cpp
> +    pref->key = keybuf;                              // copied to std::string
Nothing wrong with your code.
shorter variant: 
```suggestion
pref->key = str_sprintf("%u", keyval);
```

2022-05-19 19:00 UTC, cinadr commented on esphome/components/esp32/preferences.cpp
> +  // uint32_t current_offset = 0;   // not needed
Done

2022-05-20 11:26 UTC, jesserockz commented on esphome/components/esp32/preferences.cpp
> +  // uint32_t current_offset = 0;   // not needed
You still have not removed the line...

2022-05-20 13:19 UTC, cinadr commented on esphome/components/esp32/preferences.cpp
> +  // uint32_t current_offset = 0;   // not needed
Sorry. I missed that. Now done.

2022-05-23 14:32 UTC, cinadr commented
Please help!
I cannot remove "integration: tuya" from my PR. Do I need to bother with that?

2022-05-23 15:00 UTC, martgras approved these changes

2022-05-23 15:19 UTC, cinadr commented
There are two files in this PR tuya.cpp and tuya.h also which are not touched by me just appended by github on rebase. Is this ok?

2022-05-24 00:56 UTC, jesserockz commented
@cinadr you need to rebase locally and drop be2b48f857a023416e559e09cd81a5bb1fd770e9

2022-05-24 14:28 UTC, cinadr commented
> @cinadr you need to rebase locally and drop [be2b48f](https://github.com/esphome/esphome/commit/be2b48f857a023416e559e09cd81a5bb1fd770e9)

I think it's done.

2022-05-24 21:47 UTC, martgras commented on esphome/components/esp32/preferences.cpp
> +    pref->key = str_sprintf("%u", keyval);
```suggestion
    pref->key = str_sprintf("%d", keyval);
```
Wouldn't this limit the impact. Everything at offset 0 should still get the same key at offset 0?
The fact that the key can be negative is a 'cosmetic' point for me and actually doesn't make a difference

2022-05-25 07:17 UTC, cinadr commented on esphome/components/esp32/preferences.cpp
> +    pref->key = str_sprintf("%u", keyval);
Sure. The other way around: would that remove the braking-change flag? If more than one value stored in flash the user won't be able to retrieve it anyway. So if the braking-change stays I think this cosmetic change would worth it to not get negative keys. But if you insist I can revert it.

2022-05-25 07:28 UTC, martgras commented on esphome/components/esp32/preferences.cpp
> +    pref->key = str_sprintf("%u", keyval);
@jesserockz your call

2022-06-03 04:20 UTC, jesserockz commented on esphome/components/esp32/preferences.cpp
> +    pref->key = str_sprintf("%u", keyval);
The breaking change will stay regardless because as long as there are multiple components saving, any after the first wont be restored after upgrading to the version with this code.

2022-06-04 16:21 UTC, cinadr commented on esphome/components/esp32/preferences.cpp
> +    pref->key = str_sprintf("%u", keyval);
Is there anything more to be done? OttoWinter was marked accidentally for review by changing branch to beta (I was trying to remove tuya flag) and back. So I think we should not wait to him.

2022-06-06 23:00 UTC, jesserockz commented
I was just looking through the codebase and found at least 1 place this will completely break. 
The `ValueRangeTrigger` for `number` components uses the parent hash as the type. Currently this then gets "moved" by the offset, but after this change it will conflict with the restoring value of the number itself.

https://github.com/esphome/esphome/blob/ac0d921413c3884752193fe568fa82853f0f99e9/esphome/components/number/automation.cpp#L9-L17

2022-06-07 06:15 UTC, cinadr commented
> I was just looking through the codebase and found at least 1 place this will completely break. The `ValueRangeTrigger` for `number` components uses the parent hash as the type. Currently this then gets "moved" by the offset, but after this change it will conflict with the restoring value of the number itself.
> 
> https://github.com/esphome/esphome/blob/ac0d921413c3884752193fe568fa82853f0f99e9/esphome/components/number/automation.cpp#L9-L17

I've found 20 files with global_preference->make_preference calls. Some of these has calls from some descendant of EntityBase with get_object_id_hash(). Others not descending from EntityBase  creates some unique id/hash on its own. OTAComponent uses a constant which is not a problem as it is only instantiated once (I think). Many of them creates hash with `uint32_t hash = fnv1_hash(App.get_compilation_time());` which is correct if it is not instantiated more than once. Another solution was `this->rtc_ = global_preferences->make_preference<float>(global_servo_id);` which is incremented with each call to make_preference. The only one problem was within `ValueRangeTrigger::setup()` indeed. XOR-ing it's parent hash with a constant would create it's own unique hash that can be retrieved successfully.

2022-06-07 18:03 UTC, cinadr commented
I've tested this with the following yaml locally with an esp32-s, esp32-wroom-32 and esp-12e (8266). All worked well restored the state of ValueRangeTrigger boolean from flash succesfully.
```
switch:
  - platform: template
    name: ${device_name} Sw 1
    optimistic: true
    id: sw_1
    restore_state: true
  - platform: template
    name: ${device_name} SW 2
    id: sw_2
    optimistic: true
    restore_state: true
  - platform: template
    name: ${device_name} SW 3
    id: sw_3
    optimistic: true
    restore_state: true

logger:
  level: DEBUG

number:
  - platform: template
    id: test_number
    name: Test Number
    min_value: 1
    max_value: 30
    step: 1
    restore_value: true
    initial_value: 3
    optimistic: true
    on_value_range:
      above: 10
      below: 20
      then:
        logger.log: 
          format: "Value in range"
          level: DEBUG

interval:
  - interval: 2s
    then:
      number.increment:
        id: test_number
        cycle: true
```

2022-06-07 18:52 UTC, cinadr commented
I've tested this with the following yaml locally with an esp32-s, esp32-wroom-32 and esp-12e (8266). All worked well restored the state of ValueRangeTrigger boolean from flash succesfully.
```
switch:
  - platform: template
    name: ${device_name} Sw 1
    optimistic: true
    id: sw_1
    restore_state: true
  - platform: template
    name: ${device_name} SW 2
    id: sw_2
    optimistic: true
    restore_state: true
  - platform: template
    name: ${device_name} SW 3
    id: sw_3
    optimistic: true
    restore_state: true

logger:
  level: DEBUG

number:
  - platform: template
    id: test_number
    name: Test Number
    min_value: 1
    max_value: 30
    step: 1
    restore_value: true
    initial_value: 3
    optimistic: true
    on_value_range:
      above: 10
      below: 20
      then:
        logger.log: 
          format: "Value in range"
          level: DEBUG

interval:
  - interval: 2s
    then:
      number.increment:
        id: test_number
        cycle: true
```

N.B: I don't think the needs-docs label is relevant as number in the user perspective is not changed.

2022-06-13 13:20 UTC, OttoWinter commented on esphome/components/esp32/preferences.cpp
> +    ESP_LOGV(TAG, "s_pending_save: key: %s, len: %d", key.c_str(), len);
```suggestion
    ESP_LOGVV(TAG, "s_pending_save: key: %s, len: %d", key.c_str(), len);
```
Can we move these to very verbose setting? This would appear to spam the logs somewhat and most developers will have verbose level turned on.

2022-06-13 13:21 UTC, OttoWinter commented on esphome/components/esp32/preferences.cpp
> +      ESP_LOGV(TAG, "nvs_get_blob: key: %s, len: %d", key.c_str(), len);
```suggestion
      ESP_LOGVV(TAG, "nvs_get_blob: key: %s, len: %d", key.c_str(), len);
```
Same here (for the failure above verbose is better IMO because then you know no data was read as a developer when developing a component)

2022-06-13 13:23 UTC, OttoWinter commented on esphome/components/esp32/preferences.cpp
> +    pref->key = str_sprintf("%u", keyval);
I'm confused, why is this a breaking change? Yeah the key function is changed, but before any tiny change to the YAML config (and new components being added to ESPHome codebase, an unrelated component's data size changing etc) would also have changed the key. So the key _changing_ per release is the default, no?

2022-06-13 13:28 UTC, OttoWinter reviewed
> The key calculation is dependent on the size of the previously saved data making this key calculation random and not reversible.

Indeed, I can tell you the reason it's like this at the moment: So that the behavior is the same between ESP8266 and ESP32. For ESP8266 we don't have such a nice nvs framework, and there the data storage is still based on an offset. But that's not really a good reason to keep it this way, so I'm happy with the change.

And to clarify, by random you mean random across firmware flashes, right? Because as long as the same firmware is on the device, the key offset should be stable as the component setup order is stable. If not, that would point to an issue elsewhere that we need to fix.

2022-06-14 20:09 UTC, cinadr commented
> And to clarify, by random you mean random across firmware flashes, right? Because as long as the same firmware is on the device, the key offset should be stable as the component setup order is stable. If not, that would point to an issue elsewhere that we need to fix.

Random also if make_preferences is called in different order on load then save. In this case the offset would be different. I'm planning a scheduler component that saves/loads schedules if changed via mqtt and make_preferences is called by request. In general make_preference is usually called when components are created and the order is specified during compile time so in that case you are right.

2022-06-14 21:41 UTC, jesserockz commented on esphome/components/esp32/preferences.cpp
> +    pref->key = str_sprintf("%u", keyval);
Not for all components. Some like `total_daily_energy` and `climate` use the `object_id_hash` as the key so it can survive firmware updates.

2022-06-15 15:28 UTC, cinadr commented on esphome/components/esp32/preferences.cpp
> +    pref->key = str_sprintf("%u", keyval);
Idea: We could test in make_preference with nvs_get_blob if a value exists with and old key calculation algorithm. If so we will rekey it and save it with the new one. This shouldn't wear the flash as it will be done only once. Reading flash doesn't wear it. It definitely slows down make_preference but might save some headaches. 
After a few releases we can drop the checking part of the algorithm and give some update path to users to avoid flash data loss.
This needs some coding and testing though, making my day. Does this worth it?

2022-06-15 16:34 UTC, OttoWinter commented on esphome/components/esp32/preferences.cpp
> +    pref->key = str_sprintf("%u", keyval);
> Not for all components. Some like `total_daily_energy` and `climate` use the `object_id_hash` as the key so it can survive firmware updates.

Unless I'm mistaken, they use the `object_id_hash` as the *type*. But the NVS key is/was still generated from the offset variable.

So before, the entry was still invalidated by these two cases:
1. A new esphome version adds a new internal NVS setting somewhere (and thus shifts around all entries that are generated afterwards)
2. The user adds a new sensor before this ilone in their YAML (again, the keys afterwards are sgifted back and get new nvs keys)

Thus the NVS key was not _quite_ stable before either. I guess though in effect 1 doesn't happen often enough that a user expects the NVS settings to get lost.

2022-06-21 05:15 UTC, jesserockz commented on esphome/components/esp32/preferences.cpp
> +    pref->key = str_sprintf("%u", keyval);
Ah yes, did not think about those cases.

2022-06-21 05:17 UTC, jesserockz approved these changes

2022-06-21 05:17 UTC, merged