Add display_type property to DisplayBuffer
OttoWinter/esphomeyaml pull request #3430
Opened 2022-05-02 13:20 UTC by guillempages

Add the possibility for DisplayBuffer clients to know which kind of
images (monochrome/grayscale/color) the Display is capable of displaying.

# What does this implement/fix?

I some cases (e.g. PR #3255) it would be good if code using a DisplayBuffer object would be able to check which kind of images the displaybuffer is capable of displaying. Added an abstract method to get that information in the base DisplayBuffer class, and implemented it on all display components I could find in the code.

This might break compilation of custom_component displays that are built out of tree. The fix is easy (implement the one-liner method), but would need to be done on each custom display.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** needed by #3255 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-05-14 12:38 UTC, guillempages commented on esphome/components/display/display_buffer.h
> +  virtual DisplayType get_display_type() = 0;
@any senior developer/reviewer:
Would it be better to add an "UNKNOWN" type, and implement the "get_display_type" method in the base class, printing an Error log when not overridden in the implementing display classes?
This would make the change "not breaking", but any code depending on this method would then not work (or not work properly) if the sub-classes do not override the method right (which would probably be the case for all custom displays already existing in the wild).

2022-05-14 19:12 UTC, geiseri commented on esphome/components/display/display_buffer.h
> +  virtual DisplayType get_display_type() = 0;
@guillempages as someone that could really use this feature I think it would be best to have it  "fail fast" so that display drivers outside of the core repo will fail to compile and those devs can see the solution quickly from the release notes.   With something that is pretty fundamental to the display buffer memory layout it should be an all or nothing support.  

That being said I am wondering if it would be better to return the  `ImageType` instead of making a new enum.  There is already special drawing of `display::Image` present that takes care of the various formats.  One interesting side-effect of forcing display implementations to expose their internal format would be so that the `display::DisplayBuffer::image` method can skip any conversions from the internal `display::Image` format to the native framebuffer format.  Since right now if you have a 565 image and a display that supports 565 the code will convert the 565 into rgb24 and then back into 565 again.  If display implementers had to expose their internal buffer it would speed things up extensively.   Quite a few of the nicer display use 565 internally, so just keeping everything that way would help with the framerate.

2022-05-15 13:48 UTC, guillempages commented on esphome/components/display/display_buffer.h
> +  virtual DisplayType get_display_type() = 0;
Reusing ``ImageType`` was the first thing I thought about (I also prefer re-use, instead of new types for the same thing), but the ``IMAGE_TYPE_TRANSPARENT_BINARY`` does not make any sense at all for a display type (it is really image specific), and some other possible future display types (e.g. 3 color display for some e-ink displays) would make no sense/wouldn't help for images.
So I think keeping the types separate is a good thing to have.

W.r.t. the native framebuffer format (e.g. rgb24 or RGB565), I agree it would be a nice thing to have. But since my knowledge of display technology is very limited, I'd prefer to keep it as it is for now, and let some display gurus extend/rework the enum with the additional needed types, and implement it "right" in the corresponding display components.

2022-05-16 23:04 UTC, jesserockz commented
This is only a review of the terms used, not the functionality yet.

`MONOCHROME` and `GREYSCALE` basically mean the same thing...
`BINARY` would be a better option.

2022-05-17 09:35 UTC, guillempages commented
> This is only a review of the terms used, not the functionality yet.
> 
> `MONOCHROME` and `GREYSCALE` basically mean the same thing... `BINARY` would be a better option.

I originally had "BINARY" (like in the IMAGE_TYPE), but changed it to "MONOCHROME", because I thought it fits better on a display. Googling for "monochrome display" gives me back over 600.000 results, whereas "binary display" only gives 45.900. 
IMHO "MONOCHROME" means "Single color", whereas grayscale has different shades of gray. OTOH, monochrome is just a 1-bit grayscale :-D

That said, I don't have a very strong opinion here; if the project responsibles (of which you are one AFAIK) think "BINARY" is a better fit, I can change that.

2022-05-18 04:50 UTC, jesserockz commented
MONOCHROME means single colour, yes. But it can be different shades of that colour. I would prefer BINARY to be used in these cases.

We have `monochromatic` (brightness controllable) and `binary` (on/off) lights in ESPHome, so would be nice to match that even.

2022-05-29 13:40 UTC, guillempages commented
@jesserockz Ok, I've changed ``MONOCHROME`` to ``BINARY``. I'm not sure if I interpreted your last comment right; I kept "GRAYSCALE" for gray-scale devices; should I change this to "monochromatic" or leave it as it is? (IMHO, GRAYSCALE is easier to understand, but again, I defer to your judgment).

Is there anything else I should do, to get this merged?

2022-05-29 13:45 UTC, guillempages commented on esphome/components/display/display_buffer.h
> +  DISPLAY_TYPE_BINARY = 1,
Starting the enum with "1" instead of "0" to leave the possibility open to add an "UNKNOWN" in the future. If this is against project rules/recommendations, I can change it back to 0.

2022-05-31 04:59 UTC, jesserockz commented on esphome/components/display/display_buffer.h
> +  DISPLAY_TYPE_BINARY = 1,
It would not matter as the values of the enums should never be used directly.

2022-05-31 05:05 UTC, jesserockz requested changes

2022-05-31 05:05 UTC, jesserockz commented on esphome/components/st7789v/st7789v.h
> +  display::DisplayType get_display_type() override { return display::DisplayType::DISPLAY_TYPE_BINARY; }
This is a coloured display...
```suggestion
  display::DisplayType get_display_type() override { return display::DisplayType::DISPLAY_TYPE_COLOR; }
```

2022-05-31 07:28 UTC, guillempages commented on esphome/components/display/display_buffer.h
> +  DISPLAY_TYPE_BINARY = 1,
OK, then I'll leave it as it is now.

2022-05-31 07:28 UTC, guillempages commented on esphome/components/st7789v/st7789v.h
> +  display::DisplayType get_display_type() override { return display::DisplayType::DISPLAY_TYPE_BINARY; }
Oops. I thought I looked every display up to get the properties, but I messed this one up :-(

2022-06-03 03:38 UTC, jesserockz approved these changes

2022-06-03 03:39 UTC, merged