DAC7678 support
OttoWinter/esphomeyaml pull request #3441
Opened 2022-05-05 20:41 UTC by NickB1

# What does this implement/fix?

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:
```yaml
# Example configuration entry
dac7678:
  address: 0x4A
  id: dac7678_hub1
  internal_reference: true

# Individual outputs
output:
- platform: dac7678
  dac7678_id: 'dac7678_hub1'
  channel: 0
  id: 'dac7678_1_ch0'
- platform: dac7678
  dac7678_id: 'dac7678_hub1'
  channel: 1
  id: 'dac7678_1_ch1'
- platform: dac7678
  dac7678_id: 'dac7678_hub1'
  channel: 2
  id: 'dac7678_1_ch2'
- platform: dac7678
  dac7678_id: 'dac7678_hub1'
  channel: 3
  id: 'dac7678_1_ch3'
- platform: dac7678
  dac7678_id: 'dac7678_hub1'
  channel: 4
  id: 'dac7678_1_ch4'
- platform: dac7678
  dac7678_id: 'dac7678_hub1'
  channel: 5
  id: 'dac7678_1_ch5'
- platform: dac7678
  dac7678_id: 'dac7678_hub1'
  channel: 6
  id: 'dac7678_1_ch6'
- platform: dac7678
  dac7678_id: 'dac7678_hub1'
  channel: 7
  id: 'dac7678_1_ch7'
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-05-09 05:09 UTC, jesserockz commented on tests/dac7678.yaml
> +esphome:
Please add the yaml config to an existing `testX.yaml` file

2022-05-09 06:38 UTC, NickB1 commented on tests/dac7678.yaml
> +esphome:
Ok will do.

2022-05-31 04:04 UTC, jesserockz requested changes

2022-05-31 04:04 UTC, jesserockz commented on esphome/components/dac7678/dac7678_output.cpp
> +const uint8_t DAC7678_REG_INTERNAL_REF_1 = 0x90;
```suggestion
static const uint8_t DAC7678_REG_INPUT_N = 0x00;
static const uint8_t DAC7678_REG_SELECT_UPDATE_N = 0x10;
static const uint8_t DAC7678_REG_WRITE_N_UPDATE_ALL = 0x20;
static const uint8_t DAC7678_REG_WRITE_N_UPDATE_N = 0x30;
static const uint8_t DAC7678_REG_POWER = 0x40;
static const uint8_t DAC7678_REG_CLEAR_CODE = 0x50;
static const uint8_t DAC7678_REG_LDAC = 0x60;
static const uint8_t DAC7678_REG_SOFTWARE_RESET = 0x70;
static const uint8_t DAC7678_REG_INTERNAL_REF_0 = 0x80;
static const uint8_t DAC7678_REG_INTERNAL_REF_1 = 0x90;
```

2022-05-31 04:04 UTC, jesserockz commented on .gitignore
> +tests/dac7678_test.yaml
Please dont add your own files to the gitignore
```suggestion
```

2022-05-31 04:04 UTC, jesserockz commented on esphome/components/dac7678/dac7678_output.cpp
> +  }
This means that changing one channel requires all channels to be updated...
Why not just instantly write each channel as it is actually updated below in `set_channel_value`?

2022-06-07 09:48 UTC, NickB1 commented on esphome/components/dac7678/dac7678_output.cpp
> +  }
I got this from another similar component, I thought maybe all i2c transaction need to be done in the loop function of every component to avoid any sequencing issues.
But you can use it in any function?

2022-06-07 09:57 UTC, jesserockz commented on esphome/components/dac7678/dac7678_output.cpp
> +  }
It should be fine to write it in the `set_channel_value`, which is still called from the loop of whatever is writing that output anyway. I dont forsee any issues, and it will cut down on unnecessary comms when a single one has changed.

2022-06-08 20:22 UTC, NickB1 reviewed
Moved i2c write to set_channel_value_ member

2022-06-09 03:34 UTC, jesserockz commented on esphome/components/dac7678/dac7678_output.cpp
> +}
```suggestion
  }
}
```

2022-06-09 03:37 UTC, jesserockz commented on esphome/components/dac7678/__init__.py
> +CODEOWNERS = ["@NickB1"]
This will fix compile issues if someone adds the main hub, but no actual outputs
```suggestion
AUTO_LOAD = ["output"]
CODEOWNERS = ["@NickB1"]
```

2022-06-09 03:38 UTC, jesserockz approved these changes

2022-06-21 05:12 UTC, merged