Add Insignia Portable AC Component
OttoWinter/esphomeyaml pull request #3456
Opened 2022-05-10 19:20 UTC by andrewmv

# What does this implement/fix?

A subcomponent for the Climate IR component to support the Insignia NS-AC08PWH1 portal air conditioner.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2063

## Test Environment

- [ X ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
climate:
  - platform: insignia
    name: Insignia AC
    update_interval: 60s
    sensor: temperature_sensor
    follow_me_switch: insignia_follow_me_switch
    led_switch: insignia_led_switch
    supports_heat: false

remote_transmitter:
  pin: 
    number: GPIO23
    inverted: false
  carrier_duty_percent: 50%

sensor:
  platform: dht 
  model: DHT22
  pin: GPIO22
  temperature:
    name: Temperature Sensor
    id: temperature_sensor
  humidity:
    name: Humidity Sensor
    id: humidity_sensor

switch:
  - platform: template
    name: Follow Me Switch
    id: insignia_follow_me_switch
    optimistic: true
  - platform: template
    name: Insignia LED Switch
    id: insignia_led_switch
    optimistic: true
    assumed_state: true

```

## Checklist:
  - [ X ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ X ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-05-10 23:31 UTC, jesserockz requested changes

2022-05-10 23:31 UTC, jesserockz commented on esphome/components/climate_ir/climate_ir.h
> +class ClimateIR : public climate::Climate, public PollingComponent, public remote_base::RemoteReceiverListener {
This does not need to be added for every climate_ir component. You can just add it to `InsigniaClimate` directly

2022-05-11 00:06 UTC, andrewmv commented on esphome/components/climate_ir/climate_ir.h
> +class ClimateIR : public climate::Climate, public PollingComponent, public remote_base::RemoteReceiverListener {
I tried very hard to get around having to change your codebase, but was unable to find a graceful way to do so.

PollingComponent and Component are mutually exclusive, so inheriting from the climate_ir component created a method ambiguity that the compiler could not resolve (e.g. a multiple inheritance diamond problem).

I could fork the climate_ir module into something like polling_climate_ir, but that would complicate future updates and development.

Changing climate_ir from a Component to a PollingComponent, and then giving it an overrideable no-op update() method, allowed InsigniaClimate to have an update loop without affecting other submodules.

I tested several of the existing submodules (coolix, climate_ir_lg), to ensure they were unaffected by this change (compiled, ran, and ensure the IR codes emitted had the same content and timing).

2022-05-11 02:48 UTC, glmnet commented on esphome/components/climate_ir/climate_ir.h
> +class ClimateIR : public climate::Climate, public PollingComponent, public remote_base::RemoteReceiverListener {
Did you try with virtual inheritance?

2022-05-11 19:27 UTC, andrewmv commented on esphome/components/climate_ir/climate_ir.h
> +class ClimateIR : public climate::Climate, public PollingComponent, public remote_base::RemoteReceiverListener {
The components that would need to be declared virtual are deep inside the esphome codebase, and would affect many more modules than this change.
If you can suggest a way that InsigniaClimate can inherit both climate_ir and PollingComponent without creating an ambiguity error or rewriting other modules, I'd be happy to test it.

2022-05-21 16:50 UTC, andrewmv commented on esphome/components/climate_ir/climate_ir.h
> +class ClimateIR : public climate::Climate, public PollingComponent, public remote_base::RemoteReceiverListener {
Any updates?

2022-05-23 15:06 UTC, glmnet commented on esphome/components/climate_ir/climate_ir.h
> +class ClimateIR : public climate::Climate, public PollingComponent, public remote_base::RemoteReceiverListener {
You only need to declare virtual the inheritance of Component in [PollingComponent](https://github.com/esphome/esphome/blob/448e1690aac902cca7d614b2902514fa59e8d6ab/esphome/core/component.h#L266)   and the inheritance of Component in [ClimateIR](https://github.com/andrewmv/esphome/blob/383efb9a88314bba2107c0c11c584a69399fe192/esphome/components/climate_ir/climate_ir.h#L21) with these you can inherit insignia from `PollingComponent` and override `update()`

I would strongly recommend this approach as otherwise it marks climate_ir components as polling components which are just not true, in the other hand the virtual keyword should have no side effects in the rest of esphome as complex inheritance like this is not common

2022-05-23 15:47 UTC, glmnet commented
I believe the switch configurations are a bit weird @jesserockz 

This either creates the switch if defined in the climate itself 
```yaml
climate:
  - platform: insignia
    led_switch: 
      name: Insignia led switch
```

or add a switch platform insignia

```yaml
climate:
  - platform: insignia
     .... 
switch:
  - platform: insignia
    led: 
      name: Insignia led switch
```

2022-05-24 23:32 UTC, andrewmv commented on esphome/components/climate_ir/climate_ir.h
> +class ClimateIR : public climate::Climate, public PollingComponent, public remote_base::RemoteReceiverListener {
Thanks for the guidance - doing as you recommended resolved the ambiguity without having to change ClimateIR to a PollingComponent, and I tested that InsigniaClimate and the existing ClimateIR subcompoenents continued to function correctly.

I agree that this is a much better approach, however, it causes [this clang-tidy test](https://clang.llvm.org/extra/clang-tidy/checks/fuchsia-virtual-inheritance.html) for the esp32-arduino-tiny environment to fail.

2022-05-25 00:03 UTC, andrewmv commented
> I believe the switch configurations are a bit weird @jesserockz
> 
> This either creates the switch if defined in the climate itself
> 
> ```yaml
> climate:
>   - platform: insignia
>     led_switch: 
>       name: Insignia led switch
> ```
> 
> or add a switch platform insignia
> 
> ```yaml
> climate:
>   - platform: insignia
>      .... 
> switch:
>   - platform: insignia
>     led: 
>       name: Insignia led switch
> ```

Using optimistic template switch entities to control these extra functions is an admittedly messy workaround, and I welcome advice on a better way to do this.

The first proposed solution seems more ideal, and what I was originally hoping to achieve, but I wasn't able to find a good example of how to implement it, or whether its even possible to have a platform create entities belonging to a different core platform like that.

The second proposed solution seems functionally equivalent to the existing workaround, but with added complexity. My biggest concern with this is actually that it would clutter up the Switch documentation with a subcomponent that, realistically, very few users would need.

2022-08-23 12:43 UTC, glmnet commented
> The second proposed solution seems functionally equivalent to the existing workaround, but with added complexity. My biggest concern with this is actually that it would clutter up the Switch documentation with a subcomponent that, realistically, very few users would need.

I guess there is a wave where this is actually the expected implementation method, the advantage here is that the switch platform is not loaded unless necessary, although I really like the first approach as it is more cohesive in terms of grouping information in the configuration file.
Anyway, docs related you can document the switch in the climate component help page itself, many components do this, see e.g. `sim800l`

2022-11-23 00:58 UTC, ssieb commented
> The second proposed solution seems functionally equivalent to the existing workaround, but with added complexity. My biggest concern with this is actually that it would clutter up the Switch documentation with a subcomponent that, realistically, very few users would need.

You don't need to document it in the switch section.  Just document it along with this component.

2023-03-03 02:05 UTC, closed without merging