web server esp idf suppport
OttoWinter/esphomeyaml pull request #3500
Opened 2022-05-24 10:51 UTC by dentra

# What does this implement/fix?

Adds support of web server for ESP-IDF. 

Known limitation:
 - No OTA update support (should be solved by separate task).
 - Authorization is working only with very short login/password due to limitation of internal ESP-IDF http server implementation PARSER_BLOCK_SIZE (128 bytes). I am looking for a solution, I will be glad if someone helps.

If limitation is okay I will release this PR from draft.

Tested with web_server version 1, 2 + local with demo platform and some of my devices.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-05-25 19:28 UTC, dentra commented
I need help to solve `script/build_codeowners.py --check` which fails on 
```python 
AUTO_LOAD = ["web_server_idf"] if CORE.using_esp_idf else ["async_tcp"]
```

2022-05-26 15:08 UTC, dentra commented
> I need help to solve `script/build_codeowners.py --check` which fails on
> 
> ```python
> AUTO_LOAD = ["web_server_idf"] if CORE.using_esp_idf else ["async_tcp"]
> ```

all stuff resolved

2022-05-27 17:56 UTC, dentra commented
I also did an ota update, I need some time to check it.

2022-06-08 20:21 UTC, dentra commented
this is big update to support OTA, well tested but still need some time to do additional tests...

2022-06-08 20:33 UTC, dentra commented
Hey @OttoWinter I'am on the right way or should I split the code of web_server_idf to the separate github repo?

2022-06-09 03:40 UTC, jesserockz commented
@dentra please don't ping maintainers directly. Someone will get to the PR and review it when the time comes.

2022-06-09 03:45 UTC, jesserockz commented on esphome/components/web_server_base/__init__.py
> +AUTO_LOAD = ["web_server_idf"] if CORE.using_esp_idf else ["async_tcp"]
This is not guaranteed to work and really should not be written like this.

2022-06-09 03:45 UTC, jesserockz commented on esphome/components/web_server_base/__init__.py
>          cg.add_library("WiFi", None)
IDF also does not have the WiFi library available, not sure how this is compiling for you

2022-06-09 14:37 UTC, dentra commented on esphome/components/web_server_base/__init__.py
>          cg.add_library("WiFi", None)
this is untouched from original. it not used as source when compiled. will fix it

2022-06-09 14:41 UTC, dentra commented
> @dentra please don't ping maintainers directly. Someone will get to the PR and review it when the time comes.

Sorry, I won't do it again

2022-06-09 14:44 UTC, dentra commented on esphome/components/web_server_base/__init__.py
> +AUTO_LOAD = ["web_server_idf"] if CORE.using_esp_idf else ["async_tcp"]
it fails on build_codeowners.py but I fix it.  Could you advise me how it can be changed to work properly?

2022-06-09 15:37 UTC, dentra commented on esphome/components/web_server_base/__init__.py
>          cg.add_library("WiFi", None)
fixed in [bf3de65](https://github.com/esphome/esphome/pull/3500/commits/bf3de656cb49d2c73bce571acdd84abceddb0474)

2022-06-22 19:29 UTC, jesserockz commented on esphome/components/web_server_base/__init__.py
> +AUTO_LOAD = ["web_server_idf"] if CORE.using_esp_idf else ["async_tcp"]
Basically I dont think we can do this. This is a constant that is read by ESPHome core code early on to determine the component dependency tree. It would require changes in the core to accommodate this being "dynamic"

2022-08-15 18:18 UTC, misery commented
Would be great to see this in next major upgrade! 🙂

2022-10-17 08:21 UTC, marshn commented
Since it was created six month ago I have been using this PR extensively, without any issues, on several ESP32-IDF devices deployed at remote sites. Without this PR I would not have been able to migrate to IDF. Thank you for all of your work dentra! 

I too am looking forward to it being incorporated into a release.

2022-10-18 10:19 UTC, dentra commented
@marshn thanks for feedback. have you used only the functionality of the web server or also ota?

2022-10-19 08:21 UTC, marshn commented
@dentra, I have your ota component incorporated into my builds, but it is only occasionally used. I have not noticed any issues. 
I am usiing your web server far more extensively than the ota.

2022-11-06 18:01 UTC, Cossid commented
The web server in general seems to be working great, but the web OTA appears to be problematic still.  It appears to be running into memory/buffer issues where it will read a chunk and then stall for 5 seconds, and keep repeating that process for a period of time until either failing mid-way through and rebooting (can't catch the actual error when that happens), or it make it to the end of receiving data, then fails with something like

> [11:56:45][D][web_server_idf:276]: Remaining size: 198
[11:56:45][D][web_server_idf:276]: Remaining size: 70
[11:56:45][D][esp-idf:000]: W (538673) httpd_txrx: httpd_sock_err: error in recv : 104

2022-11-07 18:54 UTC, jonadis commented
Greetings,
I've found this to work well for the captive_portal and web_server when having to use the ESP-IDF.  Unfortunately it doesn't seem to help the prometheus component, which requires async_tcp.  These are the lines from the build attempt when the prometheus component is installed:
`
Compiling /data/d1-mini32-024d98/.pioenvs/d1-mini32-024d98/src/main.o
src/main.cpp:22:1: error: 'prometheus' does not name a type
 prometheus::PrometheusHandler *prometheus_prometheushandler;
 ^~~~~~~~~~
src/main.cpp: In function 'void setup()':
src/main.cpp:252:3: error: 'prometheus_prometheushandler' was not declared in this scope
   prometheus_prometheushandler = new prometheus::PrometheusHandler(web_server_base_webserverbase);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:252:38: error: 'prometheus' does not name a type
   prometheus_prometheushandler = new prometheus::PrometheusHandler(web_server_base_webserverbase);
                                      ^~~~~~~~~~
*** [/data/d1-mini32-024d98/.pioenvs/d1-mini32-024d98/src/main.o] Error 1
========================= [FAILED] Took 40.31 seconds =========================
`

2022-12-02 09:47 UTC, dspalu32 commented
Thanks for this.
Web server on ESP32 S2 IDF is working well for me on a few devices.
I haven't really used Web OTA.

2022-12-07 16:24 UTC, nagyrobi commented
Trying with:
```
external_components:
  - source: github://pr#3500
    components: [ web_server ]
    refresh: 1min
```
But fails with:
```
INFO Updating https://github.com/esphome/esphome.git@pull/3500/head
Failed config

async_tcp: None
  {}
This feature is only available with frameworks ['arduino']
```

2022-12-07 16:52 UTC, marshn commented
This is what I have in my yaml. I think you need the additional components:

```
external_components:
  - source: github://pr#3500
    components:
      # list all components modified by this Pull Request here
      - web_server
      - web_server_idf
      - web_server_base
      - captive_portal

2022-12-09 18:15 UTC, dentra commented
Thinking about to remove problematic OTA support for this PR to release main functionality and implement it in another PR

2022-12-10 19:13 UTC, nagyrobi commented
I've tested it on today's DEV and works. Feels snappier than when it was on `arduino`.

2022-12-12 10:57 UTC, nagyrobi commented
Fails with the latest Beta:
```
Compiling /data/ble-erzekelok-proxy/.pioenvs/ble-erzekelok-proxy/src/esphome/components/web_server/list_entities.o
Compiling /data/ble-erzekelok-proxy/.pioenvs/ble-erzekelok-proxy/src/esphome/components/web_server/web_server.o
Compiling /data/ble-erzekelok-proxy/.pioenvs/ble-erzekelok-proxy/src/esphome/components/web_server_base/web_server_base.o
*** [/data/ble-erzekelok-proxy/.pioenvs/ble-erzekelok-proxy/src/esphome/components/web_server_idf/ota_idf.o] Source `src/esphome/components/web_server_idf/ota_idf.cpp' not found, needed by target `/data/ble-erzekelok-proxy/.pioenvs/ble-erzekelok-proxy/src/esphome/components/web_server_idf/ota_idf.o'.
```

2022-12-12 11:25 UTC, dentra commented
> Fails with the latest Beta:
> 
> ```
> Compiling /data/ble-erzekelok-proxy/.pioenvs/ble-erzekelok-proxy/src/esphome/components/web_server/list_entities.o
> Compiling /data/ble-erzekelok-proxy/.pioenvs/ble-erzekelok-proxy/src/esphome/components/web_server/web_server.o
> Compiling /data/ble-erzekelok-proxy/.pioenvs/ble-erzekelok-proxy/src/esphome/components/web_server_base/web_server_base.o
> *** [/data/ble-erzekelok-proxy/.pioenvs/ble-erzekelok-proxy/src/esphome/components/web_server_idf/ota_idf.o] Source `src/esphome/components/web_server_idf/ota_idf.cpp' not found, needed by target `/data/ble-erzekelok-proxy/.pioenvs/ble-erzekelok-proxy/src/esphome/components/web_server_idf/ota_idf.o'.
> ```

you need to clean your project first with `esphome clean project.yaml`

2022-12-12 11:41 UTC, nagyrobi commented
Sorry, yes, indeed.

2022-12-12 11:44 UTC, nagyrobi commented
Seems to me that `web_server` has a smaller heap footprint under `esp-idf` than it had under `arduino`. About 10-11k.
Now can be used together with other big components like `bluetooth_proxy` and still have more than 120k free heap.

2022-12-12 13:42 UTC, dentra commented
> Seems to me that `web_server` has a smaller heap footprint under `esp-idf` than it had under `arduino`. About 10-11k. Now can be used together with other big components like `bluetooth_proxy` and still have more than 120k free heap.

yes, it is very small

2022-12-12 13:46 UTC, Nardol commented
What is missing to this PR to be ready for review instead of draft as it is now?

2022-12-12 14:40 UTC, nagyrobi commented
Web based OTA. 

Which, to be honest, I'd prefer to rather be a kind of sub-package, for security reasons. Any malicious application on the network could do a quick scan and try to OTA on malicious firmware to do DDOS etc...

For higher security I'd prefer to still use the webserver to control things, but not have web-based OTA at all. No browse button and no file upload.

2022-12-12 14:44 UTC, Nardol commented
Because web OTA provided by this webserver version is less secure than this provided by the Arduino based one?

2022-12-12 15:47 UTC, dentra commented
> Because web OTA provided by this webserver version is less secure than this provided by the Arduino based one?

Security is similar to arduino, but implementation is big enough

2022-12-12 15:47 UTC, dentra commented
Dropped OTA support for this PR

2022-12-12 16:14 UTC, nagyrobi commented
> Because web OTA provided by this webserver version is less secure than this provided by the Arduino based one?

No, because OTA is _in principle_ a security weak point, and a web based OTA has a very high vector. It's regardless of the platform. Currently, to add _some_ security you can add a password to the web interface but that makes its usage awkward.

It's up to the user to choose the security measures, I'd just split the web-based OTA from the general webserver package offering a choice for people to still use the webserver but completeky prevent web-based flashing. Now that we're at it...

2022-12-12 16:21 UTC, Nardol commented
Maybe the actual cold weather make my brain slow :slightly_smiling_face: but the web server documentation has the parameter `ota`, which allows to disable OTA via web server.

So I really don't understand the issue with OTA in this PR in particular :wink:

2022-12-12 16:56 UTC, nagyrobi commented
> I really don't understand the issue with OTA in this PR in particular

It has nothing to do with security, it was just a separate idea

2022-12-28 17:32 UTC, rhaamo commented
I was using this PR since the ~23 november with no issues so far on a Shelly 1PM Plus, however I have updated another one to start using it and I'm having issues, after doing the OTA through the esphome dashboard it says that it's ok, log says rebooting, and then the web interface never comes up, and most of the time the led stays on, I have to replug the shelly to restart using it.
(I did try another shelly I had unused for now too, and same issue)

I had no issues with the first one, even when doing multiple OTA in a row to do the calibration.

2022-12-29 17:04 UTC, dentra commented
@rhaamo I just update with latest dev branch and it now really crashes. Will look at...

2022-12-29 17:19 UTC, dentra commented
@rhaamo it crashes even without web_server, so please try to use latest stable esphome version

2022-12-31 22:11 UTC, grischard commented
> * ~No captive_portal support~ No any DNS resolution, only device name to IP

https://github.com/espressif/esp-idf/blob/master/examples/protocols/http_server/captive_portal claims to "redirect all DNS IP questions to point to the softAP and redirect all HTTP requests to the captive portal root page. Triggers captive portal (sign in) pop up on Android, iOS and Windows. Note that the example will not redirect HTTPS requests." 

Can that technique be used?

2023-01-12 16:50 UTC, dentra commented
> > * ~No captive_portal support~ No any DNS resolution, only device name to IP
>
> https://github.com/espressif/esp-idf/blob/master/examples/protocols/http_server/captive_portal 
> Can that technique be used?

@grischard I think yes it can and with link to code that you provided it is no so hard. But it seems to me that it is better to do it in a separate PR right after this PR will solved.

2023-01-27 04:31 UTC, SamKiley commented
Hey, I am not sure if this is the proper place to put this, but I tried adding this commit as done here: https://github.com/esphome/feature-requests/issues/1649
I am getting a compilation error when trying to use the basic web_server at port 80


src/esphome/components/web_server/web_server.cpp: In lambda function:
src/esphome/components/web_server/web_server.cpp:107:40: error: 'class esphome::Application' has no member named 'get_friendly_name'
                    root["title"] = App.get_friendly_name().empty() ? App.get_name() : App.get_friendly_name();
                                        ^~~~~~~~~~~~~~~~~
src/esphome/components/web_server/web_server.cpp:107:91: error: 'class esphome::Application' has no member named 'get_friendly_name'
                    root["title"] = App.get_friendly_name().empty() ? App.get_name() : App.get_friendly_name();
                                                                                           ^~~~~~~~~~~~~~~~~
src/esphome/components/web_server/web_server.cpp:108:42: error: 'class esphome::Application' has no member named 'get_comment'; did you mean 'get_name'?
                    root["comment"] = App.get_comment();
                                          ^~~~~~~~~~~
                                          get_name
Compiling /data/xiao-esp32c3/.pioenvs/xiao-esp32c3/src/esphome/core/log.o
*** [/data/xiao-esp32c3/.pioenvs/xiao-esp32c3/src/esphome/components/web_server/web_server.o] Error 1
========================= [FAILED] Took 21.19 seconds =========================

2023-01-27 06:13 UTC, clinta commented
@SamKiley I'm seeing the same. I've been using this PR successfully for a long time, but it broke with 2022.12.7.

2023-01-27 10:33 UTC, marshn commented
> @SamKiley I'm seeing the same. I've been using this PR successfully for a long time, but it broke with 2022.12.7.

I am seeing the same too. It was working yesterday, but broken today. I am using espHome 2022.11.3 (and was yesterday too) - so I think the problem was caused by the commits that @dentra made recently.

2023-01-27 12:47 UTC, marshn commented
> > @SamKiley I'm seeing the same. I've been using this PR successfully for a long time, but it broke with 2022.12.7.
> 
> I am seeing the same too. It was working yesterday, but broken today. I am using espHome 2022.11.3 (and was yesterday too) - so I think the problem was caused by the commits that @dentra made recently.

As a temporary fix I reverted the recent change to lines 107 & 108 of web_server.cpp (which in my Windows environment is at C:\esphome\esphome-v2022-11\.esphome\external_components\e0644c07\esphome\components\web_server\web_server.cppp). This allows the IDF webserver build and it seems to run OK. I have changed lines 107/108 from:
```
                   root["title"] = App.get_friendly_name().empty() ? App.get_name() : App.get_friendly_name();
                   root["comment"] = App.get_comment();
```
Back to:
```
                   root["title"] = App.get_name();
```
To stop this change being overwritten by what is now in Github I have also changed my configuration.yaml to not refresh for another 100 days, by which time this issue will (hopefully!) be fixed:
````
external_components:
  - source: github://pr#3500
    components:
      - web_server
      - web_server_idf
      - web_server_base
      - captive_portal
    refresh: 100days
````
I'm sure there is a better way to do this, but I needed a quick fix this morning.

2023-01-27 13:06 UTC, dentra commented
@marshn @SamKiley it is dev branch changes and unfortunately they are incompatible with previous version code.
I will look to a solution to support both.

2023-01-27 23:00 UTC, evlo commented
@marshn thank you for posting that, I was afraid I will need to use brain to find out what changed~

2023-01-29 16:25 UTC, bkbartk commented
I have this error
```
Compiling /data/trapkast-light/.pioenvs/trapkast-light/src/esphome/components/web_server_idf/web_server_idf_ota.o
src/esphome/components/web_server/web_server.cpp: In lambda function:
src/esphome/components/web_server/web_server.cpp:107:40: error: 'class esphome::Application' has no member named 'get_friendly_name'
                    root["title"] = App.get_friendly_name().empty() ? App.get_name() : App.get_friendly_name();
                                        ^~~~~~~~~~~~~~~~~
src/esphome/components/web_server/web_server.cpp:107:91: error: 'class esphome::Application' has no member named 'get_friendly_name'
                    root["title"] = App.get_friendly_name().empty() ? App.get_name() : App.get_friendly_name();
                                                                                           ^~~~~~~~~~~~~~~~~
src/esphome/components/web_server/web_server.cpp:108:42: error: 'class esphome::Application' has no member named 'get_comment'; did you mean 'get_name'?
                    root["comment"] = App.get_comment();
                                          ^~~~~~~~~~~
                                          get_name
Compiling /data/trapkast-light/.pioenvs/trapkast-light/src/esphome/components/wifi/wifi_component.o
Compiling /data/trapkast-light/.pioenvs/trapkast-light/src/esphome/components/wifi/wifi_component_esp32_arduino.o
*** [/data/trapkast-light/.pioenvs/trapkast-light/src/esphome/components/web_server/web_server.o] Error 1
========================= [FAILED] Took 154.92 seconds =========================
```

Since the last release, maybe it helps someone, I don't know python or checked the source, But my guess would be that some methods have been changed or renamed

2023-01-30 18:24 UTC, grischard commented
Thank you for the quick fix @marshn.

If you're running esphome on HA OS, the file you want to edit will be `/root/config/esphome/.esphome/external_components/e0644c07/esphome/components/web_server/web_server.cpp`

2023-02-03 17:58 UTC, dentra commented
temporary solution to support 2022.12 added

2023-02-05 11:42 UTC, marshn commented
> temporary solution to support 2022.12 added

This works for me with 2022.12.8. Thankyou @dentra

2023-02-17 04:19 UTC, hlyi commented
@dentra Thanks for the PR! I encountered an issue when use the PR without `web_server` in yaml file. the workaround is the following patch. Could you review it and check if it was okay to incorporate into your PR?
```
     # Increase the maximum supported size of headers section in HTTP request packet to be processed by the server
     add_idf_sdkconfig_option("CONFIG_HTTPD_MAX_REQ_HDR_LEN", 1024)
 
-    if CORE.config[CONF_WEB_SERVER][CONF_OTA]:
+    if CONF_WEB_SERVER in CORE.config and CONF_OTA in CORE.config[CONF_WEB_SERVER]:
         cg.add_define("USE_WEBSERVER_IDF_MULTIPART")
```

2023-02-20 11:33 UTC, dentra commented
@hlyi thanks for contributing

2023-02-22 00:30 UTC, jesserockz commented on esphome/components/web_server/__init__.py
> +        raise cv.Invalid("Enabling 'ota' is not supported for IDF framework yet")
If this is not supported, why are there ota files for the idf web server? 
You either need to remove that code from this PR, or allow OTA (if its working)

2023-02-22 01:05 UTC, jesserockz requested changes
Overall its looking good. I have tested locally and it seems to be working as expected. No OTA support yet, but perhaps get this PR merged, then another PR can add the OTA code I requested to remove above?

2023-02-22 01:05 UTC, jesserockz commented on esphome/components/web_server_idf/__init__.py
> +        cg.add_define("USE_WEBSERVER_IDF_MULTIPART")
This define is not even used anywhere?
```suggestion
```

2023-02-23 08:57 UTC, grischard commented
Thank you @jesserockz! It looks like a053f8481d66dc3c2f931960cc33bc415d00aa03 which turns auto_load into a function broke this PR because auto_load is [iterated on](https://github.com/esphome/esphome/blob/dev/esphome/config.py#L308):

```
INFO Reading configuration /config/esphome/bed.yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 963, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 941, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
  File "/esphome/esphome/config.py", line 986, in read_config
    res = load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 840, in load_config
    return _load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 828, in _load_config
    result = validate_config(config, command_line_substitutions)
  File "/esphome/esphome/config.py", line 756, in validate_config
    result.run_validation_steps()
  File "/esphome/esphome/config.py", line 125, in run_validation_steps
    task.step.run(self)
  File "/esphome/esphome/config.py", line 308, in run
    for load in component.auto_load:
TypeError: 'function' object is not iterable
```

2023-03-06 10:07 UTC, marshn commented
I am seeing the same problems as [grischard](https://github.com/grischard).

For me, reverting two commits that jesserockz made recently allows this PR to work again on both the dev and release branch :
https://github.com/esphome/esphome/commit/a053f8481d66dc3c2f931960cc33bc415d00aa03 (turns auto_load into a function)
https://github.com/esphome/esphome/commit/592800b88dc3404b9a4b9268b2308a25678f975e (removes a 'using')

As a temporary fix I have reverted the change to web_server_base \_\_init\_\_.py  (which in my Windows environment is at C:\esphome\esphome-v2023-2\.esphome\external_components\e0644c07\esphome\components\web_server_base\\_\_init\_\_.py).  
( If you're running esphome on HA OS, I would expect the file to edit to be /root/config/esphome/.esphome/external_components/e0644c07/esphome/components/web_server_base/\_\_init\_\_.py )

Removed lines 9-14

````
def AUTO_LOAD():
    if CORE.using_arduino:
        return ["async_tcp"]
    if CORE.using_esp_idf:
        return ["web_server_idf"]
    return []
````

(Re)added at line 9:
````
if CORE.using_arduino:
    AUTO_LOAD = ["async_tcp"]
elif CORE.using_esp_idf:
    AUTO_LOAD = ["web_server_idf"]
````    
And the change to web_server_idf.h (which in my Windows environment is at C:\esphome\esphome-v2023-2\.esphome\external_components\e0644c07\esphome\components\web_server_idf\web_server_idf.h).  
( If you're running esphome on HA OS, I would expect the file to edit to be /root/config/esphome/.esphome/external_components/e0644c07/esphome/components/web_server_idf/web_server_idf.h )


(Re)added line 19:

````
using String = std::string;
````

To stop this change being overwritten by what is now in Github I have also changed my configuration.yaml to not refresh for another 100 days, by which time this issue will (hopefully!) be fixed:

````
external_components:
  - source: github://pr#3500
    components:
      - web_server
      - web_server_idf
      - web_server_base
      - captive_portal
    refresh: 100days
````
I'm sure there is a better way to do this, but I needed a quick fix this morning.

2023-03-09 15:38 UTC, spali commented
The problem is the required change in `esphome/loader.py` which is not possible to pull by `external_components`.

I think there is no cleaner workaround for us.
The fastest simplest would be if @jesserockz would cherry-pick https://github.com/esphome/esphome/commit/a053f8481d66dc3c2f931960cc33bc415d00aa03 into dev branch, so at least we can use this PR with the dev branch until the PR is fully merged.

2023-03-09 17:14 UTC, spali commented
Till then for convenience... made a branch of this PR with the two commits reverted.
Just use `github://spali/esphome@pr3500` as source.

2023-03-12 22:35 UTC, jesserockz commented
Apologies for breaking the PR while using `external_components`. I always check out the local branch when testing PRs so I do not notice these things sometimes.

#4550

2023-03-13 12:25 UTC, spali commented
@jesserockz Thanks for the fix, much appreciated.
works with 2023.3.0b3 and dev branch.

2023-03-13 20:39 UTC, syssi commented
Is the `local` option supposed to work? For me it doesn't compile. The following configuration

```
web_server:
  local: true
```

results in

```
src/esphome/components/web_server/web_server.cpp: In member function 'void esphome::web_server::WebServer::handle_index_request(esphome::web_server_idf::AsyncWebServerRequest*)':
src/esphome/components/web_server/web_server.cpp:158:107: error: cannot convert 'esphome::web_server_idf::AsyncProgmemResponse*' to 'esphome::web_server_idf::AsyncWebServerResponse*' in initialization
   AsyncWebServerResponse *response = request->beginResponse_P(200, "text/html", INDEX_GZ, sizeof(INDEX_GZ));
```

2023-03-16 01:50 UTC, Greg-MM commented
OTA seems to be working for me (on an Emporia Vue 2) when using the command line, however it does not reboot afterword and I have to power cycle to get up and running again, should there be a reboot command inside the below if statement in OTA::end? I am not sure if the esphome command is supposed to send a reboot command after flashing and that is not working or if the ESP itself is supposed to reboot after a successful update.
I also don't know if not rebooting is specific to the Vue 2 or not.

```
if (this->error_ == ESP_OK) {
    this->error_ = esp_ota_set_boot_partition(this->partition_);
    // ADD REBOOT COMMAND HERE?
  }
```

2023-03-17 10:43 UTC, evlo commented
Today I noticed a bit weird behavior, it might be specific to my config, but when using esp-idf webserver version 1
```
web_server:
  version: 1
```
I get constant connection loop from HA API, although it seems to be working.

Can someone else please verify it happens to them too?

2023-03-21 17:47 UTC, dentra commented on esphome/components/web_server/__init__.py
> +        raise cv.Invalid("Enabling 'ota' is not supported for IDF framework yet")
done in [27a02b5](https://github.com/esphome/esphome/pull/3500/commits/27a02b5d48ba35495b61b8a7e1f5fe75a44433a4)

2023-03-21 17:51 UTC, dentra commented
> Is the `local` option supposed to work? For me it doesn't compile. The following configuration
> 
> ```
> web_server:
>   local: true
> ```
> 
> results in
> 
> ```
> src/esphome/components/web_server/web_server.cpp: In member function 'void esphome::web_server::WebServer::handle_index_request(esphome::web_server_idf::AsyncWebServerRequest*)':
> src/esphome/components/web_server/web_server.cpp:158:107: error: cannot convert 'esphome::web_server_idf::AsyncProgmemResponse*' to 'esphome::web_server_idf::AsyncWebServerResponse*' in initialization
>    AsyncWebServerResponse *response = request->beginResponse_P(200, "text/html", INDEX_GZ, sizeof(INDEX_GZ));
> ```

@syssi fixed in [[46b110d](https://github.com/esphome/esphome/pull/3500/commits/46b110dc23115d40784b1e5a7370a4d9623a681d)]

2023-04-23 11:15 UTC, evlo commented
The OTA issue is just with this button right?
Because I'm using ota both from esp home web and from esphome python script with this web server added as external component successfully for months now.
![image](https://user-images.githubusercontent.com/8813196/233836587-2c8958c8-4e76-48bf-87c3-82a753759d0e.png)

2023-07-10 18:54 UTC, grischard commented
@jesserockz I don't know if you've seen, but it looks like @dentra did the changes you'd requested.

2023-07-10 19:10 UTC, grischard commented
Although compilation currently throws an error for me:

```
In file included from src/esphome/components/web_server/web_server.cpp:1:
src/esphome/components/web_server/web_server.h:17:53: error: expected initializer before 'PROGMEM'
 extern const uint8_t ESPHOME_WEBSERVER_INDEX_HTML[] PROGMEM;
                                                     ^~~~~~~
Compiling /data/bedroom/.pioenvs/bedroom/src/esphome/components/wifi/wifi_component.o
src/esphome/components/web_server/web_server.cpp: In member function 'void esphome::web_server::WebServer::handle_index_request(esphome::web_server_idf::AsyncWebServerRequest*)':
src/esphome/components/web_server/web_server.cpp:330:50: error: 'ESPHOME_WEBSERVER_INDEX_HTML' was not declared in this scope
       request->beginResponse_P(200, "text/html", ESPHOME_WEBSERVER_INDEX_HTML, ESPHOME_WEBSERVER_INDEX_HTML_SIZE);
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/web_server/web_server.cpp:330:50: note: suggested alternative: 'ESPHOME_WEBSERVER_INDEX_HTML_SIZE'
       request->beginResponse_P(200, "text/html", ESPHOME_WEBSERVER_INDEX_HTML, ESPHOME_WEBSERVER_INDEX_HTML_SIZE);
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  ESPHOME_WEBSERVER_INDEX_HTML_SIZE
*** [/data/bedroom/.pioenvs/bedroom/src/esphome/components/web_server/web_server.o] Error 1
```

2023-07-11 13:02 UTC, dentra commented
> Although compilation currently throws an error for me

Can't reproduce your problem. PROGMEM definition is part of ESPHome core, see core/hal.h

2023-07-11 15:06 UTC, grischard commented
Full log:

```
INFO ESPHome 2023.6.5
INFO Reading configuration /config/esphome/test.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing test (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.3.0)
--------------------------------------------------------------------------------
Library Manager: Installing bblanchon/ArduinoJson @ 6.18.5
INFO Installing bblanchon/ArduinoJson @ 6.18.5
Unpacking  [####################################]  100%
Library Manager: ArduinoJson@6.18.5 has been installed!
INFO ArduinoJson@6.18.5 has been installed!
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40404.0 (4.4.4) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- ArduinoJson @ 6.18.5
Compiling /data/test/.pioenvs/test/src/esphome/components/captive_portal/captive_portal.o
Compiling /data/test/.pioenvs/test/src/esphome/components/esp32/core.o
Compiling /data/test/.pioenvs/test/src/esphome/components/esp32/gpio.o
Compiling /data/test/.pioenvs/test/src/esphome/components/esp32/preferences.o
Compiling /data/test/.pioenvs/test/src/esphome/components/json/json_util.o
Compiling /data/test/.pioenvs/test/src/esphome/components/mdns/mdns_component.o
Compiling /data/test/.pioenvs/test/src/esphome/components/mdns/mdns_esp32.o
Compiling /data/test/.pioenvs/test/src/esphome/components/mdns/mdns_esp8266.o
Compiling /data/test/.pioenvs/test/src/esphome/components/mdns/mdns_host.o
Compiling /data/test/.pioenvs/test/src/esphome/components/mdns/mdns_rp2040.o
Compiling /data/test/.pioenvs/test/src/esphome/components/network/util.o
Compiling /data/test/.pioenvs/test/src/esphome/components/web_server/list_entities.o
Compiling /data/test/.pioenvs/test/src/esphome/components/web_server/web_server.o
Compiling /data/test/.pioenvs/test/src/esphome/components/web_server_base/web_server_base.o
Compiling /data/test/.pioenvs/test/src/esphome/components/web_server_idf/web_server_idf.o
Compiling /data/test/.pioenvs/test/src/esphome/components/wifi/wifi_component.o
In file included from src/esphome/components/web_server/web_server.cpp:1:
src/esphome/components/web_server/web_server.h:17:53: error: expected initializer before 'PROGMEM'
 extern const uint8_t ESPHOME_WEBSERVER_INDEX_HTML[] PROGMEM;
                                                     ^~~~~~~
src/esphome/components/web_server/web_server.cpp: In member function 'void esphome::web_server::WebServer::handle_index_request(esphome::web_server_idf::AsyncWebServerRequest*)':
src/esphome/components/web_server/web_server.cpp:330:50: error: 'ESPHOME_WEBSERVER_INDEX_HTML' was not declared in this scope
       request->beginResponse_P(200, "text/html", ESPHOME_WEBSERVER_INDEX_HTML, ESPHOME_WEBSERVER_INDEX_HTML_SIZE);
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/web_server/web_server.cpp:330:50: note: suggested alternative: 'ESPHOME_WEBSERVER_INDEX_HTML_SIZE'
       request->beginResponse_P(200, "text/html", ESPHOME_WEBSERVER_INDEX_HTML, ESPHOME_WEBSERVER_INDEX_HTML_SIZE);
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  ESPHOME_WEBSERVER_INDEX_HTML_SIZE
Compiling /data/test/.pioenvs/test/src/esphome/components/wifi/wifi_component_esp32_arduino.o
*** [/data/test/.pioenvs/test/src/esphome/components/web_server/web_server.o] Error 1
========================= [FAILED] Took 203.84 seconds =========================
```

Minimal example to reproduce:

```
esphome:
  name: test
  friendly_name: Test

esp32:
  board: esp32dev
  framework:
    type: esp-idf
web_server:

wifi:
  ssid: test
  password: password

external_components:
  - source: github://pr#3500
    components:
      - web_server
      - web_server_idf
      - web_server_base
      - captive_portal
```

2023-07-11 15:07 UTC, grischard commented
Are you maybe running against the latest dev tree and I'm on the latest stable release, and something has changed underneath?

2023-07-11 16:31 UTC, dentra commented
> Are you maybe running against the latest dev tree and I'm on the latest stable release 2023.6.5, and something has changed underneath?

Hm..., no. in my test configs I am always use light domain. So you can add empty `light` to your config as workaround.
```yaml
light:
```

anyway I will fix this behaviour.

2023-07-11 18:14 UTC, kbx81 commented on esphome/components/web_server/__init__.py
> +        raise cv.Invalid("Enabling 'ota' is not supported for IDF framework yet")
Rebasing changed the hash so I can't see what was modified. Can either of you confirm if this is ok?

2023-07-11 20:21 UTC, grischard commented
Thank you, [3c1e407](https://github.com/esphome/esphome/pull/3500/commits/3c1e407c31745a8381b932763cff3aa0197330a9) fixed the compilation error for me.

2023-07-11 22:11 UTC, fernandodelucca commented
Hi,

i'm testing with FQDN url to access my esphome, eg.: http://solar-panel.localdomain.local but with IP address or hostname works correctly.

[18:56:36][D][esp-idf:000]: W (3107854) httpd_parse: parse_block: request URI/header too long
[18:56:36][D][esp-idf:000]: W (3107856) httpd_txrx: httpd_resp_send_err: 431 Request Header Fields Too Large - Header fields are too long
[18:56:37][D][esp-idf:000]: W (3108660) httpd_parse: parse_block: request URI/header too long
[18:56:37][D][esp-idf:000]: W (3108661) httpd_txrx: httpd_resp_send_err: 431 Request Header Fields Too Large - Header fields are too long
[18:56:37][D][esp-idf:000]: W (3108673) httpd_parse: parse_block: request URI/header too long
[18:56:37][D][esp-idf:000]: W (3108675) httpd_txrx: httpd_resp_send_err: 431 Request Header Fields Too Large - Header fields are too long
[18:56:37][D][esp-idf:000]: W (3108872) httpd_parse: parse_block: request URI/header too long
[18:56:37][D][esp-idf:000]: W (3108873) httpd_txrx: httpd_resp_send_err: 431 Request Header Fields Too Large - Header fields are too long

2023-07-11 22:42 UTC, kbx81 commented on esphome/components/web_server_base/__init__.py
> +AUTO_LOAD = ["web_server_idf"] if CORE.using_esp_idf else ["async_tcp"]
@jesserockz how do you feel about the modification to address this? 😇

2023-07-11 22:43 UTC, kbx81 approved these changes, later dismissed
Tested on ESP32 + ESP32-S3 -- builds & runs without any issues.

2023-07-11 22:52 UTC, jesserockz requested changes, later dismissed

2023-07-11 22:52 UTC, jesserockz commented on script/build_codeowners.py
If you use AUTO_LOAD as a function, these changes are not needed.

2023-07-11 22:52 UTC, jesserockz commented on esphome/components/web_server_base/__init__.py
> +    AUTO_LOAD = ["web_server_idf"]
```suggestion
def AUTO_LOAD():
    if CORE.using_arduino:
        return ["async_tcp"]
    elif CORE.using_esp_idf:
        return ["web_server_idf"]
    else:
        return []
```

2023-07-11 23:10 UTC, kbx81 commented on esphome/components/web_server_base/__init__.py
> +AUTO_LOAD = ["web_server_idf"] if CORE.using_esp_idf else ["async_tcp"]
For posterity -- this is fixed as `AUTO_LOAD` can be a function now. Patch applied accordingly.

2023-07-11 23:32 UTC, kbx81 approved these changes

2023-07-12 00:08 UTC, merged