Fix bogus reading on no communication with MAX31865
OttoWinter/esphomeyaml pull request #3505
Opened 2022-05-28 01:17 UTC by DAVe3283

# What does this implement/fix?

Prevents bogus reading when MAX31865 has no communication.
Explicitly checks for all zeros or all ones in the RTD registers (virtually impossible when the chip is operating in datasheet specs) and reports an error instead of -242.02°C.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#3289

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
esphome:
  name: d1-mini-proto

esp8266:
  board: d1_mini

# Enable logging
logger:
  # Get detailed output from max31865
  level: VERY_VERBOSE
  logs:
    # Silence unrelated chatty components
    api: DEBUG
    api.connection: DEBUG
    api.service: DEBUG
    app: DEBUG
    json: DEBUG
    scheduler: DEBUG
    sensor.filter: DEBUG
    sensor: DEBUG

# Enable Home Assistant API
api:
  password: !secret d1_mini_proto_api
  encryption:
    key: !secret d1_mini_proto_key

ota:
  password: !secret d1_mini_proto_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1-Mini-Proto Fallback Hotspot"
    password: !secret d1_mini_proto_ota

captive_portal:

spi:
  clk_pin: GPIO14
  mosi_pin: MOSI
  miso_pin: MISO

#  Override internal version with proposed patch
external_components:
  - source: github://DAVe3283/esphome@dev
    components: ["max31865"]

sensor:
  - platform: max31865
    name: "PT1000 Test"
    cs_pin: GPIO15
    reference_resistance: 4.3 kΩ
    rtd_nominal_resistance: 1 kΩ
    rtd_wires: 3
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-06-04 15:20 UTC, DAVe3283 commented
This has been running fine for me for over a week, and fixes the problem described in esphome/issues#3289.

For what it is worth, I am the original author of the MAX31865 integration (#832), but it was written before codeowners were tracked. I added myself in this PR to address that going forward.

@OttoWinter and/or @jesserockz anything I need to do before this can be merged?

2022-06-07 11:04 UTC, jesserockz requested changes
Just one comment about the init file, otherwise looks fine.

2022-06-07 11:04 UTC, jesserockz commented on esphome/components/max31865/__init__.py
> +DEPENDENCIES = ["spi"]
This should be in the `sensor.py` file.

Actually, both of these lines can go in there, but `DEPENDENCIES` must move. 

Surprised it was not there already. That's gonna trigger me to check every component now, thanks...haha

2022-06-07 13:46 UTC, DAVe3283 commented on esphome/components/max31865/__init__.py
> +DEPENDENCIES = ["spi"]
Done!

2022-06-07 21:40 UTC, jesserockz approved these changes

2022-06-07 21:40 UTC, jesserockz commented
Thanks!

2022-06-07 21:58 UTC, merged