Support for LibreTuya platform (RTL8710, BK7231 & other modules)
OttoWinter/esphomeyaml pull request #3509
Opened 2022-05-28 20:35 UTC by kuba2k2

# What does this implement/fix?

This is not a single chip, but rather a universal PlatformIO framework that I'll use to add support for cheap IoT chips found in modules manufactured by Tuya, Inc. These chips are normally incompatible with ESP32/ESP8266 firmwares, and have very limited vendor and community support, so people tend to swap these for ESP-12 modules, which is also not always possible. This is often very troublesome and wasteful.

My project is made to be as compatible with ESP32 Arduino core as possible. This decision was made especially with ESPHome in mind, so that porting it would require minimal changes to its components. The APIs are made to resemble ESP32 APIs closely.

This PR is not yet ready, as [LibreTuya](https://github.com/kuba2k2/libretuya) is still under rapid development; I'm opening it mostly to track my progress and let others know about this project.

**If you're reading this and have any non-ESP IoT chips - you can be helpful by contacting me in this discussion** (or anywhere else).

### Porting progress
- [x] Boots :clap: 
- [x] WiFi, mDNS, preferences backend
- [ ] OTA
- [ ] GPIO, ADC, PWM
- [ ] I2C
- [ ] SPI

As I'm totally new to ESPHome's codebase, any reviews of the work done so far will be appreciated.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> (not yet)

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] LibreTuya?

## Example entry for `config.yaml`:

```yaml
libretuya:
  board: wr3
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-06-12 06:02 UTC, RoganDawes commented
Nice! Thanks for working on this!

I'm curious about your choice to make a new component, though, rather than a new platform.

Are you actually making use of some underlying Tuya functionality, or is this a bare metal implementation?

I made a very cursory port to STM32 a year or so ago, available in the stm32 branch of my fork at https://GitHub.com/RoganDawes/esphome. 

That was achieved by basically defining a new processor family alongside the existing esp8266 and esp32, then iteratively fixing the error messages! 🤪 Admittedly, that avoided all of the networking code, and is therefore a lot simpler than this work.

2022-06-12 07:37 UTC, kuba2k2 commented
ESP32 and ESP8266 are also implemented as components, thus my choice was the same. In your fork you put chip-specific code in the HAL itself; I think EspHome is made that way so the HALs are "abstract", and the platform component provides implementation of everything. Curiously, this does apply to GPIO, system control, but doesn't to i.e. WiFi.

I'm trying to avoid using Tuya SDKs, so I'm taking vendor-provided codebases. Everything else (PIO builders, Arduino HAL code, OTA updater, some other APIs) was written by me from scratch (though for Realtek I had an official Arduino core for a similar CPU, so it was mostly a matter of code cleanup). 

See the project's repo for more details. I'm trying to keep everything as universal as possible, so that adding new chips will most likely not require any changes to ESPHome.

2022-06-12 09:27 UTC, RoganDawes commented
My apologies, I see there was a substantial refactor of the platform code after I did my port. (First commit to components/esp32/ is in September 2021). So it makes sense to me now.

2022-06-22 12:35 UTC, rradar commented
Hello @kuba2k2 :wave: 
thank's for the effort you put in the libretuya platform and the up streaming to esphome :rocket: 

Is this already in state that it could get tested? Looks like only I2C and SPI is missing now...

I own a device with WB3S chip (https://www.esphome-devices.com/devices/Nameless-DS-102/) and wonder if I could/should try to flash it? If so could you give me a very short instruction how to proceed?

Thank's

2022-06-22 16:09 UTC, kuba2k2 commented
> Is this already in state that it could get tested? Looks like only I2C and SPI is missing now...

That's the state of LT implementation in ESPHome, but not all features are implemented for every platform yet. Currently, you can check in [the docs](https://kuba2k2.github.io/libretuya/docs/implementation-status/) which features are supported for the BK7231T. I haven't started doing WiFi impl yet, so ESPHome probably wouldn't even run right now.

You can follow the development process in the repo or by joining our Discord server. I'll let you know when I'll have any usable build of ESPHome working.

2022-07-01 11:09 UTC, openshwprojects commented
@rradar OpenBeken already supports this device with WB3S, you should try it, it's a tested solution and I daily provide support for that:
https://github.com/openshwprojects/OpenBK7231T_App
BK7231T, BK7231N, XR809, BL602 are supported, there is Tasmota Device Groups support, Home Assistant support, simple scripting, events, power on/ state saving, and much more.

2022-07-01 11:20 UTC, kuba2k2 commented
..but does it support EspHome? This thread is about porting EspHome, not really about Tasmota-alternatives.

2022-10-03 10:16 UTC, RoganDawes commented
(I'd raise this as an issue on your own repo, but issues are disabled.)

Trying this out with WR3E, and run into the following:
```
Compiling .pioenvs/test/src/esphome/components/libretuya/core.cpp.o
src/esphome/components/libretuya/core.cpp: In function 'void esphome::arch_init()':
src/esphome/components/libretuya/core.cpp:22:6: error: 'class LibreTuya' has no member named 'wdtEnable'
   LT.wdtEnable();
      ^
src/esphome/components/libretuya/core.cpp: In function 'void esphome::arch_feed_wdt()':
src/esphome/components/libretuya/core.cpp:33:41: error: 'class LibreTuya' has no member named 'wdtFeed'
 void IRAM_ATTR HOT arch_feed_wdt() { LT.wdtFeed(); }
                                         ^
*** [.pioenvs/test/src/esphome/components/libretuya/core.cpp.o] Error 1
======================================================================= [FAILED] Took 3.02 seconds =======================================================================
```
Looks like the last commit in libretuya-esphome introduced the WDT, but didn't implement it? Or do I just not have the latest libretuya? I installed libretuya-esphome today, and that did all the subsequent installation for me.

2022-10-03 10:58 UTC, kuba2k2 commented
Hi @RoganDawes 
Yes, currently manual installation of libretuya itself is required (libretuya-esphome pulls the PIO registry version, which is way outdated). [You can run `platformio platform install -f https://github.com/kuba2k2/libretuya`](https://docs.libretuya.ml/docs/getting-started/) to install the latest version.

Also, if you face any other issues, feel free to raise them in the [main LibreTuya repo](https://github.com/kuba2k2/libretuya). I'm not sure why issues are disabled, maybe it inherited from the fork parent repo.

2022-10-15 18:44 UTC, rickyelopez commented
Just got a device that uses a Tuya CBU chip which is not pin compatible with any ESP boards. Before I mangle this thing trying to make one fit, figured I'd take a closer look at this.

Just glancing at your changes, seems like the only chip that is supported by this right now is the wr3? Any chance you've looked into supporting the CBU (which uses a bk7231N as far as I can tell) or know what might be required to do so? Happy to help develop/test if you can point me in the right direction

2022-10-15 18:47 UTC, Cossid commented
CBU can currently be utilized using the generic BK7231N board `generic-bk7231n-qfn32-tuya`

2022-10-15 18:53 UTC, kuba2k2 commented
> Just glancing at your changes, seems like the only chip that is supported by this right now is the wr3?

@rickyelopez 
No; all the chips (formally called "boards") from [the docs](https://docs.libretuya.ml/docs/status/supported/) are supported - as long as they support the Arduino core (CBU does) - even though they're not listed on ESPHome code.

If you're using the wizard, it fetches the board list from PlatformIO and shows all available choices. Because the PIO Registry package is very outdated, if your board of choice is not yet in the wizard, you have to choose any and then edit the generated .yaml manually.

As @Cossid pointed out, CBU is not yet available as a proper board, but it works just fine using the generic board (they only differ in pin assignments - generic has them all).

2022-10-15 18:54 UTC, rickyelopez commented
Oh nice, that's awesome! Thanks for the fast replies @Cossid and @kuba2k2, I'm gonna play with this today, see if I can get it set up!

2022-10-16 03:04 UTC, rickyelopez commented
Getting a couple of link errors, any suggestions?

```
.pioenvs/living-room-remote/src/main.cpp.o: In function `setup':
/home/ricclopez/repos/resphome/.esphome/build/living-room-remote/src/main.cpp:192: undefined reference to `vtable for esphome::remote_receiver::RemoteReceiverComponent'
.pioenvs/living-room-remote/src/main.cpp.o: In function `std::string::_Rep::_M_dispose(std::allocator<char> const&)':
/home/ricclopez/.platformio/packages/toolchain-gccarmnoneeabi@1.40804.0/arm-none-eabi/include/c++/4.8.4/bits/basic_string.h:249: undefined reference to `vtable for esphome::remote_transmitter::RemoteTransmitterComponent'
```

relevant parts of the yaml:
```yaml
libretuya:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: latest

remote_receiver:
  id: rtrx
  pin:
    number: D4
    mode:
      input: true
      pullup: true
    # inverted: true
  # dump: all
  buffer_size: 1024

remote_transmitter:
  id: rttx
  pin: D3
  carrier_duty_percent: 50%
```

2022-10-16 03:11 UTC, Cossid commented
@rickyelopez many less common modules have not been reviewed yet, and need adjustments to defines where platform separation is needed.  In most cases, you can change `#ifdef USE_ESP32` to `#if defined(USE_ESP32) || defined(USE_LIBRETUYA)` and it will probably work, but no guarantee.  You probably need to do that for anything in .h/.cpp files in the remote_receiver and remote_transmitter modules.

2022-10-16 03:11 UTC, rickyelopez commented
Cool I'll give that a shot, thanks!

2022-10-16 08:11 UTC, rickyelopez commented
Hate to keep spamming this thread but I've been stuck on this for hours now. I got the firmware building and uploading, but it doesn't do anything. I've gone so far as to comment out everything except the minimum from the yaml, but still nothing. Doesn't connect to wifi, doesn't create the fallback AP, doesn't even spit anything out on either UART (even with `loglevel: verbose`).

I've also tried building and flashing the PinScan example from the libretuya repo, again, nothing on either UART.

If I restore the backup I took of the stock firmware, everything goes back to working fine, so I don't think I broke anything.

Any suggestions?

2022-10-16 08:49 UTC, kuba2k2 commented
Hi, how exactly are you uploading the firmware? It may be tricky at first, so make sure you follow the guides in the docs. It's best to use ltchiptool or Esphome built-in uploader, which safeguards against flashing the wrong file to the wrong offset. I'm always saying that tools like BkWriter or hid_download_py are terrible and should never be used.

2022-12-07 18:28 UTC, kuba2k2 commented
Hi @jesserockz 
What does this PR need so that we can make it merge-able? It's not feature-complete, many components will not work yet, but I think that's the case with RP2040 as well.
I need we need to add a test.yaml and some documentation pages. Can you point at what else needs to be done? Or are there any certain requirements this needs to meet first?

2023-01-02 14:32 UTC, rspaargaren commented
I really hope it is possible to ingrate this functionallity into ESPHOME. I bought a TUYA switch [Aubess 20A Switch based on a Tuya CB2S board with BK7231N chip]... and found out it was not ESP based any more. So are a lot of them by now, as I just learned... The fork of @kuba2k2 worked like a charm and I could flash the device and use it like a normal ESP. However I don't like to have a seperate environment for just this ESP devices I like to update them all from the main desktop.

2023-01-02 19:44 UTC, RoganDawes commented
Trying to use the WR3E in a CBI Astute Smart Isolator. I have been able to flash the basic ESPHome onto the RTL8710, but am struggling to get the `uart:` configured.
I have tried:
```
uart:
  rx_pin: PA18
  tx_pin: PA23
  baud_rate: 9600
```

But I get an error trying to initialise it on boot:

```
[C][ota:477]: There have been 9 suspected unsuccessful boot attempts.
[D][lt.preferences:104]: Saving 1 preferences to flash...
[D][lt.preferences:133]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[C][uart.lt:049]: Setting up UART...
ROM:[V0.1]
FLASHRATE:4
BOOT TYPE:0 XTAL:40000000
IMG1 DATA[1168:10002000]
```
and it eventually falls back to safe mode.

Any idea what I am doing wrong?

2023-01-03 06:08 UTC, RoganDawes commented
> Any idea what I am doing wrong?

Apparently my comprehension skills are lacking - I had the RX and TX swapped around. Using the correct values worked, but now I am getting:
```
08:06:06 | [E] | [tuya:409] | Initialization failed at init_state 0
```
Will try debug that.

2023-01-03 06:18 UTC, kuba2k2 commented
You can use values like RX2 and TX2 to make sure you don't get these mixed up. Otherwise, it'll detect a non-hardware UART and try to use software serial.

2023-01-03 07:38 UTC, RoganDawes commented
Ah, nice! I guess the Software serial path is broken, then, because my device was crashing at that point.

2023-01-03 08:12 UTC, kuba2k2 commented
Soft serial works on Realtek, but it's TX-only. I'm not sure what happens when you try to activate SS on hardware UART pins, that's probably why it failed. Also, I'm not sure if it can handle baud rates like this - it's a very hacky implementation using timers, and I couldn't find more accurate/faster timers on RTL.

2023-01-04 08:56 UTC, RoganDawes commented
> Soft serial works on Realtek, but it's TX-only. I'm not sure what happens when you try to activate SS on hardware UART pins, that's probably why it failed. Also, I'm not sure if it can handle baud rates like this - it's a very hacky implementation using timers, and I couldn't find more accurate/faster timers on RTL.

Turns out there was no additional microcontroller connected via UART, but rather the module was making direct GPIO connections. I got the details figured out, and all is working perfectly.

2023-01-19 22:34 UTC, donburch888 commented
Thanks Kuba for your work here. I have just found out by chance about this and CloudCutter which look an almost perfect match to get Tuya devices into ESPHome environment Over the Air !

I am concerned that the vulnerability may get patched before LibreTuya is considered "ready" to merge into ESPHome, and that would mean that so many users would miss out.  The sooner that ESPHome announce the exploit, more users will find out and take advantage before it gets patched.  Those with chips not yet supported also benefit by being alerted to the exploit.

2023-01-20 08:37 UTC, kuba2k2 commented
LibreTuya itself has pretty much nothing to do with Cloudcutter. In fact, the vulnerability has been patched for nearly a year now.

Same thing applies for ESP chips. We've had tuya-convert a few years ago, but AFAIK it doesn't work on most newer Tuya devices - and users still benefit from ESPHome on these devices. Cloudcutter/tuya-convert just eliminates the need to disassemble devices. Users of patched devices can still flash ESPHome by wires, whether it's an ESP chip or a Beken/Realtek.

2023-01-20 08:57 UTC, DidierA commented
Tuya has been informed of the vulnerability used by cloucutter before it was released publicly, and yet I bought some smartplugs last month and I could flash them with cloudcutter :) 
@kuba2k2 Thank you for this fork, it has allowed me to use these smartplugs with esphome, and I agree that merging this PR would help a lot of users.

2023-01-28 21:10 UTC, digiblur commented
Looking forward to seeing this folded into ESPHome as it will definitely be a game changer for many.

2023-01-28 21:28 UTC, kuba2k2 commented
@jesserockz what do you think about this? It's been tested by multiple users already, on a whole variety of devices and with many components and peripherals. That being said, some things (like I2C) are still not implemented on the ESPHome side, but I see it was done in a similar fashion for RP2040 in #3284. The current state (needing to download a forked version, without an easy way to use it in Home Assistant) keeps many users away from using ESPHome on newer devices (those with non-ESP chips), unless they do a chip swap.

If you let me know what should I add/fix/correct/improve (aside from the Python lint error that I missed, and probably some test YAMLs), we could go through a review process to get this merged at some point eventually.

2023-01-28 21:52 UTC, digiblur commented
I can confirm this works great!  I've been running a build I put on a night light plug with motion, PWM leds, etc and it works awesome!

2023-01-28 21:56 UTC, Cossid commented
I can also add that I have this running on about 30 wall switches, 40ish bulbs, and a few misc devices (plugs, spotlights, etc), and it has been excellent so far.

2023-01-29 05:12 UTC, RoganDawes commented
> Following project violates Tuya Inc trademark. The license status is not clear. Legal action will be taken shortly.

Is legal action necessary? What remedies would satisfy you? Then we can avoid any unnecessary unpleasantness.

2023-01-29 05:26 UTC, donburch888 commented
> Is legal action necessary? 
"ZhaoJunSmart"is a new empty profile - no indication that it is a real person, let alone connected to Tuya.  Probably just another scammer trying to scare up money for nothing.

2023-01-29 05:49 UTC, digiblur commented
Looks like it is gone already. That was quick.

2023-02-03 04:15 UTC, rickyelopez commented
+1 on merging this. I haven't had any issues either, and I would really like to be able to manage all of my devices from the latest version of esphome in homeassistant. This is awesome!

2023-02-03 07:41 UTC, openshwprojects commented
The best solution to clear up legal confusion would be to contact Tuya directly. Something like: "can I use your registered commercial trademark name to advertise my jailbreak 3rd party product". Project author should do it first before getting potentials problems for esphome.

2023-02-03 07:53 UTC, kuba2k2 commented
Did you do that for OpenBeken? I believe that also is a trademark name. ESPHome has nothing to do with LT's name, and we're going to change it anyway. And, if you're trying to scare out esphome devs from merging this, please don't.

2023-02-03 09:34 UTC, openshwprojects commented
Please do not make accusations here, @kuba2k2 . Your offtopic statements (Obk? Scare?) **should not have place here and this thread has nothing to do with LibreTuya**, although for the sake of transparency, we will note that [we're working on a new name as soon](https://github.com/openshwprojects/OpenBK7231T_App/issues/638) as it was brought to our attention that it poses a potential issue, just as we're working on other issues.

It was just our private suggestion related to the potential merge made with good faith, especially considering that you already have a history of violations both with basing your project on our 3 years of research made on Elektroda without giving a credit (_what a coincidence, you are even from the same forum and country as me!_),  and with your previous project which was even took down from Google Play because of that. 

We are against merging before you fix the issues and then you're free to go. That's all from us, no further comments will be made by us in this topic.

2023-02-03 10:35 UTC, kuba2k2 commented
3 years of research.. on what exactly? I don't get it, I didn't need, nor use, any of your research. And, just to clarify, my other project (Android app) was never taken down from Google Play due to any legal issues, I'm not sure how did you come up with that. **Everything like OBK, LT's name, and most certainly my Android app, is off-topic here.** I don't know why did the now-@ghost user post here, but don't continue this topic. LT's issues page is a much better place to discuss stuff like that. We didn't ask you for your opinion about the name. This matter is not to be continued here. If you have any further questions/statements to add, please do it on the LT's issues page.

2023-02-04 02:33 UTC, digiblur commented
> Following project violates Tuya Inc trademark. The license status is not clear. Legal action will be taken shortly.

could someone please nuke this comment, the one below and including mine from the thread as well like the others from this morning of false info? Thanks!

2023-03-12 19:00 UTC, im-kulikov commented
any updates?

2023-03-28 15:48 UTC, edestecd commented
Recently tried this out and I can not believe how good it is and how well it worked. +1 from me and also willing to help with whatever to get us moving.

2023-03-30 10:36 UTC, im-kulikov commented
> Recently tried this out and I can not believe how good it is and how well it worked. +1 from me and also willing to help with whatever to get us moving.

could you explain how to use it without merging?

2023-03-30 15:38 UTC, kuba2k2 commented
Read this guide:
https://docs.libretuya.ml/docs/projects/esphome/

2023-04-12 20:47 UTC, Bramw2003 commented
SM2135 Support does seem to have some bugs (or I'm just configuring it wrong) but this would be a great addon to esphome! Flashing with cloudconvert was simple and uploading firmware from esphome is just as easy as it is for esp devices. Job well done 👌

2023-04-12 21:04 UTC, Cossid commented
> SM2135 Support does seem to have some bugs (or I'm just configuring it wrong) but this would be a great addon to esphome! Flashing with cloudconvert was simple and uploading firmware from esphome is just as easy as it is for esp devices. Job well done 👌

SM2135 is a bug in ESPHome core, not the LibreTuya port (power levels were hard-coded to low levels that don't even light some devices).  You can get a correction by pulling the pending PR https://github.com/esphome/esphome/pull/3850

2023-04-15 12:40 UTC, camsaway commented
+1 for merge on this PR - I have need to support BL and BK chips.
@kuba2k2 I see two checks are failing before they will look at it.

2023-04-15 22:10 UTC, poldim commented
Saw this in digiblur's video.  Looks like a great addition! Looking forward to when this merges!

2023-04-16 01:34 UTC, TheHomieFox commented
This is working amazingly well, please merge.

2023-04-17 13:54 UTC, Xmister commented
@kuba2k2 Is there a chance to implement ble tracking?

2023-04-17 13:56 UTC, kuba2k2 commented
It isn't planned right now, because the APIs for BLE are way different from ESP32's APIs, and even these are not standardized AFAIK.

2023-04-17 14:01 UTC, Xmister commented
I would imagine that would be a separate component, like `libretuya_ble_tracker`, so API compatibility might not be an issue there. But I understand if it might be too much work for the first milestone.

2023-04-19 13:27 UTC, kwiksilver commented
I have 11 devices running LibreTuya and it would be great if this was merged. It's been rock solid for months for me.

2023-04-23 21:29 UTC, evlo commented
Would this magically work somehow if I add this into external components? I do have only sockets with beken, kinda hard to disassemble if it would brick the device.

2023-04-25 15:39 UTC, rishabmehta7 commented
@kuba2k2 any plans for Home Assistant Bluetooth Proxy? We all have so many Beken Powered AC devices around that can run LibreTuya and they will make an amazing Bluetooth Proxy setup.

2023-04-25 19:08 UTC, digiblur commented
> @kuba2k2 any plans for Home Assistant Bluetooth Proxy? We all have so many Beken Powered AC devices around that can run LibreTuya and they will make an amazing Bluetooth Proxy setup.

Probably long term maybe if it is possible but step one needs to happen first.

2023-04-27 21:55 UTC, TommySharpNZ commented
+1 this would be a great addition!

2023-04-27 23:05 UTC, GM-AZ commented
This would be a great addition to ESPHome

2023-05-10 23:13 UTC, dsduarte commented
also learn about this on digiblur's video... hope this merge comes soon!

2023-05-12 18:20 UTC, urbatecte commented
Learn about this on @digiblur  's video... 
see it in CI/CD !
hope it will be succesfull soon.
thanks foir effort
cheers

2023-05-21 02:38 UTC, hahn23 commented
Tested this on my local build. It worked perfectly. 

A merge would be realy nice!

2023-05-26 09:34 UTC, Kudjo-Grand commented
+1 for merging this. It would be GREAT!

2023-05-30 00:10 UTC, dasb00ter commented
Can somebody clarify the road map for the Beken chips. Will flashing these chips be done from esphome or will there be a separate way. Currently I have the libretiny add-on installed along esphome in Hassos. What is the final plan or what do the developers want to happen here

2023-05-30 04:50 UTC, camsaway commented
As a user I want to treat my BK based devices the same as any ESP based devices within Esphome.

I will look at the add-on (wasn't aware of it) but given the level of integration in this PR I dont see how the add-on could achieve this.

2023-05-30 08:03 UTC, kuba2k2 commented
@dasb00ter @camsaway
The process is the same as for ESP devices. After initially flashing the device via wire (or cloudcutter for BK chips), which also applies for ESP devices, everything can be done via the add-on. It can compile and update firmware, just like on ESP.

2023-05-30 10:04 UTC, rishabmehta7 commented
> @dasb00ter @camsaway The process is the same as for ESP devices. After initially flashing the device via wire (or cloudcutter for BK chips), which also applies for ESP devices, everything can be done via the add-on. It can compile and update firmware, just like on ESP.

But having this merged would make this so much better. Everything in one place!!!

2023-05-30 10:48 UTC, camsaway commented
> > @dasb00ter @camsaway The process is the same as for ESP devices. After initially flashing the device via wire (or cloudcutter for BK chips), which also applies for ESP devices, everything can be done via the add-on. It can compile and update firmware, just like on ESP.
> 
> But having this merged would make this so much better. Everything in one place!!!

Fully agree here. My preference is for this to be merged into core.

2023-05-30 18:00 UTC, dasb00ter commented
> @dasb00ter @camsaway The process is the same as for ESP devices. After initially flashing the device via wire (or cloudcutter for BK chips), which also applies for ESP devices, everything can be done via the add-on. It can compile and update firmware, just like on ESP.

I understand. I guess there are 3 stakeholders here the developer, the user and the maintainers of home assistant (although this could be completely separate from the last). Just want to ask how this is going to pan out BC currently I have 2 add-ons installer. Can the libretuya sddon compiler for esp32 also? I'm just trying to consolidate my devices into one dashboard and it seemed possible

2023-05-30 18:48 UTC, felipecrs commented
@dasb00ter I can tell you that as soon as this PR gets merged and a new version of ESPHome is released, you'll be able to use the official ESPHome add-on for all your devices, including the Tuya-based ones.

2023-05-30 18:48 UTC, felipecrs commented
But @kuba2k2 maybe you can help clarify what's pending from marking this PR as ready, for example.

2023-05-30 21:13 UTC, jesserockz commented
## Status update

I have been talking with @kuba2k2 and have requested changes to be made before it can be merged. They are also a very busy person doing this in spare time, so please have patience =)

Jesse

2023-05-31 05:17 UTC, Monacoslo commented
It should be merged into official ESPhome dev branch. I hope this will happen soon.

I can confirm it works perfectly with Aubess mini switches with and without power monitoring and with very similar switches of other producer.

2023-05-31 07:06 UTC, donburch888 commented
>t **_as soon as_** this PR gets merged

I see that this PR was created 1 year ago ... 

I'm new to Github, so I may have this wrong ... but it looks as though Kuba2k2 has been committing ESPHome updates to LibreTiny, rather than managing to get ahead and work out what changes are needed for ESPHome to accept this PR.  

It feels to me that Paulus and co are interested in custom building their own devices; not in supporting the many off-the-shelf products using the newer tuya modules.

2023-05-31 07:29 UTC, kuba2k2 commented
Let me clarify.

As Jesse said yesterday, we've talked about the changes that need to be done before merging. And I always knew there will be *some* changes needed, so that was what I expected.
To be fair, I'm glad that it didn't get merged earlier - we've just finished a huge refactor, only a month ago. This had some breaking changes (like the project name) so I'm glad we've been waiting to merge this to sort that out.
I'm also trying to keep LT as good as possible, by updating its core repository, not essentially the ESPHome fork. It doesn't even require that much maintenance.

Tl;dr: The changes will be made shortly. I need to find enough time to make them. Then we'll talk about merging and release schedules.

2023-05-31 16:26 UTC, dasb00ter commented
My question only came from the fact that I found an add-on that already seemed to do everything. No question for me on time line just wanted to know the plan if there was one. Thanks all for answering. Thanks @kuba2k2 who patiently helped me get my globe electric light bulbs(Beken) removed from the cloud and flashed with esphome. I wish I could help more but I'm reaching the limit of my technical expertise

2023-07-13 19:34 UTC, kuba2k2 commented
The PR has now been refactored, so that the `libretiny:` block is replaced with a chip family-specific block, like `rtl87xx:` and `bk72xx:`. All users must update their configs accordingly (this will not be reverted to the previous scheme, to comply with naming of other platform components).

Moreover (to the devs):
- pin validation has been added (you can't use pins not present on your board)
- board lists have been added to the "family components"
- D# and A# pin naming has been deprecated (but is still usable for now)
- the "OTA backend error code" feature introduced for debugging has been reverted
- the CLI wizard (and dashboard wizard) haven't been changed yet; I know that the devs requested changes in these areas, so I need directions - do I update it to "still work" with the new family components, or do I remove LT from it completely?
- some libraries (namely AsyncTCP/AsyncWebServer and MQTT) are still linked to my forked versions; when the time comes, I'll make a PR to the base repos so that the standard versions will be used. Note that the changes are not breaking there, it's only about `#ifdefs` for platform compatibility.
- docs are missing; I'd like the main PR to be reviewed first
- tests are missing; it's probably just a matter of adding a few YAMLs

That being said, everything on my side should be ready to review, so I'm marking the PR as such.

2023-07-13 19:40 UTC, felipecrs requested changes

2023-07-13 19:40 UTC, felipecrs commented on docker/ha-addon-rootfs/etc/s6-overlay/s6-rc.d/esphome/run
> +exec esphome dashboard /config/libretuya-esphome --socket /var/run/esphome.sock --ha-addon
This change is only applicable to the fork.

```suggestion
exec esphome dashboard /config/esphome --socket /var/run/esphome.sock --ha-addon
```

2023-07-13 19:40 UTC, felipecrs commented on requirements.txt
> +libretiny-esphome-dashboard
This too, I guess.

2023-07-13 20:00 UTC, kuba2k2 commented on docker/ha-addon-rootfs/etc/s6-overlay/s6-rc.d/esphome/run
> +exec esphome dashboard /config/libretuya-esphome --socket /var/run/esphome.sock --ha-addon
Correct, but changing it now will break it for users, until the merge happens. This will be reverted prior to merging (along with other changes described in https://github.com/esphome/esphome/pull/3509#issuecomment-1634801150).

2023-07-13 20:03 UTC, felipecrs commented on docker/ha-addon-rootfs/etc/s6-overlay/s6-rc.d/esphome/run
> +exec esphome dashboard /config/libretuya-esphome --socket /var/run/esphome.sock --ha-addon
Got it. Maybe we should separate the branches then, one for this PR, and another one for the fork itself.

Anyway, do whatever you prefer, I was just making sure you noticed it. :)

2023-08-02 07:16 UTC, vxav commented
Are there any news on merging this PR? This would be amazing for ESPHome

2023-08-19 20:47 UTC, tannisroot commented
Hi, could you enable issues for your fork of esphome, so that issues could be reported there? There is one minor visual one in the addon (all devices always show up as offline despite being connectable) and some MDNS shenanigans.

2023-08-20 08:21 UTC, kuba2k2 commented
You can report issues in the main LibreTiny repo. The devices showing up as offline is due to ping problems, and apply to standard ESPHome as well, afaik.

2023-08-21 00:53 UTC, jesserockz commented on docker/ha-addon-rootfs/etc/s6-overlay/s6-rc.d/esphome/run
> +exec esphome dashboard /config/libretuya-esphome --socket /var/run/esphome.sock --ha-addon
We need to leave this unresolved then otherwise it might be missed before the final merge.

2023-08-21 04:07 UTC, jesserockz requested changes
Apologies for the delay.

One main thing I keep coming back to while reviewing the code is that the platforms being passed around everywhere should be `rtl87xx` / `bk72xx` not `libretiny` because the `libretiny` component is autoloaded by those two.

Also there is a lot of `|| defined(USE_LIBRETINY)` inside files dedicated to esp8266 or esp32 etc which makes it really confusing to know exactly where the code if later if/when we go to make changes. I think if there is an existing split of files for platforms, then libretiny should have its own split too.

I have probably not reviewed every file due to changed required and files will need to be looked at again.

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/api/api_connection.cpp
> +  resp.manufacturer = "LibreTiny";
This is the manufacturer, not the firmware developer... 
It should be `Realtek` or `Beken` etc...

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/debug/debug_component.cpp
>    return ESP.getFreeHeap();  // NOLINT(readability-static-accessed-through-instance)
Why does LibreTiny expose ESP as a global when it has nothing to do with Espressif?
Why doesnt this code use `lt_heap_get_free()`?

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/debug/debug_component.cpp
>      this->block_sensor_->publish_state(ESP.getMaxFreeBlockSize());
Same here?

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/ledc/ledc_output_libretiny.cpp
I feel like libretiny should have its own platform for pwm to keep it separate, esp32 uses `ledc` because that is the actual name of the hardware peripheral...

2023-08-21 04:07 UTC, jesserockz commented on esphome/wizard.py
> +            platform = "LIBRETINY"
This should actually be explicit for all cases and raise an error on else (unknown platform)

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/mdns/mdns_component.cpp
> +    platform = "LibreTiny";
As per the main comment above, this really should be something like:
```suggestion
#ifdef USE_RTL87XX
    platform = "RTL87XX";
#endif
#ifdef USE_BK72XX
    platform = "BK72XX";
```

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/mdns/mdns_rp2040.cpp
Please make a new file for libretiny.

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/mqtt/__init__.py
> +        )
#4759 changes this library to another fork we will be using going forward, please PR your changes there

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/mqtt/mqtt_backend_esp8266.h
This file was recently renamed from `_arduino` to `esp8266` but perhaps we should rename it back.

Thoughts @HeMan ?

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/ota/__init__.py
> +            CONF_PORT, esp8266=8266, esp32=3232, rp2040=2040, libretiny=8892
Should we use a number that doesn't represent `TUYA`?

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/ota/ota_backend_arduino_esp32.cpp
> +#endif
This is probably a pretty important feature to not be implemented yet?

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/ota/ota_backend_arduino_esp32.cpp
I think please make a new file for libretiny. Its duplicate yes, but its easier to make changes per platform if need be.

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/uart/uart_component_libretiny.cpp
> +  }
The fake `if(false)` is not needed if written like this and should also mark the component as failed before the `return`

```suggestion
#if LT_HW_UART0
  if ((tx_pin == -1 || tx_pin == PIN_SERIAL0_TX) && (rx_pin == -1 || rx_pin == PIN_SERIAL0_RX)) {
    this->serial_ = &Serial0;
    this->hardware_idx_ = 0;
  } else
#endif
#if LT_HW_UART1
  if ((tx_pin == -1 || tx_pin == PIN_SERIAL1_TX) && (rx_pin == -1 || rx_pin == PIN_SERIAL1_RX)) {
    this->serial_ = &Serial1;
    this->hardware_idx_ = 1;
  } else
#endif
#if LT_HW_UART2
  if ((tx_pin == -1 || tx_pin == PIN_SERIAL2_TX) && (rx_pin == -1 || rx_pin == PIN_SERIAL2_RX)) {
    this->serial_ = &Serial2;
    this->hardware_idx_ = 2;
  } else
#endif
  {
#if LT_ARD_HAS_SOFTSERIAL
    this->serial_ = new SoftwareSerial(rx_pin, tx_pin, rx_inverted || tx_inverted);
#else
    this->serial_ = &Serial;
    ESP_LOGE(TAG, "  SoftwareSerial is not implemented for this chip. Only hardware pins are supported:");
#if LT_HW_UART0
    ESP_LOGE(TAG, "    TX=%u, RX=%u", PIN_SERIAL0_TX, PIN_SERIAL0_RX);
#endif
#if LT_HW_UART1
    ESP_LOGE(TAG, "    TX=%u, RX=%u", PIN_SERIAL1_TX, PIN_SERIAL1_RX);
#endif
#if LT_HW_UART2
    ESP_LOGE(TAG, "    TX=%u, RX=%u", PIN_SERIAL2_TX, PIN_SERIAL2_RX);
#endif
    this->mark_failed();
    return;
#endif
  }
```

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/web_server_base/__init__.py
> +        )
Can you PR the renames into the main repo?

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/wifi/wifi_component_libretiny.cpp
> +#endif  // USE_ESP32_FRAMEWORK_ARDUINO
```suggestion
#endif  // USE_LIBRETINY
```

2023-08-21 04:07 UTC, jesserockz commented on esphome/const.py
> +    PLATFORM_LIBRETINY,
This list of platforms is used to make sure users have one of them in config, I dont think this should be here as a user needs to define one of the meta platforms.
```suggestion
```

2023-08-21 04:07 UTC, jesserockz commented on esphome/core/config.py
> +#ifndef USE_LIBRETINY
I think it would be better to just not execute the `add_arduino_global_workaround` if its libretiny...

2023-08-21 04:07 UTC, jesserockz commented on esphome/dashboard/dashboard.py
> +
The dashboard should be asking for `rtl87xx` or `bk72xx` boards which allows the code to be the same as below.

2023-08-21 04:07 UTC, jesserockz commented on esphome/util.py
Can you move these changes into their own pr?

2023-08-21 04:07 UTC, jesserockz commented on esphome/components/libretiny/lt_component.cpp
> +void LTComponent::update() {}
No need to override these when they are not even used?

2023-08-21 06:11 UTC, HeMan commented on esphome/components/mqtt/mqtt_backend_esp8266.h
Yes, since it is another port that uses Arduino it could be renamed.

2023-08-21 06:15 UTC, HeMan commented on esphome/components/mqtt/__init__.py
> +        )
If you do a PR against https://github.com/HeMan/async-mqtt-client I could push a new release to platformio registry.

2023-08-21 06:21 UTC, Monacoslo commented
Now I am confused. Will libretiny be now included in dev version of esphome or not?

2023-08-21 06:28 UTC, kbx81 commented
> Now I am confused. Will libretiny be now included in dev version of esphome or not?

Not just yet @Monacoslo; Jesse has left some feedback & change requests to help ensure the code is a good fit architecturally. It's part of the review process. Some changes will be made here, some perhaps broken out into other PRs, etc. but in time this will likely become a part of ESPHome -- just not quite yet. 😄

2023-08-21 10:00 UTC, kuba2k2 commented on esphome/components/ledc/ledc_output_libretiny.cpp
Regarding the PWM component, if I make it separate for LT, there will be *four* PWM components:
- `ledc`
- `esp8266_pwm`
- `rp2040_pwm`
- `libretiny_pwm` (?) or `bk72xx_pwm`+`rtl87xx_pwm`

...all of which share nearly the same options and schema (id, pin, frequency + channel for ledc).

What prevents them from being merged together into a single `pwm` component?

I believe this could be simplified this way. The old components would be kept as "deprecated" not to break users' configs, instead let them migrate slowly.

2023-08-21 10:03 UTC, kuba2k2 commented on esphome/components/mqtt/mqtt_backend_esp8266.h
(answering https://github.com/esphome/esphome/pull/3509#discussion_r1299492672, https://github.com/esphome/esphome/pull/3509#discussion_r1299502394 and this comment)

About file naming for components with per-platform implementations:
few components have `_arduino_esp32.h` implementations, while they don't use any esp32-specific parts.

Same code could be used for LibreTiny (as it is done now with `USE_LIBRETINY` which makes it confusing), and possibly even RP2040.

Such components are, for instance:
- `ota` having esp32, esp8266 and rp2040 arduino impls, all identical or very similar
- `remote_receiver` and `remote_transmitter` having esp32 (RMT) impl and esp8266 (arduino generic) impl -> could be renamed instead of adding another LT impl
- `mdns` having nearly identical esp8266 and rp2040 impls -> could be merged and renamed
- `mqtt` having esp8266 impl, recently renamed from `arduino` -> could be renamed back (as per the comment) since it uses the same library anyways

and probably a few more that I didn't use yet.

Of course, components like `wifi` or `uart` (which have totally different code on all platforms) should be kept in separate units, like it is done now.

That being said, there are components such as `adc` which have *all platforms* in a *single file*,
making it hard to read since multiple different implementations are together in one file
(esp32 idf ADC / esp8266 and libretiny Arduino Analog / RP2040 sdk ADC)

2023-08-21 10:06 UTC, kuba2k2 commented on esphome/components/ota/__init__.py
> +            CONF_PORT, esp8266=8266, esp32=3232, rp2040=2040, libretiny=8892
Changing this number would make it very hard (if not impossible) to apply OTA updates for all existing users (migrate to pre-release LT to esphome upstream). Besides, it's just a number, nobody has to know what it means :smile: 

But, if you need to have this changed, I can use a different port number.

2023-08-21 10:09 UTC, kuba2k2 commented on esphome/dashboard/dashboard.py
> +
The whole dashboard/wizard situation wasn't resolved yet, as far as I remember. On discord, we have settled to remove LT from the dashboard completely, quoting:

> We don't see much point in trying to create configs from scratch from the wizard as you are almost certainly going to be flashing a device from a known config that already implements all the required parts for that device.

Should I keep the dashboard compatibility then? Or should I remove libretiny from the dashboard?

2023-08-21 10:16 UTC, kuba2k2 commented
> One main thing I keep coming back to while reviewing the code is that the platforms being passed around everywhere should be `rtl87xx` / `bk72xx` not `libretiny` because the `libretiny` component is autoloaded by those two.

On Discord, I have pointed out a few drawbacks from referencing chip components everywhere:
> [...] things like "split defaults" and CORE.target_platform checking will need to have every LT chip available, like:
> `if CORE.target_platform in (PLATFORM_LIBRETINY):`
> will need to be
> `if CORE.target_platform in (PLATFORM_BK72XX, PLATFORM_RTL87XX, PLATFORM_...):`

> or
> ```
> cv.SplitDefault(
>            CONF_IMPLEMENTATION,
>            esp8266=IMPLEMENTATION_LWIP_TCP,
>            esp32=IMPLEMENTATION_BSD_SOCKETS,
>            rp2040=IMPLEMENTATION_LWIP_TCP,
>            libretiny=IMPLEMENTATION_LWIP_SOCKETS, # all chips have to be specified?
>            host=IMPLEMENTATION_BSD_SOCKETS,
> ):
> ```

> what about USE_* macros in C?
> the chip sets will *always* be the same in all three places (`CORE.target_platform`, `cv.SplitDefault` and `USE_*`)
> I don't think it makes much sense duplicating that, it might make the code less readable and longer
> my solution would still abstract away the "libretiny" part from users
> which matches with what they're used to - typing the chip name in yaml 
> it should be easier to maintain as well

2023-08-21 14:45 UTC, kuba2k2 commented on esphome/components/uart/uart_component_libretiny.cpp
> +  }
I didn't know I have to mark it as failed.

As for the fake if(false), it gets formatted incorrectly otherwise:
![obraz](https://github.com/esphome/esphome/assets/30433568/a8ba9065-6028-46d8-8f0b-046862830af9)
(extra indent on subsequent if's)

2023-08-21 16:11 UTC, kuba2k2 commented on esphome/const.py
> +    PLATFORM_LIBRETINY,
Now the libretiny platform is only kept for compatibility with older configs, so that an error will be displayed, asking the user to migrate:
![obraz](https://github.com/esphome/esphome/assets/30433568/ffa4f7fa-3560-4b33-91d6-a7055f719ca2)
Putting the validation in config.py instead produces config parse errors; I don't know how to make it work better.

2023-08-21 16:14 UTC, kuba2k2 commented
Re https://github.com/esphome/esphome/pull/3509#issuecomment-1686050232:
I've decided to make the code use family-components instead, as Jesse suggested (`CORE.target_platform` is NOT `libretiny` now). However, I kept `USE_LIBRETINY` (and `USE_BK72XX`, `USE_RTL87XX`) as well as `CORE.is_libretiny` (and `CORE.is_bk72xx`, `CORE.is_rtl87xx`). These are just shorthands for not having to list all platforms in every piece of code compatible with each LibreTiny family.

2023-08-21 20:07 UTC, jesserockz commented on esphome/components/ledc/ledc_output_libretiny.cpp
I think the point of it though is that they represent the hardware doing the pwm. Whereas you can have an external chip such as `pca9685`.
So technically `ledc` should really be named `esp32_ledc` but that's not something that should hold up this PR. 
I am happy to look at this again later after this PR is merged in.

2023-08-21 20:20 UTC, jesserockz commented on esphome/components/mqtt/mqtt_backend_esp8266.h
Yes `adc` is a bit of a mess and actually should be split out.

`rp2040` like `libretiny` is very similar to esp8266 as I think thats what they based the arduino core on. 

I am happy for things to be renamed to generic `_arduino.h/cpp` if they are shared and almost identical.

Where possible, I do try to use the native sdk functions (from `esp-idf` / `pico-sdk`) instead of the arduino abstractions.

I think for this PR, make the separate files so we know exactly what is being added and we can change the files around in a further PR as that is not exposed to users.

2023-08-21 20:21 UTC, jesserockz commented on esphome/components/ota/__init__.py
> +            CONF_PORT, esp8266=8266, esp32=3232, rp2040=2040, libretiny=8892
Ok, I am fine with leaving it.

2023-08-21 20:22 UTC, jesserockz commented on esphome/dashboard/dashboard.py
> +
Yes lets remove it for now and we can revisit it later if need be.

2023-08-23 09:30 UTC, catalin2402 commented on docker/ha-addon-rootfs/etc/s6-overlay/s6-rc.d/esphome/run
> +exec esphome dashboard /config/libretuya-esphome --socket /var/run/esphome.sock --ha-addon
This is fixed now.

2023-08-23 09:31 UTC, catalin2402 commented on esphome/components/mqtt/__init__.py
> +        )
I reverted the mqtt files because it's not stable on libretiny

2023-08-23 09:32 UTC, catalin2402 commented on esphome/components/mdns/mdns_rp2040.cpp
Done, now mdns has it's own file

2023-08-23 09:33 UTC, catalin2402 commented on esphome/components/ota/ota_backend_arduino_esp32.cpp
Fixed, ota_backend_arduino_libretiny created

2023-08-23 09:33 UTC, kuba2k2 commented on esphome/components/mqtt/mqtt_backend_esp8266.h
We'll leave the arduino merging for a separate PR then. Separate units will be added in this PR.

2023-08-23 09:34 UTC, kuba2k2 commented on esphome/components/mqtt/__init__.py
> +        )
We decided to disable MQTT on LibreTiny (config-time validation) because it wasn't usable anyway. The mqtt component changes have been reverted for now.

2023-08-23 09:41 UTC, kuba2k2 commented
Note:
The PR is now tracking [libretiny-eu/libretiny-esphome](https://github.com/libretiny-eu/libretiny-esphome) instead of [kuba2k2/libretiny-esphome](https://github.com/libretiny-eu/libretiny-esphome).
The repo fork on my personal account is the one used with unofficial Docker containers.
The organization repo (this PR) might be **not usable** as it depends on ESPHome libraries, instead of LibreTiny forks with fixes.

Your local repos and HA installations will not be affected. Just don't pull the [libretiny-eu/libretiny-esphome](https://github.com/libretiny-eu/libretiny-esphome) repo if you're not planning on developing ESPHome.

2023-08-29 11:12 UTC, kuba2k2 commented on esphome/components/web_server_base/__init__.py
> +        )
PRs submitted:
https://github.com/esphome/AsyncTCP/pull/4
https://github.com/esphome/ESPAsyncWebServer/pull/23

2023-08-29 11:14 UTC, kuba2k2 commented on esphome/dashboard/dashboard.py
> +
No action needs to be taken; the LibreTiny part in Dashboard is only in the fork, there's no PR submitted.

However, merging this is important: https://github.com/esphome/dashboard/pull/469

2023-08-29 11:16 UTC, kuba2k2 commented on esphome/components/ledc/ledc_output_libretiny.cpp
PWM component has been split and removed from ledc.

2023-08-29 11:18 UTC, kuba2k2 commented on esphome/components/mqtt/mqtt_backend_esp8266.h
Code has been refactored and is no longer keeping LibreTiny code in ESP32 units.

2023-08-29 11:48 UTC, kuba2k2 commented on esphome/util.py
Moved to https://github.com/esphome/esphome/pull/5313

2023-08-29 17:26 UTC, kuba2k2 commented on esphome/components/ota/ota_backend_arduino_esp32.cpp
> +#endif
Fixed: implemented on LT side and tested.

2023-09-02 12:21 UTC, kuba2k2 commented
A draft pull request for docs has been created: https://github.com/esphome/esphome-docs/pull/3159

2023-09-02 14:22 UTC, kuba2k2 commented
A quick TODO of things to do before merging:
- merge esphome/ESPAsyncWebServer#23, release new version
- bump in esphome/esphome#3509
- merge esphome/dashboard#469
- merge esphome/esphome-docs#3159

2023-09-04 22:13 UTC, jesserockz approved these changes

2023-09-04 22:16 UTC, merged

2023-09-04 22:21 UTC, felipecrs commented
Wow!

2023-09-04 22:25 UTC, digiblur commented
Nice job to all! The process for many users just got easier again!