Add sum type to binary_sensor_map
OttoWinter/esphomeyaml pull request #3541
Opened 2022-06-09 14:37 UTC by fbrthld

# What does this implement/fix?

This adds the "sum" type to the binary_sensor_map in order to allow for addition of different values based on binary sensors. This enables usage of chips like the [CD4040](https://www.ti.com/lit/ds/symlink/cd4040b.pdf?HQS=dis-mous-null-mousermode-dsf-pf-null-wwe&ts=1654730631019&ref_url=https%253A%252F%252Fwww.mouser.com%252F).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2123

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

sensor:
  - platform: binary_sensor_map
    id: group_0
    name: 'Group Map 0'
    type: sum
    channels:
      - binary_sensor: bit0
        value: 1
      - binary_sensor: bit1
        value: 2
      - binary_sensor: bit2
        value: 4
      - binary_sensor: bit3
        value: 8

binary_sensor:
  - platform: gpio
    pin: 4
    id: bit0

  - platform: gpio
    pin: 5
    id: bit1

  - platform: gpio
    pin: 6
    id: bit2

  - platform: gpio
    pin: 7
    id: bit3
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-08-18 23:51 UTC, jesserockz requested changes

2022-08-18 23:51 UTC, jesserockz commented on esphome/components/binary_sensor_map/sensor.py
> +    "sum": SensorMapType.BINARY_SENSOR_MAP_TYPE_SUM,
Please make `"sum"` a const variable

2022-08-26 08:27 UTC, fbrthld commented
sorry to everyone that got notified... i messed up my commit

2022-08-31 04:50 UTC, jesserockz approved these changes

2022-08-31 04:52 UTC, merged