Max6956 support added
OttoWinter/esphomeyaml pull request #3570
Opened 2022-06-16 13:47 UTC by looping40

# What does this implement/fix?

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-08-01 23:01 UTC, DrunkPyromaniac requested changes
I think it looks good, except for the perhaps-missing action, and the one comment about setting the global current settings.

2022-08-01 23:01 UTC, GregJArnold commented on esphome/components/max6956/__init__.py
> +)
Should there also be an automation to set the brightness mode to global or individual?

2022-08-01 23:01 UTC, DrunkPyromaniac commented on esphome/components/max6956/automation.h
> +  void play(Ts... x) override { this->max6956_->set_brightness_global(16 * this->brightness_global_.value(x...)); }
I could be mistaken, but I think that this just sets the class variable, but doesn't actually write it out to the I²C bus.

2022-09-01 18:07 UTC, looping40 commented on esphome/components/max6956/__init__.py
> +)
I implemented this modification, but I can't commit : it seems I should not be on the dev branch.
How can I solve this ?

2022-09-02 13:35 UTC, looping40 commented
I created the PR using a Dev branch so I could not commit the changes required by the review.
The only way to fix this seems  to close this PR and create a new one, on a dedicated branch:
https://github.com/esphome/esphome/pull/3764

2022-09-02 13:35 UTC, closed without merging