Add GC9A01 round TFT display
OttoWinter/esphomeyaml pull request #3625
Opened 2022-07-08 10:10 UTC by 4cello

# What does this implement/fix?

Add display platform for GC9A01 240x240 TFT LCD.
Tested with ESP32 and ESP8266. (ESP8266 only with reduced display size because of frame buffer size)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** -

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> (follows)

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
spi:
  mosi_pin: GPIO32
  clk_pin: GPIO27

display:
- platform: gc9a01
  reset_pin: GPIO26
  cs_pin: GPIO25
  dc_pin: GPIO33
  rotation: 180
  lambda: |-
    it.print(0, 120, id(font), "Hello World!");
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-07-26 06:50 UTC, firepinn commented
This doesn't seem to work for the Waveshare 1.8" round display which is IPS

2022-07-26 07:11 UTC, 4cello commented
do you mean 1.28"? The only Waveshare 1.8" display is not round.
I'll look into the code nevertheless, but I don't own that display and I'm not sure how easily I can buy it for a reasonable price.

2022-07-26 08:22 UTC, firepinn commented
I actually managed to get it to work. Sorry for the confusion.

2022-07-26 15:15 UTC, velkrosmaak commented
> I actually managed to get it to work. Sorry for the confusion.

Can you please share the yaml you used to get this display working?

2022-09-29 12:36 UTC, pvh0 commented
> > I actually managed to get it to work. Sorry for the confusion.
> 
> Can you please share the yaml you used to get this display working?

Probably something like:

```
external_components:
  - source: github://pr#3625
    components: [ gc9a01 ]

spi:
  mosi_pin: GPIO13
  clk_pin: GPIO14

display:
- platform: gc9a01
  reset_pin: GPIO26
  cs_pin: GPIO15
  dc_pin: GPIO33
  rotation: 180
  lambda: |-
      it.line(0, 0, 100, 50);

Probably something like:


```

2022-10-08 22:09 UTC, sam632 commented
I'm getting this error when trying to install with the above YAML. Not 100% sure how esphome works in the background, any help would be appreciated. 

```
In file included from src/esphome/components/gc9a01/gc9a01.cpp:1:0:
src/esphome/components/gc9a01/gc9a01.h:29:12: error: 'DisplayType' in namespace 'esphome::display' does not name a type
   display::DisplayType get_display_type() override { return display::DisplayType::DISPLAY_TYPE_COLOR; }
```

2022-12-10 11:14 UTC, bigmoby commented
> I'm getting this error when trying to install with the above YAML. Not 100% sure how esphome works in the background, any help would be appreciated.
> 
> ```
> In file included from src/esphome/components/gc9a01/gc9a01.cpp:1:0:
> src/esphome/components/gc9a01/gc9a01.h:29:12: error: 'DisplayType' in namespace 'esphome::display' does not name a type
>    display::DisplayType get_display_type() override { return display::DisplayType::DISPLAY_TYPE_COLOR; }
> ```

@sam632 please you could have a try with:

```
external_components:
  - source: github://4cello/esphome@gc9a01
    components: ["gc9a01"]
```

2022-12-10 21:47 UTC, sam632 commented
> > I'm getting this error when trying to install with the above YAML. Not 100% sure how esphome works in the background, any help would be appreciated.
> > ```
> > In file included from src/esphome/components/gc9a01/gc9a01.cpp:1:0:
> > src/esphome/components/gc9a01/gc9a01.h:29:12: error: 'DisplayType' in namespace 'esphome::display' does not name a type
> >    display::DisplayType get_display_type() override { return display::DisplayType::DISPLAY_TYPE_COLOR; }
> > ```
> 
> @sam632 please you could have a try with:
> 
> ```
> external_components:
>   - source: github://4cello/esphome@gc9a01
>     components: ["gc9a01"]
> ```

This didn't work unfortunately. What's the best way to debug this issue?

2023-03-11 03:31 UTC, filmkorn commented
I'd love to see this implemented as these displays are fairly cheap and widely available. How could I help with this PR without having any language knowledge?

2023-03-28 05:05 UTC, pkejval commented
Why is this stale? I'm using this PR component and works without any problems.

2023-03-28 06:03 UTC, bigmoby commented
Hi @pkejval yes it works, it should be maintained aligned with dev branch (there are some conflicts).

2023-05-03 15:52 UTC, jbishop129 commented
I've been working with this external component (Thanks @4cello !!!), and it works quite well. The only issue I've had so far is I cannot get it to drive two of these displays from one ESP32; you just use separate `CS` pins. Shouldn't be an issue, as there's several "animated eyes" projects out there in the wild [such as this one](https://dronebotworkshop.com/gc9a01/), but it seems in ESPHome, adding a second instance of the `display` results in the last one in my code being the only one that works, the first one stops working. I dug through @4cello 's [code](https://github.com/4cello/esphome/tree/gc9a01/esphome/components/gc9a01) to see if I could find a setting, but I didn't see anything. 

Here's a basic Hello World example of what I'm troubleshooting with, trimmed down as much as possible to test with. Any thoughts?

``` c++
esphome:
  name: "round-display"
  friendly_name: ESP32 Round Display

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: [redacted]

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    ssid: "Esphome-Round-Display"
    password: !secret ap

captive_portal:
    
external_components:
  - source: github://4cello/esphome@gc9a01
    components: ["gc9a01"]

spi:
  mosi_pin: GPIO23
  clk_pin: GPIO18

font:
  - file: 'fonts/Google_Sans_Regular.ttf'
    id: font_16
    size: 16

time:
  - platform: sntp
    id: my_time

display:
## First display <-- Nothing displays, when Second Display is configured. Works fine if comment out Second Display
  - platform: gc9a01
    id: roundOLED1
    reset_pin: GPIO26
    cs_pin: GPIO5
    dc_pin: GPIO25
    rotation: 90
    lambda: |-
      it.strftime(120,80, id(font_16), TextAlign::CENTER, "%A %b %w", id(my_time).now());

## Second display <-- Displays dateTime data as expected.
  - platform: gc9a01
    id: roundOLED2
    reset_pin: GPIO26
    cs_pin: GPIO15
    dc_pin: GPIO25
    rotation: 90
    lambda: |-
      it.strftime(120,80, id(font_16), TextAlign::CENTER, "%A %b %w", id(my_time).now());
```

2023-06-01 20:16 UTC, lboue commented
Could you merge this PR with the dev branch? This has been tested by several people and works.

![GC9A01_1 28inch_s](https://github.com/esphome/esphome/assets/938089/e859dd27-5863-458a-8b68-3a4e5b17f4d6)

2023-06-09 21:21 UTC, ayufan commented on esphome/components/gc9a01/gc9a01.cpp
> +    for (size_t line = 0; line < this->get_buffer_length(); line = line + this->get_width_internal()) {
This loop is extreamly slow. Sending pixel data on 40MHz SPI takes 30ms, but this loop for 240x240 on ESP32S3 (160MHz clock) takes ~200ms.

2023-06-09 21:27 UTC, ayufan commented on esphome/components/gc9a01/gc9a01.h
> +                                     spi::DATA_RATE_8MHZ> {
I'm able to use `DATA_RATE_40MHZ`.

2023-06-10 15:49 UTC, jbishop129 commented on esphome/components/gc9a01/gc9a01.cpp
> +    for (size_t line = 0; line < this->get_buffer_length(); line = line + this->get_width_internal()) {
I noticed this too specifically on the ESP32S3, other variants seem normal refresh speed

2023-06-10 15:50 UTC, ayufan commented on esphome/components/gc9a01/gc9a01.cpp
> +    for (size_t line = 0; line < this->get_buffer_length(); line = line + this->get_width_internal()) {
With 40MHz and using 16bit refresh takes roughly ~30ms for the 240x240 on esp32s3.

2023-07-23 20:57 UTC, tiimsvk commented
hi, esphome gives me this error when compiling using an external component.  Is there any solution?  Well thank you.
`Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 1017, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 1004, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphome/esphome/__main__.py", line 435, in command_run
    exit_code = write_cpp(config)
  File "/esphome/esphome/__main__.py", line 185, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 197, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 626, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 177, in wrapped
    await coro(conf)
  File "/config/esphome/.esphome/external_components/1ffebe30/esphome/components/gc9a01/display.py", line 77, in to_code
    await setup_gc9a01(var, config)
  File "/config/esphome/.esphome/external_components/1ffebe30/esphome/components/gc9a01/display.py", line 63, in setup_gc9a01
    config[CONF_LAMBDA], [(display.DisplayBufferRef, "it")], return_type=cg.void
AttributeError: module 'esphome.components.display' has no attribute 'DisplayBufferRef'
`

Esphome yaml:
`external_components:
  - source: github://4cello/esphome@gc9a01
    components: ["gc9a01"]

spi:
  mosi_pin: GPIO13
  clk_pin: GPIO14

display:
- platform: gc9a01
  reset_pin: GPIO26
  cs_pin: GPIO15
  dc_pin: GPIO33
  rotation: 180
  lambda: |-
      it.line(0, 0, 100, 50);
`

2023-07-23 20:57 UTC, tiimsvk commented
hi, esphome gives me this error when compiling using an external component.  Is there any solution?  Well thank you.
`Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 1017, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 1004, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphome/esphome/__main__.py", line 435, in command_run
    exit_code = write_cpp(config)
  File "/esphome/esphome/__main__.py", line 185, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 197, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 626, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 177, in wrapped
    await coro(conf)
  File "/config/esphome/.esphome/external_components/1ffebe30/esphome/components/gc9a01/display.py", line 77, in to_code
    await setup_gc9a01(var, config)
  File "/config/esphome/.esphome/external_components/1ffebe30/esphome/components/gc9a01/display.py", line 63, in setup_gc9a01
    config[CONF_LAMBDA], [(display.DisplayBufferRef, "it")], return_type=cg.void
AttributeError: module 'esphome.components.display' has no attribute 'DisplayBufferRef'
`

Esphome yaml:
`external_components:
  - source: github://4cello/esphome@gc9a01
    components: ["gc9a01"]

spi:
  mosi_pin: GPIO13
  clk_pin: GPIO14

display:
- platform: gc9a01
  reset_pin: GPIO26
  cs_pin: GPIO15
  dc_pin: GPIO33
  rotation: 180
  lambda: |-
      it.line(0, 0, 100, 50);
`

2023-07-26 14:15 UTC, wildblue commented
It's 5 months now. When will this get merged?
Anybody?

2023-07-26 18:50 UTC, nielsnl68 requested changes
Hi, from my quick view of this new display, i belief it is almost the same as the ili9xxx component's,  is it not?

When so, then i recommend you to merge this PR onto the ili9xxx component. This will make it much easier to maintain and update the displays when needed in the near future.

I know the current component name does not match correctly yet but i will make the change soon. (When i have troughed about the right one to use).  

Anyway thanks for sharing your work.

2023-07-26 18:55 UTC, nielsnl68 requested changes

2023-07-26 18:55 UTC, nielsnl68 commented on esphome/components/gc9a01/gc9a01.cpp
> +  ESP_LOGD(TAG, "  END");
``` suggestions
```

This will be done automatically.

2023-08-05 04:02 UTC, wildblue commented on esphome/components/gc9a01/gc9a01.cpp
> +  ESP_LOGD(TAG, "  END");
It is time to merge, now! Have you Seen the awesome devices that are Sold on AliExpress for about 20 bucks? I ordered one and it is a complete ready to integrate solution. A small plastic Case with everything INSIDE, exept a battery. It has outside accessible Ports for io and Power, as Well as 3 Buttons.

I Imagine, Putting this outside of any device i want to modify, to have a sweet User Interface. When more Units of there will be Sold, there will be a demand for an easy Implementation into esphome and you will get These requests frontal thrown at you, all at once.

There is a Driver, it was implemented into esphome and Just needs to be merged. And there are other much less polished components INSIDE esphome right now, so please don't wait any longer.

If there are issues with the Implementation, they can be fixed INSIDE the esphome repository, otherwise development gets stuck again for over half a year, because noone is contributing to a tiny repository with an Idea and solution that gets nowhere.

Start the Merger, full thrust ahead.. !

2023-08-09 02:39 UTC, mcmanigle commented on esphome/components/gc9a01/gc9a01.cpp
> +    for (size_t line = 0; line < this->get_buffer_length(); line = line + this->get_width_internal()) {
For me (using esp32s3) setting `eight_bit_color: false` in yaml configuration results in a broken image.

2023-08-09 07:10 UTC, nielsnl68 commented on esphome/components/gc9a01/gc9a01.cpp
> +    for (size_t line = 0; line < this->get_buffer_length(); line = line + this->get_width_internal()) {
@mcmanigle can you add an photo from your broken image on your display?

2023-08-09 10:51 UTC, mcmanigle commented on esphome/components/gc9a01/gc9a01.cpp
> +    for (size_t line = 0; line < this->get_buffer_length(); line = line + this->get_width_internal()) {
Issue is here: https://imgur.com/a/CKaTwWo

It obviously also overflows memory or otherwise breaks things somehow -- note the sensors aren't reading right; wifi connectivity is non-existent, etc in the `eight_bit_color: false` version (everything else stays the same compared to version on the left).

I assumed it was crashing the ESP entirely (I usually use wifi logs etc), but when plugged in, see that it does pass messages from the display component. Also note the central RGB circles (added for debugging) change color; looks like wrong bits written.

My display code is [here](https://github.com/mcmanigle/esphome-components/tree/main/components/gc9a01); it uses `DATA_RATE_40MHZ` and changes DisplayBufferRef to DisplayRef but no other changes.

For reference, on this esp32s2 (specifically [this one](https://www.sparkfun.com/products/17743); note in my earlier post I mentioned s3, but I was wrong; it's an s2), with eight_bit_display: false, the logger complains the display update takes 160ms. With eight_bit_display on (default), it says it takes 260ms.

2023-09-25 16:52 UTC, vilhalmer commented
I've been doing some work on this display to get the touchscreen on the [Makerfabs](https://wiki.makerfabs.com/ESP32_S3_Round_SPI_1.28_TFT_with_Touch.html) unit working as well and discovered that with this initialization procedure, the rotation of the display doesn't match up with the touchscreen or with any of the example code/screenshots provided for that board. Those examples use TFT_eSPI.

I found that the procedure differs from [the implementation used in TFT_eSPI](https://github.com/Bodmer/TFT_eSPI/blob/master/TFT_Drivers/GC9A01_Init.h) in only one spot:
```
diff --git a/esphome/components/gc9a01/gc9a01.cpp b/esphome/components/gc9a01/gc9a01.cpp
index f069ae64..798da0c9 100644
--- a/esphome/components/gc9a01/gc9a01.cpp
+++ b/esphome/components/gc9a01/gc9a01.cpp
@@ -35,8 +35,7 @@ static const uint8_t PROGMEM INITCMD[] = {
   0x8D, 1, 0x01,
   0x8E, 1, 0xFF,
   0x8F, 1, 0xFF,
-  0xB6, 2, 0x00, 0x00,
-  GC9A01_MADCTL, 1, MADCTL_MX | MADCTL_BGR,
+  GC9A011_DFUNCTR, 2, 0x00, 0x00,
   GC9A01_PIXFMT, 1, 0x05,
   0x90, 4, 0x08, 0x08, 0x08, 0x08,
   0xBD, 1, 0x06,
@@ -66,6 +65,11 @@ static const uint8_t PROGMEM INITCMD[] = {
   0x67, 10, 0x00, 0x3C, 0x00, 0x00, 0x00, 0x01, 0x54, 0x10, 0x32, 0x98,
   0x74, 7, 0x10, 0x85, 0x80, 0x00, 0x00, 0x4E, 0x00,
   0x98, 2, 0x3e, 0x07,
+  // Set correct default rotation, must be late. Without doing this the display
+  // seems to initialize to an undefined rotation, but calling this even with
+  // zero will "fix" it. It's then mirrored, so we pass MADCTL_MX here to
+  // un-flip it.
+  GC9A01_MADCTL, 1, MADCTL_MX | MADCTL_BGR,
   GC9A01_TEON, 0,
   GC9A01_INVON, 0,
   GC9A01_SLPOUT, 0x80, // Exit sleep
```
(`GC9A011_DEFUNCTR` is `0xB6`, I just moved it to the constant since it was already defined.)

For whatever reason, the display doesn't obey the `MADCTL` command when it happens earlier in the init sequence and initializes in a landscape orientation. Even sending the command with a value of `0` results in a different behavior than the "default". It may not need to be as late as I've put it. I have no idea if the landscape state I see is the same on every instance of this display or if it's effectively random. It may also be influenced by some of the other mystery commands that have been cargo-culted by everyone using this chip, I didn't go down that rabbit hole.

TFT_eSPI doesn't initialize the rotation at all, but rather expects you to call its `setRotation` routine yourself. Since esphome isn't using hardware rotation, it works just as well to run it late in the initialization. TFT_eSPI also sets `0xB6, 2, 0x00, 0x20` instead of `0x00, 0x00`, but I was unable to figure out what that actually does.

As an additional note, the Adafruit_GC9A01A library has taken to commenting out the `0x70, 9, 0x07, 0x07, 0x04, 0x0E, 0x0F, 0x09, 0x07, 0x08, 0x03,` command with a comment that says it seems to work without it, but for my unit it prevents the display from showing anything.

2023-09-29 18:37 UTC, nickpdawson commented
> hi, esphome gives me this error when compiling using an external component. Is there any solution? Well thank you.
> 
> ```
>   File "/usr/local/bin/esphome", line 33, in <module>
>     sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
>   File "/esphome/esphome/__main__.py", line 1017, in main
>     return run_esphome(sys.argv)
>   File "/esphome/esphome/__main__.py", line 1004, in run_esphome
>     rc = POST_CONFIG_ACTIONS[args.command](args, config)
>   File "/esphome/esphome/__main__.py", line 435, in command_run
>     exit_code = write_cpp(config)
>   File "/esphome/esphome/__main__.py", line 185, in write_cpp
>     generate_cpp_contents(config)
>   File "/esphome/esphome/__main__.py", line 197, in generate_cpp_contents
>     CORE.flush_tasks()
>   File "/esphome/esphome/core/__init__.py", line 626, in flush_tasks
>     self.event_loop.flush_tasks()
>   File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
>     next(task.iterator)
>   File "/esphome/esphome/__main__.py", line 177, in wrapped
>     await coro(conf)
>   File "/config/esphome/.esphome/external_components/1ffebe30/esphome/components/gc9a01/display.py", line 77, in to_code
>     await setup_gc9a01(var, config)
>   File "/config/esphome/.esphome/external_components/1ffebe30/esphome/components/gc9a01/display.py", line 63, in setup_gc9a01
>     config[CONF_LAMBDA], [(display.DisplayBufferRef, "it")], return_type=cg.void
> AttributeError: module 'esphome.components.display' has no attribute 'DisplayBufferRef'
> ```
> 
> Esphome yaml:
> 
> ```
>   - source: github://4cello/esphome@gc9a01
>     components: ["gc9a01"]
> 
> spi:
>   mosi_pin: GPIO13
>   clk_pin: GPIO14
> 
> display:
> - platform: gc9a01
>   reset_pin: GPIO26
>   cs_pin: GPIO15
>   dc_pin: GPIO33
>   rotation: 180
>   lambda: |-
>       it.line(0, 0, 100, 50);
> ```
> 
> EDIT: change DisplayBufferRef to DisplayRef fixed my problem

had to make this change too with ESPHome 2023.9.1 and using 
```
external_components:
  - source: github://4cello/esphome@gc9a01
    components: ["gc9a01"]
```

2023-09-29 22:01 UTC, the-smart-home-maker commented
> > hi, esphome gives me this error when compiling using an external component. Is there any solution? Well thank you.
> > ```
> >   File "/usr/local/bin/esphome", line 33, in <module>
> >     sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
> >   File "/esphome/esphome/__main__.py", line 1017, in main
> >     return run_esphome(sys.argv)
> >   File "/esphome/esphome/__main__.py", line 1004, in run_esphome
> >     rc = POST_CONFIG_ACTIONS[args.command](args, config)
> >   File "/esphome/esphome/__main__.py", line 435, in command_run
> >     exit_code = write_cpp(config)
> >   File "/esphome/esphome/__main__.py", line 185, in write_cpp
> >     generate_cpp_contents(config)
> >   File "/esphome/esphome/__main__.py", line 197, in generate_cpp_contents
> >     CORE.flush_tasks()
> >   File "/esphome/esphome/core/__init__.py", line 626, in flush_tasks
> >     self.event_loop.flush_tasks()
> >   File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
> >     next(task.iterator)
> >   File "/esphome/esphome/__main__.py", line 177, in wrapped
> >     await coro(conf)
> >   File "/config/esphome/.esphome/external_components/1ffebe30/esphome/components/gc9a01/display.py", line 77, in to_code
> >     await setup_gc9a01(var, config)
> >   File "/config/esphome/.esphome/external_components/1ffebe30/esphome/components/gc9a01/display.py", line 63, in setup_gc9a01
> >     config[CONF_LAMBDA], [(display.DisplayBufferRef, "it")], return_type=cg.void
> > AttributeError: module 'esphome.components.display' has no attribute 'DisplayBufferRef'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Esphome yaml:
> > ```
> >   - source: github://4cello/esphome@gc9a01
> >     components: ["gc9a01"]
> > 
> > spi:
> >   mosi_pin: GPIO13
> >   clk_pin: GPIO14
> > 
> > display:
> > - platform: gc9a01
> >   reset_pin: GPIO26
> >   cs_pin: GPIO15
> >   dc_pin: GPIO33
> >   rotation: 180
> >   lambda: |-
> >       it.line(0, 0, 100, 50);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > EDIT: change DisplayBufferRef to DisplayRef fixed my problem
> 
> had to make this change too with ESPHome 2023.9.1 and using
> 
> ```
> external_components:
>   - source: github://4cello/esphome@gc9a01
>     components: ["gc9a01"]
> ```

Same error message here. How can  make this change?

2023-11-30 05:21 UTC, nguyenquangduc commented
hello everyone i am using external component for GC9A01 display and some components use I2C when i set update_interval: 0.1s then my i2c communication components are very slow. But when I set update_interval: 5s, my I2C communication components return to normal?. Is there any way to fix this problem, thanks for reading

2023-12-09 13:24 UTC, yggi commented
:+1: for home assistant support for gc9a01!

I git it working with the external component, but like others, I am running into the slow updates problem:

```
[14:20:03][W][component:214]: Component gc9a01.display took a long time for an operation (0.25 s).
[14:20:03][W][component:215]: Components should block for at most 20-30ms.
```

As far as I understand it, it is caused by [this loop](https://github.com/esphome/esphome/pull/3625#discussion_r1224789410) and not the actual spi data transfer. Is that correct and is there any other insight or progress on this?

2023-12-09 17:29 UTC, ayufan commented
The rendering is highly inefficient. It just takes long time to render
anything, and it takes long time to convert and send to display.

On Sat, 9 Dec 2023 at 14:25, Sebastian Steuer ***@***.***>
wrote:

> 👍 for home assistant support for gc9a01!
>
> I git it working with the external component, but like others, I am
> running into the slow updates problem:
>
> [14:20:03][W][component:214]: Component gc9a01.display took a long time for an operation (0.25 s).
> [14:20:03][W][component:215]: Components should block for at most 20-30ms.
>
> As far as I understand it, it is caused by this loop
> <https://github.com/esphome/esphome/pull/3625#discussion_r1224789410> and
> not the actual spi data transfer. Is that correct and is there any other
> insight or progress on this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/3625#issuecomment-1848409701>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AASOSQMH4GYTSLHMVHTZHXLYIRRC7AVCNFSM53APD7I2U5DIOJSWCZC7NNSXTN2JONZXKZKDN5WW2ZLOOQ5TCOBUHA2DAOJXGAYQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-12-13 02:24 UTC, jesserockz requested changes

2023-12-13 02:24 UTC, jesserockz commented on esphome/components/gc9a01/gc9a01.cpp
> +  ESP_LOGD(TAG, "  END");
```suggestion
```

2023-12-13 02:24 UTC, jesserockz commented on esphome/components/gc9a01/gc9a01.cpp
> +  display_init_(INITCMD);
```suggestion
  this->display_init_(INITCMD);
```

2023-12-13 02:24 UTC, jesserockz commented on esphome/components/gc9a01/gc9a01.cpp
> +int GC9A01::get_width_internal() { return width_; }
```suggestion
int GC9A01::get_height_internal() { return this->height_; }

int GC9A01::get_width_internal() { return this->width_; }
```

2023-12-13 02:24 UTC, jesserockz commented on esphome/components/gc9a01/gc9a01.cpp
> +  delay(100);  // NOLINT
Please alter this code to use a `set_timeout` instead of delaying

2023-12-13 02:24 UTC, jesserockz commented on esphome/components/gc9a01/gc9a01.h
> +                                     spi::DATA_RATE_8MHZ> {
```suggestion
                                     spi::DATA_RATE_40MHZ> {
```

2023-12-26 09:02 UTC, bearpawmaxim commented
Hello! When using this PR I'm getting an error
`INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1041, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1028, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 407, in command_compile
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 192, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 204, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 679, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 184, in wrapped
    await coro(conf)
  File "/data/external_components/1ff663bb/esphome/components/gc9a01/display.py", line 77, in to_code
    await setup_gc9a01(var, config)
  File "/data/external_components/1ff663bb/esphome/components/gc9a01/display.py", line 56, in setup_gc9a01
    await display.register_display(var, config)
  File "/esphome/esphome/components/display/__init__.py", line 119, in register_display
    await cg.register_component(var, config)
  File "/esphome/esphome/cpp_helpers.py", line 56, in register_component
    raise ValueError(
ValueError: Component ID watchface1 was not declared to inherit from Component, or was registered twice. Please create a bug report with your configuration.
`

the config is 
`substitutions:
  device_name: pc-power-button
  device_name_underscore: pc_power_button

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32-c3-devkitm-1

packages:
  device_common: !include .device_common.yaml

external_components:
 - source: github://pr#3625
   components: [ gc9a01 ]
#  - source: github://4cello/esphome@gc9a01
#    components: ["gc9a01"]

spi:
  mosi_pin: GPIO7
  clk_pin: GPIO6

# Need to turn on backlight as by default is not on
output:
  - platform: ledc
    pin: GPIO3
    id: gpio_3_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_3_backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

font:
  - file: "gfonts://Roboto"
    id: font_16
    size: 16
  - file: "gfonts://Roboto"
    id: font_32
    size: 32

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_green
    red: 3%
    green: 100%
    blue: 5%
  - id: my_blue
    red: 3%
    green: 5%
    blue: 100%

display:
#  - platform: ili9xxx
#    model: gc9a01
# Above is for when or if this is merged into the ili9xxx platform
  - platform: gc9a01
    id: watchface1
    reset_pin: GPIO1
    cs_pin: GPIO10
    dc_pin: GPIO2
    rotation: 90
    lambda: |-
      it.strftime(120,80, id(font_16), id(my_blue), TextAlign::CENTER, "%A %b %d", id(sntp_time).now());
      it.strftime(120,120, id(font_32), TextAlign::CENTER, "%I:%M %p", id(sntp_time).now());
      it.circle(120, 120, 115, id(my_red));
`

2023-12-27 00:06 UTC, ParineetVernekar commented
> Hello! When using this PR I'm getting an error with the latest esphome version (2023.12.5):
> 
> ```
> INFO Generating C++ source...
> Traceback (most recent call last):
>   File "/usr/local/bin/esphome", line 33, in <module>
>     sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/esphome/esphome/__main__.py", line 1041, in main
>     return run_esphome(sys.argv)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/esphome/esphome/__main__.py", line 1028, in run_esphome
>     rc = POST_CONFIG_ACTIONS[args.command](args, config)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/esphome/esphome/__main__.py", line 407, in command_compile
>     exit_code = write_cpp(config)
>                 ^^^^^^^^^^^^^^^^^
>   File "/esphome/esphome/__main__.py", line 192, in write_cpp
>     generate_cpp_contents(config)
>   File "/esphome/esphome/__main__.py", line 204, in generate_cpp_contents
>     CORE.flush_tasks()
>   File "/esphome/esphome/core/__init__.py", line 679, in flush_tasks
>     self.event_loop.flush_tasks()
>   File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
>     next(task.iterator)
>   File "/esphome/esphome/__main__.py", line 184, in wrapped
>     await coro(conf)
>   File "/data/external_components/1ff663bb/esphome/components/gc9a01/display.py", line 77, in to_code
>     await setup_gc9a01(var, config)
>   File "/data/external_components/1ff663bb/esphome/components/gc9a01/display.py", line 56, in setup_gc9a01
>     await display.register_display(var, config)
>   File "/esphome/esphome/components/display/__init__.py", line 119, in register_display
>     await cg.register_component(var, config)
>   File "/esphome/esphome/cpp_helpers.py", line 56, in register_component
>     raise ValueError(
> ValueError: Component ID watchface1 was not declared to inherit from Component, or was registered twice. Please create a bug report with your configuration.
> ```
> 
> the config is
> 
> ```
> substitutions:
>   device_name: pc-power-button
>   device_name_underscore: pc_power_button
> 
> esphome:
>   name: ${device_name}
>   platform: ESP32
>   board: esp32-c3-devkitm-1
> 
> packages:
>   device_common: !include .device_common.yaml
> 
> external_components:
>  - source: github://pr#3625
>    components: [ gc9a01 ]
> #  - source: github://4cello/esphome@gc9a01
> #    components: ["gc9a01"]
> 
> spi:
>   mosi_pin: GPIO7
>   clk_pin: GPIO6
> 
> # Need to turn on backlight as by default is not on
> output:
>   - platform: ledc
>     pin: GPIO3
>     id: gpio_3_backlight_pwm
> 
> light:
>   - platform: monochromatic
>     output: gpio_3_backlight_pwm
>     name: "Display Backlight"
>     id: back_light
>     restore_mode: ALWAYS_ON
> 
> font:
>   - file: "gfonts://Roboto"
>     id: font_16
>     size: 16
>   - file: "gfonts://Roboto"
>     id: font_32
>     size: 32
> 
> color:
>   - id: my_red
>     red: 100%
>     green: 3%
>     blue: 5%
>   - id: my_green
>     red: 3%
>     green: 100%
>     blue: 5%
>   - id: my_blue
>     red: 3%
>     green: 5%
>     blue: 100%
> 
> display:
> #  - platform: ili9xxx
> #    model: gc9a01
> # Above is for when or if this is merged into the ili9xxx platform
>   - platform: gc9a01
>     id: watchface1
>     reset_pin: GPIO1
>     cs_pin: GPIO10
>     dc_pin: GPIO2
>     rotation: 90
>     lambda: |-
>       it.strftime(120,80, id(font_16), id(my_blue), TextAlign::CENTER, "%A %b %d", id(sntp_time).now());
>       it.strftime(120,120, id(font_32), TextAlign::CENTER, "%I:%M %p", id(sntp_time).now());
>       it.circle(120, 120, 115, id(my_red));
> ```
> 
> UPD: looks like this happens because of #6009 being merged some days ago

I'm having the same issue with the same config
`
time:
  - platform: homeassistant
    timezone: "Australia/Melbourne"
    id: esptime

# Test - see if the thing picks up BLE info
#esp32_ble_tracker:
#nope - locks up
#SpokeTooSoon - actually does work, kinda. Slows down the startup significantly then claims to scan but nothing is found
#Either is not supported or antenna is really weak

sensor:
  - platform: uptime
    name: "$devicename Uptime"
  - platform: wifi_signal
    name: "$devicename WiFi Signal"
    update_interval: 60s    
  - platform: homeassistant
    id: outdoor_temperature
    entity_id: sensor.gw1000_v1_7_6_outdoor_temperature

external_components:
  - source: github://pr#3625
    components: [ gc9a01 ]
# Arduino code shows screen is a GC9A01 with CST816D touch screen

spi:
  mosi_pin: $mopin
  clk_pin: $clpin
#mosi = Master Out Slave In
#miso = Master In Slave Out or fermented bean paste. In this case, most likely the former rather than the latter. Doesn't matter as not used.

# Need to turn on backlight as by default is not on
output:
  - platform: ledc
    pin: $bkpin
    id: gpio_3_backlight_pwm
light:
  - platform: monochromatic
    output: gpio_3_backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

font:
  - file: 'fonts/GoogleSans-Medium.ttf'
    id: font_16
    size: 16
  - file: 'fonts/GoogleSans-Medium.ttf'
    id: font_32
    size: 32

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_green
    red: 3%
    green: 100%
    blue: 5%
  - id: my_blue
    red: 3%
    green: 5%
    blue: 100%

display:
  - platform: gc9a01
    id: watchface
    reset_pin: $repin
    cs_pin: $cspin
    dc_pin: $dcpin

# Rotate the screen so usb socket is pointing down
    rotation: 90

# Print the date on one line in blue
# Print the current time on the next line, but in a bigger font but default white
# Print the outside temperature in green
# Surround the lot by a red circle with centre at 120, 120 and a radius of 115 because why not
    lambda: |-
      it.strftime(120,80, id(font_16), id(my_blue), TextAlign::CENTER, "%A %b %d", id(esptime).now());
      it.strftime(120,120, id(font_32), TextAlign::CENTER, "%I:%M %p", id(esptime).now());
      it.printf(120, 170, id(font_32), id(my_green), TextAlign::CENTER, "Now: %.1f°", id(outdoor_temperature).state);
      it.circle(120, 120, 115, id(my_red));`

Did you find a way around it?

2023-12-27 00:10 UTC, ParineetVernekar commented
> Hello! When using this PR I'm getting an error with the latest esphome version (2023.12.5):
> 
> ```
> INFO Generating C++ source...
> Traceback (most recent call last):
>   File "/usr/local/bin/esphome", line 33, in <module>
>     sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/esphome/esphome/__main__.py", line 1041, in main
>     return run_esphome(sys.argv)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/esphome/esphome/__main__.py", line 1028, in run_esphome
>     rc = POST_CONFIG_ACTIONS[args.command](args, config)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/esphome/esphome/__main__.py", line 407, in command_compile
>     exit_code = write_cpp(config)
>                 ^^^^^^^^^^^^^^^^^
>   File "/esphome/esphome/__main__.py", line 192, in write_cpp
>     generate_cpp_contents(config)
>   File "/esphome/esphome/__main__.py", line 204, in generate_cpp_contents
>     CORE.flush_tasks()
>   File "/esphome/esphome/core/__init__.py", line 679, in flush_tasks
>     self.event_loop.flush_tasks()
>   File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
>     next(task.iterator)
>   File "/esphome/esphome/__main__.py", line 184, in wrapped
>     await coro(conf)
>   File "/data/external_components/1ff663bb/esphome/components/gc9a01/display.py", line 77, in to_code
>     await setup_gc9a01(var, config)
>   File "/data/external_components/1ff663bb/esphome/components/gc9a01/display.py", line 56, in setup_gc9a01
>     await display.register_display(var, config)
>   File "/esphome/esphome/components/display/__init__.py", line 119, in register_display
>     await cg.register_component(var, config)
>   File "/esphome/esphome/cpp_helpers.py", line 56, in register_component
>     raise ValueError(
> ValueError: Component ID watchface1 was not declared to inherit from Component, or was registered twice. Please create a bug report with your configuration.
> ```
> 
> the config is
> 
> ```
> substitutions:
>   device_name: pc-power-button
>   device_name_underscore: pc_power_button
> 
> esphome:
>   name: ${device_name}
>   platform: ESP32
>   board: esp32-c3-devkitm-1
> 
> packages:
>   device_common: !include .device_common.yaml
> 
> external_components:
>  - source: github://pr#3625
>    components: [ gc9a01 ]
> #  - source: github://4cello/esphome@gc9a01
> #    components: ["gc9a01"]
> 
> spi:
>   mosi_pin: GPIO7
>   clk_pin: GPIO6
> 
> # Need to turn on backlight as by default is not on
> output:
>   - platform: ledc
>     pin: GPIO3
>     id: gpio_3_backlight_pwm
> 
> light:
>   - platform: monochromatic
>     output: gpio_3_backlight_pwm
>     name: "Display Backlight"
>     id: back_light
>     restore_mode: ALWAYS_ON
> 
> font:
>   - file: "gfonts://Roboto"
>     id: font_16
>     size: 16
>   - file: "gfonts://Roboto"
>     id: font_32
>     size: 32
> 
> color:
>   - id: my_red
>     red: 100%
>     green: 3%
>     blue: 5%
>   - id: my_green
>     red: 3%
>     green: 100%
>     blue: 5%
>   - id: my_blue
>     red: 3%
>     green: 5%
>     blue: 100%
> 
> display:
> #  - platform: ili9xxx
> #    model: gc9a01
> # Above is for when or if this is merged into the ili9xxx platform
>   - platform: gc9a01
>     id: watchface1
>     reset_pin: GPIO1
>     cs_pin: GPIO10
>     dc_pin: GPIO2
>     rotation: 90
>     lambda: |-
>       it.strftime(120,80, id(font_16), id(my_blue), TextAlign::CENTER, "%A %b %d", id(sntp_time).now());
>       it.strftime(120,120, id(font_32), TextAlign::CENTER, "%I:%M %p", id(sntp_time).now());
>       it.circle(120, 120, 115, id(my_red));
> ```
> 
> UPD: looks like this happens because of #6009 being merged some days ago

Hello! I'm having an issue with the same config. Did you find a way around it?

2023-12-27 07:16 UTC, bearpawmaxim commented
> Hello! I'm having an issue with the same config. Did you find a way around it?

We need to wait until PR owner will issue a fix to code.
Until then, you can use my "fork" of this PR this way
```
external_components:
  - source: github://bearpawmaxim/esphome@pr3625fix
    components: [gc9a01]
```

2023-12-27 13:54 UTC, jbishop129 commented
hey @bearpawmaxim Thanks for lending a hand here.. still getting a compile error using your fork:
`AttributeError: module 'esphome.components.display' has no attribute 'DisplayBufferRef'. Did you mean: 'DisplayBuffer'?`

Looks like `components.display` is looking for `DisplayBuffer` instead of `DisplayBufferRef`. Is this a quick fix?

> ```
> external_components:
>   - source: github://bearpawmaxim/esphome@pr3625fix
>     components: [gc9a01]
> ```

2023-12-27 14:15 UTC, ParineetVernekar commented
> hey @bearpawmaxim Thanks for lending a hand here.. still getting a compile error using your fork: `AttributeError: module 'esphome.components.display' has no attribute 'DisplayBufferRef'. Did you mean: 'DisplayBuffer'?`
> 
> Looks like `components.display` is looking for `DisplayBuffer` instead of `DisplayBufferRef`. Is this a quick fix?
> 
> > ```
> > external_components:
> >   - source: github://bearpawmaxim/esphome@pr3625fix
> >     components: [gc9a01]
> > ```

I had the same issue too, I've made my own fork from @bearpawmaxim 's which seemed to work for me
 > ```
 > external_components:
 >   - source: github://ParineetVernekar/esphome@pr3625fix
 >     components: [gc9a01]
 > ```

2023-12-27 15:42 UTC, bearpawmaxim commented
> still getting a compile error using your fork:

That is strange because it works for me)

2023-12-27 19:14 UTC, jbishop129 commented
@ParineetVernekar Thanks for jumping in. I tried your fork, and get a bit further, but still erroring on a parameter in `DisplayBuffer` see below:

using:
```yaml
external_components:
  - source: github://ParineetVernekar/esphome@pr3625fix
    components: [gc9a01]
```
compile output:
``` c++
Compiling .pioenvs/esp32-c3/bootloader_support/src/bootloader_common_loader.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/bootloader_clock_init.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/bootloader_flash.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/bootloader_mem.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/bootloader_random.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/bootloader_random_esp32c3.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/bootloader_utility.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/esp_image_format.o
src/main.cpp: In function 'void setup()':
src/main.cpp:3384:53: error: cannot declare parameter 'it' to be of abstract type 'esphome::display::DisplayBuffer'
   roundOLED1->set_writer([=](display::DisplayBuffer it) -> void {
                              ~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from src/esphome.h:19,
                 from src/main.cpp:3:
src/esphome/components/display/display_buffer.h:15:7: note:   because the following virtual functions are pure within 'esphome::display::DisplayBuffer':
 class DisplayBuffer : public Display {
       ^~~~~~~~~~~~~
In file included from src/esphome/components/api/proto.h:3,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/component.h:302:16: note: 	'virtual void esphome::PollingComponent::update()'
   virtual void update() = 0;
                ^~~~~~
In file included from src/esphome.h:18,
                 from src/main.cpp:3:
src/esphome/components/display/display.h:434:23: note: 	'virtual esphome::display::DisplayType esphome::display::Display::get_display_type()'
   virtual DisplayType get_display_type() = 0;
                       ^~~~~~~~~~~~~~~~
In file included from src/esphome.h:19,
                 from src/main.cpp:3:
src/esphome/components/display/display_buffer.h:25:15: note: 	'virtual int esphome::display::DisplayBuffer::get_height_internal()'
   virtual int get_height_internal() = 0;
               ^~~~~~~~~~~~~~~~~~~
src/esphome/components/display/display_buffer.h:26:15: note: 	'virtual int esphome::display::DisplayBuffer::get_width_internal()'
   virtual int get_width_internal() = 0;
               ^~~~~~~~~~~~~~~~~~
src/esphome/components/display/display_buffer.h:29:16: note: 	'virtual void esphome::display::DisplayBuffer::draw_absolute_pixel_internal(int, int, esphome::Color)'
   virtual void draw_absolute_pixel_internal(int x, int y, Color color) = 0;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
<unicode string>:277:4: error: no matching function for call to 'esphome::gc9a01::GC9A01::set_writer(setup()::<lambda(esphome::display::DisplayBuffer)>)'
In file included from src/esphome.h:18,
                 from src/main.cpp:3:
src/esphome/components/display/display.h:411:8: note: candidate: 'void esphome::display::Display::set_writer(esphome::display::display_writer_t&&)'
   void set_writer(display_writer_t &&writer);
        ^~~~~~~~~~
src/esphome/components/display/display.h:411:8: note:   no known conversion for argument 1 from 'setup()::<lambda(esphome::display::DisplayBuffer)>' to 'esphome::display::display_writer_t&&' {aka 'std::function<void(esphome::display::Display&)>&&'}
Compiling .pioenvs/esp32-c3/bootloader_support/src/flash_encrypt.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/secure_boot.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/flash_partitions.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/flash_qio_mode.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/bootloader_flash_config_esp32c3.o
*** [.pioenvs/esp32-c3/src/main.o] Error 1

2023-12-27 19:31 UTC, bearpawmaxim commented
@jbishop129 , @ParineetVernekar friends, what version of esphome you're using? I'm fine with my "fork" with [this](https://github.com/bearpawmaxim/esphome-configs/blob/master/pc-wol-button.yaml) config on 2023.12.5.
Even tried to clean build files and compile again: it succeeded.
Here's the log of successful build https://hastebin.com/share/akuzayerup.bash

2023-12-27 20:35 UTC, jbishop129 commented
@bearpawmaxim good call. I was running ESPHome 2023.23.0 - DEV, I rolled back to the non-Dev Add-on (2023.12.5) and cleaned build files, unfortunately the same compile error.  Seems like it is zoning in on this `cannot declare parameter 'it'` reference in the `DisplayBuffer`. Anything stand out here?
```c++
Compiling .pioenvs/esp32-c3/app_trace/gcov/gcov_rtio.o
Compiling .pioenvs/esp32-c3/app_update/esp_ota_ops.o
Compiling .pioenvs/esp32-c3/app_update/esp_app_desc.o
Compiling .pioenvs/esp32-c3/bootloader_support/src/bootloader_common.o
src/main.cpp: In function 'void setup()':
src/main.cpp:3384:53: error: cannot declare parameter 'it' to be of abstract type 'esphome::display::DisplayBuffer'
   roundOLED1->set_writer([=](display::DisplayBuffer it) -> void {

2023-12-27 20:42 UTC, bearpawmaxim commented
> Anything stand out here?

Nothing unless you specify your config ;-)

2023-12-27 20:57 UTC, jbishop129 commented
> > Anything stand out here?
> 
> Nothing unless you specify your config ;)

Fair enough ;) Removed unnecessary part of my display lambda:

```yaml
esphome:
  name: esp32-c3
  friendly_name: ESP32-C3
  platform: ESP32
  board: esp32-c3-devkitm-1

  on_boot:
    then:
      - light.turn_on:
          id: backlight
          brightness: 65%

external_components:
  - source: github://bearpawmaxim/esphome@pr3625fix
    components: [gc9a01]

logger:

api:
  encryption:
    key: !secret api

ota:
  password: !secret ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  ap:
    ssid: "Esp32-C3 Fallback Hotspot"
    password: !secret ap

spi:
  mosi_pin: GPIO10
  clk_pin: GPIO7

light:
  - platform: monochromatic
    id: backlight
    name: "Backlight"
    output: pwm_output

output:
  - platform: ledc
    id: pwm_output
    pin: GPIO3

#########
# Fonts
#########
font:
  - file: 'fonts/Google_Sans_Regular.ttf'
    id: font_16
    size: 16

  - file: 'fonts/Google_Sans_Regular.ttf'
    id: font_32
    size: 32

  - file: 'fonts/Google_Sans_Regular.ttf'
    id: font_48
    size: 48

  - file: 'fonts/Google_Sans_Regular.ttf'
    id: font_80
    size: 80

## Weather icons - Size 46
  - file: 'fonts/mdi.ttf'
    id: icon_weather
    size: 46
    glyphs: [
      "\U000F0590", # mdi-weather-cloudy
      "\U000F0F2F", # mdi-weather-cloudy-alert
      "\U000F0E6E", # mdi-weather-cloudy-arrow-right
      "\U000F0591", # mdi-weather-fog
      "\U000F0592", # mdi-weather-hail
      "\U000F0F30", # mdi-weather-hazy
      "\U000F0898", # mdi-weather-hurricane
      "\U000F0593", # mdi-weather-lightning
      "\U000F067E", # mdi-weather-lightning-rainy
      "\U000F0594", # mdi-weather-night
      "\U000F0F31", # mdi-weather-night-partly-cloudy
      "\U000F0595", # mdi-weather-partly-cloudy
      "\U000F0F32", # mdi-weather-partly-lightning
      "\U000F0F33", # mdi-weather-partly-rainy
      "\U000F0F34", # mdi-weather-partly-snowy
      "\U000F0F35", # mdi-weather-partly-snowy-rainy
      "\U000F0596", # mdi-weather-pouring
      "\U000F0597", # mdi-weather-rainy
      "\U000F0598", # mdi-weather-snowy
      "\U000F0F36", # mdi-weather-snowy-heavy
      "\U000F067F", # mdi-weather-snowy-rainy
      "\U000F0599", # mdi-weather-sunny
      "\U000F0F37", # mdi-weather-sunny-alert
      "\U000F14E4", # mdi-weather-sunny-off
      "\U000F059A", # mdi-weather-sunset
      "\U000F059B", # mdi-weather-sunset-down
      "\U000F059C", # mdi-weather-sunset-up
      "\U000F0F38", # mdi-weather-tornado
      "\U000F059D", # mdi-weather-windy
      "\U000F059E", # mdi-weather-windy-variant
      ]

# ## Other icons - Size 32
  - file: 'fonts/mdi.ttf'
    id: icon_32
    size: 32
    glyphs: [
      "\U000F000E", # mdi-account-multiple
    ]  

##################
# Sensors from HA
##################
time:
  - platform: sntp
    id: my_time
    timezone: America/Phoenix

sensor:
  - platform: homeassistant
    id: outside_temp_dht22
    entity_id: sensor.dht22_temp

  - platform: homeassistant
    id: openweather_temp
    entity_id: sensor.openweathermap_temp_rounded

  - platform: homeassistant
    id: spa_temp
    entity_id: sensor.pool_temp

binary_sensor:
  - platform: homeassistant
    id: office_motion
    entity_id: binary_sensor.office_motion_sensor

  - platform: homeassistant
    id: spa_heater
    entity_id: switch.pool_spa
  
text_sensor:
  - platform: homeassistant
    id: weather
    entity_id: weather.openweathermap
    internal: true

  - platform: homeassistant
    name: Readable_time
    entity_id: sensor.12h_time
    id: readable_ha_time

color:
  - id: yellow
    hex: FFC300

  - id: light_gray
    hex: DEDEDE

display:
  - platform: gc9a01
    id: roundOLED1
    reset_pin: GPIO4
    cs_pin: GPIO6
    dc_pin: GPIO5
    rotation: 90
    
    lambda: |-
 ... trimmed out my display lambda.. not relevant...

2023-12-27 22:08 UTC, bearpawmaxim commented
> compile error

I've managed to compile your code with the @ParineetVernekar's version. Until the code from this PR isn't merged it is better to use it.
```
external_components:
  - source: github://bearpawmaxim/esphome@pr3625fix
    components: [gc9a01]
```

2023-12-27 22:51 UTC, jbishop129 commented
> > compile error
> 
> I've managed to compile your code on 2023.12.5 with the @ParineetVernekar's version. Until the code from this PR isn't merged it is better to use it.
> 
> ```
> external_components:
>   - source: github://bearpawmaxim/esphome@pr3625fix
>     components: [gc9a01]
> ```

Really appreciate your time and attention on this. I'm still getting a different compile error when using Parineet's version as well, however if you are able to compile, I will take this aside to work further on my own. I don't want to treat this area as a troubleshooting forum :)

2023-12-28 02:28 UTC, jbishop129 commented
Some progress made: It turns out the code I gave you above with the redacted display content after `lambda: |-` Is actually the key point where it fails. If you insert anything in the `lambda:` it will fail to compile (example hello world one-liners, basic if/then, etc.) and dump the error below. Seems to be having a hard time with the display initiation. @bearpawmaxim I wonder if you just add a simple:
```yaml
    lambda: |-
      // Outside Temp
      if (id(openweather_temp).has_state()) {
        it.printf(120,210, id(font_32), TextAlign::CENTER, "%.0f°F", id(openweather_temp).state);
        it.printf(115,230, id(font_16), TextAlign::CENTER, "Outside");
      }
```


do you get a compile error like this?
```c++
|-- SPI @ 2.0.0
Compiling .pioenvs/esp32-s2/src/main.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:3319:53: error: cannot declare parameter 'it' to be of abstract type 'esphome::display::DisplayBuffer'
   roundOLED1->set_writer([=](display::DisplayBuffer it) -> void {
                              ~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from src/esphome.h:21,
                 from src/main.cpp:3:
src/esphome/components/display/display_buffer.h:15:7: note:   because the following virtual functions are pure within 'esphome::display::DisplayBuffer':
 class DisplayBuffer : public Display {
       ^~~~~~~~~~~~~
In file included from src/esphome/components/api/proto.h:3,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/component.h:302:16: note: 	'virtual void esphome::PollingComponent::update()'
   virtual void update() = 0;
                ^~~~~~
In file included from src/esphome.h:20,
                 from src/main.cpp:3:
src/esphome/components/display/display.h:449:23: note: 	'virtual esphome::display::DisplayType esphome::display::Display::get_display_type()'
   virtual DisplayType get_display_type() = 0;
                       ^~~~~~~~~~~~~~~~
In file included from src/esphome.h:21,
                 from src/main.cpp:3:
src/esphome/components/display/display_buffer.h:25:15: note: 	'virtual int esphome::display::DisplayBuffer::get_height_internal()'
   virtual int get_height_internal() = 0;
               ^~~~~~~~~~~~~~~~~~~
src/esphome/components/display/display_buffer.h:26:15: note: 	'virtual int esphome::display::DisplayBuffer::get_width_internal()'
   virtual int get_width_internal() = 0;
               ^~~~~~~~~~~~~~~~~~
src/esphome/components/display/display_buffer.h:29:16: note: 	'virtual void esphome::display::DisplayBuffer::draw_absolute_pixel_internal(int, int, esphome::Color)'
   virtual void draw_absolute_pixel_internal(int x, int y, Color color) = 0;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
<unicode string>:180:4: error: no matching function for call to 'esphome::gc9a01::GC9A01::set_writer(setup()::<lambda(esphome::display::DisplayBuffer)>)'
In file included from src/esphome.h:20,
                 from src/main.cpp:3:
src/esphome/components/display/display.h:426:8: note: candidate: 'void esphome::display::Display::set_writer(esphome::display::display_writer_t&&)'
   void set_writer(display_writer_t &&writer);
        ^~~~~~~~~~
src/esphome/components/display/display.h:426:8: note:   no known conversion for argument 1 from 'setup()::<lambda(esphome::display::DisplayBuffer)>' to 'esphome::display::display_writer_t&&' {aka 'std::function<void(esphome::display::Display&)>&&'}
*** [.pioenvs/esp32-s2/src/main.cpp.o] Error 1

2023-12-28 13:59 UTC, bearpawmaxim commented
> Is actually the key point where it fails

Yes. I got the same thing.. Will investigate in it.

2023-12-29 14:34 UTC, tiimsvk commented
hello another compilation error. commented here: [https://github.com/landonr/lilygo-tdisplays3-esphome/pull/46](url)

`Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1041, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1028, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 458, in command_run
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 192, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 204, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 679, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 246, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 184, in wrapped
    await coro(conf)
  File "/config/esphome/custom_component/gc9a01/display.py", line 78, in to_code
    await setup_gc9a01(var, config)
  File "/config/esphome/custom_component/gc9a01/display.py", line 56, in setup_gc9a01
    await display.register_display(var, config)
  File "/esphome/esphome/components/display/__init__.py", line 119, in register_display
    await cg.register_component(var, config)
  File "/esphome/esphome/cpp_helpers.py", line 56, in register_component
    raise ValueError(
ValueError: Component ID round_display was not declared to inherit from Component, or was registered twice. Please create a bug report with your configuration.`

Do you happen to know how to fix it?

2023-12-30 18:04 UTC, bearpawmaxim commented
> hello another compilation error
@tiimsvk just use my "fork"

```
external_components:
  - source: github://bearpawmaxim/esphome@pr3625fix
    components: [gc9a01]
```

@jbishop129, @ParineetVernekar I've fixed lambda in my fork, so you're free to use it.

2023-12-30 18:15 UTC, bearpawmaxim commented
@4cello hi! I'm getting the weird issue while trying to use 16-bit color (`eight_bit_color: false`)
![20231230_201040](https://github.com/esphome/esphome/assets/7537528/1d4bcb4e-4c9a-4400-9ece-2303adee83b8)

Do you have any ideas about what can be wrong?
P.S.: maybe it's time to complete with this PR?

2023-12-30 18:42 UTC, jbishop129 commented
> - source: github://bearpawmaxim/esphome@pr3625fix
>     components: [gc9a01]

Success! Thank you very much @bearpawmaxim I have this running on an ESP32 C3, display is working!

2024-01-04 10:29 UTC, bearpawmaxim commented
> I'm getting the weird issue while trying to use 16-bit color

The issue was in uint16_t overflow while calculating buffer position. Fixed in my fork.

P.S.: the benefit of using the 16bit mode are x2 drawing speed while using x2 memory (115200 bytes) and more essential colors. It is ok if you have 250+ kbytes of ram

2024-01-04 12:44 UTC, tiimsvk commented
> > hello another compilation error
> > @tiimsvk just use my "fork"
> 
> ```
> external_components:
>   - source: github://bearpawmaxim/esphome@pr3625fix
>     components: [gc9a01]
> ```
> 
> @jbishop129, @ParineetVernekar I've fixed lambda in my fork, so you're free to use it.

Hi after update to esphome 12.5  and using this plugin, the display flickers during the update (the RGB color of some brightness blocks changes, etc. as if there is a bad power supply).
After installing back to 11.6 everything works as it should
what changed in the code? can you make the code available so that I can download it manually and compare?
well thank you

2024-01-04 13:12 UTC, bearpawmaxim commented
> the display flickers during the update

It may be related to the 80MHz spi speed I've set for the display. Try to lower it from `spi::DATA_RATE_80MHZ` to `spi::DATA_RATE_40MHZ` in `gc9a01.h` and see if it would help. If not - set to `spi::DATA_RATE_20MHZ`

The code can be downloaded from [here](https://github.com/bearpawmaxim/esphome/tree/pr3625fix/esphome/components/gc9a01)

2024-01-06 05:04 UTC, tiimsvk commented
> > the display flickers during the update
> 
> It may be related to the 80MHz spi speed I've set for the display. Try to lower it from `spi::DATA_RATE_80MHZ` to `spi::DATA_RATE_40MHZ` in `gc9a01.h` and see if it would help. If not - set to `spi::DATA_RATE_20MHZ`
> 
> The code can be downloaded from [here](https://github.com/bearpawmaxim/esphome/tree/pr3625fix/esphome/components/gc9a01)

got you

On old file is speed spi is 8Mhz 
`spi::DATA_RATE_8MHZ> {`

And another problém is color on display: RGB scheme is changed
Fix this problem replace old file gc9a01.cpp

```
  if (this->eightbitcolor_) {
    const uint32_t color332 = display::ColorUtil::color_to_332(color);
//    const uint32_t color332 = display::ColorUtil::color_to_332(color,
//      display::ColorOrder::COLOR_ORDER_BGR);
    uint16_t pos = (x + y * this->get_width_internal());
    this->buffer_[pos] = color332;
  } else {
    const uint32_t color565 = display::ColorUtil::color_to_565(color);
    uint16_t pos = (x + y * this->get_width_internal()) * 2;
//    const uint32_t color565 = display::ColorUtil::color_to_565(color,
//      display::ColorOrder::COLOR_ORDER_BGR);
//    uint32_t pos = (x + y * this->get_width_internal()) * 2;
    this->buffer_[pos++] = (color565 >> 8) & 0xff;
    this->buffer_[pos] = color565 & 0xff;
  }
```

2024-01-07 10:12 UTC, bearpawmaxim commented
> RGB scheme is changed

This is strange because on my side these lines fixes the colors (blue was red and red was blue)

2024-01-07 11:02 UTC, bearpawmaxim commented
> RGB scheme is changed

@tiimsvk 
Oh, I've found the issue! While fixing the color displacement in 16bit mode, I occasionally broke the 8bit mode))). Now everything is fixed in my fork.

About your flickering. Did lowering the frequency fixed your issue?
I have an idea that it may happen because of an addition of the display buffer. I assume that there was no display buffer on 11.6.. If so, then I can't help you a lot, unfortunately..
The last thing to try (only if you have 250kb + of ram on your device) is to set `eight_bit_color: false` in your display config.

2024-03-11 02:59 UTC, clydebarrow commented
#6351 adds GC9A01A support to the `ili9xxx` driver. Closing this one.

2024-03-11 02:59 UTC, closed without merging