Add energy to pzemdc
OttoWinter/esphomeyaml pull request #3626
Opened 2022-07-08 21:28 UTC by andreashergert1984

# What does this implement/fix?

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1226

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2177

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: pzemdc
    current:
      name: "MPPT Charger Adrress 2 Current"
    voltage:
      name: "MPPT Charger Address 2 Voltage"
    power:
      name: "MPPT Charger Address 2 Power"
    energy:
      name: "MPPT Charger Address 2 Energy"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-09-07 07:48 UTC, jesserockz requested changes

2022-09-07 07:48 UTC, jesserockz commented on tests/test5.yaml
> +      name: "PZEM-003 Energy"
pzemdc is already in `tests/test3.yaml` please add the energy sensor there.

2022-12-08 12:54 UTC, andreashergert1984 commented on tests/test5.yaml
> +      name: "PZEM-003 Energy"
moved

2023-02-23 07:32 UTC, KG3RK3N commented
@jesserockz 
Would be nice if you review the last changes and complete the PR if everything fine.

2023-02-23 17:38 UTC, oxan approved these changes

2023-02-23 17:38 UTC, merged