[WIP] Implementation for Jandy Watercolors Lights
OttoWinter/esphomeyaml pull request #3628
Opened 2022-07-10 04:15 UTC by carlos-sarmiento

# What does this implement/fix?
Implement support for Jandy Watercolors Lights using a Relay. Manual is here: https://www.jandy.com/en/products/pool-lights/watercolors-led-gen-2

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-07-31 02:45 UTC, ssieb requested changes

2022-07-31 02:45 UTC, ssieb commented on esphome/components/jandy_watercolors/jandy_watercolors.cpp
> +  call.set_effect(this->get_effect_name_from_id_(new_target_effect));
You can give `set_effect` the effect number as well, so you don't need the lookup.

2022-07-31 02:45 UTC, ssieb commented on esphome/components/jandy_watercolors/jandy_watercolors.cpp
> +    call.set_effect(this->get_effect_name_from_id_(this->current_effect_));
Same thing here.

2022-07-31 02:45 UTC, ssieb commented on esphome/components/jandy_watercolors/jandy_watercolors.h
> +      "Fat Tuesday",  "Disco Tech"};
This should be a static array in the .cpp file.

2022-07-31 02:45 UTC, ssieb commented on esphome/components/jandy_watercolors/jandy_watercolors.h
> +static const char *const TAG = "jandy-watercolors";
This needs to be in the .cpp file.

2022-08-17 22:02 UTC, jesserockz commented
@carlos-sarmiento you marked this as ready to review, but you did not address any of the above feedback.

2022-08-17 22:14 UTC, carlos-sarmiento commented
Sorry. Misclicked the button. I asked a few questions on the feedback so I
can implement the changes

On Wed, Aug 17, 2022, 5:03 PM Jesse Hills ***@***.***> wrote:

> @carlos-sarmiento <https://github.com/carlos-sarmiento> you marked this
> as ready to review, but you did not address any of the above feedback.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/3628#issuecomment-1218535412>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAOQRMIHP7PVOFFJFKYQ5HDVZVOR3ANCNFSM53EL4CBA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-18 05:04 UTC, jesserockz commented
@carlos-sarmiento I think you didnt submit your answers to the review. They are probably still "pending" as I do not see them

2022-08-18 05:23 UTC, carlos-sarmiento commented
I was asking for what the syntax for the static array would be on one of @ssieb comments

2022-08-18 05:44 UTC, ssieb commented
> I was asking for what the syntax for the static array would be on one of @ssieb comments

Just put `static` in front of it and move it to the `.cpp` file.

2022-11-25 00:46 UTC, closed without merging