Add text input component
OttoWinter/esphomeyaml pull request #3638
Opened 2022-07-15 13:29 UTC by mauritskorse

# What does this implement/fix?

Adding a input text component (similar to [Home Assistant](https://www.home-assistant.io/integrations/input_text/)). It allows for setting a string by the user through webserver comp front-end (v1). Implementation for v2 webserver front-end and Home Assistant is not done yet.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:
```yaml
input_text:
  - platform: template
    name: "test input text"
    id: "it_1"
    icon: "mdi:text"
    optimistic: true
    internal: false

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-07-16 20:41 UTC, nagyrobi commented
Would it be possible to implement `initial_value` and `restore_value` for this?

2022-07-20 14:17 UTC, mauritskorse commented
> Would it be possible to implement `initial_value` and `restore_value` for this?

Yep, that's already on the roll.

2022-08-22 07:56 UTC, SCratORS commented
I'm waiting for this component. Very lacking...

2022-08-22 11:33 UTC, nielsnl68 commented
Me too, and for sure the HA integration part.

2022-08-25 04:18 UTC, jesserockz commented
This will not work with Home Assistant. 
Integrations cannot create "Input helpers". This needs to wait until there is a core entity type that allows text inputs, just like `number` did for `input_number`

2022-10-21 01:23 UTC, nielsnl68 commented
I hope this can be added soon. I like to use this in my switchplate component.

2022-11-04 10:33 UTC, mauritskorse commented
I have tried to create a new text component for HA, but I can't get it to work yet. Not sure what I'm missing. Maybe someone else could have a try.
Here's the code: https://github.com/home-assistant/core/commit/736f01a70e80b79b87ee465d5509b13397f7686c

2022-11-04 10:52 UTC, mauritskorse commented
> I have tried to create a new text component for HA, but I can't get it to work yet. Not sure what I'm missing. Maybe someone else could have a try. Here's the code: [home-assistant/core@736f01a](https://github.com/home-assistant/core/commit/736f01a70e80b79b87ee465d5509b13397f7686c)

Ah, I already see what I'm missing. Will need to add support for this in [esphome/aioesphomeapi](https://github.com/esphome/aioesphomeapi) as well.

2022-11-17 21:30 UTC, mauritskorse commented
Ok, I have tried it but I run into a problem testing as I can't get my aioesphomeapi branch to be used as dependency for the esphome component in HA. Maybe someone else could have a look:
- https://github.com/home-assistant/core/commit/736f01a70e80b79b87ee465d5509b13397f7686c
- https://github.com/mauritskorse/aioesphomeapi/tree/text-input-component

2022-12-03 09:18 UTC, SeByDocKy commented
Will be ready for the new 2022.12.0 HA release ? :)

2022-12-09 11:25 UTC, mauritskorse commented
> Will be ready for the new 2022.12.0 HA release ? :)

I see that in the HA 2022.12 the `text` component was added. I will have a look whether I can get it to work with ESPHome now.

2022-12-29 11:58 UTC, nielsnl68 requested changes
I made some small comments and suggestion on finalizing the code.

Something i'm not clear of when i just see the yaml code; you are using `min:` and `max:` in it; but what will that tell?  is that the value that is only allowed a number between `min:` and `max:`, or does it tell the size of the allowed string?

2022-12-29 11:58 UTC, nielsnl68 commented on esphome/components/template/text/__init__.py
> +    elif CONF_INITIAL_VALUE not in config:
Why not use the `default=""` in the CONFIG_SCHEMA?

2022-12-29 11:58 UTC, nielsnl68 commented on esphome/components/template/text/__init__.py
> +            cv.Optional(CONF_INITIAL_VALUE): cv.string_strict,
```suggestion
            cv.Optional(CONF_INITIAL_VALUE, default=""): cv.string_strict,
```

2022-12-29 11:58 UTC, nielsnl68 commented on esphome/components/template/text/__init__.py
> +CONF_SET_ACTION = "set_action"
All actions within **ESPHome** start with `on_***` where the `***` is replaced with a description of the action.

from what i understand you could use something like: `CONF_ON_MESSAGE`, `CONF_ON_STATE` or `CONF_ON_VALUE`

2022-12-29 11:58 UTC, nielsnl68 commented on esphome/components/template/text/template_text.h
> +  optional<std::function<optional<std::string>()>> f_;
in ESPHome it is required to use full name method and property names describing the use of it.

2023-01-04 22:19 UTC, foxsam21 commented
I just found this PR and wanted to test it out unfortunately something does not work I'm using dev branch and this config:
```yaml
external_components:
  - source: github://pr#3638
    components: 
    - text

text:
  - platform: template
    name: "My Text Component"
    id: "my_text"
    optimistic: true
```
but when I try to run I get some errors:
```
ERROR Unable to load component text:
Traceback (most recent call last):
  File "<my_path>/esphome/lib/python3.9/site-packages/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<my_config_path>/.esphome/external_components/b41ee16a/esphome/components/text/__init__.py", line 46, in <module>
    cv.OnlyWith(CONF_MQTT_ID, "mqtt"): cv.declare_id(mqtt.MQTTTextComponent),
AttributeError: module 'esphome.components.mqtt' has no attribute 'MQTTTextComponent'
```

2023-01-13 09:21 UTC, nagyrobi commented
Would be nice if this would be interoperable with the upcoming `key_collector` component so that text inputs could be also used for entering PIN codes etc. just like matrix or wiegand keypads can be used.

https://github.com/esphome/esphome-docs/pull/2426
https://github.com/ssieb/custom_components/tree/master/components/key_collector

@ssieb

2023-02-05 16:38 UTC, mauritskorse commented
> I made some small comments and suggestion on finalizing the code.
> 
> Something i'm not clear of when i just see the yaml code; you are using `min:` and `max:` in it; but what will that tell? is that the value that is only allowed a number between `min:` and `max:`, or does it tell the size of the allowed string?

Thanks @nielsnl68!
Considering the `min` and `max`, that is the way the HA text entity addresses these (https://www.home-assistant.io/integrations/input_text/#configuration-variables). I agree that `min_length` and `max_length` are actually better.

Considering your suggestions, I have tried to stay close to the way the other template implementations are done. For example in number template component
https://github.com/esphome/esphome/blob/6b7b0768755b21cca0e4b67515de93b9ca7b3821/esphome/components/template/number/__init__.py#L21

https://github.com/esphome/esphome/blob/6b7b0768755b21cca0e4b67515de93b9ca7b3821/esphome/components/template/number/__init__.py#L58

Of course I don't mind changing according to your suggestions, but my python skill aren't that good that I immediately know what to do...

2023-05-07 00:56 UTC, nielsnl68 commented
I still hope this will be added soon :D

2023-06-08 03:17 UTC, arthurkomatsu commented
This PR looks great, what is the status of this PR? @jesserockz

2023-06-11 22:14 UTC, jesserockz requested changes
Mostly looks good, a few comments below.

https://github.com/esphome/aioesphomeapi PR/branch is missing still.

2023-06-11 22:14 UTC, jesserockz commented on esphome/components/api/api.proto
The `id` in here needs to be updated to start at 97 please to come after the alarm_control_panel which has a PR ready to merge in https://github.com/esphome/aioesphomeapi

2023-06-11 22:14 UTC, jesserockz commented on esphome/components/template/text/__init__.py
> +CONF_SET_ACTION = "set_action"
`set_...` are used for template platforms which is called differently from `on_state` etc

2023-06-11 22:14 UTC, jesserockz commented on esphome/components/template/text/template_text.cpp
> +    }
`std::string` cannot actually be saved reliably inside the preferences as the length is not known/saved, so it cannot be loaded back out properly. We might just have to make it non-restorable for now.

2023-06-11 22:14 UTC, jesserockz commented on esphome/components/template/text/template_text.h
> +  optional<std::function<optional<std::string>()>> f_;
While this is true, this platform is a copy of all the other template platforms. We should go through and update all of them at the same time (individual PRs would be fine too per platform which are easier to merge =)

2023-06-11 22:14 UTC, jesserockz commented on esphome/components/template/text/__init__.py
> +        #        pattern=config[CONF_PATTERN],
Why are these commented?

2023-06-11 22:14 UTC, jesserockz commented on esphome/components/text/text_call.cpp
The Call should have a `validate` function that checks the incoming value meets the requirements of min/max and pattern

2023-06-11 22:14 UTC, jesserockz commented on esphome/components/text/text_traits.h
> +  void set_min_length(int min_length) { min_length_ = min_length; }
Please use `this->` when referring to member variables
```suggestion
  void set_min_length(int min_length) { this->min_length_ = min_length; }
```

2023-06-11 22:14 UTC, jesserockz commented on esphome/components/web_server/web_server.cpp
> +    }
Should this not also include the min/max/pattern?

2023-08-11 14:04 UTC, nielsnl68 commented
What is the status of this PR? Has the HA side still not been added?

2023-09-01 21:46 UTC, EternityForest commented
I think I have everything for restore_value here:
https://github.com/EternityForest/esphome/tree/add-text-input-component

But after writing the code, I discovered I can't easily test with what I've got on hand, this branch does not compile for S2 boards anymore it seems, it just tries and fails to fetch an old patch3 toolchain package.

2023-09-02 03:47 UTC, EternityForest commented
I think I have this synced back up with dev on this branch, with the exception that I'm not able to compile the protobufs using version 3.6.1, haven't had time to set up a VM for that, so this is compiled on 3.12.

Not sure if this work is useful, or if it would just take longer to review than to redo, but I figured I'd give it a
go, if nothing else for a chance to learn about protobufs.

https://github.com/EternityForest/aioesphomeapi/tree/text-input-component
https://github.com/EternityForest/esphome/tree/sync-add-text-input-component

2023-10-25 09:00 UTC, closed without merging