FIX: Unnecessary flash writes by ModbusSwitch component
OttoWinter/esphomeyaml pull request #3648
Opened 2022-07-22 15:30 UTC by jpeletier

# What does this implement/fix?

Modbus switches are unnecessarily updating their status to flash, since the actual state resides in the modbus slave device. 

This save state behavior resides in the base `Switch` class in `publish_state()`, therefore `ModbusSwitch` could not disable saving to flash. In fact, `ModbusSwitch` had to hack its way out of this, being forced to do a dummy read of `initial_state` even though it is not necessary for `ModbusSwitch`.

When using a large number of Modbus switches, these end up unnecessarily updating their status to flash, causing flash wear, or even a boot loop when saving preferences.

This PR addresses the problem the following way:
* Extracts the restore_mode functionality out of `GpioSwitch` and `OutputSwitch`, moving it to `Switch`
* Has `ModbusSwitch` default to `ALWAYS_OFF`
* Refactors `GpioSwitch` and `OutputSwitch` to rely on `Switch` for restore mode configuration.

The change is backward compatible. current `Switch`-based components are not affected. 

However, any `Switch`-based component can optionally leverage restore mode. For example, `ModbusSwitch` could be easily rewritten to actually persist changes to flash, so that the state is restored and held until the first modbus refresh takes place. Other components, such as `TemplateSwitch` could deprecate `restore_state` and such, in favor of the built-in `Switch` restore functionality.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-07-24 22:14 UTC, jesserockz commented on esphome/components/switch/switch.cpp
> +}
Shouldn't this be flipped?

2022-07-24 23:24 UTC, jesserockz requested changes

2022-07-24 23:24 UTC, jesserockz commented on esphome/components/modbus_controller/switch/modbus_switch.cpp
> +void ModbusSwitch::setup() { this->set_restore_mode(switch_::SWITCH_ALWAYS_OFF); }
I think this should be done as a config entry in `modbus/switch`, overriding the default from the `SWITCH_SCHEMA`. This will also need to be done for other "external" switches like `tuya`

2022-07-24 23:24 UTC, jesserockz commented on esphome/components/gpio/switch/gpio_switch.cpp
>    }
This should be moved to `LOG_SWITCH`

2022-07-24 23:55 UTC, jpeletier commented on esphome/components/switch/switch.cpp
> +}
Sorry, forgot to push one last commit just after the PR. Take a look now.

2022-07-24 23:58 UTC, jpeletier commented on esphome/components/modbus_controller/switch/modbus_switch.cpp
> +void ModbusSwitch::setup() { this->set_restore_mode(switch_::SWITCH_ALWAYS_OFF); }
I actually started doing that but then realized I had to change `ModbusSwitch` to actually honor restore modes, which didn't make much sense for that component: as soon as it refreshes, any restored state will be gone. This configures `ModbusSwitch` to behave the same way it currently does.

2022-08-01 11:26 UTC, jpeletier commented on esphome/components/gpio/switch/gpio_switch.cpp
>    }
Done

2022-09-26 21:16 UTC, jpeletier commented
@jesserockz Can we finish this review? I had recently to rebase due to a number of conflicts, I would like to avoid too much divergence, this fix is important to avoid flash wear. Thanks!

2022-10-17 21:24 UTC, jesserockz approved these changes

2022-10-25 13:31 UTC, jpeletier commented
Here is the PR for the related documentation: https://github.com/esphome/esphome-docs/pull/2381

2022-11-28 09:15 UTC, nagyrobi commented
My relay card operation is not very consistent so I'd rather rely on ESPHome restore functionality to always forcefully restore the modbus switches to what they were previously. For example when there's a power cycle, the Modbus device doesn't restore the relays states by itself, it would be very handy to restore them from ESPHome.

Do I assume correctly that with `RESTORE_DEFAULT_OFF` I could achieve what I want?

2022-11-28 19:38 UTC, nagyrobi commented
> Do I assume correctly that with `RESTORE_DEFAULT_OFF` I could achieve what I want?

Answering myself, no. Tested this PR with:

```
external_components:
  - source: github://pr#3648
    components: [ switch, output, modbus_controller, gpio ]
    refresh: 1min
```
And config:
```
switch:
- platform: modbus_controller
  modbus_controller_id: relay24
  id: heat_00_sw
  name: 00 switch
  register_type: coil
  address: 0
  bitmask: 1
  restore_mode: RESTORE_DEFAULT_OFF
```
1. Turned the the switch on
2. Waited 2 minutes
3. Power-cycled the entire circuit (modbus relay card and ESPHome node)
4. Result: switch didn't turn back on as exepcted with `RESTORE_DEFAULT_OFF`

The expectation was that the board should have saved the switch state to the flash (didn't see an entry in the log about that, either).

2022-11-29 12:35 UTC, jpeletier commented
Hello @nagyrobi,

Indeed this PR does not do what you expect. Note that it was not the original purpose of this PR, which was to fix some flash writes that were not applicable to the modbus component and that were causing unnecessary flash wear.

However, this PR does lay the groundwork to quickly build the feature you need. Hopefully I can do that once this is merged.

In the meantime, I have updated the documentation: https://deploy-preview-2381--esphome.netlify.app/components/switch/modbus_controller.html based on your feedback, to avoid confusion.

Regards

2022-11-29 16:16 UTC, nagyrobi commented
> this PR does lay the groundwork to quickly build the feature you need. Hopefully I can do that once this is merged

I would really appreciate if it would be possible to merge all in one, in case it's not too complicated. Since I have a real use case, I can contribute with real world tests in exchange for your work.

2022-11-29 16:28 UTC, jpeletier commented
This PR is already too big, and those requirements out of its scope. Let's push it to be merged as soon as possible, so we can add that functionality.

In the meantime, a boot script should fix your problem: https://esphome.io/components/esphome.html#on-boot

2022-11-29 21:04 UTC, jesserockz approved these changes

2022-11-29 21:05 UTC, merged

2022-11-29 21:23 UTC, jpeletier commented
Thanks @jesserockz 

@nagyrobi  can you test https://github.com/esphome/esphome/pull/4122 and see if it solves your issue?

2022-12-06 07:24 UTC, kbx81 commented
@jpeletier could you have a look at this? https://github.com/esphome/issues/issues/3878 😇