Fix Nextion send_command_ race condition
OttoWinter/esphomeyaml pull request #3657
Opened 2022-07-26 06:02 UTC by kbx81

# What does this implement/fix?

Given some specific set of circumstances, there appears to be a race condition that will occur which prevents communication with Nextion displays. I still don't understand exactly _why_ it occurs but _I think_ it is somehow related to the component's accessing of the display's associated (software?) UART and/or its buffer.

I don't like this fix...but it does seem to alleviate the issue as best I can tell and it's pretty trivial in terms of practical impact. I _think_ it has something to do with the soft UART needing to pick up the buffer contents before control is returned to the main loop...but this is largely speculation...

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**
 - fixes https://github.com/esphome/issues/issues/3225
 - fixes https://github.com/esphome/issues/issues/3335

The behavior described in the above issues are what prompted me to even begin to look into this.

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266 (D1 Mini)

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder). **N/A**

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs). **N/A**

2022-07-26 06:22 UTC, kbx81 commented on esphome/components/nextion/nextion.cpp
> +  delay(3);
Is there a way I can wrap this so it is only included when a soft-UART is in use?

2022-07-26 18:06 UTC, kbx81 commented
For those watching from home, you can test this PR by adding:

```yaml
external_components:
  - source: github://pr#3657
    components: [ nextion ]
```

...into your ESPHome config. 🙂

2022-07-30 09:36 UTC, s00500 commented
this closes https://github.com/esphome/issues/issues/3225

Thanks a lot =D

2022-07-31 06:14 UTC, anatoly-savchenkov commented
This fixes communication with Nextion over a software UART for me (https://github.com/esphome/issues/issues/3225 and https://github.com/esphome/issues/issues/3335). Thank you!

But now I have communication issues at VERY_VERBOSE log level. Successful initial handshake with Nextion can happen minutes after boot up or even not happen at all or can happen instantly. Once screen is detected it works well.

2022-08-04 03:44 UTC, kbx81 commented
> This fixes communication with Nextion over a software UART for me ([esphome/issues#3225](https://github.com/esphome/issues/issues/3225) and [esphome/issues#3335](https://github.com/esphome/issues/issues/3335)). Thank you!
> 
> But now I have communication issues at VERY_VERBOSE log level. Successful initial handshake with Nextion can happen minutes after boot up or even not happen at all or can happen instantly. Once screen is detected it works well.

If I remember correctly, the Nextion component dumps _a lot_ of logging when `VERY_VERBOSE` is enabled -- I've had trouble with this in the past, too...even random crashes. I recommend disabling `VERY_VERBOSE` logging unless you _absolutely_ need it enabled for troubleshooting a specific issue.

2022-08-06 16:10 UTC, anatoly-savchenkov commented
I spent some time looking at this problem this afternoon. The first thing which contributes to the problem is the "bkcmd=3" command which Nextion component sends at the setup state. Nextion instruction set manual says:
bkcmd: Sets the level of Return Data on commands processed over Serial.
min 0, max 3, default 2
– Level 0 is Off – no pass/fail will be returned
– Level 1 is OnSuccess, only when last serial command successful.
– Level 2 is OnFailure, only when last serial command failed
– Level 3 is Always, returns 0x00 to 0x23 result of serial command.

This causes Nextion to reply to every command which we send to display, producing a lot of RX traffic. At the same time, Nexttion component does not serialize commands. It can push many commands to UART and process replies as they are received. Typical interaction over UART is below (code has a `delay(3)` from this PR plus my custom logging):
```
[E][nextion:033]: [0007] -> bkcmd=3
[E][nextion:033]: [0008] -> dim=1
[E][nextion:033]: [0009] -> page 0
[E][nextion:033]: [0010] -> thup=1
[E][nextion:299]: [0005] <- 01.FF.FF.FF.01.FF.FF.FF.01.FF.FF.FF.66.00.FF.FF (16) (ps)
[E][nextion:299]: [0006] <- 01.FF.FF.FF.01.FF.FF.FF.66.00.FF.FF (12) (ps)
[E][nextion:299]: [0007] <- 01.FF.FF.FF.66.00.FF.FF (8) (ps)
[E][nextion:033]: [0011] -> page loading_page
[E][nextion:033]: [0012] -> temperature.lock_mode.val=0
[E][nextion:299]: [0008] <- 66.00.FF.FF.01.FF.FF.FF.01.FF.FF.FF.66.0C.FF.FF.01.FF.FF.FF (20) (ps)
[E][nextion:299]: [0009] <- 01.FF.FF.FF.66.0C.FF.FF.01.FF.FF.FF (12) (ps)
[E][nextion:299]: [0010] <- 66.0C.FF.FF.01.FF.FF.FF (8) (ps)
```
Incoming data is actually a content of command_data_ variable. What we can see here is: (1) how replies are being collected and processed; (2) how UART data is being corrupted / dropped.

The first observation gives us the clear fact that Nextion component uses UART in full duplex mode.

The latter is the most interesting. See reception 5 (number in square brackets at the beginning of the log line with <- symbol). Where is the third FF in 66 00 FF FF reply? It's dropped. Baud rate is 9600, so a character comes every 1/9600 second, assume each 1 ms for simplicity. We sent 4 commands, so it triggered 12 ms of pure delay (plus, compute time around), which was enough to receive 16 bytes.

Two questions appear here: (1) how about the time we spent sending those 4 commands, it should be at least 36 ms and (2) where is the lost byte?

Going deeper into ESP8266SoftwareSerial implementation, we see that `write_byte` is implemented as
```
  {
    InterruptLock lock;
    uint32_t wait = this->bit_time_;
    const uint32_t start = arch_get_cpu_cycle_count();
    // Start bit
    this->write_bit_(false, &wait, start);
    for (int i = 0; i < this->data_bits_; i++) {
      bool bit = data & (1 << i);
      this->write_bit_(bit, &wait, start);
      if (need_parity_bit)
        parity_bit ^= bit;
    }
    if (need_parity_bit)
      this->write_bit_(parity_bit, &wait, start);
    // Stop bit
    this->write_bit_(true, &wait, start);
    if (this->stop_bits_ == 2)
      this->wait_(&wait, start);
  }
  ```
Going even deeper into the implementation of `InterruptLock` we find that the whole block will be executed with interrupts disabled (yes, almost 1 ms with no interrupts). Looking at `ESP8266SoftwareSerial::gpio_intr()` we find the same. We spend almost 1 ms inside the interrupt handler, which is triggered by the start bit edge.

So, `delay(3)` after sending a command gives us enough time to receive 3 full bytes (remember we need at least 4 per reply) and compute time before we send the next command gives us enough time to start receiving the 4th byte and thus be blocked till we receive it completely.

But some commands generate a 5 byte reply (like page command above). Where is the 5th byte? It's lost because we are blocked in `write_byte()` sending the next command with interrupts disabled, so we just miss those interrupts.

**So, we've concluded that ESP8266SoftwareSerial is not compatible with full duplex operations which we heavily rely on in Nextion.**

What to do with this? First of all, why do we need bkcmd=3 mode? We simply delete commands from the queue upon reception of a confirmation. Secondly, I really don't see any benefit of implementing Nextion code relying on full duplex operations. It should not be slower to send commands one by one and wait for a reply after each command. But we still have Nextion initiated transmissions which can clash with our commands and thus be skipped / corrupted if Soft UART is used.

The only clear solution is to re-implement Soft UART supporting full duplex mode. Is that feasible? I need to think / google more. This will be an interesting piece of hard realtime code.

Another possible solution is to minimize the surface of the problem. I think, serializing commands and replies probably with bkcmd=0 (or 2) would be an acceptable alternative to the new Soft UART implementation.

And the very last (ugly ?) fix is to add an extra `delay(1)` to the page command (and to every other command where reply is more than 4 bytes) in the case of a Soft UART. Extra delay in ms should be equal to reply size in bytes - 4 (assuming 9600 baud rate).

The last 2 solutions will not eliminate the problem of randomly missing events coming from Nextion.

**Generic recommendation so far is not to use a Software UART with Nextion displays.**

2022-08-06 20:19 UTC, kbx81 commented
@anatoly-savchenkov _thank you_ for looking into this! Your explanation makes sense and more or less confirms my suspicion about the softUART. _This_ is the type of examination I wanted to do myself but I lack the time and energy at the moment and have also been busy with some other things (such as `sprinkler`). 😄

In the short-term, it would probably make the most sense to update the docs to more effectively call this out. Right now there is a single line that's easy to miss: `Without a hardware uart make sure to set the baud rate to 9600.` We should probably add a "warning" call-out near the top of [the document](https://next.esphome.io/components/display/nextion.html) to emphasize that the use of a hardware UART is more or less required. 😄

2022-08-14 13:02 UTC, anatoly-savchenkov commented
https://github.com/plerup/espsoftwareserial claims to implement full duplex software UART working well up to 56K baud rate on ESP8266. It turned to be quite simple to integrate it instead of ESP8266SoftwareSerial class in ESPHome. So, I did that in https://github.com/anatoly-savchenkov/esphome/tree/espsoftwareserial_uart. And yes it somewhat works without delay(3). But bit error rate is quite high at 9600 bauds, way higher than with the workaround in this PR. Plus I see memory leaks, although I didn't check where those occurs (in the EspSoftwareSerial itself or in Nextion caused by higher bit error rate)

I also added logging of UART traffic (the one I used for the debugging above). A typical communication log is below. See the first byte of 18 or 1E instead of expected 1A. 
```
[13:08:14][E][nextion:033]: [0050] -> uptime.txt="5m"
[13:08:14][E][nextion:298]: [0084] <- 18 (ps)
[13:08:14][E][nextion:298]: [0085] <- 18.FF.FF (ps)
[13:08:14][E][nextion:298]: [0086] <- 18.FF.FF.FF (ps)
[13:08:14][W][nextion:749]: Received unknown event from nextion: 0x18
[13:09:14][E][nextion:033]: [0051] -> uptime.txt="6m"
[13:09:14][E][nextion:298]: [0087] <- 18 (ps)
[13:09:14][E][nextion:298]: [0088] <- 18.FF.FF (ps)
[13:09:14][E][nextion:298]: [0089] <- 18.FF.FF.FF (ps)
[13:09:14][W][nextion:749]: Received unknown event from nextion: 0x18
[13:09:29][E][nextion:033]: [0052] -> signal_fill.val=1
[13:09:29][E][nextion:298]: [0090] <- 18.FF (ps)
[13:09:29][E][nextion:298]: [0091] <- 18.FF.FF.FF (ps)
[13:09:29][E][nextion:298]: [0092] <- 18.FF.FF.FF (ps)
[13:09:29][W][nextion:749]: Received unknown event from nextion: 0x18
[13:09:39][E][nextion:033]: [0053] -> signal_fill.val=2
[13:09:39][E][nextion:298]: [0093] <- 18.FF (ps)
[13:09:39][E][nextion:298]: [0094] <- 18.FF.FF.FF (ps)
[13:09:39][E][nextion:298]: [0095] <- 18.FF.FF.FF (ps)
[13:09:39][W][nextion:749]: Received unknown event from nextion: 0x18
[13:09:49][E][nextion:033]: [0054] -> signal_fill.val=1
[13:09:49][E][nextion:298]: [0096] <- 1E.FF (ps)
[13:09:49][E][nextion:298]: [0097] <- 1E.FF.FF.FF (ps)
[13:09:49][E][nextion:298]: [0098] <- 1E.FF.FF.FF (ps)
[13:09:49][W][nextion:424]: Nextion reported parameter quantity invalid!
[13:09:59][E][nextion:033]: [0055] -> signal_fill.val=2
[13:09:59][E][nextion:298]: [0099] <- 18.FF (ps)
[13:09:59][E][nextion:298]: [0100] <- 18.FF.FF.FF (ps)
[13:09:59][E][nextion:298]: [0101] <- 18.FF.FF.FF (ps)
[13:09:59][W][nextion:749]: Received unknown event from nextion: 0x18
[13:10:14][E][nextion:033]: [0056] -> uptime.txt="7m"
[13:10:14][E][nextion:298]: [0102] <- 18 (ps)
[13:10:14][E][nextion:298]: [0103] <- 18.FF.FF (ps)
[13:10:14][E][nextion:298]: [0104] <- 18.FF.FF.FF (ps)
[13:10:14][W][nextion:749]: Received unknown event from nextion: 0x18
```

@kbx81, could you please give my branch a try on your side. Please compile your app with WARN logging to see only UART IO and warnings in Nextion. The goal is to confirm operations without delay(3) and check for bit error rate with your display.

Meanwhile I'll ask authors of EspSoftwareSerial for ideas to try.

2022-08-15 03:54 UTC, kbx81 commented
Nice, thanks @anatoly-savchenkov -- I should be able to scrape together some time to test this week. 😄

2022-11-14 08:05 UTC, s00500 commented
Not stale

2023-02-13 08:13 UTC, s00500 commented
still not stale...

2025-09-03 19:48 UTC, jesserockz requested changes
Still relevant?

2025-09-03 20:47 UTC, s00500 commented
hm, been a while but still using it like that, are there any other changes that would have addressed this issue ?

2025-09-03 22:34 UTC, kbx81 commented
@edwardtfn has done ** a lot** of work on the Nextion component in ESPHome since I opened this PR and I'm not sure if any of the subsequent changes have perhaps mitigated this specific issue in some way.

In general, we recommend **not** using an 8266 for ESPHome at this point -- for personal projects, it's generally easy to switch to an ESP32 or variant. ESP32s have multiple UARTs and do not require use of SoftwareSerial; thus they are not impacted by the race condition this PR works around.

2025-09-05 04:34 UTC, edwardtfn commented
Sorry, I couldn't look at this yet, but I promise to look during this weekend. 😉

2025-10-06 13:42 UTC, edwardtfn commented on esphome/components/nextion/nextion.cpp
> +  delay(3);
I don't see any damage on adding a 3msec delay here, but I believe the issue you are trying to solve with this was probably solved with this PR:
- #7948

2026-01-22 02:10 UTC, closed without merging