Added new functions for use with upcoming switchplate component.
OttoWinter/esphomeyaml pull request #3658
Opened 2022-07-27 00:55 UTC by nielsnl68

- added new graphic functions for use with  upcoming switchplate component
- added option to clib a part of the screen to draw inside (1)
- add color blending functions and option to set transparant color. (2)
- removed unneeded draw_pixel_at calls while doing a filedl_rectangle()

(1) clipping will not work on the clear() and fill() functions (for now ???)
(2) work in progress

# What does this implement/fix?

Add a couple of graphics function in the Displaybuffer class to be used in the upcoming Switchplate component.
extending the (filled_)rectangle function with the option to draw rounded and added new (filled_)triangle functions
Also it is now possible to set a area where in the screen can be modified (Clipping).
Also there are some color blending function that maybe need to be moved to the color.h/.cpp file later.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  - id: my_display
    platform: ili9341
    model: TFT 2.4
    cs_pin: 5
    dc_pin: 16
    rotation: 90

    lambda: |-
      it.fill(id(my_green));
      it.print(2, 2, id(my_font), id(my_white), TextAlign::TOP_LEFT, "Woonkamer lampen");
      //it.strftime(210, 2, id(my_font), "%d/%m %H:%M", id(the_time).now() );
      //it.rectangle(    50, 50 ,228, 150, id(my_green));
      
      it.set_clipping( 50, 50 ,228, 150);
      it.filled_rectangle(0, 0, 320, 240,  id(my_black));

      it.rectangle(3, 28, 99, 99, id(my_blue));
      it.rectangle(3,136, 99, 99, 8, id(my_red));

      it.filled_rectangle(110, 28, 99, 99, id(my_blue));
      it.filled_rectangle(110,136, 99, 99, 7,  id(my_red));

      it.triangle(       268,  28,  218, 128, 318, 128, id(my_blue));
  
      it.filled_triangle(268, 136,  218, 236, 318, 236, id(my_red));
  
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-07-31 19:53 UTC, jesserockz commented on esphome/components/display/display_buffer.h
> +#define USE_EXTENDEDDRAW
Whats the point of the ifdefs if this is always defined here?

2022-08-02 18:46 UTC, nielsnl68 commented on esphome/components/display/display_buffer.h
> +#define USE_EXTENDEDDRAW
Ha yes, good point i added, it just there from while i was testing. I needed a point to find the changes i made and to debug the code.
While preparing the PR i was thinking, maybe it can be for use when the added code is not wanted for the normal use outside my upcoming SwitchPlate component.

2022-08-02 19:26 UTC, DrunkPyromaniac requested changes
Looks good; just a few suggestions.

2022-08-02 19:26 UTC, DrunkPyromaniac commented on esphome/components/display/display_buffer.cpp
> +  int32_t err = delta_x + delta_y;
`dx` is a standard shorthand for `delta_x`, so not only is the variable name longer, but the changes increase the diff set, which makes it harder to see what's changed.  You should revert these changes, here and below.

2022-08-02 19:26 UTC, DrunkPyromaniac commented on esphome/components/display/display_buffer.cpp
> +bool DisplayBuffer::is_color_equal(Color a, Color b) { return a.r == b.r && a.g == b.g && a.b == b.b; }
`Color` already has a = operator to compare two colors.  Can you not use that?

2022-08-02 19:26 UTC, DrunkPyromaniac commented on esphome/components/display/display_buffer.cpp
> +}
Given that you've created a `Point`, I'd suggest creating additional function signatures that take a `Point` instead of an (x, y) pair, then this can be greatly simplified:
```suggestion
void DisplayBuffer::quad(Point *points, Color color) {
  this->line(points[0], points[1], color);
  this->line(points[1], points[2], color);
  this->line(points[2], points[3], color);
  this->line(points[3], points[0], color);
}
```

2022-08-02 19:26 UTC, DrunkPyromaniac commented on esphome/components/display/display_buffer.cpp
> +}
Same as above:
```suggestion
void DisplayBuffer::filled_quad(Point *points, Color color) {
  // Break down quadrilateral into two triangles
  this->filled_triangle(points[0], points[1], points[2], color);
  this->filled_triangle(points[2], points[0], points[3], color);
}
```

2022-08-02 19:53 UTC, nielsnl68 commented on esphome/components/display/display_buffer.cpp
> +bool DisplayBuffer::is_color_equal(Color a, Color b) { return a.r == b.r && a.g == b.g && a.b == b.b; }
I agree, this function could be removed indeed.

2022-08-02 20:00 UTC, nielsnl68 commented on esphome/components/display/display_buffer.cpp
> +}
can you explain more, could you tell how that new function should be look like?

2022-08-02 20:12 UTC, DrunkPyromaniac commented on esphome/components/display/display_buffer.cpp
> +}
You'd create a function something like this:
```cpp
void DisplayBuffer::line(Point &pt1, Point &pt2, Color color,) {
  this->line(pt1.x, pt1.y, pt2.x, pt2.y, color);
}

2022-08-02 21:51 UTC, nielsnl68 commented on esphome/components/display/display_buffer.cpp
> +}
okey, i got you, I will add it when i see more then 5 thumbs-up otherwise i go the other way around and remove the point version in favor of:
```cpp
void qaud(int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, int16_t x3, int16_t y3, Color color = COLOR_ON) { 
  ...
}
```

2022-08-08 06:45 UTC, nielsnl68 commented on esphome/components/display/display_buffer.cpp
> +}
I have removed the point structure from the PR changes,

2022-08-08 06:47 UTC, nielsnl68 commented on esphome/components/display/display_buffer.cpp
> +}
I did something similar as this, by removing the `Point` structure.

2022-08-18 10:31 UTC, closed without merging