Add support for V2 of the waveshare 5.83in e-paper display.
OttoWinter/esphomeyaml pull request #3660
Opened 2022-07-28 16:07 UTC by cooki35

# What does this implement/fix?

Add code to support the WaveShare 5.83in black & white displays with "V2" stickers on them.
The resolution of the V2 version changed (from 600x448) to 648x480.
The init and display code differ from the original 5.83in version.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [esphome/issues/issues/2121](https://github.com/esphome/issues/issues/2121)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

The display was connected with the WaveShare e-Paper Driver HAT Rev2.2 and via SPI to an ESP32 (esp32doit-devkit-v1).
The switches of the driver HAT were set to:
- Display Config: B (0.47R)
- Interface Config 0 (4-line SPI)

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  id: spi001

display:
  - platform: waveshare_epaper_test
    spi_id: spi001
    cs_pin: GPIO5
    dc_pin: GPIO19
    busy_pin: GPIO16
    reset_pin: GPIO17
    model: 5.83inv2
    update_interval: 30s
    reset_duration: 2ms
    id: eink
    lambda: |-
      it.line(10, 10, 630, 10, COLOR_ON);
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-10-27 07:51 UTC, ssieb requested changes

2022-10-27 07:51 UTC, ssieb commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +  */
Why is this commented out?  If it's not needed, then just remove it.

2022-10-29 18:26 UTC, TheStork239 commented
Is work still being done on this?  It would be great to get it over the line, so that the newer 5.83in displays would be usable.  
@cooki35 is the change that @ssieb requested doable?

2022-12-29 08:07 UTC, TheStork239 commented
This looks like it would be ready to go, apart from the one change requested by the review.
@cooki35, are you planning on making that edit to move this PR forward? It would be great to have the 5.83 v2 supported.

2023-01-16 13:56 UTC, oisaak commented
Just tested it, works great, thanks @cooki35

2023-03-21 14:06 UTC, cooki35 commented
The changes sound reasonable, I forgot to delete the comments. I removed them. Thanks @ssieb !

2023-05-01 21:35 UTC, jesserockz approved these changes

2023-05-01 21:36 UTC, merged