Added support for setting the current animation frame in the `Display` component
OttoWinter/esphomeyaml pull request #3681
Opened 2022-08-03 08:54 UTC by davestubbs

# What does this implement/fix?

This allows users of the `Display` component to select an explicit animation frame, in addition to the existing `next_frame` and `prev_frame`.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
lambda: |-
  id(animated_git).set_frame(5);
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-08-06 17:29 UTC, DrunkPyromaniac requested changes

2022-08-06 17:29 UTC, DrunkPyromaniac commented on esphome/components/display/display_buffer.cpp
> +}
We should handle calling this with a negative number, which I feel should set it to `this->animation_frame_count_ - frame`.

2022-08-06 19:26 UTC, davestubbs commented
Done. Is that roughly what you meant?

2022-08-06 19:37 UTC, davestubbs commented
Is this correct?

```
void Animation::next_frame() {
  this->current_frame_++;
  if (this->current_frame_ >= animation_frame_count_) {
    this->current_frame_ = 0;
  }
}
```

Should it be:

2022-08-06 19:41 UTC, davestubbs commented
Not related to this change, but is this correct:
```cpp
void Animation::next_frame() {
  this->current_frame_++;
  if (this->current_frame_ >= animation_frame_count_) {
    this->current_frame_ = 0;
  }
}
```

Should it be this?
```cpp
  if (this->current_frame_ >= animation_frame_count_ - 1) {
```

2022-08-07 19:47 UTC, jesserockz approved these changes

2022-08-07 19:49 UTC, DrunkPyromaniac approved these changes
> @DrunkPyromaniac: is that roughly what you meant?
Yeah.  Looks good.

2022-08-07 19:49 UTC, jesserockz requested changes

2022-08-07 19:49 UTC, jesserockz commented on esphome/components/display/display_buffer.cpp
> +    if (frame) {
This is `true` for any non-zero

2022-08-07 19:59 UTC, davestubbs commented on esphome/components/display/display_buffer.cpp
> +    if (frame) {
How do you propose I change it? I'm not sure how to make that clearer. `frame` could be negative at that point, at which point I'll update `current_frame_` to `animation_frame_count_ - abs(frame)` as suggested by @DrunkPyromaniac.

2022-08-07 20:05 UTC, DrunkPyromaniac commented on esphome/components/display/display_buffer.cpp
> +    if (frame) {
Just change it to `if (frame > 0)`.

2022-08-07 20:08 UTC, DrunkPyromaniac approved these changes

2022-08-07 20:10 UTC, jesserockz commented on esphome/components/display/display_buffer.cpp
> +    if (frame > 0) {
Shouldnt you be able to set to frame 0 too?

```suggestion
    if (frame >= 0) {
```

2022-08-07 20:11 UTC, DrunkPyromaniac commented on esphome/components/display/display_buffer.cpp
> +    if (frame > 0) {
D'oh, yeah.

2022-08-07 20:12 UTC, davestubbs commented on esphome/components/display/display_buffer.cpp
> +    if (frame > 0) {
You most definitely should. Thanks! Not sure how I missed that :)

2022-08-08 00:42 UTC, jesserockz approved these changes

2022-08-08 00:49 UTC, jesserockz commented
@davestubbs Could you make a docs PR and add a small example to the Animation section?

2022-08-08 22:28 UTC, merged