Esp32 pulsecounter optional pcnt
OttoWinter/esphomeyaml pull request #3691
Opened 2022-08-07 13:30 UTC by RoboMagus

# What does this implement/fix?

Make use of hardware `pcnt` optional for pulsecounter sensors on ESP32.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino
    version: latest

sensor:
  - platform: pulse_counter
    pin:
      number: D3
    name: "Pulse Counter"
    update_interval: 5min
    accuracy_decimals: 3
    use_pcnt: false
    internal_filter: 500ms

  - platform: pulse_counter
    pin:
      number: D6
    name: "PCNT Pulse Counter"
    update_interval: 5min
    accuracy_decimals: 3
    use_pcnt: true
    internal_filter: 13us
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-08-08 23:31 UTC, jesserockz requested changes

2022-08-08 23:31 UTC, jesserockz commented on esphome/components/pulse_counter/sensor.py
> +            cv.Optional(CONF_USE_PCNT, default=CORE.is_esp32): cv.boolean,
You need to use use `cv.SplitDefault` here

2022-08-09 07:20 UTC, RoboMagus commented on esphome/components/pulse_counter/sensor.py
> +            cv.Optional(CONF_USE_PCNT, default=CORE.is_esp32): cv.boolean,
Thanks Jesse,
I've updated to contain defaults for both esp8266 and esp32. This is not really in line with how it's used in other places, in favor of having compatible partial configs between esp8266 and esp32. E.g. to avoid having to remove a moot `use_pcnt: false` for esp8266 configurations.

2022-08-09 07:20 UTC, jesserockz commented on esphome/components/pulse_counter/sensor.py
> +            cv.SplitDefault(CONF_USE_PCNT, esp32=true, esp8266=false): cv.boolean,
```suggestion
            cv.SplitDefault(CONF_USE_PCNT, esp32=True): cv.boolean,
```

2022-08-09 08:10 UTC, RoboMagus commented on esphome/components/pulse_counter/sensor.py
> +            cv.SplitDefault(CONF_USE_PCNT, esp32=true, esp8266=false): cv.boolean,
I.m.o. it would be best to keep the esp8266 default stated explicitly here as well, as otherwise defaults would also have to be stated on [L46](https://github.com/RoboMagus/esphome/blob/63823555df453c6830c61aebafdb98e396f8a866/esphome/components/pulse_counter/sensor.py#L46) and [L127](https://github.com/RoboMagus/esphome/blob/63823555df453c6830c61aebafdb98e396f8a866/esphome/components/pulse_counter/sensor.py#L127). (Otherwise it defaults to None instead)

2022-08-09 20:07 UTC, jesserockz commented on esphome/components/pulse_counter/sensor.py
> +            cv.SplitDefault(CONF_USE_PCNT, esp32=true, esp8266=false): cv.boolean,
The reason I removed the `esp8266` key is because this setting will not apply to esp8266. It should not be false, it should be None and handled as such in other places. in `validate_internal_filter` the code should check `if CORE.is_esp32` and ignore checking the config value.

The reason for this is that if someone does a config validation, it will show `use_pcnt: false` because it is a default instead of omitting that line entirely for esp8266

2022-08-11 07:00 UTC, RoboMagus commented on esphome/components/pulse_counter/sensor.py
> +            cv.SplitDefault(CONF_USE_PCNT, esp32=true, esp8266=false): cv.boolean,
ah, that makes sense. Thanks for clarifying. 
I'll see if I can rework this some time later today.

2022-08-30 21:55 UTC, jesserockz approved these changes

2022-08-30 21:58 UTC, jesserockz commented on esphome/components/pulse_counter/sensor.py
> +    var = await sensor.new_sensor(config, config.get(CONF_USE_PCNT))
Does this work with esp8266 and `None` being returned?

2022-08-31 07:22 UTC, RoboMagus commented on esphome/components/pulse_counter/sensor.py
> +    var = await sensor.new_sensor(config, config.get(CONF_USE_PCNT))
This does work, yes. When `None` is passed the constructor will receive no arguments, and thus fall back to the constructor argument default value: `PulseCounterSensor(bool hw_pcnt = false)`

2022-09-02 01:21 UTC, jesserockz approved these changes

2022-09-02 01:22 UTC, merged

2022-09-14 01:36 UTC, glmnet commented
I'm getting a boot loop with this PR, can be reproduced with a bare esp32 and this yaml below (of course, previous code works ok)

I strongly recommend reverting this PR if somebody other than me can reproduce this at least until further investigation is done. Thanks

```yaml
---
esphome:
  name: test-esp32

esp32:
  framework:
    type: arduino

  board: nodemcu-32s

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

captive_portal:

ota:
api:

logger:
sensor:
  - platform: pulse_counter
    pin: GPIO34
    id: engine_rpm_instant
    update_interval: 300ms
    count_mode:
      falling_edge: INCREMENT
      rising_edge: DISABLE
```

dump

```
Compiling .pioenvs\test-esp32\FrameworkArduino\wiring_pulse.c.o
Compiling .pioenvs\test-esp32\FrameworkArduino\wiring_shift.c.o
Archiving .pioenvs\test-esp32\libFrameworkArduino.a
Linking .pioenvs\test-esp32\firmware.elf
Retrieving maximum program size .pioenvs\test-esp32\firmware.elf
Checking size .pioenvs\test-esp32\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  12.7% (used 41692 bytes from 327680 bytes)
Flash: [=====     ]  49.8% (used 914742 bytes from 1835008 bytes)
Building .pioenvs\test-esp32\firmware.bin
esptool.py v3.1
Merged 1 ELF section
esp32_create_combined_bin([".pioenvs\test-esp32\firmware.bin"], [".pioenvs\test-esp32\firmware.elf"])
esptool.py v3.3.1
Wrote 0xef5a0 bytes to file C:\git\esphome_devices\experiments\.esphome\build\test-esp32\.pioenvs\test-esp32/firmware-factory.bin, ready to flash to offset 0x0
============================================================================================================= [SUCCESS] Took 40.95 seconds =============================================================================================================
INFO Successfully compiled program.
Found multiple options, please choose one:
  [1] COM9 (Silicon Labs CP210x USB to UART Bridge (COM9))
  [2] Over The Air (test-esp32.local)
(number): 1
esptool.py v3.3.1
Serial port COM9
Connecting........................
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 8c:aa:b5:8b:2a:b4
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash will be erased from 0x00010000 to 0x000effff...
Flash will be erased from 0x00001000 to 0x00005fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Compressed 914848 bytes to 521108...
Wrote 914848 bytes (521108 compressed) at 0x00010000 in 12.9 seconds (effective 568.4 kbit/s)...
Hash of data verified.
Compressed 17104 bytes to 11191...
Wrote 17104 bytes (11191 compressed) at 0x00001000 in 0.6 seconds (effective 228.1 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 144...
Wrote 3072 bytes (144 compressed) at 0x00008000 in 0.1 seconds (effective 273.0 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.2 seconds (effective 390.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
INFO Successfully uploaded program.
INFO Starting log output from COM9 with baud rate 115200
[22:23:00]ts Jun  8 2[I][logger:243]: Log initialized
[22:23:00][C][ota:461]: There have been 5 suspected unsuccessful boot attempts.
[22:23:00][D][esp32.preferences:113]: Saving 1 preferences to flash...
[22:23:00][D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[22:23:00][I][app:029]: Running through setup()...
[22:23:00][C][pulse_counter:147]: Setting up pulse counter 'engine_rpm_instant'...
[22:23:00][C][pulse_counter:061]:     PCNT Unit Number: 0
[22:23:00][C][pulse_counter:107]:     Filter Value: 13us (val=1023)
[22:23:00][C][wifi:037]: Setting up WiFi...
[22:23:00][D][wifi:384]: Sta.W\xcb\xeb\x81scan...
[22:23:00][D][pulse_counter:180]: 'engine_rpm_instant': Total : 0 pulses
[22:23:00]Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
[22:23:00]Core 1 register dump:
[22:23:00]PC      : 0x400d7e89  PS      : 0x00060430  A0      : 0x800d81ef  A1      : 0x3ffb1d20  
WARNING Decoded 0x400d7e89: esphome::sensor::Filter::input(float) at c:\users\glmne\.platformio\packages\toolchain-xtensa32@2.50200.97\xtensa-esp32-elf\include\c++\5.2.0\ext/new_allocator.h:105
[22:23:00]A2      : 0x55c000e8  A3      : 0x00000000  A4      : 0x000000b4  A5      : 0x3f4029c3  
[22:23:00]A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x3ffb1cd0  
[22:23:00]A10     : 0x3ffb8254  A11     : 0x00000000  A12     : 0x3f402779  A13     : 0x000000b4  
[22:23:00]A14     : 0x3f4029c3  A15     : 0x00000000  SAR     : 0x00000004  EXCCAUSE: 0x0000001c  
[22:23:00]EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  
[22:23:00]
[22:23:00]ELF file SHA256: 0000000000000000
[22:23:00]
[22:23:00]Backtrace: 0x400d7e89:0x3ffb1d20 0x400d81ec:0x3ffb1d50 0x400d7dbb:0x3ffb1d80 0x400d7dcc:0x3ffb1dc0 0x40163599:0x3ffb1de0 0x400dddda:0x3ffb1e00 0x400dcb67:0x3ffb1e50 0x400de6da:0x3ffb1ea0 0x400e8536:0x3ffb1fb0 0x40089c02:0x3ffb1fd0
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x400d7e89: esphome::sensor::Filter::input(float) at c:\users\glmne\.platformio\packages\toolchain-xtensa32@2.50200.97\xtensa-esp32-elf\include\c++\5.2.0\ext/new_allocator.h:105
WARNING Decoded 0x400d81ec: esphome::sensor::Sensor::publish_state(float) at C:\git\esphome_devices\experiments\.esphome\build\test-esp32/src\esphome\components\sensor/sensor.cpp:120
WARNING Decoded 0x400d7dbb: esphome::pulse_counter::PulseCounterSensor::update() at C:\git\esphome_devices\experiments\.esphome\build\test-esp32/src\esphome\components\pulse_counter/pulse_counter_sensor.cpp:181
WARNING Decoded 0x400d7dcc: non-virtual thunk to esphome::pulse_counter::PulseCounterSensor::update()
WARNING Decoded 0x40163599: std::_Function_handler<void (), esphome::PollingComponent::call_setup()::{lambda()#1}>::_M_invoke(std::_Any_data const&) at C:\git\esphome_devices\experiments\.esphome\build\test-esp32/src/esphome/core/component.cpp:149
 (inlined by) _M_invoke at c:\users\glmne\.platformio\packages\toolchain-xtensa32@2.50200.97\xtensa-esp32-elf\include\c++\5.2.0/functional:1871
WARNING Decoded 0x400dddda: std::function<void ()>::operator()() const at c:\users\glmne\.platformio\packages\toolchain-xtensa32@2.50200.97\xtensa-esp32-elf\include\c++\5.2.0/functional:1710
 (inlined by) esphome::Scheduler::call() at C:\git\esphome_devices\experiments\.esphome\build\test-esp32/src\esphome\core/scheduler.cpp:204
WARNING Decoded 0x400dcb67: esphome::Application::setup() at C:\git\esphome_devices\experiments\.esphome\build\test-esp32/src\esphome\core/application.cpp:49
WARNING Decoded 0x400de6da: setup() at C:\git\esphome_devices\experiments\.esphome\build\test-esp32/src/esphome/core/gpio.h:62
WARNING Decoded 0x400e8536: loopTask(void*) at C:\Users\glmne\.platformio\packages\framework-arduinoespressif32\cores\esp32/main.cpp:18
WARNING Decoded 0x40089c02: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
[22:23:01]
[22:23:01]Rebooting...
[22:23:01]ets Jun  8 2016 00:22:57
[22:23:01]
[22:23:01]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[22:23:01]configsip: 0, SPIWP:0xee
[22:23:01]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[22:23:01]mode:DIO, clock div:2
[22:23:01]load:0x3fff0018,len:4
[22:23:01]load:0x3fff001c,len:1044
[22:23:01]load:0x40078000,len:10124
[22:23:01]load:0x40080400,len:5828
[22:23:01]entry 0x400806a8
[22:23:01][I][logger:243]: Log initialized
[22:23:01][C][ota:461]: There have been 6 suspected unsuccessful boot attempts.
[22:23:01][D][esp32.preferences:113]: Saving 1 preferences to flas [...]