Add dps310 sensor support
OttoWinter/esphomeyaml pull request #3704
Opened 2022-08-10 01:43 UTC by kbx81

# What does this implement/fix?

I'm continuing to add support for components I found on my [Adafruit FunHouse](https://www.adafruit.com/product/4985).

This one add support for the `DPS310` pressure and temperature sensor via I2C.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs# _[coming soon]_

## Test Environment

- [x] ESP32-S2
- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:
```yaml
# Example config.yaml
sensor:
  - platform: dps310
    temperature:
      id: funhouse_dps310_temperature
      name: FunHouse DPS310 Temperature
    pressure:
      id: funhouse_dps310_pressure
      name: FunHouse DPS310 Pressure
    update_interval: 5s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs)

2022-08-12 15:23 UTC, DrunkPyromaniac requested changes
Just a couple minor details.

2022-08-12 15:23 UTC, DrunkPyromaniac commented on esphome/components/dps310/dps310.cpp
> +  uint8_t coef_data_raw[DPS310_INIT_TIMEOUT];
This constant doesn't seem like what you want to use to declare the size of the array.  A literal `20` would actually be OK here, in my opinion, because it's tied to the protocol itself.

2022-08-12 15:23 UTC, DrunkPyromaniac commented on esphome/components/dps310/dps310.cpp
> +      DPS310Component::twos_complement(int16_t(((uint16_t) coef_data_raw[16] << 8) | (uint16_t) coef_data_raw[17]), 16);
These are full 16-bit numbers, so you wouldn't need to do the twos-compliment math.
```suggestion
  this->c01_ = (int16_t)((uint16_t) coef_data_raw[8] << 8) | (uint16_t) coef_data_raw[9]);
  this->c11_ = (int16_t)((uint16_t) coef_data_raw[10] << 8) | (uint16_t) coef_data_raw[11]);
  this->c20_ = (int16_t)((uint16_t) coef_data_raw[12] << 8) | (uint16_t) coef_data_raw[13]);
  this->c21_ = (int16_t)((uint16_t) coef_data_raw[14] << 8) | (uint16_t) coef_data_raw[15]);
  this->c30_ = (int16_t)((uint16_t) coef_data_raw[16] << 8) | (uint16_t) coef_data_raw[17]);
```

2022-08-12 15:55 UTC, kbx81 commented on esphome/components/dps310/dps310.cpp
> +      DPS310Component::twos_complement(int16_t(((uint16_t) coef_data_raw[16] << 8) | (uint16_t) coef_data_raw[17]), 16);
Great catch! It's interesting, everybody else does it anyway (and admittedly I largely copy/pasted this and didn't think much about it). Anything we could be missing? 😄 References: [Adafruit](https://github.com/adafruit/Adafruit_DPS310/blob/fe563adb0389aa630ffa44b1fff3482212711a11/Adafruit_DPS310.cpp#L210-L214), [Infineon](https://github.com/Infineon/DPS310-Pressure-Sensor/blob/ed02f803fc780cbcab54ed8b35dd3d718f2ebbda/src/Dps310.cpp#L110-L120)

2022-08-12 16:36 UTC, kbx81 commented on esphome/components/dps310/dps310.cpp
> +  uint8_t coef_data_raw[DPS310_INIT_TIMEOUT];
This is a (bad) typo/copy-paste error. The constant should be `DPS310_NUM_COEF_REGS`. The reason I use a constant instead of a literal is for clarity. If I see `uint8_t coef_data_raw[18];` and I'm not familiar with the device, I have no idea what `18` is/means, why it's there, or what `coef_data_raw` will actually be used for. If I instead see `uint8_t coef_data_raw[DPS310_NUM_COEF_REGS];` then I immediately have context -- I know it's tied to a range of registers in the device, I know why it is the size that it is, and I know what `coef_data_raw` will be used for. 😄

2022-08-12 16:54 UTC, DrunkPyromaniac commented on esphome/components/dps310/dps310.cpp
> +  uint8_t coef_data_raw[DPS310_INIT_TIMEOUT];
Yeah, that makes sense.

2022-08-12 19:48 UTC, DrunkPyromaniac approved these changes
Looks good.

2022-08-18 05:09 UTC, jesserockz commented on esphome/components/dps310/dps310.cpp
> +  if (!this->update_in_progress_) {
This is never set to `true`

2022-08-18 05:11 UTC, kbx81 commented on esphome/components/dps310/dps310.cpp
> +  if (!this->update_in_progress_) {
Oh dear...let's fix that... 😆

2022-08-18 19:49 UTC, jesserockz approved these changes

2022-08-18 19:49 UTC, merged