Add Factory Reset button and switch
OttoWinter/esphomeyaml pull request #3724
Opened 2022-08-17 11:47 UTC by anatoly-savchenkov

# What does this implement/fix?

This PR adds Reset button and switch components (and underlying changes to Preferences code) which perform a restart with resetting all preferences to default values. This can be helpful in case of:
- problems with complex designs especially when many global variables are used to keep some state
- transferring of ownership/installation point of ESP based equipment
- resetting to factory conditions for devices natively coming with ESPHome-based firmware

ESP32 code still to be tested as I don't have access to any ESP32 system at this moment. Docs will be added once maintainers are conceptually ok to accept this change.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2280

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
switch:
  - platform: factory_reset
    name: "Living Room Restart (Default Settings)"

button:
  - platform: factory_reset
    name: "Living Room Restart (Default Settings)"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-08-17 22:00 UTC, jesserockz reviewed
I agree with the concept now that we have pre-flashed devices.

I wouldn't add a `switch` though, just keep the `button` (switches for shutdown/restart etc came before `button` was a thing so they have hung around)

I will give it a test and report back.

2022-08-21 18:34 UTC, anatoly-savchenkov commented
My thinking was the following: buttons are still rare, switches are very common. New device class adds ~1KB of code. So, adding buttons support just to add this Reset component might be too heavy for devices with 512KB of flash.

Do you have plans to retire Shutdown/Restart switches?

2022-08-25 03:51 UTC, jesserockz commented
Ah, I did not think about that. I have the restart button on every device via my common configs =)
Happy to keep both then.

2022-08-25 03:52 UTC, jesserockz commented on esphome/components/esp8266/preferences.cpp
> +    s_flash_dirty = false; */
What is this for?

2022-08-25 03:56 UTC, jesserockz requested changes
Generally looks good. One question above. 

Can we rename the platform to `factory_reset` though please? 
the terms reset/reboot/restart can be easily mistaken.

2022-08-27 21:31 UTC, anatoly-savchenkov commented on esphome/components/esp8266/preferences.cpp
> +    s_flash_dirty = false; */
This is old code, should be removed

2022-08-30 22:42 UTC, jesserockz approved these changes

2022-08-30 22:42 UTC, jesserockz commented
Please add a documentation PR, then this can be merged

2022-09-11 22:10 UTC, jesserockz commented on esphome/components/factory_reset/switch/__init__.py
> +        cv.Optional(CONF_ICON, default=ICON_RESTART_ALERT): switch.icon,
```suggestion
        cv.Optional(CONF_ICON, default=ICON_RESTART_ALERT): cv.icon,
```

2022-09-11 22:10 UTC, jesserockz approved these changes

2022-09-11 22:23 UTC, merged