add xiaomi door window sensor 2
OttoWinter/esphomeyaml pull request #3725
Opened 2022-08-17 12:50 UTC by JordyH66

# What does this implement/fix?
add xiaomi door window sensor 2
Quick description and explanation of changes

## Types of changes

- [ ☑️] New feature (non-breaking change which adds functionality)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

ESP32

```yaml
binary_sensor:
  - platform: xiaomi_mccgq02hl
    name: "xiaomi_mccgq02hl"
    mac_address: "xxxxxx"
    bindkey: "xxxxxxx"
    on_lock:
      name: "xiaomi_mccgq02hl"
    light:
      name: "xiaomi_mccgq02hl light"

```

## Checklist:
The code change is tested and works locally.

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-08-17 22:57 UTC, jesserockz requested changes

2022-08-17 22:57 UTC, jesserockz commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +    result.name = "TYPE_MCCGQ02HL";
```suggestion
    result.name = "MCCGQ02HL";
```

2022-08-17 22:57 UTC, jesserockz commented on esphome/components/xiaomi_mccgq02hl/binary_sensor.py
> +from esphome.components import sensor, binary_sensor, esp32_ble_tracker
```suggestion
from esphome.components import binary_sensor, esp32_ble_tracker
```

2022-08-17 22:57 UTC, jesserockz commented on esphome/components/xiaomi_mccgq02hl/binary_sensor.py
> +AUTO_LOAD = ["xiaomi_ble", "sensor"]
```suggestion
AUTO_LOAD = ["xiaomi_ble"]
```

2022-08-18 12:43 UTC, JordyH66 reviewed
check and correct

2022-08-25 01:48 UTC, jesserockz commented
Please add to a test file and create a docs PR

2022-08-26 02:47 UTC, JordyH66 commented
https://github.com/esphome/esphome/pull/3725#issuecomment-1226676272
> Please add to a test file and create a docs PR

This is my first time working on a public PR submission and overall I feel a little overwhelmed, but I'm also trying to learn and refine my process.

2022-08-28 08:36 UTC, JordyH66 commented
> # What does this implement/fix?
> add xiaomi door window sensor 2 Quick description and explanation of changes
> 
> ## Types of changes
> * [ ]  Bugfix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  Other
> 
> **Related issue or feature (if applicable):** fixes
> 
> **Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#
> 
> ## Test Environment
> * [x]  ESP32
> * [ ]  ESP32 IDF
> * [ ]  ESP8266
> 
> ## Example entry for `config.yaml`:
> ```yaml
> binary_sensor:
>   - platform: xiaomi_mccgq02hl
>     name: "xiaomi_mccgq02hl"
>     mac_address: "xxxxxx"
>     bindkey: "xxxxxxx"
>     on_lock:
>       name: "xiaomi_mccgq02hl"
>     light:
>       name: "xiaomi_mccgq02hl light"
> ```
> 
> ## Checklist:
> * [x]  The code change is tested and works locally.
> * [ ]  Tests have been added to verify that the new code works (under `tests/` folder).
> 
> If user exposed functionality or configuration variables are added/changed:
> 
> * [ ]  Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).



> Please add to a test file and create a docs PR

I have added documentation and tested it locally, new devices can be detected and status can be obtained on other platforms

2022-08-31 03:54 UTC, jesserockz commented on esphome/components/xiaomi_mccgq02hl/binary_sensor.py
> +AUTO_LOAD = ["xiaomi_ble",'sensor']
```suggestion
AUTO_LOAD = ["xiaomi_ble", "sensor"]
```

2022-08-31 04:27 UTC, jesserockz requested changes

2022-08-31 04:27 UTC, jesserockz commented on esphome/components/xiaomi_ble/xiaomi_ble.h
> +  optional<bool> is_lock;
`open` is probably better than `lock` as this does not tell you if something is locked, but open or closed.
```suggestion
  optional<bool> is_open;
```

2022-08-31 04:27 UTC, jesserockz commented on esphome/components/xiaomi_mccgq02hl/binary_sensor.py
> +            ),
```suggestion
```

2022-08-31 04:27 UTC, jesserockz commented on esphome/components/xiaomi_mccgq02hl/binary_sensor.py
> +        cg.add(var.set_lock(sens))
```suggestion
```

2022-08-31 04:27 UTC, jesserockz commented on esphome/components/xiaomi_mccgq02hl/xiaomi_mccgq02hl.cpp
> +  LOG_BINARY_SENSOR("  ", "Light", this->is_light_);
```suggestion
  LOG_BINARY_SENSOR("", "Xiaomi MCCGQ02HL", this);
  LOG_BINARY_SENSOR("  ", "Light", this->light_);
```

2022-08-31 04:27 UTC, jesserockz commented on esphome/components/xiaomi_mccgq02hl/xiaomi_mccgq02hl.cpp
> +      this->is_lock_->publish_state(!*res->is_lock);
```suggestion
    if (res->is_light.has_value() && this->light_ != nullptr)
      this->light_->publish_state(*res->is_light);
    if (res->is_open.has_value())
      this->publish_state(*res->is_open);
```

2022-08-31 04:27 UTC, jesserockz commented on esphome/components/xiaomi_mccgq02hl/xiaomi_mccgq02hl.h
> +  void set_lock(binary_sensor::BinarySensor *lock) { is_lock_ = lock; }
```suggestion
  void set_light(binary_sensor::BinarySensor *light) { this->light_ = light; }
```

2022-08-31 04:27 UTC, jesserockz commented on esphome/components/xiaomi_mccgq02hl/xiaomi_mccgq02hl.h
> +  binary_sensor::BinarySensor *is_lock_{nullptr};
```suggestion
  binary_sensor::BinarySensor *light_{nullptr};
```

2022-08-31 04:27 UTC, jesserockz commented on tests/test2.yaml
> +      name: 'Mi Door Window 2 Door'
```suggestion
    name: 'Mi Door Window 2 Door'
    mac_address: '12:34:56:12:34:56'
    bindkey: '48403ebe2d385db8d0c187f81e62cb64'
```

2022-08-31 04:27 UTC, jesserockz commented on esphome/components/xiaomi_ble/xiaomi_ble.cpp
> +    result.is_lock = data[0];
```suggestion
    result.is_open = data[0];
```

2022-08-31 04:28 UTC, jesserockz commented
For my review above, you dont need a second child binary sensor as the main code **is** a binary sensor and just needs to publish to itself.

Also, `open` suits this uuid better than `lock`

2022-08-31 14:23 UTC, JordyH66 commented
Sorry, it was my negligence. I was also looking for a very close word to express it at the time, but I was afraid that my changes would affect the project, so I used ON_LOCK. So when I feel that I have become more and more aware of the project when I created a new config [CONFIG_DOOR] to replace

2022-08-31 14:32 UTC, JordyH66 commented
> Sorry, it was my negligence. I was also looking for a very close word to express it at the time, but I was afraid that my changes would affect the project, so I used ON_LOCK. So when I feel that I have become more and more aware of the project when I created a new config [CONFIG_DOOR] to replace

I think it's OK to reject my submission, OPEN seems to be more suitable for the real role of this sensor than DOOR

2022-09-02 00:25 UTC, jesserockz commented
> Sorry, it was my negligence. I was also looking for a very close word to express it at the time, but I was afraid that my changes would affect the project, so I used ON_LOCK. So when I feel that I have become more and more aware of the project when I created a new config [CONFIG_DOOR] to replace

You miss the point I was making, The main component **IS** already the main door binary sensor, you do not need a sub-sensor named door

2022-12-08 01:59 UTC, closed without merging