Add support to tm1621 display
OttoWinter/esphomeyaml pull request #3737
Opened 2022-08-22 07:37 UTC by Philippe12

# What does this implement/fix?

App support for TM1621 display controler that used in Sonoff THR316D, THR320D, POWR316D or POWR320D
Thanks to arendst for it first code into [Tasmota](https://github.com/arendst/Tasmota)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
display:
  platform: tm1621
  id: tm1621_display
  cs_pin: GPIO17
  data_pin: GPIO5
  read_pin: GPIO23
  write_pin: GPIO18
  lambda: |-
    it.printf(0, "%.1f", id(my_sensor1).state);
    it.display_celsius(true);
    it.printf(1, "%.1f", id(my_sensor2).state);
    it.display_humidity(true);
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-08-23 01:43 UTC, jesserockz requested changes

2022-08-23 01:43 UTC, jesserockz commented on esphome/components/tm1621/display.py
> +        cv.Required("write_pin"): pins.gpio_output_pin_schema,
Please make consts for these. They can just go above in this file.

2022-08-23 01:43 UTC, jesserockz commented on esphome/components/tm1621/tm1621.cpp
> +  for (unsigned char tm1621_command : TM1621_COMMANDS) {
Please replace all `unsigned char` with `uint8_t`

```suggestion
  for (uint8_t tm1621_command : TM1621_COMMANDS) {
```

2022-08-23 14:46 UTC, Philippe12 commented on esphome/components/tm1621/display.py
> +        cv.Required("write_pin"): pins.gpio_output_pin_schema,
That done
https://github.com/Philippe12/esphome/commit/06918e5dc8bccb8079411d55c62a1f4958e1374a

2022-08-23 14:47 UTC, Philippe12 commented on esphome/components/tm1621/tm1621.cpp
> +  for (unsigned char tm1621_command : TM1621_COMMANDS) {
Done
https://github.com/Philippe12/esphome/commit/fb1161bef4f08d77d59a7eef40bd0e8b3f336973

2022-08-25 04:31 UTC, jesserockz approved these changes

2022-08-30 22:03 UTC, jesserockz commented
Please add the platform to an existing test yaml file

2022-08-31 08:27 UTC, Philippe12 commented
> Please add the platform to an existing test yaml file

That done

2022-09-02 01:46 UTC, jesserockz requested changes

2022-09-02 01:46 UTC, jesserockz commented on tests/test1.yaml
>    - platform: template
Please dont change unrelated lines in the test files.

2022-09-02 07:17 UTC, Philippe12 commented on tests/test1.yaml
>    - platform: template
I revert some code modifications due to VisualCode option (automatic formating when saving).

2022-09-06 03:38 UTC, jesserockz commented on tests/test1.yaml
>    - platform: template
I also use this, but I have it set to only format lines that are modified, not the whole file :wink:

2022-09-06 03:42 UTC, jesserockz approved these changes

2022-09-07 23:40 UTC, merged