Add support for EE895, HTE501 and TEE501 sensors
OttoWinter/esphomeyaml pull request #3739
Opened 2022-08-22 12:58 UTC by Stock-M

# What does this implement/fix?

Add support for EE895, HTE501 and TEE501 sensors.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2241

## Test Environment

- [x ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml

sensor:
  - platform: ee895
    co2:
      name: "Office CO2"
      accuracy_decimals: 0
    temperature:
      name: "Office Temperature"
      accuracy_decimals: 2
    pressure:
      name: "Office Pressure"
      accuracy_decimals: 1
    address: 0x5F
    update_interval: 15s

sensor:
  - platform: hte501
    temperature:
      name: "Office Temperature"
    humidity:
      name: "Office Humidity"
    address: 0x40
    update_interval: 60s

sensor:
  - platform: tee501
    name: "Office Temperature"
    address: 0x48
    update_interval: 60s

```

## Checklist:
  - [x ] The code change is tested and works locally.
  - [x ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-08-23 09:19 UTC, nielsnl68 commented
Hi Mathias, 
it is good that you work hard on this component set, but could you do me (us) a favor, and commit less frequent, my mailbox is filling up with all your commit messages. 

When you do this for testing, maybe you can create an external component and test it that way.

2022-08-24 16:34 UTC, DrunkPyromaniac requested changes
A couple refactor suggestions, for readability.

2022-08-24 16:34 UTC, DrunkPyromaniac commented on esphome/components/ee895/ee895.cpp
> +    uint32_t x = i2cResponse[4] * 16777216 + i2cResponse[5] * 65536 + i2cResponse[2] * 256 + i2cResponse[3];
Why did you do multiplication here?  Why not bit-shifting like everywhere else?  Also, I think you can directly store the data into a float like this:
```c
float temperature = (i2cResponse[4] << 24 | i2cResponse[5] << 16 | i2cResponse[2]  << 8 | i2cResponse[3]);

2022-08-24 16:34 UTC, GregJArnold commented on esphome/components/ee895/ee895.cpp
> +  uint8_t address_1[] = {0x03, 0x03, 0xEA, 0x00, 0x02, 0xE8, 0xC5};
This is a magic number.  You should create a function like `EE895Component::write_command(uint16_t addr, uint16_t reg_cnt)` that builds this, computes the checksum, and calls `this->write()`.

2022-08-24 16:34 UTC, DrunkPyromaniac commented on esphome/components/ee895/ee895.cpp
> +    float temperature = *(float *) &x;
This code is common across all of your float reads.  You should create a `float EE895Component::read_float()` function that handles reading, computing the checksum, and squishing it into a float and returning it.

2022-08-30 17:16 UTC, DrunkPyromaniac requested changes

2022-08-30 17:16 UTC, DrunkPyromaniac commented on esphome/components/ee895/ee895.cpp
> +           serial_number4);
I just found this out, but there's a `format_hex()` function in the core.
```suggestion
  ESP_LOGV(TAG, "    Serial Number: 0x%s", format_hex(serial_number + 2, 16).c_str());
```

2022-08-30 17:16 UTC, DrunkPyromaniac commented on esphome/components/hte501/hte501.cpp
> +  ESP_LOGV(TAG, "    Serial Number: 0x%08X%08X", serial_number1, serial_number2);
Same as above.

2022-08-30 17:16 UTC, DrunkPyromaniac commented on esphome/components/tee501/tee501.cpp
> +  ESP_LOGV(TAG, "    Serial Number: 0x%08X%08X", serial_number1, serial_number2);
Same.

2022-09-02 01:51 UTC, jesserockz commented
I'm gonna be a PITA and ask you to split this into 1 PR per integration please =)

2022-09-05 08:37 UTC, Stock-M commented
I close this PR and open 3 new ones

2022-09-05 08:37 UTC, closed without merging