Add support for DDS238-4 W Wifi Smart meter and DTS238-7 W
OttoWinter/esphomeyaml pull request #3750
Opened 2022-08-28 23:27 UTC by rodgon81

# What does this implement/fix?

Add support for DDS238-4 W Wifi Smart meter and DTS238-7 W, both only with WISEN App.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

dxs238xw:
  update_interval: 3s

sensor:
  - platform: dxs238xw
    current_phase_1:
      name: "Current"
    voltage_phase_1:
      name: "Voltage"
    frequency:
      name: "Frequency"
    reactive_power_phase_1:
      name: "Reactive Power"
    active_power_phase_1:
      name: "Active Power"
    power_factor_phase_1:
      name: "Power Factor"
    import_active_energy:
      name: "Import Active Energy"
    export_active_energy:
      name: "Export Active Energy"
    total_energy:
      name: "Total Energy"
    phase_count:
      name: "N° Phases"

text_sensor:
  - platform: dxs238xw
    meter_state_detail:
      name: "State - Detail"
    meter_id:
      name: "Serial N°"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-08-30 22:15 UTC, jesserockz requested changes
I started to write specific reviews then realised what you did.

To start, you need to split all code into their respective sub directories for each type (sensor etc).

Remove the AUTO_LOAD for all platform component types, and create a common interface in the parent code that each platform type implements and the parent code can call.

Basically, component code should not know anything about the "child" platform implementations and only rely on an interface. There are a few examples of this in the ESPHome codebase.

2022-08-31 02:46 UTC, rodgon81 commented
> I started to write specific reviews then realised what you did.
> 
> To start, you need to split all code into their respective sub directories for each type (sensor etc).

Ok with this.

> Remove the AUTO_LOAD for all platform component types, 

Ok with this.

> and create a common interface in the parent code that each platform type implements and the parent code can call.
> 
> Basically, component code should not know anything about the "child" platform implementations and only rely on an interface. There are a few examples of this in the ESPHome codebase.

I don't really understand what you mean by this, since I think the current behavior is this way. Better I explain my intentions of how the component works. 

For each entity that works as an input (number, switch, button) they are declared with a unique ID and send their value to the main component, which, according to the received ID, processes the received value. Each ID is obviously associated with a specific variable, eg "max_current_limit". In this way who decides what to do with the value of the number, button or switch is the main component. The number, switch and button only report your change state to de main component.

For each entity that works as an output (binary_sensor, button, number, sensor, switch, text_sensor), the parent component has internally declared each entity, to use "->publish_state(value);"

If I'm still wrong, please indicate a more specific example of operation.

2022-08-31 03:51 UTC, jesserockz requested changes
Happier with the split, much easier to review and understand, thanks.

Added a bunch of changes to be made, there are more of the same, its just not the easiest to mark them all in GitHub.

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/__init__.py
> +    "dxs238xw.meterStateToogle",
Typo in `Toggle`?

And please use `snake_case` for actions.

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/automation.h
> +template<typename... Ts> class sendHexMessageAction : public Action<Ts...> {
Class names should all be `PascalCase`

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/dxs238xw.h
> +#include "esphome/components/text_sensor/text_sensor.h"
These imports, and any code in the parent component using the classes within these files should be wrapped in `#ifdef USE_BINARY_SENSOR` (for example).

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/dxs238xw.cpp
> +                            SM_UART_CONFIG_DATA_BITS);
You are already enforcing this in config validation, there is no need to check here.

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/switch/__init__.py
> +dxs238xwSwitch = dxs238xw_ns.class_("Dxs238xwSwitch", switch.Switch)
The case of the variables should match the c++ classes exactly

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/switch/__init__.py
> +        ),
This should simplify the switch code a bit simiilar to how sensor is done.
Also all icon strings should be added in `esphome/const.py`

```suggestion
        switch.switch_schema(
            dxs238xwSwitch,
            icon=ICON_LIGHTNING_BOLT,
            entity_category=ENTITY_CATEGORY_CONFIG
        ),
```

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/switch/__init__.py
> +            await switch.register_switch(var, conf)
```suggestion
            var = await switch.new_switch(conf)
```

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/text_sensor/__init__.py
> +        icon="mdi:power-plug",
Move to `esphome/const.py` please

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/text_sensor/__init__.py
> +DEPENDENCIES = ["uart"]
This should be the parent only for all children platforms.
```suggestion
DEPENDENCIES = ["dxs238xw"]
```

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/__init__.py
> +    maybe_simple_id(
You cant have `maybe_simple_id with a second required field in the schema. Just use `cv.Schema(...)` here

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/dxs238xw.cpp
> +void Dxs238xwComponent::send_hex_message(const char *message, bool check_crc) {
Please use `std::string` here, and change the references

```suggestion
void Dxs238xwComponent::send_hex_message(std::string message, bool check_crc) {
```

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/automation.h
> +  TEMPLATABLE_VALUE(const char *, message)
```suggestion
  TEMPLATABLE_VALUE(std::string, message)
```

2022-08-31 03:51 UTC, jesserockz commented on esphome/components/dxs238xw/dxs238xw.cpp
> +  const char *string_code = nullptr;
```suggestion
  std::string string_type;
  std::string string_code;
```

2022-08-31 14:44 UTC, rodgon81 commented on esphome/components/dxs238xw/switch/__init__.py
> +        ),
At first, I try to define everything in the same way as I did in sensor, but as of today it is not possible. For example, on the switch it wouldn't work since "switch_schema" doesn't define the "icon" option like sensor does.

![Captura de pantalla 2022-08-31 103831](https://user-images.githubusercontent.com/6945715/187706144-60bcea9f-f47b-454c-99a8-f1a38437111f.png)

In the case of button, is not defined "class_".
In the case of number, "number_schema" doesn't even exist.

I didn't want to modify other files outside of my component, so for the number, switch, and button I adapted to what exists today.

2022-08-31 23:48 UTC, rodgon81 commented on esphome/components/dxs238xw/automation.h
> +template<typename... Ts> class sendHexMessageAction : public Action<Ts...> {
Ok with this.

2022-08-31 23:48 UTC, rodgon81 commented on esphome/components/dxs238xw/dxs238xw.h
> +#include "esphome/components/text_sensor/text_sensor.h"
Ok with this.

2022-08-31 23:48 UTC, rodgon81 commented on esphome/components/dxs238xw/dxs238xw.cpp
> +                            SM_UART_CONFIG_DATA_BITS);
Ok with this. I delete this line.

2022-08-31 23:49 UTC, rodgon81 commented on esphome/components/dxs238xw/switch/__init__.py
> +dxs238xwSwitch = dxs238xw_ns.class_("Dxs238xwSwitch", switch.Switch)
Ok with this. I change the case.

2022-08-31 23:54 UTC, rodgon81 commented on esphome/components/dxs238xw/__init__.py
> +    "dxs238xw.meterStateToogle",
> Typo in `Toggle`?

yes, i change to toggle.

> And please use `snake_case` for actions.

ok, change to snake_case

2022-08-31 23:56 UTC, rodgon81 commented on esphome/components/dxs238xw/switch/__init__.py
> +            await switch.register_switch(var, conf)
Ok, I will use new_switch

2022-08-31 23:57 UTC, rodgon81 commented on esphome/components/dxs238xw/text_sensor/__init__.py
> +DEPENDENCIES = ["uart"]
ok with this, "uart" for parent "dxs238xw" for children

2022-08-31 23:58 UTC, rodgon81 commented on esphome/components/dxs238xw/__init__.py
> +    maybe_simple_id(
Ok, i will use cv.Schema

2022-09-01 00:19 UTC, rodgon81 commented on esphome/components/dxs238xw/dxs238xw.cpp
> +  const char *string_code = nullptr;
ok, i will change to std::string.

2022-09-01 00:36 UTC, rodgon81 commented on esphome/components/dxs238xw/automation.h
> +  TEMPLATABLE_VALUE(const char *, message)
ok, i will change to std::string.

2022-09-01 00:36 UTC, rodgon81 commented on esphome/components/dxs238xw/dxs238xw.cpp
> +void Dxs238xwComponent::send_hex_message(const char *message, bool check_crc) {
ok, i will change to std::string.

2022-09-01 03:17 UTC, rodgon81 commented on esphome/components/dxs238xw/text_sensor/__init__.py
> +        icon="mdi:power-plug",
Ok, i will move this and all other icons to const.py.

2022-09-01 03:20 UTC, rodgon81 commented on esphome/components/dxs238xw/switch/__init__.py
> +        ),
I noticed that they recently changed the definition of switch_schema. So I update according to your indication.

The number and buttons are expected to update, so update the same way as the switch?

2022-09-02 01:56 UTC, jesserockz commented on esphome/components/dxs238xw/switch/__init__.py
> +        ),
Yeah sorry I did it recently =)
Dont worry about the ones that are not done yet like number/button. I will go through and update each platform when I make the core changes.

2022-09-02 01:58 UTC, jesserockz commented on esphome/components/dxs238xw/__init__.py
> +async def MeterStateToggleAction_to_code(config, action_id, template_arg, args):
Haha, sorry. Having multiple cases can be confusing. This should be snake_case too

```suggestion
async def meter_state_toggle_action_to_code(config, action_id, template_arg, args):
```

2022-09-03 03:01 UTC, rodgon81 commented on esphome/components/dxs238xw/__init__.py
> +async def MeterStateToggleAction_to_code(config, action_id, template_arg, args):
Ok, change to snake_case.

2022-09-03 03:03 UTC, rodgon81 commented on esphome/components/dxs238xw/switch/__init__.py
> +        ),
ok

2022-09-09 13:16 UTC, rodgon81 commented
@jesserockz is there anything else needed for this? What's next?

2022-09-11 22:15 UTC, jesserockz commented
> @jesserockz is there anything else needed for this? What's next?

Patience as I make the rounds. I am very busy =)

2023-03-31 00:45 UTC, closed without merging