Max6956 support added
OttoWinter/esphomeyaml pull request #3764
Opened 2022-09-02 12:01 UTC by looping40

# What does this implement/fix?

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2138

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs/pull/2138).

2022-09-02 13:37 UTC, looping40 commented
This PR replace https://github.com/esphome/esphome/pull/3570 I created on Dev branch, so I could not commit changes.

2022-09-05 03:56 UTC, jesserockz requested changes
Here is my initial review

2022-09-05 03:56 UTC, jesserockz commented on esphome/components/max6956/__init__.py
> +@coroutine
Not needed
```suggestion
```

2022-09-05 03:56 UTC, jesserockz commented on esphome/components/max6956/automation.cpp
> +}  // namespace esphome
No point in an empty file...

2022-09-05 03:56 UTC, jesserockz commented on esphome/components/max6956/max6956.cpp
> +  ESP_LOGCONFIG(TAG, "digital_write pin[%u]=%u", pin, value);
Please remove this log line
```suggestion
```

2022-09-05 03:56 UTC, jesserockz commented on esphome/components/max6956/max6956.cpp
> +  ESP_LOGD(TAG, "pin_mode IO pin[%u] reg[0x%u]=0x%.2X", pin, reg_addr, config);
```suggestion
```

2022-09-05 03:56 UTC, jesserockz commented on esphome/components/max6956/max6956.cpp
> +  uint8_t mode = 0;
You really should use the enum names when making variables, otherwise its harder to follow the code.
```suggestion
  MAX6956GPIOMode mode = 0;
```

2022-09-05 03:56 UTC, jesserockz commented on esphome/components/max6956/max6956.cpp
> +  ESP_LOGD(TAG, "pin_mode LED pin[%u] = reg[0x%.2X] = 0x%.2X", pin, reg_addr, config);
```suggestion
```

2022-09-05 03:56 UTC, jesserockz commented on esphome/components/max6956/__init__.py
> +            cv.Optional(CONF_BRIGHTNESS_GLOBAL, default="6%"): cv.percentage,
Does this make sense as a percentage considering it is limited to only 16 steps in the end? It really should just be an integer between 0-15 inclusive.
(Same for the action below)

2022-09-05 03:56 UTC, jesserockz commented on esphome/components/max6956/max6956.cpp
> +  ESP_LOGD(TAG, "write_brightness_global_ reg[0x%.2X] = 0x%.2X", MAX6956_GLOBAL_CURRENT, global_brightness_);
All of these write reg logs should be removed please. If someone wants to inspect, VV logging level has all i2c bytes in the logs

2022-09-05 03:56 UTC, jesserockz commented on esphome/components/max6956/max6956.cpp
> +}*/
This should dump the config, mode and brightness etc.

2022-09-05 03:56 UTC, jesserockz commented on esphome/components/max6956/__init__.py
> +            cv.Required(CONF_ID): cv.use_id(MAX6956),
You can combine this with `cv.maybe_simple_value` to make the config smaller for users:
```yaml
- max6956.set_brightness_global: 10%
```
Do see my comment above about this not being a percentage though...

```suggestion
            cv.GenerateID(CONF_ID): cv.use_id(MAX6956),
```

2022-09-05 21:57 UTC, looping40 commented on esphome/components/max6956/automation.cpp
> +}  // namespace esphome
removed

2022-09-06 00:11 UTC, jesserockz requested changes
A couple more changes below, otherwise looks good.

2022-09-06 00:11 UTC, jesserockz commented on esphome/components/max6956/automation.h
> +  TEMPLATABLE_VALUE(float, brightness_global)
```suggestion
  TEMPLATABLE_VALUE(uint8_t, brightness_global)
```

2022-09-06 00:11 UTC, jesserockz commented on esphome/components/max6956/__init__.py
> +    cv.Schema(
The same `cv.maybe_simple_value` can be applied here =)

2022-09-06 00:11 UTC, jesserockz commented on esphome/components/max6956/output/max6956_led_output.cpp
> +  ESP_LOGD(TAG, "write_state float pin[%u]=%f", this->pin_, state);
```suggestion
```

2022-09-06 00:11 UTC, jesserockz commented on esphome/components/max6956/output/max6956_led_output.cpp
> +  ESP_LOGD(TAG, "write_state bool pin[%u]=%u", this->pin_, state);
```suggestion
```

2022-09-06 00:11 UTC, jesserockz commented on tests/test4.yaml
> +    name: "MaxIn Pin 4"
```suggestion
    name: MaxIn Pin 4
```

2022-09-06 00:11 UTC, jesserockz commented on tests/test4.yaml
> +      inverted: False
```suggestion
      inverted: false
```

2022-09-06 13:42 UTC, looping40 commented on esphome/components/max6956/automation.h
> +  TEMPLATABLE_VALUE(float, brightness_global)
I changed the brightness_global from float ( 0.0 to 1.0) to uint8_t (0 to 15).
But when current mode is set to 'segment', the current value for the pin is a float (0.0 to 1.0) because it inherits from output::FloatOutput. I could not find a way to allow a value up to 15.
Isn't it a bit heterogeneous ?

2022-12-23 14:47 UTC, looping40 commented
@jesserockz : Do you need anything else for this PR ?

2023-05-01 21:32 UTC, jesserockz approved these changes

2023-05-01 21:51 UTC, merged