Add support for EE895
OttoWinter/esphomeyaml pull request #3771
Opened 2022-09-05 09:14 UTC by Stock-M

# What does this implement/fix?

Add support for EE895 sensor.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2241

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml

sensor:
  - platform: ee895
    co2:
      name: "Office CO2"
      accuracy_decimals: 0
    temperature:
      name: "Office Temperature"
      accuracy_decimals: 2
    pressure:
      name: "Office Pressure"
      accuracy_decimals: 1
    address: 0x5F
    update_interval: 15s

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-09-06 00:45 UTC, jesserockz requested changes

2022-09-06 00:45 UTC, jesserockz commented on esphome/components/ee895/sensor.py
> +    .extend(cv.polling_component_schema("15s"))
We try to keep the defaults for sensors at 60s please.

```suggestion
    .extend(cv.polling_component_schema("60s"))
```

2022-09-06 00:45 UTC, jesserockz commented on tests/test1.yaml
> +      name: "Office Pressure 1"
```suggestion
      name: Office CO2 1
    temperature:
      name: Office Temperature 1
    pressure:
      name: Office Pressure 1
```

2022-09-06 00:45 UTC, jesserockz commented on esphome/components/ee895/ee895.h
> +  uint16_t calc_crc16_(const unsigned char buf[], unsigned char len);
Please use `uint8_t` instead of `unsigned char`
```suggestion
  uint16_t calc_crc16_(const uint8_t *buf, uint8_t len);
```

2022-09-06 00:45 UTC, jesserockz commented on esphome/components/ee895/ee895.cpp
> +}
I have actually just moved the 3 crc16 functions in the codebase into `esphome/core/helpers.h` so you don't need to create one here. See #3780

2022-09-06 00:45 UTC, jesserockz commented on esphome/components/ee895/ee895.cpp
> +  float value = *(float *) &x;  // convert uin32_t IEEE-754 format to float
```suggestion
  uint32_t x = encode_uint32(i2c_response[4], i2c_response[5], i2c_response[2], i2c_response[3]);
  float value;
  memcpy(&value, &x, sizeof(value));  // convert uin32_t IEEE-754 format to float
```

2022-09-07 09:00 UTC, Stock-M commented on esphome/components/ee895/ee895.cpp
> +}
I have changed the function but could not delete it completely, because i have to add the i2c address in front of the array to calculate the correct checksum.

2022-09-11 22:18 UTC, jesserockz commented on esphome/components/ee895/ee895.cpp
> +}
Updated function is fine :+1:

2022-09-11 22:19 UTC, jesserockz commented on esphome/components/ee895/ee895.cpp
> +  crc_check_buf[0] = 0x5F;
Should not be hardcoded
```suggestion
  crc_check_buf[0] = this->address_;
```

2022-09-11 22:21 UTC, jesserockz requested changes

2022-09-11 22:21 UTC, jesserockz commented on esphome/components/ee895/ee895.cpp
> +uint16_t EE895Component::calc_crc16_(const unsigned char buf[], unsigned char len) {
```suggestion
uint16_t EE895Component::calc_crc16_(const uint8_t buf[], uint8_t len) {
```

2022-09-11 22:21 UTC, jesserockz commented on esphome/components/ee895/ee895.cpp
> +  crc_check_buf[0] = 0x5F;
Should not be hardcoded
```suggestion
  crc_check_buf[0] = this->address_;
```

2022-09-11 22:21 UTC, jesserockz commented on esphome/components/ee895/ee895.cpp
> +  unsigned char crc_check_buf[22];
```suggestion
  uint8_t crc_check_buf[22];
```

2022-09-11 22:21 UTC, jesserockz commented on esphome/components/ee895/ee895.h
> +  uint16_t calc_crc16_(const unsigned char buf[], unsigned char len);
```suggestion
  uint16_t calc_crc16_(const uint8_t buf[], uint8_t len);
```

2022-09-12 23:44 UTC, jesserockz approved these changes

2023-01-17 21:42 UTC, merged