Add support for HTE501
OttoWinter/esphomeyaml pull request #3772
Opened 2022-09-05 09:16 UTC by Stock-M

# What does this implement/fix?

Add support for HTE501 sensor.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2241

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml

sensor:
  - platform: hte501
    temperature:
      name: "Office Temperature"
    humidity:
      name: "Office Humidity"
    address: 0x40
    update_interval: 60s

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-09-06 00:52 UTC, jesserockz requested changes

2022-09-06 00:52 UTC, jesserockz commented on tests/test1.yaml
> +    i2c_id: i2c_bus
```suggestion
      name: Office Temperature 2
    humidity:
      name: Office Humidity 1
    address: 0x40
    i2c_id: i2c_bus
```

2022-09-06 00:52 UTC, jesserockz commented on esphome/components/hte501/hte501.cpp
> +}
You should use `crc8` that is already in helpers and just pass the part of the buffer you want to calculate on with the length.

2022-09-06 00:52 UTC, jesserockz commented on esphome/components/hte501/hte501.cpp
> +#include "esphome/core/log.h"
```suggestion
#include "esphome/core/log.h"
#include "esphome/core/helpers.h"
```

2022-09-06 00:52 UTC, jesserockz commented on esphome/components/hte501/hte501.cpp
> +    float temperature = ((float) (i2c_response[0]) * 256 + i2c_response[1]);
```suggestion
    float temperature = (float) encode_uint16(i2c_response[0], i2c_response[1]);
```

2022-09-06 00:52 UTC, jesserockz commented on esphome/components/hte501/hte501.cpp
> +    float humidity = ((float) (i2c_response[3]) * 256 + i2c_response[4]) / 100;
```suggestion
    float humidity = ((float) encode_uint16(i2c_response[3], i2c_response[4])) / 100.0f;
```

2022-09-12 08:29 UTC, Stock-M commented on esphome/components/hte501/hte501.cpp
> +}
I changed everything to the crc8 calculation from helpers. When I tested it, it turned out that the wrong checksum was calculated.  I can't find any other crc8 calculation in helpers. Do you have any suggestions.

2022-09-26 12:03 UTC, Stock-M commented
I changed everything to the crc8 calculation from helpers. When I tested it, it turned out that the wrong checksum was calculated. I can't find any other crc8 calculation in helpers. Do you have any suggestions.

2022-09-26 22:22 UTC, dcousens commented
The code in this repository for `crc8` seems to be an unattributed copy of https://github.com/PaulStoffregen/OneWire/blob/master/OneWire.cpp#L522-L540; and is known as the Dallas / Maxim "OneWire" variant.

This pull request (and https://github.com/esphome/esphome/pull/3773) is additionally using a CRC-8 Dallas / Maxim variant.

The problem is the byte ordering, the code as written by @Stock-M is the same polynomial, but the byte ordering is reversed.
For example, if you changed the `crc8` code (in repository) from

```
  while ((len--) != 0u) {
```

to
```
  for (auto l = 0; l < len; ++l) {
```

Your problem will be resolved.

2022-09-26 22:50 UTC, PaulStoffregen commented
Can't help much.  When I inherited OneWire (about 12-13 years ago) that code was already present and the list of prior authors was already several names.  At the time I tried reaching out to all of them.  Only one replied, to say he was glad someone was going to fix the bugs and hoped it "would not be horrible next time" he used, or something along those lines.  A brief mention of OneWire is probably the proper thing to do, but I wouldn't worry or try to overthink it too much.

2022-10-03 10:41 UTC, Stock-M commented
So your suggestion is to add a new crc 8 calculation in helpers with an additional attribute.

2022-10-19 00:32 UTC, jesserockz commented
Ok considering the above, lets just leave the crc8 function in this PR and I can look at refactoring it later on.

2023-01-17 21:41 UTC, jesserockz approved these changes

2023-01-17 21:42 UTC, merged