Revisit the ili9341 platform component.
OttoWinter/esphomeyaml pull request #3795
Opened 2022-09-12 15:53 UTC by nielsnl68

# What does this implement/fix?

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other
- Removed cleaning the screen twice
  \Should be handled by  `DisplayBuffer::init_internal_();`
- Made ili9341::initalize() protected and renamed \ it to ili9341::initalize().
- ili9341::initalize() should only init the display \ and set the width and heigth.

Clean
**Related issue or feature (if applicable):** fixes PR#3756

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-09-23 18:54 UTC, landonr commented
are there any screenshots of these widgets? I might make use of them in my project here. It'd like to show widgets for the different sensors I have set up https://github.com/landonr/esphome-remote

2022-09-23 20:06 UTC, nielsnl68 commented
> are there any screenshots of these widgets? I might make use of them in my project here. It'd like to show widgets for the different sensors I have set up https://github.com/landonr/esphome-remote

there is not much ready yet. but you can follow me progress on discord's show-off section:
https://discord.com/channels/429907082951524364/1019881727159697418/1019881727159697418

2022-10-05 01:39 UTC, jesserockz requested changes
Since `EXTENDED_DISPLAYBUFFER` is never set, can you remove all of those blocks? If its planned for more work then please add them back in that PR, right now they make no sense.

2022-10-05 01:39 UTC, jesserockz commented on esphome/components/ili9341/display.py
> +    "The ili0341 platform component is renamed to ili9xxx and gives more display chooses."
No need to explain =)
```suggestion
    "The ili9341 platform component has been renamed to ili9xxx."
```

2022-10-05 01:39 UTC, jesserockz commented on esphome/components/ili9xxx/display.py
> +            cv.GenerateID(CONF_RAW_DATA_ID): cv.declare_id(cg.uint8),
Need to add CONF_LED_PIN here with an invalid saying its not used here anymore.
(This will be for people that just change the platform to the new `ili9xxx`)

2022-10-05 01:39 UTC, jesserockz commented on esphome/components/ili9xxx/ili9xxx_defines.h
> +// clang-format off
Why turning off the formatter for this block?

2022-10-05 01:39 UTC, jesserockz commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +  uint16_t w = this->x_high_ - this->x_low_ + 1;  // NOLINT
This is broken...
if `EXTENDED_DISPLAYBUFFER` was defined then there is code outside the function here...

2022-10-05 03:40 UTC, gpambrozio commented on esphome/components/ili9341/display.py
> -            cv.Optional(CONF_LED_PIN): pins.gpio_output_pin_schema,
Just fyi: the led pin is missing in the new schema, not sure if it's intended as it breaks configs.

2022-10-05 07:06 UTC, nielsnl68 commented on esphome/components/ili9341/display.py
> -            cv.Optional(CONF_LED_PIN): pins.gpio_output_pin_schema,
It was intended indeed. The LED_PIN was never used inside the driver itself. so i removed it.
But because of your statement i will bring it back with a proper error message.

> **BTW when someone used it in there script other then defining it. Please let me know**

2022-10-05 07:16 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
> +            cv.GenerateID(CONF_RAW_DATA_ID): cv.declare_id(cg.uint8),
indeed. I will add that.

2022-10-05 07:16 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_defines.h
> +// clang-format off
Not sure i did not added it myself, it was there before i started. Should i remove it?

2022-10-05 07:22 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +  uint16_t w = this->x_high_ - this->x_low_ + 1;  // NOLINT
ouch, 

> Since `EXTENDED_DISPLAYBUFFER` is never set, can you remove all of those blocks? If its planned for more work then please add them back in that PR, right now they make no sense.

I use it i combination with the displaybuffer PR i created as well for my SwitchPlate component. That is way it is here.

2022-10-05 07:23 UTC, nielsnl68 commented
> Since `EXTENDED_DISPLAYBUFFER` is never set, can you remove all of those blocks? If its planned for more work then please add them back in that PR, right now they make no sense.

I use it i combination with the displaybuffer PR i created as well for my SwitchPlate component. That is way it is here.

2022-10-06 15:23 UTC, nielsnl68 commented
@workingmanrob found in his feature request (esphome/feature-requests/issues/1853) that we have a memory issue using the ili9486.
This means that i need to do more work to fix this issue.

2022-10-12 20:24 UTC, clowrey commented
Can you re-add the "led_pin: xx" of "backlight_pin: xx" functionality? otherwise by default allot of display will not be turned on. Users can still use the external "light" component to control the backlight externally but at least it will not be required.

2022-11-11 23:42 UTC, tuct commented
Will this be released soon?
2 displays with a ST7796 just arrived and i wanted to use them with esphome, happy to test

2022-11-12 00:28 UTC, clowrey commented
> Will this be released soon? 2 displays with a ST7796 just arrived and i wanted to use them with esphome, happy to test

You can always use these too, just import as external component

2022-12-13 12:42 UTC, gpambrozio commented
@nielsnl68 I'm trying to compile my touch panel config using latest develop version (esphome-2022.12.0b4) but it fails to compile:
```
Compiling .pioenvs/touch_panel/src/esphome/components/light/esp_hsv_color.cpp.o
In file included from src/esphome/components/ili9xxx/ili9xxx_display.h:9,
                 from src/esphome/components/ili9xxx/ili9xxx_display.cpp:1:
src/esphome/components/ili9xxx/ili9xxx_init.h:121:3: error: 'ILI9488_INVON' was not declared in this scope
   ILI9488_INVON  , 0,
   ^~~~~~~~~~~~~
src/esphome/components/ili9xxx/ili9xxx_init.h:121:3: note: suggested alternative: 'ILI9XXX_INVON'
   ILI9488_INVON  , 0,
   ^~~~~~~~~~~~~
   ILI9XXX_INVON
Compiling .pioenvs/touch_panel/src/esphome/components/light/esp_range_view.cpp.o

```

Some of the tests ran on this branch also fail for the same reason.

2022-12-14 04:27 UTC, gpambrozio commented
@nielsnl68 The suggestion given by the error seems to fix the issue. I don't have a device here with me to confirm but it at least compiles successfully.

2022-12-19 14:04 UTC, nielsnl68 commented
I fixed the error for now. sorry to say, in the meantime i have abandoned this solution in favor for a more complete end different solution using Arduino_gfx as bases of the display driver. 
It will allow for SPI and parallel communication with the different displays.
Also it will offer much more types of display's
And it is very compact so far i can see.
It will mimic the current displaybuffer functions but it will have his own base component class.

2023-01-07 12:29 UTC, closed without merging

2023-01-09 16:57 UTC, gpambrozio commented
@nielsnl68 do you already have a pr I could try? I also got a new board with a ST7796 display that uses the parallel interface and I believe that the `Arduino_gfx` supports it so it might solve my issue. Thanks.

2023-01-09 17:13 UTC, nielsnl68 commented
I am working on a graphics platform component around the Arduino_gfx as well. 
Checkout my Github repo under: https://github.com/nielsnl68/esphome-components

it is still work in progress. Although it should work, it is not (yet) inherited from the DisplayBuffer class and therefor it does not have the page option and animations.

2023-01-10 14:27 UTC, nielsnl68 commented
I created a new PR: #4275