Allow preserving WiFi credentials entered with captive_portal
OttoWinter/esphomeyaml pull request #3813
Opened 2022-09-15 14:02 UTC by kuba2k2

# What does this implement/fix?

This PR allows the user to preserve the WiFi credentials, that were entered using `captive_portal`, over subsequent OTA updates. I think this may be a useful feature, given that guides like `Sharing ESPHome devices` exist, and the recent addition of a "factory reset" component. When using `keep_user_credentials`, the user can freely reconfigure a device to a different network in a [WiFiManager](https://github.com/tzapu/WiFiManager)-like manner, whether it's a DIY, tuya-converted, or vendor-supplied ESPHome device.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2301

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] LibreTuya port

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
wifi:
  keep_user_credentials: true
  # ssid: "my_ssid_unused"
  # password: "1234"
  ap:
    password: "ESPHome123"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-09-15 19:41 UTC, jesserockz requested changes
The issue here is that if you flash a YAML over top that has credentials "built in", they wont work unless you remove the `keep_user_credentials: true` so there needs to be some validation on the config there to prevent both at the same time.

2022-09-15 20:37 UTC, kuba2k2 commented
Right, that's a good point! I'll refactor that tomorrow.

2022-09-17 15:14 UTC, kuba2k2 commented
Okay, the option is now incompatible with either `ssid`, `password` or `networks`.

```yaml
Failed config

wifi: [source .\aubess-4b1-03h4-01.yml:35]

  WiFi credentials cannot be used together with keep_user_credentials.
  keep_user_credentials: True
  ssid: 127.0.0.1
  ap:
    password: FallbackApPassword
```

2022-10-12 04:20 UTC, jesserockz requested changes
Feels weird the way this works, but its fine.
Just a rename of the define below please.

2022-10-12 04:20 UTC, jesserockz commented on esphome/components/captive_portal/__init__.py
> +        cg.add_define("USE_WIFI_USER_CREDENTIALS")
Would just like the define to be named from the component that actually creates it.
```suggestion
        cg.add_define("USE_CAPTIVE_PORTAL_KEEP_USER_CREDENTIALS")
```

2022-10-13 15:48 UTC, kuba2k2 commented on esphome/components/captive_portal/__init__.py
> +        cg.add_define("USE_WIFI_USER_CREDENTIALS")
Okay, done.

2022-10-13 19:57 UTC, jesserockz approved these changes

2022-10-13 19:58 UTC, merged