MR24BHP1 Human-Presence Sensor
OttoWinter/esphomeyaml pull request #3842
Opened 2022-09-23 21:01 UTC by lorki97

# What does this implement/fix?

This PR adds support for the seeedstudio MR24HPB1 Human-Presence sensor.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2322

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
    # UART is required for MR24HPB1
    uart:
      tx_pin: 17
      rx_pin: 16
      baud_rate: 9600

    # Example configuration entry
    mr24hpb1:
      threshold_gear: 7
      scene_setting: DEFAULT
      force_unoccupied: NONE
      environment_status:
        name: Environment Status
      occupancy:
        name: Occupancy
      movement:
        name: Movement
      movement_rate:
        name: Movement Rate
      movement_type:
        name: Movement Type
      device_id:
        name: Device ID
      software_version:
        name: Software version
      protocol_version: 
        name: Protocol Version
      hardware_version: 
        name: Hardware Version
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-01-11 08:10 UTC, andyfsimon commented
This is precisely what I was looking for - I'd love to test it, but I am not practical with esphome-dev.

2023-01-11 11:50 UTC, lorki97 commented
@andyfsimon You would have to clone the code from https://github.com/lorki97/esphome/tree/feature/Seeed-Studio-MR24D11C10 and setup a development environment on your PC to use this module.

2023-01-11 19:54 UTC, singhdd93 commented
Any Idea when this will be merged ?

2023-01-18 10:45 UTC, andyfsimon commented
I managed to build the code and it does indeed work. I still have to figure out the parameters though, as it seems to be detecting pretty much anything and not only presence. For instance, while pointed to an empty room with a 3d printer running it'll go off. Might be legit, but that's not what I expected.
Other than that, it seems to be working just great so thumbs up! I'll keep testing.

2023-01-18 14:29 UTC, andyfsimon commented
Indeed I do see a potential issue, but I am unsure of what's causing this: no matter what threshold level I select the minimum detection of movement rate is 1. Meaning that even if I leave the room (empty) it will still detect presence, albeit stationary.

2023-01-19 12:12 UTC, florianL21 commented
I've found that the sensor is quite sensitive even in the lowest sensitivity level.
I currently have it mounted at a 15 degree angle right below the ceiling which in my room I've found works best.
I also have the same "issue" that it will never switch to unoccupied when my 3d printer is running but I guess that is to be expected since it's a bunch of metal moving around and the sensor is trying to detect micro movements.

I've also found that the sensor seems to be quite picky about where it is placed. It might not work in some locations/orientations at all. I suggest trying different locations if you are having the issue that the room never goes to unoccupied.

The sensor also does not like to be moved/vibrated after it's started. So make sure it is mounted to a steady location. If you readjust it's position try to cut power for a few seconds and turn it back on again. There seems to be a background noise analysis ongoing in the first 30s after the sensor starts. So make sure to also keep it really steady as soon as it has power.

Hope these tips will help you to get it working reliably

2023-01-19 14:07 UTC, andyfsimon commented
Hi @florianL21, you make some very interesting points indeed. I did make sure to create a generous separation (for tests) between the ESP32 and the sensor (I've been told the ESP antenna interferes with the sensor at times) but I did not consider vibrations or, more interestingly, the need to keep it steady during startup.
I tried removing the printer, which was the most obvious interference, but I suppose other elements in the room or outside could be making the sensor's life harder than it should.
I was hoping to be able to test before putting it into the enclosure I printed (which contains other sensors as well) but it seems I'll have to assemble and place the unit before I can test/calibrate.

Thanks a lot for the suggestions and of course also to @lorki97 for the great work! I hope it'll be merged soon!

2023-05-02 03:57 UTC, jesserockz commented on esphome/components/mr24hpb1/constants.h
> +#include "mr24hpb1.h"
Why include the whole component when only "types.h" is needed here?

2023-05-16 17:03 UTC, asucrews commented
Really lookin forward to this integration! I hope @lorki97 has the time to review Jesse comments.

2023-05-16 17:51 UTC, lorki97 commented
> Really lookin forward to this integration! I hope @lorki97 has the time to review Jesse comments.

Thanks for pinging me, the notifications got drowned in my email folder. I'll check this ASAP.

2023-06-01 20:11 UTC, florianL21 commented on esphome/components/mr24hpb1/constants.h
> +#include "mr24hpb1.h"
@lorki97 updated this already, I just checked it again on the actual hardware and everything still seems to be working fine

2023-09-01 15:04 UTC, asucrews commented
Bump

2023-09-06 04:59 UTC, jesserockz requested changes

2023-09-06 04:59 UTC, jesserockz commented on esphome/components/mr24hpb1/__init__.py
> +            cv.Optional(CONF_MOVEMENT_TYPE): text_sensor.text_sensor_schema(),
Please split these entities out into their own platform files similar to how other components do inside ESPHome.

2023-09-06 04:59 UTC, jesserockz commented on esphome/components/mr24hpb1/__init__.py
> +AUTO_LOAD = ["text_sensor", "binary_sensor", "sensor"]
`AUTO_LOAD`ing multiple platforms like this is not allowed in new components unless absolutely necessary, which is almost never if the code is written right.
```suggestion
```

2023-10-05 13:05 UTC, lorki97 commented on esphome/components/mr24hpb1/__init__.py
> +AUTO_LOAD = ["text_sensor", "binary_sensor", "sensor"]
Removed in newest commit.

2023-10-05 13:07 UTC, lorki97 commented on esphome/components/mr24hpb1/__init__.py
> +            cv.Optional(CONF_MOVEMENT_TYPE): text_sensor.text_sensor_schema(),
Split up into own platform files according how other components handle this. Some testing is required to ensure this didn't change anything else. I currently don't have access to the required HW, maybe @florianL21 or somebody else can test with the newest commit.

2024-02-19 00:44 UTC, closed without merging

2024-02-19 06:10 UTC, asucrews commented
@lorki97 did this ever get merged?

2024-02-20 09:25 UTC, lorki97 commented
@asucrews This has not been merged. I have little hope of getting this merged anytime soon with the PR being opened nearly 1.5 years ago.