Sm2135 current fixes
OttoWinter/esphomeyaml pull request #3850
Opened 2022-09-27 18:19 UTC by BoukeHaarsma23

# What does this implement/fix?

Rebased https://github.com/esphome/esphome/pull/3621

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-09-27 19:39 UTC, BoukeHaarsma23 commented
Confirmed working on my calex GU10 bulbs

2022-10-05 03:06 UTC, jesserockz commented on esphome/components/sm2135/__init__.py
> +        ),
Inline with other config variables in ESPHome, it would be nice if this could enforce the use of mA as the unit in YAML.

To do this, you would need to change the `DRIVE_STRENGTHS_CW` to be something like `{"10mA": 10, ...}` and change these to `cv.enum(...)`

2022-10-07 15:05 UTC, BoukeHaarsma23 commented on esphome/components/sm2135/__init__.py
> +        ),
I don't really understand what you want me to inline. But I have made the mA change.

2023-01-20 22:08 UTC, BoukeHaarsma23 commented
unstale

2023-04-13 15:44 UTC, pvizeli approved these changes

2023-04-22 11:05 UTC, jesserockz requested changes

2023-04-22 11:05 UTC, jesserockz commented on esphome/components/sm2135/sm2135.h
All of these function codes doing something other than simple getter/setters should be in the cpp file please.

2023-04-22 15:38 UTC, BoukeHaarsma23 commented on esphome/components/sm2135/sm2135.h
I have moved the more complicated functions.

2023-05-07 23:58 UTC, jesserockz approved these changes
@BoukeHaarsma23 I have made some changes to tidy up the code a little.

Please test and confirm them, otherwise this is good to go.

2023-05-09 23:06 UTC, merged