Add ble RSSI sensor for connected devices
OttoWinter/esphomeyaml pull request #3860
Opened 2022-10-02 19:11 UTC by RoboMagus

# What does this implement/fix?

Adds the option to add an RSSI sensor to `ble_client`, to poll the RSSI for connected devices. 
Currently, without this change, RSSI can only be read from devices not yet connected.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes n/a

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
ble_client:
  - mac_address: ${iTag_MAC}
    id: action_iTag
    rssi:
      update_interval: 30s
      name: "iTag RSSI (connected)"

sensor:
  - platform: ble_rssi
    mac_address: ${iTag_MAC}
    name: "iTag RSSI"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-10-04 00:24 UTC, jesserockz approved these changes, later dismissed
This will break if someone tries to use this without having a top level `sensor` block in yaml.

I would suggest extending the current `ble_client` `sensor` to accept a `typed_schema` with `characteristic` and `rssi` types and the default being `characteristic` (the current type) which will allow further extensions again later on.

YAML would look like this:
```yaml
ble_client:
  mac: ...
  id: ble_client_1
  
sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: ble_client_1
    name: Client 1 RSSI
```

2022-10-04 00:24 UTC, jesserockz requested changes
This will break if someone tries to use this without having a top level `sensor` block in yaml.

I would suggest extending the current `ble_client` `sensor` to accept a `typed_schema` with `characteristic` and `rssi` types and the default being `characteristic` (the current type) which will allow further extensions again later on.

YAML would look like this:
```yaml
ble_client:
  mac: ...
  id: ble_client_1
  
sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: ble_client_1
    name: Client 1 RSSI
```

2022-10-04 07:34 UTC, RoboMagus commented
Thanks for the feedback. I like your suggestion as it does integrate much better with the `ble_client` sensor structure used for characteristics.

However, I think making type a mandatory part of `ble_client` sensors, but having it implicitly default to `characteristic` would cause confusion. Especially when later on more sensor types could be added to the `ble_client` platform.
IMO making it explicit instead would be the better options, though that would introduce a breaking change which in general I'd like to avoid.

Is there a way to issue a warning when validating a config to inform the users about having to add `type: characteristic` to existing `ble_client` sensors? If so, that would both keep things clear and explicit and inform users about the required change.

2022-10-04 22:18 UTC, jesserockz commented
Happy for it to be explicit too. cv.typed_schema will complain with `type not specified` if not added in config.

2022-10-06 11:26 UTC, RoboMagus commented
Refactoring after the merge conflicts was a bit of a challenge, but after making the requested changes I do like this implementation a whole lot better. Thanks for the suggestion @jesserockz.

I've had a couple of esp32 boards scattered around the house running code including these changes and it works as intended.

2022-10-12 02:23 UTC, jesserockz approved these changes

2022-10-12 02:23 UTC, merged