allow to use MQTT for discovery of IPs if mDNS is no option
OttoWinter/esphomeyaml pull request #3887
Opened 2022-10-08 16:35 UTC by Links2004

# What does this implement/fix?

The changes allows the user to use MQTT as a alternative to mDNS  for discovery of IPs / ESPhome devices.

This is helpful when for example:
 - the CLI/dashboard is running not on the same network segment the the ESPhome devices and there is only access via routing
 - the CLI/dashboard is running in kubernetes
 - the host the has no mDNS support
 
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:
```yaml
# Example config.yaml
esphome:
  name: esphome-test

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxx"

ota:
  password: "yyyy"

mqtt:
  broker: mqtt.demo.com
  username: esphome
  discovery_retain: False
  discovery: False

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mdns:
  disabled: True
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-10-16 09:22 UTC, Links2004 commented
docker image for easy testing:
ghcr.io/links2004/esphome/amd64:g8efb7594.mqtt_discover

2022-10-25 18:53 UTC, jesserockz commented on esphome/__main__.py
> +    )
Please test and confirm, but `mdns` should be auto loaded if `wifi` or `ethernet` is in the config and `CONF_DISABLED` defaults to `False` so this structure should always be in the config. 
If `wifi` or `ethernet` are not there then this would fail above on `CONF_OTA not in config` so should be safe.

```suggestion
    mdns_disabled = config[CONF_MDNS][CONF_DISABLED]
```

2022-10-25 19:26 UTC, Links2004 commented on esphome/__main__.py
> +    )
you are correct, I simplify-ed the code.

and also found a other but with the mqtt client id with haveing 2 dashboards on the same MQTT server. (which is fixed not too)
had my changes running in kubernetes and the testing on my computer.

2022-12-03 08:56 UTC, Links2004 commented
Any change of some feedback or a merge?

2023-01-28 14:57 UTC, Links2004 commented
Any change of some feedback or a merge?

2023-02-20 03:05 UTC, jesserockz requested changes

2023-02-20 03:05 UTC, jesserockz commented on esphome/components/mqtt/mqtt_client.cpp
> +#include "esphome/components/wifi/wifi_component.h"
wifi is not guaranteed to be availabel, could be using ethernet.
Use the `network` component to get the ip address below.

2023-02-20 03:05 UTC, jesserockz commented on esphome/mqtt.py
> +def get_esphome_device_ip(config, username=None, password=None, client_id=None):
This really should use async/await, not just rely on the mqtt loop_forever ending, which could happen if the device never comes online?

2023-02-21 17:42 UTC, Links2004 commented on esphome/components/mqtt/mqtt_client.cpp
> +#include "esphome/components/wifi/wifi_component.h"
changed

2023-02-21 18:04 UTC, Links2004 commented on esphome/mqtt.py
> +def get_esphome_device_ip(config, username=None, password=None, client_id=None):
added a timeout

2023-04-03 17:42 UTC, Links2004 commented
@jesserockz  any change of a merge ?

2023-05-12 01:22 UTC, jesserockz approved these changes
Hi @Links2004, I have pushed some minor changes; 
- add a message to the cli prompt telling you what the choice is for
- removed `MQTT` as an upload target as its not really the target, and the code you added already uses the mqtt code to get the ip (Someone can still add `--device MQTT` to bypass the choices)
- another change that reduces the timeout to 10 seconds, as making people wait 2 mins is way too long. The device is either online or offline and will respond quickly if online.

Let me know what you think. I have tested these changes locally and I am happy with the PR in its state now.

Jesse

2023-05-12 15:08 UTC, Links2004 commented
Hi @jesserockz,

thanks for taking the time to look at it.
I tested your changes in my setup and for ESP32 based devices its working,
but for ESP8266's I run in the timeout after the upload.
most likely that the ESP8266 needs more then the 10 sec to reboot and reconnect to MQTT.

```
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting looking for IP in topic esphome/discover/flexispot-desk-control
INFO Connected to MQTT broker!
INFO Send discover via MQTT broker topic: esphome/ping/flexispot-desk-control
ERROR Failed to find IP via MQTT
```

2023-05-12 15:50 UTC, Links2004 commented
did some testing and 25sec works every time for me.

2023-05-13 03:18 UTC, jesserockz approved these changes
25 is fine =)

LGTM

2023-05-17 04:29 UTC, merged