Support for Sharp memory LCD
OttoWinter/esphomeyaml pull request #3898
Opened 2022-10-11 16:27 UTC by skaldo

Hi maintainers,
first of all, thanks for the esphome project. While preparing the PR I could explore the internals and must admit how well architected it is, good job!

I will add the documentation PR in the next days. Looking forward to feedback in the meantime.

# What does this implement/fix?

Support for Sharp memory LCD, tested with the [400x240 model](https://www.adafruit.com/product/4694). I left resolution configurable so it should work also with its [smaller brother](https://www.adafruit.com/product/3502).

## Types of changes

- [X] New feature (non-breaking change which adds functionality)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32 S2
- [X] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
spi:
  clk_pin: GPIO36
  mosi_pin: GPIO35

font:
  - file: "gfonts://Roboto"
    id: roboto_40
    size: 40
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz@'

display:
  - platform: sharp_memory_lcd
    cs_pin: GPIO34
    sharp_cs_pin: GPIO34
    disp_pin: GPIO18
    extmode_pin: GPIO21
    extcomin_pin: GPIO33
    width: 400
    height: 240
    update_interval: 30s
    invert_color: false
    lambda: |-
      it.print(0, 0, id(roboto_40), "Hello World!");
      it.print(0, 86, id(roboto_40), "Hello @esphome_!");
      it.line(0, 0, 400, 240);
      it.line(400, 0, 0, 240);
      it.rectangle(20, 50, 30, 30);
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-23 16:43 UTC, skaldo commented
Hi @jesserockz may I ask you to have a brief look at my PR and let me know in case there's something missing?

Thanks a lot!

2023-05-11 21:42 UTC, max246 commented
@skaldo would be great to add a test

2023-05-17 17:27 UTC, skaldo commented
Do you have some examples? I have checked the implementation of a handful of displays, such as pcd8544, and could not find any.

Code is tested on ESP32, see screenshot in documentation PR: https://github.com/esphome/esphome-docs/pull/2360

Would be great if we could get this merged 🙂

2023-08-16 05:33 UTC, skaldo commented
Hi @jesserockz,
it has been almost a year since I have opened this PR.

I’m using my code since then without any issues on my CO2 monitor and would like to let others benefit from it as well.

Could you please let me know what needs to be done in order to get it merged?

Thank you.

2023-08-17 03:51 UTC, jesserockz requested changes
Apologies for the delay. 
Here is my review.
Generally the code looks good, just a few styling things really.

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/__init__.py
> +CODEOWNERS = ["@skaldo"]
Not required in both files
```suggestion
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/display.py
> +AUTO_LOAD = ["display"]
Not required for display platforms
```suggestion
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/display.py
> +            cv.Required(CONF_CS_PIN): pins.gpio_output_pin_schema,
This is part of `spi.spi_device_schema()` below
```suggestion
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/display.py
> +    .extend(spi.spi_device_schema())
```suggestion
    .extend(spi.spi_device_schema(cs_pin_required=True))
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.h
> +#define SHARPMEM_BIT_CLEAR (0x04)     // 0x20 in LSB format
These can go in the cpp file as static consts
```suggestion
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.cpp
> +
```suggestion

static const uint8_t SHARPMEM_BIT_WRITECMD = 0x01;  // 0x80 in LSB format
static const uint8_t SHARPMEM_BIT_VCOM = 0x02;      // 0x40 in LSB format
static const uint8_t SHARPMEM_BIT_CLEAR = 0x04;     // 0x20 in LSB format

```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.cpp
> +  TOGGLE_VCOM;
```suggestion
  this->transfer_byte(this->sharpmem_vcom_ | SHARPMEM_BIT_WRITECMD);
  this->sharpmem_vcom_ = this->sharpmem_vcom_ ? 0x00 : SHARPMEM_BIT_VCOM;
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.cpp
> +  _sharpmem_vcom = SHARPMEM_BIT_VCOM;
```suggestion
  this->sharpmem_vcom_ = SHARPMEM_BIT_VCOM;
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.cpp
> +  this->cs_->digital_write(false);
`spi_setup()` sets the pin state already
```suggestion
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.cpp
> +  this->cs_->digital_write(true);
The cs_pin should be inverted in the yaml config if this is the case.
```suggestion
  this->enable();
```

```yaml
display:
  platform: sharp_memory_lcd
  cs_pin:
    number :XX
    inverted: true
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.cpp
> +  this->disable();
As above
```suggestion
  this->disable();
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.cpp
> +  ESP_LOGCONFIG(TAG, "  Inverted colors: %s", this->invert_color_ ? "true" : "false");
```suggestion
  ESP_LOGCONFIG(TAG, "  Inverted colors: %s", TRUEFALSE(this->invert_color_);
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.cpp
> +    ESP_LOGW(TAG, "Position out of area: %dx%d", x, y);
Not really needed
```suggestion
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.h
> +  uint16_t width_ = 400, height_ = 240;
These will always be set with a value from config
```suggestion
  uint16_t width_;
  uint16_t height_;
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.h
> +  bool invert_color_ = false;
Same as above
```suggestion
  bool invert_color_;
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/display.py
> +            cv.Optional(CONF_INVERT_COLOR): cv.boolean,
```suggestion
            cv.Optional(CONF_INVERT_COLOR, default=False): cv.boolean,
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/display.py
> +        cg.add(var.set_invert_color(config[CONF_INVERT_COLOR]))
```suggestion
    cg.add(var.set_invert_color(config[CONF_INVERT_COLOR]))
```

2023-08-17 03:51 UTC, jesserockz commented on esphome/components/sharp_memory_lcd/display.py
> +CONF_SHARP_CS_PIN = "sharp_cs_pin"
Not used
```suggestion
```

2023-08-17 19:18 UTC, skaldo commented
Thanks @jesserockz for comment and rebase of my documentation PR.

I’ll check your review and adjust my PR till the end of this week.

2023-08-18 19:47 UTC, skaldo commented on esphome/components/sharp_memory_lcd/display.py
> +    .extend(spi.spi_device_schema())
Oh, nice, learned something!

2023-08-18 20:04 UTC, skaldo commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.cpp
> +  this->cs_->digital_write(true);
I have documented this in the documentation PR, thanks!

2023-08-18 20:07 UTC, skaldo commented
Thanks a lot for your feedback @jesserockz, especially for sharing the little tricks 😉 

In the next days, I will flash my device with the updated code to make sure that everything works as expected and will let you know here.

2023-08-24 19:13 UTC, skaldo commented
Hi @jesserockz,
sorry for delay, I had to find my device and resurrect my esphome instance.

All your comments are addressed and my CO2 sensor still works.

From my side, this can be merged.

Thank you!

<img src="https://github.com/esphome/esphome/assets/396663/fa909f97-8ab1-45d8-9b69-d59001f33ca5" width="300">

2023-09-09 12:29 UTC, clydebarrow requested changes
The good news is that with the clock rate dropped to 2MHz and changing the `transfer_...` calls to writes, I was able to get the driver working on a [Newt display](https://github.com/Phambili-Tech/Newt_Display/wiki).

2023-09-09 12:29 UTC, clydebarrow commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.cpp
> +    this->transfer_array(line, bytes_per_line + 2);
You're using `transfer_array` when you should be using `write_array`. The display has no data out pin, so you can't read from it (nor do I presume you want to.) All the `transfer_...` calls imply simultaneous read and write.

This fails with the new ESP-IDF hardware SPI implementation. The same goes for the `transfer_byte` calls.

Instead of copying and writing each line separately, I'd suggest you change `get_width_internal()` to allocate an extra two bytes per line, plus one extra byte for the whole buffer (`get_buffer_length()`) then  make `draw_absolute_pixel()` skip the first byte in each line, and write the whole buffer in one go without copying:

```
  for (size_t i = 0 ; i != height ; i++) {
    this->buffer_[i * bytes_per_line] = i + 1;
    this->buffer_[i * bytes_per_line + bytes_per_line - 1] = 0;
  }
  this->buffer_[this->get_buffer_length_() - 1] = 0;
  this->write_array(this->buffer_, this->get_buffer_length_());
  this->disable();

```

For bonus points add an extra byte at the beginning of the buffer for the `SHARPMEM_BIT_WRITECMD` byte.

2023-09-09 12:29 UTC, clydebarrow commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.h
> +                                             spi::CLOCK_PHASE_LEADING, spi::DATA_RATE_20MHZ> {
20MHz is too fast an SPI clock for the Sharp displays. The datasheet for the 2.7" display gives the maximum clock speed as 2MHz.

2023-09-09 12:29 UTC, clydebarrow commented on esphome/components/sharp_memory_lcd/sharp_memory_lcd.cpp
> +  }
```suggestion
  if (this->invert_color_ == color.is_on) {
    this->buffer_[y * width + x / 8] |= (0x01 << (x & 7));
  } else {
    this->buffer_[y * width + x / 8] &= ~(0x01 << (x & 7));
  }
```

2024-02-24 00:44 UTC, closed without merging