DIYLess OpenTherm device
OttoWinter/esphomeyaml pull request #3921
Opened 2022-10-20 18:09 UTC by khenderick

# What does this implement/fix?

This PR introduces support for the [DIYLess](https://diyless.com/) Master OpenTherm Shield, which is typically connected to a Wemos D1 mini (ESP8266 or ESP32 version).

The goal of this integration is not to provide a full-blown climate device, but rather expose a bunch of OpenTherm data and functionality. To make use of this data and functionality is up to the user, e.g. by use of automations in Home Assistant.

As this is my first contribution, I'm also looking for constructive criticism on how to enhance this integration where needed. For example, I'm a bit struggling with the code style and I'll most likely tune this a bit more. 

Note that I've not written documentation yet; I'll make a PR on the docs as soon as PR has the potential to be merged, as it's rather simple.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
diyless_opentherm:
  pin_in: 21
  pin_out: 22

sensor:
  - platform: diyless_opentherm
    ch_min_temperature:
      name: "CH minimum temperature"
    ch_max_temperature:
      name: "CH maximum temperature"
    dhw_min_temperature:
      name: "DHW minimum temperature"
    dhw_max_temperature:
      name: "DHW maximum temperature"
    pressure:
      name: "pressure"
    modulation:
      name: "modulation"
    boiler_temperature:
      name: "boiler temperature"
    return_temperature:
      name: "return temperature"

binary_sensor:
  - platform: diyless_opentherm
    ch_active:
      name: "CH active"
    dhw_active:
      name: "DHW active"
    flame_active:
      name: "flame active"
    fault:
      name: "fault"
    diagnostic:
      name: "diagnostic"

switch:
  - platform: diyless_opentherm
    ch_enabled:
      name: "CH enabled"
    dhw_enabled:
      name: "DHW enabled"

number:
  - platform: diyless_opentherm
    ch_setpoint_temperature:
      name: "CH setpoint temperature"
      min_value: 20.0
      max_value: 45.0
      step: 0.5
      restore_value: true
    dhw_setpoint_temperature:
      name: "DHW setpoint temperature"
      min_value: 38.0
      max_value: 60.0
      step: 0.5
      restore_value: true

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-10-20 18:17 UTC, khenderick commented
The component makes use of the OpenTherm library from https://github.com/ihormelnyk/opentherm_library which is a bit cleaned up to fit better in the implementation.

2022-10-20 18:51 UTC, khenderick commented
I'm not sure why `CI / Test tests/test1.yaml (pull_request)` fails. It seems unrelated to this component :thinking: .

2022-10-21 05:10 UTC, khenderick commented
After thinking about the current state of the code & the errors, I think I'll just merge stuff together to make it simpler and easier to maintain.

2022-11-13 15:04 UTC, Weissnix4711 commented
Hi, nice to see someone else is interested in getting OpenTherm working in ESPHome.

Sadly the approach you've taken here almost certainly won't be accepted.

As per the [docs](https://esphome.io/guides/contributing.html#runtime):

> Specifically methods like delay(10) should be avoided and delays above ~10ms are not permitted.

Yeah blocking for 32ms at a time (1ms per bit, 32 bit frame) probably won't pass.

Ideally we would rewrite the entire thing using interrupts. Or, the lazy approach I've taken is to simply [write a new remote protocol](https://github.com/Weissnix4711/esphome-opentherm-custom/tree/master/components/opentherm), as the remote transmitter / receiver components already make use of the ESP32's rmt peripheral. It ain't pretty, but it works.

2022-11-13 15:50 UTC, khenderick commented
Thanks for the valuable feedback. I was - incorrectly - looking at individual delays, the total delay is indeed at least 32ms per loop. While the code is already running quite a while without issues, I can indeed see the potential issues if combined with multiple other components.

Your approach seems interesting and from what I read in your code not too complex. I wonder if it would be possible to embed such a protocol transceiver inside my current component so from the outside (so in the yaml) users don't have to fiddle with OpenTherm data, but rather can just set numbers and read sensors :thinking:.

2022-11-14 17:50 UTC, Weissnix4711 commented
> embed such a protocol transceiver inside my current component so from the outside (so in the yaml) users don't have to fiddle with OpenTherm data, but rather can just set numbers and read sensors

Yes, that should be quite easy.

I'm not sure if that would be accepted into ESPHome. But either way, if you decide to go down that route, I would certainly encourage you to publish your work so others can use it as an external component.

2022-11-14 18:26 UTC, khenderick commented
Yeah, I've been thinking about it and I'm going to investigate the interrupt route first, to see what the possibilities are, with the main goal of native ESPHome integration.

If that would be no option or it would be unlikely that the protocol route wouldn't be accepted (as it indeed feels somewhat hack/workaround -ish), I'm definitely going to publish this PR as a stand alone component so it can be easily used.

2022-11-14 20:03 UTC, Weissnix4711 commented
Yes, hack is probably the best way to describe it.

I did hear some talk a while ago that an entire restructure of the remote components was wanted (for this reason, to create an easy way for devs to use the esp32's rmt to implement all sorts of weird protocols with little effort). The current system was created very much with IR and RF in mind more than anything else, hence also the name. That it could be used for so much more was an afterthought.

But I think that idea's been abandoned now.

Anyways, I don't know shit about interrupts or timers on ESP8266/32, but I can suggest you have a look at the existing CAN bus and tuya components as to how they handle the registration of individual sensors, buttons, switches, etc.

Also, there's a FR here: esphome/feature-requests#520 for opentherm you might want to look at, because it has a few other people's attempts to get OT working. Though most seem to have gone down the route of using either Ihor Melnyk or jpraus' libraries (again, not going to be accepted as 1. try not to use libraries whenever possible and 2. both block for long periods of time).

Also, if you want to chat on discord, matrix, whatever, lmk. I don't know if I'll be much help, but I can try lol.

2022-11-27 17:14 UTC, khenderick commented
The code of this PR is now also available in a separate repository ([khenderick/esphome-opentherm](https://github.com/khenderick/esphome-opentherm)) in case users want to test it. I'll keep the repo and this PR in sync.

Note: The component on my repo contains the delay as discussed above, so might not behave well with other functionality. In my own setup, it is the only component running, and it works fine.

I didn't find the time yet for making the code async or implement the remote protocol as there's some learning for me on that topic :sweat_smile:

2022-12-10 10:11 UTC, PierreAronnax commented
In my opinion, this integration should be hardware independent and not contain any hardware reading and writing.
That way it can be used easily for other hardware that receive OpenTherm over a uart (like the [Nodo-Shop OpenTherm Gateway](https://www.nodo-shop.nl/nl/ons-assortiment/211-opentherm-gateway.html)).
The actual support for the two devices should be moved to a different integration.

2022-12-10 10:40 UTC, khenderick commented
@PierreAronnax, the device you've linked uses the [OTGW firmware](http://otgw.tclcode.com/), which doesn't expose the raw OpenTherm data, but a higher-level protocol. For these devices there's already a [native Home Assistant integration](https://www.home-assistant.io/integrations/opentherm_gw/) available.

2022-12-10 10:53 UTC, PierreAronnax commented
That gateway has two processors, one PIC16F88/PIC16F1847 that uses the [OTGW firmware](http://otgw.tclcode.com/), and one Wemos D1 mini that currently runs https://github.com/rvdbreemen/OTGW-firmware and acts as a bridge between the PIC and the [native Home Assistant integration](https://www.home-assistant.io/integrations/opentherm_gw/) (or MQTT).

I am working on creating new firmware for the Wemos D1 mini using ESPHome. Initially only for the same bridge functionality. Eventually also exposing as sensors, and that's where this integration comes in.

2022-12-10 11:11 UTC, khenderick commented
If the ESP device has indeed access to the raw OT messages and not the OTGW pre-parsed protocol, it shouldn't be too hard to extend this code to also support UART.

If you would decide to work with this code, feel free to check out [khenderick/esp-opentherm](https://github.com/khenderick/esphome-opentherm) which is this code as external component.

2023-01-02 15:02 UTC, khenderick commented
I wonder if somebody from the core team could elaborate whether using a new remote transmitter protocol would be acceptable, and if so, whether the protocol definition should be inside the opentherm component folder, or in one of the remote_* folders. May I politely tag @jesserockz for this information?

2023-02-28 21:22 UTC, jesserockz requested changes

2023-02-28 21:22 UTC, jesserockz commented on esphome/components/opentherm/__init__.py
> +AUTO_LOAD = ["sensor", "binary_sensor", "switch", "number"]
Unless strictly necessary, all the platforms should not be auto loaded. The C++ code should be wrapped with `#ifdef USE_SENSOR` etc around those parts.

2023-02-28 21:28 UTC, ssieb commented on esphome/components/opentherm/__init__.py
> +AUTO_LOAD = ["sensor", "binary_sensor", "switch", "number"]
If you use listeners instead of putting the components in the hub, then you don't even need the ifdefs.

2023-03-01 16:44 UTC, khenderick commented on esphome/components/opentherm/__init__.py
> +AUTO_LOAD = ["sensor", "binary_sensor", "switch", "number"]
@jesserockz I made the changes, thanks for the feedback.

@ssieb I'm not sure I understand what you mean. Can you give me a few pointers or examples of such an implementation?

2023-05-31 05:41 UTC, khenderick commented
This branch isn't stale, but I'd like to get some feedback on the best way forward here. See for example https://github.com/esphome/esphome/pull/3921#issuecomment-1369015504.

The current code is already running for many months now, working without any issues.

2023-11-13 00:04 UTC, jesserockz requested changes

2023-11-13 00:04 UTC, jesserockz commented on esphome/components/opentherm/__init__.py
> +AUTO_LOAD = []
```suggestion
```

2023-11-13 00:04 UTC, jesserockz commented on esphome/components/opentherm/binary_sensor.py
> +        conf = config[key]
```suggestion
    if conf := config.get(key):
```

2023-11-13 00:04 UTC, jesserockz commented on esphome/components/opentherm/opentherm.h
> +    return data;
```suggestion
  uint32_t temperature_to_data_(float temperature) {
    temperature = clamp(temperature, 0.0f, 100.0f);
    return (uint32_t) (data * 256);
```

2023-11-13 00:04 UTC, jesserockz commented on esphome/components/opentherm/opentherm.h
> +  void request_(OpenThermMessageType type, OpenThermMessageID id, unsigned int data);
Please change all `unsigned int` to `uint32_t`
```suggestion
  void request_(OpenThermMessageType type, OpenThermMessageID id, uint32_t data);
```

2023-11-13 00:04 UTC, jesserockz commented on esphome/components/opentherm/opentherm.h
> +  sensor::Sensor *ch_min_temperature_sensor_{nullptr};
All of the sensors etc should be `protected` not `public`
A macro exists to make this a little easier and defines the pointer and the setter for you.

```suggestion
  SUB_SENSOR(ch_min_temperature)
```

2023-11-13 00:04 UTC, jesserockz commented on esphome/components/opentherm/number/__init__.py
> +
```suggestion

DEPENDENCIES = ["opentherm"]

```

2023-11-13 00:04 UTC, jesserockz commented on esphome/components/opentherm/number/__init__.py
> +            ).extend(cv.COMPONENT_SCHEMA),
```suggestion
            cv.Optional(CONF_CH_SETPOINT_TEMPERATURE): number.number_schema(
                CustomNumber,
                icon=ICON_HOME_THERMOMETER,
                unit_of_measurement=UNIT_CELSIUS,
            ).extend(
                {
                    cv.Required(CONF_MAX_VALUE): cv.float_,
                    cv.Required(CONF_MIN_VALUE): cv.float_,
                    cv.Required(CONF_STEP): cv.positive_float,
                    cv.Optional(CONF_MODE, default="BOX"): cv.enum(
                        number.NUMBER_MODES, upper=True
                    ),
                    cv.Optional(CONF_INITIAL_VALUE): cv.float_,
                    cv.Optional(CONF_RESTORE_VALUE): cv.boolean,
                }
            ).extend(cv.COMPONENT_SCHEMA),
```

2023-11-13 00:04 UTC, jesserockz commented on esphome/components/opentherm/number/__init__.py
> +        conf = config[key]
```suggestion
    if conf := config.get(key):
```

2023-11-13 00:04 UTC, jesserockz commented on esphome/components/opentherm/sensor.py
> +        conf = config[key]
```suggestion
    if conf := config.get(key):
```

2023-11-13 00:04 UTC, jesserockz commented on esphome/components/opentherm/switch/__init__.py
> +                class_=CustomSwitch,
The key for `class_` is not required as its the first and only positional argument
```suggestion
                CustomSwitch,
```

2023-11-13 00:04 UTC, jesserockz commented on esphome/components/opentherm/switch/__init__.py
> +CustomSwitch = opentherm.class_("CustomSwitch", switch.Switch, cg.Component)
These classes really should be named `OpenThermXXX`

```suggestion
OpenThermSwitch = opentherm.class_("OpenThermSwitch", switch.Switch, cg.Component)
```

2023-11-15 08:47 UTC, khenderick commented
Thanks for the feedback @jesserockz. I've made the requested changes.

I also brought the PR up-to-date with pending changes from my separate component repo. These changes include some new sensors etc, but also include a refactor to spread communication in time, getting rid of the "took a long time for an operation"-messages. I did my best to also apply your suggestions to that new code.

2024-02-14 07:58 UTC, khenderick commented
This PR is not stale from my end. 

I still hope that eventually I will get some constructive feedback and that it will get merged in. If it's unlikely this will ever be merged in, I also would like to know. To be honest, it's a bit demotivating to have a PR open for well over a year with some review feedback, but nothing about if and when it would or could be merged in.

2024-05-17 08:06 UTC, rotilho commented
Hello @khenderick! I'm very excited about this PR; thanks for putting in the effort. I really appreciate it.

I'm not part of the esphome team, but I've worked with GitHub before and see why nobody reviewed your PR. If you don't re-request the review, the PR won't appear in the list of PRs to be reviewed. I'd also mark the previous review as closed, just in case.

Again, thank you 🙏

2024-05-18 07:21 UTC, khenderick commented
> Hello @khenderick! I'm very excited about this PR; thanks for putting in the effort. I really appreciate it.
> 
> I'm not part of the esphome team, but I've worked with GitHub before and see why nobody reviewed your PR. If you don't re-request the review, the PR won't appear in the list of PRs to be reviewed. I'd also mark the previous review as closed, just in case.

I've re-requested the review, thanks for the tip. Hope it helps :crossed_fingers:.
 
> Again, thank you 🙏

You're welcome :slightly_smiling_face:. In case you didn't know yet, you can already use this component directly via https://github.com/khenderick/esphome-opentherm :+1:.

2024-07-31 23:35 UTC, jesserockz commented
https://github.com/esphome/esphome/pull/6645#issuecomment-2261656949

Please talk with the author of #6645 (and maybe #7169) and come to a concensus as to which PR we (reviewers) should spend our time on.

2024-09-16 02:22 UTC, jesserockz commented
Replaced by #6645

2024-09-16 02:22 UTC, closed without merging