Create E1.31 light effect for non-addressable lights
OttoWinter/esphomeyaml pull request #3932
Opened 2022-10-23 15:47 UTC by Almighty-Alpaca

# What does this implement/fix?

This PR implements the E1.31 light effect for non-addressable lights. This was previously only possible with a weird workaround by creating a partition with a length of 1.

To stick to the naming conventions of other light effects the addressable variant was renamed to `addressable_e131`, making this a breaking change as `e131` is now the non-addressable one. 

Since I do not currently have an addressable RGB strip I was only able to test the `addressable_e131` effect with the partition workaround. The non-addressable effect has been in use for many months in my personal setup without any issues.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# To test this change without checking out the PR in Git
external_components:
  - source: "github://Almighty-Alpaca/esphome@simple-e131-effect"
    components: [ "e131" ]

e131:
  method: multicast

light:
  - platform: rgb
    name: "RGB Light"
    id: led
    red: led_r
    green: led_g
    blue: led_b
    effects:
      - e131:
          universe: 1
          channels: RGB
  - platform: neopixelbus
    variant: WS2811
    pin: GPIO23
    num_leds: 60
    name: "ARGB Light"
    effects:
      - addressable_e131:
          universe: 2
          channels: RGB

output:
  - platform: ledc
    id: led_g
    pin: GPIO13
  - platform: ledc
    id: led_r
    pin: GPIO12
  - platform: ledc
    id: led_b
    pin: GPIO14
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-10-24 23:59 UTC, jesserockz requested changes
Virtual protected methods don't have trailing underscores

One more I could not add a review for on https://github.com/esphome/esphome/pull/3932/files#diff-78af0c8f4d80a0219497b177ac521e2edba7e350d92c96f6e59da29a769ef30aR36

2022-10-24 23:59 UTC, jesserockz commented on esphome/components/e131/e131_light_effect_base.h
> +  virtual bool process_(int universe, const E131Packet &packet) = 0; // NOLINT(readability-identifier-naming)
```suggestion
  virtual bool process(int universe, const E131Packet &packet) = 0;
```

2022-10-24 23:59 UTC, jesserockz commented on esphome/components/e131/e131_light_effect.h
> +  bool process_(int universe, const E131Packet &packet) override;
```suggestion
  bool process(int universe, const E131Packet &packet) override;
```

2022-10-24 23:59 UTC, jesserockz commented on esphome/components/e131/e131_addressable_light_effect.h
> +  bool process_(int universe, const E131Packet &packet) override;
```suggestion
  bool process(int universe, const E131Packet &packet) override;
```

2022-10-24 23:59 UTC, jesserockz commented on esphome/components/e131/e131_light_effect.cpp
> +bool esphome::e131::E131LightEffect::process_(int universe, const E131Packet &packet) {
```suggestion
bool esphome::e131::E131LightEffect::process(int universe, const E131Packet &packet) {
```

2022-10-25 20:26 UTC, Almighty-Alpaca commented
I've implemented the requested changes and also gone ahead and rebased the PR onto the latest commit on the dev branch.

2022-12-22 06:58 UTC, jesserockz requested changes
I don't have the capacity to investigate, but could you try to see if both addressable and non-addressable could be named `e131` and make a determination in codegen which class should be used? 

If the answer is "that won't work" then that is acceptable and I will have another think about changing `e131` to `addressable_e131`

2023-03-31 00:45 UTC, closed without merging