Haier climate
OttoWinter/esphomeyaml pull request #4001
Opened 2022-11-07 23:24 UTC by Yarikx

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-19 14:37 UTC, oxan requested changes
Looks good in general, some small things:

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/climate.py
> +SwingMode = haier_ns.enum("SwingMode")
Unused.
```suggestion
```

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/haier.h
> +static const uint8_t OFF_REQ[13] = {255, 255, 10, 0, 0, 0, 0, 0, 1, 1, 77, 3, 92};
We generally put these constants in the `.cpp` file, as they're not an API but more of an implementation detail.

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/haier.h
> +  std::set<climate::ClimateSwingMode> supported_swing_modes_{};
We generally put private variables last, not first.

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/haier.h
> +  HaierClimate() : PollingComponent(5 * 1000) {}
We define defaults in YAML, not in C++ code.
```suggestion
```

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/haier.h
> +  void setup() override {}
No need for an empty override.
```suggestion
```

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/haier.cpp
> +  dump_traits_(TAG);
```suggestion
  this->dump_traits_(TAG);
```
In general there seems to be a `this->` prefix in some places but not in others, it's nice to be consistent (general ESPHome style is to use `this->`).

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/haier.cpp
> +  }
You check if there's any data available, but then read `sizeof(data_)` bytes, but there might not be that many bytes available. This can block `loop()`, which is not nice as that may cause connectivity issues. 

I'd suggest something like this instead:
```cpp
  if (this->available() >= sizeof(this->data_)) {
    this->read_array(this->data_, sizeof(this->data_));
    if(this->data_[0] != 255 || this->data_[1] != 255)
      return;
    this->read_state_(this->data_, sizeof(this->data_));
  }
```
This changes the error handling though, in that it will always read `sizeof(data_)` bytes, even if the first two bytes aren't all ones. I don't know if that's the correct behaviour.

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/haier.cpp
> +  this->target_temperature = data[SET_TEMPERATURE] + MIN_VALID_TEMPERATURE;
Is it correct that `data[TEMPERATURE]` is an absolute temp, while `data[SET_TEMPERATURE]` is an offset w.r.t. the min valid temperature? Seems strange.

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/haier.cpp
> +      case climate::CLIMATE_FAN_QUIET:
I suppose this is just here to silence a missing-enumerator-in-switch warning, in which case this can just be a default:
```suggestion
      default:  // other modes are unsupported
```

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/haier.cpp
> +  data_[11] = 95;
It looks kinda strange to have the `COMMAND` index be a constant but to use magic values for the other indices.

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/haier.cpp
> +  dump_message_("Sent message", message, size);
This logs a different CRC than what is actually sent.
```suggestion
  message[size - 1] = get_checksum_(message, size);
  this->write_array(message, size);
  
  dump_message_("Sent message", message, size);
```

2023-02-19 14:37 UTC, oxan commented on esphome/components/haier/haier.cpp
> +  }
It might be nicer to dump this as a single hex message instead of spamming the logs, though I can see why doing it this way might be easier for debugging. Up to you.
```suggestion
  ESP_LOGV(TAG, "%s: %s", title, format_hex_pretty(message, size).c_str());
```
(requires `#include "esphome/core/helpers.h"`)

2023-02-19 21:48 UTC, Yarikx commented on esphome/components/haier/haier.cpp
> +  this->target_temperature = data[SET_TEMPERATURE] + MIN_VALID_TEMPERATURE;
Yes, the setpoint temperature starts from 16, so it has offset, but the current temperature is "absolute". It looks weird, but the current temperature can be outside the supported set temperature range.

2023-02-19 21:57 UTC, Yarikx commented on esphome/components/haier/haier.cpp
> +  data_[11] = 95;
Good point.
I believe the original reverse engineering of that protocol comes from this post https://blog.instalator.ru/archives/433 (you can google-translate it).
Those are specific parts that need to have specific values for Send command. The true meaning of those is unknown ¯\_(ツ)_/¯
I'll leave magic numbers, but add a comment about its unknown nature.

2023-02-19 22:02 UTC, Yarikx commented on esphome/components/haier/haier.cpp
> +  }
I would prefer to have it displayed byte-by-byte. As the protocol is basically byte-per-value, it's much easier to understand what's going on only by looking at it.
It's LOGV, so should not create too much spam by default.

2023-02-19 22:33 UTC, oxan commented on esphome/components/haier/haier.cpp
> +  this->target_temperature = data[SET_TEMPERATURE] + MIN_VALID_TEMPERATURE;
Ok, great. Just wanted to check it wasn't an oversight.

2023-02-21 21:05 UTC, Yarikx commented
Thanks @oxan for reviewing the code. I adjusted it according to your comments.  Please take a look, when you will have time.

2023-02-21 21:12 UTC, oxan approved these changes

2023-02-23 02:05 UTC, merged