small DisplayBuffer images and font update
OttoWinter/esphomeyaml pull request #4044
Opened 2022-11-18 13:55 UTC by nielsnl68

# What does this implement/fix?

Changed the way transparant images are saved. 
- TRANSPANT_BINARY: are now working the same way as BINARY images.
- TRANSPARENT_IMAGE: 🆕 replaces the the old TRANSPANT_BINARY.

Renaming the font `bottom` to `height` and allow the get the baseline and height.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-01-10 20:13 UTC, jesserockz requested changes

2023-01-10 20:13 UTC, jesserockz commented on esphome/components/animation/__init__.py
> +    else:  # config[CONF_TYPE] == "BINARY"/ "TRANSPANT_BINARY":
I would rather keep as an elif for any future changes
```suggestion
    elif config[CONF_TYPE] in ["BINARY", "TRANSPARENT_BINARY"]:
```

2023-01-10 20:36 UTC, nielsnl68 commented on esphome/components/animation/__init__.py
> +    else:  # config[CONF_TYPE] == "BINARY"/ "TRANSPANT_BINARY":
Okay, how about using a switch construction?

2023-01-10 23:15 UTC, jesserockz commented on esphome/components/animation/__init__.py
> +    else:  # config[CONF_TYPE] == "BINARY"/ "TRANSPANT_BINARY":
Switch would be fine too

2023-01-11 01:53 UTC, jesserockz approved these changes

2023-01-11 01:55 UTC, merged