Avoid compiling user services code if none are configured
OttoWinter/esphomeyaml pull request #4067
Opened 2022-11-22 16:21 UTC by bdraco

# What does this implement/fix?

Avoid compiling user services code if none are configured

It looks like we can ifdef some of this out if there are no services configured

I'm not 100% sure this isn't used for something else though

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-11-22 23:50 UTC, jesserockz requested changes
Because of custom user services via included headers, I dont think this is a safe operation to do...

2022-11-22 23:50 UTC, jesserockz commented on esphome/components/api/api_pb2_service.cpp
> +#ifdef USE_API_USER_SERVICES
These files are generated and cannot be manually ifdef'd like this...
See the first line of the file =)

2022-11-22 23:50 UTC, jesserockz commented on esphome/components/api/api_pb2_service.h
> +#ifdef USE_API_USER_SERVICES
Same here, cant manually change this file

2022-11-22 23:50 UTC, jesserockz commented on esphome/components/api/custom_api_device.h
> +#ifdef USE_API_USER_SERVICES
This is a class that a user can use in a custom component, we have no way of knowing if its used at config validation / code generation time

2022-11-23 01:28 UTC, bdraco commented
This one is probably not worth pursuing.  We need more runtime heap memory and this isn’t going to make much difference

2022-11-23 01:28 UTC, closed without merging