Add support for Lippert LP sensors in mopeka_pro_check component
OttoWinter/esphomeyaml pull request #4118
Opened 2022-11-29 15:35 UTC by rperciaccante

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [<link to issue>](https://github.com/esphome/feature-requests/issues/1988)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X ] ESP32
- [ X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
#No changes from existing YAML configuration: 
esp32_ble_tracker:

sensor:
  # Example using 20lb vertical propane tank.
  - platform: mopeka_pro_check
    mac_address: D3:75:F2:DC:16:91
    tank_type: 20LB_V
    temperature:
        name: "Propane test temp"
    level:
        name: "Propane test level"
    distance:
        name: "Propane test distance"
    battery_level:
        name: "Propane test battery level"

```

## Checklist:
  - [Y ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-11-29 17:53 UTC, spbrogan approved these changes
Thanks for adding support for a new model of sensor.  
You should probably add a documentation update here: https://github.com/esphome/esphome-docs/blob/current/components/sensor/mopeka_pro_check.rst  
to indicate support for the new sensor model.

2022-11-29 18:15 UTC, rperciaccante commented
> Thanks for adding support for a new model of sensor. You should probably add a documentation update here: https://github.com/esphome/esphome-docs/blob/current/components/sensor/mopeka_pro_check.rst to indicate support for the new sensor model.

I submitted a new PR for that as well - https://github.com/esphome/esphome-docs/pull/2493

2022-11-30 03:36 UTC, jesserockz requested changes

2022-11-30 03:36 UTC, jesserockz commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +
No commented code please
```suggestion
```

2022-11-30 03:36 UTC, jesserockz commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +      static_cast<SensorType>(manu_data.data[0]) != PLUS_BOTTOM_UP ) {
```suggestion
      static_cast<SensorType>(manu_data.data[0]) != PLUS_BOTTOM_UP) {
```

2022-11-30 03:36 UTC, jesserockz commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +
Removing extra blank line
```suggestion
```

2022-11-30 03:37 UTC, jesserockz commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
Add back original comment
```suggestion
// Now parse the data - See Datasheet for definition

```

2022-12-07 19:59 UTC, rperciaccante reviewed
Thank you

2022-12-08 05:34 UTC, spbrogan commented
Now that all "checks" are passing the content looks good.  Hopefully since this is such a small but important change (adding support for an additional sensor) this can get merged soon.   Thanks again.

2022-12-14 21:56 UTC, rperciaccante commented
@jesserockz was there something that I missed that prevents this from being merged?

2022-12-14 22:59 UTC, jesserockz commented
Sorry, just been too busy...haha

2022-12-14 23:00 UTC, jesserockz approved these changes

2023-02-08 22:07 UTC, merged