Climate PID Autotune Logging fixes
OttoWinter/esphomeyaml pull request #4136
Opened 2022-12-02 10:29 UTC by patrickcollins12

# What does this implement/fix?

[User requested](https://github.com/esphome/issues/issues/3858) changes to PID Autotune logging, to allow it to work with multiple concurrent PID Climate devices. 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [this issue](https://github.com/esphome/issues/issues/3858)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** no documentation changes needed.

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
#### FOR DEBUG 
## This is standard functionality, nothing added.

output:
  - platform: ledc
    id: console_heat_speed
    pin: GPIO32
  - platform: ledc
    id: console_fan_speed
    pin: GPIO25
climate:
  - platform: pid
    name: "Console Fan Thermostat"
    id: console_thermostat
    sensor: console_fan_temperature
    default_target_temperature: 21°C
    heat_output: console_heat_speed
    cool_output: console_fan_speed

switch:
  - platform: template
    name: "PID Climate Autotune"
    turn_on_action:
      - climate.pid.autotune: console_thermostat

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] N/A

2022-12-02 17:43 UTC, nagyrobi commented
@patrickcollins12 great!

Note:
- _!!! For PID autotuner you need to set AUTO (also called heat/cool) mode!_ message is missing the `%s:", name_.c_str()`
- Maybe an _Autotune has started. This can take a long time._ kind of message would be good to have at he very beginning once (also with name), to have _one_ feedback that things are OK.

2022-12-03 08:59 UTC, nagyrobi commented
PID config:

```yaml
climate:
- platform: pid
  id: heat_01_pid
  name: Iroda külső fűtés PID
  visual:
    min_temperature: 14
    max_temperature: 25
    temperature_step: 0.1
  sensor: heat_01_temp
  default_target_temperature: 19
  heat_output: heat_01_pwm
  control_parameters:
    kp: 0.0
    ki: 0.0
    kd: 0.0
```

Started Autotune for it, took 6 hours:

```
[19:58:27][W][pid.climate:158]: !!! For PID autotuner you need to set AUTO (also called heat/cool) mode!
[20:02:32][I][ota:113]: Boot seems successful, resetting boot loop counter.
[02:07:09][I][pid.autotune:119]: PID Autotune finished!
[02:07:09][I][pid.autotune:135]: PID Autotune - Iroda külső fűtés PID (iroda_kls_fts_pid):
[02:07:09][I][pid.autotune:136]:   State: Succeeded!
[02:07:09][W][pid.autotune:144]:   Oscillation Frequency is not symmetrical. PID parameters may be inaccurate!
[02:07:09][W][pid.autotune:147]:     This is usually because the heat and cool processes do not change the temperature at the
[02:07:09][W][pid.autotune:149]:     Please try reducing the positive_output value (or increase negative_output in case of a
[02:07:09][I][pid.autotune:157]:   Calculated PID parameters ("Ziegler-Nichols PID" rule):
[02:07:09][I][pid.autotune:158]:
[02:07:09][I][pid.autotune:159]:   control_parameters:
[02:07:09][I][pid.autotune:160]:     kp: 0.56172
[02:07:09][I][pid.autotune:161]:     ki: 0.00015
[02:07:09][I][pid.autotune:162]:     kd: 541.99701
[02:07:09][I][pid.autotune:163]:
[02:07:09][I][pid.autotune:164]:   Please copy these values into your YAML configuration! They will reset on the next reboot.
```

Observations:
- the ID in `PID Autotune - Iroda külső fűtés PID (iroda_kls_fts_pid):` is wrong. The ID of the component is `heat_01_pid`, not  `iroda_kls_fts_pid`
- as noted above a message stating the autotune has been started would be very useful. In my case I got the warning about heat/cool mode but if that would have not been the case, I had no indication that it started something
- I think it would be nice to include the name or ID in _each_ line because when multiple autotunes run in parallel, their log messages are not queued into one, they might interleave if they wanna print out in the same time. I was thinking of something like adding the ID to the TAG:
```
[02:07:09][I][pid.autotune.heat_01_pid:119]: PID Autotune finished!
[02:07:09][I][pid.autotune.heat_01_pid:135]: PID Autotune - Iroda külső fűtés PID (iroda_kls_fts_pid):
[02:07:09][I][pid.autotune.heat_01_pid:136]:   State: Succeeded!
---
```

2022-12-03 20:14 UTC, gabormagyar commented
This might be better as a separate issue but  could you please also add a way to query the results after the autotune has completed?

I just completed two autotunes but weren't connected to the logs when the results were printed, so I don't know the results. Also I don't know if there's a way to get them back currently.

Could the logs keep going and print the results periodically? The device is getting reinstalled after a successful autotune anyway.

2022-12-03 20:22 UTC, gabormagyar commented
I agree that the initial message would be a good idea, maybe it could also include an explanation that initial temperature values are going to be `nan` until a fresh update is received from the sensor, as I described here:

https://github.com/esphome/issues/issues/3860#issue-1471090612

2022-12-03 20:29 UTC, nagyrobi commented
> a way to query the results after the autotune has completed

It is possible by adding the Kp Ki Kd sensors to the config, before you do the autotune:
https://esphome.io/components/climate/pid.html#pid-sensor

2022-12-03 20:36 UTC, nagyrobi commented
> Could the logs maybe keep going and print the results periodically?

What I did before this patch was to open a putty session to my HA as below, and keep it runnig until finished:

_In Home Assistant’s SSH addon, configure a username and a password, and disable Protection Mode (please assess the risks you take with that). Then, for example to access the logs form a device through an SSH client, log in, and you can use a command like:_
`docker exec -it addon_15ef4d2f_esphome esphome logs /config/esphome/garage-door.yaml`

2022-12-04 23:48 UTC, mgabor3141 commented
I was pleasantly surprised on my second autotune that the results are in fact printed every time you connect after it has completed. The issue I described above is incorrect, what I experienced was most likely an interrupted autotune due to a brief power outage.

2022-12-04 23:50 UTC, gabormagyar commented
I was pleasantly surprised on my second autotune that the results are in fact printed every time you connect after it has completed. The issue I described above is incorrect, what I experienced was most likely an interrupted autotune due to a brief power outage.

2022-12-05 06:47 UTC, jesserockz approved these changes, later dismissed

2022-12-10 20:38 UTC, nagyrobi commented
And yes! The results are printed in the logs after connecting later! Great, thank you @patrickcollins12 !

@jesserockz this is good to be merged!

2023-01-01 00:44 UTC, patrickcollins12 commented
OK a few changes included to address the above requests. I only tested with one instance of a pid controller as I don't have a system with multiple PID controllers. @nagyrobi please test with multiple controllers.

Also I can confirm that it will now reprint the successful autotune results if you reconnect to the logs (so long as the ESP hasn't rebooted).

Here is an example of the logs.

```
[11:38:11][D][switch:013]: 'PID Climate Autotune' Turning ON.
[11:38:11][I][pid.climate.console_fan_thermostat:158]: Autotune has started. This can take a long time depending on the responsiveness of your system. Your system output will be altered to deliberately oscillate above and below the setpoint multiple times. Until your sensor provides a reading, the autotuner may display 'nan'
[11:38:11][W][pid.climate.console_fan_thermostat:166]: !!! For PID autotuner you need to set AUTO (also called heat/cool) mode! Console Fan Thermostat
[11:38:11][D][pid.autotune.console_fan_thermostat:184]: PID Autotune:
[11:38:11][D][pid.autotune.console_fan_thermostat:185]:   Autotune is still running!
[11:38:11][D][pid.autotune.console_fan_thermostat:186]:   Status: Trying to reach nan °C
[11:38:11][D][pid.autotune.console_fan_thermostat:187]:   Stats so far:
```

2023-01-01 07:47 UTC, nagyrobi commented
Great! Thanks. Checkin today...

2023-01-01 18:04 UTC, nagyrobi commented
Tested with multiple controllers, prints the internal ID to the log tags, and that accomplishes the request.

One very small suggestion: it would be very useful to reprint the `Autotune is still running!`  message when you reconnect to the logs while it's still running and there's no result. Some very slow cases can take long hours, reconnecting with the logs and seeing that would help confirming that no reboot or anything else interrupted it.

2023-01-02 05:08 UTC, patrickcollins12 commented
Great! @jesserockz can you please merge?

I'll consider this other request, not sure how to do that, but if so let's create another ticket for that.

2023-01-18 00:06 UTC, jesserockz commented
Please fix the CI issues found.

Also, I dont like that the `TAG` has been overwritten with the id, the TAG should not be changed, instead you either need to prefix every log message, or put a "block start" / "block end" message before a group of logs

2023-02-03 07:18 UTC, patrickcollins12 commented
Hey @jesserockz ok i fixed this per your request not to alter the TAG. @nagyrobi please note that that formatting has changed a bit, but hopefully still works for you. It took me a while to please the almighty God of Clang.

2023-02-06 23:54 UTC, jesserockz requested changes

2023-02-06 23:54 UTC, jesserockz commented on esphome/components/pid/pid_autotuner.cpp
> +    // ESP_LOGV(TAG, "Autotune: Turning output to %.1f%%", output * 100);
```suggestion
```

2023-02-06 23:54 UTC, jesserockz commented on esphome/components/pid/pid_autotuner.cpp
> +    // ESP_LOGV(TAG, "Autotune: Detected Zero-Cross at %u", now);
```suggestion
```

2023-02-06 23:54 UTC, jesserockz commented on esphome/components/pid/pid_autotuner.cpp
> +      // ESP_LOGV(TAG, "  dt: %u", dt);
```suggestion
```

2023-02-06 23:54 UTC, jesserockz commented on esphome/components/pid/pid_autotuner.cpp
> +      // ESP_LOGV(TAG, "Autotune: Phase Max: %f", phase_max);
```suggestion
```

2023-02-06 23:54 UTC, jesserockz commented on esphome/components/pid/pid_autotuner.cpp
> +      // ESP_LOGV(TAG, "Autotune: Phase Min: %f", phase_min);
```suggestion
```

2023-02-07 00:19 UTC, patrickcollins12 commented
damn, sorry to deploy those two files... my bad, thanks for deleting.

didn't like those log entries? :)

2023-02-07 11:24 UTC, patrickcollins12 commented
ready @jesserockz

2023-02-09 09:36 UTC, jesserockz approved these changes

2023-02-09 09:37 UTC, merged