Use ENTITY_CATEGORY_CONFIG for sprinkler config switches.
OttoWinter/esphomeyaml pull request #4141
Opened 2022-12-04 11:07 UTC by schinckel

# What does this implement/fix?

This sets the entity_category for the valve/sprinkler configuration switches: ie the valve enable switch, reverse switch and so on.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-12-04 19:06 UTC, jesserockz requested changes

2022-12-04 19:06 UTC, jesserockz commented on esphome/components/sprinkler/__init__.py
> +            switch.switch_schema(SprinklerControllerSwitch, entity_category=ENTITY_CATEGORY_CONFIG),
```suggestion
            switch.switch_schema(
                SprinklerControllerSwitch, entity_category=ENTITY_CATEGORY_CONFIG
            ),
```

2022-12-04 19:06 UTC, jesserockz commented on esphome/components/sprinkler/__init__.py
> +            switch.switch_schema(SprinklerControllerSwitch, entity_category=ENTITY_CATEGORY_CONFIG),
```suggestion
            switch.switch_schema(
                SprinklerControllerSwitch, entity_category=ENTITY_CATEGORY_CONFIG
            ),
```

2022-12-04 19:06 UTC, jesserockz commented on esphome/components/sprinkler/__init__.py
> +            switch.switch_schema(SprinklerControllerSwitch, entity_category=ENTITY_CATEGORY_CONFIG),
```suggestion
            switch.switch_schema(
                SprinklerControllerSwitch, entity_category=ENTITY_CATEGORY_CONFIG
            ),
```

2022-12-04 19:26 UTC, kbx81 commented
LGTM -- although, @schinckel should we be adding this for the valve switch itself, too? (Not the GPIO switch, the controller's managed switch _for_ the GPIO switch.)

2022-12-04 19:27 UTC, kbx81 commented
Also, you mentioned the reverse switch in the PR desc., but I don't see it updated in the PR. 🤔

2022-12-04 22:12 UTC, schinckel commented
> Also, you mentioned the reverse switch in the PR desc., but I don't see it updated in the PR. 🤔

Fixed. That's the one I don't use, so I didn't notice when I tested that it wasn't changed.

2022-12-04 22:13 UTC, schinckel commented
> LGTM -- although, @schinckel should we be adding this for the valve switch itself, too? (Not the GPIO switch, the controller's managed switch _for_ the GPIO switch.)

Yeah, I'm not sure. I use those to manually trigger just a single zone, so I saw them as actions, rather than configuration items.

I'm happy to switch (!!) them over to `config` if that's the general consensus though.

2022-12-05 07:24 UTC, kbx81 commented
> ...I saw them as actions, rather than configuration items.

Yeah, you're right. At first I didn't completely understand what this change was doing, but I had a closer look and now it makes sense. I agree, the valves themselves aren't really configuration items.

Could you fix the issues the linter is calling out? Then we can probably merge this in.

2022-12-05 07:30 UTC, kbx81 requested changes
Formatting

2022-12-05 07:30 UTC, kbx81 commented on esphome/components/sprinkler/__init__.py
> +            switch.switch_schema(SprinklerControllerSwitch, entity_category=ENTITY_CATEGORY_CONFIG),
```suggestion
            switch.switch_schema(
                 SprinklerControllerSwitch, entity_category=ENTITY_CATEGORY_CONFIG
             ),
```

2022-12-05 07:39 UTC, kbx81 requested changes
Formatting...take 2

2022-12-05 07:39 UTC, kbx81 commented on esphome/components/sprinkler/__init__.py
> +             ),
```suggestion
                SprinklerControllerSwitch, entity_category=ENTITY_CATEGORY_CONFIG
            ),
```

2022-12-05 07:41 UTC, schinckel commented on esphome/components/sprinkler/__init__.py
> +             ),
Yeah, I saw that one too. Forgot to `pre-commit run` in this repo, so that should take care of the linting.

2022-12-05 18:37 UTC, jesserockz approved these changes

2022-12-06 03:00 UTC, kbx81 approved these changes

2022-12-06 03:00 UTC, merged