Add support for Airthings Wave Radon
OttoWinter/esphomeyaml pull request #4166
Opened 2022-12-09 05:07 UTC by willhaines

# What does this implement/fix?

Adds support for Airthings Wave Radon device, a slightly cheaper alternative to the already-supported Wave Plus. See [this vendor page](https://help.airthings.com/en/articles/5161848-what-s-the-difference-between-airthings-smart-products) for more info about the feature comparison.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
ble_client:
  - mac_address: F4:60:77:XX:XX:XX
    id: airthings01

sensor:
  - platform: airthings_wave_radon
    ble_client_id: airthings01
    update_interval: 5min #default
    temperature:
      name: "WaveRadon Temperature"
    radon:
      name: "WaveRadon Radon"
    radon_long_term:
      name: "WaveRadon Radon Long Term"
    humidity:
      name: "WaveRadon Humidity"

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-09-12 22:37 UTC, jesserockz requested changes
Please refactor this to use the `airthings_wave_base class like the mini and plus if possible.

2023-12-19 04:51 UTC, willhaines commented
@jesserockz I've updated the `airthings_wave_radon` component to make use of the `airthings_wave_base` and tested the latest code by reading my Airthings Wave Radon device.

2024-07-29 04:51 UTC, jesserockz requested changes
Please add some test yaml files

2024-07-29 04:51 UTC, jesserockz commented on esphome/components/airthings_wave_radon/airthings_wave_radon.h
> +  void set_radon_long_term(sensor::Sensor *radon_long_term) { radon_long_term_sensor_ = radon_long_term; }
```suggestion
  void set_radon(sensor::Sensor *radon) { this->radon_sensor_ = radon; }
  void set_radon_long_term(sensor::Sensor *radon_long_term) { this->radon_long_term_sensor_ = radon_long_term; }
```

2025-09-19 01:19 UTC, closed without merging