Added in mmc5603 code
OttoWinter/esphomeyaml pull request #4175
Opened 2022-12-12 11:34 UTC by benhoff

# What does this implement/fix?

Implements code for a MMC5603 magnet sensor

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2524

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esphome:
  name: water

esp8266:
  board: d1_mini

# Enable logging
logger:

i2c:
  sda: D2
  scl: D1
  scan: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: mmc5603
    address: 0x30
    field_strength_x:
      name: "HMC5883L Field Strength X"
    field_strength_y:
      name: "HMC5883L Field Strength Y"
    field_strength_z:
      name: "HMC5883L Field Strength Z"
    update_interval: 1s

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-12-22 23:43 UTC, jesserockz requested changes
Minor changes, otherwise fine

2022-12-22 23:43 UTC, jesserockz commented on esphome/components/mmc5603/sensor.py
> +    return validate_enum_bound
Not used anywhere?

2022-12-22 23:43 UTC, jesserockz commented on esphome/components/mmc5603/mmc5603.h
> +  MMC5603Datarate datarate_{MMC5603_DATARATE_150_0_HZ};
Value is always set from config/codegen
```suggestion
  MMC5603Datarate datarate_;
```

2022-12-22 23:43 UTC, jesserockz commented on esphome/components/mmc5603/mmc5603.cpp
> +  // if (!isContinuousMode())
No commented code please
```suggestion
```

2022-12-22 23:43 UTC, jesserockz commented on esphome/components/mmc5603/mmc5603.cpp
> +  status = status << 6;
Never used again?
```suggestion
```

2023-03-31 21:03 UTC, benhoff commented
@jesserockz , do I need to do anything like bump this? Should I let the bot close it as stale? I am using this PR for one of my devices.

2023-04-04 02:33 UTC, jesserockz approved these changes

2023-04-04 02:34 UTC, jesserockz commented
Sorry for not getting to this earlier.

2023-04-04 02:47 UTC, merged