Add ENS160 Sensor
OttoWinter/esphomeyaml pull request #4243
Opened 2022-12-30 10:35 UTC by vincentscode

# What does this implement/fix?

This implements the ENS160 Air Quality Sensor.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2569

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: ens160
    eco2:
      name: "eCO2 Value"
    tvoc:
      name: "Total Volatile Organic Compounds"
    aqi:
      name: "Air Quality Index"
    update_interval: 5s

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2022-12-30 16:09 UTC, vincentscode commented
Unfortunately I do not know what the linter is trying to tell me here. It would be great if somebody could explain it. The code is working as intended.

2022-12-30 21:33 UTC, stas-sl commented
> Unfortunately I do not know what the linter is trying to tell me here. It would be great if somebody could explain it. The code is working as intended.

```cpp
uint8_t buf_eco2[2];
uint8_t buf_tvoc[2];
uint8_t data_aqi = 0;
this->read_register(ENS160_REG_DATA_ECO2, buf_eco2, sizeof(buf_eco2));
this->read_register(ENS160_REG_DATA_TVOC, buf_tvoc, sizeof(buf_tvoc));
this->read_register(ENS160_REG_DATA_AQI, &data_aqi, sizeof(data_aqi));

uint16_t data_eco2 = encode_uint16(buf_eco2[1], buf_eco2[0]);
uint16_t data_tvoc = ENS160_CONCAT_BYTES(buf_tvoc[1], buf_tvoc[0]);
```

Maybe it doesn't like that `buf_eco2` and `buf_tvoc` could be potentially uninitialised?

Probably it could be rewritten as:
```cpp
auto buf_eco2 = this->read_bytes<2>(ENS160_REG_DATA_ECO2);
auto buf_tvoc = this->read_bytes<2>(ENS160_REG_DATA_TVOC);
auto buf_aqi = this->read_bytes<1>(ENS160_REG_DATA_AQI);

uint16_t data_eco2 = encode_uint16((*buf_eco2)[1], (*buf_eco2)[0]);
uint16_t data_tvoc = encode_uint16((*buf_tvoc)[1], (*buf_tvoc)[0]);
```
Here I'm also using ESPHome's helper `encode_uint16` instead of `ENS160_CONCAT_BYTES`. Additionally a good idea would be to check if `read_bytes` returned something: `if (buf_eco2.has_value()) ...`

2022-12-30 22:09 UTC, vincentscode commented
That seems to have worked and is way cleaner than before, thanks for the explanation!

2023-01-06 03:47 UTC, NonaSuomy commented
When will this get merged? Would love to use it. Just got this sensor a few weeks ago!

2023-01-07 17:55 UTC, vincentscode commented
@NonaSuomy T/H Compensation has already been implemented. Currently it is still missing documentation but it is basically the same as for the CCS811 and I will add documentation for it soon.

2023-01-09 04:39 UTC, NonaSuomy commented
> @NonaSuomy T/H Compensation has already been implemented. I just added documentation - it's basically the same as with the CCS811 sensor.

2023-01-09 04:40 UTC, NonaSuomy commented
Got it working thank you so much! Thought I really messed up impulse buying this module 😆 

```yaml
# ENS160 + AHT21 Module https://www.aliexpress.us/item/3256804712105923.html

# Define the I2C device for iFan04 to the Test Points on the back of the board.
# GPIO04 - TP11 D_RX (SDA)
# GPIO05 - TP10 D_TX (SCL)
i2c:
  id: i2c_component
  sda: 4
  scl: 5
  scan: true

external_components:
  - source: github://pr#4243
    components:
      - ens160

sensor:
  - platform: aht10
    id: aht21_sensor
    address: 0x38
    temperature:
      name: "AHT21 Sensor Temperature"
      id: aht21_sensor_temp
    humidity:
      name: "AHT21 Sensor Humidity"
      id: aht21_sensor_humi
    update_interval: 55s

  - platform: ens160
    id: ens160_sensor
    address: 0x53
    eco2:
      name: "ENS160 Sensor eCO2"
      id: ens160_sensor_eco2
    tvoc:
      name: "ENS160 Sensor Total Volatile Organic Compounds"
      id: ens160_sensor_tvoc
    aqi:
      name: "ENS160 Sensor Air Quality Index"
      id: ens160_sensor_aqi
    # Inject the temp/humi data from the AHT21 into the ENS160 attached module for compensation.
    # Makes the gas results more accurate.
    temperature: aht21_sensor_temp
    humidity: aht21_sensor_humi
    update_interval: 60s
    ```

![image](https://user-images.githubusercontent.com/1906575/211242058-90ecad3d-5771-4da4-acc6-8662ee973496.png)

2023-01-11 09:48 UTC, NonaSuomy commented
Is it possible to currently access these separate registers from the module? 
![985EC278-2249-4C5D-A3A9-903AE85962D4](https://user-images.githubusercontent.com/1906575/211773378-ac63e2c9-1c59-4aec-9c8d-1d93590bb00a.jpeg)

2023-01-11 10:17 UTC, vincentscode commented
I did not implement that as those values have no real meaning without proper calibration (as stated in the datasheet). Feel free to add it tho.

2023-01-12 06:04 UTC, NonaSuomy commented
They should have real meaning as that is how it computes the score by tallying up each of those items.

2023-01-12 06:18 UTC, vincentscode commented
Well, not really. The combination of them has been calibrated. On their own they are not calibrated and by that not really useful.

2023-02-05 13:29 UTC, Carpenter64 commented
> ```yaml
>       id: aht21_sensor_temp
> ```

Hi,

Thank you, it work for dfRobot SEN0335 too (ENS160 + BM280), I can now use it:
https://www.dfrobot.com/product-2064.html

It seems there is 2 versions of SEN0335 the other is with CCS811 instead of ENS160.
Beware the package itself said that it was CCS811, but it was ENS160 inside for mine...

2023-02-05 16:16 UTC, NonaSuomy commented
> ```yaml
> ```yaml
>       id: aht21_sensor_temp
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> Hi,
> Thank you, it work for dfRobot SEN0335 too (ENS160 + BM280), I can now use it:
> https://www.dfrobot.com/product-2064.html
> It seems there is 2 versions of SEN0335 the other is with CCS811 instead of ENS160.
> Beware the package itself said that it was CCS811, but it was ENS160 inside for mine...
> ```

The CCS811 is the predecessor to the ENS160, it’s no longer in production as the ENS160 replaces it.

2023-02-06 00:39 UTC, tomasrojasc commented
@NonaSuomy how did you get ENS160 to work? I can only get data from the AHT21 :(

2023-02-06 00:42 UTC, tomasrojasc commented
This is the esphome program:
```
esphome:
  name: test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GDhGfiOvVrjBgf0oxyh8OA3K8BwQjRDYyBR7Gc3ylQY="

ota:
  password: "e0aa4adcd9c72fa672317a9dceba9511"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "HHtP30QR7frb"

  
# Example configuration entry
dallas:
  - pin: 14  # D5

i2c:
  id: i2c_component
  sda: 4
  scl: 5
  scan: true

external_components:
  - source: github://pr#4243
    components:
      - ens160

# ENS160 + AHT21 Module https://www.aliexpress.us/item/3256804712105923.html
# Define the I2C device for iFan04 to the Test Points on the back of the board.
# GPIO04 - TP11 D_RX (SDA)
# GPIO05 - TP10 D_TX (SCL)

# Individual sensors
sensor:
  - platform: dallas
    address: 0xcb99e4e90264ff28
    name: "Temperatura pieza"

  - platform: aht10
    id: aht21_sensor
    address: 0x38
    temperature:
      name: "AHT21 Sensor Temperature"
      id: aht21_sensor_temp
    humidity:
      name: "AHT21 Sensor Humidity"
      id: aht21_sensor_humi
    update_interval: 55s

  - platform: ens160
    id: ens160_sensor
    address: 0x53
    eco2:
      name: "ENS160 Sensor eCO2"
      id: ens160_sensor_eco2
    tvoc:
      name: "ENS160 Sensor Total Volatile Organic Compounds"
      id: ens160_sensor_tvoc
    aqi:
      name: "ENS160 Sensor Air Quality Index"
      id: ens160_sensor_aqi
    temperature: aht21_sensor_temp
    humidity: aht21_sensor_humi
    update_interval: 60s
```
And this is what the log returns me
```
[21:37:25][I][app:102]: ESPHome version 2022.12.8 compiled on Feb  5 2023, 21:21:03
[21:37:25][C][wifi:504]: WiFi:
[21:37:25][C][wifi:362]:   Local MAC: E0:98:06:8A:37:19
[21:37:25][C][wifi:363]:   SSID: [redacted]
[21:37:25][C][wifi:364]:   IP Address: 192.168.1.89
[21:37:25][C][wifi:365]:   BSSID: [redacted]
[21:37:25][C][wifi:367]:   Hostname: 'test'
[21:37:25][C][wifi:369]:   Signal strength: -71 dB ▂▄▆█
[21:37:25][C][wifi:373]:   Channel: 6
[21:37:25][C][wifi:374]:   Subnet: 255.255.255.0
[21:37:25][C][wifi:375]:   Gateway: 192.168.1.1
[21:37:25][C][wifi:376]:   DNS1: 200.28.4.130
[21:37:25][C][wifi:377]:   DNS2: 200.28.4.129
[21:37:25][C][logger:293]: Logger:
[21:37:25][C][logger:294]:   Level: DEBUG
[21:37:25][C][logger:295]:   Log Baud Rate: 115200
[21:37:25][C][logger:296]:   Hardware UART: UART0
[21:37:25][C][i2c.arduino:052]: I2C Bus:
[21:37:25][C][i2c.arduino:053]:   SDA Pin: GPIO4
[21:37:25][C][i2c.arduino:054]:   SCL Pin: GPIO5
[21:37:25][C][i2c.arduino:055]:   Frequency: 50000 Hz
[21:37:25][C][i2c.arduino:058]:   Recovery: bus successfully recovered
[21:37:25][I][i2c.arduino:068]: Results from i2c bus scan:
[21:37:25][I][i2c.arduino:074]: Found i2c device at address 0x38
[21:37:25][I][i2c.arduino:074]: Found i2c device at address 0x53
[21:37:25][C][dallas.sensor:075]: DallasComponent:
[21:37:25][C][dallas.sensor:076]:   Pin: GPIO14
[21:37:25][C][dallas.sensor:077]:   Update Interval: 60.0s
[21:37:25][D][dallas.sensor:082]:   Found sensors:
[21:37:25][D][dallas.sensor:084]:     0xcb99e4e90264ff28
[21:37:25][C][dallas.sensor:089]:   Device 'Temperatura pieza'
[21:37:25][C][dallas.sensor:089]:     Device Class: 'temperature'
[21:37:25][C][dallas.sensor:089]:     State Class: 'measurement'
[21:37:25][C][dallas.sensor:089]:     Unit of Measurement: '°C'
[21:37:25][C][dallas.sensor:089]:     Accuracy Decimals: 1
[21:37:25][C][dallas.sensor:097]:     Address: 0xcb99e4e90264ff28
[21:37:25][C][dallas.sensor:098]:     Resolution: 12
[21:37:25][C][aht10:136]: AHT10:
[21:37:25][C][aht10:137]:   Address: 0x38
[21:37:25][C][aht10:141]:   Temperature 'AHT21 Sensor Temperature'
[21:37:25][C][aht10:141]:     Device Class: 'temperature'
[21:37:25][C][aht10:141]:     State Class: 'measurement'
[21:37:25][C][aht10:141]:     Unit of Measurement: '°C'
[21:37:25][C][aht10:141]:     Accuracy Decimals: 2
[21:37:25][C][aht10:142]:   Humidity 'AHT21 Sensor Humidity'
[21:37:25][C][aht10:142]:     Device Class: 'humidity'
[21:37:25][C][aht10:142]:     State Class: 'measurement'
[21:37:25][C][aht10:142]:     Unit of Measurement: '%'
[21:37:25][C][aht10:142]:     Accuracy Decimals: 2
[21:37:25][C][ens160:283]: ENS160
[21:37:25][C][ens160:284]:   Address: 0x53
[21:37:25][C][ens160:285]:   Update Interval: 60.0s
[21:37:25][C][ens160:286]:   CO2 Sensor 'ENS160 Sensor eCO2'
[21:37:25][C][ens160:286]:     Device Class: 'carbon_dioxide'
[21:37:25][C][ens160:286]:     State Class: 'measurement'
[21:37:25][C][ens160:286]:     Unit of Measurement: 'ppm'
[21:37:25][C][ens160:286]:     Accuracy Decimals: 1
[21:37:25][C][ens160:286]:     Icon: 'mdi:molecule-co2'
[21:37:25][C][ens160:287]:   TVOC Sensor 'ENS160 Sensor Total Volatile Organic Compounds'
[21:37:25][C][ens160:287]:     Device Class: 'volatile_organic_compounds'
[21:37:25][C][ens160:287]:     State Class: 'measurement'
[21:37:25][C][ens160:287]:     Unit of Measurement: 'ppb'
[21:37:25][C][ens160:287]:     Accuracy Decimals: 1
[21:37:25][C][ens160:287]:     Icon: 'mdi:radiator'
[21:37:25][C][ens160:288]:   AQI Sensor 'ENS160 Sensor Air Quality Index'
[21:37:25][C][ens160:288]:     Device Class: 'aqi'
[21:37:25][C][ens160:288]:     State Class: 'measurement'
[21:37:25][C][ens160:288]:     Unit of Measurement: 'index'
[21:37:25][C][ens160:288]:     Accuracy Decimals: 0
[21:37:25][C][ens160:288]:     Icon: 'mdi:chemical-weapon'
[21:37:25][C][ens160:291]:   Temperature Compensation 'AHT21 Sensor Temperature'
[21:37:25][C][ens160:291]:     Device Class: 'temperature'
[21:37:25][C][ens160:291]:     State Class: 'measurement'
[21:37:25][C][ens160:291]:     Unit of Measurement: '°C'
[21:37:25][C][ens160:291]:     Accuracy Decimals: 2
[21:37:25][C][ens160:292]:   Humidity Compensation 'AHT21 Sensor Humidity'
[21:37:25][C][ens160:292]:     Device Class: 'humidity'
[21:37:25][C][ens160:292]:     State Class: 'measurement'
[21:37:25][C][ens160:292]:     Unit of Measurement: '%'
[21:37:25][C][ens160:292]:     Accuracy Decimals: 2
[21:37:25][W][ens160:296]: Communication failed! Is the sensor connected?
[21:37:25][C][mdns:103]: mDNS:
[21:37:25][C][mdns:104]:   Hostname: test
[21:37:25][C][ota:093]: Over-The-Air Updates:
[21:37:25][C][ota:094]:   Address: test.local:8266
[21:37:25][C][ota:097]:   Using Password.
[21:37:25][C][api:138]: API Server:
[21:37:25][C][api:139]:   Address: test.local:6053
[21:37:25][C][api:141]:   Using noise encryption: YES
[21:38:09][D][aht10:083]: AHT10 is busy, waiting...
[21:38:09][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 24.50829 °C with 2 decimals of accuracy
[21:38:09][D][sensor:126]: 'AHT21 Sensor Humidity': Sending state 52.25134 % with 2 decimals of accuracy
[21:38:19][D][dallas.sensor:143]: 'Temperatura pieza': Got Temperature=25.2°C
[21:38:19][D][sensor:126]: 'Temperatura pieza': Sending state 25.18750 °C with 1 decimals of accuracy
[21:39:04][D][aht10:083]: AHT10 is busy, waiting...
[21:39:04][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 24.21131 °C with 2 decimals of accuracy
[21:39:04][D][sensor:126]: 'AHT21 Sensor Humidity': Sending state 50.48037 % with 2 decimals of accuracy
[21:39:19][D][dallas.sensor:143]: 'Temperatura pieza': Got Temperature=25.2°C
[21:39:19][D][sensor:126]: 'Temperatura pieza': Sending state 25.18750 °C with 1 decimals of accuracy
[21:39:59][D][aht10:083]: AHT10 is busy, waiting...
[21:39:59][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 24.39995 °C with 2 decimals of accuracy
[21:39:59][D][sensor:126]: 'AHT21 Sensor Humidity': Sending state 54.48627 % with 2 decimals of accuracy
[21:40:19][D][dallas.sensor:143]: 'Temperatura pieza': Got Temperature=25.4°C
[21:40:19][D][sensor:126]: 'Temperatura pieza': Sending state 25.43750 °C with 1 decimals of accuracy
[21:40:54][D][aht10:083]: AHT10 is busy, waiting...
[21:40:54][D][sensor:126]: 'AHT21 Sensor Tempera [...]

2023-02-06 00:45 UTC, tomasrojasc commented
This is the esphome program:
```
esphome:
  name: test

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GDhGfiOvVrjBgf0oxyh8OA3K8BwQjRDYyBR7Gc3ylQY="

ota:
  password: "e0aa4adcd9c72fa672317a9dceba9511"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "HHtP30QR7frb"

  
# Example configuration entry
dallas:
  - pin: 14  # D5

i2c:
  id: i2c_component
  sda: 4
  scl: 5
  scan: true

external_components:
  - source: github://pr#4243
    components:
      - ens160

# ENS160 + AHT21 Module https://www.aliexpress.us/item/3256804712105923.html
# Define the I2C device for iFan04 to the Test Points on the back of the board.
# GPIO04 - TP11 D_RX (SDA)
# GPIO05 - TP10 D_TX (SCL)

# Individual sensors
sensor:
  - platform: dallas
    address: 0xcb99e4e90264ff28
    name: "Temperatura pieza"

  - platform: aht10
    id: aht21_sensor
    address: 0x38
    temperature:
      name: "AHT21 Sensor Temperature"
      id: aht21_sensor_temp
    humidity:
      name: "AHT21 Sensor Humidity"
      id: aht21_sensor_humi
    update_interval: 55s

  - platform: ens160
    id: ens160_sensor
    address: 0x53
    eco2:
      name: "ENS160 Sensor eCO2"
      id: ens160_sensor_eco2
    tvoc:
      name: "ENS160 Sensor Total Volatile Organic Compounds"
      id: ens160_sensor_tvoc
    aqi:
      name: "ENS160 Sensor Air Quality Index"
      id: ens160_sensor_aqi
    temperature: aht21_sensor_temp
    humidity: aht21_sensor_humi
    update_interval: 60s
```
And this is what the log returns me
```
[21:37:25][I][app:102]: ESPHome version 2022.12.8 compiled on Feb  5 2023, 21:21:03
[21:37:25][C][wifi:504]: WiFi:
[21:37:25][C][wifi:362]:   Local MAC: 
[21:37:25][C][wifi:363]:   SSID: [redacted]
[21:37:25][C][wifi:364]:   IP Address: 192.168.1.89
[21:37:25][C][wifi:365]:   BSSID: [redacted]
[21:37:25][C][wifi:367]:   Hostname: 'test'
[21:37:25][C][wifi:369]:   Signal strength: -71 dB ▂▄▆█
[21:37:25][C][wifi:373]:   Channel: 6
[21:37:25][C][wifi:374]:   Subnet: 255.255.255.0
[21:37:25][C][wifi:375]:   Gateway: 192.168.1.1
[21:37:25][C][wifi:376]:   DNS1: 200.28.4.130
[21:37:25][C][wifi:377]:   DNS2: 200.28.4.129
[21:37:25][C][logger:293]: Logger:
[21:37:25][C][logger:294]:   Level: DEBUG
[21:37:25][C][logger:295]:   Log Baud Rate: 115200
[21:37:25][C][logger:296]:   Hardware UART: UART0
[21:37:25][C][i2c.arduino:052]: I2C Bus:
[21:37:25][C][i2c.arduino:053]:   SDA Pin: GPIO4
[21:37:25][C][i2c.arduino:054]:   SCL Pin: GPIO5
[21:37:25][C][i2c.arduino:055]:   Frequency: 50000 Hz
[21:37:25][C][i2c.arduino:058]:   Recovery: bus successfully recovered
[21:37:25][I][i2c.arduino:068]: Results from i2c bus scan:
[21:37:25][I][i2c.arduino:074]: Found i2c device at address 0x38
[21:37:25][I][i2c.arduino:074]: Found i2c device at address 0x53
[21:37:25][C][dallas.sensor:075]: DallasComponent:
[21:37:25][C][dallas.sensor:076]:   Pin: GPIO14
[21:37:25][C][dallas.sensor:077]:   Update Interval: 60.0s
[21:37:25][D][dallas.sensor:082]:   Found sensors:
[21:37:25][D][dallas.sensor:084]:     0xcb99e4e90264ff28
[21:37:25][C][dallas.sensor:089]:   Device 'Temperatura pieza'
[21:37:25][C][dallas.sensor:089]:     Device Class: 'temperature'
[21:37:25][C][dallas.sensor:089]:     State Class: 'measurement'
[21:37:25][C][dallas.sensor:089]:     Unit of Measurement: '°C'
[21:37:25][C][dallas.sensor:089]:     Accuracy Decimals: 1
[21:37:25][C][dallas.sensor:097]:     Address: 0xcb99e4e90264ff28
[21:37:25][C][dallas.sensor:098]:     Resolution: 12
[21:37:25][C][aht10:136]: AHT10:
[21:37:25][C][aht10:137]:   Address: 0x38
[21:37:25][C][aht10:141]:   Temperature 'AHT21 Sensor Temperature'
[21:37:25][C][aht10:141]:     Device Class: 'temperature'
[21:37:25][C][aht10:141]:     State Class: 'measurement'
[21:37:25][C][aht10:141]:     Unit of Measurement: '°C'
[21:37:25][C][aht10:141]:     Accuracy Decimals: 2
[21:37:25][C][aht10:142]:   Humidity 'AHT21 Sensor Humidity'
[21:37:25][C][aht10:142]:     Device Class: 'humidity'
[21:37:25][C][aht10:142]:     State Class: 'measurement'
[21:37:25][C][aht10:142]:     Unit of Measurement: '%'
[21:37:25][C][aht10:142]:     Accuracy Decimals: 2
[21:37:25][C][ens160:283]: ENS160
[21:37:25][C][ens160:284]:   Address: 0x53
[21:37:25][C][ens160:285]:   Update Interval: 60.0s
[21:37:25][C][ens160:286]:   CO2 Sensor 'ENS160 Sensor eCO2'
[21:37:25][C][ens160:286]:     Device Class: 'carbon_dioxide'
[21:37:25][C][ens160:286]:     State Class: 'measurement'
[21:37:25][C][ens160:286]:     Unit of Measurement: 'ppm'
[21:37:25][C][ens160:286]:     Accuracy Decimals: 1
[21:37:25][C][ens160:286]:     Icon: 'mdi:molecule-co2'
[21:37:25][C][ens160:287]:   TVOC Sensor 'ENS160 Sensor Total Volatile Organic Compounds'
[21:37:25][C][ens160:287]:     Device Class: 'volatile_organic_compounds'
[21:37:25][C][ens160:287]:     State Class: 'measurement'
[21:37:25][C][ens160:287]:     Unit of Measurement: 'ppb'
[21:37:25][C][ens160:287]:     Accuracy Decimals: 1
[21:37:25][C][ens160:287]:     Icon: 'mdi:radiator'
[21:37:25][C][ens160:288]:   AQI Sensor 'ENS160 Sensor Air Quality Index'
[21:37:25][C][ens160:288]:     Device Class: 'aqi'
[21:37:25][C][ens160:288]:     State Class: 'measurement'
[21:37:25][C][ens160:288]:     Unit of Measurement: 'index'
[21:37:25][C][ens160:288]:     Accuracy Decimals: 0
[21:37:25][C][ens160:288]:     Icon: 'mdi:chemical-weapon'
[21:37:25][C][ens160:291]:   Temperature Compensation 'AHT21 Sensor Temperature'
[21:37:25][C][ens160:291]:     Device Class: 'temperature'
[21:37:25][C][ens160:291]:     State Class: 'measurement'
[21:37:25][C][ens160:291]:     Unit of Measurement: '°C'
[21:37:25][C][ens160:291]:     Accuracy Decimals: 2
[21:37:25][C][ens160:292]:   Humidity Compensation 'AHT21 Sensor Humidity'
[21:37:25][C][ens160:292]:     Device Class: 'humidity'
[21:37:25][C][ens160:292]:     State Class: 'measurement'
[21:37:25][C][ens160:292]:     Unit of Measurement: '%'
[21:37:25][C][ens160:292]:     Accuracy Decimals: 2
[21:37:25][W][ens160:296]: Communication failed! Is the sensor connected?
[21:37:25][C][mdns:103]: mDNS:
[21:37:25][C][mdns:104]:   Hostname: test
[21:37:25][C][ota:093]: Over-The-Air Updates:
[21:37:25][C][ota:094]:   Address: test.local:8266
[21:37:25][C][ota:097]:   Using Password.
[21:37:25][C][api:138]: API Server:
[21:37:25][C][api:139]:   Address: test.local:6053
[21:37:25][C][api:141]:   Using noise encryption: YES
[21:38:09][D][aht10:083]: AHT10 is busy, waiting...
[21:38:09][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 24.50829 °C with 2 decimals of accuracy
[21:38:09][D][sensor:126]: 'AHT21 Sensor Humidity': Sending state 52.25134 % with 2 decimals of accuracy
[21:38:19][D][dallas.sensor:143]: 'Temperatura pieza': Got Temperature=25.2°C
[21:38:19][D][sensor:126]: 'Temperatura pieza': Sending state 25.18750 °C with 1 decimals of accuracy
[21:39:04][D][aht10:083]: AHT10 is busy, waiting...
[21:39:04][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 24.21131 °C with 2 decimals of accuracy
[21:39:04][D][sensor:126]: 'AHT21 Sensor Humidity': Sending state 50.48037 % with 2 decimals of accuracy
[21:39:19][D][dallas.sensor:143]: 'Temperatura pieza': Got Temperature=25.2°C
[21:39:19][D][sensor:126]: 'Temperatura pieza': Sending state 25.18750 °C with 1 decimals of accuracy
[21:39:59][D][aht10:083]: AHT10 is busy, waiting...
[21:39:59][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 24.39995 °C with 2 decimals of accuracy
[21:39:59][D][sensor:126]: 'AHT21 Sensor Humidity': Sending state 54.48627 % with 2 decimals of accuracy
[21:40:19][D][dallas.sensor:143]: 'Temperatura pieza': Got Temperature=25.4°C
[21:40:19][D][sensor:126]: 'Temperatura pieza': Sending state 25.43750 °C with 1 decimals of accuracy
[21:40:54][D][aht10:083]: AHT10 is busy, waiting...
[21:40:54][D][sensor:126]: 'AHT21 Sensor Temperature': Sending st [...]

2023-02-09 00:44 UTC, jesserockz requested changes, later dismissed
The ideal and desired way to solve the blow comment is to split the component into hub and sensor/text_sensors.

2023-02-09 00:44 UTC, jesserockz commented on esphome/components/ens160/sensor.py
> +AUTO_LOAD = ["text_sensor"]
This auto loads a lot of code into ESPHome even if the user is not using `version` or `status`.

2023-02-09 06:20 UTC, NonaSuomy commented
> 

Maybe try to remove everything from the config except the ens160 stuff and see what happens 

Also try to use it direct with just Arduino IDE
https://github.com/adafruit/ENS160_driver

If it doesn't work then maybe your module got over-voltage and damaged somehow or product defect. I killed a BME280 just by forgetting it was powered up and testing the I2C pins for continuity after that it reported as 3 devices on the bus but would no longer work.

2023-02-11 17:07 UTC, tomasrojasc commented
I'll try what you suggested @NonaSuomy, probably during next week. Thanks!

2023-02-20 12:40 UTC, MiteZZ commented
> I'll try what you suggested @NonaSuomy, probably during next week. Thanks!

Let it know please, I'm facing the same issue at the moment. ESP D1 mini in combination with a ENS160+AHT21.. only data from the AHT is popping up.

2023-02-20 19:04 UTC, daeddebyan commented
> This is the esphome program:
> 
> ```
> esphome:
>   name: test
> 
> esp8266:
>   board: esp01_1m
> 
> # Enable logging
> logger:
> 
> # Enable Home Assistant API
> api:
>   encryption:
>     key: "GDhGfiOvVrjBgf0oxyh8OA3K8BwQjRDYyBR7Gc3ylQY="
> 
> ota:
>   password: "e0aa4adcd9c72fa672317a9dceba9511"
> 
> wifi:
>   ssid: !secret wifi_ssid
>   password: !secret wifi_password
> 
>   # Enable fallback hotspot (captive portal) in case wifi connection fails
>   ap:
>     ssid: "Test Fallback Hotspot"
>     password: "HHtP30QR7frb"
> 
>   
> # Example configuration entry
> dallas:
>   - pin: 14  # D5
> 
> i2c:
>   id: i2c_component
>   sda: 4
>   scl: 5
>   scan: true
> 
> external_components:
>   - source: github://pr#4243
>     components:
>       - ens160
> 
> # ENS160 + AHT21 Module https://www.aliexpress.us/item/3256804712105923.html
> # Define the I2C device for iFan04 to the Test Points on the back of the board.
> # GPIO04 - TP11 D_RX (SDA)
> # GPIO05 - TP10 D_TX (SCL)
> 
> # Individual sensors
> sensor:
>   - platform: dallas
>     address: 0xcb99e4e90264ff28
>     name: "Temperatura pieza"
> 
>   - platform: aht10
>     id: aht21_sensor
>     address: 0x38
>     temperature:
>       name: "AHT21 Sensor Temperature"
>       id: aht21_sensor_temp
>     humidity:
>       name: "AHT21 Sensor Humidity"
>       id: aht21_sensor_humi
>     update_interval: 55s
> 
>   - platform: ens160
>     id: ens160_sensor
>     address: 0x53
>     eco2:
>       name: "ENS160 Sensor eCO2"
>       id: ens160_sensor_eco2
>     tvoc:
>       name: "ENS160 Sensor Total Volatile Organic Compounds"
>       id: ens160_sensor_tvoc
>     aqi:
>       name: "ENS160 Sensor Air Quality Index"
>       id: ens160_sensor_aqi
>     temperature: aht21_sensor_temp
>     humidity: aht21_sensor_humi
>     update_interval: 60s
> ```
> 
> And this is what the log returns me
> 
> ```
> [21:37:25][I][app:102]: ESPHome version 2022.12.8 compiled on Feb  5 2023, 21:21:03
> [21:37:25][C][wifi:504]: WiFi:
> [21:37:25][C][wifi:362]:   Local MAC: 
> [21:37:25][C][wifi:363]:   SSID: [redacted]
> [21:37:25][C][wifi:364]:   IP Address: 192.168.1.89
> [21:37:25][C][wifi:365]:   BSSID: [redacted]
> [21:37:25][C][wifi:367]:   Hostname: 'test'
> [21:37:25][C][wifi:369]:   Signal strength: -71 dB ▂▄▆█
> [21:37:25][C][wifi:373]:   Channel: 6
> [21:37:25][C][wifi:374]:   Subnet: 255.255.255.0
> [21:37:25][C][wifi:375]:   Gateway: 192.168.1.1
> [21:37:25][C][wifi:376]:   DNS1: 200.28.4.130
> [21:37:25][C][wifi:377]:   DNS2: 200.28.4.129
> [21:37:25][C][logger:293]: Logger:
> [21:37:25][C][logger:294]:   Level: DEBUG
> [21:37:25][C][logger:295]:   Log Baud Rate: 115200
> [21:37:25][C][logger:296]:   Hardware UART: UART0
> [21:37:25][C][i2c.arduino:052]: I2C Bus:
> [21:37:25][C][i2c.arduino:053]:   SDA Pin: GPIO4
> [21:37:25][C][i2c.arduino:054]:   SCL Pin: GPIO5
> [21:37:25][C][i2c.arduino:055]:   Frequency: 50000 Hz
> [21:37:25][C][i2c.arduino:058]:   Recovery: bus successfully recovered
> [21:37:25][I][i2c.arduino:068]: Results from i2c bus scan:
> [21:37:25][I][i2c.arduino:074]: Found i2c device at address 0x38
> [21:37:25][I][i2c.arduino:074]: Found i2c device at address 0x53
> [21:37:25][C][dallas.sensor:075]: DallasComponent:
> [21:37:25][C][dallas.sensor:076]:   Pin: GPIO14
> [21:37:25][C][dallas.sensor:077]:   Update Interval: 60.0s
> [21:37:25][D][dallas.sensor:082]:   Found sensors:
> [21:37:25][D][dallas.sensor:084]:     0xcb99e4e90264ff28
> [21:37:25][C][dallas.sensor:089]:   Device 'Temperatura pieza'
> [21:37:25][C][dallas.sensor:089]:     Device Class: 'temperature'
> [21:37:25][C][dallas.sensor:089]:     State Class: 'measurement'
> [21:37:25][C][dallas.sensor:089]:     Unit of Measurement: '°C'
> [21:37:25][C][dallas.sensor:089]:     Accuracy Decimals: 1
> [21:37:25][C][dallas.sensor:097]:     Address: 0xcb99e4e90264ff28
> [21:37:25][C][dallas.sensor:098]:     Resolution: 12
> [21:37:25][C][aht10:136]: AHT10:
> [21:37:25][C][aht10:137]:   Address: 0x38
> [21:37:25][C][aht10:141]:   Temperature 'AHT21 Sensor Temperature'
> [21:37:25][C][aht10:141]:     Device Class: 'temperature'
> [21:37:25][C][aht10:141]:     State Class: 'measurement'
> [21:37:25][C][aht10:141]:     Unit of Measurement: '°C'
> [21:37:25][C][aht10:141]:     Accuracy Decimals: 2
> [21:37:25][C][aht10:142]:   Humidity 'AHT21 Sensor Humidity'
> [21:37:25][C][aht10:142]:     Device Class: 'humidity'
> [21:37:25][C][aht10:142]:     State Class: 'measurement'
> [21:37:25][C][aht10:142]:     Unit of Measurement: '%'
> [21:37:25][C][aht10:142]:     Accuracy Decimals: 2
> [21:37:25][C][ens160:283]: ENS160
> [21:37:25][C][ens160:284]:   Address: 0x53
> [21:37:25][C][ens160:285]:   Update Interval: 60.0s
> [21:37:25][C][ens160:286]:   CO2 Sensor 'ENS160 Sensor eCO2'
> [21:37:25][C][ens160:286]:     Device Class: 'carbon_dioxide'
> [21:37:25][C][ens160:286]:     State Class: 'measurement'
> [21:37:25][C][ens160:286]:     Unit of Measurement: 'ppm'
> [21:37:25][C][ens160:286]:     Accuracy Decimals: 1
> [21:37:25][C][ens160:286]:     Icon: 'mdi:molecule-co2'
> [21:37:25][C][ens160:287]:   TVOC Sensor 'ENS160 Sensor Total Volatile Organic Compounds'
> [21:37:25][C][ens160:287]:     Device Class: 'volatile_organic_compounds'
> [21:37:25][C][ens160:287]:     State Class: 'measurement'
> [21:37:25][C][ens160:287]:     Unit of Measurement: 'ppb'
> [21:37:25][C][ens160:287]:     Accuracy Decimals: 1
> [21:37:25][C][ens160:287]:     Icon: 'mdi:radiator'
> [21:37:25][C][ens160:288]:   AQI Sensor 'ENS160 Sensor Air Quality Index'
> [21:37:25][C][ens160:288]:     Device Class: 'aqi'
> [21:37:25][C][ens160:288]:     State Class: 'measurement'
> [21:37:25][C][ens160:288]:     Unit of Measurement: 'index'
> [21:37:25][C][ens160:288]:     Accuracy Decimals: 0
> [21:37:25][C][ens160:288]:     Icon: 'mdi:chemical-weapon'
> [21:37:25][C][ens160:291]:   Temperature Compensation 'AHT21 Sensor Temperature'
> [21:37:25][C][ens160:291]:     Device Class: 'temperature'
> [21:37:25][C][ens160:291]:     State Class: 'measurement'
> [21:37:25][C][ens160:291]:     Unit of Measurement: '°C'
> [21:37:25][C][ens160:291]:     Accuracy Decimals: 2
> [21:37:25][C][ens160:292]:   Humidity Compensation 'AHT21 Sensor Humidity'
> [21:37:25][C][ens160:292]:     Device Class: 'humidity'
> [21:37:25][C][ens160:292]:     State Class: 'measurement'
> [21:37:25][C][ens160:292]:     Unit of Measurement: '%'
> [21:37:25][C][ens160:292]:     Accuracy Decimals: 2
> [21:37:25][W][ens160:296]: Communication failed! Is the sensor connected?
> [21:37:25][C][mdns:103]: mDNS:
> [21:37:25][C][mdns:104]:   Hostname: test
> [21:37:25][C][ota:093]: Over-The-Air Updates:
> [21:37:25][C][ota:094]:   Address: test.local:8266
> [21:37:25][C][ota:097]:   Using Password.
> [21:37:25][C][api:138]: API Server:
> [21:37:25][C][api:139]:   Address: test.local:6053
> [21:37:25][C][api:141]:   Using noise encryption: YES
> [21:38:09][D][aht10:083]: AHT10 is busy, waiting...
> [21:38:09][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 24.50829 °C with 2 decimals of accuracy
> [21:38:09][D][sensor:126]: 'AHT21 Sensor Humidity': Sending state 52.25134 % with 2 decimals of accuracy
> [21:38:19][D][dallas.sensor:143]: 'Temperatura pieza': Got Temperature=25.2°C
> [21:38:19][D][sensor:126]: 'Temperatura pieza': Sending state 25.18750 °C with 1 decimals of accuracy
> [21:39:04][D][aht10:083]: AHT10 is busy, waiting...
> [21:39:04][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 24.21131 °C with 2 decimals of accuracy
> [21:39:04][D][sensor:126]: 'AHT21 Sensor Humidity': Sending state 50.48037 % with 2 decimals of accuracy
> [21:39:19][D][dallas.sensor:143]: 'Temperatura pieza': Got Temperature=25.2°C
> [21:39:19][D][sensor:126]: 'Temperatura pieza': Sending state 25.18750 °C with 1 decimals of accuracy
> [21:39:59][D][aht10:083]: AHT10 is busy, waiting...
> [21:39:59][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 24.39995 °C with 2 decimals of accuracy
> [21:39:59][D][sensor: [...]

2023-03-11 12:30 UTC, Corrado-possieri commented
Hello, as @daeddebyan and @tomasrojasc, I cannot get measurements from the ENS160.
In the log, I have

`[12:29:09][D][aht10:083]: AHT10 is busy, waiting...
[12:29:09][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 20.05291 °C with 2 decimals of accuracy
[12:29:09][D][sensor:126]: 'AHT21 Sensor Humidity': Sending state 66.83903 % with 2 decimals of accuracy`

but no ENS160 measurements.
I also tried connecting the 3.3V of the sensor to 3.3V of the D1 mini, but nothing.
Do you have any idea on how to make it work?

Thanks

2023-03-17 16:13 UTC, goyourfly commented
aht21 worked, but ens160 no connected
Device: NodeMcu v2

3v3 -> 3v3
GND -> GND
sda -> D2
scl -> D1

```
[00:09:33][W][ens160:296]: Communication failed! Is the sensor connected?
[00:09:33][C][captive_portal:088]: Captive Portal:
[00:09:33][C][mdns:108]: mDNS:
[00:09:33][C][mdns:109]:   Hostname: home-air-quality
[00:09:33][C][ota:093]: Over-The-Air Updates:
[00:09:33][C][ota:094]:   Address: 10.236.1.248:8266
[00:09:33][C][ota:097]:   Using Password.
[00:09:34][C][api:138]: API Server:
[00:09:34][C][api:139]:   Address: 10.236.1.248:6053
[00:09:34][C][api:141]:   Using noise encryption: YES
[00:09:34][D][aht10:083]: AHT10 is busy, waiting...
[00:09:34][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 26.13487 °C with 2 decimals of accuracy
[00:09:34][D][sensor:126]: 'AHT21 Sensor Humidity': Sending state 30.54981 % with 2 decimals of accuracy
```

2023-03-17 19:19 UTC, NonaSuomy commented
> aht21 worked, but ens160 no connected Device: NodeMcu v2
> 
> 3v3 <---> 3v3 GND <---> GND sda <---> D2 scl <---> D1
> 
> ```
> [00:09:33][W][ens160:296]: Communication failed! Is the sensor connected?
> [00:09:33][C][captive_portal:088]: Captive Portal:
> [00:09:33][C][mdns:108]: mDNS:
> [00:09:33][C][mdns:109]:   Hostname: home-air-quality
> [00:09:33][C][ota:093]: Over-The-Air Updates:
> [00:09:33][C][ota:094]:   Address: 10.236.1.248:8266
> [00:09:33][C][ota:097]:   Using Password.
> [00:09:34][C][api:138]: API Server:
> [00:09:34][C][api:139]:   Address: 10.236.1.248:6053
> [00:09:34][C][api:141]:   Using noise encryption: YES
> [00:09:34][D][aht10:083]: AHT10 is busy, waiting...
> [00:09:34][D][sensor:126]: 'AHT21 Sensor Temperature': Sending state 26.13487 °C with 2 decimals of accuracy
> [00:09:34][D][sensor:126]: 'AHT21 Sensor Humidity': Sending state 30.54981 % with 2 decimals of accuracy
> ```

Can you try with the suggest arduino and library above?

2023-04-04 01:38 UTC, r3klawz commented
I've been having some issues getting this to work with 2 of the ENS160+AHT210 boards I have.  I recently discovered that it seems to only work when I heat the board past ambient room temperature (its relatively cold in my basement).  I'm seeing the following with very verbose logging.

[ens160.txt](https://github.com/esphome/esphome/files/11143810/ens160.txt)

2023-04-04 15:55 UTC, NonaSuomy commented
> I've been having some issues getting this to work with 2 of the ENS160+AHT210 boards I have. I recently discovered that it seems to only work when I heat the board past ambient room temperature (its relatively cold in my basement). I'm seeing the following with very verbose logging.
> 
> [ens160.txt](https://github.com/esphome/esphome/files/11143810/ens160.txt)

Did you contact the manufacture of the board for the hardware related issues you are having?

2023-04-14 08:41 UTC, Corrado-possieri commented
I tried using the arduino library and everything seems fine.

I got the following output

```
Sensor operating status: 0
Air quality index: 0
Concentration of total volatile organic compounds: 0 ppb 
Carbon dioxide equivalent concentration: 0 ppm
``` 

however going back to esphome the results are still unavailable

2023-04-15 00:17 UTC, NonaSuomy commented
> status:

Did you get any results while using the arduino library as it should show some value not 0?

2023-04-15 07:26 UTC, vincentscode commented
@Corrado-possieri The values you show are not "fine". My integration would return unavailable here because (by the datasheet) all values being zero is not a valid state and shows that something is not working.

2023-04-17 01:21 UTC, mrtoy-me commented
Hi Vincentscode, I just stumbled across you pr and component - I have been developing a component for ens160 as well - I took a different path and used as starting point a combination of sparkfun library, sciosense library and my own reading of the data sheet. Your code gave me some ideas thanks. My component is not really finished yet but working with bme280 for temp and humidity compensation.
I haven’t included the text sensor or a few other things that you have in my component… but I am waiting until after warmup until getting valid readings. Happy to help if you need it to resolve outstanding and can share my code in a week or two when I tidy up if you want. Also have not used GitHub before so but of a learning curve

2023-04-22 17:15 UTC, rosbeef commented
> > status:
> 
> Did you get any results while using the arduino library as it should show some value not 0?

@vincentscode @NonaSuomy i have a module with ath21 ans ens160 bang.  As you temperature andn humidity works but not air quality. 

Then, I press hard the ens160 chip and I had data's. It seems to be hardware default soldering.

I will try to find out howto de/resolder this kind of things.

2023-04-23 10:13 UTC, vincentscode commented
Hi @mrtoy-me, that'd be great actually! I think my current implementation might have some issues with not waiting for the sensor warmup. I'd be happy to read your implementation / hear your thoughts on what might be improved here!

2023-04-26 16:03 UTC, Corrado-possieri commented
> @Corrado-possieri The values you show are not "fine". My integration would return unavailable here because (by the datasheet) all values being zero is not a valid state and shows that something is not working.

Thank you for the hint. I tried disconnecting the sensor module while using the Arduino library and it actually returns unavailable, so probably it communicates but it does not return usable measurements. I don’t know if the component is broken and if it can be fixed somehow

2023-04-26 17:19 UTC, r3klawz commented
> > @Corrado-possieri The values you show are not "fine". My integration would return unavailable here because (by the datasheet) all values being zero is not a valid state and shows that something is not working.
> 
> Thank you for the hint. I tried disconnecting the sensor module while using the Arduino library and it actually returns unavailable, so probably it communicates but it does not return usable measurements. I don’t know if the component is broken and if it can be fixed somehow

I have a feeling a lot of us that are experiencing issues have boards from the same supplier with shoddy soldering of the SMDs.  Like @rosbeef pointed out, I too get data when I press down on the ENS160.  Previously I realized I only got readings when the board was heated, but I'm assuming that the expansion during the heating was enough for the bad contacts to close.  Pressing on it worked until it didn't and then the ENS160 failed altogether.

I got my last board out to test and I do get readings from this one.... but the AHT10 isn't replying on I2C.  These boards might be junk unfortunately.  I'm reaching out to the seller to ask for a refund although I'm afraid they'll tell me I'm out of luck.

2023-05-01 04:15 UTC, jesserockz commented
@vincentscode What is the state of thie PR? I see lots of comment activity, but is it ready or still having some issues?

I am going to mark as draft for now, if/when it is ready, please mark as ready.

Jesse

2023-05-01 11:17 UTC, mrtoy-me commented
> Hi @mrtoy-me, that'd be great actually! I think my current implementation might have some issues with not waiting for the sensor warmup. I'd be happy to read your implementation / hear your thoughts on what might be improved here!

Hi @vincentcode, I have sent an email to you

2023-05-01 11:22 UTC, vincentscode commented
Hi @jesserockz, currently there are quite a few issues but many of them seem to be originating from faulty PCBs from a singular source. Mitigation for that might be to have a longer wait for heatup which I will be discussing with mrtoy-me. Other than that I have not gotten around to separating out the text_component but I will do that soon. 
I will notify you once all of this is done and mark the PR as ready-for-review then.

2023-05-04 11:51 UTC, mrtoy-me requested changes
Hi Vincent,
I have compared what I am doing in my component to yours and added some comments on differences that might improve and be useful.  First time I have used Githib for commenting on someone's code.  I hope I have done it correctly and that it helps you..  Regards mrtoy-me

2023-05-04 11:51 UTC, mrtoy-me commented on esphome/components/ens160/ens160.cpp
> +  CHECKED_IO(this->write_byte(ENS160_REG_OPMODE, ENS160_OPMODE_STD));
I would double check that you achieve standard mode and read back the opmode and check that it standard mode - see the end of my setup. I have found you do not need any delay when setting op mode and it is not mentioned in doco or examples.
Something like:

 uint8_t op_mode;
 if (!this->read_byte(ENS160_REG_OPMODE,&op_mode)) {
    this->error_code_ = READ_OPMODE_FAILED;
    this->mark_failed();
    return; 
  }	
  if (op_mode != ENS160_OPMODE_STD) {
    this->error_code_ = STANDARD_OPMODE_FAILED;
    this->mark_failed();
    return; 
  }

2023-05-04 11:51 UTC, mrtoy-me commented on esphome/components/ens160/ens160.cpp
> +  // read & publish status
If you want to publish the status, I would do that by setting up another sensor in sensor.py and publishing as a value then you could also make it optional
Something like:

 cv.Optional(CONF_STATUS): sensor.sensor_schema(
                unit_of_measurement=UNIT_EMPTY,
                accuracy_decimals=0,
                state_class=STATE_CLASS_MEASUREMENT,
            ),

2023-05-04 11:51 UTC, mrtoy-me commented on esphome/components/ens160/ens160.cpp
> +  // full reset on invalid status
Not sure about doing a full reset ... this is not in ScioSense library that I can find. Myself, I would explicitly check the STATAS and STATER bits and then raise an error if either is zero. Either of these could be zero which indicates an error and other bits could be non-zero which means you miss the error.
At this point you could just check STATER because lines 176-181 checks STATAS

2023-05-04 11:51 UTC, mrtoy-me commented on esphome/components/ens160/ens160.cpp
> +  // test: always set opmode to std
No sure why you are setting STD Opmode here. Should be in STD, I would check by reading opmode as per my first comment/suggestion.

2023-05-04 11:51 UTC, mrtoy-me commented on esphome/components/ens160/ens160.cpp
> +
This is where I would check the validity flags of the status register to determine if the the sensor is on first startup or warming up... see my ENS160 component lines 190-218. If it is I give a message the first time through and return from update. I set globals so I don't keep displaying initial startup / warming up log message and I also set the compensation values here, so the first measurement after warmup has compensation values.

2023-05-15 11:20 UTC, ayufan commented
For some reason my ENS160 when running this PR get stuck with elevated set of measurements. After rebooting ESPHome it shows more expected values again.

<img width="1009" alt="image" src="https://github.com/esphome/esphome/assets/2419009/dc8e42ee-58ee-49ce-ab68-020c19dc44e6">

2023-05-18 21:38 UTC, mrtoy-me commented
> For some reason my ENS160 when running this PR get stuck with elevated set of measurements. After rebooting ESPHome it shows more expected values again.
> 
> 
> 
> <img width="1009" alt="image" src="https://github.com/esphome/esphome/assets/2419009/dc8e42ee-58ee-49ce-ab68-020c19dc44e6">
> 
> 

try again pr again - quick a few changes have been made. I recommend using temperature and humidity compensation

2023-05-20 15:39 UTC, bennop commented
Just to let you know: I got my sensor working with this a couple of weeks ago but run into problems now when trying to recompile, seeing these messages:

```
  [temperature] is an invalid option for [sensor.ens160]. Please check the indentation.
  temperature: esp25_aht_temp
  
  [humidity] is an invalid option for [sensor.ens160]. Please check the indentation.
  humidity: esp25_aht_hum
```

(the ENS160-related code has not changed since the last successful compilation)

Any hints for fixing this would be appreciated!

2023-05-20 15:41 UTC, vincentscode commented
@bennop The configuration for compensation has changed slightly, check out the new interface here:
https://deploy-preview-2931--esphome.netlify.app/components/sensor/ens160.html

2023-05-20 23:04 UTC, bennop commented
Thank for the quick feedback - I saw something hinting at this in the source but was not quite sure how to actually use it …

Have a nice weekend!

	Benno

> On 20. May 2023, at 17:41, Vincent Schmandt ***@***.***> wrote:
> 
> 
> @bennop <https://github.com/bennop> The configuration for compensation has changed slightly, check out the new interface here:
> https://deploy-preview-2931--esphome.netlify.app/components/sensor/ens160.html <https://deploy-preview-2931--esphome.netlify.app/components/sensor/ens160.html>
> —
> Reply to this email directly, view it on GitHub <https://github.com/esphome/esphome/pull/4243#issuecomment-1555938367>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABNFDNKNLZ4JC75QXQYI2SLXHDQ3XANCNFSM6AAAAAATMZH5V4>.
> You are receiving this because you were mentioned.
>

2023-05-20 23:11 UTC, bennop commented
One minor correction: Looking through the new page I noticed that the closing quotes are missing in the name entry of the text sensor example.

Cheers,

	Benno

> On 21. May 2023, at 01:04, Puetz, Benno ***@***.***> wrote:
> 
> Thank for the quick feedback - I saw something hinting at this in the source but was not quite sure how to actually use it …
> 
> Have a nice weekend!
> 
> 	Benno
> 
>> On 20. May 2023, at 17:41, Vincent Schmandt ***@***.*** ***@***.***>> wrote:
>> 
>> 
>> @bennop <https://github.com/bennop> The configuration for compensation has changed slightly, check out the new interface here:
>> https://deploy-preview-2931--esphome.netlify.app/components/sensor/ens160.html <https://deploy-preview-2931--esphome.netlify.app/components/sensor/ens160.html>
>> —
>> Reply to this email directly, view it on GitHub <https://github.com/esphome/esphome/pull/4243#issuecomment-1555938367>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABNFDNKNLZ4JC75QXQYI2SLXHDQ3XANCNFSM6AAAAAATMZH5V4>.
>> You are receiving this because you were mentioned.
>> 
>

2023-05-30 17:23 UTC, cowboy3d commented
Hi,
just followed this thread to integrate a ENS160+ATH21 sensor - works so far, but the values I get from ATH21 look a bit strange (quite off) and the ENS160 is reporting only 0 values....

[19:20:59][VV][i2c.arduino:141]: 0x38 TX 00AC3300
[19:21:00][VV][aht10:075]: Attempt 0 at   1303
[19:21:00][VV][i2c.arduino:117]: 0x38 RX 980000060980
[19:21:00][D][aht10:083]: AHT10 is busy, waiting...
[19:21:00][VV][aht10:075]: Attempt 1 at   1338
[19:21:00][VV][i2c.arduino:117]: 0x38 RX 1C7505D609CC
[19:21:00][VV][aht10:099]: Answer at   1373
[19:21:00][V][sensor:043]: 'AHT21 Sensor Temperature': Received new state 25.478363
[19:21:00][D][sensor:093]: 'AHT21 Sensor Temperature': Sending state 25.47836 °C with 2 decimals of accuracy
[19:21:00][V][sensor:043]: 'AHT21 Sensor Humidity': Received new state 45.711994
[19:21:00][D][sensor:093]: 'AHT21 Sensor Humidity': Sending state 45.71199 % with 2 decimals of accuracy
[19:21:00][VV][i2c.arduino:141]: 0x53 TX 20
[19:21:00][VV][i2c.arduino:117]: 0x53 RX 03
[19:21:00][V][ens160:156]: Status: ENS160 STATAS bit    0x0
[19:21:00][V][ens160:158]: Status: ENS160 STATER bit    0x0
[19:21:00][V][ens160:160]: Status: ENS160 VALIDITY FLAG 0x00
[19:21:00][V][ens160:161]: Status: ENS160 NEWDAT bit    0x1
[19:21:00][V][ens160:163]: Status: ENS160 NEWGPR bit    0x1
[19:21:00][VV][i2c.arduino:141]: 0x53 TX 24
[19:21:00][VV][i2c.arduino:117]: 0x53 RX 0000
[19:21:00][V][sensor:043]: 'ENS160 Sensor eCO2': Received new state 0.000000
[19:21:00][D][sensor:093]: 'ENS160 Sensor eCO2': Sending state 0.00000 ppm with 0 decimals of accuracy
[19:21:00][VV][i2c.arduino:141]: 0x53 TX 22
[19:21:00][VV][i2c.arduino:117]: 0x53 RX 0000
[19:21:00][V][sensor:043]: 'ENS160 Sensor Total Volatile Organic Compounds': Received new state 0.000000
[19:21:00][D][sensor:093]: 'ENS160 Sensor Total Volatile Organic Compounds': Sending state 0.00000 ppb with 0 decimals of accuracy
[19:21:00][VV][i2c.arduino:141]: 0x53 TX 21
[19:21:00][VV][i2c.arduino:117]: 0x53 RX 00
[19:21:00][V][sensor:043]: 'ENS160 Sensor Air Quality Index': Received new state 0.000000
[19:21:00][D][sensor:093]: 'ENS160 Sensor Air Quality Index': Sending state 0.00000 index with 0 decimals of accuracy
[19:21:00][V][ens160:247]: External temperature compensation: 25.5°C
[19:21:00][V][ens160:258]: External humidity compensation:    45.7%
[19:21:00][VV][i2c.arduino:141]: 0x53 TX 13A84A6C5B
[19:21:00][V][component:204]: Component ens160.sensor took a long time for an operation (0.13 s).
.....
[19:21:55][VV][i2c.arduino:141]: 0x53 TX 20
[19:21:55][VV][i2c.arduino:117]: 0x53 RX 01
[19:21:55][V][ens160:156]: Status: ENS160 STATAS bit    0x0
[19:21:55][V][ens160:158]: Status: ENS160 STATER bit    0x0
[19:21:55][V][ens160:160]: Status: ENS160 VALIDITY FLAG 0x00
[19:21:55][V][ens160:161]: Status: ENS160 NEWDAT bit    0x0
[19:21:55][V][ens160:163]: Status: ENS160 NEWGPR bit    0x1
[19:21:55][D][ens160:172]: ENS160 readings unavailable - Normal Operation but readings not ready

Any ideas? Or did I just have bad luck with my sensor?

Kind regards

Stephan

2023-05-30 18:52 UTC, vincentscode commented
Hi @cowboy3d. The AHT21 is just a bad Temperature / Humidity Sensor. I've never had any luck getting reasonable values from it and similar sensors, but it's also not a new implementation from this PR.
As for the ENS160: we've had a number of faulty boards with the AHT21 and ENS160.
Could you try using this revision of the component?
```

2023-05-31 00:05 UTC, mrtoy-me commented on esphome/components/ens160/sensor.py
> +AUTO_LOAD = ["text_sensor"]
changes made by removing text sensor - all updated including docs

2023-05-31 00:12 UTC, mrtoy-me commented
> Hi, just followed this thread to integrate a ENS160+ATH21 sensor - works so far, but the values I get from ATH21 look a bit strange (quite off) and the ENS160 is reporting only 0 values....
> 
> [19:20:59][VV][i2c.arduino:141]: 0x38 TX 00AC3300 [19:21:00][VV][aht10:075]: Attempt 0 at 1303 [19:21:00][VV][i2c.arduino:117]: 0x38 RX 980000060980 [19:21:00][D][aht10:083]: AHT10 is busy, waiting... [19:21:00][VV][aht10:075]: Attempt 1 at 1338 [19:21:00][VV][i2c.arduino:117]: 0x38 RX 1C7505D609CC [19:21:00][VV][aht10:099]: Answer at 1373 [19:21:00][V][sensor:043]: 'AHT21 Sensor Temperature': Received new state 25.478363 [19:21:00][D][sensor:093]: 'AHT21 Sensor Temperature': Sending state 25.47836 °C with 2 decimals of accuracy [19:21:00][V][sensor:043]: 'AHT21 Sensor Humidity': Received new state 45.711994 [19:21:00][D][sensor:093]: 'AHT21 Sensor Humidity': Sending state 45.71199 % with 2 decimals of accuracy [19:21:00][VV][i2c.arduino:141]: 0x53 TX 20 [19:21:00][VV][i2c.arduino:117]: 0x53 RX 03 [19:21:00][V][ens160:156]: Status: ENS160 STATAS bit 0x0 [19:21:00][V][ens160:158]: Status: ENS160 STATER bit 0x0 [19:21:00][V][ens160:160]: Status: ENS160 VALIDITY FLAG 0x00 [19:21:00][V][ens160:161]: Status: ENS160 NEWDAT bit 0x1 [19:21:00][V][ens160:163]: Status: ENS160 NEWGPR bit 0x1 [19:21:00][VV][i2c.arduino:141]: 0x53 TX 24 [19:21:00][VV][i2c.arduino:117]: 0x53 RX 0000 [19:21:00][V][sensor:043]: 'ENS160 Sensor eCO2': Received new state 0.000000 [19:21:00][D][sensor:093]: 'ENS160 Sensor eCO2': Sending state 0.00000 ppm with 0 decimals of accuracy [19:21:00][VV][i2c.arduino:141]: 0x53 TX 22 [19:21:00][VV][i2c.arduino:117]: 0x53 RX 0000 [19:21:00][V][sensor:043]: 'ENS160 Sensor Total Volatile Organic Compounds': Received new state 0.000000 [19:21:00][D][sensor:093]: 'ENS160 Sensor Total Volatile Organic Compounds': Sending state 0.00000 ppb with 0 decimals of accuracy [19:21:00][VV][i2c.arduino:141]: 0x53 TX 21 [19:21:00][VV][i2c.arduino:117]: 0x53 RX 00 [19:21:00][V][sensor:043]: 'ENS160 Sensor Air Quality Index': Received new state 0.000000 [19:21:00][D][sensor:093]: 'ENS160 Sensor Air Quality Index': Sending state 0.00000 index with 0 decimals of accuracy [19:21:00][V][ens160:247]: External temperature compensation: 25.5°C [19:21:00][V][ens160:258]: External humidity compensation: 45.7% [19:21:00][VV][i2c.arduino:141]: 0x53 TX 13A84A6C5B [19:21:00][V][component:204]: Component ens160.sensor took a long time for an operation (0.13 s). ..... [19:21:55][VV][i2c.arduino:141]: 0x53 TX 20 [19:21:55][VV][i2c.arduino:117]: 0x53 RX 01 [19:21:55][V][ens160:156]: Status: ENS160 STATAS bit 0x0 [19:21:55][V][ens160:158]: Status: ENS160 STATER bit 0x0 [19:21:55][V][ens160:160]: Status: ENS160 VALIDITY FLAG 0x00 [19:21:55][V][ens160:161]: Status: ENS160 NEWDAT bit 0x0 [19:21:55][V][ens160:163]: Status: ENS160 NEWGPR bit 0x1 [19:21:55][D][ens160:172]: ENS160 readings unavailable - Normal Operation but readings not ready
> 
> Any ideas? Or did I just have bad luck with my sensor?
> 
> Kind regards
> 
> Stephan

Just interested what logs say when you power cycle or re-flash... the normal response in logs should is sensor is warming up for 3min with updated PR 
You should only get the "ENS160 readings unavailable - Normal Operation but readings not ready" if you have a low update 
interval down near 1 sec which is how long it takes the sensor to do a measurement but it looks like you have an update interval of around 60s. 

Regards
Brett

2023-05-31 06:11 UTC, cowboy3d commented
> Hi @cowboy3d. The AHT21 is just a bad Temperature / Humidity Sensor. I've never had any luck getting reasonable values from it and similar sensors, but it's also not a new implementation from this PR. As for the ENS160: we've had a number of faulty boards with the AHT21 and ENS160. Could you try using this revision of the component?
> 
> ```
> external_components:
>   - source:
>       type: git
>       url: https://github.com/vincentscode/esphome/
>       ref: test-ens160-stable # ens160
>     components:
>       - ens160
> ```

Did try it out - using that version I do not get any values from ENS160 at all. Had it running all night - it stays at "NA".
Switching back to the previous version - but thanks a lot for your support.

2023-06-22 09:27 UTC, niyazFattahov commented
Hello, I bought ens160 here: aliexpress.ru/item/32803371228.html and all zeros from it. I use it in conjunction with this temp & humidity sensors AHT20+BMP280 
This is part of my config:

```
i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a

external_components:
  - source: github://pr#4243
    components:
      - ens160

sensor:
  - platform: bmp280
    address: 0x77
    update_interval: 55s
    temperature:
      name: "BMP temp"
      oversampling: 2x
    pressure:
      name: "BMP Pressure"

  - platform: aht10
    address: 0x38
    update_interval: 55s
    temperature:
      name: "AHT20 temp"
      id: aht20_temp
      accuracy_decimals: 1
      filters:
      - filter_out: 0.0
      - median:
          window_size: 3
          send_every: 3
          send_first_at: 1
    humidity:
      name: "AHT20 humidity"
      id: aht20_humidity
      accuracy_decimals: 1
      filters:
      - filter_out: 0.0
      - median:
          window_size: 3
          send_every: 3
          send_first_at: 1
  - platform: ens160
    id: ens160_sensor
    address: 0x52
    eco2:
      name: "ENS160 Sensor eCO2"
      id: ens160_sensor_eco2
    tvoc:
      name: "ENS160 Sensor Total Volatile Organic Compounds"
      id: ens160_sensor_tvoc
    aqi:
      name: "ENS160 Sensor Air Quality Index"
      id: ens160_sensor_aqi
    # Inject the temp/humi data from the AHT21 into the ENS160 attached module for compensation.
    # Makes the gas results more accurate.
    compensation:
      temperature: aht20_temp
      humidity: aht20_humidity
    update_interval: 60s
```
is this meaning what my ens160 not working?
where can I buy working ens160 from aliexpress?

2023-06-22 21:58 UTC, mrtoy-me commented
Hi Niyaz
See previous posts to cowboy3d about correct referencing component and problems with some boards. 
Using logger level debug, you get messages about the status of registers. When you power cycle or re-flash... the normal response in logs for a working sensor is... warming up for 3min

2023-06-25 08:03 UTC, niyazFattahov commented
> Hi Niyaz See previous posts to cowboy3d about correct referencing component and problems with some boards. Using logger level debug, you get messages about the status of registers. When you power cycle or re-flash... the normal response in logs for a working sensor is... warming up for 3min

with this version:
```
external_components:
  - source:
      type: git
      url: https://github.com/vincentscode/esphome/
      ref: test-ens160-stable # ens160
    components:
      - ens160
```
I don't see 'warming up...'

```[10:49:02][C][logger:301]: Logger:
[10:49:02][C][logger:302]:   Level: DEBUG
[10:49:02][C][logger:303]:   Log Baud Rate: 115200
[10:49:02][C][logger:305]:   Hardware UART: UART0
[10:49:02][C][i2c.arduino:053]: I2C Bus:
[10:49:02][C][i2c.arduino:054]:   SDA Pin: GPIO4
[10:49:02][C][i2c.arduino:055]:   SCL Pin: GPIO5
[10:49:02][C][i2c.arduino:056]:   Frequency: 50000 Hz
[10:49:02][C][i2c.arduino:059]:   Recovery: bus successfully recovered
[10:49:02][I][i2c.arduino:069]: Results from i2c bus scan:
[10:49:02][I][i2c.arduino:075]: Found i2c device at address 0x38
[10:49:02][I][i2c.arduino:075]: Found i2c device at address 0x52
[10:49:02][I][i2c.arduino:075]: Found i2c device at address 0x77
[10:49:02][C][bmp280.sensor:124]: BMP280:
[10:49:02][C][bmp280.sensor:125]:   Address: 0x77
[10:49:02][C][bmp280.sensor:137]:   IIR Filter: OFF
[10:49:02][C][bmp280.sensor:138]:   Update Interval: 55.0s
[10:49:02][C][bmp280.sensor:140]:   Temperature 'BMP temp'
[10:49:02][C][bmp280.sensor:140]:     Device Class: 'temperature'
[10:49:02][C][bmp280.sensor:140]:     State Class: 'measurement'
[10:49:02][C][bmp280.sensor:140]:     Unit of Measurement: '°C'
[10:49:02][C][bmp280.sensor:140]:     Accuracy Decimals: 1
[10:49:02][C][bmp280.sensor:141]:     Oversampling: 2x
[10:49:02][C][bmp280.sensor:142]:   Pressure 'BMP Pressure'
[10:49:02][C][bmp280.sensor:142]:     Device Class: 'pressure'
[10:49:02][C][bmp280.sensor:142]:     State Class: 'measurement'
[10:49:02][C][bmp280.sensor:142]:     Unit of Measurement: 'hPa'
[10:49:02][C][bmp280.sensor:142]:     Accuracy Decimals: 1
[10:49:02][C][bmp280.sensor:143]:     Oversampling: 16x
[10:49:02][C][aht10:136]: AHT10:
[10:49:02][C][aht10:137]:   Address: 0x38
[10:49:02][C][aht10:141]:   Temperature 'AHT20 temp'
[10:49:02][C][aht10:141]:     Device Class: 'temperature'
[10:49:02][C][aht10:141]:     State Class: 'measurement'
[10:49:02][C][aht10:141]:     Unit of Measurement: '°C'
[10:49:02][C][aht10:141]:     Accuracy Decimals: 1
[10:49:02][C][aht10:142]:   Humidity 'AHT20 humidity'
[10:49:02][C][aht10:142]:     Device Class: 'humidity'
[10:49:02][C][aht10:142]:     State Class: 'measurement'
[10:49:02][C][aht10:142]:     Unit of Measurement: '%'
[10:49:02][C][aht10:142]:     Accuracy Decimals: 1
[10:49:02][C][ens160:283]: ENS160
[10:49:02][C][ens160:284]:   Address: 0x52
[10:49:02][C][ens160:285]:   Update Interval: 60.0s
[10:49:02][C][ens160:286]:   CO2 Sensor 'ENS160 Sensor eCO2'
[10:49:02][C][ens160:286]:     Device Class: 'carbon_dioxide'
[10:49:02][C][ens160:286]:     State Class: 'measurement'
[10:49:02][C][ens160:286]:     Unit of Measurement: 'ppm'
[10:49:02][C][ens160:286]:     Accuracy Decimals: 1
[10:49:02][C][ens160:286]:     Icon: 'mdi:molecule-co2'
[10:49:02][C][ens160:287]:   TVOC Sensor 'ENS160 Sensor Total Volatile Organic Compounds'
[10:49:02][C][ens160:287]:     Device Class: 'volatile_organic_compounds'
[10:49:02][C][ens160:287]:     State Class: 'measurement'
[10:49:02][C][ens160:287]:     Unit of Measurement: 'ppb'
[10:49:02][C][ens160:287]:     Accuracy Decimals: 1
[10:49:02][C][ens160:287]:     Icon: 'mdi:radiator'
[10:49:02][C][ens160:288]:   AQI Sensor 'ENS160 Sensor Air Quality Index'
[10:49:02][C][ens160:288]:     Device Class: 'aqi'
[10:49:02][C][ens160:288]:     State Class: 'measurement'
[10:49:02][C][ens160:288]:     Unit of Measurement: 'index'
[10:49:02][C][ens160:288]:     Accuracy Decimals: 0
[10:49:02][C][ens160:288]:     Icon: 'mdi:chemical-weapon'
[10:49:02][C][ens160:291]:   Temperature Compensation 'AHT20 temp'
[10:49:02][C][ens160:291]:     Device Class: 'temperature'
[10:49:02][C][ens160:291]:     State Class: 'measurement'
[10:49:02][C][ens160:291]:     Unit of Measurement: '°C'
[10:49:02][C][ens160:291]:     Accuracy Decimals: 1
[10:49:02][C][ens160:292]:   Humidity Compensation 'AHT20 humidity'
[10:49:02][C][ens160:292]:     Device Class: 'humidity'
[10:49:02][C][ens160:292]:     State Class: 'measurement'
[10:49:02][C][ens160:292]:     Unit of Measurement: '%'
[10:49:02][C][ens160:292]:     Accuracy Decimals: 1
[10:49:02][C][captive_portal:088]: Captive Portal:
[10:49:02][C][mdns:108]: mDNS:
[10:49:02][C][mdns:109]:   Hostname: livingroom
[10:49:02][C][ota:093]: Over-The-Air Updates:
[10:49:02][C][ota:094]:   Address: livingroom.local:8266
[10:49:02][C][ota:097]:   Using Password.
[10:49:02][C][api:138]: API Server:
[10:49:02][C][api:139]:   Address: livingroom.local:6053
[10:49:02][C][api:143]:   Using noise encryption: NO
[10:49:04][D][api:102]: Accepted 192.168.1.118
[10:49:04][D][api.connection:959]: Home Assistant 2023.5.4 (192.168.1.118): Connected successfully
[10:49:36][D][bmp280.sensor:175]: Got temperature=24.1°C pressure=1003.4hPa
[10:49:36][D][sensor:093]: 'BMP temp': Sending state 24.08000 °C with 1 decimals of accuracy
[10:49:36][D][sensor:093]: 'BMP Pressure': Sending state 1003.38013 hPa with 1 decimals of accuracy
[10:49:46][D][aht10:083]: AHT10 is busy, waiting...
[10:50:31][D][bmp280.sensor:175]: Got temperature=24.1°C pressure=1003.4hPa
[10:50:31][D][sensor:093]: 'BMP temp': Sending state 24.14000 °C with 1 decimals of accuracy
[10:50:31][D][sensor:093]: 'BMP Pressure': Sending state 1003.39819 hPa with 1 decimals of accuracy
```

With this version
```
external_components:
  - source: github://pr#4243
    components:
      - ens160
```
I get following logs
```
[10:53:49][C][logger:301]: Logger:
[10:53:49][C][logger:302]:   Level: DEBUG
[10:53:49][C][logger:303]:   Log Baud Rate: 115200
[10:53:49][C][logger:305]:   Hardware UART: UART0
[10:53:49][C][i2c.arduino:053]: I2C Bus:
[10:53:49][C][i2c.arduino:054]:   SDA Pin: GPIO4
[10:53:49][C][i2c.arduino:055]:   SCL Pin: GPIO5
[10:53:49][C][i2c.arduino:056]:   Frequency: 50000 Hz
[10:53:49][C][i2c.arduino:059]:   Recovery: bus successfully recovered
[10:53:49][I][i2c.arduino:069]: Results from i2c bus scan:
[10:53:49][I][i2c.arduino:075]: Found i2c device at address 0x38
[10:53:49][I][i2c.arduino:075]: Found i2c device at address 0x52
[10:53:49][I][i2c.arduino:075]: Found i2c device at address 0x77
[10:53:49][C][bmp280.sensor:124]: BMP280:
[10:53:49][C][bmp280.sensor:125]:   Address: 0x77
[10:53:49][C][bmp280.sensor:137]:   IIR Filter: OFF
[10:53:49][C][bmp280.sensor:138]:   Update Interval: 55.0s
[10:53:49][C][bmp280.sensor:140]:   Temperature 'BMP temp'
[10:53:49][C][bmp280.sensor:140]:     Device Class: 'temperature'
[10:53:49][C][bmp280.sensor:140]:     State Class: 'measurement'
[10:53:49][C][bmp280.sensor:140]:     Unit of Measurement: '°C'
[10:53:49][C][bmp280.sensor:140]:     Accuracy Decimals: 1
[10:53:49][C][bmp280.sensor:141]:     Oversampling: 2x
[10:53:49][C][bmp280.sensor:142]:   Pressure 'BMP Pressure'
[10:53:49][C][bmp280.sensor:142]:     Device Class: 'pressure'
[10:53:49][C][bmp280.sensor:142]:     State Class: 'measurement'
[10:53:49][C][bmp280.sensor:142]:     Unit of Measurement: 'hPa'
[10:53:49][C][bmp280.sensor:142]:     Accuracy Decimals: 1
[10:53:49][C][bmp280.sensor:143]:     Oversampling: 16x
[10:53:49][C][aht10:136]: AHT10:
[10:53:49][C][aht10:137]:   Address: 0x38
[10:53:49][C][aht10:141]:   Temperature 'AHT20 temp'
[10:53:49][C][aht10:141]:     Device Class: 'temperature'
[10:53:49][C][aht10:141]:     State Class: 'measurement'
[10:53:49][C][aht10:141]:     Unit of Measurement: '°C'
[10:53:49][C][aht10:141]:     Accuracy Decimals: 1
[10:53:49][C][aht10:142]:   Humidity 'AHT20 humidity'
[10:53:49][C][aht10:142]:     Device Class: 'humidity'
[10:53:49][C][aht10:142]:     Sta [...]

2023-06-25 09:51 UTC, mrtoy-me commented
Hi Niyaz

Regarding logs for:
external_components:
  - source: github://pr#4243
    components:
      - ens160

Apologies... to see the reg status - you need to make logger level - verbose. This is worth doing to see what is going on, but it does not look good for a functional ENS160. 
Looks like setup works ok so it is communicating but per the ENS160 datasheet the first thing that should happen is ... 3 minutes warmup if it has been previously started (very first power up requires 1 hour of warmup before normal operation). What you are getting is no warm up and normal operation with no data ready, whereas you should be getting 3 min warm up and followed by entering normal mode with data ready (particularly with 60 second update).

2023-07-06 06:31 UTC, velijv commented
Tried it with https://www.aliexpress.us/item/1005004898420675.html - didn't get any responses, so i through crap sensor. 
Then https://www.aliexpress.com/item/1005004399782807.html - finally worked. 

But it always does "During first hour after power-on. Only once in a lifetime" after flashing, rebooting or losing power... 

| 0  | Operating ok     | Standard operating mode.                                                               |  
|----|------------------|----------------------------------------------------------------------------------------|
| 1  | Warm-up          | During first minute after power-on                                                     | 
| 2  | Initial Start-up | During first hour after power-on. Only once in a lifetime.                             | 
| 3  | No valid output  | Signals give unexpected values (very high or very low). Multiple sensors out of range. |  



> 09:28:45 | [D] | [ens160:254] | Status: ENS160 STATAS bit    0x1
> 09:28:45 | [D] | [ens160:256] | Status: ENS160 STATER bit    0x0
> 09:28:45 | [D] | [ens160:257] | Status: ENS160 VALIDITY FLAG 0x02
> 09:28:45 | [D] | [ens160:259] | Status: ENS160 NEWDAT bit    0x1
> 09:28:45 | [D] | [ens160:261] | Status: ENS160 NEWGPR bit    0x1
>

2023-07-06 07:38 UTC, niyazFattahov commented
> Tried it with https://www.aliexpress.us/item/1005004898420675.html - didn't get any responses, so i through crap sensor. Then https://www.aliexpress.com/item/1005004399782807.html - finally worked.
> 
> But it always does "During first hour after power-on. Only once in a lifetime" after flashing, rebooting or losing power...
> 
> 0	Operating ok	Standard operating mode.
> 1	Warm-up	During first minute after power-on
> 2	Initial Start-up	During first hour after power-on. Only once in a lifetime.
> 3	No valid output	Signals give unexpected values (very high or very low). Multiple sensors out of range.
> > 09:28:45 | [D] | [ens160:254] | Status: ENS160 STATAS bit    0x1
> > 09:28:45 | [D] | [ens160:256] | Status: ENS160 STATER bit    0x0
> > 09:28:45 | [D] | [ens160:257] | Status: ENS160 VALIDITY FLAG 0x02
> > 09:28:45 | [D] | [ens160:259] | Status: ENS160 NEWDAT bit    0x1
> > 09:28:45 | [D] | [ens160:261] | Status: ENS160 NEWGPR bit    0x1


my ens160 [aliexpress.ru/item/32803371228.html](url) seems doesn't work
I always get after starting 
```
[10:36:24][V][ens160:156]: Status: ENS160 STATAS bit    0x0
[10:36:24][V][ens160:158]: Status: ENS160 STATER bit    0x0
[10:36:24][V][ens160:160]: Status: ENS160 VALIDITY FLAG 0x00
[10:36:24][V][ens160:161]: Status: ENS160 NEWDAT bit    0x0
[10:36:24][V][ens160:163]: Status: ENS160 NEWGPR bit    0x1
[10:36:24][D][ens160:172]: ENS160 readings unavailable - Normal Operation but readings not ready
```

2023-07-06 17:51 UTC, niyazFattahov commented
why I don't see 'Setting up ENS160...' in the logs?
is it possible that 'setup()' function not perfomed for initalization?
But I see: 
```
[20:34:59][C][ens160:282]: ENS160:
[20:34:59][D][ens160:304]: Setup successful
```
 'dump_config()' performed

2023-07-07 11:58 UTC, mrtoy-me commented
Hi Velijv and Niyaz

Both your sensors don't appear to be working as per datasheet.

validity flag should be 0 for normal operation and that is what the component looks for. If validity flag is 2 per datasheet that indicates first start. After the first start a typical progression after reset or re-flash is validity flag = 1 for 3 minutes then goes to zero. The component does not read data until that happens and data is ready.

Data ready is indicated by the newdat bit and it needs to go to indicating data is ready, before data is read by the component.

Both your ens160 boards don't appear to be operating per the datasheet and the component is written according to the datasheet. 

About startup, you don't normally see log entries during setup, all the components I have used are the same. If you get "setup successful" message from dump_config, setup has run and worked.

If you want to do a totally independent check, I suggest you test your sensor with arduino ens160 library - both sciosense and sparkfun have libraries.

2023-07-07 16:47 UTC, NonaSuomy commented
Push the sensor down with your finger and hold it down while you boot and see if it picks it up. If it does you you may have to solder it back to the board with a hot air rework station ideally I would ask for a refund.

2023-07-13 15:22 UTC, velijv commented
For me it was wiring thing (soldered and all), apparently not well, or too long/thick wires. Now it boots at `ENS160 readings not available yet - Warming up requires 3 minutes` ✅

Note to self - triple check wires always.

2023-09-16 06:34 UTC, vincentscode commented
Hi @jesserockz, all the requested changes should be implemented. Could you look at this again?

2023-09-23 16:34 UTC, FlyGoat commented
Hi all,

Just come back to report success with this module: https://www.aliexpress.com/item/1005004052950350.html
```
[17:26:50][C][ens160:283]: ENS160
[17:26:50][C][ens160:284]:   Address: 0x53
[17:26:50][C][ens160:285]:   Update Interval: 10.0s
[17:26:50][C][ens160:286]:   CO2 Sensor 'ENS160 Sensor eCO2'
[17:26:50][C][ens160:286]:     Device Class: 'carbon_dioxide'
[17:26:50][C][ens160:286]:     State Class: 'measurement'
[17:26:50][C][ens160:286]:     Unit of Measurement: 'ppm'
[17:26:50][C][ens160:286]:     Accuracy Decimals: 1
[17:26:50][C][ens160:286]:     Icon: 'mdi:molecule-co2'
[17:26:50][C][ens160:287]:   TVOC Sensor 'ENS160 Sensor Total Volatile Organic Compounds'
[17:26:50][C][ens160:287]:     Device Class: 'volatile_organic_compounds'
[17:26:50][C][ens160:287]:     State Class: 'measurement'
[17:26:50][C][ens160:287]:     Unit of Measurement: 'ppb'
[17:26:50][C][ens160:287]:     Accuracy Decimals: 1
[17:26:50][C][ens160:287]:     Icon: 'mdi:radiator'
[17:26:50][C][ens160:288]:   AQI Sensor 'ENS160 Sensor Air Quality Index'
[17:26:50][C][ens160:288]:     Device Class: 'aqi'
[17:26:50][C][ens160:288]:     State Class: 'measurement'
[17:26:50][C][ens160:288]:     Unit of Measurement: 'index'
[17:26:50][C][ens160:288]:     Accuracy Decimals: 0
[17:26:50][C][ens160:288]:     Icon: 'mdi:chemical-weapon'
```
```
[17:29:07][D][sensor:094]: 'ENS160 Sensor eCO2': Sending state 407.00000 ppm with 1 decimals of accuracy
[17:29:07][D][sensor:094]: 'ENS160 Sensor Total Volatile Organic Compounds': Sending state 27.00000 ppb with 1 decimals of accuracy
[17:29:07][D][sensor:094]: 'ENS160 Sensor Air Quality Index': Sending state 1.00000 index with 0 decimals of accuracy
```

Now I'm reaaly looking forward to get ENS160 driver merged into esphome :-)

2023-10-09 08:50 UTC, ghsensdev commented
Hi,

I also would like to use this component. When can the change request be solved?

Thanks

2023-10-22 20:12 UTC, outpoints commented
@jesserockz is there anything else that needs to be done before implementing?

Thanks!

2023-10-28 09:22 UTC, xxddff commented
Every time I restart esp32 or flash the firmware, it will change to 
```
ENS160 VALIDITY FLAG 0x02
```
However, after an hour, the data can be read normally again. Is my ens160 damaged? Normally, doesn’t the second startup only take 3 minutes?

2023-10-28 18:56 UTC, bvarick commented
Thanks for writing this!
I noticed a couple unit issues:
- The device class should be changed to volatile_organic_compounds_parts (instead of volatile_organic_compounds) because its measured in ppb
- the AQI value should be unitless (instead of "index")
https://www.home-assistant.io/integrations/sensor/

2023-10-29 06:21 UTC, stephankn commented
> Every time I restart esp32 or flash the firmware, it will change to
> 
> ```
> ENS160 VALIDITY FLAG 0x02
> ```
> 
> However, after an hour, the data can be read normally again. Is my ens160 damaged? Normally, doesn’t the second startup only take 3 minutes?

As per data-sheet, the initial calibration phase takes one hour. Then you will get values. But sensor must be powered for 24 hours for it to persist the status that it has completed the initial calibration.
So actually, it takes 24 hours for the first calibration, but after the first hour in this period you start getting values.

Keep your sensor powered for >24h to persist this state and then subsequent starts are 3 minutes.

2023-11-04 10:34 UTC, xxddff commented
> > Every time I restart esp32 or flash the firmware, it will change to
> 
> > 
> 
> > ```
> 
> > ENS160 VALIDITY FLAG 0x02
> 
> > ```
> 
> > 
> 
> > However, after an hour, the data can be read normally again. Is my ens160 damaged? Normally, doesn’t the second startup only take 3 minutes?
> 
> 
> 
> As per data-sheet, the initial calibration phase takes one hour. Then you will get values. But sensor must be powered for 24 hours for it to persist the status that it has completed the initial calibration.
> 
> So actually, it takes 24 hours for the first calibration, but after the first hour in this period you start getting values.
> 
> 
> 
> Keep your sensor powered for >24h to persist this state and then subsequent starts are 3 minutes.

Thank you! After 24 hours, it only takes 3 minutes to warm up.

2023-11-05 16:47 UTC, Gorm-Minetest commented
Hello!
I've this sensor-combo ens160+aht21.
Tested it with different ESP but i don't get it working:

`ENS160 VALIDITY FLAG 0x03`

But when i connect the sensor to an Arduino Uno (lib: DFRobot_ENS160) it is working es expected:
```
Sensor operating status : 2
Air quality index : 1
Concentration of total volatile organic compounds : 55 ppb
Carbon dioxide equivalent concentration : 464 ppm
```
Esphome is latest version and i used a D1 Mini and a NODEMCUv3 but nothing.

If i use this code:
```
external_components:
#  - source:
#      type: git
#      url: https://github.com/vincentscode/esphome/
#      ref: test-ens160-stable # ens160 
  - source: github://pr#4243
    components:
      - ens160
```
i get a meaningful output like this:
```
[17:36:36][V][ens160:156]: Status: ENS160 STATAS bit    0x0
[17:36:36][V][ens160:158]: Status: ENS160 STATER bit    0x0
[17:36:36][V][ens160:160]: Status: ENS160 VALIDITY FLAG 0x00
[17:36:36][V][ens160:161]: Status: ENS160 NEWDAT bit    0x1
[17:36:36][V][ens160:163]: Status: ENS160 NEWGPR bit    0x1
[17:36:36][V][sensor:043]: 'ENS160 eCO2': Received new state 0.000000
[17:36:36][D][sensor:093]: 'ENS160 eCO2': Sending state 0.00000 ppm with 0 decimals of accuracy
[17:36:36][V][json:038]: Attempting to allocate 512 bytes for JSON serialization
[17:36:36][V][json:058]: Size after shrink 76 bytes
...
```
But the values are all zero!
If i use the commented part from above code snippet i only get 
`Status 0x3`

If you need some other info please tell me. 

regards Michael

2023-11-05 23:42 UTC, Geosham233 commented
"Is there a way to connect the "ENS160 + AHT21" to an ESP8266 module?"

2023-11-06 07:32 UTC, stephankn commented
@Gorm-Minetest and @Geosham233 
> "Is there a way to connect the "ENS160 + AHT21" to an ESP8266 module?"

Yes, it is. At least "sort of". I am using such a combined module, which you can get for ~7€ from AliExpress (eg https://www.aliexpress.com/item/1005004891574661.html) and connect it to esphome with esp01_1m. The I2C is on GPIO 0/2.
I have included this patch as _external_component_.

What troubles me is the AHT21 on the module. Intention is to use it for temperature compensation of the ENS160. Unfortunately the esphome aht10 driver did not work for me at all. it failed in setup(). Looking at the data sheet, the initialization differs completely from the AHT10. Instead of sending an "init" command, you have to set three registers.
I implemented my own driver, also taking care not to block the ESP long like the aht10 driver. 
Unfortunately, it only works for me if I have the log level to VERY_VERBOSE, otherwise I am getting frequently NACK on I2C. So my driver is not ready for publishing. 
http://www.aosong.com/userfiles/files/media/AHT21%E4%BA%A7%E5%93%81%E8%A7%84%E6%A0%BC%E4%B9%A6(%E8%8B%B1%E6%96%87%E7%89%88)%20A3.pdf
http://www.aosong.com/en/products-60.html

If you only want to use the ENS160, this driver here worked always fine for me and the module is responding as expected. You have to feed in 5V, there is a voltage regulator to create 1.8V for the ESP160. another regulator creates 3V3.

After initial connect of the ENS160 it will do a self calibration. This takes 24h, but after the first hour you are already receiving values. If you disconnect power earlier, the calibration will restart. This is the status 2. Wait the time and you will get readings.
I have never seen a status 3 reported with my module and this driver.
https://www.sciosense.com/wp-content/uploads/documents/SC-001224-DS-9-ENS160-Datasheet.pdf

Power-cycling the module with esphome still running gives me similar results like the one observed above with invalid readings. I think in this situation the state machine needs reset and module set up again.

Another maybe hardware related issue with such a combined module is that for me there are situations in which the AHT21 reports values too high. I am not certain what causes this. I suspect that I2C pins are not on right level while power-cycling and some back-flow via data happens. I also observed sometimes the chip heating up quickly after boot up to read ~4-5 degrees above ambient. Feeding in such bad calibration to ENS160 is not desired, but unlikely to cause the above symptom with status 3. Product manual did recommend to connect ground pin via a GPIO, which is not how it is wired on this combined module.

So in general, I would rate this ens160 driver as quite good and it works.

2023-11-06 14:10 UTC, michaelsidenius commented
This is my D1 mini  (ESP8266) setup for the "ENS160 + AHT21" board. Be aware of the general caviats mentioned by others about calibration etc. And having 5 boards, I see a lot of different behaviour, also with the AHT21 (TBC)

```
esphome:
  name: esphome-ens160
  friendly_name: ESPHome ENS160

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG # Alternatively: VERY_VERBOSE for much more logging of details

# Enable Home Assistant API
api:
  encryption:
    key: "?????????"

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPhome-ENS160"
    password: "????????"

captive_portal:


# Define the I2C bus connection (using di_mini notation from the PCB)
i2c:
  id: i2c_component
  scl: D1
  sda: D2
  scan: true
  frequency: 200kHz # Seems to work fine, default is 50kHz, you can play with this

# Get the un-released driver from the git PR
external_components:
  - source: github://pr#4243
    components:
      - ens160
    
sensor:
  - platform: aht10
    id: aht21_sensor
    address: 0x38
    update_interval: 10s  # This you can play with
    temperature:
      name: "AHT21 Temperature"
      id: aht21_temp
    humidity:
      name: "AHT21 Humidity"
      id: aht21_humi

  - platform: ens160
    id: ens160_sensor
    address: 0x53
    update_interval: 10s # This you can play with
    eco2:
      name: "ENS160 eCO2"
      id: ens160_eco2
    tvoc:
      name: "ENS160 Total Volatile Organic Compounds"
      id: ens160_tvoc
    aqi:
      name: "ENS160 Air Quality Index"
      id: ens160_aqi
    compensation:
      # Inject the temp/humi data from the AHT21 into the ENS160 attached module for compensation.
      # Makes the gas results more accurate.
      temperature: aht21_temp
      humidity: aht21_humi
```

2023-11-06 23:18 UTC, mcarbonneaux commented
> What troubles me is the AHT21 on the module. Intention is to use it for temperature compensation of the ENS160. Unfortunately the esphome aht10 driver did not work for me at all.

normaly the documentation say that the AHT21 are supported !?

https://esphome.io/components/sensor/aht10.html?highlight=aht21

2023-11-07 06:04 UTC, vincentscode commented
Hi @jesserockz, this PR has been ready to be merged for a while, why has it been marked as a draft?

2023-11-07 06:53 UTC, mrtoy-me commented
> Hello! I've this sensor-combo ens160+aht21. Tested it with different ESP but i don't get it working:
> 
> `ENS160 VALIDITY FLAG 0x03`
> 
> But when i connect the sensor to an Arduino Uno (lib: DFRobot_ENS160) it is working es expected:
> 
> ```
> Sensor operating status : 2
> Air quality index : 1
> Concentration of total volatile organic compounds : 55 ppb
> Carbon dioxide equivalent concentration : 464 ppm
> ```
> 
> Esphome is latest version and i used a D1 Mini and a NODEMCUv3 but nothing.
> 
> If i use this code:
> 
> ```
> external_components:
> #  - source:
> #      type: git
> #      url: https://github.com/vincentscode/esphome/
> #      ref: test-ens160-stable # ens160 
>   - source: github://pr#4243
>     components:
>       - ens160
> ```
> 
> i get a meaningful output like this:
> 
> ```
> [17:36:36][V][ens160:156]: Status: ENS160 STATAS bit    0x0
> [17:36:36][V][ens160:158]: Status: ENS160 STATER bit    0x0
> [17:36:36][V][ens160:160]: Status: ENS160 VALIDITY FLAG 0x00
> [17:36:36][V][ens160:161]: Status: ENS160 NEWDAT bit    0x1
> [17:36:36][V][ens160:163]: Status: ENS160 NEWGPR bit    0x1
> [17:36:36][V][sensor:043]: 'ENS160 eCO2': Received new state 0.000000
> [17:36:36][D][sensor:093]: 'ENS160 eCO2': Sending state 0.00000 ppm with 0 decimals of accuracy
> [17:36:36][V][json:038]: Attempting to allocate 512 bytes for JSON serialization
> [17:36:36][V][json:058]: Size after shrink 76 bytes
> ...
> ```
> 
> But the values are all zero! If i use the commented part from above code snippet i only get `Status 0x3`
> 
> If you need some other info please tell me.
> 
> regards Michael
> 
> ps: I changed the 3.3V from the chip to the 5V source on my NODeMCU. Before i used the 3.3V as source and used the code that is commented above and now it is working but there are two VALID Flags:
> 
> ```
> [17:55:00][V][ens160:159]: Status: 0x8b
> [17:55:00][V][ens160:184]: Status: ENS160_DATA_STATUS_STATAS 0x1
> [17:55:00][V][ens160:186]: Status: ENS160_DATA_STATUS_STATER 0x0
> [17:55:00][V][ens160:188]: Status: ENS160_DATA_STATUS_VALID_B 0x1
> [17:55:00][V][ens160:190]: Status: ENS160_DATA_STATUS_VALID_A 0x0
> [17:55:00][V][ens160:192]: Status: ENS160_DATA_STATUS_NEWDAT 0x1
> [17:55:00][V][ens160:194]: Status: ENS160_DATA_STATUS_NEWGPR 0x1
> [17:55:00][V][sensor:043]: 'ENS160 eCO2': Received new state 406.000000
> [17:55:00][D][sensor:093]: 'ENS160 eCO2': Sending state 406.00000 ppm with 1 decimals of accuracy
> [17:55:00][V][json:038]: Attempting to allocate 512 bytes for JSON serialization
> [17:55:00][V][json:058]: Size after shrink 80 bytes
> [17:55:00][V][sensor:043]: 'ENS160 Total Volatile Organic Compounds': Received new state 26.000000
> [17:55:00][D][sensor:093]: 'ENS160 Total Volatile Organic Compounds': Sending state 26.00000 ppb with 1 decimals of accuracy
> [17:55:00][V][json:038]: Attempting to allocate 512 bytes for JSON serialization
> [17:55:00][V][json:058]: Size after shrink 104 bytes
> [17:55:00][V][sensor:043]: 'ENS160 Air Quality Index': Received new state 1.000000
> [17:55:00][D][sensor:093]: 'ENS160 Air Quality Index': Sending state 1.00000 index with 0 decimals of accuracy
> [17:55:00][V][json:038]: Attempting to allocate 512 bytes for JSON serialization
> [17:55:00][V][json:058]: Size after shrink 88 bytes
> ```

Hi
source: github://pr#4243 is the correct reference I believe
The up to date current component which has not changed for quite a while show in verbose debug - Status: ENS160 VALIDITY FLAG 0x..
if you get two VALIDITY FLAGS VALID_B and VALID_A that is a prior version.

2023-11-10 15:47 UTC, Gorm-Minetest commented
Hello!

I am now feeding the ens160-chips directly with 5V and now they are running without any issue.
If i set them to 3.3V they behave randomly. Sometimes they work and sometimes not.
I guess this is only an issue from the ens160-chip.

Regards Michael

2023-11-11 08:53 UTC, stephankn commented
> I am now feeding the ens160-chips directly with 5V and now they are running without any issue. If i set them to 3.3V they behave randomly. Sometimes they work and sometimes not. I guess the issues i had were only related to this.

Please have a look at the data sheet. The ENS160 chip requires two input voltages. VDD on pin 4 of typical 1.8V and VDDio on pin 5 of 1.7 to 3.6V (I see it connected to 3.3V on my module).

![image](https://github.com/esphome/esphome/assets/251140/b91d53d5-173f-44a4-99f6-41e64d332f8d)

I guess that you are not using the chip directly, but instead some module where some company soldered the chip and probably some voltage regulators. Directly feeding 5V by far exceeds the maximum rating of the chip. Maybe you have a similar module than I do.

On my module (named ENS160+AHT2x), there are two voltage regulators connected to VIN. A 65K5 producing 1.8V towards pin 4 and a 662K producing 3.3V towards pin 5, both stabilized with capacitors as required by the ENS160 data sheet (see figure 14).

This is a sample photo of such a combined module of ENS160 and some temperature/humidity sensor for compensation of measurements.

![image](https://www.androegg.de/wp-content/uploads/2022/11/ENS160AHT21-Kohlendioxid-Sensor-Modul-kompl.jpg)

2023-11-11 12:46 UTC, Gorm-Minetest commented
Hello

@stephankn 

What made me think 5V are maybe good/ok was when i connect the chip (board) in question to an Arduino Uno. There it is working out of the box.

```
Sensor operating status : 1
Air quality index : 3
Concentration of total volatile organic compounds : 365 ppb
Carbon dioxide equivalent concentration : 823 ppm
```

I measured the voltage at the points where the ens160 is connected (there are 2 resistors? connected to the pins, there i can measure the voltage) and the voltages are as you mentioned. So you are right. But applying 5V seems to do no harm to the chip. At Pin 4 and 5 are ~1.8V and ~3.3V.



Sorry and yes i use a board like that in your picture.
Marked the points where i measured the voltage
![ens160+aht2X](https://github.com/esphome/esphome/assets/132831505/80a7de39-6bda-4b6c-8faf-0e9c487b1713)

Regards Michael

ps. Currently the ens160 is not working at all if i connect him to an ESP. Only the AHT2X is working always. Tried 3 different ESPs. But with an Arduino it works.

2023-11-11 13:55 UTC, stephankn commented
@Gorm-Minetest yes, the test points you marked are the voltage input towards the ENS160, which is the silver chip. So you are not feeding 5V to it, but the 1.8V/3.3.V.
You are feeding 5V via VIN to your _module_ (the PCB containing then ens160 chip+other things like regulators, capacitors and the aht21). Part of that are the two voltage regulators. The black chip on the left side with three pins. You can trace the PCB towardds the input of the chip and by that huge via towards the 3V3 label, which is then a "out" of 3V3. The two beige colored chips are ceramic capacitors which stabilize the voltage of the ENS160.

For me the ENS160 works perfect with the code here on ESP8266. I have trouble with the AHT21.

I wonder whether this is a thing with the start up of the module and timing. I am not certain the I2C is having the right pull-up in place to boot with a defined setup. This could explain the various communication problems in these comments.
I still try to understand the purpose of the network resistor and transistor package at lower side of the module.

I am still convinced that the source code of vincent is good and it should be merged into esphome. Maybe there could be a counter in this state: if (data_ready != ENS160_DATA_STATUS_NEWDAT) { to try to re-initialize the chip if the situation persists for too long. Power-cycling the chip but not re-running the setup of esphome leads there.

2023-11-21 06:59 UTC, kbx81 requested changes
Couple little nitpicks, otherwise lgtm

2023-11-21 06:59 UTC, kbx81 commented on esphome/components/ens160/sensor.py
> +    DEVICE_CLASS_AQI,
```suggestion
    CONF_ECO2,
    CONF_HUMIDITY,
    CONF_ID,
    CONF_TEMPERATURE,
    CONF_TVOC,
    DEVICE_CLASS_AQI,
    DEVICE_CLASS_CARBON_DIOXIDE,
    DEVICE_CLASS_VOLATILE_ORGANIC_COMPOUNDS,
    ICON_CHEMICAL_WEAPON,
    ICON_MOLECULE_CO2,
    ICON_RADIATOR,
    STATE_CLASS_MEASUREMENT,
    UNIT_PARTS_PER_BILLION,
    UNIT_PARTS_PER_MILLION,
```

2023-11-21 06:59 UTC, kbx81 commented on esphome/components/ens160/sensor.py
> +CONF_AQI = "aqi"
```suggestion
CONF_AQI = "aqi"
CONF_COMPENSATION = "compensation"
```

2023-11-23 03:16 UTC, kbx81 approved these changes

2023-11-24 04:31 UTC, merged

2023-11-25 14:16 UTC, EdIVeDeR commented
Hi! His it merge at this moment?