increase size filter range
OttoWinter/esphomeyaml pull request #4244
Opened 2022-12-30 20:57 UTC by max246

# What does this implement/fix?

Increase size of the filter value from uint8 to unit32 to allow a large number than 255

## Types of changes

- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <[link to issue](https://github.com/esphome/issues/issues/3537)>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
remote_receiver:
  pin: D0
  dump:
    - rc_switch
  tolerance: 50%
  filter: 350us
  idle: 4ms
  buffer_size: 2kb
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-31 14:51 UTC, max246 commented
Can it be merge?

2023-04-04 02:36 UTC, jesserockz requested changes
The config validation side only allows up to 255 as a value, also the code that uses the filter in RMT is `uint8_t filter_ticks_thresh`, so not sure this will work as intended?

2023-04-04 09:58 UTC, max246 commented
> The config validation side only allows up to 255 as a value, also the code that uses the filter in RMT is `uint8_t filter_ticks_thresh`, so not sure this will work as intended?

Right that means this requests can be done if RMT wont update their drivers.

Should I just cancel the PR or is there another way you can think of it can be done?

2023-04-12 21:55 UTC, jesserockz commented
Yeah unless there is a different method in rmt, we cant achieve this in ESPHome right now.

Best to close the PR for now. I dont have time to look into another solution right now, but may visit in the future. Happy to look again if you find something else.

2023-04-13 08:15 UTC, closed without merging