Dispay the configured esphome:comment on the WebServer
OttoWinter/esphomeyaml pull request #4246
Opened 2022-12-31 03:57 UTC by grillp

This code displays the configured `esphome:comment` under the title on the web server.

- It does this by passing through the configured `esphome:comment` through to the App object during setup.
- This is then passed to the WebServer front end as part of the `ping` call.

Example:
```yaml
esphome:
  name: tester-d8407a
  comment: This Will appear in the WebConsole's header

esp8266:
  board: esp01_1m

# Enable logging
logger:

ota:

api:

web_server:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tester-D8407A Fallback Hotspot"
    password: "lE7PR8uNHwlX"

captive_portal:
```

gives:
![image](https://user-images.githubusercontent.com/122615/210124071-90e35d62-d65f-4230-855b-244b5b22164f.png)

Note: 
- This requires esphome_frontend chage [esphome-webserver/PR24](https://github.com/esphome/esphome-webserver/pull/24)  to function correctly 
- This is backward compatible, so will not break functionality without the matching frontend version

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** None

Note: No Doc Changes Required

**Pull request in [esphome-frontend](https://github.com/esphome/esphome-frontend) with relevant code changes:** 
https://github.com/esphome/esphome-webserver/pull/24

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] No changes in functionality or configuration variables.

2023-01-11 14:17 UTC, RoboMagus requested changes
I like this addition, but please fix the coppied comment.

2023-01-11 14:17 UTC, RoboMagus commented on esphome/core/application.h
> +  /// Get the name of this Application set by set_name().
This comment is lying about the lines that follow

2023-01-14 07:44 UTC, RoboMagus approved these changes

2023-01-16 23:13 UTC, jesserockz approved these changes

2023-01-17 00:02 UTC, merged