Update the FastLED compoment
OttoWinter/esphomeyaml pull request #4257
Opened 2023-01-03 23:19 UTC by nielsnl68

# What does this implement/fix?

This PR does 2 thinks, first of all it will resolve the current issue (having warnings about the register attribute not used anymore and some other small warnings) with the current version of the FastLED library.
The other is moving the FastLed_clockless and FastLED_SPI together as one component.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-21 19:16 UTC, sermayoral commented
Hi! Great job! The idea is wonderful.

But it's not working for me. No error. The light does not just turn on :-(

Firm is:

```
external_components:
  - source: github://pr#4257
    components: [fastled]
    refresh: 1d

substitutions:
  device_name: vitrina
  friendly_name: Vitrina
  
esphome:
  name: ${device_name}
  comment: ${friendly_name}
  
esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Importa la configuracion comun
<<: !include common/common.yaml

# Habilita la subida por OTA
ota:
  password: !secret passwd_esphome

# Habilita el logging
logger:
  
# Habilita el acceso web al ESP
# web_server:
#   port: 80

light:
  - platform: fastled
    chipset: WS2812B
    rgb_order : GRB
    pin: 17
    num_leds: 94
    name: "LED Vitrina"
    restore_mode: RESTORE_AND_OFF
    <<: !include common/addressable_effects.yaml
  - platform: fastled
    chipset: WS2812B
    rgb_order: GRB
    pin: 16
    num_leds: 94
    name: "LED Interior Vitrina"
    id: led_interior_vitrina
    restore_mode: RESTORE_AND_OFF
    <<: !include common/addressable_effects.yaml
```

Log is:

```
INFO Reading configuration /config/esphome/vitrina.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing vitrina (board: esp-wrover-kit; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- FastLED @ 3.5.0+sha.6afcfe0
RAM:   [=         ]  12.2% (used 39984 bytes from 327680 bytes)
Flash: [=====     ]  50.7% (used 931229 bytes from 1835008 bytes)
========================= [SUCCESS] Took 23.37 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of esp-vitrina.lan
INFO  -> 192.168.33.62
INFO Uploading /data/vitrina/.pioenvs/vitrina/firmware.bin (937008 bytes)
Uploading: [============================================================] 100% Done...


INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from esp-vitrina.lan using esphome API
INFO Successfully connected to esp-vitrina.lan
[20:11:39][I][app:102]: ESPHome version 2023.2.3 compiled on Feb 21 2023, 20:06:20
[20:11:39][C][wifi:504]: WiFi:
[20:11:39][C][wifi:362]:   Local MAC: 24:6F:28:97:0A:84
[20:11:39][C][wifi:363]:   SSID: [redacted]
[20:11:39][C][wifi:364]:   IP Address: 192.168.33.62
[20:11:39][C][wifi:366]:   BSSID: [redacted]
[20:11:39][C][wifi:367]:   Hostname: 'vitrina'
[20:11:39][C][wifi:369]:   Signal strength: -53 dB ▂▄▆█
[20:11:39][C][wifi:373]:   Channel: 6
[20:11:39][C][wifi:374]:   Subnet: 255.255.255.0
[20:11:39][C][wifi:375]:   Gateway: 192.168.33.1
[20:11:39][C][wifi:376]:   DNS1: 192.168.33.30
[20:11:39][C][wifi:377]:   DNS2: 192.168.33.1
[20:11:39][C][logger:293]: Logger:
[20:11:39][C][logger:294]:   Level: DEBUG
[20:11:39][C][logger:295]:   Log Baud Rate: 115200
[20:11:39][C][logger:296]:   Hardware UART: UART0
[20:11:39][C][fastled:021]: FastLED light:
[20:11:39][C][fastled:022]:   Num LEDs: 94
[20:11:39][C][fastled:023]:   Max refresh rate: 400
[20:11:39][C][fastled:021]: FastLED light:
[20:11:39][C][fastled:022]:   Num LEDs: 94
[20:11:39][C][fastled:023]:   Max refresh rate: 400
[20:11:40][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Puerta Vitrina Izquierda'
[20:11:40][C][gpio.binary_sensor:015]:   Device Class: 'door'
[20:11:40][C][gpio.binary_sensor:016]:   Pin: GPIO34
[20:11:40][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Puerta Vitrina Derecha'
[20:11:40][C][gpio.binary_sensor:015]:   Device Class: 'door'
[20:11:40][C][gpio.binary_sensor:016]:   Pin: GPIO35
[20:11:40][C][light:104]: Light 'LED Vitrina'
[20:11:40][C][light:106]:   Default Transition Length: 1.0s
[20:11:40][C][light:107]:   Gamma Correct: 2.80
[20:11:40][C][light:104]: Light 'LED Interior Vitrina'
[20:11:40][C][light:106]:   Default Transition Length: 1.0s
[20:11:40][C][light:107]:   Gamma Correct: 2.80
[20:11:40][C][captive_portal:088]: Captive Portal:
[20:11:40][C][ota:093]: Over-The-Air Updates:
[20:11:40][C][ota:094]:   Address: esp-vitrina.lan:3232
[20:11:40][C][ota:097]:   Using Password.
[20:11:40][C][api:138]: API Server:
[20:11:40][C][api:139]:   Address: esp-vitrina.lan:6053
[20:11:40][C][api:141]:   Using noise encryption: YES
[20:11:46][D][api:102]: Accepted ::FFFF:192.168.33.30
[20:11:46][D][api.connection:918]: Home Assistant 2023.2.5 (::FFFF:192.168.33.30): Connected successfully
[20:12:21][D][esp32.preferences:113]: Saving 1 preferences to flash...
[20:12:21][D][esp32.preferences:142]: Saving 1 preferences to flash: 1 cached, 0 written, 0 failed
[20:12:46][D][light:035]: 'LED Interior Vitrina' Setting:
[20:12:46][D][light:046]:   State: ON
[20:12:46][D][light:084]:   Transition length: 1.0s
[20:12:48][D][light:035]: 'LED Vitrina' Setting:
[20:12:48][D][light:046]:   State: ON
[20:12:48][D][light:084]:   Transition length: 1.0s
[20:12:49][D][light:035]: 'LED Vitrina' Setting:
[20:12:49][D][light:046]:   State: OFF
[20:12:49][D][light:084]:   Transition length: 1.0s
[20:12:50][D][light:035]: 'LED Vitrina' Setting:
[20:12:50][D][light:046]:   State: ON
[20:12:50][D][light:084]:   Transition length: 1.0s
[20:12:52][D][light:035]: 'LED Vitrina' Setting:
[20:12:52][D][light:050]:   Brightness: 41%
[20:12:52][D][light:084]:   Transition length: 1.0s
[20:12:52][D][light:035]: 'LED Vitrina' Setting:
[20:12:52][D][light:050]:   Brightness: 39%
[20:12:52][D][light:084]:   Transition length: 1.0s
[20:12:54][D][light:035]: 'LED Vitrina' Setting:
[20:12:54][D][light:050]:   Brightness: 100%
[20:12:54][D][light:084]:   Transition length: 1.0s
[20:12:55][D][light:035]: 'LED Vitrina' Setting:
[20:12:55][D][light:054]:   Color brightness: 100%
[20:12:55][D][light:058]:   Red: 100%, Green: 100%, Blue: 100%
[20:12:55][D][light:084]:   Transition length: 1.0s
[20:12:55][D][light:035]: 'LED Vitrina' Setting:
[20:12:55][D][light:054]:   Color brightness: 100%
[20:12:55][D][light:058]:   Red: 53%, Green: 38%, Blue: 100%
[20:12:55][D][light:084]:   Transition length: 1.0s
[20:12:56][D][light:035]: 'LED Vitrina' Setting:
[20:12:56][D][light:054]:   Color brightness: 100%
[20:12:56][D][light:058]:   Red: 50%, Green: 100%, Blue: 87%
[20:12:56][D][light:084]:   Transition length: 1.0s
[20:12:58][D][light:035]: 'LED Vitrina' Setting:
[20:12:58][D][light:046]:   State: OFF
[20:12:58][D][light:084]:   Transition length: 1.0s
```

2023-02-26 21:45 UTC, nielsnl68 commented
@sermayoral i can't reproduce this with my esp8266 configuration. For me it works fine.

2023-03-21 16:06 UTC, k-w-1 commented
Not sure if helpful, but for me to use the code from this PR I had to make the following changes in my config:

1. Remove the ESP8266 framework pinning:
```
#esp8266:
#  framework:
#    version: 2.7.4
```
2. Change the light platform from `fastled_clockless` to `fastled`

That said, I still do get the following warnings during compilation (no noticeable end effect, however; all seems to work as intended):

```In file included from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms/esp/8266/fastled_esp8266.h:9,
                 from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms.h:40,
                 from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/FastLED.h:62,
                 from src/esphome/components/fastled/fastled_light.h:16,
                 from src/esphome.h:21,
                 from src/main.cpp:3:
/data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms/esp/8266/clockless_esp8266.h: In instantiation of 'void ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::showPixels(PixelController<RGB_ORDER>&) [with int DATA_PIN = 14; int T1 = 20; int T2 = 50; int T3 = 30; EOrder RGB_ORDER = GRB; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 85]':
/data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms/esp/8266/clockless_esp8266.h:38:15:   required from here
/data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms/esp/8266/clockless_esp8266.h:41:27: warning: 'static uint32_t ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::showRGBInternal(PixelController<RGB_ORDER>) [with int DATA_PIN = 14; int T1 = 20; int T2 = 50; int T3 = 30; EOrder RGB_ORDER = GRB; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 85; uint32_t = unsigned int]' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
   41 |     while((showRGBInternal(pixels)==0) && cnt--) {
      |            ~~~~~~~~~~~~~~~^~~~~~~~
In file included from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms/esp/8266/fastled_esp8266.h:9,
                 from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms.h:40,
                 from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/FastLED.h:62,
                 from src/esphome/components/fastled/fastled_light.h:16,
                 from src/esphome.h:21,
                 from src/main.cpp:3:
/data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms/esp/8266/clockless_esp8266.h:80:34: note: declared here
   80 |  static uint32_t ICACHE_RAM_ATTR showRGBInternal(PixelController<RGB_ORDER> pixels) {
      |                                  ^~~~~~~~~~~~~~~
In file included from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms/esp/8266/fastled_esp8266.h:9,
                 from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms.h:40,
                 from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/FastLED.h:62,
                 from src/esphome/components/fastled/fastled_light.h:16,
                 from src/esphome.h:21,
                 from src/main.cpp:3:
/data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms/esp/8266/clockless_esp8266.h:41:27: warning: 'static uint32_t ClocklessController<DATA_PIN, T1, T2, T3, RGB_ORDER, XTRA0, FLIP, WAIT_TIME>::showRGBInternal(PixelController<RGB_ORDER>) [with int DATA_PIN = 14; int T1 = 20; int T2 = 50; int T3 = 30; EOrder RGB_ORDER = GRB; int XTRA0 = 0; bool FLIP = false; int WAIT_TIME = 85; uint32_t = unsigned int]' is deprecated: Use IRAM_ATTR in place of ICACHE_RAM_ATTR to move functions into IRAM [-Wdeprecated-declarations]
   41 |     while((showRGBInternal(pixels)==0) && cnt--) {
      |            ~~~~~~~~~~~~~~~^~~~~~~~
In file included from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms/esp/8266/fastled_esp8266.h:9,
                 from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms.h:40,
                 from /data/mctorch1/.piolibdeps/mctorch1/FastLED/src/FastLED.h:62,
                 from src/esphome/components/fastled/fastled_light.h:16,
                 from src/esphome.h:21,
                 from src/main.cpp:3:
/data/mctorch1/.piolibdeps/mctorch1/FastLED/src/platforms/esp/8266/clockless_esp8266.h:80:34: note: declared here
   80 |  static uint32_t ICACHE_RAM_ATTR showRGBInternal(PixelController<RGB_ORDER> pixels) {
      |                                  ^~~~~~~~~~~~~~~```

2023-04-20 09:34 UTC, PaulSchulz commented
I still have issues with this pull request with my 'esp32-s3' based Heltec board. (Heltec Wifi LoRa V3) - It works with my V2 version Heltec board wich uses an ESP32 processor.

- ESPhome still pulls in FastLED @ 3.3.2

I have been able to sucessfully use FastLED @ 3.5.0 if I use it directly from C++ in a 'custom_configuration'.

2023-05-16 20:39 UTC, lboue commented
It doesn't work in my case with a WS2812C-2020 LED with PR 4257 witch updates FastLED to a version that supports ESP32-S3
This compiles but it is impossible to control the LED
```
external_components:
  - source: github://pr#4257
    components: [fastled]

# RGB	WS2812C-2020 LED
light:
  - platform: fastled 
    chipset: WS2812B
    pin: 35 # LED35
    num_leds: 1
    rgb_order: GRB
    id: status_led
    name: AtomS3 lite Light
```
[logs_m5-atoms3-c84858_run.txt](https://github.com/esphome/esphome/files/11491856/logs_m5-atoms3-c84858_run.txt)

2023-05-16 21:56 UTC, PaulSchulz commented
> It doesn't work in my case with a [WS2812C-2020 LED](https://datasheet.lcsc.com/lcsc/2202221130_Worldsemi-WS2812C-2020-V1_C2976072.pdf) with PR 4257 witch updates FastLED to a version that supports ESP32-S3. This compiles but it is impossible to control the LED
> 
> ```
> external_components:
>   - source: github://pr#4257
>     components: [fastled]
> 
> # RGB	WS2812C-2020 LED
> light:
>   - platform: fastled 
>     chipset: WS2812B
>     pin: 35 # LED35
>     num_leds: 1
>     rgb_order: GRB
>     id: status_led
>     name: AtomS3 lite Light
> ```
> 
> [logs_m5-atoms3-c84858_run.txt](https://github.com/esphome/esphome/files/11491856/logs_m5-atoms3-c84858_run.txt)

Are you able to try using a different GPIO pin? I have successfully used GPIO6.

I don't know precisely what is going on, but there is a difference between compiling the code for ESP32 and ESP32-S3 in that some pins that used to work for output no longer work. I have my suspisions in that it might have something to do with the way the pins are used and connected to internal peripherals, but I haven't been able to confirm anything.

2023-05-16 22:00 UTC, lboue commented
> > It doesn't work in my case with a [WS2812C-2020 LED](https://datasheet.lcsc.com/lcsc/2202221130_Worldsemi-WS2812C-2020-V1_C2976072.pdf) with PR 4257 witch updates FastLED to a version that supports ESP32-S3. This compiles but it is impossible to control the LED
> > ```
> > external_components:
> >   - source: github://pr#4257
> >     components: [fastled]
> > 
> > # RGB	WS2812C-2020 LED
> > light:
> >   - platform: fastled 
> >     chipset: WS2812B
> >     pin: 35 # LED35
> >     num_leds: 1
> >     rgb_order: GRB
> >     id: status_led
> >     name: AtomS3 lite Light
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [logs_m5-atoms3-c84858_run.txt](https://github.com/esphome/esphome/files/11491856/logs_m5-atoms3-c84858_run.txt)
> 
> Are you able to try using a different GPIO pin? I have successfully used GPIO6.
> 
> I don't know precisely what is going on, but there is a difference between compiling the code for ESP32 and ESP32-S3 in that some pins that used to work for output no longer work. I have my suspisions in that it might have something to do with the way the pins are used and connected to internal peripherals, but I haven't been able to confirm anything.

I can't because it's soldered on the M5 AtomS3 lite board. But neopixelbus driver worksfine with that config:

```
# RGB	WS2812C-2020 LED
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812X
    pin: 35
    num_leds: 1
    name: "NeoPixel Light"

```

2023-05-17 00:44 UTC, PaulSchulz commented
**Note** the ESPHome documentation has some things to say about the use of ESP Pins
https://esphome.io/components/esp32.html#gpio-pin-numbering

Not sure how this should be changed for the ESP32-S3.

I am using a Heltec V3 board, and was able to change my output pin

2023-05-30 06:45 UTC, lboue commented
[FastLED 3.6.0 release](https://github.com/FastLED/FastLED/releases/tag/3.6.0) was release yesterday.

2023-06-16 11:11 UTC, PaulSchulz commented
If anyone is still having issues, I found the following platform which appears to work better (until the above is fixed) - esp32_rmt_led_strip

It also appears to use ESP32 hardware to control timings etc. I have had less flickering with longer and more power intensive LED strings - WS2812

I was made aware of this library from the following: 
https://github.com/esphome/media-players/blob/main/m5stack-atom-echo.yaml

2023-08-21 05:01 UTC, bibach commented
This PR is working for me on a LilyGO T-Dongle-S3 board with an ESP32-S3 and a single APA102 LED on GPIO 39 and 40.  The higher-numbered pins wouldn't work, previously, due to missing ESP32-S3 pin definitions in the older version of the FastLED library.

```yaml
external_components:
  - source: github://pr#4257
    components: [fastled]
    refresh: always

light:
  - platform: fastled
    chipset: APA102
    clock_pin: GPIO39
    data_pin: GPIO40
    num_leds: 1
    rgb_order: BGR
    data_rate: 10MHz
    restore_mode: RESTORE_AND_OFF
    name: T-Dongle-S3 RGB LED
    id: t_dongle_s3_rgb_led
```

I created a pull request on esphome-docs in an attempt to satisfy the needs-docs tag.  It looks like an extra blank line needs to be removed from this branch to satisfy the clang-format check.  Not sure if there's a way for me to help with that.

Is there anything else I can do to help this move forward?

2023-08-21 21:17 UTC, nielsnl68 commented
thanks @bibach for reporting back.

2023-08-21 21:42 UTC, bibach commented
Thank you for all your work on the code, @nielsnl68!

Can you take a look at the esphome-docs pull request I added, above, to make sure everything looks good?  In particular, I wasn't sure if I was correct in adding the warnings about the existing, separate light platforms now being deprecated.  Hopefully, this will help check the remaining boxes to get this change incorporated.

2023-08-21 22:28 UTC, nielsnl68 commented
> Thank you for all your work on the code, @nielsnl68 !
> 
> Can you take a look at the esphome-docs pull request I added, above, to make sure everything looks good? In particular, I wasn't sure if I was correct in adding the warnings about the existing, separate light platforms now being deprecated. Hopefully, this will help check the remaining boxes to get this change incorporated.

 can you give me the link to the esphome-doc PR you made? then i will add it to the top text.

2023-08-21 22:46 UTC, bibach commented
https://github.com/esphome/esphome-docs/pull/3148

2023-09-12 08:10 UTC, lowercasename commented
Is it worth testing this with an RP2040 device, or does it still compile on RP2040 with these changes?

2023-09-12 11:21 UTC, nielsnl68 commented
> Is it worth testing this with an RP2040 device, or does it still not compile on RP2040 with these changes?

I do not have an RP2040, so please try and see if it works.

2023-10-24 21:37 UTC, bibach commented
@nielsnl68 I updated the esphome-docs pull request to resolve a merge conflict, so it should be good to go.  Is there anything else remaining to resolve on this, or is it just awaiting review by @OttoWinter ?

2023-10-24 22:23 UTC, nielsnl68 commented
Thanks for updating the documentation.

This PR needs to be validated by @jesserockz or other team members. It is not clear to me what the esphome team wound to do with the FastLed component. I already asked this on discord.

2023-11-07 21:29 UTC, rafafuenza commented
Can´t compile:

`  - 
    Source is not a file system path, in expected github://username/name[@branch-or-tag] or github://pr#1234 format!.
    source: github://#4257
    components: 
      - fastled
    refresh: always`

What can I do?

2023-11-07 21:31 UTC, ssieb commented
Compare what you wrote with what the error is telling you.

2023-11-13 00:18 UTC, jesserockz requested changes

2023-11-13 00:18 UTC, jesserockz commented on esphome/components/fastled_base/__init__.py
> +    cg.add_library("fastled/FastLED", "3.5.0")
Wrong version here?
```suggestion
    cg.add_library("fastled/FastLED", "3.6.0")
```

2023-11-13 00:18 UTC, jesserockz commented on esphome/components/fastled/light.py
> +        config[CONF_DATA_PIN] = config[CONF_PIN]
Don't alter the config in `to_code`

2023-11-13 00:18 UTC, jesserockz commented on esphome/components/fastled/light.py
> +            cv.Optional(CONF_PIN): pins.internal_gpio_output_pin_number,
I understand that you are adding both of these so people can move from _clockless or _spi, but just choose one and stick to it, otherwise it will create confusing examples online.

2023-11-13 00:18 UTC, jesserockz commented on esphome/components/fastled/light.py
> +SPIChipsets = [
```suggestion
SPI_CHIPSETS = [
```

2023-11-13 00:18 UTC, jesserockz commented on esphome/components/fastled/light.py
> +CHIPSETS = [
Instead of duplicating the SPI chipsets in another list, create a `CLOCKLESS_CHIPSETS` and then combine them together for the validation
```py
CHIPSETS = CLOCKLESS_CHIPSETS + SPI_CHIPSETS
```

2023-11-13 00:18 UTC, jesserockz commented on esphome/components/fastled/light.py
> +    cv.has_exactly_one_key(CONF_DATA_PIN, CONF_PIN),
```suggestion
    cv.has_exactly_one_key(CONF_DATA_PIN, CONF_PIN),
    cv.only_on_arduino,
```

2023-11-15 15:32 UTC, nielsnl68 commented on esphome/components/fastled/light.py
> +            cv.Optional(CONF_PIN): pins.internal_gpio_output_pin_number,
i will remove the `CONF_PIN`. it makes sense

2023-11-15 15:36 UTC, nielsnl68 commented on esphome/components/fastled/light.py
> +    cv.has_exactly_one_key(CONF_DATA_PIN, CONF_PIN),
The `CONF_PIN` has been removed so we do not need the `cv.has_exactly_one_key(CONF_DATA_PIN, CONF_PIN),`

2023-11-15 17:19 UTC, jesserockz commented on esphome/components/fastled/light/__init__.py
> +            cv.Optional(CONF_PIN): cv.Invalid("This pin is renamed to 'data_pin'"),
When you raise an error, it's a capitalised `Invalid`, but in the schema, it's lower case `invalid`
```suggestion
            cv.Optional(CONF_PIN): cv.invalid("This pin is renamed to 'data_pin'"),
```

2023-11-15 17:53 UTC, nielsnl68 commented on esphome/components/fastled/light/__init__.py
> +            cv.Optional(CONF_PIN): cv.Invalid("This pin is renamed to 'data_pin'"),
then i copied the line from the wrong place. thanks for you note.

2023-12-14 04:58 UTC, jesserockz commented on esphome/components/fastled/light/__init__.py
> +).extend(cv.COMPONENT_SCHEMA)
What is the purpose of this is every field is redefined in the CONFIG_SCHEMA?

2024-01-09 00:29 UTC, nielsnl68 commented on esphome/components/fastled/light/__init__.py
> +).extend(cv.COMPONENT_SCHEMA)
Not sure what happened here. The BASE_SCHEMA is not needed anymore and now removed.

2024-04-29 02:09 UTC, bibach commented
@jesserockz @nielsnl68 Are there still requested changes outstanding for this issue, or have they been resolved?  Would be nice to see this get merged - along with the associated documentation PR.

2024-09-19 01:37 UTC, zackees commented
the register issue was fixed a while ago.

Are you still having an issue with this?

2024-09-19 15:51 UTC, nielsnl68 commented
This PR is very old, Not sure of it is worth to bring it back alive.

2024-09-19 15:54 UTC, nielsnl68 commented
I when i revive this PR i need minimal 10 x 👍🏼 including one from @jesserockz, @kbx81 or an other maintainer.

2025-05-05 20:19 UTC, nielsnl68 commented
To old to implement

2025-05-05 20:19 UTC, closed without merging