Add support for BLE passkey authentication
OttoWinter/esphomeyaml pull request #4258
Opened 2023-01-04 07:35 UTC by Mat931

# What does this implement/fix?

Allows pairing with BLE devices using a static passkey (PIN)
Tested with a [LYWSD03MMC](https://esphome.io/components/display/pvvx_mithermometer.html) running the [pvvx firmware](https://github.com/pvvx/ATC_MiThermometer) v3.8 and with a PIN code configured

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esphome:
  name: esp32-ble-client

esp32:
  board: esp32dev
  framework:
    type: arduino
    
wifi:
...

logger:
  baud_rate: 115200

time:
  - platform: homeassistant
    id: homeassistant_time

esp32_ble_tracker:
  io_capability: keyboard_only

ble_client:
- mac_address: "A4:C1:38:B1:CD:7F"
  id: pvvx_ble_display
  pin_code: 123456

display:
- platform: pvvx_mithermometer
  ble_client_id: pvvx_ble_display
  update_interval: 24h
  validity_period: 0s
  disconnect_delay: 30s
  time_id: homeassistant_time
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-01-21 11:30 UTC, ignisf commented
Paging @ammmze to take a look as well.

2023-01-21 15:43 UTC, ammmze approved these changes
This looks good to me! Thanks for doing this work!

2023-01-21 15:43 UTC, ammmze commented on esphome/components/esp32_ble_client/ble_client_base.cpp
> +      // esp_ble_confirm_reply(param->ble_security.ble_req.bd_addr, true);
Presumably we are commenting this out and logging not implemented because we just aren't able to test it presently? Perhaps a code comment explaining that would be good?

```suggestion
      // We probably want to something like this, however it has not yet been tested/verified.
      // esp_ble_confirm_reply(param->ble_security.ble_req.bd_addr, true);
```

2023-01-21 15:43 UTC, ammmze commented on esphome/components/esp32_ble_client/ble_client_base.cpp
> +      // esp_ble_oob_req_reply(param->ble_security.ble_req.bd_addr, tk, sizeof(tk));
Probably good to note the reason for the commented code here too.

```suggestion
      // We probably want to something like this, however it has not yet been tested/verified.
      // uint8_t tk[16] = {1}; // If you paired with OOB, both devices need to use the same tk
      // esp_ble_oob_req_reply(param->ble_security.ble_req.bd_addr, tk, sizeof(tk));
```

2023-01-21 16:53 UTC, syssi commented
Off-topic question: I would like to use this PR to authenticate a BLE connection with IO capabilities `display_only`. Is this supposed to work or is this feature limited to `keyboard_only`?

2023-01-21 16:58 UTC, Mat931 commented
@syssi
Yes, you should see the pin code in the ESPHome logs (Example: "ESP_GAP_BLE_PASSKEY_NOTIF_EVT: Passkey: 123456")
It's not tested yet because i don't have a BLE device that uses this authentication method.

2023-01-26 01:43 UTC, ignisf commented
@Mat931, since you added more options, I was wondering... Would it make sense to have an option to the ble client to not be automatically connected to upon discovery? This would make it possible polling sensors to initiate a connection in their `update` function when they need it?

This would also extend to the BLE proxy -- you would essentially have a list of addresses and their respective passkeys, and whenever the BLE proxy attempts a connection to a device, the passkey will be handled transparently to it.

2023-01-26 09:24 UTC, Mat931 commented
@ignisf
Yes, that would be very useful! You could make a new feature request

I need this functionality too and currently I'm stopping the scanner as a workaround to prevent all clients from connecting

2023-01-27 22:01 UTC, psychowood commented
I noticed the docs PR says "fixed 6 digits pin code". Does this mean that 4 digit pins are not supported?

2023-01-27 22:56 UTC, Mat931 commented
@psychowood
All codes up to 6 digits are supported :)
You can fill the missing digits with zero, 1234 would be 001234

2023-02-13 01:30 UTC, jesserockz commented on esphome/components/esp32_ble/ble.cpp
> +esp_ble_io_cap_t global_io_cap = ESP_IO_CAP_NONE;  // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
There is only ever a single instance of `ESP32BLE` so a global here is not required.

2023-02-17 18:32 UTC, Fabian-Schmidt commented
Hi,
Thanks for this awesome work.

I have two comments:

1. When I try using it with an incorrect passkey it crashes my ESP. Can you replicate this on you rend or this someting todo with my test setup. `io_capability: keyboard_only` and using action `ble_client.passkey_reply`.
2. Can you also add an action to unauthenticate a device (Method is `esp_ble_remove_bond_device`). This is very helpful for testing / validation.

Thank you

2023-02-19 08:47 UTC, Mat931 commented
@Fabian-Schmidt I can't replicate the crash. With an incorrect passkey I get:
```
[09:39:04][E][esp32_ble_client:263]: [0] [A4:C1:38:XX:XX:XX] auth fail reason = 0x51
```
Can you set the log level to VERY_VERBOSE and send me your config and logs?

2023-02-19 10:37 UTC, Fabian-Schmidt commented
Hi @Mat931 ,

The error occurs a moment later.

After the failed auth I receive a call to my class `victron_ble` (child of `ble_client::BLEClientNode`) method `gattc_event_handler` with `BLEClientNode=ESP_GATTC_READ_CHAR_EVT` log output at `victron_ble:136`. Afterwards I return from my method and the ESP crashes without any log output.

This is the full output. Afterwards I see the reboot log. As this happens right at the start the ESP restarts every ~5-10 seconds.

The full component code is at <https://github.com/Fabian-Schmidt/esphome-victron_ble>

```txt
[11:17:27][V][esp32_ble_client:260]: [0] [F6:42:55:CE:6B:16] auth complete. remote BD_ADDR: f64255ce6b16
[11:17:28][E][esp32_ble_client:263]: [0] [F6:42:55:CE:6B:16] auth fail reason = 0x51
[11:17:28][V][esp32_ble:205]: (BLE) gattc_event [esp_gatt_if: 4] - 3
[11:17:28][V][esp32_ble_client:111]: [0] [F6:42:55:CE:6B:16] gattc_event_handler: event=3 gattc_if=4
[11:17:28][W][victron_ble:136]: [F6:42:55:CE:6B:16] Error reading char at handle 46, status=137
[11:17:28]Guru Meditation Error: Core  0 panic'ed (Unhandled debug exception).
[11:17:28]Debug exception reason: Stack canary watchpoint triggered (BTU_TASK)
[11:17:28]Core  0 register dump:
[11:17:28]PC      : 0x40090aba  PS      : 0x00060a36  A0      : 0x8014625d  A1      : 0x3ffd8f30
WARNING Decoded 0x40090aba: memset at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/machine/xtensa/memset.S:153
[11:17:28]A2      : 0x3ffd8f44  A3      : 0x00000000  A4      : 0x00000268  A5      : 0x3ffd8f74
[11:17:28]A6      : 0x00000000  A7      : 0x00000026  A8      : 0x800988f4  A9      : 0x3ffd9190
[11:17:28]A10     : 0x3ffdc034  A11     : 0x00000000  A12     : 0x3ffef3a8  A13     : 0x3fff55d4
[11:17:28]A14     : 0x00000006  A15     : 0x3ffb6c68  SAR     : 0x00000017  EXCCAUSE: 0x00000001
[11:17:28]EXCVADDR: 0x00000000  LBEG    : 0x40090ab4  LEND    : 0x40090abf  LCOUNT  : 0x00000022
[11:17:28]
[11:17:28]
[11:17:28]Backtrace:0x40090ab7:0x3ffd8f300x4014625a:0x3ffd8f40 0x4017e730:0x3ffd91d0 0x40145c16:0x3ffd9210 0x4017d990:0x3ffd9230 0x4017e773:0x3ffd9250 0x40145c16:0x3ffd9290 0x4017d990:0x3ffd92b0 0x4017e773:0x3ffd92d0 0x40145c16:0x3ffd9310 0x4017d990:0x3ffd9330 0x4017e773:0x3ffd9350 0x40145c16:0x3ffd9390 0x4017d990:0x3ffd93b0 0x4017e773:0x3ffd93d0 0x40145c16:0x3ffd9410 0x4017d990:0x3ffd9430 0x4017e773:0x3ffd9450 0x40145c16:0x3ffd9490 0x4017d990:0x3ffd94b0 0x4017e773:0x3ffd94d0 0x40145c16:0x3ffd9510 0x4017d990:0x3ffd9530 0x4017e773:0x3ffd9550 0x40145c16:0x3ffd9590 0x4017d990:0x3ffd95b0 0x4017e773:0x3ffd95d0 0x40145c16:0x3ffd9610 0x4017d990:0x3ffd9630 0x4017e773:0x3ffd9650 0x40145c16:0x3ffd9690 0x4017d990:0x3ffd96b0 0x4017e773:0x3ffd96d0 0x40145c16:0x3ffd9710 0x4017d990:0x3ffd9730 0x4017e773:0x3ffd9750 0x40145c16:0x3ffd9790 0x4017d990:0x3ffd97b0 0x4017e773:0x3ffd97d0 0x40145c16:0x3ffd9810 0x4017d990:0x3ffd9830 0x4017e773:0x3ffd9850 0x40145c16:0x3ffd9890 0x4017d990:0x3ffd98b0 0x4017e773:0x3ffd98d0 0x40145c16:0x3ffd9910 0x4017d990:0x3ffd9930 0x4017e773:0x3ffd9950 0x40145c16:0x3ffd9990 0x4017d990:0x3ffd99b0 0x4017e773:0x3ffd99d0 0x40145c16:0x3ffd9a10 0x4017d990:0x3ffd9a30 0x4017e773:0x3ffd9a50 0x40145c16:0x3ffd9a90 0x4017d990:0x3ffd9ab0 0x4017e773:0x3ffd9ad0 0x40145c16:0x3ffd9b10 0x4017d990:0x3ffd9b30 0x4017e773:0x3ffd9b50 0x40145c16:0x3ffd9b90 0x4017d990:0x3ffd9bb0 0x4017e773:0x3ffd9bd0 0x40145c16:0x3ffd9c10 0x4017d990:0x3ffd9c30 0x4017e773:0x3ffd9c50 0x40145c16:0x3ffd9c90 0x4017d990:0x3ffd9cb0 0x4017e773:0x3ffd9cd0 0x40145c16:0x3ffd9d10 0x4017d990:0x3ffd9d30 0x4017e773:0x3ffd9d50 0x40145c16:0x3ffd9d90 0x4017d990:0x3ffd9db0 0x4017e773:0x3ffd9dd0 0x40145c16:0x3ffd9e10 0x4017d990:0x3ffd9e30 0x4017e773:0x3ffd9e50 0x40145c16:0x3ffd9e90 0x4017d990:0x3ffd9eb0 0x4017e773:0x3ffd9ed0 0x40145c16:0x3ffd9f10 0x4017d990:0x3ffd9f30 0x4017e773:0x3ffd9f50 0x40145c16:0x3ffd9f90 0x4017d990:0x3ffd9fb0 0x4017e773:0x3ffd9fd0 0x40145c16:0x3ffda010 0x4017d990:0x3ffda030 0x4017e773:0x3ffda050 0x40145c16:0x3ffda090 0x4017d990:0x3ffda0b0 0x4017e773:0x3ffda0d0 0x40145c16:0x3ffda110 0x4017d990:0x3ffda130 0x4017e773:0x3ffda150 0x40145c16:0x3ffda190 0x4017d990:0x3ffda1b0 0x4017e773:0x3ffda1d0 0x40145c16:0x3ffda210 0x4017d990:0x3ffda230  |<-CONTINUES
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x40090ab7: memset at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/machine/xtensa/memset.S:151
WARNING Decoded 0x4014625a: bta_gattc_enqueue at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_utils.c:464
WARNING Decoded 0x4017e730: bta_gattc_read at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1098
WARNING Decoded 0x40145c16: bta_gattc_sm_execute at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_main.c:298
WARNING Decoded 0x4017d990: bta_gattc_pop_command_to_send at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1576
WARNING Decoded 0x4017e773: bta_gattc_read at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1114
WARNING Decoded 0x40145c16: bta_gattc_sm_execute at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_main.c:298
WARNING Decoded 0x4017d990: bta_gattc_pop_command_to_send at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1576
WARNING Decoded 0x4017e773: bta_gattc_read at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1114
WARNING Decoded 0x40145c16: bta_gattc_sm_execute at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_main.c:298
WARNING Decoded 0x4017d990: bta_gattc_pop_command_to_send at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1576
WARNING Decoded 0x4017e773: bta_gattc_read at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1114
WARNING Decoded 0x40145c16: bta_gattc_sm_execute at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_main.c:298
WARNING Decoded 0x4017d990: bta_gattc_pop_command_to_send at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1576
WARNING Decoded 0x4017e773: bta_gattc_read at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1114
WARNING Decoded 0x40145c16: bta_gattc_sm_execute at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_main.c:298
WARNING Decoded 0x4017d990: bta_gattc_pop_command_to_send at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1576
WARNING Decoded 0x4017e773: bta_gattc_read at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1114
WARNING Decoded 0x40145c16: bta_gattc_sm_execute at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_main.c:298
WARNING Decoded 0x4017d990: bta_gattc_pop_command_to_send at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1576
WARNING Decoded 0x4017e773: bta_gattc_read at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_act.c:1114
WARNING Decoded 0x40145c16: bta_gattc_sm_execute at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/gatt/bta_gattc_main.c:298
WARNING Decoded 0x4017d990: bta_gattc_pop_command_to_send at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/bt/host/bluedroid/bta/g [...]

2023-02-19 11:25 UTC, Mat931 commented
Looks like a bug in esp-idf
https://github.com/espressif/esp-idf/issues/5371

2023-02-19 12:08 UTC, Fabian-Schmidt commented
Thanks.

So the fix is to only issue a single `esp_ble_gattc_read_char` request during `ESP_GATTC_SEARCH_CMPL_EVT` event. Then wait for the `ESP_GATTC_READ_CHAR_EVT` return back and issue the next read event only afterwards.

I looked at the other ble components and I think most issue all read commands during the search complete and will therefore fail when auth is necessary.

2023-04-02 23:40 UTC, jesserockz requested changes

2023-04-02 23:40 UTC, jesserockz commented on esphome/components/esp32_ble_client/ble_client_base.cpp
> +    return;
This wont work if we extend this handler later as `param` is a union depending on the event type.

Also both the events below are already doing this address check so its not needed here..

2023-04-03 06:17 UTC, Mat931 commented on esphome/components/esp32_ble_client/ble_client_base.cpp
> +    return;
Thanks!

2023-05-01 05:26 UTC, jesserockz approved these changes

2023-05-01 21:25 UTC, merged