Add Clipping to displaybuffer
OttoWinter/esphomeyaml pull request #4271
Opened 2023-01-07 09:54 UTC by nielsnl68

# What does this implement/fix?

This per extends the displaybuffer with the option to clip parts of the screen where the changes are allowed.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  - platform: ili9341
    model: TFT 2.4
    cs_pin: 14
    dc_pin: 27
    led_pin: 32  
    reset_pin: 33

    lambda: |-
      it.print(20, 20, id(my_red), id(my_red), TextAlign::TOP_LEFT, "Hello World!");
      it.push_clipping(30, 25, 100, 40);
      it.print(20, 20, id(my_red), id(my_blue), TextAlign::TOP_LEFT, "Hello World!");
      it.pop_clipping();

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-07 19:03 UTC, jesserockz requested changes

2023-02-07 19:03 UTC, jesserockz commented on esphome/components/display/display_buffer.cpp
> +  // ESP_LOGW(TAG, "set: Push new clipping");
```suggestion
```

2023-02-07 19:03 UTC, jesserockz commented on esphome/components/display/display_buffer.cpp
> +    // ESP_LOGW(TAG, "add: join new clipping");
```suggestion
```

2023-02-07 19:03 UTC, jesserockz commented on esphome/components/display/display_buffer.h
> +  ///
???

2023-02-07 19:03 UTC, jesserockz commented on esphome/components/display/display_buffer.h
> +      ESP_LOGI("Rect", "%s [%3d,%3d,%3d,%3d]", prefix.c_str(), this->x, this->y, this->w, this->h);
Log calls need to be in the cpp file

2023-02-07 19:03 UTC, jesserockz commented on esphome/components/display/display_buffer.h
> +#include "esphome/core/log.h"
This needs to go in the cpp file

2023-02-07 22:06 UTC, nielsnl68 commented on esphome/components/display/display_buffer.cpp
> +  // ESP_LOGW(TAG, "set: Push new clipping");
I have moved the function code to the cpp file now.

2023-02-07 22:07 UTC, nielsnl68 commented on esphome/components/display/display_buffer.h
> +  ///
thanks, i have removed it

2023-02-07 22:07 UTC, nielsnl68 commented on esphome/components/display/display_buffer.h
> +      ESP_LOGI("Rect", "%s [%3d,%3d,%3d,%3d]", prefix.c_str(), this->x, this->y, this->w, this->h);
I moved the functions now to the cpp file

2023-02-07 22:08 UTC, nielsnl68 commented on esphome/components/display/display_buffer.h
> +#include "esphome/core/log.h"
done

2023-02-08 01:28 UTC, jesserockz approved these changes

2023-02-10 20:55 UTC, jesserockz approved these changes

2023-02-10 20:56 UTC, merged