Add support for hy271
OttoWinter/esphomeyaml pull request #4282
Opened 2023-01-10 13:05 UTC by Philippe12

# What does this implement/fix?

Add new driver for HY271

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true
  id: bus_a
  frequency: 200000

sensor:
  - platform: hyt271
    id: sonde
    temperature:
      name: "Temperature"
      id: temp_etuve
    humidity:
      name: "Humidity"        

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-01-11 00:46 UTC, jesserockz requested changes

2023-01-11 00:46 UTC, jesserockz commented on esphome/components/hyt271/hyt271.cpp
> +}
No need for a setup that just delays
```suggestion
```

2023-01-11 00:46 UTC, jesserockz commented on esphome/components/hyt271/hyt271.h
> +  void setup() override;
```suggestion
```

2023-01-11 00:46 UTC, jesserockz commented on esphome/components/hyt271/hyt271.cpp
> +  }
This is never marked as failed
```suggestion
```

2023-01-11 00:46 UTC, jesserockz commented on esphome/components/hyt271/hyt271.cpp
> +  if (this->read(reinterpret_cast<uint8_t *>(&raw_data), 4) != i2c::ERROR_OK) {
```suggestion
  if (this->read(raw_data, 4) != i2c::ERROR_OK) {
```

2023-01-11 07:22 UTC, Philippe12 commented on esphome/components/hyt271/hyt271.cpp
> +  }
Yes it is error in dump config

2023-02-09 02:30 UTC, jesserockz requested changes

2023-02-09 02:30 UTC, jesserockz commented on esphome/components/hyt271/hyt271.cpp
> +  delay(50);  // NOLINT
Why does this need a delay every update?

If it does need a delay, look at using `set_timeout` to wrap the below code into a callback function to put onto the ESPHome scheduler and execute ~50ms in the future instead of blocking the whole application loop.

2023-04-24 10:33 UTC, Philippe12 commented on esphome/components/hyt271/hyt271.cpp
> +  delay(50);  // NOLINT
It changed no more waiting on to main loop. I add liké you say a timeout

2023-05-01 04:17 UTC, jesserockz approved these changes

2023-05-01 04:18 UTC, merged