Add cpu_temperature component
OttoWinter/esphomeyaml pull request #4330
Opened 2023-01-21 15:43 UTC by Mat931

# What does this implement/fix?

A sensor for the internal CPU temperature (ESP32, RP2040)

Note: The original ESP32 returns many invalid temperature readings. (raw value 128, calculated temperature would be 53.3°C) This component ignores the invalid readings. (see https://github.com/arendst/Tasmota/discussions/13026)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/744

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

Please help me test this on the ESP32S2, ESP32S3, ESP32C3 and RP2040. I only have ESP32 devices!

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [X] RP2040

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: cpu_temperature
    name: "CPU Temperature"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-01-21 16:22 UTC, Mat931 commented
![1](https://user-images.githubusercontent.com/49403702/213876341-f0b4473d-1d5d-47ad-bc60-52854d46bccb.png)
![2](https://user-images.githubusercontent.com/49403702/213876347-d32c0d0c-987e-4a5b-9665-28529720d4af.png)
![3](https://user-images.githubusercontent.com/49403702/213876348-5cf6cf0b-b127-4d71-baaa-c770322ba3a3.png)

2023-01-22 18:14 UTC, SeByDocKy commented
I tested your PR. In the log I got the temperature but nothing is sent to HA...

2023-01-22 18:20 UTC, nagyrobi commented
Not sure if "cpu" is the correct term to use in this case. These are microcontrollers, not microprocessors...
Perhaps something like "internal_temperature" would be a better match.

2023-01-22 21:12 UTC, Mat931 commented
@SeByDocKy Thanks for testing! That's interesting, the same thing happened to me when installing it for the first time on an ESP32 with no other components.

- What microcontroller are you using?
- Can you try rebooting the ESP / RP2040 or reuploading the firmware?
- Did you specify a name for the sensor?

@nagyrobi Yeah, internal_temperature would fit better. I'll rename the component tomorrow.

2023-01-23 07:36 UTC, SeByDocKy commented
> @SeByDocKy Thanks for testing! That's interesting, the same thing happened to me when installing it for the first time on an ESP32 with no other components.
> 
> * What microcontroller are you using?
> * Can you try rebooting the ESP / RP2040 or reuploading the firmware?
> * Did you specify a name for the sensor?
> 
> @nagyrobi Yeah, internal_temperature would fit better. I'll rename the component tomorrow.

Strange now the entity is available.... Maybe after a reboot


i) ESP32 WROOM32
```
esp32:
  board: esp32dev
  framework:
    type: arduino
    version: 2.0.6   #2.0.5
    platform_version: 5.3.0 #5.2.0
    # type: esp-idf
    
external_components:
  - source: github://pr#4330
    components: [cpu_temperature]
    refresh: 0s
```



iii) 

```
- platform: cpu_temperature
    name: ${prefix}_cpu_temperature
    update_interval: 10s
```


Often in the logs, got ignoring temperature as depicted below, but I guess it's normal.

![image](https://user-images.githubusercontent.com/6464595/213986864-9097a25d-81e5-4bca-9f55-5f48f1fb70fd.png)


Btw, I don't why during 1h, the new entity didn't update (I tried to delete and add again the ESPhome node without success)

2023-01-23 10:12 UTC, Mat931 commented
@SeByDocKy I think the problem was that the sensor didn't have a value yet when connecting to HA. Now the temperature is set to NAN / Unknown if the first measurement after booting the ESP is invalid. Hope that fixes the issue :)

2023-01-23 11:42 UTC, SeByDocKy commented
Work fine for me :)

2023-01-26 22:20 UTC, eavyon commented
I can confirm it works on board lolin_c3_mini > esp32c3
Doesnt work on board nodemcu-32s(az delivery wroom32) > esp32 gives only invalid values
Both arduino framework

2023-01-26 22:32 UTC, Mat931 commented
@eavyon
Thanks for testing!
On the ESP32 there can be many invalid values in a row, that doesn't mean it isn't working at all. Sometimes rebooting the ESP helps. If there's still no valid measurement after multiple hours it's probably broken.
Can you tell me the chip version from esptool.py or from the logs when uploading via serial?

Mine (confirmed working) are:

- ESP32-D0WDQ6 (revision v0.0)
- ESP32-D0WDQ6 (revision v1.0)
- ESP32-U4WDH (Shelly Plus 1PM, don't know the revision)

2023-01-30 18:30 UTC, eavyon commented
@Mat931 I checked again after restarting and it is now reporting last few days. 
Revision ESP32-D0WDQ6 (revision 1)
![image](https://user-images.githubusercontent.com/84970882/215561427-016ce9a1-1371-4b91-9dd0-6ae19669d5fb.png)

2023-01-30 18:34 UTC, Mat931 commented
@eavyon Nice, thanks! Would be great if you could also test it with esp-idf on your ESP32C3 :)

2023-02-09 22:08 UTC, eavyon commented
@Mat931 I flashed with esp-idf and can confirm it also works normally last few hours on ESP32C3.

2023-02-19 14:14 UTC, oxan requested changes

2023-02-19 14:14 UTC, oxan commented on esphome/components/internal_temperature/internal_temperature.cpp
> +
No need for the `#ifdef __cplusplus` as this is a `.cpp` file and will thus always compile as C++, and we prefer our own `USE_ESP32_VARIANT_*` macros over those from the IDF (also change this below please). I also added a comment to note why we define the prototype here manually.
```suggestion
#ifdef USE_ESP32
#ifdef USE_ESP32_VARIANT_ESP32
// there is no official API available on the original ESP32
extern "C" {
uint8_t temprature_sens_read();
}
#else  // USE_ESP32_VARIANT_ESP32
#include "driver/temp_sensor.h"
#endif  // USE_ESP32_VARIANT_ESP32
#endif  // USE_ESP32
```

2023-02-19 14:14 UTC, oxan commented on esphome/components/internal_temperature/internal_temperature.cpp
> +    ESP_LOGD(TAG, "Got temperature: %.1f°C", temperature);
```suggestion
```
This log statement is superfluous as `this->publish_state` will already log the published value.

2023-02-19 14:14 UTC, oxan commented on esphome/components/internal_temperature/internal_temperature.h
> +  std::string unique_id() override;
This override isn't necessary nor desired for new components.

2023-02-19 14:14 UTC, oxan commented on esphome/components/internal_temperature/internal_temperature.cpp
> +#include "esphome/core/hal.h"
Doesn't seem to be used:
```suggestion
```

2023-02-19 18:05 UTC, oxan approved these changes

2023-02-20 02:47 UTC, merged