Add support for AS7341 spectral color sensor
OttoWinter/esphomeyaml pull request #4331
Opened 2023-01-21 16:18 UTC by mrgnr

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2609

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-09 02:26 UTC, jesserockz requested changes

2023-02-09 02:26 UTC, jesserockz commented on esphome/components/as7341/sensor.py
> +    )
No need to wrap in a function
```suggestion
SENSOR_SCHEMA = sensor.sensor_schema(
    unit_of_measurement=UNIT_COUNTS,
    icon=ICON_BRIGHTNESS_5,
    accuracy_decimals=0,
    device_class=DEVICE_CLASS_ILLUMINANCE,
    state_class=STATE_CLASS_MEASUREMENT,
)
```

2023-02-09 02:26 UTC, jesserockz commented on esphome/components/as7341/sensor.py
> +            cv.Optional(CONF_NIR): sensor_schema(),
```suggestion
            cv.Optional(CONF_F1): SENSOR_SCHEMA,
            cv.Optional(CONF_F2): SENSOR_SCHEMA,
            cv.Optional(CONF_F3): SENSOR_SCHEMA,
            cv.Optional(CONF_F4): SENSOR_SCHEMA,
            cv.Optional(CONF_F5): SENSOR_SCHEMA,
            cv.Optional(CONF_F6): SENSOR_SCHEMA,
            cv.Optional(CONF_F7): SENSOR_SCHEMA,
            cv.Optional(CONF_F8): SENSOR_SCHEMA,
            cv.Optional(CONF_CLEAR): SENSOR_SCHEMA,
            cv.Optional(CONF_NIR): SENSOR_SCHEMA,
```

2023-02-09 02:26 UTC, jesserockz commented on esphome/components/as7341/as7341.h
> +using as7341_gain_t = enum {
Should be using this format to match the rest of ESPHome codebase =)
Same for the above enums
```suggestion
enum AS7341Gain {
```

2023-02-12 16:37 UTC, mrgnr commented
Thanks for the review @jesserockz, I've made the requested changes and tested the sensor locally.

2023-03-04 07:42 UTC, jupe commented
Thanks for component. Could you give home-assistant view config example here as well?

2023-03-06 07:01 UTC, jesserockz requested changes

2023-03-06 07:01 UTC, jesserockz commented on esphome/components/as7341/as7341.cpp
> +  read_channels(this->channel_readings_);
Consistency is key =)
```suggestion
  this->read_channels(this->channel_readings_);
```

2023-03-06 07:01 UTC, jesserockz commented on esphome/components/as7341/as7341.h
> +  void set_f1_sensor(sensor::Sensor *f1_sensor) { f1_ = f1_sensor; }
```suggestion
  void set_f1_sensor(sensor::Sensor *f1_sensor) { this->f1_ = f1_sensor; }
```

2023-03-08 01:07 UTC, jesserockz approved these changes

2023-03-08 01:24 UTC, merged