2080 mopeka std
OttoWinter/esphomeyaml pull request #4351
Opened 2023-01-26 09:58 UTC by Fabian-Schmidt

# What does this implement/fix?

Add support for Mopeka Standard Check LP BLE sensor and update generic component that helps find the BLE MAC address.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <https://github.com/esphome/feature-requests/issues/2080>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
    esp32_ble_tracker:
    
    sensor:
      # Example using 11kg 100% propane tank.
      - platform: mopeka_std_check
        mac_address: D3:75:F2:DC:16:91
        tank_type: Europe_11kg
        temperature:
            name: "Propane test temp"
        level:
            name: "Propane test level"
        distance:
            name: "Propane test distance"
        battery_level:
            name: "Propane test battery level"
    
      # Custom example - user defined empty / full points and 80% butane and 20% propane.
      - platform: mopeka_std_check
        mac_address: D3:75:F2:DC:16:91
        tank_type: CUSTOM
        custom_distance_full: 40cm
        custom_distance_empty: 32mm
        propane_butane_mix: 0.2
        temperature:
            name: "Propane c test temp"
        level:
            name: "Propane c test level"
        distance:
            name: "Propane c test distance"
        battery_level:
            name: "Propane c test battery level"

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-01-28 21:39 UTC, spbrogan commented on esphome/components/mopeka_ble/mopeka_ble.cpp
> +  if (service_uuid == esp32_ble_tracker::ESPBTUUID::from_uint16(SERVICE_UUID_CC2540)) {
I know in many oss projects it isn't common to see comments and to be honest I am listed as code owner not because I am involved in the project but just because i submitted the integration.  But i would prefer to see a bunch more comments to make this much easier to read and grok quickly.  

Comments indicating what sensor each conditional is for etc.

2023-01-28 21:39 UTC, spbrogan commented on esphome/components/mopeka_ble/mopeka_ble.cpp
> +static const uint16_t SERVICE_UUID_CC2540 = 0xADA0;
I would prefer these are ordered by sensor...so the 3 parts for each sensor are together and then a comment can be made about each sensor and it's info.

2023-01-28 21:39 UTC, spbrogan commented on esphome/components/mopeka_std_check/sensor.py
> +            cv.Optional(CONF_PROPANE_BUTANE_MIX, default=1.0): cv.float_range(0, 1),
is the propane/butane mix feature new?  Should we try to keep capabilities the same between pro check and std device?

2023-01-28 21:51 UTC, spbrogan commented on esphome/components/mopeka_std_check/sensor.py
> +    "EUROPE_6KG": (38, 336),
should this be added to pro check or maybe even do the python sensor code with "common" code?

2023-01-29 15:45 UTC, Fabian-Schmidt commented on esphome/components/mopeka_ble/mopeka_ble.cpp
> +  if (service_uuid == esp32_ble_tracker::ESPBTUUID::from_uint16(SERVICE_UUID_CC2540)) {
Okay added some comments.

2023-01-29 15:45 UTC, Fabian-Schmidt commented on esphome/components/mopeka_ble/mopeka_ble.cpp
> +static const uint16_t SERVICE_UUID_CC2540 = 0xADA0;
Done

2023-01-29 15:46 UTC, Fabian-Schmidt commented on esphome/components/mopeka_ble/mopeka_ble.cpp
> +static const uint16_t SERVICE_UUID_CC2540 = 0xADA0;
Done

2023-01-29 15:55 UTC, Fabian-Schmidt commented on esphome/components/mopeka_std_check/sensor.py
> +            cv.Optional(CONF_PROPANE_BUTANE_MIX, default=1.0): cv.float_range(0, 1),
What do you mean with new feature? 

It is a common thing. In Europe I can purchase 100% Butane or 100% Propane tanks and depending on the season also mixes (Winter mix or Summer mix). Because pure Butane boils around 0C and is therefore unusable below this temperature.

The Mopeka app on my phone also has a slider so I can configure the mixture. If I don't configure it accordingly my measurements are incorrect.

2023-01-29 15:58 UTC, Fabian-Schmidt commented on esphome/components/mopeka_std_check/sensor.py
> +    "EUROPE_6KG": (38, 336),
I think it is best to keep it KISS and separate both sensors.
The list is static and will not change often. Even if we add the ~100 different types of tanks present in the app it is only once done.

2023-02-20 22:42 UTC, jesserockz commented on esphome/components/mopeka_std_check/sensor.py
> +            cv.Optional(CONF_PROPANE_BUTANE_MIX, default="100%"): cv.percentage,
Since you log this as `LPG Butane ratio: %.0f%%"`, it really should be `CONF_LPG_BUTANE_RATIO` in config to match

2023-02-20 22:44 UTC, jesserockz requested changes

2023-02-20 22:44 UTC, jesserockz commented on esphome/components/mopeka_std_check/mopeka_std_check.h
> +  void set_tank_empty(float empty) { empty_mm_ = empty; };
These should all have `this->` prefixes please

2023-02-21 09:47 UTC, Fabian-Schmidt commented on esphome/components/mopeka_std_check/sensor.py
> +            cv.Optional(CONF_PROPANE_BUTANE_MIX, default="100%"): cv.percentage,
Thanks. I have adjusted the Cpp and output. I like `Propane Butane mix` better as I find it is easier to understand.

2023-02-21 21:44 UTC, jesserockz approved these changes

2023-02-21 21:48 UTC, merged