SCD30 Added support for manual calibration
OttoWinter/esphomeyaml pull request #4362
Opened 2023-01-29 12:44 UTC by ftrueck

# What does this implement/fix?

Added support to calibrate the SCD30 sensor to a known CO2 value. The calibration is adapted immediately.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] RP2040

## Example entry for `config.yaml`:
```yaml
button:
  - platform: template
    name: "SCD30 Force manual calibration"
    entity_category: "config"
    on_press:
      then:
        - scd30.force_recalibration_with_reference:
            value: !lambda 'return id(co2_cal).state;'

number:
  - platform: template
    name: "CO2 calibration value"
    optimistic: true
    min_value: 350
    max_value: 4500
    step: 1
    id: co2_cal
    icon: "mdi:molecule-co2"
    entity_category: "config"

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-01-29 14:09 UTC, ftrueck commented
The PR for documentation can be found here:
https://github.com/esphome/esphome-docs/pull/2631

2023-02-02 19:08 UTC, jesserockz requested changes

2023-02-02 19:08 UTC, jesserockz commented on esphome/components/scd30/sensor.py
> +    maybe_simple_id(
Since there is a required `CONF_VALUE` this will never just be a simple id. But it could be a `cv.maybe_simple_value` with `key=CONF_VALUE`

2023-02-02 20:30 UTC, jesserockz approved these changes

2023-02-03 08:13 UTC, merged