add MQTT preset support for Climate components
OttoWinter/esphomeyaml pull request #4379
Opened 2023-02-02 16:19 UTC by jmichiel

# What does this implement/fix?

The current preset state and changing presets through MQTT was still lacking.
ClimateTraits::get_supports_presets() was also updated to be in line with ClimateTraits::get_supports_fan_modes() behaviour.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation:** esphome/esphome-docs#2641

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

Tested with a dummy custom climate: discovery is correct, state changes are published and commands forwarded.

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-02 18:59 UTC, jesserockz requested changes

2023-02-02 18:59 UTC, jesserockz commented on esphome/components/mqtt/mqtt_climate.cpp
> +  if (traits.get_supports_presets() || !traits.get_supported_custom_presets().empty()) {
You added this check inside `get_supports_presets()`
```suggestion
  if (traits.get_supports_presets()) {
```

2023-02-06 23:13 UTC, jesserockz requested changes

2023-02-06 23:13 UTC, jesserockz commented on esphome/components/climate/climate_traits.h
> +  bool get_supports_presets() const { return !supported_presets_.empty() || !supported_custom_presets_.empty(); }
Just had a quick browse through the code and this change might break existing usages where it is also checking for custom in a different conditional

2023-02-07 08:35 UTC, jmichiel commented on esphome/components/climate/climate_traits.h
> +  bool get_supports_presets() const { return !supported_presets_.empty() || !supported_custom_presets_.empty(); }
I feared as much and perhaps that's why it wasn't aligned with get_supports_fan_modes?

2023-02-07 14:53 UTC, jmichiel commented on esphome/components/climate/climate_traits.h
> +  bool get_supports_presets() const { return !supported_presets_.empty() || !supported_custom_presets_.empty(); }
I reverted the changes

2023-02-08 23:34 UTC, jesserockz approved these changes

2023-02-08 23:46 UTC, merged