Add configurable color datapoint
OttoWinter/esphomeyaml pull request #4383
Opened 2023-02-03 06:54 UTC by irtimaled

# What does this implement/fix?

I recently discovered a new color scheme used by some TuyaMCUs, a 15 character RGBHSV. Instead of making a third dp_id and complicating all the logic that is already there for rgb_datapoint and hsv_datapoint, this PR deprecates those old ones and switches to a new color_datapoint & color_type config value. It simplifies a bunch of the code and allows support for the new devices.

This PR will cause existing configurations using rgb_datapoint or hsv_datapoint to break, and will require configurations to be changed to use color_datapoint & color_type.

Specification of Tuya's RGBHSV:-

red = 0-255 encoded as 2 digit hex
green = 0-255 encoded as 2 digit hex
blue = 0-255 encoded as 2 digit hex
hue = 0-360 encoded as 4 digit hex
saturation = 0-255 encoded as 2 digit hex
value = 0-255 encoded as 2 digit hex

If this approach is acceptable I will make the necessary changes to the docs project to match.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
light:
  - platform: tuya
    name: "${friendly_name}"
    switch_datapoint: 1
    color_datapoint: 2
    color_type: rgbhsv
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-09 05:00 UTC, jesserockz requested changes

2023-02-09 05:00 UTC, jesserockz commented on esphome/components/tuya/light/__init__.py
> +            cv.Optional(CONF_COLOR_TYPE, default="RGBHSV"): cv.enum(
This should not have a default, but should be `cv.Inclusive` with the `CONF_COLOR_DATAPOINT` to enforce the user to select a type when specifying `CONF_COLOR_TYPE`

2023-02-12 08:53 UTC, irtimaled commented on esphome/components/tuya/light/__init__.py
> +            cv.Optional(CONF_COLOR_TYPE, default="RGBHSV"): cv.enum(
@jesserockz like this? 
```
cv.Inclusive(CONF_COLOR_DATAPOINT, "color"): cv.uint8_t,
cv.Inclusive(CONF_COLOR_TYPE, "color"): cv.enum(
    COLOR_TYPES, upper=True
),
```

2023-02-12 08:54 UTC, irtimaled commented on esphome/components/tuya/light/__init__.py
> +            cv.Optional(CONF_COLOR_TYPE, default="RGBHSV"): cv.enum(
Wanted to make sure that's what you meant!

2023-02-13 02:14 UTC, jesserockz approved these changes

2023-02-19 21:51 UTC, merged