Update the delta filter to be able to take a percentage change
OttoWinter/esphomeyaml pull request #4391
Opened 2023-02-06 12:12 UTC by TrentHouliston

# What does this implement/fix?

Adds functionality to the delta filter so that it is able to check if a new value is a percentage of the old value different if you pass a percentage value.
It maintains the old functionality if you don't use a percentage as your configuration.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
Example of a percentage filter
```yaml
# Example config.yaml
sensor:
  - platform: ...
    filters:
      - delta: 1%
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-06 23:22 UTC, jesserockz requested changes

2023-02-06 23:22 UTC, jesserockz commented on esphome/components/sensor/__init__.py
> +    raise cv.Invalid("Delta filter requires a positive number or percentage value.")
This will not work as expected as `0.5` satisfies both `cv.positive_float` (0.5f) and `cv.percentage` (50%)

2023-02-07 02:39 UTC, TrentHouliston commented on esphome/components/sensor/__init__.py
> +    raise cv.Invalid("Delta filter requires a positive number or percentage value.")
But `0.5` should satisfy postive_float first and return as an absolute delta value so it will never even try the percentage.

Only if you put a `%` symbol on the end of the value will it fail to work in `positive_float` and throw and then try as a percentage.

2023-03-15 20:00 UTC, jesserockz approved these changes

2023-03-15 22:39 UTC, merged