Add support for MAX31850 1-wire thermocouple amp
OttoWinter/esphomeyaml pull request #4416
Opened 2023-02-12 01:07 UTC by lylavoie

# What does this implement/fix?

* Updated the Dallas driver to support the MAX31850 device.
* Overloads the DS1825 device id, MAX31850 device is enabled through yaml override.
* Throw ESS_LOGE errors for devices faults (short or open junction).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2663

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).
  - Refer to PR in esphome-docs

2023-02-21 01:09 UTC, Guncotton commented
Empirically validated function on ESP8266, two MAX31850 sensors on a NODEMCUv2 monitoring a fireplace. Thank you for the added functionality.

2023-02-26 22:41 UTC, jesserockz requested changes

2023-02-26 22:41 UTC, jesserockz commented on esphome/components/dallas/sensor.py
> +            cv.Optional(CONF_MAX31850, default=False): cv.boolean,
I don't know how many others there might be, but I would prefer a `model` enum approach here that defaults to `DS18XXX`

2023-02-27 14:57 UTC, lylavoie commented on esphome/components/dallas/sensor.py
> +            cv.Optional(CONF_MAX31850, default=False): cv.boolean,
I can that that approach, the other DS chips can be "auto," since the model ID in the onewire address / serial number isn't being overloaded yet.  Would you be ok with a model enum that include auto, along with the specific models, i.e. it can force something for a specific sensor?

2023-06-05 00:46 UTC, closed without merging