Ld2410
OttoWinter/esphomeyaml pull request #4434
Opened 2023-02-14 01:04 UTC by regevbr

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-15 12:31 UTC, regevbr commented
To test please use the following config in the **dev** version of esphome:

```yaml
external_components:
  source: github://regevbr/esphome@ld2410
  components: [ld2410, number, button, binary_sensor, text_sensor]
 
uart:
  id: uart1
  tx_pin: GPIO17 // Your pin
  rx_pin: GPIO16 // Your pin
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: uart1

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410
    timeout:
      name: timeout
    max_move_distance:
      name: max move distance
    max_still_distance:
      name: max still distance
    g0_move_threshold:
      name: g0 move threshold
    g0_still_threshold:
      name: g0 still threshold
    g1_move_threshold:
      name: g1 move threshold
    g1_still_threshold:
      name: g1 still threshold
    g2_move_threshold:
      name: g2 move threshold
    g2_still_threshold:
      name: g2 still threshold
    g3_move_threshold:
      name: g3 move threshold
    g3_still_threshold:
      name: g3 still threshold
    g4_move_threshold:
      name: g4 move threshold
    g4_still_threshold:
      name: g4 still threshold
    g5_move_threshold:
      name: g5 move threshold
    g5_still_threshold:
      name: g5 still threshold
    g6_move_threshold:
      name: g6 move threshold
    g6_still_threshold:
      name: g6 still threshold
    g7_move_threshold:
      name: g7 move threshold
    g7_still_threshold:
      name: g7 still threshold
    g8_move_threshold:
      name: g8 move threshold
    g8_still_threshold:
      name: g8 still threshold

text_sensor:
  - platform: ld2410
    version:
      name: "presenece sensor version" 

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode" 

binary_sensor:
  - platform: ld2410
    has_target:
      name: "presence"
    has_moving_target:
      name: "movement"
    has_still_target:
      name: "still"

sensor:
  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
    g0_move_energy:
      name: g0 move energy
    g0_still_energy:
      name: g0 still energy
    g1_move_energy:
      name: g1 move energy
    g1_still_energy:
      name: g1 still energy
    g2_move_energy:
      name: g2 move energy
    g2_still_energy:
      name: g2 still energy
    g3_move_energy:
      name: g3 move energy
    g3_still_energy:
      name: g3 still energy
    g4_move_energy:
      name: g4 move energy
    g4_still_energy:
      name: g4 still energy
    g5_move_energy:
      name: g5 move energy
    g5_still_energy:
      name: g5 still energy
    g6_move_energy:
      name: g6 move energy
    g6_still_energy:
      name: g6 still energy
    g7_move_energy:
      name: g7 move energy
    g7_still_energy:
      name: g7 still energy
    g8_move_energy:
      name: g8 move energy
    g8_still_energy:
      name: g8 still energy
```

2023-02-15 12:40 UTC, regevbr commented
@sebcaps this currently works with some quirks that I still need to figure out (mainly some race conditions) 
Can you please review the changes and test it out and give me some input?

2023-02-16 00:30 UTC, jesserockz requested changes
Please split out the changes to the top level components (binary_sensor/button/number etc) into their own individual PRs.

2023-02-16 08:55 UTC, regevbr commented
> Please split out the changes to the top level components (binary_sensor/button/number etc) into their own individual PRs.

https://github.com/esphome/esphome/pull/4447
https://github.com/esphome/esphome/pull/4448
https://github.com/esphome/esphome/pull/4449
https://github.com/esphome/esphome/pull/4450

2023-02-17 18:59 UTC, regevbr commented
@jesserockz @sebcaps @TheOfficialMrBlah this PR is finally ready with docs and a green CI would appreciate your feedback :-)

![Peek 2023-02-17 20-55](https://user-images.githubusercontent.com/5775519/219760157-696868c4-9fd2-462c-a193-3578ec3e54e7.gif)

2023-02-19 17:39 UTC, sebcaps commented
Hi @regevbr many, thanks for the hard work having a look, but without test ;-) sounds good to me.
Anyway I'll give a try for usage and confirm if everything is OK in my side.
In the meantime, I added some 'minor' comments on doc.

2023-02-19 20:24 UTC, regevbr commented
> Hi @regevbr many, thanks for the hard work having a look, but without test ;-) sounds good to me. Anyway I'll give a try for usage and confirm if everything is OK in my side. In the meantime, I added some 'minor' comments on doc.

Great thanks! Notice that you must be on latest dev branch of esphome to test out!

2023-02-19 22:55 UTC, jesserockz requested changes

2023-02-19 22:55 UTC, jesserockz commented on esphome/components/ld2410/ld2410.h
> +    delay(1000);  // NOLINT
There is a reason for the lint rule to disallow long delays.

Please use `set_timeout` to execute code in the future

2023-02-20 07:02 UTC, regevbr commented on esphome/components/ld2410/ld2410.h
> +    delay(1000);  // NOLINT
done

2023-02-20 08:31 UTC, regevbr commented
Added in the latest [docs](https://deploy-preview-2680--esphome.netlify.app/components/sensor/ld2410) also a very cool custom HA card for easy calibration that utilizes all the new features in this PR, rendering the app useless :-)


![ld2410-card](https://user-images.githubusercontent.com/5775519/220052773-7366a505-5012-46c4-ab11-5722ef86cac1.png)

2023-02-26 22:35 UTC, jesserockz requested changes
Please leave all of the removed config items in the main component schema, but change the validation to `cv.invalid(...)` with a message telling users to check documentation to see how it should be now.

This is so that they know the key is removed, otherwise ESPHome just fails on an invalid key which is not nice.

2023-02-27 08:29 UTC, regevbr commented
> Please leave all of the removed config items in the main component schema, but change the validation to `cv.invalid(...)` with a message telling users to check documentation to see how it should be now.
> 
> This is so that they know the key is removed, otherwise ESPHome just fails on an invalid key which is not nice.

Good idea - done

2023-03-01 17:10 UTC, sebcaps requested changes

2023-03-01 17:10 UTC, sebcaps commented on esphome/components/ld2410/button/virtual_button.cpp
> +#include "virtual_button.h"
I think "ld2410_button" would be more suitable than "virtual_button"

2023-03-01 17:10 UTC, sebcaps commented on esphome/components/binary_sensor/binary_sensor.h
> +#define SUB_BINARY_SENSOR(name) \
Handled in [4477](https://github.com/esphome/esphome/pull/4447) => should be removed from this PR ?

2023-03-01 17:10 UTC, sebcaps commented on esphome/components/button/__init__.py
> +    class_: MockObjClass = _UNDEF,
handled in https://github.com/esphome/esphome/pull/4450, to remove from PR (?)

2023-03-01 17:10 UTC, sebcaps commented on esphome/components/copy/button/__init__.py
> +    button.button_schema(CopyButton)
handled in https://github.com/esphome/esphome/pull/4450, to remove from PR (?)

2023-03-01 17:10 UTC, sebcaps commented on esphome/components/factory_reset/button/__init__.py
> +CONFIG_SCHEMA = button.button_schema(
handled in https://github.com/esphome/esphome/pull/4450, to remove from PR (?)

2023-03-01 17:10 UTC, sebcaps commented on esphome/components/number/__init__.py
> +    CONF_ENTITY_CATEGORY,
handled in https://github.com/esphome/esphome/pull/4449, to remove from PR (?)

2023-03-01 17:10 UTC, sebcaps commented on esphome/components/restart/button/__init__.py
> +CONFIG_SCHEMA = button.button_schema(
handled in https://github.com/esphome/esphome/pull/4450, to remove from PR (?)

2023-03-01 17:10 UTC, sebcaps commented on esphome/components/safe_mode/button/__init__.py
> +        SafeModeButton,
handled in https://github.com/esphome/esphome/pull/4450, to remove from PR (?)

2023-03-01 17:10 UTC, sebcaps commented on esphome/components/text_sensor/text_sensor.h
> +#define SUB_TEXT_SENSOR(name) \
handled in https://github.com/esphome/esphome/pull/4448, to remove from PR (?)

2023-03-01 17:10 UTC, sebcaps commented on esphome/components/ld2410/number/virtual_number.cpp
> +#include "virtual_number.h"
I think "ld2410_number" would be more suitable than "virtual_number"

2023-03-01 17:10 UTC, sebcaps commented on esphome/components/ld2410/switch/virtual_switch.cpp
> +#include "virtual_switch.h"
I think "ld2410_switch" would be more suitable than "virtual_switch"

2023-03-01 17:14 UTC, sebcaps commented
@regevbr my comments about your PR. I (finally) managed to give a try to your update but, having trouble with 'engineering mode' button which is disabled as soon as one of the sensor presence, still or movement change => thus can't use it in a reliable way.
Many thx for the doc update and HA UI suggestion. Personnaly I never used decluttering and it's really a great  component, I'll use in the future

2023-03-01 17:20 UTC, regevbr commented on esphome/components/ld2410/button/virtual_button.cpp
> +#include "virtual_button.h"
fixed

2023-03-01 17:20 UTC, regevbr commented on esphome/components/ld2410/number/virtual_number.cpp
> +#include "virtual_number.h"
fixed

2023-03-01 17:20 UTC, regevbr commented on esphome/components/ld2410/switch/virtual_switch.cpp
> +#include "virtual_switch.h"
fixed

2023-03-01 17:21 UTC, regevbr commented on esphome/components/binary_sensor/binary_sensor.h
> +#define SUB_BINARY_SENSOR(name) \
@sebcaps seems like you are reviewing an old version of the code as this is already removed

2023-03-01 17:21 UTC, regevbr commented on esphome/components/button/__init__.py
> +    class_: MockObjClass = _UNDEF,
@sebcaps seems like you are reviewing an old version of the code as this is already removed

2023-03-01 17:21 UTC, regevbr commented on esphome/components/copy/button/__init__.py
> +    button.button_schema(CopyButton)
@sebcaps seems like you are reviewing an old version of the code as this is already removed

2023-03-01 17:21 UTC, regevbr commented on esphome/components/factory_reset/button/__init__.py
> +CONFIG_SCHEMA = button.button_schema(
@sebcaps seems like you are reviewing an old version of the code as this is already removed

2023-03-01 17:21 UTC, regevbr commented on esphome/components/number/__init__.py
> +    CONF_ENTITY_CATEGORY,
@sebcaps seems like you are reviewing an old version of the code as this is already removed

2023-03-01 17:22 UTC, regevbr commented on esphome/components/restart/button/__init__.py
> +CONFIG_SCHEMA = button.button_schema(
@sebcaps seems like you are reviewing an old version of the code as this is already removed

2023-03-01 17:22 UTC, regevbr commented on esphome/components/safe_mode/button/__init__.py
> +        SafeModeButton,
@sebcaps seems like you are reviewing an old version of the code as this is already removed

2023-03-01 17:22 UTC, regevbr commented on esphome/components/text_sensor/text_sensor.h
> +#define SUB_TEXT_SENSOR(name) \
@sebcaps seems like you are reviewing an old version of the code as this is already removed

2023-03-01 17:22 UTC, regevbr commented
> @regevbr my comments about your PR. I (finally) managed to give a try to your update but, having trouble with 'engineering mode' button which is disabled as soon as one of the sensor presence, still or movement change => thus can't use it in a reliable way. Many thx for the doc update and HA UI suggestion. Personnaly I never used decluttering and it's really a great component, I'll use in the future

Thanks! But it seems like you are using an old version of the code. Please update to the latest and the mode button will work perfectly

2023-03-02 15:13 UTC, clinta commented
I just tested this and it's excellent. The only remaining configuration option I can think of that's missing is the ability to disable bluetooth. Any chance that could be added as another switch?

![image](https://user-images.githubusercontent.com/3177437/222468520-c297e3e1-de6b-45e1-8a7c-2a880f4d8525.png)

2023-03-02 15:32 UTC, regevbr commented
> I just tested this and it's excellent. The only remaining configuration option I can think of that's missing is the ability to disable bluetooth. Any chance that could be added as another switch?
> 
> ![image](https://user-images.githubusercontent.com/3177437/222468520-c297e3e1-de6b-45e1-8a7c-2a880f4d8525.png)

Thanks! Glad to hear it works great.

About the request - I didn't add it on purpose as it is not relevant when using esphome - Bluetooth is not enabled when its data pins are connected (which is the case in esphome). If you can think of a relevant scenario that will be useful please let me know.

2023-03-02 15:37 UTC, clinta commented
> > I just tested this and it's excellent. The only remaining configuration option I can think of that's missing is the ability to disable bluetooth. Any chance that could be added as another switch?
> > ![image](https://user-images.githubusercontent.com/3177437/222468520-c297e3e1-de6b-45e1-8a7c-2a880f4d8525.png)
> 
> Thanks! Glad to hear it works great.
> 
> About the request - I didn't add it on purpose as it is not relevant when using esphome - Bluetooth is not enabled when its data pins are connected (which is the case in esphome). If you can think of a relevant scenario that will be useful please let me know.

Interesting. That is not the behavior I'm seeing. I still see the bluetooth device in a scan when powered up connected to an esp32. And I'm not seeing any documentation that indicates it should be automatically disabled. This just says it's enabled by default and can be turned off through the serial port.

![image](https://user-images.githubusercontent.com/3177437/222475218-c39374fb-8984-4ba6-8843-a6322e536614.png)

2023-03-02 15:39 UTC, regevbr commented
> > > I just tested this and it's excellent. The only remaining configuration option I can think of that's missing is the ability to disable bluetooth. Any chance that could be added as another switch?
> > > ![image](https://user-images.githubusercontent.com/3177437/222468520-c297e3e1-de6b-45e1-8a7c-2a880f4d8525.png)
> > 
> > 
> > Thanks! Glad to hear it works great.
> > About the request - I didn't add it on purpose as it is not relevant when using esphome - Bluetooth is not enabled when its data pins are connected (which is the case in esphome). If you can think of a relevant scenario that will be useful please let me know.
> 
> Interesting. That is not the behavior I'm seeing. I still see the bluetooth device in a scan when powered up connected to an esp32. And I'm not seeing any documentation that indicates it should be automatically disabled. This just says it's enabled by default and can be turned off through the serial port.
> 
> ![image](https://user-images.githubusercontent.com/3177437/222475218-c39374fb-8984-4ba6-8843-a6322e536614.png)

I don't see it that it why I figured it doesn't work when connected. So ok great I will add it as a toggle button (as they don't expose the state anywhere)

2023-03-02 16:41 UTC, clinta commented
Thanks for the quick addition. I added it to my config, and I get this error when pressing the button.

```yaml
button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params
    bluetooth_on:
      name: "bluetooth on"
    bluetooth_off:
      name: "bluetooth off"
```

![image](https://user-images.githubusercontent.com/3177437/222494305-56c8c005-f8af-4da6-9195-aef89b679212.png)

2023-03-02 16:42 UTC, regevbr commented
> Thanks for the quick addition. I added it to my config, and I get this error when pressing the button.
> 
> ```yaml
> button:
>   - platform: ld2410
>     factory_reset:
>       name: "factory reset"
>     restart:
>       name: "restart"
>     query_params:
>       name: query params
>     bluetooth_on:
>       name: "bluetooth on"
>     bluetooth_off:
>       name: "bluetooth off"
> ```
> 
> ![image](https://user-images.githubusercontent.com/3177437/222494305-56c8c005-f8af-4da6-9195-aef89b679212.png)

Haaha you are quick this is still a work in progress, I will let you know once it works

2023-03-02 17:39 UTC, sebcaps commented
@regevbr thanks for for the update and my bad for reviewing / using an old version. I still did not understand how this happened.
Anyway, sounds good to me.
I let you go on with BT ;-)

2023-03-02 18:58 UTC, regevbr commented
@clinta @sebcaps the bluetooth feature is ready (see updated example at top of this PR). It took some time as they have a typo in their API (to turn on you need to send 0X0001 and not 0x0100). 
I decided (luckily) to also add the mac address as a text sensor.
I found out that when BT is off, they don't send a mac address but a value of `08:05:04:03:02:01`. This causes issues with the state machine parser that I had to fix (as it ends with the `04:03:02:01` which signals the end of an ack response). But what it means is that I can realize from the mac address if BT is on or off, so I added a new switch to support changing Bluetooth and getting visibility of it (which is way better than 2 buttons :-) )
I do ask @clinta if you can verify it works for you as I want to make sure that the special mac value of `08:05:04:03:02:01` is consistent. If it doesn't work, please send over the mac address that you see when the BT is off.

@sebcaps did you manage to try out the newest code?

ps
I will update the docs PR as well now

2023-03-02 19:13 UTC, clinta commented
> @clinta @sebcaps the bluetooth feature is ready (see updated example at top of this PR). It took some time as they have a typo in their API (to turn on you need to send 0X0001 and not 0x0100). I decided (luckily) to also add the mac address as a text sensor. I found out that when BT is off, they don't send a mac address but a value of `08:05:04:03:02:01`. This causes issues with the state machine parser that I had to fix (as it ends with the `04:03:02:01` which signals the end of an ack response). But what it means is that I can realize from the mac address if BT is on or off, so I added a new switch to support changing Bluetooth and getting visibility of it (which is way better than 2 buttons :-) ) I do ask @clinta if you can verify it works for you as I want to make sure that the special mac value of `08:05:04:03:02:01` is consistent. If it doesn't work, please send over the mac address that you see when the BT is off.
> 
> @sebcaps did you manage to try out the newest code?
> 
> ps I will update the docs PR as well now

Working great. Switch toggles and my bluetooth scans confirm it is properly turning off and on.

2023-03-02 19:24 UTC, regevbr commented
apparently factory reset also turns on the BT, so I fixed it to reflect that

2023-03-05 16:30 UTC, sebcaps commented
Hello @regevbr everything is OK to me. 
Unfortunately, can't test Bluetooth since my device is not bluetooth, despite the fact I ordered a ld2410B.
Not a big deal, since I see it as a nice to have.

2023-03-05 16:30 UTC, sebcaps approved these changes

2023-03-05 16:35 UTC, menelike commented
I just tested my two ld2410b and this branch including the mentioned HA interface works like a charm. Thanks @regevbr!

`Unfortunately, can't test Bluetooth since my device is not bluetooth, despite the fact I ordered a ld2410B.`

This was the main reason for me testing this branch, I felt uncomfortable with bluetooth always being on. I was able to turn it off this way and still have an interface within HA for fine adjustments.

2023-03-06 08:22 UTC, regevbr commented
@jesserockz what else can I do to push this PR forward?

2023-03-08 18:31 UTC, nibblerrick commented
Hi,

first of all: thank you for this nice work!
I am trying your updated implementation and encounter one thing:
I have api disconnects every 1-2 seconds.
I completely removed the uart and ld2410 stuff to see if the board disconnects then, too, but no.

```
[19:23:02][W][api.connection:083]: Home Assistant 2023.3.1 (10.134.47.118): Connection closed
[19:23:02][V][api:114]: Removing connection to Home Assistant 2023.3.1 (10.134.47.118)
[19:23:02][V][component:204]: Component api took a long time for an operation (0.05 s).
[19:23:02][V][component:205]: Components should block for at most 20-30ms.
[19:23:02][V][ld2410:404]: Will handle Periodic Data
```
is what I see with loglevel verbose.
One time I hat Component ld2410 took a long time for operation, this varies between api and ld2410.

After the the "component took a long time" I only have a bunch of
`[19:28:45][V][ld2410:404]: Will handle Periodic Data`
between the disconnects (besided the actual data logging lines).
Is there something wrong on my end or can I do something to provide better logs/help?

2023-03-08 18:53 UTC, regevbr commented
> Hi,
> 
> first of all: thank you for this nice work! I am trying your updated implementation and encounter one thing: I have api disconnects every 1-2 seconds. I completely removed the uart and ld2410 stuff to see if the board disconnects then, too, but no.
> 
> ```
> [19:23:02][W][api.connection:083]: Home Assistant 2023.3.1 (10.134.47.118): Connection closed
> [19:23:02][V][api:114]: Removing connection to Home Assistant 2023.3.1 (10.134.47.118)
> [19:23:02][V][component:204]: Component api took a long time for an operation (0.05 s).
> [19:23:02][V][component:205]: Components should block for at most 20-30ms.
> [19:23:02][V][ld2410:404]: Will handle Periodic Data
> ```
> 
> is what I see with loglevel verbose. One time I hat Component ld2410 took a long time for operation, this varies between api and ld2410.
> 
> After the the "component took a long time" I only have a bunch of `[19:28:45][V][ld2410:404]: Will handle Periodic Data` between the disconnects (besided the actual data logging lines). Is there something wrong on my end or can I do something to provide better logs/help?

Hi,

Using log level verbose creates a very high load on the board, especially if you have used my entire configuration with all the components. I suggest to use the following logger config which disables USB logging that also helps performance:

```yaml
logger:
  baud_rate: 0
```

In addition, if you did not use the `throttle` option on the ld2410 component, I suggest you do that as well with at least `1000ms`

If it still fails for you, even after all of that with default log level (and not verbose) we will have to think of another thing that might cause it.

i.e
the messages `Component api took a long time for an operation` happens for me as well but I don't experience any disconnects.

2023-03-08 19:14 UTC, nibblerrick commented
Thank for the fast response!
logger baud_rate: 0 was already in.
This happens on the actual ld2410 configuration in esphome and esphome-dev, too (the actual codebase).
I enabled verbose logging after seeing the disconnects.
Disabling the webserver doesn't bring any improvments, either.
It's an ESP32. At the moment I have no idea. uart is configured correctly, too.
If I disconnect the LD2410 this happens, too, so shouldn't be a powerissue.
What I could try is getting another ESP and look if there's the same behaviour.
My other deployed ESPs are working fine.

So I'll try with another ESP the next days. If you have anything else I can try, let me know.
Others doesn't seem to have that problem, so something is odd here.

2023-03-08 20:50 UTC, regevbr commented
> Thank for the fast response! logger baud_rate: 0 was already in. This happens on the actual ld2410 configuration in esphome and esphome-dev, too (the actual codebase). I enabled verbose logging after seeing the disconnects. Disabling the webserver doesn't bring any improvments, either. It's an ESP32. At the moment I have no idea. uart is configured correctly, too. If I disconnect the LD2410 this happens, too, so shouldn't be a powerissue. What I could try is getting another ESP and look if there's the same behaviour. My other deployed ESPs are working fine.
> 
> So I'll try with another ESP the next days. If you have anything else I can try, let me know. Others doesn't seem to have that problem, so something is odd here.

I'm confused - this happens to you for the current ld2410 implementation from the stable esphome version (i.e. not related to this PR in any way)? If that is the case please open a new issue

2023-03-08 21:07 UTC, nibblerrick commented
No and yes:
I received my LD2410 yesterday and played around over bluetooth.
Looking to use it wired with ESPHome I looked for issues before deploying it and found your PR here, so I wanted to start with this directly.
All was working - except the api disconnects.
In order to nail down the problem I tried afterwards the current implementation, too, and flashed with the current implementation from esphome stable and dev, too.
So 3 variants:
1st this PR compiled in esphome dev addon
(then I wrote here, you answered, and then)
2nd current implementation esphome stable
3rd current implementation esphome dev.
All 3 variants have the api disconnect.
Besides that I completely commented out the ld2410 stuff and flashed without that, there the API disconnect don't happen. This was to see if the board/basic configuration has an issue, but there are no disconnects.
So it is related to this PR. But to the current implemenation, too, as I discovered afterwards.
Therefore next thing I will try is to use another ESP to see if this problem is consistent or some weird glitch with this specific ESP.
De-confuses this now a bit?

2023-03-08 21:11 UTC, regevbr commented
Ok makes more sense. In any case this to me deems a different ticket. If we can help nail down the problem and solve it in this PR I will be happy too but as it only happens to you, I don't want this issue to set back this PR... I'm sure you understand

2023-03-08 21:59 UTC, Padm59 commented
Hey, i just searched for a way to do what will be able with this PR. Also I have to say the HA Card is awesome and really renders the app useless. The only thing that is missing is the option to use the light level sensor of the ld2410. When you update the firmware over Bluetooth to the new beta starting with v2. it lets you also see the graph of the light level and adds some settlings. 

It would be awesome to have the light level sensor in HA and maybe add new settings also to the card. 
I get that this is a lot of work and definitely not part of this PR. Maybe you are interested to give it a try in the future if you have the time. I don’t even know if there is even a documentation about that feature yet. Maybe it will be my first PR if I find something and get it to work.

2023-03-08 22:11 UTC, regevbr commented
> Hey, i just searched for a way to do what will be able with this PR. Also I have to say the HA Card is awesome and really renders the app useless. The only thing that is missing is the option to use the light level sensor of the ld2410. When you update the firmware over Bluetooth to the new beta starting with v2. it lets you also see the graph of the light level and adds some settlings.
> 
> It would be awesome to have the light level sensor in HA and maybe add new settings also to the card. I get that this is a lot of work and definitely not part of this PR. Maybe you are interested to give it a try in the future if you have the time. I don’t even know if there is even a documentation about that feature yet. Maybe it will be my first PR if I find something and get it to work.

If you can locate the updated serial communication protocol docs, I will be happy to

2023-03-09 00:27 UTC, jesserockz commented
> @jesserockz what else can I do to push this PR forward?

![patience](https://media.tenor.com/3OZu_n2PL-QAAAAd/star-wars-yoda.gif)

2023-03-09 09:36 UTC, regevbr commented
> Hey, i just searched for a way to do what will be able with this PR. Also I have to say the HA Card is awesome and really renders the app useless. The only thing that is missing is the option to use the light level sensor of the ld2410. When you update the firmware over Bluetooth to the new beta starting with v2. it lets you also see the graph of the light level and adds some settlings.
> 
> It would be awesome to have the light level sensor in HA and maybe add new settings also to the card. I get that this is a lot of work and definitely not part of this PR. Maybe you are interested to give it a try in the future if you have the time. I don’t even know if there is even a documentation about that feature yet. Maybe it will be my first PR if I find something and get it to work.

I just spoke to the guys manufacturing it. Currently there are no docs for v2 so I can't implement anything from it. But on my search I did discover new docs for v1.7 and found out some more operations that can be done. I'm working on adding them now (+fixing the version parsing)

2023-03-09 10:00 UTC, nibblerrick commented
> Ok makes more sense. In any case this to me deems a different ticket. If we can help nail down the problem and solve it in this PR I will be happy too but as it only happens to you, I don't want this issue to set back this PR... I'm sure you understand

Totally. Besides that this implementation worked fantastic, all settings and switches worked fine.
It was just my troubleshooting-route:
This PR -> API disconnects
Other ESPs: fine.
Trouble ESP without this implementation: fine
So I asked, I thought probably I just overlooked sth.
But also tried to find the cause and then discovered that with the actual implementation has disconnects, too.
I think it's right to say, that this problem isn't specific to this this PR.
It seems to be somehow sth. with the complete LD2410 implementation and sth. on my side.
I'll give an update if I find out why, otherwise I'll open an issue with all things I tried.
For now I'll test with my other LD2410-modules and other ESPs to see if it's something reproducable with different hardware.
Thanks again for your work!

2023-03-09 14:36 UTC, nibblerrick commented
With another ESP32 it works flawless.
Seems to be one of this very wired problems, as the "problematic" ESP works without issue with other sensors attached.
So only one specific ESP with this integration doesn't seem to work (same vendor of the two ESPs).
Sorry for the confusion, if I discover anything when deploying other LD2410 I'll make an issue, but I doubt it will be the case.
Thanks!

2023-03-09 15:41 UTC, regevbr commented
Guys sorry for all the commits but I discovered some updated docs so I added 2 new features:
- `select` component to control the distance resolution. I'm not sure what it means but it is part of the protocol
- automation action to change the BT password. This can be hooked up with HA service (see full configuration above)

In order to check latest version, please also include the `select` component from my branch (`components: [ld2410, select]`) until I will open a separate PR for that change.

I will also update the docs to reflect the new features.

Your review and tests will be appreciated :-)

2023-03-09 20:18 UTC, nibblerrick commented
> Your review and tests will be appreciated :-)

Having a functional setup now I tested your latest additions. Works fine over here, switcheing between 0,75 and 0.2 gives the expected distance results.
Setting the BT-password works fine, too!

2023-03-11 10:23 UTC, sebcaps commented
@regevbr  sounds good to me (still no BT to test).
Can you please add a link to updated doc for distance_resolution ?
Last point is baud rate config and I think everything will be covered. I assume I did not implement it since I tried to use config from UART but with no luck. Implementing actionis relatively easy (ie using select ?). Not convinced it's a good thing to multiply config for the same parameter that's why I gave up ;-)

2023-03-11 10:24 UTC, sebcaps approved these changes

2023-03-11 15:51 UTC, regevbr commented
> @regevbr sounds good to me (still no BT to test). Can you please add a link to updated doc for distance_resolution ? Last point is baud rate config and I think everything will be covered. I assume I did not implement it since I tried to use config from UART but with no luck. Implementing actionis relatively easy (ie using select ?). Not convinced it's a good thing to multiply config for the same parameter that's why I gave up ;-)

The thing with baud rate with the approach you suggested is that it becomes a chicken and egg situation - in order to change the baud rate, you need to know the existing baud rate to send the command. So if you set in the yaml config the rate you want, how will you know to what baud rate you need to first connect?

I can add a buad rate command (not a select) that will require the user to change the yaml config afterwards and recompile the esphome. What do you think?

2023-03-11 16:27 UTC, sebcaps commented
> The thing with baud rate with the approach you suggested is that it becomes a chicken and egg situation - in order to change the baud rate, you need to know the existing baud rate to send the command. So if you set in the yaml config the rate you want, how will you know to what baud rate you need to first connect?

Definitely the reason I wanted to be able to get the rate configured in UART section and then apply it.
But I can't figure out how it works in the app since baud rate is set before connection,and why it works as well in this [implementation](https://github.com/rain931215/ESPHome-LD2410/blob/main/ld2410_uart.h) which I used as a basis for the initial implementation :-)

2023-03-11 20:48 UTC, regevbr commented
> > The thing with baud rate with the approach you suggested is that it becomes a chicken and egg situation - in order to change the baud rate, you need to know the existing baud rate to send the command. So if you set in the yaml config the rate you want, how will you know to what baud rate you need to first connect?
> 
> Definitely the reason I wanted to be able to get the rate configured in UART section and then apply it. But I can't figure out how it works in the app since baud rate is set before connection,and why it works as well in this [implementation](https://github.com/rain931215/ESPHome-LD2410/blob/main/ld2410_uart.h) which I used as a basis for the initial implementation :-)

App is working on Bluetooth not sire baud rate has anything to do with it. As to the implementation yoi based on he doesn't handle baud rate changes in the uarc component so im6not sure what you are talking about.

In amy case i will implement it but it will not work smoothly like i said in previous comment. That is the reason i did not implement it in the first place

2023-03-12 08:14 UTC, sebcaps commented
About app, I refer to windows app which can be used to configure ld2410 and uses serial bus.
 If you don't feel comfortable, don't do it, your work is already incredible and add great features. Baud rate config would just be a small one compared to others.
I was just wondering if you missed it or consider it and don't do on purpose. As we share the 'difficulty' and low added value, let's go this way😀

2023-03-12 11:33 UTC, hungpr0 commented
Hello @regevbr 

This may be a noob question. Just wanted to test your PR. I'm using ESP32. Is there anything I need to do to test it?

Here is config:
```
external_components:
  source: github://regevbr/esphome@ld2410
  components: [ld2410, select]
  refresh: 0s

esphome:
  name: esp32

esp32:
  board: esp32dev

# Enable logging
logger:
  level: WARN
  baud_rate: 0
web_server:
  port: 80
# Enable Home Assistant API
api:
  encryption:
    key: "censored"
ota:
  password: "censored"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-Mini-Presence01"
    password: "censored"

uart:
  id: uart1
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: uart1
  throttle: 1500ms
  id: ld2410_comp

select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410
    timeout:
      name: timeout
    max_move_distance:
      name: max move distance
    max_still_distance:
      name: max still distance
    g0_move_threshold:
      name: g0 move threshold
    g0_still_threshold:
      name: g0 still threshold
    g1_move_threshold:
      name: g1 move threshold
    g1_still_threshold:
      name: g1 still threshold
    g2_move_threshold:
      name: g2 move threshold
    g2_still_threshold:
      name: g2 still threshold
    g3_move_threshold:
      name: g3 move threshold
    g3_still_threshold:
      name: g3 still threshold
    g4_move_threshold:
      name: g4 move threshold
    g4_still_threshold:
      name: g4 still threshold
    g5_move_threshold:
      name: g5 move threshold
    g5_still_threshold:
      name: g5 still threshold
    g6_move_threshold:
      name: g6 move threshold
    g6_still_threshold:
      name: g6 still threshold
    g7_move_threshold:
      name: g7 move threshold
    g7_still_threshold:
      name: g7 still threshold
    g8_move_threshold:
      name: g8 move threshold
    g8_still_threshold:
      name: g8 still threshold

text_sensor:
  - platform: ld2410
    version:
      name: "presenece sensor version" 
    mac_address:
      name: "presenece sensor mac address"

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode" 
    bluetooth:
      name: control Bluetooth

binary_sensor:
  - platform: ld2410
    has_target:
      name: "presence"
    has_moving_target:
      name: "movement"
    has_still_target:
      name: "still"

sensor:
  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
    g0_move_energy:
      name: g0 move energy
    g0_still_energy:
      name: g0 still energy
    g1_move_energy:
      name: g1 move energy
    g1_still_energy:
      name: g1 still energy
    g2_move_energy:
      name: g2 move energy
    g2_still_energy:
      name: g2 still energy
    g3_move_energy:
      name: g3 move energy
    g3_still_energy:
      name: g3 still energy
    g4_move_energy:
      name: g4 move energy
    g4_still_energy:
      name: g4 still energy
    g5_move_energy:
      name: g5 move energy
    g5_still_energy:
      name: g5 still energy
    g6_move_energy:
      name: g6 move energy
    g6_still_energy:
      name: g6 still energy
    g7_move_energy:
      name: g7 move energy
    g7_still_energy:
      name: g7 still energy
    g8_move_energy:
      name: g8 move energy
    g8_still_energy:
      name: g8 still energy
```

Here is error log:
```
INFO Reading configuration /config/esphome/esp32.yaml...
INFO Updating https://github.com/regevbr/esphome.git@ld2410
ERROR Unable to load component ld2410.button:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/a73781ce/esphome/components/ld2410/button/__init__.py", line 15, in <module>
    cv.Optional(CONF_FACTORY_RESET): button.button_schema(
TypeError: button_schema() got multiple values for argument 'icon'
ERROR Unable to load component ld2410.number:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/a73781ce/esphome/components/ld2410/number/__init__.py", line 52, in <module>
    cv.Optional(CONF_TIMEOUT): number.number_schema(
AttributeError: module 'esphome.components.number' has no attribute 'number_schema'
Failed config

button.ld2410: [source /config/esphome/esp32.yaml:53]
  
  Platform not found: 'button.ld2410'.
  platform: ld2410
  factory_reset: 
    name: factory reset
  restart: 
    name: restart
  query_params: 
    name: query params
number.ld2410: [source /config/esphome/esp32.yaml:62]
  
  Platform not found: 'number.ld2410'.
  platform: ld2410
  timeout: 
    name: timeout
  max_move_distance: 
    name: max move distance
  max_still_distance: 
    name: max still distance
  g0_move_threshold: 
    name: g0 move threshold
  g0_still_threshold: 
    name: g0 still threshold
  g1_move_threshold: 
    name: g1 move threshold
  g1_still_threshold: 
    name: g1 still threshold
  g2_move_threshold: 
    name: g2 move threshold
  g2_still_threshold: 
    name: g2 still threshold
  g3_move_threshold: 
    name: g3 move threshold
  g3_still_threshold: 
    name: g3 still threshold
  g4_move_threshold: 
    name: g4 move threshold
  g4_still_threshold: 
    name: g4 still threshold
  g5_move_threshold: 
    name: g5 move threshold
  g5_still_threshold: 
    name: g5 still threshold
  g6_move_threshold: 
    name: g6 move threshold
  g6_still_threshold: 
    name: g6 still threshold
  g7_move_threshold: 
    name: g7 move threshold
  g7_still_threshold: 
    name: g7 still threshold
  g8_move_threshold: 
    name: g8 move threshold
  g8_still_threshold: 
    name: g8 still threshold
```

2023-03-12 11:51 UTC, regevbr commented
> Hello @regevbr
> 
> This may be a noob question. Just wanted to test your PR. I'm using ESP32. Is there anything I need to do to test it?
> 
> Here is config:
> 
> ```
> external_components:
>   source: github://regevbr/esphome@ld2410
>   components: [ld2410, select]
>   refresh: 0s
> 
> esphome:
>   name: esp32
> 
> esp32:
>   board: esp32dev
> 
> # Enable logging
> logger:
>   level: WARN
>   baud_rate: 0
> web_server:
>   port: 80
> # Enable Home Assistant API
> api:
>   encryption:
>     key: "censored"
> ota:
>   password: "censored"
> 
> wifi:
>   ssid: !secret wifi_ssid
>   password: !secret wifi_password
> 
>   # Enable fallback hotspot (captive portal) in case wifi connection fails
>   ap:
>     ssid: "ESP-Mini-Presence01"
>     password: "censored"
> 
> uart:
>   id: uart1
>   tx_pin: GPIO1
>   rx_pin: GPIO3
>   baud_rate: 256000
>   parity: NONE
>   stop_bits: 1
> 
> ld2410:
>   uart_id: uart1
>   throttle: 1500ms
>   id: ld2410_comp
> 
> select:
>   - platform: ld2410
>     distance_resolution:
>       name: distance resolution
> 
> button:
>   - platform: ld2410
>     factory_reset:
>       name: "factory reset"
>     restart:
>       name: "restart"
>     query_params:
>       name: query params
> 
> number:
>   - platform: ld2410
>     timeout:
>       name: timeout
>     max_move_distance:
>       name: max move distance
>     max_still_distance:
>       name: max still distance
>     g0_move_threshold:
>       name: g0 move threshold
>     g0_still_threshold:
>       name: g0 still threshold
>     g1_move_threshold:
>       name: g1 move threshold
>     g1_still_threshold:
>       name: g1 still threshold
>     g2_move_threshold:
>       name: g2 move threshold
>     g2_still_threshold:
>       name: g2 still threshold
>     g3_move_threshold:
>       name: g3 move threshold
>     g3_still_threshold:
>       name: g3 still threshold
>     g4_move_threshold:
>       name: g4 move threshold
>     g4_still_threshold:
>       name: g4 still threshold
>     g5_move_threshold:
>       name: g5 move threshold
>     g5_still_threshold:
>       name: g5 still threshold
>     g6_move_threshold:
>       name: g6 move threshold
>     g6_still_threshold:
>       name: g6 still threshold
>     g7_move_threshold:
>       name: g7 move threshold
>     g7_still_threshold:
>       name: g7 still threshold
>     g8_move_threshold:
>       name: g8 move threshold
>     g8_still_threshold:
>       name: g8 still threshold
> 
> text_sensor:
>   - platform: ld2410
>     version:
>       name: "presenece sensor version" 
>     mac_address:
>       name: "presenece sensor mac address"
> 
> switch:
>   - platform: ld2410
>     engineering_mode:
>       name: "engineering mode" 
>     bluetooth:
>       name: control Bluetooth
> 
> binary_sensor:
>   - platform: ld2410
>     has_target:
>       name: "presence"
>     has_moving_target:
>       name: "movement"
>     has_still_target:
>       name: "still"
> 
> sensor:
>   - platform: ld2410
>     moving_distance:
>       name: "Moving distance (cm)"
>     still_distance:
>       name: "Still Distance (cm)"
>     moving_energy:
>       name: "Move Energy (%)"
>     still_energy:
>       name: "Still Energy (%)"
>     detection_distance:
>       name: "Distance Detection (cm)"
>     g0_move_energy:
>       name: g0 move energy
>     g0_still_energy:
>       name: g0 still energy
>     g1_move_energy:
>       name: g1 move energy
>     g1_still_energy:
>       name: g1 still energy
>     g2_move_energy:
>       name: g2 move energy
>     g2_still_energy:
>       name: g2 still energy
>     g3_move_energy:
>       name: g3 move energy
>     g3_still_energy:
>       name: g3 still energy
>     g4_move_energy:
>       name: g4 move energy
>     g4_still_energy:
>       name: g4 still energy
>     g5_move_energy:
>       name: g5 move energy
>     g5_still_energy:
>       name: g5 still energy
>     g6_move_energy:
>       name: g6 move energy
>     g6_still_energy:
>       name: g6 still energy
>     g7_move_energy:
>       name: g7 move energy
>     g7_still_energy:
>       name: g7 still energy
>     g8_move_energy:
>       name: g8 move energy
>     g8_still_energy:
>       name: g8 still energy
> ```
> 
> Here is error log:
> 
> ```
> INFO Reading configuration /config/esphome/esp32.yaml...
> INFO Updating https://github.com/regevbr/esphome.git@ld2410
> ERROR Unable to load component ld2410.button:
> Traceback (most recent call last):
>   File "/esphome/esphome/loader.py", line 162, in _lookup_module
>     module = importlib.import_module(f"esphome.components.{domain}")
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/config/esphome/.esphome/external_components/a73781ce/esphome/components/ld2410/button/__init__.py", line 15, in <module>
>     cv.Optional(CONF_FACTORY_RESET): button.button_schema(
> TypeError: button_schema() got multiple values for argument 'icon'
> ERROR Unable to load component ld2410.number:
> Traceback (most recent call last):
>   File "/esphome/esphome/loader.py", line 162, in _lookup_module
>     module = importlib.import_module(f"esphome.components.{domain}")
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/config/esphome/.esphome/external_components/a73781ce/esphome/components/ld2410/number/__init__.py", line 52, in <module>
>     cv.Optional(CONF_TIMEOUT): number.number_schema(
> AttributeError: module 'esphome.components.number' has no attribute 'number_schema'
> Failed config
> 
> button.ld2410: [source /config/esphome/esp32.yaml:53]
>   
>   Platform not found: 'button.ld2410'.
>   platform: ld2410
>   factory_reset: 
>     name: factory reset
>   restart: 
>     name: restart
>   query_params: 
>     name: query params
> number.ld2410: [source /config/esphome/esp32.yaml:62]
>   
>   Platform not found: 'number.ld2410'.
>   platform: ld2410
>   timeout: 
>     name: timeout
>   max_move_distance: 
>     name: max move distance
>   max_still_distance: 
>     name: max still distance
>   g0_move_threshold: 
>     name: g0 move threshold
>   g0_still_threshold: 
>     name: g0 still threshold
>   g1_move_threshold: 
>     name: g1 move threshold
>   g1_still_threshold: 
>     name: g1 still threshold
>   g2_move_threshold: 
>     name: g2 move threshold
>   g2_still_threshold: 
>     name: g2 still threshold
>   g3_move_threshold: 
>     name: g3 move threshold
>   g3_still_threshold: 
>     name: g3 still threshold
>   g4_move_threshold: 
>     name: g4 move threshold
>   g4_still_threshold: 
>     name: g4 still threshold
>   g5_move_threshold: 
>     name: g5 move threshold
>   g5_still_threshold: 
>     name: g5 still threshold
>   g6_move_threshold: 
>     name: g6 move threshold
>   g6_still_threshold: 
>     name: g6 still threshold
>   g7_move_threshold: 
>     name: g7 move threshold
>   g7_still_threshold: 
>     name: g7 still threshold
>   g8_move_threshold: 
>     name: g8 move thresho [...]

2023-03-12 19:50 UTC, regevbr commented
> About app, I refer to windows app which can be used to configure ld2410 and uses serial bus. If you don't feel comfortable, don't do it, your work is already incredible and add great features. Baud rate config would just be a small one compared to others. I was just wondering if you missed it or consider it and don't do on purpose. As we share the 'difficulty' and low added value, let's go this waygrinning

I'm guessing since they can control the baud rate on the fly (which here doesn't seem like it is an option) and save the current rate on disk and reuse it on next run, it is possible. Here it will not be possible (at least I couldn't figure out how).
What I will do is add a select component and once someone use it to change the baud rate, they must change their yaml config and resinstall the device.

As to updated docs, it can be found here - https://h.hlktech.com/Mobile/download/fdetail/214.html

2023-03-12 20:39 UTC, regevbr commented
baud rate control was added and tested. Docs were updated accordingly. I will emphasize again - changing baud rate will cause the sensor to stop working and you will have to reinstall with the updated yaml config.
This final change renders this PR as 100% compatible with the 1.7 version of the firmware.
Your tests and feedback are welcome as always :-)

2023-03-17 21:53 UTC, regevbr commented
Thanks to @user45876, I was able to extract the latest docs from the app's apk, and I have added all the new functionality that is included in it:

[LD2410 串口通信协议 V1.06 230220_zh (1).pdf](https://github.com/esphome/esphome/files/11006624/LD2410.V1.06.230220_zh.1.pdf)

```yaml
select:
  - platform: ld2410
    light_function:
      name: light function
    out_pin_level:
      name: out ping level

number:
  - platform: ld2410
    light_threshold:
      name: light threshold

binary_sensor:
  - platform: ld2410
    out_pin_presence:
      name: out pin presence
  - platform: gpio
    pin: REPLACE ME
    name: gpio out pin presence
    device_class: presence

sensor:
  - platform: ld2410
    light:
      name: light
```

I have updated the docs (and HA cards in them) and samples in this PR. I suggest to also add the gpio sensor (described in the docs) to get the full experience of the HA card and new abilities.
Please note that there are 2 breaking changes I made in the last commit:
- `max_move_distance` -> `max_move_distance_gate`
- `max_still_distance` -> `max_still_distance_gate`

@Padm59 and @sebcaps I would appreciate it if you can also test out the new functionality and provide any feedback.

2023-03-17 22:30 UTC, user45876 commented
@regevbr thanks, this is great! 
Small typo alert:

select: - platform: ld2410 light_function: name: light function out_pin_level: name: out **ping** level

Ping instead of pin - I smell autocorrect 😁

2023-03-17 22:40 UTC, regevbr commented
> @regevbr thanks, this is great! Small typo alert:
> 
> select: - platform: ld2410 light_function: name: light function out_pin_level: name: out **ping** level
> 
> Ping instead of pin - I smell autocorrect grin

Thanks, fixed

2023-03-18 16:24 UTC, pacjo commented
Would it be possible to get data from light sensor without engineering mode being enabled? Currently it acts just like other still / move energy sensor.

2023-03-18 20:58 UTC, regevbr commented
> Would it be possible to get data from light sensor without engineering mode being enabled? Currently it acts just like other still / move energy sensor.

nope

2023-03-20 05:00 UTC, hungpr0 commented
Hello,

Anyone tested with ESP8266?
It seems there is a problem, the board reboot every time I reload the web interface.
There are error: `Could not allocate memory for JSON document! Requested 456 bytes, largest free heap block: 456 bytes`

Here is my config:
```
esphome:
  name: esp8266-bedroom
  friendly_name: esp8266-bedroom

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: WARN
  baud_rate: 0
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: "my_password"
  services:
    - service: set_ld2410_bluetooth_password
      variables:
        password: string
      then:
        - bluetooth_password.set:
            id: ld2410_comp
            password: !lambda 'return password;'

ota:
  password: "my_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-Bedroom Fallback Hotspot"
    password: "my_password"

captive_portal:

external_components:
  source: github://regevbr/esphome@ld2410
  components: [ld2410, select]

ld2410:
  uart_id: uart1
  throttle: 1500ms
  id: ld2410_comp

uart:
  id: uart1
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence:
      name: out pin presence

sensor:
  - platform: uptime
    name: Uptime Sensor
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0_move_energy:
      name: g0 move energy
    g0_still_energy:
      name: g0 still energy
    g1_move_energy:
      name: g1 move energy
    g1_still_energy:
      name: g1 still energy
    g2_move_energy:
      name: g2 move energy
    g2_still_energy:
      name: g2 still energy
    g3_move_energy:
      name: g3 move energy
    g3_still_energy:
      name: g3 still energy
    g4_move_energy:
      name: g4 move energy
    g4_still_energy:
      name: g4 still energy
    g5_move_energy:
      name: g5 move energy
    g5_still_energy:
      name: g5 still energy
    g6_move_energy:
      name: g6 move energy
    g6_still_energy:
      name: g6 still energy
    g7_move_energy:
      name: g7 move energy
    g7_still_energy:
      name: g7 still energy
    g8_move_energy:
      name: g8 move energy
    g8_still_energy:
      name: g8 still energy

number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0_move_threshold:
      name: g0 move threshold
    g0_still_threshold:
      name: g0 still threshold
    g1_move_threshold:
      name: g1 move threshold
    g1_still_threshold:
      name: g1 still threshold
    g2_move_threshold:
      name: g2 move threshold
    g2_still_threshold:
      name: g2 still threshold
    g3_move_threshold:
      name: g3 move threshold
    g3_still_threshold:
      name: g3 still threshold
    g4_move_threshold:
      name: g4 move threshold
    g4_still_threshold:
      name: g4 still threshold
    g5_move_threshold:
      name: g5 move threshold
    g5_still_threshold:
      name: g5 still threshold
    g6_move_threshold:
      name: g6 move threshold
    g6_still_threshold:
      name: g6 still threshold
    g7_move_threshold:
      name: g7 move threshold
    g7_still_threshold:
      name: g7 still threshold
    g8_move_threshold:
      name: g8 move threshold
    g8_still_threshold:
      name: g8 still threshold

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"

select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

```

ESP32 doesn't have that issue.

2023-03-20 06:59 UTC, user45876 commented
@hungpr0 try disabling the webserver. From the documentation it is known to put a high memory load especially on the esp8266. Also, which board are you using? Try setting it accordingly in your config :)

https://esphome.io/components/web_server.html

"The web_server component creates a simple web server on the node that can be accessed through any browser and a simple [REST API](https://esphome.io/web-api/index.html). **Please note that enabling this component will take up a lot of memory and can lead to problems, especially on the ESP8266.**"

2023-03-20 11:17 UTC, hungpr0 commented
> @hungpr0 try disabling the webserver. From the documentation it is known to put a high memory load especially on the esp8266. Also, which board are you using? Try setting it accordingly in your config :)
> 
> https://esphome.io/components/web_server.html
> 
> "The web_server component creates a simple web server on the node that can be accessed through any browser and a simple [REST API](https://esphome.io/web-api/index.html). **Please note that enabling this component will take up a lot of memory and can lead to problems, especially on the ESP8266.**"

It is NodeMCU V3.
Thanks. After disabling web server. It is fine now.

2023-03-22 11:33 UTC, Electronlibre2012 commented
Hello @regevbr 

sorry but i cant find your sample code for the HA card : "In the updated docs I added a suggestion of a custom HA card that will make this process super easy, same as the app :-)"

i search the updated docs but dont find your custom HA code anywhere.

Could you point me to this code please?

2023-03-22 11:38 UTC, regevbr commented
> Hello @regevbr
> 
> sorry but i cant find your sample code for the HA card : "In the updated docs I added a suggestion of a custom HA card that will make this process super easy, same as the app :-)"
> 
> i search the updated docs but dont find your custom HA code anywhere.
> 
> Could you point me to this code please?

https://deploy-preview-2680--esphome.netlify.app/components/sensor/ld2410

2023-03-23 14:19 UTC, sebcaps requested changes

2023-03-23 14:19 UTC, sebcaps commented on esphome/components/ld2410/sensor.py
> +            unit_of_measurement=UNIT_LUX,
Hardly imagine that the 0-255 value reported is in lux

2023-03-23 14:19 UTC, sebcaps commented on esphome/components/ld2410/sensor.py
> +            device_class=DEVICE_CLASS_ENERGY,
Generate warning in HA since '%' is not a valid unit of measurement for energy.
Anyway can't find a better class than 'None' for replacement....
Just warning & in engineering mode only => not a big issue :-)

2023-03-23 14:19 UTC, sebcaps commented on esphome/components/ld2410/binary_sensor.py
> +CONF_OUT_PIN_PRESENCE = "out_pin_presence"
I think CONF_OUT_PIN_PRESENCE_STATUS would be more meaningful (?) . Not taking about a gpio pin but more likely its status (high/low).

2023-03-23 14:25 UTC, sebcaps commented on esphome/components/ld2410/binary_sensor.py
> +CONF_OUT_PIN_PRESENCE = "out_pin_presence"
Hello @regevbr please find some 'small' comments about code review.
From my side, light reporting is working (values are reported), but no luck with "out_presence_pin", whatever the config its (out pin level, light function or light threshold) status is always 'off'. I personnaly don"t plan to use it but just to let you know ;-)
Thx for your very, very, very hard job and your commitment to to get the most complete component :-)

2023-03-23 14:38 UTC, regevbr commented on esphome/components/ld2410/sensor.py
> +            unit_of_measurement=UNIT_LUX,
Yes it actually starts in 85, but that is what the docs say....

2023-03-23 14:38 UTC, regevbr commented on esphome/components/ld2410/sensor.py
> +            device_class=DEVICE_CLASS_ENERGY,
I will change it to none

2023-03-23 14:43 UTC, regevbr commented on esphome/components/ld2410/binary_sensor.py
> +CONF_OUT_PIN_PRESENCE = "out_pin_presence"
CONF_OUT_PIN_PRESENCE_STATUS - will handle
about the out_presence_pin - this might be part of the firmware update that I'm guessing you don't have access to. This is actually just helpful for debugging in the app, and probably no real use to it here in esp. But I added it anyway.
And gladly :-) It was (and still is) a challenging journey.

2023-03-23 14:52 UTC, regevbr commented on esphome/components/ld2410/sensor.py
> +            unit_of_measurement=UNIT_LUX,
I updated the docs to say that

2023-03-23 15:01 UTC, regevbr commented on esphome/components/ld2410/binary_sensor.py
> +CONF_OUT_PIN_PRESENCE = "out_pin_presence"
fixed all CR comments

2023-03-23 15:28 UTC, sebcaps approved these changes

2023-03-26 20:03 UTC, clinta commented
Thanks again for the amazing work on this. I'm using this to integrate presence sensors into esp32 ceiling lights.

Could the entity category of some of the sensors and numbers be changed?

It seems to me that all the sensors that are only available in engineering mode should be consider `diagnostic`, as well as the reboot and factory reset buttons. And the threshold numbers, bluetooth switch, engineering switch, and timeout value should be in `config`. Or these sensors can be made configurable by allowing the `entity_category` option to be set in yaml.

Having these categorized this way would result in a clean device page for my device.

2023-03-26 20:14 UTC, regevbr commented
@jesserockz can you please reopen this?

2023-03-26 21:10 UTC, jesserockz commented
Why did you link that other pr to close this one? Haha

2023-03-26 21:11 UTC, regevbr commented
> Why did you link that other pr to close this one? Haha

My bad 😋

2023-03-26 21:56 UTC, regevbr commented
> Thanks again for the amazing work on this. I'm using this to integrate presence sensors into esp32 ceiling lights.
> 
> Could the entity category of some of the sensors and numbers be changed?
> 
> It seems to me that all the sensors that are only available in engineering mode should be consider `diagnostic`, as well as the reboot and factory reset buttons. And the threshold numbers, bluetooth switch, engineering switch, and timeout value should be in `config`. Or these sensors can be made configurable by allowing the `entity_category` option to be set in yaml.
> 
> Having these categorized this way would result in a clean device page for my device.

Thanks!
I just updated some default entity categories. I did however use CONFIG on the factory reset button as it changes config :-)
You can also change it in your YAML - the docs state on each config entry that it can also use any configuration from it "base type" with a link to the docs of it

2023-03-26 22:00 UTC, clinta commented
Oh, I had bad indenting when I tried to set it manually, and that made me think it was a feature that had to be implemented. My bad. But thanks for updating the defaults.

2023-03-28 20:30 UTC, lienbacher commented
I've just found this amazing addition and wanted to give it a try, unfortunately it does not seem to go for me. When compiling the example config from this PR I get this error: 

```
INFO Reading configuration /config/esphome/ld2410-test.yaml...
INFO Updating https://github.com/regevbr/esphome.git@ld2410
ERROR Unable to load component ld2410.select:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 165, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/a73781ce/esphome/components/ld2410/select/__init__.py", line 30, in <module>
    cv.Optional(CONF_DISTANCE_RESOLUTION): select.select_schema(
AttributeError: module 'esphome.components.select' has no attribute 'select_schema'
Failed config

select.ld2410: [source /config/esphome/ld2410-test.yaml:55]
  
  Platform not found: 'select.ld2410'.
  platform: ld2410
  distance_resolution: 
    name: distance resolution
  baud_rate: 
    name: baud rate
  light_function: 
    name: light function
  out_pin_level: 
    name: out pin level
```

When I remove the select config this error goes away but it then fails like this: 

```
INFO Compiling app...
Processing ld2410-test (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Compiling /data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/ld2410/ld2410.cpp.o
Compiling /data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/ld2410/ld2410_call.cpp.o
Compiling /data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/number/number.cpp.o
Compiling /data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/number/number_call.cpp.o
In file included from src/esphome/components/ld2410/ld2410_call.cpp:2:
src/esphome/components/ld2410/ld2410.h: In lambda function:
src/esphome/components/ld2410/ld2410.h:233:11: error: 'class esphome::ld2410::LD2410Component' has no member named 'set_light_control_'; did you mean 'get_light_control_'?
     this->set_light_control_();
           ^~~~~~~~~~~~~~~~~~
src/esphome/components/ld2410/ld2410.h:149:7: note: in definition of macro 'SUB_LAMBDA_NUMBER'
       cb; \
       ^~
In file included from src/esphome/components/ld2410/ld2410.cpp:1:
src/esphome/components/ld2410/ld2410.h: In lambda function:
src/esphome/components/ld2410/ld2410.h:233:11: error: 'class esphome::ld2410::LD2410Component' has no member named 'set_light_control_'; did you mean 'get_light_control_'?
     this->set_light_control_();
           ^~~~~~~~~~~~~~~~~~
src/esphome/components/ld2410/ld2410.h:149:7: note: in definition of macro 'SUB_LAMBDA_NUMBER'
       cb; \
       ^~
*** [/data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/ld2410/ld2410_call.cpp.o] Error 1
*** [/data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/ld2410/ld2410.cpp.o] Error 1
========================== [FAILED] Took 3.59 seconds ==========================
```

Reading the code It seems to be directly related to the missing select definition. 

I'm a bit clueless but I guess the problem might be rather obvious. Whats your thoughts @regevbr?

2023-03-28 20:33 UTC, regevbr commented
> I've just found this amazing addition and wanted to give it a try, unfortunately it does not seem to go for me. When compiling the example config from this PR I get this error:
> 
> ```
> INFO Reading configuration /config/esphome/ld2410-test.yaml...
> INFO Updating https://github.com/regevbr/esphome.git@ld2410
> ERROR Unable to load component ld2410.select:
> Traceback (most recent call last):
>   File "/esphome/esphome/loader.py", line 165, in _lookup_module
>     module = importlib.import_module(f"esphome.components.{domain}")
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/config/esphome/.esphome/external_components/a73781ce/esphome/components/ld2410/select/__init__.py", line 30, in <module>
>     cv.Optional(CONF_DISTANCE_RESOLUTION): select.select_schema(
> AttributeError: module 'esphome.components.select' has no attribute 'select_schema'
> Failed config
> 
> select.ld2410: [source /config/esphome/ld2410-test.yaml:55]
>   
>   Platform not found: 'select.ld2410'.
>   platform: ld2410
>   distance_resolution: 
>     name: distance resolution
>   baud_rate: 
>     name: baud rate
>   light_function: 
>     name: light function
>   out_pin_level: 
>     name: out pin level
> ```
> 
> When I remove the select config this error goes away but it then fails like this:
> 
> ```
> INFO Compiling app...
> Processing ld2410-test (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.2.0)
> --------------------------------------------------------------------------------
> HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
>  - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
> LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
> Dependency Graph
> |-- AsyncTCP-esphome @ 1.2.2
> |-- WiFi @ 2.0.0
> |-- FS @ 2.0.0
> |-- Update @ 2.0.0
> |-- ESPAsyncWebServer-esphome @ 2.1.0
> |   |-- AsyncTCP-esphome @ 1.2.2
> |-- DNSServer @ 2.0.0
> |-- ESPmDNS @ 2.0.0
> |-- noise-c @ 0.1.4
> |   |-- libsodium @ 1.10018.1
> Compiling /data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/ld2410/ld2410.cpp.o
> Compiling /data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/ld2410/ld2410_call.cpp.o
> Compiling /data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/number/number.cpp.o
> Compiling /data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/number/number_call.cpp.o
> In file included from src/esphome/components/ld2410/ld2410_call.cpp:2:
> src/esphome/components/ld2410/ld2410.h: In lambda function:
> src/esphome/components/ld2410/ld2410.h:233:11: error: 'class esphome::ld2410::LD2410Component' has no member named 'set_light_control_'; did you mean 'get_light_control_'?
>      this->set_light_control_();
>            ^~~~~~~~~~~~~~~~~~
> src/esphome/components/ld2410/ld2410.h:149:7: note: in definition of macro 'SUB_LAMBDA_NUMBER'
>        cb; \
>        ^~
> In file included from src/esphome/components/ld2410/ld2410.cpp:1:
> src/esphome/components/ld2410/ld2410.h: In lambda function:
> src/esphome/components/ld2410/ld2410.h:233:11: error: 'class esphome::ld2410::LD2410Component' has no member named 'set_light_control_'; did you mean 'get_light_control_'?
>      this->set_light_control_();
>            ^~~~~~~~~~~~~~~~~~
> src/esphome/components/ld2410/ld2410.h:149:7: note: in definition of macro 'SUB_LAMBDA_NUMBER'
>        cb; \
>        ^~
> *** [/data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/ld2410/ld2410_call.cpp.o] Error 1
> *** [/data/ld2410-test/.pioenvs/ld2410-test/src/esphome/components/ld2410/ld2410.cpp.o] Error 1
> ========================== [FAILED] Took 3.59 seconds ==========================
> ```
> 
> Reading the code It seems to be directly related to the missing select definition.
> 
> I'm a bit clueless but I guess the problem might be rather obvious. Whats your thoughts @regevbr?

To run this you must use esphome dev from the last 2 days or so, as it relies on code (select) that was only added to the dev branch 2 days ago. If you are using HA Addons, you need to uninstall and reinstall the dev version to get it to download the latest version

2023-03-28 20:35 UTC, lienbacher commented
ohhhh! thanks for the quick response!

2023-03-29 08:16 UTC, nibblerrick commented
Hi again,
the component runs totally stable on my side!
One question: is it possible to configure two ld2410 on one ESP and if yes, how would the configuration code look like?

2023-03-29 08:38 UTC, regevbr commented
> Hi again, the component runs totally stable on my side! One question: is it possible to configure two ld2410 on one ESP and if yes, how would the configuration code look like?

Glad to hear!

I will add it to the docs but this is an example:

```yaml
uart:
  - id: ld2410_uart_1
    tx_pin: GPIO17 // Your pin
    rx_pin: GPIO16 // Your pin
    baud_rate: 256000
    parity: NONE
    stop_bits: 1
  - id: ld2410_uart_2
    tx_pin: GPIO17 // Your pin
    rx_pin: GPIO16 // Your pin
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

ld2410:
  - uart_id: ld2410_uart_1
    throttle: 1500ms
    id: ld2410_comp_1
  - uart_id: ld2410_uart_2
    throttle: 1500ms
    id: ld2410_comp_2

select:
  - platform: ld2410
    ld2410_id: ld2410_comp_1
    distance_resolution:
      name: distance resolution 1
  - platform: ld2410
    ld2410_id: ld2410_comp_2
    distance_resolution:
      name: distance resolution 2
```

I would appreciate it if you can let us know here if that works

2023-03-29 08:57 UTC, regevbr commented
> ```yaml
> id
> ```

I updated the docs so it will be more clear on how to use multiple devices, and fixed a minor bug in id validation of the automation

2023-03-29 09:07 UTC, lienbacher commented
Just fyi, this integration of the LD2140 works absolutely marvelously! I was able to install a sensor in a rather tight room and managed to fine tune the parameters perfectly using engineering mode and home assistant. Doing that without engineering mode and live updates would have been a true pita! Thanks a lot!

2023-03-29 19:58 UTC, sebastiansson commented
First of all very good job @regevbr!

I'm trying to wrap my head around the gate concept. I'm trying to trigger a still detection but seem to not understand what makes it not trigger. The still energy for g2 & g3 exceeds the gate value (6%). The light threshold is set to off and i've tried all combinations (almost).

I'm using the HLK-LD2410 (non Bluetooth version). I saw that Andreas Spiees had some troubles as well -> https://www.youtube.com/watch?v=dAzHXpP3FcI&t=617s can it be related? His conclusion was to use the sensor values instead of relying on the output-pin to be triggered. Is that how you use it?


https://user-images.githubusercontent.com/3044878/228653182-37744f6c-72b4-4db7-8a2b-78c46f9eba30.mov

2023-03-29 20:05 UTC, clinta commented
> First of all very good job @regevbr!
> 
> I'm trying to wrap my head around the gate concept. I'm trying to trigger a still detection but seem to not understand what makes it not trigger. The still energy for g2 & g3 exceeds the gate value (6%). The light threshold is set to off and i've tried all combinations (almost).
> 
> I'm using the HLK-LD2410 (non Bluetooth version). I saw that Andreas Spiees had some troubles as well -> https://www.youtube.com/watch?v=dAzHXpP3FcI&t=617s can it be related? His conclusion was to use the sensor values instead of relying on the output-pin to be triggered. Is that how you use it?

In my testing, it seems that the still sensor is only triggered after the motion sensor. When I realized this, I actually appreciate that it works that way, because it makes sense for my use case. Someone will walk into a room, triggering the motion sensor, then stay in the room keeping the still presence active until they leave the room.

But if the room is empty and the still sensor goes off, it will take motion again to reactivate presence. So some small incidental movement in the room is unlikely to falsely trigger a presence event.

2023-03-29 20:09 UTC, nibblerrick commented
> I would appreciate it if you can let us know here if that works

Hi, thanks very much. It works as long as my cabling for the second ld2410 is stable (still waiting for my 1,25mm plugs...)
Only in home assistant the control bluetooth, engineering mode, factory reset, light threshold, and the move thresholds end up in "configuration" instead of "control element" and the move/still energy in diagnose instead of sensors.
I named all the sensors of the second ld2410 as "... 2".
I don't know exactly if control element is the correct heading, it's "Steuerelemente" in german.

2023-03-29 20:11 UTC, regevbr commented
> > First of all very good job @regevbr!
> > I'm trying to wrap my head around the gate concept. I'm trying to trigger a still detection but seem to not understand what makes it not trigger. The still energy for g2 & g3 exceeds the gate value (6%). The light threshold is set to off and i've tried all combinations (almost).
> > I'm using the HLK-LD2410 (non Bluetooth version). I saw that Andreas Spiees had some troubles as well -> https://www.youtube.com/watch?v=dAzHXpP3FcI&t=617s can it be related? His conclusion was to use the sensor values instead of relying on the output-pin to be triggered. Is that how you use it?
> 
> In my testing, it seems that the still sensor is only triggered after the motion sensor. When I realized this, I actually appreciate that it works that way, because it makes sense for my use case. Someone will walk into a room, triggering the motion sensor, then stay in the room keeping the still presence active until they leave the room.
> 
> But if the room is empty and the still sensor goes off, it will take motion again to reactivate presence. So some small incidental movement in the room is unlikely to falsely trigger a presence event.

Also the refrence link you posted suggests to use the values sent by the sensor but your video shows that the still sensor doesn't get triggered as well, so it seems that the observation of @clinta might be true, though i didn't test it myself

2023-03-29 20:14 UTC, regevbr commented
> > I would appreciate it if you can let us know here if that works
> 
> Hi, thanks very much. It works as long as my cabling for the second ld2410 is stable (still waiting for my 1,25mm plugs...) Only in home assistant the control bluetooth, engineering mode, factory reset, light threshold, and the move thresholds end up in "configuration" instead of "control element" and the move/still energy in diagnose instead of sensors. I named all the sensors of the second ld2410 as "... 2". I don't know exactly if control element is the correct heading, it's "Steuerelemente" in german. 

Great to hear it works! 
The categories can be be changed in the yaml if you don't like the defaults

2023-03-29 20:21 UTC, clinta commented
Once this is accepted I'll do a PR on the docs to add some of the additional things I've discovered in my testing of these sensors. An additional interesting thing I've discovered with the 4 sensors I have in place now, they seem to operate just fine powered by 3.1v. YMMV, and this may only work on the batches I got, but so far I've not had to add 5v to my projects to power these sensors.

2023-03-29 20:24 UTC, regevbr commented
> Once this is accepted I'll do a PR on the docs to add some of the additional things I've discovered in my testing of these sensors. An additional interesting thing I've discovered with the 4 sensors I have in place now, they seem to operate just fine powered by 3.1v. YMMV, and this may only work on the batches I got, but so far I've not had to add 5v to my projects to power these sensors.

Cool, but you can do the PR right now to my branch and then it will all be released together

2023-03-29 20:32 UTC, sebastiansson commented
> > First of all very good job @regevbr!
> 
> > 
> 
> > I'm trying to wrap my head around the gate concept. I'm trying to trigger a still detection but seem to not understand what makes it not trigger. The still energy for g2 & g3 exceeds the gate value (6%). The light threshold is set to off and i've tried all combinations (almost).
> 
> > 
> 
> > I'm using the HLK-LD2410 (non Bluetooth version). I saw that Andreas Spiees had some troubles as well -> https://www.youtube.com/watch?v=dAzHXpP3FcI&t=617s can it be related? His conclusion was to use the sensor values instead of relying on the output-pin to be triggered. Is that how you use it?
> 
> 
> 
> In my testing, it seems that the still sensor is only triggered after the motion sensor. When I realized this, I actually appreciate that it works that way, because it makes sense for my use case. Someone will walk into a room, triggering the motion sensor, then stay in the room keeping the still presence active until they leave the room.
> 
> 
> 
> But if the room is empty and the still sensor goes clear, it will take motion again to reactivate presence. So some small incidental movement in the room is unlikely to falsely trigger a presence event.

Lucky you! I have a PIR which turns on the lights, I only use this sensor to turn off the lights when someone leaves the room. I can't really have this sensor pointing at the door and the shower at the same time. And the PIR is faster and "never" gives false positives.

But I have the values so I guess I could use them manually somehow. But yeah it would be nice to in a future version not to be dependent on motion. It's confusing as hell how it works now IMO. That the still needs the motion to trigger first. But is it just motion has to pass any gate for still to be able to trigger? Or is it the motion gate for that specific distance need to trigger for still to work?

2023-03-29 20:35 UTC, nibblerrick commented
> The categories can be be changed in the yaml if you don't like the defaults

Ok, but here I didn't change the defaults and the entities of the second component are in other categories as the ones for the first component.
It's not a problem, I just wanted to let you know if the mapping should be the same for the second component.
As it is only an assignment in the ha-backend overview it is totally not a problem.

2023-03-29 20:38 UTC, regevbr commented
> > The categories can be be changed in the yaml if you don't like the defaults
> 
> Ok, but here I didn't change the defaults and the entities of the second component are in other categories as the ones for the first component. It's not a problem, I just wanted to let you know if the mapping should be the same for the second component. As it is only an assignment in the ha-backend overview it is totally not a problem.

Oh that is very strange indeed. Can you please try to remove all related devices from HA and then reboot the board to trigger re-adding the devices and let me know if that solves it? I'm thinking that some sensors are stuck with the old defaults as it was just recently changed

2023-03-29 20:50 UTC, clinta commented
> > > First of all very good job @regevbr!
> > 
> > 
> > > 
> > 
> > 
> > > I'm trying to wrap my head around the gate concept. I'm trying to trigger a still detection but seem to not understand what makes it not trigger. The still energy for g2 & g3 exceeds the gate value (6%). The light threshold is set to off and i've tried all combinations (almost).
> > 
> > 
> > > 
> > 
> > 
> > > I'm using the HLK-LD2410 (non Bluetooth version). I saw that Andreas Spiees had some troubles as well -> https://www.youtube.com/watch?v=dAzHXpP3FcI&t=617s can it be related? His conclusion was to use the sensor values instead of relying on the output-pin to be triggered. Is that how you use it?
> > 
> > 
> > In my testing, it seems that the still sensor is only triggered after the motion sensor. When I realized this, I actually appreciate that it works that way, because it makes sense for my use case. Someone will walk into a room, triggering the motion sensor, then stay in the room keeping the still presence active until they leave the room.
> > But if the room is empty and the still sensor goes clear, it will take motion again to reactivate presence. So some small incidental movement in the room is unlikely to falsely trigger a presence event.
> 
> Lucky you! I have a PIR which turns on the lights, I only use this sensor to turn off the lights when someone leaves the room. I can't really have this sensor pointing at the door and the shower at the same time. And the PIR is faster and "never" gives false positives.
> 
> But I have the values so I guess I could use them manually somehow. But yeah it would be nice to in a future version not to be dependent on motion. It's confusing as hell how it works now IMO. That the still needs the motion to trigger first. But is it just motion has to pass any gate for still to be able to trigger? Or is it the motion gate for that specific distance need to trigger for still to work?

I think motion in any gate will allow still presence to be detected. It's just once still is cleared, nothing will happen until motion is detected. At low sensitivities this sensor can detect motion through certain walls and doors. I have tuned mine so that it turns on the light when I'm outside the door about to open it. You may be able to set the motion thresholds low enough that you're almost always guaranteed to get motion events before you want still detection.

2023-03-30 06:42 UTC, nibblerrick commented
> I'm thinking that some sensors are stuck with the old defaults as it was just recently changed

Removing and readding cleared it up, now they different sensors are grouped correctly in their groups!
Thanks again :-)

2023-04-06 16:44 UTC, sebcaps approved these changes

2023-04-07 10:29 UTC, flacco54 commented
This is so good! I have been using the LD2410 sensor for a few months now and am loving it, but I am ready to fine tune the thresholds. I would love to use this, but when I use your code I get the following error:

`ERROR Unable to load component ld2410.select:`

Any ideas on what I have done wrong?

2023-04-07 11:28 UTC, lienbacher commented
> This is so good! I have been using the LD2410 sensor for a few months now and am loving it, but I am ready to fine tune the thresholds. I would love to use this, but when I use your code I get the following error:
> 
> 
> 
> `ERROR Unable to load component ld2410.select:`
> 
> 
> 
> Any ideas on what I have done wrong?

See my same question above. You need ti run the dev-version of esphome as it contains some stuff necessary for this pr.

2023-04-07 23:35 UTC, flacco54 commented
> > This is so good! I have been using the LD2410 sensor for a few months now and am loving it, but I am ready to fine tune the thresholds. I would love to use this, but when I use your code I get the following error:
> > `ERROR Unable to load component ld2410.select:`
> > Any ideas on what I have done wrong?
> 
> See my same question above. You need ti run the dev-version of esphome as it contains some stuff necessary for this pr.

Thanks. I did search how to do that last night but couldn't figure it out. With a good sleep and fresh look, I have figured it out (even ChatGPT couldn't get it right! I run the AddOn).

2023-04-10 04:28 UTC, Regressor commented
After reading the datasheet, I realized that these "gates" are actually distance ranges. So shouldn't they be renamed to avoid confusing people? I.e. "g0 move threshold" -> "Move at 0 - 0.75 m threshold" an so on?

2023-04-10 05:45 UTC, regevbr commented
> After reading the datasheet, I realized that these "gates" are actually distance ranges. So shouldn't they be renamed to avoid confusing people? I.e. "g0 move threshold" -> "Move at 0 - 0.75 m threshold" an so on?

Gate distance can be changed to 0.2 meter so no

2023-04-11 15:42 UTC, rodpayne commented
Excellent update!  

Much like @nibblerrick, in the ESPHome LD2410 prod version, I was getting constant disconnect/reconnects whenever I had sensors defined.  **That is gone with your version.**

```
[12:51:31][W][api.connection:083]: Home Assistant 2023.3.6 (172.19.54.77): Connection closed
[12:51:31][D][api.connection:920]: Home Assistant 2023.3.6 (172.19.54.77): Connected successfully
[12:51:32][D][api:102]: Accepted 172.19.54.77
[12:51:32][W][api.connection:083]: Home Assistant 2023.3.6 (172.19.54.77): Connection closed
[12:51:32][D][sensor:126]: 'Moving Distance': Sending state 70.00000 cm with 0 decimals of accuracy
[12:51:32][D][sensor:126]: 'Still Distance': Sending state 65.00000 cm with 0 decimals of accuracy
[12:51:32][D][sensor:126]: 'Detection Distance': Sending state 37.00000 cm with 0 decimals of accuracy
[12:51:32][D][api.connection:920]: Home Assistant 2023.3.6 (172.19.54.77): Connected successfully
[12:51:33][D][api:102]: Accepted 172.19.54.77
[12:51:33][W][api.connection:081]: Home Assistant 2023.3.6 (172.19.54.77): Connection reset
```

2023-04-11 16:20 UTC, rodpayne commented
Add configuration flow abilites to the **ld2140** component --> **ld2410**
(LD2140 is a dishwasher.)

2023-04-11 17:33 UTC, regevbr commented
> Add configuration flow abilites to the **ld2140** component --> **ld2410** (LD2140 is a dishwasher.)

Thanks updated

2023-04-24 18:45 UTC, lienbacher commented
> Please leave all of the removed config items in the main component schema, but change the validation to `cv.invalid(...)` with a message telling users to check documentation to see how it should be now.
> 
> This is so that they know the key is removed, otherwise ESPHome just fails on an invalid key which is not nice.

I'd love to help getting this merged and jesses review makes a lot of sense. could I help make these changes to unblock this merge? @regevbr @jesserockz?

2023-04-24 18:47 UTC, rbnayax commented
> > Please leave all of the removed config items in the main component schema, but change the validation to `cv.invalid(...)` with a message telling users to check documentation to see how it should be now.
> > This is so that they know the key is removed, otherwise ESPHome just fails on an invalid key which is not nice.
> 
> I'd love to help getting this merged and jesses review makes a lot of sense. could I help make these changes to unblock this merge? @regevbr @jesserockz?

Thanks but everything was handled already, we are waiting for the maintainers to review as well

2023-04-24 18:49 UTC, regevbr commented
> > Please leave all of the removed config items in the main component schema, but change the validation to `cv.invalid(...)` with a message telling users to check documentation to see how it should be now.
> > 
> > This is so that they know the key is removed, otherwise ESPHome just fails on an invalid key which is not nice.
> 
> I'd love to help getting this merged and jesses review makes a lot of sense. could I help make these changes to unblock this merge? @regevbr @jesserockz?

Thanks but everything was handled. Waiting for maintainers review

2023-04-27 14:19 UTC, formatBCE commented
@jesserockz i guess you requested changes, and changes been done - but this PR is on hold now for couple months, and it won't be merged without your re-approval. Could you check please?

2023-04-27 17:00 UTC, Elpollocurioso commented
Estoy siguiendo todos sus procesos con este módulo yo dispongo de varios ld2410b, versión con bluetooth  y mi interés es poderlo integrarlo como un sensor más bluetooth atraves de un esp32 tracert ya operativo. Como integrarlo con .yaml del esp32 para lograrlo???? Gracias por su tiempo.

2023-04-28 14:11 UTC, markmghali commented
This looks amazing how do we get this merged? Thank you for the hard work

2023-04-28 21:25 UTC, formatBCE approved these changes

2023-05-03 04:06 UTC, rajil commented
There is an extra gpio,
```
  - platform: gpio
    pin: GPIO13  // Your pin
    name: gpio out pin presence
    device_class: presence
```
which is not present in old [code](https://esphome.io/components/sensor/ld2410.html#id2). Is this gpio optional?

2023-05-03 13:14 UTC, formatBCE commented
I love it in Github, when person can request changes to the code, and go offline for months, effectively blocking the process.

2023-05-03 13:17 UTC, regevbr commented
> I love it in Github, when person can request changes to the code, and go offline for months, effectively blocking the process.

I don't like it either but the project is open source and you don't pay for it so you can't complain and demand anything from the maintainers. This kind of attitude is not helping in any way in the open source community :-( 😇

2023-05-03 13:19 UTC, lienbacher commented
> I love it in Github, when person can request changes to the code, and go offline for months, effectively blocking the process.

except that @jesserockz is actually very active in this project and one main reason why esphome is as awesome as it is.  I'm sure has a good reason why this is delayed. 

Also keep in mind that there is no actual problem in using this with a tiny bit of reading. There is no significant disadvantage with this PR not being merged yet.

2023-05-03 13:25 UTC, formatBCE commented
Yeah, sorry for my passive aggression.

2023-05-04 17:01 UTC, rajil commented
I want the engineering mode to be always on. Unfortunately, the restore_mode doesnt have any effect.

```
switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
      inverted: true
      restore_mode: ALWAYS_ON
```

Also i had to invert the switch to get the UI to match the switch state.

2023-05-04 17:37 UTC, regevbr commented
> I want the engineering mode to be always on. Unfortunately, the restore_mode doesnt have any effect.
> 
> ```
> 
> esp32:
>   board: esp32-c3-devkitm-1
> 
> switch:
>   - platform: ld2410
>     engineering_mode:
>       name: "engineering mode"
>       inverted: true
>       restore_mode: ALWAYS_ON
> ```
> 
> Also i had to invert the switch to get the UI to match the switch state.

restore_mode as far as I understand is not what you need, please remove it and add a HA automation that will turn it on once it detects that it is off

2023-05-10 16:23 UTC, descipher commented
Love the PR, FYI you could make it availble for wider testing via the "external component" method or if you have no objections I can do that on my git account.

2023-05-10 16:26 UTC, regevbr commented
> Love the PR, FYI you could make it availble for wider testing via the "external component" method or if you have no objections I can do that on my git account.

what do you mean? You can use external component already see the code example in the PR description

2023-05-10 16:34 UTC, descipher commented
LOL, first line .. never mind.

2023-05-10 17:26 UTC, descipher commented
Could add it as a LD2410B component and avoid the "breaking" issues.

2023-05-10 21:18 UTC, descipher commented
Please note:

I have been coding for the LD2420 for a few weeks now and I am sceptical of the accuracy with the supplied docs from Hi-Link (They are translated with a tool). I have confirmed this by reverse engineering their provided config tools actual command output values. There are errors within the provided protocol command ref for the LD2420.  I have not done this check for the LD2410 at this time but I suspect the same could be true for it here.

Here we are restricting the move and sens gate range from 2 to 8, however this may be wrong for the move gate range. Likely to be 1-8, I know that the noise levels can be an issue for gate 0 so they seem to avoid it in all cases. Not that this is a critical thing, since really, who needs to restrict it to less than 2, but this note just gives you some insight to what I have observed from a doc accuracy point of view.
   
![image](https://github.com/esphome/esphome/assets/10734527/1b5de935-bef6-49bf-8bf0-cb2923ac9970)

The doc command ref doc initially specs this:

page 5

- farthest detection distance

Set the farthest detectable distance, only human targets that appear within this farthest distance
will be detected and output the result.
Set in units of distance gates, and each distance gate is 0.75m.
Including the farthest door for motion detection and the farthest door for static detection, the
setting **range is 1 to 8.** For example, if the farthest door is set to 2, only if there is a human body
within 1.5m will it effectively detect and output the result.

later it specs:

page 8

This command sets the radar's maximum detection range gate (moving & stationary) **(configuration
range 2~8)**, and the parameter of unmanned duration (configuration range 0~65535 seconds). For
specific parameters, please refer to Table 5- 5. This configuration value is not lost when power off.

This does not conform to the initial spec. You may want to verify this with the LD2410 to see if accurate.


Also the pre refactored code you are fixing/improving does not wait for an ack back from the module. I think this is a issue that may need to be addressed. I have locked up the LD2420 by aggresivly flooding it with commands while writing the initail code and have since coded it to wait and also to never write to flash if the config is unchanged. The only remidiation after the lockup event is a power cycle. Not a good thing. I have sent the Hi-Link engineers of the module a heads up on that issue.

Thanks for your PR!

2023-05-11 15:10 UTC, descipher commented
I have started some basic testing with the updated code. There are a couple of items that need to be confirmed by others. I am running the LD2410 version 1.07.22082218 and an esp32 WEB UI to observe it.

I see an inconsistant move energy state of 0% when both the move detection and move distance states go positive. This does not make sence. We should have move energy fluctuation when this occurs. I do see move energy infrequently hit 100% but no other value is observed, Possibly we are parsing the wrong inner frame byte for that data element. The still energy appears correct and fluctuates as expected.

Note: when coding the LD2420 I noticed it may be good to setup a low value publish filter to block still energy sends below a certain level e.g. below 10%. This would be optional to clean up unwanted noise sends.

Factory reset has minor issues with some values on firmware version 1.07.22082218
(this module being an LD2410 thus no bluetooth)
09:08:21 | [D] | [text_sensor:064] | 'presence sensor mac address': Sending state 'unknown'
When bluetooth is off it should probably not send state for it.

I set all thresholds to 45 and observed the reset result:

The web UI value is not always refreshed on change in the web UI, a manual refresh is required sometimes not sure why yet. It does work on the inititial open.
Not a issue per say, just a note:

factory reset log output:

[09:32:21][D][text_sensor:064]: 'presence sensor version': Sending state '1.07.22082218'
[09:32:21][D][text_sensor:064]: 'presence sensor mac address': Sending state 'unknown'
[09:32:21][D][number:012]: 'g0 move threshold': Sending state 50.000000
[09:32:21][D][number:012]: 'g1 move threshold': Sending state 50.000000
[09:32:22][D][number:012]: 'g2 move threshold': Sending state 40.000000
[09:32:22][D][number:012]: 'g3 move threshold': Sending state 30.000000
[09:32:22][D][number:012]: 'g4 move threshold': Sending state 20.000000
[09:32:23][D][number:012]: 'g5 move threshold': Sending state 15.000000
[09:32:23][D][number:012]: 'g6 move threshold': Sending state 15.000000
[09:32:23][D][number:012]: 'g7 move threshold': Sending state 15.000000
[09:32:23][D][number:012]: 'g8 move threshold': Sending state 15.000000
[09:32:24][D][number:012]: 'g2 still threshold': Sending state 40.000000
[09:32:24][D][number:012]: 'g3 still threshold': Sending state 40.000000
[09:32:24][D][number:012]: 'g4 still threshold': Sending state 30.000000
[09:32:24][D][number:012]: 'g5 still threshold': Sending state 30.000000
[09:32:25][D][number:012]: 'g6 still threshold': Sending state 20.000000
[09:32:25][D][number:012]: 'g7 still threshold': Sending state 20.000000
[09:32:25][D][number:012]: 'g8 still threshold': Sending state 20.000000
[09:32:25][E][ld2410:332]: Error with last command : incorrect length

We are missing g0 and g1 still sets due to the "doc spec indicating not possible obviously"
If these gate are fixed we could read the value and set the display appropriately.
(Maybe a translation problem but I a sure there is a value for these) 

The incorrect length is possibly overloading the receive buffer, I found that this was an issue on the LD2420 and Hi-Link decided to change the default baud to 115200, could be related,  
There is a need for error handling and ack wait/timeouts at some point, did this on the LD2420 but not finished yet. 

UI result after refresh:

![image](https://github.com/esphome/esphome/assets/10734527/1b67b0e8-2443-4c73-8a76-3f359f18174f)

Will do more later.
Again thanks for your work.

2023-05-12 11:59 UTC, regevbr commented
@descipher thanks for all the input, although I'm very confused about the call to action here.
- About waiting for ack - this is currently not planned, and doesn't have too many issues with currently, but if you can contribute it will be awsome (in a PR to my repo)
- About the threshold gate starting from 1 and not 2, I can check that, but as you said - not that critical (i'd rather make this "fix" after the PR will be finally merged)
- About the error - `Error with last command : incorrect length`, it has something do to with the ack response, and I can't see how that can affect the things you talk about
- about missing g0 and g1 - in the code we are handling them... Maybe you don't see it in the logs since the values remain the same so it doesn't need to republish their state?

I can't detect any buffer overloading happening, can you demonstrate such a case backed up by HEX logs of the buffers?

2023-05-12 20:22 UTC, descipher commented
_About the threshold gate starting from 1 and not 2, I can check that, but as you said - not that critical (i'd rather make this "fix" after the PR will be finally merged)_

The value is left unchanged in the WEB UI from it last setting, so what is the default and did it really set one? Is gate 0 & 1 still sensitivity adjustable or not. The UI leads us to think it is adjustable but if we do not read it we just don't know for sure. This is why I suggest that change here or in the future.  

_About waiting for ack - this is currently not planned, and doesn't have too many issues with currently, but if you can contribute it will be awsome (in a PR to my repo)_

I am going on the bases of the LD2420 where the engineers spec the following:

"Notice:
1. The maximum data length of a single serial port command does not exceed 64 bytes (the size is subject to the actual situation, and each platform may be different. When the upper computer sends the start command, the result returned by the lower computer includes the buffer size of the command communication) , so when reading and writing multiple registers, if it exceeds 64 bytes, it needs to be divided into multiple commands and issued."

When it exceeds 64 bytes you will usually see the length error because the previous code does not really handle errors, it checks for some conditions at best, one check is the length field and if it does not match the actual received bytes you get the length error even if it's just junk in the buffer. The ack reply does provide an error return code which has no documented description but any value other than 0 needs a resend at minimum.   

In order handle this receive buffer overflow issue we have to wait for the previous ack before sending more data otherwise it can overload the receive buffer. This is specific to the LD2420 but they use the same mmWave radar SOC so I suspect its a issue with both. SOC = S3KM111O or S3KM111L (L is the low power version)  

The command structure of the LD2410 is simpler than the LD2420, currently there are no docs for the LD2420's output stream data or it's output field descriptions, so it a different beast to code for. They only output ascii "ON" "OFF" and "Range nnn"

As far as a PR submission, this is a fairly involved change and would require all commands to go through a single send function or wrapper that processes the receive data. The current code is not structured that way. All sends are independent and the loop() process checks for any received data continually so it can consume it at random in the back ground. I could look at using a received status variable, but with async capability each send would need a unique ID so I'm not sure that would work well in this case. It think it needs to be sync based. Also there are multiple modes where we receive different data streams and then the config mode with command send/acks. 

I do not recommend we muck to much with the work you have already done. It works far better than the first release for the LD2410. The information shared here is to have more knowledge for the next refactor/fix etc.

As for proof of overflow, I can certainly do that if you like.

2023-05-13 05:13 UTC, descipher commented
@regevbr 

I dumped the Rx stream to capture the buffer overrun issue.
Here you can observe a partial frame in the Rx buffer, this is a issue when the receive loop was late to process the incomming data. This issue also  occurs when we don't wait for the acks to be handled syncronously. The serial available loop is unrelable for this task. In this case the receiver was overrun. The LD2410 is replying faster than we can process it. The loop() is also receiving the incomming data stream and this further complicates the command handling. It may be possible to reduce some of the overruns by lowering the baud rate. With the LD2420 code I setup a serial wait loop in the send command function which immediately waits for the ack and retries after a timeout. It ignores the stream data if present while waiting for the command frame. On the LD2420 they have a command to set the stream send interval which help too. I dont see the same command on the Ld2410.
I will look at the possibility of use a simmilar method for the LD2410 but lets not do that in the current PR. It's not frequent enough to justify holding up a commit besides it was there before your updates. 
```
[22:44:15][C][ld2410:066]:     Unit of Measurement: '%'
[22:44:15][C][ld2410:066]:     Device Class: 'signal_strength'
[22:44:16][C][ld2410:069]:   Throttle_ : 1500ms
[22:44:16][C][ld2410:070]:   MAC Address : unknown
[22:44:16][C][ld2410:071]:   Firmware Version : 1.07.22082218
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.06.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][sensor:110]: 'Still Energy (%)': Sending state 6.00000 % with 0 decimals of accuracy
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.07.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.07.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.07.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.07.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.07.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.07.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.07.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.07.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.07.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.07.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.07.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:501]: Rx: 2D.28.28.1E.1E.14.14.14.1D.02.04.03.02.01 (14)
[22:44:16][E][ld2410:336]: Error with last command : incorrect Header
[22:44:16][D][ld2410:501]: Rx: FD.FC.FB.FA.04.00.FE.01.00.00.04.03.02.01 (14)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.08.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.08.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.08.00.00.55.00.F8.F7.F6.F5 (23)
[22:44:16][C][captive_portal:088]: Captive Portal:
[22:44:16][C][web_server:151]: Web Server:
[22:44:16][C][web_server:152]:   Address: motion-1.local:80

[22:53:49][D][ld2410:501]: Rx: FD.FC.FB.FA.08.00.FF.01.00.00.01.00.40.00.04.03.02.01 (18)
[22:53:49][D][ld2410:501]: Rx: FD.FC.FB.FA.0C.00.A0.01.00.00.00.00.07.01.18.22.08.22.04.03.02.01 (22)
[22:53:49][D][text_sensor:064]: 'presence sensor version': Sending state '1.07.22082218'
[22:53:50][D][ld2410:501]: Rx: FD.FC.FB.FA.0A.00.A5.01.00.00.08.05.04.03.02.01 (16)
[22:53:50][D][ld2410:501]: Rx: FD.FC.FB.FA.0A.00.A5.01.00.00.08.05.04.03.02.01.04.03.02.01 (20)
[22:53:50][D][text_sensor:064]: 'presence sensor mac address': Sending state 'unknown'
[22:53:50][D][ld2410:501]: Rx: FD.FC.FB.FA.06.00.AB.01.00.00.00.00.04.03.02.01 (16)
[22:53:50][D][ld2410:501]: Rx: FD.FC.FB.FA.1C.00.61.01.00.00.AA.08.08.08.32.32.28.1E.14.0F.0F.0F.0F.37.3D.28.28.1E.1E.14.14.14.05.00.04.03.02.01 (38)
[22:53:50][D][number:012]: 'g3 move threshold': Sending state 30.000000
[22:53:50][D][number:012]: 'g7 move threshold': Sending state 15.000000
[22:53:50][D][number:012]: 'g8 move threshold': Sending state 15.000000
[22:53:50][D][number:012]: 'g3 still threshold': Sending state 40.000000
[22:53:51][D][number:012]: 'g7 still threshold': Sending state 20.000000
[22:53:51][D][number:012]: 'g8 still threshold': Sending state 20.000000
[22:53:51][D][ld2410:501]: Rx: FD.FC.FB.FA.04.00.FE.01.00.00.04.03.02.01 (14)
[22:53:51][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.00.00.00.55.00.F8.F7.F6.F5 (23)
[22:53:51][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.00.00.00.55.00.F8.F7.F6.F5 (23)
[22:53:51][D][ld2410:501]: Rx: FD.FC.FB.FA.08.00.FF.01.00.00.01.00.40.00.04.03.02.01 (18)
[22:53:51][D][ld2410:501]: Rx: FD.FC.FB.FA.04.00.64.01.00.00.04.03.02.01 (14)
[22:53:51][D][ld2410:501]: Rx: FD.FC.FB.FA.1C.00.61.01.00.00.AA.08.08.08.32.32.28.1E.14.0F.0F.0F.0F.37.3D.28.28.1E.1E.14.14.14.05.00.04.03.02.01 (38)
[22:53:51][D][ld2410:501]: Rx: FD.FC.FB.FA.04.00.FE.01.00.00.04.03.02.01 (14)
[22:53:51][D][ld2410:501]: Rx: 01.FD.FC.FB.FA.04.00.FE.01.00.00.04.03.02.01 (15)
[22:53:51][E][ld2410:336]: Error with last command : incorrect Header
[22:53:51][D][ld2410:495]: Rx: F4.F3.F2.F1.0D.00.02.AA.00.00.00.00.00.00.00.00.00.55.00.F8.F7.F6.F5 (23)
```

2023-05-18 21:40 UTC, lollokara commented
Just installed on 3 esp8266, to replace the sensors alone that keeps dropping on the BLE i can't just thank enought the creator/mantainer of this. 
For now they are up and running without any issues.

2023-05-24 23:21 UTC, jesserockz requested changes
I have not done a full review, but I really don't like how much is stuffed into the main `ld2410.cpp` class/file and not using the classes for `button`/`select`/`number`/`switch` with callbacks to the parent to then do the required functions.
This makes it so much harder to understand what is doing what.

I know it is more work, but the end result is that its so much easier to maintain the code if we make internal changes.

For example `baud_rate` should have its own class:
```c++
class LD2410BaudRateSelect : public select::Select, public Parented<LD2410> {
  void control(const std::string &value) {
    this->parent_->set_baud_rate(value);
    this->publish_state(value);
  }
};

Where the parent function `set_baud_rate` can then take care of what it needs to do to change the baud rate.

2023-05-24 23:21 UTC, jesserockz commented on esphome/components/ld2410/button/__init__.py
> +        device_class=DEVICE_CLASS_UPDATE,
This is not what this device class is for.

2023-05-27 16:29 UTC, regevbr commented on esphome/components/ld2410/button/__init__.py
> +        device_class=DEVICE_CLASS_UPDATE,
removed

2023-05-27 16:31 UTC, regevbr commented
> I have not done a full review, but I really don't like how much is stuffed into the main `ld2410.cpp` class/file and not using the classes for `button`/`select`/`number`/`switch` with callbacks to the parent to then do the required functions. This makes it so much harder to understand what is doing what.
> 
> I know it is more work, but the end result is that its so much easier to maintain the code if we make internal changes.
> 
> For example `baud_rate` should have its own class:
> 
> ```c++
> class LD2410BaudRateSelect : public select::Select, public Parented<LD2410> {
>   void control(const std::string &value) {
>     this->parent_->set_baud_rate(value);
>     this->publish_state(value);
>   }
> };
> ```
> 
> Where the parent function `set_baud_rate` can then take care of what it needs to do to change the baud rate.

Done - much work indeed.

Notice that to use it you need to have select and switch components from my branch as well until #4897 and #4898 are merged

```yaml
external_components:
  source: github://regevbr/esphome@ld2410
  components: [ld2410, select, switch]
```

2023-06-23 17:32 UTC, papperone commented
any chance to have this PR merged any time soon? it's been here pending since 4 months :(

2023-06-23 17:43 UTC, raidnet-ms commented
Great work, hope to see this to be released for july!

2023-06-25 11:43 UTC, bilogic commented
is this something we can use over BLE proxy? Or does it require wiring the RX/TX to another ESP?

2023-06-25 12:25 UTC, descipher commented
> is this something we can use over BLE proxy? Or does it require wiring the RX/TX to another ESP?

You do not need any additional hardware to use this code. A single Esp device thats fast enough e.g. esp32 and the LD2410 with or without blue tooth will work. The blue tooth interface on the LD2410B can be used with the separate tuning app from hi-link.

2023-06-25 13:45 UTC, bilogic commented
> > is this something we can use over BLE proxy? Or does it require wiring the RX/TX to another ESP?
> 
> You do not need any additional hardware to use this code. A single Esp device thats fast enough e.g. esp32 and the LD2410 with or without blue tooth will work. The blue tooth interface on the LD2410B can be used with the separate tuning app from hi-link.

Hmm, I have 1 ESP32 running as a ESPHome BLE proxy. I have the LD2410 powered on 5v alone and they are talking to each other, i.e. I see my LD2410 in my home assistant.

Can I configure the LD2410 via home assistant or ESPHome without any hardware changes?

2023-06-25 15:34 UTC, descipher commented
I don’t think a shared esp blue tooth proxy would be a supported configuration with the blue tooth hi-link application. I believe you can only pair one link at a time on the LD module. The other option is to dedicate the esp locally via serial. You need a wifi connection in either case. With wifi you can tune without ble using a web server locally.

2023-06-26 23:53 UTC, energywave commented
Hope to see this PR merged soon. We're starting to use a custom made board with ESP32 and LD2410 in Italy, would be a perfect fit with this PR! :)

2023-06-27 01:26 UTC, bilogic commented
> I don’t think a shared esp blue tooth proxy would be a supported configuration with the blue tooth hi-link application. I believe you can only pair one link at a time on the LD module. The other option is to dedicate the esp locally via serial. You need a wifi connection in either case. With wifi you can tune without ble using a web server locally.

1. Hmm, the BLE proxy current can receive from multiple BLE senders (e.g. LD module) all at once right?
2. The android APK communicates with LD via BLE
3. I'm getting detailed numeric values in my HA via BLE (e.g. detection distance etc)
4. Taken together, it just seems to me that the device should be configurable via BLE too

2023-06-27 05:04 UTC, descipher commented
> > I don’t think a shared esp blue tooth proxy would be a supported configuration with the blue tooth hi-link application. I believe you can only pair one link at a time on the LD module. The other option is to dedicate the esp locally via serial. You need a wifi connection in either case. With wifi you can tune without ble using a web server locally.
> 
> 1. Hmm, the BLE proxy can receive from multiple BLE senders (e.g. LD module) all at once right?
> 2. The android APK configures the LD module via BLE
> 3. I'm getting detailed numeric values in my HA via BLE (e.g. detection distance etc)
> 4. Taken together, it just seems to me that the LD module can be configurable via the BLE proxy too

Maybe, but I really doubt it will be reliable. See https://esphome.io/components/bluetooth_proxy.html

2023-06-29 14:05 UTC, dwildstr commented
I've recently integrated this version into my own devices and have run into a confusing error which probably should be addressed before merging for release. If a configuration provides an ld2410 device but _does not_ have any `select` section in its YAML, there's a compile-time error in [number/light_threshold_number.cpp](https://github.com/regevbr/esphome/tree/ld2410/esphome/components/ld2410/number) where the symbol `set_light_out_control` is unrecognized. I believe the actual bug is in [ld2410.cpp](https://github.com/regevbr/esphome/blob/ld2410/esphome/components/ld2410/ld2410.cpp) and [ld2410.h](https://github.com/regevbr/esphome/blob/ld2410/esphome/components/ld2410/ld2410.h), where `set_light_out_control` is only defined if `USE_SELECT` is defined; if number components also depend on it then it needs to be active when `USE_NUMBER` is defined as well.

2023-06-29 15:55 UTC, regevbr commented
> I've recently integrated this version into my own devices and have run into a confusing error which probably should be addressed before merging for release. If a configuration provides an ld2410 device but _does not_ have any `select` section in its YAML, there's a compile-time error in [number/light_threshold_number.cpp](https://github.com/regevbr/esphome/tree/ld2410/esphome/components/ld2410/number) where the symbol `set_light_out_control` is unrecognized. I believe the actual bug is in [ld2410.cpp](https://github.com/regevbr/esphome/blob/ld2410/esphome/components/ld2410/ld2410.cpp) and [ld2410.h](https://github.com/regevbr/esphome/blob/ld2410/esphome/components/ld2410/ld2410.h), where `set_light_out_control` is only defined if `USE_SELECT` is defined; if number components also depend on it then it needs to be active when `USE_NUMBER` is defined as well.

If you define light_threshold number, you must also define out_pin_level and light_function selects, as they are an all-or-nothing feature (when you set one of them, you must set the others, API wise)

What will be ideal is to alert you on the matter when you edit your configuration. Sadly as far as I understand it, it can't be done, as we can't run schema validation across different entities (i.e. number and select here)
maybe @jesserockz can advise here on how to do it, and I will be more than happy to implement it.

2023-07-03 20:02 UTC, xaviergr commented
Any chance for this to get merged? What is the blocking point?

2023-07-10 06:12 UTC, Martin22 commented
I'd also like it to be merged. Why did it fall asleep like that, is there a problem with it?

2023-07-11 19:29 UTC, jsouth117 commented
Any chance this will make it into the July release? Really looking forward to these new features

2023-07-19 22:25 UTC, jollybully commented
Anything we can do to help this get merged?

2023-07-21 03:51 UTC, jesserockz commented
To all the people asking when a PR will be merged, I do not see any other comments from you since the last changes/commits were made confirming that you tested the new code and its working as expected.

2023-07-21 04:00 UTC, clinta commented
I've added one of these sensors into every light in my house and have been running this code without issue on 17 devices since April.

2023-07-21 04:32 UTC, nibblerrick commented
> confirming that you tested the new code and its working as expected.

If you like I can write daily that it just works, but I didn't want to spam the thread.
Jokes aside, besides my one problem earlier were the cause was this one esp32-board it runs since then without hiccups totally stable. I regularly updated my boards with ld2410 with the different esphome-dev-versions and this code and never had any problems.
HTH!

2023-07-21 09:28 UTC, ChrisThomas42 commented
Sorry I didn't realise that I should I have added feedback, again didn't want to spam thread.  I only have one sensor that has this code and it has been working as expected for a couple of weeks.  I have another 5 sensors waiting to be updated.  Would be good to clean up the configuration.

2023-07-21 10:14 UTC, xaviergr commented
> To all the people asking when a PR will be merged, I do not see any other comments from you since the last changes/commits were made confirming that you tested the new code and its working as expected.

I have been using this PR on 8 different esphome nodes to track presence on all of my rooms for about a month now. Compared to the current upstream version, functionally the presence tracking is the same, and I couldn't detect any regressions on this. The huge difference for this PR is the addition of letting the user to change all sorts of settings instead of relying on the bluetooth android application (which wastes power and pollutes the bluetooth network).

2023-07-21 10:37 UTC, lienbacher commented
Same. Works perfectly without hickups on multiple devices!

2023-07-26 16:47 UTC, ChrisThomas42 commented
I'm slowly moving my devices over to this PR in anticipation.  So far all is working VERY smoothly, so much easier than using the app and updating ESPHome code.  Overall much quicker to get to the settings required for each location.

2023-07-28 07:46 UTC, diabl0 commented
I have been on this PR for a week with 5 ESP+LD2410 (different dev-boards and setups), and experienced only two problems:

- After lowering the baud rate, LD2410 stopped working - even BT - I had to reset it (5 quick power cycles) - removed that dropdown to avoid accidents.  
- Due to the change of some sensor names, I now have some entities in HA that I don't know how to remove (just copied the suggested config without syncing names).

Other than that, it all works like a charm, and the possibility to quickly check and adjust thresholds without messing with config and reflashing is fantastic.

Thank You @regevbr

2023-07-28 07:51 UTC, regevbr commented
> I have been on this PR for a week with 5 ESP+LD2410 (different dev-boards and setups), and experienced only two problems:
> 
> * After lowering the baud rate, LD2410 stopped working - even BT - I had to reset it (5 quick power cycles) - removed that dropdown to avoid accidents.
> * Due to the change of some sensor names, I now have some entities in HA that I don't know how to remove (just copied the suggested config without syncing names).
> 
> Other than that, it all works like a charm, and the possibility to quickly check and adjust thresholds without messing with config and reflashing is fantastic.
> 
> Thank You @regevbr

About baud rate - please see the docs at https://deploy-preview-2680--esphome.netlify.app/components/sensor/ld2410 :

![image](https://github.com/esphome/esphome/assets/5775519/90764ae6-404d-4ce9-b8f4-940dc58657d3)

2023-07-28 17:55 UTC, xaviergr commented
>     * Due to the change of some sensor names, I now have some entities in HA that I don't know how to remove (just copied the suggested config without syncing names).

That's a problem with home assistant/esphome in general it has nothing to do with this particular PR.

2023-07-28 18:39 UTC, alexruffell commented
Love this PR. I have been using it for over a couple months on 5+ ESPs and have had no issues. It makes configuring things so much easier. Thanks @regevbr

2023-07-28 18:40 UTC, markmghali commented
Trying to figure out how to use this? Do I need the dev esphome add-on? Can
I run it together with the stable add-on?

On Fri, Jul 28, 2023, 1:39 PM alexruffell ***@***.***> wrote:

> Love this PR. I have been using it for over a couple months on 5+ ESPs and
> have had no issues. It makes configuring things so much easier. Thanks
> @regevbr <https://github.com/regevbr>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/4434#issuecomment-1656168728>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEENN4CS3IL27JV4THHBL4DXSQBOTANCNFSM6AAAAAAU26DYZ4>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-08-02 13:16 UTC, formatBCE commented
> Trying to figure out how to use this? Do I need the dev esphome add-on? Can I run it together with the stable add-on?
I just installed it from stable add-on, using YAML in description. Works great!

2023-08-02 19:38 UTC, simonyel commented
Thanks for this! I've loaded this into 8 room nodes and in my house. Works as intended and makes tuning so much easier!

2023-08-02 21:09 UTC, simonyel commented
What changes are still blocking the merge?

2023-08-04 15:25 UTC, markmghali commented
> > Trying to figure out how to use this? Do I need the dev esphome add-on? Can I run it together with the stable add-on?
> 
> I just installed it from stable add-on, using YAML in description. Works great!

Cool! I got it working on one of mine! now trying to find that graph card? It is harder to configure than the HLK BLE App as they have nice graphs.

2023-08-04 15:49 UTC, formatBCE commented
> > > Trying to figure out how to use this? Do I need the dev esphome add-on? Can I run it together with the stable add-on?
> > 
> > I just installed it from stable add-on, using YAML in description. Works great!
> 
> Cool! I got it working on one of mine! now trying to find that graph card? It is harder to configure than the HLK BLE App as they have nice graphs.

Couldn't find good card to display it in a way the app does. But what I do instead to calibrate, is placing sensor, then leaving it alone for couple hours in engineering mode, hanging in areas it shouldn't pick - and then seeing maximums on still/move history graphs, and set thresholds a bit higher than maximum.

2023-08-04 16:48 UTC, markmghali commented
> 
> Couldn't find good card to display it in a way the app does. But what I do instead to calibrate, is placing sensor, then leaving it alone for couple hours in engineering mode, hanging in areas it shouldn't pick - and then seeing maximums on still/move history graphs, and set thresholds a bit higher than maximum.

Thank you! I saw someone people talking about a custom card.

2023-08-05 07:24 UTC, athua commented
> > Couldn't find good card to display it in a way the app does. But what I do instead to calibrate, is placing sensor, then leaving it alone for couple hours in engineering mode, hanging in areas it shouldn't pick - and then seeing maximums on still/move history graphs, and set thresholds a bit higher than maximum.
> 
> Thank you! I saw someone people talking about a custom card.

Using the custom bar card, you can create a bar chart to give you a visual representation of the move or still levels:
`type: custom:bar-card
title: Move Energy
direction: up
columns: 9
height: 100px
width: 100%
positions:
  icon: 'off'
  name: none
  indicator: 'off'
  value: none
entities:
  - entity: sensor.g0_move_energy_lounge_room
  - entity: sensor.g1_move_energy_lounge_room
  - entity: sensor.g2_move_energy_lounge_room
  - entity: sensor.g3_move_energy_lounge_room
  - entity: sensor.g4_move_energy_lounge_room
  - entity: sensor.g5_move_energy_lounge_room
  - entity: sensor.g6_move_energy_lounge_room
  - entity: sensor.g7_move_energy_lounge_room
  - entity: sensor.g8_move_energy_lounge_room
`
![move-levles](https://github.com/esphome/esphome/assets/60054635/2cc3099d-1321-431a-b2e2-2e7c473e20e3)

2023-08-05 07:41 UTC, segator commented
tested and working! why is this not yet merge?

2023-08-06 23:40 UTC, jesserockz requested changes
Apologies for the delayed review.

There are quite a few changes required before this PR can be merged and I probably missed some below and some of the changes below need to be applied in multiple places.

Please join discord and start a thread for this PR if you wish to discuss changes in realtime as I cannot keep up with GitHub notifications.

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/ld2410.h
> +static const char *const TAG = "ld2410";
This goes in the cpp file please.

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/ld2410.h
> +static const std::map<uint8_t, std::string> OUT_PIN_LEVEL_INT_TO_ENUM{{0x0, "low"}, {0x01, "high"}};
Please use actual `enum` types for these

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/ld2410_call.cpp
I don't really see the need for this whole class. Just call `set_bluetooth_password` on the member itself.

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/number/__init__.py
> +    return config
```suggestion
```

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/number/__init__.py
> +        ),
```suggestion
        cv.Inclusive(CONF_TIMEOUT, "timeout"): number.number_schema(
            MaxDistanceTimeoutNumber,
            unit_of_measurement=UNIT_SECOND,
            entity_category=ENTITY_CATEGORY_CONFIG,
            icon="mdi:clock-time-eight-outline",
        ),
        cv.Inclusive(CONF_MAX_MOVE_DISTANCE_GATE, "timeout"): number.number_schema(
            MaxDistanceTimeoutNumber,
            device_class=DEVICE_CLASS_DISTANCE,
            entity_category=ENTITY_CATEGORY_CONFIG,
            icon="mdi:motion-sensor",
        ),
        cv.Inclusive(CONF_MAX_STILL_DISTANCE_GATE, "timeout"): number.number_schema(
            MaxDistanceTimeoutNumber,
            device_class=DEVICE_CLASS_DISTANCE,
            entity_category=ENTITY_CATEGORY_CONFIG,
            icon="mdi:motion-sensor-off",
        ),
```

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/number/__init__.py
> +    )
I think it would be preferable if the code was something like below (CONF changes and formatting still required) to produce yaml config like this:
```yaml
number:
  - platform: ld2410
    g0:
      move_threshold:
        name: ...
      still_threshold:
        name: ...
     g1:
       ...
```

```suggestion
CONFIG_SCHEMA = CONFIG_SCHEMA.extend({
    cv.Optional(f"g{x}): cv.Schema(
        {
            cv.Required("move_threshold"): number.number_schema(
                GateThresholdNumber,
                device_class=DEVICE_CLASS_SIGNAL_STRENGTH,
                unit_of_measurement=UNIT_PERCENT,
                entity_category=ENTITY_CATEGORY_CONFIG,
                icon="mdi:motion-sensor",
            ),
            cv.Required("still_threshold"): number.number_schema(
                GateThresholdNumber,
                device_class=DEVICE_CLASS_SIGNAL_STRENGTH,
                unit_of_measurement=UNIT_PERCENT,
                entity_category=ENTITY_CATEGORY_CONFIG,
                icon="mdi:motion-sensor-off",
            ),
        }
    ) for x in range(9)
})
```

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/number/__init__.py
> +CONFIG_SCHEMA = cv.All(CONFIG_SCHEMA, validate)
With the above changes, the `validate` function is not needed

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/number/__init__.py
> +        )
See #5181
Please apply to all places that use a similar syntax
```suggestion
    if timeout_config := config.get(CONF_TIMEOUT):
        n = await number.new_number(
            timeout_config, min_value=0, max_value=65535, step=1
        )
```

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/number/__init__.py
> +            cg.add(ld2410_component.set_gate_still_threshold_number(x, n))
```suggestion
        if g_config := config.get(f"g{x}"):
            move_config = g_config[CONF_MOVE_THRESHOLD]
            n = cg.new_Pvariable(move_config[CONF_ID], x)
            await number.register_number(
                n, move_config, min_value=0, max_value=100, step=1
            )
            await cg.register_parented(n, config[CONF_LD2410_ID])
            cg.add(ld2410_component.set_gate_move_threshold_number(x, n))

            still_config = g_config[CONF_STILL_THRESHOLD]
            n = cg.new_Pvariable(still_config[CONF_ID], x)
            await number.register_number(
                n, still_config, min_value=0, max_value=100, step=1
            )
            await cg.register_parented(n, config[CONF_LD2410_ID])
            cg.add(ld2410_component.set_gate_still_threshold_number(x, n))
```

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/select/__init__.py
> +    return config
```suggestion
```

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/ld2410.cpp
> +  }
This should just send the default value for that index of the data if the select/number is not defined in config. This is not a good reason to force the use of the extra selects.

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/ld2410.cpp
> +#ifdef USE_SELECT
You have made it impossible to use the selects without the numbers also being defined by nesting these ifdefs.

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/sensor.py
> +            unit_of_measurement=UNIT_LUX,
I agree with @sebcaps, this should not have a UNIT_LUX as it cannot be a lux value
```suggestion
```

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/sensor.py
> +            icon="mdi:signal-distance-variant",
Please use/add consts from `const.py` for icons.

2023-08-06 23:40 UTC, jesserockz commented on esphome/components/ld2410/sensor.py
> +    )
Same as my above change for `number` to group these

2023-08-07 02:18 UTC, serg0342 commented
When uploading this code to esp01s, there is a problem with flashing over the air. In most cases the firmware download hangs and causes the esp to reboot after a few minutes. This is a big problem if the esp is installed in a hard-to-reach place. Can this problem be fixed? There is no problem on esp32.
![Screenshot (1)](https://github.com/esphome/esphome/assets/136201400/c1e70e5d-76ca-432b-8a78-5a8f68f68d0a)

2023-08-07 07:51 UTC, regevbr commented on esphome/components/ld2410/ld2410.cpp
> +#ifdef USE_SELECT
This is a restriction by the api of the device. How do you suggest to address it?

2023-08-07 07:53 UTC, regevbr commented on esphome/components/ld2410/ld2410.cpp
> +  }
But this will mean that you will override the configured values without being aware of that. 
Example scenario - user defined some values using the mobile app, and then changed this value in HA, causing his defined values to be overridden.

2023-08-07 07:56 UTC, regevbr commented on esphome/components/ld2410/select/__init__.py
> +    return config
Same issue as in the rest of the API - when you set a value, you must provide to the device all the values in a single API call. If we use default values and do not enforce this validation, we will override configuration implicitly

2023-08-07 07:58 UTC, regevbr commented on esphome/components/ld2410/number/__init__.py
> +    return config
same comment - API restriciton imposes us to use that validation

2023-08-07 08:23 UTC, lienbacher commented
Thanks for being so swift on the comments @regevbr! Please don't overlook jesses comment about making a thread in the discord. It seems this will really speed things up!

2023-08-07 20:19 UTC, xaviergr commented on esphome/components/ld2410/ld2410.cpp
> +  }
> Example scenario - user defined some values using the mobile app, and then changed this value in HA, causing his defined values to be overridden.

This scenario is super important and one of the reasons why the current ld2410 component is hard to use on upstream. If you fine tune with the bluetooth app, then on the next reboot your settings are overwritten by esphome.

2023-08-07 21:01 UTC, jesserockz commented on esphome/components/ld2410/ld2410.cpp
> +  }
Why would you use the mobile app via bluetooth instead of just configuring via ESPHome? What is the point of all of this if you are just gonna use the manufacturer app still?

2023-08-07 21:28 UTC, xaviergr commented on esphome/components/ld2410/ld2410.cpp
> +  }
> Why would you use the mobile app via bluetooth instead of just configuring via ESPHome? What is the point of all of this if you are just gonna use the manufacturer app still?

You can use both depending on the scenario. If I want to do a small tweak to the settings (say increase by one the distance) I can do it through the home assistant interface, but if I set up a new sensor or want to customize from scratch, the bluetooth app has a nice graph view and an auto-configuration option to detect background noise and set thresholds according to that. Additionally you still need the app if you want to upgrade to the latest firmware.

On all other cases esphome/home assistant is more suited, plus with this PR I can finally disable bluetooth and force the UART baudrate to something faster than the default, as well as getting access to the crude light sensor. Also, I haven't tried it yet, but a athua posted above in the comments of an alternative way to visualize the readings/thresholds compared to the plain number bars (which are a pain to adjust on mobile) of home assistant, so in theory this opens up possibilities for someone to make an even fancier interface than the bluetooth app.

2023-08-08 00:46 UTC, alexruffell commented on esphome/components/ld2410/ld2410.cpp
> +  }
> Why would you use the mobile app via bluetooth instead of just configuring via ESPHome? What is the point of all of this if you are just gonna use the manufacturer app still?

@jesserockz The bluetooth app has a graphical representation of what is detected and the thresholds set. I exclusively use the bt app to configure and tweak my settings and am super happy that ESPHome pulls them in so they don't get overwritten. Configuring the sensor without the app would be a lot more painful and time consuming.

2023-08-08 07:16 UTC, regevbr commented on esphome/components/ld2410/ld2410.h
> +static const char *const TAG = "ld2410";
fixed

2023-08-08 07:30 UTC, regevbr commented on esphome/components/ld2410/ld2410.h
> +static const std::map<uint8_t, std::string> OUT_PIN_LEVEL_INT_TO_ENUM{{0x0, "low"}, {0x01, "high"}};
done

2023-08-08 08:30 UTC, regevbr commented on esphome/components/ld2410/ld2410_call.cpp
done

2023-08-08 08:35 UTC, regevbr commented on esphome/components/ld2410/number/__init__.py
> +        ),
cool done

2023-08-08 08:56 UTC, regevbr commented on esphome/components/ld2410/number/__init__.py
> +    return config
done

2023-08-08 08:56 UTC, regevbr commented on esphome/components/ld2410/number/__init__.py
> +    )
done

2023-08-08 08:56 UTC, regevbr commented on esphome/components/ld2410/number/__init__.py
> +CONFIG_SCHEMA = cv.All(CONFIG_SCHEMA, validate)
done

2023-08-08 09:11 UTC, regevbr commented on esphome/components/ld2410/number/__init__.py
> +        )
done in all relevant places

2023-08-08 09:13 UTC, regevbr commented on esphome/components/ld2410/number/__init__.py
> +            cg.add(ld2410_component.set_gate_still_threshold_number(x, n))
done. Though not sure why I passed `x` in `n = cg.new_Pvariable(move_config[CONF_ID], x)` so for no removed unless @jesserockz you think it is needed

2023-08-08 09:16 UTC, regevbr commented on esphome/components/ld2410/select/__init__.py
> +    return config
I used inclusive here, just like you suggested in Number

2023-08-08 09:29 UTC, regevbr commented on esphome/components/ld2410/sensor.py
> +    )
Done

2023-08-08 10:43 UTC, regevbr commented on esphome/components/ld2410/sensor.py
> +            icon="mdi:signal-distance-variant",
done

2023-08-08 12:49 UTC, regevbr commented on esphome/components/ld2410/ld2410.cpp
> +#ifdef USE_SELECT
Done

2023-08-08 12:49 UTC, regevbr commented on esphome/components/ld2410/ld2410.cpp
> +  }
Hi all I managed to handle that without causing any issue for people who use the app as well

2023-08-08 12:52 UTC, regevbr commented
Hi all,
I have completed the CR and pushed the changes, but it imposes a breaking change for the configuration. Please see PR description for the proper way to configure the g* gates sensor and number entities.

I would also appreciate feedback for the latest version so we can push this as fast as possible :-)

2023-08-08 14:54 UTC, clinta commented
I've updated my configs and all my devices. So far everything seems fine. I'll update in a couple of days if I still see no issues.

2023-08-08 16:07 UTC, Martin22 commented
Hi @regevbr ,

I have a question about ESP32-S2 and LD2410C. I would like to ask if this solution should work with these components. Unfortunately, even after the correct pin settings, as I have in the original functional from Scrreka, it does not work. According to the log, there is no communication.

Can you please advise me what might be wrong?

Thank you

2023-08-08 16:09 UTC, regevbr commented
> Hi @regevbr ,
> 
> I have a question about ESP32-S2 and LD2410C. I would like to ask if this solution should work with these components. Unfortunately, even after the correct rx and tx pin settings, as I have in the original functional from Screek, it does not work. According to the log, there is no communication.
> 
> Can you please advise me what might be wrong?
> 
> Thank you

Not a clue... Does it work for you in the current implementation (i.e. not mine)

2023-08-08 16:11 UTC, Martin22 commented
> > Hi @regevbr ,
> > I have a question about ESP32-S2 and LD2410C. I would like to ask if this solution should work with these components. Unfortunately, even after the correct rx and tx pin settings, as I have in the original functional from Screek, it does not work. According to the log, there is no communication.
> > Can you please advise me what might be wrong?
> > Thank you
> 
> Not a clue... Does it work for you in the current implementation (i.e. not mine)

Yes, it works in the current implementation, but not in yours.

2023-08-08 16:14 UTC, regevbr commented
> > > Hi @regevbr ,
> > > I have a question about ESP32-S2 and LD2410C. I would like to ask if this solution should work with these components. Unfortunately, even after the correct rx and tx pin settings, as I have in the original functional from Screek, it does not work. According to the log, there is no communication.
> > > Can you please advise me what might be wrong?
> > > Thank you
> > 
> > 
> > Not a clue... Does it work for you in the current implementation (i.e. not mine)
> 
> Yes, it works in the current implementation, but not in yours.

Can you share the config here? Maybe you didn't put uart_id? Besides that I can't think of a reason it will not work

2023-08-08 16:23 UTC, Martin22 commented
> > > > Hi @regevbr ,
> > > > I have a question about ESP32-S2 and LD2410C. I would like to ask if this solution should work with these components. Unfortunately, even after the correct rx and tx pin settings, as I have in the original functional from Screek, it does not work. According to the log, there is no communication.
> > > > Can you please advise me what might be wrong?
> > > > Thank you
> > > 
> > > 
> > > Not a clue... Does it work for you in the current implementation (i.e. not mine)
> > 
> > 
> > Yes, it works in the current implementation, but not in yours.
> 
> Can you share the config here? Maybe you didn't put uart_id? Besides that I can't think of a reason it will not work

 

> > > Couldn't find good card to display it in a way the app does. But what I do instead to calibrate, is placing sensor, then leaving it alone for couple hours in engineering mode, hanging in areas it shouldn't pick - and then seeing maximums on still/move history graphs, and set thresholds a bit higher than maximum.
> > 
> > 
> > Thank you! I saw someone people talking about a custom card.
> 
> Using the custom bar card, you can create a bar chart to give you a visual representation of the move or still levels:
> 
> ```
> type: custom:bar-card
> title: Move Energy
> direction: up
> columns: 9
> height: 100px
> width: 100%
> positions:
>   icon: 'off'
>   name: none
>   indicator: 'off'
>   value: none
> entities:
>   - entity: sensor.g0_move_energy_lounge_room
>   - entity: sensor.g1_move_energy_lounge_room
>   - entity: sensor.g2_move_energy_lounge_room
>   - entity: sensor.g3_move_energy_lounge_room
>   - entity: sensor.g4_move_energy_lounge_room
>   - entity: sensor.g5_move_energy_lounge_room
>   - entity: sensor.g6_move_energy_lounge_room
>   - entity: sensor.g7_move_energy_lounge_room
>   - entity: sensor.g8_move_energy_lounge_room
> ```
> 
> ![move-levles](https://user-images.githubusercontent.com/60054635/258570025-2cc3099d-1321-431a-b2e2-2e7c473e20e3.JPG)
> 
> Also wondering what is preventing this from being merged as I have been using it for several months now with no issues.



> > > > Hi @regevbr ,
> > > > I have a question about ESP32-S2 and LD2410C. I would like to ask if this solution should work with these components. Unfortunately, even after the correct rx and tx pin settings, as I have in the original functional from Screek, it does not work. According to the log, there is no communication.
> > > > Can you please advise me what might be wrong?
> > > > Thank you
> > > 
> > > 
> > > Not a clue... Does it work for you in the current implementation (i.e. not mine)
> > 
> > 
> > Yes, it works in the current implementation, but not in yours.
> 
> Can you share the config here? Maybe you didn't put uart_id? Besides that I can't think of a reason it will not work

```
external_components:
source: github://regevbr/esphome@ld2410
components: [ld2410]

esp32:
board: lolin_s2_mini
variant: ESP32S2

logger:
hardware_uart: uart0

uart:
id: ld2410_uart
tx_pin: GPIO33
rx_pin: GPIO18
baud_rate: 256000
parity: NONE
stop_bits: 1

ld2410:
uart_id: ld2410_uart
throttle: 1500ms
id: ld2410_comp

select:

platform: ld2410
distance_resolution:
name: distance resolution
baud_rate:
name: baud rate
light_function:
name: light function
out_pin_level:
name: out pin level
button:

platform: ld2410
factory_reset:
name: "factory reset"
restart:
name: "restart"
query_params:
name: query params
number:

platform: ld2410
timeout:
name: timeout
max_move_distance_gate:
name: max move distance gate
max_still_distance_gate:
name: max still distance gate
g0:
move_threshold:
name: g0 move threshold
still_threshold:
name: g0 still threshold
g1:
move_threshold:
name: g1 move threshold
still_threshold:
name: g1 still threshold
g2:
move_threshold:
name: g2 move threshold
still_threshold:
name: g2 still threshold
g3:
move_threshold:
name: g3 move threshold
still_threshold:
name: g3 still threshold
g4:
move_threshold:
name: g4 move threshold
still_threshold:
name: g4 still threshold
g5:
move_threshold:
name: g5 move threshold
still_threshold:
name: g5 still threshold
g6:
move_threshold:
name: g6 move threshold
still_threshold:
name: g6 still threshold
g7:
move_threshold:
name: g7 move threshold
still_threshold:
name: g7 still threshold
g8:
move_threshold:
name: g8 move threshold
still_threshold:
name: g8 still threshold
light_threshold:
name: light threshold
text_sensor:

platform: ld2410
version:
name: "presenece sensor version"
mac_address:
name: "presenece sensor mac address"
switch:

platform: ld2410
engineering_mode:
name: "engineering mode"
bluetooth:
name: control Bluetooth
binary_sensor:

platform: ld2410
has_target:
name: "presence"
has_moving_target:
name: "movement"
has_still_target:
name: "still"
out_pin_presence_status:
name: out pin presence status
platform: gpio
pin: GPIO16
name: gpio out pin presence
device_class: presence
sensor:

platform: ld2410
moving_distance:
name: "Moving distance (cm)"
still_distance:
name: "Still Distance (cm)"
moving_energy:
name: "Move Energy (%)"
still_energy:
name: "Still Energy (%)"
detection_distance:
name: "Distance Detection (cm)"
g0:
move_energy:
name: g0 move energy
still_energy:
name: g0 still energy
g1:
move_energy:
name: g1 move energy
still_energy:
name: g1 still energy
g2:
move_energy:
name: g2 move energy
still_energy:
name: g2 still energy
g3:
move_energy:
name: g3 move energy
still_energy:
name: g3 still energy
g4:
move_energy:
name: g4 move energy
still_energy:
name: g4 still energy
g5:
move_energy:
name: g5 move energy
still_energy:
name: g5 still energy
g6:
move_energy:
name: g6 move energy
still_energy:
name: g6 still energy
g7:
move_energy:
name: g7 move energy
still_energy:
name: g7 still energy
g8:
move_energy:
name: g8 move energy
still_energy:
name: g8 still energy
light:
name: light
```

> > > > Hi @regevbr ,
> > > > I have a question about ESP32-S2 and LD2410C. I would like to ask if this solution should work with these components. Unfortunately, even after the correct rx and tx pin settings, as I have in the original functional from Screek, it does not work. According to the log, there is no communication.
> > > > Can you please advise me what might be wrong?
> > > > Thank you
> > > 
> > > 
> > > Not a clue... Does it work for you in the current implementation (i.e. not mine)
> > 
> > 
> > Yes, it works in the current implementation, but not in yours.
> 
> Can you share the config here? Maybe you didn't put uart_id? Besides that I can't think of a reason it will not work

```
external_components:
  source: github://regevbr/esphome@ld2410
  components: [ld2410]

esp32:
  board: lolin_s2_mini
  variant: ESP32S2

logger:
  hardware_uart: uart0


uart:
  id: ld2410_uart
  tx_pin: GPIO33
  rx_pin: GPIO18
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_comp

select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution
    baud_rate:
      name: baud rate
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410
    timeout:
      name: timeout
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
  [...]

2023-08-08 16:24 UTC, Martin22 commented
```
external_components:
  source: github://regevbr/esphome@ld2410
  components: [ld2410]

esp32:
  board: lolin_s2_mini
  variant: ESP32S2

logger:
  hardware_uart: uart0


uart:
  id: ld2410_uart
  tx_pin: GPIO33
  rx_pin: GPIO18
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_comp

select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution
    baud_rate:
      name: baud rate
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410
    timeout:
      name: timeout
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
    light_threshold:
      name: light threshold

text_sensor:
  - platform: ld2410
    version:
      name: "presenece sensor version" 
    mac_address:
      name: "presenece sensor mac address"

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode" 
    bluetooth:
      name: control Bluetooth

binary_sensor:
  - platform: ld2410
    has_target:
      name: "presence"
    has_moving_target:
      name: "movement"
    has_still_target:
      name: "still"
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin: GPIO16
    name: gpio out pin presence
    device_class: presence

sensor:
  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
    g0: 
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1: 
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2: 
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3: 
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4: 
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5: 
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6: 
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7: 
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8: 
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy
    light:
      name: light
```

2023-08-08 16:26 UTC, regevbr commented
> ```
> external_components:
>   source: github://regevbr/esphome@ld2410
>   components: [ld2410]
> 
> esp32:
>   board: lolin_s2_mini
>   variant: ESP32S2
> 
> logger:
>   hardware_uart: uart0
> 
> 
> uart:
>   id: ld2410_uart
>   tx_pin: GPIO33
>   rx_pin: GPIO18
>   baud_rate: 256000
>   parity: NONE
>   stop_bits: 1
> 
> ld2410:
>   uart_id: ld2410_uart
>   throttle: 1500ms
>   id: ld2410_comp
> 
> select:
>   - platform: ld2410
>     distance_resolution:
>       name: distance resolution
>     baud_rate:
>       name: baud rate
>     light_function:
>       name: light function
>     out_pin_level:
>       name: out pin level
> 
> button:
>   - platform: ld2410
>     factory_reset:
>       name: "factory reset"
>     restart:
>       name: "restart"
>     query_params:
>       name: query params
> 
> number:
>   - platform: ld2410
>     timeout:
>       name: timeout
>     max_move_distance_gate:
>       name: max move distance gate
>     max_still_distance_gate:
>       name: max still distance gate
>     g0:
>       move_threshold:
>         name: g0 move threshold
>       still_threshold:
>         name: g0 still threshold
>     g1:
>       move_threshold:
>         name: g1 move threshold
>       still_threshold:
>         name: g1 still threshold
>     g2:
>       move_threshold:
>         name: g2 move threshold
>       still_threshold:
>         name: g2 still threshold
>     g3:
>       move_threshold:
>         name: g3 move threshold
>       still_threshold:
>         name: g3 still threshold
>     g4:
>       move_threshold:
>         name: g4 move threshold
>       still_threshold:
>         name: g4 still threshold
>     g5:
>       move_threshold:
>         name: g5 move threshold
>       still_threshold:
>         name: g5 still threshold
>     g6:
>       move_threshold:
>         name: g6 move threshold
>       still_threshold:
>         name: g6 still threshold
>     g7:
>       move_threshold:
>         name: g7 move threshold
>       still_threshold:
>         name: g7 still threshold
>     g8:
>       move_threshold:
>         name: g8 move threshold
>       still_threshold:
>         name: g8 still threshold
>     light_threshold:
>       name: light threshold
> 
> text_sensor:
>   - platform: ld2410
>     version:
>       name: "presenece sensor version" 
>     mac_address:
>       name: "presenece sensor mac address"
> 
> switch:
>   - platform: ld2410
>     engineering_mode:
>       name: "engineering mode" 
>     bluetooth:
>       name: control Bluetooth
> 
> binary_sensor:
>   - platform: ld2410
>     has_target:
>       name: "presence"
>     has_moving_target:
>       name: "movement"
>     has_still_target:
>       name: "still"
>     out_pin_presence_status:
>       name: out pin presence status
>   - platform: gpio
>     pin: GPIO16
>     name: gpio out pin presence
>     device_class: presence
> 
> sensor:
>   - platform: ld2410
>     moving_distance:
>       name: "Moving distance (cm)"
>     still_distance:
>       name: "Still Distance (cm)"
>     moving_energy:
>       name: "Move Energy (%)"
>     still_energy:
>       name: "Still Energy (%)"
>     detection_distance:
>       name: "Distance Detection (cm)"
>     g0: 
>       move_energy:
>         name: g0 move energy
>       still_energy:
>         name: g0 still energy
>     g1: 
>       move_energy:
>         name: g1 move energy
>       still_energy:
>         name: g1 still energy
>     g2: 
>       move_energy:
>         name: g2 move energy
>       still_energy:
>         name: g2 still energy
>     g3: 
>       move_energy:
>         name: g3 move energy
>       still_energy:
>         name: g3 still energy
>     g4: 
>       move_energy:
>         name: g4 move energy
>       still_energy:
>         name: g4 still energy
>     g5: 
>       move_energy:
>         name: g5 move energy
>       still_energy:
>         name: g5 still energy
>     g6: 
>       move_energy:
>         name: g6 move energy
>       still_energy:
>         name: g6 still energy
>     g7: 
>       move_energy:
>         name: g7 move energy
>       still_energy:
>         name: g7 still energy
>     g8: 
>       move_energy:
>         name: g8 move energy
>       still_energy:
>         name: g8 still energy
>     light:
>       name: light
> ```

Sadly I can't help, but would fix it once you find out why it happens...

2023-08-08 16:28 UTC, Martin22 commented
> Sadly I can't help, but would fix it once you find out why it happens...

I would like to, but I am afraid that my knowledge is not enough to find out.

2023-08-08 16:41 UTC, descipher commented
> uart:
>   id: ld2410_uart
>   tx_pin: GPIO33
>   rx_pin: GPIO18
>   baud_rate: 256000
>   parity: NONE
>   stop_bits: 1
> 
> ld2410:
>   uart_id: ld2410_uart
>   throttle: 1500ms
>   id: ld2410_comp

Not using the right pins for the hardware uart mapping which means it will run software emulation .. not good.

GPIO17 23 I/O/T VDD3P3_RTC RTC_GPIO17, GPIO17, **U1TXD**, ADC2_CH6
GPIO18 24 I/O/T VDD3P3_RTC RTC_GPIO18, GPIO18, **U1RXD**, ADC2_CH7, CLK_OUT3

2023-08-08 16:44 UTC, simonyel commented
@Martin22 I compared my code to yours and saw a few differences there. See if below fixes it. 

`external_components:
  source: github://regevbr/esphome@ld2410
  components: [ld2410]

esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  framework:
    type: Arduino  

logger:

api:
  services:
    - service: set_ld2410_bluetooth_password
      variables:
        password: string
      then:
        - bluetooth_password.set:
            id: ld2410_comp
            password: HiLink
uart:
  id: ld2410_uart
  tx_pin: GPIO33
  rx_pin: GPIO18
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_comp

select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution
    baud_rate:
      name: baud rate
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410
    timeout:
      name: timeout
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
    light_threshold:
      name: light threshold

text_sensor:
  - platform: ld2410
    version:
      name: "presenece sensor version" 
    mac_address:
      name: "presenece sensor mac address"

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode" 
    bluetooth:
      name: control Bluetooth

binary_sensor:
  - platform: ld2410
    has_target:
      name: "presence"
    has_moving_target:
      name: "movement"
    has_still_target:
      name: "still"
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin: GPIO16
    name: gpio out pin presence
    device_class: presence

sensor:
  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
    g0: 
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1: 
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2: 
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3: 
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4: 
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5: 
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6: 
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7: 
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8: 
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy
    light:
      name: light`

2023-08-08 17:14 UTC, Martin22 commented
> 

I am using the pins correctly, it would not work for me even now, where Screek's code is used. It can be seen in the pictures below.

![image](https://github.com/esphome/esphome/assets/2546041/34fe7593-dba4-44c7-b550-b7b7a0e064fa)
![image](https://github.com/esphome/esphome/assets/2546041/c6b1fa1a-d0f7-4252-b2ea-509d74e309d5)

2023-08-08 17:21 UTC, menelike commented
@regevbr Thanks for keeping this PR alive, it works great and I have been using this for months without issues.
If we'd be in prison, I'd protect to in the shower ;)

2023-08-08 17:30 UTC, descipher commented
Nope, you need the other row for GPIO17 so you can't solder it directly like that.

<img width="494" alt="image" src="https://github.com/esphome/esphome/assets/10734527/72f0c80a-9d13-4865-a1f4-7b4337327342">

2023-08-08 17:32 UTC, Martin22 commented
> 

I have https://www.wemos.cc/en/latest/s2/s2_mini.html, the pins are different there.

2023-08-08 17:36 UTC, simonyel commented
I'm wondering if the reason it 

> > 
> 
> I am using the pins correctly, it would not work for me even now, where Screek's code is used. It can be seen in the pictures below.
> 
> ![image](https://user-images.githubusercontent.com/2546041/259176798-34fe7593-dba4-44c7-b550-b7b7a0e064fa.png) ![image](https://user-images.githubusercontent.com/2546041/259176912-c6b1fa1a-d0f7-4252-b2ea-509d74e309d5.png)

![image](https://github.com/esphome/esphome/assets/30694967/39cff225-ef49-4183-ba9d-dd89552c7ba3)


It might be that the official integration is working now only because it doesn't verify transmits, this code does.

2023-08-08 17:45 UTC, Martin22 commented
> It might be that the official integration is working now only because it doesn't verify transmits, this code does.

Okay, I will try it sometime, probably solder it over the weekend and see.

2023-08-08 18:11 UTC, sebcaps commented
> > It might be that the official integration is working now only because it doesn't verify transmits, this code does.
> 
> Okay, I will try it sometime, probably solder it over the weekend and see.

It "indirectly" verify transmit : to each command send a acknoldegment is received and interpreted => each pins must be correctly connected otherwise it will not work  and errors in logs

2023-08-08 21:56 UTC, segator commented
Its not working anymore, I got this in the esp logs
[23:55:30][E][ld2410:340]: Error with last command : incorrect Header
Used your new yaml file

2023-08-09 09:26 UTC, regevbr commented
> Its not working anymore, I got this in the esp logs [23:55:30][E][ld2410:340]: Error with last command : incorrect Header Used your new yaml file

Hmm that is strange, I didn't really change anything about the communication. But I might have an idea, can you please share your config (formatted)?

2023-08-09 16:16 UTC, alexruffell commented
@regevbr - I updated my YAML to work with the latest iteration and all 5+ systems are working great. I noticed that when you turn Engineering mode On / Off with the BT app (Android) open, you get an "error with last command" in the logs. Behavior with regards to it turning on/off seems to vary depending on whether you turned Eng. Mode on with the app and are trying to turn it off with HA, or the other way around. In summary, changing that toggle is unreliable when you have the app open only - as soon as you close it, all is back to normal. I'd say this is likely to be expected however it may warrant looking into as I see the error even when it actually toggles (does it try again when it fails?). To replicate just look at logs while the LD2410 is connected via BT to the app and toggle Eng. Mode from both the app and HA (device page).

```
[10:54:45][E][ld2410:348]: Error with last command , last buffer was: 1 , 0
[10:54:45][E][ld2410:348]: Error with last command , last buffer was: 1 , 0
```

Here I was turning Eng. Mode on/off via the BT app, and then turned it off via HA (single error instance). At times, HA is unable to turn it on/off if the BT app is open.

<img width="452" alt="image" src="https://github.com/esphome/esphome/assets/4006944/b50b7eed-bc21-4cb1-b10c-738a2521d810">

Either way, I really appreciate being able to use both the BT app and HA at the same time to configure it, and don't consider this a show stopper issue. At first I tried configuring the sensor via HA thinking it would overwrite anything I did in the app but it was quite annoying as I really needed the app for its graphs to figure out the settings. Now I use the app to configure all the gates and thresholds and the rest in HA. I love that HA pulls in all the sensor settings! I also changed the default sliders to number boxes in my ESPHome YAML to improve ease of use.

2023-08-10 04:53 UTC, jesserockz commented
> Nope, you need the other row for GPIO17 so you can't solder it directly like that.
> 
> <img alt="image" width="494" src="https://user-images.githubusercontent.com/10734527/259180238-72f0c80a-9d13-4865-a1f4-7b4337327342.png">

@descipher ESP32 can use hardware UART on any pin combination you just gotta match the pin numbers in config. cc @Martin22

2023-08-10 05:03 UTC, jesserockz requested changes

2023-08-10 05:03 UTC, jesserockz commented on esphome/components/ld2410/ld2410.cpp
> +  }
This should not call turn_on/off as its an external state change and should just be updating to match the hardware. It should just `publish_state`. `publish_state` already has a deduplicator so there is no risk calling again.

```suggestion
  if (this->engineering_mode_switch_ != nullptr) {
    this->engineering_mode_switch_->publish_state(engineering_mode);
  }
```

The same goes for the numbers and selects.

2023-08-10 07:21 UTC, regevbr commented on esphome/components/ld2410/ld2410.cpp
> +  }
select and numbers do not have dedup mechanism though, should I take that under account or not?

2023-08-10 08:12 UTC, regevbr commented on esphome/components/ld2410/ld2410.cpp
> +  }
done

2023-08-14 09:28 UTC, jcastro commented
Hi @regevbr, thanks a lot for this great work. I'm testing some mmWave sensors and came across to this PR. Love how much it changes the experience of tweaking it vs the current implementation.

Anyway! I have a few comments
- At 0.75m resolution shouldn't the sliders `max move distance gate` and `max still distance gate` move in 0.75 increments?. And also looks like if I change it to 0.2 the increments stay the same. I tried adding `steps` option to the config to configure the increments but only works when using a number template
- When changing to 0.2 resolution I'm experiencing some problems, the sensor stops reporting, it looks like it's just "crashing". Attaching an image below that shows what happens when I set it to 0.2
<img width="1450" alt="image" src="https://github.com/esphome/esphome/assets/190036/53962d37-b93b-4b61-bcb0-2c03a10fa18a">

2023-08-14 11:16 UTC, regevbr commented
> Hi @regevbr, thanks a lot for this great work. I was testing some mmWave sensors and came across this PR. I love how much it changes the experience of tweaking it vs the current implementation.
> 
> Anyway! I have a few comments
> 
> * At 0.75m resolution shouldn't the sliders `max move distance gate` and `max still distance gate` move in 0.75 increments? And also looks like if I change it to 0.2 the increments stay the same. I tried adding `steps` option to configure the increments but it only works when using a number template
> * When changing to 0.2 resolution I'm experiencing some problems, the sensor stops reporting, and it looks like it's just "crashing". Attaching an image below that shows what happens when I set it to 0.2
> 
> <img alt="image" width="1450" src="https://user-images.githubusercontent.com/190036/260410962-53962d37-b93b-4b61-bcb0-2c03a10fa18a.png">
> Edit: I should add that I just factory reset the sensor and didn't change any settings either. Running the LD2410C on a Wemos d1 mini esp32 on esphome 2023.9.0-dev

Hi,

- The sliders are working on gate number, not the distance.
- I don't see any issues on my side, it takes a few seconds after you make the change for the sensors to report values again but it works

2023-08-14 11:30 UTC, jcastro commented
@regevbr ahh got it. As for the second issue I've recorded a video with some comments so maybe that's more helpful. Are you also on version 2.0 of the firmware?

Check the video here https://d.pr/v/s6MVWa (too big to upload to Github)

2023-08-14 11:43 UTC, regevbr commented
> @regevbr ahh got it. As for the second issue I've recorded a video with some comments so maybe that's more helpful. Are you also on version 2.04 of the firmware?
> 
> Check the video here https://d.pr/v/s6MVWa (too big to upload to Github)

Yes I use same version.
The video clearly shows the issue is the gates. Can you reproduce the same thing using the app? My guess it will happen if you use the regular app and it is not related to my code. When you reproduce please stand exactly where you are at and keep the sensor in the same place.

2023-08-14 11:53 UTC, jcastro commented
> > @regevbr ahh got it. As for the second issue I've recorded a video with some comments so maybe that's more helpful. Are you also on version 2.04 of the firmware?
> > Check the video here https://d.pr/v/s6MVWa (too big to upload to Github)
> 
> Yes I use same version. The video clearly shows the issue is the gates. Can you reproduce the same thing using the app? My guess it will happen if you use the regular app and it is not related to my code. When you reproduce please stand exactly where you are at and keep the sensor in the same place.

Indeed! in the app is happening exactly the same!

2023-08-14 11:54 UTC, regevbr commented
> > > @regevbr ahh got it. As for the second issue I've recorded a video with some comments so maybe that's more helpful. Are you also on version 2.04 of the firmware?
> > > Check the video here https://d.pr/v/s6MVWa (too big to upload to Github)
> > 
> > 
> > Yes I use same version. The video clearly shows the issue is the gates. Can you reproduce the same thing using the app? My guess it will happen if you use the regular app and it is not related to my code. When you reproduce please stand exactly where you are at and keep the sensor in the same place.
> 
> Indeed! in the app is happening exactly the same!

Ok so you probably need to be more closer to the sensor for it to detect you when you set the gate distances to 0.2 instead of 9.75

2023-08-14 12:04 UTC, jcastro commented
> 

Actually YES! Mine is installed on the ceiling, just waved my hand on top of a chair and it's detecting some movement now. Thanks a lot!

BTW Do you have handy the 2.0 documentation? (only been able to find V1.02 so far) I'm having a hard time understanding the threshold and gates, and when it actually changes to the detection state. I was hoping to get some answers there

2023-08-14 12:21 UTC, regevbr commented
Enjoy. BTW you can download it from their app and then use google to translate it

[LD2410 串口通信协议 V1.06 230220_zh.pdf](https://github.com/esphome/esphome/files/12334517/LD2410.V1.06.230220_zh.pdf)
[LD2410 串口通信协议 V1.06 230220_zh - en.pdf](https://github.com/esphome/esphome/files/12334518/LD2410.V1.06.230220_zh.-.en.pdf)

2023-08-14 12:27 UTC, EenerNL commented
Is there any chance this PR will be merged into 2023.8.0?

2023-08-14 12:30 UTC, clinta commented
Still no issues in my testing. Updated to 2023.9.0-dev yesterday.

2023-08-14 12:48 UTC, ChrisThomas42 commented
Updated my two active (got another 4 waiting enclosures) to latest version along with the the dashboard code.  All working for me

2023-08-14 12:49 UTC, lienbacher commented
All working just fine here as well, just added another sensor. How Could I live without those?

2023-08-14 13:15 UTC, jcastro commented
Guys for the ones that got the sensor nicely working with almost no false negatives or positives, can you share your gate configuration? thanks a lot <3

2023-08-14 13:22 UTC, lienbacher commented
> For the ones that got the sensor nicely working with almost no false negatives or positives, can you share your gate configuration? thanks a lot <3

well honestly every single of my sensors has it's very own configuration for the very specific use case. I don't think you will be able to solve your specific problem by looking at other configurations. I made myself a dashboard using the bar-card from the hacs store so I can see the gate values using engineering-mode. you can also use the history graph to see which gate triggered your false positive and adjust the sensitivities accordingly.

2023-08-14 13:33 UTC, ChrisThomas42 commented
@jcastro I agree with @lienbacher , the configuration of my two fully operational sensors are wildly different!  One is in the lounge/living room and the other the bedroom.  I took a while to get them both "right" but with this code it's SO much easier.

When I say a while, that was changing the last digit of the gate sensitivities.

2023-08-14 13:36 UTC, regevbr commented
> > For the ones that got the sensor nicely working with almost no false negatives or positives, can you share your gate configuration? thanks a lot <3
> 
> well honestly every single of my sensors has it's very own configuration for the very specific use case. I don't think you will be able to solve your specific problem by looking at other configurations. I made myself a dashboard using the bar-card from the hacs store so I can see the gate values using engineering-mode. you can also use the history graph to see which gate triggered your false positive and adjust the sensitivities accordingly.

Do you mind sharing your custom card config that you use to illustrate the gates?

2023-08-14 13:49 UTC, EenerNL commented
> > > For the ones that got the sensor nicely working with almost no false negatives or positives, can you share your gate configuration? thanks a lot <3
> > 
> > 
> > well honestly every single of my sensors has it's very own configuration for the very specific use case. I don't think you will be able to solve your specific problem by looking at other configurations. I made myself a dashboard using the bar-card from the hacs store so I can see the gate values using engineering-mode. you can also use the history graph to see which gate triggered your false positive and adjust the sensitivities accordingly.
> 
> Do you mind sharing your custom card config that you use to illustrate the gates?

Athua already shared a config up here:
https://github.com/esphome/esphome/pull/4434#issuecomment-1666424716

2023-08-14 14:28 UTC, jcastro commented
@EenerNL uuuh this is great! I was checking Bar Card and it seems you can set a target... I wish we could put an entity as a target so it change update automatically but for now this is quite visual to me!

![Screen Capture on 2023-08-14 at 16-26-12](https://github.com/esphome/esphome/assets/190036/d343d6da-cd90-4a6e-9bf0-ca8d12ac2b59)

2023-08-14 14:31 UTC, markmghali commented
> @EenerNL uuuh this is great! I was checking Bar Card and it seems you can set a target... I wish we could put an entity as a target so it change update automatically but for now this is quite visual to me!
> 
> Note: forgot to change the name, one is move the other still energy
> 
> ![Screen Capture on 2023-08-14 at 16-26-12](https://github.com/esphome/esphome/assets/190036/d343d6da-cd90-4a6e-9bf0-ca8d12ac2b59)
> 

How do you set that target? Can you show me the yaml?

2023-08-14 15:20 UTC, jcastro commented
Thanks everyone! with this setup, I'm now understanding way better what's happening and what I should be tweaking.

Btw, I just tried to hold my breath so the sensor clears occupancy and discovered (for myself haha) that it won't trigger back to occupied only with still energy, it actually requires reaching the move thresholds! (video below) 

https://github.com/esphome/esphome/assets/190036/7bec7656-eee4-42a4-a968-becb41d6aef0

2023-08-14 15:22 UTC, markmghali commented
> Thanks everyone! with this setup, I'm now understanding way better what's happening and what I should be tweaking.
> 
> Btw, I just tried to hold my breath so the sensor clears occupancy and discovered (for myself haha) that it won't trigger back to occupied only with still energy, it actually requires reaching the move thresholds! (video below) 
> 
> https://github.com/esphome/esphome/assets/190036/7bec7656-eee4-42a4-a968-becb41d6aef0
> 
> 

Yes the move threshold has to be met first for a still occupancy

2023-08-15 23:30 UTC, jesserockz approved these changes

2023-08-15 23:31 UTC, merged

2023-08-15 23:40 UTC, jsouth117 commented
Awesome!

2023-08-16 08:59 UTC, ChrisThomas42 commented
Awesome, splendid, excellent.  A big thank you to evryone who's contributed to make this so useful and easy to use!

2023-08-17 16:22 UTC, jascdk commented
Which microcontroller do you guys use? I have UART hooked up to an ESP8266 D1 mini pro. It does not seem to start with all the new sensors? Looks like it lacks of memory in some kind of way:( Are you using esp32 ?

2023-08-17 16:29 UTC, ChrisThomas42 commented
@jascdk I have a ESP8266 (D1 mini) working in my lounge and seems to work just as well as ESP32 in a bedroom.  D1 mini pro has more RAM than a normal D1 mini so I don't think it's RAM.

2023-08-17 16:44 UTC, markmghali commented
> Which microcontroller do you guys use? I have UART hooked up to an ESP8266 D1 mini pro. It does not seem to start with all the new sensors? Looks like it lacks of memory in some kind of way:( Are you using esp32 ?

Are you using the esp-idf framework? I think that is recommended due to better layout? need to flash over usb if you are changing framework

2023-08-17 16:49 UTC, jascdk commented
@ChrisThomas42 - and you use all the bells and whistles the newest release offers on the LD2410 integration? Mine won't boot - it worked before with the old "minimal" configuration :/

2023-08-17 16:50 UTC, jascdk commented
@markmghali im using standard arduino framework - I don't think IDF is for esp8266

2023-08-17 16:58 UTC, ChrisThomas42 commented
@jascdk Yes, all the settings from this PR and working without issue, my board setting is basic;

`
  uart_tx_pin: GPIO15
  uart_rx_pin: GPIO13
.
.
. 

esp8266:
  board: d1_mini

# Enable logging
logger:
  baud_rate: 0
`

2023-08-17 18:46 UTC, sanchosk commented
I connected the LD2410 with ESP8266 in Shelly 2.5. I cannot use it anymore - it runs out of RAM when creating the JSON.
Even removing all threshold values, it still gets out of RAM when reporting both shelly power meter data and LD2410 :(
This is unfortunate as it was working with the old version of ld2410 no problem on the Shelly...

2023-08-18 00:08 UTC, simonyel commented
> I connected the LD2410 with ESP8266 in Shelly 2.5. I cannot use it anymore - it runs out of RAM when creating the JSON. Even removing all threshold values, it still gets out of RAM when reporting both shelly power meter data and LD2410 :( This is unfortunate as it was working with the old version of ld2410 no problem on the Shelly...

Do you have the web server enabled? Could you remove it if so? It might clean up enough space for everything else to run correctly.

2023-08-18 05:24 UTC, sanchosk commented
I did have it enabled, I'll test it without today.
Thanks for the tip!

On August 18, 2023 2:08:40 AM GMT+02:00, Simon Yelfimov ***@***.***> wrote:
>> I connected the LD2410 with ESP8266 in Shelly 2.5. I cannot use it anymore - it runs out of RAM when creating the JSON. Even removing all threshold values, it still gets out of RAM when reporting both shelly power meter data and LD2410 :( This is unfortunate as it was working with the old version of ld2410 no problem on the Shelly...
>
>Do you have the web server enabled? Could you remove it if so? It might clean up enough space for everything else to run correctly. 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/esphome/esphome/pull/4434#issuecomment-1683138388
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- Sent from /e/ Mail.

2023-08-18 06:10 UTC, Spoil001 commented
> > I connected the LD2410 with ESP8266 in Shelly 2.5. I cannot use it anymore - it runs out of RAM when creating the JSON. Even removing all threshold values, it still gets out of RAM when reporting both shelly power meter data and LD2410 :( This is unfortunate as it was working with the old version of ld2410 no problem on the Shelly...
> 
> Do you have the web server enabled? Could you remove it if so? It might clean up enough space for everything else to run correctly.

Disabling the webserver resolved the JSON issue for me

2023-08-18 06:36 UTC, sanchosk commented
> Do you have the web server enabled?

Now that did not work as desired :)
So now, my webserver is disabled on the ESP, but:
- I cannot reach it using the ESPHOME API anymore
- pings are working, but that's about it
- I cannot reflash firmware without the LD2410 anymore
I will have to disassemble the wall switch again, disconnect the device, connect it locally to USB-to-serial header and force reflash it :(
I wonder what happened - guess I will never know as I cannot add the device to HA or reach it in any way :(

2023-08-18 07:06 UTC, Shaunpottie commented
> number:
>   - platform: ld2410
>     timeout:
>       name: timeout
>     max_move_distance_gate:
>       name: max move distance gate
>     max_still_distance_gate:
>       name: max still distance gate
>     g0:
>       move_threshold:
>         name: g0 move threshold
>       still_threshold:
>         name: g0 still threshold
>     g1:
>       move_threshold:
>         name: g1 move threshold
>       still_threshold:
>         name: g1 still threshold
>     g2:
>       move_threshold:
>         name: g2 move threshold
>       still_threshold:
>         name: g2 still threshold
>     g3:
>       move_threshold:
>         name: g3 move threshold
>       still_threshold:
>         name: g3 still threshold
>     g4:
>       move_threshold:
>         name: g4 move threshold
>       still_threshold:
>         name: g4 still threshold
>     g5:
>       move_threshold:
>         name: g5 move threshold
>       still_threshold:
>         name: g5 still threshold
>     g6:
>       move_threshold:
>         name: g6 move threshold
>       still_threshold:
>         name: g6 still threshold
>     g7:
>       move_threshold:
>         name: g7 move threshold
>       still_threshold:
>         name: g7 still threshold
>     g8:
>       move_threshold:
>         name: g8 move threshold
>       still_threshold:
>         name: g8 still threshold
>     light_threshold:
>       name: light threshold
> 
> text_sensor:
>   - platform: ld2410
>     version:
>       name: "presenece sensor version" 
>     mac_address:
>       name: "presenece sensor mac address"
> 
> switch:
>   - platform: ld2410
>     engineering_mode:
>       name: "engineering mode" 
>     bluetooth:
>       name: control Bluetooth
> 
> binary_sensor:
>   - platform: ld2410
>     has_target:
>       name: "presence"
>     has_moving_target:
>       name: "movement"
>     has_still_target:
>       name: "still"
>     out_pin_presence_status:
>       name: out pin presence status
>   - platform: gpio
>     pin: GPIO13  // Your pin
>     name: gpio out pin presence
>     device_class: presence
> 
> sensor:
>   - platform: ld2410
>     moving_distance:
>       name: "Moving distance (cm)"
>     still_distance:
>       name: "Still Distance (cm)"
>     moving_energy:
>       name: "Move Energy (%)"
>     still_energy:
>       name: "Still Energy (%)"
>     detection_distance:
>       name: "Distance Detection (cm)"
>     g0: 
>       move_energy:
>         name: g0 move energy
>       still_energy:
>         name: g0 still energy
>     g1: 
>       move_energy:
>         name: g1 move energy
>       still_energy:
>         name: g1 still energy
>     g2: 
>       move_energy:
>         name: g2 move energy
>       still_energy:
>         name: g2 still energy
>     g3: 
>       move_energy:
>         name: g3 move energy
>       still_energy:
>         name: g3 still energy
>     g4: 
>       move_energy:
>         name: g4 move energy
>       still_energy:
>         name: g4 still energy
>     g5: 
>       move_energy:
>         name: g5 move energy
>       still_energy:
>         name: g5 still energy
>     g6: 
>       move_energy:
>         name: g6 move energy
>       still_energy:
>         name: g6 still energy
>     g7: 
>       move_energy:
>         name: g7 move energy
>       still_energy:
>         name: g7 still energy
>     g8: 
>       move_energy:
>         name: g8 move energy
>       still_energy:
>         name: g8 still energy
>     light:
>       name: light
> ```
> 
> ## Checklist:
> * [x]  The code change is tested and works locally.
> * [x]  Tests have been added to verify that the new code works (under `tests/` folder).
> 
> If user exposed functionality or configuration variables are added/changed:
> 
> * [x]  Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).
> 
> Features done:
> 
> * added engineering mode switch + sensors to show the energy values
> * added bluetooth switch
> * added factory reset, restart and query parameters buttons
> * added version and mac address text sensors
> * added ability to see and control all configurations directly from HA using number elements
> * Added nice default icons to all enetites
> * Cleaned up some of the code
> * added option to control the throttling of the data rate
> * added option to control the distance resolution
> * added option to change the bluetooth password
> * added option to change baud rate
> * added option to control the light sensor functionality
> 
> Please note that this is a breaking change to the current configuration

Thank you for all your work on the LD sensor, it's really appreciated.

Please can I ask, someone that has no clue what all the parameters and entities mean, in the above and how they affect any adjustments?

Where does a person find normal terms on what they mean and do, for someone like me that has no clue?

Thank you in advance.

2023-08-18 07:14 UTC, sanchosk commented
Perhaps check this video:
https://youtu.be/dAzHXpP3FcI?t=429

2023-08-18 07:16 UTC, Shaunpottie commented
Thanks, will take a look

2023-08-18 07:21 UTC, Shaunpottie commented
I just threw it into ChatGPT :)

Does this look right?

Configuration Settings
Baud Rate (256000):

Meaning: The speed of communication between the radar sensor and the D1 mini.
Adjustment: Usually set to a standard value; changing it may require matching changes in the sensor's configuration.
Control Bluetooth:

Meaning: Enables or disables Bluetooth functionality.
Adjustment: Use this to control Bluetooth connectivity as needed for your application.
Distance Resolution (0.75m):

Meaning: The granularity of distance measurements.
Adjustment: Reducing this value can provide more precise distance readings but may require more processing power.
Engineering Mode:

Meaning: A special mode for testing and development.
Adjustment: Use with caution; typically for developers or advanced users.
Factory Reset:

Meaning: Resets all settings to their default values.
Adjustment: Use if you need to start fresh with the default configuration.
Move and Still Thresholds (g0 to g8):

Meaning: Sensitivity settings for detecting movement and stillness in different zones (g0 to g8).
Adjustment: Increase or decrease these values to fine-tune the detection sensitivity in each zone.
Light Function (off/on):

Meaning: Controls a light function, possibly related to visual indicators.
Adjustment: Turn on or off as needed for your specific use case.
Light Threshold:

Meaning: The threshold for triggering the light function.
Adjustment: Adjust to control when the light function is activated.
Max Move/Still Distance Gate:

Meaning: The maximum distance for detecting movement or stillness.
Adjustment: Increase or decrease to control the range of detection.
Out Pin Level (low/high):

Meaning: The output level of a specific pin, possibly for controlling external devices.
Adjustment: Change as needed for controlling connected hardware.
Timeout (5,0 s):
Meaning: The time before a specific function or command times out.
Adjustment: Increase to allow more time for a function to complete, or decrease to make the system more responsive.

Sorry everyone, I'm very new to this type of stuff.

2023-08-18 10:24 UTC, sanchosk commented
Unfortunately, it did not work for me - the combination of Shelly power meter and the LD does not seem to fit into memory.
I guess this is not a problem of the code itself, but too many things attempted to run on the small RAM footprint.

I managed to disassemble the shelly from the wall and logged it on cutecom, this is the output:
```
Exception (29):␍␊
epc1=0x4000df64 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000
```
This is then followed by a long part of stack trace or something.
For now, I'll only use shelly to power the sensor, which also might not work OK as shelly outputs 3.3V and the sensor needs 5V :(
A bit failed project on my end...

2023-08-18 11:22 UTC, xaviergr commented
> For now, I'll only use shelly to power the sensor, which also might not
> work OK as shelly outputs 3.3V and the sensor needs 5V :(
> A bit failed project on my end...
>
Actually LD2410 does also work with 3.3V input. You just have to use the
outer test points that are on the opposite side of the PCB compared to the
usual 1.27 mm pins.

>

2023-08-18 11:24 UTC, sanchosk commented
I wish you were 20 minutes faster - before I closed the wall again :D

2023-08-18 12:35 UTC, clinta commented
> For now, I'll only use shelly to power the sensor, which also might not work OK as shelly outputs 3.3V and the sensor needs 5V :( A bit failed project on my end...
> Actually LD2410 does also work with 3.3V input. You just have to use the outer test points that are on the opposite side of the PCB compared to the usual 1.27 mm pins.
> […](#)

Mine are all powered with 3.3v from the 1.27mm pins, no issues on my many devices.

2023-08-18 13:58 UTC, jcastro commented
guys is this also compatible with the 2420?

2023-08-18 14:02 UTC, simonyel commented
> guys is this also compatible with the 2420?



> > Do you have the web server enabled?
> 
> Now that did not work as desired :) So now, my webserver is disabled on the ESP, but:
> 
> * I cannot reach it using the ESPHOME API anymore
> * pings are working, but that's about it
> * I cannot reflash firmware without the LD2410 anymore
>   I will have to disassemble the wall switch again, disconnect the device, connect it locally to USB-to-serial header and force reflash it :(
>   I wonder what happened - guess I will never know as I cannot add the device to HA or reach it in any way :(

If you know the API key, you can always add the device manually via IP. I usually copy it from the config file and :
- Delete the old "unavailable" device
- Settings > Devices and Services > Add Integration > ESPHome 
- Fill in the IP and leave the port as default
- Paste API key.

2023-08-18 18:36 UTC, Calcu2006 commented
Trying to remove web server (more info asap), but my esp is not starting (Ping to ip works, but can't connect)

Recieved this error:

```
[D][api.connection:1031]: Home Assistant 2023.8.2 (192.168.1.30): Connected successfully

abort() was called at PC 0x401f7847 on core 1


Backtrace:0x40083815:0x3ffd20200x400931f9:0x3ffd2040 0x400987bd:0x3ffd2060 0x401f7847:0x3ffd20e0 0x401f788e:0x3ffd2100 0x401f7987:0x3ffd2120 0x401f78e6:0x3ffd2140 0x400d47bb:0x3ffd2160 0x400d7ed6:0x3ffd2190 0x400d810d:0x3ffd21c0 0x40210cce:0x3ffd21f0 0x400d4a2f:0x3ffd2210 0x400d93cd:0x3ffd22f0 0x400ec836:0x3ffd2310 0x400d3ccb:0x3ffd2330 0x400d9365:0x3ffd23c0 0x40211a75:0x3ffd2430 0x40211afd:0x3ffd2450 0x400eb458:0x3ffd2470 0x400edada:0x3ffd24a0 0x400fcec9:0x3ffd24c0 




ELF file SHA256: 0000000000000000

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
```

2023-08-19 15:21 UTC, tomadan1968 commented
Hello, please if someone can help me, I added this yaml configuration to my esp32: 
esphome:
  name: detector-prezenta-test
  friendly_name: Detector Prezenta Test

external_components:
  source: github://regevbr/esphome@ld2410
  components: [ld2410]

esp32:
  board: esp32dev
  framework:
    type: arduino
 
api:
  services:
    - service: set_ld2410_bluetooth_password
      variables:
        password: string
      then:
        - bluetooth_password.set:
            id: ld2410_comp
            password: HiLink

uart:
  id: ld2410_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_comp

select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution
    baud_rate:
      name: baud rate
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410
    timeout:
      name: timeout
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
    light_threshold:
      name: light threshold

text_sensor:
  - platform: ld2410
    version:
      name: "presenece sensor version" 
    mac_address:
      name: "presenece sensor mac address"

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode" 
    bluetooth:
      name: control Bluetooth

binary_sensor:
  - platform: ld2410
    has_target:
      name: "presence"
    has_moving_target:
      name: "movement"
    has_still_target:
      name: "still"
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin: GPIO14
    name: gpio out pin presence
    device_class: presence

sensor:
  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
    g0: 
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1: 
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2: 
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3: 
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4: 
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5: 
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6: 
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7: 
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8: 
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy
    light:
      name: light

si imi apar urmatoarele erori la validare :

INFO ESPHome 2023.8.1
INFO Reading configuration /config/esphome/detector-prezenta-test.yaml...
Failed config

api: [source /config/esphome/detector-prezenta-test.yaml:15]
  
  Component api requires component network.
  services: 
    - service: set_ld2410_bluetooth_password
      variables: 
        password: string
      then: 
        - bluetooth_password.set: 
            id: ld2410_comp
            password: HiLink
number.ld2410: [source /config/esphome/detector-prezenta-test.yaml:58]
  platform: ld2410
  timeout: 
    name: timeout
  max_move_distance_gate: 
    name: max move distance gate
  max_still_distance_gate: 
    name: max still distance gate
  
  [g0] is an invalid option for [number.ld2410]. Please check the indentation.
  g0: 
    move_threshold: 
      name: g0 move threshold
    still_threshold: 
      name: g0 still threshold
  
  [g1] is an invalid option for [number.ld2410]. Please check the indentation.
  g1: 
    move_threshold: 
      name: g1 move threshold
    still_threshold: 
      name: g1 still threshold
  
  [g2] is an invalid option for [number.ld2410]. Please check the indentation.
  g2: 
    move_threshold: 
      name: g2 move threshold
    still_threshold: 
      name: g2 still threshold
  
  [g3] is an invalid option for [number.ld2410]. Please check the indentation.
  g3: 
    move_threshold: 
      name: g3 move threshold
    still_threshold: 
      name: g3 still threshold
  
  [g4] is an invalid option for [number.ld2410]. Please check the indentation.
  g4: 
    move_threshold: 
      name: g4 move threshold
    still_threshold: 
      name: g4 still threshold
  
  [g5] is an invalid option for [number.ld2410]. Please check the indentation.
  g5: 
    move_threshold: 
      name: g5 move threshold
    still_threshold: 
      name: g5 still threshold
  
  [g6] is an invalid option for [number.ld2410]. Please check the indentation.
  g6: 
    move_threshold: 
      name: g6 move threshold
    still_threshold: 
      name: g6 still threshold
  
  [g7] is an invalid option for [number.ld2410]. Please check the indentation.
  g7: 
    move_threshold: 
      name: g7 move threshold
    still_threshold: 
      name: g7 still threshold
  
  [g8] is an invalid option for [number.ld2410]. Please check the indentation.
  g8: 
    move_threshold: 
      name: g8 move threshold
    still_threshold: 
      name: g8 still threshold
  light_threshold: 
    name: light threshold
sensor.ld2410: [source /config/esphome/detector-prezenta-test.yaml:143]
  platform: ld2410
  moving_distance: 
    name: Moving distance (cm)
  still_distance: 
    name: Still Distance (cm)
  moving_energy: 
    name: Move Energy (%)
  still_energy: 
    name: Still Energy (%)
  detection_distance: 
    name: Distance Detection (cm)
  
  [g0] is an invalid option for [sensor.ld2410]. Please check the indentation.
  g0: 
    move_energy: 
      name: g0 move energy
    still_energy: 
      name: g0 still energy
  
  [g1] is an invalid option for [sensor.ld2410]. Please check the indentation.
  g1: 
    move_energy: 
      name: g1 move energy
    still_energy: 
      name: g1 still energy
  
  [g2] is an invalid option for [sensor.ld2410]. Please check the indentation.
  g2: 
    move_energy: 
      name: g2 move energy
    still_energy: 
      name: g2 still energy
  
  [g3] is an invalid option for [sensor.ld2410]. Please check the indentation.
  g3: 
    move_energy: 
      name: g3 move energy
    still_energy: 
      name: g3 still energy
  
  [g4] is an invalid option for [sensor.ld2410]. Please check the indentation.
  g4: 
    move_energy: 
      name: g4 move energy
    still_energy: 
      name: g4 still energy
  
 [...]

2023-08-19 15:57 UTC, pacjo commented
@tomadan1968 remove this part:
```
external_components:
source: github://regevbr/esphome@ld2410
components: [ld2410]
```
This component is now merged into main branch, so no need for external_component.

Also next time put your code into codeblock.

2023-08-19 15:59 UTC, tomadan1968 commented
> @tomadan1968 remove this part:
> 
> ```
> external_components:
> source: github://regevbr/esphome@ld2410
> components: [ld2410]
> ```
> 
> This component is now merged into main branch, so no need for external_component.
> 
> Also next time put your code into codeblock.

Thank you, nou i have another error:
`INFO ESPHome 2023.8.1
INFO Reading configuration /config/esphome/detector-prezenta-test.yaml...
Failed config

api: [source /config/esphome/detector-prezenta-test.yaml:11]
  
  Component api requires component network.
  services: 
    - service: set_ld2410_bluetooth_password
      variables: 
        password: string
      then: 
        - bluetooth_password.set: 
            id: ld2410_comp
            password: HiLink`

2023-08-19 17:13 UTC, pacjo commented
Please share your config with proper formatting. 3x\` (```) instead of ` like this:

` ``` `
your code
` ``` `

from error I suspect issue with networking. Now that I look, I can't see any wifi configuration. Do you have it?

2023-08-19 17:19 UTC, tomadan1968 commented
> Please share your config with proper formatting. 3x` (```) instead of ` like this:
> 
> `` ``` `` your code `` ``` ``
> 
> from error I suspect issue with networking. Now that I look, I can't see any wifi configuration. Do you have it?

`esphome:
  name: detector-prezenta-test
  friendly_name: Detector Prezenta Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
api:
  services:
    - service: set_ld2410_bluetooth_password
      variables:
        password: string
      then:
        - bluetooth_password.set:
            id: ld2410_comp
            password: HiLink

ota:
  password: "56ad0b8e4af645a680a57088563ae3c9"

captive_portal:

uart:
  id: ld2410_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_comp

select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution
    baud_rate:
      name: baud rate
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410
    timeout:
      name: timeout
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
    light_threshold:
      name: light threshold

text_sensor:
  - platform: ld2410
    version:
      name: "presenece sensor version" 
    mac_address:
      name: "presenece sensor mac address"

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode" 
    bluetooth:
      name: control Bluetooth

binary_sensor:
  - platform: ld2410
    has_target:
      name: "presence"
    has_moving_target:
      name: "movement"
    has_still_target:
      name: "still"
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin: GPIO14
    name: gpio out pin presence
    device_class: presence

sensor:
  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
    g0: 
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1: 
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2: 
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3: 
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4: 
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5: 
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6: 
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7: 
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8: 
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy
    light:
      name: light`

2023-08-19 17:21 UTC, tomadan1968 commented
`esphome:
  name: detector-prezenta-test
  friendly_name: Detector Prezenta Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
api:
  services:
    - service: set_ld2410_bluetooth_password
      variables:
        password: string
      then:
        - bluetooth_password.set:
            id: ld2410_comp
            password: HiLink

ota:
  password: "56ad0b8e4af645a680a57088563ae3c9"

captive_portal:

uart:
  id: ld2410_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_comp

select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution
    baud_rate:
      name: baud rate
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410
    timeout:
      name: timeout
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
    light_threshold:
      name: light threshold

text_sensor:
  - platform: ld2410
    version:
      name: "presenece sensor version" 
    mac_address:
      name: "presenece sensor mac address"

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode" 
    bluetooth:
      name: control Bluetooth

binary_sensor:
  - platform: ld2410
    has_target:
      name: "presence"
    has_moving_target:
      name: "movement"
    has_still_target:
      name: "still"
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin: GPIO14
    name: gpio out pin presence
    device_class: presence

sensor:
  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
    g0: 
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1: 
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2: 
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3: 
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4: 
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5: 
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6: 
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7: 
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8: 
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy
    light:
      name: light`

2023-08-19 17:29 UTC, tomadan1968 commented
esphome:
  name: detector-prezenta-test
  friendly_name: Detector Prezenta Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
api:
  services:
    - service: set_ld2410_bluetooth_password
      variables:
        password: string
      then:
        - bluetooth_password.set:
            id: ld2410_comp
            password: HiLink

ota:
  password: "56ad0b8e4af645a680a57088563ae3c9"

captive_portal:

uart:
  id: ld2410_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_comp

select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution
    baud_rate:
      name: baud rate
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410
    timeout:
      name: timeout
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
    light_threshold:
      name: light threshold

text_sensor:
  - platform: ld2410
    version:
      name: "presenece sensor version" 
    mac_address:
      name: "presenece sensor mac address"

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode" 
    bluetooth:
      name: control Bluetooth

binary_sensor:
  - platform: ld2410
    has_target:
      name: "presence"
    has_moving_target:
      name: "movement"
    has_still_target:
      name: "still"
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin: GPIO14
    name: gpio out pin presence
    device_class: presence

sensor:
  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
    g0: 
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1: 
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2: 
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3: 
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4: 
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5: 
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6: 
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7: 
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8: 
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy
    light:
      name: light

2023-08-19 17:31 UTC, tomadan1968 commented
I entered the correct code but I don't understand why it doesn't appear properly

2023-08-19 17:37 UTC, pacjo commented
## formatting info
and I don't know how to properly escape codeblock. Anyway it should be like this:

backtickbacktickbacktick
code goes here
backtickbacktickbacktick

The first one was almost good, but you need additional newline after quoteblock. You can use preview option to check the formatting. Could you also delete the unformatted messages?

## Issue
The api section should look something like this:
```
services:
  - service: set_ld2410_bluetooth_password
    variables:
      password: string
    then:
      - bluetooth_password.set:
          id: ld2410_comp
          password: <your passsword>
```
can you check the indentation?

2023-08-19 18:04 UTC, tomadan1968 commented
And the entities do not appear in the ESP integration
```
esphome:
  name: detector-prezenta-test
  friendly_name: Detector Prezenta Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
api:
  services:
    - service: set_ld2410_bluetooth_password
      variables:
        password: string
      then:
        - bluetooth_password.set:
            id: ld2410_comp
            password: HiLink

ota:
  password: "56ad0b8e4af645a680a57088563ae3c9"

captive_portal:

uart:
  id: ld2410_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_comp

select:
  - platform: ld2410
    distance_resolution:
      name: distance resolution
    baud_rate:
      name: baud rate
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410
    timeout:
      name: timeout
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
    light_threshold:
      name: light threshold

text_sensor:
  - platform: ld2410
    version:
      name: "presenece sensor version" 
    mac_address:
      name: "presenece sensor mac address"

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode" 
    bluetooth:
      name: control Bluetooth

binary_sensor:
  - platform: ld2410
    has_target:
      name: "presence"
    has_moving_target:
      name: "movement"
    has_still_target:
      name: "still"
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin: GPIO14
    name: gpio out pin presence
    device_class: presence

sensor:
  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
    g0: 
      move_energy:
        name: g0 move energy
      still_energy:
        name: g0 still energy
    g1: 
      move_energy:
        name: g1 move energy
      still_energy:
        name: g1 still energy
    g2: 
      move_energy:
        name: g2 move energy
      still_energy:
        name: g2 still energy
    g3: 
      move_energy:
        name: g3 move energy
      still_energy:
        name: g3 still energy
    g4: 
      move_energy:
        name: g4 move energy
      still_energy:
        name: g4 still energy
    g5: 
      move_energy:
        name: g5 move energy
      still_energy:
        name: g5 still energy
    g6: 
      move_energy:
        name: g6 move energy
      still_energy:
        name: g6 still energy
    g7: 
      move_energy:
        name: g7 move energy
      still_energy:
        name: g7 still energy
    g8: 
      move_energy:
        name: g8 move energy
      still_energy:
        name: g8 still energy
    light:
      name: light
```
It only appears:
![image](https://github.com/esphome/esphome/assets/99090481/3a3ffa89-4e88-4cbd-aa2a-3d753166fc12)

2023-08-19 18:06 UTC, tomadan1968 commented
> ## formatting info
> and I don't know how to properly escape codeblock. Anyway it should be like this:
> 
> backtickbacktickbacktick code goes here backtickbacktickbacktick
> 
> [official github quide](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
> 
> The first one was almost good, but you need additional newline after quoteblock. You can use preview option to check the formatting. Could you also delete the unformatted messages?
> 
> ## Issue
> The api section should look something like this:
> 
> ```
> services:
>   - service: set_ld2410_bluetooth_password
>     variables:
>       password: string
>     then:
>       - bluetooth_password.set:
>           id: ld2410_comp
>           password: <your passsword>
> ```
> 
> can you check the indentation?

I post new message up...

2023-08-19 18:24 UTC, pacjo commented
> And the entities do not appear in the ESP integration

Hmm, it compiles fine now? Did you upload the version you shared above?

What do you have in logs from esphome?

2023-08-19 18:28 UTC, tomadan1968 commented
> > Iar entitățile nu apar în integrarea ESP
> 
> Hmm, se compilează bine acum? Ați încărcat versiunea pe care ați distribuit-o mai sus?
> 
> Ce aveți în buștenii de la esphome?

Yes, I uploaded it but it does not compile wirelessly, only OTA, in the log it appears that it works but I have no entity in the esp integration
INFO ESPHome 2023.8.1
INFO Reading configuration /config/esphome/detector-prezenta-test.yaml...
INFO Starting log output from detector-prezenta-test.local using esphome API
INFO Successfully connected to detector-prezenta-test.local
[21:28:00][I][app:102]: ESPHome version 2023.8.1 compiled on Aug 19 2023, 20:17:28
[21:28:00][C][wifi:543]: WiFi:
[21:28:00][C][wifi:379]:   Local MAC: 78:21:84:E2:16:5C
[21:28:00][C][wifi:380]:   SSID: 'Dan UPC'[redacted]
[21:28:00][C][wifi:381]:   IP Address: 192.168.68.74
[21:28:00][C][wifi:383]:   BSSID: 28:87:BA:C1:41:4E[redacted]
[21:28:00][C][wifi:384]:   Hostname: 'detector-prezenta-test'
[21:28:00][C][wifi:386]:   Signal strength: -63 dB ▂▄▆█
[21:28:00][C][wifi:390]:   Channel: 2
[21:28:00][C][wifi:391]:   Subnet: 255.255.252.0
[21:28:00][C][wifi:392]:   Gateway: 192.168.68.1
[21:28:00][C][wifi:393]:   DNS1: 213.233.64.231
[21:28:00][C][wifi:394]:   DNS2: 213.233.64.233
[21:28:00][C][logger:301]: Logger:
[21:28:00][C][logger:302]:   Level: DEBUG
[21:28:00][C][logger:303]:   Log Baud Rate: 115200
[21:28:00][C][uart.arduino_esp32:124]: UART Bus 1:
[21:28:00][C][uart.arduino_esp32:125]:   TX Pin: GPIO17
[21:28:00][C][uart.arduino_esp32:126]:   RX Pin: GPIO16
[21:28:00][C][uart.arduino_esp32:128]:   RX Buffer Size: 256
[21:28:00][C][uart.arduino_esp32:130]:   Baud Rate: 256000 baud
[21:28:00][C][uart.arduino_esp32:131]:   Data Bits: 8
[21:28:00][C][uart.arduino_esp32:132]:   Parity: NONE
[21:28:00][C][uart.arduino_esp32:133]:   Stop bits: 1
[21:28:00][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'gpio out pin presence'
[21:28:00][C][gpio.binary_sensor:015]:   Device Class: 'presence'
[21:28:00][C][gpio.binary_sensor:016]:   Pin: GPIO14
[21:28:00][C][ld2410:022]: LD2410:
[21:28:00][C][ld2410:024]:   TargetBinarySensor 'presence'
[21:28:00][C][ld2410:024]:     Device Class: 'occupancy'
[21:28:00][C][ld2410:025]:   MovingTargetBinarySensor 'movement'
[21:28:00][C][ld2410:025]:     Device Class: 'motion'
[21:28:00][C][ld2410:026]:   StillTargetBinarySensor 'still'
[21:28:00][C][ld2410:026]:     Device Class: 'occupancy'
[21:28:00][C][ld2410:027]:   OutPinPresenceStatusBinarySensor 'out pin presence status'
[21:28:00][C][ld2410:027]:     Device Class: 'presence'
[21:28:00][C][ld2410:068]:   EngineeringModeSwitch 'engineering mode'
[21:28:00][C][ld2410:070]:     Icon: 'mdi:pulse'
[21:28:00][C][ld2410:079]:     Device Class: 'switch'
[21:28:00][C][ld2410:091]:     Restore Mode: always OFF
[21:28:00][C][ld2410:068]:   BluetoothSwitch 'control Bluetooth'
[21:28:00][C][ld2410:070]:     Icon: 'mdi:bluetooth'
[21:28:00][C][ld2410:079]:     Device Class: 'switch'
[21:28:00][C][ld2410:040]:     Accuracy Decimals: 0
[21:28:00][C][ld2410:040]:     Icon: 'mdi:signal-distance-variant'
[21:28:00][C][ld2410:041]:   StillTargetDistanceSensor 'Still Distance (cm)'
[21:28:00][C][ld2410:041]:     Device Class: 'distance'
[21:28:00][C][ld2410:041]:     State Class: ''
[21:28:00][C][ld2410:041]:     Unit of Measurement: 'cm'
[21:28:00][C][ld2410:041]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:041]:     Icon: 'mdi:signal-distance-variant'
[21:28:01][C][ld2410:042]:   MovingTargetEnergySensor 'Move Energy (%)'
[21:28:01][C][ld2410:042]:     State Class: ''
[21:28:01][C][ld2410:042]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:042]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:042]:     Icon: 'mdi:motion-sensor'
[21:28:01][C][ld2410:043]:   StillTargetEnergySensor 'Still Energy (%)'
[21:28:01][C][ld2410:043]:     State Class: ''
[21:28:01][C][ld2410:043]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:043]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:043]:     Icon: 'mdi:flash'
[21:28:01][C][ld2410:044]:   DetectionDistanceSensor 'Distance Detection (cm)'
[21:28:01][C][ld2410:044]:     Device Class: 'distance'
[21:28:01][C][ld2410:044]:     State Class: ''
[21:28:01][C][ld2410:044]:     Unit of Measurement: 'cm'
[21:28:01][C][ld2410:044]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:046]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:046]:     Icon: 'mdi:flash'
[21:28:01][C][ld2410:046]:   NthGateStillSesnsor 'g4 still energy'
[21:28:01][C][ld2410:046]:     State Class: ''
[21:28:01][C][ld2410:046]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:046]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:046]:     Icon: 'mdi:flash'
[21:28:01][C][ld2410:046]:   NthGateStillSesnsor 'g5 still energy'
[21:28:01][C][ld2410:046]:     State Class: ''
[21:28:01][C][ld2410:046]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:046]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:046]:     Icon: 'mdi:flash'
[21:28:01][C][ld2410:046]:   NthGateStillSesnsor 'g6 still energy'
[21:28:01][C][ld2410:046]:     State Class: ''
[21:28:01][C][ld2410:046]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:046]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:046]:     Icon: 'mdi:flash'
[21:28:01][C][ld2410:046]:   NthGateStillSesnsor 'g7 still energy'
[21:28:01][C][ld2410:046]:     State Class: ''
[21:28:01][C][ld2410:046]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:046]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:046]:     Icon: 'mdi:flash'
[21:28:01][C][ld2410:046]:   NthGateStillSesnsor 'g8 still energy'
[21:28:01][C][ld2410:046]:     State Class: ''
[21:28:01][C][ld2410:046]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:046]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:046]:     Icon: 'mdi:flash'
[21:28:01][C][ld2410:049]:   NthGateMoveSesnsor 'g0 move energy'
[21:28:01][C][ld2410:049]:     State Class: ''
[21:28:01][C][ld2410:049]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:049]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:049]:     Icon: 'mdi:motion-sensor'
[21:28:01][C][ld2410:049]:   NthGateMoveSesnsor 'g1 move energy'
[21:28:01][C][ld2410:049]:     State Class: ''
[21:28:01][C][ld2410:049]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:049]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:049]:     Icon: 'mdi:motion-sensor'
[21:28:01][C][ld2410:049]:   NthGateMoveSesnsor 'g2 move energy'
[21:28:01][C][ld2410:049]:     State Class: ''
[21:28:01][C][ld2410:049]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:049]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:049]:     Icon: 'mdi:motion-sensor'
[21:28:01][C][ld2410:049]:   NthGateMoveSesnsor 'g3 move energy'
[21:28:01][C][ld2410:049]:     State Class: ''
[21:28:01][C][ld2410:049]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:049]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:049]:     Icon: 'mdi:motion-sensor'
[21:28:01][C][ld2410:049]:   NthGateMoveSesnsor 'g4 move energy'
[21:28:01][C][ld2410:049]:     State Class: ''
[21:28:01][C][ld2410:049]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:049]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:049]:     Icon: 'mdi:motion-sensor'
[21:28:01][C][ld2410:049]:   NthGateMoveSesnsor 'g5 move energy'
[21:28:01][C][ld2410:049]:     State Class: ''
[21:28:01][C][ld2410:049]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:049]:   NthGateMoveSesnsor 'g7 move energy'
[21:28:01][C][ld2410:049]:     State Class: ''
[21:28:01][C][ld2410:049]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:049]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:049]:     Icon: 'mdi:motion-sensor'
[21:28:01][C][ld2410:049]:   NthGateMoveSesnsor 'g8 move energy'
[21:28:01][C][ld2410:049]:     State Class: ''
[21:28:01][C][ld2410:049]:     Unit of Measurement: '%'
[21:28:01][C][ld2410:049]:     Accuracy Decimals: 0
[21:28:01][C][ld2410:049]:     Icon: 'mdi:motion-sensor'
[21:28:01][C][ld2410:053]:   VersionTextSensor 'presenece sensor version'
[21:28:01][C][ld2410:053]:     Icon: 'mdi:chip'
[21:28:01][C][ld2410:054]:   Mac [...]

2023-08-19 18:32 UTC, tomadan1968 commented
Can you show me a functional yaml configuration for the sensor that you have?

2023-08-19 18:35 UTC, pacjo commented
can you try removing and adding the device again in home assistant?

> Can you show me a functional yaml configuration for the sensor that you have?

Sure:
```
esphome:
  name: esp32-roomsensor-kamil
  friendly_name: esp32-roomsensor-kamil

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: <api_key>
  
  services:
    - service: set_ld2410_bluetooth_password
      variables:
        password: string
      then:
        - bluetooth_password.set:
            id: ld2410_comp
            password: !lambda 'return password;'

ota:
  password: <ota_password>

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Roomsensor-Kamil"
    password: "9byRr8EZACpo"

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

uart:
  id: ld2410_uart
  tx_pin: 1
  rx_pin: 3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

ld2410:
  uart_id: ld2410_uart
  throttle: 1500ms
  id: ld2410_comp

select:
  - platform: ld2410
    distance_resolution:
      name: "Distance resolution"
    baud_rate:
      name: "Baud rate"
    light_function:
      name: "light function"
    out_pin_level:
      name: "Out pin level"

button:
  - platform: ld2410
    factory_reset:
      name: "Factory reset module"
    restart:
      name: "Restart module"
    query_params:
      name: "Query parameters"

number:
  - platform: ld2410
    timeout:
      name: Timeout
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: G0 move threshold
      still_threshold:
        name: G0 still threshold
    g1:
      move_threshold:
        name: G1 move threshold
      still_threshold:
        name: G1 still threshold
    g2:
      move_threshold:
        name: G2 move threshold
      still_threshold:
        name: G2 still threshold
    g3:
      move_threshold:
        name: G3 move threshold
      still_threshold:
        name: G3 still threshold
    g4:
      move_threshold:
        name: G4 move threshold
      still_threshold:
        name: G4 still threshold
    g5:
      move_threshold:
        name: G5 move threshold
      still_threshold:
        name: G5 still threshold
    g6:
      move_threshold:
        name: G6 move threshold
      still_threshold:
        name: G6 still threshold
    g7:
      move_threshold:
        name: G7 move threshold
      still_threshold:
        name: G7 still threshold
    g8:
      move_threshold:
        name: G8 move threshold
      still_threshold:
        name: G8 still threshold
    light_threshold:
      name: light threshold

text_sensor:
  - platform: ld2410
    version:
      name: "Module version" 
    mac_address:
      name: "Module mac address"

switch:
  - platform: ld2410
    engineering_mode:
      name: "Engineering mode" 
    bluetooth:
      name: "Bluetooth control"

binary_sensor:
  - platform: ld2410
    has_target:
      name: "Presence"
    has_moving_target:
      name: "Moving target"
    has_still_target:
      name: "Still target"

sensor:
  - platform: ld2410
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Detection Distance (cm)"
    g0:
      move_energy:
        name: G0 move energy
      still_energy:
        name: G0 still energy
    g1:
      move_energy:
        name: G1 move energy
      still_energy:
        name: G1 still energy
    g2:
      move_energy:
        name: G2 move energy
      still_energy:
        name: G2 still energy
    g3:
      move_energy:
        name: G3 move energy
      still_energy:
        name: G3 still energy
    g4:
      move_energy:
        name: G4 move energy
      still_energy:
        name: G4 still energy
    g5:
      move_energy:
        name: G5 move energy
      still_energy:
        name: G5 still energy
    g6:
      move_energy:
        name: G6 move energy
      still_energy:
        name: G6 still energy
    g7:
      move_energy:
        name: G7 move energy
      still_energy:
        name: G7 still energy
    g8:
      move_energy:
        name: G8 move energy
      still_energy:
        name: G8 still energy
    light:
      name: light

  - platform: bh1750
    name: "Illuminance"
    address: 0x23
    update_interval: 5s
```

There's some additional stuff for light sensor, but nothing crazy.

2023-08-19 20:27 UTC, tomadan1968 commented
> can you try removing and adding the device again in home assistant?
> 
> > Can you show me a functional yaml configuration for the sensor that you have?
> 
> Sure:
> 
> ```
> esphome:
>   name: esp32-roomsensor-kamil
>   friendly_name: esp32-roomsensor-kamil
> 
> esp32:
>   board: esp32dev
>   framework:
>     type: esp-idf
> 
> # Enable logging
> logger:
>   baud_rate: 0
> 
> # Enable Home Assistant API
> api:
>   encryption:
>     key: <api_key>
>   
>   services:
>     - service: set_ld2410_bluetooth_password
>       variables:
>         password: string
>       then:
>         - bluetooth_password.set:
>             id: ld2410_comp
>             password: !lambda 'return password;'
> 
> ota:
>   password: <ota_password>
> 
> wifi:
>   ssid: !secret wifi_ssid
>   password: !secret wifi_password
> 
>   # Enable fallback hotspot (captive portal) in case wifi connection fails
>   ap:
>     ssid: "Esp32-Roomsensor-Kamil"
>     password: "9byRr8EZACpo"
> 
> i2c:
>   sda: 21
>   scl: 22
>   scan: true
>   id: bus_a
> 
> uart:
>   id: ld2410_uart
>   tx_pin: 1
>   rx_pin: 3
>   baud_rate: 256000
>   parity: NONE
>   stop_bits: 1
> 
> esp32_ble_tracker:
>   scan_parameters:
>     interval: 1100ms
>     window: 1100ms
>     active: true
> 
> bluetooth_proxy:
>   active: true
> 
> ld2410:
>   uart_id: ld2410_uart
>   throttle: 1500ms
>   id: ld2410_comp
> 
> select:
>   - platform: ld2410
>     distance_resolution:
>       name: "Distance resolution"
>     baud_rate:
>       name: "Baud rate"
>     light_function:
>       name: "light function"
>     out_pin_level:
>       name: "Out pin level"
> 
> button:
>   - platform: ld2410
>     factory_reset:
>       name: "Factory reset module"
>     restart:
>       name: "Restart module"
>     query_params:
>       name: "Query parameters"
> 
> number:
>   - platform: ld2410
>     timeout:
>       name: Timeout
>     max_move_distance_gate:
>       name: max move distance gate
>     max_still_distance_gate:
>       name: max still distance gate
>     g0:
>       move_threshold:
>         name: G0 move threshold
>       still_threshold:
>         name: G0 still threshold
>     g1:
>       move_threshold:
>         name: G1 move threshold
>       still_threshold:
>         name: G1 still threshold
>     g2:
>       move_threshold:
>         name: G2 move threshold
>       still_threshold:
>         name: G2 still threshold
>     g3:
>       move_threshold:
>         name: G3 move threshold
>       still_threshold:
>         name: G3 still threshold
>     g4:
>       move_threshold:
>         name: G4 move threshold
>       still_threshold:
>         name: G4 still threshold
>     g5:
>       move_threshold:
>         name: G5 move threshold
>       still_threshold:
>         name: G5 still threshold
>     g6:
>       move_threshold:
>         name: G6 move threshold
>       still_threshold:
>         name: G6 still threshold
>     g7:
>       move_threshold:
>         name: G7 move threshold
>       still_threshold:
>         name: G7 still threshold
>     g8:
>       move_threshold:
>         name: G8 move threshold
>       still_threshold:
>         name: G8 still threshold
>     light_threshold:
>       name: light threshold
> 
> text_sensor:
>   - platform: ld2410
>     version:
>       name: "Module version" 
>     mac_address:
>       name: "Module mac address"
> 
> switch:
>   - platform: ld2410
>     engineering_mode:
>       name: "Engineering mode" 
>     bluetooth:
>       name: "Bluetooth control"
> 
> binary_sensor:
>   - platform: ld2410
>     has_target:
>       name: "Presence"
>     has_moving_target:
>       name: "Moving target"
>     has_still_target:
>       name: "Still target"
> 
> sensor:
>   - platform: ld2410
>     moving_distance:
>       name: "Moving distance (cm)"
>     still_distance:
>       name: "Still Distance (cm)"
>     moving_energy:
>       name: "Move Energy (%)"
>     still_energy:
>       name: "Still Energy (%)"
>     detection_distance:
>       name: "Detection Distance (cm)"
>     g0:
>       move_energy:
>         name: G0 move energy
>       still_energy:
>         name: G0 still energy
>     g1:
>       move_energy:
>         name: G1 move energy
>       still_energy:
>         name: G1 still energy
>     g2:
>       move_energy:
>         name: G2 move energy
>       still_energy:
>         name: G2 still energy
>     g3:
>       move_energy:
>         name: G3 move energy
>       still_energy:
>         name: G3 still energy
>     g4:
>       move_energy:
>         name: G4 move energy
>       still_energy:
>         name: G4 still energy
>     g5:
>       move_energy:
>         name: G5 move energy
>       still_energy:
>         name: G5 still energy
>     g6:
>       move_energy:
>         name: G6 move energy
>       still_energy:
>         name: G6 still energy
>     g7:
>       move_energy:
>         name: G7 move energy
>       still_energy:
>         name: G7 still energy
>     g8:
>       move_energy:
>         name: G8 move energy
>       still_energy:
>         name: G8 still energy
>     light:
>       name: light
> 
>   - platform: bh1750
>     name: "Illuminance"
>     address: 0x23
>     update_interval: 5s
> ```
> 
> There's some additional stuff for light sensor, but nothing crazy.

Thank you very much, it works very well now.

2023-08-20 05:45 UTC, inane69 commented
I'm stuck trying to understand where I put my custom values for the gates now.... I don't see any examples that have them.

2023-08-20 06:21 UTC, athua commented
> I'm stuck trying to understand where I put my custom values for the gates now.... I don't see any examples that have them.

They are now configured in HA and not in the YAML.

2023-08-20 06:21 UTC, inane69 commented
> I'm stuck trying to understand where I put my custom values for the gates now.... I don't see any examples that have them.

answering my own question, this was moved to the HA interface as sliders to set the value which is nice but man, that was not clear in anything I read here or in the ESPHome doc page for this sensor

2023-08-20 14:56 UTC, distante commented
@regevbr thank you for this excellent PR! 

I have a couple of questions and one comment if I may.

1. Is there a reason why the gate selectors go from 2 to 8 instead of 0 to 8 ? 
   <img width="557" alt="image" src="https://github.com/esphome/esphome/assets/5490201/eee48f5a-5249-4e88-95d7-7326d9e20e26">

2. The maximal distance is calculated using the gate number and the distance resolution, correct? maybe the example/configuration card should change the values to, instead of show `0 - 1 - 2`, to show `0.2 - 0.4 - 0.6` or `0.75 - 1.5` etc?

4. The example card in the docs is using names that were changed during the review of this PR 👀 

Thanks again!

2023-08-21 07:42 UTC, regevbr commented
> @regevbr thank you for this excellent PR!
> 
> I have a couple of questions and one comment if I may.
> 
> 1. Is there a reason why the gate selectors go from 2 to 8 instead of 0 to 8 ?
>    <img alt="image" width="557" src="https://user-images.githubusercontent.com/5490201/261859266-eee48f5a-5249-4e88-95d7-7326d9e20e26.png">
> 2. The maximal distance is calculated using the gate number and the distance resolution, correct? maybe the example/configuration card should change the values to, instead of show `0 - 1 - 2`, to show `0.2 - 0.4 - 0.6` or `0.75 - 1.5` etc?
> 3. The example card in the docs is using names that were changed during the review of this PR 👀
> 
> Thanks again!

Gladly.

1. That is the technical specification
2. If you can find a way, please submit a PR
3. Not sure what you mean

2023-08-21 07:55 UTC, distante commented
> 1. That is the technical specification
So the minimun gate distance should always be 0.4 or 1.5, correct?

> 2. If you can find a way, please submit a PR
Will try, probably it will be easier on the card level.

> 3. Not sure what you mean
Some entities' names are wrong in the example card from the docs.

2023-08-21 08:00 UTC, regevbr commented
> > 1. That is the technical specification
> >    So the minimun gate distance should always be 0.4 or 1.5, correct?
> 
> > 2. If you can find a way, please submit a PR
> >    Will try, probably it will be easier on the card level.
> 
> > 3. Not sure what you mean
> >    Some entities' names are wrong in the example card from the docs.

1. indeed
2. great
3. please submit a PR so we can fix it :-)

2023-08-21 08:52 UTC, dflvunoooooo commented
Is there a reason why the light sensor is listed under diagnostic? And it is not displayed as a graph in HA.

2023-08-21 10:58 UTC, regevbr commented
> Is there a reason why the light sensor is listed under diagnostic? And it is not displayed as a graph in HA?

You need to enable engineering mode in order to receive it (sadly) and keeping it on at all times can be very "expensive" so it was set up as a diagnostic. If you want, you can change its type from your esphome config - see entity category in https://esphome.io/components/sensor/#config-sensor

2023-08-21 11:49 UTC, dflvunoooooo commented
> You need to enable engineering mode in order to receive it (sadly) and keeping it on at all times can be very "expensive" so it was set up as a diagnostic. If you want, you can change its type from your esphome config - see entity category in https://esphome.io/components/sensor/#config-sensor

Thanks for your answer! I see, what do you mean by "expensive"? I will try to change the type. What type do I have to change? The device claass? I was unable to find the type diagnostic anywhere.

2023-08-21 15:48 UTC, regevbr commented
> > You need to enable engineering mode in order to receive it (sadly) and keeping it on at all times can be very "expensive" so it was set up as a diagnostic. If you want, you can change its type from your esphome config - see entity category in https://esphome.io/components/sensor/#config-sensor
> 
> Thanks for your answer! I see, what do you mean by "expensive"? I will try to change the type. What type do I have to change? The device claass? I was unable to find the type diagnostic anywhere.

you need to set it to "" in order to remove the diagnostic category, as mentioned in the docs I referenced.
expensive as in it causes the device to send a lot more data then it is built to, which should only be used when caliabraint the device. You can keep it on, but that is not the intended use