add person sensor (SEN21231) from usefulsensors
OttoWinter/esphomeyaml pull request #4454
Opened 2023-02-17 02:05 UTC by shreyaskarnik

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1925

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
i2c:
  sda: 21
  scl: 22
sensor:
  - platform: sen21231
  - id: person_sensor
    name: "Person Sensor"

## can also turn this into a binary sensor as a motion detection sensor 
binary_sensor:
  - platform: status
    name: "Sense Status"
  - platform: template
    name: Person Sensor Binary
    device_class: motion
    lambda: |-
      if (id(person_sensor).state) {
        return true;
      } else {
        return false;
      }

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs). https://github.com/esphome/esphome-docs/pull/2678

2023-02-17 03:05 UTC, jesserockz requested changes

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sen21231.cpp
> +static const char *TAG = "sen21231_sensor.sensor";
```suggestion
static const char *const TAG = "sen21231_sensor.sensor";
```

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sen21231.cpp
> +
No need for an empty function
```suggestion
```

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sen21231.cpp
> +  this->read_data_();
Dont read during the dump please
```suggestion
```

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sen21231.cpp
> +}
```suggestion
 LOG_UPDATE_INTERVAL(this);
}
```

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sen21231.cpp
> +  }
This is a sensor, it should publish a number...
```suggestion
  this->publish_state(results.num_faces);
```

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sen21231.h
> +  void setup() override;
Not needed
```suggestion
```

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sen21231.h
> +  void read_data_();
```suggestion
 protected:
  void read_data_();
```

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sen21231.h
> +class Sen21231Sensor : public sensor::Sensor, public PollingComponent, public i2c::I2CDevice {
Readability
```suggestion

class Sen21231Sensor : public sensor::Sensor, public PollingComponent, public i2c::I2CDevice {
```

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sensor.py
> +    .extend(i2c.i2c_device_schema(CONF_I2C_ADDR))
No need for a new CONST for the address
```suggestion
    .extend(i2c.i2c_device_schema(0x62))
```

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sensor.py
> +
```suggestion
```

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sensor.py
> +DEPENDENCIES = ["i2c"]
```suggestion
CODEOWNERS = ["@shreyaskarnik"]
DEPENDENCIES = ["i2c"]
```

2023-02-17 03:05 UTC, jesserockz commented on esphome/components/sen21231/sensor.py
> +    yield i2c.register_i2c_device(var, config)
```suggestion
async def to_code(config):
    var = await sensor.new_sensor(config)
    await cg.register_component(var, config)
    await i2c.register_i2c_device(var, config)
```

2023-02-17 03:53 UTC, shreyaskarnik commented
Thank you for your feedback @jesserockz really really appreciate it. Changes requested have been applied and tested on ESP32 based system.

2023-02-17 08:48 UTC, SeByDocKy commented
Sound a great addition :). How good is this sensor ?

2023-02-17 14:07 UTC, shreyaskarnik commented
@SeByDocKy the sensor works pretty well in good lighting conditions. So far I've had no issues.

2023-02-17 14:08 UTC, SeByDocKy commented
> @SeByDocKy the sensor works pretty well in good lighting conditions. So far I've had no issues.

Ok I ordered two of them.... to try your PR :)

2023-02-20 04:03 UTC, jesserockz requested changes

2023-02-20 04:03 UTC, jesserockz commented on esphome/components/sen21231/sensor.py
> +    )
```suggestion
    sensor.sensor_schema(
        Sen21231Sensor, icon=ICON_MOTION_SENSOR, accuracy_decimals=1
    )
```

2023-02-20 04:03 UTC, jesserockz commented on esphome/components/sen21231/sensor.py
> +    .extend(cv.polling_component_schema("30s"))
We always try to default sensors to 60s unless there is a specific reason? Its easy for a user to override this in yaml.
```suggestion
    .extend(cv.polling_component_schema("60s"))
```

2023-02-20 04:03 UTC, jesserockz commented on esphome/components/sen21231/sen21231.h
> +} person_sensor_face_t;
```suggestion
using person_sensor_face_t = struct __attribute__((__packed__)) {
  uint8_t box_confidence;  // Byte 1.
  uint8_t box_left;        // Byte 2.
  uint8_t box_top;         // Byte 3.
  uint8_t box_right;       // Byte 4.
  uint8_t box_bottom;      // Byte 5.
  int8_t id_confidence;    // Byte 6.
  int8_t id;               // Byte 7
  uint8_t is_facing;       // Byte 8.
};
```

2023-02-20 04:03 UTC, jesserockz commented on esphome/components/sen21231/sen21231.h
> +} person_sensor_results_t;
```suggestion
using person_sensor_results_t = struct __attribute__((__packed__)) {
  person_sensor_results_header_t header;                      // Bytes 0-4.
  int8_t num_faces;                                           // Byte 5.
  person_sensor_face_t faces[PERSON_SENSOR_MAX_FACES_COUNT];  // Bytes 6-37.
  uint16_t checksum;                                          // Bytes 38-39.
};
```

2023-02-20 04:17 UTC, shreyaskarnik commented
Thanks @jesserockz for the suggestions I have applied all of them. Really appreciate your feedback and time to review the PR! 🙌

2023-02-23 00:25 UTC, jesserockz approved these changes

2023-02-23 00:37 UTC, merged