Added pzemdc reset energy action
OttoWinter/esphomeyaml pull request #4481
Opened 2023-02-23 19:06 UTC by KG3RK3N

# What does this implement/fix?

I've added a action to reset the energy on the pzemdc device.
Additionally I removed `frequency_sensor_` & `powerfactor_sensor_` because that was not used and are not documented. This sensors only available for AC devices.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2700

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

- [ ] RP2040
## Example entry for `config.yaml`:

```yaml

uart:
  tx_pin: D1
  rx_pin: D2
  baud_rate: 9600
  stop_bits: 2

sensor:
  - platform: pzemdc
    id: pzemdc_1
    current:
      name: "PZEM-017 Current"
    voltage:
      name: "PZEM-017 Voltage"
    power:
      name: "PZEM-017 Power"
    energy:
      name: "PZEM-017 Energy"
    update_interval: 60s

on_...:
  then:
    - pzemdc.reset_energy: pzemdc_1

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-26 19:38 UTC, jesserockz requested changes

2023-02-26 19:38 UTC, jesserockz commented on esphome/components/pzemdc/pzemdc.h
> +  void reset_energy_();
Just make this public and remove the friend class stuff. Then this can be called from lambdas too

2023-02-27 19:06 UTC, KG3RK3N commented on esphome/components/pzemdc/pzemdc.h
> +  void reset_energy_();
Makes sense, done 👍

2023-03-08 18:50 UTC, jesserockz commented on esphome/components/pzemdc/pzemdc.h
> +
Dont need to forward declare anymore
```suggestion
```

2023-03-08 18:50 UTC, jesserockz commented on esphome/components/pzemdc/sensor.py
> +            cv.Required(CONF_ID): cv.use_id(PZEMDC),
This allows auto linking if you only have 1 in yaml
```suggestion
            cv.GenerateID(CONF_ID): cv.use_id(PZEMDC),
```

2023-03-08 18:51 UTC, jesserockz approved these changes

2023-03-08 19:13 UTC, merged