Add check for completed upload size to prevent incomplete updates and potential bootloops
OttoWinter/esphomeyaml pull request #4482
Opened 2023-02-24 17:16 UTC by nuclearcat

In certain situations, the update process may terminate prematurely due to connection resets or other bugs, resulting in an incomplete update. This can lead to a bootloop, which would require manual recovery and be particularly inconvenient if the device is installed in a hard-to-reach location.

To avoid this issue, a simple check for completed upload size can be added to ensure that the update is fully uploaded before proceeding.

# What does this implement/fix?

## Types of changes

- [X ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-08 01:05 UTC, jesserockz requested changes

2023-03-08 01:05 UTC, jesserockz commented on esphome/components/web_server_base/web_server_base.cpp
> +      return;
This should also call abort to clear out anything
```suggestion
      Update.abort();
      return;
```

2023-03-08 18:27 UTC, jesserockz approved these changes

2023-03-08 18:43 UTC, jesserockz requested changes
Just actually tested this on ESP32 and its failing everytime, the content length sent from the browser actually includes more than just the firmware bytes...

```
[07:39:42][I][web_server_base:083]: Size: 1006778 != 1006576
[07:39:42][I][web_server_base:084]: OTA update incomplete, terminating
```


![image](https://user-images.githubusercontent.com/3060199/223805736-5d20bbf6-9b13-4cc6-8e7a-8986f9f2b2f7.png)


```shell
$ ls -al firmware.bin
-rw-r--r-- 1 jesse users 1006576 Mar  9 07:38 firmware.bin
```

2023-03-09 06:46 UTC, nuclearcat commented
It seems there is no way to get real data length from ESPAsyncWebServer. It exists in private _parsedLength, but we can't access it.
Also i am having problems to reproduce issue reliably, it happens only in one place with unreliable wifi network, and sensor is installed in very hard to reach place, so it is difficult to debug it.

Best i got:
```
timeout -s KILL 3 curl -v --limit-rate 100k -F 'upload=@acmainroom.bin' http://acmainroom.local/update
```
But it doesn't set "final", so OTA just ends in incomplete state, and if i restart it start from beginning.

So i have to investigate this corruption issue more, will test it better next time, sorry for disturbing.

2023-03-09 06:46 UTC, closed without merging