Use PSRam for BLE scan results.
OttoWinter/esphomeyaml pull request #4486
Opened 2023-02-25 17:53 UTC by Fabian-Schmidt

# What does this implement/fix?

Given that the Bluetooth stack is consuming so much memory. I try to reduce the memory consumption a bit by moving the BLE scan results to SPI RAM (PSRAM).  It saves 3kb.

Also if PSRAM is used more scan results can be cached,

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-26 18:32 UTC, jesserockz commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.h
> +#if BOARD_HAS_PSRAM
This flag is only added when using arduino as a framework.

2023-02-27 10:24 UTC, Fabian-Schmidt commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.h
> +#if BOARD_HAS_PSRAM
Using the generic `CONFIG_SPIRAM` flag instead?
It is used by Arduino and ESP-IDF.

2023-03-03 20:57 UTC, oxan requested changes

2023-03-03 20:57 UTC, oxan commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +         sizeof(esp_ble_gap_cb_param_t::ble_scan_result_evt_param) * ESP32BLETracker::SCAN_RESULT_BUFFER_SIZE);
This will blow up if the allocation fails. Either the `ALLOW_FAILURE` flag should be removed from the allocator, or a check to see if `this->scan_result_buffer_` is not nullptr should be added.

2023-03-03 20:57 UTC, oxan commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.h
> +  esp_ble_gap_cb_param_t::ble_scan_result_evt_param *scan_result_buffer_;
I think converting `scan_result_buffer_` to an `std::vector` is a cleaner solution, though I'm not sure how involved that'd be.

2023-03-04 12:41 UTC, Fabian-Schmidt commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.h
> +  esp_ble_gap_cb_param_t::ble_scan_result_evt_param *scan_result_buffer_;
The existing solution with C style array is working fine. No need to 'fix' it.

Also `vector` can (and do) cause a lot of memory fragmentation and this is already an issue especially when using Bluetooth, Wifi and Display, memory is already tight. My opinion is that less usage of `vector` or only with `reserve` and `shrink_to_fit` operations are needed.

2023-03-04 12:49 UTC, Fabian-Schmidt commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +         sizeof(esp_ble_gap_cb_param_t::ble_scan_result_evt_param) * ESP32BLETracker::SCAN_RESULT_BUFFER_SIZE);
Adjusted the call and changed `ALLOW_FAILURE` to `NONE`.

2023-03-05 20:47 UTC, oxan commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.h
> +  esp_ble_gap_cb_param_t::ble_scan_result_evt_param *scan_result_buffer_;
Using scissors to cut your lawn also works, but that doesn't mean it's the best solution ;)

Kidding aside, in general we prefer not to do manual memory management, as it's much easier to make mistakes when doing that as opposed to using STL containers. In fact, there's a CI check that prohibits use of malloc/free - I should add the `allocate()` function to that. If memory fragmentation is a problem, we can indeed use `reserve`, or use a pointer to an `std::array` instance instead.

In any case, given that a C-style array is already used here (and the BLE-code is already quite messy), I don't really oppose this change and will leave it up to @jesserockz.

2023-03-08 01:24 UTC, jesserockz commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.h
> +  esp_ble_gap_cb_param_t::ble_scan_result_evt_param *scan_result_buffer_;
I think its fine as it is and we can revisit changing the type later with some more testing if needed.

2023-03-08 07:16 UTC, jesserockz commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +         sizeof(esp_ble_gap_cb_param_t::ble_scan_result_evt_param) * ESP32BLETracker::SCAN_RESULT_BUFFER_SIZE);
Changing this to NONE is going to `abort` when it cannot allocate anywhere, which is almost certainly going to cause a boot loop until it gets into safe mode.

It would be quite rare to not be able to allocate the memory, but I think the ALLOW_FAILURE with a nullptr check afterwards is better as it can then mark the component as failed like other components do now.

2023-03-08 09:38 UTC, Fabian-Schmidt commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +         sizeof(esp_ble_gap_cb_param_t::ble_scan_result_evt_param) * ESP32BLETracker::SCAN_RESULT_BUFFER_SIZE);
Okay. I changed it to mark component as failed instead of abort.

2023-03-08 18:22 UTC, jesserockz approved these changes

2023-03-08 18:34 UTC, merged