Add a LG-UART component
OttoWinter/esphomeyaml pull request #4490
Opened 2023-02-26 21:26 UTC by kquinsland

# What does this implement/fix?

This implements UART based control over LG brand TVs and Monitors.
Most LG screens have some RS232 based control input that can be used to set/poll certain things.
Unfortunately, the number of "things" that can be set/polled is different for each display/model/firmware version.

E.G.: some displays respond to "turn on/off" commands but do not respond to "are you on or off?" commands.

I haven't written any serious C++ in more than a decade so I was mostly following the architecture of the `bedjet` component; there is a `hub` that does all of the work and then a 'child' `switch` or `number` or `sensor` component is responsible for transforming the value of the parameter into the appropriate metaphor.

E.G.: the packet format for "are you on or off?" and "what is the current volume level" is the same so the `hub` handles most of the comms and just lets each child component know when an update has come in for the particular param. When it makes sense, the user can elect to have the reply represented by a `switch` or a `number` .

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

I have a WIP branch that I will turn into a PR after the code here is reviewed... my C++ is **rusty** so I'll wait for a "this code is good enough" or a "this code needs to be re-factored to ..." before i put more time into the docs.

If you require a PR for the docs before this can be reviewed, let me know and i'll open the docs PR and update this post.

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

This is a direct copy/paste from the test file that I've been using.
It's the exact same hardware that I used here: https://github.com/kquinsland/lg-m43mu79-esp-home-bridge

Although the LG device that I am using / testing against has changed.

```yaml

# See: https://esphome.io/components/uart.html
uart:
  id: uart_01
  tx_pin: GPIO16
  rx_pin: GPIO17
  # LG monitor wants 9600/8N1... pretty standard :)
  baud_rate: 9600

lg_uart:
  id: lg01
  screen_number: 01
  uart_id: uart_01

switch:
  - name: "Power"
    platform: lg_uart
    icon: "mdi:power"
    device_class: "switch"
    lg_uart_id: lg01
    # ka for power
    lg_uart_cmd: "ka"
    update_interval: 5s
    # Assume that the screen is on at boot.
    restore_mode: RESTORE_DEFAULT_ON

number:
  - name: "Volume level"
    icon: "mdi:volume-source"
    platform: lg_uart
    lg_uart_id: lg01
    # docs indicate kf for audio level
    lg_uart_cmd: "kf"
    # And that values ranges from 0x00 to 0x65
    decode_base: 16
    mode: slider
    # For testing; Like with the audio mute setting, this seems to have a ~ 10s delay on it.
    update_interval: 15s

sensor:
  - name: "active input (raw)"
    internal: true
    id: sens_lg_active_inpt_raw
    platform: lg_uart
    lg_uart_id: lg01
    # xb is for setting input
    lg_uart_cmd: "xb"
    # And that active inputs are numbers 00 through 99
    decode_base: 10
    # For testing; Like with the audio mute setting, this seems to have a ~ 10s delay on it.
    update_interval: 10s
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-26 23:26 UTC, jesserockz requested changes
Couldnt get past the first file without a whole bunch of changes to be made so submitting those for now. =)

2023-02-26 23:26 UTC, jesserockz commented on esphome/components/lg_uart/__init__.py
> +MULTI_CONF = False
Why `False`? (Which is the default btw and dont need to add it is this is the case...)

2023-02-26 23:26 UTC, jesserockz commented on esphome/components/lg_uart/__init__.py
> +CONF_DECODE_BASE_TYPES = [10, 16]
The `CONF_` prefix is for the config strings, not for values
```suggestion
DECODE_BASE_TYPES = [10, 16]
```

2023-02-26 23:26 UTC, jesserockz commented on esphome/components/lg_uart/__init__.py
> +        cv.Required(CONF_LG_UART_ID): cv.use_id(LGUartHub),
This allows automatic linking if there is only a single `lg_uart` component (The user doesnt have to add the id in yaml)
```suggestion
        cv.GenerateID(CONF_LG_UART_ID): cv.use_id(LGUartHub),
```

2023-02-26 23:26 UTC, jesserockz commented on esphome/components/lg_uart/__init__.py
> +CONF_LG_UART_CMD = "lg_uart_cmd"
Please just use `CONF_COMMAND` from `const.py`. No need to prefix this with `lg_uart`

```suggestion
```

2023-02-26 23:26 UTC, jesserockz commented on esphome/components/lg_uart/__init__.py
> +LG_UART_CLIENT_SCHEMA = cv.Schema(
If all the children require `CONF_LG_UART_CMD` (to be renamed) why is that not just in this schema?

2023-02-26 23:26 UTC, jesserockz commented on esphome/components/lg_uart/__init__.py
> +        cv.Required(CONF_UART_ID): cv.use_id(uart.CONF_ID),
This component should be extending `uart.uart_device_schema`, not declaring the uart id here.
```suggestion
```

2023-02-26 23:26 UTC, jesserockz commented on esphome/components/lg_uart/__init__.py
> +def validate_uart_cmd_len(config):
Once the CONF_COMMAND is moved into the shared schema, this should just be a 	cv.Length` validation on the config entry directly (combine string_strict and length with `cv.All`)

2023-02-26 23:46 UTC, kquinsland commented on esphome/components/lg_uart/__init__.py
> +MULTI_CONF = False
That was a remnant from testing / trying to figure out how that's used internally.

2023-02-26 23:51 UTC, kquinsland commented on esphome/components/lg_uart/__init__.py
> +LG_UART_CLIENT_SCHEMA = cv.Schema(
The command is distinct per feature. `ka` for power, `ke` for audio ... etc so it's a property of the switch/number ... etc and not of the 'hub'.

2023-03-05 19:14 UTC, kquinsland commented
Gentle poke to @jesserockz. I've addressed the code duplication in the python and done some re-factor on the C++:

- `vec<uint8>` rather than char array for the packets
- some common code moved into the child class

2023-06-13 00:45 UTC, closed without merging