Emc2101
OttoWinter/esphomeyaml pull request #4491
Opened 2023-02-26 22:32 UTC by ellull

# What does this implement/fix?

Adds support for Adafruit EMC2101 Fan controller and temperature sensor

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1679

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
i2c:
  sda: GPIO8
  scl: GPIO9

emc2101:
  pwm:
    resolution: 8

output:
  - platform: emc2101
    id: fan_duty_cycle

fan:
  - platform: speed
    name: "Hall Cabinet Fan"
    output: fan_duty_cycle
    speed_count: 16

sensor:
  - platform: emc2101
    internal_temperature:
      id: internal_temperature_sensor
      name: "Internal Temperature Sensor"
    speed:
      id: speed_sensor
      name: "Speed Sensor"
    duty_cycle:
      id: duty_cycle_sensor
      name: "Duty Cycle Sensor"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-08 19:02 UTC, jesserockz requested changes

2023-03-08 19:02 UTC, jesserockz commented on esphome/components/emc2101/sensor.py
> +CONF_EMC2101_ID = "emc2101_id"
This should be in `__init__.py`

2023-03-08 19:02 UTC, jesserockz commented on esphome/components/emc2101/emc2101.h
> +#include "esphome/components/sensor/sensor.h"
This code will fail to compile with no nice message to the user if they dont have `sensor` or `output` in their config. You should either wrap any sensor code in `#ifdef USE_SENSOR` and move the output code into sub folders (should be easy for output since it just calls a single parent command)

2023-03-12 15:20 UTC, ellull commented on esphome/components/emc2101/sensor.py
> +CONF_EMC2101_ID = "emc2101_id"
Hi @jesserockz, thanks for the review.

Do you mean to move to `__init__.py` just line 22 `CONF_EMC2101_ID = "emc2101_id"`?

2023-03-12 20:46 UTC, ellull commented on esphome/components/emc2101/sensor.py
> +CONF_EMC2101_ID = "emc2101_id"
Don't worry, I think now I understand your comment.

I think that with the refactor this change request and the other one regarding the output and the sensor should be resolved.

2023-03-12 20:47 UTC, ellull commented on esphome/components/emc2101/emc2101.h
> +#include "esphome/components/sensor/sensor.h"
I moved the output and sensor code in subfolders.

2023-03-19 22:41 UTC, jesserockz requested changes

2023-03-19 22:41 UTC, jesserockz commented on esphome/components/emc2101/__init__.py
> +                        CONF_CONVERSION_RATE, default=CONVERSIONS_PER_SECOND["16"]
```suggestion
                        CONF_CONVERSION_RATE, default="16"
```

2023-03-19 22:41 UTC, jesserockz commented on esphome/components/emc2101/__init__.py
> +                    cv.Optional(CONF_DIVIDER, default=0x01): cv.uint8_t,
No need to use hex values here
```suggestion
                    cv.Optional(CONF_RESOLUTION, default=23): cv.int_range(
                        min=0, max=31
                    ),
                    cv.Optional(CONF_DIVIDER, default=1): cv.uint8_t,
```

2023-03-19 22:41 UTC, jesserockz commented on esphome/components/emc2101/__init__.py
> +    .extend(i2c.i2c_device_schema(CONF_I2C_ADDR)),
Just put the address inline here to align with all other i2c components
```suggestion
    .extend(i2c.i2c_device_schema(0x4C)),
```

2023-03-19 22:41 UTC, jesserockz commented on esphome/components/emc2101/__init__.py
> +
```suggestion
```

2023-03-19 22:41 UTC, jesserockz commented on esphome/components/emc2101/sensor/emc2101_sensor.h
> +  void set_duty_cycle_sensor(sensor::Sensor *sensor) { duty_cycle_sensor_ = sensor; }
```suggestion
  void set_internal_temperature_sensor(sensor::Sensor *sensor) { this->internal_temperature_sensor_ = sensor; }
  /** Used by ESPHome framework. */
  void set_external_temperature_sensor(sensor::Sensor *sensor) { this->external_temperature_sensor_ = sensor; }
  /** Used by ESPHome framework. */
  void set_speed_sensor(sensor::Sensor *sensor) { this->speed_sensor_ = sensor; }
  /** Used by ESPHome framework. */
  void set_duty_cycle_sensor(sensor::Sensor *sensor) { this->duty_cycle_sensor_ = sensor; }
```

2023-03-19 22:41 UTC, jesserockz commented on esphome/components/emc2101/emc2101.cpp
> +          // 100% duty cycle or a maximum DAC output voltage.
Please change these all to `static const uint8_t`

2023-03-19 22:41 UTC, jesserockz commented on esphome/components/emc2101/emc2101.h
> +  friend class EMC2101Sensor;
Not sure how this is not failing since there is not include and there is not forward class declaration. I would personally remove the `friend class` and make the functions needed public to simplify this.

2023-03-21 15:35 UTC, ellull commented on esphome/components/emc2101/__init__.py
> +                    cv.Optional(CONF_DIVIDER, default=0x01): cv.uint8_t,
I used hex values because the datasheet used hex values. But I don't see any problem using decimal values.

2023-03-21 16:13 UTC, ellull commented on esphome/components/emc2101/emc2101.cpp
> +          // 100% duty cycle or a maximum DAC output voltage.
Done. But, if I may ask, is this for some particular reason or just a matter of code style?

2023-03-25 16:15 UTC, ellull commented on esphome/components/emc2101/emc2101.h
> +  friend class EMC2101Sensor;
I'm not really experienced in C++ but searching in stackoverflow I found the following answer that may answer your question: https://stackoverflow.com/a/14115071

Do you still think I should still make the functions needed public?

2023-03-25 16:46 UTC, ellull commented on esphome/components/emc2101/emc2101.cpp
> +          // 100% duty cycle or a maximum DAC output voltage.
Never mind. I've already found it in the Codebase Standards section of the Contributing page: https://esphome.io/guides/contributing.html#codebase-standards

2023-04-06 10:07 UTC, ellull commented
Hi @jesserockz, I've made the changes you suggested. Could you please review the code?

Thank you very much.

2023-05-03 14:16 UTC, ellull commented
Hello @jesserockz, would you mind taking a look to the latests changes I've made?

Thank you.

2023-08-25 08:44 UTC, the01 commented
Hello,
is there anything particular that is blocking this pull request?
I'd love to use this component 😄

2023-08-25 10:53 UTC, ssjoholm commented
> Hello, is there anything particular that is blocking this pull request? I'd love to use this component 😄

Me too. I can help to test, if I just know how to add the component into the build.

2023-08-25 11:33 UTC, the01 commented
> > Hello, is there anything particular that is blocking this pull request? I'd love to use this component 😄
> 
> Me too. I can help to test, if I just know how to add the component into the build.

I found out today that esphome can actually pull in external code, so we don't need to wait for this pull request to come through.
According to [this link](https://esphome.io/components/external_components.html) it should be enough to a section like the following to the yaml

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/ellull/esphome
      ref: emc2101
    components: [ emc2101 ]
```

and then it should be usable as if it was already merged directly (at least from my understanding). I haven't actually tested it, so this is purely from the docs from now.
I'll update when I get a chance

2023-08-26 13:16 UTC, ellull commented
Hi @the01 and @ssjoholm, I haven't had any response from @jesserockz since March 19, 2023 and I don't know what is blocking the PR. I've lost almost all hope that the component will ever be added to ESPHome.

I've used the external_components configuration in a working configuration (https://github.com/ellull/fan-controller/blob/main/firmware/fan-controller-v1.yaml) like this:
```
external_components:
  - source: github://pr#4491
    refresh: 0s
    components: 
      - emc2101
```
I reference the PR so I'm using the very same code that might end in ESPHome.

2023-08-27 15:12 UTC, ssjoholm commented
> Hi @the01 and @ssjoholm, I haven't had any response from @jesserockz since March 19, 2023 and I don't know what is blocking the PR. I've lost almost all hope that the component will ever be added to ESPHome.
> 
> I've used the external_components configuration in a working configuration (https://github.com/ellull/fan-controller/blob/main/firmware/fan-controller-v1.yaml) like this:
> 
> ```
> external_components:
>   - source: github://pr#4491
>     refresh: 0s
>     components: 
>       - emc2101
> ```
> 
> I reference the PR so I'm using the very same code that might end in ESPHome.

Thank You. I have it now up and running with QT PY ESP32-S2. The on/off for fan works, the sensors (temp, duty cycle and rpm) shows correct values.

-Sebastian

2023-08-28 08:44 UTC, ellull commented
> Any plans to be able to control the duty cycle from esphome? as I did not see that option.

Hi, Sebastian.

Yes it is possible to control the Fan.

There is a companion PR in the documentation project (esphome/esphome-docs/#2709) where I'm adding the documentation for this component. The temporari URL for the EMC2101 documentation (until the PR is merged) is https://deploy-preview-2709--esphome.netlify.app/components/emc2101.html

There you will find a minimal but complete example on how to expose a fan component that uses the EMC2101 to control a fan.

2023-08-28 18:40 UTC, ssjoholm commented
> > Any plans to be able to control the duty cycle from esphome? as I did not see that option.
> 
> Hi, Sebastian.
> 
> Yes it is possible to control the Fan.
> 
> There is a companion PR in the documentation project ([esphome/esphome-docs#2709](https://github.com/esphome/esphome-docs/pull/2709)) where I'm adding the documentation for this component. The temporari URL for the EMC2101 documentation (until the PR is merged) is https://deploy-preview-2709--esphome.netlify.app/components/emc2101.html
> 
> There you will find a minimal but complete example on how to expose a fan component that uses the EMC2101 to control a fan.

Hi, thank you.

I have following the example, and checked the fan speed documents as well. But it seems that for me the fan is only a switch, not represented as the "fan speed" control that might be expected.

emc2101:
  pwm:
    resolution: 8

output:
  - platform: emc2101
    id: fan_duty_cycle

fan:
  - platform: speed
    id: fan_id
    output: fan_duty_cycle
    name: "Bathroom Fan"
    speed_count: 16

sensor:
  - platform: emc2101
    internal_temperature:
      id: internal_temperature_sensor
      name: "Internal Temperature Sensor"
    speed:
      id: speed_sensor
      name: "Speed Sensor"
    duty_cycle:
      id: duty_cycle_sensor
      name: "Duty Cycle Sensor"

I can see that the "speed.fan" object get initialised in the log.

[20:24:32][C][speed.fan:016]: Speed Fan 'Bathroom Fan'
[20:24:32][C][speed.fan:151]:   Speed: YES
[20:24:32][C][speed.fan:152]:   Speed count: 16

<img width="333" alt="image" src="https://github.com/esphome/esphome/assets/2561804/df3e7b05-44a7-4a81-a26c-29304ada1433">

Using the external components as referred previously

external_components:
  - source: github://pr#4491
    refresh: 0s
    components: 
      - emc2101

Maybe I have missed something.

-Sebastian

2023-08-29 07:25 UTC, ellull commented
Ohhh. I think I know where the problem is :)

In Home Assistant, click on the "Bathroom fan" entity (not the toggle switch on its right)
![image](https://github.com/esphome/esphome/assets/5901372/a3b3bcf0-d339-40f1-a784-6ce4e045763a)

You should see a slider you can use to modify the fan speed.

I cannot show mine because recently I modified my fan configuration to use [PID](https://esphome.io/components/climate/pid.html) to keep a "constant" temperature as explained [here](https://github.com/patrickcollins12/esphome-fan-controller).

2023-08-29 17:04 UTC, ssjoholm commented
Hi Eduard,

You are correct, by sliding the "switch" I can adjust the percentage, and then adjust the speed.

![image](https://github.com/esphome/esphome/assets/2561804/c561c0b6-3944-4a53-b6d6-e2cc8473b18d)

I tested also via automation script and it worked as well.

![image](https://github.com/esphome/esphome/assets/2561804/1e933a19-1ffb-4183-a630-621324031f40)

I appreciate the work on this. Thank You.

-Sebastian

2023-08-30 22:34 UTC, the01 commented
Works awesome!
Thanks @ellull not only for the integration, but also for the info on how to install it while waiting for the pull request

2023-10-23 23:42 UTC, jesserockz requested changes

2023-10-23 23:42 UTC, jesserockz commented on esphome/components/emc2101/__init__.py
> +        dac_config = config[CONF_DAC]
```suggestion
    if dac_config := config.get(CONF_DAC):
        cg.add(var.set_dac_mode(True))
```

2023-10-23 23:42 UTC, jesserockz commented on esphome/components/emc2101/__init__.py
> +        pwm_config = config[CONF_PWM]
```suggestion
    if pwm_config := config.get(CONF_PWM):
        cg.add(var.set_dac_mode(False))
```

2023-10-23 23:52 UTC, jesserockz requested changes

2023-10-23 23:52 UTC, jesserockz commented on esphome/components/emc2101/sensor/__init__.py
> +            unit_of_measurement="RPM",
```suggestion
            unit_of_measurement=UNIT_REVOLUTIONS_PER_MINUTE,
```

2023-10-23 23:52 UTC, jesserockz commented on esphome/components/emc2101/sensor/__init__.py
> +    UNIT_PERCENT,
```suggestion
    UNIT_PERCENT,
    UNIT_REVOLUTIONS_PER_MINUTE,
```

2023-10-24 00:03 UTC, jesserockz approved these changes

2023-10-25 18:30 UTC, merged