Feat: add support for hex color in color component
OttoWinter/esphomeyaml pull request #4493
Opened 2023-02-27 09:57 UTC by dorianim

# What does this implement/fix?

Fixes https://github.com/esphome/feature-requests/issues/2138

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/feature-requests#2138

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
color:
  - id: test
    hex: '#112233'
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-02-27 14:21 UTC, nielsnl68 approved these changes
I do not know of I would at the `def hex_color()` in the *config_validation.py* but i like it.

2023-02-27 15:00 UTC, dorianim commented
@nielsnl68 I tried to stick to the scheme and express what it is. Maybe colo_code would be better?
How would you name it?

2023-02-27 15:13 UTC, nielsnl68 commented
> @nielsnl68 I tried to stick to the scheme and express what it is. Maybe color_code would be better? How would you name it?

I did not mean that the function name was wrong. I tried to say that i would not put the function in *config_validation.py* file myself. It is not wrong or anything.

2023-02-27 16:34 UTC, dorianim commented
Oh, I see. Yes, you're probably right about that. The color code validator shouldn't be needed anywhere else. I'll move it.

2023-03-03 21:17 UTC, oxan requested changes

2023-03-03 21:17 UTC, oxan commented on esphome/components/color/__init__.py
> +Invalid = vol.Invalid
Please drop both these changes, and use `cv.Invalid` directly instead.

2023-03-03 21:17 UTC, oxan commented on esphome/components/color/__init__.py
> +        raise Invalid("Color must start with #")
I'm not sure we want to do this: `#` also indicates a comment in YAML, so it'll require escaping, and since we're only accepting hex for this option, we don't need it to resolve ambiguity. 

@jesserockz what do you think?

2023-03-03 21:17 UTC, oxan commented on esphome/components/color/__init__.py
> +        return (int(value[0:2], 16), int(value[2:3], 16), int(value[3:5], 16))
```suggestion
        return (int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16))
```

2023-03-03 21:17 UTC, oxan commented on esphome/components/color/__init__.py
> +        cv.Exclusive(CONF_HEX, "hex"): hex_color,
`Exclusive` ensures not more than one item from the same group (indicated by the second parameter) is present, so this doesn't make hex incompatible with red/green/blue.

2023-03-04 08:35 UTC, dorianim commented on esphome/components/color/__init__.py
> +        raise Invalid("Color must start with #")
That's a good point.

2023-03-04 15:31 UTC, dorianim commented on esphome/components/color/__init__.py
> +        cv.Exclusive(CONF_HEX, "hex"): hex_color,
How should it be done instead?

2023-03-05 18:49 UTC, oxan commented on esphome/components/color/__init__.py
> +        cv.Exclusive(CONF_HEX, "hex"): hex_color,
I'm not quite sure tbh.

2023-03-08 22:45 UTC, jesserockz commented
I pushed a commit that should fix it. I don't think we can de-duplicate the `.extend(cv.COMPONENT_SCHEMA)` but that's fine.

2023-03-08 22:46 UTC, dorianim commented
Thanks! Just tried to do the same thing :)
![image](https://user-images.githubusercontent.com/30153207/223868701-71e58a54-89cf-4512-9072-269706941c5b.png)

2023-03-08 23:12 UTC, jesserockz approved these changes
Thanks. Please also add a PR to the docs repo targeting `next`

2023-03-09 09:23 UTC, dorianim commented
@jesserockz done! https://github.com/esphome/esphome-docs/pull/2731 :)

2023-03-12 20:39 UTC, merged