RF Protocol Tx/RX for Drayton Digistat heating controller
OttoWinter/esphomeyaml pull request #4494
Opened 2023-02-27 16:07 UTC by marshn

# What does this implement/fix?

Adds ability to receive and send data sent by Draton Digistat central heating controller. 
Tested with Digistat model "+3RF" using 433MHz radio modules.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** #Pending

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```
    on_ ... :
      then:
        - remote_transmitter.transmit_drayton:
            # Boiler OFF packet   AA AC 69 56 95 55 55 66 59
            # Payload 0x6180052     0110000110000000 0000010 10010            
            address: '0x0000'
            channel: '0x0e'
            command: '0x41'
            repeat:
              times: 3
              wait_time: 100ms

binary_sensor:
  - platform: remote_receiver
    name: Drayton On
    drayton:
      address: 0x6180
      channel: 0x12
      command: 0x41
    on_press:
      then:
        - switch.turn_on: switch_relay_1
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-08 18:56 UTC, jesserockz requested changes

2023-03-08 18:56 UTC, jesserockz commented on esphome/components/remote_base/__init__.py
> +    template_ = await cg.templatable(config[CONF_COMMAND], args, cg.uint16)
If these have max value of `0x1F` and `0x7F` then they should be `cg.uint8`

Please also make the changes in the `DraytonData` and places that use them.

```suggestion
    template_ = await cg.templatable(config[CONF_CHANNEL], args, cg.uint8)
    cg.add(var.set_channel(template_))
    template_ = await cg.templatable(config[CONF_COMMAND], args, cg.uint8)
```

2023-03-09 10:50 UTC, marshn commented on esphome/components/remote_base/__init__.py
> +    template_ = await cg.templatable(config[CONF_COMMAND], args, cg.uint16)
Thank you for the review, Changes made and retested.

2023-03-09 11:08 UTC, marshn commented
I seem to have pulled multiple commits by others into the PR when making the review changes.Any advice on straightening things out appreciated!

2023-05-01 04:06 UTC, jesserockz approved these changes

2023-05-01 04:12 UTC, merged