FS3000 sensor
OttoWinter/esphomeyaml pull request #4502
Opened 2023-03-03 14:03 UTC by kahrendt

# What does this implement/fix?

This pull request adds support for the FS3000 Air Velocity Sensor. It includes support for the two available models, 1005 and 1015.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes (not applicable)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2715

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: fs3000
    name: "Air Velocity"
    model: 1005
    update_interval: 60s

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-04 09:17 UTC, SeByDocKy commented
Very interesting sensor.... and thanks for the ESPhome integration.... I may use it in a big project

2023-03-06 06:54 UTC, jesserockz requested changes

2023-03-06 06:54 UTC, jesserockz commented on esphome/components/fs3000/sensor.py
> +CONFIG_SCHEMA = cv.All(
No need to wrap in `All`
```suggestion
CONFIG_SCHEMA = (
```

2023-03-06 06:54 UTC, jesserockz commented on esphome/components/fs3000/sensor.py
> +            cv.GenerateID(): cv.declare_id(FS3000Component),
This is not needed as the `sensor_schema()` adds it already
```suggestion
```

2023-03-06 06:54 UTC, jesserockz commented on esphome/components/fs3000/sensor.py
> +    await sensor.register_sensor(var, config)
```suggestion
    var = await sensor.new_sensor(config)
    await cg.register_component(var, config)
    await i2c.register_i2c_device(var, config)
```

2023-03-06 06:54 UTC, jesserockz commented on esphome/components/fs3000/fs3000.cpp
> +  }
I would prefer this initialization is done in `setup` and leave the `setter` to be just a `setter` for the `model` variable

2023-03-06 06:54 UTC, jesserockz commented on esphome/components/fs3000/fs3000.h
> +  FS3000Model model_{FIVE};
`set_model` is always called by code generation so a default is not needed in the header
```suggestion
  FS3000Model model_{};
```

2023-03-06 06:54 UTC, jesserockz commented on esphome/components/fs3000/fs3000.cpp
> +    publish_state(NAN);
```suggestion
    this->publish_state(NAN);
```

2023-03-06 06:54 UTC, jesserockz commented on esphome/components/fs3000/fs3000.cpp
> +  publish_state(fit_raw_(raw_value));
```suggestion
  this->publish_state(fit_raw_(raw_value));
```

2023-03-06 13:19 UTC, kahrendt commented on esphome/components/fs3000/fs3000.cpp
> +  }
Makes sense, thanks!

2023-03-06 13:21 UTC, kahrendt commented
Thank you for taking the time to review my pull request! This is all fairly new to me, and I appreciate your help. I made the requested changes, including the in-depth setting up code for each module into the setup() function, as well as fixed the sensor.py to remove the unnecessary components.

2023-03-07 04:10 UTC, jesserockz approved these changes

2023-03-07 04:43 UTC, merged