climate: add on_message callbacks
OttoWinter/esphomeyaml pull request #4511
Opened 2023-03-05 07:24 UTC by nwf

# What does this implement/fix?

This lets downstream components respond to climate configuration changes, which take place through ClimateCall objects, without also being notified every time the state changes, which happens every time the input sensor announces a new value.

FIXES https://github.com/esphome/feature-requests/issues/2136

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

**I have not yet updated the documentation, as I would like feedback on the idea first.**  However, I think it is what I want, so I thought I would take a stab at it.

I also have not tested it on a real device, but it does compile and I think I have plumbed it right.  I'll get there.

2023-03-05 19:02 UTC, jesserockz requested changes
Changes look good, but I don't like `on_message`. Perhaps `on_config` or `on_control`?

2023-03-05 19:19 UTC, nwf commented
OK.  I wasn't sure how you'd feel about expanding the set of trigger names.  I had originally suggested `on_config` but I think I like `on_control` better; thank you for the suggestion.  I'll go flip everything to that.

2023-03-05 19:33 UTC, oxan approved these changes

2023-03-07 04:18 UTC, jesserockz approved these changes

2023-03-07 04:42 UTC, merged