Added response for Tuya RSSI command
OttoWinter/esphomeyaml pull request #4549
Opened 2023-03-12 11:29 UTC by catalin2402

# What does this implement/fix?
Implemented wifi rssi response for tuya MCU

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-13 22:58 UTC, jesserockz requested changes

2023-03-13 22:58 UTC, jesserockz commented on esphome/components/network/util.cpp
> +
Not sure I like the wifi rssi being added in the network utils when it will never apply to ethernet...

Probably best to just have this code directly inside the `case TuyaCommandType::WIFI_RSSI`

2023-03-13 23:35 UTC, catalin2402 commented on esphome/components/network/util.cpp
> +
Got it, thanks for the review, I will move the code from network to tuya component :)
In my original thought, I wanted to move the code from the WiFiSignalSensor sensor to use the same network utils, and maybe other components who would need to access the same method can use the utils instead

2023-03-14 00:35 UTC, jesserockz commented on esphome/components/network/util.cpp
> +
Well technically the code is already common for the different wifi backends with `wifi::global_wifi_component->wifi_rssi()` and adding another wrapper around that is just extra code. I dont think it needs to be moved anywhere else.

2023-03-14 00:48 UTC, jesserockz approved these changes

2023-03-14 01:05 UTC, merged