Added support for M5CoreInk display gdew0154m09
OttoWinter/esphomeyaml pull request #4584
Opened 2023-03-18 14:54 UTC by tobiasoort

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** n/a

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2762

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

display:
  - platform: gdew0154m09
    id: my_display
    reset_pin: GPIO0
    cs_pin: GPIO9
    dc_pin: GPIO15
    busy_pin: GPIO4
    rotation: 0
    update_interval: 60s

```

## Checklist:
  - [x ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-19 08:25 UTC, nielsnl68 requested changes
Hi i added some suggestions to make your component more readable and understanding for others.
I hope you they are useful to you.

2023-03-19 08:25 UTC, nielsnl68 commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +  if (mode == 0) {
Hi, i would suggest to use `static const` here instead a numeriek , so ever one can later understand what this mode does.

2023-03-19 08:25 UTC, nielsnl68 commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +  // this->clear_dsram_();
Please let you inspire here by the *ili9xxx* component to allow partially screen updates.

2023-03-19 08:25 UTC, nielsnl68 commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +    command_(0x10); // data transmission start DTM1
To allow a better understanding of the commands you use it is a better practice to setup a list of `static const` with all used commands and replace the numeric commands in you code.

2023-03-19 13:03 UTC, tobiasoort commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +  if (mode == 0) {
Agree. This was a 1:1 port from the M5Stack example code; thanks for the feedback because that will definitely make it clearer.

2023-03-19 13:04 UTC, tobiasoort commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +  // this->clear_dsram_();
Partial mode is total barf on this display at the moment. I'd prefer to get non-partial polished and finish before diving into the complexities of partial updates.

2023-03-19 13:07 UTC, tobiasoort commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +    command_(0x10); // data transmission start DTM1
This has diminishing value as the specs are very very uncomprehensible and only a few make sense, and some are even undocumented yet used by the M5Stack example code (i'm looking at you, `0xaa`). I started to document the commands but after starting could already stop by lack of good docs from the vendor.

2023-03-19 20:58 UTC, nielsnl68 commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +  if (mode == 0) {
Top, good luck :)

2023-03-19 20:59 UTC, nielsnl68 commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +  // this->clear_dsram_();
Best choose,

2023-03-19 21:02 UTC, nielsnl68 commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +    command_(0x10); // data transmission start DTM1
Ach, I know this issue as well, i found a lot of undocumented Command code's while i was upgrade the ili9xxx and i still missing some of them.

2023-03-26 20:32 UTC, tobiasoort commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +    command_(0x10); // data transmission start DTM1
done; implemented all commands and some data messages where handy.

2023-03-27 19:35 UTC, jesserockz requested changes

2023-03-27 19:35 UTC, jesserockz commented on esphome/components/gdew0154m09/display.py
> +            cv.Required(CONF_CS_PIN): pins.gpio_output_pin_schema,
This is provided by the `spi.spi_device_schema()` already
```suggestion
```

2023-03-27 19:35 UTC, jesserockz commented on esphome/components/gdew0154m09/display.py
> +    .extend(spi.spi_device_schema()),
To change the CS pin to required
```suggestion
    .extend(spi.spi_device_schema(True)),
```

2023-03-27 19:35 UTC, jesserockz commented on esphome/components/gdew0154m09/display.py
> +    cg.add(var.set_busy_pin(busy))
This pin is set as optional so you have to check its set
```suggestion
    if CONF_BUSY_PIN in config:
        busy = await cg.gpio_pin_expression(config[CONF_BUSY_PIN])
        cg.add(var.set_busy_pin(busy))
```

2023-03-27 19:35 UTC, jesserockz commented on esphome/components/gdew0154m09/gdew0154m09_defines.h
> +static const int CMD_UNDOCUMENTED_0xF3 = 0xf3;  //  NOLINT
Why are these `NOLINT`ed?

2023-03-27 19:35 UTC, jesserockz commented on esphome/components/gdew0154m09/gdew0154m09_defines.h
These should all be `uint8_t` type to save on flash space

2023-03-27 19:35 UTC, jesserockz commented on esphome/components/gdew0154m09/gdew0154m09.h
> +const unsigned char LUT_VCOM_D_C1[] PROGMEM = {
Please use `uint8_t` instead of `unsigned char`
```suggestion
const uint8_t LUT_VCOM_D_C1[] PROGMEM = {
```

2023-03-27 19:35 UTC, jesserockz commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +  command_(CMD_DTM1_DATA_START_TRANS);
This is just one random line, please change to consistently use `this->`
```suggestion
  this->command_(CMD_DTM1_DATA_START_TRANS);
```

2023-03-27 19:41 UTC, tobiasoort commented on esphome/components/gdew0154m09/gdew0154m09_defines.h
> +static const int CMD_UNDOCUMENTED_0xF3 = 0xf3;  //  NOLINT
because clang-format wants to change `0x4D` into `0x4_D` since it thinks letters and numbers should always be separate.

2023-03-27 19:57 UTC, tobiasoort commented on esphome/components/gdew0154m09/gdew0154m09_defines.h
> +static const int CMD_UNDOCUMENTED_0xF3 = 0xf3;  //  NOLINT
example output from `clang-tidy for ESP32 Arduino`:

```
-static const int CMD_UNDOCUMENTED_0x4D = 0x4D;
-static const int CMD_UNDOCUMENTED_0xAA = 0xaa;
-static const int CMD_UNDOCUMENTED_0xE9 = 0xe9;
-static const int CMD_UNDOCUMENTED_0xB6 = 0xb6;
-static const int CMD_UNDOCUMENTED_0xF3 = 0xf3;
+static const int CMD_UNDOCUMENTED_0X4_D = 0x4D;
+static const int CMD_UNDOCUMENTED_0X_AA = 0xaa;
+static const int CMD_UNDOCUMENTED_0X_E9 = 0xe9;
+static const int CMD_UNDOCUMENTED_0X_B6 = 0xb6;
+static const int CMD_UNDOCUMENTED_0X_F3 = 0xf3;
```

2023-03-27 20:01 UTC, jesserockz commented on esphome/components/gdew0154m09/gdew0154m09_defines.h
> +static const int CMD_UNDOCUMENTED_0xF3 = 0xf3;  //  NOLINT
haha, thats fine then. Was just curious

2023-04-01 10:39 UTC, tobiasoort commented
@jesserockz all requested changes have been done.

2023-05-26 03:07 UTC, kbx81 requested changes
Couple nit-picks, but otherwise LGTM 😄

2023-05-26 03:07 UTC, kbx81 commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +    delay(10);
You're just checking the state of a GPIO pin, so I would argue the `delay()` is not necessary here -- let it roll out of the loop as soon as the line clears. 🙂

2023-05-26 03:07 UTC, kbx81 commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +  unsigned char *start_ptr = ((unsigned char *) list + 1);
For consistency with the rest of the platform, please use `uint8_t` instead of `unsigned char` -- also, instead of just `int`, I tend to push people towards `int32_t` or  `uint32_t`, as well. 😄

2023-05-27 09:35 UTC, tobiasoort commented
I'm I changed this PR to draft. After tinkering with another E-paper I noticed two things:

- It seems a lot of e-paper support (for various devices of various vendors) is accumulated in the `waveshare_epaper` platform. I'm going to try to integrate this display in there as well
- After testing my code extensively (for months) in hardware, I noticed undesirable wear on the e-ink display. I probably didn't write the proper power-down procedures for this display. I have to fix this before we go to main.

2023-05-27 09:48 UTC, tobiasoort commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +    delay(10);
I would think that would be less power-efficient, but I don't know how delay is handled on-cpu (if its just a busy-wait then it makes no difference). I stole this from other display components with similar setups which also included a similar `delay()` call. I'm happy to learn :)

2023-05-27 17:41 UTC, kbx81 commented on esphome/components/gdew0154m09/gdew0154m09.cpp
> +    delay(10);
As far as I know, the only way it would be more power. Efficient is if the CPU sleeps during the delay; I could be incorrect myself, but I don't believe that's the case with this environment.

2023-06-11 19:38 UTC, closed without merging

2023-06-11 19:38 UTC, tobiasoort commented
Closing this pullrequest - will port the (improved) code into the `waveshare_epaper` component.