BME68X Temperature+Pressure+Humidity+Gas Sensor via BSEC2
OttoWinter/esphomeyaml pull request #4585
Opened 2023-03-18 16:21 UTC by neffs

# What does this implement/fix?

This should be in draft state, because we should probably wait for a new release of the BSEC2 library.

This is a new integration based on the bme680_bsec component, updated to the BSEC2 library by Bosch. This supports BME688 sensors.

Unfortunately binary configurations settings are needed for 3,3V operation, that are not included in the public repo. I requested them here: https://github.com/boschsensortec/Bosch-BSEC2-Library/issues/20
You can get the configuration files by requesting the SDK from the Bosch website.

bme680_bsec already supports multiple sensors. I chose not to include these commits in my branch, because a native implementation was added in bsec 2.4 (https://github.com/boschsensortec/Bosch-BSEC2-Library/issues/3). BSEC 2.4 is not available on GitHub yet.

BSEC 2.4 will be a unified version that also supports BME680

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1332

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266 (NOT working, `section '.text1' will not fit in region 'iram1_0_seg'`)
- [X] RP2040 (Couldn't get ESPhome working with dev branch, BSEC2 broken until  https://github.com/boschsensortec/Bosch-BSEC2-Library/pull/22 is merged)

## Example entry for `config.yaml`:

```yaml
bme68x_bsec:
  state_save_interval: 30min
  bsec_configuration: 0,0,2,2, ....# bsec configuration, currently only available from bosch sensortec website.
# omitting this parameter results in a configuration for 1.8V supply voltage, according to BSEC2 documentation

sensor:
  - platform: bme68x_bsec
    temperature:
      name: "BME688 Temperature"
      filters:
        - median
    pressure:
      name: "BME688 Pressure"
      filters:
        - median
    humidity:
      name: "BME688 Humidity"
      filters:
        - median
    iaq:
      name: "BME688 IAQ"
      filters:
        - median
    iaq_static:
      name: "BME688 Static IAQ"
      filters:
        - median
    co2_equivalent:
      name: "BME688 CO2 Equivalent"
      filters:
        - median
    breath_voc_equivalent:
      name: "BME688 Breath VOC Equivalent"
      filters:
        - median
    gas_resistance:
      # Gas resistance in Ω
      name: "BME688 Gas Resistance"
      filters:
        - median
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-24 14:22 UTC, jesseklm commented
small note: if you pass repository to `add_library(name: str, version: Optional[str], repository: Optional[str] = None)` version will be skipped later in the generated platformio.ini.

```cpp
    cg.add_library(
        "BME68x Sensor library",
        "1.1.40407",
        "https://github.com/BoschSensortec/Bosch-BME68x-Library.git",
    )
    cg.add_library(
        "BSEC2 Software Library",
        "1.4.2200",
        "https://github.com/BoschSensortec/Bosch-BSEC2-Library.git",
    )
```
will generate:
```
    BME68x Sensor library=https://github.com/BoschSensortec/Bosch-BME68x-Library.git
    BSEC2 Software Library=https://github.com/BoschSensortec/Bosch-BSEC2-Library.git
```
it would be cleaner to use:
```cpp
    cg.add_library("BME68x Sensor library", "1.1.40407")
    cg.add_library("BSEC2 Software Library", "1.3.2200")
```

2023-03-24 14:22 UTC, jesseklm commented
small note: if you pass repository to `add_library(name: str, version: Optional[str], repository: Optional[str] = None)` version will be skipped later in the generated platformio.ini.

```cpp
    cg.add_library(
        "BME68x Sensor library",
        "1.1.40407",
        "https://github.com/BoschSensortec/Bosch-BME68x-Library.git",
    )
    cg.add_library(
        "BSEC2 Software Library",
        "1.4.2200",
        "https://github.com/BoschSensortec/Bosch-BSEC2-Library.git",
    )
```
will generate:
```
    BME68x Sensor library=https://github.com/BoschSensortec/Bosch-BME68x-Library.git
    BSEC2 Software Library=https://github.com/BoschSensortec/Bosch-BSEC2-Library.git
```
it would be cleaner to use:
```cpp
    cg.add_library("BME68x Sensor library", "1.1.40407")
    cg.add_library("BSEC2 Software Library", "1.3.2200")
```

2023-03-25 17:56 UTC, dremsol commented
Thanks for the PR. A quick test with my BME680 and the supplied config `bme680_iaq_33v_300s_4d` seems that `uint8_t` doesn't cover the range of specific entries.

```
In file included from src/esphome/components/bme68x_bsec/bme68x_bsec.h:8,
                 from src/esphome/components/bme68x_bsec/bme68x_bsec.cpp:1:
src/esphome/core/defines.h:3:63: error: narrowing conversion of '1974' from 'int' to 'uint8_t' {aka 'unsigned char'} inside { } [-Wnarrowing]
 #define BME68X_BSEC_CONFIGURATION {1974, 0, 0, 4, 2, 189, 1, 0}
                                                               ^
src/esphome/components/bme68x_bsec/bme68x_bsec.cpp:12:45: note: in expansion of macro 'BME68X_BSEC_CONFIGURATION'
 static const uint8_t bsec_configuration[] = BME68X_BSEC_CONFIGURATION;
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
*** [.pioenvs/development/src/esphome/components/bme68x_bsec/bme68x_bsec.cpp.o] Error 1
====================================================== [FAILED] Took 2.65 seconds ======================================================
```

2023-03-25 19:43 UTC, neffs commented
> Thanks for the PR. A quick test with my BME680 and the supplied config `bme680_iaq_33v_300s_4d` seems that `uint8_t` doesn't cover the range of specific entries.

You'll have to use the format from the .c file or just remove the first number (it probably is just the length). 

Be aware that the only BSEC 2.2 is available on github, this is not the same version as the config files you are using. BME680  is only supported officially in 2.4.

2023-03-25 19:46 UTC, neffs commented
> it would be cleaner to use:
> 
> ```c++
>     cg.add_library("BME68x Sensor library", "1.1.40407")
>     cg.add_library("BSEC2 Software Library", "1.3.2200")
> ```
Thanks! Back when I started, this BSEC2 was not in the platform.io registry and this did not work. Now it should work.

2023-03-25 19:55 UTC, dremsol commented
> > Thanks for the PR. A quick test with my BME680 and the supplied config `bme680_iaq_33v_300s_4d` seems that `uint8_t` doesn't cover the range of specific entries.
> 
> You'll have to use the format from the .c file or just remove the first number (it probably is just the length).
> 
> Be aware that the only BSEC 2.2 is available on github, this is not the same version as the config files you are using. BME680 is only supported officially in 2.4.

Thanks, I've been using the .csv file. However you are right, BME680 doesn't seem to work yet with BSEC 2.2

```
[19:52:59][C][bme68x_bsec.sensor:134]: BME68X via BSEC:
[19:52:59][C][bme68x_bsec.sensor:139]:   BSEC Version: 2.2.0.0
[19:52:59][C][bme68x_bsec.sensor:141]:   Address: 0x77
[19:52:59][E][bme68x_bsec.sensor:145]: Communication failed (BSEC Status: -34, BME68X Status: 0)
```

2023-04-01 08:42 UTC, dremsol commented
The upstream repository has been updated to BSEC 2.4.0.0. However, your [request](https://github.com/boschsensortec/Bosch-BSEC2-Library/issues/20) to include the configs has not been included unfortunately. 

Trying to compile against this version results in a error. Seems like the library is not correctly linked and therefore some functions are out of scope?
`error: 'bsec_init' was not declared in this scope`

2023-04-01 14:12 UTC, neffs commented
> Trying to compile against this version results in a error. Seems like the library is not correctly linked and therefore some functions are out of scope? `error: 'bsec_init' was not declared in this scope`

they changed their interface for multi-instance support. I'll have to change some code.

2023-04-04 21:10 UTC, Schluggi commented
Thank you for your awesome work. Since your bsec2 branch does not work anymore with the latest esphome version i tried this PR. But I was not able to compile:

![image](https://user-images.githubusercontent.com/43608073/229923184-77e37c10-2d30-4b3f-bf3d-e3da39d85ba1.png)


```text
INFO Reading configuration /config/all-in-one-test.yaml...
ERROR Unable to import component bme68x_bsec:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 165, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/.esphome/external_components/0afd76d4/esphome/components/bme68x_bsec/__init__.py", line 4, in <module>
    from esphome.const import CONF_ID, CONF_TEMPERATURE_OFFSET
ImportError: cannot import name 'CONF_TEMPERATURE_OFFSET' from 'esphome.const' (/esphome/esphome/const.py)
Failed config

bme68x_bsec: [source /config/all-in-one-test.yaml:45]
  
  Component not found: bme68x_bsec.
```

Same error for `bme680_bsec`.

2023-05-08 22:14 UTC, TamasKazsoki commented
So the case is that currently there is no way to use Bosch BSEC library with ESP other than ESP8266 in esphome because:

- BSEC is not supported on ESP32-C3/S2/S3 devices. Only BSEC2 supports these platforms officially. Some fix have been made to address this, previously I used the one made by @Schluggi and it worked well before esphome 2023.3.0
- Platform restrictions has been implemented in esphome 2023.4.0: Fix platform restriction for bme680_bsec https://github.com/esphome/esphome/pull/4616 by [@jesserockz](https://github.com/jesserockz) Because of this fix, there is no way to use bme680_bsec with ESP32 with external componenst

The best would be to replace the current and old bme680_bsec with the new Bosch BSEC2 library, because:
- BSEC2 has support for more devices like RPI2040 and ESP32-C3/S2/S3 as well officially
- BSEC2 supports more devices: it supports BME680 and BME688 as well while BSEC is only supports BME680

2023-05-15 18:49 UTC, tactmaster commented
@TamasKazsoki  Make a good point that this should just be used to upgrade bme680_bsec. The old bme680_bsec lib doesn't have the latest BSEC1 lib which does support BME688.

I have tired this lib on my bme688. Seems to be working. (I also rebase it to master and it works fine too)

The values seem a little high but I am waiting for them to bed  in. 
![image](https://github.com/esphome/esphome/assets/793117/a53f532a-b07a-433b-8407-0c682f8d47b1)


The configs are on github here:

[https://github.com/boschsensortec/BSEC-Arduino-library/blob/21213272be0fcb8f6d886089b38068b1ae25c3de/src/config](https://github.com/boschsensortec/BSEC-Arduino-library/blob/21213272be0fcb8f6d886089b38068b1ae25c3de/src/config)
 I tired [generic_18v_3s_4d](https://github.com/boschsensortec/BSEC-Arduino-library/blob/21213272be0fcb8f6d886089b38068b1ae25c3de/src/config/generic_18v_3s_4d/bsec_iaq.txt)
 and it seem to get no values of of the device. Not even humity and pressure etc.

2023-06-11 23:46 UTC, selfmade01 commented
Hi,

I would also like to use the BME688 with the "BSEC" library on an ESP32-Sa-Saola-1.
Is that possible or do I have to pay attention to a few things or can I not use something?

That would be really great if I could use this sBME688 with my ESP32-S2  and ESPHOME.

2023-08-23 16:07 UTC, fran6120 commented
Bosch has been released a new library version https://github.com/boschsensortec/Bosch-BSEC2-Library/releases/tag/v1.6.2400

2023-10-12 23:15 UTC, tao-j commented
This device yaml works for 2023.10.2 and ESP32-S2. Users may want to use it temporarily it before this PR is merged. 

```yaml
external_components:
  - source: github://tao-j/esphome@dev
    components: [ bme68x_bsec ]
    # refresh: 1d

bme68x_bsec:
  state_save_interval: 30min
  bsec_configuration: 0,0,2,2,189,1,0,0,0,0,0,0,213,8,0,0,52,0,1,0,0,192,168,71,64,49,119,76,0,0,97,69,0,0,97,69,137,65,0,63,0,0,0,63,0,0,64,63,205,204,204,62,10,0,3,0,216,85,0,100,0,0,96,64,23,183,209,56,28,0,2,0,0,244,1,150,0,50,0,0,128,64,0,0,32,65,144,1,0,0,112,65,0,0,0,63,16,0,3,0,10,215,163,60,10,215,35,59,10,215,35,59,13,0,5,0,0,0,0,0,100,35,41,29,86,88,0,9,0,229,208,34,62,0,0,0,0,0,0,0,0,218,27,156,62,225,11,67,64,0,0,160,64,0,0,0,0,0,0,0,0,94,75,72,189,93,254,159,64,66,62,160,191,0,0,0,0,0,0,0,0,33,31,180,190,138,176,97,64,65,241,99,190,0,0,0,0,0,0,0,0,167,121,71,61,165,189,41,192,184,30,189,64,12,0,10,0,0,0,0,0,0,0,0,0,173,6,11,0,1,2,2,207,61,208,65,149,110,24,66,180,108,177,65,219,148,13,192,70,132,58,66,163,58,140,192,12,99,178,192,185,59,255,193,178,213,175,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,110,211,55,195,237,6,56,67,0,0,0,0,0,0,0,0,26,3,255,63,61,246,7,192,171,201,228,192,249,144,215,63,237,199,104,193,128,158,216,64,117,140,155,63,137,120,129,67,108,109,253,191,0,0,0,0,81,64,57,68,103,241,231,64,109,29,152,192,209,43,193,63,93,54,30,65,197,46,92,64,128,27,224,192,6,20,144,191,56,179,130,64,0,0,0,0,43,156,59,196,33,217,100,194,104,77,72,65,15,103,175,191,249,252,12,193,63,117,253,192,233,5,141,65,155,42,25,64,13,88,249,191,0,0,0,0,48,141,122,190,204,150,44,192,36,162,29,193,96,59,39,189,54,202,48,65,151,205,68,64,79,105,55,193,53,120,53,192,77,211,32,192,0,0,0,0,193,207,92,65,239,201,76,65,208,70,82,66,81,63,96,65,48,179,0,194,251,96,242,193,176,51,96,194,153,114,98,66,144,247,64,65,0,0,0,0,219,179,180,63,175,218,119,191,51,71,207,191,245,145,129,63,53,16,244,65,138,208,117,65,138,97,36,66,228,15,32,195,126,91,103,191,0,0,0,0,26,151,170,193,64,105,49,193,46,223,189,193,129,203,168,193,40,91,49,66,4,87,107,65,205,202,37,65,244,36,154,66,240,85,39,193,0,0,0,0,166,96,87,192,114,7,68,191,233,32,214,63,84,249,40,192,45,78,132,64,145,33,253,61,49,43,187,192,244,32,77,67,224,250,71,191,0,0,0,0,103,75,214,190,206,141,252,63,99,15,178,65,80,79,166,190,214,25,146,192,165,29,24,194,18,228,219,193,113,246,235,194,49,115,232,63,0,0,0,0,17,211,124,64,56,252,251,62,25,118,148,193,168,234,94,64,131,157,82,64,217,119,236,65,120,245,240,65,17,69,168,195,49,51,8,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,217,97,66,182,104,101,194,0,0,0,0,0,0,0,0,6,142,142,195,229,54,143,67,0,0,0,0,0,0,0,0,25,224,153,66,217,51,154,194,0,0,0,0,0,0,0,0,142,36,105,194,199,63,110,66,0,0,0,0,0,0,0,0,206,73,250,193,138,69,249,65,0,0,0,0,0,0,0,0,123,173,127,66,20,116,128,194,0,0,0,0,0,0,0,0,49,65,49,64,205,213,107,192,0,0,0,0,0,0,0,0,189,250,179,194,164,98,180,66,0,0,0,0,0,0,0,0,96,182,197,67,155,71,197,195,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,185,28,179,73,64,25,141,76,223,26,138,76,222,207,133,76,87,134,164,75,23,127,159,75,166,9,155,75,94,120,170,73,95,221,177,73,93,44,182,73,0,0,0,0,0,0,0,0,0,0,0,0,30,55,120,73,215,98,32,76,7,79,34,76,161,238,36,76,119,151,160,75,119,96,157,75,202,75,154,75,118,89,111,73,133,239,116,73,219,140,120,73,0,0,128,63,0,0,128,63,0,0,128,63,0,0,0,87,1,254,0,2,1,5,48,117,100,0,44,1,112,23,151,7,132,3,197,0,92,4,144,1,64,1,64,1,144,1,48,117,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,48,117,48,117,8,7,8,7,8,7,8,7,8,7,100,0,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,100,0,100,0,255,255,255,255,255,255,255,255,255,255,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,255,255,255,255,255,255,255,255,255,255,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,255,255,255,255,255,255,255,255,255,255,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,220,5,220,5,220,5,255,255,255,255,255,255,220,5,220,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,48,117,0,5,10,5,0,2,0,10,0,30,0,5,0,5,0,5,0,5,0,5,0,5,0,64,1,100,0,100,0,100,0,200,0,200,0,200,0,64,1,64,1,64,1,10,0,0,0,0,145,33,0,0
  address: 0x77

sensor:
  - platform: bme68x_bsec
    temperature:
      name: "BME688 Temperature"
      id: temperature
    pressure:
      name: "BME688 Pressure"
      id: pressure
      device_class: atmospheric_pressure
    humidity:
      name: "BME688 Humidity"
      id: humidity
    iaq:
      name: "BME688 IAQ"
      id: iaq
      device_class: aqi
    co2_equivalent:
      name: "BME688 CO2 Equivalent"
      device_class: carbon_dioxide
    breath_voc_equivalent:
      name: "BME688 Breath VOC Equivalent"
      device_class: volatile_organic_compounds

text_sensor:
  - platform: template
    name: "BME688 IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }
```

2023-10-13 09:17 UTC, fran6120 commented
I can confirm that it works on ESP32-C3

Thank you so much!

2023-10-13 20:08 UTC, chaudi commented
> This device yaml works for 2023.10.2 and ESP32-S2. Users may want to use it temporarily it before this PR is merged.
> 
> ```yaml
> external_components:
>   - source: github://tao-j/esphome@dev
>     components: [ bme68x_bsec ]
>     # refresh: 1d
> 
> bme68x_bsec:
>   state_save_interval: 30min
>   bsec_configuration: 0,0,2,2,189,1,0,0,0,0,0,0,213,8,0,0,52,0,1,0,0,192,168,71,64,49,119,76,0,0,97,69,0,0,97,69,137,65,0,63,0,0,0,63,0,0,64,63,205,204,204,62,10,0,3,0,216,85,0,100,0,0,96,64,23,183,209,56,28,0,2,0,0,244,1,150,0,50,0,0,128,64,0,0,32,65,144,1,0,0,112,65,0,0,0,63,16,0,3,0,10,215,163,60,10,215,35,59,10,215,35,59,13,0,5,0,0,0,0,0,100,35,41,29,86,88,0,9,0,229,208,34,62,0,0,0,0,0,0,0,0,218,27,156,62,225,11,67,64,0,0,160,64,0,0,0,0,0,0,0,0,94,75,72,189,93,254,159,64,66,62,160,191,0,0,0,0,0,0,0,0,33,31,180,190,138,176,97,64,65,241,99,190,0,0,0,0,0,0,0,0,167,121,71,61,165,189,41,192,184,30,189,64,12,0,10,0,0,0,0,0,0,0,0,0,173,6,11,0,1,2,2,207,61,208,65,149,110,24,66,180,108,177,65,219,148,13,192,70,132,58,66,163,58,140,192,12,99,178,192,185,59,255,193,178,213,175,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,110,211,55,195,237,6,56,67,0,0,0,0,0,0,0,0,26,3,255,63,61,246,7,192,171,201,228,192,249,144,215,63,237,199,104,193,128,158,216,64,117,140,155,63,137,120,129,67,108,109,253,191,0,0,0,0,81,64,57,68,103,241,231,64,109,29,152,192,209,43,193,63,93,54,30,65,197,46,92,64,128,27,224,192,6,20,144,191,56,179,130,64,0,0,0,0,43,156,59,196,33,217,100,194,104,77,72,65,15,103,175,191,249,252,12,193,63,117,253,192,233,5,141,65,155,42,25,64,13,88,249,191,0,0,0,0,48,141,122,190,204,150,44,192,36,162,29,193,96,59,39,189,54,202,48,65,151,205,68,64,79,105,55,193,53,120,53,192,77,211,32,192,0,0,0,0,193,207,92,65,239,201,76,65,208,70,82,66,81,63,96,65,48,179,0,194,251,96,242,193,176,51,96,194,153,114,98,66,144,247,64,65,0,0,0,0,219,179,180,63,175,218,119,191,51,71,207,191,245,145,129,63,53,16,244,65,138,208,117,65,138,97,36,66,228,15,32,195,126,91,103,191,0,0,0,0,26,151,170,193,64,105,49,193,46,223,189,193,129,203,168,193,40,91,49,66,4,87,107,65,205,202,37,65,244,36,154,66,240,85,39,193,0,0,0,0,166,96,87,192,114,7,68,191,233,32,214,63,84,249,40,192,45,78,132,64,145,33,253,61,49,43,187,192,244,32,77,67,224,250,71,191,0,0,0,0,103,75,214,190,206,141,252,63,99,15,178,65,80,79,166,190,214,25,146,192,165,29,24,194,18,228,219,193,113,246,235,194,49,115,232,63,0,0,0,0,17,211,124,64,56,252,251,62,25,118,148,193,168,234,94,64,131,157,82,64,217,119,236,65,120,245,240,65,17,69,168,195,49,51,8,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,217,97,66,182,104,101,194,0,0,0,0,0,0,0,0,6,142,142,195,229,54,143,67,0,0,0,0,0,0,0,0,25,224,153,66,217,51,154,194,0,0,0,0,0,0,0,0,142,36,105,194,199,63,110,66,0,0,0,0,0,0,0,0,206,73,250,193,138,69,249,65,0,0,0,0,0,0,0,0,123,173,127,66,20,116,128,194,0,0,0,0,0,0,0,0,49,65,49,64,205,213,107,192,0,0,0,0,0,0,0,0,189,250,179,194,164,98,180,66,0,0,0,0,0,0,0,0,96,182,197,67,155,71,197,195,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,185,28,179,73,64,25,141,76,223,26,138,76,222,207,133,76,87,134,164,75,23,127,159,75,166,9,155,75,94,120,170,73,95,221,177,73,93,44,182,73,0,0,0,0,0,0,0,0,0,0,0,0,30,55,120,73,215,98,32,76,7,79,34,76,161,238,36,76,119,151,160,75,119,96,157,75,202,75,154,75,118,89,111,73,133,239,116,73,219,140,120,73,0,0,128,63,0,0,128,63,0,0,128,63,0,0,0,87,1,254,0,2,1,5,48,117,100,0,44,1,112,23,151,7,132,3,197,0,92,4,144,1,64,1,64,1,144,1,48,117,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,48,117,48,117,8,7,8,7,8,7,8,7,8,7,100,0,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,100,0,100,0,255,255,255,255,255,255,255,255,255,255,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,255,255,255,255,255,255,255,255,255,255,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,255,255,255,255,255,255,255,255,255,255,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,220,5,220,5,220,5,255,255,255,255,255,255,220,5,220,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,48,117,0,5,10,5,0,2,0,10,0,30,0,5,0,5,0,5,0,5,0,5,0,5,0,64,1,100,0,100,0,100,0,200,0,200,0,200,0,64,1,64,1,64,1,10,0,0,0,0,145,33,0,0
>   address: 0x77
> 
> sensor:
>   - platform: bme68x_bsec
>     temperature:
>       name: "BME688 Temperature"
>       id: temperature
>     pressure:
>       name: "BME688 Pressure"
>       id: pressure
>       device_class: atmospheric_pressure
>     humidity:
>       name: "BME688 Humidity"
>       id: humidity
>     iaq:
>       name: "BME688 IAQ"
>       id: iaq
>       device_class: aqi
>     co2_equivalent:
>       name: "BME688 CO2 Equivalent"
>       device_class: carbon_dioxide
>     breath_voc_equivalent:
>       name: "BME688 Breath VOC Equivalent"
>       device_class: volatile_organic_compounds
> 
> text_sensor:
>   - platform: template
>     name: "BME688 IAQ Classification"
>     icon: "mdi:checkbox-marked-circle-outline"
>     lambda: |-
>       if ( int(id(iaq).state) <= 50) {
>         return {"Excellent"};
>       }
>       else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
>         return {"Good"};
>       }
>       else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
>         return {"Lightly polluted"};
>       }
>       else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
>         return {"Moderately polluted"};
>       }
>       else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
>         return {"Heavily polluted"};
>       }
>       else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
>         return {"Severely polluted"};
>       }
>       else if (int(id(iaq).state) >= 351) {
>         return {"Extremely polluted"};
>       }
>       else {
>         return {"error"};
>       }
> ```

Just to confirm, it works on Raspberry Pico as well.

Need to [...]

2023-10-13 20:51 UTC, tao-j commented
Thanks for testing

> But no way of settings sample_rate of the gas sensor?

bsec_configuration can control the sample rate. There are multiple versions that can be used, you can download premade strings from bosch (not github). 3s or 300s are given.

2023-10-13 20:55 UTC, cityeyes commented
If I understand, these configs are just to get the BME68X device working on different ESP boards, right?

Those of us with older devices that are having issues with accuracy in the gas pressure sensors will have to wait for the merge of Bosch's new version?

Just want to make sure. My two devices are working fine outside of the voc/co2, which are wildly off. Excited to have it fixed eventually.

2023-10-13 21:17 UTC, chaudi commented
> Thanks for testing
> 
> > But no way of settings sample_rate of the gas sensor?
> 
> bsec_configuration can control the sample rate. There are multiple versions that can be used, you can download premade strings from bosch (not github). 3s or 300s are given.

Right, I see.

Thank you again!

2023-10-14 17:52 UTC, bvolkmer commented
> This device yaml works for 2023.10.2 and ESP32-S2. Users may want to use it temporarily it before this PR is merged.
> 
> ```yaml
> external_components:
>   - source: github://tao-j/esphome@dev
>     components: [ bme68x_bsec ]
>     # refresh: 1d
> 
> bme68x_bsec:
>   state_save_interval: 30min
>   bsec_configuration: 0,0,2,2,189,1,0,0,0,0,0,0,213,8,0,0,52,0,1,0,0,192,168,71,64,49,119,76,0,0,97,69,0,0,97,69,137,65,0,63,0,0,0,63,0,0,64,63,205,204,204,62,10,0,3,0,216,85,0,100,0,0,96,64,23,183,209,56,28,0,2,0,0,244,1,150,0,50,0,0,128,64,0,0,32,65,144,1,0,0,112,65,0,0,0,63,16,0,3,0,10,215,163,60,10,215,35,59,10,215,35,59,13,0,5,0,0,0,0,0,100,35,41,29,86,88,0,9,0,229,208,34,62,0,0,0,0,0,0,0,0,218,27,156,62,225,11,67,64,0,0,160,64,0,0,0,0,0,0,0,0,94,75,72,189,93,254,159,64,66,62,160,191,0,0,0,0,0,0,0,0,33,31,180,190,138,176,97,64,65,241,99,190,0,0,0,0,0,0,0,0,167,121,71,61,165,189,41,192,184,30,189,64,12,0,10,0,0,0,0,0,0,0,0,0,173,6,11,0,1,2,2,207,61,208,65,149,110,24,66,180,108,177,65,219,148,13,192,70,132,58,66,163,58,140,192,12,99,178,192,185,59,255,193,178,213,175,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,110,211,55,195,237,6,56,67,0,0,0,0,0,0,0,0,26,3,255,63,61,246,7,192,171,201,228,192,249,144,215,63,237,199,104,193,128,158,216,64,117,140,155,63,137,120,129,67,108,109,253,191,0,0,0,0,81,64,57,68,103,241,231,64,109,29,152,192,209,43,193,63,93,54,30,65,197,46,92,64,128,27,224,192,6,20,144,191,56,179,130,64,0,0,0,0,43,156,59,196,33,217,100,194,104,77,72,65,15,103,175,191,249,252,12,193,63,117,253,192,233,5,141,65,155,42,25,64,13,88,249,191,0,0,0,0,48,141,122,190,204,150,44,192,36,162,29,193,96,59,39,189,54,202,48,65,151,205,68,64,79,105,55,193,53,120,53,192,77,211,32,192,0,0,0,0,193,207,92,65,239,201,76,65,208,70,82,66,81,63,96,65,48,179,0,194,251,96,242,193,176,51,96,194,153,114,98,66,144,247,64,65,0,0,0,0,219,179,180,63,175,218,119,191,51,71,207,191,245,145,129,63,53,16,244,65,138,208,117,65,138,97,36,66,228,15,32,195,126,91,103,191,0,0,0,0,26,151,170,193,64,105,49,193,46,223,189,193,129,203,168,193,40,91,49,66,4,87,107,65,205,202,37,65,244,36,154,66,240,85,39,193,0,0,0,0,166,96,87,192,114,7,68,191,233,32,214,63,84,249,40,192,45,78,132,64,145,33,253,61,49,43,187,192,244,32,77,67,224,250,71,191,0,0,0,0,103,75,214,190,206,141,252,63,99,15,178,65,80,79,166,190,214,25,146,192,165,29,24,194,18,228,219,193,113,246,235,194,49,115,232,63,0,0,0,0,17,211,124,64,56,252,251,62,25,118,148,193,168,234,94,64,131,157,82,64,217,119,236,65,120,245,240,65,17,69,168,195,49,51,8,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,217,97,66,182,104,101,194,0,0,0,0,0,0,0,0,6,142,142,195,229,54,143,67,0,0,0,0,0,0,0,0,25,224,153,66,217,51,154,194,0,0,0,0,0,0,0,0,142,36,105,194,199,63,110,66,0,0,0,0,0,0,0,0,206,73,250,193,138,69,249,65,0,0,0,0,0,0,0,0,123,173,127,66,20,116,128,194,0,0,0,0,0,0,0,0,49,65,49,64,205,213,107,192,0,0,0,0,0,0,0,0,189,250,179,194,164,98,180,66,0,0,0,0,0,0,0,0,96,182,197,67,155,71,197,195,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,185,28,179,73,64,25,141,76,223,26,138,76,222,207,133,76,87,134,164,75,23,127,159,75,166,9,155,75,94,120,170,73,95,221,177,73,93,44,182,73,0,0,0,0,0,0,0,0,0,0,0,0,30,55,120,73,215,98,32,76,7,79,34,76,161,238,36,76,119,151,160,75,119,96,157,75,202,75,154,75,118,89,111,73,133,239,116,73,219,140,120,73,0,0,128,63,0,0,128,63,0,0,128,63,0,0,0,87,1,254,0,2,1,5,48,117,100,0,44,1,112,23,151,7,132,3,197,0,92,4,144,1,64,1,64,1,144,1,48,117,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,48,117,48,117,8,7,8,7,8,7,8,7,8,7,100,0,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,100,0,100,0,255,255,255,255,255,255,255,255,255,255,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,255,255,255,255,255,255,255,255,255,255,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,8,7,255,255,255,255,255,255,255,255,255,255,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,112,23,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,220,5,220,5,220,5,255,255,255,255,255,255,220,5,220,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,48,117,0,5,10,5,0,2,0,10,0,30,0,5,0,5,0,5,0,5,0,5,0,5,0,64,1,100,0,100,0,100,0,200,0,200,0,200,0,64,1,64,1,64,1,10,0,0,0,0,145,33,0,0
>   address: 0x77
> 
> sensor:
>   - platform: bme68x_bsec
>     temperature:
>       name: "BME688 Temperature"
>       id: temperature
>     pressure:
>       name: "BME688 Pressure"
>       id: pressure
>       device_class: atmospheric_pressure
>     humidity:
>       name: "BME688 Humidity"
>       id: humidity
>     iaq:
>       name: "BME688 IAQ"
>       id: iaq
>       device_class: aqi
>     co2_equivalent:
>       name: "BME688 CO2 Equivalent"
>       device_class: carbon_dioxide
>     breath_voc_equivalent:
>       name: "BME688 Breath VOC Equivalent"
>       device_class: volatile_organic_compounds
> 
> text_sensor:
>   - platform: template
>     name: "BME688 IAQ Classification"
>     icon: "mdi:checkbox-marked-circle-outline"
>     lambda: |-
>       if ( int(id(iaq).state) <= 50) {
>         return {"Excellent"};
>       }
>       else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
>         return {"Good"};
>       }
>       else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
>         return {"Lightly polluted"};
>       }
>       else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
>         return {"Moderately polluted"};
>       }
>       else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
>         return {"Heavily polluted"};
>       }
>       else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
>         return {"Severely polluted"};
>       }
>       else if (int(id(iaq).state) >= 351) {
>         return {"Extremely polluted"};
>       }
>       else {
>         return {"error"};
>       }
> ```

Can confirm that this is working for BME680 and ESP32-C3 if i [...]

2023-10-19 11:07 UTC, cederfelt commented
> Thanks for testing
> 
> > But no way of settings sample_rate of the gas sensor?
> 
> bsec_configuration can control the sample rate. There are multiple versions that can be used, you can download premade strings from bosch (not github). 3s or 300s are given.

Hm, I'v tried a couple of different configurations like, bsec_sel_iaq_33v_300s_4d and bsec_sel_iaq_33v_300s_28d. but the sensor is still polled every 3 seconds. Am I missing something?

2023-11-01 10:34 UTC, SeveranExp commented
Hey everyone, just wanted to say that I’ve been following this work and I’m super excited to see bsec 2 included (soon I hope) with esphome!
Just a generic hint (I failed to see this mentioned before and I think it’s important) Bosch sensortec has a community for devs and makers to participate, ask questions and get support. Here’s the link:
https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/bd-p/bst_community-mems-forum

They do track issues and address them, so if you haven’t yet, head over there and make use of the support they provide. They do improve bsec based on customer feedback ;) 
If anyone needs a bme680 for testing feel free to reach out :)

2023-12-01 18:28 UTC, dremsol commented
Works here with `ESP32-S3-DevKitC-1-N32R8V` and `Adafruit BME60`.

2023-12-06 12:03 UTC, TCB13 commented
> > Trying to compile against this version results in a error. Seems like the library is not correctly linked and therefore some functions are out of scope? `error: 'bsec_init' was not declared in this scope`
> 
> they changed their interface for multi-instance support. I'll have to change some code.

Thank you for your efforts @neffs any updates on this?

What about the [solution provided](https://github.com/esphome/esphome/pull/4585#issuecomment-1760506962) by @tao-j does it support the BME680 or just the 688? Thank you all.

2023-12-10 19:42 UTC, neffs commented
I made some updates to the component. It can now be included with "external_components" and uses the current bsec2 library, which should also support multiple sensors.

```yaml
external_components:
  - source: github://neffs/esphome@bsec2_bme68x
    components: [ bme68x_bsec ]

i2c:

bme68x_bsec:
  state_save_interval: 30min
  bsec_configuration: 0,0,4,2,189,1,0,0,0,0,0,0,158,7,0,0,176,0,1,0,0,192,168,71,64,49,119,76,0,0,97,69,0,0,97,69,137,65,0,63,0,0,0,63,0,0,64,63,205,204,204,62,10,0,3,0,0,0,96,64,23,183,209,56,0,0,0,0,0,0,0,0,0,0,0,0,205,204,204,189,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,82,73,157,188,95,41,203,61,118,224,108,63,155,230,125,63,191,14,124,63,0,0,160,65,0,0,32,66,0,0,160,65,0,0,32,66,0,0,32,66,0,0,160,65,0,0,32,66,0,0,160,65,8,0,2,0,236,81,133,66,16,0,3,0,10,215,163,60,10,215,35,59,10,215,35,59,13,0,5,0,0,0,0,0,100,35,41,29,86,88,0,9,0,229,208,34,62,0,0,0,0,0,0,0,0,218,27,156,62,225,11,67,64,0,0,160,64,0,0,0,0,0,0,0,0,94,75,72,189,93,254,159,64,66,62,160,191,0,0,0,0,0,0,0,0,33,31,180,190,138,176,97,64,65,241,99,190,0,0,0,0,0,0,0,0,167,121,71,61,165,189,41,192,184,30,189,64,12,0,10,0,0,0,0,0,0,0,0,0,13,5,11,0,1,2,2,207,61,208,65,149,110,24,66,180,108,177,65,219,148,13,192,70,132,58,66,163,58,140,192,12,99,178,192,185,59,255,193,178,213,175,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,110,211,55,195,237,6,56,67,0,0,0,0,0,0,0,0,26,3,255,63,61,246,7,192,171,201,228,192,249,144,215,63,237,199,104,193,128,158,216,64,117,140,155,63,137,120,129,67,108,109,253,191,0,0,0,0,81,64,57,68,103,241,231,64,109,29,152,192,209,43,193,63,93,54,30,65,197,46,92,64,128,27,224,192,6,20,144,191,56,179,130,64,0,0,0,0,43,156,59,196,33,217,100,194,104,77,72,65,15,103,175,191,249,252,12,193,63,117,253,192,233,5,141,65,155,42,25,64,13,88,249,191,0,0,0,0,48,141,122,190,204,150,44,192,36,162,29,193,96,59,39,189,54,202,48,65,151,205,68,64,79,105,55,193,53,120,53,192,77,211,32,192,0,0,0,0,193,207,92,65,239,201,76,65,208,70,82,66,81,63,96,65,48,179,0,194,251,96,242,193,176,51,96,194,153,114,98,66,144,247,64,65,0,0,0,0,219,179,180,63,175,218,119,191,51,71,207,191,245,145,129,63,53,16,244,65,138,208,117,65,138,97,36,66,228,15,32,195,126,91,103,191,0,0,0,0,26,151,170,193,64,105,49,193,46,223,189,193,129,203,168,193,40,91,49,66,4,87,107,65,205,202,37,65,244,36,154,66,240,85,39,193,0,0,0,0,166,96,87,192,114,7,68,191,233,32,214,63,84,249,40,192,45,78,132,64,145,33,253,61,49,43,187,192,244,32,77,67,224,250,71,191,0,0,0,0,103,75,214,190,206,141,252,63,99,15,178,65,80,79,166,190,214,25,146,192,165,29,24,194,18,228,219,193,113,246,235,194,49,115,232,63,0,0,0,0,17,211,124,64,56,252,251,62,25,118,148,193,168,234,94,64,131,157,82,64,217,119,236,65,120,245,240,65,17,69,168,195,49,51,8,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,217,97,66,182,104,101,194,0,0,0,0,0,0,0,0,6,142,142,195,229,54,143,67,0,0,0,0,0,0,0,0,25,224,153,66,217,51,154,194,0,0,0,0,0,0,0,0,142,36,105,194,199,63,110,66,0,0,0,0,0,0,0,0,206,73,250,193,138,69,249,65,0,0,0,0,0,0,0,0,123,173,127,66,20,116,128,194,0,0,0,0,0,0,0,0,49,65,49,64,205,213,107,192,0,0,0,0,0,0,0,0,189,250,179,194,164,98,180,66,0,0,0,0,0,0,0,0,96,182,197,67,155,71,197,195,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,2,185,28,179,73,64,25,141,76,223,26,138,76,222,207,133,76,87,134,164,75,23,127,159,75,166,9,155,75,94,120,170,73,95,221,177,73,93,44,182,73,0,0,0,0,0,0,0,0,0,0,0,0,30,55,120,73,215,98,32,76,7,79,34,76,161,238,36,76,119,151,160,75,119,96,157,75,202,75,154,75,118,89,111,73,133,239,116,73,219,140,120,73,0,0,128,63,0,0,128,63,0,0,128,63,0,0,0,88,1,254,0,2,1,5,48,117,100,0,44,1,112,23,151,7,132,3,197,0,92,4,144,1,64,1,64,1,144,1,48,117,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,48,117,48,117,8,7,8,7,8,7,8,7,8,7,100,0,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,100,0,100,0,255,255,255,255,255,255,255,255,255,255,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,255,255,255,255,255,255,255,255,255,255,112,23,112,23,112,23,112,23,8,7,8,7,8,7,8,7,112,23,112,23,112,23,112,23,112,23,112,23,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,112,23,112,23,112,23,112,23,255,255,255,255,220,5,220,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,220,5,220,5,220,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,44,1,0,5,10,5,0,2,0,10,0,30,0,5,0,5,0,5,0,5,0,5,0,5,0,64,1,100,0,100,0,100,0,200,0,200,0,200,0,64,1,64,1,64,1,10,1,0,0,0,0,233,74,0,0
sensor:
  - platform: bme68x_bsec
    temperature:
      name: "BME680 Temperature"
      filters:
        - median
    pressure:
      name: "BME680 Pressure"
      filters:
        - median
    humidity:
      name: "BME680 Humidity"
      filters:
        - median
    iaq:
      name: "BME680 IAQ"
      filters:
        - median
    iaq_static:
      name: "BME680 Static IAQ"
      filters:
        - median
    co2_equivalent:
      name: "BME680 CO2 Equivalent"
      filters:
        - median
    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"
      filters:
        - median
    gas_resistance:
      # Gas resistance in Ω
      name: "BME680 Gas Resistance"
      filters:
        - median
text_sensor:
  - platform: bme68x_bsec
    iaq_accuracy: 
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: "BME680 IAQ Accuracy"
```

2023-12-10 19:58 UTC, dremsol commented
@neffs works for me with ESP32-S3 and BME680. Which bsec configuration did you pick?
<img width="595" alt="image" src="https://github.com/esphome/esphome/assets/34475288/5fcbd827-1470-491f-95ed-8353a13d6766">

2023-12-10 20:02 UTC, neffs commented
> @neffs works for me with ESP32-S3 and BME680. Which bsec configuration did you pick? 

I'm using bme688_sel_33v_3s_4d

Still waiting for https://github.com/boschsensortec/Bosch-BSEC2-Library/issues/20 to be closed

2023-12-29 19:21 UTC, hagak commented
@neffs I recently have tried using your branch on my Seeed ESP32-C3 board

I get an issue bsec2.h: no such file or directory.  It is acting like it can not get the header from platformio
```
In file included from src/esphome/components/bme68x_bsec/bme68x_bsec.cpp:1:
src/esphome/components/bme68x_bsec/bme68x_bsec.h:12:10: fatal error: bsec2.h: No such file or directory

***************************************************************
* Looking for bsec2.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:bsec2.h"
* Web  > https://registry.platformio.org/search?q=header:bsec2.h
*
***************************************************************

 #include <bsec2.h>
          ^~~~~~~~~
compilation terminated.
```


``` 
external_components:
  - source: github://neffs/esphome@bsec2_bme68x
    components:
      - bme68x_bsec

bme68x_bsec:
  address: 0x77 
  state_save_interval: 30min
  bsec_configuration: 0,0,4,2,189,1,0,0,0,0,0,0,158,7,0,0,176,0,1,0,0,192,168,71,64,49,119,76,0,0,97,69,0,0,97,69,137,65,0,63,0,0,0,63,0,0,64,63,205,204,204,62,10,0,3,0,0,0,96,64,23,183,209,56,0,0,0,0,0,0,0,0,0,0,0,0,205,204,204,189,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,82,73,157,188,95,41,203,61,118,224,108,63,155,230,125,63,191,14,124,63,0,0,160,65,0,0,32,66,0,0,160,65,0,0,32,66,0,0,32,66,0,0,160,65,0,0,32,66,0,0,160,65,8,0,2,0,236,81,133,66,16,0,3,0,10,215,163,60,10,215,35,59,10,215,35,59,13,0,5,0,0,0,0,0,100,35,41,29,86,88,0,9,0,229,208,34,62,0,0,0,0,0,0,0,0,218,27,156,62,225,11,67,64,0,0,160,64,0,0,0,0,0,0,0,0,94,75,72,189,93,254,159,64,66,62,160,191,0,0,0,0,0,0,0,0,33,31,180,190,138,176,97,64,65,241,99,190,0,0,0,0,0,0,0,0,167,121,71,61,165,189,41,192,184,30,189,64,12,0,10,0,0,0,0,0,0,0,0,0,13,5,11,0,1,2,2,207,61,208,65,149,110,24,66,180,108,177,65,219,148,13,192,70,132,58,66,163,58,140,192,12,99,178,192,185,59,255,193,178,213,175,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,110,211,55,195,237,6,56,67,0,0,0,0,0,0,0,0,26,3,255,63,61,246,7,192,171,201,228,192,249,144,215,63,237,199,104,193,128,158,216,64,117,140,155,63,137,120,129,67,108,109,253,191,0,0,0,0,81,64,57,68,103,241,231,64,109,29,152,192,209,43,193,63,93,54,30,65,197,46,92,64,128,27,224,192,6,20,144,191,56,179,130,64,0,0,0,0,43,156,59,196,33,217,100,194,104,77,72,65,15,103,175,191,249,252,12,193,63,117,253,192,233,5,141,65,155,42,25,64,13,88,249,191,0,0,0,0,48,141,122,190,204,150,44,192,36,162,29,193,96,59,39,189,54,202,48,65,151,205,68,64,79,105,55,193,53,120,53,192,77,211,32,192,0,0,0,0,193,207,92,65,239,201,76,65,208,70,82,66,81,63,96,65,48,179,0,194,251,96,242,193,176,51,96,194,153,114,98,66,144,247,64,65,0,0,0,0,219,179,180,63,175,218,119,191,51,71,207,191,245,145,129,63,53,16,244,65,138,208,117,65,138,97,36,66,228,15,32,195,126,91,103,191,0,0,0,0,26,151,170,193,64,105,49,193,46,223,189,193,129,203,168,193,40,91,49,66,4,87,107,65,205,202,37,65,244,36,154,66,240,85,39,193,0,0,0,0,166,96,87,192,114,7,68,191,233,32,214,63,84,249,40,192,45,78,132,64,145,33,253,61,49,43,187,192,244,32,77,67,224,250,71,191,0,0,0,0,103,75,214,190,206,141,252,63,99,15,178,65,80,79,166,190,214,25,146,192,165,29,24,194,18,228,219,193,113,246,235,194,49,115,232,63,0,0,0,0,17,211,124,64,56,252,251,62,25,118,148,193,168,234,94,64,131,157,82,64,217,119,236,65,120,245,240,65,17,69,168,195,49,51,8,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,217,97,66,182,104,101,194,0,0,0,0,0,0,0,0,6,142,142,195,229,54,143,67,0,0,0,0,0,0,0,0,25,224,153,66,217,51,154,194,0,0,0,0,0,0,0,0,142,36,105,194,199,63,110,66,0,0,0,0,0,0,0,0,206,73,250,193,138,69,249,65,0,0,0,0,0,0,0,0,123,173,127,66,20,116,128,194,0,0,0,0,0,0,0,0,49,65,49,64,205,213,107,192,0,0,0,0,0,0,0,0,189,250,179,194,164,98,180,66,0,0,0,0,0,0,0,0,96,182,197,67,155,71,197,195,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,2,185,28,179,73,64,25,141,76,223,26,138,76,222,207,133,76,87,134,164,75,23,127,159,75,166,9,155,75,94,120,170,73,95,221,177,73,93,44,182,73,0,0,0,0,0,0,0,0,0,0,0,0,30,55,120,73,215,98,32,76,7,79,34,76,161,238,36,76,119,151,160,75,119,96,157,75,202,75,154,75,118,89,111,73,133,239,116,73,219,140,120,73,0,0,128,63,0,0,128,63,0,0,128,63,0,0,0,88,1,254,0,2,1,5,48,117,100,0,44,1,112,23,151,7,132,3,197,0,92,4,144,1,64,1,64,1,144,1,48,117,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,48,117,48,117,8,7,8,7,8,7,8,7,8,7,100,0,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,100,0,100,0,255,255,255,255,255,255,255,255,255,255,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,255,255,255,255,255,255,255,255,255,255,112,23,112,23,112,23,112,23,8,7,8,7,8,7,8,7,112,23,112,23,112,23,112,23,112,23,112,23,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,112,23,112,23,112,23,112,23,255,255,255,255,220,5,220,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,220,5,220,5,220,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,44,1,0,5,10,5,0,2,0,10,0,30,0,5,0,5,0,5,0,5,0,5,0,5,0,64,1,100,0,100,0,100,0,200,0,200,0,200,0,64,1,64,1,64,1,10,1,0,0,0,0,233,74,0,0

sensor:
  - platform: bme68x_bsec
    temperature:
      name: "BME680 Temperature"
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    iaq:
      name: "BME680 IAQ"
      id: iaq
    co2_equivalent:
      name: "BME680 CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"
 ```

2024-01-10 12:48 UTC, TCB13 commented
Thank you guys, @neffs in particular, for the work on this. I'm currently running a BME680 on a ESP32 S2 Mini with your code https://github.com/esphome/feature-requests/issues/1332#issuecomment-1883976632 and it works just fine.

2024-02-09 01:11 UTC, dek3rr commented
We have potential release configs! [https://github.com/boschsensortec/Bosch-BSEC2-Library/pull/35](url)

2024-02-15 14:03 UTC, Szewcson commented
@neffs Hi, I tried to use that component with bme680 and [bme680_iaq_33v_3s_4d](https://github.com/boschsensortec/Bosch-BSEC2-Library/tree/master/src/config/bme680/bme680_iaq_33v_3s_4d) config. I'm getting:

`[E][bme68x_bsec.sensor:145]: Communication failed (BSEC Status: 0, BME68X Status: 0)`

2024-02-15 17:24 UTC, Szewcson commented
Bumping library into v1.7.2502 fix the problem. It looks like they added regression operator which needs additional config values.

2024-02-21 07:57 UTC, Boxter91 commented
Hi, noob from Finland. 

> Bumping library into v1.7.2502 fix the problem. It looks like they added regression operator which needs additional config values.

Is there any change that you could give me instructions or working yaml config to get bme688 to work with esphome. Board adafruit QTPY esp32s2 with stemma 

`i2c:
  sda: 41
  scl: 40
  scan: True


external_components:
  - source: github://neffs/esphome@bsec2_bme68x
    components:
      - bme68x_bsec

bme68x_bsec:
  address: 0x77 
  state_save_interval: 30min
  bsec_configuration: 0,0,4,2,189,1,0,0,0,0,0,0,158,7,0,0,176,0,1,0,0,192,168,71,64,49,119,76,0,0,97,69,0,0,97,69,137,65,0,63,0,0,0,63,0,0,64,63,205,204,204,62,10,0,3,0,0,0,96,64,23,183,209,56,0,0,0,0,0,0,0,0,0,0,0,0,205,204,204,189,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,82,73,157,188,95,41,203,61,118,224,108,63,155,230,125,63,191,14,124,63,0,0,160,65,0,0,32,66,0,0,160,65,0,0,32,66,0,0,32,66,0,0,160,65,0,0,32,66,0,0,160,65,8,0,2,0,236,81,133,66,16,0,3,0,10,215,163,60,10,215,35,59,10,215,35,59,13,0,5,0,0,0,0,0,100,35,41,29,86,88,0,9,0,229,208,34,62,0,0,0,0,0,0,0,0,218,27,156,62,225,11,67,64,0,0,160,64,0,0,0,0,0,0,0,0,94,75,72,189,93,254,159,64,66,62,160,191,0,0,0,0,0,0,0,0,33,31,180,190,138,176,97,64,65,241,99,190,0,0,0,0,0,0,0,0,167,121,71,61,165,189,41,192,184,30,189,64,12,0,10,0,0,0,0,0,0,0,0,0,13,5,11,0,1,2,2,207,61,208,65,149,110,24,66,180,108,177,65,219,148,13,192,70,132,58,66,163,58,140,192,12,99,178,192,185,59,255,193,178,213,175,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,110,211,55,195,237,6,56,67,0,0,0,0,0,0,0,0,26,3,255,63,61,246,7,192,171,201,228,192,249,144,215,63,237,199,104,193,128,158,216,64,117,140,155,63,137,120,129,67,108,109,253,191,0,0,0,0,81,64,57,68,103,241,231,64,109,29,152,192,209,43,193,63,93,54,30,65,197,46,92,64,128,27,224,192,6,20,144,191,56,179,130,64,0,0,0,0,43,156,59,196,33,217,100,194,104,77,72,65,15,103,175,191,249,252,12,193,63,117,253,192,233,5,141,65,155,42,25,64,13,88,249,191,0,0,0,0,48,141,122,190,204,150,44,192,36,162,29,193,96,59,39,189,54,202,48,65,151,205,68,64,79,105,55,193,53,120,53,192,77,211,32,192,0,0,0,0,193,207,92,65,239,201,76,65,208,70,82,66,81,63,96,65,48,179,0,194,251,96,242,193,176,51,96,194,153,114,98,66,144,247,64,65,0,0,0,0,219,179,180,63,175,218,119,191,51,71,207,191,245,145,129,63,53,16,244,65,138,208,117,65,138,97,36,66,228,15,32,195,126,91,103,191,0,0,0,0,26,151,170,193,64,105,49,193,46,223,189,193,129,203,168,193,40,91,49,66,4,87,107,65,205,202,37,65,244,36,154,66,240,85,39,193,0,0,0,0,166,96,87,192,114,7,68,191,233,32,214,63,84,249,40,192,45,78,132,64,145,33,253,61,49,43,187,192,244,32,77,67,224,250,71,191,0,0,0,0,103,75,214,190,206,141,252,63,99,15,178,65,80,79,166,190,214,25,146,192,165,29,24,194,18,228,219,193,113,246,235,194,49,115,232,63,0,0,0,0,17,211,124,64,56,252,251,62,25,118,148,193,168,234,94,64,131,157,82,64,217,119,236,65,120,245,240,65,17,69,168,195,49,51,8,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,217,97,66,182,104,101,194,0,0,0,0,0,0,0,0,6,142,142,195,229,54,143,67,0,0,0,0,0,0,0,0,25,224,153,66,217,51,154,194,0,0,0,0,0,0,0,0,142,36,105,194,199,63,110,66,0,0,0,0,0,0,0,0,206,73,250,193,138,69,249,65,0,0,0,0,0,0,0,0,123,173,127,66,20,116,128,194,0,0,0,0,0,0,0,0,49,65,49,64,205,213,107,192,0,0,0,0,0,0,0,0,189,250,179,194,164,98,180,66,0,0,0,0,0,0,0,0,96,182,197,67,155,71,197,195,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,2,185,28,179,73,64,25,141,76,223,26,138,76,222,207,133,76,87,134,164,75,23,127,159,75,166,9,155,75,94,120,170,73,95,221,177,73,93,44,182,73,0,0,0,0,0,0,0,0,0,0,0,0,30,55,120,73,215,98,32,76,7,79,34,76,161,238,36,76,119,151,160,75,119,96,157,75,202,75,154,75,118,89,111,73,133,239,116,73,219,140,120,73,0,0,128,63,0,0,128,63,0,0,128,63,0,0,0,88,1,254,0,2,1,5,48,117,100,0,44,1,112,23,151,7,132,3,197,0,92,4,144,1,64,1,64,1,144,1,48,117,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,48,117,48,117,8,7,8,7,8,7,8,7,8,7,100,0,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,100,0,100,0,255,255,255,255,255,255,255,255,255,255,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,255,255,255,255,255,255,255,255,255,255,112,23,112,23,112,23,112,23,8,7,8,7,8,7,8,7,112,23,112,23,112,23,112,23,112,23,112,23,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,112,23,112,23,112,23,112,23,255,255,255,255,220,5,220,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,220,5,220,5,220,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,44,1,0,5,10,5,0,2,0,10,0,30,0,5,0,5,0,5,0,5,0,5,0,5,0,64,1,100,0,100,0,100,0,200,0,200,0,200,0,64,1,64,1,64,1,10,1,0,0,0,0,233,74,0,0

sensor:
  - platform: bme68x_bsec
    temperature:
      name: "BME680 Temperature"
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    iaq:
      name: "BME680 IAQ"
      id: iaq
    co2_equivalent:
      name: "BME680 CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"

      
text_sensor:
  - platform: template
    name: "BME688 IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Excellent"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Good"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lightly polluted"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Moderately polluted"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Heavily polluted"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Severely polluted"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremely polluted"};
      }
      else {
        return {"error"};
      }`

2024-02-21 08:01 UTC, Boxter91 commented
> Bumping library into v1.7.2502 fix the problem. It looks like they added regression operator which needs additional config values.

Hi, im noob with libraries and i would like to get bme688 work with esphome. Board adafruit qtpy esp32-s2 stemma. 

Can you give me instructions how to modify yaml to get it work?

2024-02-21 08:27 UTC, Szewcson commented
> > Bumping library into v1.7.2502 fix the problem. It looks like they added regression operator which needs additional config values.
> 
> Hi, im noob with libraries and i would like to get bme688 work with esphome. Board adafruit qtpy esp32-s2 stemma.
> 
> Can you give me instructions how to modify yaml to get it work?

Don't know if you can do it via yaml. I checked that PR in my fork and push new commit with changed lib version in 
https://github.com/esphome/esphome/pull/4585/files#diff-b660113b5f83389ce987022bbe31990383ad535f498098d0caecf5d232d45024

You can use my fork or do it yourself.

2024-02-21 09:46 UTC, Boxter91 commented
> > > Bumping library into v1.7.2502 fix the problem. It looks like they added regression operator which needs additional config values.
> > 
> > 
> > Hi, im noob with libraries and i would like to get bme688 work with esphome. Board adafruit qtpy esp32-s2 stemma.
> > Can you give me instructions how to modify yaml to get it work?
> 
> Don't know if you can do it via yaml. I checked that PR in my fork and push new commit with changed lib version in
> 
> [Szewcson@0b519c1](https://github.com/Szewcson/esphome/commit/0b519c19dc6e3cf4c12669825a9bec61a17583ad)
> 
> You can use my fork or do it yourself.

This is first time that i try to do this by my self, without any instrcuctions how to do it. Is there any change that you would give me some simple steps to do it?

 Sorry and thank you for advance.

2024-02-21 15:58 UTC, Boxter91 commented
> I made some updates to the component. It can now be included with "external_components" and uses the current bsec2 library, which should also support multiple sensors.
> 
> ```yaml
> external_components:
>   - source: github://neffs/esphome@bsec2_bme68x
>     components: [ bme68x_bsec ]
> 
> i2c:
>   frequency: 400kHz
> 
> bme68x_bsec:
>   state_save_interval: 30min
>   bsec_configuration: 0,0,4,2,189,1,0,0,0,0,0,0,158,7,0,0,176,0,1,0,0,192,168,71,64,49,119,76,0,0,97,69,0,0,97,69,137,65,0,63,0,0,0,63,0,0,64,63,205,204,204,62,10,0,3,0,0,0,96,64,23,183,209,56,0,0,0,0,0,0,0,0,0,0,0,0,205,204,204,189,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,82,73,157,188,95,41,203,61,118,224,108,63,155,230,125,63,191,14,124,63,0,0,160,65,0,0,32,66,0,0,160,65,0,0,32,66,0,0,32,66,0,0,160,65,0,0,32,66,0,0,160,65,8,0,2,0,236,81,133,66,16,0,3,0,10,215,163,60,10,215,35,59,10,215,35,59,13,0,5,0,0,0,0,0,100,35,41,29,86,88,0,9,0,229,208,34,62,0,0,0,0,0,0,0,0,218,27,156,62,225,11,67,64,0,0,160,64,0,0,0,0,0,0,0,0,94,75,72,189,93,254,159,64,66,62,160,191,0,0,0,0,0,0,0,0,33,31,180,190,138,176,97,64,65,241,99,190,0,0,0,0,0,0,0,0,167,121,71,61,165,189,41,192,184,30,189,64,12,0,10,0,0,0,0,0,0,0,0,0,13,5,11,0,1,2,2,207,61,208,65,149,110,24,66,180,108,177,65,219,148,13,192,70,132,58,66,163,58,140,192,12,99,178,192,185,59,255,193,178,213,175,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,110,211,55,195,237,6,56,67,0,0,0,0,0,0,0,0,26,3,255,63,61,246,7,192,171,201,228,192,249,144,215,63,237,199,104,193,128,158,216,64,117,140,155,63,137,120,129,67,108,109,253,191,0,0,0,0,81,64,57,68,103,241,231,64,109,29,152,192,209,43,193,63,93,54,30,65,197,46,92,64,128,27,224,192,6,20,144,191,56,179,130,64,0,0,0,0,43,156,59,196,33,217,100,194,104,77,72,65,15,103,175,191,249,252,12,193,63,117,253,192,233,5,141,65,155,42,25,64,13,88,249,191,0,0,0,0,48,141,122,190,204,150,44,192,36,162,29,193,96,59,39,189,54,202,48,65,151,205,68,64,79,105,55,193,53,120,53,192,77,211,32,192,0,0,0,0,193,207,92,65,239,201,76,65,208,70,82,66,81,63,96,65,48,179,0,194,251,96,242,193,176,51,96,194,153,114,98,66,144,247,64,65,0,0,0,0,219,179,180,63,175,218,119,191,51,71,207,191,245,145,129,63,53,16,244,65,138,208,117,65,138,97,36,66,228,15,32,195,126,91,103,191,0,0,0,0,26,151,170,193,64,105,49,193,46,223,189,193,129,203,168,193,40,91,49,66,4,87,107,65,205,202,37,65,244,36,154,66,240,85,39,193,0,0,0,0,166,96,87,192,114,7,68,191,233,32,214,63,84,249,40,192,45,78,132,64,145,33,253,61,49,43,187,192,244,32,77,67,224,250,71,191,0,0,0,0,103,75,214,190,206,141,252,63,99,15,178,65,80,79,166,190,214,25,146,192,165,29,24,194,18,228,219,193,113,246,235,194,49,115,232,63,0,0,0,0,17,211,124,64,56,252,251,62,25,118,148,193,168,234,94,64,131,157,82,64,217,119,236,65,120,245,240,65,17,69,168,195,49,51,8,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,217,97,66,182,104,101,194,0,0,0,0,0,0,0,0,6,142,142,195,229,54,143,67,0,0,0,0,0,0,0,0,25,224,153,66,217,51,154,194,0,0,0,0,0,0,0,0,142,36,105,194,199,63,110,66,0,0,0,0,0,0,0,0,206,73,250,193,138,69,249,65,0,0,0,0,0,0,0,0,123,173,127,66,20,116,128,194,0,0,0,0,0,0,0,0,49,65,49,64,205,213,107,192,0,0,0,0,0,0,0,0,189,250,179,194,164,98,180,66,0,0,0,0,0,0,0,0,96,182,197,67,155,71,197,195,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,0,2,185,28,179,73,64,25,141,76,223,26,138,76,222,207,133,76,87,134,164,75,23,127,159,75,166,9,155,75,94,120,170,73,95,221,177,73,93,44,182,73,0,0,0,0,0,0,0,0,0,0,0,0,30,55,120,73,215,98,32,76,7,79,34,76,161,238,36,76,119,151,160,75,119,96,157,75,202,75,154,75,118,89,111,73,133,239,116,73,219,140,120,73,0,0,128,63,0,0,128,63,0,0,128,63,0,0,0,88,1,254,0,2,1,5,48,117,100,0,44,1,112,23,151,7,132,3,197,0,92,4,144,1,64,1,64,1,144,1,48,117,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,48,117,48,117,8,7,8,7,8,7,8,7,8,7,100,0,100,0,100,0,100,0,48,117,48,117,48,117,100,0,100,0,100,0,48,117,48,117,100,0,100,0,255,255,255,255,255,255,255,255,255,255,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,44,1,255,255,255,255,255,255,255,255,255,255,112,23,112,23,112,23,112,23,8,7,8,7,8,7,8,7,112,23,112,23,112,23,112,23,112,23,112,23,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,112,23,112,23,112,23,112,23,255,255,255,255,220,5,220,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,220,5,220,5,220,5,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,44,1,0,5,10,5,0,2,0,10,0,30,0,5,0,5,0,5,0,5,0,5,0,5,0,64,1,100,0,100,0,100,0,200,0,200,0,200,0,64,1,64,1,64,1,10,1,0,0,0,0,233,74,0,0
> sensor:
>   - platform: bme68x_bsec
>     temperature:
>       name: "BME680 Temperature"
>       filters:
>         - median
>     pressure:
>       name: "BME680 Pressure"
>       filters:
>         - median
>     humidity:
>       name: "BME680 Humidity"
>       filters:
>         - median
>     iaq:
>       name: "BME680 IAQ"
>       filters:
>         - median
>     iaq_static:
>       name: "BME680 Static IAQ"
>       filters:
>         - median
>     co2_equivalent:
>       name: "BME680 CO2 Equivalent"
>       filters:
>         - median
>     breath_voc_equivalent:
>       name: "BME680 Breath VOC Equivalent"
>       filters:
>         - median
>     gas_resistance:
>       # Gas resistance in Ω
>       name: "BME680 Gas Resistance"
>       filters:
>         - median
> text_sensor:
>   - platform: bme68x_bsec
>     iaq_accuracy: 
>       # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
>       name: "BME680 IAQ Accuracy"
> ```



> I made some updates to the component. It can now be included with "external_components" and uses the current bsec2 library, which should also support multiple sensors.
> 
> ```yaml
> external_components:
>   - source: github://neffs/esphome@bsec2_bme68x
>     components: [ bme68x_bsec ]
> 
> i2c:
>   frequency: 400kHz
> 
> bme68x_bsec:
>   state_save_interval: 30min
>   bsec_configuration: 0,0,4,2,189,1,0,0,0,0,0,0,158,7,0,0,176,0,1,0,0,192,168,71,64,49,119,76,0,0,97,69,0,0,97,69,137,65,0,63,0,0,0,63,0,0,64,63,205,204,204,62,10,0,3,0,0,0,96,64,23,183,209,56,0,0,0,0,0,0,0,0,0,0,0,0,205,204,204,189,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,128,63,82,73,157,188,95,41,203,61,118,224,108,63,155,230,125,63,191,14,124,63,0,0,160,65,0,0,32,66,0,0,160,65,0,0,32,66,0,0,32,66,0,0,160,65,0,0,32,66,0,0,160,65,8,0,2,0,236,81,133,66,16,0,3,0,10,215,163,60,10,215,35,59,10,215,35,59,13,0,5,0,0,0,0,0,100,35,41,29,86,88,0,9,0,229,208,34,62,0,0,0,0,0,0,0,0,218,27,156,62,225,11,67,64,0,0,160,64,0,0,0,0,0,0,0,0,94,75,72,189,93,254,159,64,66,62,160,191,0,0, [...]

2024-02-21 21:19 UTC, Szewcson commented
If you want to use my fork, just change username in the link for the external component. Of course, if you trust me rhat i don't add anything malicious to that branch. You can also click fork on the esphome repo, clone it to your computer, switch to pr using gh tool, change the lib version, commit and push that change to your fork, and change the link to your own fork.

2024-03-09 08:27 UTC, fran6120 commented
I can confirm that changing the BSEC2 library version from 1.6.2400 to 1.7.2502 from neff's external_component works correctly on an esp32c3 with a BME680, taking the bsec configuration for BME680 from the latest library.

2024-04-22 13:58 UTC, Rudd-O commented
> I made some updates to the component. It can now be included with "external_components" and uses the current bsec2 library, which should also support multiple sensors.

I can confirm that exact YAML works perfectly on my device.  I'm using the Arduino framework on a Freenove ESP32-S3-WROOM.

This really should be pulled into the main codebase, with any blockers resolved ASAP.  The sensor is almost completely pointless without this code.

2024-04-22 14:56 UTC, Szewcson commented
I think before merge config should be handled as before since config vectors are again available in the repo.

2024-04-23 10:00 UTC, tactmaster commented
Hello,

Stil not working for me when I set a config.

[11:57:28][E][bme68x_bsec.sensor:145]: Communication failed (BSEC Status:
0, BME68X Status: 0)
[11:57:29][E][component:082]: Component bme68x_bsec is marked FAILED
Ed Watson
Tel: +46 702053827



On Mon, 22 Apr 2024 at 16:57, Szewcson ***@***.***> wrote:

> I think before merge config should be handled as before since config
> vectors are again available in the repo.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/4585#issuecomment-2069770542>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGBUHOXZB2Z7EKEHAOWVVTY6UQMNAVCNFSM6AAAAAAV7RXSSSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANRZG43TANJUGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-05-14 15:06 UTC, Szewcson commented
@neffs did you plan to add handling configs to this PR and finalize it? Maybe I can help a bit?

2024-05-14 15:16 UTC, neffs commented
> @neffs did you plan to add handling configs to this PR and finalize it? Maybe I can help a bit?

That was the plan. Copying them to esphome config is not practical because it breaks with new bsec releases (and in consequence esphome releases). Since they are now in the repo we can reference them directly. 

Unfortunately I currently don't have the time to finish it. Help is appreciated!

2024-07-01 07:38 UTC, kbx81 commented
I've pushed a number of updates to this branch so hopefully we can push it over the finish line before much longer. I moved the consts in #7023 so the code in this PR can now easily be used/tested by adding:

```yaml
external_components:
  - source: github://pr#4585
    components: [bme68x_bsec]
    refresh: 5min  # or whatever interval you like
```

...to your configuration.

@neffs what else do we need to do to complete this PR, other than docs? Also, thanks for working on this!

2024-07-01 07:41 UTC, kbx81 commented
I should also add that I've got this code running now on several devices of mine with ESP32s and ESP32-C3s, all with BME680s. Quite happy to be able to use the C3s now...it's been time to replace the old 8266s... 😉

2024-07-01 08:03 UTC, Szewcson commented
The main missing thing was usage of config variables like in old bsec implementation instead of embedding binary blobs in config. Now whenthe blobs are in repo it is possible. I want to work on that some time ago, but didn't find the time.

2024-07-03 09:59 UTC, kbx81 commented
I've pushed an update which will pull the BSEC configuration blob at build time. It also renames the component. Here's an example configuration for the base component with these changes:

```yaml
bme68x_bsec_i2c:
  model: bme680  # or "BME688"
  # algorithm_output: classification  # or "regression" -- valid on BME688 only
  operating_age: 28d  # or "4d"
  sample_rate: LP  # or "ULP"
  voltage: 3.3V  # or "1.8V"
```

Based on these variables, the appropriate configuration is selected, pulled and installed when the configuration is built.

Why rename the component like this? To avoid breaking changes later on as we saw with the [BME280](https://github.com/esphome/esphome/pull/5538).

I've only got BME680s here so I haven't been able to test on the BME688. Hopefully everything is working as expected...so far, it seems to be for me!

2024-07-03 11:07 UTC, Szewcson commented
Great work. Is something else stopping us from changing it from draft and starting the review process? @neffs?

2024-07-03 20:18 UTC, kbx81 commented
I'm fine with flagging it as "ready for review" -- I just wanted to make sure the code was in a state where we agree that it's "done" (no new features/major changes are required to satisfy its use case(s)).

If the binary blob handling was really the last bit needed, I'll have a look at it through the reviewing lens and pull docs together, too. I have a bunch of BME680s, so I'm somewhat eager to get it merged now that I see it's so close. 🙂

2024-07-03 20:26 UTC, TCB13 commented
> ```yaml
> bme68x_bsec_i2c:
> ```

This new config breaks the existing ones for a good reason, however the name is kind of misleading there. That code uses the BSEC library / binaries **version 2**, so a more appropriate name would something like `bme68x_bsec2_i2c`.

2024-07-04 03:45 UTC, kbx81 commented
> > ```yaml
> > bme68x_bsec_i2c:
> > ```
> 
> This new config breaks the existing ones for a good reason, however the name is kind of misleading there. That code uses the BSEC library / binaries **version 2**, so a more appropriate name would something like `bme68x_bsec2_i2c`.

@TCB13  yes, I noticed this code seemed to be using "bsec" (as opposed to bsec2) in most cases. I wasn't sure if there was a reason for that or if it's significant enough that it should be called out in the component's name.

Generally, I would be opposed to building a version number into a component name because, what if the library is updated such that it becomes 2.1? 2.2? 3.0? Do we create _another_ new component named (for example) `bme68x_bsec21_i2c`? Do we stick to just keeping the major version in the name? As I was discussing it with Jesse, he asked why we didn't just upgrade in-place the original component -- and I'm not sure I know the answer to that myself, at least as it relates to BSEC.

That said, I think that _this_ component's name is now better since it supports multiple pieces of hardware (BME680 and BME688) and includes `i2c` since it supports only the I2C implementation of this hardware. Having a new component also gives us an opportunity to migrate people to this new component since the old one isn't named correctly, anyway (I'll likely add a pointer in the docs to this component and flag the original one as deprecated).

Regardless, I'd like to know what the consensus is on the name before we merge this. I'm not opposed to the suggestion to change it to include "bsec2", but I'm not sure having an increasing number of "BSEC" components (as time progresses) is a great idea, either. Still, I'm not a BSEC (or sensor) expert in general, so I'd like input from folks here. 😄

2024-07-04 06:40 UTC, Szewcson commented
I'm not sure how @boschsensortec versioning this library but this is BSEC2 v1.7.2502. So I assume that they rather releas BSEC3 and start versioning it with v.major.minor.patch like with BSEC2. So we can create BSEC3 component then.

2024-07-04 08:29 UTC, TCB13 commented
> @TCB13 yes, I noticed this code seemed to be using "bsec" (as opposed to bsec2) in most cases. I wasn't sure if there was a reason for that or if it's significant enough that it should be called out in the component's name.

@kbx81 yeah BSEC 2 was a large rewrite of the library and I suggested the change because only the v2 added support for hardware like ESP32-S2, S3, C3. Their proprietary algorithms also seem to be behave a bit differently and the v2 is more sensor agnostic than the v1 was.

Those are the reasons why I believe it should be abundantly clear this is using v2.

2024-07-04 08:30 UTC, kbx81 commented
Very well, I have updated the component name and such accordingly as well as my comments with examples above. Thank you for the input! 🍻

2024-07-04 08:55 UTC, Szewcson commented
Could you also add @jesserockz  as a reviewer?

2024-07-04 09:08 UTC, kbx81 commented
Done. But anybody can review...and even approve. 😉

2024-07-13 10:36 UTC, trvrnrth commented
Just tried this out as a drop-in replacement for bme680_bsec on an ESP8266 D1 mini with no joy:
```
[11:22:41][C][bme68x_bsec2_i2c.sensor:025]: Setting up BME68X via BSEC2...
[11:22:41][VV][i2c.arduino:176]: 0x76 TX E0B6
[11:22:41][V][bme68x_bsec2_i2c.sensor:460]: Delaying for 10000us
[11:22:41][VV][i2c.arduino:176]: 0x76 TX D0
[11:22:41][VV][i2c.arduino:148]: 0x76 RX 61
[11:22:41][VV][i2c.arduino:176]: 0x76 TX F0
[11:22:41][VV][i2c.arduino:148]: 0x76 RX 00
[11:22:41][VV][i2c.arduino:176]: 0x76 TX 8A
[11:22:41][VV][i2c.arduino:148]: 0x76 RX DC66031F1D92B0D658FFE91FA1FF371E000089EF5EF81E
[11:22:41][VV][i2c.arduino:176]: 0x76 TX E1
[11:22:41][VV][i2c.arduino:148]: 0x76 RX 408629002D14789CB1660DEFD412
[11:22:41][VV][i2c.arduino:176]: 0x76 TX 00
[11:22:41][VV][i2c.arduino:148]: 0x76 RX 2BAA16CB03
[11:22:41]Fatal exception 3(LoadStoreErrorCause):
epc1=0x40202cce, epc2=0x00000000, epc3=0x00000000, excvaddr=0x40270cba, depc=0x00000000
```

[Full log](https://github.com/user-attachments/files/16201833/crash.log)

I haven't tried digging into the problem yet, but has anyone else been able to successfully run on an ESP8266?

2024-07-14 10:33 UTC, Szewcson commented
> Just tried this out as a drop-in replacement for bme680_bsec on an ESP8266 D1 mini with no joy:
> 
> ```
> [11:22:41][C][bme68x_bsec2_i2c.sensor:025]: Setting up BME68X via BSEC2...
> [11:22:41][VV][i2c.arduino:176]: 0x76 TX E0B6
> [11:22:41][V][bme68x_bsec2_i2c.sensor:460]: Delaying for 10000us
> [11:22:41][VV][i2c.arduino:176]: 0x76 TX D0
> [11:22:41][VV][i2c.arduino:148]: 0x76 RX 61
> [11:22:41][VV][i2c.arduino:176]: 0x76 TX F0
> [11:22:41][VV][i2c.arduino:148]: 0x76 RX 00
> [11:22:41][VV][i2c.arduino:176]: 0x76 TX 8A
> [11:22:41][VV][i2c.arduino:148]: 0x76 RX DC66031F1D92B0D658FFE91FA1FF371E000089EF5EF81E
> [11:22:41][VV][i2c.arduino:176]: 0x76 TX E1
> [11:22:41][VV][i2c.arduino:148]: 0x76 RX 408629002D14789CB1660DEFD412
> [11:22:41][VV][i2c.arduino:176]: 0x76 TX 00
> [11:22:41][VV][i2c.arduino:148]: 0x76 RX 2BAA16CB03
> [11:22:41]Fatal exception 3(LoadStoreErrorCause):
> epc1=0x40202cce, epc2=0x00000000, epc3=0x00000000, excvaddr=0x40270cba, depc=0x00000000
> ```
> 
> [Full log](https://github.com/user-attachments/files/16201833/crash.log)
> 
> I haven't tried digging into the problem yet, but has anyone else been able to successfully run on an ESP8266?

` ESP8266 (NOT working, section '.text1' will not fit in region 'iram1_0_seg')`

2024-07-14 12:04 UTC, trvrnrth commented
> ` ESP8266 (NOT working, section '.text1' will not fit in region 'iram1_0_seg')`

I was assuming that was an older compile time issue that had been addressed with later changes/releases. It looks like tests have been added recently for esp8266 and the underlying BSEC2 library does claim support.

2024-07-14 17:05 UTC, Szewcson commented
> > ` ESP8266 (NOT working, section '.text1' will not fit in region 'iram1_0_seg')`
> 
> I was assuming that was an older compile time issue that had been addressed with later changes/releases. It looks like tests have been added recently for esp8266 and the underlying BSEC2 library does claim support.

Ok, it sounds like linking error indeed, so if you can flash the board it was probably something else. Did you try to use EspExceptionDecoder on that stack trace that you have in log? Here is an online version: https://maximeborges.github.io/esp-stacktrace-decoder/

2024-07-14 18:31 UTC, Szewcson commented
@kbx81 did you test it on esp8266? I'm only testing it on my esp32s2. Maybe I will check it tomorrow if it can run on my wemos d1 mini also.

2024-07-15 05:39 UTC, kbx81 commented
I did a quick test with an ESP-01 & custom board I made with a BME680 on it and I'm running into (I believe) the same problem -- it appears to run out of memory (?) when calling `bsec_set_configuration_m()` to give the configuration blob to the BSEC2 library. A cursory search on the 'net reveals that there may be some memory parameters we can fine-tune to get it to work but I'm not sure how that may affect other components. I did some tinkering here tonight but wasn't able to get it working. That said, I'm going to need to focus on other code in the days/weeks ahead so I'm not expecting to have time to chase this.

For now, I'm leaning towards changing the config validation to simply not allow using the '8266 (and add a note to the docs indicating this). In other words, if you want to use this, you need an ESP32 or variant (the C3 is what I'm mostly using and it's a wonderful choice if you want the "modern equivalent"/chip closest to the '8266). Otherwise, if someone else wants to jump in and chase the (memory?) issue on the '8266, please do.

2024-07-16 18:33 UTC, trvrnrth commented
Found the time to do a build and run [an exception](https://github.com/user-attachments/files/16255129/crash.log) through the decoder:
```
    0x4023be0d: __math_divzerof at /workdir/repo/newlib/newlib/libm/common/math_errf.c:82
    0x40237984: _scanf_chars at /workdir/repo/newlib/newlib/libc/stdio/nano-vfscanf_i.c:90
    0x4023b605: __kernel_rem_pio2f at /workdir/repo/newlib/newlib/libm/math/kf_rem_pio2.c:105
    0x4023ac94: __ieee754_powf at /workdir/repo/newlib/newlib/libm/math/ef_pow.c:227
    0x40235859: __localeconv_l at /workdir/repo/newlib/newlib/libc/locale/localeconv.c:51
    0x4023ac94: __ieee754_powf at /workdir/repo/newlib/newlib/libm/math/ef_pow.c:227
    0x4023ac94: __ieee754_powf at /workdir/repo/newlib/newlib/libm/math/ef_pow.c:227
    0x40235859: __localeconv_l at /workdir/repo/newlib/newlib/libc/locale/localeconv.c:51
    0x4023ac94: __ieee754_powf at /workdir/repo/newlib/newlib/libm/math/ef_pow.c:227
    0x4023abd0: __ieee754_powf at /workdir/repo/newlib/newlib/libm/math/ef_pow.c:206
    0x40235988: _Bfree at /workdir/repo/newlib/newlib/libc/stdlib/mprec.c:143
    0x4023ac94: __ieee754_powf at /workdir/repo/newlib/newlib/libm/math/ef_pow.c:227
    0x4023ac94: __ieee754_powf at /workdir/repo/newlib/newlib/libm/math/ef_pow.c:227
    0x4023ae91: __ieee754_rem_pio2f at /workdir/repo/newlib/newlib/libm/math/ef_rem_pio2.c:104
    0x40230ec4: _printf_common at /workdir/repo/newlib/newlib/libc/stdio/nano-vfprintf_i.c:94
    0x40230e6a: _printf_common at /workdir/repo/newlib/newlib/libc/stdio/nano-vfprintf_i.c:88
```

2024-07-21 23:24 UTC, jesserockz requested changes

2024-07-21 23:24 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/__init__.py
> +AUTO_LOAD = ["sensor", "text_sensor"]
Please alter the cpp side to compile safely without sensor and text sensor headers being available using `#ifdefs`

2024-07-21 23:24 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/__init__.py
> +    validate_bme68x,
I would put these outside together
```suggestion
    ).extend(i2c.i2c_device_schema(0x76)),
    cv.only_with_arduino,
    validate_bme68x,
```

2024-07-21 23:24 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/__init__.py
> +        filename = "bsec_selectivity"
```suggestion
    if model == "bme688":
        algo = ALGORITHM_OUTPUT_FILE_NAME[
            config.get(CONF_ALGORITHM_OUTPUT, "classification")
        ]
        filename = "bsec_selectivity"
    else:
        algo = "iaq"
        filename = "bsec_iaq"
```

2024-07-21 23:24 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/__init__.py
> +    bsec2_iaq_config = _download_file(url, path)
Files should be downloaded in the validation stage, and then just read in `to_code`

2024-07-21 23:24 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.h
> +#ifdef USE_BSEC2
This should just wrap everything
```suggestion

namespace esphome {
namespace bme68x_bsec2_i2c {
```

2024-07-21 23:24 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +#ifdef USE_BSEC2
```suggestion
#ifdef USE_BSEC2

namespace esphome {
namespace bme68x_bsec2_i2c {
```

2024-07-21 23:24 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +  BME68xBSEC2I2CComponent::instance = this;
Instead of having a static instance (which will block multiple instances of this component), you can set a pointer to the instance like `this->bme68x_.intf_ptr = (void *) this;` which will be provided to the read/write/delay callbacks as `intfPtr`

2024-07-21 23:24 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +  bsec_get_version_m(&this->bsec_instance_, &version);
`dump_config` shouldnt be doing any device communication, it should have these values cacehd from `setup` and just be dumping them here.

2024-07-22 07:14 UTC, trvrnrth requested changes

2024-07-22 07:14 UTC, trvrnrth commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +        // Queue up an opportunity to save state
I would expect that we'd still want to save state if measuring static IAQ only.

2024-07-22 07:14 UTC, trvrnrth commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +  LOG_SENSOR("  ", "IAQ", this->iaq_sensor_);
If separate static and mobile IAQ sensors are to be retained, then iaq_static_sensor_ is missing here.

2024-07-22 07:14 UTC, trvrnrth commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +        accuracy = outputs[i].accuracy;
This accuracy isn't used anywhere. Previously there was a mode config to switch between static and "mobile" IAQ mode with the iaq and accuracy sensors reflecting the reading for the given mode.

Assuming this value is reliable/useful I would have expected it to be exposed either via separate static iaq accuracy sensors. Or alternatively for the mode switch to be re-introduced such that the same three IAQ/accuracy/text accuracy sensors are used at all times.

If the accuracy reading here is not useful then the docs will need updating to reflect that the accuracy sensors reflect mobile iaq only and we can change the scope of this var and not read it here.

FWIW the mode switch and shared sensors make most sense to me as the sensor cannot be deployed in a static location and also mobile at the same time. But as I originally wrote it that way that probably comes as no surprise.

2024-07-22 07:14 UTC, trvrnrth commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +  BME68xBSEC2I2CComponent::instance = this;
That will be much nicer. This global was always an unpleasant workaround as with the previous BSEC version only a numeric device id was available in the callbacks.

2024-07-22 07:31 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/__init__.py
> +    bsec2_iaq_config = _download_file(url, path)
[`5ea34b1` (#4585)](https://github.com/esphome/esphome/pull/4585/commits/5ea34b1b87c8faaef59cefddcedf0478f2cfda5d)

2024-07-22 07:46 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +  bsec_get_version_m(&this->bsec_instance_, &version);
[`e351165` (#4585)](https://github.com/esphome/esphome/pull/4585/commits/e35116503b90230559d073c9d7584ced74bcd6d3)

2024-07-22 09:07 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/__init__.py
> +AUTO_LOAD = ["sensor", "text_sensor"]
[`b3fb6c2` (#4585)](https://github.com/esphome/esphome/pull/4585/commits/b3fb6c2ee6e7ce25e73df5058feaf60cde27fee6)

2024-07-22 09:35 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +  BME68xBSEC2I2CComponent::instance = this;
Great catch! Done in [`2900c5e` (#4585)](https://github.com/esphome/esphome/pull/4585/commits/2900c5e96d880804f484c97a203708f955a194b5)

2024-07-22 10:02 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +        // Queue up an opportunity to save state
[`a405aea` (#4585)](https://github.com/esphome/esphome/pull/4585/commits/a405aeac0ed24553b3fd8aafe17d404d986ac055)

2024-07-22 16:01 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +        accuracy = outputs[i].accuracy;
Ok, I'm reaching here, but...

Let's say I've got a sensor and I'm riding my bike through the woods. Mobile mode.
Now I stop to have a picnic. Static mode...yes? I haven't studied how Bosch defines which values should be used and when, so please do correct me if I'm misunderstanding. 😇

While I imagine it's not common, I could picture cases where sometimes the sensor is moving and other times it's not. It feels a bit egregious to have to re-flash to switch this mode. Personally, I would lean towards having two sets of sensors available and the user can choose which sensors are used & when. That said, yes, I see we need better consistency here and I'm happy to fix this either way.

2024-07-22 16:57 UTC, trvrnrth commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +        accuracy = outputs[i].accuracy;
I've just been digging out the references that lead me to the decision I made originally and having done so I'm now inclined to agree with you. Here's a decent comment that gives a bit more detail on the [different outputs and their use cases](https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/Explanation-on-static-IAQ-breath-VOC-and-CO2-equivalent/m-p/7536/highlight/true#M483). The main thing I believe being that in actual fact all the values are based on the same underlying calibration/history data and thus will presumably all [share the same accuracy value](https://community.bosch-sensortec.com/t5/MEMS-sensors-forum/Explanation-on-static-IAQ-breath-VOC-and-CO2-equivalent/m-p/7536/highlight/true#M483).

So on that basis the ability to expose the two IAQ sensors separately seems reasonable (with IAQ being a scaled/trimmed variant of sIAQ). I imagine that here we can use the accuracy value from *any* of the outputs being read and trigger state saves accordingly. A number of the virtual sensors [provide accuracy values](https://github.com/boschsensortec/Bosch-BSEC2-Library/blob/master/src/inc/bsec_datatypes.h#L415). I guess what might be nicest here would be to track the maximum accuracy value from all of the sensors and feed that into a queued save state opportunity once all have been read.

2024-07-22 19:17 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/__init__.py
> +    raise cv.Invalid("Unable to download binary configuration blob")
This should simplify a bit
The download content will raise cv.Invalid if it failed
```suggestion
def download_bme68x_blob(config):
    url = _compute_url(config)
    path = _compute_local_file_path(url)

    external_files.download_content(url, path):
    return config
```

2024-07-22 19:33 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/__init__.py
> +    raise cv.Invalid("Unable to download binary configuration blob")
Oh sweet! 😄 Thank you

2024-07-23 00:04 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +        accuracy = outputs[i].accuracy;
> I guess what might be nicest here would be to track the maximum accuracy value from all of the sensors and feed that into a queued save state opportunity once all have been read.

@trvrnrth something like this?: [`7ed61d2` (#4585)](https://github.com/esphome/esphome/pull/4585/commits/7ed61d2beafa0bbd211f066edd394443986e9564)

2024-07-23 07:46 UTC, trvrnrth commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +        accuracy = outputs[i].accuracy;
That looks fairly sane to me. Couple of thoughts:
- It would be clearer to have `uint8_t accuracy` scoped inside each case statement as it is only used within.
- To cover the scenario that only the sIAQ sensor is set up it would probably make more sense to publish the max_accuracy to the accuracy sensors if we have calculated it (ie. outside of the for loop if save_state is true).

2024-07-23 07:57 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +        accuracy = outputs[i].accuracy;
Great points -- will do. 😄

2024-07-23 08:32 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +        accuracy = outputs[i].accuracy;
Alrighty, I think [`8d0ee0e` (#4585)](https://github.com/esphome/esphome/pull/4585/commits/8d0ee0eab92c80354ffc5d7f35c2699045c8f5af) tidies this up nicely -- let me know what you think @trvrnrth. 😄

2024-07-25 03:47 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +  LOG_SENSOR("  ", "IAQ", this->iaq_sensor_);
[`d5a8463` (#4585)](https://github.com/esphome/esphome/pull/4585/commits/d5a8463692ab0085567d6f65b322ee4e9853cc55)

2024-07-25 20:52 UTC, trvrnrth commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +        accuracy = outputs[i].accuracy;
That looks good to me. I suspect that strictly speaking it might also make sense to save state if only some of the other derived sensors (and not IAQ/sIAQ) are enabled. But that's not something the existing component does properly either if it is the case and certainly shouldn't hold up merging this.

2024-07-25 20:54 UTC, trvrnrth approved these changes
I don't have the hardware to test with at the moment (my test sensor is hooked up to an ESP8266) but this looks good to me.

2024-08-07 04:51 UTC, jesserockz requested changes

2024-08-07 04:51 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +    return;
Please put some sort of error log message here so we know why/when it failed.
We have had users create issues, but because the components dont log anything, we have no idea **why** it was marked failed.

Same for the any place that calls `mark_failed()`

2024-08-07 07:27 UTC, kbx81 commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +    return;
[`2dc0711` (#4585)](https://github.com/esphome/esphome/pull/4585/commits/2dc0711623f4623518622e6c71b3409eceeb2e74)

2024-08-07 08:09 UTC, trvrnrth requested changes

2024-08-07 08:09 UTC, trvrnrth commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +    ESP_LOGE(TAG, "bme68x_init failed: status %d", this->bsec_status_);
```suggestion
    ESP_LOGE(TAG, "bme68x_init failed: status %d", this->bme68x_status_);
```

2024-08-07 08:09 UTC, trvrnrth commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +    ESP_LOGE(TAG, "bme68x_init failed: status %d", this->bsec_status_);
However, I'm not entirely sure we actually need these new logs at all as the statuses are logged out in dump_config. Perhaps the extra context of the action is useful? Should they be debug/verbose level in that case?

2024-08-07 09:34 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/bme68x_bsec2_i2c.cpp
> +    ESP_LOGE(TAG, "bme68x_init failed: status %d", this->bsec_status_);
The problem with the dump config line is that the same status is used in 3 places and it doesn't help to know where the error happens/which function call returned the error.
I don't think they should be changed to anything but error as they are errors and they should be prominent when they happen.

2024-08-08 03:11 UTC, jesserockz approved these changes

2024-08-08 04:48 UTC, jesserockz requested changes
Pending moving the `sensor` and `text_sensor` to `bme_68x_bsec2` (not `i2c` specific) so they can be re-used by a future SPI implementation

2024-08-09 03:31 UTC, kbx81 commented
In [`c599bbb` (#4585)](https://github.com/esphome/esphome/pull/4585/commits/c599bbbd00631b1742c91a9114c0b68fb017ad47), I broke apart a bunch of stuff. It's not a massive change, but it'll make it significantly easier if anybody wants to implement SPI for this hardware in the future.

2024-08-11 07:33 UTC, trvrnrth commented
> Just tried this out as a drop-in replacement for bme680_bsec on an ESP8266 D1 mini with no joy.

To follow up on this I spent some time yesterday to look at this properly. It would seem that it's running out of memory internally in the BSEC library when setting the config as previously posited. As already discussed an ESP32 would be more appropriate but I have got up and running on a ESP8266 D1 mini by using `16KB cache + 48KB IRAM and 2nd Heap (shared)` as follows:
```
esphome:
  platformio_options:
    build_flags:
      - -DPIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48_SECHEAP_SHARED
```

2024-08-12 03:43 UTC, jesserockz submitted a review, later dismissed

2024-08-12 03:43 UTC, jesserockz commented on esphome/components/bme68x_bsec2/sensor.py
> +            cg.add(getattr(hub, f"set_{key}_sample_rate")(conf[CONF_SAMPLE_RATE]))
```suggestion
        if sample_rate := conf.get(CONF_SAMPLE_RATE):
            cg.add(getattr(hub, f"set_{key}_sample_rate")(sample_rate))
```

2024-08-12 03:43 UTC, jesserockz commented on esphome/components/bme68x_bsec2_i2c/__init__.py
> +)
```suggestion
CONFIG_SCHEMA = CONFIG_SCHEMA_BASE.extend(
    cv.Schema({cv.GenerateID(): cv.declare_id(BME68xBSEC2I2CComponent)})
).extend(i2c.i2c_device_schema(0x76))
```

2024-08-12 03:46 UTC, kbx81 commented on esphome/components/bme68x_bsec2/sensor.py
> +            cg.add(getattr(hub, f"set_{key}_sample_rate")(conf[CONF_SAMPLE_RATE]))
More walrus! 🦭🤦🏻‍♂️ Need to up my walrus game 😅

2024-08-12 03:50 UTC, jesserockz approved these changes

2024-08-12 03:57 UTC, kbx81 commented
> > Just tried this out as a drop-in replacement for bme680_bsec on an ESP8266 D1 mini with no joy.
> 
> To follow up on this I spent some time yesterday to look at this properly. It would seem that it's running out of memory internally in the BSEC library when setting the config as previously posited. As already discussed an ESP32 would be more appropriate but I have got up and running on a ESP8266 D1 mini by using `16KB cache + 48KB IRAM and 2nd Heap (shared)` as follows:
> 
> ```
> esphome:
>   platformio_options:
>     build_flags:
>       - -DPIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48_SECHEAP_SHARED
> ```

Nice -- thanks for working this out @trvrnrth! 🍻

2024-08-12 04:14 UTC, merged