Updating the touchscreen interface structure
OttoWinter/esphomeyaml pull request #4596
Opened 2023-03-20 16:56 UTC by nielsnl68

# What does this implement/fix?

**This breaking PR implements a consistent solution for the current available touchscreen drivers.**
- A `binary sensor` and `on_touch` event will now be triggered once until all touches are released. 
- Two new events are added:
   - `on_update` will be triggered when a touched position moved around or that an extra touch has been detected.
   - `on_release` will be triggered when all touches are release from the touchscreen.
- The raw touch position is added to the `on_touch` `touch` argument.
- The touchscreen drivers will from now on get the raw touch data on request of main touchscreen component.
  - the touchscreen component will convert the raw data and determine which triggers and events will be called.
 
**NOTE: This is a PR that will break all existing touchscreen components not in the esphome repository,** 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3405
## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
touchscreen:
  - platform: xpt2046
    id: touch_1
    display: my_display
    ...
  ```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-20 19:04 UTC, jesserockz commented on esphome/components/touchscreen/touchscreen.h
> +  void set_dispay_dimension(uint16_t width, u_int16_t height) {
```suggestion
  void set_display_dimension(uint16_t width, u_int16_t height) {
```

2023-03-20 19:07 UTC, jesserockz commented on esphome/components/touchscreen/touchscreen.h
> +  uint16_t get_rotation_() {
Why not return the enum type?
 ```suggestion
  TouchRotation get_rotation_() {
```

2023-03-20 20:53 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.h
> +  uint16_t get_rotation_() {
thanks, you are right, i missed this. I was to busy try it to work without the need of a display

2023-05-11 16:34 UTC, jesserockz requested changes

2023-05-11 16:34 UTC, jesserockz commented on esphome/components/touchscreen/touchscreen.h
> +  uint16_t display_height_{320};
The config validation should enforce at least either `display` or `dimensions`+`rotation` to be supplied and remove these fallback values from this file.

2023-05-12 22:18 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.h
> +  uint16_t display_height_{320};
Good point.
I am try to figure out how i should do that correctly. I could not find a suitable function in `config_validation` to do what you suggest, i think.

2023-09-11 16:43 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.h
> +  uint16_t display_height_{320};
Added this check now

2023-11-02 02:15 UTC, jesserockz commented on esphome/components/touchscreen/__init__.py
>  CODEOWNERS = ["@jesserockz"]
Maybe add yourself here now that you are making many changes?

2023-11-09 15:49 UTC, nielsnl68 commented on esphome/components/touchscreen/__init__.py
>  CODEOWNERS = ["@jesserockz"]
done

2023-11-27 02:48 UTC, jesserockz commented on esphome/components/touchscreen/touchscreen.h
> +// std::vector<Style> styles_{};
Commented code?

2023-11-27 02:48 UTC, jesserockz commented on esphome/components/touchscreen/touchscreen.h
> +  /* return true to update first touch position */
What does this comment refer to exactly?
There are no bool returns here?

2023-11-27 03:23 UTC, jesserockz requested changes

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/touchscreen/touchscreen.h
> +  uint16_t get_height_() { return display_->get_height(); }
```suggestion
  uint16_t get_height_() { return this->display_->get_height(); }
```

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/touchscreen/touchscreen.h
> +  int16_t x_raw_min_{0}, x_raw_max_{0}, y_raw_min_{0}, y_raw_max_{0};
Do these need to be signed values?

```suggestion
  uint16_t x_raw_min_{0}, x_raw_max_{0}, y_raw_min_{0}, y_raw_max_{0};
```

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/touchscreen/touchscreen.cpp
> +  }
This could be replace by `clamp` and `remap` from `helpers.h` =)

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/touchscreen/binary_sensor/touchscreen_binary_sensor.h
> +#ifdef USE_DISPLAY
Since display is currently required by touchscreen, we can safely assume it is there.

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/touchscreen/binary_sensor/touchscreen_binary_sensor.cpp
> +#ifdef USE_DISPLAY
Same here

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/touchscreen/__init__.py
> +        cv.Required(CONF_DISPLAY): cv.use_id(display.DisplayBuffer),
Lets not break the config here until we are making changes for it to become optional
```suggestion
        cv.GenerateID(CONF_DISPLAY): cv.use_id(display.DisplayBuffer),
```

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/touchscreen/__init__.py
> +        cv.Optional(CONF_SWAP_X_Y, default=False): cv.boolean,
These are not used?

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/lilygo_t5_47/touchscreen/lilygo_t5_47_touchscreen.cpp
> +  for (int i = 0; i < point; i++) {
```suggestion
  for (uint8_t i = 0; i < point; i++) {
```

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/lilygo_t5_47/touchscreen/lilygo_t5_47_touchscreen.cpp
> +    //      tp.state = 0x07;
If its not used, lets just delete it
```suggestion
```

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/xpt2046/touchscreen/__init__.py
> +        raise cv.Invalid("Calibration y values missing")
They cant be missing since they have a default value

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
> +  read_adc_(0xD0);  // ADC powerdown, enable PENIRQ pin
I know you probably just moved this file for the most part, but it shows up as an entirely new file on github due to the changes, so it may as well be cleaned up to standards =)

```suggestion
  this->spi_setup();
  this->read_adc_(0xD0);  // ADC powerdown, enable PENIRQ pin
```

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
> +  // ESP_LOGCONFIG(TAG, "  Report interval: %u", this->report_millis_);
```suggestion
```

2023-11-27 03:23 UTC, jesserockz commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
> +  int16_t da, db, dc;                                                      // NOLINT
Maybe name these `delta_a` etc instead of disabling lint =)

2023-11-27 03:23 UTC, jesserockz commented on tests/test8.yaml
> +    display: displ8
Should not be required if reverted to `GenerateID`

2023-11-27 03:29 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.h
> +  int16_t x_raw_min_{0}, x_raw_max_{0}, y_raw_min_{0}, y_raw_max_{0};
No, i want to allow negative values as well.

2023-11-27 04:06 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
> +  }
Good idea, need to dig in to this a bit more. Can i do that for an upcoming fix?

2023-11-28 02:23 UTC, clydebarrow requested changes

2023-11-28 02:23 UTC, clydebarrow commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
> +  if (touch_state  == 0)
```suggestion
  if ((touch_state & 0x80) == 0)
```

2023-11-28 02:23 UTC, clydebarrow commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
>    uint8_t data[MAX_TOUCHES + 1][8];  // 8 bytes each for each point, plus extra space for the key byte
```suggestion
  uint8_t data[MAX_TOUCHES + 1][8];  // 8 for each point, plus extra space for the keypress info
```

2023-11-28 02:23 UTC, clydebarrow commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
>    uint8_t data[MAX_TOUCHES + 1][8];  // 8 bytes each for each point, plus extra space for the key byte
CI objects to "byte" appearing even in comments!

2023-11-28 02:23 UTC, clydebarrow commented on esphome/components/ektf2232/touchscreen/ektf2232.cpp
> +    this->set_raw_touch_posistion_(i, x_raw, y_raw);
should be `set_raw_touch_position_`

2023-11-28 02:23 UTC, clydebarrow commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
>    touchscreen::TouchPoint tp;
Is this still needed?

2023-11-28 02:40 UTC, jesserockz commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
>    uint8_t data[MAX_TOUCHES + 1][8];  // 8 bytes each for each point, plus extra space for the key byte
The actual issue is the regex that sees it like this:
```c++
  byte

  err = this->write(GET_TOUCH_STATE, sizeof(GET_TOUCH_STATE), false);
```

2023-11-28 02:45 UTC, clydebarrow commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
>    uint8_t data[MAX_TOUCHES + 1][8];  // 8 bytes each for each point, plus extra space for the key byte
Ah regexes - we can't live without them but don't we hate them? 
So the regex should exclude comment lines.

2023-11-28 02:49 UTC, jesserockz commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
>    uint8_t data[MAX_TOUCHES + 1][8];  // 8 bytes each for each point, plus extra space for the key byte
https://github.com/esphome/esphome/pull/5851

2023-11-28 02:50 UTC, jesserockz commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
>    touchscreen::TouchPoint tp;
Nope 
```suggestion
```

2023-11-28 03:44 UTC, jesserockz requested changes, later dismissed

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/ft63x6/ft63x6.cpp
> +  set_raw_touch_position_(touch_id, x, y);
```suggestion
  uint8_t touch_id = this->read_touch_id_(FT63X6_ADDR_TOUCH1_ID);  // id1 = 0 or 1
  int16_t x = this->read_touch_coordinate_(FT63X6_ADDR_TOUCH1_X);
  int16_t y = this->read_touch_coordinate_(FT63X6_ADDR_TOUCH1_Y);
  this->set_raw_touch_position_(touch_id, x, y);
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/ft63x6/ft63x6.cpp
> +    set_raw_touch_position_(touch_id, x, y);
```suggestion
    touch_id = this->read_touch_id_(FT63X6_ADDR_TOUCH2_ID);  // id2 = 0 or 1(~id1 & 0x01)
    x = this->read_touch_coordinate_(FT63X6_ADDR_TOUCH2_X);
    y = this->read_touch_coordinate_(FT63X6_ADDR_TOUCH2_Y);
    this->set_raw_touch_position_(touch_id, x, y);
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/ft63x6/ft63x6.cpp
> +uint8_t FT63X6Touchscreen::read_touch_count_() { return read_byte_(FT63X6_ADDR_TOUCH_COUNT); }
```suggestion
uint8_t FT63X6Touchscreen::read_touch_count_() { return this->read_byte_(FT63X6_ADDR_TOUCH_COUNT); }
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/ft63x6/ft63x6.cpp
> +  read_buf[1] = read_byte_(coordinate + 1);
```suggestion
  read_buf[0] = this->read_byte_(coordinate);
  read_buf[1] = this->read_byte_(coordinate + 1);
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/ft63x6/ft63x6.cpp
> +uint8_t FT63X6Touchscreen::read_touch_id_(uint8_t id_address) { return read_byte_(id_address) >> 4; }
```suggestion
uint8_t FT63X6Touchscreen::read_touch_id_(uint8_t id_address) { return this->read_byte_(id_address) >> 4; }
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/ft63x6/touchscreen.py
> +        interrupt_pin = await cg.gpio_pin_expression(config[CONF_INTERRUPT_PIN])
```suggestion
    if interrupt_pin_config := config.get(CONF_INTERRUPT_PIN):
        interrupt_pin = await cg.gpio_pin_expression(interrupt_pin_config)
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/ft63x6/touchscreen.py
> +        reset_pin = await cg.gpio_pin_expression(config[CONF_RESET_PIN])
```suggestion
    if reset_pin_config := config.get(CONF_RESET_PIN):
        reset_pin = await cg.gpio_pin_expression(reset_pin_config)
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
> +    set_raw_touch_position_(id, x, y);
```suggestion
    this->set_raw_touch_position_(id, x, y);
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/touchscreen/__init__.py
> +).extend(cv.polling_component_schema("50ms"))
If users dont need to be able to change this time and it is going to always poll at 50ms, it shouldnt be a PollingComponent, but should internally use `set_interval` and run the callback itself so users do not have the opportunity to change it.

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/touchscreen/binary_sensor/touchscreen_binary_sensor.cpp
> +  if ((this->page_ != nullptr) && (this->parent_->get_display() != nullptr)) {
The display cant be null with these changes.
```suggestion

  if (this->page_ != nullptr) {
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
> +    data[4] = read_adc_(0x91 /* Y */);
```suggestion
    data[0] = this->read_adc_(0x91 /* Y */);
    data[1] = this->read_adc_(0xD1 /* X */);  // make 3 x-y measurements
    data[2] = this->read_adc_(0x91 /* Y */);
    data[3] = this->read_adc_(0xD1 /* X */);
    data[4] = this->read_adc_(0x91 /* Y */);
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
> +  int16_t touch_pressure_2 = read_adc_(0xC1 /* touch_pressure_2 */);
```suggestion
  int16_t touch_pressure_1 = this->read_adc_(0xB1 /* touch_pressure_1 */);
  int16_t touch_pressure_2 = this->read_adc_(0xC1 /* touch_pressure_2 */);
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
> +  data[5] = read_adc_(0xD0 /* X */);  // Last X touch power down
```suggestion
  data[5] = this->read_adc_(0xD0 /* X */);  // Last X touch power down
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
> +    set_raw_touch_position_(0, x_raw, y_raw, z_raw);
```suggestion
    this->set_raw_touch_position_(0, x_raw, y_raw, z_raw);
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
> +  write_byte(ctrl);
```suggestion
  this->write_byte(ctrl);
```

2023-11-28 03:44 UTC, jesserockz commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
> +  data[1] = read_byte();
```suggestion
  data[0] = this->read_byte();
  data[1] = this->read_byte();
```

2023-11-28 13:07 UTC, nielsnl68 commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
> +  if (touch_state  == 0)
@Clyde, why would you want that change back, In both case (touch_state & 0x80) and (touch_state & 0x07) would mean a return without changes.
Maybe should change it into:
```suggestion
  if ((touch_state & 0x87) == 0)
```

2023-11-28 13:11 UTC, nielsnl68 commented on esphome/components/ektf2232/touchscreen/ektf2232.cpp
> +    this->set_raw_touch_posistion_(i, x_raw, y_raw);
not sure where that "**S**" was coming from. :D

2023-11-28 20:26 UTC, clydebarrow commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
> +  if (touch_state  == 0)
Bit 7 must be set for the data to be valid. The lower 3 bits encode the number of touches, which can range from 0-5. Your change would mean that an invalid byte of e.g. 0x01 would be incorrectly processed as a single touch. The code as I had it was based on reading the datasheet and actual testing. The check for the most significant bit is required, and should be reinstated.

2023-11-28 21:24 UTC, nielsnl68 commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
> +  if (touch_state  == 0)
okay i understand it now :D thanks for explaining

2023-12-05 20:29 UTC, clydebarrow commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
> +      err = this->read(&data, 1);
```suggestion
      err = this->read(&data, sizeof(data));
```

2023-12-05 20:33 UTC, clydebarrow commented on esphome/components/gt911/touchscreen/gt911_touchscreen.cpp
> +        this->y_raw_max_ = encode_uint16(data[2], data[3]);
```suggestion
        this->x_raw_max_ = encode_uint16(data[1], data[0]);
        this->y_raw_max_ = encode_uint16(data[3], data[2]);
```

2023-12-08 04:45 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
> +    tp.state = 1;
It would make the code easier to read if these states were enum constants rather than plain numbers. Also a comment with a state machine description showing when the state changes would be helpful for the future.

2023-12-08 04:49 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
> +  tp.y = (uint16_t) ((int) y * this->get_height_() / 0xfff);
```suggestion
  tp.x = (uint16_t) ((int) x * (this->get_width_() - 1) / 0xfff);
  tp.y = (uint16_t) ((int) y * (this->get_height_() - 1) / 0xfff);
```

2023-12-08 04:55 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
> +  tp.y = (uint16_t) ((int) y * this->get_height_() / 0xfff);
Or alternatively, since the maximum value after normalisation will be 0xFFF:

Either way the resulting value should never == the width (or height) since the pixels are numbered 0:width-1.


```
tp.x = (uint16_t) ((int) x * this->get_width_() / 0x1000);
tp.y = (uint16_t) ((int) y * this->get_height_() / 0x1000);
```

2023-12-08 12:45 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
> +  tp.y = (uint16_t) ((int) y * this->get_height_() / 0xfff);
i like the later one better. One (two) calculation step less for the esp to calculated.

2023-12-10 09:48 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.h
> +      }
```suggestion
      return this->touches_.begin().second;
```

2023-12-12 16:03 UTC, nielsnl68 commented on esphome/components/touchscreen/__init__.py
> +).extend(cv.polling_component_schema("50ms"))
the idea of using the polling component is that people can use it when they have no interrupt pin enabled.

2023-12-12 20:38 UTC, clydebarrow approved these changes

2023-12-12 20:38 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.h
> +  optional<TouchPoints_t> get_touches() {
Can't this one just return an empty vector if there are no touches, rather than wrapping it in an `optional`?

2023-12-12 20:38 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.h
> +struct TouchscreenInterupt {
Should be `TouchScreenInterrupt`

2023-12-12 20:38 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.h
> +static const uint8_t STATE_RELAESED = 0x00;
Should be `STATE_RELEASED`

2023-12-12 22:56 UTC, merged