add pmwcs3 component
OttoWinter/esphomeyaml pull request #4624
Opened 2023-03-27 08:03 UTC by SeByDocKy

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-28 09:10 UTC, jesserockz requested changes

2023-03-28 09:10 UTC, jesserockz commented on esphome/components/pmwcs3/pmwcs3.cpp
Please remove the comments with `NOLINT delay`

2023-03-28 09:10 UTC, jesserockz commented on esphome/components/pmwcs3/pmwcs3.cpp
> +  ESP_LOGW(TAG, "Air calibration finished");
If this process takes 300s, you should set a flag that stops the component from trying to read data until it is done.

You can use `set_timeout` to run code 300s later to set the flag back to false.

2023-03-28 09:10 UTC, jesserockz commented on esphome/components/pmwcs3/pmwcs3.h
> +static const uint8_t PMWCS3_REG_RT = 0x0D;
These can be moved into the cpp file

2023-03-28 09:26 UTC, SeByDocKy commented on esphome/components/pmwcs3/pmwcs3.cpp
> +  ESP_LOGW(TAG, "Air calibration finished");
> set_timeout

In fact if the read_register is not written (as in the beginning of the read_data() method), no new data are avalable on the I2C bus. Anyway I will look to set_timeout method :)

2023-04-06 17:05 UTC, sebcaps commented on esphome/components/pmwcs3/pmwcs3.cpp
> +  LOG_SENSOR("  ", "temperatue", this->temperature_sensor_);
small typo :-) temperatuRe

2023-04-06 17:09 UTC, SeByDocKy commented on esphome/components/pmwcs3/pmwcs3.cpp
> +  LOG_SENSOR("  ", "temperatue", this->temperature_sensor_);
Dammned you see everything :)

2023-04-07 17:32 UTC, sebcaps commented on esphome/components/pmwcs3/pmwcs3.cpp
> +void PMWCS3Component::change_i2c_address(uint8_t newaddress) {
can't see how / when it's called ?
For future use ?

2023-04-07 17:32 UTC, sebcaps commented on esphome/components/pmwcs3/pmwcs3.cpp
> +void PMWCS3Component::set_air_calibration() {
idem : how to use it ?
For a future use ?

2023-04-07 17:32 UTC, sebcaps commented on esphome/components/pmwcs3/pmwcs3.cpp
> +void PMWCS3Component::set_water_calibration() {
For future use ?

2023-04-07 17:35 UTC, sebcaps commented
@SeByDocKy you requested review I did it ;-).
Initally  had a look to this PR since I know your youtube channel, permit myself to let a comment.
Can't test it, since I don't have this device (yet), but may give a help to use the three unused function.
Looking forward to see your next video.

2023-04-07 17:58 UTC, SeByDocKy commented
> @SeByDocKy you requested review I did it ;-). Initally had a look to this PR since I know your youtube channel and permit myself to let a comment. Can't test it, since I don't have this device (yet), but may give a help to use the three unused function. Looking forward to see your next video.

Yes as you noticed, there are 3 methods not documented coz even in the original arduino lib there are no example how to use them. Anyway I more or less understood how. My proposal was(is) to use these methods in dedicaced yaml model : changing the I2C adress, calibrating air and water measures. To proceed, I propose to definie a lambda in the on_boot section and run these method like

````
esphome:
  name: ${name}
  
  # on_boot:
  #   priority: -100
  #   then:

  #     ######### Uncomment the next lamnda section to change I2C address, then replace the new I2C address in the sensor part ########

  #     - lambda: |-
  #         esphome::pmwcs3::PMWCS3Component *sen =  ${name}_pmwc3;
  #         sen->change_i2c_address(0x65);

  #     #########  Uncomment the next lamnda section to perform the air/dry soil calibration   ##########
      
  #     - lambda: |-
  #         esphome::pmwcs3::PMWCS3Component *sen =  ${name}_pmwc3;
  #         sen->set_air_calibration();

  #     #########  Uncomment the next lamnda section to perform the water/humid soil calibration   ##########
      
  #     - lambda: |-
  #         esphome::pmwcs3::PMWCS3Component *sen =  ${name}_pmwc3;
  #         sen->set_water_calibration();````

2023-04-08 16:50 UTC, sebcaps commented
Hello,
Definitely device doc is very light, but arduino library quite explicit. 
From a style perspective, it's a pity to declare functions not being able to use them. If usage of these lambda in boot was discouraged I would stick to the advice.
Setting i2c adress via code is somehow strange, on other devices I know they are either static or set by hardware. 
The point here is egg & chicken problem : you first need to use default adress ```0x63``` to be able to communicate with the device, execute the command and then modify esphome config to use the new address.
Can't see how to set a new adress without updating i2c component adress and make it working. It would require some tests to confirm what is the exact 'behavior'.

I would suggest you, either to remove unused fucntions or  provide  them as action  (ex [here](https://esphome.io/components/sensor/mhz19.html?highlight=mhz19#mhz19-calibrate-zero-action).

2023-04-23 20:38 UTC, sebcaps approved these changes

2023-05-01 21:51 UTC, jesserockz requested changes

2023-05-01 21:51 UTC, jesserockz commented on esphome/components/pmwcs3/sensor.py
> +)
```suggestion
PMWCS3_NEW_I2C_ADDRESS_SCHEMA = cv.maybe_simple_value(
    {
        cv.GenerateID(): cv.use_id(PMWCS3Component),
        cv.Required(CONF_ADDRESS): cv.templatable(cv.i2c_address),
    },
    key=CONF_ADDRESS,
)
```

2023-05-01 21:51 UTC, jesserockz commented on esphome/components/pmwcs3/sensor.py
> +    "pmwcs3.newi2caddress",
Dont try make things shorter, its just harder to read
```suggestion
    "pmwcs3.new_i2c_address",
```

2023-05-01 21:51 UTC, jesserockz commented on esphome/components/pmwcs3/sensor.py
> +    PMWCS3NEWI2CADDRESS_SCHEMA,
```suggestion
    PMWCS3_NEW_I2C_ADDRESS_SCHEMA,
```

2023-05-01 21:51 UTC, jesserockz commented on esphome/components/pmwcs3/sensor.py
> +    cg.add(var.set_newaddress(newaddress_))
```suggestion
    address = await cg.templatable(config[CONF_ADDRESS], args, int)
    cg.add(var.set_new_address(address))
```

2023-05-01 21:51 UTC, jesserockz commented on esphome/components/pmwcs3/sensor.py
> +            cv.Optional(CONF_ADDRESS): cv.i2c_address,
Not required as its included with `i2c.i2c_device_schema()`
```suggestion
```

2023-05-01 21:51 UTC, jesserockz commented on esphome/components/pmwcs3/pmwcs3.h
> +  void play(Ts... x) override { this->parent_->new_i2c_address(this->newaddress_.value(x...)); }
```suggestion
  TEMPLATABLE_VALUE(int, new_address)

  void play(Ts... x) override { this->parent_->new_i2c_address(this->new_address_.value(x...)); }
```

2023-05-01 21:51 UTC, jesserockz commented on esphome/components/pmwcs3/pmwcs3.h
> +  void set_newaddress_(uint8_t newaddress);
Not used
```suggestion
```

2023-05-01 21:51 UTC, jesserockz commented on esphome/components/pmwcs3/pmwcs3.cpp
> +}
```suggestion
void PMWCS3Component::new_i2c_address(uint8_t address) {
  if (!this->write_byte(PMWCS3_SET_I2C_ADDRESS, address)) {
    this->status_set_warning();
    ESP_LOGW(TAG, "couldn't write the new I2C address %d", address);
    return;
  }
  this->set_i2c_address(address);  // Allows device to continue working until new firmware is written with new address.
  ESP_LOGVV(TAG, "changed I2C address to %d", address);
  this->status_clear_warning();
}
```

2023-05-01 21:51 UTC, jesserockz commented on esphome/components/pmwcs3/sensor.py
> +CONF_NEWADDRESS = "newaddress"
```suggestion
```

2023-08-14 18:57 UTC, jesserockz submitted a review, later dismissed

2023-08-14 19:03 UTC, jesserockz approved these changes

2023-08-17 20:03 UTC, merged