add bluetooth mac address in dump_config()
OttoWinter/esphomeyaml pull request #4628
Opened 2023-03-28 09:06 UTC by felixlungu

# What does this implement/fix?

Whenever I setup a new device with esp32_ble/esp32_ble_server i have no  info about its own mac_address until i setup another esp32 device with esp32_ble_tracker to figure out what's my mac_address.

I added just a few line to get and print the configure mac_address in the dump_config() of the esp32_ble component.
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-03-28 09:19 UTC, jesserockz requested changes

2023-03-28 09:19 UTC, jesserockz commented on esphome/components/esp32_ble/ble.cpp
> +    ESP_LOGCONFIG(TAG, "ESP32 BLE: bluetooth stack is not enabled");
The `esp32_ble` component enables the stack so I don't think this code will ever run.

2023-03-28 09:19 UTC, jesserockz commented on esphome/components/esp32_ble/ble.cpp
> +                  mac_address[0],mac_address[1],mac_address[2],mac_address[3],mac_address[4],mac_address[5]);
Please format this to two log lines like other components do

2023-03-28 09:29 UTC, felixlungu commented on esphome/components/esp32_ble/ble.cpp
> +    ESP_LOGCONFIG(TAG, "ESP32 BLE: bluetooth stack is not enabled");
I not very familiar with the formatting since it is my first time digging into the code.
Can you point me to example and i'll follow it.
Thanks!

2023-03-28 09:33 UTC, felixlungu commented on esphome/components/esp32_ble/ble.cpp
> +    ESP_LOGCONFIG(TAG, "ESP32 BLE: bluetooth stack is not enabled");
in the doc here [https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_bt_device.html](url) it says it can return NULL so i did not want to bang on the bytes at the begining of the firmware.

2023-03-28 10:14 UTC, felixlungu commented on esphome/components/esp32_ble/ble.cpp
> +    ESP_LOGCONFIG(TAG, "ESP32 BLE: bluetooth stack is not enabled");
is this acceptable?

2023-03-30 01:11 UTC, jesserockz commented on esphome/components/esp32_ble/ble.cpp
> +    ESP_LOGCONFIG(TAG, "ESP32 BLE: bluetooth stack is not enabled");
Ok I see, this code is fine then.

2023-03-30 01:12 UTC, jesserockz approved these changes

2023-03-30 01:34 UTC, merged