Remote receiver improvements
OttoWinter/esphomeyaml pull request #4642
Opened 2023-04-01 09:53 UTC by Mat931

# What does this implement/fix?

- Allow setting the tolerance in microseconds (Required for some protocols)
- ESP32: Add a software-based glitch filter (Reason: The filter of the RMT peripheral doesn't filter out all glitches)
- ESP32: Prevent overflow of filter_ticks_thresh and idle_threshold
- ESP32: Allow changing the clock divider
- Change filter to uint32_t (see https://github.com/esphome/esphome/pull/4244)
- Add more Config Validation

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
remote_receiver:
  pin: GPIO25
  filter: 8us
  tolerance: 15us
  idle: 1500us
  clock_divider: 160
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-20 05:50 UTC, jesserockz requested changes

2023-12-20 05:50 UTC, jesserockz commented on esphome/components/remote_base/remote_base.h
> +                                                    : int32_t(100 - this->tolerance_) * length / 100U;
Please change these to regular if/else instead of ternary

2023-12-20 05:50 UTC, jesserockz commented on esphome/components/remote_base/remote_base.h
> +    tolerance_mode_ = tolerance_mode;
```suggestion
    this->tolerance_ = tolerance;
    this->tolerance_mode_ = tolerance_mode;
```

2023-12-20 22:29 UTC, kbx81 commented on esphome/components/remote_receiver/remote_receiver_esp8266.cpp
> +  ESP_LOGCONFIG(TAG, "  Tolerance: %u%s", this->tolerance_,
Please make sure this builds & runs with IDF 5:
```yaml
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: 5.0.2
    platform_version: 6.3.2
```

2023-12-20 23:08 UTC, Mat931 commented on esphome/components/remote_receiver/remote_receiver_esp8266.cpp
> +  ESP_LOGCONFIG(TAG, "  Tolerance: %u%s", this->tolerance_,
Fixed for the ESP32. Can IDF 5 run on the ESP8266 too? (since you selected the file remote_receiver_esp8266.cpp)

2023-12-20 23:33 UTC, kbx81 commented on esphome/components/remote_receiver/remote_receiver_esp8266.cpp
> +  ESP_LOGCONFIG(TAG, "  Tolerance: %u%s", this->tolerance_,
Oh no - I totally missed the file name! 😅 I don't think it matters for the '8266 but it will for the other ESPs. 😄

2023-12-20 23:34 UTC, kbx81 commented on esphome/components/remote_receiver/remote_receiver_esp8266.cpp
> +  ESP_LOGCONFIG(TAG, "  Tolerance: %u%s", this->tolerance_,
Thanks for taking care of this!

2023-12-21 00:21 UTC, jesserockz approved these changes, later dismissed

2024-04-16 19:34 UTC, jesserockz requested changes

2024-04-16 19:34 UTC, jesserockz commented on esphome/components/remote_receiver/__init__.py
> +    )
This should not convert a "simple" value to a dict unless that dict is also valid to type in YAML directly.

2024-04-16 19:38 UTC, Mat931 commented on esphome/components/remote_receiver/__init__.py
> +    )
What should I do instead?

2024-05-01 23:16 UTC, dgomes commented
can confirm this code works properly :)

2024-05-02 01:07 UTC, jesserockz approved these changes

2024-05-02 01:21 UTC, merged