Add minimum RSSI check to ble presence + fox padding boolean values
OttoWinter/esphomeyaml pull request #4646
Opened 2023-04-02 22:34 UTC by nielsnl68

# What does this implement/fix?

I do have multiple BLE_PRESENCE sensors around the house and i liked to set when the sensor should say my etag was marked as present.
This PR will implement this behavier.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

binary_sensor:
  # Presence based on MAC address
  - platform: ble_presence
    mac_address: AC:37:43:77:5F:4C
    name: "ESP32 BLE Tracker"
    min_rssi: 80
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-04-02 23:22 UTC, jesserockz requested changes

2023-04-02 23:22 UTC, jesserockz commented on esphome/components/ble_presence/binary_sensor.py
> +        cg.add(var.set_minimum_rssi(config[CONF_MIN_RSSI].as_hex))
`as_hex` here is a little bit useless
```suggestion
        cg.add(var.set_minimum_rssi(config[CONF_MIN_RSSI]))
```

2023-04-02 23:22 UTC, jesserockz commented on esphome/components/ble_presence/binary_sensor.py
> +            cv.Optional(CONF_MIN_RSSI): cv.uint16_t,
The rssi reported is negative and should be using this:
```suggestion
            cv.Optional(CONF_MIN_RSSI): cv.decibel,
```

2023-04-02 23:22 UTC, jesserockz commented on esphome/components/ble_presence/ble_presence_device.h
> +  void set_minimum_rssi(uint16_t rssi) {
```suggestion
  void set_minimum_rssi(int rssi) {
```

2023-04-02 23:22 UTC, jesserockz commented on esphome/components/ble_presence/ble_presence_device.h
> +  uint16_t minimum_rssi_{0};
```suggestion
  int minimum_rssi_{0};
```

2023-04-23 20:50 UTC, jesserockz approved these changes

2023-05-07 00:58 UTC, nielsnl68 commented
I need some time to test this better :(

2023-05-11 16:27 UTC, jesserockz approved these changes

2023-05-11 16:28 UTC, merged