Add push to talk voice assistant
OttoWinter/esphomeyaml pull request #4648
Opened 2023-04-03 02:07 UTC by jesserockz

# In progress and not final

# What does this implement/fix?

Moving with the Year of the Voice in Home Assistant, this PR adds a few "linked" components.

- `i2s_audio` `microphone` for getting the audio data into ESPHome.
- `voice_assistant` asks Home Assistant to start a UDP server and then sends the received microphone data via UDP to that server.

## Related PRs
- https://github.com/esphome/aioesphomeapi/pull/412
- HA Core TBD

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-04-03 04:59 UTC, herostrat commented
Wow, massive respect for this. Awesome work!

2023-04-03 07:10 UTC, SeByDocKy commented
WHoaahhh .....

2023-04-03 08:59 UTC, nielsnl68 requested changes
I hope you will breakout the `I2S_Audio` part from the `media_player` in the future as well, like you do with the `microphone` and `voice_assistant`. That way we could update the RTTTL component etc. to output using I2S as well or create an other component that can use the audion out component.

something like:
```yaml
speaker:
  platform: i2s_audio
  id: my_speaker
  ....

media_player:
  output: my_speaker
  ...
```
so we can do something like
```yaml
rtttl:
  output: my_speaker
  ....
```
etc.

2023-04-03 08:59 UTC, nielsnl68 commented on esphome/components/i2s_audio/media_player/__init__.py
> +from .. import i2s_audio_ns
```suggestion
from .. import i2s_audio_ns, CONF_I2S_DOUT_PIN, CONF_I2S_BCLK_PIN, CONF_I2S_LRCLK_PIN 
```

2023-04-03 15:16 UTC, nagyrobi commented
One suggestion though, maybe the naming and the approach could be a bit more universal. Instead of `voice_assistant` maybe `push_to_talk` could be more appropriate, as there could be other use cases of the UDP audio stream, not only voice assistants.

For example we could build a simple two-way intercom doorbell, where the core part is the same, it could just be a different UDP port, moreover, could be in the future another ESPHome node listening with a speaker...

2023-04-03 21:42 UTC, jesserockz commented
I actually named it `push_to_talk` originally, but then realised the `push_to_talk` part really was just the binary sensor triggers telling the `voice_assistant` to start, so that is done in yaml, and we may look at hot-word detection in the future if possible, so that would be another thing that triggers the start of `voice_assistant`

I do agree with you though partly, but its easy to set up another component that has its own udp setup to send the data to a different server like an intercom/direct p2p audio etc. This component is specifically set up to transmit the data to HA via the random port it receives.

The voice_assistant part is quite small itself and any component can latch onto a `microphone` and request the data "stream" and do whatever it wants.

2023-04-06 07:10 UTC, nagyrobi commented
@jesserockz please don't forget about the `annouce` flag coming from HA when TTS is being played. This was implemented to differentiate between normal media playback (eg. music) vs announcements or signalizations, which have a higher priority. Eg. if speakers are powered off, `annouce` can turn them on. If it's playing some music, that volume can be dimmed for wile the announcement sounds. When announcement playback finishes, the flag (=binary sensor) should go false, allowing to power the speakers back off or restore music original volume.

Also see https://github.com/esphome/feature-requests/issues/1771

2023-04-11 23:55 UTC, merged