New component: Add support for bmp581 pressure and temperature sensors
OttoWinter/esphomeyaml pull request #4657
Opened 2023-04-05 01:34 UTC by kahrendt

# What does this implement/fix?

This pull request add support for Bosch's BMP581's Pressure and Temperature sensors. The component supports enabling oversampling for temperature and pressure independently, as well as independently enabling an IIR filter for each sensor.

Any input is appreciated! Stylistically, I am unsure about best naming practices for the protected functions that interact with the sensor via I2C. In particular, I avoided using set_ or get_ prefixes because these functions involve updating the component's internal variables but also writing to or reading from the sensor itself. As such, I prefaced these functions with write_ or read_. Additionally, I update register bits directly in the setup code to configure settings. Would it be better practice to have set functions that modify these bits to abstract it away from directly modifying them in the setup function?

**Sorry for redoing this pull request! I made a Git mistake when attempting to rebase, and the old PR requested reviews for unrelated merges.**

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** not applicable

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2771

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: bmp581
    temperature:
      name: "BMP581 Temperature"
      iir_filter: 2x
    pressure:
      name: "BMP581 Pressure"
      oversampling: 128x
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-07-11 03:28 UTC, jesserockz commented on esphome/components/bmp581/bmp581.cpp
> +      this->determine_conversion_time_(this->temperature_oversampling_, this->pressure_oversampling_);
Could this not be determined at compile time since it is a static calculation based on the oversamplings which are known?

2023-07-11 13:51 UTC, kahrendt commented on esphome/components/bmp581/bmp581.cpp
> +      this->determine_conversion_time_(this->temperature_oversampling_, this->pressure_oversampling_);
Good point. I have moved that calculation into sensor.py

2023-08-08 00:32 UTC, jesserockz requested changes

2023-08-08 00:32 UTC, jesserockz commented on esphome/components/bmp581/sensor.py
> +    return math.ceil(1.05 * pressure_conversion_time + temperature_conversion_time)
```suggestion
    return math.ceil(1.05 * (pressure_conversion_time + temperature_conversion_time))
```

2023-08-08 00:32 UTC, jesserockz commented on esphome/components/bmp581/sensor.py
> +    ]
These will crash if either pressure or temperature is not configured

2023-08-08 00:32 UTC, jesserockz commented on esphome/components/bmp581/sensor.py
> +        cg.add(var.set_temperature_iir_filter_config(conf[CONF_IIR_FILTER]))
Also the same for pressure please
```suggestion
    if temperature_config := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_config)
        cg.add(var.set_temperature_sensor(sens))
        cg.add(var.set_temperature_oversampling_config(temperature_config[CONF_OVERSAMPLING]))
        cg.add(var.set_temperature_iir_filter_config(temperature_config[CONF_IIR_FILTER]))
```

2023-08-08 00:32 UTC, jesserockz commented on esphome/components/bmp581/bmp581.cpp
> +}
Not used?
```suggestion
```

2023-08-08 01:39 UTC, jesserockz approved these changes

2023-08-08 05:05 UTC, merged