Added m5stack_4_relays
OttoWinter/esphomeyaml pull request #4665
Opened 2023-04-07 18:44 UTC by KoenBreeman

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
# Example config.yaml
external_components:
  - source: github://pr#4664
    components: m5stack_4_relays

m5stack_4_relays:
  id: M5stackrelay_ID1
  i2c_id: bus_a

switch:
  - platform: m5stack_4_relays
    id: relay_1
    name: relay1
    channel: Relay_1
    M5Stack_4_Relays_id: M5stackrelay_ID1
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-04-07 20:40 UTC, KoenBreeman commented
@jesserockz I've opened this pull request and created a fork to implement this feature. I have no experience with this process, so I'm finding out while I'm doing it. Hopefully it's OK. If not any advice is appreciated. 

Furthermore I need to make some documents, I say that you had someone who did that for you. I have no experience with that. So I will check how I have to do that.

2023-04-12 20:04 UTC, KoenBreeman commented
@jesserockz I've added the documentation, how is this checked and merged?

2023-04-12 21:07 UTC, jesserockz requested changes
Mostly looks fine. A few comments below.

Also, dont need to add to many test yaml files, 1 will do fine.

2023-04-12 21:07 UTC, jesserockz commented on .gitignore
Please dont add lines to this file like this. You can add these to your .gitignore in your home folder if you plan to have an ignored folder in projects.

2023-04-12 21:07 UTC, jesserockz commented on esphome/components/m5stack4relay/__init__.py
> +CONF_M5Stack4Relay_ID = "m5stack4relay_id"
Should be all uppercase
```suggestion
CONF_M5STACK4RELAY_ID = "m5stack4relay_id"
```

2023-04-12 21:07 UTC, jesserockz commented on esphome/components/m5stack4relay/__init__.py
> +M5Stack_ns = cg.esphome_ns.namespace("m5stack4relay")
This should match the actual namespace
```suggestion
m5stack4relay_ns = cg.esphome_ns.namespace("m5stack4relay")
```

2023-04-12 21:07 UTC, jesserockz commented on esphome/components/m5stack4relay/m5stack4relay.cpp
> +  ESP_LOGCONFIG(TAG, "M5Stack_4_Relays:");
```suggestion
  ESP_LOGCONFIG(TAG, "M5Stack 4 Relays:");
```

2023-04-12 21:07 UTC, jesserockz commented on esphome/components/m5stack4relay/m5stack4relay.cpp
> +static const char *const TAG = "M5Stack_4_Relay";
```suggestion
static const char *const TAG = "m5stack_4_relay";
```

2023-04-12 21:07 UTC, jesserockz commented on esphome/components/m5stack4relay/m5stack4relay.cpp
> +    this->mark_failed();
Should not really fail the component just because of a bad write (or read above). It should go into warning mode and the next attempt can try again. We typically only mark components as failed during the setup phase.

2023-04-13 17:35 UTC, KoenBreeman commented
> Mostly looks fine. A few comments below.
> 
> Also, dont need to add to many test yaml files, 1 will do fine.

I'll do that next time, should I remove them or not?

2023-04-16 11:37 UTC, KoenBreeman commented
@jesserockz Is it ok now?

2023-04-16 20:40 UTC, jesserockz requested changes

2023-04-16 20:40 UTC, jesserockz commented on esphome/components/m5stack4relay/__init__.py
> +
```suggestion
```

2023-04-16 20:40 UTC, jesserockz commented on esphome/components/m5stack4relay/__init__.py
> +    .extend(i2c.i2c_device_schema(CONF_I2C_ADDR))
Dont need a const for the address
```suggestion
    .extend(i2c.i2c_device_schema(0x26))
```

2023-04-16 20:40 UTC, jesserockz commented on esphome/components/m5stack4relay/switch/__init__.py
> +from esphome.const import CONF_CHANNEL, CONF_INTERLOCK  # , CONF_ID,
```suggestion
from esphome.const import CONF_CHANNEL, CONF_INTERLOCK
```

2023-04-16 20:40 UTC, jesserockz commented on esphome/components/m5stack4relay/switch/__init__.py
> +    await cg.register_parented(var, config[CONF_M5STACK4RELAY_ID])
No commented code please
```suggestion
    var = await switch.new_switch(config)
    await cg.register_component(var, config)
    await cg.register_parented(var, config[CONF_M5STACK4RELAY_ID])
```

2023-04-27 06:39 UTC, jesserockz reviewed
I wonder if these switches should actually be binary outputs, it moves the concern of interlocking to existing switch code and simplifies the implementation for this component...

2023-05-05 20:07 UTC, closed without merging

2023-05-05 20:38 UTC, KoenBreeman commented
> I wonder if these switches should actually be binary outputs, it moves the concern of interlocking to existing switch code and simplifies the implementation for this component...

Hi Jesse

Just returned from a small vacation. I've created a new branch and move the code to the new branch. Should I just implement this suggestion into the switch component? The new pull request is https://github.com/esphome/esphome/pull/4786

2023-05-05 20:45 UTC, jesserockz commented
Yes, please change them to binary outputs in the new PR/branch.

Thanks

2023-05-05 21:03 UTC, KoenBreeman commented
> Yes, please change them to binary outputs in the new PR/branch.
> 
> Thanks

Just a quick question, how do you plan on implementing the interlock than? For me it's now not an issue, but I want to contribute. So would you like me to change the switch.h and switch.cpp to implement the changes of the interlocking? Or is there another way you intent to implement the interlocking? I do not fully get the picture yet, sorry for that.