Add dashboard API to get firmware binaries
OttoWinter/esphomeyaml pull request #4675
Opened 2023-04-11 17:12 UTC by kuba2k2

# What does this implement/fix?

Dashboard API improvements for https://github.com/esphome/dashboard/pull/469. See that PR for description of changes.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

2023-07-12 03:47 UTC, jesserockz requested changes
I dont think the same endpoint should be used for getting the list of available files per platform, it should have its own endpoint

2023-07-13 11:24 UTC, kuba2k2 commented
Okay, should be better now. I don't even know why did I put that in the same endpoint. I'll update the dashboard in a moment.

2023-07-13 13:28 UTC, kuba2k2 commented
I updated esphome and dashboard to current upstream branch, and updated the list endpoint.

Also, I added a Popen()-based process spawning method, so that the dashboard can be tested on Windows. Nothing changes for Linux/Docker users, it only adds Windows compatibility (which would raise a Python exception prior to that).

2023-07-16 22:59 UTC, jesserockz requested changes

2023-07-16 22:59 UTC, jesserockz commented on esphome/__main__.py
Please make these changes in their own PR

2023-07-16 22:59 UTC, jesserockz commented on esphome/components/esp32/__init__.py
> +def get_download_types(storage_json=None):
This should be required (or it will crash the below code)
```suggestion
def get_download_types(storage_json):
```

2023-07-16 22:59 UTC, jesserockz commented on esphome/components/esp8266/__init__.py
> +def get_download_types(storage_json=None):
```suggestion
def get_download_types(storage_json):
```

2023-07-16 22:59 UTC, jesserockz commented on esphome/components/rp2040/__init__.py
> +def get_download_types(storage_json=None):
```suggestion
def get_download_types(storage_json):
```

2023-07-16 22:59 UTC, jesserockz commented on esphome/dashboard/dashboard.py
> +        file_name = self.get_argument("file", "firmware.bin")
Please also check the `type` as a fallback so we can deprecate that param over time

2023-07-16 22:59 UTC, jesserockz commented on esphome/dashboard/dashboard.py
> +        self._use_popen = os.name == "nt"
Please move any dashboard fixes for windows into their own PR

2023-07-17 10:18 UTC, kuba2k2 commented on esphome/dashboard/dashboard.py
> +        file_name = self.get_argument("file", "firmware.bin")
Should I also worry about not specifying `type=` at all (and falling back to default `firmware.bin`)? That will not work for RP2040, as `firmware.uf2` is used instead. The type/file parameter should be mandatory, and AFAIK has been passed by the dashboard already at all times.

2023-07-18 00:25 UTC, jesserockz commented on esphome/dashboard/dashboard.py
> +        file_name = self.get_argument("file", "firmware.bin")
Making them mandatory is fine. The download endpoint has been documented to be used externally recently for a tasmota ota update to ESPHome so I don't want to break that.

2023-09-01 05:26 UTC, jesserockz approved these changes, later dismissed

2023-09-01 05:27 UTC, jesserockz approved these changes

2023-09-01 06:17 UTC, merged