Add pylontech integration
OttoWinter/esphomeyaml pull request #4688
Opened 2023-04-14 22:35 UTC by functionpointer

# What does this implement/fix?

Adds a new integration that reads the state of battery banks made by Pylontech.
Pylontech makes large battery banks for PV systems.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** none

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
uart:
  - id: pylontech_uart
    tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 115200

pylontech:
  - uart_id: pylontech_uart
    id: pylontech0
    update_interval: 5s

sensor:
  - platform: pylontech
    pylontech_id: pylontech0
    battery: 1

    voltage:
      id: bat1_voltage
      name: "Battery1 Voltage"
    current:
      id: bat1_current
      name: "Battery1 Current"
    coulomb:
      id: bat1_soc
      name: "Battery1 State of Charge"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-04-15 09:05 UTC, SeByDocKy commented
Great adding !!!

2023-05-24 04:51 UTC, norcon commented
Can't wait to use it :-) thanks a lot!

2023-09-05 22:18 UTC, jesserockz commented on esphome/components/pylontech/__init__.py
> +        add_num_batteries.already_ran = True
A much simpler method would just be to have `num_batteries` as a config item on the main component...

2023-09-06 12:57 UTC, functionpointer commented on esphome/components/pylontech/__init__.py
> +        add_num_batteries.already_ran = True
Very much simpler, yes. I didn't like it because it would be redundant. [The config](https://deploy-preview-2841--esphome.netlify.app/components/pylontech#sensor) already requires a separate block for every battery.

All this code is really doing is counting how many config blocks are defined.
Is there a better way of doing this than what is currently implemented?

2023-09-11 11:28 UTC, functionpointer commented on esphome/components/pylontech/__init__.py
> +        add_num_batteries.already_ran = True
Well, apparently not.

Do you want me to implement `num_batteries`? I don't like it, but i will implement it to get this PR merged.

2023-10-28 01:54 UTC, functionpointer commented on esphome/components/pylontech/__init__.py
> +        add_num_batteries.already_ran = True
Implemented it.

2023-11-06 02:54 UTC, jesserockz requested changes

2023-11-06 02:54 UTC, jesserockz commented on esphome/components/pylontech/sensor/__init__.py
> +    await check_battery_index(bat)
Validation is not to be performed inside `to_code`

Please see other components implementations of `FINAL_VALIDATE_SCHEMA` to validate sensor configs against parent configs.
```suggestion
```

2023-11-06 02:54 UTC, jesserockz commented on esphome/components/pylontech/pylontech.h
> +  PYLONTECH_SENSOR(mos_temperature)
All sensor code needs to be wrapped similar to text sensors.
```suggestion
#ifdef USE_SENSOR
  PYLONTECH_SENSOR(voltage)
  PYLONTECH_SENSOR(current)
  PYLONTECH_SENSOR(temperature)
  PYLONTECH_SENSOR(temperature_low)
  PYLONTECH_SENSOR(temperature_high)
  PYLONTECH_SENSOR(voltage_low)
  PYLONTECH_SENSOR(voltage_high)

  PYLONTECH_SENSOR(coulomb)
  PYLONTECH_SENSOR(mos_temperature)
#endif
```

2023-11-06 02:54 UTC, jesserockz commented on esphome/components/pylontech/__init__.py
> +    cg.add_define("PYLONTECH_NUM_BATTERIES", config[CONF_NUM_BATTERIES])
To follow the format we use in ESPHome, the define should be like this:
```suggestion
    cg.add_define("USE_PYLONTECH_NUM_BATTERIES", config[CONF_NUM_BATTERIES])
```

2023-11-06 02:54 UTC, jesserockz commented on esphome/components/pylontech/__init__.py
> +        raise cv.Invalid(f"battery expected between 1 and {num_batteries}")
See my other comment on validation against parent

```suggestion
```

2023-11-06 02:54 UTC, jesserockz commented on esphome/components/pylontech/__init__.py
> +    num_batteries = config[CONF_NUM_BATTERIES]
```suggestion
```

2023-11-06 02:54 UTC, jesserockz commented on esphome/components/pylontech/pylontech.cpp
> +    }
The LOG_SENSOR macro already does a nullptr check
```suggestion
    LOG_SENSOR("  ", "Voltage", this->voltage_[bat_num]);
```

2023-11-06 02:54 UTC, jesserockz commented on esphome/components/pylontech/pylontech.cpp
> +    this->voltage_[bat_num]->publish_state(((float) volt) / 1000);
```suggestion
    this->voltage_[bat_num]->publish_state(((float) volt) / 1000.0f);
```

2023-11-06 02:54 UTC, jesserockz commented on esphome/components/pylontech/pylontech.h
> +};
Not used?

2023-11-07 00:14 UTC, functionpointer commented on esphome/components/pylontech/pylontech.h
> +};
Indeed. Removed.

2023-11-07 00:15 UTC, functionpointer commented on esphome/components/pylontech/__init__.py
> +    cg.add_define("PYLONTECH_NUM_BATTERIES", config[CONF_NUM_BATTERIES])
Removed entirely :)

2023-11-07 00:16 UTC, functionpointer commented on esphome/components/pylontech/sensor/__init__.py
> +    await check_battery_index(bat)
Good to know `FINAL_VALIDATE_SCHEMA` exists!

2023-11-07 00:18 UTC, functionpointer commented on esphome/components/pylontech/__init__.py
> +        add_num_batteries.already_ran = True
Turns out the recently used ld2420 uses `std::vector`. I did not know this was allowed in embedded context.
So i rewrote this PR with a `std::vector` at its core, which solves all the problems i had.

No crazy validation, no global variables, no define. So much cleaner IMO

2023-11-16 10:50 UTC, functionpointer commented
@jesserockz i addressed all issues, this code is ready for another review.

I have since also tested it with a US3000C, and it works great.

2023-11-16 11:00 UTC, norcon commented
> @jesserockz i addressed all issues, this code is ready for another review.
> 
> 
> 
> I have since also tested it with a US3000C, and it works great.

Cannot wait to get it up and running

2023-11-16 11:22 UTC, SeByDocKy commented
Should be merge soon in the dev  version..... :) 👍

2023-11-21 01:10 UTC, jesserockz requested changes

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/sensor/__init__.py
> +)
```suggestion
CONFIG_SCHEMA = PYLONTECH_COMPONENT_SCHEMA.extend(
    {cv.GenerateID(): cv.declare_id(PylontechSensor)}
).extend(
    {cv.Optional(marker): schema for marker, schema in TYPES.items()}
)
```

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/pylontech.h
> +#define PYLONTECH_TEXT_SENSOR(name) PYLONTECH_ENTITY_(text_sensor::TextSensor, name)
We already have macros for these
`SUB_SENSOR(name)` in `esphome/components/sensor/sensor.h` for example
```suggestion
```

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/pylontech.h
> +#endif
Shouldnt be required when using listeners
```suggestion
```

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/sensor/__init__.py
> +            sens = await sensor.new_sensor(config[marker])
```suggestion
        if marker_config := config.get(marker):
            sens = await sensor.new_sensor(marker_config)
```

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/sensor/__init__.py
> +            cg.add(getattr(bat, f"set_{marker}")(sens))
`SUB_SENSOR` names them with a `sensor` suffix
```suggestion
            cg.add(getattr(bat, f"set_{marker}_sensor")(sens))
```

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/__init__.py
> +CONF_NUM_BATTERIES = "num_batteries"
These should move to the file that actually uses them if they are not common to multiple files, or move to the `esphome/const.py`

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/sensor/pylontech_sensor.h
> +  int bat_num_;
No need to assign 4 bytes for a number that is only between 1 and 6 =)
```suggestion
  uint8_t bat_num_;
```

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/sensor/pylontech_sensor.h
> +  PylontechSensor(int bat_num);
```suggestion
  PylontechSensor(uint8_t bat_num);
```

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/sensor/pylontech_sensor.h
> +  PYLONTECH_SENSOR(voltage)
```suggestion
  SUB_SENSOR(voltage)
```

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/sensor/pylontech_sensor.cpp
> +  LOG_SENSOR("  ", "Voltage", this->voltage_);
```suggestion
  LOG_SENSOR("  ", "Voltage", this->voltage_sensor_);
```

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/sensor/pylontech_sensor.cpp
> +PylontechSensor::PylontechSensor(int bat_num) { this->bat_num_ = bat_num; }
```suggestion
PylontechSensor::PylontechSensor(uint8_t bat_num) { this->bat_num_ = bat_num; }
```

2023-11-21 01:10 UTC, jesserockz commented on esphome/components/pylontech/text_sensor/__init__.py
Please make the same changes here as in `sensor/__init.py`

2023-11-21 12:55 UTC, functionpointer commented on esphome/components/pylontech/sensor/pylontech_sensor.h
> +  int bat_num_;
Good point.
I have used `int8_t` though, as it has less potential for bugs when comparing and subtracting.

2023-11-21 12:56 UTC, functionpointer commented on esphome/components/pylontech/sensor/__init__.py
> +)
Unfortunately black formats it less nicely:
```python
CONFIG_SCHEMA = PYLONTECH_COMPONENT_SCHEMA.extend(
    {cv.GenerateID(): cv.declare_id(PylontechSensor)}
).extend({cv.Optional(marker): schema for marker, schema in TYPES.items()})
```
Implemented nonetheless.

2023-11-27 21:20 UTC, jesserockz commented on esphome/components/pylontech/sensor/__init__.py
> +)
You can usually manually add commas to force black to use newlines

2023-11-27 21:56 UTC, jesserockz approved these changes, later dismissed
Thanks for making those changes =)

2023-11-27 22:02 UTC, jesserockz commented on esphome/components/pylontech/__init__.py
> +MULTI_CONF = True
Just a small tidy up and removal of auto load that is not needed
```suggestion
_LOGGER = logging.getLogger(__name__)

CODEOWNERS = ["@functionpointer"]
DEPENDENCIES = ["uart"]
MULTI_CONF = True
```

2023-11-27 22:05 UTC, jesserockz commented on esphome/components/pylontech/__init__.py
> +        cv.Required(CONF_PYLONTECH_ID): cv.use_id(PylontechComponent),
This can be used for automatic id resolving
```suggestion
        cv.GenerateID(CONF_PYLONTECH_ID): cv.use_id(PylontechComponent),
```

2023-11-27 22:24 UTC, jesserockz approved these changes

2023-11-27 22:43 UTC, merged