Allow partially looping animations
OttoWinter/esphomeyaml pull request #4693
Opened 2023-04-15 22:13 UTC by guillempages

# What does this implement/fix?
    Add the possibility of specifying a "loop" in an animation; where the
    requested frames (start - end) will be repeateadly shown for "count" times.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> TBD

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
animation:
  - id: fire
    file: "fire.gif"
    loop:
      start_frame: 4
      end_frame: 7
      repeat: 5
# When calling "next_frame()" on the animation, frames 4 to 7 will be repeated 5 times before moving on to frame 8.
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-04-16 12:35 UTC, guillempages commented
This PR is based on #4600 to avoid merge conflicts later on; once that one is merged, a simple rebase to "dev" should make this one much smaller.

2023-05-21 20:57 UTC, kroimon requested changes

2023-05-21 20:57 UTC, kroimon commented on esphome/components/animation/__init__.py
> +                    cv.Optional(CONF_REPEAT): cv.Any(None, cv.int_),
Do you need `None` here at all if they are optional anyway?

2023-05-21 20:57 UTC, kroimon commented on esphome/components/display/display_buffer.cpp
> +  }
Your innermost `if` is effectively a `==` as you already checked for `<=` in the outermost `if`.
You can merge that into one or two `if`s:

```suggestion
  if (loop_count_ && this->current_frame_ == loop_end_frame_
      && (this->loop_current_iteration_ < loop_count_ || loop_count_ < 0)) {
    this->current_frame_ = loop_start_frame_;
    this->loop_current_iteration_++;
  }
```

2023-05-22 05:34 UTC, kbx81 commented on esphome/components/animation/__init__.py
> +                    cv.Optional(CONF_REPEAT): cv.Any(None, cv.int_),
^^^ second this -- I just tried locally and this seems to work whether the parameter is specified or not:

```suggestion
                    cv.Optional(CONF_END_FRAME): cv.int_,
                    cv.Optional(CONF_REPEAT): cv.int_,
```

2023-05-22 20:14 UTC, guillempages commented on esphome/components/animation/__init__.py
> +                    cv.Optional(CONF_REPEAT): cv.Any(None, cv.int_),
I followed the upstream voluptuous documentation, but you are right; that is superfluous.

2023-05-22 20:23 UTC, guillempages commented on esphome/components/display/display_buffer.cpp
> +  }
Thanks for pointing this out. I spent so much time trying to make the loop work at all, that I did not see the redundancy anymore.

2023-05-22 20:26 UTC, kroimon commented on esphome/components/display/display_buffer.cpp
> +  }
Happens to all of us 😄 That's exactly what code reviews are for.

2023-05-23 06:17 UTC, kbx81 commented on esphome/components/animation/__init__.py
> +                    cv.Optional(CONF_REPEAT): cv.Any(None, cv.int_),
I should've mentioned this the first time, but `cv.positive_int` would probably be even better for these (I'm assuming you'd never want to allow a value less than zero). 😄

2023-05-23 06:28 UTC, kbx81 reviewed
One more quick suggestion for validation -- I should've mentioned this before, sorry! I hope it makes sense. If not, feel free to discard.

2023-05-23 06:28 UTC, kbx81 commented on esphome/components/animation/__init__.py
> +                    cv.Optional(CONF_REPEAT): cv.int_,
```suggestion
                    cv.Optional(CONF_START_FRAME, default=0): cv.positive_int,
                     cv.Optional(CONF_END_FRAME): cv.positive_int,
                     cv.Optional(CONF_REPEAT): cv.positive_int,
```

2023-05-23 06:29 UTC, kbx81 commented on esphome/components/animation/__init__.py
> +                    cv.Optional(CONF_REPEAT): cv.Any(None, cv.int_),
Left a suggestion in case it's easier to just merge in the change that way. Sorry for not catching this the first time!

2023-05-23 07:45 UTC, guillempages commented on esphome/components/animation/__init__.py
> +                    cv.Optional(CONF_REPEAT): cv.int_,
I'm using "-1" as the default for the repeat in the c++ part of the code, but you are right, the configuration itself should be positive only; default is handled by "None" here. 
Thanks!

2023-05-23 08:18 UTC, guillempages commented
@kbx81 I've implemented your suggestion, and while I was at it, I also changed the types in the c++ part whenever possible, to also use unsigned types (and thus avoid some unnecessary checks for >0 )

2023-05-24 07:44 UTC, kroimon commented on esphome/components/display/display_buffer.cpp
> +  loop_count_ = count;
I just noticed that you should probably reset the current loop iteration when updating the parameters, for example via a lambda.
```suggestion
  if (loop_count_ != count) {
    this->loop_current_iteration_ = 1;
  }
  loop_count_ = count;
```

2023-05-24 19:17 UTC, guillempages commented on esphome/components/display/display_buffer.cpp
> +  loop_count_ = count;
The lambda thought is a valid one; I hadn't thought about that, I considered this setter method as "part of the constructor".

Nevertheless I would do that without the if; when the parameters are reset in a lambda, the iteration count should also restart.

Also, weren't you the one (rightly) warning me about useless loops? In your suggestion there is a useless assignment: if the ˋifˋ is not entered, there is no point in setting the ˋloop_countˋ to ˋcountˋ; they are already equal ;-)

2023-05-25 19:26 UTC, kbx81 commented
I'm good with this -- any other feedback/changes? 😄

2023-05-25 19:34 UTC, guillempages commented
Not from my side 😉

2023-05-25 21:49 UTC, merged