[ili9xxx] Allow config of spi data rate.
OttoWinter/esphomeyaml pull request #4701
Opened 2023-04-17 11:01 UTC by Fabian-Schmidt

# What does this implement/fix?

Allow config of spi data rate. For example WT32-SC01 can be run with 80MHz for faster processing.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2851

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

- platform: ili9xxx
    model: ST7796
    cs_pin: 15
    dc_pin: 21
    reset_pin: 22
    data_rate: 80Mhz

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-04-26 20:11 UTC, jesserockz submitted a review, later dismissed
The below changes should work and make a little simpler, please test though

2023-04-26 20:11 UTC, jesserockz commented on esphome/components/spi/__init__.py
> +
```suggestion
SPI_DATA_RATE_OPTIONS = {
    80e6: SPIDataRate.DATA_RATE_80MHZ,
    40e6: SPIDataRate.DATA_RATE_40MHZ,
    20e6: SPIDataRate.DATA_RATE_20MHZ,
    10e6: SPIDataRate.DATA_RATE_10MHZ,
    5e6: SPIDataRate.DATA_RATE_5MHZ,
    2e6: SPIDataRate.DATA_RATE_2MHZ,
    1e6: SPIDataRate.DATA_RATE_1MHZ,
    2e5: SPIDataRate.DATA_RATE_200KHZ,
    75e3: SPIDataRate.DATA_RATE_75KHZ,
    1e3: SPIDataRate.DATA_RATE_1KHZ,
}
SPI_DATA_RATE_SCHEMA = cv.All(cv.frequency, cv.enum(SPI_DATA_RATE_OPTIONS))

```

2023-04-26 20:11 UTC, jesserockz commented on esphome/components/ili9xxx/display.py
> +            cv.Optional(CONF_DATA_RATE, default="40MHz"): spi.SPIDataRate_SCHEMA,
```suggestion
            cv.Optional(CONF_DATA_RATE, default="40MHz"): spi.SPI_DATA_RATE_SCHEMA,
```

2023-04-26 20:11 UTC, jesserockz commented on esphome/components/ili9xxx/display.py
> +    spi_data_rate = spi.SPIDataRate_OPTIONS[config[CONF_DATA_RATE]]
```suggestion
    spi_data_rate = config[CONF_DATA_RATE]
```

2023-04-27 19:56 UTC, Fabian-Schmidt commented
Thanks updated code based on feedback.

2023-05-26 02:26 UTC, kbx81 requested changes
Quick comment about the default speed -- that aside, LGTM 😄

2023-05-26 02:26 UTC, kbx81 commented on esphome/components/ili9xxx/display.py
> +            cv.Optional(CONF_DATA_RATE, default="40MHz"): spi.SPI_DATA_RATE_SCHEMA,
I would strongly suggest using a safer default such as 10 MHz -- most people are connecting these with dupont wires and 40 MHz is likely to cause issues in this case. Speeds greater than 10 MHz are likely to require a custom PCB which is definitely not what most people are using. 😇

```suggestion
            cv.Optional(CONF_DATA_RATE, default="10MHz"): spi.SPI_DATA_RATE_SCHEMA,
```

2023-05-26 02:29 UTC, kbx81 commented on esphome/components/ili9xxx/display.py
> +            cv.Optional(CONF_DATA_RATE, default="40MHz"): spi.SPI_DATA_RATE_SCHEMA,
...related -- it would probably be worthwhile to add a note to the docs about this. I realize most people just want the fastest speed possible; however, there are electrical/physical limitations that software can't fix and people are likely to open issues based on this if it's not called out. 😇

2023-05-26 06:33 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
> +            cv.Optional(CONF_DATA_RATE, default="40MHz"): spi.SPI_DATA_RATE_SCHEMA,
I disagree, the default was always 40MHz why should we change that to 10MHz now just because we can set the value lower.

2023-05-26 07:20 UTC, kroimon commented
The use of the define makes the unlikely but theoretically possible use of two displays with different data rates impossible, right?
That should then probably be added to the docs as a hint.

2023-05-26 08:09 UTC, nielsnl68 commented
> The use of the define makes the unlikely but theoretically possible use of two displays with different data rates impossible, right? That should then probably be added to the docs as a hint.
From my understanding is this no problem, the SPI bus switched speed based on the connected device.

2023-05-26 14:17 UTC, kbx81 commented on esphome/components/ili9xxx/display.py
> +            cv.Optional(CONF_DATA_RATE, default="40MHz"): spi.SPI_DATA_RATE_SCHEMA,
I didn't realize the original default was 40 MHz -- but I still think this is a risky value to use by default given how many folks who use the platform in general tend to wire projects up. Frequencies higher than about ten MHz tend to be affected negatively by the extra capacitance that breadboards/perfboards/dev boards introduce; we have seen this with the Ethernet component, for example.

I only made the suggestion because I think we should use a safer default that should work for everyone as opposed to a default that may perform better but cause problems for folks with less-than-perfect wiring...regardless of what it was going before. Still, I'm ok with the more aggressive setting, but it might be worth adding a note to the docs to try slowing it down if you experience issues with the display.

2023-05-26 14:36 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
> +            cv.Optional(CONF_DATA_RATE, default="40MHz"): spi.SPI_DATA_RATE_SCHEMA,
I understand what you are saying, and i would have agreed with it when this was a new component. Sadly it is not and we should not down talk the people that are using this component to already and only want to have a faster display and not slower.

Also, in the last year or so that i have worked on the ili9xxx component and before i have never heard or seen issues that where related to the fast SPI communication.

So i belief for sure we can let it be set to 40MHz and when someone has indeed issues like you for shadow than we can now advice to set the `data rate` to a slower frequency.

2023-05-26 15:02 UTC, kbx81 commented on esphome/components/ili9xxx/display.py
> +            cv.Optional(CONF_DATA_RATE, default="40MHz"): spi.SPI_DATA_RATE_SCHEMA,
Sounds good, works for me! 😄

2023-05-26 16:26 UTC, Fabian-Schmidt commented
> The use of the define makes the unlikely but theoretically possible use of two displays with different data rates impossible, right? That should then probably be added to the docs as a hint.

Correct. Having two displays with different SPI speed should result in the last configured speed be used by all ili9xxx displays and a compile warning be generated.
If it is desired that multiple displays can be used with different SPI speed then the PR will be much larger / complex.

2023-06-19 03:30 UTC, jesserockz commented
I guess to make it per display we would need to template the ILI9xxx class with the speed. 
But honestly, is there anyone that uses multiple displays with a single ESP?

2023-06-21 15:30 UTC, Fabian-Schmidt commented
> I guess to make it per display we would need to template the ILI9xxx class with the speed. But honestly, is there anyone that uses multiple displays with a single ESP?

I have added a note to the docs about this behaviour.

2023-07-05 04:45 UTC, kbx81 approved these changes

2023-07-05 04:46 UTC, kbx81 commented
@Fabian-Schmidt if you'll rebase this, I think we can merge. 🙃

2023-07-05 07:51 UTC, kbx81 approved these changes

2023-07-05 07:53 UTC, merged

2023-07-05 22:38 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.h
> +                                             spi::CLOCK_PHASE_LEADING, ILI9XXXDisplay_DATA_RATE> {
Why the use of a `#DEFINE` for this, why not use a direct approach?

2023-07-06 01:01 UTC, kbx81 commented on esphome/components/ili9xxx/ili9xxx_display.h
> +                                             spi::CLOCK_PHASE_LEADING, ILI9XXXDisplay_DATA_RATE> {
True -- this could easily be an `enum`. Easy fix/patch, though 😇

2023-07-06 07:40 UTC, Fabian-Schmidt commented on esphome/components/ili9xxx/ili9xxx_display.h
> +                                             spi::CLOCK_PHASE_LEADING, ILI9XXXDisplay_DATA_RATE> {
This is a C++ template class inheritance. So I must specify a solid type here or make `ILI9XXXDisplay` a template to propagate the parameter to the child classes and make all 20 child classes also templates so I can specify them from python. Given this would have been a larger change and the only benefit is that two displays could be connected. I opted for the easier solution.