GTK101 support
OttoWinter/esphomeyaml pull request #4703
Opened 2023-04-17 13:43 UTC by Szewcson

# What does this implement/fix?

Support for [GDK-101](url=http://allsmartlab.com/eng/294-2/) Radiation Detector Module from FTLab.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <[link to issue](https://github.com/esphome/feature-requests/issues/496)>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: True
  id: bus_a
  frequency: 100kHz
#  timeout: 15ms

gdk101:    
  i2c_id: bus_a
  address: 0x18
  update_interval: 10s

sensor:
  - platform: gdk101
    radiation_dose_per_1_minute:
      name: "Radiation @ 1 minute"
    radiation_dose_per_10_minutes:
      name: "Radiation @ 10 minutes"
    status:
      name: "Status"
    version:
      name: "sensor fw version"
    meas_time:
      name: "Measurement Time"

binary_sensor:
  - platform: gdk101
    vibrations:
      name: "vibration status"
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-04-19 09:22 UTC, Szewcson commented
Should I add tests for other platforms then esp32? I plan to test it locally also on rp2040 within two days.

2023-04-20 18:40 UTC, Szewcson commented
Sensor works also on rp2040. Other thing is that Raspberry Pi Pico W not seems to be very stable platform.

2023-07-25 17:49 UTC, ssieb commented
Does HA support the `radiation` device class?

2023-07-26 17:03 UTC, Szewcson commented
I think no, should I set it to none since there is no appropriate class supported by HA? https://www.home-assistant.io/integrations/sensor#device-class

2023-07-27 20:11 UTC, jesserockz requested changes

2023-07-27 20:11 UTC, jesserockz commented on esphome/const.py
> +DEVICE_CLASS_RADIATION = "radiation"
Device classes are syncronised with Home assistant automatically. 
If the class does not already exist, it cannot just be added here.

2023-09-25 08:37 UTC, Szewcson commented on esphome/const.py
> +DEVICE_CLASS_RADIATION = "radiation"
device class changed to DEVICE_CLASS_EMPTY

2023-12-21 06:11 UTC, jesserockz requested changes

2023-12-21 06:11 UTC, jesserockz commented on esphome/components/gdk101/__init__.py
> +    .extend(cv.polling_component_schema("10s"))
We like to set the default to 60s, the user can set whatever time they want in YAML
```suggestion
    .extend(cv.polling_component_schema("60s"))
```

2023-12-21 06:11 UTC, jesserockz commented on esphome/components/gdk101/__init__.py
> +AUTO_LOAD = ["sensor", "binary_sensor"]
Instead of auto loading platforms, we ask that components are rewritten in a safe way that they will work if `sensor` or `binary_sensor` are not compiled into the final application.

```suggestion
```

2023-12-22 06:14 UTC, jesserockz requested changes

2023-12-22 06:14 UTC, jesserockz commented on esphome/components/gdk101/gdk101.h
> +#include "esphome/components/binary_sensor/binary_sensor.h"
Please see how other components have `#ifdef USE_SENSOR` etc to guard against code not being available.

2024-01-24 16:18 UTC, Szewcson commented on esphome/components/gdk101/gdk101.h
> +#include "esphome/components/binary_sensor/binary_sensor.h"
Is there an define for i2c? I can't find it.

2024-05-06 05:14 UTC, Szewcson commented
It looks like CONF_VIBRATIONS should also be moved. I can fix that today's eveni g.

2024-05-06 05:20 UTC, Szewcson commented
There is also some meas_time left somewhere.

2024-05-06 17:41 UTC, Szewcson commented
@jesserockz it passed all the tests again. Can we merge it?

2024-05-06 19:23 UTC, jesserockz approved these changes

2024-05-06 19:23 UTC, jesserockz commented
Thanks @Szewcson

2024-05-13 01:36 UTC, merged