Online image buffer
OttoWinter/esphomeyaml pull request #4710
Opened 2023-04-19 22:06 UTC by guillempages

# What does this implement/fix?

This PR implements the possibility of downloading PNG images at runtime and showing them in a compatible display.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes #1463

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2076
## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  # ...
  on_boot:
    then:
      - wait_until: api.connected
      - component.update: example_image

online_image:
  - url: "https://www.example.org/image.png"
    id: example_image
    type: RGB565

display:
  # ...
  lambda: |-
    it.image(0, 0, id(example_image));
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-04-20 05:05 UTC, osos commented
If I understand correct, the image is only downloaded when _updated_.

I have a dynamic image, which I which to download and display every minute or less. I suppose I now need to _update_ then _display_ ?

Feature suggestion: Event on update/download finished, e.g. for a call to display the image once downloaded.

2023-04-20 06:48 UTC, guillempages commented
@osos yes, the image needs to be updated and then the display as well.
I also had thought about this callback, but then thought "it's easier/shorter to just do ```
 - component.update: my_image
 - component.update: my_display
```
than ```
  - component.update: my_image
on_image_downloaded:
  - component.update: my_display
```
Of course, I forgot about the "update_interval" case :-( That would be a "valid" use case for the "on_downloaded" callback. Neverhteless, I'd rather focus on getting it working good first (there are still sometimes issues when decoding that I haven't been able to track down / fix). There is already a workaround for your use case: Instead of using `update_interval`, you could define an ```
interval:
  - time: 1m
  - then:
    - component.update: my_image
    - component.update: my_display
```
and would achieve the same.

2023-04-27 16:54 UTC, peralta commented
I am unable to get esphome to build using the components in this PR (I was against PR #3255). This is the relevant config part:
```
external_components:
  - source: github://pr#4710
    components: [ online_image, image, display ]
online_image:
  - url: "https://www.example.org/image.png"
    id: example_image
```

Which fails with
```
Failed config

online_image: [source ll-test.yaml:70]
  
  Component not found: online_image.
  - url: https://www.example.org/image.png
    id: example_image
```

I have tried different things to get it to compile, but in the end I have realised that just changing the PR number to 3255 works and 4710 does not. Any idea of what might the problem be?

2023-04-28 08:43 UTC, peralta commented
Found the issue: missing dependencies and esphome silently eating the exception. Missing dependencies in the official docker container are `reportlab` and `svglib`.

2023-05-01 16:52 UTC, Unfocused commented on esphome/components/image/__init__.py
> +        mdi_id = config[CONF_MDI]
Was already loving this PR, but seeing this get added just made my day. I recently started working on an `icon_font` component so I could easily use MDI icons, but I like this better. 

One design decision I made early on that I'd like you to consider is supporting using an optional prefix in the icon name - ie, allowing both `weather-sunny` and `mdi:weather-sunny`. So the YAML could be written as:

```yaml
image:
  - id: mdi_weather_sunny
    mdi: "mdi:weather-sunny"
```

Aside from being the same syntax that Home Assistant uses, it allows using existing editor support for autocomplete, preview, and linting  - see [this extension](https://marketplace.visualstudio.com/items?itemName=lukas-tr.materialdesignicons-intellisense) for support for this in VS Code. Not everyone will use that, so I think the prefix should be optional.

Conviently, ESPHome requires Python 3.9 (as of 2022.10.0), which added `removeprefix()` (it just returns the original string if the prefix isn't there)

```suggestion
        mdi_id = config[CONF_MDI].removeprefix("mdi:")
```

2023-05-02 01:04 UTC, rbray89 commented
Is jpeg supported?

I'm interested in building a doorbell camera viewer, and would need jpeg support, or better yet, mjpeg support.

2023-05-02 11:27 UTC, guillempages commented on esphome/components/image/__init__.py
> +        mdi_id = config[CONF_MDI]
The MDI support is actually a separate PR (#4654); this one (online images) just happens to build on top of that one.
I haven't played with the VS Code extension yet, but from the documentation, it looks like it should be possible to enhance the regex used to detect mdi; why not add a "mdi: {param}" (i.e. with the space) to the extension configuration instead? would make the yaml better readable (`mdi: mdi:whatever` looks very ugly IMHO).

2023-05-02 11:30 UTC, guillempages commented
> Is jpeg supported?
> 
> I'm interested in building a doorbell camera viewer, and would need jpeg support, or better yet, mjpeg support.

Currently only PNG is supported. Once (if) this PR gets merged, I plan to add support for JPEG as well (I designed it with the possibility of adding additional formats in my mind). 

MJPEG is probably out of scope; both for performance reasons (it takes a couple of seconds to download and decode an image as it is now), and from an implementation point of view.
The PR is using additional libraries to decode images; I'm having trouble finding one for jpeg, and haven't seen any that supports mjpeg (for the ESP32 of course; I know ffmpeg supports it)

2023-05-05 17:46 UTC, Jellyfrog commented
Nice been looking for something like this!
One idea, add etag header support, then we don't need to download images that hasn't been updated

2023-05-06 23:13 UTC, Unfocused commented on esphome/components/image/__init__.py
> +        mdi_id = config[CONF_MDI]
Ah, I missed that, thanks.

I know it's not the prettist, but it's a simple win. 

TBH, if I were the maintainer of that extension, I would suggest ESPHome adopt the existing standard, rather than add yet another variation to the extension and risk breaking something unexpected.

2023-05-06 23:19 UTC, Unfocused commented
> I'm having trouble finding one for jpeg, and haven't seen any that supports mjpeg (for the ESP32 of course; I know ffmpeg supports it)

At least for HTTP streaming, MJPEG is sent as the `multipart/x-mixed-replace;boundary=` MIME type, and each "frame" is just a normal JPEG file separated by the MIME boundary. See the [`esp32_cmaera_web_server` component](https://github.com/esphome/esphome/blob/dev/esphome/components/esp32_camera_web_server/camera_web_server.cpp) for an example of how it's constructed. 

But saying that, I agree that it's not likely to work well.

2023-05-07 19:57 UTC, guillempages commented on esphome/components/image/__init__.py
> +        mdi_id = config[CONF_MDI]
Well, it is a separate PR, but this one (#4710) is rebased on top of that one, so yes, it can be tested by pointing it at this one ;-)

And I am also the creator of the other PR, so you still reached the "right" guy :-D

I'm still not fully convinced it looks good on the yaml config, but haven't been able to make the one with the space work with intellisense, so I'll add that to the PR, and let the reviewers decide whether to keep it in or not. As you said, it doesn't really hurt; nobody forces you to use the ugly "mdi: mdi:icon" syntax.

2023-05-07 20:05 UTC, guillempages commented
> Nice been looking for something like this! One idea, add etag header support, then we don't need to download images that hasn't been updated , which would save some time and battery :)

@jellyfrog Sounds like a good idea; I wasn't aware of the header. I'll think of that and add the option at some point. I'll also add a parameter "force" (with default false) to the update service, so that a re-download can be forced regardless of etag; there might be use cases where a redownload is desireable.

2023-05-08 03:42 UTC, Unfocused commented
That's a good point - there's a few different things that can be done to avoid unnecessarily downloading an image if you only want an updated file (I wouldn't say I'm an expert when it comes to this area either, but I did work at Mozilla on Firefox, so....)

Unfortunately, you need a skattershot approach (trying a lot of different methods all at once) to the problem, since server behaviour is very inconsistent. 

- ETags, as mentioned above. The ETag is usually a computed hash string of the file, but it's opaque and the value doesn't matter - just whether it's the same or different. Check the `ETag` response header value against the stored value received from the last refresh - if they're the same, then abort the request.
- `If-None-Match` request header is another way of using ETags. You send the ETag you last saw, and if the ETag on the server hasn't changed then it should respond with a `304` code (or if you're using POST/PUT/etc, it should respond with a `412`)
- `Last-Modified` response header. Similar to ETag, but a date (not opaque - the value does matter). Once you get this header, process the date to figure out if you want to abort the request or not. It can be less reliable than ETags, but not all servers support ETags (and if they do, not necessarily for all resources).
- `If-Modified-Since` request header. Similar to `If-None-Match`. If you know the last date the image was refreshed, you can send it via the `If-Modified-Since` header. If the resource hasn't been modified since the specified date, the server should return a `304` code.

2023-05-08 04:11 UTC, Unfocused commented
And while I'm thinking about HTTP headers, for compatibility ideally this would support a User-Agent config option - since some servers will have restrictions on this. 

As for the default, there's a tradeoff in sending something like `ESPHome/2023.5.1` (accurate, useful for logging, but may be rejected) vs mimicking a browser via something like `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0` (better compatibility, except for those servers that alter their behaviour based on which browser the client is claiming to be, which can reduce compatibility. Can also have issues when either too old, or too new). Unfortunately, there's no good universal option here - whatever is picked is guaranteed to break something (including not sending a User-Agent string). Not to mention that it can unfortunately get political. But as an ex-Firefox engineer, my recomendation would be to just use `ESPHome/<VERSION>` as the default, and document the config option with some example alternatives to try if something breaks.

2023-05-08 07:05 UTC, Unfocused commented
About MJPEG, I said:
> But saying that, I agree that it's not likely to work well.

I retract that. Thinking about it, I'm seeing more and more devkits with 8Mb PSRAM (I think I've got at least 3). 8Mb should be more than enough to handle a basic stream. It won't be 1080p or high frame rate, but it'd be enough to make it usable. And security camera monitor is a big use-case - one I'd like to build myself, too. (Just for the record. I'm not saying I think it should necessarily be added in this PR.)

As for the JPEG decoder, amazingly some ESP32 variants have a JPEG decoder built-in. The story I heard was that after adding everything they needed to the ROM, they had some leftover spare space, and decided to fill it up with a few miscellaneous small libraries, and a JPEG decoder just happened to be one of them - and so has the benefit of running faster than code running from the flash. The library, TJpgDec, is also available to be used as a normal library you compile into the flashed firmware: https://components.espressif.com/components/espressif/esp_jpeg

Alternatively, the other library I'm aware of that's specifically optimised for ultra-low memory use is [JPEGDEC](https://github.com/bitbank2/JPEGDEC).

2023-05-08 09:00 UTC, rbray89 commented
> About MJPEG, I said:
> 
> > But saying that, I agree that it's not likely to work well.
> 
> I retract that. Thinking about it, I'm seeing more and more devkits with 8Mb PSRAM (I think I've got at least 3). 8Mb should be more than enough to handle a basic stream. It won't be 1080p or high frame rate, but it'd be enough to make it usable. And security camera monitor is a big use-case - one I'd like to build myself, too. (Just for the record. I'm not saying I think it should necessarily be added in this PR.)
> 
> As for the JPEG decoder, amazingly some ESP32 variants have a JPEG decoder built-in. The story I heard was that after adding everything they needed to the ROM, they had some leftover spare space, and decided to fill it up with a few miscellaneous small libraries, and a JPEG decoder just happened to be one of them - and so has the benefit of running faster than code running from the flash. The library, TJpgDec, is also available to be used as a normal library you compile into the flashed firmware: https://components.espressif.com/components/espressif/esp_jpeg
> 
> Alternatively, the other library I'm aware of that's specifically optimised for ultra-low memory use is [JPEGDEC](https://github.com/bitbank2/JPEGDEC).

Yeah, in aware of at least one other project that accomplishes this: https://github.com/botofancalin/ESP32_Camera_System

2023-05-09 16:18 UTC, Unfocused commented on esphome/components/online_image/__init__.py
> +        cg.add_library("ESP8266HTTPClient", None)
Did you forget the RP2040 platform? No library added for RP2040, but also no guard against using this component on that platform

2023-05-09 16:50 UTC, Unfocused commented on .gitattributes
> +*.png binary
This shouldn't be needed - Git is pretty good at auto-detecting binary files

2023-05-09 21:15 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +        cg.add_library("ESP8266HTTPClient", None)
I copied the http code from the http_request component, and I overlooked the fact that it's forcing ESP framework (i.e. it does not support RP2040). Thanks for pointing this out.

Since I don't have a RP2040 to test, I decided to follow the same approach here, instead of blindly trying to make it work there.

Thanks for pointing this out!

2023-05-09 21:19 UTC, guillempages commented
Ok, I've implemented the ETag validation, and the UserAgent request (and also added the possibility of setting the HTTP timeout).

I've decided against implementing the additional checks explained by @Unfocused on https://github.com/esphome/esphome/pull/4710#issuecomment-1537694120; the main focus of this component is to be able to download images; not to implement a full HTTP downloader ;-)

2023-05-09 21:23 UTC, guillempages commented
Regarding JPEG support, I know about the TJpegDec library, but last time I tried using it in ESPHome (i.e. adding it as a dependency in the python file) I did not succeed. I've learned a little more about library inclusion since then, so it might have been a PEBKAC issue at that time.

Nevertheless, as I mentioned above, the PR is already quite complex as it is. The focus of this PR is to add basic support for runtime images, in the form of PNG images (since that is mainly my use case ;-) ).
Once this PR gets merged (if it ever happens; I haven't had a great experience with the previous iteration of that implementation), I'll try to get JPEG support in.

2023-05-09 22:17 UTC, Jellyfrog commented
> Ok, I've implemented the ETag validation, and the UserAgent request (and also added the possibility of setting the HTTP timeout).
> 
> I've decided against implementing the additional checks explained by @Unfocused on [#4710 (comment)](https://github.com/esphome/esphome/pull/4710#issuecomment-1537694120); the main focus of this component is to be able to download images; not to implement a full HTTP downloader ;-)

I think the Etag implementation is wrong, The client is suppose to send back the next request with the header "If-None-Match: <etag-value>, then the server will either respond with the updated image and 200 OK, or 304 not modified, like so:

```bash
$ curl -sI https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/HTTP_logo.svg/2880px-HTTP_logo.svg.png | grep etag
etag: 327dd26ffcbec27096bcc97363d1c51e

$ curl -sI -H 'If-None-Match: 327dd26ffcbec27096bcc97363d1c51e' https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/HTTP_logo.svg/2880px-HTTP_logo.svg.png
HTTP/2 304
```

2023-05-14 21:18 UTC, guillempages commented
@Jellyfrog "Wrong" is a matter of definition ;-) It was working as it was.

But I agree; if there is a standard defined, it's better to follow that standard. I've implemented the `If-None-Match` header now, and the download is stopped even sooner than it was, so it's a win-win. Thanks for the check/explanation/suggestion!

2023-05-21 06:23 UTC, osos commented
I cant get it to load and display a full size image:

```
[20:23:41][I][online_image:248]: Updating image
[20:23:41][D][online_image:297]: Content Type: image/png
[20:23:41][D][online_image:298]: Content Length: 69868
[20:23:41][D][online_image:299]: ETag: 
[20:23:41][I][online_image:320]: Downloading image from http://mydomain.tld/esp/newimage.php?page=1
[20:23:41][D][online_image:097]: Allocating new buffer of 153600 Bytes...
[20:23:41][D][online_image:098]: Bits per pixel: 16
[20:23:41][E][online_image:106]: allocation failed
[20:23:42][I][online_image:323]: Decoded 69868 bytes
```

Config snippet:
```
online_image:
  - url: "http://mydomain.tld/esp/newimage.php?page=1"
    id: overview_1
    type: RGB565
```

2023-05-21 21:13 UTC, guillempages commented
@osos It looks like it could not allocate a big enough buffer for your image: 
> [20:23:41][E][online_image:106]: allocation failed

Does your device have PSRAM? There should be a line in the configuration dump when the device boots mentioning that.

I've enhanced that log line above to also print the available heap; can you try again to see if that is the issue?

2023-05-22 16:52 UTC, osos commented
> Does your device have PSRAM? There should be a line in the configuration dump when the device boots mentioning that.

`[18:50:03]E (311) psram: PSRAM ID read error: 0xffffffff`

```
[18:50:14][D][online_image:097]: Allocating new buffer of 153600 Bytes...
[18:50:14][D][online_image:098]: Bits per pixel: 16
[18:50:14][E][online_image:106]: allocation failed. Free Heap: 90828 Bytes
```

Hmmm... indeed a heap-size issue. The old PR could download and show the image. Could this not directly stream the output to the display while decoding if allocation fails ?

2023-05-22 19:51 UTC, guillempages commented
@osos The old PR was downloading the image and decoding directly into the display buffer; without any caching. Some reviewers (including Jesse IIRC) mentioned it is dangerous to do the download and decode in the display update lambda, so I decided to rewrite the implementation.

Now the image is downloaded once (or as many times as the user wants, but controlled by the user), and updated into the display in a separate call.
With the current implementation, it is not possible to decode directly into the display; at least in a generic enough way, that would work for all displays and would make the image movable around.

I do see advantages and disadvantages in both ways of doing it (otherwise I would not have implemented both ;-) ), but the current way is the way the project would like to go, if I understood it right.

I'm not sure about your use case; you might want to set the image type to "GRAYSCALE"; it should only use half the memory, and thus would fit in the memory you still have available. 

Another mid-term option would be to add support for RGB332 images, this would also halve the needed memory, at the cost of less color resolution. But this would need extra implementation in the image component and in the online_image component as well; I don't think this will happen "soon".

2023-05-22 20:57 UTC, osos commented
the heap in my case is big enough to cache the .png file but not the RGB565 version of it. Maybe just the png version could be cached, and then decoded directly to the display from the cache?

2023-05-22 21:18 UTC, guillempages commented
I had seen that (you have enough heap to store the PNG data). The problem is that the current implementation is subclassing the `image` class, and the `display_buffer` class (which is the one that actually does the drawing to the display) does not know, that it is a png image; it just expects the `get_color_pixel(x,y)` method in the image to return the right value (i.e. the color for that pixel), and goewss through the whole image pixel-by-pixel.

The previous PR worked differently; in that case the `display_buffer` component asked the `online_image` class "draw yourself into this buffer". It's an either-or implementation; either the image is decoded when downloading or it gets decoded when drawing; this is a decision that needs to be done when implementing the feature; I don't see an easy way of choosing that at runtime. :-(

2023-06-11 21:14 UTC, guillempages commented
I'm reworking the download loop to leverage the standard "loop" functionality, and avoid having to ping the watchdog manually.
Looking good, but still some issues left. (e.g the download is fully asynchronous now, so the callback requested by @osos on https://github.com/esphome/esphome/pull/4710#issuecomment-1515719343 will actually be needed)

2023-07-31 12:07 UTC, haraldpaulsen commented
What would be the correct way to test it now?

I have a ESP32 with integrated waveshare-driver and a 7.5" screen

At the top of my yaml i tried putting:
```
external_components:
  - source: 'github://pr#4710'
    components:
      - online_image
      - image
      - display
```

It fails while compiling:
```
Compiling /data/ramme/.pioenvs/ramme/src/esphome/components/online_image/online_image.cpp.o
In file included from src/esphome/components/online_image/online_image.cpp:3:
src/esphome/components/online_image/online_image.h:5:10: fatal error: esphome/components/image/image.h: No such file or directory
 #include "esphome/components/image/image.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [/data/ramme/.pioenvs/ramme/src/esphome/components/online_image/online_image.cpp.o] Error 1
In file included from src/esphome/components/online_image/image_decoder.cpp:4:
src/esphome/components/online_image/online_image.h:5:10: fatal error: esphome/components/image/image.h: No such file or directory
 #include "esphome/components/image/image.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [/data/ramme/.pioenvs/ramme/src/esphome/components/online_image/image_decoder.cpp.o] Error 1
========================== [FAILED] Took 3.26 seconds ==========================
```

2023-07-31 12:26 UTC, guillempages commented
@haraldpaulsen on esphome 2023.7 there was a change/reporting of internal files, and currently `animation`, `font`, `graph` and `online_image` cannot be used "standalone". 

The easiest workaround is to just add a small "standard" image to your configuration (no need to show it; it just needs to be added). In order to save ROM, I suggest setting the type to `binary_image`

2023-07-31 13:58 UTC, haraldpaulsen commented
> @haraldpaulsen on esphome 2023.7 there was a change/reporting of internal files, and currently `animation`, `font`, `graph` and `online_image` cannot be used "standalone".
> 
> The easiest workaround is to just add a small "standard" image to your configuration (no need to show it; it just needs to be added). In order to save ROM, I suggest setting the type to `binary_image`

Ah, I see.
I tried modifying it now to this:

```
external_components:
  - source: 'github://pr#4710'
    components:
      - display
      - online_image

online_image:
  - url: "https://upload.wikimedia.org/wikipedia/commons/4/47/PNG_transparency_demonstration_1.png"
    id: png_image

image:
  - file: mdi:alert-outline
    id: alert
    resize: 80x80

```
And in the lambda I have:
`it.image(0, 0, id(png_image));
`

But I see no image being displayed, and tcpdumping on the router I can't see any attempts to download the png either.

I also tried hosting a png on my own server without seeing any traffic.

Any other tips?

2023-07-31 14:53 UTC, guillempages commented
@haraldpaulsen if you are not actually using the "mdi:alert" you could use a `resize: 1x1` instead, to save more space. But this is just micro-optimizing.

The (online) image is not downloaded automatically when showing it; you need to do a `component.update: png_image` somewhere in your code. I normally do that in `on_boot` after `api_connected` (as in the example config at the top of this PR).

You can also use an interval, if you expect your image to change. If the web server supports the ETAG header, the image will only be re-downloaded once it actually has changed.

Also, the "display" component from this PR should not be needed in the "external_components" part; there are no changes there (anymore).

2023-07-31 15:03 UTC, haraldpaulsen commented
> The (online) image is not downloaded automatically when showing it; you need to do a `component.update: png_image` somewhere in your code. I normally do that in `on_boot` after `api_connected` (as in the example config at the top of this PR).

Awesome! It works now.

I can't believe I missed the example at the top. Sorry about that.

2023-08-01 08:30 UTC, alfwro13 commented
I would like to use this to display a snapshot from my CCTV system. The snapshot jpg picture is saved in the home assistant media folder. Is there an option to access local files as well?

2023-08-01 10:21 UTC, haraldpaulsen commented
> I would like to use this to display a snapshot from my CCTV system. The snapshot jpg picture is saved in the home assistant media folder. Is there an option to access local files as well?

To the ESP32, any file stored in home assistant is not a local file. It has to go through the network. Can you access the file through http/https somehow? Maybe with the http integration? If so, yes then you should be able to get the snapshot and display it.

https://www.home-assistant.io/integrations/http/#hosting-files

2023-08-01 19:04 UTC, lukastrkan commented
Hi, I really like this PR. Good job!

But I have a question: Can we somehow turn off image dithering? I'm already making dithered images on the server. I think this could help with memory problems on big screens.

2023-08-01 19:16 UTC, guillempages commented
I'm not sure what you mean by "dithering". There is no dithering implementation done in this PR.

The PNG is downloaded as is from the server and decoded into the buffer. If you explicitly specify a size, it will resize the image to that size, but if you don't specify any size, it will use the original image size on the server.

2023-08-01 19:35 UTC, lukastrkan commented
> I'm not sure what you mean by "dithering". There is no dithering implementation done in this PR.
> 
> The PNG is downloaded as is from the server and decoded into the buffer. If you explicitly specify a size, it will resize the image to that size, but if you don't specify any size, it will use the original image size on the server.

There seems to be some sort of image processing happening.
![capybara](https://github.com/esphome/esphome/assets/19746629/7dc8c9ea-5e37-4aa0-b92a-902d08244570)
![image](https://github.com/esphome/esphome/assets/19746629/4ec092fc-3d03-439c-8722-e59d2837be97)

2023-08-01 20:30 UTC, guillempages commented
This looks like a plain color inversion; your display seems to treat white as black and viceversa.

Have you tried using `type: binary_image` in your online_image configuration?

2023-08-01 21:17 UTC, lukastrkan commented
> This looks like a plain color inversion; your display seems to treat white as black and viceversa.
> 
> Have you tried using `type: binary_image` in your online_image configuration?

Yes, I have.

I was able to fix it using `it.image(0, 0, id(png_image), COLOR_OFF, COLOR_ON);`. It's interesting that colors work fine without inverting when using `it.print(0, 0, id(font1), "Hello World!");`.

2023-08-02 08:38 UTC, alfwro13 commented
any chance that jpg images can be displayed using this method?

2023-08-02 11:05 UTC, guillempages commented
> any chance that jpg images can be displayed using this method?

The answer is a clear "yes and no" :-D

This particular PR is focusing on PNG only, since the code changes are already complex enough as they are. When designing this, I tried designing it so that it would be easy to add JPEG support on top (i.e. once it gets merged).

At the moment there are many changes going on in the display area, and some of those changes might make implementing JPEG easier, but will also probably need a big rewrite of the current status of the PR.

So, to answer your question truthfully:
yes, there is a chance that jpg images can be displayed using this method, but only in the mid-term future; not with the current PR.

2023-08-02 12:44 UTC, landonr commented
in the mean time you can use a imageproxy docker to convert your images before you grab them https://www.digitalocean.com/community/tutorials/how-to-serve-next-generation-images-with-imgproxy-using-docker

2023-08-03 20:18 UTC, geiseri commented
I have had very good results with [bitbank2's JPEG ](https://github.com/bitbank2/JPEGDEC) Decoder.  In another project and it is fast enough for my TTGO T-Camera to decode 640x480 images from the camera and scale them down to display on the screen without any drops.  It looks like it's about the same method as Pngle of read/decode/invoke callback.

2023-08-23 18:53 UTC, Shoggomo commented
I propose to check the URL validty at runtime to provide it dynamically. E.g. via home assistant. 
Right now it is checked before compilation.
This is a config that does not work right now:

```
online_image:
  - url: id(image_url)
    id: example_image
    type: binary
    on_download_finished:
      - component.update: eink_display
    on_error:
      - logger.log: "Could not download the image"

text_sensor:
  - platform: template
    id: image_url
    name: "Image URL"
    on_value: 
      then:
        - component.update: example_image
```

![grafik](https://github.com/esphome/esphome/assets/18146212/5c8a5bf6-edd3-4014-98fc-ca52ee7730e1)

2023-08-25 13:24 UTC, guillempages commented
@Shoggomo validation at compile time is a feature, not a bug ;-)

Allowing cross referencing IDs would make the code more complex.

That all said, there *is* a way to accomplish what you want. `online_image` has an action `set_url` that can be used to change the URL at runtime. For example, in the `on_boot` section, you could replace the `update_component: my_image` line with:
```
  on_boot:
    - wait_until: api_connected
    - online_image.set_url:
       url:
         lambda:
            id(image_url).state
       id: my_image
```
You would also do the same in the "on_changed" trigger for the "image_url" sensor. `set_url` automatically calls update on the image; the `update_component` call is then not needed for that image.

(It's been a while since I have implemented and tested that; I might have some syntax error on the example here ;-) )

2023-08-27 11:45 UTC, osos commented
Why am i now getting this:
```
Compiling .pioenvs/infobox-s2/src/esphome/components/online_image/image_decoder.cpp.o
Compiling .pioenvs/infobox-s2/src/esphome/components/online_image/online_image.cpp.o
In file included from src/esphome/components/online_image/online_image.cpp:3:
src/esphome/components/online_image/online_image.h:5:10: fatal error: esphome/components/image/image.h: No such file or directory
 #include "esphome/components/image/image.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from src/esphome/components/online_image/image_decoder.cpp:4:
src/esphome/components/online_image/online_image.h:5:10: fatal error: esphome/components/image/image.h: No such file or directory
 #include "esphome/components/image/image.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pioenvs/infobox-s2/src/main.cpp.o
In file included from src/esphome.h:34,
                 from src/main.cpp:3:
src/esphome/components/online_image/online_image.h:5:10: fatal error: esphome/components/image/image.h: No such file or directory
 #include "esphome/components/image/image.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

yaml:
```
esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

external_components:
  - source: 'github://pr#4710'
    components:
      - online_image
      - display
      - image
```

2023-08-27 12:33 UTC, guillempages commented
@osos: https://github.com/esphome/esphome/pull/4710#issuecomment-1658245444

It's the same root cause as https://github.com/esphome/issues/issues/4719, https://github.com/esphome/issues/issues/4720, https://github.com/esphome/issues/issues/4726 and probably others.

2023-08-27 19:11 UTC, Shoggomo commented
@guillempages thanks, your example almost worked. I had to use a `!lambda` tag. Here's the working code.

```
  on_boot:
    - wait_until: api_connected
    - online_image.set_url:
       url:
         lambda: !lambda |-
                return id(image_url).state.c_str();
       id: my_image
```

2023-08-31 19:45 UTC, bakman2 commented
Last time i tried this, it was quite slow to load the image, is this still the case ?

2023-09-10 13:34 UTC, guillempages commented
> Last time i tried this, it was quite slow to load the image, is this still the case ?

I'm not sure when you tried this, and if it was with this PR or my previous PR. I haven't optimized it for speed though, but just to make it work. In any case, the speed will not be enough for any kind of video stream.

My particular use case requires pretty static images and low update frequency, so performance is not my main concern. I'm open to ideas on how to improve the performance though.

The next "planned" iteration of the PR will try storing the coded image, and decoding on the fly when drawing. I'm not sure how it will affect performance; depends on the frequency of downloading vs. display updating I assume. But this should improve the memory usage and help with devices without PSRAM.

No promises on when that will be though; it depends on some other work by @ayufan

2023-09-11 09:33 UTC, alfwro13 commented
I have noticed "[Add support for multiple image types](https://github.com/esphome/esphome/pull/4710/commits/2cc41ad83f475c0bb962a422ab0979fa78fec888)" Does this mean that formats other than PNG will be supported? Or is that just a ground work for a future work?

2023-10-04 15:26 UTC, janpapenbrock commented on esphome/components/online_image/__init__.py
> +    if CORE.is_esp8266 and not config[CONF_ESP8266_DISABLE_SSL_SUPPORT]:
I'm aware that this is still under construction, but I thought I'd give it a test, as I'm excited to use this for a pixel-art display :)

No luck though with the testing, as it is throwing a compilation error for me on an **ESP8266**:

```
  File "/data/external_components/b8a7b76b/esphome/components/online_image/__init__.py", line 137, in to_code
    if CORE.is_esp8266 and not config[CONF_ESP8266_DISABLE_SSL_SUPPORT]:
KeyError: 'esp8266_disable_ssl_support'
```

If I understand this correctly, then a config definition for `CONF_ESP8266_DISABLE_SSL_SUPPORT` might be missing in the `HTTP Request options` maybe? Not familiar with the codebase at all :)

If I can further support with debugging / testing, happy to do so.

2023-10-04 16:12 UTC, bakman2 commented
> > Last time i tried this, it was quite slow to load the image, is this still the case ?
> 
> I'm not sure when you tried this, and if it was with this PR or my previous PR. I haven't optimized it for speed though, but just to make it work. In any case, the speed will not be enough for any kind of video stream.

Ok hear me out :)

Liligo TTGO T5 4.7 - epaper with touch screen. 

What I wanted to do - have the thing sleep (it's static because of epaper), upon touch:

using node-red, render a webpage that displays an interface with buttons 
create screenshot
send screenshot to screen

upon touch of certain button (screen x,y) - render another dynamic webpage, screenshot, send to screen
etc.. etc..

This way I could create a controller for anything while running on batteries for a long time. 
but at the time i tried it, loading took either all memory or it took a long time.

2023-10-14 14:02 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +    if CORE.is_esp8266 and not config[CONF_ESP8266_DISABLE_SSL_SUPPORT]:
hm. I haven't tested it with ESP8266, since I don't have any device there. This part of the code was copy&pasted from the http_request component a while ago. I'm not sure if there have been changes on that part of the code that broke it :-(

I'd have to look into it in detail, but currenlty RL is taking most of my time :-(

2023-10-14 14:20 UTC, guillempages commented
@bakman2 I now understand your use case. But I'm not sure it can be made as performat as you would need it to. Basically you would need almost immediate refresh of the image whenever the button is touched. 
With the current implementation, the image is requested (via HTTP) from the server, it gets downloaded, it then gets decoded, and only after it's decoded (and kept in memory), the display lambda will actually display it on screen.

At some point in the future, once @ayufan 's double-buffering changes and display optimizations are merged in, I might change the code to actually store the compressed image, and decode "online" whenever it needs to be shown. In some cases this might make the displaying faster (since it is directly decoded into the display, instead of into memory and then copied over to the display), and for most images would also reduce the memory footprint.
But there is no clear roadmap/timeline when this would be done ATM. 

BTW, I also have a LilyGO T5 4.7 display (without the touchscreen), and I just tried the timings: it took ~35 seconds to just *download* the image; without doing any processing on it, and then another 15 seconds to actually decode it and display it. The decode and display part can probably be optimized, but I'm not really sure what can be done to optimize the download time. (Ok, I confess, that it is a 770KB full-color image, which is then processed to grayscale onboard. Probably a simple black&white image would be much smaller and would download faster).

2023-11-05 04:33 UTC, NonaSuomy commented
> in the mean time you can use a imageproxy docker to convert your images before you grab them https://www.digitalocean.com/community/tutorials/how-to-serve-next-generation-images-with-imgproxy-using-docker

Attempted this seems to explode

Docker Compose for Imgproxy
```yaml
# Imgproxy docker container for ESPHome
version: '3'
networks:
  dhcp:
    name: "dbrv700"
    external: true

services:
  imgproxy:
    restart: no
    image: darthsim/imgproxy:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=false"
    container_name: imgproxy
    hostname: "imgproxy"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/lib/libvirt/images/usb001/docker-storage/imgproxy/www:/home:cached
    mac_address: "9e:de:ad:be:ef:42"
    networks:
      - dhcp
    expose:
      - 8080
    healthcheck:
      test: ["CMD", "imgproxy", "health"]
    environment:
      ### See:
      ### https://docs.imgproxy.net/configuration

      ### log and debug
      IMGPROXY_LOG_LEVEL: "warn"
      IMGPROXY_ENABLE_DEBUG_HEADERS: "false"
      IMGPROXY_DEVELOPMENT_ERRORS_MODE: "false"
      IMGPROXY_REPORT_DOWNLOADING_ERRORS: "false"

      ### timeouts
      IMGPROXY_READ_TIMEOUT: 10
      IMGPROXY_WRITE_TIMEOUT: 10
      IMGPROXY_DOWNLOAD_TIMEOUT: 10
      IMGPROXY_KEEP_ALIVE_TIMEOUT: 300
      IMGPROXY_MAX_SRC_FILE_SIZE: 20971520 # 20MB

      ### image source
      #IMGPROXY_TTL: 2592000 # client-side cache time is 30 days
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_SO_REUSEPORT: "true"
      IMGPROXY_IGNORE_SSL_VERIFICATION: "true"
      #IMGPROXY_LOCAL_FILESYSTEM_ROOT: /home
      #IMGPROXY_SKIP_PROCESSING_FORMATS: "svg,webp,avif"

      ### presets
      #IMGPROXY_AUTO_ROTATE: "true"
      #IMGPROXY_WATERMARK_PATH: /home/noimage_thumb.jpg
      #IMGPROXY_PRESETS: default=resizing_type:fit/gravity:sm,logo=watermark:0.5:soea:10:10:0.15,center_logo=watermark:0.3:ce:0:0:0.3

      ### compression
      #IMGPROXY_STRIP_METADATA: "true"
      #IMGPROXY_STRIP_COLOR_PROFILE: "true"
      #IMGPROXY_FORMAT_QUALITY: jpeg=80,webp=70,avif=50
      #IMGPROXY_JPEG_PROGRESSIVE: "false"
      #IMGPROXY_PNG_INTERLACED: "false"
      #IMGPROXY_PNG_QUANTIZATION_COLORS: 128
      #IMGPROXY_PNG_QUANTIZE: "false"
      #IMGPROXY_MAX_ANIMATION_FRAMES: 64
      #IMGPROXY_GZIP_COMPRESSION: 0
      #IMGPROXY_AVIF_SPEED: 8

      ### For URL signature
      # IMGPROXY_KEY: "<your key>"
      # IMGPROXY_SALT: "<your salt>"
      # IMGPROXY_SIGNATURE_SIZE: 32
```

base64 converter
https://www.base64encode.org/
Convert ESP IP:Port to Base64
http://10.0.1.101:8081 > aHR0cDovLzEwLjAuMS4xMDE6ODA4MQ==
Drop the ==
See final URL below...

ESPHome YAML
```yaml
# TTGO-Camera Plus 001
esphome:
  name: ttgo-camera-plus-001
  friendly_name: ttgo-camera-plus-001
  on_boot:
    - wait_until: api.connected

esp32:
  board: esp32dev
  framework:
    type: arduino

image:
  - file: mdi:alert-outline
    id: alert
    resize: 1x1

external_components:
  # Online Image Display  
  - source: 'github://pr#4710'
    components: [ online_image ]

# Enable logging
logger:
  #level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key007

ota:
  password: !secret ota_pass007

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: !secret use_address_wifi007
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "TTGO-Camera-Plus-001"
    password: !secret fallbackhotspot007

captive_portal:

web_server:

# TTGO Camera Plus
# OV2640 2Megapixel
esp32_camera:
  external_clock:
    pin: GPIO4
    frequency: 20MHz
  i2c_pins:
    sda: GPIO18
    scl: GPIO23
  data_pins: [GPIO34, GPIO13, GPIO26, GPIO35, GPIO39, GPIO38, GPIO37, GPIO36]
  vsync_pin: GPIO5
  href_pin: GPIO27
  pixel_clock_pin: GPIO25
  vertical_flip: false
  horizontal_mirror: false

# Image settings
  name: TTGOCameraPlus001

# Camera Web Server
esp32_camera_web_server:
  #- port: 8080
  #  mode: stream
  - port: 8081
    mode: snapshot

# ST7789 Display
# IPS Panel 1.3 Inch 260ppi 240x240 16-bit full color pixels 
spi:
  clk_pin: GPIO21
  mosi_pin: GPIO19
  miso_pin: GPIO22

display:
  - platform: st7789v
    id: st7789_display
    model: Adafruit_Funhouse 240x240
    backlight_pin: GPIO2
    cs_pin: GPIO12
    dc_pin: GPIO15
    reset_pin: GPIO23
    lambda: |-
      it.image(0, 0, id(example_image));

online_image:
  # Test URL that worked.
  #url: "https://www.kasandbox.org/programming-images/avatars/cs-hopper-cool.png"
  # http://10.0.1.100:8080/sig is the imgproxy server 
  # /Base64 conversion URL of ESPHome snapshot server 
  # .png conversion format from .jpg
  url: "http://10.0.1.100:8080/sig/aHR0cDovLzEwLjAuMS4xMDE6ODA4MQ.png"
  id: example_image
  type: RGB565
  on_download_finished:
    - component.update: st7789_display
  #on_error:
  #  - logger.log "Could not download the image"
  # ^-- This doesn't work

# Update the displayed URL image every nth min
interval:
  - interval: 2min
    then:
    - component.update: example_image
    #- component.update: st7789_display <-- removed as it's already in the example_image process.
```

LOG - After trying to "Updating image" it restarts.
```
[I][online_image:348]: Updating image
E (91797) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (91797) task_wdt:  - loopTask (CPU 1)
E (91797) task_wdt: Tasks currently running:
E (91797) task_wdt: CPU 0: IDLE
E (91797) task_wdt: CPU 1: IDLE
E (91797) task_wdt: Aborting.

abort() was called at PC 0x400fe790 on core 0

Backtrace:0x40083aad:0x3ffbe9fc |<-CORRUPTED

ELF file SHA256: 0000000000000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
```

2023-11-05 14:57 UTC, NonaSuomy commented
> @bakman2 I now understand your use case. But I'm not sure it can be made as performat as you would need it to. Basically you would need almost immediate refresh of the image whenever the button is touched. With the current implementation, the image is requested (via HTTP) from the server, it gets downloaded, it then gets decoded, and only after it's decoded (and kept in memory), the display lambda will actually display it on screen.
> 
> At some point in the future, once @ayufan 's double-buffering changes and display optimizations are merged in, I might change the code to actually store the compressed image, and decode "online" whenever it needs to be shown. In some cases this might make the displaying faster (since it is directly decoded into the display, instead of into memory and then copied over to the display), and for most images would also reduce the memory footprint. But there is no clear roadmap/timeline when this would be done ATM.
> 
> BTW, I also have a LilyGO T5 4.7 display (without the touchscreen), and I just tried the timings: it took ~35 seconds to just _download_ the image; without doing any processing on it, and then another 15 seconds to actually decode it and display it. The decode and display part can probably be optimized, but I'm not really sure what can be done to optimize the download time. (Ok, I confess, that it is a 770KB full-color image, which is then processed to grayscale onboard. Probably a simple black&white image would be much smaller and would download faster).

https://github.com/atomic14/esp32-tv

2023-11-07 03:23 UTC, NonaSuomy commented
@guillempages are you able to load that png image above from the url or of a service you know works properly?

2023-11-11 20:44 UTC, guillempages commented
@NonaSuomy I've just tried downloading the image from https://i.ibb.co/1mp3SkP/image.png and showing it on my display (Lilygo T-Display-S3) and it works fine.

In my case I'm not continuously updating the image with an interval, but I only call "update_component" once to download the image after the api connected call.
I understand that in your use-case you need to update the image regularly; but just to test, you might want to disable the interval, and explicitly call "update_component" once the web server is actually up and running.

It might be that reading the camera, sending the data to your proxy image server, and reading it back from the ESP is too much for the device :-(

2023-11-12 13:16 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +    if CORE.is_esp8266 and not config[CONF_ESP8266_DISABLE_SSL_SUPPORT]:
@janpapenbrock Sorry it took a while. I've checked the code, and you are right, the option (with the default) was missing on the schema. I've updated the code, so that there should be a default now.
I don't have any ESP8266, so I cannot fully test that.
Would you be so kind and try again with the latest version of this PR?

2023-11-15 13:29 UTC, jhbruhn commented
I'm currently testing this PR to use with a flexible matrix display. I am using the new Text template component to set an image URL, but unfortunately the application always crashes when sending the second URL:
```

[I][ota:117]: Boot seems successful, resetting boot loop counter.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[D][text:050]: 'Image URL' - Setting text value: http://192.168.178.34:8032/unsafe/192.168.178.34:8031/png,64x64/https://images.pexels.com/photos/268941/pexels-photo-268941.jpeg?cs=srgb&dl=pexels-pixabay-268941.jpg&fm=jpg
[D][text:016]: 'Image URL': Sending state http://192.168.178.34:8032/unsafe/192.168.178.34:8031/png,64x64/https://images.pexels.com/photos/268941/pexels-photo-268941.jpeg?cs=srgb&dl=pexels-pixabay-268941.jpg&fm=jpg
[I][online_image:348]: Updating image
[D][online_image:384]: Content Type: image/png
[D][online_image:385]: Content Length: 9525
[D][online_image:386]: ETag: "8a1374879f08990bf8759f832924b642167918c9"
[I][online_image:408]: Downloading image from http://192.168.178.34:8032/unsafe/192.168.178.34:8031/png,64x64/https://images.pexels.com/photos/268941/pexels-photo-268941.jpeg?cs=srgb&dl=pexels-pixabay-268941.jpg&fm=jpg
[W][component:214]: Component api took a long time for an operation (1.53 s).
[W][component:215]: Components should block for at most 20-30ms.
[D][online_image:154]: Allocating new buffer of 8192 Bytes...
[D][online_image:161]: New size: (64, 64)
[D][online_image:178]: Image fully downloaded
[D][text:050]: 'Image URL' - Setting text value: http://192.168.178.34:8032/unsafe/192.168.178.34:8031/png,64x64/https://jhbruhn.de/posts/moonboot/banks.png
[D][text:016]: 'Image URL': Sending state http://192.168.178.34:8032/unsafe/192.168.178.34:8031/png,64x64/https://jhbruhn.de/posts/moonboot/banks.png
[I][online_image:348]: Updating image
[D][online_image:384]: Content Type: image/png
[D][online_image:385]: Content Length: 1987
[D][online_image:386]: ETag: "b81fd8e5cfb05ecdf54095080183c9abf9839409"
[I][online_image:408]: Downloading image from http://192.168.178.34:8032/unsafe/192.168.178.34:8031/png,64x64/https://jhbruhn.de/posts/moonboot/banks.png
[W][component:214]: Component api took a long time for an operation (0.12 s).
[W][component:215]: Components should block for at most 20-30ms.
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400eaabd  PS      : 0x00060530  A0      : 0x800db4e6  A1      : 0x3ffb2690  
A2      : 0x00000000  A3      : 0x3ffc8fac  A4      : 0x000007c3  A5      : 0x3ffefb28  
A6      : 0x00000000  A7      : 0x003fffff  A8      : 0x3ffc976e  A9      : 0x3ffb2710  
A10     : 0x00000082  A11     : 0x4004667f  A12     : 0x3ffb270c  A13     : 0x3ffc3a68  
A14     : 0x00060120  A15     : 0x00000001  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000024  LBEG    : 0x40084799  LEND    : 0x400847a1  LCOUNT  : 0x00000026  


Backtrace:0x400eaaba:0x3ffb26900x400db4e3:0x3ffb2730 0x400db41a:0x3ffb2770 0x401870cd:0x3ffb2790 0x4018718d:0x3ffb27b0 0x400df80c:0x3ffb27d0 0x400e1dae:0x3ffb2800 0x400ee799:0x3ffb2820 




ELF file SHA256: 0000000000000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
```

My YAML looks like this:

```yaml
esphome:
  name: matrix-1
  friendly_name: Matrix
  platformio_options:
    lib_deps:
      - SPI
      - Wire
      - Adafruit BusIO
      - adafruit/Adafruit GFX Library
      - https://github.com/TillFleisch/ESP32-HUB75-MatrixPanel-DMA#optional_logging

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  common-base: !include common/common-base.yaml    
  #web-base: !include common/web-base.yaml    
  #ble-gateway: !include common/ble-gateway.yaml

external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main
  - source: github://pr#4710
    components:
      - online_image
      - image
    refresh: 0s

image:
  - file: mdi:alert-outline
    id: alert
    resize: 80x80

online_image:
  - url: "https://example.com/baubs.png"
    id: coverimage
    type: RGB565
    buffer_size: 16384
    resize: 64x64
    on_download_finished:
      - component.update: matrix
    on_error:
      - logger.log: "Could not download the image"

text:
  - platform: template
    name: Image URL
    max_length: 255
    id: url
    mode: text
    optimistic: true
    on_value:
      then:
        - online_image.set_url:
            id: coverimage
            url: !lambda return id(url).state.c_str();

display:
  - platform: matrix_display
    id: matrix
    width: 64
    height: 64
    E_pin: 18
    lambda: |-
      if (!id(url).state.empty()) {
        it.image(0, 0, id(coverimage));
      }
```

Do you have an idea why the LoadProhibited exception occurs? I am guessing some buffer reuse from the first image download?

2023-11-20 18:25 UTC, borodihin commented
How to convert an image to supported format with imagemagick?

2023-11-22 20:31 UTC, NonaSuomy commented
Failed config

online_image: [source /config/ttgo-camera-plus.yaml:653]
  
  This feature is incompatible with esp-idf.

2023-11-30 20:10 UTC, fawick commented
This PR can not be used with esphome 2023.11.6, as there is an error during C++ code generation. 
See my initial report on https://github.com/esphome/issues/issues/5177 for details.

2023-11-30 20:21 UTC, guillempages commented
@fawick there was an unrelated change to the display component, which is already merged to dev but not released yet, and changed the way displays compile. 

I renewed this PR to the latest dev yesterday, and this those changes are probably included when you use it, but not the rest of the related chances.

As a workaround, until 2023.12 is released, can you also use the component "inkplate6" from this PR? I'm not 100% sure this will work, you might need to add additional components as well (e.g. display?). All I can say is, that it works for me with an inkplate10 and using dev instead of 2023.11.

2023-11-30 20:29 UTC, fawick commented
Thank you for your fast reply, @guillempages, and for putting me on the right track!

I was able to restore function by reducing 

```yaml
external_components:
   - source: 'github://pr#4710'
     components: [ online_image, image, display ]
```

to

```yaml
external_components:
   - source: 'github://pr#4710'
     components: [ online_image ]
```

2023-12-05 07:57 UTC, wardozer commented
whenever I add, component update on the image or even on boot, the system keep disconnecting and connecting to the API, any idea why this is happening?

```
online_image:
  - url: "https://www.example.org/image.png"
    id: example_image
    type: RGB565
    on_download_finished:
      - component.update: my_display
    on_error:
      - logger.log: "Could not download the image"
```

2023-12-18 19:17 UTC, dmagyar commented
I'm trying to load a 240x280 PNG and I'm running out of heap :( I understand RAM is not great on ESP32 but is is possible to use PSRAM for the image decoding?

2023-12-20 19:38 UTC, guillempages commented
> whenever I add, component update on the image or even on boot, the system keep disconnecting and connecting to the API, any idea why this is happening?
> 
> ```
> online_image:
>   - url: "https://www.example.org/image.png"
>     id: example_image
>     type: RGB565
>     on_download_finished:
>       - component.update: my_display
>     on_error:
>       - logger.log: "Could not download the image"
> ```

I haven't had this happen to me, so I'm not sure what it can be. Maybe the server you are trying to get the image from is too slow/takes too long to respond or is going into some timeout, and then the internal watchdog hits :-(

2023-12-20 19:42 UTC, guillempages commented
> I'm trying to load a 240x280 PNG and I'm running out of heap :( I understand RAM is not great on ESP32 but is is possible to use PSRAM for the image decoding?

@dmagyar Actually the code is configured to use psram if available. Are you sure that your psram is configured for your board? Does the initial configuration dump print the `psram` line with the expected value?
I have different displays with psram, and on all of them it is using it for me (one of the images I'm downloading is a 800x600 px image, and it is working for me)

2024-01-08 15:34 UTC, nagyrobi commented
Is the `url` templatable? So we could easily change the URL from a `text` or `text_sensor` component from HA?

2024-01-10 21:50 UTC, MartinLindenau commented
I like to use the online image component, but I miss the dither method from the original image component.

2024-01-13 15:56 UTC, guillempages commented
@nagyrobi no, the URL is not templateable, but there is a way to do what you want: there is an `update_url` action, that you could call in an `on_change` trigger on your text.

@MartinLindenau the dithering in the "standard" image component is done at compile time using python libraries on the original image. To do dithering here, the dithering algorithm would need to be implemented in the ESPHome code itself; which would increase footprint and decoding time. And it is way beyond my level of expertise anyway ;-)

Once (if ever) this PR gets merged, someone with more image processing knowledge can take it and implement dithering. For the purposes of this particular PR, dithering is out of scope

2024-01-14 16:58 UTC, velijv commented
Awesome updates! 💯

I have modified the url with the new text component and your components lambda call: 

```
text:  # https://esphome.io/components/text/
  - platform: template
    name: Online image
    icon: mdi:image-frame
    restore_value: false
    id: online_image_source
    entity_category: config
    min_length: 0
    max_length: 255
    mode: text
    optimistic: true
    set_action:
      then:
         - lambda: |-
              auto url = x.c_str();
              id(example_image)->set_url(url);
         - component.update: example_image
         - component.update: lcd
```
<img width="360" alt="Screenshot 2024-01-14 at 18 56 03" src="https://github.com/esphome/esphome/assets/5716539/f39e46dc-8dd8-48d4-96e5-689bfeede434">

This way i can set the url from home assistant. 

Also I am using [timthumb.php ](https://github.com/GabrielGil/TimThumb)to convert JPG and GIF to PNG and resize it before sending it, so it updates almost instantly and supports all. 😍

2024-01-16 00:37 UTC, NonaSuomy commented
@velijv Can you do a write up how you accomplished that? Where did you put the files etc?

2024-01-18 04:37 UTC, landonr commented
# Online Media Player Image

## home assistant sensor
 - needs an image proxy docker running to resize the image 
 - https://hub.docker.com/r/darthsim/imgproxy/

```yaml
template:
  - sensor:
      - name: Media Player Image Proxy URL
        state: |
          {{ 
            state_attr(states.sensor.active_player.state, "entity_picture") | base64_encode
          }}
        attributes:
          url: >
            {% set homeAssistantURL = "http://172.16.1.67:8123" %}
            {% set imageProxyURL = "172.16.1.23:8080/insecure/rs:fill:170:170/" %}
            {% set url = homeAssistantURL + state_attr(states.sensor.active_player.state, "entity_picture") %}
            {% set base64url_encoded_url = (url | base64_encode) | replace('+', '-') | replace('/', '_') | replace('=', '') %}
            {{ imageProxyURL + base64url_encoded_url }}
```
## esphome sensor
```yaml
text_sensor:
  - platform: homeassistant
    id: entity_picture
    entity_id: sensor.beam_picture_proxy
    attribute: url
    on_value:
      then:
      - online_image.set_url:
          id: media_player_image
          # prepend https:// because it has trouble decoding the url otherwise
          url: !lambda 'return ("https://" + x).c_str();'
```
the remote has a `active_player` sensor which reports which media player it's focused on. The Home Assistant template sensor uses that to create a resized image url using the image proxy docker 

@guillempages with this setup I had to expose my imageproxy docker to the web to get https working because I couldn't load http images

![IMG_0844 mov](https://github.com/esphome/esphome/assets/2607659/67b940e4-a96a-452c-8fe6-5f783ffb13b6)

2024-01-18 05:43 UTC, landonr commented
I made an addon for Image Proxy to make it easy for home assistant users. Once its running you can access homeassistant.local:8080 to resize images
https://github.com/landonr/home-assistant-imgproxy

2024-02-06 07:48 UTC, velijv commented
> @velijv Can you do a write up how you accomplished that? Where you put the timthumb.php files etc, Full ESPHome/HomeAssistant code, etc?

Timthumb i host on my other local Raspberry Pi with just Apache. No special code for home assistant, the ESPHome yaml exposes the text input by itself to device. :) 

No exposing the url/port to public needed. The text input can take both local and external sources. 

```yaml 
substitutions:
  # General
  friendly_name: 'ESPHome Display'
  # Display related
  local_image_size: '200x200'
  local_image_format: "RGB565"
  local_image_use_transparency: "true"
  BOARD_TFT_WIDTH: "240"
  BOARD_TFT_HEIGHT: "240"
  # image sources
  chatgpt_url: "http://coral.local/timthumb.php?src=http://homeassistant.local:8123/local/gpt/snap.png"
  camera_1_url: "http://coral.local/timthumb.php?src=http://camera-cased.local:8081"
  camera_2_url: "http://coral.local/timthumb.php?src=http://camera-servo.local:8081"
  system_url: "http://coral.local/timthumb.php?src=http://homeassistant.local:8123/local/nspanel/system.png"
  blank_url: "http://homeassistant.local:8123/local/blank.png"

online_image:
  - url: ${chatgpt_url}
    id: example_image
    format: PNG
    resize: ${BOARD_TFT_WIDTH}x${BOARD_TFT_HEIGHT} 
    type: ${local_image_format}
    use_transparency: true 
    useragent: ${friendly_name}
    on_download_finished:
      - lambda: |-
            // this is the display backlight
            id(backlight).turn_on().set_brightness(1).perform();
            // this is the display page that shows online image
            id(lcd).show_page(id(page_online_image));
            // this is the display
            id(lcd).update();
    on_error:
      - lambda: |-
          ESP_LOGW("online_image","could not download");

text:
  - platform: template
    name: Online image
    icon: mdi:image-frame
    restore_value: false
    id: online_image_source
    min_length: 0
    max_length: 255
    mode: text
    update_interval: never
    set_action:
      then:
         - lambda: |-
              auto url = x.c_str();
              id(example_image)->set_url(url);
         - component.update: example_image
```

2024-02-08 23:48 UTC, adrianrdzv commented
@landonr @velijv Great work! It works perfectly. However, I'm trying to use the entity_picture of the Spotify player which is a very long url, and states in home assistant (text) only allows 255 max characters. Any idea on how to solve this issue?

2024-02-09 23:14 UTC, adrianrdzv commented
So I moved the url construction to esphome to avoid having long sensor states. However now it seems I'm having issues with the encoding:
```
globals:
  - id: ha_url
    type: std::string
    initial_value: '"http://192.168.86.246:8123"'
  - id: imgproxy_url
    type: std::string
    initial_value: '"http://192.168.86.2:3434/insecure/"'
  - id: imgproxy_cover_art_filters
    type: std::string
    initial_value: '"rs:fill:320:170/plain/"'
text_sensor:
  - platform: homeassistant
    id: spotify_image_url
    entity_id: sensor.spotify_image_url # Looks like this: /api/media_player_proxy/media_player.spotify_username%3Ftoken=434sad56a4d5as4d6saasdae9d9bc5b63b06213b98189c43242236c48c8f%26cache=4a52bc342ae1fb
    on_value:
      then:
        - lambda: |-
            auto url = id(imgproxy_url) + id(imgproxy_cover_art_filters) + id(ha_url) + to_string(x) + "@png";
            id(cover_art)->set_url(url.c_str());
        - component.update: cover_art
```

Sometimes it works, and sometimes it doesn't. I have no idea why some images work and some don't. I believe there is some random encoding issue with the url and the "%" character. Practically the url is always the same, just the string after `cache=` is what changes.

```
[17:12:43][I][online_image:348]: Updating image
[17:12:43][E][online_image:353]: Could not download image from . Connection failed: 0
```

2024-02-10 00:05 UTC, adrianrdzv commented
Ok so I "made it work" following the example from @landonr. I still get every now on then some errors but it's more stable now. If anyone wants to build this Spotify "Now Playing":

![2024-02-09 17 57 42](https://github.com/esphome/esphome/assets/4851625/965a272a-b9e6-4d83-8f1b-5db09a1840c8)

HA:
```
template
  - sensor
    - name: Spotify Image URL
     unique_id: spotify_image_url
     state: >
        {% set imageUrl = state_attr('media_player.spotify_username', 'entity_picture') %}
        {{ (imageUrl | replace('?', '%3F') | replace('&', '%26') )  }}
```
esp:
```
globals:
  - id: ha_url
    type: std::string
    initial_value: '"http://192.168.86.246:8123"'
  - id: imgproxy_url
    type: std::string
    initial_value: '"http://192.168.86.2:3434/insecure/"'
  - id: imgproxy_cover_art_filters
    type: std::string
    initial_value: '"rs:fill:320:170/plain/"'
  - id: imgproxy_cover_art_blur_filters
    type: std::string
    initial_value: '"rs:fill:320:28/c:640:105/bl:10/plain/"'

display:
  - platform: tdisplays3
    id: s3
    update_interval: 0.2s
    rotation: 270
    lambda: |-
      auto black = Color(0, 0, 0);
      it.image(0, 0, id(cover_art));
      it.image(0, 71, id(cover_art_blur));
      std::string val = id(title).state;
      it.printf(161, 86, id(text_font), black, TextAlign::CENTER, "%s", val.c_str());
      it.printf(160, 85, id(text_font), TextAlign::CENTER, "%s", val.c_str());

text_sensor:
  - platform: homeassistant
    id: title
    entity_id: media_player.spotify_username
    attribute: media_title
  - platform: homeassistant
    id: spotify_image_url
    entity_id: sensor.spotify_image_url
    on_value:
      then:
      - online_image.set_url:
          id: cover_art
          url: !lambda 'return (id(imgproxy_url) + id(imgproxy_cover_art_filters) + id(ha_url) + to_string(x) + "@png").c_str();'
      - online_image.set_url:
          id: cover_art_blur
          url: !lambda 'return (id(imgproxy_url) + id(imgproxy_cover_art_blur_filters) + id(ha_url) + to_string(x) + "@png").c_str();'
```

2024-02-13 11:53 UTC, velijv commented
@adrianrdzv 
> @landonr @velijv Great work! It works perfectly. However, I'm trying to use the entity_picture of the Spotify player which is a very long url, and states in home assistant (text) only allows 255 max characters. Any idea on how to solve this issue?

As i dont want to hardcode and recompile every time, and use the `text:` entity which allows dynamic setting - I am installing [yourls](https://yourls.org/) url shortener locally 😆

2024-02-13 13:13 UTC, Nornode commented
How likely is this to reach the main branch and be released? 
I have been waiting for this functionality and would prefer to implement this for production use when it's released.

2024-02-16 03:46 UTC, PaulBiod commented
Hi,
I'm having hard time making this work.
At first, I tried with image component from esphome and it prints successfully my image.
Then, I tried with online_image, but it isn't working.

My code : 

`external_components:
   - source: 'github://pr#4710'
     components: [ online_image ]`
     
`online_image:
  - url: "http://192.168.1.135:8123/local/bambulab/image.png"
    id: my_image
    type: RGB565
    resize: 204x204
    on_download_finished:
      - component.update: my_display
    on_error:
      - logger.log: "Could not download the image"`

And the errors after compiling : 
[04:42:03][E][online_image:163]: allocation failed. Free Heap: 93128 Bytes
[04:42:03][E][online_image:198]: Error when decoding image.

The metadata of my image : 
file_name
image.png
file_size
13 kB
file_type
PNG
file_type_extension
png
mime_type
image/png
image_width
512
image_height
512
bit_depth
8
color_type
RGB with Alpha
compression
Deflate/Inflate
filter
Adaptive
interlace
Noninterlaced
image_size
512x512
megapixels
0.262
category
image

Thanks

2024-02-16 13:32 UTC, guillempages commented
@Nornode It doesn't really depend on me ;-) It's already my second try on implementing this functionality, the first PR was open for almost one year IIRC before I decided to rewrite as it is now, and this has also been open for almost one year (although it was as "draft" for a while, while some other previous PRs were not yet merged).

This would need an in-depth review by some of the core maintainers, to be able to assess whether it can be merged with some small changes, or whether a bigger rewrite would be needed (or whether it is already good as-is, but I don't expect that to be the case :-D)

2024-02-16 13:43 UTC, guillempages commented
@PaulBiod does your device have PSRAM? What do the initial (configuration) logs about PSRAM say?

From the error log you posted:
> [04:42:03][E][online_image:163]: allocation failed. Free Heap: 93128 Bytes
> [04:42:03][E][online_image:198]: Error when decoding image.

it looks as if it did not have enough RAM to allocate the necessary buffer. After resizing, your image is 204x204@16bpp, which gives ~83KB. The log claims that you do have enough memory (~93KB), but it is so close, that it might be that there is no block that is big enough to hold the buffer contiguously.

The "offline" images are stored in ROM, not RAM, and this most probably explains why the same image works as precompiled but not at runtime.

2024-02-16 13:51 UTC, PaulBiod commented
> @PaulBiod does your device have PSRAM? What do the initial (configuration) logs about PSRAM say?
> 
> From the error log you posted:
> 
> > [04:42:03][E][online_image:163]: allocation failed. Free Heap: 93128 Bytes
> > [04:42:03][E][online_image:198]: Error when decoding image.
> 
> it looks as if it did not have enough RAM to allocate the necessary buffer. After resizing, your image is 204x204@16bpp, which gives ~83KB. The log claims that you do have enough memory (~93KB), but it is so close, that it might be that there is no block that is big enough to hold the buffer contiguously.
> 
> The "offline" images are stored in ROM, not RAM, and this most probably explains why the same image works as precompiled but not at runtime.

Hi @guillempages 
At first thanks for replying.
About psram, I activated it, but I don't know if my wroom32 has some.
psram:
  mode: octal
  speed: 80MHz
I just tried with a 2ko image, and same result : 
![image](https://github.com/esphome/esphome/assets/28720176/d85bd491-73f8-4a13-ae8f-38a90ca481c9)
I added the logs if you wanna drop an eye.
Many thanks
[logs_display-bambulab_run.txt](https://github.com/esphome/esphome/files/14311775/logs_display-bambulab_run.txt)

2024-03-02 14:51 UTC, guillempages commented
@PaulBiod sorry, I somehow forgot to reply :-(

I've looked at the logs, and I can't see anything about the PSRAM configuration. On my deivces, when the API connects, I get a log of all the configuration; which seems to be missing on your log. And in (my) logs, I can see 
```
[15:42:28][C][psram:020]: PSRAM:
[15:42:28][C][psram:021]:   Available: YES
[15:42:28][C][psram:024]:   Size: 8191 KB
```
(or `Available: NO` on the boards that do not have PSRAM or it is wrongly configured).

The needed memory is not related to the *original* size of the image (i.e. the bytes that need to be downloaded), but to the *decoded* size of the image.
So for your configuration
```
image: 
  # ...
  type: RGB565
  resize: 204x204
```
The needed memory is 204x204x2 = 83.232 bytes *in a single block*. Your log claims `allocation failed. Free Heap: 105924 Bytes`; which sounds like it should be enough, but most probably there is no block of contiguous memory that is big enough. E.g. if you would have 4 blocks of 50KB; with some already allocated memory in between, you would have 200KB Free memory, but this would still fail, since it cannot get a continuous buffer that is big enough to contain the decoded image.

You could add some debug sensors, so that you can really check what's the biggest block available, and whether PSRAM is configured/working on your device:

```
debug:
  update_interval: 60s
sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    psram:
      name: "PSRAM"
```

2024-03-02 15:35 UTC, PaulBiod commented
Hi @guillempages 
Thanks for the explanation.
I fixed my issue by... buying an esp32 S3 and no more problems with psram :)
Thanks for your good work

2024-03-03 12:14 UTC, osos commented
I keep getting these warnings:

```
[13:09:50][W][component:214]: Component interval took a long time for an operation (0.96 s).
[13:09:50][W][component:215]: Components should block for at most 20-30ms.
[13:09:50][W][component:214]: Component online_image took a long time for an operation (0.06 s).
[13:09:50][W][component:215]: Components should block for at most 20-30ms.
```

It is a 320x240 png download.

```
online_image:
  - url: "http://local.server.url"
    id: overview_1
    type: RGB565
    format: PNG
    on_download_finished:
      - component.update: ili_display
    on_error:
      - logger.log: "Could not download the image"
```

Any possibilities to limit the blocking nature of this component? Thinking background thread or something.

2024-03-03 13:03 UTC, nagyrobi commented
> [13:09:50][W][component:214]: Component interval took a long time for an operation (0.96 s).

What's the URL? Likely a DNS resolution issue...

2024-03-03 16:52 UTC, osos commented
> > [13:09:50][W][component:214]: Component interval took a long time for an operation (0.96 s).
> 
> What's the URL? Likely a DNS resolution issue...

Could be. but then why the subsequent warnings immediately? sometimes multiple with the 0.06s. Wemos s3 mini hardware

2024-03-05 09:11 UTC, NonaSuomy commented
https://github.com/Bodmer/TJpg_Decoder/
Since this is taking a while to get included possible to get JPG support?

2024-03-05 11:01 UTC, nagyrobi commented
> https://github.com/Bodmer/TJpg_Decoder/ Since this is taking a while to get included possible to get JPG support?

It's Arduino-only... ESP-IDF-compatible solutions would be better.

2024-03-06 08:46 UTC, velijv commented
> > https://github.com/Bodmer/TJpg_Decoder/ Since this is taking a while to get included possible to get JPG support?
> 
> It's Arduino-only... ESP-IDF-compatible solutions would be better.

sadly the whole component is not ESP-IDF compatible. 😞 

```
online_image: [source /config/voice.idf.yaml:88]
  
  This feature is incompatible with esp-idf.
```

2024-03-06 11:28 UTC, nagyrobi commented
Yes, sadly. ESP-IDF is the future. Plus, certain future components will likey be IDF-only so developing arduino-only new stuff should be avoided...

2024-03-07 16:32 UTC, NonaSuomy commented
Does the RP2040 support ESP-IDF?

2024-03-07 18:05 UTC, nagyrobi commented
Support for all aspects of ESPHome on the RP2040 is still highly experimental. The equivalent of IDF is PicoSDK for RP.

Arduino as a wrapper increases resource consumption. On ESP32 already, if you compare the same ESPHome functionality under with ESP-IDF, you'll notice higher stability/reliability, less RAM used and snappier responsiveness overall, just because there's not an extra abstraction layer in the code.

2024-03-13 20:09 UTC, guillempages commented
I agree that it would be nice to have JPEG support in it, and to have this work on ESP-IDF.

For the JPEG part, I still think that it is best to first get this merged, and then implement additional support. The PR is already pretty big, and I assume this is the main reason why it has not been reviewed in the (almost) year that it has already been open.

Regarding esp-idf support, when I created the first PR for this issue (this one is actually my second try) two years ago, I had not even heard of the idf framework. For this one, I reworked lots of it, but kept using the pngle library for PNG. and I'm not sure whether this also supports esp-idf. It's been so long since I've done this implementation, that I'm not sure I'm up to re-implement it once again for esp-idf. I think the best would be if both arduino and esp-idf would be supported, but I'm not sure if this is possible (though I assume it is) or how to achieve that.
And then again see point 1: I'd rather have this merged in, and then improve it / add support for JPEG / add esp-idf support, than have it ever-growing and thus reducing the motivation for someone to review it.

2024-04-01 14:16 UTC, pgericson commented
I get this error for displays of 960x680 on a ESP32. its too many bytes allocated probably. even tho it should fit in Heap size, but maybe there is some reserved space? I don't know enough about ESP32s to diagnose it.
```
[16:10:07][I][online_image:348]: Updating image
[16:10:07][D][online_image:384]: Content Type: image/png
[16:10:07][D][online_image:385]: Content Length: 174
[16:10:07][D][online_image:386]: ETag:
[16:10:07][I][online_image:408]: Downloading image from http://192.168.1.138:8000/black.png
[16:10:07][W][component:232]: Component esphome.coroutine took a long time for an operation (114 ms).
[16:10:07][W][component:233]: Components should block for at most 30 ms.
[16:10:07][D][online_image:154]: Allocating new buffer of 81600 Bytes...
[16:10:07][E][online_image:163]: allocation failed. Free Heap: 100376 Bytes
[16:10:07][  8238][E][png_image.cpp:59] decode(): [online_image.png] Error decoding image: No IHDR chunk is found
[16:10:07][E][online_image:198]: Error when decoding image.
[16:10:07][D][main:356]: Error downloading image
```

on line 163 which is then 156 that fails. you can ignore the `png_image.cpp:59` one as it just continues and fails on that too.
https://github.com/esphome/esphome/blob/76f3b55f85a1fd39930f692037488b782aa3f72d/esphome/components/online_image/online_image.cpp#L154-L166


related PR for the supported display size: [#waveshare133](https://github.com/esphome/esphome/pull/6443)

2024-04-08 15:53 UTC, flemingt commented
Hi everyone, this project is exactly what I need.
I've home assistant running on an unraid vm, I also have a docker with a fixed IP address which takes a B/W PNG screenshot of a specific dashboard which refreshes every minute. This is viewable by going to <<ip:5000>>.

I have a waveshare 7.5" V2 connected to an ESP32devkit using a e-paper driver hat. Using the arduino IDE I've been able to display various demos in the GxEPD / GxEPD2 repos.

Reading through this thread, I've written the following very simple YAML:
substitutions:
  name: esphome-web-fb033c
  friendly_name: epaper

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'
  on_boot:
  - wait_until:
      condition: wifi.connected

esp32:
  board: esp32dev
  framework:
    type: arduino

# png support
external_components:
  - source: 'github://pr#4710'
    components: [ online_image ]

# Optional manual IP
wifi:
  ssid: !SSID
  password: !PSK
  manual_ip:
    static_ip: 192.168.1.123
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.4
  fast_connect: True

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:

# Allow provisioning Wi-Fi via serial
improv_serial:
 
# display settings
spi:
  clk_pin: 18
  mosi_pin: 23
display:
  - platform: waveshare_epaper
    id: waveshare_display
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4 
    reset_pin: 16
    model: 7.50inV2
    rotation: 90°

binary_sensor:
  - platform: status
    name: "Display Status"

# Fetch the PNG image from the specified IP
online_image:
  url: "http://192.168.1.13:5000"
  id: my_image
  format: PNG
  on_download_finished:
    - component.update: waveshare_display
  on_error:
    - logger.log: "Could not download the image"

# Refreshing
interval:
  - interval: 2min
    then:
    - component.update: my_image

However it results in the following error:
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[I][logger:158]: Log initialized
[C][ota:483]: There have been 0 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[D][spi:039]: Setting up SPI bus...
[D][binary_sensor:034]: 'Display Status': Sending initial state OFF
[D][spi_device:379]: mode 0, data_rate 2000kHz
[E][waveshare_epaper:2284]: Timeout while displaying image!
[C][wifi:038]: Setting up WiFi...
[C][wifi:051]: Starting WiFi...
[C][wifi:052]:   Local MAC: <<I've deleted this>>
[I][wifi:303]: WiFi Connecting to '<<I've deleted this>>'...
[I][online_image:348]: Updating image
[ 10591][E][WiFiClient.cpp:242] connect(): connect on fd 48, errno: 118, "Host is unreachable"
[E][online_image:375]: Could not download image from http://192.168.1.13:5000. Error code: -1
[D][main:398]: Could not download the image
[I][waveshare_epaper:2339]: Power on the display and hat
[E][waveshare_epaper:2284]: Timeout while displaying image!
[E][waveshare_epaper:2284]: Timeout while displaying image!
[W][component:232]: Component display took a long time for an operation (21373 ms).
[W][component:233]: Components should block for at most 30 ms.
[W][wifi:152]: Warning set: unspecified
[I][wifi:594]: WiFi Connected!
[C][wifi:408]:   Local MAC: <<I've deleted this>>
[C][wifi:413]:   SSID: [redacted]
[C][wifi:416]:   IP Address: 192.168.1.123
[C][wifi:420]:   BSSID: [redacted]
[C][wifi:421]:   Hostname: 'esphome-web-fb033c'
[C][wifi:423]:   Signal strength: -50 dB ▂▄▆█
[C][wifi:427]:   Channel: 5
[C][wifi:428]:   Subnet: 255.255.255.0
[C][wifi:429]:   Gateway: 192.168.1.1
[C][wifi:430]:   DNS1: 192.168.1.4
[C][wifi:431]:   DNS2: 0.0.0.0
[D][wifi:752]: Saved fast_connect wifi settings
[C][ota:096]: Over-The-Air Updates:
[C][ota:097]:   Address: 192.168.1.123:3232
[C][ota:103]:   OTA version: 2.
[C][api:025]: Setting up Home Assistant API server...
[I][app:062]: setup() finished successfully!
[I][waveshare_epaper:2339]: Power on the display and hat
[W][component:232]: Component display took a long time for an operation (1355 ms).
[W][component:233]: Components should block for at most 30 ms.
[W][wifi:165]: Warning cleared
[W][api:152]: Warning set: unspecified
[I][app:102]: ESPHome version 2024.3.1 compiled on Apr  8 2024, 16:41:24
[I][app:104]: Project esphome.web version 1.0
[C][wifi:580]: WiFi:
[C][wifi:408]:   Local MAC: <<I've deleted this>>
[C][wifi:413]:   SSID: [redacted]
[C][wifi:416]:   IP Address: 192.168.1.123
[C][wifi:420]:   BSSID: [redacted]
[C][wifi:421]:   Hostname: 'esphome-web-fb033c'
[C][wifi:423]:   Signal strength: -55 dB ▂▄▆█
[C][wifi:427]:   Channel: 5
[C][wifi:428]:   Subnet: 255.255.255.0
[C][wifi:429]:   Gateway: 192.168.1.1
[C][wifi:430]:   DNS1: 192.168.1.4
[C][wifi:431]:   DNS2: 0.0.0.0
[I][waveshare_epaper:2339]: Power on the display and hat
[W][component:232]: Component display took a long time for an operation (1353 ms).
[W][component:233]: Components should block for at most 30 ms.
[C][logger:166]: Logger:
[C][logger:167]:   Level: DEBUG
[C][logger:169]:   Log Baud Rate: 115200
[C][logger:170]:   Hardware UART: UART0
[I][waveshare_epaper:2339]: Power on the display and hat
[W][component:232]: Component display took a long time for an operation (1354 ms).
[W][component:233]: Components should block for at most 30 ms.
[C][spi:068]: SPI bus:
[C][spi:069]:   CLK Pin: GPIO18
[C][spi:070]:   SDI Pin: 
[C][spi:071]:   SDO Pin: GPIO23
[C][spi:076]:   Using HW SPI: SPI
[I][waveshare_epaper:2339]: Power on the display and hat
[E][waveshare_epaper:2284]: Timeout while displaying image!
[W][component:232]: Component display took a long time for an operation (11363 ms).
[W][component:233]: Components should block for at most 30 ms.
[I][waveshare_epaper:2339]: Power on the display and hat
[W][component:232]: Component display took a long time for an operation (1353 ms).
[W][component:233]: Components should block for at most 30 ms.
[I][waveshare_epaper:2339]: Power on the display and hat
[W][component:232]: Component display took a long time for an operation (1353 ms).
[W][component:233]: Components should block for at most 30 ms.
[I][waveshare_epaper:2339]: Power on the display and hat
[W][component:232]: Component display took a long time for an operation (1353 ms).
[W][component:233]: Components should block for at most 30 ms.
[C][status:034]: Status Binary Sensor 'Display Status'
[C][status:034]:   Device Class: 'connectivity'
[I][waveshare_epaper:2339]: Power on the display and hat
[E][waveshare_epaper:2284]: Timeout while displaying image!
[W][component:232]: Component display took a long time for an operation (11363 ms).
[W][component:233]: Components should block for at most 30 ms.
[I][waveshare_epaper:2339]: Power on the display and hat
[W][component:232]: Component display took a long time for an operation (1353 ms).
[W][component:233]: Components should block for at most 30 ms.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][waveshare_epaper:2339]: Power on the display and hat
[W][component:232]: Component display took a long time for an operation (1353 ms).
[W][component:233]: Components should block for at most 30 ms.
[C][waveshare_epaper:2373]: Waveshare E-Paper
[C][waveshare_epaper:2373]:   Rotations: 90 °
[C][waveshare_epaper:2373]:   Dimensions: 480px x 800px
[C][waveshare_epaper:2374]:   Model: 7.5inV2rev2
[C][waveshare_epaper:2375]:   Reset Pin: GPIO16
[C][waveshare_epaper:2376]:   DC Pin: GPIO17
[C][waveshare_epaper:2377]:   Busy Pin: GPIO4
[C][waveshare_epaper:2378]:   Update Interval: 1.0s
[I][w [...]

2024-04-14 13:04 UTC, guillempages commented
@flemingt I'm not sure what the error could be in your case... One thing I see, is that it tries to download the image for the first time before it is actually connected. I can also see, that your "display" component takes very long to update; even before the image is downloaded (there are logs where it takes 11 seconds or even 21 seconds).

I'm not sure what you want to display but, at least for a test, it might be a good idea to add an `update_interval: never` to your `display:` component, so that it does not waste time in trying to display something that is not there yet (i.e. the downloaded image).
Another thing you could try, would be to make the timeout in the interval bigger (maybe 5 minutes instead of the current 2).
If you then get it working, you can try updating the intervals to a different (more frequent) one; just for ruling things out.

In any case, the current implementation is not (fully?) optimized for speed. The main goal was to get it working, and once this is merged, it can be iterated over, to add more functionality (e.g. JPEG, esp-idf support, ...) and also optimize it.

2024-04-28 16:09 UTC, easyjoh commented
I suddenly have this:

Content Length: 0

However, the apache-server from which the png is fetched say it delivers 60512 bytes status 200 

Any ideas?

Esp32-s3-mini

```
[18:06:46][I][online_image:354]: Updating image
[18:06:47][D][online_image:390]: Content Type: image/png
[18:06:47][D][online_image:391]: **Content Length: 0**
[18:06:47][D][online_image:392]: ETag: 
[18:06:47][I][online_image:414]: Downloading image from http://192.168.x.x/esp/info.php?page=1
[18:06:47][W][component:237]: Component interval took a long time for an operation (1101 ms).
[18:06:47][W][component:238]: Components should block for at most 30 ms.
[18:06:47][D][online_image:184]: Image fully downloaded
```

2024-04-28 17:03 UTC, easyjoh commented
> I suddenly have this:
> 
> Content Length: 0
> 
> However, the apache-server from which the png is fetched say it delivers 60512 bytes status 200
> 
> Any ideas?

I have found that apache with php generated image does not provide a Content-Length header as the file is send as chunks. Thus, the "total_size" variable will be set to zero (0). maybe the total_size should be set by httpclients sizeinformation and not the missing header ?

2024-04-28 17:09 UTC, easyjoh commented on esphome/components/online_image/online_image.cpp
> +  uint32_t total_size = http_.header("Content-Length").toInt();
Maybe use the HTTPClient getSize() 

https://github.com/espressif/arduino-esp32/blob/cf448906b3836fbe9368934713b697469254c62f/libraries/HTTPClient/src/HTTPClient.h#L232

uint32_t total_size = http_.getSize();

2024-05-08 11:33 UTC, DominoLeChat commented
Hi ! First of all, thank you for your work. When using this PR in conjunction with the component "waveshare_epaper" from "https://github.com/twisterss/esphome-dev.git", an unhandled exception occurs, and causes a reboot of the ESP32. The config works fine without the custom "waveshare_epaper",  and this custom component works fine without "online_image". Here's my config : 

esphome:
  name: e-ink-display
  friendly_name: e-ink display
  on_boot:
    then:
      - wait_until: api.connected

esp32:
  board: esp32dev
  framework:
    type: arduino

time:
  - platform: sntp
    id: sntp_id
    timezone: Europe/Paris

external_components:
  - source:
      type: git
      url: https://github.com/twisterss/esphome-dev.git
      ref: waveshare-red-black
    components: [ waveshare_epaper ]
  - source: 'github://pr#4710'
    components:
      - online_image

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: --redacted--

ota:
  password: --redacted--

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light
  fast_connect: true
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.0.90
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    # The subnet of the network. 255.255.255.0 works for most home networks.
    dns1: 192.168.0.15

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "E-Ink-Display Fallback Hotspot"
    password: "password"

font:
  - file:
      type: gfonts
      family: Poppins
      weight: 600
    id: poppins_38
    size: 38

  - file:
      type: gfonts
      family: Poppins
      weight: 500
    id: poppins_32
    size: 32

text_sensor:
  - platform: homeassistant
    id: title
    entity_id: media_player.symfonisk_lampadaire
    attribute: media_title
  - platform: homeassistant
    id: artist
    entity_id: media_player.symfonisk_lampadaire
    attribute: media_artist

online_image:
  - url: "http://192.168.0.15:5050"
    id: album_artwork
    format: PNG
    type: binary

spi:
  clk_pin: 13
  mosi_pin: 14

color:
  - id: COLOR_RED
    red: 100%
    green: 0%
    blue: 0%
    white: 0%

button:
  - platform: template
    name: "Update screen"
    id: bouton_refresh
    on_press:
      then:
        - component.update: album_artwork
display:
    platform: waveshare_epaper
    id: waveshare_display
    update_interval: never
    cs_pin: 15
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    model: 7.50in-bv2-rb
    rotation: 180°
    lambda: |-
      // Album
      it.image(240, 20, id(album_artwork), COLOR_OFF, COLOR_ON);

      // Titre
      it.printf(400, 345, id(poppins_38), COLOR_ON, COLOR_OFF, TextAlign::TOP_CENTER, "%s", id(title).state.c_str());

      // Artiste
      it.printf(400, 400, id(poppins_32), COLOR_ON, COLOR_OFF, TextAlign::TOP_CENTER, "%s", id(artist).state.c_str());

captive_portal:

---------------------------------------------------------------------------------------------------------------------------------

And here's the error : 

[13:25:31]Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
[13:25:31]
[13:25:31]Core  1 register dump:
[13:25:31]PC      : 0x400ef22d  PS      : 0x00060530  A0      : 0x800db9c6  A1      : 0x3ffb2690  
[13:25:31]A2      : 0x00000000  A3      : 0x3ffb32a4  A4      : 0x00000800  A5      : 0x3ffd3160  
[13:25:31]A6      : 0x00000000  A7      : 0x00060023  A8      : 0x3ffb3aa3  A9      : 0x3ffb2710  
[13:25:31]A10     : 0x0000008b  A11     : 0x00000010  A12     : 0x3ffb270c  A13     : 0x3ffc3a00  
[13:25:31]A14     : 0x00000001  A15     : 0x3ffb08c0  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
[13:25:31]EXCVADDR: 0x00000024  LBEG    : 0x4008469d  LEND    : 0x400846a5  LCOUNT  : 0x00000027  
[13:25:31]
[13:25:31]
[13:25:31]Backtrace:0x400ef22a:0x3ffb26900x400db9c3:0x3ffb2730 0x400db8fa:0x3ffb2770 0x40190555:0x3ffb2790 0x401905f1:0x3ffb27b0 0x400e1228:0x3ffb27d0 0x400e390e:0x3ffb2800 0x400f427d:0x3ffb2820 
[13:25:31]
[13:25:31]
[13:25:31]
[13:25:31]
[13:25:31]ELF file SHA256: 0000000000000000
[13:25:31]
[13:25:31]Rebooting...
[13:25:31]ets Jun  8 2016 00:22:57
[13:25:31]
[13:25:31]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[13:25:31]configsip: 0, SPIWP:0xee
[13:25:31]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[13:25:31]mode:DIO, clock div:2
[13:25:31]load:0x3fff0030,len:1184
[13:25:31]load:0x40078000,len:13132
[13:25:31]load:0x40080400,len:3036
[13:25:31]entry 0x400805e4

2024-05-11 12:25 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +  uint32_t total_size = http_.header("Content-Length").toInt();
Thanks for the tip; it works as expected (and I need one "string to int" conversion less) :-)

2024-05-11 12:30 UTC, guillempages commented
@DominoLeChat Sorry, I have no idea what could possibly be wrong with that combination :-( I don't have a waveshare that I could try on.
Do you have the logs from before the crash? So that at least I could see where in the image component it is crashing? (if it is crashing there)

One thing that comes to mind, if I am reading your configuration right, your screen is a 3-color (white, black, red) one, right? Do you know how the pixels are being drawn to that screen? Or which format do images use to draw? It might be a mismatch between what the custom component driver expects as a color format, and what the online_image supports.

You might want to try (just to see if this helps) other pixel formats (`type: BINARY` `type:RGB565` ... on the online_image).

2024-05-12 19:16 UTC, ianByrne commented
Hello - I am running into the following error when trying to install.

```yaml
external_components:
  - source: github://pr#4710
    components: [ "online_image" ]
```

```
In file included from src/esphome/components/online_image/image_decoder.cpp:4:
src/esphome/components/online_image/online_image.h:79:3: error: 'ESPHOME_ALWAYS_INLINE' does not name a type; did you mean 'ALWAYS_INLINE'?
   ESPHOME_ALWAYS_INLINE bool auto_resize_() const { return fixed_width_ == 0 || fixed_height_ == 0; }
   ^~~~~~~~~~~~~~~~~~~~~
   ALWAYS_INLINE
*** [.pioenvs/bedroom-lilygo-display/src/esphome/components/online_image/image_decoder.cpp.o] Error 1
In file included from src/esphome/components/online_image/online_image.cpp:3:
src/esphome/components/online_image/online_image.h:79:3: error: 'ESPHOME_ALWAYS_INLINE' does not name a type; did you mean 'ALWAYS_INLINE'?
   ESPHOME_ALWAYS_INLINE bool auto_resize_() const { return fixed_width_ == 0 || fixed_height_ == 0; }
   ^~~~~~~~~~~~~~~~~~~~~
   ALWAYS_INLINE
src/esphome/components/online_image/online_image.cpp: In member function 'bool esphome::online_image::OnlineImage::resize_(int, int)':
src/esphome/components/online_image/online_image.cpp:143:7: error: 'auto_resize_' was not declared in this scope
   if (auto_resize_()) {
       ^~~~~~~~~~~~
src/esphome/components/online_image/online_image.cpp:143:7: note: suggested alternative: 'resize_'
   if (auto_resize_()) {
       ^~~~~~~~~~~~
       resize_
*** [.pioenvs/bedroom-lilygo-display/src/esphome/components/online_image/online_image.cpp.o] Error 1
```

2024-05-12 21:21 UTC, guillempages commented
@ianByrne sorry about that error.  I did a fix for the beta,  and somehow forgot,  that the release is not yet out 🫤.

When the next release is released (should be on Wednesday if I am not mistaken) the issue will be automatically fixed. 

Meanwhile I'll try to do some hack tomorrow,  to see if I can make it work again on the previous versions as well.

2024-05-30 08:09 UTC, DohmenICT commented
Hi!

This still doesn't work for me, this is my code:
`external_components:
  - source: github://guillempages/esphome@online_image_buffer
    components: [online_image]

online_image:
  - url: "https://office.******.nl/EnergyPrices.png"
    id: energypricesimage
    on_download_finished:
      - component.update: epaperdisplay`

and these are the errors I get when compiling:
`INFO ESPHome 2024.5.4
INFO Reading configuration /config/esphome/epaper1.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing epaper1 (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- SPI @ 1.0
|-- ESP8266HTTPClient @ 1.2
|-- pngle @ 1.0.2
Compiling .pioenvs/epaper1/src/esphome/components/online_image/image_decoder.cpp.o
Compiling .pioenvs/epaper1/src/esphome/components/online_image/online_image.cpp.o
Compiling .pioenvs/epaper1/src/esphome/components/online_image/png_image.cpp.o
Compiling .pioenvs/epaper1/src/esphome/components/spi/spi_arduino.cpp.o
src/esphome/components/online_image/png_image.cpp: In member function 'virtual int esphome::online_image::PngDecoder::decode(uint8_t*, size_t)':
src/esphome/components/online_image/png_image.cpp:54:5: error: 'ESP_LOGD' was not declared in this scope
   54 |     ESP_LOGD(TAG, "Waiting for data");
      |     ^~~~~~~~
src/esphome/components/online_image/png_image.cpp:59:5: error: 'ESP_LOGE' was not declared in this scope; did you mean 'USE_LOGGER'?
   59 |     ESP_LOGE(TAG, "Error decoding image: %s", pngle_error(pngle));
      |     ^~~~~~~~
      |     USE_LOGGER
Compiling .pioenvs/epaper1/src/esphome/components/spi/spi_esp_idf.cpp.o
src/esphome/components/online_image/image_decoder.cpp: In member function 'uint8_t* esphome::online_image::DownloadBuffer::data(size_t)':
src/esphome/components/online_image/image_decoder.cpp:29:5: error: 'ESP_LOGE' was not declared in this scope; did you mean 'USE_LOGGER'?
   29 |     ESP_LOGE(TAG, "Tried to access beyond download buffer bounds!!!");
      |     ^~~~~~~~
      |     USE_LOGGER
*** [.pioenvs/epaper1/src/esphome/components/online_image/png_image.cpp.o] Error 1
*** [.pioenvs/epaper1/src/esphome/components/online_image/image_decoder.cpp.o] Error 1
src/esphome/components/online_image/online_image.cpp: In member function 'virtual void esphome::online_image::OnlineImage::update()':
src/esphome/components/online_image/online_image.cpp:357:33: error: call to 'HTTPClient::begin' declared with attribute error: obsolete API, use ::begin(WiFiClient, url)
  357 |   int begin_status = http_.begin(url_);
      |                      ~~~~~~~~~~~^~~~~~
*** [.pioenvs/epaper1/src/esphome/components/online_image/online_image.cpp.o] Error 1
========================== [FAILED] Took 3.09 seconds ==========================`

2024-06-05 21:43 UTC, guillempages commented
@DohmenICT Your problem is a different one. You are using an ESP8266, and I have actually never tested the code there. So it does not even compile 😕 
There was some half-hearted intent to support it (because I originally based my code on the http_request component; which does support it).

I have updated the code now to support (at least compiling) on ESP8266, but I am not really sure that it will work as you expect; probably you will run into issues because of low performance or low memory.

Please, do test it with the latest version, and let me know whether it works at all.

2024-06-06 06:46 UTC, DohmenICT commented
Hi, thanks for your feedback. The code compiles now and I can upload it. But I get a weird error where the complete url of the image isn't shown in the logging:

```
[08:42:32][I][online_image:375]: Updating image
[08:42:37][E][online_image:408]: Could not download image from Ԛ\xff?,. Error code: -5
[08:43:00][D][main:100]: Could not download the image
```

This is my code:
```
esphome:
  name: epaper1
  friendly_name: epaper1
  on_boot:
    priority: -10       
    then:
      - delay: 10s
      - component.update: energypricesimage
      - component.update: epaperdisplay


interval:
  - interval: 1min
    then:
    - component.update: energypricesimage
    - component.update: epaperdisplay

external_components:
  - source: github://guillempages/esphome@online_image_buffer
    components: [online_image]
    refresh: 0s

online_image:
  - url: "https://office.xxx.nl/EnergyPrices.png"
    id: energypricesimage
    on_download_finished:
      - component.update: epaperdisplay
    on_error:
      - logger.log: "Could not download the image"

esp8266:
  board: esp01_1m

# Enable logging
logger:
    level: DEBUG

api:

ota:
  password: !secret otaPassword

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.169.54
  ap:
    ssid: "Epaper1 Fallback Hotspot"
    password: !secret fallbackHotSpot

captive_portal:
    
spi:
  clk_pin: 14
  mosi_pin: 13  #DIN
 
display:
  - platform: waveshare_epaper
    id: epaperdisplay
    cs_pin: 15
    dc_pin: 12
    update_interval: 300s
    busy_pin: 16
    reset_pin: 4
    model: 4.20in-bV2
    lambda: |-
      it.image(0,0,id(energypricesimage));
```

and this is the image that is hosted:
![image](https://github.com/esphome/esphome/assets/7723754/f5bcaef7-82f1-4016-8296-e8fc4d2c0b67)

2024-06-06 08:21 UTC, DohmenICT commented
saw the new commit; testing....

2024-06-06 10:49 UTC, DohmenICT commented
Still something wrong with the url in the logging...

```
[I][online_image:375]: Updating image
[E][online_image:408]: Could not download image from $��?/. Error code: -4
[D][main:098]: Could not download the image
```

2024-06-08 19:40 UTC, pgericson commented on esphome/components/online_image/__init__.py
> +        cv.Optional(CONF_BUFFER_SIZE, default=2048): cv.int_range(256, 65536),
My screen is a 13.3 inch eink, which are 960x680 which is 81600 bytes. :( 

can we increase this to 98304 maybe ?

PR for adding the support for 13.3inch screen size to esphome: https://github.com/esphome/esphome/pull/6443

2024-06-09 13:19 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +        cv.Optional(CONF_BUFFER_SIZE, default=2048): cv.int_range(256, 65536),
Why do you need to increase that? This is not the buffer to hold the decoded image; this is the temporary buffer that is used to download the image chunks before decoding.
The image is downloaded in chunks of this size and decoded on the fly.

Do you have an acutal problem with using the default size of the buffer? This option was actually added at some point to debug an issue someone else was having, but it is not intended to be used except in some very special cases, where the chunk downloading does not work.

2024-06-09 14:06 UTC, pgericson commented on esphome/components/online_image/__init__.py
> +        cv.Optional(CONF_BUFFER_SIZE, default=2048): cv.int_range(256, 65536),
I might have tried to increase the buffer size to get past the error i got, but that might just have been me not having enough free Heap Size for storing and resizing the image. Let me resolve this

2024-06-09 19:49 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +        cv.Optional(CONF_BUFFER_SIZE, default=2048): cv.int_range(256, 65536),
What do you mean by "there is no resolve button"? Do you mean that this conversation should be resolved and you don't see the button? I see it, but maybe because I am the owner of the PR ;-)

Or do you mean that the issue is not resolved? Your log looks strange; the biggest reported block is different for the online_image and for the debug sensor, but I actually copied the max block reading code from the debug sensor 🤔 

Does your device have PSRAM and if so, is it enabled and working? Images do need a lot of memory, so PSRAM is almost mandatory.

2024-06-09 19:49 UTC, guillempages commented
> Still something wrong with the url in the logging...
> 
> ```
> [I][online_image:375]: Updating image
> [E][online_image:408]: Could not download image from $��?/. Error code: -4
> [D][main:098]: Could not download the image
> ```

Oops, my bad. Should be fixed now.

2024-06-09 22:37 UTC, pgericson commented on esphome/components/online_image/__init__.py
> +        cv.Optional(CONF_BUFFER_SIZE, default=2048): cv.int_range(256, 65536),
> What do you mean by "there is no resolve button"? Do you mean that this conversation should be resolved and you don't see the button? I see it, but maybe because I am the owner of the PR ;-)

yeah, its just my view and this thread I started should probably be resolved, as it _might_ not be an issue with your code.

> 
> Or do you mean that the issue is not resolved? Your log looks strange; the biggest reported block is different for the online_image and for the debug sensor, but I actually copied the max block reading code from the debug sensor 🤔

This might be a product of the debug code running every X seconds, and thereby not reading the memory at the time of running the `pngle_feed` function. So don't read too much into it. 
https://github.com/esphome/esphome/blob/d5cec7da5a1d34b7523eeb30616d7728ad7f65ff/esphome/components/online_image/png_image.cpp#L59-L61
 
> 
> Does your device have PSRAM and if so, is it enabled and working? Images do need a lot of memory, so PSRAM is almost mandatory.

I don't have one with PSRAM that i can get to work right now.

and thanks for all the work on this PR!

but you can resolve this thread, as I won't be able to debug any more for the time being.

2024-06-11 17:56 UTC, DohmenICT commented
Well! The URL now shows in the error message.... But the error message doesn't :-D

[19:53:52][I][app:100]: ESPHome version 2024.5.5 compiled on Jun 11 2024, 19:52:40
[19:53:52][C][wifi:580]: WiFi:
[19:53:52][C][wifi:408]:   Local MAC: 3C:61:05:DC:7F:E0
[19:53:52][C][wifi:413]:   SSID: [redacted]
[19:53:52][C][wifi:416]:   IP Address: 192.168.168.234
[19:53:52][C][wifi:419]:   BSSID: [redacted]
[19:53:52][C][wifi:421]:   Hostname: 'epaper1'
[19:53:52][C][wifi:423]:   Signal strength: -76 dB ▂▄▆█
[19:53:52][C][wifi:427]:   Channel: 6
[19:53:52][C][wifi:428]:   Subnet: 255.255.255.0
[19:53:52][C][wifi:429]:   Gateway: 192.168.168.1
[19:53:52][C][wifi:430]:   DNS1: 192.168.168.1
[19:53:52][C][wifi:431]:   DNS2: 0.0.0.0
[19:53:52][C][logger:185]: Logger:
[19:53:52][C][logger:186]:   Level: DEBUG
[19:53:52][C][logger:188]:   Log Baud Rate: 115200
[19:53:52][C][logger:189]:   Hardware UART: UART0
[19:53:52][C][spi:068]: SPI bus:
[19:53:52][C][spi:069]:   CLK Pin: GPIO14
[19:53:52][C][spi:070]:   SDI Pin: 
[19:53:52][C][spi:071]:   SDO Pin: GPIO13
[19:53:52][C][spi:076]:   Using HW SPI: SPI
[19:53:52][C][waveshare_epaper:1904]: Waveshare E-Paper
[19:53:52][C][waveshare_epaper:1904]:   Rotations: 0 °
[19:53:52][C][waveshare_epaper:1904]:   Dimensions: 400px x 300px
[19:53:52][C][waveshare_epaper:1905]:   Model: 4.2in (B V2)
[19:53:52][C][waveshare_epaper:1906]:   Reset Pin: GPIO4
[19:53:52][C][waveshare_epaper:1907]:   DC Pin: GPIO12
[19:53:52][C][waveshare_epaper:1908]:   Busy Pin: GPIO16
[19:53:52][C][waveshare_epaper:1909]:   Update Interval: 300.0s
[19:53:52][C][captive_portal:088]: Captive Portal:
[19:53:52][C][mdns:115]: mDNS:
[19:53:52][C][mdns:116]:   Hostname: epaper1
[19:53:52][C][ota:096]: Over-The-Air Updates:
[19:53:52][C][ota:097]:   Address: epaper1.local:8266
[19:53:52][C][ota:100]:   Using Password.
[19:53:52][C][ota:103]:   OTA version: 2.
[19:53:52][W][ota:106]: Last Boot was an unhandled reset, will proceed to safe mode in 8 restarts
[19:53:52][C][api:139]: API Server:
[19:53:52][C][api:140]:   Address: epaper1.local:6053
[19:53:52][C][api:144]:   Using noise encryption: NO
[19:54:00][I][online_image:375]: Updating image
[19:54:04][E][online_image:409]: Could not download image from https://office.xxxxx.nl/EnergyPrices.png. Error: \xb2
[19:54:04][D][main:098]: Could not download the image
[19:54:04][W][component:237]: Component esphome.coroutine took a long time for an operation (4474 ms).

2024-06-13 10:03 UTC, guillempages commented
Hm. Very strange. Works for me on an ESP32, and I don't have an ESP8266 to test.

Now that the http_requests component has been refactored to allow other components to use it, I'll need to refactor this whole PR to use that, and hopefully the 8266 particularities will then be handled by the http_requesst component instead (and thus hopefully work). I'm not sure when I will have time to do that though.

2024-06-13 13:49 UTC, DohmenICT commented
No worries! I really appreciate your effort. No rush from my side, take your time and I'll test as soon as there's something to test.

2024-06-27 13:53 UTC, saue0 commented
can it work with ESP32 IDF ?

2024-06-27 15:00 UTC, guillempages commented
This was already asked before, but the circumstances have slightly changed.

Short answer: no

Medium length answer: not yet

Full answer:

I was working on adding idf support, but got side tracked on other
projects/rl issues.
In the meantime,  the http_request component got a big overhaul and should
now be usable by other components (like this one).
This would need a big refactoring on my side, that I haven't yet found time
for, but will be needed in any case for this PR to get a chance of getting
merged (<= my assumption, not any official statement from the project
maintainers). On the plus side,  this refactoring would make this PR
smaller *and* get support for esp-idf and rp2040 for free.

So: it's "on top of the list", but no planned date for implementation yet.

Eric Sauvé ***@***.***> schrieb am Do., 27. Juni 2024, 15:54:

> can it work with ESP32 IDF ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/4710#issuecomment-2194748621>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAS6VE3EXHG52INBARS7YFTZJQKPVAVCNFSM6AAAAAAXEVFX52VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJUG42DQNRSGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-29 16:19 UTC, DohmenICT commented
Hi!

Saw your commits; still doesn't work though:

[18:17:42][I][online_image:375]: Updating image
[18:17:42][E][online_image:409]: Could not download image from http://192.168.168.30/EnergyPrices.png. Error: 
[18:17:42][D][main:100]: Could not download the image

2024-06-30 12:57 UTC, guillempages commented
@DohmenICT I did not expect it to work... I just rebased my branch to top-of-dev, and force-pushed it, but there were no actual changes in the code.

2024-06-30 12:59 UTC, DohmenICT commented
Ah yes, no problem.

2024-06-30 13:19 UTC, guillempages commented
Moved back to "draft" until I implement the http_request refactoring. The current status should still work for ESP32-arduino framework as it was until now.

My hope is that, after the refactoring, ESP32-idf, ESP8266 and RP2040 will work "for free", but I don't have the last two to test with; so no guarantees ;-)

2024-07-01 07:23 UTC, DohmenICT commented
> My hope is that, after the refactoring, ESP32-idf, ESP8266 and RP2040 will work "for free", but I don't have the last two to test with; so no guarantees ;-)

I'm here to test if needed.

2024-07-13 14:20 UTC, guillempages commented
To everyone that might be interested ;-)

I've refactored this PR to rely on the new (2024.6) `http_request` implementation, so that the download code is now not part of the PR anymore, but only the triggering of the download and the decoding of the image.

With that refactoring I hope to achieve following benefits:
 - Automatic support for ESP8266, ESP32 (Arduino), ESP32 (IDF) and RP2040.
 - One less complain by the reviewers 😉 
 - Smaller PR (i.e. focus on the image, and not on the network issues)

This has one (small) downside though:
  A while ago, someone asked me to implement "ETAG" support here, to leverage the HTTP protocol and avoid re-downloading an image if it had not changed in the server. Since the downloading is now being handled transparently in the `http_request` component, this part of the implementation was also removed.
  It could be added on the http_component itself, but it is out of scope of this PR now. If I get some time, I might give that a shot, but it doesn't have the highest priority on my list.

And now, without further ADO, I give you the *untested* (but often desired) support for online images on the ESP-IDF framework.
I've tested on ESP32 *arduino* and works as it was working before. YMMV.

2024-07-13 15:10 UTC, clydebarrow commented
Can I suggest the ability to specify an optional compile time image that acts as a placeholder until the downloaded image is available? I would assume this will need to be copied in setup().

2024-07-13 15:16 UTC, nagyrobi commented
What a great idea! Have a local image "Connecting" to be prepared to be shown until the actual download happens.

2024-07-13 17:27 UTC, guillempages commented
While I agree that having a default placeholder image is a great idea, I disagree that it belongs in **this** PR.

I see this as an additional feature that could be added once this is merged in.

Also, copying it at setup won't work since it would be overwritten on the first download, and the buffer is deleted for every download. 

I have an idea how to do the placeholder thing, but as I said, in a following PR

2024-07-13 17:55 UTC, clydebarrow commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, Display *display, Color color_on, Color color_off) {
Isn't this already implemented in `image::Image`? Is there a difference? It looks it was copied, as it has the same use of `width_` instead of `this->width_`.

2024-07-13 18:21 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, Display *display, Color color_on, Color color_off) {
Yes, this was copied from `image::Image`. There is no difference in the code (or there shouldn't be); the problem is that the `get_*_pixel` methods in the image class are not virtual (and they shouldn't be for performance reasons), so if I don't override the method, the wrong `get*pixel` functions are called.

As for the `witdh_` vs `this->width_` I can change it, if desired; then the code wouldn't be "the same" 😜

2024-07-13 18:24 UTC, clydebarrow commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, Display *display, Color color_on, Color color_off) {
Is the image format different to `Image`? If so it won't work with LVGL.

2024-07-13 18:25 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, Display *display, Color color_on, Color color_off) {
Hm. Let me double check that statement about the wrong methods being called. 🤔

2024-07-13 18:30 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, Display *display, Color color_on, Color color_off) {
> Is the image format different to Image? If so it won't work with LVGL.

It's not about the format, but where it is stored. The `get*pixel` methods from the `Image` class read from ROM, and the `get*pixel` methods from `OnlineImage` read from RAM; the code there is slightly different, but there are the same 5 image formats as in `Image`.

And nevertheless, I started implementing this more than two and a half years ago, with a big refactoring (including closing the old PR and opening this one) one and a half year ago. At that point there was no talks about LVGL yet, (and LVGL is not yet merged anyway), so I'd rather focus on having this work with the "current standard" (i.e. lambda), and if LVGL works, this is a bonus.

2024-07-13 18:37 UTC, clydebarrow commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, Display *display, Color color_on, Color color_off) {
If the format is the same, it will be fine. I see the issue with progmem - I would have thought that progmem_read will happily read from RAM anyway (it's only an issue on ESP8266 which requires ROM reads to be on even addresses), but I'm not certain of that. I'll look into it later - I'm at 39000 ft over Tashkent right now :-)

2024-07-13 18:56 UTC, clydebarrow commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, Display *display, Color color_on, Color color_off) {
Well, I did look and I am confident progmem_read will read from RAM. On anything except 8266 it's just a pointer dereference anyway, and the 8266 code reads a 32 bit word and shifts the result to extract a byte so doesn't care where it reads from (RAM and ROM are in the same address space.) I can't actually test on hardware right now though. So there should be no need to reimplement the drawing functions, unless there is some other issue.

2024-07-13 18:58 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, Display *display, Color color_on, Color color_off) {
> If the format is the same, it will be fine. I see the issue with progmem - I would have thought that progmem_read will happily read from RAM anyway (it's only an issue on ESP8266 which requires ROM reads to be word-aligned)

I'm testing it at the moment; it looks like, at least on an ESP32-S3 it mostly works without the overridden method. Only binary images seem to have a problem; I'll have to dig deeper into that.

Nevertheless, there are people hoping for it to work on the ESP8266, and if there is an issue with progmem_read there, this wouldn't work then.

2024-07-13 19:22 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, Display *display, Color color_on, Color color_off) {
Ok, the binary issue was on my side; apparently I wasn't using the same storage format as `Image` for that case.
Fixed it.

2024-07-13 19:23 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, Display *display, Color color_on, Color color_off) {
@clydebarrow it would be great if you could double check what you meant with the 8266, since I don't have any to test with.

@DohmenICT You also might want to test this, since IIRC you do need it to work with an 8266, right?

2024-07-13 19:49 UTC, clydebarrow commented on esphome/components/online_image/online_image.cpp
> +void OnlineImage::draw(int x, int y, Display *display, Color color_on, Color color_off) {
I'll be able to test it in a few days. I can't see it being used much on an 8266 anyway, but there should be no reason it won't work.

2024-07-14 13:31 UTC, guillempages commented
Managed to test it with ESP-IDF as well 😃 It works **if** there is enough (PS-)RAM available; might have issues if PSRAM is not properly working.

2024-07-15 09:31 UTC, nagyrobi commented
```yaml
Failed config

online_image: [source config/zz_pak_lvgl_test.yaml:22]

  Internal Error: require_framework_version does not support this platform configuration
                  platform: host
                  framework: host
```

2024-07-15 12:40 UTC, guillempages commented
> Wanted to try with LVGL on `host` platform...
> 
> ```yaml
> Failed config
> 
> online_image: [source config/zz_pak_lvgl_test.yaml:22]
> 
>   Internal Error: require_framework_version does not support this platform configuration
>                   platform: host
>                   framework: host
> ```

This looks like a generic issue with the framework version validator.
The online_image is explicitly requiring a minimum version of the arduino or the esp-idf framework, and this is being handled by that method that prints out your error.
There is no support for the "host" platform on that validator, so that I cannot fix that by explicitly allowing it.
And even if I could, or if I would remove the validator at all, the `http_request` dependency that online_image is using, also has a validator for the framework, so the same issue would appear.

So, while I see the advantadges that allowing `host` as a platform would bring, I don't see it as feasible in the short/mid term.

2024-07-15 22:59 UTC, clydebarrow commented
Fails on ESP8266 during png decode:

```
[08:56:57][D][http_request.arduino:124]: Content-Length: 685
[08:56:57][D][online_image:121]: Starting download
[08:56:57][I][online_image:137]: Downloading image
[08:56:57][W][component:237]: Component interval took a long time for an operation (605 ms).
[08:56:57][W][component:238]: Components should block for at most 30 ms.
[08:56:57]Fatal exception 28(LoadProhibitedCause):
[08:56:57]epc1=0x402012c2, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000024, depc=0x00000000
WARNING Decoded 0x402012c2: pngle_feed
[08:56:57]
[08:56:57]--------------- CUT HERE FOR EXCEPTION DECODER ---------------
[08:56:57]
[08:56:57]Exception (28):
WARNING Exception type: Access to invalid address: LOAD (wild pointer?)
[08:56:57]epc1=0x402012c2 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000024 depc=0x00000000
WARNING Decoded 0x402012c2: pngle_feed
[08:56:57]
[08:56:57]>>>stack>>>
WARNING Found stack trace! Trying to decode it
[08:56:57]
[08:56:57]ctx: cont
[08:56:57]sp: 3ffffd30 end: 3fffffd0 offset: 0150
[08:56:57]3ffffe80:  3fffff00 3ffffef0 00000010 4022add2
WARNING Decoded 0x4022add2: pbuf_free_LWIP2 at /local/users/gauchard/arduino/arduino_esp8266/origin/tools/sdk/lwip2/builder/lwip2-src/src/core/pbuf.c:786
 (inlined by) pbuf_free_LWIP2 at /local/users/gauchard/arduino/arduino_esp8266/origin/tools/sdk/lwip2/builder/lwip2-src/src/core/pbuf.c:725
[08:56:57]3ffffe90:  00000001 00000000 3fff4254 4020fae1
WARNING Decoded 0x4020fae1: ClientContext::_consume(unsigned int)
[08:56:58]3ffffea0:  00000000 00001d4f f0a3d70a 000002ad
[08:56:58]3ffffeb0:  3fff409c 3fff409c 00000082 4020fbda
WARNING Decoded 0x4020fbda: WiFiClient::read()
[08:56:58]3ffffec0:  3fff409c 3fff147c 3fff409c 40219b1c
WARNING Decoded 0x40219b1c: Stream::timedRead()
[08:56:58]3ffffed0:  00000000 00001d4f f851eb85 0021e477
[08:56:58]3ffffee0:  00001ade 3ffef4bc 3fff13d4 3fff409c
[08:56:58]3ffffef0:  3fff3f68 00001d4b 000002ad 40204687
WARNING Decoded 0x40204687: esphome::http_request::HttpContainerArduino::read(unsigned char*, unsigned int)
[08:56:58]3fffff00:  00000000 00000000 00000000 4020dbc3
WARNING Decoded 0x4020dbc3: void std::__push_heap<__gnu_cxx::__normal_iterator<std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> >*, std::vector<std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> >, std::allocator<std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> > > > >, int, std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> >, __gnu_cxx::__ops::_Iter_comp_val<bool (*)(std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> > const&, std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> > const&)> >(__gnu_cxx::__normal_iterator<std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> >*, std::vector<std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> >, std::allocator<std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> > > > >, int, int, std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> >, __gnu_cxx::__ops::_Iter_comp_val<bool (*)(std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> > const&, std::unique_ptr<esphome::Scheduler::SchedulerItem, std::default_delete<esphome::Scheduler::SchedulerItem> > const&)>&)
[08:56:58]3fffff10:  3fff147c 00000800 3fff3404 4020e1d3
WARNING Decoded 0x4020e1d3: esphome::Scheduler::call()
[08:56:58]3fffff20:  4026656e 3fff0ea4 00001d4b 402045f4
WARNING Decoded 0x4026656e: wifi_get_opmode
WARNING Decoded 0x402045f4: esphome::http_request::HttpContainerArduino::read(unsigned char*, unsigned int)
[08:56:58]3fffff30:  3fff1430 3fff3dac 3fff13d4 40206b6d
WARNING Decoded 0x40206b6d: esphome::online_image::OnlineImage::loop()
[08:56:58]3fffff40:  3fff3f68 3fff3f5c d1eb851e 0021dfaa
[08:56:58]3fffff50:  00000800 3fff33fc fffff3ce 3fff13d4
[08:56:58]3fffff60:  3fff3f40 3fff13d4 3fffff80 3fff13d4
[08:56:58]3fffff70:  3fff3f40 00000002 3ffef4bc 4020baae
WARNING Decoded 0x4020baae: esphome::Application::loop()
[08:56:58]3fffff80:  00001d4b 3fff13d4 3fff3534 3ffef938
[08:56:58]3fffff90:  3fff3f48 3fff13a0 3ffef4f0 3ffef938
[08:56:58]3fffffa0:  3fffdad0 00000000 3ffef90c 3ffef938
[08:56:58]3fffffb0:  3fffdad0 00000000 3ffef90c 4021b3c4
WARNING Decoded 0x4021b3c4: loop_wrapper() at core_esp8266_main.cpp
[08:56:58]3fffffc0:  feefeffe feefeffe 3fffdab0 401003cd
WARNING Decoded 0x401003cd: cont_wrapper
[08:56:58]<<<stack<<<
[08:56:58]
[08:56:58]--------------- CUT HERE FOR EXCEPTION DECODER ---------------
```

2024-07-15 23:06 UTC, clydebarrow commented
I personally doubt that it's worth trying to make it work on ESP8266. There is only 80K RAM available, the PNGLE library requires over 40K according to the Github page, by the time you add space for the decoded image, and a display buffer, it is just too tight (and may not even be possible.)

Free heap on my test device *before* starting a download is reported at only 30Kbytes.

2024-07-19 04:42 UTC, jesserockz commented
I added `host` just now in #7107 after seeing this (because why not). But you are correct that `http_request` doesn't support host, so it wont work with this PR anyway.

The PR will at least give a better error message.

2024-07-21 14:39 UTC, guillempages commented
> I personally doubt that it's worth trying to make it work on ESP8266. There is only 80K RAM available, the PNGLE library requires over 40K according to the Github page, by the time you add space for the decoded image, and a display buffer, it is just too tight (and may not even be possible.)
> 
> Free heap on my test device _before_ starting a download is reported at only 30Kbytes.

I'll disable support for ESP8266 then, and write a note in the documentation, that the component is pretty hungry for RAM, and might not work at all without PSRAM.

2024-07-23 05:31 UTC, NonaSuomy commented
> I personally doubt that it's worth trying to make it work on ESP8266. There is only 80K RAM available, the PNGLE library requires over 40K according to the Github page, by the time you add space for the decoded image, and a display buffer, it is just too tight (and may not even be possible.)
> 
> Free heap on my test device _before_ starting a download is reported at only 30Kbytes.

Can you use external ram chips like https://www.microchip.com/en-us/product/23LC1024

2024-07-23 06:17 UTC, clydebarrow commented
> Can you use external ram chips

On an 8266? Haha, no. We're talking pigs and lipstick here. The 8266 is yesterday's technology, a ESP32-C3 would be the bare minimum to support an LCD display now.

2024-07-23 06:35 UTC, anabolyc commented
> > I personally doubt that it's worth trying to make it work on ESP8266. There is only 80K RAM available, the PNGLE library requires over 40K according to the Github page, by the time you add space for the decoded image, and a display buffer, it is just too tight (and may not even be possible.)
> > Free heap on my test device _before_ starting a download is reported at only 30Kbytes.
> 
> Can you use external ram chips like https://www.microchip.com/en-us/product/23LC1024

Technically you can connect it to the ESP8266. It doesn't map it into usable memory though, so every memory operation becomes a library function call. Very slow and extremely inconvenient. I wouldn't consider it usable.

2024-07-26 12:31 UTC, DohmenICT commented
> > I personally doubt that it's worth trying to make it work on ESP8266. There is only 80K RAM available, the PNGLE library requires over 40K according to the Github page, by the time you add space for the decoded image, and a display buffer, it is just too tight (and may not even be possible.)
> > Free heap on my test device _before_ starting a download is reported at only 30Kbytes.
> 
> I'll disable support for ESP8266 then, and write a note in the documentation, that the component is pretty hungry for RAM, and might not work at all without PSRAM.

Okay, fair enough. I'll get me some other device then. Any suggestions?

2024-07-30 00:48 UTC, jesserockz requested changes

2024-07-30 00:48 UTC, jesserockz commented on esphome/components/online_image/__init__.py
> +        cv.Optional(CONF_FORMAT, default="PNG"): cv.enum(IMAGE_FORMAT, upper=True),
If the intention is to add more formats in the future, then this should not have a default even if there is only one option. Otherwise it would be a breaking change in the future to remove the default.
```suggestion
        cv.Required(CONF_FORMAT): cv.enum(IMAGE_FORMAT, upper=True),
```

2024-07-30 00:48 UTC, jesserockz commented on esphome/components/online_image/__init__.py
> +        cg.add_define("ONLINE_IMAGE_PNG_SUPPORT")
This needs to be added to `esphome/core/defines.h` so clang-tidy can check the code
```suggestion
        cg.add_define("USE_ONLINE_IMAGE_PNG_SUPPORT")
```

2024-07-30 00:48 UTC, jesserockz commented on esphome/components/online_image/__init__.py
> +    if config[CONF_FORMAT] in ["PNG"]:
```suggestion
	format = config[CONF_FORMAT]
    if format in [FORMAT_PNG]:
```

2024-07-30 00:48 UTC, jesserockz commented on esphome/components/online_image/__init__.py
> +        config[CONF_FORMAT],
```suggestion
        format,
```

2024-07-30 00:48 UTC, jesserockz commented on esphome/components/online_image/__init__.py
> +IMAGE_FORMAT = {"PNG": ImageFormat.PNG}  # Add new supported formats here
```suggestion

FORMAT_PNG = "PNG"

IMAGE_FORMAT = {FORMAT_PNG: ImageFormat.PNG}  # Add new supported formats here
```

2024-07-30 00:48 UTC, jesserockz commented on esphome/components/online_image/online_image.cpp
> +  if (auto_resize_()) {
> All uses of class members and member functions should be prefixed with `this->` to distinguish them from global functions in code review.
https://esphome.io/guides/contributing#codebase-standards

```suggestion
  if (this->auto_resize_()) {
```

2024-07-30 00:48 UTC, jesserockz commented on esphome/components/online_image/online_image.cpp
> +  PollingComponent::loop();
This does nothing
```suggestion
```

2024-07-30 00:48 UTC, jesserockz commented on esphome/components/online_image/image_decoder.h
> +class DownloadBuffer {
Since this is a fixed size from creation, it should use `uint8_t *` instead of a vector, and use the `ExternalRAMAllocator` so it could be put into psram if available.

Anything to free up the internal ram helps.

2024-07-30 00:48 UTC, jesserockz commented on esphome/components/online_image/online_image.cpp
> +  auto container = this->downloader_ = this->parent_->get(this->url_);
The returned object here is a `unique_ptr`, you should not be assigning it to multiple variables. If you want to keep the member variable, remove the `auto container` and just access it via `this->downloader_`

2024-07-30 00:48 UTC, jesserockz commented on esphome/components/online_image/__init__.py
> +    cg.add_define("USE_ONLINE_IMAGE")
This is not really needed as it would only be used to remove code from other components
```suggestion
```

2024-07-30 00:48 UTC, jesserockz commented on esphome/components/online_image/__init__.py
> +        cg.add_library("pngle", "1.0.2")
Please add this to the root `platformio.ini` file

2024-07-30 19:30 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +        cv.Optional(CONF_FORMAT, default="PNG"): cv.enum(IMAGE_FORMAT, upper=True),
The idea was to also add an "AUTO" format, that would choose depending on the Content-Type returned by the server; and have that as default later on.
But since at the moment I'm not sure if the http_request component can be used to get extra headers, it's probably better to make `format` mandatory as you suggest, and it can always be made optional again later on without being a breaking change.

2024-07-30 19:35 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +        cg.add_define("ONLINE_IMAGE_PNG_SUPPORT")
I was not aware of that; thanks!

2024-07-30 19:50 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +  PollingComponent::loop();
thought it is good practice to call the super implementation; but I might have done too much Java lately ;-)

2024-07-30 20:12 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +  if (auto_resize_()) {
I thought for protected fields/methods (which have the "_" suffix) it was clear enough and not necessary, but I must have dreamed that exception.

2024-07-30 20:15 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +  auto container = this->downloader_ = this->parent_->get(this->url_);
This was just for convenience, no real need for the "auto container"

2024-07-30 20:32 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +  auto container = this->downloader_ = this->parent_->get(this->url_);
It's actually a shared_ptr, not a unique_ptr. Removed the `auto container` nevertheless.

2024-07-30 23:34 UTC, jesserockz requested changes
Still a few missing `this->` prefixes I noticed and could have easily missed some more. =)

2024-07-30 23:34 UTC, jesserockz commented on platformio.ini
> +    kikuchan98/pngle@1.0.2                 ; PNG decoder
This should be the component using it
```suggestion
    kikuchan98/pngle@1.0.2                 ; online_image
```

2024-07-30 23:34 UTC, jesserockz commented on esphome/components/online_image/__init__.py
> +CODEOWNERS = ["@guillempages"]
`http_request` may need its own configuration so it should not be auto laoded.
```suggestion
AUTO_LOAD = ["image"]
DEPENDENCIES = ["display", "http_request"]
CODEOWNERS = ["@guillempages"]
```

2024-07-30 23:34 UTC, jesserockz commented on esphome/components/online_image/online_image.cpp
> +  PollingComponent::loop();
In cases where the super function is doing something, yes. But it is an empty virtual function to allow optional implementations in the final component classes.

2024-07-30 23:34 UTC, jesserockz commented on esphome/components/online_image/image_decoder.cpp
> +  this->y_scale_ = static_cast<double>(image_->buffer_height_) / height;
```suggestion
  this->image_->resize_(width, height);
  this->x_scale_ = static_cast<double>(this->image_->buffer_width_) / width;
  this->y_scale_ = static_cast<double>(this->image_->buffer_height_) / height;
```

2024-07-30 23:34 UTC, jesserockz commented on esphome/components/online_image/image_decoder.cpp
> +      image_->draw_pixel_(i, j, color);
```suggestion
  auto width = std::min(this->image_->buffer_width_, static_cast<int>(std::ceil((x + w) * this->x_scale_)));
  auto height = std::min(this->image_->buffer_height_, static_cast<int>(std::ceil((y + h) * this->y_scale_)));
  for (int i = x * this->x_scale_; i < width; i++) {
    for (int j = y * this->y_scale_; j < height; j++) {
      this->image_->draw_pixel_(i, j, color);
```

2024-07-30 23:34 UTC, jesserockz commented on esphome/components/online_image/image_decoder.h
> +    buffer_ = allocator.allocate(size);
```suggestion
    this->buffer_ = allocator.allocate(size);
```

2024-07-30 23:34 UTC, jesserockz commented on esphome/components/online_image/online_image.cpp
> +  auto container = this->downloader_ = this->parent_->get(this->url_);
:facepalm: I even opened the source code and checked but somehow misread it. My bad

2024-07-30 23:34 UTC, jesserockz commented on esphome/components/online_image/image_decoder.h
> +  DownloadBuffer(size_t size) : size_(size) {
It is unlikely to be called due to the way the code is written now, but in case that changes in the future, please also implement a Destructor to free up the memory.

2024-07-30 23:34 UTC, jesserockz commented on esphome/components/online_image/online_image.cpp
> +  switch (type_) {
```suggestion
  switch (this->type_) {
```

2024-07-31 18:05 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +CODEOWNERS = ["@guillempages"]
Well, the idea was that if the default configuration works, there is no need to explicitly list the dependency, and only if there is something extra to do (like disabling SSL on arduino) you then explicitly add the dependency. I documented it also this way in the docs PR.
But it's not a big deal either way, and it might be clearer (and most important: consistent with the rest of the code base) to make it an explicit dependency.

2024-08-06 04:08 UTC, jesserockz approved these changes

2024-08-06 11:08 UTC, merged