Rework ip address
OttoWinter/esphomeyaml pull request #4729
Opened 2023-04-23 09:08 UTC by HeMan

# What does this implement/fix?

This is preparation work for more IPv6 targets. It changes `network::IPAddress` to use `ip_addr_t` instead of `std::array<uint8_t, 4>`. I haven't done a lot of testing but it compiles on all platforms as of now.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [x] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-05-07 20:42 UTC, HeMan commented
This now works on all hardware I've tried and passes all esphome tests. It still needs some work.

2023-05-11 03:00 UTC, jesserockz requested changes

2023-05-11 03:00 UTC, jesserockz commented on esphome/config_validation.py
> +    return IPAddress(value)
This loses all of the nice validation errors and removes the ability for a list (I doubt its used much, but it would be a breaking-change nonetheless)

It really should be `cv.Any(cv.ipv4, cv.ipv6)` (Obviously you would need to create `def ipv6(value)`)

2023-08-15 11:50 UTC, HeMan commented
I've decided to change scope a bit. The discussion in this PR are no longer relevant, I will thus close this PR and open a new, with correct description.

2023-08-15 11:50 UTC, closed without merging