Enable IPv6 for ESP32 arduino
OttoWinter/esphomeyaml pull request #4750
Opened 2023-04-27 19:51 UTC by HeMan

# What does this implement/fix?

Initial ESP32 Arduino platform IPv6 support. This should take it to about the same level as the ESP IDF IPv6 support.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: ipv6

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: wifissid
  password: !secret wifipwd

network:
  enable_ipv6: true

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-05-01 22:08 UTC, jesserockz requested changes

2023-05-01 22:08 UTC, jesserockz commented on esphome/components/network/__init__.py
> +        cg.add_build_flag("-DCONFIG_LWIP_IPV6_AUTOCONFIG")
When using IDF, these sdkconfig options default to true (at least the first one does), which is why I was explicitly setting them to the value set in config.

Would be good to continue to set the sdkconfig flags if using idf.

2023-05-02 06:41 UTC, HeMan commented on esphome/components/network/__init__.py
> +        cg.add_build_flag("-DCONFIG_LWIP_IPV6_AUTOCONFIG")
Does my fix look good?

2023-05-20 11:07 UTC, HeMan commented
Replaced by #4865

2023-05-20 11:07 UTC, closed without merging