Ipv6 8266
OttoWinter/esphomeyaml pull request #4759
Opened 2023-04-29 08:24 UTC by HeMan

# What does this implement/fix?

Initial ESP8266 IPv6 support. This should take it to about the same level as the ESP IDF IPv6 support.
**NOTE! It needs https://github.com/OttoWinter/ESPAsyncTCP/pull/4 to compile!**

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esphome:
  name: ipv6
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: wifissid
  password: !secret wifipwd

network:
  enable_ipv6: true

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-04-30 21:47 UTC, jesserockz commented
I have forked the library into the ESPHome org and published 1.2.3 to platformio. Please reopen your PR against that fork

2023-04-30 21:48 UTC, jesserockz commented
Related: https://github.com/esphome/esphome/pull/4764

2023-07-25 03:36 UTC, koo5 commented
i'm excited!

2023-08-08 12:54 UTC, HeMan commented
@jesserockz I think this is ready for merge now

2023-08-10 08:00 UTC, Nardol commented
After this PR, ESPHome will have IPv6 for all platforms, great!

2023-08-10 12:07 UTC, HeMan commented
> After this PR, ESPHome will have IPv6 for all platforms, great!

RP2040 is still missing IPv6, but I'll look into that soon.

2023-08-20 23:40 UTC, jesserockz requested changes

2023-08-20 23:40 UTC, jesserockz commented on esphome/components/network/__init__.py
> +            cg.add_build_flag("-DPIO_FRAMEWORK_ARDUINO_LWIP2_IPV6_LOW_MEMORY")
This is assuming the value in config is true, but it still might be false.

2023-08-20 23:40 UTC, jesserockz commented on esphome/components/network/__init__.py
> +        cv.Optional(CONF_ENABLE_IPV6): cv.boolean,
This should default to false for all platforms and then be utilised in `to_code` properly
```suggestion
        cv.Optional(CONF_ENABLE_IPV6, default=False): cv.boolean,
```

2023-08-21 06:05 UTC, HeMan commented on esphome/components/network/__init__.py
> +            cg.add_build_flag("-DPIO_FRAMEWORK_ARDUINO_LWIP2_IPV6_LOW_MEMORY")
Should be solved now

2023-08-21 06:05 UTC, HeMan commented on esphome/components/network/__init__.py
> +        cv.Optional(CONF_ENABLE_IPV6): cv.boolean,
Solved

2023-09-12 04:29 UTC, jesserockz commented on esphome/components/network/__init__.py
> +                cg.add_build_flag("-DPIO_FRAMEWORK_ARDUINO_LWIP2_IPV6_LOW_MEMORY")
Shouldnt these still be nested under checking its enabled?
```suggestion
            if config[CONF_ENABLE_IPV6]:
                cg.add_build_flag("-DCONFIG_LWIP_IPV6")
                cg.add_build_flag("-DCONFIG_LWIP_IPV6_AUTOCONFIG")
                if CORE.is_rp2040:
                    cg.add_build_flag("-DPIO_FRAMEWORK_ARDUINO_ENABLE_IPV6")
                if CORE.is_esp8266:
                    cg.add_build_flag("-DPIO_FRAMEWORK_ARDUINO_LWIP2_IPV6_LOW_MEMORY")
```

2023-09-12 04:31 UTC, jesserockz commented on esphome/components/network/__init__.py
line 24 could probably be removed since it defaults to False for all platforms so will always be `in config`

2023-09-12 05:54 UTC, HeMan commented on esphome/components/network/__init__.py
> +                cg.add_build_flag("-DPIO_FRAMEWORK_ARDUINO_LWIP2_IPV6_LOW_MEMORY")
Yes, fixed now. Thanks!

2023-09-12 20:04 UTC, jesserockz approved these changes

2023-09-12 20:05 UTC, merged