Micronova
OttoWinter/esphomeyaml pull request #4760
Opened 2023-04-29 14:16 UTC by Jorre05

# What does this implement/fix?

New component to support pellet stoves with a MicroNova board.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x ] ESP32
- [ x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
# Example config.yaml
micronova:
    enable_rx_pin: 7
    update_interval: 10s
    scan_memory_location: 0x00
    room_temperature:
        memory_address: 0x01
        name: Ambient temperature
        id: ambient_temperature
    thermostat_temperature:
        name: Stove thermostat temperature
    fumes_temperature:
        name: Smoke temperature
    stove_power:
        name: Stove current power
    fan_speed:
        fan_rpm_offset: 240
        name: Fan RPM
        id: fan_rpm
    memory_address_sensor:
        memory_location: 0x20
        memory_address: 0x7d
        name: Memory Adres sensor
        id: mem_adres_sensor
    stove_state:
        memory_address: 0x21
        name: Stove Status
    stove_switch:
        memory_location: 0x80
        memory_address: 0x21
        memory_data_on: 0x01
        memory_data_off: 0x06
        name: Switch stove on/off
    but_temp_up:
        name: Increase thermostat
        memory_location: 0xA0
        memory_address: 0x7D
        memory_data: 0x21
    but_temp_down:
        name: Decrease thermostat

## Checklist:
  - [x ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-04-29 14:40 UTC, Jorre05 commented
Any pointers on how to implement the script/ci-suggest-changes suggestions in an automated fashion? Also, the "script/clang-tidy for ESP32 Arduino 2/4" output baffles me.

2023-06-15 10:25 UTC, grahambrown11 commented
> Hey there @grahambrown11, mind taking a look at this pull request as it has been labeled with an integration (`alarm_control_panel`) you are listed as a [code owner](https://github.com/esphome/esphome/blob/dev/CODEOWNERS#L22) for? Thanks! (message by CodeOwnersMention)

What the heck... this seems you cherry picked commits instead of rebasing/merging from dev...

2023-06-15 10:50 UTC, Jorre05 commented
> What the heck... this seems you cherry picked commits instead of rebasing/merging from dev...

Humm, the conflict was on test1.yaml, but it looks like I messed things up during a rebase. Don't really know how to fix this now...

2023-06-15 13:27 UTC, grahambrown11 commented
> Humm, the conflict was on test1.yaml, but it looks like I messed things up during a rebase. Don't really know how to fix this now...

Sorry I just realised the tone of `What the heck...` is quite harsh 😳 
I was just surprised as to why I was getting tagged on an unrelated PR...
I'm also not 100% sure how to recover here... I would just copy my code out and start a fresh PR, maybe there are some git wizards out there who know better.

Sorry again if I came across negatively 😄

2023-06-15 16:59 UTC, Jorre05 commented
> Sorry again if I came across negatively 😄

No hard feelings here. I've redone de merge/rebase. That seems to have solved it, i think. But now the CI checks seem to fail, but it looks like a general problem, not specific to my code. I see the same errors in other recent pull requests.

2023-07-01 07:05 UTC, Jorre05 commented
@jesserockz I overheard a discussion on Discord. As I understand, my code assumes that the top level types (sensor, button, switch and text_sensor) are present but does not check that. I never bumped into that problem because my devices all have those included. Any pointers to some docs on how to properly code this to be in line with the coding standards?

2023-07-11 03:35 UTC, jesserockz requested changes

2023-07-11 03:35 UTC, jesserockz commented on esphome/components/micronova/__init__.py
> +AUTO_LOAD = ["sensor", "text_sensor", "button", "switch"]
Autoloading all the types is not an accepted solution. (Existing components are in the process of being migrated away from using this one at a time when time permits)

2023-07-11 03:36 UTC, jesserockz commented on esphome/components/micronova/__init__.py
> +AUTO_LOAD = ["sensor", "text_sensor", "button", "switch"]
You should be either making an interface class to talk between the parent and children and/or using `#ifdef USE_SENSOR` etc to remove the code that is not available to use.

2023-07-11 05:23 UTC, Jorre05 commented on esphome/components/micronova/__init__.py
> +AUTO_LOAD = ["sensor", "text_sensor", "button", "switch"]
Thanks for the review, I'll look into that.

2023-07-11 05:56 UTC, Jorre05 commented on esphome/components/micronova/__init__.py
> +AUTO_LOAD = ["sensor", "text_sensor", "button", "switch"]
@jesserockz 

I believe I can use the existing teleinfo component as an example for the interface implementation you suggest. Correct?
Also, are you suggesting I split the configuration like this?
```yaml
micronova:
  enable_rx_pin: 7
  update_interval: 10s

sensor:
  platform: micronova
    room_temperature:
      memory_address: 0x01
      name: Ambient temperature
      id: ambient_temperature
    thermostat_temperature:
      name: Stove thermostat temperature

button:
  platform: micronova
    but_temp_up:
      memory_address: 0x21
      name: Increase thermostat

switch:
  platform: micronova
  stove_switch:
    memory_location: 0x80
    name: Switch stove on/off

```

2023-07-14 11:07 UTC, Jorre05 commented on esphome/components/micronova/__init__.py
> +AUTO_LOAD = ["sensor", "text_sensor", "button", "switch"]
@jesserockz I reworked the component. Can you review?

2023-07-27 05:56 UTC, Jorre05 commented
Problems with IDF framework, converting back to draft.

2023-09-05 22:33 UTC, jesserockz requested changes

2023-09-05 22:33 UTC, jesserockz commented on esphome/components/micronova/button/__init__.py
> +CONF_BUT_TEMP_DOWN = "but_temp_down"
Config items should be well named, and since they are already buttons, they don't need the `but` prefix...
```suggestion
CONF_TEMPERATURE_UP = "temperature_up"
CONF_TEMPERATURE_DOWN = "temperature_down"
```

2023-09-05 22:33 UTC, jesserockz commented on esphome/components/micronova/sensor/__init__.py
> +            unit_of_measurement=UNIT_RPM,
This already exists in const.py
```suggestion
            unit_of_measurement=UNIT_REVOLUTIONS_PER_MINUTE,
```

2023-09-05 22:33 UTC, jesserockz commented on esphome/components/micronova/switch/__init__.py
> +CONF_STOVE_SWITCH = "stove_switch"
This doesnt need a suffix, its already under `switch`
```suggestion
CONF_STOVE = "stove"
```

2023-09-06 22:29 UTC, jesserockz commented on esphome/components/micronova/sensor/__init__.py
> +        ).extend(MICRONOVA_LISTENER_SCHEMA),
Should this sensor have device_class POWER and UoM Watts?

2023-09-07 03:43 UTC, Jorre05 commented on esphome/components/micronova/sensor/__init__.py
> +        ).extend(MICRONOVA_LISTENER_SCHEMA),
No. The stove output power is a number ranging from 0 tot 6 in my case.6 meaning 'full throttle', 0 is off.

2023-09-11 19:25 UTC, jesserockz requested changes

2023-09-11 19:25 UTC, jesserockz commented on esphome/components/micronova/micronova.cpp
> +  ESP_LOGD(TAG, "Write 4 bytes [%02X,%02X,%02X,%02X]", write_data[0], write_data[1], write_data[2], write_data[3]);
```suggestion
  ESP_LOGV(TAG, "Write 4 bytes [%02X,%02X,%02X,%02X]", write_data[0], write_data[1], write_data[2], write_data[3]);
```

2023-09-11 19:25 UTC, jesserockz commented on esphome/components/micronova/micronova.cpp
> +  ESP_LOGD(TAG, "First 2 bytes from [%02X:%02X] [%02X,%02X]", write_data[0], write_data[1], reply_data[0],
```suggestion
  ESP_LOGV(TAG, "First 2 bytes from [%02X:%02X] [%02X,%02X]", write_data[0], write_data[1], reply_data[0],
```

2023-09-11 19:25 UTC, jesserockz commented on esphome/components/micronova/micronova.cpp
> +  delay(STOVE_REPLY_DELAY);  // NOLINT
This 60ms delay is going to cause this component to log warnings every time. See https://github.com/esphome/issues/issues/4717

If possible, the code should be made asyncronous if it has to wait a long time before continuing to execute

2023-09-11 19:25 UTC, jesserockz commented on esphome/components/micronova/micronova.cpp
> +  ESP_LOGD(TAG, "First 2 bytes from [0x%02X:0x%02X] [0x%02X,0x%02X] dec: [%d,%d]", addr, reg, data[0], data[1], data[0],
```suggestion
  ESP_LOGV(TAG, "First 2 bytes from [0x%02X:0x%02X] [0x%02X,0x%02X] dec: [%d,%d]", addr, reg, data[0], data[1], data[0],
```

2023-09-11 19:25 UTC, jesserockz commented on esphome/components/micronova/sensor/__init__.py
> +                )
Honestly, if there is an `if` block for each type here, theres not much point in using a `for` loop over the keys. You might as well do it the same way as every other component:

```py
if room_temperature_config := config.get(CONF_ROOM_TEMPERATURE):
  room_temperature_sensor = ...
  
if thermostat_temperature_config := config.get(...):
  ...
```

2023-09-12 16:01 UTC, Jorre05 commented on esphome/components/micronova/micronova.cpp
> +  ESP_LOGD(TAG, "Write 4 bytes [%02X,%02X,%02X,%02X]", write_data[0], write_data[1], write_data[2], write_data[3]);
Done

2023-09-12 16:01 UTC, Jorre05 commented on esphome/components/micronova/micronova.cpp
> +  ESP_LOGD(TAG, "First 2 bytes from [%02X:%02X] [%02X,%02X]", write_data[0], write_data[1], reply_data[0],
done

2023-09-12 16:01 UTC, Jorre05 commented on esphome/components/micronova/micronova.cpp
> +  ESP_LOGD(TAG, "First 2 bytes from [0x%02X:0x%02X] [0x%02X,0x%02X] dec: [%d,%d]", addr, reg, data[0], data[1], data[0],
done

2023-09-12 16:01 UTC, Jorre05 commented on esphome/components/micronova/sensor/__init__.py
> +                )
Done, on all __init__'s

2023-09-12 16:09 UTC, Jorre05 commented on esphome/components/micronova/micronova.cpp
> +  delay(STOVE_REPLY_DELAY);  // NOLINT
This would be a hard nut to crack. The uart to the stove is a single line serial. You either transmit or receive. Moreover the protocol style request/reply based. One can easily mess things up by interrupting the stoves reply, a reply that came late for example. I'll give this some thought.

2023-09-12 16:25 UTC, Jorre05 commented on esphome/components/micronova/micronova.cpp
> +  delay(STOVE_REPLY_DELAY);  // NOLINT
Aha, there is a yield() function. I'll explore that.

2023-09-14 08:23 UTC, Jorre05 commented on esphome/components/micronova/micronova.cpp
> +  delay(STOVE_REPLY_DELAY);  // NOLINT
Ok, I've removed the delay() and split the code to process the request/reply asynchronously. But still reading two bytes at baud 1200 (higher baud rate is not possible) takes about 50ms. I don't think I can make it faster than this. But the processing time in loop() went from 160ms to 50ms.

2023-10-26 02:56 UTC, jesserockz requested changes
Mostly looks good, just a few changes below please =)

2023-10-26 02:56 UTC, jesserockz commented on esphome/components/micronova/micronova.h
> +  virtual void process_value_from_stove(int value_from_stove);
Should these be changed to enforce implementation in the final class?
```suggestion
  virtual void request_value_from_stove() = 0;
  virtual void process_value_from_stove(int value_from_stove) = 0;
```

2023-10-26 02:56 UTC, jesserockz commented on esphome/components/micronova/micronova.h
> +  void register_micronova_listener(MicroNovaSensorListener *l) { micronova_listeners_.push_back(l); }
We like to always prefix member variables with `this->` so it is always clear

Please make sure to update it everywhere.
```suggestion
  void register_micronova_listener(MicroNovaSensorListener *l) { this->micronova_listeners_.push_back(l); }
```

2023-10-26 02:56 UTC, jesserockz commented on esphome/components/micronova/micronova.h
> +  MicroNovaSwitchListener *get_stove_switch() { return stove_switch_; }
```suggestion
  void set_current_stove_state(uint8_t s) { this->current_stove_state_ = s; }
  uint8_t get_current_stove_state() { return this->current_stove_state_; }

  void set_stove(MicroNovaSwitchListener *s) { this->stove_switch_ = s; }
  MicroNovaSwitchListener *get_stove_switch() { return this->stove_switch_; }
```

2023-10-26 02:56 UTC, jesserockz commented on esphome/components/micronova/number/__init__.py
> +        )
These values are something that should go into the config as a default, and not hidden from the user in `to_code`. 

Two ways to do this are to add it to the final extend which will override the `MICRONOVA_LISTENER_SCHEMA`, 

or (maybe the better option) you can make `MICRONOVA_LISTENER_SCHEMA` a function/generator that will return the schema with the defaults if all number/sensor/switch etc will be setting these.

2023-10-26 02:56 UTC, jesserockz commented on esphome/components/micronova/switch/__init__.py
> +        .extend({cv.Optional(CONF_MEMORY_DATA_ON, default=0x01): cv.hex_int_range()}),
These should be in a single extend
```suggestion
        .extend(
            {
                cv.Optional(CONF_MEMORY_DATA_OFF, default=0x06): cv.hex_int_range(),
                cv.Optional(CONF_MEMORY_DATA_ON, default=0x01): cv.hex_int_range(),
            }
        ),
```

2023-10-26 17:00 UTC, Jorre05 commented on esphome/components/micronova/micronova.h
> +  virtual void process_value_from_stove(int value_from_stove);
Correct, done.

2023-10-26 17:01 UTC, Jorre05 commented on esphome/components/micronova/micronova.h
> +  void register_micronova_listener(MicroNovaSensorListener *l) { micronova_listeners_.push_back(l); }
Done, I hope I've spotted them all.

2023-10-26 17:01 UTC, Jorre05 commented on esphome/components/micronova/micronova.h
> +  MicroNovaSwitchListener *get_stove_switch() { return stove_switch_; }
Done.

2023-10-26 17:02 UTC, Jorre05 commented on esphome/components/micronova/switch/__init__.py
> +        .extend({cv.Optional(CONF_MEMORY_DATA_ON, default=0x01): cv.hex_int_range()}),
Done.

2023-10-26 17:03 UTC, Jorre05 commented on esphome/components/micronova/number/__init__.py
> +        )
Not entirely sure what you mean by function/generator. But, I've done my best.

2023-10-29 21:44 UTC, jesserockz commented on esphome/components/micronova/__init__.py
> +def MICRONOVA_LISTENER_SCHEMA(default_memory_location, default_memory_address):
This is exactly what I meant =)

2023-10-29 22:00 UTC, jesserockz commented on esphome/components/micronova/number/__init__.py
> +        ),
```suggestion
        .extend(
            {
                cv.Optional(CONF_MEMORY_WRITE_LOCATION, default=0xA0): cv.hex_int_range(),
                cv.Optional(CONF_STEP, default=1.0): cv.float_range(min=0.1, max=10.0),
            }
        ),
```

2023-10-29 22:03 UTC, jesserockz approved these changes, later dismissed

2023-10-29 22:15 UTC, jesserockz approved these changes

2023-11-03 06:54 UTC, merged