Add Alarm Control Panel
OttoWinter/esphomeyaml pull request #4770
Opened 2023-05-02 07:34 UTC by grahambrown11

# Implement Alarm Control Panel

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

A new `alarm_control_panel` that takes a list of `binary_sensors` that triggers the alarm when any of the sensor change to on, with the relevant API stuff to automatically create the Alarm Control Panel in HomeAssistant and provide state changes.

**Pull requests in progress:**
- ESPHome API: esphome/aioesphomeapi#427
- HomeAssistant: home-assistant/core#92357
- Docs: esphome/esphome-docs#2891

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esphome:
  name: alarm-panel
  friendly_name: Alarm
  comment: Alarm Control Panel

esp8266:
  board: d1_mini

logger:

api:

alarm_control_panel:
  id: alarm
  name: Panel
  codes:
    - "1234"
  requires_code_to_arm: true
  arming_time: 10
  delay_time: 15
  trigger_time: 30
  binary_sensors:
    - input: zone_1
    - input: zone_2
      bypass_armed_home: true
    - input: ha_test
  on_state:
    then:
      - lambda: !lambda |-
          ESP_LOGD("TEST", "State change %s", id(alarm)->to_string(id(alarm)->get_state()).c_str());
  on_triggered:
    then:
      - switch.turn_on: siren
  on_cleared:
    then:
      - switch.turn_off: siren

binary_sensor:
  - platform: gpio
    id: zone_1
    name: Zone 1
    device_class: door
    pin:
      number: D1
      mode: INPUT_PULLUP
      inverted: True
  - platform: gpio
    id: zone_2
    name: Zone 2
    device_class: motion
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
  - platform: homeassistant
    id: ha_test
    name: Zone 3
    entity_id: input_boolean.test_switch

switch:
  - platform: gpio
    id: siren
    name: Siren
    icon: mdi:alarm-bell
    pin: D7

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-05-02 23:20 UTC, dougiteixeira commented
It would be very useful to have the option of configuring multiple codes to control the alarm, so it would be possible for each person to have their own personal code.

Is this viable?

2023-05-03 06:48 UTC, grahambrown11 commented
> It would be very useful to have the option of configuring multiple codes to control the alarm, so it would be possible for each person to have their own personal code.
> 
> Is this viable?

@dougiteixeira I'll add it to the list for future enhancements

2023-05-03 15:27 UTC, nagyrobi commented
> > It would be very useful to have the option of configuring multiple codes to control the alarm, so it would be possible for each person to have their own personal code.
> > Is this viable?
> 
> @dougiteixeira I'll add it to the list for future enhancements

Yes this is a must. Moreover, combined with a [Wiegand](https://esphome.io/components/wiegand.html) reader, not only numeric codes could be used, but also proxy cards, which are actually strings of various lengths. Each family member could have a separate proxy keyring or card.

2023-05-04 08:10 UTC, grahambrown11 commented
@nagyrobi 

> not only numeric codes could be used

The code is a string cos if your code started with a zero and it was stored as a numeric then the leading zero is dropped...

> combined with a Wiegand reader

For now you could use a HomeAssistant Automation to translate the many codes from the Wiegand reader
 into 1 to disarm... but will definatly add more codes in future release, for local ESPHome automation.
I just want to get this out as there are a lot of moving parts between ESPHome and HomeAssistant.

2023-05-07 23:08 UTC, grahambrown11 commented
Multiple code support has now been added

2023-06-01 01:02 UTC, jesserockz requested changes
One big thing missing from this is `calls` As per all of the other entities types that can be controlled (from with YAML or API) have a `Call` class that is used to `control` them. Please modify this to follow that same pattern.

I think the base ACP code should be more basic, and we should look at making platforms similar to all the other entity types with most of this code falling into the `template` platform under ACP.

There's probably more, but these requests might change the code too much to bother reviewing everything right now. Please reach out if you have questions.

2023-06-01 01:02 UTC, jesserockz commented on esphome/components/alarm_control_panel/__init__.py
> +AlarmPanelNS = cg.esphome_ns.namespace("alarm_control_panel")
```suggestion
alarm_control_panel_ns = cg.esphome_ns.namespace("alarm_control_panel")
```

2023-06-01 01:02 UTC, jesserockz commented on esphome/components/alarm_control_panel/__init__.py
> +AlarmControlPanelComponent = AlarmPanelNS.class_("AlarmControlPanel", cg.Component)
Variable name should match the actual class name please.
```suggestion
AlarmControlPanel = AlarmPanelNS.class_("AlarmControlPanel", cg.Component)
```

2023-06-01 01:02 UTC, jesserockz commented on esphome/components/alarm_control_panel/alarm_control_panel.h
> +  std::vector<uint32_t> bypass_when_home_;
You should really just store a pointer to the binary_sensor

2023-06-01 01:02 UTC, jesserockz commented on esphome/components/alarm_control_panel/__init__.py
> +        cv.Optional(CONF_REQUIRES_CODE_TO_ARM, False): cv.boolean,
There should be a validation on `CONF_REQUIRES_CODE_TO_ARM` because it is ignored if you dont have any codes

2023-06-01 01:02 UTC, jesserockz commented on esphome/components/alarm_control_panel/__init__.py
> +        cv.Required(CONF_BINARY_SENSORS): cv.ensure_list(CONFIG_SCHEMA_BINARY_SENSOR),
I don't think binary_sensors should be **required**. personally I might want to write custom logic for my binary sensors (or any other sensor type) based on other factors and manually "trigger" the ACP to go into pending/triggered mode via yaml actions.

2023-06-01 01:02 UTC, jesserockz commented on esphome/components/alarm_control_panel/__init__.py
> +)
This should be wrapped in `cv.maybe_simple_id` to allow people not having to define a sub-object in yaml but just have a list of ids

2023-06-01 01:02 UTC, jesserockz commented on esphome/components/alarm_control_panel/alarm_control_panel.cpp
> +      ESP_LOGD(TAG, "After Arming Time");
This log message seems a bit random

2023-06-01 01:02 UTC, jesserockz commented on esphome/components/alarm_control_panel/alarm_control_panel.cpp
> +}
This should be changed to use constants within here, and also should be set based on features users are actually using. For instance I would never use ARM_HOME in my house so I would not want HA to show it.

You don't have to implement all the modes in this PR, but at least ARM_HOME should be optional based on config.

2023-06-04 09:11 UTC, grahambrown11 commented on esphome/components/alarm_control_panel/__init__.py
> +        cv.Required(CONF_BINARY_SENSORS): cv.ensure_list(CONFIG_SCHEMA_BINARY_SENSOR),
I'm not sure I fully understand your usecase, in my mind an alarm system is a bunch of binary sensors that trigger the alarm when armed...
You can always use a template binary sensor to turn non binary sensors (like ultrasonic distance) into a binary on/off when over/under a certain value...

2023-06-04 09:38 UTC, grahambrown11 commented
> One big thing missing from this is `calls` As per all of the other entities types that can be controlled (from with YAML or API) have a `Call` class that is used to `control` them. Please modify this to follow that same pattern.

Sure I'll work on that, didn't know there were patterns to follow 😅 

> I think the base ACP code should be more basic, and we should look at making platforms similar to all the other entity types with most of this code falling into the `template` platform under ACP.

I don't understand - I thought the `template` platform was for using Lambda which is advanced 🤔 this is basic from a user of ESPHome is it not?

2023-06-04 11:33 UTC, grahambrown11 commented on esphome/components/alarm_control_panel/alarm_control_panel.h
> +  std::vector<uint32_t> bypass_when_home_;
For the logic in the loop, I ignore the sensor when in the `bypass_when_home_` vector, I don't see how a pointer will help here... I have a vector of binary sensors above...

2023-06-05 16:14 UTC, nagyrobi commented on esphome/components/alarm_control_panel/__init__.py
> +        cv.Required(CONF_BINARY_SENSORS): cv.ensure_list(CONFIG_SCHEMA_BINARY_SENSOR),
I think Jesse thinks of an option to use the system the other way around too: have actions triggered from the other parts of the config. Eg. an extreme case a binary sensor could change the state of the alarm fine-tuned from _Binary Sensor Filters_ / _Binary Sensor Automation_ without having to create copies of it with different settings for other uses (eg. the same binary sensor would be useful for both Alarm and A/C overriding, but with different trigger delay settings). 

So it would be very well feasible that someone wouldn't want to specify any `binary_sensors` in Alarm Control Panel, but would just use Alarm's Automation Actions to trigger it. 

I think this is just really about making binary_sensors optional.

2023-06-05 20:15 UTC, jesserockz commented on esphome/components/alarm_control_panel/__init__.py
> +        cv.Required(CONF_BINARY_SENSORS): cv.ensure_list(CONFIG_SCHEMA_BINARY_SENSOR),
I'm not saying remove the `binary_sensors`, just don't force people to only have `binary_sensors` as the way to trigger the alarm from `armed` to `pending`. 
One use case could be instant triggering, where some sensors could be used to instantly trigger the alarm/sirens instead of going into pending/countdown mode.

2023-06-06 07:02 UTC, grahambrown11 commented on esphome/components/alarm_control_panel/__init__.py
> +        cv.Required(CONF_BINARY_SENSORS): cv.ensure_list(CONFIG_SCHEMA_BINARY_SENSOR),
Cool, I guess a less opinionated system is more flexible for everyone

2023-06-13 06:49 UTC, RoganDawes commented
I've been working on a UART integration with my Texecom Premier 832 alarm panel, which exposes the various sensors states as binary inputs, and provides controls for away arm/stay arm/disable, zone bypass, etc. The Texecom also has multiple partitions which can be armed and disarmed independently, but I'd love to be able to just extend the basic Alarm Control Panel classes to gain the automatic interfaces into e.g. the webserver and Home Assistant.

2023-06-14 21:50 UTC, jesserockz approved these changes

2023-06-15 00:34 UTC, merged