Add TR-502MSV Protocol
OttoWinter/esphomeyaml pull request #4791
Opened 2023-05-08 07:49 UTC by Mat931

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/3748

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
remote_receiver:
  filter: 15us
  pin:
    number: 26
    mode:
      input: True
      pullup: True
    inverted: False
  dump: [tr_502msv, raw]

remote_transmitter:
  pin: 25
  carrier_duty_percent: 100

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      inverted: true
    id: test
    filters:
      - delayed_on_off: 100ms
    on_press:
      - remote_transmitter.transmit_tr_502msv:
          group: 0x123
          device: all
          command: turn_on
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-06-20 23:59 UTC, jesserockz requested changes

2023-06-20 23:59 UTC, jesserockz commented on esphome/components/remote_base/tr_502msv_protocol.cpp
> +  out.set_raw(0);
I don't see the need for this when `set_raw` is called below, or `out` is not even returned.
```suggestion
```

2023-12-21 05:51 UTC, jesserockz submitted a review, later dismissed
I have made some changes to the struct to use a packed union to get and set the raw value without having to bitshift everytime. Please let me know if that still works for you.

2023-12-21 06:18 UTC, Mat931 commented
Thanks for taking a look!
Unfortunately I'm getting some compile errors on the ESP8266 with your changes. My config is different from the example above.
```
In file included from src/esphome.h:63,
                 from src/main.cpp:3:
src/esphome/components/remote_base/tr_502msv_protocol.h:26:12: note: offset of packed bit-field 'esphome::remote_base::TR502MSVData::<unnamed union>::<unnamed struct>::command' has changed in GCC 4.4
   26 |     struct {
      |            ^
src/main.cpp: In function 'void setup()':
src/main.cpp:756:3: error: too many initializers for 'esphome::remote_base::TR502MSVData'
  756 |   });
      |   ^
src/main.cpp:788:3: error: too many initializers for 'esphome::remote_base::TR502MSVData'
  788 |   });
      |   ^
src/main.cpp:820:3: error: too many initializers for 'esphome::remote_base::TR502MSVData'
  820 |   });
      |   ^
src/main.cpp:852:3: error: too many initializers for 'esphome::remote_base::TR502MSVData'
  852 |   });
      |   ^
src/main.cpp:892:3: error: too many initializers for 'esphome::remote_base::TR502MSVData'
  892 |   });
      |   ^
src/main.cpp:932:3: error: too many initializers for 'esphome::remote_base::TR502MSVData'
  932 |   });
      |   ^
```

2023-12-21 06:25 UTC, Mat931 commented
I updated the yaml example so you can reproduce the error

2023-12-22 00:33 UTC, jesserockz commented
Ok, ill take another look at this locally when I get some time.

2024-06-21 19:22 UTC, closed without merging

2024-06-21 19:28 UTC, Mat931 commented
Closed because it wasn't merged after a year and I don't really need it anymore.