Feature/grove tb6612 fng
OttoWinter/esphomeyaml pull request #4797
Opened 2023-05-09 07:19 UTC by max246

# What does this implement/fix?

I am working with this handy motor driver which can drive DC and Stepper motors : https://wiki.seeedstudio.com/Grove-I2C_Motor_Driver-TB6612FNG/
The good thing about this driver is the connectivity to be used over i2c rather than the usual hbridge and you can set the motor driver to standby to stop wasting power.

Methods implemented:
- grove_i2c_motor.motor_run
- grove_i2c_motor.motor_break
- grove_i2c_motor.motor_stop
- grove_i2c_motor.standby
- grove_i2c_motor.no_standby

At the current state, only DC motor is implemented but the code for the stepper motor is already ready to be expose via an action. I dont currently have a stepper motor so in my case I can only test a DC motor

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ x ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ x ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-05-09 19:12 UTC, HeMan commented on tests/test3.yaml
> +
These extra line feeds could be removed.

2023-05-12 18:17 UTC, kroimon commented on esphome/components/grove_i2c_motor/__init__.py
> +            cv.Required(CONF_NAME): cv.string,
What is the name used for?

2023-05-12 18:17 UTC, kroimon commented on esphome/components/grove_i2c_motor/grove_i2c_motor.cpp
> +  delayMicroseconds(100000);
Do you really need a 100 ms delay here? That feels overly long, especially if no other command directly follows.
Same question for the other delays in the code.

You could also remember the time of the last sent command and only delay right before sending the next command, if the time since the last command was too short.

2023-05-12 19:17 UTC, max246 commented on esphome/components/grove_i2c_motor/grove_i2c_motor.cpp
> +  delayMicroseconds(100000);
Probably I can remove them, it came from the offical library

2023-05-12 19:17 UTC, max246 commented on esphome/components/grove_i2c_motor/__init__.py
> +            cv.Required(CONF_NAME): cv.string,
I suppose it was nice to have a name but maybe I can make it optional?

2023-05-12 19:40 UTC, kroimon commented on esphome/components/grove_i2c_motor/__init__.py
> +            cv.Required(CONF_NAME): cv.string,
If it's just cosmetics because it's not used in code, remove them. Users can always just use comments in the YAML if they need additional information.

2023-05-14 14:21 UTC, descipher commented on esphome/components/grove_i2c_motor/grove_i2c_motor.h
> +/*
Embeding driver code may not be the most effective method, please consider using this method:

  platformio_libs:
    - https://github.com/Seeed-Studio/Grove_Motor_Driver_TB6612FNG.git

2023-05-14 14:49 UTC, max246 commented on esphome/components/grove_i2c_motor/grove_i2c_motor.h
> +/*
And writer a class as helper to use the imported library?

2023-05-14 15:06 UTC, descipher commented on esphome/components/grove_i2c_motor/grove_i2c_motor.h
> +/*
You should be able to just include the external Grove_Motor_Driver_TB6612FNG.h and use the same calls in the local component. So essentially yes.

2023-05-14 16:39 UTC, descipher approved these changes
Looks good to me.

2023-05-14 16:45 UTC, max246 commented
> Looks good to me.

I tried to use the library provided without the GitHub link, but is behind a version which had compile issues.

2023-05-14 16:53 UTC, descipher commented
> > Looks good to me.
> 
> I tried to use the library provided without the GitHub link, but is behind a version which had compile issues.

Yes, hit that type of issue b4, compliler barfs but the code is fine.

2023-05-14 21:17 UTC, jesserockz requested changes
Generally looks good, just a few "tips" to align better with the codebase =)

2023-05-14 21:17 UTC, jesserockz commented on esphome/components/grove_i2c_motor/__init__.py
> +            cv.Required(CONF_SPEED): cv.int_range(min=0, max=255),
You access these as templatable below, but they are not in the schema? Same for other actions below.
```suggestion
            cv.Required(CONF_CHANNEL): cv.templatable(cv.int_range(min=0, max=1)),
            cv.Required(CONF_SPEED): cv.templatable(cv.int_range(min=0, max=255)),
```

2023-05-14 21:17 UTC, jesserockz commented on esphome/components/grove_i2c_motor/grove_i2c_motor.cpp
> +  }
```suggestion
  speed = clamp<int16_t>(speed, -255, 255);
```

2023-05-14 21:17 UTC, jesserockz commented on esphome/components/grove_i2c_motor/grove_i2c_motor.cpp
> +void GroveMotorDriveTB6612FNG::dc_motor_run(uint8_t chl, int16_t speed) {
No need to shorten variable names, just makes it harder to understand
```suggestion
void GroveMotorDriveTB6612FNG::dc_motor_run(uint8_t channel, int16_t speed) {
```

2023-05-14 21:17 UTC, jesserockz commented on esphome/components/grove_i2c_motor/grove_i2c_motor.cpp
> +    steps = 32767;
```suggestion
  } else if (steps == INT16_MIN) {
    steps = INT16_MAX
```

2023-05-14 21:17 UTC, jesserockz commented on esphome/components/grove_i2c_motor/grove_i2c_motor.cpp
> +  }
```suggestion
  rpm = clamp<uint16_t>(rpm, 1, 300);
```

2023-05-14 21:17 UTC, jesserockz commented on esphome/components/grove_i2c_motor/grove_i2c_motor.cpp
> +  }
```suggestion
  rpm = clamp<uint16_t>(rpm, 1, 300);
```

2023-05-14 21:17 UTC, jesserockz commented on esphome/components/grove_i2c_motor/grove_i2c_motor.h
> +};
If you also `#include "esphome/core/helpers.h" at the top, each action can be made slightly simpler:
```suggestion
template<typename... Ts> class GROVETB6612FNGMotorRunAction : public Action<Ts...>, public Parented<GroveMotorDriveTB6612FNG> {
 public:
  TEMPLATABLE_VALUE(uint8_t, chl)
  TEMPLATABLE_VALUE(uint16_t, speed)

  void play(Ts... x) override {
    auto chl = this->chl_.value(x...);
    auto speed = this->speed_.value(x...);
    this->parent_->dc_motor_run(chl, speed);
  }
};
```

2023-07-08 10:55 UTC, max246 commented
@jesserockz could this be approved?

2023-07-11 03:59 UTC, jesserockz requested changes
Please add the actions to the test yaml file too

2023-07-11 09:41 UTC, max246 commented
> Please add the actions to the test yaml file too

Should be all good now

2023-07-12 01:41 UTC, jesserockz submitted a review, later dismissed

2023-07-12 03:02 UTC, jesserockz approved these changes

2023-07-12 03:02 UTC, merged