Integratoin LightwaveRF switches
OttoWinter/esphomeyaml pull request #4812
Opened 2023-05-12 18:36 UTC by max246

# What does this implement/fix?

This is an implemantion of [LightwaveRF](https://lightwaverf.com/) which allows to dump and send raw messages

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ x ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml

lightwaverf:
  read_pin: 13
  write_pin: 14

switch:
  - platform: template
    name: "Turn off sofa"
    id: light_off_ceiling_sofa
    turn_on_action:
      lightwaverf.send_raw:
        code:  [0x04, 0x00, 0x00, 0x00, 0x0f, 0x03, 0x0d, 0x09, 0x08, 0x08]
        name: "Sofa"
        repeat: 1
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-05-14 14:00 UTC, descipher commented
Looks good to me.

2023-07-08 10:55 UTC, max246 commented
@jesserockz  could this be approved?

2023-07-11 03:44 UTC, jesserockz requested changes
Please remove the EEPROM stuff, if you want to store state etc, then you can use `global_preferences->make_preference(...)` See `esphome/core/preferences.h`

2023-07-11 03:44 UTC, jesserockz commented on esphome/components/lightwaverf/__init__.py
> +"""
Commented code is not allowed

2023-07-11 07:28 UTC, max246 commented
> Please remove the EEPROM stuff, if you want to store state etc, then you can use `global_preferences->make_preference(...)` See `esphome/core/preferences.h`

I am going to remove the eeprom stuff which was part of an old library and I was meant to remove it.

I have to re-test the validation code before uncomment it, I totally forgot about it :(

2023-07-12 20:55 UTC, jesserockz requested changes

2023-07-12 20:55 UTC, jesserockz commented on esphome/components/lightwaverf/__init__.py
> +    return value
Im pretty sure the existing validation (`[cv.Any(cv.hex_uint8_t)]`) should prevent this custom validation form being necessary.

2023-07-12 22:09 UTC, kbx81 requested changes

2023-07-12 22:09 UTC, kbx81 commented on esphome/components/lightwaverf/LwRx.h
> +  bool lwrx_stats_enable = true;
Are you sure you want _all_ of these to be `public`?

2023-07-12 22:09 UTC, kbx81 commented on esphome/components/lightwaverf/LwTx.h
> +  InternalGPIOPin *tx_pin;
As with the receiver, should these _all_ really be `public`?

2023-07-12 22:09 UTC, kbx81 commented on esphome/components/lightwaverf/LwRx.cpp
> +  if (rx_paircount < RX_MAXPAIRS) {
```suggestion
  if (this->rx_paircount < RX_MAXPAIRS) {
```

It seems you've got a bunch of places throughout where you're referring to a member variable without the `this->` prefix. We tend to prefer this is appended to each use of class variables within the code base. Please fix this for all member variable uses throughout. 😇

2023-08-17 15:43 UTC, max246 commented
@kbx81 due to the interrupt system, these variables need to be outside. 
I think the PR is ready to merge

2023-08-22 16:14 UTC, max246 commented
@jesserockz any decision on this? :)

2023-09-05 22:20 UTC, jesserockz commented on esphome/components/lightwaverf/LwRx.h
> +  bool lwrx_stats_enable = true;
While these are public here, this is a class that is only protected in the main component. This should be fine.

2023-09-05 22:21 UTC, jesserockz approved these changes

2023-09-05 22:33 UTC, merged