add heating functionality to SI7021
OttoWinter/esphomeyaml pull request #4828
Opened 2023-05-15 19:20 UTC by max246

# What does this implement/fix?

add heating functionality to SI7021

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes  https://github.com/esphome/feature-requests/issues/47
**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3150

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-05-15 22:34 UTC, jesserockz requested changes

2023-05-15 22:34 UTC, jesserockz commented on esphome/components/sensor/__init__.py
Device classes are syncronised with Home Assistant automatically, if it doesnt exist already, you cant just add it.

2023-08-20 21:16 UTC, jesserockz commented on esphome/components/htu21d/sensor.py
> +            cv.Required(CONF_HEATER): sensor.sensor_schema(
This should not be required. (And I just noticed the temp and humidity are `Required` which I will change in a separate PR.
```suggestion
            cv.Optional(CONF_HEATER): sensor.sensor_schema(
```

2023-08-20 21:32 UTC, jesserockz requested changes, later dismissed

2023-08-20 21:32 UTC, jesserockz commented on esphome/components/htu21d/sensor.py
> +    ),
This allows for yaml such as this if there is only 1 htu21d platform in yaml as it can auto populate the id.
```yaml
- htu21d.set_heater_level: xx
```

```suggestion
    cv.maybe_simple_value(
        {
            cv.GenerateID(): cv.use_id(HTU21DComponent),
            cv.Required(CONF_LEVEL): cv.templatable(cv.int_),
        },
        key=CONF_LEVEL,
    ),
```

2023-08-20 21:32 UTC, jesserockz commented on esphome/components/htu21d/sensor.py
> +    ),
```suggestion
    cv.maybe_simple_value(
        {
            cv.GenerateID(): cv.use_id(HTU21DComponent),
            cv.Required(CONF_STATUS): cv.templatable(cv.boolean),
        },
        key=CONF_STATUS,
    ),
```

2023-08-20 22:20 UTC, max246 commented
@jesserockz  I suppoes I need tomake a doc update as well?

2023-08-22 07:12 UTC, max246 commented
> @jesserockz I suppoes I need tomake a doc update as well?

Ok that is done :)

2023-09-01 23:15 UTC, kbx81 approved these changes
LGTM

2023-09-02 00:03 UTC, merged