[ILI9XXX] Improve display transfer performance & add second FB
OttoWinter/esphomeyaml pull request #4833
Opened 2023-05-15 21:27 UTC by Fabian-Schmidt

# What does this implement/fix?

Improve transfer speed to SPI display - example WT32-SC01 480x320px display 16 bit color from ~215ms to 105ms.

Use improvement to add a second framebuffer so full display draw takes up to 195ms.

Second framebuffer is optional and used to detect changes by comparing last display to current display. Goal is to make writing of display lambda functions easier. As I can now use `fill` operation etc.

Typical ESP32 devices with display have PSRam. Smallest possible PSRam is 3MB. One framebuffer with 480x320px and 16 bit color uses 300kb.

All performance gain only on ESP32 Arduino. ESP32 IDF SPI is very very slow.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-05-15 21:55 UTC, nielsnl68 requested changes
Thanks @Fabian-Schmidt for taking over the touch to make the ili9xxx platform component much faster and better.

I have added 2 small change requests.

2023-05-15 21:55 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +      buffer_to_transfer_(pos, pos_16, sz);
`
      this->buffer_to_transfer_(pos, pos_16, sz);
`

to make it more consistent met the other changes you made below.

2023-05-15 21:55 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +uint32_t ILI9XXXDisplay::buffer_to_transfer_(uint32_t pos, uint32_t pos_16, uint32_t sz) {
Not sure of i see the  benefits to send `pos_16` as parameter in compare with just create the variable only when you are in `BITS_16` mode.

2023-05-16 07:40 UTC, Fabian-Schmidt commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +      buffer_to_transfer_(pos, pos_16, sz);
fixed

2023-05-16 07:41 UTC, Fabian-Schmidt commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +uint32_t ILI9XXXDisplay::buffer_to_transfer_(uint32_t pos, uint32_t pos_16, uint32_t sz) {
I was playing with performance optimizations and this one is not worth it. Removed the parameter.

2023-05-16 07:42 UTC, Fabian-Schmidt commented
Thanks @nielsnl68 for this very quick feedback on the changes.

2023-10-13 00:44 UTC, closed without merging