Component.ld2420
OttoWinter/esphomeyaml pull request #4847
Opened 2023-05-17 02:53 UTC by descipher

# What does this implement/fix?

Adds the HLK-LD2420 mmWave Radar module component.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> 
**Working on it** 

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
external_components:
  - source: github://descipher/esphome@component.ld2420
    components: [ ld2420 ]
    refresh: 0s

esphome:
  name: presence-1
  friendly_name: presence-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<your.api.key>"

ota:
  password: "<your.ota.password>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
 ap:
    ssid: presense-1
    password: !secret captive_password

captive_portal:

web_server:
  port: 80

uart:
  id: ld2420_uart
  tx_pin: GPIO16 
  rx_pin: GPIO17
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

# The LD2420 has 16 time gate intervals (0-15) with a gate resolution of 0.75 meters
ld2420:
  presence_time_window: 120s
  detection_gate_minimum : 1
  detection_gate_maximum: 12
  g0_move_threshold: 60000
  g0_still_threshold: 40000
  g1_move_threshold: 30000
  g1_still_threshold: 20000
  g2_move_threshold: 3000
  g2_still_threshold: 400
  g3_move_threshold: 2000
  g3_still_threshold: 3000
  g4_move_threshold: 500
  g4_still_threshold: 300
  g5_move_threshold: 400
  g5_still_threshold: 200
  g6_move_threshold: 400
  g6_still_threshold: 200
  g7_move_threshold: 300
  g7_still_threshold: 150
  g8_move_threshold: 300
  g8_still_threshold: 150
  g9_move_threshold: 300
  g9_still_threshold: 100
  g10_move_threshold: 300
  g10_still_threshold: 100
  g11_move_threshold: 250
  g11_still_threshold: 100
  g12_move_threshold: 250
  g12_still_threshold: 100
  g13_move_threshold: 200
  g13_still_threshold: 100
  g14_move_threshold: 200
  g14_still_threshold: 100
  g15_move_threshold: 200
  g15_still_threshold: 100

sensor:
  - platform: ld2420
    moving_distance:
      name : Moving Distance

binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-05-18 20:39 UTC, max246 commented
Why would you keep 

```
external_components:
  - source: github://descipher/esphome@component.ld2420
    components: [ ld2420 ]
    refresh: 0s
```

when the code is in the codebase?

2023-05-18 20:53 UTC, descipher commented
Its not in the code base, its in a PR which currently lives at https://github.com/descipher/esphome@component.ld2420. It may become part of the code if it is accepted. 
Now, as far as the example goes it makes it easy for people to field test on their ha install even as it changes without hassles.

2023-05-18 20:56 UTC, max246 commented
> 

I guess this config should reflect the use of this PR rather than external use otherwise it will be confusing if I checkout your PR and run it locally. It will pull the external library rather the one on the branch.

It makes sense in your github README but here is missleading

2023-05-19 06:32 UTC, max246 requested changes
Would be great to remove the ignore lint and if there is any potential issue with module other than esp32, let's block to only esp32

2023-05-19 06:32 UTC, max246 commented on esphome/components/ld2420/__init__.py
> +                min=0, max=65535
Can use the constant instead of 65535 : `UINT16_MAX`

2023-05-19 06:32 UTC, max246 commented on esphome/components/ld2420/ld2420.h
> +static const char *err_message[] = {"None", "Unknown", "Timeout"};  // NOLINT
Why adding `// NOLINT` ? Can we resolve it rathen than ignoring it?

2023-05-19 06:32 UTC, max246 commented on tests/test1.yaml
> +  g1_still_threshold: 20000
Would be better to add all the gates to ensure it always works

2023-05-19 06:32 UTC, max246 commented on esphome/components/ld2420/ld2420.cpp
> +      for (uint16_t index = 0; index < (CMD_REG_DATA_REPLY_SIZE *  // NOLINT
We shouldn't ignore the lint check

2023-05-19 06:32 UTC, max246 commented on esphome/components/ld2420/ld2420.cpp
> +      }  // NOLINT
Same here shouldn't ignore it

2023-05-19 06:32 UTC, max246 commented on esphome/components/ld2420/ld2420.cpp
> +                                        ((buffer[CMD_FRAME_DATA_LENGTH] - 4) / CMD_ABD_DATA_REPLY_SIZE));
Shouldn't ignore it

2023-05-19 06:32 UTC, max246 commented on esphome/components/ld2420/ld2420.cpp
> +      }  // NOLINT
Shouldn't ignore it

2023-05-19 06:32 UTC, max246 commented on esphome/components/ld2420/ld2420.cpp
> +    // TODO setup a dynamic method e.g. millis time count etc. to tune for non ESP32 240Mhz devices
You can define the module to work only if esp32 to ensure it doesn't break

2023-05-19 06:32 UTC, max246 commented on esphome/components/ld2420/ld2420.cpp
> +                                                     uint32_t timeout) {
Shouldn't ignore it

2023-05-19 13:10 UTC, GelidusResearch commented on esphome/components/ld2420/ld2420.cpp
> +      for (uint16_t index = 0; index < (CMD_REG_DATA_REPLY_SIZE *  // NOLINT
In this case the warn indicated the index is potentially too small for the size if the input buffer count. However the condition for this to occur is completed mitigated in the frame size check above. The buffer count for the future stream data processing needs to be greater that 1500. Could separate the stream processing as an option but we don't even know what that will look like until Hi-Link provides docs for it. Ditto on the related.

2023-05-19 13:12 UTC, GelidusResearch commented on esphome/components/ld2420/ld2420.cpp
> +    // TODO setup a dynamic method e.g. millis time count etc. to tune for non ESP32 240Mhz devices
Clearly a TODO, it safely works for slower mpu's.

2023-05-19 13:13 UTC, GelidusResearch commented on esphome/components/ld2420/ld2420.cpp
> +                                                     uint32_t timeout) {
No risk.

2023-05-19 13:18 UTC, GelidusResearch commented on esphome/components/ld2420/__init__.py
> +                min=0, max=65535
True, updating it.

2023-05-19 13:23 UTC, GelidusResearch commented on esphome/components/ld2420/__init__.py
> +                min=0, max=65535
Wait, this is python and thats not a typical convention for coding it. Lets leave that alone.

2023-05-19 13:47 UTC, GelidusResearch commented on esphome/components/ld2420/ld2420.h
> +static const char *err_message[] = {"None", "Unknown", "Timeout"};  // NOLINT
I can add constexpr in this case. It may possibly optimize better but the code will be effectively the same.

2023-05-19 13:49 UTC, GelidusResearch commented on esphome/components/ld2420/ld2420.cpp
> +      }  // NOLINT
That one does nothing .. removing it.

2023-05-19 13:59 UTC, GelidusResearch commented on tests/test1.yaml
> +  g1_still_threshold: 20000
I don't think there is value in that. The tests are already very long and that would only validate more of the same code gen test. I was thinking the the other direction and do only one for each specific code gen test as a rule. Maybe something that @jesserockz should dialogue on?

2023-05-19 14:04 UTC, max246 commented on esphome/components/ld2420/__init__.py
> +                min=0, max=65535
In previous PRs @jesserockz  has requested to use the const rather than typing the value.

2023-05-19 14:06 UTC, max246 commented on esphome/components/ld2420/ld2420.cpp
> +                                                     uint32_t timeout) {
What was the lint issue? It looks odd to add to the function when it can be dealt with

2023-05-19 14:13 UTC, GelidusResearch commented on esphome/components/ld2420/ld2420.cpp
> +                                                     uint32_t timeout) {
If you don't know then commenting "should't ignore it" is not apropriate.
It's a user input variable swap potentential warning. Please stop spamming the PR.

2023-05-19 14:16 UTC, max246 commented on esphome/components/ld2420/ld2420.cpp
> +                                                     uint32_t timeout) {
Ignoring lint is an anti pattern of coding! @jesserockz  put these checks in place to keep a code quality not because it is fun. Don't ignore lint! Fix them!

2023-05-19 14:48 UTC, GelidusResearch commented on esphome/components/ld2420/__init__.py
> +                min=0, max=65535
Sir there are 2 instances of the UINT16_MAX const in the entire repo, none are in python files. There are 0 discussions with the term. Stop spamming the PR.

2023-05-20 20:11 UTC, ssieb commented on tests/test1.yaml
> +  g1_still_threshold: 20000
There was recently some discussion about this because there was a non-tested option in a component that broke the compile.  I suppose it's ok in this case because they all have default values.

2023-05-20 20:13 UTC, ssieb commented on esphome/components/ld2420/ld2420.h
> +#endif
Please change it to use callbacks and separate files instead of having to `#ifdef` stuff.  The `sensor` and `binary_sensor` code will go in separate directories and will only get included if used.

2023-05-20 20:15 UTC, ssieb commented on esphome/components/ld2420/ld2420.cpp
> +float LD2420Component::get_setup_priority() const { return setup_priority::AFTER_CONNECTION; }
Why did you pick this priority?

2023-05-20 20:26 UTC, ssieb commented
I changed the `external_components` config to use the PR format instead.

2023-05-20 20:29 UTC, GelidusResearch commented on esphome/components/ld2420/ld2420.cpp
> +float LD2420Component::get_setup_priority() const { return setup_priority::AFTER_CONNECTION; }
I forgot about that, It was set to allow me observe setup log activity wirelessly, we can bump it up to a more resonable one now.

2023-05-20 20:32 UTC, GelidusResearch commented on esphome/components/ld2420/ld2420.h
> +#endif
Yes no default could fault a call. Noted.

2023-05-20 20:44 UTC, jesserockz commented on esphome/components/ld2420/__init__.py
> +                min=0, max=65535
`cv.uint16` is what you want

2023-05-20 21:00 UTC, GelidusResearch commented on esphome/components/ld2420/__init__.py
> +                min=0, max=65535
Makes sense now, thanks.

2023-05-21 01:04 UTC, ssieb commented on esphome/components/ld2420/ld2420.h
> +#endif
There are various ways to do it, but for this component, the `matrix_keypad` and `vbus` components would be good examples.  If you need more guidance on how to do it, come ask us on discord.

2023-05-21 20:55 UTC, ssieb commented on esphome/components/ld2420/ld2420.h
> +static const char *err_message[] = {"None", "Unknown", "Timeout"};  // NOLINT
What's the lint error for this?

2023-05-21 21:07 UTC, descipher commented on esphome/components/ld2420/ld2420.h
> +static const char *err_message[] = {"None", "Unknown", "Timeout"};  // NOLINT
That's suppressed with static constexpr const char *ERR_MESSAGE[] = {"None", "Unknown", "Timeout"}; it was just complaining about a global array pointer being writable.

2023-05-29 01:26 UTC, descipher commented on esphome/components/ld2420/ld2420.h
> +#endif
Completed.

2023-06-30 21:56 UTC, EVSalomon commented
I testet that implementation and found a weird behaviour on my wemos mini.
After the first upload, the sensor is working, but after a reboot the wemos mini wont recognize the sensor again.
Only way to get it back working, is to rename the sensors and compile it again.

The Firmware Version is v1.5.4

YAML of the wemos mini:

```
external_components:
  - source: github://pr#4847
    components: [ ld2420 ]
    refresh: 0s

esphome:
  name: pir
  friendly_name: PIR

esp8266:
  board: d1_mini

# Enable logging
logger:
  
# Enable Home Assistant API
api:
  encryption:
    key: xxxxxx

ota:
  password: xxxxxxx

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: xxxxx
    password: xxxxxxx

captive_portal:
  
web_server:
  port: 80

uart:
  id: ld2420_uart
  rx_pin: GPIO13 #(D7)
  tx_pin: GPIO15  #(D8)
  baud_rate: 115200
  parity: NONE
  stop_bits: 1



ld2420:
  presence_time_window: 5s
  detection_gate_min: 1
  detection_gate_max: 12
  g0_move_threshold: 60000
  g0_still_threshold: 40000
  g1_move_threshold: 30000
  g1_still_threshold: 20000
  g2_move_threshold: 400
  g2_still_threshold: 200
  g3_move_threshold: 250
  g3_still_threshold: 200
  g4_move_threshold: 250
  g4_still_threshold: 200
  g5_move_threshold: 250
  g5_still_threshold: 200
  g6_move_threshold: 250
  g6_still_threshold: 200
  g7_move_threshold: 250
  g7_still_threshold: 150
  g8_move_threshold: 250
  g8_still_threshold: 150
  g9_move_threshold: 250
  g9_still_threshold: 100
  g10_move_threshold: 250
  g10_still_threshold: 100
  g11_move_threshold: 250
  g11_still_threshold: 100
  g12_move_threshold: 250
  g12_still_threshold: 100
  g13_move_threshold: 200
  g13_still_threshold: 100
  g14_move_threshold: 200
  g14_still_threshold: 100
  g15_move_threshold: 200
  g15_still_threshold: 100
    
#sensor:
#  - platform: ld2420
#    moving_distance:
#      name : Moving Distance

binary_sensor:
  - platform: gpio
    pin: D1
    name: "Movement"
    device_class: motion

  - platform: ld2420
    has_target:
      name: Presence detected   

```


The Sensor on pin D1 is my PIR-Sensor and is always working correctly.

2023-07-01 05:35 UTC, descipher commented
Esp8266 software serial is not going to work very good, you could try uart0, it can run up to 115200. But I still do not recommend it, an esp32 in your friend.

2023-07-01 10:10 UTC, EVSalomon commented
With uart2 my wemos mini is working fine beside the restart probleme.
With uart0 it werent working. (also with baudrate 0 and the logger setting)
In best case my lolin32 only get the firmware-version and it always shows detected. It refreshed the distance but not the detection status. After restart on a other place it wasnt working to. It doesnt show firmware-version or other sensor values.
Its very strange.

Maybe i have to buy some new ones. Can you recommend a small (cheap) esp32 board?

2023-07-02 02:28 UTC, descipher commented
It was developed on a generic esp32 development board. Aliexpress has em for cheap.

2023-07-02 06:18 UTC, qkddn49 commented
esp8266 WeMos D1 Mini and esp32 Mini Does Not Work
GPIO1, GPIO3 TX, RX Can't Read Values At All
Esp8266 WeMos D1 Mini TX2, RX2 does not work.
Is it only possible on certain boards?
Example esp32 Using GPIO16, GPIO17 Pin, TX1, RX1?

2023-07-02 13:50 UTC, descipher commented
> esp8266 WeMos D1 Mini and esp32 Mini Does Not Work
> GPIO1, GPIO3 TX, RX Can't Read Values At All
> Esp8266 WeMos D1 Mini TX2, RX2 does not work.
> Is it only possible on certain boards?
> Example esp32 Using GPIO16, GPIO17 Pin, TX1, RX1?

The esp8266 is generally to slow to handle io rates @ 256000 or 115200 and all the other crypto processing etc. and thats why the esp32 is noted as a supported processor. Sharing uart0 is not recommended so yes an alternate uart is the only way I could get good result. It is possible to slow the baud rate down but I have not tested it.

2023-08-11 23:35 UTC, qkddn49 commented
Is it more sensitive if the number is high?

2023-08-12 06:27 UTC, descipher commented
> 

The value represents the signal threshold, the lower the threshold the higher it’s sensitively will be.

2023-08-12 06:29 UTC, qkddn49 commented
> 

Thank you.

2023-08-14 05:03 UTC, descipher commented
@ssieb @jesserockz It would be appreciated if this PR were to be reviewed soon.

2023-08-15 08:42 UTC, ootktk commented
I tried this on both ESP8266 and ESP32, 95% of the time it doesn't seem to be able to communicate with the sensor, not even the firmware version is returned. Tried the restart switch like @EVSalomon with no success, power cycle does not help either. On the rare occasion that it works, my LD2420 firmware is showing v1.5.6. Even when it works, the distance freezes within the first few seconds. I'm quite lost on this

2023-08-15 12:20 UTC, descipher commented
> I tried this on both ESP8266 and ESP32, 95% of the time it doesn't seem to be able to communicate with the sensor, not even the firmware version is returned. Tried the restart switch like @EVSalomon with no success, power cycle does not help either.
> 
> On the rare occasion that it works, my LD2420 firmware is showing v1.5.6. Even when it works, the distance freezes within the first few seconds. @descipher have you tried your code on v1.5.6 firmware?

That sounds like you do not have good power to the ld2420.
How are you powering it? Those 3.3v serial interface outputs are NOT good enough.
I have not run the v1.5.6 firmware yet. My last shipment was v1.5.4 so they are  obviously fixing issues but that should not cause what you are experiencing.

2023-08-16 03:09 UTC, ootktk commented
> > I tried this on both ESP8266 and ESP32, 95% of the time it doesn't seem to be able to communicate with the sensor, not even the firmware version is returned. Tried the restart switch like @EVSalomon with no success, power cycle does not help either.
> > On the rare occasion that it works, my LD2420 firmware is showing v1.5.6. Even when it works, the distance freezes within the first few seconds. @descipher have you tried your code on v1.5.6 firmware?
> 
> That sounds like you do not have good power to the ld2420. How are you powering it? Those 3.3v serial interface outputs are NOT good enough. I have not run the v1.5.6 firmware yet. My last shipment was v1.5.4 so they are obviously fixing issues but that should not cause what you are experiencing.

its unlikely to be a power supply issue as it works OK with the HLK configuration interface via the same power source. I have several other LD2420 that's powered from the same type of AMS1117 regulator that's working fine for months (but only with binary output on pin OT2 not UART).

HLK staffs have informed that the latest factory firmware is v1.5.8 but they're not providing any info on how to reflash existing units

2023-08-16 04:37 UTC, descipher commented
> HLK staffs have informed that the latest factory firmware is v1.5.8 but they're not providing any info on how to reflash existing units

I can flash them using any j-link interface but they have not published the firmware yet.

2023-08-16 04:50 UTC, descipher commented
@ootktk Can you post the YAML config your are using?

2023-08-16 05:08 UTC, ootktk commented
```
external_components:
  - source: github://pr#4847
    components: [ ld2420 ]
    refresh: 0s

esp32:
  board: esp32dev

esphome:
  name: esp-radar-04
  friendly_name: esp-radar-04

# Enable logging
logger:
  baud_rate: 0
  level: verbose

# Enable Home Assistant API
api:
  encryption:
    key: xxxxxxx

ota:
  password: xxxxxxx

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Radar-04 Fallback Hotspot"
    password: xxxxxxx

web_server:
  port: 80

uart:
  id: ld2420_uart
  tx_pin: GPIO17 
  rx_pin: GPIO16
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

button:
  - platform: restart
    name: "esp-radar-04-platform-restart"

# The LD2420 has 16 time gate intervals (0-15) with a gate resolution of 0.75 meters
ld2420:
  presence_time_window: 5s
  detection_gate_min: 1
  detection_gate_max: 12
  g0_move_threshold: 60000
  g0_still_threshold: 40000
  g1_move_threshold: 30000
  g1_still_threshold: 20000
  g2_move_threshold: 400
  g2_still_threshold: 200
  g3_move_threshold: 250
  g3_still_threshold: 200
  g4_move_threshold: 250
  g4_still_threshold: 200
  g5_move_threshold: 250
  g5_still_threshold: 200
  g6_move_threshold: 250
  g6_still_threshold: 200
  g7_move_threshold: 250
  g7_still_threshold: 150
  g8_move_threshold: 250
  g8_still_threshold: 150
  g9_move_threshold: 250
  g9_still_threshold: 100
  g10_move_threshold: 250
  g10_still_threshold: 100
  g11_move_threshold: 250
  g11_still_threshold: 100
  g12_move_threshold: 250
  g12_still_threshold: 100
  g13_move_threshold: 200
  g13_still_threshold: 100
  g14_move_threshold: 200
  g14_still_threshold: 100
  g15_move_threshold: 200
  g15_still_threshold: 100

sensor:
  - platform: ld2420
    moving_distance:
      name : Moving Distance

binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence
    
```

2023-08-16 05:11 UTC, ootktk commented
i also tried GPIO1 and GPIO3 on ESP32 as well as on esp8266 as below

```
esp8266:
  board: esp01_1m

uart:
  id: ld2420_uart
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200
  parity: NONE
  stop_bits: 1
```

2023-08-16 12:58 UTC, descipher commented
> baud_rate: 0
>   level: verbose

@ootktk Please test after removing these two lines.

2023-08-16 16:00 UTC, descipher commented
@ootktk This is really odd, I have an error in my YAML config that is working fine.
Can you try this out.

Your YAML tx pin is GPIO17.

~~~
uart:
  id: ld2420_uart
  tx_pin: GPIO17
  rx_pin: GPIO16 
  baud_rate: 115200
  parity: NONE
  stop_bits: 1
~~~

My YAML is reversed but the code works!

~~~
uart:
  id: ld2420_uart
  tx_pin: GPIO16 
  rx_pin: GPIO17
  baud_rate: 115200
  parity: NONE
  stop_bits: 1
~~~

Can you switch your pin map and physical connections to test if it functions?
Then I can investigate why this even worked.

2023-08-16 16:29 UTC, ootktk commented
![image](https://github.com/esphome/esphome/assets/59531692/5ef93692-060f-433f-92d6-539a4c9714ca)
this is the output after removing the 2 logger lines as suggested (pretty much the same as what I had before)

2023-08-16 16:39 UTC, ootktk commented
> @ootktk This is really odd, I have an error in my YAML config that is working fine. Can you try this out.
> 
> Your YAML tx pin is GPIO17.
> 
> ```
> uart:
>   id: ld2420_uart
>   tx_pin: GPIO17
>   rx_pin: GPIO16 
>   baud_rate: 115200
>   parity: NONE
>   stop_bits: 1
> ```
> 
> Mine YAML is reversed but the code works!
> 
> ```
> uart:
>   id: ld2420_uart
>   tx_pin: GPIO16 
>   rx_pin: GPIO17
>   baud_rate: 115200
>   parity: NONE
>   stop_bits: 1
> ```
> 
> Can you switch your pin map and physical connections to test if it functions? Then I can investigate why this even worked.

actually I spotted this anomaly when first testing with your code, but I thought maybe you have your own reasons to swap it around. Anyways as long as the GPIO pins are not hardcoded in your code it shouldn't be the problem.

I tried using the same inverted pins as yours and it didn't work either.
![image](https://github.com/esphome/esphome/assets/59531692/b797dd8d-d861-40cd-9e66-0225cf4e3fe8)

2023-08-16 16:53 UTC, descipher commented
@ootktk Can you post the serial log with level: DEBUG
Should look like:

~~~
[D][ld2420:329]: Sending set config enable command: FF
[D][ld2420:295]: Tx: FD.FC.FB.FA.04.00.FF.00.02.00.04.03.02.01 (14)
[D][ld2420:117]: Rx: FD.FC.FB.FA.08.00.FF.01.00.00.02.00.20.00.04.03.02.01 (18)
[D][ld2420:211]: LD2420 reply - set config enable: CMD = FF success
[D][ld2420:407]: Sending read gate min max and timeout command:  8
[D][ld2420:295]: Tx: FD.FC.FB.FA.08.00.08.00.00.00.01.00.04.00.04.03.02.01 (18)
[D][ld2420:117]: Rx: FD.FC.FB.FA.10.00.08.01.00.00.01.00.00.00.0C.00.00.00.78.00.00.00.04.03.02.01 (26)
[D][ld2420:236]: LD2420 reply - read gate parameter(s):  8 success
[D][ld2420:243]: Data[ 0]: 00.00.00.01
[D][ld2420:243]: Data[ 1]: 00.00.00.0C
[D][ld2420:243]: Data[ 2]: 00.00.00.78
[D][ld2420:442]: Sending read firmware version command:  0
[D][ld2420:295]: Tx: FD.FC.FB.FA.02.00.00.00.04.03.02.01 (12)
[D][ld2420:117]: Rx: FD.FC.FB.FA.0C.00.00.01.00.00.06.00.76.31.2E.35.2E.34.04.03.02.01 (22)
[D][ld2420:253]: LD2420 reply - module firmware version:  v1.5.4 success
[D][ld2420:382]: Sending read gate 0 high/low theshold command:  8
[D][ld2420:295]: Tx: FD.FC.FB.FA.06.00.08.00.10.00.20.00.04.03.02.01 (16)
~~~

Also make sure your connecting 3.3v for power and not the dev boards VCC which is +5v

2023-08-16 22:11 UTC, descipher commented
@ootktk If you have one of these you can extract the v1.5.6 firmware with j-Command.
![image](https://github.com/esphome/esphome/assets/10734527/56390151-103a-4ff7-88ad-a5ae2596856e)

 e.g. 

~~~
J-Link>SaveBin x:\ld2410.bin 0x08000000 0x8000
Opening binary file for writing... [x:\ld2410.bin]
Reading 32768 bytes from addr 0x08000000 into file...O.K.
J-Link>
~~~

2023-08-17 02:50 UTC, ootktk commented
uh...the page is missing now...

```
INFO ESPHome 2023.7.1
INFO Reading configuration /config/esp-radar-04.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/4847/head
Failed config

external_components: [source /config/esp-radar-04.yaml:2]
  - 
    unable to access 'https://github.com/esphome/esphome.git/': Could not resolve host: github.com.
    source: github://pr#4847
    components: 
      - ld2420
    refresh: 0s
```

2023-08-17 03:56 UTC, jesserockz commented
> uh...the page is missing now...can't even compile
> 
> ```
> INFO ESPHome 2023.7.1
> INFO Reading configuration /config/esp-radar-04.yaml...
> INFO Updating https://github.com/esphome/esphome.git@pull/4847/head
> Failed config
> 
> external_components: [source /config/esp-radar-04.yaml:2]
>   - 
>     unable to access 'https://github.com/esphome/esphome.git/': Could not resolve host: github.com.
>     source: github://pr#4847
>     components: 
>       - ld2420
>     refresh: 0s
> ```

@ootktk Looks like you are simply having internet issues. Try again after a bit.

2023-08-17 04:00 UTC, jesserockz commented
@descipher Would you be able to implement similar changes to this platform as has been done for the ld2410 in #4434 to expose the configuration via number/select/switch etc?

2023-08-17 04:18 UTC, descipher commented
> @descipher Would you be able to implement similar changes to this platform as has been done for the ld2410 in #4434 to expose the configuration via number/select/switch etc?

@jesserockz The LD2420 does not work the same. They have not documented any engineering data formats like the LD2410. I could do something with automatic room noise ranging and or interactive number/selects etc. but it would not give us feed back like the LD2410.

2023-08-17 04:19 UTC, jesserockz commented
Ok not a problem then. Thanks

2023-08-17 05:19 UTC, ootktk commented
@descipher just to confirm, my config should be like this right?
```
uart:
  id: ld2420_uart
  tx_pin: GPIO17 
  rx_pin: GPIO16
  baud_rate: 115200
  parity: NONE
  stop_bits: 1
  debug:
    direction: both
```

2023-08-17 09:41 UTC, ootktk commented
@descipher emailed you the bins as I'm not sure if it can be posted here

2023-08-17 13:03 UTC, descipher commented
> @descipher just to confirm, my config should be like this right?
> 
> ```
> uart:
>   id: ld2420_uart
>   tx_pin: GPIO17 
>   rx_pin: GPIO16
>   baud_rate: 115200
>   parity: NONE
>   stop_bits: 1
>   debug:
>     direction: both
> ```

For debug serial logging you would setup this:

~~~
logger:
  level: DEBUG
~~~

2023-08-17 15:52 UTC, ootktk commented
OK i can now confirm that both my sensors which I've used for this test can't even communicate with the HLK tool, which explains why this component is not working for me.
So either the sensors are dead (which I'm not sure how or why) or they're just returning gibberish that even the HLK tool couldn't decipher. not sure how to proceed from here then since i dont have a j-link tool

2023-08-20 19:36 UTC, dlsnet commented
Integration works fine on ESP32-Wroom and DOESN'T work on ESP32-**S3**-WROOM-1 - I tried both sets of uart pins. 

[12:34:45][C][uart.arduino_esp32:124]: UART Bus 1:
[12:34:45][C][uart.arduino_esp32:125]:   TX Pin: GPIO43
[12:34:45][C][uart.arduino_esp32:126]:   RX Pin: GPIO44
[12:34:45][C][uart.arduino_esp32:128]:   RX Buffer Size: 256
[12:34:45][C][uart.arduino_esp32:130]:   Baud Rate: 115200 baud
[12:34:45][C][uart.arduino_esp32:131]:   Data Bits: 8
[12:34:45][C][uart.arduino_esp32:132]:   Parity: NONE
[12:34:45][C][uart.arduino_esp32:133]:   Stop bits: 1
[12:34:45][C][ld2420:012]: LD2420:
[12:34:45][C][ld2420:013]:   Firmware Version :

2023-08-21 01:55 UTC, ootktk commented
> Integration works fine on ESP32-Wroom and DOESN'T work on ESP32-**S3**-WROOM-1 - I tried both sets of uart pins.
> 
> [12:34:45][C][uart.arduino_esp32:124]: UART Bus 1: [12:34:45][C][uart.arduino_esp32:125]: TX Pin: GPIO43 [12:34:45][C][uart.arduino_esp32:126]: RX Pin: GPIO44 [12:34:45][C][uart.arduino_esp32:128]: RX Buffer Size: 256 [12:34:45][C][uart.arduino_esp32:130]: Baud Rate: 115200 baud [12:34:45][C][uart.arduino_esp32:131]: Data Bits: 8 [12:34:45][C][uart.arduino_esp32:132]: Parity: NONE [12:34:45][C][uart.arduino_esp32:133]: Stop bits: 1 [12:34:45][C][ld2420:012]: LD2420: [12:34:45][C][ld2420:013]: Firmware Version :

once it stopped working on ESP32-S3-WROOM-1 did you try to reconnect it back to ESP32-WROOM and see if it still works?

2023-08-21 02:55 UTC, descipher commented
> Integration works fine on ESP32-Wroom and DOESN'T work on ESP32-**S3**-WROOM-1 - I tried both sets of uart pins.
> 
> [12:34:45][C][uart.arduino_esp32:124]: UART Bus 1: [12:34:45][C][uart.arduino_esp32:125]: TX Pin: GPIO43 [12:34:45][C][uart.arduino_esp32:126]: RX Pin: GPIO44 [12:34:45][C][uart.arduino_esp32:128]: RX Buffer Size: 256 [12:34:45][C][uart.arduino_esp32:130]: Baud Rate: 115200 baud [12:34:45][C][uart.arduino_esp32:131]: Data Bits: 8 [12:34:45][C][uart.arduino_esp32:132]: Parity: NONE [12:34:45][C][uart.arduino_esp32:133]: Stop bits: 1 [12:34:45][C][ld2420:012]: LD2420: [12:34:45][C][ld2420:013]: Firmware Version :

What did you define for the board, framework and variant?

2023-08-21 04:14 UTC, dlsnet commented
> once it stopped working on ESP32-S3-WROOM-1 did you try to reconnect it back to ESP32-WROOM and see if it still works?

yes, the same radar module works when plugged into ESP32-WROOM and doesn't with ESP32-S3-WROOM-1

> What did you define for the board, framework and variant?

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

2023-08-21 04:56 UTC, descipher commented
> > once it stopped working on ESP32-S3-WROOM-1 did you try to reconnect it back to ESP32-WROOM and see if it still works?
> 
> yes, the same radar module works when plugged into ESP32-WROOM and doesn't with ESP32-S3-WROOM-1
> 
> > What did you define for the board, framework and variant?
> 
> esp32: board: esp32-s3-devkitc-1 framework: type: arduino

@dlsnet try this:
~~~
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
~~~

Try using these uart pins:

~~~
uart:
  id: uart_ld2420
  tx_pin: GPIO17
  rx_pin: GPIO18
~~~

2023-08-21 13:23 UTC, dlsnet commented
It didn't help. To be fair, ESPHope didn't do much after I made the suggested changed

[06:15:34][C][uart.arduino_esp32:124]: UART Bus 1:
[06:15:34][C][uart.arduino_esp32:125]:   TX Pin: GPIO17
[06:15:34][C][uart.arduino_esp32:126]:   RX Pin: GPIO18
[06:15:34][C][uart.arduino_esp32:128]:   RX Buffer Size: 256
[06:15:34][C][uart.arduino_esp32:130]:   Baud Rate: 115200 baud
[06:15:34][C][uart.arduino_esp32:131]:   Data Bits: 8
[06:15:34][C][uart.arduino_esp32:132]:   Parity: NONE
[06:15:34][C][uart.arduino_esp32:133]:   Stop bits: 1
[06:15:34][C][ld2420:012]: LD2420:
[06:15:34][C][ld2420:013]:   Firmware Version :        
[06:15:34][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'PIR'



INFO ESPHome 2023.8.1
INFO Reading configuration /config/esphome/mmwave-test.yaml...
INFO Updating https://github.com/descipher/esphome.git@component.ld2420
WARNING 'mmwave_test': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
INFO Generating C++ source...
INFO Compiling app...
Processing mmwave_test (board: esp32-s3-devkitc-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- ESPmDNS @ 2.0.0
|-- Wire @ 2.0.0
|-- ArduinoJson @ 6.18.5
|-- Improv @ 1.2.3
RAM:   [=         ]  13.1% (used 42936 bytes from 327680 bytes)
Flash: [=====     ]  46.7% (used 857345 bytes from 1835008 bytes)
========================= [SUCCESS] Took 4.96 seconds =========================

2023-08-21 15:02 UTC, descipher commented
Are you using this external?

~~~
external_components:
  - source: github://pr#4847
    components: [ ld2420 ]
    refresh: 0s
~~~

2023-08-21 16:50 UTC, dlsnet commented
i use this one:

external_components:
  - source: github://descipher/esphome@component.ld2420
    components: [ ld2420 ]
    refresh: 0s

2023-08-21 17:00 UTC, descipher commented
> i use this one:
> 
> external_components:
> 
> * source: github://descipher/esphome@component.ld2420
>   components: [ ld2420 ]
>   refresh: 0s

Should be fine then. 

Turn on serial debugging to see is any data is flowing.

~~~
uart:
  id: ld2420_uart
  tx_pin: GPIOxx 
  rx_pin: GPIOxx
  baud_rate: 115200
  parity: NONE
  stop_bits: 1
  debug:
    direction: both
~~~

2023-08-21 18:03 UTC, dlsnet commented
I don't see any data flow reflected in the log. Anyway, I ordered ld2410 - will see if this one works with my S3. if not, I always can go back to using old good esp32-wroom

2023-09-02 07:35 UTC, kbx81 requested changes
Thanks for working on this! I finally got some of these sensors this week and was playing around with them this evening -- they have fw version 1.5.6 and seem to work well.

I left a few comments, mostly centered around readability (code and logs) and a couple other oddball things I caught along the way. Overall, looking good!

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +        ESP_LOGD(TAG, "Rx: %s", format_hex_pretty(buffer, pos).c_str());
Let's maybe make this verbose or even very-verbose along with those below -- otherwise it really makes the logs unnecessarily noisy.

```suggestion
        ESP_LOGVV(TAG, "Rx: %s", format_hex_pretty(buffer, pos).c_str());
```

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +        ESP_LOGD(TAG, "Rx: %s", format_hex_pretty(buffer, pos).c_str());
Let's maybe make this verbose or even very-verbose along with those below -- otherwise it really makes the logs unnecessarily noisy.

```suggestion
        ESP_LOGVV(TAG, "Rx: %s", format_hex_pretty(buffer, pos).c_str());
```

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +    ESP_LOGD(TAG, "LD2420 reply - received frame is corrupt, data lenght exceeds 64 bytes.");
```suggestion
    ESP_LOGD(TAG, "LD2420 reply - received frame is corrupt, data length exceeds 64 bytes.");
```

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +    ESP_LOGD(TAG, "LD2420 reply - received frame is corrupt, data lenght is less than 2 bytes.");
```suggestion
    ESP_LOGD(TAG, "LD2420 reply - received frame is corrupt, data length is less than 2 bytes.");
```

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +        ESP_LOGD(TAG, "Data[%2X]: %s", reg_element, format_hex_pretty(cmd_reply_.data[reg_element]).c_str());
Let's maybe make this verbose or even very-verbose along with those below -- otherwise it really makes the logs unnecessarily noisy.

```suggestion
        ESP_LOGVV(TAG, "Data[%2X]: %s", reg_element, format_hex_pretty(cmd_reply_.data[reg_element]).c_str());
```

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +        ESP_LOGD(TAG, "Data[%2X]: %s", data_element, format_hex_pretty(cmd_reply_.data[data_element]).c_str());
Let's maybe make this verbose or even very-verbose along with those below -- otherwise it really makes the logs unnecessarily noisy.

```suggestion
        ESP_LOGVV(TAG, "Data[%2X]: %s", data_element, format_hex_pretty(cmd_reply_.data[data_element]).c_str());
```

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +    ESP_LOGD(TAG, "Tx: %s", format_hex_pretty(cmd_buffer, frame.length).c_str());
Let's maybe make this verbose or even very-verbose along with those below -- otherwise it really makes the logs unnecessarily noisy.

```suggestion
    ESP_LOGVV(TAG, "Tx: %s", format_hex_pretty(cmd_buffer, frame.length).c_str());
```

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.h
> +  u_int8_t set_config_mode_(bool enable);
Well this is weird, haha
```suggestion
  uint8_t set_config_mode_(bool enable);
```

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +    ESP_LOGCONFIG(TAG, "LD2420 module has failed to respond, check baud rate and serial connections.");
```suggestion
    ESP_LOGE(TAG, "LD2420 module has failed to respond, check baud rate and serial connections.");
```

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +    ESP_LOGCONFIG(TAG, "LD2420 module has failed to respond, check baud rate and serial connections.");
I think you also want to `mark_failed()` at this point

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +    for (uint8_t gate = 0; gate < 16; gate++) {
Could we make the number of gates a `const` somewhere? Helps with readability and it's just better practice. 😇

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +      } else if ((pos >= 64 && (memcmp(&buffer[pos - 5], &CMD_FRAME_HEADER, sizeof(CMD_FRAME_HEADER)) == 0) &&
What is 64? Could we use another `const` for this value?

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.h
> +static const uint16_t CMD_SYSTEM_MODE_NORMAL = 0x0064;
Totally nitpicking here but I like to alphabetize lists of vars like this as it makes it easier to find one at a glance. 😇 We also try to make a practice of this in other parts of the codebase.

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +  if (cmd_reply_.length > 64) {
Here's that 64 again -- could use a `const`, haha

2023-09-02 07:35 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +      } else if ((pos >= 64 && (memcmp(&buffer[pos - 5], &CMD_FRAME_HEADER, sizeof(CMD_FRAME_HEADER)) == 0) &&
Ah just saw in your comments: _"No command can exceed 64 bytes"_
Let's just make this a `const`, then. 😄

2023-09-02 08:55 UTC, kbx81 commented
About the issues reported with the S3 above -- I tested on my `esp32-s3-devkitc-1` board with both Arduino and IDF 5 and it worked perfectly fine the first time I tried. Not sure what might've been going on above.

2023-09-05 14:18 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +    ESP_LOGCONFIG(TAG, "LD2420 module has failed to respond, check baud rate and serial connections.");
Thanks for the review!
Changed to LOGE and added mark_failed();

2023-09-05 14:43 UTC, descipher commented on esphome/components/ld2420/ld2420.h
> +  u_int8_t set_config_mode_(bool enable);
Isn't it. Compiler must know something we don't.

2023-09-05 14:45 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +      } else if ((pos >= 64 && (memcmp(&buffer[pos - 5], &CMD_FRAME_HEADER, sizeof(CMD_FRAME_HEADER)) == 0) &&
Added const.

2023-09-05 15:04 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +        ESP_LOGD(TAG, "Rx: %s", format_hex_pretty(buffer, pos).c_str());
I am not keen on this and at the same time not opposed, here is why.
We default to a log level of DEBUG and we should expect higher levels of logging from that setting. The default should not be DEBUG in my view.
There are no documented defines for what is considered debug data or any sublevels of the same.
In this case we are logging what was sent to the LD2420 which is what I would consider as debug data.
This could be removed since it is available via uart debuging but thats essentially the same debug function.
Verbose is a sublevel and we can move it there but I believe there is a fundametal problem with the amount of and type of logging we are doing.
I would not go with VV since it would mix too much log info from other components.

Thoughts?

2023-09-05 15:05 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +  if (cmd_reply_.length > 64) {
For sure.

2023-09-05 15:15 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +    for (uint8_t gate = 0; gate < 16; gate++) {
Done.

2023-09-05 15:34 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +    ESP_LOGD(TAG, "LD2420 reply - received frame is corrupt, data lenght exceeds 64 bytes.");
Would WARN or ERROR be more appropriate?

2023-09-05 16:02 UTC, descipher commented
> About the issues reported with the S3 above -- I tested on my `esp32-s3-devkitc-1` board with both Arduino and IDF 5 and it worked perfectly fine the first time I tried. Not sure what might've been going on above.

Thanks for verifying it works.

2023-09-05 20:47 UTC, jesserockz commented on esphome/components/ld2420/ld2420.cpp
> +        ESP_LOGD(TAG, "Rx: %s", format_hex_pretty(buffer, pos).c_str());
You can add `debug:` to the `uart` component if you want the bytes logged...

2023-09-05 20:57 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +        ESP_LOGD(TAG, "Rx: %s", format_hex_pretty(buffer, pos).c_str());
Yes I noted that option above, then we could just remove the serial output here and report the higher level command log functions. Whats you thought on default log levels? is there a point at which the default could become WARN. This would also ease up on issue of hitting 50ms blocking with slow baud reate logging.

2023-09-05 22:12 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +        ESP_LOGD(TAG, "Rx: %s", format_hex_pretty(buffer, pos).c_str());
> We default to a log level of DEBUG and we should expect higher levels of logging from that setting.

Agree, but...

> The default should not be DEBUG in my view.

Also agree. However...

The pattern I've noticed in several other components is that, where there's logging to log individual bytes/arrays/messages such as you're doing here, the `VV` level is used.

At the default log level (regardless of what that might be) and because (as Jesse mentioned earlier) you can define the log level on a per-component basis, I guess I just do not expect to see arrays of bytes/messages being logged and it feels as though it's spamming the logs too much.

I guess, if it helps, think of as a `debug` level for users, not for developers.

2023-09-05 22:15 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +    ESP_LOGD(TAG, "LD2420 reply - received frame is corrupt, data lenght exceeds 64 bytes.");
Warn would probably be a good level for this message

2023-09-05 22:18 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +        ESP_LOGD(TAG, "Rx: %s", format_hex_pretty(buffer, pos).c_str());
Ok, that helps, best would be to remove the serial byte output lines from this component and provide it via the uart component. It results in the same functionality without more code here.

2023-09-05 22:20 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +        ESP_LOGD(TAG, "Rx: %s", format_hex_pretty(buffer, pos).c_str());
That works -- totally valid solution, too. Thanks for working on this! 🍻

2023-09-05 22:51 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +    ESP_LOGD(TAG, "LD2420 reply - received frame is corrupt, data lenght is less than 2 bytes.");
Changed to WARN

2023-09-06 03:05 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +  if (rx_data >= 0) {
Always true because unsigned

2023-09-06 03:28 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +  if (rx_data >= 0) {
Changed to int

2023-09-07 00:13 UTC, descipher commented
All changes have passed testing.

2023-09-08 01:05 UTC, qkddn49 commented
The button is currently missing from the component, which is the correct code?

2023-09-08 01:28 UTC, descipher commented
> The button is currently missing from the component, which is the correct code?

This is the correct code, I removed the button. It was contributing to blocking delays and its not required.
There was a problem with the restart command thar was just fixed in the last push.

2023-09-13 14:32 UTC, mkwatchface commented
Hello, thank you for the great work you are doing!

I am trying to test the component with the code above but the entities remain as Unknown in Home assistant. I am sure that the sensor works because i tested it with the Hilink tool and i get readings. Firmware should be 1.5.6 because the OT1 pin is RX however, in the ESP logs i dont get a firmware version. Pasting the logs below. Please disregard a PIR Sensor that i have on the same ESP32:

`[16:30:12][C][logger:301]: Logger:
[16:30:12][C][logger:302]:   Level: DEBUG
[16:30:12][C][logger:303]:   Log Baud Rate: 115200
[16:30:12][C][logger:305]:   Hardware UART: UART0
[16:30:12][C][uart.arduino_esp32:124]: UART Bus 0:
[16:30:12][C][uart.arduino_esp32:125]:   TX Pin: GPIO1
[16:30:12][C][uart.arduino_esp32:126]:   RX Pin: GPIO3
[16:30:12][C][uart.arduino_esp32:128]:   RX Buffer Size: 256
[16:30:12][C][uart.arduino_esp32:130]:   Baud Rate: 115200 baud
[16:30:12][C][uart.arduino_esp32:131]:   Data Bits: 8
[16:30:12][C][uart.arduino_esp32:132]:   Parity: NONE
[16:30:12][C][uart.arduino_esp32:133]:   Stop bits: 1
[16:30:12][W][uart.arduino_esp32:179]:   You're using the same serial port for logging and the UART component. Please disable logging over the serial port by setting logger->baud_rate to 0.
[16:30:13][C][ld2420:012]: LD2420:
[16:30:13][C][ld2420:013]:   Firmware Version :        
[16:30:13][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Bedroom Motion Sensor'
[16:30:13][C][gpio.binary_sensor:015]:   Device Class: 'motion'
[16:30:13][C][gpio.binary_sensor:016]:   Pin: GPIO2
[16:30:13][C][LD2420.binary_sensor:011]: LD2420 BinarySensor:
[16:30:13][C][LD2420.binary_sensor:012]:   Presence 'Bedroom Presence'
[16:30:13][C][LD2420.binary_sensor:012]:     Device Class: 'occupancy'
[16:30:13][C][LD2420.sensor:011]: LD2420 Sensor:
[16:30:13][C][LD2420.sensor:012]:   Distance 'Moving Distance'
[16:30:13][C][LD2420.sensor:012]:     Device Class: 'distance'
[16:30:13][C][LD2420.sensor:012]:     State Class: ''
[16:30:13][C][LD2420.sensor:012]:     Unit of Measurement: 'cm'
[16:30:13][C][LD2420.sensor:012]:     Accuracy Decimals: 0`

Hoping for support!

2023-09-13 16:18 UTC, descipher commented
Do not use:
TX Pin: GPIO1
RX Pin: GPIO3

e.g. You're using the same serial port for logging and the UART component. Please disable logging over the serial port by setting logger->baud_rate to 0

Use GPIO 17 and 16.

2023-09-13 21:59 UTC, mkwatchface commented
> Do not use: TX Pin: GPIO1 RX Pin: GPIO3
> 
> e.g. You're using the same serial port for logging and the UART component. Please disable logging over the serial port by setting logger->baud_rate to 0
> 
> Use GPIO 17 and 16.

I changed the pins but still I have "Unknown" entities... Here is my yaml in case I am doing something wrong:

```
esphome:
  name: esphome-web-2631d8
  friendly_name: Master Bedroom Motion Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "my key"

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-2631D8"
    password: "MyPsw"

captive_portal:


external_components:
  - source: github://pr#4847
    components: [ ld2420 ]
    refresh: 0s

uart:
  id: ld2420_uart
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

binary_sensor:
  - platform: gpio
    pin: GPIO02
    name: "Bedroom Motion Sensor"
    device_class: motion
  - platform: ld2420
    has_target:
      name: Bedroom Presence

ld2420:
  presence_time_window: 120s
  detection_gate_min: 1
  detection_gate_max: 12
  g0_move_threshold: 60000
  g0_still_threshold: 40000
  g1_move_threshold: 30000
  g1_still_threshold: 20000
  g2_move_threshold: 400
  g2_still_threshold: 200
  g3_move_threshold: 250
  g3_still_threshold: 200
  g4_move_threshold: 250
  g4_still_threshold: 200
  g5_move_threshold: 250
  g5_still_threshold: 200
  g6_move_threshold: 250
  g6_still_threshold: 200
  g7_move_threshold: 250
  g7_still_threshold: 150
  g8_move_threshold: 250
  g8_still_threshold: 150
  g9_move_threshold: 250
  g9_still_threshold: 100
  g10_move_threshold: 250
  g10_still_threshold: 100
  g11_move_threshold: 250
  g11_still_threshold: 100
  g12_move_threshold: 250
  g12_still_threshold: 100
  g13_move_threshold: 200
  g13_still_threshold: 100
  g14_move_threshold: 200
  g14_still_threshold: 100
  g15_move_threshold: 200
  g15_still_threshold: 100


sensor:
  - platform: ld2420
    moving_distance:
      name : Moving Distance
```

there is also a PIR sensor on GPIO02 so please disregard!

2023-09-14 00:42 UTC, descipher commented
![image](https://github.com/esphome/esphome/assets/10734527/77dbaf35-a7ee-4558-a51d-39d67152c5ec)

1) Make sure your pins are correct.

ESP Tx GPIO17 goes to LD2420 Rx, 
ESP Rx GPIO16 goes to LD2420 Tx, 

~~~
uart:
  id: ld2420_uart
  tx_pin: GPIO17 
  rx_pin: GPIO16
  baud_rate: 115200
  parity: NONE
  stop_bits: 1
  debug:
~~~

2) enable serial debugging so you can see the data and post it quoted with ~~~ serial data ~~~.

~~~
logger:
  baud_rate: 115200
~~~

3) You can leave logger the way it normally works.
4) remove all unnecessary components while debugging the problem.

2023-09-14 08:55 UTC, mkwatchface commented
> logger:
>   baud_rate: 115200

Hi descipher, thanks for your guidance! I confirm it works! Keep up the good work and hopefully we can see an official release!

2023-10-01 08:58 UTC, ootktk commented
@descipher I tried your PR on a different radar and it seems to work now, however upon hitting the platform restart button it has gone dead again, now it doesn't even talk to the original HLK tool. Seems to be the same issue with my earlier radars. Any ideas?

button:
- platform: restart
  name: "Restart ESP"

2023-10-01 12:42 UTC, descipher commented
> @descipher I tried your PR on a different radar and it seems to work now, however upon hitting the platform restart button it has gone dead again, now it doesn't even talk to the original HLK tool. Seems to be the same issue with my earlier radars. Any ideas?
> 
> button:
> 
> * platform: restart
>   name: "Restart ESP"

I have not seen hangs on firmware v1.5.4 and up and when a hang occurred it was always cleared with a power cycle.

Methods to resolve:

1) Check connections: If you're using a proto board they are notorious for bad connections.
2) Verify you're using 3.3v as a supply to the LD2420
3) Verify Tx and Rx are correct (see image above)
4) If all else fails use this board to deploy and test: https://www.gelidus.ca/product/gelidus-research-ac-powered-mmwave-sensor-board/

2023-10-20 19:30 UTC, GelidusResearch commented
This PR is updating to a refactored version that is more like the LD2410. If you are running this version you will need to switch to the upgraded configuration provided in the PR description post. This is a breaking change. Hopefully this will happen today.

2023-10-21 15:50 UTC, descipher commented
Docs are now updated.

2023-10-23 07:32 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +  ESP_LOGI(TAG, "Total samples: %d", total_sample_number_counter);
IDF 5+ compatibility
```suggestion
  ESP_LOGI(TAG, "Total samples: %" PRId32, total_sample_number_counter);
```

2023-10-23 07:37 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +    ESP_LOGI(TAG, "Gate: %2d Avg: %5d Peak: %5d", gate, gate_avg[gate], gate_peak[gate]);
When referring to member variables, please (consistently) prefix with `this->` -- I see this in some places but not others. haha
```suggestion
    ESP_LOGI(TAG, "Gate: %2d Avg: %5d Peak: %5d", gate, this->gate_avg[gate], this->gate_peak[gate]);
```

2023-10-23 14:37 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +    ESP_LOGI(TAG, "Gate: %2d Avg: %5d Peak: %5d", gate, gate_avg[gate], gate_peak[gate]);
Installed cppcheck to catch them.

2023-10-24 20:47 UTC, descipher commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:Consolas;
	panose-1:2 11 6 9 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:12.0pt;
	font-family:"Times New Roman",serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
	{mso-style-priority:99;
	color:purple;
	text-decoration:underline;}
p
	{mso-style-priority:99;
	mso-margin-top-alt:auto;
	margin-right:0cm;
	mso-margin-bottom-alt:auto;
	margin-left:0cm;
	font-size:12.0pt;
	font-family:"Times New Roman",serif;}
pre
	{mso-style-priority:99;
	mso-style-link:"HTML Preformatted Char";
	margin:0cm;
	margin-bottom:.0001pt;
	font-size:10.0pt;
	font-family:"Courier New";}
span.HTMLPreformattedChar
	{mso-style-name:"HTML Preformatted Char";
	mso-style-priority:99;
	mso-style-link:"HTML Preformatted";
	font-family:Consolas;}
span.EmailStyle20
	{mso-style-type:personal-reply;
	font-family:"Calibri",sans-serif;
	color:#1F497D;}
.MsoChpDefault
	{mso-style-type:export-only;
	font-family:"Calibri",sans-serif;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
--> 

2023-10-25 14:35 UTC, simonyel commented
I tried to install this morning and ran into compiler issues:
```
Compiling .pioenvs/ld2420-test/src/esphome/components/ld2420/ld2420.cpp.o
In file included from src/esphome/components/uart/uart.h:6,
                 from src/esphome/components/ld2420/ld2420.h:4,
                 from src/esphome/components/ld2420/ld2420.cpp:1:
src/esphome/components/ld2420/ld2420.cpp: In member function 'void esphome::ld2420::LD2420Component::report_gate_data()':
src/esphome/components/ld2420/ld2420.cpp:270:36: error: expected ')' before 'PRId32'
   ESP_LOGI(TAG, "Total samples: %" PRId32, this->total_sample_number_counter);
                                    ^~~~~~
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
 #define ESPHOME_LOG_FORMAT(format) format
                                    ^~~~~~
src/esphome/core/log.h:151:28: note: in expansion of macro 'esph_log_i'
 #define ESP_LOGI(tag, ...) esph_log_i(tag, __VA_ARGS__)
                            ^~~~~~~~~~
src/esphome/components/ld2420/ld2420.cpp:270:3: note: in expansion of macro 'ESP_LOGI'
   ESP_LOGI(TAG, "Total samples: %" PRId32, this->total_sample_number_counter);
   ^~~~~~~~
src/esphome/core/log.h:108:18: note: to match this '('
   esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                  ^
src/esphome/core/log.h:151:28: note: in expansion of macro 'esph_log_i'
 #define ESP_LOGI(tag, ...) esph_log_i(tag, __VA_ARGS__)
                            ^~~~~~~~~~
src/esphome/components/ld2420/ld2420.cpp:270:3: note: in expansion of macro 'ESP_LOGI'
   ESP_LOGI(TAG, "Total samples: %" PRId32, this->total_sample_number_counter);
   ^~~~~~~~
*** [.pioenvs/ld2420-test/src/esphome/components/ld2420/ld2420.cpp.o] Error 1
========================= [FAILED] Took 20.54 seconds =========================
```

2023-10-25 16:33 UTC, descipher commented
@simonyel  Can you post the config yaml, I just compiled without issues for an esp32dev
```
esp32:
  board: esp32dev
  framework:
    type: arduino
```

2023-10-25 17:01 UTC, simonyel commented
```
substitutions:
  device_name: ld2420-test
  friendly_name: ld2420-test
  entity_prefix: ld2420-test
  device_comment: "All-In-One Sensor vAIO3"
  device_type: "SVYtech"

packages:
  core: !include _config/core1.yaml

external_components:
  - source: github://pr#4847
    components: [ ld2420 ]
    refresh: 0s

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***"

status_led:
  pin:
    number: GPIO2 
    inverted: false  

i2c:
  - id: bus_a
    sda: GPIO22
    scl: GPIO21
    frequency: 100kHz
    scan: true

uart:
  id: ld2420_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

ld2420:

sensor:
  - platform: bh1750
    i2c_id: bus_a
    name: ${entity_prefix} Light
    address: 0x23
    update_interval: 2s  
  - platform: ld2420
    moving_distance:
      name: ${entity_prefix} Moving Distance

text_sensor:
  - platform: ld2420
    fw_version:
      name: ${entity_prefix} Radar Firmware

binary_sensor:
  - platform: ld2420
    has_target:
      name: ${entity_prefix} Presence

select:
  - platform: ld2420
    operating_mode:
      name: ${entity_prefix} Operating Mode

number:
  - platform: ld2420
    timeout:
      name: ${entity_prefix} Presence Timeout
    min_gate_distance:
      name: ${entity_prefix} Gate Minimum
    max_gate_distance:
      name: ${entity_prefix} Gate Maximum
    gate_select:
      name: ${entity_prefix} Select Gate to Set
    still_threshold:
      name: ${entity_prefix} Set Still Threshold
    move_threshold:
      name: ${entity_prefix} Set Move Threshold

button:
  - platform: ld2420
    apply_config:
      name: ${entity_prefix} Apply Config
    factory_reset:
      name: ${entity_prefix} Factory Reset
    restart_module:
      name: ${entity_prefix} Restart Radar
    revert_config:
      name: ${entity_prefix} Undo Edits      
```

2023-10-25 17:16 UTC, descipher commented
@simonyel Looks fine, try a cleaning of the build env.

2023-10-25 19:04 UTC, simonyel commented
Cleaning build files and retrying didn't help.

2023-10-25 19:42 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +  ESP_LOGI(TAG, "Total samples: %d", total_sample_number_counter);
To fix the [issue in the comment below](https://github.com/esphome/esphome/pull/4847#issuecomment-1779424352), you also need to `#include <cinttypes>` here. Sorry, should've mentioned that in my original comment. 😇

2023-10-25 19:46 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +  ESP_LOGI(TAG, "Total samples: %d", total_sample_number_counter);
Ok thanks, will add it, just odd that I can't dup the issue.

2023-10-25 20:07 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +  ESP_LOGI(TAG, "Total samples: %d", total_sample_number_counter);
Yeah, it just depends on what you happen to include in your build. It's already in some places but not others, so if you happen to be including a component that already includes it, you won't see any errors. haha

FWIW, I got the compile errors here, too. 😇

2023-10-25 21:26 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +  ESP_LOGI(TAG, "Total samples: %d", total_sample_number_counter);
Looking at it closer, I switched to uint16 since at 10 samples per sec it does not need to be uint32 ..

2023-10-25 22:55 UTC, descipher commented
> Cleaning build files and retrying didn't help.

Should work now.

2023-10-25 23:41 UTC, kbx81 commented
> > Cleaning build files and retrying didn't help.
> 
> Should work now.

Yup, working for me 🎉

2023-11-01 23:53 UTC, kbx81 commented on esphome/components/ld2420/number/__init__.py
> +        cv.Optional(f"g{x}"): (
Quick thought -- since we use the full word "gate" in the other parameters, could/should we use it here, too? I think maybe like this:
```suggestion
        cv.Optional(f"gate_{x}"): (
```

2023-11-02 01:35 UTC, descipher commented on esphome/components/ld2420/number/__init__.py
> +        cv.Optional(f"g{x}"): (
For sure. Added change.

2023-11-02 05:32 UTC, kbx81 commented
Hmm, the new `number` components were working prior to your last couple of commits. 🤔

2023-11-02 05:54 UTC, kbx81 commented on esphome/components/ld2420/number/__init__.py
> +            if gate_conf := config.get(f"g{x}"):
Ah, found the issue to [this comment](https://github.com/esphome/esphome/pull/4847#issuecomment-1790097404):
```suggestion
            if gate_conf := config.get(f"gate_{x}"):
```

As and alternative, make this prefix a constant somewhere above. haha

2023-11-02 08:29 UTC, kbx81 commented on esphome/components/ld2420/number/gate_config_number.cpp
> +  if (this->parent_->is_gate_select()) {
I think this logic is inverted -- it crashes when I change a gate value 😄
```suggestion
  if (!this->parent_->is_gate_select()) {
```

2023-11-02 08:29 UTC, kbx81 commented on esphome/components/ld2420/number/gate_config_number.cpp
> +  if (this->parent_->is_gate_select()) {
I think this logic is inverted -- it crashes when I change a gate value 😄
```suggestion
  if (!this->parent_->is_gate_select()) {
```

2023-11-02 08:40 UTC, kbx81 commented on esphome/components/ld2420/number/gate_config_number.cpp
> +  }
Could probably simplify this slightly:
```suggestion
    min_gate = this->parent_->get_min_gate_distance_value();
  } else {
    this->parent_->new_config.min_gate = (uint16_t) min_gate;
  }
  this->publish_state(min_gate);
```

2023-11-02 08:40 UTC, kbx81 commented on esphome/components/ld2420/number/gate_config_number.cpp
> +  }
Could probably simplify this slightly:
```suggestion
    max_gate = this->parent_->get_max_gate_distance_value();
  } else {
    this->parent_->new_config.max_gate = (uint16_t) max_gate;
  }
  this->publish_state(max_gate);
```

2023-11-02 13:47 UTC, descipher commented on esphome/components/ld2420/number/gate_config_number.cpp
> +  if (this->parent_->is_gate_select()) {
Yep, should with gate select defined then use get_gate_select_value. Added.

2023-11-02 13:49 UTC, descipher commented on esphome/components/ld2420/number/gate_config_number.cpp
> +  }
In plain sight :/ Cleaned.

2023-11-02 21:45 UTC, descipher commented on esphome/components/ld2420/number/gate_config_number.cpp
> +  if (this->parent_->is_gate_select()) {
Added.

2023-11-02 21:46 UTC, descipher commented on esphome/components/ld2420/number/__init__.py
> +            if gate_conf := config.get(f"g{x}"):
Added.

2023-11-02 23:00 UTC, kbx81 approved these changes

2023-11-02 23:02 UTC, merged

2023-11-02 23:10 UTC, simonyel commented
Is there a guide on calibration?

2023-11-02 23:24 UTC, descipher commented
> Is there a guide on calibration?

Not at this time, but it is strait forward. The code does the work in most cases I will look at doing a blog with my experiences on it.
In general the move threshold should be approximately 1.5 times the noise floor. The still gate can be much lower. The auto calibration should run for 1+ minutes to catch the minimum noise baseline.  The default sensitivity number values work well. The ld2420 is very sensitive and will detect movement through walls and floors so remember to set those gate min/max values.