mqtt: add ESP-IDF >= 5.0 support
OttoWinter/esphomeyaml pull request #4854
Opened 2023-05-18 16:06 UTC by stintel

# What does this implement/fix?

Add ESP-IDF >= 5.0 support to the MQTT component.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-05-31 02:10 UTC, jesserockz commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> +#endif
Does this mean no `on_connect` callback for idf 5+?

2023-05-31 23:30 UTC, stintel commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> +#endif
Unfortunately I don't remember why I did this two weeks ago. I'll have to dig back into it, but as I'm currently travelling it might be a while.

2023-06-01 02:33 UTC, jesserockz commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> +#endif
Im guessing because the `mqtt_cfg_.disable_clean_session` has changed in idf 5+. Funny thing though is that the boolean is not actually exposed in YAML/lambdas and could probably just be removed form the trigger entirely.

2023-06-05 16:46 UTC, stintel commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> +#endif
Shall I just remove it then?

2023-06-06 21:36 UTC, jesserockz commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> +#endif
Yes, if we decide to expose it to the yaml later it can be added back.

2023-06-07 14:43 UTC, stintel commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> +#endif
Done.

2023-06-19 02:01 UTC, jesserockz requested changes

2023-06-19 02:01 UTC, jesserockz commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> -      this->on_connect_.call(!mqtt_cfg_.disable_clean_session);
What I meant by remove it, was remove the argument to the trigger so it can be called from both versions:
It will require changes to the definition of `on_connect_` to rmeove the arg etc.
```
this->on_connect_.call()
```

2023-06-20 23:29 UTC, stintel commented on esphome/components/mqtt/mqtt_backend_idf.cpp
> -      this->on_connect_.call(!mqtt_cfg_.disable_clean_session);
Thanks. I couldn't get it figured out.

2023-06-20 23:30 UTC, jesserockz approved these changes

2023-06-20 23:53 UTC, merged