Ipv6 ESP32
OttoWinter/esphomeyaml pull request #4865
Opened 2023-05-20 11:06 UTC by HeMan

# What does this implement/fix?

Enable basic IPv6 for ESP32 Arduino framework, both wifi and ethernet. Replaces #4750 and #4807 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 Ethernet
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

wifi:
```yaml
# Example config.yaml
esphome:
  name: ipv6

esp32:
  board: esp32dev
  framework:
    type: arduino

network:
  enable_ipv6: true

wifi:
  ssid: wifissid
  password: !secret wifipwd
```

ethernet:
```yaml
esphome:
  name: ipv6eth

esp32:
  board: esp32dev
  framework:
    type: arduino

network:
  enable_ipv6: true

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-06-01 02:28 UTC, jesserockz requested changes

2023-06-01 02:28 UTC, jesserockz commented on esphome/components/network/__init__.py
> +            cg.add_build_flag("-DCONFIG_LWIP_IPV6_AUTOCONFIG")
Im pretty sure I commented on this in the past, but these flags default to true if not specified, so they need to be explicitly set on idf
 ```suggestion
    if CONF_ENABLE_IPV6 in config:
        if CORE.using_esp_idf:
            add_idf_sdkconfig_option("CONFIG_LWIP_IPV6", config[CONF_ENABLE_IPV6])
            add_idf_sdkconfig_option(
                "CONFIG_LWIP_IPV6_AUTOCONFIG", config[CONF_ENABLE_IPV6]
            )
        else:
            if config[CONF_ENABLE_IPV6]:
                cg.add_build_flag("-DCONFIG_LWIP_IPV6")
                cg.add_build_flag("-DCONFIG_LWIP_IPV6_AUTOCONFIG")
```

2023-06-01 02:28 UTC, jesserockz commented on esphome/components/ethernet/ethernet_component.cpp
Shouldnt all of this code be pre-processed out if IPv6 is disabled?

2023-06-13 12:34 UTC, HeMan commented
@jesserockz Is there anything else I need to fix in this PR?

2023-06-19 21:02 UTC, HeMan commented
Works with Ethernet on esp-idf framework as well.
```
esphome:
  name: ipv6ethidf

esp32:
  board: esp32dev
  framework:
    type: esp-idf

network:
  enable_ipv6: true

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
```

2023-07-30 21:57 UTC, jesserockz approved these changes

2023-07-30 22:20 UTC, merged