Added base64 helper
OttoWinter/esphomeyaml pull request #4866
Opened 2023-05-20 14:47 UTC by freekode

# What does this implement/fix?

Added encode and decode funcitons for base64
Copied from [here](https://stackoverflow.com/questions/180947/base64-decode-snippet-in-c)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esp32_camera:
  ...
  on_image:
      then:
        - lambda: |-
            const char* image_data_char = reinterpret_cast<char*>(image.data);
            std::string encodedData = base64_encode(&image_data_char[0], image.length);
            bool result = id(mqtt_client).publish("cam/image", encodedData);
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-05-20 14:50 UTC, freekode commented
I'm not sure which tests to add.
I tested it locally only.

2023-05-20 16:35 UTC, max246 commented
Maybe would be good to add a note in the esphome doc? If it gets approved is handy to know that i can be used for espcamera or just generic encoding.

2023-05-20 18:52 UTC, freekode commented
Sure thing. I added it to esp32 camera docs. If you think there is another better place, jut let me know.

2023-05-20 20:51 UTC, kroimon approved these changes
Looks good to me!

2023-08-21 04:46 UTC, jesserockz requested changes

2023-08-21 04:46 UTC, jesserockz commented on esphome/core/helpers.h
> +std::string base64_encode(const char *buf, unsigned int buf_len);
```suggestion
std::string base64_encode(const uint8_t *buf, size_t buf_len);
```

2023-08-21 04:46 UTC, jesserockz commented on esphome/core/helpers.h
> +std::string base64_encode(const char *buf, unsigned int buf_len);
Might be nice to also create overloads for these to they are consistent, ie decoding can take a buffer to write to and return the length as other buffer apis do.

And an overload to pass a std::vector to `encode` as well

2024-04-24 02:14 UTC, jesserockz approved these changes

2024-04-24 03:07 UTC, merged