[internal_temperature] ESP32-S3 needs ESP IDF V4.4.3 or higher
OttoWinter/esphomeyaml pull request #4873
Opened 2023-05-22 08:24 UTC by Fabian-Schmidt

# What does this implement/fix?

Avoid building non working firmware for ESP32-S3 with internal temperature sensor.
Check in Python code is a bit complex as there is no translation between Arduino version and internally used ESP IDF version.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <https://github.com/esphome/issues/issues/4271>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-05-22 09:44 UTC, Mat931 approved these changes

2023-05-22 20:39 UTC, jesserockz requested changes
Yes there is no exact way to know which idf version arduino is using (in code), but instead of throwing a compile error, it would be better to add a validation to the component that checks if s3 and if arduino version is >= 2.0.5 as we know thats when arduino start using it

2023-05-23 14:12 UTC, Fabian-Schmidt commented
@jesserockz I updated the python to include the validation of the version.

2023-05-23 19:50 UTC, jesserockz approved these changes

2023-05-23 19:51 UTC, jesserockz commented
Thanks @Fabian-Schmidt

2023-05-23 19:51 UTC, merged