Implement connection retries for http_request
OttoWinter/esphomeyaml pull request #4881
Opened 2023-05-23 20:38 UTC by mgorven

# What does this implement/fix?

Add `retries`, `retry_delay` and `retry_backoff_factor` options to `http_request` component. Use `Component::set_retry()` to retry HTTP requests. Requests are only retried for network and connection errors; if an HTTP response is received the request is not retried.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2940

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
http_request:
  retries: 10
  retry_delay: 1s
  retry_backoff_factor: 1.5
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-08 20:42 UTC, mgorven commented
@OttoWinter Please can I get a review on this. Thanks.

2023-12-12 23:55 UTC, jesserockz requested changes

2023-12-12 23:55 UTC, jesserockz commented on esphome/components/http_request/__init__.py
> +            cv.Optional(CONF_RETRY_BACKOFF_FACTOR, 1.0): cv.float_,
Can we alter this so that it is something like thi?
```yaml
...
retry:
  count: 10
  delay: 1s
  backoff_factor: 1.0
```

2024-01-05 00:07 UTC, mgorven commented on esphome/components/http_request/__init__.py
> +            cv.Optional(CONF_RETRY_BACKOFF_FACTOR, 1.0): cv.float_,
Changed

2024-01-05 00:44 UTC, mgorven commented
There's a problem with this after https://github.com/esphome/esphome/pull/5360.

2024-01-05 01:17 UTC, mgorven commented
> There's a problem with this after #5360.

Resolved by doing `set_body("")` before requests instead of after.

2024-05-07 03:29 UTC, kbx81 commented on esphome/components/http_request/__init__.py
> +                    cv.Optional(CONF_COUNT, 0): cv.int_,
You'd never want to allow a negative value here
```suggestion
                    cv.Optional(CONF_COUNT, 0): cv.positive_int,
```

2024-05-07 03:29 UTC, kbx81 commented on esphome/components/http_request/__init__.py
> +                    cv.Optional(CONF_BACKOFF_FACTOR, 1.0): cv.float_,
Similar to above, perhaps setting `1` as the minimum?
```suggestion
                    cv.Optional(CONF_BACKOFF_FACTOR, 1.0): cv.float_range(min=1),
```

2026-07-30 01:37 UTC, swoboda1337 commented
Closing this out: changes were requested back in December 2023 and the discussion trailed off in mid-2024 with the review feedback unresolved. The http_request component has been substantially reworked since then, so this would need a fresh start against current dev regardless.

Connection retries would still be a useful addition — if you or anyone else wants to pick this up again, a new PR against current dev would be welcome.

2026-07-30 01:37 UTC, closed without merging