Airthings refactor
OttoWinter/esphomeyaml pull request #4910
Opened 2023-06-01 20:03 UTC by kpfleming

# What does this implement/fix?

Refactoring of `airthings_wave_mini` and `airthings_wave_plus` components into a new `airthings_wave_base` component, eliminating code duplication.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Other (refactoring only)

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

2023-06-18 23:32 UTC, jesserockz requested changes

2023-06-18 23:32 UTC, jesserockz commented on esphome/components/airthings_wave_mini/sensor.py
> -DEPENDENCIES = ["ble_client"]
Please leave the DEPENDENCIES here as well as they show up nicer as errors in the editor on the real components

2023-06-18 23:32 UTC, jesserockz commented on esphome/components/airthings_wave_base/airthings_wave_base.cpp
> +AirthingsWaveBase::AirthingsWaveBase() : PollingComponent(10000) {}
This should not have actually been in the main component, safe to remove.
```suggestion
```

2023-06-19 11:15 UTC, kpfleming commented on esphome/components/airthings_wave_mini/sensor.py
> -DEPENDENCIES = ["ble_client"]
Sure, I can just `import` that from the base into the real components.

2023-06-19 11:16 UTC, kpfleming commented on esphome/components/airthings_wave_base/airthings_wave_base.cpp
> +AirthingsWaveBase::AirthingsWaveBase() : PollingComponent(10000) {}
Does this mean the `PollingComponent` constructor does not need to be called, or that it should be called from the constructors of the real components?

2023-06-19 22:48 UTC, jesserockz commented on esphome/components/airthings_wave_base/airthings_wave_base.cpp
> +AirthingsWaveBase::AirthingsWaveBase() : PollingComponent(10000) {}
It doesn't need to be called, the update interval is set inside `cg.register_component`

2023-06-19 23:17 UTC, kpfleming commented on esphome/components/airthings_wave_mini/sensor.py
> -DEPENDENCIES = ["ble_client"]
Will push an update now.

2023-06-19 23:17 UTC, kpfleming commented on esphome/components/airthings_wave_base/airthings_wave_base.cpp
> +AirthingsWaveBase::AirthingsWaveBase() : PollingComponent(10000) {}
Will push an update now.

2023-06-20 00:04 UTC, kpfleming commented
@jesserockz Requested changes have been made and CI is passing again. Thanks for the review!

2023-06-20 23:44 UTC, jesserockz approved these changes

2023-06-20 23:53 UTC, merged