Sigma delta fix
OttoWinter/esphomeyaml pull request #4911
Opened 2023-06-02 19:35 UTC by PlainTechEnthusiast

# What does this implement/fix?

The output pin, if configured, in the Sigma Delta Output was never initialized. This worked as long as the pin had been used as an output since power up since a software reset after an OTA didn't seem to reset the pin registers. Though I'm sure that last bit is probably expected behavior.

This PR also implements dump_config() and adds a missing header for automation.h.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-06-03 07:01 UTC, PlainTechEnthusiast commented
I should be able to take care of the lint issue later today and amend the PR

2023-06-03 11:35 UTC, HxYxI commented
-

2023-06-03 11:36 UTC, HxYxI approved these changes
Text

2023-06-05 01:15 UTC, PlainTechEnthusiast commented
Ready for review

2023-06-19 02:30 UTC, jesserockz requested changes
Since you are making changes, could you also move the `update` function into the cpp file?

Thanks

2023-06-22 05:25 UTC, PlainTechEnthusiast commented
> Since you are making changes, could you also move the `update` function into the cpp file?

Done and tested on an ESP32. I went back and forth on including it initially, I guess I could have just included it as a separate commit.

Thanks

2023-07-18 00:48 UTC, jesserockz approved these changes

2023-07-18 00:49 UTC, merged