I have created IR Noblex climate component
OttoWinter/esphomeyaml pull request #4913
Opened 2023-06-02 22:54 UTC by AGalfra

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
climate:
  - platform: noblex
    name: "Prueba AC"
    id: prueba_ac
    sensor: temp
    receiver_id: rcvr
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-06-03 01:13 UTC, AGalfra commented
Hello.
This is my first contribution to ESPHome.
I've been using it for a long time and it's time to contribute to the project.
thank you so much.

2023-07-10 19:45 UTC, AGalfra commented
hi @jesserockz could you verify this pull request?

2023-07-12 02:18 UTC, AGalfra commented
Hi dear @jesserockz now the documentation is ready https://github.com/esphome/esphome-docs/pull/3054.

2023-07-12 03:12 UTC, jesserockz requested changes

2023-07-12 03:12 UTC, jesserockz commented on esphome/components/noblex/noblex.cpp
> +}
ESPHome has `uint8_t reverse_bits(uint8_t)` in `helpers.h` for this already.

2023-07-12 22:55 UTC, AGalfra commented on esphome/components/noblex/noblex.cpp
> +}
thank you for the correction. I already modified the file and I am using the function included in helpers

2023-08-07 11:00 UTC, AGalfra commented on esphome/components/noblex/noblex.cpp
> +}
@jesserockz.
dear, the suggested correction is ready

2023-08-07 23:02 UTC, jesserockz requested changes

2023-08-07 23:02 UTC, jesserockz commented on esphome/components/noblex/noblex.cpp
> +  for (unsigned char i : remote_state) {
```suggestion
  for (uint8_t i : remote_state) {
```

2023-08-07 23:02 UTC, jesserockz commented on esphome/components/noblex/noblex.cpp
> +  for (unsigned char i : remote_state)
```suggestion
  for (uint8_t i : remote_state)
```

2023-08-07 23:02 UTC, jesserockz commented on esphome/components/noblex/noblex.cpp
> +  for (unsigned char &i : remote_state)
```suggestion
  for (uint8_t &i : remote_state)
```

2023-08-07 23:02 UTC, jesserockz commented on esphome/components/noblex/noblex.cpp
> +  static uint8_t remote_state[8] = {0};
These should not be static variables, if you need them across calls, make them member variables please.

2023-08-07 23:02 UTC, jesserockz commented on esphome/components/noblex/noblex.h
> +  bool send_swing_cmd_{false};
Not actually used anywhere?

2023-08-15 23:01 UTC, AGalfra commented on esphome/components/noblex/noblex.cpp
> +  for (unsigned char i : remote_state) {
made the suggested changes

2023-08-15 23:01 UTC, AGalfra commented on esphome/components/noblex/noblex.cpp
> +  for (unsigned char i : remote_state)
@jesserockz  made the suggested changes

2023-08-15 23:02 UTC, AGalfra commented on esphome/components/noblex/noblex.cpp
> +  for (unsigned char &i : remote_state)
@jesserockz made the suggested changes

2023-08-15 23:02 UTC, AGalfra commented on esphome/components/noblex/noblex.cpp
> +  static uint8_t remote_state[8] = {0};
revision of variables carried out

2023-08-15 23:02 UTC, AGalfra commented on esphome/components/noblex/noblex.h
> +  bool send_swing_cmd_{false};
@jesserockz  revision of variables carried out

2023-08-16 01:54 UTC, AGalfra commented on esphome/components/noblex/noblex.h
> +  bool send_swing_cmd_{false};
It is the same as in Whirpool, LG, Coolix...

2023-09-14 12:42 UTC, AGalfra commented on esphome/components/noblex/noblex.h
> +  bool send_swing_cmd_{false};
@jesserockz
Hello dear, how do you now find this integration so that you can merge it?

2023-10-24 01:57 UTC, AGalfra commented on esphome/components/noblex/noblex.h
> +  bool send_swing_cmd_{false};
@jesserockz how do you now find this integration so that you can merge it?

2023-10-24 03:24 UTC, jesserockz approved these changes

2023-10-24 03:28 UTC, merged