Handling of sensor read quality refined
OttoWinter/esphomeyaml pull request #4928
Opened 2023-06-08 19:03 UTC by lukasl96

It's now possible to receive sensor values even when the sensor thinks its read quality is low

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-06-10 05:05 UTC, spbrogan requested changes

2023-06-10 05:05 UTC, spbrogan commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +    if (quality_value < QUALITY_HIGH && quality_value > QUALITY_LOW) {
If i am reading this correctly there is an odd overlap for these conditionals and log messages.  I would suggest a more traditional if/else if structure and print a unique log message for each quality.

2023-06-10 05:05 UTC, spbrogan commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +      ESP_LOGW(TAG, "Poor sensor read quality.");
instead of allowing low quality readings without letting the user know that their sensor is reading poorly I wonder if we want to something different. 

One idea is we could expose the read quality as a sensor.  That way the HA user can at least see what the quality reading is.  

and/or 

create a config item per sensor that allows you to specify the minimum reading quality you want reported in the level and distance sensors.
or
 create multiple distance and level sensors pairs.  1 pair for high only.  1 pair for med and above.  1 pair for low and above.  Then you could choose which sensor pair you wanted.  

and/or 

Enable some algorithm to ignore N number of bad readings and not change the level or distance sensor on a bad reading unless there have been no better readings within N reports. 

Thoughts?

2023-06-10 05:18 UTC, lukasl96 commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +      ESP_LOGW(TAG, "Poor sensor read quality.");
I already have a custom component with sensor reading quality as an own sensor. I will add the code later this day.

2023-06-10 10:24 UTC, lukasl96 commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +      ESP_LOGW(TAG, "Poor sensor read quality.");
I committed the changes but the tests are failing.
I don't understand why they are failing because i use the same code as a custom component in my environment.

2023-06-11 22:51 UTC, jesserockz commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +    }
I don't like the fact this is converting the fixed enums to a fixed percentage.

I feel like this would just be better as a text_sensor with the names as they are.

2023-06-15 07:08 UTC, spbrogan commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +      if (quality_value = QUALITY_HIGH) {
these should all be "==" as you are doing assignment rather than comparison.

2023-06-15 07:10 UTC, spbrogan commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +    }
you could also just return the quality value which is int between 0 - 3

2023-06-15 07:19 UTC, spbrogan commented
I kind of like the idea of adding an optional config item of value between 0-3 which could be the quality reading in which to not report.  And maybe another optional config item of the value between 0-3 which all quality readings below will be reported as zero.

2023-06-22 15:53 UTC, phurth commented
I like the idea of passing the quality value and allowing the user to configure whether or not to ignore at a certain level. This better aligns with the Mopeka app behavior, where low (1) quality readings are still reported to the user. I have one sensor that often reports a quality of 1, but still seems accurate enough. I'd like the ability to allow that reading, but maybe still ignore 0 quality readings.

2023-09-29 00:44 UTC, closed without merging