display: Improve Image rendering by removing usage of virtual functions
OttoWinter/esphomeyaml pull request #4931
Opened 2023-06-10 11:42 UTC by ayufan

# What does this implement/fix?

The virtual functions have high overhead. In case of image rendering they are being called for each pixel. This change improves rendering by about 5%.

Since Image does no longer expose virtual functions for pixels, fix Animation to shift `data_buffer`.

For 150x150 image, with RGB565:

- before: `28987 us`
- after: `30600 us`

It was tested on ESP32S3.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other: Performance improvement

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32S3
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
animation:
  - id: image_startup
    file: "images/AfterPrinting/AfterPrinting.gif"
    resize: 150x150
    type: RGB565

display:
  lambda: |-
    id(image_startup).next_frame();
    auto start_us = micros();
    it.image(0, 0, id(image_startup));
    ESP_LOGE("display", "image draw: %ld", dt_us);
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

2023-06-10 15:33 UTC, nielsnl68 commented
Greate work @ayufan,

Do you think we can simplify the `get_color()` a bit more by combining those four in to one function?

2023-06-10 15:36 UTC, ayufan commented
@nielsnl68 I have to think about this, maybe in next PR, since there's an overhead for `switch`. I'm playing with various ways to speed-up the bitblit since this code related to rendering is crazy slow, and it is possible to make it easily 20x faster.

So, far I'm unifying everything to be derivative of `Image`, next will be making `Glyph` rendering to be also done through `Image`.

2023-06-10 15:44 UTC, nielsnl68 requested changes
Suc6

2023-06-10 15:44 UTC, nielsnl68 commented on esphome/components/display/display_buffer.cpp
>  void Animation::prev_frame() {
I'm missing the `next_frame()` method or am i overlooking it?

2023-06-10 15:44 UTC, nielsnl68 commented on esphome/components/display/display_buffer.cpp
> +void Animation::update_data_start_() {
It would be nice when this function moves to the  `Image` class. Where current_frame_ is always set to **0**.

2023-06-10 15:44 UTC, nielsnl68 commented on esphome/components/display/display_buffer.cpp
> +  const uint32_t image_size = width_aligned * this->height_;
When you try to speed up this classes, i think you should also try not to create to many unneeded variables just to calculate a result, are you not agree?

2023-06-10 15:44 UTC, nielsnl68 commented on esphome/components/display/display_buffer.h
> +  Color get_grayscale_pixel(int x, int y) const;
As wrote above, maybe we can combine this functions to one as well?

2023-06-10 15:48 UTC, ayufan commented on esphome/components/display/display_buffer.cpp
>  void Animation::prev_frame() {
A few lines up.

2023-06-10 15:48 UTC, ayufan commented on esphome/components/display/display_buffer.cpp
> +void Animation::update_data_start_() {
@nielsnl68 This will not work. This method is only applicable to `Animation`, since Animation knows that it has frames and Animation implements frames rotation.

2023-06-10 15:48 UTC, ayufan commented on esphome/components/display/display_buffer.h
> +  Color get_grayscale_pixel(int x, int y) const;
This is too big of a change for now. This color blitting needs to be completely reworked, and I would prefer to look at this separately.

The purpose of this PR is to do targeted change that does not break existing interfaces. Someone could have esphome integration that depends on `get_color_pixel`.

2023-06-10 15:48 UTC, nielsnl68 commented
> So, far I'm unifying everything to be derivative of `Image`, next will be making `Glyph` rendering to be also done through `Image`.

Fantastic idea, makes my Switchplate work much simpler :D

BTW, pleace checkout @guillempages work as well and try to work together ;)

2023-06-10 15:49 UTC, ayufan commented on esphome/components/display/display_buffer.cpp
> +  const uint32_t image_size = width_aligned * this->height_;
It does not matter. Those are added for readability purposes, they are optimised by the compiler anyway.

2023-06-10 15:55 UTC, guillempages commented
I also spent some time trying to unify everything into "get_color" but found out that it was faster to actually keep the 4 methods separate 😕

I'd be glad to be proven wrong though.

Regarding "unvirtualizing" those methods, please hold on. I'm working in adding support for runtime images (i.e. downloaded at runtime), and that code is relying on the virtual methods 😕

There's might be a way around that, I'm not sure. My problem is that current images need to read from program memory, but the runtime images need to read from heap memory (or psram when available)

2023-06-10 16:01 UTC, ayufan commented
@guillempages I have easy trick for you then: Pass execution to `image->draw()`.

```c++
class DisplayBuffer {
public:
  void image(int x, int y, BaseImage *image, Color color_on = COLOR_ON, Color color_off = COLOR_OFF) {
    image->draw(this, x, y, color_on, color_off);
  }

class BaseImage {
public:
  virtual void draw(DisplayBuffer *buffer, int x, int y...) = 0;
};

class Image : BaseImage {
public:
}

class CompressedImage {};
```

It will be cheaper to decode image online and render it right away, since the larger images will use a lot of memory. The `Image` could then figure out the best way to decode in a target format of `DisplayBuffer` if it starts exposing what this format is.

2023-06-10 16:09 UTC, guillempages commented
Ok, I was just answering blindly to @nielsnl68 comment. I'll need to take a look at your proposal then, and see of I can leverage that. 🙂

2023-06-10 18:55 UTC, nielsnl68 commented
> Ok, I was just answering blindly to @nielsnl68 comment. I'll need to take a look at your proposal then, and see if I can leverage that. 🙂

that is way i pinged you on this PR  👍🏻

2023-06-10 19:45 UTC, guillempages commented on esphome/components/display/display_buffer.cpp
> +      return 0;
I'm not sure if it is a good idea to set the default to 0.
Maybe not having a default case at all? Depending on how the compilation warnings are setup, this should fail compilation (or at least give a warning) if a new type is added to the enum, and not added to the switch.

2023-06-10 19:46 UTC, ayufan commented on esphome/components/display/display_buffer.cpp
> +      return 0;
Yes, this is good idea, to ensure that all cases are always covered.

2023-06-10 19:52 UTC, guillempages commented on esphome/components/display/display_buffer.h
> +  Color get_grayscale_pixel(int x, int y) const;
Also (as mentioned on another PR), having the image type check at runtime has a ~10% performance penalty.
I did some tests regarding that on https://github.com/esphome/esphome/pull/4600#discussion_r1153808915
(having a single `get_pixel` method that chooses which method to use internally basically amounts to the same as the "switch-within-for" use case)

I'd strongly advise against having this single `get_pixel` (unless you are able to find some performance trick to avoid having to check the image type at every pixel)

2023-06-10 19:54 UTC, ayufan commented on esphome/components/display/display_buffer.h
> +  Color get_grayscale_pixel(int x, int y) const;
The current implementation of `display` is far from being performance focused. It is to be rewritten completely, since working on individual pixels will newer work fast. Here you can find twisting the problem around: https://github.com/esphome/esphome/pull/4932 and gaining a few more %.

2023-06-10 19:55 UTC, guillempages commented
Now I did look at the code :-D

In general it looks good, but I'm still concerned about removing the "virtual" calls; since there might be external components (or the already mentioned PR #4710) that rely on the `get_xxx_pixel` methods being virtual.

I find the animation part a great idea though.

2023-06-10 19:56 UTC, ayufan commented
> In general it looks good, but I'm still concerned about removing the "virtual" calls; since there might be external components (or the already mentioned PR https://github.com/esphome/esphome/pull/4710) that rely on the get_xxx_pixel methods being virtual.

Well. I cannot test that :) I think that in general people do update their components with breaking changes from `esphome`. I did it a few times :)

2023-06-10 19:59 UTC, guillempages commented on esphome/components/display/display_buffer.h
> +  Color get_grayscale_pixel(int x, int y) const;
It's not about making it "fast", it's about not making it "slower" :-D

2023-06-10 19:59 UTC, guillempages commented on esphome/components/display/display_buffer.h
> +  Color get_grayscale_pixel(int x, int y) const;
Let's see where this leads

2023-06-10 21:00 UTC, ayufan commented
@guillempages Thanks for the review of all PR. I appreciate all the comments :) Can you guide me which one of those I should address, or should I wait for more feedback? There are code-style ones like handling `default:` and `ImageAlign::HORIZONTAL_ALIGN` which are great suggestions, but I'm unsure how to handle the functional suggestions.

2023-06-10 21:09 UTC, guillempages commented
@ayufan I'm not a maintainer of the repo, nor a code-owner of any part of it, so I cannot tell you which part will bring the greatest chances of success :-D @nielsnl68 mentioned me, because I have also done some modifications to the image and animation parts lately (and as I mentioned, I still have two of them open).

From experience, it takes a while until some senior reviewer looks at the PR. So you might want to start thinking about that, and maybe implementing some of them, if you think they are valid/worth it.

2023-06-10 21:10 UTC, ayufan commented
> From experience, it takes a while until some senior reviewer looks at the PR. So you might want to start thinking about that, and maybe implementing some of them, if you think they are valid/worth it.

I don't want to open too many and have them lingering :)

2023-06-10 21:14 UTC, guillempages commented
You can modify them locally, and do a force-push, so that you stay at three PRs. If the changes are directly related to one PR, it's ok to have more than one commit on that branch. You then need to rebase the other PRs, of course.

I also had three PRs that based on each other, and Jesse put the latter two to draft, so that it's clear that there is no point in reviewing them yet (since the code is part of the other PRs, *and* might change because of suggestions/requests on the previous ones). So I had to wait until each one got merged, and then rebase and set the next one to "ready for review".

2023-06-14 21:45 UTC, jesserockz approved these changes

2023-06-14 21:50 UTC, merged