Add actions to animation
OttoWinter/esphomeyaml pull request #4959
Opened 2023-06-17 21:32 UTC by guillempages

# What does this implement/fix?

Add actions to be able to easily change the current frame to the animation component.
Instead of needing to use a lambda and c++ code, allow a simple yaml action to switch to the next or previous frame, or to set a specific frame.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#TBD

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```yaml
animation:
  - id: fire
    file: fire.gif

interval:
  - interval: 200ms
    then:
       - animation.next_frame: fire
# Alternative 1:
#       - animation.prev_frame: fire
# Alternative 2:
#       - animation.set_frame:
#          - id: fire
#            frame: 5
       - component.update: disp

display:
  - platform: <xyz>
     id: disp
     lambda: |-
       it.image(0, 0, id(fire));
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-06-18 22:37 UTC, jesserockz commented on esphome/components/animation/__init__.py
> +        cv.Required(CONF_FRAME): cv.positive_int,
```suggestion
        cv.Required(CONF_FRAME): cv.uint16_t,
```

2023-06-18 22:39 UTC, jesserockz requested changes

2023-06-18 22:39 UTC, jesserockz commented on esphome/components/display/animation.cpp
> +#include "esphome/core/log.h"
Why is this needed? There are no logs in this file?

2023-06-19 07:10 UTC, guillempages commented on esphome/components/display/animation.cpp
> +#include "esphome/core/log.h"
Ouch. I removed the debug logs I was using while implementing, and forgot to remove the include.

Good spot, thanks!

2023-06-19 22:49 UTC, jesserockz approved these changes

2023-06-19 22:50 UTC, merged