airthings_wave: Battery level reporting
OttoWinter/esphomeyaml pull request #4979
Opened 2023-06-21 00:17 UTC by kpfleming

# What does this implement/fix?

Reports battery level (0-100%) of Airthings devices as an additional sensor.

Also adds the author as a CODEOWNER of the modified components.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```yaml
# Example config.yaml
sensor:
  - platform: airthings_wave_plus
    ble_client_id: airthings01
    update_interval: 5min # default
    temperature:
      name: "WavePlus Temperature"
    radon:
      name: "WavePlus Radon"
    radon_long_term:
      name: "WavePlus Radon Long Term"
    pressure:
      name: "WavePlus Pressure"
    humidity:
      name: "WavePlus Humidity"
    co2:
      name: "WavePlus CO2"
    tvoc:
      name: "WavePlus VOC"
    battery_level:
      name: "WavePlus Battery Level"
      low_voltage_reference: 2.2V # default
      high_voltage_reference: 3.2V # default
      update_interval: 24h # default
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-07-11 03:21 UTC, jesserockz requested changes

2023-07-11 03:21 UTC, jesserockz commented on esphome/components/airthings_wave_base/__init__.py
> +                device_class=DEVICE_CLASS_BATTERY,
```suggestion
                device_class=DEVICE_CLASS_VOLTAGE,
```

2023-07-11 03:21 UTC, jesserockz commented on esphome/components/airthings_wave_base/__init__.py
> +            ),
We don't expose fake virtual sensors like this. If people want a percentage based sensor then they can make a `copy` sensor with filters or change the voltage to percent and use filters there.
```suggestion

```

2023-07-11 10:53 UTC, kpfleming commented on esphome/components/airthings_wave_base/__init__.py
> +            ),
Fair enough... I wondered about that :-)

In the companion PR for esphome-docs I'll include examples of those methods for deriving the percentage, since users will likely want to have it mirror (or at least be close to) the percentage reported in the Airthings mobile app.

2023-07-11 14:06 UTC, kpfleming commented
Requested changes have been made, docs PR updated, new version running in 'production' on one of my ESP32R4s.

2023-07-12 01:36 UTC, jesserockz approved these changes
Thanks for making the changes. And yes documenting that is acceptable.

2023-07-12 01:38 UTC, merged