Gcja5 vector
OttoWinter/esphomeyaml pull request #4988
Opened 2023-06-21 23:57 UTC by gcormier

# What does this implement/fix?

Support for Panasonic SN-GCJA5 https://api.pim.na.industrial.panasonic.com/file_stream/main/fileversion/244938

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3011

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

uart:
  rx_pin: GPIO10
  parity: EVEN
  baud_rate: 9600

esphome:
  name: pannypm

sensor:
  - platform: gcja5
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-07-05 21:00 UTC, functionpointer commented
Not a maintainer, but i think the `core` label is bad for a PR like this.
It means you are modifying files that are part of the esphome core, which shouldn't be needed for a new sensor.

Looks like you changed something the `clang-format` script. Is that really needed?

2023-07-06 00:33 UTC, gcormier commented
Well I just blew that up with `git`. Yikes.

As far as the label, I didn't apply it, bot did.

I removed my clang-format changes, and then in trying to rebase I blew things up :| Don't know if I can recover this or if I should just make a new PR?

2023-07-11 04:05 UTC, jesserockz requested changes

2023-07-11 04:05 UTC, jesserockz commented on tests/test1.yaml
> +    uart_id: gcja5_uart
Please add all sensors here so we know if they get broken in the future.

2023-07-11 04:05 UTC, jesserockz commented on esphome/components/gcja5/gcja5.cpp
> +void GCJA5Component::update() {
You should update the sensors when the data comes in via the loop, not in update as this is not a polling sensor but just receives data when it is new and current.

2023-07-11 22:01 UTC, gcormier commented on tests/test1.yaml
> +    uart_id: gcja5_uart
Completed

2023-07-11 22:03 UTC, gcormier commented on esphome/components/gcja5/gcja5.cpp
> +void GCJA5Component::update() {
Is this what you had in mind?

https://github.com/esphome/esphome/pull/4988/files/e15550ae4e7f7bcff09f48fd5a0f6c2d2675f23a..0daf400e5baa4817c0cb3166a8e1b6463950e420#diff-eea3104323ebfe4453602fae493747639ce9353e41ea843605531ac92c284515R37-R65

2023-07-12 20:44 UTC, jesserockz approved these changes, later dismissed
Yeah looks good now apart from this block of commented code

2023-07-12 20:44 UTC, jesserockz commented on esphome/components/gcja5/gcja5.cpp
> +
```suggestion
```

2023-07-13 00:30 UTC, ssieb commented
@functionpointer it's definitely possible for a new sensor to be marked as a core change if there are new constants added to the const.py file.

2023-08-08 00:19 UTC, jesserockz requested changes

2023-08-08 00:19 UTC, jesserockz commented on esphome/components/gcja5/gcja5.cpp
> +  have_good_data_ = true;
Please make sure to prefix the member variables with `this->`
```suggestion
  this->have_good_data_ = true;
```

2023-08-08 01:50 UTC, jesserockz requested changes

2023-08-08 01:50 UTC, jesserockz commented on esphome/components/gcja5/gcja5.cpp
> +      if (have_good_data_) {
```suggestion
      if (this->have_good_data_) {
```

2023-08-08 01:50 UTC, jesserockz commented on esphome/components/gcja5/gcja5.cpp
> +  if (!first_status_log_) {
```suggestion
  if (!this->first_status_log_) {
```

2023-08-09 19:38 UTC, jesserockz approved these changes

2023-08-10 05:04 UTC, merged