Add 'map_linear' and 'clamp' sensor filters
OttoWinter/esphomeyaml pull request #5040
Opened 2023-07-02 13:58 UTC by Mat931

# What does this implement/fix?

Adds 2 new sensor filters:
- `map_linear`: similar to calibrate_linear but can have multiple linear equations if more that 2 points are configured
- `clamp`: makes sure the value stays in a minimum/maximum range

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: sensor-filters
  friendly_name: sensor_filters

esp32:
  board: esp32dev
  framework:
    type: arduino

sensor:
  - platform: template
    id: testsensor
    filters:
      - clamp:
          min_value: -5
          max_value: 5
      - map_linear:
          - -1 -> 2
          - 0.0 -> 0.0
          - 1.0 -> 1.0
          - 2.0 -> 2.0

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      inverted: true
    id: test
    filters:
      - delayed_on_off: 100ms
    on_press:
      - lambda: !lambda |-
          id(testsensor).publish_state(-6);
          id(testsensor).publish_state(-5);
          id(testsensor).publish_state(-4);
          id(testsensor).publish_state(-2);
          id(testsensor).publish_state(0);
          id(testsensor).publish_state(2);
          id(testsensor).publish_state(4);
          id(testsensor).publish_state(5);
          id(testsensor).publish_state(6);
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-07-03 08:02 UTC, Misiu commented
Maybe instead of adding a new filter (`map_linear`) extend `calibrate_linear` to support more than two points. As you mentioned both will do the exact same thing.

> If only two values are given this behaves exactly the same as ``calibrate_linear``.

2023-07-03 09:54 UTC, Mat931 commented
@Misiu Yeah that would be possible. The only difference would be the calculation of the linear function(s) in Python. The `calibrate_linear` filter could re-use the C++ code from `map_linear`.

2023-07-04 00:42 UTC, jesserockz requested changes

2023-07-04 00:42 UTC, jesserockz commented on esphome/components/sensor/__init__.py
> +        validate_calibrate_linear,
Can this be change to use `cv.maybe_simple_value` so this is not a breaking change in config

2023-07-30 21:07 UTC, jesserockz approved these changes

2023-07-30 21:09 UTC, merged