Prepare some components for IDF >= 5
OttoWinter/esphomeyaml pull request #5061
Opened 2023-07-05 15:12 UTC by HeMan

# What does this implement/fix?

Prepares enough components for IDF >= 5 so that test5.yaml works with latest version. Also added test5.1.yaml that uses latest version.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-07-05 16:21 UTC, jhansche requested changes
For the record: Only looked at `bedjet`

2023-07-05 16:21 UTC, jhansche commented on esphome/components/bedjet/bedjet_hub.cpp
> +        ESP_LOGVV(TAG, "[%s] Decoding packet: last=%" PRId32 ", delta=% " PRId32 ", force=%s", this->get_name().c_str(),
Looks like there's a space added here? Won't be a valid replacement

2023-07-05 16:29 UTC, HeMan commented on esphome/components/bedjet/bedjet_hub.cpp
> +        ESP_LOGVV(TAG, "[%s] Decoding packet: last=%" PRId32 ", delta=% " PRId32 ", force=%s", this->get_name().c_str(),
Ah, good you spotted that! Fixing it.

2023-07-05 17:06 UTC, DAVe3283 commented
Tested `max31865` on an ESP8266 and it compiles/runs as expected. Can't test the ESP-IDF as I don't have a spare 31865 to hook to an ESP32. But the changes look good to me.

2023-07-05 20:25 UTC, jhansche commented
Just thinking out loud here: is there any reason we wouldn't be able to handle these automatically in the ESP_LOG* macro(s)?

I guess it would involve either converting the %d arguments to the expected type at runtime, or doing a string replacement of the %d format placeholder, which might be more effort than we want to go through 🤔

2023-07-09 23:32 UTC, jesserockz commented on esphome/components/esp32_ble/ble_uuid.cpp
>        return str_snprintf("0x%02X%02X", 6, this->uuid_.uuid.uuid16 >> 8, this->uuid_.uuid.uuid16 & 0xff);
Shouldnt this be changed to match too?

2023-07-10 03:24 UTC, jhansche commented on esphome/components/esp32_ble/ble_uuid.cpp
>        return str_snprintf("0x%02X%02X", 6, this->uuid_.uuid.uuid16 >> 8, this->uuid_.uuid.uuid16 & 0xff);
I would expect that %X should be unambiguous? It sounds like it's just (u)int(32) that's changing?

2023-07-10 03:30 UTC, jhansche commented on esphome/components/max31865/max31865.cpp
> +               "Fault detection incomplete (0x%02X) after %" PRIu32 "μs (datasheet spec is 600μs max)! Aborting read.",
Another %X here too

2023-07-10 03:33 UTC, jhansche commented on esphome/components/sen5x/sen5x.cpp
>    ESP_LOGCONFIG(TAG, "  Firmware version: %d", this->firmware_version_);
I admit I'm not entirely sure what the goal is, or why some placeholders are replaced but others aren't.

If it's necessary for the new IDF, could we come up with a lint check that would make these easier to spot?

The new macro admittedly feels clunky to me 🤷‍♂️

2023-07-10 06:31 UTC, HeMan commented on esphome/components/esp32_ble/ble_uuid.cpp
>        return str_snprintf("0x%02X%02X", 6, this->uuid_.uuid.uuid16 >> 8, this->uuid_.uuid.uuid16 & 0xff);
Hmm, it compiles both without changes and when changed to `PRIX16`. It could be that uint16_t doesn't change between IDF 4 and IDF 5. Anyway, I'll match with PRIX16.

2023-07-10 06:34 UTC, HeMan commented on esphome/components/max31865/max31865.cpp
> +               "Fault detection incomplete (0x%02X) after %" PRIu32 "μs (datasheet spec is 600μs max)! Aborting read.",
Similar resolution here as in https://github.com/esphome/esphome/pull/5061#discussion_r1257772707, uint8_t doesn't change between IDF 4 and 5, but I change to match.

2023-07-10 06:52 UTC, HeMan commented
When I started to look in to it, not sure if all the format specifiers should be macro'ified. Changing all won't give any benefits now, but could reduce work in the future if datatypes changes. 
Just changing the bare minimum is easier since it fails to compile on IDF => 5, and it reduces noise in that the PR's gets smaller.
What do you say?

2023-07-10 16:59 UTC, jhansche commented
> Just changing the bare minimum is easier since it fails to compile on IDF => 5, and it reduces noise in that the PR's gets smaller.

My concern is that the new ESP_LOG* invocations look clunky and overly verbose. It doesn't look like a natural logging statement. That's why my [earlier question](https://github.com/esphome/esphome/pull/5061#issuecomment-1622446107) was trying to propose ideas to handle this in a different way - one that _doesn't_ require changing every place we use `%u` for example; instead it would be handled by the ESP_LOG* macros internally, but only on IDF5+. I can't think of a magical way to do that that doesn't also become a heavy lift, unfortunately (like a string replacement JIT at runtime)

What exactly is the change? Is there a link to documentation explaining what is actually causing this? Sounds like you're saying that IDF5 changes the definition of `uint32_t` (etc)?

2023-07-18 01:58 UTC, jesserockz commented on esphome/components/esp32_ble/ble_uuid.cpp
>        return str_snprintf("0x%02X%02X", 6, this->uuid_.uuid.uuid16 >> 8, this->uuid_.uuid.uuid16 & 0xff);
Either that, or change the arguments, considering they are all technically bit shifted down to uint8_t anyway, we could cast each one to keep the format string simpler.

2023-07-24 22:56 UTC, kbx81 commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +  ESP_LOGCONFIG(TAG, "  Full Update Every: %" PRIu32, this->full_update_every_);
Extra `%` symbol left here?

```suggestion
  ESP_LOGCONFIG(TAG, "  Full Update Every: " PRIu32, this->full_update_every_);
```

2023-07-25 04:50 UTC, kbx81 approved these changes

2023-07-25 05:09 UTC, kbx81 commented
I'm fine with this -- any final comments before we merge?

2023-07-27 05:18 UTC, merged