ESP-IDF SPI LED strip (APA102/SK9822)
OttoWinter/esphomeyaml pull request #5101
Opened 2023-07-14 13:52 UTC by dentra

# What does this implement/fix?

This PR adds ESP-IDF support  for SPI LED strips on APA102 and SK9822 chips.
Tested with my Lilygo Dongle S3 with one led.

I will do PR in the docs a little later.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
light:
  - platform: esp32_spi_led_strip
    name: "Led Light"
    data_pin: GPIO40
    clock_pin: GPIO39
    num_leds: 1
    rgb_order: RGB
    max_refresh_rate: 50us
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-07-16 07:06 UTC, kbx81 commented
Ah! I was just thinking we needed this. 😄
Please be sure to add a simple test into one of the `test*.yaml` files. I'll try to test this here and review this week.
Thanks for working on this! 🍻

2023-07-16 22:22 UTC, jesserockz reviewed
Why is this restricted to esp-idf? It should work on arduino too as esp-idf headers/code are available there

2023-07-17 12:43 UTC, dentra commented
added test and support of arduino platform

2023-07-18 22:26 UTC, kbx81 commented
Tested this today on my Adafruit Funhouse board and it works beautifully! Now I can use ESP-IDF alone on this hardware. 😁

That said, it's getting into some trouble when using the Arduino framework. It appears it keeps crashing -- although it doesn't crash _immediately_ (seems to take about a minute or two). This board does not have a proper serial adapter (it depends on the ESP's USB interface) so I can't see the logs. I'll see if I can try it on different hardware that allows me to see what's up, but I figured I'd mention it here in the meantime. 😇

Overall, good work!

2023-07-25 05:16 UTC, kbx81 requested changes
Quick thing I found relating to IDF 5+ compatibility

2023-07-25 05:16 UTC, kbx81 commented on esphome/components/esp32_spi_led_strip/led_strip.cpp
> +    ESP_LOGCONFIG(TAG, "  Max Refresh Rate: %u Hz", this->max_refresh_rate_);
For IDF 5+ compatibility:
```suggestion
    ESP_LOGCONFIG(TAG, "  Max Refresh Rate: %" PRIu32 " Hz", this->max_refresh_rate_);
```

2023-07-25 05:16 UTC, kbx81 commented on esphome/components/esp32_spi_led_strip/led_strip.cpp
> +    ESP_LOGCONFIG(TAG, "  Max Refresh Rate: %u Hz", this->max_refresh_rate_);
...you'll also need to `#include <cinttypes>`

2023-07-25 18:27 UTC, dentra commented on esphome/components/esp32_spi_led_strip/led_strip.cpp
> +    ESP_LOGCONFIG(TAG, "  Max Refresh Rate: %u Hz", this->max_refresh_rate_);
done.

2023-07-25 18:28 UTC, dentra commented on esphome/components/esp32_spi_led_strip/led_strip.cpp
> +    ESP_LOGCONFIG(TAG, "  Max Refresh Rate: %u Hz", this->max_refresh_rate_);
do I also change %d -> PRId16 for num_leds_ and %d -> PRId8 for data_pin_ and clock_pin_?

2023-07-26 06:12 UTC, kbx81 commented on esphome/components/esp32_spi_led_strip/led_strip.cpp
> +    ESP_LOGCONFIG(TAG, "  Max Refresh Rate: %u Hz", this->max_refresh_rate_);
No need for those -- this is a change made in IDF 5+ that only affects 32-bit `int` types. 😄

2023-07-27 04:51 UTC, kbx81 commented
Alrighty, I've been testing this pretty extensively today and have some feedback...and I apologize in advance for this because it's a bit lengthy. 😇 Regardless, I'm excited to have this component available and I'm sure it'll be widely used, so we need to get it just right. 😄

I'm testing with the [Funhouse board from Adafruit](https://www.adafruit.com/product/4985) because it has five APA102s along the top of it -- very convenient to use for this purpose. I've been building with either of these two configurations:

```yaml
esp32:
  board: adafruit_funhouse_esp32s2
  framework:
    type: arduino
    version: 2.0.9
    platform_version: 5.4.0
```

```yaml
esp32:
  board: adafruit_funhouse_esp32s2
  framework:
    type: esp-idf
    version: 5.0.2
    platform_version: 6.3.2
```

I've also tried Arduino with `platform_version: 6.3.2`.

In any event, here's what I've found, largely based on this board:

**SPI `display` + `esp32_spi_led_strip`**

Something very bad is happening when the ST7789 (and I'm going to make the leap guess other SPI displays, too) is used with this component, regardless of the framework. I have not dug into it deeply, but my gut is telling me that it's some conflict between this component's SPI initialization and what ESPHome is doing for the display. This brings us to a suggestion:

Instead of defining the data and clock pins within this component and having it do its own initialization of the SPI, should we instead use ESPHome's built-in SPI handling and then point this component at that? In other words, perhaps `esp32_spi_led_strip` could inherit from `SPIDevice` and (in the config) it would get a `spi_id` telling it which interface instance to use (which, naturally, includes the pins) -- I think this would mitigate any conflicts as it relates to the initialization of the hardware. It's not uncommon to use a display with LEDs such as this.

**Color ordering**

This is short and sweet: for the LEDs on the Funhouse board, I use the `BGR` order with `fastled_spi` but I have to use `RGB` with `esp32_spi_led_strip `. Not a big deal, but some folks might complain/be confused/think something is wrong if they switch from that to this.

**Arduino**

When built with the Arduino framework and including the changes I have in [this PR](https://github.com/esphome/esphome/pull/5116), I am getting some *bizarre* behavior. It's an odd combination of things that I haven't dug in to pin down just yet, but, to name a few:

- Wi-fi sometimes won't connect -- it scans, finds the network, but connecting continuously fails; eventually it falls back to starting the fallback AP but this also fails, logging errors about failing to allocate buffer memory (???)
- When it *does* connect to wi-fi, it logs a connection from HA but either:
  - HA indicates all of its entities are unavailable
  - Everything operates normally for a minute or two but then the connection stalls and drops until the ESP is reset
- It'll crash randomly, although this is infrequent

Casual observation: when running an effect (such as the built-in Twinkle), the effect freezes at the same time the HA connection stalls/drops (as described above). It's not completely freezing/crashing, though, as it continues to log readings from the other sensors on the board (seen via serial logs). There's something really weird going on there...

I'm completely at a loss to explain what's going on -- I've never seen behavior this erratic. 😅 I probably need more time to sort through it and to try to pin down (a) specific cause(s).

**ESP-IDF**

When built with ESP-IDF, the SPI display issue aside, everything seems to work just fine. 🎉

Ok, I think that's everything for now. Thanks for reading all this. If I work out anything else, I'll report back...

2023-07-27 15:36 UTC, dentra commented
@kbx81 thank you for such a detailed review and testing. 
I will try to look deeper to use SPIDevice. Changing color ordering is very simple, I will do that.

2023-07-28 16:47 UTC, dentra commented
SPIDevice does not use hardware capabilities for ESP-IDF, but does it only for Arduino. Thus, there may be a collision of using the same spi_bus_id when compiling in the Arduino environment. In this component is is hardcoded to SPI2_HOST (looking for a solution).

2023-07-28 23:33 UTC, kbx81 commented
> SPIDevice does not use hardware capabilities for ESP-IDF, but does it only for Arduino. Thus, there may be a collision of using the same spi_bus_id when compiling in the Arduino environment. In this component is is hardcoded to SPI2_HOST (looking for a solution).

Jesse and I were discussing this yesterday. I'm going to do some work to move IDF onto the SPI hardware. I had no idea it was bit-banging when I made this suggestion. Will fix soon.

2023-09-11 02:16 UTC, kbx81 commented
Thank you for working on this! Just to let you know, the SPI component was refactored in #5311 and the author wrote #5288 in parallel; as such, it's fully updated and using `SPIDevice`, pulling in hardware full support when/where it's able & configured. As such, we're going to move forward with #5288. Regardless, thank you for your contribution.

2023-09-11 02:16 UTC, closed without merging