Add ESP32-S2/S3 capacitive touch support
OttoWinter/esphomeyaml pull request #5116
Opened 2023-07-18 01:21 UTC by kbx81

# What does this implement/fix?

Make capacitive touch work on ESP32-S2/S3 variants, yay!

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**
- Fixes https://github.com/esphome/issues/issues/4411
- Implements https://github.com/esphome/feature-requests/issues/2131

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32-S2
- [ ] ESP32-S3
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```yaml
# illustrates NEW configuration options implemented
esp32_touch:
  denoise_grade: BIT12
  denoise_cap_level: L0
  debounce_count: 1
  filter_mode: IIR_16
  noise_threshold: 0
  jitter_step: 0
  smooth_mode: IIR_2
  waterproof_guard_ring: 5
  waterproof_shield_driver: L0
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-07-18 01:54 UTC, jesserockz requested changes

2023-07-18 01:54 UTC, jesserockz commented on esphome/components/esp32_touch/__init__.py
> +    variant = CORE.data[KEY_ESP32][KEY_VARIANT]
```suggestion
    variant = get_esp32_variant()
```

2023-07-18 01:54 UTC, jesserockz commented on esphome/components/esp32_touch/esp32_touch.cpp
> +#endif
AS if they couldn't make the touch APIs even more different, they made the value opposite too?

2023-07-18 01:58 UTC, kbx81 commented on esphome/components/esp32_touch/esp32_touch.cpp
> +#endif
yup 😅

2023-07-18 02:08 UTC, kbx81 commented on esphome/components/esp32_touch/esp32_touch.cpp
> +#endif
...mostly explained in:
- https://docs.espressif.com/projects/esp-idf/en/v4.4.5/esp32/api-reference/peripherals/touch_pad.html#_CPPv423touch_pad_set_meas_time8uint16_t8uint16_t
- https://docs.espressif.com/projects/esp-idf/en/v4.4.5/esp32s2/api-reference/peripherals/touch_pad.html

2023-08-07 01:51 UTC, jesserockz approved these changes

2023-08-07 01:54 UTC, merged