image: allow the image to by auto-loaded by animation
OttoWinter/esphomeyaml pull request #5139
Opened 2023-07-22 08:56 UTC by ayufan

This fixes the case where only `animation:` is present and `image:` is auto-loaded.

This introduces `MULTI_CONF_NO_DEFAULT=True` that allows to include image source code only without initialising a default object.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

Per `test8.yaml` included in PR.

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

2023-07-22 22:56 UTC, nielsnl68 commented
@ayufan , although this fix is mostly for the `animation` issue.
The fix itself is a more common one. May i suggest to change the title more to that change then to the animation issue.

2023-08-01 17:12 UTC, geiseri commented
@ayufan Wouldn't this better be addressed by the image component directly?  I am not sure what other components it could impact to warrant this being more general.  This is a special case where the image functionality can be used without an actual component.  I could argue it is "being used wrong" as other animation implementations use sprites.  It would be a single image with all of the frames together and the memory is blit from each frame offset.  Technically I think that is what it is doing under the hood anyway.  The only other place I could see this is `color`.  You might want to subclass that one to provide a dynamic behavior similar to animation. 

@nielsnl68 I also have this issue in a custom component that is a factory that constructs images.  I moved it subclass image, but remained with the same issue.  Would it be better to have it named `SUBCLASS_COMPONENT` or `IMPLEMENTS_COMPONENT`?

2023-08-18 13:48 UTC, guillempages commented
@nielsnl68 it is not only animation; IIRC there was someone on discord complaining about this issue for a font, and my online_image implementation also has the same issue.

@ayufan as niels mentioned, it might be a good idea to handle this generically; not animation specific. I created a PR a while ago to add the test that you are adding for the animation; we might want to split that, add the tests for animation and font in my PR (#5057) and keep the fix here.

2023-08-18 13:50 UTC, guillempages commented
@ayufan you might want to add "Fixes #4719" to the description as well (and there might be other duplicate issues as well)

2023-12-19 01:46 UTC, jesserockz commented
I started to look into this again and remembered this PR and I think its actually the best way forward =)

2023-12-19 01:50 UTC, jesserockz approved these changes

2023-12-19 01:50 UTC, jesserockz commented
Tested working locally and also with https://github.com/esphome/esphome/pull/5218 (after adding the new flag to `uart`)

2023-12-20 10:10 UTC, jesserockz requested changes
Rebase required

(I'm just using this PR to test a new bot on the ESPHome github repo)

2023-12-20 10:11 UTC, ayufan commented
@jesserockz This is rebased.

2023-12-20 10:12 UTC, ayufan commented
@jesserockz This is rebased.

2023-12-20 10:16 UTC, jesserockz commented
Thanks @ayufan

2023-12-20 10:20 UTC, jesserockz approved these changes

2023-12-20 10:33 UTC, merged