Draft: Add BMI160 support
OttoWinter/esphomeyaml pull request #5143
Opened 2023-07-23 01:24 UTC by flaviut

# What does this implement/fix?

Still WIP--want to see what the CI says about this. I'll also do the docs before 

Adds support for [the Bosch BMI160 IMU](https://www.bosch-sensortec.com/products/motion-sensors/imus/bmi160/)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
  - platform: bmi160
    address: 0x68
    accel_x:
      name: BMI160 Accel X
    accel_y:
      name: BMI160 Accel Y
    accel_z:
      name: BMI160 Accel z
    gyro_x:
      name: BMI160 Gyro X
    gyro_y:
      name: BMI160 Gyro Y
    gyro_z:
      name: BMI160 Gyro z
    temperature:
      name: BMI160 Temperature
    i2c_id: i2c_bus
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-07-23 03:11 UTC, flaviut commented on esphome/components/bmi160/bmi160.cpp
> +  delay(81);
Unfortunately I don't see a better way to do this--I could do a loop checking the I2C register if it's done yet, but that's a lot of work to maybe save 30ms (typical duration of this step is 50ms, max is 81ms)

2023-07-24 07:05 UTC, clydebarrow commented on esphome/components/bmi160/bmi160.cpp
> +  delay(81);
You could extract the succeeding code into another function and use `set_timeout()` to call it later.

2023-07-26 22:00 UTC, flaviut commented on esphome/components/bmi160/bmi160.cpp
> +  delay(81);
Good call! Thank you and done.

2023-07-27 01:51 UTC, clydebarrow requested changes

2023-07-27 01:51 UTC, clydebarrow commented on esphome/components/bmi160/bmi160.cpp
> +      this->set_timeout(81, [this]() { this->internal_setup_(2); });
If 81ms is the maximum per the datasheet, I'd allow a little extra in case the timeout call happens early. There is no guarantee on the accuracy of the timeout, and while I'm fairly certain it will not happen early, an extra few ms delay will do no harm. I'd round it up to 100ms.

2023-07-27 01:51 UTC, clydebarrow commented on esphome/components/bmi160/bmi160.cpp
> +  int16_t int_temperature = *reinterpret_cast<int16_t *>(&raw_temperature);
This relies on the executing architecture being little-endian. Better to explicitly shift and add the bytes, that way it's portable across architecures.

2023-07-27 01:51 UTC, clydebarrow commented on esphome/components/bmi160/sensor.py
> +CONF_ACCEL_X = "accel_x"
There are already similar config constants defined in esphome.const:
```
CONF_ACCELERATION_X = "acceleration_x"
CONF_ACCELERATION_Y = "acceleration_y"
CONF_ACCELERATION_Z = "acceleration_z"

```
I know that other gyro components define their own, but if they're in the system files I would think it better to use those. There are currently no GYRO versions in const.py - maybe you could add those as part of the PR.

2023-07-27 01:51 UTC, clydebarrow commented on esphome/components/bmi160/sensor.py
> +    icon=ICON_BRIEFCASE_DOWNLOAD,
There are icons defined in const.py for acceleration in three axes.

```
ICON_ACCELERATION_X = "mdi:axis-x-arrow"
ICON_ACCELERATION_Y = "mdi:axis-y-arrow"
ICON_ACCELERATION_Z = "mdi:axis-z-arrow"
```

Or just `ICON_ACCELERATION` if you don't care about differentiating them.

2023-07-28 03:18 UTC, flaviut commented
Good call on the icons & configs! Fixed & tested everything.

2023-09-09 04:17 UTC, flaviut commented
Hi I want to check in on this. I understand if it won't be merged, but I would like to at least have the icon changes merged so I can keep this custom integration in an upstreamable state.

2023-09-09 23:42 UTC, kbx81 approved these changes

2023-09-10 02:25 UTC, merged