Max31850
OttoWinter/esphomeyaml pull request #5149
Opened 2023-07-24 23:48 UTC by lylavoie

# What does this implement/fix?

Implements support for MAX31850 thermocouple, based on Dallas sensor component.  Deals with the unit conversions and error handling provided within the MAX31850 chip.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ X ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: dallas
    address: 0x973c01d075bd6028
    name: Boiler Water Supply Temp
  - platform: dallas
    address: 0x082d4c0f49858c3b
    name: Boiler Exhaust Temp
    chipset: max31850
```

## Checklist:
  - [ X ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ X ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-09-26 20:40 UTC, lylavoie commented
Checking if any further review / changes are needed?

2023-12-19 03:46 UTC, jesserockz requested changes

2023-12-19 03:46 UTC, jesserockz commented on esphome/components/dallas/sensor.py
>              cv.Optional(CONF_RESOLUTION, default=12): cv.int_range(min=9, max=12),
If the resolution cannot be changed on certain chipsets, then config validations should exist to block it being set.

2023-12-19 09:25 UTC, randybb commented
Is the chipset definition needed? Because 1wire 64-bit ID contains a 8-bit family code, so it can be always autodiscovered https://www.analog.com/en/technical-articles/1wire-software-resource-guide-device-description.html (Maxim 1-Wire device types are missing in this list).

2023-12-29 23:34 UTC, lylavoie commented on esphome/components/dallas/sensor.py
>              cv.Optional(CONF_RESOLUTION, default=12): cv.int_range(min=9, max=12),
This is not completely possible, because of the "auto" chipset, where the chipset isn't known until the i2c connection is made and the device ID is read.  We could validate the resolution / chipset, if it's not set to auto.  Do you have a preference?

2023-12-30 00:12 UTC, lylavoie commented
@randybb If I am ready the want the sensors are reporting correctly, it seems like the MAX31850 overload the 0x3B value.  The output below is from scanning the bus on my setup, and the 0x3248000ec426833b sensor is my MAX31850, while the other is a standard DS18B20 temp probe.  Unfortunately, the overloaded the value, bit bit stuffing for the two sensors is different.  That was the original reason I started this work.

[18:35:32][D][dallas.sensor:085]:   Found sensors:
[18:35:32][D][dallas.sensor:087]:     0x973c01d075bd6028
[18:35:32][D][dallas.sensor:087]:     0x3248000ec426833b

The other option would be to break the MAX31850 to a separate component, but I don't think that configuration would support sharing the same bus/wire with the other Dallas sensors.

2023-12-30 13:06 UTC, randybb commented
The dallas component is really old and it was never meant to be universal, so it is supporting only DS18B20 sensors. Probably a major rewrite would be needed to support various types of sensors/IO/bus bridges (at least the scanner could show the device family). Let's wait for the devs what they think about that.

2023-12-30 15:03 UTC, lylavoie commented
We could refactor the dallas component into a 1-wire base component and then sensor components, similar to the structure of SPI and other buses.  That would allow the different chipsets / sensors to become independent, at the cost of some duplicated code (between different sensors) and the bus component.

2024-01-12 19:27 UTC, randybb commented
And ideally when it could be used for i2c 1-wire masters like is mentioned here https://github.com/esphome/feature-requests/issues/621

2025-10-18 00:50 UTC, closed without merging