Add support for waveshare epaper 5.83in-bv2
OttoWinter/esphomeyaml pull request #5154
Opened 2023-07-26 19:06 UTC by jakubcermak

# What does this implement/fix?

Extension of waveshare_epaper component to support 5.83in-bv2 display

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 

https://github.com/esphome/esphome-docs/pull/3090

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  - platform: waveshare_epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 5.83in-bv2
    update_interval: 30s
    lambda: |-
      it.print(0, 10, id(def_font), "Hello World!");    
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-15 12:20 UTC, functionpointer commented
awesome!

2023-08-31 21:23 UTC, jakubcermak commented
is there anything I should do?

2023-09-10 14:29 UTC, jakubcermak commented
Btw I think it fixes https://github.com/esphome/feature-requests/issues/1477

2023-12-10 12:11 UTC, functionpointer commented
You may want to merge the `dev` branch into this periodically.
This should keep the bot happy. New integrations regularly take many months to merge.

2023-12-10 12:29 UTC, jakubcermak commented
not stale.
However this takes already half a year, is it normal? Or is the project dead and not accepting contributions anymore?

2023-12-10 12:45 UTC, functionpointer commented
Unfortunately it is normal.

ESPHome is quite active and the maintainers are active as well. There are just too many PRs

2023-12-21 08:55 UTC, jesserockz requested changes
Apologies for the delay. As mentioned above, there are so many PRs and so little reviewers that it can take a long time to get to some. And sometimes they just simply get lost in the PR list or accidentally skipped over.

We truly do appreciate contributions.
Jesse

2023-12-21 08:55 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.h
> +  void deep_sleep() override {
Please move the contents of this function into the cpp file too. I know there are others in the header, but they also need to be moved in their own PRs at some point.

2025-10-18 00:50 UTC, closed without merging