Add support for new modes in Tuya Climate
OttoWinter/esphomeyaml pull request #5159
Opened 2023-07-27 20:44 UTC by blacktirion

# What does this implement/fix?
Added support for Fan Only Mode, Dry Mode, Swing Mode and Fan Speed Control.

Also added/fixed support for entity states syncing with current operation mode.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>
https://github.com/esphome/feature-requests/issues/2329
**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
climate:
  - platform: tuya
    id: "tuya_climate"
    name: None
    switch_datapoint: 1
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    supports_heat: True
    supports_cool: True
    active_state_datapoint: 4
    active_state_heating_value: 1
    active_state_cooling_value: 0
    active_state_drying_value: 2
    active_state_fanonly_value: 3
    eco_datapoint: 8
    eco_temperature: 28
    sleep_datapoint: 101
    swing_vertical_datapoint: 106
    swing_horizontal_datapoint: 107
    fan_speed_datapoint: 5
    fan_speed_auto_value: 0
    fan_speed_low_value: 2
    fan_speed_middle_value: 3
    fan_speed_medium_value: 4
    fan_speed_high_value: 1

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [?] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).
   (Not Yet, Need to learn how to do this, probably finish tomorrow).

2023-07-28 16:37 UTC, blacktirion commented
This is now a breaking change. Added grouping to Preset, Swing Mode, Fan Speed and Active State.

2023-07-30 21:31 UTC, jesserockz requested changes

2023-07-30 21:31 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
> +    cv.has_at_most_one_key(CONF_STATE_DATAPOINT, CONF_COOLING_STATE_PIN),
```suggestion
    cv.has_at_most_one_key(CONF_ACTIVE_STATE, CONF_HEATING_STATE_PIN),
    cv.has_at_most_one_key(CONF_ACTIVE_STATE, CONF_COOLING_STATE_PIN),
```

2023-07-30 21:31 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
> +            cv.Optional(CONF_ACTIVE_STATE): ACTIVE_STATES,
Don't apply this suggestion as it requires more changes, but for removing config options, we switch them to `cv.invalid` do people get nicer errors when they try to compile and remove them in a later version.

```suggestion
            cv.Optional(CONF_ACTIVE_STATE): ACTIVE_STATES,
            cv.Optional("active_state_datapoint"): cv.invalid("'active_state_datapoint' has moved inside of the 'active_state' config block as 'datapoint'"),
            cv.Optional("active_state_heating_value"): cv.invalid(...),
            cv.Optional("active_state_cooling_value"): cv.invalid(...),
```

2023-07-30 21:31 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
> +        cv.Required(CONF_STATE_DATAPOINT): cv.uint8_t,
Lets simplify these as just `datapoint` in config since they are already inside the block that describes what it is for.

Same for eco and fan

```suggestion
        cv.Required(CONF_DATAPOINT): cv.uint8_t,
```

2023-07-30 21:31 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
> +        },
Same reason as above
```suggestion
        cv.Optional(CONF_ECO): {
            cv.Required(CONF_DATAPOINT): cv.uint8_t,
            cv.Optional(CONF_TEMPERATURE): cv.temperature,
        },
```

2023-07-31 13:40 UTC, blacktirion commented on esphome/components/tuya/climate/__init__.py
> +    cv.has_at_most_one_key(CONF_STATE_DATAPOINT, CONF_COOLING_STATE_PIN),
Is it OK to commit all these at one time with a new file version that has all the changes requested here? I've also resolved some issues I saw with certain code validation with COOLING_STATE_PIN and ACTIVE_STATE COOLING_VALUE, that the function wasn't working as expected. And I moved Sleep Datapoint under its own block in presets.

2023-07-31 21:49 UTC, blacktirion commented on esphome/components/tuya/climate/__init__.py
> +    cv.has_at_most_one_key(CONF_STATE_DATAPOINT, CONF_COOLING_STATE_PIN),
Resolved in latest commit.

2023-07-31 21:50 UTC, blacktirion commented
Requested changes reviewed and changes applied in single commit so that I could validate testing. Also put Sleep preset in its own config block to be consistent with other presets and fix logic for validate_cooling_values function to better align with existing documentation.

2023-07-31 22:16 UTC, jesserockz commented on esphome/components/tuya/climate/__init__.py
> +            cv.Optional("heating_state_datapoint"): cv.invalid(
This is not a datapoint (also for cooling, and the message itself
```suggestion
            cv.Optional("active_state_heating_value"): cv.invalid(
```

2023-07-31 22:22 UTC, blacktirion commented on esphome/components/tuya/climate/__init__.py
> +            cv.Optional("heating_state_datapoint"): cv.invalid(
Thanks for the oversight. Missed that one.

2023-08-01 23:14 UTC, jesserockz requested changes

2023-08-01 23:14 UTC, jesserockz commented on esphome/components/tuya/climate/tuya_climate.cpp
> +          swing_horizontal_ = false;
Member variables should always be prefixed with `this->` please.
```suggestion
          this->swing_vertical_ = false;
          this->swing_horizontal_ = false;
```

2023-08-02 01:29 UTC, blacktirion commented on esphome/components/tuya/climate/tuya_climate.cpp
> +          swing_horizontal_ = false;
changed. Thank you for this. Total oversight on my part.

2023-08-03 16:06 UTC, blacktirion commented
Not sure what's causing `CI / Run YAML test 4` (pull_request) to fail...

2023-08-07 22:05 UTC, jesserockz approved these changes

2023-12-21 16:04 UTC, PsychoRS commented
Would be nice to have this merged, I'm trying to make a Becasmart BAC-005ELW thermostat work with ESPHome and Libretiny (CB3S), but with the current tuya climate component I can't set fan speeds or fan_only modes.

2024-01-19 18:37 UTC, shakin89 commented
Is there any chance to have this pr merged?
I successfully flashed 5 devices, Beca BAC-002 CB3S based, and cannot set correctly fan speed during heating/cooling nor set fan_only mode. 
I would be sad to come back to the original firmware.

2024-01-19 19:21 UTC, moriahmorgan commented
> Is there any chance to have this pr merged? I successfully flashed 5 devices, Beca BAC-002 CB3S based, and cannot set correctly fan speed during heating/cooling nor set fan_only mode. I would be sad to come back to the original firmware.

I think it's just waiting on me to finish documentation. I have had a bit of a busy last few months health related and it keeps getting put on the back burner. I will attempt to finish this weekend, since @jesserockz is currently out for the rest of the week.

2024-01-19 21:45 UTC, shakin89 commented
> I think it's just waiting on me to finish documentation. I have had a bit of a busy last few months health related and it keeps getting put on the back burner. I will attempt to finish this weekend, since @jesserockz is currently out for the rest of the week.

I'm sorry, hope you are well now. Let me know if i can help writing the docs in some way. 
Thanks both for the great work done till now.

2024-01-19 22:31 UTC, moriahmorgan commented
@shakin89 Docs updated, just waiting for review, approval, then merge by @jesserockz when he has time, unless there are other issues to resolve. It has been some months since I looked at the code and I don't know if there's any issues right now with merging this.

2024-03-21 00:40 UTC, merged