Force heater off on setup
OttoWinter/esphomeyaml pull request #5161
Opened 2023-07-27 23:29 UTC by rufuswilson

# What does this implement/fix?

forces the heater to be turned off on setup

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes
https://github.com/esphome/issues/issues/2887

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-14 22:16 UTC, jesserockz reviewed
How would someone turn it back on?

2023-08-16 09:23 UTC, rufuswilson commented
This is a good question. From the different discussions, I understood it should have been turned off by default.

I was going to use the following as a temporary workaround to turn it off (I haven't tested it yet). Something similar but with the 0x306D code should turn it back on again. What do you think?
```
esphome:
  on_boot:
    - priority: 100
      then:
      - lambda: |-
          id(sht31d).write_command(0x3066);
```

2023-08-17 00:19 UTC, jesserockz commented
Well the best and most user friendly way would be to have:
```yaml

sensor:
  - platform: sht3xd
    heater_at_start: on/off
    
on_...:
  - sht3xd.heater_on:
  - sht3xd.heater_off:
```

2023-08-17 14:32 UTC, rufuswilson commented
That is a very good suggestion however it goes well beyond my current coding capabilities

2023-08-21 00:22 UTC, jesserockz commented
In that case, the actions we can leave for another time. But adding a config boolean for heater at startup should be done so a user can configure it properly and this does not become a breaking/unexpected change to all users already using it.

2023-08-21 20:04 UTC, jesserockz requested changes
c++ code looks good, just a few changes to the python side

2023-08-21 20:04 UTC, jesserockz commented on esphome/components/sht3xd/sensor.py
> +    )
This can go directly inside the schema, and also needs to define `CONF_HEATER_ENABLED = "heater_enabled"` higher up in the file
```suggestion
        },
        cv.Optional(CONF_HEATER_ENABLED, default=True): cv.boolean,
    )
```

2023-08-21 20:04 UTC, jesserockz commented on esphome/components/sht3xd/sensor.py
> +    cg.add(var.set_heater_enabled(config["heater_enabled"]))
```suggestion
    cg.add(var.set_heater_enabled(config[CONF_HEATER_ENABLED]))
```

2023-08-22 00:16 UTC, jesserockz approved these changes
Thanks for making the changes

2023-08-22 06:39 UTC, rufuswilson commented
Great! Just created a PR for the docs.
https://github.com/esphome/esphome-docs/pull/3149

2023-09-12 22:19 UTC, jesserockz approved these changes

2023-09-12 22:20 UTC, merged