Add KMeterISO component.
OttoWinter/esphomeyaml pull request #5170
Opened 2023-07-31 11:19 UTC by Rudd-O

# What does this implement/fix?

KMeterISO K-Type thermocouple support, pursuant to https://github.com/esphome/feature-requests/issues/2333 .

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2333

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a
  frequency: 100kHz

sensor:
- platform: kmeteriso
  temperature:
    name: Temperature
  internal_temperature:
    name: Internal temperature
    entity_category: diagnostic
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-07-31 12:07 UTC, Rudd-O commented
Folks, I need help with the tests and the clang format.  Not sure what is going on.  Please help me either with pointers or do feel free to add commits to the pull request.  Thanks so much in advance!

2023-08-07 01:35 UTC, jesserockz requested changes

2023-08-07 01:35 UTC, jesserockz commented on esphome/components/kmeteriso/kmeteriso.cpp
> +static const uint8_t KMETER_KMETER_ERROR_STATUS_REG = 0x20;
```suggestion
static const uint8_t KMETER_ERROR_STATUS_REG = 0x20;
```

2023-08-07 01:35 UTC, jesserockz commented on esphome/components/kmeteriso/kmeteriso.cpp
> +    int32_t temp = (read_buf[3] << 24) | (read_buf[2] << 16) | (read_buf[1] << 8) | read_buf[0];
```suggestion
    int32_t temp = encode_uint32(read_buf[3], read_buf[2], read_buf[1], read_buf[0]);
```

2023-08-07 01:35 UTC, jesserockz commented on esphome/components/kmeteriso/kmeteriso.cpp
> +    int32_t internal_temp = (read_buf[3] << 24) | (read_buf[2] << 16) | (read_buf[1] << 8) | read_buf[0];
```suggestion
    int32_t internal_temp = encode_uint32(read_buf[3], read_buf[2], read_buf[1], read_buf[0]);
```

2023-08-07 01:35 UTC, jesserockz commented on esphome/components/kmeteriso/kmeteriso.cpp
> +    if (this->temperature_sensor_ != nullptr)
This check should be before the `read_bytes` so it doesnt have to communicate if the sensor is not configured. Same for the below sensor.

2023-08-07 01:35 UTC, jesserockz commented on esphome/components/kmeteriso/kmeteriso.h
> +  void set_internal_temperature_sensor(sensor::Sensor *t) { internal_temperature_sensor_ = t; }
```suggestion
  void set_temperature_sensor(sensor::Sensor *t) { this->temperature_sensor_ = t; }
  void set_internal_temperature_sensor(sensor::Sensor *t) { this->internal_temperature_sensor_ = t; }
```

2023-08-07 01:35 UTC, jesserockz commented on esphome/components/kmeteriso/kmeteriso.h
> +  float read_temperature_(const uint8_t *data, int32_t *t_fine);
Not used?
```suggestion
```

2023-08-07 01:35 UTC, jesserockz commented on esphome/components/kmeteriso/sensor.py
> +    # changed by the end user of this component.
Users can set `update_interval: XXs` in yaml to change the timer (as you added in the test yaml)

We also prefer to default everything to 60s

```suggestion
    .extend(cv.polling_component_schema("60s"))
    .extend(i2c.i2c_device_schema(0x66))
```

2023-08-07 01:35 UTC, jesserockz commented on esphome/components/kmeteriso/sensor.py
> +        sens = await sensor.new_sensor(conf)
```suggestion
    if temperature_config := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_config)
```

2023-08-07 01:35 UTC, jesserockz commented on esphome/components/kmeteriso/sensor.py
> +        sens = await sensor.new_sensor(conf)
```suggestion
    if internal_temperature_config := config.get(CONF_INTERNAL_TEMPERATURE):
        sens = await sensor.new_sensor(internal_temperature_config)
```

2023-08-07 07:51 UTC, Rudd-O commented on esphome/components/kmeteriso/kmeteriso.cpp
> +    int32_t temp = (read_buf[3] << 24) | (read_buf[2] << 16) | (read_buf[1] << 8) | read_buf[0];
Wow.  Great knowledge and nice trick!  Thanks.

2023-08-07 07:57 UTC, Rudd-O commented
Thanks for the review.  All review suggestions were accepted.  PTAL @jesserockz .

2023-08-07 08:15 UTC, Rudd-O commented
![image](https://github.com/esphome/esphome/assets/346306/c35c5c00-3e98-4941-8074-729088c24b5b)

Strange.  No review comment was unaddressed.

2023-08-07 22:18 UTC, jesserockz submitted a review, later dismissed

2023-08-07 22:19 UTC, jesserockz commented
Thanks for making the changes

2023-08-07 22:51 UTC, Rudd-O commented
Despite the approval, I can't merge this — or maybe the UI will allow me to merge once the tests finish.  Will wait a little longer.

2023-08-07 23:18 UTC, jesserockz commented
No, you cannot merge, only people with write access can merge (like myself) which is done when both code and docs are approved

2023-08-07 23:19 UTC, Rudd-O commented
> No, you cannot merge, only people with write access can merge (like myself) which is done when both code and docs are approved

Cool.  Thanks!

2023-08-07 23:22 UTC, Rudd-O commented
Check your Discord privmsgs please @jesserockz .

2023-08-07 23:47 UTC, jesserockz approved these changes

2023-08-08 00:32 UTC, merged

2023-08-08 00:36 UTC, Rudd-O commented
Woohoo.  Thanks.