Pn532 non blocking scan
OttoWinter/esphomeyaml pull request #5191
Opened 2023-08-03 05:22 UTC by sharkydog

# What does this implement/fix?

Do not block loop() while waiting for tags to appear (command InListPassiveTarget).
Reading and writing NDEF is still blocking.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/4382

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-07 23:30 UTC, jesserockz requested changes

2023-08-07 23:30 UTC, jesserockz commented on esphome/components/pn532/pn532.cpp
> +  static int8_t ready = -1;
This prevents using multiple pn532 at the same time...
Which is not common, but there was a request for it so I added it

2023-08-09 11:14 UTC, sharkydog commented on esphome/components/pn532/pn532.cpp
> +  static int8_t ready = -1;
then move those as instance properties?

2023-08-09 11:36 UTC, sharkydog commented on esphome/components/pn532/pn532.cpp
> +  static int8_t ready = -1;
And maybe convert `int8_t ready` to enum?

2023-08-09 12:52 UTC, sharkydog commented on esphome/components/pn532/pn532.cpp
> +  static int8_t ready = -1;
Also should I add `yield()` at the end of the loop (if block==true) as in pn532_spi before this PR?

2023-10-02 15:44 UTC, github-k8n commented
Perfect, I tested the PR using 
external_components:
  - source: github://pr#5191
    components: [ pn532, pn532_i2c, pn532_spi ]

 and it pretty much solved the issue of pn532 blocking everything else all the time.
However i noticed that it still seems to have a delay (130ms) right after i scan a tag (but not at any other time), not sure if this is related here, just wanted to bring it up in case there is some edgecase that was forgotten:

[17:39:31][D][pn532:200]: Found new tag '0F-14-57-34'
[17:39:31][D][pn532:379]: Waiting to read next tag
[17:39:31][W][component:204]: Component pn532 took a long time for an operation (0.13 s).
[17:39:31][W][component:205]: Components should block for at most 20-30ms.

2023-10-02 18:00 UTC, sharkydog commented
Yep, reading is still blocking.
The whole component need to be reworked to fix this, probably along with the nfc component.

2023-10-03 03:55 UTC, sharkydog commented
Also, if interest in this PR "sparks", I won't have the time to update and test it to current dev in the next 3-4 weeks, so I will happily give up credit to someone who wants to speed things up.

2023-11-28 21:16 UTC, jesserockz approved these changes

2023-11-28 21:17 UTC, merged