Emmeti infrared climate support
OttoWinter/esphomeyaml pull request #5197
Opened 2023-08-04 16:19 UTC by E440QF

# What does this implement/fix?

This component adds support for Emmeti brand climate via infrared remote both in receiving and transmitting mode

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** not applicable

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```yaml
climate:
  - platform: emmeti
    name: AC
    receiver_id: rcvr

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-23 20:41 UTC, jesserockz requested changes

2023-10-23 20:41 UTC, jesserockz commented on esphome/components/emmeti/emmeti.cpp
> +  }*/
No commented code please.
```suggestion
```

2023-10-23 20:41 UTC, jesserockz commented on esphome/components/emmeti/emmeti.cpp
> +  return false;*/
Why is this commented?

2023-11-23 17:06 UTC, E440QF commented on esphome/components/emmeti/emmeti.cpp
> +  return false;*/
The packet sent by the remote is in a format like
bits0-34 20ms_pause bits35-66
Because of the long pause, esphome doesn't recognize it as a single big packet, so i don't decode the second half (see [previously commented code](https://github.com/esphome/esphome/pull/5197#discussion_r1369242831)) this is not a big deal as that half of the packet doesn't hold any data we REALLY need.
The caveat is: the checksum is in the last 4 bits, so without receiving it we obviously cant verify it
```suggestion

```

2024-03-11 22:30 UTC, jesserockz requested changes

2024-03-11 22:30 UTC, jesserockz commented on esphome/components/emmeti/emmeti.cpp
> +  add_(reverse_(val, len), len, data);
Please ensure all class members and member functions are prefixed with `this->` 
```suggestion
  this->add_(reverse_(val, len), len, data);
```

2024-03-11 22:30 UTC, jesserockz commented on esphome/components/emmeti/emmeti.cpp
> +  ESP_LOGD(TAG, "Checksum received: %X", checksum);
```suggestion
  ESP_LOGV(TAG, "Expected checksum: %X", expected);
  ESP_LOGV(TAG, "Checksum received: %X", checksum);
```

2024-03-11 22:30 UTC, jesserockz commented on esphome/components/emmeti/emmeti.h
> +using state = struct State {
This is unnecessary
```suggestion
struct State {
```

2024-03-13 00:39 UTC, jesserockz approved these changes, later dismissed

2024-03-13 01:15 UTC, jesserockz approved these changes

2024-03-13 01:16 UTC, merged