Fix AHT10 / AHT20 communication
OttoWinter/esphomeyaml pull request #5198
Opened 2023-08-04 16:21 UTC by flaminggoat

# What does this implement/fix?

Fixes communication with AHT20 modules & presumably AHT10 modules (though I don't have an AHT10 to test with). The implementation before this PR sends the messages shown in the scope capture, which include a byte of 0x00 after the device address, which is not what is specified in the [AHT10](https://kaimte.com/upload/attach/20200514/2786ec587a09412dcd95609fe91e00e4.pdf) or [AHT20 datasheet](https://cdn.sparkfun.com/assets/d/2/b/e/d/AHT20.pdf) and results in the AHT20 sending a NACK. So I am not sure how this code was working at all previously?
![image](https://github.com/esphome/esphome/assets/5025185/0d10117e-5210-4d95-8505-fd7c0b7b0631)
This PR corrects that, and allows communication with the module.

In addition the AHT20 datasheet indicates that the calibration/initialisation command is different for the AHT20 compared to the AHT10 module, so a variant config option has been added to allow selection of AHT10 or AHT20 modules. I found that my AHT20 module would not calibrate unless the command specified in the data sheet was used.

AHT20 Datasheet commands
![image](https://github.com/esphome/esphome/assets/5025185/bd63df66-7698-4e65-8a2c-240ccaea6201)

AHT10 Datasheet commands
![image](https://github.com/esphome/esphome/assets/5025185/4d1693f0-ee0f-42a4-946c-e4e560b88556)

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** possibly related https://github.com/esphome/issues/issues/3941

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> TODO

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
i2c:
  sda: 6
  scl: 7
  scan: false
  id: bus_a
  frequency: 200kHz
    
sensor:
  - platform: aht10
    variant: aht20
    i2c_id: bus_a
    id: aht_20
    address: 0x38
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 5s
```

## Checklist:
  - [x] The code change is tested and works locally.
![image](https://github.com/esphome/esphome/assets/5025185/3ba96dcc-532e-47b6-b1fb-c172ed350f06)
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-07 00:44 UTC, jesserockz requested changes

2023-08-07 00:44 UTC, jesserockz commented on esphome/components/aht10/aht10.h
> +  std::string variant_ = "aht10";
Please change this to be an `enum` similar to other components that have a `model` configuration

2023-08-07 21:47 UTC, flaminggoat commented on esphome/components/aht10/aht10.h
> +  std::string variant_ = "aht10";
Thanks for reviewing, I have changed to use an enum. I can add a PR for the documentation if this approach is okay.  My only concern is I don't understand how it could have been working before for the AHT10 with the `write_bytes(0,...` function. The updated code is inline with other AHT10 libraries such as the [adafruit one](https://github.com/adafruit/Adafruit_AHTX0/blob/d0aff01e79cc36ab0c0df01e2b17663fc99b0d02/Adafruit_AHTX0.cpp#L134C19-L134C19)

2023-08-07 22:42 UTC, jesserockz requested changes

2023-08-07 22:42 UTC, jesserockz commented on esphome/components/aht10/aht10.h
> +  AHT10Variant variant_ = AHT10Variant::AHT10;
```suggestion
  AHT10Variant variant_{};
```

2023-08-07 22:42 UTC, jesserockz commented on esphome/components/aht10/aht10.cpp
> +  if (this->write(calibrate_cmd, sizeof(AHT10_CALIBRATE_CMD)) != i2c::ERROR_OK) {
This probably should have a size const instead of using just the aht10 size.

2023-08-08 07:10 UTC, flaminggoat commented on esphome/components/aht10/aht10.cpp
> +  if (this->write(calibrate_cmd, sizeof(AHT10_CALIBRATE_CMD)) != i2c::ERROR_OK) {
```suggestion
  if (this->write(calibrate_cmd, sizeof(AHT20_CALIBRATE_CMD)) != i2c::ERROR_OK) {
```

2023-09-28 21:41 UTC, jesserockz commented on esphome/components/aht10/aht10.cpp
> +  if (this->write(calibrate_cmd, sizeof(AHT10_CALIBRATE_CMD)) != i2c::ERROR_OK) {
You missed the important part of what I said... 
Instead of using the size of aht10 or aht20, just define a new const that is the expected size to use for both

2023-09-28 21:43 UTC, jesserockz commented on esphome/components/aht10/aht10.cpp
> +  if (this->write(calibrate_cmd, sizeof(AHT20_CALIBRATE_CMD)) != i2c::ERROR_OK) {
At the top of this file add:
```c++
static const uint8_t CALIBRATE_CMD_LENGTH = 3;
```

and use that here

2023-09-28 21:43 UTC, SasaKaranovic commented
Tested the PR and can confirm it's working as expected with AHT20 sensor (AHT20 + BMP280 board) and ESP32 (ESP32 C3 Super Mini).

Configuration file used is below:
```
esphome:
  name: sk-test
  platform: ESP32
  board: lolin_c3_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "---redacted---"

ota:
  password: "---redacted---"

wifi:
  ssid: "---redacted---"
  password: "---redacted---"

web_server:
  port: 80

i2c:
  sda: 8
  scl: 9
  scan: true
  id: bus_a

sensor:
  - platform: bmp280
    temperature:
      id: 'bmp_temp'
      name: "Outside Temperature"
      oversampling: 16x
    pressure:
      id: 'bmp_pressure'
      name: "Outside Pressure"
    address: 0x77
    update_interval: 10s

  - platform: aht10
    variant: aht20
    i2c_id: bus_a
    id: aht_20
    address: 0x38
    temperature:
      id: 'aht_temp'
      name: "Living Room Temperature"
    humidity:
      id: 'aht_humid'
      name: "Living Room Humidity"
    update_interval: 10s

external_components:
  - source: github://pr#5198
    components: [ aht10 ]

```

2023-09-29 16:42 UTC, flaminggoat commented on esphome/components/aht10/aht10.cpp
> +  if (this->write(calibrate_cmd, sizeof(AHT10_CALIBRATE_CMD)) != i2c::ERROR_OK) {
done

2023-09-29 16:44 UTC, flaminggoat commented
As I guess there were no complaints with the general design of the change I have now added a PR for the documentation too https://github.com/esphome/esphome-docs/pull/3221

2023-11-27 19:45 UTC, heintjeput commented
This did solve an issue for me with the AHT21 sensor. Is there a way this can be merged into main?

2023-11-27 21:01 UTC, jesserockz approved these changes

2023-11-29 00:15 UTC, GyroW commented
I can also confirm this PR works for an "AHT30" sensor on a Wemos D1 mini using the aht20 variant. The aht30 also outputs a 7th byte containing a CRC according to the datasheet, but it doesn't seem to get in the way of the functionality.

2023-11-30 17:47 UTC, kristof-dragon commented
I can also confirm, that this PR solved the "Communication with AHT10 failed!" issue, where the I2C scan would detect the sensor, but it would not work.

I tested it on the latest v2023.11.6 ESPhome with
AHT20 + BMP280 sensor board on ESP32
AHT20 + ENS160 sensor board on ESP8266

2023-12-03 18:37 UTC, z3roq commented
Also can confirm that this fix "Communication with AHT10 failed!" issue for me with ESP32 C3 SuperMini using AHT20 + BMP280 cheap chinese board.

2023-12-12 23:28 UTC, merged