support illuminance for airthings wave plus device
OttoWinter/esphomeyaml pull request #5203
Opened 2023-08-05 16:05 UTC by MadMonkey87

# What does this implement/fix?

Extends the existing airthings wave plus integration to also support illuminance values

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [1935](https://github.com/esphome/feature-requests/issues/1935)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> coming soon

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```yaml
sensor:
  - platform: airthings_wave_plus
    name: wave plus
    ble_client_id: airthings01
    illuminance:
      name: "WavePlus ambient light"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-07 01:38 UTC, jesserockz requested changes

2023-08-07 01:38 UTC, jesserockz commented on esphome/components/airthings_wave_plus/airthings_wave_plus.cpp
> +  LOG_SENSOR("  ", "ILLUMINANCE", this->illuminance_sensor_);
```suggestion
  LOG_SENSOR("  ", "Illuminance", this->illuminance_sensor_);
```

2023-08-07 01:38 UTC, jesserockz approved these changes

2023-08-17 20:07 UTC, kpfleming commented
Yeesh... I should have added myself to CODEOWNERS for this one (and `mini`), as I was the one who most recently worked on the code.

2024-08-14 02:25 UTC, merged