download svg from web
OttoWinter/esphomeyaml pull request #5214
Opened 2023-08-08 07:32 UTC by landonr

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** 

related #3255 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 

esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
image:
  - id: launch_image
    file: https://raw.githubusercontent.com/landonr/homeThing/main/docs/homeThing%20logo.svg
    resize: 48x48
    type: TRANSPARENT_BINARY

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-08 07:32 UTC, landonr commented
@guillempages wassup

2023-08-20 12:48 UTC, guillempages reviewed
@landonr sorry, was AFK for a while.

I think your PR could be improved by reusing some of the MDI download code; left some comments.

2023-08-20 12:48 UTC, guillempages commented on esphome/components/image/__init__.py
> +CONF_FILETYPE = "filetype"
Are you using the `filetype` config option? I couldn't find it (but I might have overlooked that)

2023-08-20 12:48 UTC, guillempages commented on esphome/components/image/__init__.py
> +        file_name = match.group(1)
For consistency with the method's name (and the rest of the code), you might want to rename "file_name" to a single word filename (valid for all instances)
```suggestion
        filename = match.group(1)
```

2023-08-20 12:48 UTC, guillempages commented on esphome/components/image/__init__.py
> +    pattern = r"/([^/]+)$"
You can put two subgroups in the regex, and then parse filename and extension with a single call.
```suggestion
    pattern = r"/([^/]+)(\.([^./]+))?$"
```
`group(1)` would be filename (without extension) and `group(3)`  the extension (only if group(2) finds a match).
Then you could return a tuple instead of a single value, and avoid the next method.

2023-08-20 12:48 UTC, guillempages commented on esphome/components/image/__init__.py
> +    return None
See above; it can be merged into "get_filename_from_url"

2023-08-20 12:48 UTC, guillempages commented on esphome/components/image/__init__.py
> +        file_name = re.sub(r"%20", "", file_name)  # Replace %20 with empty string
"%20" is normally a white space; it might be better to replace it with "_" for readability?

2023-08-20 12:48 UTC, guillempages commented on esphome/components/image/__init__.py
> +    return base_dir / f"{image_id}.{filetype}"
Instead of a new method doing (mostly) the same, the already existing `_compute_local_icon_path` method above could be re-used. You could add a second parameter "extension" or similar to pass the filetype.

2023-08-20 12:48 UTC, guillempages commented on esphome/components/image/__init__.py
> +def download_image(value):
This method has a lot of common code with `download_mdi`, that could be reused.

Maybe put the common part into a new internal method, and just keep the URL/MDI name parsing part in the respective "public" download methods?

2023-08-20 12:48 UTC, guillempages commented on esphome/components/image/__init__.py
> +    if value.startswith("https"):
I'm also in favor of the "https only" Internet, but there are people still using non-encrypted http ;-) (Especially in local-only setups)
```suggestion
    if value.startswith("http://") or value.startswith("https://"):
```

2023-08-20 12:48 UTC, guillempages commented on esphome/components/image/__init__.py
> +        validate_cairosvg_installed(value)
cairosvg should only be needed for svg images, but the URL could be another kind of image (e.g. PNG). 
I'm not 100% sure how to handle this best though.

2023-08-20 12:48 UTC, guillempages commented on esphome/components/image/__init__.py
> +        # icon = match.group(1)
Any reason you left this in?
```suggestion
```

2023-08-20 12:48 UTC, guillempages commented on esphome/components/image/__init__.py
> +        req = requests.get(url, timeout=MDI_DOWNLOAD_TIMEOUT)
Since now the timeout is used as well for image download, you might want to rename the constant.
```suggestion
        req = requests.get(url, timeout=IMAGE_DOWNLOAD_TIMEOUT)
```

2023-08-20 13:01 UTC, guillempages commented on esphome/components/image/__init__.py
> +    return base_dir / f"{image_id}.{filetype}"
OTOH, it might be a good idea to use a hash instead of the actual filename (like the fonts are doing), to allow having similar images coming from different URLs (e.g. different weather icons, from separate providers; you might have `http://example.com/cool_icons/sunny.svg` and `https://example.org/big_colored_icon/sunny.svg`

2023-08-21 12:48 UTC, landonr commented
sweet thanks for the review! as I mentioned in #5254 i'll do those changes first so I can pull the duplicate code into here

2023-11-01 02:49 UTC, jesserockz requested changes

2023-11-01 02:49 UTC, jesserockz commented on esphome/external_files.py
> +    base_directory = Path(CORE.config_dir) / ".esphome" / domain
This should be using the data_dir, not the config_dir
```suggestion
    base_directory = Path(CORE.data_dir) / domain
```

2023-11-01 02:49 UTC, jesserockz commented on esphome/components/image/__init__.py
> +        validate_cairosvg_installed(value)
The `download_image` function should take care of this by checking the file type either from the webserver Content-Type, or by inspecting the file after its downloaded and then check if cairosvg is installed.

2023-11-01 02:49 UTC, jesserockz commented on esphome/components/image/__init__.py
> +def download_image(value):
There is a lot of overlap with download_mdi here, they should probably be combined

2023-11-01 02:49 UTC, jesserockz commented on esphome/external_files.py
> +    return file_base_name, file_extension
This needs to handle when the filename is not directly in the url

2023-11-01 13:15 UTC, landonr commented on esphome/external_files.py
> +    return file_base_name, file_extension
> jesserockz

i don't understand. Do you mean we should download the file first before checking for info?

2023-11-06 03:01 UTC, jesserockz commented on esphome/external_files.py
> +    return file_base_name, file_extension
I just want to make sure that URLs like `https://example.com/image` which could legitimately be an image download redirect work. Right now if someone was to use this url, the code only looks for a filename and extension based on the end of the url which is hacky at best...
Most download servers will give something like `Content-Disposition: attachment; filename="filename.jpg"` header which should be used for the local filename. This is the filename the browser would save a file as in such a case.

2023-11-06 13:01 UTC, landonr commented on esphome/external_files.py
> +    return file_base_name, file_extension
I'm not getting a Content-Disposition back from home assistant when i try to load a media play image like the following
> http://172.16.1.67:8123/api/media_player_proxy/media_player.beam?token=f6a40dc8c712ca8c1f3a599ee15286283f197bd696f5f59b0d3481185fe14c4e&cache=b311e6b1cf141036

what do you think about downloading the file and checking its type, and deleting it if it's not correct?

2023-11-20 02:24 UTC, jesserockz commented on esphome/external_files.py
> +    return file_base_name, file_extension
Ah yes this is a very good example of what I meant. So yes, the file should be downloaded in the validator and actual content type checked. 
Another option is to allow the user to specify the format/type of the image as another config param?

2023-11-22 02:15 UTC, landonr commented on esphome/external_files.py
> +    return file_base_name, file_extension
I have it working for everything but svg images hidden behind a redirect. I could add `type` as a config param but wouldn't I need to list out every supported image type?

2023-11-22 18:46 UTC, jesserockz requested changes
Tested and working with pngs so far.
One minor text change below so far and will take another look very soon

2023-11-22 18:46 UTC, jesserockz commented on esphome/external_files.py
> +                f"Could check if {url} has changed, please check if file exists "
```suggestion
                f"Could not check if {url} has changed, please check if file exists "
```

2023-11-22 18:46 UTC, jesserockz requested changes
Tested and working with pngs so far.
One minor text change below so far and will take another look very soon

2023-11-22 19:22 UTC, jesserockz commented on esphome/external_files.py
> +            f"Could check {url} info, check if file exists " f"({r.status_code}"
Another one here =)
```suggestion
            f"Could not check {url} info, check if file exists " f"({r.status_code}"
```

2023-11-22 20:14 UTC, jesserockz commented on esphome/external_files.py
> +    return file_base_name, file_extension
This is the `home.svg` download from the mdi repo
```py
>>> import mimetypes
>>> mimetypes.MimeTypes().guess_type("home.svg")
('image/svg+xml', None)
```

2023-11-22 20:59 UTC, landonr commented on esphome/external_files.py
> +    return file_base_name, file_extension
should I use mimetypes to guess the image types for all image types?

2023-11-23 04:43 UTC, jesserockz commented
@landonr I have pushed some kinda big changes that removed the content disposition and url filename guessing and just storing the file in any case with a hash of the url

The actual file type is determined when the code actually needs to read and decode the file just so it can follow a different path for svg types.

If you are happy/unhappy with the changes, please let me know =)

Jesse

2023-11-23 14:12 UTC, landonr commented
> @landonr I have pushed some kinda big changes that removed the content disposition and url filename guessing and just storing the file in any case with a hash of the url
> 
> The actual file type is determined when the code actually needs to read and decode the file just so it can follow a different path for svg types.
> 
> If you are happy/unhappy with the changes, please let me know =)
> 
> Jesse

great idea, I learned a lot from this PR! Thanks!

2023-11-23 14:14 UTC, landonr commented on esphome/components/image/__init__.py
> +    return base_dir / key
I think it'd like to use this for fonts also, if that works I think it should go into external_files

2023-11-23 18:30 UTC, jesserockz commented on esphome/components/image/__init__.py
> +    return base_dir / key
The same code is used for packages and external_components to clone the git repo into a local hashed. 

For now I am going to merge this PR. If you want to move the code to be reusable, please make another PR to not hold this feature back from being released =)

2023-11-23 18:30 UTC, jesserockz approved these changes

2023-11-23 19:10 UTC, merged

2023-11-24 00:46 UTC, alexd321 commented
Docs linked are wrong. Links to victron component

2023-11-24 07:47 UTC, fawick commented
Having seen this released just with 2023.11.04 just now, I wonder whether the web source images are fetched only once in the firmware build stage or whether the ESPHome-running device actually downloads them (possibly regularly) at runtime. 

I have a use case for the latter, which I currently handle with pr#4710.

2023-11-24 14:42 UTC, landonr commented
This is for images downloaded once on build. Looking forward to #4710

2023-11-24 16:31 UTC, fawick commented
Thank you for clarifying!