Add the WeiKai SPI/I2C UART/IO Expander components to esphome
OttoWinter/esphomeyaml pull request #5218
Opened 2023-08-08 14:14 UTC by DrCoolzic

# What does this implement/fix?

Add 8 new components from the WeiKai family of components:
[WK2168-IQPG](https://jlcpcb.com/partdetail/WEIKAI-WK2168IQPG/C401041) [WK2132-ISSG](https://jlcpcb.com/partdetail/Weikai-WK2132ISSG/C401039) [WK2124-ISSG](https://jlcpcb.com/partdetail/Weikai-WK2124ISSG/C86332) [WK2204-IQNG](https://jlcpcb.com/partdetail/Weikai-WK2204IQNG/C401040) [WK2212-IQNG](https://jlcpcb.com/partdetail/Weikai-WK2212IQNG/C2987671)

These components allow to connect up to 4 UART devices and IO pins from an SPI or I²C bus

There are 11 components added to the ESPHome library:
- The weikai: component that contains all the code for the base functionality
- the weikai_i2c: provides the interface using the i2c bus
- the weikai_spi:  provides the interface using the spi bus
- The wk2132_spi: that contains the spi related classes for the wk2132
- The wk2132_i2c: that contains the i2c related classes for the wk2132
- The wk2168_spi: that contains the spi related classes for the wk2168
- The wk2168_i2c: that contains the i2c related classes for the wk2132
- The wk2204_spi: that contains the spi related classes for the wk2204
- The wk2204_i2c: that contains the i2c related classes for the wk2204
- The wk2212_spi: that contains the spi related classes for the wk2212
- The wk2212_i2c: that contains the i2c related classes for the wk2212

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3113

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml for the wk2132_i2c: component
wk2132_i2c:
  - id: wk2132_0
    address: 0x70
    i2c_id: i2c_bus
    uart:
      - uart_id: uart_id_0
        channel: 0
        baud_rate: 115200
        stop_bits: 1
        parity: none
      - uart_id: uart_id_1
        channel: 1
        baud_rate: 19200
```

```yaml
# Example config.yaml for the wk2168_spi component
wk2168_spi:
  - id: bridge_0
    cs_pin: 5
    data_rate: 4MHz
    crystal: 11059200
    test_mode: 1
    uart:
      - uart_id: uart_id0
        channel: 0
        baud_rate: 115200
        stop_bits: 1
        parity: none
      - uart_id: uart_id1
        channel: 1
        baud_rate: 115200
      - uart_id: uart_id2
        channel: 2
        baud_rate: 115200
# individual binary_sensor inputs
binary_sensor:
  - platform: gpio
    name: "b0 p3"
    pin:
      wk2168_spi: bridge_0
      number: 0
  - platform: gpio
    name: "b0 p1"
    pin:
      wk2168_spi: bridge_0
      number: 1
      mode:
        input: true
      inverted: true
# Individual binary outputs
switch:
  - platform: gpio
    name: "b0 p2"
    pin:
      wk2168_spi: bridge_0
      number: 2
      mode:
        output: true
  - platform: gpio
    name: "b0 p3"
    pin:
      wk2168_spi: bridge_0
      number: 3
      mode:
        output: true
      inverted: true
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-09 11:13 UTC, SeByDocKy commented
That's a major addition to ESPhome!!!!!!! Bravo....

2023-08-24 15:26 UTC, kahrendt reviewed
Nice work on the component! I have it tested and working with a DFRobot module.

I have added a few recommendations mainly based off changes that I have been requested to make for my own PRs. For a couple of them, I wrote if I was unsure about them in terms of the project's bigger picture, so I may be off base on those.

It would be great to get this working without needing a dummy UART device, but I'm not sure how to go about that!

2023-08-24 15:26 UTC, kahrendt commented on esphome/components/wk2132/__init__.py
> +                    cv.Optional(CONF_CHANNEL): cv.int_range(min=0, max=1),
Either provide a default for this optional config option or change it to required. Otherwise, it will have issues in the ``to_code`` function if it isn't defined.

2023-08-24 15:26 UTC, kahrendt commented on esphome/components/wk2132/__init__.py
> +            cv.Optional(CONF_CRYSTAL): cv.int_,
Provide a default value of 14745600 here instead of doing so in the ``post_validate`` function

2023-08-24 15:26 UTC, kahrendt commented on esphome/components/wk2132/wk2132.cpp
> +  address_ = i2c_address(base_address_, channel, 0);  // update the i2c address
In the [ESPHome Style Guidelines](https://esphome.io/guides/contributing.html#codebase-standards), they want all class members and member functions to be prefixed with ``this->``, so here it should be ``this->base_address_``. This change needs to happen throughout your code for several variables and functions.

2023-08-24 15:26 UTC, kahrendt commented on esphome/components/wk2132/wk2132.h
> +  uint32_t crystal_{14745600L};              ///< crystal default value;
Since the Python codegen will always set a crystal value, you don't need to specify it here:
``uint32_t crystal_{}; ``

2023-08-24 15:26 UTC, kahrendt commented on esphome/components/wk2132/wk2132.cpp
> +  if (this->is_failed()) {
Is this possible for your component? You don't have any ``this->mark_failed()`` calls.

2023-08-24 15:26 UTC, kahrendt commented on esphome/components/wk2132/wk2132.h
> +  bool initialized_{false};                  ///< true when initialization is finished
I'm not sure if this would work, but would the built-in ``this->is_ready()`` function work here instead of keeping track of it yourself? I can't find any components that use that function as an example, so I may be way off base here.

2023-08-24 15:26 UTC, kahrendt commented on esphome/components/wk2132/wk2132.cpp
> +  initialized_ = true;  // ths is the end of the initialization for our component
Would this work if moved to the end of the ``setup()`` function? That's where the initialization occurs, this function is just logging basic info about the component. I'm not sure if there is a project guideline that specifies if doing more than logging in it is ok.

2023-08-24 15:26 UTC, kahrendt commented on esphome/components/wk2132/wk2132.h
> +  std::bitset<8> test_mode_{0};              ///< test mode 0 -> no tests
The Python codgen should always set this as well, so you do not need to specify a default value here either.

2023-08-24 16:58 UTC, DrCoolzic commented on esphome/components/wk2132/__init__.py
> +                    cv.Optional(CONF_CHANNEL): cv.int_range(min=0, max=1),
Oops dont know what happen. Somehow the correct code for post_validate() got lost at some point ....
The **correct ** post_validate() method take care of that

2023-08-24 17:08 UTC, DrCoolzic commented on esphome/components/wk2132/__init__.py
> +            cv.Optional(CONF_CRYSTAL): cv.int_,
ok make sense

2023-08-24 17:48 UTC, DrCoolzic commented on esphome/components/wk2132/wk2132.cpp
> +  address_ = i2c_address(base_address_, channel, 0);  // update the i2c address
I have added tons of this-> !!!
I would not garantee correction at 100% but should be close :)

2023-08-24 17:50 UTC, DrCoolzic commented on esphome/components/wk2132/wk2132.h
> +  uint32_t crystal_{14745600L};              ///< crystal default value;
done

2023-08-24 17:53 UTC, DrCoolzic commented on esphome/components/wk2132/wk2132.cpp
> +  if (this->is_failed()) {
Originally I wanted to add two components, this one and the sc16is752 component. As this is my first test with
ESPHome I decided to start with one only!
So I borowed lot of code from one to the other but during the copy/paste some part did not moved correctly.
I just put back the intended code and indeed I now do call mark_failed().
Thanks for finding the problem.

2023-08-24 17:56 UTC, DrCoolzic commented on esphome/components/wk2132/wk2132.h
> +  bool initialized_{false};                  ///< true when initialization is finished
I was not aware of this function. I will look at it. Might be what I need

2023-08-24 17:58 UTC, DrCoolzic commented on esphome/components/wk2132/wk2132.h
> +  std::bitset<8> test_mode_{0};              ///< test mode 0 -> no tests
yes removed

2023-08-24 18:49 UTC, DrCoolzic commented on esphome/components/wk2132/wk2132.cpp
> +  if (this->is_failed()) {
Ok. Now I remember why the mark_failed() was gone! I am trying to test the communication to the wk2132 way to early. Most probably the I²C bus is not yet ready and the test fail.
Fortunately I found the problem running regression tests!

So I removed the test as it is useless at this place and I removed the is_failed
Still testing and I will submit

2023-08-24 18:51 UTC, DrCoolzic commented on esphome/components/wk2132/wk2132.h
> +  bool initialized_{false};                  ///< true when initialization is finished
I tested using the is_ready() function and works fine. So I will remove the initialized_ flag

2023-08-24 18:53 UTC, DrCoolzic commented on esphome/components/wk2132/wk2132.cpp
> +  initialized_ = true;  // ths is the end of the initialization for our component
again seems to work ok replacing with is_ready().
Anyway not critical as only used in test mode

2023-08-24 19:45 UTC, DrCoolzic commented
> Nice work on the component! I have it tested and working with a DFRobot module.
> 
Thanks good to know its working for you

> It would be great to get this working without needing a dummy UART device, but I'm not sure how to go about that!
From what I understand it has to be solved in UART component. Jessie is aware of the problem, but I do not think anybody
is working on the problem?

2023-08-24 20:13 UTC, SeByDocKy commented
> Nice work on the component! I have it tested and working with a DFRobot module.
> 
> I have added a few recommendations mainly based off changes that I have been requested to make for my own PRs. For a couple of them, I wrote if I was unsure about them in terms of the project's bigger picture, so I may be off base on those.
> 
> It would be great to get this working without needing a dummy UART device, but I'm not sure how to go about that!

Which components you tested with ?

2023-08-24 21:45 UTC, kahrendt commented
I've retested the updated code, and everything is still working. I hope those changes help get this PR accepted a bit faster! This will be a useful component for some of my future projects.

SeByDocKy, I am testing it with the [dfrobot mmwave component](https://github.com/esphome/esphome/pull/4203). I haven't explored that PR too deeply, but the WK2132 is reading the motion sensor state just fine out of the box. Here is the basic config for it:

```

external_components:
  - source: github://pr#5218
    components: [ wk2132 ]    
  - source: github://pr#4203
    components: [ dfrobot_mmwave_radar ]

wk2132:
  - id: wk2132_0
    address: 0x70
    uart:
      - uart_id: uart_id_wk2132_0_0
        channel: 0 
        baud_rate: 115200
        stop_bits: 1
        parity: none

uart:
  id: dummy
  tx_pin: 3
  baud_rate: 9600

binary_sensor:
  - platform: dfrobot_mmwave_radar
    name: "MMWave Motion"

```

2023-08-25 08:24 UTC, DrCoolzic commented
> I've retested the updated code, and everything is still working. I hope those changes help get this PR accepted a bit faster! This will be a useful component for some of my future projects.

Thank you for your time and help. This is my first submission so I'm not too familiar with the process.
It's a shame that component design for ESPHome isn't better documented. You have to guess at a lot of things to get the result, but the more comfortable you get the more you appreciate the architecture...
Thanks again for your help, and let's hope the PR validation goes smoothly.

2023-08-25 14:00 UTC, SeByDocKy commented
Ok I did the first testing with a sds011 sensor. Got a good and a bad news...

i) The good one.... With the Wk2132, i can collect both sensor informations (pm2.5 & pm10)
ii) The bad one... If I am not pluging the wk2132 into the I2C bus, got a bunch of I2C error msgs
```[15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
[15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
[15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
[15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
[15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
[15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
[15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
[15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
[15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
````

I guess during the setup of the conponents, no check is performed if it's plugged .... must be added...

Now I will check a more complex serial component like a BMS

2023-08-25 14:35 UTC, DrCoolzic commented
> The bad new... If I am not pluging the wk2132 into the I2C bus, got a bunch of I2C error msgs
> 
> ```
> [15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
> ```

I am not sure to understand what you are asking for? If you declare a component and if the component is not connected it is normal that the I²C bus returns error code 2. This is the expected behaviour to indicate your hardware is faulty and telling you where is the error.
The only thing I can do is to report the same error and then invalidate all calls to the wk2132. In which case you will need  to restart the ESP if you connect the component latter.

2023-08-25 14:57 UTC, SeByDocKy commented
> > The bad new... If I am not pluging the wk2132 into the I2C bus, got a bunch of I2C error msgs
> > ```
> > [15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
> > ```
> 
> I am not sure to understand what you are asking for? If you declare a component and if the component is not connected it is normal that the I²C bus returns error code 2. This is the expected behaviour to indicate your hardware is faulty and telling you where is the error. The only thing I can do is to report the same error and then invalidate all calls to the wk2132. In which case you will need to restart the ESP if you connect the component latter.

the "absence" detection must be done during the setup in order to have multiple error msg during the main update().... Maybe a working around would be to change the ESPLOG verbosity level ....

2023-08-25 15:15 UTC, DrCoolzic commented
> > > The bad new... If I am not pluging the wk2132 into the I2C bus, got a bunch of I2C error msgs
> > > ```
> > > [15:44:18][E][wk2132:083]: read_wk2132_register_(@70 FSR, ch=0 b=00 [00000000], len=1): I2C code 2
> > > ```
> > 
> > 
> > I am not sure to understand what you are asking for? If you declare a component and if the component is not connected it is normal that the I²C bus returns error code 2. This is the expected behaviour to indicate your hardware is faulty and telling you where is the error. The only thing I can do is to report the same error and then invalidate all calls to the wk2132. In which case you will need to restart the ESP if you connect the component latter.
> 
> the "absence" detection must be done during the setup in order to have multiple error msg during the main update().... Maybe a working around would be to change the ESPLOG verbosity level ....

Once again, I don't understand why it's a problem to indicate that the module is not correctly connected? The debug messages were created to help users locate a fault.

I don't suppose you're going to make a board where you can add or remove components during operation?
As far as I know, ESPHome's architecture was not designed for dynamic component configuration.

2023-08-26 12:29 UTC, SeByDocKy commented
Ok just tested with a JKBMS and unfortunaly no data are received :( (like bandid17)
Here is my yaml
```substitutions:
  updates: 5s
  name: air_control

esphome:
  name: ${name}
  
esp32:
  board: esp32dev
  framework:
    type: arduino
    version: 2.0.11 #2.0.5 2.0.9
    platform_version: 6.3.2 #4.4.0 6.2.0
 
external_components:
  - source: github://pr#5218
    components: [wk2132]
  - source: github://syssi/esphome-jk-bms@main
    refresh: 0s  

wifi:
  ssid: !secret esphome_ssid
  password: !secret esphome_password

# Enable logging
logger:
  #baud_rate: 0
  level: very_verbose
# Enable Home Assistant API
api:

ota:

switch:
  - platform: restart
    name: restart_${name}

# font:
# - file: 'dejavusans.ttf'
#   id: font1
#   size: 8

uart:
  tx_pin: GPIO17
#  rx_pin: GPIO16
  baud_rate: 115200 #9600
  id: ubus1

i2c:
- sda: GPIO25
  scl: GPIO26
  id: i2c_bus1
  
wk2132:
  - address: 0x10
    id: uart_bridge0
    i2c_id: i2c_bus1
    uart:
      - uart_id: uart_00
        channel: 0
        baud_rate: 9600
        #parity: even
      - uart_id: uart_01
        channel: 1
        baud_rate: 115200

jk_modbus:
  - id: jkbms_0
    uart_id: uart_01
jk_bms:
  - id: bms_0
    jk_modbus_id: jkbms_0
       
sensor:

- platform: jk_bms
  jk_bms_id: bms_0
  min_cell_voltage:
    name: ${name}_min_cell_voltage
  max_cell_voltage:
    name: ${name}_max_cell_voltage
  min_voltage_cell:
    name: ${name}_min_voltage_cell
  max_voltage_cell:
    name: ${name}_max_voltage_cell  
  delta_cell_voltage:
    name: ${name}_delta_cell_voltage
  average_cell_voltage:
    name: ${name}_average_cell_voltage 
  cell_voltage_1:
    name: ${name}_cell_voltage_1
  cell_voltage_2:
    name: ${name}_cell_voltage_2
  cell_voltage_3:
    name: ${name}_cell_voltage_3
  cell_voltage_4:
    name: ${name}_cell_voltage_4
```

2023-08-26 14:25 UTC, SeByDocKy commented
Concerning the sds011, even if I can collect the two sensor data, I noticed I got this warning msg

```[16:23:35][D][sds011:169]: Got PM2.5 Concentration: 11.2 µg/m³, PM10.0 Concentration: 16.5 µg/m³
[16:23:35][D][sensor:094]: 'air_control_2_5µm_concentration': Sending state 11.20000 µg/m³ with 1 decimals of accuracy
[16:23:35][D][sensor:094]: 'air_control_10_0µm_concentration': Sending state 16.50000 µg/m³ with 1 decimals of accuracy
[16:23:35][W][component:204]: Component sds011.sensor took a long time for an operation (0.07 s).
[16:23:35][W][component:205]: Components should block for at most 20-30ms.```

2023-08-26 14:58 UTC, DrCoolzic commented
@SeByDocKy 
I looked at the log file and I see that the wk2132 is asked to send 21 characters starting with 0x4E and after that is listening but not receiving anything ? 
Could that be an hardware problem? Can you connect a logic analyzer? Typically you should see activity on the I²C bus prior to reading or writing character ...
Can you put the loger at debug level and add the undocummented line in your yaml
```
...
wk2132:
  - address: 0x10
    test_mode: 1
    id: uart_bridge0
    i2c_id: i2c_bus1
...
```
Nothing else I can think about

2023-08-26 15:04 UTC, DrCoolzic commented
> Concerning the sds011, even if I can collect the two sensor data, I noticed I got this warning msg
> 
> ```
> [16:23:35][D][sensor:094]: 'air_control_2_5µm_concentration': Sending state 11.20000 µg/m³ with 1 decimals of accuracy
> [16:23:35][D][sensor:094]: 'air_control_10_0µm_concentration': Sending state 16.50000 µg/m³ with 1 decimals of accuracy
> [16:23:35][W][component:204]: Component sds011.sensor took a long time for an operation (0.07 s).
> [16:23:35][W][component:205]: Components should block for at most 20-30ms.```
> ```

sorry I know nothing about the sds011.
Actually a lot of components block the loop more than 30 ms!

2023-08-26 15:24 UTC, DrCoolzic commented
FYI here is how to interpret the wk2132 address
```
+----+----+----+----+----+----+----+----+
|  0 | A1 | A0 |  1 |  0 | C1 | C0 |  F |
+----+----+----+----+----+----+----+----+
where :
A1 A0 are the two switches
C1 C0 is the channel number (0-4)
F normal(0) or FIFO(1)
```

for example with a0 a1 = 0 0
register ch 0 = 0x10
register ch 1 = 0x12
fifo ch0 = 0x11
fifo ch1 = 0x13

note that acessing directly the fifo is very unusual with i²c component

But if you look on the bus remember that the R/W bit is added at the end.  So it becomes:
```
+----+----+----+----+----+----+----+----+
| A1 | A0 |  1 |  0 | C1 | C0 |  F | WR |
+----+----+----+----+----+----+----+----+
```
![image](https://github.com/esphome/esphome/assets/6078364/80f38463-c233-4b5f-ae4f-9dfc893e62de)

2023-08-30 20:22 UTC, kahrendt commented
I've been testing this a bit more, and I am running into issues using the LD2410 component that was updated in the last release. It is trying to call some validation functions that check the UART interface is configured correctly, and this PR doesn't have them. This setup will throw errors:

```
wk2132:
  - id: wk2132_0
    address: 0x70
    uart:
      - uart_id: uart_mmwave
        channel: 0 
        baud_rate: 256000
        stop_bits: 1
        parity: none

uart:
  id: dummy
  tx_pin: 3
  rx_pin: 32
  baud_rate: 9600

ld2410:
  uart_id: uart_mmwave

```

In the base UART component  [``__init__.py``](https://github.com/esphome/esphome/blob/dev/esphome/components/uart/__init__.py), there are some validate functions starting around line 243. I think those will need to be added to this PR to avoid the compilation errors. There may be a better way than duplicating them in your own ``__init__.py``, but I am unaware of it.

2023-08-31 09:15 UTC, DrCoolzic commented
> I've been testing this a bit more, and I am running into issues using the LD2410 component that was updated in the last release. It is trying to call some validation functions that check the UART interface is configured correctly, and this PR doesn't have them. This setup will throw errors:

I already had the exact same problem using the PMSX003. It is also complaining about a RX pin that does not exist during some sensor validation. 
This seems to be some problem in the UART validation again. I already started to look in the UART validation functions to understand why we need to declare a “dummy” UART when using the `AUTO_LOAD = ["uart"]` but my knowledge of Python is not sufficient to follow this code … and it is the same to fix it for the problem you describe.
Therefore, as I am not the cause of the problem, I will probably leave the resolution of the problem to the UART team. I intend to create a bug report for the problem of the need to add a dummy UART.

2023-09-01 11:02 UTC, DrCoolzic commented
@kahrendt I have made major changes to the code (added ring buffer) for performance improvement in specific conditions.
The code has been tested but I would appreciate if you can rerun some of your tests to check that nothing has been broken.
Thanks

2023-09-01 21:25 UTC, kahrendt commented
> @kahrendt I have made major changes to the code (added ring buffer) for performance improvement in specific conditions. The code has been tested but I would appreciate if you can rerun some of your tests to check that nothing has been broken. Thanks

I tested your PR again with the dfrobot mmwave component (I linked to the PR for the component earlier), and it is still working. It also did drastically improve performance, nice work! The max loop time (obtained via the debug component) was around 45 ms with the old code, and now it is averaging around 22 ms for the max loop time.

That is the only easily accessible UART device I have to test with at the moment (besides the ld2410 that I discussed in my last comment). I'll look through your new code and see if there are any changes that I can recommend in the next day or two.

2023-09-03 08:35 UTC, DrCoolzic commented
> I tested your PR again with the dfrobot mmwave component (I linked to the PR for the component earlier), and it is still working. It also did drastically improve performance, nice work! The max loop time (obtained via the debug component) was around 45 ms with the old code, and now it is averaging around 22 ms for the max loop time.

Thanks for your feedback. I have changed the code again! Nothing major but I would like to propose several UART bridges. Probably sc16is750, sc16is752 from i2c and spi to uarts (I already have code working for i2c version). In order not to duplicate the UART code many times (prone to errors) I have created an intermediate class that I called GenericUART. It implements the factory method from the UARTComponent class and leaves the HW details of communication with the device registers to the derived class. I also added a ring buffer for the writing to the UART. This is probably less critical because usually for writing people use the write_array() function and the frames are usually relatively small.

FYI: This is unfortunate that all the code I reviewed are using a while loop to read the received bytes **one by one** but hopefully with the ring buffer the problem should be solved. Before I added the ring buffer the jk-bms integration was not working for performance reason (reading about 300 bytes one by one). I have modified this loop to use read_array() and that solved the problem. But I realized I could not ask to all the implementations that use read() to be modified…

2023-12-19 02:12 UTC, jesserockz submitted a review, later dismissed
LGTM, pending #5139 to not fail config validation because of auto loading uart

2023-12-19 02:49 UTC, jesserockz approved these changes, later dismissed

2023-12-19 09:02 UTC, DrCoolzic commented
Hello it seems that you are looking at my component WK2132. It also looks like you are removing the constraint of having to specify a UART when doing a UART auto_load.
There is another problem that has been reported to me by two of the users of my WK2132 component. It seems that when certain components (but obviously not all)  use the WK2132, the configuration validation crashes esphome. For example:
```
esphome:
  name: wk2132-i2c-arduino
esp32:
  board: esp32dev
  framework:
    type: arduino
external_components:
  - source: github://pr#5932
    components: [uart]
    refresh: 0s
  - source: github://pr#5947
    components: [i2c]
    refresh: 0s
  - source: github://pr#5218
    components: [wk2132_i2c]
    refresh: 0s

logger:
  level: debug

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_i2c
  frequency: 600kHz

uart:
  id: dummy
  tx_pin: 3
  baud_rate: 9600

wk2132_i2c:
  - id: bridge_0
    address: 0x70
    test_mode: 1
    uart:
      - uart_id: uart_id0
        channel: 0
        baud_rate: 115200
        stop_bits: 1
        parity: none
      - uart_id: uart_id1
        channel: 1
        baud_rate: 921600

# bug with these components

ld2410:
  uart_id: uart_id0

# sensor:
#   - platform: pmsx003
#     uart_id: uart_id0
#     type: PMSX003
#     pm_1_0:
#       name: "Particulate Matter <1.0µm Concentration"

```
Generates the following messages during compilation:
```
PS U:\__DEV__\VSCode\ESPHome\esphome> esphome run .\config\wk2132_i2c-arduino.yaml
INFO ESPHome 2024.1.0-dev
INFO Reading configuration .\config\wk2132_i2c-arduino.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/5932/head
INFO Updating https://github.com/esphome/esphome.git@pull/5947/head
INFO Updating https://github.com/esphome/esphome.git@pull/5218/head
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python311\Scripts\esphome.exe\__main__.py", line 7, in <module>
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\__main__.py", line 1041, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\__main__.py", line 1019, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 1046, in read_config
    res = load_config(command_line_substitutions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 900, in load_config
    return _load_config(command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 888, in _load_config
    result = validate_config(config, command_line_substitutions)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 816, in validate_config
    result.run_validation_steps()
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 132, in run_validation_steps
    task.step.run(self)
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 697, in run
    self.comp.final_validate_schema(conf)
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\voluptuous_schema.py", line 34, in __call__
    res = super().__call__(data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python311\Lib\site-packages\voluptuous\schema_builder.py", line 287, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python311\Lib\site-packages\voluptuous\schema_builder.py", line 611, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\voluptuous_schema.py", line 148, in validate_mapping
    cval = cvalue(key_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python311\Lib\site-packages\voluptuous\schema_builder.py", line 834, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\final_validate.py", line 56, in validator
    return schema(declaration_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\voluptuous_schema.py", line 34, in __call__
    res = super().__call__(data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python311\Lib\site-packages\voluptuous\schema_builder.py", line 287, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python311\Lib\site-packages\voluptuous\schema_builder.py", line 834, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\config\.esphome\external_components\dfddce82\esphome\components\uart\__init__.py", line 301, in validate_hub
    uart_id = hub_config[CONF_ID]
              ~~~~~~~~~~^^^^^^^^^
KeyError: 'id'
```
I don't think the problem is coming from my component directly and I can't really figure out what's causing it. 
At one point, the error message was a little more specific and I seem to remember that it mentioned a problem indicating that the GPIO pins (probably rx tx) had the wrong type or something like that. Which makes no sense for my component as I don't use any GPIO pins. But now the error message doesn't seem to mention this problem anymore and is much more encryptic. I really don't know what it's due to. 

If you could see if this is related to my WK2132 component or if it's related to the UART validation that would be cool because I do not yet feel confortable looking/debugging the Python code

2023-12-19 09:08 UTC, DrCoolzic commented
I am not familiar with the acceptance process and how far you are in the review, but before closing the PR give me a chance to remove some workaround, I have put in place to circumvent the bugs found. 
I'm also going to work on updating the component documentation, removing all the mentioned limitations that apparently won't be there when the component and all the fixed bugs are released.

2023-12-19 16:33 UTC, DrCoolzic commented
I have tested the modification you did to __init__.py of UART component (adding `MULTI_CONF_NO_DEFAULT = True`) and unless I am doing something wrong that does not seems to fix the problem I still get
```
PS U:\__DEV__\VSCode\ESPHome\esphome> esphome run .\config\wk2132_i2c-arduino.yaml
INFO ESPHome 2024.1.0-dev
INFO Reading configuration .\config\wk2132_i2c-arduino.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/5932/head
INFO Updating https://github.com/esphome/esphome.git@pull/5947/head
Failed config

uart: None

  'baud_rate' is a required option for [0].
  []
PS U:\__DEV__\VSCode\ESPHome\esphome> 
```

2023-12-19 23:49 UTC, jesserockz commented
The required PR #5139 is not yet merged, I am waiting on a rebase from the author as I cannot do it myself due to limitations in GitHub.

I can see why the crash is happening above and I will look to fix it after merging this PR as to not hold it up. It is due to the `uart.final_validate` function that some components use.

2024-01-04 15:39 UTC, DrCoolzic commented
I took the opportunity that the PR is still open to squeeze **the SPI version** of the code. So now it handles the WK2132 connected to the ESP either by a **SPI** or an **I²C** bus.
For that matter the code has been considerably modified an organized differently. I took example on the RC522 component for the organization. I now have three components the wk2132 component that takes care of the UART transmission logic, the wk2132_spi that takes care of the SPI communication and the wk2132_i2c that takes care of the I²C communication. 
The simplified class diagram for the SPI version looks like this
 
![image](https://github.com/esphome/esphome/assets/6078364/28378cb6-0142-4982-829b-3373948d2dfc)

### The status is the following:
As it seems like pr#5932 and pr#5947 are now integrated in current esphome, this allow to compile the components with the ESP-IDF framework and this removes the 256 bytes error (at least for the ESP-IDF as the Arduino framework is still broken in Wire.h).
Therefore, the components (wk2132_spi, wk2132_i2c) have tested and works with 256 bytes buffer for the ESP-IDF framework and with 255 bytes buffer for the Arduino framework. This is done automatically and transparently for the user.
The i2c version has been tested very extensively by SeByDocky and Bandit-17 for several months.
### Two problems are still open:
•	To work the configuration file still need to declare a “dummy UART”
•	Some components like ld2410, sds011 and others fails on UART extra test

2024-01-09 14:30 UTC, DrCoolzic commented
I have renamed and updated `wk2132 `‘base’ component to `wk_base `in prevision of the upcoming new components of the Weikai family. The wk_base component will be used by the wk2132_i2c, wk2132_spi, wk2168_i2c, wk2168_spi components and potentially by the wk2204 and wk2124 if necessary. For that matter the registers of WKxxxx chips have been updated to cover the current family member and the base classes have been renamed to more “neutral” names. 
But overall, it is more a cosmetic modification as the code has not changed much.

2024-02-28 22:48 UTC, jesserockz requested changes

2024-02-28 22:48 UTC, jesserockz commented on esphome/components/wk2168_spi/__init__.py
> +    cg.add_build_flag("-DHAS_GPIO_PIN")
Components should avoid setting build flags, and even defines unless absolutely necessary. 
I think the best way to only include the code needed for this specific platform, would be to make a sub-class that includes its own fields and checks etc...

2024-02-29 14:46 UTC, DrCoolzic commented on esphome/components/wk2168_spi/__init__.py
> +    cg.add_build_flag("-DHAS_GPIO_PIN")
Ok I will do that but this is a big work and will force me to add three more component :)
Already tested the concept for i2c working on gpio subclaas
will let you now when ready

2024-03-01 00:59 UTC, jesserockz commented on esphome/components/wk2168_spi/__init__.py
> +    cg.add_build_flag("-DHAS_GPIO_PIN")
Thanks

2024-03-01 12:29 UTC, DrCoolzic commented on esphome/components/wk2168_spi/__init__.py
> +    cg.add_build_flag("-DHAS_GPIO_PIN")
All the build flags and define have been removed. For that I have created two more components weikai_i2c and weikai_spi that takes care of the i2c and spi bus respectively. All the __init__.py have been updated and all the components have been tested by me and some (wk2132 and wk2168 in i2c and spi) have been tested by @SeByDocKy and @Bandit-17 and everything seems to work.
Tests are currently running on the PR and I will fix the code accordingly. So should be ready for rewiew

2024-03-01 13:20 UTC, DrCoolzic commented
Hi Jesse wanted to check if you had time to fix the UART auto_load problem and the post UART validation problem ?
Thanks

2024-03-13 01:29 UTC, jesserockz commented
@DrCoolzic I just tested this PR very briefly and you dont need a `uart` block at all in the yaml anymore to use this component.

2024-03-13 06:55 UTC, SeByDocKy commented
> @DrCoolzic I just tested this PR very briefly and you dont need a `uart` block at all in the yaml anymore to use this component.

Hi,
For me without the UART block (tested in spi), still have errors:

```INFO ESPHome 2024.3.0-dev
INFO Reading configuration /config/esphome/test-wk2168spi-s3.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/5218/head
INFO Updating https://github.com/syssi/esphome-pipsolar.git@pip8048
INFO Updating https://github.com/syssi/esphome-jk-bms.git@main
INFO Updating https://github.com/SeByDocKy/myESPhome.git@None
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Detected timezone 'Europe/Paris'
Failed config

uart: None
  
  'baud_rate' is a required option for [0].
  []
```

2024-03-13 12:08 UTC, DrCoolzic commented
> @DrCoolzic I just tested this PR very briefly and you dont need a `uart` block at all in the yaml anymore to use this component.

Just tested with the last version of ESPHome and it woks. Thanks for fixing this problem.
I will double check the documentation to make sure this requirement is removed.

There are still a problems when using some components. It seems that there is a problem in validate_hub of the uart component.
For example if I add this component to my yaml:
```
ld2410:
  uart_id: uart_id0
sensor:
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_id0
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
```
I am getting the following error:
```
PS U:\__DEV__\VSCode\ESPHome\esphome> esphome run .\config\wk2132_i2c-arduino.yaml
INFO ESPHome 2024.4.0-dev
INFO Reading configuration .\config\wk2132_i2c-arduino.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/5218/head
INFO Cloning https://github.com/DrCoolzic/esphome.git@wk2132
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python312\Scripts\esphome.exe\__main__.py", line 7, in <module>
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\__main__.py", line 1061, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\__main__.py", line 1039, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 1065, in read_config
    res = load_config(command_line_substitutions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 919, in load_config
    return _load_config(command_line_substitutions)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 907, in _load_config
    result = validate_config(config, command_line_substitutions)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 835, in validate_config
    result.run_validation_steps()
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 143, in run_validation_steps
    task.step.run(self)
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\config.py", line 716, in run
    self.comp.final_validate_schema(conf)
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\voluptuous_schema.py", line 34, in __call__
    res = super().__call__(data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python312\Lib\site-packages\voluptuous\schema_builder.py", line 287, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python312\Lib\site-packages\voluptuous\schema_builder.py", line 611, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\voluptuous_schema.py", line 148, in validate_mapping
    cval = cvalue(key_path, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python312\Lib\site-packages\voluptuous\schema_builder.py", line 834, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\final_validate.py", line 56, in validator
    return schema(declaration_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\voluptuous_schema.py", line 34, in __call__
    res = super().__call__(data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python312\Lib\site-packages\voluptuous\schema_builder.py", line 287, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jean\AppData\Local\Programs\Python\Python312\Lib\site-packages\voluptuous\schema_builder.py", line 834, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "U:\__DEV__\VSCode\ESPHome\esphome\esphome\components\uart\__init__.py", line 302, in validate_hub
    uart_id = hub_config[CONF_ID]
              ~~~~~~~~~~^^^^^^^^^
KeyError: 'id'
```
Will you be able to fix this problem. If I remember correctly you had an idea about what is causing this problem?

2024-04-09 03:32 UTC, jesserockz commented
@DrCoolzic I have fixed that issue now in https://github.com/esphome/esphome/pull/6504

2024-04-09 03:51 UTC, jesserockz requested changes
I had to push some commits to this PR to change from `uart_id` to just `id` which is what the final validate expects. This change will break any existing configs using this PR as an external_component.

@DrCoolzic Can you create new test files located in `tests/components/<component>` for each of the new component folders and move all of the yaml testing into those please.
Base code can be deduplicated with a `common.yaml` inside the folder.

2024-04-09 14:56 UTC, DrCoolzic commented
> I had to push some commits to this PR to change from `uart_id` to just `id` which is what the final validate expects. This change will break any existing configs using this PR as an external_component.
> 
> @DrCoolzic Can you create new test files located in `tests/components/<component>` for each of the new component folders and move all of the yaml testing into those please. Base code can be deduplicated with a `common.yaml` inside the folder.

Is there a documentation somewhere? If I understand correctly looking at other:
1)	create a directory in test/components 
2)	in this directory add one yaml file per platform. Assumption esp32 for esp32 arduino, esp32-idf for esp32 esp-idf, esp8286 for esp8286 etc.
3)	in this file put what used to be in testX.yaml
4)	if several platform use common.yaml to avoid duplication

Is the above correct?

Question: is possible to have:
```
test/components/weikai:
-	common.yaml
-	…
test/component/wk2132_i2c
	test.esp32.yaml that contains <<: !include ../weikai/common.yaml
```

Is there a way to test locally (like esphome compile test/test1.yaml) or can it only be done by submitting

Thanks

2024-04-09 16:34 UTC, DrCoolzic commented
> I had to push some commits to this PR to change from `uart_id` to just `id` which is what the final validate expects. This change will break any existing configs using this PR as an external_component.

I am cannot compile anymore any of my components ???
I have tried  to add
```
external_components:
  - source: github://pr#6504
    components: [uart]
    refresh: 0s
```
but it does not help ?

```
PS U:\__DEV__\VSCode\ESPHome\esphome> esphome run .\config\wk2132_i2c-arduino.yaml
INFO ESPHome 2024.4.0-dev
INFO Reading configuration .\config\wk2132_i2c-arduino.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/6504/head
Failed config

wk2132_i2c: [source .\config\wk2132_i2c-arduino.yaml:52]
  - id: bridge_0
    address: 112
    test_mode: 1
    uart: 

      'id' is a required option for [0].
      - 
        [uart_id] is an invalid option for [0]. Please check the indentation.
        uart_id: uart_id0
        channel: 0
        baud_rate: 115200
        stop_bits: 1
        parity: none
      - uart_id: uart_id1
        channel: 1
        baud_rate: 115200
uart: None

  'baud_rate' is a required option for [0].
  []
...
```

and it fails even if I had a dummy uart?

what should I do to make them working again ???

2024-04-09 16:44 UTC, DrCoolzic commented
the test did not pass with same error: https://github.com/esphome/esphome/actions/runs/8618224123/job/23620133312?pr=5218

2024-04-09 19:21 UTC, jesserockz commented
> - create a directory in test/components
> - in this directory add one yaml file per platform. Assumption esp32 for esp32 arduino, esp32-idf for esp32 esp-idf, esp8286 for esp8286 etc.
> - in this file put what used to be in testX.yaml
> - if several platform use common.yaml to avoid duplication
>
> Is the above correct?

Correct yes

> I am cannot compile anymore any of my components ???

Did you read my message where I said this?

> change from `uart_id` to just `id`

It needs to change to be like this:
```yaml
wk2132_i2c:
  - id: bridge_0
    address: 112
    test_mode: 1
    uart: 
      - id: uart_id0 # Change this from `uart_id` to just `id`
        channel: 0
        baud_rate: 115200
        stop_bits: 1
        parity: none
      - id: uart_id1 # Change this from `uart_id` to just `id`
        channel: 1
        baud_rate: 115200
```

2024-04-10 09:52 UTC, DrCoolzic commented
> @DrCoolzic I have fixed that issue now in #6504

Cool it woks on my test

2024-04-10 12:14 UTC, DrCoolzic commented
> > I am cannot compile anymore any of my components ???
> 
> Did you read my message where I said this?
> 
> > change from `uart_id` to just `id`
> 
> It needs to change to be like this:
> 
> ```yaml
> wk2132_i2c:
>   - id: bridge_0
>     address: 112
>     test_mode: 1
>     uart: 
>       - id: uart_id0 # Change this from `uart_id` to just `id`
>         channel: 0
>         baud_rate: 115200
>         stop_bits: 1
>         parity: none
>       - id: uart_id1 # Change this from `uart_id` to just `id`
>         channel: 1
>         baud_rate: 115200
> ```

Sorry I did not understand what I had to change. My mistake. :( I  have modified my yamls and now it works.

I have completed the tests for the wk2132_i2c and I am waiting for the results. 
If it works correctly I will add the tests for the seven other components. I will also modified my documentation.
Keep you posted. Thanks

2024-04-10 15:13 UTC, DrCoolzic commented
@jesserockz all modifications requested have been done.
- Added 40 files for Weikai components tests
- Removed Weikai test in tests/testX.yaml
- Modified the documentation to reflect your requested changes https://deploy-preview-3113--esphome.netlify.app/components/weikai

Shoul be ready for final review as soon as tests finished ?

2024-04-18 08:54 UTC, DrCoolzic commented
@jesserockz 
FYI since latest modification `uart_component_esp_idf.cpp `does not compile anymorer in idf 5.2.1
```
src/esphome/components/uart/uart_component_esp_idf.cpp: In member function 'virtual void esphome::uart::IDFUARTComponent::setup()':
src/esphome/components/uart/uart_component_esp_idf.cpp:72:34: error: invalid conversion from 'uint8_t' {aka 'unsigned char'} to 'uart_port_t' [-fpermissive]
   72 |   this->uart_num_ = next_uart_num++;
      |                     ~~~~~~~~~~~~~^~
      |                                  |
      |                                  uint8_t {aka unsigned char}
*** [.pioenvs\weikai-i2c-spi\src\esphome\components\uart\uart_component_esp_idf.o] Error 1
```
I think it would be nice to fix it.

By the way tests/test6.yaml is broken but I did not touch it ???

2024-04-23 20:50 UTC, jesserockz commented
> FYI since latest modification `uart_component_esp_idf.cpp `does not compile anymorer in idf 5.2.1

This has been fixed in #6487

2024-04-23 21:02 UTC, jesserockz commented on esphome/components/wk2132_i2c/wk2132_i2c.cpp
> +/* compiling with esp-idf framework requires a .cpp file for some reason ? */
Weird, I will look into this after this PR is merged

2024-04-23 21:14 UTC, jesserockz approved these changes

2024-04-24 01:21 UTC, merged