ESP-ADF microphone and speaker board support for s3-box
OttoWinter/esphomeyaml pull request #5230
Opened 2023-08-10 20:03 UTC by jesserockz

# What does this implement/fix?

This imports esp-adf as an esp-idf component allowing auto configuration of the speaker and microphone drivers for specific boards (ESP32-S3-BOX is the only supported board in ESPHome for now)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-15 08:16 UTC, alucryd commented
Nice, would be nice to extend that to older boards like the LyraTD, it's not officially supported but if you don't count the crashes when playing audio, it's looking pretty good already.

2023-08-15 23:14 UTC, jesserockz commented
> Nice, would be nice to extend that to older boards like the LyraTD, it's not officially supported but if you don't count the crashes when playing audio, it's looking pretty good already.

If you can test it and show that it works, then you can make a PR to add the board to the list (once this is actually merged)

2023-10-20 20:01 UTC, joey-90 commented
I've been trying to use this with the ESP32-S3-Korvo-1, I can get speaker and microphone working with push to speak. However whenever trying to enable ESP-ADF I get a compile error, are there plans to support this board? If so is there anything that would help the implementation?

2023-11-07 18:57 UTC, genebean commented on esphome/components/esp_adf/__init__.py
> +    )
I may be misreading things, but it seems like this section of this PR is referenced by https://github.com/esphome/firmware/blob/d760ac5a753f69cec1296e51eba38778eaddfe47/voice-assistant/m5stack-atom-echo.yaml#L216-L220 and is resulting in https://github.com/esphome/issues/issues/4952, and likely also https://github.com/esphome/firmware/issues/45

2023-11-21 20:44 UTC, ArminasTV commented
Hello
I just compiled the voice assistant firmware for the esp32 s3 box3 get it here _https://github.com/esphome/firmware/blob/main/voice-assistant/esp32-s3-box-3.yaml_
The microphone does not work.
I am on Windows 11 with the latest version of esphome 2023.11.3.
With Visual Code, I run the command `esphome run esps3box.yaml --device COM4`

On the other hand, the firmware of the site _https://esphome.io/projects/_ is OK

Logs : 

[21:00:35][D][voice_assistant:159]: Starting Microphone
[21:00:35][D][voice_assistant:395]: State changed from START_MICROPHONE to STARTING_MICROPHONE
[21:00:35][D][esp-idf:000]: I (14841) I2S: DMA Malloc info, datalen=blocksize=512, dma_buf_count=8
[21:00:35]
[21:00:35][D][esp-idf:000]: I (14843) I2S: I2S0, MCLK output by GPIO2
[21:00:35]
[21:00:35][D][esp-idf:000]: I (14845) AUDIO_PIPELINE: link el->rb, el:0x3d036c54, tag:i2s, rb:0x3d037068
[21:00:35]
[21:00:35][D][esp-idf:000]: I (14847) AUDIO_PIPELINE: link el->rb, el:0x3d036dc8, tag:filter, rb:0x3d0390a8
[21:00:35]
[21:00:35][D][esp-idf:000]: I (14850) AUDIO_ELEMENT: [i2s-0x3d036c54] Element task created
[21:00:35]
[21:00:35][D][esp-idf:000]: I (14850) AUDIO_THREAD: The filter task allocate stack on external memory
[21:00:35]
[21:00:35][D][esp-idf:000]: E (14852) AUDIO_THREAD: Not found right xTaskCreateRestrictedPinnedToCore.
[21:00:35]Please enter IDF-PATH with "cd $IDF_PATH" and apply the IDF patch with "git apply $ADF_PATH/idf_patches/idf_4.4._freertos.patch" first
[21:00:35]
[21:00:35]
[21:00:35][D][esp-idf:000]: E (14856) AUDIO_THREAD: Error creating RestrictedPinnedToCore filter
[21:00:35]
[21:00:35][D][esp-idf:000]: E (14856) AUDIO_ELEMENT: [filter] audio_thread_create f
[21:00:35][D][esp-idf:000]: I (14858) AUDIO_ELEMENT: [raw-0x3d036ef8] Element task created
[21:00:35]
[21:00:35][D][esp-idf:000]: I (14860) AUDIO_PIPELINE: Func:audio_pipeline_run, Line:359, MEM Total:16543923 Bytes, Inter:4488 Bytes, Dram:4488 Bytes
[21:00:35]
[21:00:35]
[21:00:35][D][esp-idf:000]: I (14862) AUDIO_ELEMENT: [i2s] AEL_MSG_CMD_RESUME,state:1
[21:00:35]
[21:00:35][D][esp-idf:000]: W (14864) AUDIO_ELEMENT: [filter] Element has not create when AUDIO_ELEMENT_RESUME
[21:00:35]
[21:00:35][D][esp-idf:000]: E (14864) AUDIO_PIPELINE: audio_pipeline_resume failed
[21:00:35]
[21:00:35][D][esp-idf:000]: W (14876) AUDIO_ELEMENT: [filter] Element has not create when AUDIO_ELEMENT_TERMINATE
[21:00:35]
[21:00:35][D][esp_adf.microphone:294]: Microphone started
[21:00:35][D][voice_assistant:395]: State changed from STARTING_MICROPHONE to WAIT_FOR_VAD
[21:00:35][D][voice_assistant:176]: Waiting for speech...
[21:00:35][D][voice_assistant:395]: State changed from WAIT_FOR_VAD to WAITING_FOR_VAD
[21:00:36][D][esp32_ble:255]: Disabling BLE...

2023-11-23 00:37 UTC, abmantis requested changes

2023-11-23 00:37 UTC, abmantis commented on esphome/components/esp_adf/microphone/esp_adf_microphone.cpp
> +      .i2s_port = I2S_NUM_0,
```suggestion
      .i2s_port = static_cast<i2s_port_t>(CODEC_ADC_I2S_PORT),
```
This is required for boards that use a mic that is not on I2S 0, like Korvo1

2023-11-23 22:24 UTC, abmantis requested changes

2023-11-23 22:24 UTC, abmantis commented on esphome/components/esp_adf/__init__.py
> +    "esp32s3box3": "CONFIG_ESP32_S3_BOX_3_BOARD",
```suggestion
    "esp32s3box3": "CONFIG_ESP32_S3_BOX_3_BOARD",
    "esp32s3korvo1": "CONFIG_ESP32_S3_KORVO1_BOARD",
```

2023-11-28 22:58 UTC, abmantis commented on esphome/components/esp_adf/__init__.py
> +    "esp32s3box3": "CONFIG_ESP32_S3_BOX_3_BOARD",
@jesserockz could you add this one please?
It is used here: https://github.com/abmantis/firmware/blob/korvo1/voice-assistant/esp32-s3-korvo1.yaml

2023-12-21 14:35 UTC, Nardol commented
When compiling with this PR, I have the following on console:

```txt
Linking .pioenvs/enceinte-test/firmware.elf
/home/user/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: missing -
-end-group; added as last command line option
```

Is it expected?

2024-02-22 05:15 UTC, sammcj commented
Is this PR still current?

I've got a esp-s3-box-3 and the standard esphome config file for it references this PR:

```yaml
external_components:
  - source: github://pr#5230
    components: esp_adf
    refresh: 0s
```

and fails:

```
INFO ESPHome 2024.2.0
INFO Reading configuration /config/esp-s3-box-3.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/5230/head
ERROR Unable to load component ili9xxx.display:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 169, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/esphome/esphome/components/ili9xxx/display.py", line 155, in <module>
    .extend(spi.spi_device_schema(False, "40MHz")),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: spi_device_schema() takes from 0 to 1 positional arguments but 2 were given
```

2024-03-07 04:35 UTC, jaymunro commented
Hi @jesserockz 

Is the reason this pr is not progressing because of the failing checks with missing file references in the includes?
- esphome/components/esp_adf/microphone/esp_adf_microphone.cpp
- `algorithm_stream.h` file not found on line 10

and
- esphome/components/esp_adf/speaker/esp_adf_speaker.h
- `audio_element.h` file not found x 2 on line 14

Interestingly `esphome/components/esp_adf/microphone/esp_adf_microphone.cpp` includes `audio_element.h` on line 11 but there is no mention of file not found from the check.

I see `algorithm_stream.h` can be found at:
https://github.com/espressif/esp-adf/blob/master/components/audio_stream/include/algorithm_stream.h

and `audio_element.h` can be found at:
https://github.com/espressif/esp-adf/blob/master/components/audio_pipeline/include/audio_element.h

Should these be copied in locally so they can be referenced as needed (if they are needed)?

2024-03-07 04:40 UTC, jesserockz commented
It's not progressing because I have not found a way to get esp idf components available for CI.
It works just fine as an `external_component`

2024-03-07 04:45 UTC, jaymunro commented
Ah, that's above my pay grade at this stage.

2024-05-14 07:24 UTC, IvanVojtko commented
I tried to install this into my brand new M5 echo, but microphone is not working. I enabled debug in HA and I'm getting empty wav files. When I tried M5 "repeater" demo, my microphone works, but I had to add `tx_pin_config.mck_io_num = GPIO_NUM_0;`, otherwise I was getting errors and mic was not working. I tried to do the same here by adding `i2s_mclk_pin: GPIO0`, but no luck, still empty wav files. Any idea what is wrong? I even tried to hardcode mck_io_num = 0 into CPP files just to make sure it's there. I'm using button to wake up, but I also have to stop it manually, as it doesn't get my voice at all.

2024-05-16 23:51 UTC, jmorille commented
This a way to support esp32-s3-korvos board ?
 - esp-adf is not supported :  https://github.com/espressif/esp-adf?tab=readme-ov-file#hardware

Or any way to adapte a configuration to use with this ?

2024-06-12 09:19 UTC, mikenorgate commented
Will these changes work with the `media_player` component? I would like to make TTS announcements on the ESPHome device but I can't see how to play a message with just the `speaker` component

2024-08-17 11:49 UTC, nielsnl68 requested changes

2024-08-17 11:49 UTC, nielsnl68 commented on esphome/components/esp_adf/__init__.py
> +        components=["*"],
Could you just add the components that you really need for esphome Component to work?

2024-08-17 11:50 UTC, nielsnl68 commented
Also could you merge the last DEV branch into this PR?

2024-09-10 18:03 UTC, johnboiles commented
@jesserockz: I've been trying both this and [gnumpi/esphome_audio](https://github.com/gnumpi/esphome_audio) to use ADF things in ESPHome. I've appreciated @gnumpi's approach to supporting ESP-ADF's pipelines in ESPHome. You've probably taken a look at it but in case you haven't it's worth a look. Instead of hardcoding the ADF pipeline in the C++ it allows you to compose the pipeline in the YAML.

I wanted to add optical SPDIF out to my ESPHome media player. I first looked at doing it directly in ESPHome but all the decoding stuff is specific to the I2S media player (since that component [uses](https://github.com/esphome/esphome/blob/caaae59ea9db397bc80e6e51504bd698ece059f3/esphome/components/i2s_audio/media_player/i2s_audio_media_player.h#L14) [ESP32-audioI2S](https://github.com/schreibfaul1/ESP32-audioI2S)). That meant to make an ESPHome SPDIF output I would need to bring in my own audio decoder. Using @gnumpi's approach, I just created new ADF pipeline element as a sink for the audio. The existing ADF pipeline elements took care of decoding the media, and resampling the media (if needed). It left my implementation is pretty simple (see https://github.com/gnumpi/esphome_audio/pull/59). 

```yaml
spdif_audio:
  pin: GPIO13

adf_pipeline:
  - platform: spdif_audio
    id: adf_spdif_out

media_player:
  - platform: adf_pipeline
    id: adf_media_player
    name: Main Stereo
    internal: false
    keep_pipeline_alive: true
    pipeline:
      - self
      - resampler
      - adf_spdif_out
```

I think a composable pipeline design like this would make it simpler to adopt other ADF features and pipeline elements (like perhaps [multiroom audio](https://github.com/espressif/esp-adf/blob/302f9a2c113d302776b896149fbcdd6d718438da/examples/advanced_examples/multi-room/README.md#L1) at some point 😄 ) since you could bring in those features individually instead of making a `media_player` variant for every combination of pipeline elements.

2024-09-10 19:58 UTC, jesserockz commented on esphome/components/esp_adf/__init__.py
> +        components=["*"],
I started it like that, then it complained X was missing, then Y, then Z, and soon enough, I had pretty much all of the components added, so just gave up and changed to *.

2024-09-10 19:58 UTC, jesserockz commented
This PR / Branch really was only a quick/easy way to bringing the s3-box mic/speaker support into ESPHome. I probably wont merge this PR into ESPHome as we found that ESP-ADF does stuff we didnt like and wanted to focus more on natively implementing the features. (And the fact that it is a massive and crazy esp-idf component with many dependencies and esp-idf patches makes it not desireable to merge and maintain.

2025-04-30 09:26 UTC, jesserockz commented
I am closing this PR as components for the various s3-boxes were created directly in ESPHome now, and these devices are supported without the need for esp-adf.

2025-04-30 09:26 UTC, closed without merging