Implement deep sleep and clear screen on Waveshare 7.5in B V3
OttoWinter/esphomeyaml pull request #5239
Opened 2023-08-12 17:19 UTC by lucasprim

# What does this implement/fix?

As stated on [issue 4739](https://github.com/esphome/issues/issues/4739), some of the components used to handle the communication with waveshare displays are leaving the screen always on a high power state.

As stated on the "precautions" section of the [official manufacturer documentation](https://www.waveshare.com/wiki/7.5inch_e-Paper_HAT_(B)_Manual#Precautions), and in the [Waveshare 7.5in B Datasheet (p. 35)](https://www.waveshare.com/w/upload/8/8c/7.5inch-e-paper-b-v3-specification.pdf), a normal operation should not leave the screen powered on after an update.

This PR implements a "turn off/deep sleep" command after the screen is updated along with a "reset/turn on" command used whenever the display needs to be refreshed.

Also implemented a `clear_screen()` method that clears the screen on initialization and may be used to clear the screen before storage, as recommended by the manufacturer.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Other

**Related issue or feature (if applicable):** fixes [4739](https://github.com/esphome/issues/issues/4739) on 7.5 in [Waveshare V3 "B" model](https://www.waveshare.com/wiki/7.5inch_e-Paper_HAT_(B)_Manual#Introduction)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** Not Applicable

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
button:
  - platform: template
    name: "Clear Screen"
    on_press:
      - lambda: id(epaper).clear_screen();

font:
  - file:
      type: gfonts
      family: Inter
      weight: 900
    id: font_main_title
    size: 24

spi:
  clk_pin: 13
  mosi_pin: 14
  id: epaper_display

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: 15
    dc_pin: 27
    busy_pin: 25
    reset_pin: 26
    model: 7.50in-bV3
    update_interval: 30s
    reset_duration: 2ms
    rotation: 90°
    lambda: |-
      it.filled_circle(240, 200, 50);
      it.print(240, 400, id(font_main_title), TextAlign::CENTER, "HELLO WORLD!");
      it.filled_circle(240, 600, 50);
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-14 19:08 UTC, jesserockz requested changes

2023-08-14 19:08 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +  this->display();
`display()` really should not be called outside of the `update` "loop"

2023-08-14 19:08 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +  this->display();
If its for storage purposes, then you should just flash a config with a blank page and wait for it to draw before turning off

2023-09-30 15:13 UTC, lucasprim commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +  this->display();
Agreed. Sorry for the delay on fixing this.
I've removed the `clear_screen()` code, there are other ways to accomplish what i wanted.
It's been running for a solid week now.

2023-10-07 11:02 UTC, lucasprim commented
@jesserockz Hi! Any chance you could get a look at the changes? I think it's production ready, been running for two weeks straight with absolutely no problems.

2023-11-21 16:49 UTC, lucasprim commented
Hi! I've been running this code for a while now and it works flawlessly. Any chance this will get accepted into the main branch? I really think this will benefit other owners of Waveshare e-Ink displays that want an improved lifetime for their displays.

2023-11-27 14:47 UTC, lucasprim commented
> Hi! I've been running this code for a while now and it works flawlessly. Any chance this will get accepted into the main branch? I really think this will benefit other owners of Waveshare e-Ink displays that want an improved lifetime for their displays.

@jesserockz It would be great if you could take a look 😄

2023-11-27 23:40 UTC, jesserockz approved these changes

2023-11-27 23:40 UTC, merged