New component: ADE7880 voltage/current/power/energy sensor
OttoWinter/esphomeyaml pull request #5242
Opened 2023-08-13 19:39 UTC by kpfleming

# What does this implement/fix?

ADE7880 voltage/current/power/energy sensor

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1579

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```yaml
sensor:
  - platform: ade7880
    irq0_pin:
      number: GPIO13
    irq1_pin:
      number: GPIO5
    channel_a:
      name: Room Heater
      voltage: Voltage
      current: Current
      active_power: Active Power
      power_factor: Power Factor
      forward_active_energy: Forward Active Energy
      reverse_active_energy: Reverse Active Energy
      calibration:
        current: 3116628
        voltage: -757178
        power: -1344457
        phase_angle: 188
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-14 11:58 UTC, sourabhjaiswal approved these changes

2023-08-27 11:58 UTC, kpfleming commented
CI failures in this PR will be resolved once #5304 is merged.

2023-09-10 10:35 UTC, kpfleming commented
Updated to reflect the changes made in #5304.

2023-12-19 05:23 UTC, jesserockz requested changes

2023-12-19 05:23 UTC, jesserockz commented on esphome/components/ade7880/sensor.py
> +                cv.Required(CONF_CURRENT): cv.int_,
We try to enforce units on config entries so users know specifically what they are typing in.
Please apply this to the below calibration too.
```suggestion
                cv.Required(CONF_CURRENT): cv.All(cv.current, cv.int_),
```

2023-12-19 05:23 UTC, jesserockz commented on esphome/components/ade7880/sensor.py
> +        current[CONF_NAME] = f"{channel_name} {sensor_name}"
I see what you are doing here, but the config object should not be manipulated after config validation has been performed.

2023-12-19 11:40 UTC, kpfleming commented on esphome/components/ade7880/sensor.py
> +                cv.Required(CONF_CURRENT): cv.int_,
In this case there are no units; the value is a factor used in the calculations inside the chip. If this is a concern, I can make new CONF_ entries and avoid using CONF_CURRENT/VOLTAGE/etc.

2023-12-19 11:41 UTC, kpfleming commented on esphome/components/ade7880/sensor.py
> +        current[CONF_NAME] = f"{channel_name} {sensor_name}"
Fair enough; would it be OK if I did this in a `final_validate` function instead?

2023-12-22 06:18 UTC, jesserockz commented on esphome/components/ade7880/sensor.py
> +                cv.Required(CONF_CURRENT): cv.int_,
Perhaps a better name is `current_gain` etc?

2023-12-22 12:14 UTC, kpfleming commented on esphome/components/ade7880/sensor.py
> +                cv.Required(CONF_CURRENT): cv.int_,
Sure, that will work. The datasheet says the registers are called "<X>GAIN" :-)

2023-12-22 15:19 UTC, kpfleming commented on esphome/components/ade7880/sensor.py
> +                cv.Required(CONF_CURRENT): cv.int_,
Changes made; those three configuration elements are now `current_gain`, `power_gain`, and `voltage_gain`.

2023-12-22 15:20 UTC, kpfleming commented on esphome/components/ade7880/sensor.py
> +        current[CONF_NAME] = f"{channel_name} {sensor_name}"
The name manipulation has been moved into `final_validate` so the effects will be visible if `esphome config` is used.

2024-01-18 00:18 UTC, jesserockz requested changes

2024-01-18 00:18 UTC, jesserockz commented on tests/test1.yaml
> +      number: GPIO16
```suggestion
    irq0_pin:
      number: GPIO13
      allow_other_uses: true
    irq1_pin:
      number: GPIO5
      allow_other_uses: true
    reset_pin:
      number: GPIO16
      allow_other_uses: true
```

2024-01-18 00:18 UTC, jesserockz commented on tests/test3.1.yaml
> +      number: GPIO16
```suggestion
    irq0_pin:
      number: GPIO13
      allow_other_uses: true
    irq1_pin:
      number: GPIO5
      allow_other_uses: true
    reset_pin:
      number: GPIO16
      allow_other_uses: true
```

2024-01-18 01:10 UTC, jesserockz submitted a review, later dismissed

2024-01-20 17:09 UTC, kpfleming commented
@jesserockz Thanks for the 'duplicate pin' fix; that problem was masking an actual problem in the Python code, which has now been fixed. I've also rebased the branch against `dev` to remove all of the intermediary merge-commits.

2024-02-19 19:25 UTC, jesserockz submitted a review, later dismissed

2024-02-19 19:40 UTC, kpfleming commented
OK, updated to latest `dev` again and added component-level YAML tests using the new framework.

2024-02-19 22:29 UTC, kpfleming commented
... and now refactored the component-level YAML tests using `<<: !include` to avoid repeating the configuration to be tested.

2024-02-19 23:16 UTC, jesserockz approved these changes

2024-02-19 23:24 UTC, merged