load font from url
OttoWinter/esphomeyaml pull request #5254
Opened 2023-08-15 17:33 UTC by landonr

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
font:
    - file: "https://github.com/landonr/homeThing/raw/main/fonts/iosevka-heavy.ttf"
      id: large_heavy_font
      size: 24
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-20 12:58 UTC, guillempages commented on esphome/components/font/__init__.py
> +    return None
As in #5214, this could be combined into the get_filename_from_url method

2023-08-20 12:58 UTC, guillempages commented on esphome/components/font/__init__.py
> +        file_name = match.group(1)
You might want to rename to filename for consistency with the method name
```suggestion
        filename = match.group(1)
```

2023-08-20 12:58 UTC, guillempages commented on esphome/components/font/__init__.py
> +        file_name = re.sub(r"%20", "", file_name)  # Replace %20 with empty string
"%20" is normally a space; maybe replace by "_" for better readability?

2023-08-20 12:58 UTC, guillempages commented on esphome/components/font/__init__.py
> +def download_font(value):
Maybe combine with `download_gfont`? (i.e. write the common functionality only once and keep the methods only for parsing the URLs/names)

2023-08-20 12:58 UTC, guillempages commented on esphome/components/font/__init__.py
> +    if value.startswith("https"):
unencrypted http is not fully dead yet ;-)
```suggestion
    if value.startswith("http://") or value.startswith("https://"):
```

2023-08-20 12:58 UTC, guillempages commented on esphome/components/font/__init__.py
> +def _compute_local_image_path(value) -> Path:
Could this be combined with the gfont one?
Also, the hash calculation used for gfonts might also be useful here, to allow downloading diffenent fonts with the same name (but different URLs)

2023-08-20 12:58 UTC, guillempages commented on esphome/components/font/__init__.py
> +        path = _compute_local_image_path(conf).as_posix()
Could the `as_posix()` call be done within the `compute_path` method? (this comment might become irrelevant if you do combine it with the `_compute_gfonts_local_path` method).

2023-08-21 12:47 UTC, landonr commented
thanks for the review @guillempages i'll do the changes this week. It might make sense to move out the `compute_local_path` stuff to a new file because it can be used between fonts and images.

I've also been meaning to add an option for `refresh: 1day` so images can be updated

2023-08-25 22:30 UTC, landonr commented on esphome/components/font/__init__.py
> +def download_font(value):
good idea, I had to call it from the higher level config, but it looks a lot cleaner

2023-08-25 22:30 UTC, landonr commented on esphome/components/font/__init__.py
> +        file_name = re.sub(r"%20", "", file_name)  # Replace %20 with empty string
done!

2023-08-25 22:30 UTC, landonr commented on esphome/components/font/__init__.py
> +        file_name = match.group(1)
i renamed the method instead because file_name was used elsewhere already

2023-08-25 22:36 UTC, landonr commented on esphome/components/font/__init__.py
> +def _compute_local_image_path(value) -> Path:
I'll check back on this

2023-08-25 22:37 UTC, landonr commented on esphome/components/font/__init__.py
> +        path = _compute_local_image_path(conf).as_posix()
I removed this, but I haven't tested it yet

2023-08-25 22:38 UTC, landonr commented on esphome/components/font/__init__.py
> +    if value.startswith("https"):
long live http. what do you suggest? I can look for a regex to match URLs if you think that works?

2023-08-26 13:04 UTC, landonr commented on esphome/components/font/__init__.py
> +    return None
i don't really understand this comment, can you suggest the change? How would the method return 2 different options

2023-08-27 00:41 UTC, landonr commented
> thanks for the review @guillempages i'll do the changes this week. It might make sense to move out the `compute_local_path` stuff to a new file because it can be used between fonts and images.
> 
> I've also been meaning to add an option for `refresh: 1day` so images can be updated

@guillempages i updated the external_files stuff to a new component called `external_files`. I also added the `source_refresh` key, but made it default to `never`

2023-08-27 13:04 UTC, guillempages commented on esphome/components/font/__init__.py
> +    return None
You can return a tuple:
```
return (file_name, file_type)
```

and when calling the method you can do
```
  filename, extension = get_file_from_url(url)
```
And you would fill both variables with a single call. Python magic ;-)

2023-08-27 13:28 UTC, guillempages commented on esphome/components/external_files/__init__.py
> +    sub_directory = Path(os.path.join(base_directory, str(current_time)))
I don't think it's a good idea to hard-code the timestamp into the directory name. Both Linux and Windows filesystems do store metadata related to the file like when was it created; no need to make this explicit in the directory name.

2023-08-27 13:28 UTC, guillempages commented on esphome/components/external_files/__init__.py
> +def compute_local_file_dir(name: str, domain: str, refresh: TimePeriodSeconds) -> Path:
IMHO "refresh" would only be relevant when deciding whether to re-download or not, but the whole directory creation methods should be agnostic to the refresh time.

2023-08-27 13:28 UTC, guillempages commented on esphome/components/external_files/__init__.py
> +        dir_timestamp = int(os.path.basename(directory_path))
You should read the timestamp from the file stats; not from the directory name.

2023-08-27 13:28 UTC, guillempages commented on esphome/components/external_files/__init__.py
> +def find_recent_directory(base_directory: str, refresh: TimePeriodSeconds) -> Path:
I'm not sure this method is needed at all (I know you are calling it; I mean I don't think this should be called ;-) )

2023-08-27 13:28 UTC, guillempages commented on esphome/components/external_files/__init__.py
> +        return recent_directory
The directory should be unrelated to the timestamp.

2023-08-27 13:28 UTC, guillempages commented on esphome/components/external_files/__init__.py
> +    pattern = r"/([^/]+)$"
As mentioned before, you could combine "filename" and "extension" into a single regex, to optimize the code a bit. If you then `return (filename, extension)`, callers can get the split for free...

2023-08-27 13:28 UTC, guillempages commented on esphome/components/external_files/__init__.py
> +def get_file_type(file_name):
...And then you wouldn't need this method.

2023-08-27 13:28 UTC, guillempages commented on esphome/components/font/__init__.py
> +from esphome.components import external_files
I'm not sure if this is actually a component, or would be a utility; but that's not for me to decide; that should be decided by the project owners (Jesse & Co)

2023-08-27 13:28 UTC, guillempages commented on esphome/components/font/__init__.py
> +    return ""
Maybe better return None, instead of an empty string?
```suggestion
    return None
```

2023-08-27 13:28 UTC, guillempages commented on esphome/components/font/__init__.py
> +    return ""
```suggestion
    return None
```

2023-08-27 13:28 UTC, guillempages commented on esphome/components/font/__init__.py
> +                external_files.compute_local_file_dir(name, DOMAIN, value[CONF_REFRESH])
Previously, the directory contained a hashed version of the font name; now it contains the name in plaintext. I don't have a strong opinion either way, but I assume the previous implementation was done this way for a reason; maybe Jesse does have some input on that.

2023-08-27 13:28 UTC, guillempages commented on esphome/components/font/__init__.py
> +    return ""
```suggestion
    return None
```

2023-08-27 13:28 UTC, guillempages commented on esphome/components/font/__init__.py
> +        font_id = external_files.get_file_name_from_url(value[CONF_URL])
You created the method "get_font_name", but are not using that?

2023-08-27 13:28 UTC, guillempages commented on esphome/components/font/__init__.py
> +        req = requests.get(url, timeout=30)
Maybe create a constant for the timeout?

2023-08-27 13:28 UTC, guillempages commented on esphome/components/font/__init__.py
> +        cv.Optional(CONF_REFRESH, default="never"): cv.All(
Not sure about the "refresh" value. Maybe a more automatic system, using the ETAG header from the HTTP request would be better? If the server properly implements that, it would return an id on the etag header, that would indicate whether the file changed on the server or not. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag)

2023-08-27 13:28 UTC, guillempages commented on esphome/components/font/__init__.py
> +CONFIG_SCHEMA = cv.All(
Was this change necessary because of the CI formatting checks (black, pyflake,...)?

2023-08-27 16:48 UTC, landonr commented on esphome/components/external_files/__init__.py
> +    sub_directory = Path(os.path.join(base_directory, str(current_time)))
i thought about that but I wasn't sure if that was a solid solution. It's an easy switch if you think that's better!

2023-08-27 16:50 UTC, landonr commented on esphome/components/font/__init__.py
> +        cv.Optional(CONF_REFRESH, default="never"): cv.All(
interesting, i'll check that out! I made it default to never because it could return a new directory if the build took over a second. This should solve that

2023-08-27 16:51 UTC, landonr commented
thanks @guillempages i'll get to work on this later today or tomorrow

2023-09-06 22:49 UTC, landonr commented on esphome/components/font/__init__.py
> +    return None
got it working, thanks for the suggestion!

2023-09-06 22:52 UTC, landonr commented on esphome/components/font/__init__.py
> +CONFIG_SCHEMA = cv.All(
I forgot to remove this, thanks!

2023-09-07 00:35 UTC, landonr commented on esphome/components/font/__init__.py
> +        cv.Optional(CONF_REFRESH, default="never"): cv.All(
how do you think we should keep track of the etag? In the file name or directory?

2023-10-15 01:51 UTC, landonr commented on esphome/components/external_files/__init__.py
I moved this to a new file so we can reuse it for images

2023-10-27 00:10 UTC, jesserockz commented on esphome/components/external_files/__init__.py
This is probably better off in a helper/util file, not a component file

2023-10-27 14:46 UTC, landonr commented on esphome/components/external_files/__init__.py
I'm going to reuse it for external images, i'll move it out to a helper file

2023-10-29 23:26 UTC, landonr commented on esphome/components/font/__init__.py
> +        return value
return the font if the file is recent, or the etag matches the remote

2023-11-24 17:32 UTC, landonr commented
@jesserockz updated with changes from #5214

2023-12-12 04:57 UTC, jesserockz requested changes

2023-12-12 04:57 UTC, jesserockz commented on esphome/components/font/__init__.py
> +        download_gfont(typed_schema)
I think these should still be on the relevant SCHEMAs as extras...

2023-12-22 04:17 UTC, landonr commented on esphome/components/font/__init__.py
> +        download_gfont(typed_schema)
Thanks! Updated, let me know what you think

2023-12-22 05:32 UTC, jesserockz requested changes

2023-12-22 05:32 UTC, jesserockz commented on esphome/components/font/__init__.py
>  )
No, it should be like this I think.
```suggestion
GFONTS_SCHEMA = cv.All(
    EXTERNAL_FONT_SCHEMA.extend(
        {
            cv.Required(CONF_FAMILY): cv.string_strict,
        }
    ),
    download_gfont,
)

WEB_FONT_SCHEMA = cv.All(
    EXTERNAL_FONT_SCHEMA.extend(
        {
            cv.Required(CONF_URL): cv.string_strict,
        }
    ),
    download_web_font,
)
```

2023-12-22 14:38 UTC, landonr commented on esphome/components/font/__init__.py
>  )
nice I couldn't figure out how to get the cv.All to have a schema. Updated, hopefully it looks good!

2024-03-12 21:52 UTC, jesserockz submitted a review, later dismissed

2024-03-12 22:11 UTC, jesserockz approved these changes, later dismissed

2024-03-12 22:23 UTC, clydebarrow approved these changes
Tested the earlier font changes with this, all seems well.

2024-03-12 22:25 UTC, jesserockz commented
Thanks @clydebarrow. Im just fixing up the docs PR now

2024-03-12 23:07 UTC, merged