Adding an RGB version of the 2.4 inch TFT
OttoWinter/esphomeyaml pull request #5270
Opened 2023-08-17 13:50 UTC by ElektronikCZ

# What does this implement/fix?

Every aliexpress 2.4TFT ive ordered is RGB instead of BGR, so that means the colours are all wrong. This just adds a TFT 2.4 RGB and TFT 2.4 R RGB variant that is fixed. Honestly im not home currently so i cant test it, but it should probably work or atleast serve as a base of a fix. Its based on this fix [https://github.com/esphome/issues/issues/3418#issuecomment-1646327294](url), which i did test at  home. Solves issue #3418

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
display:
  - platform: ili9xxx
    model: TFT 2.4R RGB
    #height: 320
    #width: 240
    #offset_height: 0
    #offset_width: 0
    dc_pin: GPIO32
    cs_pin: GPIO33
    reset_pin: GPIO27
    data_rate: 80MHz

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-08-17 15:09 UTC, nielsnl68 approved these changes
Looks good to me.

2023-08-18 07:56 UTC, ElektronikCZ commented
Added the documentation in docs: https://github.com/esphome/esphome-docs/pull/3139

2023-08-20 08:27 UTC, nielsnl68 requested changes

2023-08-20 08:27 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_init.h
> +  0xEA, 2, 0x00, 0x00,
Do you have the `command` names for the above codes? when so please use that here.

2023-08-21 08:34 UTC, ElektronikCZ commented on esphome/components/ili9xxx/ili9xxx_init.h
> +  0xEA, 2, 0x00, 0x00,
I dont have the codes, the config is copied from ILI9341 to avoid any potential issues. The only change is changing the line 
" ILI9XXX_MADCTL  , 1, 0x48,             // Memory Access Control" 
to 
" ILI9XXX_MADCTL  , 1, 0x40,             // Memory Access Control"

2023-11-25 01:13 UTC, clydebarrow commented
#5406 would supersede this since it allows the color order to be specified. IMHO preferable to adding yet more specific model configs.

2023-11-27 15:09 UTC, ElektronikCZ commented
Epic

2023-11-27 15:09 UTC, closed without merging