Modbus Controller added some features
OttoWinter/esphomeyaml pull request #5318
Opened 2023-08-30 14:58 UTC by 0x3333

# What does this implement/fix?

Added some helpers and functionalities to Modbus Controller:

* Exposed `get_command_queue_length()` method as public, in my case, it is useful to know if the module has sent all commands(In case we update very frequently).
* If the Modbus module didn't respond, we mark the module `offline`(Currently not exposed to UI or API just via code).
* Added `offline_skip_updates`, if the module is offline, we skip some updates so we don't have to wait too much for the timeout of some module and keep reading others in the same bus.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** Will update the docs about `offline_skip_updates` if this PR is cleared.

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
modbus_controller:
  - id: modbus_input_0
    address: 0x1
    modbus_id: modbus_0
    offline_skip_updates: 50
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs). ***Not yet***

2023-09-01 02:08 UTC, jesserockz requested changes

2023-09-01 02:08 UTC, jesserockz commented on esphome/components/modbus_controller/modbus_controller.h
> +      : command_throttle_(throttle), offline_skip_updates_(offline_skip_updates){};
We dont need the variables in both the constructor and as setters. Lets just change to setters only to match the codebase.
```suggestion
```

2023-09-01 02:08 UTC, jesserockz commented on esphome/components/modbus_controller/__init__.py
> +    cg.add(var.set_offline_skip_updates(offline_skip_updates))
```suggestion
    var = cg.new_Pvariable(config[CONF_ID])
    cg.add(var.set_command_throttle(config[CONF_COMMAND_THROTTLE]))
    cg.add(var.set_offline_skip_updates(config[CONF_OFFLINE_SKIP_UPDATES]))
```

2023-09-01 13:33 UTC, 0x3333 commented on esphome/components/modbus_controller/modbus_controller.h
> +      : command_throttle_(throttle), offline_skip_updates_(offline_skip_updates){};
`throttle` was already present in the constructor, should I remove it and let only the setter?

2023-09-05 19:51 UTC, jesserockz approved these changes

2023-09-05 20:01 UTC, 0x3333 commented
I'll create a PR regarding the docs.

2023-09-05 20:37 UTC, 0x3333 commented
Created Docs [PR](https://github.com/esphome/esphome-docs/pull/3163)

2023-09-12 22:15 UTC, merged