Debug component: add free PSRAM sensor
OttoWinter/esphomeyaml pull request #5334
Opened 2023-09-02 14:58 UTC by kahrendt

# What does this implement/fix?

Adds a free PSRAM sensor to the ``debug`` component, as suggested by @martijnbuts in a comment on a recent PR. Additionally, it checks for the ``CHIP_FEATURE_EMB_PSRAM`` bit in the ``esp_chip_info_t`` variable in ``dump_config()``. Note, this appears to not be consistently set for all chips with psram in the esp-idf code. Finally, I added the sensors to several test cases.

I have tested these changes on an ESP32 with PSRAM, without PSRAM, and an ESP32-S3 with PSRAM, and all report as expected.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** not applicable

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3160

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-09-04 20:37 UTC, jesserockz requested changes

2023-09-04 20:37 UTC, jesserockz commented on esphome/components/debug/sensor.py
> +        sensor.sensor_schema(
This will force fail validation if your config doesnt have `psram` (Either manually added or autoloaded by some components.
```suggestion
    cv.Optional(CONF_PSRAM): cv.All(
        cv.only_on_esp32,
        cv.requires_component("psram"),
        sensor.sensor_schema(
```

2023-09-04 22:24 UTC, jesserockz approved these changes

2023-09-04 22:26 UTC, jesserockz requested changes

2023-09-04 22:26 UTC, jesserockz commented on tests/test5.yaml
> +debug:
```suggestion
debug:

psram:
```

2023-09-04 22:26 UTC, jesserockz commented on tests/test8.yaml
> +debug:
```suggestion
debug:

psram:
```

2023-09-04 22:28 UTC, jesserockz approved these changes

2023-09-05 00:18 UTC, kahrendt commented
Thanks for the feedback and help with this one!

2023-09-05 02:02 UTC, merged