Updated forked PR for "Add text input component"
OttoWinter/esphomeyaml pull request #5336
Opened 2023-09-03 07:26 UTC by EternityForest

# What does this implement/fix?
This is an updated version of the text inputs component branch, building on work by [mauritskorse](https://github.com/mauritskorse) in https://github.com/esphome/esphome/pull/3638 which seems to have not gotten any updates for a few months.

Almost all of the work here is his, and he deserves full credit, I have only solved some merge conflicts and made a few minor changes as mentioned in the review, as I had some free time and he seems to be busy lately.

The original description is here:

> Adding a input text component (similar to [Home Assistant](https://www.home-assistant.io/integrations/input_text/)). It allows for setting a string by the user through webserver comp front-end (v1). Implementation for v2 webserver front-end and Home Assistant is not done yet.

But I have since added V2 support(https://github.com/esphome/esphome-webserver/pull/43), and I believe that I have covered most of the requested changes in the original.

Changes relative to the original:

Synced to upstream

- Changed the message type numbers as the old ones conflicted with newer upstream work
- Added the ability to persist strings to flash
- Use this-> for property references instead of the implicit ones
- add validate_ method(I wasn't quite sure what was actually needed or how validate works, more of a draft there, maybe @jesserockz can weigh in on if I did it right?)
- Deleted commented out code that did not appear to be relevant
- value_ begins at nullpointer by default(Not sure if that's actually a thing, or if the other components do it for a reason?)
- Added min_length, max_length, and pattern to the JSON in the web server.

The protocol buffers here were **not** compiled with 3.6 as mentioned in a comment, because that version is not available in newer Ubuntus.  If it's an exact version requirement and not a "Any later minor version" kind of thing, I can set up a VM and fix this.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
  - platform: template
    name: "test 2 text"
    id: "it_2"
    icon: "mdi:text"
    optimistic: true
    internal: false
    initial_value: "Welcome ESPHOME"
    restore_value: true
    max_restore_data_length: 24

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

(The original PR is marked as having documentation, but I have not updated it to include the newly-fixed restore_value)

2023-10-24 03:15 UTC, jesserockz requested changes
Overall looks fine. I have not tested yet, but will hopefully this week.
A few things below.

I don't think we need to have an auto mode (there is no way to determine if you want text or password), and mode should be required not optional.

2023-10-24 03:15 UTC, jesserockz commented on esphome/components/api/api.proto
> +  TEXT_MODE_AUTO = 0;
I don't see how an auto mode will help at all..
HA doesn't seem to have this as a mode either

2023-10-24 03:15 UTC, jesserockz commented on esphome/components/text/__init__.py
> +icon = cv.icon
```suggestion
```

2023-10-24 03:15 UTC, jesserockz commented on esphome/components/text/__init__.py
> +    "AUTO": TextMode.TEXT_MODE_AUTO,
```suggestion
```

2023-10-24 03:15 UTC, jesserockz commented on esphome/components/text/__init__.py
> +        cv.Optional(CONF_MODE, default="AUTO"): cv.enum(TEXT_MODES, upper=True),
```suggestion
        cv.Required(CONF_MODE): cv.enum(TEXT_MODES, upper=True),
```

2023-10-24 03:15 UTC, jesserockz commented on esphome/components/text/text_call.cpp
> +void TextCall::perform() {
Missing the call to validate_ ?

2023-10-24 03:15 UTC, jesserockz commented on esphome/components/text/text_traits.cpp
> +#include "esphome/core/log.h"
Not much point in this file...

2023-10-24 03:15 UTC, jesserockz commented on esphome/components/text/text_traits.h
> +  TEXT_MODE_PASSWORD = 2,
```suggestion
  TEXT_MODE_TEXT = 0,
  TEXT_MODE_PASSWORD = 1,
```

2023-10-24 03:15 UTC, jesserockz commented on tests/component_tests/text/test_text.yaml
> +esphome:
These tests are not used by CI. 
Please add to one of the test yaml files in the tests folder.

2023-10-24 08:55 UTC, EternityForest commented
Yeah, I'm not exactly sure what the intent of the auto mode was, but I can
certainly get back on this PR and make those changes!

I could see the value of making generic text as the default and having mode
be optional, but then again, explicit is better than implicit.

I'm impressed by the thoroughness of the review and attention to code
quality!

On Mon, Oct 23, 2023, 9:15 PM Jesse Hills ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Overall looks fine. I have not tested yet, but will hopefully this week.
> A few things below.
>
> I don't think we need to have an auto mode (there is no way to determine
> if you want text or password), and mode should be required not optional.
> ------------------------------
>
> In esphome/components/api/api.proto
> <https://github.com/esphome/esphome/pull/5336#discussion_r1369461731>:
>
> > @@ -1517,3 +1518,49 @@ message AlarmControlPanelCommandRequest {
>    AlarmControlPanelStateCommand command = 2;
>    string code = 3;
>  }
> +
> +// ===================== TEXT =====================
> +enum TextMode {
> +  TEXT_MODE_AUTO = 0;
>
> I don't see how an auto mode will help at all..
> HA doesn't seem to have this as a mode either
> ------------------------------
>
> In esphome/components/text/__init__.py
> <https://github.com/esphome/esphome/pull/5336#discussion_r1369489897>:
>
> > +    "TextStateTrigger", automation.Trigger.template(cg.std_string)
> +)
> +
> +# Actions
> +TextSetAction = text_ns.class_("TextSetAction", automation.Action)
> +
> +# Conditions
> +TextMode = text_ns.enum("TextMode")
> +
> +TEXT_MODES = {
> +    "AUTO": TextMode.TEXT_MODE_AUTO,
> +    "TEXT": TextMode.TEXT_MODE_TEXT,
> +    "PASSWORD": TextMode.TEXT_MODE_PASSWORD,  # to be implemented for keys, passwords, etc.
> +}
> +
> +icon = cv.icon
>
> ⬇️ Suggested change
>
> -icon = cv.icon
>
> ------------------------------
>
> In esphome/components/text/__init__.py
> <https://github.com/esphome/esphome/pull/5336#discussion_r1369490013>:
>
> > +Text = text_ns.class_("Text", cg.EntityBase)
> +TextPtr = Text.operator("ptr")
> +
> +# Triggers
> +TextStateTrigger = text_ns.class_(
> +    "TextStateTrigger", automation.Trigger.template(cg.std_string)
> +)
> +
> +# Actions
> +TextSetAction = text_ns.class_("TextSetAction", automation.Action)
> +
> +# Conditions
> +TextMode = text_ns.enum("TextMode")
> +
> +TEXT_MODES = {
> +    "AUTO": TextMode.TEXT_MODE_AUTO,
>
> ⬇️ Suggested change
>
> -    "AUTO": TextMode.TEXT_MODE_AUTO,
>
> ------------------------------
>
> In esphome/components/text/__init__.py
> <https://github.com/esphome/esphome/pull/5336#discussion_r1369491063>:
>
> > +    "TEXT": TextMode.TEXT_MODE_TEXT,
> +    "PASSWORD": TextMode.TEXT_MODE_PASSWORD,  # to be implemented for keys, passwords, etc.
> +}
> +
> +icon = cv.icon
> +
> +TEXT_SCHEMA = cv.ENTITY_BASE_SCHEMA.extend(cv.MQTT_COMPONENT_SCHEMA).extend(
> +    {
> +        cv.OnlyWith(CONF_MQTT_ID, "mqtt"): cv.declare_id(mqtt.MQTTTextComponent),
> +        cv.GenerateID(): cv.declare_id(Text),
> +        cv.Optional(CONF_ON_VALUE): automation.validate_automation(
> +            {
> +                cv.GenerateID(CONF_TRIGGER_ID): cv.declare_id(TextStateTrigger),
> +            }
> +        ),
> +        cv.Optional(CONF_MODE, default="AUTO"): cv.enum(TEXT_MODES, upper=True),
>
> ⬇️ Suggested change
>
> -        cv.Optional(CONF_MODE, default="AUTO"): cv.enum(TEXT_MODES, upper=True),
> +        cv.Required(CONF_MODE): cv.enum(TEXT_MODES, upper=True),
>
> ------------------------------
>
> In esphome/components/text/text_call.cpp
> <https://github.com/esphome/esphome/pull/5336#discussion_r1369494564>:
>
> > +  int sz = this->value_.value().size();
> +
> +  if (sz > this->parent_->traits.get_max_length()) {
> +    ESP_LOGW(TAG, "'%s' - Value set for TextCall is too long", name);
> +    this->value_.reset();
> +    return;
> +  }
> +
> +  if (sz < this->parent_->traits.get_min_length()) {
> +    ESP_LOGW(TAG, "'%s' - Value set for TextCall is too short", name);
> +    this->value_.reset();
> +    return;
> +  }
> +}
> +
> +void TextCall::perform() {
>
> Missing the call to validate_ ?
> ------------------------------
>
> In esphome/components/text/text_traits.cpp
> <https://github.com/esphome/esphome/pull/5336#discussion_r1369495686>:
>
> > @@ -0,0 +1,10 @@
> +#include "esphome/core/log.h"
>
> Not much point in this file...
> ------------------------------
>
> In esphome/components/text/text_traits.h
> <https://github.com/esphome/esphome/pull/5336#discussion_r1369496212>:
>
> > +  TEXT_MODE_AUTO = 0,
> +  TEXT_MODE_TEXT = 1,
> +  TEXT_MODE_PASSWORD = 2,
>
> ⬇️ Suggested change
>
> -  TEXT_MODE_AUTO = 0,
> -  TEXT_MODE_TEXT = 1,
> -  TEXT_MODE_PASSWORD = 2,
> +  TEXT_MODE_TEXT = 0,
> +  TEXT_MODE_PASSWORD = 1,
>
> ------------------------------
>
> In tests/component_tests/text/test_text.yaml
> <https://github.com/esphome/esphome/pull/5336#discussion_r1369520134>:
>
> > @@ -0,0 +1,31 @@
> +esphome:
>
> These tests are not used by CI.
> Please add to one of the test yaml files in the tests folder.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/5336#pullrequestreview-1693805000>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFZCHZU7XZAWYO4TVWGY3TYA4XFNAVCNFSM6AAAAAA4JEEEIOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMOJTHAYDKMBQGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-24 09:14 UTC, jesserockz commented
> I'm impressed by the thoroughness of the review and attention to code
quality!

When given the time to sit there and without distractions, its really nice to be able to sit there and review code from top to bottom.

Hopefully we can get this into the next ESPHome release, I might be able to get it into the HA November release if I work on that side tomorrow as the beta starts tomorrow for that.

2023-10-24 09:42 UTC, nielsnl68 commented
I will give you a peace of 🍰 when this will be finally in 👯‍♂️

2023-10-25 04:12 UTC, jesserockz approved these changes

2023-10-25 09:00 UTC, merged