Add support for Waveshare EPD 2.13" V3
OttoWinter/esphomeyaml pull request #5363
Opened 2023-09-08 11:50 UTC by clydebarrow

# What does this implement/fix?

Add support for the [V3 Waveshare 2.13" e-paper display](https://www.waveshare.com/wiki/Pico-ePaper-2.13).

While this is possibly the same display as the 2.13in-ttgo-dke already supported this PR provides improved performance - faster updates, less blocking of the loop thread and improved partial updates.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
time:
  - platform: sntp
    id: ntp

spi:
  mosi_pin: GPIO4
  miso_pin: GPIO5
  clk_pin: GPIO6

display:
  - platform: waveshare_epaper
    rotation: 270
    cs_pin: GPIO7
    dc_pin: GPIO15
    busy_pin: GPIO16
    reset_pin: GPIO17
    model: 2.13inv3
    full_update_every: 30
    lambda: |-
      it.strftime(70, 100, id(roboto), TextAlign::BASELINE_LEFT, "%H:%M:%S", id(ntp).now());
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-19 02:34 UTC, clydebarrow commented on tests/test4.yaml
> +    cs_pin: GPIO23
```suggestion
    spi_id: spi_id_1
    cs_pin: GPIO23
```

2023-12-22 04:07 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.h
> +      delay(20);  // NOLINT
```suggestion
      delay(20);
```

2023-12-22 05:05 UTC, clydebarrow commented on esphome/components/waveshare_epaper/waveshare_epaper.h
> +      delay(20);  // NOLINT
I wrote this some time - I'm older and wiser now. Will rework to use `set_timeout()`.

2024-01-19 01:30 UTC, jesserockz requested changes

2024-01-19 01:30 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +    // delay(300);  // NOLINT
Lets just remove it =)
```suggestion
```

2024-01-19 02:29 UTC, clydebarrow commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +    // delay(300);  // NOLINT
Well, I tested without it and it works, on my display at least. That code is used by other displays, but the `wait_until_idle()` should take care of things.

2024-01-19 03:10 UTC, jesserockz approved these changes

2024-01-19 03:10 UTC, merged