As3935 calibration
OttoWinter/esphomeyaml pull request #5366
Opened 2023-09-08 14:59 UTC by mveinot

# What does this implement/fix?

Pick-up feature started in https://github.com/esphome/esphome/pull/2084/files (implement antenna calibration and tuning for the AS3935 lightning detector) and attempt to bring them inline with requested changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

https://github.com/esphome/esphome/pull/2084

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
as3935_spi:
  cs_pin: GPIO5
  irq_pin:
    number: GPIO15
    mode: INPUT_PULLDOWN
  indoor: False
  noise_level: 2
  spike_rejection: 5      # Default 2
  lightning_threshold: 1
  mask_disturber: False
  div_ratio: 0
  capacitance: 2
  watchdog_threshold: 2
  tune_antenna: False
  calibration: True
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-04 12:19 UTC, drawgas commented on esphome/components/as3935/as3935.cpp
> +  ESP_LOGI(TAG, "Displaying oscillator on INT pin. Measure its frequency - multiply value by DivisionRatio");
Neet picking, but `DivisionRatio` => `Division Ratio`

2023-10-04 14:52 UTC, mveinot commented on esphome/components/as3935/as3935.cpp
> +  ESP_LOGI(TAG, "Displaying oscillator on INT pin. Measure its frequency - multiply value by DivisionRatio");
Fix applies

2023-10-06 09:40 UTC, drawgas approved these changes
Looks good to me

2023-10-08 21:07 UTC, jesserockz requested changes

2023-10-08 21:07 UTC, jesserockz commented on esphome/components/as3935/as3935.cpp
> +  }
This "work" should not be done in `dump_config`, as per the name, its for dumping config, not for performing functions. This should be moved to `setup`

2023-10-09 12:21 UTC, mveinot commented on esphome/components/as3935/as3935.cpp
> +  }
Makes perfect sense, moved it.

2023-10-12 01:27 UTC, jesserockz approved these changes

2023-10-12 01:27 UTC, merged