Update DSMR to support Lithuania meeters.
OttoWinter/esphomeyaml pull request #5395
Opened 2023-09-15 12:22 UTC by geduxas

# What does this implement/fix?

Adds Lithuanian meeter support. For a while it will not work, because in Lithuania meter's Volts and Amps are represent as KiloVolt's and KiloAmps, local energy copmany have confirmed that it will be changed ASAP. So not to break compatibility i will leav Volt's and Amp's untoched.

Also it's changed UNIT_KILOVOLT_AMPS_REACTIVE to UNIT_VOLT_AMPS_REACTIVE, becouse HomeAssistnat don't have kVAr value, but it have var to represent Volt amp reactive. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```yaml

substitutions:
  device_name: slimmelezer
  friendly_name: DSMR Reader

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: ${friendly_name} Energy Delivered Tariff 1
      state_class: total_increasing
#    energy_delivered_tariff2:
#      name: ${friendly_name} Energy Delivered Tariff 2
#      state_class: total_increasing
    energy_returned_tariff1:
      name: ${friendly_name} Energy Returned Tariff 1
#    energy_returned_tariff2:
#      name: ${friendly_name} Energy Returned Tariff 2
    reactive_energy_delivered_tariff1:
        name: ${friendly_name} Reactiver Power Delivered 1
    reactive_energy_returned_tariff1:
        name: ${friendly_name} Reactiver Power Returned 1
    power_delivered:
      name: ${friendly_name} Power Consumed
      accuracy_decimals: 3
    power_returned:
      name: ${friendly_name} Power Returned
      accuracy_decimals: 3
    electricity_failures:
      name: ${friendly_name} Electricity Failures
      icon: mdi:alert
    electricity_long_failures:
      name: ${friendly_name} Electricity Long Failures
      icon: mdi:alert
    voltage:
      name: ${friendly_name} Voltage
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_l1:
      name: ${friendly_name} Voltage L1
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_avg_l1:
      name: ${friendly_name} Voltage average L1
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_l2:
      name: ${friendly_name} Voltage L2
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_avg_l2:
      name: ${friendly_name} Voltage average L2
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_l3:
      name: ${friendly_name} Voltage L3
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    voltage_avg_l3:
      name: ${friendly_name} Voltage average L3
      unit_of_measurement: "V"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_l1:
      name: ${friendly_name} Current L1
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_fuse_l1:
      name: ${friendly_name} Current L1
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_l2:
      name: ${friendly_name} Current L2
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_fuse_l2:
      name: ${friendly_name} Current L2
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_l3:
      name: ${friendly_name} Current L3
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters: 
        multiply: 1000
    current_fuse_l3:
      name: ${friendly_name} Current L3
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current:
      name: ${friendly_name} Current
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_n:
      name: ${friendly_name} Current N
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    current_sum:
      name: ${friendly_name} Current sum
      unit_of_measurement: "A"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    power_delivered_l1:
      name: ${friendly_name} Power Delivered L1
    power_delivered_l2:
      name: ${friendly_name} Power Delivered L2
    power_delivered_l3:
      name: ${friendly_name} Power Delivered L3
    power_returned_l1:
      name: ${friendly_name} Power Returned L1
    power_returned_l2:
      name: ${friendly_name} Power Returned L2
    power_returned_l3:
      name: ${friendly_name} Power Returned L3
    apparent_delivery_power:
      name: ${friendly_name} Apparent Power Deliverd
      filters:
        multiply: 1000
    apparent_delivery_power_l1:
      name: ${friendly_name} Apparent Power Deliverd L1
      filters:
        multiply: 1000
    apparent_delivery_power_l2:
      name: ${friendly_name} Apparent Power Deliverd L2
      filters:
        multiply: 1000
    apparent_delivery_power_l3:
      name: ${friendly_name} Apparent Power Deliverd L3
      filters:
        multiply: 1000
    apparent_return_power:
      name: ${friendly_name} Apparent Power Returned 
      filters:
        multiply: 1000
    apparent_return_power_l1:
      name: ${friendly_name} Apparent Power Returned L1
      filters:
        multiply: 1000
    apparent_return_power_l2:
      name: ${friendly_name} Apparent Power Returned L2
      filters:
        multiply: 1000
    apparent_return_power_l3:
      name: ${friendly_name} Apparent Power Returned L3
      filters:
        multiply: 1000
    active_demand_power:
      name: ${friendly_name} Active Demand Avg3
#    active_demand_net:
#      name: ${friendly_name} Active Demand Avg3 Net
    active_demand_abs:
      name: ${friendly_name} Active Demand Avg3 Absolute 
    reactive_power_delivered_l1:
      name: ${friendly_name} Reactive Power Delivered L1
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    reactive_power_delivered_l2:
      name: ${friendly_name} Reactive Power Delivered L2
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    reactive_power_delivered_l3:
      name: ${friendly_name} Reactive Power Delivered L3
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    reactive_power_returned_l1:
      name: ${friendly_name} Reactive Power Returned L1
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    reactive_power_returned_l2:
      name: ${friendly_name} Reactive Power Returned L2
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    reactive_power_returned_l3:
      name: ${friendly_name} Reactive Power Returned L3
      unit_of_measurement: "var"
      accuracy_decimals: 0
      filters:
        multiply: 1000
    active_energy_import_current_average_demand:
      name: ${friendly_name} Active Average Recive Demand
    active_energy_export_current_average_demand:
      name: ${friendly_name} Active Average Export Demand
    reactive_energy_import_current_average_demand:
      name: ${friendly_name} Reactive Average Recive Demand
    reactive_energy_export_current_average_demand:
      name: ${friendly_name} Reactive Average Export Demand
    apparent_energy_import_current_average_demand:
      name: ${friendly_name} Apparent Average Recive Demand
      filters: [...]

2023-09-20 21:50 UTC, jesserockz commented on esphome/components/dsmr/sensor.py
> +            unit_of_measurement=UNIT_VOLT_AMPS_REACTIVE,
Changing the units here becomes a breaking change...
Were they always wrong or did the source unit change?

2023-09-21 03:56 UTC, geduxas commented on esphome/components/dsmr/sensor.py
> +            unit_of_measurement=UNIT_VOLT_AMPS_REACTIVE,
No, i tried to adopt it to HomeAssistant unit's. In HomeAssistant there is no kVAr, for reactive power there is only VAr. So with kVar it can't be to added to class. So it's need to change it here, or add in HomeAssistant. If it makes problems i will revert it back to kVAr.

2023-09-23 18:18 UTC, geduxas commented
Hey @glmnet, @zuidwijk, I appreciate your hard work, and truly know that reviewing is intensive task, but would be glad if someone of you review my merge request, and maybe give any comments ;) I am very happy that @glmnet have already included  bunch of code to support Lithuanian power meters, but without extending esphome, it only takes half of work. Also  @zuidwijk, i have added sample configuration to your repo. If you could review that too and add to slimmelezer project, and that will be mostly finished.

2023-09-23 18:20 UTC, geduxas commented on esphome/components/dsmr/sensor.py
> +            unit_of_measurement=UNIT_VOLT_AMPS_REACTIVE,
@jesserockz what do you think, will this change bring problems to most of users? I could revert it back before this change are not merged to main project.

2023-10-05 06:27 UTC, tomaziss commented
Hi @glmnet,@zuidwijk, whole LT smart home comunity is egerly waiting for this. We would appreciate your time reviewing and helping this to be finally shipped. Thanks again!

2023-10-07 12:31 UTC, geduxas commented
> Hi @glmnet,@zuidwijk, whole LT smart home comunity is egerly waiting for this. We would appreciate your time reviewing and helping this to be finally shipped. Thanks again!

For a while, feel free to use build from my repository
https://github.com/geduxas/esphome-dsmr-eso

It will add additional dsmr-eso component to esphome.

2023-10-23 19:51 UTC, jesserockz commented on esphome/components/dsmr/sensor.py
> +            unit_of_measurement=UNIT_VOLT_AMPS_REACTIVE,
I think that HA needs to be updated to support kVAr in the reactive_power class. It has other k- units so this should not be any different.

If you just change the unit, but the actual value is still kVAr, then the value is going to be off by 1000x

2023-10-23 19:56 UTC, geduxas commented on esphome/components/dsmr/sensor.py
> +            unit_of_measurement=UNIT_VOLT_AMPS_REACTIVE,
I agree :) someone is willing to do that?

2023-11-03 21:59 UTC, geduxas commented
@glmnet, @zuidwijk, @OttoWinter, is there any problem's with this pr?

2023-12-11 19:42 UTC, grambas commented
Any update about this PR? Do you need guys some help or more info? Is there any TODOs?

2023-12-14 05:25 UTC, jesserockz requested changes

2023-12-14 05:25 UTC, jesserockz commented on esphome/components/dsmr/__init__.py
> +    cg.add_library("glmnet/Dsmr", "0.9")
The version needs to be also bumped in `/platformio.ini`

2023-12-14 05:25 UTC, jesserockz commented on esphome/components/dsmr/sensor.py
> -            state_class=STATE_CLASS_TOTAL_INCREASING,
Why is this removed?

2023-12-14 05:25 UTC, jesserockz commented on esphome/components/dsmr/sensor.py
> +            device_class=DEVICE_CLASS_ENERGY,
`state_class=STATE_CLASS_TOTAL_INCREASING,` should be added to these too

2023-12-14 08:43 UTC, geduxas commented on esphome/components/dsmr/__init__.py
> +    cg.add_library("glmnet/Dsmr", "0.9")
I am not quiet sure why it should be in ```/platformio.ini``` at all? Could you help me understand that?

2023-12-14 08:45 UTC, geduxas commented on esphome/components/dsmr/sensor.py
> -            state_class=STATE_CLASS_TOTAL_INCREASING,
Good question, i relay know what it does, but don't remember now why i have done that.. it should be reason :) will try  dig it out..

2023-12-14 08:47 UTC, geduxas commented
> Any update about this PR? Do you need guys some help or more info? Is there any TODOs?

@grambas no rush for while.. ESO still didn't fix kV, kA values for volts ant amperes.. so if it will be added in release it still will not work for Lithuania.. ESO has confirmed to me that it should be fixed in 2023.Q4 .. but as today it still in kV and kA. Truly without volt's and amp's its possible to use.

2023-12-15 13:05 UTC, geduxas commented on esphome/components/dsmr/sensor.py
> +            unit_of_measurement=UNIT_VOLT_AMPS_REACTIVE,
@jesserockz should i revert var back to kvar for this PR ?

2023-12-18 23:36 UTC, jesserockz commented on esphome/components/dsmr/__init__.py
> +    cg.add_library("glmnet/Dsmr", "0.9")
The platformio.ini file is used for CI and local development

2023-12-19 04:50 UTC, geduxas commented on esphome/components/dsmr/__init__.py
> +    cg.add_library("glmnet/Dsmr", "0.9")
Ok, i didn't know that it is important :) reaolved almost all suggestions, only kvar>var unit question is left. Stick to HA value's or revert to kvar?

2023-12-19 05:31 UTC, jesserockz commented on esphome/components/dsmr/sensor.py
> +            unit_of_measurement=UNIT_VOLT_AMPS_REACTIVE,
Yes please

2023-12-19 08:40 UTC, geduxas commented on esphome/components/dsmr/sensor.py
> +            unit_of_measurement=UNIT_VOLT_AMPS_REACTIVE,
Ok, anything else i can do?

2024-03-08 08:53 UTC, geduxas reviewed
Is it good now?

2024-05-10 06:06 UTC, closed without merging