add support for Tuya pink version of miflora
OttoWinter/esphomeyaml pull request #5402
Opened 2023-09-17 10:20 UTC by fariouche

# What does this implement/fix?
Hello.
Added support for new miflora Pink (Tuya version) of the sensor.
This version is not compatible with the xiaomi version (white and green) and is using a BLE5.0 chip.
This is a simple component, tested and working (I have 3).
Parsing is inspired by the openmqttgateway (theengs decoder)
The code name is hhccjcy10 (see the last number is not 01 as the old one)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
 - platform: xiaomi_hhccjcy10
    mac_address: 'xx:xx:xx:xx:xx:xx'
    temperature:
      name: "S6 Temperature"
    moisture:
      name: "S6 Moisture"
    illuminance:
      name: "S6 Illuminance"
    conductivity:
      name: "S6 Soil Conductivity"
    battery_level:
      name: "S6 Battery Level"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-17 10:40 UTC, fariouche commented
what do you think?

2023-12-18 03:41 UTC, jesserockz requested changes
> what do you think?

Code looks fine on quick glance, but PRs with failing CI, or labels like `needs-docs` or `needs-tests` dont usually get reviewed until resolved =)

2023-12-18 09:31 UTC, fariouche commented
oh I see, thanks. I will check the docs and tests then thanks

2023-12-18 10:31 UTC, fariouche commented
All green now :smile: 
Thanks!

2023-12-18 23:33 UTC, jesserockz requested changes

2023-12-18 23:33 UTC, jesserockz commented on esphome/components/xiaomi_hhccjcy10/sensor.py
> +AUTO_LOAD = ["xiaomi_ble"]
As this doesnt use the xiaomi_ble code, this is not required (paired with below removal too)
```suggestion
```

2023-12-18 23:33 UTC, jesserockz commented on esphome/components/xiaomi_hhccjcy10/xiaomi_hhccjcy10.h
> +#include "esphome/components/xiaomi_ble/xiaomi_ble.h"
Not used
```suggestion
```

2023-12-18 23:33 UTC, jesserockz commented on esphome/components/xiaomi_hhccjcy10/sensor.py
> +        cg.add(var.set_temperature(sens))
Please alter these to use this method of checking
```suggestion
    if temperature_config := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_config)
        cg.add(var.set_temperature(sens))
```

2023-12-18 23:33 UTC, jesserockz commented on esphome/components/xiaomi_hhccjcy10/xiaomi_hhccjcy10.cpp
> +    this->temperature_->publish_state((float) temperature / 10.0f);
These need to be checked that the user actually configured them
```suggestion
    if (this->temperature_ != nullptr) {
      const int16_t temperature = encode_uint16(data[1], data[2]);
      this->temperature_->publish_state((float) temperature / 10.0f);
    }
```

2023-12-18 23:33 UTC, jesserockz commented on esphome/components/xiaomi_hhccjcy10/xiaomi_hhccjcy10.h
> +  void set_address(uint64_t address) { address_ = address; }
Member variables and function calls need to all be prefixed with `this->`
```suggestion
  void set_address(uint64_t address) { this->address_ = address; }
```

2024-01-05 14:15 UTC, fariouche commented on esphome/components/xiaomi_hhccjcy10/xiaomi_hhccjcy10.h
> +  void set_address(uint64_t address) { address_ = address; }
done

2024-01-05 14:15 UTC, fariouche commented on esphome/components/xiaomi_hhccjcy10/xiaomi_hhccjcy10.cpp
> +    this->temperature_->publish_state((float) temperature / 10.0f);
done

2024-01-05 14:15 UTC, fariouche commented on esphome/components/xiaomi_hhccjcy10/sensor.py
> +        cg.add(var.set_temperature(sens))
done

2024-01-05 14:15 UTC, fariouche commented on esphome/components/xiaomi_hhccjcy10/xiaomi_hhccjcy10.h
> +#include "esphome/components/xiaomi_ble/xiaomi_ble.h"
done

2024-01-05 14:15 UTC, fariouche commented on esphome/components/xiaomi_hhccjcy10/sensor.py
> +AUTO_LOAD = ["xiaomi_ble"]
done

2024-02-17 12:17 UTC, fariouche commented
Hello, any news?

2024-02-18 18:59 UTC, jesserockz approved these changes

2024-04-08 22:17 UTC, merged