Speed up (and fix) ili9xxx display component.
OttoWinter/esphomeyaml pull request #5406
Opened 2023-09-18 11:53 UTC by clydebarrow

# What does this implement/fix?

* Improve the update speed of the ili9xxx display driver, for 16 bit colour at least (should also be some improvement for 8 bit.) Speed in 16 bit mode is roughly tripled (full screen write reduced from 120ms to 40ms @ 40MHz SPI.)
* 
* Fix a bug in `display.py` that meant use of `color_palette: GRAYSCALE` did not build.

Tested on [this display](https://protosupplies.com/product/tft-lcd-3-2-240x320-rgb-spi-display-with-touchscreen/) in 16 bit and 8 bit modes (Grayscale and image adaptive). Not tested on an 18 bit display since I don't have one.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Other

## Test Environment

- [x] ESP32
- [x] ESP32 IDF

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
time:
  - platform: sntp
    id: ntp

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  interface: hardware

font:
  - file: "gfonts://Roboto"
    id: roboto_40
    size: 40
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz@'

output:
  - platform: ledc
    pin: 32
    id: gpio_32_backlight_pwm

# Define a monochromatic, dimmable light for the backlight
light:
  - platform: monochromatic
    output: gpio_32_backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON

display:
  - platform: ili9xxx
    model: ili9341
    dc_pin: GPIO22
    reset_pin: GPIO21
    cs_pin: GPIO5
    rotation: 90
    update_interval: 1s
    lambda: |-
      it.print(0, 0, id(roboto_40), Color(0, 255, 0), "Hello World!");
      it.print(0, 86, id(roboto_40), Color(255, 0, 0), "Hello @esphome_!");
      it.strftime(120, 200, id(roboto_40), TextAlign::BASELINE_LEFT, "%H:%M:%S", id(ntp).now());
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

2023-09-18 12:13 UTC, nielsnl68 requested changes
Looks good indeed.
I have just 2 questions below.

2023-09-18 12:13 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
> -        cg.add(var.set_palette(prog_arr))
Why did you remove this?

2023-09-18 12:13 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +  set_addr_window_(0, this->y_low_, this->width_ - 1, this->y_high_);
why did you removed the width window here?

2023-09-18 12:16 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> -        cg.add(var.set_palette(prog_arr))
It was a duplicate, and caused a compile time error due to the same id being defined twice.

2023-09-18 12:20 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +  set_addr_window_(0, this->y_low_, this->width_ - 1, this->y_high_);
By ignoring the min/max x values and just updating full lines it's possible to do a single SPI write of the modified part of the buffer. The speedup due to eliminating SPI transaction setup overhead more than compensates for the possible redundant data being written.

2023-09-18 12:24 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> -        cg.add(var.set_palette(prog_arr))
Lines 178-180 are executed for both GRAYSCALE and ADAPTIVE mode.

2023-09-19 09:35 UTC, nielsnl68 requested changes
Although your idea of doing bulk writes is nice at first I think it is only useful with small display's but not when we use bigger display's.
I suggest to update the `pos` for every row you send to the display. 
Like the examples below.

2023-09-19 09:35 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
> -        cg.add(var.set_palette(prog_arr))
Oww that is a good find 👍🏻

2023-09-19 09:35 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +  set_addr_window_(0, this->y_low_, this->width_ - 1, this->y_high_);
```suggestion
  set_addr_window_(this->x_low_, this->y_low_, this->x_high_, this->y_high_);
```

2023-09-19 09:35 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +  uint16_t const w = this->width_;
```suggestion
  uint16_t const w = this->x_high_ - this->x_low_ + 1;  // NOLINT
```
See reason below.

2023-09-19 09:35 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +  size_t pos = this->y_low_ * this->width_;
``` suggestion
  size_t pos = (this->y_low_ * this->width_) + this->x_low_;
```
See reason below.

2023-09-19 09:35 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +    this->write_array(this->buffer_ + pos * 2, h * w * 2);
``` suggestion
    while  (rem-- != 0) {
       this->write_array(this->buffer_ + pos * 2,  w * 2);
       pos = pos + this->width_;
       rem = rem - w;
    }
```

2023-09-19 09:35 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
>        }
``` suggestion
      }
      if ( idx % w == 0) {
         pos = pos + (this->width_ - this->x_high_) + this->x_low_;
      }

2023-09-19 10:06 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.cpp
>        }
That won't work - `idx` is an index into the transfer buffer, not the display buffer. It will need another variable to track the position in the display buffer.

2023-09-19 10:13 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.cpp
>        }
So I applied your suggestions (with another variable) and it crashes (watchdog timeout.)

2023-09-19 10:39 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
>        }
Can you commit the changes, so i can see where it did go wrong.

2023-09-19 11:06 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.cpp
>        }
Sure but here are some benchmark numbers to consider - I fudged your code enough to send each line separately, so even though the display is wrong, the timing will be the same. This is on a 320 pixel wide display  - not sure what you consider a "bigger" display. 

I tested two scenarios - full screen redraw (always the case unless `auto_clear_enabled` is set to `false`) and toggling a 40x40 pixel rectangle - so a tiny part of the whole screen changed.

#### My PR as it stands:

Full screeen redraw: 47ms
40x40 redraw:           6ms (12800 pixels transmitted.)

#### Line by line as per your suggestion:

Full screen redraw: 185ms
40x40 redraw: 5ms (1600 pixels transmitted)

So there is only a small saving when very small areas are redrawn (and the time then is going to be small anyway) and a huge hit when bigger areas are redrawn.  This is due to the relatively high overhead of starting an SPI transaction.

Now bear in mind that even if only small areas of the screen are redrawn, the full bounding box of the changes is redrawn, so two small changes on opposite sides of the screen mean nearly the entire width is considered to have changed.

So there will be some very special cases where there is a small benefit to going line-by-line but in my opinion a typical use-case is likely to see worse performance, not better.

So I'm happy to commit your suggestions for you to debug (it won't even compile as it stands) but at this point I don't believe it's worth the effort.

2023-09-19 11:08 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.cpp
>        }
Those numbers BTW are just the execution time of `void ILI9XXXDisplay::display_()` - I added test code to measure duration using `millis()`.

2023-09-19 11:15 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.cpp
>        }
Oh, and the actual display is 240 wide, not 320 (I have it rotated 90 degrees :-) So on a wider display there will be more benefit to line by line, but large areas will still suffer greatly.

2023-09-19 11:39 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +    this->write_array(this->buffer_ + pos * 2, h * w * 2);
oeps, a bit to hasty copy past there:
```c++
  while  (rem != 0) {
```

and maybe add a `App.feed_wdt();` in the while loop as well ;)

2023-09-19 11:59 UTC, nielsnl68 requested changes

2023-09-19 11:59 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +    while  (rem-- != 0) {
Oeps my mistake to hasty with copy paste here

```suggestion
    while  (rem != 0) {
       App.feed_wdt();
```

2023-09-19 11:59 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +  set_addr_window_(this->x_low_, this->y_low_, this->x_high_, this->y_high_);
```suggestion
  set_addr_window_(this->x_low_, this->y_low_, this->x_high_, this->y_high_);
  size_t rem = h * w;  // remaining number of pixels to write
```

2023-09-19 11:59 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +    size_t rem = h * w;  // remaining number of pixels to write
```suggestion
```

2023-09-19 11:59 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.cpp
>        }
cool test. Not so cool results :(

> This is on a 320 pixel wide display - not sure what you consider a "bigger" display.
480x320 and more. like the ili93488 or ili93486 displays

Can we talk about this on discord later just DM me and i will comeback to you when i have time later today. My name is the same as here.

2023-09-19 12:05 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.cpp
> +    this->write_array(this->buffer_ + pos * 2, h * w * 2);
You didn't try compiling did you?

```
src/esphome/components/ili9xxx/ili9xxx_display.cpp:194:13: error: 'rem' was not declared in this scope; did you mean 'drem'?
```

With all due respect, I'm not inclined to try to apply major changes that you haven't even built or tested, especially when I believe the end result will be inferior to what I have proposed. I'm going to revert the suggestions, happy to consider further suggestions if well-founded.

2023-09-19 12:20 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.cpp
>        }
Bedtime for me now, could not find you on discord. I'm cly_de_barrow (discord reserves Clyde for its AI bot apparently.)

2023-09-19 20:07 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.cpp
>        }
So here's how I see it:

* my code as it stands is faster than the existing implementation in _all_ cases, _much_ faster in most cases.
* It would nonetheless be possible to improve the speed for updates with narrow widths;
* The problem is that there is over 100µs of setup time for each SPI transaction (see scope capture below)
* To speed up narrow updates without ruining the general case will require a run-time adaptation choosing between different approaches;
* The complexity of that means significant time to implement and test, which I don't have.

So, I suggest going with the PR as is (preferably after finding someone to test the 18 bit display case) and if anyone has the time and motivation to improve it even further they can do so.



![scope_1 copy](https://github.com/esphome/esphome/assets/2366188/90ae4a3a-2e05-4ae7-96c8-45baa2a30465)

2023-09-19 22:58 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.cpp
>        }
And a few more numbers for larger displays (tested timing only, not functionality). Partial updates are 40 pixels wide, 200 lines high. Times in ms for `ILI9XXXDisplay::display_()`.
```
                                  dev branch                    PR
                               full       partial        full      partial
ILI9486 (480x320, 16 bit).      338           23          96         58
ILI9488 (480x320, 18 bit)      7400          410         417        262
```

So for 18 bit the improvement is major for all cases. For 16 bit the worst case is much better, best case still fast enough that any improvement is unlikely to be noticeable.

2023-09-26 21:43 UTC, jesserockz commented on esphome/components/ili9xxx/display.py
> -        cg.add(var.set_palette(prog_arr))
@clydebarrow Can you put this fix into its own pr so I can pull into the beta and release today?

2023-09-26 22:40 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> -        cg.add(var.set_palette(prog_arr))
https://github.com/esphome/esphome/pull/5433

2023-11-15 18:35 UTC, jesserockz commented on esphome/components/ili9xxx/display.py
> +            cv.Optional(CONF_HEIGHT): cv.int_,
This should be like this
```suggestion
            cv.Optional(CONF_DIMENSIONS): cv.Any(
                cv.dimensions,
                cv.Schema({
                    cv.Optional(CONF_WIDTH): cv.int_,
                    cv.Optional(CONF_HEIGHT): cv.int_,
                }),
            ),
```

2023-11-15 22:50 UTC, nielsnl68 requested changes

2023-11-15 22:50 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
> +            mad |= 0x20
I prefer that is done in the class it self, not all drivers could work the same way.

2023-11-15 22:50 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
> +CONF_OFFSET_WIDTH = "offset_width"
```suggestion
CONF_OFFSET_y= "offset_x"
CONF_OFFSET_Y = "offset_y"
```

2023-11-15 22:50 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
> +)
I do not see the real need to move this into it own section, all the other settings are basicly for the panel as well.

2023-11-15 22:50 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
> +            cv.Optional(CONF_OFFSET_WIDTH, default=0): cv.int_,
```suggestion
            cv.Optional(CONF_OFFSET_X, default=0): cv.int_,
            cv.Optional(CONF_OFFSET_Y, default=0): cv.int_,
```

2023-11-15 22:50 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
> +    cg.add(var.set_offsets(config[CONF_OFFSET_WIDTH], config[CONF_OFFSET_HEIGHT]))
```suggestion
    cg.add(var.set_offsets(config[CONF_OFFSET_X], config[CONF_OFFSET_Y]))
```

2023-11-16 00:37 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> +            mad |= 0x20
This is correct for all the currently supported devices. If something different is required in the future then it should be able to be handled in Python anyway. I am of the understanding from earlier discussions that it is preferred that as much setup-time configuration as possible should be handled in the Python code - is that correct @jesserockz ?

2023-11-16 00:37 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> +            cv.Optional(CONF_HEIGHT): cv.int_,
Fixed in next push.

2023-11-16 00:40 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> +CONF_OFFSET_WIDTH = "offset_width"
While `x` and `y` are probably more technically correct descriptions, maintaining the naming correspondence with the dimension values make sense to me, and  matches what was done in the st7789v driver. I don't think there is any chance of it being misinterpreted.

2023-11-16 00:46 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> +)
Each chip init sequence already sets these values to something. By making the entire group optional, the default values magically coded in the initialisation sequence will remain if the group is absent, otherwise it will be overridden by these settings, even the defaults. If the inner values were moved to the outer schema, they could not have default values since it would be necessary to test if any of them were user-specified.

2023-11-16 02:26 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> +)
Another option would be to move the swap/mirror options under `rotation:` instead (and move `color_order` to the top level.) So it would look like this:

```
    color_order: bgr
    rotation:
      mirror_x: true
      mirror_y: true
      swap_xy: false
```
Alternatively
```
    rotation: 90
```
And that would be mapped to `swap_xy` and `mirror_x` (I think - have to confirm the correct combinations.)

This would eliminate the need for software rotation.

2023-11-16 11:51 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> +            mad |= 0x20
I have moved this config into the CPP code. for various reasons it made sense.

2023-11-16 11:51 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> +)
I've gone with the latter option.

2023-11-16 14:40 UTC, nielsnl68 requested changes

2023-11-16 14:40 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
>      "M5STACK": ili9XXX_ns.class_("ILI9XXXM5Stack", ili9XXXSPI),
I do not know if i missed up here: but `ili9xxxSPI` should be `ILI9XXXDisplay` i think.

2023-11-24 03:34 UTC, jesserockz requested changes
Can you split the power supply stuff into a separate PR?

2023-11-24 03:34 UTC, jesserockz commented on esphome/components/ili9xxx/ili9xxx_display.h
> +#endif
Not needed anymore?

2023-11-24 04:05 UTC, jesserockz commented on esphome/components/ili9xxx/display.py
> +
The `config` dict is not a place to add new keys to during a validation to use later. It should only set keys that are part of the schema already.

For example, if `rotation` has potential to be an object, then this validation should set the values inside the object, not on the top level config.

2023-11-24 04:16 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> +
The problem is that the top-level `display` component expects CONF_ROTATION, if present, to be a scalar value. The only alternative I can think of is to move the sub-schema options (`SWAP_XY` etc) under a different key (`transform:` ?) and make it exclusive with ROTATION.

2023-11-24 04:21 UTC, clydebarrow commented on esphome/components/ili9xxx/display.py
> +
And the problem with that is that specifying `rotation` would not then map to the flags necessary to set up hardware rotation. That would have to be moved into the C++ code.

Or I could disallow use of `rotation` completely and just allow `transform` with appropriate documentation.

2023-11-24 06:47 UTC, jesserockz commented on esphome/components/ili9xxx/display.py
> +                "invert_display is deprecated - use invert_colors "
```suggestion
                "'invert_display' has been removed - please use 'invert_colors'"
```

2023-11-24 06:47 UTC, jesserockz commented on esphome/components/ili9xxx/display.py
> +
Having a CONF_TRANSFORM that is exclusive with CONF_ROTATION would be fine.

2023-11-27 23:50 UTC, jesserockz approved these changes
LGTM

2023-11-28 00:42 UTC, merged