Feat/component poller suspend
OttoWinter/esphomeyaml pull request #5423
Opened 2023-09-24 12:29 UTC by xdecock

# What does this implement/fix?

This mr aims at allowing suspend / resume of polling component update, this is mainly in place to help out with "slow component" when managing audio interractions.

PS: I'm doing the test locally, trying to setup the test env, i'll tick off box as soon as it's done

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2301

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3205

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-09-24 15:07 UTC, nagyrobi commented
Would it be possible to start the poller in suspended state at boot?

The use case is, for example having to wait for a slave device to start up (as it's slower than the esp), before starting to poll it.

2023-09-24 15:21 UTC, xdecock commented
> Would it be possible to start the poller in suspended state at boot?
> 
> The use case is, for example having to wait for a slave device to start up (as it's slower than the esp), before starting to poll it.

I thought about that, and imo, the most elegant way to do that, would be to add an action:
```yaml
  component.set_update_interval;
    id: component_id
    interval: xxxs
```

This mr do allow to "dynamically update the interval" 

The only thing i did not understand is how to create an action with that template.

That being, said, if i'm guided about how to implement those type of actions, i would probably do it as a separate pull request.

I'd then solve this exact scenario this way:
```
fast_component:
  id: fc_id
  update_interval: never
  
slow_component:
  id: sc_id
  on_startup:
    - component.set_interval:
      id: fc_id
      update_interval: 5s 
      resume: false #not sure about this or the next line
    - component.resume: fc_id
```

2023-09-24 21:14 UTC, jesserockz commented
Instead of another action to change the interval, you could add an `Optional` config item to the `start` action for `update_interval`

2023-09-25 02:35 UTC, xdecock commented
> Instead of another action to change the interval, you could add an `Optional` config item to the `start` action for `update_interval`

So more something in the vein of

```yaml
component.resume:
  id: fc_id
  update_interval: 3s
```

An extreme version would allow to merge those two actions via

```yaml
component.set_update_interval:
  id: fc_id
  update_interval: never

component.set_update_interval:
  id: fc_id
  update_interval: 5s

# possible helpers
component.set_update_interval:
  id: fc_id
  action: suspend

component.set_update_interval:
  id: fc_id
  action: resume
```

If this would work, i'd be happy with a pointer to the correct class to declare the correct structure in python, I'm quite happy to update my mr but i'm struggling a bit to find how things work.

2023-09-25 09:02 UTC, xdecock commented
Fast tentative,

I'll debug it later today if it doesn't work, if the logic is sound, i'll redo my local tests, and update the documentation accordingly

2023-09-25 15:45 UTC, xdecock commented
Updated the example, seems it works correctly on my local devices. i've struggled a bit to understand the code generation logic, so i'm happy with any correction i might have to do

2023-09-29 01:03 UTC, jesserockz requested changes

2023-09-29 01:03 UTC, jesserockz commented on esphome/automation.py
> +            cv.Optional(CONF_UPDATE_INTERVAL): cv.positive_time_period_milliseconds,
In the cpp class you define this as `templatable`, but the config side does not allow the use of a lambda to set.
```suggestion
            cv.Optional(CONF_UPDATE_INTERVAL): cv.templatable(cv.positive_time_period_milliseconds),
```

This also needs some changes in function to match

2023-09-29 13:06 UTC, xdecock commented on esphome/automation.py
> +            cv.Optional(CONF_UPDATE_INTERVAL): cv.positive_time_period_milliseconds,
Updated, along side the test it runs as (i) expected it to work

2023-09-29 13:12 UTC, xdecock commented
> Would it be possible to start the poller in suspended state at boot?
> 
> The use case is, for example having to wait for a slave device to start up (as it's slower than the esp), before starting to poll it.

this is now possible by starting with update_interval: never, and doing a component.resume when the slow component booted up, and set the interval with the resume action

2023-10-02 20:20 UTC, jesserockz approved these changes

2023-10-02 20:25 UTC, merged