Adding display features
OttoWinter/esphomeyaml pull request #5436
Opened 2023-09-27 12:30 UTC by clydebarrow

# What does this implement/fix?

Some display improvements that should have no impact on existing code, but will facilitate further enhancements.

This is a draft PR for further discussion.

* Hoist `PollingComponent` out of individual display classes and make it a parent class of `DisplayBuffer`. All existing display components already implement this so no breaking change.
* Add a new function to allow potentially efficient drawing of multiple pixels. The default implementation will work for all displays but is slow, but can be overridden by individual components (with knowledge of buffer format) to optimise this procedure.

The second change is aimed at efficient implementation of the LVGL display interface. This has been tested with LVGL.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-09-27 12:32 UTC, clydebarrow commented
This is a sample implemention of the draw function for ili9xx. Runs  5-10 times faster than the reference implementation (for 16 bit colour.)

```
void ILI9XXXDisplay::draw_pixels_in_window(int x_start, int y_start, int w, int h, const uint8_t *ptr,
                                           display::ColorOrder order, display::ColorBitness bitness, bool big_endian) {
  if (bitness != display::COLOR_BITNESS_565 || order != display::COLOR_ORDER_RGB) {
    DisplayBuffer::draw_pixels_in_window(x_start, y_start, w, h, ptr, order, bitness, big_endian);
    return;
  }

  ESP_LOGD(TAG, "copy with rotation %d degrees", (int) this->rotation_);
  switch (this->rotation_) {
    case display::DISPLAY_ROTATION_0_DEGREES: {
      size_t start = (y_start * this->width_ + x_start) * 2;
      for (int y = y_start; y != y_start + h; y++) {
        memcpy(this->buffer_ + start, ptr, w * 2);
        ptr += w * 2;
        start += w * 2;
      }
      return;
    }
    case display::DISPLAY_ROTATION_180_DEGREES: {
      for (int py = 0; py != h; py++) {
        for (int px = 0; px != w; px++) {
          ((uint16_t *) this
               ->buffer_)[(this->height_ - y_start - py - 1) * this->width_ + this->width_ - x_start - px - 1] =
              *(uint16_t *) ptr;
          ptr += 2;
        }
      }
      break;
    }
    case display::DISPLAY_ROTATION_90_DEGREES: {
      for (int py = 0; py != h; py++) {
        for (int px = 0; px != w; px++) {
          ((uint16_t *) this->buffer_)[(x_start + px + 1) * this->width_ - y_start - py - 1] = *(uint16_t *) ptr;
          ptr += 2;
        }
      }
      break;
    }
    case display::DISPLAY_ROTATION_270_DEGREES: {
      for (int py = 0; py != h; py++) {
        for (int px = 0; px != w; px++) {
          ((uint16_t *) this->buffer_)[(this->height_ - x_start - px) * this->width_ + y_start + py] = *(uint16_t *) ptr;
          ptr += 2;
        }
      }
      break;
    }
  }
}

```

2023-09-27 14:05 UTC, nielsnl68 commented
@clydebarrow Would it not much better and faster when the display it self handles the rotation?

2023-09-27 14:26 UTC, nielsnl68 requested changes
top work

2023-09-27 14:26 UTC, nielsnl68 commented on esphome/components/display/display_color_utils.h
> +};
Could you use the same *enum* values as used in ili9xxx?

```c++
enum ILI9XXXColorMode {
  BITS_8 = 0x08,  // would corspondent to COLOR_BITNESS_332
  BITS_8_INDEXED = 0x09,
  BITS_16 = 0x10, // would corspondent to COLOR_BITNESS_565
  BITS_18 = 0x12, // would corspondent to COLOR_BITNESS_666 (*)
  BITS_24 = 0x18, //  would corspondent to COLOR_BITNESS_888 (*)
  BITS_UNKNOWN = 0xFF, //  would corspondent to COLOR_BITNESS_UNKNOWN  (*)
};
```

2023-09-27 14:26 UTC, nielsnl68 commented on esphome/components/display/display_buffer.h
> +class DisplayBuffer : public Display, public PollingComponent {
I do like to move the `PollingComponent` to the *DisplayBuffer. But i'm not sure of this should be in this PR.

2023-09-27 14:26 UTC, nielsnl68 commented on esphome/components/display/display_buffer.h
> +  virtual void draw_pixels_in_window(int x_start, int y_start, int w, int h, const uint8_t *ptr, ColorOrder order,
Sorry, i do not think that the ColorOrder, bitness and big_endian should be handled by this function. To me it is just a Base setting that should be set by the driver it self.

2023-09-27 21:41 UTC, clydebarrow commented
> @clydebarrow Would it not much better and faster when the display it self handles the rotation?

Yes, it would. But not all drivers can handle rotation - the ili9xx series could do it easily(it's not currently implemented) but that's not going to be true for all displays. So it needs to be something implemented on a per-driver basis.

The idea would be for the upper-level (`DisplayBuffer`) to have a user-specified rotation set, and the driver to optionally provide an 'effective rotation'. If the driver can implement the rotation in hardware, then the effective rotation is set to 0 degrees. The effective rotation is what will be used by the `draw_pixel` functions to do the mapping rather than the user-specified rotation.

That's another task on top of what I'm doing here and should be a separate PR.

2023-09-27 21:43 UTC, clydebarrow commented on esphome/components/display/display_buffer.h
> +class DisplayBuffer : public Display, public PollingComponent {
Sure, that is quite separate to the other stuff, I just bundled it in because it was easy and I thought non-controversial, but could just as easily be a separate PR.

There is also the question of whether it should be in the `DisplayBuffer` or `Display` class - I have no strong opinion either way but if there's no good reason to limit it to `DisplayBuffer` then I would guess it should go at the higher level.

2023-09-27 21:45 UTC, clydebarrow commented on esphome/components/display/display_color_utils.h
> +};
Those values were already defined in `display_color_utils.h` (except `UNKNOWN`) and are used by the color conversion functions in `ColorUtils` so I did not want to rework all that code.

Currently the indexed color case is not provided for there - that's another can of worms so for now I just left it to the driver.

2023-09-27 22:00 UTC, clydebarrow commented on esphome/components/display/display_buffer.h
> +  virtual void draw_pixels_in_window(int x_start, int y_start, int w, int h, const uint8_t *ptr, ColorOrder order,
I think you misunderstand - this is not setting anything in the driver. Let me explain (at some length):

The use case for this is where there is a rendering component (i.e. LVGL) that can draw stuff into some kind of buffer. Then there is a display component that is responsible for displaying stuff on a screen. The objective is that any rendering component in ESPHome should be able to be plugged into any display component and it should Just Work. The secondary objective is that it should be _possible_ to make it not just work, but work fast, if the right choices are made, but it should never not work.

Each driver has potentially a different internal buffer layout which is unknown (and unknowable) to the rendering component.  So to make it Just Work the base case is that every pixel in the render buffer is copied, with colour translation, to the display (via `draw_pixel_at` which is implemented on a per-driver basis.) Using that mechanism, the rendering component and the display component are coupled only the notion of x-y position and colour space.

However that is going to be very slow in many cases. So the `draw_pixels_in_window` method allows the rendering component to say to the display driver 'here's a block of pixels stored in a buffer, corresponding to this display window, and this is how they are encoded. Go show it'. The default implementation in `DisplayBuffer` just falls back to the naive pixel-by-pixel implementation, but as a virtual method it can be re-implemented on a per-driver basis to make things faster.

Now if the render buffer and the display buffer use different colour encodings e.g. then there isn't much improvement that can be made, but if e.g. they both use RGB565 big-endian format, then the data can be copied straight from one buffer to another without colour conversion. Even better if the effective rotation is zero, `memcpy` can be used. That's all shown in the example implementation I posted - https://github.com/esphome/esphome/pull/5436#issuecomment-1737302151.

So the colour format information in the function call isn't setting anything in the driver - it has its own internal notion of colour encoding - but a description of how the supplied render buffer is encoded.

This means that to get the full performance a user will have to choose the right settings for both the display driver and the renderer in the YAML - but if they don't match it still works - just not as fast as it might.

I used the already-defined types from `display_color_utils.h` so that the existing colour conversion routines could be used - no sense in re-inventing the wheel.

2023-09-28 01:05 UTC, nielsnl68 approved these changes

2023-09-28 04:44 UTC, clydebarrow commented
I have removed the `PollingComponent` hoisting and will submit a separate PR - I agree with @ayufan that it should go in `Display`, but the Python code also needs work as the component registration should be handled by the display registration.
I think this is now ready to go.

2023-09-28 04:47 UTC, clydebarrow commented on esphome/components/display/display_color_utils.h
> +};
Actually the indexed case is probably never going to work as there would need to be agreement between the renderer and the display driver on the palette to be used. I think that belongs in the Too Hard basket. I expect the majority of cases to use 16 bit RGB565 big-endian so that's where the focus should be. If saving RAM by use of an 8 bit display buffer matters, then it's probably not a chip suited to running something like LVGL.

2023-09-28 08:16 UTC, nielsnl68 commented on esphome/components/display/display_buffer.h
> +        this->draw_pixel_at(x + x_start, y + y_start, ColorUtil::to_color(color_value, order, bitness));
I could not find it, but make you sure that `x + x_start` and ` y + y_start` does not go outside the display window?

2023-09-28 08:16 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.h
> +  virtual void draw_pixels_in_window(int x_start, int y_start, int w, int h, const uint8_t *ptr,
``` suggestion
   void draw_pixels_in_window(int x_start, int y_start, int w, int h, const uint8_t *ptr,
```
i belief the `virtual` is only needed the first time this method was declared

2023-09-28 08:22 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.h
> +  virtual void draw_pixels_in_window(int x_start, int y_start, int w, int h, const uint8_t *ptr,
Correct, I already fixed that.

2023-09-28 08:37 UTC, clydebarrow commented on esphome/components/display/display_buffer.h
> +        this->draw_pixel_at(x + x_start, y + y_start, ColorUtil::to_color(color_value, order, bitness));
Same way that the existing code (doesn't) ensure that -  it relies on the calling code to pass valid values. 

However looking at `draw_pixel_at` while it does not check that the x/y coords are within the display boundaries, it does check that they are within the clipping rectangle, _if one is set_. As far as I can tell the clipping rectangle is _never_ set, i.e. there are no usages of the clipping functions I can find in the code base.

Right now `get_clipping` returns an unset `Rect` if no clipping is set. It should probably instead return a rectangle representing the display limits. Want me to fix that?

In any case `draw_pixels_in_window()` should also check the clipping rectangle. I'll attend to that.

2023-09-28 14:06 UTC, nielsnl68 commented on esphome/components/display/display_buffer.h
> +        this->draw_pixel_at(x + x_start, y + y_start, ColorUtil::to_color(color_value, order, bitness));
That is right, i added the clipping future to be used with my `switchplate` component. That component was using it a lot.
Maybe we should set the default clipping regio to the screensize?

2023-09-28 20:33 UTC, clydebarrow commented on esphome/components/display/display_buffer.h
> +        this->draw_pixel_at(x + x_start, y + y_start, ColorUtil::to_color(color_value, order, bitness));
Yes, agree - shall I add that to this PR?

2023-09-28 20:52 UTC, nielsnl68 commented on esphome/components/display/display_buffer.h
> +        this->draw_pixel_at(x + x_start, y + y_start, ColorUtil::to_color(color_value, order, bitness));
yeah, i belief it is better here.

2023-12-02 20:54 UTC, closed without merging