add spi support for ade7953
OttoWinter/esphomeyaml pull request #5439
Opened 2023-09-27 18:53 UTC by angelnu

# What does this implement/fix?

Sensor ADE7953 supports multiple buses. This adds support for SPI to the existing i2c implementation.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**
- implements https://github.com/esphome/feature-requests/issues/2067
- dependency for https://github.com/esphome/feature-requests/issues/1784

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
TBD

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml for spi

sensor:
  - platform: ade7953_spi
    id: ade7953_1
    spi_id: spi_bus_1
    cs_pin: GPIO04
    irq_pin: GPIO35
    voltage:
      name: "Voltage"
      filters:
      - delta: 1
    current_a:
      name: "Current A"
      filters:
      - delta: 0.01
    current_b:
      name: "Current B"
      filters:
      - delta: 0.01
    active_power_a:
      name: "Power A"
      id: active_power_1
      # active_power is inverted, so multiply by -1
      filters:
      - multiply: -1
      - delta: 1
    active_power_b:
      name: "Power B"
      id: active_power_2
      # active_power is inverted, so multiply by -1
      filters:
      - multiply: -1
      - delta: 1
    update_interval: 1s

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-09 01:08 UTC, jesserockz requested changes
Partial review below

2023-10-09 01:08 UTC, jesserockz commented on esphome/components/ade7953_base/__init__.py
> +).extend(cv.polling_component_schema("1s"))
This needs to stay at 60 seconds default
```suggestion
).extend(cv.polling_component_schema("60s"))
```

2023-10-09 01:08 UTC, jesserockz commented on esphome/components/ade7953_base/ade7953_base.cpp
> +  ESP_LOGCONFIG(TAG, "  BWGAIN_32: 0x%08jX", (uintmax_t) val);
`dump_config` should not really be doing comms, it should only be printing out the existing configuration, or previously read data

2023-10-09 01:08 UTC, jesserockz commented on esphome/components/ade7953_base/ade7953_base.h
> +    });
What is the point of the timeout here? 
Nothing was done beforehand that would need to be waited on...

2023-10-09 01:08 UTC, jesserockz commented on esphome/components/ade7953_i2c/ade7953_i2c.h
> +  bool ade_write_8(uint16_t reg, uint8_t value) override {
Please move all of these functions into the cpp file.

2023-10-09 01:08 UTC, jesserockz commented on esphome/components/ade7953_i2c/sensor.py
> +    .extend(cv.polling_component_schema("1s"))
```suggestion
```

2023-10-09 01:08 UTC, jesserockz commented on esphome/components/ade7953_spi/sensor.py
> +    .extend(cv.polling_component_schema("1s"))
```suggestion
```

2023-10-09 01:08 UTC, jesserockz commented on esphome/components/ade7953_base/ade7953_base.h
> +  void setup() override {
Content of this should be in cpp file please.

2023-10-09 09:07 UTC, angelnu commented on esphome/components/ade7953_base/ade7953_base.h
> +    });
The chip needs up to 100ms to be ready after a reset. Since we do not always have access to the ready interrupt this is what the documentation recommends.
It was like this in the previous implementation - I can add a comment.

2023-10-09 09:15 UTC, angelnu commented on esphome/components/ade7953_base/ade7953_base.cpp
> +  ESP_LOGCONFIG(TAG, "  BWGAIN_32: 0x%08jX", (uintmax_t) val);
My intention is to provide feedback on the actual values from the registers without querying them in each sensor refresh.
I went with the dump_config as this is not called to often but I can see why it does not fit the esphome architecture.

Do you have a recommendation or should I come up with a proposal? For example, we could threat them as (optional) sensors even if they do not change often. Another option would be to read the value on setup only but then if the chip gets reset they actual values might have changed.

My feeling is that just covering them as sensors is good enough. They are only required for initial debugging really so most configs do not need to include them as sensors.

WDYT?

2023-10-09 09:23 UTC, angelnu commented on esphome/components/ade7953_base/ade7953_base.h
> +  void setup() override {
Done

2023-10-09 09:23 UTC, angelnu commented on esphome/components/ade7953_i2c/ade7953_i2c.h
> +  bool ade_write_8(uint16_t reg, uint8_t value) override {
Done

2023-10-09 09:25 UTC, angelnu commented on esphome/components/ade7953_base/ade7953_base.h
> +    });
I added a comment to explain the 100ms delay.

2023-10-10 23:17 UTC, jesserockz commented on esphome/components/ade7953_base/ade7953_base.cpp
> +  ESP_LOGCONFIG(TAG, "  BWGAIN_32: 0x%08jX", (uintmax_t) val);
Either as sensors, or gather the data once in `setup` and then print in `dump_config`

2023-10-11 07:13 UTC, angelnu commented on esphome/components/ade7953_base/ade7953_base.cpp
> +  ESP_LOGCONFIG(TAG, "  BWGAIN_32: 0x%08jX", (uintmax_t) val);
Moved @jesserockz  - resolving.

2023-10-27 01:32 UTC, angelnu commented
@notsonominal you also mentioned in discord that this worked for you, right?

2023-11-06 03:51 UTC, jesserockz requested changes

2023-11-06 03:51 UTC, jesserockz commented on esphome/components/ade7953_base/__init__.py
> +        # cv.GenerateID(): cv.declare_id(ADE7953),
No commented code please
```suggestion
```

2023-11-06 03:51 UTC, jesserockz commented on esphome/components/ade7953_i2c/sensor.py
> +ADE7953 = ade7953_ns.class_("AdE7953I2c", cg.PollingComponent, i2c.I2CDevice)
This should be showing that is extends `ade7953_base::ADE7953`

The class stub should be created in the _base python file and imported here.

```suggestion
ADE7953 = ade7953_ns.class_("AdE7953I2c", ade7953_base.ADE7953, i2c.I2CDevice)
```

2023-11-06 03:51 UTC, jesserockz commented on esphome/components/ade7953_i2c/ade7953_i2c.cpp
> +  *value |= ((uint32_t) recv[1]);
Much cleaner =)

Need to add `#include "esphome/core/helpers.h"` to the top of the file

```suggestion
  *value = encode_uint16(recv[0], recv[1]);
```

2023-11-06 03:51 UTC, jesserockz commented on esphome/components/ade7953_i2c/ade7953_i2c.cpp
> +  *value |= ((uint32_t) recv[3]);
Same as above
```suggestion
  *value = encode_uint32(recv[0], recv[1], recv[2], recv[3]);
```

2023-11-06 03:51 UTC, jesserockz commented on esphome/components/ade7953_spi/ade7953_spi.cpp
> +  *value |= this->read_byte();
Same here as i2c

2023-11-06 14:27 UTC, angelnu commented
Thanks for the review @jesserockz - changes made and testcases passing. Ready to merge from my side.

2023-11-06 19:55 UTC, jesserockz requested changes

2023-11-06 19:55 UTC, jesserockz commented on esphome/components/ade7953_spi/ade7953_spi.cpp
> +  read_array(recv, 4);
```suggestion
  this->read_array(recv, 4);
```

2023-11-06 19:55 UTC, jesserockz commented on esphome/components/ade7953_i2c/ade7953_i2c.cpp
> +  *value = 0;
Probably don't need this line
```suggestion
```

2023-11-06 19:55 UTC, jesserockz commented on esphome/components/ade7953_i2c/ade7953_i2c.cpp
> +  std::vector<uint8_t> data;
Since we know the future size we can allocate it once at the start
```suggestion
  std::vector<uint8_t> data(6);
```

2023-11-06 19:55 UTC, jesserockz commented on esphome/components/ade7953_i2c/ade7953_i2c.cpp
> +  std::vector<uint8_t> data;
```suggestion
  std::vector<uint8_t> data(4);
```

2023-11-06 19:55 UTC, jesserockz commented on esphome/components/ade7953_i2c/ade7953_i2c.cpp
> +  std::vector<uint8_t> data;
```suggestion
  std::vector<uint8_t> data(3);
```

2023-11-06 19:55 UTC, jesserockz commented on esphome/components/ade7953_i2c/ade7953_i2c.cpp
> +  return write(data.data(), data.size()) != i2c::ERROR_OK;
Please make sure you prefix member functions with `this->`
```suggestion
  return this->write(data.data(), data.size()) != i2c::ERROR_OK;
```

2023-11-06 20:12 UTC, angelnu commented
Thanks for the new additions @jesserockz - all merged.

2023-11-06 21:00 UTC, jesserockz commented on esphome/components/ade7953_i2c/ade7953_i2c.cpp
> +  return write(data.data(), data.size()) != i2c::ERROR_OK;
There are some more places to add `this->` prefix. I just dont add all of them in a review as I might as well just update the branch at that point and then it doesnt help you for future PRs =)

2023-11-06 21:18 UTC, angelnu commented on esphome/components/ade7953_i2c/ade7953_i2c.cpp
> +  return write(data.data(), data.size()) != i2c::ERROR_OK;
@jesserockz - ok, I think I got them all now. Sorry that I missed your comment about other occurrences.

2023-11-06 21:41 UTC, angelnu commented on esphome/components/ade7953_spi/ade7953_spi.cpp
> +  read_array(recv, 4);
added in a later commit

2023-11-06 22:10 UTC, jesserockz commented on esphome/components/ade7953_base/ade7953_base.h
> +  void setup() override {
This is not done yet?

2023-11-06 22:18 UTC, jesserockz requested changes

2023-11-06 22:18 UTC, jesserockz commented on esphome/components/ade7953/sensor.py
I have been on the fence about this since aliasing is nice for people that currently use the platform, but we tend to just remove them with a validation error informing users they need to make a change or see the documentation etc.

Please search the codebase for `CONFIG_SCHEMA = cv.invalid("...")` to see other examples.

2023-11-06 22:49 UTC, angelnu commented on esphome/components/ade7953/sensor.py
ok - removed alias @jesserockz

2023-11-06 23:10 UTC, jesserockz approved these changes

2023-11-07 00:17 UTC, merged