Fix an Issue with IR Remote Climate and Whirlpool protocol toggle
OttoWinter/esphomeyaml pull request #5447
Opened 2023-09-28 12:03 UTC by the-mentor

# What does this fix?
In short because the whirlpool protocol is based on toggle we need to block the receiver while transmitting to prevent the system from getting confused. 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

Related issues:
https://github.com/esphome/issues/issues/4650
https://github.com/esphome/issues/issues/4468

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```
 remote_transmitter:
  id: remote_transmitter_id
  pin: GPIO14
  carrier_duty_percent: 50%

remote_receiver:
  id: "remote_receiver_id"
  pin:
    number: GPIO5
    inverted: True
  tolerance: 55%
  dump: all

climate:
  - platform: whirlpool
    name: "Study AC"
    model: "DG11J1-91"
    sensor: room_temperature
    transmitter_id: remote_transmitter_id
    receiver_id: remote_receiver_id
```

## Checklist:
  - [x] The code change is tested and works locally.

2023-09-28 13:51 UTC, the-mentor commented
Ping @kpfleming following our discord chat

2023-09-28 20:24 UTC, clydebarrow requested changes
You should make the variable an instance member - declare it in the header file under `protected:`. Call it `last_transmit_time_` (note the trailing underscore) and refer to it in your code as `this->last_transmit_time_`. "t1" is not descriptive and a global is not appropriate here - it should not be visible outside the component.

2023-09-28 21:17 UTC, clydebarrow requested changes

2023-09-28 21:17 UTC, clydebarrow commented on esphome/components/whirlpool/whirlpool.h
> +  int32_t last_transmit_time_ = millis() + 500;
```suggestion
  int32_t last_transmit_time_;
```

2023-09-28 22:31 UTC, clydebarrow approved these changes
Looks good to me.

2023-09-28 23:20 UTC, clydebarrow commented on esphome/components/whirlpool/whirlpool.h
> +  int32_t last_transmit_time_;
Sorry, I led you astray there, this should have an initialiser, just not `millis()`. Initiialising to `{}` will make it zero, so guaranteed to be in the past.

```suggestion
  int32_t last_transmit_time_{};
```

2023-09-29 00:40 UTC, jesserockz approved these changes

2023-09-29 01:17 UTC, merged