Improve dualstack and IPv6 support
OttoWinter/esphomeyaml pull request #5449
Opened 2023-09-28 17:28 UTC by HeMan

# What does this implement/fix?

Makes ESPHome work better with IPv6 by adding a datatype for multiple IP addresses. This adds support for reporting all addresses it got, via `wifi_info`/`ethernet_info` text-sensors, via MQTT and as part of debug message.
It makes MQTT resolve both IPv6 and IPv4 addresses, and connects over IPv6 (as well as over IPv4 as before).
Breaks external components that assumes ESPHome only has one IP address.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP32 Ethernet
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esphome:
  name: ipv6mqtt

network:
  enable_ipv6: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifissd
  password: !secret wifipwd

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address

debug:

logger:
  level: VERY_VERBOSE

web_server:
  port: 80

api:

ota:

mqtt:
  broker: mqtt6.example.com
  discovery: true

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-23 19:13 UTC, jesserockz requested changes

2023-10-23 19:13 UTC, jesserockz commented on esphome/components/ethernet/ethernet_component.h
> +  network::IPAddresses get_ip_address();
I feel like if you are changing the functionality to return a list, the name of the function should also change...
```suggestion
  network::IPAddresses get_ip_addresses();
```

2023-10-24 05:39 UTC, HeMan commented on esphome/components/ethernet/ethernet_component.h
> +  network::IPAddresses get_ip_address();
Good suggestion! Should I also update `WiFiComponent::wifi_sta_ip` to `WiFiComponent::wifi_sta_ips`?

2023-11-05 22:05 UTC, jesserockz commented on esphome/components/ethernet_info/ethernet_info_text_sensor.h
> +      this->publish_state(address_results);
Not sure I like this sensor changing to just list all addresses. This could be a breaking change for people that use it currently.

2023-11-05 22:09 UTC, jesserockz commented on esphome/components/ethernet_info/ethernet_info_text_sensor.h
> +      this->publish_state(address_results);
Maybe have a second sensor for ipv6_address?

2023-11-05 22:37 UTC, jesserockz requested changes

2023-11-05 22:37 UTC, jesserockz commented on esphome/components/network/__init__.py
> +    cg.add_define("MIN_IPV6_ADDR_COUNT", config[CONF_MIN_IPV6_ADDR_COUNT])
This should follow the format we use through ESPHome. `USE_NETWORK_MIN_IPV6_ADDRESS_COUNT`

(Really, `ENABLE_IPV6` should have followed this format too)

2023-11-05 22:37 UTC, jesserockz commented on esphome/components/wifi/wifi_component.cpp
> +  // TODO: fix soft ap
Is this still a TODO?

2023-11-06 08:11 UTC, HeMan commented on esphome/components/network/__init__.py
> +    cg.add_define("MIN_IPV6_ADDR_COUNT", config[CONF_MIN_IPV6_ADDR_COUNT])
Should I change `ENABLE_IPV6` while I'm at it? Is `USE_NETWORK_IPV6` a good name or do you have a better suggestion?

2023-11-06 08:12 UTC, HeMan commented on esphome/components/wifi/wifi_component.cpp
> +  // TODO: fix soft ap
Nope, removing the comment.

2023-11-06 10:03 UTC, HeMan commented on esphome/components/ethernet_info/ethernet_info_text_sensor.h
> +      this->publish_state(address_results);
This is a tricky one. Going dual stack will change the behavior for the entire system with that it usually has more than one address. Having different API endpoints for different addresses is also something that I like to avoid.
On the other hand, I'm not really pleased with adding prefixes to the address and treat is a "textblob" with newlines since it makes it harder to machine parse.
Is there a way to dynamically add and remove sensors? Have an array of sensors that could contain empty/unset addresses? Would that break something else?

2023-11-29 20:45 UTC, MatthewCroughan commented
Just commenting to let you know that this fixed all of my IPv6 woes. AAAA records now resolve, MQTT broker can be set to an IPv6 address. In addition, IPv6 addresses will not be accidentally parsed as if they were domain names.

2023-12-01 22:25 UTC, MatthewCroughan commented
It seems like the web interface doesn't listen on the v6 address, meaning it is inaccessible via IPv6.

2023-12-03 20:14 UTC, HeMan commented
> It seems like the web interface doesn't listen on the v6 address, meaning it is inaccessible via IPv6.

Web interface for Arduino on ESP32 depends on https://github.com/esphome/AsyncTCP/pull/5

2023-12-21 04:05 UTC, jesserockz requested changes

2023-12-21 04:05 UTC, jesserockz commented on esphome/components/ethernet_info/ethernet_info_text_sensor.h
> +          if (ip_sensors_[sensor]) {
Please alter to explicitly check for `nullptr`
```suggestion
          if (ip_sensors_[sensor] != nullptr) {
```

2023-12-21 04:05 UTC, jesserockz commented on esphome/components/ethernet_info/text_sensor.py
> +                cv.Optional(f"a{x}"): text_sensor.text_sensor_schema(
I feel like the config key should be a bit more descriptive than `aX`

2023-12-21 04:05 UTC, jesserockz commented on esphome/components/wifi_info/text_sensor.py
> +                cv.Optional(f"a{x}"): text_sensor.text_sensor_schema(
Same here

2023-12-21 04:05 UTC, jesserockz commented on esphome/components/wifi_info/wifi_info_text_sensor.h
> +          if (ip_sensors_[sensor]) {
Same here

2024-01-22 06:45 UTC, HeMan commented
Libretiny depends on https://github.com/esphome/AsyncTCP/pull/9

2024-02-27 03:15 UTC, jesserockz requested changes
**This** almost looks good, just a couple of missing things :wink:

2024-02-27 03:15 UTC, jesserockz commented on esphome/components/ethernet_info/ethernet_info_text_sensor.h
> +  void add_ip_sensors(uint8_t index, text_sensor::TextSensor *s) { ip_sensors_[index] = s; }
```suggestion
  void add_ip_sensors(uint8_t index, text_sensor::TextSensor *s) { this->ip_sensors_[index] = s; }
```

2024-02-27 03:15 UTC, jesserockz commented on esphome/components/ethernet_info/ethernet_info_text_sensor.h
> +          if (ip_sensors_[sensor] != nullptr) {
```suggestion
          if (this->ip_sensors_[sensor] != nullptr) {
```

2024-02-27 03:15 UTC, jesserockz commented on esphome/components/wifi_info/wifi_info_text_sensor.h
> +          if (ip_sensors_[sensor] != nullptr) {
```suggestion
          if (this->ip_sensors_[sensor] != nullptr) {
```

2024-02-27 03:15 UTC, jesserockz commented on esphome/components/wifi_info/wifi_info_text_sensor.h
> +  void add_ip_sensors(uint8_t index, text_sensor::TextSensor *s) { ip_sensors_[index] = s; }
```suggestion
  void add_ip_sensors(uint8_t index, text_sensor::TextSensor *s) { this->ip_sensors_[index] = s; }
```

2024-02-27 07:24 UTC, HeMan commented
> **This** almost looks good, just a couple of missing things 😉

Fixed! Found an unused variable as well.

2024-02-27 08:16 UTC, jesserockz approved these changes

2024-02-27 08:16 UTC, merged