Bug: Unwanted change resistance in x9c component
OttoWinter/esphomeyaml pull request #5483
Opened 2023-10-05 10:03 UTC by fizista

# What does this implement/fix?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes n/a

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** n/a

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```yaml
select:
  # - platform: template
  #   name: "Tryb pracy"
  #   id: sel_tryb_pracy
  #   options:
  #     - Automatyczny
  #     - Manualny
  #     - Wyłączony
  #   lambda: |- 
  #     auto option = id(sel_tryb_pracy).at(id(glob_program));
  #     if (option.has_value()) {
  #       auto value = option.value();
  #       return value;
  #     } else {
  #       auto option = id(sel_tryb_pracy).at(0);
  #       if (option.has_value()) {
  #         auto value = option.value();
  #         return value;
  #       } else {
  #         ESP_LOGE("main", "Index %d does not exist", index);
  #       }
  #     }
  #   set_action:
  #     # - logger.log:
  #     #     format: "Chosen option: %s"
  #     #     args: ["x.c_str()"]
  #     - lambda: |-
  #         auto index = id(sel_tryb_pracy).index_of(x);
  #         if (index.has_value()) {
  #           id(glob_program)=index.value();
  #         } else {
  #           ESP_LOGE("main", "There is no option '%s'", x);
  #         }

switch:
  - platform: template
    id: test_repeat
    name: "X9C Const value 20"
    restore_mode: ALWAYS_OFF
    optimistic: True
    on_turn_on:
      - output.set_level: 
          id: x9c_pot
          level: 20
    on_turn_off:
      - output.set_level: 
          id: x9c_pot
          level: 20

output:
  - platform: x9c
    id: x9c_pot
    cs_pin: GPIO15
    inc_pin: GPIO4
    ud_pin: GPIO2
    initial_value: 0.01
    inverted: True

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-11 18:33 UTC, EtienneMD commented
I see what you are saying, chip should not be selected with INC pin in High state. It never is thought as the pin is selected high prior to CS pin being lowered. Any advantage in leaving it high all the time when not in use?

2023-10-16 09:24 UTC, fizista commented
You're right. The high state on INC is not needed.

2023-10-16 12:36 UTC, EtienneMD requested changes

2023-10-16 12:36 UTC, EtienneMD commented on esphome/components/x9c/x9c.cpp
> -  this->inc_pin_->digital_write(false);
I'd leave this in, as this prevents saving the counter position to non-volatile memory. An action could be added in the future to enable that feature.

2023-12-21 06:42 UTC, jesserockz approved these changes

2023-12-21 07:03 UTC, merged