Add support for PN7160
OttoWinter/esphomeyaml pull request #5486
Opened 2023-10-06 03:37 UTC by kbx81

# What does this implement/fix?

Adds support for PN7160 NFCCs.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-12 00:43 UTC, jesserockz requested changes

2023-12-12 00:43 UTC, jesserockz commented on esphome/components/pn7160/__init__.py
> +        pin = await cg.gpio_pin_expression(config[CONF_DWL_REQ_PIN])
Can we change all of these to the new format? (same for 7150)
```suggestion
    if dwl_req_pin_config := config.get(CONF_DWL_REQ_PIN):
        pin = await cg.gpio_pin_expression(dwl_req_pin_config)
```

2023-12-12 00:43 UTC, jesserockz commented on esphome/components/pn7160/automation.h
> +};
Similar to `Conditions` these can be `Parented<>` and drop the constructor and protected field

```suggestion
template<typename... Ts> class EmulationOffAction : public Action<Ts...>, public Parented<PN7160> {
 public:
  void play(Ts... x) override { this->pn7160_->set_tag_emulation_off(); }
};
```

2023-12-12 00:43 UTC, jesserockz commented on esphome/components/pn7160/binary_sensor.py
Maybe this should be a common `nfc` binary sensor, similar to `touchscreen`?

2023-12-12 07:09 UTC, kbx81 commented on esphome/components/pn7160/__init__.py
> +        pin = await cg.gpio_pin_expression(config[CONF_DWL_REQ_PIN])
Done

2023-12-12 07:09 UTC, kbx81 commented on esphome/components/pn7160/automation.h
> +};
Done

2023-12-12 07:10 UTC, kbx81 commented on esphome/components/pn7160/binary_sensor.py
That's a good idea -- maybe good to do in a follow-up PR and make it so the other NFC components can use it, too?

2023-12-12 07:30 UTC, jesserockz commented on esphome/components/pn7160/binary_sensor.py
If this becomes a followup, it will be breaking for this brand new binary sensor platform just to remove it again...

2023-12-12 07:34 UTC, kbx81 commented on esphome/components/pn7160/binary_sensor.py
Good point 😅

2023-12-13 02:32 UTC, kbx81 commented on esphome/components/pn7160/binary_sensor.py
(For posterity) The `binary_sensor` was removed for now; we'll implement it as its own component before too long.

2023-12-13 22:46 UTC, jesserockz approved these changes

2023-12-13 22:54 UTC, merged