Allow Pillow versions 10+
OttoWinter/esphomeyaml pull request #5489
Opened 2023-10-06 06:24 UTC by hostcc

# What does this implement/fix?
Unlocking recent versions of Pillow Python package has an immediate benefit of closing [security
issue](https://security.snyk.io/vuln/SNYK-PYTHON-PILLOW-5918878) has been reported recently.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-06 11:40 UTC, frenck commented on requirements_optional.txt
> +pillow>=10.0.0
Pillow 10.0.0 contains a high-severity vulnerability.

```suggestion
pillow>=10.0.1
```

2023-10-06 11:42 UTC, hostcc commented on requirements_optional.txt
> +pillow>=10.0.0
Sharp eye, sir - was targeting to address that exact case, thanks!

2023-10-06 18:28 UTC, nielsnl68 requested changes
Thanks for updating this code. Based on @frenck 's suggestion about the vulnerability of 10.0.0, i have some suggested changes as well.

2023-10-06 18:28 UTC, nielsnl68 commented on esphome/components/font/__init__.py
> +            '(pip install pillow">=10.0.0")'
``` suggestion
            '(pip install pillow">10.0.0")'
```
when  10.0.0 has that vulnerability as @frenck said, should we not disallow that version to be installed as well?

2023-10-06 18:28 UTC, nielsnl68 commented on esphome/components/font/__init__.py
> +            '(pip install pillow">=10.0.0")'
same as above.

2023-10-06 18:28 UTC, nielsnl68 commented on esphome/components/font/__init__.py
> +    if version.parse(PIL.__version__) < version.parse("10.0.0"):
same as above

2023-10-07 07:22 UTC, hostcc commented on esphome/components/font/__init__.py
> +            '(pip install pillow">=10.0.0")'
Makes a perfect sense - thanks! addressed with eb35958d

2023-10-07 11:37 UTC, nielsnl68 approved these changes

2023-10-08 20:26 UTC, jesserockz requested changes

2023-10-08 20:26 UTC, jesserockz commented on requirements_optional.txt
> +pillow>=10.0.1
I actually want to move these to be exact versions, so may as well make that here
```suggestion
pillow==10.0.1
```

2023-10-08 20:29 UTC, hostcc commented on requirements_optional.txt
> +pillow>=10.0.1
@jesserockz , I agree pinning dependencies to exact versions is great, I initially followed same semantics as others under `requirements_optional.txt. Will update the PR shortly.

2023-10-08 21:32 UTC, jesserockz commented
CI errors unrelated, fixed with #5501

2023-10-08 22:56 UTC, jesserockz requested changes

2023-10-08 22:56 UTC, jesserockz commented on esphome/components/font/__init__.py
> +            '(pip install pillow">=10.0.1")'
```suggestion
            '(pip install "pillow==10.0.1")'
```

2023-10-08 22:56 UTC, jesserockz commented on esphome/components/font/__init__.py
> +    if version.parse(PIL.__version__) < version.parse("10.0.1"):
```suggestion
    if version.parse(PIL.__version__) != version.parse("10.0.1"):
```

2023-10-08 22:56 UTC, jesserockz commented on esphome/components/font/__init__.py
> +            '(pip install pillow">=10.0.1")'
```suggestion
            "Please update your pillow installation to 10.0.1. "
            '(pip install "pillow==10.0.1")'
```

2023-10-08 22:57 UTC, jesserockz approved these changes

2023-10-09 00:47 UTC, merged