Allow manual set "Invert_display"
OttoWinter/esphomeyaml pull request #5494
Opened 2023-10-07 14:25 UTC by nielsnl68

# What does this implement/fix?

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes (https://github.com/esphome/issues/issues/4948)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
  display:
     platform: ili9xxx
     model: ili9488
     invert_display: true
     ...
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs/pull/3245).

2023-10-08 20:30 UTC, jesserockz requested changes

2023-10-08 20:30 UTC, jesserockz commented on esphome/components/ili9xxx/display.py
> +        cg.add(var.invert_display(config[CONF_INVERT_DISPLAY]))
codegen functions cannot call command functions as the component is not setup yet.
This should just set a variable which is then called during setup

2023-10-08 23:36 UTC, nielsnl68 commented on esphome/components/ili9xxx/display.py
> +        cg.add(var.invert_display(config[CONF_INVERT_DISPLAY]))
It took me a while to understand what you mend here, but men you are right.

2023-10-10 23:47 UTC, jesserockz approved these changes

2023-10-12 01:26 UTC, merged