Don't allow entity category "CONFIG" for sensors
OttoWinter/esphomeyaml pull request #5505
Opened 2023-10-09 11:04 UTC by edenhaus

# What does this implement/fix?

The configuration category "config" is for read/write entities that control things. A sensor can never control things (and thus the change triggering because of this change are incorrect to begin with).
See https://github.com/home-assistant/core/pull/101471

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-09 20:45 UTC, jesserockz requested changes

2023-10-09 20:45 UTC, jesserockz commented on esphome/components/sensor/__init__.py
> +    for k, v in cv._ENTITY_CATEGORIES.items()  # pylint: disable=protected-access
Happy with the overall change, but can we just change this to be non-protected instead?
```suggestion
    for k, v in cv.ENTITY_CATEGORIES.items()
```

2023-10-10 06:12 UTC, edenhaus commented on esphome/components/sensor/__init__.py
> +    for k, v in cv._ENTITY_CATEGORIES.items()  # pylint: disable=protected-access
Yes sure :) I thought that it was protected so everybody uses the function `entity_category` instead

2023-10-10 06:24 UTC, jesserockz commented on esphome/components/sensor/__init__.py
> +    for k, v in cv.ENTITY_CATEGORIES.items()  # pylint: disable=protected-access
Still needed?
```suggestion
    for k, v in cv.ENTITY_CATEGORIES.items()
```

2023-10-10 06:26 UTC, jesserockz submitted a review, later dismissed
LGTM, Thanks

2023-10-10 06:52 UTC, jesserockz approved these changes

2023-10-10 07:00 UTC, merged