BME280 SPI
OttoWinter/esphomeyaml pull request #5538
Opened 2023-10-16 06:00 UTC by apbodrov

# A new interface for BME280 sensor

BME280 SPI 

## Types of changes

- [+] New feature (non-breaking change which adds functionality)

**fixies https://github.com/esphome/feature-requests/issues/1321**

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [+] ESP32

## Example entry for `config.yaml`:

```yaml
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

sensor:
  - platform: bme280_spi
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    update_interval: 60s
    cs_pin: GPIO5
```

## Checklist:
  - [+] The code change is tested and works locally.
  - [+] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [...] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-17 00:39 UTC, apbodrov commented
tested two BMEs with config

```yaml
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

i2c:
  sda: 21
  scl: 22
  scan: true

sensor:
  - platform: bme280_spi
    temperature:
      name: "BME280 SPI Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 SPI Pressure"
    humidity:
      name: "BME280 SPI Humidity"
    update_interval: 60s
    cs_pin: GPIO5


  - platform: bme280
    temperature:
      name: "BME280 I2C Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 I2C Pressure"
    humidity:
      name: "BME280 I2C Humidity"
    update_interval: 60s
    address: 0x76
```

2023-10-17 15:53 UTC, apbodrov commented
@OttoWinter hello! can you check my PR? Thanks!

2023-10-19 00:32 UTC, jesserockz commented
Please don't ping maintainers. Its a good way to get ignored :wink:

2023-10-19 00:44 UTC, apbodrov commented
@jesserockz 
I'm following your **_own_** guide
<img width="862" alt="изображение" src="https://github.com/esphome/esphome/assets/12022677/53e7b7d9-35e7-468e-a8ac-858cafe1ae2d">

2023-10-19 00:59 UTC, jesserockz commented
3 days is not lingering yet. It's still fresh out of the oven.

2023-12-16 01:22 UTC, rossens commented
I am looking forward to trying/usinig this - I have several SPI BME280 and Pi Pico ready and waiting. I'm fairly new to ESPHome - can anyone advise how long it usually takes for something like this to make it over to Home Assistant?
PS - seems one of the Validate YAML tests failed - "Pin 5 is used in multiple places."?

2023-12-18 06:03 UTC, kbx81 commented
@rossens you (or anyone else who might be interested) can test this PR as an external component by adding this to your yaml config:
```yaml
external_components:
  - source: github://pr#5538
    components: [ bme280_base, bme280_spi ]
```

2023-12-18 06:05 UTC, kbx81 commented
While it means a breaking change, for consistency with other components within the platform where the hardware (sensor, display, etc.) is able to support both I2C and SPI, the I2C component should probably be renamed to `bme280_i2c`.

2023-12-19 00:59 UTC, apbodrov commented
> While it means a breaking change, for consistency with other components within the platform where the hardware (sensor, display, etc.) is able to support both I2C and SPI, the I2C component should probably be renamed to `bme280_i2c`.

In fact, the only difference will be another name, but it will take a lot of work to

1) Refactor the code, tests, and documentation in the repository.
2) Refactor the _alll_ configs of all users.

2023-12-21 04:44 UTC, rossens commented
> @rossens you (or anyone else who might be interested) can test this PR as an external component by adding this to your yaml config:
> 
> ```yaml
> external_components:
>   - source: github://pr#5538
>     components: [ bme280_base, bme280_spi ]
> ```

Thanks that looks much simpler than what I did (I applied this PR as a patch over my installed ESPHome files). I got it working fine though. Will try this better way next time.

Results: Temperature and pressure seem pretty close - but humidity is reading too low. e.g. currently 25% reported vs 50% actual. 
Wondering if it could be anything to do with the PR - but assume it is more likely an issue with the cheap sensors I purchased from AliExpress.
 
I also wonder if it could be relative vs absolute humidity? I am assuming the sensor/code and ESPHome all talk "relative" but I'm not 100% sure. Anyone know?

2023-12-21 04:50 UTC, apbodrov commented
@rossens 
> Results: Temperature and pressure seem pretty close - but humidity is reading too low. e.g. currently 25% reported vs 50% actual. Wondering if it could be anything to do with the PR - but assume it is more likely an issue with the cheap sensors I purchased from AliExpress.

Hello! I had a similar problem, and I also decided that it was the sensor. But since I'm not the only one with the problem, now I'm starting to think that the problem is in the code.

I'll try to fix the bug and synchronize the readings later.

Thanks!

2023-12-21 22:18 UTC, rossens commented
I'm suspicious the problem may be here:
```
float BME280Component::read_humidity_(const uint8_t *data, int32_t t_fine) {
  uint16_t const raw_adc = ((data[6] & 0xFF) << 8) | (data[7] & 0xFF); // <<<<<<<<<<<<<<<
```
Depending on compiler - `(data[6] << 8)` may always give 0 because `uint8_t(x) << 8 = uint8_t(0)`

Try this instead... (I also removed the `& 0xFF` which aren't neccesary)
```
  uint16_t const raw_adc = (uint16_t(data[6]) << 8) | data[7];
```

I'll also give this a try later on today myself.

2023-12-21 23:47 UTC, apbodrov commented
> I'm suspicious the problem may be here:
> `float BME280Component::read_humidity_(const uint8_t *data, int32_t t_fine)`

This is a shared code between I2C and SPI component, it was moved from BME280 I2C. So that fix will affect I2C code (which I do not touched, just move)

2023-12-22 00:19 UTC, rossens commented
> I'm suspicious the problem may be here:
> `float BME280Component::read_humidity_(const uint8_t *data, int32_t t_fine)`

I just tried this out - no improvement in humidity reading - so my suspicion wasn't correct.

2023-12-22 01:22 UTC, rossens commented on esphome/components/bme280_spi/bme280_spi.cpp
> +  data[0] = this->delegate_->transfer(0);
Looks like the humidity issue is coming from here...
`data` is `uint16_t*` - but code looks like `u8*` was intended... e.g.
```
  ((uint8_t*)data)[1] = this->delegate_->transfer(0);
  ((uint8_t*)data)[0] = this->delegate_->transfer(0);
```
I tried the above fix and my humidity increased from 35% to 50% - which I "hope" is now correct.

2023-12-22 05:09 UTC, apbodrov commented on esphome/components/bme280_spi/bme280_spi.cpp
> +  data[0] = this->delegate_->transfer(0);
Thank you! Will fix with tests shortly

2023-12-23 01:55 UTC, jesserockz requested changes, later dismissed
As per the message above from @kbx81

> While it means a breaking change, for consistency with other components within the platform where the hardware (sensor, display, etc.) is able to support both I2C and SPI, the I2C component should probably be renamed to `bme280_i2c`.

Please move the main component. This is to avoid confusion in the future and we have done it many times in the past.

2023-12-24 00:48 UTC, rossens commented on CODEOWNERS
> +esphome/components/bme280_spi/* @apbodrov
Is it an issue this says `Unknown owner: make sure @apbodrov exists and has write access to the repository`

2023-12-24 00:58 UTC, rossens commented on esphome/components/bme280_spi/bme280_spi.cpp
> +  // cause: *data = this->delegate_->transfer(tmp) doesnt work
Probably my fault - but I don't understand this comment.

2023-12-24 01:04 UTC, rossens approved these changes
Looks good to me. 
I'm successfully using this PR/patch to operate 4x BME280 SPI sensors on a Pi Pico.

2023-12-24 01:16 UTC, apbodrov commented on CODEOWNERS
> +esphome/components/bme280_spi/* @apbodrov
> Is it an issue this says `Unknown owner: make sure @apbodrov exists and has write access to the repository`

Interesting, what nickname should be here in that case

2023-12-24 01:20 UTC, apbodrov commented on esphome/components/bme280_spi/bme280_spi.cpp
> +  // cause: *data = this->delegate_->transfer(tmp) doesnt work
> Probably my fault - but I don't understand this comment.

This method should return the read value, but it did not work properly, I had to split the line
`*data = this->delegate_->transfer(set_bit(a_register, 7))`
into two
`this->delegate_->transfer(set_bit(a_register, 7));`
`*data = this->delegate_->transfer(0);`

2023-12-24 01:24 UTC, jesserockz commented on CODEOWNERS
> +esphome/components/bme280_spi/* @apbodrov
This is fine and not actually a problem and can be ignored

2024-01-09 12:36 UTC, TCB13 commented
Any updates on merging this? Thank you.

2024-01-10 04:18 UTC, kbx81 approved these changes
LGTM, thanks!

2024-01-10 04:31 UTC, merged