Fan cycle no off option
OttoWinter/esphomeyaml pull request #5550
Opened 2023-10-17 17:00 UTC by skykingjwc

# What does this implement/fix?
Adds a feature to the fan component so that the fan will not turn off when calling the cycle_speed action if so desired by the user

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes nothing.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3275

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esphome:
    name: fantest

esp32:
  board: esp32dev
  framework:
    type: esp-idf   #also tested with Arduino

output:
  - platform: ledc  #using ledc because we need a float output
    id: my_output_id
    inverted: false
    pin: GPIO19

logger:

fan:
    - platform: speed
      id: test_speed_fan
      speed_count: 3
      off_speed_cycle: True
      output: my_output_id
      on_speed_set:
        then:
          - logger.log: Fan speed was changed!

binary_sensor:
  - platform: gpio
    name: Cycle Fan Speed
    id: cyclespeed
    pin:
      number: 18
      mode:
        input: true
        pulldown: true

    filters:
      - delayed_on: 10ms

    # Optional variables:
    on_press:
      - fan.cycle_speed: test_speed_fan
      - logger.log: "Cycle speed clicked"

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-17 18:53 UTC, jesserockz requested changes

2023-10-17 18:53 UTC, jesserockz commented on esphome/components/speed/fan/__init__.py
> +        cg.add(var.set_offcycle(config[CONF_OFF_SPEED_CYCLE]))
Since you added a default, it will always be in config
```suggestion
   cg.add(var.set_offcycle(config[CONF_OFF_SPEED_CYCLE]))
```

2023-10-17 18:53 UTC, jesserockz commented on .gitignore
If you want to add a line to here, please add it in its own PR.

2023-10-17 18:53 UTC, jesserockz commented on esphome/components/fan/automation.h
> +        else if (speed > supported_speed_count && !off_speed_cycle) {
```suggestion
        } else if (speed > supported_speed_count && !off_speed_cycle) {
```

2023-10-17 18:53 UTC, jesserockz commented on esphome/components/fan/automation.h
> +        else {
```suggestion
        } else {
```

2023-10-17 18:53 UTC, jesserockz commented on tests/fantests.yaml
Can you add the config option and action test to test1.yaml please instead of a new file.

2023-10-17 20:35 UTC, jesserockz requested changes
THinking about it, I actually feel like this should just be an option on the cycle action itself and not on the fan. It will be simpler and less code changes required

2023-10-18 17:32 UTC, skykingjwc commented on esphome/components/fan/automation.h
> +        else if (speed > supported_speed_count && !off_speed_cycle) {
Resolved by deac151c7f592b106161603b4d668ca0091efbb0

2023-10-18 17:32 UTC, skykingjwc commented on esphome/components/fan/automation.h
> +        else {
Resolved by https://github.com/esphome/esphome/commit/deac151c7f592b106161603b4d668ca0091efbb0

2023-10-18 17:33 UTC, skykingjwc commented on esphome/components/speed/fan/__init__.py
> +        cg.add(var.set_offcycle(config[CONF_OFF_SPEED_CYCLE]))
Resolved by b1ebc789db86ae2c1d2792cf3d48621c82a42f49

2023-10-18 17:45 UTC, skykingjwc commented on tests/fantests.yaml
Done locally, but it fails because more code changes are required for other components.

2023-10-18 17:47 UTC, skykingjwc commented
> THinking about it, I actually feel like this should just be an option on the cycle action itself and not on the fan. It will be simpler and less code changes required

I agree after seeing the tests fail.
I would be happy to update the code to do it this way, could you elaborate a little more or point me to an example?  I'm not sure how to code an option for an action.   Thanks.

2023-10-18 21:51 UTC, skykingjwc commented
> > THinking about it, I actually feel like this should just be an option on the cycle action itself and not on the fan. It will be simpler and less code changes required
> 
> I agree after seeing the tests fail. I would be happy to update the code to do it this way, could you elaborate a little more or point me to an example? I'm not sure how to code an option for an action. Thanks.

Never mind, I used the output component as an example and I think I have it working as an action option.  Should I make a new PR and cancel this one, or just merge all my changes from the branch with the action option?

2023-10-18 23:36 UTC, jesserockz commented
Closing in favour of #5564

2023-10-18 23:36 UTC, closed without merging