Add differential pressure sensor support for CFSensor XGZP68xxD devices
OttoWinter/esphomeyaml pull request #5562
Opened 2023-10-18 21:22 UTC by gcormier

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```
sensor:
  - platform: xgzp68xx
    temperature:
      name: "press Temperature"
    pressure:
      name: "press diff pressure"
    update_interval: 60s
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-18 21:47 UTC, jesserockz requested changes

2023-10-18 21:47 UTC, jesserockz commented on esphome/components/xgzp68xx/xgzp68xx.cpp
> +  this->temperature_sensor_->publish_state(temp);
```suggestion
    this->temperature_sensor_->publish_state(temp);
```

2023-10-18 21:47 UTC, jesserockz commented on esphome/components/xgzp68xx/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_TEMPERATURE])
```suggestion
    if temperature_config := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_config)
```

2023-10-18 21:47 UTC, jesserockz commented on esphome/components/xgzp68xx/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_PRESSURE])
```suggestion
    if pressure_config := config.get(CONF_PRESSURE):
        sens = await sensor.new_sensor(pressure_config)
```

2023-10-18 21:47 UTC, jesserockz commented on esphome/components/xgzp68xx/xgzp68xx.cpp
> +  LOG_SENSOR("  ", "XGZP68xx", this);
```suggestion
  ESP_LOGCONFIG(TAG, "XGZP68xx");
  LOG_SENSOR("  ", "Temperature: ", this->temperature_sensor_);
  LOG_SENSOR("  ", "Pressure: ", this->pressure_sensor_);
```

2023-10-18 21:47 UTC, jesserockz commented on esphome/components/xgzp68xx/xgzp68xx.h
> +  sensor::Sensor *pressure_sensor_{nullptr};
```suggestion
```

2023-10-18 21:47 UTC, jesserockz commented on esphome/components/xgzp68xx/xgzp68xx.h
> +
```suggestion
 public:
  SUB_SENSOR(temperature)
  SUB_SENSOR(pressure)
```

2023-10-19 01:06 UTC, gcormier commented
Docs - https://github.com/esphome/esphome-docs/pull/3285

2023-10-19 21:52 UTC, gcormier commented
I think this is ready to go.

2023-10-20 02:04 UTC, gcormier commented
I'll need help fixing up that test, I'm not sure what is happening.

2023-10-23 19:11 UTC, jesserockz commented
As per the latest CI error, `%03b` is invalid. I dont think you can print binary like this. 

> Error: /home/runner/work/esphome/esphome/esphome/components/xgzp68xx/xgzp68xx.cpp:75:40: error: invalid conversion specifier 'b' [clang-diagnostic-format-invalid-specifier,-warnings-as-errors]

2023-10-29 14:03 UTC, gcormier commented
Thoughts on resolving this? I tried referencing i2c_bus directly and still get the error.

## Relevant section from test1.yaml
```
  - platform: xgzp68xx
    temperature:
      name: "Pressure Temperature"
    pressure:
      name: "Differential pressure"
    k_value: 4096
```

## Error
```
Failed config

sensor.xgzp68xx: [source tests/test1.yaml:344]
  
  Too many candidates found for 'i2c_id' type 'i2c::I2CBus' Some are 'i2c_bus', 'multiplex0_chan0'.
  platform: xgzp68xx
  temperature: 
    name: Pressure Temperature
    disabled_by_default: False
    force_update: False
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
  pressure: 
    name: Differential pressure
    disabled_by_default: False
    force_update: False
    unit_of_measurement: Pa
    accuracy_decimals: 1
    device_class: pressure
    state_class: measurement
  k_value: 4096
  update_interval: 60s
  address: 0x6D
Error: Process completed with exit code 2.
```

2023-10-29 18:58 UTC, jesserockz commented on tests/test1.yaml
> +  - platform: xgzp68xx
You added this?
```suggestion
  - platform: xgzp68xx
    i2c_id: i2c_bus
```

2023-10-29 18:58 UTC, jesserockz commented on tests/test1.yaml
> +      name: "Differential pressure"
Quotes are not needed around simple strings.
```suggestion
      name: Pressure Temperature
    pressure:
      name: Differential pressure
```

2023-10-29 20:09 UTC, gcormier commented
Ok I think this is finally ready!

2023-11-02 04:29 UTC, jesserockz requested changes

2023-11-02 04:29 UTC, jesserockz commented on esphome/components/xgzp68xx/xgzp68xx.h
> +  float offset_{0.0f};
Not required as will be set from the defaults
```suggestion
  uint16_t k_value_;
```

2023-11-02 04:29 UTC, jesserockz commented on esphome/components/xgzp68xx/sensor.py
> +            cv.Optional(CONF_OFFSET): cv.float_,
`offset` really should not need to exist as you can set an offset filter in yaml. Especially since the default is 0

```yaml
sensor:
  - platform: xgzp68xx
    pressure:
      name: Pressure
      filters:
        - offset: 1
```
```suggestion
```

2023-11-02 04:29 UTC, jesserockz commented on esphome/components/xgzp68xx/sensor.py
> +            cv.Optional(CONF_K_VALUE): cv.uint16_t,
This should be a config default, not hidden inside `to_code`

```suggestion
            cv.Optional(CONF_K_VALUE, default=4096): cv.uint16_t,
```

2023-11-02 04:29 UTC, jesserockz commented on esphome/components/xgzp68xx/sensor.py
> +    cg.add(var.set_offset(config.get(CONF_OFFSET, 0.0)))
```suggestion
    cg.add(var.set_k_value(config[CONF_K_VALUE]))
```

2023-11-02 04:29 UTC, jesserockz commented on esphome/components/xgzp68xx/xgzp68xx.cpp
> +    pressure_in_pa += this->offset_;
As above
```suggestion
```

2023-11-02 04:29 UTC, jesserockz commented on esphome/components/xgzp68xx/xgzp68xx.h
> +  void set_offset(float offset) { this->offset_ = offset; }
```suggestion
```

2023-11-06 01:21 UTC, jesserockz approved these changes

2023-11-06 23:46 UTC, merged