ota_http component
OttoWinter/esphomeyaml pull request #5586
Opened 2023-10-22 23:33 UTC by oarcher

# What does this implement/fix?

ota in client (http) mode: This allow to do a remote ota when the device is far away, behind a firewall, and only reachable with mqtt. (For ex in another house).

  - https only supported for esp32
  - no auth support for the moment

original component from https://github.com/oarcher/piotech/tree/main/components/ota_http

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <https://github.com/esphome/feature-requests/issues/801>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>  (TODO)

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

# Example config.yaml
```yaml
ota_http:

button:
  - platform: template
    name: "Firmware update"
    on_press:
      then:
        - ota_http.flash:
            url: http://example.com/firmware.bin
        - logger.log: "This message should be not displayed(reboot)"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-23 21:26 UTC, oarcher commented
I can see that PR #5535 change the implementation of OTA backend in `esphome/components/ota/ota_backend*`. 
This will conflict with this PR.

2023-10-25 12:13 UTC, nerijus commented
"https only supported for esp32" - does it mean that https is supported on esp32 only, not other platforms, or that esp32 supports https only, no http for example?

2023-10-26 23:56 UTC, oarcher commented
Sorry for the confusion. https and http works for esp32. I've edited the PR description with http/https support matrix.

2023-10-27 02:12 UTC, oarcher commented
Previous commit has fixed https for 8266.

2023-10-27 08:35 UTC, nerijus commented
> @nerijus Previous commit has fixed https for 8266.

So the line "https only supported for esp32" can probably be removed at all?

2023-11-19 19:22 UTC, angelnu commented
@oarcher - following with our conversation - can you please take a look at the split of the OTAComponent I drafted at https://github.com/angelnu/esphome-1/pull/1

2023-12-23 01:17 UTC, Alphaemef commented
Man I have to say again @oarcher. This thing is a beast. Probably used it a couple of hundred times by now. Its amazing. Good job man.

2024-02-13 09:43 UTC, kevireilly commented
Possible to support the advanced updater which allows the server to determine if there should be an OTA update performed? Useful for automatic updates or pushing specific updates to specific clients depending on the version string passed.

Wasn't able to find official up to date documentation, but am remembering something along these lines from years ago: https://arduino-esp8266.readthedocs.io/en/latest/ota_updates/readme.html#advanced-updater

2024-02-21 17:45 UTC, paulsteigel commented
Hi All,
Many thanks @oarcher for your work on ota_http that brilliant. I found [this](https://github.com/SmingHub/Sming/tree/8939766cb38ef540d8296c3ae4bbc0998f88b91a/Sming/Libraries/OtaUpgradeMqtt) with similar feature but it can do the OTA over MQTT.
If possible, could you please be so kind to help the community to do the OTA over MQTT using this approach.
Many thanks for the ESPHOME team.
Yours very faithfully,
Dang Dinh Ngoc

2024-02-21 20:29 UTC, oarcher commented
@paulsteigel , `ota_http` works well with mqtt, you just have to have a mqtt broker defined in an `mqtt:` section in your yaml. `ota.http.flash`  is just an action, that can be triggered by any events, including mqtt. 

```yaml

mqtt:
  broker: mqttbrocker.example.com
  username: mqtt_username
  password: mqtt_password

button:
  - platform: template
    name: "Firmware update"
    on_press:
      then:
        - ota_http.flash:
            url: http://example.com/firmware.bin
            verify_ssl: false
        - logger.log: "This message should be not displayed(reboot)"
```

2024-02-21 20:34 UTC, oarcher commented
@kevireilly , yes, I plan to add this feature to `ota_http`.  This will be done with the Arduino/NoFuss protocol (see https://github.com/esphome/feature-requests/issues/801#issuecomment-1806571447). 

But for now, I'm waiting for the main esphome maintainers to merge this PR.

2024-02-22 04:22 UTC, paulsteigel commented
Hi @oarcher,
Many thanks for your quick responses! I use your ota_http but it seems that there a bit of problem (can be due to my limited knowledge) and the update failed as following:
Hi [@oarcher](https://community.home-assistant.io/u/oarcher)
I tried your component and it throw the following error:

```
[21:38:09][D][button:010]: 'Firmware update' Pressed.
[21:38:09][D][esp32.preferences:114]: Saving 1 preferences to flash...
[21:38:09][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[21:38:09][D][ota_http:054]: Trying to connect to https://mywebpage.com.vn/firmwares/[mydeviceddns]/firmware.bin
[21:38:12][D][ota_http:101]: firmware is 1132272 bytes length.
[21:38:12][I][ota_http:111]: Progress: 0.1%
[21:38:12][E][ota_http:103]: Error code (131) writing binary data to flash at offset 4000 and size 1132272
[21:38:12][E][ota_http:150]: Abort OTA backend
[21:38:12][E][ota_http:153]: Abort http con
[21:38:12][E][ota_http:155]: previous safe mode didn't succed. ota_http skipped
[21:38:12][D][main:603]: This message should be not displayed(reboot)

```
My esphome configuration is here

```
ota_http:

button:
  - platform: template
    name: "Firmware update"
    on_press:
      then:
        - ota_http.flash:
            url: https://mywebpage.com.vn/firmwares/mydeviceddns/firmware.bin # revise it here
            verify_ssl: false
        - logger.log: "This message should be not displayed(reboot)"

```
My webpage.com.vn is the the replacement of my real address to avoid security risks. It shown that firmware was download successfully but failed in installing.
Regarding OTA over MQTT, from my knowledge, firmware build by Esphome in esphome docker (that i am now have to do the download manually, and this is a bit inconvenient rather than just click the install then all will do automatically) should be:
1. Encoded to base64 or whatever way then publish at an MQTT topic;
2. Trigger an action for the esphome device to download and install as it currently does via ota/8266.
It would be nice that we just need to click Install then firmware will be built and pass on MQTT protocol for device download and install as it is now over port 8266.
Yours very faithfully,
Dang DInh Ngoc

2024-02-22 11:47 UTC, oarcher commented
@paulsteigel , can you double check that your `firmware.bin` file is *not* `firmware-factory.bin` file ? The `Error code (131) writing binary data to flash` is frequent in this case.

A correct `firmware.bin` file starts with byte `0xE9`, you can check it with any hex file dumper or editor (ie `ghex`).

And yes, this component needs more contributions to be usable without copying manually the `firmware.bin` file to an external http server. It should be possible to use the internal HA http server, and add a button to the esphome HA addon. This was discussed by  @RubenNL and @jesserockz here: https://discord.com/channels/429907082951524364/1116081907730481162/1116081907730481162

2024-02-22 14:35 UTC, paulsteigel commented
Hi @oarcher,
I did the test again today with new built firmware, download and save it on http server for flashing, however, I could not capture the log, there was no log about the process, so I captured this status on MQTT for the device.
![image](https://github.com/esphome/esphome/assets/8839597/7d39cd0d-4b63-4f27-b9c7-cd13ee153384)
 I thought this worked so I rename the firmware on the http server to firmware.binx and press the button again to see how it work (theoretically an error will show) and here it the log:
```
LOG
[21:20:00][D][esp32.preferences:143]: Saving 1 preferences to flash: 1 cached, 0 written, 0 failed
[21:20:00][D][ota_http:054]: Trying to connect to https://thiennhienviet.org.vn/firmwares/homehbh.ddns.net/firmware.bin
[21:20:02][D][ota_http:101]: firmware is 0 bytes length.
[21:20:02][W][ota_http:083]: BACKEND->begin error: 137
LOG END
```
I renamed the file back to firmware.bin and this strange log show up

```
[21:23:26][D][ota_http:054]: Trying to connect to https://thiennhienviet.org.vn/firmwares/homehbh.ddns.net/firmware.bin
[21:23:26][E][ota_http:096]: Incorrect file size (-1) reported by http server (http status: -1). Aborting
[21:23:26][W][ota_http:083]: BACKEND->begin error: 137
[21:23:26][E][ota_http:153]: Abort http con
[21:23:26][E][ota_http:155]: previous safe mode didn't succed. ota_http skipped
[21:23:26][D][main:604]: This message should be not displayed(reboot)

```
To make sure I can capture all the log, I leave the log open and build the new firmware and upload again and press button, the following log show that it failed!
[```
21:33:08][D][ota_http:054]: Trying to connect to https://thiennhienviet.org.vn/firmwares/homehbh.ddns.net/firmware.bin
[21:33:08][E][ota_http:096]: Incorrect file size (-1) reported by http server (http status: -1). Aborting
[21:33:08][W][ota_http:083]: BACKEND->begin error: 137
[21:33:08][E][ota_http:153]: Abort http con
[21:33:08][E][ota_http:155]: previous safe mode didn't succed. ota_http skipped
[21:33:08][D][main:604]: This message should be not displayed(reboot)
```
 So I have no idea on why this is a problem. It seemed like error due to cache happened.
Haiza, please be sorry for taking your time!

2024-02-22 15:35 UTC, oarcher commented
@paulsteigel , I've downloaded your firmware, and checked it. It's invalid, because it start with byte `0xFF`, not `0xE9`. So it's probably a `firmware-factory.bin` file, not a `firmware.bin` file.

2024-02-22 18:54 UTC, Alphaemef commented
@paulsteigel  when you compile the firmware, make sure you download the “legacy” version and not the “modern” version.

2024-02-22 23:49 UTC, paulsteigel commented
Hi,
I see your points! This is a new learning curve for me as previously i
relied on esphome direct burn to ota/8266.
All the best and thanks for your great efforts!
Ngoc


On Fri, Feb 23, 2024, 1:55 AM Alphaemef ***@***.***> wrote:

> @paulsteigel <https://github.com/paulsteigel> when you compile the
> firmware, make sure you download the “legacy” version and not the “modern”
> version.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/5586#issuecomment-1960062966>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACDODLLNA7PKJBWUJCFMLADYU6IALAVCNFSM6AAAAAA6LHNNHWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRQGA3DEOJWGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-28 08:51 UTC, Rapsssito commented
@oarcher, did you have any response from the devs (maybe from @jesserockz)?

2024-03-02 08:04 UTC, paulsteigel commented
Hi @oarcher 
![image](https://github.com/esphome/esphome/assets/8839597/ebd81d55-7905-4681-9e4b-51de52f4ddce)
`15:02:30][D][button:010]: 'phanquan Firmware update' Pressed.
[15:02:30][D][esp32.preferences:114]: Saving 1 preferences to flash...
[15:02:30][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[15:02:30][D][ota_http:054]: Trying to connect to https://thiennhienviet.org.vn/firmwares/phanquan.bin
[15:02:30][E][ota_http:096]: Incorrect file size (-1) reported by http server (http status: -1). Aborting
[15:02:30][W][ota_http:083]: BACKEND->begin error: 137
[15:02:30][E][ota_http:153]: Abort http con
[15:02:30][E][ota_http:155]: previous safe mode didn't succed. ota_http skipped
[15:02:30][D][main:631]: This message should be not displayed(reboot)`
I did all as you have guided days ago: build a legacy version firmware and upload to the web and esp32lolin complained as above.
Please take some time to advice me with thanks.
best,
Ngoc

2024-03-03 00:27 UTC, oarcher commented
@paulsteigel ,
https://thiennhienviet.org.vn/firmwares/phanquan.bin give me a 404 ( not found ) when using a web browser or wget. Are you sure the file exists ?

I remember that an user reach this error using the embedded home assistant http server, that give an incorrect file size instead of a 404 error.

2024-03-03 02:24 UTC, paulsteigel commented
> @paulsteigel , https://thiennhienviet.org.vn/firmwares/phanquan.bin give me a 404 ( not found ) when using a web browser or wget. Are you sure the file exists ?
> 
> I remember that an user reach this error using the embedded home assistant http server, that give an incorrect file size instead of a 404 error.
Hi @oarcher,
Thank for your checking, the file is on the server (when I checked previously, after the failure, i removed the file). And now I did the check again with a just built file using legacy version. Here is the Log, file was there and accessible (you should you wget rather than browser):
https://thiennhienviet.org.vn/firmwares/phanquan.bin
```
[09:20:04][E][ota_http:096]: Incorrect file size (-1) reported by http server (http status: -1). Aborting
[09:20:04][W][ota_http:083]: BACKEND->begin error: 137
[09:20:04][E][ota_http:153]: Abort http con
[09:20:04][E][ota_http:155]: previous safe mode didn't succed. ota_http skipped
```
Please take some time to guide me with thanks.
Ngoc

2024-03-04 19:34 UTC, oarcher commented
@paulsteigel , do you have access to the httpd server logs ?
It seems that `ota_http` is not able to reach the server. Perhaps a firewall pb ?

Also, give me the log in `VERY_VERBOSE` level, especially for the http part :
```
logger:
  level: VERY_VERBOSE
 ```

2024-03-05 02:40 UTC, kbx81 commented on esphome/components/ota_http/ota_http_idf.cpp
> +           esp_http_client_get_content_length(this->client_));
In IDF 5+, `esp_http_client_get_content_length()` [returns an `int64t`](https://docs.espressif.com/projects/esp-idf/en/release-v5.0/esp32/api-reference/protocols/esp_http_client.html#_CPPv434esp_http_client_get_content_length24esp_http_client_handle_t) which causes an error here when compiling.

2024-03-05 02:42 UTC, kbx81 commented on esphome/components/ota_http/ota_http_idf.cpp
> +           esp_http_client_get_content_length(this->client_));
Try building with:
```yaml
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: 5.1.1
    platform_version: 6.4.0
```
...to test. 😄

2024-03-05 07:18 UTC, kbx81 commented on esphome/components/ota_http/__init__.py
> +        if config[CONF_SAFE_MODE] is True:
Some redundancy here, maybe?

2024-03-05 07:46 UTC, paulsteigel commented
> @paulsteigel , do you have access to the httpd server logs ? It seems that `ota_http` is not able to reach the server. Perhaps a firewall pb ?
> 
> Also, give me the log in `VERY_VERBOSE` level, especially for the http part :
> 
> ```
> logger:
>   level: VERY_VERBOSE
> ```

Hi @oarcher ,
Thanks for your response, here is the LOG
```
[10:46:40][D][button:010]: 'homehbh Firmware update' Pressed.
[10:46:40][VV][esp32.preferences:040]: s_pending_save: key: 99380598, len: 261
[10:46:40][V][ota_http:048]: restored pref ota_http_state: 40
[10:46:40][V][ota_http:052]: setting mode to progress
[10:46:40][D][esp32.preferences:114]: Saving 1 preferences to flash...
[10:46:40][VV][esp32.preferences:123]: Checking if NVS data 99380598 has changed
[10:46:40][V][esp32.preferences:126]: sync: key: 99380598, len: 261
[10:46:40][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[10:46:40][D][ota_http:054]: Trying to connect to https://thiennhienviet.org.vn/firmwares/homehbh.bin
[10:46:40][V][ota_http:072]: http begin successfull.
[10:46:40][VV][ota_http:076]: http client setReuse.
[10:46:40][V][ota_http:080]: http headers collected.
[10:46:40][V][ota_http:086]: http GET finished.
[10:46:40][E][ota_http:096]: Incorrect file size (-1) reported by http server (http status: -1). Aborting
[10:46:40][V][ota_http:079]: md5sum from received data initialized.
[10:46:40][W][ota_http:083]: BACKEND->begin error: 137
[10:46:40][E][ota_http:153]: Abort http con
[10:46:40][E][ota_http:155]: previous safe mode didn't succed. ota_http skipped
[10:46:40][VV][esp32.preferences:040]: s_pending_save: key: 99380598, len: 261
[10:46:40][D][main:699]: This message should be not displayed(reboot)
```
I burn firmware using legacy again and tried, the following log happen:
```
[11:03:12][D][button:010]: 'homehbh Firmware update' Pressed.
[11:03:12][VV][esp32.preferences:040]: s_pending_save: key: 99380598, len: 261
[11:03:12][V][ota_http:048]: restored pref ota_http_state: 40
[11:03:12][V][ota_http:052]: setting mode to progress
[11:03:12][D][esp32.preferences:114]: Saving 1 preferences to flash...
[11:03:12][VV][esp32.preferences:123]: Checking if NVS data 99380598 has changed
[11:03:12][V][esp32.preferences:126]: sync: key: 99380598, len: 261
[11:03:12][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[11:03:12][D][ota_http:054]: Trying to connect to https://thiennhienviet.org.vn/firmwares/homehbh.bin
[11:03:12][V][ota_http:072]: http begin successfull.
[11:03:12][VV][ota_http:076]: http client setReuse.
[11:03:12][V][ota_http:080]: http headers collected.
[11:03:13][V][ota_http:086]: http GET finished.
[11:03:13][E][ota_http:096]: Incorrect file size (-1) reported by http server (http status: -1). Aborting
[11:03:13][V][ota_http:079]: md5sum from received data initialized.
[11:03:13][W][ota_http:083]: BACKEND->begin error: 137
[11:03:13][E][ota_http:153]: Abort http con
[11:03:13][E][ota_http:155]: previous safe mode didn't succed. ota_http skipped
[11:03:13][VV][esp32.preferences:040]: s_pending_save: key: 99380598, len: 261
[11:03:13][D][main:699]: This message should be not displayed(reboot)
```
Please help, if possible, please share your email so I can get you to touch the system directly with thanks.
Best
Ngoc

2024-03-05 08:47 UTC, kbx81 commented on esphome/components/ota_http/ota_http.cpp
> +  ESP_LOGE(TAG, "previous safe mode didn't succed. ota_http skipped");
```suggestion
  ESP_LOGE(TAG, "Aborting http connection");
  this->http_end();
  ESP_LOGE(TAG, "Previous safe mode unsuccessful; skipped ota_http");
```

2024-03-05 08:48 UTC, kbx81 commented on esphome/components/ota_http/ota_http.cpp
> +      ESP_LOGI(TAG, "previous ota_http doesn't succed. Retrying");
```suggestion
      ESP_LOGI(TAG, "Previous ota_http unsuccessful. Retrying");
```

2024-03-05 08:49 UTC, kbx81 commented on esphome/components/ota_http/ota_http.cpp
> +      ESP_LOGE(TAG, "previous safe mode didn't succeed. ota_http skipped");
```suggestion
      ESP_LOGE(TAG, "Previous safe mode unsuccessful; skipped ota_http");
```

2024-03-05 08:50 UTC, kbx81 commented on esphome/components/ota_http/ota_http_arduino.cpp
> +    ESP_LOGV(TAG, "http begin successfull.");
```suggestion
    ESP_LOGV(TAG, "http begin successful");
```

2024-03-05 08:52 UTC, kbx81 commented on esphome/components/ota_http/ota_http_arduino.cpp
> +    ESP_LOGV(TAG, "http begin successfull.");
Semi-related -- there's really no reason to have periods at the end of all these error messages. It just consumes memory. 😇

2024-03-05 20:16 UTC, oarcher commented on esphome/components/ota_http/__init__.py
> +        if config[CONF_SAFE_MODE] is True:
Many thanks for starting the review, @kbx81 !

There is no redundancy here, because ` config[CONF_SAFE_MODE]`  is one of [`cv.Any(cv.boolean, "fallback")` ](https://github.com/oarcher/esphome/blob/5cdb52bdfdff4c7f8070fcf722feaf1023e6b170/esphome/components/ota_http/__init__.py#L83-L84).

Do you want me to add `if config[CONF_SAFE_MODE] or config[CONF_SAFE_MODE] == "fallback":` at the outside level ?

2024-03-05 23:03 UTC, oarcher commented
@paulsteigel , It seems that your device is unable to reach your http server. To see if it's related to `ota_http` you can check with an other way, with `http_request`.

Add the following to your config:
```yaml
http_request:
  id: http_data


button:
  - platform: template
    name: "http_request test"
    on_press:
      - http_request.get:
          url: https://thiennhienviet.org.vn/hello.txt
          verify_ssl: false
          on_response:
            then:
              - logger.log:
                  format: 'Response status: %d, Duration: %u ms'
                  args:
                    - status_code
                    - duration_ms
              - lambda: |-
                  ESP_LOGI("test", "content: %s", id(http_data).get_string());
```

And add a small text file with for example content `Hello from http server!` on your http server at https://thiennhienviet.org.vn/hello.txt.

You should get in the logs:

```
[00:00:40][D][main:269]: Response status: 200, Duration: 730 ms
[00:00:40][I][test:094]: content: Hello from http server!
```

2024-03-06 02:02 UTC, kbx81 commented on esphome/components/ota_http/__init__.py
> +        if config[CONF_SAFE_MODE] is True:
Ah, no worries -- this is fine. I'd overlooked the truthy "fallback" value. LGTM!

2024-03-06 11:19 UTC, paulsteigel commented
> @paulsteigel , It seems that your device is unable to reach your http server. To see if it's related to `ota_http` you can check with an other way, with `http_request`.
> 
> Add the following to your config:
> 
> ```yaml
> http_request:
>   id: http_data
> 
> 
> button:
>   - platform: template
>     name: "http_request test"
>     on_press:
>       - http_request.get:
>           url: https://thiennhienviet.org.vn/hello.txt
>           verify_ssl: false
>           on_response:
>             then:
>               - logger.log:
>                   format: 'Response status: %d, Duration: %u ms'
>                   args:
>                     - status_code
>                     - duration_ms
>               - lambda: |-
>                   ESP_LOGI("test", "content: %s", id(http_data).get_string());
> ```
> 
> And add a small text file with for example content `Hello from http server!` on your http server at https://thiennhienviet.org.vn/hello.txt.
> 
> You should get in the logs:
> 
> ```
> [00:00:40][D][main:269]: Response status: 200, Duration: 730 ms
> [00:00:40][I][test:094]: content: Hello from http server!
> ```

Hi @oarcher, my server have the functionality of url replacement (it is a wordpress site). I put the firmware into a folder name firmwares. The link is accessible using curl and wget. I used your recommendation and here is the response.
![image](https://github.com/esphome/esphome/assets/8839597/f4508ac6-4cdc-425c-9c32-6976e5fc9510)
I finally found that it might be the problem of https protocol. My site has SSl certificicate enabled, and that would be a problem.
Please help clarifying with thanks!
Best,
Ngoc

2024-03-06 19:00 UTC, oarcher commented
@paulsteigel , I'm sorry, but the test above using `http_request` show that the problem is not related to `ota_http`. I think it's a network problem, or a server problem.  You might get some more help from the community.

2024-03-07 00:35 UTC, kbx81 commented
@paulsteigel my tests were all based on HTTPS and I had no issues -- so unless your server is misconfigured (in which case I would expect you are having issues with more than just `ota_http`) I don't think SSL/TLS alone is the problem. "Connection refused" tends to make me think that either your server or something "in front" of it (like a reverse-proxy or firewall) is not allowing connections from your ESPs. It could also be that your ESP is not connecting to the server you believe it to be connecting to for whatever reason (DNS, some other network magic or otherwise).

2024-03-07 03:36 UTC, kbx81 commented on esphome/components/ota_http/ota_http.cpp
> +  if (pref_obj_.load(&pref_)) {
```suggestion
  if (this->pref_obj_.load(&pref_)) {
```
I see quite a few cases of this below -- please be sure to use the `this->` prefix when accessing member variables.

2024-03-07 04:59 UTC, paulsteigel commented
> @paulsteigel my tests were all based on HTTPS and I had no issues -- so unless your server is misconfigured (in which case I would expect you are having issues with more than just `ota_http`) I don't think SSL/TLS alone is the problem. "Connection refused" tends to make me think that either your server or something "in front" of it (like a reverse-proxy or firewall) is not allowing connections from your ESPs. It could also be that your ESP is not connecting to the server you believe it to be connecting to for whatever reason (DNS, some other network magic or otherwise).



> @paulsteigel , I'm sorry, but the test above using `http_request` show that the problem is not related to `ota_http`. I think it's a network problem, or a server problem. You might get some more help from the community.

Hi @kbx81 and @oarcher 
Many thanks for your information! In fact my http Server is placed behind a nginx server as a reverse proxy! I will do further test to see why the server refused the connection while curl and wget worked just fine!
All the best
Ngoc

2024-03-07 05:25 UTC, oarcher commented on esphome/components/ota_http/ota_http.cpp
> +  if (pref_obj_.load(&pref_)) {
Hopefully fixed with 4236221b9bccbdc140c48125dea83a70654f18c2

2024-03-07 07:57 UTC, oarcher commented
@paulsteigel , I don't think that there is a problem with your http server, as I am able to use your urls (for firmware and `http_request`) from my device.

You should double check your network configuration.

2024-03-08 00:54 UTC, kbx81 commented on esphome/components/ota_http/ota_http.h
> +  int ota_http_state;
I think this could be a `uint8_t` since it only appears to store one of the states you've defined above, all of which are `uint8_t`.

2024-03-08 00:54 UTC, kbx81 commented on esphome/components/ota_http/ota_http.h
> +  int ota_http_state;
```suggestion
  uint8_t ota_http_state;
```

2024-03-08 00:55 UTC, kbx81 commented on esphome/components/ota_http/ota_http.h
> +  int ota_http_state;
Alternatively maybe it should be an `enum`? 🤔

2024-03-08 21:42 UTC, oarcher commented on esphome/components/ota_http/ota_http.h
> +  int ota_http_state;
Yes, using `enum` has better logic. I've also removed `this->pref_obj_.load(&this->pref_)` at the beginning of the `flash` function, because reading from NVS is only needed at boot time for safe mode, and this is already done by `check_upgrade`:

https://github.com/esphome/esphome/blob/a340c04986590cebe797da8fef8d9ea931f0216c/esphome/components/ota_http/ota_http.cpp#L162-L164

see a340c04986590cebe797da8fef8d9ea931f0216c

2024-03-10 03:26 UTC, kbx81 commented on esphome/components/ota_http/ota_http.h
> +enum OtaHttpState { OTA_HTTP_STATE_OK, OTA_HTTP_STATE_PROGRESS, OTA_HTTP_STATE_SAFE_MODE, OTA_HTTP_STATE_ABORT };
```suggestion
enum OtaHttpState {
  OTA_HTTP_STATE_OK,
  OTA_HTTP_STATE_PROGRESS,
  OTA_HTTP_STATE_SAFE_MODE,
  OTA_HTTP_STATE_ABORT,
};
```

2024-03-10 03:27 UTC, kbx81 commented on esphome/components/ota_http/ota_http.h
> +enum OtaHttpState { OTA_HTTP_STATE_OK, OTA_HTTP_STATE_PROGRESS, OTA_HTTP_STATE_SAFE_MODE, OTA_HTTP_STATE_ABORT };
If you include the trailing comma, the linter won't complain and it's still valid. Better for readability and for source control.

2024-03-11 02:46 UTC, jayge91 commented
Hosting test.bin on nginx server, http request code works fine, but ota_http on esp8266 returns not enough space: 

`[D][button:010]: 'Update over HTTP' Pressed.
[D][main:287]: Contacting Update Server...
[V][ota_http:048]: Setting mode to progress
[D][ota_http:054]: Trying to connect to http://***@172.16.0.91/test/test.bin
[HTTP-Client][begin] url: http://***@172.16.0.91/test/test.bin
[HTTP-Client][begin] host: 172.16.0.91 port: 80 url: /test/test.bin
[V][ota_http:072]: http begin successful
[VV][ota_http:076]: http client setReuse.
[V][ota_http:080]: http headers collected.
[HTTP-Client][sendRequest] type: 'GET' redirCount: 0
[hostByName] Host: 172.16.0.91 is a IP!
[HTTP-Client] connected to 172.16.0.91:80
[HTTP-Client] sending request header
-----
GET /test/test.bin HTTP/1.1
Host: 172.16.0.91
User-Agent: ESP8266HTTPClient
Accept-Encoding: identity;q=1,chunked;q=0.1,*;q=0
Authorization: Basic am9uYXRob246Q0JNMTk5NlppcHBlcg==
Connection: keep-alive
Content-Length: 0

[D][ota_http:101]: firmware is 657088 bytes length.
[V][ota_http:075]: md5sum from received data initialized.
sleep disable
[begin] roundedSize:       0x000A1000 (659456)
[begin] updateEndAddress:  0x000FB000 (1028096)
[begin] currentSketchSize: 0x000A1000 (659456)
ERROR[4]: Not Enough Space
[W][ota_http:079]: BACKEND->begin error: 136
[E][ota_http:155]: Aborting http connection
[HTTP-Client][end] still data in buffer (5582), clean up.
[HTTP-Client][end] tcp keep open for reuse
[E][ota_http:157]: Previous safe mode unsuccessful; skipped ota_http
[D][main:292]: This message should be not displayed(reboot)`

Is this a true limitation of my hardware? Or have I misconfigured something? I will be testing with an ESP32 and will update once done.

2024-03-11 20:49 UTC, oarcher commented
@jayge91, You are the first facing this error. This error is raised before any data is wrote to flash, at
https://github.com/esphome/esphome/blob/63c1e6a4a09d89f072e35dacd8acd95660701ddc/esphome/components/ota_http/ota_http.cpp#L77

So my first guest is that you are not using the right firmware. Can you check that you firmware is `legacy format` or `firmware.bin`, not `modern format` or `firmware-factory.bin`?  It should start with byte `0xE9` (you can check with a tool like `ghex` under linux).

As the bad `firmware-factory.bin` is larger, maybe the error comes from there.


Once you have checked that, can you confirm that the regular OTA ( not `ota_http`) works as expected ?
Using the regular OTA, those logs can be useful:
```
[21:03:55][V][ota:185]: OTA features is 0x01
[21:03:55][V][ota:268]: OTA size is 1119328 bytes
``` 
Can you compare the size between regular and http OTA ?


You can also check with a gziped firmware `firmware.bin.gz`. I've successfully checked it on some devices, and as it make the size smaller, you might get better results.

Please also give me the full description of your hardware. I know it's a 8266, but it might help to have more specs.

2024-03-11 21:37 UTC, jesserockz commented
> So my first guest is that you are not using the right firmware. Can you check that you firmware is legacy format or firmware.bin, not modern format or firmware-factory.bin? It should start with byte 0xE9 (you can check with a tool like ghex under linux).
>
> As the bad firmware-factory.bin is larger, maybe the error comes from there.

@oarcher For esp8266, legacy and modern is the exact same file =)

https://github.com/esphome/esphome/blob/8cb689b58c4fa6279bcc765f93f86510ec940289/esphome/components/esp8266/post_build.py.script#L7-L11

2024-03-18 07:35 UTC, kbx81 commented
I've pushed a couple of updates to this which 1. implement checking of MD5 to ensure firmware integrity, and 2. enable certificate validation when the IDF framework is used.

Note that I've removed the `verify_ssl` option in favor of including a flag `exclude_certificate_bundle` in the parent `ota_http` component; this allows forcing the exclusion of the certificate bundle, saving space on (and potentially required for) memory-constrained devices. The default is to include the certificate bundle (most secure).

I'd still like to sort out if we can include certificate validation when using Arduino, as our preference is to make this as secure as reasonably possible.

So far, I've only been testing this on an ESP32 -- I'll try to test on some other hardware, but additional testers are welcome!

2024-03-18 08:33 UTC, kbx81 commented
New example config:
```yaml
button:
  - platform: template
    name: Firmware update
    on_press:
      then:
        - ota_http.flash:
            md5_url: https://your.webserver.net/local/esphome/firmware.md5
            url: https://your.webserver.net/local/esphome/firmware.bin
        - logger.log: "This message should be not displayed (reboot)"
```

2024-03-18 08:39 UTC, Alphaemef commented
Cheesy fracking christ, I wish I was up to par to contribute to this. What marvellous job you guys are doing.

2024-03-19 02:55 UTC, arthurkomatsu commented
Awesome work @kbx81 

Can you make the `md5_url` / `url` fields templatable? I'm thinking of the following use case:
```yaml
text:
  - platform: template
    name: "OTA"
    optimistic: true
    id: autogen_ota_text
    mode: text
    update_interval: 0s
    restore_value: false
    on_value:
      then:
        - ota_http.flash:
            url: !lambda "return x;"
```

2024-03-19 03:34 UTC, kbx81 commented
> Awesome work @kbx81

Thanks! 🍻

> Can you make the `md5_url` / `url` fields templatable?

[They already are.](https://github.com/oarcher/esphome/blob/a6966d49dca0197f195b6064c354c3ef32673273/esphome/components/ota_http/__init__.py#L174-L177)

2024-03-19 04:03 UTC, arthurkomatsu commented
> [They already are.](https://github.com/oarcher/esphome/blob/a6966d49dca0197f195b6064c354c3ef32673273/esphome/components/ota_http/__init__.py#L174-L177)

You are right, I made a mistake, it works like a charm!

2024-03-19 05:48 UTC, kbx81 commented
Tested with ESP32, ESP32-C3 and ESP8266 -- I pushed a tiny fix for the 8266, but otherwise everything seems to be working well!

The last bit that would be great to work in is certificate validation for Arduino. I'm looking into it... 😁

2024-03-19 16:27 UTC, Alphaemef commented
So im having trouble with the new stuff. 

```
  - platform: template
    name: "ESP32 Firmware Update"
    disabled_by_default: true
    discovery: false
    entity_category: config
    internal: false #IMPORTANT
    icon: mdi:alert-decagram
    on_press:
      then:
        - ota_http.flash:
            md5_url: !lambda return "https:// id(updateurl).state/${name}_${flashfile}.md5";
            url: !lambda return "https://id(updateurl).state/${name}_${flashfile}.bin";
        - logger.log: "This message should be not displayed(reboot)"

external_components:
  - source: github://pr#5586
    components: [ ota_http ]
ota_http:
```

I keep getting md5 sum error. 

To create the md5 sum, I create the legacy flashfile, then use terminal to create an md5 sum file 
`md5 -q name_flashfile.bin > name_flashfile.md5 `

I get this error after trying a few times. 
```
[17:24:39][D][button:010]: 'ESP32 Firmware Update' Pressed.
[17:24:39][D][esp-idf:000]: E (966695) esp-tls: [sock=60] delayed connect error: Connection reset by peer

[17:24:39][D][esp-idf:000]: E (966703) esp-tls: Failed to open new connection

[17:24:39][D][esp-idf:000]: E (966708) TRANSPORT_BASE: Failed to open a new connection

[17:24:39][D][esp-idf:000]: E (966714) HTTP_CLIENT: Connection failed, sock < 0

[17:24:39][E][ota_http:053]: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT
[17:24:39][E][ota_http:197]: Incorrect file size (150) for MD5 reported by HTTP server. Aborting
[17:24:39][D][main:3411]: This message should be not displayed(reboot)
```


But if I reboot / reflash, I get this error:
```
[17:26:38][D][button:010]: 'ESP32 Firmware Update' Pressed.
[17:26:38][D][esp-idf:000]: I (40894) esp-x509-crt-bundle: Certificate validated

[17:26:41][D][esp-idf:000]: I (43700) HTTP_CLIENT: Body received in fetch header state, 0x3ffee0b0, 33

[17:26:41][E][ota_http:197]: Incorrect file size (33) for MD5 reported by HTTP server. Aborting
[17:26:41][D][main:3411]: This message should be not displayed(reboot)
```

I guess the question is two-fold:
1: Why does the cert fail on retries, without reboot, 
2: Why isn't the checksum valid ?

2024-03-19 17:19 UTC, Alphaemef commented
OK, one step closer:
There was indeed an extra "new line" at the end of the checksum. when I remove that, I get the following right before the esp32 reboots without having updated. 

```
[18:17:13][D][button:010]: 'ESP32 Firmware Update' Pressed.
[18:17:13][D][esp-idf:000]: I (34305) esp-x509-crt-bundle: Certificate validated

[18:17:16][D][esp-idf:000]: I (36717) HTTP_CLIENT: Body received in fetch header state, 0x3ffec96c, 32

[18:17:16][D][esp-idf:000]: I (36957) esp-x509-crt-bundle: Certificate validated

```

2024-03-20 02:01 UTC, kbx81 commented
> OK, one step closer: There was indeed an extra "new line" at the end of the checksum. when I remove that, I get the following right before the esp32 reboots without having updated.
> 
> ```
> [18:17:13][D][button:010]: 'ESP32 Firmware Update' Pressed.
> [18:17:13][D][esp-idf:000]: I (34305) esp-x509-crt-bundle: Certificate validated
> 
> [18:17:16][D][esp-idf:000]: I (36717) HTTP_CLIENT: Body received in fetch header state, 0x3ffec96c, 32
> 
> [18:17:16][D][esp-idf:000]: I (36957) esp-x509-crt-bundle: Certificate validated
> ```

@Alphaemef that all looks good up to and including that last line, but what immediately follows that last line? There should be some additional messages and it would be helpful to see those.

I'll tinker a bit and see if I can make it a bit less fussy about the MD5 file. 😄

2024-03-20 06:36 UTC, Alphaemef commented
tha

> > OK, one step closer: There was indeed an extra "new line" at the end of the checksum. when I remove that, I get the following right before the esp32 reboots without having updated.
> > ```
> > [18:17:13][D][button:010]: 'ESP32 Firmware Update' Pressed.
> > [18:17:13][D][esp-idf:000]: I (34305) esp-x509-crt-bundle: Certificate validated
> > 
> > [18:17:16][D][esp-idf:000]: I (36717) HTTP_CLIENT: Body received in fetch header state, 0x3ffec96c, 32
> > 
> > [18:17:16][D][esp-idf:000]: I (36957) esp-x509-crt-bundle: Certificate validated
> > ```
> 
> @Alphaemef that all looks good up to and including that last line, but what immediately follows that last line? There should be some additional messages and it would be helpful to see those.
> 
> I'll tinker a bit and see if I can make it a bit less fussy about the MD5 file. 😄


Thanks. Actually no further messages. Often followed by reboot. Found a way around, which was to set the exclude_certificate_bundle flag to true. 

So I guess its doing something with SSL, though I thought it shouldn't ?


NB: In my particular use case, I am connected to the esp32 though tls, and the esp32 has my CA key in the yaml config. Both MQTT and fileserver are hosted on the same domain / ip. 

In that scenario, it would be great if ota_http could apply the same server validation info. For me the issue is, with ota_http, if someone somehow got a mqtt message in, it would be fairly trivial to hijack the unit with malicious firmware. 

In my case, I use a temptable URL so that will still be an issue, but maybe a bit less with cert validation.

2024-03-20 08:39 UTC, kbx81 commented
So if you're using a custom CA, you're not going to benefit from the changes I've added here.

We're setting `CONFIG_MBEDTLS_CERTIFICATE_BUNDLE` when you build with IDF, which just enables/includes a default certificate bundle [as discussed here](https://docs.espressif.com/projects/esp-idf/en/v5.2.1/esp32/api-reference/protocols/esp_crt_bundle.html).

This is designed to facilitate the use of common public CAs, not custom/private/internal CAs. You're on the right track having added your CA's key to your config, but since that's not a part of the certificate bundle we're pointing the API at, it really doesn't accomplish anything here -- at least, not for now. I don't see any reason why we couldn't eventually build in support for doing that, but this PR is pretty big already. If there's sufficient demand and/or if someone just jumps in and does it, I don't see any reason why we wouldn't accept that PR. 😇

2024-03-21 09:30 UTC, tomatensaus commented
Instead of having a  "md5_url" can I not just specify the md5sum. 

I check for an updates and I have both the url of the update + md5sum ready to flash.

Do I need to pipe the md5sum to another URL location just to fetch it again when I flash?

2024-03-21 09:36 UTC, kbx81 commented
> Instead of having a "md5_url" can I not just specify the md5sum.

That doesn't really make sense. What if you upload a new `firmware.bin` to your web server? Then you cannot change the MD5 on the device without re-flashing it. Chicken and egg. The file with he MD5 needs to be retrieved from the web server along with the firmware.

> I check for an updates and I have both the url of the update + md5sum ready to flash.
> 
> Do I need to pipe the md5sum to another URL location just to fetch it again when I flash?

Not sure I understand your questions here.

2024-03-21 10:40 UTC, tomatensaus commented
Let me explain my usecase:

I have a rest service, the micro-controller sends through the info of the current firmware and the device it is connected to, and then the rest service checks for an update. 

If available it sends the url where it is available and the corresponding md5sum to be flashed.

2024-03-21 10:40 UTC, Alphaemef commented
Hmm not exactly sure I follow. I understand you use a certificate bundle, but my server TLS key is not self-signed or anything like that. I use lets-encrypt for the certificate renewal, and the CA certificate is from 
https://letsencrypt.org/certificates/ ( Im almost certain). 

I hate that I don't understand more of this than than I do. But can you elaborate just a bit:

So when my ESP32 connects to my MQTT server I know its an encrypted connection, and it verifies the identity of the server via the CA (so it can't be spoofed). 

But when it comes to connecting to the webserver via ota_http: Since its connecting through https, im still fairly certain it connects with an encrypted connection, but since it only work with the exclude_certificate_bundle flag set to true, then I guess it doesn't verifies the identity of the server before getting the firmware file. 
Is this correct ?

Considering that my webserver is signed via lets encrypt (that would be a public signing right ?) then shouldn't the CA bundle be able to verify my server as well ?

2024-03-21 10:43 UTC, Alphaemef commented
> Let me explain my usecase:
> 
> I have a rest service, the micro-controller sends through the info of the current firmware and the device it is connected to, and then the rest service checks for an update.
> 
> If available it sends the url where it is available and the corresponding md5sum to be flashed.

You can just send the location of md5sum file as a URL exactly like you do for the actual *.bin URL. Whatever script you use to create the flash file, just make a command to calc the md5 sum of the compiled flashfile and echo that into a md5 file with the same filename as the flash file but with a .md5 suffix

2024-03-21 11:04 UTC, paulsteigel commented
Hi All,
Many thanks to @Olivier for your work and the reviewing team on the the component. Following the light of my initial question when hitting this page. I knew that Olivier has done a lot of work to have the component be at this state. However, no matter i tried to check my network, I have never been successful have firmware updated. 
I would like to raise my idea to @Olivier and might be the team is:
Can we link this to the Install command of Esphome so Esphome will automate the process.
If user specify ota then esphome will flash over ota as usual. But if user does not have ota but mqtt, can the install routine do the work instead using the sequence that built in the Esphome docker.
I assume it would be like this:
1. Click install
2. Esphome build firmware and publish it on a topic: firmware (encoded)
3. Sending a command to esp device and it will download the firmware via mqtt topic and then apply the new firmware.
I saw this https://sming.readthedocs.io/en/latest/_inc/Sming/Libraries/OtaUpgradeMqtt/index.html.
Many thanks for your attention and please be sorry disappointing you then.
In the mean time, I will try seeing a way to do this updating, uploading firmware to site and learning how to use it.
Best,
Ngoc

2024-03-21 22:36 UTC, kbx81 commented
> Hmm not exactly sure I follow. I understand you use a certificate bundle, but my server TLS key is not self-signed or anything like that. I use lets-encrypt for the certificate renewal, and the CA certificate is from [letsencrypt.org/certificates](https://letsencrypt.org/certificates/) ( Im almost certain).

@Alphaemef interesting -- I've been using LE certificates as I've been testing it here and it's been working just fine. 🤔

> So when my ESP32 connects to my MQTT server I know its an encrypted connection, and it verifies the identity of the server via the CA (so it can't be spoofed).

I can't speak to what MQTT is doing -- I don't use it myself and I have no experience with it at all. 😅 

> But when it comes to connecting to the webserver via ota_http: Since its connecting through https, im still fairly certain it connects with an encrypted connection, but since it only work with the exclude_certificate_bundle flag set to true, then I guess it doesn't verifies the identity of the server before getting the firmware file. Is this correct ?

When you use HTTPS, the connection is always encrypted. Certificate verification takes the extra step of ensuring the identity of the remote server so that you can be certain that you're connecting to the server you think you're connecting to.

Do you have a reverse proxy (HAProxy, Nginx, etc.) or anything else that sits "in front" of your web server? Perhaps something is configured in a way that makes MQTT happy but isn't quite right for the HTTPS connection that the IDF framework is creating? Are you missing an intermediate certificate, perhaps? I've absolutely personally seen cases where a web server is misconfigured such that it provides an incomplete certificate chain to clients, which results in some things working (most desktop browsers) but others coughing up errors (embedded and some mobile devices).

If your web server is publicly exposed (or if you can briefly publicly expose it for testing), maybe try running an SSL/TLS checker against it, such as https://letsdebug.net and see if any errors come back.

> Considering that my webserver is signed via lets encrypt (that would be a public signing right ?) then shouldn't the CA bundle be able to verify my server as well ?

I would expect so -- it's working for me here without any issues already. 😄

2024-03-21 22:47 UTC, Alphaemef commented
Thanks for the response :)

Yes this is my understanding as well. I haven't had issued with the server so far, but ye its behind nginx proxy manager. Just performed a test and there was no issue (using the DNS test). The server setup might be at fault, but that doesn't explain the lack of error message in the log right ?

2024-03-21 22:51 UTC, kbx81 commented
> Just performed a test and there was no issue (using the DNS test).

@Alphaemef either of the other tests report any errors? On my setup, I can run all three options and they all pass. Just curious. 😄

2024-03-21 22:53 UTC, kbx81 commented
Regarding the messages in the logs (or lack thereof), I'll have a look and see if I can sprinkle something in to print more information if the connection somehow fails. 😇

2024-03-21 23:05 UTC, Alphaemef commented
> Regarding the messages in the logs (or lack thereof), I'll have a look and see if I can sprinkle something in to print more information if the connection somehow fails. 😇

The http request fails, but for good reason. Connections to my main domain are redirected to a honey pot, so I only accept very particular paths (I have several hundred ESP32, all calling home, and they each target their own folder with own permissions). 

ANd NPM is a bi*** to set up, since changes in the config files are not seen in UI, and changes in UI overwrite everything in the config file. 

So wouldn’t expect HTTP request to go through. 

Whats weird for me is the error messages...


by the way... it seems its working now. The logs looks like it just hangs (I don't get progress) but the firmware version changes correctly... super strange. 
<img width="879" alt="Screenshot 2024-03-22 at 00 04 01" src="https://github.com/esphome/esphome/assets/113418735/9a7152c4-3e97-4494-baef-13a6dafee42f">

2024-03-21 23:19 UTC, oarcher commented
Just pushed a commit to skip CONF_ESP8266_DISABLE_SSL_SUPPORT if CONF_ESP8266_DISABLE_SSL_SUPPORT, so we just need to have 
```yaml
ota_http:
  esp8266_disable_ssl_support: true
``` 

on 8266 without https

2024-03-21 23:19 UTC, Alphaemef commented
back to not working... mind you the only thing I change serverwise, is open the port and close it. Exact same log. "cert validated" then silence for a while, then a reboot without update.

2024-03-21 23:24 UTC, kbx81 commented
@Alphaemef here's a snip from the logs on my ESP32; I'm connected to it via wifi (as opposed to serial) when this was captured:

```
[18:16:04][D][button:010]: 'Firmware update' Pressed.
[18:16:04][D][esp32.preferences:114]: Saving 1 preferences to flash...
[18:16:04][D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[18:16:04][D][esp-idf:000]: I (67409) esp-x509-crt-bundle: Certificate validated

[18:16:05][D][esp-idf:000]: I (68367) esp-x509-crt-bundle: Certificate validated

[18:16:06][D][ota_http:072]: MD5 expected: 90765c831b9046f7e7fd786916666738
[18:16:07][I][ota_http:114]: Progress: 0.1%
[18:16:08][I][ota_http:114]: Progress: 14.9%
[18:16:09][I][ota_http:114]: Progress: 30.0%
[18:16:10][I][ota_http:114]: Progress: 43.8%
[18:16:11][I][ota_http:114]: Progress: 55.9%
[18:16:12][I][ota_http:114]: Progress: 69.4%
[18:16:13][I][ota_http:114]: Progress: 84.0%
[18:16:14][I][ota_http:114]: Progress: 92.0%
[18:16:14][I][ota_http:114]: Progress: 100.0%
[18:16:14][I][ota_http:121]: Done in 11 seconds
[18:16:15][D][esp-idf:000]: I (78037) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=47110h (291088) map

[18:16:15][D][esp-idf:000]: I (78144) esp_image: segment 1: paddr=00057138 vaddr=3ffb0000 size=03620h ( 13856) 

[18:16:15][D][esp-idf:000]: I (78156) esp_image: segment 2: paddr=0005a760 vaddr=40080000 size=058b8h ( 22712) 

[18:16:15][D][esp-idf:000]: I (78171) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=aa450h (697424) map

[18:16:15][D][esp-idf:000]: I (78416) esp_image: segment 4: paddr=0010a478 vaddr=400858b8 size=0f4f4h ( 62708) 

[18:16:15][D][esp-idf:000]: I (78446) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=47110h (291088) map

[18:16:15][D][esp-idf:000]: I (78555) esp_image: segment 1: paddr=00057138 vaddr=3ffb0000 size=03620h ( 13856) 

[18:16:15][D][esp-idf:000]: I (78567) esp_image: segment 2: paddr=0005a760 vaddr=40080000 size=058b8h ( 22712) 

[18:16:15][D][esp-idf:000]: I (78581) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=aa450h (697424) map

[18:16:15][D][esp-idf:000]: I (78827) esp_image: segment 4: paddr=0010a478 vaddr=400858b8 size=0f4f4h ( 62708) 

[18:16:15][I][ota_http:151]: OTA update completed
[18:16:15][I][app:134]: Rebooting safely...
[18:16:15][D][esp32.preferences:114]: Saving 2 preferences to flash...
[18:16:15][D][esp32.preferences:142]: Saving 2 preferences to flash: 0 cached, 2 written, 0 failed
INFO Processing expected disconnect from ESPHome API for esp32-base @ 10.100.0.102
WARNING Disconnected from API
```

This is what I'd expect a successful `ota_http` to look like. I'm still puzzled about what's going on with your environment. 🤔

2024-03-21 23:28 UTC, Alphaemef commented
> Just pushed a commit to skip CONF_ESP8266_DISABLE_SSL_SUPPORT if CONF_ESP8266_DISABLE_SSL_SUPPORT, so we just need to have
> 
> ```yaml
> ota_http:
>   esp8266_disable_ssl_support: true
> ```
> 
> on 8266 without https

just to make sure I got it correctly:
us with esp32 with/withot https can just ignore any flags under ota_http: ?

> @Alphaemef here's a snip from the logs on my ESP32; I'm connected to it via wifi (as opposed to serial) when this was captured:
> 
> ```
> [18:16:04][D][button:010]: 'Firmware update' Pressed.
> [18:16:04][D][esp32.preferences:114]: Saving 1 preferences to flash...
> [18:16:04][D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
> [18:16:04][D][esp-idf:000]: I (67409) esp-x509-crt-bundle: Certificate validated
> 
> [18:16:05][D][esp-idf:000]: I (68367) esp-x509-crt-bundle: Certificate validated
> 
> [18:16:06][D][ota_http:072]: MD5 expected: 90765c831b9046f7e7fd786916666738
> [18:16:07][I][ota_http:114]: Progress: 0.1%
> [18:16:08][I][ota_http:114]: Progress: 14.9%
> [18:16:09][I][ota_http:114]: Progress: 30.0%
> [18:16:10][I][ota_http:114]: Progress: 43.8%
> [18:16:11][I][ota_http:114]: Progress: 55.9%
> [18:16:12][I][ota_http:114]: Progress: 69.4%
> [18:16:13][I][ota_http:114]: Progress: 84.0%
> [18:16:14][I][ota_http:114]: Progress: 92.0%
> [18:16:14][I][ota_http:114]: Progress: 100.0%
> [18:16:14][I][ota_http:121]: Done in 11 seconds
> [18:16:15][D][esp-idf:000]: I (78037) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=47110h (291088) map
> 
> [18:16:15][D][esp-idf:000]: I (78144) esp_image: segment 1: paddr=00057138 vaddr=3ffb0000 size=03620h ( 13856) 
> 
> [18:16:15][D][esp-idf:000]: I (78156) esp_image: segment 2: paddr=0005a760 vaddr=40080000 size=058b8h ( 22712) 
> 
> [18:16:15][D][esp-idf:000]: I (78171) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=aa450h (697424) map
> 
> [18:16:15][D][esp-idf:000]: I (78416) esp_image: segment 4: paddr=0010a478 vaddr=400858b8 size=0f4f4h ( 62708) 
> 
> [18:16:15][D][esp-idf:000]: I (78446) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=47110h (291088) map
> 
> [18:16:15][D][esp-idf:000]: I (78555) esp_image: segment 1: paddr=00057138 vaddr=3ffb0000 size=03620h ( 13856) 
> 
> [18:16:15][D][esp-idf:000]: I (78567) esp_image: segment 2: paddr=0005a760 vaddr=40080000 size=058b8h ( 22712) 
> 
> [18:16:15][D][esp-idf:000]: I (78581) esp_image: segment 3: paddr=00060020 vaddr=400d0020 size=aa450h (697424) map
> 
> [18:16:15][D][esp-idf:000]: I (78827) esp_image: segment 4: paddr=0010a478 vaddr=400858b8 size=0f4f4h ( 62708) 
> 
> [18:16:15][I][ota_http:151]: OTA update completed
> [18:16:15][I][app:134]: Rebooting safely...
> [18:16:15][D][esp32.preferences:114]: Saving 2 preferences to flash...
> [18:16:15][D][esp32.preferences:142]: Saving 2 preferences to flash: 0 cached, 2 written, 0 failed
> INFO Processing expected disconnect from ESPHome API for esp32-base @ 10.100.0.102
> WARNING Disconnected from API
> ```
> 
> This is what I'd expect a successful `ota_http` to look like. I'm still puzzled about what's going on with your environment. 🤔

Yeah that's how it looked before here as well. I have units on local and external. All behave the same way. I receive the log output through both API and through MQTT and it shows the same. 

My board is esp32dev, framework ESP-IDF
and exclude certs are NOT set to true. 
# exclude_certificate_bundle: true

2024-03-21 23:37 UTC, oarcher commented
for MD5, I think that since it's now retrieved  from url, we should just write it with `ota_http::OtaHttpComponent::BACKEND->set_update_md5(this->md5_expected_);`, and skip on the fly `md5_receive.init();`, `md5_receive.add(buf, bufsize);`, etc..

In fact, md5 calculation is also done internally in `Updater.cpp`:
https://github.com/espressif/arduino-esp32/blob/29ede4826cee8da71bc4c161486f9672a957062c/libraries/Update/src/Updater.cpp#L407

2024-03-21 23:39 UTC, kbx81 commented
@Alphaemef I took another look at letsdebug.net and it isn't doing what I thought it was doing. Try testing your server again with [sslchecker](https://www.sslchecker.com/sslchecker) and [sslshopper](https://www.sslshopper.com/ssl-checker.html) (just for a second opinion). If everything doesn't come back green, you may have an SSL/TLS issue.

That aside, it sounds like you've got Nginx set up to do some tricky stuff with incoming connections. Any chance this could be causing some unintended behavior with these connections? Not trying to pick on your setup, but I've done enough of this to know that sometimes things can slip through cracks. 😅 I'd be curious to know what happens if tested without those rules in place, so incoming connections just go straight through to the web server, with no ACLs, rewriting, etc. I'm kind of grasping at straws here; I hope you don't mind me tossing out ideas. 😇

2024-03-21 23:42 UTC, kbx81 commented
> for MD5, I think that since it's now retrieved from url, we should just write it with `ota_http::OtaHttpComponent::BACKEND->set_update_md5(this->md5_expected_);`, and skip on the fly `md5_receive.init();`, `md5_receive.add(buf, bufsize);`, etc..
> 
> In fact, md5 calculation is also done internally in `Updater.cpp`: [espressif/arduino-esp32@`29ede48`/libraries/Update/src/Updater.cpp#L407](https://github.com/espressif/arduino-esp32/blob/29ede4826cee8da71bc4c161486f9672a957062c/libraries/Update/src/Updater.cpp#L407)

@oarcher I thought so too -- until I tested with Arduino and realized it doesn't care at all what the MD5 is set to. 🙄  So I left in the code that manually computes it and am just using that.

Feel free to play around with it if you like, maybe I was doing something wrong, but I really don't think so.

2024-03-21 23:59 UTC, Alphaemef commented
> @Alphaemef I took another look at letsdebug.net and it isn't doing what I thought it was doing. Try testing your server again with [sslchecker](https://www.sslchecker.com/sslchecker) and [sslshopper](https://www.sslshopper.com/ssl-checker.html) (just for a second opinion). If everything doesn't come back green, you may have an SSL/TLS issue.
> 
> That aside, it sounds like you've got Nginx set up to do some tricky stuff with incoming connections. Any chance this could be causing some unintended behavior with these connections? Not trying to pick on your setup, but I've done enough of this to know that sometimes things can slip through cracks. 😅 I'd be curious to know what happens if tested without those rules in place, so incoming connections just go straight through to the web server, with no ACLs, rewriting, etc. I'm kind of grasping at straws here; I hope you don't mind me tossing out ideas. 😇

Absolutely fine with the ideas!

Will setup a 2nd server and test tomorrow evening. Again, the weird parts are the logs which seemingly are working. And now even with the flag to exclude the SSL set to true, It still won't update. 

In contrast all the units with the old firmware update like a charm.

2024-03-22 00:18 UTC, Alphaemef commented
Can I just suggest, whenever you get around to it to update the documentation ? Im starting to think I need a gold standard..

2024-03-22 00:20 UTC, kbx81 commented
Docs are updated already @Alphaemef 😄 (just did it yesterday, haha)

2024-03-22 00:33 UTC, kbx81 commented
> Again, the weird parts are the logs which seemingly are working. And now even with the flag to exclude the SSL set to true, It still won't update.

It should absolutely update if `exclude_certificate_bundle` is set to `true` -- at that point, it's not doing anything differently than it was before the changes I made. If _that_ even fails, it makes me a lot more suspicious of your setup...I'm just at a loss for what would be causing that. 🤔

Have you tried cleaning your build files? Also, if you're using it as an external component, try adding `refresh`, like this:

```yaml
external_components:
  - source: github://pr#5586
    components: [ ota_http ]
    refresh: 0s
```

2024-03-22 05:51 UTC, Alphaemef commented
Alright May be about closer! The non ssl works again now. NPM did what it usually does and wiped its own config. That’s fixed. 

And may have found the issue. I can’t check right now. But IIRC my NPM ID set to restrict HTTP to 1.1. And it may look like OTA HTTP is accessing with 1.0. I’m not sure if that’s an issue, nor why only for SSL. But will test tonight. 

Also: it doesn’t look like OTA_HTTP has any error output when there is server con errors. That could be helpful for all the forum post of people who just have weird server settings like me :)

2024-03-22 06:53 UTC, kbx81 commented
> Also: it doesn’t look like OTA_HTTP has any error output when there is server con errors. That could be helpful for all the forum post of people who just have weird server settings like me :)

@Alphaemef are you sure the connection is actually failing and not just hanging/stalling? There's logging _all over_ the component -- take a look [here](https://github.com/esphome/esphome/pull/5586/files#diff-27f52552e77ae8e847311509844b5f6a0ed8c5f92516be31a2a5124f207b414b) starting on line 46. Anything that behaves abnormally should produce some kind of message. I'm really puzzled as to why you're not seeing more messages -- only thing I can think of right now is if something is just stalling the connection until it eventually times out and gives up. 🤔 Have you changed the log level in your config, perhaps?

2024-03-22 10:51 UTC, Alphaemef commented
Yes hanging/stalling  is probably correct. It’s just that it’s the same thing that happens if the server doesn’t give access due to permissions (I.e the NPM misconfig I had last night, or closed port). 

I set the log level at verbose for OTA_HTTP and error for MQTT and modbus. So should be able to see most messages. But all messages stop until the chip reboots. A stall /hang sounds reasonable.

2024-03-22 11:00 UTC, kbx81 commented
When you're watching the logs from your ESP, are you connected via serial or over wifi?

2024-03-22 11:44 UTC, Alphaemef commented
> When you're watching the logs from your ESP, are you connected via serial or over wifi? Serial would be preferred if you're not already connecting that way.

WiFi. 

I could flash a spare unit and connect through serial tonight

2024-03-24 04:36 UTC, Alphaemef commented
Did some testing. 

Practically every run, it freezes when trying to OTA update. But some times it succeeds on the safemode reattempt. But not always. here are the screenshots. 
![Screenshot 2024-03-24 at 05 23 42](https://github.com/esphome/esphome/assets/113418735/48d763ed-f7d9-49c5-b21d-dec841d3e2bc)
![Screenshot 2024-03-24 at 05 24 02](https://github.com/esphome/esphome/assets/113418735/807f38b0-0a4e-423e-9799-b21a19fad736)
![Screenshot 2024-03-24 at 05 35 43](https://github.com/esphome/esphome/assets/113418735/a4ebea67-3565-4693-ab9b-b072c587e338)
![Screenshot 2024-03-24 at 05 35 51](https://github.com/esphome/esphome/assets/113418735/e31801dd-70bf-47ce-89fa-167d71ea791a)

2024-03-24 04:41 UTC, Alphaemef commented
And this is NPM log when it _doesnt_ work 

```
[24/Mar/2024:05:32:44 +0100] - 200 200 - GET https domain "/local/path/filename.md5.md5" [Client 192.168.1.1] [Length 33] [Gzip -] [Sent-to 192.168.1.255] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:05:32:56 +0100] - 200 200 - GET https domain "/local/path/filename.md5" [Client 192.168.1.1] [Length 33] [Gzip -] [Sent-to 192.168.1.255] "ESP32 HTTP Client/1.0" "-"
```

But on the failed attempts there doesn't seem to be a request for the bin file. 

Is it crashing during the md5 check? Perhaps memory issue ?

2024-03-24 10:35 UTC, kbx81 commented
@Alphaemef any idea what `HTTP_CLIENT: Body received in fetch header state, 0x3ffee2e0, 33` means? I don't get that here with my setup. Makes me wonder if your NPM is doing something strange.

Also, in your second screenshot, I see what appears to be the file size (33, 631) reported for each request. 33 bytes makes sense for the MD5 file, but the file size (631) reported for the second request (which should be for the firmware binary file) seems awfully small. Are you sure you're using the correct firmware file? The minimal firmware I've created for my ESP32 results in a `firmware.bin` file that's about 1.1 MB.

The watchdog reset makes me think that your connection is hanging/stalling as I mentioned before. Still not sure why that would be happening, though -- I can't seem to reproduce that behavior here.

2024-03-24 11:57 UTC, Alphaemef commented
> @Alphaemef any idea what `HTTP_CLIENT: Body received in fetch header state, 0x3ffee2e0, 33` means? I don't get that here with my setup. Makes me wonder if your NPM is doing something strange.
> 
> Also, in your second screenshot, I see what appears to be the file size (33, 631) reported for each request. 33 bytes makes sense for the MD5 file, but the file size (631) reported for the second request (which should be for the firmware binary file) seems awfully small. Are you sure you're using the correct firmware file? The minimal firmware I've created for my ESP32 results in a `firmware.bin` file that's about 1.1 MB.
> 
> The watchdog reset makes me think that your connection is hanging/stalling as I mentioned before. Still not sure why that would be happening, though -- I can't seem to reproduce that behavior here.

As far as I can tell, it never actually calls the bin file from the server, since in NPM log I can see the *md5 request, which comes in twice but not the *bin request. The files are the appropriate legacy files. I rename them for validation purposes but its the legacy file from the compile and is exactly around 1.1-1.3 MB (depending if I include ssl library)


Dit some more configuration with the server. Ive removed all quirky configs of the NPM, so now its completely barebones simple, one user, one directory setup. Still get the same issue. when excluding SSL, the OTA works, but I don't see any of the update messages. When I enable it, same crash as before. The webserver is accessible through regular browser and https. 

This is bloody weird.

2024-03-24 13:12 UTC, Alphaemef commented
are there any limit to the URLs to download from i.e max length ? Any specifik formatting it needs to adhere by ? I realise HTTP formatting of special characters, but I've already fixed that issue with the old version of this component.

2024-03-24 18:19 UTC, Alphaemef commented
Right... Spent literally 10 hours testing everything and anything I could think of. Including completely restored my NPM, ACL etc. Changing file path, username / password for basic auth, proxy buffers, reboots enmasse, disabling components etc etc etc. 

Its extremely sporadic. Means once every 12-15 attempts it suddenly works, I immediately assume I found the incompatibility, but it doesn't actually work. 

The closest thing I have right now, is that setting safe mode to yes highly increases the chances of success (50% ish). Everything else is less than 10%. 

Another consistency is that in the MPN logs, the failed attempts almost always only include a get command for the MD5 file, but not the bin file. While all the success include a get command for the bin file (perhaps a bit obvious). My best bet is, the bug is in handling the md5 checksum. Since that is the only really new thing since Oarchers solo version. 

```
[24/Mar/2024:18:57:40 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:18:57:57 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.bin" [Client 192.168.1.1] [Length 1287680] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:18:59:49 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:00:08 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.bin" [Client 192.168.1.1] [Length 1287680] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:01:36 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:01:56 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.bin" [Client 192.168.1.1] [Length 1287680] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:05:32 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:06:16 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:07:10 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:07:30 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.bin" [Client 192.168.1.1] [Length 1287680] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:10:05 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:10:15 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.bin" [Client 192.168.1.1] [Length 32340] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:10:46 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:11:25 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:11:34 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.bin" [Client 192.168.1.1] [Length 32340] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:12:13 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:14:00 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:14:20 +0100] - 200 200 - GET https mqtt.solarbalance.dk "/localpathunitnumb_flashtype.bin" [Client 192.168.1.1] [Length 1287680] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
```

The successes are the lines where the length of the GET for the bin file is 1287680

2024-03-24 18:21 UTC, Alphaemef commented
Right... Spent literally 10 hours testing everything and anything I could think of. Including completely restored my NPM, ACL etc. Changing file path, username / password for basic auth, proxy buffers, reboots enmasse, disabling components etc etc etc. 

Its extremely sporadic. Means once every 12-15 attempts it suddenly works, I immediately assume I found the incompatibility, but it doesn't actually work. 

The closest thing I have right now, is that setting safe mode to yes highly increases the chances of success (50% ish). Everything else is less than 10%. 

Another consistency is that in the MPN logs, the failed attempts almost always only include a get command for the MD5 file, but not the bin file. While all the success include a get command for the bin file (perhaps a bit obvious). My best bet is, the bug is in handling the md5 checksum. Since that is the only really new thing since Oarchers solo version. 

```
[24/Mar/2024:18:57:40 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:18:57:57 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.bin" [Client 192.168.1.1] [Length 1287680] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:18:59:49 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:00:08 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.bin" [Client 192.168.1.1] [Length 1287680] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:01:36 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:01:56 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.bin" [Client 192.168.1.1] [Length 1287680] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:05:32 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:06:16 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:07:10 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:07:30 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.bin" [Client 192.168.1.1] [Length 1287680] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:10:05 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:10:15 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.bin" [Client 192.168.1.1] [Length 32340] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:10:46 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:11:25 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:11:34 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.bin" [Client 192.168.1.1] [Length 32340] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:12:13 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:14:00 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.md5" [Client 192.168.1.1] [Length 32] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
[24/Mar/2024:19:14:20 +0100] - 200 200 - GET https url.com "/local/path/unitnumb_flashtype.bin" [Client 192.168.1.1] [Length 1287680] [Gzip -] [Sent-to 192.168.1.4] "ESP32 HTTP Client/1.0" "-"
```

The successes are the lines where the length of the GET for the bin file is 1287680

2024-03-24 19:39 UTC, oarcher commented
@Alphaemef , If the ota works better with safe mode, it's perhaps because of an out of memory problem. 

I don't know what is the memory overhead induced by the certificate check, but it might be the cause of the problem. I also note that there is 'gzip' in your server logs. I don't know if the esp http client has requested gziped content, but if so, it might consume memory. Can you try to globally disable gzip at the http server level ?

2024-03-24 19:42 UTC, Alphaemef commented
> t

Yes I thought about that, and the units are only the classic ESP32, but still super suprising if that's the case. Not even disabling the SSL library, makes it work as reliably as it did before. 

Yes but its Gzip -, so its not sending gzipped content. Should it matter ?

2024-03-24 19:54 UTC, oarcher commented
@Alphaemef , I don't know if the `Gzip -` matter (it seem that there is no `content-encoding: gzip` header in the idf http client lib, so this *should* not be a problem).

I've just pushed a new commit to reduce `http_recv_buffer_` from 1024 to 512, to see if you have better chances of success with it.

2024-03-24 20:43 UTC, Alphaemef commented
> @Alphaemef , I don't know if the `Gzip -` matter (it seem that there is no `content-encoding: gzip` header in the idf http client lib, so this _should_ not be a problem).
> 
> I've just pushed a new commit to reduce `http_recv_buffer_` from 1024 to 512, to see if you have better chances of success with it.

Doesn't feel like there is much of a difference tbh. If I exclude ssl then it will run most of the times. But not nearly as reliable as before. 

Any thoughts on why it will "get" the md5 url multiple times in some runs ?

2024-03-24 21:37 UTC, oarcher commented
I haven't noticed that on some runs, the md5 file is fetched more than once. Since there is no loop in the ota_http code, it might be due to the retry feature in the http client librairie.

But the cause of the failure is not logged. I've seen above that you use serial logs, but are you using the `VERY_VERBOSE` logger level ? It might give some more infos.

2024-03-24 22:37 UTC, Alphaemef commented
Very verbose basically the same this. 

````
ota_http:
[C][ota_http:043]:   Timeout: 3000000 size=03108h ( 12552) load
I (234) esp_image: segment 2: paddr=0005eab8 vaddr=40080000 size=01560h (  5472) load
I (236) esp_image: segment 3: paddr=00060020 vaddr=40[D][button:010]: 'ESP32 Firmware Update' Pressed.
[D][esp-idf:000]: I (200856) esp-x509-crt-bundle: Certificate validated

[D][esp-idf:000]: I (203484) HTTP_CLIENT: Body received in fetch header state, 0x3ffec55f, 33

[D][esp-idf:000]: I (203708) esp-x509-crt-bundle: Certificate validated

E (205623) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (205623) task_wdt:  - loopTask (CPU 1)
E (205623) task_wdt: Tasks currently running:
E (205623) task_wdt: CPU 0: IDLE
E (205623) task_wdt: CPU 1: loopTask
E (205623) task_wdt: Aborting.

abort() was called at PC 0x40121644 on core 0


Backtrace: 0x40082b42:0x3ffb0950 0x400897e9:0x3ffb0970 0x4008f79e:0x3ffb0990 0x40121644:0x3ffb0a00 0x400834cd:0x3ffb0a20 0x401a385f:0x3ffbb830 0x40121d95:0x3ffbb850 0x4008abc0:0x3ffbb870




ELF file SHA256: 96a6e6d28b2db34c

Rebooting...
````

[
I][ota_http:180]: Previous ota_http unsuccessful. Retrying...
[D][esp-idf:000]: I (6451) wifi:
[D][esp-idf:000]: <ba-add>idx:1 (ifx:0, d8:0d:17:7b:57:96), tid:0, ssn:0, winSize:64
[D][esp-idf:000]: 

[D][esp-idf:000]: I (6673) esp-x509-crt-bundle: Certificate validated

[D][esp-idf:000]: I (8852) HTTP_CLIENT: Body received in fetch header state, 0x3ffcdd03, 33

[D][esp-idf:000]: I (9077) esp-x509-crt-bundle: Certificate validated

[D][esp-idf:000]: I (11266) HTTP_CLIENT: Body received in fetch header state, 0x3ffd6e2c, 84

[D][ota_http:072]: MD5 expected: 3bf00a07b981c105bf6aeb82b85ed0c7
[I][ota_http:114]: Progress: 0.0%
[I][ota_http:114]: Progress: 9.3%
[I][ota_http:114]: Progress: 21.3%
[I][ota_http:114]: Progress: 33.5%
[I][ota_http:114]: Progress: 45.8%
[I][ota_http:114]: Progress: 58.3%
[I][ota_http:114]: Progress: 70.6%
[I][ota_http:114]: Progress: 83.0%
[I][ota_http:114]: Progress: 95.4%
[I][ota_http:114]: Progress: 100.0%
[I][ota_http:121]: Done in 19 seconds
[D][esp-idf:000]: I (25348) esp_image: segment 0: paddr=001d0020 vaddr=3f400020 size=4e9b0h (321968) map

[D][esp-idf:000]: I (25454) esp_image: segment 1: paddr=0021e9d8 vaddr=3ffb0000 size=01640h (  5696) 

[D][esp-idf:000]: I (25458) esp_image: segment 2: paddr=00220020 vaddr=400d0020 size=dc300h (901888) map

[D][esp-idf:000]: I (25752) esp_image: segment 3: paddr=002fc328 vaddr=3ffb1640 size=01ac8h (  6856) 

[D][esp-idf:000]: I (25756) esp_image: segment 4: paddr=002fddf8 vaddr=40080000 size=14d50h ( 85328) 

[D][esp-idf:000]: I (25787) esp_image: segment 0: paddr=001d0020 vaddr=3f400020 size=4e9b0h (321968) map

[D][esp-idf:000]: I (25894) esp_image: segment 1: paddr=0021e9d8 vaddr=3ffb0000 size=01640h (  5696) 

[D][esp-idf:000]: I (25898) esp_image: segment 2: paddr=00220020 vaddr=400d0020 size=dc300h (901888) map

[D][esp-idf:000]: I (26190) esp_image: segment 3: paddr=002fc328 vaddr=3ffb1640 size=01ac8h (  6856) 

[D][esp-idf:000]: I (26195) esp_image: segment 4: paddr=002fddf8 vaddr=40080000 size=14d50h ( 85328) 

[I][ota_http:151]: OTA update completed](`[url](url)`)

2024-03-25 18:20 UTC, oarcher commented
@Alphaemef , I've setup an NPM config, and was able to reproduce your problem!

It seems that the latency probably induced by the proxy make the watchdog to be triggered. Using `App.feed_wdt()` is not enough, because the timeout occurs in the underlying http library. So I've had to use `esp_task_wdt_init(20, true)`.

Can you test ?

2024-03-25 19:17 UTC, kbx81 commented
Sweet, nice work @oarcher! Interesting that this happens with NPM but with my HAProxy instance. 😄

2024-03-25 20:23 UTC, Alphaemef commented
> @Alphaemef , I've setup an NPM config, and was able to reproduce your problem!
> 
> It seems that the latency probably induced by the proxy make the watchdog to be triggered. Using `App.feed_wdt()` is not enough, because the timeout occurs in the underlying http library. So I've had to use `esp_task_wdt_init(20, true)`.
> 
> Can you test ?

You Sly SOB!!!!!! It works!!!!! Huzzaahh!! 5 flashes in a row with no errors, a log that looks perfect. How I wish I was just 5 steps higher up on the ladder so I could contribute more than just banging my head against a wall for an entire day, but awesome of you to reproduce!! Thanks man. 

Im off to re-buidling the couple of hundred of individual users in my NPM setup, now might be a good time to learn to do it via terminal :P

2024-03-25 21:38 UTC, oarcher commented
The timeout issue on slow http server also occurs on other platforms, so I had to explicitly increase the timeout for each platform, since there isn't a uniform way to do this.

2024-03-26 08:36 UTC, tomatensaus commented
The documentation is not very clear about what needs to be in the MD5 file, there is no "md5" command in Linux. 
I do not own a MAC to check the output of the md5 command.

There is "md5sum filename" and also "openssl md5 filename"  which produces different text output.
See below the output of the commands:

```
openssl md5 filename.bin 
MD5(filename.bin)= d7aa69d7999fbc329660d6818487bdaa

md5sum filename.bin 
d7aa69d7999fbc329660d6818487bdaa  filename.bin
```

Are both of these acceptable inputs for the MD5 file? Should I use awk to strip out the MD5 only to a file ? 

Any chance someone would add an option to pass in the the MD5 itself and skip the url?

2024-03-26 19:34 UTC, oarcher commented
Changing the watchdog timeout can be done for esp32 at the yaml level (see https://github.com/esphome/esphome/pull/3256#issuecomment-2020644517):

```yaml
esp32:
  framework:
    sdkconfig_options:
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "15"
 ```
 
 But I haven't found an equivalent option for esp8266 and rp2040. It probably can be done with some lambda at `on_boot`, but this will be complicated for the end user.

So I think that the current code that increase the WDT can be kept. Do you agree with this, @kbx81 ?

2024-03-26 21:05 UTC, oarcher commented
@tomatensaus , only the first 32 bytes of the md5 file are used, so only files beginning with the HEX digits are valids. Trailing characters are ignored.

It's a very common way to validate file integrity, but I've added a windows section and modified the doc as follow:

---
the [MD5sum](https://en.wikipedia.org/wiki/Md5sum) of the firmware file is an ascii file of 32 lowercase hexadecimal characters. it can be obtained and saved to a file with the following command:

On macOS and most Linux distributions:

`md5 -q firmware.bin > firmware.md5`

On Windows/powershell:

`(Get-FileHash -Path firmware.bin -Algorithm md5).Hash.ToLower() | Out-File -FilePath firmware.md5 -Encoding ASCII`

---

I'm not familiar with windows,  I don't know if there is a better command!


> Any chance someone would add an option to pass in the the MD5 itself and skip the url? When storing your firmware in a database this makes a lot of sense

Can you explain your use case with a yaml example ? I don't think we will do that, because the md5sum is here to validate that no errors occurs during download.

2024-03-27 02:56 UTC, kbx81 commented
> So I think that the current code that increase the WDT can be kept. Do you agree with this, @kbx81 ?

@oarcher we should probably expose it as a (optional) configuration variable and allow the user to define it...could be useful for other high-latency or otherwise slow connections that result in even longer delays. I'm not too keen on hardcoding a value like that. Related: We should make sure the watchdog is restored to its default value should the OTA fail. 😇

2024-03-27 03:18 UTC, kbx81 commented
> > Any chance someone would add an option to pass in the the MD5 itself and skip the url? When storing your firmware in a database this makes a lot of sense
> 
> Can you explain your use case with a yaml example ? I don't think we will do that, because the md5sum is here to validate that no errors occurs during download.

I think I understand what @tomatensaus is asking for, but I guess I don't understand why this is necessary -- if you're storing your firmware in a database, you already have to pull it from your database to provide it to your ESPs as a downloadable file. Repeating this operation for the MD5 value should be trivial. What is the benefit in this case of passing the MD5 in another way?

2024-03-27 05:25 UTC, tomatensaus commented
> On macOS and most Linux distributions:
```
md5 -q firmware.bin
bash: md5: command not found
```
There is no such command on linux. It is mac specific
The command on linux does not understand the -q option
```
md5sum -q firmware.bin
md5sum: invalid option -- 'q'
```

2024-03-27 05:49 UTC, kbx81 commented
> > On macOS and most Linux distributions:
> 
> ```
> md5 -q firmware.bin
> bash: md5: command not found
> ```
> 
> There is no such command on linux. It is mac specific The command on linux does not understand the -q option
> 
> ```
> md5sum -q firmware.bin
> md5sum: invalid option -- 'q'
> ```

Yes, thanks @tomatensaus, the documentation was corrected a couple of hours ago. 😄

2024-03-27 06:19 UTC, tomatensaus commented
> What is the benefit in this case of passing the MD5 in another way?

The only real benefit would be one less connection and needing to build a endpoint that returns the MD5

I am under the impression that TCP guarantees the content of the download to be correct. 
The md5sum just ensures that every byte was used by the ota logic compared the the file on disk

2024-03-27 06:21 UTC, tomatensaus commented
Current WDT still getting triggered on high latency across continents
```
[I][wifi:587]: WiFi Connected!
[I][app:062]: setup() finished successfully!
[I][ota_http:180]: Previous ota_http unsuccessful. Retrying...
[I][ota_http:114]: Progress: 0.0%
[I][ota_http:114]: Progress: 1.3%
[I][ota_http:114]: Progress: 2.5%
[I][ota_http:114]: Progress: 4.4%
[I][ota_http:114]: Progress: 5.7%
[I][ota_http:114]: Progress: 6.9%
[I][ota_http:114]: Progress: 8.2%
[I][ota_http:114]: Progress: 9.4%
[I][ota_http:114]: Progress: 10.7%
[I][ota_http:114]: Progress: 12.0%
[I][ota_http:114]: Progress: 13.2%
[I][ota_http:114]: Progress: 14.5%
[I][ota_http:114]: Progress: 15.8%
[I][ota_http:114]: Progress: 17.0%
[I][ota_http:114]: Progress: 18.9%
E (65150) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (65150) task_wdt:  - loopTask (CPU 1)
E (65150) task_wdt: Tasks currently running:
E (65150) task_wdt: CPU 0: IDLE
E (65150) task_wdt: CPU 1: IDLE
E (65150) task_wdt: Aborting.

abort() was called at PC 0x40103a98 on core 0

Backtrace:0x40083915:0x3ffbe9dc |<-CORRUPTED

ELF file SHA256: 0000000000000000
Rebooting...
```

2024-03-27 06:42 UTC, kbx81 commented
> > What is the benefit in this case of passing the MD5 in another way?
> 
> The only real benefit would be one less connection and needing to build a endpoint that returns the MD5
> 
> I am under the impression that TCP guarantees the content of the download to be correct. The md5sum just ensures that every byte was used by the ota logic compared the the file on disk

Yes, TCP ensures that the data received is as expected. However, there are many other things that can go wrong--things that aren't related to network conditions/reliability--before the file reaches the ESP. The MD5 isn't there just to ensure the network transmission was as expected. What if some data is corrupted on disk, before it's sent to the ESP? What if the copy of the file on the web server is incomplete? What happens if there is some memory corruption on the ESP? The MD5 helps to address all of these situations. It's a very necessary component to ensure the integrity of the firmware image.

2024-03-27 19:10 UTC, oarcher commented
> Current WDT still getting triggered on high latency across continents

@tomatensaus , your connection is really slow!
The watchdog was fed when the progress message was displayed. I've just pushed a new commit that feed it more often.

2024-03-28 05:43 UTC, tomatensaus commented
> @tomatensaus , your connection is really slow!
> The watchdog was fed when the progress message was displayed. I've just pushed a new commit that feed it more often.

Yes it is slow, agreed. I hosted the flashing server on DigitalOcean (on the same continent) which did not solve it. Changing ISPs at the remote site solved it (so presumably something was badly configured with the ISP). Perhaps this comment will help someone in the future.

2024-03-28 10:19 UTC, oarcher commented
> > So I think that the current code that increase the WDT can be kept. Do you agree with this, @kbx81 ?
> 
> @oarcher we should probably expose it as a (optional) configuration variable and allow the user to define it...could be useful for other high-latency or otherwise slow connections that result in even longer delays. I'm not too keen on hardcoding a value like that. Related: We should make sure the watchdog is restored to its default value should the OTA fail. 😇

@kbx81 , I've added in the yaml an option to temporary change the wdt:
```yaml
ota_http:
  watchdog_timeout: 20s
```

It's only valid for `esp32` and `rp2040`, because changing the wdt on `esp8266` with `EspClass::wdtEnable(timeout_ms)` is [not implemented](https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Esp.h#L89-L92).

The only arch that fully support reading of the actual wdt value is `rp2040` with [watchdog_get_count()](https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_watchdog/include/hardware/watchdog.h#L108-L114)

There is no such function for `esp32`, so I've used `CONFIG_ESP_TASK_WDT_TIMEOUT_S` to get the default.

The watchdog files might be turned in a separate component in the future (it may need some improvements)

2024-03-28 14:28 UTC, oarcher commented
@kbx81 , I've just checked that on esp32, we can force use of idf, even with arduino framework. So, we can have certificate validation when using the default arduino framework.

Unfortunately, there are conflict if some other arduino components use arduino http, like `ESPAsyncWebServer-esphome` in `web_server`

<details>
<summary>logs</summary>

```
In file included from src/esphome/components/web_server_base/web_server_base.h:10,
                 from src/esphome/components/web_server/web_server.h:5,
                 from src/esphome.h:44,
                 from src/main.cpp:3:
.piolibdeps/mini-v02/ESPAsyncWebServer-esphome/src/ESPAsyncWebServer.h:62:18: error: 'HTTP_GET' conflicts with a previous declaration
   HTTP_GET     = 0b00000001,
                  ^~~~~~~~~~
In file included from /home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_http_client/include/esp_http_client.h:11,
                 from src/esphome/components/ota_http/ota_http_idf.h:7,
                 from src/esphome.h:35,
                 from src/main.cpp:3:
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:138:31: note: previous declaration 'http_method HTTP_GET'
 #define XX(num, name, string) HTTP_##name = num,
                               ^~~~~
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:96:3: note: in expansion of macro 'XX'
   XX(1,  GET,         GET)          \
   ^~
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:139:3: note: in expansion of macro 'HTTP_METHOD_MAP'
   HTTP_METHOD_MAP(XX)
   ^~~~~~~~~~~~~~~
In file included from src/esphome/components/web_server_base/web_server_base.h:10,
                 from src/esphome/components/web_server/web_server.h:5,
                 from src/esphome.h:44,
                 from src/main.cpp:3:
.piolibdeps/mini-v02/ESPAsyncWebServer-esphome/src/ESPAsyncWebServer.h:63:18: error: 'HTTP_POST' conflicts with a previous declaration
   HTTP_POST    = 0b00000010,
                  ^~~~~~~~~~
In file included from /home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_http_client/include/esp_http_client.h:11,
                 from src/esphome/components/ota_http/ota_http_idf.h:7,
                 from src/esphome.h:35,
                 from src/main.cpp:3:
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:138:31: note: previous declaration 'http_method HTTP_POST'
 #define XX(num, name, string) HTTP_##name = num,
                               ^~~~~
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:98:3: note: in expansion of macro 'XX'
   XX(3,  POST,        POST)         \
   ^~
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:139:3: note: in expansion of macro 'HTTP_METHOD_MAP'
   HTTP_METHOD_MAP(XX)
   ^~~~~~~~~~~~~~~
In file included from src/esphome/components/web_server_base/web_server_base.h:10,
                 from src/esphome/components/web_server/web_server.h:5,
                 from src/esphome.h:44,
                 from src/main.cpp:3:
.piolibdeps/mini-v02/ESPAsyncWebServer-esphome/src/ESPAsyncWebServer.h:64:18: error: 'HTTP_DELETE' conflicts with a previous declaration
   HTTP_DELETE  = 0b00000100,
                  ^~~~~~~~~~
In file included from /home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_http_client/include/esp_http_client.h:11,
                 from src/esphome/components/ota_http/ota_http_idf.h:7,
                 from src/esphome.h:35,
                 from src/main.cpp:3:
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:138:31: note: previous declaration 'http_method HTTP_DELETE'
 #define XX(num, name, string) HTTP_##name = num,
                               ^~~~~
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:95:3: note: in expansion of macro 'XX'
   XX(0,  DELETE,      DELETE)       \
   ^~
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:139:3: note: in expansion of macro 'HTTP_METHOD_MAP'
   HTTP_METHOD_MAP(XX)
   ^~~~~~~~~~~~~~~
In file included from src/esphome/components/web_server_base/web_server_base.h:10,
                 from src/esphome/components/web_server/web_server.h:5,
                 from src/esphome.h:44,
                 from src/main.cpp:3:
.piolibdeps/mini-v02/ESPAsyncWebServer-esphome/src/ESPAsyncWebServer.h:65:18: error: 'HTTP_PUT' conflicts with a previous declaration
   HTTP_PUT     = 0b00001000,
                  ^~~~~~~~~~
In file included from /home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_http_client/include/esp_http_client.h:11,
                 from src/esphome/components/ota_http/ota_http_idf.h:7,
                 from src/esphome.h:35,
                 from src/main.cpp:3:
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:138:31: note: previous declaration 'http_method HTTP_PUT'
 #define XX(num, name, string) HTTP_##name = num,
                               ^~~~~
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:99:3: note: in expansion of macro 'XX'
   XX(4,  PUT,         PUT)          \
   ^~
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:139:3: note: in expansion of macro 'HTTP_METHOD_MAP'
   HTTP_METHOD_MAP(XX)
   ^~~~~~~~~~~~~~~
In file included from src/esphome/components/web_server_base/web_server_base.h:10,
                 from src/esphome/components/web_server/web_server.h:5,
                 from src/esphome.h:44,
                 from src/main.cpp:3:
.piolibdeps/mini-v02/ESPAsyncWebServer-esphome/src/ESPAsyncWebServer.h:66:18: error: 'HTTP_PATCH' conflicts with a previous declaration
   HTTP_PATCH   = 0b00010000,
                  ^~~~~~~~~~
In file included from /home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/esp_http_client/include/esp_http_client.h:11,
                 from src/esphome/components/ota_http/ota_http_idf.h:7,
                 from src/esphome.h:35,
                 from src/main.cpp:3:
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:138:31: note: previous declaration 'http_method HTTP_PATCH'
 #define XX(num, name, string) HTTP_##name = num,
                               ^~~~~
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:128:3: note: in expansion of macro 'XX'
   XX(28, PATCH,       PATCH)        \
   ^~
/home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/include/nghttp/port/include/http_parser.h:139:3: note: in expansion of macro 'HTTP_METHOD_MAP'
   HTTP_METHOD_MAP(XX)
   ^~~~~~~~~~~~~~~
In file included from src/esphome/components/web_server_base/web_server_base.h:10,
                 from src/esphome/components/web_server/web_server.h:5,
                 from src/esphome.h:44,
                 from src/main.cpp:3:
.piolibdeps/mini-v02/ESPAsyncWebServer-esphome/src/ESPAsyncWebServer.h:67:18: error: 'HTTP_HEAD' conflicts with a previous declaration
   HTTP_HEAD    = 0b00100000,
                  ^~~~~~~~~~
In file included from /home/oarcher/.platformio/packages/framework-arduinoespressif32/tools/sdk/es [...]

2024-03-29 00:31 UTC, oarcher commented
The max url size is currently 250, and the memory (and flash) footprint is *2, (md5_url + url).

250 is quite big, because some user have quite long url (encoded params, user/password, etc..). 

But if memory is an issue, an `max_url_lenght` option can be added, with a default of 128 ?

2024-03-29 00:33 UTC, Alphaemef commented
> The max url size is currently 250, and the memory (and flash) footprint is *2, (md5_url + url).
> 
> 250 is quite big, because some user have quite long url (encoded params, user/password, etc..).
> 
> But if memory is an issue, an `max_url_lenght` option can be added, with a default of 128 ?

Be advised, those characters are quickly used up with basic auth and specific paths on a server. Im running at just abou 100 characters with a "rather" straight forward setup.

2024-03-29 00:52 UTC, oarcher commented
> Be advised, those characters are quickly used up with basic auth and specific paths on a server. Im running at just abou 100 characters with a "rather" straight forward setup.

Ok, I've added `max_url_lenght`, but kept 250 as default.

Those with memory issue will have to reduce it.

2024-03-29 04:49 UTC, kbx81 commented on esphome/components/ota_http/__init__.py
> +CONF_MAX_URL_LENGHT = "max_url_lenght"
Spelling 😇

```suggestion
CONF_MAX_URL_LENGTH = "max_url_length"
```

2024-03-29 11:38 UTC, oarcher commented
I was thinking about another feature: Skip flash if the remote firmware is the same as the installed one.

So the device can regularly check for updates with [interval component](https://esphome.io/guides/automations.html#interval-component), without changing the url (just update the remote files)

This can be done by saving the last successful md5sum to flash, and comparing it to the next one.

2024-03-29 21:08 UTC, paulsteigel commented
> I was thinking about another feature: Skip flash if the remote firmware is the same as the installed one.
> 
> So the device can regularly check for updates with [interval component](https://esphome.io/guides/automations.html#interval-component), without changing the url (just update the remote files)
> 
> This can be done by saving the last successful md5sum to flash, and comparing it to the next one.

@oarcher ,
Hi, thanks for your great contribution, have you ever thought of something like this:
+ Binding the Install command of the Esphome yaml to this function so that
++ If API/OTA enable, the firmware will be flashed directly over OTA (internally) as usual;
++ If API is unreachable, OTA as well (the device is not in the same network as the HA server) but MQTT is available. Install command will build the firmware first and then encode over MQTT topic and then device discover the new firmware available over a new firmware topic in MQTT and start download over MQTT and flash automatically?
With this function, all will be automated with easy. I knew this is harder job for you but it bears the same idea as you are doing then.
Currently, to do this update things, I have to do the port forwarding at device locations. 
Many thanks for your attention.

2024-03-30 00:13 UTC, oarcher commented
> I was thinking about another feature: Skip flash if the remote firmware is the same as the installed one.

I've added `force_update` option (false by default), so the following yaml will periodically check update on the server, and install it if the md5 has changed:

```yaml
esphome:
  name: mydevice

ota_http:

interval:
  - interval: 1d
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - ota_http.flash:
                url: !lambda return ("http://example.com/firmware-" + App.get_name() + ".bin").c_str();
                md5_url: !lambda return ("http://exemple.com/firmware-" + App.get_name() + ".md5").c_str();
            - logger.log: "http ota not performed (error or skipped)"
```

Remote files are named using the device name (`firmware-mydevice.bin` and  `firmware-mydevice.md5` )

2024-03-30 00:24 UTC, oarcher commented
@paulsteigel , the goal for this PR is to provide base features for ota over http, and it currently needs that the user set up a web server and do some work (md5sum, copy/rename files, etc...).

Perhaps that a better integration with HA will be done one day, but it will be another PR.

2024-03-30 03:23 UTC, paulsteigel commented
> @paulsteigel , the goal for this PR is to provide base features for ota over http, and it currently needs that the user set up a web server and do some work (md5sum, copy/rename files, etc...).
> 
> Perhaps that a better integration with HA will be done one day, but it will be another PR.

Thanks @oarcher for your response! I understood the case and only wanted to share as the potential view for future.
What about another option to ease the process by adding a new option in the install command so when it built the new firmware and md5 hash that new command will copy to a HA web server location. Currently I can do that by getting inside the esphome docker container and copy a file to the www folder under /config (this synced with docker). Then Esphome will use your ota_http to check/download and auto install the newfirwmare.
Just a thought as I am now using the http component with www under config to server the firmware and use the shell manually to generate md5 and also copy firmware to the www under config!
Best!
Ngoc

2024-04-01 07:55 UTC, kbx81 commented
Quick update:

I spoke with Jesse and we decided it makes the most sense to build out platform components for the purpose of OTA updates. I'm doing some work to implement this now and will open a related PR this week.

What we're looking to accomplish is better organization as we accommodate what's being implemented in this PR and (later)  implement (in some form) what's being discussed above. What will it look like? Something like this:

```yaml
ota:
  - platform: ota_push_http
    # ...config of existing OTA component
  - platform: ota_pull_http
    # config of this component
  - platform: ota_push_mqtt
    # future component, perhaps implementing some of what's discussed above
  - platform: ota_push_ble
    # maybe in the future...OTA via BLE?!?!?
```
...hopefully you get the idea. 😇

2024-04-01 08:14 UTC, paulsteigel commented
> Quick update:
> 
> I spoke with Jesse and we decided it makes the most sense to build out platform components for the purpose of OTA updates. I'm doing some work to implement this now and will open a related PR this week.
> 
> What we're looking to accomplish is better organization as we accommodate what's being implemented in this PR and (later) implement (in some form) what's being discussed above. What will it look like? Something like this:
> 
> ```yaml
> ota:
>   - platform: ota_push_http
>     # ...config of existing OTA component
>   - platform: ota_pull_http
>     # config of this component
>   - platform: ota_push_mqtt
>     # future component, perhaps implementing some of what's discussed above
>   - platform: ota_push_ble
>     # maybe in the future...OTA via BLE?!?!?
> ```
> 
> ...hopefully you get the idea. 😇

Hi @kbx81,
It is great to hear your option! We are all awaiting for this wonderful news and hopefully people like me will find easy time to have firmware update as straightforward as making a click. Of course, to have this, out there you are working hard to help simple people like us! 
We do appreciate your efforts in reviewing the component and making the component from scratch (@oarcher).
All the best!
Ngoc

2024-04-01 23:55 UTC, kbx81 commented
I've [started a thread on our discord server](https://discord.com/channels/429907082951524364/1224504508374061167) for some discussion about my comment above. I encourage anybody watching and/or commenting here to join. 😄

2024-04-03 18:51 UTC, BugsBunny1403 commented
I m very interested by your work in ota by addon esphome and webserver for device connected by mqtt in other network.

2024-04-05 23:27 UTC, Alphaemef commented
Hey @oarcher did you change the logging of the component ? I just noticed that in "debug" log level it shows the fetch URL, however Im using basic auth, so full username and passwords is shared over the MQTT topic. Which I would prefer to avoid without disabling logging. Anything that can be done about that :) ?

Basically I want to the able to track the OTA progess but just not show the URL. Would log level info do the trick ? Or perhaps place the URL in verbose instead of info / debug ?

2024-04-06 11:12 UTC, oarcher commented
@Alphaemef , yes, I've changed that. The url is also displayed at error level on bad http status.

Is it enough for security if I replace  `http://user:password@exemple.com/` by `http://*****:*****@exemple.com/` ?

2024-04-06 11:27 UTC, Alphaemef commented
Yes that would be fine!

2024-04-07 08:48 UTC, oarcher commented
> Yes that would be fine!

@Alphaemef , credential are now hidden in debug level. But underlying librairies show them when in verbode level.

Using regex to do it makes 8666 unstable, so I've coded it with old school C.

May be related, but the latest esphome release brake http (not https) on 8266: 
[`this->stream_ptr_->available()`](https://github.com/esphome/esphome/pull/5586/files#diff-e03fb983c5cea7a78bed0fe39edd6ff952682883318b7ab5143094364a63bd5dR67) is always `0`, so the stream is not read.

However, it seems to work well with the esphome stable release (cc: @kbx81 )

2024-04-07 21:32 UTC, oarcher commented
> May be related, but the latest esphome dev release (not sure from when) brake http (not https) on 8266: [`this->stream_ptr_->available()`](https://github.com/esphome/esphome/pull/5586/files#diff-e03fb983c5cea7a78bed0fe39edd6ff952682883318b7ab5143094364a63bd5dR67) is always `0`, so the stream is not read.
> 
> However, it seems to work well with the esphome stable release 


So I've tried to investigate further this bug.

In this PR, the bug was introduced by 1cc6aa0a6852def0f30c3afe87681ff63623afcc (`Add MD5 validation`  @kbx81 )

The problem occurs here:
https://github.com/esphome/esphome/blob/1cc6aa0a6852def0f30c3afe87681ff63623afcc/esphome/components/ota_http/ota_http_arduino.cpp#L93

The stream is not fed, and `this->stream_ptr_->available()` is always `0`.


I've try to use `ota_http` as an external component using **esphome release and beta branch**, and **it works** !!


I've also tried as an external component  using **official esphome dev branch**:  and it **fail** .


I will try to `git bisect`  on the official dev branch ...

2024-04-07 22:29 UTC, oarcher commented
So after some bisect, I've found that 7d9fc3ceaab4db660a8aeddb55499d640b549cbe is the first bad commit ( cc: @HeMan).

2024-04-08 16:10 UTC, oarcher commented
oops, bad branch manipulation...

2024-04-08 16:28 UTC, oarcher commented
> So after some bisect, I've found that [7d9fc3c](https://github.com/esphome/esphome/commit/7d9fc3ceaab4db660a8aeddb55499d640b549cbe) is the first bad commit

The commit just bump the arduino version to 3.1, and the problem is the same as https://github.com/esp8266/Arduino/issues/9035.

fixed by 6d999de2033457f9ba7503d14c805e49864935ae

2024-05-08 10:24 UTC, kbx81 commented
Alrighty, I spent some time today refactoring this into an `ota` platform, similar to what was done in #6459 for the native ESPHome OTA component-now-platform. Of course, for the moment, it's broken here, but when combined with the changes in #6459, it'll build and run as expected. We're planning to merge these PRs shortly after this upcoming (May) release to allow them a good amount of time in ~~the oven~~ `dev` before the next (June) release.

Some changes of note:
- I've sprinkled in triggers consistent with what we have in the native ESPHome OTA component-now-platform
- `force_update` can now be specified by the `ota_http_request.flash` action and it's temptable (as opposed to a `const` determined at compile time)
- I've modified it to take full advantage of the refactoring done in #6459 (some inheritance/methods/functions/etc.)
- I've tidied up and/or streamlined a number of log messages as well as a little run-time logic

So far I've only been testing on an ESP32 I have here, but I don't think these changes will impact any of the other hardware platforms. Still, I/we should do some testing to verify this in the very near future. 😉

2024-05-08 19:23 UTC, Alphaemef commented
> Alrighty, I spent some time today refactoring this into an `ota` platform, similar to what was done in #6459 for the native ESPHome OTA component-now-platform. Of course, for the moment, it's broken here, but when combined with the changes in #6459, it'll build and run as expected. We're planning to merge these PRs shortly after this upcoming (May) release to allow them a good amount of time in ~the oven~ `dev` before the next (June) release.
> 
> Some changes of note:
> 
> * I've sprinkled in triggers consistent with what we have in the native ESPHome OTA component-now-platform
> * `force_update` can now be specified by the `ota_http_request.flash` action and it's temptable (as opposed to a `const` determined at compile time)
> * I've modified it to take full advantage of the refactoring done in [Separate `OTABackend` from OTA component #6459](https://github.com/esphome/esphome/pull/6459) (some inheritance/methods/functions/etc.)
> * I've tidied up and/or streamlined a number of log messages as well as a little run-time logic
> 
> So far I've only been testing on an ESP32 I have here, but I don't think these changes will impact any of the other hardware platforms. Still, I/we should do some testing to verify this in the very near future. 😉

Uff, lot of work there Keith. Well done. Any way I can test ? Or would that require inclusion of the several number of PRs ?

Im kinda using the function on live units, and right now my yaml code will (obviously) not compile due to linking to this PR with the old schema.

2024-05-08 21:39 UTC, kbx81 commented
@Alphaemef I'll get you a solution shortly...just need to check on/test a few things. 😉

2024-05-08 23:33 UTC, oarcher commented
Yes, major changes are coming!

It will not be possible to use `ota_http` as an external component until PR is merged.

For the legacy one, you can still use:

```yam
external_components:
    - source: github://oarcher/esphome@ota_http_legacy
      components: [ ota_http ]
```

2024-05-09 00:28 UTC, kbx81 commented
@Alphaemef @oarcher I've merged the branch I'm using in #6459 into this branch so you can test it more easily.

@Alphaemef I'm not sure what your setup looks like, but if you are running the `dev` version of the ESPHome Dashboard, you can specify in its configuration an `esphome_fork` option and point it at @oarcher's fork here. 
If you're using the ESPHome command line to build & test, you can `gh pr checkout 5586` to pull a copy of the code in this PR...then (more or less) `python3 -m esphome run your_config.yaml` to build & run your config on your hardware of choice.

2024-05-09 00:41 UTC, kbx81 commented
BTW, here is what my config looks like now:

```yaml
ota:
  - platform: esphome
    # safe_mode: false
    on_state_change:
      - logger.log: esphome.on_state_change
  - platform: http_request
    # exclude_certificate_bundle: true
    on_state_change:
      - logger.log: http_request.on_state_change
    on_abort:
      - logger.log: http_request.on_abort
# ...
switch:
  - platform: template
    id: force_update
    name: Force Update
    optimistic: true

button:
  - platform: safe_mode
    name: Restart in Safe Mode button
  - platform: template
    name: Firmware update
    on_press:
      then:
        - ota_http_request.flash:
            md5_url: https://.../firmware.md5
            url: https://.../firmware.bin
            force_update: !lambda "return id(force_update).state;"
        - logger.log: "This message should be not displayed (reboot)"
```

2024-05-09 07:54 UTC, Alphaemef commented
> Yes, major changes are coming!
> 
> It will not be possible to use `ota_http` as an external component until PR is merged.
> 
> For the legacy one, you can still use:
> 
> ```
> external_components:
>     - source: github://oarcher/esphome@ota_http_legacy
>       components: [ ota_http ]
> ```

When you say legacy, you mean the version that was in this PR until Keith went haywire :P ? 

If so, I would then use that in production (its been soo reliable). And I can test this new branch on units I actually have physical access without changing  the external component link(i.e pr5586), but change the layout to the new ota: platform.

2024-05-09 09:19 UTC, kbx81 commented
> > Yes, major changes are coming!
> > It will not be possible to use `ota_http` as an external component until PR is merged.
> > For the legacy one, you can still use:
> > ```
> > external_components:
> >     - source: github://oarcher/esphome@ota_http_legacy
> >       components: [ ota_http ]
> > ```
> 
> When you say legacy, you mean the version that was in this PR until Keith went haywire :P ?

😜  Yes I believe so.

> If so, I would then use that in production (its been soo reliable). And I can test this new branch on units I actually have physical access without changing the external component link(i.e pr5586), but change the layout to the new ota: platform.

Don't test stuff on devices that you don't have physical access to! 😜 That's just asking for trouble. Running `dev` at all on devices you don't have access to is scary enough. 😅

If you really need to update a device that was already using this PR before the changes I made over the last day or two, then yes, just update the `external_components` block of your config as @oarcher suggested above -- but I would still highly recommend testing this on a device you have physical access to before deploying into things you don't have physical access to...just to be sure. 😉 Good luck! Keep me/us posted if you test the new changes **on a device you have physical access to.** 😉😅🍻

2024-05-09 10:19 UTC, Alphaemef commented
> Don't test stuff on devices that you don't have physical access to! 😜 That's just asking for trouble. Running `dev` at all on devices you don't have access to is scary enough. 😅
>

Ha, yes of course, I do multiple tests at the local site, before it goes into production. And been following your changes quite closely. 

I will continue with due diligence, and get back to you on my finding during the weekend. Only have ESP32s to test with though, but of course different network environment etc.

2024-05-09 10:53 UTC, oarcher commented
@Alphaemef is a great alpha tester!

One of the issue I've got was with `safe_mode` and nvs flash. If the device is unable to perform OTA because of a problem (memory, etc...), the url is saved to flash, so it will be accessible at boot time to retry the OTA.

Sometime, the device is unable to write the url to flash because the flash is full. So you are not able to perform the OTA, unless you are able to reset the nvs flash data.

If the device is far away, I recommend to add a way to reset the global preferences. Be warned that this will erase **all** preferences! So If the wifi credentials where set up by the `captive_portal`, You will loose the wifi...

```
button:
  - platform: template
    name: reset flash
    on_press: 
      then:
        - lambda: |-
            ESP_LOGI("xxx", "reseting prefs to factory defaults");
            global_preferences->reset();
            App.reboot();
```

2024-05-09 22:12 UTC, kbx81 commented
> @Alphaemef is a great alpha tester!

💯🍻😄

> One of the issue I've got was with `safe_mode` and nvs flash. If the device is unable to perform OTA because of a problem (memory, etc...), the url is saved to flash, so it will be accessible at boot time to retry the OTA.
> 
> Sometime, the device is unable to write the url to flash because the flash is full. So you are not able to perform the OTA, unless you are able to reset the nvs flash data.

All the more reason to use an ESP32 or variant -- _lots_ more space for NVS. 😉 haha

2024-05-12 14:34 UTC, Alphaemef commented
Alright, trying to test. But trouble even getting started. 

I usually use terminal / CLI to compile. But the gh checkout isn't working:
`alphaemef@alphaemef ~ % gh pr checkout 5586 
failed to run git: fatal: not a git repository (or any of the parent directories): .git`

And various permutations of

```
external_components:
  - source: github://pr#5586
    components: [ ota, http_request, esphome/ota, http_request/ota]
```

 external components won't work (even if I try to add the new updated components i.e [ ota, http_request, esphome/ota, http_request/ota] in various combinations. I get a "unable to find function ots_esphome

2024-05-12 15:14 UTC, oarcher commented
@Alphaemef , this is because https://github.com/esphome/esphome/pull/6459 is not yet merged into dev

But the new `ota` component  can't be used as an external component (just  tiny changes in `esphome/__main__.py`, and I don't know if there is a workaround...)

So if you are currently using the dev branch of esphome with git, you  will have to first checkout the new ota branch:

```
cd esphome
git fetch upstream pull/6459/head:new-ota  # try origin if upstream is not ok
git checkout new-ota
pip install -e .
```

At this point, using 
```
ota:
  - platform: esphome
```

should work.
You can then add `http_request.ota` as an external component:

```yaml
external_components:
  - source: github://pr#3256
    components: [ http_request ]
    
ota:
  - platform: http_request
```

2024-05-16 02:39 UTC, kbx81 commented
#6459 has been merged, so I've updated this branch so it's consistent. 😄

2024-05-16 10:25 UTC, kbx81 commented
After some discussion with Jesse, we're working to further reduce duplicated code by uncoupling safe mode from OTA. See #6759

2024-05-16 14:08 UTC, Alphaemef commented
Let's see how deep this rabbit hole really goes :)

2024-05-16 22:11 UTC, oarcher commented
Great job, @kbx81 ! I didn't expect this PR to lead to so much refactoring in the OTA code!

I've tested on a bunch of different platforms, but with so many options, it's tough to cover every possible combination.

I've just pushed some tiny changes.

2024-05-16 22:31 UTC, kbx81 commented
Thanks! 🍻 The original OTA code needed some clean-up regardless and I think this just pushed us over the edge. 😄

I talked a good bit about it with Jesse yesterday and we agreed on some more streamlining for this PR. I'll do some more refactoring based on that today/this weekend, so...expect to see a few more changes? 😅 We'd still like to get this into the next release. 😉

2024-05-20 03:31 UTC, kbx81 commented
Ok, lots of changes here -- I'll do my best to summarize/highlight what I've done:

- `safe_mode` has been removed because:
  - New `safe_mode` component eliminates the need for the redundant code
  - Multiple boot failure handling already done by new component
  - If flashing at boot is desired, it can easily be accomplished by using `ota_http_request.flash` inside of the wifi component's `on_connect ` trigger
  - This change also eliminates the need for state tracking across reboots as well as the need for "MAX_URL_LENGTH" (because it's not stored in preferences anymore).
- All watchdog timer adjusting is handled inside of the various HTTP methods in an effort to ensure the timer is reset immediately after HTTP functions are done. (There were some cases where it wouldn't get reset before returning, which is bad.) _Hopefully_ this doesn't create any new issues--I don't think it will--but we should test as much as possible to confirm.
- `username` and `password` configuration variables are now present, allowing use of YAML secrets for these values (as opposed to before where they had to be placed directly into the URL). This also eliminates the need for a bunch of extra parsing code to mask these values in logs.
- The MD5sum can be specified directly in the action in addition to the already-implemented mechanism to fetch it from a URL.
- A few other optimizations which (I think) should reduce the component's memory footprint while it's idle.

I realize this removes some of the original functionality, but any of this can already be accomplished with ESPHome's built-in automations. We want to minimize the component's footprint and streamline the code/PR size -- I think these changes help accomplish that. 😄

While testing, I've noticed that a crash seems to occur on the '8266 at around 96% -- I think this may be related to changes in #5359 as I haven't tested on the '8266 since it was merged; downgrading to v3.0.2 seems to (mostly?) mitigate this. Would love to know if anybody else sees this behavior and, if so, if there's a workaround for it. I'm not 100% sure, but I don't think this crash is related to the changes in my latest commit. As best I can tell, this PR works perfectly fine right now with Arduino on ESP32, so it seems to be something specific to the '8266.

2024-05-20 03:52 UTC, kbx81 commented
Docs have also been updated according to the updates above -- preview URL: https://deploy-preview-3291--esphome.netlify.app/components/ota_http_request

2024-05-20 10:18 UTC, kbx81 commented
Update: the crash occurs on line 94 in `ota_http_request_arduino.cpp`: `WiFiClient *stream_ptr = this->client_.getStreamPtr();`. I've seen it happen on the ESP32 but only once. I had some success inserting a `delay(50);` inside of the loop...but this slows down the OTA process significantly and is a pretty terrible workaround.

2024-05-20 20:42 UTC, oarcher commented
For http on 8266, I've also encountered the problem, and was not able to completely fix it with the workaround at https://github.com/esp8266/Arduino/issues/9035#issuecomment-1819933172 

For me it was very slow (several hours to complete an OTA), and I was perhaps too much optimistic when it reach more than 70%. I might forgot to wait until the end ...

@kbx81 , you go further than me with the `delay(50)`, but yes, I agree with you that's not an optimal solution 😉.

For me, `3.0.2` seems to be more reliable. I think that reliability is important for this component, because we know that even it's not recommended to do a remote OTA without physical access, users will do it. So we might raise an error if using the 8266 with `esp8266_disable_ssl_support=True` ? If false, users will get an issue if they use `http`, but they will be able to have an emergency recovery with an `https` server...

2024-05-20 21:42 UTC, kbx81 commented
I've been testing exclusively with HTTPS -- but I just tried with HTTP and I get a clean, fast OTA on an '8266 with the existing code as-is with:
```yaml
esp8266:
  board: d1_mini
  framework:
    version: 3.0.2
    platform_version: 3.2.0
```

Using our current default Arduino version (3.1), the OTA starts but, as you mentioned, it is **intolerably** slow (so slow, in fact, that I personally would deem it "unusable"). I'm not going to wait to see if it finishes.

With HTTPS, however, the OTA process runs at a reasonable speed, regardless of the Arduino version; the problem is that it gets to somewhere just after 95% (but before finishing) it crashes, rebooting the '8266, rendering the OTA ineffective. I haven't yet figured out a way around this, but I'm still tinkering with it. 🙂 Using 3.0.2 seems to reduce the likelihood of a crash, but it still crashes much more frequently than it should.

2024-05-21 00:03 UTC, paulsteigel commented
Hi @kbx81,
I tried the component using your guide by adding the following:
```
# Example configuration entry
ota:
  - platform: http_request

# OTA updade trigerred by a button
button:
  - platform: template
    name: Firmware update
    on_press:
      then:
        - ota_http_request.flash:
            md5_url: https://myhome.sfdp.net/local/${name}/firmware.md5
            url: https://myhome.sfdp.net/local/${name}/firmware.bin
        - logger.log: "This message should be not displayed because the device reboots"
```
However, at compiling, the following message were displayed:
```
button.template: [source /config/esphome/./commons/ota_http.yaml:7]
  platform: template
  name: Firmware update
  on_press: 
    then: 
      - 
        Unable to find action with the name 'ota_http_request.flash'.
        ota_http_request.flash: 
          md5_url: https://myhome.sfdp.net/local/quanphamhp1/firmware.md5
          url: https://myhome.sfdp.net/local/quanphamhp1/firmware.bin
      - logger.log: This message should be not displayed because the device reboots
```
It would mean that the "ota_http_request.flash" is no longer avaiable or something else. please advise with thanks!
Best

2024-05-21 02:04 UTC, kbx81 commented
@paulsteigel are you using this PR as an external component? Or have you checked out the branch locally and are building with it that way? `Unable to find action with the name 'ota_http_request.flash'` means that ESPHome isn't finding the component on your end.

2024-05-21 06:31 UTC, kbx81 commented
I pushed a small change that at least prevents a crash when OTA fails on the '8266. This allows retrying until it works...which...may take quite a few attempts...but, at _some_ point, it will work.

@oarcher I don't understand why `this->client_.getStreamPtr()` returns a valid pointer until 95-99% of the way through reading the file. The behavior is so bizarre. This only seems to happen on HTTPS connections; HTTP works fine, at least with 3.0.2 (I've yet to find the patience to wait 3-5 hours for an OTA on a build with 3.1.x to complete 🤣).

2024-05-21 07:56 UTC, paulsteigel commented
> @paulsteigel are you using this PR as an external component? Or have you checked out the branch locally and are building with it that way? `Unable to find action with the name 'ota_http_request.flash'` means that ESPHome isn't finding the component on your end.

Hi @kbx81 
I did not use the pr as the external component (as the compiler complained problem on the PR (see the log) and I decided to use the component directly from your code using just the above declaration.
```
external_components: [source /config/esphome/quanphamhp1.yaml:125]
  - source: github://syssi/esphome-jk-bms@main
    refresh: 0s
  - source: github://pr#5586
    components: 
      
      Could not find __init__.py file for component ota_http. Please check the component is defined by this source (search path: /data/external_components/c2dc8110/esphome/components/ota_http/__init__.py).
      - ota_http
```
Best

2024-05-21 08:20 UTC, kbx81 commented
@paulsteigel the PR has changed a lot and you need to update `external_component` accordingly. It is no longer a component (`ota_http`) and instead has been moved to a platform. It lives within `http_request`, so you need to update your `external_components` like this:

```yaml
external_components:
  - source: github://pr#5586
    components: [ http_request ]
```

2024-05-21 10:44 UTC, paulsteigel commented
> @paulsteigel the PR has changed a lot and you need to update your `external_components` accordingly. It is no longer a component (`ota_http`) and instead has been moved to a platform. It lives within `http_request`, so you need to update your `external_components` like this:
> 
> ```yaml
> external_components:
>   - source: github://pr#5586
>     components: [ http_request ]
> ```

Hi @kbx81,
Great thanks to your response! Now I can test! and will keep reporting to you soon!
Best,
Ngoc

2024-05-21 16:34 UTC, kbx81 commented
@paulsteigel it seems that something is still not correct with your configuration. Could you paste your full yaml config file?

2024-05-21 21:20 UTC, oarcher commented
@kbx81 , I've tried several time an OTA upgrade on 8266 (d1 mini) with HTTPS, with 3.1 . It 100% worked, and I've never reached the `Stream pointer vanished!` error message...

From my previous tests, the only problem I've encountered with HTTPS on 8266, was OOM. But the crash occur sooner, at the SSL/TLS handshake phase. It's why I've originally implemented `safe_mode`, to block the setup of others components, and perform the OTA (discussed at https://github.com/oarcher/piotech/issues/15 with @Alphaemef  and @tomatensaus ) .

 As some components are not initialized (mqtt, text sensors, etc...), I had to write the url to flash. I think that using the `on_connect` trigger at boot will not prevent other components to consume memory ?

`safe_mode` handling has introduced some code complexity, and it's probably a good thing to remove it. But can @Alphaemef and @tomatensaus try now with their use case ?

2024-05-21 22:41 UTC, paulsteigel commented
> @paulsteigel it seems that something is still not correct with your configuration. Could you paste your full yaml config file? I've tested it here and confirmed that `external_components` works as expected with this PR.

Hi @kbx81,
My full Yaml here ( it was splited into several file for easy maintenance, I merge the ota and dyndns together

```
substitutions:
# +--------------------------------------+
# name that will appear in esphome and homeassistant.
  name: quanphamhp1
  dyndnsurl: http://freemyip.com/update?token=cd8bdbfb7cb72dbc96256e55&domain=xxxxx.freemyip.com
  mac_address: 80:65:99:E3:6C:52
  
# +--------------------------------------+
# Number of Battery modules max 8. Each LX U5.4-L battery is 5.4kWh, select the number closest to your capactiy eg 3.2V * 280Ah * 16 = 14.3kWh
  batt_modules: "1"
# +--------------------------------------+
# | Battery Charge Settings              |
# +--------------------------------------+
# Tips for Deye inverter : Add 0.1v to the settings below because the Deye charging voltage is always 0.1v lower than requested.
# Float V. : 53.7v              (3.35v/cell - Natural voltage of a fully charged cell at rest, I advise you not to go higher.)
# Absorption V : 55.3v          (3.45v/cell - It's not necessary to use a charging voltage higher than 55.2V for a full charge.)
# Absorption Offset V. : 0.15v  (The absorption phase will start at 55.15v (BMS voltage). Warning: the BMS voltage must be correctly calibrated.)
# +--------------------------------------+
# This is max charging amps eg 100A, for Bulk - Constant Current charging(CC), should be at least 10A less than BMS change current protection, 0.5C max
# 100A * 50V = 5000W
  charge_a: "100"

  # by Mr. Pablo Factor to control the end of the charge current curve. A setting below 2 will extend the curve, above 2 will shorten the curve. 
  charge_a_factor_curve_end: "2.0"
  discharge_a_factor_curve_end: "2.0"
  # A factor above 1 will reduce current at a fast rate after the float voltage is reached, then slow as a cell reaches the BMS "cell_voltage_overvoltage_recovery".
  charge_a_factor_curve_shape: "1.8"
  discharge_knee_v: "3.1"

  absorption_time: "30"
# +--------------------------------------+
# | Battery Discharge Settings           |
# +--------------------------------------+
# Max discharge amps eg 120, should be at least 10A less than BMS over discharge current protection, 0.5C max
# 120A * 50V = 6000W
  discharge_a: "70"
# +--------------------------------------+
# | Battery State of Health (SOH)        |
# +--------------------------------------+
# Maximum charging cycles is used to calculate the battey SOH, LF280K v3 =8000.0, LF280K v2 =6000.0, LF280=3000.0 (decimal is required)
  max_cycles: "6000.0"
# +--------------------------------------+
# | CAN Protocol Settings                |
# +--------------------------------------+
# CAN BMS Name (0x35E) : 0 NoSent / 1 PYLON / 2 GOODWE / 3 SEPLOS
  can_bms_name: "1"
# CAN Protocol
# 1 : PYLON 1.2 (Deye)
# 2 : SEPLOS 1.0, PYLON 1.3, GOODWE 1.5 (GoodWe, Sol-Ark, Luxpower)
# 3 : SMA (Sunny Island, Sofar)
# 4 : VICTRON
  can_protocol: "1"
# +--------------------------------------+
# | ESP32 CAN/serial port pins           |
# +--------------------------------------+
# GPIO pins your CAN bus transceiver(TJA1050) is connected to the ESP, note! TX->TX and RX->RX. 
  can_tx_pin: GPIO16
  can_rx_pin: GPIO17
# GPIO pins your JK-BMS RS485(TTL) is connected to the ESP TX->RX and RX->TX. 
  tx_pin: GPIO9
  rx_pin: GPIO10
# --------------------------------------

# +------------------------------------------------------------------+
# | ** The settings below can be modified according to your needs ** |
# +------------------------------------------------------------------+
  external_components_source: github://syssi/esphome-jk-bms@main
  # components
  # github://syssi/esphome-jk-bms@main  
  
esphome:
  name: ${name}
  on_boot:
    then:
      - switch.turn_on: switch_charging
      - switch.turn_on: switch_discharging
      - switch.turn_on: switch_chg_float
    
# +--------------------------------------+
# | ESP32 settings                       |
# +--------------------------------------+
# For a stable Bluetooth connection keep the "esp-idf" framework
esp32:
  board: lolin_s2_mini
#  board: esp32doit-devkit-v1
#  framework:
#    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s
  - source: github://pr#5586
    components: [ http_request ]


logger:
  level: INFO

#debug:
#  update_interval: 5s

packages:
  dyndns_pkg: !include ./commons/dyndns.yaml
  otahttp_pkg: !include ./commons/ota_http.yaml
  
# Please use the native `api` component instead of the `mqtt` section.
# If you use Home Assistant, the native API is more lightweight.
# If there is no HA server connected to this API, the ESP32 reboots every 15 minutes to try to resolve the problem.
# If you don't use Home Assistant please uncomment the "reboot_timeout: 0s" option.
#api:
#  reboot_timeout: 0s

# If you don't want to use ESPHome's native API you can use MQQT instead.
# In this case don't forget to remove the 'api:' section.
mqtt:
  broker: example.net
  username: mqtt_user
  password: xxxxxx
  client_id: ${name}_mqtt

# In the event of problems with the WiFi network, the ESP32 will reboot every 15 minutes to try to resolve the problem.
# If we don't want to connect the ESP32 to the WiFi network please remove the 4 lines below.

wifi:
  use_address: ${name}.freemyip.com
  #use_address: 192.168.100.33
  ap:
    ssid: "ESP32S2Lolin"
#    password: !secret wifi_ap_password

captive_portal:

ota:
  password: xxxxxxx
  # Forward this TCP port to do OTA updates remotely
  port: 8266
```
and the dynurrl.yaml. Strange that http_request does not work with https (I am using Esp32S2lolin)
```
http_request:
  id: http_data

time:
  # auto update
  
  - platform: sntp
    # ...
    on_time:
      # Every 10 minutes
      - seconds: 0
        minutes: /10
        #hours: 0
        then:
          - http_request.get:          
              verify_ssl: false
              url: !lambda |-  
                return "${dyndnsurl}";
              headers:
                X-Custom-Header: !lambda |-
                  return "User-Agent: esphome/device;Host: freemyip.com;Accept: */*;";                    
              on_response:            
                then:
                  - logger.log:
                      format: 'Response status: %d, Duration: %u ms'
                      args:
                        - status_code
                        - duration_ms
                  - lambda: |-
                      ESP_LOGI("DynIP", "content: %s", id(http_data).get_string());   
```
and here the ota_http.yaml
```
# Example configuration entry
ota:
  - platform: http_request

# OTA updade trigerred by a button
button:
  - platform: template
    name: Firmware update
    entity_category: config  
    on_press:
      then:
        - ota_http_request.flash:
            md5_url: https://example.net/local/${name}/firmware.md5
            url: https://example.net/local/${name}/firmware.bin
        - logger.log: "This message should be not displayed because the device reboots"
```
Please be so kind to help!

2024-05-21 22:54 UTC, kbx81 commented
@paulsteigel at the very bottom of this file you have:

```yaml
ota:
  password: xxxxxxx
  # Forward this TCP port to do OTA updates remotely
  port: 8266
```

I think that is causing a problem with this new platform. After the next release, that bit of config will need to be updated as follows:

```yaml
ota:
  - platform: esphome
    password: xxxxxxx
    # Forward this TCP port to do OTA updates remotely
    port: 8266
```

However, if you are not building your config on current ESPHome `dev`, this won't work, which is also why you're receiving the `Unable to find action with the name 'ota_http_request.flash'` error. If you use current `dev` for your build(s), this error should go away. Do you know how to do that?

2024-05-21 23:00 UTC, paulsteigel commented
Hi @kbx81,
Thanks for your quick response, i am using nondev esphome. It may also be
the cause of the issue.
I will test the dev version.
Please be sorry for not elaborating the solution properly then!
Best,
Ngoc


On Wed, May 22, 2024, 5:54 AM Keith Burzinski ***@***.***>
wrote:

> @paulsteigel <https://github.com/paulsteigel> at the very bottom of this
> file you have:
>
> ota:
>   password: xxxxxxx
>   # Forward this TCP port to do OTA updates remotely
>   port: 8266
>
> I think that is causing a problem with this new platform. After the next
> release, that bit of config will need to be updated as follows:
>
> ota:
>   - platform: esphome
>     password: xxxxxxx
>     # Forward this TCP port to do OTA updates remotely
>     port: 8266
>
> However, if you are not building your config on current ESPHome dev, this
> won't work, which is also why you're receiving the Unable to find action
> with the name 'ota_http_request.flash' error. If you use current dev for
> your build(s), this error should go away. Do you know how to do that?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/5586#issuecomment-2123561166>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACDODLKYYZ4AWJL3BZTEFL3ZDPGDHAVCNFSM6AAAAAA6LHNNHWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMRTGU3DCMJWGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-21 23:11 UTC, kbx81 commented
Happy to help, @paulsteigel. Keep us posted if you get it working! 🍻😄

2024-05-22 05:13 UTC, kbx81 commented
> @kbx81 , I've tried several time an OTA upgrade on 8266 (d1 mini) with HTTPS, with 3.1 . It 100% worked, and I've never reached the `Stream pointer vanished!` error message...

Ok, must be my setup here, then -- thank you for confirming! I won't chase this issue anymore. 😁

> From my previous tests, the only problem I've encountered with HTTPS on 8266, was OOM. But the crash occur sooner, at the SSL/TLS handshake phase. It's why I've originally implemented `safe_mode`, to block the setup of others components, and perform the OTA (discussed at [oarcher/piotech#15](https://github.com/oarcher/piotech/issues/15) with @Alphaemef and @tomatensaus ) .
> 
> As some components are not initialized (mqtt, text sensors, etc...), I had to write the url to flash. I think that using the `on_connect` trigger at boot will not prevent other components to consume memory ?

To help address this, I've created #6790. This will give you a chance to recover in case you end up in a reboot loop -- should make it possible to grab a "last known good" firmware for recovery from safe mode.

> `safe_mode` handling has introduced some code complexity, and it's probably a good thing to remove it. But can @Alphaemef and @tomatensaus try now with their use case ?

So with #6790, in theory, this should be possible:
1. attempt OTA request
2. OTA fails
3. reboot to safe mode (manually or automagically)
4. attempt OTA request from within `on_safe_mode`
5. OTA works, device reboots
6. all done, move along

Granted, this will not address the use case of the URL being templated and the template output being stored across reboots. _However,_ that's an awful lot of implementation details that can just be solved another way. I would argue that you really don't need a custom URL for each and every new firmware build. I think most people will do one of two things: 1. name the firmware files based on the device name alone or 2. create a directory for each device and use a generic filename for all of them.

If I were to automate it here myself, I think what I would do is create a directory for each device on my web server and populate them like this:
1. `current.bin` is the current/most recent build the device is expected to use/be using.
2. `previous.bin` is the _last known good_ build used.
3. A small number of additional `.bin` files kept for historical purposes, renamed based on creation date (just in case I needed to roll back more than two versions, which, admittedly, I've never ever had to do).

If a device ends up in a reboot loop, `on_safe_mode` triggers this component to pull `previous.bin`, which should allow the device to boot into a known-good firmware again. Recovery done. Does this make sense?

2024-05-22 12:56 UTC, paulsteigel commented
> Happy to help, @paulsteigel. Keep us posted if you get it working! 🍻😄

Hi @kbx81,
I have problem transfering to esphomeDev,
I tried the old yaml but the compiler complained on the git source for the external_component. Hereby, i am using source from github://syssi/esphome-jk-bms@main
I try reading the document on revising the source for fitting with esphomeDev but I failed. Please guide me with thanks.
external_components_source: github://syssi/esphome-jk-bms@main
I am sorry for limited knowledge on this!
Best,

2024-05-22 13:34 UTC, paulsteigel commented
> Happy to help, @paulsteigel. Keep us posted if you get it working! 🍻😄

Hi @kbx81,
I tried converting into the EsphomeDev version but the new platform require my old ota: things be removed
"'ota' requires a 'platform' key but it was not specified."
Without removing that, esphomedev failed to compile the firmware.
Currently, I have no physical touch to the existing one with classic ota: enabled. This means that I have no way to update new firmware to my old device.
Can you advice me on this with thanks.
Best

2024-05-22 14:35 UTC, randybb commented
@paulsteigel OMG https://github.com/esphome/esphome/pull/5586#issuecomment-2123561166

2024-05-22 19:31 UTC, kbx81 commented
@paulsteigel see my comment [here](https://github.com/esphome/esphome/pull/5586#issuecomment-2123561166) -- the message `'ota' requires a 'platform' key but it was not specified` indicates that you need to update your config as I mentioned in the comment. Once you do this, you'll be able to update your device(s) just as before. 😄

2024-05-22 21:41 UTC, kbx81 commented
After some further review/discussion, we've removed the MD5 check for the "already installed" condition. I'll explain a bit here:
1. Any given component should perform only the task it is intended/expected to do. As an example, the existing "push"/native OTA component doesn't care what firmware is installed -- if you push firmware, it accepts and performs the OTA. It does not reject an OTA for any reason other than an actual  _failure_ of its task, such as a network/connection failure or data corruption.
2. The MD5 check can be accomplished with minimal additional components (such as a text sensor).
3. It further simplifies this component both in terms of the code and its use by end-users.

2024-05-22 23:44 UTC, paulsteigel commented
> @paulsteigel see my comment [here](https://github.com/esphome/esphome/pull/5586#issuecomment-2123561166) -- the message `'ota' requires a 'platform' key but it was not specified` indicates that you need to update your config as I mentioned in the comment. Once you do this, you'll be able to update your device(s) just as before. 😄

Hi @kbx81,
Please be sorry for over looking your comment before,
I revissed the config as following:
```
ota:
  - platform: http_request
    exclude_certificate_bundle: true
  - platform: esphome
    password: [password]
    port: 8266    
    
# OTA updade trigerred by a button
button:
  - platform: template
    name: Firmware update
    entity_category: config
    id: ${name}_firmware_update
    on_press:
      then:
        - ota_http_request.flash:
            md5_url: https://example.net/local/${name}/firmware.md5
            url: https://example.net/local/${name}/firmware.bin
        - logger.log: "This message should be not displayed because the device reboots"
```
The building of the firmware is finally done successfully, However, the Install and direct push of build image (with dev) to the existing OTA device throw the following error:
```
Creating esp32s2 image...
Successfully created esp32s2 image.
esp32_create_combined_bin([".pioenvs/tunglan1976/firmware.bin"], [".pioenvs/tunglan1976/firmware.elf"])
Wrote 0x122870 bytes to file /data/build/tunglan1976/.pioenvs/tunglan1976/firmware-factory.bin, ready to flash to offset 0x0
======================== [SUCCESS] Took 227.04 seconds ========================
INFO Successfully compiled program.
INFO Resolving IP address of tunglan1976.freemyip.com
INFO  -> 1.55.78.174
INFO Uploading /data/build/tunglan1976/.pioenvs/tunglan1976/firmware.bin (1124464 bytes)
ERROR Error receiving acknowledge version: timed out
```
I have a device at the above address and use previous image build with Esphome.
I knew that you are very busy, if you can, please share with me your email to ngocdd@sfdp.net, then I can provide you direct access to my Home assistant server for you to check this case.
Thank you very much for your attention and guidance!
Best,
Ngoc

2024-05-23 03:00 UTC, Alphaemef commented
Hey guys. Really enjoy the work you are doing here. Im super swamped, so haven't had the chance to test this properly yet. But I will as soon as humanly possible. 

Here are a few cents for what they are worth on the discussion:

> After some further review/discussion, we've removed the MD5 check for the "already installed" condition. I'll explain a bit here:
> 
> 1. Any given component should perform only the task it is intended/expected to do. As an example, the existing "push"/native OTA component doesn't care what firmware is installed -- if you push firmware, it accepts and performs the OTA. It does not reject an OTA for any reason other than an actual  _failure_ of its task, such as a network/connection failure or data corruption.
> 2. The MD5 check can be accomplished with minimal additional components (such as a text sensor).
> 3. It further simplifies this component both in terms of the code and its use by end-users.

This makes perfect sense. I assume the md5 check remains for the actual transfer: i.e it will still check for md5 before initiating and compare with actual received. The rest can be achieved by updating a md5 value in a text sensor, store that in flash, and perform an automated check before the http_request activation. 

> So with #6790, in theory, this should be possible:
> 
> 1. attempt OTA request
> 2. OTA fails
> 3. reboot to safe mode (manually or automagically)
> 4. attempt OTA request from within `on_safe_mode`
> 5. OTA works, device reboots
> 6. all done, move along
> 
> Granted, this will not address the use case of the URL being templated and the template output being stored across reboots. _However,_ that's an awful lot of implementation details that can just be solved another way. I would argue that you really don't need a custom URL for each and every new firmware build. I think most people will do one of two things: 1. name the firmware files based on the device name alone or 2. create a directory for each device and use a generic filename for all of them.

I understand the thought process behind this completely. 
However ill just point out a few benefits of the template able URL / stored in flash option:
In my use case I actually use the template URL, just to make sure that in case there are domain changes, port changes or similar, I can divert the update path to a new location without hiccups. I also appreciate that the units can't spam requests, without explicitly being handed the credentials and target, and then only for one request. (since the provided credentials are published on a non-retained topic that only the target client can sub to via the ACL)

2024-05-23 04:37 UTC, kbx81 commented
> This makes perfect sense. I assume the md5 check remains for the actual transfer: i.e it will still check for md5 before initiating and compare with actual received.

Correct -- the md5sum is still used to verify the integrity of the firmware received by the device. It's just no longer stored.

> > Granted, this will not address the use case of the URL being templated and the template output being stored across reboots. _However,_ that's an awful lot of implementation details that can just be solved another way. I would argue that you really don't need a custom URL for each and every new firmware build. I think most people will do one of two things: 1. name the firmware files based on the device name alone or 2. create a directory for each device and use a generic filename for all of them.
> 
> I understand the thought process behind this completely. However ill just point out a few benefits of the template able URL / stored in flash option: In my use case I actually use the template URL, just to make sure that in case there are domain changes, port changes or similar, I can divert the update path to a new location without hiccups. I also appreciate that the units can't spam requests, without explicitly being handed the credentials and target, and then only for one request. (since the provided credentials are published on a non-retained topic that only the target client can sub to via the ACL)

You can still use a template for the URL -- it just won't be stored across reboots (for example, should your device crash during OTA). That said, if it crashes during OTA, it'll have to repeatedly do so to invoke safe mode. If you end up in safe mode on a device that you don't have any form of physical access to...well, I'm just going to say it: you have a much bigger problem you need to solve. 😅

I realize that devices sometimes crash during OTA; for me, it's quite the exception, but I _have_ seen it happen. Even so, the device reboots, I attempt the OTA again, it works, life goes on. I'm going to assert that, if your device is _so_ taxed that crashes (during OTA or otherwise) are a regular occurrence, it's time to seriously consider either unloading some of the workload from the device or getting a "more powerful" device (for example, moving from an '8266 to an ESP32 or variant). You really should not be making special accommodations to cope with regular crashes (during OTA or otherwise) on a device that's not within arm's reach. 😇

2024-05-23 05:54 UTC, paulsteigel commented
Hi @kbx81,
Please be sorry for disturbing you, I have successfully use clasic OTA firmware update as stated on the above to flash with new firmware with the EsphomeDev version with ota_http request platform. The button for update firmware is shown. Logger is set with DEBUG. I build a new firwmware with Logger set to INFO and put it on my server with md5 file created as guided. However, when pressing the firmware update, nothing happen (I follow the log but nothing relating to the ota_http flash request has been made. Assuming that the flashing work, I waited for 10 minutes and check the log, it still in DEBUG mode (mean the new firmware flash did not happen).
If possible and you have time, please be so kind to drop me a mail to ngocdd@sfdp.net so I can show you my server details for checking with thanks. Firmware is created in legacy format as guided.
the firmware is hosted at https://myhome.sfdp.net/local/tunglan1976/firmware.bin

2024-05-23 06:10 UTC, paulsteigel commented
Hi @kbx81
Regarding your point here: 
> Granted, this will not address the use case of the URL being templated and the template output being stored across reboots. _However,_ that's an awful lot of implementation details that can just be solved another way. I would argue that you really don't need a custom URL for each and every new firmware build. I think most people will do one of two things: 1. name the firmware files based on the device name alone or 2. create a directory for each device and use a generic filename for all of them.
> 
> If I were to automate it here myself, I think what I would do is create a directory for each device on my web server and populate them like this:
> 
> 1. `current.bin` is the current/most recent build the device is expected to use/be using.
> 2. `previous.bin` is the _last known good_ build used.
> 3. A small number of additional `.bin` files kept for historical purposes, renamed based on creation date (just in case I needed to roll back more than two versions, which, admittedly, I've never ever had to do).
> 
> If a device ends up in a reboot loop, `on_safe_mode` triggers this component to pull `previous.bin`, which should allow the device to boot into a known-good firmware again. Recovery done. Does this make sense?

What I would feel absolutely good for the people is to have an additional menu item beside Install or in the dialogue to choose option for building firmware such as: Firmware for ota_http, the automating process then will be:
1. Create a folder under /homeassistant/www/[devicename]/firmware.bin. Then the firmware can be downloaded from
https://example.net/local/[devicename]/firmware.bin
2. Click update firmware button
This will be alot helpful for newbies like me then.
Currently, I have to do exactly the same as you said: Create firmware (legacy format), copy to HA server (at folder /homeassistant/www/[devicename]/) and rename to firmware.bin, and create md5 file.
Still not yet successfully in making the ota_http work over esphome Dev, but with your further guidance I am sure this can be done.
Thank you very much for your great endeavor to help people like us. we benefit a lot from your contribution. I am working on creating pump, valve controller for cutting the cost for rural farmer to apply IOT into their farming work, and this ota_http component from @oarcher and your further refining is of great value!
Best

2024-05-23 08:16 UTC, kbx81 commented
@paulsteigel the best way to get help would be to [join us on Discord](https://discord.gg/KhAMKrd) 😄

2024-05-23 08:28 UTC, paulsteigel commented
Hi @kbx81,
Thanks for your reply, last time you posted the discord link but i was not
allow to join.
Thanks to your invitation to discord this time.
I will join and seek for help!
All the best
Ngoc

On Thu, May 23, 2024, 3:16 PM Keith Burzinski ***@***.***>
wrote:

> @paulsteigel <https://github.com/paulsteigel> the best way to get help
> would be to join us on Discord <https://discord.gg/KhAMKrd> 😄
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/5586#issuecomment-2126505079>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACDODLPUJTMLBVA2XPXLW5LZDWQV5AVCNFSM6AAAAAA6LHNNHWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMRWGUYDKMBXHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-23 12:32 UTC, oarcher commented
@kbx81, what do you think about adding an `on_md5` callback? Without it, and with just `md5_url`, the user has to set up an HTTP request to fetch the md5, which is a bit of a hassle. It would be much simpler to get it through a callback (or maybe a public method?).

This way, the user can easily compare the md5 with the one they've saved in preferences and decide whether they want to continue or not.

2024-05-24 01:06 UTC, kbx81 commented
> @kbx81, what do you think about adding an `on_md5` callback? Without it, and with just `md5_url`, the user has to set up an HTTP request to fetch the md5, which is a bit of a hassle. It would be much simpler to get it through a callback (or maybe a public method?).
> 
> This way, the user can easily compare the md5 with the one they've saved in preferences and decide whether they want to continue or not.

Good idea -- I added a couple of methods to allow that (since the data is there, anyway...might as well make it available). 😄 This way, you can simply give the platform an ID and then refer to it with `id(...)` in lambdas within the various triggers. For example:

```yaml
ota:
  - platform: http_request
    id: my_http_request
    on_error:
      - lambda: ...
```

2024-05-24 02:21 UTC, kbx81 commented
...on second thought, that might not quite address what you were asking, @oarcher. 😅

To remain consistent with patterns elsewhere in ESPHome, the logic to determine whether or not to proceed with the flash needs to remain outside of this component. Yes, that's going to mean that, if you're using a file to store the (new) MD5, you're going to need to build something elsewhere in your YAML to do the HTTP request to get that value.

Note that, one of the other changes I snuck in is to allow the MD5 to be set another way -- that is, you could set it via a user API call or a `text` component (set via HA). You no longer _have_ to use HTTP(S) to get the (new) MD5 value, which I think will make it easier for some folks.

2024-05-26 22:42 UTC, jesserockz requested changes
Here is my partial review

2024-05-26 22:42 UTC, jesserockz commented on esphome/components/http_request/ota/__init__.py
> +        template_ = await cg.templatable(config[CONF_MD5_URL], args, cg.std_string)
🦭 (not exactly a walrus emoji, but close enough :sweat_smile:)

```suggestion
    if md5_url := config.get(CONF_MD5_URL):
        template_ = await cg.templatable(md5_url args, cg.std_string)
```

2024-05-26 22:42 UTC, jesserockz commented on esphome/components/http_request/ota/__init__.py
> +    return urlparse.urlunparse(parsed)
This should use `cv.url` to cut down on duplicate code

2024-05-26 22:42 UTC, jesserockz commented on esphome/components/http_request/ota/__init__.py
> +    return config
I feel like this validation is overly complex...
This should just be a `SplitDefault` and `cv.only_on_esp32` directly on the config item with a custom validation only for `not idf` with the custom message.

2024-05-26 22:42 UTC, jesserockz commented on esphome/components/http_request/ota/ota_http_request_arduino.cpp
> +#endif
To make this "safer" and no need to reset later, use a constructor and deconstructor similar to `InterruptLock` so that it will auto reset when it goes out of scope and gets cleaned up.

2024-05-26 22:42 UTC, jesserockz commented on esphome/components/http_request/ota/__init__.py
> +            "CONFIG_WATCHDOG_TIMEOUT", config[CONF_WATCHDOG_TIMEOUT].total_milliseconds
This should be `USE_HTTP_REQUEST_OTA_WATCHDOG_TIMEOUT` to match the ESPHome naming for defines

2024-05-26 22:42 UTC, jesserockz commented on esphome/components/http_request/ota/__init__.py
> +AUTO_LOAD = ["md5", "ota"]
As this is an `ota` platform, it will always be loaded
```suggestion
AUTO_LOAD = ["md5"]
```

2024-05-26 22:42 UTC, jesserockz commented on esphome/components/http_request/ota/automation.h
> +  TEMPLATABLE_VALUE(bool, force_update)
Not used?
```suggestion
```

2024-05-26 22:42 UTC, jesserockz commented on esphome/components/http_request/ota/ota_http_request.cpp
> +  this->md5_computed_ = md5_receive_str.get();
What is the purpose of having this string stored in a member variable after we are done with it?

2024-05-26 22:42 UTC, jesserockz commented on esphome/components/http_request/ota/ota_http_request.cpp
> +    this->state_callback_.call(ota::OTA_ERROR, 0.0f, 0);
The last argument to this is an error code which should have a value for each of the different error states.

2024-05-27 04:11 UTC, kbx81 commented on esphome/components/http_request/ota/__init__.py
> +        template_ = await cg.templatable(config[CONF_MD5_URL], args, cg.std_string)
D'oh...I missed this one. Thank you! 🦭

2024-05-27 04:13 UTC, kbx81 commented on esphome/components/http_request/ota/__init__.py
> +    return urlparse.urlunparse(parsed)
Yup, meant to change this. 🤦🏻‍♂️

2024-05-27 04:15 UTC, kbx81 commented on esphome/components/http_request/ota/automation.h
> +  TEMPLATABLE_VALUE(bool, force_update)
Yup, I missed removing this after the last batch of changes. 🤦🏻‍♂️

2024-05-27 04:18 UTC, kbx81 commented on esphome/components/http_request/ota/ota_http_request.cpp
> +  this->md5_computed_ = md5_receive_str.get();
The motivation for this is to allow any triggers that might want to store the value elsewhere (in a `global` or `text`, for example) to do so using the accessor method.

2024-05-27 09:57 UTC, kbx81 commented on esphome/components/http_request/ota/__init__.py
> +    return urlparse.urlunparse(parsed)
Done in [`1d8a3cb`](https://github.com/esphome/esphome/pull/5586/commits/1d8a3cb509976faf9b92f76138a00301c28f328a)

2024-05-27 09:58 UTC, kbx81 commented on esphome/components/http_request/ota/__init__.py
> +    return config
Done in [`1d8a3cb`](https://github.com/esphome/esphome/pull/5586/commits/1d8a3cb509976faf9b92f76138a00301c28f328a)

2024-05-27 09:58 UTC, kbx81 commented on esphome/components/http_request/ota/__init__.py
> +            "CONFIG_WATCHDOG_TIMEOUT", config[CONF_WATCHDOG_TIMEOUT].total_milliseconds
Done in [`1d8a3cb`](https://github.com/esphome/esphome/pull/5586/commits/1d8a3cb509976faf9b92f76138a00301c28f328a)

2024-05-27 09:58 UTC, kbx81 commented on esphome/components/http_request/ota/ota_http_request.cpp
> +    this->state_callback_.call(ota::OTA_ERROR, 0.0f, 0);
Done in [`1d8a3cb`](https://github.com/esphome/esphome/pull/5586/commits/1d8a3cb509976faf9b92f76138a00301c28f328a)

2024-05-29 07:11 UTC, kbx81 commented on esphome/components/http_request/ota/ota_http_request_arduino.cpp
> +#endif
Done in [`f6cdf40`](https://github.com/esphome/esphome/pull/5586/commits/f6cdf40835b34fe9fc49ed2cabd565c40401c2db)

2024-06-05 16:20 UTC, paulsteigel commented
Hi @kbx81 and @oarcher,
I did a new HA installation with ESPHOME dev and continue the test above. My HA sit behind a draytek Vigor2920 router with port 443 forwarded to the HA server (that is listening on 443 with Let'sencrypt certificate). Testing of files (md5 and bin) is working fine with browser.
However, when I click the button, the following error appear.
```
23:08:29][I][http_request.ota:268]: Connecting to: https://myhome.sfdp.net/local/tunglan1976/firmware.md5
[23:08:29][E][http_request.ota:074]: HTTP server did not respond (error -1)
```
Can you please be so kind to advice me on what I am doing wrong.
Thanks for your attention.
Ngoc!

2024-06-05 21:06 UTC, oarcher commented
@paulsteigel , the `force_update` option has been removed.

For `HTTP server did not respond (error -1)`, I think that you have bad network configuration. 
Can you check with a simple `http_request` ?

```
http_request:
  id: http_data


button:
  - platform: template
    name: "http_request test"
    on_press:
      - http_request.get:
          url: https://myhome.sfdp.net/local/${name}/firmware.md5
          verify_ssl: false
          on_response:
            then:
              - logger.log:
                  format: 'Response status: %d, Duration: %u ms'
                  args:
                    - status_code
                    - duration_ms
              - lambda: |-
                  ESP_LOGI("test", "content: %s", id(http_data).get_string());
```

Also try with a public server url, like `https://api.ipify.org/?format=text`

2024-06-06 01:57 UTC, jesserockz approved these changes

2024-06-06 02:35 UTC, merged

2024-06-06 15:32 UTC, paulsteigel commented
> @paulsteigel , the `force_update` option has been removed.
> 
> For `HTTP server did not respond (error -1)`, I think that you have bad network configuration. Can you check with a simple `http_request` ?
> 
> ```yaml
> http_request:
>   id: http_data
> 
> 
> button:
>   - platform: template
>     name: "http_request test"
>     on_press:
>       - http_request.get:
>           url: https://myhome.sfdp.net/local/${name}/firmware.md5
>           verify_ssl: false
>           on_response:
>             then:
>               - logger.log:
>                   format: 'Response status: %d, Duration: %u ms'
>                   args:
>                     - status_code
>                     - duration_ms
>               - lambda: |-
>                   ESP_LOGI("test", "content: %s", id(http_data).get_string());
> ```
> 
> Also try with a public server url, like `https://api.ipify.org/?format=text`

Many thanks to @oarcher 
I will test tomorrow! One thing specifically, my HA often restart since installing the Esphome Dev and the Ota_http component! I tried checking the system log but the reason is not known yet!
I will check problem in detail during this weekend!
Best 
Ngoc

2024-06-06 18:32 UTC, tomatensaus commented
@paulsteigel 
> Can you please be so kind to advice me on what I am doing wrong.
> Thanks for your attention.

If you specify a static IP be sure to also include the nameserver entry in your network configuration. I once spent a whole day trying to figure out why I could work from an IP and not to my domain. I remember the error message was very confusing but I cannot recall if this is the same case

2024-06-08 13:52 UTC, cavamora commented
hi! how do i use this? trying to follow the docs without luck...

2024-06-10 16:07 UTC, kbx81 commented
We have merged some follow-on changes that affect this component -- the updated docs are available on the preview ESPHomes site: https://next.esphome.io/components/ota_http_request

Note that some config variables have been moved to the `http_request` component itself (as opposed to the `http_request`  OTA _platform_), which is now required to use this component: https://next.esphome.io/components/http_request

@cavamora please check the updated docs as the instructions you're finding in comments on this PR won't work anymore. 😄

2024-06-11 03:51 UTC, kbx81 commented
For anybody here who is still paying attention to the PR and was concerned about the MD5 stuff -- check out what we are doing in #6885. 😉