Add SHT2X
OttoWinter/esphomeyaml pull request #5635
Opened 2023-10-31 09:44 UTC by dmaasland

# What does this implement/fix?

Add the SHT2x sensor component.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
   sensor:
    - platform: sht2x
       temperature:
         name: "Living Room Temperature"
       humidity:
         name: "Living Room Humidity"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-10-31 15:38 UTC, kahrendt requested changes
I don't have a sensor to test it with, but I looked through your code and added comments for a few things that I have missed in my previous PRs. Nice work overall!

2023-10-31 15:38 UTC, kahrendt commented on esphome/components/sht2x/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_TEMPERATURE])
```
    if temperature_config := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_config)
```

2023-10-31 15:38 UTC, kahrendt commented on esphome/components/sht2x/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_HUMIDITY])
```
    if humidity_config := config.get(CONF_HUMIDITY):
        sens = await sensor.new_sensor(humidity_config)
```

2023-10-31 15:38 UTC, kahrendt commented on esphome/components/sht2x/sht2x.cpp
> +  crc = crc8_(buffer, 2);
`crc = this->crc8_(buffer, 2);`

2023-10-31 15:38 UTC, kahrendt commented on esphome/components/sht2x/sht2x.cpp
> +  uint16_t raw_temperature = read_raw_value_();
Change this everywhere you call a class function (see https://esphome.io/guides/contributing.html#codebase-standards)
`  uint16_t raw_temperature = this->read_raw_value_();`

2023-10-31 15:38 UTC, kahrendt commented on esphome/components/sht2x/sht2x.cpp
> +  delay(SHT2X_DELAY_HUMIDITY);  // NOLINT
Avoid the delay here too

2023-10-31 15:38 UTC, kahrendt commented on esphome/components/sht2x/sht2x.h
> +  void set_humidity_sensor(sensor::Sensor *humidity_sensor) { humidity_sensor_ = humidity_sensor; }
Don't forget to add ``this->`` in this file as well.

2023-10-31 15:40 UTC, kahrendt commented on esphome/components/sht2x/sht2x.cpp
> +  delay(SHT2X_DELAY_HUMIDITY);  // NOLINT
I must have dropped the first comment for get_temperature. You should use ``set_timeout`` instead of NOLINT and a delay to avoid blocking the main loop. It will require you to restructure your code a bit to make it work.

2023-11-07 12:31 UTC, dmaasland commented
Thanks for your review @kahrendt. I think i've resolved all of them :)

2023-11-07 13:09 UTC, kahrendt commented on esphome/components/sht2x/sht2x.cpp
> +  this->set_timeout(SHT2X_DELAY_HUMIDITY + 10, [this]() { this->handle_temperature_(); });
Move the check for if ``humidity_sensor_`` and ``temperature_sensor_`` are not ``nullptr`` here. If a sensor is not configured, then the handle code will never need to run in the first place (assuming the SHT2X is okay with only ever requesting one type of measurement).

2023-11-07 13:31 UTC, dmaasland commented on esphome/components/sht2x/sht2x.cpp
> +  this->set_timeout(SHT2X_DELAY_HUMIDITY + 10, [this]() { this->handle_temperature_(); });
Done! Should be fine. Added a small check to remove the delay if the humidity sensor isn't available.

2023-11-07 13:31 UTC, kahrendt approved these changes
Looks good to me!

2024-02-14 00:44 UTC, closed without merging