Support for CST 860 Touch screen controller
OttoWinter/esphomeyaml pull request #5641
Opened 2023-10-31 19:25 UTC by dirkjankrijnders

# What does this implement/fix?

Added support for the CST860 Touch screen controller as found on 2432S024C boards. Implementation is based on other implementations as a datasheet for this controller is not readily available
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
ouchscreen:
  platform: cst860
  id: my_touchscreen
  i2c_id: bus_a
  update_interval: 50ms
  report_interval: 1s
  x_max: 240
  y_max: 320
  invert_y: false
  swap_x_y: false
  on_touch:
      - lambda: |-
            ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                id(my_touchscreen).x,
                id(my_touchscreen).y,
                id(my_touchscreen).x_raw,
                id(my_touchscreen).y_raw
                );
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-11-01 02:17 UTC, nielsnl68 commented
Hello @dirkjankrijnders, how are you doing? Recently i created a PR around the touchscreen component's, trying to make it more universal. (https://github.com/esphome/esphome/pull/4596) could you check it out and make the needed changes to your component so we can merge both at the same time?

2023-11-12 20:12 UTC, dirkjankrijnders commented
Hi @nielsnl68, I've been looking through your PR and looks like a very useful change. But I'm a bit lost on how to change my PR. I guess forking yours and adapting my changes to that would work. I also have no issues waiting a bit for your PR to be merged and then following up on this one.

2023-11-21 11:30 UTC, nielsnl68 reviewed
The following changes are based on the new touchscreen component. As you can see a lot of work has been taken out of your hands already by the Touchscreen class.

At the moment you do not need to update any of the changes. Until my PR https://github.com/esphome/esphome/pull/4596 is merged.

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/binary_sensor.py
You can remove this file.

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.cpp
> +void CST860TouchscreenStore::gpio_intr(CST860TouchscreenStore *store) { store->touch = true; }
```suggestion
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.cpp
> +
```suggestion
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.cpp
> +void CST860Component::check_touch_() {
```suggestion
void CST860Component::update_touches() {
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.cpp
> +    };
```suggestion
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.cpp
> +  };
```suggestion
    y = (((data[0] & 0x0f) << 8) | data[1]);
    x = (((data[2] & 0x0f) << 8) | data[3]);
    set_raw_touch_posistion_(0, x, y);
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.h
> +  void update() override;
```suggestion
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.h
> +  int16_t x_raw{0}, y_raw{0}, z_raw{0};
```suggestion
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.h
> +  void check_touch_();
```suggestion
  void update_touches() override;
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.h
> +  CST860TouchscreenStore store_;
```suggestion
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.h
> +  }
```suggestion
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.h
> +  uint32_t get_report_interval() { return this->report_millis_; }
```suggestion
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/cst860.h
> +
```suggestion
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/touchscreen.py
> +            cv.Optional(CONF_REPORT_INTERVAL, default="never"): report_interval,
```suggestion
```

2023-11-21 11:30 UTC, nielsnl68 commented on esphome/components/cst860/touchscreen.py
> +    cg.add(var.set_report_interval(config[CONF_REPORT_INTERVAL]))
```suggestion
```

2023-11-21 11:33 UTC, nielsnl68 commented
Hallo @dirkjankrijnders do you have any code or documentation that you used to based this code on? I love to compare and help make this PR better,

2023-11-26 12:50 UTC, dirkjankrijnders commented
I based this mostly on this [code](https://github.com/rzeldent/esp32-smartdisplay/blob/main/src/touch_cst820.cpp)

2023-11-26 15:11 UTC, dirkjankrijnders commented
Another implementation is [here](https://github.com/Xinyuan-LilyGO/T-RGB/blob/main/lib/TouchLib/src/ModulesCSTSelf.tpp)

2023-12-17 09:51 UTC, dirkjankrijnders commented
I spend some time digging further and it turns out the device actually is a CST820. The legend on the chip was badly readable... That led to a product page: http://en.hynitron.com/product/wearable/126. But the datasheet link there is dead, also on the Chinese version. However I found the datasheet for the CST816S:  https://www.buydisplay.com/download/ic/DS-CST816S_DS_V1.3.pdf. This seems pretty similar if I compare to the other implementations. I'll update this PR when I have found some time to process the new information and played with the new touchscreen implementation.

2023-12-17 20:28 UTC, nielsnl68 commented
> I based this mostly on this [code](https://github.com/rzeldent/esp32-smartdisplay/blob/main/src/touch_cst820.cpp)

Hi @dirkjankrijnders As of this month the touchscreen main class has got the update that i talked about earlier, please check out the dev or beta branch of esphome. The only thing you now need to do is setup the needed pins and override the `update_touches_()` method. and call `set_raw_touch_position_(id, raw_x, raw_y [, pressure]);` for every detected touch on the screen.

2023-12-22 19:26 UTC, nielsnl68 requested changes
Starting to look good. Still 3 small changes to make. 
Thanks for your effort.

2023-12-22 19:26 UTC, nielsnl68 commented on esphome/components/cst820/touchscreen/cst820.cpp
> +  };
```suggestion
    if (this->display_ != nullptr) {
      if (this->x_raw_max_ == this->x_raw_min_) {
        this->x_raw_max_ = this->display_->get_width_internal();
      }
      if (this->y_raw_max_ == this->y_raw_min_) {
        this->y_raw_max_ = this->display_->get_height_internal();
      }
    }
```

2023-12-22 19:26 UTC, nielsnl68 commented on esphome/components/cst820/touchscreen/cst820.cpp
> +  set_raw_touch_position_(0, x, y);
```suggestion
  set_raw_touch_position_(fingerindex, x, y);
```

2023-12-22 19:26 UTC, nielsnl68 commented on esphome/components/cst820/touchscreen/cst820.h
> +  float get_setup_priority() const override;
Im not sure of we should add the `get_setup_priority()` override. None of the existing touchscreen drivers (except the *XPT2046*) has it set atm.  So i decided to remove it also from the  *XPT2046* driver.

2023-12-22 19:58 UTC, dirkjankrijnders commented on esphome/components/cst820/touchscreen/cst820.cpp
> +  set_raw_touch_position_(0, x, y);
Of course, fixed

2023-12-22 19:58 UTC, dirkjankrijnders commented on esphome/components/cst820/touchscreen/cst820.h
> +  float get_setup_priority() const override;
I kept as my example code had it, will be removed here as well.

2023-12-22 20:01 UTC, dirkjankrijnders commented on esphome/components/cst820/touchscreen/cst820.cpp
> +  };
The _internal are member of `DisplayBuffer`, but `this->display_` is of class `Display`. How to resolve that neatly?

2023-12-22 21:23 UTC, nielsnl68 commented
BTW, are you sure this is a single touch display?

2023-12-23 10:14 UTC, dirkjankrijnders commented
> BTW, are you sure this is a single touch display?

No, I think it is multitouch, I get `fingerindex = 2` when I use two or more touches. I have never seen `fingerindex = 3`. However, the X en Y register only report 1 coordinate, the first one, in my testing. However, looking through other implementations there seem to be more registers then the datasheet defines. I focussed on getting single stable first, before diving into undocumented features. I do plan to revisit multi touch in the future though.

2024-02-25 08:59 UTC, pixelwave commented
> Added support for the CST860 Touch screen controller as found on 2432S024C boards.

I have the ESP32-2432S024C. I think it has the CST820 touch controller? Maybe a typo because the headline says 820 as well? Or maybe I am missing something ...

Anyways I would like to get the touch functionality working. I got the screen displaying stuff with this code:

`color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%

spi:
 clk_pin: GPIO14
 mosi_pin: GPIO13
 miso_pin: GPIO12

display:
  - platform: ili9xxx
    model: TFT 2.4
    cs_pin: GPIO15
    dc_pin: GPIO2
    rotation: 90
    id: tft_ha
    lambda: |-
      it.fill(my_red);`

How to I get the touch now working / what files to I have to include in my ESPHome build? Sorry I am still learning ESPHome ... quite new to the syntax...

2024-02-25 12:30 UTC, dirkjankrijnders commented
Hi,

There is another PR that supports this chip is a more generic sense: https://github.com/esphome/esphome/pull/5941. That PR sees more active development. 
I plan to support that PR instead of this one, but I have no working hardware at the moment to test either one.

2024-02-26 07:20 UTC, pixelwave commented
Thanks @dirkjankrijnders for the feedback. Will look into this PR. Do you know if the CST820 is compatible with the CST816?

2024-03-11 03:35 UTC, clydebarrow commented
Closing in favour of #5941

2024-03-11 07:38 UTC, clydebarrow commented
> Thanks @dirkjankrijnders for the feedback. Will look into this PR. Do you know if the CST820 is compatible with the CST816?

The CST820 is supported in ESPHome now - just merged into `dev` branch, as part of the `cst816` component. Beta goes out this week I believe.

2024-03-12 07:08 UTC, pixelwave commented
Awesome - thanks @clydebarrow !

Would love to do some testing. But need help how to use the dev branch / integrate the touch controller...  I started this way: https://github.com/esphome/esphome/pull/5941#issuecomment-1963471884

2024-03-12 08:14 UTC, clydebarrow commented
> Awesome - thanks @clydebarrow !
> 
> Would love to do some testing. But need help how to use the dev branch / integrate the touch controller... I started this way: [#5941 (comment)](https://github.com/esphome/esphome/pull/5941#issuecomment-1963471884)

You can install the ESPHome (dev) addon in HA. That will build against the dev branch. Or wait for the beta in a few days and use the beta addon.

2024-03-12 08:14 UTC, closed without merging