wifi: Don't build SoftAP/DHCPS support unless 'ap' is in config.
OttoWinter/esphomeyaml pull request #5649
Opened 2023-11-01 10:54 UTC by kpfleming

# What does this implement/fix?

Optimization: don't build the SoftAP and DHCP server code (in the ESP-IDF framework) unless the ESPHome config includes `ap`; don't build AP setup code in the `wifi` component either in that case.

Also updates version of `flake8` in pre-commit config to avoid a false negative when checking `__init__.py` in the wifi component.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Other

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

2023-11-01 23:13 UTC, ChillingSilence commented
cACK, sounds nice for me as someone who has a bunch of PoE devices that don't have any WiFi / AP support :)

2023-11-02 03:54 UTC, jesserockz requested changes

2023-11-02 03:54 UTC, jesserockz commented on esphome/components/wifi/__init__.py
> +        cg.add_define("ENABLE_WIFI_AP")
To match other defines in ESPHome we follow `USE_<component>[_<something>]`

```suggestion
        cg.add_define("USE_WIFI_AP")
```

2023-11-02 03:54 UTC, jesserockz commented on .pre-commit-config.yaml
I have bumped this is its own pr https://github.com/esphome/esphome/pull/5658

2023-11-02 03:54 UTC, jesserockz commented on esphome/components/wifi/wifi_component.cpp
> +#if ENABLE_WIFI_AP
This might as well be one line above so there is no empty if block

2023-11-02 10:16 UTC, kpfleming commented
> cACK, sounds nice for me as someone who has a bunch of PoE devices that don't have any WiFi / AP support :)

This PR is unlikely to be useful for you; if your YAML does not have the `wifi` component then none of the WiFi code (all of it, not just SoftAP) should be linked into the binary. It's still being compiled, and there's no easy to way to avoid compiling *all* of the WiFi code.

2023-11-02 10:29 UTC, kpfleming commented on esphome/components/wifi/__init__.py
> +        cg.add_define("ENABLE_WIFI_AP")
Making this change now; should I also add `USE_WIFI_API` to `defines.h` for static analyzer/IDE usage?

2023-11-02 10:30 UTC, kpfleming commented on esphome/components/wifi/wifi_component.cpp
> +#if ENABLE_WIFI_AP
Good point, I've found a few other places where the entire block should be inside the ifdef-endif too.

2023-11-05 22:48 UTC, jesserockz commented on esphome/components/wifi/__init__.py
> +        cg.add_define("ENABLE_WIFI_AP")
Yes =)

2023-11-05 22:51 UTC, jesserockz reviewed
Please do add to `defines.h` then this PR is good to merge

2023-11-06 12:30 UTC, kpfleming commented
Done, and CI tests found another bug which has also been fixed :-)

2023-11-20 03:32 UTC, jesserockz approved these changes

2023-11-20 03:32 UTC, merged