Checks for pins used in multiple places
OttoWinter/esphomeyaml pull request #5666
Opened 2023-11-03 10:58 UTC by clydebarrow

# What does this implement/fix?

Check that I/O pins are not (erroneously) used in more than one place for different functions.

Pin schema option `other_uses: true` will suppress the errors on a pin-by-pin basis, while a `check_pin_use: false` entry in the `esphome:` block will globally disable the check (this is intended for test YAMLs.)

To facilitate implementation across different components, a new function in `pins.py` has been defined to provide a base schema for gpio pins.

Still to be done: update various I/O expander components to make use of this.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#TBA

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [x] RP2040
- [x] BK72xx
- [x] RTL87xx

## Example entry for `config.yaml`:

binary_sensor:
  - platform: gpio
    internal: true
    name: Pin 1_1
    pin:
      pca9554: p_c_a
      other_uses: false
      number: 9
```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-11-06 20:30 UTC, jesserockz commented on esphome/core/config.py
> +            cv.Optional(CONF_CHECK_PIN_USE, default=True): cv.boolean,
I dont like global config options that can allow bad configs as tutorials add them and then everyone copy/pastes it into every config.

2023-11-06 20:44 UTC, jesserockz requested changes

2023-11-06 20:44 UTC, jesserockz commented on esphome/components/esp32/gpio.py
> -            }
Note that esp32 doesnt allow analog in the modes

2023-11-06 20:44 UTC, jesserockz commented on esphome/components/libretiny/gpio.py
> +    validate_gpio_usage,
This uses `add_extra` as there is potential for this to be extended and you cannot extend an `All`

2023-11-06 20:44 UTC, jesserockz commented on esphome/pins.py
> +            cv.Optional(CONF_OTHER_USES): cv.boolean,
Maybe a better name?
```suggestion
            cv.Optional(CONF_ALLOW_OTHER_USES): cv.boolean,
```

2023-11-06 20:44 UTC, jesserockz commented on esphome/pins.py
> +            or config.get(CONF_OTHER_USES) is True
Similar to the ignore strapping warning and potentially the ignore_validation warning, I think that an error should be raised if the pin is only used once but this is set, to stop people putting it everywhere.

2023-11-06 21:14 UTC, clydebarrow commented on esphome/core/config.py
> +            cv.Optional(CONF_CHECK_PIN_USE, default=True): cv.boolean,
Agreed, but the test yamls need a way of supressing this - I added the per-pin suppression for a couple but some have numerous instances where it is needed. Do you have any other ideas to achieve this or should I just bite the bullet and add it to all overloaded pins in the test yamls?

2023-11-28 07:05 UTC, jesserockz commented on esphome/__main__.py
> +        safe_print(output)
"Unrelated" changes should go in their own PR for easier tracing and in case of needing to be reverted etc

2023-11-28 07:34 UTC, jesserockz requested changes
Overall looks good. Please just split the `quiet` stuff into its own PR then this can merge :tada:

2023-11-28 07:41 UTC, clydebarrow commented on esphome/__main__.py
> +        safe_print(output)
Oh, forgot I had that in there - I needed it when cleaning up the test yamls because "esphome config" was the easiest way to find the issues and it insisted on spitting out the whole config on success.

2023-12-04 23:52 UTC, jesserockz approved these changes

2023-12-04 23:56 UTC, merged