Refactor ATM90E32 to reduce blocking time and improve accuracy.
OttoWinter/esphomeyaml pull request #5670
Opened 2023-11-03 22:55 UTC by descipher

# What does this implement/fix?

Simplify code and increase SPI data rate to 2Mhz.
Adds manufactures application guide calibration capability. (no user changes) 

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
No change.

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

2023-11-05 20:40 UTC, jesserockz requested changes

2023-11-05 20:40 UTC, jesserockz commented on esphome/components/atm90e32/atm90e32.cpp
> +float ATM90E32Component::get_setup_priority() const { return setup_priority::BUS; }
This should be `IO` at the earliest as it relies on the spi bus to be setup.
```suggestion
float ATM90E32Component::get_setup_priority() const { return setup_priority::IO; }
```

2023-11-05 20:40 UTC, jesserockz commented on esphome/components/atm90e32/atm90e32.h
> +  }
Can the contents of these be moved to the cpp file please?

2023-11-05 20:40 UTC, jesserockz commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
Fetching the data should only be done once per `update` call.

Perhaps another solution could be to have a state machine {idle, update, publish}. `update()` can set from idle to update, `loop()` can fetch the data in `update` state then change state to `publish` which `loop()` can pick up next time around (~16ms later).

2023-11-05 23:18 UTC, descipher commented on esphome/components/atm90e32/atm90e32.h
> +  }
For sure, what's the threshold for moving em out to the cpp, 3 or more lines?

2023-11-05 23:40 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +float ATM90E32Component::get_setup_priority() const { return setup_priority::BUS; }
Ok, But I think the priority description should change then. It's not clear to me, do we set the priority of the component to a value lower than the interfaces it will use or at them?

Here the description is misleading unless we indicate that we need to be lower than i2c or spi when we depend on a BUS.

e.g.
const float esphome::setup_priority::BUS
For communication buses like i2c/spi

2023-11-05 23:54 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
The objective here is to do a local SPI data fetch into an array store at a resonable frequency. The update overide does the publish from the pre-populated local array. I will look at a state machine to see if thats more effective. May I ask why the concern on this?

2023-11-06 00:11 UTC, jesserockz commented on esphome/components/atm90e32/atm90e32.cpp
> +float ATM90E32Component::get_setup_priority() const { return setup_priority::BUS; }
Lower number = lower priority = setup later

2023-11-06 00:12 UTC, jesserockz commented on esphome/components/atm90e32/atm90e32.cpp
> +float ATM90E32Component::get_setup_priority() const { return setup_priority::BUS; }
If a component is set at the same priority level, it could be setup out of order

2023-11-06 00:14 UTC, jesserockz commented on esphome/components/atm90e32/atm90e32.h
> +  }
To be honest, not sure...haha
But these functions are reading data from the bus, so they definitely don't belong in the header.

2023-11-06 00:15 UTC, jesserockz commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
There is no point in updating local data every 400ms when the update interval could be 60 seconds. Its a waste of resource and cpu time when it is just thrown away.

The local store doesn't need to update any faster than the configured `update_interval`

2023-11-06 02:10 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +float ATM90E32Component::get_setup_priority() const { return setup_priority::BUS; }
Ok, I'm a bit confused by this .. we init the SPI interface in this component so wouldn't this require a higher priority.

e.g. from setup the first thing we call is:
  this->spi_setup(); and there is and option to have multiple instances in the configuration.

2023-11-06 02:22 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +float ATM90E32Component::get_setup_priority() const { return setup_priority::BUS; }
I think I see it now, SPI is a separate component and has it's own priority setting.

2023-11-06 02:56 UTC, jesserockz commented on esphome/components/atm90e32/atm90e32.cpp
> +float ATM90E32Component::get_setup_priority() const { return setup_priority::BUS; }
Yes, the SPI base component needs to do its own periperhal setup before any components try to register themselves with it.

2023-11-06 04:07 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
Fair enough. I don't think I can do it the way you envisioned though, it only works well if the array data is ready to go b4 the update polling event. I can look at preempting but I think the exact polling pit may be unpredicatable. I will measure it and see.

2023-11-06 19:39 UTC, jesserockz commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
Data doesnt have to be ready when `update` is called, it can take however long it needs before its actually published. `update` can be thought of a trigger to start the process to get sensors updated.

2023-11-06 20:04 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
The accuracy suffers by doing that. See: https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/issues/88

2023-11-08 21:46 UTC, CircuitSetup commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
@descipher now that I think about it, performance could suffer with setups that are doing, for example, 24+ current channels at 60 second update intervals. Could the local polling be dependent on the update interval, maybe?

2023-11-09 02:40 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
I don't think its a performance issue at all. It is maximum of 12 SPI channels at 2Mhz reading directly into memory. The processing time calculates as 2us of SPI data transfer processing per polling every 400ms. Which is nothing compared to the API publishing process of 46ms * 12  or 552ms unless you turn serial logging off. However it would be good if you could test that many since I cannot or at least somewhere close to it.

If we do the publishing during the local poll it will have a large delay between channels with 12 of them.

2023-11-14 16:57 UTC, CircuitSetup commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
@descipher okay, that makes sense. I was thinking that storing 24+ current channels in memory every 400ms until the update is called would overrun the buffer, but you obviously have a better understanding of how that works than me. 

@jesserockz what needs to happen to get this pushed through?

2023-11-15 14:16 UTC, danieltwagner commented on esphome/components/atm90e32/atm90e32_reg.h
>  static const uint16_t ATM90E32_REGISTER_APENERGYA = 0x81;  // A Forward Active
seems like all of these A/B/C register names will become unused once you reference them with base + offset, mind removing them?

2023-11-15 14:24 UTC, danieltwagner commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
Could you expand on why reading these registers in `loop()` is better than reading them in `update()`? It's not obvious to me. My impression is that the issue was that reading these registers at 200 kHz might mean the value updates in between reads and so reading, say, voltage across different phases might be out of sync if new data arrives between reads.

The linked issue has a lengthy conversation but I take it this is the relevant insight?
> What does provide value is the quick polling local memory retrieval which have no additional delays.

Where the code runs (`update()` or `loop()`) shouldn't make a difference on how quickly these values are read. What this change would accomplish is minimizing time waiting for the SPI reads to finish before exiting `update()`, but otherwise it should be identical. Am I missing something?

2023-11-15 18:57 UTC, descipher commented on esphome/components/atm90e32/atm90e32_reg.h
>  static const uint16_t ATM90E32_REGISTER_APENERGYA = 0x81;  // A Forward Active
True, but I have not referenced everyone of them so only instances where I added the Base value can be cleaned and not all of them have a base. There is value as documentation allowing them to remain.

2023-11-15 19:25 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
update() triggers only once and holds up other callbacks (single thread) while it processes. If we publish direct chip reads from update we will miss the single PIT physical chip read sample and thus the values will dither from channel to channel significantly. A phase publishing call takes too much time even at 2Mhz. We are not waiting on the read we are waiting on the publishing code to complete before the next direct read. This crosses the 220ms chip read frequency which results in value changes on the same phase over two diffent SPI ports. loop() is in a different scheduling context and is not a thread blocking contributor. @jesserockz and I spoke on this last night we are going to test a bool flag comming in on update() and then process everything out of loop() based on the flag state to see if that's a better solution than the 400ms local work interval. As long as that does not result in the 0 phase value read problem during an atm90e32 chip and esp boot cycle we should be in good shape.

2023-11-16 16:29 UTC, danieltwagner commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
Thanks for the explanation, that makes sense. Could you read all values first (essentially the code that's currently in `loop()`) and then publish (the code that's currently in `update()`) after you read the values? That would seem conceptually simpler than a (binary) state machine where business logic is spread across two functions.

2023-11-16 17:44 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
That approach was tried using a preempt strategy, it fails. The scheduler is random so there is no predictable time slot to prempt the update() interval. That also results in 0 value reads on restart and thats a show stopper.

2023-11-16 18:17 UTC, danieltwagner commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
I'm not sure I'm following. Just to be clear, what I was suggesting was something like this:
```
void ATM90E32Component::update() {
  for (uint8_t phase = 0; phase < 3; phase++) {
    if (this->phase_[phase].voltage_sensor_ != nullptr) {
      this->phase_[phase].voltage_ = this->get_phase_voltage_(phase);
    }
  }
  
  [... read all other values ...]
  
  for (uint8_t phase = 0; phase < 3; phase++) {
    if (this->phase_[phase].voltage_sensor_ != nullptr) {
      this->phase_[phase].voltage_sensor_->publish_state(this->get_local_phase_voltage_(phase));
    }
  }
  
  [... publish all other values ...]
}
```

Why would this result in 0 value reads and where does the need to preempt anything come from?

2023-11-16 18:32 UTC, danieltwagner commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
Is the concern that the execution of `update()` might get interrupted in order to do some other work? (Is it an RTOS Task?) If so, presumably the same might happen for the component's `loop()`?

2023-11-16 19:45 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
Yep, data PIT would be good however now we have the thread blocking problem, it will be well over 50ms with just 2 phases and with 12 its at least 6 * 50ms.

2023-11-16 19:53 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
If we do it with a flag we no longer block because the polling interval only waits for the flag to be updated, it's even better than the original effort I came up with provided that I can solve the 0 value initial read problem which should be resolvable.

2023-11-17 03:14 UTC, Extrapilot1 commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
Max data rate is 1.1Mhz (900khz for calibration), so a 2Mhz data rate is likely a problem

There is a related concern- as regards the max window size on the peak and sag detector registers. They rollover at a max of 256ms, where the value for that window is available only during the following window. If you want to be able to actually monitor peaks, which tend to be sub-50ms events, there is a need to poll those registers at a high rate, where others can comfortably be at 60 seconds, or minutes, depending on which. Ideally, this could be configured per entity vs per chip, so that the SPI bus doesn’t become limiting, and the CPU isnt dealing with a bunch of data no one needs/wants.

2023-11-17 14:55 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
Thanks for catching that, will adjust the rate to 1Mhz. We cannot reach full throttle therefore the hardware interval of 900khz would not be reached under the current safe delay read constraint.

2023-11-18 00:41 UTC, descipher commented on esphome/components/atm90e32/atm90e32.cpp
> +    last_periodic_millis = current_millis;
@jesserockz bool flag method works well on my local testing rigs, thank-you. By setting it to true on init it resolves the 0 value plublishing issue on startup. Just need some additional users to validate the change.

2023-12-14 13:49 UTC, CircuitSetup approved these changes
looks good!

2023-12-15 03:36 UTC, descipher commented
Adding 3 additional capabilities of the ATM90E32 chip, phase angle,  harmonic power and peak current. Docs to follow, will post the completion event with PR details in the next few days.

2024-01-18 14:23 UTC, CircuitSetup commented
@descipher thanks for all your hard work with this! 

@jesserockz does anything else need to change with this for it to be merged?

2024-01-18 14:30 UTC, descipher commented
> @descipher thanks for all your hard work with this!
> 
> @jesserockz does anything else need to change with this for it to be merged?

I will add the docs shortly lots going on at the moment, this part is good to go and can be committed with or with the added docs for the features. There will also be a follow on PR part which deals with selectable higher polling data functions of the advanced peak current and other data output.

2024-01-25 16:05 UTC, descipher commented
@jesserockz This is ready for a final QA, there is more work coming to address a specific need to poll peak_current ate a higher rate the the interval. When I have time I will make it an option via a number comp with a publish timeout so it does not bloat an upstream HA DB with excess data.

2024-03-10 23:47 UTC, jesserockz submitted a review, later dismissed

2024-03-11 04:23 UTC, jesserockz commented on esphome/components/atm90e32/atm90e32.h
> +  bool peak_current_signed_{true};
This initialised value should match the default in config, otherwise its kinda confusing.

2024-03-11 05:14 UTC, descipher commented on esphome/components/atm90e32/atm90e32.h
> +  bool peak_current_signed_{true};
Corrected.

2024-03-11 18:18 UTC, jesserockz approved these changes

2024-03-11 18:23 UTC, merged