Add changes to support enhanced features: ready call back chime call …
OttoWinter/esphomeyaml pull request #5671
Opened 2023-11-03 23:18 UTC by hwstar

# What does this implement/fix?
This adds some needed features to the alarm control panel. See feature requests: 2307, 2364

1. Adds a zone type identifier for each zone one of: delayed, instant, or interior follower.
2. Adds a chime setting for all defined zones.
3. Adds callbacks for all zones ready and chime.
4. Adds all zones ready method.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```
#
# esphome
#

esphome:
  name: 16-zone-sensor-board
  platform: ESP32
  board: esp-wrover-kit
  name_add_mac_suffix: true # Adds a 6 digit MAC suffix to the name defined above. Can be used to distinguish between multiple sensor panels.
  project:
    name: esphome.project-template
    version: "1.0"
  min_version: "2023.8.1"
  on_boot: # Important - need to enable the UART rx pin
    then:
      # Handle cbus uart_rx strapping pin
      - output.turn_on: rx_ena
      - delay: 1s
      # Send status update to Kpa1 as Alarm Panel does not initially send its state.
      - lambda: |-
          // Alarm panel returns an enum
          esphome::alarm_control_panel::AlarmControlPanelState status = id(acp1)->get_state();
          // Transmit state to keypads on power up
          id(cbus).update_alarm_state((uint8_t) status);
          
      - delay: 30s # Test only - dump config
      
      - lambda: |-
          id(acp1).dump_config();
          id(cbus).get_keypad_count();
          id(cbus).get_keypad_info();
      
#
# Ethernet
#

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

external_components:
  - source:
      type: local
      path: external_components
    components: ["kpa1", "alarm_control_panel", "template"] 
  

alarm_control_panel:
  - platform: template
    name: Alarm Panel # You will see this name as alarm_panel.Alarm_Panel in HomeAssistant
    id: acp1
    codes:
      - "1234"
    requires_code_to_arm: true
    arming_away_time: 30s
    arming_home_time: 5s
    pending_time: 45s
    trigger_time: 1min
    restore_mode: RESTORE_DEFAULT_DISARMED # Fail Secure
    
    binary_sensors:
      - input: zone1  # Label your zones here as comments
        sensor_type: delayed
        chime: true
      - input: zone2  # 
        chime: true
        sensor_type: instant
      - input: zone3  # 
        sensor_type: interior_follower
      - input: zone4  #
      - input: zone5  #
      - input: zone6  # 
      - input: zone7  # 
      - input: zone8  # 
      - input: zone9  # 
      - input: zone10 # 
      - input: zone11 #
      - input: zone12 # 
      - input: zone13 # 
      - input: zone14 # 
      - input: zone15 # 
      - input: zone16 #
    on_state:
      then: # Add things to do on state changes here.
        - lambda: !lambda |-
            id(cbus)->update_alarm_state(id(acp1)->get_state()); // Send state change to Kpa1 via cbus
            ESP_LOGI("AlarmPanel", "State change %s", alarm_control_panel_state_to_string(id(acp1)->get_state()));
        
    on_triggered:
      then: # Add things to do when triggered here. e.g. sound siren, send a message etc.
        - lambda: !lambda |-
            ESP_LOGI("AlarmPanel", "Alarm Triggered!");
            id(siren).turn_on();
            
    on_cleared:
      then: # Add things to do when the alarm is canceled here.
        - lambda: !lambda |-
            ESP_LOGI("AlarmPanel", "Alarm Cleared!");
            id(siren).turn_off();
            
    on_chime:
      then: # Add things to do when a chime zone is opened.
        - lambda: !lambda |-
            ESP_LOGI("AlarmPanel", "Chime Yaml");
            id(cbus).send_entry_chime();
            
    on_ready:
      then: # Ready state change
        - lambda: !lambda |-
            ESP_LOGI("AlarmPanel", "Ready State Change");
            bool ready = id(acp1).get_all_sensors_ready();
            // Update keypads
            id(cbus).update_system_ready(ready);
            

#
# webserver
#

web_server:
  port: 80
# auth:
#    username: admin
#    password: !secret web_password

#
# logger
#

logger:
  level: INFO

#
# api
#

api:
  reboot_timeout: 24h
#
#  Uncomment the lines below to enable encrypted communication
#  between homeassistant and the sensor panel.
#  You'll need to change your encryption key in secrets.yaml,
#  and give homeassistant the encryption key.
#
#  encryption:
#          key: !secret api_key

#
# ota
#

ota:
  password: !secret esphome_ota_password

#
# Dashboard import
#

dashboard_import:
  package_import_url: github://hwstar/8-zone-sensor-panel/16-zone-sensor.yaml@main

#
# I2C bus definition
#

i2c:
  sda: GPIO33
  scl: GPIO14
  id: bus_a
  frequency: 300kHz # Limited by bus capacitance on the board
  
  
pca9554:
  - id: pca9554_zones_1_8
    address: 0x38

    
  - id: pca9554_zones_9_16
    address: 0x39
  

interval:
  - interval: 3sec
    then:
      - switch.turn_on: heartbeat_led
      - delay: 100ms
      - switch.turn_off: heartbeat_led
      - delay: 100ms
      - switch.turn_on: heartbeat_led
      - delay: 100ms
      - switch.turn_off: heartbeat_led

  
sensor:
  # TMP102 sensor on board 
  # Commented out 8/4/23 due to 50mS delay in component causing warnings to be generated.
#  - platform: tmp102
#    name: "Board Temperature"
#    update_interval: 1s
#    address: 0x48
#    id: board_temp

  # ADC inputs
  - platform: adc
    id: vbatt_monitor
    name: Vbatt_Monitor
    attenuation: 11dB
    accuracy_decimals: 2
    update_interval: 10s
    pin: GPIO39
    filters:
      multiply: 5.3
    
  - platform: adc
    id: aux_monitor
    name: Aux_Monitor
    attenuation: 11dB
    accuracy_decimals: 2
    update_interval: 10s
    pin: GPIO36
    filters:
      multiply: 5.3
    
  - platform: adc
    id: siren_monitor
    name: Siren_Monitor
    attenuation: 11dB
    accuracy_decimals: 2
    update_interval: 10s
    pin: GPIO35
    filters:
      multiply: 5.3

binary_sensor:
  #
  # Digital Inputs
  #
  
  # AC failure
  - platform: gpio
    id: ac_fail
    name: AC-Fail
    pin:
      number: GPIO32
      mode:
        input: true
      inverted: false      
        
  # Zones 1-8
  
  - platform: gpio
    name: Zone_8
    id: zone8
    pin:
      pca9554: pca9554_zones_1_8
      number: 7
      mode:
        input: true
      inverted: true # Inverted because the alarm component wants to see a low when the zone is normal

  - platform: gpio
    name: Zone_7
    id: zone7
    pin:
      pca9554: pca9554_zones_1_8
      number: 6
      mode:
        input: true
      inverted: true  
 
     
  - platform: gpio
    name: Zone_6
    id: zone6
    pin:
      pca9554: pca9554_zones_1_8
      number: 5
      mode:
        input: true
      inverted: true
 
      
  - platform: gpio
    name: Zone_5
    id: zone5
    pin:
      pca9554: pca9554_zones_1_8
      number: 4
      mode:
        input: true
      inverted: true
 

  - platform: gpio
    name: Zone_4
    id: zone4
    pin:
      pca9554: pca9554_zones_1_8
      number: 3
      mode:
        input: true
      inverted: true
 
  - platform: gpio
    name: Zone_3
    id: zone3
    pin:
      pca9554: pca9554_zones_1_8
      number: 2
      mode:
        input: true
      inverted: true
 
  - platform: gpio
    name: Zone_2
    id: zone2
    pin:
      pca9554: pca9554_zones_1_8
      number: 1
      mode:
        input: true
      inverted: true
 
  - platform: gpio 
    name: Zone_1
    id: zone [...]

2023-11-07 21:20 UTC, grahambrown11 commented
@hwstar can you please explain what `interior_follower` is for the sensor type.
I understand the need for instant vs delayed trigger so I would opt for a `trigger_instant: true` option instead.
If there is a need for the 3 types then I'd rename the config item to `trigger_mode`, not `sensor_type` (I find that name confusing as a sensor type in an alarm is a PIR, read switch, glass break, etc...)

I was going to look into the ready state, but I wanted to make sure that HA & ESPHome have feature parity, so I was 1st going to add that in HA, I've unfortunately not had much time to work on fun stuff 😄
 
Personally I'm not a fan of chimes 😵, but I understand others are, this didn't need to be added to the alarm_panel code though as it could be acheived by adding a trigger to the binary sensor.

2023-11-08 00:09 UTC, hwstar commented
Hi Gordon. Interior follower is useful in situations where you have a keypad in a hallway which is protected by a passive infrared sensor. You want the sensor to act as a delayed entry sensor in this case as instant would cause nuisance trips. Likewise, if the passive infrared zone was set to delay, then the protection could be compromised if someone gets into the building via an unprotected entrance (such as breaking a window in a room without a passive infared, glass break or other sensor).   A passive infrared zone set to interior follower will sound an instant alarm in this case since no delayed entry zone was triggered prior to the passive infrared zone being tripped. I chose a zone type over binary settings because there may be more than 3 zone types implemented in the future. (Think fire and 24 hour zones). Using binary flags seemed more logical as the zone types are typically mutually exclusive.

2023-11-09 04:23 UTC, grahambrown11 requested changes

2023-11-09 04:23 UTC, grahambrown11 commented on esphome/components/alarm_control_panel/__init__.py
>  @automation.register_condition(
I would add a `is_ready` condition

2023-11-09 04:23 UTC, grahambrown11 commented on esphome/components/template/alarm_control_panel/template_alarm_control_panel.cpp
> +      default:
the default should be `delayed`

2023-11-09 05:33 UTC, grahambrown11 commented
👍🏻 Thanks for the explanation, I'd prefer the name `delayed_follower` then and please then update the documentation PR so that its clear what the intention of that setting is, in fact not just that one but all the "modes" need explanation in the docs 😄

2023-11-09 19:54 UTC, hwstar commented on esphome/components/alarm_control_panel/__init__.py
>  @automation.register_condition(
Added. Please review.

2023-11-09 19:54 UTC, hwstar commented on esphome/components/template/alarm_control_panel/template_alarm_control_panel.cpp
> +      default:
Added. Please review.

2023-11-09 19:55 UTC, hwstar commented
All suggested changes are incorporated in the code. Will update the docs soon.

2023-11-18 07:43 UTC, grahambrown11 approved these changes

2023-12-19 04:25 UTC, jesserockz requested changes

2023-12-19 04:25 UTC, jesserockz commented on esphome/components/template/alarm_control_panel/__init__.py
> +        if sensor["trigger_mode"] not in SensorTypes:
Please make sure to use the CONF_ constants

2023-12-19 04:25 UTC, jesserockz commented on esphome/components/template/alarm_control_panel/template_alarm_control_panel.cpp
> +        sensor_type = "delayed";
```suggestion
      case 1:
        sensor_type = "instant";
        break;
      case 2:
        sensor_type = "delayed_follower";
        break;
      case 0:
      default:
        sensor_type = "delayed";
        break;
```

2023-12-19 04:25 UTC, jesserockz commented on esphome/components/template/alarm_control_panel/template_alarm_control_panel.cpp
> +                              : ACP_STATE_TRIGGERED);
Please change this from a ternary to a regular if/else as it has a "complex" condition and ends up spanning multiple lines anyway

2023-12-19 04:25 UTC, jesserockz commented on esphome/components/template/alarm_control_panel/template_alarm_control_panel.h
> +  uint16_t type;
Please use the enum here correctly
```suggestion
  AlarmSensorType type;
```

2023-12-19 04:25 UTC, jesserockz commented on esphome/components/template/alarm_control_panel/template_alarm_control_panel.cpp
> +        sensor_type = "delayed";
Also with the enum suggestion, this should use the enums as the case values instead of "magic numbers" =)

2023-12-19 22:48 UTC, hwstar commented on esphome/components/template/alarm_control_panel/template_alarm_control_panel.h
> +  uint16_t type;
All suggested changes made.

2023-12-20 05:27 UTC, jesserockz submitted a review, later dismissed

2023-12-20 17:53 UTC, hwstar commented
The change made to add the ALARM_SENSOR_TYPES dict has changed DELAYED_FOLLOWER back to INTERIOR_FOLLOWER on line 62 in __init__.py and at line 58, and 154 in template_alarm_control_panel.cpp. 

Which is it going to be: DELAYED_FOLLOWER or INTERIOR_FOLLOWER? 

Graham brown requested I change the from INTERIOR_FOLLOWER to DELAYED_FOLLOWER so I made this change a while back.

2023-12-20 22:26 UTC, jesserockz commented
Oops, my bad there. I was following the enum though, not the SensorTypes list as they should match to not be confusing =)

2023-12-21 00:38 UTC, jesserockz approved these changes

2023-12-21 05:10 UTC, merged