Nextion more reliable Upload TFT (arduino)
OttoWinter/esphomeyaml pull request #5683
Opened 2023-11-06 21:59 UTC by edwardtfn

# What does this implement/fix?

The upload TFT process is the most painful part of this component in ESPHome. As it fails many times and is very hard to troubleshoot.
The idea of this change is to make it a bit more reliable by ensuring a bit more free heap, by reducing the chunk size when needed.
It also adds a couple of delays to give a bit more time to the different components involved (http and uart).
Smaller chunks shouldn't be really a problem, but can ensure a more stable transfer by itself.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**
- Possibly fixes https://github.com/esphome/issues/issues/5029
- Probably fixes https://github.com/esphome/issues/issues/2423 or at least some of the many cases reported there

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
N/A

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-11-07 03:40 UTC, kbx81 commented on esphome/components/nextion/nextion.cpp
> +    delay(2);
Is this and line `865` the delays you mention in the PR description? If so, these are not asynchronous delays and they don't give time to other components -- they just block until the delay completes (which can do more harm than good). If the hardware itself doesn't require a specific, fixed delay here, it's best to omit them.

2023-11-07 03:41 UTC, kbx81 commented on esphome/components/nextion/nextion_upload.cpp
> +      delay(500);  // NOLINT
Also as above -- this is a 0.5 second delay, which is wayyyy longer than we want to block for (unless specifically required by hardware).

2023-11-07 04:54 UTC, edwardtfn commented on esphome/components/nextion/nextion_upload.cpp
> +      delay(500);  // NOLINT
I'm not adding a delay, as this is the same delay as in the original code, I've just added the delay when going to this conditional as this was bypassing the delay, which we don't want.
Again, I can play with other values here, but I would prefer to not touch on this as my tests shown adding some of these delays helped with reliability.
But I was all the time playing with the existing code. Maybe I should do just like in the idf version rewrite this completely to make it simpler, but this will probably require more time and I would prefer to do it later.

2023-11-07 05:23 UTC, kbx81 commented on esphome/components/nextion/nextion_upload.cpp
> +      delay(500);  // NOLINT
Cool, no problem. 😄

2023-11-08 04:49 UTC, edwardtfn commented
Should I close this and create a new one to resolve it's conflicts?

2023-11-08 09:09 UTC, kbx81 commented
> Should I close this and create a new one to resolve it's conflicts?

No need, you can rebase your branch locally to pick up the changes, resolve any conflicts and then push the result back up here.

2023-11-08 11:55 UTC, edwardtfn commented
This was by mistake with a rebase. 😞

2023-11-28 05:01 UTC, kbx81 requested changes
I've tested this with my displays, seems to be working fine here!
Just a couple little nits, otherwise LGTM

2023-11-28 05:01 UTC, kbx81 commented on esphome/components/nextion/nextion_upload_arduino.cpp
> +    ESP_LOGD(TAG, "Uploaded %0.2f %%, remaining %d bytes",
```suggestion
    ESP_LOGD(TAG, "Uploaded %0.2f %%; %d bytes remaining",
```

2023-11-28 05:01 UTC, kbx81 commented on esphome/components/nextion/nextion_upload_arduino.cpp
> +  ESP_LOGD(TAG, "url: %s", this->tft_url_.c_str());
```suggestion
  ESP_LOGD(TAG, "URL: %s", this->tft_url_.c_str());
```

2023-11-28 05:11 UTC, kbx81 approved these changes

2023-11-28 05:25 UTC, merged