Addressable color gradient effect
OttoWinter/esphomeyaml pull request #5689
Opened 2023-11-07 03:16 UTC by lifeisafractal

# What does this implement/fix?

This PR adds a new option to the addressable color wipe effect to enable gradient transitions between colors.

This also address the code/doc dependency of `num_leds` being required/options respectively. The approach taken is to honor the docs and allow it to be optional (see docs PR for details). The only catch here is that I couldn't figure out how to get voluptuous to statefully reference previous entries in a list as a default value, so my approach was to tackle this during code generation which I know isn't the preferred method. I'm open to hearing suggestions on how to handle this better.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3339

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
light:
  - platform: neopixelbus
    type: RGB
    pin: D2
    num_leds: 50
    method: BIT_BANG
    variant: ws2811
    id: lights
    name: "Holiday Lights"
    effects:
      - addressable_color_wipe:
          name: thanksgiving
          colors:
            - # yellow
              red: 100%
              green: 91%
              blue: 0%
              num_leds: 10
            - # red
              red: 100%
              green: 6%
              blue: 18%
            - # orange
              red: 100%
              green: 63%
              blue: 0%
          add_led_interval: 30ms
          reverse: false
          gradient: true
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-15 01:49 UTC, lifeisafractal commented
It's been a bit with no review. Do I need to do another step I missed? Happy to help out to get this feature in; I think it's really neat!

2023-12-15 08:57 UTC, kroimon requested changes

2023-12-15 08:57 UTC, kroimon commented on esphome/components/light/effects.py
> +                cv.Optional(CONF_GRADIENT): cv.boolean,
Please add default values for the optional settings here for use during validation.

2023-12-15 08:57 UTC, kroimon commented on esphome/components/light/effects.py
> +    gradient = False
Do not add default values during code generation.

2023-12-15 08:57 UTC, kroimon commented on esphome/components/light/effects.py
> +                ("gradient", gradient),
After adding defaults to the validation, remove the `num_leds` and `gradient` variables above and just use:
```suggestion
                ("num_leds", config[CONF_NUM_LEDS]),
                ("gradient", config[CONF_GRADIENT]),
```

2023-12-15 08:57 UTC, kroimon commented on esphome/components/light/addressable_light_effect.h
> +  bool gradient_{};
Unused?

2023-12-19 17:44 UTC, lifeisafractal commented on esphome/components/light/effects.py
> +                cv.Optional(CONF_GRADIENT): cv.boolean,
done.

2023-12-19 17:44 UTC, lifeisafractal commented on esphome/components/light/effects.py
> +    gradient = False
fixed.

2023-12-19 17:44 UTC, lifeisafractal commented on esphome/components/light/effects.py
> +                ("gradient", gradient),
fixed.

2023-12-19 17:45 UTC, lifeisafractal commented on esphome/components/light/addressable_light_effect.h
> +  bool gradient_{};
correct, left from earlier implementation when trying things out. Removed.

2023-12-19 17:45 UTC, lifeisafractal commented
All PR feedback addressed. I went back to the approach of defaults in the validator as is the custom here. The documentation PR has been updated to reflect this as well.

2023-12-20 05:23 UTC, kroimon approved these changes

2023-12-20 06:01 UTC, jesserockz approved these changes

2023-12-21 00:08 UTC, merged