Actions to enable and disable WireGuard connection
OttoWinter/esphomeyaml pull request #5690
Opened 2023-11-07 06:08 UTC by droscy

# What does this implement/fix?

This PR add actions to enable and disable the WireGuard component and conditions to check if the vpn link is enabled and active.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** this PR should also address a feature requested here https://github.com/esphome/feature-requests/issues/1444#issuecomment-1621489477 by @snechiporenko

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# configure wireguard as usual
wireguard:
  [...]

button:                                                                                                                                                                                                                                       
  - platform: template                                                                                                                                                                                                                        
    name: 'Toggle WireGuard'                                                                                                                                                                                                                  
    entity_category: config                                                                                                                                                                                                                   
    on_press:                                                                                                                                                                                                                                 
      - if:                                                                                                                                                                                                                                   
          condition: wireguard.enabled                                                                                                                                                                                                        
          then:                                                                                                                                                                                                                               
            - wireguard.disable:                                                                                                                                                                                                              
          else:                                                                                                                                                                                                                               
            - wireguard.enable:                                                                                                                                                                                                               
                                                                                                                                                                                                                                              
  - platform: template                                                                                                                                                                                                                        
    name: 'Log WireGuard status'                                                                                                                                                                                                              
    entity_category: config                                                                                                                                                                                                                   
    on_press:                                                                                                                                                                                                                                 
      - if:                                                                                                                                                                                                                                   
          condition: wireguard.peer_online                                                                                                                                                                                                    
          then:                                                                                                                                                                                                                               
            - logger.log: 'wireguard remote peer is online'                                                                                                                                                                                   
          else:                                                                                                                                                                                                                               
            - logger.log: 'wireguard remote peer is offline'
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-11-07 06:20 UTC, jesserockz requested changes

2023-11-07 06:20 UTC, jesserockz commented on esphome/components/wireguard/wireguard.cpp
> +  this->publish_enabled_state();
Can you do this in a further loop outside of the action itself?

See https://github.com/esphome/esphome/pull/5616#pullrequestreview-1714120196 for details on how I changed for ble (the same needs to be done for wifi too)

2023-11-07 08:04 UTC, droscy commented on esphome/components/wireguard/wireguard.cpp
> +  this->publish_enabled_state();
Can I simply replace `this->stop_connection_();` with the following?

```c++
this->defer(std::bind(&Wireguard::stop_connection_, this));
```

2023-11-07 17:59 UTC, jesserockz commented on esphome/components/wireguard/wireguard.cpp
> +  this->publish_enabled_state();
If it works correctly, yeah probably

2023-11-29 16:47 UTC, droscy commented on esphome/components/wireguard/wireguard.cpp
> +  this->publish_enabled_state();
I've just pushed the requested change.

2023-12-19 03:33 UTC, jesserockz commented on esphome/components/wireguard/wireguard.cpp
> +Wireguard *global_wireguard;  // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
Is this really needed?

2023-12-19 03:39 UTC, jesserockz requested changes

2023-12-19 03:39 UTC, jesserockz commented on esphome/components/wireguard/wireguard.cpp
> +Wireguard *global_wireguard;  // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
But in saying that, we try to only add globals like this when there are cross component calls, which there are not here. Wi-Fi and BLE have it because there is other code that calls them. 
For the actions inside WireGuard, the config schema should use GenerateID to pass a reference of the wireguard component to the actions and add `Parented<WireGuard>` so they can just use `this->parent_`

2024-01-09 17:25 UTC, droscy commented on esphome/components/wireguard/wireguard.cpp
> +Wireguard *global_wireguard;  // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
Ok, I've switched from global pointer to local parent.

2024-01-11 05:08 UTC, jesserockz approved these changes

2024-01-11 05:09 UTC, merged