Add support of Honeywell HumidIcon (I2C HIH series) Temperature & Humidity sensor
OttoWinter/esphomeyaml pull request #5730
Opened 2023-11-11 11:29 UTC by Benichou34

# What does this implement/fix?
Add support of Honeywell HumidIcon (I2C HIH series) Temperature & Humidity sensor

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature:** [esphome/feature-requests/issues/1799]

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation:** esphome/esphome-docs#3357

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
```yaml
sensor:
  - platform: honeywell_hih_i2c
    update_interval: 60s
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-22 06:29 UTC, jesserockz requested changes

2023-12-22 06:29 UTC, jesserockz commented on esphome/components/honeywell_hih_i2c/honeywell_hih.cpp
> +static const uint8_t RESQUEST_CMD[1] = {0x00};  // Measurement Request Format
```suggestion
static const uint8_t REQUEST_CMD[1] = {0x00};  // Measurement Request Format
```

2023-12-22 06:29 UTC, jesserockz commented on esphome/components/honeywell_hih_i2c/honeywell_hih.cpp
> +static const char *const TAG = "honeywell_hih";
```suggestion
static const char *const TAG = "honeywell_hih.i2c";
```

2023-12-22 06:29 UTC, jesserockz commented on esphome/components/honeywell_hih_i2c/honeywell_hih.h
> +class HONEYWELLHIComponent : public PollingComponent, public i2c::I2CDevice {
```suggestion
class HoneywellHIComponent : public PollingComponent, public i2c::I2CDevice {
```

2023-12-22 06:29 UTC, jesserockz commented on esphome/components/honeywell_hih_i2c/honeywell_hih.h
> +  void set_humidity_sensor(sensor::Sensor *humidity_sensor) { humidity_sensor_ = humidity_sensor; }
```suggestion
  void set_temperature_sensor(sensor::Sensor *temperature_sensor) { this->temperature_sensor_ = temperature_sensor; }
  void set_humidity_sensor(sensor::Sensor *humidity_sensor) { this->humidity_sensor_ = humidity_sensor; }
```

2023-12-22 06:29 UTC, jesserockz commented on esphome/components/honeywell_hih_i2c/honeywell_hih.cpp
> +  this->mark_failed();
Should this mark as failed, or just set a warning/error status which can be cleared if it succeeds in a future update? Same in the other places that call `mark_failed`

2023-12-22 06:29 UTC, jesserockz commented on esphome/components/honeywell_hih_i2c/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_TEMPERATURE])
```suggestion
    if temperature_config := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_config)
```

2023-12-22 06:29 UTC, jesserockz commented on esphome/components/honeywell_hih_i2c/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_HUMIDITY])
```suggestion
    if humidity_config := config.get(CONF_HUMIDITY):
        sens = await sensor.new_sensor(humidity_config)
```

2023-12-26 18:04 UTC, Benichou34 commented on esphome/components/honeywell_hih_i2c/honeywell_hih.cpp
> +  this->mark_failed();
I think that if there is an I2c communication error or a timeout error, the device must be mark as failed.

2024-01-18 00:47 UTC, jesserockz approved these changes

2024-01-18 00:56 UTC, merged