[Deep Sleep] Support wake from multiple pins (ESP32C3)
OttoWinter/esphomeyaml pull request #5739
Opened 2023-11-12 23:01 UTC by Xmister

# What does this implement/fix?

Changes the `wakeup_pin:` structure to accept multiple pins, each with its wakeup_pin_mode on supported devices.

Right now only ESP32C3 is supported, but I plan on adding deep sleep support for bk72xx which also supports it.

The PR also consolidates unnecessarily duplicated codes on deep sleep setup.

The  changes are breaking, as in the `wakeup_pin:` yaml definitions will need to be updated by users.

Will update documentation once the PR is accepted.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
deep_sleep:
  run_duration: 10s
  wakeup_pin:
    - pin: 3
    - pin: 4
      wakeup_pin_mode: INVERT_WAKEUP
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-11-13 18:04 UTC, jesserockz reviewed
I'm not sure it makes sense to break the config for everyone when only people using C3 that want to use multiple pins get any gains from this.

2023-11-14 16:50 UTC, Xmister commented
@jesserockz Yeah, you're right. Updated the code to be backwards compatible with existing definitions.

2023-11-15 00:21 UTC, jesserockz requested changes

2023-11-15 00:21 UTC, jesserockz commented on esphome/components/deep_sleep/__init__.py
> +                    )
Validations cannot be done in `to_code` they need to be added in validators on the schema itself.

2023-11-15 20:09 UTC, Xmister commented on esphome/components/deep_sleep/__init__.py
> +    value = pins.internal_gpio_input_pin_schema(value)
This had to be moved here from the definitions with this check, otherwise the validator considered each `- pin` item as a list itself.

2023-11-15 20:11 UTC, Xmister commented
@jesserockz Updated validators. If you are fine with the current code, I'll do another round of testing each combination on ESP32 and ESP32C3.

2023-11-20 00:02 UTC, Xmister commented
@jesserockz Updated the validators to be a bit cleaner, also added a bunch of pytests. Please let me know if there is anything else you would like to see.

2023-11-27 20:36 UTC, Xmister commented
@jesserockz Can you please take a look? I'd like to follow this up with deep sleep support for bk72xx, which I think many people using them would like to see.

2023-11-27 20:53 UTC, jesserockz requested changes

2023-11-27 20:53 UTC, jesserockz commented on esphome/components/deep_sleep/__init__.py
> +WAKEUP_SINGLEPIN_SCHEMA = cv.All(pins.internal_gpio_input_pin_schema)
`cv.All` is not needed when there is only one validation
```suggestion
WAKEUP_SINGLEPIN_SCHEMA = pins.internal_gpio_input_pin_schema
```

2023-11-27 20:53 UTC, jesserockz commented on esphome/components/deep_sleep/__init__.py
> +        ),
Same here
```suggestion
        cv.Optional(CONF_WAKEUP_PIN_MODE): (
            cv.enum(WAKEUP_PIN_MODES, upper=True)
        ),
```

2023-11-27 20:53 UTC, jesserockz commented on tests/test2.yaml
> -  wakeup_pin_mode: INVERT_WAKEUP
We need to keep these in a test yaml file to ensure we are not breaking for existing users

2023-11-27 20:53 UTC, jesserockz commented on esphome/components/deep_sleep/deep_sleep_component.h
> +  bool prepare_pin_(esphome::InternalGPIOPin * /*pin*/, WakeupPinMode /*pin_mode*/);
To keep it simpler, we just give the args their names inline
```suggestion
  bool prepare_pin_(esphome::InternalGPIOPin * pin, WakeupPinMode pin_mode);
```

2023-11-27 20:53 UTC, jesserockz commented on esphome/components/deep_sleep/__init__.py
> +    if CORE.target_platform in (PLATFORM_ESP32):
A little simpler =)
```suggestion
    if CORE.is_esp32:
```

2023-11-27 20:55 UTC, Xmister commented on tests/test2.yaml
> -  wakeup_pin_mode: INVERT_WAKEUP
@jesserockz test1.yaml has it

2023-12-10 00:18 UTC, Xmister commented
@jesserockz Could you take another look please?

2023-12-16 19:28 UTC, voed commented on esphome/components/deep_sleep/__init__.py
> +            raise cv.Invalid("ESP32-C3 does not support wakeup from ext1")
Isn't this messages should be swapped? 🤔

2023-12-16 20:55 UTC, Xmister commented on esphome/components/deep_sleep/__init__.py
> +            raise cv.Invalid("ESP32-C3 does not support wakeup from ext1")
You are right. Although this is not new code, I'll fix it.

2023-12-19 03:23 UTC, jesserockz requested changes

2023-12-19 03:23 UTC, jesserockz commented on esphome/components/deep_sleep/__init__.py
> +            wakeup_pin_mode_parent = item if CONF_PIN in item else config
See how `wifi` "moves" the ssid and password into the `networks` list via a custom validator. I think this code should be doing the same here to simplify the `to_code` function

2024-01-02 21:14 UTC, Xmister commented
@jesserockz I made the suggested changes, can you take a look please?

2024-01-10 22:42 UTC, Xmister commented
@jesserockz Just a reminder...whenever you have some time to review.

2024-01-20 20:52 UTC, Xmister commented
@jesserockz Hi, Could you take look a please? It's been a few weeks already...

2024-01-27 21:44 UTC, Xmister commented
@jesserockz Here goes my weekly reminder :)

2024-02-04 14:26 UTC, Xmister commented
@jesserockz Hi! Can we get this sorted? I think I've addressed everything, and it's been a while now...

2024-02-08 23:15 UTC, Xmister commented
@jesserockz :smiling_face_with_tear:

2024-03-02 00:06 UTC, Xmister commented
@jesserockz Please review when you got a chance

2025-10-28 19:04 UTC, swoboda1337 requested changes
Hi, there are conflicts, those need to be resolved before this can be reviewed. Thanks

2026-03-14 00:52 UTC, closed without merging