SCD30 support pressure compensation updates
OttoWinter/esphomeyaml pull request #5757
Opened 2023-11-15 00:14 UTC by schiermi

# What does this implement/fix?

Continuously process changed pressure compensation values for SCD30 CO2 sensor.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esp8266:
  board: d1_mini

esphome:
  name: "test"
  friendly_name: "test"

globals:
  - id: last_calibrate_pressure
    type: float
    restore_value: no
    initial_value: '0'

i2c:
  scan: false
  id: bus_a

sensor:
  - platform: scd30
    id: sensor_scd30
    co2:
      name: "scd30_co2"
      accuracy_decimals: 0
      icon: "mdi:molecule-co2"
    automatic_self_calibration: false
    address: 0x61
    update_interval: 3s
  - platform: bme280
    pressure:
      name: "bme280_pressure"
      id: "bme280_pressure"
      on_value:
        then:
          - lambda: |-
              if (abs(id(bme280_pressure).state - id(last_calibrate_pressure)) > 1) {
                ESP_LOGD("calibrate_pressure", "SCD30 set_ambient_pressure_compensation(%f)", id(bme280_pressure).state/1000);
                sensor_scd30->set_ambient_pressure_compensation(id(bme280_pressure).state/1000);
                id(last_calibrate_pressure) = id(bme280_pressure).state;
              }
      accuracy_decimals: 1
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-21 08:50 UTC, jesserockz requested changes

2023-12-21 08:50 UTC, jesserockz commented on esphome/components/scd30/scd30.cpp
> +      this->restart_continuous_measurements_();
If for some reason the continuous fails to stop or start here once, the component will be marked as failed and stop reporting altogether, is this correct?
If so, `this->cancel_interval("status-check");` needs to also be run at that point to stop this interval callback from running anymore.

2023-12-23 12:52 UTC, optimusprimespace commented
Also writing continuously to the EEPROM of the sensor isn't desired, because it will shorten it's lifespan. A larger pressure difference or a manual time set for when to update the pressure would be awesome!

2023-12-24 02:26 UTC, schiermi commented
I try to look into the suggestions the next days

2023-12-24 02:39 UTC, schiermi commented
> A larger pressure difference or a manual time set for when to update the pressure would be awesome!

It's already up to the user when to call set_ambient_pressure_compensation.

2025-09-19 01:20 UTC, closed without merging