Add Seeed Studio mmWave Kit MR24HPC1
OttoWinter/esphomeyaml pull request #5761
Opened 2023-11-15 09:02 UTC by limengdu

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ √ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3376

## Test Environment

- [ ] ESP32
- [ √ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
mr24hpc1:
  id: my_mr24hpc1

text_sensor:
  - platform: mr24hpc1
    heartbeat:
      name: "Heartbeat"
    productmodel:
      name: "Product Model"
    productid:
      name: "Product ID"
    hardwaremodel:
      name: "Hardware Model"
    hardwareversion:
      name: "Hardware Version"
    keepaway:
      name: "Active Reporting Of Proximity"
    motionstatus:
      name: "Motion Information"

binary_sensor:
  - platform: mr24hpc1
    someoneexist:
      name: "Presence Information"

sensor:
  - platform: mr24hpc1
    custompresenceofdetection:
      name: "Static Distance"
```

## Checklist:
  - [ √ ] The code change is tested and works locally.
  - [ √ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ √ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-12 04:34 UTC, jesserockz requested changes
Below is a whole bunch of changes/comments on various parts. Many of them need to be applied in multiple places that I was not going to write here in the GH UI.

Please hit the `ready for review` button at the bottom of the PR when you have applied all changes.

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/__init__.py
> +)
There is no need to declare CONFIG_SCHEMA and then immediately override it with an extension.
Feel free to add back in some comments, but most of them were explaining the extending so I just removed them.

```suggestion
CONFIG_SCHEMA = (
    cv.Schema(
        {
            cv.GenerateID(): cv.declare_id(MR24HPC1Component),
        }
    )
    .extend(uart.UART_DEVICE_SCHEMA).extend(cv.COMPONENT_SCHEMA)
)
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/__init__.py
> +)
Not used anywhere?
```suggestion
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/binary_sensor.py
> +    DEVICE_CLASS_OCCUPANCY,  # https://github.com/limengdu/esphome/blob/17e1d4c2455997a0a15c875950be1942c6249d0d/esphome/const.py#L1006
```suggestion
    DEVICE_CLASS_OCCUPANCY,
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/binary_sensor.py
> +CONF_SOMEONE_EXIST = "someone_exist"
As per a suggestion I saw from @kbx81 it is a bit better to reuse config keys from other components to not create so much diversity/confusion for users
```suggestion
CONF_HAS_TARGET = "has_target"
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/button/__init__.py
> +    ),
What does `reset` mean?

Is this a factory reset of the data on the sensor? If so, I think it should be named `CONF_FACTORY_RESET`/`factory_reset` for clear purpose.

If it is just to restart the device, then it should be named `CONF_RESTART`/`restart`

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/number/__init__.py
> +        await cg.register_parented(n, config[CONF_MR24HPC1_ID])
Since you already have the parent you can use it here as the second argument to save it doing a lookup again
```suggestion
        await cg.register_parented(n, mr24hpc1_component)
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/number/__init__.py
> +Motion2RestTimeNumber = mr24hpc1_ns.class_("Motion2RestTimeNumber", number.Number)
This should be named "properly"
```suggestion
MotionToRestTimeNumber = mr24hpc1_ns.class_("MotionToRestTimeNumber", number.Number)
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.cpp
> +  LOG_TEXT_SENSOR(" ", "HeartbeatTextSensor", this->heartbeat_state_text_sensor_);
Please use spaces in the labels here
```suggestion
  LOG_TEXT_SENSOR(" ", "Heartbeat Text Sensor", this->heartbeat_state_text_sensor_);
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.cpp
> +      //   break;
No commented out code allowed please.

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.cpp
> +      // break;
No commented code allowed please.

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.cpp
> +  unsigned char send_data_len = 10;
We use the `uint8_t` type in ESPHome instead of `unsigned char`
```suggestion
  uint8_t send_data_len = 10;
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.cpp
> +  }
This should just write the array at once and let the underlying code handle it.
```suggestion
  this->write_array(query, string_length);
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.cpp
> +  show_frame_data(query, i);
Please make sure all member variables and functions are prefixed with `this->` as per our published [codebase standards](https://esphome.io/guides/contributing#codebase-standards)
```suggestion
  this->show_frame_data(query, i);
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.cpp
> +}
This should not be added as:
1: it bypasses esphome normal logging
2: users can add `debug` to the uart component to print out all sent and received raw bytes when they require it.
```suggestion
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/select/__init__.py
> +            options=["None", "Living Room", "Bedroom", "Washroom", "Area Detection"],
Why are these options hardcoded, what do they mean exactly?

2023-12-12 04:34 UTC, jesserockz commented on esphome/pyvenv.cfg
Please dont add user specific files to ESPHome

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.h
> +  SUB_SENSOR(movementSigns)
variables shoudl always be `lower_snake_case`
```suggestion
  SUB_SENSOR(movement_signs)
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/__init__.py
> +)
This should also extend `cv.polling_component_schema("60s")` instead of `cv.COMPONENT_SCHEMA` so the user can set the `update_inteval

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.h
> +  MR24HPC1Component() : PollingComponent(8000) {}  // The update() function is called every 8 seconds.
The default for all ESPHome sensor components is 60 seconds, and is set by the above `cv.polling_component_schema("60s")`
```suggestion
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.h
> +  void send_query(uint8_t *query, size_t string_length);
These should all be protected functions

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.cpp
> +  if (this->custom_mode_num_sensor_->state == 0)
This also needs a nullptr check

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/seeed_mr24hpc1.h
> +  void set_existence_threshold(int value);
Please use the correct limiting type for arguments and variables to lessen the amount of ram used by this component.
```suggestion
  void set_existence_threshold(uint8_t value);
```

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/select/existence_boundary_select.cpp
> +void ExistenceBoundarySelect::control(const std::string &value) { this->parent_->set_existence_boundary(value); }
If the string values for these selects are hardcoded into the firmware of the sensor, and have the same index, then you should just use `this->index_of(value)` to get the index number and send that directly to the parent instead of doing a `std::map` with string lookup to save on flash and memory.

2023-12-12 04:34 UTC, jesserockz commented on esphome/components/seeed_mr24hpc1/select/existence_boundary_select.cpp
> +void ExistenceBoundarySelect::control(const std::string &value) { this->parent_->set_existence_boundary(value); }
These selects/controls should also do `this->publish_state(value);` so that the state is instantly updated and doesn't have to wait for the device to respond.

2023-12-14 06:46 UTC, limengdu commented on esphome/components/seeed_mr24hpc1/select/__init__.py
> +            options=["None", "Living Room", "Bedroom", "Washroom", "Area Detection"],
The radar allows the user to set up scenarios for its use. Different scenarios correspond to different commands, e.g. Living Room corresponds to 0x01. For the user, it is possible to select different scenarios from a selection box to change the recognition accuracy of the radar, whereas 0x01 is not readable for the user, and Living Room helps them to understand it.

2024-02-18 01:44 UTC, limengdu commented
Please review the merger, thank you.

2024-03-12 03:32 UTC, jesserockz approved these changes

2024-03-12 03:33 UTC, merged