Add Uponor Smatrix component
OttoWinter/esphomeyaml pull request #5769
Opened 2023-11-15 20:30 UTC by kroimon

# What does this implement/fix?

This adds a component to read and control an Uponor Smatrix Base Pulse underfloor heating control system.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
```yaml
# Example config.yaml

time:
  - platform: homeassistant
    id: ha_time

uart:
  baud_rate: 19200
  tx_pin: GPIO17
  rx_pin: GPIO16
  debug:

uponor_smatrix:
  address: 0x110B
  time_id: ha_time
  time_device_address: 0xDE13

climate:
  - platform: uponor_smatrix
    address: 0xDE13
    name: "Thermostat Living Room"

sensor:
  - platform: uponor_smatrix
    address: 0xDE13
    humidity:
      name: "Thermostat Humidity Living Room"
    temperature:
      name: "Thermostat Temperature Living Room"
    external_temperature:
      name: "Thermostat Floor Temperature Living Room"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-11-17 13:31 UTC, ellull approved these changes

2023-12-12 20:39 UTC, kroimon commented on tests/test1.yaml
> +    rx_pin: GPIO16
```suggestion
    tx_pin:
      allow_other_uses: true
      number: 17
    rx_pin:
      allow_other_uses: true
      number: 16
```

2023-12-13 01:27 UTC, jesserockz requested changes

2023-12-13 01:27 UTC, jesserockz commented on esphome/components/uponor_smatrix/climate.py
Please move this (and sensor) and supporting cpp files into their relevant sub-folders

2024-01-19 04:33 UTC, jesserockz requested changes

2024-01-19 04:33 UTC, jesserockz commented on tests/test1.yaml
> +      name: "Thermostat Floor Temperature Living Room"
Quotes not required in simple strings in YAML
```suggestion
      name: Thermostat Humidity Living Room
    temperature:
      name: Thermostat Temperature Living Room
    external_temperature:
      name: Thermostat Floor Temperature Living Room
```

2024-01-19 04:33 UTC, jesserockz commented on tests/test1.yaml
> +    name: "Thermostat Living Room"
```suggestion
    name: Thermostat Living Room
```

2024-01-19 04:33 UTC, jesserockz commented on esphome/components/uponor_smatrix/uponor_smatrix.h
> +  void set_device_address(uint16_t address) { address_ = address; }
Please make sure to prefix all class members and member functions with `this->`
```suggestion
  void set_device_address(uint16_t address) { this->address_ = address; }
```

2024-01-19 04:33 UTC, jesserockz commented on esphome/components/uponor_smatrix/uponor_smatrix.h
> +  optional<time::RealTimeClock *> time_id_{};
No need to overcomplicate this with `optional`
```suggestion
  time::RealTimeClock *time_id_{nullptr};
```

2024-01-19 04:33 UTC, jesserockz commented on esphome/components/uponor_smatrix/uponor_smatrix.cpp
> +  std::vector<uint8_t> packet;
We can reserve the underlying data array since we know how many bytes will be pushed
```suggestion
  std::vector<uint8_t> packet(6 + 3 * data_len);
```

2024-01-19 04:33 UTC, jesserockz commented on esphome/components/uponor_smatrix/uponor_smatrix.cpp
> +  this->check_uart_settings(19200);
This should be changed to use `uart.final_validate_schema` in __init__.py` to check the baud rate before compiling.

2024-01-19 04:33 UTC, jesserockz commented on esphome/components/uponor_smatrix/uponor_smatrix.cpp
> +  if ((now - this->last_rx_ > 300) && (now - last_poll_start_ < 9500) && (now - last_tx_ > 200)) {
```suggestion
  if ((now - this->last_rx_ > 300) && (now - this->last_poll_start_ < 9500) && (now - this->last_tx_ > 200)) {
```

2024-01-19 10:07 UTC, kroimon commented on esphome/components/uponor_smatrix/uponor_smatrix.h
> +  optional<time::RealTimeClock *> time_id_{};
Good catch, `optional` really doesn't make much sense with pointer types. I think I just blindly copied that from the `tuya` integration... Fixed.

2024-01-19 10:08 UTC, kroimon commented on esphome/components/uponor_smatrix/uponor_smatrix.cpp
> +  this->check_uart_settings(19200);
Oh, I didn't know `uart.final_validate_schema` existed! Yes, makes sense to check that before compilation.
I left the `check_uart_settings` runtime check in because other components also still use it in addition to the schema validation.

2024-01-19 12:20 UTC, kroimon commented on esphome/components/uponor_smatrix/uponor_smatrix.h
> +  optional<time::RealTimeClock *> time_id_{};
#6120 also cleans this up for `tuya` and `bedjet`.

2024-01-19 14:01 UTC, jesserockz submitted a review, later dismissed

2024-02-22 01:53 UTC, jesserockz approved these changes

2024-02-22 03:03 UTC, merged