feat: Add HTU31D Support
OttoWinter/esphomeyaml pull request #5805
Opened 2023-11-20 19:44 UTC by betterengineering

# What does this implement/fix?
This change adds support for the HTU31D sensor, which is the third generation temperature/humidity sensor from TE and available via a breakout board from [Adafruit](https://www.adafruit.com/product/4832). 

I wrote this component by using the [HTU21D (previous generation](https://esphome.io/components/sensor/htu21d) component as a starting point and referencing the [adafrult/Adafruit_HTU31D](https://github.com/adafruit/Adafruit_HTU31D/tree/master) library for the updated commands. In addition, I used the [datasheet](https://www.tti.com/content/dam/ttiinc/manufacturers/te-connectivity/PDF/HTU31_Sensors_Datasheet.pdf) and the [reference driver](https://github.com/TEConnectivity/HTU31D_Generic_C_Driver) to extend the capabilities provided from the Adafruit library.

**One design choice I'd love feedback on**: While I wrote functionality into the CPP component to be able to inspect and toggle the heater, I removed configuration values for the end user. I feel it's a confusing feature for a user of this component, especially given it took me a bit of research to fully understand what it's purpose was :sweat_smile: .

From [Adafruit](https://www.adafruit.com/product/4832):
> The sensor also has an on-board heater that can be controlled on and off to help evaporate condensation on the sensing element. Of course, temperature sensing will not be accurate with the heater on. 

From the [previous version's reference](https://cdn-shop.adafruit.com/datasheets/1899_HTU21D.pdf):
> The heater is intended to be used for functionality diagnosis: relative humidity drops upon rising temperature. The heater consumes about 5.5mW and provides a temperature increase of about 0.5-1.5°C.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes #3485 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: htu31d
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"

external_components:
  - source:
      type: local
      path: /home/mark/code/src/github.com/betterengineering/esphome/esphome/components
    components: [ htu31d ]
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-11-20 21:36 UTC, betterengineering commented
Currently testing this component against a Govee H5074 and will report back with a time series once I have more data:
![image](https://github.com/esphome/esphome/assets/3886576/d8fcf521-ea3c-4754-a00d-5747232b5825)

2023-11-21 00:40 UTC, jesserockz requested changes
Overall looks good. Just a few changes below please =)

2023-11-21 00:40 UTC, jesserockz commented on esphome/components/htu31d/htu31d.h
> +#define HTU31D_DIAGNOSTICS (0x08)
Please use `static const uint8_t xxxx = xx;` for values like this.
They can also move to the `.cpp` file as they are not used in the header.

2023-11-21 00:40 UTC, jesserockz commented on esphome/components/htu31d/htu31d.cpp
> +  temperature /= 65535.0;
```suggestion
  temperature /= 65535.0f;
```

2023-11-21 00:40 UTC, jesserockz commented on esphome/components/htu31d/htu31d.cpp
> +  raw_temp |= thdata[1];
```suggestion
  uint16_t raw_temp = encode_uint16(thdata[0], thdata[1]);
```

2023-11-21 00:40 UTC, jesserockz commented on esphome/components/htu31d/htu31d.cpp
> +#include "esphome/core/hal.h"
Required for `encode_uint16`
```suggestion
#include "esphome/core/hal.h"
#include "esphome/core/helpers.h"
```

2023-11-21 00:40 UTC, jesserockz commented on esphome/components/htu31d/htu31d.cpp
> +  raw_hum |= thdata[4];
```suggestion
  uint16_t raw_hum = encode_uint16(thdata[3], thdata[4]);
```

2023-11-21 00:40 UTC, jesserockz commented on esphome/components/htu31d/htu31d.cpp
> +  humidity /= 65535.0;
```suggestion
  humidity /= 65535.0f;
```

2023-11-21 00:40 UTC, jesserockz commented on esphome/components/htu31d/htu31d.cpp
> +  serial <<= 8;
```suggestion
  serial = encode_uint24(reply[0], reply[1], reply[2]);
```

2023-11-21 00:40 UTC, jesserockz commented on esphome/components/htu31d/htu31d.h
> +  void set_heater(sensor::Sensor *heater) { heater_ = heater; }
Not used
```suggestion
```

2023-11-21 00:40 UTC, jesserockz commented on esphome/components/htu31d/htu31d.h
> +  sensor::Sensor *heater_{nullptr};
Not used
```suggestion
```

2023-11-21 00:40 UTC, jesserockz commented on esphome/components/htu31d/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_TEMPERATURE])
This is the newest way to do this that the codebase is slowly switching to
```suggestion
    if temperature_config := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_config)
```

2023-11-21 02:02 UTC, betterengineering commented
Thanks for all the feedback @jesserockz! :raised_hands: Let me know if I missed anything

2023-11-21 15:35 UTC, betterengineering commented
Some more stats for the nerds :nerd_face: The blue line is for the HTU31D. It looks like the temperature difference is about 1 degree Fahrenheit, but consistently so:
![image](https://github.com/esphome/esphome/assets/3886576/dc78102b-6b5d-4de4-80f1-322fa559ef21)

For humidity, the blue line is for the HTU31D and it appears to be a 2% difference, but consistently so:
![image](https://github.com/esphome/esphome/assets/3886576/1b1c3f3b-f7b7-4c8e-b560-235c869d4968)

2023-12-07 07:18 UTC, dbaarda commented
First, thanks for doing this. I haven't had time to play with it yet, but would definitely never have found time to implement it myself. Maybe I'll get a chance to 

 @betterengineering: In my experience with an ESP32C3 and a BME280 (documented at https://community.home-assistant.io/t/success-esphome-esp32-c3-bme280-mqtt-and-deep-sleep-with-homeassistant/432067), a constant temp offset like that can be caused by just having your sensor and micro close enough in the same enclosure and not using deep-sleep. The heat generated by the micro power consumption bumps the temp up a bit. A temp offset also directly translates into a humidity difference, since humidity % depends on air temp.

I think I 've also seen that the temp difference can depend on how good your wifi signal is. I think a weaker wifi connection requires it to be driven harder, chewing more power, generating more heat. I'm using a case with a fair bit of sensor/micro separation and pretty good passive ventilation grills

I just noticed above that the heater feature says "5.5mW and provides a temperature increase of about 0.5-1.5°C" . A non-sleeping busy ESP32C3 board using wifi eats about 50mA, which at 3.3V  is 165mW and drops to about 2mA or 6.6mW for "light sleep", and down to 0.1mA or 0.33mW for "deep sleep". These power numbers, even for "light sleep" are more than the "heater mode", so it's only the extra distance from the sensor and ventilation that means you don't see even higher temp rises without deep-sleeping.

2024-03-12 23:35 UTC, dbaarda commented
Err... I want this... can we please not forget to merge this?

What else still needs to be done?

2024-03-12 23:38 UTC, dbaarda commented
If the original author is AWOL I'm willing to take this over and apply the suggested fixes... any way I can easily do that?

2024-03-13 00:17 UTC, betterengineering commented
Yes, I believe I'm just waiting on an approval. @jesserockz is this good to go?

2024-03-13 00:31 UTC, jesserockz commented
Im just making a few minor updates, but yes it will be merged soon

2024-03-13 00:34 UTC, jesserockz approved these changes

2024-03-13 01:04 UTC, merged