feat(packages): support removing components
OttoWinter/esphomeyaml pull request #5821
Opened 2023-11-22 23:03 UTC by TMaYaD

# What does this implement/fix?

Items from lists can be removed by `id`.
```yaml
sensor:
  - id: !remove uptime_sensor
```

Items from dicts can be removed directly:
```yaml
voice_assistant:
  media_player: media_player.kitchen_speaker_2
  speaker: !remove
```

Works even at top level:
```yaml
captive_portal: !remove
```

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [*] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [esphome/feature-requests#2163](https://github.com/esphome/feature-requests/issues/2163)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

_Included in description._

## Checklist:
  - [*] The code change is tested and works locally.
  - [*] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-11-23 15:53 UTC, nielsnl68 commented
Just wondering; what is the use case for this kind of feature?

2023-11-23 18:31 UTC, TMaYaD commented
There are some use cases mentioned in the feature-request.

Personally, I have a little over 200 devices on my network which are made up of 4 types of hardware and a mix of traits I've made into packages. As the old adage goes, there is an exception to every rule and my packages are no exception. Sometimes it's just easy (and better DRY) to remove a component from a package for a device than add it to all the other devices. 

One example is where most of my fans are fan controllers but there is that one fan which is just an on/off and runs off of a 4 gang switch board. It's better abstraction to configure the switch board and *remove* the one switch and redefine it as a fan rather than redefine all the other 3.

2023-11-23 20:42 UTC, jesserockz reviewed
:heavy_check_mark: Tentative approval on the code side until I test it locally

2023-11-28 11:51 UTC, TMaYaD commented
@jesserockz any update on this?

2023-11-28 18:23 UTC, jesserockz commented
I just have not had the chance to test this yet as I have been doing other stuff. I hopefully try it today

2023-11-28 21:28 UTC, jesserockz requested changes
Ok just gave this a quick test and the removal process works as expected when you write the correct id. This brought up an issue though, which is the fact that you can `!remove any_id` and it doesn't care if it exists or not which should not be allowed and should be an invalid config.

2023-11-29 17:59 UTC, TMaYaD commented
@jesserockz Added validations as requested. Turns out I mis-interpreted the missing ID test for !extend (after which I modelled this PR) 🤣

2023-12-02 23:20 UTC, barndawgie commented
Would be great to see this merged soon; we have some usecases that will be much simpler with it!

2023-12-06 00:30 UTC, jesserockz approved these changes
Thanks for making that final change!

2023-12-06 01:04 UTC, merged