Prevent network config on rpipico board
OttoWinter/esphomeyaml pull request #5832
Opened 2023-11-24 23:05 UTC by carlosV2

# What does this implement/fix?

It prevents adding networking capabilities to a board that doesn't support them.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/5134

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** n/a

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

This bugfix actually fixes the wizard that generates the yaml files. Nevertheless, here is an example generated for the `rpipicow` board:
```yaml
esphome:
  name: picowboard
  friendly_name: picowboard

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "SzsbyFrPhZEzvdJ27nxNdMoLFSDi28t2uFMT7IGy9pI="

ota:
  password: "eb0c1a91c47001b923f61e28bf9b4b0d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Picow Fallback Hotspot"
    password: "EL2kvLpeXTmm"
```

And another example generated for the `rpipico` board:
```yaml
esphome:
  name: picoboard
  friendly_name: picoboard

rp2040:
  board: rpipico
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

Couldn't find any test for the wizard. If they exist, please, could you point me to them so I can update them accordingly? Many thanks!

2023-12-18 04:25 UTC, jesserockz requested changes

2023-12-18 04:25 UTC, jesserockz commented on esphome/wizard.py
> +        config += API_CONFIG
Its much better to return early instead of putting everything inside a conditional branch
```suggestion
    if kwargs["board"] == "rpipico":
    	return config
    	
    config += API_CONFIG
```

2024-02-18 18:57 UTC, jesserockz approved these changes

2024-02-19 01:29 UTC, merged

2024-02-20 11:37 UTC, carlosV2 commented
@jesserockz apologies. I completely forgot about this as I was working with a patched copy (which reminds me that I should pull latest changes more often 🤦🏼‍♂️). Many thanks!