Nanos
OttoWinter/esphomeyaml pull request #5857
Opened 2023-11-28 18:47 UTC by erapade

# What does this implement/fix?

We currently only have a timestamp function that measures down to micro seconds. In some situations there's a requirement to have time stamps with resolutions and hence I added the nanos() function.

I did this knowing that the resolution will not come down to nano seconds due to the system clock frequency but this will still be better than just using the already existing micros().

Using a 80 MHz system clock the resolution will be 12.5 nano seconds
using a 120 MHz system clock the resolution will be 6.25 nano seconds

This function will be used to increase the reliability of timing in the Dallas component

And yes, 12.5 nano seconds in resolution will not give us an accuracy of 12.5 nano seconds, but using relative time measures this will help.

There was already and existing arch_get_cpu_cycle_count() that will do the same thing but this function wasn't declared as IRAM_ATTR HOT and didn't follow the same naming convention as micros() and millis()

This is my first pull request of code, Please be nice to me ;-)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-11-28 22:58 UTC, jesserockz requested changes

2023-11-28 22:58 UTC, jesserockz commented on esphome/components/host/core.cpp
> +uint32_t IRAM_ATTR HOT nanos() {
This file is only used when building a native linux binary for example, not on esp32/esp8266 etc...
You will need to implement on all platforms in their respective components.

2023-11-29 07:29 UTC, erapade commented on esphome/components/host/core.cpp
> +uint32_t IRAM_ATTR HOT nanos() {
Ohhh, Thanks @jesserockz. Based on your comment I looked into that. Makes sense since I then can include those components as local in my yaml. But I really didn't understand how to implement it in ESP8266 and ESP32 components and the current implementation of micros() in these components looks very different.

Any chance you can point me to some directions. This is my first attempt to contribute to ESPHome

2023-11-29 07:45 UTC, ssieb commented on esphome/components/host/core.cpp
> +uint32_t IRAM_ATTR HOT nanos() {
I think microseconds is the smallest interval easily available.  You can try looking through the ESP docs to see if you can find something else.

2024-03-07 00:44 UTC, closed without merging