Add Support for Infineon XENSIV PASCO2 CO2 Sensor
OttoWinter/esphomeyaml pull request #5883
Opened 2023-12-03 00:30 UTC by circuitvalley

# What does this implement/fix?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sensor:
   - platform: pasco2
      co2:
        name: "PASCO2 CO2"
      measurement_mode: periodic
      update_interval: 5s

```

## Checklist:
  - [x ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-21 04:56 UTC, jesserockz requested changes
With all of the set_timeouts and delays in the setup code, I feel like this component needs to be refactored to use a state machine and do one task in loop and set a timer to move to the next task etc.

2023-12-21 04:56 UTC, jesserockz commented on esphome/components/pasco2/automation.h
> + protected:
Not required, the macro includes these modifiers.
```suggestion
```

2023-12-21 04:56 UTC, jesserockz commented on esphome/components/pasco2/pasco2.cpp
> +          ESP_LOGE(TAG, "Failed to Write Scractch Pad");
```suggestion
          ESP_LOGE(TAG, "Failed to Write Scratch Pad");
```

2023-12-21 04:56 UTC, jesserockz commented on esphome/components/pasco2/pasco2.cpp
> +        delay(100);  // NOLINT wait 100 ms and try again
This should use `set_retry` instead of delay

2023-12-21 04:56 UTC, jesserockz commented on esphome/components/pasco2/pasco2.cpp
> +      delay(XENSIV_PASCO2_SOFT_RESET_DELAY_MS);  // NOLINT wait 2000 ms for sensor to reset
This is way too long for a delay in ESPHome.

2024-09-30 10:14 UTC, ozonejunkieau commented
I'm pretty keen to get this merged and am happy to help refactor it. 

Is there a good example state machine based implementation to model this refactoring on?

2025-09-19 01:27 UTC, swoboda1337 commented
Replaced by https://github.com/esphome/esphome/pull/8175

2025-09-19 01:27 UTC, closed without merging