Add support for lan867x Microchip 10BASE-T1S Single Pair Ethernet PHY
OttoWinter/esphomeyaml pull request #5904
Opened 2023-12-11 15:51 UTC by adeepn

# What does this implement/fix?

Add driver for lan867x Microchip 10BASE-T1S Single Pair Ethernet PHY.
Driver developed for ESP IDF 5.x. Based on work @bigdankolendovskyy https://github.com/espressif/esp-eth-drivers/pull/19

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2126

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3447

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: jxd-e1-t1s
  name_add_mac_suffix: true

esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
    version: 5.1.2
    platform_version: https://github.com/platformio/platform-espressif32
    # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SPEED: y
      CONFIG_GPIO_CTRL_FUNC_IN_IRAM: y

ethernet:
  type: LAN867x
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  power_pin: GPIO17
  clk_mode: GPIO0_IN
  phy_addr: 0

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-11 16:04 UTC, nagyrobi commented
Is there any hardware available we can test this with?

2023-12-11 16:07 UTC, adeepn commented
> Is there any hardware available we can test this with?

We have engineering samples of the devices on ESP32 with LAN8671. Ethernet tested:

```
[17:31:08][I][app:102]: ESPHome version 2023.12.0-dev2 compiled on Dec 11 2023, 17:30:33
[17:31:08][C][PCF8563:022]: PCF8563:
[17:31:08][C][PCF8563:023]:   Address: 0x51
[17:31:08][C][ethernet:233]: Ethernet:
[17:31:08][C][ethernet:365]:   IP Address: 10.42.0.74
[17:31:08][C][ethernet:366]:   Hostname: 'jxd-e1-t1s-6bfa48'
[17:31:08][C][ethernet:367]:   Subnet: 255.255.255.0
[17:31:08][C][ethernet:368]:   Gateway: 10.42.0.1
[17:31:08][C][ethernet:373]:   DNS1: 10.42.0.1
[17:31:08][C][ethernet:374]:   DNS2: 0.0.0.0
[17:31:08][C][ethernet:394]:   MAC Address: 3C:E9:0E:6B:FA:4B
[17:31:08][C][ethernet:399]:   Is Full Duplex: NO
[17:31:08][C][ethernet:404]:   Link Speed: 10
[17:31:08][C][ethernet:236]:   Power Pin: 17
[17:31:08][C][ethernet:238]:   MDC Pin: 23
[17:31:08][C][ethernet:239]:   MDIO Pin: 18
[17:31:08][C][ethernet:240]:   Type: LAN867X
[17:31:08][C][ethernet:241]:   PHY addr: 0
[17:31:08][C][web_server:168]: Web Server:
[17:31:08][C][web_server:169]:   Address: jxd-e1-t1s.local:80
```

2023-12-12 12:38 UTC, nagyrobi commented
Does your hardware support T1S only, or does it work with T1L also?

10Base-T1S (S stands for short reach) has a reach of up to 25m, it's designed for in-vehicle applications. 10Base-T1L (L stands for long reach) allows for the same 10 Mb/s speed over a reach of 1000m. T1L would be very beneficial in smarthome/building environment, as laid cable lengths can easily run over 25m within a building.

2023-12-12 12:51 UTC, adeepn commented
> Does your hardware support T1S only, or does it work with T1L also?

We use lan8671: The LAN8671 is a high-performance 10BASE-T1S single-pair Ethernet PHY transceiver


> 10Base-T1S (S stands for short reach) has a reach of up to 25m, it's designed for in-vehicle applications. 10Base-T1L (L stands for long reach) allows for the same 10 Mb/s speed over a reach of 1000m. T1L would be very beneficial in smarthome/building environment, as laid cable lengths can easily run over 25m within a building.



We are currently focused on the T1S: it is very well suited for assembling smart home electrical panels, where many modules are located on one bus and close to each other.
The T1L, in turn, is well suited for remote sensors or for external modules. This is planned for later.

2023-12-12 13:02 UTC, nagyrobi commented
[This adapter](https://buildings.honeywell.com/us/en/products/by-category/control-panels/building-controls/zone-and-unitary-controllers/t1l-media-adapter#overview) for example would allow to connect the 10BASE-T1L bus directly to 10BASE-T Ethernet (typically a simple Ethernet switch which has a 10/100Mbit port).

Would be nice to have such an adapter to 10BASE-T1S too...

2023-12-12 13:05 UTC, adeepn commented
> Would be nice to have such an adapter to 10BASE-T1S too...

We have such a device in production: Ethernet switch 2x100Mbit + 1 T1S. We are expecting engineering samples in near weeks :)

2023-12-12 13:08 UTC, nagyrobi commented
Please send me a contact, I'd like to test.

2024-01-29 10:33 UTC, adeepn commented
Resync with upstream drivers and rebase

2024-03-23 18:10 UTC, Callum6677 commented
This might be me missing something as I am not too in touch with ESPHome codebase, but while I see you have the structs and interface defined to node id and node count for the phy, I dont see anywhere you're actually setting this or allowing ESPHome to set it.

2024-03-25 10:55 UTC, adeepn commented
This version of the driver works for IDF>=5.1.2
esp-eth-drivers repo has driver with requirements IDF>=5.3
I'l switch PR to new driver after 5.3 release and add support for it in platform component

2024-03-25 22:51 UTC, jesserockz requested changes
This will need a custom validation that only allows you to choose this type if using idf 5 and above.

2024-08-08 12:27 UTC, adeepn commented
> This will need a custom validation that only allows you to choose this type if using idf 5 and above.

can you provide an example?
at this moment:
if you do not use lan867x driver esphome builds ok in all versions.
if you use lan867x driver - build fails if not used idf>=5.3 (and platform_version>=6.8.0)

2024-08-19 08:06 UTC, adeepn commented
Can fail on IDF 5.3.0 (https://github.com/espressif/esp-idf/issues/14265), with idf5.3.0 fix works.

2024-09-23 09:12 UTC, adeepn commented
rebase on dev

> This will need a custom validation that only allows you to choose this type if using idf 5 and above.

added validation

2024-09-25 01:02 UTC, jesserockz commented on esphome/components/ethernet/__init__.py
> +            )
Possibly this can be replaced by the below (untested)
```suggestion
        cv.require_framework_version(esp_idf=cv.Version(5, 3, 1))
```

2024-09-27 07:40 UTC, adeepn commented on esphome/components/ethernet/__init__.py
> +            )
```
validator = cv.require_framework_version(esp_idf=cv.Version(5, 3, 0))
validator(config)
```
works

2024-09-27 07:43 UTC, adeepn commented
add bug fix in уsp idf (esp_eth_mac_esp.h)  5.3.0&5.3.1 versions. will be fixed in 5.3.2 (hope so).

2025-01-17 12:32 UTC, adeepn commented
@jesserockz gentle ping. Any recommendations on what is missing in this pr for it to be accepted?

2025-10-10 13:31 UTC, closed without merging