UART change at runtime
OttoWinter/esphomeyaml pull request #5909
Opened 2023-12-12 13:29 UTC by edwardtfn

# What does this implement/fix?

This adds the method `load_settings()` to the UART component on ESP32 (`arduino` and `esp-idf`) allowing the interface to reload with the new settings used by methods `set_baud_rate`, `set_parity`, `set_data_bits`, etc. without the assignment of a new software UART.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** N/A
Related Discord thread: https://discord.com/channels/429907082951524364/1180653963461275648

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
select:
  - id: change_baud_rate
    name: Baud rate
    platform: template
    options:
      - "2400"
      - "9600"
      - "38400"
      - "57600"
      - "115200"
      - "256000"
      - "512000"
      - "921600"
    initial_option: "115200"
    optimistic: true
    restore_value: True
    internal: false
    entity_category: config
    icon: mdi:swap-horizontal
    set_action:
      - lambda: |-
          tf_uart->flush();
          ESP_LOGD("change_baud_rate", "Set new baud rate to %i", stoi(x));
          tf_uart->set_baud_rate(stoi(x));
          tf_uart->load_settings();
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-13 00:34 UTC, jesserockz requested changes

2023-12-13 00:34 UTC, jesserockz commented on esphome/components/uart/uart_component_esp32_arduino.cpp
> +  load_settings(false);
Please ensure that you are prefixing member variables and function calls
```suggestion
  this->load_settings(false);
```

2023-12-13 00:34 UTC, jesserockz commented on esphome/components/uart/uart_component_esp32_arduino.cpp
> +    dump_config_();
```suggestion
    this->dump_config_();
```

2023-12-13 00:34 UTC, jesserockz commented on esphome/components/uart/uart_component_esp_idf.cpp
> +    dump_config_();
```suggestion
    this->dump_config_();
```

2023-12-13 00:34 UTC, jesserockz commented on esphome/components/uart/uart_component_esp32_arduino.cpp
> +void ESP32ArduinoUARTComponent::dump_config() { this->dump_config_(); }
What is the purpose of having this intermediate function?

2023-12-13 02:52 UTC, edwardtfn commented on esphome/components/uart/uart_component_esp32_arduino.cpp
> +void ESP32ArduinoUARTComponent::dump_config() { this->dump_config_(); }
The idea is to have it showing the new settings on the log when it changes. Some of the validations won't support a directly call to `dump_config()` and I don't wanna to duplicate it's code, so I've used a different name for the function and kept the original `dump_config()` with the reference to the other one as this is called when log starts.

2023-12-13 05:37 UTC, edwardtfn commented on esphome/components/uart/uart_component_esp32_arduino.cpp
> +void ESP32ArduinoUARTComponent::dump_config() { this->dump_config_(); }
Well, look again at the Action's logs maybe it haven't failed due to calling `dump_config()`, but due to calling it directly (instead of `this->dump_config()`). I will try that again as it will make the code cleaner...

2023-12-13 06:01 UTC, edwardtfn commented on esphome/components/uart/uart_component_esp32_arduino.cpp
> +void ESP32ArduinoUARTComponent::dump_config() { this->dump_config_(); }
Done!

2023-12-13 07:28 UTC, jesserockz approved these changes

2023-12-13 07:29 UTC, merged

2023-12-14 08:24 UTC, nagyrobi commented
@edwardtfn please add to the docs (next branch) a note containing the example above mentioning which uart parameters can be reconfigured at runtime.

2023-12-14 08:31 UTC, edwardtfn commented
I can do that, but as none of those pre-existing functions to change settings (`set_baud_rate`, `set_parity`, etc.) are not there, I think we should add a more extensive section describing those a bit.
I can take a look at this later.

2023-12-14 10:40 UTC, nagyrobi commented
Problem is that this PR was merged, functionality is in, but it's not documented for the users.

2023-12-14 10:59 UTC, edwardtfn commented
There is: https://github.com/esphome/esphome-docs/pull/3455

Please let me know your thoughs.

2023-12-14 11:29 UTC, nagyrobi commented
Nice, but I also see changes to the `components/display/nextion.rst` file.

2023-12-14 11:49 UTC, edwardtfn commented
Hmmm
That shouldn't be there...
I will take a look soon.

2023-12-14 12:24 UTC, edwardtfn commented
Now it is correct at https://github.com/esphome/esphome-docs/pull/3456

2023-12-14 13:32 UTC, edwardtfn commented
I've also added some inline documentation at #5930.
Although that isn't changing any line of code, I will run some sanity check later and then request an approval.