Add ability to lock to set mode
OttoWinter/esphomeyaml pull request #5924
Opened 2023-12-14 00:27 UTC by ysmilda

# What does this implement/fix?

It allows locking the read out of the HLW8012 component to a single mode (e.g current or voltage). This is useful when you're not interested in one of the two values and want to continuously read back the other.

This adds an optional parameter (e.g `lock_mode`) which locks the mode to the given `initial_mode`.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** _TBD_

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [x] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

With the below config the `mode` will be locked to `VOLTAGE` and the `change_mode_every` setting will be ignored.

```yaml
# Example config.yaml
  - platform: hlw8012
    change_mode_every: 16
    initial_mode: VOLTAGE
    lock_mode: true
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-14 03:46 UTC, jesserockz requested changes
This would be better to change `change_every` to allow `never` similar to `update_interval`s do

2023-12-14 07:56 UTC, ysmilda commented
I like that proposal, but I'm not sure how to implement that. The `update_interval`s take a time string, this is than checked to be `never` or parsed to an `uint32_t` in milliseconds. The `change_every` already takes an `uint32_t` and changing that to a `string` would break everyone's config. 

Ideally `change_every` would take either a `string` or an `int` but I'm unsure how that could be implemented.

2023-12-14 08:48 UTC, jesserockz commented
You can use something like `cv.Any(..., "never")` to allow the current time and the hardcoded string never. And then convert never into `0` and check for 0 in the cpp code since the minimum is currently 1

2023-12-14 09:23 UTC, ysmilda commented
Thanks for the insight, I've changed `change_every` to accept `"never"` and that locks the mode to the one set in `initial_mode`.

2023-12-15 05:33 UTC, jesserockz commented on tests/test1.yaml
While it is better in the end, please undo the unrelated YAML changes here.

2023-12-15 07:33 UTC, ysmilda commented on tests/test1.yaml
I've undone the changes, formatting on save is a blessing and a curse.

2023-12-15 09:11 UTC, kroimon approved these changes
LGTM

2023-12-18 00:05 UTC, jesserockz commented on tests/test1.yaml
It is yes. Feel free to make a PR dedicated to just formatting the YAML files though =)

2023-12-18 00:05 UTC, jesserockz approved these changes

2023-12-20 10:52 UTC, merged