Add quad spi features
OttoWinter/esphomeyaml pull request #5925
Opened 2023-12-14 00:39 UTC by clydebarrow

# What does this implement/fix?

Add functionality to the SPI component (ESP-IDF only) to allow the use of quad SPI transactions. This will support
the addition of the LilyGo T-Display-S3 AMOLED board and other displays with quad SPI interfaces.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
spi:
  - id: spi_id_1
    clk_pin: GPIO7
    mosi_pin: GPIO6
    interface: any
  - id: quad_spi
    clk_pin: 47
    data_pins:
      - 40
      - 41
      - 42
      - 43
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-14 04:24 UTC, jesserockz commented on esphome/components/spi/__init__.py
> +# clock pin in the standard and quad schemas.
Why would you reuse the pin?

2023-12-14 04:24 UTC, jesserockz commented on esphome/components/spi/__init__.py
> +            ),
You can add a `msg` argument to `cv.Any` with a custom message to print if neither are matched.

2023-12-14 04:28 UTC, clydebarrow commented on esphome/components/spi/__init__.py
> +# clock pin in the standard and quad schemas.
You wouldn't, but the pin gets logged into the registry when the pin validation is evaluated, so if the first schema  fails (due e.g. to miso/mosi missing), the clock pin gets entered twice in the registry.

2023-12-21 03:52 UTC, jesserockz requested changes

2023-12-21 03:52 UTC, jesserockz commented on esphome/components/spi/__init__.py
> +            # relates to the standard schema, not this.
No longer relevant?
```suggestion
```

2023-12-21 05:09 UTC, jesserockz submitted a review, later dismissed

2023-12-21 05:09 UTC, jesserockz commented on esphome/components/spi/__init__.py
> +            ),
Does a full pin schema make sense here when they need to be the number only when configuring the bus and cant be inverted or external etc?

If not, then the below code that calls `set_data_pins` can be simplified to only set a vector of the pin numbers instead of the full objects...

2023-12-21 06:58 UTC, clydebarrow commented on esphome/components/spi/__init__.py
> +            ),
I think the schema is fine, firstly it ensures that only output-capable pins are listed, secondly it allows for the (admittedly unlikely) multiple use of a pin. But it could well be that only the number need be used in the vector. I'll look at that again when I get back to a computer.

2023-12-22 03:09 UTC, jesserockz commented on esphome/components/spi/__init__.py
> +            ),
What I mean is, `pins.internal_gpio_output_pin_number` might be better. IIRC it still allows the multi use, but restricts to an internal pin number only

2024-01-19 02:24 UTC, jesserockz approved these changes

2024-01-19 02:42 UTC, merged