Webserver ota optimization
OttoWinter/esphomeyaml pull request #5937
Opened 2023-12-14 21:42 UTC by afarago

# What does this implement/fix?
When webserver ota is disabled certain amount of memory footprint can be removed during compilation.

## Details of an example config
_non-optimized_
```
RAM:   [====      ]  42.2% (used 34568 bytes from 81920 bytes)
Flash: [=====     ]  45.5% (used 475125 bytes from 1044464 bytes)
```

_optimized
```
RAM:   [====      ]  42.2% (used 34548 bytes from 81920 bytes)
Flash: [====      ]  44.9% (used 468685 bytes from 1044464 bytes)
```

* 34568-34548=20 byte of RAM
* 475125-468685=6440 bytes of flash

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Other

**Related issue or feature (if applicable):** fixes <link to issue>
webserver.ota
https://esphome.io/components/web_server

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
not applicable

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
web_server:
  ota: false

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-14 23:24 UTC, afarago commented
Apologies, will close and reopen this - by mistake I already merged the home_assistant styling improvements, that I should have avoided.
I will clos this, redo and come back with a clean PR.

2024-04-16 22:24 UTC, jesserockz requested changes

2024-04-16 22:24 UTC, jesserockz commented on esphome/components/web_server_base/web_server_base.h
>    void handleUpload(AsyncWebServerRequest *request, const String &filename, size_t index, uint8_t *data, size_t len,
This is also used by captive_portal

2024-04-16 22:24 UTC, jesserockz commented on esphome/components/web_server/web_server.h
> +#endif
This variable has become useless with the define

2025-09-20 11:53 UTC, swoboda1337 commented
Stale for over a year, review comments no resolved.

2025-09-20 11:53 UTC, closed without merging