Add support for DFRobot HCHO Formaldehyde Sensor (SEN0231)
OttoWinter/esphomeyaml pull request #5946
Opened 2023-12-15 20:22 UTC by cwitting

# What does this implement/fix?

Add support for DFRobot HCHO Formaldehyde Sensor (SEN0231) (#2052)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2052

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs https://github.com/esphome/esphome-docs/pull/3461

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
uart:
  - id: uart_bus
    rx_pin: 27
    baud_rate: 9600

sensor:
  - platform: sen0231
    name: "Formaldehyde Sensor"
    update_interval: 10s
    uart_id: "uart_bus"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [?] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-02-14 08:20 UTC, cwitting commented
Is it possible anyone could have a look at this?

2024-07-29 05:00 UTC, jesserockz requested changes

2024-07-29 05:00 UTC, jesserockz commented on esphome/components/sen0231/sen0231.cpp
> +  float val = ((uint16_t) (buffer[CONCENTRATION_HIGH_BYTE] << 8) + buffer[CONCENTRATION_LOW_BYTE]) / 1000.0;
```suggestion
  float val = encode_uint16(buffer[CONCENTRATION_HIGH_BYTE], buffer[CONCENTRATION_LOW_BYTE]) / 1000.0;
```

2024-07-29 05:00 UTC, jesserockz commented on esphome/components/sen0231/sen0231.cpp
> +void Sen0231Sensor::setup() { ESP_LOGCONFIG(TAG, "Setting up sen0231..."); }
No need to log where there is no actual setting up happening
```suggestion
```

2024-07-29 05:00 UTC, jesserockz commented on esphome/components/sen0231/sen0231.cpp
> +  ESP_LOGCONFIG(TAG, "DF Robot Formaldehyde Sensor sen0231:");
```suggestion
  LOG_SENSOR("", "SEN0231", this);
```

2024-07-29 05:00 UTC, jesserockz commented on esphome/components/sen0231/sen0231.cpp
> +static const char *const TAG = "sen0231_sensor.sensor";
```suggestion
static const char *const TAG = "sen0231.sensor";
```

2024-07-29 05:00 UTC, jesserockz commented on tests/test1.yaml
Please make the new test files located in `tests/components/sen0231`

2026-07-30 01:31 UTC, swoboda1337 commented
Closing this out: changes were requested back in July 2024 and the review comments were never addressed, and the PR has been sitting in draft without activity since. The codebase has moved on quite a bit in that time (test layout, coding patterns), so this would need a rework against current dev anyway.

If you or anyone else wants to pick up SEN0231 support again, feel free to open a fresh PR — the sensor itself would still be a welcome addition.

2026-07-30 01:31 UTC, closed without merging