Fix I2CBus::write() bug add documentation
OttoWinter/esphomeyaml pull request #5947
Opened 2023-12-16 14:55 UTC by DrCoolzic

I fixed a bug where the buffer length was incorrectly specified as a uin8_t instead of a size_t.
I have also added a lot of documentation to the i2c library, as well as aliased NO_ERROR to ERROR_OK
File affected:
- esphome/components/i2c/i2c.h
- esphome/components/i2c/i2c_bus.h

# What does this implement/fix?
- This PR fixes the problem of not being able to write buffer of 256 or more bytes when using the ESP-IDF framework.
-  It also fixes the same problem when using the Arduino framework
- at the same time, I took the opportunity to document the I²C library usage
- I have added an alias (so it does not break the I/F) to ERROR_OK

The only code changes are:
```c++
ErrorCode write(const uint8_t *data, uint8_t len, bool stop = true) { return bus_->write(address_, data, len, stop); }
```
As been replaced by
```c++
ErrorCode write(const uint8_t *data, size_t len, bool stop = true) { return bus_->write(address_, data, len, stop); }
```
And the addition of the ErrorCode alias in i2c_bus.h.

As far as the documentation is concerned, I've added information on classes, methods and attributes to help users of the I2C library. Please note that my native language is not English, so it's likely that the text contains errors. Please feel free to correct them.

# What does this PR do not fix?
Unfortunately, this PR does not fix the problem of not being able to read messages with 256 or bytes when using the Arduino framework is used. Fixing this problem requires to modify the Wire.h file in the Arduino framework and I do not know how to do that (or even if it is possible). However, as a courtesy I provide the code to do so.
In Wire.h the following code:
```c++
uint8_t TwoWire::requestFrom(int address, int len) {
    return requestFrom(static_cast<uint16_t>(address), static_cast<size_t>(len), true);
}
uint8_t TwoWire::requestFrom(int address, int len, int sendStop) {
    return static_cast<uint8_t>(requestFrom(static_cast<uint16_t>(address), static_cast<size_t>(len), static_cast<bool>(sendStop)));
}
```

Needs to be replaced by
```c++
size_t TwoWire::requestFrom(int address, int len) {
    return requestFrom(static_cast<uint16_t>(address), static_cast<size_t>(len), true);
}
size_t TwoWire::requestFrom(int address, int len, int sendStop) {
    return requestFrom(static_cast<uint16_t>(address), static_cast<size_t>(len), static_cast<bool>(sendStop));
}
```

# summary
When integrated this fix will allow to use the i2c library with buffers of 256 or more bytes with the ESP-IDF framework but unfortunately for the Arduino library the buffer size will still be limited to 255 unless the framework is also fixed.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
```yaml
esphome:
  name: test-wk2132-i2c-arduino
  platformio_options:
    build_flags:
      - -DI2C_BUFFER_LENGTH=257
esp32:
  board: esp32dev
  framework:
    type: arduino
…
external_components:
  - source: github://pr#5932
    components: [uart]
    refresh: 0s
  - source: github://pr#5218
    components: [wk2132_i2c]
    refresh: 0s

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_i2c
  frequency: 600kHz
```
## more info in this document
[Bus i2c problemes et solutions en.pdf](https://github.com/esphome/esphome/files/13692916/Bus.i2c.problemes.et.solutions.en.pdf)

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

2023-12-17 23:38 UTC, jesserockz requested changes

2023-12-17 23:38 UTC, jesserockz commented on esphome/components/i2c/i2c_bus.h
> +  virtual ErrorCode write(uint8_t address, const uint8_t *buffer, size_t length, bool stop) {
For consistency, please change all `len` to `length` or leave all as `len`

2023-12-18 08:56 UTC, DrCoolzic commented on esphome/components/i2c/i2c_bus.h
> +  virtual ErrorCode write(uint8_t address, const uint8_t *buffer, size_t length, bool stop) {
Chaged `length `to `len`. As it will be more consistent with read and write buffer that we can't change for compatibility reason.
Now len is used for i2c.h and i2c_bus.h

2023-12-18 10:35 UTC, DrCoolzic commented
Is there a way to fix the bug in Wire.h of the Arduino library?

2023-12-18 23:13 UTC, jesserockz approved these changes
Thanks @DrCoolzic

2023-12-18 23:13 UTC, jesserockz commented
> Is there a way to fix the bug in Wire.h of the Arduino library?

The Wire.h code is part of the Arduino Framework and would need to be changed there (If it is not already in a newer Arduino version).

2023-12-18 23:14 UTC, merged