Add graphical layout system
OttoWinter/esphomeyaml pull request #5949
Opened 2023-12-17 09:39 UTC by MrMDavidson

# What does this implement/fix?

Adds a simple graphical layout system. My experience making ESPhome devices with a physical UI is that there's a lot of trial and error to get things to layout nicely. I expect the API in this PR to evolve over time as I add different UI elements and trial it in different ways.

The intent of this is PR is to solicit feedback from the community.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

display:
#  ...
  pages:
    - id: layout_test_page
      lambda: |-
        it.clear();
        
        it.render_layout(0, 0, id(test_layout);

graphical_layout:
  id: test_layout
  layout:
    type: vertical_stack
    item_padding: 1
    items:
      - type: horizontal_stack
        item_padding: 0
        items: 
          - type: text_panel
            font: small_font
            text: 'Left to'
          - type: text_panel
            font: small_font
            text: ' right text'
      - type: text_panel
        font: big_font
        text: 'A 2nd row of text  '

```

Sample config produces: 
![image](https://github.com/esphome/esphome/assets/1366249/1c52d7fd-7f74-4a44-ad17-a5e2a26f0d63)

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-21 03:44 UTC, jesserockz commented
My initial thought on this is that I would make this part of the `pages` config object, exclusive with `lambda`

2023-12-21 03:53 UTC, MrMDavidson commented
> My initial thought on this is that I would make this part of the `pages` config object, exclusive with `lambda`

So for dynamic scenarios the user would need a page per layout and switch between them as needed? Does your thought on having it be one or the other change with the inclusion of the `DisplayRenderingPanel` (final name to be determined!)
```yaml
  - type: display_rendering_panel
    height: 50
    width: 50
    lambda: |-
      it.filled_circle(10, 10, 10);
      it.filled_rectangle(30, 30, 10, 10);
      // Other arbitrary drawing
```

2023-12-29 10:23 UTC, nielsnl68 commented
Hello @MrMDavidson last year i worked on an similar project named [SwitchPanel ](https://github.com/nielsnl68/esphome-components/tree/main/components/switchplate). Maybe you it has some stuff that is interesting for your project.
Also just for your information there is also some work to intergrade LVGL into esphome. 

Suc6 with your project.

2023-12-29 23:26 UTC, MrMDavidson commented
> Hello @MrMDavidson last year i worked on an similar project named [SwitchPanel ](https://github.com/nielsnl68/esphome-components/tree/main/components/switchplate). Maybe you it has some stuff that is interesting for your project. Also just for your information there is also some work to intergrade LVGL into esphome.
> 
> Suc6 with your project.

Interesting project - I remember you mentioning it when I was working on the graphical menu PR. Was there a reason you made it as an external component rather than part of esphome itself?

2024-01-30 23:43 UTC, MrMDavidson commented
> My initial thought on this is that I would make this part of the `pages` config object, exclusive with `lambda`

Hey @jesserockz , any more thoughts on this?

2024-06-24 11:21 UTC, GraffJosh commented
I tried to use this PR, because I'm facing a very similar issue:
waveshare epd driver board
4.2" display WFT0420CZ15

When I install the yaml I get this:
![image](https://github.com/esphome/esphome/assets/15370055/2d0adbb4-9aaa-4ec4-9943-060f6187de82)
![image](https://github.com/esphome/esphome/assets/15370055/335ebc31-3ca7-4610-a4ef-4cc7641e3b58)

Thanks for your work thusfar, hoping there's a solution out there.

2024-08-06 11:01 UTC, jesserockz requested changes
I want to start by saying sorry it has taken so long to really make a start on reviewing this PR.

I have not reviewed this components actual code yet, I have just been fixing and updating it so CI will start passing etc. 

Can you split out the `display::Point`/`local coordinates` stuff into its own PR as there could be feedback specifically to that from others, and it affects all display components.

I think also splitting `text_align_to_string` to its own PR too will make that easier to merge.

2024-08-08 02:46 UTC, MrMDavidson commented
> I want to start by saying sorry it has taken so long to really make a start on reviewing this PR.
>
> I have not reviewed this components actual code yet, I have just been fixing and updating it so CI will start passing etc.

Cheers, appreciate you getting the build back to green!
 
> Can you split out the `display::Point`/`local coordinates` stuff into its own PR as there could be feedback specifically to that from others, and it affects all display components.
> 
> I think also splitting `text_align_to_string` to its own PR too will make that easier to merge.

Will endeavour to get some time this weekend to split these out. Do you want me to split out the doc side of it, too?

2024-08-08 05:04 UTC, jesserockz commented
> Will endeavour to get some time this weekend to split these out. Do you want me to split out the doc side of it, too?

That definitely makes it easier to merge code and docs together

2024-08-11 07:30 UTC, MrMDavidson commented
> > Will endeavour to get some time this weekend to split these out. Do you want me to split out the doc side of it, too?
> 
> That definitely makes it easier to merge code and docs together

Done! See #7243, #7244 and esphome/esphome-docs#4123

2025-09-20 12:02 UTC, swoboda1337 commented
Gone stale and do we really need this anymore after LVGL?

2025-09-20 12:02 UTC, closed without merging