Add support for VEML3235 lux sensor
OttoWinter/esphomeyaml pull request #5959
Opened 2023-12-18 08:32 UTC by kbx81

# What does this implement/fix?

Add support for VEML3235 lux sensor

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: veml3235
    name: Light Sensor
    auto_gain: true
    auto_gain_threshold_high: 0.9
    auto_gain_threshold_low: 0.2
    digital_gain: 1X
    gain: 1X
    integration_time: 50ms
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-20 05:16 UTC, jesserockz requested changes

2023-12-20 05:16 UTC, jesserockz commented on esphome/components/veml3235/sensor.py
> +            cv.Optional(CONF_AUTO_GAIN, default="true"): cv.boolean,
```suggestion
            cv.Optional(CONF_AUTO_GAIN, default=True): cv.boolean,
```

2023-12-20 05:16 UTC, jesserockz commented on esphome/components/veml3235/veml3235.cpp
> +  } else if (device_id[0] != DEVICE_ID) {
`DEVICE_ID` is a `uint16_t` (`0x0035`) and you are comparing it to only the first byte of the `device_id` array returned from the device?

2023-12-20 05:16 UTC, jesserockz commented on esphome/components/veml3235/veml3235.cpp
> +  uint16_t als_raw_value = als_regs[1] << 8 | als_regs[0];
```suggestion
  uint16_t als_raw_value = encode_uint16(als_regs[1], als_regs[0]);
```

2023-12-20 05:16 UTC, jesserockz commented on esphome/components/veml3235/veml3235.cpp
> +#include "esphome/core/log.h"
For `encode_uint16`
```suggestion
#include "esphome/core/helpers.h"
#include "esphome/core/log.h"
```

2023-12-20 10:37 UTC, kbx81 commented on esphome/components/veml3235/veml3235.cpp
> +  } else if (device_id[0] != DEVICE_ID) {
Yes, because according to the [reference manual](https://www.vishay.com/docs/80131/veml3235.pdf) only those eight bits are defined.

2023-12-20 10:39 UTC, kbx81 commented on esphome/components/veml3235/veml3235.cpp
> +  } else if (device_id[0] != DEVICE_ID) {
...ah, but yes, that should be a `uint8_t` then -- good catch...will fix!

2023-12-20 10:41 UTC, kbx81 commented on esphome/components/veml3235/veml3235.h
> +static const uint16_t DEVICE_ID = 0x0035;
```suggestion
static const uint8_t DEVICE_ID = 0x35;
```

2024-01-16 07:53 UTC, jesserockz requested changes
A few minor things below

2024-01-16 07:53 UTC, jesserockz commented on esphome/components/veml3235/sensor.py
> +                cv.one_of(*VEML3235_INTEGRATION_TIMES, lower=True),
```suggestion
                cv.enum(VEML3235_INTEGRATION_TIMES, lower=True),
```

2024-01-16 07:53 UTC, jesserockz commented on esphome/components/veml3235/sensor.py
> +    )
```suggestion
    cg.add(var.set_integration_time(config[CONF_INTEGRATION_TIME]))
```

2024-01-16 07:53 UTC, jesserockz commented on esphome/components/veml3235/veml3235.cpp
> +    if (!refresh_config_reg(true)) {
```suggestion
    if (!this->refresh_config_reg(true)) {
```

2024-01-16 07:53 UTC, jesserockz commented on esphome/components/veml3235/veml3235.cpp
> +    if (!refresh_config_reg()) {
```suggestion
    if (!this->refresh_config_reg()) {
```

2024-01-16 07:53 UTC, jesserockz commented on esphome/components/veml3235/veml3235.cpp
> +      (als_raw_value < UINT16_MAX * auto_gain_threshold_high_)) {
```suggestion
  if ((als_raw_value > UINT16_MAX * this->auto_gain_threshold_low_) &&
      (als_raw_value < UINT16_MAX * this->auto_gain_threshold_high_)) {
```

2024-01-16 08:09 UTC, kbx81 commented on esphome/components/veml3235/veml3235.cpp
> +      (als_raw_value < UINT16_MAX * auto_gain_threshold_high_)) {
Wow...how did I miss these? 🤦🏻 Thank you!

2024-01-17 06:49 UTC, jesserockz approved these changes

2024-01-17 06:50 UTC, merged