icnt86 touch driver
OttoWinter/esphomeyaml pull request #5960
Opened 2023-12-18 10:00 UTC by siemon-geeroms

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-18 10:03 UTC, siemon-geeroms commented on esphome/components/touchscreen/__init__.py
> +        cv.GenerateID(CONF_DISPLAY): cv.use_id(display.DisplayBuffer),
@nielsnl68 why did you change it display.Display? because the touch driver I'm using is for a waveshare epaper display

2023-12-18 10:10 UTC, siemon-geeroms commented on esphome/components/touchscreen/__init__.py
> -    await cg.register_component(var, config)
@nielsnl68 I had to remove this to resolve an issue where he was trying to set the same id for my display and touchsensor. Maybe a config issue on my part?

2023-12-18 10:12 UTC, nielsnl68 commented on esphome/components/touchscreen/__init__.py
> +        cv.GenerateID(CONF_DISPLAY): cv.use_id(display.DisplayBuffer),
Because of the Display is the top level class for controlling your epaper and DisplayBuffer is currently inherent from Display.

2023-12-18 10:20 UTC, siemon-geeroms commented on esphome/components/touchscreen/__init__.py
> +        cv.GenerateID(CONF_DISPLAY): cv.use_id(display.DisplayBuffer),
so do you mean that the class is wrongfully defined for the waveshare component? it now inherits from displaybuffer instead of display? so one of the 2 needs to be changed because now I have compile errors 

```
class WaveshareEPaper : public display::DisplayBuffer,
                        public spi::SPIDevice<spi::BIT_ORDER_MSB_FIRST, spi::CLOCK_POLARITY_LOW,
                                              spi::CLOCK_PHASE_LEADING, spi::DATA_RATE_2MHZ> {
```

2023-12-18 10:21 UTC, nielsnl68 requested changes

2023-12-18 10:21 UTC, nielsnl68 commented on esphome/components/icnt86/touchscreen.py
> +    await touchscreen.register_touchscreen(var, config)
```suggestion
    await touchscreen.register_touchscreen(var, config)
    await i2c.register_i2c_device(var, config)
```
You should remove the `await cg.register_component(var, config)` line here it is already done for you by calling: `await touchscreen.register_touchscreen(var, config)`

2023-12-18 10:21 UTC, nielsnl68 commented on esphome/components/icnt86/touchscreen.py
> +    .extend(cv.COMPONENT_SCHEMA)
```suggestion
```
Will be added by `touchscreen.TOUCHSCREEN_SCHEMA`

2023-12-18 10:21 UTC, nielsnl68 commented on esphome/components/touchscreen/__init__.py
> -    await cg.register_component(var, config)
As i suggested above. You can omit the `await cg.register_component(var, config)` in your own component. 
All is controlled in the **touchscreen** component.

2023-12-18 14:53 UTC, siemon-geeroms commented
@nielsnl68 what is the purpose of the following code in the function set_raw_touch_position_:

```
  tp.x = (uint16_t) ((int) x * this->get_width_() / 0x1000);
  tp.y = (uint16_t) ((int) y * this->get_height_() / 0x1000); 
```

in my case no further manipulations should be done on the x and y coordinates

2023-12-28 10:18 UTC, siemon-geeroms commented
> @nielsnl68 what is the purpose of the following code in the function set_raw_touch_position_:
> 
> ```
>   tp.x = (uint16_t) ((int) x * this->get_width_() / 0x1000);
>   tp.y = (uint16_t) ((int) y * this->get_height_() / 0x1000); 
> ```
> 
> in my case no further manipulations should be done on the x and y coordinates

@nielsnl68 can you please comment, because I think I'm overlooking something, I don't want to just remove this code, thanks!

2024-04-02 09:04 UTC, nielsnl68 requested changes
Here are my findings.

2024-04-02 09:04 UTC, nielsnl68 commented on esphome/components/icnt86/icnt86.cpp
> +    for (UBYTE i = 0; i < touch_count; i++) {
```suggestion
    for (uint8_t i = 0; i < touch_count; i++) {
```
please use uint8_t or uint16_t instead of UBYTE and UWORD etc or in this case you can use `auto` here.

2024-04-02 09:04 UTC, nielsnl68 commented on esphome/components/icnt86/icnt86.cpp
> +      UWORD touch_evenid = buf[6 + 7 * i];
```suggestion
      uint16_t x = ((uint16_t) buf[2 + 7 * i] << 8) + buf[1 + 7 * i];
      uint16_t y = ((uint16_t) buf[4 + 7 * i] << 8) + buf[3 + 7 * i];
      uint16_t p = buf[5 + 7 * i];
      uint16_t touch_evenid = buf[6 + 7 * i];
```

2024-04-02 09:04 UTC, nielsnl68 commented on esphome/components/icnt86/icnt86.cpp
> +      }
```suggestion
      this->add_raw_touch_position_(touch_evenid, x, y, p);
```
this is handled by the touchscreen class.

2024-04-02 09:04 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
Please dont change the touchscreen class files. Just because your component does not need the functionality.
When there is a bug. Make an bug report/ issue and i will fix the issue for you.

2024-04-02 09:04 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.h
Please dont change the touchscreen class files. Just because your component does not need the functionality.
When there is a bug. Make an bug report/ issue and i will fix the issue for you.

2024-04-02 09:25 UTC, siemon-geeroms commented on esphome/components/icnt86/icnt86.cpp
> +      }
@nielsnl68 I had to do this because the touch controller keeps on reporting 1 touch count when reading out the I2C register when the timeout has passed, do I do something wrong when reading/writing to the register? without this code he loops endlessly now

2024-04-02 09:48 UTC, nielsnl68 commented on esphome/components/icnt86/icnt86.cpp
> +      }
The code looks okay to me. Do you mean that it also report 1 after you released the touch?
lets talk here: https://discord.com/channels/429907082951524364/1076516361011998761

2025-06-01 18:07 UTC, Coornh commented
Thank you @siemon-geeroms for the icnt86 touch driver, it got my 2.9 inch Touch E-Ink E-Paper Display working on a RP2040.
When only importing the icnt86 class it indeed keeps on reporting the first touch (resulting in the on_touch event triggered only once after boot). By also including the touchscreen class it works perfectly!
```
external_components:
  - source: github://pr#5960
    components: [ icnt86, touchscreen ]
```
Is there any prospect of this request being merged? If I can help with some testing I'd be happy to do so.

2025-10-18 00:49 UTC, closed without merging