try to set the volume higher.
OttoWinter/esphomeyaml pull request #5968
Opened 2023-12-19 20:53 UTC by nielsnl68

# What does this implement/fix?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

2023-12-20 00:01 UTC, jesserockz reviewed
I have not tested this yet, but should this be a config option like volume between 0-10 etc that maps to bigger values?

2023-12-20 00:06 UTC, nielsnl68 commented
> I have not tested this yet, but should this be a config option like volume between 0-10 etc that maps to bigger values?

Yes, but i need to figure out what the high and low values should be.

2023-12-20 00:13 UTC, jesserockz commented
> Yes, but i need to figure out what the high and low values should be.

True...haha

2023-12-20 20:53 UTC, edwardtfn commented
Could this be like a `volume_gain` argument on the rtttl settings?

Something like:

```yaml
rtttl:
  output: rtttl_out
  id: my_rtttl
  gain: 2
```
Or:
```yaml
rtttl:
  output: rtttl_out
  id: my_rtttl
  gain: 0.5
```
So you multiply 8192 by the gain, which will be float, with `1` as default or not used and limited by something like `0` to `10` (I haven't tested).

2023-12-21 03:40 UTC, nielsnl68 commented
> Could this be like a `volume_gain` argument on the rtttl settings?
> 
> Something like:
> 
> ```yaml
> rtttl:
>   output: rtttl_out
>   id: my_rtttl
>   gain: 2
> ```
> 
> Or:
> 
> ```yaml
> rtttl:
>   output: rtttl_out
>   id: my_rtttl
>   gain: 0.5
> ```
> 
> So you multiply 8192 by the gain, which will be float, with `1` as default or not used and limited by something like `0` to `10` (I haven't tested).
> 
> My point is more that naming `gain` makes more sense than `volume` in this case.

I think this is the way to go.

2023-12-25 05:15 UTC, nielsnl68 commented
Okay @edwardtfn, @jesserockz  i have added the `gain` option it will be a value between 0.1 to 1. And will be default set to 0.5.

2024-01-09 00:57 UTC, jesserockz requested changes

2024-01-09 00:57 UTC, jesserockz commented on esphome/components/rtttl/__init__.py
> +            cv.Optional(CONF_GAIN, default="0.5"): cv.float_range(0.1, 1),
I feel like this would be better as a `cv.percentage` which is a little more user friendly?

Forcing a user to enter a 0.x number as a config doesnt really make sense.

2024-01-09 00:57 UTC, jesserockz commented on esphome/components/rtttl/rtttl.cpp
> +      uint16_t devision = ((this->samples_count_ << 10) / this->samples_per_wave_) + 1;
```suggestion
      uint16_t division = ((this->samples_count_ << 10) / this->samples_per_wave_) + 1;
```

2024-01-09 00:57 UTC, jesserockz commented on esphome/components/rtttl/rtttl.cpp
> +      ESP_LOGD(TAG, "play time old: %d div: %d new: %d %d", x, devision, this->samples_count_, this->samples_per_wave_);
```suggestion
      this->samples_count_ = (division * this->samples_per_wave_);
      ESP_LOGD(TAG, "play time old: %d div: %d new: %d %d", x, division, this->samples_count_, this->samples_per_wave_);
```

2024-01-09 00:57 UTC, jesserockz commented on esphome/components/rtttl/rtttl.h
> +  double gain_{0.5};
We try to use floats instead of doubles
```suggestion
  float gain_{0.5f};
```

2024-01-09 00:57 UTC, jesserockz commented on esphome/components/rtttl/rtttl.h
> +  }
This could also use `clamp` from `helpers.h`
```suggestion
  void set_gain(float gain) {
    if (gain < 0.1f)
      gain = 0.1f;
    if (gain > 1.0f)
      gain = 1.0f;
    this->gain_ = gain;
  }
```

2024-01-09 01:19 UTC, nielsnl68 commented on esphome/components/rtttl/__init__.py
> +            cv.Optional(CONF_GAIN, default="0.5"): cv.float_range(0.1, 1),
```suggestion
            cv.Optional(CONF_GAIN, default="0.5"): cv.percentage,
```

2024-02-19 01:28 UTC, jesserockz requested changes
A couple of things below, and also can you please update the PR title and description and also add a docs PR for the new config?

Cheers
Jesse

2024-02-19 01:28 UTC, jesserockz commented on esphome/components/rtttl/rtttl.cpp
> +    ESP_LOGI(TAG, "playing note: %d for %dms", note, this->note_duration_);
Should this log level be reverted?

2024-02-19 01:28 UTC, jesserockz commented on esphome/components/rtttl/__init__.py
> +            cv.Optional(CONF_GAIN, default="0.6"): cv.percentage,
The default here should at east match what you have in the header file: https://github.com/esphome/esphome/pull/5968/files#diff-606929f046de6c81e59c42cfe6bdadfb235f8ea671634c1cec4090ec3dafed95R70

2024-02-20 01:12 UTC, nielsnl68 commented on esphome/components/rtttl/rtttl.h
> +  float gain_{0.5f};
```suggestion
  float gain_{0.6f};
```

2024-02-20 01:14 UTC, nielsnl68 commented on esphome/components/rtttl/__init__.py
> +            cv.Optional(CONF_GAIN, default="0.6"): cv.percentage,
Done, by updating the header file

2024-02-20 01:14 UTC, nielsnl68 commented on esphome/components/rtttl/rtttl.cpp
> +    ESP_LOGI(TAG, "playing note: %d for %dms", note, this->note_duration_);
```suggestion
    ESP_LOGVV(TAG, "playing note: %d for %dms", note, this->note_duration_);
```

2024-02-20 01:17 UTC, nielsnl68 commented
Thanks for the review @jesserockz. i resolved the issues you reported

2024-02-27 13:04 UTC, nielsnl68 commented
> A couple of things below, and also can you please update the PR title and description and also add a docs PR for the new config?
> 
> Cheers Jesse

I have updated the documentation now.

2024-02-27 19:11 UTC, jesserockz requested changes

2024-02-27 19:11 UTC, jesserockz commented on esphome/components/rtttl/__init__.py
> +        cg.add(var.set_gain(config[CONF_GAIN]))
```suggestion
    cg.add(var.set_gain(config[CONF_GAIN]))
```

2024-02-27 20:49 UTC, jesserockz approved these changes

2024-02-27 22:31 UTC, merged