[Touchscreen] Add expire of touch record.
OttoWinter/esphomeyaml pull request #5986
Opened 2023-12-21 20:50 UTC by Fabian-Schmidt

# What does this implement/fix?

I observed an issue while using touchscreen `lilygo_t5_47`. A touch event was fired once on the first touch, but no release or new touch events were fired.

The issue is when interrupt is used for touchscreen i2c handling. On touch release the `this->store_.touched` is no longer set inside the `loop()` function. Therefore `send_touches_` is never called to release the touch.

Added logic into the `loop()` that a touch event expires when not found by touchscreen for ~250ms.

Calling `update_touches` more frequently is not an option. As when requesting data via i2c without an event (indicated by interrupt) will result in no detected touches.

This is a regression of PR https://github.com/esphome/esphome/pull/4596.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
touchscreen:
- platform: lilygo_t5_47
  interrupt_pin: GPIO47
  address: 0x5A
  on_touch:
    then:
      - logger.log:
          format: "Touch x:%i y:%i"
          args: [ 'touch.x', 'touch.y' ]
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-22 04:32 UTC, nielsnl68 approved these changes

2023-12-22 04:42 UTC, clydebarrow commented
Isn't this an issue specific to the particular touch controller, and thus should be dealt with in that component, not the top-level touchscreen component?

2023-12-22 05:02 UTC, nielsnl68 commented
> Isn't this an issue specific to the particular touch controller, and thus should be dealt with in that component, not the top-level touchscreen component?

No, imho, the particular touch controller should only delver the touches, all logic should be handled in the top-level touchscreen component.

2023-12-22 05:19 UTC, nielsnl68 commented
That said, i suggest an other approach using a timeout timer. This timer will be (re)set every time touches are found (when `this->is_touched_ `  is set) and will set `this->store_.touched = true;`

2023-12-22 10:20 UTC, clydebarrow commented
> all logic should be handled in the top-level touchscreen component.

Only logic that is common to multiple touchscreens. This is a work-around for a specific chip, and should not be applied to all touchscreens, as it risks incorrectly announcing a release when it has not occurred. If it is to go in common code, it should only be activated if the particular touchscreen requires it.

Part of the problem is that the Lilygo touchscreen is not well documented. There may be other possible solutions, e.g. triggering on both edges of the interrupt signal. I believe I have some of these screens and could do some tests after Christmas.

2023-12-22 10:57 UTC, Fabian-Schmidt commented
> > all logic should be handled in the top-level touchscreen component.
> 
> Only logic that is common to multiple touchscreens. This is a work-around for a specific chip, and should not be applied to all touchscreens, as it risks incorrectly announcing a release when it has not occurred. If it is to go in common code, it should only be activated if the particular touchscreen requires it.
> 
> Part of the problem is that the Lilygo touchscreen is not well documented. There may be other possible solutions, e.g. triggering on both edges of the interrupt signal. I believe I have some of these screens and could do some tests after Christmas.

I agree with the statement that this should only include logic which is common to multiple touchscreens.

Therefore my question: How should a touchscreen driver announce to this component the touch release? A touch screen driver has only the method `add_raw_touch_position_`. So my understanding is it cannot do this. Also the touchscreen driver is only requested to submit touch if the interrupt is fired. Which given the touch was released is not the case.
Also based on what I can see in the other drivers it is common that they all only get events for when a touch happens, but never when a touch is released. Therefore I believe this common touchscreen component is the right place to implement this.

Please correct me if my assumptions are incorrect as I only have access to this one Touchscreen.
But in my testing it was very obvious that it did not work as the `on_touch` `logger` was fired once and no subsequent touch event were logged. Please validate this for another Touchscreen than `lilygo_t5_47`.

```yaml
  on_touch:
    then:
      - logger.log:
          format: "Touch x:%i y:%i"
          args: [ 'touch.x', 'touch.y' ]
```

2023-12-22 11:01 UTC, clydebarrow commented
> How should a touchscreen driver announce to this component the touch release?

When `update_touches()` is called, it either calls `add_raw_touch()` one or more times, or not, and can also set a flag to say "can't update right now." If that flag is not set, and no touches are added, then release is assumed.

2023-12-22 11:03 UTC, Fabian-Schmidt commented
> > How should a touchscreen driver announce to this component the touch release?
> 
> When `update_touches()` is called, it either calls `add_raw_touch()` one or more times, or not, and can also set a flag to say "can't update right now." If that flag is not set, and no touches are added, then release is assumed.

Correct. But `update_touches` is not called because the interrupt is not fired. An interrupt is only fired when new touch data is present. If no touch (or release) occurs no interrupt is fired.

2023-12-22 11:18 UTC, clydebarrow commented
> But `update_touches` is not called because the interrupt is not fired

Sure, so that needs to be triggered one way or another. Either a timeout, or in `update()` perhaps. The previous code just tested the interrupt flag in `loop()`. An optional timeout that forced a call to `update_touches` is probably simplest. I.e. have a property `touch_timeout` or similar that if non-zero triggers a call to `update_touches` if that time has elapsed since the last call to `update_touches`. The default value for the property could be zero, have it overridden when needed. That would keep the logic in common code, add very little extra code, and make it activated only when needed. Make sense?

2023-12-22 12:10 UTC, Fabian-Schmidt commented
Okay I changed the implementation to use a timeout to simulate a touch interrupt 250ms after the last real touch interrupt. This simulated touch is then using the existing code and will ask driver using the `update_touches` method.

Assumption is that every touch driver can fetch data every 250ms.

2023-12-22 17:13 UTC, nielsnl68 requested changes
Perfect. Just on question:
Should we not clear the timeout when no touches where detected? 

We can do that by adding `this->cancel_timeout(TAG);` like:

```c++
void Touchscreen::send_touches_() {
  if (!this->is_touched_) {
    this->cancel_timeout(TAG);
    this->release_trigger_.trigger();
    for (auto *listener : this->touch_listeners_)
      listener->release();
    this->touches_.clear();
  } else {
```

2023-12-22 20:40 UTC, clydebarrow commented
> Assumption is that every touch driver can fetch data every 250ms.

Best not to assume - unless you can test this on every other touchscreen that it will impact, it would be unwise to change the logic for _all_ touchscreens.

I'd like to see a protected property for the delay as discussed above, with default value 0. This could either be set by code in the `lilygo_t5_47` setup, or configured in YAML with a default value for that component.

250ms seems a bit long to me, I suspect that will make button presses e.g. a bit laggy, but I don't know what the right value is, except that in the previous code it basically defaulted to the `loop()` time, which IIRC is something like 30ms. If it's configurable but with a sensible default, then it will work out of the box, but a user can tweak it to suit their preferences if required.

Otherwise heading in the right direction - much cleaner than the first pass.

2023-12-22 20:42 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
> +      this->set_timeout(TAG, 250, [this]() { this->store_.touched = true; });
Is `TAG` the right choice here? What if there is more than one touchscreen configured?

2023-12-23 15:47 UTC, Fabian-Schmidt commented on esphome/components/touchscreen/touchscreen.cpp
> +      this->set_timeout(TAG, 250, [this]() { this->store_.touched = true; });
This is no issue. As the scheduler uses a combination of component and name to find items.

2023-12-23 15:51 UTC, Fabian-Schmidt commented
> 250ms seems a bit long to me, I suspect that will make button presses e.g. a bit laggy,

I don't think this is the case. The 250ms is only for the touch release detection. The binary sensors (and most other logic) is operating on the touch event. So a large timeout has very little impact on the perceived speed.

2023-12-24 10:36 UTC, Fabian-Schmidt commented
As requested I added an additional python configuration value `touch_timeout` which can be set by the touchscreen driver to activate the additional logic.

2023-12-24 11:42 UTC, nielsnl68 approved these changes
Seems to look good to me.

2023-12-24 19:15 UTC, clydebarrow approved these changes

2023-12-24 19:16 UTC, merged

2023-12-24 19:21 UTC, nielsnl68 commented
Dont forget to add the new variable to the documentation.

2023-12-24 19:40 UTC, Fabian-Schmidt commented
> Dont forget to add the new variable to the documentation.

Sure. Do you mind if I wait until <https://github.com/esphome/esphome-docs/pull/3487> is merged? As this is an extensions to these changes.

2023-12-24 20:40 UTC, nielsnl68 commented
you can also send me a PR so i can add it to #3487 directly.