Add feature to reverse char order
OttoWinter/esphomeyaml pull request #5996
Opened 2023-12-22 14:01 UTC by sellerie98

# What does this implement/fix?

This PR adds a feature to optionally reverse the character order.
This is helpful when driving TM1637 modules that have the segment-blocks reversed and display "210543" when "012345" is defined.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/4375

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
display:
    platform: tm1637
    id: tm1637_display
    clk_pin: 16
    dio_pin: 15
    reversed: True
    lambda: |-
      it.print("012345");

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-23 01:47 UTC, jesserockz requested changes

2023-12-23 01:47 UTC, jesserockz commented on esphome/components/tm1637/tm1637.cpp
> +  ESP_LOGCONFIG(TAG, "  Reversed: %d", this->reversed_);
I know the line above is wrong, but %d is for numbers, not booleans. Look for the TRUE FALSE macro in the codebase

2024-12-23 16:37 UTC, github-cyprien commented
Thanks for this feature, working fine for me...
Why the merge is stopped ?

2025-02-11 13:49 UTC, sanchosk commented on esphome/components/tm1637/tm1637.cpp
> +  ESP_LOGCONFIG(TAG, "  Reversed: %d", this->reversed_);
> I know the line above is wrong, but %d is for numbers, not booleans. Look for the TRUE FALSE macro in the codebase

I don't understand the complain here - the setter and getter require boolean as argument and set the value to 0 or 1 - this is a number. So the log will display the value 1 for true a 0 for false. Works the same for inverted as for the newly proposed reversed.
Can this PR move forward? It would really help with the 6 digit 7-segment displays...

2025-08-12 13:20 UTC, sanchosk commented on esphome/components/tm1637/tm1637.cpp
> +  ESP_LOGCONFIG(TAG, "  Reversed: %d", this->reversed_);
Would it help if the line would be changed to 
`ESP_LOGCONFIG(TAG, "  Reversed: %s", this->reversed_ ? "true" : "false");`
It's really annoying to do the reversing in code for every display, having to always use lambda instead just standard yaml...

2025-09-20 11:54 UTC, swoboda1337 commented
Stale, suggested changes not addressed.

2025-09-20 11:54 UTC, closed without merging