Introduce calibration settings to all touchscreen drivers.
OttoWinter/esphomeyaml pull request #5997
Opened 2023-12-22 17:40 UTC by nielsnl68

# What does this implement/fix?

In some cases the touchscreen dimensions where not good setup. This fix introduces 2 fixes. It will take the real dimensions from the display and the option to set the dimensions via the calibration variables in the YAML file.

The XPT2024 will break with this PR. All the ``calibration_*_min`` and ``calibration_*_max`` are now moved to

``` yaml
touchscreen:
  - platform: XPT2024
    calibration:
      x_min: 280
      x_max: 3860
      y_min: 340
      y_max: 3860
```
 
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes:
     https://github.com/esphome/issues/issues/5251
     https://github.com/esphome/issues/issues/5265
     https://github.com/esphome/issues/issues/5249

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

``` yaml
touchscreen:
  - platform: XPT2024
    calibration:
      x_min: 280
      x_max: 3860
      y_min: 340
      y_max: 3860
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2023-12-22 19:53 UTC, guillempages commented on esphome/components/display/display.h
> +  virtual int get_width_internal() = 0;
If those are called "_internal", shouldn't they be better placed on the "protected:" section?

2023-12-22 19:53 UTC, guillempages commented on esphome/components/media_player/media_player.h
>  #include "esphome/core/entity_base.h"
I think the changes to the media_player.h file are unrelated to the touchscreen PR

2023-12-22 19:53 UTC, guillempages commented on esphome/components/touchscreen/__init__.py
> +def calibration_schema(max):
For consistency/clarity, you might want to split max in "max_x" and "max_y". I know it they are always used together to detect whether it has been set or not, but using "max" on both axes feels wrong.

Alternatively, you might want to rename the parameter to "default_value", or "unspecified_value" or similar.

2023-12-22 19:53 UTC, guillempages commented on esphome/components/touchscreen/__init__.py
> +            cv.int_(config[CONF_CALIBRATION][CONF_X_MIN]) != 0
For simplicity/readability, once you know that `CONF_CALIBRATION` exists (i.e. inside the if), you could use a temporary variable `calibration_config` to avoid accessing the dict every time.

2023-12-22 19:53 UTC, guillempages commented on esphome/components/xpt2046/touchscreen/__init__.py
> +                    "Deprecated: use the new Calibration variable"
```suggestion
                    "Deprecated: use the new 'calibration' configuration variable"
```

2023-12-22 19:53 UTC, guillempages commented on esphome/components/xpt2046/touchscreen/__init__.py
> +                    "Deprecated: use the new Calibration variable"
```suggestion
                    "Deprecated: use the new 'calibration:' configuration variable"
```

2023-12-22 19:53 UTC, guillempages commented on esphome/components/xpt2046/touchscreen/__init__.py
> +                    "Deprecated: use the new Calibration variable"
```suggestion
                    "Deprecated: use the new 'calibration' configuration variable"
```

2023-12-22 19:53 UTC, guillempages commented on esphome/components/xpt2046/touchscreen/__init__.py
> +                    "Deprecated: use the new Calibration variable"
```suggestion
                    "Deprecated: use the new 'calibration' configuration variable"
```

2023-12-22 19:53 UTC, guillempages commented on esphome/components/xpt2046/touchscreen/__init__.py
> +                    "Deprecated: use the update_interval variable"
```suggestion
                    "Deprecated: use the 'update_interval' configuration variable"
```

2023-12-22 19:53 UTC, guillempages commented on esphome/components/xpt2046/touchscreen/__init__.py
> +                cv.Optional(CONF_THRESHOLD, default=400): cv.int_range(min=0, max=4095),
I have the feeling the indenting is wrong here

2023-12-22 19:53 UTC, guillempages commented on esphome/components/xpt2046/touchscreen/__init__.py
> +                cv.Optional(
and here

2023-12-22 19:53 UTC, guillempages commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
Is this really related to this PR?

2023-12-22 19:57 UTC, nielsnl68 commented on esphome/components/display/display.h
> +  virtual int get_width_internal() = 0;
I made them public to allow access from the touchscreen drivers,

2023-12-22 20:02 UTC, nielsnl68 commented on esphome/components/touchscreen/__init__.py
> +def calibration_schema(max):
I thought about adding *max_x* and *max_y* as you suggesting. But it is now only used for the XPT2046 and there both are set to 4095. In all other cases the the *max* values should be **0** at all times.

Renaming it to "default_max_values" is good idea.

2023-12-22 20:19 UTC, guillempages commented on esphome/components/display/display.h
> +  virtual int get_width_internal() = 0;
Sure, but then maybe they should be renamed ;-)

2023-12-22 20:20 UTC, nielsnl68 reviewed
thanks @guillempages for the quick review. There is one comment still open. When you give me a thumps-up then i can mark that one resolved as well.

2023-12-22 20:20 UTC, nielsnl68 commented on esphome/components/media_player/media_player.h
>  #include "esphome/core/entity_base.h"
Yep you are right. Did not see it slipping into a commit

2023-12-22 20:20 UTC, nielsnl68 commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
to what do you refer to?

2023-12-22 20:25 UTC, guillempages commented on esphome/components/xpt2046/touchscreen/xpt2046.cpp
The rest of the PR is basically handling the new get_width_internal() changes, or the global calibration options.
Removing the `get_setup_priority()` method seems unrelated to the rest of the PR. IMHO this would be better handled in a separate PR, so that the reasons for that can be better explained, and (unlikely but...) if needed, it can be reverted separately.

(I normally like PRs that focus on once issue, and not generic PRs that happen to change many things in a component).

2023-12-22 22:12 UTC, clydebarrow commented
Looks like #5999 and this are doing the same thing.

2023-12-23 00:05 UTC, nielsnl68 commented
> Looks like #5999 and this are doing the same thing.

There should be a difference, @guillempages made an attempt to allow to use the transform settings from the display and use that for the touchscreen.

2023-12-23 19:52 UTC, clydebarrow commented
Split the tt21100 fix into a separate PR and I can approve it straight away.

2023-12-31 01:39 UTC, clydebarrow commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
Why introduce an extra method here, why not just rename `get_width_internal()` which is already public?

2023-12-31 01:55 UTC, nielsnl68 commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
Because then we need to change all display drivers as well. My intension was to use the internal version.  But that was not good enough. And you and @guillempages suggested to create an other set of methods to get the right values.
So i did that now. we have discussed it very well on discord.

2023-12-31 05:51 UTC, clydebarrow commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
Yeah, but we don't want two sets of functions with different names doing the same thing (not public ones anyway) - that will just lead to confusion. Either stick with the original names, or replace them.

2024-01-03 22:48 UTC, clydebarrow commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
So in your code, you're using `get_internal_width()` in some places, and `get_native_width()` in others, so confusion has already set in. I recommend removing the `native` versions and just sticking with the `internal` as before. The name is not critical, since they're not user-exposed anyway.

Other than that, it looks OK. If you fix up those functions I'll have a final look and it should be good to go.

2024-01-03 23:09 UTC, nielsnl68 commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
> So in your code, you're using `get_internal_width()` in some places, and `get_native_width()` in others, so confusion has already set in. I recommend removing the `native` versions and just sticking with the `internal` as before. The name is not critical, since they're not user-exposed anyway.

Good point going to fix that.
> 
> Other than that, it looks OK. If you fix up those functions I'll have a final look and it should be good to go.

🤩 let me know how it go's now. Sorry that i takeover your PR :D

2024-01-07 16:14 UTC, nagyrobi commented
Trying on a [Lanbon L8](https://deploy-preview-622--esphome-devices.netlify.app/devices/Lanbon-L8-LCD-Switch).
Intention is to use with LVGL (migrate from OpenHASP).

```
  - source: github://pr#6049
    refresh: 1440min
    components: [ touchscreen ]
  - source: github://pr#5997
    refresh: 1440min
    components: [ touchscreen, ft63x6 ]
  - source: github://pr#6055
    refresh: 1440min
    components: [ ft63x6 ]

touchscreen:
  - platform: ft63x6
    id: tft_touch
    display: tft_display
    calibration:
#      x_min: 0
      x_max: 240
#      y_min: 0
      y_max: 320
    on_touch:
      - lambda: |-
            ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                touch.x,
                touch.y,
                touch.x_raw,
                touch.y_raw
                );
```

Results in:
```
src/esphome/components/touchscreen/touchscreen.cpp: In member function 'virtual void esphome::touchscreen::Touchscreen::call_setup()':
src/esphome/components/touchscreen/touchscreen.cpp:20:44: error: 'class esphome::display::Display' has no member named 'get_native_width'
   20 |     this->display_width_ = this->display_->get_native_width();
      |                                            ^~~~~~~~~~~~~~~~
src/esphome/components/touchscreen/touchscreen.cpp:21:45: error: 'class esphome::display::Display' has no member named 'get_native_height'
   21 |     this->display_height_ = this->display_->get_native_height();
      |                                             ^~~~~~~~~~~~~~~~~
```

Otherwise the device works fine, if I ignore the PRs related to ft63x6, remove calibration config and change straight in its code
```
  this->x_raw_max_ = 240;
  this->y_raw_max_ = 320;
 ```
 compiles and works correctly.

2024-01-07 16:23 UTC, guillempages commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
> So in your code, you're using `get_internal_width()` in some places, and `get_native_width()` in others, so confusion has already set in. I recommend removing the `native` versions and just sticking with the `internal` as before. The name is not critical, since they're not user-exposed anyway.

Why not keep the "internal" as protected, so that they can still be used by the components, but use the "native" for the touchscreen? Somehow I find the "internal" ones should not be used by "other" components or be made public.

2024-01-07 23:42 UTC, nielsnl68 commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
> Why not keep the "internal" as protected, so that they can still be used by the components, but use the "native" for the touchscreen? Somehow I find the "internal" ones should not be used by "other" components or be made public.

That is what it should have been, i just forgot those to changes.

2024-01-08 00:33 UTC, nielsnl68 commented
@nagyrobi to fix your issue you need to change the `external_component`:
```yaml
external_component:
  - source: github://pr#5997
    refresh: 1440min
    components: [ display, touchscreen, ft63x6 ]

2024-01-08 04:59 UTC, clydebarrow requested changes

2024-01-08 04:59 UTC, clydebarrow commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
I'd suggest making this virtual so it can be overridden in subclasses.

2024-01-08 04:59 UTC, clydebarrow commented on esphome/components/display/display.h
> +  virtual int get_height_internal() = 0;
Since these are for internal use only, they should now be protected, and thus renamed to `get_width_internal_()`

2024-01-09 00:50 UTC, jesserockz commented on esphome/components/display/display.h
> +  virtual int get_height_internal() = 0;
virtual protected functions do not use the `_` suffix

2024-01-09 00:56 UTC, clydebarrow commented on esphome/components/display/display.h
> +  virtual int get_height_internal() = 0;
Maybe that should be spelt out in https://esphome.io/guides/contributing.html#codebase-standards then.

2024-01-15 01:18 UTC, jesserockz commented on esphome/components/display/display.h
> +  virtual int get_height_internal() = 0;
clang will ping you for it if you add the suffix too I believe =)

2024-01-16 22:26 UTC, clydebarrow requested changes

2024-01-16 22:26 UTC, clydebarrow commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
I'm still unhappy with having two sets of methods doing exactly the same thing with no obvious rationale for the duplication.

2024-01-16 22:26 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
> +    touches.push_back(tp.second);
Touches that have been released should be filtered out here.

2024-01-16 22:26 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
>    tp.x_raw = x_raw;
Consider this scenario - two touches are registered, then one is lifted. Now another finger touches the screen in a different place and send with the same ID as the previously lifted touch. Since the touches map will still contain the original second touch, with state RELEASED, it will now be put in state UPDATED, even though it's actually a new touch and so should be in state PRESSED.

I think that once a touchpoint goes into state RELEASED, it should be removed from the touches map, so any new touch with the same ID will be recognised as a new touch, not a continuation of the previous one.

2024-01-16 22:26 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
> +    tp.state |= STATE_CALIBRATE;
What's the meaning of STATE_CALIBRATE and where is it used?

2024-01-18 12:03 UTC, nielsnl68 commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
sorry i do not see the need for that. You can override the `get_width_internal()` already when you need.

2024-01-18 12:03 UTC, nielsnl68 commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
> I'm still unhappy with having two sets of methods doing exactly the same thing with no obvious rationale for the duplication.

How about updating the `get_height();` and `get_width();` by adding a default *boolean* parameter when set true it will return the **native** value otherwise it is as default behavier?

2024-01-18 12:03 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
>    tp.x_raw = x_raw;
The way I designed it is well thought out, by me. I have been thinking about the best solution for sometime now.
And I also have toughed about the solution you suggest, but then the user needs to check the touch ID's every time  an on_update is fired. Imho an lot of extra logic that is now prevented.

Say you created an zoom gesture that uses only 2 touches. at some point you touching 3 point on the screen (no zoom happens anymore). 
- In your solution, when you release point 2; the zoom gesture sees 2 points again and start zooming again.  Or the gesture needs to store the ID's that where uses when it started zooming. 

- In my solution the number of points stay's the same (3 Points) until all touches are removed. as long there are 2 touches the gesture needs only to validate the state =0 to enable the zoom function.

> I think that once a touchpoint goes into state RELEASED, it should be removed from the touches map, so any new touch with the same ID will be recognised as a new touch, not a continuation of the previous one.

The handling of retouching the screen is still an open issue. Until i know more how Touchscreen drivers handle this kind of touch sequence i cant yet handle this correctly. 

I belief you have a display where you can have multiple touches is it not? Please provide me with a log where i can see how it is handling retouching etc. 

Because there is no gesture's made i do not find it a big issue for now.

2024-01-18 12:07 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
> +    tp.state |= STATE_CALIBRATE;
This is a new flag that you can use in your yaml script to see of you need to calibrate the touchscreen or not.
And tells that the **x** and **y** are invalid.

2024-01-28 10:24 UTC, nielsnl68 commented
- The red flag is because i made this PR useable for current version ESPHome users.
You should be able to fix most of the issues with you touchscreen with this PR.
Add the following part in your YAML file.

```yaml
external_components:
  - source: github://pr#5997
    components: [ display, touchscreen, YourTouchScreen]
    refresh: 0sec
``` 
> Replace "`YourTouchScreen`" with the name of the used touchscreen.

2024-02-11 21:57 UTC, nagyrobi commented
This PR works nicely for me on Lanbon L8 with `ft63x6`.

2024-02-11 22:01 UTC, nagyrobi approved these changes

2024-02-13 00:06 UTC, kbx81 commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
Any decision/resolution on this? 🙂

2024-02-13 00:12 UTC, nielsnl68 commented on esphome/components/display/display.h
> +  int get_native_width() { return this->get_width_internal(); }
It will be resolved in a next PR. For the new version of the ili9xxx component. 
https://github.com/nielsnl68/esphome/tree/nvds-displaydriver imm this will become THE native platform component between all the graphical display drivers and the display component.

2024-02-13 09:40 UTC, clydebarrow requested changes
The changes to `display` relating to anti-aliased fonts should be removed from this PR and left for #6198.

2024-02-13 15:11 UTC, nielsnl68 commented
> The changes to `display` relating to anti-aliased fonts should be removed from this PR and left for #6198.

I have remove those.

2024-02-21 01:01 UTC, jesserockz submitted a review, later dismissed

2024-02-21 01:01 UTC, jesserockz commented on esphome/components/xpt2046/test.esp32.yaml
Please dont add test files into the component folders.
If you want to add a test file for this, it needs to go into `/tests/components/xxxx/test.xxx.yaml`

2024-02-21 01:01 UTC, jesserockz commented on esphome/components/tt21100/test.esp32.yaml
Same here

2024-02-21 01:01 UTC, jesserockz commented on tests/test13.yaml
Given the new yaml test setup, we dont want any new test yaml files in here please

2024-02-21 01:33 UTC, nielsnl68 commented
@clydebarrow Could you please approve this PR, thanks.

2024-02-21 02:03 UTC, kbx81 requested changes, later dismissed
Comments about tests

2024-02-21 02:03 UTC, kbx81 commented on tests/components/ft63x6/test.esp32.yaml
> +  level: verbose
In light of the new testing frameworks, please do not include any of this in the test yaml files.

Tests should now include **only** the component itself and components it depends on (such as `spi`, `display`, etc.). Do not include anything that isn't strictly required to compile the component the test is for -- it just makes the test take longer to complete.

2024-02-21 02:03 UTC, kbx81 commented on tests/components/tt21100/test.esp32.yaml
Same as above

2024-02-21 02:03 UTC, kbx81 commented on tests/components/xpt2046/test.esp32.yaml
Here, too

2024-02-21 20:06 UTC, guillempages reviewed
Left some minor formatting/leg message improvement comments.

Otherwise, looks good to me

2024-02-21 20:06 UTC, guillempages commented on esphome/components/touchscreen/__init__.py
> +# CONF_SWAP_XY = "swap_xy"
Do you still need those here?
```suggestion
```

2024-02-21 20:06 UTC, guillempages commented on esphome/components/touchscreen/__init__.py
> +            raise cv.Invalid("Calibration X values difference must be more then 10")
```suggestion
            raise cv.Invalid("Calibration X values difference must be more than 10")
```

2024-02-21 20:06 UTC, guillempages commented on esphome/components/touchscreen/__init__.py
> +            raise cv.Invalid("Calibration Y values difference must be more then 10")
```suggestion
            raise cv.Invalid("Calibration Y values difference must be more than 10")
```

2024-02-21 20:06 UTC, guillempages commented on esphome/components/touchscreen/__init__.py
> +            cv.Optional(CONF_X_MIN, default=0): cv.int_range(min=0, max=4095),
Is there a reason why the minimum cannot be greater than 4095? Are you sure that there are no strange devices out there that have weird values here?
(Comment valid for all 4 values)

2024-02-21 20:06 UTC, guillempages commented on esphome/components/touchscreen/touchscreen.cpp
> +    ESP_LOGW(TAG, "Touch Polling Stopped !!!");
Is this really a warning? Wouldn't this be a "normal" use case, and thus just a LOGI would be enough?
Also, do you really need all three exclamation marks? ;-)

2024-02-21 23:46 UTC, nielsnl68 reviewed
Thanks @guillempages for reviewing and give your opinions. 
I changed them as suggested.

2024-02-21 23:46 UTC, nielsnl68 commented on esphome/components/touchscreen/__init__.py
> +            cv.Optional(CONF_X_MIN, default=0): cv.int_range(min=0, max=4095),
I get where you saying and but for now i do not have seen a touchscreen driver that needs more then 4095 value.
As soon there is one we could change at that point is it not? The value is not set in stone.

2024-02-21 23:46 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
> +    ESP_LOGW(TAG, "Touch Polling Stopped !!!");
```suggestion
    ESP_LOGW(TAG, "Touch Polling Stopped. You can safely remove the "update_interval:" variable from the YAML file.");
```
You could see this as a yaml configuration problem where the user should have remove the `update_interval:` variable.

2024-02-21 23:50 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
> +    ESP_LOGW(TAG, "Touch Polling Stopped. You can safely remove the "update_interval:" variable from the YAML file.");
```suggestion
    ESP_LOGW(TAG, "Touch Polling Stopped. You can safely remove the 'update_interval:' variable from the YAML file.");
```

2024-02-28 02:22 UTC, clydebarrow approved these changes

2024-02-28 02:42 UTC, merged