Add Electra RC3 protocol AC support
OttoWinter/esphomeyaml pull request #6000
Opened 2023-12-22 22:52 UTC by roygolds

# What does this implement/fix?

This PR is adding the Electra's RC3 IR protocol, to the IR Remote Climate component.
This will add the ability to control Electra's ACs.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: bedroom-ac

esp8266:
  board: d1_mini

# Enable logging
logger:
web_server:

# Enable Home Assistant API
api:

ota:

captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%

climate:
  - platform: electra_rc3_ir
    name: "Bedroom AC"

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-15 19:24 UTC, omersht commented
I know it’s not “official” but I have made an external component, with receiving support, https://github.com/omersht/ElectraEspHome.

2025-04-29 02:25 UTC, jesserockz requested changes

2025-04-29 02:25 UTC, jesserockz commented on esphome/components/electra_rc3_ir/electra_rc3_ir.cpp
> +// using climate::ClimateFanMode;
No commented out code
```suggestion
```

2025-04-29 02:25 UTC, jesserockz commented on esphome/components/electra_rc3_ir/electra_rc3_ir.cpp
> +// }
```suggestion
```

2025-04-29 02:25 UTC, jesserockz commented on esphome/components/electra_rc3_ir/electra_rc3_ir.h
> +  // void control(const climate::ClimateCall &call) override;
```suggestion
```

2025-04-29 02:26 UTC, jesserockz approved these changes, later dismissed

2025-05-03 19:43 UTC, roygolds commented on esphome/components/electra_rc3_ir/electra_rc3_ir.cpp
> +// }
@jesserockz, why did you remove this function, it supposed to override a case where the control is changed when the AC is off, w/o this the AC will power on when any other control is changed.
If you did it for a reason, let me understand why, and if needed I can test this with my AC. (This code is working with y AC for more than a year now)

2025-05-31 12:38 UTC, roygolds commented
Hi @jesserockz,

Tests added, and the code is updated with all recent code in dev.
It is working with my AC.

Please review and merge.

Thanks,
Roy.

2025-08-09 17:11 UTC, roygolds commented
Hi @jesserockz, could you please review this PR?

2025-09-18 18:22 UTC, swoboda1337 commented on esphome/components/electra_rc3_ir/electra_rc3_ir.cpp
> +// }
Why is it commented out?

2025-09-18 18:31 UTC, roygolds commented on esphome/components/electra_rc3_ir/electra_rc3_ir.cpp
> +// }
It was a test that I tried (and didn't work). I removed the commented code in the final version.

2025-10-03 21:55 UTC, swoboda1337 requested changes

2025-10-03 21:55 UTC, swoboda1337 commented on esphome/components/electra_rc3_ir/climate.py
> +CONFIG_SCHEMA = climate_ir.climate_ir_with_receiver_schema(ElectraRC3IR)
You are not using the receive part
```suggestion
CONFIG_SCHEMA = climate_ir.climate_ir_schema(ElectraRC3IR)
```

2025-10-03 21:55 UTC, swoboda1337 commented on esphome/components/electra_rc3_ir/electra_rc3_ir.h
> +  bool on_receive(remote_base::RemoteReceiveData data) override;
```suggestion
```

2025-10-03 21:55 UTC, swoboda1337 commented on esphome/components/electra_rc3_ir/electra_rc3_ir.cpp
> +bool ElectraRC3IR::on_receive(remote_base::RemoteReceiveData data) { return false; }
```suggestion
```

2025-10-03 21:55 UTC, swoboda1337 commented on esphome/components/electra_rc3_ir/electra_rc3_ir.h
> +const uint8_t ELECTRA_RC3_TEMP_MAX = 30;
```suggestion
constexpr uint8_t ELECTRA_RC3_TEMP_MIN = 16;
constexpr uint8_t ELECTRA_RC3_TEMP_MAX = 30;
```

2025-10-03 21:55 UTC, swoboda1337 commented on esphome/components/electra_rc3_ir/electra_rc3_ir.cpp
> +  data.sleep = (this->preset == climate::CLIMATE_PRESET_SLEEP) ? 1 : 0;
```suggestion
  auto temp = (uint8_t) roundf(this->target_temperature);
  temp = std::min(ELECTRA_RC3_TEMP_MAX, temp);
  temp = std::max(ELECTRA_RC3_TEMP_MIN, temp);
  
  data.temperature = temp - 15;
  data.sleep = (this->preset == climate::CLIMATE_PRESET_SLEEP) ? 1 : 0;
```

2025-10-03 21:55 UTC, swoboda1337 commented on esphome/components/remote_base/electra_rc3_protocol.cpp
> +static const uint16_t ELECTRA_RC3_REPEATS = 3;
Use constexpr here?

2025-10-03 21:55 UTC, swoboda1337 commented on esphome/components/remote_base/electra_rc3_protocol.cpp
> +    for (int bit_index = ELECTRA_RC3_NUM_BITS - 1; bit_index >= 0; --bit_index) {
```suggestion
    for (int32_t bit_index = ELECTRA_RC3_NUM_BITS - 1; bit_index >= 0; --bit_index) {
```

2025-10-03 21:55 UTC, swoboda1337 commented on esphome/components/remote_base/electra_rc3_protocol.cpp
> +        }
It seems this complicated bit of code is to avoid doing multiple spaces and marks next to each other. That is perfectly fine though. You can do two spaces or two marks in a row (many other protocols do that). Maybe this can be simplified? Is there a bug with the last bit?

2025-10-03 21:55 UTC, swoboda1337 commented on esphome/components/electra_rc3_ir/__init__.py
Should this be called electra_rc3 instead of electra_rc3_ir?

2026-01-10 00:50 UTC, closed without merging