Make `pulse_meter` PULSE filter report the pulse as soon as it can
OttoWinter/esphomeyaml pull request #6014
Opened 2023-12-24 03:00 UTC by TrentHouliston

# What does this implement/fix?

The pulse meter filter would only publish the pulses when the next pulse came through when in PULSE mode.
This caused some strange behaviour when the pulses were slow as features like timeout would happen at unexpected times as even though a pulse had happened since the next pulse hadn't yet it was not counted.

This change allows the main loop to "peek" the filter state to see if it can count the incomplete pulse and repay that pulse count later when the interrupt catches up.

This also resulted in some refactoring to the pulse filter to enable this which simplified it significantly in the process.
I've also added a markdown file to help describe the pulse filter so that myself and others are not as confused by it in the future.

Since almost all of my devices use higher frequencies and the EDGE filter mode, if someone who uses some of these slower pulse rate devices could test this that would be appreciated.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-10 22:19 UTC, TrentHouliston commented
Should be a more complete fix for #5813 as described in that PR

2024-04-30 22:02 UTC, jesserockz commented on esphome/components/pulse_meter/pulse_filter.md
While I appreciate you putting the effort into this file (It looks great btw), we do not want "documentation" throughout the esphome codebase in adhoc files. This is what https://esphome/esphome-docs is for.

2024-04-30 22:05 UTC, jesserockz requested changes

2024-04-30 22:05 UTC, jesserockz commented on esphome/components/pulse_meter/pulse_meter_sensor.h
> +#include <variant>
Is this used?

2024-05-01 00:08 UTC, TrentHouliston commented on esphome/components/pulse_meter/pulse_meter_sensor.h
> +#include <variant>
It is not! I couldn't manage to get it to compile and work on the ESPs, I was trying to avoid having to have an object allocated for each filter when only one was used.

Looks like I left the header behind

2024-05-07 22:13 UTC, jesserockz approved these changes

2024-05-07 22:13 UTC, merged