dimmer: Add OXT 1-channel dimmer type
OttoWinter/esphomeyaml pull request #6021
Opened 2023-12-26 22:10 UTC by michau-krakow

# What does this implement/fix?

Adding support for another type of Tuya 1-ch dimmers branded OXT 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3498

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [x] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: dimmer
  comment: OXT 1-ch dimmer

bk72xx:
  board: cb3s # Using original CB3S module by Tuya, can also be replaced with other pin-compatible

# Disable UART logging - we need UART to talk to dimming MCU
logger:
  baud_rate: 0

uart:
  tx_pin: GPIO11 # rx_pin is not required (not used)
  baud_rate: 9600

light:
  - platform: oxt_dimmer
    id: lamp1
    name: lamp1
    sensing_pin:
      number: GPIO08
      inverted: true
      mode: input_pullup
    min_value: 0
    max_value: 255
    default_transition_length: 1s # tranistions would work!
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-11 07:51 UTC, jesserockz requested changes
All PRs are to target `dev` please

2024-01-11 16:43 UTC, michau-krakow commented
> All PRs are to target `dev` please

Bo problem. Rebased on top of `dev` and updated PR target.

2024-02-07 13:40 UTC, michau-krakow commented
@jesserockz I there anything I can help with to merge this? I appreciate you have lots of other task but this is 3 weeks since I updated it. 
Also, I can still see "Changes requested" message and the comment from bot says to use 'Ready for review' button when ready but I does not seem to have that button... Perhaps you need to mark it done?

2024-03-16 08:58 UTC, michau-krakow commented
@jesserockz it's been another month passed without reply - any commets appreciated.
note https://github.com/esphome/esphome/pull/6021#issuecomment-1886537594 but I have no *Ready for review* button...

2024-03-18 00:56 UTC, jesserockz requested changes
The whole sensing pin part is completely unnecessary. 
The user should just set up a `gpio` `binary_sensor` on that pin number and then they can use automations in YAML to decide to turn on/off the light etc. 

This component should only be concerned with controlling the light.

2024-03-18 00:56 UTC, jesserockz commented on esphome/components/oxt_dimmer/light.py
> +DEPENDENCIES = ["uart", "light"]
Not required for light platform files
```suggestion
DEPENDENCIES = ["uart"]
```

2024-05-20 12:25 UTC, nagyrobi commented
@michau-krakow I tested your component and works! Please make the adjustments Jesse required as this is a very common device.

The [example](https://devices.esphome.io/devices/OXT-1ch-dimmer) should be removed from the devices site until this gets merged. Also, it contains outdated configuration (misses channel).

2026-02-27 22:00 UTC, closed without merging