Add new Component: Ultrasonic Distance Sensor JSN-SR04T
OttoWinter/esphomeyaml pull request #6023
Opened 2023-12-27 09:10 UTC by Mafus1

# What does this implement/fix?

This PR implements support for the ultrasonic distance sensor JSN-SR04T

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** none

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600

sensor:
  - platform: "jsn_sr04t"
    name: "Distance"
    update_interval: 1s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-18 08:37 UTC, jesserockz requested changes

2024-01-18 08:37 UTC, jesserockz commented on esphome/components/jsn_sr04t/jsn_sr04t.cpp
> +      ESP_LOGV(TAG, "Distance from sensor: %f mm, %f m", distance, meters);
```suggestion
    uint16_t distance = encode_uint16(this->buffer_[1], this->buffer_[2]);
    if (distance > 230) {
      float meters = distance / 1000.0f;
      ESP_LOGV(TAG, "Distance from sensor: %" PRIu32 "mm, %.3fm", distance, meters);
```

2024-01-18 08:37 UTC, jesserockz commented on esphome/components/jsn_sr04t/jsn_sr04t.cpp
> +
```suggestion

#include <cinttypes>

```

2024-01-18 08:37 UTC, jesserockz commented on esphome/components/jsn_sr04t/jsn_sr04t.cpp
> +}
Read requests should happen in `update`, and checking for response bytes should happen in the `loop` in case there is a delay receiving the response.
```suggestion
void Jsnsr04tComponent::update() {
  this->write_byte(0x55);
  ESP_LOGV(TAG, "Request read out from sensor");
}
void Jsnsr04tComponent::loop() {
  while (this->available() > 0) {
    uint8_t data;
    this->read_byte(&data);

    ESP_LOGV(TAG, "Read byte from sensor: %x", data);

    if (this->buffer_.empty() && data != 0xFF)
      continue;

    this->buffer_.push_back(data);
    if (this->buffer_.size() == 4)
      check_buffer_();
  }
}
```

2024-01-18 08:37 UTC, jesserockz commented on esphome/components/jsn_sr04t/jsn_sr04t.h
> +  void update() override;
```suggestion
  void update() override;
  void loop() override;
```

2024-01-18 08:38 UTC, jesserockz commented
Additionally to the above, please add this platform to a test YAML.

2024-01-23 08:52 UTC, Mafus1 commented
@jesserockz thanks for reviewing my PR. I hope I have resolved all your change requests. I will switch to ready for review again.

2024-03-24 08:29 UTC, Mafus1 commented
Hi @jesserockz 
Do you still consider merging this PR? The documentation PR has already gone stale.

2024-03-24 22:31 UTC, jesserockz commented
Apologies for the delay @Mafus1. Could you move the code added into `tests/test4.yaml` into a new file located in `tests/components/jsn_sr04t/...`. Take a look at sibling directories there for examples.

2024-03-26 10:39 UTC, Mafus1 commented
@jesserockz I moved the test to `tests/components/jsn_sr04t/...` like you requested. I looked at the `tests/components/a01nyub/...` as an example.

2024-03-26 22:53 UTC, jesserockz commented on esphome/components/jsn_sr04t/jsn_sr04t.cpp
> +      check_buffer_();
```suggestion
      this->check_buffer_();
```

2024-03-26 22:54 UTC, jesserockz approved these changes

2024-03-27 01:14 UTC, merged