web_server_idf: support x-www-form-urlencoded POST requests
OttoWinter/esphomeyaml pull request #6037
Opened 2023-12-29 13:05 UTC by dentra

# What does this implement/fix?

Added support x-www-form-urlencoded POST requests to ESP-IDF web server implementation.
+ small url_encode optimisation to reduce unnecessary memory allocation. 
+ change returning type from size_t to int when requesting vsnprintf for buffer length.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
web_server:
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-09 16:08 UTC, dentra commented
Just a note for next level component upgrade. Multipart support is required for OTA updates from the web browser and now we have a ready made MIT licensed idf-component for parsing multipart post requests: https://github.com/zorxx/multipart-parser

2024-02-07 15:45 UTC, heythisisnate commented
@dentra this looks great! what's the best way to test this?
I'm interested in helping to get HTTP POST OTA updates working on ESP-IDF framework and it looks like this is a foundational piece.

2024-02-08 00:42 UTC, dentra commented
@heythisisnate OTA requires multipart POST, but this PR only add www-form-urlencoded POST.

2024-02-08 00:45 UTC, dentra commented
In the upper comment I mention library to use to implement multipart POST

2024-02-29 02:10 UTC, jesserockz requested changes

2024-02-29 02:10 UTC, jesserockz commented on esphome/components/web_server_idf/web_server_idf.cpp
> +  auto content_type = request_get_header(r, "Conetnt-Type");
Not sure how this was working in your testing...
```suggestion
  auto content_type = request_get_header(r, "Content-Type");
```

2024-02-29 09:38 UTC, dentra commented on esphome/components/web_server_idf/web_server_idf.cpp
> +  auto content_type = request_get_header(r, "Conetnt-Type");
> Not sure how this was working in your testing...

This check is only to forbid multipart requests. My tests using only form-urlencoded request, so they works. Thanks for the typo found!

2024-03-11 00:09 UTC, jesserockz approved these changes

2024-03-11 00:09 UTC, merged