t6615: dump more infos about sensor on startup
OttoWinter/esphomeyaml pull request #6043
Opened 2023-12-31 15:42 UTC by lewurm

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-03 00:29 UTC, tylermenezes commented
This looks fine so far, although I have not been able to test it.

2024-01-03 16:15 UTC, lewurm commented
Thanks for the feedback @tylermenezes.

Alas I don't see those messages on bootup and furthermore, decoding trips over (but recovers thanks to the added mechanism).  I'll need to poke at it more on the weekend.

In general I wanted to see if my sensor is in some weird state, as the measured values didn't make sense for a while.  I guess auto calibration kicked, and now the reported values look plausible again.

![Screenshot 2024-01-03 at 17 14 23](https://github.com/esphome/esphome/assets/75403/7ea1b636-1ea4-427d-add4-606db307944a)

2025-09-20 11:59 UTC, swoboda1337 requested changes

2025-09-20 11:59 UTC, swoboda1337 commented on esphome/components/t6615/t6615.cpp
> +static uint8_t bootup_state = 0;
This has to be part of the class not a global

2025-12-27 00:50 UTC, closed without merging