Touchscreen: Fix multiple release callback bug
OttoWinter/esphomeyaml pull request #6049
Opened 2024-01-01 21:10 UTC by clydebarrow

# What does this implement/fix?

The touchscreen component was sending continuous release callbacks when nothing was pressed.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-01 21:46 UTC, nielsnl68 approved these changes

2024-01-01 22:12 UTC, clydebarrow commented
Found another bug (would only affect multiple touch situation.)

2024-01-01 22:29 UTC, nielsnl68 requested changes

2024-01-01 22:29 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
> +      if (tp.second.state == STATE_PRESSED || tp.second.state == STATE_UPDATED)
Imho, we need to send the release action as well, the using function need to monitor the `state` flag it self to see of the button is still pressed or not. so it can handle the right action.
That said; maybe we need to call `on_update` also when no more touches are registered.

2024-01-02 01:01 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
> +      if (tp.second.state == STATE_PRESSED || tp.second.state == STATE_UPDATED)
> maybe we need to call `on_update` also when no more touches are registered

This^

2024-01-02 01:09 UTC, clydebarrow commented
Hmm, Github is not reflecting my latest commits.

2024-01-02 05:08 UTC, nielsnl68 requested changes

2024-01-02 05:08 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
> +      }
After reading the method again i think we should change a bit more. 
```c++
void Touchscreen::send_touches_() {
  TouchPoints_t touches;
  for (auto tp : this->touches_) {
      touches.push_back(tp.second);
  }
  if (this->need_update_ || ( !this->is_touched_ && this->was_touched_)) {
    this->update_trigger_.trigger(touches);
    for (auto *listener : this->touch_listeners_) {
      listener->update(touches);
    }
  }
  if (!this->is_touched_) {
    if (this->was_touched_) {
      if (this->touch_timeout_ > 0) {
        this->cancel_timeout(TAG);
      }
      this->release_trigger_.trigger();
      for (auto *listener : this->touch_listeners_)
        listener->release();
      this->touches_.clear();
      this->was_touched_ = false;
    }
  } else {
    if (this->first_touch_) {
      TouchPoint tp = this->touches_.begin()->second;
      this->touch_trigger_.trigger(tp, touches);
      for (auto *listener : this->touch_listeners_) {
        listener->touch(tp);
      }
    }
  }
}
```
i'm not 100% happy with this function yet. But it should work, i think.

2024-01-02 05:22 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
> +      }
The problem is that nobody is currently using the multi-touch feature AFAIK, nor do we have a clear specification of how it is expected to work, so randomly tweaking the behaviour is unlikely to be useful when someone does come to use it. I'm not particularly happy with the code either, not least because it's hard to understand what it's doing, and what the various state bits mean (some of them are set but never tested.)

Right now the major problem is that continual release events get sent, which is clearly wrong. Maybe we should just fix that (my first commit) and leave the rest until we have a plan for how it should work.

2024-01-02 05:41 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
> +      }
I;m already working on mote multi touch support. It is still on paper but it will be there soon.
There are just a couple of projects that i need to finish first. But when done it would be cool.

2024-01-02 05:42 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
> +      }
Sounds good - having it on paper to start helps a lot. I'll revert to the simple fix.

2024-01-02 05:45 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
> +      }
Please use the code as i shown above. that should fox the issue and my own issue as well.

2024-01-02 06:07 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
> +      }
The problem with that is that `update()` continues to report touches that have been released. So if there are two touches, and one is lifted, the next update reports one with state UPDATED and one with RELEASED, but continues to do so until the remaining touch is released. Just like with the released callback, a release for a touch should only be delivered once.

Also on some occasions a touch is reported with both UPDATED and RELEASING set. What does this mean? For the touch consumer having to interpret these states that have no description as to what they mean is difficult, whereas if only touches that were still ongoing were reported, it can easily keep track of which have been released.

2024-01-02 06:46 UTC, nielsnl68 commented on esphome/components/touchscreen/touchscreen.cpp
> +      }
then there is something else wrong. 
I will look of i can reproduce what you are telling me now.

2024-01-02 11:15 UTC, clydebarrow commented on esphome/components/touchscreen/touchscreen.cpp
> +      }
I think the update() call should just return the touches that are in PRESSED or UPDATED state only. And send an empty list on last release.

2024-01-16 17:03 UTC, nielsnl68 commented
This PR is being included into #5997

2024-02-11 21:20 UTC, nagyrobi commented
Indeed, with https://github.com/esphome/esphome/pull/5997 this is not needed anymore.

2024-03-10 22:36 UTC, closed without merging