Use touch state from ft63x6 driver.
OttoWinter/esphomeyaml pull request #6055
Opened 2024-01-03 22:56 UTC by nielsnl68

# What does this implement/fix?

This is an reworked version for the FT63x6 driver. The old method did not registered correctly when the touch was released.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-03 23:25 UTC, gpambrozio commented on esphome/components/ft63x6/ft63x6.cpp
> +    this->x_raw_max_ = 319;
From what I can tell, max value is exclusive, so I think this should still be 320.

2024-01-03 23:25 UTC, gpambrozio commented on esphome/components/ft63x6/ft63x6.cpp
> +    this->y_raw_max_ = 459;
I believe this should be 480

2024-01-03 23:31 UTC, nielsnl68 commented
@gpambrozio you are right. I doubted myself earlier :(

2024-01-03 23:44 UTC, gpambrozio approved these changes

2024-01-09 01:05 UTC, jesserockz requested changes

2024-01-09 01:05 UTC, jesserockz commented on esphome/components/ft63x6/ft63x6.cpp
> +    esph_log_e(TAG, "Failed to read touch data");
```suggestion
    ESP_LOGE(TAG, "Failed to read touch data");
```

2024-01-09 01:05 UTC, jesserockz commented on esphome/components/ft63x6/ft63x6.cpp
> +    // ESP_LOGV(TAG, "Add Touch A: id:%3d (x:%4d, y:%4d) %x", touch_id, x, y, (data[0x03] >> 6) & 0x01);
No commented code please
```suggestion
```

2024-01-09 01:05 UTC, jesserockz commented on esphome/components/ft63x6/ft63x6.cpp
> +    // ESP_LOGV(TAG, "Add Touch B: id:%3d (x:%4d, y:%4d) %x", touch_id, x, y, (data[0x09] >> 6) & 0x01);
```suggestion
```

2024-01-15 01:47 UTC, jesserockz approved these changes

2024-01-15 02:07 UTC, merged