More gain
OttoWinter/esphomeyaml pull request #6063
Opened 2024-01-08 15:54 UTC by selamanse

# What does this implement/fix?

Adds RC522 Gain support.

Basically took changes from https://github.com/esphome/esphome/pull/3171 and applied dev change requests.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [#1576](https://github.com/esphome/feature-requests/issues/1576)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
see [test](tests/test1.yaml)

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-08 23:09 UTC, jesserockz requested changes
There is no correlation between the configured value (0-7) and the dB valued that is logged. 
Ideally, the gain config variable should be an `enum` with the actual dB values that the user can choose from.

Also please look at how other code use LogString for logging the enums.

2024-01-11 13:55 UTC, selamanse commented
@jesserockz thanks for pointing this out. I have now updated the code to be more transparent in the requested manner. Please bear with me since I'm not so firm with c++ language but I tried my best by aligning with existing implementations of enum and LogString usage.

2024-01-31 07:34 UTC, selamanse commented
@jesserockz just a friendly reminder that I have fixed the issues you mentioned.

2024-02-27 07:55 UTC, selamanse commented
@glmnet @jesserockz friendly reminder.

2024-06-07 23:49 UTC, gabriel403 commented
@glmnet @jesserockz I'm very interested in this change too, what can we do to get this merged?

2024-06-08 04:01 UTC, kbx81 commented on .gitignore
Please remove these changes from this PR.

2024-06-08 04:09 UTC, kbx81 commented on esphome/components/rc522/__init__.py
> +        cv.Optional(CONF_GAIN, default="38dB"): validate_gain,
Couldn't this just use `cv.decibel`, instead?

2024-06-08 04:13 UTC, kbx81 commented on tests/test1.yaml
Please update the tests in the `/tests/components` directory, instead

2024-06-08 04:14 UTC, kbx81 commented on esphome/components/rc522/__init__.py
> +    CONF_GAIN,
Please alphabetize the constants

2024-06-08 06:40 UTC, selamanse commented on esphome/components/rc522/__init__.py
> +        cv.Optional(CONF_GAIN, default="38dB"): validate_gain,
sure thing

2024-06-08 07:21 UTC, kbx81 commented
Please also make sure all CI/tests are passing. 🙂

2024-06-08 17:18 UTC, selamanse commented on esphome/components/rc522/__init__.py
> +        cv.Optional(CONF_GAIN, default="38dB"): cv.enum(GAIN, string=True),
I can't use decibel here since a pure float based decibel value can never be used here (without the mapping logic). the rc522 only allows the custom fixed values that GAIN enum exposes (according to datasheet). so I decided to use cv.enum without any number validating logic anymore.

2024-06-10 15:54 UTC, kbx81 commented on esphome/components/rc522/__init__.py
> +        cv.Optional(CONF_GAIN, default="38dB"): cv.enum(GAIN, string=True),
You can use more than one validator

2024-06-10 15:57 UTC, kbx81 commented on esphome/components/rc522/__init__.py
> +        cv.Optional(CONF_GAIN, default="38dB"): cv.enum(GAIN, string=True),
Something like [this](https://github.com/esphome/esphome/blob/dceab6ce29493e67caaa8cdadf8cf7f4df063635/esphome/components/http_request/__init__.py#L108-L112)

2024-06-16 16:46 UTC, selamanse commented on esphome/components/rc522/__init__.py
> +        cv.Optional(CONF_GAIN, default="38dB"): cv.enum(GAIN, string=True),
@kbx81 can you please elaborate what your suggestion is?

2024-06-16 22:22 UTC, jesserockz commented on esphome/components/rc522/__init__.py
> +        cv.Optional(CONF_GAIN, default="38dB"): cv.enum(GAIN, string=True),
I think this is fine as is given it also has two special dBA values

2024-06-16 22:27 UTC, jesserockz requested changes

2024-06-16 22:27 UTC, jesserockz commented on esphome/components/rc522/rc522.cpp
> +}
This really should show the value as close to the config entered as possible.
```suggestion
const LogString *rc522_gain_to_string(RC522Gain gain) {
  switch (gain) {
    case RC522Gain::RC522_GAIN_18DB:
      return LOG_STR("18dB");
    case RC522Gain::RC522_GAIN_18DBA:
      return LOG_STR("18dB_a");
    case RC522Gain::RC522_GAIN_23DB:
      return LOG_STR("23dB");
    case RC522Gain::RC522_GAIN_23DBA:
      return LOG_STR("23dB_a");
    case RC522Gain::RC522_GAIN_33DB:
      return LOG_STR("33dB");
    case RC522Gain::RC522_GAIN_38DB:
      return LOG_STR("38dB");
    case RC522Gain::RC522_GAIN_43DB:
      return LOG_STR("43dB");
    case RC522Gain::RC522_GAIN_48DB:
      return LOG_STR("48dB");
    default:
      return LOG_STR("UNKNOWN");
  }
}
```

2024-06-27 19:02 UTC, selamanse commented
@kbx81 fyi: I added docs here https://github.com/esphome/esphome-docs/pull/3979

2024-10-04 07:18 UTC, selamanse commented
superseeded by #7539

2024-10-04 07:18 UTC, closed without merging