OTA 1.1 which confirm each written chunk
OttoWinter/esphomeyaml pull request #6066
Opened 2024-01-09 17:19 UTC by tomaszduda23

# What does this implement/fix?

**AS-IS**
All OTA chunks are written to a device without checking if device is able to keep up with transfer or not.
It works at the beginning but after a while client side reset connection.

![Screenshot from 2024-01-09 18-15-11](https://github.com/esphome/esphome/assets/35012788/15ae19c7-9284-4984-8fd5-7418fe95c51d)

**TO-BE**
OTA client waits for device to confirm each chunk. That way device needs to handle just one chunk at the time.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>
https://github.com/esphome/issues/issues/3318

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-10 03:30 UTC, bdraco commented on esphome/espota2.py
> +OTA_VERSION_1_1 = 2
Its a bit unexpected that the ota version is `1_1` and the value is `2`

2024-01-11 04:56 UTC, jesserockz commented
CLI Logs
```
Uploading: [============================================================] 100% Done...

INFO Upload took 3.52 seconds, waiting for result...
ERROR Error receive OK: Unexpected response from ESP: 0x47
```

Device logs:
```
[13:50:29][D][ota:151]: Starting OTA Update from 10.30.30.1...
[13:50:31][D][ota:322]: OTA in progress: 0.2%
[13:50:32][D][ota:322]: OTA in progress: 25.5%
[13:50:33][D][ota:322]: OTA in progress: 51.3%
[13:50:34][D][ota:322]: OTA in progress: 77.0%
[13:50:35][W][ota:427]: Failed to write 1 bytes of data, errno: 104
[13:50:35][W][ota:427]: Failed to write 1 bytes of data, errno: 128
[13:50:35][W][ota:299]: Error receiving data for update, errno: 128
[13:50:35][W][ota:427]: Failed to write 1 bytes of data, errno: 128
[13:50:35][W][component:214]: Component ota took a long time for an operation (5.79 s).
[13:50:35][W][component:215]: Components should block for at most 20-30ms.
```

2024-01-11 06:28 UTC, tomaszduda23 commented
If downgrade is needed. It could be solved by:
```yaml
ota:
  version: 1
```
User could:
1. Downgrade OTA version with the same eaphome version 
2. From that point any legacy esphome version could be used

Another option would be to make protocol negotiations between device and client. This is kind of complex to make sure that old devices behave with it. 

Downgrade use case is limited. I would prefer first option since it is simple. What do you think?

2024-01-11 10:15 UTC, tomaszduda23 commented
> Uploading: [============================================================] 100% Done...
> 
> INFO Upload took 3.52 seconds, waiting for result...
> ERROR Error receive OK: Unexpected response from ESP: 0x47

I've missed that data might be sliced by TCP/IP. It is fixed now.

2024-01-12 08:27 UTC, tomaszduda23 commented
> I switched back to `dev` and OTA is working normally after a serial flash. OTA from v1 to v2 is working correctly, but for obvious reasons, you cannot go from v2 to v1

Now you can go back and forth.

2024-01-14 23:11 UTC, jesserockz commented on esphome/components/ota/ota_component.cpp
> +         size_acknowledged += OTA_BLOCK_SIZE) {
Not saying it **has** to change, but these lines were really weird to understand due to formatting..

2024-01-14 23:18 UTC, jesserockz requested changes
Working now, thanks. One small change below then good to merge.

2024-01-14 23:18 UTC, jesserockz commented on esphome/core/defines.h
> +#define USE_OTA_VERSION 1
Please move this above to the USE_OTA "group"

2024-01-17 17:23 UTC, tomaszduda23 commented on esphome/components/ota/ota_component.cpp
> +         size_acknowledged += OTA_BLOCK_SIZE) {
I've changed to while loop to make it more clear.

2024-01-17 23:33 UTC, jesserockz approved these changes, later dismissed

2024-01-17 23:34 UTC, jesserockz commented
Please make sure to add a docs PR with the new `version` config variable

2024-01-18 06:55 UTC, tomaszduda23 commented
Doc is already done https://github.com/esphome/esphome-docs/pull/3552

2024-01-19 03:24 UTC, jesserockz commented on esphome/components/ota/__init__.py
> +        cv.Optional(CONF_VERSION, default=1): cv.one_of(1, 2, int=True),
Lets just default to the newest, otherwise nobody will use it =)
```suggestion
        cv.Optional(CONF_VERSION, default=2): cv.one_of(1, 2, int=True),
```

2024-01-19 03:32 UTC, jesserockz approved these changes

2024-01-19 04:18 UTC, merged