VEML7700 and VEML6030 light sensors
OttoWinter/esphomeyaml pull request #6067
Opened 2024-01-09 21:43 UTC by latonita

# What does this implement/fix?

Implements component for ambient light sensors from Vishay - VEML7700 and VEML6030

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2493

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
esphome:
  name: veml7700-test

esp32:
  board: esp32dev
  framework:
    type: arduino

# esp8266:
#   board: nodemcuv2

logger:
  level: DEBUG

i2c:
  sda: GPIO25
  scl: GPIO32
  scan: true

sensor:
  - platform: veml7700
    address: 0x10
    update_interval: 30s
    # auto_mode: false
    # gain: X1
    # integration_time: 100ms
    # lux_compensation: false
    # glass_attenuation_factor: 1.10
    ambient_light:
      name: "Ambient light"
    ambient_light_counts:
      name: "Ambient light counts"
    full_spectrum:
      name: "Full spectrum"
    full_spectrum_counts:
      name: "Full spectrum counts"
    actual_integration_time:
      name: "Actual integration time"
    actual_gain:
      name: "Actual gain"

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-18 07:22 UTC, jesserockz requested changes
Thank you for your contribution.

I got as far as `wait_for_device` and decided to stop reviewing there as it will need quite a bit of reworking to be accepted in.

Please take a look at my comments below.

2024-01-18 07:22 UTC, jesserockz commented on esphome/components/veml7700/sensor.py
> +ICON_GAIN = "mdi:multiplication"
Please name consts with what actually represents the value
```suggestion
ICON_MULTIPLICATION = "mdi:multiplication"
```

2024-01-18 07:22 UTC, jesserockz commented on esphome/components/veml7700/sensor.py
> +    ),
I know this might seem strange, but we do not enforce the use of any sensors etc in ESPHome
```suggestion
```

2024-01-18 07:22 UTC, jesserockz commented on esphome/components/veml7700/veml7700.cpp
> +}
This is a big no. Components should not delay for any significant amount. 
The component should be reworked to use `this->set_timeout(fn, milliseconds)` which will call the function sometime after the milliseconds has elapsed without blocking the rest of the application.

2024-01-18 22:52 UTC, kbx81 commented on esphome/components/veml7700/sensor.py
> +ICON_GAIN = "mdi:multiplication"
Marked as resolved, but it seems this change was not made?

2024-01-18 22:52 UTC, kbx81 commented on esphome/components/veml7700/sensor.py
> +    ),
As above, this was marked as resolved, but it seems this change was not made?

2024-01-19 03:07 UTC, jesserockz submitted a review, later dismissed

2024-01-19 03:07 UTC, jesserockz commented on esphome/components/veml7700/sensor.py
> +ICON_GAIN = "mdi:multiplication"
Indeed

2024-01-19 03:07 UTC, jesserockz commented on esphome/components/veml7700/sensor.py
> +    ),
Correct

2024-01-19 03:07 UTC, jesserockz commented on esphome/components/veml7700/veml7700.h
> +#pragma pack(1)
Please change to use `__attribute__((packed));`

2024-01-19 17:21 UTC, latonita commented on esphome/components/veml7700/sensor.py
> +ICON_GAIN = "mdi:multiplication"
apologies, merge glitch. fixed now.

2024-01-19 17:22 UTC, latonita commented on esphome/components/veml7700/sensor.py
> +    ),
apologies, merge glitch. fixed now.

2024-01-19 17:22 UTC, latonita commented on esphome/components/veml7700/veml7700.h
> +#pragma pack(1)
Done.

2024-01-26 06:06 UTC, mrtoy-me commented
Hi @latonita
I have tested the component on veml6030 seems to work fine ... but I will do some more testing overnight and let you know if I pick up anything.

Two suggestions I have 
1.
I was getting some compile warnings around the packed ConfigurationRegister for IntegrationTime ALS_IT relating to gcc4.4
From what I have read, it related to the compiler complaining about the packed structure crossing a type boundary with uint8_t.
In the .h file, I changed enum IntegrationTime : uint16_t rather than uint8_t and no more warnings :) - makes no difference to packed structure anyway.
2.
There are plenty of  ESP_LOGD messages in the component and I can understand why they are there when you were debugging but now it is working it makes the logs pretty noisy - I changed all the ESP_LOGD to ESP_LOGV so you can get the messages as verbose if you want and in debug there are enough messages on what values are being sent.

They are minor changes so I didn't do a PR to you, but I think they are worth you considering.

Anyway thanks a lot for developing the component - great work.

2024-01-26 10:24 UTC, latonita commented
@mrtoy-me thanks for taking a look and testing
1. I don't believe its a good thing, it just a hack which works due to specific bit positions in the struct. Stupid compilation note from the GCC drives people craze since 2010... Moreover another GCC bug doesn't let to suppress this with `#pragma GCC diagnostic ignored "-Wxxxxx"` :) It was fixed in 2022 in GCC 13, but extensa-gcc is based on gcc8 i believe.
2. Good catch, thanks! I actually forgot to change them to LOGV. Fixed.

2024-01-26 18:02 UTC, latonita commented on esphome/components/veml7700/veml7700.cpp
> +}
fixed, FSM implemented

2024-03-12 00:40 UTC, kbx81 approved these changes
LGTM -- thanks for working on this!

2024-03-12 02:51 UTC, merged

2024-03-12 15:44 UTC, latonita commented
> LGTM -- thanks for working on this!

Thanks. There are several more PRs to review! :)