Add AGS10 Sensor
OttoWinter/esphomeyaml pull request #6070
Opened 2024-01-10 07:38 UTC by mak-42

Add support for AGS10 VOC Sensor.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
  - platform: ags10
    tvoc:
      name: "TVOC2"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-18 08:04 UTC, jesserockz requested changes

2024-01-18 08:04 UTC, jesserockz commented on esphome/components/ags10/sensor.py
> +            ),
This sensor should be setting most if not all of the arguments to `sensor_schema` and also have `entity_category=ENTITY_CATEGORY_DIAGNOSTIC` (The `version` sensor should also be a diagnostic sensor)

2024-01-18 08:04 UTC, jesserockz commented on esphome/components/ags10/sensor.py
> +            cv.Required(CONF_TVOC): sensor.sensor_schema(
All sensors are to be Optional
```suggestion
            cv.Optional(CONF_TVOC): sensor.sensor_schema(
```

2024-01-18 08:04 UTC, jesserockz commented on esphome/components/ags10/ags10.h
> +template<typename... Ts> class AGS10SetZeroPointAction : public Action<Ts...> {
After adding this, you can remove the constructor and protected field
```suggestion
template<typename... Ts> class AGS10SetZeroPointAction : public Action<Ts...>, public Parented<AGS10Component> {
```

2024-01-18 08:04 UTC, jesserockz commented on esphome/components/ags10/ags10.h
> +  TEMPLATABLE_VALUE(int, new_address)
I2C addresses are limites to a single byte, no need to reserve more memory that wont be used
```suggestion
  TEMPLATABLE_VALUE(uint8_t, new_address)
```

2024-01-18 08:04 UTC, jesserockz commented on esphome/components/ags10/ags10.h
> +  void set_tvoc(sensor::Sensor *tvoc) { tvoc_ = tvoc; }
Please make sure to always prefix member variables and function calls with `this->` as per our [code standards](https://esphome.io/guides/contributing#codebase-standards)
```suggestion
  void set_tvoc(sensor::Sensor *tvoc) { this->tvoc_ = tvoc; }
```

2024-01-18 08:06 UTC, jesserockz commented on esphome/components/ags10/sensor.py
> +CONFIG_SCHEMA = (
Please also look at `final_validate_device_schema` and look in the codebase on how to use it to specify a `max_frequency` of the i2c bus.

2024-02-11 12:35 UTC, mak-42 commented on esphome/components/ags10/sensor.py
> +            ),
Done. Please check if it is enough.  The devices which code I used as example does not contain that :(

2024-02-11 12:35 UTC, mak-42 commented on esphome/components/ags10/sensor.py
> +            cv.Required(CONF_TVOC): sensor.sensor_schema(
Done

2024-02-11 12:35 UTC, mak-42 commented on esphome/components/ags10/ags10.h
> +template<typename... Ts> class AGS10SetZeroPointAction : public Action<Ts...> {
Done

2024-02-11 12:35 UTC, mak-42 commented on esphome/components/ags10/ags10.h
> +  TEMPLATABLE_VALUE(int, new_address)
Done

2024-02-11 12:35 UTC, mak-42 commented on esphome/components/ags10/ags10.h
> +  void set_tvoc(sensor::Sensor *tvoc) { tvoc_ = tvoc; }
Done

2024-02-11 16:38 UTC, mak-42 commented on esphome/components/ags10/ags10.h
> +template<typename... Ts> class AGS10SetZeroPointAction : public Action<Ts...> {
I've to leave constructors, because the compilation error occurs without it:
```
src/main.cpp: In function 'void setup()':
src/main.cpp:1274:81: error: no matching function for call to 'esphome::ags10::AGS10NewI2cAddressAction<>::AGS10NewI2cAddressAction(esphome::ags10::AGS10Component*&)'
   ags10_ags10newi2caddressaction = new ags10::AGS10NewI2cAddressAction<>(ags10_1);
                                                                                 ^
In file included from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/ags10/ags10.h:116:32: note: candidate: 'esphome::ags10::AGS10NewI2cAddressAction<>::AGS10NewI2cAddressAction()'
 template<typename... Ts> class AGS10NewI2cAddressAction : public Action<Ts...>, public Parented<AGS10Component> {
                                ^~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/ags10/ags10.h:116:32: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/ags10/ags10.h:116:32: note: candidate: 'esphome::ags10::AGS10NewI2cAddressAction<>::AGS10NewI2cAddressAction(const esphome::ags10::AGS10NewI2cAddressAction<>&)'
src/esphome/components/ags10/ags10.h:116:32: note:   no known conversion for argument 1 from 'esphome::ags10::AGS10Component*' to 'const esphome::ags10::AGS10NewI2cAddressAction<>&'
src/esphome/components/ags10/ags10.h:116:32: note: candidate: 'esphome::ags10::AGS10NewI2cAddressAction<>::AGS10NewI2cAddressAction(esphome::ags10::AGS10NewI2cAddressAction<>&&)'
src/esphome/components/ags10/ags10.h:116:32: note:   no known conversion for argument 1 from 'esphome::ags10::AGS10Component*' to 'esphome::ags10::AGS10NewI2cAddressAction<>&&'
src/main.cpp:1301:83: error: no matching function for call to 'esphome::ags10::AGS10NewI2cAddressAction<>::AGS10NewI2cAddressAction(esphome::ags10::AGS10Component*&)'
   ags10_ags10newi2caddressaction_2 = new ags10::AGS10NewI2cAddressAction<>(ags10_1);
                                                                                   ^
In file included from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/ags10/ags10.h:116:32: note: candidate: 'esphome::ags10::AGS10NewI2cAddressAction<>::AGS10NewI2cAddressAction()'
 template<typename... Ts> class AGS10NewI2cAddressAction : public Action<Ts...>, public Parented<AGS10Component> {
                                ^~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/ags10/ags10.h:116:32: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/ags10/ags10.h:116:32: note: candidate: 'esphome::ags10::AGS10NewI2cAddressAction<>::AGS10NewI2cAddressAction(const esphome::ags10::AGS10NewI2cAddressAction<>&)'
src/esphome/components/ags10/ags10.h:116:32: note:   no known conversion for argument 1 from 'esphome::ags10::AGS10Component*' to 'const esphome::ags10::AGS10NewI2cAddressAction<>&'
src/esphome/components/ags10/ags10.h:116:32: note: candidate: 'esphome::ags10::AGS10NewI2cAddressAction<>::AGS10NewI2cAddressAction(esphome::ags10::AGS10NewI2cAddressAction<>&&)'
src/esphome/components/ags10/ags10.h:116:32: note:   no known conversion for argument 1 from 'esphome::ags10::AGS10Component*' to 'esphome::ags10::AGS10NewI2cAddressAction<>&&'
src/main.cpp:1329:79: error: no matching function for call to 'esphome::ags10::AGS10SetZeroPointAction<>::AGS10SetZeroPointAction(esphome::ags10::AGS10Component*&)'
   ags10_ags10setzeropointaction = new ags10::AGS10SetZeroPointAction<>(ags10_1);
                                                                               ^
In file included from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/ags10/ags10.h:132:32: note: candidate: 'esphome::ags10::AGS10SetZeroPointAction<>::AGS10SetZeroPointAction()'
 template<typename... Ts> class AGS10SetZeroPointAction : public Action<Ts...>, public Parented<AGS10Component> {
                                ^~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/ags10/ags10.h:132:32: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/ags10/ags10.h:132:32: note: candidate: 'esphome::ags10::AGS10SetZeroPointAction<>::AGS10SetZeroPointAction(const esphome::ags10::AGS10SetZeroPointAction<>&)'
src/esphome/components/ags10/ags10.h:132:32: note:   no known conversion for argument 1 from 'esphome::ags10::AGS10Component*' to 'const esphome::ags10::AGS10SetZeroPointAction<>&'
src/esphome/components/ags10/ags10.h:132:32: note: candidate: 'esphome::ags10::AGS10SetZeroPointAction<>::AGS10SetZeroPointAction(esphome::ags10::AGS10SetZeroPointAction<>&&)'
src/esphome/components/ags10/ags10.h:132:32: note:   no known conversion for argument 1 from 'esphome::ags10::AGS10Component*' to 'esphome::ags10::AGS10SetZeroPointAction<>&&'
src/main.cpp:1357:81: error: no matching function for call to 'esphome::ags10::AGS10SetZeroPointAction<>::AGS10SetZeroPointAction(esphome::ags10::AGS10Component*&)'
   ags10_ags10setzeropointaction_2 = new ags10::AGS10SetZeroPointAction<>(ags10_1);
                                                                                 ^
In file included from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/ags10/ags10.h:132:32: note: candidate: 'esphome::ags10::AGS10SetZeroPointAction<>::AGS10SetZeroPointAction()'
 template<typename... Ts> class AGS10SetZeroPointAction : public Action<Ts...>, public Parented<AGS10Component> {
                                ^~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/ags10/ags10.h:132:32: note:   candidate expects 0 arguments, 1 provided
src/esphome/components/ags10/ags10.h:132:32: note: candidate: 'esphome::ags10::AGS10SetZeroPointAction<>::AGS10SetZeroPointAction(const esphome::ags10::AGS10SetZeroPointAction<>&)'
src/esphome/components/ags10/ags10.h:132:32: note:   no known conversion for argument 1 from 'esphome::ags10::AGS10Component*' to 'const esphome::ags10::AGS10SetZeroPointAction<>&'
src/esphome/components/ags10/ags10.h:132:32: note: candidate: 'esphome::ags10::AGS10SetZeroPointAction<>::AGS10SetZeroPointAction(esphome::ags10::AGS10SetZeroPointAction<>&&)'
src/esphome/components/ags10/ags10.h:132:32: note:   no known conversion for argument 1 from 'esphome::ags10::AGS10Component*' to 'esphome::ags10::AGS10SetZeroPointAction<>&&'
```

2024-02-11 16:41 UTC, mak-42 commented on esphome/components/ags10/sensor.py
> +CONFIG_SCHEMA = (
Done. 
I've also move tests to separated files, because configuration i2c of all the tests has higher frequency then required.

2024-03-03 21:00 UTC, jesserockz requested changes

2024-03-03 21:00 UTC, jesserockz commented on esphome/components/ags10/sensor.py
> +    var = cg.new_Pvariable(action_id, template_arg, parent)
```suggestion
    var = cg.new_Pvariable(action_id, template_arg)
    await cg.register_parented(var, config[CONF_ID])
```
```

2024-03-03 21:00 UTC, jesserockz commented on esphome/components/ags10/sensor.py
> +        cg.add(var.set_value(await cg.templatable(value, args, int)))
Since there is a default (`0xFFFF`), the value is always in config
```suggestion
    value = await cg.templatable(config[CONF_VALUE], args, int)
    cg.add(var.set_value(value))
```

2024-03-03 21:00 UTC, jesserockz commented on esphome/components/ags10/sensor.py
> +AGS10_SET_ZERO_POINT_SCHEMA = cv.All(
```suggestion
AGS10_SET_ZERO_POINT_SCHEMA = cv.Schema(
```

2024-03-03 21:00 UTC, jesserockz commented on esphome/components/ags10/sensor.py
> +    var.set_mode(await cg.templatable(config.get(CONF_MODE), args, enumerate))
Mode is not templatable in the above SCHEMA...

2024-03-08 15:11 UTC, mak-42 commented on esphome/components/ags10/sensor.py
> +    var = cg.new_Pvariable(action_id, template_arg, parent)
Done. It allowed to remove constructors as you suggested previously.

2024-03-08 15:11 UTC, mak-42 commented on esphome/components/ags10/sensor.py
> +        cg.add(var.set_value(await cg.templatable(value, args, int)))
Done.

2024-03-08 15:13 UTC, mak-42 commented on esphome/components/ags10/sensor.py
> +    var.set_mode(await cg.templatable(config.get(CONF_MODE), args, enumerate))
Fixed.

2024-03-08 15:13 UTC, mak-42 commented on esphome/components/ags10/sensor.py
> +AGS10_SET_ZERO_POINT_SCHEMA = cv.All(
Done

2024-03-08 15:14 UTC, mak-42 commented on esphome/components/ags10/ags10.h
> +template<typename... Ts> class AGS10SetZeroPointAction : public Action<Ts...> {
Finally I managed to remove constructors.

2024-03-10 21:07 UTC, jesserockz approved these changes

2024-03-10 21:19 UTC, merged