LTR303 and LTR329 light sensors
OttoWinter/esphomeyaml pull request #6076
Opened 2024-01-11 00:58 UTC by latonita

# What does this implement/fix?

Component for using LiteOn LTR303/LTR329 ambient light sensors.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2485

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: ltr303-test

esp32:
  board: esp32dev
  framework:
    type: arduino

# esp8266:
#   board: nodemcuv2

logger:
  level: DEBUG

i2c:
  sda: GPIO25
  scl: GPIO32
  scan: true

sensor:
  - platform: ltr303
    address: 0x29
    gain: 1x
    integration_time: 100ms
    repeat: 500ms
    ambient_light:
      name: "Ambient light"
    full_spectrum_counts:
      name: "Full spectrum counts"
    infrared_counts:
      name: "Infrared counts"
    actual_gain:
      name: "Actual gain"

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-19 10:15 UTC, kbx81 requested changes
Thank you for working on this -- just a few comments.

2024-01-19 10:15 UTC, kbx81 commented on esphome/components/ltr303/ltr303.cpp
> +      delay(ALS_MEAS_RATE[this->repeat_rate_]);
As Jesse mentioned [here](https://github.com/esphome/esphome/pull/6067#discussion_r1457026808), we can't have big delays like this. Please rework to eliminate this.

2024-01-19 10:15 UTC, kbx81 commented on esphome/components/ltr303/ltr303.cpp
> +static const int ALS_GAIN[8] = {1, 2, 4, 8, 0, 0, 48, 96};                        // multiplier
These could be `uint8_t` -- would save some memory...
```suggestion
static const uint8_t ALS_GAIN[8] = {1, 2, 4, 8, 0, 0, 48, 96};                        // multiplier
```

2024-01-19 10:15 UTC, kbx81 commented on esphome/components/ltr303/ltr303.cpp
> +static const int ALS_MEAS_RATE[8] = {50, 100, 200, 500, 1000, 2000, 2000, 2000};  // ms
As above, these could save some memory by making them `uint16_t`.
```suggestion
static const uint16_t ALS_INT_TIME[8] = {100, 50, 200, 400, 150, 250, 300, 350};       // ms
static const uint16_t ALS_MEAS_RATE[8] = {50, 100, 200, 500, 1000, 2000, 2000, 2000};  // ms
```

2024-01-19 10:15 UTC, kbx81 commented on esphome/components/ltr303/ltr303.h
> +};
In ESPHome, we typically use (static) consts for this purpose.
```suggestion
static const uint8_t CR_ALS_CTRL = 0x80;   // ALS operation mode control SW reset
static const uint8_t CR_MEAS_RATE = 0x85;  // ALS measurement rate in active mode
static const uint8_t CR_PART_ID = 0x86;    // Part Number ID and Revision ID
static const uint8_t CR_MANU_ID = 0x87;    // Manufacturer ID
static const uint8_t CR_CH1_0 = 0x88;      // ALS measurement CH1 data, lower byte - infrared only
static const uint8_t CR_CH1_1 = 0x89;      // ALS measurement CH1 data, upper byte - infrared only
static const uint8_t CR_CH0_0 = 0x8A;      // ALS measurement CH0 data, lower byte - visible + infrared
static const uint8_t CR_CH0_1 = 0x8B;      // ALS measurement CH0 data, upper byte - visible + infrared
static const uint8_t CR_ALS_STATUS = 0x8c; // ALS new data status
```

2024-01-19 12:15 UTC, latonita commented on esphome/components/ltr303/ltr303.h
> +};
yes, i saw this usage in other components, but I think we might move forward small steps at least.
Simple `static const` are really from the old C-style past. 
I believe enums give us much more clearer and readable code, especially if used prefixed with enum name like `RegisterMap::CONF_ABC`. Also it works as typecheck.
If there is one or two values - consts are okay, 
when we have numbers of them - semantically its better to organize them into enums.

I'm strong believer we shall keep with enums, even if is is (yet) look a little bit different than old approach. All in all its not of that big difference in the end, but readability much better.
What do you think? 

I have few more components I in progress of making now. All with enums now, really easier to read.  (VEML7700, INA228).

2024-01-19 17:24 UTC, latonita commented on esphome/components/ltr303/ltr303.cpp
> +      delay(ALS_MEAS_RATE[this->repeat_rate_]);
I will rework this one a little bit similarly to VEML7700 (state machine in the loop)

2024-01-19 21:51 UTC, kbx81 commented on esphome/components/ltr303/ltr303.h
> +};
I'm not strictly opposed to it if it's a generally-accepted new(ish) approach -- would be curious if @jesserockz has an opinion. I've seen it come up elsewhere a couple of times (outside of your PRs) in the last few weeks but didn't realize it's a new pattern people are adopting.

2024-01-20 18:14 UTC, latonita commented on esphome/components/ltr303/ltr303.cpp
> +static const int ALS_GAIN[8] = {1, 2, 4, 8, 0, 0, 48, 96};                        // multiplier
thats my bad, copy paste from my test code. fixed

2024-01-26 18:08 UTC, latonita commented
Looks like this component might support more than 2 sensors. There is number of ALS sensors, PS(Proximity) sensors and ALS + PS integrated sensors from Lite-On which share same API, the only issue they can't be detected by product_id, its just the same form many of them with different features, so manual selection will be required.
I'm reworking component, it will be `ltr_alsps` supporting at least LTR-303,329, 553, 556, 659 and some others

2024-01-28 18:36 UTC, Donkie commented
I have been trying this for some time with very mixed results, none of them I would call successful.
I previously used the exact same board and sensor etc but with a simple arduino code to talk to the sensor. Then it worked fine and I got proper readings.

However with this esphome sensor I either get extremely noisy data or incorrect data. I tried it first using the auto setting, and then it was very noisy during daylight, it kept jumping up and down from 0 to 1000s of lux:
![image](https://github.com/esphome/esphome/assets/2332094/39065970-c392-4cf2-83fc-8773e1c82dc9)

Now with auto off, I some days get very low values like this:
![image](https://github.com/esphome/esphome/assets/2332094/d5a841a9-ae53-42a0-af96-d9350f98fc46)

Here is a log from today, where the values was slightly higher, but still much lower than they were with my custom code.
```
INFO ESPHome 2023.12.9
INFO Reading configuration /config/weather-station.yaml...
INFO Updating https://github.com/latonita/esphome-ltr303.git@None
INFO Detected timezone 'Europe/Berlin'
[10:25:13][I][app:102]: ESPHome version 2023.12.9 compiled on Jan 26 2024, 17:02:16
[10:25:13][C][status_led:019]: Status LED:
[10:25:13][C][status_led:020]:   Pin: GPIO16
[10:25:13][C][wifi:573]: WiFi:
[10:25:13][C][wifi:405]:  
[10:25:13][C][logger:439]: Logger:
[10:25:13][C][logger:440]:   Level: DEBUG
[10:25:13][C][logger:441]:   Log Baud Rate: 115200
[10:25:13][C][logger:443]:   Hardware UART: UART0
[10:25:13][C][i2c.arduino:053]: I2C Bus:
[10:25:13][C][i2c.arduino:054]:   SDA Pin: GPIO4
[10:25:13][C][i2c.arduino:055]:   SCL Pin: GPIO5
[10:25:13][C][i2c.arduino:056]:   Frequency: 50000 Hz
[10:25:13][C][i2c.arduino:059]:   Recovery: bus successfully recovered
[10:25:13][I][i2c.arduino:069]: Results from i2c bus scan:
[10:25:13][I][i2c.arduino:075]: Found i2c device at address 0x29
[10:25:13][C][uptime.sensor:031]: Uptime Sensor 'Uptime'
[10:25:13][C][uptime.sensor:031]:   Device Class: 'duration'
[10:25:13][C][uptime.sensor:031]:   State Class: 'total_increasing'
[10:25:13][C][uptime.sensor:031]:   Unit of Measurement: 's'
[10:25:13][C][uptime.sensor:031]:   Accuracy Decimals: 0
[10:25:13][C][uptime.sensor:031]:   Icon: 'mdi:timer-outline'
[10:25:13][C][homeassistant.time:010]: Home Assistant Time:
[10:25:13][C][homeassistant.time:011]:   Timezone: 'CET-1CEST,M3.5.0,M10.5.0/3'
[10:25:13][C][ltr303:067]:   Address: 0x29
[10:25:13][C][ltr303:068]:   Automatic mode: OFF
[10:25:13][C][ltr303:069]:   Gain: 1x
[10:25:13][C][ltr303:070]:   Integration time: 400 ms
[10:25:13][C][ltr303:071]:   Measurement repeat rate: 500 ms
[10:25:13][C][ltr303:072]:   Glass attenuation factor: 1.000000
[10:25:13][C][ltr303:073]:   Update Interval: 60.0s
[10:25:13][C][ltr303:075]:   ALS calculated lux 'Ambient light'
[10:25:13][C][ltr303:075]:     Device Class: 'illuminance'
[10:25:13][C][ltr303:075]:     State Class: 'measurement'
[10:25:13][C][ltr303:075]:     Unit of Measurement: 'lx'
[10:25:13][C][ltr303:075]:     Accuracy Decimals: 1
[10:25:13][C][ltr303:075]:     Icon: 'mdi:brightness-6'
[10:25:13][C][ltr303:076]:   CH1 Infrared counts 'Infrared counts'
[10:25:13][C][ltr303:076]:     Device Class: 'illuminance'
[10:25:13][C][ltr303:076]:     State Class: 'measurement'
[10:25:13][C][ltr303:076]:     Unit of Measurement: '#'
[10:25:13][C][ltr303:076]:     Accuracy Decimals: 0
[10:25:13][C][ltr303:076]:     Icon: 'mdi:brightness-5'
[10:25:13][C][ltr303:077]:   CH0 Visible+IR counts 'Full spectrum counts'
[10:25:13][C][ltr303:077]:     Device Class: 'illuminance'
[10:25:13][C][ltr303:077]:     State Class: 'measurement'
[10:25:13][C][ltr303:077]:     Unit of Measurement: '#'
[10:25:13][C][ltr303:077]:     Accuracy Decimals: 0
[10:25:13][C][ltr303:077]:     Icon: 'mdi:brightness-7'
[10:25:13][C][ltr303:078]:   Actual gain 'Actual gain'
[10:25:13][C][ltr303:078]:     Device Class: 'illuminance'
[10:25:13][C][ltr303:078]:     State Class: 'measurement'
[10:25:13][C][ltr303:078]:     Unit of Measurement: ''
[10:25:13][C][ltr303:078]:     Accuracy Decimals: 0
[10:25:13][C][ltr303:078]:     Icon: 'mdi:multiplication'
[10:25:13][C][dht:017]: DHT:
[10:25:13][C][dht:018]:   Pin: GPIO12
[10:25:13][C][dht:020]:   Auto-detected model: DHT22
[10:25:13][C][dht:027]:   Update Interval: 60.0s
[10:25:13][C][dht:029]:   Temperature 'Temperature'
[10:25:13][C][dht:029]:     Device Class: 'temperature'
[10:25:13][C][dht:029]:     State Class: 'measurement'
[10:25:13][C][dht:029]:     Unit of Measurement: '°C'
[10:25:13][C][dht:029]:     Accuracy Decimals: 1
[10:25:13][C][dht:030]:   Humidity 'Humidity'
[10:25:13][C][dht:030]:     Device Class: 'humidity'
[10:25:13][C][dht:030]:     State Class: 'measurement'
[10:25:13][C][dht:030]:     Unit of Measurement: '%'
[10:25:13][C][dht:030]:     Accuracy Decimals: 0
[10:25:13][C][captive_portal:088]: Captive Portal:
[10:25:13][C][mdns:115]: mDNS:
[10:25:13][C][mdns:116]:   Hostname: weather-station
[10:25:13][C][ota:097]: Over-The-Air Updates:
[10:25:13][C][ota:098]:   Address: weather-station.local:8266
[10:25:13][C][ota:101]:   Using Password.
[10:25:13][C][api:139]: API Server:
[10:25:13][C][api:140]:   Address: weather-station.local:6053
[10:25:13][C][api:142]:   Using noise encryption: YES
[10:25:13][C][wifi_signal.sensor:009]: WiFi Signal 'RSSI'
[10:25:13][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[10:25:13][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[10:25:13][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[10:25:13][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[10:25:27][D][ltr303:086]: Updating
[10:25:27][D][ltr303:088]: Initiating new data collection
[10:25:27][D][ltr303:244]: Data ready, reported gain is 1
[10:25:27][D][ltr303:126]: Reading sensor data having gain = 1x, time = 400 ms
[10:25:27][D][ltr303:256]: Got sensor data: CH1 = 150, CH0 = 89
[10:25:27][D][ltr303:328]: Lux calculation: ratio 0.627615, gain 1.000000, int time 4.000000, inv_pfactor 1.000000
[10:25:27][D][sensor:093]: 'Ambient light': Sending state 21.89162 lx with 1 decimals of accuracy
[10:25:27][D][sensor:093]: 'Infrared counts': Sending state 150.00000 # with 0 decimals of accuracy
[10:25:27][D][sensor:093]: 'Full spectrum counts': Sending state 89.00000 # with 0 decimals of accuracy
[10:25:27][D][sensor:093]: 'Actual gain': Sending state 1.00000  with 0 decimals of accuracy
[10:25:27][D][sensor:093]: 'Actual integration time': Sending state 400.00000 ms with 0 decimals of accuracy
[10:25:31][D][dht:048]: Got Temperature=4.7°C Humidity=99.9%
[10:25:32][D][sensor:093]: 'Temperature': Sending state 4.70000 °C with 1 decimals of accuracy
[10:25:32][D][sensor:093]: 'Humidity': Sending state 99.90000 % with 0 decimals of accuracy
[10:25:36][D][sensor:093]: 'Uptime': Sending state 148969.73438 s with 0 decimals of accuracy
[10:25:53][D][sensor:093]: 'RSSI': Sending state -65.00000 dBm with 0 decimals of accuracy
[10:26:27][D][ltr303:086]: Updating
[10:26:27][D][ltr303:088]: Initiating new data collection
[10:26:27][D][ltr303:244]: Data ready, reported gain is 1
[10:26:27][D][ltr303:126]: Reading sensor data having gain = 1x, time = 400 ms
[10:26:27][D][ltr303:256]: Got sensor data: CH1 = 125, CH0 = 76
[10:26:27][D][ltr303:328]: Lux calculation: ratio 0.621891, gain 1.000000, int time 4.000000, inv_pfactor 1.000000
[10:26:27][D][sensor:093]: 'Ambient light': Sending state 20.20400 lx with 1 decimals of accuracy
[10:26:27][D][sensor:093]: 'Infrared counts': Sending state 125.00000 # with 0 decimals of accuracy
[10:26:27][D][sensor:093]: 'Full spectrum counts': Sending state 76.00000 # with 0 decimals of accuracy
[10:26:27][D][sensor:093]: 'Actual gain': Sending state 1.00000  with 0 decimals of accuracy
[10:26:27][D][sensor:093]: 'Actual integration time': Sending state 400.00000 ms with 0 decimals of accuracy
[10:26:31][D][dht:048]: Got Temperature=4.7°C Humidity=99.9%
[10:26:32][D][sensor:093]: 'Temperature': Sending state 4.70000 °C with 1 decimals of accuracy
[10:26:32][D][sensor:093]:  [...]

2024-01-30 17:10 UTC, latonita commented
> It might be that this is an issue from my side, I'm not fully sure yet. I can do some more testing and comparing my code with this if necessary, but I just wanted to call out if anyone else experienced similar issues.
> 
> LTR-303 with a NodeMCU host

Hi. Thanks for reporting, would you please post follow up in this thread https://github.com/esphome/feature-requests/issues/2485 
What I see is that data coming from sensor looks ok. If you can compare manual results of this component and some arduino library you using - it would be great. here https://github.com/esphome/feature-requests/issues/2485 
thanks a lot!

2024-01-31 21:16 UTC, latonita commented on esphome/components/ltr303/ltr303.h
> +};
resolving as 'happy to disagree', moreover a lot of other things changed as well

2024-02-12 20:12 UTC, Donkie commented
> > It might be that this is an issue from my side, I'm not fully sure yet. I can do some more testing and comparing my code with this if necessary, but I just wanted to call out if anyone else experienced similar issues.
> > LTR-303 with a NodeMCU host
> 
> Hi. Thanks for reporting, would you please post follow up in this thread [esphome/feature-requests#2485](https://github.com/esphome/feature-requests/issues/2485) What I see is that data coming from sensor looks ok. If you can compare manual results of this component and some arduino library you using - it would be great. here [esphome/feature-requests#2485](https://github.com/esphome/feature-requests/issues/2485) thanks a lot!

My issues seems to have mysteriously fixed themselves, so I don't think it's an issue with the implementation, mostly an issue on my side. Thanks anyway :)

2024-03-13 00:49 UTC, kbx81 commented on tests/test2.yaml
> +    update_interval: 60s
Not needed with the new tests in place
```suggestion
```

2024-04-23 09:54 UTC, latonita commented on tests/test2.yaml
> +    update_interval: 60s
old-style test removed

2024-05-30 07:29 UTC, kbx81 reviewed
Just a couple little nitpicks/corrections for some messages and a question, but overall I think this is looking good! 😄

2024-05-30 07:29 UTC, kbx81 commented on esphome/components/ltr_als_ps/ltr_als_ps.cpp
> +  ESP_LOGCONFIG(TAG, "Setting up LTR-303/329");
I wonder if this should be expanded somehow to included all supported sensors; maybe something like this?:
```suggestion
  ESP_LOGCONFIG(TAG, "Setting up LTR-303/329/55x/659");
```

2024-05-30 07:29 UTC, kbx81 commented on esphome/components/ltr_als_ps/ltr_als_ps.cpp
> +        return "Als + PS";
Make this consistent with what's used above
```suggestion
        return "ALS + PS";
```

2024-05-30 07:29 UTC, kbx81 commented on esphome/components/ltr_als_ps/ltr_als_ps.cpp
> +    ESP_LOGE(TAG, "Communication with I2C LTR-303/329 failed!");
If we change what's logged in `setup()`...just a callout to keep this consistent.
```suggestion
    ESP_LOGE(TAG, "Communication with I2C LTR-303/329/55x/659 failed!");
```

2024-05-30 07:29 UTC, kbx81 commented on esphome/components/ltr_als_ps/ltr_als_ps.cpp
> +    ESP_LOGV(TAG, "Waiting chip to reset");
```suggestion
    ESP_LOGV(TAG, "Waiting for chip to reset");
```

2024-05-30 07:29 UTC, kbx81 commented on esphome/components/ltr_als_ps/ltr_als_ps.cpp
> +    ESP_LOGW(TAG, "Failed to finalize reset procedure");
I think I would just say:
```suggestion
    ESP_LOGW(TAG, "Reset timed out");
```

2024-05-30 07:29 UTC, kbx81 commented on esphome/components/ltr_als_ps/ltr_als_ps.cpp
> +  //  ESP_LOGV(TAG, "Got sensor data: PS = %5d, Saturation flag = %d", val, ps_high.ps_saturation_flag);
If you don't want this, please delete -- alternatively, you could make it an `ESP_LOGVV` (very verbose).

2024-05-30 07:29 UTC, kbx81 commented on esphome/components/ltr_als_ps/ltr_als_ps.cpp
> +    ESP_LOGD(TAG, "Illuminance is good enough.");
Total nitpick, but I think this looks better. haha
```suggestion
    ESP_LOGD(TAG, "Illuminance is sufficient.");
```

2024-05-30 07:29 UTC, kbx81 commented on esphome/components/ltr_als_ps/ltr_als_ps.cpp
> +  }
What is the reason for splitting the state publishing into two parts?

2024-05-30 07:36 UTC, latonita commented on esphome/components/ltr_als_ps/ltr_als_ps.cpp
> +  }
With many sensors enabled it takes time to publish and triggers 'component ... took a long time'.
I believe its not a big deal to publish in two batches, just making sure we don't hold the line.

2024-05-30 07:50 UTC, latonita commented on esphome/components/ltr_als_ps/ltr_als_ps.cpp
> +  //  ESP_LOGV(TAG, "Got sensor data: PS = %5d, Saturation flag = %d", val, ps_high.ps_saturation_flag);
forgot to remove. removed now.

2024-05-30 07:56 UTC, kbx81 commented on esphome/components/ltr_als_ps/ltr_als_ps.cpp
> +  }
I kind of figured -- thanks for confirming. 😄

2024-05-30 08:46 UTC, kbx81 approved these changes

2024-05-30 08:46 UTC, merged