Feature add last_operation to time based cover
OttoWinter/esphomeyaml pull request #6084
Opened 2024-01-12 10:26 UTC by xprofiler

# What does this implement/fix?

I need to know the last operation of the cover when handle a cover STOP command, because the current_operation is already set to IDLE. With the last operation information I am able to decide which of the two buttons (UP and DOWN) for my Warema controller I have to press to stop the cover.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/4252

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
cover:
  - platform: time_based
    name: "Sunblind AZ"
    id: sunblind_az
    open_action:
      - button.press: az_h
    open_duration: 34s
    close_action:
      - button.press: az_r
    close_duration: 32.5s
    stop_action: 
      - lambda: !lambda |-
          if (id(sunblind_az).last_operation() == CoverOperation::COVER_OPERATION_IDLE) {
            // Cover is idle
          } else if (id(sunblind_az).last_operation() == CoverOperation::COVER_OPERATION_OPENING) {
            // Cover is currently opening
            id(az_r).press();
          } else if (id(sunblind_az).last_operation() == CoverOperation::COVER_OPERATION_CLOSING) {
            // Cover is currently closing
            id(az_h).press();
          }
    has_built_in_endstop: true
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-12 10:43 UTC, xprofiler commented
I created my feature branch from tag https://github.com/esphome/esphome/tree/2023.12.5 because this is my docker containers version and the version I tested my changes.

2024-01-12 10:43 UTC, kroimon requested changes
Please rebase your branch onto the latest dev branch, there are a lot of unrelated changes in this PR.

2024-01-12 11:44 UTC, xprofiler commented
For some reason a normal rebase was not possible, so I recreated my feature branch derived from the current dev branch and make this one line change to corresponding file. I will try to test it with a current build.

2024-04-22 23:08 UTC, jesserockz commented on esphome/components/time_based/time_based_cover.h
> +  cover::CoverOperation last_operation() const { return this->last_operation_; }
```suggestion
  cover::CoverOperation get_last_operation() const { return this->last_operation_; }
```

2024-04-24 03:27 UTC, jesserockz approved these changes

2024-04-25 21:04 UTC, merged