Light component: add a way to disable restore_mode
OttoWinter/esphomeyaml pull request #6113
Opened 2024-01-17 23:28 UTC by t3chguy

# What does this implement/fix?

Adds a `restore_mode: DISABLED` enum value to the `light` component

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2547

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
remote_transmitter:
  pin: GPIO26
  carrier_duty_percent: 100%

output:
  - platform: template
    type: binary
    id: rf_magnifying_light
    write_action:
      - if:
          condition:
            light.is_on: _rf_magnifying_light
          then:
            remote_transmitter.transmit_rc_switch_raw:
              code: '001110000100011100000001'
              protocol: 1
              repeat:
                  times: 5
                  wait_time: 0s
          else:
            remote_transmitter.transmit_rc_switch_raw:
              code: '001110000100011100000011'
              protocol: 1
              repeat:
                  times: 5
                  wait_time: 0s

light:
  - platform: binary
    name: "Magnifying Light"
    output: rf_magnifying_light
    id: _rf_magnifying_light
    restore_mode: DISABLED
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-17 23:32 UTC, jesserockz approved these changes, later dismissed
LGTM

2024-01-17 23:40 UTC, t3chguy commented
@jesserockz do you think the alternative (overengineered) approach summarised [here](https://github.com/esphome/feature-requests/issues/2547#issuecomment-1897452759) would be preferable? Would be good to avoid duplication/breaking changes and getting it right off the bat if you think being able to restore the initial state without writing it out to external devices (e.g. RF) would be better.

cc @ssieb

2024-01-18 20:40 UTC, t3chguy commented
@jesserockz let me know if you're happy with this approach, works just as well as the original one for my use case. Will make the accompanying docs PR at that point

2024-06-05 06:30 UTC, ssieb commented
assumed state is very different from just not setting a value at boot.  What you're doing is only disabling restore, which seems better to be added as a restore mode like other components.

2024-07-14 22:18 UTC, jesserockz requested changes
If it is set to disabled then you should also not save the state back to flash/rtc.

2025-10-17 00:50 UTC, closed without merging