Add support for Pico-ResTouch-LCD-3.5 to ili9xxx driver
OttoWinter/esphomeyaml pull request #6129
Opened 2024-01-22 04:21 UTC by clydebarrow

# What does this implement/fix?

Support the Waveshare Pico-ResTouch-LCD-3.5. This is an ILI9488 with a custom SPI-parallel interface.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/5324

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3563

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  - platform: ili9xxx
    id: wave_disp
    model: WAVESHARE_RES_3_5
    transform:
      mirror_y: true
      swap_xy: true
    cs_pin: GPIO5
    dc_pin: GPIO22
    reset_pin: GPIO21
    spi_mode: mode0
    data_rate: 20MHz
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-01-22 12:04 UTC, nielsnl68 requested changes
Thanks for digging into this issue and found the solution. 

I was a little shocked about the extra bit in the sending method's last night when you committed this PR,  But your explanation on the issue tread did made a lot of sense.

2024-01-22 12:04 UTC, nielsnl68 commented on esphome/components/ili9xxx/ili9xxx_display.h
> +    uint8_t mad = this->color_order_ == display::COLOR_ORDER_BGR ? MADCTL_BGR : MADCTL_RGB;
From the contribution page:
- function, method and variable names are lower_snake_case
- It’s preferred to use long variable/function names over short and non-descriptive ones.

The first names where better :D

2024-01-22 12:28 UTC, nielsnl68 commented
@clydebarrow, You made the `data()` method 16 bit as explained [here](https://github.com/esphome/issues/issues/5324#issuecomment-1903213935). Should the `command()` method not also be 16 bits as well?

2024-01-22 21:00 UTC, clydebarrow commented
> @clydebarrow, You made the `data()` method 16 bit as explained [here](https://github.com/esphome/issues/issues/5324#issuecomment-1903213935). Should the `command()` method not also be 16 bits as well?

No.Waveshare does not publish a schematic or describe the logic of the interface, but the sample code does exactly what I have implemented, and it works.

2024-01-22 21:02 UTC, clydebarrow commented on esphome/components/ili9xxx/ili9xxx_display.h
> +    uint8_t mad = this->color_order_ == display::COLOR_ORDER_BGR ? MADCTL_BGR : MADCTL_RGB;
Well, the CI clang-tidy checks did not like the original names (I guess clang-tidy doesn't read the contribution page :-). They're only local to one small function and it's very obvious what they do, so there seems little point in tinkering with the names.

2024-01-23 09:38 UTC, kbx81 approved these changes

2024-01-23 09:38 UTC, kbx81 commented
@nielsnl68 I'm good with this -- are you? 😇

2024-01-23 09:50 UTC, nielsnl68 approved these changes
as it works then it is okay.

2024-01-23 20:40 UTC, merged