INA228/INA229, INA238/INA239, INA237 power/energy/charge monitor (I2C, SPI)
OttoWinter/esphomeyaml pull request #6138
Opened 2024-01-24 01:24 UTC by latonita

# What does this implement/fix?

Component enables INA228/INA229, INA238/INA239, INA237 power/energy/charge monitors

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes
https://github.com/esphome/feature-requests/issues/2549

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example configuration

esphome:
  name: ina228-test

esp32:
  board: esp32dev
  framework:
    type: arduino

# esp8266:
#   board: nodemcuv2

logger:
  level: DEBUG

external_components:
  source: github://latonita/pr#xxx
  components: [ina2xx_base, ina2xx_i2c]

i2c:

sensor:
  - platform: ina2xx_i2c
    address: 0x40
    shunt_resistance: 0.001100 ohm
    max_current: 40 A

    # adc_range 0 -> shunt V ±163.84mV , default
    # adc_range 1 -> shunt V ±40.96mV
    adc_range: 0

    # shunt resistor temp coefficient, ppm/�C, integer 0 - 16383
    #temperature_coefficient: 0
    
    update_interval: 60s
    shunt_voltage:
      name: "INA228 Shunt Voltage"
    bus_voltage:
      name: "INA228 Bus Voltage"
    current:
      name: "INA228 Current"
    power:
      name: "INA228 Power"
    energy:
      name: "INA228 Energy"
    charge:
      name: "INA228 Charge"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-02-02 09:12 UTC, taHC81 approved these changes
Fine from my side

2024-04-30 04:27 UTC, jesserockz requested changes

2024-04-30 04:27 UTC, jesserockz commented on esphome/components/ina2xx_base/__init__.py
> +        ),
Home Assistant will throw a warning for these device_class/UoM combinations.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/sensor/const.py#L172-L187

```py
    ENERGY = "energy"
    """Energy.

    Use this device class for sensors measuring energy consumption, for example
    electric energy consumption.
    Unit of measurement: `Wh`, `kWh`, `MWh`, `MJ`, `GJ`
    """

    ENERGY_STORAGE = "energy_storage"
    """Stored energy.

    Use this device class for sensors measuring stored energy, for example the amount
    of electric energy currently stored in a battery or the capacity of a battery.

    Unit of measurement: `Wh`, `kWh`, `MWh`, `MJ`, `GJ`
    """
```

2024-04-30 04:27 UTC, jesserockz commented on esphome/components/ina2xx_base/ina2xx_base.cpp
> +  static bool all_ok = true;
This will break if there are multiple devices configured in the same yaml, it should be a member variable.

2024-04-30 04:27 UTC, jesserockz commented on esphome/components/ina2xx_base/ina2xx_base.cpp
> +  }
Please add a Required `CONF_MODEL` to the config that can be used to validate and block sensors that are not supported by certain models. This user set value should also match against this device_type check and mark failed if it doesn't match and log this in `dump_config` too as a failure.

2024-04-30 04:27 UTC, jesserockz commented on esphome/components/ina2xx_base/ina2xx_base.h
> +  void set_shunt_resistance_ohm(float shunt_resistance_ohm) { shunt_resistance_ohm_ = shunt_resistance_ohm; }
> All uses of class members and member functions should be prefixed with this-> to distinguish them from global functions in code review.

https://esphome.io/guides/contributing#codebase-standards

```suggestion
  void set_shunt_resistance_ohm(float shunt_resistance_ohm) { this->shunt_resistance_ohm_ = shunt_resistance_ohm; }
```

2024-04-30 04:27 UTC, jesserockz commented on esphome/components/ina2xx_i2c/ina2xx_i2c.cpp
> +    ESP_LOGD(TAG, "read_ina_register_ failed. Reg=0x%02X Err=%d", reg, ret);
This should be an error, or at least a warning.
```suggestion
    ESP_LOGE(TAG, "read_ina_register_ failed. Reg=0x%02X Err=%d", reg, ret);
```


```suggestion
    ESP_LOGW(TAG, "read_ina_register_ failed. Reg=0x%02X Err=%d", reg, ret);
```

2024-04-30 04:27 UTC, jesserockz commented on esphome/components/ina2xx_i2c/ina2xx_i2c.cpp
> +    ESP_LOGD(TAG, "write_register failed. Reg=0x%02X Err=%d", reg, ret);
This should be an error, or at least a warning.

```suggestion
    ESP_LOGE(TAG, "write_register failed. Reg=0x%02X Err=%d", reg, ret);
```

```suggestion
    ESP_LOGW(TAG, "write_register failed. Reg=0x%02X Err=%d", reg, ret);
```

2024-04-30 04:27 UTC, jesserockz commented on esphome/components/ina2xx_i2c/sensor.py
> +    .extend(cv.COMPONENT_SCHEMA)
The base already extends polling_component_schema
```suggestion
```

2024-04-30 04:27 UTC, jesserockz commented on esphome/components/ina2xx_i2c/__init__.py
This line can actually go inside `sensor.py` along with the rest of your code. There is no need for it to be alone in the `__init__.py` file, which just needs to exist but can be blank.

2024-04-30 04:27 UTC, jesserockz commented on esphome/components/ina2xx_spi/sensor.py
> +AUTO_LOAD = ["ina2xx_base"]
Small nitpick: alphabetical order =)
```suggestion
AUTO_LOAD = ["ina2xx_base"]
CODEOWNERS = ["@latonita"]
```

2024-04-30 04:27 UTC, jesserockz commented on tests/components/ina2xx_spi/test.esp32-c3-idf.yaml
Please deduplicate these with common.yaml

2024-04-30 04:27 UTC, jesserockz commented on tests/test1.yaml
No need to add to this file.

2024-04-30 14:25 UTC, latonita commented on esphome/components/ina2xx_base/__init__.py
> +        ),
Got it. I reviewed Hass code and had to remove device classes from 3 sensors to avoid this warning.

2024-05-01 22:34 UTC, jesserockz commented on esphome/components/ina2xx_base/ina2xx_base.cpp
> +  }
Model changes look good so far. Just need to validate that the energy sensors can not be configured in yaml if the user doesn't specify a model that supports them.

2024-05-01 22:41 UTC, kbx81 commented
Don't forget to mark as "ready for review" if you're done making changes! 😄

2024-05-16 04:48 UTC, jesserockz approved these changes

2024-05-16 04:50 UTC, merged

2024-05-17 10:14 UTC, icefest commented
Is there any way to write the charge counter values into flash memory? Every power cycle wipes the result.