Add "transformer_active" flag for use in effects.
OttoWinter/esphomeyaml pull request #6157
Opened 2024-01-31 03:10 UTC by TikiBill

# What does this implement/fix?

This adds a simple boolean flag to indicate if a transformer is active such that effects may easily know when to return immediately in the apply() method. As such, it simplifies effect development.

This is in the Kauf bulb source and I used it with great success when developing a new effect. I went to bring the code over to ESPHome to contribute and realized there is no simple (that I could find) alternative.

## Types of changes

- New feature (non-breaking change which adds functionality)

This is internal only and does not affect any configuration files nor add any configurations.

2024-02-04 23:34 UTC, jesserockz requested changes

2024-02-04 23:34 UTC, jesserockz commented on esphome/components/light/light_state.h
> +
Can we change this to a protected member and add `bool is_transformer_active()`?

2024-02-05 04:34 UTC, TikiBill commented on esphome/components/light/light_state.h
> +
Thank you for the feedback. Your suggestion has been implemented.

2024-02-06 23:13 UTC, jesserockz approved these changes

2024-02-06 23:13 UTC, jesserockz commented
Thanks @TikiBill

2024-02-06 23:13 UTC, merged