LTR390 - Correct UVI calculations and fix resolution not being set
OttoWinter/esphomeyaml pull request #6161
Opened 2024-02-01 08:23 UTC by sjtrny

Addresses Issue #4380

# What does this implement/fix?

- Set resolution parameter on the device, which was not set previously.
- Added correction to UV index calculation to account for different gain and integration time combinations. 

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/4380

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: ltr390
    update_interval: 5s
    gain: "X3"
    resolution: 18
    uv_index:
      name: "UV Index"
    uv:
      name: "UV Counts"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-02-07 01:16 UTC, jesserockz requested changes

2024-02-07 01:16 UTC, jesserockz commented on esphome/components/ltr390/ltr390.h
> +
We dont put consts in the header unless they are required there, but these should stay in the cpp file please

2024-02-07 02:43 UTC, sjtrny commented on esphome/components/ltr390/ltr390.h
> +
Thanks, I've moved them into the cpp file along with other consts defined above that.

2024-02-20 21:29 UTC, jesserockz approved these changes

2024-02-21 04:10 UTC, merged