separate logger implementation for each platfor to diffrent file
OttoWinter/esphomeyaml pull request #6167
Opened 2024-02-02 21:32 UTC by tomaszduda23

# What does this implement/fix?

Make logger code a little bit more redable.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-02-05 02:17 UTC, jesserockz submitted a review, later dismissed

2024-02-05 02:17 UTC, jesserockz commented on esphome/components/logger/logger_rp2040.cpp
> +#endif
Its not possible in ESPHome to not use Arduino at this point in time so this is not needed.
```suggestion
```

2024-02-05 02:17 UTC, jesserockz commented on esphome/components/logger/logger_esp8266.cpp
> +#endif
Same here
```suggestion
```

2024-02-05 02:17 UTC, jesserockz commented on esphome/components/logger/__init__.py
> +        cg.add_build_flag("-DUSE_USB_SERIAL_JTAG")
```suggestion
        cg.add_define("-DUSE_LOGGER_USB_SERIAL_JTAG")
```

2024-02-26 08:44 UTC, kbx81 reviewed
I've tested this extensively on 8266, ESP32, S2, S3 and C3 with both USB CDC/JTAG (where supported) and serial adapter IC. Everything looks good. Just one little nitpick to make the error message a bit clearer.

2024-02-26 08:44 UTC, kbx81 commented on esphome/components/logger/__init__.py
> +            raise cv.Invalid(f"esp idf variant {variant} does not support {value}.")
```suggestion
            raise cv.Invalid(f"{value} is not supported for variant {variant} when using ESP-IDF .")
```

2024-02-26 09:06 UTC, kbx81 submitted a review, later dismissed

2024-02-26 09:07 UTC, kbx81 commented on esphome/components/logger/__init__.py
> +            raise cv.Invalid(f"{value} is not supported for variant {variant} when using ESP-IDF .")
```suggestion
            raise cv.Invalid(
                 f"{value} is not supported for variant {variant} when using ESP-IDF ."
             )
```

2024-02-26 09:48 UTC, kbx81 submitted a review, later dismissed

2024-02-26 22:25 UTC, jesserockz requested changes

2024-02-26 22:25 UTC, jesserockz commented on esphome/components/logger/logger.cpp
> +#if defined(USE_HOST) || defined(USE_ARDUINO)
I feel like since you are splitting them per platform, you should just split this out into each platform file to make it really clear.

2024-02-26 23:44 UTC, tomaszduda23 commented on esphome/components/logger/logger.cpp
> +#if defined(USE_HOST) || defined(USE_ARDUINO)
My goal here was to get rid of complex `#ifdef` since those are hard to read. I was thinking about logger_host.cpp as well. I didn't want to do that since more code would be duplicated that way. With curent structure it is not possible to get rid of platform specific things from common files completely. You would have to also do logger_esp32_arduino etc. It seems to be nice balance.

2024-02-27 03:36 UTC, jesserockz commented on esphome/components/logger/logger.cpp
> +#if defined(USE_HOST) || defined(USE_ARDUINO)
I understand the code would be duplicated, but I would rather have it split as much as possible if we are gonna do it at all.

The reason I noticed this was because when I was looking at the logger_esp32.cpp file, I was trying to find where Arduino logging was and couldn't find it which makes it more confusing I think.

I don't think you would need `logger_esp32_arduino.cpp` as the `pre_setup` code inside `logger_esp32.cpp` already does stuff for Arduino etc.

2024-03-04 21:52 UTC, jesserockz approved these changes
Thanks for making that final change. LGTM now

2024-03-04 21:52 UTC, merged