Firmware v1.5.4+ bug workaround
OttoWinter/esphomeyaml pull request #6168
Opened 2024-02-03 00:22 UTC by descipher

# What does this implement/fix?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>
#2219

## Test Environment

- [x] ESP32

## Example entry for `config.yaml`:
N/A

## Checklist:
  - [x] The code change is tested and works locally.

2024-02-04 23:37 UTC, jesserockz requested changes

2024-02-04 23:37 UTC, jesserockz commented on esphome/components/ld2420/ld2420.cpp
> +  delay_microseconds_safe(70000);  // Throttle down to no more than 22 LD2420 register writes per second
This delay is too big. If such a delay needs to be used, it should be done asynchronously with `set_timeout`

2024-02-05 03:32 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +  delay_microseconds_safe(70000);  // Throttle down to no more than 22 LD2420 register writes per second
I know and I did give ```set_timeout(70, [this, buffer](){
...
}```
a go prior to this point.
It was a total failure with the timing since the uart read() is done outside this loop. 
Keep in mind this is a workaround and it only hits this delay when editing the nvram config of the module.

2024-02-05 03:49 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +  delay_microseconds_safe(70000);  // Throttle down to no more than 22 LD2420 register writes per second
If we had interrupt driven uart capability it might work but that lib is not in ESPHome. The ESPHome scheduler does not allow the component to work with with uart data as it arrives. 
I'm just not sure how I can get the ```set_timeout``` lambda to work in this case. Any suggestions?

2024-02-05 06:26 UTC, kbx81 commented on esphome/components/ld2420/ld2420.cpp
> +  delay_microseconds_safe(70000);  // Throttle down to no more than 22 LD2420 register writes per second
Can you use `loop()` and maybe somehow build a simple state machine to throttle updates to some extent?

2024-02-05 17:59 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +  delay_microseconds_safe(70000);  // Throttle down to no more than 22 LD2420 register writes per second
I think its a good option. I will give it a go.

2024-02-10 18:22 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +  delay_microseconds_safe(70000);  // Throttle down to no more than 22 LD2420 register writes per second
Ok, I have a much better solution now, thanks @jesserockz for calling me out on the loooong delay. I have set an increased delay at the incomming cmd reply point that gives the module enough time to do it's processing avoiding the data reporting lockup state.

2024-02-14 02:45 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +  delay_microseconds_safe(70000);  // Throttle down to no more than 22 LD2420 register writes per second
This issue still occurs even with the delay. However it does dramatically reduce the frequency of occurence when initially doing any calibrations. I have ruled out the ESP state by restarting the ESPhome node b4 tests are run. Serial debug reveals the CMD sends and replies are normal. Once it occurs the module ignores any further commands.

Going to increase the delay a up to 200us more and do additional testing.

2024-02-14 03:27 UTC, descipher commented on esphome/components/ld2420/ld2420.cpp
> +  delay_microseconds_safe(70000);  // Throttle down to no more than 22 LD2420 register writes per second
Ok, looks better, 50 consective calibrations and no re-occurence with an additiona 100us.

2024-03-18 18:25 UTC, jesserockz approved these changes

2024-03-18 18:26 UTC, merged