Add some components to the new testing framework (D)
OttoWinter/esphomeyaml pull request #6175
Opened 2024-02-05 02:06 UTC by kbx81

# What does this implement/fix?

Add components beginning with the letter "D" to the new testing framework.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-02-11 23:10 UTC, jesserockz requested changes

2024-02-11 23:10 UTC, jesserockz commented on tests/components/dfplayer/test.esp32-c3-idf.yaml
I didn't think about this for other components, but all of the actions should also be in these files

2024-02-17 01:27 UTC, kbx81 commented on tests/components/dfplayer/test.esp32-c3-idf.yaml
Done 😄
I'll circle back for A/B/C (as well as the other PRs I've got open) and add them in.

2024-02-20 19:39 UTC, jesserockz approved these changes

2024-02-20 19:40 UTC, merged