DS3232M RTC Clock support
OttoWinter/esphomeyaml pull request #6182
Opened 2024-02-05 19:48 UTC by ViKozh

# What does this implement/fix?

This PR implements support for DS3232MZ RTC crystal ([DataSheet](https://www.analog.com/media/en/technical-documentation/data-sheets/ds3232m.pdf)) via i2c bus.
Supported hardware features:
 - RTC base functionality
 - Two hardware-based alarm via additional INT gpio pin on ESP chip.
 - Power type sense via additional gpio pin on ESP chip.
 - Limited support of integrated NVRAM. Only 231 of total 235 free bytes are available for numeric variables. 4 bytes are reserved for service information.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3591

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml for DS3232
  - platform: ds3232
    id: ds3232_chip
    temperature:
      name: "Chip Temperature"
    use_heartbeat: false
    interrupt_pin:
      number: GPIO18
      mode:
        input: true
        pullup: true
    reset_pin: GPIO23
    fire_alarms_on_startup: true
    first_alarm:
      mode: MATCH_DAY_OF_WEEK_AND_TIME
      time_pattern: "Wed 12:04:23"
    second_alarm:
      mode: MATCH_TIME
      time:
        minute: 10
        hour: 21
    on_first_alarm:
      then:
        - ...
    on_heartbeat:
      then:
        - ...
    on_second_alarm:
      then:
        - ...
    on_power_change:
      then:
        - ...
    persistent_storage:
      - id: counter_one
        type: uint64
        register: 0x18
        initial_value: '31415'
      - id: binary_variable
        type: bool
        register: 0x20
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (see *test1.2.yaml* under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-07 01:57 UTC, jesserockz requested changes
Please make sure that all [codebase standards](https://esphome.io/guides/contributing#codebase-standards) are followed and re-request a review after changes have been made.

2024-10-07 01:57 UTC, jesserockz commented on tests/test1.2.yaml
Please move to a new test file at `tests/components/ds3232/....yaml`

2024-10-07 01:57 UTC, jesserockz commented on esphome/components/ds3232/time.py
> +            cv.Optional(CONF_PERSISTENT_STORAGE, default={}): cv.All(
Can we remove the persistent storage stuff?
Until ESPHome has a better way of exposing these with a common API, I would rather not include it. If you are personally using it, you could probably put it into its own branch/external_component.

2024-10-07 01:57 UTC, jesserockz commented on esphome/components/ds3232/time.py
> +            ),
Could these go inside the `DS3232_ALARM_SCHEMA` for each alarm?

2024-10-07 01:57 UTC, jesserockz commented on esphome/components/ds3232/time.py
> +    return var
```suggestion
DS3232_AUTOMATION_SCHEMA = automation.maybe_simple_id(
    {
        cv.GenerateID(): cv.use_id(DS3232Component),
    }
)

@automation.register_action(
    "ds3232.factory_reset",
    FactoryResetAction,
    DS3232_AUTOMATION_SCHEMA,
)
@automation.register_action(
    "ds3232.erase_memory",
    EraseMemoryAction,
    DS3232_AUTOMATION_SCHEMA,
)
@automation.register_action(
    "ds3232.write_time",
    WriteAction,
    DS3232_AUTOMATION_SCHEMA,
)
@automation.register_action(
    "ds3232.read_time",
    ReadAction,
    DS3232_AUTOMATION_SCHEMA,
)
@automation.register_action(
    "ds3232.enable_heartbeat",
    EnableHeartbeatAction,
    DS3232_AUTOMATION_SCHEMA,
)
@automation.register_action(
    "ds3232.enable_alarms",
    EnableAlarmsAction,
    DS3232_AUTOMATION_SCHEMA,
)
@automation.register_condition(
    "ds3232.is_heartbeat_enabled",
    IsHeartbeatEnabledCondition,
    DS3232_AUTOMATION_SCHEMA,
)
async def ds3232_automation_to_code(config, automation_id, template_arg, args):
    var = cg.new_Pvariable(automation_id, template_arg)
    await cg.register_parented(var, config[CONF_ID])
    return var
```

2024-10-07 01:57 UTC, jesserockz commented on esphome/components/ds3232/time.py
> +ESPTime = cg.esphome_ns.struct("ESPTime")
https://github.com/esphome/esphome/blob/81f6750211cd98a7595d0a6320cd4d7760e161ff/esphome/cpp_types.py#L43

2024-10-07 01:57 UTC, jesserockz commented on esphome/components/ds3232/ds3232.h
> +  union DS3232RegData {
Can we organise this union so that the readable data and the raw data are a single union right next to each other to make the source code easier to understand?

2024-10-07 01:57 UTC, jesserockz commented on esphome/components/ds3232/ds3232.cpp
> +    this->read_data_();
`dump_config` is for dumping the config that is known in variables. There should be no reading from hardware in here.

2024-10-07 01:57 UTC, jesserockz commented on esphome/components/ds3232/ds3232.cpp
> +  ESP_LOGV(TAG,
Since you are adding `\n`, can you just split this into multiple ESP_LOGV lines?

2024-10-07 01:57 UTC, jesserockz commented on esphome/components/ds3232/time.py
> +def validate_alarm_(conf):
Can you use a cron-like pattern here instead of making a new one?
I realise its either a single number, or `*`, but still would be nicer to follow something we already use in ESPHome.

2026-07-30 01:37 UTC, swoboda1337 commented
Closing this out: changes were requested in October 2024 and the review comments were never addressed. If you'd like to pick this back up, feel free to open a fresh PR against current dev — DS3232M support would still be a welcome addition.

2026-07-30 01:37 UTC, closed without merging