rp2040_pio_led flicker fix and proper multi-strip support
OttoWinter/esphomeyaml pull request #6194
Opened 2024-02-07 04:50 UTC by Papa-DMan

# What does this implement/fix?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <[5450](https://github.com/esphome/issues/issues/5450)> and <[5158](https://github.com/esphome/issues/issues/5158)>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
```yaml
light:
  - platform: rp2040_pio_led_strip
    name: LED test
    id: led_strip
    pin: GPIO28
    num_leds: 30
    pio: 0
    rgb_order: GRB
    chipset: WS2812B
    effects:
      - addressable_rainbow:
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

2024-02-18 22:57 UTC, jesserockz commented on esphome/components/rp2040_pio_led_strip/led_strip.cpp
>    }
Is this not going to be nullptr all the time now?

2024-02-19 20:04 UTC, Papa-DMan commented on esphome/components/rp2040_pio_led_strip/led_strip.cpp
>    }
No when the program gets compiled down it's my understanding that the set_pio(int) function will get generated and  called based on the yaml before the final setup function runs.

2024-02-20 19:14 UTC, jesserockz commented on esphome/components/rp2040_pio_led_strip/led_strip.cpp
>    }
AH my bad, that was outside of the diff so I didnt see it.

2024-03-01 03:59 UTC, jesserockz requested changes

2024-03-01 03:59 UTC, jesserockz commented on esphome/components/rp2040_pio_led_strip/led_strip.cpp
> +}
This would be much nicer if it was just an `enum`, and have CUSTOM as `0x00` or `0xFF`

2024-05-07 22:07 UTC, jesserockz approved these changes

2024-05-15 23:33 UTC, merged