Add device_class to text_sensor
OttoWinter/esphomeyaml pull request #6202
Opened 2024-02-09 21:07 UTC by dougiteixeira

# What does this implement/fix?

It is currently not possible to use a sensor with device class TIMESTAMP or DATE with simplified configuration and automatic discovery in ESPHome using MQTT, as the MQTT integration in Home Assistant expects to receive a datetime, so it is not compatible with `sensor` that only expects values float. Previously we used `id(sntp_time).now().timestamp` to publish a value to a sensor with device class TIMESTAMP or DATE.

Currently we need to publish `ESPTime::from_epoch_utc(id(sntp_time).now().timestamp).strftime("%Y-%m-%dT%H:%M:%S+00:00")` to be compatible with integration, but it is not possible because `sensor` only accepts float.

To solve it in the simplest way, I tried to add the conversion from EPOCH UNIX to `datetime` in the MQTT integration (https://github.com/home-assistant/home-assistant.io/pull/31282), similar to how it is done in the ESPHome integration, but the change was rejected in favor of using `value_template: "{{ as_datetime( value) }}"` in the MQTT sensor or discovery topic. Which wouldn't work to keep the same configuration compatible with the API and MQTT.

Another solution I tested locally is to add `device_class` to `text_sensor`, allowing only TIMESTAMP and DATE.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/5481

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3599

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-02-21 04:20 UTC, jesserockz requested changes
Looks good, just one minor change for validation.

Could you please create the `aioesphomeapi` PR and a draft PR on `homeassistant` stating it requires a release. It would be good to get those two merged and in the 2024.3 HA release which means they need to be merged before 28th Feb for the beta there.

2024-02-21 04:20 UTC, jesserockz commented on esphome/components/text_sensor/__init__.py
> +            {cv.Optional(CONF_DEVICE_CLASS, default=device_class): cv.string}
```suggestion
            {cv.Optional(CONF_DEVICE_CLASS, default=device_class): validate_device_class}
```

2024-02-21 08:25 UTC, dougiteixeira commented
> Looks good, just one minor change for validation.
> 
> Could you please create the `aioesphomeapi` PR and a draft PR on `homeassistant` stating it requires a release. It would be good to get those two merged and in the 2024.3 HA release which means they need to be merged before 28th Feb for the beta there.

Criado:
  * `aioesphomeapi`: https://github.com/esphome/aioesphomeapi/pull/828
  * `homeassistant`: https://github.com/home-assistant/core/pull/111057 (em rascunho até liberar a nova versão de `aioesphomeapi`)

2024-02-22 15:05 UTC, dougiteixeira commented
> It would be good to get those two merged and in the 2024.3 HA release which means they need to be merged before 28th Feb for the beta there.

Hey @jesserockz, I believe this and the related PR are ready. Will we continue with them in time for the next beta version?

2024-02-25 22:20 UTC, jesserockz approved these changes

2024-02-25 22:29 UTC, merged