Mhz19 warmup
OttoWinter/esphomeyaml pull request #6214
Opened 2024-02-12 17:50 UTC by fornellas

# What does this implement/fix?

MHZ-19C seems to take somewhere between 60-75s to warm up after power on. Until that, the reported CO2 concentration seems to be rubbish, sometimes 500... sometimes 505... and it seems there's no way to know when it finishes warming up, other than... waiting.

This PR adds a configuration option to accomodate for this warmup time, and return NAN until warmup is finished, thus avoiding reporting bougus sensor readings.

The default value of 75s was empirically determined, after a series of tests.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

Any standard configuration as described https://esphome.io/components/sensor/mhz19.html should work.

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-02-25 12:27 UTC, fornellas commented
@OttoWinter , @Anonym-tsk , @glmnet it seems you worked on this previously, would you mind reviewing this please? Thanks.

2024-03-11 00:07 UTC, jesserockz requested changes

2024-03-11 00:07 UTC, jesserockz commented on esphome/components/mhz19/sensor.py
> +            ),
This cannot be templatable
```suggestion
            cv.Optional(CONF_WARMUP_TIME, default="75s"): cv.positive_time_period_seconds,
```

2024-03-11 00:07 UTC, jesserockz commented on esphome/components/mhz19/sensor.py
> +
There is a default, so it is always there
```suggestion
    cg.add(var.set_warmup_seconds(config[CONF_WARMUP_TIME]))

```

2024-03-11 18:16 UTC, jesserockz approved these changes

2024-03-11 18:17 UTC, merged