Eink 2.9 inch weact(probably others) support
OttoWinter/esphomeyaml pull request #6217
Opened 2024-02-13 07:30 UTC by alinelena

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

this is practically this pr !4579 https://github.com/esphome/esphome/pull/4579 which github closed in eagerness.

2024-02-13 07:36 UTC, alinelena commented
at this stage I would like feedabck of the most acceptable way to integrate these changes in the esphome. changes are really minimal.

2024-02-13 07:38 UTC, alinelena commented
@jbergler reopened in here... I will need to check the 3colours i wonder if your change is relevant for bw only screens too.

2024-02-13 09:52 UTC, clydebarrow requested changes
These changes modify an existing display model, which will break support for that. If you are adding support for a new model you need create a new one, copying relevant code and modifying as required. That will need changes in the CPP code and Python code.

2024-02-13 15:15 UTC, alinelena commented
> These changes modify an existing display model, which will break support for that. If you are adding support for a new model you need create a new one, copying relevant code and modifying as required. That will need changes in the CPP code and Python code.

sorry I was not very clear, I put only to show what are the changes, I am not gonna modify that screen.. just wanted to know what is the best way to add support for 2.9 given the changes are minimal. I would like not to create an entire 2.9 file that just duplicates 99% of 2.13

2024-02-15 09:25 UTC, clydebarrow commented
> I would like not to create an entire 2.9 file that just duplicates 99% of 2.13

That's the quick, easy and somewhat clunky option. The other would be to refactor the code to have a single class with suitable parameters for the different models. That involves more work, will take longer to review, and if done properly the scope could get quite broad.

Refactoring _should_ result in a better end result, but unless you have the time and skills to do it well, it's probably best to go for the the quick and easy option right now.

See https://github.com/esphome/esphome/pull/6226 for an example.

2024-02-15 09:44 UTC, alinelena commented
I have the 2.13 version of this and I can test,I remember from playing with it on another system, changes are minimal between the two vesions, similar with the bw version. 
do you want to add support for both given I test the 2.13?

2025-10-17 00:50 UTC, closed without merging