[waveshare_epaper] add support for 2.9" weact 3 color display
OttoWinter/esphomeyaml pull request #6226
Opened 2024-02-14 22:21 UTC by jbergler

# What does this implement/fix?

Adds a driver for the WeAct 2.9" 3 color (red/black/white) epaper to the waveshare_epaper component.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**

Partially addresses esphome/feature-requests#2191

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
display:
  - id: screen
    platform: waveshare_epaper
    model: 2.90in3c
    cs_pin: GPIO07
    dc_pin: GPIO01
    reset_pin: GPIO02
    reset_duration: 2ms
    busy_pin: GPIO03
    rotation: 270
    update_interval: 300s # 5m
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-02-14 23:37 UTC, clydebarrow commented on esphome/components/waveshare_epaper/weact_2p9in3c.cpp
> +#define SEND(x) this->cmd_data(x, sizeof(x))
This kind of macro can cause problems when used in certain contexts, e.g. with conditionals. While it does save typing and makes the code neater, on balance I'd suggest just having the function calls in full in the code - it's less opaque.

2024-02-14 23:42 UTC, clydebarrow commented on esphome/components/waveshare_epaper/weact_2p9in3c.cpp
> +  const uint8_t subpos = x & 0x07;
Should pre-calculate `(0x80 >> subpos) ` here:
```suggestion
  const uint8_t sub_bit = 0x80 >> (x & 0x07);
```
And replace in subsequent code accordingly.

2024-02-14 23:45 UTC, jbergler commented on esphome/components/waveshare_epaper/weact_2p9in3c.cpp
> +#define SEND(x) this->cmd_data(x, sizeof(x))
Makes sense, happy to swap that out.

FWIW though I based this on your recent PR https://github.com/esphome/esphome/pull/5363/files#diff-967f4727cde2afa27e81f14211edbbec1219f23efee46b0e5e2365dcf43e897cR58

2024-02-14 23:52 UTC, clydebarrow commented on esphome/components/waveshare_epaper/weact_2p9in3c.cpp
> +#define SEND(x) this->cmd_data(x, sizeof(x))
Oh, guilty as charged! It is interesting how you see things differently when writing vs reviewing.

2024-02-14 23:59 UTC, clydebarrow submitted a review, later dismissed

2024-02-15 00:06 UTC, clydebarrow commented
Don't forget to update the docs with the new model selection.

2024-02-15 09:43 UTC, alinelena commented
thank you!

2024-02-15 09:44 UTC, alinelena commented
I have the 2.13 version of this and I can test,I remember from playing with it on another system, changes are minimal between the two vesions, similar with the bw version.
do you want to add support for both given I test the 2.13?

2024-03-27 21:16 UTC, alinelena commented
collected few things on weact ones in here https://github.com/esphome/feature-requests/issues/2101#issuecomment-2021983529 will be nice if 2.13 will be included with this one since one bug, needs trivial changes to 2.9

2024-05-21 07:27 UTC, qwerk commented
Can someone revive this update?
my epaper module still does not work correct. I am hoping for this update to be implemented

2024-07-05 21:53 UTC, PingPongLee commented
> Can someone revive this update? my epaper module still does not work correct. I am hoping for this update to be implemented

Just adding to this. I just got this display, and its not working correctly.

Would it be possible to test this implementation out ?

2024-09-22 10:12 UTC, weado commented
Hello, 
I have a Weact 2.9 W/B/R screen with esp32C3, but the screen flickers when I push the code below. Have you ever encountered this?
`external_components:
  - source: github://pr#6226
    components: [waveshare_epaper]

spi:
  clk_pin: 4
  mosi_pin: 6

sensor:
  - platform: uptime
    name: Uptime Sensor  
    id: uptime_text

color:
  - id: red
    hex: "FF0000"
  - id: black
    hex: "FFFFFF"

# Configuration for the display
display:
  - platform: waveshare_epaper
    model: 2.90in3c
    cs_pin: 7
    dc_pin: 1
    busy_pin: 3
    reset_pin: 2
    rotation: 270
    reset_duration: 2ms
    update_interval: 30s
    id: my_display
    lambda: !lambda |-
      it.print(0, 4, id(font1), id(red), "ESPHome ePaper");
      it.print(220, 1, id(font1), id(red), "E");
      it.print(235, 0, id(font1), id(black), "E");
      it.printf(10, 60, id(font1), "uptime: %d",id(uptime_text).state);`

2024-12-29 16:14 UTC, andyhirsch commented
Same here. On every refresh I see this:

https://github.com/user-attachments/assets/49bb9e23-63db-417d-9f63-ac9d6267506e

```
esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  source: github://pr#6226
  components: [waveshare_epaper]

font:
  - file: 'gfonts://Roboto'
    id: font1
    size: 24

color:
  - id: red
    hex: "FF0000"
  - id: black
    hex: "FFFFFF"

spi:  
  mosi_pin: GPIO15
  clk_pin: GPIO02

display:
  - platform: waveshare_epaper
    model: 2.90in3c
    cs_pin: GPIO16
    dc_pin: GPIO17
    reset_pin: GPIO05
    busy_pin: GPIO18
    rotation: 270
    reset_duration: 2ms
    update_interval: 300s
    lambda: |-    
      it.print(0, 4, id(font1), id(red), "ESPHome Hello World!");
```

2025-01-07 17:57 UTC, Dewieinns commented
I just tried to utilize this library on an esp8266 and it appears to throw the device into a boot-loop (I the screen working using built-in component). Has anyone been able to make it work using an ESP8266?

2025-01-07 21:08 UTC, alinelena commented
i would expect resources to be too poor to have it work for 8266

2025-01-08 14:57 UTC, Dewieinns commented
> i would expect resources to be too poor to have it work for 8266

you are mistaken, the manufacturer provides Arduino-based examples which work on the 8266 (it works great for all 3 colors) and other libraries for the 2.9" displays work also (but none support the red color yet)

2025-01-13 18:38 UTC, mstsclev commented
![CViXDUXZPJg](https://github.com/user-attachments/assets/a32c13ae-2a70-4d64-9365-7a24bf051d97)
Работает на дисплее  Waveshare 4,2 rev v2.2 но не на весь экран. Как решить эту проблему? Возможно сделать поддержку для больших экранов тоже?

2025-01-15 11:30 UTC, mstsclev commented
It turned out that replacing two parameters in the weact_2p9in3c.cpp file is enough for the display to work properly.

`static const uint16_t HEIGHT = 300;
static const uint16_t WIDTH = 400;`

 However, there is an anomaly that displays a pink stripe at the bottom of the screen. I will attach a photo. When using "#6209" there is no such problem. But fix 6209 only supports gray tones, and does not support red.

![dsp2](https://github.com/user-attachments/assets/42aad521-fae3-4191-8350-3fb3dfc1259c)

2025-02-04 05:12 UTC, yashmulgaonkar commented
Confirmed not working for Waveshare 2.9” tricolor display with ESP32-S3.

No coherent display. Just static and random flickering.

2025-02-16 13:51 UTC, sikksakk commented
> This PR works perfectly for a Waveshare 2.9" tricolor display! Great work @jbergler !

Are you not getting flickering on refresh?

2025-02-16 19:32 UTC, yashmulgaonkar commented
The screen flickers for about 10-12sec before displaying the final graphics. This is expected with tricolor EPDs.

If you are not able to get a proper screen render, I would recommend powering the screen from a standalone PSU - NOT from the 3V3/5V pin from a microcontroller.

2025-02-28 17:37 UTC, Bobmorton-TX commented
> The screen flickers for about 10-12sec before displaying the final graphics. This is expected with tricolor EPDs.
> 
> If you are not able to get a proper screen render, I would recommend powering the screen from a standalone PSU - NOT from the 3V3/5V pin from a microcontroller.

I can confirm it works with weact 2.9 tricolor epaper - but I think the refresh time of 10+ seconds is way too long.
when i use instead of 2.90in3c
```
   model: 2.90inv2-r2
    cs_pin: GPIO15
    dc_pin: GPIO10
    reset_pin: GPIO11
    busy_pin: GPIO9
    update_interval: 2s
    full_update_every: 300
```
black and white only but the display can do partial updates quickly which is way more practical in many cases. 
Maybe partial updates can be added.
thanks for the work!!

2025-03-05 08:20 UTC, yashmulgaonkar commented
This is what the screen refresh sequence looks like:

https://github.com/user-attachments/assets/a9c911df-0fe2-4d45-a3be-43a693993975

2025-03-12 04:59 UTC, yashmulgaonkar commented
@Bobmorton-TX Unable to run your code. Can you post a barebones test yaml?

![image](https://github.com/user-attachments/assets/04987347-3cd7-44bc-92f6-f19d5e4b3cb7)

2025-03-12 05:53 UTC, yashmulgaonkar commented
@jbergler Thanks for the great work! Can confirm this works well for R/W/B tricolor displays perfectly!
Any plans on adding partial refresh or improving the refresh rates?

2025-03-12 08:41 UTC, Bobmorton-TX commented
> @Bobmorton-TX Unable to run your code. Can you post a barebones test yaml?
> 
> ![image](https://private-user-images.githubusercontent.com/824023/421697351-04987347-3cd7-44bc-92f6-f19d5e4b3cb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE3Njg5NjcsIm5iZiI6MTc0MTc2ODY2NywicGF0aCI6Ii84MjQwMjMvNDIxNjk3MzUxLTA0OTg3MzQ3LTNjZDctNDRiYy05MmY2LWYxOWQ1ZTRiM2NiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxMlQwODM3NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTNhMmUzYThjMDY1NmJjZDA4YWJmOGE2YmEwZjFjYmM2ZDFlNTJjZjRmZWVhMWExMDIwMGE0OGU0NDAzOTIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2Jd1XAevkJ_icB-RSwqon6NDAaQz40t88tBwH7WkQ5Q)

you need to remove the PR for it to be recognized. I think the PR is outdated.

` comment PR

 #external_components:
    #source: github://pr#6226
    #components: [waveshare_epaper]`

2025-03-12 18:21 UTC, 666djb commented
> @Bobmorton-TX Unable to run your code. Can you post a barebones test yaml?
> 
> ![image](https://private-user-images.githubusercontent.com/824023/421697351-04987347-3cd7-44bc-92f6-f19d5e4b3cb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE4MDM3MDIsIm5iZiI6MTc0MTgwMzQwMiwicGF0aCI6Ii84MjQwMjMvNDIxNjk3MzUxLTA0OTg3MzQ3LTNjZDctNDRiYy05MmY2LWYxOWQ1ZTRiM2NiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMxMlQxODE2NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDIwNGRiMTU3NWUzNmU2ODY5M2ZmNmYwNjFlZWVkYWYzZmRiOGQ0NmZkMmVlZTY5MjM0NzI3ZWY1NWIyOTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zcGC-JgJn7eHwP_lFqqQOn0pTBicU2oNn14tcUltoDE)

I have found if I use PR6217 (source: github://pr#6226 and model: 2.13inv3) with my three-colour WeAct 2.9" displays, then it works well in black and white mode with quick (partial) refreshes. Whereas, with PR6226, the three colours work well but require the long refresh cycle.

2025-03-12 18:23 UTC, yashmulgaonkar commented
Looks like the 15 sec refresh time is the official refresh time as per the datasheet:
![image](https://github.com/user-attachments/assets/041bf997-4eec-46f6-bc64-c857c67d254c)

2025-03-12 18:58 UTC, pzich commented
Is it expected that black and white are seemingly inverted? I initially thought that this PR wasn't working for me until I realized I needed to use `Color::WHITE` to draw black text/shapes/etc.

2025-03-12 19:13 UTC, yashmulgaonkar commented
@pzich negative. red/white/black show up as they should:
![image](https://github.com/user-attachments/assets/6aaa46f1-957b-4cff-a566-df9ec96c34e8)

2025-03-12 21:03 UTC, pzich commented
> red/white/black show up as they should

Is your config based on the one above? I see it has
```yaml
color:
  - id: red
    hex: "FF0000"
  - id: black
    hex: "FFFFFF"
 ```
 but `FFFFFF` is actually white

2025-03-21 18:13 UTC, Flaterick22 commented
Hello
Can you provide a complete test code?
I can't get it to work properly with a Wemos D1mini and WeAct 3 color display.

2025-03-24 09:34 UTC, regystro commented
> > The screen flickers for about 10-12sec before displaying the final graphics. This is expected with tricolor EPDs.
> > If you are not able to get a proper screen render, I would recommend powering the screen from a standalone PSU - NOT from the 3V3/5V pin from a microcontroller.
> 
> I can confirm it works with weact 2.9 tricolor epaper - but I think the refresh time of 10+ seconds is way too long. when i use instead of 2.90in3c
> 
> ```
>    model: 2.90inv2-r2
>     cs_pin: GPIO15
>     dc_pin: GPIO10
>     reset_pin: GPIO11
>     busy_pin: GPIO9
>     update_interval: 2s
>     full_update_every: 300
> ```
> 
> black and white only but the display can do partial updates quickly which is way more practical in many cases. Maybe partial updates can be added. thanks for the work!!

Hi @Bobmorton-TX. When I try `model: 2.90inv2-r2`, I get the whole background in red. Partial updates work as expected, and the red background becomes lighter with every update, until the next full update which paints the whole background in red again.

Could you confirm if the same happens to you? Tested with ESPHome 2025.3.1.

2025-03-24 16:59 UTC, Flaterick22 commented
Yes, I have the same behavior.

2025-05-29 10:39 UTC, 3DJupp commented
Hey, any updates on this PR?
I want to use the 2.90in3c but now there seem to be conflicts.
For the moment i will utilize GxEPD2. :smiling_face_with_tear:

2025-05-29 17:33 UTC, silvelo commented
I tested this PR with a 2.13" 3-color display and it works great.
The only thing to watch out for is making sure you use the correct dimensions for the display so everything renders properly. Great work!

2025-05-29 17:37 UTC, silvelo commented
> Hello, I have a Weact 2.9 W/B/R screen with esp32C3, but the screen flickers/blinks when I push the code below. Have you ever encountered this?
> 
> ```
> `external_components:
>   - source: github://pr#6226
>     components: [waveshare_epaper]
> 
> spi:
>   clk_pin: 4
>   mosi_pin: 6
> 
> sensor:
>   - platform: uptime
>     name: Uptime Sensor  
>     id: uptime_text
> 
> color:
>   - id: red
>     hex: "FF0000"
>   - id: black
>     hex: "FFFFFF"
> 
> display:
>   - platform: waveshare_epaper
>     model: 2.90in3c
>     cs_pin: 7
>     dc_pin: 1
>     busy_pin: 3
>     reset_pin: 2
>     rotation: 270
>     reset_duration: 2ms
>     update_interval: 30s
>     id: my_display
>     lambda: !lambda |-
>       it.print(0, 4, id(font1), id(red), "ESPHome ePaper");
>       it.print(220, 1, id(font1), id(red), "E");
>       it.print(235, 0, id(font1), id(black), "E");
>       it.printf(10, 60, id(font1), "uptime: %d",id(uptime_text).state);`
> ```

I tested this PR with a 2.13" 3-color display and it works great.
The only thing to watch out for is making sure you use the correct dimensions for the display so everything renders properly.
One thing I noticed is that the screen flickers during updates, but overall it works as expected. Great work!

2025-07-28 22:47 UTC, RaceNJason commented on esphome/components/waveshare_epaper/weact_2p9in3c.cpp
> +#define SEND(x) this->cmd_data(x, sizeof(x))
I'm not sure how to contact the author of this PR (not necessarily new to GitHub, but never reached out to someone specifically before). My purpose is that I found the newer 4.2" WeAct 3 color display works with this code with the obvious exception that it only draws out the 296x128 screen rather than the 400x300. The part the draws works perfectly. The rest is just that noise look. I'm thinking all it would take is changing the screen dimensions to the 400x300 and we'd have another supported screen.

I've made copies of all the files shown here that are modified and added the 4.2" code (or in the case of the weact_2p9in3c.cpp file, I created a modified/new weact_4p2in3c.cpp file) to do exactly this. Unfortunately I'm clueless now how to either test it with my ESPHome setup or upload it to ESPHome GitHub (so I can do my own external_component testing) and/or who to contact to do this.

Being the author of this 2.9" mod which works (and I've been using for some time), I figured this was the best place to start. I totally apologize if this is not the right way to do it and if you'd be so kind to direct me just a little I'll do it the correct way. Thanks...

2025-07-29 00:21 UTC, jesserockz requested changes
- Please resolve the conflicts
- Please add this model to the test files

2025-08-01 18:59 UTC, RaceNJason commented
I've confirmed this works with the WeAct 2.9" 3-color screen. I have also now learned how to test custom component code within ESPHome (even if it's installed on Home Assistant). Anyway, I don't know how to submit a PR or request ESPHome/Espressif make a WeActStudio_ePaper component for adding direct support instead (although I did post a request to do this on the main WaveShare_ePaper request page if that is the right way). Point of this is...

To add to this, I have now checked this PR and PR 6209 which provides support for WeAct 4.2" 2-color screen. I then added a 4.2" 3-color screen which is a modification of this (PR6226) 2.9" 3-color screen, but sized accordingly. I was able to create the custom component and pull it into a build and then test it with my screens (I have all 3 variants).

Anyway, not knowing how to submit this for use in the actual ESPHome library...for the time being I created a single repository with all 3 of these WeAct screens pulled together in a single mod (and all current WaveShare screens) for anyone to use. Letting whoever know here in case it is of use...

https://github.com/RaceNJason/WeAct-Studio_ePaper

2025-09-17 18:46 UTC, 666djb commented
> I've confirmed this works with the WeAct 2.9" 3-color screen. I have also now learned how to test custom component code within ESPHome (even if it's installed on Home Assistant). Anyway, I don't know how to submit a PR or request ESPHome/Espressif make a WeActStudio_ePaper component for adding direct support instead (although I did post a request to do this on the main WaveShare_ePaper request page if that is the right way). Point of this is...
> 
> To add to this, I have now checked this PR and PR 6209 which provides support for WeAct 4.2" 2-color screen. I then added a 4.2" 3-color screen which is a modification of this (PR6226) 2.9" 3-color screen, but sized accordingly. I was able to create the custom component and pull it into a build and then test it with my screens (I have all 3 variants).
> 
> Anyway, not knowing how to submit this for use in the actual ESPHome library...for the time being I created a single repository with all 3 of these WeAct screens pulled together in a single mod (and all current WaveShare screens) for anyone to use. Letting whoever know here in case it is of use...
> 
> https://github.com/RaceNJason/WeAct-Studio_ePaper

Your mod files work great locally as a custom component, but as they've not been merged you need to add semicolons after LOG_UPDATE_INTERVAL macros following the latest Esphome update.

2025-09-18 19:34 UTC, RaceNJason commented
> [666djb](https://github.com/666djb) Your mod files work great locally as a custom component, but as they've not been merged you need to add semicolons after LOG_UPDATE_INTERVAL macros following the latest Esphome update.

Thanks for the heads up...I've modified the repository and verified it with my local build. Hadn't done a build on that screen for a while so I hadn't noticed the change.

Any clue how to request a merger into the main code so I don't have to keep updating them anytime something like this happens? Or, because they are WeAct screens and right now ESPHome's ePaper integration heavily leans towards WaveShare products, this is unlikely to happen? I originally thought maybe splitting it to have a ePaper WaveShare integration and an ePaper WeAct integration would be best, but I think that would cause unnecessary redundancy (since many underlying protocols are similar across ePaper manufacturers) in which case maybe instead of platform waveshare_epaper it should just be epaper (then again, is it WaveShare that created the integration??). I'm just rambling...but, if you know the answer to any of these questions I'd like to learn/understand it all a little better.

2025-09-18 19:40 UTC, 666djb commented
> Any clue how to request a merger into the main code so I don't have to keep updating them anytime something like this happens? Or, because they are WeAct screens and right now ESPHome's ePaper integration heavily leans towards WaveShare products, this is unlikely to happen? I originally thought maybe splitting it to have a ePaper WaveShare integration and an ePaper WeAct integration would be best, but I think that would cause unnecessary redundancy (since many underlying protocols are similar across ePaper manufacturers) in which case maybe instead of platform waveshare_epaper it should just be epaper (then again, is it WaveShare that created the integration??). I'm just rambling...but, if you know the answer to any of these questions I'd like to learn/understand it all a little better.

I don't know how to create a pull request that will get accepted. But, if it gets to December holiday time, I might have a go because these WeAct displays work well and are good value, so should get support.

2025-10-04 17:34 UTC, 666djb commented
I've made some edits to your code @RaceNJason so that it can support the WeAct 3 Colour 2.9 inch display in black and white mode with partial refreshes based on PR #6217. I find this useful for some displays that I update each minute and where I can live without the red colour, but want to avoid the flickering of the full update. I also modified the display.py to provide unique names (as seen from within Home Assistant ESPHome Builder) to "wa2.90in" (WeAct 2.90 inch in b/w) and "wa2.90in3c" (WeAct 2.90 inch in 3 colour). Let me know if you interested and I'll put the code on github.

2025-10-09 18:46 UTC, RaceNJason commented
> @666djb Let me know if you're interested and I'll put the code on github.

Yes, I would like to keep my code updated with any WeAct screens (or mods of) that current public code doesn't cover if possible (at least until ESPHome integrates them directly since I really don't want to do this long term). Can you post a change request to my repository? Or are you just going to post what changes you did on your github site and I'll need to copy/modify them over? Thanks

2025-10-19 21:35 UTC, pgolawsk commented
This PR was working form me since early 2024:) but no longer compiles since 2025.9.0:( 
I needed to fork it, make fixes (added missing semicolons) to have still support in the latest releases.

Can we make somehow this PR accepted?

2025-11-18 17:20 UTC, dudzio12 commented
> This PR was working form me since early 2024:) but no longer compiles since 2025.9.0:( I needed to fork it, make fixes (added missing semicolons) to have still support in the latest releases.
> 
> Can we make somehow this PR accepted?

I don't want to create new PR, but this PR should be already reworked, reviewed and closed by the time..
I've prepared working fork of this branch, rebased and fixed issues, but didn't have time for a full refactor.

```xml

external_components:
  - source:
      type: git
      url: 'https://github.com/dudzio12/esphome'
      ref: weact-2.9-rbw
    components:
      - waveshare_epaper
```

2025-11-19 20:23 UTC, grericht commented
Hello, I'm using this component:

external_components:
  - source:
      type: git
      url: 'https://github.com/dudzio12/esphome'
      ref: weact-2.9-rbw
    components:
      - waveshare_epaper

I've managed to get everything displaying correctly. However, the screen refresh takes about 10 seconds. Is there a way to display time and update it every 5 seconds or even every second? I have the 2.9" BWR display

2025-11-19 21:58 UTC, clydebarrow commented
> Is there a way to display time and update it every 5 seconds or even every second?

No, e-paper is slow, and the 3-color displays are even slower. If you want a display that will be updated every second you need an LCD.

2025-11-20 17:00 UTC, RaceNJason commented
> Is there a way to display time and update it every 5 seconds or even every second?

Also...ePaper displays have a limited number of refreshes it can do. I'm not sure what happens if/when you exceed that since all I saw was that they had limited refreshes...so it could be pixels that no longer update or maybe the whole thing just stops working all together.  More advanced ePaper display's have more refresh times they are capable of...but, I don't think I've seen one with unlimited (keeping in mind I've never looked into those high end ePaper screens with fast refresh times like that ePaper monitor I saw on YouTube...but then again, those really are not meant for projects like these).

To add to what @clydebarrow said, the fastest refresh screens will be BW. Let's say it takes 3 seconds. Although not exact, add 2 seconds for each additional color. So a BWR would be 5 seconds and a 7-color screen would be about 13 seconds. All manufacturers will show refresh times though. More advanced screens allow a 'fast refresh' to the screen in like a second, but those screens generally have light ghosting of the previous images when you do the fast refresh. The slow refresh rewrites the entire image (removing the ghosting), but taking the normal slow time to do it. Those screens are definitely more expensive...I do not have one. Not sure what their refresh count is or how the fast refresh effects it's lifespan.

Anyway...I'd say maybe 5 minute intervals should be the shortest time you should refresh these types of ePaper displays and if you need it shorter, than just as @clydebarrow said, you are using the wrong screen type or you need to look into the much, much more expensive ePaper displays that have fast refresh capabilities and be willing to have a shorter lifespan of your device.

2025-11-23 14:14 UTC, marcelrv commented
> I've made some edits to your code @RaceNJason so that it can support the WeAct 3 Colour 2.9 inch display in black and white mode with partial refreshes based on PR #6217. I find this useful for some displays that I update each minute and where I can live without the red colour, but want to avoid the flickering of the full update. I also modified the display.py to provide unique names (as seen from within Home Assistant ESPHome Builder) to "wa2.90in" (WeAct 2.90 inch in b/w) and "wa2.90in3c" (WeAct 2.90 inch in 3 colour). Let me know if you interested and I'll put the code on github.

Please share how you did that.
I have the WBR display, but would like to do partial updates as the 15 seconds full refresh annoys me. I can live with it not showing red color if it would allow faster partial refreshes

2025-11-23 15:31 UTC, 666djb commented
> > @666djb Let me know if you're interested and I'll put the code on github.
> 
> Yes, I would like to keep my code updated with any WeAct screens (or mods of) that current public code doesn't cover if possible (at least until ESPHome integrates them directly since I really don't want to do this long term). Can you post a change request to my repository? Or are you just going to post what changes you did on your github site and I'll need to copy/modify them over? Thanks

I've created a PR for you to look at!

2025-11-23 15:32 UTC, 666djb commented
> > I've made some edits to your code @RaceNJason so that it can support the WeAct 3 Colour 2.9 inch display in black and white mode with partial refreshes based on PR #6217. I find this useful for some displays that I update each minute and where I can live without the red colour, but want to avoid the flickering of the full update. I also modified the display.py to provide unique names (as seen from within Home Assistant ESPHome Builder) to "wa2.90in" (WeAct 2.90 inch in b/w) and "wa2.90in3c" (WeAct 2.90 inch in 3 colour). Let me know if you interested and I'll put the code on github.
> 
> Please share how you did that. I have the WBR display, but would like to do partial updates as the 15 seconds full refresh annoys me. I can live with it not showing red color if it would allow faster partial refreshes

I've created a PR for RaceNJason, but if you want a look before anyone other than me has tested this, it's here: https://github.com/666djb/WeAct-Studio_ePaper

(I've run this code now for weeks/months with two displays updating every minute in b/w mode and a third display updating every 5 mins in 3 colour mode)

2025-11-23 16:10 UTC, marcelrv commented
> I've created a PR for RaceNJason, but if you want a look before anyone other than me has tested this, it's here: https://github.com/666djb/WeAct-Studio_ePaper

Thanks, Love it, finally I can use the display without the crazy refresh! 

Do you think it is (technically) feasible to write the red color once (at initation) and do the partial refreshes afterwards with the BW code? (not assuming the code can do that right now, but conceptually)

2025-11-23 17:22 UTC, pgolawsk commented
@RaceNJason , @666djb  Can someone of you incorporate changes for weAct displays into this PR (6226)?
It would be much easier just to have it natively within esphome code base, not via copy of source files into custom_components.

Probably some substantial work is required to merge into this PR, but the longer it's outside, the harder it will be:(
I would be happy to see that someday if possible.

Thanks a lot!

2026-01-15 22:44 UTC, BastelBaus commented
when I include the component 
```
external_components:
  source: github://pr#6226
  components: [waveshare_epaper]
```
I get currently the following error

```
Compiling .pioenvs/display-small1/src/main.cpp.o
src/esphome/components/waveshare_epaper/weact_2p9in3c.cpp: In member function 'virtual void esphome::waveshare_epaper::WeActEPaper2P9In3C::dump_config()':
src/esphome/components/waveshare_epaper/weact_2p9in3c.cpp:58:1: error: expected ';' before '}' token
   58 | }
      | ^
src/esphome/components/waveshare_epaper/waveshare_213v3.cpp: In member function 'virtual void esphome::waveshare_epaper::WaveshareEPaper2P13InV3::dump_config()':
src/esphome/components/waveshare_epaper/waveshare_213v3.cpp:179:1: error: expected ';' before '}' token
  179 | }
      | ^
*** [.pioenvs/display-small1/src/esphome/components/waveshare_epaper/weact_2p9in3c.cpp.o] Error 1
*** [.pioenvs/display-small1/src/esphome/components/waveshare_epaper/waveshare_213v3.cpp.o] Error 1

```

2026-01-25 18:28 UTC, pgolawsk commented
Quick update! WeAct 3-color e-paper display support (2.13in, 2.90in, 4.20in) is now in the `waveshare_epaper` component, based on esphome 2026.1.1.

If you wanna give it a spin, you can test it with `external_components` like this:
```yaml
external_components:
  - source: github://pr#13528
    components: [waveshare_epaper]
    refresh: 1h
```
The new `model:` options for WeAct 3-color are:
- `2.13in3c-weact`
- `2.90in3c-weact`
- `4.20in3c-weact`

I was testing it on 2.9in version, but added 2 more as well - if somebody have ability to test this pls.
Cheers!

2026-01-25 19:02 UTC, kR1StYaN commented
@pgolawsk 
I tried the new PR with my 2.9in3c-weact display. It works pretty good. But it does many full refreshes which leads to many flashes as the update takes like 8 Seconds. I tried increasing full_update_every to one hour, but compiling fails with this error:
/config/eink1.yaml: In function 'void setup()':
/config/eink1.yaml:150:44: error: 'class esphome::waveshare_epaper::WeActEPaper3C' has no member named 'set_full_update_every'
  150 | #   - id: red
      |                                            ^                    
*** [.pioenvs/eink1/src/main.cpp.o] Error 1

This are the Logs of the Updates:
[19:57:57.466][D][weact_3c:165]: Performing full e-paper update.
[19:58:22.489][D][weact_3c:165]: Performing full e-paper update.
[19:58:47.492][D][weact_3c:165]: Performing full e-paper update.
[19:59:17.504][D][weact_3c:165]: Performing full e-paper update.

This is the code i used for testing.

```yaml
font:
  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: roboto_16
    size: 16

time:
  - platform: homeassistant
    id: homeassistant_time

spi:
  mosi_pin: GPIO5  # aka SDA
  clk_pin: GPIO17  #aka SCL

color:
  - id: red
    hex: "FF0000"
  - id: black
    hex: "FFFFFF"

display:
  - platform: waveshare_epaper
    model: 2.90in3c-weact
    cs_pin: GPIO21
    dc_pin: GPIO16
    rotation: 270
    reset_pin: GPIO4
    busy_pin: GPIO0
    update_interval: 5s
    full_update_every: 3600

    lambda: !lambda |-
      it.print(0, 4, id(roboto_16), id(red), "ESPHome ePaper");
      it.print(220, 1, id(roboto_16), id(red), "E");
      it.print(235, 0, id(roboto_16), id(black), "E");
      it.strftime(230, 100, id(roboto_16), TextAlign::BASELINE_RIGHT , "Updated %H:%M %d/%b/%Y", id(homeassistant_time).now());
 ```

2026-01-26 18:43 UTC, pgolawsk commented
> @pgolawsk I tried the new PR with my 2.9in3c-weact display. It works pretty good. But it does many full refreshes which leads to many flashes as the update takes like 8 Seconds. I tried increasing full_update_every to one hour, but compiling fails with this error: /config/eink1.yaml: In function 'void setup()': /config/eink1.yaml:150:44: error: 'class esphome::waveshare_epaper::WeActEPaper3C' has no member named 'set_full_update_every' 150 | # - id: red | ^ *** [.pioenvs/eink1/src/main.cpp.o] Error 1
> 
> This are the Logs of the Updates: [19:57:57.466][D][weact_3c:165]: Performing full e-paper update. [19:58:22.489][D][weact_3c:165]: Performing full e-paper update. [19:58:47.492][D][weact_3c:165]: Performing full e-paper update. [19:59:17.504][D][weact_3c:165]: Performing full e-paper update.
> 

Hi, Thanks for testing!

The flickering is the same as for above @RaceNJason and @666djb implementations - I've just adjusted this to current ESPHome (2026.1.1) and raise official PR to include in next version. I assume this is specific for those displays - they do have very slow refresh and lot of flickering:(

Regarding `full_update_every` - this option was not implemented in above implementations either, as those WeAct displays needs update fully each time.

Maybe there is a way to improve both points, but I have no time to focus on them - just wanted to have those displays included natively in esphome, as I had enough to fix them when esphome introduce some changes and those separate repos need updates.

Thanks,

2026-02-09 23:03 UTC, pgolawsk commented
Another update!
As there was a comment for my previous PR that it uses `waveshare_epaper` deprecated component I needed to move this implementation to `epaper_spi` component... so I did that

```yaml
external_components:
  - source: github://pr#13894
    components: [epaper_spi]
    refresh: 1h
```
Example entry for config.yaml:

```yaml
# 2.9" display
display:
  - platform: epaper_spi
    model: weact-2.9in-3c
    # ...

# 4.2" display  
display:
  - platform: epaper_spi
    model: weact-4.2in-3c
    # ...
```

I was testing it on 2.9in version, but added 4.2 version as well - if somebody have ability to test this pls.
Thanks!

2026-02-20 18:07 UTC, hamster65 commented
Wow. great, thansk for this! I can finally use my 2.9" 128x296 "designed by weact studio" display :)
Red and black fonts work, but I have to do a  it.fill(Color::BLACK); first to get a white (!) background. Without this, the background is black...

2026-02-21 10:05 UTC, pgolawsk commented
> Wow. great, thansk for this! I can finally use my 2.9" 128x296 "designed by weact studio" display :) Red and black fonts work, but I have to do a it.fill(Color::BLACK); first to get a white (!) background. Without this, the background is black...

Seems I missed fill() in my config. Anyway there is already PR in place https://github.com/esphome/esphome/pull/14134 to fix that:). So once released with 2026.3 it should work.

2026-02-21 16:09 UTC, weado commented
I don't know if I'm crazy or if I just don't understand, but when I go to the epaper_spi or the Waveshare integration, I can't find any information about the WeAct display. Where can I find this information?

2026-02-21 16:37 UTC, pgolawsk commented
> I don't know if I'm crazy or if I just don't understand, but when I go to the epaper_spi or the Waveshare integration, I can't find any information about the WeAct display. Where can I find this information?

It's on dev branch at the moment, will be "published" with next version, ie. 2026.3. at present you can check it on epaper_spi on https://deploy-preview-6053--esphome.netlify.app/
Direct link: https://deploy-preview-6053--esphome.netlify.app/components/display/epaper_spi/

2026-02-22 16:53 UTC, alinelena commented
@pgolawsk do you still need someone to test the 4.2?

2026-02-23 20:12 UTC, pgolawsk commented
> @pgolawsk do you still need someone to test the 4.2? 

Hi, it was already merged, but if you can test then go ahead:) Note my PR have a bug (swapped black and white colors), fixed already on dev branch. In case issues please raise a bug to esphome. I hope it will work for you:)

2026-04-20 19:36 UTC, avg-I commented
It's great that #13894 has been merged.
But how about black-and-white WeAct displays?
I do not see them listed, maybe they are compatible with some other model?
Those do exist: https://www.aliexpress.com/item/1005005183232092.html
Also, people in this PR mentioned that the BWR displays can also be used in BW mode.

2026-07-01 03:58 UTC, closed without merging