Additional sensors and binary sensors support for Haier Climate
OttoWinter/esphomeyaml pull request #6257
Opened 2024-02-21 14:06 UTC by paveldn

# What does this implement/fix?

New sensors and binary sensors support for hOn protocol of Haier climate. Removed dependency on the sensor for climate. Fixed some warnings for hOn protocol if presets is not supported.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

uart:
  id: haier_uart
  baud_rate: 9600
  tx_pin: 1
  rx_pin: 3

climate:
  - platform: haier
    protocol: hOn
    id: haier_climate
    uart_id: haier_uart
    name: Haier AC

sensor:
  - platform: haier
    haier_id: haier_climate
    outdoor_temperature:
      name: Haier AC outdoor temperature
    humidity:
      name: Haier AC indoor humidity

binary_sensor:
  - platform: haier
    haier_id: haier_climate
    defrost_status:
      name: Haier AC defrost status

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-02-29 02:23 UTC, jesserockz requested changes

2024-02-29 02:23 UTC, jesserockz commented on esphome/components/haier/binary_sensor/__init__.py
> +            conf = config[type]
```suggestion
        if conf := config.get(type):
```

2024-02-29 02:23 UTC, jesserockz commented on esphome/components/haier/hon_packet.h
> +#define UINT16_BE(x) (((uint16_t) ((x)[0]) << 8) + (x)[1])
We have `encode_uint16()` for this already
https://github.com/esphome/esphome/blob/f53f91e191e110c22aaa16c6f94f75d3d5ab6da7/esphome/core/helpers.h#L182-L184

2024-02-29 02:23 UTC, jesserockz commented on esphome/components/haier/sensor/__init__.py
> +            conf = config[type]
Same as above
```suggestion
        if conf := config.get(type):
```

2024-02-29 02:23 UTC, jesserockz commented on tests/test3.yaml
Could you please create test files for haier in `tests/components/haier`?
Take a look at https://github.com/esphome/esphome/pull/6179/files for the tests that were going to be added for haier already. You can completly copy/paste them into this PR no problem and make the required changes.

You can then revert the changes to this file for this PR.

2024-02-29 09:45 UTC, paveldn commented on esphome/components/haier/hon_packet.h
> +#define UINT16_BE(x) (((uint16_t) ((x)[0]) << 8) + (x)[1])
Thanks, haven't seen this one before. Updated the code.

2024-02-29 09:47 UTC, paveldn commented on tests/test3.yaml
Thanks, updated the tests and included them in this PR.

2024-03-01 01:04 UTC, jesserockz approved these changes
Thanks for making those changes

2024-03-04 21:54 UTC, merged