Light sensors LTR-501, LTR-301, LTR-558
OttoWinter/esphomeyaml pull request #6262
Opened 2024-02-21 16:14 UTC by latonita

# What does this implement/fix?

Component for ambient light and proximity sensors LTR-501, LTR-301, LTR-558

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
i2c:
# ...
sensor:
  - platform: ltr501
    address: 0x23
    type: ALS_PS
    ambient_light: "Ambient light"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-22 12:57 UTC, kpfleming commented
I fully support this PR getting merged, I've been using the ltr501 component from this branch for a few months now.

2024-06-24 09:42 UTC, kbx81 commented on tests/components/ltr501/test.esp32.yaml
This file (as well as the other arduino tests) will need to be renamed to be consistent with the updated test naming scheme.

2024-06-24 09:57 UTC, latonita commented on tests/components/ltr501/test.esp32.yaml
I was going to ask 
1) whats the new schema
2) what to do with `No base test file [./tests/test_build_components/build_components_base.esp32-c3.yaml] for component test [./tests/components/ltr501/test.esp32-c3.yaml] found.`

2024-06-24 09:59 UTC, latonita commented on tests/components/ltr501/test.esp32.yaml
oh, i see some files there in 'test-build...' 
I suppose my files shall have names like 'test.esp32-c3-ard.yaml' right?

2024-06-24 13:30 UTC, latonita commented on tests/components/ltr501/test.esp32.yaml
@kbx81 done! build is passing now

2024-09-03 14:03 UTC, latonita commented
@kbx81 do you think we might move forward with this request, already becoming quite old ? :) Thanks

2024-09-07 09:32 UTC, kbx81 requested changes
Couple more nits, but otherwise LGTM

2024-09-07 09:32 UTC, kbx81 commented on esphome/components/ltr501/ltr_definitions_501.h
> +
If this isn't used, let's just remove it.

2024-09-07 09:32 UTC, kbx81 commented on esphome/components/ltr501/ltr501.cpp
> +    ESP_LOGW(TAG, "Failed to finalize reset procedure");
So many words, haha
```suggestion
    ESP_LOGW(TAG, "Reset failed");
```

2024-09-08 06:31 UTC, latonita commented on esphome/components/ltr501/ltr501.cpp
> +    ESP_LOGW(TAG, "Failed to finalize reset procedure");
This is funny ) thanks for the find. "when programmer wins over human"

2024-09-08 06:34 UTC, latonita commented on esphome/components/ltr501/ltr_definitions_501.h
> +
removed!

2024-09-09 16:07 UTC, kbx81 requested changes
One more

2024-09-09 16:07 UTC, kbx81 commented on esphome/components/ltr501/ltr501.cpp
> +        check_and_trigger_ps_();
```suggestion
        this->check_and_trigger_ps_();
```

2024-09-09 17:25 UTC, kbx81 approved these changes

2024-09-09 17:25 UTC, merged