MH-Z19: Add detection range
OttoWinter/esphomeyaml pull request #6283
Opened 2024-02-25 13:41 UTC by fornellas

# What does this implement/fix?

Add detection range setting support. It seem datasheets out there for the MH-Z19 family aren't always complete, but this one has it:

https://emariete.com/wp-content/uploads/2020/12/MH-Z19B%20(Datasheet%20del%20MH-Z19B%20en%20ingl%C3%A9s%20del%2023-09-2019).pdf

![image](https://github.com/esphome/esphome/assets/1386232/6e9f57c2-6daf-46b4-a6c6-1afa7ca5fb31)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> https://github.com/esphome/esphome-docs/pull/3636

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
substitutions:
  mhz19_warmup: "75"

esphome:
  name: "environmental"
  friendly_name: "Environmental"
  name_add_mac_suffix: true
  on_boot:
    - priority: 600.0
      then:
        - lambda: |-
            // Default: Connecting
            id(wifi_led_pwm).set_level(0.5);
            id(wifi_led_pwm).set_period(1000);
            id(wifi_led_pwm).turn_on();
        - script.execute: fast_reboot_factory_reset
    - priority: 800.0
      then:
        - lambda: |-
            // mhz19
            if(id(mhz19_abc))
              id(mhz19_sensor).abc_enable();
            else
              id(mhz19_sensor).abc_disable();
            id(mhz19_hd).turn_on();

            // pmsx003
            id(pmsx003_reset).turn_off();
            id(pmsx003_set).turn_off();
            delay(20);
            id(pmsx003_reset).turn_on();
            id(pmsx003_set).turn_on();

            // aqi_led
            id(aqi_led).set_level(0.0);
            id(aqi_led).turn_on();

  on_loop:
    then:
      - lambda: |-
          // Captive portal
          if(id(wifi_component).has_ap() && !id(wifi_component).has_sta()) {
            id(wifi_led_pwm).set_level(0.5);
            id(wifi_led_pwm).set_period(200);
          } else {
            id(wifi_led_pwm).set_period(1000);
            // Connected
            if(id(wifi_component).is_connected())
              id(wifi_led_pwm).set_level(1);
            // Connecting
            else
              id(wifi_led_pwm).set_level(0.5);
          }

esp32:
  board: esp32-c3-devkitm-1

external_components:
  - source:
      type: git
      url: https://github.com/fornellas/esphome
      ref: mhz19_patches
    components: [ mhz19 ]
    refresh: 0s

globals:
  - id: fast_reboot
    type: int
    restore_value: yes
    initial_value: '0'

  - id: factory_reset_reboot_counter
    type: int
    initial_value: '5'

  - id: mhz19_calibrate_zero_unix_timestamp
    type: time_t
    restore_value: yes
    initial_value: '0'

  - id: mhz19_abc
    type: bool
    restore_value: yes
    initial_value: 'false'

logger:
  baud_rate: 0
  level: info

script:
  - id: fast_reboot_factory_reset
    then:
      - if:
          condition:
            lambda: return ( id(fast_reboot) >= id(factory_reset_reboot_counter) );
          then:
            - lambda: |-
                ESP_LOGI("Fast Boot Factory Reset", "Performing factotry reset");
                id(fast_reboot) = 0;
                fast_reboot->loop();
                global_preferences->sync();
            - button.press: factory_reset_button
      - lambda: |-
          if(id(fast_reboot) > 0)
            ESP_LOGI("Fast Boot Factory Reset", "Quick reboot %d/%d, do it %d more times to factory reset", id(fast_reboot), id(factory_reset_reboot_counter), id(factory_reset_reboot_counter) - id(fast_reboot));
          id(fast_reboot) += 1;
          fast_reboot->loop();
          global_preferences->sync();
      - delay: 10s
      - lambda: |-
          id(fast_reboot) = 0;
          fast_reboot->loop();
          global_preferences->sync();

  - id: mhz19_calibrate_zero
    then:
      - output.turn_on: mhz19_calibration_led
      - mhz19.calibrate_zero: mhz19_sensor
      - lambda: |-
          auto time = id(sntp_time).utcnow();
          if(time.is_valid()) {
            id(mhz19_calibrate_zero_unix_timestamp) = time.timestamp;
            mhz19_calibrate_zero_unix_timestamp->loop();
            global_preferences->sync();
            ESP_LOGD("MH-Z19", "Saved zero calibration timestamp");
          } else {
            ESP_LOGW("MH-Z19", "Time unavailable, can't save zero calibration timestamp");
          }
      - delay: 2s
      - output.turn_off: mhz19_calibration_led

wifi:
  id: wifi_component
  ap:
    ap_timeout: 0s
  reboot_timeout: 0s
  power_save_mode: none

captive_portal:
    
web_server:

api:
  reboot_timeout: 0s

ota:
  safe_mode: false

uart:
  - id: uart_mhz19
    rx_pin: 5
    tx_pin: 4
    baud_rate: 9600

  - id: uart_pmsx003
    rx_pin: 1
    tx_pin:
      number: 2
      ignore_strapping_warning: true
    baud_rate: 9600

i2c:
  sda: 19
  scl: 10
  scan: false

binary_sensor:
  - platform: status
    name: "Status"

  - platform: gpio
    id: mhz19_sensor_calibrate_zero
    pin:
      number: 18
      mode: INPUT_PULLUP
    on_press:
      then:
        - script.execute:  mhz19_calibrate_zero

select:
  - platform: template
    name: "MH-Z19: Detection range"
    id: mhz19_detection_range
    icon: mdi:dots-horizontal
    entity_category: config
    optimistic: true
    options:
      - "Default"
      - "0-2000ppm"
      - "0-5000ppm"
      - "0-10000ppm"
    initial_option: "Default"
    restore_value: true
    on_value:
      then:
      - lambda: |-
          if ("0-2000ppm" == x)
            id(mhz19_sensor).detection_range(esphome::mhz19::MHZ19_DETECTION_RANGE_0_2000PPM);
          else if ("0-5000ppm" == x)
            id(mhz19_sensor).detection_range(esphome::mhz19::MHZ19_DETECTION_RANGE_0_5000PPM);
          else if ("0-10000ppm" == x)
            id(mhz19_sensor).detection_range(esphome::mhz19::MHZ19_DETECTION_RANGE_0_10000PPM);

sensor:
  - platform: uptime
    name: 'Uptime'
    update_interval: 15s

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 15s

  - platform: mhz19
    id: mhz19_sensor
    uart_id: uart_mhz19
    co2:
      id: mhz19_sensor_co2
      name: "CO₂ (UART)"
      filters:
        - lambda: |-
            return id(mhz19_non_linearity_slope).state * x + id(mhz19_non_linearity_offset).state;
    update_interval: 1s
    automatic_baseline_calibration: true
    warmup_time: "${mhz19_warmup}s"

  - platform: duty_cycle
    name: "CO₂ (PWM)"
    unit_of_measurement: "ppm"
    icon: "mdi:molecule-co2"
    accuracy_decimals: 0
    pin:
      number: 7
      mode:
        input: true
    update_interval: 1s
    filters:
      - lambda: |-
          if(millis() < ${mhz19_warmup} * 1000)
            return NAN;

          if (id(mhz19_detection_range).state == "Default")
            return NAN;
          double mul;
          if (id(mhz19_detection_range).state == "0-2000ppm")
            mul = 2.0;
          else if (id(mhz19_detection_range).state == "0-5000ppm")
            mul = 5.0;
          else if (id(mhz19_detection_range).state == "0-10000ppm")
            mul = 10.0;

          auto ppm = (x/100.0*1004.0-2.0)*mul;

          return id(mhz19_non_linearity_slope).state * ppm + id(mhz19_non_linearity_offset).state;

  - platform: template
    name: "MH-Z19: Last zero calibration unix timestamp"
    entity_category: diagnostic
    unit_of_measurement: "s"
    lambda: |-
      time_t timestamp = id(mhz19_calibrate_zero_unix_timestamp);
      if (timestamp == 0)
        return NAN;
      return timestamp;
    update_interval: 1s

  - platform: template
    name: "MH-Z19: Last zero calibration time ago"
    entity_category: [...]

2024-03-10 22:41 UTC, jesserockz requested changes

2024-03-10 22:41 UTC, jesserockz commented on esphome/components/mhz19/mhz19.h
> +  MHZ19DetectionRange detection_range_;
```suggestion
  MHZ19DetectionRange detection_range_{MHZ19_DETECTION_RANGE_DEFAULT};
```

2024-03-10 22:41 UTC, jesserockz commented on esphome/components/mhz19/sensor.py
> +            cv.Optional(CONF_DETECTION_RANGE): cv.one_of(2000, 5000, 10000, int=True),
Please add a custom validator in front of `cv.one_off` to enforce the use of `ppm` units in YAML. We try to make it so that config items have units where possible to ensure it is not just some seemingly random number that the user has to enter.

2024-03-10 22:41 UTC, jesserockz commented on esphome/components/mhz19/sensor.py
> +            cv.Optional(CONF_DETECTION_RANGE): cv.one_of(2000, 5000, 10000, int=True),
You also need to add to `to_code` to actually utilize the user choice.

2024-03-10 22:41 UTC, jesserockz commented on esphome/components/mhz19/mhz19.h
> +  void detection_range(MHZ19DetectionRange detection_range);
```suggestion
  void set_detection_range(MHZ19DetectionRange detection_range);
```

2024-03-10 22:41 UTC, jesserockz commented on esphome/components/mhz19/mhz19.cpp
> +void MHZ19Component::detection_range(MHZ19DetectionRange detection_range) {
Setter functions should not be logging and sending commands. This block of code should be in `setup` and run once there to configure the device.

2024-03-11 12:00 UTC, fornellas commented on esphome/components/mhz19/mhz19.cpp
> +void MHZ19Component::detection_range(MHZ19DetectionRange detection_range) {
@jesserockz I partially get what your'e saying here. I see the missing part at setup (fixed), but now this won't work anymore:

```
select:
  - platform: template
    name: "MH-Z19: Detection range"
    id: mhz19_detection_range
    icon: mdi:dots-horizontal
    entity_category: config
    optimistic: true
    options:
      - "Default"
      - "0-2000ppm"
      - "0-5000ppm"
      - "0-10000ppm"
    initial_option: "Default"
    restore_value: true
    on_value:
      then:
      - lambda: |-
          if ("Default" == x)
            id(mhz19_sensor).set_detection_range(esphome::mhz19::MHZ19_DETECTION_RANGE_DEFAULT);
          else if ("0-2000ppm" == x)
            id(mhz19_sensor).set_detection_range(esphome::mhz19::MHZ19_DETECTION_RANGE_0_2000PPM);
          else if ("0-5000ppm" == x)
            id(mhz19_sensor).set_detection_range(esphome::mhz19::MHZ19_DETECTION_RANGE_0_5000PPM);
          else if ("0-10000ppm" == x)
            id(mhz19_sensor).set_detection_range(esphome::mhz19::MHZ19_DETECTION_RANGE_0_10000PPM);
```

I'm not sure how to fix this, suggestions?

2024-03-11 12:31 UTC, fornellas commented on esphome/components/mhz19/mhz19.cpp
> +void MHZ19Component::detection_range(MHZ19DetectionRange detection_range) {
PS: for reference:
https://esphome.io/api/classesphome_1_1esp32__camera_1_1_e_s_p32_camera.html#ae8692b2ec8aa37e22c04fa80475ae046
this works, but is quite a confusing API to me (maybe I missed something), as the constructor that should receive the parameters don't, the set_* methods dont actually apply any changes, setup sort of fills the role of the constructor, but can't be called twice, and we rely on ad-hoc methods (such as this update one) to apply any changes.

2024-03-11 12:32 UTC, fornellas commented on esphome/components/mhz19/sensor.py
> +            cv.Optional(CONF_DETECTION_RANGE): cv.one_of(2000, 5000, 10000, int=True),
I like the idea, not sure how to get there, tried something, please review.

2024-03-11 12:32 UTC, fornellas commented
Test failures looks unrelated.

2024-03-11 18:15 UTC, jesserockz commented on esphome/components/mhz19/mhz19.cpp
> +void MHZ19Component::detection_range(MHZ19DetectionRange detection_range) {
If you want a `select` for changing the detection range, then you should build a select for the platform that provides this, not using template select.

2025-10-17 00:50 UTC, closed without merging