Add support for AT581x component
OttoWinter/esphomeyaml pull request #6297
Opened 2024-02-27 22:08 UTC by X-Ryl669

# What does this implement/fix?

This adds support for the AT581x 5.8GHz radar that's found in ESP32S3-BOX-3 device.
It's a very power efficient human detection device that configurable via I2C.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3646

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
external_components:
  - source: github://pr#5432
    components: at581x
    refresh: 0s

at581x:
  id: "Waveradar"
  i2c_id: bus_a
  detection_pin: 21

binary_sensor:
  - platform: at581x
    at581x_id: "Waveradar"
    motion_detected:
      name: "Radar motion"

switch:
  - platform: at581x
    at581x_id: "Waveradar"
    rf:
      name: "Enable Radar"

i2c:
  - id: bus_a
    sda: GPIO41
    scl: GPIO40
    sda_pullup_enabled: false
    scl_pullup_enabled: false
    scan: false
    frequency: 400kHz

esphome:
  [...]
  on_boot:
    priority: 600
    then:
      - at581x.settings:
          id: "Waveradar"
          factory_reset: false
          frequency: 5800  # In MHz
          sensing_distance: 200 # 0-1023
          poweron_selfcheck_time: 2000 # in ms
          protect_time: 1000 # in ms
          trigger_base: 500  # in ms
          trigger_keep: 10000 # in ms
          stage_gain: 3 # 0-12 the higher the value the smaller the gain
          power_consumption: 70 # in µA
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-03-13 21:07 UTC, X-Ryl669 commented
The failing CI test is completely random (and unrelated to the code). I think it's a CI failure

2024-03-14 04:20 UTC, jesserockz requested changes

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/switch/__init__.py
> +    cv.Optional(CONF_RF): switch.switch_schema(
I feel like this should have a longer, better descriptive name. Maybe `RF_POWER` or `SENSOR_POWER` etc?

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/__init__.py
> +        ),
Please move these values to a const list higher up in the file, and also validate with `cv.frequency`. We don't like having "random" number config items that don't have units

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/__init__.py
> +        ),
Same here

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/__init__.py
> +        ),
These should have units too

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/at581x.cpp
> +  return write_register(addr, &data, 1) == esphome::i2c::NO_ERROR;
All member function calls and variables should be prefixed with `this->` please
```suggestion
  return this->write_register(addr, &data, 1) == esphome::i2c::NO_ERROR;
```

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/at581x.cpp
> +  }
Not required as the macro does this already
```suggestion
  LOG_BINARY_SENSOR("", "AT581X", this->motion_binary_sensor_);
```

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/at581x.cpp
> +#define ArrSz(X) (sizeof(X) / sizeof((X)[0]))
It is preferred to use long/descriptive/meaningful names rather than short ones.
```suggestion
#define ARRAY_SIZE(X) (sizeof(X) / sizeof((X)[0]))
```

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/at581x.cpp
> +}
I don't think that this function should be called `factory_reset` considering its not actually factory resetting, but simply restarting?

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/at581x.h
> +#include "esphome/components/switch/switch.h"
All of these and any other references to the classes and variables need to be protected with `#ifdef USE_BINARY_SENSOR` etc.
If someone configures this device with no other switches for example in YAML, this will fail compilation.

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/automation.h
> +    }
The last line of `i2c_write_config` is `set_factory_reset`, so is this really needed?

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/binary_sensor.py
> +    cv.Optional(CONF_MOTION_DETECTED): binary_sensor.binary_sensor_schema(
Can we please change this to be in line with the other motion/radar/mmwave sensors?
```suggestion
    cv.Optional(CONF_HAS_TARGET): binary_sensor.binary_sensor_schema(
```

2024-03-14 04:20 UTC, jesserockz commented on esphome/components/at581x/binary_sensor.py
> +    cv.Optional(CONF_MOTION_DETECTED): binary_sensor.binary_sensor_schema(
The alternative is to not make this a child sensor of the config at all, but just directly on the CONFIG_SCHEMA since it is the only one.

2024-03-14 04:20 UTC, jesserockz commented on tests/test1.yaml
Can we move the tests into the new test file format please under `tests/components/at581x`?

2024-03-14 05:35 UTC, X-Ryl669 commented on esphome/components/at581x/__init__.py
> +        ),
The sensing distance is unitless (or it's not specified in the datasheet). 
Ok for the time stuff, they are all milliseconds.

2024-03-14 05:39 UTC, X-Ryl669 commented on esphome/components/at581x/at581x.cpp
> +}
Agree. It's the same name as in Espressif's driver but it doesn't make sense. It's more like a RF's hardware reset.

2024-03-14 05:40 UTC, X-Ryl669 commented on esphome/components/at581x/automation.h
> +    }
Yes, see above

2024-03-14 05:54 UTC, X-Ryl669 commented on esphome/components/at581x/binary_sensor.py
> +    cv.Optional(CONF_MOTION_DETECTED): binary_sensor.binary_sensor_schema(
I'm not 100% sure I get it here. This radar detects motion not static target (unlike 24GHz or 60GHz? IIUC). If you stop moving in front of the radar, the detection signal will go down. 

In the datasheet, there's also a light detection sensor, but I don't know if it's an error in the Chinese to English translation (in that case, light would mean RF emission, I'm not sure), or if it's actually here. 

What's sure is that on Box S3, the radar is under a opaque plastic cover so it can't detect light.

What do you mean about not making a child sensor, do you have an example I can look at?

2024-03-14 15:02 UTC, X-Ryl669 commented
I'm waiting to test on the real hardware before committing the last change that'll modify `esphome/const.py` for all other components (but will make the PR unusable as an `external_components`). Maybe these kinds of changes should be in another PR that should be merged at the same time as this one, what do you think?

2024-03-14 15:07 UTC, X-Ryl669 commented on tests/test1.yaml
This was a huge PITA. Since it's using I2C I had to guess what pins I could use for each supported platform (C3, C6, ESP32, ESP8266, etc...) since each have their own constraint on strapping pin/flash pins. I wasn't able to figure out how to generate the complete YAML from the test YAML on the command line, so I relied on trial and error here with the CI. 

Maybe a better documentation on how to run those tests locally is required.

2024-03-14 20:23 UTC, X-Ryl669 commented
Tested on my Box S3 and it's working as expected.

2024-03-14 23:38 UTC, jesserockz commented on esphome/components/at581x/binary_sensor.py
> +}
> I'm not 100% sure I get it here. This radar detects motion not static target (unlike 24GHz or 60GHz? IIUC). If you stop moving in front of the radar, the detection signal will go down.
> 
> In the datasheet, there's also a light detection sensor, but I don't know if it's an error in the Chinese to English translation (in that case, light would mean RF emission, I'm not sure), or if it's actually here.
>
> What's sure is that on Box S3, the radar is under a opaque plastic cover so it can't detect light.
>
> What do you mean about not making a child sensor, do you have an example I can look at?

So because this is the only binary sensor, there is no real need to have it as a deeper object in the config. See the below suggestion.

```suggestion
CONFIG_SCHEMA = (
    binary_sensor.binary_sensor_schema(
        device_class=DEVICE_CLASS_MOTION,
        icon=ICON_MOTION_SENSOR,
    ).extend(cv.Schema(
        {
            cv.GenerateID(CONF_AT581X_ID): cv.use_id(AT581XComponent),
        }
    )
)

```

This would allow config like:
```yaml
binary_sensor:
  - platform: at581x
    name: Motion Detected
    at581x_id: ...
```

2024-03-15 06:48 UTC, X-Ryl669 commented
I think everything should be ok now.

2024-03-25 22:26 UTC, jesserockz requested changes
After reviewing the code and how it actually works, I don't think this entire component needs its own binary_sensor platform and the `detection_pin` config item. 

Setting up the main component, and settings and power switch is fine, but for detecting motion, the user can just set up a `gpio` binary sensor on that pin.

2024-03-25 22:26 UTC, jesserockz commented on esphome/components/at581x/at581x.cpp
> +AT581XComponent::AT581XComponent() {}
No need to create an empty constructor
```suggestion
```

2024-03-26 22:48 UTC, jesserockz approved these changes
Thanks for making that change.

2024-03-26 22:51 UTC, merged