cc1101 radio transmitter component
OttoWinter/esphomeyaml pull request #6300
Opened 2024-02-28 11:35 UTC by gabest11

# What does this implement/fix?

Texas Instruments CC1101 transceiver component.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x ] ESP32
- [ x] ESP32 IDF
- [ x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

substitutions:
  device_name: cc1101

external_components:
  - source: github://gabest11/esphome-cc1101@main
    components: [ cc1101 ]

esphome:
  name: ${device_name}

esp32:
  board: nodemcu-32s
  variant: esp32
  framework:
    type: arduino
#  framework:
#    type: esp-idf
#    version: recommended

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_pass

logger:
  level: DEBUG

ota:
  password: !secret every_password

spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

sensor:
  - platform: cc1101
    id: transceiver
    cs_pin: GPIO5
    gdo0: GPIO32
    gdo2: GPIO33
    bandwidth: 200
    frequency: 433920
    rssi:
      name: "${device_name} rssi"
    lqi:
      name: "${device_name} lqi"
  
remote_transmitter:
  - pin: GPIO32 # GDO0
    carrier_duty_percent: 100%

remote_receiver:
  pin: GPIO33 # GDO2
  dump:
    - rc_switch
    # - raw
  # Settings to optimize recognition of RF devices
  tolerance: 50%
  #buffer_size: 2kb
  filter: 250us
  idle: 4ms

api:
  services:
    - service: 'remote_transmit'
      variables:
        code: string
      then:
        - cc1101.begin_tx: transceiver
        - remote_transmitter.transmit_rc_switch_raw:
            code: !lambda 'return code.c_str();'
            protocol:
              pulse_length: 420
              sync: [1,31]
              zero: [1,3]
              one: [3,1]
              inverted: true
            repeat:
              times: 10
        - cc1101.end_tx: transceiver

#mqtt:
#  on_json_message:
#    topic: "${device_name}/remote_transmit"
#    then:
#      - cc1101.begin_tx: transceiver
#      - remote_transmitter.transmit_rc_switch_raw:
#          code: !lambda |-
#            if(x.containsKey("code")) return x["code"];
#            return "111111111111111111111111";
#          protocol:
#            pulse_length: 420
#            sync: [1,31]
#            zero: [1,3]
#            one: [3,1]
#            inverted: false
#          repeat:
#            times: 10
#      - cc1101.end_tx: transceiver

button:
  - platform: template
    name: "${device_name} gate"
    on_press:
      - cc1101.begin_tx: transceiver
      - remote_transmitter.transmit_rc_switch_raw:
          code: '0111000110010011110110010100011111110001001011110111'
          protocol:
            pulse_length: 434
            sync: [1,6]
            zero: [1,2]
            one: [2,1]
            inverted: true
          repeat:
            times: 10
      - cc1101.end_tx: transceiver

binary_sensor:
  - platform: remote_receiver
    name: "${device_name} window"
    rc_switch_raw:
      code: '110111110001111011100110'
      protocol:
        pulse_length: 420
        sync: [1,31]
        zero: [1,3]
        one: [3,1]
        inverted: false
    filters:
      - delayed_off: 1000ms

```

## Checklist:
  - [x ] The code change is tested and works locally.
  - [x ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-02-28 16:57 UTC, gabest11 commented
"Files Changed", top entry: "This CODEOWNERS file contains errors" Any idea what it means?

2024-02-29 02:04 UTC, jesserockz requested changes
Putting this into the `sensor` component type is wrong. It should be a top level component. To introduce other radio transmitters like these, we probably need to do a refactor of the `remote_*` components first to allow better integration between them. THe user should not have to specifically call start/stop, but simply transmit and it should handle that itself.

2024-02-29 02:24 UTC, gabest11 commented
> Putting this into the `sensor` component type is wrong. It should be a top level component. 

I agree. I was looking for a fitting type, just could not find one. Other radios are all one wire, and can either receive or send, they don't really need anything other than a gpio pin.

> To introduce other radio transmitters like these, we probably need to do a refactor of the `remote_*` components first to allow better integration between them. 

I've been looking at this for two days, probably could not do it myself. The python part is a mystery, I just copy from others what fits.

> THe user should not have to specifically call start/stop, but simply transmit and it should handle that itself.

Yea, that's an annoyance. But the device needs it, otherwise it won't switch modes. Maybe something remote_transmitter.transmit_cc11001_raw, but then it needs to hook back into the original remote_transmitter.transmit_rc_switch_raw to access its functionallity.

2024-02-29 02:25 UTC, jesserockz commented
> I agree. I was looking for a fitting type, just could not find one. Other radios are all one wire, and can either receive or send, they don't really need anything other than a gpio pin.

It can at least become a top level component, like `remote_transmitter` and doesn't have to be inside sensor etc.

For the actual sensors you defined inside this PR, they can be in the sensor platform themselves and have a reference to the top level component.

2024-02-29 04:03 UTC, gabest11 commented
Is there a special requirement to get sensor.h included in the build? One of the test is failing.

2024-02-29 08:37 UTC, nagyrobi commented
> Yea, that's an annoyance. But the device needs it, otherwise it won't switch modes.

It should do it automatically behind the scenes, without having the user to put `begin_tx` and `end_tx` in the config. No need for these, just simply move their functions within your `transmit_*` trigger.

2024-02-29 18:39 UTC, gabest11 commented
> No need for these, just simply move their functions within your `transmit_*` trigger.

It's not my trigger, it belongs to the rc_switch_protocol. But working on it.

2024-02-29 21:45 UTC, gabest11 commented
It was super easy and also took surprisingly look to figure it out.

2024-02-29 23:25 UTC, Mat931 commented
I started working on the CC1101 too (over half a year ago) but was told that the existing remote receiver/transmitter code needs refactoring. So I waited with implementing the RF stuff but already got the internal temperature sensor of the CC1101 to work with ESPHome. Maybe you can use anything from that for your own CC1101 component. https://github.com/Mat931/esphome/tree/cc1101

2024-02-29 23:43 UTC, gabest11 commented
Oh well, I wish I had seen this before. When I was looking for solutions only that custom component showed up, which inspired this.

There is still a little problem with this remote_transmitter.transmit_cc1101 approach. It can only replace transmit_rc_switch_raw, not the rest of the transmit_* actions. Maybe I'll keep begin_tx, end_tx around.

2024-03-01 00:09 UTC, Mat931 commented
BTW there's a discord thread where we started collecting some ideas about refactoring the remote component: https://discord.com/channels/429907082951524364/1124742532329373728

2024-03-01 00:40 UTC, gabest11 commented
Not a Discord user, but I'll try tomorrow.

2024-03-01 06:40 UTC, PiuPiuson commented on esphome/components/cc1101/cc1101defs.h
> +static const uint32_t CC1101_MARCSTATE_RXTX_SWITCH = 0x15;
Consider converting these to constexpr to improve on RAM usage
```suggestion
static constexpr uint32_t CC1101_IOCFG2 = 0x00;    // GDO2 output pin configuration
static constexpr uint32_t CC1101_IOCFG1 = 0x01;    // GDO1 output pin configuration
static constexpr uint32_t CC1101_IOCFG0 = 0x02;    // GDO0 output pin configuration
static constexpr uint32_t CC1101_FIFOTHR = 0x03;   // RX FIFO and TX FIFO thresholds
static constexpr uint32_t CC1101_SYNC1 = 0x04;     // Sync word, high INT8U
static constexpr uint32_t CC1101_SYNC0 = 0x05;     // Sync word, low INT8U
static constexpr uint32_t CC1101_PKTLEN = 0x06;    // Packet length
static constexpr uint32_t CC1101_PKTCTRL1 = 0x07;  // Packet automation control
static constexpr uint32_t CC1101_PKTCTRL0 = 0x08;  // Packet automation control
static constexpr uint32_t CC1101_ADDR = 0x09;      // Device address
static constexpr uint32_t CC1101_CHANNR = 0x0A;    // Channel number
static constexpr uint32_t CC1101_FSCTRL1 = 0x0B;   // Frequency synthesizer control
static constexpr uint32_t CC1101_FSCTRL0 = 0x0C;   // Frequency synthesizer control
static constexpr uint32_t CC1101_FREQ2 = 0x0D;     // Frequency control word, high INT8U
static constexpr uint32_t CC1101_FREQ1 = 0x0E;     // Frequency control word, middle INT8U
static constexpr uint32_t CC1101_FREQ0 = 0x0F;     // Frequency control word, low INT8U
static constexpr uint32_t CC1101_MDMCFG4 = 0x10;   // Modem configuration
static constexpr uint32_t CC1101_MDMCFG3 = 0x11;   // Modem configuration
static constexpr uint32_t CC1101_MDMCFG2 = 0x12;   // Modem configuration
static constexpr uint32_t CC1101_MDMCFG1 = 0x13;   // Modem configuration
static constexpr uint32_t CC1101_MDMCFG0 = 0x14;   // Modem configuration
static constexpr uint32_t CC1101_DEVIATN = 0x15;   // Modem deviation setting
static constexpr uint32_t CC1101_MCSM2 = 0x16;     // Main Radio Control State Machine configuration
static constexpr uint32_t CC1101_MCSM1 = 0x17;     // Main Radio Control State Machine configuration
static constexpr uint32_t CC1101_MCSM0 = 0x18;     // Main Radio Control State Machine configuration
static constexpr uint32_t CC1101_FOCCFG = 0x19;    // Frequency Offset Compensation configuration
static constexpr uint32_t CC1101_BSCFG = 0x1A;     // Bit Synchronization configuration
static constexpr uint32_t CC1101_AGCCTRL2 = 0x1B;  // AGC control
static constexpr uint32_t CC1101_AGCCTRL1 = 0x1C;  // AGC control
static constexpr uint32_t CC1101_AGCCTRL0 = 0x1D;  // AGC control
static constexpr uint32_t CC1101_WOREVT1 = 0x1E;   // High INT8U Event 0 timeout
static constexpr uint32_t CC1101_WOREVT0 = 0x1F;   // Low INT8U Event 0 timeout
static constexpr uint32_t CC1101_WORCTRL = 0x20;   // Wake On Radio control
static constexpr uint32_t CC1101_FREND1 = 0x21;    // Front end RX configuration
static constexpr uint32_t CC1101_FREND0 = 0x22;    // Front end TX configuration
static constexpr uint32_t CC1101_FSCAL3 = 0x23;    // Frequency synthesizer calibration
static constexpr uint32_t CC1101_FSCAL2 = 0x24;    // Frequency synthesizer calibration
static constexpr uint32_t CC1101_FSCAL1 = 0x25;    // Frequency synthesizer calibration
static constexpr uint32_t CC1101_FSCAL0 = 0x26;    // Frequency synthesizer calibration
static constexpr uint32_t CC1101_RCCTRL1 = 0x27;   // RC oscillator configuration
static constexpr uint32_t CC1101_RCCTRL0 = 0x28;   // RC oscillator configuration
static constexpr uint32_t CC1101_FSTEST = 0x29;    // Frequency synthesizer calibration control
static constexpr uint32_t CC1101_PTEST = 0x2A;     // Production test
static constexpr uint32_t CC1101_AGCTEST = 0x2B;   // AGC test
static constexpr uint32_t CC1101_TEST2 = 0x2C;     // Various test settings
static constexpr uint32_t CC1101_TEST1 = 0x2D;     // Various test settings
static constexpr uint32_t CC1101_TEST0 = 0x2E;     // Various test settings

// CC1101 Strobe commands
static constexpr uint32_t CC1101_SRES = 0x30;     // Reset chip.
static constexpr uint32_t CC1101_SFSTXON = 0x31;  // Enable and calibrate frequency synthesizer (if MCSM0.FS_AUTOCAL=1).
                                              // If in RX/TX: Go to a wait state where only the synthesizer is
                                              // running (for quick RX / TX turnaround).
static constexpr uint32_t CC1101_SXOFF = 0x32;    // Turn off crystal oscillator.
static constexpr uint32_t CC1101_SCAL = 0x33;     // Calibrate frequency synthesizer and turn it off
                                              // (enables quick start).
static constexpr uint32_t CC1101_SRX = 0x34;      // Enable RX. Perform calibration first if coming from IDLE and
                                              // MCSM0.FS_AUTOCAL=1.
static constexpr uint32_t CC1101_STX = 0x35;      // In IDLE state: Enable TX. Perform calibration first if
                                              // MCSM0.FS_AUTOCAL=1. If in RX state and CCA is enabled:
                                              // Only go to TX if channel is clear.
static constexpr uint32_t CC1101_SIDLE = 0x36;    // Exit RX / TX, turn off frequency synthesizer and exit
                                              // Wake-On-Radio mode if applicable.
static constexpr uint32_t CC1101_SAFC = 0x37;     // Perform AFC adjustment of the frequency synthesizer
static constexpr uint32_t CC1101_SWOR = 0x38;     // Start automatic RX polling sequence (Wake-on-Radio)
static constexpr uint32_t CC1101_SPWD = 0x39;     // Enter power down mode when CSn goes high.
static constexpr uint32_t CC1101_SFRX = 0x3A;     // Flush the RX FIFO buffer.
static constexpr uint32_t CC1101_SFTX = 0x3B;     // Flush the TX FIFO buffer.
static constexpr uint32_t CC1101_SWORRST = 0x3C;  // Reset real time clock.
static constexpr uint32_t CC1101_SNOP = 0x3D;     // No operation. May be used to pad strobe commands to two
                                              // INT8Us for simpler software.
// CC1101 STATUS REGSITER
static constexpr uint32_t CC1101_PARTNUM = 0x30;
static constexpr uint32_t CC1101_VERSION = 0x31;
static constexpr uint32_t CC1101_FREQEST = 0x32;
static constexpr uint32_t CC1101_LQI = 0x33;
static constexpr uint32_t CC1101_RSSI = 0x34;
static constexpr uint32_t CC1101_MARCSTATE = 0x35;
static constexpr uint32_t CC1101_WORTIME1 = 0x36;
static constexpr uint32_t CC1101_WORTIME0 = 0x37;
static constexpr uint32_t CC1101_PKTSTATUS = 0x38;
static constexpr uint32_t CC1101_VCO_VC_DAC = 0x39;
static constexpr uint32_t CC1101_TXBYTES = 0x3A;
static constexpr uint32_t CC1101_RXBYTES = 0x3B;

// CC1101 PATABLE,TXFIFO,RXFIFO
static constexpr uint32_t CC1101_PATABLE = 0x3E;
static constexpr uint32_t CC1101_TXFIFO = 0x3F;
static constexpr uint32_t CC1101_RXFIFO = 0x3F;

static constexpr uint32_t CC1101_WRITE_BURST = 0x40;      // write burst
static constexpr uint32_t CC1101_READ_SINGLE = 0x80;      // read single
static constexpr uint32_t CC1101_READ_BURST = 0xC0;       // read burst
static constexpr uint32_t CC1101_BYTES_IN_RXFIFO = 0x7F;  // byte number in RXfifo

static constexpr uint32_t CC1101_MARCSTATE_TX = 0x13;
static constexpr uint32_t CC1101_MARCSTATE_TX_END = 0x14;
static constexpr uint32_t CC1101_MARCSTATE_RXTX_SWITCH = 0x15;
```

2024-03-01 09:09 UTC, gabest11 commented
Yea, compilers just put the value into the instruction operand directly, these things aren't stored anywhere.

2024-03-01 16:47 UTC, gabest11 commented
> I started working on the CC1101 too (over half a year ago) but was told that the existing remote receiver/transmitter code needs refactoring. So I waited with implementing the RF stuff but already got the internal temperature sensor of the CC1101 to work with ESPHome. Maybe you can use anything from that for your own CC1101 component. https://github.com/Mat931/esphome/tree/cc1101

I think I killed a pin on my esp32 when trying to do the temperature sensing. First copied the relevant code and only showed 0.075v, then tried yours, that worked perfectly, then flashed back mine and mocked around more, and it's dead. Tried just an adc on it with nothing else, it's completelty dead. But the rest of the board is fine. Now I'm scared to do anything :)

2024-03-01 21:29 UTC, gabest11 commented
The pin has miraculously recovered. And I got the temperature sensor working just alone in a separate yaml.

```
sensor:
  - platform: adc
    pin: GPIO32
    name: "${plug_name} ADC"
    id: gdo0_adc
    update_interval: 60s

spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

spi_device:
    id: spidev
    cs_pin: GPIO5
    data_rate: 1MHz
    mode: 0
    bit_order: msb_first

interval:
  - interval: 5s
    then:
    - lambda: !lambda |-

        auto strobe = [&](uint8_t reg) {
          id(spidev).enable();
          id(spidev).write_byte(reg);
          id(spidev).disable();          
        };

        auto write_reg = [&](uint8_t reg, uint8_t value) {
          id(spidev).enable();
          id(spidev).write_byte(reg);
          id(spidev).write_byte(value);
          id(spidev).disable();
        };

        auto read_reg = [&](uint8_t reg) -> uint8_t {
          id(spidev).enable();
          id(spidev).write_byte(reg);
          uint8_t value = id(spidev).transfer_byte(0xFF);
          id(spidev).disable();
          return value;
        };

        auto set_mode = [&](uint8_t mode, uint8_t marcstate = 0x01) {
          strobe(mode);
          for (uint16_t timeout = 5000; (read_reg(0xF5) & 0x1f) != marcstate && timeout > 0; timeout--) { delayMicroseconds(1); }
          delayMicroseconds(100);
        };

        static const uint8_t IOCFG0 = 0x02;
        static const uint8_t PTEST = 0x2A;
        static const uint8_t SRES = 0x30;
        static const uint8_t SIDLE = 0x36;
        static const uint8_t SFRX = 0x3A;
        static const uint8_t SFTX = 0x3B;

        id(spidev).enable();
        delayMicroseconds(10);
        id(spidev).disable();
        delayMicroseconds(40);
        strobe(SRES);
        delay(1);

        strobe(SFTX); // Flush TX FIFO
        delayMicroseconds(100);
        strobe(SFRX); // Flush RX FIFO
        delayMicroseconds(100);

        uint8_t part_number = read_reg(0xF0);
        uint8_t chip_version = read_reg(0xF1);
        ESP_LOGD("${plug_name}", "part_number = %02x, chip_version = %02x", part_number, chip_version);

        // this->temperature_ = this->get_temperature(1);

        set_mode(SIDLE);

        write_reg(0x02, 0x2F); // IOCFG0
        float voltage_low = id(gdo0_adc).sample();
        write_reg(0x02, 0x6F); // IOCFG0
        float voltage_high = id(gdo0_adc).sample();
        ESP_LOGD("${plug_name}", "ADC low = %f high = %f", voltage_low, voltage_high);

        write_reg(IOCFG0, 0x80); // Analog temperature output on GDO0
        write_reg(PTEST, 0xBF); // Enable temperature sensor

        delay(50);

        float voltage = 0.0f;
        int successful_samples = 0;

        for (uint8_t i = 0, num_samples = 10; i < num_samples; i++) {
          float voltage_reading = id(gdo0_adc).sample();
          ESP_LOGD("${plug_name}", "ADC voltage_reading = %f", voltage_reading);
          if (std::isfinite(voltage_reading) && voltage_reading > 0.6 &&
              voltage_reading < 1.0) {
            voltage += voltage_reading;
            successful_samples++;
          }
        }

        if (successful_samples) {
          voltage = voltage * 1000.0f / static_cast<float>(successful_samples);
        }
        else {
          voltage = NAN;
        }

        auto mapvalue = [&](float x, float in_min, float in_max, float out_min, float out_max) -> float {
          return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
        };

        float t = 0;
        
        if (voltage >= 651 && voltage < 747) {
          t = mapvalue(voltage, 651, 747, -40, 0);
        }
        else if (voltage >= 747 && voltage < 847) {
          t = mapvalue(voltage, 747, 847, 0, 40);
        }
        else if (voltage >= 847 && voltage < 945) {
          t = mapvalue(voltage, 847, 945, 40, 80);
        }
        else {
          t = NAN;
        }

        ESP_LOGD("${plug_name}", "ADC voltage = %f, temperature = %.2f", voltage, t);

        write_reg(PTEST, 0x7F); // Disable temperature sensor
        write_reg(IOCFG0, 0x80); // Restore GDO0 pin mode

        set_mode(SIDLE);
```        


[22:26:15][D][analogsensor2:105]: part_number = 00, chip_version = 14
[22:26:15][D][analogsensor2:117]: ADC low = 0.075000 high = 1.045000
[22:26:15][D][analogsensor2:129]: ADC voltage_reading = 0.806000
[22:26:15][D][analogsensor2:129]: ADC voltage_reading = 0.809000
[22:26:15][D][analogsensor2:129]: ADC voltage_reading = 0.800000
[22:26:15][D][analogsensor2:129]: ADC voltage_reading = 0.806000
[22:26:15][D][analogsensor2:129]: ADC voltage_reading = 0.806000
[22:26:15][D][analogsensor2:129]: ADC voltage_reading = 0.806000
[22:26:15][D][analogsensor2:129]: ADC voltage_reading = 0.806000
[22:26:15][D][analogsensor2:129]: ADC voltage_reading = 0.806000
[22:26:15][D][analogsensor2:129]: ADC voltage_reading = 0.809000
[22:26:15][D][analogsensor2:129]: ADC voltage_reading = 0.806000
[22:26:15][D][analogsensor2:163]: ADC voltage = 805.999939, temperature = 23.60

It measures about +2C higher than what I have in the room.

2024-03-01 21:30 UTC, gabest11 commented
Can't join the discord channel btw.

2024-03-02 03:57 UTC, gabest11 commented
remote_transmitter does not want to work together with the ADC component for some reason. ESP32. I have GDO0 on 32, GDO2 on 33. With ADC on 32 I can read the temperature. But ADC on 32, 35, 36, or any other pin in the ADC1 group (wifi and ADC2 does not work together) and transmission stops working. Just by having the ADC component there, not even using it.

2024-03-07 11:40 UTC, nagyrobi commented
fyi https://github.com/esphome/feature-requests/issues/2638

2024-03-07 11:43 UTC, gabest11 commented
I have not tried anything other than 433.92, but this should work on all frequencies.

2024-05-18 10:56 UTC, LorbusChris commented
@gabest11 thank you fir this! For access to the discord channel you first need to join the ESPhome server: https://discord.com/invite/KhAMKrd

Wondering what the state of this is, would be great to get this merged!

2024-05-27 06:14 UTC, fightforlife commented
Latest dev seems to introduce new printf handling and leading to some compilation errors.
I fixed the compilation errors for printf in https://github.com/gabest11/esphome/pull/1 (PR to this PR)

2024-06-03 18:45 UTC, fightforlife commented
@gabest11 can you add MULTI_CONF = True to the python?  It would be cool to use multiple CC1101 on one host.
e.g.:
```
cc1101:
  - id: transceiver
    cs_pin: GPIO15
    bandwidth: 200
    frequency: 433920

  - id: transceiver2
    cs_pin: GPIO33
    bandwidth: 200
    frequency: 868300
```

2024-06-17 16:44 UTC, swoboda1337 commented
> ld be a top level component. To introduce other radio transmitters like these, we probably need to do a refactor of the `remote_*` components first to allow better integration between them. The user should not have to specifically call start/

I also have an rf component that I would like to push: (https://github.com/swoboda1337/sx127x-esphome). Anyone working on this API change to start/stop transmitters automatically?

2024-06-27 16:14 UTC, swoboda1337 commented
> > ld be a top level component. To introduce other radio transmitters like these, we probably need to do a refactor of the `remote_*` components first to allow better integration between them. The user should not have to specifically call start/
> 
> I also have an rf component that I would like to push: (https://github.com/swoboda1337/sx127x-esphome). Anyone working on this API change to start/stop transmitters automatically?

I put up a draft PR (https://github.com/esphome/esphome/pull/7000) so radios can automatically enable and disable tx. The radio component would be responsible for registering a listener. Remote transmitter will call the radio listener at the beginning and end of a transmission. This way the user wont have to worry about manually starting and stopping tx. Thoughts?

2024-07-26 17:49 UTC, swoboda1337 commented
It would also be good if there was a way to configure the carrier sense thresholds. A big issue with remote receiver is it doesnt handle a lot of data very well, it seems to drop some data. Its nice to be able to filter out the noise on the RF via some threshold.

2024-10-09 11:22 UTC, swoboda1337 commented
FYI have a look at:

https://github.com/esphome/esphome-docs/pull/4275
https://github.com/esphome/esphome/pull/7483

The user can automatically switch into and out of TX mode now if they use these new triggers. 

I was also able to get both rx and tx working on the same gpio in my component. Not sure if it helps with the cc1101 though:

https://deploy-preview-4278--esphome.netlify.app/components/sx127x#as-a-transmitter-receiver

2024-10-09 11:25 UTC, gabest11 commented
I'm aware of it. Once that pull request is merged, I can update my source and start using it.

2024-10-09 12:42 UTC, swoboda1337 commented
> I'm aware of it. Once that pull request is merged, I can update my source and start using it. Edit: looks like it was, oops.

Yeah it's merged, should be in the next release. I plan on creating a set mode automation for mine. The user will have to call that in the on_transmit/on_complete triggers. Simple

2024-11-14 17:11 UTC, gabest11 commented
Just noticed a problem that happens randomly.

https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/rmt.html

> Due to a software limitation in the GPIO driver, when both TX and RX channels are bound to the same GPIO, ensure the RX Channel is initialized before the TX Channel. If the TX Channel was set up first, then during the RX Channel setup, the previous RMT TX Channel signal will be overridden by the GPIO control signal.

Put some logging and... setups are called in the unfortunate wrong order on my nodemcu-32s. If I remove the receiver, transmit works. I had this problem with before, maybe this was the reason all along.

2024-11-14 17:21 UTC, swoboda1337 commented
> Just noticed a problem that happens randomly.
> 
> https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/rmt.html
> 
> > Due to a software limitation in the GPIO driver, when both TX and RX channels are bound to the same GPIO, ensure the RX Channel is initialized before the TX Channel. If the TX Channel was set up first, then during the RX Channel setup, the previous RMT TX Channel signal will be overridden by the GPIO control signal.
> 
> Put some logging and... setups are called in the unfortunate wrong order on my nodemcu-32s. If I remove the receiver, transmit works. I had this problem with the transmitter before, maybe this was the reason all along.

A few comments:
1. We are using the deprecated RMT drivers. I have ported remote receiver and transmitter to the new drivers will put up a draft PR this week. It should be easier to get this working on the new drivers. 
2. Its tricky to get both rx and tx working with the current drivers. I have done it though. Take a look at the bottom of my docs: https://deploy-preview-4278--esphome.netlify.app/components/sx127x I change the GPIO mode from input to output and also call the transmitter setup again. It works. I can do rx and tx reliably on the same GPIO.

2024-11-14 17:25 UTC, gabest11 commented
float RemoteTransmitterComponent::get_setup_priority() const override { return setup_priority::DATA - 1; }

This fixes it.

2024-11-14 17:28 UTC, swoboda1337 commented
> float RemoteTransmitterComponent::get_setup_priority() const override { return setup_priority::DATA - 1; }
> 
> This fixes it. I had no problem using it bidirectionally on a 8266, but now switched it to a 32 to have more space and memory and it stopped working.

I don't think I was ever able to get it working on esp32 with just a priority change. Both rx and tx work?

2024-11-14 17:29 UTC, gabest11 commented
Yes, I can make it work and not work with this change.

2024-11-14 17:33 UTC, swoboda1337 commented
> Yes, I can make it work and not work with this change. But this is cc1101, might be other factors.
> 
> I see you call setup again. This can have the same effect as setting up the transmitter later.

I will try it again but I don't think changing priority was enough. BTW you can change the priority in the yaml with setup_priority: 500

2024-11-14 17:43 UTC, gabest11 commented
That's good to know!

2024-11-14 17:50 UTC, gabest11 commented
Okay... receive no longer works, lol. But I put the setup lambda before transmit and now both seem to be okay. Without changing priority.

2024-11-14 18:09 UTC, swoboda1337 commented
It works though lol. I will test more with the new drivers. Hopefully this work around will not be needed in the future.

2024-11-15 03:42 UTC, swoboda1337 commented
I verified with the new RMT drivers this work around won't be needed. I can do rx/tx without and gpio mode change or transmitter setup. Draft PR #7770 if you are interested.

2024-11-15 07:15 UTC, gabest11 commented
I'll probaby go through all my esp32 variants in single and two pin mode. Last night I remembered that I can use a second pin, I'm so dumb. It was the 8266 yaml that I adopted and totally forgot about that.

2024-12-09 19:07 UTC, chemelli74 approved these changes
Tested and working perfectly. Thx for your work !

2024-12-23 16:31 UTC, swoboda1337 commented
FYI: https://github.com/esphome/esphome/pull/8002

Should be able to use a single GPIO now, see the example yaml in this PR.

2025-02-04 21:04 UTC, fightforlife commented
I have two cc1101 running, each with a receiver and transmitter config on single wire.
Is there a way to show the receiver and transmitter ID in the logs?
Otherwise I do not know which receiver got the message. (If they are on different Mhz)

Example where both receivers are set to the same frequency:
Even in VERY_VERBOSE I did not see something.
```
[22:02:30][I][remote.raw:028]: Received Raw: 336, -938, 289, -989, 248, -1011, 859, -377, 260, -1013, 221, -1015, 247, -1008, 884, -362, 260, -989, 898, -377, 246, -1008, 231, -1016, 241, -1013, 868, -359, 275, -1011, 861, -396, 233, -998, 892, -385, 256, -989, 888, -397, 219, -1013, 
[22:02:30][I][remote.raw:028]:   246, -1006, 256, -1010, 886, -369, 244, -9720, 259, -985, 244, -1018, 227, -1011, 887, -374, 242, -1012, 246, -1002, 255, -988, 888, -396, 243, -1012, 871, -388, 234, -1016, 242, -1013, 246, -1001, 880, -404, 234, -1012, 865, -407, 227, -1036, 859, 
[22:02:30][I][remote.raw:028]:   -397, 243, -1013, 871, -388, 260, -986, 262, -1003, 257, -1000, 869, -385, 257, -9709, 267, -998, 256, -987, 261, -1012, 865, -399, 248, -1007, 232, -1011, 260, -1013, 865, -404, 226, -1010, 887, -399, 234, -1025, 222, -1042, 206, -1040, 861, -398, 
[22:02:30][I][remote.raw:028]:   219, -1036, 871, -387, 234, -1016, 891, -394, 224, -1038, 853, -414, 236, -1018, 866, -394, 870, -404, 856, -409, 235, -9718, 256, -989, 261, -1018, 236, -1004, 864, -394, 247, -1001, 254, -1015, 236, -1018, 858, -394, 223, -1040, 853, -408, 235, 
[22:02:30][I][remote.raw:041]:   -1012, 865, -401, 250, -1009, 860, -414, 219, -1036, 873, -387, 234, -1043, 850, -394, 222, -1049, 858, -413, 859, -394, 870, -404, 855, -409, 864, -422, 205
[22:02:30][W][component:237]: Component remote_receiver took a long time for an operation (95 ms).
[22:02:30][W][component:238]: Components should block for at most 30 ms.
[22:02:30][I][remote.raw:028]: Received Raw: 312, -937, 273, -993, 250, -1010, 884, -364, 266, -989, 247, -1001, 253, -984, 886, -396, 243, -988, 893, -360, 256, -1016, 237, -1012, 244, -1012, 871, -362, 255, -1015, 891, -369, 251, -988, 895, -387, 234, -1010, 887, -392, 244, -990, 
[22:02:30][I][remote.raw:028]:   250, -1010, 259, -991, 890, -369, 258, -9695, 263, -986, 266, -987, 246, -1028, 859, -378, 259, -989, 257, -1001, 246, -1005, 880, -414, 237, -1004, 875, -397, 221, -1030, 232, -1013, 236, -1017, 866, -393, 247, -1017, 877, -389, 236, -1043, 839, -393, 
[22:02:30][I][remote.raw:028]:   248, -1016, 878, -389, 236, -1018, 236, -1027, 232, -1002, 894, -388, 233, -9705, 268, -1001, 257, -1013, 236, -1013, 864, -400, 250, -1008, 232, -1010, 260, -1013, 866, -404, 226, -1012, 887, -374, 261, -1000, 246, -1042, 206, -1013, 888, -400, 233, 
[22:02:30][I][remote.raw:028]:   -1001, 894, -383, 229, -1039, 861, -423, 206, -1026, 870, -410, 232, -1012, 867, -397, 864, -420, 848, -410, 234, -9707, 270, -998, 254, -1012, 236, -988, 889, -397, 223, -1005, 256, -1036, 210, -1035, 865, -377, 250, -1010, 887, -401, 234, -1001, 869, 
[22:02:30][I][remote.raw:041]:   -405, 227, -1010, 889, -398, 218, -1038, 871, -385, 234, -1040, 858, -394, 220, -1039, 853, -409, 861, -395, 890, -401, 852, -410, 864, -424, 206
[22:02:30][W][component:237]: Component remote_receiver took a long time for an operation (112 ms).
[22:02:30][W][component:238]: Components should block for at most 30 ms.
```

2025-02-04 21:45 UTC, swoboda1337 commented
> I have two cc1101 running, each with a receiver and transmitter config on single wire. Is there a way to show the receiver and transmitter ID in the logs? Otherwise I do not know which receiver got the message. (If they are on different Mhz)
> 

There is no way to determine this from the logs atm. Probably possible to do with lambdas. Could write a simple external component to do it too,

2025-02-05 02:58 UTC, swoboda1337 commented
> I have two cc1101 running, each with a receiver and transmitter config on single wire. Is there a way to show the receiver and transmitter ID in the logs? Otherwise I do not know which receiver got the message. (If they are on different Mhz)
> 

@fightforlife you can do something like this in a lambda, will print a message before every raw dump:
```
esphome:
  on_boot:
    - priority: 0
      then:
      - lambda: |-
          class LambdaDumper : public remote_base::RemoteReceiverListener {
            public:
              LambdaDumper(std::string msg, remote_receiver::RemoteReceiverComponent *rx) : msg_(msg) {
                rx->register_listener(this);
              }
              bool on_receive(remote_base::RemoteReceiveData data) override {
                ESP_LOGD("lambda", msg_.c_str());
                remote_base::RawDumper dumper;
                dumper.dump(data);
                return true;
              }
              std::string msg_;
          };
          new LambdaDumper("Dumping rx1:", id(rx_id));
```
```
[21:57:32][D][lambda:013]: Dumping rx1:
[21:57:32][I][remote.raw:041]: Received Raw: 209, -587, 196, -196, 196, -170, 209, -392, 195
[21:57:32][D][lambda:013]: Dumping rx1:
[21:57:32][I][remote.raw:041]: Received Raw: 196
[21:57:32][D][lambda:013]: Dumping rx1:
[21:57:32][I][remote.raw:041]: Received Raw: 197, -195, 197
```

2025-02-20 16:38 UTC, jesusvallejo commented
Could you please add support for ESP32 S3?

2025-02-20 16:55 UTC, swoboda1337 commented
> Could you please add support for ESP32 S3?

What is broken on s3?

2025-02-20 17:58 UTC, jesusvallejo commented
> > Could you please add support for ESP32 S3?
> 
> What is broken on s3?

[18:56:30][E][component:082]:   Component cc1101 is marked FAILED 


The board, and layout is known to be correct as it worked following this:
https://github.com/dbuezas/esphome-cc1101 (the original esphome component)

2025-02-20 20:28 UTC, swoboda1337 commented
> this is the config (using arduino):

IDF is far better with a new version of the RMT drivers, I would move to that.

You can try my modified version. I made so tweaks to the setup for someone. Not sure it will fix it for you but you can try. 
```
external_components:
  - source: github://swoboda1337/components-esphome@main
    components: [ cc1101 ]
```

2025-02-21 07:33 UTC, jesusvallejo commented
> > this is the config (using arduino):
> 
> IDF is far better with a new version of the RMT drivers, I would move to that, remote receiver misses a lot of data on Arduino.
> 
> You can try my modified version. I made so tweaks to the setup for someone. Not sure it will fix it for you but you can try.
> 
> ```
> external_components:
>   - source: github://swoboda1337/components-esphome@main
>     components: [ cc1101 ]
> ```

Thanks, now it works!!

2025-02-22 11:09 UTC, A13X-Norton commented
> > > this is the config (using arduino):
> > 
> > 
> > IDF is far better with a new version of the RMT drivers, I would move to that, remote receiver misses a lot of data on Arduino.
> > You can try my modified version. I made so tweaks to the setup for someone. Not sure it will fix it for you but you can try.
> > ```
> > external_components:
> >   - source: github://swoboda1337/components-esphome@main
> >     components: [ cc1101 ]
> > ```
> 
> Thanks, now it works!!

Hi @all, can you help me? i have this message error when compiling PO to my esphome with your PR and OP PR:
src/esphome\components\remote_transmitter\cc1101.h:6:10: fatal error: ELECHOUSE_CC1101_SRC_DRV.h: No such file or directory

2025-02-22 13:23 UTC, swoboda1337 commented
> Hi @ALL, can you help me? i have this message error when compiling PO to my esphome with your PR and OP PR: src/esphome\components\remote_transmitter\cc1101.h:6:10: fatal error: ELECHOUSE_CC1101_SRC_DRV.h: No such file or directory

That error doesnt make any sense. You must have made some changes yourself or are using a second external component. Revert your changes or remove other external components.

2025-02-22 23:43 UTC, Malt0178 commented
Is there a way to access the CC1101 internal registers? My current use case is to command multiple fans in the 300-315MHz band with a single CC1101, but it requires changing frequencies.

2025-02-22 23:51 UTC, swoboda1337 commented
> Is there a way to access the CC1101 internal registers? My current use case is to command multiple fans in the 300-315MHz band with a single CC1101, but it requires changing frequencies.

You can try this in a lambda:
```
id(cc1101_id)->set_config_frequency(300000);
id(cc1101_id)->setup();
```
Not ideal to call setup again, this PR should provide a better way to switch frequencies. If this doeesnt work let me know I can add a way in my repo.

2025-02-23 00:21 UTC, Malt0178 commented
Thank you. That works, but it throws errors "SPI device already registered" when setup is called.

2025-02-23 00:29 UTC, swoboda1337 commented
> Thank you. That works, but it throws errors "SPI device already registered" when setup is called.

Yeah, can ignore it, pr should be updated and provide a proper reconfigure method to avoid that.

2025-03-01 07:06 UTC, gregb79 commented
HI , is it possible to change modulation type? in yaml code ?

2025-03-01 15:30 UTC, swoboda1337 commented
> HI , is it possible to change modulation type? in yaml code ?

I added modulation to my modified version if you want to give it a try. I haven't verified FSK works but you can set it:
```
external_components:
  - source: github://swoboda1337/components-esphome@main
    components: [ cc1101 ]
```

2025-03-05 00:06 UTC, gregb79 commented
> > HI , is it possible to change modulation type? in yaml code ?
> 
> I added modulation to my modified version if you want to give it a try. I haven't verified FSK works but you can set it:
> 
> ```
> external_components:
>   - source: github://swoboda1337/components-esphome@main
>     components: [ cc1101 ]
> ```

Thank you, is it possible to also expose frequency deviation?

2025-03-05 02:01 UTC, swoboda1337 commented
> Thank you, is it possible to also expose frequency deviation?

Done, I also fixed a typo in the last change. Note the docs were not clear about MSK, I don't have the time to figure it out so I just added a way to pass the register value in:
```
cc1101:
  id: cc1101_id
  cs_pin: GPIO5
  bandwidth: 200
  deviation: 0x47
  modulation: GFSK
  frequency: 433920
  ```

2025-03-05 02:21 UTC, gregb79 commented
Thank you. 

 

From: Jonathan Swoboda ***@***.***> 
Sent: Wednesday, 5 March 2025 12:02 PM
To: esphome/esphome ***@***.***>
Cc: gregb79 ***@***.***>; Manual ***@***.***>
Subject: Re: [esphome/esphome] cc1101 radio transmitter component (PR #6300)

 

Thank you, is it possible to also expose frequency deviation?

Done, I also fixed a typo in the last change. Note the docs were not clear about MSK, I don't have the time to figure it out so I just added a way to pass the register value in:

cc1101:
  id: cc1101_id
  cs_pin: GPIO5
  bandwidth: 200
  deviation: 0x47
  modulation: GFSK
  frequency: 433920

—
Reply to this email directly, view it on GitHub <https://github.com/esphome/esphome/pull/6300#issuecomment-2699543010> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABPHB3LU34XJNNPYA7UODDD2SZLILAVCNFSM6AAAAABD53DBKGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMOJZGU2DGMBRGA> .
You are receiving this because you are subscribed to this thread.  <https://github.com/notifications/beacon/ABPHB3OZYHY5O7OT2DYWT3D2SZLILA5CNFSM6AAAAABD53DBKGWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTVA47A6E.gif> Message ID: ***@***.*** ***@***.***> >

  <https://avatars.githubusercontent.com/u/154711427?s=20&v=4> swoboda1337 left a comment (esphome/esphome#6300) <https://github.com/esphome/esphome/pull/6300#issuecomment-2699543010> 

Thank you, is it possible to also expose frequency deviation?

Done, I also fixed a typo in the last change. Note the docs were not clear about MSK, I don't have the time to figure it out so I just added a way to pass the register value in:

cc1101:
  id: cc1101_id
  cs_pin: GPIO5
  bandwidth: 200
  deviation: 0x47
  modulation: GFSK
  frequency: 433920

—
Reply to this email directly, view it on GitHub <https://github.com/esphome/esphome/pull/6300#issuecomment-2699543010> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABPHB3LU34XJNNPYA7UODDD2SZLILAVCNFSM6AAAAABD53DBKGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMOJZGU2DGMBRGA> .
You are receiving this because you are subscribed to this thread.  <https://github.com/notifications/beacon/ABPHB3OZYHY5O7OT2DYWT3D2SZLILA5CNFSM6AAAAABD53DBKGWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTVA47A6E.gif> Message ID: ***@***.*** ***@***.***> >



-- 
This email has been checked for viruses by AVG antivirus software.
www.avg.com

2025-03-17 20:08 UTC, mcmasterp commented
Super excited for this to merge, thanks for everyone's hard work

2025-03-21 08:12 UTC, gabest11 commented
I'm trying to understand how AGC works. AGCCTRL2.MAGN_TARGET looks like the one to adjust if I want to see receive data from further away. There are some weather sensors in the area which simply do not generate anything, but I can see them with an sdr tuner and rtl433. The reception gets better going down to 4 or even lower. No idea about all those registers, I just kept playing with all until something changed.

2025-03-21 08:21 UTC, jesusvallejo commented
hi could you please explain how this part works, or refer to some documentation regarding the protocol part:

```
      - remote_transmitter.transmit_cc1101:
          code: '0111000110010011110110010100011111110001001011110111'
          protocol:
            pulse_length: 434
            sync: [1,6]
            zero: [1,2]
            one: [2,1]
            inverted: true
```

2025-03-21 08:27 UTC, gabest11 commented
The protocol comes from rc_switch. It will output a signal like this. If it was not inverted, the _ and - characters would be switched. One character is 434 microseconds long.

```
sync _------ 
zero _--
one __-
one __-
one __-
zero _--
```

2025-03-21 08:33 UTC, jesusvallejo commented
Oh, thanks, dont know why i could not find it hehe , thank again fro the explanation, https://esphome.io/components/remote_transmitter.html#rc-switch-protocol

2025-03-21 18:26 UTC, Malt0178 commented
> I'm trying to understand how AGC works. AGCCTRL2.MAGN_TARGET looks like the one to adjust if I want to see receive data from further away. There are some weather sensors in the area which simply do not generate anything, but I can see them with an sdr tuner and rtl433. The reception gets better going down to 4 or even lower. No idea about all those registers, I just kept playing with them until something changed.

From a non-RF person, but a couple of ideas:

Since you receive better with the SDR, maybe it’s the CC1101 antenna. If you can, move the SDR antenna to the CC1101 and do some testing. I’ve done this (same connector) and it proved beneficial to identify that adding the dipole ground leg to the CC1101 made a big difference.

What’s the RSSI from the SDR vs the CC1101 and can you use the CC1101 RSSI to optimize any changes made to the AGC registers?

TI CC1101 Design Note 22 might offer some help. Search CC1101 DN022.

2025-03-21 18:37 UTC, gabest11 commented
It's three cc1101's with just a piece of wire soldered to it as the antenna. All of them need a different value to get the best results. The antenna on the sdr tuner has a regular RF connector, so it would be hard to connect it without cutting it... I think I'll add a few number components and experiment in real time.

<img width="668" alt="image" src="https://github.com/user-attachments/assets/f0dd7b72-5105-4e1b-81b1-c981bbc32b16" />

2025-03-21 19:16 UTC, Malt0178 commented
OK, my CC1101s have the rf connector so it’s easy for me to switch. Ultimately, I solder both a signal wire and equivalent ground wire for the antenna to improve transmission/reception.

I also read “red” as the worst noise floor to overcome for reception in your plot.

2025-03-23 01:18 UTC, chemelli74 commented
Is there anything preventing the merge of tips marvelous PR ?

2025-03-23 01:25 UTC, mcmasterp commented
> Is there anything preventing the merge of tips marvelous PR ?

Yeah i can't seem to find a way to view the change requested.  Not that I can do anything to help im no fool, but I figured it would give me an idea of how big the obstacles to merge are. Oh well

2025-03-23 08:27 UTC, gabest11 commented
> > Is there anything preventing the merge of tips marvelous PR ?
> 
> Yeah i can't seem to find a way to view the change requested. Not that I can do anything to help im no fool, but I figured it would give me an idea of how big the obstacles to merge are. Oh well

I think it was to move it from sensor component to top level.

2025-03-23 13:05 UTC, chemelli74 commented
> > Is there anything preventing the merge of tips marvelous PR ?
> 
> Yeah i can't seem to find a way to view the change requested.

https://github.com/esphome/esphome/pull/6300#pullrequestreview-1907801134

2025-03-23 15:08 UTC, gabest11 commented
I'm rewriting the whole thing to support changing as many parameters as possible. 

There are some settings which might have come from smartrf studio, at least that's what the datasheet recommends to use to figure out the optimal value. Not sure if they are needed, it seems to work fine with the default values set after reset.

The calibration part is also strange. With the FSCTRL0, TEST0, FSCAL2 registers. Not sure what's going on there.

2025-03-24 01:26 UTC, gabest11 commented
This is how it now looks in HA. Tuning tested, AGC not much, but we definitely need the old setup values to work properly.

<img width="367" alt="image" src="https://github.com/user-attachments/assets/4486843b-bb6b-4d0f-9e60-81c0024e5a16" />

2025-03-24 01:30 UTC, mcmasterp commented
> This is how it now looks in HA. Tuning tested, AGC not so much, but we definitely need the old setup values to work properly.
> <img alt="image" width="367" src="https://private-user-images.githubusercontent.com/8768197/425890772-4486843b-bb6b-4d0f-9e60-81c0024e5a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI3ODAwODYsIm5iZiI6MTc0Mjc3OTc4NiwicGF0aCI6Ii84NzY4MTk3LzQyNTg5MDc3Mi00NDg2ODQzYi1iYjZiLTRkMGYtOWU2MC04MWMwMDI0ZTVhMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMjRUMDEyOTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzliY2YyODJlMTI3ZTJkZWVhODFiNTg5MjM3OTc4NjQ4OTk2NmMzMTgwNjQ5YThlYzk1NmRlNWVkYWQzMWExYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.w6ImGQXpjqMsBunFqJhKEldyYMFWWCOytslV9KLgnro">

whoa whats the yaml to get all that!

2025-03-24 15:59 UTC, jbrandek commented
hi one question when i try to use 
`- platform: template
    name: "Send RF Code"
    on_press:
      - remote_transmitter.transmit_cc1101:
          code: '0111000110010011110110010100011111110001001011110111'
          protocol:
            pulse_length: 434
            sync: [1,6]
            zero: [1,2]
            one: [2,1]
            inverted: true`
i get the error -> Unable to find action with the name 'remote_transmitter.transmit_cc1101'

if i use a normal rc_switch_raw: i get no errors but it does not work, it does not send any rf to the device
im trying this:
`- remote_transmitter.transmit_rc_switch_raw:
          code: '000000000000001000010'  # Replace with the code you want to send
          protocol: 6`

any help if im missing something, i can read other devices on the house but cannot send anything

2025-03-24 16:23 UTC, swoboda1337 commented
@gabest11 sorry looks like my pr https://github.com/esphome/esphome/pull/8455 has exposed some issue with S2 and is causing your build to fail.

2025-03-25 00:18 UTC, gabest11 commented
@jbrandek You should use rc_switch_raw and enable call begin_tx, end_ex. Do you have them under remote_transmitter?

```
remote_transmitter:
  on_transmit:
    then:
      - cc1101.begin_tx: transceiver
  on_complete:
    then:
      - cc1101.end_tx: transceiver
```

2025-03-25 00:21 UTC, gabest11 commented
@swoboda1337 I was wondering about that..., an unexplainable error happens sometimes with these tests, but then it always fixes itself.

2025-03-25 00:22 UTC, gabest11 commented
Btw, nearly all the code was rewritten, I am surprised it even works. Did anyone notice anything strange?

2025-03-25 01:44 UTC, Malt0178 commented
Setting tuner frequency in yaml to 303 MHz transmits garbage at that frequency. If I subsequently set the same frequency via a lambda or tick the tuner frequency number in HA it works great. Subsequent frequency changes all work. I really like the changes and appreciate your efforts.

2025-03-25 01:49 UTC, gabest11 commented
That might be the order of setting the registers. It's not clear if I can just sequentially upload all of them during setup in its idle state. Even the frequency is split between three registers, there is no "atomic" way to change it.

2025-03-25 02:13 UTC, Malt0178 commented
Just reiterating the initial frequency was set correctly. Verified via SDR. The data transmitted remains garbage until frequency is set again.

2025-03-25 08:34 UTC, gabest11 commented
Just checked the recorded signal, recorded by rtl433, in audacity, and it looks to be inverted until I set the frequency again in HA.

2025-03-27 01:43 UTC, Malt0178 commented
The fix for the inverted data works great.

I’m not sure I fully follow your implementation of output power and the PA TABLE, but testing with the 315 MHz band seems to work. Some results were different than expected and it looks to me like some of the offsets in PA_TABLE_315 are slightly off.

Is there any reason not to just load the PA TABLE with the recommended settings for a given frequency band and then just select output power from FREND0?

2025-03-27 02:59 UTC, gabest11 commented
I found https://github.com/gabest11/datasheet/blob/main/CC1101%20DN013.pdf and copied the whole table. If you choose a dBm value, I find the closest and put it into PATABLE[1]. In OOK/ASK mode PATABLE[0] is zero, PATABLE[1] is one.

2025-03-27 03:21 UTC, gabest11 commented
There was a rounding error when I calculated the difference between following dbm entries.

2025-03-27 11:54 UTC, Malt0178 commented
Thanks for the explanation. It’s a pretty clever way to handle out of spec inputs. I do see a difference when setting output power from yaml vs using the number slider. In the 315 band, selecting 3.9 with the slider sets output power to 3.9 which is what I would expect since it’s a valid setting from the table. However, setting 3.9 from yaml sets 2.8. This happens with other output power settings as well.

2025-03-27 12:06 UTC, Weltherrscher commented
> Btw, nearly all the code was rewritten, I am surprised it even works. Did anyone notice anything strange?

Yep, me:
![image](https://github.com/user-attachments/assets/bd09fa0e-b2a9-434d-a199-8f66fd6b1734)
![image](https://github.com/user-attachments/assets/5ed40b8c-b146-414c-be09-ea6dc28bceeb)

2025-03-27 18:26 UTC, gabest11 commented
That's an annoying problem. 3.9 is looked up from the default 433.92 mhz table, because output_power in yaml is before frequency.

2025-03-31 08:34 UTC, gabest11 commented
Has anyone played with MAGN_TARGET? I found that 36dB or even 33dB has much better range than the 42dB I set as default. In the datasheet Table 32 recommends 33dB for low datarate. I'm hunting local weather stations on 433MHz, it sure saves a lot of money if I just use the neighbours.

2025-04-01 02:27 UTC, Malt0178 commented
I haven’t used the receiver and I could be wrong, but I read that setting MAG_TARGET to 42 dB would preference strong signals at the expense of weaker. That’s opposite of what you need to see what’s out there and that agrees with your observation. See Design Note DN022, Section 3 as an example that maximizes receiver sensitivity.

As a side note, I now have a single cc1101 controlling 5 fans on different frequencies in the 315 band as well as 17 storm shades in 433 band. The wire dipole antenna supporting both bands will probably make some cringe, but it works (tx only). Thanks for adding the ability to dynamically change settings.

2025-04-16 16:26 UTC, swoboda1337 commented
FYI I have played around with this and SYNC_MODE should be 4 for most things OOK/ASK. Default it is 2 and that means the signal must have 16 bits of sync. My weather stuff doesnt have that and I had very poor performance before changing that.

2025-04-16 16:41 UTC, gabest11 commented
Isn't it for syncronous operation only? 27.2 talks about sync word detection. I can still change it to 4.

2025-04-16 16:47 UTC, swoboda1337 commented
> Isn't it for synchronous operation only? 27.2 talks about sync word detection. I can still change it to 4.

Actually I am not sure what's going on as it works without that change now. I need to play with this some more.

2025-04-16 19:46 UTC, swoboda1337 commented
> I haven’t used the receiver and I could be wrong, but I read that setting MAG_TARGET to 42 dB would preference strong signals at the expense of weaker. That’s opposite of what you need to see what’s out there and that agrees with your observation. See Design Note DN022, Section 3 as an example that maximizes receiver sensitivity.

Thanks this doc was helpful. 

You get a lot of noise with those settings. Should use IDF and these SDK options help a lot:
```
    sdkconfig_options:
      CONFIG_LOG_DEFAULT_LEVEL_NONE: "y"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: "y"
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ: "240"
      CONFIG_ESP_CONSOLE_NONE: "y"
      CONFIG_RMT_RECV_FUNC_IN_IRAM: "y"
      CONFIG_RMT_ISR_IRAM_SAFE: "y"
```
The IRAM flags allow handling of RMT interrupts in ISR context, you miss a lot less data that way. The log and console flags disable all serial and IDF logging, there is a bug in the RMT code that constantly write debug to the uart, it really slows it down. 

I would also recommend setting `filter_symbols` in remote_receiver to drop short bursts of noise in ISR context before it gets to the esphome loop.

2025-04-25 18:34 UTC, Malt0178 commented
Thanks for the complier config settings.

Really good stuff here. Spent considerable time testing the receiver side and have a few observations and comments for consideration:

-  Setting ook/ask agc filter length also sets fsk/msk agc filter length and vice versa. Not sure if this was intended. I can envision a case where they would be better separated, but it can be worked as is.
- This may be a function of async mode, but why force IDLE state prior to TX and RX modes? Seems like it would be more efficient to set the desired transition mode from TX and RX in the MCSM1 register that lets the frequency synthesizer auto cal happen.
- Consider setting max_dvga_gain to the default, allow all gain settings to be used. As per the spec (pg 47), if looking for strong signals, reduce max_lna_gain prior to max_dvga_gain.
- Consider setting magn_target default to something like 36 dB or the default 33 dB. In my testing this seems to be a more out of the box solution and may give a user a better chance of initial success.
- Can you get an LQI status using async mode? I couldn’t. I set up tests to check Packet Error Rate (PER) and receiver instability to confirm receiver settings during testing.
- Noticed that setting both absolute and relative carrier sense to disabled with filter length to 4 dB allows great sensitivity and very good link quality. I was getting PER of 1.5% at -102 dBm and 0% at -97 dBm RSSI with noise -107 dBm. Good for searching far away/weak signals, but PERs were all over the place (5-19%) at -80 thru -50 dBm RSSI. This seems to confirm likely receiver instability mentioned in DN022.

I’d be happy to do some additional testing.

2025-04-25 19:13 UTC, gabest11 commented
> Thanks for the complier config settings.
> 
> Really good stuff here. Spent considerable time testing the receiver side and have a few observations and comments for consideration:
> 
> * Setting ook/ask agc filter length also sets fsk/msk agc filter length and vice versa. Not sure if this was intended. I can envision a case where they would be better separated, but it can be worked as is.

Those go to the same register, you can't set them individually.

> * This may be a function of async mode, but why force IDLE state prior to TX and RX modes? Seems like it would be more efficient to set the desired transition mode from TX and RX in the MCSM1 register that lets the frequency synthesizer auto cal happen.

Which settings exactly? I see no direct path between rx and tx which could include calibration. Looking at the two flow charts. Figure 13 and 25. It always goes through idle. In 19.4 it says "The frequency synthesizer must be calibrated regularly" and lists four options, one manual and three auto, all include idle states.

> * Consider setting max_dvga_gain to the default, allow all gain settings to be used. As per the spec (pg 47), if looking for strong signals, reduce max_lna_gain prior to max_dvga_gain.
> * Consider setting magn_target default to something like 36 dB or the default 33 dB. In my testing this seems to be a more out of the box solution and may give a user a better chance of initial success.

The two test setups I have behaves a bit different, maybe it is just my junky antenna. One cannot go below magn_target 40, else it receives too much noise, the other can operate at 33 and even see more stations. I don't really know much about these to be honest, but now that we can play with them, there is a chance to find their optimal values. Most of the values came from the old code, or from the three sources I mixed together. On page 47, higher magn_target values are recommended for higher baud rates. We have 5000 as default, which is pretty low.

> * Can you get an LQI status using async mode? I couldn’t. I set up tests to check Packet Error Rate (PER) and receiver instability to confirm receiver settings during testing.

Not really, but maybe the update speed is too low. If you can (by copying it to a local external_component), log the read-out inside loop() or `this->set_interval(1000, [this]() { ... });`. This can also capture RSSI much more accurately. But it would be too much data for HA.

> * Noticed that setting both absolute and relative carrier sense to disabled with filter length to 4 dB allows great sensitivity and very good link quality. I was getting PER of 1.5% at -102 dBm and 0% at -97 dBm RSSI with noise -107 dBm. Good for searching far away/weak signals, but PERs were all over the place (5-19%) at -80 thru -50 dBm RSSI. This seems to confirm likely receiver instability mentioned in DN022.

I will definitely test those. My strategy so far has been to randomly change every parameter.

> 
> I’d be happy to do some additional testing.

2025-04-26 18:01 UTC, Malt0178 commented
> > * This may be a function of async mode, but why force IDLE state prior to TX and RX modes? Seems like it would be more efficient to set the desired transition mode from TX and RX in the MCSM1 register that lets the frequency synthesizer auto cal happen.
> 
> Which settings exactly? I see no direct path between rx and tx which could include calibration. Looking at the two flow charts. Figure 13 and 25. It always goes through idle. In 19.4 it says "The frequency synthesizer must be calibrated regularly" and lists four options, one manual and three auto, all include idle states.
> 
TL;DR; The current implementation is fine.
What I was asking rather poorly is there a way to avoid issuing SIDLE which turns off the frequency synthesizer (pg 67, Table 42) only to reenable it and transition to RX or TX. I was not necessarily trying to include or avoid calibration. With that, is any merit to any of the following configurations:

Current settings:
MCSM1.TXOFF_MODE and MCSM1.RXOFF_MODE = “IDLE” Both default to transition to IDLE after a packet is TX or RX. 
MCSM0.FS_AUTOCAL = Auto Cal when going from “IDLE to RX or TX” 

Going from RX to TX: Another option:

Configure RXOFF_MODE = “Stay in RX” and FS_AUTOCAL = “IDLE to RX or TX” Issuing STX would enter TX without calibration and with the caveats associated with the  MCSM1.CCA_MODE setting. With TX settings in items 2 and 3 below cal would be performed when returning to RX. Granted, the current implementation guarantees a clear channel and that TX mode is entered. 

Going from TX to RX:  Three other possible options:

1. Configure TXOFF_MODE = “RX” and FS_AUTOCAL = “IDLE to RX or TX” so that RX is reenabled and no cal is performed. If cal was just performed going to TX (current implementation) it doesn’t seem necessary to do it again switching back to RX.
2. Configure TXOFF_MODE = “RX” and FS_AUTOCAL = ”RX or TX to IDLE” to auto cal, return to IDLE where an SRX can be issued to return to RX after checking MARCSTATE = “IDLE.”
3. Configure TXOFF_MODE = “IDLE” and FS_AUTOCAL = “IDLE to RX or TX” followed by SRX after checking MARCSTATE = “IDLE.”

> > * Consider setting max_dvga_gain to the default, allow all gain settings to be used. As per the spec (pg 47), if looking for strong signals, reduce max_lna_gain prior to max_dvga_gain.
> > * Consider setting magn_target default to something like 36 dB or the default 33 dB. In my testing this seems to be a more out of the box solution and may give a user a better chance of initial success.
> 
> The two test setups I have behaves a bit different, maybe it is just my junky antenna. One cannot go below magn_target 40, else it receives too much noise, the other can operate at 33 and even see more stations. I don't really know much about these to be honest, but now that we can play with them, there is a chance to find their optimal values. Most of the values came from the old code, or from the three sources I mixed together. On page 47, higher magn_target values are recommended for higher baud rates. We have 5000 as default, which is pretty low.
> 
Have I misinterpreted baud? The pulses I'm working with are between 330-425 us. I've set symbol rate to 3030 for 330us and 2353 for 425us. I can set the data rate higher and still receive data, to a point or even mis-match the data rates between receiver and transmitter and it will work, to a point. Sampling is done at 8x the data rate. Optimum gain settings change with data rates.

2025-04-30 02:26 UTC, buxtronix commented on esphome/components/cc1101/cc1101.h
> +                                              spi::CLOCK_PHASE_LEADING, spi::DATA_RATE_1KHZ> {
Is 1KHz data rate intended? I've just started testing this and it failed to detect the chip until I set it to a more reasonable value of 1MHz.

2025-04-30 09:15 UTC, gabest11 commented on esphome/components/cc1101/cc1101.h
> +                                              spi::CLOCK_PHASE_LEADING, spi::DATA_RATE_1KHZ> {
Never had any problem with this. Which cc1101 board do you have? It is supposed to work up to 10MHz, but I can't see a minimum value. You can also set the frequency in the yaml with data_rate: 1MHz, it extends the spi device schema.

2025-05-01 22:56 UTC, buxtronix commented on esphome/components/cc1101/cc1101.h
> +                                              spi::CLOCK_PHASE_LEADING, spi::DATA_RATE_1KHZ> {
I have [this AliExpress module](https://www.aliexpress.com/item/1005003781140201.html).

I have set it in the yaml for my testing, though I would err on the side of having something that works well by default for as many modules as possible.

2025-05-10 21:44 UTC, jordycoding commented
When I try to use this component with an ESP32-S3, I get the following errors:
```
[C][spi:068]: SPI bus:
[C][spi:069]:   CLK Pin: GPIO7
[C][spi:070]:   SDI Pin: GPIO8
[C][spi:071]:   SDO Pin: GPIO9
[C][spi:076]:   Using HW SPI: SPI
[C][cc1101:250]: CC1101:
[E][cc1101:253]: failed!
[C][cc1101:255]:   Chip:
[C][cc1101:256]:   Tuner:
[C][cc1101:257]:     Output Power: 9.9 dBm
[C][cc1101:258]:     Rx Attenuation: 0 dB
[C][cc1101:259]:     DC Blocking Filter: 1
[C][cc1101:260]:     Frequency: 433920 KHz
[C][cc1101:261]:     IF Frequency: 152 KHz
[C][cc1101:262]:     Bandwith: 203 KHz
[C][cc1101:263]:     Channel: 0
[C][cc1101:264]:     Channel Spacing: 199 KHz
[C][cc1101:265]:     FSK Deviation: 47 KHz
[C][cc1101:266]:     MSK Deviation: 8 KHz
[C][cc1101:267]:     Symbol Rate: 4996 Baud
[C][cc1101:268]:     Sync Mode: 0
[C][cc1101:269]:     Carrier Sense Above Threshold: 1
[C][cc1101:270]:     Modulation: 3
[C][cc1101:272]:   CS Pin: GPIO4
[C][cc1101:278]:   Update Interval: 60.0s
[E][component:082]:   Component cc1101 is marked FAILED:
```

This is my config:
```
substitutions:
  device_name: lightwave

esphome:
  name: ${device_name}
  friendly_name: Lightwave

external_components:
  - source: github://pr#6300
    components: 
      - cc1101

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

spi:
  clk_pin: GPIO7
  miso_pin: GPIO8
  mosi_pin: GPIO9

cc1101:
    id: transceiver
    cs_pin: GPIO4
    tuner:
      bandwidth: 200
      frequency: 433920

remote_transmitter:
  pin: GPIO43
  carrier_duty_percent: 100%

# remote_receiver:
#   pin: GPIO44
#   dump:
#     - rc_switch
#   tolerance: 50%
#   buffer_size: 2kb
#   filter: 250us
#   idle: 4ms

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<key>"

ota:
  - platform: esphome
    password: "<pass>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lightwave Fallback Hotspot"
    password: "05qBBOylUgbx"

captive_portal:
```

2025-05-15 08:47 UTC, Zipponia commented
Hi

But is it already possible to try the cc1101 integration ?

2025-05-19 10:42 UTC, skowron0 commented
When can this feature be included in the official Esphome release?

2025-05-20 05:27 UTC, buxtronix commented
@Zipponia @skowron0 you can already try this by including this in your device yaml:

```
external_components:
  - source: github://pr#6300
    components: [ cc1101 ]
```

2025-05-20 07:32 UTC, Zipponia commented
I tried

I get a cc1101 component not found when compiling


-- 
Alessandro Zippilli

On 20 May 2025 at 07:28:17, buxtronix ***@***.***) wrote:

> *buxtronix* left a comment (esphome/esphome#6300)
> <https://github.com/esphome/esphome/pull/6300#issuecomment-2893002251>
>
> @Zipponia <https://github.com/Zipponia> @skowron0
> <https://github.com/skowron0> you can already try this by including this
> in your device yaml:
>
> external_components:
>
>   - source: github://pr#6300
>
>     components: [ cc1101 ]
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/6300#issuecomment-2893002251>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGHN4CQBE2YBDRAIYK4VN4L27K4PDAVCNFSM6AAAAABD53DBKGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDQOJTGAYDEMRVGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-05-27 09:01 UTC, skowron0 commented
Hi, i use this configuration:

```
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3 # withouth PSRAM
  flash_size: 8MB
  framework:
    type: esp-idf

external_components:
  - source: github://pr#6300
    components: [ cc1101 ]

spi:
  clk_pin: 35
  miso_pin: 36
  mosi_pin: 37

cc1101:
  - id: cc1101_433
    cs_pin: GPIO16
    tuner:
      bandwidth: 200
      frequency: 433920
      modulation: ASK/OOK

  - id: cc1101_868
    cs_pin: GPIO17
    tuner:
      bandwidth: 300
      frequency: 868300
      modulation: 2-FSK
      fsk_deviation: 50.0
      symbol_rate: 17240
```

and I see in logger:
```
[10:52:56][C][cc1101:250]: CC1101: 
[10:52:56][C][cc1101:255]:   Chip: 0014
[10:52:56][C][cc1101:256]:   Tuner:
[10:52:56][C][cc1101:257]:     Output Power: 9.9 dBm
[10:52:56][C][cc1101:258]:     Rx Attenuation: 0 dB
[10:52:56][C][cc1101:259]:     DC Blocking Filter: 1
[10:52:56][C][cc1101:260]:     Frequency: 433920 KHz
[10:52:56][C][cc1101:261]:     IF Frequency: 0 KHz
[10:52:56][C][cc1101:262]:     Bandwith: 203 KHz
[10:52:56][C][cc1101:263]:     Channel: 0
[10:52:56][C][cc1101:264]:     Channel Spacing: 199 KHz
[10:52:56][C][cc1101:265]:     FSK Deviation: 47 KHz
[10:52:56][C][cc1101:266]:     MSK Deviation: 8 KHz
[10:52:56][C][cc1101:267]:     Symbol Rate: 4996 Baud
[10:52:56][C][cc1101:268]:     Sync Mode: 0
[10:52:56][C][cc1101:269]:     Carrier Sense Above Threshold: 1
[10:52:56][C][cc1101:270]:     Modulation: 3
[10:52:56][C][cc1101:272]:   CS Pin: GPIO16
[10:52:56][C][cc1101:278]:   Update Interval: 60.0s
[10:52:56][C][cc1101:250]: CC1101: 
[10:52:56][C][cc1101:255]:   Chip: 0014
[10:52:56][C][cc1101:256]:   Tuner:
[10:52:56][C][cc1101:257]:     Output Power: 10.7 dBm
[10:52:56][C][cc1101:258]:     Rx Attenuation: 6 dB
[10:52:56][C][cc1101:259]:     DC Blocking Filter: 0
[10:52:56][C][cc1101:260]:     Frequency: 1424281 KHz
[10:52:56][C][cc1101:261]:     IF Frequency: 406 KHz
[10:52:56][C][cc1101:262]:     Bandwith: 271 KHz
[10:52:56][C][cc1101:263]:     Channel: 34
[10:52:56][C][cc1101:264]:     Channel Spacing: 31 KHz
[10:52:56][C][cc1101:265]:     FSK Deviation: 57 KHz
[10:52:56][C][cc1101:266]:     MSK Deviation: 2 KHz
[10:52:56][C][cc1101:267]:     Symbol Rate: 67840 Baud
[10:52:56][C][cc1101:268]:     Sync Mode: 1
[10:52:56][C][cc1101:269]:     Carrier Sense Above Threshold: 0
[10:52:56][C][cc1101:270]:     Modulation: 2
[10:52:56][C][cc1101:272]:   CS Pin: GPIO17
[10:52:56][C][cc1101:278]:   Update Interval: 60.0s
```
Why do the logger display different utility values?
Cc1101 in 433 works ok, but 868 not receive data.


after some test, sometimes I see in log (I'm nothing change in code - only restart module):
```
[11:03:13][C][cc1101:250]: CC1101: 
[11:03:13][E][cc1101:253]: failed!
[11:03:13][C][cc1101:255]:   Chip: 
[11:03:13][C][cc1101:256]:   Tuner:
[11:03:13][C][cc1101:257]:     Output Power: 9.9 dBm
[11:03:13][C][cc1101:258]:     Rx Attenuation: 0 dB
[11:03:13][C][cc1101:259]:     DC Blocking Filter: 1
[11:03:13][C][cc1101:260]:     Frequency: 433920 KHz
[11:03:13][C][cc1101:261]:     IF Frequency: 152 KHz
[11:03:13][C][cc1101:262]:     Bandwith: 203 KHz
[11:03:13][C][cc1101:263]:     Channel: 0
[11:03:13][C][cc1101:264]:     Channel Spacing: 199 KHz
[11:03:13][C][cc1101:265]:     FSK Deviation: 47 KHz
[11:03:13][C][cc1101:266]:     MSK Deviation: 8 KHz
[11:03:13][C][cc1101:267]:     Symbol Rate: 4996 Baud
[11:03:13][C][cc1101:268]:     Sync Mode: 0
[11:03:13][C][cc1101:269]:     Carrier Sense Above Threshold: 1
[11:03:13][C][cc1101:270]:     Modulation: 3
[11:03:13][C][cc1101:272]:   CS Pin: GPIO16
[11:03:13][C][cc1101:278]:   Update Interval: 60.0s
[11:03:13][E][component:082]:   Component cc1101 is marked FAILED: 
[11:03:13][C][cc1101:250]: CC1101: 
[11:03:13][E][cc1101:253]: failed!
[11:03:13][C][cc1101:255]:   Chip: 0014
[11:03:13][C][cc1101:256]:   Tuner:
[11:03:13][C][cc1101:257]:     Output Power: 10.7 dBm
[11:03:13][C][cc1101:258]:     Rx Attenuation: 0 dB
[11:03:13][C][cc1101:259]:     DC Blocking Filter: 1
[11:03:13][C][cc1101:260]:     Frequency: 391529 KHz
[11:03:13][C][cc1101:261]:     IF Frequency: 380 KHz
[11:03:13][C][cc1101:262]:     Bandwith: 813 KHz
[11:03:13][C][cc1101:263]:     Channel: 15
[11:03:13][C][cc1101:264]:     Channel Spacing: 215 KHz
[11:03:13][C][cc1101:265]:     FSK Deviation: 2 KHz
[11:03:13][C][cc1101:266]:     MSK Deviation: 8 KHz
[11:03:13][C][cc1101:267]:     Symbol Rate: 860107 Baud
[11:03:13][C][cc1101:268]:     Sync Mode: 3
[11:03:13][C][cc1101:269]:     Carrier Sense Above Threshold: 1
[11:03:13][C][cc1101:270]:     Modulation: 0
[11:03:13][C][cc1101:272]:   CS Pin: GPIO17
[11:03:13][C][cc1101:278]:   Update Interval: 60.0s
[11:03:13][E][component:082]:   Component cc1101 is marked FAILED: 
```

2025-06-03 13:51 UTC, aarnaud commented
Since custom platform no longer works, this PR start to be more and more important. what is missing ?

2025-06-03 13:59 UTC, mcmasterp commented
> Hi, i use this configuration:
> 
> ```
> esp32:
>   board: esp32-s3-devkitc-1
>   variant: esp32s3 # withouth PSRAM
>   flash_size: 8MB
>   framework:
>     type: esp-idf
> 
> external_components:
>   - source: github://pr#6300
>     components: [ cc1101 ]
> 
> spi:
>   clk_pin: 35
>   miso_pin: 36
>   mosi_pin: 37
> 
> cc1101:
>   - id: cc1101_433
>     cs_pin: GPIO16
>     tuner:
>       bandwidth: 200
>       frequency: 433920
>       modulation: ASK/OOK
> 
>   - id: cc1101_868
>     cs_pin: GPIO17
>     tuner:
>       bandwidth: 300
>       frequency: 868300
>       modulation: 2-FSK
>       fsk_deviation: 50.0
>       symbol_rate: 17240
> ```
> 
> and I see in logger:
> 
> ```
> [10:52:56][C][cc1101:250]: CC1101: 
> [10:52:56][C][cc1101:255]:   Chip: 0014
> [10:52:56][C][cc1101:256]:   Tuner:
> [10:52:56][C][cc1101:257]:     Output Power: 9.9 dBm
> [10:52:56][C][cc1101:258]:     Rx Attenuation: 0 dB
> [10:52:56][C][cc1101:259]:     DC Blocking Filter: 1
> [10:52:56][C][cc1101:260]:     Frequency: 433920 KHz
> [10:52:56][C][cc1101:261]:     IF Frequency: 0 KHz
> [10:52:56][C][cc1101:262]:     Bandwith: 203 KHz
> [10:52:56][C][cc1101:263]:     Channel: 0
> [10:52:56][C][cc1101:264]:     Channel Spacing: 199 KHz
> [10:52:56][C][cc1101:265]:     FSK Deviation: 47 KHz
> [10:52:56][C][cc1101:266]:     MSK Deviation: 8 KHz
> [10:52:56][C][cc1101:267]:     Symbol Rate: 4996 Baud
> [10:52:56][C][cc1101:268]:     Sync Mode: 0
> [10:52:56][C][cc1101:269]:     Carrier Sense Above Threshold: 1
> [10:52:56][C][cc1101:270]:     Modulation: 3
> [10:52:56][C][cc1101:272]:   CS Pin: GPIO16
> [10:52:56][C][cc1101:278]:   Update Interval: 60.0s
> [10:52:56][C][cc1101:250]: CC1101: 
> [10:52:56][C][cc1101:255]:   Chip: 0014
> [10:52:56][C][cc1101:256]:   Tuner:
> [10:52:56][C][cc1101:257]:     Output Power: 10.7 dBm
> [10:52:56][C][cc1101:258]:     Rx Attenuation: 6 dB
> [10:52:56][C][cc1101:259]:     DC Blocking Filter: 0
> [10:52:56][C][cc1101:260]:     Frequency: 1424281 KHz
> [10:52:56][C][cc1101:261]:     IF Frequency: 406 KHz
> [10:52:56][C][cc1101:262]:     Bandwith: 271 KHz
> [10:52:56][C][cc1101:263]:     Channel: 34
> [10:52:56][C][cc1101:264]:     Channel Spacing: 31 KHz
> [10:52:56][C][cc1101:265]:     FSK Deviation: 57 KHz
> [10:52:56][C][cc1101:266]:     MSK Deviation: 2 KHz
> [10:52:56][C][cc1101:267]:     Symbol Rate: 67840 Baud
> [10:52:56][C][cc1101:268]:     Sync Mode: 1
> [10:52:56][C][cc1101:269]:     Carrier Sense Above Threshold: 0
> [10:52:56][C][cc1101:270]:     Modulation: 2
> [10:52:56][C][cc1101:272]:   CS Pin: GPIO17
> [10:52:56][C][cc1101:278]:   Update Interval: 60.0s
> ```
> 
> Why do the logger display different utility values? Cc1101 in 433 works ok, but 868 not receive data.
> 
> after some test, sometimes I see in log (I'm nothing change in code - only restart module):
> 
> ```
> [11:03:13][C][cc1101:250]: CC1101: 
> [11:03:13][E][cc1101:253]: failed!
> [11:03:13][C][cc1101:255]:   Chip: 
> [11:03:13][C][cc1101:256]:   Tuner:
> [11:03:13][C][cc1101:257]:     Output Power: 9.9 dBm
> [11:03:13][C][cc1101:258]:     Rx Attenuation: 0 dB
> [11:03:13][C][cc1101:259]:     DC Blocking Filter: 1
> [11:03:13][C][cc1101:260]:     Frequency: 433920 KHz
> [11:03:13][C][cc1101:261]:     IF Frequency: 152 KHz
> [11:03:13][C][cc1101:262]:     Bandwith: 203 KHz
> [11:03:13][C][cc1101:263]:     Channel: 0
> [11:03:13][C][cc1101:264]:     Channel Spacing: 199 KHz
> [11:03:13][C][cc1101:265]:     FSK Deviation: 47 KHz
> [11:03:13][C][cc1101:266]:     MSK Deviation: 8 KHz
> [11:03:13][C][cc1101:267]:     Symbol Rate: 4996 Baud
> [11:03:13][C][cc1101:268]:     Sync Mode: 0
> [11:03:13][C][cc1101:269]:     Carrier Sense Above Threshold: 1
> [11:03:13][C][cc1101:270]:     Modulation: 3
> [11:03:13][C][cc1101:272]:   CS Pin: GPIO16
> [11:03:13][C][cc1101:278]:   Update Interval: 60.0s
> [11:03:13][E][component:082]:   Component cc1101 is marked FAILED: 
> [11:03:13][C][cc1101:250]: CC1101: 
> [11:03:13][E][cc1101:253]: failed!
> [11:03:13][C][cc1101:255]:   Chip: 0014
> [11:03:13][C][cc1101:256]:   Tuner:
> [11:03:13][C][cc1101:257]:     Output Power: 10.7 dBm
> [11:03:13][C][cc1101:258]:     Rx Attenuation: 0 dB
> [11:03:13][C][cc1101:259]:     DC Blocking Filter: 1
> [11:03:13][C][cc1101:260]:     Frequency: 391529 KHz
> [11:03:13][C][cc1101:261]:     IF Frequency: 380 KHz
> [11:03:13][C][cc1101:262]:     Bandwith: 813 KHz
> [11:03:13][C][cc1101:263]:     Channel: 15
> [11:03:13][C][cc1101:264]:     Channel Spacing: 215 KHz
> [11:03:13][C][cc1101:265]:     FSK Deviation: 2 KHz
> [11:03:13][C][cc1101:266]:     MSK Deviation: 8 KHz
> [11:03:13][C][cc1101:267]:     Symbol Rate: 860107 Baud
> [11:03:13][C][cc1101:268]:     Sync Mode: 3
> [11:03:13][C][cc1101:269]:     Carrier Sense Above Threshold: 1
> [11:03:13][C][cc1101:270]:     Modulation: 0
> [11:03:13][C][cc1101:272]:   CS Pin: GPIO17
> [11:03:13][C][cc1101:278]:   Update Interval: 60.0s
> [11:03:13][E][component:082]:   Component cc1101 is marked FAILED: 
> ```

I'm not a dev but can you do two frequencies at the same time on the cc1101?

2025-06-03 13:59 UTC, mcmasterp commented
> Since custom platform no longer works, this PR start to be more and more important. what is missing ?

I also can't wait for this!!

2025-06-03 14:13 UTC, gabest11 commented
You can't tune anything to two frequencies at the same time. Is this a single cc1101 module? I'm confused because it should work as long as you have two cc1101 modules, each wired up correctly. Having a different cs pin is all it needs on the same spi bus, and you have that too.

Btw, GPIO16 and GPIO17 are ADC2 pins, which don't work with wifi active.

2025-06-03 21:12 UTC, skowron0 commented
Yes, I have two modules cc1101. Sometimes values which I set on yaml is different on log. 

EDIT

As someone wrote earlier, there is a problem with esp32s3.

I used different pins to connect my radios, for example:
 
```
substitutions:
  gpio_spi_mosi: GPIO9
  gpio_spi_miso: GPIO8
  gpio_spi_clk: GPIO6

  gpio_cc1101_433_rx: GPIO13
  gpio_cc1101_433_tx: GPIO48
  gpio_cc1101_433_cs: GPIO16

  gpio_cc1101_868_rx: GPIO14
  gpio_cc1101_868_cs: GPIO11
  gpio_cc1101_868_tx: GPIO47
```

In the example given earlier I used different ones and it didn't work properly every time. After connecting the oscilloscope I noticed that the SPI CLK pin is not pulled up correctly, regardless of which pin I define it on - I think this may be the problem, but I don't know how to deal with it. Tired of testing I connected the same radios to the XIAO ESP32 C3 board and it started right away, without any problems. Pins used when connecting to XIAO:

```
substitutions:
  gpio_spi_mosi: GPIO10
  gpio_spi_miso: GPIO9
  gpio_spi_clk: GPIO8
  
  gpio_cc1101_433_rx: GPIO3
  gpio_cc1101_433_tx: GPIO4
  gpio_cc1101_433_cs: GPIO5

  gpio_cc1101_868_rx: GPIO6
  gpio_cc1101_868_tx: GPIO7
  gpio_cc1101_868_cs: GPIO21
```
If I can help in any way by sending data or taking measurements, I'd be happy to do so because I'd ultimately like to use these radios with an esp32s3.

2025-06-10 21:57 UTC, Cian911 commented
I have been trying to get this to work with my `esp32dev` board for the past few days, to no avail. I wonder if anyone here might be able to spot what I'm doing wrong. 

I have tried other GPIO pins thinking it _has_ to be a problem with my wiring, but I've gone over and over it again and again, and I can't see what I might be doing wrong, if I am at all.

My config and wiring are as follows:

```yaml
substitutions:
  device_name: cc1101

external_components:
  - source: github://pr#6300
    components: [ cc1101 ]

esphome:
  name: esphome-web-4e7d44
  friendly_name: rf-tester-sub-gig
  min_version: 2025.5.0
  name_add_mac_suffix: false
  libraries:
    - SPI
  on_boot:
    priority: 600
    then:
      - logger.log: "ESP32 booted and logger initialized."

esp32:
  board: esp32dev
  framework:
    type: arduino


# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_pass

logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: UART0

spi:
  clk_pin: GPIO14
  miso_pin: GPIO19
  mosi_pin: GPIO23

cc1101:
  id: transceiver_module
  cs_pin: GPIO5

api:
```

And in the logs, all I see is that the component has failed:

```
[22:52:18][C][logger:224]: Logger:
[22:52:18][C][logger:225]:   Max Level: DEBUG
[22:52:18][C][logger:226]:   Initial Level: DEBUG
[22:52:18][C][logger:228]:   Log Baud Rate: 115200
[22:52:18][C][logger:229]:   Hardware UART: UART0
[22:52:18][C][logger:233]:   Task Log Buffer Size: 768
[22:52:18][C][spi:068]: SPI bus:
[22:52:18][C][spi:069]:   CLK Pin: GPIO14
[22:52:18][C][spi:070]:   SDI Pin: GPIO19
[22:52:18][C][spi:071]:   SDO Pin: GPIO23
[22:52:18][C][spi:076]:   Using HW SPI: SPI
[22:52:18][C][cc1101:250]: CC1101: 
[22:52:18][E][cc1101:253]: failed!
[22:52:18][C][cc1101:255]:   Chip: 
[22:52:18][C][cc1101:256]:   Tuner:
[22:52:18][C][cc1101:257]:     Output Power: 9.9 dBm
[22:52:18][C][cc1101:258]:     Rx Attenuation: 0 dB
[22:52:18][C][cc1101:259]:     DC Blocking Filter: 1
[22:52:18][C][cc1101:260]:     Frequency: 433920 KHz
[22:52:18][C][cc1101:261]:     IF Frequency: 152 KHz
[22:52:18][C][cc1101:262]:     Bandwith: 203 KHz
[22:52:18][C][cc1101:263]:     Channel: 0
[22:52:18][C][cc1101:264]:     Channel Spacing: 199 KHz
[22:52:18][C][cc1101:265]:     FSK Deviation: 47 KHz
[22:52:18][C][cc1101:266]:     MSK Deviation: 8 KHz
[22:52:18][C][cc1101:267]:     Symbol Rate: 4996 Baud
[22:52:18][C][cc1101:268]:     Sync Mode: 0
[22:52:18][C][cc1101:269]:     Carrier Sense Above Threshold: 1
[22:52:18][C][cc1101:270]:     Modulation: 3
[22:52:18][C][cc1101:272]:   CS Pin: GPIO5
[22:52:18][C][cc1101:278]:   Update Interval: 60.0s
[22:52:18][E][component:085]:   Component cc1101 is marked FAILED: 
[22:52:18][C][mdns:120]: mDNS:
[22:52:18][C][mdns:121]:   Hostname: esphome-web-4e7d44
[22:52:19][C][esphome.ota:073]: Over-The-Air updates:
[22:52:19][C][esphome.ota:074]:   Address: 192.168.0.175:3232
[22:52:19][C][esphome.ota:075]:   Version: 2
[22:52:19][C][safe_mode:018]: Safe Mode:
[22:52:19][C][safe_mode:020]:   Boot considered successful after 60 seconds
[22:52:19][C][safe_mode:021]:   Invoke after 10 boot attempts
[22:52:19][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[22:52:19][C][api:170]: API Server:
[22:52:19][C][api:171]:   Address: 192.168.0.175:6053
[22:52:19][C][api:178]:   Using noise encryption: NO
```

![1000037532](https://github.com/user-attachments/assets/db1244f0-e520-4749-acf2-b19e72a1cebd)
![1000037533](https://github.com/user-attachments/assets/f71380e7-90f4-43d4-b057-beee74335449)
![1000037534](https://github.com/user-attachments/assets/4121665d-e470-46c5-abdf-26cc09db925e)

2025-06-10 22:01 UTC, gabest11 commented
Any reason why you aren't using gpio18 for clk? What's the SPI library?

2025-06-10 22:11 UTC, Cian911 commented
> Any reason why you aren't using gpio18 for clk? What's the SPI library?

Opps, my mistake, I was testing GPIO14 previously. I have now put it back to GPIO18 and updated my original post. Note, it still fails.

Regarding the SPI library, that is something I [found here](https://github.com/robertos/esphome-swing-fans/blob/main/example.yaml#L5) which I thought I might be missing, alas it does nothing. I have also removed this from my original post. Sorry about that confusion

2025-06-11 00:09 UTC, buxtronix commented
@Cian911 set this:

```
cc1101:
    data_rate: 1MHz
```

I don't know why this PR has a low default data rate.

2025-06-11 06:13 UTC, gabest11 commented
I can't exactly see where the wires go, but check your miso, mosi, clk connections again. Or try different cables. I put together the exact same (with your yaml) and it worked with 1khz or 1mhz the first time. (It's just another kind of cc1101 board, all the type you have are in service now)
![2025-06-11-08-10-59-800](https://github.com/user-attachments/assets/0b950096-1004-4fdd-940f-9386b147c7c2)

2025-06-11 09:56 UTC, Cian911 commented
@gabest11 @buxtronix Ok, it's working now after that change, thanks both!

2025-06-18 20:10 UTC, ximex requested changes
the output power min doesn't match:
`static constexpr float OUTPUT_POWER_MIN = -30;`
`CONF_OUTPUT_POWER: [cv.float_range(-70, 11)],`

and the datasheet has written: `Programmable data rate from 0.6 to 600kbps`
but in code: `static constexpr float SYMBOL_RATE_MAX = 500000;`
Edit: other places in the datasheet shows the 500kbps...

2025-06-18 21:10 UTC, gabest11 commented
I think I limited it to -30 because there were not many entries in the PA table between -30 and -70. And these are either zero or one of the not recommended 0x6? values.

2025-06-18 21:47 UTC, TheChatty commented
I have a device with __65 bit__ RF messages. I don't expect that it will be supported as protocol-based binary message in esphome unless rcswitch supports it.

But how do I define [really raw messages](https://github.com/[dbuezas/esphome-cc1101](https://github.com/dbuezas/esphome-cc1101))? It's currently not described at the [latest cc1101.rst](https://github.com/esphome/esphome-docs/blob/b71b259d5c9b4ee7a9dbadb7cae4a03a21e63f88/components/cc1101.rst) if I am not mistaken.

2025-06-18 22:10 UTC, gabest11 commented
Only rc_switch is limited to 64 bit, You can use raw messages with remote_transmitter. Or write your own plugin if you want to translate some kind of string representing the signal.

https://esphome.io/components/remote_transmitter.html#remote-transmitter-transmit-raw-action

2025-06-18 22:16 UTC, swoboda1337 commented
> I have a device with **65 bit** RF messages. I don't expect that it will be supported as protocol-based binary message in esphome unless rcswitch supports it.
> 
> But how do I define [really raw messages](https://github.com/%5Bdbuezas/esphome-cc1101%5D(https://github.com/dbuezas/esphome-cc1101))? It's currently not described at the [latest cc1101.rst](https://github.com/esphome/esphome-docs/blob/b71b259d5c9b4ee7a9dbadb7cae4a03a21e63f88/components/cc1101.rst) if I am not mistaken.

You can also send it in a lambda like this, timings is just a vector:
```
      - lambda: |-
          esphome::remote_base::RawTimings timings = {+601, -613, +601, -613, +601, -613, +601, -613};
          timings.push_back(+405);
          timings.push_back(-209);
          auto call = id(remote_transmitter_id).transmit();
          call.get_data()->set_data(timings);
          call.set_send_times(3);
          call.set_send_wait(2000);
          call.perform();
```

2025-06-20 20:18 UTC, TheChatty commented
@gabest11: I succeeded to transmit (both raw & rc_switch) but [failed to receive with rc_switch](https://github.com/esphome/issues/issues/7139) (although raw works. That must be an issue in the code?

2025-06-20 21:04 UTC, gabest11 commented
First turn on raw dumping and see if you receive anything at all. Might need to tweak the filter (150us-250us) and idle 
(10ms). Or increase magn_target until you see too much raw data.

2025-06-21 14:18 UTC, TheChatty commented
My current config is:
```
...
remote_receiver:
  pin: GPIO33 # This is GDO2
  dump:
    - rc_switch
    - raw
  tolerance: 50%
  buffer_size: 2kb
  filter: 100us
  idle: 4ms

binary_sensor:
  - platform: remote_receiver
    name: "Leinwand stop (proto)"
    rc_switch_raw:
      code: '1010001101000111100101101001011000000001000000000010001110010111'  # trailing '1' missing due to rc_switch limitation to 64 bits
      protocol:
        pulse_length: 200
        sync: [0,3]
    filters:
    - delayed_off: 400ms

  - platform: remote_receiver
    name: "Leinwand stop (raw, 65 bits)"
    raw:
      code: [-600,600,-200,200,-600,600,-200,200,-600,200,-600,200,-600,600,-200,600,-200,200,-600,600,-200,200,-600,200,-600,200,-600,600,-200,600,-200,600,-200,600,-200,200,-600,200,-600,600,-200,200,-600,600,-200,600,-200,200,-600,600,-200,200,-600,200,-600,600,-200,200,-600,600,-200,600,-200,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,600,-200,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,600,-200,200,-600,200,-600,200,-600,600,-200,600,-200,600,-200,200,-600,200,-600,600,-200,200,-600,600,-200,600,-200,600,-200,600,-200]
    filters:
    - delayed_off: 400ms
  - platform: remote_receiver
    name: "Leinwand stop (raw, 64 bits)"
    raw:
      code: [-600,600,-200,200,-600,600,-200,200,-600,200,-600,200,-600,600,-200,600,-200,200,-600,600,-200,200,-600,200,-600,200,-600,600,-200,600,-200,600,-200,600,-200,200,-600,200,-600,600,-200,200,-600,600,-200,600,-200,200,-600,600,-200,200,-600,200,-600,600,-200,200,-600,600,-200,600,-200,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,600,-200,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,200,-600,600,-200,200,-600,200,-600,200,-600,600,-200,600,-200,600,-200,200,-600,200,-600,600,-200,200,-600,600,-200,600,-200,600,-200]
    filters:
    - delayed_off: 400ms
...
```

Raw data is being dumped. No problem here.

When I now press the button on the remote:

```
[16:13:04][D][binary_sensor:036]: 'Leinwand stop (raw, 65 bits)': Sending state ON
[16:13:04][D][binary_sensor:036]: 'Leinwand stop (raw, 64 bits)': Sending state ON
[16:13:04][I][remote.raw:028]: Received Raw: -601, 577, -211, 194, -577, 583, -225, 175, -599, 198, -595, 198, -594, 572, -221, 588, -198, 194, -593, 572, -221, 195, -597, 173, -613, 198, -592, 572, -221, 565, -222, 589, -197, 595, -198, 197, -595, 199, -594, 569, -222, 192, -591, 
[16:13:04][I][remote.raw:028]:   572, -222, 591, -197, 193, -594, 597, -197, 196, -593, 199, -595, 569, -221, 193, -590, 572, -222, 591, -197, 193, -597, 199, -593, 199, -594, 198, -594, 196, -592, 197, -592, 199, -592, 199, -593, 568, -221, 193, -593, 199, -595, 198, -596, 197, -592, 
[16:13:04][I][remote.raw:041]:   173, -615, 198, -593, 198, -593, 197, -593, 198, -592, 197, -595, 573, -197, 216, -591, 198, -593, 198, -593, 573, -221, 588, -197, 593, -198, 197, -594, 199, -594, 573, -221, 192, -590, 598, -198, 568, -221, 592, -197, 590, -246
...
[16:13:05][D][binary_sensor:036]: 'Leinwand stop (raw, 65 bits)': Sending state OFF
[16:13:05][D][binary_sensor:036]: 'Leinwand stop (raw, 64 bits)': Sending state OFF
```

But no mentioning of `Leinwand stop (proto)`.

2025-06-21 14:27 UTC, gabest11 commented
rc_switch needs sync, I think it will not trigger without it. [0,3] isn't really a valid option either. And since you have -600 as the first item, there is no way you can fake a sync word there. That would be 600us off, 600us on, but rc_switch cannot start with off. 

It is also good to know that raw dumping is low priority and ommited when rc_switch get matched. Not in this case though.

I'm not even sure how you received the raw starting with -601. The first item should be after an empty interval longer than idle.

2025-06-21 16:08 UTC, TheChatty commented
The [real signal is this](https://triq.org/pdv/#AAB00005011447024C00C93D83CADB8192A192A1A1A19292A192A1A1A192929292A1A192A19292A192A1A192A19292A1A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A192A1A1A1929292A1A192A1929292928192A192A1A1A19292A192A1A1A192929292A1A192A19292A192A1A192A19292A1A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A192A1A1A1929292A1A192A1929292928192A192A1A1A19292A192A1A1A192929292A1A192A19292A192A1A192A19292A1A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A192A1A1A1929292A1A192A1929292928192A192A1A1A19292A192A1A1A192929292A1A192A19292A192A1A192A19292A1A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A192A1A1A1929292A1A192A19292929355+AAB09005011447024C00C93D83CADB8192A192A1A1A19292A192A1A1A192929292A1A192A19292A192A1A192A19292A1A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A192A1A1A1929292A1A192A1929292928192A192A1A1A19292A192A1A1A192929292A1A192A19292A192A1A192A19292A1A1A1A1A1A1A1A192A1A1A1A1A1A1A1A1A1A192A1A1A1929292A1A192A19292929455). That corresponds to `sync: [26,3]`.

And I even tried with 0, 10, 20 and 26 to no avail.

Btw, all raw dump signals of this remote consistently start with roughly -600.

2025-06-21 17:00 UTC, gabest11 commented
I see. The raw decoder might treat the first 5200us as the gap (>idle) and it gives you -600 as the first item. Sync looks like [26,3], as you wrote. It's unfortunate that you have 65 bits, you can only match the raw data.

2025-06-21 22:32 UTC, TheChatty commented
I have another remote which sends [this signal](https://triq.org/pdv/#AAB01E040400E30205100F2711819081908181909081908181908181818190818255+AAB01E040100E30205100F2711819081908181909081908181908181818190818355).

This is received raw as:
```
[00:09:17][I][remote.raw:041]: Received Raw: 200, -551, 475, -250, 200, -551, 500, -250, 200, -551, 200, -550, 476, -250, 500, -250, 200, -551, 475, -275, 200, -526, 200, -550, 501, -250, 200, -550, 201, -525, 225, -525, 201, -550, 475, -276, 200, -550, 200
[00:09:17][I][remote.raw:041]: Received Raw: 200, -551, 475, -250, 200, -551, 475, -275, 200, -551, 200, -525, 501, -250, 475, -275, 200, -551, 475, -250, 226, -525, 225, -525, 501, -250, 225, -526, 200, -525, 225, -526, 225, -525, 500, -226, 225, -525, 225
[00:09:17][I][remote.raw:041]: Received Raw: 225, -526, 500, -250, 225, -526, 500, -225, 225, -526, 225, -525, 526, -225, 500, -225, 226, -525, 500, -250, 226, -525, 200, -550, 476, -275, 200, -526, 225, -525, 200, -551, 200, -550, 475, -276, 200, -525, 225
[00:09:17][I][remote.raw:041]: Received Raw: 225, -526, 500, -250, 200, -551, 475, -275, 200, -526, 200, -550, 476, -275, 475, -275, 201, -525, 500, -250, 201, -550, 200, -550, 476, -250, 225, -526, 200, -550, 200, -551, 200, -550, 475, -251, 200, -550, 200
[00:09:17][I][remote.raw:041]: Received Raw: 200, -551, 475, -275, 200, -551, 475, -250, 200, -551, 200, -550, 476, -275, 475, -250, 201, -550, 475, -275, 201, -525, 225, -526, 500, -225, 250, -501, 225, -525, 225, -526, 225, -525, 500, -226, 225, -550, 200
```

So it actually misses the closing low signal. But how should the component guess that?

I could resemble this as protocol in many ways and they **all get detected**:
```
[00:09:17][D][binary_sensor:036]: 'Lüfter minus (raw, 227/517)': Sending state ON
[00:09:17][D][binary_sensor:036]: 'Lüfter minus (proto longsync)': Sending state ON
[00:09:17][D][binary_sensor:036]: 'Lüfter minus (proto shortsync)': Sending state ON
[00:09:17][D][binary_sensor:036]: 'Lüfter minus (proto nosync)': Sending state ON
[00:09:17][D][binary_sensor:036]: 'Lüfter minus (proto nosync sharp)': Sending state ON
[00:09:17][I][remote.raw:041]: Received Raw: ...
[00:09:17][I][remote.raw:041]: Received Raw: ...
[00:09:17][I][remote.raw:041]: Received Raw: ...
[00:09:17][I][remote.raw:041]: Received Raw: ...
[00:09:17][I][remote.raw:041]: Received Raw: ...
[00:09:17][D][binary_sensor:036]: 'Lüfter minus (proto longsync)': Sending state OFF
[00:09:17][D][binary_sensor:036]: 'Lüfter minus (raw, 227/517)': Sending state OFF
[00:09:17][D][binary_sensor:036]: 'Lüfter minus (proto nosync sharp)': Sending state OFF
[00:09:17][D][binary_sensor:036]: 'Lüfter minus (proto nosync)': Sending state OFF
[00:09:17][D][binary_sensor:036]: 'Lüfter minus (proto shortsync)': Sending state OFF
```

I had to strip trailing `1` from `code` to have it detected (applied to the 65 bit signal: detecting first 64 bits should work).
Sync value was irrelevant (applied to the 65 bit signal: correct sync or no sync makes no difference).

Definition of the closest resemblance (sharp --> pulse down to 3 to match 227/517 µs signals):
````
  - platform: remote_receiver
    name: Lüfter minus (proto nosync sharp)
    rc_switch_raw:
      code: '1010110010110111101'
      protocol:
        pulse_length: 3
        zero: [172,75]
        one: [75,172]
    filters:
      delayed_off: 100ms
```

2025-06-23 23:53 UTC, gabest11 commented
Created something similar to rc_switch from my weather station branch. The code length might be up to 65536 bits. Masking is also supported, anything that is not 0 or 1 is not matched.

It has no predefined protocols, so no trigger or dump, only binary_sensor and transmission. The protocol has to be defined every time. 

signal_type can be PWM or PPM. The only difference in the source code is that PPM only has upper bound check for the leading high part of the bit.

This is to detect my window sensor.

```
external_components:
  - source: github://pr#6300
    components: [ cc1101 ]
  - source: github://gabest11/esphome@rc_switch_but_better
    components: [ remote_base, remote_receiver, remote_transmitter ]
...
binary_sensor:
  - platform: remote_receiver
    name: test
    rc_switch_but_better:
      code: '111100110010100100100110'
      protocol:
        pulse_length: 420
        sync: [1,31]
        zero: [1,3]
        one: [3,1]
        inverted: False
        reversed: False
        signal_type: PWM
```

For your signal, set idle bigger than sync (10ms). The protocol would be:

```
      code: '1010001101000111100101101001011000000001000000000010001110010111'
      protocol:
        pulse_length: 200
        sync: [26,1]
        zero: [1,3]
        one: [3,1]
        inverted: False
        reversed: False
        signal_type: PWM
```

2025-06-24 00:14 UTC, gabest11 commented
Those remote components are frequently updated, if it cannot compile, upgrade to the latest dev branch of esphome.

2025-06-24 15:14 UTC, TheChatty commented
You were right: I needed to upgrade esphome from release to dev branch.

`PWM` is probably the default value, because I could leave it out. Similar to definition of `zero`and `one`. (If you leave out `sync`only first occurance of the code is recognized.)

The log now looks like:
```
[17:07:44][D][remote.rc_switch_but_better:053]: receive @131 e9c400806969e2c5 (65)
[17:07:44][D][remote.rc_switch_but_better:059]: 10100011010001111001011010010110000000010000000000100011100101111
[17:07:44][D][binary_sensor:026]: 'Leinwand stop gabest sync': New state is ON
[17:07:44][D][remote.rc_switch_but_better:053]: receive @131 e9c400806969e2c5 (65)
[17:07:44][D][remote.rc_switch_but_better:059]: 10100011010001111001011010010110000000010000000000100011100101111
[17:07:44][D][binary_sensor:026]: 'Leinwand stop gabest nosync': New state is ON
[17:07:44][I][remote.raw:028]: Received Raw: -590, 591, ...
[17:07:44][W][component:314]: Component remote_receiver took a long time for an operation (93 ms)
[17:07:44][W][component:315]: Components should block for at most 30 ms
[17:07:44][W][remote_receiver.esp32:135]: Buffer overflow
[17:07:44][D][remote.rc_switch_but_better:053]: receive @131 e9c400806969e2c5 (65)
[17:07:44][D][remote.rc_switch_but_better:059]: 10100011010001111001011010010110000000010000000000100011100101111
[17:07:44][D][remote.rc_switch_but_better:053]: receive @131 e9c400806969e2c5 (65)
[17:07:44][D][remote.rc_switch_but_better:059]: 10100011010001111001011010010110000000010000000000100011100101111
[17:07:44][I][remote.raw:028]: Received Raw: -597, 571, ...
[17:07:44][W][component:314]: Component remote_receiver took a long time for an operation (107 ms)
[17:07:44][W][component:315]: Components should block for at most 30 ms
[17:07:44][D][binary_sensor:026]: 'Leinwand stop gabest sync': New state is OFF
[17:07:44][I][remote.raw:028]: Received Raw: -568, 592, ...
[17:07:44][D][remote.rc_switch_but_better:053]: receive @131 e9c400806969e2c5 (65)
[17:07:44][D][remote.rc_switch_but_better:059]: 10100011010001111001011010010110000000010000000000100011100101111
[17:07:44][D][binary_sensor:026]: 'Leinwand stop gabest sync': New state is ON
[17:07:44][D][remote.rc_switch_but_better:053]: receive @131 e9c400806969e2c5 (65)
[17:07:44][D][remote.rc_switch_but_better:059]: 10100011010001111001011010010110000000010000000000100011100101111
[17:07:44][I][remote.raw:028]: Received Raw: -601, 586, ...
[17:07:44][W][component:314]: Component remote_receiver took a long time for an operation (179 ms)
[17:07:44][W][component:315]: Components should block for at most 30 ms
[17:07:44][D][binary_sensor:026]: 'Leinwand stop gabest sync': New state is OFF
[17:07:44][I][remote.raw:028]: Received Raw: -571, 595, ...
[17:07:45][D][binary_sensor:026]: 'Leinwand stop gabest nosync': New state is OFF
```

So your component rocks! Thank you.

2025-06-24 15:37 UTC, gabest11 commented
Default values are [1,31] [1,3] [3,1], same as rc_switch. It's just a lucky coincidence that you also need those for zero and one.

2025-06-24 20:51 UTC, TheChatty commented
How to use rc_switch_but_better to dump unknown codes? Is it possible to specify a custom protocol and see received codes for this?

2025-06-24 21:03 UTC, gabest11 commented
It is not possible, you cannot really put protocol definitions under dump and triggers (on_...). I think. There is no example. rc_switch goes through its 8 predefined types.

2025-06-24 22:19 UTC, gabest11 commented
Okay, I tried and it looks possible, with a small modificiation. I wonder why no one else puts additional parameters there. But you have to define the protocol, no presets.

```
remote_receiver:
  dump:
    - rc_switch_but_better:
        pulse_length: 200
        sync: [26,1]
        zero: [1,3]
        one: [3,1]
        nbits: 65
        nbits_min: 8
```

nbits_min is new, 1 by default, maybe it could be 8. It means do not dump less bits.

nbits is also needed, since it was derived from the length of code for the binary sensor, 64 by default. When nbits_min is zero, it has to be exactly nbits to be dumped.

2025-06-25 08:14 UTC, TheChatty commented
Is it possible to receive signals with a pulse_length of 50?

2025-06-25 08:51 UTC, gabest11 commented
Do you have a raw dump and/or triq.org?

2025-06-25 10:06 UTC, TheChatty commented
Certainly. Three different remotes: [1](https://triq.org/pdv/#AAB00D0501003D00900602002727118255+AAB0250509003D00900602002727118181938181938181818181938193938181818181818193818255+AAB01F0501003D00900602002727118181938181938181818181938193938181818455), [2](https://triq.org/pdv/#AAB00F0601003E009100190601002627118355+AAB0270601003E009100190601002627118181948181818181948181948194949481948181818194818355+AAB0240601003E00910019060100262711818194818181818194818194819494948194818181A555), [3](https://triq.org/pdv/#AAB00D050100380095002A060627118355+AAB023050300380095002A06062711819292819292928192819281818192819281818192818355+AAB023050100380095002A0606271181929281929292819281928181819081908181819081A455).

2025-06-25 10:56 UTC, gabest11 commented
You could try filter <50us, but I am not sure if it's going to pick it up correctly, it might be too fast.

2025-06-25 13:06 UTC, TheChatty commented
I tried already with 40us to no avail.

2025-06-25 13:08 UTC, swoboda1337 commented
> I tried already with 40us to no avail.

You will have to increase your bandwidth. The higher the bandwidth the higher the sampling rate.

2025-06-25 13:20 UTC, ximex commented
is there a documentation for the user to know what parameter helps for what problem etc?

2025-06-26 20:36 UTC, Zipponia commented
Any tips to increase range when receiving 433 mhz as rc switch ?

2025-06-27 09:49 UTC, gabest11 commented
Try different antennas. I'm not an expert, my best effort was a thick solid core, cut piece by piece until it had the best reception.

Also, slowly increase magn_target.

2025-06-27 12:33 UTC, mcmasterp commented
the perfect half wave length for 433mhz is 13". that probably too big but try half that for a quarter wave

2025-06-27 12:35 UTC, swoboda1337 commented
> Any tips to increase range when receiving 433 mhz as rc switch ?

What antenna do you have? If it a cheap coil one they can have a negative gain in certain directions. They are not omni directional, don't trust their advertised gain numbers. I got this one: https://www.digikey.ca/en/products/detail/siretta-ltd/TANGO9-1-5M-SMAM-S-S-20/12179148 

You can mount the antenna outside if you stuff is outside. Will increase gain. 

What range are you getting? With OOK I am getting about 50 metes with some obstructions including a wall. I also have one sensor below grade, 20 meters away in a basement, going throw a brick wall. Note I also use the SX1278 for my stuff, haven't tried to compare the range between that and the CC1101.

2025-07-05 16:19 UTC, mik-laj commented
> > I have a device with **65 bit** RF messages. I don't expect that it will be supported as protocol-based binary message in esphome unless rcswitch supports it.
> > But how do I define [really raw messages](https://github.com/%5Bdbuezas/esphome-cc1101%5D(https://github.com/dbuezas/esphome-cc1101))? It's currently not described at the [latest cc1101.rst](https://github.com/esphome/esphome-docs/blob/b71b259d5c9b4ee7a9dbadb7cae4a03a21e63f88/components/cc1101.rst) if I am not mistaken.
> 
> You can also send it in a lambda like this, timings is just a vector:
> 
> ```
>       - lambda: |-
>           esphome::remote_base::RawTimings timings = {+601, -613, +601, -613, +601, -613, +601, -613};
>           timings.push_back(+405);
>           timings.push_back(-209);
>           auto call = id(remote_transmitter_id).transmit();
>           call.get_data()->set_data(timings);
>           call.set_send_times(3);
>           call.set_send_wait(2000);
>           call.perform();
> ```

Thanks for sharing example. I see I wasn't the only one who had this problem, so I added the code to our documentation.
PR: https://github.com/esphome/esphome-docs/pull/5070

2025-07-22 06:34 UTC, ximex commented
@gabest11 anything needed to get that PR finished?

2025-07-22 06:41 UTC, gabest11 commented
Any suggestions for different default values? Maybe I press Ready for review again. Let's see.

2025-08-06 23:23 UTC, ximex commented
@gabest11 should it work with 2025.8-dev?
```yaml
[01:22:17][C][cc1101:250]: CC1101: 
[01:22:17][C][cc1101:255]:   Chip: FFFF
[01:22:17][C][cc1101:256]:   Tuner:
[01:22:17][C][cc1101:257]:     Output Power: 10.7 dBm
[01:22:17][C][cc1101:258]:     Rx Attenuation: 0 dB
[01:22:17][C][cc1101:259]:     DC Blocking Filter: 1
[01:22:17][C][cc1101:260]:     Frequency: 0 KHz
[01:22:17][C][cc1101:261]:     IF Frequency: 0 KHz
[01:22:17][C][cc1101:262]:     Bandwith: 813 KHz
[01:22:17][C][cc1101:263]:     Channel: 0
[01:22:17][C][cc1101:264]:     Channel Spacing: 25 KHz
[01:22:17][C][cc1101:265]:     FSK Deviation: 1 KHz
[01:22:17][C][cc1101:266]:     MSK Deviation: 1 KHz
[01:22:17][C][cc1101:267]:     Symbol Rate: 24 Baud
[01:22:17][C][cc1101:268]:     Sync Mode: 0
[01:22:17][C][cc1101:269]:     Carrier Sense Above Threshold: 0
[01:22:17][C][cc1101:270]:     Modulation: 0
[01:22:17][C][cc1101:272]:   CS Pin: GPIO16
[01:22:17][C][cc1101:274]:   Chip ID 'Chip Id'
[01:22:17][C][cc1101:274]:     Icon: 'mdi:chip'
[01:22:17][C][cc1101:275]:   RSSI 'RSSI'
[01:22:17][C][cc1101:275]:     Device Class: 'signal_strength'
[01:22:17][C][cc1101:275]:     State Class: 'measurement'
[01:22:17][C][cc1101:275]:     Unit of Measurement: 'dBm'
[01:22:17][C][cc1101:275]:     Accuracy Decimals: 0
[01:22:17][C][cc1101:276]:   LQI 'LQI'
[01:22:17][C][cc1101:276]:     State Class: 'measurement'
[01:22:17][C][cc1101:276]:     Unit of Measurement: ''
[01:22:17][C][cc1101:276]:     Accuracy Decimals: 0
[01:22:17][C][cc1101:277]:   Temperature sensor 'Temperature'
[01:22:17][C][cc1101:277]:     Device Class: 'temperature'
[01:22:17][C][cc1101:277]:     State Class: 'measurement'
[01:22:17][C][cc1101:277]:     Unit of Measurement: '°C'
[01:22:17][C][cc1101:277]:     Accuracy Decimals: 1
[01:22:17][C][cc1101:278]:   Update Interval: 60.0s
```
see: `Frequency: 0 KHz`

in the config i have set: `frequency: 868250`

2025-09-18 13:43 UTC, nschimme commented
@gabest11 Are you able to pick this up again?

2025-09-30 05:20 UTC, simonyel commented
Thank you @gabest11. After waiting for over a year for this option to become available, I was able to get my 303MHz fan/light working with HA. ESP32-WROOM with one of these Chinese CC1101s. 

WIRING CONFIG
CC1101 --> ESP32
1 GND		GND
2 VCC		v3.3
3 GDO0		GPIO32
4 CSN		GPIO5 
5 SKC		GPIO18
6 MOSI		GPIO23
7 MISO/GDO1	GPIO19
8 GDO2		GPIO33

YAML:
````
substitutions:
  device_name: test-cc1101
  friendly_name: "CC1101 test"

external_components:
  - source: github://pr#6300
    components: [cc1101]

esphome:
  name: $device_name

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .iot.local

ota:
  - platform: esphome
    password: !secret ota_password

safe_mode:
    boot_is_good_after: 1min
    num_attempts: 10
    reboot_timeout: 5min

api:
  reboot_timeout: 0s
  encryption:
    key: "*********************************"

spi:
  clk_pin: GPIO18
  miso_pin: GPIO19
  mosi_pin: GPIO23

cc1101:
# data_rate: 1MHz
  id: transceiver
  cs_pin: 
    number: GPIO5
    ignore_strapping_warning: true
  gdo0_pin:
    number: GPIO32 #from PIN3 GDO0
    allow_other_uses: true
  output_power: 11
  tuner:
    frequency: 303947
    if_frequency: 152
    bandwidth: 270
    symbol_rate: 6000
    sync_mode: None
    carrier_sense_above_threshold: false
    modulation: ASK/OOK
  sensor:
    chip_id:
      name: Chip Id
    rssi:
      name: RSSI
    lqi:
      name: LQI

remote_transmitter:
  pin: 
    number: GPIO32 #from PIN3 GDO0
    allow_other_uses: true
  carrier_duty_percent: 100%


remote_receiver:
  pin: GPIO33
  dump:
    - rc_switch
  tolerance: 55%
  buffer_size: 4kb
  filter: 10us
  idle: 10ms


fan:
  - platform: template
    id: remote_fan
    name: "Fan"
    speed_count: 6
    has_direction: true
    on_turn_off:
      - lambda: |-
          id(fan_off_frames).execute();
    on_speed_set:
      - lambda: |-
          if      (id(remote_fan).state == 0) { /* do nothing when off */ }
          else if (id(remote_fan).speed == 1) { id(fan_speed1_frames).execute(); }
          else if (id(remote_fan).speed == 2) { id(fan_speed2_frames).execute(); }
          else if (id(remote_fan).speed == 3) { id(fan_speed3_frames).execute(); }
          else if (id(remote_fan).speed == 4) { id(fan_speed4_frames).execute(); }
          else if (id(remote_fan).speed == 5) { id(fan_speed5_frames).execute(); }
          else if (id(remote_fan).speed == 6) { id(fan_speed6_frames).execute(); }
    on_direction_set:
        - lambda: |-
            if (id(remote_fan).state == 0) { /* do nothing when off */ }    
            else  { id(fan_reverse_frames).execute(); /* press toggle to change direction */}     

number:
  - platform: template   
    id: num_frameA
    name: "Command frame repeat:"
    optimistic: true
    min_value: 1
    max_value: 10
    step: 1
    restore_value: True
    entity_category: CONFIG
    mode: BOX

  - platform: template   
    id: num_frameB
    name: "Trail frame repeat:"
    optimistic: true
    min_value: 1
    max_value: 10
    step: 1
    restore_value: True
    entity_category: CONFIG
    mode: BOX



switch:
  - platform: template
    name: "Light"
    id: ceiling_light
    restore_mode: DISABLED ## WITHOUT THIS CC1101 BLOWS UP
    turn_on_action:
      - script.execute: fan_light_frames
    turn_off_action:
      - script.execute: fan_light_frames

script:
  - id: fan_off_frames        # Speed 0
    then: 
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000111101'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameA).state;"
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000111111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameB).state;"      
  - id: fan_speed1_frames
    then: 
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000110111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameA).state;"
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000111111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameB).state;"   
  - id: fan_speed2_frames
    then: 
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000110101'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameA).state;"
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000111111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameB).state;"
  - id: fan_speed3_frames
    then:
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000101111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameA).state;"
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000111111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameB).state;"
  - id: fan_speed4_frames
    then:
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000100111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameA).state;"
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000111111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameB).state;"
  - id: fan_speed5_frames
    then:
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000011101'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameA).state;"
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000111111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameB).state;"
  - id: fan_speed6_frames
    then:
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000011111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameA).state;"
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000111111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameB).state;"
  - id: fan_light_frames
    then:
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000111110'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameA).state;"
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000111111'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
          repeat: !lambda "return id(num_frameB).state;"
      - switch.template.publish: 
          id: ceiling_light
          state: !lambda 'return !id(ceiling_light).state;'    
  - id: fan_reverse_frames
    then:
      - remote_transmitter.transmit_rc_switch_raw_cc1101:
          code: '010000111011'
          protocol: { pulse_length: 330, sync: [21,1], zero: [1,2], one: [2,1], inverted: true }
       [...]

2025-10-21 03:57 UTC, gabest11 commented
> ### 📦 Pull Request Size
> This PR is too large with 3876 line changes (excluding tests). Please consider breaking it down into smaller, focused PRs to make review easier and reduce the risk of conflicts.
> 
> For guidance on breaking down large PRs, see: https://developers.esphome.io/contributing/submitting-your-work/#how-to-approach-large-submissions

@esphomebot Are you drunk? God save us from AI controlling the world. 

Sorry guys, I am having a little midlife crisis right now. But getting better.

2025-10-21 13:41 UTC, swoboda1337 commented
> @esphomebot Are you drunk? God save us from AI controlling the world.

Probably best to discuss on Discord when you’re ready to revisit this. No rush. Take care.

2025-11-08 22:21 UTC, ckarrie commented
Thanks for the integration and docs. I found one error in the [docs](https://deploy-preview-3897--esphome.netlify.app/components/cc1101.html):

```yaml
cc1101:
  ...
  bandwidth: 200
  frequency: 433920
```

should be replaced with:

```yaml
cc1101:
  ...
  tuner:
    bandwidth: 200
    frequency: 433920
```

Wish you good a recovery <3

2025-11-22 09:30 UTC, One35SEven commented
Trying to use the gabest11:cc1101 component files and the example at the top of this page, but getting:

  on_press: 
    - 
      Unable to find action with the name 'remote_transmitter.transmit_cc1101'.
      remote_transmitter.transmit_cc1101: 

should this still work?

2025-12-03 16:20 UTC, ximex commented
@swoboda1337 i would say this PR got replaced by https://github.com/esphome/esphome/pull/11849 and could get closed

2025-12-03 16:23 UTC, swoboda1337 commented
> @swoboda1337 i would say this PR got replaced by #11849 and could get closed

Well #11849 is a stripped down version of this PR with ~1700 lines. This PR was never going to get reviewed with ~5000 lines. Now that the base component is in this PR can be updated with new features etc (will be much easier to review). I will keep this open and leave it up to gabest11.

2025-12-03 16:31 UTC, ximex commented
i havn't checked both PRs in detail. what features etc has this PR more?

2025-12-03 16:35 UTC, swoboda1337 commented
> i havn't checked both PRs in detail. what features etc has this PR more?

For one all the sub components etc. I will leave it up to the author.

2026-04-20 20:33 UTC, swoboda1337 commented
Thanks for the original work on this. Closing as superseded — the cc1101 component has since been picked up by another contributor and merged into dev. Really appreciate the groundwork you laid here, which helped make that happen.

2026-04-20 20:33 UTC, closed without merging