ADE7953: Add the ability to use accumulating energy registers, more precise power reporting
OttoWinter/esphomeyaml pull request #6311
Opened 2024-03-01 17:11 UTC by isorin

# What does this implement/fix?

Use ADE7935 accumulated energy registers instead of instant power registers. These registers store the accumulated energy since the last read and should provide better accuracy for power calculation.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
  - platform: ade7953_i2c
    use_accumulated_energy_registers: true
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-03-11 21:34 UTC, jesserockz requested changes

2024-03-11 21:34 UTC, jesserockz commented on esphome/components/ade7953_base/ade7953_base.cpp
> +#define ADE_WATTSEC_POWER_FACTOR (ADE_POWER_FACTOR * ADE_POWER_FACTOR / 3600)
Please use static consts for these

2024-03-12 09:40 UTC, isorin commented on esphome/components/ade7953_base/ade7953_base.cpp
> +#define ADE_WATTSEC_POWER_FACTOR (ADE_POWER_FACTOR * ADE_POWER_FACTOR / 3600)
Will do, thanks for reviewing.

2024-03-12 19:02 UTC, jesserockz approved these changes

2024-03-12 23:17 UTC, merged