add possibility to provide different conversion times for Bus Voltage…
OttoWinter/esphomeyaml pull request #6327
Opened 2024-03-06 10:03 UTC by kev300

… and Shunt Voltage (Current)

# What does this implement/fix?

The INA266 provides the possibility to set different conversion times for bus voltage and shunt voltage.
I suggest we should also do that (and I need it. :-p)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (improvement)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
adc_time_voltage: 140us
adc_time_current: 332us

```yaml
sensor:
  - platform: ina226
    address: 0x40
    shunt_resistance: 0.1 ohm
    adc_time_voltage: 140us
    adc_time_current: 332us
    current:
      name: "INA226 Current"
    power:
      name: "INA226 Power"
    bus_voltage:
      name: "INA226 Bus Voltage"
    shunt_voltage:
      name: "INA226 Shunt Voltage"
    max_current: 3.2A
    update_interval: 60s

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-03-06 23:13 UTC, jesserockz requested changes
Some changes below to make it a non-breaking change, it will also need `CONF_VOLTAGE` imported from `const`

2024-03-06 23:13 UTC, jesserockz commented on esphome/components/ina226/sensor.py
> +            cv.Optional(CONF_ADC_TIME_CURRENT, default="1100 us"): validate_adc_time,
Something like this would make the change non-breaking and allow people to specify a single time for both, or split the times if they want to.
```suggestion
            cv.Optional(CONF_ADC_TIME, default="1100 us"): cv.Any(
                validate_adc_time,
                cv.Schema(
                    {
                        cv.Required(CONF_VOLTAGE): validate_adc_time,
                        cv.Required(CONF_CURRENT): validate_adc_time,
                    }
                ),
            )
```

2024-03-06 23:13 UTC, jesserockz commented on esphome/components/ina226/sensor.py
> +    cg.add(var.set_adc_time_current(config[CONF_ADC_TIME_CURRENT]))
This is paired with the above schema change
```suggestion
	adc_time_config = config[CONF_ADC_TIME]
	if isinstance(adc_time_config, dict):
    	cg.add(var.set_adc_time_voltage(adc_time_config[CONF_VOLTAGE]))
    	cg.add(var.set_adc_time_current(adc_time_config[CONF_CURRENT]))
    else:
    	cg.add(var.set_adc_time_voltage(adc_time_config))
    	cg.add(var.set_adc_time_current(adc_time_config))
```

2024-03-06 23:13 UTC, jesserockz commented on esphome/components/ina226/sensor.py
> +CONF_ADC_TIME_CURRENT = "adc_time_current"
```suggestion
CONF_ADC_TIME = "adc_time"
```

2024-03-07 07:55 UTC, kev300 commented on esphome/components/ina226/sensor.py
> +            cv.Optional(CONF_ADC_TIME_CURRENT, default="1100 us"): validate_adc_time,
I'm not sure how this works...
Would it result in a yaml config like this?

adc_time: 140us
or optionally:
adc_time:
  voltage: 140us
  current: 332us

2024-03-07 08:07 UTC, kev300 commented on esphome/components/ina226/sensor.py
> +            cv.Optional(CONF_ADC_TIME_CURRENT, default="1100 us"): validate_adc_time,
OK cool, thanks for that suggestion.

2024-03-13 03:24 UTC, jesserockz approved these changes

2024-03-13 03:25 UTC, merged