WireGuard for esp8266
OttoWinter/esphomeyaml pull request #6365
Opened 2024-03-13 06:11 UTC by droscy

# What does this implement?

Add WireGuard support for esp8266 boards.

There are no breaking changes regarding the usage of the component because the configuration schema is still the same, but something changed in the underlying `esp_wireguard` library even for esp32 platform. So I would ask everyone here to do tests also on esp32 boards.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other (see note above)

**Related issue or feature (if applicable):** none

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3708

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
external_components:                                                                                                                                                                                                                          
  - source: github://pr#6365                                                                                                                                                                                                                  
    components: [wireguard]

esp8266:                                                                                                                                                                                                                                      
  board: ...

wireguard:
  # configure as usual
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-03-13 13:21 UTC, thomas0bernard commented
Tested and working on esp32 and esp8266. Sorry for the delay. Amazing work @droscy :raised_hands:

2024-03-13 13:24 UTC, thomas0bernard commented on esphome/components/wireguard/wireguard.cpp
> -  suspend_wdt();
I see that you removed the wdt suspension. Any reason for that? I can test on the offending network that ran into this problem later today.

2024-03-13 13:32 UTC, droscy commented on esphome/components/wireguard/wireguard.cpp
> -  suspend_wdt();
I removed the watchdog suspension because in `esp_wireguard` 0.4 the DNS resolution is handled asynchronously, see https://github.com/esphome/esphome/pull/6365/commits/5c40618663e8ab8cdc993f59a9334b5c59d9adea and https://github.com/droscy/esp_wireguard/commit/3b4a1b5585f4aaec8d4d1440b60341e5949258d3, but please test the offending network to be sure it works correctly.

2024-03-13 13:36 UTC, thomas0bernard commented on esphome/components/wireguard/wireguard.cpp
> -  suspend_wdt();
Wonderful, I figured you might have improved something in `esp_wireguard` to fix that. I'll have access to that network in a few hours and I'll keep you posted, thank you!

2024-03-13 18:57 UTC, thomas0bernard approved these changes
Confirmed working on the network with long DNS resolution. Everything looks good to me!

2024-03-14 04:25 UTC, jesserockz requested changes
Nice work.

Can you please move the tests to the new test file format that should go in `tests/components/wireguard/` You can delete any wireguard code from the `tests/testX.yaml` files at the same time

2024-03-24 22:19 UTC, jesserockz approved these changes

2024-03-24 22:21 UTC, merged