Make SPI compile with IDF >= 5.0
OttoWinter/esphomeyaml pull request #6383
Opened 2024-03-16 13:19 UTC by HeMan

# What does this implement/fix?

SPI compiles with IDF >= 5.0

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-03-16 21:21 UTC, clydebarrow requested changes

2024-03-16 21:21 UTC, clydebarrow commented on esphome/components/spi_device/spi_device.cpp
> +    ESP_LOGCONFIG(TAG, "  Data rate: %" PRId32 "kHz", this->data_rate_ / 1000);
The PRId32 stuff is ugly and fragile. Why not simply:
```suggestion
    ESP_LOGCONFIG(TAG, "  Data rate: %dkHz", (int)(this->data_rate_ / 1000));
```

2024-03-16 21:21 UTC, clydebarrow commented on esphome/components/spi_device/spi_device.cpp
> +    ESP_LOGCONFIG(TAG, "  Data rate: %" PRId32 "MHz", this->data_rate_ / 1000000);
```suggestion
    ESP_LOGCONFIG(TAG, "  Data rate: %dMHz", (int)(this->data_rate_ / 1000000));
```

2024-03-17 05:26 UTC, HeMan commented on esphome/components/spi_device/spi_device.cpp
> +    ESP_LOGCONFIG(TAG, "  Data rate: %" PRId32 "kHz", this->data_rate_ / 1000);
That is how it is done in other PRs, https://github.com/esphome/esphome/pull/6382, https://github.com/esphome/esphome/pull/5451, https://github.com/esphome/esphome/pull/5614 to name a few

2024-03-17 08:40 UTC, kbx81 commented on esphome/components/spi_device/spi_device.cpp
> +    ESP_LOGCONFIG(TAG, "  Data rate: %" PRId32 "kHz", this->data_rate_ / 1000);
This is the pattern we've been using in a lot of places -- I agree it's quite ugly, but if there's a cleaner way to handle this that keeps IDF 4, IDF 5 and Arduino all happy, I'm happy to use it. 😄

2024-03-17 09:39 UTC, clydebarrow commented on esphome/components/spi_device/spi_device.cpp
> +    ESP_LOGCONFIG(TAG, "  Data rate: %" PRId32 "kHz", this->data_rate_ / 1000);
In this instance the calculated numbers are small integers, printing as decimal. Casting the result of the division to int is portable, and I just don't see the point of reducing the code readability when there's a portable, correct alternative.

In a different context, e.g. where the `uint32_t` value represents an address potentially using the full 32 bits (and usually to be printed as hex), this would not not the right solution, so using `PRIu32` there would be a necessary compromise.

2024-03-18 02:41 UTC, kbx81 commented on esphome/components/spi_device/spi_device.cpp
> +    ESP_LOGCONFIG(TAG, "  Data rate: %" PRId32 "kHz", this->data_rate_ / 1000);
Makes sense -- fine by me! 😄

2024-03-18 06:38 UTC, HeMan commented on esphome/components/spi_device/spi_device.cpp
> +    ESP_LOGCONFIG(TAG, "  Data rate: %" PRId32 "kHz", this->data_rate_ / 1000);
Isn't the cast done at runtime while the macro is done at compile time?

2024-03-18 06:41 UTC, clydebarrow commented on esphome/components/spi_device/spi_device.cpp
> +    ESP_LOGCONFIG(TAG, "  Data rate: %" PRId32 "kHz", this->data_rate_ / 1000);
> Isn't the cast done at runtime while the macro is done at compile time?

There is absolutely no change to the generated code, because `int` and `uint32_t` are the same width (32 bits.) The sole effect of the cast in this case is to suppress the error at compile time. Technically it should be cast to `unsigned int` and the format should be `%u` because the result is never negative.

2024-03-18 07:05 UTC, HeMan commented on esphome/components/spi_device/spi_device.cpp
> +    ESP_LOGCONFIG(TAG, "  Data rate: %" PRId32 "kHz", this->data_rate_ / 1000);
With `(int)` it got one op longer but `(unsigned int)` was the same. How ever, there seem to be some changes in between SDK versions since `uint_32` was `unsigned int` on Xtensa and `unsigned long` on RISC-V, but is `unsigned long` on both after ESP-IDF 5.0, https://docs.espressif.com/projects/esp-idf/en/v5.0/esp32/migration-guides/release-5.x/gcc.html#espressif-toolchain-changes

2024-03-18 20:44 UTC, clydebarrow commented on esphome/components/spi_device/spi_device.cpp
> +    ESP_LOGCONFIG(TAG, "  Data rate: %" PRId32 "kHz", this->data_rate_ / 1000);
Given the code is only executed once, speed is hardly a consideration. Code readability and thus maintainability is far more valuable in the long run.

But in any case this is fiddling at the margins - I made a suggestion, you can choose to take it on board or not, I won't care, and the Sun will still rise tomorrow.

2024-03-18 20:46 UTC, clydebarrow approved these changes

2024-03-19 02:56 UTC, merged