Add IRK support to ble_rssi
OttoWinter/esphomeyaml pull request #6422
Opened 2024-03-23 14:23 UTC by chbmuc

# What does this implement/fix?

Most modern smartphones use use a privacy feature called Resolvable Private Addresses to avoid BLE tracking. However if you know the devices "Identity Resolving Key" (IRK), you can check if the generated private MAC address belongs to the device with the IRK.

This PR adds an option to the `ble_rssi` sensor to configure the IRK.

There is no support to obtain the key. You will have to use one of the options described here: https://espresense.com/beacons

Once you have the IRK, configuration is similar to the other methods for the `ble_rssi` binary sensor.

Implementation is almost the same as in `ble_presence` (#6335).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** feature (as requested in https://github.com/esphome/feature-requests/issues/2285)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation:** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
```yaml
# Example configuration entry
esp32_ble_tracker:

sensor:
  # Presence based on IRK
  - platform: ble_rssi
    irk: 1234567890abcdef1234567890abcdef
    name: "BLE Tracker with Identity Resolving Key"

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-03-24 22:40 UTC, jesserockz requested changes

2024-03-24 22:40 UTC, jesserockz commented on esphome/components/ble_rssi/ble_rssi_sensor.h
> +  bool resolve_irk_(uint64_t addr64, const uint8_t *irk) {
Since this is exactly the same as `ble_presence`, lets move it to the base `esp32_ble` component for reuse.

2024-04-07 08:03 UTC, chbmuc commented on esphome/components/ble_rssi/ble_rssi_sensor.h
> +  bool resolve_irk_(uint64_t addr64, const uint8_t *irk) {
I decided to move it to `esp32_ble_tracker`. Hope that's okay.

2024-05-07 00:24 UTC, jesserockz commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +#endif
I probably should have asked this in the initial PR, but why do you need to differentiate here between arduino and idf? All of the idf values are available when using arduino still...

2024-05-08 16:45 UTC, chbmuc commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +#endif
I didn't know that, but you are right. I've removed it.

2024-05-09 02:09 UTC, jesserockz approved these changes

2024-05-09 03:02 UTC, merged