reduce firmware size by moving strptime to the datetime component
OttoWinter/esphomeyaml pull request #6424
Opened 2024-03-24 11:35 UTC by gabest11

# What does this implement/fix?

std::regex adds 180k to the firmware even if the datetime component is not included in the build. Ideally, strptime could be implemented with basic string functions, but I'm not sure if the original author (@RFDarter) would like that.

Introduced in #6191

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/5630

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [x] RP2040
- [x] BK72xx
- [x] RTL87xx

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-03-24 22:05 UTC, jesserockz requested changes
I am fine with moving this code, but please move it into `datetime_base.h/cpp` so #6399 can also use it without moving it again.

2024-03-24 22:48 UTC, RFDarter commented
Why not wrap the methode and the include in ```#ifdef USE_DATETIME ... #endif``` ?

2024-03-24 22:50 UTC, gabest11 commented
That was my first idea, it also worked. But it seemed out of place in a core file.

2024-03-25 00:57 UTC, jesserockz commented on esphome/core/time.cpp
> +#if defined(USE_DATETIME_DATE) || defined(USE_DATETIME_TIME)
This can be simplified, otherwise I will need to add USE_DATETIME_DATETIME later when that entity is added too
```suggestion
#ifdef USE_DATETIME
```

2024-03-25 08:23 UTC, gabest11 commented on esphome/core/time.cpp
> +#if defined(USE_DATETIME_DATE) || defined(USE_DATETIME_TIME)
Okay, I was not sure about that.

2024-03-25 22:33 UTC, jesserockz approved these changes

2024-03-25 22:34 UTC, merged