WPA2 Enterprise - Explicitly set TTLS Phase 2
OttoWinter/esphomeyaml pull request #6436
Opened 2024-03-26 19:03 UTC by shxshxshxshx

# What does this implement/fix?

Explicitly set the Phase 2 Authentication for WPA2 Enterprise EAP-TTLS, will default to MSCHAPv2 (mirroring the existing behavior) if the option is not defined.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
wifi:
      networks:
      - ssid: EAP-TTLS_EnterpriseNetwork
        eap:
          username: bob
          password: VerySafePassword
          ttls_phase_2: mschapv2
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-03-26 21:51 UTC, jesserockz requested changes

2024-03-26 21:51 UTC, jesserockz commented on esphome/components/wifi/wpa2_eap.py
> +    raise cv.Invalid(f"Unsupported TTLS Phase 2: {value}")
This should be a `cv.enum` with the dict values being the CONSTS `ESP_EAP_TTLS_PHASE2_MSCHAPV2` etc

Then no string storing and parsing will be required.

2024-03-27 05:07 UTC, shxshxshxshx commented on esphome/components/wifi/wpa2_eap.py
> +    raise cv.Invalid(f"Unsupported TTLS Phase 2: {value}")
Changed accordingly.

2024-03-28 00:16 UTC, jesserockz commented on esphome/components/wifi/__init__.py
> +    "eap": cg.MockObj("ESP_EAP_TTLS_PHASE2_EAP"),
```suggestion
    "pap": cg.global_ns.ESP_EAP_TTLS_PHASE2_PAP,
    "chap": cg.global_ns.ESP_EAP_TTLS_PHASE2_CHAP,
    "mschap": cg.global_ns.ESP_EAP_TTLS_PHASE2_MSCHAP,
    "mschapv2": cg.global_ns.ESP_EAP_TTLS_PHASE2_MSCHAPV2,
    "eap": cg.global_ns.ESP_EAP_TTLS_PHASE2_EAP,
```

2024-03-28 00:23 UTC, jesserockz commented on esphome/components/wifi/wifi_component.cpp
> +    ESP_LOGV(TAG, "    TTLS Phase 2: " LOG_SECRET("'%s'"), eap_config.ttls_phase_2.c_str());
This will fail to compile now that it is an enum

2024-03-28 02:21 UTC, jesserockz reviewed
We can wrap this so its dropped if not using verbose logging

2024-03-28 02:21 UTC, jesserockz commented on esphome/components/wifi/wifi_component.cpp
> +    std::map<esp_eap_ttls_phase2_types, std::string> phase2types = {{ESP_EAP_TTLS_PHASE2_PAP, "pap"},
```suggestion
#if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_VERBOSE
    std::map<esp_eap_ttls_phase2_types, std::string> phase2types = {{ESP_EAP_TTLS_PHASE2_PAP, "pap"},
```

2024-03-28 02:21 UTC, jesserockz commented on esphome/components/wifi/wifi_component.cpp
> +    ESP_LOGV(TAG, "    TTLS Phase 2: " LOG_SECRET("'%s'"), phase2types[eap_config.ttls_phase_2].c_str());
```suggestion
    ESP_LOGV(TAG, "    TTLS Phase 2: " LOG_SECRET("'%s'"), phase2types[eap_config.ttls_phase_2].c_str());
#endif
```

2024-03-28 02:34 UTC, shxshxshxshx commented on esphome/components/wifi/wifi_component.cpp
> +    std::map<esp_eap_ttls_phase2_types, std::string> phase2types = {{ESP_EAP_TTLS_PHASE2_PAP, "pap"},
The compiler already drops unused variables, hence why I originally elected to not drop it explicitly.

2024-05-15 23:37 UTC, jesserockz approved these changes

2024-05-15 23:37 UTC, merged