init
OttoWinter/esphomeyaml pull request #6445
Opened 2024-03-29 00:47 UTC by RFDarter

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-03-29 08:42 UTC, jesserockz commented on esphome/components/web_server/web_server.cpp
> +  for (auto sorting_entity : this->sorting_entitys_) {
Considering the way esphome works and calls this, I don't think you need to check it exists already.

2024-03-29 08:42 UTC, jesserockz commented on esphome/components/web_server/web_server.h
> +  std::vector<SortingEntity *> sorting_entitys_;
Instead of storing a vector that needs to be iterated, maybe a std::map with the pointer to the entity as the key and the group/weight as the value. 
This should make the detail_all lookup a bit better too and you don't need the object hash.

2024-04-10 10:49 UTC, kroimon commented
Are we sure we want to introduce more top-level properties to all those components?
I wonder if something like the introduction of a `meta` property would make sense that could store properties for other components to use, including the already existing MQTT properties. This would reduce clutter, especially if similar additional properties for other components are necessary in the future.
An example would be:

```yaml
button:
  - platform: template
    name: My Button
    meta:
      web_server:
        sorting_weight: 4
      mqtt:
        qos: 1
        retain: true
        availability:
          topic: mybutton/status
          payload_available: online
          payload_not_available: offline
        state_topic: mybutton/custom_state_topic
        command_topic: mybutton/custom_command_topic
        command_retain: false
```

I understand this would be the scope of a separate PR and would introduce a breaking change for existing MQTT properties, but it might be worth considering before merging this.

2024-04-10 13:18 UTC, RFDarter commented
> Are we sure we want to introduce more top-level properties to all those components?
> I wonder if something like the introduction of a `meta` property would make sense that could store properties for other components to use, including the already existing MQTT properties. This would reduce clutter, especially if similar additional properties for other components are necessary in the future.
> An example would be:
> 
> ```yaml
> button:
>   - platform: template
>     name: My Button
>     meta:
>       web_server:
>         sorting_weight: 4
>       mqtt:
>         qos: 1
>         retain: true
>         availability:
>           topic: mybutton/status
>           payload_available: online
>           payload_not_available: offline
>         state_topic: mybutton/custom_state_topic
>         command_topic: mybutton/custom_command_topic
>         command_retain: false
> ```
> 
> I understand this would be the scope of a separate PR and would introduce a breaking change for existing MQTT properties, but it might be worth considering before merging this.

I like that idea!

2024-05-01 22:21 UTC, jesserockz requested changes

2024-05-01 22:21 UTC, jesserockz commented on esphome/components/binary_sensor/__init__.py
> +            ),
This can go inside `WEBSERVER_SORTING_SCHEMA`. The only reason the mqtt ones are in here is because they all have different rhs with different classes.

2024-05-01 23:17 UTC, RFDarter commented on esphome/components/binary_sensor/__init__.py
> +            ),
Allright, i might find the time tomorrow to change that.

2024-05-07 01:58 UTC, jesserockz approved these changes

2024-05-09 03:17 UTC, jesserockz requested changes
I realised we need to validate that sorting_weight is only specified when using webserver v3

2024-05-09 11:00 UTC, RFDarter commented
> I realised we need to validate that sorting_weight is only specified when using webserver v3

@jesserockz Any hint how we could accomplish that? I was looking into it for some time now and there seems no obvios way of doing this

2024-05-09 22:47 UTC, jesserockz commented
CI will fail until #6716 is merged and updated into this PR

2024-05-29 21:51 UTC, jesserockz approved these changes

2024-05-30 01:54 UTC, merged

2024-05-30 22:01 UTC, sodabrew commented
<3 when I go looking for how to solve a problem and someone has just merged it earlier today! Thank you @RFDarter!