Add valve component
OttoWinter/esphomeyaml pull request #6447
Opened 2024-03-29 03:23 UTC by kbx81

# What does this implement/fix?

Adds support for valve components/entities

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-09 22:09 UTC, jesserockz commented on esphome/components/web_server/web_server.cpp
> +
I would worry about updating v1 webserver stuff for new entities (I didnt add the date/time stuff)

2024-04-09 22:11 UTC, jesserockz commented on esphome/components/valve/valve.h
> +  void stop();
Doesnt make sense to add deprecated functions on a new section of code =)

2024-04-09 23:27 UTC, kbx81 commented on esphome/components/valve/valve.h
> +    auto traits_ = (obj) -> get_traits(); \
Haha, why does it complain about this one line? 😅 
```suggestion
    auto traits_ = (obj)->get_traits(); \
```

2024-04-17 02:02 UTC, jesserockz requested changes

2024-04-17 02:02 UTC, jesserockz commented on esphome/components/template/valve/__init__.py
> +        cg.add(var.set_state_lambda(template_))
More walruses are required in this file =)
```suggestion
    if lambda_config := config.get(CONF_LAMBDA):
        template_ = await cg.process_lambda(
            lambda_config, [], return_type=cg.optional.template(float)
        )
        cg.add(var.set_state_lambda(template_))
```

2024-04-17 02:02 UTC, jesserockz commented on esphome/components/template/valve/__init__.py
> +        ),
I think a while back we came to a decision that everything should not restore by default and it needs to be user choice.
```suggestion
        cv.Optional(CONF_RESTORE_MODE, default="NO_RESTORE"): cv.enum(
            RESTORE_MODES, upper=True
        ),
```

2024-04-17 02:02 UTC, jesserockz commented on esphome/components/template/valve/template_valve.h
> +  TemplateValveRestoreMode restore_mode_{VALVE_RESTORE};
```suggestion
  TemplateValveRestoreMode restore_mode_{VALVE_NO_RESTORE};
```

2024-04-17 02:02 UTC, jesserockz commented on esphome/components/valve/__init__.py
> +        cg.add(var.set_device_class(config[CONF_DEVICE_CLASS]))
```suggestion
    if device_class_config := config.get(CONF_DEVICE_CLASS):
        cg.add(var.set_device_class(device_class_config))
```

2024-04-17 02:35 UTC, kbx81 commented on esphome/components/template/valve/__init__.py
> +        cg.add(var.set_state_lambda(template_))
Hahaha, we talked about this and I completely forgot to circle back and do it. 🤦🏻‍♂️  Will fix.

2024-04-17 18:29 UTC, nagyrobi commented
The Endstop and Time Based valves (copied functionality from the coresponding cover types) are the next ones needed...

2024-04-18 02:39 UTC, jesserockz commented on esphome/components/template/valve/__init__.py
> +    if position_config := config.get(CONF_POSITION):
Gotta be careful with config values that can be falsy
```suggestion
    if (position_config := config.get(CONF_POSITION)) is not None:
```

2024-04-23 04:33 UTC, jesserockz approved these changes

2024-04-23 04:47 UTC, merged