Separate `OTABackend` from OTA component
OttoWinter/esphomeyaml pull request #6459
Opened 2024-04-02 00:55 UTC by kbx81

# What does this implement/fix?

Splits the OTABackend out from the OTA component so that it can be more easily used by other (future) OTA components.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-08 21:40 UTC, oarcher commented
It would be nice to make the function `std::unique_ptr<ota::OTABackend> make_ota_backend()`  become a public method of `OTAESPHomeComponent`, so other platforms can get the backend easily.

in https://github.com/esphome/esphome/pull/5586, I had to copy/paste the whole function to get the backend...

2024-04-09 01:56 UTC, kbx81 commented
> It would be nice to make the function `std::unique_ptr<ota::OTABackend> make_ota_backend()` become a public method of `OTAESPHomeComponent`, so other platforms can get the backend easily.
> 
> in #5586, I had to copy/paste the whole function to get the backend...

I had considered doing that -- I can add that change here. 😄

2024-04-09 22:46 UTC, oarcher commented
I've tried to turn `ota_http` in a platform component, and it worked ! 

My yaml was:
```yaml
ota:
   - platform: esphome
     password: "xxxxxxxxxxxxxxxx"
     num_attempts: 3
     safe_mode: no
   - platform: ota_http
     safe_mode: false
     exclude_certificate_bundle: true
     watchdog_timeout: 20s
     timeout: 4min
     max_url_length: 128
     force_update: true
 ```
 
 This was just a local quick and dirty test, I've not refactored it yet to `http_request`.

2024-04-09 23:22 UTC, kbx81 commented
Thank you for confirming, @oarcher! 🍻

2024-04-11 05:29 UTC, kbx81 commented
@oarcher I've moved `make_ota_backend` into...the OTA backend. 😅 Should help eliminate duplicate code. Feel free to try it out!

2024-04-11 10:07 UTC, oarcher commented
ok, I've been able to remove `make_ota_backend` implementation from `ota_http`: works well, with less code!

2024-04-17 23:58 UTC, jesserockz requested changes
A couple of points below I thought I would submit before going through the rest

2024-04-17 23:58 UTC, jesserockz commented on esphome/components/esphome/ota/__init__.py
> +DEPENDENCIES = ["network", "ota"]
Not required as this is an ota platform so it will always be loaded
```suggestion
DEPENDENCIES = ["network"]
```

2024-04-17 23:58 UTC, jesserockz commented on esphome/components/esphome/ota/__init__.py
> +        ),
I feel like these could all stay in the base `ota` and be in a BASE_OTA_SCHEMA and a base c++ class that all platforms should implement.

2024-04-17 23:58 UTC, jesserockz commented on esphome/components/esphome/ota/ota_esphome.h
> +namespace ota_esphome {
Namespaces need to match the platform
```suggestion
namespace esphome {
```

2024-04-17 23:58 UTC, jesserockz commented on esphome/components/esphome/ota/ota_esphome.h
> +class OTAESPHomeComponent : public Component {
This one is optional, but I think having them this way reads better
```suggestion
class ESPHomeOTAComponent : public Component {
```

2024-04-18 01:55 UTC, kbx81 commented on esphome/components/esphome/ota/__init__.py
> +DEPENDENCIES = ["network", "ota"]
🤦🏻‍♂️

2024-04-18 01:56 UTC, kbx81 commented on esphome/components/esphome/ota/__init__.py
> +        ),
Solid agree. I'll rework this.

2024-04-18 01:57 UTC, kbx81 commented on esphome/components/esphome/ota/ota_esphome.h
> +class OTAESPHomeComponent : public Component {
Works for me!

2024-04-21 09:18 UTC, kbx81 commented on esphome/components/esphome/ota/__init__.py
> +        ),
Did some rearranging in [`8426084` (#6459)](https://github.com/esphome/esphome/pull/6459/commits/8426084ebfe523066855c20dcd636b0dfb04bc5d) and it's at least working...not 100% sure it's what you had in mind but have a look! 😄

2024-04-22 03:45 UTC, kbx81 commented on esphome/components/esphome/ota/__init__.py
> +        ),
An outstanding question I have is about `USE_OTA_STATE_CALLBACK` -- it seems it's always set when `defines.h` is included...which would seem to make it somewhat...useless? There may be some history there that I'm not aware of and/or maybe I just don't understand its intended use. Regardless, just something I wanted to call out.

2024-04-22 11:00 UTC, oarcher commented on esphome/components/esphome/ota/__init__.py
> +        ),
If using `esp32_ble_tracker`, `USE_OTA_STATE_CALLBACK` is forced, so the tracker is able to add a callback when ota starts, to disable the scan.

So if `esp32_ble_tracker` is not used, `USE_OTA_STATE_CALLBACK` should not be in `define.h`.

Does the `esp32_ble_tracker` do that to release memory for the OTA ? If so, https://github.com/esphome/esphome/pull/5586 should raise an `ota_esphome::OTA_STARTED` event *before* the http request, because this one take much memory. But it is in the `ota_esphome` namespace, not `ota`...

2024-04-22 16:28 UTC, kbx81 commented on esphome/components/esphome/ota/__init__.py
> +        ),
More broadly, it _appears_ that `USE_OTA_STATE_CALLBACK` is not to be defined unless one or more of the callbacks (actions) is defined; `esp32_ble_tracker` just hooks into this.

But it's defined in `defines.h`, so it ends up being defined wherever that gets included...which I think may be an error.

2024-04-28 23:56 UTC, jesserockz commented on esphome/components/ota/ota_backend.h
> +class OTAStateChangeTrigger : public Trigger<OTAState> {
Why did these move out of the automation.h file?

2024-04-29 00:04 UTC, jesserockz requested changes

2024-04-29 00:04 UTC, jesserockz commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +  esphome::global_ota_component->add_on_state_callback([this](ota::OTAState state, float progress, uint8_t error) {
This should not be specific to the esphome ota component.

2024-04-29 00:04 UTC, jesserockz commented on esphome/components/ota/__init__.py
>  DEPENDENCIES = ["network"]
Does the backend actually still have a dependency on network still?

2024-04-29 01:22 UTC, kbx81 commented on esphome/components/ota/ota_backend.h
> +class OTAStateChangeTrigger : public Trigger<OTAState> {
That's just where I pasted them. 😅 We can move them back into `automation.h`; it shouldn't cause any issues.

2024-04-29 02:01 UTC, kbx81 commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +  esphome::global_ota_component->add_on_state_callback([this](ota::OTAState state, float progress, uint8_t error) {
Ah! I think this will need a little refactoring. I'm on it. 😄

2024-04-29 02:01 UTC, kbx81 commented on esphome/components/ota/__init__.py
>  DEPENDENCIES = ["network"]
Looks like it does not. I'll remove this

2024-04-29 02:11 UTC, kbx81 commented on esphome/components/ota/ota_backend.h
> +class OTAStateChangeTrigger : public Trigger<OTAState> {
Done

2024-04-29 02:52 UTC, kbx81 commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +  esphome::global_ota_component->add_on_state_callback([this](ota::OTAState state, float progress, uint8_t error) {
Ok, I think [`4f8dd25`](https://github.com/esphome/esphome/pull/6459/commits/4f8dd25478df50150e3c01e8a77195387a8dd5c4) should take care of this.

2024-04-30 05:54 UTC, kbx81 commented on esphome/components/esphome/ota/__init__.py
> +        ),
..I should've really read the comment at the top of `defines.h`...

2024-04-30 06:36 UTC, kbx81 commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +  esphome::global_ota_component->add_on_state_callback([this](ota::OTAState state, float progress, uint8_t error) {
Done more better in [`2da0bca`](https://github.com/esphome/esphome/pull/6459/commits/2da0bcadc70093b9fc234baad5ee88ef104596b3)...I think 😅

2024-05-07 00:06 UTC, kbx81 commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +  esphome::global_ota_component->add_on_state_callback([this](ota::OTAState state, float progress, uint8_t error) {
Done even more better in [`8dd03a3`](https://github.com/esphome/esphome/pull/6459/commits/8dd03a3dac480e8eda0c8d8e31d1bf62ae23efae)

2024-05-08 19:10 UTC, tomaszduda23 commented
I just merged the change to https://github.com/esphome/esphome/pull/6075. It simplified the implementation a lot :+1:

2024-05-16 01:56 UTC, jesserockz approved these changes

2024-05-16 02:01 UTC, merged