add actions to the MAX7219Component
OttoWinter/esphomeyaml pull request #6462
Opened 2024-04-02 15:36 UTC by nielsnl68

# What does this implement/fix?

This add a couple of Actions that allow update the dot matrix display.

adding:

    "MAX7219.invert_off"
    "MAX7219.invert_on"

    "MAX7219.turn_off"
    "MAX7219.turn_on"

    "MAX7219.reverse_off"
    "MAX7219.reverse_on"

    "MAX7219.intensity"

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4164

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-15 03:54 UTC, jesserockz requested changes

2024-04-15 03:54 UTC, jesserockz commented on esphome/components/max7219digit/display.py
> +DisplayVisiblityAction = max7219_ns.class_("DisplayVisiblityAction", automation.Action)
Typo?
```suggestion
DisplayVisibilityAction = max7219_ns.class_("DisplayVisibilityAction", automation.Action)
```

2024-04-15 03:54 UTC, jesserockz commented on esphome/components/max7219digit/display.py
> +    "MAX7219.inveert_on", DisplayInvertAction, MAX7219_ON_ACTION_SCHEMA
Typo?
```suggestion
    "MAX7219.invert_on", DisplayInvertAction, MAX7219_ON_ACTION_SCHEMA
```

2024-04-15 03:54 UTC, jesserockz commented on esphome/components/max7219digit/max7219digit.h
> +*/
No commented out code please
```suggestion
```

2024-11-12 22:52 UTC, jesserockz commented
Drafted as needs testing on device.

2025-05-05 04:11 UTC, jesserockz requested changes

2025-05-05 04:11 UTC, jesserockz commented on esphome/components/max7219digit/automation.h
> +  void play(Ts... x) override { this->parent_->intensity(this->state_.optional_value(x...)); }
```suggestion
  void play(Ts... x) override { this->parent_->set_intensity(this->state_.optional_value(x...)); }
```

2025-05-05 15:52 UTC, nielsnl68 commented on esphome/components/max7219digit/automation.h
> +  void play(Ts... x) override { this->parent_->intensity(this->state_.optional_value(x...)); }
thanks

2025-05-05 17:30 UTC, nielsnl68 commented
Jesse, there is still something wrong with the "`intensity`" action and i have not found what i doing wrong.

2025-05-14 21:12 UTC, jesserockz approved these changes

2025-05-14 21:15 UTC, merged