Mirage remote receiver & transmitter
OttoWinter/esphomeyaml pull request #6479
Opened 2024-04-04 19:52 UTC by heggi

# What does this implement/fix?

I implemented infrared mirage protocol.

Protocol description was taken from the source code:
https://github.com/crankyoldgit/IRremoteESP8266/blob/master/src/ir_Mirage.h
https://github.com/crankyoldgit/IRremoteESP8266/blob/master/src/ir_Mirage.cpp

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** https://github.com/esphome/feature-requests/issues/2309

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%

remote_receiver:
  pin:
    number: D7
    inverted: true
    mode:
      input: true
      pullup: true
  dump: mirage
  on_mirage:
    then:
      - logger.log: "Hello World"

binary_sensor:
  - platform: gpio
    pin:
      number: D3
      inverted: true
      mode:
        input: true
        pullup: true
    name: "OFF"
    on_press:
      remote_transmitter.transmit_mirage:
        code:
          [0x56, 0x77, 0x00, 0x00, 0x22, 0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-09 21:12 UTC, jesserockz requested changes

2024-04-09 21:12 UTC, jesserockz commented on tests/test1.yaml
Please move this to the tests located at `tests/components/remote_transmitter` and `tests/components/remote_receiver`

2024-04-09 23:46 UTC, heggi commented on tests/test1.yaml
I added tests to `tests/components/remote_transmitter` and `tests/components/remote_receiver`

I didn't change the file `tests/test1.yaml` (it stays as is). Do I need to remove the test from it?

2024-04-10 22:11 UTC, jesserockz submitted a review, later dismissed

2024-04-14 21:02 UTC, jesserockz approved these changes

2024-05-15 23:35 UTC, merged