Added HTU21D models
OttoWinter/esphomeyaml pull request #6485
Opened 2024-04-05 12:34 UTC by MRemy2

# What does this implement/fix?

Added models to the HTU21D because the HTU21D sensor does not support heater_level

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3742
## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-08 07:47 UTC, jesserockz requested changes
Please do not combine fixes across different components into a single PR.

2024-04-08 08:19 UTC, MRemy2 commented
Removed the fix for ble. I will include it in another pr.

2024-04-09 01:51 UTC, jesserockz commented on esphome/core/component.cpp
As core changes, these should go into their own PR as well. Also you defined the message, but never used it.

2024-04-09 06:01 UTC, MRemy2 commented on esphome/core/component.cpp
The core changes are used in the htu21d.cpp files. I do not see why the commit should be split. The chages to the htu21d component depend on the core changes. I used  the 'status_clear_warning' with a message in the component files. Also the never used message is because of https://github.com/esphome/esphome/pull/6485/commits/fd59a0fc42a2cf26a0a944163faa5b044493f049. I did use the message in the first place. 
Thanks.

2024-04-09 20:06 UTC, jesserockz commented on esphome/core/component.cpp
Ah my bad, there were conflicts when I did a merge and I guess it got lost. But in any case, small core changes like this should be in their own PRs so its easier to follow the chain of commits. It doesnt make sense if the PR/commit that adds a new core feature to be named `Added HTU21D models`.
This PR should only focus on that specific feature of adding new models.

2024-04-10 06:12 UTC, MRemy2 commented on esphome/core/component.cpp
created a new pull as my branches got messed up really bad and I found it easier to create a new PR 
https://github.com/esphome/esphome/pull/6511

2024-04-10 06:12 UTC, MRemy2 commented
Closing pull request. tracked by https://github.com/esphome/esphome/pull/6511

2024-04-10 06:12 UTC, closed without merging