Add beken_spi_led_strip component
OttoWinter/esphomeyaml pull request #6515
Opened 2024-04-11 14:49 UTC by Mat931

# What does this implement/fix?

Allows using addressable LEDs like the WS2812 on pin P16 of the BK7231N. This is a temporary solution until LibreTiny provides the necessary SPI functions. Other chips (BK7231T and BK7251) are untested. For accurate timings the SPI DMA interface of the Beken chip is used.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [x] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
bk72xx:
  board: generic-bk7231n-qfn32-tuya

light:
  - platform: beken_spi_led_strip
    name: "Color Light"
    pin: P16
    chipset: WS2812
    num_leds: 60
    rgb_order: GRB
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-24 04:03 UTC, jesserockz commented on esphome/components/beken_spi_led_strip/light.py
> +            cv.Required(CONF_CHIPSET): cv.one_of(*CHIPSETS, upper=True),
No option for custom timings like esp32_rmt_led_strip and rp2040_pio_led_strip support?

2024-04-24 04:26 UTC, Mat931 commented on esphome/components/beken_spi_led_strip/light.py
> +            cv.Required(CONF_CHIPSET): cv.one_of(*CHIPSETS, upper=True),
How do you suggest implementing this? On the Beken chips we don't have nearly as much control over the timings as on the ESP32 for example. There are only a few values for the frequency depending on the clock divider. To change the duty cycle of each LED strip bit we have 8 SPI bit positions we can change plus a 9th bit at the end which is always low. To be sure that the timings are compatible with a given LED strip we need to know the acceptable timing range from the datasheet. Should we just let the user figure all that out and expose bit0, bit1 and spi_frequency in YAML? Or should we try to calculate some (probably inaccurate) values for the timings in Python?

2024-04-24 07:17 UTC, jesserockz commented on esphome/components/beken_spi_led_strip/light.py
> +            cv.Required(CONF_CHIPSET): cv.one_of(*CHIPSETS, upper=True),
So in the other led_strips, the chipset just defines the know bit0/1 high/low values for a specific led chipset. 
But in yaml, a user can define these values directly. 

I have not done a full proper review yet so i'm not sure exactly how the bk chips work in this PR.

2024-05-07 22:09 UTC, jesserockz requested changes

2024-05-07 22:09 UTC, jesserockz commented on esphome/components/beken_spi_led_strip/led_strip.cpp
> +#include "../../beken378/driver/spi/spi.h"
There should not be relative paths to external included files...

2024-05-13 04:14 UTC, jesserockz requested changes
Minor changes below, otherwise good to go I think.

2024-05-13 04:14 UTC, jesserockz commented on esphome/components/beken_spi_led_strip/light.py
> +    if value.get(CONF_IS_RGBW, False) or value.get(CONF_IS_WRGB, False):
Since there is a default of False for both of these, you can just access it directly
```suggestion
    if value[CONF_IS_RGBW] or value[CONF_IS_WRGB]:
```

2024-05-13 04:14 UTC, jesserockz commented on esphome/components/beken_spi_led_strip/light.py
> +    if value.get(CONF_NUM_LEDS) > max_num_leds:
```suggestion
    if value[CONF_NUM_LEDS] > max_num_leds:
```

2024-05-13 04:14 UTC, jesserockz commented on esphome/components/beken_spi_led_strip/light.py
> +            f"The maximum number of LEDs for this configuration is {max_num_leds}."
```suggestion
            f"The maximum number of LEDs for this configuration is {max_num_leds}.",
            path=CONF_NUM_LEDS,
```

2024-05-13 18:58 UTC, jesserockz submitted a review, later dismissed

2024-05-15 23:32 UTC, jesserockz approved these changes

2024-05-15 23:32 UTC, merged