Nextion - Use persistent http connection for TFT upload (ESP-IDF)
OttoWinter/esphomeyaml pull request #6576
Opened 2024-04-18 04:41 UTC by edwardtfn

# What does this implement/fix?

This will avoid a new http connection per chunk on Nextion when uploading TFT file, improving memory management and reliability of the whole process.

This is part of the breaking down of #6192

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

N/A

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-29 22:08 UTC, jesserockz requested changes
Please also move/duplicate `#define USE_NEXTION_TFT_UPLOAD` in `esphome/core/defines.h` so that the idf upload code is run by clang correctly. Currently it is not.

2024-04-29 22:08 UTC, jesserockz commented on esphome/components/nextion/nextion_upload_idf.cpp
> +  }
Please see ExternalRAMAllocator which does all of this for you already

2024-04-29 22:08 UTC, jesserockz commented on esphome/components/nextion/nextion_upload_idf.cpp
> +    esp_restart();                    // NOLINT(readability-static-accessed-through-instance)
```suggestion
    delay(1500);  // NOLINT
    arch_restart();
```

2024-04-30 14:08 UTC, edwardtfn commented on esphome/components/nextion/nextion_upload_idf.cpp
> +  }
That makes things much easier. Thanks for pointing it.

2024-04-30 14:51 UTC, edwardtfn commented
> Please also move/duplicate #define USE_NEXTION_TFT_UPLOAD in esphome/core/defines.h so that the idf upload code is run by clang correctly. Currently it is not.

I've changed that in PR #6661 as this wasn't duplicated by any of my previous PRs, so I wanna track this on the side.

2024-05-01 22:05 UTC, jesserockz approved these changes

2024-05-01 22:05 UTC, merged