Add MPL115A2 Barometric Pressure/Temperature Sensor
OttoWinter/esphomeyaml pull request #6584
Opened 2024-04-18 22:49 UTC by unic8s

# What does this implement/fix?

Add support for the MPL115A2 pressure/temperature I²C sensor (https://github.com/adafruit/Adafruit_MPL115A2). This is the tinier version of the already exisiting implementation of the sensor MPL3115A2 but without the altitude metric. The code is partly ported from https://github.com/adafruit/Adafruit_MPL115A2

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sensor:
- platform: mpl115a2
  temperature:
    name: "Temperature"
  pressure:
    name: "Pressure"
  update_interval: 10s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-05-05 22:32 UTC, jesserockz requested changes

2024-05-05 22:32 UTC, jesserockz commented on esphome/components/mpl115a2/mpl115a2.cpp
> +  c12coeff = (((uint16_t) buffer[6] << 8) | buffer[7]) >> 2;
```suggestion
  a0coeff = encode_uint16(buffer[0], buffer[1]);
  b1coeff = encode_uint16(buffer[2], buffer[3]);
  b2coeff = encode_uint16(buffer[4], buffer[5]);
  c12coeff = encode_uint16(buffer[6], buffer[7]) >> 2;
```

This will also require `#include "esphome/core/helpers.h"`

2024-05-05 22:32 UTC, jesserockz commented on esphome/components/mpl115a2/mpl115a2.cpp
> +  mpl115a2_c12_ /= 4194304.0;
```suggestion
  this->mpl115a2_a0_ = a0coeff / 8.0f;
  this->mpl115a2_b1_ = b1coeff / 8192.0f;
  this->mpl115a2_b2_ = b2coeff / 16384.0f;
  this->mpl115a2_c12_ = c12coeff / 4194304.0f;
```

2024-05-05 22:32 UTC, jesserockz commented on esphome/components/mpl115a2/mpl115a2.cpp
> +  ESP_LOGD(TAG, "Got Temperature=%.1f°C Pressure=%.1f", temperature_out, pressure_out);
```suggestion
  // Wait a bit for the conversion to complete (3ms max)
  this->set_timeout(5, [this, cmd]() {
    uint8_t buffer[4];
	  cmd[0] = MPL115A2_REGISTER_PRESSURE_MSB;
	  this->write(cmd, 1);
	  this->read(buffer, 4);
	
	  uint16_t pressure_in = encode_uint16(buffer[0], buffer[1]) >> 6;
	  uint16_t temp_in = encode_uint16(buffer[2], buffer[3]) >> 6;
	
	  // See datasheet p.6 for evaluation sequence
	  float pressure_comp = mpl115a2_a0_ + (mpl115a2_b1_ + mpl115a2_c12_ * temp_in) * pressure_in + mpl115a2_b2_ * temp_in;
	
	  float pressure_out = ((65.0f / 1023.0f) * pressure_comp) + 50.0f;
	  if (this->pressure_ != nullptr)
	    this->pressure_->publish_state(pressure_out);
	
	  float temperature_out = ((float) temp_in - 498.0f) / -5.35f + 25.0f;
	  if (this->temperature_ != nullptr)
	    this->temperature_->publish_state(temperature_out);
	
	  ESP_LOGD(TAG, "Got Temperature=%.1f°C Pressure=%.1f", temperature_out, pressure_out);
  });
```

2024-05-05 22:32 UTC, jesserockz commented on esphome/components/mpl115a2/mpl115a2.cpp
> +  this->status_clear_warning();
There is nowhere a warning is set, so no need to clear
```suggestion
```

2024-05-05 22:32 UTC, jesserockz commented on esphome/components/mpl115a2/mpl115a2.h
> +  void set_pressure(sensor::Sensor *pressure) { pressure_ = pressure; }
```suggestion
  void set_temperature(sensor::Sensor *temperature) { this->temperature_ = temperature; }
  void set_pressure(sensor::Sensor *pressure) { this->pressure_ = pressure; }
```

2024-05-05 22:32 UTC, jesserockz commented on esphome/components/mpl115a2/mpl115a2.cpp
> +
```suggestion
  uint8_t cmd[2] = {MPL115A2_REGISTER_STARTCONVERSION, 0};
```

2024-05-05 22:32 UTC, jesserockz commented on esphome/components/mpl115a2/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_PRESSURE])
```suggestion
    if pressure_sensor := config.get(CONF_PRESSURE):
        sens = await sensor.new_sensor(pressure_sensor)
```

2024-05-05 22:32 UTC, jesserockz commented on esphome/components/mpl115a2/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_TEMPERATURE])
```suggestion
    if temperature_sensor := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_sensor)
```

2024-05-05 22:32 UTC, jesserockz commented on tests/test1.yaml
Please move this to its own file in `tests/components/mpl115a2/`

2024-05-06 20:21 UTC, unic8s commented on tests/test1.yaml
@jesserockz I did so - should I remove it from the test1.py as well?

2024-06-03 12:21 UTC, unic8s reviewed
Looks good to me. I did some changes to fix the reference issue inside the timeout callback. Thank you very much

2024-09-24 22:32 UTC, closed without merging