add testcard when no pages or lambda is provided.
OttoWinter/esphomeyaml pull request #6608
Opened 2024-04-23 00:32 UTC by nielsnl68

# What does this implement/fix?

When you start with using a display you want to know how it is shown and if the colors etc. are correct. This PR shows a testcard with the RGB colors, an indicator what the top left corner is and text (R,G,B) to validate the display is oriented.

The main purpose to help people that has issues with there display show what is going on with there display.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  - platform: ili9xxx
    model: ili9342
    spi_id: tft
    cs_pin:
      ignore_strapping_warning: true
      number: GPIO15
    dc_pin:
      ignore_strapping_warning: true
      number: GPIO2
    color_order: RGB
    #invert_colors: true
    transform:
      mirror_y: true
      mirror_x: false
      swap_xy: false
      #pages:
      #lambda:
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-23 02:09 UTC, jesserockz commented
As with all ESPHome code, we prefer not to have "magical" things happen like this.

It would make more sense if it was a function to call inside the lambda or a page:
```yaml
lambda: |-
  it.test_card();
```

2024-04-23 02:12 UTC, clydebarrow commented on esphome/components/display/display.cpp
> +  } else {
When LVGL is in use, this would get triggered since there is no lambda.

```suggestion
  } else if (this->auto_clear_enabled_) {
```

2024-04-23 02:17 UTC, clydebarrow commented
Nice idea! A couple of suggestions - as well as the `fade_to_{white,black}` areas (which don't need to be repeated 7 times IMHO) something equivalent to this lambda is useful to diagnose mis-wired RGB interfaces, since it allows identification of individual bits for each color.

```
      it.filled_rectangle(0, 0, 40, 40, Color(0x80, 0, 0));
      it.filled_rectangle(0, 60, 40, 40, Color(0x40, 0, 0));
      it.filled_rectangle(0, 120, 40, 40, Color(0x20, 0, 0));
      it.filled_rectangle(0, 180, 40, 40, Color(0x10, 0, 0));
      it.filled_rectangle(0, 240, 40, 40, Color(0x8, 0, 0));

      it.filled_rectangle(40, 0, 40, 40, Color(0, 0x80, 0));
      it.filled_rectangle(40, 60, 40, 40, Color(0, 0x40, 0));
      it.filled_rectangle(40, 120, 40, 40, Color(0, 0x20, 0));
      it.filled_rectangle(40, 180, 40, 40, Color(0, 0x10, 0));
      it.filled_rectangle(40, 240, 40, 40, Color(0, 0x8, 0));
      it.filled_rectangle(40, 320, 40, 40, Color(0, 0x4, 0));

      it.filled_rectangle(80, 0, 40, 40, Color(0, 0, 0x80));
      it.filled_rectangle(80, 60, 40, 40, Color(0, 0, 0x40));
      it.filled_rectangle(80, 120, 40, 40, Color(0, 0, 0x20));
      it.filled_rectangle(80, 180, 40, 40, Color(0, 0, 0x10));
      it.filled_rectangle(80, 240, 40, 40, Color(0, 0, 0x8));
```

2024-04-23 02:19 UTC, clydebarrow commented on esphome/components/display/display.cpp
> +  } else {
Or what Jesse said.

2024-04-23 02:22 UTC, nielsnl68 commented on esphome/components/display/display.cpp
> +  } else {
Good point, i will follow Jesses suggestion. And make it a callable method.

2024-04-23 02:27 UTC, nielsnl68 commented
> Nice idea! A couple of suggestions - as well as the `fade_to_{white,black}` areas (which don't need to be repeated 7 times IMHO) something equivalent to this lambda is useful to diagnose mis-wired RGB interfaces, since it allows identification of individual bits for each color.
> 
the reason i used the fade_to is to see of the display driver runs in 8 or 16 bit mode. Having just a couple of blocks does not show that 100%. And it cost not that much time extra. The testcard is just called once after that the poller is stopt.

2024-04-23 02:28 UTC, nielsnl68 commented
> As with all ESPHome code, we prefer not to have "magical" things happen like this.
> 
> It would make more sense if it was a function to call inside the lambda or a page:
> 
> ```yaml
> lambda: |-
>   it.test_card();
> ```

Yes, i will do this.

2024-04-23 02:39 UTC, clydebarrow commented
> the reason i used the fade_to is to see of the display driver runs in 8 or 16 bit mode. Having just a couple of blocks does not show that 100%.

Each repetition is the same, I'm suggesting keeping that, with say 2 repetitions over half the area, add the single-bit colours in the other half.  This number of copies of the same gradients seems unnecessary:
<img width="314" alt="Screenshot 2024-04-23 at 12 38 56 pm" src="https://github.com/esphome/esphome/assets/2366188/e5a1d232-1706-4fb8-8211-96f85553c888">

2024-04-23 08:26 UTC, nielsnl68 commented
> > the reason i used the fade_to is to see of the display driver runs in 8 or 16 bit mode. Having just a couple of blocks does not show that 100%.
> 
> Each repetition is the same, I'm suggesting keeping that, with say 2 repetitions over half the area, add the single-bit colours in the other half. This number of copies of the same gradients seems unnecessary.

Is this how you see it on your display?

2024-04-23 08:56 UTC, clydebarrow commented on esphome/components/display/display.cpp
> +    }
When image_h is > 255 the value passed to esp_scale (which takes 8 bit arguments) is truncated.
```suggestion
    image_w = std::min(w - 20, 310);
    image_h = std::min(h - 20, 255);
```

2024-04-23 08:56 UTC, clydebarrow commented
> Is this how you see it on your display?

Yes. Found the reason - https://github.com/esphome/esphome/pull/6608/files#r1575898035

2024-04-23 09:01 UTC, nielsnl68 commented
> > Is this how you see it on your display?
> 
> Yes. Found the reason - https://github.com/esphome/esphome/pull/6608/files#r1575898035

Okay thanks. your suggestion is added.

2024-04-23 12:45 UTC, nielsnl68 commented
Thinking about it a bit more i decided to make it much easier to popup the testcard.
Now you can just add `show_testcard: true` to the display component configuration and it shows up at the first moment the display is updated.

2024-04-24 01:29 UTC, clydebarrow requested changes

2024-04-24 01:29 UTC, clydebarrow commented on esphome/components/display/__init__.py
> +CONF_SHOW_TESTCART = "show_testcart"
Should be `CONF_SHOW_TESTCARD`

2024-04-24 01:29 UTC, clydebarrow commented on esphome/components/display/__init__.py
> +    if (CONF_SHOW_TESTCART in config) and (config[CONF_PAGES] is True):
Why only if PAGES is true? 

This should probably only be permitted if neither PAGES nor LAMBDA are set.

And since it's a boolean, if set to False the card should not be shown. As written, `show_testcart: false` will still show the card.

2024-04-24 08:13 UTC, nielsnl68 commented on esphome/components/display/__init__.py
> +    if (CONF_SHOW_TESTCART in config) and (config[CONF_PAGES] is True):
Oeps, [dutch] foutje bedankt [/dutch] that should have been `CONF_SHOW_TESTCART`

2024-04-24 12:56 UTC, nielsnl68 commented
> > Is this how you see it on your display?
> 
> Yes. Found the reason - https://github.com/esphome/esphome/pull/6608/files#r1575898035

Clyde could you hummer me, why your fix works better then what i did? I just cant understand. And i want to learn from my mistake. :D 
while i was testing it the **c** value nicely from 0 to 255. But when i see your image it looks as if it did do the same loop multiple times.

2024-04-24 23:03 UTC, clydebarrow commented
> Clyde could you humour me, why your fix works better then what i did?

In your original code you had this:
```
    if (w > h) {
      image_w = w > 330 ? 310 : w - 20;
      image_h = h > 280 ? 255 : h - 20;
    } else {
      image_h = h > 330 ? 310 : h - 20;
      image_w = w > 280 ? 255 : w - 20;
    }
```
So `image_h` could be (and was in my test cases) greater than 255. But, you then passed that value to `esp_scale()`:
```
      int c = esp_scale(i, image_h);

```
and the arguments to `esp_scale()` are defined as `uint8_t`:
```
inline static uint8_t esp_scale(uint8_t i, uint8_t scale, uint8_t max_value = 255) { return (max_value * i / scale); }
```

So e.g. a value for `image_h` of 280 gets truncated to 8 bits and would be seen by `esp_scale()` as 24, so as you go around the loop 280 times, the colour value cycles within a range of only 24 distinct values, so the pattern gets repeated numerous times.

Any portrait mode with height greater than 255 would fail to display as expected (as would landscape mode between 256 and 280.) So I assume you did not test in portrait mode, or you used a really small display.

2024-04-24 23:13 UTC, nielsnl68 commented
thanks for the explanation. I was looking at the wrong place. and could not figure out what was wrong.

2024-04-25 04:32 UTC, clydebarrow requested changes

2024-04-25 04:32 UTC, clydebarrow commented on esphome/components/display/__init__.py
> +    if (CONF_SHOW_TEST_CARD in config) and (config[CONF_SHOW_TEST_CARD] is True):
```suggestion
    if config.get(CONF_SHOW_TEST_CARD):
```

2024-04-25 04:32 UTC, clydebarrow commented on esphome/components/display/__init__.py
> +        cv.Optional(CONF_SHOW_TEST_CARD): cv.boolean,
There should really be a check here that `show_test_card` is not true if a lambda has been provided.

2024-04-25 23:27 UTC, nielsnl68 commented on esphome/components/display/__init__.py
> +        cv.Optional(CONF_SHOW_TEST_CARD): cv.boolean,
The show_test_card flag overrules the lambda and pages. So both can exist.

2024-04-26 00:23 UTC, clydebarrow approved these changes
Working fine here.

2024-04-26 00:54 UTC, nielsnl68 commented
> Working fine here.

Could you make a picture to add to the Display doc?

2024-04-26 03:23 UTC, merged