New sensor component : ds248x
OttoWinter/esphomeyaml pull request #6616
Opened 2024-04-23 12:21 UTC by alainstark

# What does this implement?

This  new component help to build wide and reliable 1-wire network. It support for now only temperature sensors of type ds18b20.

This component is writen to drive ds248x family of I²C to 1-wire bus.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [x] RP2040
- [x] BK72xx
- [x] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: "olimex-01"
  friendly_name: "olimex-01"

esp32:
  board: esp32-poe-iso

# Enable logging
logger:
  # level: INFO
  level: DEBUG
  # level: VERBOSE
  # level: VERY_VERBOSE

<<: !include inc/olimex_network.yaml
<<: !include inc/auth.yaml

external_components:
  # source: github://mknjc/esphome@ds248x
  source:
    type: local
    path: local_components
  components: [ ds248x ]

i2c:
  sda: GPIO13 # set your i2c pins
  scl: GPIO16 # set your i2c pins
  id: bus_a
  frequency: 400kHz # 400 is the maximum the ds2484 supports

ds248x:
  i2c_id: bus_a
  type: ds2482-800
  address: 0x1f # should be the default
#  sleep_pin: 32 # remove if not needed, if set the ds248x sleeps when no transaction is in progress
  active_pullup: true # adds a active pullup which should improve signal integrity
  strong_pullup: false
  bus_sleep: false
#  strong_pullup: true # enables a strong pullup used to provide the needed current for temperature reading without vcc connected
#  bus_sleep: true # power down the bus when no transaction is in progres
  update_interval: 10s

sensor:

# Channel 0

  - platform: ds248x
    address: 0x80000002a5fea828
    channel: 0
    name: "Temp-01"
    resolution: 12

  - platform: ds248x
    address: 0x3a000002ceac6928
    channel: 0
    name: "Temp-02"
    resolution: 12

  - platform: ds248x
    address: 0x3a000002ceac6928
    channel: 0
    name: "Temp-03"
    resolution: 12

# Channel 1

  - platform: ds248x
    address: 0xf10000051c169828
    channel: 1
    name: "Temp-04"
    resolution: 12

  - platform: ds248x
    address: 0xda000002cea33128
    channel: 1
    name: "Temp-05"
    resolution: 12

  - platform: ds248x
    address: 0xe9000002ce987728
    channel: 1
    name: "Temp-06"
    resolution: 12

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-23 12:58 UTC, nagyrobi commented
Please edit the top message by specifying the PR number for the docs.
Add your codeowners as suggested by the bot.
Please add some tests to the esphome\tests directory. It needs a basic config-like yaml just with the dependency components you need this component to run, with some dummy config.

2024-04-23 15:01 UTC, nagyrobi commented
You can also link the feature request to the "Related issue or feature (if applicable): fixes" sentece in the opening message.

2024-04-24 21:48 UTC, alainstark commented
Hello,
I have a problem with CODEOWNERS
I am not the principal writer of this component. I have only adapt this to support ds2482-800 the principal writer is [mkncj](https://github.com/mknjc).
[mkncj/esphome](https://github.com/mknjc/esphome)

2024-05-07 13:53 UTC, martijnbuts commented
What board did you use for testing?

2024-05-07 14:48 UTC, alainstark commented
I use an [Olimex esp32 PoE ISO](https://www.olimex.com/Products/IoT/ESP32/ESP32-POE-ISO/open-source-hardware).

2024-05-07 14:59 UTC, labricolenumerique commented
> I use an [Olimex esp32 PoE ISO](https://www.olimex.com/Products/IoT/ESP32/ESP32-POE-ISO/open-source-hardware).

@alainstark Which ds248x board do you use as an i²C <==> OneWire adapter?
ds248x

2024-05-07 16:53 UTC, martijnbuts commented
I searched for the chip but i only find the chip itself, not a board. I am interested in testing because of the following: 

Internal factory trimmed timers relieve the system host processor from generating time-critical 1-Wire waveforms, supporting both standard and Overdrive 1-Wire communication speeds.
https://www.analog.com/en/products/ds2482-100.html 

I have a ESP32-S3 with a lot of sensors and also a modbus connectection and when I add the ds18b20 I get some strange problems. When I use the ds18b20 without the other sensors and modbus connection it works good. 
I would like tot test if the ds248x board solve the problem based on the information from the datasheet.

2024-05-07 16:54 UTC, alainstark commented
This component is working with many I²C to 1-wire : ds2482-100, ds2482-800

2024-05-07 16:56 UTC, martijnbuts commented
> This component is working with many I²C to 1-wire : ds2482-100, ds2482-800

Where did you order the ds2482-100 or ds2482-800?

2024-05-07 17:03 UTC, alainstark commented
I use t[his breakout board](https://www.tindie.com/products/closedcube/ds2482-800-i2c-to-8-channel-1-wire-breakout-board/) with this [I²C level shifter](https://www.sparkfun.com/products/15439).

2024-05-07 22:06 UTC, lboue commented
I noticed other chips in[ Analog Devices website](https://www.analog.com/en/parametricsearch/12875#/ps6=i2c): 

- [DS2484](https://www.analog.com/en/products/ds2484.html): Single-Channel 1-Wire Master with Adjustable Timing and Sleep Mode
  - Best-in-Class Integrated 1-Wire Line Driver Facilitates Protocol Conversion Between I2C Host and 1-Wire Slave Network
- [DS28E17](https://www.analog.com/en/products/ds28e17.html):  - 1-Wire-to-I2C Master Bridge: Extend I2C Slave Peripheral Communication Distance up to 100m

Do you know what the main difference is with these other references?

2024-05-08 00:04 UTC, jesserockz requested changes

2024-05-08 00:04 UTC, jesserockz commented on esphome/components/ds248x/__init__.py
> +AUTO_LOAD = ["sensor"]
Please move all of the sensor code into a `sensor` directory so that the parent component does not rely on the sensor headers.
```suggestion
```

2024-05-08 06:40 UTC, lboue commented
> I noticed other chips in [Analog Devices website](https://www.analog.com/en/parametricsearch/12875#/ps6=Master):
> 
> * [DS2484](https://www.analog.com/en/products/ds2484.html): Single-Channel 1-Wire Master with Adjustable Timing and Sleep Mode
>   
>   * Best-in-Class Integrated 1-Wire Line Driver Facilitates Protocol Conversion Between I2C Host and 1-Wire Slave Network
> * [DS28E17](https://www.analog.com/en/products/ds28e17.html):  - 1-Wire-to-I2C Master Bridge: Extend I2C Slave Peripheral Communication Distance up to 100m
> 
> Do you know what the main difference is between the DS2482 and these other references?

I started a discussion about that : [[One-Wire] I²C Master to 1-wire bus slave adapter #6699 ](https://github.com/esphome/esphome/discussions/6699)

2024-05-08 11:15 UTC, alainstark commented on esphome/components/ds248x/__init__.py
> +AUTO_LOAD = ["sensor"]
Ok I have make the change but I am a poor git user.
```
$ git status
On branch dev
Your branch is up to date with 'origin/dev'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   CODEOWNERS
	modified:   esphome/components/ds248x/__init__.py
	modified:   esphome/components/ds248x/ds248x.cpp
	modified:   esphome/components/ds248x/ds248x.h
	renamed:    esphome/components/ds248x/sensor.py -> esphome/components/ds248x/sensor/__init__.py
	new file:   esphome/components/ds248x/sensor/ds248x_temperature_sensor.cpp
	new file:   esphome/components/ds248x/sensor/ds248x_temperature_sensor.h
```
but the commit failed :
```
$ git commit -m "create sensor directory and restructure"
black....................................................................Passed
flake8...................................................................Passed
Don't commit to branch...................................................Failed
- hook id: no-commit-to-branch
- exit code: 1
pyupgrade................................................................Passed
```
Can you help me please ?

2024-05-09 20:54 UTC, alainstark commented on esphome/components/ds248x/__init__.py
> +AUTO_LOAD = ["sensor"]
Ok I used github web interface to change my code.

2024-05-09 22:48 UTC, jesserockz commented on esphome/components/ds248x/__init__.py
> +AUTO_LOAD = ["sensor"]
You should be doing your work on a new branch inside your fork, not the `dev` branch.

2024-05-10 13:18 UTC, alainstark commented on esphome/components/ds248x/__init__.py
> +AUTO_LOAD = ["sensor"]
Sorry but as said, I'm a beginner with git. What should I do now?

2024-05-16 07:14 UTC, alainstark commented
Excuse me but I don't know what I should do.
Maybe I just have to wait but I'm asking the question because @jesserockz tells me that I should have created a new branch for restructuring the code but I did it in the dev branch and I don't know how to go back.
On the other hand, there is the automatic code check which indicates an error :
`Run script/ci-custom: CODEOWNERS file is not up to date.`
So I thought I had to add myself to this file which is at the root but again I think I did it wrong.
Suddenly, I no longer dare to do anything except wait for things to change.
Thank you in advance for your help.

2024-05-16 18:29 UTC, martijnbuts commented
I would suggest to ask it on the esphome discord,  i just recieved the ds2482-100 and i hope this pr got merged.

2024-05-18 06:38 UTC, lboue commented
> I noticed other chips in [Analog Devices website](https://www.analog.com/en/parametricsearch/12875#/ps6=Master):
> 
> * [DS2484](https://www.analog.com/en/products/ds2484.html): Single-Channel 1-Wire Master with Adjustable Timing and Sleep Mode
>   
>   * Best-in-Class Integrated 1-Wire Line Driver Facilitates Protocol Conversion Between I2C Host and 1-Wire Slave Network
> * [DS28E17](https://www.analog.com/en/products/ds28e17.html):  - 1-Wire-to-I2C Master Bridge: Extend I2C Slave Peripheral Communication Distance up to 100m

Adafruit is preparing a new board: [DS2484 I2C to 1-Wire converter](https://x.com/adafruit/status/1791604099764416659) based on the [DS2484](https://www.analog.com/en/products/ds2484.html) (Single-Channel 1-Wire Master with Adjustable Timing and Sleep Mode).

2024-05-24 15:18 UTC, lboue commented
> I would suggest to ask it on the esphome discord, i just recieved the ds2482-100 and i hope this pr got merged.

@martijnbuts There's no need to wait. Just configure this:

```yaml
external_components:
  source: github://mknjc/esphome@ds248x
  components: [ ds248x ]

i2c:
  sda: # set your i2c pins
  scl: # set your i2c pins
  id: bus_a
  frequency: 400kHz # 400 is the maximum the ds2484 supports

ds248x:
  i2c_id: bus_a
  # type: ds2482-800
  address: 0x1f # should be the default
  #  sleep_pin: 32 # remove if not needed, if set the ds248x sleeps when no transaction is in progress
  active_pullup: true # adds a active pullup which should improve signal integrity
  strong_pullup: false
  bus_sleep: false
  #  strong_pullup: true # enables a strong pullup used to provide the needed current for temperature reading without vcc connected
  #  bus_sleep: true # power down the bus when no transaction is in progres
  update_interval: 10s
```

2024-05-31 09:09 UTC, ssieb commented
I'm almost finished the conversion of 1-wire to be a bus component.  Do you want me to include the bus part of this into mine or do you want to adjust this after mine is in?  The sensor part of this will go away entirely.

2024-05-31 10:16 UTC, alainstark commented
Hey @ssieb, yes, its a good thing to write a 1-wire bus component so it can support all separate 1-wire components and not only ds18b20 temerature sensors.
My problem is that community development via git is new and I still have to learn. I would like to participate in your project by integrating my code but I just need a little help with git. Is it possible for you?

2024-06-05 06:18 UTC, ssieb commented
Somehow I missed your reply here.  Please reply to me on discord and we can figure out where to go with this.

2024-06-13 05:47 UTC, lboue commented
There's a new board with this component [Adafruit DS2484 I2C to 1-Wire Bus Adapter Breakout - STEMMA QT / Qwiic JST SH 1mm](https://www.adafruit.com/product/5976)

2024-06-19 05:08 UTC, martijnbuts commented
Will this be integrated in the one wire componenten? @ssieb

2024-06-22 10:54 UTC, martijnbuts commented
> ```yaml
>  - platform: ds248x
>     address: 0x80000002a5fea828
>     channel: 0
>     name: "Temp-01"
>     resolution: 12
> ```

I just got it working ;)
can you update the documentation with type not needed and channel?
I could find the board so i ordered the chip and create one myself.0.
![ds248x](https://github.com/esphome/esphome/assets/103023334/6afb7274-e074-49c9-9859-c55fe962e870)


ds248x:
  i2c_id: bus_a
  # type: ds2482-100
  address: 0x18 # should be the default
#  sleep_pin: 32 # remove if not needed, if set the ds248x sleeps when no transaction is in progress
  active_pullup: true # adds a active pullup which should improve signal integrity
  strong_pullup: false
  bus_sleep: false
#  strong_pullup: true # enables a strong pullup used to provide the needed current for temperature reading without vcc connected
#  bus_sleep: true # power down the bus when no transaction is in progres
  update_interval: 10s


 - platform: ds248x
    address: 0x9803191c52331728
#    channel: 0
    name: "Temp-01"
    resolution: 12

2024-06-22 11:34 UTC, lboue commented
> I just got it working ;) can you update the documentation with type not needed and channel for the ds2482-100? I could find the board so i ordered the chip and create one myself.

You can comment this PR for the doc: [Documentation of ds248x component #3792](https://github.com/esphome/esphome-docs/pull/3792).

2024-06-22 11:43 UTC, martijnbuts commented
> > I just got it working ;) can you update the documentation with type not needed and channel for the ds2482-100? I could find the board so i ordered the chip and create one myself.
> 
> You can comment this PR for the doc: [Documentation of ds248x component #3792](https://github.com/esphome/esphome-docs/pull/3792) to propose an addition to the documentation for [DS2482-100 Single-Channel 1-Wire Master](https://www.analog.com/en/products/ds2482-100.html).

Thanks, i am not so handy yet with github but i give it a try.

2024-07-20 11:59 UTC, lboue commented
@alainstark

**ESPHome test**

Test with the following example works great with the Adafruit DS248x Breakout Board: https://www.adafruit.com/product/5976
https://github.com/adafruit/Adafruit_DS248x/blob/main/examples/DS2484_DS18B20/DS2484_DS18B20.ino

```
[13:43:51][I][i2c.arduino:096]: Results from i2c bus scan:
[13:43:51][I][i2c.arduino:102]: Found i2c device at address 0x18
[13:43:51][C][ds248x:103]: DS248x:
[13:43:51][C][ds248x:107]:   Address: 0x18
[13:43:51][D][ds248x:114]:   Found sensors:
[13:43:51][D][ds248x:116]:     0x7a000005fab2f728
[13:43:51][C][ds248x:119]:   Update Interval: 10.0s
[13:43:51][C][ds248x:122]:   Device 'Temperature #1'
[13:43:51][C][ds248x:122]:     Device Class: 'temperature'
[13:43:51][C][ds248x:122]:     State Class: 'measurement'
[13:43:51][C][ds248x:122]:     Unit of Measurement: '°C'
[13:43:51][C][ds248x:122]:     Accuracy Decimals: 1
[13:43:51][C][ds248x:130]:     Address: 0x7a000005fab2f728
[13:43:51][C][ds248x:131]:     Resolution: 12
[13:43:51][C][esphome.ota:073]: Over-The-Air updates:
[13:43:51][C][esphome.ota:074]:   Address: s3-ds248x-i2c-to-1wire.local:3232
[13:43:51][C][esphome.ota:075]:   Version: 2
[13:43:51][C][esphome.ota:078]:   Password configured
[13:43:51][C][safe_mode:018]: Safe Mode:
[13:43:51][C][safe_mode:020]:   Boot considered successful after 60 seconds
[13:43:51][C][safe_mode:021]:   Invoke after 10 boot attempts
[13:43:51][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[13:43:51][C][api:139]: API Server:
[13:43:51][C][api:140]:   Address: s3-ds248x-i2c-to-1wire.local:6053
[13:43:51][C][api:142]:   Using noise encryption: YES
[13:43:53][D][ds248x:199]: 'Temperature #1': Got Temperature=28.4°C
[13:43:53][D][sensor:094]: 'Temperature #1': Sending state 28.37500 °C with 1 decimals of accuracy
[13:44:03][D][ds248x:199]: 'Temperature #1': Got Temperature=28.4°C
[13:44:03][D][sensor:094]: 'Temperature #1': Sending state 28.43750 °C with 1 decimals of accuracy
[13:44:13][D][ds248x:199]: 'Temperature #1': Got Temperature=28.4°C
```

**Config issue**
The `type `setting is specified as mandatory in the documentation. However, when this parameter is set, it generates an error.

`   [type] is an invalid option for [ds248x]. Please check the indentation.`

**Test config**
```
ds248x:
  i2c_id: bus_b
  type: ds2484
  address: 0x18 # should be the default
```

2024-07-20 12:49 UTC, lboue commented
@alainstark 
Could you accept my pull request to you Github repo:
[[ds248x] Support for DS2484 Single-Channel 1-Wire Master #2](https://github.com/alainstark/esphome/pull/2)

2024-07-29 19:00 UTC, alainstark commented
Hey @lboue
Excuse me but I'm in holliday.
Are you French ? If yes, you can send me a mail to astark@medialsace.fr so we can communicate in french on a private channel.
Bye

2024-07-29 19:09 UTC, lboue commented
@alainstark 
Yes I am French.

2024-07-30 17:21 UTC, lboue commented
> I'm almost finished the conversion of 1-wire to be a bus component.  Do you want me to include the bus part of this into mine or do you want to adjust this after mine is in?  The sensor part of this will go away entirely.

@ssieb 
Have you successfully integrated the bus part your onewire  component?

2024-07-30 17:25 UTC, ssieb commented
That was integrated 2 releases ago.

2024-08-06 05:34 UTC, lboue commented
> That was integrated 2 releases ago.

@clydebarrow 
What configuration should I use?
I didn't find how in the 1-Wire Bus page: https://esphome.io/components/one_wire.html.

2024-08-06 06:07 UTC, clydebarrow commented
Please don't ping random people - use the Discord general support channel to ask for help.

2025-07-10 18:43 UTC, tomtom13 commented
Have there been any progress with that ? 
I wanted to design a pcb with multiple 1-wire sensors (industrial connectivity) and this multiplexer would be beneficial.

2025-07-11 07:12 UTC, lboue commented
Check this: [[ds2484] New component #9147](https://github.com/esphome/esphome/pull/9147)

2025-09-01 03:18 UTC, charlesrg commented
Great work on this guys, really looking forward to see this pull request making mainstream. Really appreciate the efforts.

2025-09-01 06:10 UTC, lboue commented
> Great work on this guys, really looking forward to see this pull request making mainstream. Really appreciate the efforts.

https://esphome.io/components/one_wire/ds2484/

2025-09-13 02:09 UTC, charlesrg commented
> > Great work on this guys, really looking forward to see this pull request making mainstream. Really appreciate the efforts.
> 
> https://esphome.io/components/one_wire/ds2484/

This only cover 2484 not 2482. 2482-800 have up to 8 one wire channels.

2025-10-15 14:14 UTC, martijnbuts commented
Hi, any news on the ds2482-100 to be added as a standard component?

2025-12-17 10:40 UTC, sermaster2477 commented
"Hi @alainstark, I have DS2482-800 with multiple channels and ready to test the component. I can provide logs, help with tests/docs or anything to move this PR forward. Let me know how I can help!"

2026-01-02 11:06 UTC, tomwellnitz commented
Hi @alainstark and everyone following this PR.

I have just submitted a new Pull Request that implements the DS248x family support: https://github.com/esphome/esphome/pull/12717

I wanted to highlight the key architectural difference between these two implementations, as it aligns with the recent OneWire refactoring mentioned by @ssieb earlier:

This PR (#6616): Implements ds248x as a Sensor Platform. It handles the 1-Wire protocol internally but is effectively limited to DS18B20 temperature sensors (re-implementing the sensor logic).
My PR: Implements ds248x as a OneWire Bus Platform (one_wire component). It acts purely as a bridge/interface.
The Benefit: By implementing the Bus interface, the new PR allows any existing ESPHome 1-Wire component (e.g., dallas_temp, ds2438, dallas_hub, etc.) to work transparently with DS248x chips without any code duplication or modification.

Feel free to check it out and test it!

2026-04-03 10:26 UTC, henrykuijpers commented
@alainstark Would it also be possible to auto-expose onewire sensors? Currently, we have to hardcode all the device IDs which means connecting everything the first time, then obtaining the IDs and then adding them to the yaml.

It would be nice if a sensor could automatically be created whenever a new device ID is found.

2026-04-03 14:55 UTC, tomtom13 commented
> @alainstark Would it also be possible to auto-expose onewire sensors? Currently, we have to hardcode all the device IDs which means connecting everything the first time, then obtaining the IDs and then adding them to the yaml.
> 
> It would be nice if a sensor could automatically be created whenever a new device ID is found.

Let's not give this dude more feature requests making it harder to push this PR through esp home "council" ;) Trust me we should count our lucky stars if this gets in.

2026-07-30 01:50 UTC, swoboda1337 commented
Closing this out: DS248x support has since landed via #12717, which reimplemented this as a OneWireBus platform and is now merged. Thanks for the original work here — it paved the way. For feature requests against the in-tree component (like auto-discovering onewire devices), please open a separate feature request.

2026-07-30 01:50 UTC, closed without merging