BedJet: expose the outlet temperature on the climate and as a sensor
OttoWinter/esphomeyaml pull request #6633
Opened 2024-04-25 09:07 UTC by javawizard

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-25 09:08 UTC, javawizard commented
This is still a draft - I accidentally hit the button early. Sorry for the noise!

2024-04-25 09:46 UTC, javawizard commented on esphome/components/bedjet/__init__.py
> +        cv.GenerateID(CONF_BEDJET_ID): cv.use_id(BedJetHub),
@jhansche - this makes the `bedjet_id:` config field optional when there's only one `bedjet:` hub configured.

2024-04-25 11:48 UTC, javawizard commented
Alright this is ready for review!

2024-04-25 19:47 UTC, jhansche approved these changes
Thank you for this! The code looks good - with a minor suggestion for reducing code duplication.

2024-04-25 19:47 UTC, jhansche commented on esphome/components/bedjet/bedjet_const.h
> +  TEMPERATURE_SOURCE_OUTLET,
There have been other discussions about this topic in the past, and I guess my main holdup is that typically a climate entity has the goal of altering the temperature, until the current temp matches the target temp, at which point its job is more or less "done" for now.

When using the outlet temp, it will (or should) 99% of the time match the target temp -- if it doesn't, then that means you have a problem with your BedJet, because it has a fine grained regulator to keep the outlet air pushing a constant temp that matches the target. And with that in mind, it does not just stop blowing air once the target temp is reached.

Personally I don't find that useful, because the two numbers will almost always be aligned.

At the same time, a typical climate entity _will_ influence the ambient air temp, until they are eventually aligned - so in that perspective, showing a climate entity where the ambient temp will never actually move in the direction of the target, is also awkward and not quite consistent with how a normal climate entity would work.

That said, I appreciate that it is a configuration option, and I recognize that my opinion is not the only one out there! 🙌  So thanks for making it configurable 👍 

One thing to keep in mind is that this outlet temp will now be included in the average temp of the room where the ESPHome climate entity is - so if you have the BedJet in a bedroom Room, and an ambient air temp sensor in the same Room, a Room card will display the average of those temps, which will be incorrect when the outlet temp source is chosen. It's a pretty minor detail overall, but might be something we want to call out in the documentation.

2024-04-25 19:47 UTC, jhansche commented on esphome/components/bedjet/climate/bedjet_climate.cpp
> +  }
Given the nearly identical code, it might be easier to read with a ternary (or two)? 🤔 
```cpp
auto source_temp =
  this->temperature_source_ == TEMPERATURE_SOURCE_OUTLET ? data->actual_temp_step
    : this->temperature_source_ == TEMPERATURE_SOURCE_AMBIENT ? data->ambient_temp_step
      : 0;
if (converted_temp > 0) {
  this->current_temperature = bedjet_temp_to_c(source_temp)
}
```

2024-04-25 19:47 UTC, jhansche commented on esphome/components/bedjet/sensor/__init__.py
minor: I would generally prefer to split these into 2 separate PRs: one for the climate entity temp source, and a 2nd for the new sensor platform.

That said, the sensor addition is surprisingly simple! And it's exactly what I had in mind when refactoring to add the "hub".

2024-04-25 19:47 UTC, jhansche commented on esphome/components/bedjet/__init__.py
> +        cv.GenerateID(CONF_BEDJET_ID): cv.use_id(BedJetHub),
Awesome - great idea. I assume this is automatic in ESPHome, when there is only one instance (and will raise a validation error if there's more than one)?

2024-04-25 19:59 UTC, jhansche commented on esphome/components/bedjet/bedjet_const.h
> +  TEMPERATURE_SOURCE_OUTLET,
Also note, I could be mistaken about the way a Room's temp gets averaged 🤔  Have you tested that, by chance? If it doesn't influence the room's average temp, then we can ignore that

2024-04-26 09:14 UTC, javawizard commented on esphome/components/bedjet/__init__.py
> +        cv.GenerateID(CONF_BEDJET_ID): cv.use_id(BedJetHub),
Exactly.

2024-04-26 09:22 UTC, javawizard commented on esphome/components/bedjet/climate/bedjet_climate.cpp
> +  }
Good call 👍

2024-04-26 09:24 UTC, javawizard commented on esphome/components/bedjet/sensor/__init__.py
Noted, and totally fair 🙂 

Agree! I love the hub approach, totally feels like the right way to do it.

2024-04-26 09:46 UTC, javawizard commented on esphome/components/bedjet/bedjet_const.h
> +  TEMPERATURE_SOURCE_OUTLET,
> One thing to keep in mind is that this outlet temp will now be included in the average temp of the room where the ESPHome climate entity is

Ok I think I'm totally missing something - I'm not seeing a Room card in my local HA instance's card browser, nor am I finding any other way of viewing an average temperature for a room. Is that a third-party card type? I see https://github.com/marcokreeft87/room-card but that seems to require entities to be listed out manually so I imagine that's not what you're talking about.

Let me know if there's somewhere specific I should be looking in the UI.

(Fun side note: I have temperature sensors in tons of things that are not at ambient temp - like my refrigerator and freezer, my 3D printer, and my laser cutter's fume extractor - so average room temperature readings would likely be totally off for me 🙂 )

> There have been other discussions about this topic in the past, and I guess my main holdup is that typically a climate entity has the goal of altering the temperature, until the current temp matches the target temp, at which point its job is more or less "done" for now.
> 
> When using the outlet temp, it will (or should) 99% of the time match the target temp -- if it doesn't, then that means you have a problem with your BedJet, because it has a fine grained regulator to keep the outlet air pushing a constant temp that matches the target. And with that in mind, it does not just stop blowing air once the target temp is reached.
> 
> Personally I don't find that useful, because the two numbers will almost always be aligned.
> 
> At the same time, a typical climate entity will influence the ambient air temp, until they are eventually aligned - so in that perspective, showing a climate entity where the ambient temp will never actually move in the direction of the target, is also awkward and not quite consistent with how a normal climate entity would work.
> 
> That said, I appreciate that it is a configuration option, and I recognize that my opinion is not the only one out there! 🙌 So thanks for making it configurable 👍

For sure. It's definitely a tricky one: neither temperature source seems to perfectly fit the way a climate entity would work. The argument against using the ambient temperature would of course be that a BedJet doesn't influence the ambient room temp _that much_, or at least that's not its primary purpose, and if for example I put it on cool at the lowest temperature I still want it to put out air even if the ambient temperature drops below the minimum setpoint of 66 degrees.

The reason I like seeing the outlet temperature is that I adjust the temperature on my BedJet quite frequently and often I'll think "hm, I don't feel like I turned it up/down enough, has it reached the target temp yet or is it still adjusting?" and then I'll look and see that it's still adjusting up or down and wait a few moments before making adjustments. It seems to take _just_ long enough to respond that I'm always second guessing it without knowing that - last I checked it takes ~2 minutes for the temperature to drop from 104 degrees down to ambient with the airflow at 20%, presumably because of all the residual heat in the heating block that has to be dissipated.

Anyway. I'm definitely in the same boat as you in recognizing that that's my preference and by no means everyone else's, so configurable it is! 🙂

2024-04-26 09:58 UTC, javawizard commented
@jhansche - responded and pushed changes, let me know if you have any more questions!

2024-04-26 14:24 UTC, jhansche commented on esphome/components/bedjet/bedjet_const.h
> +  TEMPERATURE_SOURCE_OUTLET,
> Ok I think I'm totally missing something - I'm not seeing a Room card in my local HA instance's card browser

My bad, it's the Area card, not Room 🤦‍♂️ Example(s)
![Screenshot_20240426-102332](https://github.com/esphome/esphome/assets/99272/3d0ded65-c84d-4e7c-8263-b37b7e77dbe8)

2024-04-26 14:29 UTC, jhansche approved these changes
Nice, and thanks for the PR!
Just FYI, I can't approve it for merge, but looks good

2024-04-26 23:21 UTC, javawizard commented
No worries @jhansche, I assume @jesserockz will be along soon enough to click the button.

Thanks for taking a look at this! (And thanks for writing this awesome component in the first place 😄)

2024-04-27 00:19 UTC, javawizard commented on esphome/components/bedjet/bedjet_const.h
> +  TEMPERATURE_SOURCE_OUTLET,
Ah, got it, no worries!

I just checked the area card and it looks like thermostat current temperatures are _not_ incorporated into an area's average temperature; only temperature sensors are.

2024-04-29 01:54 UTC, jesserockz requested changes

2024-04-29 01:54 UTC, jesserockz commented on esphome/components/bedjet/climate/bedjet_climate.cpp
> +                                                                                              : 0);
Multi level ternaries can get messy...
```suggestion
  if (this->temperature_source_ == TEMPERATURE_SOURCE_OUTLET) {
    converted_temp = bedjet_temp_to_c(data->actual_temp_step);
  } else {
    converted_temp = bedjet_temp_to_c(data->ambient_temp_step);
  }
```

2024-04-29 03:32 UTC, jhansche commented on esphome/components/bedjet/climate/bedjet_climate.cpp
> +                                                                                              : 0);
If we don't have the 3rd value, then it doesn't have to be multi-level:
```
  converted_temp = bedjet_temp_to_c(
    this->temperature_source_ == TEMPERATURE_SOURCE_OUTLET
      ? data->actual_temp_step
      : data->ambient_temp_step)
```
Since the source has to be one or the other, we don't have to fall back to 0

2024-04-29 03:47 UTC, jesserockz commented on esphome/components/bedjet/climate/bedjet_climate.cpp
> +                                                                                              : 0);
If it has to even be multiline, it shouldnt be a ternary. The compiler will optimise it in the end, so I would rather it be easier to read.

2024-04-29 04:58 UTC, javawizard commented on esphome/components/bedjet/climate/bedjet_climate.cpp
> +                                                                                              : 0);
Ha. No strong feelings myself either way!

Change accepted, this is ready for review again.

2024-05-02 04:08 UTC, jhansche approved these changes
LGTM 
@javawizard not sure if Jesse filters his view, but it might help to dismiss/re-request review to show that you've made the changes

2024-05-06 01:16 UTC, jesserockz requested changes

2024-05-06 01:16 UTC, jesserockz commented on esphome/components/bedjet/sensor/__init__.py
> +        sensor_var = await sensor.new_sensor(config[CONF_OUTLET_TEMPERATURE])
```suggestion
    if outlet_temperature_sensor := config.get(CONF_OUTLET_TEMPERATURE):
        sensor_var = await sensor.new_sensor(outlet_temperature_sensor)
```

2024-05-06 01:16 UTC, jesserockz commented on esphome/components/bedjet/sensor/__init__.py
> +        sensor_var = await sensor.new_sensor(config[CONF_AMBIENT_TEMPERATURE])
```suggestion
    if ambient_temperature_sensor := config.get(CONF_AMBIENT_TEMPERATURE):
        sensor_var = await sensor.new_sensor(ambient_temperature_sensor)
```

2024-05-15 13:41 UTC, jhansche approved these changes

2024-05-15 23:27 UTC, jesserockz approved these changes

2024-05-15 23:31 UTC, merged