Add StatsD component
OttoWinter/esphomeyaml pull request #6642
Opened 2024-04-26 10:04 UTC by Links2004

# What does this implement/fix?

Adding a new component that allows ESPHome to send StatsD gauges metric via UDP.

StatsD Infos:
https://github.com/statsd/statsd
https://github.com/statsd/statsd/blob/master/docs/metric_types.md

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> (in the works)

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

see  tests/test11.5.yaml

e.g.:
```yaml
statsd:
  host: "192.168.1.1"
  port: 8125
  prefix: esphome
  sensors:
    - id: adc_sensor_p32
      name: adc.32
  binary_sensors:
    - id: io0_button
      name: gpio.0
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-26 11:10 UTC, Links2004 commented
script/build_codeowners.py is not working locally :/

```
$ python3 script/build_codeowners.py
Cannot find component animation. Make sure current path is pip installed ESPHome
```

2024-04-26 21:19 UTC, jesserockz commented on esphome/components/statsd/statsd.cpp
> +void StatsdComponent::update() {
Why not register with `add_on_state_callback` on each (binary)sensor and just send one state live as it is updated?

2024-04-27 06:29 UTC, Links2004 commented on esphome/components/statsd/statsd.cpp
> +void StatsdComponent::update() {
this will easy result in many packets and statsD needs a value each cycle which means we need to send every 10sec any way, with this sending with update result in less UDP packets and less load.

sending only on state change will result in big gabs it the metrics.
this is on of the reasons why I have written this.
my old chain (ESPhome --> Home Assistant --> node RED --> statsD --> graphite --> grafana --> Alerts) resulted in long gabs in the metrics, which I tried to fix with code in node RED at first but its basiclly impossible to handle all cases there (dead esp, node RED restart,...).
as a result I moved to sending the data direct from ESPhome.

2024-04-29 07:29 UTC, Links2004 commented
documentation PR: https://github.com/esphome/esphome-docs/pull/3802

2024-05-04 07:22 UTC, mdop commented
> script/build_codeowners.py is not working locally :/
> 
> ```
> $ python3 script/build_codeowners.py
> Cannot find component animation. Make sure current path is pip installed ESPHome
> ```
> 
> pwd is git root dir.

did you run `script/setup` and `source venv/bin/activate`?

2024-05-04 07:36 UTC, Links2004 commented
yes I did, not sure if its related but I am running Python 3.12.3.

had to do the changes needed by estimating what the changes of the code will be after reding it, not optimal ;) but I got the CI/CD to pass that way.

2024-05-05 22:56 UTC, jesserockz requested changes

2024-05-05 22:56 UTC, jesserockz commented on script/clang-tidy
Please move this to its own PR

2024-05-05 22:56 UTC, jesserockz commented on tests/test11.5.yaml
Please use the new test file structure by making new files in `tests/components/statsd/`

2024-05-05 22:56 UTC, jesserockz commented on esphome/components/statsd/__init__.py
> +).extend(cv.COMPONENT_SCHEMA)
```suggestion
    }
).extend(cv.polling_component_schema("10s"))
```

2024-05-05 22:56 UTC, jesserockz commented on esphome/components/statsd/__init__.py
> +statsdComponent = statsd_component_ns.class_("StatsdComponent", cg.Component)
```suggestion
StatsdComponent = statsd_component_ns.class_("StatsdComponent", cg.PollingComponent)
```

2024-05-05 22:56 UTC, jesserockz commented on esphome/components/statsd/statsd.h
> +  StatsdComponent() : PollingComponent(10000){};
```suggestion
```

2024-05-05 22:56 UTC, jesserockz commented on esphome/components/statsd/statsd.cpp
> +#error ESP8266 does not Support UDP socket
This condition combination will not be satisfied in ESPHome as ESP8266 always uses Arduino

2024-05-05 22:56 UTC, jesserockz commented on esphome/components/statsd/statsd.h
> +#endif
I would prefer this to be for the specific platforms so that esp32 with arduino can still use the internal socket implementation instead of WiFiUDP

2024-05-06 18:36 UTC, Links2004 commented on tests/test11.5.yaml
done

2024-05-06 18:36 UTC, Links2004 commented on esphome/components/statsd/statsd.cpp
> +#error ESP8266 does not Support UDP socket
removed error check

2024-05-06 18:37 UTC, Links2004 commented on esphome/components/statsd/statsd.h
> +#endif
switched to checks for ESP8266

2024-05-06 18:41 UTC, Links2004 commented on script/clang-tidy
done: https://github.com/esphome/esphome/pull/6684

2024-05-06 19:18 UTC, jesserockz commented on esphome/components/statsd/statsd.cpp
> +#ifndef ESP8266
All of our definitions are prefixed with `USE_` in esphome.
```suggestion
#ifndef USE_ESP8266
```

2024-05-06 19:22 UTC, Links2004 commented on esphome/components/statsd/statsd.cpp
> +#ifndef ESP8266
intresting that ESP8266 works too, may from the Arduino framework.

changed.

2024-06-11 09:18 UTC, Links2004 commented
anything i can help with to get this merged?

2024-09-02 22:38 UTC, jesserockz commented on esphome/components/statsd/__init__.py
> +CODEOWNERS = ["@Links2004"]
```suggestion
AUTO_LOAD = ["socket"]
CODEOWNERS = ["@Links2004"]
DEPENDENCIES = ["network"]
```

2024-09-02 22:49 UTC, jesserockz requested changes

2024-09-02 22:49 UTC, jesserockz commented on tests/components/statsD/common.yaml
> +
Should be auto loaded as per above suggestion
```suggestion
```

2024-09-02 22:49 UTC, jesserockz commented on esphome/components/statsd/statsd.cpp
> +float StatsdComponent::get_setup_priority() const { return esphome::setup_priority::BEFORE_CONNECTION; }
```suggestion
float StatsdComponent::get_setup_priority() const { return esphome::setup_priority::AFTER_WIFI; }
```

2024-09-02 23:02 UTC, jesserockz approved these changes

2024-09-05 00:57 UTC, merged