Add OpenTherm component
OttoWinter/esphomeyaml pull request #6645
Opened 2024-04-26 15:15 UTC by olegtarasov

# What does this implement/fix?

This PR adds a new component that allows ESPHome to communicate with OpenTherm devices via a hardware bridge.

OpenTherm (OT) is a standard communications protocol used in central heating systems for the communication between a central heating appliances and a thermostatic controller.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3800

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# An extremely minimal configuration which only enables you to set the boiler's
# water temperature setpoint as a number.

esphome:
  name: thermostat-number-minimal

esp8266:
  board: d1_mini

opentherm:
  in_pin: 21
  out_pin: 26

number:
  - platform: opentherm
    t_set:
      name: "Boiler Control setpoint"

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-05-20 09:22 UTC, olegtarasov commented
@jesserockz Hi! Can you please take a look at this pull request? It adds a new OpenTherm component to control various boilers through a hardware bridge. There is also another open pull request that implements a smaller subset of this functionality: https://github.com/esphome/esphome/pull/3921. I would argue that my PR should be accepted instead, for the following reasons:

1. This implementation uses more robust OpenTherm protocol handling which doesn't rely on measuring elapsed timespans by hand. Instead I use a timer to sample IO levels at regular intervals, so the code is more resistant to low-level protocol fluctuations.
2. This implementation is better structured to diagnose low-level protocol failures. You can debug protocol errors with 1-bit precision, which is not the case with the other PR.
3. Arthur Rump's component, on which this PR is based, supports defining control signals as a `numer`, `output` or as an input sensor, whereas the other PR supports only `number` outputs, requiring additional work to connect them to Climate components. So this implementation leads to cleaner config files.
4. This component generates C++ code dynamically, based on what sensors and controls signals are used in config. If sensors are not used (and most of them are not on account of many boilers not supporting large portions of OpenTherm standard), their corresponding code is not generated.

2024-07-31 23:32 UTC, jesserockz commented
I know literally nothing about OpenTherm myself.

I can only provide a review in terms of ESPHome functionality and code safety/style.

I cannot simply choose one PR over another (apart from saying first in first served), and really need all PR authors to come to a consensus together. The better thing to do would have been to base your work off of the PR that was created first to add extra functionality or at least talk to the author of https://github.com/esphome/esphome/pull/3921 which I see none of.

Please work together with other contributors to make ESPHome better for all.

2024-08-30 02:03 UTC, jesserockz requested changes
Here is *a* review. Not fully done but submitting as I need to go out and didnt want to leave it pending.

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/__init__.py
> +            cv.Optional("sync_mode", False): cv.boolean,
All config items should be using consts for the keys: `CONF_CH_ENABLE`

Maybe even better to use existing consts for the pins, `CONF_TX_PIN` / `CONF_RX_PIN`?

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/hub.h
> +  bool ch_enable = true, dhw_enable = true, cooling_enable = false, otc_active = false, ch2_active = false;
If these values have defaults, they should be in the schema itself so it is visible to users in validation dump.

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/hub.h
> +  OpenTherm *opentherm_;
Since this is only referenced in one place and never shared anywhere else we can safely use a unique ptr here
```suggestion
  std::unique_ptr<OpenTherm> opentherm_;
```

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/hub.cpp
> +  this->opentherm_ = new OpenTherm(this->in_pin_, this->out_pin_);  // NOLINT because hub is never deleted
```suggestion
  this->opentherm_ = make_unique<OpenTherm>(this->in_pin_, this->out_pin_);
```

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/hub.cpp
> +    return;
```suggestion
		this->mark_failed();
    return;
```

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/hub.cpp
> +  initialized_ = true;
With `this->mark_failed()` setting a boolean is not required.
```suggestion
```

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/hub.cpp
> +
```suggestion
```

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/hub.h
> +  bool initialized_ = false;
```suggestion
```

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/hub.cpp
> +    sync_loop_();
Please make sure **all** member variables and function calls have `this->` prefixed.
```suggestion
  if (this->sync_mode_) {
    this->sync_loop_();
```

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/opentherm.h
> +#define OT_TAG "opentherm"
For consistency across ESPHome, please use `static const char *const TAG` in the c++ files

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/opentherm.h
> +#define writeBit(value, bit, bitvalue) ((bitvalue) ? setBit(value, bit) : clearBit(value, bit))
Please make these regular `constexpr` functions in the c++ file.

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/opentherm.h
> +}
`helpers.h` has an existing `format_hex` function to do this too.
Less duplication is better where possible =)

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/hub.cpp
> +#ifdef OPENTHERM_READ_ch_enable
Where do these come from exactly? I don't see them being optionally set even...

2024-08-30 02:03 UTC, jesserockz commented on esphome/components/opentherm/hub.cpp
> +#pragma GCC diagnostic ignored "-Wswitch"
Which switch does this apply to? I would prefer not to disable rules, but if it does need to be done, it should only be done around the smallest amount of code possible please.

2024-09-02 07:29 UTC, olegtarasov commented on esphome/components/opentherm/__init__.py
> +            cv.Optional("sync_mode", False): cv.boolean,
Extracted strings into constants. As for renaming config items for pins, I would rather leave “IN” and “OUT” as they are, since most adapter boards call them this way. If we call them TX and RX, it might create additional confusion for users.

2024-09-02 07:30 UTC, olegtarasov commented on esphome/components/opentherm/hub.h
> +  bool ch_enable = true, dhw_enable = true, cooling_enable = false, otc_active = false, ch2_active = false;
They already do have the same defaults in the schema:

```python
cv.Optional(CONF_CH_ENABLE, True): cv.boolean,
cv.Optional(CONF_DHW_ENABLE, True): cv.boolean,
cv.Optional(CONF_COOLING_ENABLE, False): cv.boolean,
cv.Optional(CONF_OTC_ACCTIVE, False): cv.boolean,
cv.Optional(CONF_CH2_ACTIVE, False): cv.boolean,
cv.Optional(CONF_SYNC_MODE, False): cv.boolean
```

2024-09-02 07:30 UTC, olegtarasov commented on esphome/components/opentherm/hub.h
> +  OpenTherm *opentherm_;
Done.

2024-09-02 07:30 UTC, olegtarasov commented on esphome/components/opentherm/hub.cpp
> +    sync_loop_();
Done.

2024-09-02 07:31 UTC, olegtarasov commented on esphome/components/opentherm/opentherm.h
> +#define OT_TAG "opentherm"
Done.

2024-09-02 07:31 UTC, olegtarasov commented on esphome/components/opentherm/opentherm.h
> +#define writeBit(value, bit, bitvalue) ((bitvalue) ? setBit(value, bit) : clearBit(value, bit))
Done, but placed them into `opentherm.h`, since they will be reused in `hub.cpp` when we implement sensors.

2024-09-02 07:32 UTC, olegtarasov commented on esphome/components/opentherm/opentherm.h
> +}
Done.

2024-09-02 07:33 UTC, olegtarasov commented on esphome/components/opentherm/hub.cpp
> +#ifdef OPENTHERM_READ_ch_enable
These defines are generated from Python, and I've excluded that code from this batch — that's why you didn't find it. I removed these conditions for now, and will bring them back when we move to implement sensors.

2024-09-02 07:35 UTC, olegtarasov commented on esphome/components/opentherm/hub.cpp
> +#pragma GCC diagnostic ignored "-Wswitch"
This also applies to an auto-generated switch statement which handles sensor requests. I've moved the pragmas more closely to the actual place where that statement will live.

2024-09-05 05:15 UTC, jesserockz commented on esphome/components/opentherm/hub.cpp
> +    this->last_conversation_end_ = millis();
```suggestion
    this->stop_opentherm_();
```

2024-09-05 05:27 UTC, jesserockz requested changes
I think only 1 thing below stood out to me, otherwise good to go. 
I will probably merge this after the beta is cut in 6-7 days and then we have the full cycle to get further PRs in so this one isnt released by itself.

2024-09-05 05:27 UTC, jesserockz commented on esphome/components/opentherm/hub.cpp
> +  ESP_LOGCONFIG(TAG, "  Out: GPIO%d", this->out_pin_->get_pin());
```suggestion
  LOG_PIN("  In: ", this->in_pin_);
  LOG_PIN("  Out: ", this->out_pin_);
```

2024-09-05 05:27 UTC, jesserockz commented on esphome/components/opentherm/hub.h
> +  bool ch_enable = true, dhw_enable = true, cooling_enable = false, otc_active = false, ch2_active = false;
Somehow I missed that..haha

2024-09-06 09:24 UTC, olegtarasov commented
@jesserockz That's great to hear, thank you for the review! Meanwhile, I will start preparing the sensors part.

2024-09-11 05:17 UTC, jesserockz approved these changes

2024-09-15 21:59 UTC, merged