Add thermocouple type, autoconversion, and averaging to max31856
OttoWinter/esphomeyaml pull request #6659
Opened 2024-04-29 22:38 UTC by fhriley

# What does this implement/fix?

It adds thermocouple type, autoconversion, and averaging to the max31856 sensor while maintaining backwards compatibility with polling mode if the `data_ready_pin` is not specified.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3803

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: max31856
    id: temperature_1
    name: "Temperature 1"
    cs_pin: GPIO12
    data_ready_pin: GPIO13
    type: K
    samples_per_value: 16
  - platform: max31856
    id: temperature_2
    name: "Temperature 2"
    cs_pin: GPIO33
    type: T
    samples_per_value: 2
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-04-30 20:17 UTC, jesserockz requested changes
Please add tests for the new configurations

2024-04-30 20:17 UTC, jesserockz commented on esphome/components/max31856/max31856.cpp
> +  ESP_LOGVV(TAG, "Setting up MAX31856Sensor '%s'...", this->name_.c_str());
Why did you change this? These should be LOGCONFIG

2024-04-30 20:17 UTC, jesserockz commented on esphome/components/max31856/sensor.py
> -    .extend(cv.polling_component_schema("60s"))
This should extend cv.COMPONENT_SCHEMA instead then

2024-04-30 20:17 UTC, jesserockz commented on esphome/components/max31856/sensor.py
> +            ),
Sensors should not have binary sensors as children configuration. They should be in their own `binary_sensor.py` file which can link back to the parent.

2024-04-30 20:17 UTC, jesserockz commented on esphome/components/max31856/sensor.py
> +exclusive_update_interval_with_default.default = lambda: "60s"
This is still setting the default update interval to 60s. You can use regular Exclusive and a custom overall validation to add default values for this. 

Then, this component should no longer inherit from PollingComponent, but set its own update `interval` in setup if the time is set but the pin is not.

There are other components that set their own update interval you can reference (I cannot remember them though)

2024-05-02 01:49 UTC, fhriley commented
I've already spent too much time on this, and I don't have time to go searching the codebase to figure out how to make a bunch of changes here, unfortunately. You can close this, and I'll just use it from my own repo.

2025-10-15 00:50 UTC, closed without merging