Minor tidy up of BME280 code
OttoWinter/esphomeyaml pull request #6672
Opened 2024-05-02 22:56 UTC by latonita

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-05-03 04:10 UTC, jesserockz commented on esphome/components/bme280_i2c/sensor.py
> +CODEOWNERS = ["@esphome/core"]
`@esphome/core` is not a "default" codeowner, its only added to a component if a core team member has added it. 
```suggestion
```

2024-05-05 22:40 UTC, jesserockz commented on esphome/components/bme280_spi/sensor.py
> +from ..bme280_base import to_code_base, cv, CONFIG_SCHEMA_BASE
I never saw this before, but since you are making changes, can you change to import `cv` "correctly" instead of from another module?

2024-05-05 22:42 UTC, jesserockz requested changes

2024-05-05 22:42 UTC, jesserockz commented on esphome/components/bme280_base/__init__.py
Did you forget to commit the deleted `sensor.py` file?

2024-05-05 23:39 UTC, latonita commented on esphome/components/bme280_spi/sensor.py
> +from ..bme280_base import to_code_base, cv, CONFIG_SCHEMA_BASE
n.p. 
done

2024-05-06 02:19 UTC, jesserockz approved these changes

2024-05-06 02:19 UTC, merged