Added HDC2010 component
OttoWinter/esphomeyaml pull request #6674
Opened 2024-05-03 19:32 UTC by optimusprimespace

# What does this implement/fix?

Description:

This PR introduces a new temperature and humidity sensor to our system. The sensor, HDC2010 from Texas Instruments, provides accurate and reliable readings, enhancing our environmental monitoring capabilities.

Key Features for the sensor:

- High precision temperature and humidity measurements.
- Wide operating range suitable for various environments.
- Low power consumption for extended use.
- Easy integration with existing systems aka. HDC1080

PS: I need some help with the code, and testing, this is only a draft as of now.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: hdc2010
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-26 13:22 UTC, optimusprimespace commented
The doc is on https://github.com/esphome/esphome-docs/pull/3872, but i don't know how to link it here.

2024-06-28 10:54 UTC, optimusprimespace commented
![hdc2010homeassistant](https://github.com/esphome/esphome/assets/62800678/da76805f-dc9e-4c74-9d75-8b440a397d27)
It's been working for the past month or two without any problem in HA. I would encourage anyone who has the sensor to try it.

2024-07-22 21:25 UTC, optimusprimespace commented
@jesserockz @ssieb Can you review the code?

2024-10-06 23:13 UTC, jesserockz requested changes

2024-10-06 23:13 UTC, jesserockz commented on esphome/components/hdc2010/sensor.py
> +    #     cg.add(var.set_heater(conf[CONF_TEMPERATURE], conf[CONF_DURATION]))
No commented out code allowed
```suggestion
```

2024-10-06 23:13 UTC, jesserockz commented on esphome/components/hdc2010/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_TEMPERATURE])
```suggestion
    if temperature_config := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_config)
```

2024-10-06 23:13 UTC, jesserockz commented on esphome/components/hdc2010/sensor.py
> +    # CONF_HEATER,
```suggestion
```

2024-10-06 23:13 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.h
> +  void set_temperature(sensor::Sensor *temperature) { temperature_ = temperature; }
Please go over the PR and ensure all calls to member variables and functions are prefixed with `this->`

```suggestion
  void set_temperature_sensor(sensor::Sensor *temperature) { this->temperature_sensor_ = temperature; }
```

2024-10-06 23:13 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.cpp
> +  ESP_LOGD(TAG, "Got temperature=%.1f°C humidity=%.1f%%", temp, humidity);
```suggestion
  if(this->temperature_sensor_ != nullptr) {
    float temp = this->read_temp();
    this->temperature_->publish_state(temp);
    ESP_LOGD(TAG, "Got temperature=%.1f°C", temp);
  }
  
  if(this->humidity_sensor_ != nullptr) {
    float humidity = this->read_humidity();
    this->humidity_->publish_state(humidity);
    ESP_LOGD(TAG, "Got humidity=%.1f%%", humidity);
  }
```

2024-10-06 23:13 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.h
> +  sensor::Sensor *humidity_{nullptr};
```suggestion
  sensor::Sensor *temperature_sensor_{nullptr};
  sensor::Sensor *humidity_sensor_{nullptr};
```

2024-10-06 23:13 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.h
> +  void set_humidity(sensor::Sensor *humidity) { humidity_ = humidity; }
```suggestion
  void set_humidity_sensor(sensor::Sensor *humidity) { this->humidity_sensor_ = humidity; }
```

2024-10-06 23:13 UTC, jesserockz commented on esphome/components/hdc2010/sensor.py
> +        cg.add(var.set_temperature(sens))
```suggestion
        cg.add(var.set_temperature_sensor(sens))
```

2024-10-06 23:13 UTC, jesserockz commented on esphome/components/hdc2010/sensor.py
> +        cg.add(var.set_humidity(sens))
```suggestion
    if humidity_config := config.get(CONF_HUMIDITY):
        sens = await sensor.new_sensor(humidity_config)
        cg.add(var.set_humidity_sensor(sens))
```

2024-10-07 18:59 UTC, optimusprimespace commented
@jesserockz I have done all the necessary modifications you've requested.

2025-01-08 20:24 UTC, optimusprimespace commented
@jesserockz Can you merge this PR to the beta channel at least? It's been running flawlessly ever since for me. I know there are currently 396 open PR, but it would be nice to have this new sensor integrated into ESPHome.

2025-06-29 16:58 UTC, optimusprimespace commented
@ssieb, @swoboda1337, @jesserocks. I think we're all on the same page here that this PR is looking great. Let's go ahead and get it merged. I've been running the component on my end on a ESP32 for over a year now. I've fixed the documentation too today.

2025-07-01 04:29 UTC, kbx81 submitted a review, later dismissed
Couple nitpicks, mostly just needs test deduplication.

2025-07-01 04:29 UTC, kbx81 commented on esphome/components/hdc2010/hdc2010.cpp
> +  ESP_LOGCONFIG(TAG, "Setting up HDC2010...");
We are using this standard string here shared among all components/platforms now. It's more memory efficient.
```suggestion
  ESP_LOGCONFIG(TAG, "Running setup");
```

2025-07-01 04:29 UTC, kbx81 commented on esphome/components/hdc2010/hdc2010.cpp
> +    ESP_LOGW(TAG, "HDC2010 initial config instruction error");
[Do not use the component name in log messages](https://developers.esphome.io/architecture/logging/#minimizing-impact) -- that's what `TAG` is for.
```suggestion
    ESP_LOGW(TAG, "Initial config instruction error");
```

2025-07-01 04:29 UTC, kbx81 commented on esphome/components/hdc2010/hdc2010.cpp
> +    ESP_LOGE(TAG, "Communication with HDC2010 failed!");
As above. We also have a macro for this  particular condition now:
```suggestion
    ESP_LOGE(TAG, ESP_LOG_MSG_COMM_FAIL);
```

2025-07-01 04:29 UTC, kbx81 commented on esphome/components/hdc2010/hdc2010.cpp
> +float HDC2010Component::get_setup_priority() const { return setup_priority::DATA; }
This is the default value, so no need to override
```suggestion
```

2025-07-01 04:29 UTC, kbx81 commented on esphome/components/hdc2010/hdc2010.h
> +
```suggestion
```

2025-07-01 04:29 UTC, kbx81 commented on tests/components/hdc2010/test.esp32-ard.yaml
Please de-duplicate the tests with a `common.yaml` file as done in most other components.

2025-07-01 04:41 UTC, kbx81 commented
I've added back the `needs-docs` label as this will need a new PR in [esphome-docs](https://github.com/esphome/esphome-docs) as the old one was closed & branch deleted.

2025-07-01 16:20 UTC, optimusprimespace commented
Thanks for making these changes. Also added the documentation to the docs. I think now it's ready for merge.

2025-07-01 21:39 UTC, jesserockz submitted a review, later dismissed

2025-07-01 21:39 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.cpp
> +  delayMicroseconds(5000);  // wait for 5ms
The chances of update being called within 5ms is extremely improbable
```suggestion
```

2025-07-01 21:39 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.cpp
> +  uint16_t temp;
```suggestion
```

2025-07-01 21:39 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.cpp
> +  temp = (unsigned int) byte[1] << 8 | byte[0];
```suggestion
  uint6_t temp = encode_uint16(byte[1], byte[0]);
```

2025-07-01 21:39 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.cpp
> +#include "esphome/core/log.h"
```suggestion
#include "esphome/core/log.h"
#include "esphome/core/helpers.h"
```

2025-07-01 21:39 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.cpp
> +  uint16_t humidity;
```suggestion
```

2025-07-01 21:39 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.cpp
> +  humidity = (unsigned int) byte[1] << 8 | byte[0];
```suggestion
  uint16_t humidity = encode_uint16(byte[1], byte[0]);
```

2025-07-01 21:39 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.cpp
> +  this->read_register(HDC2010_CMD_HUMIDITY_HIGH, &byte[1], 1);
**OPTIONAL**
Does this work?
```suggestion
  this->read_register(HDC2010_CMD_HUMIDITY_LOW, byte, 2);
```

2025-07-01 22:18 UTC, kbx81 commented on tests/components/hdc2010/test.esp32-s3-ard.yaml
There's no benefit to having tests for the S3 specifically since the same code is being compiled for it and for the original ESP32, which you already have tests for. Please remove this and the S3 IDF test, too.

2025-07-03 11:39 UTC, optimusprimespace commented on esphome/components/hdc2010/hdc2010.cpp
> +  this->read_register(HDC2010_CMD_HUMIDITY_HIGH, &byte[1], 1);
Does this work as intended? I use the HDC2010_CMD_TEMPERATURE_LOW and HDC2010_CMD_TEMPERATURE_HIGH for this purpose too. It's mentioned in the datasheet.

2025-07-03 11:42 UTC, optimusprimespace commented on esphome/components/hdc2010/hdc2010.cpp
> +  temp = (unsigned int) byte[1] << 8 | byte[0];
Here did you mean uint16_t temp?

2025-07-03 14:05 UTC, optimusprimespace commented
I have tested the new humidity read function and here are the results. Now it's only reading the humidity low according to the diagram. The sampling time is set to 30s inside config. Is this OK or do i need to revert it?
![hdc2010hum](https://github.com/user-attachments/assets/eca86d78-e3a3-4cd5-8059-5887e58b9fe0)

2025-07-03 17:36 UTC, optimusprimespace commented
I have now reverted to the old code without merging the humidity function into one `this->read_register(HDC2010_CMD_HUMIDITY_LOW, byte, 2);`. 
The spikes are present either way, and don't know why. Maybe due to the heater of the CCS811 component on the board turning on and off...
![hdc2010hum](https://github.com/user-attachments/assets/d03fd3e7-4be9-4387-9c98-58d7eb850092)

2025-07-04 01:01 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.cpp
> +  temp = (unsigned int) byte[1] << 8 | byte[0];
Haha, yes just a typo

2025-07-04 01:02 UTC, jesserockz commented on esphome/components/hdc2010/hdc2010.cpp
> +  this->read_register(HDC2010_CMD_HUMIDITY_HIGH, &byte[1], 1);
That's why I said optional and asked if it works... =)
I'm pretty sure you can read multiple in a row like this, please test with the sensor itself.

2025-07-10 16:23 UTC, optimusprimespace commented on esphome/components/hdc2010/hdc2010.cpp
> +  this->read_register(HDC2010_CMD_HUMIDITY_HIGH, &byte[1], 1);
I've tested it and i think it's better to keep it the way it was (I've posted some pictures about why i think it's better). If you want to merge it with the suggested modifications it's still OK from my part. 💯

2025-07-11 23:18 UTC, kbx81 commented on esphome/components/hdc2010/hdc2010.cpp
> +    ESP_LOGD(TAG, "Got temperature=%.1f°C", temp);
```suggestion
    ESP_LOGV(TAG, "Temperature=%.1f°C", temp);
```

2025-07-11 23:19 UTC, kbx81 commented
@optimusprimespace could those spikes be related to a polling interval that's too aggressive?...or maybe reading too quickly after requesting the read? If you haven't already, I'd experiment with that interval and see how it impacts those spikes.

2025-07-11 23:23 UTC, kbx81 commented on esphome/components/hdc2010/hdc2010.cpp
> +  delayMicroseconds(1000);  // 1ms delay after triggering the sample
Related to my last comment, see what happens if you double or even triple this duration. I'd experiment with values up to 10 ms.

```suggestion
  delayMicroseconds(2000);  // 2 ms delay after triggering the sample
```

2025-08-07 20:11 UTC, optimusprimespace commented on esphome/components/hdc2010/hdc2010.cpp
> +  delayMicroseconds(1000);  // 1ms delay after triggering the sample
Hi, sorry for late reply, but the spike are only visible in HA, and not in Grafana. TL;DR: HA interprets noisy data as spikes.

2025-10-21 13:25 UTC, swoboda1337 requested changes

2025-10-21 13:25 UTC, swoboda1337 commented on esphome/components/hdc2010/hdc2010.cpp
> +  }
```suggestion
  // 1ms delay after triggering the sample
  set_timeout(1, [this]() {
    if (this->temperature_sensor_ != nullptr) {
      float temp = this->read_temp();
      this->temperature_sensor_->publish_state(temp);
      ESP_LOGV(TAG, "Temperature=%.1f°C", temp);
    }
  
    if (this->humidity_sensor_ != nullptr) {
      float humidity = this->read_humidity();
      this->humidity_sensor_->publish_state(humidity);
      ESP_LOGD(TAG, "Got humidity=%.1f%%", humidity);
    }
  }
```

2025-10-21 13:25 UTC, swoboda1337 commented on tests/components/hdc2010/common.yaml
> +    update_interval: 15s
Tests need to be updated to the new format. See other i2c tests: https://github.com/esphome/esphome/tree/dev/tests/components/am2315c

2025-10-21 13:26 UTC, swoboda1337 commented on esphome/components/hdc2010/hdc2010.cpp
> +  }
Better to use a non-blocking delay if you can.

2025-10-21 18:03 UTC, swoboda1337 submitted a review, later dismissed
Looks good to me.

2025-10-21 18:42 UTC, swoboda1337 commented on esphome/components/hdc2010/hdc2010.cpp
> +      ESP_LOGD(TAG, "Humidity=%.1f%%", humidity);
Why is one log verbose and the other debug?

2025-10-22 17:25 UTC, swoboda1337 requested changes
Docs PR needs to be recreated. You created it directly on your fork of next and I didn't realize that and the PR got messed up. Could create a new one, hopefully on a separate branch? Sorry about that.

2025-10-23 02:23 UTC, swoboda1337 approved these changes

2025-10-23 02:24 UTC, merged