Add new component mcp3426 7 8
OttoWinter/esphomeyaml pull request #6675
Opened 2024-05-03 19:39 UTC by mdop

# What does this implement/fix?

Adds support for the 4 channel 16 bit ADC chips of the MCP3426/7/8 family.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes -

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
mcp3428:
  address: 0b1101000

sensor:
  - platform: mcp3428
    name: "Channel 1"
    multiplexer: 1
    resolution: 12
    gain: 8
    id: mcp3428_sensor1

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-04 23:03 UTC, jesserockz requested changes

2024-07-04 23:03 UTC, jesserockz commented on esphome/components/mcp3428/__init__.py
> +    .extend(i2c.i2c_device_schema(None))
Devices with address pins still have a default address if the pins are left floating.
```suggestion
    .extend(i2c.i2c_device_schema(0x58))
```

2024-07-04 23:03 UTC, jesserockz commented on esphome/components/mcp3428/sensor/__init__.py
> +    await sensor.register_sensor(var, config)
```suggestion
    var = await sensor.new_sensor(config)
```

2024-07-04 23:03 UTC, jesserockz commented on esphome/components/mcp3428/mcp3428.cpp
> +    this->mark_failed();
Please put useful error messages here so users can look back at logs and see **why** it failed.

2024-07-04 23:03 UTC, jesserockz commented on esphome/components/mcp3428/mcp3428.cpp
> +    this->mark_failed();
Same here

2024-07-04 23:03 UTC, jesserockz commented on esphome/components/mcp3428/mcp3428.cpp
> +  single_measurement_active_ = false;
Please make sure to always prefix member variables and functions with `this->`
```suggestion
  this->single_measurement_active_ = false;
```

2024-07-04 23:03 UTC, jesserockz commented on esphome/components/mcp3428/mcp3428.cpp
> +float MCP3428Component::convert_anwser_to_voltage_(uint8_t const *anwser) {
```suggestion
float MCP3428Component::convert_answer_to_voltage_(uint8_t const *answer) {
```

2024-07-04 23:03 UTC, jesserockz commented on esphome/components/mcp3428/mcp3428.cpp
> +      timeout_wait = 1000;
I dont see the point in setting this to an arbitrary high number since it should not be used when false is returned.
```suggestion
```

2024-07-04 23:03 UTC, jesserockz commented on esphome/components/mcp3428/sensor/mcp3428_sensor.cpp
> +  ESP_LOGCONFIG(TAG, "    Resolution: %u", this->resolution_);
These should be converted back to the human friendly values that were entered in yaml

2024-07-04 23:03 UTC, jesserockz commented on tests/components/MCP3428/test.esp32-c3-idf.yaml
> +  address: 0b1101000
Please use hex here to keep consistent with all other i2c examples.
```suggestion
  address: 0x68
```

2024-07-07 11:23 UTC, mdop commented on esphome/components/mcp3428/mcp3428.cpp
> +    this->mark_failed();
Added context that communication failed

2024-07-07 11:27 UTC, mdop commented on esphome/components/mcp3428/mcp3428.cpp
> +      timeout_wait = 1000;
Indeed, not sure what I was thinking.

2024-07-07 11:46 UTC, mdop commented on esphome/components/mcp3428/__init__.py
> +    .extend(i2c.i2c_device_schema(None))
Ok, but left floating the address is 0x68, like with grounded pins. Addressed it in a separate commit.

2024-07-07 12:01 UTC, mdop commented on esphome/components/mcp3428/sensor/mcp3428_sensor.cpp
> +  ESP_LOGCONFIG(TAG, "    Resolution: %u", this->resolution_);
Seems like I forgot to change this when I changed the numerical values of the enums. Fixed in a commit.

2024-07-07 13:46 UTC, mdop commented
Not sure why `CI / Component test MCP3428 (pull_request)` failed, the file `./tests/test_build_components/build_components_base.esp8266.yaml` does exist

2025-01-13 22:57 UTC, lcrockett commented
Hello, I was just wondering if there's any love planned for this PR. We have a few use cases for ESP32 + NCD 4-20mA current receiver boards (https://store.ncd.io/product/8-channel-i2c-4-20ma-current-receiver-with-i2c-interface/). It uses a MCP3428 ADC.

2025-01-16 21:46 UTC, mdop commented
> Hello, I was just wondering if there's any love planned for this PR. We have a few use cases for ESP32 + NCD 4-20mA current receiver boards (https://store.ncd.io/product/8-channel-i2c-4-20ma-current-receiver-with-i2c-interface/). It uses a MCP3428 ADC.

I'll have a look at the test issues on the weekend. You can already use the component as an external component, though. Just add this to your yaml file:
```
external_components:
  source:
    type: git
    url: https://github.com/mdop/esphome/
    ref: add-MCP3426-7-8
  components: [mcp3428]
  refresh: 300s
```

2025-03-29 15:47 UTC, lcrockett commented
@mdop I've hooked up a test setup and am trying out a few configurations. See 'https://pastecode.io/s/nd9joi03' for relevant configuration details.

Based on the receiver board (hooked up with a esp32-wroom-32d) description (https://store.ncd.io/product/mcp3428-8-channel-4-20ma-16-bit-current-receiver-with-iot-interface/) I should be seeing raw ADC values of between 5813-29390.

It appears that this component reports voltage initially ? What i'm unsure about at this point is if I need configuration changes to achieve the readings I want (ADC / mA), or if this is not possible with the hardware i'm using.

See current ESPHome logging at 'https://pastecode.io/s/uovf9tkg'.
- `MCP3428 #68-1` is a 5m submersible depth sensor currently hanging at about 3.5m of depth (very rough estimate)
- `MCP3428 #6e-1` is a pressure sensor 0-10 bar just sitting open
Both sensors are 24v powered and output 4-20mA signals

2025-03-30 14:14 UTC, mdop commented
ADCs measure voltage, so that is what the sensor reports. Internal codes are abstracted away to make work easier for the user, but it is a calculated value after all. The reference voltage is 2.048V and is divided into 2¹⁵ ticks in 16bit mode, ie. 62.5µV per tick (internally). With the recommended gain of 2 we get 31.25µV per tick (external voltage). A code of 29390 for 20mA is therefore equivalent to 0.9184V. That would be a 45.9 Ohm sensing resistor, which is a weird value because it doesn't appear in the E96 series. Probably best to check/calibrate the sensing circuit yourself.

2025-03-30 14:28 UTC, mdop commented
@lcrockett The component is an ADC which measures a voltage, so that is what it is reporting. It abstracts away all the internal conversions necessary to get the voltage. The product page specifies a code of 29390 at 16 bit resolution and a gain of 2 at 20mA. The code is equivalent to 0.9184375V, or 45.922 V/mA=Ohm. It's a strange sensing resistance value as it doesn't appear in the E96 series, so you may want to check/calibrate the sensing circuit.

2025-03-31 14:05 UTC, lcrockett commented
@mdop Thank you for the clarification. I'm going to have to read up more on ADCs working and determine if i'm able to check the sensing circuit.

For now, i've modified your [code](https://github.com/lcrockett/esphome-components-mcp3428) to report only raw ADC values instead of voltage. I can use that to calibrate and report the units I want (bar / CM). The raw ADC readings seem to be very stable relative to the voltage readings (without filters delta).

Your code in this PR does however work as intended with my DAQ circuit, so it's functional and passes usability tests. Thanks again.

2025-10-15 00:50 UTC, closed without merging