Apds9306
OttoWinter/esphomeyaml pull request #6709
Opened 2024-05-09 06:42 UTC by aodrenah

# What does this implement/fix?

Adds support for the APDS9306 ambient light sensor.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3826

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: apds9306
    name: "APDS9306 Light Level" # below are optional
    gain: 1
    bit_width: 18
    measurement_rate: 100ms
    update_interval: 60s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-05-13 21:57 UTC, jesserockz requested changes

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/apds9306.cpp
> +  if (!this->read_byte(0x06, &id)) {  // Part ID register
Please move all of the register addresses to named constants or enums at the top of this file.

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/apds9306.cpp
> +  switch (gain_) {
```suggestion
  switch (this->gain_) {
```

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/apds9306.cpp
> +  switch (measurement_rate_) {
```suggestion
  switch (this->measurement_rate_) {
```

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/apds9306.cpp
> +  switch (bit_width_) {
```suggestion
  switch (this->bit_width_) {
```

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/apds9306.cpp
> +  uint32_t light_level = 0x0000 | ((als_data[0]) + (als_data[1] << 8) + (als_data[2] << 16));
This is available with `#include "esphome/core/helpers.h"`
```suggestion
  uint32_t light_level = encode_uint24(als_data[2], als_data[1], als_data[0]);
```

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/apds9306.cpp
> +  float lux = ((float) light_level / gain_val_) * (100.0f / rate_val_);
```suggestion
  float lux = ((float) light_level / this->gain_val_) * (100.0f / this->rate_val_);
```

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/sensor.py
> +}
```suggestion
MEASUREMENT_BIT_WIDTHS = {
    20: 0,
    19: 1,
    18: 2,
    17: 3,
    16: 4,
    13: 5,
}
```

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/sensor.py
> +}
```suggestion
AMBIENT_LIGHT_GAINS = {
    1: 0,
    3: 1,
    6: 2,
    9: 3,
    18: 4,
}
```

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/sensor.py
> +                AMBIENT_LIGHT_GAINS, lower=True
```suggestion
                AMBIENT_LIGHT_GAINS, int=True
```

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/sensor.py
> +}
```suggestion
MEASUREMENT_RATES = {
    25: 0,
    50: 1,
    100: 2,
    200: 3,
    500: 4,
    1000: 5,
}
```

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/sensor.py
> +                MEASUREMENT_BIT_WIDTHS, lower=True
```suggestion
                MEASUREMENT_BIT_WIDTHS, int=True
```

2024-05-13 21:57 UTC, jesserockz commented on esphome/components/apds9306/sensor.py
> +            ),
```suggestion
            cv.Optional(CONF_MEASUREMENT_RATE, default="100ms"): cv.All(
                cv.positive_time_period_milliseconds, 
                cv.enum(MEASUREMENT_RATES, int=True),
            ),
```

2024-05-23 08:07 UTC, kbx81 submitted a review, later dismissed

2024-05-23 08:07 UTC, kbx81 commented on esphome/components/apds9306/sensor.py
> +    UNIT_LUX,
```suggestion
    CONF_GAIN,
    DEVICE_CLASS_ILLUMINANCE,
    ICON_LIGHTBULB,
    STATE_CLASS_MEASUREMENT,
    UNIT_LUX,
```

2024-05-23 08:07 UTC, kbx81 commented on tests/components/apds9306/test.esp32-c3-idf.yaml
Please consolidate the test files using a `common.yaml` file with substitutions for the pins. [Example](https://github.com/esphome/esphome/tree/dev/tests/components/ade7880)

2024-05-23 13:29 UTC, aodrenah commented
If you see this and I haven't commented again, please ignore this pull request for now. Since I started making changes I think I broke something  because the sensor always gets marked as failed when I test.

2024-05-24 02:24 UTC, kbx81 commented
No worries, just remember to mark as "ready" once you've fixed things up. 😄

2024-06-10 19:00 UTC, aodrenah commented
It works again, I was using read_byte instead of read_bytes and I was resetting the device necessarily.

2024-06-12 02:06 UTC, jesserockz requested changes

2024-06-12 02:06 UTC, jesserockz commented on esphome/components/apds9306/apds9306.cpp
> +    case 0:
Please define and use actual enum types for all of these

2024-06-15 05:19 UTC, aodrenah commented on esphome/components/apds9306/apds9306.cpp
> +    case 0:
I switched to using an array, is this OK or did you want me to declare constants and use those inside the switch statement like I did with the registers? I'm not sure what you mean by use actual enum types.

2024-07-03 05:24 UTC, jesserockz commented
@aodrenah I have pushed some commits to change to `enum` types where applicable.

2024-07-22 04:58 UTC, jesserockz approved these changes

2024-07-22 05:29 UTC, merged