fix: Growatt solar, prevent invalid readouts during boot cycle
OttoWinter/esphomeyaml pull request #6724
Opened 2024-05-11 22:11 UTC by rfpronk

# What does this implement/fix?

Early morning when first light hits the solar panels the inverter boots up and powers the USB port on which the ESPhome device is powered.
The first readouts can be invalid, giving either invalid values or values from the previous day, which is annoying when counting energy production per day. (this ruins home assistant energy dashboard graphs).
This PR gives the inverter a bit time (30s) to complete it's boot cycle before ESPHome will pay attention to the data values it will be sending.

I wrote this fix in the evening, but I can't this in the evening. Compilation works and tomorrow when the sun shines again I will flash this branch and let it run for a couple of days to see if the spikes are gone.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes  esphome/issues/issues/3965

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
Example will do the trick, https://esphome.io/components/sensor/growatt_solar.html

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-05-12 23:15 UTC, jesserockz requested changes
This should be a user configurable config of duration that defaults to `0s` (to no break existing configs).

This user provided time should then just be checked inside `update` and just do a `return` if its less than the time, preventing it from ever sending any data requests.

2024-05-13 12:43 UTC, rfpronk commented
Thanks for your review.

> This should be a user configurable config of duration that defaults to 0s (to no break existing configs).

This only happens after startup (when the inverter comes online) and when flashing a new esphome (and thus restart). It will only take a bit longer for the first reading to be available. imho it doesn't break existing config and a user configurable value might work confusing. Would you still prefer a user configurable setting?  I'm just curious to your thoughts here.

> This user provided time should then just be checked inside update and just do a return if its less than the time, preventing it from ever sending any data requests.

Good point, I will change this soon

This morning it worked fine on my unit, the invalid spike in readout was gone so the idea does the trick on the initial issue 👍

2024-05-13 19:07 UTC, jesserockz requested changes
Looks better =)
Just a few minor things below

2024-05-13 19:07 UTC, jesserockz commented on esphome/components/growatt_solar/sensor.py
> +            cv.Optional(CONF_WARM_UP_TIME, default=0): cv.uint8_t,
```suggestion
            cv.Optional(CONF_WARM_UP_TIME, default="0s"): cv.All(cv.positive_time_period_seconds, cv.uint8_t),
```

2024-05-13 19:07 UTC, jesserockz commented on esphome/components/growatt_solar/sensor.py
> +        cg.add(var.set_warm_up_time(int(config[CONF_WARM_UP_TIME])))
There is a default of 0 so it is always there
```suggestion
    cg.add(var.set_warm_up_time(int(config[CONF_WARM_UP_TIME])))
```

2024-05-14 07:04 UTC, rfpronk commented on esphome/components/growatt_solar/sensor.py
> +        cg.add(var.set_warm_up_time(int(config[CONF_WARM_UP_TIME])))
ah okay I misunderstood it then, I thought `config` would only be the config text blob without the defaults.

2024-05-14 07:08 UTC, rfpronk commented on esphome/components/growatt_solar/sensor.py
> +            cv.Optional(CONF_WARM_UP_TIME, default=0): cv.uint8_t,
Sorry for asking, but setting a string as default for an int would cause an issue right? Or does the `Optional` function convert/cast that? The `int()` cast  on line 169 will error on `"0s"` but can handle `"0"`

2024-06-05 06:11 UTC, ssieb commented
Are you aware of this filter?  https://esphome.io/components/sensor/#skip-initial

2024-10-03 19:34 UTC, rfpronk commented
I was not, thanks for that!
Much simpler solution indeed. 
Will flash this change tomorrow to my unit when the sun shines again and powers the unit

```diff
     energy_production_day:
       name: "Growatt Today's Generation"
       icon: "mdi:solar-power-variant"
+      filters:
+      - skip_initial: 3
     total_energy_production:
       name: "Growatt Total Energy Production"
       icon: "mdi:solar-power-variant"
+      filters:
+      - skip_initial: 3
```

2024-10-03 19:34 UTC, closed without merging