[io_bus] Add i80 parallel bus and parent
OttoWinter/esphomeyaml pull request #6787
Opened 2024-05-21 02:16 UTC by clydebarrow

# What does this implement/fix?

## Types of changes

Add a new bus parallel type - `i80` - used for interfacing  LCD display controllers. This is used in a similar way to the `spi` component, and will be utilised by the `ili9xxx` display driver, enabling support for the Seeed [W32-SC01-Plus](https://www.seeedstudio.com/WT32-3-5-Inch-Display-p-5542.html) and the [LilyGo T-Display S3](https://www.lilygo.cc/products/t-display-s3?variant=42589373268149).

The changes have been tested on the above as well as numerous SPI interfaced displays previously supported by `ili9xxx` to ensure that nothing has been broken in the process.

This PR contains only the `io_bus` and `i80` components. Further PRs will add the functionality to the SPI and ili9xxx components.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes 
- https://github.com/esphome/feature-requests/issues/2387
- https://github.com/esphome/feature-requests/issues/901
- 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3761

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
i80:
  dc_pin: 7
  wr_pin: 8
  rd_pin: 9
  data_pins:
    - 39
    - 40
    - 41
    - 42
    -
      ignore_strapping_warning: true
      number: 45
    -
      ignore_strapping_warning: true
      number: 46
    - 47
    - 48
    
display:
  - platform: ili9xxx
    bus_type: i80
    cs_pin: 6
    reset_pin: 5
    model: st7789v
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-05-24 14:36 UTC, bearpawmaxim commented
Hello @clydebarrow !

How can I use this with my WT32-SC01 Plus screen?
There are no changes for `ili9xxx` component in this pr, so it fails on the `bus_type` validation...
If using your `iobus` branch, it also fails with the same.

Here's my config
`substitutions:
  device_name: battery-controller
      
packages:
  device_common: !include .device_common.yaml

esphome:
  name: battery-controller
  friendly_name: battery-controller

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: github://pr#6787
    components: [io_bus, i80]
  - source: github://clydebarrow/esphome@iobus
    components: [ili9xxx]
    refresh: 1s

# Enable logging
logger:

i80:
  dc_pin: 7
  wr_pin: 8
  rd_pin: 9
  data_pins:
    - 39
    - 40
    - 41
    - 42
    - ignore_strapping_warning: true
      number: 45
    - ignore_strapping_warning: true
      number: 46
    - 47
    - 48

spi:

display:
  - platform: ili9xxx
    bus_type: i80
    model: st7796
    dc_pin: GPIO1
    reset_pin: GPIO2
`

2024-05-24 21:43 UTC, clydebarrow commented
You need to use #6537 for now. That was the original complete PR. I was asked to split that into parts, this is just the first part, the others have to wait for this to be merged. But you should be able to use the original PR as is.

2024-08-07 02:23 UTC, jesserockz requested changes

2024-08-07 02:23 UTC, jesserockz commented on esphome/components/io_bus/io_bus.h
> +static GPIOPin *const NULL_PIN = new NullPin();  // NOLINT(cppcoreguidelines-avoid-non-const-global-variables)
I still really do not like this type of null handling being added.
```suggestion
```

2024-08-07 02:23 UTC, jesserockz commented on esphome/components/i80/i80_component.h
> +static I80Delegate *const NULL_DELEGATE = new I80DelegateDummy();  // NOLINT
This makes it out to be a user error instead of a developer error. Components should not get into a state where the things they depend on are not setup before the PR is merged even.
```suggestion
```

2024-08-07 02:26 UTC, clydebarrow commented on esphome/components/i80/i80_component.h
> +static I80Delegate *const NULL_DELEGATE = new I80DelegateDummy();  // NOLINT
When it's in a user-written lambda, it _is_ a user error. That check is there for precisely that reason, because it has happened in the field, and the effect without the check is a null-pointer crash, diagnosable only with serial logging.

2025-02-11 06:34 UTC, closed without merging