MSA311 and MSA301 accelerometer support
OttoWinter/esphomeyaml pull request #6795
Opened 2024-05-22 23:23 UTC by latonita

# What does this implement/fix?

Implements support of MSA311 and MSA301 accelerometers
- reading accel sensors
- on_tap/on_double_tap triggers

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2648

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
```yaml
# Example config.yaml
i2c: 
#...

msa3xx:
  model: msa311
  offset_x: -0.250 # m/s²
  offset_y: -0.400 # m/s²
  offset_z: -0.800 # m/s²
  update_interval: 5s
  on_tap:
    - then: 
        - logger.log: "Tapped"
  on_double_tap:
    - then: 
        - logger.log: "Double Tapped"

sensor:
  - platform: msa3xx
    accel_x: Accel X
    accel_y: Accel Y
    accel_z: Accel Z

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-05-23 04:54 UTC, lboue commented
Thank @latonita . The component built correctly.

2024-05-23 10:45 UTC, lboue commented
I noticed a warning:

`Error: POST:1:1: lint: Constant CONF_ACCEL_X is defined in 3 files. Please move all definitions of the constant to const.py (Uses: esphome/components/mpu6050/sensor.py, esphome/components/mpu6886/sensor.py, esphome/components/msa3xx/sensor.py)`

2024-05-23 11:20 UTC, latonita commented
> I noticed a warning:
> 
> ```
> Error: POST:1:1: lint: Constant CONF_ACCEL_X is defined in 3 files. 
> Please move all definitions of the constant to const.py (Uses: esphome/components/mpu6050/sensor.py, esphome/components/mpu6886/sensor.py, esphome/components/msa3xx/sensor.py)
> ```

I actually changed ACCEL_ to fully written ACCELERATION_ from const.py

2024-05-24 06:03 UTC, lboue commented
Working config for me:

```
msa3xx:
  model: msa311
  address: 0x62

  # offset used to configure proper 'zero'
  # can be from -4.5 to 4.5 m/s²
  #offset_x: 0.000 # m/s²
  #offset_y: 0.000 # m/s²
  #offset_z: 0.000 # m/s²
  update_interval: 5s
  on_tap:
    - then: 
        - logger.log: "Tapped"
  on_double_tap:
    - then: 
        - logger.log: "Double Tapped"

sensor:
  - platform: msa3xx
    acceleration_x: Accel X
    acceleration_y: Accel Y
    acceleration_z: Accel Z
```

![image](https://github.com/esphome/esphome/assets/938089/e399d16a-356a-4dd8-af0b-cb2f29d6ca7c)

2024-05-24 06:49 UTC, lboue commented
Do you think it would be possible to display the taps as press buttons? This would enable an automation to be triggered in HomeAssistant.
```
[08:01:56][W][msa3xx:383]: Activity detected
[08:01:56][W][msa3xx:383]: Activity detected
[08:01:56][W][msa3xx:373]: Double Tap detected
[08:01:56][D][main:245]: Double Tapped
[08:01:56][W][msa3xx:373]: Double Tap detected
[08:01:56][D][main:245]: Double Tapped
[08:01:56][W][msa3xx:383]: Activity detected
[08:05:35][W][msa3xx:383]: Activity detected
[08:05:35][W][msa3xx:368]: Single Tap detected
[08:05:35][D][main:240]: Tapped
[08:05:35][W][msa3xx:368]: Single Tap detected
[08:05:35][D][main:240]: Tapped
```

2024-05-24 06:55 UTC, latonita commented
Yes, I think so, need to check how buttons work

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ludovic BOUÉ ***@***.***>
Sent: Friday, May 24, 2024 8:50:06 AM
To: esphome/esphome ***@***.***>
Cc: Anton Viktorov ***@***.***>; Mention ***@***.***>
Subject: Re: [esphome/esphome] MSA311 and MSA301 accelerometer support (PR #6795)


Do you think it would be possible to display the taps as press buttons? This would enable an automation to be triggered in HomeAssistant.

[08:01:56][W][msa3xx:383]: Activity detected
[08:01:56][W][msa3xx:383]: Activity detected
[08:01:56][W][msa3xx:373]: Double Tap detected
[08:01:56][D][main:245]: Double Tapped
[08:01:56][W][msa3xx:373]: Double Tap detected
[08:01:56][D][main:245]: Double Tapped
[08:01:56][W][msa3xx:383]: Activity detected
[08:05:35][W][msa3xx:383]: Activity detected
[08:05:35][W][msa3xx:368]: Single Tap detected
[08:05:35][D][main:240]: Tapped
[08:05:35][W][msa3xx:368]: Single Tap detected
[08:05:35][D][main:240]: Tapped


—
Reply to this email directly, view it on GitHub<https://github.com/esphome/esphome/pull/6795#issuecomment-2128707210>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA6O66U55R3FCKRM4AXHXPLZD3PJ5AVCNFSM6AAAAABIERU46CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMRYG4YDOMRRGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-24 06:58 UTC, latonita commented
Not the buttons, but binary sensors.
Buttons are way round

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Anton Viktorov ***@***.***>
Sent: Friday, May 24, 2024 8:55:33 AM
To: esphome/esphome ***@***.***>; esphome/esphome ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [esphome/esphome] MSA311 and MSA301 accelerometer support (PR #6795)

Yes, I think so, need to check how buttons work

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ludovic BOUÉ ***@***.***>
Sent: Friday, May 24, 2024 8:50:06 AM
To: esphome/esphome ***@***.***>
Cc: Anton Viktorov ***@***.***>; Mention ***@***.***>
Subject: Re: [esphome/esphome] MSA311 and MSA301 accelerometer support (PR #6795)


Do you think it would be possible to display the taps as press buttons? This would enable an automation to be triggered in HomeAssistant.

[08:01:56][W][msa3xx:383]: Activity detected
[08:01:56][W][msa3xx:383]: Activity detected
[08:01:56][W][msa3xx:373]: Double Tap detected
[08:01:56][D][main:245]: Double Tapped
[08:01:56][W][msa3xx:373]: Double Tap detected
[08:01:56][D][main:245]: Double Tapped
[08:01:56][W][msa3xx:383]: Activity detected
[08:05:35][W][msa3xx:383]: Activity detected
[08:05:35][W][msa3xx:368]: Single Tap detected
[08:05:35][D][main:240]: Tapped
[08:05:35][W][msa3xx:368]: Single Tap detected
[08:05:35][D][main:240]: Tapped


—
Reply to this email directly, view it on GitHub<https://github.com/esphome/esphome/pull/6795#issuecomment-2128707210>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA6O66U55R3FCKRM4AXHXPLZD3PJ5AVCNFSM6AAAAABIERU46CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMRYG4YDOMRRGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-24 13:16 UTC, latonita commented
@lboue  check new version. internal debounce of 500 ms enabled on all three binary sensors.
To extend the signal i would use filter delayed_off like in example yaml (for `activity`)

![image](https://github.com/esphome/esphome/assets/3993466/4d381610-85af-42f1-83b6-66ef78feef7a)

2024-05-24 13:57 UTC, lboue commented
I've just tried it and it's great!

![image](https://github.com/esphome/esphome/assets/938089/6747f3d7-6e87-455c-ab70-bbbc51247665)


```yaml
[15:55:12][D][sensor:094]: 'Accel Y': Sending state 0.01964 m/s² with 2 decimals of accuracy
[15:55:12][D][sensor:094]: 'Accel Z': Sending state 0.85070 m/s² with 2 decimals of accuracy
[15:55:14][D][binary_sensor:036]: 'Active': Sending state ON
[15:55:14][D][main:249]: Tapped
[15:55:14][D][binary_sensor:036]: 'Single tap': Sending state ON
[15:55:15][D][binary_sensor:036]: 'Single tap': Sending state OFF
[15:55:16][D][main:254]: Double Tapped
[15:55:16][D][binary_sensor:036]: 'Double tap': Sending state ON
[15:55:16][D][binary_sensor:036]: 'Double tap': Sending state OFF
[15:55:17][D][sensor:094]: 'Accel X': Sending state -9.66457 m/s² with 2 decimals of accuracy
[15:55:17][D][sensor:094]: 'Accel Y': Sending state 0.02196 m/s² with 2 decimals of accuracy
[15:55:17][D][sensor:094]: 'Accel Z': Sending state 0.87806 m/s² with 2 decimals of accuracy
[15:55:21][D][binary_sensor:036]: 'Active': Sending state OFF
[15:55:22][D][sensor:094]: 'Accel X': Sending state -9.66274 m/s² with 2 decimals of accuracy
[15:55:22][D][sensor:094]: 'Accel Y': Sending state 0.03587 m/s² with 2 decimals of accuracy
> ```

![image](https://github.com/esphome/esphome/assets/938089/fc7f4c1b-c06b-404c-bf1b-93e2ba9c6fba)

2024-05-26 23:43 UTC, jesserockz requested changes, later dismissed

2024-05-26 23:43 UTC, jesserockz commented on esphome/components/msa3xx/__init__.py
> +AUTO_LOAD = ["sensor", "binary_sensor", "text_sensor"]
Auto loading the platforms is not allowed. Please restructure your code so that it can safely compile without these being available.
```suggestion
```

2024-05-27 08:29 UTC, latonita commented on esphome/components/msa3xx/__init__.py
> +AUTO_LOAD = ["sensor", "binary_sensor", "text_sensor"]
done

2024-05-29 16:23 UTC, lboue commented on esphome/components/msa3xx/__init__.py
> +AUTO_LOAD = ["sensor", "binary_sensor", "text_sensor"]
@latonita can you use the 'Ready for review' button when you are done

2024-06-19 05:08 UTC, lboue commented
@latonita Have you made the requested changes?

2024-06-19 07:58 UTC, latonita commented
> @latonita Have you made the requested changes?

yes, changes are done, review was re-requested a while ago.
it takes time.

2024-10-14 04:28 UTC, lboue commented
Why is the review labelled lvgl? I think this is a mistake.

2024-10-31 09:14 UTC, latonita commented
> Why is the review labelled lvgl? I think this is a mistake.

there is one from lvgl file had to be changed. its required due to duplication check in the build pipeline

2024-12-11 02:31 UTC, baffles commented
Will this be merged anytime soon? Surely 7 months is enough time for a review and merge, and yet there's no updates here?

2024-12-16 01:58 UTC, baffles commented
@latonita / @lboue / @clydebarrow / @jesserockz ?

2024-12-16 04:19 UTC, clydebarrow requested changes

2024-12-16 04:19 UTC, clydebarrow commented on esphome/components/msa3xx/text_sensor.py
> +CONFIG_SCHEMA = cv.All(
It's not necessary to wrap a single schema in `cv.All`.

2024-12-16 04:19 UTC, clydebarrow commented on esphome/components/msa3xx/text_sensor.py
> +    SENSORS = [CONF_ORIENTATION_XY, CONF_ORIENTATION_Z]
Why not move this into the file scope, and use it to generate the schema as well, using a dict comprehension, e.g.

```
SENSORS = (CONF_ORIENTATION_XY, CONF_ORIENTATION_Z)

CONFIG_SCHEMA = cv.Schema(
    {
        cv.GenerateID(CONF_MSA3XX_ID): cv.use_id(MSA3xxComponent),
    }
).extend(
    {
        cv.Optional(sensor): cv.maybe_simple_value(
            text_sensor.text_sensor_schema(icon=ICON_SCREEN_ROTATION),
            key=CONF_NAME,
        )
        for sensor in SENSORS
    }
)

```

Similarly for entries in `sensor.py` and `binary_sensor.py`

2024-12-16 04:19 UTC, clydebarrow commented on esphome/components/msa3xx/text_sensor.py
> +    ).extend(cv.COMPONENT_SCHEMA)
Why extend the component schema for a sensor?

2024-12-16 04:19 UTC, clydebarrow commented on tests/components/msa3xx/common.yaml
> +    acceleration_z: Accel Z
Needs entries for `binary_sensor` and `text_sensor`

2024-12-16 04:19 UTC, clydebarrow commented on esphome/components/msa3xx/__init__.py
> +            cv.Required(CONF_MODEL): cv.enum(MSA_MODELS, upper=True),
Use `cv.typed_schema` to offer different schemas for each model. This will avoid having to use the final validation (which didn't need to be final anyway.) And either set the correct default i2c address for each model or better don't use `i2c_device_schema` at all, just set  the correct address for each model in `to_code()` before calling `register_i2c_device`. The user shouldn't even be offered the chance to choose the address if you aren't going to accept it.

2024-12-23 21:05 UTC, latonita commented
@baffles @lboue please check the new version.
minimal changes to config: there shall be 'type: msa301' or 'type:msa311'

2024-12-23 21:12 UTC, latonita commented on esphome/components/msa3xx/__init__.py
> +            cv.Required(CONF_MODEL): cv.enum(MSA_MODELS, upper=True),
done

2025-02-22 03:14 UTC, clydebarrow requested changes

2025-02-22 03:14 UTC, clydebarrow commented on esphome/components/msa3xx/__init__.py
> +        config[CONF_RESOLUTION] = 12
Rather than doing this here, add `CONF_RESOLUTION` to the MSA311 config, but with only a single choice and a corresponding default.

2025-02-22 03:14 UTC, clydebarrow commented on esphome/components/msa3xx/__init__.py
> +        transform = config[CONF_TRANSFORM]
```suggestion
    if transform := config.get(CONF_TRANSFORM):
```

This is the preferred style for handling config options that may not be present. Apply this to the subsequent code too where possible. Just beware of options that can have values that are Falsy like 0 - in that case it is necessary to write `if (xxx := config.get(CONF_XXX) is not None:`

2025-02-22 03:14 UTC, clydebarrow commented on esphome/components/msa3xx/binary_sensor.py
> +    }
Refactor this out to the parent since it's used in multiple platforms. Call it MSA_SCHEMA or similar, and just import and extend that in the platform files.

2025-02-23 17:11 UTC, latonita commented on esphome/components/msa3xx/__init__.py
> +        transform = config[CONF_TRANSFORM]
good, i forgot about this codestyle. applied!

2025-02-23 17:11 UTC, latonita commented on esphome/components/msa3xx/binary_sensor.py
> +    }
thats a nice idea, thanks !

2025-02-23 17:12 UTC, latonita commented on esphome/components/msa3xx/__init__.py
> +        config[CONF_RESOLUTION] = 12
agreed, updated!

2025-02-27 03:45 UTC, clydebarrow approved these changes

2025-02-27 03:48 UTC, merged