Add rotation config parameter for stepper component.
OttoWinter/esphomeyaml pull request #6803
Opened 2024-05-24 10:56 UTC by cvwillegen

# What does this implement/fix?

In certain configurations, you might want a stepper motor to only run in one direction (e.g. when there's an object blocking rotation in one direction). Or when a stepper motor is used to indicate the hands on a clock.

This PR adds the possibility to add a ``rotation`` parameter to the stepper motor config, forcing a specific direction when running the motor. Note! The user must take care of not running onto an infinite loop when using ``set_target`` on the stepper motor, i.e. by using the ``report-position`` when the position of the stepper motor in known.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: test-stepper
  friendly_name: test_stepper

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "cxxxxxxxxxxxxxxxxcccxxaaa"

ota:
  password: "xxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Stepper Fallback Hotspot"
    password: "xxxxxxxxxxx"

captive_portal:

stepper:
  - platform: uln2003
    pin_a: D1
    pin_b: D2
    pin_c: D3
    pin_d: D4
    id: my_stepper
    max_speed: 70 steps/s

globals:
  - id: g_position
    type: int
    restore_value: no
    initial_value: '0'

number:
  - platform: template
    id: position
    min_value: 0
    max_value: 2048
    step: 1
    name: Position
    internal: False
    mode: BOX
    on_value: 
      then:
        - lambda: |-
            id(g_position) = x;
    set_action: 
      then:
        - stepper.set_target: 
            id: my_stepper
            target: !lambda return x;

button:
  - platform: template
    name: CCW
    id: ccw
    on_press:
      - stepper.set_rotation:
          id: my_stepper
          rotation: ccw

  - platform: template
    name: CW
    id: cw
    on_press:
      - stepper.set_rotation:
          id: my_stepper
          rotation: cw

  - platform: template
    name: Both
    id: both
    on_press:
      - stepper.set_rotation:
          id: my_stepper
          rotation: both```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-05-26 19:44 UTC, jesserockz requested changes

2024-05-26 19:44 UTC, jesserockz commented on esphome/components/stepper/__init__.py
> +        cv.Optional(CONF_ROTATION, default="both"): validate_rotation,
Please use an enum in c++ and `cv.enum` in python for this.

2024-05-28 09:41 UTC, cvwillegen commented on esphome/components/stepper/__init__.py
> +        cv.Optional(CONF_ROTATION, default="both"): validate_rotation,
Thanks for the hint!

2024-05-29 05:21 UTC, jesserockz requested changes

2024-05-29 05:21 UTC, jesserockz commented on esphome/components/stepper/__init__.py
> +}
Lets not add multiple options per each type. It can add confusion and be less clear in the documentation.

```suggestion
ROTATIONS = {
    "BOTH": Rotation.ROTATION_BOTH,
    "CLOCKWISE": Rotation.ROTATION_CW,
    "COUNTERCLOCKWISE": Rotation.ROTATION_CCW,
}
```

2024-05-29 05:21 UTC, jesserockz commented on esphome/components/stepper/stepper.cpp
> +                                              : (rotation_ == ROTATION_CW ? 1 : -1));
Please split this out so there are not embedded ternaries

2024-10-03 10:45 UTC, cvwillegen commented
The failure looks unrelated to my changes. I'll update the branch later on to see if it makes any difference...

2024-12-05 01:30 UTC, jesserockz commented on esphome/components/stepper/__init__.py
> +        cg.add(stepper_var.set_rotation(config[CONF_ROTATION]))
As there is a default, we dont need to check
```suggestion
    cg.add(stepper_var.set_rotation(config[CONF_ROTATION]))
```

2024-12-05 01:31 UTC, jesserockz requested changes
Changes look good. Please add to the test yaml files

2026-04-29 01:14 UTC, closed without merging