fix rtttl error:  Note out of valid range
OttoWinter/esphomeyaml pull request #6817
Opened 2024-05-27 16:07 UTC by nielsnl68

# What does this implement/fix?

I got some errors that show an error about  range errors.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-16 10:56 UTC, xNUTx commented
Without this fix PR#6718 will cause my unit to throw a fit once I start the microphone (in this process the rtttl is used to have an audible start of the listening phase).

```
[23:42:29][D][switch:012]: 'Voice Assistant On/Off' Turning ON.
[23:42:29][D][switch:055]: 'Voice Assistant On/Off': Sending state ON
[23:42:29][D][rtttl:051]: Playing song scale_up
[23:42:29][D][rtttl:294]: play time old: 750 div: 25 new: 783150 31326
[23:42:29][D][esp-idf:000][speaker_task]: I (130515) I2S: DMA Malloc info, datalen=blocksize=512, dma_buf_count=4

[23:42:29][D][i2s_audio:072][speaker_task]: Installing driver : yes
[23:42:29][D][rtttl:294]: play time old: 750 div: 26 new: 768924 29574
[23:42:29][D][i2s_audio.speaker:163]: Started I2S Audio Speaker
[23:42:29][D][rtttl:294]: play time old: 750 div: 30 new: 790200 26340
[23:42:29][D][rtttl:294]: play time old: 750 div: 31 new: 770691 24861
[23:42:29][D][rtttl:294]: play time old: 750 div: 35 new: 774900 22140
[23:42:29][D][rtttl:294]: play time old: 750 div: 39 new: 768924 19716
[23:42:29][D][rtttl:294]: play time old: 750 div: 44 new: 773476 17579
[23:42:29][D][rtttl:294]: play time old: 750 div: 47 new: 779354 16582
[23:42:29][D][rtttl:176]: Playback finished
[23:42:29][D][ring_buffer:024]: Created ring buffer with size 2048
[23:42:29][D][micro_wake_word:399]: Resetting buffers and probabilities
[23:42:29][D][micro_wake_word:195]: State changed from IDLE to START_MICROPHONE
[23:42:29][D][micro_wake_word:107]: Starting Microphone
[23:42:29][D][micro_wake_word:195]: State changed from START_MICROPHONE to STARTING_MICROPHONE
[23:42:29][D][esp-idf:000]: I (130784) I2S: DMA Malloc info, datalen=blocksize=1024, dma_buf_count=4

[23:42:29][D][i2s_audio:072]: Installing driver : yes
[23:42:29][D][micro_wake_word:195]: State changed from STARTING_MICROPHONE to DETECTING_WAKE_WORD
[23:42:29][W][component:157]: Component i2s_audio.microphone set Warning flag: unspecified
[23:42:29][W][component:170]: Component i2s_audio.microphone cleared Warning flag
[23:42:29][W][component:157]: Component i2s_audio.microphone set Warning flag: unspecified
[23:42:29][W][component:170]: Component i2s_audio.microphone cleared Warning flag
[23:42:29][W][component:157]: Component i2s_audio.microphone set Warning flag: unspecified
[23:42:29][W][component:170]: Component i2s_audio.microphone cleared Warning flag
[23:42:29][W][component:157]: Component i2s_audio.microphone set Warning flag: unspecified
[23:42:29][W][component:170]: Component i2s_audio.microphone cleared Warning flag
[23:42:29][W][component:157]: Component i2s_audio.microphone set Warning flag: unspecified
[23:42:29][W][component:170]: Component i2s_audio.microphone cleared Warning flag
[23:42:29][W][component:157]: Component i2s_audio.microphone set Warning flag: unspecified
[23:42:29][W][component:170]: Component i2s_audio.microphone cleared Warning flag
[23:42:29][W][component:157]: Component i2s_audio.microphone set Warning flag: unspecified
[23:42:29][W][component:170]: Component i2s_audio.microphone cleared Warning flag
[23:42:29][W][component:157]: Component i2s_audio.microphone set Warning flag: unspecified
[23:42:29][W][component:170]: Component i2s_audio.microphone cleared Warning flag
```
This last notification will keep coming until I stop the mww/microphone listening.

Just to iterate: it _FIXED_ my issue.

2024-08-12 23:15 UTC, jesserockz requested changes
Given that the `finish` code does nothing useful at this time, I do not see any point in adding it (yet).

Can you split the speaker.is_stopped code into its own PR please that this one would be dependent on?

2024-08-13 00:46 UTC, nielsnl68 commented
> Given that the `finish` code does nothing useful at this time, I do not see any point in adding it (yet).
>
The implementation of the `finish` code was very easy. and is done it the split PR#7255

> Can you split the speaker.is_stopped code into its own PR please that this one would be dependent on?

Done.

2024-08-14 10:50 UTC, nielsnl68 commented
@jesserockz this one is ready as well.

2024-08-15 04:25 UTC, jesserockz requested changes
One minor missing prefix :see_no_evil: 
Otherwise looks good.

2024-08-15 04:25 UTC, jesserockz commented on esphome/components/rtttl/rtttl.cpp
> +    int pos = rtttl_.find(':');
```suggestion
    int pos = this->rtttl_.find(':');
```

2024-08-15 04:25 UTC, jesserockz approved these changes

2024-08-15 04:51 UTC, merged