Add SPS30 idle mode functionality
OttoWinter/esphomeyaml pull request #6828
Opened 2024-05-29 18:39 UTC by c0mputerguru

# What does this implement/fix?

Adds functionality to put SPS30 sensor into idle mode.  This can be done manually as an action or in a idle/wake/warm-up/read/idle loop by specifying the `idle_interval` configuration parameter.

This is useful as the SPS30 sensor when running in continuous mode always has its fan on.  To improve energy usage as well as prolong the life of the sensor, it can be put into idle mode where measurements are no longer taken.

When measurement is started again, the [documentation](https://sensirion.com/media/documents/188A2C3C/6166F165/Sensirion_Particulate_Matter_AppNotes_SPS30_Low_Power_Operation_D1.pdf) states that there is a warm up period of up to 30 seconds.

Note that this warm-up period is applied whether or not the idle_interval is specified.  This is the only change in behavior compared to status quo, but any readings taken prior to sensor warm-up were not necessarily accurate, so this change may remove some inaccurate readings, so I don't consider this a breaking change.

Inspiration for this change:
https://community.home-assistant.io/t/ignoring-sensor-values-during-warm-up-after-periodic-wake-up/245401/9
https://github.com/tiimsvk/SPS30-idle-mode

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2133

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3913

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: sps30
    id: particulate
    update_interval: 1s
    idle_interval: 5min
    pm_1_0:
      name: "PM <1µm Weight concentration"
      id: "PM_1_0"
    pm_2_5:
      name: "PM <2.5µm Weight concentration"
      id: "PM_2_5"
    pm_4_0:
      name: "PM <4µm Weight concentration"
      id: "PM_4_0"
    pm_10_0:
      name: "PM <10µm Weight concentration"
      id: "PM_10_0"
    pmc_0_5:
      name: "PM <0.5µm Number concentration"
      id: "PMC_0_5"
    pmc_1_0:
      name: "PM <1µm Number concentration"
      id: "PMC_1_0"
    pmc_2_5:
      name: "PM <2.5µm Number concentration"
      id: "PMC_2_5"
    pmc_4_0:
      name: "PM <4µm Number concentration"
      id: "PMC_4_0"
    pmc_10_0:
      name: "PM <10µm Number concentration"
      id: "PMC_10_0"
    pm_size:
      name: "Typical Particle size"
      id: "pm_size"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-05-30 04:08 UTC, c0mputerguru commented
I've also got https://github.com/c0mputerguru/esphome/pull/1 as a prototype of how to implement the wake/sleep and warm-up in the component itself.

2024-12-16 20:15 UTC, SP2FET commented
Is there any possibility to bring take that PR to be merged? It's kind of nice feature. I'm currently using the diff as a local component, but as it's already prepared - it should be merged IMO :)

2024-12-16 20:20 UTC, c0mputerguru commented
I'd like it to be merged as well, but it's currently waiting on review from
a repo owner.

On Mon, Dec 16, 2024, 12:15 PM Bartosz Cichocki ***@***.***>
wrote:

> Is there any possibility to bring take that PR to be merged? It's kind of
> nice feature. I'm currently using the diff as a local component, but as
> it's already prepared - it should be merged IMO :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/6828#issuecomment-2546636269>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFPT7N44WGUIISM2EPU2VHD2F4YGVAVCNFSM6AAAAABTW5KQLSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBWGYZTMMRWHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-16 21:47 UTC, SP2FET commented
@c0mputerguru I see - just wanted to bump up the thread, maybe the code owner will notice that PR

2025-01-02 14:52 UTC, Kaedeko commented
Just adding my voice to this PR - having to currently manually implement this behaviour, would be great for it to be in ESPHome.

2025-10-27 20:47 UTC, bruvv commented
please get this merged!  @martgras ping ping

2025-10-29 21:15 UTC, andy7t commented
@bdraco I see you approved a change on sps30 a few days ago? Is this something you can help with?

2025-11-25 16:20 UTC, SeveranExp commented
I'm currenly replacing one SPS30 sensor because of this idle topic. Would be amazing to have this merged. How can we increase the visibility of this topic??

2025-11-25 16:36 UTC, bruvv commented
@bdraco perhaps you can have a look ?

2025-11-25 17:06 UTC, bdraco requested changes
Hi, thanks for the contribution! Before this can be reviewed, there are a few issues that need to be addressed:

1. **Branch conflicts**: This branch has conflicts that must be resolved and is 4555 commits behind `dev`. Please merge `dev` into your branch to resolve these.

2. **Branch naming**: The branch is named `dev`, which makes it difficult to review since it conflicts with our main development branch name. Please rename it to something descriptive like `sps30-idle-mode` or `feature/sps30-idle`.

Additionally, a note for those pinging maintainers for reviews in the comments: **please do not do this**. It is considered rude and is not allowed in this project. Users who violate this rule get added to maintainers' ignore lists, which is counterproductive to getting PRs reviewed. Maintainers monitor PRs and will review when they have availability.

Once the branch is updated and renamed, this will be much easier for someone to review. Thanks for your patience!

2025-11-25 22:47 UTC, Repsay commented
@c0mputerguru would be great if this could be fixed and merged.

2025-11-25 23:02 UTC, c0mputerguru commented
I'm not going to be able to look at this for a few weeks but will take a
look when I have the chance.

On Tue, Nov 25, 2025, 4:47 PM Jasper Delahaije ***@***.***>
wrote:

> *Repsay* left a comment (esphome/esphome#6828)
> <https://github.com/esphome/esphome/pull/6828#issuecomment-3577910838>
>
> @c0mputerguru <https://github.com/c0mputerguru> would be great if this
> could be fixed and merged.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/6828#issuecomment-3577910838>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFPT7NZOMQ4K2CTBUPBWDK336TL75AVCNFSM6AAAAABTW5KQLSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTKNZXHEYTAOBTHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-11-29 07:17 UTC, valluriavi commented
Is idle mode implemented for the SPS30? 
I used SPS30 with esphome and the fan is spinning continuously even when ESP 32C6 is in deep sleep mode.

2025-11-29 08:38 UTC, SeveranExp commented
> Is idle mode implemented for the SPS30? I used SPS30 with esphome and the fan is spinning continuously even when ESP 32C6 is in deep sleep mode.

Not yet.

2025-12-02 17:38 UTC, c0mputerguru commented
Looks like there's no good way to rename the branch and keep the same pull request so I created a new one.

Closed in favor of #12255

2025-12-02 17:38 UTC, closed without merging