[dsmr] Add internal 'telegram' text_sensor to support bridging
OttoWinter/esphomeyaml pull request #6841
Opened 2024-05-31 08:34 UTC by marcovaneck

# [DSMR] Adding internal 'telegram' text_sensor to support bridging 

By creating an internal _telegram_ text_sensor it's possible to forward the telegram to another uart (P1 bridge) or simply log it.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> **TODO**

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
```yaml
# Example config.yaml
text_sensor:
- platform: dsmr
   telegram:
      name: "telegram"
      disabled_by_default: true
      on_value:
        then:
          - lambda: |-
              ESP_LOGI("dsrm", "telegram is %s", x.c_str());
              p1_bridge_uart->write_str(x.c_str());
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-04 13:47 UTC, nagyrobi commented
What a great idea!

2024-06-05 19:29 UTC, jesserockz requested changes

2024-06-05 19:29 UTC, jesserockz commented on esphome/components/dsmr/dsmr.cpp
> +  }
This should be set in the config schema to default `internal: true` instead. 
The `homeassistant` platform of sensors does this.

2024-06-06 10:23 UTC, marcovaneck commented on esphome/components/dsmr/dsmr.cpp
> +  }
Hi @jesserockz, first of all thanks for your comment. I'm new to esphome(development), but I can't figger out how to make this sensor _internal_ by default. I assume this can be done in text_sensor.py? Or do you mean it should be done in the yaml for the device?

2024-06-06 11:32 UTC, nagyrobi commented on esphome/components/dsmr/dsmr.cpp
> +  }
See https://github.com/marcovaneck/esphome/blob/c4fe6428fc24558922c73aa6aee7571a092da483/esphome/components/homeassistant/__init__.py#L12

2024-06-08 09:13 UTC, marcovaneck commented on esphome/components/dsmr/dsmr.cpp
> +  }
Hi @jesserockz, the working of default is unclear to me. _default=True_ didn't do the trick. But I agree it's not nice to force internal to be turned off. So I removed the code block and added _internal: true_ to the documentation.

2024-06-09 20:08 UTC, jesserockz commented on esphome/components/dsmr/text_sensor.py
> +        cv.Optional("telegram"): text_sensor.text_sensor_schema(),
This wont pass CI, but is how you do it.
```suggestion
        cv.Optional("telegram"): text_sensor.text_sensor_schema().extend({cv.Optional(CONF_INTERNAL, default=True): cv.boolean),
```

2024-06-10 10:14 UTC, marcovaneck commented on esphome/components/dsmr/text_sensor.py
> +        cv.Optional("telegram"): text_sensor.text_sensor_schema(),
Thanks @jesserockz !
 It takes a while but now I understand how it works. I've tested you're suggested change and it of course it works. The documentation will be updated as well. (strange enough the CI pytest on linux 3.11 fails, but on the other mac/windows they succeed trying to reproduce and fix)

2024-08-31 06:10 UTC, mhendriks commented
Thanks Marco for this addition. This works really fine on various hardware (equipped with ESP32S3 and ESP32C3). 

See:
https://github.com/mhendriks/esphome-p1/blob/main/p1-dongle-pro-h2o-v2.yaml
and
https://github.com/mhendriks/esphome-p1/blob/main/ultra.yaml

Would be nice when this PR in merged into the main :-)

2024-09-02 04:10 UTC, jesserockz approved these changes

2024-09-10 07:21 UTC, niobos commented
I also needed this feature, so I was looking into adding it myself. Good thing that I checked the open PRs! Thank you!

And also a sneaky "ping" to hopefully get this merged into main...

2024-09-10 08:22 UTC, merged