change to new 1-wire platform
OttoWinter/esphomeyaml pull request #6860
Opened 2024-06-04 08:16 UTC by ssieb

# What does this implement/fix?

Moves the 1-wire support out of the dallas temperature sensor into its own platform.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3911

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [X] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
one_wire:
  - platform: gpio
    pin: 4

sensor:
  - platform: dallas_temp
    resolution: 12
    name: "Temperature"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-04 13:02 UTC, sphen13 commented
In my limited test here on a ESP32-WROOM-32D and a single DS18B20, this is working. It was not working previously and i had to use an external component.

2024-06-04 14:59 UTC, sphen13 commented
also tested same sensor on d1mini ESP8266 and it is working - some compilation warnings:

```INFO ESPHome 2024.5.4
INFO Reading configuration /config/esphome/dev-01.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing dev-01 (board: d1_mini; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/noise-c @ 0.1.4
INFO Installing esphome/noise-c @ 0.1.4
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.4 has been installed!
INFO noise-c@0.1.4 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10018.1
INFO Installing esphome/libsodium @ 1.10018.1
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10018.1 has been installed!
INFO libsodium@1.10018.1 has been installed!
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
Compiling .pioenvs/dev-01/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/dallas_temp/dallas_temp.cpp.o
src/esphome/components/dallas_temp/dallas_temp.cpp: In member function 'virtual void esphome::one_wire::DallasTemperatureSensor::setup()':
src/esphome/components/dallas_temp/dallas_temp.cpp:89:29: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
   89 |   if (this->address_ & 0xff == DALLAS_MODEL_DS18S20) {
      |                        ~~~~~^~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/dallas_temp/dallas_temp.cpp: In member function 'float esphome::one_wire::DallasTemperatureSensor::get_temp_c_()':
src/esphome/components/dallas_temp/dallas_temp.cpp:147:29: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
  147 |   if (this->address_ & 0xff == DALLAS_MODEL_DS18S20) {
      |                        ~~~~~^~~~~~~~~~~~~~~~~~~~~~~
Compiling .pioenvs/dev-01/src/esphome/components/duty_time/duty_time_sensor.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/esp8266/core.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/esp8266/gpio.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/esp8266/preferences.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/gpio/one_wire/gpio_one_wire.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/gpio/switch/gpio_switch.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/logger/logger_esp32.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/logger/logger_esp8266.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/logger/logger_host.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/logger/logger_libretiny.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/logger/logger_rp2040.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/one_wire/one_wire.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/one_wire/one_wire_bus.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/ota/ota_backend_arduino_libretiny.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/script/script.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/sensor/sensor.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/sntp/sntp_component.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/socket/lwip_sockets_impl.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/socket/socket.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/switch/automation.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/switch/switch.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/time/automation.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/time/real_time_clock.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/wifi/wifi_component_esp32_arduino.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/wifi/wifi_component_esp_idf.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/wifi/wifi_component_libretiny.cpp.o
Compiling .pioenvs/dev-01/src/esphome/components/wifi/wifi_component_pico_w.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/application.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/color.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/component.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/component_iterator.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/controller.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/entity_base.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/helpers.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/log.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/ring_buffer.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/scheduler.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/string_ref.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/time.cpp.o
Compiling .pioenvs/dev-01/src/esphome/core/util.cpp.o
Compiling .pioenvs/dev-01/src/main.cpp.o
Generating LD script .pioenvs/dev-01/ld/local.eagle.app.v6.common.ld
Compiling .pioenvs/dev-01/lib67b/ESP8266WiFi/BearSSLHelpers.cpp.o
Compiling .pioenvs/dev-01/lib67b/ESP8266WiFi/CertStoreBearSSL.cpp.o
Compiling .pioenvs/dev-01/lib67b/ESP8266WiFi/ESP8266WiFi.cpp.o
Compiling .pioenvs/dev-01/lib67b/ESP8266WiFi/ESP8266WiFiAP.cpp.o
Compiling .pioenvs/dev-01/lib67b/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
Compiling .pioenvs/dev-01/lib67b/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
Compiling .pioenvs/dev-01/lib67b/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
Compiling .pioenvs/dev-01/lib67b/ESP8266WiFi/ESP8266WiFiSTA-WPS.cpp.o
Compiling .pioenvs/dev-01/lib67b/ESP8266WiFi/ESP826 [...]

2024-06-07 21:08 UTC, lboue commented
Hello @ssieb. Thank you for your contribution.
I'm trying to test it and I'm getting an error:

```
INFO ESPHome 2024.6.0-dev
INFO Reading configuration /config/esphome/1-wire-bus.yaml...
Failed config

one_wire.gpio: [source /config/esphome/1-wire-bus.yaml:47]
  
  Platform not found: 'one_wire.gpio'.
  platform: gpio
  pin: 4
```

**ESPHome config**
```yaml
external_components:
    # https://github.com/esphome/esphome/pull/6860
  - source: github://pr#6860
    components: 
      - dallas
      - dallas_temp
      - gpio/one_wire
      - one_wire

# 1-Wire Bus
one_wire:
  - platform: gpio
    pin: 4

sensor:
  - platform: dallas_temp
    resolution: 12
    name: "Temperature"
```
Do you know how to correct this?

2024-06-07 21:29 UTC, ssieb commented
Don't include `dallas` and it's just `gpio`.

2024-06-08 03:45 UTC, lboue commented
> Don't include `dallas` and it's just `gpio`.

```yaml
external_components:
    # https://github.com/esphome/esphome/pull/6860
  - source: github://pr#6860
    components: 
      #- dallas
      #- dallas_temp
      - gpio/one_wire
      - one_wire

# DS248x family of i2c to 1-wire
# https://github.com/ssieb/esphome-docs/blob/fe7059dbe0e0cd03005ce88f0042cfcca49d656e/components/one_wire.rst
# 1-Wire Bus

# The gpio platform uses the CPU to generate the bus signals on a GPIO pin.
one_wire:
  - platform: gpio
    pin: 4

```
This generates the same error:
```
Download 1-wire-bus.yaml
INFO ESPHome 2024.6.0-dev
INFO Reading configuration /config/esphome/1-wire-bus.yaml...
Failed config

one_wire.gpio: [source /config/esphome/1-wire-bus.yaml:49]
  
  Platform not found: 'one_wire.gpio'.
  platform: gpio
  pin: 4
```

2024-06-08 07:23 UTC, ssieb commented
You do need the `dallas_temp` and `gpio`, not `gpio/one_wire`.

2024-06-09 15:05 UTC, lboue commented
Thanks. It's OK this time.

```yaml
external_components:
    # https://github.com/esphome/esphome/pull/6860
  - source: github://pr#6860
    components: 
      - dallas_temp
      - one_wire
      - gpio
    refresh: 0s

one_wire:
  - platform: gpio
    pin: 4

# DS18B20 Temperature Sensor
sensor:
  - platform: dallas_temp
    resolution: 12
    name: "Temperature"
```

2024-06-11 23:33 UTC, jesserockz requested changes

2024-06-11 23:33 UTC, jesserockz commented on tests/components/dallas/common.yaml
This folder should be renamed to `dallas_temp` or it will not be run

2024-06-11 23:33 UTC, jesserockz commented on tests/test1.yaml
Lets just drop the dallas/one-wire from the old test files

2024-06-11 23:33 UTC, jesserockz commented on esphome/components/dallas_temp/sensor.py
> +        cg.add(var.set_resolution(config[CONF_RESOLUTION]))
There is a default so checking is not needed
```suggestion
    cg.add(var.set_resolution(config[CONF_RESOLUTION]))
```

2024-06-11 23:33 UTC, jesserockz commented on esphome/components/one_wire/__init__.py
> +        cg.add(var.set_address(config[CONF_ADDRESS]))
```suggestion
    if (address := config.get(CONF_ADDRESS)) is not None:
        cg.add(var.set_address(address))
```

2024-06-11 23:33 UTC, jesserockz commented on esphome/components/dallas_temp/dallas_temp.cpp
> +  for (unsigned char &i : this->scratch_pad_) {
```suggestion
  for (uint8_t &i : this->scratch_pad_) {
```

2024-06-11 23:48 UTC, jesserockz approved these changes

2024-06-11 23:51 UTC, ssieb commented
Release note:
The `dallas` component has been split up into the `one_wire` bus and the `dallas_temp` sensor.  This will allow for other 1-wire interfaces to be added and other 1-wire devices that aren't temperature sensors.  The `index` option has been removed.  If there is only one device on the bus, then the address is optional.  Otherwise, you must specify the address.

2024-06-12 01:05 UTC, merged