Add Initial TE-M3200 pressure sensor support
OttoWinter/esphomeyaml pull request #6862
Opened 2024-06-05 02:16 UTC by bakerkj

# What does this implement/fix?

Adds support for the TE-M3200 i2c pressure sensor.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-07 18:10 UTC, swoboda1337 commented on esphome/components/tem3200/tem3200.cpp
> +  this->set_timeout(50, [this]() {
Why do you need this timeout when nothing is done before it? What are you waiting for?

2024-06-07 18:34 UTC, bakerkj commented on esphome/components/tem3200/tem3200.cpp
> +  this->set_timeout(50, [this]() {
@swoboda1337, I duplicated this from another component I was modeling some of my work on. Given your comment, I believe I misunderstood its purpose. There is nothing before this to wait on. Given your comment, and reading some more, I believe it is not needed.

2024-06-07 20:57 UTC, bakerkj commented on esphome/components/tem3200/tem3200.cpp
> +  this->set_timeout(50, [this]() {
I have updated the code to remove this timeout. Thanks for your help!

2024-07-29 03:47 UTC, jesserockz requested changes

2024-07-29 03:47 UTC, jesserockz commented on esphome/components/tem3200/sensor.py
> +CONFIG_MULTI = True
Not required
```suggestion
```

2024-07-29 03:47 UTC, jesserockz commented on esphome/components/tem3200/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_TEMPERATURE])
```suggestion
    if temperature_config := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_config)
```

2024-07-29 03:47 UTC, jesserockz commented on esphome/components/tem3200/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_RAW_PRESSURE])
```suggestion
    if raw_pressure_config := config.get(CONF_RAW_PRESSURE):
        sens = await sensor.new_sensor(raw_pressure_config)
```

2024-07-29 03:47 UTC, jesserockz commented on esphome/components/tem3200/tem3200.h
> +  void set_temperature_sensor(sensor::Sensor *temperature_sensor) { temperature_sensor_ = temperature_sensor; }
https://esphome.io/guides/contributing#codebase-standards
> All uses of class members and member functions should be prefixed with this-> to distinguish them from global functions in code review.

```suggestion
  void set_temperature_sensor(sensor::Sensor *temperature_sensor) { this->temperature_sensor_ = temperature_sensor; }
```

2024-07-29 03:47 UTC, jesserockz commented on esphome/components/tem3200/tem3200.cpp
> +float TEM3200Component::convert_temperature_(uint16_t raw_temperature) {
This function can probably just be an inline function outside of the class itself.
```suggestion
inline float convert_temperature(uint16_t raw_temperature) {
```

2024-07-30 02:57 UTC, bakerkj commented on esphome/components/tem3200/tem3200.cpp
> +float TEM3200Component::convert_temperature_(uint16_t raw_temperature) {
fixed.

2024-10-02 03:49 UTC, jesserockz approved these changes

2024-10-02 03:50 UTC, jesserockz requested changes

2024-10-02 03:50 UTC, jesserockz commented on esphome/components/tem3200/tem3200.cpp
> +  ESP_LOGD(TAG, "Got pressure=%draw temperature=%.1f°C", raw_pressure, temperature);
```suggestion
  ESP_LOGD(TAG, "Got raw pressure=%d, temperature=%.1f°C", raw_pressure, temperature);
```

2024-10-03 00:11 UTC, jesserockz approved these changes

2024-10-04 02:27 UTC, bakerkj commented
@jesserockz thank you for your help and approvals. Is there anything else I need to do to merge this in?

2024-10-07 02:58 UTC, merged