Sntp
OttoWinter/esphomeyaml pull request #6871
Opened 2024-06-07 05:34 UTC by asergunov

# What does this implement/fix?

SNTP component for esp-idf builds.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/3123

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_LWIP_SNTP_MAX_SERVERS: '3' # Let it use all three servers

# wifi here

time:
  - platform: sntp
    id: sntp_time
    timezone: ${timezone}
    update_interval: 5min
    servers: 
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
    on_time_sync:
      then:
      - logger.log: "Synchronized"
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-10 06:24 UTC, asergunov commented
Could someone please help me with check failures. Code looks good for me. Am I missing something?

2024-06-10 06:25 UTC, asergunov commented on esphome/components/sntp/sntp_component.h
> +#if defined(USE_ESP_IDF)
```suggestion
#if !defined(USE_ESP_IDF)
```

2024-06-10 11:41 UTC, asergunov commented on esphome/components/sntp/sntp_component.cpp
>      sntp_stop();
```suggestion
#if defined(USE_ESP_IDF)
  if (esp_sntp_enabled()) {
    ESP_LOGD(TAG, "Force resync");
    sntp_restart();
#else
  if (sntp_enabled()) {
    sntp_stop();
```

2024-08-17 15:44 UTC, CarlosGS approved these changes
I confirm this PR works well and fixes NTP for the esp-idf platform.
Thank you very much @asergunov!

2024-08-18 12:03 UTC, CarlosGS requested changes
I've found a small problem where SNTP was being restarted every update interval.
Here are the suggested changes, open for comment as there are many ways to do this.
https://github.com/asergunov/esphome_esphome/pull/1

2024-08-19 05:30 UTC, asergunov commented on esphome/components/sntp/sntp_component.cpp
> +  this->stop_poller();
@CarlosGS here I stop any automatic update calls

2024-08-19 05:32 UTC, asergunov commented
> I've found a small problem where SNTP was being restarted every update interval.
> 
> Here are the suggested changes, open for comment as there are many ways to do this.
> 
> https://github.com/asergunov/esphome_esphome/pull/1

I disabling calling update function periodically. So user can call it to manually trigger update

2024-08-19 05:47 UTC, asergunov commented on esphome/components/sntp/sntp_component.cpp
> +  this->stop_poller();
Do you have an idea why this doesn't work?

2024-08-19 05:57 UTC, asergunov reviewed
Adding comments explaining update interval logic

2024-08-19 05:57 UTC, asergunov commented on esphome/components/sntp/sntp_component.cpp
> +void SNTPComponent::set_update_interval(uint32_t update_interval) {
```suggestion
/**
Sets the update interval calling `sntp_set_sync_interval()`.

Calls `sntp_restart()` if update interval is less then it was before as ESP IDF according documentation. Without this cal interval will be updated only after previously scheduled update.
*/
void SNTPComponent::set_update_interval(uint32_t update_interval) {
```

2024-08-19 05:57 UTC, asergunov commented on esphome/components/sntp/sntp_component.cpp
> +uint32_t SNTPComponent::get_update_interval() const { return sntp_get_sync_interval(); }
```suggestion
/**
Redirects the call to `sntp_get_sync_interval()` so it's only one source of truth.
*/
uint32_t SNTPComponent::get_update_interval() const { return sntp_get_sync_interval(); }
```

2024-08-19 05:57 UTC, asergunov commented on esphome/components/sntp/sntp_component.cpp
> +  this->stop_poller();
```suggestion
  // Stop the puller to prevent periodically update calls. IDF Handles periodic updates by itself.
  // The user still able to call `update` to trigger manual update.
  this->stop_poller();
```

2024-08-19 06:30 UTC, asergunov commented
@CarlosGS I've deferred the `stop_poller`call. Could you please retest if it helps?

2024-08-19 06:30 UTC, asergunov commented on esphome/components/sntp/sntp_component.cpp
> +  this->stop_poller();
I've deferred this call.

2024-08-19 11:21 UTC, CarlosGS commented
> The purpose to override get_update_interval is to report correct value in case user changed it directly with esp idf API. So there is an only one source of truth in the system.

Ah yes it makes sense. Better this way :+1:

> I've deferred the stop_pollercall. Could you please retest if it helps?

Nice, it just makes it run on the next loop, much cleaner than my approach.
And yep, now it works correctly in the background without restarting the ntp library :)

I hope this gets merged soon, thanks a lot!

2024-08-19 11:23 UTC, CarlosGS approved these changes

2025-10-06 01:57 UTC, asergunov commented
Keep open

2025-10-21 03:03 UTC, swoboda1337 commented
> Keep open

There are conflicts that need to be resolved in order for this to be reviewed.

2025-10-23 23:28 UTC, swoboda1337 requested changes
Need to fix conflicts

2025-10-25 09:10 UTC, asergunov commented
@CarlosGS Hi. I've resolved conflicts. Could you give it a test?

2025-10-25 14:49 UTC, CarlosGS approved these changes
All looks good and it seems to be working well.
Thanks for revisiting this! I hope it can be merged soon.
Cheers!

2025-10-25 16:25 UTC, asergunov commented
> All looks good and it seems to be working well.
> 
> Thanks for revisiting this! I hope it can be merged soon.
> 
> Cheers!

What board did you test? Esp32 or esp8266?

2025-10-26 09:09 UTC, CarlosGS commented
ESP32 C3 with IDF
<img width="539" height="126" alt="Screenshot_20251026_112735" src="https://github.com/user-attachments/assets/deff1ad2-2d7c-40ea-bcab-135a37c8816c" />

2025-10-27 02:52 UTC, asergunov commented
We need to check both esp32 and esp8266 in both Arduino and idf builds:
- changing sync period 
- manual sync
- callbacks in both sync cases

I have everything for that. Will try to check by tomorrow.

2025-11-16 14:47 UTC, cypherbits commented
And I was wondering why sntp wasn't working on esp-idf, now the recommended and default framework, lost almost 3 hours trying things, but no error messages. And just found this, that sntp is not working on esp-idf since years...

2025-11-19 02:49 UTC, asergunov commented
I have no time to test it after merging with latest dev branch and conflicts resolution. That's the only reason it's in draft. Could someone give it a test on different platforms?

The points to test:

- [ ] on_time_sync triggering (just put log message inside)
- [ ] Manual sync triggering with update function
- [ ] Changing the update interval
- [ ] Changing the server list runtime (not critical)

2025-11-27 05:39 UTC, asergunov commented
I've tested on esp32idf - all works

2025-11-27 06:03 UTC, bdraco commented on esphome/components/sntp/sntp_component.cpp
> -// The loop is used to infer whether we have valid time on platforms where we
why not sntp_set_time_sync_notification_cb on esp idf instead of loop ?

2025-11-27 06:04 UTC, bdraco commented on esphome/components/sntp/sntp_component.h
> +  void set_servers(const std::array<const char *, SNTP_SERVER_COUNT> &servers);
I'm not sure we want to support setting servers at runtime as it increases the complexity here.

This also gets very confusing since `SNTP_SERVER_COUNT` is defined from python codegen and can be 1, 2, or 3 based on what is in yaml

2025-11-27 06:06 UTC, bdraco commented on esphome/components/sntp/sntp_component.cpp
> +  esp_sntp_init();
esp_sntp_init is also called on line 24

2025-11-27 06:06 UTC, bdraco commented on esphome/components/sntp/sntp_component.cpp
> +  // Tah sntp_get_sync_status call returns SNTP_SYNC_STATUS_COMPLETED only once when time just synched. So we don't need
```suggestion
  // The sntp_get_sync_status call returns SNTP_SYNC_STATUS_COMPLETED only once when time just synched. So we don't need
```

2025-11-27 06:12 UTC, bdraco commented on esphome/components/sntp/sntp_component.cpp
> +  // any callbacks
The code is mixing `esp_sntp_*` vs `sntp_*` APIs.

 https://github.com/espressif/esp-idf/blob/master/components/lwip/include/apps/esp_sntp.h
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/lwip.html
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/system_time.html#system-time-sntp-sync

https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/system_time.html#sntp-time-synchronization

> Some lwIP APIs, including SNTP functions, are not thread safe, so it is recommended to use [esp_netif component](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/network/esp_netif.html) when interacting with SNTP module.

Seems like the `esp_` ones are preferred

2025-11-27 06:15 UTC, bdraco commented on esphome/components/sntp/sntp_component.cpp
> +    // Stop the puller to prevent periodically update calls. IDF Handles periodic updates by itself.
```suggestion
    // Stop the poller to prevent periodically update calls. IDF Handles periodic updates by itself.
```

2025-11-27 06:17 UTC, bdraco commented on esphome/components/sntp/sntp_component.cpp
> +  esp_sntp_set_sync_interval(time::RealTimeClock::get_update_interval());
line 23 uses `this->get_update_interval()` ... this is a bit confusing as to why one over the other. Each spot needs comments explaing the choice

2025-11-27 06:18 UTC, bdraco commented on esphome/components/sntp/sntp_component.cpp
> +    if (buff != nullptr && buff != esp_sntp_getservername(i)) {
pointer comparison may not be correct here. This might need to be `strcmp` like https://github.com/esphome/esphome/pull/6871/files#diff-aef5cc5434185d4f591b9df6f5be5ecb32ad1e089d3d52be9b2434885fe3888fR34

2025-11-27 06:18 UTC, bdraco commented on esphome/components/sntp/sntp_component.cpp
> +    if (buff != nullptr && buff != sntp_getservername(i)) {
pointer comparison may not be correct here. This might need to be `strcmp` like https://github.com/esphome/esphome/pull/6871/files#diff-aef5cc5434185d4f591b9df6f5be5ecb32ad1e089d3d52be9b2434885fe3888fR34

2025-11-27 06:22 UTC, bdraco commented on esphome/components/sntp/sntp_component.cpp
> +    this->stop_poller();
It would be cleaner to prevent it from ever starting than using a defer to stop it.


Maybe override `call_setup` and prevent it from starting on esp32

2025-11-27 06:22 UTC, bdraco requested changes
Please see review comments above. Thanks!

2026-03-05 00:55 UTC, closed without merging