Add DFRobot environmental sensor support (sen0501 and sen0500)
OttoWinter/esphomeyaml pull request #6889
Opened 2024-06-11 20:18 UTC by thetestspecimen

# What does this implement/fix?

Implements support for DFRobot's sen0501 and sen0500 environmental sensors

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#TBC

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
i2c:

sensor:
    - platform: sen0501
      temperature:
          name: "Temperature"
      humidity:
          name: "Humidity"
      uv_irradiance:
          name: "UV Irradiance"
      illuminance:
          name: "Ambient Light"
      pressure:
          name: "Atmospheric Pressure"
      elevation:
          name: "Elevation"
      update_interval: 10s

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-07 02:42 UTC, jesserockz requested changes

2024-10-07 02:42 UTC, jesserockz commented on esphome/components/sen0501/sen0501.cpp
> +}
We have this already, no need to reimplement

https://github.com/esphome/esphome/blob/81f6750211cd98a7595d0a6320cd4d7760e161ff/esphome/core/helpers.h#L153-L155

```suggestion
```

2024-10-07 02:42 UTC, jesserockz commented on esphome/components/sen0501/sen0501.cpp
> +  uint8_t buffer[2];
Need to return if the sensor is not defined by the user
```suggestion
  if (this->temperature_ == nullptr)
    return;
  uint8_t buffer[2];
```

2024-10-07 02:42 UTC, jesserockz commented on esphome/components/sen0501/sen0501.cpp
> +  data = buffer[0] << 8 | buffer[1];
All member variables and function calls should be prefixed with `this->`
We also have a helper for bitshift adding bytes together with casting.
Please apply these below too

```suggestion
  float temp;
  this->read_bytes(REG_TEMP, buffer, 2);
  uint16_t data = encode_uint16(buffer[0], buffer[1]);
```

2024-10-07 02:42 UTC, jesserockz commented on esphome/components/sen0501/sen0501.h
> +  void set_temperature(sensor::Sensor *temperature) { temperature_ = temperature; }
```suggestion
  void set_temperature(sensor::Sensor *temperature) { this->temperature_ = temperature; }
```

2024-10-07 21:46 UTC, jesserockz commented on esphome/components/sen0501/sen0501.cpp
>  }
This might need to be done differently so the user can have elevation, but doesnt need at pressure sensor configured.

2024-10-07 22:12 UTC, thetestspecimen commented on esphome/components/sen0501/sen0501.cpp
>  }
I have updated the logic in a new commit. Let me know if you think that is ok once the integration checks complete.

2024-10-08 01:41 UTC, jesserockz approved these changes

2024-10-08 03:26 UTC, jesserockz requested changes
I just actually read the note at the top of the docs 🤦 and realised it can use i2c or uart. 
Since this is the case, please rename this component to `sen0501_i2c` to allow for a future `sen0501_uart` if someone wishes to make it without breaking changes.

Mostly this just involves renaming the folders and namespaces

2024-10-08 19:27 UTC, thetestspecimen commented
> I just actually read the note at the top of the docs 🤦 and realised it can use i2c or uart. Since this is the case, please rename this component to `sen0501_i2c` to allow for a future `sen0501_uart` if someone wishes to make it without breaking changes.
> 
> Mostly this just involves renaming the folders and namespaces

No problem. Will get it done at some point this week (hopefully!)

2025-03-12 00:06 UTC, WestwardWinds commented
Hello,
I am wondering what still needs to be done to integrate support for the sens0500_i2c at this time? I'll admit I'm not the best at github but is this just sitting for review? I'd really like to incorporate this sensor into my HA uni project.

2025-03-12 21:37 UTC, thetestspecimen commented
> Hello, I am wondering what still needs to be done to integrate support for the sens0500_i2c at this time? I'll admit I'm not the best at github but is this just waiting for review? I'd really like to incorporate this sensor into my HA uni project.

As far as I am aware it is just waiting for review, yes.

If you really want to use the code you can, I use it already with my own project and it works fine. The only problem is that you will need to know how to utilise the code directly, which might be a bit difficult if you are not that familiar doing things like that.

2025-03-18 16:59 UTC, WestwardWinds commented
Yeah I might have to do that. I am just not familiar with doing so so I'll have to figure that out. Maybe getting new comments on this post will drive the process forward with @jesserockz. I noticed that the docs thread for this has been marked stale as well

2025-10-14 00:49 UTC, closed without merging