[nextion] Optionally skip connection handshake
OttoWinter/esphomeyaml pull request #6905
Opened 2024-06-13 12:33 UTC by edwardtfn

# What does this implement/fix?

This adds the possibility to set whether the Nextion display should skip the connection handshake process.
When skip_connection_handshake is true, the connection will be established without performing the handshake.
This can be useful when connecting to Nextion Simulator, as it won't performs the handshake process.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#2872

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3951

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
```yaml
display:
  - id: disp1
    platform: nextion
    uart_id: tf_uart
    skip_connection_handshake: true
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-13 21:04 UTC, jesserockz requested changes, later dismissed

2024-08-13 21:04 UTC, jesserockz commented on esphome/components/nextion/nextion.h
> +  }
This function seems redundant as this is a simple boolean flag.
```suggestion
```

2024-08-13 21:04 UTC, jesserockz commented on esphome/components/nextion/nextion_commands.cpp
> +void Nextion::set_skip_connection_handshake(bool skip_handshake) { this->skip_connection_handshake_ = skip_handshake; }
```suggestion
```

2024-08-13 21:04 UTC, jesserockz commented on esphome/components/nextion/nextion.h
> +  void set_skip_connection_handshake(bool skip_handshake);
```suggestion
  void set_skip_connection_handshake(bool skip_handshake) { this->skip_connection_handshake_ = skip_handshake; }
```

2024-08-13 21:04 UTC, jesserockz commented on esphome/components/nextion/nextion.cpp
> +    this->set_skip_connection_handshake(this->skip_connection_handshake_);
```suggestion
```

2024-08-13 21:04 UTC, jesserockz commented on esphome/components/nextion/display.py
> +        var.set_skip_connection_handshake_internal(
```suggestion
        var.set_skip_connection_handshake(
```

2024-08-14 09:07 UTC, edwardtfn commented on esphome/components/nextion/nextion.h
> +  }
Indeed, but it is in line with other similar function on this component. I'm fine about simplifying this, but then shouldn't we simplify all the other functions on this component? I'm fine about doing this in another PR later.

2024-08-14 09:11 UTC, jesserockz commented on esphome/components/nextion/nextion.h
> +  }
Yes, if it is only setting a variable, then it should not have a duplicate `_internal` function that does the same thing

2024-09-12 09:37 UTC, kbx81 approved these changes

2024-09-19 04:08 UTC, merged