Inherit `esp32_ble_beacon` from `esp32_ble`
OttoWinter/esphomeyaml pull request #6908
Opened 2024-06-13 21:38 UTC by jpbede

# What does this implement/fix?

Inherit the `esp32_ble_beacon` component from `esp32_ble` component, so the `esp32_ble_beacon` can be used along with `bluetooth_proxy` or something like that.

I hope the code fits, my C++ is a little bit older

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2689

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-14 00:43 UTC, jesserockz requested changes
To better make this non-conflicting, the code that builds and calls `esp_ble_gap_config_adv_data_raw` should be moved into the `esp32_ble` component files like we have for other advertising services so it can be managed in one place there.

2024-07-01 12:50 UTC, Rapsssito approved these changes

2024-07-02 07:07 UTC, jesserockz commented
Hi @jpbede,

I thought about what I proposed and today I came back to this and decided to make it even more modular so that other components can set the raw advertising data as they wish and they will all get turns based on the new `advertising_cycle_time`. 

Let me know what you think. 
I have tested this on a device with improv and beacon and saw it switching nicely via nRF connect on my Android phone.

2024-07-02 12:06 UTC, jpbede commented
This makes way more sense. Thanks for improving it further 👍

2024-07-22 04:20 UTC, jesserockz approved these changes

2024-07-22 04:20 UTC, merged