Update mitsubishi.cpp
OttoWinter/esphomeyaml pull request #6909
Opened 2024-06-15 11:15 UTC by ttaborda

Mitsubishi climate not showing current temperature (not reading sensor from homeassistant)

Changing this line works ok

2024-06-17 15:25 UTC, RubyBailey commented on esphome/components/mitsubishi/mitsubishi.cpp
> -  traits.set_supports_action(false);
Hello @ttaborda, Thank you for the PR. I don't use HA and so didn't know that was an issue; I now see that a number of people had reported this. 
I'm unsure why traits.set_supports_action(false); need to be removed for this to work?

2024-06-17 15:25 UTC, RubyBailey commented on esphome/components/mitsubishi/mitsubishi.cpp
> +  traits.set_supports_current_temperature(this->sensor_ != nullptr);
This seem fine, but I cannot test it with my system, using MQTT, at this time. I will be back there in a couple of weeks. Just unsure how (this->sensor_ != nullptr) evaluates to True within HA and what effect it may have with systems that use MQTT.

2024-06-22 15:52 UTC, RubyBailey commented
Hello @ttaborda, Thought I’d check to see if you had an opportunity to look at my comments?

2024-06-22 16:02 UTC, ttaborda commented on esphome/components/mitsubishi/mitsubishi.cpp
> +  traits.set_supports_current_temperature(this->sensor_ != nullptr);
Checked your comments but i cant really help you out. It works on HA if you edit as i said.

Im not a programmer.. 

On esphome before there was an options to add a sensor (on the Mitsubishi climate) and now its missing.

It really sucks not to have the temperature on HA.

Thanks

2024-06-22 16:31 UTC, RubyBailey commented on esphome/components/mitsubishi/mitsubishi.cpp
> +  traits.set_supports_current_temperature(this->sensor_ != nullptr);
I agree that we need to fix this issue. Would you please test something? I don’t use HA and cannot test this. 

Please restore the line that you deleted in your PR, then test that code and let me know if you still see the sensor temperature. I think the added line may be the only change required. Thanks.

2024-06-22 16:53 UTC, ttaborda commented on esphome/components/mitsubishi/mitsubishi.cpp
> +  traits.set_supports_current_temperature(this->sensor_ != nullptr);
It does work thanks!!

2024-06-22 17:48 UTC, RubyBailey commented on esphome/components/mitsubishi/mitsubishi.cpp
> +  traits.set_supports_current_temperature(this->sensor_ != nullptr);
Thanks for testing that, that’s great. Please now update this PR with that change. Thanks.

2024-06-22 17:55 UTC, ttaborda commented
Perfect

2024-06-23 01:13 UTC, RubyBailey commented
Hello @ttaborda, Why did you close this PR?

2024-06-23 01:34 UTC, ttaborda commented
I thought you said so, sorry

2024-06-23 01:55 UTC, RubyBailey commented
Sorry about the confusion. Just upload the revised file, without the deleted line, to the PR. Thanks

2024-06-23 20:08 UTC, jesserockz requested changes

2024-06-23 20:08 UTC, jesserockz commented on esphome/components/mitsubishi/mitsubishi.cpp
> -  traits.set_supports_action(false);
Yes this line should not be removed

2024-06-27 15:00 UTC, RubyBailey commented
Hello @ttaborda, the PR needs to be updated per comments above, ie add the deleted line back into the file, and then indicate that the change has been completed. Otherwise it will not be merged into esphome.

2024-07-11 04:23 UTC, jesserockz approved these changes

2024-07-11 04:26 UTC, merged