Fix garbled graphics on LILYGO T4-S3 display
OttoWinter/esphomeyaml pull request #6910
Opened 2024-06-15 19:09 UTC by manuelkasper

# What does this implement/fix?

On my LILYGO T4-S3, shapes drawn on the display often become garbled, with each consecutive line shifted to the left (see photo, generated by the config.yaml below).

The issue seems to be that the `qspi_amoled` driver does not honor the restriction of the RM690B0 and RM67162 that the x/y start coordinates and width/height set using CASET/RASET must be divisible by 2 according to the datasheet.

My patch grows the update "window" as necessary to get even values.

<img src="https://github.com/esphome/esphome/assets/496413/ea1d594b-b234-42be-a252-9c417a6c9a6d" width="250">

Note: I don't have a LILYGO T-Display S3 AMOLED (RM67162) to test with.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
display:
  - platform: qspi_amoled
    id: amoled_display
    model: RM690B0
    data_rate: 80MHz
    dimensions:
      width: 450
      height: 600
      offset_width: 16
    color_order: rgb
    invert_colors: false
    brightness: 255
    cs_pin: 11
    reset_pin: 13
    enable_pin: 9
    update_interval: 5s
    auto_clear_enabled: false
    lambda: |-
      it.clear();
      auto red = Color(255, 0, 0);
      auto green = Color(0, 255, 0);
      auto blue = Color(0, 0, 255);
      it.filled_circle(100, 110, 50, red);
      it.filled_circle(100, 220, 50, green);
      it.filled_circle(100, 330, 50, blue);

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-15 22:36 UTC, clydebarrow commented on esphome/components/qspi_amoled/qspi_amoled.cpp
> +  if (this->x_high_ % 2 == 0 && this->x_high_ < this->get_width_internal() - 1) {
No need to check the upper bound here as it is clamped in `draw_absolute_pixel_internal()` anyway. Same for the y co-ordinate (if it _was_ necessary here, it would also be necessary for the lower bound.) Otherwise looks good.

2024-06-17 09:36 UTC, manuelkasper commented on esphome/components/qspi_amoled/qspi_amoled.cpp
> +  if (this->x_high_ % 2 == 0 && this->x_high_ < this->get_width_internal() - 1) {
> No need to check the upper bound here as it is clamped in `draw_absolute_pixel_internal()` anyway.

We're potentially incrementing `x_high_`/`y_high_` after `draw_absolute_pixel_internal()` has done its checks. However, in the usual case that the display width/height are even, the highest "high" value encountered will be odd, so no increment will take place. I still thought it would be prudent to avoid an out-of-bounds situation, but have now removed this check, and instead added a check that the display width/height are even in the config validation, for good measure.

> and if it _was_ necessary here, it would also be necessary for the lower bound.

Since we're only decrementing x_low_/y_low_ if it's uneven, there's no risk of decrementing below 0.

2024-06-17 15:25 UTC, clydebarrow commented on esphome/components/qspi_amoled/qspi_amoled.cpp
> +  if (this->x_high_ % 2 == 0 && this->x_high_ < this->get_width_internal() - 1) {
The point about the lower bound was that it's not required _only_ because it's already limited in `draw_absolute_pixel()`, just like the upper bound. If those checks weren't done there, then you have to check both before setting the draw window, but because they are, you don't need to check either.

Good point about enforcing even dimensions - you also need to check that `offset_width` and `offset_height` are even.

2024-06-17 16:28 UTC, clydebarrow requested changes

2024-06-17 16:28 UTC, clydebarrow commented on esphome/components/qspi_amoled/display.py
> +    if value % 2 != 0:
Also should check that these values are positive - and can then simplify the validation in the schema to just `validate_dimension` rather than the `cv.All( ...`
```suggestion
    value = cv.positive_int(value)
    if value % 2 != 0:
```

2024-06-17 20:12 UTC, clydebarrow approved these changes

2024-06-18 18:59 UTC, clydebarrow commented
If this is good to go, mark it ready for review.

2024-06-18 19:40 UTC, manuelkasper commented
Sorry, I got sidetracked by another issue with the initial screen never showing if `update()` is called before the `setTimeout()` calls in `setup()` have fired. But that is a different story and somewhat dependant on my particular setup. I'll investigate some more and file a separate PR if necessary. So yes, this change is good to go.

2024-06-18 19:53 UTC, merged