UAERT component support added for host platform
OttoWinter/esphomeyaml pull request #6912
Opened 2024-06-16 11:48 UTC by paveldn

# What does this implement/fix?

Support for UART component for host platform (Linux only)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
uart:
  id: ${uart_id}
  baud_rate: 9600
  name: "/dev/ttyUSB0"
  debug:
    direction: BOTH
    dummy_receiver: true
    after:
      delimiter: "\n"
    sequence:
      - lambda: |-
          id(${uart_id}).write_array(&bytes[0], bytes.size());
          UARTDebug::log_hex(uart::UART_DIRECTION_RX, bytes, ' ');

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-16 20:01 UTC, jesserockz requested changes

2024-06-16 20:01 UTC, jesserockz commented on esphome/components/uart/__init__.py
> +            cv.Optional(CONF_NAME): cv.string_strict,
`name` could be confusing here, maybe `port` instead?
And you can also use `cv.file_` to ensure it exists at validation time
```suggestion
            cv.Optional(CONF_PORT): cv.All(cv.file_, cv.only_on(PLATFORM_HOST)),
```

2024-06-16 20:01 UTC, jesserockz commented on esphome/components/uart/__init__.py
> +    return config
With the changes to the field itself, this can be thinned out. 

The `else` is no longer required because of `only_on()`, and the `if CONF_NAME not in config:` will never be reached because of `cv.has_at_least_one_key`

Technically we could put `cv.only_on` on the TX/RX fields to, but that could get messy.

```suggestion
def validate_port_name(config):
    if CORE.is_host:
        if CONF_TX_PIN in config or CONF_RX_PIN in config:
            raise cv.Invalid(
                "TX and RX pins are not supported for UART on host platform."
            )
    return config
```

2024-06-16 20:01 UTC, jesserockz commented on esphome/components/uart/__init__.py
> +    str(HostUartComponent),
This list is only used to validate tx/rx pins, and is not needed to add here.
```suggestion
```

2024-06-16 20:01 UTC, jesserockz commented on esphome/components/uart/uart_component_host.cpp
> +  }
These should also mark the component as failed. `this->mark_failed()`

2024-06-16 20:01 UTC, jesserockz commented on esphome/components/uart/uart_component_host.cpp
> +  if (read(this->file_descriptor_, &data, 1) != 1) {
For consistency should this (and any other native calls) be `::read`?

2024-06-16 22:06 UTC, jesserockz commented on esphome/components/uart/__init__.py
> +    if not re.match(r"^\/dev\/(?:(?:tty(?:S|USB)|pts\/)\d+)$", value):
This does not cover ttyACMx devices

2024-06-17 05:09 UTC, paveldn commented on esphome/components/uart/__init__.py
> +    if not re.match(r"^\/dev\/(?:(?:tty(?:S|USB)|pts\/)\d+)$", value):
Thanks. Completely forgot about them. I will fix it.

2024-06-17 09:33 UTC, clydebarrow commented
Any reason this wouldn't work on MacOS?

2024-06-17 10:06 UTC, jesserockz commented
I would say test it out and if it does, no reason to exclude it.
I personally don't have access to a Mac.

2024-06-17 10:35 UTC, paveldn commented
@clydebarrow  Same situation for me, I don't have a way to test it on Mac. Theoretically, the only thing that is blocking it for MAC is `#ifndef __linux__` in uart_component_host.cpp. If you will test it let me know how it goes.

2024-06-17 14:39 UTC, clydebarrow commented
I use a Mac but am travelling right now, so won't be able to test for a few weeks.

2024-06-17 22:33 UTC, paravoid reviewed
Thanks for working on this! I had just started to implement this and have a draft branch in my checkout that I will now happily delete :laughing:

Shouldn't `final_validate_device_schema` also be adjusted to validate the port?

Also, it should probably skip validating the pins, as well as require_tx/require_rx, as ttys are implicitly read/write (assuming both of their underlying serial pins are wired). Basically it'd be great to be able to use the few integrations that use `final_validate_device_schema` without modifying them.

2024-06-18 05:24 UTC, paveldn commented
@paravoid 
Thanks. If I knew somebody working on this I wouldn't start it myself 😆. This functionality is important for me because it will allow me to do some basic tests for my component without hardware at all.  As for your remarks, you are completely right I will adjust my code.  I think require_tx/require_rx part is already covered because the HostUartComponent not in NATIVE_UART_CLASSES array. All other things I will implement. Thanks for help!

2024-06-18 07:01 UTC, paveldn commented
@paravoid, @jesserockz  I don't think I need to change something in final_validate_device_schema. Because HostUartComponent is not in NATIVE_UART_CLASSES require_tx/require_rx ignored, you can use components that require them without any problem. I tried to build a config with a couple of them (jsn_sr04t, cse7761) and it worked. I added baud rate validation but everything else looks OK. Let me know if you think something else should be adjusted. Thanks.

2024-06-18 08:12 UTC, jesserockz commented
Yes correct, the pins are only validated on the native MCU uart types. This was added previously for the weikei uart expanders.

2024-06-18 08:14 UTC, jesserockz commented on esphome/components/uart/__init__.py
> +        if CORE.is_host:
This is already inside a `is_host` block

2024-06-18 08:16 UTC, jesserockz requested changes

2024-06-18 08:16 UTC, jesserockz commented on esphome/components/uart/__init__.py
> +            ]
Please put this outside the validator as HOST_BAUD_RATES

2024-06-18 08:16 UTC, jesserockz commented on esphome/components/uart/__init__.py
> +                )
As baud is required, it will always be there
```suggestion
            if config[CONF_BAUD_RATE] not in HOST_BAUD_RATES):
                raise cv.Invalid(
                    f"Host platform doesn't support baud rate {config[CONF_BAUD_RATE]}", 
                    path=CONF_BAUD_RATE,
                )
```

2024-06-18 08:41 UTC, paravoid commented
> @paravoid, @jesserockz I don't think I need to change something in final_validate_device_schema. Because HostUartComponent is not in NATIVE_UART_CLASSES require_tx/require_rx ignored, you can use components that require them without any problem. I tried to build a config with a couple of them (jsn_sr04t, cse7761) and it worked. I added baud rate validation but everything else looks OK. Let me know if you think something else should be adjusted. Thanks.

Ah, I hadn't realized that. Thanks so much for looking into it and my apologies for pointing you to the wrong direction!

2024-06-28 06:55 UTC, nagyrobi commented
@paveldn any docs update for this?

2024-06-28 08:35 UTC, paveldn commented
> @paveldn any docs update for this?

Potentially there can be some documentation update but should we do it? I will need to add a port option description for the UART component that will be valid only for the host platform and I suppose UART for the host shouldn't be used for some "production" units just by developers for testing purposes. So I am afraid updating documentation can confuse other customers trying to configure their devices. 
What is your opinion? Should I update the documentation?

2024-06-28 08:39 UTC, nagyrobi commented
A PR for the doc is needed, we can all collaborate on the arrangement and wording, and only merge it when it's appropriate enough. Since `host` platform is already merged and available to anyone (certainly it's an advanced thing, but that's obvious), it's trivial to prepare documentation for this feature too.

2024-06-28 09:25 UTC, paveldn commented
@nagyrobi  OK Will prepare PR for doc changes

2024-06-28 11:11 UTC, paveldn commented
@nagyrobi Done. Can you please check it? https://github.com/esphome/esphome-docs/pull/4004

2024-07-01 06:46 UTC, nagyrobi commented
Here's my use case for this component: https://github.com/hn/linkplay-a31

2024-07-01 07:03 UTC, clydebarrow requested changes

2024-07-01 07:03 UTC, clydebarrow commented on esphome/components/uart/__init__.py
> +    if not re.match(r"^\/dev\/(?:(?:tty(?:S|USB|ACM)|pts\/)\d+)$", value):
I'd suggest just checking that the path starts with `/dev/tty` or `/dev/cu` - the remainder of the device name is going to be driver dependent.

2024-07-01 12:16 UTC, paveldn commented on esphome/components/uart/__init__.py
> +    if not re.match(r"^\/dev\/(?:(?:tty(?:S|USB|ACM)|pts\/)\d+)$", value):
Good point. Implemented.

2024-07-02 01:57 UTC, jesserockz commented on esphome/components/uart/__init__.py
> +    if not re.match(r"^\/dev\/(?:(?:tty(?:S|USB|ACM)|pts\/)\d+)$", value):
Even that can be too restrictive sometimes. I personally map certain device ids to named ports eg `/dev/buspirate` :skull_and_crossbones: 
It might make it more flexible in the long term if someone was to have an ESPHome binary running and wanted a consistent port name that could survive reboots, replugs etc.

2024-07-02 07:13 UTC, paravoid commented on esphome/components/uart/__init__.py
> +    if not re.match(r"^\/dev\/(?:(?:tty(?:S|USB|ACM)|pts\/)\d+)$", value):
+1 to this, but to add to it, I find even /dev/ to be restrictive. One can create PTYs on their /tmp, or $HOME etc.A use case could be to e.g. create a program to speak the MCU side of a UART protocol (i.e. an emulator), and point ESPHome to this PTY for local development. Or in simpler terms, use socat to bridge a PTY with a TCP/IP socket.

2024-07-02 07:20 UTC, paveldn commented on esphome/components/uart/__init__.py
> +    if not re.match(r"^\/dev\/(?:(?:tty(?:S|USB|ACM)|pts\/)\d+)$", value):
OK. I am not against it. Different people have different use cases. Personally, I want to use UART host implementation to have a way to easily debug when developing my Haier AC component using socat. 
So @paravoid what would be your suggestion? Do not validate the port name at all?

2024-07-02 09:25 UTC, clydebarrow commented on esphome/components/uart/__init__.py
> +    if not re.match(r"^\/dev\/(?:(?:tty(?:S|USB|ACM)|pts\/)\d+)$", value):
Yeah, sure. It will fail at run time if invalid which since it's on a host will be pretty obvious.

2024-07-02 10:03 UTC, paveldn commented on esphome/components/uart/__init__.py
> +    if not re.match(r"^\/dev\/(?:(?:tty(?:S|USB|ACM)|pts\/)\d+)$", value):
OK Maybe we can agree on something like this 
^\/(?:[\w\s.-]+\/)*[\w\s.-]+$
Which will just check if the path is a proper Linux path without other restrictions?

2024-07-02 12:55 UTC, clydebarrow commented on esphome/components/uart/__init__.py
> +    if not re.match(r"^\/dev\/(?:(?:tty(?:S|USB|ACM)|pts\/)\d+)$", value):
The ?: is unnecessary since you don't care if the group is capturing or not. That also restricts the allowable characters more than the Linux FS does - is there a good rationale for that? `^/.*[^/]$` should be sufficient - ensures it's absolute and doesn't end with /.

2024-07-02 13:13 UTC, paveldn commented on esphome/components/uart/__init__.py
> +    if not re.match(r"^\/dev\/(?:(?:tty(?:S|USB|ACM)|pts\/)\d+)$", value):
OK. Will do it with [^/] but I will keep mine ?: I prefer to do it the right way even if it doesn't matter.

2024-07-04 14:37 UTC, clydebarrow approved these changes

2024-07-04 16:37 UTC, nagyrobi commented
Next thing to add would be something like ha's [shell_command](https://www.home-assistant.io/integrations/shell_command/)...

To be able to run linux commands from ESPHome triggers...

2024-07-04 18:13 UTC, paveldn commented
> Next thing to add would be something like ha's [shell_command](https://www.home-assistant.io/integrations/shell_command/)...
> 
> To be able to run linux commands from ESPHome triggers...

Personally for me running bash scripts as a part of ESPHome is already too much. There are enough ways to have automation on Linux and it is too different from ESP platforms. For me, the best feature of the host platform is to run the same code that running on ESP for debugging and testing. But of course, everybody can have their own use cases and ways to use ESPHome.

2024-07-05 05:24 UTC, paveldn commented
@jesserockz  Is there something else I need to do here? I would really like to see it in the next release.

2024-07-06 07:40 UTC, jesserockz approved these changes

2024-07-11 01:30 UTC, merged