Haier minor changes
OttoWinter/esphomeyaml pull request #6949
Opened 2024-06-20 12:28 UTC by dudanov

# What does this implement/fix?

Some minor code improvements. `haier_id` is now auto-assigned and optional.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Before
sensor:
  - platform: haier
    haier_id: haier_climate
    compressor_current:
      name: Compressor Current

# After
sensor:
  - platform: haier
    compressor_current:
      name: Compressor Current
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-20 20:52 UTC, paveldn approved these changes
Looks OK to me. I  tested this PR and it works fine. Thank you for checking this.

2024-06-23 21:43 UTC, jesserockz requested changes
Looks good, just a small note/change on the test files

2024-06-23 21:43 UTC, jesserockz commented on tests/components/haier/test.esp32-ard.yaml
> -    haier_id: haier_ac
I would prefer that some of these stay to confirm that the config item is not changed/broken in the future.

2024-06-24 06:20 UTC, jesserockz approved these changes

2024-06-24 06:22 UTC, merged