[http_request] Get chunked content length and add some logs
OttoWinter/esphomeyaml pull request #6953
Opened 2024-06-21 02:34 UTC by jesserockz

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-21 02:42 UTC, kbx81 approved these changes

2024-06-21 03:18 UTC, kbx81 requested changes

2024-06-21 03:18 UTC, kbx81 commented on esphome/components/http_request/http_request_idf.cpp
> +  ESP_LOGV(TAG, "HTTP Request body written: %" PRId32, body_len);
```suggestion
  ESP_LOGV(TAG, "HTTP Request body written: %d", body_len);
```

2024-06-21 03:18 UTC, kbx81 commented on esphome/components/http_request/http_request_idf.cpp
> +  ESP_LOGD(TAG, "Status %" PRId32, status_code);
```suggestion
  ESP_LOGD(TAG, "Status %d", status_code);
```

2024-06-21 03:18 UTC, kbx81 commented on esphome/components/http_request/http_request_idf.cpp
> +  ESP_LOGV(TAG, "HTTP Request ended: %" PRId32, this->status_code);
```suggestion
  ESP_LOGV(TAG, "HTTP Request ended: %d", this->status_code);
```

2024-06-21 03:18 UTC, kbx81 approved these changes, later dismissed

2024-06-21 03:50 UTC, kbx81 approved these changes

2024-06-26 07:16 UTC, andrewjswan commented
How about Arduino framework?

2024-07-03 08:21 UTC, andrewjswan commented
Any news or maybe milestone for this PR?

2024-07-03 16:11 UTC, andrewjswan commented
Tested this PR with ESP IDF and got the content of the response (body) to the request (there was no response before).
```
[19:10:59][D][esp-idf:000][shadow]: I (184159) HTTP_CLIENT: Body received in fetch header state, 0x3ffd8761, 32
[19:10:59][D][http_request.idf:131][shadow]: Status 200
[19:10:59][D][SvitloBot:098][shadow]: Response: 200 (1079ms): [32]: Accepted request from...
```

2024-07-04 10:21 UTC, andrewjswan commented
https://github.com/esp8266/Arduino/blob/7e0d20e2b9034994f573a236364e0aef17fd66de/libraries/ESP8266HTTPClient/examples/StreamHttpsClient/StreamHttpsClient.ino#L68-L89

2024-07-04 20:04 UTC, jesserockz commented
Hi @andrewjswan I still need to come back to this PR when I get some time.

2024-07-05 08:23 UTC, andrewjswan commented
Hi @jesserockz , I also try to make changes for the Arduino framework from time to time, but the example uses a static buffer size, not a dynamic one as used in the integration. It is probably possible to change it, but I have not yet figured out how to fit it nicely into a single Arduino and ESP-IDF code.

2024-07-22 08:06 UTC, andrewjswan commented
I noticed that if the resource is unavailable (due to hosting problems due to CrowdStrike), then the regular component returns -1 and TimeOut, or error 500, and if I use this one from PR, then the ESP simply reboots, without additional information in the logs.

2024-10-18 15:59 UTC, andrewjswan commented
Hi @jesserockz There is no time yet? Maybe there is a rough idea in which version to expect the fix?

2025-10-14 00:49 UTC, closed without merging