New distance and SNR sensors for DFRobot sen0395
OttoWinter/esphomeyaml pull request #6977
Opened 2024-06-24 08:52 UTC by robin-thoni

# What does this implement/fix?

This adds new sensors for the DFRobot mmwave sensor to get the distance and SNR (Signal to Noise Ratio) to the up to 9 tracked targets.

![image](https://github.com/esphome/esphome/assets/9640353/93017b80-1f2e-4c95-8770-95a916eb24f4)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3997

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: dfrobot_sen0395
    id: mmwave_1_target_1_dist
    name: mmWave target 1 distance
    dfrobot_sen0395_id: mmwave_1
    type: distance
    target: 1
  - platform: dfrobot_sen0395
    id: mmwave_1_target_1_snr
    name: mmWave target 1 snr
    dfrobot_sen0395_id: mmwave_1
    type: SNR
    target: 1
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-04 15:19 UTC, niklasweber commented
Hi @robin-thoni, thanks for the contribution!
Do you know, if the dfrobot mmwave radar has different revisions / firmware versions?
I am not aware of this feature and my sensors don't send $JYRPO messages. The sensor values always stay unknown and nan is published every second. Is it possible to only send a value on change? Do I need to send some command to activate the distance and SNR values? Does your sensor send it by default?
![log](https://github.com/esphome/esphome/assets/11338893/9398f140-dc72-4342-84d3-263395467743)

2024-07-04 15:46 UTC, robin-thoni commented
Ah, you need to turn on the presence switch to activate that feature, otherwise, the device will stay in its default config, where it just sends the binary information. I added this my config:
```yaml
esphome:
  on_boot: 
    - priority: -200
      then:
        - switch.turn_on: office_presence_sensor_active
        - switch.turn_on: office_presence_via_uart

switch:
  - platform: dfrobot_sen0395
    dfrobot_sen0395_id: mmwave_1
    type: sensor_active
    name: Présence Capteur Actif
    id: office_presence_sensor_active
  - platform: dfrobot_sen0395
    dfrobot_sen0395_id: mmwave_1
    type: presence_via_uart
    name: Présence UART Actif
    id: office_presence_via_uart
```
I should add this to the doc

2024-07-04 16:22 UTC, niklasweber commented
I already activated the sensor and uart output, but I still don't get any $JYRPO messages. Only "$JYBSS,0, , , *\r\n". Can you activate serial debug output and post your sensor output? You can activate it by adding debug to the uart block
```
uart:
  tx_pin: 14
  rx_pin: 27
  baud_rate: 115200
  debug:
    sequence:
      - lambda: UARTDebug::log_string(direction, bytes);
```
Also it is discouraged to run the commands on every boot. Any setting is saved to the internal eeprom of the sensor. You should only set settings by hand to avoid breaking the eeprom because of too many writes. Changing settings once is fine, as they will survive power cycles.

I only get the JYBSS messages periodically:
```
[16:20:33][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
[16:20:34][D][sensor:094]: 'mmWave target 1 distance': Sending state nan m with 2 decimals of accuracy
[16:20:34][D][sensor:094]: 'mmWave target 1 snr': Sending state nan  with 2 decimals of accuracy
[16:20:34][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
[16:20:35][D][sensor:094]: 'mmWave target 1 distance': Sending state nan m with 2 decimals of accuracy
[16:20:35][D][sensor:094]: 'mmWave target 1 snr': Sending state nan  with 2 decimals of accuracy
[16:20:35][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
[16:20:36][D][sensor:094]: 'mmWave target 1 distance': Sending state nan m with 2 decimals of accuracy
[16:20:36][D][sensor:094]: 'mmWave target 1 snr': Sending state nan  with 2 decimals of accuracy
[16:20:36][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
[16:20:37][D][sensor:094]: 'mmWave target 1 distance': Sending state nan m with 2 decimals of accuracy
[16:20:37][D][sensor:094]: 'mmWave target 1 snr': Sending state nan  with 2 decimals of accuracy
[16:20:37][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
[16:20:38][D][sensor:094]: 'mmWave target 1 distance': Sending state nan m with 2 decimals of accuracy
[16:20:38][D][sensor:094]: 'mmWave target 1 snr': Sending state nan  with 2 decimals of accuracy
[16:20:38][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
[16:20:39][D][sensor:094]: 'mmWave target 1 distance': Sending state nan m with 2 decimals of accuracy
[16:20:39][D][sensor:094]: 'mmWave target 1 snr': Sending state nan  with 2 decimals of accuracy
[16:20:39][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
```

2024-07-04 18:37 UTC, robin-thoni commented
I can not try it right now. Have you tried disabling both the switches, and re-enabling them?

I didn't realized turning those on/off would save the setting, thanks for the tip!

2024-07-06 17:08 UTC, robin-thoni commented
This is what I have:
```
[19:07:37][D][sensor:094]: 'mmWave target 1 distance': Sending state nan m with 2 decimals of accuracy
[19:07:37][D][sensor:094]: 'mmWave target 1 snr': Sending state nan  with 2 decimals of accuracy
[19:07:37][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
[19:07:38][D][sensor:094]: 'mmWave target 1 distance': Sending state nan m with 2 decimals of accuracy
[19:07:38][D][sensor:094]: 'mmWave target 1 snr': Sending state nan  with 2 decimals of accuracy
[19:07:38][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
[19:07:39][D][sensor:094]: 'mmWave target 1 distance': Sending state nan m with 2 decimals of accuracy
[19:07:39][D][sensor:094]: 'mmWave target 1 snr': Sending state nan  with 2 decimals of accuracy
[19:07:39][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
[19:07:40][D][sensor:094]: 'mmWave target 1 distance': Sending state nan m with 2 decimals of accuracy
[19:07:40][D][sensor:094]: 'mmWave target 1 snr': Sending state nan  with 2 decimals of accuracy
[19:07:40][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
[19:07:41][D][sensor:094]: 'mmWave target 1 distance': Sending state nan m with 2 decimals of accuracy
[19:07:41][D][sensor:094]: 'mmWave target 1 snr': Sending state nan  with 2 decimals of accuracy
[19:07:41][D][uart_debug:158]: <<< "$JYBSS,0, , , *\r\n"
[19:07:42][D][binary_sensor:036]: 'Presence Detected via UART': Sending state ON
[19:07:42][D][uart_debug:158]: <<< "$JYBSS,1, , , *\r\n"
[19:07:43][D][uart_debug:158]: <<< "$JYBSS,1, , , *\r\n"
[19:07:44][D][sensor:094]: 'mmWave target 1 distance': Sending state 0.46900 m with 2 decimals of accuracy
[19:07:44][D][sensor:094]: 'mmWave target 1 snr': Sending state 13.59400  with 2 decimals of accuracy
[19:07:44][D][uart_debug:158]: <<< "$JYRPO,6,1,0.469, ,13.594, , *\r\n$JYRPO,6,2,1.156, ,1.313, , *\r\n$JYRPO,6,3,2.156, ,12.969, , *\r\n$JYRPO,6,4,3.516, ,1.844, , *\r\n$JYRPO,6,5,3.820, ,1.969"
[19:07:44][D][uart_debug:158]: <<< ", , *\r\n$JYRPO,6,6,4.992, ,1.438, , *\r\n$JYBSS,1, , , *\r\n"
[19:07:45][D][sensor:094]: 'mmWave target 1 distance': Sending state 0.46100 m with 2 decimals of accuracy
[19:07:45][D][sensor:094]: 'mmWave target 1 snr': Sending state 10.25000  with 2 decimals of accuracy
[19:07:45][D][uart_debug:158]: <<< "$JYRPO,6,1,0.461, ,10.250, , *\r\n$JYRPO,6,2,1.164, ,1.156, , *\r\n$JYRPO,6,3,2.172, ,13.469, , *\r\n$JYRPO,6,4,3.586, ,2.094, , *\r\n$JYRPO,6,5,4.063, ,1.875"
[19:07:45][D][uart_debug:158]: <<< ", , *\r\n$JYRPO,6,6,4.984, ,1.188, , *\r\n$JYBSS,1, , , *\r\n"
[19:07:46][D][sensor:094]: 'mmWave target 1 distance': Sending state 0.45300 m with 2 decimals of accuracy
[19:07:46][D][sensor:094]: 'mmWave target 1 snr': Sending state 8.43800  with 2 decimals of accuracy
[19:07:46][D][uart_debug:158]: <<< "$JYRPO,6,1,0.453, ,8.438, , *\r\n$JYRPO,6,2,1.203, ,1.000, , *\r\n$JYRPO,6,3,2.148, ,14.500, , *\r\n$JYRPO,6,4,3.602, ,1.781, , *\r\n$JYRPO,6,5,4.133, ,1.625,"
[19:07:46][D][uart_debug:158]: <<< " , *\r\n$JYRPO,6,6,4.859, ,0.938, , *\r\n$JYBSS,1, , , *\r\n"
[19:07:47][D][sensor:094]: 'mmWave target 1 distance': Sending state 0.44500 m with 2 decimals of accuracy
[19:07:47][D][sensor:094]: 'mmWave target 1 snr': Sending state 6.75000  with 2 decimals of accuracy
[19:07:47][D][uart_debug:158]: <<< "$JYRPO,6,1,0.445, ,6.750, , *\r\n$JYRPO,6,2,1.227, ,1.063, , *\r\n$JYRPO,6,3,2.148, ,12.406, , *\r\n$JYRPO,6,4,3.625, ,1.688, , *\r\n$JYRPO,6,5,4.141, ,1.813,"
```

2024-07-06 17:11 UTC, robin-thoni commented
Both my modules have `24GHz Millimeter Wave Radar V1.0` printed on them. Not aware of any firmware upgrade on those.

2024-07-07 11:25 UTC, niklasweber requested changes
Looks good so far except for some minor details. Unfortunately I can't test the distance and SNR functionality. My sensors don't output the $JYRPO info. I can't figure out why yet.

2024-07-07 11:25 UTC, niklasweber commented on esphome/components/dfrobot_sen0395/automation.h
> +        this->parent_->enqueue(make_unique<UartOutputCommand>(2, val));
In the everything-presence-one config "setUartOutput 2 1 1 1" is used. Maybe also set the auto_update and interval parameters as well?

2024-07-07 11:25 UTC, niklasweber commented on esphome/components/dfrobot_sen0395/automation.h
>          this->parent_->enqueue(make_unique<UartOutputCommand>(val));
This line can be removed. You are overwriting it in the next line anyways.

2024-07-07 11:25 UTC, niklasweber commented on esphome/components/dfrobot_sen0395/switch/dfrobot_sen0395_switch.cpp
>    this->parent_->enqueue(make_unique<UartOutputCommand>(state));
Same as above. I think this line can be removed.

2024-07-07 11:25 UTC, niklasweber commented on esphome/components/dfrobot_sen0395/switch/dfrobot_sen0395_switch.cpp
> +  this->parent_->enqueue(make_unique<UartOutputCommand>(2, state));
Same as above. Maybe also set the auto_update and interval parameters as well.

2024-07-07 11:29 UTC, niklasweber commented
> Both my modules have `24GHz Millimeter Wave Radar V1.0` printed on them. Not aware of any firmware upgrade on those.

Same on mine. I thought the setUartOutput Command changes something (I set it to mode 1 before, but mode 2 changes nothing). I have a feeling we have a different firmware on the sensors. That would be a bummer. I also want to use the feature you  added.

2024-07-07 12:42 UTC, robin-thoni commented on esphome/components/dfrobot_sen0395/automation.h
> +        this->parent_->enqueue(make_unique<UartOutputCommand>(2, val));
According to my tests, we lose the presence binary sensor if we do not also send `setUartOutput 1`

2024-07-07 12:42 UTC, robin-thoni commented on esphome/components/dfrobot_sen0395/automation.h
>          this->parent_->enqueue(make_unique<UartOutputCommand>(val));
According to my tests, we lose the presence binary sensor if we do not also send `setUartOutput 1`

2024-07-07 12:42 UTC, robin-thoni commented on esphome/components/dfrobot_sen0395/switch/dfrobot_sen0395_switch.cpp
> +  this->parent_->enqueue(make_unique<UartOutputCommand>(2, state));
See my answer above

2024-07-07 12:44 UTC, robin-thoni commented on esphome/components/dfrobot_sen0395/automation.h
> +        this->parent_->enqueue(make_unique<UartOutputCommand>(2, val));
Could be nice to have then as input parameters in the YAML? As a second PR, maybe?

2024-07-07 12:44 UTC, robin-thoni commented on esphome/components/dfrobot_sen0395/switch/dfrobot_sen0395_switch.cpp
>    this->parent_->enqueue(make_unique<UartOutputCommand>(state));
See my comment above

2024-07-07 12:44 UTC, robin-thoni commented on esphome/components/dfrobot_sen0395/switch/dfrobot_sen0395_switch.cpp
> +  this->parent_->enqueue(make_unique<UartOutputCommand>(2, state));
See my comment above

2024-07-10 16:21 UTC, robin-thoni commented
Just found out you can get hardware/software versions:
```
[18:20:58][D][uart_debug:158]: >>> "getSWV"
[18:20:58][I][dfrobot_sen0395.commands:348]: Version: SoftwareVersion:JYSJ_02.08.07.010706
[18:20:58][D][uart_debug:158]: <<< "getSWV\r\nSoftwareVersion:JYSJ_02.08.07.010706\r\nDone\r\nleapMMW:/>"
[18:20:59][D][uart_debug:158]: >>> "getHWV"
[18:20:59][I][dfrobot_sen0395.commands:342]: Version: HardwareVersion:JYSJ_403_A01
[18:20:59][D][uart_debug:158]: <<< "getHWV\r\nHardwareVersion:JYSJ_403_A01\r\nDone\r\nleapMMW:/>"
```

2024-07-22 17:05 UTC, robin-thoni commented
@niklasweber Did you have any chance to look at your hardware/software versions?

2024-09-27 07:21 UTC, robin-thoni commented
@niklasweber Are you still around? :)

2024-09-27 13:11 UTC, niklasweber commented
Sorry @robin-thoni, I had to unsolder my sensor which I was putting off.. But I unsoldered it now and connected to it directly on my pc to run the commands:
getSWV gives me **SoftwareVersion:JYSJ_02.08.07.010706**
getHWV gives me **HardwareVersion:JYSJ_403_A01**
Strange. It is the exact same as yours. I still don't get the $JYRPO messages. Not sure if I remember correctly. I might have seen these messages at the beginning when I got the sensor.

2024-11-22 13:51 UTC, niklasweber approved these changes

2025-06-04 14:31 UTC, robin-thoni commented
Hey @niklasweber, I just realized this has actually not been merged, could you please re-approve, and merged right after? Any new commit requires a new approval, and the PR has to be up to date w/ main :/ (No merge queue, unfortunately)

2025-06-04 14:48 UTC, niklasweber commented
Hi @robin-thoni, thats unfortunate. It seems my approval is still active, but I don't have write access. I can't merge the PR. If I'm not mistaken only the admins like @jesserockz with write access can merge.

2025-07-06 10:16 UTC, robin-thoni commented
Hi @jesserockz, can we get a review/approval here? THanks!

2026-01-12 00:50 UTC, closed without merging