Enable verbose mode from env ESPHOME_VERBOSE or --verbose
OttoWinter/esphomeyaml pull request #6987
Opened 2024-06-25 21:24 UTC by ptr727

# What does this implement/fix?

Enable `--verbose` mode using `--verbose` or setting environment variable `ESPHOME_VERBOSE=True`.

This allows e.g. docker users to get `--verbose` dashboard behavior by setting the environment variable.

It is also an alternative to e.g.

```shell
# Run with verbose logging if ESPHOME_VERBOSE is set
if [[ -v ESPHOME_VERBOSE ]]; then
    exec esphome --verbose dashboard /config
else
    exec esphome dashboard /config
fi
```

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-24 04:00 UTC, jesserockz commented
I don't think an env var is needed for this.

Especially with your main use case being for docker. 
If you are using docker, just override the container command to `--verbose dashboard /config` instead of the default `dashboard /config`

2024-07-24 04:29 UTC, ptr727 commented
> I don't think an env var is needed for this.

The idea is that anybody can easily modify logging verbosity using an environment variable, which is very common for docker, and very useful for exposing suppressed compilation issues. Modifying the docker entrypoint or command, is a not-so-common way of modifying container runtime behavior.

If you still disagree, feel free to close.

2024-08-15 01:40 UTC, jesserockz requested changes
Remove this code, and change the `verbose` arg to this:
```py
    options_parser.add_argument(
        "-v",
        "--verbose",
        help="Enable verbose ESPHome logs.",
        action="store_true",
        default=get_bool_env("ESPHOME_VERBOSE"),
    )
```

2024-08-16 01:38 UTC, jesserockz approved these changes

2024-08-22 00:58 UTC, merged