Bump HeatpumpIR, add protocols, remove IRremoteESP8266
OttoWinter/esphomeyaml pull request #6996
Opened 2024-06-26 12:34 UTC by nagyrobi

# What does this implement/fix?

- Bump HeatpumpIR to 1.0.27: https://github.com/ToniA/arduino-heatpumpir/commits/1.0.27
- add protocols:
  ```
  airway
  bgh_aud
  panasonic_altdke
  vaillantvai8
  r51m
  ```
- remove IRremoteESP8266 dependency as it's not required anymore (see https://github.com/ToniA/arduino-heatpumpir/pull/175#issuecomment-2190544978 and https://github.com/esphome/esphome/pull/6955#issuecomment-2188338667), allowing usage on platforms like BK72XX and RP2040.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-26 13:13 UTC, nagyrobi commented
Tested on an ESP3266, HeatpumpIR 1.0.27 pulls in IRremoteESP8266 on its own:

```
...
Processing ir-1-halo (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/noise-c @ 0.1.4
INFO Installing esphome/noise-c @ 0.1.4
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.4 has been installed!
INFO noise-c@0.1.4 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10018.1
INFO Installing esphome/libsodium @ 1.10018.1
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10018.1 has been installed!
INFO libsodium@1.10018.1 has been installed!
Library Manager: Installing tonia/HeatpumpIR @ 1.0.27
INFO Installing tonia/HeatpumpIR @ 1.0.27
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Library Manager: HeatpumpIR@1.0.27 has been installed!
INFO HeatpumpIR@1.0.27 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing crankyoldgit/IRremoteESP8266 @ ~2.8.4
INFO Installing crankyoldgit/IRremoteESP8266 @ ~2.8.4
Unpacking  [####################################]  100%
Library Manager: IRremoteESP8266@2.8.6 has been installed!
INFO IRremoteESP8266@2.8.6 has been installed!
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
|-- HeatpumpIR @ 1.0.27
Compiling .pioenvs/ir-1-halo/src/esphome/components/api/api_connection.cpp.o
...
```

2024-07-03 04:07 UTC, jesserockz requested changes

2024-07-03 04:07 UTC, jesserockz commented on tests/components/heatpumpir/test.esp32-ard.yaml
> -    name: HeatpumpIR Climate
You shouldnt remove these if they still work. Just add new ones.

2024-07-04 09:37 UTC, nagyrobi commented on tests/components/heatpumpir/test.esp32-ard.yaml
> -    name: HeatpumpIR Climate
I just moved them to the other framework test files,
added back...

2024-07-10 22:33 UTC, jesserockz requested changes
You are still removing protocols from the test YAML fiels instead of just adding new ones. Adding entire new test files adds about 5 mins to testing time, adding new climate models to the list adds about 5 seconds =)
Just keep them all there and add more if needed. No need to remove any old protocols unless they are removed from the library itself and no longer compile.

2024-07-11 07:22 UTC, nagyrobi commented
I was just trying to optimize a bit, because I thought testing for the exact same component configuration repeatedly would be redundant for each framework; considered a performance gain to distribute some different configuration possibilities over the config files.
As these should actually behave exactly the same at ESPHome level, the difference is only at library level. 
Restored the original files and only added new protocols to the new file.

2024-07-11 07:48 UTC, jesserockz commented
Ideally, we would have a case for as many configuration cases as possible, but that can be a bit overkill. I just don't see the point in removing the ones that work just fine. Just good to add the newly supported ones. Looks good now

2024-07-11 07:52 UTC, jesserockz approved these changes

2024-07-12 21:19 UTC, merged