Add remote transmitter listener to support auto tx on/off
OttoWinter/esphomeyaml pull request #7000
Opened 2024-06-26 22:57 UTC by swoboda1337

# What does this implement/fix?

Need a way for turn the transmitter on and off for 433 radios. Add a way for radios to listen for transmit events. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-26 23:21 UTC, jesserockz requested changes
We have a `power_supply` component that can do this instead of having `listeners`.

2024-06-26 23:57 UTC, swoboda1337 commented
> We have a `power_supply` component that can do this instead of having `listeners`.

The power supply component seems to write to a gpio. Normally these radios will need to do a spi write not toggle a gpio.

2024-06-27 00:03 UTC, jesserockz commented
Ah ok. I wasnt sure how you planned to attach to these listeners since there are no yaml configs for it added.

2024-06-27 00:16 UTC, swoboda1337 commented
> Ah ok. I wasnt sure how you planned to attach to these listeners since there are no yaml configs for it added.

The radio component would have to get the remote transmitter id and register itself. I have a poc working for my radio component here:

https://github.com/swoboda1337/sx127x-esphome/compare/main...remote_transmitter_listener

2024-06-27 01:09 UTC, jesserockz commented
Yes, it would have made sense if you put that in the PR description :sweat_smile:

2024-06-27 01:13 UTC, jesserockz requested changes
I think the calls to `call_listeners_transmit_`/`complete_` needs to happen outside of the loops. Otherwise they could cause timing issues. It should only need to turn on once at the beginning of an entire transmission, and once off at the end.

2024-06-27 01:19 UTC, swoboda1337 commented
> I think the calls to `call_listeners_transmit_`/`complete_` needs to happen outside of the loops. Otherwise they could cause timing issues. It should only need to turn on once at the beginning of an entire transmission, and once off at the end.

Yeah it can be moved out. The user could put a long delay between each send. I wasn't sure if its better to turn off the tx or not. This would mess with the timing. I guess its probably best to keep the transmitter on. The user can send multiple times if they want it off.

2024-09-09 11:39 UTC, swoboda1337 commented
Any chance at getting this PR merged? I want add support for the rf chip but need this first. Thanks!

2024-09-18 15:01 UTC, swoboda1337 commented
Moved to draft temporarily, possibly a better way to implement this

2024-09-24 01:57 UTC, swoboda1337 commented
I implemented this in a better way in: https://github.com/esphome/esphome/pull/7483

2024-09-24 01:57 UTC, closed without merging