feat: Create custom BLE services, characteristics and descriptors
OttoWinter/esphomeyaml pull request #7009
Opened 2024-06-27 20:04 UTC by Rapsssito

# What does this implement/fix?

Adds the ability to create a fully custom BLE server with its own services, characteristics and descriptors.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> TODO

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esp32_ble:

esp32_ble_server:
  manufacturer: ESPHome
  model: Test5
  services:
    - uuid: 2a24b789-7aab-4535-af3e-ee76a35cc42d
      num_handles: 14
      advertise: false
      characteristics:
        - uuid: cad48e28-7fbe-41cf-bae9-d77a6c233423
          properties:
            - read
          value: [0, 1, 2]
    - uuid: 2a24b789-7a1b-4535-af3e-ee76a35cc42d
      advertise: false
      characteristics:
        - id: test_write_characteristic
          uuid: 2a24b789-7a1b-4535-af3e-ee76a35cc12d
          properties:
            - read
            - write
          on_write:
            then:
              - lambda: |-
                  ESP_LOGD("BLE", "Received: %s", x.c_str());
              - ble_server.characteristic_set_value:
                  id: test_write_characteristic
                  value: x
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-29 13:46 UTC, clydebarrow requested changes
Why not make the value of a characteristic templatable? A read request from a client would trigger evaluation of the lambda. Could also add a `notify` action to trigger evaluation and notification, and separate it from `set_value` - which I'd prefer to be named `ble_server.characteristic.set_value`, i.e. use a dot instead of the underscore.
Instead of a `properties` key, why not make `read`, `write` etc top-level Boolean keys, defaulting to false? I would also prefer `write_nr` to be the full `write_no_response`.

2024-07-01 07:02 UTC, Rapsssito commented
> Why not make the value of a characteristic templatable? A read request from a client would trigger evaluation of the lambda. Could also add a `notify` action to trigger evaluation and notification, and separate it from `set_value` - which I'd prefer to be named `ble_server.characteristic.set_value`, i.e. use a dot instead of the underscore. Instead of a `properties` key, why not make `read`, `write` etc top-level Boolean keys, defaulting to false? I would also prefer `write_nr` to be the full `write_no_response`.

The issue I found with setting the value of a characteristic templatable is that it must always be a string (or any other type). I was not able to find a way to overload it.

I will make the other changes ASAP!

2024-07-01 12:30 UTC, Rapsssito commented
@clydebarrow, I have your requested changes staged. I don't want to commit them yet as I also want @jesserockz feedback on this.

@jesserockz, is there any way to overload a templatable entry? If it is not the case, do you think the benefits of making the "value" entry templatable will outweigh the benefits of the compatibility of having many types (byte array, int, float, boolean)?

@clydebarrow, regarding `ble_server.characteristic.set_value`, at the moment this only sets the value of the characteristic with the output of the lambda **when the automation is called** because it matches the current paradigm (i.e. the value is not computed when requested, but before). If @jesserockz agrees, we can change the paradigm so the value is always set when it is requested. Either way, I will add a `ble_server.characteristic.notify` automation, as it is already implemented in the C code.

2024-07-01 17:28 UTC, clydebarrow commented
The way I would do it is to only compute the value when a read is requested, or the notify action is executed. The value would be templatable (requiring a byte array as value), but also allow fixed values of various types, which get translated to lambdas (templates) yielding a byte array at build time, so the C++ code only has to deal with a template and one type. Or you could store a fixed value as a byte array and not set a lambda for invariant values. Some utility functions callable in lambdas would make providing a dynamic value for e.g. ints or floats simpler.  That is in keeping with other BLE implementations I've worked with. It means that if the value is not fixed, it is freshly computed when needed, rather than representing a computation that took place at some time in the past, so is guaranteed to be as up-to-date as possible.It would avoid the need to run a `set_value` action on an interval or other event, which is pointless if nobody is reading it.

2024-07-13 10:03 UTC, Rapsssito commented
@clydebarrow, I have implemented the changes you requested (also marked as outdated my other comments). Let me know what you think!

2024-08-13 16:51 UTC, Rapsssito commented
@clydebarrow @jesserockz, pinging you with a friendly reminder about this!

2024-08-13 19:04 UTC, clydebarrow commented on esphome/core/helpers.h
> +/// Create a byte vector from multiple types of values.
There should be at least a comment here indicating what the endian-ness of the conversion is.

2024-08-13 19:18 UTC, clydebarrow reviewed
This will be a useful addition, but there's a lot to review, have only looked at a little so far.

2024-08-13 19:18 UTC, clydebarrow commented on esphome/components/esp32_ble_server/ble_characteristic.cpp
> -void BLECharacteristic::set_value(uint16_t &data) {
These functions were storing data in little-endian order, whereas the vector functions added in helpers.cpp appear to store in big-endian format. The endian-ness for characteristic data is going to be application-specific. Have a look at https://github.com/esphome/esphome/pull/6878 as an alternative.

2024-08-14 10:58 UTC, Rapsssito commented on esphome/components/esp32_ble_server/ble_characteristic.cpp
> -void BLECharacteristic::set_value(uint16_t &data) {
I have changed all calls from `to_vector` to ByteBuffer (https://github.com/esphome/esphome/pull/6878) to avoid code duplication. I also added a few new methods for populating a ByteBuffer from types like double, bool, string, etc.

2024-08-14 20:48 UTC, clydebarrow commented on esphome/core/bytebuffer.cpp
> +  if (endianness == BIG) {
Could just assign to the property here - that's perfectly fine inside the class, is likely faster than the test, and makes no assumptions about the default.

2024-08-14 20:55 UTC, clydebarrow commented on esphome/core/bytebuffer.cpp
> +  if (endianness == BIG) {
Alternatively the create method could take an endianness parameter.

2024-08-14 20:56 UTC, clydebarrow commented on esphome/core/bytebuffer.h
> +  ByteBuffer() = default;
Why is this needed? It leaves the vector uninitialised so is dangerous.

2024-08-14 21:31 UTC, Rapsssito commented on esphome/core/bytebuffer.cpp
> +  if (endianness == BIG) {
Indeed! I have implemented your suggestion in the last commit (6a7c4b2e595e8c591054b740b095c31db3d0563f)

2024-08-14 21:32 UTC, Rapsssito commented on esphome/core/bytebuffer.h
> +  ByteBuffer() = default;
It is needed because `TEMPLATABLE_VALUE` initializes the value with the class default constructor when instantiated:
https://github.com/esphome/esphome/blob/80a0f137224c82fdc3cf17dfdd5dd3683ad9e796/esphome/core/automation.h#L66
I have changed the default constructor (https://github.com/esphome/esphome/commit/6a7c4b2e595e8c591054b740b095c31db3d0563f) so it the vector is initialized empty.

2024-08-15 02:31 UTC, clydebarrow commented on esphome/components/esp32_ble_server/ble_characteristic.cpp
> -void BLECharacteristic::set_value(uint16_t &data) {
If you break out the ByteBuffer changes to a separate PR that can be reviewed and merged quickly. Also the change to const.py and text_sensor etc. It's much easier for testing as if there are no core changes in the PR, since these don't get pulled in by an external component.

2024-08-15 03:43 UTC, clydebarrow requested changes
Partial review. My eyes were glazing over so had to stop.

2024-08-15 03:43 UTC, clydebarrow commented on esphome/components/esp32_ble_server/__init__.py
> +    return result
```suggestion
PROPERTY_MAP = {
    CONF_READ: BLECharacteristic_ns.PROPERTY_READ,
    CONF_WRITE: BLECharacteristic_ns.PROPERTY_WRITE,
    CONF_NOTIFY: BLECharacteristic_ns.PROPERTY_NOTIFY,
    CONF_BROADCAST: BLECharacteristic_ns.PROPERTY_BROADCAST,
    CONF_INDICATE: BLECharacteristic_ns.PROPERTY_INDICATE,
    CONF_WRITE_NO_RESPONSE: BLECharacteristic_ns.PROPERTY_WRITE_NR,
}

def parse_properties(char_conf):
    return sum([PROPERTY_MAP[k] for k in char_conf if k in PROPERTY_MAP], start=0)
```

Can then also use the map keys to generate the corresponding entries in the config schema e.g.
```
).extend({
    cv.Optional(k, default=False): cv.boolean for k in PROPERTY_MAP.keys()
})
```

2024-08-15 03:43 UTC, clydebarrow commented on esphome/components/esp32_ble_server/__init__.py
> +    for service_config in _ble_server_config[CONF_SERVICES]:
Several issues here; it's not acceptable to raise `cv.Invalid()` in a `to_code` function - it must be done during validation; using a global like that is problematic.

Best solution I can come up with;

* populate a map of characteristics IDs to configs during validation, along with a list of IDs used in notify actions.
* Define a final validate function that checks these:
```
characteristic_map = {}
notifications = set()

def final_validator(config):
    for id in notifications:
        if not characteristic_map[id][CONF_NOTIFY]:
            raise cv.Invalid(f"Characteristic {id} does not support notifications")
    return config

FINAL_VALIDATE_SCHEMA = final_validator

def store_config(config):
    characteristic_map[config[CONF_ID]] = config
    return config


```

The `store_config` function is added to the SERVICE_CHARACTERISTIC_SCHEMA with `cv.All()` Similarly for ids referenced in the notify action.

2024-08-15 03:43 UTC, clydebarrow commented on esphome/components/esp32_ble_server/ble_descriptor.cpp
> +  uint8_t *data = buffer.array();
Only referenced once, just inline the `buffer.array()` call.

2024-08-15 03:43 UTC, clydebarrow commented on esphome/components/esp32_ble_server/ble_server.cpp
> +        if (index_to_remove > 0) {
What scenario would mean that the vector can't simply be cleared after starting the services?

2024-08-15 04:30 UTC, jesserockz commented on esphome/components/esp32_ble_server/__init__.py
> +    for service_config in _ble_server_config[CONF_SERVICES]:
`CORE.data[KEY_ESP32_BLE_SERVER]` can be used to store and retrieve things later

2024-08-15 04:32 UTC, clydebarrow commented on esphome/components/esp32_ble_server/__init__.py
> +    for service_config in _ble_server_config[CONF_SERVICES]:
So where in the core data would you find the notify actions which aren't part of the component config?

2024-08-15 04:33 UTC, clydebarrow commented on esphome/components/esp32_ble_server/__init__.py
> +    for service_config in _ble_server_config[CONF_SERVICES]:
Ah, you're saying that's a good place to store things rather than a random global.

2024-08-15 05:37 UTC, clydebarrow commented on esphome/components/esp32_ble_server/ble_characteristic.cpp
> +    // TODO: Handle when require_ack=true
Need to test here if `service_` is valid - this can be called by an action before the component is setup. If you initialise it in the class definition in the header file it can be tested against `nullptr`, currently it's uninitialised and will be a garbage pointer before being set. Same in `ble_service.h` for `  BLEServer *server_;`

2024-08-19 10:11 UTC, Rapsssito commented on esphome/components/esp32_ble_server/ble_characteristic.cpp
> -void BLECharacteristic::set_value(uint16_t &data) {
I have created #7316 with all core changes (and `ble_client`).

2024-08-19 10:35 UTC, Rapsssito commented on esphome/components/esp32_ble_server/__init__.py
> +    return result
You are right! Thanks! I have included this change in 96026e8d07500f9f2b5db336b546488dd8c20f52

2024-08-19 11:57 UTC, Rapsssito commented on esphome/components/esp32_ble_server/__init__.py
> +    for service_config in _ble_server_config[CONF_SERVICES]:
I have taken your suggestions and used the `extra_schema` to implement the validation. Let me know what you think of the solution:

```python

def validate_notify_characteristic(char_config):
    if KEY_ESP32_BLE_SERVER_NOTIFY_PROVIDED not in CORE.data:
        CORE.data[KEY_ESP32_BLE_SERVER_NOTIFY_PROVIDED] = dict()
    CORE.data[KEY_ESP32_BLE_SERVER_NOTIFY_PROVIDED][char_config[CONF_ID]] = char_config[CONF_NOTIFY]
    # Check if the NOTIFY property is set if the characteristic has a notify action
    char_ids = CORE.data.get(KEY_ESP32_BLE_SERVER_NOTIFY_REQUIRED, set())
    if not char_config[CONF_NOTIFY] and char_config[CONF_ID] in char_ids:
        raise cv.Invalid("Characteristic has a notify action, but the NOTIFY property is not set")
    return char_config


def validate_notify_action(action_char_id):
    if KEY_ESP32_BLE_SERVER_NOTIFY_REQUIRED not in CORE.data:
        CORE.data[KEY_ESP32_BLE_SERVER_NOTIFY_REQUIRED] = set()
    CORE.data[KEY_ESP32_BLE_SERVER_NOTIFY_REQUIRED].add(action_char_id)
    # Check if the NOTIFY property is set for the characteristic
    char_notify_value = CORE.data.get(KEY_ESP32_BLE_SERVER_NOTIFY_PROVIDED, dict()).get(action_char_id, None)
    if char_notify_value is not None and not char_notify_value:
        raise cv.Invalid("Missing NOTIFY property for characteristic with notify action")
    return action_char_id


SERVICE_CHARACTERISTIC_SCHEMA = cv.Schema(
    {
        cv.GenerateID(): cv.declare_id(BLECharacteristic),
        cv.Required(CONF_UUID): UUID_SCHEMA,
        cv.Optional(CONF_WRITE_NO_RESPONSE, default=False): cv.boolean,
        cv.Optional(CONF_VALUE): CHARACTERISTIC_VALUE_SCHEMA,
        cv.GenerateID(CONF_VALUE_ACTION_ID_): cv.declare_id(
            BLECharacteristicSetValueAction
        ),
        cv.Optional(CONF_DESCRIPTORS, default=[]): cv.ensure_list(DESCRIPTOR_SCHEMA),
        cv.Optional(CONF_ON_WRITE): automation.validate_automation(
            {cv.GenerateID(): cv.declare_id(BLECharacteristic)}, single=True
        ),
    },
    extra_schemas=[validate_on_write, validate_notify_characteristic],
).extend({cv.Optional(k, default=False): cv.boolean for k in PROPERTY_MAP.keys()})


@automation.register_action(
    "ble_server.characteristic.notify",
    BLECharacteristicNotifyAction,
    cv.Schema(
        {
            cv.Required(CONF_ID): cv.All(cv.use_id(BLECharacteristic), validate_notify_action),
        }
    ),
)
```

Regarding `validate_notify_characteristic` and `validate_notify_action`, I had to duplicate the validation logic, as I am not sure which one will be called first. Is the order of validation deterministic?

I am still not sure how to handle the `cv.Invalid` at the end of `parse_characteristic_value` and `parse_descriptor_value`. It handles an invalid state that should never occur since the validation scheme already prevents it. Should I just remove it?

2024-08-19 15:27 UTC, Rapsssito commented on esphome/components/esp32_ble_server/ble_server.cpp
> +        if (index_to_remove > 0) {
The thing is that `service->start()` does not start the service right away. It needs to be called once for every characteristic:

https://github.com/esphome/esphome/blob/93f30a0798def5a1b59a0ca891acdc6b975b717c/esphome/components/esp32_ble_server/ble_service.cpp#L85-L101

2024-10-14 08:54 UTC, Rapsssito commented
@clydebarrow, just pinging again as a friendly reminder.

2024-10-14 10:28 UTC, clydebarrow commented
I started some testing of this. I notice you used my Bluetooth company ID in the example above :-)

 My first attempt resulted in the program crashing, due to this:
```
      characteristics:
        - id: test_notify_characteristic
          uuid: cad48e28-7fbe-41cf-bae9-d77a6c233423
          read: true
          notify: true
          value: !lambda return random_uint32();
```

There were no errors or warnings during compilation, even though the generated code returned a uint32 where a ByteBuffer was expected. I would have expected the compiler to complain.

I changed that wrap the uint32 in a bytebuffer, and that worked.

Next step, this characteristic says it supports notifications, but when connecting to the device, it's not possible to enable notifications, due to the lack of a CCCD.

So I added a descriptor for the CCCD:
          descriptors:
            - uuid: 0x2902
              value: 0

This then meant that in the client application I could apparently subscribe to notifications - but when doing so, there was no event in the ESPHome code to tell me that the descriptor had been written to. Also, when reading the CCCD it gave an error because 4 bytes were returned instead of 2.

This raises the question then, it is worth supporting descriptors in general? If so it needs to be done in full, with events and lambdas for values. If not, then the commonly used descriptors (CCCD and User Description) should be implicitly added as required - CCCD added if notify or indicate is enabled, and CUD via a suitable config option e.g. `description:`.

This would also imply a trigger when the CCCD is written to, or just conditions to test if notifications or indications are enabled.

For non-lambda characteristic values it should be possible to specify the size, e.g.:
```
    value: 0
    bytes: 2
```

or something similar.

Basic read and write operations appear to work ok.

2024-10-14 11:17 UTC, clydebarrow requested changes

2024-10-14 11:17 UTC, clydebarrow commented on esphome/components/esp32_ble_server/__init__.py
> +    return action_char_id
these two functions appear to be checking the same thing. There should be a single function that is invoked with a FINAL_VALIDATE rather than trying to do it on the fly. Currently this crashes at build time if a notification action precedes the service definition.

2024-10-14 11:17 UTC, clydebarrow commented on esphome/components/esp32_ble_server/ble_2901.cpp
>  }
This doesn't appear to be used anywhere.

2024-10-14 11:17 UTC, clydebarrow commented on esphome/components/esp32_ble_server/__init__.py
> +        cv.hex_uint32_t,
These validators only check that the value is within range, so e.g. 0x0000 will succeed with `float_` which would be unexpected. So ` value: 0x23` actually delivers 35.0.

2024-10-14 11:17 UTC, clydebarrow commented on esphome/components/esp32_ble_server/__init__.py
> +    return ESPBTUUID_ns.from_uint32(uuid)
This should validate the format for a string - right now it just passes it through without checks (other than length) which generates a uuid at run time with `1` for any non-hex character.

2024-10-14 11:17 UTC, clydebarrow commented on esphome/components/esp32_ble_server/__init__.py
> +        cv.Optional(CONF_NUM_HANDLES, default=0): cv.int_,
Why would there be a need to override the calculation of the number of handles required?

2024-10-19 07:44 UTC, Rapsssito commented on esphome/components/esp32_ble_server/ble_2901.cpp
>  }
You are right! It looks like it was created by @jesserockz in a70a205ace089c30c0ffcf38b9793d7181595b04. Should I remove it?

2024-10-19 08:18 UTC, Rapsssito commented on esphome/components/esp32_ble_server/__init__.py
> +        cv.Optional(CONF_NUM_HANDLES, default=0): cv.int_,
Indeed. I have removed it.

2024-10-19 08:39 UTC, Rapsssito commented on esphome/components/esp32_ble_server/__init__.py
> +        cv.hex_uint32_t,
Ups, my bad. I was not familiar with the `cv.hex_uint` validators. I have changed them to  `cv.uint` to avoid these issues.

2024-10-19 08:56 UTC, Rapsssito commented on esphome/components/esp32_ble_server/__init__.py
> +    return ESPBTUUID_ns.from_uint32(uuid)
Right! I have moved `bt_uuid` validator from `esp32_ble_tracker` to `esp32_ble` and it is now also used here.

2024-10-19 09:32 UTC, Rapsssito commented on esphome/components/esp32_ble_server/__init__.py
> +    return action_char_id
Thanks for the comment! I did not know about the `FINAL_VALIDATE_SCHEMA`. I have followed your suggestion and added it instead of `validate_notify_characteristic`.

2024-10-19 11:20 UTC, clydebarrow commented on esphome/components/esp32_ble_server/__init__.py
> +        cv.hex_uint32_t,
> Ups, my bad

No need to feel bad or apologise BTW. I know that review feedback can sometimes seem a little terse but there's no criticism implied - the whole point of the review process is to improve the code by having another pair (or preferably several pairs) of eyes on it, and it's a learning process for everyone involved.

This is a reasonably large and complex PR so it's inevitable it's going to take several rounds of review to get it right. You can be assured that this is is useful work you're doing and I'm certainly keen to see it get done.

2024-10-19 18:00 UTC, Rapsssito commented
> I started some testing of this. I notice you used my Bluetooth company ID in the example above :-)

Oops. I did not know that. I don't even remember where I took it from...

> My first attempt resulted in the program crashing, due to this:
> 
> ```
>       characteristics:
>         - id: test_notify_characteristic
>           uuid: cad48e28-7fbe-41cf-bae9-d77a6c233423
>           read: true
>           notify: true
>           value: !lambda return random_uint32();
> ```
> 
> There were no errors or warnings during compilation, even though the generated code returned a uint32 where a ByteBuffer was expected. I would have expected the compiler to complain.
> 
> I changed that wrap the uint32 in a bytebuffer, and that worked.
> 

I checked with other value types like `return "string"` and discovered the underlying issue. It looks like the lambda is calling the default constructor `ByteBuffer(size_t capacity, Endian endianness = LITTLE)` in the `TEMPLATE_VALUE` with the `uint32` value as the `size_t capacity` parameter. I am not sure if this is fixable.

> Next step, this characteristic says it supports notifications, but when connecting to the device, it's not possible to enable notifications, due to the lack of a CCCD.
> This then meant that in the client application I could apparently subscribe to notifications - but when doing so, there was no event in the ESPHome code to tell me that the descriptor had been written to. Also, when reading the CCCD it gave an error because 4 bytes were returned instead of 2.
> This raises the question then, it is worth supporting descriptors in general? If so it needs to be done in full, with events and lambdas for values. If not (or as well) then the commonly used descriptors (CCCD and User Description) should be implicitly added as required - CCCD added if notify or indicate is enabled, and CUD via a suitable config option e.g. `description:`.

Thank you very much for the feedback. I would like to point out that I am not very familiar with BLE (in fact, I am getting more familiar with it by developing this PR). I didn't think enough about "notify" or "indicate" because I didn't need them in my use case. I think the best option is to support descriptors 100%, so I have implemented everything you mentioned. However, I couldn't find if (or how) a descriptor value is supposed to be updated right before it is read, so right now the descriptor value is the initial value.

Let me know what you think!

2024-10-19 22:55 UTC, clydebarrow commented on esphome/components/esp32_ble_server/ble_2901.cpp
>  }
I think so, it does nothing that can't be done otherwise.

2024-10-19 23:03 UTC, clydebarrow reviewed
Looking good, will do some more testing, might be a few days though.

2024-10-19 23:03 UTC, clydebarrow commented on esphome/components/esp32_ble_server/ble_characteristic.cpp
> +        uint16_t cccd = (value[1] << 8) | value[0];
There are helper functions to do this in `esphome/core/helpers.h`. The benefit of using them is that it makes it clear what you are doing, it keeps style consistent, and the code is already known to work correctly.
```suggestion
        uint16_t cccd = encode_uint16(value[1], value[0]);
```

2024-10-19 23:03 UTC, clydebarrow commented on esphome/components/esp32_ble_server/ble_characteristic.h
> +  BLEService *service_ = nullptr;
```suggestion
  BLEService *service_{};
```
Same result, more modern idiom, keeps code style consistent.

2024-11-01 00:07 UTC, clydebarrow commented
@Rapsssito I sent you a message via discord. I have some changes I'd like to push, and also need to discuss some other issues with you.

2024-12-26 12:51 UTC, lufton commented
Hey @Rapsssito, is there a way to use this implementation right away? I thought I can do:
```yaml
external_components:
  - source: github://pr#7009
    components: [ esp32_ble, esp32_ble_server ]
```

But there are also changes in a `core/event_emitter`. So I'm getting:

```
src/esphome/components/esp32_ble_server/ble_descriptor.h:4:10: fatal error: esphome/core/event_emitter.h: No such file or directory
```

2025-01-20 01:28 UTC, clydebarrow commented
@Rapsssito I left some comments in the Discord DM channel. Look this over and let me know, but from my perspective it's ready to go.

2025-01-28 10:59 UTC, clydebarrow approved these changes

2025-01-28 11:00 UTC, merged

2025-01-28 11:05 UTC, lufton commented
Oh, gosh! I was waiting for this to be merged forever! Thanks @clydebarrow @Rapsssito, you are awesome!

2025-09-27 00:59 UTC, bdraco commented
Hi everyone,

I wanted to provide some feedback on this PR after working with it in production environments. While the EventEmitter pattern and BLE customization features are powerful additions, we've discovered some significant challenges that have emerged from this implementation:

This PR has added approximately 15-30KB of flash usage (depending on usage), which is substantial for embedded systems. For context, the entire bluetooth_proxy implementation is only ~6.6KB. This has caused memory pressure on devices, particularly affecting vendors shipping products with Improv where the BLE stack now consumes more resources than most other components combined.

The original implementations were severely impacting performance - service lookups were 241x slower before optimizations in #10894 and #10714. The `std::unordered_map` approach with string key generation and hashing, while elegant for desktop applications, isn't suitable for embedded systems where we typically have just 1-3 services.

We've encountered crashes in the ESP32 Improv component that were introduced with these changes (addressed in #10902). The null pointer dereferences and uninitialized pointers have caused devices to crash when BLE client and server are used together.

The advanced features are primarily used by custom automations, which represents a small percentage of use cases, yet the memory and performance costs are paid by all users of ESP32 BLE server.

Moving forward, we're working on:
- Conditionally compiling automations to reduce overhead (#10910)
- Continuing vector-based optimizations (#10900, #10897) achieving 2.3x+ better performance
- Designing a more lightweight event system better suited for embedded constraints
- Ensuring future contributions consider memory/flash/performance impact as primary design constraints

This is a learning opportunity for all of us about balancing feature richness with embedded system constraints. Thank you for your contribution - it sparked important discussions about architecture patterns in ESPHome.

2025-09-27 07:35 UTC, Rapsssito commented
Hi @bdraco,

Thanks for your work and apologies for my poorly optimized implementation. I have no previous experience with embedded systems, so I default to design choices more commonly used in high level implementations.

This PR was actually pretty difficult for me to pull off, and I appreciate your work optimizing it. I am actually using it in production, so these new fixes are very welcomed.

Regarding the event emitter, I believe there is redundant code regarding events in the whole codebase. I realized this a few months ago (the PR was already merged), when I was working on the MQTT errors. It would be great if the event emitter functionality was optimized and the optimized version was shared across components.

Thanks again!