Add Switch support to Homeassistant component.
OttoWinter/esphomeyaml pull request #7018
Opened 2024-06-30 05:52 UTC by Links2004

# What does this implement/fix?

Add Switch support to Homeassistant component.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
api:

switch:
  - platform: homeassistant
    entity_id: switch.my_cool_switch
    id: my_cool_switch
    on_turn_on:
      then:
        - light.turn_on: led_button_1
    on_turn_off:
      then:
        - light.turn_off: led_button_1

light:
  - platform: binary
    output: dummy_out
    id: led_button_1
    internal: true

binary_sensor:
  - platform: gpio
    id: input_1
    internal: true
    pin: dummy
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - light.toggle: my_cool_switch
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-06-30 11:07 UTC, Links2004 commented
this PR will be updated based on the outcome of the `unavailable` and `unknown` decisions in:
https://github.com/esphome/esphome/pull/7016

2024-07-01 17:33 UTC, landonr commented
I have a similar component [here](https://github.com/landonr/esphome-components/blob/main/components/homeassistant_component/switch/HomeAssistantSwitch.cpp) that I've been waiting for !6455 to put up for review. After making a call to the Home Assistant switch, do you have an issue with the state updating on Home Assistant and in your state subscription?

2024-08-13 04:51 UTC, jesserockz requested changes
A few minor things while below. Otherwise looks good.

2024-08-13 04:51 UTC, jesserockz commented on esphome/components/homeassistant/switch/homeassistant_switch.cpp
> +  }
Unless the code is written badly (not the case here) then this cannot happen as the global api server is assigned in the APIServer constructor
```suggestion
```

2024-08-13 04:51 UTC, jesserockz commented on esphome/components/homeassistant/switch/homeassistant_switch.cpp
> +    ESP_LOGE(TAG, "API Server not connected");
```suggestion
    ESP_LOGE(TAG, "No clients connected to API server");
```

2024-08-13 04:51 UTC, jesserockz commented on esphome/components/homeassistant/switch/homeassistant_switch.cpp
> +  }
Just reorganising it a little
```suggestion
  api::HomeassistantServiceResponse resp;
  if (state) {
    resp.service = "switch.turn_on";
  } else {
    resp.service = "switch.turn_off";
  }
  
  api::HomeassistantServiceMap entity_id_kv;
  entity_id_kv.key = "entity_id";
  entity_id_kv.value = this->entity_id_;
  resp.data.push_back(entity_id_kv);
```

2024-08-13 04:51 UTC, jesserockz commented on esphome/components/homeassistant/switch/homeassistant_switch.cpp
> +      this->entity_id_, optional<std::string>(""), [this](const std::string &state) {
```suggestion
      this->entity_id_, nullopt, [this](const std::string &state) {
```

2024-08-13 04:51 UTC, jesserockz commented on esphome/components/homeassistant/switch/homeassistant_switch.cpp
> +        return;
Not needed
```suggestion
```

2024-08-13 04:51 UTC, jesserockz commented on esphome/components/homeassistant/switch/homeassistant_switch.h
> +  void set_entity_id(const std::string &entity_id) { entity_id_ = entity_id; }
```suggestion
  void set_entity_id(const std::string &entity_id) { this->entity_id_ = entity_id; }
```

2024-08-13 05:01 UTC, jesserockz requested changes

2024-08-13 05:01 UTC, jesserockz commented on esphome/components/homeassistant/switch/__init__.py
> +    .extend({cv.GenerateID(): cv.declare_id(HomeassistantSwitch)})
This is redundant as the class/id is done in the `switch_schema`
```suggestion
```

2024-08-13 05:01 UTC, jesserockz commented on esphome/components/homeassistant/switch/__init__.py
> +DEPENDENCIES = ["api"]
```suggestion
CODEOWNERS = ["@Links2004"]
DEPENDENCIES = ["api"]
```

2024-08-13 05:01 UTC, jesserockz commented on esphome/components/homeassistant/switch/__init__.py
> +    .extend(HOME_ASSISTANT_IMPORT_SCHEMA)
Added in #7259
```suggestion
    .extend(HOME_ASSISTANT_IMPORT_CONTROL_SCHEMA)
```

2024-08-13 05:01 UTC, jesserockz commented on esphome/components/homeassistant/switch/__init__.py
> +    HOME_ASSISTANT_IMPORT_SCHEMA,
Added in #7259
```suggestion
    HOME_ASSISTANT_IMPORT_CONTROL_SCHEMA,
```

2024-08-13 05:09 UTC, jesserockz commented
Depends on https://github.com/esphome/esphome/pull/7259 being merged first

2024-08-13 06:35 UTC, jesserockz commented
I wonder if we should add a validation to the `entity_id` so that it can only use `switch.` entities.
It could then be extended (In a different PR) to allow more entities and automatically perform the correct `action` based on the entity_id.

2024-08-13 12:53 UTC, nielsnl68 requested changes
Very interesting addition to espHome.

2024-08-13 12:53 UTC, nielsnl68 commented on tests/components/homeassistant/common.yaml
> +    entity_id: switch.my_cool_switch
To make sure everyone understand directly that the entity_id is related to home-assistant would it not be to change:  
```suggestion
    homeassistant_entity: switch.my_cool_switch
```

2024-08-13 12:56 UTC, nielsnl68 commented on tests/components/homeassistant/common.yaml
> +    entity_id: switch.my_cool_switch
I see that the depending PR is already merged.

2024-08-13 20:14 UTC, jesserockz commented on tests/components/homeassistant/common.yaml
> +    entity_id: switch.my_cool_switch
If we changed it to something else, it would be inconsistent with the existing sensor/binary_sensor/text_sensor implementations.

2024-08-13 23:55 UTC, jesserockz approved these changes

2024-08-14 01:36 UTC, nielsnl68 commented on tests/components/homeassistant/common.yaml
> +    entity_id: switch.my_cool_switch
Yeah, when you decide to change it then those should change as well.
As i said i'm to late for this request :(

2024-08-14 02:03 UTC, merged