Tuya Number: allow to set hidden datapoints
OttoWinter/esphomeyaml pull request #7024
Opened 2024-07-01 09:45 UTC by szupi-ipuzs

# What does this implement/fix?

Some Tuya devices do not publish all of their datapoints at initialization, but they still allow writing to the so-called "hidden" datapoints.
Current implementation of Tuya Number requires to know the datapoint type upfront. In case of the "hidden" datapoints, their type remains unknown and thus it is not possible to set such a Number.

This PR adds a yaml config block which allows specifying missing datapoint type and also (optionally) the initial value to be written to datapoint upon the initialization.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs# (to be added later)

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [x] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
    - platform: "tuya"
      name: "Alarm at maximum"
      number_datapoint: 116
      min_value: 0
      max_value: 100
      datapoint_hidden:
        datapoint_type: int
        init:
          value: 85
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-01 17:03 UTC, szupi-ipuzs commented
@ssieb would you mind taking a look at this PR?

2024-07-02 01:51 UTC, jesserockz commented
Don't ping people on PRs. It will only get them ignored by that person.

2024-08-13 00:59 UTC, jesserockz requested changes

2024-08-13 00:59 UTC, jesserockz commented on esphome/components/tuya/number/__init__.py
> +                        ),
The extra nested config here seems over the top
```suggestion
                        cv.Optional(CONF_INITIAL_VALUE): cv.float_,
```

2024-08-13 00:59 UTC, jesserockz commented on esphome/components/tuya/number/tuya_number.cpp
> +    ESP_LOGCONFIG(TAG, "  Value to restore is %f", *this->value_to_restore_);
```suggestion
    ESP_LOGCONFIG(TAG, "  Initial Value: %f", *this->value_to_restore_);
```

2024-08-13 00:59 UTC, jesserockz commented on esphome/components/tuya/number/tuya_number.h
> +  optional<float> value_to_restore_{};
```suggestion
  optional<float> initial_value_{};
```

2024-08-13 00:59 UTC, jesserockz commented on esphome/components/tuya/tuya.h
> +enum TuyaDatapointType {
Dont remove the restrictions here
```suggestion
enum class TuyaDatapointType : uint8_t {
```

2024-08-13 22:19 UTC, szupi-ipuzs commented on esphome/components/tuya/number/__init__.py
> +                        ),
This wasn't done by mistake. I plan to extend the yaml later with an option to restore the initial value from persistent storage, instead of a constant.

```yaml
init:
  - value: 10
  - restore_value: true # this part will be added in a separate PR
```

If I have the nested config now, the yaml will remain backwards compatible after I add the restoring part.

2024-08-13 22:20 UTC, szupi-ipuzs commented on esphome/components/tuya/number/tuya_number.cpp
> +    ESP_LOGCONFIG(TAG, "  Value to restore is %f", *this->value_to_restore_);
This can be changed now, but see above.

2024-08-13 22:21 UTC, szupi-ipuzs commented on esphome/components/tuya/tuya.h
> +enum TuyaDatapointType {
I have to remove them, because of https://github.com/esphome/issues/issues/5984

2024-08-14 02:16 UTC, jesserockz commented on esphome/components/tuya/number/__init__.py
> +                        ),
In other places in ESPHome we have `initial_value` and `restore_value` as two separate keys beside each other.

2024-08-14 02:18 UTC, jesserockz commented on esphome/components/tuya/__init__.py
> +TuyaDatapointType = tuya_ns.enum("TuyaDatapointType")
```suggestion
TuyaDatapointType = tuya_ns.enum("TuyaDatapointType", is_class=True)
```

2024-08-14 02:18 UTC, jesserockz commented on esphome/components/tuya/tuya.h
> +enum TuyaDatapointType {
Ah, the solution is to add `is_class=True` to the enum in python. See my latest suggestion

2024-08-15 22:59 UTC, jesserockz requested changes

2024-08-15 22:59 UTC, jesserockz commented on esphome/components/tuya/number/__init__.py
> +        if hidden_init_value := hidden_config.get(CONF_INITIAL_VALUE):
Gotta protect against 0 being falsy here
```suggestion
        if (hidden_init_value := hidden_config.get(CONF_INITIAL_VALUE, None)) is not None:
```

2024-08-15 22:59 UTC, jesserockz commented on esphome/components/tuya/number/__init__.py
> +            )
```suggestion
    max_value = config[CONF_MAX_VALUE]
    min_value = config[CONF_MIN_VALUE]
    if max_value <= min_value:
        raise cv.Invalid("max_value must be greater than min_value")
    if hidden_config := config.get(CONF_DATAPOINT_HIDDEN):
        if (initial_value := hidden_config.get(CONF_INITIAL_VALUE, None)) is not None:
            if (initial_value > max_value) or (initial_value < min_value):
                raise cv.Invalid(
                    f"{CONF_INITIAL_VALUE} must be a value between {CONF_MAX_VALUE} and {CONF_MIN_VALUE}"
                )
```

2024-08-15 23:51 UTC, jesserockz approved these changes

2024-08-22 00:59 UTC, merged