Add new component max6921
OttoWinter/esphomeyaml pull request #7025
Opened 2024-07-01 13:58 UTC by endym

# What does this implement/fix?

This PR introduces the component MAX6921 [(datasheet)](https://www.analog.com/media/en/technical-documentation/data-sheets/MAX6921-MAX6931.pdf). This chip is a vacuum-fluorescent display (VFD) tube driver. For example it can be used to drive a IV18 display tube.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#_coming  soon_

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
```
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

display:
  - platform: max6921
    id: iv18
    load_pin: GPIO5
    blank_pin: GPIO17
    out_pin_mapping:
        seg_to_out_map:
            seg_a_pin: 0
            seg_b_pin: 2
            seg_c_pin: 5
            seg_d_pin: 6
            seg_e_pin: 4
            seg_f_pin: 1
            seg_g_pin: 3
            seg_p_pin: 7
        pos_to_out_map:
            # IV18 positions starts at the right side!
            pos_0_pin: 15
            pos_1_pin: 14
            pos_2_pin: 13
            pos_3_pin: 16
            pos_4_pin: 12
            pos_5_pin: 17
            pos_6_pin: 11
            pos_7_pin: 18
    brightness: 100%
    update_interval: 500ms
    lambda: |-
      it.print("01234567");
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-29 04:14 UTC, jesserockz requested changes
Please address the automatic CI errors. This will not be manually reviewed until that is passing and new tests are also added.

2024-09-19 16:33 UTC, endym commented
Hi!
All requested changes are done IMHO. Just to be sure: Is something still missing?

2024-09-26 22:57 UTC, jesserockz requested changes
Please read over the [codebase standards](https://esphome.io/guides/contributing#codebase-standards) as I can see in many places they have not been followed.

I have not looked over all of the code yet due to its size. Will come back once changes have been made.

2024-09-26 22:57 UTC, jesserockz commented on esphome/components/max6921/display.py
> +        raise cv.Invalid("OUT pin duplicate")
```suggestion
        raise cv.Invalid("Pin numbers cannot be reused")
```

2024-09-26 22:57 UTC, jesserockz commented on esphome/components/max6921/display.py
> +    #     raise cv.Invalid("Not more than 20 OUT pins supported")
No commented out code
```suggestion
```

2024-09-26 22:57 UTC, jesserockz commented on esphome/components/max6921/display.py
> +            # ),
```suggestion
```

2024-09-26 22:57 UTC, jesserockz commented on esphome/components/max6921/max6921.cpp
> +#ifdef USE_ESP32_FRAMEWORK_ARDUINO
AFAICT the only reason you have this is `ledc`. But as per my comment below, this component should not be doing that.

2024-09-26 22:57 UTC, jesserockz commented on esphome/components/max6921/display.h
> +class Display : public DisplayBrightness, public DisplayMode {
Please use a different name here, even though this is namespaced, it is easy to confuse with the main ESPHome `Display` class.

2024-09-26 22:57 UTC, jesserockz commented on esphome/components/max6921/display.cpp
> +  }
This should just be handled by a monochromatic light in yaml. The display code should not have anything to do with brightness

2024-09-26 22:57 UTC, jesserockz commented on esphome/components/max6921/max6921.cpp
> +}
Should the update happen after the lambda is run and the changes are now buffered ready to be sent to the device?

2024-09-26 22:57 UTC, jesserockz commented on esphome/components/max6921/max6921.cpp
> +  this->disable_load_();            // set LOAD to low
Isnt this just duplicating the `cs_pin` and `enable()` / `disable()` we have built into the base spi device code?

2024-09-28 16:48 UTC, endym commented on esphome/components/max6921/display.py
> +        raise cv.Invalid("OUT pin duplicate")
Done

2024-09-28 16:48 UTC, endym commented on esphome/components/max6921/display.py
> +    #     raise cv.Invalid("Not more than 20 OUT pins supported")
Done

2024-09-28 16:48 UTC, endym commented on esphome/components/max6921/display.py
> +            # ),
Done

2024-09-28 16:49 UTC, endym commented on esphome/components/max6921/max6921.cpp
> +#ifdef USE_ESP32_FRAMEWORK_ARDUINO
Replaced with USE_ESP32 (ledc usage removed, see below).

2024-09-28 16:50 UTC, endym commented on esphome/components/max6921/display.h
> +class Display : public DisplayBrightness, public DisplayMode {
Done

2024-09-28 16:50 UTC, endym commented on esphome/components/max6921/display.cpp
> +  }
Done

2024-09-28 16:52 UTC, endym commented on esphome/components/max6921/max6921.cpp
> +}
Addressed (see code comment).

2024-09-28 17:10 UTC, endym commented on esphome/components/max6921/max6921.cpp
> +  this->disable_load_();            // set LOAD to low
Currently the load pin is handled similarly to a SPI CS pin. However, the load pin has a completely different task with a quite flexible handling. For example, a HIGH pulse could also be made after the data transfer (see figure 4 in the data manual).
I would prefer to leave the load pin configuration as it is.

2024-09-28 17:20 UTC, endym commented
I've also addressed codebase standards (prefixed all class members/functions with "this->", made private class fields protected).

2024-10-03 20:09 UTC, closed without merging

2024-10-03 20:38 UTC, endym commented
@jesserockz I've no idea, why this PR is marked as closed now. It wasn't me. The only thing I've done was to reset the branch in my forked repo to commit d00e0eb2d6194be562219d1313d18d0236280307, because the next commit breaks the checks. Maybe this was not a good idea...
Can you re-activate the PR or do I have to create a new PR?