[micro_wake_word] Version 2
OttoWinter/esphomeyaml pull request #7032
Opened 2024-07-02 19:18 UTC by kahrendt

# What does this implement/fix?

Adds support for microWakeWord version 2 models.

- Adds ops to support more efficient and accurate 'MixedNet' models which can run on an ESP32
- Adds support for running multiple models at once
- Adds support for running a Voice Activity Model to reduce false activations from non-speech noises
- Moved spectrogram feature generation to a PlatformIO library that uses C code. This is much faster!
- Models load and unload as mWW is started and stopped to reduce memory usage
- Update the model manifest to version 2 to support setting the spectrogram feature step size and setting the amount of memory to allocate for the tensor arena.

The old microWakeWord models will still work with this version of the component, but they cannot run simultaneously with the new models. It is a breaking change as the YAML configuration has changed to support listing multiple models.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** not applicable

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4015

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

Ensure you are running the ESPHome dev branch!

```yaml
# Example config.yaml
external_components:
  - source:
      type: git
      url: https://github.com/kahrendt/esphome
      ref:  mww-v2-external-library
    refresh: 0s
    components: [ micro_wake_word ]  

micro_wake_word:
  on_wake_word_detected:
    - voice_assistant.start: 
        wake_word: !lambda return wake_word; 
  vad:
    model: https://github.com/kahrendt/microWakeWord/releases/download/v2_models/vad.json
  models:
    - model: https://github.com/kahrendt/microWakeWord/releases/download/v2_models/okay_nabu.json
    - model: https://github.com/kahrendt/microWakeWord/releases/download/v2_models/hey_mycroft.json
    - model: https://github.com/kahrendt/microWakeWord/releases/download/v2_models/alexa.json

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-02 23:42 UTC, jesserockz requested changes
Here is my initial review. I have not looked at everything yet.

We have the tflite component loaded now in CI, so `#ifndef CLANG_TIDY` can be removed from the source files.

2024-07-02 23:42 UTC, jesserockz commented on esphome/components/micro_wake_word/__init__.py
> +    if manifest_version := manifest_data["version"]:
We should use the const here, and also change to `.get` in case it is not in the file as we dont want to raise an unhandled key error
```suggestion
    if manifest_version := manifest_data.get(KEY_VERSION):
```

2024-07-02 23:42 UTC, jesserockz commented on esphome/components/micro_wake_word/__init__.py
> +        raise cv.Invalid("Invalid manifest file, missing 'version' key.")
Lets combine this with the above so we dont have a large chunk of duplicate code

2024-07-02 23:42 UTC, jesserockz commented on esphome/components/micro_wake_word/__init__.py
> -            cv.Required(CONF_MODEL): MODEL_SOURCE_SCHEMA,
Please leave removed keys in the schema with a validation of `cv.invalid("This has moved... etc")`

2024-07-02 23:42 UTC, jesserockz commented on esphome/components/micro_wake_word/__init__.py
> +            raise cv.Invalid("Cannot load models with differet features step sizes.")
We cannot raise cv.Invalid errors inside `to_code`. This should be checked in the validation stage.
Also a typo =)

```suggestion
            raise cv.Invalid("Cannot load models with different features step sizes.")
```

2024-07-02 23:42 UTC, jesserockz commented on esphome/components/micro_wake_word/micro_wake_word.cpp
> +#endif
```suggestion
  ESP_LOGCONFIG(TAG, "microWakeWord:");
  ESP_LOGCONFIG(TAG, "  models:");
  for (auto &model : this->wake_word_models_) {
    model.log_model_config();
  }
#ifdef USE_MWW_VAD
  this->vad_model_->log_model_config();
#endif
```

2024-07-02 23:42 UTC, jesserockz commented on esphome/components/micro_wake_word/__init__.py
> +        cg.add_define("USE_MWW_VAD")
I know its long, but we need to keep consistency and use the actual component name =)
Also please add it to `esphome/core/defines.h` in the esp32 section so it is set during development and CI.
```suggestion
        cg.add_define("USE_MICRO_WAKE_WORD_VAD")
```

2024-07-02 23:42 UTC, jesserockz commented on esphome/components/micro_wake_word/streaming_model.cpp
> +  ESP_LOGCONFIG(TAG, "    Sliding window size: %d", this->sliding_window_size_);
I split the logconfig text in the main component and prefixed "models" so these should also move over.
```suggestion
  ESP_LOGCONFIG(TAG, "    - Wake Word: %s", this->wake_word_.c_str());
  ESP_LOGCONFIG(TAG, "      Probability cutoff: %.3f", this->probability_cutoff_);
  ESP_LOGCONFIG(TAG, "      Sliding window size: %d", this->sliding_window_size_);
```

2024-07-02 23:42 UTC, jesserockz commented on esphome/components/micro_wake_word/streaming_model.cpp
> +  ESP_LOGCONFIG(TAG, "    Sliding window size: %d", this->sliding_window_size_);
```suggestion
  ESP_LOGCONFIG(TAG, "    - VAD Model");
  ESP_LOGCONFIG(TAG, "      Probability cutoff: %.3f", this->probability_cutoff_);
  ESP_LOGCONFIG(TAG, "      Sliding window size: %d", this->sliding_window_size_);
```

2024-07-02 23:42 UTC, jesserockz commented on esphome/components/micro_wake_word/streaming_model.h
> +  std::string get_wake_word() { return this->wake_word_; }
```suggestion
  const std::string &get_wake_word() const { return this->wake_word_; }
```

2024-07-03 17:05 UTC, kahrendt commented on esphome/components/micro_wake_word/__init__.py
> +            raise cv.Invalid("Cannot load models with differet features step sizes.")
I've created a new function to validate this and just set ``FINAL_VALIDATE_SCHEMA = _feature_step_size_validate`` I think this is the right approach from looking at other components, but I'm not 100% sure.

2024-07-03 17:06 UTC, kahrendt commented on esphome/components/micro_wake_word/__init__.py
> +        cg.add_define("USE_MWW_VAD")
I get lazy sometimes :)

2024-07-03 17:12 UTC, kahrendt commented
> Here is my initial review. I have not looked at everything yet.
> 
> We have the tflite component loaded now in CI, so `#ifndef CLANG_TIDY` can be removed from the source files.

Thanks for the initial review! I made those changes and fixed the things clang tidy was complaining about:
- add final specifier to the ``WakeWordModel`` and ``VADModel`` classes (I'm not 100% this is the best way to handle the virtual destructor issue)
- use unique_ptr for the VAD model and the TFLite interpreter
- use constexpr in the ``generate_features_for_window_`` function
- use ``emplace_back`` instead of ``push_back`` when adding WakeWordModels

2024-07-10 22:51 UTC, jesserockz approved these changes

2024-07-10 22:59 UTC, jesserockz requested changes
Forgot we should change the shorthand url builder to have the v2 directory
https://github.com/esphome/esphome/pull/7032/files#diff-7dd4ab6d5bf5e2bc507a1a67e15a8aa9b206c8d285bbe47be228a71f0de749c2R271

2024-07-11 00:00 UTC, jesserockz approved these changes

2024-07-11 01:21 UTC, merged