Haier component update to support more protocol variations
OttoWinter/esphomeyaml pull request #7040
Opened 2024-07-04 06:13 UTC by paveldn

# What does this implement/fix?

Update for haier climate component. What is new:
- Added support for self-cleaning and swing controls for hOn ACs that use single parameter control mode.
- New parameters added to support more Haier protocol variations
- on_status trigger added for both smartAir2 and hOn to be able to process raw AC status data. This will allow users to support features that are unique to the model.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-05 01:36 UTC, jesserockz requested changes

2024-07-05 01:36 UTC, jesserockz commented on platformio.ini
> +    pavlodn/HaierProtocol@0.9.31           ; haier
Please add links to the releases so we can take a quick look over what is being changed. This is not for reviewing the library itself, but for making sure that there is no hidden malicious code in them.

2024-07-05 05:21 UTC, paveldn commented on platformio.ini
> +    pavlodn/HaierProtocol@0.9.31           ; haier
Hi @jesserockz,

My library code is here: https://github.com/paveldn/HaierProtocol
Here you can see the difference between 28 and 31: https://github.com/paveldn/HaierProtocol/compare/7bab6a487cc0c77f7b0d5aba831de7580ca3bcbe..a356ba37cec091ad9c963e40f93f8f4125e8bb3c?diff=unified&w=
Changes are not that big. Most of the changes are related to tests and tools. The biggest change is I changed some headers to be able to build it for the host platform together with the UART component for the host. You can ignore everything that is not in src or include folders. As you can see in the library.json only those folders are included in the library itself.

Let me know if I can help or if you have questions.

2024-07-06 06:57 UTC, jesserockz commented on platformio.ini
> +    pavlodn/HaierProtocol@0.9.31           ; haier
Thank for that. Your diff url is [backwards](https://github.com/paveldn/HaierProtocol/compare/a356ba37cec091ad9c963e40f93f8f4125e8bb3c...7bab6a487cc0c77f7b0d5aba831de7580ca3bcbe?w=1) btw =)

Not required, but would be nice if you tagged the repo at the point of the package release too so it is clear to anyone else who wants to inspect. Otherwise they will not know what commit to look at.

2024-07-06 06:58 UTC, jesserockz approved these changes

2024-07-06 07:00 UTC, merged