jsn_sr04t component: AJ_SR04M compatibility mode in checksum calculation
OttoWinter/esphomeyaml pull request #7044
Opened 2024-07-04 22:27 UTC by soeffi

# What does this implement/fix?

The AJ_SR04M ultarsonic module is very similar to the JSN SR04T and has similar operation modes.

There is only one differences in the protocol, which is the checksum calculation that does not include the first byte.

This PR adds a configuration option to use the alternative checksum calculation mode.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2784

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: jsn_sr04t
    ajsr04m_mode: true
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-04 22:28 UTC, soeffi commented
I did my best to compile a PR. Be kind, this is my first PR ever.

Let me know what you think and I'll work on the open checklist items

2024-07-05 06:51 UTC, Mafus1 commented
@soeffi I just looked at the PR, and it looks good to me! I also tested it on my JSN-RT04T and it behaves as expected. It would be great if you could also update the documentation, so other people know how to use this option, too.

2024-07-05 22:43 UTC, soeffi commented
> It would be great if you could also update the documentation

Done, added PR for docs as well

2024-07-06 04:28 UTC, jesserockz requested changes

2024-07-06 04:28 UTC, jesserockz commented on esphome/components/jsn_sr04t/sensor.py
> +            cv.Optional(CONF_AJSR04M_MODE, default=False): cv.boolean,
Lets change this to an enum with `CONF_MODEL` with the default being "jsn_sr04t"

2024-07-11 07:33 UTC, soeffi commented on esphome/components/jsn_sr04t/sensor.py
> +            cv.Optional(CONF_AJSR04M_MODE, default=False): cv.boolean,
> Lets change this to an enum with `CONF_MODEL` with the default being "jsn_sr04t"

Done, PR for code and docs updated. Could you please review and let me know if that works?

2024-07-11 07:59 UTC, jesserockz requested changes
Changes look good. Just a couple of things below

2024-07-11 07:59 UTC, jesserockz commented on esphome/components/jsn_sr04t/jsn_sr04t.h
> +  Model model_ = JSN_SR04T;
```suggestion
  Model model_;
```

2024-07-11 07:59 UTC, jesserockz commented on esphome/components/jsn_sr04t/jsn_sr04t.cpp
> +      ESP_LOGE(TAG, "  sensor model undefined, set 'model' option in YAML");
It will always be set, no need to handle default.
```suggestion
```

2024-07-11 08:22 UTC, Mafus1 commented
@soeffi, the changes look good to me! I tested it and it behaves as expected. I like the option with the enum to extend it to further models in the future.
@jesserockz made two comments about small improvements, maybe you can apply them, and then I think this should be ready to merge.

2024-07-11 20:27 UTC, soeffi commented on esphome/components/jsn_sr04t/jsn_sr04t.cpp
> +      ESP_LOGE(TAG, "  sensor model undefined, set 'model' option in YAML");
Typically, I'd try to check as much as possible, just in case. However, for embedded devices, it's probably better to reduce code size...

2024-07-11 20:57 UTC, Mafus1 approved these changes

2024-07-11 21:28 UTC, jesserockz approved these changes

2024-07-11 21:29 UTC, jesserockz commented on esphome/components/jsn_sr04t/jsn_sr04t.cpp
> +      ESP_LOGE(TAG, "  sensor model undefined, set 'model' option in YAML");
Yes its good to cover everything. Our CI will fail if all switch cases are not handled for this specifically though.

2024-07-11 21:30 UTC, merged