nrf52 core based on zephyr
OttoWinter/esphomeyaml pull request #7049
Opened 2024-07-06 16:35 UTC by tomaszduda23

# What does this implement/fix?

Core part of https://github.com/esphome/esphome/pull/6075. The rest could be added as external components.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-22 01:31 UTC, jesserockz requested changes
Please add an env to `platformio.ini` and add it to the CI matrix so that clang-tidy etc is run correctly

2024-07-22 01:31 UTC, jesserockz commented on esphome/config_validation.py
> +    PLATFORM_NRF52,
Please put this in its alphabetical order position.

2024-07-22 01:31 UTC, jesserockz commented on esphome/components/logger/logger_zephyr.cpp
> +  if (this->uart_ != UART_SELECTION_USB_CDC || nullptr == uart_dev_) {
Please make sure any instance members are prefixed with `this->`
```suggestion
  if (this->uart_ != UART_SELECTION_USB_CDC || nullptr == this->uart_dev_) {
```

2024-07-22 01:31 UTC, jesserockz commented on esphome/components/zephyr/core.cpp
> +
no implementation of `delayMicroseconds` (and other functions in `esphome/core/hal.h`?

2024-07-22 01:31 UTC, jesserockz commented on esphome/components/nrf52/gpio.py
> +GPIOPin = zephyr_ns.class_("ZephyrGPIOPin", cg.InternalGPIOPin)
Class names should always match here to cause less confusion
```suggestion
ZephyrGPIOPin = zephyr_ns.class_("ZephyrGPIOPin", cg.InternalGPIOPin)
```

2024-07-22 01:31 UTC, jesserockz commented on esphome/components/nrf52/__init__.py
> +            "platformio/toolchain-gccarmnoneeabi@https://github.com/tomaszduda23/toolchain-sdk-ng",
Can we get versions on these please?

2024-07-22 09:58 UTC, tomaszduda23 commented on esphome/components/zephyr/core.cpp
> +
added

2024-07-22 10:52 UTC, tomaszduda23 commented on esphome/config_validation.py
> +    PLATFORM_NRF52,
done

2024-07-22 22:53 UTC, jesserockz commented
@tomaszduda23 please don't force push after a review has started as it makes showing changes since the review a lot harder
The commit history doesn't have to be pretty as we squash and merge anyway

2024-07-23 04:35 UTC, tomaszduda23 commented on esphome/components/nrf52/__init__.py
> +            "platformio/toolchain-gccarmnoneeabi@https://github.com/tomaszduda23/toolchain-sdk-ng",
done

2024-07-23 09:42 UTC, tomaszduda23 commented on esphome/components/logger/__init__.py
> +    zephyr_add_cdc_acm,
Make alphabetical order

2024-08-12 05:46 UTC, lboue commented
> Please add an env to `platformio.ini` and add it to the CI matrix so that clang-tidy etc is run correctly

What was added as env in the file is not correct?

https://github.com/esphome/esphome/pull/7049/files#diff-4446afd728a4f34cbcddc306a9cb6be845d1a61c216076a295683bcc9c106724R186-R203

```
; This is the common settings for the nRF52 using Zephyr.
[common:nrf52-zephyr]
extends = common
platform = platformio/nordicnrf52@10.3.0
framework = zephyr
platform_packages =
    platformio/framework-zephyr @ https://github.com/tomaszduda23/framework-sdk-nrf/archive/refs/tags/v2.6.1.zip
    platformio/toolchain-gccarmnoneeabi@https://github.com/tomaszduda23/toolchain-sdk-ng/archive/refs/tags/v0.16.1.zip
build_flags =
    ${common.build_flags}
    -DUSE_ZEPHYR
    -DUSE_NRF52
lib_deps =
    bblanchon/ArduinoJson@7.0.0           ; json
    wjtje/qr-code-generator-library@1.7.0  ; qr_code
    lvgl/lvgl@8.4.0                                       ; lvgl
    pavlodn/HaierProtocol@0.9.31           ; haier
```

2024-08-20 08:41 UTC, dwmw2 requested changes

2024-08-20 08:41 UTC, dwmw2 commented on esphome/components/md5/md5.h
> +#ifndef USE_ZEPHYR
Is this because Zephyr doesn't give us an MD5 implementation to use? Shouldn't we mark the md5 component as being unsupported in that case, rather than silently making the header file empty? 

We can also have a native implementation of MD5 as a fallback if the underlying platform doesn't provide one.

2024-08-20 09:10 UTC, tomaszduda23 commented on esphome/components/md5/md5.h
> +#ifndef USE_ZEPHYR
It is just to silence clang-tidy. I will add comment there. For now md5 is not needed. It can be implemented on zephyr in the future.

2024-08-20 09:18 UTC, dwmw2 commented on esphome/components/md5/md5.h
> +#ifndef USE_ZEPHYR
Why doesn't clang-tidy like it? Because of the lack of an implementation?

2024-08-20 10:11 UTC, tomaszduda23 commented on esphome/components/md5/md5.h
> +#ifndef USE_ZEPHYR
Exactly. It complain about missing types.

2024-08-20 15:46 UTC, tomaszduda23 commented on esphome/components/md5/md5.h
> +#ifndef USE_ZEPHYR
USE_MD5 was added to follow similar patter as for other components.

2024-09-22 13:01 UTC, lboue commented
There is change requested by the CI job [30325917252](https://github.com/esphome/esphome/actions/runs/10924911772/job/30325917252?pr=7049):


```
Your formatting is not correct, ESPHome uses clang-format to format
all source files in a unified way. Please apply the changes listed below

The following files need to be changed:
  esphome/components/weikai/weikai.h

diff --git a/esphome/components/weikai/weikai.h b/esphome/components/weikai/weikai.h
index 042c729..8953d30 100644
--- a/esphome/components/weikai/weikai.h
+++ b/esphome/components/weikai/weikai.h
@@ -209,7 +209,7 @@ class WeikaiComponent : public Component {
 
   /// @brief store the name for the component
   /// @param name the name as defined by the python code generator
-  void set_name(std::string name) { this->name_ = std::move(name); }
+  void set_name(const std::string& name) { this->name_ = std::move(name); }
 
   /// @brief Get the name of the component
   /// @return the name
@@ -[30](https://github.com/esphome/esphome/actions/runs/10924911772/job/30325917252?pr=7049#step:10:31)8,7 +308,7 @@ class WeikaiChannel : public uart::UARTComponent {
 
   /// @brief The name as generated by the Python code generator
   /// @param name of the channel
-  void set_channel_name(std::string name) { this->name_ = std::move(name); }
+  void set_channel_name(const std::string& name) { this->name_ = std::move(name); }
 
   /// @brief Get the channel name
   /// @return the name
```

2024-09-22 13:10 UTC, tomaszduda23 commented
Clang-tidy includes all headers. Probably it triggers error. It is small fix. Does not make sense to fix after each merge from dev branch. Most likely will be broken again after a while.

2024-12-11 06:23 UTC, lboue commented
Do you have any news about this request?

2025-01-24 10:15 UTC, Hedda commented
> Do you have any news about this request?

FYI, looks like this is making progress with ESPHome now merged new feature patch by @tomaszduda23 to allow adding support for nrf52 (and potentially also others) as a custom platform:

* https://github.com/esphome/esphome/pull/7616

PS: Slighty off-topic but FYI, Nordic Semi has now released new nRF54L Series including a much more powerful nRF54L15 SoC:

* https://docs.nordicsemi.com/category/nrf-54L-series
  * https://www.nordicsemi.com/Products/nRF54L15
    * https://www.nordicsemi.com/Products/Development-hardware/nRF54L15-DK

"_nRF54L15 is suitable for products using [Bluetooth Low Energy](https://www.nordicsemi.com/Products/Wireless/Bluetooth-Low-Energy), [Bluetooth Mesh](https://www.nordicsemi.com/Products/Wireless/Bluetooth-Mesh), [Zigbee](https://www.nordicsemi.com/Products/Wireless/Zigbee), [Thread](https://www.nordicsemi.com/Products/Wireless/Thread), [Matter](https://www.nordicsemi.com/Products/Technologies/Matter), [Amazon Sidewalk](https://www.nordicsemi.com/Products/Technologies/Amazon-Sidewalk), and [proprietary 2.4 GHz protocols](https://www.nordicsemi.com/Products/Wireless/2-4-GHz-proprietary). In addition, it can run a Wi-Fi stack for the nRF70 Series companion ICs._

_nRF54L15 is the largest memory option in the nRF54L Series, with 1.5 MB NVM and 256 KB RAM, for more demanding applications, while still being cost-optimized for high-volume applications. nRF54L10 and nRF54L05 are smaller memory options._

_The nRF54L Series tab below and the ["nRF54L Series now widely available for development"](https://devzone.nordicsemi.com/nordic/nordic-blog/b/blog/posts/nrf54l-series-now-widely-available-for-development) DevZone blog post provide more information about the nRF54L Series and the different SoC options._"

2025-01-25 13:15 UTC, tomaszduda23 commented
It can be build as external component using latest dev version of esphome. The files has to be copied manually though.
The location of files is as follow:

adafruit bootloader:
`build_dir/zephyr/zephyr.uf2` - For flashing via Adafruit nRF52 Bootloader as a flash drive.
`build_dir/firmware.zip` - For flashing via adafruit-nrfutil using USB CDC

mcuboot bootloader:
`build_dir/zephyr/zephyr.hex` - For flashing via pyocd using SWD.

2025-02-26 18:44 UTC, tomaszduda23 commented on esphome/components/nrf52/__init__.py
> +        return True
fix mt

2025-03-04 09:02 UTC, bdraco commented on esphome/components/zephyr/__init__.py
> +    CORE.data[KEY_ZEPHYR][KEY_EXTRA_BUILD_FILES] = {}
```suggestion
    CORE.data[KEY_ZEPHYR] = {
        KEY_BOARD: config[CONF_BOARD],
        KEY_PRJ_CONF: {},
        KEY_OVERLAY: "",
        KEY_BOOTLOADER: config[KEY_BOOTLOADER],
        KEY_EXTRA_BUILD_FILES: {},
    }
```

2025-03-04 09:05 UTC, bdraco commented on esphome/components/zephyr/__init__.py
> +        CORE.data[KEY_ZEPHYR][KEY_PRJ_CONF][name] = (value, required)
```suggestion
def zephyr_add_prj_conf(name: str, value: PrjConfValueType, required: bool = True) -> None:
    """Set an zephyr prj conf value."""
    if not name.startswith("CONFIG_"):
        name = "CONFIG_" + name
    prj_conf = CORE.data[KEY_ZEPHYR][KEY_PRJ_CONF]
    if name not in prj_conf:
        prj_conf[name] = (value, required)
        return
    old_value, old_required = prj_conf[name]
    if old_value != value and old_required:
        raise ValueError(
            f"{name} already set with value '{old_value}', cannot set again to '{value}'"
        )
    if required:
        prj_conf[name] = (value, required)
```

2025-03-04 09:07 UTC, bdraco commented on esphome/components/zephyr/__init__.py
> +    return False
```suggestion
    extra_build_files = CORE.data[KEY_ZEPHYR][KEY_EXTRA_BUILD_FILES]
    if filename not in extra_build_files:
        extra_build_files[filename] = {KEY_NAME: filename, KEY_PATH: path}
        return True
    return False
```

2025-03-04 09:08 UTC, bdraco commented on esphome/components/zephyr/__init__.py
> +        )
```suggestion
    for file in CORE.data[KEY_ZEPHYR][KEY_EXTRA_BUILD_FILES].values():
        copy_file_if_changed(
            file[KEY_PATH],
            CORE.relative_build_path(file[KEY_NAME]),
        )
```

2025-03-04 09:09 UTC, bdraco commented on esphome/components/zephyr/__init__.py
> +    want_opts = CORE.data[KEY_ZEPHYR][KEY_PRJ_CONF]
Might be a bit cleaner to do something like
`zephyr_data = CORE.data[KEY_ZEPHYR]`

than replace all `CORE.data[KEY_ZEPHYR]` with `zephyr_data`

even better if you make `zephyr_data` a [`TypedDict`](https://peps.python.org/pep-0589/)

2025-03-04 11:05 UTC, tomaszduda23 commented on esphome/components/zephyr/__init__.py
> +    want_opts = CORE.data[KEY_ZEPHYR][KEY_PRJ_CONF]
done

2025-03-14 20:40 UTC, felipejfc commented
@tomaszduda23 I have been working on openthread support for nrf52 based on these PRs of yours and also by #7506 

here: https://github.com/felipejfc/esphome/tree/nrf52-ot

I've got openthread, IPV6, sockets, mdns all working on nrf52 chip, consequently api component works, allowing for seamless integration with homeassistant. Also anything else that's based on ip connectivity and sockets will work such as mqtt!

generated bunch of the code with AI so its not beautiful and that's y I didn't open PR yet

example config:

```
nrf52:
  board: adafruit_itsybitsy_nrf52840

esphome:
  name: nrf52-test-nrf

#encryption support is not working but plaintext integration is working fine!
api:

logger:
  level: DEBUG
  logs:
    switch: NONE

switch:
  - platform: gpio
    pin:
      number: 15
      inverted: true
      mode:
        output: true
    id: gpio_15

interval:
  - interval: 500ms
    then:
      - switch.toggle: gpio_15

output:
  - platform: gpio
    pin:
      number: 14
      inverted: true
      mode:
        output: true
    id: rest_gpio

# Enable IPv6 networking
network:
  enable_ipv6: true

# Enable OpenThread
zephyr_openthread:
  channel: 25
  panid: 0xe064
  network_name: "MyHome5"
  xpanid: "1db74a0a3797454b"
  network_key: "e1d4b93b0d4xxxxxxxx6f3d982fa4ac0"
  pskc: "e1d4b93b0d4724xxxxxxxxd982fa4ac0"
  force_dataset: true

# Add a text sensor to display the IPv6 address
text_sensor:
  - platform: template
    name: "Thread IPv6 Address"
    id: thread_ipv6
    update_interval: 60s
    lambda: |-
      if (zephyr_openthread::global_openthread_component->has_ipv6_address()) {
        return zephyr_openthread::global_openthread_component->get_ipv6_address();
      }
      return {"No IPv6 Address"};

2025-03-15 09:37 UTC, tomaszduda23 commented
@felipejfc nice. Thanks for the effort. If you open draft PR it would be easier to look on the changes. Please include `external_components` in your example. That way it could be used for testing.

2025-03-15 12:44 UTC, felipejfc commented
> @felipejfc nice. Thanks for the effort. If you open draft PR it would be easier to look on the changes. Please include `external_components` in your example. That way it could be used for testing.

done: https://github.com/esphome/esphome/pull/8410

2025-03-20 19:21 UTC, tomaszduda23 commented
Version `2025.3.0` can build and "Manual download" firmware from dashboard.

2025-05-15 16:15 UTC, bdraco commented on esphome/components/logger/logger.cpp
> +  this->main_task_ = k_current_get();
Is this used?

2025-05-15 16:27 UTC, bdraco commented on esphome/components/nrf52/__init__.py
> +from pathlib import Path
```diff
diff --git a/esphome/components/nrf52/__init__.py b/esphome/components/nrf52/__init__.py
index 6a25d5a3c..7c2c2b349 100644
--- a/esphome/components/nrf52/__init__.py
+++ b/esphome/components/nrf52/__init__.py
@@ -1,3 +1,5 @@
+from __future__ import annotations
+
 from pathlib import Path
 
 import esphome.codegen as cg
@@ -22,6 +24,8 @@ from esphome.const import (
     KEY_TARGET_PLATFORM,
 )
 from esphome.core import CORE, EsphomeError, coroutine_with_priority
+from esphome.storage_json import StorageJSON
+from esphome.types import ConfigType
 
 from .boards import BOARDS_ZEPHYR, BOOTLOADER_CONFIG
 from .const import (
@@ -40,7 +44,7 @@ IS_TARGET_PLATFORM = True
 PLATFORM_NRF52 = "nrf52"
 
 
-def set_core_data(config):
+def set_core_data(config: ConfigType) -> ConfigType:
     zephyr_set_core_data(config)
     CORE.data[KEY_CORE][KEY_TARGET_PLATFORM] = PLATFORM_NRF52
     CORE.data[KEY_CORE][KEY_TARGET_FRAMEWORK] = KEY_ZEPHYR
@@ -61,29 +65,28 @@ BOOTLOADERS = [
 ]
 
 
-def _detect_bootloader(value):
-    value = value.copy()
-    bootloaders = []
+def _detect_bootloader(config: ConfigType) -> ConfigType:
+    """Detect the bootloader for the given board."""
+    config = config.copy()
+    bootloaders: list[str] = []
+    board = config[CONF_BOARD]
 
-    if (
-        value[CONF_BOARD] in BOARDS_ZEPHYR
-        and KEY_BOOTLOADER in BOARDS_ZEPHYR[value[CONF_BOARD]]
-    ):
+    if board in BOARDS_ZEPHYR and KEY_BOOTLOADER in BOARDS_ZEPHYR[board]:
         # this board have bootloaders config available
-        bootloaders = BOARDS_ZEPHYR[value[CONF_BOARD]][KEY_BOOTLOADER]
+        bootloaders = BOARDS_ZEPHYR[board][KEY_BOOTLOADER]
 
-    if KEY_BOOTLOADER not in value:
+    if KEY_BOOTLOADER not in config:
         if bootloaders:
             # there is no bootloader in config -> take first one
-            value[KEY_BOOTLOADER] = bootloaders[0]
+            config[KEY_BOOTLOADER] = bootloaders[0]
         else:
             # make mcuboot as default if there is no configuration for that board
-            value[KEY_BOOTLOADER] = BOOTLOADER_MCUBOOT
-    elif bootloaders and value[KEY_BOOTLOADER] not in bootloaders:
+            config[KEY_BOOTLOADER] = BOOTLOADER_MCUBOOT
+    elif bootloaders and config[KEY_BOOTLOADER] not in bootloaders:
         raise cv.Invalid(
-            f"{value[CONF_BOARD]} does not support {value[KEY_BOOTLOADER]}, select one of: {', '.join(bootloaders)}"
+            f"{config[CONF_BOARD]} does not support {config[KEY_BOOTLOADER]}, select one of: {', '.join(bootloaders)}"
         )
-    return value
+    return config
 
 
 CONFIG_SCHEMA = cv.All(
@@ -99,7 +102,8 @@ CONFIG_SCHEMA = cv.All(
 
 
 @coroutine_with_priority(1000)
-async def to_code(config):
+async def to_code(config: ConfigType) -> None:
+    """Convert the configuration to code."""
     cg.add_platformio_option("board", config[CONF_BOARD])
     cg.add_build_flag("-DUSE_NRF52")
     cg.add_define("ESPHOME_BOARD", config[CONF_BOARD])
@@ -128,11 +132,13 @@ async def to_code(config):
     zephyr_to_code(config)
 
 
-def copy_files():
+def copy_files() -> None:
+    """Copy files to the build directory."""
     zephyr_copy_files()
 
 
-def get_download_types(storage_json):
+def get_download_types(storage_json: StorageJSON) -> list[dict[str, str]]:
+    """Get the download types for the firmware."""
     types = []
     UF2_PATH = "zephyr/zephyr.uf2"
     DFU_PATH = "firmware.zip"
@@ -181,7 +187,9 @@ def get_download_types(storage_json):
     return types
 
 
-def _upload_using_platformio(config, port, upload_args):
+def _upload_using_platformio(
+    config: ConfigType, port: str, upload_args: list[str]
+) -> int | str:
     from esphome import platformio_api
 
     if port is not None:
@@ -189,7 +197,7 @@ def _upload_using_platformio(config, port, upload_args):
     return platformio_api.run_platformio_cli_run(config, CORE.verbose, *upload_args)
 
 
-def upload_program(config, args, host):
+def upload_program(config: ConfigType, args, host: str) -> bool:
     from esphome.__main__ import check_permissions, get_port_type
 
     result = 0
```

I think some of these have type available now

2025-05-15 16:49 UTC, bdraco commented
This looks like it nearly ready to go

2025-05-15 16:58 UTC, tomaszduda23 commented on esphome/components/logger/logger.cpp
> +  this->main_task_ = k_current_get();
It is now to get name of task.

2025-05-15 17:10 UTC, tomaszduda23 commented on esphome/components/nrf52/__init__.py
> +from pathlib import Path
fixed

2025-05-15 17:11 UTC, bdraco approved these changes, later dismissed

2025-07-02 12:20 UTC, jesserockz commented on esphome/components/time/real_time_clock.h
> +  void add_on_time_sync_callback(std::function<void()> &&callback) {
This should be its own PR

2025-07-02 12:20 UTC, jesserockz commented on esphome/components/zephyr/gpio.cpp
> +  snprintf(buffer, sizeof(buffer), "GPIO%u", this->pin_);
You don't want to convert this back to the P0.0 format as well?

2025-07-02 13:05 UTC, tomaszduda23 commented on esphome/components/time/real_time_clock.h
> +  void add_on_time_sync_callback(std::function<void()> &&callback) {
done

2025-07-02 13:13 UTC, tomaszduda23 commented on esphome/components/zephyr/gpio.cpp
> +  snprintf(buffer, sizeof(buffer), "GPIO%u", this->pin_);
done

2025-07-05 13:25 UTC, bdraco commented
InterruptLock doesn't seem to be implemented for this platform. It looks like there might be irq_lock()/irq_unlock() ?

2025-07-05 13:36 UTC, tomaszduda23 commented
> InterruptLock doesn't seem to be implemented for this platform. It looks like there might be irq_lock()/irq_unlock() ?

It looks like. I've not seen this class before.

2025-07-05 14:07 UTC, tomaszduda23 commented
> InterruptLock doesn't seem to be implemented for this platform. It looks like there might be irq_lock()/irq_unlock() ?

fixed

2025-07-05 14:12 UTC, bdraco approved these changes

2025-07-07 04:45 UTC, jesserockz approved these changes, later dismissed

2025-07-07 18:36 UTC, bdraco approved these changes, later dismissed

2025-07-07 23:21 UTC, jesserockz submitted a review, later dismissed

2025-07-07 23:22 UTC, jesserockz approved these changes

2025-07-13 02:48 UTC, bdraco approved these changes

2025-07-16 01:00 UTC, merged