Rename bmp280 to bmp280_i2c.
OttoWinter/esphomeyaml pull request #7053
Opened 2024-07-07 20:03 UTC by ademuri

This is in preparation for adding a bmp280_spi component, similar to

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-18 23:10 UTC, jesserockz requested changes
Please leave a minimal file in place at `bmp280/__init__.py` and `bmp280/sensor.py` similar to `bmp3xx`

2024-07-18 23:10 UTC, jesserockz commented on esphome/components/bmp280_base/__init__.py
> +CODEOWNERS = ["@esphome/core"]
This is not "owned" by the core team. Either this needs to be owned by you as the person making this PR, or just leave it blank as you are only moving the base code. You can ignore the bot message in this case.

```suggestion
```

2024-07-21 20:04 UTC, jesserockz requested changes

2024-07-21 20:04 UTC, jesserockz commented on esphome/components/bmp280_spi/sensor.py
> +DEPENDENCIES = ["spi"]
Not sure why you removed as codeowner on the actual new component you are adding yourself...
```suggestion
CODEOWNERS = ["@ademuri"]
DEPENDENCIES = ["spi"]
```

2024-07-21 20:04 UTC, jesserockz commented on esphome/components/bmp280/sensor.py
> +CODEOWNERS = ["@ademuri"]
A codeowner is not needed for removed components
```suggestion
```

2024-07-21 20:04 UTC, jesserockz commented on esphome/components/bmp280/sensor.py
> +CONFIG_SCHEMA = CONFIG_SCHEMA = cv.invalid(
```suggestion
CONFIG_SCHEMA = cv.invalid(
```

2024-08-07 02:48 UTC, ademuri commented on esphome/components/bmp280/sensor.py
> +CODEOWNERS = ["@ademuri"]
Done - I mistakenly added it here instead of in `bmp280_spi/sensor.py`.

2024-08-23 21:37 UTC, ademuri commented
Apologies for the spam, I accidentally rebased against the wrong dev branch. I did in fact apply all of the requested changes, but Github is showing one of them as outstanding.

2024-08-25 06:50 UTC, kbx81 requested changes, later dismissed
Couple other quick remarks

2024-08-25 06:50 UTC, kbx81 commented on esphome/components/bmp280_base/__init__.py
> +    CONF_OVERSAMPLING,
```suggestion
    CONF_ID,
    CONF_IIR_FILTER,
    CONF_OVERSAMPLING,
    CONF_PRESSURE,
    CONF_TEMPERATURE,
    DEVICE_CLASS_PRESSURE,
    DEVICE_CLASS_TEMPERATURE,
    STATE_CLASS_MEASUREMENT,
    UNIT_CELSIUS,
    UNIT_HECTOPASCAL,
```

2024-08-25 06:50 UTC, kbx81 commented on tests/components/bmp280_i2c/common.yaml
> +      id: bmp280_pressure
We should leave `iir_filter: 16x` in as it appears it is still in the config. (Same for SPI config)

2024-08-25 16:37 UTC, ademuri commented on tests/components/bmp280_i2c/common.yaml
> +      id: bmp280_pressure
Good point. Done.

2024-09-05 02:42 UTC, jesserockz approved these changes

2024-09-05 03:48 UTC, jesserockz commented
:facepalm: Merging dev back in again after approval means I now have to wait for the CI to run again...haha

2024-09-05 05:08 UTC, merged