Add Candle and Fireplace Light Effects.
OttoWinter/esphomeyaml pull request #7055
Opened 2024-07-08 05:00 UTC by TikiBill

This is a new feature which adds a new, highly-configurable candle and fireplace flame effect. The candle effect goes dim from a baseline, and the fireplace goes brighter from a baseline.

The documentation pull request along with sample yaml can be found here:
https://github.com/esphome/esphome-docs/pull/4028

2024-07-10 10:16 UTC, kbx81 commented on esphome/components/light/flame_light_effects.cpp
> +  ESP_LOGD("FlameLightEffect", "start()    Speed: %lums   Jitter: %lu", this->transition_length_ms_,
```suggestion
  ESP_LOGD("FlameLightEffect", "start()    Speed: %" PRIu32" ms   Jitter: %" PRIu32, this->transition_length_ms_,
```

2024-07-10 10:17 UTC, kbx81 commented on esphome/components/light/flame_light_effects.cpp
> +  ESP_LOGD("FlameLightEffect", "start()    Speed: %lums   Jitter: %lu", this->transition_length_ms_,
Be sure to also `#include <cinttypes>`

2024-07-11 04:29 UTC, jesserockz requested changes
Please do not delete the pull request template and fill out the relevant sections correctly

2024-07-26 22:17 UTC, TikiBill reviewed
I restored the original template in the initial pull request comment. I believe that covers the changes requested thus far.

2024-09-18 00:54 UTC, TikiBill commented
@jesserockz I restored the original template in the initial pull request comment. I believe that covers the changes requested thus far.

2025-10-13 00:50 UTC, closed without merging