Add support for Daikin BRC52A61
OttoWinter/esphomeyaml pull request #7068
Opened 2024-07-10 15:41 UTC by andrewkww

# What does this implement/fix?

Add support for Daikin BRC52A61

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2670

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
climate:
  - platform: daikin_brc52a61
    name: "AC"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-04 09:25 UTC, thloh85-starfivetech commented
Tested on my HA and works correctly

2024-09-05 19:27 UTC, SodaWithoutSparkles commented
I suggest testing again on esp-idf. The current solution of hacking the irremoteesp8266 lib does _not_ work on esp-idf. 

I hope that this PR can change that as esp-idf is more efficient and allows cheaper esp32c3 to be used.

2024-09-06 07:05 UTC, andrewkww commented
I just made a small update to the docs to mention `BRC52A62` as well.

https://deploy-preview-4032--esphome.netlify.app/components/climate/climate_ir#daikin-brc52a61

This PR seems to be working, so it'd be great if it can be merged soon.

2024-09-06 21:30 UTC, SodaWithoutSparkles commented
@andrewkww I've just thought of sth. When the physical remote is used, there is a chance for the status of the AC to de-sync with esphome (and in turn, HA). This wont cause the air-con to flip its state as you've used the workaround, but automations based on the state of the AC wont work.

Maybe an option to use an external binary sensor would be ideal.

2024-09-08 13:22 UTC, andrewkww commented
> @andrewkww I've just thought of sth. When the physical remote is used, there is a chance for the status of the AC to de-sync with esphome (and in turn, HA). This wont cause the air-con to flip its state as you've used the workaround, but automations based on the state of the AC wont work.
> 
> The workaround may also override the current timers but that function is seldom used anyway.
> 
> Maybe an option to use an external binary sensor would be ideal. For example, a door sensor glued to the indoor AC exhaust to detect if the flap of the unit is open/closed.

I kind of thought about the issue with using the physical remote as well. But this issue exists for all IR Remote Climate, not only this AC model. Also, in practice, I think this probably isn't too big of a problem either. If the actual state and the HA state are different, we have two scenarios: 1) HA tries to turn AC on, but it's already on, or 2) HA tries to turn AC off, but it's already off. Neither should cause an issue.

This would be a problem if the component was implemented as a "toggle", since we would be toggling the AC to the wrong state. But since we're using a workaround to "set" it to on or off, this probably isn't an issue.

> Also I dont think this component updates the clock on the AC? It would be a "nice to have", but given that any timers would probably on HA, this wont be as relevant.

I think the clock on the AC is only used for on/off timer. If someone is using HA to control the AC, then presumably the timer would be on HA instead. Having both automation on HA and timers on the AC would probably get into some weird situations.

2024-09-09 12:21 UTC, RFDarter requested changes

2024-09-09 12:21 UTC, RFDarter commented on esphome/components/daikin_brc52a61/daikin_brc52a61.cpp
> +
```suggestion
  IRData irdata{{{0x16}}};
  irdata.mode = this->operation_mode_();
  irdata.fan_speed = this->fan_speed_();
  irdata.temperature = this->temperature_();
  irdata.swing = this->swing_();
  irdata.set_power(this->mode != climate::CLIMATE_MODE_OFF);
  irdata.set_checksum();

```

2024-11-12 07:23 UTC, andrewkww commented
Any updates on when this change can be merged?
Github bot just marked the docs change to be stale.

2025-01-14 12:51 UTC, andrewkww commented
@jesserockz It's been a while since I submitted this PR.
Is there anything further that needs to be done for this PR?
Is it possible to have this PR merged? Thanks.

2025-04-29 07:44 UTC, thloh85 commented
Hi are there any reviewer who can help do the PR for this?
I tested this and is working correctly.

2025-08-10 10:21 UTC, ilfuriano commented
Hi, I have the remote control with model R04089036295A, I used this PR for about 8 months and it worked properly. Now I can turn on the air conditioner by setting the HVAC modes, but I can no longer turn it off.

2025-11-16 00:50 UTC, closed without merging