ac_dimmer updated to work with ESP-IDF
OttoWinter/esphomeyaml pull request #7072
Opened 2024-07-10 21:08 UTC by latonita

# What does this implement/fix?

AC_DIMMER only woks with Arduino. 
This is minor update to make it work under ESP-IDF framework.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-10 22:07 UTC, randybb commented
Nice, but one thing. Make it please compatible with IDF 5.x. With 5.1.2 it is not compiling:
```
Compiling .pioenvs/mcu-dimmer/src/esphome/components/ac_dimmer/hw_timer_esp_idf.o
In file included from src/esphome/components/ac_dimmer/hw_timer_esp_idf.h:3,
                 from src/esphome/components/ac_dimmer/hw_timer_esp_idf.cpp:3:
/data/cache/platformio/packages/framework-espidf@3.50102.240122/components/driver/deprecated/driver/timer.h:16:2: warning: #warning "legacy timer group driver is deprecated, please migrate to driver/gptimer.h" [-Wcpp]
   16 | #warning "legacy timer group driver is deprecated, please migrate to driver/gptimer.h"
      |  ^~~~~~~
src/esphome/components/ac_dimmer/hw_timer_esp_idf.cpp:7:10: fatal error: esp32/clk.h: No such file or directory
    7 | #include "esp32/clk.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/mcu-dimmer/src/esphome/components/ac_dimmer/hw_timer_esp_idf.o] Error 1
In file included from src/esphome/components/ac_dimmer/hw_timer_esp_idf.h:3,
                 from src/esphome/components/ac_dimmer/ac_dimmer.cpp:16:
/data/cache/platformio/packages/framework-espidf@3.50102.240122/components/driver/deprecated/driver/timer.h:16:2: warning: #warning "legacy timer group driver is deprecated, please migrate to driver/gptimer.h" [-Wcpp]
   16 | #warning "legacy timer group driver is deprecated, please migrate to driver/gptimer.h"
      |  ^~~~~~~
```

2024-07-10 22:26 UTC, latonita commented
Yes, I know. Timers were changed.
I will try fix it soon.

2024-07-15 09:24 UTC, latonita commented
@randybb what exactly are your version numbers are in yaml? platform_version and version 
```
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    platform_version: 6.7.0
    version: 5.2.1
```

2024-07-15 09:45 UTC, randybb commented
@latonita 
I have tested two version: 5.1.2 and 5.2.1 (I am using this on all my devices):
```yaml
esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    version: 5.1.2
    # version: 5.2.1
    platform_version: 6.6.0
```

2024-07-15 13:18 UTC, latonita commented
@randybb happy to try new version?

2024-07-15 15:18 UTC, randybb commented
Tested with 5.1, 5.2 and the default 4.4 one. All good. Many thanks!

2025-04-23 21:32 UTC, VasilKalchev commented
Tested on ESP32-C3 with ESP-IDF 5.1.5 - works correctly!

This fixes an issue on ESP32-C3 with the Arduino framework where the gate pin misses a switch, causing the light to flicker constantly.

2025-05-26 08:28 UTC, gyp5y commented
Please merge.

2025-07-18 11:10 UTC, jesserockz requested changes
If someone wants to pick up this PR, please do. It should be able to make it a lot smaller now that ESPHome uses IDF5+ for both idf and arduino, and they both use the same idf version by default. No idf4 support is required.

2025-07-18 13:03 UTC, latonita commented
> If someone wants to pick up this PR, please do. It should be able to make it a lot smaller now that ESPHome uses IDF5+ for both idf and arduino, and they both use the same idf version by default. No idf4 support is required.

I will drop IDF4 support from the PR

2025-07-18 16:56 UTC, latonita commented
@randybb @VasilKalchev do you have a chance to test this latest PR on real appliances? Thanks

2025-07-18 19:29 UTC, jesserockz commented
Seems my codeowners script needs to check for previous mentions :see_no_evil: 

Thanks for updating the PR

2025-07-18 19:29 UTC, randybb commented
will try on Monday

2025-07-21 17:12 UTC, randybb commented
With a fan still working fine, but I tested it with a "standard" bulb and LED bulb from a trashcan and both are blinking when on less than 100 %. Since I tested such lights for the first time not sure if this is the standard behavior, maybe this is the problem that everybody was reporting. Since the blinking was not regular (like from a horror movie :P) - maybe the zero cross is not syncing it correctly.

But for a fan not an issue and it is building just fine with idf 5.4.2.

2025-07-21 17:43 UTC, latonita commented
Is behaviour the same if you compile arduino version? I mean flickering still there or goes away?
Can you try if not yet tried?
Thanks
________________________________
From: Roman Priesol ***@***.***>
Sent: Monday, July 21, 2025 19:13
To: esphome/esphome ***@***.***>
Cc: Anton Viktorov ***@***.***>; Mention ***@***.***>
Subject: Re: [esphome/esphome] [ac_dimmer] Added support for ESP-IDF (5+) (PR #7072)

[https://avatars.githubusercontent.com/u/206765?s=20&v=4]randybb left a comment (esphome/esphome#7072)<https://github.com/esphome/esphome/pull/7072#issuecomment-3097641864>

With a fan still working fine, but I tested it with a "standard" bulb and LED bulb from a trashcan and both are blinking when on less than 100 %. Since I tested such lights for the first time not sure if this is the standard behavior, maybe this is the problem that everybody was reporting. Since the blinking was not regular (like from a horror movie :P) - maybe the zero cross is not syncing it correctly.

But for a fan not an issue and it is building just fine with idf 5.4.2.

—
Reply to this email directly, view it on GitHub<https://github.com/esphome/esphome/pull/7072#issuecomment-3097641864>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA6O66WA547UBTG7JFJPWZL3JUNSJAVCNFSM6AAAAABKVV5MSOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZTAOJXGY2DCOBWGQ>.
You are receiving this because you were mentioned.

2025-07-25 17:22 UTC, latonita commented
@randybb please check arduino ver, and my email :)

2025-07-28 15:13 UTC, randybb commented
Went finally to my basement. And yes, with arduino it is blinking the same. But as I have mentioned, it was always running only a fan, so don't know it was always blinking with an incandescent bulb.

2025-08-05 04:40 UTC, jesserockz requested changes, later dismissed
Can we clean this up even more and always use the esp-idf APIs directly regardless of the framework if it is an ESP32?

2025-08-05 04:40 UTC, jesserockz commented on esphome/components/ac_dimmer/hw_timer_esp_idf.cpp
> +#endif
What triggers one to be available over the other? I can see only `esp_clk_tree.h` in the current supported esp-idf version

2025-08-05 04:40 UTC, jesserockz commented on esphome/components/ac_dimmer/hw_timer_esp_idf.cpp
> +#ifdef USE_ESP32_FRAMEWORK_ESP_IDF
```suggestion
#ifdef USE_ESP_IDF
```

2025-08-05 04:40 UTC, jesserockz commented on esphome/components/ac_dimmer/hw_timer_esp_idf.h
> +#ifdef USE_ESP32_FRAMEWORK_ESP_IDF
```suggestion
#ifdef USE_ESP_IDF
```

2025-08-05 04:40 UTC, jesserockz commented on esphome/components/ac_dimmer/hw_timer_esp_idf.cpp
> +#if SOC_GPTIMER_SUPPORTED
Looking at esp-idf, all variants have this flag set to 1

2025-08-05 18:53 UTC, latonita commented on esphome/components/ac_dimmer/hw_timer_esp_idf.cpp
> +#if SOC_GPTIMER_SUPPORTED
Good point. I have never asked it myself.
It looks like its espressif's protection for the future. as for now - all the chipsets support general purpose timers

2025-08-05 19:03 UTC, latonita commented on esphome/components/ac_dimmer/hw_timer_esp_idf.cpp
> +#endif
Okay, i took a deeper look into this clk_tree.h, looks like it was introduced in some beta versions of v.5.1 and then replaced by esp_clk_tree.h.
So its safe to simplify now.

2025-08-05 22:09 UTC, latonita commented
> Can we clean this up even more and always use the esp-idf APIs directly regardless of the framework if it is an ESP32?

reworked.

2025-08-06 06:12 UTC, kbx81 submitted a review, later dismissed
Shortening some log messages: https://developers.esphome.io/architecture/logging/#minimizing-impact

2025-08-06 06:12 UTC, kbx81 commented on esphome/components/ac_dimmer/hw_timer_esp_idf.cpp
> +    ESP_LOGE(TAG, "Resolution cannot be reached with any clock source, aborting!");
```suggestion
    ESP_LOGE(TAG, "Resolution not possible; aborting");
```

2025-08-06 06:12 UTC, kbx81 commented on esphome/components/ac_dimmer/hw_timer_esp_idf.cpp
> +    ESP_LOGE(TAG, "Failed to create a new GPTimer, error num=%d", err);
```suggestion
    ESP_LOGE(TAG, "GPTimer creation failed; error %d", err);
```

2025-08-06 06:12 UTC, kbx81 commented on esphome/components/ac_dimmer/hw_timer_esp_idf.cpp
> +    ESP_LOGE(TAG, "Timer Attach Interrupt failed, error num=%d", err);
```suggestion
    ESP_LOGE(TAG, "Timer Attach Interrupt failed; error %d", err);
```

2025-08-06 06:12 UTC, kbx81 commented on esphome/components/ac_dimmer/hw_timer_esp_idf.cpp
> +    ESP_LOGE(TAG, "Timer Detach Interrupt failed, error num=%d", err);
```suggestion
    ESP_LOGE(TAG, "Timer Detach Interrupt failed; error %d", err);
```

2025-08-06 06:12 UTC, kbx81 commented on esphome/components/ac_dimmer/hw_timer_esp_idf.cpp
> +    ESP_LOGE(TAG, "Timer Alarm Write failed, error num=%d", err);
```suggestion
    ESP_LOGE(TAG, "Timer Alarm Write failed; error %d", err);
```

2025-10-28 15:56 UTC, glmnet commented
From usability this works like the arduino version may be. It is not good enough the timing is not great, it does flickers sometimes... I guess the problem is the ESPHome overhead plus may be the wifi or other stuff causing the interrupt timer and zc timer not handling the timing precisely enough.
I have made a test project with bare esp idf and it is better.
From an implementation point of view it seems kind of complex to have all that extra files.

In any case, I was wondering if using RMT won't be more precise here, instead of having two interrupts (ZC + Timer) the work would be done in the ZC timer to setup the RMT delay and just fire it

I will try to get a POC of this working first anyway, but wanted to have some feedback from people using this? It never worked for me in a "usable" way

2025-10-28 16:13 UTC, randybb commented
For me it is good enough as I am using it for a fan (driven as a light as it supports transition time). When I was testing it with a light bulb (LED and incandescent) it was flickering, so any way making it better would help people.

2025-10-29 19:16 UTC, latonita commented
@randybb It does the job to a degree, and it’s fine to use with heaters — but not with bulbs, as firing mismatches can cause them to flicker.
@glmnet so far the logic itself definitely over complicated
I will have time to work on logic refactoring in a week or two and will try to make it simpler. If you have some good results before that - please share, lets fix it. I'm thinking of splitting 8266/32. and maybe using user controlled 50/60 hz freq setting, but thats under question.

2025-10-31 16:29 UTC, glmnet commented
Using your code and disabling Wifi it works quite well, controlling the dimmer with a wired potentiometer. 
According to IA and other sources WiFi will always cause interrupts to not be accurate, best results were found by using RMT and running all other tasks on CORE 0, should be error by less than 10uS so I am currently working on trying to get that working to see what happens. From what I see on the scope errors are sometimes like 1/4 of the waveform which is in the order of ms

Splitting esp32 and esp8266 sounds good

2025-10-31 18:26 UTC, latonita commented
> Using your code and disabling Wifi it works quite well, controlling the dimmer with a wired potentiometer. According to IA and other sources WiFi will always cause interrupts to not be accurate, best results were found by using RMT and running all other tasks on CORE 0, should be error by less than 10uS so I am currently working on trying to get that working to see what happens. From what I see on the scope errors are sometimes like 1/4 of the waveform which is in the order of ms
> 
> Splitting esp32 and esp8266 sounds good

RMT-  never worked with it, dont know what can be done.
Timer based solution - is not mine, it is just migrated from the arduino library, originally this component only worked with arduino libs. Timer based solution is defintely not a great one, but helps to support many dimmers. 

Do we need it? I don't know. I would rather have ONE channel working flawlessly.

I was looking into hardware based solution with on-chip comparators or MCPWM.

2025-11-01 19:58 UTC, glmnet commented
🎉 Got the dimmer working steady enough for lights
Tried with esp_timers but this gptimer also works, the problem is somewhere else...

CORE 0 is used for wifi, so we need to use CORE1 for the dimmer, 
two things needs to be done so interrupts are more reliable:

1. Ensure the GPIO interrupts (zero cross) is triggered in CORE1, interrupts are attached to the core which the attach task is run on, since currently the main task might run on CORE 0 or CORE 1 we need to modify [this ](https://github.com/esphome/esphome/blob/55af8186294b900d52cd31eabd20407f30563286/esphome/components/esp32/core.cpp#L99) or somewhere else to ensure the attach is run from CORE 1
```
xTaskCreatePinnedToCore(loop_task, "loopTask", 8192, nullptr, 1, &loop_task_handle, 1);
```

2. The esp_timer task is also run on CORE 0 by default, this causes the timer to trigger not very accurately also, running timers on CORE 1 is "experimental". I managed to get the esp_timer task to run on CORE 1 by adding these flags (can be be added on output.py to_code)
```
    if CORE.is_esp32 and CORE.using_esp_idf:
        add_idf_sdkconfig_option("CONFIG_ESP_TIMER_SHOW_EXPERIMENTAL", True)
        add_idf_sdkconfig_option("CONFIG_ESP_TIMER_TASK_AFFINITY", "0x01")
        add_idf_sdkconfig_option("CONFIG_ESP_TIMER_TASK_AFFINITY_CPU1", True)
        add_idf_sdkconfig_option("CONFIG_ESP_TIMER_ISR_AFFINITY_CPU1", True)
```


I'm sharing a debug test only branch [here](https://github.com/glmnet/esphome/tree/ac-dimmers-on-core-1), which also lists the tasks and their core:
```
[16:49:58][I][ac_dimmer:280]: loopTask         | Core: 1 | Pri:  1 | Base:  1 | Stack HW:  5628 | RUNNING   | RunTime:      0
[16:49:58][I][ac_dimmer:280]: IDLE0            | Core: 0 | Pri:  0 | Base:  0 | Stack HW:  1068 | READY     | RunTime:      0
[16:49:58][I][ac_dimmer:280]: IDLE1            | Core: 1 | Pri:  0 | Base:  0 | Stack HW:  1060 | READY     | RunTime:      0
[16:49:58][I][ac_dimmer:280]: tiT              | Core: 2147483647 | Pri: 18 | Base: 18 | Stack HW:  2152 | BLOCKED   | RunTime:      0
[16:49:58][I][ac_dimmer:280]: ipc1             | Core: 1 | Pri: 24 | Base: 24 | Stack HW:   352 | SUSPENDED | RunTime:      0
[16:49:58][I][ac_dimmer:280]: ipc0             | Core: 0 | Pri: 24 | Base: 24 | Stack HW:   520 | SUSPENDED | RunTime:      0
[16:49:58][I][ac_dimmer:280]: httpd            | Core: 2147483647 | Pri:  5 | Base:  5 | Stack HW:  3136 | BLOCKED   | RunTime:      0
[16:49:58][I][ac_dimmer:280]: sys_evt          | Core: 0 | Pri: 20 | Base: 20 | Stack HW:  3224 | BLOCKED   | RunTime:      0
[16:49:58][I][ac_dimmer:280]: mdns             | Core: 0 | Pri:  1 | Base:  1 | Stack HW:  2704 | BLOCKED   | RunTime:      0
[16:49:58][I][ac_dimmer:280]: wifi             | Core: 0 | Pri: 23 | Base: 23 | Stack HW:  4516 | BLOCKED   | RunTime:      0
[16:49:58][I][ac_dimmer:280]: esp_timer        | Core: 1 | Pri: 22 | Base: 22 | Stack HW:  3336 | SUSPENDED | RunTime:      0
[16:49:58][I][ac_dimmer:280]: Tmr Svc          | Core: 2147483647 | Pri:  1 | Base:  1 | Stack HW:  1628 | BLOCKED   | RunTime:      0
```

what is important here is the loopTask to be on core 1 and esp_timer to be on core 1

There is logic on the debug branch to ensure the interrupts are attached from CORE 1, but this is not a necessity if loopTask runs from CORE 1.
I will send a PR to attach loopTask to CORE 1 is available (not all ESP32 are dual core), currently it is a bit random of which core is selected.

2025-11-05 11:58 UTC, glmnet commented
#11669 Fixes issue number one.
Now it is required to bring in the second part, esp_timer to run on core 1 also.

2025-11-17 07:10 UTC, VasilKalchev commented
It's off topic now, but I can't reproduce the blinking problem. Last time I tested my device (in April 2025 https://github.com/esphome/esphome/pull/7072#issuecomment-2825546657) with `framework: arduino`, `version: recommended` - it was blinking:
<img width="2560" height="1400" alt="glitch" src="https://github.com/user-attachments/assets/8e7c3d0b-e57a-4275-a35a-8758c83b5855" />
_top is zero-cross, bottom is inverted gate pin_

I switched to this pull request:
```yaml
...
external_components:
  - source: github://pr#7072
    components: [ ac_dimmer ]
...
```
and it fixed the blinking.


Now I can't reproduce the blinking glitch (it's working fine). I've tried:
```yaml
# esphome version: 2025.10.5

esp32:
  variant: esp32c3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    version: recommended

external_components:
  - source: github://pr#7072
    components: [ ac_dimmer ]
```

```yaml
# esphome version: 2025.10.5

esp32:
  variant: esp32c3
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: recommended
```

and

```yaml
# esphome version: 2024.12.4

esp32:
  variant: esp32c3
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: "2.0.17"
```

and they all work fine.

Feel free to delete this comment if it's irrelevant for testing now.

2026-01-06 01:15 UTC, bdraco commented
needs a docs pr to remove ac_dimmer from the components that don't work on idf

2026-01-06 12:26 UTC, latonita commented
> needs a docs pr to remove ac_dimmer from the components that don't work on idf

done https://github.com/esphome/esphome-docs/pull/5870

2026-01-06 20:49 UTC, bdraco commented on esphome/components/ac_dimmer/hw_timer_esp_idf.cpp
> +  for (auto clk_candidate : SOC_GPTIMER_CLKS) {
we check divider for 0. its already safe

2026-01-06 20:49 UTC, bdraco commented
I did some cleanup, removed magic numbers, dead code paths, added error checking, cleaned up casts, removed redundant tests since there is no variant specific code and it otherwise just slows down the CI.

Would you please re-test. If its still good, I think we are good to merge

2026-01-06 20:49 UTC, bdraco approved these changes

2026-01-07 20:18 UTC, latonita commented
@VasilKalchev @glmnet would you please re-test ac_dimmer on your set up ? I will do on mine

2026-01-07 23:40 UTC, latonita commented
@bdraco I have checked updated code on single core c3 - compiles and works well.

as for the flickering - no flickering. there might be tiny shimmering in few set points when there is a lot of wifi comms.
but this have nothing to do with current task 'esp-idf' support.

2026-01-08 14:53 UTC, glmnet commented
I see the part for forcing timer to run on core 1 is not included in the PR. May be it is off topic of the PR but anyway.

 I will test tonight (needs to be dark) with and without the timer on core 1 to check if there are differences.

2026-01-09 01:12 UTC, glmnet approved these changes
Works great, dimmer not flickering noticeably so no need to add the experimental timer on core 1 thing.
I say we send this.

2026-01-09 01:23 UTC, bdraco commented
Thanks @latonita 

Thanks @glmnet

2026-01-09 01:24 UTC, merged