Add on_command trigger to modbus_controller
OttoWinter/esphomeyaml pull request #7078
Opened 2024-07-12 10:17 UTC by leejoow

# What does this implement/fix?

Add an on_command trigger to the modbus_controller which fires every time a command is sent on the modbus. In the lambda the `function_code` and `address` are available.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
modbus_controller:
  - id: modbus_con
    address: 0x01
    update_interval: 5min
    offline_skip_updates : 0
    on_command:
      - number.increment: modbus_writes
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-19 05:16 UTC, jesserockz requested changes

2024-07-19 05:16 UTC, jesserockz commented on esphome/components/modbus_controller/const.py
> +CONF_ON_COMMAND = "on_command"
Probably better to be more specific here and say `on_command_sent`
I feel like `on_command` implies an incoming command

```suggestion
CONF_ON_COMMAND_SENT = "on_command_sent"
```

2024-07-19 06:26 UTC, leejoow commented on esphome/components/modbus_controller/const.py
> +CONF_ON_COMMAND = "on_command"
I agree, I will make the changes

2024-07-22 00:43 UTC, jesserockz approved these changes

2024-07-22 01:33 UTC, merged