Allow unsetting of speaker and media player
OttoWinter/esphomeyaml pull request #7118
Opened 2024-07-22 16:30 UTC by HarvsG

# What does this implement/fix?

```yaml
  on_start: 
    - if:
        condition:
          lambda: return id(reply_location).state != "Another Media Player";
        then: 
          - lambda: id(va).set_speaker(echo_speaker);
        else
          - lambda: id(va).set_speaker(nullptr); # does not work
```
Currently a user can set a speaker dynamically, however they cannot unset the speaker because `local_output_` will always be true once `set_speaker()` is called.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-22 16:30 UTC, HarvsG commented
I have not tested this locally as I do not have & and do not know how to set up a dev environment

2024-07-23 11:06 UTC, nielsnl68 requested changes

2024-07-23 11:06 UTC, nielsnl68 commented on esphome/components/voice_assistant/voice_assistant.h
> +    }
```suggestion
    this->local_output_ = (this->speaker_ != nullptr)l
```
You can simplify your code into the above.

2024-07-23 11:06 UTC, nielsnl68 commented on esphome/components/voice_assistant/voice_assistant.h
>    }
```suggestion
    this->local_output_ = (this->media_player_ != nullptr);
```

2024-07-23 11:07 UTC, nielsnl68 commented
> I have not tested this locally as I do not have & and do not know how to set up a dev environment

Good suggestion. But why do you want to disconnect a speaker component?

2024-07-23 12:04 UTC, HarvsG commented
> Good suggestion. But why do you want to disconnect a speaker component?

At the moment, once a speaker is connected there is no way to disable it.
Two main reasons I can see.
1) To act as a pseudo mute button as I2S audio does not support volume control.
2) To disable the speaker when replies are sent to an external media player (this is my use case)
   - although I have a working work-around for this use case https://gist.github.com/HarvsG/40468d1d0e3f444d9a1907f26a503bc6#file-m5stack-atom-echo-mww2beta-reply-selector-full-config-yaml

2024-07-23 20:09 UTC, jesserockz commented
> I have not tested this locally as I do not have & and do not know how to set up a dev environment

You need to test this before it can be accepted. Not knowing how to set up a dev environment doesnt stop it from being tested. https://esphome.io/components/external_components

2024-07-24 14:34 UTC, nielsnl68 commented
> > Good suggestion. But why do you want to disconnect a speaker component?
> 
> At the moment, once a speaker is connected there is no way to disable it. Voice assistant will continue to play replies over it. Two main reasons I can see.
> 
> 1. To act as a pseudo mute button as I2S audio does not support volume control. (VA supports `media_player` but esp-idf doesn't and many devices are space limited)
> 2. To disable the speaker when replies are sent to an external media player (this is my use case)
>    
>    * although I have a working work-around for this use case https://gist.github.com/HarvsG/40468d1d0e3f444d9a1907f26a503bc6#file-m5stack-atom-echo-mww2beta-reply-selector-full-config-yaml

Sorry, i still not see the reason why you want to detach the speaker. Is using the speaker.stop action not enough?

2024-07-24 14:36 UTC, HarvsG commented
> Sorry, i still not see the reason why you want to detach the speaker. Is using the speaker.stop action not enough?

No 1) it doesn't seem to do anything. And 2) I want to prevent the speaker from playing. Not stop it half way through playing.

2024-07-24 14:41 UTC, nielsnl68 commented
Okay, got it. 
I belief it is better to add the mute option to the speaker component. 
The easy thing would be to disallow the play method to add new data to be send to the speaker.

2024-07-24 15:00 UTC, HarvsG commented
> Okay, got it. I belief it is better to add the mute option to the speaker component. The easy thing would be to disallow the play method to add new data to be send to the speaker.

That may well be true but is this code change not appropriate anyway. There is a function which can take a nullptr as an argument but behaves as if it can't?

2025-10-13 00:50 UTC, closed without merging