LVGL stage 2
OttoWinter/esphomeyaml pull request #7129
Opened 2024-07-24 20:18 UTC by clydebarrow

# What does this implement/fix?

Adds touchscreens, and `btn` (allows testing touch input.)

Refactor of typing.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-25 18:57 UTC, brotherdust commented
@clydebarrow , thank you for all your hard work on this! I'm trying this out on my LilyGo T4 S3 and am running into some compile errors with the config options. Specifically:
`
  [pages] is an invalid option for [lvgl]. Please check the indentation.
  pages: 
    - id: main_page
      widgets: 
        - label: 
            align: center
            text: Hello world!
`
If I remove pages, the widget by itself compiles and works fine on the device:
`
lvgl:
  displays:
    - disp_0
  touchscreens:
    - touch_0
  default_font: montserrat_24
  # pages:
  #   - id: main_page
  widgets:
  - label:
      align: center
      text: "Hello world!"
`

Okay I can live without pages. Let's try a slider?
`
  widgets: 
    - 
      [slider] is an invalid option for [widgets]. Please check the indentation.
      slider: 
        id: slider_test
        x: 20
        y: 50
        width: 30
        height: 220
`
I'm following the examples in the latest documentation. Maybe I'm doing it wrong? Either way, I understand this is not a complete implementation. Just wanted to bring this up in case anyone else runs into it.

Thanks!

2024-07-25 18:59 UTC, nagyrobi commented
@brotherdust please don't use this PR, as it only contains partial features. Use https://github.com/esphome/esphome/pull/6363 instead.

2024-07-25 19:00 UTC, brotherdust commented
> @brotherdust please don't use this PR, as it only contains partial features. Use #6363 instead.

Will do. Thanks!

2024-07-26 16:48 UTC, brotherdust commented
@clydebarrow / @nagyrobi

I have a use-case for the color wheel  widget. If you don't already have a plan to implement it, I would like to contribute the implementation to this integration. Would you be open to that, or should I just wait?

Thanks!

2024-07-26 19:56 UTC, nagyrobi commented
It was dropped in lvgl9. Maybe it would be better to manually implement a color selector with sliders.

2024-07-27 15:43 UTC, brotherdust commented
> It was dropped in lvgl9. Maybe it would be better to manually implement a color selector with sliders.

I noted that as I was perusing the LVGL docs yesterday.

I take it, then, that moving to v9 is on the roadmap?

2024-07-27 20:24 UTC, clydebarrow commented
> I take it, then, that moving to v9 is on the roadmap?

Yes, on hold for now pending merge and release of current version and maturity of LVGL9. There are issues with functionality and performance ATM.

2024-07-27 20:26 UTC, nagyrobi commented
We'd like to avoid breaking changes on long term.
It's not yet decided what's the best approach:
a) implement lvgl8 now but just with the limited set of features wich allow a possibly clean (aka with no breaking changes) migration for users in ESPHome
b) implement lvgl8 now as complete as possible and later implement lvgl9 (and any future version) as a separate component, allowing the users to be prepsred for a manual migration with breaking changes at their will

Both have advantages and disadvantages. At the moment we're on a).

2024-07-27 21:46 UTC, brotherdust commented
Fair. Even on v8, my Lilygo T3 S4, which has an ESP32-S3, 8MB of SRAM and a quad-SPI display, seems to struggle a bit. With that in mind, the newer ESP32-P4 looks promising.

Thanks again for implementing this. The docs are high quality!

2024-07-29 02:04 UTC, jesserockz requested changes

2024-07-29 02:04 UTC, jesserockz commented on esphome/components/lvgl/lvgl_esphome.h
> +#ifdef LV_USE_TOUCHSCREEN
```suggestion
#ifdef USE_LVGL_TOUCHSCREEN
```

2024-07-29 02:04 UTC, jesserockz commented on esphome/components/lvgl/lvgl_esphome.h
> +#ifdef LV_USE_TOUCHSCREEN
```suggestion
#ifdef USE_LVGL_TOUCHSCREEN
```

2024-07-29 02:04 UTC, jesserockz commented on esphome/components/lvgl/lvgl_esphome.h
> +#endif
```suggestion
#endif  // USE_LVGL_TOUCHSCREEN
```

2024-07-29 02:04 UTC, jesserockz commented on esphome/components/lvgl/touchscreens.py
> +        lprt = tconf[CONF_LONG_PRESS_REPEAT_TIME].total_milliseconds & 0xFFFF
If these have a max of uint16 max, then this should be in the validation.

2024-07-29 02:04 UTC, jesserockz commented on esphome/components/lvgl/__init__.py
> +        )
I feel like having multiple displays and multiple touchscreens is adding extra complexity to the code and extra configuration for a user.

If I was writing a YAML, and it automatically attaches to the display, then it should automatically attach to the touchscreen as well. Nobody is going to write a YAML file with a display, touchscreen and lvgl and not want to use the touchscreen.

Maybe we should remove multi-display/touch and can add it back later as an optional/advanced option. I don't see it being used in many real world situations anyway.

2024-07-29 02:42 UTC, nagyrobi commented on esphome/components/lvgl/__init__.py
> +        )
Physical display/touch + VNC display/touch for remote viewing/interact...

2024-07-29 02:43 UTC, nagyrobi commented on esphome/components/lvgl/__init__.py
> +        )
There can be setups without touch/rotary/keypad (just a status display).

2024-07-29 03:25 UTC, clydebarrow commented on esphome/components/lvgl/__init__.py
> +        )
Touchscreen now automatically used if a single one present, but not specifically configured in `lvgl:`. Multiples of both display and touchscreen still permitted.

2024-07-29 22:53 UTC, jesserockz requested changes
Looks good, just one minor thing that caught my eye =)

2024-07-29 22:53 UTC, jesserockz commented on esphome/components/lvgl/touchscreens.py
> +        lv_add(touchscreen.register_listener(listener))
Tested this locally and it is working with the normal cg instead of being placed inside the init lambda
```suggestion
        cg.add(touchscreen.register_listener(listener))
```

2024-07-29 23:19 UTC, jesserockz approved these changes

2024-07-29 23:23 UTC, clydebarrow commented on esphome/components/lvgl/touchscreens.py
> +        lv_add(touchscreen.register_listener(listener))
As you saw, I've done that, but it may have to be reverted in the future. There is a potential for touchscreen events to be sent to the listener before the the parent component has been completely setup. Right now I can't see that will cause any problems.

2024-07-29 23:41 UTC, merged