Add tca9555 GPIO driver
OttoWinter/esphomeyaml pull request #7146
Opened 2024-07-28 11:33 UTC by mobrembski

# What does this implement/fix?

This PR adds driver for Texas Instruments TCA9555 I2C GPIO Port Expander (simillar to PCF8574 and MCP2003).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

Please have a look at esphome-docs PR.

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-29 02:31 UTC, jesserockz requested changes

2024-07-29 02:31 UTC, jesserockz commented on esphome/components/tca9555/tca9555.cpp
> +  this->read_gpio_();
Something we would like to implement on all GPIO expanders is a "pin reading cache".
Basically it would work like this:
1. _Something_ reads a gpio pin from this expander `digital_read`
2. `digital_read` checks if this pin has been read already in this `loop` 
  a. If it has not, returns the cached value (from `input_mask_` etc)
  b. If is has been read before, then force a new read from the hardware before returning the newly cached value.

This would significantly speed up the GPIO expanders, because right now, every pin read triggers a hardware read, and `gpio` `binary_sensor`s read every configured pin, every loop.

If this is something you think you are able to add to this PR, we would be very grateful as we can then apply it to all of the expanders.

2024-07-29 02:31 UTC, jesserockz commented on esphome/components/tca9555/tca9555.cpp
> +  this->write_gpio_();
I know other expander components do this already, but we would like to remove it from them as it causes pins to flip on reboot.

One solution to avoid this is to read the output register from the hardware into the `output_mask` so that after setup, any pin changes will only affect the pin being changed and not the others.

2024-07-29 02:31 UTC, jesserockz commented on esphome/components/tca9555/__init__.py
> +    cv.int_range(min=0, max=17),
Values here are inclusive
```suggestion
    cv.int_range(min=0, max=15),
```

2024-07-29 02:31 UTC, jesserockz commented on esphome/components/tca9555/__init__.py
> +    cg.add(var.set_pin(num))
```suggestion
    cg.add(var.set_pin(config[CONF_NUMBER]))
```

2024-07-29 02:31 UTC, jesserockz commented on esphome/components/tca9555/tca9555.h
> +class TCA9555GPIOPin : public GPIOPin {
```suggestion
class TCA9555GPIOPin : public GPIOPin, public Parented<TCA9555Component> {
```

2024-07-29 02:31 UTC, jesserockz commented on esphome/components/tca9555/tca9555.h
> +  void set_parent(TCA9555Component *parent) { parent_ = parent; }
```suggestion
```

2024-07-29 02:31 UTC, jesserockz commented on esphome/components/tca9555/tca9555.h
> +  TCA9555Component *parent_;
```suggestion
```

2024-07-29 02:31 UTC, jesserockz commented on esphome/components/tca9555/tca9555.h
> +  void set_flags(gpio::Flags flags) { flags_ = flags; }
```suggestion
  void set_pin(uint8_t pin) { this->pin_ = pin; }
  void set_inverted(bool inverted) { this->inverted_ = inverted; }
  void set_flags(gpio::Flags flags) { this->flags_ = flags; }
```

2024-07-29 02:31 UTC, jesserockz commented on esphome/components/tca9555/tca9555.cpp
> +void TCA9555GPIOPin::setup() { pin_mode(flags_); }
```suggestion
void TCA9555GPIOPin::setup() { this->pin_mode(this->flags_); }
```

2024-07-29 02:31 UTC, jesserockz commented on esphome/components/tca9555/tca9555.cpp
> +  return buffer;
```suggestion
  return str_sprintf("%u via TCA9555", this->pin_);
```

2024-07-29 02:31 UTC, jesserockz commented on esphome/components/tca9555/__init__.py
> +    cg.add(var.set_parent(parent))
```suggestion
    await cg.register_parented(var, config[CONF_TCA9555])
```

2024-07-29 10:25 UTC, mobrembski commented on esphome/components/tca9555/tca9555.cpp
> +  this->read_gpio_();
I can implement it, give me some time this week, i'll try :)

2024-07-29 10:27 UTC, mobrembski commented on esphome/components/tca9555/tca9555.cpp
> +  this->write_gpio_();
+1, good idea. I didnt think about software reboots. Indeed, registers should preserve their contents since there is no reset on expander chip. Will do.

2024-07-30 14:45 UTC, mobrembski commented
@jesserockz Feel free to comment.

My idea is to add a "proxy" class  which will implement digitial_read and write, and based on flag (which resets every loop) it calls main component (here tca9555) to update its "cache" content.
I did it because as you said:

> ...we would be very grateful as we can then apply it to all of the expanders.

So i tried to make it more generic.

So far, cached_gpio class is added at tca9555. If you like the idea, i suggest to place it somewhere else since it's not tca9555 specific.

2024-08-28 04:03 UTC, jesserockz commented
I have made a few more changes to hopefully make it a bit clearer what is happening and moved the class to its own component folder for importing by other expanders.

Let me know if it causes issues with your tca9555. Ill try to test it with an expander I actually have at some point.

2024-08-28 12:17 UTC, mobrembski commented
> I have made a few more changes to hopefully make it a bit clearer what is happening and moved the class to its own component folder for importing by other expanders.
> 
> Let me know if it causes issues with your tca9555. Ill try to test it with an expander I actually have at some point.

There was a small bug - we've been missing setting output flags so tca9555 gets always same value. But already fixed ;)

2024-08-28 22:09 UTC, jesserockz commented
Oops, not sure how I dropped that out..haha
Thanks for fixing and confirming.

2024-09-13 04:21 UTC, jesserockz approved these changes

2024-09-19 04:17 UTC, merged