[lvgl] PR stage 3
OttoWinter/esphomeyaml pull request #7160
Opened 2024-07-29 23:48 UTC by clydebarrow

# What does this implement/fix?

Add rotary_encoder
Add automations (actions, conditions, triggers)

DO NOT USE THIS PR as an external component - it is not a complete implementation. See #6363 for a working implementation of LVGL.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3678

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [x] host

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
lvgl:
  touchscreens: my_touchscreen
  log_level: TRACE
  bg_color: light_blue
  default_font: space16
  widgets:
    - btn:
        widgets:
          - label:
              text: Button
        align: top_mid
        pressed:
          bg_color: 0x00FFFF
    - label:
        text: Hello world
        text_color: 0xFF8000
        align: center
        text_font: montserrat_40
        border_post: true
        pressed:
          text_color: 0x00FFFF
    - label:
        text: "Hello shiny day"
        text_color: 0xFFFFFF
        align: bottom_mid

font:
  - file: "gfonts://Roboto"
    id: space16
    size: 40
    bpp: 4

color:
  - id: light_blue
    hex: "3340FF"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-07-30 03:44 UTC, jesserockz requested changes

2024-07-30 03:44 UTC, jesserockz commented on esphome/components/lvgl/rotary_encoders.py
> +        lprt = enc_conf[CONF_LONG_PRESS_REPEAT_TIME].total_milliseconds & 0xFFFF
Not needed with the max validation
```suggestion
        lpt = enc_conf[CONF_LONG_PRESS_TIME].total_milliseconds
        lprt = enc_conf[CONF_LONG_PRESS_REPEAT_TIME].total_milliseconds
```

2024-07-30 03:44 UTC, jesserockz commented on esphome/components/lvgl/rotary_encoders.py
> +                lv_add(listener.set_sensor(sensor))
```suggestion
        if sensor_config := enc_conf.get(CONF_SENSOR):
            if isinstance(sensor_config, dict):
                b_sensor = await cg.get_variable(sensor_config[CONF_LEFT_BUTTON])
                cg.add(listener.set_left_button(b_sensor))
                b_sensor = await cg.get_variable(sensor_config[CONF_RIGHT_BUTTON])
                cg.add(listener.set_right_button(b_sensor))
            else:
                sensor = await cg.get_variable(sensor_config)
                cg.add(listener.set_sensor(sensor))
```

2024-07-30 03:44 UTC, jesserockz commented on esphome/components/lvgl/rotary_encoders.py
> +                        cv.Optional(CONF_RIGHT_BUTTON): cv.use_id(BinarySensor),
Should these be required?
If not, the `to_code` will also need to check if they have been set in config or it will fail on a `KeyError`
```suggestion
                        cv.Required(CONF_LEFT_BUTTON): cv.use_id(BinarySensor),
                        cv.Required(CONF_RIGHT_BUTTON): cv.use_id(BinarySensor),
```

2024-07-30 03:44 UTC, jesserockz commented on esphome/components/lvgl/rotary_encoders.py
> +        lv_add(listener.set_enter_button(b_sensor))
```suggestion
        cg.add(listener.set_enter_button(b_sensor))
```

2024-07-30 03:44 UTC, jesserockz commented on esphome/components/lvgl/trigger.py
> +    lv_add(lv_component.add_event_cb(w.obj, await context.get_lambda(), literal(event)))
I know python doesn't scope things like this, but accessing the context variable outside of the context/with feels wrong...

I noticed the same with the LVContext too :see_no_evil: 
```suggestion
    with LambdaContext([(lv_event_t_ptr, "event_data")]) as context:
        add_line_marks(tid)
        lv_add(trigger.trigger(value))
    	lv_add(lv_component.add_event_cb(w.obj, await context.get_lambda(), literal(event)))
```

2024-07-30 04:29 UTC, clydebarrow commented on esphome/components/lvgl/trigger.py
> +    lv_add(lv_component.add_event_cb(w.obj, await context.get_lambda(), literal(event)))
No, that's a perfectly valid usage. The value returned by the `with` is the value returned by the `__enter__` method, and allows access to data captured during the `with` block.

2024-07-30 04:40 UTC, clydebarrow commented on esphome/components/lvgl/rotary_encoders.py
> +                lv_add(listener.set_sensor(sensor))
As with the touchscreen, I don't like adding callbacks to something that has not yet been fully set up, but will go along with it for now.

2024-07-30 04:42 UTC, clydebarrow commented on esphome/components/lvgl/trigger.py
> +    lv_add(lv_component.add_event_cb(w.obj, await context.get_lambda(), literal(event)))
Calling `lv_add` inside the `with` adds it to the current context, the captured lambda needs to be added to the enclosing context, which is restored in `__exit__`.

2024-07-31 04:31 UTC, jesserockz approved these changes

2024-07-31 04:31 UTC, merged