Update MiCS Values
OttoWinter/esphomeyaml pull request #7173
Opened 2024-08-01 18:32 UTC by TrevorSchirmer

# What does this implement/fix?

Corrects values reported in the MiCS component to match datasheet.

## Types of changes

- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-01 19:04 UTC, erkr approved these changes
Looks good, to enable easy verification of the calculations, it could help to add two 'raw' sensors:
- One for the red_f value 
- One for the ox_f value

2024-08-02 00:30 UTC, manafount commented on esphome/components/mics_4514/mics_4514.cpp
> +      nitrogendioxide = 0.164 * pow(0x_f, 0.975);
Looks like a small typo here: `0x_f` should be `ox_f`

2024-08-02 10:17 UTC, erkr commented on esphome/components/mics_4514/mics_4514.cpp
> +    if (red_f > 3.4f) {
As CO has the largest range on the RED sensor, it triggers by all gasses supported.
CO false positives are very alarming, so I propose a small addition to this method to avoid false positives.

- for both low and high levels of CO the RED sensor detection is CO only, only the mid region of RED is not conclusive
- Assumption is that CO build up, so before measuring other gasses, low concentrations CO (outside the range of other gasses) will be measured first.
- so the approach I propose is to keep track if CO was measured a few cycles before entering the mid region. 
- Only report the CO measurement if RED is in a CO only range, or detected CO before entering the mid range (for some cycles to be robust)

The pseudo code (not tested/ compiled):
``` 
// extra code to keep track of CO was detected initially
static long exclusive_co=0;// counter
if (red_f > 3.4) {
  exclusive_co=0;
}
else if (red_f > 1 || red_f < 0.02) {
  exclusive_co++; // CO only range
}
// only the first line is changed in order to wait 2 cycles before reporting
if (red_f > 3.4f || exclusive_co < 3) {
 co = 0.0;
}
else if (red_f < 0.01) {
  co = 1000.0;
}
else {
  co = 4.2/ pow(red_f,1.2);
}
```

2024-08-27 00:22 UTC, TrevorSchirmer commented
Updated my AIR-1 and instantly had much better readings in the low PMs.

@manafount @erkr If you'd like to test here is the change in ESPHome addon to the yaml

`
packages:
  ApolloAutomation.AIR-1:
    url: https://github.com/ApolloAutomation/AIR-1
    ref: Mics_Test 
    files: [Integrations/ESPHome/AIR-1.yaml]
    refresh: 1min 
`

2024-08-29 18:47 UTC, jpiszcz commented
Hello, I have had an issue as reported here, Ammonia levels on one if my AIR-1's which should always be 0.00ppm has been spiking after sometime, I have written the following block below to the AIR-1 and I do see there is now a lot of logging in the ESPHome console, I will see if this issue I have been having presents itself again.


```
packages:
  ApolloAutomation.AIR-1:
    url: https://github.com/ApolloAutomation/AIR-1
    ref: Mics_Test 
    files: [Integrations/ESPHome/AIR-1.yaml]
    refresh: 1min
```

AIR-1 Dining Room: 0.00ppm
AIR-1 Garage: 11.76ppm (as shown in screenshot)

I moved the AIR-1 Dining Room into the Garage (above the other unit) and it remained 0.00ppm.
The uptime on the AIR-1 Garage was ~13d, I am guessing that this bug takes awhile to occur.
After updating the AIR-1 Garage unit I placed it back in the garage on 8/29, I will see if the levels of Ammonia spike again (there are no sources of Ammonia in the garage, (used for storage only and no natural gas here), and the other AIR-1 showed 0ppm for Ammonia).

![sensor-comparison](https://github.com/user-attachments/assets/b262dfea-a47f-466f-b52f-0f523bd84fd5)
![a2](https://github.com/user-attachments/assets/f6b663ba-f8a4-4651-9e91-fd2dfc764019)

Will see if the Ammonia levels spike again with this new version.

2024-08-29 19:11 UTC, jpiszcz commented
Update: I have updated two AIR-1s, one in the garage, another in the house, changes I have noticed:

1. Ammonia in garage before (10-20 ppm) -> now 1.06ppm (maybe fixed?)
2. Carbon Monoxide in the house (4.20ppm) -> is this right (it was always 0.00ppm before the update)
3. Ethanol in the house -> 1.52ppm is this right (it was always 0.00ppm before the update)
4. Nitrogen Dioxide in the house (0.16ppm) -> is this right?

![air1-compare](https://github.com/user-attachments/assets/1668390b-9860-42c2-9ebf-42b316d30372)

2024-08-29 20:46 UTC, jpiszcz commented
Around ~1-2hrs later after the HVAC ran for awhile it seems most of everything appears to be accurate **indoors** with the exception of Carbon Monoxide, none of my devices (3) are showing any carbon monoxide in the house.

![bb2](https://github.com/user-attachments/assets/7e3a7354-695f-4fdf-9152-7d3eeb5c5aa1)

2024-08-29 23:50 UTC, jesserockz requested changes

2024-08-29 23:50 UTC, jesserockz commented on esphome/components/mics_4514/mics_4514.cpp
> +      methane = 0.0;  // outside the range->unlikely
```suggestion
    if (red_f > 0.9f || red_f < 0.5) {  // outside the range->unlikely
      methane = 0.0;
```

2024-08-29 23:50 UTC, jesserockz commented on esphome/components/mics_4514/mics_4514.cpp
> +      ethanol = 0.0;  // outside the range->unlikely
```suggestion
    if (red_f > 1.0f || red_f < 0.02) {  // outside the range->unlikely
      ethanol = 0.0;
```

2024-08-29 23:50 UTC, jesserockz commented on esphome/components/mics_4514/mics_4514.cpp
> +      hydrogen = 0.0;  // outside the range->unlikely
```suggestion
    if (red_f > 0.9f || red_f < 0.02) {  // outside the range->unlikely
      hydrogen = 0.0;
```

2024-08-29 23:50 UTC, jesserockz commented on esphome/components/mics_4514/mics_4514.cpp
> +      ammonia = 0.0;  // outside the ammonia range->unlikely
```suggestion
    if (red_f > 0.98f || red_f < 0.2532) {  // outside the ammonia range->unlikely
      ammonia = 0.0;
```

2024-08-30 00:34 UTC, jesserockz approved these changes

2024-08-30 00:36 UTC, merged

2024-08-30 04:19 UTC, ha-elguano commented
I wanted to chime in and say that implementing the test branch of the MICS fix above, I'm also now getting accurate readings at low concentrations. Sensors that have ALWAYS read zero now display reasonable values and ranges. 

![mics](https://github.com/user-attachments/assets/7849bb83-04c5-484d-b89f-4a75ef3ccd91)

2024-08-30 10:33 UTC, jpiszcz commented
Agree with ha-elguano’s comment above.  Once this version is merged into the ESPHome, will the debugging window remain enabled?