adjust to new python pre-commit hooks
OttoWinter/esphomeyaml pull request #7178
Opened 2024-08-02 16:34 UTC by tomaszduda23

# What does this implement/fix?

Part https://github.com/esphome/esphome/pull/7049. It applies formatting by new pre-commit hooks and lint which can be merge without the rest. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-05 23:39 UTC, jesserockz commented on esphome/components/climate/climate_traits.h
> +    if (supported) {  // NOLINT(bugprone-branch-clone)
Im confused as to why these are causing this rule to fire. they are clearly different bodies

2024-08-05 23:40 UTC, jesserockz requested changes
Could you split this PR up even further so there is 1 for components, 1 for sscripts, and 1 for core changes?

2024-08-07 16:19 UTC, tomaszduda23 commented on esphome/components/climate/climate_traits.h
> +    if (supported) {  // NOLINT(bugprone-branch-clone)
for some reason it does not pick that error now

2024-08-12 04:52 UTC, jesserockz approved these changes

2024-08-12 04:52 UTC, merged