Add Initial NPI-19 pressure sensor support
OttoWinter/esphomeyaml pull request #7181
Opened 2024-08-03 00:05 UTC by bakerkj

# What does this implement/fix?

Adds support for the NPI-19 i2c pressure sensor.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable): none

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-02 03:48 UTC, jesserockz requested changes
One minor log, otherwise looks good

2024-10-02 03:48 UTC, jesserockz commented on esphome/components/npi19/npi19.cpp
> +  ESP_LOGD(TAG, "Got pressure=%draw temperature=%.1f°C", raw_pressure, temperature);
```suggestion
  ESP_LOGD(TAG, "Got raw pressure=%d, temperature=%.1f°C", raw_pressure, temperature);
```

2024-10-02 23:42 UTC, bakerkj commented
> One minor log, otherwise looks good

Thank you for the review. Change accepted.

2024-10-03 00:10 UTC, jesserockz approved these changes

2024-10-07 02:59 UTC, merged