Adds MQTT component to Alarm Control panel component
OttoWinter/esphomeyaml pull request #7188
Opened 2024-08-04 21:08 UTC by heythisisnate

# What does this implement/fix?

Makes the Alarm Panel Component implement MQTT using the MQTT component.
After this change, when MQTT is enabled, the Alarm Control Panel component will publish its state to a MQTT state topic and receive commands by subscribing to a MQTT command topic, following the conventions in the MQTT component.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
mqtt:
  broker: $mqtt_addr

alarm_control_panel:
  - platform: template
    name: Alarm Panel
    binary_sensors:
      - input: zone1
      - input: zone2

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-04 23:56 UTC, jesserockz requested changes
ESPHome's default MQTT implementation should always work with Home Assistant if the platform is implemented there.

https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/alarm_control_panel.py

2024-08-04 23:56 UTC, jesserockz commented on esphome/components/mqtt/mqtt_alarm_control_panel.cpp
> +  if (!this->publish(this->get_state_topic_(), state_s))
Have you tested this with Home Assistant?
If I am reading it correctly, HA expects the state payload to be lower case.

2024-08-04 23:56 UTC, jesserockz commented on esphome/components/mqtt/mqtt_alarm_control_panel.cpp
> +void MQTTAlarmControlPanelComponent::send_discovery(JsonObject root, mqtt::SendDiscoveryConfig &config) {}
This should be populated with supported features and code settings etc.

2024-08-05 00:35 UTC, heythisisnate commented
@jesserockz thanks for the quick review.
Good point. I wasn't thinking of HA as a client and wasn't using it for testing. I will adjust to make sure it works.

2024-08-05 19:57 UTC, heythisisnate commented
@jesserockz Working perfectly with HA now with lowercase state payloads.

The only thing I'm unsure about is if the `supported_features` data format is correct. It looks like this is stored as an integer which has a mapping to some values but HA is expecting a list of strings. Can you give me a hint or example how to decode this into the strings that HA wants to see?

2024-08-05 20:23 UTC, heythisisnate commented
Nevermind, I figured it out. This should be good now. Working great with HA and MQTT discovery.

2024-08-05 23:26 UTC, jesserockz requested changes
Thanks for making those changes. 
I don't have my HA set up with mqtt so I cannot test it easily. 

Please also add acp to the `tests/components/mqtt` files so it gets compiled in CI.

2024-08-05 23:26 UTC, jesserockz commented on esphome/components/mqtt/mqtt_alarm_control_panel.cpp
> +  if (!this->publish(this->get_state_topic_(), state_s))
I dont think we should be using the log argument for sending the string state. Its there for logging, hence the name :sweat_smile: 

https://github.com/esphome/esphome/blob/f737ca6e286f36e243b5bae1bcb7515b9a4bf857/esphome/components/mqtt/mqtt_climate.cpp#L255-L284

While this would basically be repeating the same code as the log helper, I think for consistency it is better to implement similarly to the climate.

If we do a bigger refactor on them, they will be done together.

2024-08-06 03:53 UTC, jesserockz approved these changes

2024-08-06 03:53 UTC, merged