[lvgl] Stage 5
OttoWinter/esphomeyaml pull request #7191
Opened 2024-08-05 08:35 UTC by clydebarrow

# What does this implement/fix?

Penultimate stage of LVGL PR series. All supported widgets implemented.

And read the docs as below:

Doc preview is here: https://deploy-preview-3678--esphome.netlify.app/components/lvgl.html

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3678

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] RP2040
- [x] host

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-05 23:14 UTC, jesserockz requested changes
I think it might be best to also rename the `animimg` to `animated_image` to be consistent too.

2024-08-05 23:14 UTC, jesserockz commented on esphome/components/lvgl/btnmatrix.py
> +CONF_BUTTONMATRIX = "buttonmatrix"
I feel like since this is two words, it should be separated as such in config
```suggestion
CONF_BUTTON_MATRIX = "button_matrix"
```

2024-08-05 23:14 UTC, jesserockz commented on esphome/components/lvgl/btnmatrix.py
> +            CONF_BUTTONMATRIX,
```suggestion
            CONF_BUTTON_MATRIX,
```

2024-08-05 23:14 UTC, jesserockz commented on esphome/components/lvgl/btnmatrix.py
> +BTNM_BTN_SCHEMA = cv.Schema(
It would also be more preferred to not shorten everything down. It is better to be clear about what this is exactly.

> It’s preferred to use long variable/function names over short and non-descriptive ones.
https://esphome.io/guides/contributing#codebase-standards
```suggestion
BUTTON_MATRIX_BUTTON_SCHEMA = cv.Schema(
```

2024-08-05 23:14 UTC, jesserockz commented on esphome/components/lvgl/btnmatrix.py
> +async def get_button_data(config, btnm: Widget):
```suggestion
async def get_button_data(config, button_matrix: Widget):
```

2024-08-05 23:14 UTC, jesserockz commented on esphome/components/lvgl/btnmatrix.py
> +            bid = btnconf[CONF_ID]
```suggestion
            button_id = btnconf[CONF_ID]
```

2024-08-05 23:14 UTC, jesserockz commented on esphome/components/lvgl/btnmatrix.py
> +    "lvgl.matrixbutton.update",
```suggestion
    "lvgl.matrix_button.update",
```

2024-08-05 23:14 UTC, jesserockz commented on esphome/components/lvgl/btnmatrix.py
> +        cv.GenerateID(CONF_BUTTONMATRIX_TEXT_LIST_ID): cv.declare_id(char_ptr),
Since this is inside a button matrix schema, do we really need the "buttonmatrix" prefix here?
```suggestion
        cv.GenerateID(CONF_TEXT_LIST_ID): cv.declare_id(char_ptr),
```

2024-08-05 23:14 UTC, jesserockz commented on esphome/components/lvgl/msgbox.py
> +CONF_MSGBOX = "msgbox"
```suggestion
CONF_MESSAGE_BOX = "message_box"
```

2024-08-05 23:14 UTC, jesserockz commented on esphome/components/lvgl/spinbox.py
> +def validate_spinbox(config):
Is this called from anywhere? Cannot find any references

2024-08-05 23:14 UTC, jesserockz commented on esphome/components/lvgl/tabview.py
> +            },
For consistency across the files, I think all of these widget types should define the schema before the class

2024-08-05 23:14 UTC, jesserockz commented on esphome/components/lvgl/tileview.py
> +            },
Same here

2024-08-05 23:26 UTC, clydebarrow commented on esphome/components/lvgl/btnmatrix.py
> +CONF_BUTTONMATRIX = "buttonmatrix"
The LVGL name for that widget is "buttonmatrix" (was btnmatrix in 8.4, 9.x renamed it to buttonmatrix). I think it's best to keep consistency with the underlying implementation to avoid confusion.

2024-08-05 23:37 UTC, clydebarrow commented on esphome/components/lvgl/btnmatrix.py
> +    "lvgl.matrixbutton.update",
I'll make this `lvgl.matrix.button.update` since it doesn't have a direct link with LVGL, and the `matrix` part is to distinguish it from `lvgl.button.update` which operates on regular buttons.

2024-08-05 23:39 UTC, clydebarrow commented on esphome/components/lvgl/btnmatrix.py
> +        cv.GenerateID(CONF_BUTTONMATRIX_TEXT_LIST_ID): cv.declare_id(char_ptr),
It is a little redundant - I'll go with `CONF_BUTTON_TEXT_LIST_ID` to keep it clear what it applies to.

2024-08-05 23:40 UTC, clydebarrow commented on esphome/components/lvgl/msgbox.py
> +CONF_MSGBOX = "msgbox"
`msgbox` is the LVGL name (not renamed in 9.x) so I think it best to retain consistency.

2024-08-06 01:17 UTC, jesserockz approved these changes

2024-08-06 01:17 UTC, merged