[http_request] Add custom UpdateInfo checks
OttoWinter/esphomeyaml pull request #7193
Opened 2024-08-05 13:00 UTC by dentra

# What does this implement/fix?

This PR adds the ability to do additional custom UpdateInfo checks to decide whether an update is available.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
http_request:
ota:
  - platform: http_request
update:
  - platform: http_request
    name: Firmware
    source: $FW_MANIFEST_JSON
    check_update: |-
      return !str_endswith(x.latest_version, "-beta");
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-15 23:25 UTC, jesserockz requested changes

2024-09-15 23:25 UTC, jesserockz commented on esphome/components/http_request/update/http_request_update.h
> +  std::function<bool(const update::UpdateInfo &)> check_update_{[](const update::UpdateInfo &) { return true; }};
```suggestion
  std::function<bool(const update::UpdateInfo &)> check_update_{};
```

2024-09-15 23:25 UTC, jesserockz commented on esphome/components/http_request/update/http_request_update.cpp
> +      !this->check_update_(this->update_info_)) {
```suggestion
      (this->check_update_ != nullptr && !this->check_update_(this->update_info_))) {
```

2024-09-15 23:25 UTC, jesserockz commented on esphome/components/http_request/update/http_request_update.cpp
> +    this->update_info_.md5 = "";
Resetting all of this will break the `force` update functionality.

2024-09-17 18:17 UTC, dentra commented on esphome/components/http_request/update/http_request_update.cpp
> +    this->update_info_.md5 = "";
if I change the return value to enum (AVAILABLE, LIMITED, DENIED) and process it accordingly, will that be enough?

2024-09-17 23:40 UTC, jesserockz commented on esphome/components/http_request/update/http_request_update.cpp
> +    this->update_info_.md5 = "";
What is limited and denied?

2024-09-18 08:10 UTC, dentra commented on esphome/components/http_request/update/http_request_update.cpp
> +    this->update_info_.md5 = "";
Available - check was success and allow any update
Limited - check was failed but allow to do force update
Denied - check was failed and completely disallow any update

your names are welcome :)

2024-09-18 08:28 UTC, dentra commented on esphome/components/http_request/update/http_request_update.cpp
> +    this->update_info_.md5 = "";
For example we have a new firmware that use new partition mapping or something other critical and do not want to flash it via ota, it update will just broke device for user. So even a forced update in this case should be prohibited.

Another case is the classic beta version, in this case, a forced update is what is needed.

2024-09-24 17:06 UTC, dentra commented on esphome/components/http_request/update/http_request_update.cpp
> +    this->update_info_.md5 = "";
Some additional enum suggestion: accept_any, only_forced, reject_all

2025-10-13 00:50 UTC, closed without merging