hx711: Configure GPIO pins and detect absent devices
OttoWinter/esphomeyaml pull request #7214
Opened 2024-08-06 21:16 UTC by dwmw2

The protocol for the HX711 is very simple, but it *is* possible to detect that the device is absent and not just report zeroes as it does at the momemt:

 ﻿[D][hx711:033]: 'HX711 value': Got value 0

Firstly, configure the GPIO pins and default to pulling the DOUT pin up; if there's nothing connected, that should trigger the existing check before taking a reading:

 [W][hx711:039]: HX711 is not ready for new measurements yet!

Secondly, check that DOUT goes high as it should after the additional gain bits are clocked:

 [W][hx711:067]: HX711 DOUT pin not high after reading!

The board which actually *does* have an HX711 attached also still works.

 [D][hx711:033]: 'HX711 value': Got value -1064032
 [D][sensor:094]: 'HX711 value': Sending state 65.73016 kg with 0 decimals of accuracy

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-07 07:10 UTC, jesserockz requested changes

2024-08-07 07:10 UTC, jesserockz commented on esphome/components/hx711/hx711.cpp
> +  this->dout_pin_->pin_mode(gpio::FLAG_INPUT | gpio::FLAG_PULLUP);
The pin modes are already set to these by default in the config/code generation (take a look at the generated main.cpp) 
Pull-up is not, but that depends on user config.

2024-08-07 09:01 UTC, dwmw2 commented on esphome/components/hx711/hx711.cpp
> +  this->dout_pin_->pin_mode(gpio::FLAG_INPUT | gpio::FLAG_PULLUP);
I double-checked the SparkFun HX711 board schematic, and it *doesn't* have an external pullup. That implies that it's internal to the HX711 chip. So configuring it for pullup probably isn't necessary if there's a chip present.

Now that I've found the trick of checking for DOUT to go high after a reading, that should suffice to catch the cases where there *isn't* a chip present. I'll just drop that part.

Thanks.

2024-08-07 09:26 UTC, dwmw2 commented on esphome/components/hx711/hx711.cpp
> +  this->dout_pin_->pin_mode(gpio::FLAG_INPUT | gpio::FLAG_PULLUP);
Thanks. I double-checked the [schematic](https://cdn.sparkfun.com/assets/f/5/5/b/c/SparkFun_HX711_Load_Cell.pdf) of the SparkFun HX711 board, and it doesn't have an external pullup on the DOUT line. So it must be internal to the chip, and the pullup on the GPIO shouldn't really be necessary when there's a chip attached.

Now that I've found the trick of waiting for DOUT to go high after the reading, we can live without it because we can detect absent chips that way.

I'll drop the GPIO config part and retest.

2024-08-08 02:06 UTC, jesserockz approved these changes

2024-08-08 02:29 UTC, merged