Implement all supported thermocouple types for MAX31856
OttoWinter/esphomeyaml pull request #7218
Opened 2024-08-07 14:22 UTC by ArkanStasarik

# What does this implement/fix?

MAX31856 supports 8 different thermocouple types however this was not implement. This implements all thermocouple types supported by the sensor

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ x ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

## Checklist:
  - [ X ] The code change is tested and works locally.
  - [ X ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-10 03:54 UTC, jesserockz requested changes

2024-09-10 03:54 UTC, jesserockz commented on esphome/components/max31856/max31856.h
> +    thermocouple_type_ = thermocouple_type;
```suggestion
  void set_filter(MAX31856ConfigFilter filter) { this->filter_ = filter; }
  void set_thermocouple_type(MAX31856ConfigThermocoupleType thermocouple_type) {
    this->thermocouple_type_ = thermocouple_type;
```

2024-09-10 03:54 UTC, jesserockz commented on esphome/components/max31856/max31856.h
> +};
You might as well reuse the `MAX31856ThermocoupleType` enum instead of making another one?

2024-09-10 04:06 UTC, clydebarrow commented on esphome/components/max31856/max31856.cpp
> +    ESP_LOGCONFIG(TAG, "  Thermocouple Type: Unknown");
```suggestion
  ESP_LOGCONFIG(TAG, "  Thermocouple Type: "%c", "BEJKNRST"[this->thermocouple_type_]);
```
You could check for it being in range, but that's guaranteed by the config anyway.

2024-09-10 15:20 UTC, ArkanStasarik commented on esphome/components/max31856/max31856.h
> +};
You are right! Fixed now

2024-09-11 04:43 UTC, jesserockz approved these changes

2024-09-11 04:53 UTC, merged