Support Setting Dashboard Port from Environment Variable
OttoWinter/esphomeyaml pull request #7226
Opened 2024-08-07 19:36 UTC by zhudhjen

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-07 19:38 UTC, zhudhjen commented
(previous [PR](https://github.com/esphome/esphome/pull/7224) closed due to messed up commit history)

The implementation has finished. Tests have been performed locally regarding dashboard port configuration: 
![Screenshot 2024-08-07 104609](https://github.com/user-attachments/assets/5a593394-2eda-4a38-999b-cc32df8aa39f)

Changes are only made to the dashboard, so no on-board testing was done. The dashboard was able to discover and adopt my devices properly.

Doc has not been updated yet. I did not find any current environment variables being documented in the doc. I can add it to [here](https://esphome.io/guides/cli.html#cmdoption-esphome-dashboard-port), but is there a convention to omit such configurations? As `USERNAME` and `PASSWORD` are not documented either.

2024-08-15 01:32 UTC, jesserockz requested changes

2024-08-15 01:32 UTC, jesserockz commented on esphome/__main__.py
> +        default=0,
Untested, but i'm sure that this is really all that is needed for this to work
```suggestion
        default=os.getenv("ESPHOME_DASHBOARD_PORT", 6052),
```

2024-08-15 18:35 UTC, zhudhjen commented on esphome/__main__.py
> +        default=0,
Updated according to your suggestion. Tested and it works: 
![image](https://github.com/user-attachments/assets/ba5c3249-8a85-43a4-81df-65bae60cc471)

2024-08-15 21:13 UTC, jesserockz commented on tests/dashboard/test_web_server.py
>      DASHBOARD.settings.parse_args(args)
I actually think the port here is not doing anything as the `sock` is being used directly to "host" the webserver and the `port` number is directly being used by the `DashboardTestHelper` lower down.

2024-08-16 00:36 UTC, zhudhjen commented on tests/dashboard/test_web_server.py
>      DASHBOARD.settings.parse_args(args)
Tested by removing the `os.environ` line and it still passed, so this is true. Then how should I test this port? Or do I have to test it? As it looks like other environment vars are not being tested either, e.g. `USERNAME`/`PASSWORD`.

2024-08-16 01:40 UTC, jesserockz commented on tests/dashboard/test_web_server.py
>      DASHBOARD.settings.parse_args(args)
You cant really test it in these unit tests due to the way the port assigning works.

Basically you would need to write a new test that tests `__main__.parse_args` to ensure that the env var is in the `port` argument

2024-08-16 18:05 UTC, zhudhjen commented on tests/dashboard/test_web_server.py
>      DASHBOARD.settings.parse_args(args)
I cannot write a test to cover all the parse arg behaviors now -- there are too many arguments to cover and I'm not familiar with most of them. I can add `test_parse_args.py` in `tests/unit_tests` to cover the test of the `port` argument. Potentially other args can be added to this test later. Do you think it is acceptable?

2024-08-16 19:40 UTC, jesserockz commented on tests/dashboard/test_web_server.py
>      DASHBOARD.settings.parse_args(args)
Yes. You are only changing port, so testing only port is fine

2025-10-13 00:50 UTC, closed without merging