Correct offset calibration
OttoWinter/esphomeyaml pull request #7228
Opened 2024-08-08 04:09 UTC by descipher

# What does this implement/fix?

Offset calibration should be run when all inputs are 0 values, the current code runs at startup. This requirement was overlooked. The fix changes the calibration feature to an optional capability with button controls for run and clear calibration operations. A bool var in the sensor component sets an enable flag which enables loading/saves offset calibration values at startup from flash using the preferences core component. The pref is hashed using the device name and will persist as long as the same device name is used for updates. 
The fix now allows a user to use the calibration feature when the 0 value input requirement is active capturing the offset values into nvram which is subsequently loaded during startup if the enable_offset_calibration var is true.   

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

https://github.com/CircuitSetup/Expandable-6-Channel-ESP32-Energy-Meter/discussions/179

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

external_components:
  - source: github://PR#1234
    components: [ atm90e32 ]
    refresh: 0s

substitutions:
  disp_name: PM1
  update_time: 15s
  phase_a_current_cal: '15270'
  phase_c_current_cal: '15270'
  phase_a_voltage_cal: '4470'
  phase_c_voltage_cal: '4470'

sensor:
  - platform: atm90e32
    cs_pin: 5
    atm90e32_id: chip1
    phase_a:
      voltage:
        name: ${disp_name} L1 Volts
        accuracy_decimals: 2
      current:
        name: PM CT1 Amps
        id: "ct1Amps"
      power:
        name: PM CT1 Watts
        accuracy_decimals: 1
        id: "ct1Watts"
      gain_voltage: ${phase_a_voltage_cal}
      gain_ct: ${phase_a_current_cal}
    phase_c:
      voltage:
        name: PM  L2 Volts
        accuracy_decimals: 2
      current:
        name: ${disp_name} CT2 Amps
        id: "ct2Amps"
      power:
        name: PM CT2 Watts
        accuracy_decimals: 1
        id: "ct2Watts"
      gain_voltage: ${phase_c_voltage_cal}
      gain_ct: ${phase_c_current_cal}
    frequency:
      name: ${disp_name} Freq
    line_frequency: 60Hz
    gain_pga: 2x
    update_interval: ${update_time}
    enable_offset_calibration: True
	
  - platform: atm90e32
    cs_pin: 4
    atm90e32_id: chip2
    phase_a:
      voltage:
        name: ${disp_name} L3 Volts
        accuracy_decimals: 2
      current:
        name: ${disp_name} CT3 Amps
        id: "ct3Amps"
      power:
        name: ${disp_name} CT3 Watts
        accuracy_decimals: 1
        id: "ct3Watts"
      gain_voltage: ${phase_a_voltage_cal}
      gain_ct: ${phase_a_current_cal}
    phase_c:
      voltage:
        name: ${disp_name} L4 Volts
        accuracy_decimals: 2
      current:
        name: ${disp_name} CT4 Amps
        id: "ct4Amps"
      power:
        name: ${disp_name} CT4 Watts
        accuracy_decimals: 1
        id: "ct4Watts"
      gain_voltage: ${phase_c_voltage_cal}
      gain_ct: ${phase_c_current_cal}
    line_frequency: 60Hz
    current_phases: 2
    gain_pga: 2X
    update_interval: 60s

button:
  - platform: atm90e32
    atm90e32_id: chip1
    run_offset_calibration:
      name: "Chip1 - Run Offset Calibration"
    clear_offset_calibration:
      name: "Chip1 - Clear Offset Calibration"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).
  - Docs will be added when ready

2024-08-13 08:13 UTC, jesserockz approved these changes

2024-08-13 08:14 UTC, jesserockz requested changes
Please add the button and new config option to the test files.
And also don't forget to add a docs PR for the new features.
I will be cutting the beta release tomorrow my time and it would be great if these were done so this can make it into the release.

2024-08-14 02:03 UTC, descipher commented
@jesserockz Thanks, I will be following up with the test yaml and adding docs as well.

2024-08-14 03:34 UTC, jesserockz approved these changes

2024-08-14 04:43 UTC, merged