Fix https://github.com/esphome/issues/issues/658
OttoWinter/esphomeyaml pull request #724
Opened 2019-09-08 19:45 UTC by fake-name

See https://github.com/esphome/issues/issues/658

2019-09-10 12:35 UTC, glmnet commented
Should should have filled in the PR template, you briefly explain there the PR information and you can link to other issues.

2019-09-10 12:37 UTC, glmnet requested changes
Please fix for travis build

2019-09-10 12:37 UTC, glmnet commented on esphome/components/web_server/web_server.cpp
> +  #include <esphome/components/logger/logger.h>
lint is failing here because the `#include` should not be indented inside the `#idfef`

2019-09-11 02:15 UTC, fake-name commented on esphome/components/web_server/web_server.cpp
> +  #include <esphome/components/logger/logger.h>
Ugh, that code style is so gross.

2019-09-11 02:36 UTC, glmnet approved these changes

2019-09-11 02:37 UTC, merged