HLW8032 Single-phase metering IC
OttoWinter/esphomeyaml pull request #7241
Opened 2024-08-10 22:11 UTC by rici4kubicek

# What does this implement/fix?

Implementation of Single-phase metering IC

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: hlw8032
    voltage_divider: 1.72
    voltage:
      name: HLW8032 Voltage
      id: hlw8032_voltage
    current:
      name: HLW8032 Current
      id: hlw8032_current
    power:
      name: HLW8032 Power
      id: hlw8032_power
    apparent_power:
      name: HLW8032 Apparent Power
      id: hlw8032_apparent_power
    power_factor:
      name: HLW8032 Power Factor
      id: hlw8032_power_factor

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-11 10:05 UTC, lboue commented
@rici4kubicek 
Which device did you test with? Is it the [M5Stack AC Measure Unit (HLW8032)](https://shop.m5stack.com/products/ac-measure-unit-hlw8032)?

2024-08-11 10:08 UTC, rici4kubicek commented
> @rici4kubicek Which device did you test with? Is it the [M5Stack AC Measure Unit (HLW8032)](https://shop.m5stack.com/products/ac-measure-unit-hlw8032)?

I have tested it with my own hardware. There I have similiar connection of HLW8032 which is used on the M5Stack

2024-08-15 11:28 UTC, tarontop commented
It seems that the communication protocol of HLW8032 and CSE7766 is the same. The metering IC of Athom's plug is HLW8032, and it is using the components of CSE7766.

https://github.com/athom-tech/esp32-configs/blob/e90516b3d18118f8c069f6538bff85e736691c35/athom-smart-plug.yaml#L157

2024-08-15 20:50 UTC, rici4kubicek commented
> It seems that the communication protocol of HLW8032 and CSE7766 is the same. The metering IC of Athom's plug is HLW8032, and it is using the components of CSE7766.
> 
> https://github.com/athom-tech/esp32-configs/blob/e90516b3d18118f8c069f6538bff85e736691c35/athom-smart-plug.yaml#L157

Yes. The protocol is very similiar. There are little bit diferrencies in the mechanism of calculation measured values from the read values. HLW8032 have `calibration` values used in the numerator. But CSE7766 have `calibration` values used in the denumerator.
On the real hardware it is necessary to apply some multiplier which depends on the hardware. 
Hovewer, current implementation of the CSE7766 component expect using 1MOhm resistor used in the voltage sens branch and the 1mOhm resistor as the current sense shunt resistor. 
In the case You want to use the CSE7766 implementation with the HLW8032, you should use post processed `calibration` values. On the other side, implemntation of the HLW8032 in this PR support settings of the hardware dependence resistor values. Which make the driver more general.

2025-08-10 23:38 UTC, jesserockz requested changes

2025-08-10 23:38 UTC, jesserockz commented on tests/components/hlw8032/test.esp32-ard.yaml
Please deduplicate these by moving the bulk to a `common.yaml` file and including that into the individual test files.

2025-08-10 23:38 UTC, jesserockz commented on esphome/components/hlw8032/hlw8032.h
> +  sensor::Sensor *power_factor_sensor_{nullptr};
Better for memory padding
```suggestion
  sensor::Sensor *voltage_sensor_{nullptr};
  sensor::Sensor *current_sensor_{nullptr};
  sensor::Sensor *power_sensor_{nullptr};
  sensor::Sensor *apparent_power_sensor_{nullptr};
  sensor::Sensor *power_factor_sensor_{nullptr};
  
  float current_resistor_{0.001f};
  float voltage_divider_{1.720f};
  
  uint32_t last_transmission_{0};
  
  uint8_t raw_data_[24]{};
  
  uint8_t check_{0};
  uint8_t raw_data_index_{0};
  
  bool header_found_{false};
```

2025-08-10 23:38 UTC, jesserockz commented on esphome/components/hlw8032/hlw8032.h
> +  void set_current_resistor(float current_resistor) { current_resistor_ = current_resistor; }
> All uses of class members and member functions should be prefixed with this-> to distinguish them from global functions/variables.

https://developers.esphome.io/contributing/code/#c-code-style

```suggestion
  void set_current_resistor(float current_resistor) { this->current_resistor_ = current_resistor; }
```

2025-08-10 23:38 UTC, jesserockz commented on esphome/components/hlw8032/hlw8032.cpp
> +  ESP_LOGCONFIG(TAG, "  Voltage Divider: %.3f", this->voltage_divider_);
```suggestion
  ESP_LOGCONFIG(TAG, "HLW8032:\n"
                     "  Current resistor: %.1f mΩ\n"
                     "  Voltage Divider: %.3f",
                     this->current_resistor_ * 1000.0f, this->voltage_divider_);
```

2025-08-10 23:38 UTC, jesserockz commented on esphome/components/hlw8032/hlw8032.cpp
> +  uint32_t voltage_parameter = this->get_24_bit_uint_(2);
```suggestion
  uint32_t voltage_parameter = encode_uint24(this->raw_data_[2], this->raw_data_[3], this->raw_data_[4]);
```

2025-08-10 23:38 UTC, jesserockz commented on esphome/components/hlw8032/hlw8032.cpp
> +#endif
We have an entire uart debug config for this. And stringstream is a massive lib to pull in
```suggestion
```

2025-08-10 23:38 UTC, jesserockz commented on esphome/components/hlw8032/hlw8032.cpp
> +#endif
```suggestion
#if ESPHOME_LOG_LEVEL >= ESPHOME_LOG_LEVEL_VERY_VERBOSE
  ESP_LOGVV(TAG, "HLW8032 Parsed data:");
  ESP_LOGVV(TAG, "  Voltage Parameter REG: 0x%06X, Voltage REG: 0x%06X", (unsigned int) voltage_parameter,
           (unsigned int) voltage_reg);
  ESP_LOGVV(TAG, "  Current Parameter REG: 0x%06X, Current REG: 0x%06X", (unsigned int) current_parameter,
           (unsigned int) current_reg);
  ESP_LOGVV(TAG, "  Power Parameter REG: 0x%06X, Power REG: 0x%06X", (unsigned int) power_parameter,
           (unsigned int) power_reg);
  ESP_LOGVV(TAG, "  Data Update REG: 0x%02X", data_update_register);
#endif
```

2025-08-10 23:38 UTC, jesserockz commented on esphome/components/hlw8032/hlw8032.cpp
> +#endif
```suggestion
```

2025-08-10 23:38 UTC, jesserockz commented on esphome/components/hlw8032/hlw8032.cpp
> +#include <sstream>
```suggestion
```

2025-08-15 01:18 UTC, jesserockz submitted a review, later dismissed

2025-08-15 01:18 UTC, jesserockz commented on esphome/components/hlw8032/hlw8032.cpp
> +  ESP_LOGVV(TAG, "  Voltage Parameter REG: 0x%06X, Voltage REG: 0x%06X", (unsigned int) voltage_parameter,
We don't need to log the component name as the TAG includes that already. Please check all log lines.
https://developers.esphome.io/architecture/logging/#minimizing-impact

Also, when printing 32-bit values, you need to use these macros. Please apply to the rest as well.
```suggestion
  ESP_LOGVV(TAG, "Parsed data:");
  ESP_LOGVV(TAG, "  Voltage Parameter REG: 0x%06" PRIX32 ", Voltage REG: 0x%06" PRIX32, voltage_parameter, voltage_reg);
```

2025-08-15 06:39 UTC, rici4kubicek commented on esphome/components/hlw8032/hlw8032.cpp
> +  ESP_LOGVV(TAG, "  Voltage Parameter REG: 0x%06X, Voltage REG: 0x%06X", (unsigned int) voltage_parameter,
I have fixed this. Thanks.

2025-11-04 02:18 UTC, swoboda1337 requested changes

2025-11-04 02:18 UTC, swoboda1337 commented on tests/components/hlw8032/common.yaml
Tests need to be updated to use the new common bus stuff.

2025-11-07 04:10 UTC, swoboda1337 requested changes
As requested last time test yamls need to be fixed after the recently testing changes. Please look at the changes to existing uart tests.

2025-11-07 11:48 UTC, rici4kubicek commented
> As requested last time test yamls need to be fixed after the recently testing changes. Please look at the changes to existing uart tests.

Thanks for the clarification of your request.

2025-11-07 16:50 UTC, swoboda1337 requested changes

2025-11-07 16:50 UTC, swoboda1337 commented on tests/components/hlw8032/test.esp32-c3-idf.yaml
> +substitutions:
```suggestion
```

2025-11-07 16:50 UTC, swoboda1337 commented on esphome/components/hlw8032/sensor.py
> +FINAL_VALIDATE_SCHEMA = uart.final_validate_device_schema(
```suggestion

FINAL_VALIDATE_SCHEMA = uart.final_validate_device_schema(
```

2025-11-07 17:29 UTC, swoboda1337 requested changes

2025-11-07 17:29 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.cpp
> +  if (((data == 0x55) || (data == 0xaa) || (data & 0xf0)) && !this->header_found_) {
This check seems wrong. Why do you have `data & 0xf0` here? You could replace this line with:
```
if ((data & 0xf0) && !this->header_found_) {
```

2025-11-07 17:29 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.cpp
> +  if (((data == 0x55) || (data == 0xaa) || (data & 0xf0)) && !this->header_found_) {
Is that correct? Does any bit in the top nibble signal that it is the start of the header? No other bytes have any bits set in the top nibble?

2025-11-07 17:29 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.cpp
> +    voltage = float(voltage_parameter) * this->voltage_divider_ / float(voltage_reg);
Should check if voltage_reg is non zero first to avoid a divide by zero. Similar issues with other divides on lines 122 and 130.

2025-11-07 17:29 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.cpp
> +    power_cycle_exceeds_range = state_reg & (1 << 1);
Why not use have_power?

2025-11-07 17:29 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.cpp
> +               !parameter_regs_usable ? "\n  Voltage/Current/Power Parameter REGs not usable." : "");
Why make printing of these strings conditional? Why not just print the values? If would be useful to print no if there is no overflow.  There is a YESNO macro you can use.

2025-11-07 17:29 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.cpp
> +namespace hlw8032 {
```suggestion
namespace esphome::hlw8032 {
```

2025-11-07 17:29 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.cpp
Many magic numbers in the code, could so do something like:
```
  static constexpr uint8_t VOLTAGE_PARAM_OFFSET = 2;
  static constexpr uint8_t VOLTAGE_REG_OFFSET = 5;
  static constexpr uint8_t DATA_UPDATE_REG_OFFSET = 20;
  static constexpr uint8_t HAVE_POWER_BIT = (1 << 4);
  static constexpr uint8_t HAVE_CURRENT_BIT = (1 << 5);
  static constexpr uint8_t HAVE_VOLTAGE_BIT = (1 << 6);
```

2025-11-07 17:31 UTC, swoboda1337 requested changes

2025-11-07 17:31 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.cpp
> +    ESP_LOGE(TAG, "Function of error correction fails.");
This error message is confusing.

2025-11-08 18:15 UTC, rici4kubicek commented on esphome/components/hlw8032/hlw8032.cpp
> +    ESP_LOGE(TAG, "Function of error correction fails.");
I have tried to make this message more explicit

2025-11-08 18:15 UTC, rici4kubicek commented on esphome/components/hlw8032/hlw8032.cpp
Fixed as suggested

2025-11-08 18:15 UTC, rici4kubicek commented on esphome/components/hlw8032/hlw8032.cpp
> +namespace hlw8032 {
Fixed as suggested

2025-11-08 18:15 UTC, rici4kubicek commented on esphome/components/hlw8032/hlw8032.cpp
> +               !parameter_regs_usable ? "\n  Voltage/Current/Power Parameter REGs not usable." : "");
I have used YESNO macro now

2025-11-08 18:15 UTC, rici4kubicek commented on esphome/components/hlw8032/hlw8032.cpp
> +    power_cycle_exceeds_range = state_reg & (1 << 1);
Refcatored

2025-11-08 18:16 UTC, rici4kubicek commented on esphome/components/hlw8032/hlw8032.cpp
> +    voltage = float(voltage_parameter) * this->voltage_divider_ / float(voltage_reg);
Yes, you are right, I have added missing zero division protection

2025-11-08 18:17 UTC, rici4kubicek commented on esphome/components/hlw8032/hlw8032.cpp
> +  if (((data == 0x55) || (data == 0xaa) || (data & 0xf0)) && !this->header_found_) {
Well, it is from datasheet. There are multiple valid values for the State register (first byte). Valid values are 0x55, 0xaa and 0xfx

2025-11-08 18:22 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.cpp
> +  if (((data == 0x55) || (data == 0xaa) || (data & 0xf0)) && !this->header_found_) {
> Well, it is from datasheet. There are multiple valid values for the State register (first byte). Valid values are 0x55, 0xaa and 0xfx

Ok but that is not what that line is doing. It is currently checking if any bit in the top nibble is 1 (you want to check if all bits are 1). You probably want `(data & 0xF0) == 0xF0` instead

2025-11-08 18:26 UTC, rici4kubicek commented on esphome/components/hlw8032/hlw8032.cpp
> +  if (((data == 0x55) || (data == 0xaa) || (data & 0xf0)) && !this->header_found_) {
Yes, that was a missing condition. I have added this condition. So now, there is a check for three values:
* `0x55`
* `0xaa`
* `(data & 0xF0) == 0xF0`

2025-11-10 19:15 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.cpp
> +}
Changed this to a while loop, best to read everything, the loop will only run every 16 msec.

2025-11-10 19:32 UTC, swoboda1337 commented
Looks good to me. Do you mind retesting this after my changes? Thanks

2025-11-10 19:45 UTC, swoboda1337 approved these changes

2025-11-10 19:47 UTC, swoboda1337 requested changes

2025-11-10 19:47 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.h
> +
```suggestion
```

2025-11-10 19:47 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.h
> +
```suggestion
```

2025-11-10 19:48 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.h
> +
```suggestion
```

2025-11-10 19:49 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.h
> +
```suggestion
```

2025-11-10 19:49 UTC, swoboda1337 submitted a review, later dismissed

2025-11-12 11:43 UTC, rici4kubicek commented
> Looks good to me. Do you mind retesting this after my changes? Thanks

I have tested it after changes. It works fine. Thanks for the changes and help.

2025-11-14 20:24 UTC, swoboda1337 approved these changes

2025-12-06 20:12 UTC, swoboda1337 requested changes

2025-12-06 20:12 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.h
> +namespace hlw8032 {
```suggestion
namespace esphome::hlw8032 {
```

2025-12-06 20:12 UTC, swoboda1337 commented on esphome/components/hlw8032/hlw8032.h
> +}  // namespace esphome
```suggestion
}  // namespace esphome::hlw8032
```

2025-12-07 19:36 UTC, swoboda1337 approved these changes

2025-12-08 14:07 UTC, merged