bl0942: Fix init sequence, add address and line_frequency options
OttoWinter/esphomeyaml pull request #7250
Opened 2024-08-12 14:17 UTC by dwmw2

Closes: https://github.com/esphome/issues/issues/6143

# What does this implement/fix?

Fix the register definitions and init sequence for the BL0942 sensor.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/6143

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> (pending)

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [x] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
uart:
  id: uart_bus
  tx_pin: TX1
  rx_pin: RX1
  baud_rate: 4800
  stop_bits: 1

sensor:
  - platform: bl0942
    uart_id: uart_bus
    line_frequency: 60Hz
    address: 0
    update_interval: 20s
    current:
      name: BL0942 Current
    voltage:
      name: BL0942 Voltage
    power:
      name: BL0942 Power
      filters:
        multiply: -1
    energy:
      name: BL0942 Energy
    frequency:
      name: BL0942 Frequency
      accuracy_decimals: 2

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-12 14:27 UTC, dwmw2 commented
No material changes to anything but bl0942; just making `CONF_LINE_FREQUENCY` common as CI demanded it.

2024-08-13 03:43 UTC, jesserockz requested changes

2024-08-13 03:43 UTC, jesserockz commented on esphome/components/bl0942/sensor.py
> +            ),
```suggestion
            cv.Optional(CONF_LINE_FREQUENCY, default="50HZ"): cv.All(
                cv.frequency,
                cv.enum(
                    LINE_FREQS, int=True
                ),
            )
```

2024-08-13 03:43 UTC, jesserockz commented on esphome/components/bl0942/sensor.py
> +}
This needs to be moved down in this file
```suggestion
LineFrequency = bl0942_ns.enum("LineFrequency")
LINE_FREQS = {
    50: LineFrequency.LINE_FREQUENCY_50HZ,
    60: LineFrequency.LINE_FREQUENCY_60HZ,
}
```

2024-08-13 03:43 UTC, jesserockz commented on esphome/components/bl0942/bl0942.h
> +  void set_line_freq(int freq) { line_freq_ = freq; }
```suggestion
  void set_line_freq(LineFrequency freq) { this->line_freq_ = freq; }
```

2024-08-13 03:43 UTC, jesserockz commented on esphome/components/bl0942/bl0942.h
> +  void set_address(int address) { address_ = address; }
```suggestion
  void set_address(int address) { this->address_ = address; }
```

2024-08-13 03:43 UTC, jesserockz commented on esphome/components/bl0942/bl0942.cpp
> +    ESP_LOGCONFIG(TAG, "  Mode register: 0x%x", modereg);
Data transactions should not be done in `dump_config`. This is only to print out the configuration variables, or data that was previously gathered (in `setup` for example)

2024-08-13 11:59 UTC, dwmw2 commented on esphome/components/bl0942/bl0942.cpp
> +    ESP_LOGCONFIG(TAG, "  Mode register: 0x%x", modereg);
Thanks. I'll move it to `setup()` as a sanity check that the device is really there and we aren't just sending serial bytes into the void.

2024-08-13 12:17 UTC, dwmw2 commented on esphome/components/bl0942/bl0942.h
> +  void set_line_freq(int freq) { line_freq_ = freq; }
```
src/esphome/components/bl0942/bl0942.h:38:22: error: 'LineFrequency' has not been declared
   38 |   void set_line_freq(LineFrequency freq) { this->line_freq_ = freq; }
      |                      ^~~~~~~~~~~~~
```
Do I have to define the corresponding enum in C++ code too, or should it be autogenerated somewhere?

2024-08-13 12:22 UTC, dwmw2 commented on esphome/components/bl0942/bl0942.h
> +  void set_line_freq(int freq) { line_freq_ = freq; }
Answered my own question by looking for other examples. I note the other examples of 'LineFrequency' don't do it this way; I had just copied from those.

2024-08-13 15:40 UTC, dbuezas commented
I unfortunately don't have my bl0942 bulb anymore, was this confirmed to work?
When I first made a custom component for it (which was used as a base for this integration and the open even one), the datasheet wasn't available so I reversed engineered the protocol.
It may well be that that initialization code was imperfect and this PR makes it fully compliant

2024-08-13 16:32 UTC, dwmw2 commented
Yes, I'm reading back the mode register and checking it works, and have checked the order of the soft reset vs. write protect by checking when the mode is reset. Fill details in the linked issue.

2024-08-14 02:27 UTC, jesserockz commented on esphome/components/bl0942/bl0942.h
> +  void set_line_freq(int freq) { line_freq_ = freq; }
> I note the other examples of 'LineFrequency' don't do it this way; I had just copied from those.

I will add to my list to update the others.

2024-08-14 08:58 UTC, dwmw2 commented
@dbuezas Where did you get your calibration data from?

```
static const float BL0942_PREF = 596;              // taken from tasmota
static const float BL0942_UREF = 15873.35944299;   // should be 73989/1.218
static const float BL0942_IREF = 251213.46469622;  // 305978/1.218
static const float BL0942_EREF = 3304.61127328;    // Measured
```
I'm tempted to make those calibration options, but that's not very helpful unless I can document for the user how to set them. _(And it would be great if we now know enough about decrypting the Tuya storage partitions that we could even find the factory settings!)._

As I understand it, the inputs of the "calibration-free IC" are a linear factor of the voltage and the current. The IC then measures the phase difference between the two, remembers everything I've forgotten about AC power theory, and uses it to calculate the actual power, as well as accumulating that to count total energy flow.

So calculating `UREF` and `IREF` ought to be as simple as applying an external meter and comparing with the raw values from the IC. And all that **I** need to remember about AC power theory is that the I and the V are on the top of the equation, so both power and energy factors ought to be proportional to (`UREF` * `IREF`) ?

2024-08-14 11:13 UTC, dwmw2 commented
Let's deal with the calibration separately, in https://github.com/esphome/issues/issues/6155. This PR should be ready to go, and just addresses the setup issues.

2024-08-14 12:51 UTC, dbuezas commented
@dwmw2 

> Where did you get your calibration data from?

I'm sorry, I confused this with the BP5758, which is an LED driver. Looking at my PR for this one I see that PRef was from tasmota and the others just measured.

2024-08-14 15:07 UTC, dwmw2 commented
@jesserockz I believe I've made the changes you asked for and clicked the 'Ready for review' button as directed, but it still seems to say '1 change requested'. Have I done something wrong?

Apologies for hassling, if it's just in your queue and you'll get round to it when you can.

2024-08-16 17:15 UTC, dwmw2 commented
Hm, why does the pull request list still say this has 'Changes requested'?

![Screenshot from 2024-08-16 18-14-48](https://github.com/user-attachments/assets/166fdad7-9785-4722-90a6-533ed6c7b1a9)

2024-08-26 01:15 UTC, jesserockz requested changes
Please also add the line_frequency and address to 1 or more yaml tests.

2024-08-26 01:15 UTC, jesserockz commented on esphome/components/bl0942/bl0942.cpp
>        received_package_(&buffer);
```suggestion
    if (this->validate_checksum_(&buffer)) {
      this->received_package_(&buffer);
```

2024-08-26 01:16 UTC, jesserockz commented on esphome/components/bl0942/bl0942.h
> +  void set_address(int address) { this->address_ = address; }
```suggestion
  void set_address(uint8_t address) { this->address_ = address; }
```

2024-08-26 01:16 UTC, jesserockz requested changes

2024-08-26 01:16 UTC, jesserockz commented on esphome/components/bl0942/bl0942.cpp
>        received_package_(&buffer);
```suggestion
      this->received_package_(&buffer);
```

2024-08-26 01:16 UTC, jesserockz commented on esphome/components/bl0942/bl0942.cpp
>    if (read_array((uint8_t *) &buffer, sizeof(buffer))) {
```suggestion
  if (this->read_array((uint8_t *) &buffer, sizeof(buffer))) {
```

2024-08-26 22:23 UTC, jesserockz commented
@dwmw2 Please dont force push/rebase PRs once a review has started. It makes seeing followup changes more difficult and means the entire PR has to be reviewed again

2024-08-26 22:27 UTC, dwmw2 commented
> @dwmw2 Please dont force push/rebase PRs once a review has started. It makes seeing followup changes more difficult and means the entire PR has to be reviewed again

Ack. Would you like me to undo that, or would that make it worse now?

2024-08-26 22:38 UTC, jesserockz approved these changes

2024-08-26 22:38 UTC, jesserockz commented
> Ack. Would you like me to undo that, or would that make it worse now?

It can't be fixed once done.

2024-08-26 22:41 UTC, merged

2024-08-26 22:50 UTC, dwmw2 commented
OK. I have rebased #7299 though, as that was based on this one, and I don't believe the review had really started. Hope that's OK.