Adding EPaper support for GDEY075Z08 including segment-based partial updates.
OttoWinter/esphomeyaml pull request #7264
Opened 2024-08-13 11:10 UTC by DJGummikuh

# What does this implement/fix?

Adding support for the 7.5 inch, Black/White/Red GDEY075Z08 ePaper Display from GoodDisplay

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4133

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  - platform: waveshare_epaper
    cs_pin: GPIO27
    dc_pin: GPIO14
    num_segments_x: 50
    num_segments_y: 20
    update_interval: 35s
    full_update_every: 10
    busy_pin:
      number: GPIO13
      inverted: true
    reset_pin: GPIO12
    model: 7.5in-bgr-gd
    lambda: |-
      ...
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-13 19:45 UTC, jesserockz requested changes
Here is an initial review. I have not gone over everything yet.

2024-08-13 19:45 UTC, jesserockz commented on esphome/components/waveshare_epaper/display.py
> +            cv.Optional(CONF_NUM_SEGMENTS_Y): cv.int_range(min=1, max=100),
If this only exists on this one model, there needs to be an extra validation to ensure users do not set it for others.

2024-08-13 19:45 UTC, jesserockz commented on esphome/components/waveshare_epaper/display.py
> +        cg.add(var.set_num_segments_y(config["num_segments_y"]))
```suggestion
    if num_segments_x := config.get(CONF_NUM_SEGMENTS_X):
        cg.add(var.set_num_segments_x(num_segments_x))
    if num_segments_y := config.get(CONF_NUM_SEGMENTS_Y):
        cg.add(var.set_num_segments_y(num_segments_y))
```

2024-08-13 19:45 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +          segment[segment_position + segment_size] = buffer_[global_position + buffer_half_size];  // copy red data
```suggestion
          segment[segment_position] = this->buffer_[global_position];                                    // copy black data
          segment[segment_position + segment_size] = this->buffer_[global_position + buffer_half_size];  // copy red data
```

2024-08-13 19:45 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +      uint8_t *segment = new uint8_t[segment_size * 2];  // create segment array (muliply by 2 since we need 2 byte per
You should be creating this array once, and reusing it for all of the loop iterations.
Please also use `ExternalRAMAllocator` to allocate and deallocate

2024-08-13 19:45 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +             last_segment_x_, last_segment_y_);
Please ensure all member variable access and function calls are prefixed with `this->`

```suggestion
    ESP_LOGD(TAG, "CRC Calculation finished. Found changes: %02d:%02d to %02d:%02d", this->first_segment_x_, this->first_segment_y_,
             this->last_segment_x_, this->last_segment_y_);
```

2024-08-13 19:45 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +  }
This should be enforced at config validation, not at runtime.
```suggestion
  this->seg_x_ = value;
```

2024-08-13 19:45 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +                   seg_y_];  // initialize the checksums array. Will be filed and maintained by calculate_CRCs_()
Please use `ExternalRAMAllocator`

2024-08-13 20:14 UTC, DJGummikuh commented on esphome/components/waveshare_epaper/display.py
> +            cv.Optional(CONF_NUM_SEGMENTS_Y): cv.int_range(min=1, max=100),
This exists for the moment only for this one model. I do however fully expect that other large displays would also profit from this (I only have the GDEY075Z08 so I can't actually test, but I know of at least one person that has a waveshare 7.5 and also would want partial update functionality).
Last, I don't know how to add that validation :sweat_smile:

2024-08-13 20:18 UTC, DJGummikuh commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +  }
I actually thought about this, and didn't know how to do this. I don't have the dimensions of the display in python (since they are managed in the C++ Code), PLUS if (as I am fully expecting), these settings will also be eventually used for other displays with different resolutions, the values would probably be different.

2024-08-13 21:07 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +  }
Most displays either have hardcoded resolutions in the `get_width_internal` or they are set by the user in config. 
Since this only applies to this display right now, we can start a dict of model -> resolution and look it up that way.

2024-08-13 21:08 UTC, jesserockz commented on esphome/components/waveshare_epaper/display.py
> +            cv.Optional(CONF_NUM_SEGMENTS_Y): cv.int_range(min=1, max=100),
Same as `validate_full_update_every_only_types_ac` and `validate_reset_pin_required`

2024-08-13 21:10 UTC, jesserockz commented on esphome/components/waveshare_epaper/waveshare_epaper.cpp
> +  this->segment_buffer_ = allocator8.allocate(
Do check that `this->segment_buffer_ != nullptr` (same for checksums) after allocating to make sure it was allocated. If it wasnt, you should call `this->mark_failed();`, print an error log, and `return;`

2024-08-20 21:28 UTC, DJGummikuh commented
I pulled the PR back to draft. Turns out I was abusing the display and didn't actually use the proper partial update functionality. Will have to develop this some more, including a better segment approach that allows individual segments to be updated in sequence (as opposed to building one huge square over it) as this allows me to get away with deciding between partial update and full update only if red pixels are affected.

2025-10-13 00:50 UTC, closed without merging