Added Device Address Functionality to BL0939 Component
OttoWinter/esphomeyaml pull request #7293
Opened 2024-08-15 15:15 UTC by praveens-git

# What does this implement/fix?

The BL0939 IC is available in two packages SOP16 & SSOP20L. The SSOP20L has address selection functionality which was not implemented in the component. This feature enables the user to add up to 15 BL0939 components in a single loop.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

sensor:
  - platform: bl0939
    uart_id: uart_2
    voltage:
      name: 'BL0939 Voltage'
    current_1:
      name: 'BL0939 Current 1'
    current_2:
      name: 'BL0939 Current 2'
    active_power_1:
      name: 'BL0939 Active Power 1'
    active_power_2:
      name: 'BL0939 Active Power 2'
    energy_1:
      name: 'BL0939 Energy 1'
    energy_2:
      name: 'BL0939 Energy 2'
    energy_total:
      name: 'BL0939 Energy Total'

    device_address: 0
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-19 21:06 UTC, dwmw2 commented
For BL0942 I called this just `address`.

See also the calibration, in https://github.com/esphome/esphome/pull/7299

2024-08-20 03:08 UTC, praveens-git commented
Ok, I will update as address.

2024-08-20 08:48 UTC, dwmw2 commented
You should be able to mostly cut and paste the commit which does the calibration too, although the constants are different for the BL0939 as noted in bl0939.h.

2024-08-21 03:39 UTC, praveens-git commented
Hi @dwmw2, I have changed the address key as you requested. Since the line Frequency Constant has not been added (merged yet), How can I implement the calibration part, wouldn't that cause some issues?

2024-08-21 06:32 UTC, dwmw2 commented
> Hi @dwmw2, I have changed the address key as you requested. Since the line Frequency Constant has not been added (merged yet), How can I implement the calibration part, wouldn't that cause some issues?

Hopefully that will be merged soon. But if not, perhaps we should add it in my PR too? The main reason I didn't touch BL0939 and BL0940 was because I couldn't test them.

2025-07-02 12:34 UTC, jesserockz requested changes

2025-07-02 12:34 UTC, jesserockz commented on esphome/components/bl0939/bl0939.h
> +  int device_address_;
```suggestion
  uint8_t device_address_;
```

2025-07-02 12:34 UTC, jesserockz commented on esphome/components/bl0939/bl0939.h
> +  void set_device_address(int device_address) { device_address_ = device_address; }
```suggestion
  void set_device_address(uint8_t device_address) { this->device_address_ = device_address; }
```

2025-07-02 12:34 UTC, jesserockz commented on esphome/components/bl0939/bl0939.h
> +  uint8_t bl0939_init_[6][6];
This is only used once during setup, not really needed to store forever after

2025-07-02 12:34 UTC, jesserockz commented on esphome/components/bl0939/bl0939.cpp
>    }
```suggestion
  for (uint8_t *i : BL0939_INIT_DEFAULT) {
    this->write_byte(BL0939_WRITE_COMMAND | (this->address_ & 0xF));
    this->write_array(i, 5);
    delay(1);
  }
```

2025-07-02 12:34 UTC, jesserockz commented on esphome/components/bl0939/bl0939.cpp
> +static const uint8_t BL0939_INIT_DEFAULT[6][6] = {
Since the first byte is always `BL0939_WRITE_COMMAND`, remove it from here and write it manually with the address as in my above suggestion.

2025-10-12 00:50 UTC, closed without merging