Support BL0942 calibration
OttoWinter/esphomeyaml pull request #7299
Opened 2024-08-16 15:03 UTC by dwmw2

# What does this implement/fix?

Calibration of BL0942 power sensor

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/6155
**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> #TBD

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
  - platform: bl0942
    uart_id: uart_bus
    line_frequency: 50Hz
    address: 0
    update_interval: 20s
    current:
      name: ${tongou_name} Current
    voltage:
      name: ${tongou_name} Voltage
    power:
      name: ${tongou_name} Power
      filters:
        multiply: -1
    energy:
      name: ${tongou_name} Energy
    frequency:
      name: ${tongou_name} Frequency
      accuracy_decimals: 2
    voltage_reference: ${voltage_ref}
    current_reference: ${current_ref}
    power_reference: ${power_ref}
    energy_reference: ${energy_ref}

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-16 15:03 UTC, dwmw2 commented
This is on top of the simpler bug fix in https://github.com/esphome/issues/issues/6143

2024-08-16 17:32 UTC, descipher commented on esphome/components/bl0942/bl0942.cpp
>    LOG_SENSOR("", "Power", this->power_sensor_);
LOG_SENSOR("", "Energy", this->energy_sensor_);
  LOG_SENSOR("", "frequency", this->frequency_sensor_);

frequency can be capitalized

2024-08-16 18:43 UTC, dwmw2 commented
@dbuezas Are you OK for me to mark myself as a co-owner for this component?

2024-08-16 19:14 UTC, CircuitSetup commented on esphome/components/atm90e32/sensor.py
> +    CONF_LINE_FREQUENCY,
Im unsure why this needs to be changed. Care to explain?

2024-08-16 19:16 UTC, dwmw2 commented on esphome/components/atm90e32/sensor.py
> +    CONF_LINE_FREQUENCY,
The CI complained at me that as I was adding the third instance of `CONF_LINE_FREQUENCY` I now needed to consolidate them into `const.py`

2024-08-16 19:19 UTC, descipher commented on esphome/components/atm90e32/sensor.py
> +    CONF_LINE_FREQUENCY,
It's just CI forced cleanup, the two constants are identical so it's prefered to use the const.py defined one vs creating a local const. with the same or possibly overriding one.

2024-08-16 20:10 UTC, CircuitSetup commented on esphome/components/atm90e32/sensor.py
> +    CONF_LINE_FREQUENCY,
got it, thanks!

2024-08-19 21:09 UTC, dwmw2 commented on esphome/components/bl0942/bl0942.cpp
>    LOG_SENSOR("", "Power", this->power_sensor_);
Done

2024-08-25 22:59 UTC, jesserockz commented on esphome/components/atm90e32/sensor.py
> +    CONF_LINE_FREQUENCY,
I have made https://github.com/esphome/esphome/pull/7351 to remove those changes from this PR

2024-08-26 01:17 UTC, jesserockz commented
Coverted to draft until https://github.com/esphome/esphome/pull/7250 is merged

2024-08-26 19:48 UTC, dwmw2 commented
Added calibration fields to YAML tests.

2024-08-27 03:47 UTC, jesserockz requested changes

2024-08-27 03:47 UTC, jesserockz commented on esphome/components/bl0942/sensor.py
> +        cg.add(var.set_current_reference(config[CONF_CURRENT_REFERENCE]))
```suggestion
    if (current_reference := config.get(CONF_CURRENT_REFERENCE, None)) is not None:
        cg.add(var.set_current_reference(current_reference))
```

2024-08-27 03:47 UTC, jesserockz commented on esphome/components/bl0942/bl0942.cpp
> +  if (!this->power_reference_set_)
```suggestion
  if (this->power_reference_set_ && !this->energy_reference_set_)
```

2024-08-27 03:47 UTC, jesserockz commented on esphome/components/bl0942/bl0942.cpp
> +    this->energy_reference_ = this->power_reference_ * 3600000 / 419430.4;
```suggestion
    this->energy_reference_ = this->power_reference_ * 3600000 / 419430.4;
    this->energy_reference_set_ = true
```

2024-08-27 07:23 UTC, dwmw2 commented on esphome/components/bl0942/bl0942.cpp
> +    this->energy_reference_ = this->power_reference_ * 3600000 / 419430.4;
Nobody cares if it's set any more, but I suppose it makes sense. Will need `{}` around it though.

2024-09-04 01:11 UTC, jesserockz requested changes

2024-09-04 01:11 UTC, jesserockz commented on esphome/components/bl0942/sensor.py
> +    if (current_reference := config.get(CONF_CURRENT_REFERENCE, None)) is not None:
The same changes need to be applied to the 3 below too =)

2024-09-04 08:02 UTC, dwmw2 commented on esphome/components/bl0942/sensor.py
> +    if (current_reference := config.get(CONF_CURRENT_REFERENCE, None)) is not None:
Does that make a difference? When I omit those parameters from the yaml configuration, nothing shows up in main.cpp for them. They already get elided somewhere, it seems?

2024-09-05 00:01 UTC, jesserockz approved these changes

2024-09-05 00:05 UTC, jesserockz commented on esphome/components/bl0942/bl0942.cpp
> +  }
Maybe for another PR in the future if you are up for it, it would be better to set the defaults in python, and do this calculation in python so at runtime it will always have the values set.

2024-09-05 00:08 UTC, merged