add the ability to add more idf components to an existing setup
OttoWinter/esphomeyaml pull request #7302
Opened 2024-08-17 11:41 UTC by nielsnl68

# What does this implement/fix?

When a one component added some extra esp_idf components a second attempt was ignored.
With this PR the new components and submodules are bying added to the earlier request.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-18 22:49 UTC, jesserockz requested changes

2024-08-18 22:49 UTC, jesserockz commented on esphome/components/esp32/__init__.py
> +            KEY_COMPONENTS: components if components is not None else [],
Line 164-165 above ensures it is at least an empty list already
```suggestion
            KEY_COMPONENTS: components,
```

2024-08-18 22:49 UTC, jesserockz commented on esphome/components/esp32/__init__.py
> +            KEY_SUBMODULES: submodules if submodules is not None else [],
This will break the `clone_or_update` function that checks explicitly for `None`

2024-08-19 00:42 UTC, jesserockz commented on esphome/components/esp32/__init__.py
> +        if components is not None:
Lets pull this out to clean it up a bit
```suggestion
        component_config = CORE.data[KEY_ESP32][KEY_COMPONENTS][name]
        if components is not None:
```

2024-08-19 02:23 UTC, jesserockz commented on esphome/components/esp32/__init__.py
> +                    set([KEY_SUBMODULES] + submodules)
Missing a critical piece :wink: 
```suggestion
                    set(component_config[KEY_SUBMODULES] + submodules)
```

2024-08-19 17:24 UTC, nielsnl68 commented on esphome/components/esp32/__init__.py
> +                    set([KEY_SUBMODULES] + submodules)
I think i was sleeping at that point :(

2024-08-19 22:21 UTC, jesserockz approved these changes

2024-08-19 22:22 UTC, merged