[i2s_audio] Add more options to speakers and microphones
OttoWinter/esphomeyaml pull request #7306
Opened 2024-08-18 13:06 UTC by pyos

# What does this implement/fix?

Now I2S speakers also have the following options that already exist for microphones:

 * `i2s_mode` (primary/secondary; default: primary)
 * `use_apll` (true/false, default: false)
 * `channel` (left/right/mono/stereo, default: mono)
 * `sample_rate` (default: 16000)
 * `bits_per_sample` (default: 16bit)

Both speakers and microphones also have:

 * `bits_per_channel` (default: equal to `bits_per_sample`)

`channel` has new values:

 * stereo: input/output data is interpreted as a sequence of (right, left) pairs (this option works for both speakers and microphones);
 * mono: for speakers, this is the old behavior - each sample from the input is sent to both left and right channels.

Also, speakers have an extra option:

 * `timeout` (default: 100ms) - how long the background tasks should wait before releasing the bus if the buffer is empty.

The `mode` option of speakers was removed, because it didn't actually do anything.

The `pdm` option for microphones is now optional and defaults to `false`.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
i2s_audio:
- i2s_lrclk_pin: 26
  i2s_bclk_pin: 27
  id: i2so
- i2s_lrclk_pin: 33 # WS
  i2s_bclk_pin: 32 # SCK
  id: i2si

microphone:
- platform: i2s_audio
  id: sound_in
  adc_type: external
  i2s_din_pin: 25 # SD
  i2s_audio_id: i2si
  sample_rate: 24000
  bits_per_sample: 32bit
  channel: right
  on_data:
    lambda: |-
      id(sound_out)->play((const uint8_t*)x.data(), x.size() * sizeof(x[0]));

speaker:
- platform: i2s_audio
  id: sound_out
  dac_type: external
  i2s_dout_pin: 14
  i2s_audio_id: i2so
  sample_rate: 24000
  bits_per_sample: 32bit
  channel: mono
  timeout: 500ms
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-19 00:53 UTC, nielsnl68 requested changes
It looks like we had almost the same ideas, already. 
see: 
https://github.com/esphome/esphome/pull/7183
https://github.com/esphome/esphome/pull/7137

2024-08-19 00:53 UTC, nielsnl68 commented on esphome/components/i2s_audio/__init__.py
> +    CONF_MONO: i2s_channel_fmt_t.I2S_CHANNEL_FMT_ALL_LEFT,
In what case would you suggest this is useful?  I have played with the same ideas as you and i also already added some PR's for some suggested changes as well. 
In the end i saw no use case to have the option for  `i2s_channel_fmt_t.I2S_CHANNEL_FMT_ALL_LEFT,` available. only the other 3 are interesting.

2024-08-19 00:53 UTC, nielsnl68 commented on esphome/components/i2s_audio/__init__.py
> +            ),
Just not sure we should offer this. imho it makes everything a bit difficult. But when you see a really use case. Then i don't mind.

2024-08-19 00:53 UTC, nielsnl68 commented on esphome/components/i2s_audio/microphone/__init__.py
> +                    cv.Optional(CONF_PDM, default=False): cv.boolean,
In my honest opinion this should be an option for the ADC_TYPE enum like:
internal, standard, PDM

2024-08-19 00:53 UTC, nielsnl68 commented on esphome/components/i2s_audio/microphone/i2s_audio_microphone.cpp
> +      .bits_per_chan = this->bits_per_channel_,
look at the remark above about this option.

2024-08-19 00:53 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/__init__.py
> +    default_channel=CONF_MONO,
My suggestion is to use "CONF_RIGHT" here.

2024-08-19 00:53 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +    if (xQueueReceive(this_speaker->buffer_queue_, &data_event, this_speaker->timeout_) != pdTRUE) {
```suggestion
    if (xQueueReceive(this_speaker->buffer_queue_, &data_event, this_speaker->timeout_ / portTICK_PERIOD_MS) != pdTRUE) {
```

2024-08-19 00:53 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.h
> +#include "esphome/components/i2s_audio/i2s_audio.h"
?

2024-08-19 00:53 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.h
> -  void set_external_dac_channels(uint8_t channels) { this->external_dac_channels_ = channels; }
where did you moved this to?

2024-08-19 07:42 UTC, pyos commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.h
> -  void set_external_dac_channels(uint8_t channels) { this->external_dac_channels_ = channels; }
nowhere, it was not used

2024-08-19 07:43 UTC, pyos commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.h
> +#include "esphome/components/i2s_audio/i2s_audio.h"
copied from a custom_components directory, forgot to revert

2024-08-19 07:43 UTC, pyos commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +    if (xQueueReceive(this_speaker->buffer_queue_, &data_event, this_speaker->timeout_) != pdTRUE) {
already divided in the setter

2024-08-19 07:43 UTC, pyos commented on esphome/components/i2s_audio/speaker/__init__.py
> +    default_channel=CONF_MONO,
CONF_MONO is equivalent to the current behavior

2024-08-19 07:45 UTC, pyos commented on esphome/components/i2s_audio/__init__.py
> +            ),
technically INMP441 for example has 24-bit data in 32-bit channels, but since 32-bit data mode discards the low 8 bits anyway it doesn't really matter

2024-08-19 07:52 UTC, pyos commented on esphome/components/i2s_audio/__init__.py
> +    CONF_MONO: i2s_channel_fmt_t.I2S_CHANNEL_FMT_ALL_LEFT,
this mode plays the same sound on both channels, so it's useful for switching the same 2-amplifier/speaker arrangement between mono and stereo mode in software (you can call speaker.set_channel in a lambda while it's not playing)

2024-08-19 08:12 UTC, pyos commented on esphome/components/i2s_audio/__init__.py
> +    CONF_MONO: i2s_channel_fmt_t.I2S_CHANNEL_FMT_ALL_LEFT,
in your PRs my `channel: mono` is your `use_16bit_mode: true` with `channel: stereo`, I just put it as a separate `channel` option because combining `use_16bit_mode: true` with `channel: left` and `channel: right` is wrong

2024-08-19 08:42 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.h
> -  void set_external_dac_channels(uint8_t channels) { this->external_dac_channels_ = channels; }
Ha yes, this is one of the phantom variable @jesserockz added to the speaker component :P

2024-08-19 08:45 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/__init__.py
> +    default_channel=CONF_MONO,
I know, but still i do think it is not necessary

2024-08-19 08:50 UTC, nielsnl68 commented on esphome/components/i2s_audio/__init__.py
> +    CONF_MONO: i2s_channel_fmt_t.I2S_CHANNEL_FMT_ALL_LEFT,
> in your PRs my channel: mono is your use_16bit_mode: true with channel: stereo, I just put it as a separate channel option because combining use_16bit_mode: true with channel: left and channel: right is wrong

True that was a mistake in later work i removed this option in favor of I2S_CHANNELS like you do.

2024-09-10 23:52 UTC, jesserockz commented
I have rebased this PR after merging #7183. The tests compile but I have not actually looked at the code or reviewed or tested yet.

2024-09-11 02:52 UTC, jesserockz commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +  bytes *= (sizeof(b) / sizeof(a)) * (repeat ? 2 : 1);
```suggestion
  bytes *= (sizeof(b) / sizeof(a)) * (repeat ? 2 : 1);  // NOLINT
```

2024-09-11 05:12 UTC, jesserockz approved these changes

2024-09-11 05:12 UTC, merged