Fix RP2040 Neopixel flickering issue
OttoWinter/esphomeyaml pull request #7307
Opened 2024-08-18 14:21 UTC by deCodeIt

# What does this implement/fix?

Fixes Raspberry Pi Pico W ( RP2040 ) flickering issue for the following cases:
- Any addressable effect used to cause random flickering along with random color leds in between.
- Flickering during normal color change transitions

The dma writes were missing interrupt handling causing writes to fire faster than the previous writes used to complete ending up with flickering and random colors. This patch adds interrupt handling for dma writes.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [esphome/issues#6083](https://github.com/esphome/issues/issues/6083)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
light:
  - platform: rp2040_pio_led_strip
    name: LED test
    id: led_strip
    pin: GPIO28
    num_leds: 30
    pio: 0
    rgb_order: GRB
    chipset: WS2812B
    effects:
      - addressable_rainbow:

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-18 14:22 UTC, deCodeIt commented
Tagging @jesserockz

2024-08-19 00:23 UTC, jesserockz requested changes

2024-08-19 00:23 UTC, jesserockz commented on esphome/components/rp2040_pio_led_strip/led_strip.cpp
> +  dma_chan_active_[this->dma_chan_] = true;
Can we add some class prefixes here just to make it clearer what is being accessed?
(I know the other static variables are not marked like this, if you want to update them, that would be helpful too, but that would not be a requirement for this PR.)
```suggestion
  RP2040PIOLEDStripLightOutput::dma_chan_active_[this->dma_chan_] = true;
```

2024-08-19 05:19 UTC, deCodeIt commented
Addressed review changes by using class name to differentiate static class variables.

2024-08-19 21:42 UTC, jesserockz approved these changes

2024-08-19 21:42 UTC, merged