[Modbus Controller] Added preference to change command retries
OttoWinter/esphomeyaml pull request #7312
Opened 2024-08-19 00:21 UTC by 0x3333

# What does this implement/fix?

Currently, if a command fails (no response received), it will retry 5 times. This needs to be configurable by the user; otherwise, in fast environments, it could cause some trouble.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

modbus_controller:
- id: modbus_device
  address: 0x1   ## address of the Modbus slave device on the bus
  modbus_id: modbus1
  setup_priority: -10
  max_cmd_retries: 1
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-21 04:09 UTC, clydebarrow requested changes
Also note that the convention is that class properties like `command_queue_` should always be referenced as `this->command_queue_`.

2024-08-21 04:09 UTC, clydebarrow commented on esphome/components/modbus_controller/modbus_controller.h
> +  uint8_t max_cmd_retries_;
```suggestion
  uint8_t max_cmd_retries_{5};
```
If it's not set in the constructor, it should be initialised to something, even though in the usual case this will get overwritten later.

2024-08-21 04:09 UTC, clydebarrow commented on esphome/components/modbus_controller/__init__.py
> +        cg.add(var.set_max_cmd_retries(config[CONF_MAX_CMD_RETRIES]))
```suggestion
    cg.add(var.set_max_cmd_retries(config[CONF_MAX_CMD_RETRIES]))
```
It will always be set since a default is provided.

2024-08-21 04:09 UTC, clydebarrow commented on esphome/components/modbus_controller/modbus_controller.cpp
> +    if (command->send_counter >= this->max_cmd_retries_) {
```suggestion
    if (command->send_counter == this->max_cmd_retries_) {
```
Can't ever be greater. But this logic could be moved into the `ModbusCommandItem` class so `send_counter` becomes protected, and gets modified only within the class. Either that or move the increment of the counter into this function - the logic should be confined to one class to make it easier to understand and validate.

2024-08-21 04:09 UTC, clydebarrow commented on esphome/components/modbus_controller/__init__.py
> +            cv.Optional(CONF_MAX_CMD_RETRIES, default=5): cv.positive_int,
```suggestion
            cv.Optional(CONF_MAX_CMD_RETRIES, default=5): cv.int_range(min=1),
```
A value of zero would mean the command is never sent. I'm assume that's not meant to be an option.

2024-08-21 04:09 UTC, clydebarrow commented on esphome/components/modbus_controller/modbus_controller.cpp
> +  send_counter++;
Either move the test into this class, or move this increment into the controller class.

2024-08-21 13:25 UTC, 0x3333 commented on esphome/components/modbus_controller/modbus_controller.h
> +  uint8_t max_cmd_retries_;
I moved the initialization to the generated code, but I got your point, will fix. Is there any instrumentation that can "sync" both values? The one in C++ and the one in Python?

2024-08-21 13:25 UTC, 0x3333 commented on esphome/components/modbus_controller/__init__.py
> +        cg.add(var.set_max_cmd_retries(config[CONF_MAX_CMD_RETRIES]))
Got it wrong, will fix.

2024-08-22 20:27 UTC, 0x3333 commented on esphome/components/modbus_controller/__init__.py
> +            cv.Optional(CONF_MAX_CMD_RETRIES, default=5): cv.positive_int,
This is a little confusing I admit, but if this is a retry, I could have this as zero. Because if the command is sent and receives a response, there is no retry per se. What are your thoughts about it?

2024-08-22 20:44 UTC, 0x3333 commented on esphome/components/modbus_controller/__init__.py
> +            cv.Optional(CONF_MAX_CMD_RETRIES, default=5): cv.positive_int,
I'll keep the way it is, and make it clear in the documentation that this number includes the initial sent. If you agree, of course.

2024-08-22 20:56 UTC, clydebarrow commented on esphome/components/modbus_controller/__init__.py
> +            cv.Optional(CONF_MAX_CMD_RETRIES, default=5): cv.positive_int,
Sure, though I can't imagine why anyone would want to specify this and never have it sent. An alternative would be to allow it to be zero, but add 1 when setting to allow for the initial send. That would make sense in that the "retries" value is just that.

2024-08-22 21:01 UTC, 0x3333 commented on esphome/components/modbus_controller/__init__.py
> +            cv.Optional(CONF_MAX_CMD_RETRIES, default=5): cv.positive_int,
The issue is just the nomenclature; if we say this is the retry count, the initial transmission is not a retry, so it should not be counted. I'll add 1 and make sure the documentation makes it clear.

2024-08-22 21:16 UTC, 0x3333 commented
> Also note that the convention is that class properties like `command_queue_` should always be referenced as `this->command_queue_`.

Despite the fact that this PR is not related to this, but I added `this->` to all `command_queue_` calls.

2024-08-23 06:58 UTC, clydebarrow requested changes
Nearly there. Otherwise looks fine.

2024-08-23 06:58 UTC, clydebarrow commented on esphome/components/modbus_controller/modbus_controller.h
> +    this->max_cmd_retries_ = max_cmd_retries + 1;
Only problem here is that `get_max_cmd_retries()` will return a different number to what was set.
```suggestion
    this->max_cmd_retries_ = max_cmd_retries;
```

2024-08-23 06:58 UTC, clydebarrow commented on esphome/components/modbus_controller/modbus_controller.h
> +  bool should_retry(uint8_t max_send_count) { return this->send_count_ < max_send_count; };
Change the test so the first one always gets sent.
```suggestion
  bool should_retry(uint8_t max_retries) { return this->send_count_ <= max_retries; };
```

2024-08-23 20:04 UTC, 0x3333 commented on esphome/components/modbus_controller/modbus_controller.h
> +  bool should_retry(uint8_t max_send_count) { return this->send_count_ < max_send_count; };
In this case we need `max_cmd_retries_` to be 5, but it would represent 4 retries. Am I right? So I can update the documentation.

2024-08-23 21:57 UTC, clydebarrow commented on esphome/components/modbus_controller/modbus_controller.h
> +  bool should_retry(uint8_t max_send_count) { return this->send_count_ < max_send_count; };
Correct. One initial send, 4 retries. On the basis that there will always be the initial send.

2024-08-26 00:55 UTC, clydebarrow commented on esphome/components/modbus_controller/modbus_controller.h
> +  /// How many times we will send a command if we get no response(Includes the first one).
```suggestion
  /// How many times we will retry a command if we get no response
```

2024-08-26 00:57 UTC, clydebarrow submitted a review, later dismissed

2024-08-26 00:57 UTC, clydebarrow commented
Just need an update to the docs now.

2024-08-26 00:59 UTC, clydebarrow commented
Oh, and add the config to one or more the test files under `tests/components/modbus`

2024-08-26 01:20 UTC, 0x3333 commented
I’ll do the docs and test. No worries.

2024-08-26 01:20 UTC, 0x3333 commented
> Just need an update to the docs now.

The docs base is next, right?

2024-08-26 01:24 UTC, clydebarrow commented
> The docs base is next, right?

Correct. When creating the PR make sure you change the base branch in the drop-down, can't be done afterwards. DAMHIK.

2024-08-28 01:36 UTC, 0x3333 commented
> Oh, and add the config to one or more the test files under `tests/components/modbus`

Done

> Correct. When creating the PR make sure you change the base branch in the drop-down, can't be done afterwards. 

Done, PR esphome/esphome-docs#4202

2024-09-05 00:52 UTC, jesserockz approved these changes

2024-09-11 05:21 UTC, merged