feat(WiFi): Add wifi.save_ap_settings action
OttoWinter/esphomeyaml pull request #7335
Opened 2024-08-21 17:10 UTC by Rapsssito

# What does this implement/fix?

Added `wifi.save_ap_settings` action that stores the SSID and password in persistent memory. This allows for more complex setups where the SSID and password might be negotiated dynamically.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
script:
  - id: change_wifi_ap
    then:
      - wifi.save_ap_settings:
          - ssid: MySSID
          - password: password1
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-15 07:09 UTC, Rapsssito commented
@jesserockz, what do you think? It is quite a small PR and might be very useful for dynamic WiFi connections.

2024-09-15 23:14 UTC, jesserockz commented
Not against it, but what would be better would be that the action actually sets the details on the wifi component, makes sure it connects successfully, only then would it save to prefs, otherwise logs an error.

improv does this too:

```c++
  wifi::global_wifi_component->set_sta(sta);
  wifi::global_wifi_component->start_connecting(sta, false);

  ... 
  // Sets state and keeps checking in `loop` if connected before saving.
  ...

  if (wifi::global_wifi_component->is_connected()) {
    wifi::global_wifi_component->save_wifi_sta(this->connecting_sta_.get_ssid(),
                                             this->connecting_sta_.get_password());
  }
```

2024-09-17 10:37 UTC, Rapsssito commented
@jesserockz, you are right! I have updated the method so it now checks for a connection before saving it to the device. I had to use `wifi.disable()` and `wifi.enable()` to make it work (the WiFi component does not like to be disconnected from the current network). Let me know what you think!

I will update the documentation once it is approved, to avoid having to change it again.

2024-10-22 19:29 UTC, Rapsssito commented
@jesserockz, just pinging you again as a friendly reminder!

2024-11-19 22:02 UTC, pzich commented
@jesserockz is this good to merge? Or are there changes that need to be made?

2024-11-20 04:41 UTC, jesserockz commented
Will review again after release this week

2024-11-20 18:09 UTC, jesserockz requested changes
Further to my requested name change below, I think adding a `save: bool` config to the schema to allow users to not save to prefs (can default to true) would be nice too.

2024-11-20 18:09 UTC, jesserockz commented on esphome/components/wifi/__init__.py
> +    "wifi.set_sta",
Not sure I like the action name being `set_sta`. This refers to an internal function name and is not exactly user friendly for the yaml side. 
Maybe simply `wifi.connect`?
```suggestion
    "wifi.connect",
```

2024-11-20 18:29 UTC, pzich commented on esphome/components/wifi/__init__.py
> +    "wifi.set_sta",
I feel like `connect` could be confused with just enabling/disabling it. Maybe `update`, `change`, or even just `set`?

2024-11-20 18:30 UTC, jesserockz commented on esphome/components/wifi/__init__.py
> +    "wifi.set_sta",
This is true, maybe `wifi.configure`?

2024-11-20 18:37 UTC, pzich commented
Probably outside of the scope of this PR, but it might be useful if this could optionally take `networks` instead (similar to the wifi config itself) to update/replace the whole set of ssid/pws in the list.

2024-11-23 15:20 UTC, Rapsssito commented
@jesserockz, @pzich, I have implemented your suggestions. Let me know what you think!

Regarding multiple networks, sadly I am not familiar with that kind of setup. @pzich, feel free to build on top of my PR!

2024-11-24 21:59 UTC, jesserockz approved these changes

2024-11-24 22:06 UTC, merged