Update i2s_audio media_player
OttoWinter/esphomeyaml pull request #7348
Opened 2024-08-24 14:43 UTC by shadow578

# What does this implement/fix?

this PR updates the i2s_audio media_player component.
the ESP-AudioI2S library is updated to the latest version. Currently, a fork of the library is used but this can be changed to the main branch once https://github.com/schreibfaul1/ESP32-audioI2S/pull/816 is merged.

Additional (small-ish) changes:
- the `audio_info` hook used by ESP-AudioI2S is forwarded to `ESP_LOGD` to get some more info on what the library is doing.
- the volume steps are increased to make volume control smoother.
- support for TTS is added (via tts://[lang]:[text] uris).
- a stub for playback of files on SD-Card is added (via file://[path) uris).

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# use custom implementation for i2s_audio media_player
# uses a fork of the latest ESP32-AudioI2C library version
external_components:
  - source: github://shadow578/esphome@update/i2s-audio
    components:
      - i2s_audio
      - media_player
      - i2s_audio/media_player
    refresh: 0s # update on every build

# usage as normal
i2s_audio:
  i2s_lrclk_pin: ${i2s_dac_lrclk_pin}
  i2s_bclk_pin: ${i2s_dac_bclk_pin}

media_player:
  - platform: i2s_audio
    name: ${device_name}.media_player
    id: mediaplayer
    dac_type: external
    i2s_dout_pin: ${i2s_dac_dout_pin}
    i2s_comm_fmt: lsb
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-07 12:55 UTC, shadow578 commented
hope the `sd_card` stuff is ok. if not, it should be easy to remove again.

2024-09-08 00:13 UTC, clydebarrow commented
> hope the `sd_card` stuff is ok. if not, it should be easy to remove again.

It should be split out to a separate PR.

2024-09-09 15:22 UTC, shadow578 commented
> It should be split out to a separate PR.

ok, i removed all the local playback stuff now.

2024-09-11 05:15 UTC, jesserockz requested changes
Please fix the CI issues

2024-09-17 06:31 UTC, shadow578 commented
> Please fix the CI issues

@jesserockz CI should be fixed now

2024-09-30 08:10 UTC, shadow578 commented
hi @jesserockz ,

anything missing on this PR?

2024-10-22 03:40 UTC, jesserockz commented on esphome/components/i2s_audio/media_player/__init__.py
> +    cg.add_library("SPIFFS", None)
I spent ages added the define to avoid pulling all of these in :cry:

2024-10-22 03:46 UTC, jesserockz requested changes

2024-10-22 03:46 UTC, jesserockz commented on esphome/components/i2s_audio/media_player/i2s_audio_media_player.cpp
> +  }
No commented out code in PRs please
```suggestion
```

2024-10-22 08:37 UTC, shadow578 commented on esphome/components/i2s_audio/media_player/i2s_audio_media_player.cpp
> +  }
oops, this must've been when i was testing sd card, but i forgot to remove it. i'll remove it

2024-10-22 09:12 UTC, shadow578 commented
note: on a real-world use-case, this PR increases the flash usage by about 220 KiB and ram usage by about 1 KiB.   

however, this comparison may not be quite fair since the updated library also adds support for the opus and vorbis codecs, as well as replacing the flac decoder from helix to faad2.

still, it should be acceptable in most cases since ESP32-S3 modules typically contain at least 4 MiB of flash, and smaller modules using for example the ESP-C3 struggle with playback anyways.


<details>
<summary>Details</summary>

#### Current State

Supported Decoders:
- AAC
- FLAC (helix)
- MP3

```
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
|-- ArduinoJson @ 6.18.5
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
|-- ESP32-audioI2S @ 2.0.7

RAM:   [==        ]  15.2% (used 49848 bytes from 327680 bytes)
Flash: [=======   ]  69.9% (used 1283185 bytes from 1835008 bytes)
```


#### New State

Supported Decoders:
- AAC
- FLAC (-> faad2)
- MP3
- OPUS (+)
- VORBIS (+)

```
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
|-- ArduinoJson @ 6.18.5
|-- SPI @ 2.0.0
|-- FFat @ 2.0.0
|-- SD @ 2.0.0
|-- SD_MMC @ 2.0.0
|-- SPIFFS @ 2.0.0
|-- WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
|-- ESP32-audioI2S @ 2.0.0+sha.1bc79e5

RAM:   [==        ]  15.6% (used 50968 bytes from 327680 bytes)
Flash: [========  ]  82.2% (used 1508821 bytes from 1835008 bytes)
```
</details>


<details>
<summary>Example use-case</summary>

```yaml
substitutions:
  # name of the device
  device_name: media-example

  # I2S DAC
  i2s_dac_lrclk_pin: GPIO4
  i2s_dac_bclk_pin: GPIO12 # aka TDI
  i2s_dac_dout_pin: GPIO32

  # SPI (SD Card)
  spi_clk_pin: GPIO17
  spi_mosi_pin: GPIO21 # SD: DI
  spi_miso_pin: GPIO16 # SD: DO
  spi_cs_pin: GPIO22

  # Buttons
  btn_a_pin: GPIO23
  btn_b_pin: GPIO18
  btn_plus_pin: GPIO26
  btn_minus_pin: GPIO5
  btn_play_pin: GPIO19

  # Status LED
  status_led_pin: GPIO2 # LED0

  # Tag IDs for buttons causing actions on home assistant
  # these buttons use the 'tag_scanned' action to trigger actions on home assistant
  # 
  # Note:
  # You must allow the device to make service calls for this to work, see https://esphome.io/components/api.html#api-actions
  tag_play: ""  # "PLAY"
  tag_a: ""     # "STOP"
  tag_b: ""     # "LIGHTS"

  # Volume UP / DOWN button step size
  volume_step_size: 0.02f

# use custom implementation for i2s_audio media_player
# uses a fork of the latest ESP32-AudioI2C library version
external_components:
  - source: github://shadow578/esphome@update/i2s-audio
    components:
      - i2s_audio
      - media_player
      - i2s_audio/media_player
    refresh: 0s # update on every build

# config
esphome:
  name: ${device_name}
  friendly_name: "Media Player"
  comment: "ESP32 Media Player Cube"


############
## Basics ##
############
esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino
    version: latest # better support for ESP32-AudioI2C

logger:
api:
  encryption:
    key: !secret api_key
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name} Fallback"
captive_portal:


##########
## Misc ##
##########
web_server:
  include_internal: True

status_led:
  pin: ${status_led_pin}

#psram:

button:
  - platform: restart
    id: btn_restart

text:
  - platform: template
    id: media_uri
    name: "Media URI"
    internal: True
    optimistic: true
    mode: text
    on_value:
      then:
        - media_player.play_media: !lambda "return x;"

sensor:
  - platform: wifi_signal
    id: wifi_signal_db
    internal: True
    update_interval: 60s

  - platform: copy 
    source_id: wifi_signal_db
    id: wifi_signal_percent
    internal: True
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"

  - platform: internal_temperature
    id: internal_temp
    internal: True


##################
## Media Player ##
##################
i2s_audio:
  i2s_lrclk_pin: ${i2s_dac_lrclk_pin}
  i2s_bclk_pin: ${i2s_dac_bclk_pin}

#spi:
#  id: my_spi
#  clk_pin: ${spi_clk_pin}
#  mosi_pin: ${spi_mosi_pin}
#  miso_pin: ${spi_miso_pin}
#
#sd_card:
#  cs_pin: ${spi_cs_pin}
#  spi_id: my_spi
#  id: my_sd_card

media_player:
  - platform: i2s_audio
    name: ${device_name}.media_player
    id: mediaplayer
    dac_type: external
    i2s_dout_pin: ${i2s_dac_dout_pin}
    i2s_comm_fmt: lsb
    mode: mono
#    sd_card_id: my_sd_card


#############
## Buttons ##
#############
binary_sensor:
  # "A" / "STOP"
  - id: "btn_a"
    platform: gpio
    pin:
      number: ${btn_a_pin}
      mode: 
        input: True
        pullup: True
      inverted: True
    on_click: 
      then:
        - logger.log: "A"
        - homeassistant.tag_scanned: ${tag_a}
    on_double_click: 
      then:
        - button.press: btn_restart
  
  # "B" / "LIGHTS"
  - id: "btn_b"
    platform: gpio
    pin:
      number: ${btn_b_pin}
      mode: 
        input: True
        pullup: True
      inverted: True
    on_click: 
      then:
        - logger.log: "B"
        - homeassistant.tag_scanned: ${tag_b}

  # "PLAY"
  - id: "btn_play"
    platform: gpio
    pin:
      number: ${btn_play_pin}
      mode: 
        input: True
        pullup: True
      inverted: True
    on_click: 
      then:
        #- if:
        #    condition:
        #      media_player.is_playing: 
        #    then:
        #      - logger.log: "PLAY stop"
        #      - media_player.stop: 
        #    else:
               - logger.log: "PLAY start"
               - homeassistant.tag_scanned: ${tag_play}

  # "+"
  - id: "btn_plus"
    platform: gpio
    pin:
      number: ${btn_plus_pin}
      mode: 
        input: True
        pullup: True
      inverted: True
    on_click: 
      then:
        - logger.log: "+"
        #- media_player.volume_up:
        - media_player.volume_set:
            !lambda "return constrain(id(mediaplayer).volume + ${volume_step_size}, 0.0f, 1.0f);"

  # "-"
  - id: "btn_minus"
    platform: gpio
    pin:
      number: ${btn_minus_pin}
      mode: 
        input: True
        pullup: True
      inverted: True
    on_click: 
      then:
        - logger.log: "-"
        #- media_player.volume_down: 
        - media_player.volume_set:
            !lambda "return constrain(id(mediaplayer).volume - ${volume_step_size}, 0.0f, 1.0f);"

```

</details>

2024-10-22 09:27 UTC, nielsnl68 commented on esphome/components/i2s_audio/media_player/__init__.py
> +    cg.add_library("SPIFFS", None)
How about moving those lib's to there own component where you can enable them as you need?

And add a link/pointer to the madia player like Jesse did with his file component.

2024-12-16 07:22 UTC, shadow578 commented
@jesserockz 

sorry to bother you, but is there anything missing from this PR?

2025-05-11 12:28 UTC, closed without merging

2025-05-14 11:58 UTC, shadow578 commented
replaced by https://github.com/esphome/ESP32-audioI2S/pull/20