esp32_can: make queue lengths configurable (WIP)
OttoWinter/esphomeyaml pull request #7361
Opened 2024-08-27 20:34 UTC by mrk-its

# What does this implement/fix?

It adds optional parameters `rx_queue_len` and `tx_queue_len` to esp32_can config. esp32 twai driver assumes length 5 by default which is pretty small value and frequently leads to packet loss. This is change is backward compatible: when these parameters are not set, then esp32 twai default will be used.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> **TBD**

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
canbus:
  - platform: esp32_can
    # ...
    tx_queue_len: 128
    rx_queue_len: 128
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs). **TBD**

2024-08-28 04:33 UTC, jesserockz requested changes

2024-08-28 04:33 UTC, jesserockz commented on esphome/components/esp32_can/canbus.py
> +        cg.add(var.set_rx_queue_len(config[CONF_RX_QUEUE_LEN]))
```suggestion
    if (rx_queue_length := config.get(CONF_RX_QUEUE_LEN, None)) is not None:
        cg.add(var.set_rx_queue_len(rx_queue_length))
```

2024-08-28 04:33 UTC, jesserockz commented on esphome/components/esp32_can/esp32_can.h
> +  void set_rx_queue_len(int rx_queue_len) { rx_queue_len_ = optional<int>(rx_queue_len); }
Please use the correct types
```suggestion
  void set_tx_queue_len(uint32_t length) { this->tx_queue_len_ = length; }
  void set_rx_queue_len(uint32_t length) { this->rx_queue_len_ = length; }
```

2024-08-28 04:33 UTC, jesserockz commented on esphome/components/esp32_can/esp32_can.h
> +  optional<int> rx_queue_len_{};
Please use the correct types
```suggestion
  optional<uint32_t> tx_queue_len_{};
  optional<uint32_t> rx_queue_len_{};
```

2024-08-28 09:05 UTC, mrk-its commented on esphome/components/esp32_can/esp32_can.h
> +  void set_rx_queue_len(int rx_queue_len) { rx_queue_len_ = optional<int>(rx_queue_len); }
good catch, thanks!

2024-08-28 22:36 UTC, jesserockz requested changes

2024-08-28 22:36 UTC, jesserockz commented on esphome/components/esp32_can/esp32_can.h
> +  void set_tx_queue_len(uint32_t tx_queue_len) { tx_queue_len_ = tx_queue_len; }
> All uses of class members and member functions should be prefixed with this-> to distinguish them from global functions/variables.
https://esphome.io/guides/contributing#codebase-standards

```suggestion
  void set_tx_queue_len(uint32_t tx_queue_len) { this->tx_queue_len_ = tx_queue_len; }
```

2024-08-28 22:36 UTC, jesserockz commented on esphome/components/esp32_can/esp32_can.h
> +  void set_rx_queue_len(uint32_t rx_queue_len) { rx_queue_len_ = rx_queue_len; }
```suggestion
  void set_rx_queue_len(uint32_t rx_queue_len) { this->rx_queue_len_ = rx_queue_len; }
```

2024-08-29 01:10 UTC, jesserockz approved these changes

2024-08-29 08:39 UTC, mrk-its commented
@jesserockz I created documentation PR already: esphome/esphome-docs#4199, forgot to update the PR desccription :facepalm:

2024-08-29 23:43 UTC, merged