[image] Remove dependency on libmagic
OttoWinter/esphomeyaml pull request #7365
Opened 2024-08-28 03:27 UTC by clydebarrow

# What does this implement/fix?

Use of libmagic is problematic on windows and requires native libraries installed on other host systems. It's only used to detect an SVG file and in any case does so solely by searching for a string. This PR replicates that behaviour without bringing in a heavyweight external library.

Also change `display` from a dependency to an auto-load since image does not depend on having a display configured, only the header file available.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [ ] host

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-08-28 08:15 UTC, nielsnl68 commented
Did you intended to push 2 changes in this PR :D

2024-08-28 08:25 UTC, paravoid requested changes

2024-08-28 08:25 UTC, paravoid commented on esphome/components/image/__init__.py
>      # Local import only to allow "validate_pillow_installed" to run *before* importing it
This comment needs to be moved alongside the import.

2024-08-28 08:25 UTC, paravoid commented on esphome/components/image/__init__.py
> +from PIL import UnidentifiedImageError
Doesn't this need to be a local import, like other pillow imports, for `validate_pillow_installed` etc.?

2024-08-28 08:25 UTC, paravoid commented on esphome/components/image/__init__.py
> +        if "<svg" in str(file_contents):
For what it's worth, libmagic has these rules:
```
0       string          \<?xml\ version=
>14     regex           ['"\ \t]*[0-9.]+['"\ \t]*
>>19    search/4096     \<svg                   SVG Scalable Vector Graphics image
!:mime  image/svg+xml
!:ext   svg

0       string          \<svg                   SVG Scalable Vector Graphics image
!:mime  image/svg+xml
!:ext   svg
```

In other words: `file_contents.startswith("<svg") or ( file_contents.startswith("<?xml version=") and "<svg" in file_contents[:4096]) )`.

Checking for "<svg" in the whole file seems a little broad, but I can't imagine it being _that_ risky - in the worst case `load_svg_image()` fails.

2024-08-28 09:10 UTC, clydebarrow commented
> Did you intended to push 2 changes in this PR

Yes, without those it fails CI.

2024-08-28 10:12 UTC, paravoid commented on esphome/components/image/__init__.py
>      # Local import only to allow "validate_pillow_installed" to run *before* importing it
@clydebarrow I don't think this was actually fixed?

2024-08-28 10:36 UTC, nielsnl68 approved these changes

2024-08-28 11:05 UTC, clydebarrow commented on esphome/components/image/__init__.py
>      # Local import only to allow "validate_pillow_installed" to run *before* importing it
> I don't think this was actually fixed?

It was, but `ruff` un-fixed it.

2024-09-01 14:53 UTC, guillempages commented
@clydebarrow can you add issue 5896 to the "fixes" line in the description? As far as I can see, that issue is exactly what you are trying to fix here

2024-09-01 14:55 UTC, guillempages commented
IMHO the `invert_colors` changes on the tests belong in a separate PR... They are unrelated to this change, but to the one that made it mandatory

2024-09-01 21:35 UTC, clydebarrow commented
> IMHO the `invert_colors` changes on the tests belong in a separate PR

True, but without those (actually now only one) this PR won't pass CI. I'm not going to raise a separate PR to change a single line, sorry Jesse, but I'm drawing a line here :-)

2024-09-02 03:59 UTC, jesserockz commented
> True, but without those (actually now only one) this PR won't pass CI. I'm not going to raise a separate PR to change a single line, sorry Jesse, but I'm drawing a line here :-)

Your PR is adding `invert_colors` to the `spi` config :thinking: 
It already exists on the `display` for this test...

And its not failing becuase the 8266 commmon file is not used anywhere :see_no_evil: 

![2024-09-02_15-56-42](https://github.com/user-attachments/assets/75731b03-a7b4-49bc-a0ae-42d00aa17715)

2024-09-03 00:01 UTC, jesserockz commented
Another alternative is https://pypi.org/project/puremagic/
Especially if other file types are added and need to be identified before some code runs in the future.

2024-09-11 13:07 UTC, kahrendt commented
> Another alternative is https://pypi.org/project/puremagic/ Especially if other file types are added and need to be identified before some code runs in the future.

I like this option! I want to determine the type of an audio file (wav, flac, or mp3), and I'm currently using libmagic for it. Puremagic is pretty much a straight drop in replacement.

2024-10-03 19:55 UTC, guillempages commented
Since there seems to be no movement here, I've implemented the "puremagic" version in #7536.
So probably only one of the two PRs should be merged, since they address the same issue in two different ways

2024-10-07 01:02 UTC, closed without merging