Add Support for PHS32 HeatPump
OttoWinter/esphomeyaml pull request #7378
Opened 2024-08-30 00:25 UTC by mrtntome

# What does this implement/fix?

Add support for the Philco PHS32 HeatPump (through Arduino-HeatpumpIR) on the climate component.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
```yaml

remote_transmitter:
  pin: GPIO23
  carrier_duty_percent: 50%

climate:
  - platform: heatpumpir
    name: "Living Room AC"
    protocol: philco_phs32
    horizontal_default: auto
    vertical_default: auto
    max_temperature: 30
    min_temperature: 18

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-15 20:21 UTC, mrtntome commented
Hi @rob-deutsch, do you have an estimate of when you might be able to check out this PR?

2024-09-16 00:14 UTC, rob-deutsch commented
LGTM, ready to merge

2024-09-16 01:10 UTC, jesserockz requested changes

2024-09-16 01:10 UTC, jesserockz commented on esphome/components/heatpumpir/climate.py
> +    cg.add_library("tonia/HeatpumpIR", "1.0.29")
Please put a link in the PR to the release and source of any of these library version bumps please.

2024-09-26 22:21 UTC, mrtntome commented on esphome/components/heatpumpir/climate.py
> +    cg.add_library("tonia/HeatpumpIR", "1.0.29")
Added links to PR.

2024-11-22 03:23 UTC, mrtntome commented
@jesserockz is this ok to merge?

2025-07-02 03:03 UTC, jesserockz approved these changes

2025-07-02 12:05 UTC, merged