Add enable_pin and reset_display method to RPI_DPI_RGB Display Driver
OttoWinter/esphomeyaml pull request #7383
Opened 2024-09-01 09:46 UTC by lboue

# What does this implement/fix?

- Add enable_pin to RPI_DPI_RGB Display Driver
- Add reset_display method to RPI_DPI_RGB Display Driver

Thanks for the help from @cly_de_barrow.

This is linked to the new composant [CH422G support #7356](https://github.com/esphome/esphome/pull/7356).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** [CH422G support #7356](https://github.com/esphome/esphome/pull/7356)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

[Waveshare ESP32-S3-Touch-LCD-4.3](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3) board

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-01 11:26 UTC, clydebarrow requested changes

2024-09-01 11:26 UTC, clydebarrow commented on esphome/components/rpi_dpi_rgb/rpi_dpi_rgb.h
> +  void set_enable_pin(GPIOPin *enable_pin) { this->reset_pin_ = enable_pin; }
```suggestion
  void set_enable_pin(GPIOPin *enable_pin) { this->enable_pin_ = enable_pin; }
```

2024-09-01 12:32 UTC, lboue commented
Tests with [Waveshare ESP32-S3-Touch-LCD-4.3](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3) board

```
[14:28:51][C][ch422g:037]: CH422G:
[14:28:51][C][ch422g:038]:   Address: 0x24
[14:28:51][C][:103]: RPI_DPI_RGB LCD
[14:28:51][C][rpi_dpi_rgb:104]:   Height: 480
[14:28:51][C][rpi_dpi_rgb:105]:   Width: 800
[14:28:51][C][rpi_dpi_rgb:106]:   DE Pin: GPIO5
[14:28:51][C][rpi_dpi_rgb:108]:   Reset Pin: EXIO3 via CH422G
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 0: GPIO48
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 1: GPIO47
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 2: GPIO21
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 3: GPIO1
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 4: GPIO2
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 5: GPIO42
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 6: GPIO41
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 7: GPIO40
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 8: GPIO14
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 9: GPIO38
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 10: GPIO18
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 11: GPIO17
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 12: GPIO10
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 13: GPIO39
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 14: GPIO0
[14:28:51][C][rpi_dpi_rgb:111]:   Data pin 15: GPIO45
[14:28:51][C][gt911.touchscreen:127]: GT911 Touchscreen:
[14:28:51][C][gt911.touchscreen:128]:   Address: 0x5D
[14:28:51][C][gt911.touchscreen:129]:   Interrupt Pin: GPIO4

```

2024-09-01 13:11 UTC, lboue commented on esphome/components/rpi_dpi_rgb/rpi_dpi_rgb.h
> +  void set_enable_pin(GPIOPin *enable_pin) { this->reset_pin_ = enable_pin; }
Fixed

2024-09-02 02:29 UTC, clydebarrow approved these changes

2024-09-02 02:30 UTC, merged