Enable IPv6 support for BK72xx
OttoWinter/esphomeyaml pull request #7398
Opened 2024-09-02 19:55 UTC by dwmw2

Requires
 LibreTiny-LwIP: https://github.com/libretiny-eu/lwip/pull/2
 LibreTiny: https://github.com/libretiny-eu/libretiny/pull/292

Closes https://github.com/esphome/feature-requests/issues/2853

# What does this implement/fix?

Add IPv6 support for BK72xx

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2853

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [x] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
network:
  enable_ipv6: true
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-03 22:27 UTC, dwmw2 commented
Will also need to pull in the newer AsyncTCP with https://github.com/esphome/AsyncTCP/pull/14 fixed.

2024-09-09 10:23 UTC, dwmw2 commented
No longer waiting for upstream; just for the ESPHome PRs #7409 and #7410.
_(Those could possibly have been included in *this* PR, but I've taken the advice "always separate PRs" literally.)_

2024-09-09 10:25 UTC, dwmw2 commented
@kuba2k2 It looks like the bots dropped 'integration:libretiny' from this, although it still very much is for LibreTiny.

2024-09-09 11:07 UTC, kuba2k2 approved these changes

2024-09-10 00:02 UTC, jesserockz requested changes

2024-09-10 00:02 UTC, jesserockz commented on esphome/components/async_tcp/__init__.py
> +        cg.add_library("esphome/AsyncTCP-esphome", "2.1.4")
Please split this into its own PR, and also needs to be bumped in `platformio.ini`

2024-09-10 06:58 UTC, dwmw2 commented on esphome/components/async_tcp/__init__.py
> +        cg.add_library("esphome/AsyncTCP-esphome", "2.1.4")
Done,. thanks.

2024-09-10 19:44 UTC, jesserockz approved these changes

2024-09-10 22:02 UTC, merged