Support for BL0910 sensor.
OttoWinter/esphomeyaml pull request #7402
Opened 2024-09-03 07:22 UTC by jimmyw

# What does this implement/fix?

Implement support for Belling BL0910 Ten-phase energy measurement chip

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
esphome:
  name: bl0910
  platformio_options:
    board_build.flash_mode: dio

esp32:
  #board: esp32-s3-devkitc-1
  board: lolin32
  #flash_size: 8MB

  framework:
    type: esp-idf
    version: recommended
    #sdkconfig_options:
    #  BOARD_HAS_PSRAM: "y"

wifi:
  ssid: "SSID"
  password: "PASSWORD"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BL0910 Fallback Hotspot"
    password: "rnKi2fnCRGfQ"

captive_portal:

# Enable logging
logger:
  hardware_uart: UART0
  level: INFO
  logs:
    wifi: ERROR

# Enable Home Assistant API
api:

#ota:

web_server:
  port: 80

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

# Example reference values values
# All magic values are calculated from the BL0910 app note:
# https://www.belling.com.cn/media/file_object/bel_product/BL0910/datasheet/BL0910%20APP%20Note_V1.02.pdf

# Example 1: Plugging values from the app note into the formulas:
# BURDEN1 = (5.1 + 5.1)
# BURDEN2 = 100.0
# BURDEN3 = 100.0
# CT_TURNS = 2000.0

# Example 2: https://github.com/jimmyw/energymeter/blob/main/energymeter.pdf
# BURDEN1 = 10.2 ohm(R2 + R3)
# BURDEN2 = 100.0 ohm (R68)
# BURDEN3 = 110.0 kohm (R63 + R64 + R65 + R66 + R67)
# CT_TURNS = 3000.0

# Example 3: https://github.com/JustNoot/10CH-Energy-Meter/blob/main/Schematic_10ch_power_meter_2024-05-11.pdf
# BURDEN1 = 33 ohm (R2)
# BURDEN2 = 120.0 ohm (R33)
# BURDEN3 = 132.0 kohm (R36 + R37 + R38 + R39 + R40 + R41)
# CT_TURNS = 2000.0

# Note, Some CT clamps have additional resistors in series with the burden resistor, so you need to add those to the burden resistor value.

# Calculate the reference values from the app note magic values:
# IREF = (12875.0 * BURDEN1) / (1.097 * CT_TURNS / 1000.0)
# UREF = (13162.0 * BURDEN2) / (1.097 * BURDEN3)
# PREF = (40.4125 * BURDEN1 * BURDEN2 * 1000.0 / CT_TURNS) / (1.097 * 1.097 * BURDEN3)
# EREF = (3600000.0 * 16.0 * PREF) / (4194304.0 * 0.032768 * 16.0)

sensor:
  - platform: bl0910
    update_interval: 500ms
    cs_pin: GPIO21

    # In mode 0, channel 11 is the voltage reference
    voltage_11:
      name: BL0910 RMS Voltage
      uref: 10907.4335
    current_1:
      name: BL0910 Current 1
      iref: 36774.5366
    current_2:
      name: BL0910 Current 2
      iref: 36774.5366
    current_3:
      name: BL0910 Current 3
      iref: 36774.5366
    current_4:
      name: BL0910 Current 4
      iref: 36774.5366
    current_5:
      name: BL0910 Current 5
      iref: 36774.5366
    current_6:
      name: BL0910 Current 6
      iref: 36774.5366
    current_7:
      name: BL0910 Current 7
      iref: 36774.5366
    current_8:
      name: BL0910 Current 8
      iref: 36774.5366
    current_9:
      name: BL0910 Current 9
      iref: 36774.5366
    current_10:
      name: BL0910 Current 10
      iref: 36774.5366

    active_power_1:
      name: BL0910 Active Power 1
      pref: 95.6569
    active_power_2:
      name: BL0910 Active Power 2
      pref: 95.6569
    active_power_3:
      name: BL0910 Active Power 3
      pref: 95.6569
    active_power_4:
      name: BL0910 Active Power 4
      pref: 95.6569
    active_power_5:
      name: BL0910 Active Power 5
      pref: 95.6569
    active_power_6:
      name: BL0910 Active Power 6
      pref: 95.6569
    active_power_7:
      name: BL0910 Active Power 7
      pref: 95.6569
    active_power_8:
      name: BL0910 Active Power 8
      pref: 95.6569
    active_power_9:
      name: BL0910 Active Power 9
      pref: 95.6569
    active_power_10:
      name: BL0910 Active Power 10
      pref: 95.6569

    energy_1:
      name: BL0910 Energy 1
      eref: 2505.5844
    energy_2:
      name: BL0910 Energy 2
      eref: 2505.5844
    energy_3:
      name: BL0910 Energy 3
      eref: 2505.5844
    energy_4:
      name: BL0910 Energy 4
      eref: 2505.5844
    energy_5:
      name: BL0910 Energy 5
      eref: 2505.5844
    energy_6:
      name: BL0910 Energy 6
      eref: 2505.5844
    energy_7:
      name: BL0910 Energy 7
      eref: 2505.5844
    energy_8:
      name: BL0910 Energy 8
      eref: 2505.5844
    energy_9:
      name: BL0910 Energy 9
      eref: 2505.5844
    energy_10:
      name: BL0910 Energy 10
      eref: 2505.5844

    power_factor_1:
      name: BL0910 PowerFactor 1
    power_factor_2:
      name: BL0910 PowerFactor 2
    power_factor_3:
      name: BL0910 PowerFactor 3
    power_factor_4:
      name: BL0910 PowerFactor 4
    power_factor_5:
      name: BL0910 PowerFactor 5
    power_factor_6:
      name: BL0910 PowerFactor 6
    power_factor_7:
      name: BL0910 PowerFactor 7
    power_factor_8:
      name: BL0910 PowerFactor 8
    power_factor_9:
      name: BL0910 PowerFactor 9
    power_factor_10:
      name: BL0910 PowerFactor 10

    frequency:
      name: BL0910 Frequency
    temperature:
      name: BL0910 Temperature

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-03 07:26 UTC, jesserockz commented
Before you get too far on this, please take a look at the recently merged bl0906 component and model this one off that. If it is not too different, perhaps we can merge the two into a single component

2024-09-03 07:28 UTC, jimmyw commented on bl-0910/bl-0910.yml
> +esphome:
This file is just here until im ready with the documentation.

2024-09-03 09:04 UTC, jesserockz requested changes
There is a lot that will fail CI here. Please make sure to go over all of the [codebase standards](https://esphome.io/guides/contributing#codebase-standards) which handle a lot of them and helps make a PR take up less precious time of reviewers.

Once CI is passing fully and the PR is marked as ready, someone will take another look.

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.cpp
> +  return (((int8_t) packet[2]) << 16) | (packet[3] << 8) | packet[4];
```suggestion
  return encode_uint24(packet[2], packet[3], packet[4]);
```

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.cpp
> +#include "esphome/core/log.h"
```suggestion
#include "esphome/core/log.h"
#include "esphome/core/helpers.h"
```

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.cpp
> +static const uint8_t BL0910_READ_COMMAND = 0x82;
Please move all of these consts into a `constant.h` file

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.cpp
> +  checksum ^= 0xFF;
```suggestion
  // Verify checksum
  uint8_t checksum = checksum_calc(packet);
```

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.cpp
> +int8_t BL0910::checksum_calc(uint8_t *data) {
```suggestion
constexpr uint8_t checksum_calc(uint8_t *data) {
```

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.h
> +  int8_t checksum_calc(uint8_t *data);
```suggestion
```

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.cpp
> +  static float freq = 50.0;
Component should not have static variables as they will conflict if multiple instances are set up.

Use a member variable for the current channel being read, and do the actual read in `loop`, only resetting the current channel in `update`. 

https://github.com/esphome/esphome/blob/565835cb59c284c886e29600d605c6053bb6ceb3/esphome/components/bl0906/bl0906.cpp#L88

https://github.com/esphome/esphome/blob/565835cb59c284c886e29600d605c6053bb6ceb3/esphome/components/bl0906/bl0906.cpp#L20

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.cpp
> +float BL0910::getVoltage(uint8_t channel) {
lower_snake_case
```suggestion
float BL0910::get_voltage(uint8_t channel) {
```

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.cpp
> +      LOG_SENSOR("", buf, voltage_sensor[i]);
```suggestion
      std::string label = str_sprintf("Voltage %d", i + 1);
      LOG_SENSOR("", label.c_str(), this->voltage_sensor[i]);
```

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.h
> +  sensor::Sensor *voltage_sensor[NUM_CHANNELS] = {};
lower_snake_case_with_trailing_underscore_
```suggestion
  sensor::Sensor *voltage_sensor_[NUM_CHANNELS] = {};
```

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.h
> + private:
Private is not really needed, protected is just fine
```suggestion
```

2024-09-03 09:04 UTC, jesserockz commented on esphome/components/bl0910/bl0910.h
> +  }
```suggestion
  void set_voltage_sensor(sensor::Sensor *voltage_sensor, uint8_t index, float uref) {
    this->voltage_sensors_[index - 1] = voltage_sensor;
    this->urefs[index - 1] = uref;
  }
```

2024-09-03 12:43 UTC, dwmw2 commented on esphome/components/bl0910/sensor.py
> +            cg.add(var.set_voltage_sensor(sens, i, voltage_config.get("uref")))
For the BL0942 in https://github.com/esphome/esphome/pull/7299 and the associated docs PR I've called these `voltage_reference`, `current_reference`, `power_reference` and `energy_reference`. Can we use the same names for consistency?

2024-09-08 20:56 UTC, jimmyw commented on esphome/components/bl0910/bl0910.cpp
> +  checksum ^= 0xFF;
Did this misstake my self at first, but problem is that the first two bytes have beens swapped out for zeros doing SPI tranfer, so the checksum did not match..

2024-09-08 20:58 UTC, jimmyw commented on esphome/components/bl0910/bl0910.cpp
> +int8_t BL0910::checksum_calc(uint8_t *data) {
Did not manage to fit it into a constexpr, as the error: body of 'constexpr' function 'constexpr uint8_t esphome::bl0910::checksum_calc(uint8_t*)' not a return-statement.

Can make it a static function outside the class if thats better..

2024-09-09 04:03 UTC, jesserockz commented
Please see the big red warning box on the [contributing guide](https://esphome.io/guides/contributing#your-local-copy-of-dev)

2024-09-09 07:41 UTC, jimmyw commented
> Please see the big red warning box on the [contributing guide](https://esphome.io/guides/contributing#your-local-copy-of-dev)

Sorry.

I`m learning!

2024-09-09 07:56 UTC, jimmyw commented
@jesserockz 
After moving the spi stuff to loop (Or might have been the rebase) i started to se "Task watchdog got triggered"

Strangely  it seems that both cores are running IDLE tasks, so im unsure how it can be stuck. 

Do you have any idea?

```
[09:52:28]E (202979) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
[09:52:28]E (202979) task_wdt:  - loopTask (CPU 1)
[09:52:28]E (202979) task_wdt: Tasks currently running:
[09:52:28]E (202979) task_wdt: CPU 0: IDLE0
[09:52:28]E (202979) task_wdt: CPU 1: IDLE1
[09:52:28]E (202979) task_wdt: Aborting.
[09:52:28]
[09:52:28]abort() was called at PC 0x400ef5c9 on core 0
[09:52:28]
[09:52:28]
[09:52:28]Backtrace: 0x40083046:0x3ffb08a0 0x40089f39:0x3ffb08c0 0x400907da:0x3ffb08e0 0x400ef5c9:0x3ffb0950 0x400839c9:0x3ffb0970 0x4015506b:0x3ffba2c0 0x400efc3e:0x3ffba2e0 0x4008b310:0x3ffba300
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x40083046: panic_abort at /home/jimmy/.platformio/packages/framework-espidf/components/esp_system/panic.c:408
WARNING Decoded 0x40089f39: esp_system_abort at /home/jimmy/.platformio/packages/framework-espidf/components/esp_system/esp_system.c:137
WARNING Decoded 0x400907da: abort at /home/jimmy/.platformio/packages/framework-espidf/components/newlib/abort.c:46
WARNING Decoded 0x400ef5c9: task_wdt_isr at /home/jimmy/.platformio/packages/framework-espidf/components/esp_system/task_wdt.c:176 (discriminator 3)
WARNING Decoded 0x400839c9: _xt_lowint1 at /home/jimmy/.platformio/packages/framework-espidf/components/freertos/port/xtensa/xtensa_vectors.S:1118
WARNING Decoded 0x4015506b: cpu_ll_waiti at /home/jimmy/.platformio/packages/framework-espidf/components/hal/esp32/include/hal/cpu_ll.h:183
 (inlined by) esp_pm_impl_waiti at /home/jimmy/.platformio/packages/framework-espidf/components/esp_pm/pm_impl.c:853
WARNING Decoded 0x400efc3e: esp_vApplicationIdleHook at /home/jimmy/.platformio/packages/framework-espidf/components/esp_system/freertos_hooks.c:63
WARNING Decoded 0x4008b310: prvIdleTask at /home/jimmy/.platformio/packages/framework-espidf/components/freertos/tasks.c:4099
```

2024-09-11 22:40 UTC, jimmyw commented
@jesserockz 
Did find some time to look into this now, and i got a stacktrace from loopTask when WDT times out.
Seems that the issue is not related to this component, else than it tries to log a little.

```
#0  0x4008b254 in xQueueSemaphoreTake (xQueue=0x3ffcdfc8, xTicksToWait=<optimized out>) at /home/jimmy/.platformio/packages/framework-espidf/components/freertos/queue.c:1687
#1  0x401017e5 in sys_arch_sem_wait (sem=0x3ffcd650, timeout=0) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/port/esp32/freertos/sys_arch.c:184
#2  0x400f92ea in tcpip_send_msg_wait_sem (fn=<optimized out>, apimsg=0x3ffc0cb0, sem=0x3ffcd650) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/api/tcpip.c:462
#3  0x4010266c in netconn_apimsg (fn=0x40103a34 <lwip_netconn_do_write>, apimsg=0x3ffc0cb0) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/api/api_lib.c:136
#4  0x401028a5 in netconn_write_vectors_partly (conn=<optimized out>, vectors=0x3ffc0d00, vectorcnt=<optimized out>, apiflags=1 '\001', bytes_written=0x3ffc0d30) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/api/api_lib.c:1077
#5  0x401028f4 in netconn_write_partly (conn=0x3ffd250c, dataptr=0x3ffd27a4, size=84, apiflags=1 '\001', bytes_written=0x3ffc0d30) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/api/api_lib.c:993
#6  0x400f89de in lwip_send (s=<optimized out>, data=0x3ffd27a4, size=84, flags=<optimized out>) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/api/sockets.c:1472
#7  0x400f0264 in send (flags=0, size=84, dataptr=0x3ffd27a4, s=60) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/include/lwip/sockets.h:650
#8  httpd_default_send (hd=0x3ffce268, sockfd=60, buf=0x3ffd27a4 <error: Cannot access memory at address 0x3ffd27a4>, buf_len=84, flags=0) at /home/jimmy/.platformio/packages/framework-espidf/components/esp_http_server/src/httpd_txrx.c:582
#9  0x400f02ba in httpd_socket_send (hd=0x3ffce268, sockfd=60, buf=0x3ffd27a4 <error: Cannot access memory at address 0x3ffd27a4>, buf_len=84, flags=0) at /home/jimmy/.platformio/packages/framework-espidf/components/esp_http_server/src/httpd_txrx.c:612
#10 0x400ddeca in esphome::web_server_idf::AsyncEventSourceResponse::send (this=0x3ffd02bc, message=<optimized out>, event=<optimized out>, id=<optimized out>, reconnect=0) at /home/jimmy/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:2290
#11 0x400ddef8 in esphome::web_server_idf::AsyncEventSource::send (this=0x3ffbb994, message=0x3ffba960 <error: Cannot access memory at address 0x3ffba960>, event=0x3f405c0f "log", id=78229, reconnect=0) at src/esphome/components/web_server_idf/web_server_idf.cpp:288
#12 0x400dc635 in <lambda(int, char const*, char const*)>::operator() (__closure=<optimized out>, level=<optimized out>, tag=<optimized out>, message=0x3ffba960 <error: Cannot access memory at address 0x3ffba960>) at src/esphome/components/web_server/web_server.cpp:114
#13 std::_Function_handler<void(int, char const*, char const*), esphome::web_server::WebServer::setup()::<lambda(int, char const*, char const*)> >::_M_invoke(const std::_Any_data &, int &&, const char *&&, const char *&&) (__functor=..., __args#0=<optimized out>, __args#1=@0x3ffc0e34: 0x3f403c68 "bl0910", __args#2=@0x3ffc0e30: 0x3ffba960 <error: Cannot access memory at address 0x3ffba960>) at /home/jimmy/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/std_function.h:297
#14 0x400da2a8 in std::function<void (int, char const*, char const*)>::operator()(int, char const*, char const*) const (__args#2=<optimized out>, __args#1=<optimized out>, __args#0=<optimized out>, this=0x3ffd203c) at /home/jimmy/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/std_function.h:687
#15 esphome::CallbackManager<void (int, char const*, char const*)>::call(int, char const*, char const*) (args#2=0x3ffba960 <error: Cannot access memory at address 0x3ffba960>, args#1=0x3f403c68 "bl0910", args#0=3, this=<optimized out>) at src/esphome/core/helpers.h:488
#16 esphome::logger::Logger::log_message_ (this=<optimized out>, level=3, tag=0x3f403c68 "bl0910", offset=<optimized out>) at src/esphome/components/logger/logger.cpp:140
#17 0x400da35d in esphome::logger::Logger::log_vprintf_ (this=0x3ffba914, level=3, tag=0x3f403c68 "bl0910", line=125, format=0x3f403db5 "BL0910 loop end in %d ms", args=...) at src/esphome/components/logger/logger.cpp:70
#18 0x400e2bfc in esphome::esp_log_vprintf_ (level=3, tag=0x3f403c68 "bl0910", line=125, format=0x3f403db5 "BL0910 loop end in %d ms", args=...) at src/esphome/core/log.cpp:32
#19 0x400e2c29 in esphome::esp_log_printf_ (level=3, tag=0x3f403c68 "bl0910", line=125, format=0x3f403db5 "BL0910 loop end in %d ms") at src/esphome/core/log.cpp:14
#20 0x400d7bed in esphome::bl0910::BL0910::loop (this=0x3ffc19cc) at src/esphome/components/bl0910/bl0910.cpp:125
#21 esphome::bl0910::BL0910::loop (this=0x3ffc19cc) at src/esphome/components/bl0910/bl0910.cpp:94
#22 0x401581d0 in esphome::Component::call_loop (this=0x3ffc19cc) at src/esphome/core/component.cpp:77
#23 0x4015826c in esphome::Component::call (this=0x3ffc19cc) at src/esphome/core/component.cpp:104
#24 0x400e136e in esphome::Application::loop (this=0x3ffb4c90 <esphome::App>) at src/esphome/core/application.cpp:76
#25 0x400e3591 in loop () at src/main.cpp:835
#26 0x400d8955 in esphome::loop_task (pv_params=0x0) at src/esphome/components/esp32/core.cpp:69
```

2024-09-11 22:44 UTC, jimmyw commented
@jesserockz 
Another one that are similar issue:
```
#0  0x4008b254 in xQueueSemaphoreTake (xQueue=0x3ffcdf28, xTicksToWait=<optimized out>) at /home/jimmy/.platformio/packages/framework-espidf/components/freertos/queue.c:1687
#1  0x40100389 in sys_arch_sem_wait (sem=0x3ffcd660, timeout=0) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/port/esp32/freertos/sys_arch.c:184
#2  0x400f7ea6 in tcpip_send_msg_wait_sem (fn=<optimized out>, apimsg=0x3ffc0cc0, sem=0x3ffcd660) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/api/tcpip.c:462
#3  0x40101210 in netconn_apimsg (fn=0x401025d8 <lwip_netconn_do_write>, apimsg=0x3ffc0cc0) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/api/api_lib.c:136
#4  0x40101449 in netconn_write_vectors_partly (conn=<optimized out>, vectors=0x3ffc0d10, vectorcnt=<optimized out>, apiflags=1 '\001', bytes_written=0x3ffc0d40) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/api/api_lib.c:1077
#5  0x40101498 in netconn_write_partly (conn=0x3ffd20b4, dataptr=0x3ffd4e64, size=86, apiflags=1 '\001', bytes_written=0x3ffc0d40) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/api/api_lib.c:993
#6  0x400f759a in lwip_send (s=<optimized out>, data=0x3ffd4e64, size=86, flags=<optimized out>) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/api/sockets.c:1472
#7  0x400eef8c in send (flags=0, size=86, dataptr=0x3ffd4e64, s=60) at /home/jimmy/.platformio/packages/framework-espidf/components/lwip/lwip/src/include/lwip/sockets.h:650
#8  httpd_default_send (hd=0x3ffce1bc, sockfd=60, buf=0x3ffd4e64 <error: Cannot access memory at address 0x3ffd4e64>, buf_len=86, flags=0) at /home/jimmy/.platformio/packages/framework-espidf/components/esp_http_server/src/httpd_txrx.c:582
#9  0x400eefe2 in httpd_socket_send (hd=0x3ffce1bc, sockfd=60, buf=0x3ffd4e64 <error: Cannot access memory at address 0x3ffd4e64>, buf_len=86, flags=0) at /home/jimmy/.platformio/packages/framework-espidf/components/esp_http_server/src/httpd_txrx.c:612
#10 0x400dd01a in esphome::web_server_idf::AsyncEventSourceResponse::send (this=0x3ffd2104, message=<optimized out>, event=<optimized out>, id=<optimized out>, reconnect=0) at /home/jimmy/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:2290
#11 0x400dd048 in esphome::web_server_idf::AsyncEventSource::send (this=0x3ffbb97c, message=0x3ffd289c <error: Cannot access memory at address 0x3ffd289c>, event=0x3f412d1b "state", id=0, reconnect=0) at src/esphome/components/web_server_idf/web_server_idf.cpp:288
#12 0x400dbc19 in esphome::web_server::WebServer::on_sensor_update (state=0, obj=0x3ffc1d3c, this=0x3ffbb960) at src/esphome/components/web_server/web_server.cpp:216
#13 esphome::web_server::WebServer::on_sensor_update (this=0x3ffbb960, obj=0x3ffc1d3c, state=0) at src/esphome/components/web_server/web_server.cpp:213
#14 0x40156f08 in <lambda(float)>::operator() (state=<optimized out>, __closure=0x3ffd1e50) at src/esphome/core/controller.cpp:29
#15 std::_Function_handler<void(float), esphome::Controller::setup_controller(bool)::<lambda(float)> >::_M_invoke(const std::_Any_data &, float &&) (__functor=..., __args#0=@0x3ffc0e80: 0) at /home/jimmy/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/std_function.h:297
#16 0x400da90c in std::function<void (float)>::operator()(float) const (this=0x3ffd1e50, __args#0=<optimized out>) at /home/jimmy/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/std_function.h:687
#17 0x400da930 in esphome::CallbackManager<void (float)>::call(float) (args#0=<optimized out>, this=<optimized out>) at src/esphome/core/helpers.h:488
#18 esphome::sensor::Sensor::internal_send_state_to_frontend (this=<optimized out>, state=<optimized out>) at src/esphome/components/sensor/sensor.cpp:95
#19 0x400da971 in esphome::sensor::Sensor::publish_state (this=0x3ffc1d3c, state=<optimized out>) at src/esphome/components/sensor/sensor.cpp:46
#20 0x400d7139 in esphome::bl0910::BL0910::loop (this=0x3ffc19dc) at src/esphome/components/bl0910/bl0910.cpp:103
#21 0x40156df0 in esphome::Component::call_loop (this=0x3ffc19dc) at src/esphome/core/component.cpp:77
#22 0x40156e8c in esphome::Component::call (this=0x3ffc19dc) at src/esphome/core/component.cpp:104
#23 0x400e00d2 in esphome::Application::loop (this=0x3ffb4c90 <esphome::App>) at src/esphome/core/application.cpp:76
#24 0x400e22e5 in loop () at src/main.cpp:835
#25 0x400d7e81 in esphome::loop_task (pv_params=0x0) at src/esphome/components/esp32/core.cpp:69
```

2024-09-12 07:06 UTC, jimmyw commented
I confirmed now, running all night that the watchdog timeout was related to the webserver and not to my component.

Will change this to "Ready for review", as i have no open issues.

2024-09-25 11:47 UTC, jimmyw commented
Force pushed the branch back to the original tree to see if github understands that, but seemed not to help.

2024-09-27 02:00 UTC, jesserockz requested changes
Please restructure the config schema so that it is like this:
```yaml
sensor:
  - platform: bl0910
    channel_1:
      voltage: ...
      current: ...
    channel_2:
      voltage: ...
    ...
```

If you need help with that, please see how the bl0906 component does it.

2025-10-12 00:50 UTC, closed without merging