MCP3204 differential mode support
OttoWinter/esphomeyaml pull request #7436
Opened 2024-09-12 16:19 UTC by markodraca

# What does this implement/fix?

Support for MCP3204 differential mode measurement

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [ X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sensor:
      - platform: mcp3204             # Attached to pin 0 of the MCP3204.
        id: solar_voltage
        number: 0                     # MCP3204 pin number
        diff_mode: true               # MCP3204 differential mode measurement

```

## Checklist:
  - [ X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2025-10-06 12:04 UTC, rsumner approved these changes

2025-10-21 02:59 UTC, swoboda1337 requested changes
Needs a docs PR and add the new field to the tests.

2025-10-21 13:18 UTC, swoboda1337 requested changes
Need to update the docs and add the new field to the tests.

2025-11-18 00:38 UTC, swoboda1337 commented
Still need to add the new field here: esphome/tests/components/mcp3204/common.yaml and that will clear the needs tests flag

2025-11-19 09:05 UTC, markodraca commented
added tests to tests\components\mcp3204\common.yaml

2025-11-21 18:59 UTC, swoboda1337 submitted a review, later dismissed

2025-11-21 19:10 UTC, swoboda1337 submitted a review, later dismissed

2025-11-21 19:11 UTC, swoboda1337 approved these changes

2025-11-21 19:12 UTC, swoboda1337 commented
Ok I did some cleanup. Can you test it again? Looks good. Thanks!

2025-11-21 19:45 UTC, markodraca commented
Looks fine but I dont have an access to the board anymore, it has been a year.

2025-11-21 19:50 UTC, swoboda1337 commented
> Looks fine but I dont have an access to the board anymore, it has been a year.

It does look correct. I will merge.

2025-11-21 19:50 UTC, merged

2025-11-21 19:53 UTC, markodraca commented
In a first try, damn Im good.