feat: add swing change
OttoWinter/esphomeyaml pull request #7444
Opened 2024-09-13 04:58 UTC by magicbear

# What does this implement/fix?

Add swing change for daikin_arc climate

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml

remote_transmitter:
  id: tsvr
  carrier_duty_percent: 50%
  pin:
    number: 26
    inverted: false
    mode:
      output: true

remote_receiver:
  id: rcvr
  pin:
    number: 27
    inverted: true
    mode:
      input: true
      pullup: true
  tolerance: 40%

climate:
  - platform: daikin_arc
    name: Climate
    receiver_id: rcvr
    transmitter_id: tsvr

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-16 01:57 UTC, jesserockz requested changes

2024-09-16 01:57 UTC, jesserockz commented on esphome/components/daikin_arc/daikin_arc.cpp
> +  // a2 c3 03 80 21: 時刻設定
I only just noticed that the other comments in this file are Japanese. Could you please open another PR and convert them to English. 

よろしく :v: :pray:

2024-09-16 01:57 UTC, jesserockz commented on esphome/components/daikin_arc/daikin_arc.cpp
> +  transmit_flag_ = 0;
Can you explain the meaning of this `transmit_flag_`?

2024-09-17 17:52 UTC, magicbear commented on esphome/components/daikin_arc/daikin_arc.cpp
> +  transmit_flag_ = 0;
It is the flag that control the AC controller to tell which paramerter is changed (in japan model will be have a japanese voice said whats changed) , and this flag is need to be send at transmit_state.

2024-09-17 17:54 UTC, magicbear commented on esphome/components/daikin_arc/daikin_arc.cpp
> +  // a2 c3 03 80 21: 時刻設定
Because currently the home assistant have not support for timer (or is unnecessary), so this comment is only a note for reverse engineering.

2025-10-12 00:49 UTC, closed without merging