Support inkplate 5 and 5 V2
OttoWinter/esphomeyaml pull request #7448
Opened 2024-09-15 19:27 UTC by DavidSichau

Provide support for inkplate 5 and 5 V2

# What does this implement/fix?

Support inkplate 5 and 5V2 displays,

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2884

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32 Inkplate 5

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

2024-09-15 23:08 UTC, jesserockz requested changes
Don't forget to add the models to the config options
https://github.com/esphome/esphome/blob/f652cd3851d17a4434876ab546021c6f698cb47f/esphome/components/inkplate6/display.py#L51-L56

2024-09-15 23:08 UTC, jesserockz commented on esphome/components/inkplate6/inkplate.h
> +};
```suggestion
                                             {0, 0, 0, 0, 0, 0, 0, 0, 0}}};
```

2024-09-16 07:44 UTC, DavidSichau commented
@jesserockz  I added the requested changes. Thanks for the review.

2024-09-17 23:50 UTC, jesserockz approved these changes

2024-09-24 07:21 UTC, DavidSichau commented
Doc was added: https://github.com/esphome/esphome-docs/pull/4276

2024-09-25 00:50 UTC, merged