Add TC74 temperature sensor
OttoWinter/esphomeyaml pull request #7460
Opened 2024-09-17 01:23 UTC by sethgirvan

# What does this implement/fix?
Add support for the [TC74 temperature sensor](https://www.microchip.com/en-us/product/tc74).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: tc74
    name: "Living Room Temperature"
    update_interval: 60s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-02 01:05 UTC, jesserockz requested changes

2024-10-02 01:05 UTC, jesserockz commented on esphome/components/tc74/sensor.py
> +
We try to keep the codebase free of extra stuff like this.

This is what the documentation repo is for.

```suggestion
```

2024-10-02 01:05 UTC, jesserockz commented on esphome/components/tc74/tc74.cpp
> +  this->set_timeout("temperature", 2, [this]() { this->read_temperature_(); });
I don't see the point in delaying the actual read by 2ms here (which will actually be more like 16ms as it wont execute until the next `loop` comes around and runs the next scheduled tasks).
```suggestion
  this->read_temperature_();
```

2024-10-02 01:05 UTC, jesserockz commented on esphome/components/tc74/tc74.cpp
> +}
```suggestion
void TC74Component::dump_config() {
  LOG_SENSOR("", "TC74", this);
  LOG_I2C_DEVICE(this);
  if (this->is_failed()) {
    ESP_LOGE(TAG, "Connection with TC74 failed!");
  }
  LOG_UPDATE_INTERVAL(this);

}
```

2024-10-15 03:05 UTC, jesserockz approved these changes

2024-10-15 03:39 UTC, jesserockz commented
In future, please dont force push a branch after a review unless asked to by the reviewer. It messes with the review state on GH

2024-10-15 20:40 UTC, sethgirvan commented
> In future, please dont force push a branch after a review unless asked to by the reviewer. It messes with the review state on GH

Okay will do! Had to make lint fixes to suggestion, will make separate commits in the future!

2024-10-16 03:24 UTC, merged