[esp32_improv] Add triggers for various states
OttoWinter/esphomeyaml pull request #7461
Opened 2024-09-17 02:59 UTC by kbx81

# What does this implement/fix?

SSIA

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-17 12:49 UTC, nielsnl68 requested changes
I nice addition to the improv compronent, just on request to drop the **USE_ESP32_IMPROV_STATE_CALLBACK** define in favor of a global **USE_ESP32_IMPROV**

2024-09-17 12:49 UTC, nielsnl68 commented on esphome/components/esp32_improv/esp32_improv_component.cpp
> +#endif
```suggestion
      this->state_callback_.call(this->state_);
```

2024-09-17 12:49 UTC, nielsnl68 commented on esphome/components/esp32_improv/esp32_improv_component.cpp
> +#endif
```suggestion
  this->state_callback_.call(state);
```

2024-09-17 12:49 UTC, nielsnl68 commented on esphome/components/esp32_improv/esp32_improv_component.h
> +#endif
```suggestion
  void add_on_state_callback(std::function<void(improv::State, improv::Error)> &&callback) {
    this->state_callback_.add(std::move(callback));
  }
```
Optional Allow please sending the error state to the events as well.

2024-09-17 12:49 UTC, nielsnl68 commented on esphome/components/esp32_improv/esp32_improv_component.h
> +#endif
```suggestion
  CallbackManager<void(improv::State)> state_callback_{};
```

2024-09-17 12:49 UTC, nielsnl68 commented on esphome/components/esp32_improv/esp32_improv_component.h
> +
```suggestion
   improv::State get_improv_error_state() const { return this->error_; }
   
```
Allow external access to the latest error state.

2024-09-17 12:49 UTC, nielsnl68 commented on esphome/components/esp32_improv/__init__.py
> +        cg.add_define("USE_ESP32_IMPROV_STATE_CALLBACK")
```suggestion
      cg.add_define("USE_ESP32_IMPROV")
```

2024-09-17 12:49 UTC, nielsnl68 commented on esphome/components/esp32_improv/esp32_improv_component.h
> +#endif
```suggestion
#include "esphome/core/automation.h"
```

2024-09-18 01:17 UTC, kbx81 commented
> I nice addition to the improv compronent, just on request to drop the **USE_ESP32_IMPROV_STATE_CALLBACK** define in favor of a global **USE_ESP32_IMPROV**

@nielsnl68 I talked with Jesse about this and we will keep the `#defines`. The BT stack itself already significantly increases the size of the binary and we want to exclude code where it's not in use (which, for the new code in this PR, will be everywhere, at least initially).

If a specific component requires the callbacks, it can simply `cg.add_define()` [as the `esp32_ble_tracker` does for OTA](https://github.com/esphome/esphome/blob/5a3e1d57921a839a5f383350e45cdd3304efa311/esphome/components/esp32_ble_tracker/__init__.py#L275).

2024-09-23 04:54 UTC, jesserockz approved these changes

2024-09-23 04:54 UTC, merged