WIP: Mopeka Pro Check improvement to allow user to configure the sensor reporting for lower quality readings
OttoWinter/esphomeyaml pull request #7475
Opened 2024-09-19 17:53 UTC by spbrogan

# What does this implement/fix?

Originally this integration made a choice to not reporting level or distance sensors when the read quality was below a 2 (scale of 0-3, 3 being highest).  Many users have reported that despite moving their sensor, cleaning their tank, and adding grease their device reports lower quality readings.  They also report that these measurements are still accurate enough to be useful for their use cases.  Additionally, the integration zeroed the sensors when the reading quality was bad.  Both of these conditions made it harder to use their device in automations or for alerts.  This PR provides more configuration options to the end user while still maintaining a default that is similar.  

- Remove hardcoded zero and no report quality levels.  
- Never zero the sensor level or distance. (minor change in behavior but still not considered "breaking change")
- Provide new configuration option for min reported quality level and only report level and distance sensors when quality is greater than or equal to min.  
- Create new diagnostic sensor that reports the quality level so that additional filtering could be done if desired.
- Create new diagnostic sensor for the count of contiguous bad readings so there is visibility into the performance of the sensor. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>  

Docs update will be needed. 

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
- platform: mopeka_pro_check
    mac_address: AA:BB:CC:DD:EE:FF
    tank_type: 20LB_V
    temperature:
        name: "Propane test2 temp"
    level:
        name: "Propane test2 level"
    distance:
        name: "Propane test2 distance"
    battery_level:
        name: "Propane test2 battery level"
   # new options below here
    signal_strength:
        name: "propane test2 read quality"
    ignored_reads:
        name: "propane test2 ignored reads"
    minimum_signal_quality_to_report: 1
    
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-01 03:43 UTC, spbrogan commented
@jesserockz  - Any chance you can review this?  This is reworked from a PR from last year https://github.com/esphome/esphome/pull/4928.  It is implemented to match what we discussed on that PR.  This resolves a pretty common complaint of this integration so I think it would be great to get it checked in.  Thanks

2024-10-01 04:40 UTC, jesserockz requested changes

2024-10-01 04:40 UTC, jesserockz commented on esphome/components/mopeka_pro_check/sensor.py
> +                device_class=DEVICE_CLASS_SIGNAL_STRENGTH,
This device class is for measurements with dB / dBm units only
```suggestion
```

2024-10-01 04:40 UTC, jesserockz commented on esphome/components/mopeka_pro_check/sensor.py
> +            cv.Optional(CONF_SIGNAL_STRENGTH): sensor.sensor_schema(
Since this is labelled as signal quality everywhere, the config name should match
```suggestion
            cv.Optional(CONF_SIGNAL_QUALITY): sensor.sensor_schema(
```

2024-10-01 04:40 UTC, jesserockz commented on esphome/components/mopeka_pro_check/sensor.py
> +        )
```suggestion
    if (minimum_signal_quality := config.get(CONF_MINIMUM_SIGNAL_QUALITY_TO_REPORT, None)) is not None:
        cg.add(
            var.set_min_signal_quality(minimum_signal_quality)
        )
```

2024-10-01 04:40 UTC, jesserockz commented on esphome/components/mopeka_pro_check/mopeka_pro_check.h
> +  SensorReadQuality min_signal_quality_to_report_ = QUALITY_MED;
```suggestion
  SensorReadQuality min_signal_quality_ = QUALITY_MED;
```

2024-10-01 04:40 UTC, jesserockz commented on esphome/components/mopeka_pro_check/mopeka_pro_check.h
> +  void set_min_signal_quality_to_report(int min);
```suggestion
  void set_min_signal_quality(SensorReadQuality min);
```

2024-10-01 04:40 UTC, jesserockz commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +  SensorReadQuality value = static_cast<SensorReadQuality>(min);
```suggestion
void MopekaProCheck::set_min_signal_quality(SensorReadQuality min) {
```

2024-10-01 04:40 UTC, jesserockz commented on esphome/components/mopeka_pro_check/sensor.py
> +            ),
Probably doesn't need `to_report`
Also should be an enum
```suggestion
            cv.Optional(CONF_MINIMUM_SIGNAL_QUALITY, default="MEDIUM"): cv.enum(SIGNAL_QUALITIES, upper=True),
```

2024-10-01 05:37 UTC, spbrogan commented on esphome/components/mopeka_pro_check/mopeka_pro_check.h
> +  void set_min_signal_quality_to_report(int min);
This change doesn't work.  The python code generation still converts the enum to an int and then calls the this C code with an int.  

```
src/main.cpp:330:62: error: invalid conversion from 'int' to 'esphome::mopeka_pro_check::SensorReadQuality' [-fpermissive]
   mopeka_pro_check_mopekaprocheck_id->set_min_signal_quality(1);
                                                              ^
In file included from src/esphome.h:37,
                 from src/main.cpp:3:
src/esphome\components\mopeka_pro_check\mopeka_pro_check.h:38:49: note:   initializing argument 1 of 'void esphome::mopeka_pro_check::MopekaProCheck::set_min_signal_quality(esphome::mopeka_pro_check::SensorReadQuality)'
   void set_min_signal_quality(SensorReadQuality min); 
```

2024-10-01 05:48 UTC, spbrogan commented on esphome/components/mopeka_pro_check/mopeka_pro_check.cpp
> +  SensorReadQuality value = static_cast<SensorReadQuality>(min);
Change didn't work.  See comment on header file requested change.

2024-10-01 19:01 UTC, jesserockz commented on esphome/components/mopeka_pro_check/mopeka_pro_check.h
> +  void set_min_signal_quality_to_report(int min);
Yes, you need to make more changes than what was suggestion to accommodate this change. I can only suggest so much on GH, it doesnt let me make suggestions in other places

2024-10-01 19:04 UTC, jesserockz commented on esphome/components/mopeka_pro_check/sensor.py
> +SIGNAL_QUALITIES = {"ZERO": 0, "LOW": 1, "MEDIUM": 2, "HIGH": 3}
You will need to also move this down lower in the file (below at least `mopeka_pro_check_ns`)
```suggestion
SensorReadQuality = mopeka_pro_check_ns.enum("SensorReadQuality")

SIGNAL_QUALITIES = {
    "ZERO": SensorReadQuality.QUALITY_ZERO,
    "LOW": SensorReadQuality.QUALITY_LOW,
    "MEDIUM": SensorReadQuality.QUALITY_MEDIUM,
    "HIGH": SensorReadQuality.QUALITY_HIGH,
}
```

2024-10-02 14:07 UTC, phurth commented
Looking forward to this change to improve the usability of the integration.

2024-10-03 15:11 UTC, rperciaccante commented
I am looking forward to this as well!

2024-10-04 03:41 UTC, spbrogan commented
@jesserockz - I was able to pass the enum type through.  Thanks for the feedback.

2024-10-28 14:12 UTC, spbrogan commented
@jesserockz anything more needed here?

2024-10-29 03:48 UTC, jesserockz approved these changes

2024-10-29 03:49 UTC, merged