Add sx127x component
OttoWinter/esphomeyaml pull request #7490
Opened 2024-09-24 15:57 UTC by swoboda1337

# What does this implement/fix?

The SX127X component allows you to configure the SX1276, SX1277, SX1278 and SX1279 transceivers in ESPHome. Supported frequencies range from 137 MHz to 1020 MHz. Supported modulations include OOK, FSK, GFSK, MSK and GMSK. Support for both receive and transmit.

Datasheet: https://www.semtech.com/products/wireless-rf/lora-connect/sx1278#documentation
There are many ESP32s already packaged with these radios: https://www.lilygo.cc/en-ca/products/lora3

There are already about a dozen or so people using my component. It would be nice to get these radios officially supported.  

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4278

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sx127x:
  nss_pin: GPIO18
  rst_pin: GPIO23
  frequency: 433920000
  modulation: OOK
  rx_start: true
  rx_bandwidth: 50_0kHz
  rx_floor: -90

remote_receiver:
  pin: GPIO32
  dump: raw
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-24 17:23 UTC, lboue commented
Build is OK with M5stack Cores3 and Module-LoRa868_V1.1.

2024-09-30 11:42 UTC, swoboda1337 commented
Concerted to draft temporarily to do more fsk testing,

2024-10-02 12:30 UTC, swoboda1337 commented
M5 stack doesn't have dio2 connected. Will add support for packet mode as well.

2024-10-17 17:09 UTC, herostrat commented
No review, just a thank you for writing this component.
It works for me (heltec lora 32 v2)!

2024-10-20 12:29 UTC, swoboda1337 commented
Packet mode is done, works great with fsk. M5stack can be used now as it only supports packet mode. Need to add a few automations and it's done.

2024-10-21 14:43 UTC, swoboda1337 commented
Everything is done, will be updating the docs this week.

2024-10-22 00:16 UTC, paravoid reviewed
Disclaimer: I know very little about the SX127s, so consider this a mostly uninformed review.

Broadly speaking, there are a lot of magic numbers in the code (some I've left comments at, but there are plenty more) and I had to go back and forth to the datasheet to unpack the code. So for clueless folks like me :grin:, perahps it would be useful to add names to many (most?) of them, especially when the datasheet already has names defined for them (e.g. FXOSC).

Hope this review helps!

2024-10-22 00:16 UTC, paravoid commented on esphome/components/sx127x/sx127x.cpp
> +    uint64_t bitrate = (32000000u + this->bitrate_ / 2) / this->bitrate_;
Perhaps define this hardcoded constant (32000000u), as it's also used elsewhere. I believe this is FXOSC, right? Also perhaps explain why this calculation is built this way?

2024-10-22 00:16 UTC, paravoid commented on esphome/components/sx127x/sx127x.cpp
> +    bit_sync = BIT_SYNC_ON;
Should the bit synchronizer be unilaterally on? AIUI the data sheet recommends it, but does not mandate it. If not configurable through YAML, perhaps allow a way for other components to disable it, if necessary?

2024-10-22 00:16 UTC, paravoid commented on esphome/components/sx127x/sx127x.cpp
> +  uint64_t frf = ((uint64_t) this->frequency_ << 19) / 32000000;
This is dividing by FSTEP = FXOSC / 2**19, correct? Perhaps use define and/or comments to avoid the magic numbers?

2024-10-22 00:16 UTC, paravoid commented on esphome/components/sx127x/sx127x.h
> +enum SX127xRxBw : uint8_t {
Where did you get these values? From the data sheet I could only find the table of RxBwMant/RxBwExp/RxBw. I saw that you're calculating `rx_bw_mant` and `rx_bw_exp` from these values, but I couldn't figure out what the source information is? Are these precalculated?

2024-10-22 00:16 UTC, paravoid commented on esphome/components/sx127x/__init__.py
> +        cv.Optional(CONF_PA_POWER, default=17): cv.int_range(min=0, max=17),
Any plans to also support setting PaDac = "the +20dBm option on PA_BOOST pin"?

2024-10-22 00:16 UTC, paravoid commented on esphome/components/sx127x/__init__.py
> +        cv.Optional(CONF_FSK_FDEV, default=5000): cv.int_range(min=0, max=100000),
I think this, as well as CONF_FSK_RAMP, should not be configured on OOK mode, correct? If so, perhaps a final_validate is needed to raise an invalid config exception if these are defined but mode is set to OOK?

2024-10-22 00:30 UTC, swoboda1337 commented on esphome/components/sx127x/sx127x.cpp
> +    bit_sync = BIT_SYNC_ON;
It is configurable in the YAML, if the bitrate is 0 the bit synchronizer if off. Definitely need the ability to turn it off. You may not know what the bitrate of your rf device is before you listen to it. So need the ability to do raw unsynchronized data.

2024-10-22 00:31 UTC, swoboda1337 commented on esphome/components/sx127x/sx127x.cpp
> +    bit_sync = BIT_SYNC_ON;
I am working on finishing the docs now

2024-10-22 00:33 UTC, swoboda1337 commented on esphome/components/sx127x/sx127x.h
> +enum SX127xRxBw : uint8_t {
Just taking the values from the table and using register description putting them together. I can add a comment.

2024-10-22 00:35 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +        cv.Optional(CONF_PA_POWER, default=17): cv.int_range(min=0, max=17),
Honestly it wasn't clear from the register description how to do that. I can look again but yeah it was confusing.

2024-10-22 00:36 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +        cv.Optional(CONF_FSK_FDEV, default=5000): cv.int_range(min=0, max=100000),
Yes I could add that. It doesn't break OOK mode, it does set the register it just doesn't have any effect on the signal.

2024-10-22 00:44 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +        cv.Optional(CONF_PA_POWER, default=17): cv.int_range(min=0, max=17),
![image](https://github.com/user-attachments/assets/1a8bb4a3-2a32-49bc-8591-68e41fb984a6)

In boost mode Pout is 17 - (15 - OutputPower) and OutputPower is only 4 bits... so the max I can set is 17. I know the docs say 20 db but I have no idea how to do that.

2024-10-22 00:54 UTC, paravoid commented on esphome/components/sx127x/sx127x.cpp
> +    bit_sync = BIT_SYNC_ON;
Sorry I think I wasn't clear! I meant that right now as the code is structured, it's not possible to set a bitrate _and_ turn off the bit synchronizer. Shouldn't that be possible?

2024-10-22 00:55 UTC, paravoid commented on esphome/components/sx127x/sx127x.h
> +enum SX127xRxBw : uint8_t {
So why is e.g. RX_BW_2_6 = 0x17 and  RX_BW_25_0 = 0x0C? I didn't find that in the table, but I may have missed it!

2024-10-22 01:00 UTC, paravoid commented on esphome/components/sx127x/__init__.py
> +        cv.Optional(CONF_PA_POWER, default=17): cv.int_range(min=0, max=17),
I believe this is a different setting:

![image](https://github.com/user-attachments/assets/e438ea50-8940-4ff0-bfcb-1eb462489c62)

So...
```
// REG_PA_DAC = 0x4d
// PA_DAC_ENABLED  = 0x07
// PA_DAC_DISABLED = 0x04
this->write_register_(REG_PA_DAC, PA_DAC_ENABLED);
```
...but only when output power is 17?

(untested)

2024-10-22 01:03 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +        cv.Optional(CONF_PA_POWER, default=17): cv.int_range(min=0, max=17),
Yeah I didnt spend a lot of time on that. I can add support for it.

2024-10-22 01:05 UTC, swoboda1337 commented on esphome/components/sx127x/sx127x.cpp
> +    bit_sync = BIT_SYNC_ON;
I don't think that setting would do anything with it off.

2024-10-22 01:07 UTC, swoboda1337 commented on esphome/components/sx127x/sx127x.cpp
> +    bit_sync = BIT_SYNC_ON;
I will double check this but dont think the bit rate setting matters if it is off.

2024-10-22 01:13 UTC, swoboda1337 commented on esphome/components/sx127x/sx127x.h
> +enum SX127xRxBw : uint8_t {
Table 40 on page 88 has all the possible bw mant and exp settings. For 25 the exp would be 4 and the mant would be 01/20. For 2.6 the exp would be 7 and the mant would be 10/24. Since bw is FXOSC / (mant * 2^(exp +2)) it works out.

2024-10-22 01:18 UTC, swoboda1337 commented on esphome/components/sx127x/sx127x.cpp
> +    bit_sync = BIT_SYNC_ON;
I guess I can add this just in case something is affected by the bitrate without the synchronizer on.

2024-10-31 02:01 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +        cv.Optional(CONF_PA_POWER, default=17): cv.int_range(min=0, max=17),
Ok I read a bit more about this and I don't think its worth it. Has a lot of restrictions including duty cycle. Have to adjust the over current protection too.

2024-11-01 01:52 UTC, swoboda1337 commented
Docs are done and I made some updates after review comments. Should be ready to go

2024-11-07 15:45 UTC, paravoid commented on esphome/components/sx127x/__init__.py
> +    if CONF_BITSYNC in config and CONF_BITRATE not in config:
This fails with:
```
# no bitrate
bitsync: false
```

Doesn't this need to check for `config[CONF_BITSYNC] is True`? Like `config.get(CONF_BITSYNC, False) is True and CONF_BITRATE not in config`?

2024-11-07 16:01 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +    if CONF_BITSYNC in config and CONF_BITRATE not in config:
Thanks yeah don't know why I missed this

2024-12-12 16:11 UTC, swoboda1337 commented
Moved to draft until new RMT drivers are integrated.

2025-01-02 14:14 UTC, swoboda1337 commented
Cleaned up docs. Removed hacks that were required with the older RMT drivers. PR is ready to go.

2025-01-10 12:28 UTC, esnet146 commented
Tested on board heltec_wifi_lora_32_V2. 
Remote_receiver and remote_transmitter works great!
Rst - gpio14
DIO2 Connected in GPIO34 (INPUT ONLY)
To operate the transmitter, you can connect GPIO34 and GPIO13.
We are impatiently waiting for the PR to be received!
```
spi:
  clk_pin: GPIO5
  mosi_pin: GPIO27
  miso_pin: GPIO19
sx127x:
  dio0_pin: GPIO26
  nss_pin: GPIO18
  rst_pin: GPIO14
  frequency: 433920000
  pa_pin: BOOST
```

2025-02-07 04:49 UTC, kbx81 requested changes, later dismissed
Couple thoughts

2025-02-07 04:49 UTC, kbx81 commented on esphome/components/sx127x/__init__.py
> +CONF_ON_PACKET = "on_packet"
Please alphabetize lists of constants/variables like this. 🙂

2025-02-07 04:49 UTC, kbx81 commented on tests/components/sx127x/test.esp32-ard.yaml
Please consolidate the tests into a `common.yaml` file and use substitutions for the pin numbers (as is done in most other components).

2025-02-07 22:01 UTC, swoboda1337 commented
More clean up, please use the standard CS_PIN instead of NSS_PIN

2025-02-08 19:37 UTC, swoboda1337 commented
Code clean up complete and review comments addressed. Ready to go.

2025-02-08 19:50 UTC, swoboda1337 commented
Code clean up complete and review comments addressed. Should be ready to go.

2025-02-11 04:18 UTC, swoboda1337 commented
Sorry, now its ready, found a few more things to clean up

2025-02-11 17:37 UTC, swoboda1337 commented
Stress testing revealed a few corner cases in packet mode when switching from rx to tx. 

Resolve by switching directly from rx to tx (the only way to clear the fifo) and increasing fs delays. 

Stress testing is complete and things look good.

2025-02-17 03:38 UTC, swoboda1337 commented
Ok LoRa support has been added after a few people requested it.

2025-03-18 10:09 UTC, esnet146 commented
Please add packet_transport platform lora for this component.
https://github.com/esphome/esphome/pull/8214

Checked the operation of the module sx1278 ( XL1278-SMT)  on the board KinCony KC868-A6 
```
sx127x:
  dio0_pin:
    number: GPIO02
    ignore_strapping_warning: true    
  cs_pin:
    number: GPIO05
    ignore_strapping_warning: true    
  rst_pin: GPIO21
  pa_pin: BOOST
  pa_power: 17
  bandwidth: 250_0kHz
  crc_enable: true
  frequency: 433920000
  modulation: LORA
  rx_start: true
  sync_value: 0x33 
  spreading_factor: 7 
  coding_rate: CR_4_5 
  on_packet:
    then:
  ```
In packet transmission mode, two-way communication to standard antennas within the city limits is 400 meters, outside the city up to 1 km

2025-03-18 12:41 UTC, swoboda1337 commented
> Please add packet_transport platform lora for this component. #8214
> 
> In packet transmission mode, two-way communication to standard antennas within the city limits is 400 meters, outside the city up to 1 km

You can increase the range if you change the spreading_factor and code_rate. SF12 and CR_4_8 would be give a much larger range. SF12 takes a very long time on the air though SF10 would be better. 

That PR is not merged yet. I will look at integrating it once that happens.

2025-03-18 12:46 UTC, mortenx commented
What could be the distance with the best settings?

2025-03-18 13:02 UTC, swoboda1337 commented
Depends on the environment. If its line of sight with a good antenna they claim 5km, some people say even 10km but would need a perfect environment like one side elevated on hill or something. 

To get the max range I would also have to add support for 20dbm tx, probably should do that.

2025-03-18 20:41 UTC, esnet146 commented
> SF12 and CR_4_8

~30% !

2025-03-18 20:48 UTC, swoboda1337 commented
> > SF12 and CR_4_8
> 
> ~30% ! in city

30% of what?

2025-03-18 21:11 UTC, esnet146 commented
> 30% of what?

range

2025-04-02 21:13 UTC, dala318 commented
> Please add packet_transport platform lora for this component. 

@esnet146 and @swoboda1337 
I've made an attempt in appending this base with packet_transport in https://github.com/dala318/esphome/pull/3 and it seem to be possible without much extras. The later addition of `register_listener` was a good help!

In my config I have set the sx1276 in LoRa mode, which don't have a pre-defined payload length. I suppose that would be a requirement if using packet_transport. (have not tried how the other FSK/OOK modes behave)

Also, as I commented in https://github.com/esphome/feature-requests/issues/2634#issuecomment-2761064325 it would be a nice addition if both sx126x and sx127x could be wrapped by a `lora` component. If so (and if LoRa mode is required) maybe this lora component is the one that should get packet_transport added?

2025-04-05 20:47 UTC, swoboda1337 commented
> Also, as I commented in https://github.com/esphome/feature-requests/issues/2634#issuecomment-2761064325 it would be a nice addition if both sx126x and sx127x could be wrapped by a lora component. If so (and if LoRa mode is required) maybe this lora component is the one that should get packet_transport added?

Yeah eventually I think a higher layer LoRa component would be a good idea especially if we ever want to support LoRaWAN. Hopefully the packet transport stuff gets merged soon.

2025-04-22 14:42 UTC, wildekek commented
This is an amazing component, works great on the LilyGo LoRa32 V1.0. It would be amazing to have this merged to dev. This could be what LoRa needs to get broad adoption in the HA community, especially when people build LoraWan and Meshtastic support on top. This PR deserves more attention from the core devs.

2025-05-13 08:58 UTC, dala318 commented on esphome/components/sx127x/__init__.py
> +)
Is the `cv.All(..)` really needed?
```suggestion
CONFIG_SCHEMA = cv.Schema(
    {
        cv.GenerateID(): cv.declare_id(SX127x),
        cv.Optional(CONF_AUTO_CAL, default=True): cv.boolean,
        cv.Optional(CONF_BANDWIDTH, default="125_0kHz"): cv.enum(BW),
        cv.Optional(CONF_BITRATE): cv.int_range(min=500, max=300000),
        cv.Optional(CONF_BITSYNC): cv.boolean,
        cv.Optional(CONF_CODING_RATE, default="CR_4_5"): cv.enum(CODING_RATE),
        cv.Optional(CONF_CRC_ENABLE, default=False): cv.boolean,
        cv.Optional(CONF_DEVIATION, default=5000): cv.int_range(min=0, max=100000),
        cv.Optional(CONF_DIO0_PIN): pins.internal_gpio_input_pin_schema,
        cv.Required(CONF_FREQUENCY): cv.int_range(min=137000000, max=1020000000),
        cv.Required(CONF_MODULATION): cv.enum(MOD),
        cv.Optional(CONF_ON_PACKET): automation.validate_automation(single=True),
        cv.Optional(CONF_PA_PIN, default="BOOST"): cv.enum(PA_PIN),
        cv.Optional(CONF_PA_POWER, default=17): cv.int_range(min=0, max=17),
        cv.Optional(CONF_PA_RAMP, default="40us"): cv.enum(RAMP),
        cv.Optional(CONF_PAYLOAD_LENGTH, default=0): cv.int_range(min=0, max=256),
        cv.Optional(CONF_PREAMBLE_DETECT, default=0): cv.int_range(min=0, max=3),
        cv.Optional(CONF_PREAMBLE_ERRORS, default=0): cv.int_range(min=0, max=31),
        cv.Optional(CONF_PREAMBLE_POLARITY, default=0xAA): cv.All(
            cv.hex_int, cv.one_of(0xAA, 0x55)
        ),
        cv.Optional(CONF_PREAMBLE_SIZE, default=0): cv.int_range(min=0, max=65535),
        cv.Required(CONF_RST_PIN): pins.internal_gpio_output_pin_schema,
        cv.Optional(CONF_RX_FLOOR, default=-94): cv.float_range(min=-128, max=-1),
        cv.Optional(CONF_RX_START, default=True): cv.boolean,
        cv.Optional(CONF_SHAPING, default="NONE"): cv.enum(SHAPING),
        cv.Optional(CONF_SPREADING_FACTOR, default=7): cv.int_range(min=6, max=12),
        cv.Optional(CONF_SYNC_VALUE, default=[]): cv.ensure_list(cv.hex_uint8_t),
    },
).extend(
    cv.COMPONENT_SCHEMA
).extend(
    spi.spi_device_schema(True, 8e6, "mode0")
).add_extra(
    validate_config
)
```

2025-05-13 13:24 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +)
Doesnt make much of a difference but sure can use add_extra instead

2025-05-28 06:32 UTC, dala318 reviewed
Just some proposals. Thinks it look good in general.

2025-05-28 06:32 UTC, dala318 commented on esphome/components/sx127x/__init__.py
> +        cg.add(var.set_bitrate(config[CONF_BITRATE]))
Just a suggestion, makes the code a bit cleaner (in my oppinion).
```suggestion
    if bitrate := config.get(CONF_BITRATE):
        cg.add(var.set_bitrate(bitrate))
```

2025-05-28 06:32 UTC, dala318 commented on esphome/components/sx127x/sx127x.h
> +  uint32_t payload_length_;
Rename to `max_payload_length_`? Could otherwise be mistaken for actual payload length.

2025-05-28 06:32 UTC, dala318 commented on tests/components/sx127x/common.yaml
> +
Add a `packet_transport` instance as well?

2025-05-28 07:28 UTC, dala318 commented on esphome/components/sx127x/automation.h
> +template<typename... Ts> class RunImageCalAction : public Action<Ts...> {
Is there a reason to why SendPacketAction is `public Parented<SX127x>` but the other actions not?

2025-05-28 11:04 UTC, swoboda1337 commented on tests/components/sx127x/common.yaml
> +
packet_transport is its own thing, dont need actions: https://esphome.io/components/packet_transport/index.html#example-configuration

2025-05-28 11:10 UTC, swoboda1337 commented
> Just some proposals. Thinks it look good in general.

Thanks! I will look at these and probably make a few changes.

2025-05-31 15:32 UTC, swoboda1337 commented on esphome/components/sx127x/sx127x.h
> +  uint32_t payload_length_;
If the value is 0 its variable length. If it has a non zero value that is the actual length.

2025-05-31 15:32 UTC, swoboda1337 commented on esphome/components/sx127x/automation.h
> +template<typename... Ts> class RunImageCalAction : public Action<Ts...> {
There is not, I will update them all to use `public Parented<SX127x>`

2025-05-31 15:33 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +        cg.add(var.set_bitrate(config[CONF_BITRATE]))
It looks more consistent with the other lines though:
```
    cg.add(var.set_pa_ramp(config[CONF_PA_RAMP]))
    cg.add(var.set_pa_power(config[CONF_PA_POWER]))
    cg.add(var.set_shaping(config[CONF_SHAPING]))
    if CONF_BITRATE in config:
        cg.add(var.set_bitrate(config[CONF_BITRATE]))
    else:
        cg.add(var.set_bitrate(4800))
```

2025-06-12 20:15 UTC, mcuelenaere commented on esphome/components/sx127x/packet_transport/sx127x_transport.cpp
> +#include "esphome/components/network/util.h"
I don't believe this include is being used. Having it here, requires the board to be configured with wifi/network enabled.

2025-06-12 20:23 UTC, swoboda1337 commented on esphome/components/sx127x/packet_transport/sx127x_transport.cpp
> +#include "esphome/components/network/util.h"
I will take a look

2025-06-12 21:54 UTC, mcuelenaere commented on esphome/components/sx127x/packet_transport/sx127x_transport.cpp
> +#include "esphome/components/network/util.h"
(I can confirm this PR works without that include. I forked your code to remove it, otherwise I couldn't get it to work on a board with wifi disabled)

2025-06-12 21:58 UTC, swoboda1337 commented on esphome/components/sx127x/packet_transport/sx127x_transport.cpp
> +#include "esphome/components/network/util.h"
Ok I will update the pr

2025-06-27 18:50 UTC, M66B commented
@swoboda1337 Since Lora is often used for IoT devices out of range of Wi-Fi networks, it would be nice to be able to OTA update via Lora.

Something like:

```
ota:
  platform: sx127x
```

A spreading factor of 7 has a theoretical data rate of 5465 kbps, let's say 5 KByte/sec. Sending a 2MB image would take 2000/5 seconds = ~ 7 minutes.

The sending esp device could have a web interface to upload to another esp device.

```
web_server:
  ota: true
    platform: sx127x    
```

Is this feasible? No, of course, is also an answer. I'm just thinking out loud.

2025-06-27 19:19 UTC, swoboda1337 commented
> Is this feasible? No, of course, is also an answer. I'm just thinking out

Is it possible to do, probably could hack something together. 

Is it feasible, not atm. Would need a device to act as a proxy and forward the update. There is no way to do that atm without hacks.

2025-07-01 23:43 UTC, jesserockz commented on esphome/components/sx127x/__init__.py
> +        cg.add(var.set_bitrate(config[CONF_BITRATE]))
You should be setting the default inside the config_schema, then you can assume there is always a value. Same for the below ones too

2025-07-02 01:45 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +        cg.add(var.set_bitrate(config[CONF_BITRATE]))
I did this because I made a breaking change and needed to know if it was set in the validation code. It's been long enough though. I will clean it up.

2025-07-03 00:20 UTC, bdraco commented on esphome/components/sx127x/__init__.py
> +            raise cv.Invalid("Payload length must be >= 64 with FSK/OOK")
message doesn't match check

2025-07-03 00:25 UTC, bdraco commented on esphome/components/sx127x/sx127x.cpp
> +        }
nit: Magic numbers count use comments or constants here

2025-07-03 00:26 UTC, bdraco commented on esphome/components/sx127x/sx127x.cpp
> +  ESP_LOGCONFIG(TAG, "  PA Ramp: %" PRIu16 " us", RAMP[this->pa_ramp_]);
could be optimized a bit https://developers.esphome.io/architecture/logging/

2025-07-03 00:26 UTC, bdraco commented on esphome/components/sx127x/sx127x.cpp
> +    ESP_LOGCONFIG(TAG, "  Rx Floor: %.1f dBm", this->rx_floor_);
https://developers.esphome.io/architecture/logging/

2025-07-03 00:28 UTC, bdraco commented on esphome/components/sx127x/sx127x.cpp
> +    if (this->dio0_pin_->digital_read()) {
Could use early return here to make this a bit easier to follow

2025-07-03 00:29 UTC, bdraco commented on esphome/components/sx127x/sx127x.cpp
> +      break;
Is there a potential concern about blocking the event loop here?

2025-07-03 00:36 UTC, bdraco commented on esphome/components/sx127x/__init__.py
> +        return value
Looks unreachable

2025-07-03 00:37 UTC, bdraco commented on esphome/components/sx127x/__init__.py
> +        if config[CONF_PREAMBLE_SIZE] > 0 and config[CONF_PREAMBLE_SIZE] < 6:
```suggestion
        if 0 < config[CONF_PREAMBLE_SIZE] < 6:
```

2025-07-03 00:38 UTC, bdraco commented on esphome/components/sx127x/__init__.py
> +        ]
nit: Could be a constant frozenset to avoid linear search

2025-07-03 00:41 UTC, bdraco commented on esphome/components/sx127x/__init__.py
> +    if config[CONF_MODULATION] == "LORA":
cv.typed_schema with discriminator=CONF_MODULATION might be cleaner in the schema to avoid hand rolled validate_config

2025-07-03 00:47 UTC, bdraco commented
Besides some minor nits, https://github.com/esphome/esphome/pull/7490#discussion_r2181229415 looks like the only potential area of concern remaining

2025-07-03 01:49 UTC, swoboda1337 commented on esphome/components/sx127x/sx127x.cpp
> +      break;
Its basically the same as remote transmitter which blocks as well. Typically you will do other things after transmitting like delay plus transmit again. Making this non blocking can get messy and I think will cause misunderstandings.

The 4 second delay isn't representative of the typical delay. Like remote transmitter this should normally be like 50 ms or less. 

Even if a blocking mode is added I think the default should be blocking.

2025-07-03 01:50 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +        return value
Must have been a copy and paste error

2025-07-03 01:51 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +            raise cv.Invalid("Payload length must be >= 64 with FSK/OOK")
yeah should be <= wups

2025-07-03 01:51 UTC, bdraco commented on esphome/components/sx127x/sx127x.cpp
> +      break;
Would you please add some comments explaining this behavior so we don't need to revisit it in the future.

2025-07-03 01:53 UTC, swoboda1337 commented on esphome/components/sx127x/sx127x.cpp
> +    ESP_LOGCONFIG(TAG, "  Rx Floor: %.1f dBm", this->rx_floor_);
Yeah wrote this a year ago... will update

2025-07-03 13:32 UTC, swoboda1337 commented on esphome/components/sx127x/__init__.py
> +        ]
Only used once, the savings are probably offset by creating the frozenset. Would save like 1 us max and add two lines of code.

2025-07-03 13:40 UTC, bdraco approved these changes

2025-07-03 15:37 UTC, merged

2025-07-03 15:37 UTC, bdraco commented
Thanks @swoboda1337