tcs34725: optimize fetch time with burst read for RGB and clear values
OttoWinter/esphomeyaml pull request #7494
Opened 2024-09-25 01:56 UTC by RubenKelevra

# What does this implement/fix?

- Switched to a single burst read operation for R, G, B, and clear channels. This replaces four separate I2C commands with one, allowing us to pull all 16 bytes in one go.
- Significantly reduces roundtrip overhead, improving the overall performance.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other: Small optimization

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

<details>

```yaml
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini
  friendly_name: $friendly_name

substitutions:
  devicename: ambient-light-sensor
  friendly_name: "Ambient Light Sensor"

logger:
  level: DEBUG

mdns:
  
time:
  - platform: homeassistant

api:
  encryption: 
    key: !secret api_key-ambient-light-sensor

ota:
  platform: esphome
  password: !secret ota_password_ambient-light-sensor

wifi:
  networks:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    manual_ip:
      static_ip: !secret ip-ambient-light-sensor
      gateway: !secret wifi_gateway
      subnet: !secret wifi_subnet
      dns1: !secret wifi_dns1

i2c:
  sda: D1
  scl: D2
  scan: true
  id: bus_a

sensor:
  - platform: tcs34725
    i2c_id: bus_a
    red_channel:
      name: "$friendly_name Red Channel relative"
      accuracy_decimals: 1
    green_channel:
      name: "$friendly_name Green Channel relative"
      accuracy_decimals: 1
    blue_channel:
      name: "$friendly_name Blue Channel relative"
      accuracy_decimals: 1
    clear_channel:
      name: "$friendly_name Clear Channel"
      accuracy_decimals: 1
    illuminance:
      name: "$friendly_name Illuminance"
      accuracy_decimals: 0
    color_temperature:
      name: "$friendly_name Color Temperature"
      accuracy_decimals: 0
    gain: 1x
    integration_time: auto
    glass_attenuation_factor: 1.0
    address: 0x29   

output:
  - platform: gpio
    pin: D3
    id: white_led
    inverted: false
  
light:
  - platform: binary
    output: white_led
    name: "$friendly_name White LED"
```

</details>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-25 04:58 UTC, jesserockz commented on esphome/components/tcs34725/tcs34725.cpp
clang-format :wink: 
```suggestion
```

2024-09-25 05:02 UTC, jesserockz requested changes

2024-09-25 05:02 UTC, jesserockz commented on esphome/components/tcs34725/tcs34725.cpp
> +  uint16_t raw_b = data[6] | (data[7] << 8);  // Blue channel
We have functions in `helpers.h` that do this with the correct casting. It will require `#include "esphome/core/helpers.h"` at the top too
```suggestion
  uint16_t raw_c = encode_uint16(data[1], data[0]);  // Clear channel
  uint16_t raw_r = encode_uint16(data[3], data[2]);  // Red channel
  uint16_t raw_g = encode_uint16(data[5], data[4]);  // Green channel
  uint16_t raw_b = encode_uint16(data[7], data[6]);  // Blue channel
```

2024-09-25 07:21 UTC, RubenKelevra commented on esphome/components/tcs34725/tcs34725.cpp
Yeah, I'm sorry, I haven't yet set up an IDE and it's been a while - 2009 or so - since I programmed the last time in C++. Please be patient :)

2024-09-25 20:13 UTC, jesserockz commented on esphome/components/tcs34725/tcs34725.cpp
clang-format is easy to set up and can be installed as just a python package. Its clang-tidy that requires a lot more set up (I dont set up tidy myself locally)

2024-09-25 21:16 UTC, RubenKelevra commented on esphome/components/tcs34725/tcs34725.cpp
Thanks, I thought about using Clion, which supports both. But I'm not yet finished setting it up. So Kate it is atm :)

2024-09-30 22:00 UTC, jesserockz approved these changes

2024-09-30 22:00 UTC, merged