Support W5500 SPI-Ethernet polling mode if framework is supported
OttoWinter/esphomeyaml pull request #7503
Opened 2024-09-27 11:41 UTC by slakichi

# What does this implement/fix?

W5500 can work without interrupt(IRQ) pin, but crash at init if configure without `interrupt_pin`.
This patch adds polling mode to SPI-based ethernet if ESP-IDF framework is supported.
Closes: 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#6268

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> [not yet]

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: m5atoms3-lite
  friendly_name: "M5Stack M5AtomS3 Lite"
  platformio_options:
    board_build.f_cpu: 80000000L
    board_build.f_flush: 80000000L

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  variant: esp32s3
  framework:
    type: esp-idf
# recommended version disables polling mode (interrupt_pin is mandatory; polling_interval is invalid)
#    version: recommended
    version: "5.3.1"
    platform_version: "6.9.0"

network:
  enable_ipv6: false

ethernet:
  type: W5500
  # W5500(SPI) mandatory pins
  # ATOM: CLK=22, CS=19, MISO=23, MOSI=33
  clk_pin: GPIO5
  mosi_pin: GPIO8
  miso_pin: GPIO7
  cs_pin: GPIO6
  # if ESP-IDF >= 5.3 or 5.2.1+ or 5.1.4+ / arduino >= 3.0.0, interrupt_pin is optional; oterwise mandatory
  #interrupt_pin: GPIO4
  # [New] if interrupt_pin is omitted, set polling interval; minimum is 1ms, default is 10ms.
  # available only if ESP-IDF >= 5.3 or 5.2.1+ or 5.1.4+ / arduino >= 3.0.0 (* pio still not supports arduino-esp32 3.0.x)
  polling_interval: 10ms
  #reset_pin:
  clock_speed: 10MHz
  manual_ip:
    static_ip: 192.168.xxx.xxx
    gateway: 192.168.xxx.xxx
    subnet: 255.255.255.0
    dns1: 192.168.xxx.xxx

api:
  encryption:
    key: !secret home_assistant_api_password
  reboot_timeout: 300s

ota:
  platform: esphome
  password: !secret ota_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: uptime
    type: timestamp
    entity_category: diagnostic
  - platform: internal_temperature
    entity_category: diagnostic
    name: "Internal Temperture"

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-09-28 03:59 UTC, cortices commented
This change is a requirement for correct functioning on a few devices I have had issues using, both for the same reason:

- M5Stack POECam-W 
- Norvi ENET AE06 

Both using W5500 with no INTn pin connected

2024-09-28 14:55 UTC, ijc commented
This works for me on an m5stack lite with the [Atom POE](https://docs.m5stack.com/en/atom/atom_poe). Previously I was seeing symptoms similar to #6217. My crash was in a gpio setup function.

2024-10-06 12:08 UTC, ptrkp commented
> This works for me on an m5stack lite with the [Atom POE](https://docs.m5stack.com/en/atom/atom_poe). Previously I was seeing symptoms similar to [esphome/issues#6217](https://github.com/esphome/issues/issues/6217). My crash was in a gpio setup function.

What for config did you use?

2024-10-06 12:33 UTC, ijc commented
At commit cc2f39aa1f85e7bad567a8022a2ccfd8f246e6ec I used 

```yaml
esphome:
  name: study-bluetooth-proxy
  friendly_name: Study Bluetooth Proxy

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    version: "5.3.1" 
    platform_version: "6.9.0" 

ethernet:
  type: W5500
  clk_pin: GPIO22
  mosi_pin: GPIO33
  miso_pin: GPIO23
  cs_pin: GPIO19
  clock_speed: 20MHz
  polling_interval: 10ms
  manual_ip:
    static_ip: ...
    gateway: ...
    subnet: ...
    dns1: ...

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "..."

ota:
  - platform: esphome
    password: "..."

esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    id: button_safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset
```

2024-10-16 08:21 UTC, ijc reviewed
This LGTM and I've been running it for a while. I left some comments/suggestions but I think nothing which really affects the functionality

@jesserockz @JeroenVanOort would it be possible to get this on the radar for a future release?

2024-10-16 08:21 UTC, ijc commented on esphome/components/ethernet/__init__.py
> +            "using framework is unknown for ethernet component (expecting esp-idf or arduino)"
I'm struggling to grok this message. I think what it means to say "framework is unknown for..." or "using unknown framework for..."? It might be worth including `target_framework` in the message to? `f"framework {target_framework} is unknown..." ?

2024-10-16 08:21 UTC, ijc commented on esphome/components/ethernet/__init__.py
> +                    ): pins.internal_gpio_input_pin_number,
This is done in both sides of the `if`/`else`.

I think you could just have left it at [line 155](https://github.com/esphome/esphome/pull/7503/files#diff-85e64ec58a4b59699afbc9adca694a178fd5b54f8b91dee76ff0390f38da0312L155) where you removed it?

2024-10-16 08:21 UTC, ijc commented on esphome/components/ethernet/__init__.py
>  SPI_SCHEMA = BASE_SCHEMA.extend(
WDYT of naming this `BASE_SPI_SCHEMA`?

2024-10-16 08:21 UTC, ijc commented on esphome/components/ethernet/ethernet_component.cpp
> +    ESP_LOGE(TAG, "IRQ pin number is negative(%d), seems configuration error", this->interrupt_pin_);
Suggest: "...seems to be configuration error" or "Configuration error: IRQ pin number is negative(%d)".

2024-10-18 02:41 UTC, slakichi commented on esphome/components/ethernet/ethernet_component.cpp
> +    ESP_LOGE(TAG, "IRQ pin number is negative(%d), seems configuration error", this->interrupt_pin_);
corrected: 4619cf649151c13680125cf2aea016b2304b43cc

2024-10-18 02:57 UTC, slakichi commented on esphome/components/ethernet/__init__.py
> +SPI_SCHEMA = _add_spi_irq_schema(SPI_SCHEMA)
IMHO, this may cause meaningless and irritating warnings for ESP8266 users... Should I validate at _final_validate(FINAL_VALIDATE_SCHEMA)?

2024-10-18 03:11 UTC, slakichi commented on esphome/components/ethernet/__init__.py
>  SPI_SCHEMA = BASE_SCHEMA.extend(
Looks like it is named in the same way as RMII_SCHEMA (line 140).

2024-10-18 03:36 UTC, slakichi commented on esphome/components/ethernet/__init__.py
> +            "using framework is unknown for ethernet component (expecting esp-idf or arduino)"
`ethernet component is not expected to use framework {target_framework} (expecting esp-idf or arduino)` is OK?

2024-10-18 04:13 UTC, slakichi commented on esphome/components/ethernet/__init__.py
> +                    ): pins.internal_gpio_input_pin_number,
Please look carefully. At [line 199](https://github.com/esphome/esphome/pull/7503/files#diff-85e64ec58a4b59699afbc9adca694a178fd5b54f8b91dee76ff0390f38da0312R199)(if condition is met), `interrupt_pin` is configured as 'Optional', but [line 213](https://github.com/esphome/esphome/pull/7503/files#diff-85e64ec58a4b59699afbc9adca694a178fd5b54f8b91dee76ff0390f38da0312R213)(if condition is not met) `interrupt_pin` is configured as 'Required'. This is required for older frameworks (that don't support polling-based SPI ethernet module). They __require__ `interrupt_pin` number.

2024-10-18 07:01 UTC, ijc commented on esphome/components/ethernet/__init__.py
> +            "using framework is unknown for ethernet component (expecting esp-idf or arduino)"
Your proposal sounds good to me. Or maybe "... is not compatible with framework {target_framework}"?

2024-10-18 07:01 UTC, ijc commented on esphome/components/ethernet/__init__.py
> +                    ): pins.internal_gpio_input_pin_number,
Thanks, I had missed that indeed.

2024-10-18 07:04 UTC, ijc commented on esphome/components/ethernet/__init__.py
>  SPI_SCHEMA = BASE_SCHEMA.extend(
That's fair, there are some other examples of `FOO_BASE_SCHEMA` used in the rest of the tree but keeping `SPI_SCHEMA` is indeed consistent with the rest of  `ethernet/__init__.py`.

2024-10-18 07:09 UTC, ijc commented on esphome/components/ethernet/__init__.py
> +SPI_SCHEMA = _add_spi_irq_schema(SPI_SCHEMA)
This is beyond my knowledge of esphome internals. I guess you are referring to:
```
        LOGGER.warning(
            "using framework is unknown for ethernet component (expecting esp-idf or arduino)"
        )
```
?

Looking at other components it does look like the norm might be to raise `cv.Invalid` from the validate function.

2024-10-18 08:34 UTC, slakichi commented on esphome/components/ethernet/__init__.py
> +SPI_SCHEMA = _add_spi_irq_schema(SPI_SCHEMA)
At first, I [raised an error](https://github.com/esphome/esphome/pull/7503/commits/3849be8a258915231116ca6a685857a28259243f#diff-85e64ec58a4b59699afbc9adca694a178fd5b54f8b91dee76ff0390f38da0312R187-R189) if framework is not compatible with ethernet component. But this causes [error at list-components test](https://github.com/esphome/esphome/actions/runs/11069972387/job/30758641612?pr=7503). So I changed an error to a warning (commit d02228ffd9a3fdfa0f466801c312321c0409eda1). Even now we still see [warnings at list-components test](https://github.com/esphome/esphome/actions/runs/11397499943/job/31713055338?pr=7503) (list-components -> Find chaned components). 
Fortunately, I tested with a simple ESP8266 config file and there was no warning output. So usual user may not see meaningless warnings about ethernet component.

2024-10-21 00:44 UTC, slakichi commented
Moved the polling_interval and interrupt_pin setting checks to _validate(). Compared to the previous code, there are the following differences:
1. For older (unsupported) frameworks, prepend "In this version of the framework, ..." to error messages when polling_interval is set or interrupt_pin is not set.
2. If both polling_interval and interrupt_pin are in the config, polling_interval is no longer silently ignored, but an error is raised.
3. No more warnings in list-components test.

2024-10-21 01:00 UTC, slakichi commented on esphome/components/ethernet/__init__.py
> +            "using framework is unknown for ethernet component (expecting esp-idf or arduino)"
Applied commit 2ca6436da0109bc84f96af9cd9efe850bb39f4fe, [Line 126](https://github.com/esphome/esphome/pull/7503/commits/2ca6436da0109bc84f96af9cd9efe850bb39f4fe#diff-85e64ec58a4b59699afbc9adca694a178fd5b54f8b91dee76ff0390f38da0312R126)

2024-10-21 01:01 UTC, slakichi commented on esphome/components/ethernet/__init__.py
> +SPI_SCHEMA = _add_spi_irq_schema(SPI_SCHEMA)
Resolved commit 2ca6436da0109bc84f96af9cd9efe850bb39f4fe

2024-10-21 07:44 UTC, ijc approved these changes
LGTM. I've built and uploaded this to my device.

BTW, I have merged the 2024.10.0 release tag into my checkout of your branch so actually not quite testing exactly what is here, but I think it makes no practical impact.

2024-10-21 07:44 UTC, ijc commented on esphome/components/ethernet/__init__.py
> +def _is_framework_spi_polling_mode_support():
Really nitpicking but I'd say "is_...._supported()` or `..._is_supported()` reads better.

2024-10-21 10:13 UTC, slakichi commented on esphome/components/ethernet/__init__.py
> +def _is_framework_spi_polling_mode_support():
Indeed. (commit 26bbeeb850b9236c40b8fa8abdbc01d2eae999b8)

2024-10-24 01:57 UTC, jesserockz requested changes

2024-10-24 01:57 UTC, jesserockz commented on esphome/components/ethernet/__init__.py
> +    if build_framework == "esp-idf":
```suggestion
    if CORE.using_esp_idf:
```

2024-10-24 01:57 UTC, jesserockz commented on esphome/components/ethernet/__init__.py
> +    if build_framework == "arduino":
```suggestion
    if CORE.using_arduino:
```

2024-10-24 01:57 UTC, jesserockz commented on esphome/components/ethernet/__init__.py
> +    return True
```suggestion
    return False
```

2024-10-24 01:57 UTC, jesserockz commented on esphome/components/ethernet/__init__.py
>          if CONF_RESET_PIN in config:
```suggestion
        if _is_framework_spi_polling_mode_supported():
          cg.add_define("USE_ETHERNET_SPI_POLLING_SUPPORTED")
        if CONF_RESET_PIN in config:
```

2024-10-24 01:57 UTC, jesserockz commented on esphome/components/ethernet/ethernet_component.cpp
> +
```suggestion
```

2024-10-24 01:57 UTC, jesserockz commented on esphome/components/ethernet/ethernet_component.cpp
> +  }
Given the validations on the python side, and the defaults in the header, I don't think you need to do super complex logic here at all
```suggestion
  w5500_config.int_gpio_num = this->interrupt_pin_;
#ifdef USE_ETHERNET_SPI_POLLING_SUPPORTED
  w5500_config.poll_period_ms = this->polling_interval_;
#endif
```

2024-10-24 01:57 UTC, jesserockz commented on esphome/components/ethernet/ethernet_component.cpp
> +#endif
```suggestion
#ifdef USE_ETHERNET_SPI_POLLING_SUPPORTED
  if (this->polling_interval_ != 0) {
    ESP_LOGCONFIG(TAG, "  Polling Interval: %lu ms", this->polling_interval_);
  } else
#endif
  {
    ESP_LOGCONFIG(TAG, "  IRQ Pin: %d", this->interrupt_pin_);
  }
```

2024-10-24 01:57 UTC, jesserockz commented on esphome/components/ethernet/ethernet_component.cpp
> +void EthernetComponent::set_polling_interval(uint32_t polling_interval) { this->polling_interval_ = polling_interval; }
```suggestion
#ifdef USE_ETHERNET_SPI_POLLING_SUPPORTED
void EthernetComponent::set_polling_interval(uint32_t polling_interval) { this->polling_interval_ = polling_interval; }
#endif
```

2024-10-24 01:57 UTC, jesserockz commented on esphome/components/ethernet/ethernet_component.h
> +  void set_polling_interval(uint32_t polling_interval);
```suggestion
#ifdef USE_ETHERNET_SPI_POLLING_SUPPORTED
  void set_polling_interval(uint32_t polling_interval);
#endif
```

2024-10-24 01:57 UTC, jesserockz commented on esphome/components/ethernet/ethernet_component.h
> +  uint32_t polling_interval_{0};
```suggestion
#ifdef USE_ETHERNET_SPI_POLLING_SUPPORTED
  uint32_t polling_interval_{0};
#endif
```

2024-10-24 10:29 UTC, slakichi commented on esphome/components/ethernet/__init__.py
> +    if build_framework == "arduino":
Corrected in [bf00e00](https://github.com/esphome/esphome/pull/7503/commits/bf00e0060b0d2ed921d5344317a292e31515cc7c)

2024-10-24 10:29 UTC, slakichi commented on esphome/components/ethernet/__init__.py
> +    if build_framework == "esp-idf":
Corrected in [bf00e00](https://github.com/esphome/esphome/pull/7503/commits/bf00e0060b0d2ed921d5344317a292e31515cc7c)

2024-10-24 11:03 UTC, slakichi commented on esphome/components/ethernet/__init__.py
>          if CONF_RESET_PIN in config:
`USE_ETHERNET_SPI_POLLING_SUPPORTED` sounds strange. I'll use `USE_ETHERNET_SPI_POLLING_SUPPORT` instead.

2024-10-24 11:21 UTC, slakichi commented on esphome/components/ethernet/__init__.py
> +    return True
OK, Let's throw out the robustness principle.
Resolved in commit [5c9edd6](https://github.com/esphome/esphome/pull/7503/commits/5c9edd645d13e6d330a34520f7edd94dd8632fb9).

2024-10-24 12:29 UTC, slakichi commented on esphome/components/ethernet/ethernet_component.h
> +  uint32_t polling_interval_{0};
Resolved in commit [92fa95d](https://github.com/esphome/esphome/pull/7503/commits/92fa95d180eb749d7680cb3d5faaf567312ebf8a).

2024-10-24 12:29 UTC, slakichi commented on esphome/components/ethernet/ethernet_component.h
> +  void set_polling_interval(uint32_t polling_interval);
Resolved in commit [92fa95d](https://github.com/esphome/esphome/pull/7503/commits/92fa95d180eb749d7680cb3d5faaf567312ebf8a).

2024-10-24 12:29 UTC, slakichi commented on esphome/components/ethernet/ethernet_component.cpp
> +void EthernetComponent::set_polling_interval(uint32_t polling_interval) { this->polling_interval_ = polling_interval; }
Resolved in commit [92fa95d](https://github.com/esphome/esphome/pull/7503/commits/92fa95d180eb749d7680cb3d5faaf567312ebf8a).

2024-10-24 12:29 UTC, slakichi commented on esphome/components/ethernet/ethernet_component.cpp
> +#endif
Resolved in commit [92fa95d](https://github.com/esphome/esphome/pull/7503/commits/92fa95d180eb749d7680cb3d5faaf567312ebf8a).

2024-10-24 12:30 UTC, slakichi commented on esphome/components/ethernet/ethernet_component.cpp
> +  }
Resolved in commit [92fa95d](https://github.com/esphome/esphome/pull/7503/commits/92fa95d180eb749d7680cb3d5faaf567312ebf8a).

2024-10-24 12:30 UTC, slakichi commented on esphome/components/ethernet/ethernet_component.cpp
> +
Resolved in commit [92fa95d](https://github.com/esphome/esphome/pull/7503/commits/92fa95d180eb749d7680cb3d5faaf567312ebf8a).

2024-10-24 12:30 UTC, slakichi commented on esphome/components/ethernet/__init__.py
>          if CONF_RESET_PIN in config:
Resolved in commit [ce22b44](https://github.com/esphome/esphome/pull/7503/commits/ce22b4438cb693c4f09998e988548aa2fd93fb2b).

2024-10-25 00:19 UTC, slakichi commented
- [x] Check review comments and apply to files
- [ ] Build firmware with latest code and run for a few days (started at 2024-10-24 21:13 +0900)
- [x] Make a PR for docs

2024-10-25 00:29 UTC, jesserockz commented on esphome/components/ethernet/__init__.py
> +    return True
The function is giving you a true/false if polling is supported, if not running a specific idf/arduino version, the answer is simply no/false =)

2024-10-25 00:31 UTC, jesserockz commented
https://esphome.io/guides/contributing#force-push

2024-10-25 00:36 UTC, jesserockz approved these changes

2024-10-25 07:23 UTC, ijc commented
FYI I've uploaded a new build from bc71786a0461622344a47dabf3f4af8eecd4716c to my system and it seems to be working well.

2024-10-27 01:12 UTC, slakichi commented
I built W5500+bluetooth_proxy with commit 162e521143d171e001694e0332b85a002d2d07a2, and I run for a few days and no issue occured.
I got warning about there are some uninitialized members in setup, and there may cause something unexpected  -- but ignored because there are out of scope for this PR. (will be fixed by small bugfix PR)

```
src/esphome/components/ethernet/ethernet_component.cpp: In member function 'virtual void esphome::ethernet::EthernetComponent::setup()':
src/esphome/components/ethernet/ethernet_component.cpp:66:3: warning: missing initializer for member 'spi_bus_config_t::isr_cpu_id' [-Wmissing-field-initializers]
src/esphome/components/ethernet/ethernet_component.cpp:107:3: warning: missing initializer for member 'spi_device_interface_config_t::clock_source' [-Wmissing-field-initializers]
```

2024-10-27 07:11 UTC, ijc commented
> I got warning about there are some uninitialized members in setup

FWIW I saw these too.

I think they are due to the non-default version of esp-idf and/or platform I/O and not directly related to this PR (other than it requiring the non-default version).

2024-10-29 03:08 UTC, merged