TCS34725: add accurate sensor saturation; remove clear channel
OttoWinter/esphomeyaml pull request #7508
Opened 2024-09-29 08:19 UTC by RubenKelevra

This PR contains two commits which are filed seperately as PR #7492 and PR #7494, which need to be merged first.

# What does this implement/fix?

### What Has Changed?

1. **Removal of Clear Channel Handling:**
   - The `clear_channel` attribute and associated code have been removed from the `TCS34725Component`.
   - The `calculate_temperature_and_lux_` function has been modified to no longer use or handle the clear channel (`c`) as an input parameter.
   - `clear_channel` related sensor configuration and data handling have been replaced with the newly introduced `sensor_saturation`.

2. **Introduction of Sensor Saturation:**
   - The `sensor_saturation` attribute has been added to provide a direct representation of sensor saturation, making it more informative.
   - This value is now logged and used to determine if samples should be discarded or used, based on specified saturation thresholds.

3. **Adjustment of Saturation and Minimum Raw Value Handling:**
   - The code now uses the maximum of the RGB channels (`peak_raw_value`) to calculate saturation instead of relying on the clear channel.
   - As the clear channel is no longer used, we now use the minimum raw value (`min_raw_value`) of R, G, B to determining underexposure conditions. The minimum raw value of 5 is used in accordance to the spec sheet, to avoid sensor noise on very low light conditions. In other circumstances, 1 is used.

4. **Dynamic Range Improvement:**
   - By removing the dependency on the clear channel, the overall dynamic range of the sensor has been increased by approximately 73%.
   - This is achieved by relying solely on the RGB channels, which prevents the clear channel from prematurely limiting the sensor’s range due to overexposure.

5. **Test Updates:**
   - Test configuration files have been updated to reflect the removal of the `clear_channel` and the addition of `sensor_saturation`.
   - All relevant test cases and configurations have been adapted to the new attribute and its handling.

# Rationale

It may be counterintuitive at the first glance, but removing the clear channel improves this sensor's output:

The clear channel is a sum of the spectrum of the R, G, B channels. Meaning, it's value is also a sum. The clear channel therefore will overexpose long before the R, G, B channels will. This is artificially reducing the capabilities of this sensor, as the R, G, B channels are all we really need for color, color temperature and lux calculations.

The clear channel is also absolutely not useful for any purpose, as its response curve is quite similar to the R, G, B channel ones, but cannot be corrected, as it's a sum. So a user can just sum up the R, G, B channels, to get to the clear channel's output, if there's a need for this value.

Removing the clear channel gives us around 73% more dynamic range, with no downsides.

# Limits of this PR

As I was asked to keep the PRs small, this PR will break color calculations. The color calculation will be added back in the next PR. So this is not meant to be released on its own, but together with the next PR. 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
<details>

```yaml
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini
  friendly_name: $friendly_name

substitutions:
  devicename: ambient-light-sensor
  friendly_name: "Ambient Light Sensor"

logger:
  level: DEBUG

mdns:
  
time:
  - platform: homeassistant

api:
  encryption: 
    key: !secret api_key-ambient-light-sensor

ota:
  platform: esphome
  password: !secret ota_password_ambient-light-sensor

wifi:
  networks:
    ssid: !secret wifi_ssid
    password: !secret wifi_password
    manual_ip:
      static_ip: !secret ip-ambient-light-sensor
      gateway: !secret wifi_gateway
      subnet: !secret wifi_subnet
      dns1: !secret wifi_dns1

i2c:
  sda: D1
  scl: D2
  scan: true
  id: bus_a

sensor:
  - platform: tcs34725
    i2c_id: bus_a
    red_channel:
      name: "$friendly_name Red Channel relative"
      accuracy_decimals: 1
    green_channel:
      name: "$friendly_name Green Channel relative"
      accuracy_decimals: 1
    blue_channel:
      name: "$friendly_name Blue Channel relative"
      accuracy_decimals: 1
    sensor_saturation:
      name: "$friendly_name Sensor Saturation"
      accuracy_decimals: 1
    illuminance:
      name: "$friendly_name Illuminance"
      accuracy_decimals: 0
    color_temperature:
      name: "$friendly_name Color Temperature"
      accuracy_decimals: 0
    gain: 1x
    integration_time: auto
    glass_attenuation_factor: 1.0
    address: 0x29   

output:
  - platform: gpio
    pin: D3
    id: white_led
    inverted: false
  
light:
  - platform: binary
    output: white_led
    name: "$friendly_name White LED"
```

</details>

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs). ([PR 4288](https://github.com/esphome/esphome-docs/pull/4288))

2024-09-29 08:26 UTC, RubenKelevra commented
Sorry, git messed up the rebase of the commits made in the meantime in `dev` that's why the bot added the wrong tags/mentioned the wrong people.

2024-09-29 08:44 UTC, RubenKelevra commented
@jesserockz quick question: My next PR has a sensor calibration file - derived from the spec sheet, and two scripts to calculate the sensor calibration based off of that.

As they may come handy on any other color sensor with calibration data in the specs, I was wondering if there's a place in the repo to put such stuff, or if I should publish it in a repo of my own?

2024-09-29 12:12 UTC, RubenKelevra commented
Clang-tidy complains about std::clamp() not existing, are we talking about pre-C++17 standard here? I mean the code compiles fine, so it does exist.

2024-10-03 07:30 UTC, RubenKelevra commented
I revised the "fix low light noisy output, where the color temperature will just flop up and down" fix, to be less stringent. It will now no longer ensure a minimum of 5 (raw value) but a minimum of 1, as the sensor seems to have less noise than anticipated by the spec sheet.

2024-10-06 22:47 UTC, jesserockz commented
> @jesserockz quick question: My next PR has a sensor calibration file - derived from the spec sheet, and two scripts to calculate the sensor calibration based off of that.
> 
> As they may come handy on any other color sensor with calibration data in the specs, I was wondering if there's a place in the repo to put such stuff, or if I should publish it in a repo of my own?

Your own repo would be a better place for this

2024-10-06 22:51 UTC, jesserockz requested changes

2024-10-06 22:51 UTC, jesserockz commented on esphome/components/tcs34725/sensor.py
> -            cv.Optional(CONF_CLEAR_CHANNEL): color_channel_schema,
Please leave the key there but with a value of `cv.invalid("Some short message explaining the removal")`

2024-10-06 22:51 UTC, jesserockz commented on esphome/components/tcs34725/tcs34725.cpp
> +  ESP_LOGD(TAG, "Raw values clear=%d red=%d green=%d blue=%d", raw_c, raw_r, raw_g, raw_b);
```suggestion
  ESP_LOGV(TAG, "Raw values clear=%d red=%d green=%d blue=%d", raw_c, raw_r, raw_g, raw_b);
```

2024-10-07 09:09 UTC, RubenKelevra commented
> > @jesserockz quick question: My next PR has a sensor calibration file - derived from the spec sheet, and two scripts to calculate the sensor calibration based off of that.
> > As they may come handy on any other color sensor with calibration data in the specs, I was wondering if there's a place in the repo to put such stuff, or if I should publish it in a repo of my own?
> 
> Your own repo would be a better place for this

Alright, then they stay at https://github.com/RubenKelevra/tcs34725-irradiance-correction

2024-10-08 19:48 UTC, swifty99 commented
Hey [@RubenKelevra](https://github.com/RubenKelevra),

thanks for improving this. Nice.

One comment on saturation:
the ga glass attenuation will lead to limited output too. I think the limit should be done on sensor information and not on the user provided glass attenuation. I use(d) a grey filter to not cap at super bright situations and the ga set accordingly.


The code here:
```
  // Lux Calculation (DN40 3.2)

  float g1 = R_COEF * (float) r + G_COEF * (float) g + B_COEF * (float) b;
  float cpl = (this->integration_time_ * this->gain_) / (ga * DF);

  this->illuminance_ = std::max(g1 / cpl, 0.0f);

  if (this->illuminance_ > MAX_ILLUMINANCE) {
    ESP_LOGW(TAG, "Calculated illuminance greater than limit (%f), setting to NAN", this->illuminance_);
    this->illuminance_ = NAN;
    return;
  }
```

I think it would be better to apply ga after the limitation.

2024-10-08 20:20 UTC, RubenKelevra commented
> Hey [@RubenKelevra](https://github.com/RubenKelevra),
> 
> thanks for improving this. Nice.
> 
> One comment on saturation: the ga glass attenuation will lead to limited output too. I think the limit should be done on sensor information and not on the user provided glass attenuation. I use(d) a grey filter to not cap at super bright situations and the ga set accordingly.
> 
> The code here:
> 
> ```
>   // Lux Calculation (DN40 3.2)
> 
>   float g1 = R_COEF * (float) r + G_COEF * (float) g + B_COEF * (float) b;
>   float cpl = (this->integration_time_ * this->gain_) / (ga * DF);
> 
>   this->illuminance_ = std::max(g1 / cpl, 0.0f);
> 
>   if (this->illuminance_ > MAX_ILLUMINANCE) {
>     ESP_LOGW(TAG, "Calculated illuminance greater than limit (%f), setting to NAN", this->illuminance_);
>     this->illuminance_ = NAN;
>     return;
>   }
> ```
> 
> I think it would be better to apply ga after the limitation.

Yeah, makes sense. But I think that's better put into a new PR, so I can test the change individually. 

For this PR it maybe makes sense to raise the limit to 200,000 lux in the meantime, to not cap it?

I just want to avoid putting inf lux out, which we did before.

2024-10-09 18:59 UTC, RubenKelevra commented
@swifty99 temporary fix has been added here.

Permanent fix is in PR#7574

2024-10-11 15:43 UTC, swifty99 approved these changes
Looks good to me. Nice work.

2024-10-11 15:43 UTC, swifty99 commented on esphome/components/tcs34725/tcs34725.cpp
>      // increase gain if less than 20% of white channel used and high integration time
maybe this comment should reflect the new behavior

2024-10-11 16:28 UTC, RubenKelevra commented on esphome/components/tcs34725/tcs34725.cpp
>      // increase gain if less than 20% of white channel used and high integration time
Sorry which comment?

2024-10-11 16:41 UTC, RubenKelevra commented on esphome/components/tcs34725/tcs34725.cpp
>      // increase gain if less than 20% of white channel used and high integration time
yeah, I went over some of the code comments. Thanks!

2024-10-15 14:12 UTC, swifty99 commented
I have this running since a few days. Found no trouble.

2024-10-15 23:24 UTC, RubenKelevra commented
@swifty99 thanks for your confirmation!

2024-12-18 18:50 UTC, RubenKelevra commented
@jesserockz can you please take another look? Thanks!

2025-10-26 11:31 UTC, swifty99 commented
what a bummer. So much effort put into this.

2026-02-01 01:01 UTC, closed without merging