Add support for Maxim MAX17043 battery gauge
OttoWinter/esphomeyaml pull request #7522
Opened 2024-10-01 21:02 UTC by blacknell

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-06 22:46 UTC, jesserockz requested changes

2024-10-06 22:46 UTC, jesserockz commented on esphome/components/max17043/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_BATTERY_VOLTAGE])
```suggestion
    if voltage_config := config.get(CONF_BATTERY_VOLTAGE):
        sens = await sensor.new_sensor(voltage_config)
```

2024-10-06 22:46 UTC, jesserockz commented on esphome/components/max17043/max17043.cpp
> +    this->voltage_sensor_->publish_state(voltage);
If the user does not have one of these sensors configured, this component should not even request the data for it.

2024-10-06 22:46 UTC, jesserockz commented on esphome/components/max17043/max17043.cpp
> +  ESP_LOGCONFIG(TAG, "  Percent: %s", this->battery_remaining_sensor_->get_name().c_str());
```suggestion
  LOG_SENSOR("  ", "Battery Voltage", this->voltage_sensor_);
  LOG_SENSOR("  ", "Battery Level", this->battery_remaining_sensor_);
```

2024-10-07 05:35 UTC, blacknell commented on esphome/components/max17043/max17043.cpp
> +    this->voltage_sensor_->publish_state(voltage);
Ok. Thanks (the disadvantage of picking the wrong component to crib!)

2024-10-11 07:53 UTC, kbx81 commented on esphome/components/max17043/max17043.cpp
> +  ESP_LOGD(TAG, "MAX17043 CONFIG register reads 0x%X", config_reg);
For messages like this, they're usually verbose or higher
```suggestion
  ESP_LOGV(TAG, "MAX17043 CONFIG register reads 0x%X", config_reg);
```

2024-10-11 08:21 UTC, kbx81 commented on esphome/components/max17043/sensor.py
> +    return cg.new_Pvariable(action_id, template_arg, paren)
It looks like you built out a `sleep_mode` action here but didn't build the corresponding class to implement the automation on the C++ side.

2024-10-11 08:27 UTC, blacknell commented on esphome/components/max17043/sensor.py
> +    return cg.new_Pvariable(action_id, template_arg, paren)
The sleep mode code is in

```C++
void MAX17043Component::sleep_mode() {
  if (!this->is_failed()) {
    if (!this->write_byte_16(MAX17043_CONFIG, MAX17043_CONFIG_POWER_UP_DEFAULT | MAX17043_CONFIG_SLEEP_MASK)) {
      ESP_LOGW(TAG, "Unable to write the sleep bit to config register");
      this->status_set_warning();
    }
  }
}
```

2024-10-11 08:45 UTC, kbx81 commented on esphome/components/max17043/sensor.py
> +    return cg.new_Pvariable(action_id, template_arg, paren)
Take a look at how DFPlayer implements its sleep action -- you can more or less just copy this & update the method names.
- https://github.com/esphome/esphome/blob/cedb671f075dc2ceb9c3e5f01c0e74268312a4e7/esphome/components/dfplayer/dfplayer.h#L109-L115
- https://github.com/esphome/esphome/blob/cedb671f075dc2ceb9c3e5f01c0e74268312a4e7/esphome/components/dfplayer/dfplayer.h#L194

For your case, I'd get rid of the macro since you have only a single action here.
Please put it into an `automation.h` file, like [this](https://github.com/esphome/esphome/blob/dev/esphome/components/button/automation.h).

2024-10-12 09:47 UTC, kbx81 commented
Looking great! 🍻
Last request: could you add the new action to the tests? Just do something like [this](https://github.com/esphome/esphome/blob/efe4c5e3bc496d9f1f4d152c28a27e505b9f3024/tests/components/aic3204/common.yaml#L1-L4).

2024-10-13 00:14 UTC, kbx81 approved these changes

2024-10-16 03:28 UTC, jesserockz approved these changes

2024-10-16 03:28 UTC, merged