update rc5 decode, include toggle
OttoWinter/esphomeyaml pull request #7532
Opened 2024-10-03 02:04 UTC by juanboro

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-12-26 15:27 UTC, juanboro commented
@LukasK13  - any comments?

2024-12-26 21:21 UTC, LukasK13 commented
@juanboro unfortunately I no longer have a set up with a IR remote controller so I am unable to test your changes. However, I can confirm that I encountered similar issues as you did, so I think it's great that you implemented a fix for the RC5 decoding. Ultimately, a reviewer will have to decide but your fix looks good to me.

2024-12-28 14:37 UTC, juanboro commented
Anyone know how to request a review?

2025-05-26 01:49 UTC, jesserockz requested changes

2025-05-26 01:49 UTC, jesserockz commented on esphome/components/remote_base/rc5_protocol.h
> +  uint8_t toggle;
Apologies for the delay, should this just be a `bool` instead of `uint8_t`?
```suggestion
  bool toggle;
```

2025-05-26 01:49 UTC, jesserockz commented on tests/components/remote_receiver/common-actions.yaml
> +        args: ["x.address", "x.command", "x.toggle"]
```suggestion
        format: "on_rc5: %u %u %s"
        args: ["x.address", "x.command", "YESNO(x.toggle)"]
```

2025-05-26 01:49 UTC, jesserockz commented on esphome/components/remote_base/rc5_protocol.cpp
> +  ESP_LOGI(TAG, "Received RC5: address=0x%02X, command=0x%02X, toggle=0x%02X", data.address, data.command, data.toggle);
```suggestion
  ESP_LOGI(TAG, "Received RC5: address=0x%02X, command=0x%02X, toggle=%s", data.address, data.command, YESNO(data.toggle));
```

2025-05-26 01:49 UTC, jesserockz commented on esphome/components/remote_base/rc5_protocol.cpp
> +      .toggle = 0,
```suggestion
      .toggle = false,
```

2025-05-26 22:37 UTC, juanboro commented
Agree having toggle bool makes alot more sense.  I _think_ the reason I made it uint8_t before was because I saw toggle implemented as uint8_t in rc6_protocol so I made it the same to be consistent with that.

2026-03-27 20:54 UTC, kinnison commented
I ran into this problem today as well.  I've not had a chance to execute the replacement code, but the approach looks like it'd decode the recorded codes I have much better than the existing code.

This PR desperately needs to be rebased properly though, it has 119 commits on it :(

2026-03-27 20:56 UTC, kinnison commented
Just in case they're useful, here's two raw dumps from my remote control, the first a non-extended code (supposedly 19:12):

`937, -848, 1784, -1814, 1756, -910, 873, -1821, 873, -914, 1754, -908, 873, -1806, 874, -913, 1755, -907, 873`

And the second, an extended code (supposedly 19:122):

`1781, -1819, 872, -914, 1754, -908, 873, -1807, 874, -911, 873, -915, 872, -915, 871, -913, 1754, -1819, 1753`

2026-03-27 21:42 UTC, juanboro commented
yeah - I'll update my tests and rebase hopefully sometime this weekend or next week.  I only have one real remote that does RC5 and I normally only use it with my raspberry PI media center and not anything on ESPHome based - so have to move things around to do real testing.

2026-06-03 23:13 UTC, closed without merging

2026-06-03 23:13 UTC, juanboro commented
Superseded by: https://github.com/esphome/esphome/pull/16767