lps22: add a component
OttoWinter/esphomeyaml pull request #7540
Opened 2024-10-04 18:13 UTC by nagisa

# What does this implement/fix?

LPS22HB/HH is a barometric pressure sensor. It has pretty high accuracy, is somewhat less prone to hallucinating weird measurements compared to competing chips and is reasonably widely available for purchase.

This adds a very basic one-shot based implementation for interacting with this sensor over an I2C bus. The chip also supports communication over SPI, but I don't have the means to test such configuration (for my PCB is baked for I2C) as well as measuring the conditions in a automatic mode. These are left as future extensions to the basic implementation seen here.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** N/S

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
  * tested with real hw
- [x] ESP32 IDF
  * tested with real hw
- [x] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sensors:
  - platform: lps22
    temperature:
      name: "LPS22 Temperature"
    pressure:
      name: "LPS22 Pressure"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-15 02:46 UTC, jesserockz requested changes

2024-10-15 02:46 UTC, jesserockz commented on esphome/components/lps22/lps22.cpp
> +  }
This should be in `setup()` and also call `this->mark_failed()` if the device is wrong.

2024-10-15 02:46 UTC, jesserockz commented on esphome/components/lps22/lps22.cpp
> +static constexpr float TEMPERATURE_SCALE = 0.01;
```suggestion
static constexpr float PRESSURE_SCALE = 1.0f / 4096.0f;
static constexpr float TEMPERATURE_SCALE = 0.01f;
```

2024-10-15 02:46 UTC, jesserockz commented on esphome/components/lps22/lps22.cpp
> +  this->temperature_sensor_->publish_state(temp);
```suggestion
  if(this->temperature_sensor_ != nullptr) {
    uint8_t t_buf[2]{0};
    this->read_register(TEMP_L, t_buf, 2);
    float temp =
        TEMPERATURE_SCALE * static_cast<float>(encode_uint16(t_buf[1], t_buf[0]));
    this->temperature_sensor_->publish_state(temp);
  }
```

2024-10-15 02:46 UTC, jesserockz commented on esphome/components/lps22/lps22.cpp
> +  this->pressure_sensor_->publish_state(PRESSURE_SCALE * static_cast<float>(p_lsb));
```suggestion
  if (this->pressure_sensor_ != nullptr) {
    uint8_t p_buf[3]{0};
    this->read_register(PRES_OUT_XL, p_buf, 3);
    uint32_t p_lsb = encode_uint24(p_buf[2], p_buf[1], p_buf[0]);
    this->pressure_sensor_->publish_state(PRESSURE_SCALE * static_cast<float>(p_lsb));
  }
```

2024-10-15 02:46 UTC, jesserockz commented on esphome/components/lps22/lps22.cpp
> +void LPS22Component::dump_config() { LOG_I2C_DEVICE(this); }
```suggestion
void LPS22Component::dump_config() {
  ESP_LOGCONFIG(TAG, "LPS22:");
  LOG_SENSOR("  ", "Temperature", this->temperature_sensor_);
  LOG_SENSOR("  ", "Pressure", this->pressure_sensor_);
  LOG_I2C_DEVICE(this);
  LOG_UPDATE_INTERVAL(this);
}
```

2024-10-15 02:46 UTC, jesserockz commented on esphome/components/lps22/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_TEMPERATURE])
```suggestion
    if temperature_config := config.get(CONF_TEMPERATURE):
        sens = await sensor.new_sensor(temperature_config)
```

2024-10-15 02:46 UTC, jesserockz commented on esphome/components/lps22/sensor.py
> +        sens = await sensor.new_sensor(config[CONF_PRESSURE])
```suggestion
    if pressure_config := config.get(CONF_PRESSURE):
        sens = await sensor.new_sensor(pressure_config)
```

2024-10-15 02:46 UTC, jesserockz commented on esphome/components/lps22/lps22.h
> + private:
We avoid private when not necessary
```suggestion
```

2024-10-15 02:46 UTC, jesserockz commented on esphome/components/lps22/lps22.h
> +  void set_pressure_sensor(sensor::Sensor *pressure_sensor) { pressure_sensor_ = pressure_sensor; }
```suggestion
  void set_temperature_sensor(sensor::Sensor *temperature_sensor) { this->temperature_sensor_ = temperature_sensor; }
  void set_pressure_sensor(sensor::Sensor *pressure_sensor) { this->pressure_sensor_ = pressure_sensor; }
```

2024-10-15 02:46 UTC, jesserockz commented on esphome/components/lps22/lps22.h
> +  LPS22Component() : PollingComponent(15000) {}
Not needed
```suggestion
```

2024-10-15 14:25 UTC, nagisa commented on esphome/components/lps22/lps22.cpp
> +  }
Seems to work well. Thank you!

2024-10-15 14:25 UTC, nagisa commented
Thank you very much for the thorough review. The code seems much nicer now!

2024-11-24 23:58 UTC, jesserockz commented
> Thank you very much for the thorough review. The code seems much nicer now! Let me know if you want me to squash commits or anything else.

https://esphome.io/guides/contributing#force-push

2025-07-08 20:42 UTC, jesserockz approved these changes

2025-07-08 21:13 UTC, merged