api: ensure fair network sharing + prevent lost state changes via deferred publish at high event load
OttoWinter/esphomeyaml pull request #7547
Opened 2024-10-06 05:16 UTC by nkinnan

# What does this implement/fix?

If the API buffer is full, instead of dropping messages, put them in a deferred send queue.  Once there is buffer space, the latest state from the component that missed it's update will be sent.  This means api clients will always have an up to date view of device state and can never get out of sync.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-06 18:41 UTC, edwardtfn commented
How are you simulating the "high event load" on your tests? I woukd love to try it with `esp-idf` as I already have a project where I suspect the api must be overloaded at some moments and woukd be nice to give this PR a try, but testing in the same way you are testing esp32 arduino and esp8266 would be nice.

2024-10-09 14:22 UTC, martijnbuts commented
Is it possible to test this as a external component?

2024-10-15 03:00 UTC, jesserockz requested changes, later dismissed
These file changes stuck out when I opened this PR. Have not looked at the actual changes yet.

2024-10-15 03:00 UTC, jesserockz commented on esphome/components/event/event.h
> +  const std::string *state;
If anything, the event entity should expose the same state as they do in HA, which is the timestamp it was last triggered.

If you want to continue adding a state to event, please do it in its own PR.

2024-10-15 03:00 UTC, jesserockz commented on esphome/core/defines.h
> +//#define USE_ESP32_CAMERA
?
https://github.com/esphome/esphome/blob/2cca26ada4f8c4525f1009b3e40f69e0f0675796/esphome/core/defines.h#L103

2024-10-15 05:06 UTC, nkinnan commented on esphome/core/defines.h
> +//#define USE_ESP32_CAMERA
I believe this file simply calls out defines to that things aren't "greyed out" in the editor, they don't actually do anything do they?  I needed camera defined but it also causes some other irrelevant "build warnings" in the editor I didn't bother tracking down, so I commented it.

2024-10-15 05:40 UTC, ssieb commented on esphome/components/event/event.h
> +  const std::string *state;
`state` is probably the wrong name to use here.  It's a place to store the last event name so that the publishers can use it if it gets deferred.

2024-10-15 05:52 UTC, nkinnan commented on esphome/components/event/event.h
> +  const std::string *state;
This is required to defer publishing of the event - the API component requires the event string in order to dispatch the event to HA (or other subscribers).

2024-10-15 06:07 UTC, nkinnan commented
> How are you simulating the "high event load" on your tests? I woukd love to try it with `esp-idf` as I already have a project where I suspect the api must be overloaded at some moments and woukd be nice to give this PR a try, but testing in the same way you are testing esp32 arduino and esp8266 would be nice.

I've added a stress test YAML to the main comment.  It will publish 100 sensors in a single loop() once per second.  I tested by instrumenting the API component with some log printfs so I could observe the deferred queue increasing and decreasing in length.  Sensor publishes only defer occasionally.  Let me know if you find anything interesting!

2024-10-15 06:10 UTC, nkinnan commented
> Is it possible to test this as a external component? I have a ESP32-S3 with a lot of sensors and sometimes the API connection get lost and restore after around a second but the esp32 itself keeps running.

@martijnbuts The example YAML included in the main comment uses this as an external component.  But this won't help with the API connection getting lost/restored unless you see problems with the state reported to HA getting out of sync with "reality" due to dropped state publish events.  This change addresses that by saving for later any sensor publishes that would otherwise have been dropped, and simply sending the latest value (eventually, when there is spare bandwidth).  In any case, let me know if you try this and find anything interesting!

2024-10-17 05:42 UTC, nohat commented on esphome/components/event/event.h
> +  const std::string *state;
If I'm understanding correctly, when multiple events are published using the same Event entity with different `event_types`, and the API queue fills up, the current behavior is that new events get dropped until the queue is drained. With this change, it appears that when the queue recovers, at most one additional event will be sent out. If multiple events are published during this saturation period, only the last one will get processed and sent.

While this does represent an improvement over the current behavior—since at least one event will be preserved during queue saturation—it still results in events being lost. I’m not entirely sure how many real-world use cases for Event entities would significantly benefit from this change. Given that this solution introduces a new state-storing member to the previously stateless Event class, is the marginal improvement worth the added complexity? It might be more beneficial to address the underlying issue more comprehensively, ensuring no events are lost under these circumstances.

2024-10-17 16:46 UTC, nkinnan commented on esphome/components/event/event.h
> +  const std::string *state;
Currently event is treated the same as any other state, and this issue is not related only to events.  If there is a scalar value that can increase/decrease and is accumulated HA-side, the dropped events while the tcp buffer is full will also result in accumulation error.  But at least the latest state (last event or most recent value or last/most recent whatever) will be sent which is an improvement.  This is particularly important for things like switches where (potentially a series of) on/off events may be lost but at least at the end HA and other listeners will have the last/current state and not remain out of sync indefinitely (or until the device reboots/reconnects and re-dumps all sensors).

It would be only a couple lines change to accumulate *all* lost events/states/whatevers but memory is limited.  The deduplication is done purposefully and special care was taken to minimize memory usage down to only 8 bytes per deferred event/state/whatever.  These 8 bytes are stored in a vector which has zero overhead and doesn't even reference anything else on the heap, the saved state is "inline" to the vector even though popping the front of a vector is O(n) because keeping memory usage down is more important.

In the future if someone wants to add a special case for events or whatever else to allow them to accumulate state without limit they are certainly able to do so, but it will increase memory usage per deferred update for multiple reasons we could discuss and potentially allows the state buffer to grow without constraint (or adding a constraint per source will increase memory usage per stored deferred update even more).  A lot of thought has gone into this and the current design seems to be the best compromise and is a significant improvement over current behavior.

2024-10-17 16:50 UTC, nkinnan commented on esphome/components/event/event.h
> +  const std::string *state;
additional discussion (please join in if you like): https://discord.com/channels/429907082951524364/1278449170734125149

2024-12-23 02:31 UTC, nkinnan commented
Can we get some eyes on this?  I think it is an important and valuable change that improves the reliability of the communications protocol and prevents out of date values in HA + device webserver.  The design was suggested by ssieb.

2025-01-13 19:10 UTC, bkbartk commented
I had 1 esp-idf device where the state wasn't updating always correctly.
after applying this PR I haven't found any updated statuses anymore.
so far for me this one seems to fix the issue.

2025-01-13 21:21 UTC, jeroen85 commented
Same here with a modbus sniffer with high sensor update frequency. Working well.
Please merge

2025-01-13 21:46 UTC, nkinnan commented
Thank you @bkbartk and @jeroen85 for confirming.  I will try poking the NC devs again to see if we can get some forward movement on this.  Many of them were unavailable over the holidays.

2025-01-14 13:53 UTC, shvmm commented
Flashed my Home Solar ESPHome JK-BMS setup as well.

2025-01-15 02:40 UTC, jesserockz commented on esphome/components/event/event.h
> +  const std::string *state;
All I wanted was #8088 :wink:

2025-02-20 09:30 UTC, iay commented
Per https://github.com/EverythingSmartHome/everything-presence-lite/issues/304 it looks like this PR is not compatible with the ESPHome 2025.2 release.

2025-02-20 17:04 UTC, nkinnan commented
> Per [EverythingSmartHome/everything-presence-lite#304](https://github.com/EverythingSmartHome/everything-presence-lite/issues/304) it looks like this PR is not compatible with the ESPHome 2025.2 release.

I don't understand what you mean.  The referenced PR seems unrelated and the CI tests for this PR are passing.  What is the specific issue?

2025-02-20 17:42 UTC, iay commented
>I don't understand what you mean. The referenced PR seems unrelated and the CI tests for this PR are passing. What is the specific issue?

@nkinnan I believe the issue is that this PR did not include some of the changes that were introduced into the `api` component in 2025.2, and which are required by other components. I think the merge you've just done will probably fix that, but I haven't been able to check that yet.

2025-02-20 17:48 UTC, iay commented
Can confirm, that other project is now compiling and running again under 2025.2. Thanks for the update.

2025-02-20 17:54 UTC, nkinnan commented
> Can confirm, that other project is now compiling and running again under 2025.2. Thanks for the update.

I can try to check back and click that button regularly, but it'd really be great if they could actually merge this thing into dev... :/

2025-02-20 17:58 UTC, iay commented
>it'd really be great if they could actually merge this thing into dev...

It really would. Or, you know, solved the problem some other way, that would be fine too.

Thanks for this work, by the way. It really makes a difference for chatty sensors.

2025-02-20 18:12 UTC, bkbartk commented
> > Can confirm, that other project is now compiling and running again under 2025.2. Thanks for the update.
> 
> I can try to check back and click that button regularly, but it'd really be great if they could actually merge this thing into dev... :/

I see there is a change requested by Jesse. I cannot see what the request is. But I assume that’s why they won’t merge.

2025-02-21 16:36 UTC, nkinnan commented
I give up.  If you want this and https://github.com/esphome/esphome/pull/7538 to go in, ask the devs: https://discord.com/channels/429907082951524364/524177279270780928

2025-02-21 17:32 UTC, Mosibi commented
Can any of the esphome devs step in and tell what should be done to get this one merged. @OttoWinter and/or @nohat ?

2025-02-21 17:50 UTC, nkinnan commented
> Can any of the esphome devs step in and tell what should be done to get this one merged. @OttoWinter and/or @nohat ?

ask the devs: https://discord.com/channels/429907082951524364/524177279270780928

2025-02-21 19:19 UTC, bkbartk commented
I do not have a discord account but I see @jesserockz has requested changes, but I cannot really find what they are,
Maybe Jesse can help out here?

2025-02-21 19:30 UTC, nkinnan commented
> I do not have a discord account but I see @jesserockz has requested changes, but I cannot really find what they are, Maybe Jesse can help out here?

Those changes are resolved. The message won't go away until he re-reviews. I have spent enormous amounts of time on this PR and https://github.com/esphome/esphome/pull/7538 - I can't keep following them forever. I am counting it as wasted effort at this point.

2025-02-21 19:54 UTC, craigwitter commented
I"ve never used discord, but opened a thread to try and help.
https://discord.com/channels/429907082951524364/524177279270780928/1342584660093571112



On Fri, Feb 21, 2025 at 12:32 PM Richard Arends ***@***.***>
wrote:

> Can any of the esphome devs step in and tell what should be done to get
> this one merged. @OttoWinter <https://github.com/OttoWinter> and/or @nohat
> <https://github.com/nohat> ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/7547#issuecomment-2675149281>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADDNYG4VS7Y33RBY45NFXZT2Q5PK5AVCNFSM6AAAAABPN7PZ4OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZVGE2DSMRYGE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
> [image: Mosibi]*Mosibi* left a comment (esphome/esphome#7547)
> <https://github.com/esphome/esphome/pull/7547#issuecomment-2675149281>
>
> Can any of the esphome devs step in and tell what should be done to get
> this one merged. @OttoWinter <https://github.com/OttoWinter> and/or @nohat
> <https://github.com/nohat> ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/7547#issuecomment-2675149281>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADDNYG4VS7Y33RBY45NFXZT2Q5PK5AVCNFSM6AAAAABPN7PZ4OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNZVGE2DSMRYGE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2025-02-22 08:43 UTC, nkinnan commented
@kbx81  Thank you.  https://github.com/esphome/esphome/pull/7538 has the same stale review issue for an identical comment.

2025-02-23 22:07 UTC, clydebarrow requested changes
Should the queue not be cleared in `APIConnection::on_fatal_error()`?

2025-02-23 22:07 UTC, clydebarrow commented on esphome/components/api/api_connection.cpp
> +  if (!APIConnection::try_send_binary_sensor_info(this, binary_sensor)) {
I don't think the `APIConnection::` is required here since the method is in the same namespace.

2025-02-23 22:34 UTC, jesserockz commented on esphome/components/api/api_connection.cpp
> +  if (!APIConnection::try_send_binary_sensor_info(this, binary_sensor)) {
I think I actually prefer the prefix here as it shows easily that it is a static function.

2025-02-24 03:49 UTC, nkinnan commented
> Should the queue not be cleared in `APIConnection::on_fatal_error()`?

I am unable to find this comment in the code view.  If the purpose of on_fatal_error is to mark the connection for teardown then I don't see the issue.  Since std::vector is used, there is no memory leak concern.  Would emptying the queue early serve any additional purpose?

2025-02-24 22:57 UTC, clydebarrow commented
> If the purpose of on_fatal_error is to mark the connection for teardown then I don't see the issue. Since std::vector is used, there is no memory leak concern. Would emptying the queue early have any additional benefit?

More broadly, should stuff even be in the queue if the API connection is not in place? If it is then when a connection is established there will be a burst of data sent, which is probably not ideal in itself, and it may change the current behaviour where sensors (and appropriately configured binary sensors) are published automatically on API connect (at least that's my current understanding.)

2025-02-24 23:03 UTC, nkinnan commented
> > If the purpose of on_fatal_error is to mark the connection for teardown then I don't see the issue. Since std::vector is used, there is no memory leak concern. Would emptying the queue early have any additional benefit?
> 
> More broadly, should stuff even be in the queue if the API connection is not in place? If it is then when a connection is established there will be a burst of data sent, which is probably not ideal in itself, and it may change the current behaviour where sensors (and appropriately configured binary sensors) are published automatically on API connect (at least that's my current understanding.)

The sensors are initially published by the enumerator, one sensor per loop() to avoid overloading the connection (...mostly).  The queue doesn't change any of that existing behavior.  In fact it improves it in the case that initial burst is too much for the send buffers, the data is queued.  The entire point.  If sensors were published before the connection were established there would be far larger issues with the fundamental design outside of the scope of this change and there would be far worse sensor desync issues without this change.

2025-02-24 23:19 UTC, clydebarrow approved these changes

2025-02-24 23:20 UTC, merged

2025-02-24 23:26 UTC, nkinnan commented
Thank you.  If you have time to also take a look at https://github.com/esphome/esphome/pull/7538 it is a sister PR making the same improvement to the device webserver.