Add: Seeed Studio mr60fda2 and mr60bha2 mmwave sensor
OttoWinter/esphomeyaml pull request #7576
Opened 2024-10-10 02:58 UTC by limengdu

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-10 03:05 UTC, jesserockz requested changes
Please only add 1 new component per PR

2024-10-22 02:35 UTC, jesserockz requested changes

2024-10-22 02:35 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +}
We have a helper function for this already (kind of)

https://github.com/esphome/esphome/blob/306fa914c517dbf9f8274fadc3b8cb77121df238/esphome/core/helpers.h#L210-L219

2024-10-22 02:35 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +           send_data[7], send_data[8], send_data[9], send_data[10], send_data[11], send_data[12]);
Please use V (verbose) logging for things like this. We also have a helper (`format_hex_pretty`) to convert arrays of data to hex strings
```suggestion
  ESP_LOGV(TAG, "SEND INSTALL HEIGHT FRAME: %s", format_hex_pretty(send_data, 13).c_str();
```

2024-10-22 02:35 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +          (static_cast<uint32_t>(current_data_buf_[1]) << 8) | static_cast<uint32_t>(current_data_buf_[0]);
We have a helper for this too (`encode_uint32`) :wink: 
```suggestion
      this->current_install_height_int_ = encode_uint32(current_data_buf_[3], current_data_buf_[2], current_data_buf_[1], current_data_buf_[0]);
```

2024-10-22 02:35 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.h
> +  uint8_t select_index_;
These are only used in one place, they dont need to be member variables
```suggestion
```

2024-10-22 02:35 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +uint8_t MR60FDA2Component::calculate_checksum_(const uint8_t *data, size_t len) {
This doesn't need to be a member of the class and can be static outside it.
```suggestion
static uint8_t calculate_checksum(const uint8_t *data, size_t len) {
```

2024-10-22 02:35 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +}
These can both be static too

2024-10-22 02:35 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +      this->install_height_select_->publish_state(INSTALL_HEIGHT_STR[select_index_]);
You don't need `INSTALL_HEIGHT_STR` as you can get the string from the select itself
Same with `HEIGHT_THRESHOLD_STR` below

```suggestion
      this->install_height_select_->publish_state(this->install_height_select_.at(select_index_));
```

2024-10-23 03:50 UTC, jesserockz commented
https://esphome.io/guides/contributing#force-push

2024-10-23 04:37 UTC, Love4yzp commented
> https://esphome.io/guides/contributing#force-push

I apologize for the trouble caused by the force push. I didn’t realize it would have such an impact. I used force push because the rule failure was caused by a very minor issue, and I wanted to keep the commit history clean.

Should I make any necessary adjustments to restore the branch?

2024-10-23 06:04 UTC, jesserockz commented
No, please dont try to fix it anymore, it cant get better..haha
We dont care too much for commit history as PRs are squashed into a single commit when merged.

Please just keep it in mind for future PRs =)

2024-10-24 01:19 UTC, jesserockz requested changes

2024-10-24 01:19 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/button/__init__.py
> +    cv.Optional(CONF_RESET_RADAR): button.button_schema(
I think to make this clearer, it should use `CONF_FACTORY_RESET`
```suggestion
    cv.Optional(CONF_FACTORY_RESET): button.button_schema(
```

2024-10-24 01:19 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/button/__init__.py
> +    ),
What is the actual purpose of this button? Why would a user need to manually press a button just to fetch the parameters? Shouldnt the component be automatically doing this as a oint in time when it needs to do it?

2024-10-24 01:19 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/select/__init__.py
> +        icon="mdi:axis-z-arrow",
```suggestion
        icon=ICON_ACCELERATION_Z,
```

2024-10-24 01:19 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/select/__init__.py
> +        icon="mdi:axis-z-arrow",
```suggestion
        icon=ICON_ACCELERATION_Z,
```

2024-10-24 01:19 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +      //     this->current_data_buf_[9], this->current_data_buf_[10], this->current_data_buf_[11]);
No commented out code
```suggestion
```

2024-10-24 01:19 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +      this->install_height_select_->publish_state(this->install_height_select_->at(select_index_).value());
You need to check these are not nullptr otherwise if a user doesnt configure it, it will crash
```suggestion
      if (this->install_height_select_ != nullptr) {
        this->current_install_height_int_ =
          encode_uint32(current_data_buf_[3], current_data_buf_[2], current_data_buf_[1], current_data_buf_[0]);
        float install_height_float;
        memcpy(&install_height_float, &current_install_height_int_, sizeof(float));
        select_index_ = find_nearest_index(install_height_float, INSTALL_HEIGHT, 7);
        this->install_height_select_->publish_state(this->install_height_select_->at(select_index_).value());
      }
```

2024-10-24 01:19 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +      memcpy(&height_threshold_float, &current_height_threshold_int_, sizeof(float));
We have a helper for this
```suggestion
      float height_threshold_float = bit_cast<float>(current_height_threshold_int_);
```

2024-10-24 02:56 UTC, limengdu commented on esphome/components/seeed_mr60fda2/button/__init__.py
> +    ),
The radar does not actively report parameters that are set. We are concerned that in extreme cases where some configuration items may not be successful, the user can click on this Button to get the actual parameter values of the radar, which can be used to check that the configured information agrees with the parameters that the radar is currently working with.

2024-10-30 03:46 UTC, jesserockz requested changes

2024-10-30 03:46 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +  send_data[12] = calculate_checksum(data_frame, 4);
The entire `data_frame` array is not necessary
```suggestion
  float_to_bytes_(INSTALL_HEIGHT[index], &send_data[8]);
  send_data[12] = calculate_checksum(send_data + 8, 4);
```

2024-10-30 03:46 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +  float height_threshold_float = 0;
If these are only needed in one case, put them inside that case only. 
You can wrap the case body with `{}`

2024-10-30 03:46 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +        this->current_install_height_int_ =
This field can be local too

2024-10-30 03:46 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.h
> +  uint8_t select_index_;
^^

2024-10-30 22:48 UTC, jesserockz commented on esphome/components/seeed_mr60fda2/seeed_mr60fda2.cpp
> +  send_data[12] = calculate_checksum(data_frame, 4);
This same code is in multiple places 
I just dont always put the suggestions as it forces you the contributor to learn and check the rest of the code again.

2024-11-06 02:10 UTC, jesserockz approved these changes

2024-11-26 00:53 UTC, merged