[fix] ESP32-C6: internal temperature reporting
OttoWinter/esphomeyaml pull request #7579
Opened 2024-10-10 07:46 UTC by rvalitov

# What does this implement/fix?

ESP32-C6 does not report internal temperature. This PR fixes it.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/5687

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: bt-proxy
  friendly_name: Bluetooth Proxy
  platformio_options:
    board_build.flash_mode: dio 

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y

wifi:
  ssid: "secret"
  password: "secret"

sensor:
  - platform: internal_temperature
    id: esp_internal_temperature
    name: "Internal Temperature"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-13 20:09 UTC, jesserockz requested changes

2024-10-13 20:09 UTC, jesserockz commented on esphome/components/internal_temperature/internal_temperature.cpp
> +    "ESP32-C6 requires ESP IDF V5.1.0 or higher. See https://github.com/espressif/esp-idf?tab=readme-ov-file#esp-idf-release-and-soc-compatibility"
This doesn't belong here and has nothing to do with this sensor. The entire project won't compile if not using a high enough version.
```suggestion
```

2024-10-14 06:34 UTC, rvalitov commented on esphome/components/internal_temperature/internal_temperature.cpp
> +    "ESP32-C6 requires ESP IDF V5.1.0 or higher. See https://github.com/espressif/esp-idf?tab=readme-ov-file#esp-idf-release-and-soc-compatibility"
Thank you for the review! I just followed the style with and approach in the code for ESP-S3 where there's a check for ESP IDF version. Ok, if you think such check is not required for ESP32-C6, I remove it.

2024-10-14 09:34 UTC, Mat931 approved these changes

2024-10-14 17:59 UTC, jesserockz approved these changes

2024-10-14 17:59 UTC, merged