[fix] ESP32-C6 BLE compile error
OttoWinter/esphomeyaml pull request #7580
Opened 2024-10-10 08:04 UTC by rvalitov

# What does this implement/fix?
Compilation error happens when trying to use `esp32_ble_tracker` or `bluetooth_proxy` with ESP32-C6.

Example if error message:
```
In file included from src/esphome/components/esp32_ble/ble.cpp:6:
src/esphome/components/esp32_ble/const_esp32c6.h:62:1: error: 'const esp_bt_controller_config_t' has no non-static data member named 'enable_uart_hci'
   62 | };
      | ^
Compiling .pioenvs/camerettasensor-5cf4ec/src/esphome/components/esp32_ble_client/ble_characteristic.cpp.o
*** [.pioenvs/camerettasensor-5cf4ec/src/esphome/components/esp32_ble/ble.cpp.o] Error 1
```

This happens because of some data members in file `const_esp32c6.h` that should not be there in component `esp32_ble`. This PR fixes this issue and removes all such members causing the compilation error. After that the ESP32-C6 works perfectly as a Bluetooth proxy.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/6248

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: bt-proxy
  friendly_name: Bluetooth Proxy
  platformio_options:
    board_build.flash_mode: dio 

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y

wifi:
  ssid: "secret"
  password: "secret"

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
    continuous: false

bluetooth_proxy:
  active: true 
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-13 20:03 UTC, jesserockz requested changes
I have a test c6 that works with bluetooth_proxy just fine which is when I added this file and code. 
If those fields dont exist with your config, then its because they were removed in a newer esp-idf version, which will need to be handled correctly with preproccesing

2024-10-14 07:50 UTC, rvalitov commented
Thank you for the review! I checked the ESP IDF code and fount out that some fields have been removed and some have been added since version 5.3.1 with commit https://github.com/espressif/esp-idf/commit/e761c1de8f9c0777829d597b4d5a33bb070a30a8
I applied a check for the ESP IDF version. Is it OK?

2024-10-14 19:40 UTC, jesserockz requested changes

2024-10-14 19:40 UTC, jesserockz commented on esphome/components/esp32_ble/const_esp32c6.h
> +#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 3, 1)
This field was added in 5.1.3
```suggestion
#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 1, 3)
```

2024-10-17 00:30 UTC, jesserockz approved these changes

2024-10-17 00:31 UTC, merged