chore: bump platformio and PyYAML to build with py3.13
OttoWinter/esphomeyaml pull request #7590
Opened 2024-10-12 02:30 UTC by chenrui333

bump platformio and PyYAML to build with py3.13

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

----

relates to https://github.com/Homebrew/homebrew-core/pull/193910

2024-10-13 18:55 UTC, jesserockz requested changes
Please bump PyYAML in its own PR

2024-10-16 03:48 UTC, chenrui333 commented
sounds good, will split it out then.

2024-10-16 03:51 UTC, chenrui333 commented
relates to https://github.com/Homebrew/homebrew-core/pull/194569

2024-10-16 04:26 UTC, jesserockz approved these changes

2024-10-16 04:26 UTC, merged