[axs15231] Touchscreen driver
OttoWinter/esphomeyaml pull request #7592
Opened 2024-10-12 11:21 UTC by clydebarrow

# What does this implement/fix?

Add support
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4334

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-12 18:19 UTC, xiasi0 commented
St77916 also uses QSPI protocol. We hope you can add it. Thank you 🙏

2024-10-13 01:46 UTC, clydebarrow commented
> St77916 also uses QSPI protocol. We hope you can add it. Thank you 🙏

See https://github.com/esphome/esphome-docs/pull/4335 - the CUSTOM model with an appropriate init sequence should work.

2024-10-14 01:23 UTC, jesserockz requested changes
A Couple of minor suggestions below, otherwise LGTM

2024-10-14 01:23 UTC, jesserockz commented on esphome/components/axs15231/touchscreen/axs15231_touchscreen.cpp
> +    delay(10);  // NOLINT
Not needed for only 10ms
```suggestion
    delay(10);
```

2024-10-14 01:23 UTC, jesserockz commented on esphome/components/axs15231/touchscreen/axs15231_touchscreen.cpp
> +}
Don't forget to clear previous warnings if it made it this far.
```suggestion
  this->status_clear_warning();
}
```

2024-10-17 00:35 UTC, jesserockz approved these changes

2024-10-17 00:44 UTC, merged