Add log level env var
OttoWinter/esphomeyaml pull request #7604
Opened 2024-10-14 20:15 UTC by briancw

# What does this implement/fix?
Adds a LOG_LEVEL environment variable for setting the log level on the dashboard.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-14 21:11 UTC, jesserockz requested changes

2024-10-14 21:11 UTC, jesserockz commented on esphome/dashboard/web_server.py
> +LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
I think we should prefix this
```suggestion
LOG_LEVEL = os.getenv("ESPHOME_LOG_LEVEL", "INFO").upper()
```

2024-10-14 21:47 UTC, briancw commented on esphome/dashboard/web_server.py
> +LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
Makes perfect sense to me

2024-10-14 22:41 UTC, jesserockz commented on esphome/dashboard/web_server.py
> +logging.getLogger().setLevel(LOG_LEVEL)
Just realised that this is probably not the correct file for this code. It should really be a part of `setup_log` in `esphome/log.py`

2024-10-14 23:09 UTC, briancw commented on esphome/dashboard/web_server.py
> +logging.getLogger().setLevel(LOG_LEVEL)
That makes sense. After diving in from there, I have a better idea of how logging is currently setup. Currently its not possible to set the log level to WARNING or ERROR.
Having both and environment variable and the existing flags would probably be somewhat confusing and overlapping. Would it be better to add new arguments, "-w", "--warning", "-e", "--error" to be able to target those log levels. Or to remove the existing "-q" and "-v" options and just have a single log level argument?

2024-10-14 23:19 UTC, briancw commented on esphome/dashboard/web_server.py
> +logging.getLogger().setLevel(LOG_LEVEL)
Personally I would opt for a single log level flag.

__main__.py
```suggestion
options_parser.add_argument(
    "-l",
    "--log-level",
    help="Set the log level.",
    default="INFO",
    action="store",
    choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
)
```

log.py
```suggestion
def setup_log(
    log_level = logging.INFO, include_timestamp: bool = False
) -> None:
    import colorama

    colorama.init()

    if log_level == logging.DEBUG:
        CORE.verbose = True
    elif log_level == logging.CRITICAL:
        CORE.quiet = True

    logging.basicConfig(level=log_level)

    logging.getLogger("urllib3").setLevel(logging.WARNING)

    logging.getLogger().handlers[0].setFormatter(
        ESPHomeLogFormatter(include_timestamp=include_timestamp)
    )
```

2024-10-15 15:23 UTC, ptr727 commented on esphome/dashboard/web_server.py
> +logging.getLogger().setLevel(LOG_LEVEL)
Will this replace or work with `ESPHOME_VERBOSE` that sets `--verbose`?

2024-10-15 18:32 UTC, briancw commented on esphome/dashboard/web_server.py
> +logging.getLogger().setLevel(LOG_LEVEL)
Having  single flag --log-level, and a single env var ESPHOME_LOG_LEVEL would be the most intuitive in my mind. But going the other direction would also work. Keep ESPHOME_VERBOSE and add ESPHOME_INFO ESPHOME_WARN ESPHOME_ERROR and ESPHOME_CRITICAL.

2024-10-15 18:45 UTC, ptr727 commented on esphome/dashboard/web_server.py
> +logging.getLogger().setLevel(LOG_LEVEL)
I'd vote for setting the log level, maybe retain `--verbose` as a verbose flag for CLI is pretty common, but `ESPHOME_VERBOSE` was just recently added, so disruptive but not the end of the world to deprecate. it in favor of a log level env.

2024-10-17 20:27 UTC, briancw commented on esphome/dashboard/web_server.py
> +logging.getLogger().setLevel(LOG_LEVEL)
I left the verbose and quiet flags in as well as the ESPHOME_VERBOSE env var so as to not be a breaking change. I added "--log-level" and "-l" as flags as well as the "ESPHOME_LOG_LEVEL" env var.

2025-01-12 10:04 UTC, WagnerSystems commented
Hello,
is there still work in progress here? I really would like to have such a feature.

2025-01-12 19:14 UTC, jesserockz approved these changes

2025-01-12 19:15 UTC, merged