[i2s_audio] I2S Speaker implementation using a ring buffer
OttoWinter/esphomeyaml pull request #7605
Opened 2024-10-14 21:16 UTC by kahrendt

# What does this implement/fix?

This is a near complete rewrite of the ``i2s_audio`` speaker component with improvements for simplification, stability, and supporting different audio sample rates and bits per sample. It adds to the ``speaker`` platform to support these new features while avoiding breaking changes. This requires the core audio struct added in #7585. Closes #7137, as this implements the core changes (the ESPHome ring buffer uses xStreamBuffers).

- Speaker platform supports writing audio with a FreeRTOS ``ticks_to_wait`` parameter for flexibility when using a separate task to write to the speaker.
- Speaker platform supports setting the volume with a new action. Each child speaker component needs to implement its own implementation.
  - The ``i2s_audio`` speaker component implements this in software.
- Transfers all audio data via a ring buffer instead of using a FreeRTOS queue.
  - The ring buffer deallocates when stopping, so there isn't an increase in memory use when idle.
- Uses a FreeRTOS Event Group for communicating between the speaker task and the main loop.
  - Simplifies the state and error reporting and commands.
  - Used to lock writing to the ring buffer, as FreeRTOS Stream buffers should only have 1 task writing at a time. Also ensures the task doesn't deallocate the ring buffer while a write is in progress.
  - Implements the existing stop logic: ``stop()`` ends it immediately, ``finish()`` ends the task after the ring buffer is emptied, and it will end the task with the configured timeout if no audio has been read after that time.
- Increases the default timeout to 500 ms to avoid occasional issues with delayed TTS responses.
- Simplifies the logic for writing to the I2S bus. 
  - Uses ``i2s_write_expand`` for converting between lower bits per sample to higher bits per sample.
  - Uses ``i2s_set_clk`` for handling mono and stereo audio
- Adds support for reconfiguring the I2S settings by the component sending audio with the ``set_audio_stream_info`` function.
  - This enables support for audio with more than 16 bits per sample, a sample rate higher than 16000 Hz, and more than 1 channel - the previous component always assumed that particular format.
  - Should give an error if the sending component tries to set an incompatible audio stream instead of playing distorted audio, though a component needs to implement this call if it is sending non-default setting audio.
- Documents the various new (and old) functions in detail. 

The component should be much more resilient to errors and should hopefully avoid ever getting in a stuck state that locks the device. It should stop the task and unlock the I2S port if it can't recover, but future playback should work without needing to reboot. My ATOM Echo is much more reliable and stable with this implementation. I additionally tested the changes to the parent speaker component with an S3 Box Lite using the ``esp_adf`` speaker with no issues. I would appreciate anyone able to test this on other hardware!

I'm keeping as a draft until I add documentation for the ``speaker.volume_set`` action.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

esphome:
  on_boot:
    - speaker.volume_set: 0.9

speaker:
  - platform: i2s_audio
    id: echo_speaker
    i2s_dout_pin: GPIO22
    dac_type: external
    bits_per_sample: 32bit
    channel: right
    timeout: 500ms

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-15 11:49 UTC, nielsnl68 requested changes
Hi @kahrendt,

I like the new approach of the speaker component. 
I added a couple of suggestions below. 

Anyway it looks much better then what i tried to do with it.

2024-10-15 11:49 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +
```suggestion
size_t I2SAudioSpeaker::buffer_available() const {
  if (this->audio_ring_buffer_ != nullptr) {
    return this->audio_ring_buffer_->available();
  }
  return -1;
}
```

I love to have a method that tells the real available buffer space as well. so you do not need to send more data then available in the speaker buffer.

2024-10-15 11:49 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +    this_speaker->delete_task_(0);
```suggestion
    this_speaker->delete_task_(0);
    return; // or a wait loop;
```
Just to be sure that the next code is not executed anymore. 
The same for all other places `this_speaker->delete_task_()` is called.

2024-10-15 11:49 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +void I2SAudioSpeaker::finish() { this->stop_(true); }
Could you move this two above the `this->stop_();` for easy reading.

2024-10-15 11:49 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +
Should we not check if the buffer does not exist before we allocating new space here. Just to be sure that the last session finish properly?

2024-10-15 11:49 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +        i2s_zero_dma_buffer(this_speaker->parent_->get_port());
What happens when the speaker is still playing the last part of the data stream. Will this not stop it before it finished?

2024-10-15 11:49 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +void I2SAudioSpeaker::delete_task_(size_t buffer_size) {
Would it not cleaner when we move the creation of the buffers  into `void I2SAudioSpeaker::create_task_(size_t buffer_size)' here as well? Instead of setting them up in the `speaker_task()` method?

2024-10-15 11:49 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +  i2s_driver_uninstall(this_speaker->parent_->get_port());
```suggestion
  size_t bytes_written;
  uint32_t sample = 0;
  i2s_write(this->parent_->get_port(), &sample, 4, &bytes_written, portMAX_DELAY);

  i2s_stop(this_speaker->parent_->get_port());
  i2s_driver_uninstall(this_speaker->parent_->get_port());
```
to be make sure that the speaker output does not stay at an high/low level and burn away the speaker (it happened 3 times for me testing the RTTTL component).

2024-10-15 12:24 UTC, kahrendt commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +        i2s_zero_dma_buffer(this_speaker->parent_->get_port());
When the last bit of audio is copied out of the ring buffer into ``data_buffer_,`` it will then run the ``i2s_write`` or ``i2s_write_expand`` function. That has a delay of ``portMAX_DELAY``, meaning it will block indefinitely until all the data has been written to the I2S DMA buffers. Then on the next loop, no data is read from the ring buffer, so then this code executes. The ``i2s_zero_dma_buffer`` only adds zeros to the DMA buffer until it is full. It won't overwrite existing data in the DMA buffer, so the last bit of audio should play before outputting zeros.

2024-10-15 12:35 UTC, kahrendt commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +    this_speaker->delete_task_(0);
This is unnecessary, as deleting the task immediately stops it from executing. Espressif specifies that a task function should never return or it should be terminated using the vTaskDelete function. They even follow my exact approach in some of the [esp-idf code](https://github.com/espressif/esp-idf/blob/a97a7b0962da148669bb333ff1f30bf272946ade/examples/protocols/mqtt/ssl_ds/main/app_main.c#L102). There isn't a return function after vTaskDelete, even though there is more code after it.

2024-10-15 12:43 UTC, nielsnl68 commented
@kahrendt could you show how to use the new futures in **CPP** components as well?

2024-10-15 12:56 UTC, kahrendt commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +
I believe a better practice would be to use the ``ticks_to_wait`` parameter in the audio sending code. The sending code will block (let other tasks run) while it waits to be able to write all the data to the ring buffer. The sending code just has to handle internally that not all the data may be sent when calling the play function. I know the voice assistant component already handles this.

Overall I'm hesitant to add this because each speaker component would have to individually implement this, and I can't think of a safe way to provide a default function that wouldn't break any component that relies on it being correct. In contrast, the play function with ticks_to_wait and the finish function can all provide a safe default function if it isn't overridden by the component.

2024-10-15 13:09 UTC, kahrendt commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +void I2SAudioSpeaker::finish() { this->stop_(true); }
I reorganized the code to follow this order.

2024-10-15 13:10 UTC, kahrendt commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +void I2SAudioSpeaker::delete_task_(size_t buffer_size) {
I added an ``allocate_buffers_`` function for this. It does simplify the ``speaker_task`` code, thanks!

2024-10-15 13:10 UTC, kahrendt commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +
I added this check to the ``allocate_buffers_`` function.

2024-10-15 13:11 UTC, kahrendt commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +  i2s_driver_uninstall(this_speaker->parent_->get_port());
I added an ``i2ss_zero_dma_buffer`` before stopping and uninstalling the driver, so it should effectively do this.

2024-10-15 13:17 UTC, kahrendt commented
> @kahrendt could you show how to use the new futures in **CPP** components as well?

I don't have an easy example readily available, but the nabu component in the ``kahrendt-i2s-audio-approach`` branch [home-assistant-voice-pe](https://github.com/esphome/home-assistant-voice-pe) calls the new play function in ``audio_mixer.cpp`` in the ``audio_mixer_task`` function. The ``set_audio_stream_info`` function is called in the ``nabu_media_player.cpp`` file in the same branch.

2024-10-15 13:18 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +
Hmm, i see you have well toughed about it. I belief your approach is indeed better.

2024-10-15 13:41 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +    this_speaker->delete_task_(0);
When you 💯% sure :D then it is okay by me.

2024-10-15 14:01 UTC, nielsnl68 commented on esphome/components/audio/audio.h
> +  uint8_t channels = 1;
what happens when you configure the speaker with on speaker and the using component is set to 2 channels?
I hope i'm just missing something here?

2024-10-15 14:03 UTC, kahrendt commented on esphome/components/audio/audio.h
> +  uint8_t channels = 1;
It automatically writes the incoming one channel audio sample to both channels.

2024-10-15 14:46 UTC, kahrendt commented on esphome/components/audio/audio.h
> +  uint8_t channels = 1;
I realized you maybe meant the other way around. I tested this by sending stereo audio (set using the ``set_audio_stream_info`` and using the various channels options. It seems regardless of whether you set ``channel`` to ``mono``, ``left``, ``right``, or ``stereo``, it will still send the data to both channels. If you only have one channel hooked up, then it will still receive the audio.

Espressif's documentation isn't very clear on the exact behavior of the various channel formats and the ``i2s_set_clk`` function. In my tests though, whether sending stereo or mono channel audio to the speaker, it plays it back correctly; i.e., it doesn't play it double speed or anything like that.

2024-10-15 18:52 UTC, nielsnl68 commented on esphome/components/audio/audio.h
> +  uint8_t channels = 1;
Cool, that is what i wanted to know. Now we know we do not be worried anymore.

2024-10-15 20:11 UTC, nielsnl68 approved these changes

2024-10-15 22:00 UTC, nielsnl68 commented
Keven, about the speaker_task(), what you could do is the following:

```cpp
class i2s_audio_speaker .... {
  static void speaker_task(void *params);
protected:
  void run_speaker_task_();
}

}

static void i2s_audio_speaker::speaker_task(void *params) {
  I2SAudioSpeaker *this_speaker = (I2SAudioSpeaker *) params;
  this_speaker->run_speaker_task_();
}

```

This work very well on my espnow component.

2024-10-16 22:33 UTC, jesserockz commented
> Keven, about the speaker_task(), what you could do is the following

I actually think it is better to keep the task running code in the static function, it reminds you that by using `this_speaker` instead of just `this` that you are in a task and shouldn't do unsafe operations.

2024-10-16 22:35 UTC, jesserockz approved these changes

2024-10-16 22:47 UTC, merged

2024-10-16 23:51 UTC, nielsnl68 commented
> > Keven, about the speaker_task(), what you could do is the following
> 
> I actually think it is better to keep the task running code in the static function, it reminds you that by using `this_speaker` instead of just `this` that you are in a task and shouldn't do unsafe operations.

Okay, then i will update my espnow component as well.