Add option to include vars in remote packages
OttoWinter/esphomeyaml pull request #7606
Opened 2024-10-15 07:16 UTC by pszafer

# What does this implement/fix?

This PR adds ability to add vars in remote packages.
It allows to specify same file multiple times.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/2542

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** [esphome/esphome-docs#<esphome-docs PR number goes here>](https://github.com/esphome/esphome-docs/pull/4342)

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
remote_package_files2:
  url: https://github.com/esphome/non-existant-repo
  files:
    - name: file1.yml
      vars:
        a: 1
        b: 2
    - name: file1.yml #Same file can be specified multiple times with different vars.
      vars:
        a: 3
        b: 4
    - file2.yml
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-16 03:16 UTC, jesserockz requested changes
Code looks good to me.

Please add some tests for this.

2024-11-02 09:09 UTC, itsteddyyo commented
Can confirm this works with all my packages and ESP's :smiley:

2024-11-25 18:06 UTC, XavierBerger commented
Thanks @pszafer for the Pull Request.

I did test it on my project and I can also confirm that the current code it is working.

It is working, yes, _but not exactly how I was expected_. Let me explain:

I was expecting a configuration like this: 

```yaml
packages:
  power_meter: # !include
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/power_meter_fronius.yaml
    vars:
      power_meter_ip_address: "192.168.1.21"
    refresh: 1d
  regulator: # !include
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/regulator_triac.yaml
    vars:
      regulator_gate_pin: GPIO22
      regulator_zero_crossing_pin: GPIO23
    refresh: 1d
```
In my proposed configuration, `vars` are applied to the file individually.

My motivation is to be able to quickly switch from local code I used for development to user code which is stored on github.

With a simple bash script, it is possible to transform the prevoius code (using github) to the following code (using local files). _See the change on comments_.

```yaml
packages:
  power_meter: !include
    # url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/power_meter_fronius.yaml
    vars:
      power_meter_ip_address: "192.168.1.21"
    refresh: 1d
  regulator: !include
    # url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/regulator_triac.yaml
    vars:
      regulator_gate_pin: GPIO22
      regulator_zero_crossing_pin: GPIO23
    refresh: 1d
```

**What do you think of this idea? Does-it worth it?**

I'm not really confident to propose a Pull Request on top of yours (I'm not sure to fully understand all the details of this code). Do you think possible to implement such a configuration in addition to yours? If yes, it will a great feature helping me to improve my project.

2024-11-25 21:11 UTC, itsteddyyo commented
Heya @XavierBerger,  

not the one you asked but i just wanted to jump in with another perspective :smiley:

I think the current implementation of this PR is actually spot on — it lines up nicely with the syntax how remote packages work right now, which is great for consistency. Plus, I really like how it lets you pull in multiple files from the same repo without repeating yourself over and over. For example, you can write something like this:  

```yaml
packages:
  my.packages:
    url: https://github.com/me/myrepo
    ref: main
    refresh: 0s
    files:
      - name: "base.yaml"
      - name: "board.yaml"
      - name: "sensor1.yaml"
        vars:
          i2c_id: bus_a
      - name: "sensor2.yaml"
        vars:
          i2c_id: bus_a
```

It’s super clean, and when you need to, you can still split things out across multiple packages for different refs or just because you like it better that way 😃 

```yaml
packages:
  my.packages1:
    url: https://github.com/me/myrepo
    ref: main
    refresh: 0s
    files: ["base.yaml"]
  my.packages2:
    url: https://github.com/me/myrepo
    ref: v1
    refresh: 0s
    files: ["board.yaml"]
  my.packages3:
    url: https://github.com/me/myrepo
    ref: v2
    refresh: 0s
    files:
      - name: "sensor1.yaml"
        vars:
          i2c_id: bus_a
      - name: "sensor2.yaml"
        vars:
          i2c_id: bus_a
```

This gives you a lot of flexibility without overcomplicating things. And with the syntax like in the second example you could probably also use a bash-Script for converting with just a few adjustments :smiley:  

I do agree, though, that there’s room for improvement in the long run — like bringing remote and local packages together under similar syntax and the same import/yaml-build process/code :smiley:

And yeah, it’d be awesome if things like `!extend` or `!remove` worked for remote packages too. But I feel like that’s more of a big-picture overhaul for later that is out-of-scope for this PR.  

But that's only my two cents! Curious for other thoughts thoughts especially @pszafer!

2024-11-27 13:30 UTC, pszafer commented
So !include and packages are 2 different "beasts".
In way I proposed it, there is single git pull per branch for all files and files are just compiled against vars.
In my opinion for packages it would be the best to avoid include and add extra option `localFile: true` and if it's true then don't fetch from github, but try to fetch file from filesystem.

But it's up to @jesserockz if that's good idea or not. Also I'd make it in another PR as smaller PR are easier to maintain.

2024-12-26 16:43 UTC, edwardtfn commented
I'm trying to test this, but I'm getting an issue:

```yaml
external_components:
  - source: github://pr#7606
    components:
      - packages
    refresh: 1h

packages:
  sonicare:
    url: https://github.com/edwardtfn/sonicare
    ref: main
    files:
      - name: esphome_sonicare_template.yaml
        vars:
          sonicare_name: "Toothbrush One"
          sonicare_id: "toothbrush_one"
          sonicare_mac: "24:E5:AA:X1:Y1:Z1"
      - name: esphome_sonicare_template.yaml
        vars:
          sonicare_name: "Toothbrush Two"
          sonicare_id: "toothbrush_two"
          sonicare_mac: "24:E5:AA:X2:Y2:Z2"

  bed_presence:
    url: https://github.com/ElevatedSensors/sensor-configs
    ref: main
    files: [bed-presence-mk1/base.yaml]
    refresh: 1s
```

This is what I get when trying to compile:
```log
INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/bedroom-bed-presence.yaml...
Failed config

packages: [source /config/esphome/bedroom-bed-presence.yaml:44]
  sonicare: 
    url: https://github.com/edwardtfn/sonicare
    ref: main
    files: 
      
      string value cannot be dictionary or list.
      - name: esphome_sonicare_template.yaml
        vars: 
          sonicare_name: Toothbrush One
          sonicare_id: toothbrush_one
          sonicare_mac: 24:E5:AA:X1:Y1:Z1
      
      string value cannot be dictionary or list.
      - name: esphome_sonicare_template.yaml
        vars: 
          sonicare_name: Toothbrush Two
```

It works fine when I try a local package like this:
```yaml
packages:
  sonicare.one: !include
    file: packages/sonicare.yaml
    vars:
      sonicare_name: "Toothbrush One"
      sonicare_id: "toothbrush_one"
      sonicare_mac: "24:E5:AA:X1:Y1:Z1"
  sonicare.two: !include
    file: packages/sonicare.yaml
    vars:
      sonicare_name: "Toothbrush Two"
      sonicare_id: "toothbrush_two"
      sonicare_mac: "24:E5:AA:X2:Y2:Z2"
```

2024-12-27 09:56 UTC, pszafer commented
@edwardtfn it won't work with `external_components`, I rebased this PR to dev version of esphome. You can check it out pulling it from this PR.

2025-02-13 11:00 UTC, pszafer reviewed
tests added

2025-02-26 00:41 UTC, jesserockz approved these changes

2025-02-26 01:02 UTC, merged

2025-03-08 19:31 UTC, smkent commented
I'm looking forward to being able to use this feature! Is this expected to ship in an upcoming release?