Move setting global voice assistant to constructor
OttoWinter/esphomeyaml pull request #7630
Opened 2024-10-18 20:18 UTC by synesthesiam

# What does this implement/fix?

Sets the global voice assistant in the constructor rather than in `setup()` so that the voice assistant feature flags will always be present in the device info.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-18 20:32 UTC, jesserockz requested changes

2024-10-18 20:32 UTC, jesserockz commented on esphome/components/voice_assistant/voice_assistant.cpp
>    global_voice_assistant = this;
This is not the constructor 🙈

2024-10-18 20:32 UTC, jesserockz commented on esphome/components/voice_assistant/voice_assistant.cpp
> +void VoiceAssistant::setup() { ESP_LOGCONFIG(TAG, "Setting up Voice Assistant..."); }
A setup function is not needed if it only logs
```suggestion
```

2024-10-19 19:10 UTC, synesthesiam commented on esphome/components/voice_assistant/voice_assistant.cpp
>    global_voice_assistant = this;
:man_facepalming:

2024-10-19 19:16 UTC, synesthesiam commented on esphome/components/voice_assistant/voice_assistant.cpp
> +void VoiceAssistant::setup() { ESP_LOGCONFIG(TAG, "Setting up Voice Assistant..."); }
Fixed

2024-10-21 14:32 UTC, synesthesiam commented
I'm confused why this is failing the test :/

2024-10-21 22:44 UTC, jesserockz submitted a review, later dismissed

2024-10-21 22:47 UTC, jesserockz approved these changes

2024-10-21 23:14 UTC, merged