[mlx90393] Fix inverted gain and resolution. Expose temperature_compensation and hallconf.
OttoWinter/esphomeyaml pull request #7635
Opened 2024-10-19 16:21 UTC by functionpointer

# What does this implement/fix?

I experienced integer overflows with MLX90393 three axis magnetometer. This fixes it.

I recommend reading the new documentation: [deploy preview](https://deploy-preview-4353--esphome.netlify.app/components/sensor/mlx90393)

The old gain options were copied from the arduino-MLX90393 library. However, the library actually does the opposite thing from the sensor hardware. Low hardware gain settings are multiplied with large numbers, while high gains are multiplied with small numbers. This is done in order to get consistent readings in µT independent of gain setting.

This is confusing from the user's perspective. The user configures the sensor, not the library.
Therefore, this PR inverts (actually 5/x) all gain settings. This reflects the analog gain used inside the sensor.

Furthermore, the resolution options are named more appropriately. The resolution is always 16 bit, we just choose which 16 bits we get.

Additionally, the default values are changed. The old defaults offered high sensitivity, but caused integer overflows in strong magnetic fields. This easily happened when a neodymium magnet was held within a few cm of the sensor.
The new default configuration prevents all integer overflows and can deal with strong fields easily.
Higher sensitivity must now be explicitly configured by the user. The new documentation informs about integer overflows, mitigating the risk of false readings that existed previously.

Finally, this PR exposes the already existing `hallconf` and `temperature_compensation` options.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4353

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [X] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: mlx90393
    gain: 1X
    x_axis:
      name: mlxxaxis
    y_axis:
      name: mlxyaxis
    z_axis:
      name: mlxzaxis
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-12-10 01:07 UTC, jesserockz requested changes

2024-12-10 01:07 UTC, jesserockz commented on esphome/components/mlx90393/sensor.py
> +            cv.Optional(CONF_HALLCONF, default=0xC): cv.one_of(0xC, 0x0),
You have not used these new variables in `to_code` below

2024-12-24 13:18 UTC, functionpointer commented on esphome/components/mlx90393/sensor.py
> +            cv.Optional(CONF_HALLCONF, default=0xC): cv.one_of(0xC, 0x0),
Good catch, I have added it

2025-01-28 13:49 UTC, functionpointer commented
I have addressed the changes. The PR is ready for another review.

2025-02-27 18:25 UTC, jesserockz approved these changes

2025-02-27 18:28 UTC, merged