Gp8211
OttoWinter/esphomeyaml pull request #7636
Opened 2024-10-19 18:05 UTC by haudamekki

# What does this implement/fix?

This PR implements support for the GP8211, a single-channel DAC output module controlled via I²C. The GP8211 allows users to configure voltage output in the range of either 0-5V or 0-10V, depending on the setup. It also includes a fixed I²C address of 0x58. The component supports smooth brightness control when used with lights or other analog outputs in ESPHome.

This implementation is based on the existing GP8403 component, adapting it for the single-channel GP8211 module.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
gp8211:
  id: my_gp8211
  voltage: 5V

output:
  - platform: gp8211
    id: my_gp8211_output
    gp8211_id: my_gp8211
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-20 12:18 UTC, SeByDocKy commented
Thx for this new contribution. The 8413 (15bits) need also to implemented :).

2024-10-30 22:59 UTC, jesserockz requested changes

2024-10-30 22:59 UTC, jesserockz commented on esphome/components/gp8211/gp8211.h
> +  GP8211_VOLTAGE_10V = 0x11,
You might as well make these the value of the register then you dont need the ternary in setup and can just write directly.
```suggestion
  GP8211_VOLTAGE_5V = 0x55,
  GP8211_VOLTAGE_10V = 0x77,
```

2024-10-30 22:59 UTC, jesserockz commented on esphome/components/gp8211/gp8211.cpp
> +  this->write_register(RANGE_REGISTER, &voltage_setting, 1);
```suggestion
  this->write_register(RANGE_REGISTER, &this->voltage_, 1);
```

2024-10-30 22:59 UTC, jesserockz commented on esphome/components/gp8211/output/gp8211_output.cpp
> +  ESP_LOGD(TAG, "Original brightness state received from Light component: %.5f", state);
These can be very noisy if a light does a transition and outputs are not limited to lights.
```suggestion
```

2024-10-30 22:59 UTC, jesserockz commented on esphome/components/gp8211/output/gp8211_output.cpp
> +  ESP_LOGD(TAG, "Calculated DAC value: %u", value);
```suggestion
  ESP_LOGV(TAG, "Calculated DAC value: %u", value);
```

2024-10-30 22:59 UTC, jesserockz commented on esphome/components/gp8211/output/gp8211_output.cpp
> +}
```suggestion
  if (err != i2c::ERROR_OK) {
    ESP_LOGE(TAG, "Error writing to GP8211, code %d", err);
    this->status_set_error();
    return;
  }
  this->status_clear_error();
}
```

2024-11-07 20:42 UTC, jesserockz requested changes
Since this is only a single channel output, all of the parent/hub code is not really required and can just be incorporated into the `output` directly. Sorry I didnt notice this before.

2025-10-06 00:49 UTC, closed without merging