New camera component base class that can be used for other implementations.
OttoWinter/esphomeyaml pull request #7639
Opened 2024-10-20 12:47 UTC by DT-art1

- Refactored ESP32 camera to use camera base class.
- Refactored ESP32 web server to use camera base class.

# What does this implement/fix?

This request refactors the ESP32Camera and ESP32Webserver components. Both are now using the interfaces in the new camera component. This allows other implementation to send images via the API and reuse the ESP32Webserver without the ESP32Camera.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-03 21:51 UTC, jesserockz requested changes

2024-11-03 21:51 UTC, jesserockz commented on esphome/components/esp32_camera/__init__.py
> +    cg.add_define("USE_CAMERA")
Can remove since the base camera component will add it
```suggestion
```

2024-11-03 21:51 UTC, jesserockz commented on esphome/core/defines.h
> +#define USE_CAMERA
Please move this into alphabetical order position

2024-11-03 21:51 UTC, jesserockz commented on esphome/components/camera/__init__.py
> +
The c++ classes should be in here for use by any other classes that use them

2024-11-03 21:51 UTC, jesserockz commented on esphome/components/esp32_camera_web_server/camera_web_server.cpp
> +  if (!camera::Camera::global_camera) {
The `Camera` base class should probably also inherit Component so it can be generically marked as failed and detected by anything that is attached to it.

2024-11-03 21:51 UTC, jesserockz commented on esphome/components/camera/__init__.py
> +CONFIG_SCHEMA = cv.Schema({})
The triggers `on_image` / `on_stream_start/stop` should probably move here too

2024-11-06 06:34 UTC, DT-art1 commented on esphome/components/camera/__init__.py
> +
The shared c++ files are located in the folder "esphome/components/camera/". I am not quite sure if you mean that they should be embedded in the Python file instead ? 
Setting AUTO_LOAD = ["camera"] in a component makes the c++ files available.

2024-11-06 06:51 UTC, jesserockz commented on esphome/components/camera/__init__.py
> +
```py
camera_ns = cg.esphome_ns.namespace("camera")
Camera = camera_ns.class_("Camera", cg.EntityBase)
```

These variables/definitions are then used by any class variables in python to ensure that config schema matches correctly.

This is standard across all components and classes in ESPHome. Please see the codebase for more usage examples.

2024-11-08 03:42 UTC, jesserockz requested changes

2024-11-08 03:42 UTC, jesserockz commented on esphome/components/camera/__init__.py
> +CONFIG_SCHEMA = cv.Schema(
This should not be named `CONFIG_SCHEMA` as that indicates this is a component that has its own configuration in yaml
```suggestion
CAMERA_SCHEMA = cv.Schema(
```

2024-11-22 07:41 UTC, DT-art1 commented
@jesserockz Hi. I was just wondering if there is anything else to consider or should I consider it as completed?

2025-01-07 13:37 UTC, DFINITYManu approved these changes

2025-02-20 17:20 UTC, nliaudat commented
any chance to have it merged in next release ?

2025-02-21 12:17 UTC, DT-art1 commented
@jesserockz Hi, it seems like this pull request could benefit others as well. I wanted to check if there are any additional changes you'd like me to make, or if the only thing holding back the merge is time?

2025-04-20 10:54 UTC, DT-art1 commented
**Tested:**
- [x] Compiles without errors
- [x] Uploaded successfully to Seeed Studio XIAO ESP32S3 Sense
- [x] Feature works as expected (see attached screenshot)
- [x] No breaking changes observed.

**Test configuration:**

```yaml
esphome:
  name: refactor-esp32camera
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Configuration XIAO esp32s3 sense
esp32_camera:
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_pins:
    sda: GPIO40
    scl: GPIO39
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  # Automation settings
  on_image:
    then:
    - lambda: |-
        ESP_LOGD("main", "AUTOMATION: on_image len=%d, data=%c", image.length, image.data[0]);
  on_stream_start:
    then:
    - lambda: |-
        ESP_LOGD("main", "AUTOMATION: on_stream_start.");
  on_stream_stop:
    then:
    - lambda: |-
        ESP_LOGD("main", "AUTOMATION: on_stream_stop");

  # Image settings
  name: My Camera
  # ...

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
```

**Note:**
This PR has been tested with the configuration above.
The integration works as intended and does not break previous configurations.

![Skärmbild 2025-04-20 123101](https://github.com/user-attachments/assets/9bd30017-c363-4722-94be-4a40b75f65af)

2025-04-21 14:18 UTC, nliaudat commented
tested with success on esp-idf+arduino frameworks with Freenove ESP32-S3 WROOM N8R8 (8MB Flash / 8MB PSRAM)

```
  external_clock_pin: GPIO15
  external_clock_frequency: 20MHz
  i2c_pins_sda: GPIO4
  i2c_pins_scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16] 
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  status_led_pin: GPIO02
  flash_led_pin: GPIO48
```

2025-06-09 19:12 UTC, DT-art1 commented
Hi @kbx81 - I noticed you've been reviewing some graphics-related changes recently.

I'm giving this PR one last pass through before potentially closing it as unmerged. If you feel there's value in it, I'd greatly appreciate your perspective.

Previous feedback has been addressed, and docs are already in place.
Thanks in advance - no pressure, of course!

2025-06-10 05:43 UTC, bdraco commented
The PR looks well thought out, and it's definitely worth sticking with. There aren’t many reviewers who can handle something of this size, so it might take a bit of time to get the attention it needs.

2025-06-10 14:41 UTC, DT-art1 commented
Thanks for the kind words and encouragement!
I’m happy to stick with it and available if any questions or clarifications come up.
Looking forward to hopefully getting this over the finish line 🙌

2025-06-29 11:32 UTC, bdraco commented on esphome/components/camera/camera.h
> +enum ImageFormat {
can be uint8_t size

2025-06-29 11:32 UTC, bdraco commented on esphome/components/camera/camera.h
> +enum CameraRequester { IDLE, API_REQUESTER, WEB_REQUESTER };
can be uint8_t size

2025-06-29 11:33 UTC, bdraco commented on esphome/components/camera/camera_image_impl.h
> +  uint8_t requesters_{0};
Please align members to reduce padding

2025-06-29 11:33 UTC, bdraco commented on esphome/components/camera/camera_impl.cpp
> +  const uint32_t now = millis();
App.get_loop_component_start_time()

2025-06-29 11:33 UTC, bdraco commented on esphome/components/camera/camera_impl.h
> +  enum CameraState {
uint8_t

2025-06-29 11:34 UTC, bdraco commented on esphome/components/camera/camera_impl.h
> +  CameraState state_{CAMERA_STATE_INIT};
Please align members to reduce padding

2025-06-29 11:43 UTC, bdraco commented
Thank you for this excellent work on modernizing the camera framework! The implementation quality is impressive.

Why This Review Is Taking Time: Camera components have relatively few users in ESPHome, and this PR touches 36+ files with significant architectural changes. This combination means we need to be extra careful to avoid disrupting existing users.

Every ESP32 camera user will need to update their configuration:
```yaml
# OLD
esp32_camera:
  name: "My Camera"
  jpeg_quality: 10

# NEW  
camera:
  name: "My Camera"
  encoder_quality: HIGH      # New required field
  encoder_subsampling: 420   # New required field
```

Let's split this into smaller PRs to make review easier and reduce risk:

**First PR**: Just migrate ESP32 camera to the new platform with minimal breaking changes
**Later PRs**: Add JPEG encoding, overlays, memory optimizations

This approach will:
- Get your improvements merged faster
- Give users time to adapt
- Make testing more manageable

Would you be willing to start with just the core migration? Once that foundation is solid, we can add all the great enhancements you've built.

Let's work together to land it smoothly! Camera users will be much happier in the long run if we can minimize the configuration changes they need to make.

2025-06-29 18:50 UTC, DT-art1 commented
Thank you for the thoughtful feedback and kind words!

I fully understand the need for a cautious approach given the scope and potential impact on users. Splitting the PR makes sense, and I’m absolutely on board with starting with a minimal core migration that preserves backward compatibility.

I’ll prepare a focused initial PR with just the foundational changes for ESP32 camera and keep the enhancements (encoding, overlays, etc.) for follow-ups. Looking forward to collaborating on this and ensuring a smooth transition for users.

2025-08-26 17:14 UTC, nliaudat commented
Hi, 
Many thanks for your great work !

Can you open the discussion and PR tab in https://github.com/DT-art1/esphome/tree/refactor_esp32camera ? 

I'd like to contribute to implement my needs : [camera_cropper], [camera_decoder]

Perhaps I do not have the skills :(, but I am working on a [project](https://github.com/nliaudat/meter-reader/tree/dev/esphome/components/meter_reader_tflite) to implement general tflite model on esphome and I am hurting on camera image processing. 
You component is the futur and I am actually reinventing the wheel :)

Best Regards

2025-08-26 19:30 UTC, DT-art1 commented
Thank you very much!

I've set up a discussion thread to get started: [Discussion](https://github.com/DT-art1/esphome/discussions/1)
Feel free to post your thoughts - I'll try to help wherever I can. :-)

I also started integrating a processing stage that sits between the capture and the encoder.
I think a TFLite model could fit in there as well. Currently I have just a rescaler and a local (uncommited) colorizer placed there,
but I think other "image processors" could easily be added too.

Best Regards

2025-08-31 14:44 UTC, DT-art1 commented
@bdraco I just noticed that you also closed this #7639. I'm not sure if this was intentional, since this PR contains almost the entire new camera pipeline. I was thinking of removing the parts that have already been merged upstream from this PR. But if it was intentional, I can create a new PR with only the relevant parts, with the drawback that it won't include a reference to the full camera pipeline.

2025-08-31 15:02 UTC, bdraco commented
You had closing keywords in 7639 -- ie `fixes https://github.com/esphome/esphome/pull/7639` in the PR I merged so it auto closed when I merged that one

2025-08-31 15:18 UTC, DT-art1 commented
Thanks for reopening and for the clarification. I wasn't aware of this implication.

2025-11-04 08:51 UTC, lboue commented
You should update the example config in your comments to match your test files:
```
Failed config

camera_pipeline: [source config/tab5.yaml:199]
  - 
    ID 'sensor' conflicts with the name of an esphome integration, please use another ID name.
    id: sensor
```

2025-11-04 12:17 UTC, youkorr commented
Interesting, what was your FPS?

2025-11-04 12:31 UTC, DT-art1 commented
Thanks for asking about FPS!

The FPS mainly depends on which requester is consuming the frames, since each requester has different throughput:
- Home Assistant / API requester → typically lower throughput with larger resolutions.
- Camera Web Server → generally higher sustained FPS.
- Pipeline-only processing (no streaming) → highest FPS.

The pipeline also supports an overlay processor that can draw a live FPS counter on the image, making it easy to measure in different setups.

Note: My current measurements are done over Wi-Fi, not Ethernet.
Ethernet will allow higher sustained FPS on networks that support it.

To provide numbers that match your use case — which camera + resolution + requester are you interested in?

2025-11-04 13:22 UTC, youkorr commented
I created an external_components folder for the SC202CS and OV5647 at 1280x720 with an average of around 10fps without ESP_video,but I didn't use camera encoder

2025-11-04 13:27 UTC, youkorr commented
But I'm working on implementing ESP_video; it's easy on paper.
```
┌──────────────────────────────┐
│ MIPI-DSI-CAM (ESPHome) │ ← your component
│ (mipi_dsi_cam.cpp/.h) │
└───────────┬───────────────┘

│ calls
▼
┌──────────────────────────────┐
│ esp_video │ ← core of the pipeline
│ ├─ init / device / isp │
│ └─ connects all modules │
└────────────┬─────────────────┘ 
│ uses 
▼
┌─────────────────── ───────────────────┐
│ esp_cam_sensor │ ← MIPI CSI sensor driver
│ ↳ Configure I²C (SCCB), ID register, │
│ Streaming mode │
└───────────────────────────────────┘
│

▼
┌───────────────────────────────────────┐
│ esp_sccb_intf │ ← Low-level I²C interface
│ ↳ Sensor register communication │
└──────────────────────────────────────┘

│
▼
┌───────────────────────────────────────┐
│ esp_ipa (Image Processing Accelerator)│ ← Hardware image processing
│ ↳ Noise reduction, gamma, color │
└──────────────────────────────────────┘

│
▼
┌──────────────────────────────────────┐
│ esp_h264 / esp_jpeg │ ← Hardware encoders
│ ↳ H.264 or JPEG depending on the pipeline │
└──────────────────────────────────────┘

│
▼
┌───────────────────────────────────────┐
│ Outputs (/dev/video10,11,20…) │ ← V4L2 devices
│ ↳ Playback, Streaming, Snapshot │
└──────────────────────────────────────┘
```

2025-11-04 13:55 UTC, DT-art1 commented
```
font:
  - file:
      type: gfonts
      family: Roboto
      weight: 500
    id: font_id
    size: 12

camera:
    name: Camera
    max_update_interval: 10

camera_sensor:
  type: mipi_csi
  mode: "MIPI_2lane_24Minput_RAW8_800x1280_50fps"

camera_pipeline:
  - id: input
    type: input
    next: overlay

  - id: overlay
    type: overlay
    next: encode
    on_post_process:
      then:
      - lambda: |-
          static int64_t last_frame = 0;
          int64_t now = millis();
          int64_t frame_time = now - last_frame;
          last_frame = now;
          float fps = 1000.0 / (uint32_t) frame_time;
          processor.printf(20, 20, id(font_id), Color(0xFFFFFF), "%.1f fps", fps);

  - id: encode
    type: output
    camera_encoder_id: jpeg_encoder

camera_encoder:
  id: jpeg_encoder
  type: accelerated_jpeg

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
```

With the current configuration I'm testing, using a Waveshare ESP32-P4-NANO (OV5647) in 800x1200 mode, I'm getting up to 18 FPS when viewing the stream through the ESP32 Camera Web Server.
The sustained average is typically around 15 FPS, depending on scene complexity and network conditions.
(These measurements are taken over Wi-Fi - using Ethernet would generally allow a higher stable FPS. )

2025-11-04 14:02 UTC, youkorr commented
Are you experiencing image stuttering?

2025-11-04 14:15 UTC, DT-art1 commented
There is some variation in the frame delivery, which shows up as slight stuttering.
From the logs it looks like the processing pipeline is running consistently, so the fluctuation is most likely coming from the network side (I’m currently streaming over Wi-Fi).

I’ll test again using a more stable network setup (e.g., Ethernet) to confirm.
Streaming performance should be smoother when the transport layer has consistent throughput.

2025-11-04 14:19 UTC, youkorr commented
With my project using lvgl esphome and canvas with RGB 565 format, I get around 10 to 13 fps

2025-11-04 18:27 UTC, DT-art1 commented
> But I'm working on implementing ESP_video; it's easy on paper.
> 
> ```
> ┌──────────────────────────────┐
> │ MIPI-DSI-CAM (ESPHome) │ ← your component
> │ (mipi_dsi_cam.cpp/.h) │
> └───────────┬───────────────┘
> 
> │ calls
> ▼
>... 
> │
> ▼
> ┌───────────────────────────────────────┐
> │ Outputs (/dev/video10,11,20…) │ ← V4L2 devices
> │ ↳ Playback, Streaming, Snapshot │
> └──────────────────────────────────────┘
> ```

Thanks for the detailed breakdown — but just to clarify: the pipeline implementation in this PR does not wrap or rely on esp_video, nor does it follow the V4L2-style device model.

The architecture here is:

Input  →  Pipeline (Processors)  →  Output(s)

- Input can be any image source: MIPI-CSI sensor, classic ESP32 camera, software-generated frames, etc.

- The Pipeline is modular and dynamic. Each stage is a Processor, and processors may:
  - perform hardware-accelerated scaling / rotation (using the P4 PPA)
  - run inference
  - add overlays
  - or perform any custom image operation
  
The pipeline can also branch (tree structure), meaning one input frame can be processed in multiple different ways.


- Outputs are independent and can have their own formats/encoders. For example:
  - One output may produce JPEG for HA streaming
  - Another output may provide frames to the web camera server

This allows different requesters to receive different versions of the same image depending on their bandwidth/needs.

So instead of binding everything around a single ISP/H.264 pipeline like esp_video, the structure is intentionally flexible to accommodate multiple consumers.

2025-11-04 22:01 UTC, lboue commented
I just tried with M5Tab and it works. It's just magical!:
```
[22:53:13][C][camera:182]: Camera:
[22:53:13][C][camera:182]:  Name: Camera
[22:53:13][C][camera:182]:  Idle update: 0 ms
[22:53:13][C][camera:182]:  Max update: 100 ms
[22:53:13][C][camera:034]:   Task:
[22:53:13][C][camera:034]:    Core: 1
[22:53:13][C][camera:034]:    Stack Size: 4096
[22:53:13][C][camera:034]:    Priority: 1
[22:53:13][C][camera:034]:    Delay: 5
[22:53:13][C][camera_pipeline:041]: Inputer: input
[22:53:13][C][camera_pipeline:041]:  IMAGE_FORMAT_RAW
[22:53:13][C][camera_pipeline:041]:  Retry Limit: 10
[22:53:13][C][camera_pipeline:041]:  Job: NO
[22:53:13][C][camera_sensor:226]: Camera Sensor: SC202CS
[22:53:13][C][camera_sensor:226]:  MIPI_1lane_24Minput_RAW8_1280x720_30fps
[22:53:13][C][camera_sensor:226]:  PIXEL_FORMAT_RGB565
[22:53:13][C][camera_sensor:226]:  Flip X: NO, Y: NO, Factory X: YES
[22:53:13][C][camera_sensor:226]:  Buffers: 2
[22:53:13][C][camera_sensor:226]:  Test Pattern: NO
[22:53:13][C][camera_sensor:226]:  MIPI-CSI:
[22:53:13][C][camera_sensor:226]:    Clock: 576 MHz
[22:53:13][C][camera_sensor:226]:    Lanes: 1
[22:53:13][C][camera_sensor:226]:    Line Sync: NO
[22:53:13][C][camera_sensor:241]:   Address: 0x36
[22:53:13][C][camera_sensor:101]: ISP:
[22:53:13][C][camera_sensor:101]:  Bayer Pattern:
[22:53:13][C][camera_sensor:101]:    Reported: BGGR
[22:53:13][C][camera_sensor:101]:    In Use: AUTO
[22:53:13][C][camera_pipeline:016]: Outputer: encode
[22:53:13][C][camera_pipeline:016]:  Buffers: 2
[22:53:13][C][camera_pipeline:016]:  Size: 207360
[22:53:13][C][camera_pipeline:016]:  Requester: IDLE, API, WEB
[22:53:13][C][camera_pipeline:016]:  Encoder: YES
[22:53:13][C][camera_pipeline:016]:  Job: NO
[22:53:13][C][camera_encoder:067]: Accelerated JPEG Encoder:
[22:53:13][C][camera_encoder:067]:  Size: 1048576
[22:53:13][C][camera_encoder:067]:  Quality: 40
[22:53:13][C][camera_encoder:067]:  Timeout: 100
[22:53:13][C][camera_encoder:067]:  SUBSAMPLING_444
[22:53:13][C][pipeline:149]: Pipeline:
[22:53:13][C][pipeline:154]:   input -> encode
[22:53:13][C][mdns:179]: mDNS:
[22:53:13][C][mdns:179]:  Hostname: m5stack-tab5
[22:53:13][C][esp32_camera_web_server:088]: ESP32 Camera Web Server:
[22:53:13][C][esp32_camera_web_server:088]:  Port: 8080
[22:53:13][C][esp32_camera_web_server:093]:   Mode: stream
[22:53:13][C][esp32_camera_web_server:088]: ESP32 Camera Web Server:
[22:53:13][C][esp32_camera_web_server:088]:  Port: 8081
[22:53:13][C][esp32_camera_web_server:095]:   Mode: snapshot
```

2025-11-06 14:28 UTC, hubecker commented
I just tried it with my ESP32-P4-NANO. From the log it seems to work, except the esp32_camera_web_server:
[15:24:17][C][camera:182]: Camera:
[15:24:17][C][camera:182]:  Name: Camera
[15:24:17][C][camera:182]:  Idle update: 0 ms
[15:24:17][C][camera:182]:  Max update: 100 ms
[15:24:17][C][camera:034]:   Task:
[15:24:17][C][camera:034]:    Core: 1
[15:24:17][C][camera:034]:    Stack Size: 4096
[15:24:17][C][camera:034]:    Priority: 1
[15:24:17][C][camera:034]:    Delay: 5
[15:24:17][C][camera_pipeline:041]: Inputer: input
[15:24:17][C][camera_pipeline:041]:  IMAGE_FORMAT_RAW
[15:24:17][C][camera_pipeline:041]:  Retry Limit: 10
[15:24:17][C][camera_pipeline:041]:  Job: NO
[15:24:17][C][camera_sensor:226]: Camera Sensor: OV5647
[15:24:17][C][camera_sensor:226]:  MIPI_2lane_24Minput_RAW8_800x640_50fps
[15:24:17][C][camera_sensor:226]:  PIXEL_FORMAT_RGB565
[15:24:17][C][camera_sensor:226]:  Flip X: NO, Y: NO, Factory X: YES
[15:24:17][C][camera_sensor:226]:  Buffers: 2
[15:24:17][C][camera_sensor:226]:  Test Pattern: NO
[15:24:17][C][camera_sensor:226]:  MIPI-CSI:
[15:24:17][C][camera_sensor:226]:    Clock: 400 MHz
[15:24:17][C][camera_sensor:226]:    Lanes: 2
[15:24:17][C][camera_sensor:226]:    Line Sync: YES
[15:24:17][C][camera_sensor:241]:   Address: 0x36
[15:24:17][C][camera_sensor:101]: ISP:
[15:24:17][C][camera_sensor:101]:  Bayer Pattern:
[15:24:17][C][camera_sensor:101]:    Reported: GBRG
[15:24:17][C][camera_sensor:101]:    In Use: AUTO
[15:24:17][C][camera_pipeline:016]: Outputer: encode
[15:24:17][C][camera_pipeline:016]:  Buffers: 2
[15:24:17][C][camera_pipeline:016]:  Size: 207360
[15:24:17][C][camera_pipeline:016]:  Requester: IDLE, API, WEB
[15:24:17][C][camera_pipeline:016]:  Encoder: YES
[15:24:17][C][camera_pipeline:016]:  Job: NO
[15:24:17][C][camera_encoder:067]: Accelerated JPEG Encoder:
[15:24:17][C][camera_encoder:067]:  Size: 1048576
[15:24:17][C][camera_encoder:067]:  Quality: 40
[15:24:17][C][camera_encoder:067]:  Timeout: 100
[15:24:17][C][camera_encoder:067]:  SUBSAMPLING_444
[15:24:17][C][pipeline:149]: Pipeline:
[15:24:17][C][pipeline:154]:   input -> encode
[15:24:17][C][mdns:179]: mDNS:
[15:24:17][C][mdns:179]:  Hostname: waveshare-p4-nano-camera
[15:24:17][C][esp32_camera_web_server:088]: ESP32 Camera Web Server:
[15:24:17][C][esp32_camera_web_server:088]:  Port: 8080
[15:24:17][C][esp32_camera_web_server:093]:   Mode: stream
[15:24:17][C][esp32_camera_web_server:088]: ESP32 Camera Web Server:
[15:24:17][C][esp32_camera_web_server:088]:  Port: 8081
[15:24:17][C][esp32_camera_web_server:095]:   Mode: snapshot
[15:24:17][E][esp32_camera_web_server:099]:   Setup Failed
[15:24:17][E][component:154]:   esp32_camera_web_server is marked FAILED: unspecified

can you help?

2025-11-06 15:34 UTC, DT-art1 commented
Thanks for the log output!
I’ve added some additional error logging to the esp32_camera_web_server component to make it easier to identify what’s causing the initialization issue.

When you have a moment, please update / reinstall your setup and run it again.
Also, please lower the refresh interval in your config so the new logs are definitely applied

**refresh: 60s**

Then post the new log output here — that should give us a much clearer picture.
Thanks!

2025-11-06 18:55 UTC, hubecker commented
I did a clean build file and a new install, but no newa, same error:
INFO Upload took 2.57 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from 192.168.178.129 using esphome API
INFO Successfully resolved waveshare-p4-nano-camera @ 192.168.178.129 in 0.000s
INFO Successfully connected to waveshare-p4-nano-camera @ 192.168.178.129 in 5.129s
INFO Successful handshake with waveshare-p4-nano-camera @ 192.168.178.129 in 0.200s
[19:47:55.482][I][app:185]: ESPHome version 2025.10.4 compiled on Nov  6 2025, 19:47:23
[19:47:55.489][C][logger:261]: Logger:
[19:47:55.489][C][logger:261]:   Max Level: DEBUG
[19:47:55.489][C][logger:261]:   Initial Level: DEBUG
[19:47:55.496][C][logger:267]:   Log Baud Rate: 115200
[19:47:55.496][C][logger:267]:   Hardware UART: USB_CDC
[19:47:55.501][C][logger:274]:   Task Log Buffer Size: 768
[19:47:55.506][C][logger:280]:   Level for 'camera': DEBUG
[19:47:55.511][C][logger:280]:   Level for 'esp32_camera': DEBUG
[19:47:55.518][C][logger:280]:   Level for 'esp32_camera_web_server': DEBUG
[19:47:55.526][D][text_sensor:085]: 'ESP DNS Address': Sending state '192.168.178.1 0.0.0.0'
[19:47:55.529][C][i2c.idf:081]: I2C Bus:
[19:47:55.537][C][i2c.idf:082]:   SDA Pin: GPIO7
[19:47:55.537][C][i2c.idf:082]:   SCL Pin: GPIO8
[19:47:55.537][C][i2c.idf:082]:   Frequency: 100000 Hz
[19:47:55.543][C][i2c.idf:092]:   Recovery: bus successfully recovered
[19:47:55.547][C][i2c.idf:102]: Results from bus scan:
[19:47:55.552][C][i2c.idf:108]: Found device at address 0x18
[19:47:55.557][C][i2c.idf:108]: Found device at address 0x36
[19:47:55.562][C][esp_ldo:024]: ESP LDO Channel 3:
[19:47:55.566][C][esp_ldo:025]:   Voltage: 2.500000V
[19:47:55.570][C][esp_ldo:026]:   Adjustable: NO
[19:47:55.587][C][template.text_sensor:014]: Template Sensor 'Zeit'
[19:47:55.594][C][uptime.sensor:015]: Uptime Sensor 'Uptime'
[19:47:55.594][C][uptime.sensor:015]:   State Class: 'total_increasing'
[19:47:55.594][C][uptime.sensor:015]:   Unit of Measurement: 's'
[19:47:55.594][C][uptime.sensor:015]:   Accuracy Decimals: 0
[19:47:55.600][C][uptime.sensor:025]:   Device Class: 'duration'
[19:47:55.605][C][uptime.sensor:029]:   Icon: 'mdi:timer-outline'
[19:47:55.610][C][uptime.sensor:033]:   Type: Seconds
[19:47:55.613][C][psram:016]: PSRAM:
[19:47:55.617][C][psram:019]:   Available: YES
[19:47:55.621][C][psram:021]:   Size: 32768 KB
[19:47:55.630][C][homeassistant.time:010]: Home Assistant Time:
[19:47:55.630][C][homeassistant.time:010]:   Timezone: 'CET-1CEST,M3.5.0,M10.5.0/3'
[19:47:55.638][C][version.text_sensor:014]: Version Text Sensor 'ESPHome Version'
[19:47:55.642][C][version.text_sensor:021]:   Icon: 'mdi:new-box'
[19:47:55.649][C][restart:087]: Restart Switch 'Restart'
[19:47:55.649][C][restart:087]:   Restore Mode: always OFF
[19:47:55.654][C][restart:095]:   Icon: 'mdi:restart'
[19:47:55.671][C][ethernet:384]: Ethernet:
[19:47:55.680][C][ethernet:640]:   IP Address: 192.168.178.129
[19:47:55.680][C][ethernet:640]:   Hostname: 'waveshare-p4-nano-camera'
[19:47:55.680][C][ethernet:640]:   Subnet: 255.255.255.0
[19:47:55.680][C][ethernet:640]:   Gateway: 192.168.178.1
[19:47:55.680][C][ethernet:640]:   DNS1: 192.168.178.1
[19:47:55.680][C][ethernet:640]:   DNS2: 0.0.0.0
[19:47:55.689][C][ethernet:661]:   MAC Address: 30:ED:A0:E2:54:2A
[19:47:55.689][C][ethernet:661]:   Is Full Duplex: YES
[19:47:55.689][C][ethernet:661]:   Link Speed: 100
[19:47:55.693][C][ethernet:407]:   Power Pin: 51
[19:47:55.701][C][ethernet:409]:   CLK Pin: 50
[19:47:55.701][C][ethernet:409]:   MDC Pin: 31
[19:47:55.701][C][ethernet:409]:   MDIO Pin: 52
[19:47:55.701][C][ethernet:409]:   PHY addr: 1
[19:47:55.705][C][ethernet:416]:   Type: IP101
[19:47:55.712][C][ethernet_info:014]: EthernetInfo IPAddress 'ESP IP Address'
[19:47:55.722][C][ethernet_info:014]: EthernetInfo DNS Address 'ESP DNS Address'
[19:47:55.723][C][ethernet_info:021]:   Icon: 'mdi:ip'
[19:47:55.730][C][ethernet_info:014]: EthernetInfo MAC Address 'ESP MAC Address'
[19:47:55.736][C][ethernet_info:021]:   Icon: 'mdi:access-point-network'
[19:47:55.744][C][web_server:317]: Web Server:
[19:47:55.744][C][web_server:317]:   Address: waveshare-p4-nano-camera.local:80
[19:47:55.753][C][sntp:059]: SNTP Time:
[19:47:55.753][C][sntp:062]:   Server 0: '0.pool.ntp.org'
[19:47:55.757][C][sntp:062]:   Server 1: '1.pool.ntp.org'
[19:47:55.762][C][sntp:062]:   Server 2: '2.pool.ntp.org'
[19:47:55.772][C][esphome.ota:093]: Over-The-Air updates:
[19:47:55.772][C][esphome.ota:093]:   Address: waveshare-p4-nano-camera.local:3232
[19:47:55.772][C][esphome.ota:093]:   Version: 2
[19:47:55.782][C][safe_mode:018]: Safe Mode:
[19:47:55.782][C][safe_mode:018]:   Successful after: 60s
[19:47:55.782][C][safe_mode:018]:   Invoke after: 10 attempts
[19:47:55.782][C][safe_mode:018]:   Duration: 300s
[19:47:55.793][C][api:222]: Server:
[19:47:55.793][C][api:222]:   Address: waveshare-p4-nano-camera.local:6053
[19:47:55.793][C][api:222]:   Listen backlog: 4
[19:47:55.793][C][api:222]:   Max connections: 8
[19:47:55.798][C][api:229]:   Noise encryption: YES
[19:47:55.806][C][camera:182]: Camera:
[19:47:55.806][C][camera:182]:   Name: Camera
[19:47:55.806][C][camera:182]:   Idle update: 0 ms
[19:47:55.806][C][camera:182]:   Max update: 100 ms
[19:47:55.815][C][camera:034]:   Task:
[19:47:55.815][C][camera:034]:     Core: 1
[19:47:55.815][C][camera:034]:     Stack Size: 4096
[19:47:55.815][C][camera:034]:     Priority: 1
[19:47:55.815][C][camera:034]:     Delay: 5
[19:47:55.824][C][camera_pipeline:041]: Inputer: input
[19:47:55.824][C][camera_pipeline:041]:   IMAGE_FORMAT_RAW
[19:47:55.824][C][camera_pipeline:041]:   Retry Limit: 10
[19:47:55.824][C][camera_pipeline:041]:   Job: NO
[19:47:55.846][C][camera_sensor:226]: Camera Sensor: OV5647
[19:47:55.846][C][camera_sensor:226]:   MIPI_2lane_24Minput_RAW8_800x640_50fps
[19:47:55.846][C][camera_sensor:226]:   PIXEL_FORMAT_RGB565
[19:47:55.846][C][camera_sensor:226]:   Flip X: NO, Y: NO, Factory X: YES
[19:47:55.846][C][camera_sensor:226]:   Buffers: 2
[19:47:55.846][C][camera_sensor:226]:   Test Pattern: NO
[19:47:55.846][C][camera_sensor:226]:   MIPI-CSI:
[19:47:55.846][C][camera_sensor:226]:     Clock: 400 MHz
[19:47:55.846][C][camera_sensor:226]:     Lanes: 2
[19:47:55.846][C][camera_sensor:226]:     Line Sync: YES
[19:47:55.851][C][camera_sensor:241]:   Address: 0x36
[19:47:55.859][C][camera_sensor:101]: ISP:
[19:47:55.859][C][camera_sensor:101]:   Bayer Pattern:
[19:47:55.859][C][camera_sensor:101]:     Reported: GBRG
[19:47:55.859][C][camera_sensor:101]:     In Use: AUTO
[19:47:55.871][C][camera_pipeline:016]: Outputer: encode
[19:47:55.871][C][camera_pipeline:016]:   Buffers: 2
[19:47:55.871][C][camera_pipeline:016]:   Size: 207360
[19:47:55.871][C][camera_pipeline:016]:   Requester: IDLE, API, WEB
[19:47:55.871][C][camera_pipeline:016]:   Encoder: YES
[19:47:55.871][C][camera_pipeline:016]:   Job: NO
[19:47:55.883][C][camera_encoder:067]: Accelerated JPEG Encoder:
[19:47:55.883][C][camera_encoder:067]:   Size: 1048576
[19:47:55.883][C][camera_encoder:067]:   Quality: 40
[19:47:55.883][C][camera_encoder:067]:   Timeout: 100
[19:47:55.883][C][camera_encoder:067]:   SUBSAMPLING_444
[19:47:55.886][C][pipeline:149]: Pipeline:
[19:47:55.890][C][pipeline:154]:   input -> encode
[19:47:55.897][C][mdns:179]: mDNS:
[19:47:55.897][C][mdns:179]:   Hostname: waveshare-p4-nano-camera
[19:47:55.908][C][homeassistant.text_sensor:014]: Homeassistant Text Sensor 'Weather Forecast from HA'
[19:47:55.913][C][homeassistant.text_sensor:024]:   Entity ID: 'weather.forecast_home'
[19:47:55.917][C][debug:018]: Debug component:
[19:47:55.921][D][debug:033]: ESPHome version 2025.10.4
[19:47:55.926][D][debug:037]: Free Heap Size: 446376 bytes
[19:47:55.934][D][debug:182]: Chip: Model=ESP32-P4, Features= Cores=2, Revision=100
[19:47:55.938][D][debug:191]: CPU Frequency: 360 MHz
[19:47:55.942][D][debug:199]: Framework: ESP-IDF
[19:47:55.947][D][debug:206]: ESP [...]

2025-11-06 19:01 UTC, DT-art1 commented
I forgot to mentions that the esp32_camera_web_server needs to be added in your YAML:
```
external_components:
  - source: github://pr#7639
    components: [camera, camera_encoder, camera_pipeline, camera_sensor, esp32_camera, esp32_camera_web_server]
    refresh: 0s
```

2025-11-06 19:06 UTC, hubecker commented
Now i get this error:
INFO ESPHome 2025.10.4
INFO Reading configuration /config/esphome/esp32-p4-nano-cam.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/7639/head
INFO Detected timezone 'Europe/Berlin'
INFO Detected timezone 'Europe/Berlin'
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1387, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1362, in run_esphome
    config = read_config(
             ^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 1238, in read_config
    res = load_config(command_line_substitutions, skip_external_update)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 1095, in load_config
    return _load_config(command_line_substitutions, skip_external_update)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 1083, in _load_config
    return validate_config(config, command_line_substitutions, skip_external_update)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/config.py", line 1005, in validate_config
    result.run_validation_steps()
  File "/esphome/esphome/config.py", line 201, in run_validation_steps
    task.step.run(self)
  File "/esphome/esphome/config.py", line 702, in run
    validated = schema(self.conf)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/voluptuous_schema.py", line 37, in __call__
    res = super().__call__(data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 205, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/validators.py", line 256, in _run
    return self._exec(self._compiled, value, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/validators.py", line 384, in _exec
    v = func(path, v)
        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/data/external_components/11da8824/esphome/components/esp32_camera_web_server/__init__.py", line 24, in _consume_camera_web_server_sockets
    socket.consume_sockets(sockets_needed, "esp32_camera_web_server")(config)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'esphome.components.socket' has no attribute 'consume_sockets'

2025-11-06 19:37 UTC, DT-art1 commented
Here is the explanation of the problem you are facing:

https://github.com/esphome/esphome/pull/11378

I assume this will be included in the 2025.11.1 release.

Currently, you have a few options:
1) Drop the snapshot port. This frees up 3 additional sockets:

```
external_components:
  - source: github://pr#7639
    components: [camera, camera_encoder, camera_pipeline, camera_sensor, esp32_camera]
    refresh: 0s

esp32_camera_web_server:
  - port: 8080
    mode: stream
  # - port: 8081
  #   mode: snapshot

```
2) Remove esp32_camera_web_server from your configuration and test only in Home Assistant.
3) Build ESPHome from source, that includes the changes in the socket component.

Hope it help!

2025-11-06 21:02 UTC, hubecker commented
Thanks for the info:
1. Doesn't work, i get the same error
2. Does work, i can download a snapshot jpg file, but it seems to be the wrong format.
3. Unfortunatly is this no option for me

so i have to wait for 2025.11.1 release hopefully not to far away.

Thanks for your help

2025-11-08 13:30 UTC, hubecker commented
Hi,
I switched to esphome dev and was able to compile and upload the firmware.
Unfortunatly with an error, see attached log.
[logs_esp32-p4-nano-cam_logs.txt](https://github.com/user-attachments/files/23432066/logs_esp32-p4-nano-cam_logs.txt)

2025-11-08 13:49 UTC, DT-art1 commented
I have an error detection mechanism in the input stage which retries capturing a frame from the camera sensor. If it fails a certain number of times, it gives up under the assumption that the sensor setup is not correct. The default limit is 10 retries, which may be too low.

Please try increasing it in your configuration:
```
camera_pipeline:
  - id: input
    type: input
    retries: 100
    next: encode
```

I may have chosen the default limit too low.

Thank you very much for testing!

2025-11-09 16:17 UTC, hubecker commented
Hi, again same result.
[logs_esp32-p4-nano-cam_run.txt](https://github.com/user-attachments/files/23440496/logs_esp32-p4-nano-cam_run.txt)

2025-11-09 17:00 UTC, DT-art1 commented
Everything in the logs looks good — the timeout just means that the camera sensor isn’t sending any data.
I suspect there might be an issue with the connection cable between the board and the sensor.

You can also try setting:

```
camera_pipeline:
  - id: input
    type: input
    retries: 0
    next: encode
```

That disables the timeout, but I don’t think the problem is there.

Just to confirm — are you using the [ Waveshare Nano](https://www.waveshare.com/wiki/ESP32-P4-Nano-StartPage) board?
Have you ever been able to get an image from this camera sensor before?

2025-11-09 21:29 UTC, hubecker commented
Yes you are right. The problem still exists. I also checked the cable, it should be ok. 
The red light on the camera is on, so i guess the camera is working.
And yes i have the Waveshare NANO board. Right now i was not able to get any image from the camera.
I have also the [Waveshare ESP32-P4-Module-DEV-KIT](https://www.waveshare.com/wiki/ESP32-P4-Module-DEV-KIT-StartPage#Overview) with camera and touch. i will test the code with this kit next week.


I used the camera from the ESP32-P4-Module-DEV-KIT and can confirm this one is working.

2025-11-10 07:26 UTC, DT-art1 commented
@bdraco

As I’ve seen a few people asking for MIPI-CSI camera support, I’ve adjusted this PR. The architecture has now evolved and is in a good state to support multiple use cases.

Before I move forward, I’d like to hear your opinion on how to best integrate this into ESPHome. Since I know large PRs are hard to review, I’m planning to split the MIPI-CSI support into about five smaller PRs.

Here’s a possible integration plan:
	1.	Refactor the ESP32 Camera component — move shared functionality into the core Camera component.
	2.	Add Camera Pipeline to the Camera component, with the necessary interfaces.
	3.	Accelerated JPEG Encoder.
	4.	CSI Camera Sensor + ISP.
	5.	Camera Pipeline Component (standalone), including Inputer, Outputer, and Accelerated Scaler.

There are two existing PRs somewhat related to this work:
- #10716 — introduces the Camera Sensor interface used by the CSI Camera Sensor, and provides a Software Camera implementation.
I can merge the interface part into the “CSI Camera Sensor + ISP” PR if the Software Camera support is not immediately needed.
- #10378 (AMG8833 Thermal Cam) — I added Use Case 6, showing how the Software Camera Sensor can generate a thermal image.

What do you think about this plan?
Thank you very much for your time and feedback!

2025-11-14 18:21 UTC, youkorr commented
Hi DT-art1, I've made good progress.
[18:58:18][D][camera_web_server:282][httpd]: Frame captured: 800x640 RGB565 = 1024000 bytes
[18:58:18][D][camera_web_server:311][httpd]: JPEG encoded: 64459 bytes (quality=80)
[18:58:18][I][lvgl_camera_display:100]: 🎞️ 300 frames - FPS: 26.87 | capture: 33.2ms | canvas: 0.0ms | skip: 0.0%



```
[18:57:30][D][esp-idf:000][esp_video_init]: E (1690) esp_video_init: 
[18:57:30][D][esp-idf:000][esp_video_init]: E (1691) esp_video_init: 🔍 Starting sensor detection loop...
[18:57:30][D][esp-idf:000][esp_video_init]: E (1692) esp_video_init:   DEBUG: __esp_cam_sensor_detect_fn_array_start = 0x4ff11b40[0
[18:57:30][D][esp-idf:000][esp_video_init]: E (1693) esp_video_init:   DEBUG: &__esp_cam_sensor_detect_fn_array_end = 0x4ff11b64
[18:57:30][D][esp-idf:000][esp_video_init]: E (1694) esp_video_init:   DEBUG: Pointer difference = 36 bytes
[18:57:30][D][esp-idf:000][esp_video_init]: E (1695) esp_video_init:   DEBUG: sizeof(esp_cam_sensor_detect_fn_t) = 12 bytes
[18:57:30][D][esp-idf:000][esp_video_init]: E (1696) esp_video_init: 
[18:57:30][D][esp-idf:000][esp_video_init]: E (1697) esp_video_init:   Checking sensor at 0x4ff11b40: port=1, sccb_addr=0x36, detect
[18:57:30][D][esp-idf:000][esp_video_init]: E (1698) esp_video_init:   → Attempting to detect MIPI-CSI sensor...
[18:57:30][D][esp-idf:000][esp_video_init]: E (1699) esp_video_init:   🔧 Calling detect function at 0x40057d7c with config:
[18:57:30][D][esp-idf:000][esp_video_init]: E (1700) esp_video_init:      sccb_handle=0x48006f3c, reset_pin=-1, pwdn_pin=-1
[18:57:30][D][esp-idf:000][esp_video_init]: E (1701) esp_video_init:      xclk_pin=36, xclk_freq=24000000 Hz
[18:57:30][D][esp-idf:000][esp_video_init]: E (1703) sc202cs: Camera sensor is not SC202CS, PID=0x0
[18:57:30][D][esp-idf:000][esp_video_init]: E (1704) esp_video_init:   📡 detect() returned: cam_dev=0x0
[18:57:30][D][esp-idf:000][esp_video_init]: E (1705) esp_video_init:   ✗ Sensor detection FAILED for address 0x36 (cam_dev is NULL
[18:57:30][D][esp-idf:000][esp_video_init]: E (1706) esp_video_init:   Checking sensor at 0x4ff11b4c: port=1, sccb_addr=0x36, detect
[18:57:30][D][esp-idf:000][esp_video_init]: E (1707) esp_video_init:   → Attempting to detect MIPI-CSI sensor...
[18:57:30][D][esp-idf:000][esp_video_init]: E (1708) esp_video_init:   🔧 Calling detect function at 0x40057452 with config:
[18:57:30][D][esp-idf:000][esp_video_init]: E (1709) esp_video_init:      sccb_handle=0x48006f3c, reset_pin=-1, pwdn_pin=-1
[18:57:30][D][esp-idf:000][esp_video_init]: E (1710) esp_video_init:      xclk_pin=36, xclk_freq=24000000 Hz
[18:57:30][D][esp-idf:000][esp_video_init]: E (1712) esp_video_init:   📡 detect() returned: cam_dev=0x4ff2dd44
[18:57:30][D][esp-idf:000][esp_video_init]: E (1713) esp_video_init:   ✅ Sensor detection SUCCEEDED! cam_dev->name=OV5647, cam_dev
[18:57:30][D][esp-idf:000][esp_video_init]: E (1714) esp_video_init:   🔧 About to call esp_video_create_csi_video_device(cam_dev=
[18:57:30][D][esp-idf:000][esp_video_init]: E (1715) esp_video_init:   📡 esp_video_create_csi_video_device() returned: ret=0 (ESP
[18:57:30][D][esp-idf:000][esp_video_init]: E (1716) esp_video_init:   ✅ MIPI-CSI video device created successfully - /dev/video0 
[18:57:30][D][esp-idf:000][esp_video_init]: E (1717) esp_video_init: 
[18:57:30][D][esp-idf:000][esp_video_init]: E (1718) esp_video_init: ========================================
[18:57:30][D][esp-idf:000][esp_video_init]: E (1719) esp_video_init: 🔍 DEBUG: esp_video_init() reached ISP configuration section
[18:57:30][D][esp-idf:000][esp_video_init]: E (1720) esp_video_init:   cam_dev=0x4ff2dd44
[18:57:30][D][esp-idf:000][esp_video_init]: E (1721) esp_video_init:   cam_dev->name=OV5647
[18:57:30][D][esp-idf:000][esp_video_init]: E (1722) esp_video_init:   cam_dev->cur_format=0x40190d84
[18:57:30][D][esp-idf:000][esp_video_init]: E (1754) esp_video_init:   Checking sensor at 0x4ff11b58: port=1, sccb_addr=0x36, detect
[18:57:30][W][esp_video:311]:    ✅ /dev/video0 existe et accessible (CSI video device - capteur détecté!)
[18:57:30][W][esp_video:312]:       File descriptor: 6
[18:57:30][W][esp_video:321]:    ✅ /dev/video10 existe (JPEG encoder)
[18:57:30][W][esp_video:327]:    ✅ /dev/video11 existe (H.264 encoder)
[18:57:30][W][esp_video:333]:    ✅ /dev/video20 existe (ISP device)
[18:57:30][W][esp_video:348]:    ✅ I2C lecture réussie: Chip ID = 0x0000 (attendu: 0xEB52 pour SC202CS)
[18:57:30][W][esp_video:352]:       ❌ ID invalide - XCLK probablement inactif ou capteur déconnecté
[18:57:30][I][esp_video:378]: ✅ ISP Pipeline active - IPA algorithms running
[18:57:30][I][esp_video:390]: esp-video: ok
[18:57:30][C][component:173]: Setup esp_video took 74ms
[18:57:30][I][mipi_dsi_cam:220]: PPA not needed (no mirror/rotate/crop configured)
[18:57:30][I][mipi_dsi_cam:394]: esp-cam-sensor: ok (ov5647)
[18:57:30][I][mipi_dsi_cam:395]: esp-video-isp: ok
[18:57:30][I][mipi_dsi_cam:396]: jpeg-encoder: ok
[18:57:30][I][mipi_dsi_cam:397]: h264-encoder: ok
[18:57:30][I][mipi_dsi_cam:398]: Camera ready: RGB565 @ 800x640 (30 fps)
```

2025-11-14 18:26 UTC, youkorr commented
I still need to test H264

2025-11-24 07:13 UTC, closed without merging