new component i2c_device
OttoWinter/esphomeyaml pull request #7641
Opened 2024-10-20 16:47 UTC by gabest11

# What does this implement/fix?

This is just a simple barebone i2c_device, similar to the spi_device, that can be used to quickly test i2c devices using lambdas, without writing a new component.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4356

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

Quick setup of the QN8027 FM transmitter to broadcast a web stream from media_player.

```yaml

esphome:
  on_boot:
    then: 
      - wait_until:
          timeout: 15s
          condition:
            and:
              - wifi.connected
              - media_player.is_idle
      - media_player.play_media: '__INSERT_STREAM_URL_HERE'
      - media_player.volume_set: 50%
      - script.execute: 
          id: qn8027_setup
          freq: 87.50f

logger:
  level: VERBOSE

i2c:
  sda: 10
  scl: 9
  scan: True

i2c_device:
  id: i2cdev
  address: 0x2C

i2s_audio:
  i2s_lrclk_pin: 4
  i2s_bclk_pin: 6

media_player:
  - platform: i2s_audio
    name: "Media Player"
    dac_type: external
    i2s_dout_pin: 5
    mode: stereo
      
interval:
  - interval: 5s
    then:
    - lambda: |-
        if (auto b = id(i2cdev).read_byte(0x07)) {
          ESP_LOGD("QN8027", "QN8027 status %d", *b & 7);
        }

script:
  - id: qn8027_setup
    parameters:
      freq: float
    then:
      - lambda: |-
          uint8_t CID[5] = { 0, 0, 0, 0, 0 };
          if (auto b = id(i2cdev).read_byte(0x05)) {
            CID[2] = (*b >> 0) & 3;
            CID[1] = (*b >> 2) & 7;
            CID[0] = (*b >> 5) & 7;
          }
          if (auto b = id(i2cdev).read_byte(0x06)) {
            CID[4] = (*b >> 4) & 15;
            CID[3] = (*b >> 4) & 15;
          }
          if (CID[3] == 4 && CID[1] == 0) { // QN8027 && FM
            ESP_LOGD("QN8027", "QN8027 found");
            id(i2cdev).write_byte(0x00, 0x80); // reset
            delay_microseconds_safe(10000);
            id(i2cdev).write_byte(0x00, 0x40); // calibrate
            delay_microseconds_safe(10000);
            //float freq = 87.50f;
            uint16_t ch = (uint16_t) ((freq - 76) * 20);
            ESP_LOGD("QN8027", "QN8027 tuning to %.2f %d", freq, ch);
            id(i2cdev).write_byte(0x00, (1 << 5) | ((ch >> 8) & 3)); // tx enable | ch[9:8]
            id(i2cdev).write_byte(0x01, ch & 0xff); // ch[7:0]
            id(i2cdev).write_byte(0x02, 0b00111001);
            id(i2cdev).write_byte(0x03, 0b00010000);
            id(i2cdev).write_byte(0x04, 0b10110010);
            id(i2cdev).write_byte(0x10, 0b01111111);
            id(i2cdev).write_byte(0x11, 0b10000001);
          } else {
            ESP_LOGE("QN8027", "QN8027 was not found");
          }

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-20 20:14 UTC, jesserockz requested changes

2024-10-20 20:14 UTC, jesserockz commented on esphome/components/i2c_device/__init__.py
> +MULTI_CONF = True
Small nitpick =)
```suggestion
CODEOWNERS = ["@gabest11"]
DEPENDENCIES = ["i2c"]
MULTI_CONF = True

```

2024-10-20 20:14 UTC, jesserockz commented on esphome/components/i2c_device/__init__.py
> +i2c_device = i2c_device_ns.class_("I2CDeviceComponent", cg.Component, i2c.I2CDevice)
Variable names should always match the c++ class name
```suggestion
I2CDeviceComponent = i2c_device_ns.class_("I2CDeviceComponent", cg.Component, i2c.I2CDevice)
```

2024-10-20 20:14 UTC, jesserockz commented on esphome/components/i2c_device/__init__.py
> +        cv.GenerateID(CONF_ID): cv.declare_id(i2c_device),
```suggestion
        cv.GenerateID(CONF_ID): cv.declare_id(I2CDeviceComponent),
```

2024-10-20 20:21 UTC, gabest11 commented
Well, it was a copypasta from spi_device. Just changed SPI to I2S. And removed irrelevant config.

2024-10-22 03:59 UTC, jesserockz requested changes
Please make sure to add some tests to fulfill the `needs-tests` requirement =)
Otherwise this code looks good.

2024-10-23 01:50 UTC, gabest11 commented
I put the test files there three days ago, but somehow they were not added to git.

2024-10-23 03:19 UTC, jesserockz approved these changes

2024-10-23 03:23 UTC, merged