Add Nextion actions
OttoWinter/esphomeyaml pull request #7646
Opened 2024-10-21 08:41 UTC by pkejval

# What does this implement/fix?

Adds YAML actions for publishing states of various Nextion sensors. This functionality was available only in lambdas.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

none

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#4360

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: test2
  on_boot: 
    then:
      - sensor.nextion.publish:
          id: nex_kph
          state: 1
          publish_state: false
          send_to_nextion: true

      - binary_sensor.nextion.publish:
          id: nex_binary
          state: True

      - text_sensor.nextion.publish:
          id: nex_text
          state: "TEST"

      - switch.nextion.publish:
          id: nex_switch
          state: True

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

logger:
api:
ota:
  platform: esphome

wifi:
  ssid: !secret wifi
  password: !secret wifi_pass
  reboot_timeout: 0s

external_components:
  - source:
      type: git
      url: https://github.com/pkejval/esphome
      ref: main
    components: [ nextion ]
    refresh: 0s

sensor:
  - platform: nextion
    id: nex_float
    nextion_id: nex
    component_name: test.float
    precision: 0

binary_sensor:
  - platform: nextion
    id: nex_binary
    component_name: test.binary

text_sensor:
  - platform: nextion
    id: nex_text
    component_name: test.text

switch:
  - platform: nextion
    id: nex_switch
    component_name: test.switch

uart:
  - id: ser
    rx_pin: GPIO16
    tx_pin: GPIO17
    baud_rate: 115200

display:
  - platform: nextion
    id: nex
    uart_id: ser
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-24 23:24 UTC, kbx81 submitted a review, later dismissed
LGTM -- @edwardtfn any thoughts/comments?

2024-10-25 03:17 UTC, edwardtfn commented
It looks awesome.

2024-10-30 04:28 UTC, kbx81 commented
One final thought/request @pkejval -- please update the tests for this component to include these actions.

2024-11-01 06:39 UTC, pkejval commented
I wrote some tests but I have **no idea how to run them**. Cannot find any documentation about it. Can you give me advice, please?

2024-11-03 07:30 UTC, kbx81 commented
From the root of the repo: `./script/test_build_components -e compile -c nextion`

2024-11-17 06:27 UTC, edwardtfn commented on tests/components/nextion/test.esp32-ard.yaml
It should be:

```yaml
substitutions:
  tx_pin: '17'
  rx_pin: '16'
```

2024-11-17 07:36 UTC, kbx81 requested changes
Fixes so tests will work

2024-11-17 07:36 UTC, kbx81 commented on tests/components/nextion/test.esp32-ard.yaml
> +  rx_pin: 16
```suggestion
  tx_pin: GPIO17
  rx_pin: GPIO16
```

2024-11-17 07:36 UTC, kbx81 commented on tests/components/nextion/test.esp32-c3-ard.yaml
> +  rx_pin: 5
```suggestion
  tx_pin: GPIO4
  rx_pin: GPIO5
```

2024-11-17 07:36 UTC, kbx81 commented on tests/components/nextion/test.esp32-c3-idf.yaml
> +  rx_pin: 5
```suggestion
  tx_pin: GPIO4
  rx_pin: GPIO5
```

2024-11-17 07:36 UTC, kbx81 commented on tests/components/nextion/test.esp32-idf.yaml
> +  rx_pin: 16
```suggestion
  tx_pin: GPIO17
  rx_pin: GPIO16
```

2024-11-17 07:36 UTC, kbx81 commented on tests/components/nextion/test.esp8266-ard.yaml
> +  rx_pin: 5
```suggestion
  tx_pin: GPIO4
  rx_pin: GPIO5
```

2024-11-17 07:36 UTC, kbx81 commented on tests/components/nextion/test.rp2040-ard.yaml
> +  rx_pin: 5
```suggestion
  tx_pin: GPIO4
  rx_pin: GPIO5
```

2024-11-17 07:44 UTC, kbx81 requested changes
Fix binary sensor IDs in tests

2024-11-17 07:44 UTC, kbx81 commented on tests/components/nextion/common.yaml
> +        id: r0
```suggestion
        id: r0_sensor
```

2024-11-17 07:44 UTC, kbx81 commented on tests/components/nextion/common.yaml
> +        id: r0
```suggestion
        id: r0_sensor
```

2024-11-17 07:44 UTC, kbx81 commented on tests/components/nextion/common.yaml
> +        id: r0
```suggestion
        id: r0_sensor
```

2024-11-17 07:44 UTC, kbx81 commented on tests/components/nextion/common.yaml
> +        id: r0
```suggestion
        id: r0_sensor
```

2024-11-17 07:44 UTC, kbx81 commented on tests/components/nextion/common.yaml
> +        id: r0
```suggestion
        id: r0_sensor
```

2024-11-17 07:44 UTC, kbx81 commented on tests/components/nextion/common.yaml
> +        id: r0
```suggestion
        id: r0_sensor
```

2024-11-17 07:44 UTC, kbx81 commented on tests/components/nextion/common.yaml
> +        id: r0
```suggestion
        id: r0_sensor
```

2024-11-17 07:44 UTC, kbx81 commented on tests/components/nextion/common.yaml
> +        id: r0
```suggestion
        id: r0_sensor
```

2024-11-17 07:44 UTC, kbx81 commented on tests/components/nextion/common.yaml
> +        id: r0
```suggestion
        id: r0_sensor
```

2024-11-17 07:44 UTC, kbx81 commented on tests/components/nextion/common.yaml
> +        id: r0
```suggestion
        id: r0_sensor
```

2024-11-17 07:57 UTC, kbx81 commented on tests/components/nextion/test.rp2040-ard.yaml
> +wifi: !remove
HTTP client **requires** wifi

2024-11-17 07:57 UTC, kbx81 commented on tests/components/nextion/test.rp2040-ard.yaml
> +wifi: !remove
```suggestion
```

2024-11-17 09:02 UTC, kbx81 approved these changes, later dismissed
LGTM -- thanks!

2024-11-23 04:51 UTC, kbx81 approved these changes

2024-11-23 04:52 UTC, merged