updating ESP32 board definitions
OttoWinter/esphomeyaml pull request #7650
Opened 2024-10-22 00:13 UTC by asolochek

# What does this implement/fix?

This adds the pin mappings for missing adafruit boards and a couple of missing pin definitions for wesp32. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esp32:
  board: adafruit_qtpy_esp32s3_nopsram

i2c:
  - id: bus_a
    sda: SDA1
    scl: SCL1
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-22 01:06 UTC, jesserockz requested changes

2024-10-22 01:06 UTC, jesserockz commented on esphome/components/esp32/boards.py
> +        "D5": 5,
Looking at the images of the board, the silkscreen does not label these as Dx so this is not needed.
```suggestion
```

2024-10-22 01:25 UTC, asolochek commented on esphome/components/esp32/boards.py
> +        "D5": 5,
I think you looked at the wrong board. This board does have those pins exposed and labelled. https://learn.adafruit.com/assets/110811

2024-10-22 03:48 UTC, jesserockz commented on esphome/components/esp32/boards.py
> +        "D5": 5,
The pin definition we put in this file are supposed to be silkscreen to gpio pin number. The silkscreen on the physical board shows only 13, 12, etc. No `D`.

2024-10-22 03:49 UTC, jesserockz commented on esphome/components/esp32/boards.py
> +        "D5": 5,
The Dx thing is something that is brought from the Arduino world, which we want to avoid as much as possible.

2024-10-22 04:53 UTC, asolochek commented on esphome/components/esp32/boards.py
> +        "D5": 5,
Ok. I was trying to be consistent with the other boards, but at least for these adafruit boards the DXX pins correspond directly to GPIOXX, so I suppose it doesn't matter much. Although I'd think users might expect to be able to use DXX because of the adafruit documentation for the boards. 

Out of curiosity though, if the board had only numbers on the silk screen, and they didn't correspond to the same GPIO numbers, what convention would be used? DIOXX? IOXX?

2024-10-24 00:25 UTC, jesserockz approved these changes

2024-10-24 00:25 UTC, merged