[fix] deprecated legacy driver tsens
OttoWinter/esphomeyaml pull request #7658
Opened 2024-10-22 17:08 UTC by rvalitov

# What does this implement/fix?

Since ESP-IDF 5.0 the `tsens` temperature driver is considered to be legacy and deprecated. The console shows warning:
```
tsens: legacy driver is deprecated, please migrate to driver/temperature_sensor.h
```

It's caused by the component `internal_temperature`. This PR uses the new `driver/temperature_sensor.h`.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):** https://github.com/esphome/issues/issues/6367

- fixes https://github.com/esphome/issues/issues/6367

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: test
  friendly_name: Test
  platformio_options:
    board_build.flash_mode: dio 

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
      CONFIG_OPENTHREAD_ENABLED: n
      CONFIG_ENABLE_WIFI_STATION: y
      CONFIG_USE_MINIMAL_MDNS: y

     
# Enable logging
logger:
  level: VERBOSE

sensor:
  - platform: internal_temperature
    id: esp_internal_temperature
    name: "Internal Temperature"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-22 17:31 UTC, rvalitov commented
Note: default values were taken from the old default config https://github.com/espressif/esp-idf/blob/v5.3.1/components/driver/deprecated/driver/temp_sensor_types_legacy.h

2024-10-23 17:59 UTC, jesserockz requested changes

2024-10-23 17:59 UTC, jesserockz commented on esphome/components/internal_temperature/internal_temperature.cpp
> +  }
Please move this to `setup()` and remove the static bools. Use `this->mark_failed()` if it could not be installed or enabled during setup

2024-10-24 21:53 UTC, rvalitov commented on esphome/components/internal_temperature/internal_temperature.cpp
> +  }
Ok, I'm a little confused, at what file is the `setup()` function is defined?

2024-10-24 21:58 UTC, jesserockz commented on esphome/components/internal_temperature/internal_temperature.cpp
> +  }
Each class that inherits `Component` can override `setup()` and do things it needs to once during the setup of the entire application.

2024-11-02 10:20 UTC, rvalitov commented on esphome/components/internal_temperature/internal_temperature.cpp
> +  }
Done, I suppose it's OK now

2024-11-03 14:30 UTC, luar123 commented
Could you also add H2 and C2 variants? I think they use the same install code.

2024-11-05 06:38 UTC, rvalitov commented
I can add and test that the code compiles well but I don't have these boards to make real tests.

2024-11-05 21:39 UTC, luar123 requested changes
I tested this with a esp32-h2 board and it is working. Could not test with esp32-c2 as it is not really supported (couldn't get logger or wifi to work). Up to you if you want to include it or not.

2024-11-05 21:39 UTC, luar123 commented on esphome/components/internal_temperature/internal_temperature.cpp
>      defined(USE_ESP32_VARIANT_ESP32S2) || defined(USE_ESP32_VARIANT_ESP32S3)
```suggestion
    defined(USE_ESP32_VARIANT_ESP32S2) || defined(USE_ESP32_VARIANT_ESP32S3) || \
    defined(USE_ESP32_VARIANT_ESP32H2) || defined(USE_ESP32_VARIANT_ESP32C2)
```

2024-11-05 21:39 UTC, luar123 commented on esphome/components/internal_temperature/internal_temperature.cpp
> +     defined(USE_ESP32_VARIANT_ESP32S3))
```suggestion
     defined(USE_ESP32_VARIANT_ESP32S3) || defined(USE_ESP32_VARIANT_ESP32H2) || defined(USE_ESP32_VARIANT_ESP32C2))
```

2024-11-05 21:39 UTC, luar123 commented on esphome/components/internal_temperature/internal_temperature.cpp
> +     defined(USE_ESP32_VARIANT_ESP32S3))
```suggestion
     defined(USE_ESP32_VARIANT_ESP32S3) || defined(USE_ESP32_VARIANT_ESP32H2) || defined(USE_ESP32_VARIANT_ESP32C2))
```

2024-11-05 21:39 UTC, luar123 commented on esphome/components/internal_temperature/internal_temperature.cpp
>      defined(USE_ESP32_VARIANT_ESP32S2) || defined(USE_ESP32_VARIANT_ESP32S3)
```suggestion
    defined(USE_ESP32_VARIANT_ESP32S2) || defined(USE_ESP32_VARIANT_ESP32S3)  || \
    defined(USE_ESP32_VARIANT_ESP32H2) || defined(USE_ESP32_VARIANT_ESP32C2)
```

2024-11-06 15:29 UTC, rvalitov commented
I will check this tomorrow and see no problem to include that. Thank you for your work!
I was just thinking that there are other Esp32 boards for example P-series that also would be nice to include. However I prefer to cover the boards that I have at my possession or that could be tested by other community members. So thank you for testing. I will be morr than happy to use your test results!

2024-11-07 08:51 UTC, rvalitov commented
@luar123 can you please share your YAML that you use for C2 and H2?

2024-11-07 16:32 UTC, luar123 commented
I used this for H2:
```yaml
esphome:
  name: h2-test
  
external_components:
  - source: github://pr#7658
    components: [ internal_temperature ]

esp32:
  board: esp32-h2-devkitm-1
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.1.4
    source: https://github.com/pioarduino/esp-idf/releases/download/v5.1.4.240921/esp-idf-v5.1.4.zip
    platform_version: https://github.com/pioarduino/platform-espressif32/releases/download/51.03.05/platform-espressif32.zip
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
  variant: esp32h2

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: verbose

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
```

And for c2 (compiles but couldn't get any logs or wifi connection):
```yaml
esphome:
  name: c2-test
  
external_components:
  - source: github://pr#7658
    components: [ internal_temperature ]

esp32:
  board: esp32-c2-devkitm-1
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.1.4
    source: https://github.com/pioarduino/esp-idf/releases/download/v5.1.4.240921/esp-idf-v5.1.4.zip
    platform_version: https://github.com/pioarduino/platform-espressif32/releases/download/51.03.05/platform-espressif32.zip
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
  variant: esp32c2

# Enable logging
logger:
  baud_rate: 74880
  hardware_uart: UART1
  #level: verbose

wifi:
  ssid: ****
  password: ****

# Enable Home Assistant API
api:

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
```

2024-11-07 16:36 UTC, luar123 approved these changes
LGTM

2024-11-07 18:00 UTC, luar123 approved these changes

2024-11-07 22:10 UTC, jesserockz approved these changes

2024-11-07 22:10 UTC, merged