Add OpenTherm component (part 3: rest of the sensors)
OttoWinter/esphomeyaml pull request #7676
Opened 2024-10-25 10:38 UTC by olegtarasov

# What does this implement/fix?

This is the third (and final) part of OpenTherm component. It contains the code to support all the sensors, inputs and outputs. Sensors configured in YAML are transformed to a set of C++ macros, which in turn generate the final code that handles sensors.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- Part 1: #6645 
- Part 2: #7529 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#3800

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# An extremely minimal configuration which only enables you to set the boiler's
# water temperature setpoint as a number.

esphome:
  name: thermostat-number-minimal

esp8266:
  board: d1_mini

opentherm:
  in_pin: IN_PIN
  out_pin: OUT_PIN

number:
  - platform: opentherm
    t_set:
      name: "Boiler Control setpoint"
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-25 11:30 UTC, olegtarasov commented
Hi @jesserockz! The final part of OpenTherm integration is ready for review. Thanks!

2024-11-03 22:35 UTC, jesserockz reviewed
How does the hub know if a switch (or other control type entity) has been changed by the user? I do not see the `add_on_state_callback`s being added.

I find it very difficult to follow and understand this component due to the heavy use of macros.

2024-11-04 05:10 UTC, olegtarasov commented
@jesserockz The hub doesn't need to know the exact moment when control entity changes because all sensors, switches and outputs are sent to OpenTherm device constantly in a loop. It's required by OpenTherm standard to communicate with device every 1 second even when there is no change in controls. So the approach when we send all the messages configured in yaml in a loop adds to component's robustness (a message can fail due to protocol error, and we don't need to use complicated retry logic — the same message will be sent again eventually).

> I find it very difficult to follow and understand this component due to the heavy use of macros.

I agree, but I see no other way to add class members dynamically, and adding > 100 class members for all the available sensors at once seems very wasteful. What's more, most of them likely won't be supported by end user's boiler.

2024-11-06 01:47 UTC, jesserockz requested changes

2024-11-06 01:47 UTC, jesserockz commented on tests/components/opentherm/common.yaml
> +      ki: 0.004
Adding this here wont achieve anything and if the `pid` component has a breaking change, these files wont be run. They should be contained to only itself and dependencies
```suggestion
```

2024-11-06 01:47 UTC, jesserockz commented on tests/components/opentherm/common.yaml
> +      - heartbeat: 1s
Same with these
```suggestion
```

2024-11-06 01:47 UTC, jesserockz commented on tests/components/opentherm/common.yaml
> +  t_room: ch_room_temperature
Just use one of the opentherm sensors here as this is a simple compile test and doesnt actually run

2024-11-06 01:47 UTC, jesserockz commented on esphome/components/opentherm/switch/switch.cpp
> +  esphome::switch_::log_switch("opentherm.switch", "", "OpenTherm Switch", this);
```suggestion
  LOG_SWITCH(TAG, "", "OpenTherm Switch", this);
```

2024-11-06 01:47 UTC, jesserockz commented on esphome/components/opentherm/switch/switch.cpp
> +
```suggestion

static const char *const TAG = "opentherm.switch";

```

2024-11-06 01:47 UTC, jesserockz commented on esphome/components/opentherm/switch/switch.cpp
> +    ESP_LOGD("opentherm.switch", "Couldn't restore state for OpenTherm switch '%s'", this->get_name().c_str());
Please update to add TAG to all the cpp files and use that for logging
```suggestion
    ESP_LOGD(TAG, "Couldn't restore state for OpenTherm switch '%s'", this->get_name().c_str());
```

2024-11-06 01:47 UTC, jesserockz commented on esphome/components/opentherm/switch/switch.cpp
> +    ESP_LOGD("opentherm.switch", "Restored state for OpenTherm switch '%s': %d", this->get_name().c_str(),
```suggestion
    ESP_LOGD(TAG, "Restored state for OpenTherm switch '%s': %d", this->get_name().c_str(),
```

2024-11-11 04:23 UTC, jesserockz approved these changes

2024-11-12 03:19 UTC, merged