[speaker] Removing the Finish() method. It is not needed anymore.
OttoWinter/esphomeyaml pull request #7677
Opened 2024-10-25 18:56 UTC by nielsnl68

# What does this implement/fix?

After deliberation with @kahrendt we came to the conclusion that Finish() procedure is not needed anymore. You can now just wait until everything is played and the speaker stops automatically.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-30 03:37 UTC, jesserockz requested changes

2024-10-30 03:37 UTC, jesserockz commented on esphome/components/speaker/__init__.py
> -)
Lets leave this in so its not a config breaking change and just change the class it uses.
```suggestion
automation.register_action("speaker.finish", StopAction, SPEAKER_AUTOMATION_SCHEMA)(
    speaker_action
)
```

2024-10-30 11:06 UTC, kahrendt commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> -        i2s_zero_dma_buffer(this_speaker->parent_->get_port());
Can you add the ``i2s_zero_dma_buffer`` back in when no data is read? Some amps will generate harsh noises if you suddenly stop writing anything via I2S, so the zeroing out prevents that.

2024-11-01 14:08 UTC, nielsnl68 commented on esphome/components/speaker/__init__.py
> -)
@jesserockz, the Stop and finish are 2 different thinks. The first stops the speaker directly while finish should wait until the everything is send out and then close the speaker.
Changing the finish action by doing the full stop as you suggested is as a breaking change as removing. it is worse, imho, because the end-user will think it will wait and found that the end of the audio stream is not being played anymore after calling finish. By removing the action totally will make the end-user investigate what is the problem and will found out that he does not need to call finish anymore instead he could wait until the speaker is stopped playing. 

One solution could be that we make `finish` a wait action until the speaker stops.

2024-11-01 14:10 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> -        i2s_zero_dma_buffer(this_speaker->parent_->get_port());
Copy of discord message:

Sorry i was busy the last couple of days. 
I have a issue with this, because when added, not all the playable content is being output to the speaker. 
When we figure out how to resolve that then it can be back,
An other solution would be (which we talked before) is setting the timeout based on the data that is received.

2024-11-11 17:02 UTC, nielsnl68 commented
This PR is not needed anymore PR https://github.com/esphome/esphome/pull/7749 fixes the need for it.

2024-11-11 17:02 UTC, closed without merging