Allow components to add custom partitions.
OttoWinter/esphomeyaml pull request #7682
Opened 2024-10-26 15:14 UTC by luar123

# What does this implement/fix?

Adds the possibility for components to add custom partitions to the esp32 partition table. 

My usecase is the [zigbee component](github.com/luar123/zigbee_esphome), which needs an additional zb_storage data partition.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example:
`add_custom_partition("zb_storage", "data", "fat", 0x4000)`

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-26 16:01 UTC, luar123 commented
In case of a custom partition table, I have this simple final validation in my zigbee component to check if the needed partition is there:
```
def final_validate(config):
    esp_conf = fv.full_config.get()["esp32"]
    if CONF_PARTITIONS in esp_conf:
        with open(
            CORE.relative_config_path(esp_conf[CONF_PARTITIONS]), encoding="utf8"
        ) as f:
            partitions = f.read()
            if ("zb_storage" not in partitions):
                raise cv.Invalid(
                    "Add \n'zb_storage, data, fat,   , 16K,'\n to your custom partition table."
                )
    return config
```
Should I move this to the esp32 component, to check if all partitions added with `add_custom_partition()` are included in the custom partition table?

2025-01-07 13:34 UTC, DFINITYManu approved these changes

2025-08-03 12:09 UTC, Hedda commented
Any updates on this?

2026-01-05 11:18 UTC, tomaszduda23 commented on esphome/components/esp32/__init__.py
> +            print(partitions_tab)
debug print

2026-01-05 11:54 UTC, luar123 commented on esphome/components/esp32/__init__.py
> +            print(partitions_tab)
Thanks

2026-01-05 12:25 UTC, tomaszduda23 commented on esphome/components/esp32/__init__.py
> +custom_partitions = {}
Shouldn't it be part of CORE.data?

2026-02-11 23:12 UTC, swoboda1337 requested changes

2026-02-11 23:12 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
>              cv.Optional(CONF_PARTITIONS): cv.file_,
Why not just reuse cv.Optional(CONF_PARTITIONS) allow a file or a definition?

2026-02-11 23:15 UTC, swoboda1337 commented
Here is Claude's review, somethings may be wrong or not relevant but most look legitimate:
```
  Bugs

  1. No app partition size overflow check

  app_partition_size = APP_PARTITION_SIZES[flash_size] - _get_custom_partition_half_size()

  If custom partitions are too large, this goes negative (wraps to a huge value), producing a nonsensical partition table. Needs a
  check like:

  if app_partition_size < MINIMUM_APP_SIZE:
      raise cv.Invalid("Custom partitions too large for flash size")

  2. _get_custom_partition_half_size() halving logic is questionable

  The function sums all custom partition sizes, then divides by 2 and aligns to 64KB — assuming the space is stolen equally from
  app0 and app1. This works for the Arduino layout (where both app partitions shrink symmetrically), but is conceptually wrong:
  you're adding N bytes of custom partitions, so you need to steal N bytes total, not N/2 from each. The math happens to work out
  (N/2 from each = N total), but only because there are exactly 2 app partitions. It's confusing.

  3. Dead final_validate code path

  if CONF_PARTITIONS in config and KEY_CUSTOM_PARTITIONS in CORE.data:

  The has_at_most_one_key(CONF_PARTITIONS, CONF_CUSTOM_PARTITIONS) check at schema level means CONF_PARTITIONS (file) and
  CONF_CUSTOM_PARTITIONS (inline) can never coexist. So KEY_CUSTOM_PARTITIONS in CORE.data is only populated when
  CONF_CUSTOM_PARTITIONS is used, which means CONF_PARTITIONS is absent. This validation block is unreachable dead code.

  4. Duplicate partition names silently overwrite

  CORE.data[KEY_CUSTOM_PARTITIONS] is a dict keyed by name. Two partitions with the same name would silently merge, with the second
  overwriting the first. Should error on duplicates.

  Validation Gaps

  5. String subtype not validated

  When subtype is a string, any value is accepted via cv.string_strict. Invalid subtypes (e.g., subtype: "banana") would pass YAML
  validation but fail at flash time with a confusing ESP-IDF error. Should validate against known subtypes: ota, phy, nvs, nvs_keys,
   fat, spiffs, coredump, etc. (depending on the type).

  6. Reserved name list is incomplete

  if name in ["nvs", "app0", "app1", "otadata", "eeprom", "spiffs", "phy_init"]:

  Missing at least: coredump, nvs_keys, efuse, factory. The IDF partition table has more standard names that could conflict.

  7. No validation that type: app partitions have valid subtypes

  App partitions must have subtypes like ota_0, ota_1, factory, test. A type: app, subtype: spiffs would be invalid but would pass
  validation.

  Code Quality

  8. Floating-point alignment math

  custom_partition_start = ceil(custom_partition_start / 0x10000) * 0x10000

  Uses float division then ceil(). For large addresses this could lose precision. Use integer math instead:

  custom_partition_start = (custom_partition_start + 0xFFFF) & ~0xFFFF  # 64KB align
  custom_partition_start = (custom_partition_start + 0xFFF) & ~0xFFF    # 4KB align

  9. Side effects during validation

  validate_custom_partition() writes to CORE.data as a schema validator (inside cv.All). Validation should ideally be pure; side
  effects belong in to_code() or a final validation step. If validation is re-run (e.g., during config reload), the data
  accumulates.

  10. IDF partition CSV doesn't handle alignment for custom partitions

  The Arduino CSV generator correctly aligns custom partition offsets (64KB for app, 4KB for data). The IDF generator omits offsets
  entirely (relying on IDF auto-placement), which works for standard partitions but custom partitions with specific alignment
  requirements may not get placed correctly.

  Testing

  11. No Arduino test case

  Only test.esp32-s3-idf.yaml is updated. The Arduino partition CSV generation is more complex (explicit offsets), so it needs its
  own test to verify the offset math is correct.

  Summary

  The feature is needed (zigbee, custom data storage), but the implementation should:
  1. Adopt swoboda1337's suggestion: extend CONF_PARTITIONS instead of adding a new key
  2. Add overflow validation on app partition size
  3. Fix or remove the dead final_validate code
  4. Validate subtypes against known values per type
  5. Use integer alignment instead of float math
  6. Add an Arduino test case
  ```

2026-02-13 07:49 UTC, luar123 commented
Thanks for the feedback.
Have merged with CONF_PARTITIONS and refactored the validator. Includes fixes to Claudes comments 1, 3, 4, 5, 7, 8, 9. Rest seems irrelevant and there are no Arduino tests for esp32 at all, should I add one?

2026-02-21 14:29 UTC, luar123 commented
@swoboda1337 is there more I should look into?

2026-02-21 14:31 UTC, swoboda1337 commented
Sorry it was a busy week with the release. Will get to this and other PRs next week.

2026-02-22 20:58 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +            "littlefs",
Missing "ota" and "phy" from the valid data subtypes

2026-02-22 20:58 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +                                cv.Required(CONF_SIZE): cv.int_,
cv.int_ allows 0 and negative values, should validate size > 0

2026-02-22 20:58 UTC, swoboda1337 commented on tests/components/esp32/test.esp32-s3-idf.yaml
> +  partitions:
Should also add an Arduino test for custom partitions

2026-02-22 21:11 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +def add_partition(name: str, p_type: str, subtype: str, size: int) -> None:
Type hints say str but isinstance checks below also accept int. For the YAML path the isinstance checks are dead code since _validate_custom_partition already converts ints

2026-02-22 21:11 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +            size = (size + 0xFFFF) & ~0xFFFF  # align to 64KB
Alignment logic is duplicated between here and get_arduino_partition_csv, could get out of sync

2026-02-22 21:11 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +        raise ValueError(f"Partition name {name} is reserved.")
ValueError will give the user a traceback instead of a clean error message

2026-02-22 21:11 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +    return (int(size / 2) + 0xFFFF) & ~0xFFFF  # align to 64KB
nit: should be size // 2

2026-02-22 21:11 UTC, swoboda1337 commented on tests/components/esp32/test.esp32-s3-idf.yaml
> +  partitions:
Should also add an Arduino test

2026-02-24 20:04 UTC, swoboda1337 submitted a review, later dismissed

2026-02-24 20:04 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +                                cv.Required(CONF_SIZE): cv.int_,
`cv.int_` accepts 0 and negative values. Should validate minimum size (4KB) and alignment since ESP-IDF requires partition sizes to be 4KB aligned. Something like `cv.All(cv.int_range(min=0x1000), lambda v: v if v % 0x1000 == 0 else (_ for _ in ()).throw(cv.Invalid("size must be 4KB aligned")))`

Or add a simple helper to check alignment

2026-02-24 20:04 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +    return (int(size / 2) + 0xFFFF) & ~0xFFFF  # align to 64KB
```suggestion
    return (size // 2 + 0xFFFF) & ~0xFFFF  # align to 64KB
```
`int(size / 2)` uses float division. `size // 2` is cleaner

2026-02-24 20:04 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +
`add_partition()` is the public API for other components (e.g. zigbee calling it from their `to_code`) but it doesnt validate type/subtype at all. A component could pass invalid strings and silently produce a broken CSV. Should share the validation logic with `_validate_custom_partition` or at least validate the basics here

2026-02-24 20:04 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> -
nit: unrelated whitespace change, should revert

2026-02-25 19:36 UTC, luar123 commented on esphome/components/esp32/__init__.py
> +                                cv.Required(CONF_SIZE): cv.int_,
Non app partitions could have arbitrary size, right? But as we need to align to 4KB anyway this would be a waste of space, so I think that makes sense.

2026-02-25 20:08 UTC, luar123 commented
Good points, thanks.

2026-03-09 18:19 UTC, luar123 commented
@swoboda1337 Any chance we could proceed with this?

2026-03-13 15:34 UTC, swoboda1337 commented
> @swoboda1337 Any chance we could proceed with this?

Sorry for the delay, this one was not trivial. The pre-existing partition stuff was a mess which made adding custom partitions messy. 

I pushed some changes, please take a look. I unified the arduino and idf partition code and fixed a few preexisting issues.

2026-03-13 15:58 UTC, swoboda1337 commented
Ok think it is good now. Please take a look.

2026-03-13 19:32 UTC, bdraco commented on esphome/components/esp32/__init__.py
> +    if name in CORE.data.get(KEY_CUSTOM_PARTITIONS, {}):
we have been moving keys to the component namespace ie `CORE.data[KEY_ESP32][KEY_CUSTOM_PARTITIONS]` to better organize things

2026-03-13 19:34 UTC, bdraco commented on esphome/components/esp32/__init__.py
> +PARTITION_OVERHEAD = 0x80000  # 512 KB
This seems a bit fragile. I wonder how we could make it safer

2026-03-13 19:34 UTC, bdraco commented on esphome/components/esp32/__init__.py
> +    return int(flash_size.rstrip("MB")) * 1024 * 1024
Need to make it clear this is always flash size in MB

2026-03-13 19:35 UTC, bdraco commented on esphome/components/esp32/__init__.py
> +    flash_bytes = _flash_size_to_bytes(flash_size)
Need to make it clear this is always flash size in MB

2026-03-13 20:10 UTC, bdraco commented
looks good

```
[10:09:43.967][C][debug:114]: Partition table:
[10:09:43.968][C][debug:114]:   Name         Type Subtype  Address    Size      
[10:09:43.970][C][debug:121]:   otadata      1    0        0x00009000 0x00002000
[10:09:43.972][C][debug:121]:   phy_init     1    1        0x0000B000 0x00001000
[10:09:43.973][C][debug:121]:   app0         0    16       0x00010000 0x001A0000
[10:09:43.975][C][debug:121]:   app1         0    17       0x001B0000 0x001A0000
[10:09:43.977][C][debug:121]:   nvs          1    2        0x00350000 0x00070000
[10:09:43.978][C][debug:121]:   my_data      1    130      0x003C0000 0x00010000
[10:09:43.980][C][debug:121]:   my_storage   1    129      0x003D0000 0x00020000
```

2026-03-13 20:10 UTC, bdraco submitted a review, later dismissed

2026-03-13 20:12 UTC, swoboda1337 submitted a review, later dismissed

2026-03-13 20:12 UTC, swoboda1337 commented
Thanks!

2026-03-13 21:09 UTC, luar123 reviewed
Awesome, thank you!

I wanted to keep it simple, but the refactor makes a lot of sense.

2026-03-13 21:09 UTC, luar123 commented on esphome/components/esp32/__init__.py
> +    overhead = (OTADATA_SIZE + PHY_INIT_SIZE + 0xFFFF) & ~0xFFFF
OTADATA starts at 0x9000 offset
```suggestion
    # otadata + phy_init are followed by app0 which requires 64KB alignment,
    # so pad up to the next 64KB boundary.
    overhead = (0x9000 + OTADATA_SIZE + PHY_INIT_SIZE + 0xFFFF) & ~0xFFFF
```

2026-03-13 21:09 UTC, luar123 commented on esphome/components/esp32/__init__.py
> +        )
I don't know the internals, but are these two even needed? Afaik both arduino libs, eeprom and spiffs, are removed by default. And if components need to add the library they could also add these partitions.

2026-03-13 21:40 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +        )
Not a huge deal to include them only shrinks nvs a bit. If people want to enable later they would have to reflash.

2026-03-13 21:41 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +    overhead = (OTADATA_SIZE + PHY_INIT_SIZE + 0xFFFF) & ~0xFFFF
It was never placed at a fixed address on IDF:
```
otadata,  data, ota,     ,        0x2000,
phy_init, data, phy,     ,        0x1000,
app0,     app,  ota_0,   ,        0x{app_partition_size:X},
app1,     app,  ota_1,   ,        0x{app_partition_size:X},
nvs,      data, nvs,     ,        0x6D000,
```

2026-03-13 21:41 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +    overhead = (OTADATA_SIZE + PHY_INIT_SIZE + 0xFFFF) & ~0xFFFF
I assume the tool will take care of it

2026-03-13 21:47 UTC, luar123 commented on esphome/components/esp32/__init__.py
> +    overhead = (OTADATA_SIZE + PHY_INIT_SIZE + 0xFFFF) & ~0xFFFF
> I assume the tool will take care of it

Yes it does. But for the size calculation to be robust it should be considered. At the moment it won't make a difference because it is <64KB anyway.

First partition starts always at 0x9000. 0x8000 for bootloader + 0x1000 for partition table.

2026-03-13 22:17 UTC, swoboda1337 commented on esphome/components/esp32/__init__.py
> +    overhead = (OTADATA_SIZE + PHY_INIT_SIZE + 0xFFFF) & ~0xFFFF
Ok yeah could probably add defines for those.

2026-03-13 23:10 UTC, swoboda1337 approved these changes

2026-03-13 23:12 UTC, bdraco approved these changes

2026-03-14 07:58 UTC, luar123 commented
Thanks!

2026-03-19 11:41 UTC, merged

2026-03-19 11:41 UTC, swoboda1337 commented
Thanks!