added Waveshare BWR Mode for the 7.5in Display
OttoWinter/esphomeyaml pull request #7687
Opened 2024-10-28 09:56 UTC by JonasB2497

# What does this implement/fix?

- duplicated class WaveshareEPaper7P5InBV3 and changed baseclass to get the bigger buffer needed for BWR mode
    - duplicated instead of extended as the BWR mode results in a considerable longer refresh time (~26s vs ~3s) which might not be wanted by most users
- changed to LUT from OTP and KWR Mode
- removed custom LUTs as they did not work in KWR mode and the official driver does not seem use them
    - I might add new custom LUTs in a future pull request if the currently used ones are too distracting for my dashboard project
- updated the register values in the `display()` function and added the register for red values
- as noted below no new tests have been added as they are missing for most of the other displays as well

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
spi:
  clk_pin: 14
  mosi_pin: 13

font:
  - file: 'fonts/Literata-Black.ttf'
    id: font_title
    size: 200

color:
  - id: my_red
    red: 100%
    green: 0%
    blue: 0%
    white: 0%

display:
  - platform: waveshare_epaper
    id: eink
    cs_pin: 2
    dc_pin: 4
    busy_pin:
      number: 0
      inverted: true
    reset_pin: 16
    model: 7.50in-bv3-bwr
    update_interval: 3600s
    lambda: |-
      it.print(it.get_width()/2, 0, id(font_title), COLOR_ON, TextAlign::TOP_CENTER, "Hello");
      it.print(it.get_width()/2, it.get_height()/2, id(font_title), id(my_red), TextAlign::TOP_CENTER, "World");

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-03 22:52 UTC, jesserockz requested changes
New class looks fine. Please add the model to `/tests/components/waveshare_epaper`

2024-11-04 16:25 UTC, JonasB2497 commented
Thank you for reviewing. I have added the requested changes

2024-11-06 02:25 UTC, jesserockz approved these changes

2024-11-25 22:29 UTC, merged

2024-11-27 20:21 UTC, trip5 commented
Oh!  Fantastic.  Just came here to say I tested it out and it works great!  Thanks @JonasB2497 and @jesserockz !