[http_request] Always return defined server response status
OttoWinter/esphomeyaml pull request #7689
Opened 2024-10-28 19:48 UTC by clydebarrow

# What does this implement/fix?

When a server responds with a status code outside [200-299] the http_request code returns a null pointer, denying the calling code the opportunity to examine the response. Instead, return the container with the status code.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/issues/issues/6010

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
- http_request.get:
          capture_response: true
          headers:
            content-Type: application/json
          url: !lambda |-
            return ((std::string) "${music_control_api}/lookup?key=" + x);
          on_response:
            - if:
                condition:
                  lambda: "return response->status_code == 200;"
                then:
                  - lambda: |-
                      id(tag_found_in_db).publish_state(true);
                      json::parse_json(body, [](JsonObject root) -> bool {
                      id(artist).publish_state(root["artist"]);
                      id(album).publish_state(root["album"]);
                      return true;
                      });
                  - output.turn_on: play_button_led
                else:
                    - output.turn_on: play_button_led
                    - delay: 0.5s
                    - output.turn_off: play_button_led
                    - delay: 0.5s
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-28 22:11 UTC, jesserockz requested changes
This will require all existing code calling start/get/post etc that does
```c++
if (container == nullptr) {
```
to handle a bad status code in the same way as they do the nullptr.

2024-10-28 23:41 UTC, clydebarrow commented
> to handle a bad status code in the same way as they do the nullptr.

Correct, and in that sense it's a breaking change, but the code should *already* be checking the status code since it can already be in the range 200-299, and typically only 200 means there is valid data. This basically restores the functionality to what it was before release 2024.6.

I looked for usages that were not checking the status code and found a couple, have updated them.

2024-10-28 23:44 UTC, clydebarrow commented
It's important for user code to have the response and body returned even when the server returns a status other than 200, since even a 404 response will usually have some kind of error message in the body, as will other codes like 401 (unauthorised) and 500 (server error.)

2024-10-29 00:01 UTC, jesserockz approved these changes

2024-10-29 00:12 UTC, merged