Disable bluetooth proxy during update
OttoWinter/esphomeyaml pull request #7695
Opened 2024-10-29 20:45 UTC by jzucker2

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-29 23:31 UTC, jzucker2 commented
I guess theoretically there should be a docs change too but I wanted to spec this out as a working prototype first, and get some feedback as well

2024-10-30 01:07 UTC, jesserockz requested changes
We already have a mechanism that stops ble scanning (and therefore bluetooth proxy relaying) as soon as OTA is started. This would not stop the active connections though which could do with some work to "fix". 

https://github.com/esphome/esphome/blob/38dd566e0cbb51b4eb6f14a8fcb03b36b7b962dc/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp#L63-L70

2024-10-30 01:34 UTC, jzucker2 commented
> We already have a mechanism that stops ble scanning (and therefore bluetooth proxy relaying) as soon as OTA is started. This would not stop the active connections though which could do with some work to "fix".
> 
> https://github.com/esphome/esphome/blob/38dd566e0cbb51b4eb6f14a8fcb03b36b7b962dc/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp#L63-L70

Thank you!

My bluetooth proxies are really struggling with the http request update and I assumed this was the root cause. That makes sense. I can look into that.

2024-10-30 18:21 UTC, jzucker2 commented
> We already have a mechanism that stops ble scanning (and therefore bluetooth proxy relaying) as soon as OTA is started. This would not stop the active connections though which could do with some work to "fix".
> 
> https://github.com/esphome/esphome/blob/38dd566e0cbb51b4eb6f14a8fcb03b36b7b962dc/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp#L63-L70

I might be a little confused. Are you suggesting I try to stop connections in that class, or is that an example for doing so in the bluetooth proxy class?

I kinda tried both here but I think only the bluetooth proxy changes may be necessary? And I'm not sure quite how to cancel connections in that class.

2024-10-30 22:45 UTC, jesserockz commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +          }
This is probably all that is needed for this entire PR tbh. All of the bluetooth proxy clients are in the `clients_` list.
```suggestion
          for (auto *client : this->clients_) {
            client->disconnect();
          }
```

2024-10-30 23:22 UTC, jzucker2 commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +          }
So that was my original plan, but there is no public `disconnect` method it seems, which explains why I had trouble finding it ...

From the CI tests:

```
### File esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp

Error: /home/runner/work/esphome/esphome/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp:69:21: error: no member named 'disconnect' in 'esphome::esp32_ble_tracker::ESPBTClient'; did you mean 'connect'? [clang-diagnostic-error]
            client->disconnect();
                    ^~~~~~~~~~
                    connect
/home/runner/work/esphome/esphome/esphome/components/esp32_ble_tracker/esp32_ble_tracker.h:[17](https://github.com/esphome/esphome/actions/runs/11603000836/job/32309288708?pr=7695#step:9:18)4:16: note: 'connect' declared here
  virtual void connect() = 0;
```

2024-10-31 01:46 UTC, jesserockz commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +          }
OH, its on an intermediate class.

Maybe we can fix that with #7705. Try merging that branch into this one

2024-10-31 07:46 UTC, jzucker2 commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +          }
Compiles! I'm hoping to test it tomorrow

2024-11-05 18:15 UTC, jesserockz commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +          }
How did this work out for you? Does it help / solve the problem?

2024-11-13 18:44 UTC, jzucker2 commented on esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp
> +          }
Sorry for the delay! I've been using this at home for a bit now with great success. I combined it with my attempts at adding bluetooth proxy sensors and I have pretty good stability with my bluetooth proxies during OTA, with insight

2024-11-14 00:56 UTC, jesserockz approved these changes

2024-11-14 00:57 UTC, merged