support for KP18058 / KP18068 LED dimming drivers.
OttoWinter/esphomeyaml pull request #7701
Opened 2024-10-30 19:51 UTC by NewoPL

# What does this implement/fix?
support for KP1858/KP18068 I2C LED driver 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/feature-requests/issues/2781

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [X] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
kp18058:
   data_pin: P8   
   clock_pin: P7
   cw_current: 5
   rgb_current: 5
   
output:
  - platform: kp18058
    id: output_green
    channel: 1
  - platform: kp18058
    id: output_blue
    channel: 2
  - platform: kp18058
    id: output_red
    channel: 3
  - platform: kp18058
    id: output_warm
    channel: 4
  - platform: kp18058
    id: output_cold
    channel: 5

light:
  - platform: rgbww
    id: light_rgbww
    name: Light
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-10-30 23:08 UTC, jesserockz requested changes

2024-10-30 23:08 UTC, jesserockz commented on esphome/components/kp18058/softi2c.h
This is not something that should be inside this component

2024-10-31 06:39 UTC, NewoPL commented on esphome/components/kp18058/softi2c.h
It is based on a similar component for the BP5758D chip, where I2C is also handled internally by software. I could create it as a separate component, but that would complicate the configuration and make the two components inconsistent. Let me know if this aligns with what you had in mind.

2024-10-31 07:07 UTC, NewoPL commented on esphome/components/kp18058/softi2c.h
I am looking at other LED drivers (SMxxxx). They all implement their own Soft I2C handling and follow suit.

2024-12-30 10:38 UTC, NewoPL commented
Hello @jesserockz. Would you be able to pull it in ?

2025-02-09 23:24 UTC, chrisallen commented
Any update on getting this merged?

2025-03-24 05:55 UTC, nroach44 commented
Is any help needed to get this over the line?

2025-03-24 11:56 UTC, NewoPL commented
@jesserockz would you be willing to merge this change?
If you are I can rebranch it to the current version,

2025-05-10 08:21 UTC, gaz99gh commented
Is there a way to use this as it is now before it gets included in ESPHome ??

I just picked up a new version of an Aldi light that is using this driver chip.

2025-05-14 02:56 UTC, Roving-Ronin commented
> Is there a way to use this as it is now before it gets included in ESPHome ??
> 
> I just picked up a new version of an Aldi light that is using this driver chip.

See: https://esphome.io/components/external_components.html
Try:
```external_components:
  - source: github://pr#2639
    components: [ kp18058 ]
```

2025-05-15 15:10 UTC, Roving-Ronin commented
Hi @NewoPL ,

Just wondering where this got up to, as I see there's a few people seeking a component to get their KP18058 / KP18068 lights working. See:  https://community.home-assistant.io/t/aldi-casa-life-9w-downlight-config-help-needed/618527/35

Thanks ! RR

2025-05-19 13:57 UTC, NewoPL commented
The PR is ready, you can use it to build it locally and use it.
I have it working and flashed on my smart bulb.

The merge depends on the repo owner decision,
I didnt' have any response on this since it was finally submitted


On Thu, May 15, 2025 at 5:10 PM Roving Ronin ***@***.***>
wrote:

> *Roving-Ronin* left a comment (esphome/esphome#7701)
> <https://github.com/esphome/esphome/pull/7701#issuecomment-2884185986>
>
> Hi @NewoPL <https://github.com/NewoPL> ,
>
> Just wondering where this got up to, as I see there's a few people seeking
> a component to get their KP18058 / KP18068 lights working. See:
> https://community.home-assistant.io/t/aldi-casa-life-9w-downlight-config-help-needed/618527/35
>
> Thanks ! RR
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/esphome/esphome/pull/7701#issuecomment-2884185986>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGRELIXRXDAPA35HFFB7KPD26SU63AVCNFSM6AAAAABQ44CEFGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDQOBUGE4DKOJYGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-05-19 23:58 UTC, gaz99gh commented
I got it working with a bit of trial and error:

```
external_components:
  - source: github://pr#7701
    components: [ kp18058 ]
  - source: github://pr#7701
    components: [ i2c_soft ]
```

I do get an error in the ESPHome but it still complies OK:

```
Channel 1 is already used for kp18058 component with id . Each output must have a unique channel.
```

2025-07-28 05:36 UTC, markwalkom commented
@jesserockz as the original reviewer on this, is possible to get this merged at all please given all the requested changes were made?

2025-11-04 00:49 UTC, closed without merging