Update display.cpp
OttoWinter/esphomeyaml pull request #7714
Opened 2024-11-02 21:45 UTC by mikosoft83

Add strftime variant with background color (useful for antialiased fonts with non black background)

# What does this implement/fix?

Adds strftime variant with background color (useful for antialiased fonts with non black background) 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-03 21:14 UTC, jesserockz commented
Please write a meaningful PR title

2024-11-03 21:17 UTC, jesserockz requested changes

2024-11-03 21:17 UTC, jesserockz commented on esphome/components/display/display.h
> +   * @param background The background color to draw the text with.
This is on the wrong function

2024-11-03 21:57 UTC, mikosoft83 reviewed
Added the align param

2024-11-20 20:28 UTC, mikosoft83 commented
Is this still missing something?

2024-11-21 00:12 UTC, jesserockz requested changes

2024-11-21 00:12 UTC, jesserockz commented on esphome/components/display/display.h
> +   * @param background The background color to draw the text with.
This is still on the wrong function. You put the new params as the doc for the function that doesnt have them

2024-11-21 07:14 UTC, mikosoft83 commented on esphome/components/display/display.h
> +   * @param background The background color to draw the text with.
I had a brain rot. Hopefully it's all fixed now.

2024-12-01 22:57 UTC, mikosoft83 commented
I'm just bumping this

2024-12-02 22:35 UTC, jesserockz commented
> I'm just bumping this

Unfortunately, you never fixed the comment on the function correctly, I was waiting for you to actually fix it. I have now fixed it myself

2024-12-03 07:18 UTC, mikosoft83 commented
Ah, I now see what the issue was. I apologize, I very rarely post any PRs as I'm not familiar with GitHub, but I wanted to help since posting issues usually takes forever to resolve.
Thank you for your patience.

2024-12-04 00:17 UTC, jesserockz approved these changes

2024-12-04 00:18 UTC, merged