Remove the choice for MQTT logging if it is disabled
OttoWinter/esphomeyaml pull request #7723
Opened 2024-11-05 17:39 UTC by solarkennedy

This is a second pass at https://github.com/esphome/issues/issues/6046

I have a situation where sometimes I have MQTT logging enabled, but sometimes not depending on the device.

This PR removes the choice so that one doesn't have to remember that MQTT logging is disabled, so that `esphome logs` goes right for the API method (if available).

# What does this implement/fix?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):** 

- fixes https://github.com/esphome/issues/issues/6046

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#4412

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-05 21:10 UTC, jesserockz requested changes

2024-11-05 21:10 UTC, jesserockz commented on esphome/__main__.py
> +        options.append((f"MQTT ({CORE.config[CONF_MQTT][CONF_BROKER]})", "MQTT"))
```suggestion
    if (
        show_mqtt
        and (mqtt_config := CORE.config.get(CONF_MQTT))
        and mqtt_logging_enabled(mqtt_config)
    ):
        options.append((f"MQTT ({mqtt_config[CONF_BROKER]})", "MQTT"))
```

2024-11-05 21:10 UTC, jesserockz commented on esphome/__main__.py
> +    return True
Always pull out a variable if it is going to be used multiple times
```suggestion
def mqtt_logging_enabled(mqtt_config):
	log_topic = mqtt_config[CONF_LOG_TOPIC]
    if log_topic is None:
        return False
    if CONF_TOPIC not in log_topic:
        return False
    if log_topic.get(CONF_LEVEL, None) == "NONE":
        return False
    return True
```

2024-11-10 00:42 UTC, solarkennedy commented
Added in requested changes

2024-11-11 01:13 UTC, jesserockz approved these changes

2024-11-11 01:13 UTC, merged