Store yaml in firmware
OttoWinter/esphomeyaml pull request #7725
Opened 2024-11-06 19:08 UTC by gabest11

# What does this implement/fix?

This component can be used to store the flattened yaml in the firmware, to be retrieved in case the original was lost.

I was thinking about adding this into proto.api / DeviceInfoResponse, but that would have been a bit rude, maybe. And this way it works with MQTT too.

The needed size in the firmware is typically a few kilobytes. The used can decide if it's worth it.

About documentation. I can create a new page for the component, but someone should also modify that section about yaml recoveribility in the FAQ.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes [Can Configuration Files Be Recovered From The Device?](https://esphome.io/guides/faq.html#can-configuration-files-be-recovered-from-the-device)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [x] RP2040
- [x] BK72xx
- [x] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
store_yaml:
  show_in_dump_config: True
  show_secrets: True

api:
  services:
    - service: 'store_yaml_log'
      then:
        - store_yaml.log
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-08 00:10 UTC, TrentHouliston commented
If the purpose is to store it for later retrieval, compressing it would save a lot of space

2024-11-08 05:32 UTC, gabest11 commented
I was thinking about it, but every real compression library would take up more code space than the yaml itself.

2024-11-08 14:12 UTC, DjordjeMandic commented
Any way to store it in flash without pushing it into ram? I may be wrong but this code looks like whole string is in ram all the time. 

It could be served via new API call / mqtt topic?

For use, alloc memory required to store it, read it from flash to ram, dump it and free the memory, get rid of pointer.

2024-11-08 14:20 UTC, gabest11 commented
> Any way to store it in flash without pushing it into ram? I may be wrong but this code looks like whole string is in ram all the time.

Going to check it with debug component. With and without.

> It could be served via new API call / mqtt topic?

As far I know, calls don't return anything. And HA can only take long strings in attributes, which esphome does not support. A web server or the proto.api could be used, but I would not go that far myself.

> For use, alloc memory required to store it, read it from flash to ram, dump it and free the memory, get rid of pointer.

Not sure how. There is no spiffs partition with esphome.

2024-11-08 14:44 UTC, gabest11 commented
I can see a 7k difference in Heap Free with a large yaml. It's definitely in memory.

2024-11-08 14:58 UTC, gabest11 commented
If I replace std::string with const char*, just to point to the string from main.cpp, which will never be deallocated, I can save that 7k.

2024-11-08 16:00 UTC, gabest11 commented
Tried putting the string into a global const char[], same results.

2024-11-08 17:41 UTC, DjordjeMandic commented
> > For use, alloc memory required to store it, read it from flash to ram, dump it and free the memory, get rid of pointer.
> 
> Not sure how. There is no spiffs partition with esphome.

Take a look at webserver component, it stores web pages in flash as array. If codegen can be modified, py script could generate header file containing compressed yaml as array of bytes from program memory (flash).

2024-11-08 17:44 UTC, gabest11 commented
I tried that. That's what I ment by storing it in a global variable. I think the string literal compiles to the same thing. Somewhere I read that PROGMEM makes no difference on ESP32.

2024-11-08 17:48 UTC, gabest11 commented
And the web server does not have to decompress it, there is no code to do it, it exploits http compression. Browsers can accept gzipped pages.

2024-11-08 17:54 UTC, gabest11 commented
Free heap as I was trying different approaches. Lower is string, more free mem with a simple pointer to the argument or the global.

![Screenshot 2024-11-08 185217](https://github.com/user-attachments/assets/b70f3d95-4697-4bb6-9876-1eab1113df1e)

2024-11-08 22:37 UTC, TrentHouliston commented
Typically if I was trying to ensure that a symbol occupied a specific location in memory on another embedded platform I'd be playing with the linker script and potentially`__attribute__((section("name")))` to put it in a specific location.

As for compression, I'm not sure that the device itself has any use for reading the yaml either, so compressing it and then storing the compressed `.yaml.gz` etc and just serving that would save space without requiring a compression/decompression library on the device itself.

2024-11-09 03:00 UTC, gabest11 commented
I ran into a small problem.  !extend does not resolve with load_yaml+dump. I could fall back to CORE.config, but that has everything, all the default configurations, and auto-generated ids.

2024-11-09 23:52 UTC, gabest11 commented
Compression saves 50%-70%, but the data is also bigger now. My largest file is 8k, it cannot even list it in the debug output fast enough, the watchdog resets it. Maybe I could feed it in smaller chunks from loop(). Any ideas?

2024-11-10 11:17 UTC, DjordjeMandic commented
Where does wdt timeout happen? dump_config should be fast.

I know that audio and camera components create new task with xtaskcreate to prevent wdt timeouts. I might be wrong tho.

Could you time how much time does decompression take?

2024-11-10 14:27 UTC, nielsnl68 commented
Maybe a late question, but why did you want to have the compression/decompression inside the firmware. From your earlier messages i got the idea that you only wanted to store the yaml content. Why not compressing in `__init__.py` and just store the result. And when needed send the decompress it in the dashboard.

2024-11-10 15:04 UTC, gabest11 commented
> Where does wdt timeout happen? dump_config should be fast.

There is one long yaml I have with 100+ entities, it reboots after a few seconds stuck in dump_config. The code runs fast, but the receiveing end is slow. In the browser it is very slow, command line (esphome log ...) moderately, and serial is almost fast enough. I moved the action response into loop() and every time it only print a single line, now it survives nicely. The single run dump_config is out of the question for large yamls.
 
> I know that audio and camera components create new task with xtaskcreate to prevent wdt timeouts. I might be wrong tho.

That loop() solution works now, I'm satisfied with it.

> Could you time how much time does decompression take?

Instantly, it's very basic. Logging is slow as I said. Since I don't decompress everything at once, only a line, send it, next line.

> Also, i think it might be good time to mark this pr as draft because its work in progress.

If we don't count the dump_config problem, it's usable as it is right now. Maybe I'm going to trim that output to a shorter version. First 100 lines or so.

2024-11-10 15:05 UTC, gabest11 commented
> Maybe a late question, but why did you want to have the compression/decompression inside the firmware. From your earlier messages i got the idea that you only wanted to store the yaml content. Why not compressing in `__init__.py` and just store the result. And when needed send the decompress it in the dashboard.

That's exactly what's happening.

2024-11-10 16:46 UTC, DjordjeMandic commented
I agree with suggestion from above. 

1) this now is fine, compress it during verification process, store it in flash. Loop() print works currently 

2) update api to support sending raw compressed data from flash back to dashboard only if authenticated

3) decompress in dashboard if needed

2024-11-11 15:50 UTC, nagyrobi commented
also see https://github.com/dentra/esphome-components/tree/master/components/backup @dentra

2024-11-11 16:50 UTC, gabest11 commented
> also see https://github.com/dentra/esphome-components/tree/master/components/backup @dentra

Looks very similar to this one, just with a web server.

2024-11-11 18:07 UTC, nagyrobi commented
Yeah just no need to reinvent the wheel, maybe good for inspiration.

2024-11-11 18:13 UTC, gabest11 commented
Components not in the main project don't exist for the user. And the FAQ just said it was not possible.

2024-11-12 20:48 UTC, DjordjeMandic requested changes
Make logs more useful even if `show_in_dump_config_` is false

2024-11-12 20:48 UTC, DjordjeMandic commented on esphome/components/store_yaml/store_yaml.cpp
> +}
Add more config info independent of `show_in_dump_config_`

```suggestion
void StoreYamlComponent::dump_config() {
  ESP_LOGCONFIG(TAG, "YAML:");
  ESP_LOGCONFIG(TAG, "  Compressed size: %zu", ESPHOME_YAML_SIZE);
  ESP_LOGCONFIG(TAG, "  Web server url: %s", (this->web_server_ != nullptr) ? this->web_server_url_ : "not configured!");
  if (this->show_in_dump_config_) {
    ESP_LOGCONFIG(TAG, "  Decompressed content:");
    RowDecompressor dec(ESPHOME_YAML, ESPHOME_YAML_SIZE);
    std::string row;
    while (dec.get_row(row)) {
      ESP_LOGCONFIG(TAG, "    %s", row.c_str());
    }
  }
}
```

2024-11-12 20:48 UTC, DjordjeMandic commented on esphome/components/store_yaml/store_yaml.cpp
> +  }
```suggestion
  if (this->web_server_ != nullptr) {
    this->web_server_->init();
    this->web_server_->add_handler(this);
    ESP_LOGD(TAG, "Web server configured to serve at: %s", this->web_server_url_.c_str());
  }
```

2024-11-12 20:48 UTC, DjordjeMandic commented on esphome/components/store_yaml/store_yaml.cpp
> +  ESP_LOGI(TAG, "YAML:");
```suggestion
  ESP_LOGI(TAG, "Decompressed YAML:");
```

2024-11-12 20:57 UTC, gabest11 commented
Does RP2040 really have no web server support? No captive portal, nothing.

2024-11-12 21:29 UTC, gabest11 commented
Why this script/ci-custom test cannot see CORE.target_platform. I have no problem compiling the firmware.

2024-11-13 10:11 UTC, gabest11 commented
Just noticed the web server request does nothing the second time. Neighter way, arduino or esp-idf.

2025-01-28 13:49 UTC, DjordjeMandic requested changes

2025-01-28 13:49 UTC, DjordjeMandic commented on esphome/components/store_yaml/decompressor.h
In c++ default access specifier is private. In esphome we dont use private. Make it protected.

2025-01-28 13:49 UTC, DjordjeMandic commented on esphome/components/store_yaml/decompressor.cpp
> +  for (uint32_t i = 0; i < 256; i++) {
```suggestion
  for (uint16_t i = 0; i < 256; i++) {
```

2025-01-28 13:49 UTC, DjordjeMandic commented on esphome/components/store_yaml/decompressor.cpp
> +      ESP_LOGE(TAG, "entry->p %d not found", entry->p);
```suggestion
      ESP_LOGE(TAG, "entry->p %" PRIu16 " not found", entry->p);
```
`entry->p` is `uint16_t` type right?

2025-01-28 13:49 UTC, DjordjeMandic commented on esphome/components/store_yaml/decompressor.cpp
> +    this->buff_ = (this->buff_ << 8) | progmem_read_byte(&this->data_ptr_[this->pos_++]);
AFAIK progmem functions are part of avr-libc. They're ported to arduino as compatibility layer for code. Were trying to switch to esp-idf completely.

https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/pgmspace.h

Does this code compile when ESP-IDF framework is used without arduino wrapper?

2025-01-28 13:49 UTC, DjordjeMandic commented on esphome/components/store_yaml/decompressor.h
> +  std::vector<Entry> codes_;
Is max size of `codes_` known or could be made known at compile time? If yes, reserve enough space during construction of Decompressor to prevent unnecessary memory reallocations. https://cplusplus.com/reference/vector/vector/reserve/

2025-01-28 13:49 UTC, DjordjeMandic commented on esphome/components/store_yaml/store_yaml.h
Same as for `decompressor.h`. No private allowed.

2025-01-28 13:50 UTC, DjordjeMandic commented
Could you test heap usage and heap fragmentation? Log them to home assistant, call log action multiple times. Im worried that it might fragment the heap too much.

2025-01-28 14:42 UTC, gabest11 commented
> Could you test heap usage and heap fragmentation? Log them to home assistant, call log action multiple times. Im worried that it might fragment the heap too much.

The only memory issue I noticed was on a fully loaded esp8266 with lower than 10k free memory. I had to disable this, because once day it stopped responding.

2025-01-28 14:45 UTC, gabest11 commented on esphome/components/store_yaml/decompressor.cpp
> +      ESP_LOGE(TAG, "entry->p %d not found", entry->p);
I don't really care about these, since smaller than int are promoted and passed as int.

2025-01-28 14:47 UTC, gabest11 commented on esphome/components/store_yaml/decompressor.cpp
> +    this->buff_ = (this->buff_ << 8) | progmem_read_byte(&this->data_ptr_[this->pos_++]);
progmem_read_byte just returns the pointer if the target board isn't esp8266.

2025-01-28 14:55 UTC, DjordjeMandic commented on esphome/components/store_yaml/decompressor.cpp
> +      ESP_LOGE(TAG, "entry->p %d not found", entry->p);
You're right, it will work for now. I just wanted to future-proof it. If entry->p is changed to uint32_t and the MSB gets set, it could print negative values. Similarly, on platforms where int is 2 bytes, the same issue would occur if the MSB of a uint16_t gets set. Since ESPHome is becoming more of a multi-platform project, I think it's good to account for these edge cases early.

2025-01-28 15:02 UTC, DjordjeMandic commented on esphome/components/store_yaml/decompressor.cpp
> +      ESP_LOGE(TAG, "entry->p %d not found", entry->p);
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/migration-guides/release-5.x/5.0/gcc.html#espressif-toolchain-changes

I dont know whats best practice here, this created unwanted headache in ESPHome as i understood it.

2025-01-28 15:03 UTC, DjordjeMandic commented on esphome/components/store_yaml/decompressor.cpp
> +    this->buff_ = (this->buff_ << 8) | progmem_read_byte(&this->data_ptr_[this->pos_++]);
You're correct, my bad. I didn't see this https://github.com/esphome/esphome/blob/f7f8bf4da44b83796a301bc486d77fdb46d8ed82/esphome/core/hal.h#L46

2025-01-28 15:05 UTC, gabest11 commented on esphome/components/store_yaml/decompressor.h
> +  std::vector<Entry> codes_;
That's a difficult one, I'll think about it. The beauty of LZW is that the dictionary is not transmitted, but dynamically built on both ends. The python compressor knows in the end, so it should be doable.

2025-01-28 16:26 UTC, DjordjeMandic approved these changes

2025-01-30 22:16 UTC, gabest11 commented on esphome/components/store_yaml/decompressor.cpp
> +      ESP_LOGE(TAG, "entry->p %d not found", entry->p);
This PRIu16 breaks compilation with the current Arduino framework. Will this be ever fixed?

2025-01-30 22:27 UTC, DjordjeMandic commented on esphome/components/store_yaml/decompressor.cpp
> +      ESP_LOGE(TAG, "entry->p %d not found", entry->p);
https://github.com/esphome/esphome/pull/8155

Does this fix it? Merge latest dev into gabest11/esphome#store_yaml

2025-01-30 22:34 UTC, gabest11 commented on esphome/components/store_yaml/decompressor.cpp
> +      ESP_LOGE(TAG, "entry->p %d not found", entry->p);
That helped!

2025-12-01 19:21 UTC, bdraco commented
@gabest11 are you still interested in working on this? If so, I'll do a full review, as I've had users asking for something like this.

2026-03-09 00:55 UTC, closed without merging