gp8403 : add gp8413 (15 bits) DAC model
OttoWinter/esphomeyaml pull request #7726
Opened 2024-11-06 19:09 UTC by SeByDocKy

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```
gp8403:
  - id: gp8403_id
    voltage: 10V
    i2c_id: i2c_bus
    address : 0x58
    gp8413: True

```

## Checklist:
  - [ x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2025-01-02 01:54 UTC, cyaneous commented
Would be nice to get this merged.

2025-02-02 20:22 UTC, number91982 commented
would be nice get this merged!

2025-02-03 13:38 UTC, DjordjeMandic requested changes

2025-02-03 13:38 UTC, DjordjeMandic commented on esphome/components/gp8403/gp8403.h
> +  bool gp8413_;
```suggestion
  bool gp8413_{false};
```
If `cv.Optional(CONF_GP8413, default=False): cv.boolean,` is optional, then that MUST be initialized in cpp code.

2025-02-03 13:38 UTC, DjordjeMandic commented on esphome/components/gp8403/__init__.py
> +CONF_GP8403 = "gp8403"
```suggestion
```

Is `CONF_GP8403` needed?

2025-02-03 13:38 UTC, DjordjeMandic commented on esphome/components/gp8403/gp8403.h
> +  void set_gp8413(bool gp8413) { gp8413_ = gp8413; }
```suggestion
  void set_gp8413(bool gp8413) { this->gp8413_ = gp8413; }
```

2025-02-03 13:38 UTC, DjordjeMandic commented on esphome/components/gp8403/output/gp8403_output.cpp
> +  ESP_LOGV(TAG, "Calculated DAC value: %u", value);
```suggestion
  ESP_LOGV(TAG, "Calculated DAC value: %" PRIu16, value);
```

2025-02-03 13:38 UTC, DjordjeMandic commented on esphome/components/gp8403/output/gp8403_output.cpp
>      ESP_LOGE(TAG, "Error writing to GP8403, code %d", err);
```suggestion
    ESP_LOGE(TAG, "Error writing to %s, code %d", (this->parent_->gp8413_) ? "GP8413" : "GP8403" ,err);
```

2025-02-03 13:38 UTC, DjordjeMandic commented on esphome/components/gp8403/gp8403.cpp
> +  ESP_LOGCONFIG(TAG, "  Is GP8413 ?: %s", YESNO(this->gp8413_));
```suggestion
  ESP_LOGCONFIG(TAG, "  Is GP8413: %s", YESNO(this->gp8413_));
```

2025-02-03 17:04 UTC, DjordjeMandic approved these changes

2025-02-03 17:05 UTC, DjordjeMandic commented
Looks good to me, just fix formatting

2025-02-03 18:28 UTC, SeByDocKy commented
Sorry I don't understand this error :(

``` ESP_LOGV(TAG, "Calculated DAC value: %" PRIu16, value);
   i2c::ErrorCode err = this->parent_->write_register(OUTPUT_REGISTER + (2 * this->channel_), (uint8_t *) &value, 2);
   if (err != i2c::ERROR_OK) {
-    ESP_LOGE(TAG, "Error writing to %s, code %d", (this->parent_->gp8413_) ? "GP8413" : "GP8403" ,err);
+    ESP_LOGE(TAG, "Error writing to %s, code %d", (this->parent_->gp8413_) ? "GP8413" : "GP8403", err);
   }````

Look the same... I using Github webtools to fix stuffs... not ideal I know

2025-02-03 18:30 UTC, DjordjeMandic commented on esphome/components/gp8403/output/gp8403_output.cpp
> +    ESP_LOGE(TAG, "Error writing to %s, code %d", (this->parent_->gp8413_) ? "GP8413" : "GP8403" ,err);
```suggestion
    ESP_LOGE(TAG, "Error writing to %s, code %d", (this->parent_->gp8413_) ? "GP8413" : "GP8403", err);
```

2025-02-03 19:35 UTC, cyaneous commented
> Sorry I don't understand this error :(
> 
> ```
>    i2c::ErrorCode err = this->parent_->write_register(OUTPUT_REGISTER + (2 * this->channel_), (uint8_t *) &value, 2);
>    if (err != i2c::ERROR_OK) {
> -    ESP_LOGE(TAG, "Error writing to %s, code %d", (this->parent_->gp8413_) ? "GP8413" : "GP8403" ,err);
> +    ESP_LOGE(TAG, "Error writing to %s, code %d", (this->parent_->gp8413_) ? "GP8413" : "GP8403", err);
>    }````
> 
> Look the same... I using Github webtools to fix stuffs... not ideal I know
> ```

Space before the comma, should be after.

2025-02-03 19:45 UTC, DjordjeMandic commented
Do this: https://esphome.io/guides/contributing.html#setting-up-a-development-environment

Then:
Please run `script/build_codeowners.py`

2025-02-03 19:45 UTC, DjordjeMandic requested changes
Build codeowners file

2025-02-03 19:47 UTC, SeByDocKy commented
> Build codeowners file

It's possible to that from github web tool ?

2025-02-03 19:49 UTC, cyaneous commented
Yes, look at the CODEOWNERS file and add your entry to match in the correct place.

2025-02-03 20:17 UTC, DjordjeMandic commented
> > Build codeowners file
> 
> It's possible to that from github web tool ?

I don't think so, you could manually update the file.

I did it for you on your branch.
```diff
diff --git a/CODEOWNERS b/CODEOWNERS
index cdf4ab7a9..796447a26 100644
--- a/CODEOWNERS
+++ b/CODEOWNERS
@@ -164,7 +164,7 @@ esphome/components/gcja5/* @gcormier
 esphome/components/gdk101/* @Szewcson
 esphome/components/globals/* @esphome/core
 esphome/components/gp2y1010au0f/* @zry98
-esphome/components/gp8403/* @jesserockz
+esphome/components/gp8403/* @jesserockz @sebydocky
 esphome/components/gpio/* @esphome/core
 esphome/components/gpio/one_wire/* @ssieb
 esphome/components/gps/* @coogle
```

2025-02-04 16:49 UTC, DjordjeMandic commented
Can you merge this https://github.com/SeByDocKy/esphome/pull/216

2025-02-04 17:19 UTC, SeByDocKy commented
> Can you merge this [SeByDocKy#216](https://github.com/SeByDocKy/esphome/pull/216)

Just did it ... thanks for all your help ....

2025-02-04 18:47 UTC, SeByDocKy commented
Thanks to your help, it should be now ready for merging (after the reviewing process I guess)

2025-02-04 18:51 UTC, DjordjeMandic approved these changes
@jesserockz Could you take a quick look at this? LGTM

2025-04-14 15:14 UTC, arzaman commented
Hi 
I don't understand if with the last ESPhome release the gp8503 component supports also the **15 bit GP8413 DAC**
any clarification is appreciated
br
Davide

2025-04-14 17:09 UTC, SeByDocKy commented
> Hi I don't understand if with the last ESPhome release the gp8503 component supports also the **15 bit GP8413 DAC** any clarification is appreciated br Davide

Not yet but you can use as external component

> Hi I don't understand if with the last ESPhome release the gp8503 component supports also the **15 bit GP8413 DAC** any clarification is appreciated br Davide

You can use as external component

```
external_components:    

  - source: github://pr#7726
    components: [gp8403]
    refresh: 10s
```

2025-04-14 17:16 UTC, arzaman commented
> ```
> external_components:    
> 
>   - source: github://pr#7726
>     components: [gp8403]
>     refresh: 10s
> ```

thanks for the prompt reply !
not familiar with "external component" but I will give it a try :-)
If I understand well I just need to add to my standard *gp8403  component definition the attribute gp8413: True right ?

let you know if I succed to use the 15bit version 
thanks 
Davide

2025-04-14 17:33 UTC, SeByDocKy commented
> > ```
> > external_components:    
> > 
> >   - source: github://pr#7726
> >     components: [gp8403]
> >     refresh: 10s
> > ```
> 
> thanks for the prompt reply ! not familiar with "external component" but I will give it a try :-) If I understand well I just need to add to my standard *gp8403 component definition the attribute gp8413: True right ?
> 
> let you know if I succed to use the 15bit version thanks Davide

yes just add 
```gp8413: True```

2025-04-14 21:22 UTC, arzaman commented
> 
> yes just add `gp8413: True`

I got crazy to try to make the DAC working..

I try to explain and hope you can help me to find what is wrong in my YAML file

NOTICE: I have an example sketch for Arduino IDE that works perfectly 
[https://github.com/m5stack/M5StickC-Plus/blob/master/examples/Hat/DAC2_GP8413/DAC2_GP8413.ino](url)
so this prof that
1) the M5stack DAC2 hat HW is ok and works fine
2) The I2C GPIO  (0 SDA  and 26 SCL) and the I2C address 0x59 

here my Yaml file


```
# M5StickC Plus Grove Port A uses G0 (SDA) and G26 (SCL)
i2c:
  - id: bus_a
    sda: GPIO0
    scl: GPIO26
    scan: true
    

# Integrazione GP8413 tramite PR ESPHome
external_components:
  - source: github://pr#7726
    components: [gp8403]
    refresh: 10s

# Configurazione chip DAC
gp8403:
  id: dac_hub
  i2c_id: bus_a
  address: 0x59
  voltage: 10V
  gp8413: true

# Output DAC canale 0
output:
  - platform: gp8403
    id: dac_output_0
    gp8403_id: dac_hub
    channel: 0
  - platform: gp8403
    id: dac_output_1
    gp8403_id: dac_hub
    channel: 1

# Integrazione Light per slider dimmer su Home Assistant
light:
  - platform: monochromatic
    name: "DAC CH0"
    output: dac_output_0
  - platform: monochromatic
    name: "DAC CH1"
    output: dac_output_1
```


compilation is OK but no way to initialize I2C bus and the log always contains

`23:16:04][I][i2c.arduino:096]: Results from i2c bus scan:
[23:16:04][I][i2c.arduino:098]: Found no i2c devices!`

I think the issue is related to the use of GPIO0 that is used in boot procedure for the I2C, and it seems that compiltation with Arduino IDE has different initializtion procedure than ESPhome

Any suggestion or idea how to exit this stale situation ?

**UPDATE**
I connect my damn DAC2 GP8413 module to GPIO 32 and 33 , standard I2C grove port of M5stickC uController
same story: with arduino sketch works fine, with ESPhome again error on I2C bus communication
this time the error is "` [E][i2c.arduino:234]: Recovery failed: SCL is held LOW on the I2C bus"
`


thanks in adavance
Davide

2025-04-15 06:18 UTC, SeByDocKy commented
> > yes just add `gp8413: True`
> 
> I got crazy to try to make the DAC working..
> 
> I try to explain and hope you can help me to find what is wrong in my YAML file
> 
> NOTICE: I have an example sketch for Arduino IDE that works perfectly [https://github.com/m5stack/M5StickC-Plus/blob/master/examples/Hat/DAC2_GP8413/DAC2_GP8413.ino](url) so this prof that
> 
> 1. the M5stack DAC2 hat HW is ok and works fine
> 2. The I2C GPIO  (0 SDA  and 26 SCL) and the I2C address 0x59
> 
> here my Yaml file
> 
> ```
> # M5StickC Plus Grove Port A uses G0 (SDA) and G26 (SCL)
> i2c:
>   - id: bus_a
>     sda: GPIO0
>     scl: GPIO26
>     scan: true
>     
> 
> # Integrazione GP8413 tramite PR ESPHome
> external_components:
>   - source: github://pr#7726
>     components: [gp8403]
>     refresh: 10s
> 
> # Configurazione chip DAC
> gp8403:
>   id: dac_hub
>   i2c_id: bus_a
>   address: 0x59
>   voltage: 10V
>   gp8413: true
> 
> # Output DAC canale 0
> output:
>   - platform: gp8403
>     id: dac_output_0
>     gp8403_id: dac_hub
>     channel: 0
>   - platform: gp8403
>     id: dac_output_1
>     gp8403_id: dac_hub
>     channel: 1
> 
> # Integrazione Light per slider dimmer su Home Assistant
> light:
>   - platform: monochromatic
>     name: "DAC CH0"
>     output: dac_output_0
>   - platform: monochromatic
>     name: "DAC CH1"
>     output: dac_output_1
> ```
> 
> compilation is OK but no way to initialize I2C bus and the log always contains
> 
> `23:16:04][I][i2c.arduino:096]: Results from i2c bus scan: [23:16:04][I][i2c.arduino:098]: Found no i2c devices!`
> 
> I think the issue is related to the use of GPIO0 that is used in boot procedure for the I2C, and it seems that compiltation with Arduino IDE has different initializtion procedure than ESPhome
> 
> Any suggestion or idea how to exit this stale situation ?
> 
> **UPDATE** I connect my damn DAC2 GP8413 module to GPIO 32 and 33 , standard I2C grove port of M5stickC uController same story: with arduino sketch works fine, with ESPhome again error on I2C bus communication this time the error is "`[E][i2c.arduino:234]: Recovery failed: SCL is held LOW on the I2C bus"`
> 
> thanks in adavance Davide

Why are you using GPIO0 for I2C ? You can't choose something ? ...It's the boot pin.... must be avoided.

2025-04-15 09:40 UTC, arzaman commented
> Why are you using GPIO0 for I2C ? You can't choose something else ? ...It's the boot pin.... must be avoided. Are you sure of the default I2C address 0x59 ?

hank you again for your kind support.

Regarding your question, the M5Stack modules I am using are designed to connect to GPIO0 and GPIO26. The images below illustrate this connection method, which I find convenient for my setup.

![image](https://github.com/user-attachments/assets/e555a71f-62e9-415f-b97f-0b842920c1d6)

As you can see, there are two connection options available:

Top Connector: Exposes GPIO 0 and GPIO 26.
Bottom "Grove" Connector: Exposes GPIO 32 and GPIO 33, which are commonly used for interfacing microcontrollers with external I2C devices.

Here is the pinout on the back of the controller for your reference:

![image](https://github.com/user-attachments/assets/0f850433-cb6f-491f-b19e-2b4ae3c5ad7b)


Based on my experiments using the Arduino IDE and the DFrobot library for the GP8413 sensor, I have found that both connection options work successfully. This leads me to conclude the following:

- The DAC module hardware is functioning correctly.
- I2C bus communication is **working properly using both GPIO 0 & 26 AND GPIO 32 & 33**.
- The I2C address 0x59 for the GP8413 is correct.

My goal is to achieve seamless integration within Home Assistant (HA), and therefore I prefer to utilize the ESPHome framework.

After compiling and executing the YAML configuration (could you please let me know if there are any potential errors in it?), I observed the following results:

- With the HAT module (GPIO 0 and 26): The GP8413 sensor was not detected, neither with your custom component nor with the standard GP8403 component.
- With the external module (GPIO 32 and 33): I encountered the error **"Recovery failed: SCL is held LOW on the I2C bus"**.

Given these findings, I would like to know if there is a way to use my module (either the top or bottom connector) with a native Home Assistant component.

As an alternative, I could explore using the native DFrobot library and implementing some lambda functions within ESPHome. However, I am uncertain about the potential outcome of this approach.

Thank you for your time and continued support.
Davide

2025-04-15 09:52 UTC, SeByDocKy commented
Can you test with another "normal" ESP32/ESP32-S3 ?

2025-04-15 14:16 UTC, arzaman commented
> Can you test with another "normal" ESP32/ESP32-S3 ?

Saying that the M5stickC plus microcontroller has nothing strange/special and is based on ESP32-PICO-D4 and I have used succesfully in other project I take your suggestion and movo to a M5stack Atom S3 lite that is again super standard with ESP32-S3FN8 microcontroller

I change the board definition to
```
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino
```

and now the DAC GP8413 with external component is recognized and managed correctly

```
[15:55:54][I][i2c.arduino:096]: Results from i2c bus scan:
[15:55:54][I][i2c.arduino:102]: Found i2c device at address 0x59
```

It's quite strange that with a standard ESP32-PICO-D4 I had such an Issue (using GPIO 32 & 33 and not the 0 that can have some conflict) in I2C initialization . Before changing microcontroller I was trying to add some delay in the boot sequence and prioritize I2C initialization to fix the issue..
My conclusion after my experiment is that the Ardunino IDE compilation manage boot sequence and priorty in a different way then ESPhome 

In  Arduino code,  explicitly end the Wire instance is perfromed  before reinitializing it with the correct pins:
```
Wire.end();
Wire.begin(32, 33);
```

I have a workaround solution even if the M5stickC plus with display and "hat" is a cool device and my primary choice
If I do any progress on this set up will update the thread

many thanks for the support
Davide

2025-05-01 01:56 UTC, jesserockz reviewed
I dislike the boolean config values that say if it is a specific model. Much rather have an actual `model: ...`  config value =)

2025-05-01 06:59 UTC, SeByDocKy commented
> I dislike the boolean config values that say if it is a specific model. Much rather have an actual `model: ...` config value =)

Coz I did like in https://next.esphome.io/components/pcf8574   :) Thx for your much better improving

2025-11-04 02:26 UTC, swoboda1337 requested changes
PR has conflicts, please resolve them. No docs PR either. Thanks

2025-11-04 07:25 UTC, SeByDocKy commented
The PR for doc is here : https://github.com/esphome/esphome-docs/pull/4415 but closed...

2025-11-04 12:57 UTC, swoboda1337 requested changes

2025-11-04 12:57 UTC, swoboda1337 commented on tests/components/gp8403/common.yaml
> +    model: GP8413
```suggestion
    i2c_id: i2c_bus
    model: GP8403
    voltage: 10V
  - id: gp8413
    i2c_id: i2c_bus
    model: GP8413
```

2025-11-04 12:57 UTC, swoboda1337 commented on esphome/components/gp8403/gp8403.cpp
> +  ESP_LOGCONFIG(TAG, "  Model: %s", LOG_STR_ARG(model_to_string(this->model_)));
```suggestion
  ESP_LOGCONFIG(TAG,
                "GP8403:\n"
                "  Voltage: %dV\n"
                "  Model: %s",
                this->voltage_ == GP8403_VOLTAGE_5V ? 5 : 10,
                LOG_STR_ARG(model_to_string(this->model_)));
```

2025-11-04 12:57 UTC, swoboda1337 commented on esphome/components/gp8403/gp8403.cpp
> +  ESP_LOGCONFIG(TAG, "  Model: %s", LOG_STR_ARG(model_to_string(this->model_)));
Should do these in one print, see other components.

2025-11-04 12:57 UTC, swoboda1337 commented on tests/components/gp8403/common.yaml
> +    model: GP8413
Add i2c_id

2025-11-04 17:00 UTC, swoboda1337 submitted a review, later dismissed

2025-11-04 17:07 UTC, swoboda1337 approved these changes

2025-11-04 17:11 UTC, swoboda1337 approved these changes

2025-11-04 17:16 UTC, merged