[fix] Status sensor does not check if required network component is missing
OttoWinter/esphomeyaml pull request #7734
Opened 2024-11-08 10:19 UTC by rvalitov

# What does this implement/fix?

Compilation of status binary sensor leads to error if network component is not used. Error:
```
src/esphome/components/status/status_binary_sensor.cpp:3:10: fatal error: esphome/components/network/util.h: No such file or directory
    3 | #include "esphome/components/network/util.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs\garage-sensors\src\esphome\components\status\status_binary_sensor.cpp.o] Error 1
```

If something is missing for other components, then this info is displayed properly and beautifully about missing component, for example:
```
sensor.uptime: [source zigbee.yaml:96]

  This option requires component time.
  platform: uptime
  id: esp_last_booted
  type: timestamp
  name: Last booted
```

So if network component is missing a similar message should be displayed:
```
  This option requires component network.
  platform: status
  name: Status
```
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes [#6383](https://github.com/esphome/issues/issues/6383)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: sensor
  friendly_name: Sensor
  platformio_options:
    board_build.flash_mode: dio 

esp32:
  board: esp32-c6-devkitc-1
  variant: ESP32C6
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
      CONFIG_ZB_ENABLED: y
      CONFIG_ZB_ZED: y
      CONFIG_ZB_RADIO_NATIVE: y
      ZB_ED_ROLE: y

binary_sensor:    
  - platform: status
    name: Status
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-08 17:12 UTC, rvalitov commented
Tested with ESP32-C6. Used component `debug` as an example.

2024-11-08 17:55 UTC, DjordjeMandic approved these changes
Tested locally, works

2024-11-11 03:16 UTC, jesserockz requested changes

2024-11-11 03:16 UTC, jesserockz commented on esphome/components/status/binary_sensor.py
> +from . import CONF_STATUS_ID
Im not sure why you didnt just add this, nothing else in this PR is required. And will force either wifi or ethernet to be present when trying to use this binary sensor.

```suggestion

DEPENDENCIES = ["network"]
```

2024-11-23 00:01 UTC, DjordjeMandic approved these changes

2024-11-24 22:23 UTC, jesserockz approved these changes

2024-11-24 22:23 UTC, merged