[time_based] : Support for tilt
OttoWinter/esphomeyaml pull request #7738
Opened 2024-11-08 22:45 UTC by adambogocz

# What does this implement/fix?

Adding support for shades/blinds which tilts.  Additionally it also accounts for activation delay of the rotary engine to get precision especially for inputs with small tilt change.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes [issue 664](https://github.com/esphome/feature-requests/issues/664)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [x] RP2040
- [x] BK72xx
- [x] RTL87xx

## Example entry for `config.yaml`:

```yaml
cover:
  - platform: time_based
    id: roller_1
    name: "Roleta 1"
    device_class: blind
    open_duration: 46sec
    close_duration: 45sec
    tilt_duration: 1sec
    activation_delay: 300ms
    open_action:
      - switch.turn_on: roller_1_up_switch
    close_action:
      - switch.turn_on: roller_1_down_switch
    stop_action:
      - switch.turn_off: roller_1_up_switch
      - switch.turn_off: roller_1_down_switch
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-12-04 16:13 UTC, sleepymaxx approved these changes
Worked like a charm! Thank you very much. Best wishes

2024-12-24 19:43 UTC, krystof-k commented
Works perfectly! Thanks! Hope it will get merged soon :)

2025-08-07 05:44 UTC, jesserockz requested changes
I think this needs to be reworked to add tilt. There should be a `tilt_action` trigger to automate on separately from the `open_action`

2025-08-07 05:44 UTC, jesserockz commented on esphome/components/time_based/cover.py
> +            ): cv.positive_time_period_milliseconds,
```suggestion
            cv.Optional(CONF_TILT_DURATION): cv.positive_time_period_milliseconds,
            cv.Optional(
                CONF_ACTIVATION_DELAY, default="0s"
            ): cv.positive_time_period_milliseconds,
```

2025-08-07 05:44 UTC, jesserockz commented on esphome/components/time_based/cover.py
> +    cg.add(var.set_tilt_duration(config[CONF_TILT_DURATION]))
```suggestion
    if tilt_duration := config.get(CONF_TILT_DURATION):
        cg.add(var.set_tilt_duration(tilt_duration))
```

2025-08-07 05:44 UTC, jesserockz commented on esphome/components/time_based/time_based_cover.cpp
> +  ESP_LOGCONFIG(TAG, "  Activation delay: %" PRIu32 "ms", this->activation_delay_);
```suggestion
                "  Close Duration: %.1fs"
                "  Activation delay: %" PRIu32 "ms",
                this->open_duration_ / 1e3f, this->close_duration_ / 1e3f,
                this->activation_delay_);

  if (this->tilt_duration_ > 0)
    ESP_LOGCONFIG(TAG, "  Tilt Duration: %" PRIu32 "ms", this->tilt_duration_);
```

2025-08-07 05:44 UTC, jesserockz commented on esphome/components/time_based/time_based_cover.h
> +  uint32_t tilt_duration_;
```suggestion
  uint32_t tilt_duration_{0};
```

2025-08-23 14:59 UTC, yvolchkov commented
it seems https://github.com/esphome/esphome/pull/6146 provides a bit reacher functionality. Still not enough for my use case but closer. Could you guys consider that MR instead?

2025-11-29 00:49 UTC, closed without merging