Updated dfplayer logging to be more user-friendly
OttoWinter/esphomeyaml pull request #7740
Opened 2024-11-09 04:37 UTC by solarkennedy

# What does this implement/fix?

I spent a number of hours troubleshooting a dfplayer, decoding hex output and stuff.

I think the logging can be improved to save time in the future. Specifically:

* LOGD for all actual dfplayer actions in human-readable form
* LOGV for any hex dump (was LOGD previously)
* LOGE for all errors, and expand the coverage for error codes

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- https://github.com/esphome/issues/issues/5174 is an example of an issue that would probably be easily debuggable with this PR in place.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-09 15:06 UTC, solarkennedy commented
```
Error: esphome/components/dfplayer/dfplayer.h:111:5: lint: Found reference to ESP_LOG in header file. Using ESP_LOG* in header files is currently not possible - please move the definition to a source file (.cpp)
```

Hmm. I'm surprised because it works locally? But I can move them.

2024-11-09 21:38 UTC, DjordjeMandic requested changes
Move tag const back to cpp since no logging is allowed inside header files. If you wish to keep it in header, at least move it inside dfplayer namespace

If function needs logging, declare it only in header, define it in cpp.

2024-11-09 21:38 UTC, DjordjeMandic commented on esphome/components/dfplayer/dfplayer.cpp
> -static const char *const TAG = "dfplayer";
Keep tag inside CPP file. Line number in logs is generated based on line number inside that cpp file.

So do not delete it, also keep it inside namespace esphome::dfplayer like it was before

2024-11-09 21:38 UTC, DjordjeMandic commented on esphome/components/dfplayer/dfplayer.h
> +static const char *const TAG = "dfplayer";
I'd move this to cpp file, dont log inside header file. Line number in logs is based on line number in cpp file.

2024-11-09 21:38 UTC, DjordjeMandic commented on esphome/components/dfplayer/dfplayer.h
>    void next() {
Declare functions in header, define them in cpp (cpp file should contain body of function in this case since `ESP_LOG*` is not allowed in header file).

2024-11-09 21:39 UTC, DjordjeMandic commented
> Hmm. I'm surprised because it works locally? But I can move them.

It works but compare line numbers in log entries with ESP_LOG* in header and in cpp

2024-11-10 00:31 UTC, solarkennedy commented on esphome/components/dfplayer/dfplayer.h
>    void next() {
got it, ty

2024-11-10 09:59 UTC, DjordjeMandic reviewed
Looks good, maybe make it more readable and that's it.

2024-11-10 09:59 UTC, DjordjeMandic commented on esphome/components/dfplayer/dfplayer.cpp
> +void DFPlayer::previous() {
Maybe add a new line between methods? Not trivial but makes it more readable.

2024-11-10 09:59 UTC, DjordjeMandic commented on esphome/components/dfplayer/dfplayer.cpp
>              }
Nothing wrong with it, if you wish you could switch thru argument instead of else if for each case.

2024-11-10 11:08 UTC, DjordjeMandic approved these changes

2024-11-10 20:53 UTC, jesserockz requested changes
Agree with the points made above

2024-11-12 22:30 UTC, DjordjeMandic approved these changes

2024-11-12 22:54 UTC, jesserockz approved these changes

2024-11-12 22:54 UTC, merged