feat: add target temperature as sensor
OttoWinter/esphomeyaml pull request #7745
Opened 2024-11-10 10:15 UTC by janschroeter

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- TODO: esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: uponor_smatrix
    address: 0x0A32
    target_temperature:
      name: Target Temperature Living Room

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-11 03:04 UTC, jesserockz requested changes
Code looks good, please add to the test yaml

2024-11-11 12:07 UTC, janschroeter commented
Thanks for your review @jesserockz 
Still working on the code, since I intend to implement the current heating state from the thermostat as sensor also. Since this should no be a big thing i will combine these changes in this pr.

2024-11-13 17:35 UTC, janschroeter commented
Just decided to do the other code changes later, when time permits and open a new pr for them. Removing draft state for this one and hope everything is fine.

2025-01-22 09:20 UTC, kroimon approved these changes
Hi @janschroeter!
Thanks for your contribution and sorry for not reviewing it earlier!
Looks good to me.
If you can, please merge the latest dev branch :)

2025-01-29 19:20 UTC, janschroeter commented
Hi @kroimon,
sorry for beeing late now myself. I hope this is what you requested.

2025-02-05 02:44 UTC, jesserockz approved these changes

2025-02-05 02:53 UTC, merged