[i2s_audio] I2S speaker improvements
OttoWinter/esphomeyaml pull request #7749
Opened 2024-11-11 13:27 UTC by kahrendt

# What does this implement/fix?

- (Bugfix) Fixes a rare crash when the speaker tries to stop while another component is writing to the ring buffer. Uses a ``shared_ptr`` to manage the ring buffer to prevent this instead of using an event group bit to lock the ring buffer.
- (Bugfix) Properly detects DMA buffer underflows so that the ``finish`` function behaves correctly. Attaches a queue during the I2S driver installation to monitor this.
- (New feature) Adds a yaml configuration option to disable stopping the speaker due to a timeout.
- (New feature) Allocates the DMA buffers and ring buffers based on the configured audio stream information. Instead of using fixed sample numbers, it takes into account the number of channels, bytes per sample, and the sample rate for consistent behavior with different settings.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- closes #7677, as the finish function now behaves properly and will avoid a breaking change

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#4426

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

speaker:
  - platform: i2s_audio
    i2s_dout_pin: GPIO15
    dac_type: external
    sample_rate: 16000
    bits_per_sample: 16bit
    channel: stereo
    timeout: disabled

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-11 17:00 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +
Be careful with this, switching to newer versions of edi_idf will break this construction.
V5.0 changes this to an isr callback. 
Maybe adding `#if ESP_IDF_VERSION == ESP_IDF_VERSION_VAL(4, 4)` check around it.

2024-11-11 17:00 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +  if (this_speaker->send_esp_err_to_event_group_(this_speaker->allocate_buffers_(dma_buffers_size, ring_buffer_size))) {
Just wondering, why having the `this_speaker->send_esp_err_to_event_group_()` called here instead of doing this for example in the `this_speaker->allocate_buffers_()`?

Calling it in `this_speaker->allocate_buffers_()` makes the code look much cleaner imho.

2024-11-11 17:00 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +    // Temporarily share ownership of the ring buffer so it won't be deallocated while writing
This is a very good idea. Just on suggestion, could you add some comments on the meaning why `use_count()` needs to be **1**, and which values could it be otherwise?

2024-11-11 17:42 UTC, kahrendt commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +
What part is the ISR callback? What version esp-idf are you getting this issue? I just tested building and running it on 5.1.2 and 5.3.0 with no issues.

2024-11-11 17:47 UTC, kahrendt commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +  if (this_speaker->send_esp_err_to_event_group_(this_speaker->allocate_buffers_(dma_buffers_size, ring_buffer_size))) {
In general, I wanted the ``allocate_buffers_``, ``start_i2s_driver_``, and ``reconfigure_i2s_stream_info_`` to be as informative as possible when returning an error. These functions are very general and do not rely on the event group. 

In the task, which depends on the event group, I only need to know whether they are successful or not, and if not, it should send the error to the event group. So I call that helper function inside the task to centralize this operation for all 3 functions.

2024-11-11 18:12 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +  if (this_speaker->send_esp_err_to_event_group_(this_speaker->allocate_buffers_(dma_buffers_size, ring_buffer_size))) {
thanks for the explanation. this can be closed.

2024-11-11 18:17 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +
top. I did not got an error i just checked the documentation: https://docs.espressif.com/projects/esp-idf/en/release-v5.0/esp32/api-reference/peripherals/i2s.html#id9
and
https://docs.espressif.com/projects/esp-idf/en/release-v5.0/esp32/api-reference/peripherals/i2s.html#_CPPv435i2s_channel_register_event_callback17i2s_chan_handle_tPK21i2s_event_callbacks_tPv

2024-11-11 18:20 UTC, kahrendt commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +
I'm pretty sure those refer to the new I2S driver for IDF v5. We use the legacy I2S driver, so it's still using the same the driver code from v4.4.

2024-11-11 19:09 UTC, nielsnl68 commented on esphome/components/i2s_audio/speaker/i2s_audio_speaker.cpp
> +
check that was what i expected when you said that it worked on 5.1.2 and 5.3.0

2024-11-11 19:09 UTC, nielsnl68 approved these changes

2024-11-12 00:58 UTC, kahrendt commented
I temporarily set this back as a draft, as I want to make one small change so that the ring buffer duration is configurable. Having it fixed at 500 ms matches the current behavior for only 16 kHz audio streams. Unfortunately, it will cause issues with the speaker media player component by making the pause command take half a second to actually go into effect.

I'll update the PR tomorrow with that option added.

2024-11-12 03:30 UTC, jesserockz requested changes
Just one comment about the timeout value, but otherwise looks good to me.

2024-11-12 03:30 UTC, jesserockz commented on esphome/components/i2s_audio/speaker/__init__.py
> +            cv.Optional(CONF_TIMEOUT, default="500ms"): cv.Any(
This should be consistent with things like `wifi`/`api` -> `reboot_timeout`  where `0s` means never, or `never` like can be specified for `update_interval`

2024-11-12 18:19 UTC, jesserockz approved these changes

2024-11-12 18:20 UTC, merged