Fix DHT11 not reading any values
OttoWinter/esphomeyaml pull request #7752
Opened 2024-11-11 22:15 UTC by minomy13

# What does this implement/fix?
Makes the DHT11 read correct values if used correctly with an external pull-up resistor as [described in documentation](https://esphome.io/components/sensor/dht.html).
I disabled the internal pull-up resistor. With double pull-ups there is no chance of reading any values.

Credits to Reddit user [Responsible_Hat_6056](https://www.reddit.com/user/Responsible_Hat_6056/) who shared the fix in a [post](https://www.reddit.com/r/raspberrypipico/comments/1133qqr/comment/j91qmtt/) some time ago.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml, as found in documentation
sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-13 01:30 UTC, DjordjeMandic commented
Why would this be a problem? Internal pullup is anyways 10k and up. Do you have any captures from oscilloscope showing falling edges?

This looks more like software fix for hardware specific problem caused due to sensor that's faulty or operating outside of recommended specs.

2024-11-13 01:32 UTC, DjordjeMandic requested changes
Add to docs that in yaml config you can disable internal pullup with pin schema. Don't make it hard coded, your proposed change is breaking one. Some people don't use external pullup. 

Then add bool to dht.h that will store value of that pullup enable state and add method to set pullup enable state. 

Then in code generation, get value of pullup optional parameter from pin schema supplied for dht pin and use it in code gen for that method above. 

Enable pullup based on bool from dht.h

2024-11-13 13:14 UTC, minomy13 commented
So, no, it's not RP2040 related. The most breakout boards just already have a pull-up resistor and a capacitor installed. I tested it with the original code and it just didn't work.

But, you're absolutely right - it would be breaking for those people who are not using an external pull up. I will definitely implement the config option!

2024-11-13 15:53 UTC, DjordjeMandic commented on esphome/const.py
> +CONF_INTERNAL_PULLUP = "use_internal_pullup"
I'd move this to dht/sensor.py, let those with write access decide

2024-11-13 15:59 UTC, minomy13 commented on esphome/const.py
> +CONF_INTERNAL_PULLUP = "use_internal_pullup"
Okay, moved it.

2024-11-13 16:24 UTC, DjordjeMandic commented on esphome/components/dht/sensor.py
> +CONF_INTERNAL_PULLUP = "use_internal_pullup"
```suggestion
CONF_USE_INTERNAL_PULLUP = "use_internal_pullup"
```

```suggestion
CONF_INTERNAL_PULLUP = "internal_pullup"
```

2024-11-13 18:42 UTC, minomy13 commented on esphome/const.py
> +CONF_INTERNAL_PULLUP = "use_internal_pullup"
@OttoWinter Could you please take a look if I should leave the constant where it is now or if it should be in const.py?

2024-11-17 19:11 UTC, jesserockz commented
Considering the `pin` schemas already have flags/mode, adding a `get_flags` to the generic `InteralGPIOPin` classes will allow component code to get the desired flags from the user and have defaults

2025-01-28 13:53 UTC, DjordjeMandic requested changes

2025-01-28 13:53 UTC, DjordjeMandic commented on esphome/components/dht/dht.cpp
> +  }
```suggestion
    ESP_LOGCONFIG(TAG, "  Internal pull-up resistor: %s", ONOFF(this->use_internal_pullup_));
```

Use one of these macros:
https://github.com/esphome/esphome/blob/f7f8bf4da44b83796a301bc486d77fdb46d8ed82/esphome/core/log.h#L161-L163

2025-01-28 20:01 UTC, kroimon commented
Couldn't the `CONF_PIN` / `pin:` configuration just be changed to `internal_gpio_input_pullup_pin_schema` so that the pull-up is enabled by default like it was before, but the user could override it with `pullup: False`?

2025-01-28 20:41 UTC, DjordjeMandic commented
@kroimon same gpio is used for output and it's switched between input and output during runtime. Schema does set initial stage, but during runtime you can't know what was the initial state. That's where get_flags become useful.

2025-01-28 20:54 UTC, kroimon commented
Oh I see! Sorry, didn't look too much into the component and wasn't aware of the direction switching.

2025-02-03 12:18 UTC, DjordjeMandic commented on esphome/components/dht/sensor.py
Discard this

2025-02-03 12:18 UTC, DjordjeMandic commented on esphome/components/dht/dht.h
Discard changes for this whole file

2025-02-03 12:27 UTC, DjordjeMandic commented on esphome/components/dht/dht.cpp
> +  }
```suggestion
  this->pin_->pin_mode(gpio::FLAG_INPUT | (this->pin_->get_state() & gpio::Flags::FLAG_PULLUP ? gpio::Flags::FLAG_PULLUP : 0));
```

2025-02-03 12:28 UTC, DjordjeMandic requested changes
@minomy13  https://github.com/esphome/esphome/pull/8151 is merged into dev, update your branch and use get_flags()

2025-02-16 11:23 UTC, DjordjeMandic commented
Closed in favour of #8257

2025-02-16 11:23 UTC, closed without merging