[midea] Add Fahrenheit support to `midea_ac.follow_me Action`
OttoWinter/esphomeyaml pull request #7762
Opened 2024-11-13 20:55 UTC by DjordjeMandic

# What does this implement/fix?

Implements a feature for the Midea AC component in ESPHome to correctly handle "Follow Me" temperature updates in Fahrenheit. Previously, when ESPHome sent temperature updates, the Midea AC unit would automatically switch to Celsius, regardless of the user's preferred unit setting. This update allows the "Follow Me" function to respect Fahrenheit settings, providing consistent and accurate temperature displays on the AC unit for users who prefer Fahrenheit. **NEEDS TESTING**

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/feature-requests/issues/2790

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

external_components:
  - source: github://DjordjeMandic/esphome@midea-follow-me-temp-f
    components: [ midea, midea_ac, midea_ir ]
    refresh: always
  - source: github://TheStaticTurtle/esphome_syslog
    components: [ syslog ]
    refresh: always

script:
  - id: update_follow_me
    parameters:
      temp: float
    mode: queued
    then:
      - midea_ac.follow_me:
          temperature: !lambda "return (temp * 9.0) / 5.0 + 32;"
          fahrenheit: true
          beeper: false               # Optional. Beep on update.
      - syslog.log: # external component 
          level: 3
          tag: "FollowMeUpdate"
          payload: !lambda |-
            char buffer[128];
            long rounded_temp = lroundf(temp);
            snprintf(buffer, sizeof(buffer), "Executed, temp=%.1f°C, rounded=%ld°C", temp, rounded_temp);
            return std::string(buffer);
```

## Checklist:
  - [x] The code change is tested and works locally (unit set to C).
  - [ ] The code change is tested by other users and works on their units set to F.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-14 14:58 UTC, DjordjeMandic commented
Builds just fine locally, i dont know why actions are throwing `src/esphome/components/midea/appliance_base.h:18:10: fatal error: esphome/components/midea_ir/midea_data.h: No such file or directory` error

2024-11-14 18:57 UTC, dbaq commented
I've tested your branch on my minisplit (Bryant 619AHB but it is midea under the hood) and it works beautifully. Thank you for opening this.

With `fahrenheit: true`, I see the following output and the display on unit does remain in fahrenheit now!

```
[10:49:20][D][sensor:093]: 'Room Temperature Sensor': Sending state 69.40000 °F with 1 decimals of accuracy
[10:49:20][D][midea:138]: Follow me action called with temperature: 69.400002 °F, rounded to: 69 °F
[10:49:20][D][remote_transmitter:075]: Sending remote code...
```


With `fahrenheit: false`,  the unit switches to celsius as expected.

Thank you, thank you!

2024-11-14 19:23 UTC, DjordjeMandic commented
You're welcome, i have plans for next pr to merge midea_ir into midea with typed config schema for easier development.

2024-11-15 13:33 UTC, DjordjeMandic commented
Thats it, I'm not changing anything more in this PR. It's ready for review

2024-11-17 15:45 UTC, mmiller7 commented
Just found this, also interested since my unit uses Fahrenheit.  Glad to see its up to review!

2024-11-21 19:49 UTC, jesserockz requested changes

2024-11-21 19:49 UTC, jesserockz commented on esphome/components/midea/climate.py
> +AUTO_LOAD = ["sensor", "midea_ir"]
Other components should not be auto loaded unless it will always be used by the config/project regardless of configuration. If someone is not using follow me with this change, it adds a lot of unused code to the firmware.

2024-11-21 20:47 UTC, DjordjeMandic commented on esphome/components/midea/climate.py
> +AUTO_LOAD = ["sensor", "midea_ir"]
> Other components should not be auto loaded unless it will always be used by the config/project regardless of configuration. If someone is not using follow me with this change, it adds a lot of unused code to the firmware.

Will fix it tonight but only solution i see is to have one duplicate header (same header existing in both components). It was like that before, I thought code from midea_ir wouldn't get linked after compilation and occupy flash without reason, because I need only one header from midea_ir.

Header midea_data.h does not have any functions in any source files of midea_ir component.

2024-11-22 01:03 UTC, DjordjeMandic commented on esphome/components/midea_ir/midea_data.h
> +// TODO: make base, why? Because this file can be used by midea component also. See
This should be better done with new pull request. Making base and adding more special ir commands

2024-11-22 01:03 UTC, DjordjeMandic commented on esphome/components/midea/ir_transmitter.h
> +// TODO: see esphome/components/midea_ir/midea_data.h
I decided to leave it like this for now. Plan is to make base with midea_ir_data.h which will contain content of midea_data.h + some more special ir commands taken from irremoteesp8266

2024-12-17 05:09 UTC, dbaq commented
@jesserockz would you be able to do another pass on this PR soon? a few of us in the USA would love this to get merged! Thanks both!

2024-12-17 11:12 UTC, DjordjeMandic commented
> @jesserockz would you be able to do another pass on this PR soon? a few of us in the USA would love this to get merged! Thanks both!

Maybe change to `midea_ir` was holding this PR. Reverted it, this PR now has changes made only to `midea` component. I'll be here until checks are done.

2024-12-18 00:44 UTC, jesserockz approved these changes

2024-12-18 00:47 UTC, merged