Added Hx710 24 bit serial ADC
OttoWinter/esphomeyaml pull request #7842
Opened 2024-11-26 02:54 UTC by alpauna

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-11-26 03:08 UTC, alpauna commented
The documents have been added to esphome-docs in next via [PR esphome-docs #4474 ](https://github.com/esphome/esphome-docs/pull/4474)

2024-12-10 03:12 UTC, jesserockz requested changes
Can you please also make the sensor inherit from `voltage_sampler::VoltageSampler` so that other sensors/components can use this as an adc source

2024-12-10 03:12 UTC, jesserockz commented on esphome/components/hx710/hx710.h
> +  void set_dout_pin(GPIOPin *dout_pin) { dout_pin_ = dout_pin; }
Please prefix all member variables and function calls with `this->`
https://esphome.io/guides/contributing#codebase-standards
```suggestion
  void set_dout_pin(GPIOPin *dout_pin) { this->dout_pin_ = dout_pin; }
```

2024-12-11 11:55 UTC, alpauna commented on esphome/components/hx710/hx710.h
> +  void set_dout_pin(GPIOPin *dout_pin) { dout_pin_ = dout_pin; }
Ok fix the this-> thing but have a question on sensor.py as I am still learning its syntax to add voltage sampler.  Does this look correct?

```python
import esphome.codegen as cg
import esphome.config_validation as cv
from esphome import pins
from esphome.components import sensor, voltage_sampler
from esphome.const import (
    CONF_CLK_PIN,
    CONF_MODE,
    UNIT_VOLT,
    ICON_GAUGE,
    DEVICE_CLASS_VOLTAGE,
    STATE_CLASS_MEASUREMENT,
)

AUTO_LOAD = ["voltage_sampler"]

hx710_ns = cg.esphome_ns.namespace("hx710")
HX710Sensor = hx710_ns.class_(
    "HX710Sensor", 
    sensor.Sensor, 
    cg.PollingComponent, 
    voltage_sampler.VoltageSampler,
)

CONF_DOUT_PIN = "dout_pin"
CONF_REFERENCE_VOLTAGE = "reference_voltage"

HX710Mode = hx710_ns.enum("HX710Mode")
MODES = {
    1: HX710Mode.HX710_DIFFERENTIAL_INPUT_10HZ,
    2: HX710Mode.HX710_OTHER_INPUT_40HZ,
    3: HX710Mode.HX710_DIFFERENTIAL_INPUT_40HZ,
}

CONFIG_SCHEMA = (
    sensor.sensor_schema(
        HX710Sensor,
        unit_of_measurement=UNIT_VOLT,
        accuracy_decimals=3,
        device_class=DEVICE_CLASS_VOLTAGE,
        state_class=STATE_CLASS_MEASUREMENT,
        icon=ICON_GAUGE,
    )
    .extend(
        {
            cv.Required(CONF_DOUT_PIN): pins.gpio_input_pin_schema,
            cv.Required(CONF_CLK_PIN): pins.gpio_output_pin_schema,
            cv.Optional(CONF_REFERENCE_VOLTAGE, default="0.0V"): cv.voltage,
            cv.Optional(CONF_MODE, default=1): cv.enum(MODES, int=True),
        }
    )
    .extend(cv.polling_component_schema("60s"))
)


async def to_code(config):
    var = await sensor.new_sensor(config)
    await cg.register_component(var, config)

    dout_pin = await cg.gpio_pin_expression(config[CONF_DOUT_PIN])
    cg.add(var.set_dout_pin(dout_pin))
    sck_pin = await cg.gpio_pin_expression(config[CONF_CLK_PIN])
    cg.add(var.set_reference_voltage(config[CONF_REFERENCE_VOLTAGE])) 
    cg.add(var.set_sck_pin(sck_pin))
    cg.add(var.set_gain(config[CONF_MODE]))
```

2024-12-13 08:32 UTC, alpauna commented
Ok I give up what the heck am I doing wrong to get results like this?
```yaml
sensor:
  - platform: hx710
    name: "HX710 Value"
    dout_pin: GPIO19
    clk_pin: GPIO20
    mode: 3
    update_interval: 1s
    accuracy_decimals: 2
    device_class: pressure
```
By leaving reference_voltage off or making it 0.0V it is supposed to dump raw values.

```
02:23:30	[D]	[hx710:082]	
'HX710 Value': Got value -142703
02:23:30	[D]	[hx710:090]	
'HX710 Value': As RAW value because 0.0 ref voltage -142703
02:23:30	[V]	[sensor:043]	
'HX710 Value': Received new state 4294824704.000000
02:23:30	[D]	[sensor:094]	
'HX710 Value': Sending state 4294824704.00000 V with 2 decimals of accuracy
```
Should be returning a -142703 and instead I am getting 4294824704? 

@jesserockz, any ideas would be greatly appreciated!!! I know it has to do with the float because as decimal it is correct but as soon as float touches it it goes crazy on negatives. 

Oh, and when I use reference_voltage: it works correctly:

```yaml
sensor:
  - platform: hx710
    name: "HX710 Value"
    dout_pin: GPIO19
    clk_pin: GPIO20
    mode: 3
    reference_voltage: 5.0V
    update_interval: 1s
    accuracy_decimals: 2
    device_class: pressure
```

```
02:37:14	[D]	[hx710:082]	
'HX710 Value': Got value -404463
02:37:14	[V]	[sensor:043]	
'HX710 Value': Received new state -0.241079
02:37:14	[D]	[sensor:094]	
'HX710 Value': Sending state -0.24108 V with 2 decimals of accuracy
02:37:14	[V]	[json:038]	
```

2024-12-14 07:38 UTC, alpauna commented
I am not sure why it started to work correctly. I was able to revert back close to original code. I did not see anything that would cause issues like bad pointers. Anyway all test are passing on my dev boards now. I really would like to know what caused this issue. Did notice the yaml would not really update unless I changed the the branch the yaml was using between my two branches.  By changing between this:
```yaml
external_components:
  # use rtttl and dfplayer from ESPHome's dev branch in GitHub
  - source:
      type: git
      url: https://github.com/alpauna/esphome
      ref: hx710
    components: [ hx710]
```
and this
```yaml
external_components:
  # use rtttl and dfplayer from ESPHome's dev branch in GitHub
  - source:
      type: git
      url: https://github.com/alpauna/esphome
      ref: test-hx710
    components: [ hx710]
```
then the esphome would compile the associated cpps into o's. Or if you change the logging level then it seems to compile everything otherwise objects seemed to get out of sync with my commits.

Is there a better way to always force a compile? 

Still learning here so sorry for all the commits on this one.

2025-10-03 00:50 UTC, closed without merging