Add NTC simulation sensor (esphome/feature-requests#2967)
OttoWinter/esphomeyaml pull request #7898
Opened 2024-11-30 15:14 UTC by rhabacker

Fixes https://github.com/esphome/feature-requests/issues/2967

# What does this implement/fix?

Adds an additional sensor platform named ``ntcsim`` which is an auxiliary sensor that allows temperature readings to be converted into resistance readings that simulate an NTC thermistor, which can be used in place of a real NTC thermistor with a digital potentiometer or dac.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes feature-requests/issues#2967

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#4485

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
    # Example configuration entry
    sensor:
      - platform: ntcsim
        calibration:
          b_constant: 3950
          reference_temperature: 25°C
          reference_resistance: 10kOhm
        name: NTC Resistance simulation
        sensor: temperature_sensor
        # optional
        # output: resistance_output
        # output_resistance: 100 kOhm

      # Example source sensors:
      - platform: dallas_temp
        address: 0x1234567812345628
        id: temperature_sensor
        update_interval: 120s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-12-12 13:46 UTC, DjordjeMandic commented on esphome/components/ntcsim/sensor.py
> +            cv.Required(CONF_SENSOR): cv.use_id(sensor.Sensor),
I want to hear others what they think about this key, I think that "source_sensor" or "temperature_sensor" would be more appropriate to avoid confusion.

2024-12-21 13:59 UTC, rhabacker commented on esphome/components/ntcsim/sensor.py
> +            cv.Required(CONF_SENSOR): cv.use_id(sensor.Sensor),
I searched the existing components for similar names for temperature-related sources and found `temperature_source` and used that.

2025-01-07 13:29 UTC, DFINITYManu approved these changes

2025-02-20 08:24 UTC, rhabacker commented
Anything left to do for this pull request ?

2025-02-20 14:42 UTC, DjordjeMandic requested changes
> All uses of class members and member functions should be prefixed with this-> to distinguish them from global functions/variables.

> There should be at least one test for each framework/architecture combination.

Most of it looks good to me. Little things have to be addressed and that's all.

https://esphome.io/guides/contributing.html

2025-02-20 14:42 UTC, DjordjeMandic commented on esphome/components/ntcsim/ntcsim.cpp
> +static const char *const TAG = "ntcsimulation";
```suggestion
static const char *const TAG = "ntcsim";
```
```suggestion
static const char *const TAG = "ntc.simulation";
```

2025-02-20 14:42 UTC, DjordjeMandic commented on esphome/components/ntcsim/ntcsim.cpp
> +}
```suggestion
void NTCSimulation::setup() {
  this->sensor_->add_on_state_callback([this](float value) { this->process_(value); });
  if (this->sensor_->has_state())
    this->process_(this->sensor_->state);
}
void NTCSimulation::dump_config() {
  LOG_SENSOR("", "NTC Simulation", this);
  ESP_LOGI(TAG, "  Coefficient a: %.8f", this->a_);
  ESP_LOGI(TAG, "  Coefficient b: %.8f", this->b_);
  ESP_LOGI(TAG, "  Coefficient c: %.8f", this->c_);
}
```

2025-02-20 14:42 UTC, DjordjeMandic commented on esphome/components/ntcsim/ntcsim.cpp
> +  }
```suggestion
  if (!std::isfinite(value)) {
    this->publish_state(NAN);
    return;
  }
```

Use this if you don't accept -INF / +INF values and NAN.

2025-02-20 14:42 UTC, DjordjeMandic commented on esphome/components/ntcsim/ntcsim.cpp
> +  double x = sqrt(pow(b_ / (3 * c_), 3) + y * y);
```suggestion
  double y = (this->a_ - 1 / (t)) / (2 * this->c_);
  double x = sqrt(pow(this->b_ / (3 * this->c_), 3) + y * y);
```

2025-02-20 14:42 UTC, DjordjeMandic commented on esphome/components/ntcsim/ntcsim.h
> +  void set_c(double c) { c_ = c; }
```suggestion
  void set_sensor(Sensor *sensor) { this->sensor_ = sensor; }
#ifdef USE_OUTPUT
  void set_output(output::FloatOutput *output) { this->output_ = output; }
  void set_output_resistance(float resistance) { this->resistance_ = resistance; }
#endif
  void set_a(double a) { this->a_ = a; }
  void set_b(double b) { this->b_ = b; }
  void set_c(double c) { this->c_ = c; }
```

2025-02-20 14:42 UTC, DjordjeMandic commented on tests/components/ntcsim/test.esp8266-ard.yaml
https://esphome.io/guides/contributing.html#test-configurations

Please create common.yaml and a test for each framework/architecture combination

2025-02-20 14:42 UTC, DjordjeMandic commented on esphome/components/ntcsim/ntcsim.cpp
> +  }
```suggestion
  this->publish_state(resistance);
#ifdef USE_OUTPUT
  if (this->output_) {
    double normalized_resistance = resistance / resistance_;
    ESP_LOGI(TAG, "send normalized resistor value %f to output device", normalized_resistance);
    this->output_->set_level(normalized_resistance);
  }
```

2025-02-20 21:00 UTC, DjordjeMandic approved these changes

2025-02-23 07:56 UTC, rhabacker commented
Thanks for the approval - currently I see that “at least one positive review from reviewers with writing authorization is required” - what's the next step?

2025-02-23 11:53 UTC, DjordjeMandic commented
I guess only thing we can do is wait :)

https://esphome.io/guides/contributing.html#review-by-maintainers

Maintainers still need to review everything, share their opinions, and make the final decision. My review is just here to help catch common issues that often get flagged for changes. Reviews from those without write access serve as references but don’t directly impact the Maintainers' decisions. Even my reviews sometimes get corrected by Maintainers, but having additional reviews can still be helpful during the PR process.

2025-02-23 18:32 UTC, jesserockz commented
Just reading through the description and example YAML, this is not a `sensor` as it does not provide data to ESPHome, but is ESPHome providing data out. I think it should just be a top level component.

2025-02-28 00:26 UTC, jesserockz requested changes, later dismissed
As above

2025-02-28 07:36 UTC, rhabacker commented
> I think it should only be a top level component.

Currently, this component must be defined as: 
```
 sensor:
      - platform: ntcsim
      ....
```
You are requesting to change the type to : 
```
 ???:
      - Platform: ntcsim
      ....
```

2025-03-01 20:00 UTC, clydebarrow commented
Why not make it a filter, remove the `output` specification and just use `on_value` to set a separate output?

2025-03-01 20:01 UTC, DjordjeMandic commented
> Why not make it a filter, remove the `output` specification and just use `on_value` to set a separate output?

This!!!

2025-03-04 14:44 UTC, rhabacker commented
> `on_value`

Is the value passed to the trigger also limited to a value between 0 and 1 as with the output component?

2025-03-04 14:58 UTC, rhabacker commented
> Why not make it a filter, remove the `output` specification and just use `on_value` to set a separate output?

Are there any limitations with this type of component compared to a sensor component?

2025-03-04 19:36 UTC, clydebarrow commented
> Are there any limitations with this type of component compared to a sensor component?

Not that I can think off. A filter gets applied to a sensor (which could be a real sensor, or a copy sensor, or a template) and the end result is the same - you have a sensor whose output looks like an NTC resistor value. Sending it to a destination, in your case an output, uses an existing feature. The advantage of using a filter is more flexibility and the use of building blocks to achieve the result rather than adding a new, lumpy, single purpose component.

2025-03-04 19:38 UTC, clydebarrow commented
> Is the value passed to the trigger also limited to a value between 0 and 1 as with the output component?

No, it can be scaled to whatever range you like e.g by using the offset and multiply filters.

2025-03-04 19:46 UTC, rhabacker commented
This component was created using the `ntc` component as a template. Is there a template where I can see how to create a corresponding filter ?

2025-03-04 19:57 UTC, clydebarrow commented
AFAIK currently all the sensor filters are defined in the sensor component. It's easy enough to add one.

2025-03-04 22:10 UTC, rhabacker commented
A look at  https://esphome.io/components/sensor/index.html#calibrate-linear shows this: 
``` 
# Example of a configuration entry
- platform: dht
  # ...
  Temperature:
    name: “DHT22 Temperature”
    Filter:
      - calibrate_linear:
         Method: least_squares
         Data points:
          # map 0.0 (from sensor) to 1.0 (true value)
          - 0.0 -> 1.0
          - 10.0 -> 12.1
```
An adjustment to the NTC simulation calculation would then look like this: 
``` 
# Example of a configuration entry
- platform: dht
  # ...
  Temperature:
    name: “DHT22 Temperature”
    Filter:
      - to_ntc_resistance:
         calibration:
           b_constant: 3950
           reference_temperature: 25°C
           reference_resistance: 10kOhm
```
or 
``` 
# Example of a configuration entry
- platform: dht
  # ...
  Temperature:
    name: “DHT22 Temperature”
    Filter:
      - to_ntc_resistance:
         calibration:
          - 10.0kOhm -> 25°C
          - 27.219kOhm -> 0°C
          - 14.674kOhm -> 15°C
```
There is still a question about the name of the filter, which I assumed above with `to_ntc_resistance`. It may also help to know that there is a reverse operation with the `ntc` component.

2025-03-04 22:17 UTC, clydebarrow commented
The name sounds fine to me.

2025-03-06 08:18 UTC, rhabacker commented
> Why not make it a filter, remove the `output` specification and just use `on_value` to set a separate output?

Do you have an example how to setup this ? 

```
    on_value:
     then:
       lambda: |-
        id(xxx).???(x);
```

2025-03-06 08:47 UTC, clydebarrow commented
> Do you have an example how to setup this ?

```
	on_value:
	  then:
	    - output.set_level:
	        id: output_id
	        level: !lambda return x;
```

2025-03-06 08:58 UTC, rhabacker commented
Related to the failed request https://github.com/esphome/esphome/actions/runs/13679997942/job/38249654359?pr=7898

I don't see any reference to the changes added by the commits included in this pull request. Does anyone have a clue ?

2025-03-06 08:59 UTC, rhabacker commented
> > Do you have an example how to setup this ?
> 
> ```
> 	on_value:
> 	  then:
> 	    - output.set_level:
> 	        id: output_id
> 	        level: !lambda return x;
> ```

Thanks - I will update the associated doc.

2025-03-06 10:48 UTC, rhabacker commented
> > ```
> > 	on_value:
> > 	  then:
> > 	    - output.set_level:
> > 	        id: output_id
> > 	        level: !lambda return x;
> > ```
> 
> Thanks - I will update the associated doc.

This requires additional information, as according to https://esphome.io/components/output/#output-set-level-action the values that are passed on to the output are limited to the range 0..1 (see also e.g. https://esphome.io/components/output/x9c.html) and require scaling with the actual resistance value, e.g. of the NTC:

```
    on_value:
      then:
        - output.set_level:
            id: output_id
            level: !lambda return x / 100000.0;
```
To see the actual value that is sent to the output, the following can be added: 
```
        - logger.log:
            format: "Send %.4f to output"
            args: [ x / 100000.0 ]
```

2025-04-28 09:53 UTC, clydebarrow requested changes

2025-04-28 09:53 UTC, clydebarrow commented on esphome/components/sensor/__init__.py
> +    print("Coefficient:", a, b, c)
Is this debug code?

2025-04-28 10:24 UTC, rhabacker commented on esphome/components/sensor/__init__.py
> +    print("Coefficient:", a, b, c)
As the coefficients can be calculated, this should give the user the opportunity to check the structure. I have changed it so that it is displayed as a debug message.

2025-04-28 12:04 UTC, clydebarrow commented on esphome/components/sensor/__init__.py
> +    print("Coefficient:", a, b, c)
No change. Did you forget to push?

2025-04-28 12:05 UTC, clydebarrow requested changes

2025-04-28 12:05 UTC, clydebarrow commented on esphome/components/sensor/__init__.py
> +    print("Coefficient:", a, b, c)
It should be done as a logger INFO level message.

2025-04-28 21:23 UTC, clydebarrow requested changes
Otherwise looks good.

2025-04-28 21:23 UTC, clydebarrow commented on esphome/components/sensor/__init__.py
> +    voltage = cv.resistance(parts[0].strip())
```suggestion
    resistance = cv.resistance(parts[0].strip())
```

2025-04-28 21:23 UTC, clydebarrow commented on esphome/components/sensor/__init__.py
> +                cv.Required(CONF_VALUE): cv.float_,
Maybe use cv.temperature and cv.resistance here?

2025-04-29 00:21 UTC, clydebarrow commented
Try to avoid force-pushing to a PR especially after review has started - it makes it harder to see what's been reviewed and what hasn't. If you committed by mistake, just revert that commit.

2025-04-29 00:37 UTC, rhabacker commented
> Try to avoid force-pushing to a PR especially after review has started - it makes it harder to see what's been reviewed and what hasn't. If you committed by mistake, just revert that commit.

I've seen [this](https://esphome.io/guides/contributing#your-local-copy-of-dev), but there was no mention of how to apply required changes to existing commits instead, which are normally incorporated through an interactive git rebase. In my opinion, there should be a note here that during an active review, changes are only allowed with additional commits (fixup commits) that must be squashed into the corresponding commit after a review is completed.

2025-04-29 00:58 UTC, clydebarrow commented
Those docs are a little out of date. All you need do to keep your branch up to date is `git pull upstream dev`. It's also not essential to keep it up to date constantly - as long as github is not flagging conflicts there's no big worry.

And don't worry about squashing commits - that gets done when merging anyway. It's fine to squash commits before pushing, but once it's pushed, leave the history alone.

2025-04-29 07:08 UTC, rhabacker commented
The way I see it, the CI error at https://github.com/esphome/esphome/actions/runs/14720500742/job/41313323302 is not related to changes from this pull request - how to proceed ?

2025-05-01 05:38 UTC, clydebarrow approved these changes

2025-05-01 07:53 UTC, merged