Add flip X and Y on inkplate6 component
OttoWinter/esphomeyaml pull request #7904
Opened 2024-12-01 21:07 UTC by Leicas

# What does this implement/fix?
Fix the issue in https://github.com/esphome/issues/issues/6507 by implementing a way to flip the screen on both x and y axis, on top of the previous rotations.
They might be a cleaner way to fix it for the specific Inkplate 5gen2 but this approach seems more scalable.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes [this issue](https://github.com/esphome/issues/issues/6507)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-12-01 21:32 UTC, jesserockz requested changes
Please follow other components by using `CONF_TRANSFORM` and CONF_MIRROR_X/Y

2024-12-01 21:52 UTC, Leicas reviewed
Added transform / mirror to make it more consistent with existing codebase (thanks @jesserockz  for the hint )

2025-01-14 21:33 UTC, mrwafa commented
Hi Guys, I have the same problem with a mirrored display. Would be nice if you could complete this 😃

2025-01-14 21:41 UTC, mrwafa commented
Hi Guys, I have the same problem with a mirrored display. Have you already had the opportunity to check this? Many Thanks 😃

2025-03-04 16:48 UTC, iamfrommars81 commented
I am more than happy to accept that I am reaching past my skill level and that I should just wait until this is deployed so feel free to tell me to bugger off. 

I am attempting to test using the example config from esphome.io, and this external component. 

external_components:
  # use inkplate6  from Leicas's dev branch in GitHub
  - source:
      type: git
      url: https://github.com/Leicas/esphome.git
      ref: dev
    components: [ inkplate6 ]

Getting error:

**"[flip_x] is an invalid option for [display.inkplate6]. Please check the indentation."**

2025-03-04 23:56 UTC, Leicas commented
With the change requested by @jesserockz  it is now aligned with the other component so to answer @iamfrommars81 , this is the code:

`display:
- platform: inkplate6
  id: inkplate_display
  greyscale: false
  partial_updating: true
  update_interval: never
  model: inkplate_5_v2
  transform:
    mirror_y: true`

2025-05-14 18:55 UTC, DavidSichau commented
@jesserockz what would be required to merge this?

2025-05-15 23:48 UTC, jesserockz commented
> @jesserockz what would be required to merge this?

The first and most important is that CI is passing, otherwise it takes time away from maintainers to fix something the author can fix and is mostly given the how by the CI run logs.

2025-05-16 09:27 UTC, DavidSichau commented
I created a new pull request, where the CI is happy and the formatting is fixed: https://github.com/esphome/esphome/pull/8813

2025-05-29 02:29 UTC, jesserockz approved these changes

2025-05-29 02:30 UTC, jesserockz approved these changes

2025-05-29 05:10 UTC, merged