Add waveshare 2.9inch e-Paper HAT (D)
OttoWinter/esphomeyaml pull request #7906
Opened 2024-12-02 20:08 UTC by TataGEEK

# What does this implement/fix?

This pull request adds support for the Waveshare 2.9 inch e-Paper HAT (D) to the `waveshare_epaper` component.
Now it is also possible to use a flexible e-paper 2.9 inch https://www.waveshare.com/wiki/Pico-ePaper-2.9-D

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/feature-requests/issues/1013

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
I have no opportunity to test other development environments.

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

substitutions:
  gpio_display_cs: GPIO5
  gpio_display_dc: GPIO17
  gpio_display_busy: GPIO4
  gpio_display_reset: GPIO16
  set_time_refresh: "60s"  

time:
  - platform: homeassistant
    id: homeassistant_time

font:
  - file: "C:/fonts/arial.ttf"
    id: time_font
    size: 100

display:
  - platform: waveshare_epaper
    cs_pin: $gpio_display_cs
    dc_pin: $gpio_display_dc
    busy_pin: $gpio_display_busy
    reset_pin: $gpio_display_reset
    model: 2.90in-d
    update_interval: $set_time_refresh
    rotation: 270
    lambda: |-
      // Get the current time
      if (id(homeassistant_time).now().is_valid()) {
        auto now = id(homeassistant_time).now();

        // Format the time as HH:MM
        char time_str[6];
        snprintf(time_str, sizeof(time_str), "%02d:%02d", now.hour, now.minute);

        // Plot time centred
        it.print(it.get_width() / 2, it.get_height() / 2, id(time_font), TextAlign::CENTER, time_str);
      } else {
        // If the time is not valid, show error
        it.print(it.get_width() / 2, it.get_height() / 2, id(time_font), TextAlign::CENTER, "No time");
      }
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

**This is my first contribution to the ESPhome project. I appreciate any feedback and guidance to ensure the quality of this contribution meets the project's standards**

2025-02-07 19:12 UTC, TataGEEK commented
Hi there @clydebarrow,

I hope you're doing well. I wanted to give a friendly reminder regarding my pull request [#7906](https://github.com/esphome/esphome/pull/7906) which is currently awaiting your review. As this is my first contribution, I appreciate any feedback you can provide. If there are any improvements or changes needed, please let me know, and I will be happy to address them.

Thank you for your time and consideration!

2025-02-09 02:51 UTC, clydebarrow requested changes
You should a test configuration in `tests/components/waveshare_epaper`

2025-02-09 04:24 UTC, clydebarrow commented
The Waveshare tests are a mess; I just raised a PR to rationalise those, maybe wait till it's merged and then add the new model.

2025-02-11 00:35 UTC, clydebarrow approved these changes

2025-02-11 00:35 UTC, merged