[image] Transparency changes; code refactor
OttoWinter/esphomeyaml pull request #7908
Opened 2024-12-03 00:59 UTC by clydebarrow

# What does this implement/fix?

A previous PR changed the transparency type for some images from chroma-key (where a specific color flags transparency) to alpha-channel (where an additional 8 bits per pixel encodes the opacity value.)

Now there is a choice available for which type of transparency is used. Full list of changes:

0. `use_transparency` has options `none`, `chroma_key` and `alpha_channel`
1. Image type is a required field - the previous default was BINARY which is often not what is expected;
2. The RGBA and TRANSPARENT_BINARY types are removed, instead use RGB or BINARY with an appropriate setting for `use_transparency`
3. `online_image` and `animation` code and schemas are streamlined and re-use `image` code where possible.
4. The  `image` code has been extensively refactored to facilitate maintenance.
5. 
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/issues/issues/6498

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#TBD
## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx
- [x] host

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-12-17 21:15 UTC, guillempages commented on esphome/components/image/__init__.py
> +    type = value[CONF_TYPE]
Somehow the new validation lost the checks for MDI; was this on purpose?  In the old implementation, MDI images were set to transparent by default (because that's what the average user will expect), and only allowed binary types (transparent or not-transparent).

As far as I can see, now there is no distinction between mdi images or other images; so the user will manually have to specify the transparency, even if it does not make sense.

Also, mdi images are binary on the source, so it would be nice if the "mdi" type could still have the type set to binary by default, instead of having to explicitly add binary on each image.

2024-12-17 21:18 UTC, guillempages commented on esphome/components/image/__init__.py
> +        cv.Required(CONF_TYPE): validate_type,
As mentioned above; I think it would be better to keep this as optional, to allow mdi images to be configured with the least amount of parameters possible, and "require" the type for other images in the validation function

2024-12-17 21:19 UTC, guillempages commented on esphome/components/image/__init__.py
>      # Local imports only to allow "validate_pillow_installed" to run *before* importing it
Is `validate_pillow_installed` still called at all? The comment is probably wrong

2024-12-17 21:23 UTC, guillempages commented on esphome/components/image/__init__.py
> +            image = svg2png(
Just out of curiosity; why open it as png, and then decoding into the buffer again, instead of keeping the old implementation that directly created the image from the svg?

2024-12-17 21:27 UTC, guillempages commented on esphome/components/image/image.cpp
> +      if (this->get_binary_pixel_(x, y))
Any specific reason to not use the ternary operator here? It made the switch look more consistent (i.e. one return per case).

2024-12-17 21:28 UTC, clydebarrow commented on esphome/components/image/__init__.py
> +    type = value[CONF_TYPE]
MDI images (which are SVG) are not binary in source, they're vector drawings and `binary` for MDI (and any other image with transparency) results in aliasing artefacts so that's the reason for not providing a default. Grayscale works much better for MDI. Before LVGL was merged (and the display component couldn't render transparency properly) it was not an issue.

Basically it comes down to the fact that a default type is going to be not what is wanted more often than not, so by requiring the type to be specified, the user has to at least think about what the desired result is, and if it's not as expected, there is already a starting point to tweak.

Transparency by default would make sense for MDI - I'll ponder that.

2024-12-17 21:31 UTC, clydebarrow commented on esphome/components/image/__init__.py
> +        cv.Required(CONF_TYPE): validate_type,
As per comment above I disagree. If there were to be a default for MDI it should be grayscale, and since that would be a breaking change I think it's better to make the user be explicit.

2024-12-17 21:33 UTC, guillempages commented on esphome/components/image/image.h
> +  int get_bpp() const { return this->bpp_; }
Nice one! Makes the checking of bpp once at construction instead of on every pixel.

2024-12-17 21:36 UTC, clydebarrow commented on esphome/components/image/image.cpp
> +      if (this->get_binary_pixel_(x, y))
One of the linters didn't like it, not sure why but it was simpler just to rewrite it.

2024-12-17 21:41 UTC, clydebarrow commented on esphome/components/image/__init__.py
> +            image = svg2png(
The old implementation did exactly the same. All I did was inline the function.

2024-12-17 21:52 UTC, guillempages commented on esphome/components/image/image.h
> +  size_t get_width_stride() const { return (this->width_ * this->get_bpp() + 7u) / 8u; }
maybe this could also be calculated at the constructor, instead of each time the method is called? width_ should be constant (over the image lifetime), and bpp as well.

2024-12-17 21:52 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +            host=cv.Version(0, 0, 0),
Does this now work? IIRC it was not working because the http_request dependency didn't either; but this might have changed in the meantime

2024-12-17 21:52 UTC, guillempages commented on esphome/components/online_image/__init__.py
> +    if format == FORMAT_PNG:
Please, leave the "in [FORMAT_PNG]"; at some point I plan to add an "FORMAT_AUTO" as well, that should include all possible formats

2024-12-17 21:52 UTC, guillempages commented on esphome/components/online_image/image_decoder.h
> +  // Initializing to 1, to ensure it is different to initial "decoded_bytes_".
You are a native english speaker, so I won't insist much on that... But to me "different than" sounds better than "different to"... But it might be a British vs American vs Australian thing

2024-12-17 21:52 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +  ESP_LOGV(TAG, "Allocating new buffer of %d Bytes...", new_size);
I'd like to keep at least this one as "debug"; memory is still an issue for some users, and having a log explicitly mentioning how much memory is being allocated helps with debugging user issues.
```suggestion
  ESP_LOGD(TAG, "Allocating new buffer of %d Bytes...", new_size);
```

2024-12-17 21:52 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +    ESP_LOGE(TAG, "allocation of %d bytes failed", new_size);
Please, keep the old implementation with the actual checking of the available max block... There have been cases of complaints "I have xxx bytes free, but the allocation failed", and this helps debugging (or even avoiding the complain) that

2024-12-17 21:52 UTC, guillempages commented on esphome/components/online_image/png_image.h
> +#include "esphome/core/defines.h"
why move the include here? If kept in the "image_decoder.h", it will be automatically included on all different image formats (e.g. jpeg) when implemented; instead of needing to explicitly add it to each format.

2024-12-17 21:56 UTC, guillempages commented on esphome/components/image/__init__.py
> +    type = value[CONF_TYPE]
I like my yaml files clean and DRY. Having to add an extra parameter for each MDI file I use is cumbersome.
You are a heavy defender of "make everything explicit that can have a consequence", whereas I'm a heavy defender of "put sensible defaults wherever possible, and allow overriding them for corner cases".
Changing the default to grayscale I could live with... But then this might again not work for binary eink displays (or at least waste memory)

2024-12-17 21:57 UTC, guillempages commented on esphome/components/image/__init__.py
> +        cv.Required(CONF_TYPE): validate_type,
Making it explicit is also a breaking change

2024-12-17 21:58 UTC, guillempages commented on esphome/components/image/__init__.py
> +            image = svg2png(
Oops. My bad :-(

2024-12-17 22:01 UTC, guillempages commented on esphome/components/image/__init__.py
> -    # Local imports only to allow "validate_pillow_installed" to run *before* importing it
The mention of "local import of cairosvg" is still relevant IMHO. The esphome guideline is to use global imports, and this explicitly (and purposely) breaks this guideline IMHO a comment explaining why is needed, to avoid a future "let's clean this up" requiring cairosvg for everyone.

2024-12-17 22:11 UTC, clydebarrow commented on esphome/components/image/__init__.py
> +    type = value[CONF_TYPE]
I fully agree with sensible defaults where the only exceptions are indeed corner cases, I think since the expansion of the application of the image component it's not that clear-cut. This PR and the previous one are in response to real-world issues that have arisen due to unexpected results without obvious solutions. It's impossible to keep everybody happy so it's better IMO to at least keep everybody equally unhappy.

2024-12-17 22:12 UTC, clydebarrow commented on esphome/components/image/__init__.py
> +        cv.Required(CONF_TYPE): validate_type,
> Making it explicit is also a breaking change

Sure, and that's the best kind of breaking change - it's obvious at build time, and the solution is proposed for you.

2024-12-17 22:15 UTC, clydebarrow commented on esphome/components/online_image/__init__.py
> +            host=cv.Version(0, 0, 0),
It does work, I have a working http_request for host, not in PR yet. It was essential for testing.

2024-12-17 22:17 UTC, clydebarrow commented on esphome/components/online_image/image_decoder.h
> +  // Initializing to 1, to ensure it is different to initial "decoded_bytes_".
It just grated on me as I read it. I looked it up just now, and "different than" is an Americanism. The ROW uses "from" or "to".

2024-12-17 22:45 UTC, clydebarrow commented on esphome/components/image/__init__.py
> -    # Local imports only to allow "validate_pillow_installed" to run *before* importing it
cairosvg is installed by default now. I'll move the import to the top level.

2024-12-17 22:48 UTC, clydebarrow commented on esphome/components/online_image/online_image.cpp
> +    ESP_LOGE(TAG, "allocation of %d bytes failed", new_size);
Calculation of available heap should be abstracted out to the allocator, rather than having platform-dependent code here. That will need a separate PR to update the allocator code so I'll defer that for now.

2024-12-17 22:50 UTC, clydebarrow commented on esphome/components/online_image/png_image.h
> +#include "esphome/core/defines.h"
Simply because at moment there are no other formats so this is the only file where it's used. That can be updated when other formats are added.

2024-12-17 22:56 UTC, clydebarrow commented on esphome/components/image/image.h
> +  size_t get_width_stride() const { return (this->width_ * this->get_bpp() + 7u) / 8u; }
Can't `width_` change with online image?

2024-12-18 21:48 UTC, guillempages commented on esphome/components/image/image.h
> +  size_t get_width_stride() const { return (this->width_ * this->get_bpp() + 7u) / 8u; }
Oops, right. Forgot about the child classes :-(

2024-12-18 21:50 UTC, guillempages commented on esphome/components/online_image/image_decoder.h
> +  // Initializing to 1, to ensure it is different to initial "decoded_bytes_".
In that case, can we agree on "is different from"? Somehow I can't get "is different to" parsed right in my mind ;-)

2024-12-18 22:15 UTC, guillempages commented on esphome/components/online_image/online_image.cpp
> +  delay_microseconds_safe(2000);  // allow time for log line to appear
IIRC the delay was not for the log, but because I had some strange crashes without it... But it was over a year ago, so I forgot the actual issue.

2024-12-18 22:15 UTC, guillempages commented on tests/components/animation/common.yaml
> +animation:
Maybe also port the comment explicitly mentioning to *not* load `image` manually (to test the auto-load). Just to make sure

2024-12-18 22:15 UTC, guillempages commented on tests/components/image/common.yaml
> +    use_transparency: alpha_channel
```suggestion
    use_transparency: chroma_key
```
The combination "RGB" with "alpha_channel" is already being tested in the image just above this one

2024-12-19 00:25 UTC, clydebarrow commented on esphome/components/online_image/online_image.cpp
> +  delay_microseconds_safe(2000);  // allow time for log line to appear
So remove it?

2024-12-19 00:27 UTC, clydebarrow commented on tests/components/animation/common.yaml
> +animation:
Umm, why? Is a dev really going to look at that code and think "hmm, nothing is broken but I think I should add `image:` here".

2024-12-19 00:33 UTC, clydebarrow commented
@guillempages I have a plan to satisfy your DRY requirements while still avoiding unexpected results. Stand by...

2024-12-19 04:40 UTC, clydebarrow commented
@guillempages See here: https://deploy-preview-4506--esphome.netlify.app/components/image.html#grouping-images-by-type

2024-12-19 04:48 UTC, clydebarrow commented on esphome/components/online_image/image_decoder.h
> +  // Initializing to 1, to ensure it is different to initial "decoded_bytes_".
So now it reads
```
  // Initializing to 1, to ensure it is distinguishable from initial "decoded_bytes_".

```

2025-01-12 19:06 UTC, jesserockz requested changes

2025-01-12 19:06 UTC, jesserockz commented on requirements.txt
> -puremagic==1.27
Lets leave this in for now as there are external components that are using this library.

2025-01-12 19:06 UTC, jesserockz commented on esphome/components/online_image/png_image.h
> +#include "esphome/core/defines.h"
defines.h should always be included in any file it is needed. it is best not to rely on another file including it in case that is removed in the future.

2025-01-12 19:06 UTC, jesserockz commented on esphome/components/image/image.h
> +  bool has_transparency() const { return transparency_ != TRANSPARENCY_OPAQUE; }
```suggestion
  bool has_transparency() const { return this->transparency_ != TRANSPARENCY_OPAQUE; }
```

2025-01-13 03:13 UTC, jesserockz approved these changes

2025-01-13 03:21 UTC, merged