[adc] Use new library with ESP-IDF v5
OttoWinter/esphomeyaml pull request #7942
Opened 2024-12-09 23:23 UTC by edwardtfn

# What does this implement/fix?

This adds compatibility to ESP-IDF v5 to the ADC component, preventing the warning message related to the deprecated libraries.
This is a continuation of PR#7940 which was splitting the files per platform, so if this one is merged, that other pr becomes obsolete. Or #7940 could be merged first to make this one smaller. 😉 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes esphome/issues#6389
- possibly fixes esphome/issues#6455

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF (v4.4.8 and v5.1.5)
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`: N/A

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-12-10 01:33 UTC, jesserockz commented on esphome/components/adc/adc_sensor_esp32_v4.cpp
> -#include "esphome/core/log.h"
Please keep the log.h imports in the cpp files and not in the headers

2024-12-10 01:46 UTC, edwardtfn commented on esphome/components/adc/adc_sensor_esp32_v4.cpp
> -#include "esphome/core/log.h"
I will change this tomorrow

2024-12-10 10:15 UTC, edwardtfn commented on esphome/components/adc/adc_sensor_esp32_v4.cpp
> -#include "esphome/core/log.h"
Done!

2024-12-10 22:07 UTC, edwardtfn commented
I'm changing this to "draft" as the current implementation looks to fail with ESP32-C3 and ESP-IDF v5.3.1, where `adc_cali_create_scheme_curve_fitting` is used instead.
I will look at this tomorrow.

2024-12-11 14:26 UTC, edwardtfn commented
This is ready for test.
I wanna make some changes to the docs to cover the changes on this PR, but I will try to do this later today or tomorrow morning.
Anyways, I would appreciate if someone could test this PR specially with ESP32-C3, C6, S2 and S3 (and H2?) and provide feedback.

2024-12-12 00:21 UTC, edwardtfn commented
Compiling tests:
ESP32 Std v5.1.5: Passed
ESP32 Std v5.3.1: Passed
ESP32-C3 v5.1.5: Passed
ESP32-C3 v5.3.1: Passed
ESP32-C6 v5.1.5: Passed
ESP32-C6 v5.3.1: Passed
ESP32-S2 v5.1.5: Passed
ESP32-S2 v5.3.1: Passed
ESP32-S3 v5.1.5: Passed
ESP32-S3 v5.3.1: Passed

Running tests:
- NSPanel (ESP32 std)
    - v4.4.8: Passed (temperature measurement ok)
    - v5.1.5: Passed (temperature measurement ok)
    - v5.3.1: Passed (temperature measurement ok)
- Shelly Plus 1PM (ESP32 std?)
    - v4.4.8: Passed (temperature & tension measurements ok)
    - v5.1.5: **Failing on boot** - Looks to be in safe mode, as OTA still working
    - v5.3.1: **Failing on boot** - Looks to be in safe mode, as OTA still working

2024-12-12 10:56 UTC, edwardtfn commented
I found the issue with the tests with that Shelly Plus 1PM as that used two instances of ADC1. Now the code will handle that nicely.

**Compiling tests:**
ESP32 Std v5.1.5: Passed
ESP32 Std v5.3.1: Passed
ESP32-C3 v5.1.5: Passed
ESP32-C3 v5.3.1: Passed
ESP32-C6 v5.1.5: Passed
ESP32-C6 v5.3.1: Passed
ESP32-S2 v5.1.5: Passed
ESP32-S2 v5.3.1: Passed
ESP32-S3 v5.1.5: Passed
ESP32-S3 v5.3.1: Passed

**Running tests:**
- NSPanel:
    - v5.1.5: Passed (temperature measurement ok)
    - v5.3.1: Passed (temperature measurement ok)
- Shelly Plus 1PM
    - v5.1.5: Passed (temperature & tension measurements ok)
    - v5.3.1: Passed (temperature & tension measurements ok)


Additional real-life tests with the other variants (C3, C6, S2 & S3) will be very appreciated. 😉

2024-12-14 21:18 UTC, luar123 commented
Thanks for your work!
I tried this on H2 and compared to the old driver it compiles without errors.
I only tried a simple single channel sensor with:
```
sensor:
  - platform: adc
    pin: GPIO1
    name: "Bat"
    update_interval: 10s
```
and there is an issues that the pin is wrong, 2 instead of 1: `[D][esp-idf:000]: I (836) gpio: GPIO[2]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 `

Apart from that it gives values that are completely wrong, because the first hardware revision of H2 has no calibration data:
> [D][esp-idf:000]: W (837) eFuse: calibration efuse version does not match, set default version to 0
> [D][esp-idf:000]: E (838) adc_cali: adc_cali_create_scheme_curve_fitting(79): Calibration required eFuse bits not burnt
> [W][adc.esp32:127]: Curve fitting calibration failed with error 262, will use uncalibrated readings

I get ~0.7V instead of ~0.3V, is that expected in this case?

2024-12-14 23:31 UTC, edwardtfn commented
Could you please share more of your yaml, so I could try to duplicate it here (even not having a real H2 device, but at least I can try testing for the compiling issues).
Please remove any sensitive data before sharing it, like Wi-Fi credentials, etc.

2024-12-15 11:32 UTC, luar123 commented
No compiling issues with your PR (just old driver fails). Just wrong pin.
I think the issue is related to the channel. main.cpp:
```
  esp32_esp32internalgpiopin_id = new esp32::ESP32InternalGPIOPin();
  esp32_esp32internalgpiopin_id->set_pin(::GPIO_NUM_1);
  esp32_esp32internalgpiopin_id->set_inverted(false);
  esp32_esp32internalgpiopin_id->set_drive_strength(::GPIO_DRIVE_CAP_2);
  esp32_esp32internalgpiopin_id->set_flags(gpio::Flags::FLAG_INPUT);
  adc_adcsensor_id->set_pin(esp32_esp32internalgpiopin_id);
  adc_adcsensor_id->set_output_raw(false);
  adc_adcsensor_id->set_sample_count(1);
  adc_adcsensor_id->set_attenuation(adc::ADC_ATTEN_DB_12_COMPAT);
  adc_adcsensor_id->set_channel1(::ADC1_CHANNEL_1);
```
log:
`[D][esp-idf:000]: I (508) gpio: GPIO[2]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0`

For H2 channel 1 is at gpio 2: https://espressif-docs.readthedocs-hosted.com/projects/esp-dev-kits/en/latest/esp32h2/esp32-h2-devkitm-1/user_guide.html

Minimal example:
```
esphome:
  name: h2_adc_test

esp32:
  board: esp32-h2-devkitm-1
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

external_components:
  - source: github://pr#7942
    components: [ adc ]
    refresh: 1h

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: debug

sensor:
  - platform: adc
    pin: GPIO1
    attenuation: 12dB
    name: "Bat"
    update_interval: 10s
```

2024-12-15 11:56 UTC, luar123 commented
The mapping in init.py is wrong:
https://github.com/esphome/esphome/blob/5877c57a3572138de2873262a0204759a2704149/esphome/components/adc/__init__.py#L104
So it is not related to your PR. I could create a separate PR if you don't want to include it.

2024-12-15 15:54 UTC, edwardtfn commented
Yeah, I think this should be in another one.

2024-12-21 14:53 UTC, enzo2 commented
I tried out the PR using external_components as above, and the ADC reading changed substantially, by about -0.40V. It was fairly accurate before. This is with a generic esp32dev board, with ESP-IDF 5.3.1. I am using ADC0 / GPIO36.

2024-12-21 16:31 UTC, edwardtfn commented
Have you tried also with IDF v5.1.5? Can you see the same difference?
The calibration changed quite a lot in the new library, but I believe we can find some way to force using the legacy calibration. I just wanna find when the calibration changed so the question above to help narrowing down my investigation.

2024-12-21 17:23 UTC, enzo2 commented
> Have you tried also with IDF v5.1.5? Can you see the same difference? The calibration changed quite a lot in the new library, but I believe we can find some way to force using the legacy calibration. I just wanna find when the calibration changed so the question above to help narrowing down my investigation.

Which platform_version should I use? I was on 6.9.0 but it says not compatible with 5.1.5.

2024-12-21 18:13 UTC, edwardtfn commented
> Which platform_version should I use? I was on 6.9.0 but it says not compatible with 5.1.5.

If you don't specify any IDF version, you will be using v5.1.5 since ESPHome v2024.12.0, and v4.4.8 before that. 😉 
But you can force it with this:
```yaml
esp32:
  framework:
    type: esp-idf
    version: 5.1.5
    source: https://github.com/pioarduino/esp-idf/releases/download/v5.1.5/esp-idf-v5.1.5.zip
    platform_version: https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
```

2024-12-21 19:24 UTC, enzo2 commented
Ok, I tried it with the default 5.1.5, it is no different than with 5.3.1 (lower reading and less accurate).

2024-12-22 00:18 UTC, edwardtfn commented
Ok. I will look at that.
Thanks!

2024-12-28 16:47 UTC, nliaudat commented
Perhaps is that IDF Issue https://github.com/espressif/esp-idf/issues/10543 the cause of less accurate reading.
It could be usefull to add 
`ESP_LOGI(TAG, "ADC_BITWIDTH_DEFAULT=%d", ADC_BITWIDTH_DEFAULT);`
to check if always 0

Regards

2025-01-12 13:15 UTC, BenoitAnastay commented
Can you also fix this in file `components/i2s_audio/i2s_audio.cpp`

2025-02-20 17:19 UTC, nliaudat commented
any chance to have it merged in next release ?

2025-02-25 21:21 UTC, ximex commented
@edwardtfn what is needed to get this PR out of the draft status? i could test with ESP32-C6 if needed

2025-02-26 16:56 UTC, nliaudat commented
> @edwardtfn what is needed to get this PR out of the draft status? i could test with ESP32-C6 if needed

Working great for 2 months in https://github.com/nliaudat/floor-heating-controller (about 500 users with esp32 and esp32-C3 boards)

2025-02-28 06:57 UTC, edwardtfn commented
Sorry, I got totally overloaded at work and haven't had time to look at this. I will try to find some time during this weekend.

2025-03-15 13:40 UTC, edwardtfn commented
> I tried out the PR using external_components as above, and the ADC reading changed substantially, by about -0.40V. It was fairly accurate before. This is with a generic esp32dev board, with ESP-IDF 5.3.1. I am using ADC0 / GPIO36.

Hey @enzo2, could you please try it again?
I haven't made any change other than applying the other changes from `dev`, so I wanna double check if this wasn't already fixed by someone else before I put time on this.

Thanks a lot!

2025-03-15 17:31 UTC, enzo2 commented
> > I tried out the PR using external_components as above, and the ADC reading changed substantially, by about -0.40V. It was fairly accurate before. This is with a generic esp32dev board, with ESP-IDF 5.3.1. I am using ADC0 / GPIO36.
> 
> Hey @enzo2, could you please try it again? I haven't made any change other than applying the other changes from `dev`, so I wanna double check if this wasn't already fixed by someone else before I put time on this.
> 
> Thanks a lot!

Yes, it is still broken.

2025-05-08 11:27 UTC, edwardtfn commented
@enzo2, could you please explore some other attenuations and let me know if the issue in consistent with other settings?
```yaml
- platform: adc
  pin: GPIO36
  name: "ADC 0db"
  attenuation: 0db
- platform: adc
  pin: GPIO36
  name: "ADC 6db"
  attenuation: 6db
- platform: adc
  pin: GPIO36
  name: "ADC 12db"
  attenuation: 12db
  ```

2025-05-08 14:48 UTC, enzo2 commented
> @enzo2, could you please explore some other attenuations and let me know if the issue in consistent with other settings?
> 
> ```yaml
> - platform: adc
>   pin: GPIO36
>   name: "ADC 0db"
>   attenuation: 0db
> - platform: adc
>   pin: GPIO36
>   name: "ADC 6db"
>   attenuation: 6db
> - platform: adc
>   pin: GPIO36
>   name: "ADC 12db"
>   attenuation: 12db
> ```

Sorry, having trouble compiling right now on my ESPhome Builder.

2025-05-08 17:25 UTC, edwardtfn commented
I've started implementing an option for using legacy calibration, which will use the same calc as used for IDF v4.x. I will let you know when ready. 😉

2025-05-27 04:05 UTC, edwardtfn commented
@enzo2, may I ask you to try the other branch where I'm playing with this capability of selecting the legacy calibration?

Please add this:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: adv-new-library-espidf-5-with-legacy
    components:
      - adc
    refresh: 5min
```

Then in your sensor, add the `calibration_mode` with the options `legacy` (you will get some compiling warnings), `native` and `auto` and let me know which options give you correct values.

Something like this (please adjust for your scenario):
```yaml
sensor:
  - id: ntc_source
    platform: adc
    calibration_mode: legacy  # or `native` or `auto` or without this key entirely
    pin: 38
    attenuation: 12db
    samples: 4
    update_interval: 10s
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 1
```

2025-05-27 04:06 UTC, edwardtfn commented
Also, have you had a chance to explore the multiple attenuation options?

2025-05-27 16:22 UTC, enzo2 commented
Please format this comment to look nice using github's markup: 
OK, the test reveals that the problem only occurred with "auto" attenuation. 
(Test on a 5V bus) 
#### Using PR 7942:
| Attenuation | Result |
|-------------|--------|
| auto        | 2.97V  |
| 0dB         | 5.06V  |
| 6dB         | 5.03V  |
| 12dB        | 5.05V  |

#### Using adv-new-library-espidf-5-with-legacy:
| Mode     | Attenuation | Result |
|----------|-------------|--------|
| "legacy" | auto        | 5.04V  |
| "native" | auto        | *Don't know because the device went offline, maybe it caused a boot loop? * |

2025-05-27 17:24 UTC, nliaudat commented
perhaps linked to https://github.com/esphome/esphome/pull/7942#issuecomment-2564378108

2025-05-27 22:10 UTC, edwardtfn commented
> OK, the test reveals that the problem only occurred with "auto" attenuation. (Test on a 5V bus)
> 
> #### Using PR 7942:
> Attenuation	Result
> auto	2.97V
> 0dB	5.06V
> 6dB	5.03V
> 12dB	5.05V
> #### Using adv-new-library-espidf-5-with-legacy:
> Mode	Attenuation	Result
> "legacy"	auto	5.04V
> "native"	auto	2.97 V

Nice finding!!

I've just applied a fix to `adv-new-library-espidf-5-with-legacy`. Could you please try it again and let me know the results?

2025-05-27 22:28 UTC, enzo2 commented
> 
> Nice finding!!
> 
> I've just applied a fix to `adv-new-library-espidf-5-with-legacy`. Could you please try it again and let me know the results?

Looks good. `adv-new-library-espidf-5-with-legacy` with `attenuation: auto, calibration_mode: native` now gives correct value.

2025-05-28 19:00 UTC, edwardtfn commented
I've removed that support to legacy calibration as that is not needed anymore.
The code was merged to this PR and the other branch was deleted.

Could you please try it again?

2025-05-28 19:19 UTC, enzo2 commented
> I've removed that support to legacy calibration as that is not needed anymore. The code was merged to this PR and the other branch was deleted.
> 
> Could you please try it again?

Yes, this PR is working now with 'auto'.

2025-05-28 22:25 UTC, jesserockz requested changes

2025-05-28 22:25 UTC, jesserockz commented on esphome/components/adc/adc_sensor.h
> +// Map old channel names to new ones for compatibility, if needed
I dont think we need to keep these for idf5+ as we shouldnt keep using them internally

2025-05-28 22:25 UTC, jesserockz commented on esphome/components/adc/adc_sensor_esp32_v5.cpp
> +  }
setup is only called once, we shouldnt need this

2025-05-28 22:25 UTC, jesserockz commented on esphome/components/adc/adc_sensor_esp32_v5.cpp
> +        this->adc1_handle_ = shared_adc1_handle;
Maybe prefix these so we know they are static without guessing when looking at the code?
```suggestion
        this->adc1_handle_ = ADCSensor::shared_adc1_handle;
```

2025-05-28 22:25 UTC, jesserockz commented on esphome/components/adc/adc_sensor_esp32_v5.cpp
> +    if (this->adc1_handle_ == nullptr) {
this should always be nullptr during setup

2025-05-28 22:25 UTC, jesserockz commented on esphome/components/adc/adc_sensor_esp32_v5.cpp
> +      }
```suggestion
      if (ADCSensor::shared_adc1_handle == nullptr) {
        adc_oneshot_unit_init_cfg_t init_config1 = {};  // Zero initialize
        init_config1.unit_id = ADC_UNIT_1;
        init_config1.ulp_mode = ADC_ULP_MODE_DISABLE;
#if USE_ESP32_VARIANT_ESP32C3 || USE_ESP32_VARIANT_ESP32C6 || USE_ESP32_VARIANT_ESP32H2
        init_config1.clk_src = ADC_DIGI_CLK_SRC_DEFAULT;
#endif  // USE_ESP32_VARIANT_ESP32C3 || USE_ESP32_VARIANT_ESP32C6 || USE_ESP32_VARIANT_ESP32H2
        esp_err_t err = adc_oneshot_new_unit(&init_config1, &ADCSensor::shared_adc1_handle);
        if (err != ESP_OK) {
          ESP_LOGE(TAG, "Error initializing ADC1 unit: %d", err);
          this->handle_init_complete_ = false;
          this->mark_failed();
          return;
        }
      }
      this->adc1_handle_ = ADCSensor::shared_adc1_handle;
      this->handle_init_complete_ = true;
```

2025-05-29 08:09 UTC, edwardtfn commented on esphome/components/adc/adc_sensor_esp32_v5.cpp
> +    if (this->adc1_handle_ == nullptr) {
https://github.com/edwardtfn/esphome/commit/53ae9a8cf3ce516696100ca42bfb82dd503e0ef6

2025-05-29 08:20 UTC, edwardtfn commented on esphome/components/adc/adc_sensor_esp32_v5.cpp
> +      }
https://github.com/edwardtfn/esphome/commit/e5c30d5e71e287199010fd07b5ba0fe2b5ef7ce8

2025-05-29 08:25 UTC, edwardtfn commented on esphome/components/adc/adc_sensor_esp32_v5.cpp
> +  }
https://github.com/edwardtfn/esphome/commit/3f23760be420188e4559af6096e4abd4563e3980

2025-05-29 08:56 UTC, edwardtfn commented on esphome/components/adc/adc_sensor.h
> +// Map old channel names to new ones for compatibility, if needed
Done!

2025-05-29 09:34 UTC, edwardtfn commented on esphome/components/adc/adc_sensor.h
> +// Map old channel names to new ones for compatibility, if needed
I've reverted back the changes related to this as it broke the tests. I will look at this with more time later.

2025-05-30 08:05 UTC, edwardtfn commented on esphome/components/adc/adc_sensor.h
> +// Map old channel names to new ones for compatibility, if needed
So, looking deeper on this now, I realized changing this will require changes on the mapping on `__init__.py`, which would require a different track based on the framework version, etc, which would add complexity to the code, so I would prefer to leave as it is for now.

2025-06-07 22:38 UTC, edwardtfn commented
As this PR got things from everywhere in the last merge from `dev`, instead of trying to fix it I'm closing this PR and have created a new one with exactly the same changes:
- #9021

2025-06-07 22:38 UTC, closed without merging