[nextion] Adds a command pacer with `command_spacing` attribute
OttoWinter/esphomeyaml pull request #7948
Opened 2024-12-10 16:08 UTC by edwardtfn

# What does this implement/fix?

This introduces a "pacer" for the communication with the Nextion display, with the main objective to reduce the chances of a buffer overflow on Nextion side.
The buffer overflow can be quite critical, as it removes it's queue, while the component on ESPHome keeps waiting for responses for those removed commands, so a way to control the communication pace and give to users a chance to reduce the chances of a buffer overflow by compromising (a bit?) the performance which many times wouldn't be perceived by end users.
As default I'm setting the pace to 0ms, to keep this transparent to existing installation, although I would highly recommend the use of at least 10ms. Anyhow, users can increase this dynamically, if a buffer overflow happens.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
display:
  - id: disp1
    platform: nextion
    command_spacing: 25ms
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2025-05-01 12:14 UTC, jesserockz requested changes

2025-05-01 12:14 UTC, jesserockz commented on esphome/components/nextion/display.py
> +            cv.Optional(CONF_COMMAND_SPACING): cv.uint8_t,  # in milliseconds
```suggestion
            cv.Optional(CONF_COMMAND_SPACING): cv.All(
                cv.positive_time_period_milliseconds,
                cv.Range(max=TimePeriod(milliseconds=255),
            ),
```

2025-05-01 12:14 UTC, jesserockz commented on esphome/components/nextion/nextion.h
> +  void set_command_spacing(uint32_t spacing_ms) { command_pacer_.set_spacing(spacing_ms); }
```suggestion
  void set_command_spacing(uint32_t spacing_ms) { this->command_pacer_.set_spacing(spacing_ms); }
```

2025-05-01 12:14 UTC, jesserockz commented on tests/components/nextion/common.yaml
> +    command_spacing: 5
```suggestion
    command_spacing: 5ms
```

2025-05-01 12:14 UTC, jesserockz commented on esphome/components/nextion/display.py
> +        cg.add(var.set_command_spacing(config[CONF_COMMAND_SPACING]))
```suggestion
    if command_spacing := config.get(CONF_COMMAND_SPACING):
        cg.add_define("USE_NEXTION_COMMAND_SPACING")
        cg.add(var.set_command_spacing(command_spacing.total_milliseconds))
```

2025-05-01 13:16 UTC, edwardtfn commented
I will run some additional tests tomorrow with the latest changes and let you know if something critical is found.

2025-05-05 08:07 UTC, jesserockz approved these changes

2025-05-05 08:08 UTC, merged