actions: fix loop re-entry
OttoWinter/esphomeyaml pull request #7972
Opened 2024-12-17 09:52 UTC by afflux

# What does this implement/fix?

The actions are instantiated once per definition but they store the trigger arguments in their class member ([example](https://github.com/esphome/esphome/blob/444e162c92c3148a14493f66d3de256679a6eedf/esphome/core/base_automation.h#L356)), which gets overridden, causing corruption when they are called multiple times.

Note that I'm removing the stored arguments in the `while` and `repeat` actions because they still have the action arguments available in the call stack and there is no code path in the code base that can do any changes to them.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/issues/issues/6534

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- N/A

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: test-2040

rp2040:
  board: rpipicow

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.1.91
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

logger:
  level: ERROR

ota:
  - platform: esphome
    password: !secret ota_password

api:
  reboot_timeout: 0s

globals:
   - id: global_counter
     type: size_t

script:
  - id: handle_response
    mode: parallel
    parameters:
      body: string
    then:
      - lambda: |-
          const char *const TAG = "TEST";

          json::parse_json(body, [TAG](JsonObject root) -> bool {

            JsonObject args = root["args"];
            if (!args) {
              ESP_LOGE(TAG, "no args");
              return false;
            }

            const char *arg = args["x"];
            ESP_LOGE(TAG, "got response for request #%s", arg);
            return true;
          });

      - wait_until:
          condition:
            lambda: return (id(global_counter) % 5) == 0;

      - lambda: |-
          const char *const TAG = "TEST_AFTER_WAIT";

          json::parse_json(body, [TAG](JsonObject root) -> bool {

            JsonObject args = root["args"];
            if (!args) {
              ESP_LOGE(TAG, "no args");
              return false;
            }
            const char *arg = args["x"];
            ESP_LOGE(TAG, "got response for request #%s", arg);
            return true;
          });

time:
  - platform: sntp
    id: sntp_time
    timezone: Etc/UTC
    servers:
      - 192.168.1.1

    on_time:
      - seconds: /10
        then:
          - http_request.get:
              url: !lambda |-

                return "https://httpbin.org/anything?x=" + std::to_string(id(global_counter)++);
              capture_response: true
              max_response_buffer_size: 4kB
              on_response:
                then:
                  - lambda: id(handle_response)->execute(body);

http_request:
  verify_ssl: false

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2025-09-29 11:33 UTC, afflux commented
still relevant

2025-10-29 05:28 UTC, bdraco commented on esphome/components/script/script.h
> +  std::queue<std::function<void()>> play_queue_;
std::queue is backed by a std::deque which allocates 512 byte chunks.  With many script this could run an esp8266 out of RAM quickly.

2025-10-29 12:42 UTC, afflux commented on esphome/components/script/script.h
> +  std::queue<std::function<void()>> play_queue_;
what's your suggested alternative? std::list?

2025-10-29 14:25 UTC, bdraco commented on esphome/components/script/script.h
> +  std::queue<std::function<void()>> play_queue_;
`std::list` probably makes the most sense.

  | Approach              | Empty (never used) | Empty (after 1st use) | 1 element | 3 elements | Max capacity   |
  |-----------------------|--------------------|-----------------------|-----------|------------|----------------|
  | std::queue<T> (deque) | 24-512 bytes*      | 512 bytes ❌           | 512 bytes | 512 bytes  | ~512 per chunk |
  | StaticVector<T, 8>    | 260 bytes          | 260 bytes             | 260 bytes | 260 bytes  | 8 (fixed)      |
  | FixedVector<T>        | 12 bytes†          | 260 bytes‡            | 260 bytes | 260 bytes  | Set at init()  |
  | Ring buffer (lazy)    | 20 bytes           | 260 bytes‡            | 260 bytes | 260 bytes  | Set at init()  |
  | std::list<T> ✅        | 14 bytes           | 14 bytes              | 54 bytes  | 134 bytes  | Unbounded      |

Note that my table might not be perfectly accurate

2025-10-29 14:33 UTC, bdraco commented on esphome/components/script/script.h
> +  std::queue<std::function<void()>> play_queue_;
std::queue only starts to look good at large numbers..

2025-10-29 14:35 UTC, bdraco commented on esphome/components/script/script.h
> +  std::queue<std::function<void()>> play_queue_;
Also need to handle the unbounded grow. It needs a reasonable limit

2025-10-29 14:55 UTC, bdraco requested changes
Thanks for the fix. The core approach looks correct once the memory issue is addressed.  Limit the fix to scripts that can run in parallel so we don't pay the memory cost unless its parrallel.

This PR changes `WhileAction`, `RepeatAction`, `WaitUntilAction`, and `ScriptWaitAction`. These are used heavily across all ESPHome configs. We need integration tests before merge.

Suggest splitting into two PRs:

**First PR:** Add `tests/integration/test_action_concurrent_reentry.py`
- Reproduce the parameter corruption from issue [#6534](https://github.com/esphome/issues/issues/6534)
- Parallel script with parameters
- wait_until that suspends execution
- Multiple concurrent invocations
- Assert each gets correct parameters
- Mark `@pytest.mark.xfail(reason="https://github.com/esphome/issues/issues/6534")`

**Second PR:** Apply this fix, remove the xfail marker, verify test passes.

This gives us regression coverage and proves the fix works.

2025-11-01 12:46 UTC, afflux commented
> Limit the fix to scripts that can run in parallel so we don't pay the memory cost unless its parrallel.

On the `Action` level, I don't see a simple way to determine if the script or automation can run in parallel or not. I expect this to require a major refactoring, which I am not comfortable doing. In theory, the std::forward_list based approach should be cheap enough - let me know what you get from re-running the numbers.

> Also need to handle the unbounded grow. It needs a reasonable limit

Not sure how to handle this gracefully. My best idea is to check `Automation::num_running()` during trigger execution and reject new triggers when above a hardcoded maximum, but that is potentially a long walk through the ActionList for every trigger, and it's not clear to me, what a reasonable maximum would be.

> We need integration tests before merge.

done, see #11652

2025-11-02 18:55 UTC, bdraco commented
> > Also need to handle the unbounded grow. It needs a reasonable limit
> 
> Not sure how to handle this gracefully. My best idea is to check `Automation::num_running()` during trigger execution and reject new triggers when above a hardcoded maximum, but that is potentially a long walk through the ActionList for every trigger, and it's not clear to me, what a reasonable maximum would be.

I think we can punt on this for now as its also a problem for number of executions. I recently fixed this in #11308 for queued but didn't have the time to do parallel as well.

2025-11-02 18:55 UTC, bdraco commented
> > We need integration tests before merge.
> 
> done, see #11652

Thanks!

2025-11-02 18:56 UTC, bdraco commented
> > Limit the fix to scripts that can run in parallel so we don't pay the memory cost unless its parrallel.
> 
> On the `Action` level, I don't see a simple way to determine if the script or automation can run in parallel or not. I expect this to require a major refactoring, which I am not comfortable doing. In theory, the std::forward_list based approach should be cheap enough - let me know what you get from re-running the numbers.

We are going to need to come up with a way to split it. I'll think about that.  Maybe thats template classes with c++20 concepts or separate classes. It should be possible to figure out at Python codegen time separate classes, or with c++20 concepts at compile time if we can't figure it out at codegen time.

Downside to separate classes is 2x the bug fix surface. Templates are probably the best option

2025-11-02 19:52 UTC, bdraco commented
Separate classes might be the way to go. I started using templates and concepts to have the same `WaitUntilAction` and it became way too complex

2025-11-02 20:07 UTC, afflux reviewed
What if the `script.wait_until` action is used in an automation trigger? Wouldn't this also be a potentially parallel context?

Edit: sorry, new GitHub UI is confusing me - this comment was supposed to go here:
https://github.com/esphome/esphome/pull/7972/files#diff-8fb488fbb00c19400b4b7888a5ffb32f83349ce9607e982f05717db5317605b7R54-R57

2025-11-02 20:07 UTC, afflux commented on esphome/components/script/script.h
> +  std::queue<std::function<void()>> play_queue_;
How did you generate these numbers? How does std::forward_list compare? From its implementation, I see no reason for it to have a bigger cost than storing the default-initialized std::tuple before the change.

2025-11-02 20:21 UTC, bdraco commented
> What if the `script.wait_until` action is used in an automation trigger? Wouldn't this also be a potentially parallel context?

Than we have a correctness problem which is a good argument to always use the parallel versions.

2025-11-02 20:27 UTC, bdraco commented on esphome/components/script/script.h
> +  std::queue<std::function<void()>> play_queue_;
I'll check `std::forward_list`. They are a pain to benchmark because I have to write custom services, compile, upload to the device and than run

2025-11-02 20:29 UTC, bdraco commented on esphome/components/script/script.h
> +  std::queue<std::function<void()>> play_queue_;
Just thinking about it, should use 50% of the overhead of `std::list` so probably not worth benchmarking as its clearly the better choice

2025-11-02 20:38 UTC, bdraco commented
> > What if the `script.wait_until` action is used in an automation trigger? Wouldn't this also be a potentially parallel context?
> 
> Than we have a correctness problem which is a good argument to always use the parallel versions.

Now we need tests for concurrent execution of wait_until and script.wait actions

2025-11-02 21:07 UTC, bdraco commented
I think this is good to go. Let's see if the bot can find anything we missed

2025-11-02 21:13 UTC, bdraco commented on esphome/core/base_automation.h
> +      if (this->num_running_ > 0 && this->condition_->check(x...)) {
4486bdf77d1e971ed356d459ee83958b522535fa

2025-11-02 21:15 UTC, bdraco commented on esphome/components/script/script.h
> +    this->disable_loop();
I don't think its correct. It should work either way. The question is if we want to process them all in one loop iteration or we should do one per loop to avoid blocking the loop for too long

2025-11-02 21:18 UTC, bdraco commented on esphome/components/script/script.h
> +    this->disable_loop();
The only way we would care is if someone misconfigures this and we end up with a giant queue.

2025-11-02 21:19 UTC, bdraco commented on esphome/components/script/script.h
> +    this->disable_loop();
I think we exhaust the memory on the device before this is a problem

2025-11-02 21:19 UTC, bdraco commented on esphome/components/script/script.h
> +    this->disable_loop();
Yeah we are going to OOM before this is a problem

2025-11-02 21:20 UTC, bdraco commented on esphome/core/base_automation.h
> +    });
Same feedback as https://github.com/esphome/esphome/pull/7972/#discussion_r2485023962

2025-11-02 21:27 UTC, afflux commented on esphome/components/script/script.h
> +    this->disable_loop();
It's not even correct:

1. num_running_ is incremented in play_complex(), not decremented
2. It will be decremented in play_next(), which is called exactly as many times, as play_complex() was called

2025-11-02 21:33 UTC, bdraco approved these changes
Thanks @afflux 

Good to go on my end if I didn't break anything with the refactoring

2025-11-02 23:02 UTC, merged

2025-11-03 05:25 UTC, afflux commented
Thank you @bdraco!