Adding timing budget support for vl53l0x
OttoWinter/esphomeyaml pull request #7991
Opened 2024-12-21 02:10 UTC by lastradanet

# What does this implement/fix?

Adding the ability to configure the timing budget used by the vl53l0x sensor. The larger the timing budget, the more accurate the reading.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: vl53l0x
    name: "VL53L0x Distance"
    address: 0x29
    update_interval: 1min
    long_range: false
    unit_of_measurement: "m"
    accuracy_decimals: 3
    timing_budget: 200000

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2025-02-11 20:56 UTC, jesserockz requested changes

2025-02-11 20:56 UTC, jesserockz commented on esphome/components/vl53l0x/sensor.py
> +        raise cv.Invalid("Timing budget must be between 17000us and 4294967295us")
We have a `cv.Range` validator for this

2025-02-11 20:56 UTC, jesserockz commented on esphome/components/vl53l0x/vl53l0x_sensor.h
> +  void set_timing_budget(uint32_t timing_budget) { timing_budget_ = timing_budget; }
> All uses of class members and member functions should be prefixed with `this->` to distinguish them from global functions/variables.

https://esphome.io/guides/contributing#codebase-standards

```suggestion
  void set_timing_budget(uint32_t timing_budget) { this->timing_budget_ = timing_budget; }
```

2025-02-11 20:56 UTC, jesserockz commented on esphome/components/vl53l0x/vl53l0x_sensor.cpp
> +  }
I don't think we need a new variable for this, just set the `measurement_timing_budget_us_` from the setter and here just check if it is not 0

2025-02-27 02:57 UTC, lastradanet commented on esphome/components/vl53l0x/sensor.py
> +        raise cv.Invalid("Timing budget must be between 17000us and 4294967295us")
Updated.

2025-03-03 08:15 UTC, tispokes commented
@lastradanet can you please fix the last issue, that this will be live :-)

PS: Maybe update the codebase to match the latest version from @pololu

2025-03-05 04:41 UTC, lastradanet commented
@tispokes , sorry for the delay. I'm testing the changes and should have something shortly.

2025-03-06 03:53 UTC, lastradanet commented
@tispokes , changes are in. With respect to the code base upgrade, I will review and update via a subsequent PR. I don't want to hold up this PR for that.

2025-05-01 02:16 UTC, jesserockz requested changes

2025-05-01 02:16 UTC, jesserockz commented on esphome/components/vl53l0x/sensor.py
> +from esphome import pins, core
```suggestion
from esphome import pins
```

2025-05-01 02:16 UTC, jesserockz commented on esphome/components/vl53l0x/sensor.py
> +                    max=core.TimePeriod(microseconds=4294967295),
```suggestion
                    min=cv.TimePeriod(microseconds=20000),
                    max=cv.TimePeriod(microseconds=4294967295),
```

2025-05-01 02:16 UTC, jesserockz commented on esphome/components/vl53l0x/sensor.py
> +        cg.add(var.set_timing_budget(config[CONF_TIMING_BUDGET]))
```suggestion
    if timing_budget := config.get(CONF_TIMING_BUDGET):
        cg.add(var.set_timing_budget(timing_budget))
```

2025-05-01 02:16 UTC, jesserockz commented on esphome/components/vl53l0x/vl53l0x_sensor.cpp
> +    measurement_timing_budget_us_ = get_measurement_timing_budget_();
```suggestion
  if (this->measurement_timing_budget_us_ == 0) {
    this->measurement_timing_budget_us_ = this->get_measurement_timing_budget_();
```

2025-05-01 02:16 UTC, jesserockz commented on esphome/components/vl53l0x/vl53l0x_sensor.cpp
> +  ESP_LOGCONFIG(TAG, "  Timing Budget %u%s ", this->measurement_timing_budget_us_, "us");
```suggestion
  ESP_LOGCONFIG(TAG, "  Timing Budget %uus ", this->measurement_timing_budget_us_);
```

2025-05-01 02:24 UTC, jesserockz approved these changes

2025-05-01 03:17 UTC, merged