[psram] Improve total PSRAM display in logs by using rounded KB values
OttoWinter/esphomeyaml pull request #8008
Opened 2024-12-24 18:46 UTC by edwardtfn

# What does this implement/fix?

When displaying the total PSRAM size at the `dump_config`, round to the nearest KB value if within 0.05KB threshold. Otherwise show in bytes. This makes the logs clearer and more precise.

In a real case example, where `heap_caps_get_total_size(MALLOC_CAP_SPIRAM)` returns 2097151 bytes:

- Before: `Size: 2047 KB` (off by 1023 bytes)
- After: `Size: 2048 KB` (off by 1 byte)

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`: N/A

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-12-25 16:24 UTC, DjordjeMandic approved these changes

2024-12-25 16:31 UTC, DjordjeMandic commented
Technically, "KB" refers to 1000 bytes (base 10) in the SI system, while 1024 bytes is correctly termed "KiB" (base 2). For clarity, especially in user-facing outputs, it might be better to use "KiB" if precision matters. That said, what standard is actually followed for binary prefixes in embedded systems—IEC or JEDEC? It’s worth considering since JEDEC often sticks with "KB" for 1024 bytes, which might explain the choice here.

2024-12-25 17:38 UTC, edwardtfn commented
Well, you have a point...
I just kept the same units as it was before... My intention here was to improve the number itself, so I haven't thought about the units that much.
For consistency, I think it should be similar to how units are shown elsewhere in ESPHome (including documents) and, from memory, I can remember `flash_size` also using `MB` as unit, probably with a power of two meaning...
With that said, my suggestion woukd be to keep this PR as it is and possibly create another PR to review units, which should cover other components if needed.

2024-12-25 21:42 UTC, DjordjeMandic commented
Your PR looks fine to me, I just mentioned that because I'm confused too.

2024-12-25 21:45 UTC, DjordjeMandic requested changes

2024-12-25 21:45 UTC, DjordjeMandic commented on esphome/components/psram/psram.cpp
> +      ESP_LOGCONFIG(TAG, "  Size: %.0f bytes", (float) psram_total_size_bytes);
```suggestion
      ESP_LOGCONFIG(TAG, "  Size: %zu bytes", psram_total_size_bytes);
```

Because `psram_total_size_bytes` is `size_t`. Should be faster.

2024-12-26 00:00 UTC, DjordjeMandic approved these changes

2025-01-13 04:11 UTC, jesserockz approved these changes

2025-01-13 04:11 UTC, merged