Add: Dlms smartmeter component
OttoWinter/esphomeyaml pull request #8009
Opened 2024-12-24 23:39 UTC by SimonFischer04

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>
WIP

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
uart:
  rx_pin: GPIO4 # change this to the pin where you connected the mbus adapter board
  baud_rate: 2400
  rx_buffer_size: 1024 # Needed to receive the large packets send by the smart meter

dlms_meter:
  decryption_key: "36C66639E48A8CA4D6BC8B282A793BBB" # change this to your decryption key!
  provider: netznoe # (optional) key - only set if using evn

sensor:
  - platform: dlms_meter
    voltage_l1:
      name: "Voltage L1"
    voltage_l2:
      name: "Voltage L2"
    voltage_l3:
      name: "Voltage L3"
    current_l1:
      name: "Current L1"
    current_l2:
      name: "Current L2"
    current_l3:
      name: "Current L3"
    active_power_plus:
      name: "Active power taken from grid"
    active_power_minus:
      name: "Active power put into grid"
    active_energy_plus:
      name: "Active energy taken from grid"
    active_energy_minus:
      name: "Active energy put into grid"
    # EVN
    power_factor:
      name: "Power Factor"

text_sensor:
  - platform: dlms_meter
    timestamp:
      name: "timestamp"
    # EVN
    meternumber:
      name: "meterNumber"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-12-25 16:28 UTC, ximex commented
@SimonFischer04 if you want i could also do a test with a ESP32-C6 in january

2024-12-25 16:55 UTC, SimonFischer04 commented
> @SimonFischer04 if you want i could also do a test with a ESP32-C6 in january

@ximex thanks for the offer, would be nice 👍

Although:
If we still use arduino framework it should not change anything.
But with newer esp chips it's usually recommended to use idf. I did not yet did into idf- programming, but I think some changes would be required to get this working with idf. 
That's why I did not check idf support above. 

Let's start with this and later idf support can be added if desired, so this initial pr is smaller and easier to reviewer.

2025-01-21 01:21 UTC, ximex commented
Ok than i have to wait for IDF support as i didn't get the ESP32-C6 running with arduino framework
What changes would be necessary for IDF support?
For C6 i saw at least this checks `#if defined(ESP32)`
At least i could confirm that UART with IDF is working on ESP32-C6. Have this running: https://esphome.io/components/sensor/pmsx003

2025-02-02 15:37 UTC, SimonFischer04 commented
> For C6 i saw at least this checks `#if defined(ESP32)`

Just a check, should be the least problem with IDF support.
As said, I haven't worked with idf yet, so not really sure. At least "native idf" seems to be quite different. Don't know how much platformio (used by esphome) already abstracts here.
Also want to keep this initial PR as small as possible, already quite a lot like this to review.

Also, this could be a stepstone in the meantime: https://github.com/esphome/esphome/pull/6894

2025-02-07 22:21 UTC, CodeMystic21 commented
Any progress on this pr? @jesserockz or someone might wanna take a look and review?

2025-02-20 10:20 UTC, ximex commented
@SimonFischer04 maybe change the pin?
see: https://github.com/SimonFischer04/esphome/issues/1#issuecomment-2671008121

2025-02-20 11:53 UTC, SimonFischer04 commented
> @SimonFischer04 maybe change the pin?
> see: https://github.com/SimonFischer04/esphome/issues/1#issuecomment-2671008121
> 
> maybe this would also an improvement: https://github.com/DomiStyle/esphome-dlms-meter/issues/46

Thanks, will do later so I can also change it in the docs-pr.

2025-02-20 12:58 UTC, pos-ei-don commented
This fixes https://github.com/DomiStyle/esphome-dlms-meter/issues/47 .
Thank you!

2025-02-20 16:09 UTC, cococheaf commented
As mentioned in https://github.com/DomiStyle/esphome-dlms-meter/issues/47 this also fixed it for me.

2025-02-21 09:07 UTC, RocketSience commented
Fix for https://github.com/DomiStyle/esphome-dlms-meter/issues/47 also working for me.

2025-02-21 09:14 UTC, SimonFischer04 commented
Just give a 👍 to the first post if it works for you. Keeps the thread here cleaner.

2025-02-21 09:23 UTC, pos-ei-don approved these changes
This fixes https://github.com/DomiStyle/esphome-dlms-meter/issues/47. Tested.

2025-02-21 11:47 UTC, ximex requested changes

2025-02-21 11:47 UTC, ximex commented on tests/components/dlms_meter/common.yaml
> +  rx_pin: GPIO4          # change this to the pin where you connected the mbus adapter board
Use the correct RX pin from ESP32 and give a hint that the user had to check what is the correct pin
See: https://github.com/SimonFischer04/esphome/issues/1#issuecomment-2671008121

2025-02-22 14:33 UTC, ximex requested changes
Added some suggestions for M-Bus improvements

2025-02-22 14:33 UTC, ximex commented on esphome/components/dlms_meter/mbus.h
> +static const int MBUS_HEADER_INTRO_LENGTH = 4;  // Header length for the intro (0x68, length, length, 0x68)
define start bytes for different telegram formats as constants:
- Single Character: `0xE5` (length=1)
- Short Frame: `0x10` (length=5)
- Control Frame: `0x68` (length=9)
- Long Frame: `0x68` (length=9+data_length)

Here we are using only the **Long Frame**.

Also define the stop bit `0x16`

2025-02-22 14:33 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (this->receive_buffer_[frame_offset + MBUS_START1_OFFSET] != 0x68 ||
use constant mentioned in `mbus.h`

maybe first filter out only by telegram format and then in an additional check by comparing the 2nd start byte only if `0x86`
Then it's possible to also log with telegram format is received

2025-02-22 14:33 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +          0x16) {
use constant as mentioned in `mbus.h`

2025-02-22 14:33 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        ESP_LOGE(TAG, "MBUS: Frame too big for received data");
what does this mean? do the user have to increase the `rx_buffer_size`?

2025-02-23 00:10 UTC, SimonFischer04 commented on tests/components/dlms_meter/common.yaml
> +  rx_pin: GPIO4          # change this to the pin where you connected the mbus adapter board
This is a test file for ci. Nothing the user will ever see. So I don't think I hint does bring any value here. Also the pin does therefore not matter.

2025-02-23 00:21 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        ESP_LOGE(TAG, "MBUS: Frame too big for received data");
For the user: nothing really.

A lot of these conditions are just sanity checks for the received data. It's to check if the `length` field inside the frame claiming that the frame has a specific length, actually matches the expected amount of bytes received for the frame.

If something is not right with these checks should log errors and fail instead of further continuing data processing and then returning wrong data.
-> Useful for bug-reports (or support of new meters) to more easily find out what went wrong.

2025-02-23 00:29 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (this->receive_buffer_[frame_offset + MBUS_START1_OFFSET] != 0x68 ||
Will fix, thanks.

What do you mean with filter out by telegram format?

2025-02-23 00:30 UTC, SimonFischer04 commented
@ximex thanks for the review. Added some comments. Rest I will look at later.

2025-02-23 22:23 UTC, ximex requested changes
Would it make sense to extract the parts (M-Bus, DLMS, Decryption, Decoding) in the loop function into separate functions and move them into `mbus.cpp`, `dlms.cpp`, `decryption.cpp` `obis.cpp`?

2025-02-23 22:23 UTC, ximex commented on tests/components/dlms_meter/common.yaml
> +  baud_rate: 2400
possible allowed `baud_rate` for mbus (i know this is for uart - don't know where it is set for mbus or it is automatically the same for both):
- `300`
- `600` (not recommended)
- `1200` (not recommended)
- `2400` (most common)
- `4800` (not recommended)
- `9600`
- `19200` (not recommended, only for new repeater hardware)
- `38400` (only for new repeater hardware)

2025-02-23 22:23 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +
maybe also check the checksum? the byte before the stop byte

2025-02-23 22:23 UTC, ximex commented on tests/components/dlms_meter/common.yaml
> +  rx_pin: GPIO4          # change this to the pin where you connected the mbus adapter board
yes more important in the docs. but i would set here the same pin as in the docs

2025-02-23 22:23 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (this->receive_buffer_[frame_offset + MBUS_START1_OFFSET] != 0x68 ||
The telegram formats are: `Single Character`, `Short Frame`, `Control Frame`, `Long Frame`. So that there is a fast return that checks on the telegram format first and logs if it is an unsupported format etc. and after that check if repeated start byte is the same

2025-02-23 22:23 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (mbus_payload[DLMS_CIPHER_OFFSET] != 0xDB)  // Only general-glo-ciphering is supported (0xDB)
define `0xDB` as const

2025-02-23 22:23 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (systitle_length != 0x08)  // Only system titles with length of 8 are supported
define `0x08` as const

2025-02-24 01:47 UTC, ximex requested changes
replace all `EVN` with `Netz NÖ`

Now only the decoding part is missing to review.
Up to this point i think i have understood now the protocol by comparing different documentation that i found online and your implementation

2025-02-24 01:47 UTC, ximex commented on esphome/components/dlms_meter/mbus.h
> +
here some ASCII art for better documentation of the M-Bus Long Frame Structure:
```
+----------------------------------------------------+ -
|               Start Character [0x68]               |  \
+----------------------------------------------------+   |
|                   Data Length (L)                  |   |
+----------------------------------------------------+   |
|               Data Length Repeat (L)               |   |
+----------------------------------------------------+    > M-Bus Data link layer
|            Start Character Repeat [0x68]           |   |
+----------------------------------------------------+   |
|             Control/Function Field (C)             |   |
+----------------------------------------------------+   |
|                  Address Field (A)                 |  /
+----------------------------------------------------+ -
|           Control Information Field (CI)           |  \
+----------------------------------------------------+   |
|    Source Transport Service Access Point (STSAP)   |    > DLMS/COSEM M-Bus transport layer
+----------------------------------------------------+   |
| Destination Transport Service Access Point (DTSAP) |  /
+----------------------------------------------------+ -
|                                                    |  \
~                                                    ~   |
                         Data                             > DLMS/COSEM Application Layer
~                                                    ~   |
|                                                    |  /
+----------------------------------------------------+ -
|                      Checksum                      |  \
+----------------------------------------------------+    > M-Bus Data link layer
|                Stop Character [0x16]               |  /
+----------------------------------------------------+ -
```
Data_Length = L - C - A - CI
Each line (except Data) is one Byte

Possible Values as from Docu that i found:
- C: `0x53`/`0x73` (`SND_UD`)
- A: `FF` (Broadcast)
- CI: `0x00`-`0x1F`/`0x60`/`0x61`/`0x7C`/`0x7D`
- STSAP: `0x01` (Management Logical Device ID 1 of the meter)
- DTSAP: `0x67` (Consumer Information Push Client ID 103)

2025-02-24 01:47 UTC, ximex commented on esphome/components/dlms_meter/dlms.h
> + */
ASCII Art Data Structure
```
+-------------------------------+
|       Ciphering Service       |
+-------------------------------+
|      System Title Length      |
+-------------------------------+
|                               |
|                               |
|                               |
|            System             |
|            Title              |
|                               |
|                               |
|                               |
+-------------------------------+
|            Length             | (1 or 3 Bytes)
+-------------------------------+
|     Security Control Byte     |
+-------------------------------+
|                               |
|             Frame             |
|            Counter            |
|                               |
+-------------------------------+
|                               |
~                               ~
        Encrypted Payload       
~                               ~
|                               |
+-------------------------------+
```

- Ciphering Service: `0xDB` (General-Glo-Ciphering)
- System Title Length: `0x08`
- System Title: Unique ID of meter
- Length: 1 Byte=Length <= 127, 3 Bytes=Length > 127 (`0x82` & 2 Bytes length)
- Security Control Byte:
  - Bit 3…0: Security_Suite_Id
  - Bit 4: "A" subfield: indicates that authentication is applied
  - Bit 5: "E" subfield: indicates that encryption is applied
  - Bit 6: Key_Set subfield: 0 = Unicast, 1 = Broadcast
  - Bit 7: Indicates the use of compression.

2025-02-24 01:47 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        mbus_payload[header_offset + DLMS_SECBYTE_OFFSET] !=
maybe check by bit flags for the supported features

2025-02-24 01:47 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (message_length == 0x82) {
define as const

2025-02-24 01:47 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        mbus_payload[DLMS_LENGTH_OFFSET + 2] == 0x20) {
define as const

2025-02-24 03:11 UTC, ximex requested changes
Sadly the full spec is not open available: https://www.dlms.com/core-specifications/

Some links to documentation:
- https://www.stwk.at/fileadmin/Stadtwerke/FAQ/2022-12-27_STWK_Schnittstelle-SmartMeter.pdf
- https://stadtwerkeschwaz.at/pdfs/Technische%20Beschreibung%20Kundenschnittstelle%20SWS%20Smart%20Meter.pdf
- https://www.tinetz.at/uploads/tx_bh/101/tinetz_smart-meter_beschreibung-kundenschnittstelle_001.pdf
- https://www.salzburgnetz.at/content/dam/salzburgnetz/dokumente/stromnetz/Technische-Beschreibung-Kundenschnittstelle.pdf
- https://netz-noe.at/Download-(1)/Smart-Meter/218_9_SmartMeter_Kundenschnittstelle_lektoriert_14.aspx
- [M-Bus_MBDOC48.PDF](https://github.com/user-attachments/files/18935233/M-Bus_MBDOC48.PDF)

2025-02-24 03:11 UTC, ximex commented on esphome/components/dlms_meter/obis.h
> +enum Medium { ABSTRACT = 0x00, ELECTRICITY = 0x01, HEAT = 0x06, GAS = 0x07, WATER = 0x08 };
Found some more definitions: https://github.com/Apollon77/smartmeter-obis/blob/master/lib/ObisNames.js#L9-L19
- 0:  'Abstract',
- 1:  'Electricity',
- 4:  'Heat cost Allocator',
- 5:  'Cooling',
- 6:  'Heat',
- 7:  'Gas',
- 8:  'Cold water',
- 9:  'Hot water',
- 16: 'Oil',
- 17: 'Compressed air',
- 18: 'Nitrogen'

2025-02-24 03:11 UTC, ximex commented on esphome/components/dlms_meter/obis.h
> +  LONG64_UNSIGNED = 0x15,
use int8, uint16 etc instead of long, double_long etc

2025-02-24 03:11 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (plaintext[0] != 0x0F || plaintext[5] != 0x0C) {
Following Bytes (6+12+2=20) represents the `DECODER_START_OFFSET`

**Byte 0:**
`0x0F` = `DATA_NOTIFICATION`
https://github.com/Gurux/Gurux.DLMS.Python/blob/master/Gurux.DLMS.python/gurux_dlms/enums/Command.py#L177
should be defined as const

**Byte 1-4:**
uint32 `INVOKE_ID`
https://github.com/Gurux/Gurux.DLMS.Python/blob/master/Gurux.DLMS.python/gurux_dlms/GXDLMS.py#L2198

**Byte 5:**
unit8 (Date)(TIME) length (`0x00`=none, `0x04`=time, `0x05`=date, `0x0C`=datetime)

**DATETIME** (if `0x0C`)
https://documentation.opengate.es/api/device_integration/connector_functions/connector_functions_dlms_js_api/index.html#datetime-objects
https://documentation.opengate.es/api/device_integration/connector_functions/connector_functions_dlms_js_api/index.html#getdatetimevalue---object
- Byte 0-1: uint16 year
- Byte 2: uint8 month
- Byte 3: uint8 dayOfMonth
- Byte 4: uint8 dayOfWeek
- Byte 5: uint8 hours
- Byte 6: uint8 minutes
- Byte 7: uint8 seconds
- Byte 8: uint8 hundredthsOfSecond
- Byte 9-10: int16 deviation
- Byte 11: bitflag status

maybe also support NONE, TIME and DATE?

**Bytes after DATETIME**
`0x02`=Structure followed by a byte (uint8) with the count of structure items

2025-02-24 17:26 UTC, ximex commented
Does anyone know how i could use AES128 GCM with ESP-IDF?

i'm currently trying to get this PR running with ESP-IDF but i'm getting this errors:
```
Linking .pioenvs/smart-meter/firmware.elf
/config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: .pioenvs/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp.o: in function `esphome::dlms_meter::DlmsMeterComponent::loop()':
/config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:159:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x43a): undefined reference to `mbedtls_gcm_init'
/config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:170:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x456): undefined reference to `mbedtls_gcm_setkey'
/config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:176:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x476): undefined reference to `mbedtls_gcm_auth_decrypt'
/config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:176:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x480): undefined reference to `mbedtls_gcm_free'
collect2: error: ld returned 1 exit status
*** [.pioenvs/smart-meter/firmware.elf] Error 1
```

I have already changed the `ESP32` constants to `USE_ESP32` and "fixed" the warning about the possible to short `char timestamp[21]`. now this error is the next error i get

2025-02-25 00:25 UTC, ximex requested changes
until i get it running also with IDF it should be limited to arduino. added some notes for this changes

2025-02-25 00:25 UTC, ximex commented on esphome/components/dlms_meter/__init__.py
> +ESP_PLATFORMS = [PLATFORM_ESP8266, PLATFORM_ESP32]
`ESP_PLATFORMS` is not defined for any other component. is this maybe an old way?

2025-02-25 00:25 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#if defined(ESP8266)
use `USE_ESP8266_FRAMEWORK_ARDUINO`

2025-02-25 00:25 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#elif defined(ESP32)
use `USE_ESP32_FRAMEWORK_ARDUINO`

2025-02-25 00:25 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.h
> +#if defined(ESP32)
use `USE_ESP32_FRAMEWORK_ARDUINO`

2025-02-25 00:25 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.h
> +#if defined(ESP8266)
use `USE_ESP8266_FRAMEWORK_ARDUINO`

2025-02-25 00:25 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.h
> +#if defined(ESP32)
use `USE_ESP32_FRAMEWORK_ARDUINO`

2025-02-25 00:25 UTC, ximex commented on esphome/components/dlms_meter/__init__.py
> +)
add framework and platform validation
```py
CONFIG_SCHEMA = cv.All(
    cv.Schema(
        {
            cv.GenerateID(): cv.declare_id(DlmsMeterComponent),
            cv.Required(CONF_DECRYPTION_KEY): validate_key,
            cv.Optional(CONF_PROVIDER, "generic"): cv.enum(PROVIDERS, lower=True),
            cv.GenerateID(CONF_RAW_DATA_ID): cv.declare_id(cg.uint8),
        }
    )
    .extend(uart.UART_DEVICE_SCHEMA)
    .extend(cv.COMPONENT_SCHEMA),
    cv.only_with_arduino,
    cv.only_on([PLATFORM_ESP32, PLATFORM_ESP8266]),
)
```

2025-02-25 22:03 UTC, SimonFischer04 commented
> Does anyone know how i could use AES128 GCM with ESP-IDF?
> 
> i'm currently trying to get this PR running with ESP-IDF but i'm getting this errors:
> ```
> Linking .pioenvs/smart-meter/firmware.elf
> /config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: .pioenvs/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp.o: in function `esphome::dlms_meter::DlmsMeterComponent::loop()':
> /config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:159:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x43a): undefined reference to `mbedtls_gcm_init'
> /config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:170:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x456): undefined reference to `mbedtls_gcm_setkey'
> /config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:176:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x476): undefined reference to `mbedtls_gcm_auth_decrypt'
> /config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:176:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x480): undefined reference to `mbedtls_gcm_free'
> collect2: error: ld returned 1 exit status
> *** [.pioenvs/smart-meter/firmware.elf] Error 1
> ```
> 
> I have already changed the `ESP32` constants to `USE_ESP32` and "fixed" the warning about the possible to short `char timestamp[21]`. now this error is the next error i get

I guess idf requires also some other decryption lib. Like with esp8266 vs 32?

Ok, if idf is not that hard to integrate why not include it. Unfortunately I didn't have time yet to work on this also.
Great to see that you are trying to get it working!

PS: thanks again for the thorough review. Quite a lot of interesting points here. Will try to integrate them this weekend.

2025-02-25 22:03 UTC, SimonFischer04 commented
> Does anyone know how i could use AES128 GCM with ESP-IDF?
> 
> i'm currently trying to get this PR running with ESP-IDF but i'm getting this errors:
> ```
> Linking .pioenvs/smart-meter/firmware.elf
> /config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: .pioenvs/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp.o: in function `esphome::dlms_meter::DlmsMeterComponent::loop()':
> /config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:159:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x43a): undefined reference to `mbedtls_gcm_init'
> /config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:170:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x456): undefined reference to `mbedtls_gcm_setkey'
> /config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:176:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x476): undefined reference to `mbedtls_gcm_auth_decrypt'
> /config/.esphome/platformio/packages/toolchain-riscv32-esp@13.2.0+20240530/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /config/.esphome/build/smart-meter/src/esphome/components/dlms_meter/dlms_meter.cpp:176:(.text._ZN7esphome10dlms_meter18DlmsMeterComponent4loopEv+0x480): undefined reference to `mbedtls_gcm_free'
> collect2: error: ld returned 1 exit status
> *** [.pioenvs/smart-meter/firmware.elf] Error 1
> ```
> 
> I have already changed the `ESP32` constants to `USE_ESP32` and "fixed" the warning about the possible to short `char timestamp[21]`. now this error is the next error i get

I guess idf requires also some other decryption lib. Like with esp8266 vs 32?

Ok, if idf is not that hard to integrate why not include it. Unfortunately I didn't have time yet to work on this also.
Great to see that you are trying to get it working!

PS: thanks again for the thorough review. Quite a lot of interesting points here. Will try to integrate them this weekend.

2025-02-28 14:52 UTC, SimonFischer04 commented on esphome/components/dlms_meter/__init__.py
> +ESP_PLATFORMS = [PLATFORM_ESP8266, PLATFORM_ESP32]
Just a constant I defined but then forgot to use bellow :)

2025-02-28 15:56 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (this->receive_buffer_[frame_offset + MBUS_START1_OFFSET] != 0x68 ||
If the first part of the logic or "||" is true, the second part is not evaluted.
So then it already logs and fast returns.

2025-02-28 15:57 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +
Already though about this way back when I started implementing it.
Have you found out how to check it / how it is calculated?

2025-02-28 17:04 UTC, SimonFischer04 commented on esphome/components/dlms_meter/obis.h
> +  LONG64_UNSIGNED = 0x15,
found this spec:
https://documentation.opengate.es/api/device_integration/connector_functions/connector_functions_dlms_js_api/index.html#data-types

the types are defined like in the specification.
Sure it's better to have other names then in the spec?

2025-02-28 17:05 UTC, SimonFischer04 commented on tests/components/dlms_meter/common.yaml
> +  rx_pin: GPIO4          # change this to the pin where you connected the mbus adapter board
ok, done.

2025-02-28 17:07 UTC, SimonFischer04 commented on tests/components/dlms_meter/common.yaml
> +  baud_rate: 2400
I know these, just common uart baud rates.
What do you want me to change here?

2025-02-28 18:23 UTC, SimonFischer04 commented on tests/components/dlms_meter/common.yaml
> +  rx_pin: GPIO4          # change this to the pin where you connected the mbus adapter board
Ok, reverted.
![image](https://github.com/user-attachments/assets/89471cf4-cb17-4f1f-b1ea-4cf0580727d0)

Not all boards have GPIO33. Have we actually figured out if changing the pin helps?

2025-02-28 18:36 UTC, pos-ei-don commented on tests/components/dlms_meter/common.yaml
> +  rx_pin: GPIO4          # change this to the pin where you connected the mbus adapter board
Why Not usw RX and TX as Default? Works here in my Setup even with esp8266.

2025-02-28 21:34 UTC, SimonFischer04 commented on tests/components/dlms_meter/common.yaml
> +  rx_pin: GPIO4          # change this to the pin where you connected the mbus adapter board
@pos-ei-don what do you mean, what pin do you use?
And second: tx is not required, as we obviously can't send data to the smartmeter.

2025-02-28 21:40 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        mbus_payload[header_offset + DLMS_SECBYTE_OFFSET] !=
I have not yet really figured the details of this decryption.
For me these were just two modes.

So you say there are some kind of features encoded into byte?

2025-02-28 22:19 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (plaintext[0] != 0x0F || plaintext[5] != 0x0C) {
1) Sure 0x0F is DATA_NOTIFICATION?

https://github.com/Gurux/Gurux.DLMS.Python/blob/master/Gurux.DLMS.python/gurux_dlms/enums/Command.py#L177 defines DATA_NOTIFICATION under section """DLMS commands.""".

At this point in code the data is already decrypted so why should it have anything todo with dlms?

2) What do you want to tell me with the INVOKE_ID. Do I need it for anything?

3) Also I'm note sure about 0x0C=datetime. Only netz noe meters send timestamp, but this is defined for all of them.

4) 0x02=Structure ...
Same here, should I change something here?

2025-02-28 22:30 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (message_length == 0x82) {
This is not a dedicated magic constant.

0x82 to dec so 130 - 1 byte checksum - 1 stop byte = 128 > 127 exactly what the if conditions says.

Or would you prefer something like this?
`if (message_length == 127 + 1 +1) {`

2025-02-28 22:36 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (systitle_length != 0x08)  // Only system titles with length of 8 are supported
Same here.
I agree special mbus/obis/dlms bytes should be defined as const.
But not basic length checks.
I don't see how a `EXPECTED_SYSTITLE_LENGTH=0x08` const is better than just putting 8 in hex here. Just one more constant you have to look up the actual value for.

2025-02-28 22:40 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        mbus_payload[DLMS_LENGTH_OFFSET + 2] == 0x20) {
As far as I understand, these are not spec compliant.
What should I name this const's.
NETZ_NOE_MAGIC_VALUE_1, NETZ_NOE_MAGIC_VALUE_2, NETZ_NOE_MAGIC_VALUE_3?

2025-02-28 22:49 UTC, SimonFischer04 commented
@ximex I have now implemented most requested changes.
Some things I'm unsure / don't fully understand. Have left some comments.
Please re-check.

2025-03-03 22:35 UTC, ximex commented on esphome/components/dlms_meter/obis.h
> +  LONG64_UNSIGNED = 0x15,
ok than keep the names. i only don't like this type of how the bit count is defined. the variant with `int8` etc it's directly visible how many bits it takes

2025-03-03 22:46 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (this->receive_buffer_[frame_offset + MBUS_START1_OFFSET] != 0x68 ||
the idea was to first check only for the telegram format. so `Single Character`, `Short Frame`, `Control Frame`, `Long Frame`
as only `Control Frame`, `Long Frame` has the repeated start byte it should be checked only if it's one of this two. this is like a preparation to support also the other formats. and we could log different messages. unknown/unsupported start byte vs invalid repeated start byte

2025-03-03 22:48 UTC, ximex commented on tests/components/dlms_meter/common.yaml
> +  baud_rate: 2400
i didn't know that this values are standard values. only found that in the docu so i thought maybe add this somewhere in the docu or code comments

2025-03-03 22:48 UTC, ximex commented
> Would it make sense to extract the parts (M-Bus, DLMS, Decryption, Decoding) in the loop function into separate functions and move them into `mbus.cpp`, `dlms.cpp`, `decryption.cpp` `obis.cpp`?

what about that?

2025-03-03 23:01 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (systitle_length != 0x08)  // Only system titles with length of 8 are supported
and if the check gets removed completely that also different lengths get supported?
so instead of using `DLMS_LENGTH_OFFSET` use `DLMS_SYST_OFFSET + 1 + systitle_length`

2025-03-03 23:26 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +
if i understood it correct: take all bytes from the `C` field until before the checksum. convert this to decimal, sum them up, convert back to hex and take only the first (right) byte

example from here (last page): https://www.salzburgnetz.at/content/dam/salzburgnetz/dokumente/stromnetz/Technische-Beschreibung-Kundenschnittstelle.pdf

steps:
- data: `685D5D6853FF100167DB08454C5365700000014D200000541FE2A330AD29E0D68C09365BA286DBF3A7DF14B7790E14D1556AB974B27EC5847D11936DB5191DD0F489BA768C2DBB68F6B001E304C21FEA147E0B2E2CA1B91D574DF4F7F582CEBE928316`
- take: `53FF100167DB08454C5365700000014D200000541FE2A330AD29E0D68C09365BA286DBF3A7DF14B7790E14D1556AB974B27EC5847D11936DB5191DD0F489BA768C2DBB68F6B001E304C21FEA147E0B2E2CA1B91D574DF4F7F582CEBE92` and `83` is checksum
- decimal array: `[83,255,16,1,103,219,8,69,76,83,101,112,0,0,1,77,32,0,0,84,31,226,163,48,173,41,224,214,140,9,54,91,162,134,219,243,167,223,20,183,121,14,20,209,85,106,185,116,178,126,197,132,125,17,147,109,181,25,29,208,244,137,186,118,140,45,187,104,246,176,1,227,4,194,31,234,20,126,11,46,44,161,185,29,87,77,244,247,245,130,206,190,146]`
- sum: `10883`
- hex sum: `"2a83"`
- checksum: `83`

2025-03-03 23:37 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        mbus_payload[header_offset + DLMS_SECBYTE_OFFSET] !=
this is what is documented here: https://github.com/esphome/esphome/pull/8009#discussion_r1966963033
The `Security Control Byte` Bit 5 indicates if it's encrypted. For more details i also have to dig a bit deeper

2025-03-04 00:00 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (plaintext[0] != 0x0F || plaintext[5] != 0x0C) {
this also confused me that it's defined in the commands.
Use this PDU data: `0F000055390C07E0090804130D1900FFC4800207090C07E0090804130D190000008009060100010800FF060000000002020F00161E09060100030800FF060000000002020F00162`
and insert here: https://www.gurux.fi/GuruxDLMSTranslator
and convert to XML and see the output

also look here: https://github.com/Gurux/Gurux.DLMS.Python/blob/master/Gurux.DLMS.python/gurux_dlms/GXDLMS.py#L2685
first they check for the `DATA_NOTIFICATION` and then they continue in `handleDataNotification` with the invokeId, date/time etc

i only document what i found out what all the bytes are named or what they do. here i only know the name and don't know for what they are. at least we have a name for the constants.

if we check byte 5 (date/time) than we could support all possibilities that some other smart meters could have. so depending on byte 5 take a different offset instead of hardcoding it to `0x0C`. Don't know if it make sense to expose the date/time as a sensor value (is like a last update timestamp value)

about the `0x02` after date/time:
this shows you directly how many data values are in there to parse (not the count of sensors - value&unit etc most get combined)
maybe we could use this info also for validation

2025-03-04 00:09 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        mbus_payload[DLMS_LENGTH_OFFSET + 2] == 0x20) {
The only magic value here should be the `0x81`.
The `0xF8` is the length of the encrypted data.
`0x20` is the `Security Control Byte` for this see here: https://github.com/esphome/esphome/pull/8009#discussion_r1966964018

2025-03-04 00:22 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (message_length == 0x82) {
As of this documentation the `0x82` is a special magic value. see (both page 7):
- https://www.tinetz.at/uploads/tx_bh/101/tinetz_smart-meter_beschreibung-kundenschnittstelle_001.pdf
- https://stadtwerkeschwaz.at/pdfs/Technische%20Beschreibung%20Kundenschnittstelle%20SWS%20Smart%20Meter.pdf

2025-03-04 00:24 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        mbus_payload[header_offset + DLMS_SECBYTE_OFFSET] !=
See last page: https://www.stwk.at/fileadmin/Stadtwerke/FAQ/2022-12-27_STWK_Schnittstelle-SmartMeter.pdf
maybe we could also check for authentication and not only encryption

2025-03-04 00:25 UTC, ximex commented on tests/components/dlms_meter/common.yaml
> +  rx_pin: GPIO4          # change this to the pin where you connected the mbus adapter board
> Not all boards have GPIO33. Have we actually figured out if changing the pin helps?

i havn't tested it yet. i know only of the comment in the issue that this should fix it

2025-03-05 11:18 UTC, SimonFischer04 commented on esphome/components/dlms_meter/obis.h
> +  LONG64_UNSIGNED = 0x15,
Yes, I would have also preferred the uint8, ... style, but this is how the spec is ...
Ok

2025-03-05 11:24 UTC, SimonFischer04 commented on tests/components/dlms_meter/common.yaml
> +  baud_rate: 2400
The baud_rate setting is part of the 'uart' section/component. So if any, the uart docs should document it (https://www.esphome.io/components/uart), not in one component using uart. This is exactly why esphome provides the uart abstraction and how other components are too.

2025-03-05 13:20 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (systitle_length != 0x08)  // Only system titles with length of 8 are supported
Unfortunately it's not that easy.
The systitle is part of the iv for aes-gcm. If it's different, then we would first have to figure out how it is handled. Maybe iv bigger, maybe different splitting of 12 bytes iv, ...
So for now only support length 8, until other length support is required and we have specs how decryption is handled then in such cases.

I think this explains the iv part quite well. I also used this as reference on how to implement it: https://www.weigu.lu/tutorials/sensors2bus/04_encryption/index.html

2025-03-05 16:24 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +
thanks, implemented

2025-03-05 16:58 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (message_length == 0x82) {
Didn't realize that.
Thanks

2025-03-05 17:20 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        mbus_payload[header_offset + DLMS_SECBYTE_OFFSET] !=
We currently allow 0x21 and 0x20. So according to your linked comment / docs (assuming MSB first), this means we have a 1 bit difference in bit 0 of Security_Suite_Id.

I would much rather prefer to keep this explicit check for now and change it if further issues arise / support for other meters, instead of allowing all and potentially allowing wrong data.

2025-03-05 18:28 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (plaintext[0] != 0x0F || plaintext[5] != 0x0C) {
Ok, thanks for clarification.

Defined as const now.

If other options like time are supported, I don't think it makes sense to publish them equally in the "timestamp" sensor. It should probably be published as another sensor, to not confuse users expecting an actual timestamp in there. But let's not overcomplicate things for now, if not yet required by any meter.
I think it makes sense to expose timestamp. (Also my) usecase: EEGs.
The provider assigns consumption in 15m time slots. But the esp receiving, decryption, parsing, publishing the data can take some time. For dynamic power control I need the exact values also used by the provider, to ensure there are no mismatches.

about the 0x02 after date/time:
So the count is *2 the received data (code&value), but not if it's a struct ...
I don't see an easy way to implement this and don't think we really need this.
With all the checksum, ... checks, I think this should be enough.

2025-03-05 18:42 UTC, SimonFischer04 commented
> > Would it make sense to extract the parts (M-Bus, DLMS, Decryption, Decoding) in the loop function into separate functions and move them into `mbus.cpp`, `dlms.cpp`, `decryption.cpp` `obis.cpp`?
> 
> what about that?
> 
> Have answered on every question if i didn't missed anything

Sorry, missed that one.
Yeah, probably makes sense in the future. Would also be good to then add unit tests for some known data for the individual parts (I see there is something in progress about adding unit test support: https://github.com/esphome/esphome/pull/5728). 
But unfortunately don't have time to re-structure code so it can be split-up, ... currently.
Hope it's not a blocker to get this initial implementation forward.

Same here. Implemented some more requested changes. A few questions left.

2025-03-05 20:01 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (plaintext[0] != 0x0F || plaintext[5] != 0x0C) {
yes the validation of the `0x02` would be tricky and only the cherry on the top.

the support of the different date/time types should be easy:
```cpp
// dlsm.h
static const unit8_t DATA_NOTIFICATION = 0x0F;
static const unit8_t INVOKE_ID_LENGTH = 0x04;

enum DateTimeLength : uint8_t {
  DATETIME_LENGTH_NONE = 0x00, 
  DATETIME_LENGTH_TIME = 0x04,
  DATETIME_LENGTH_DATE = 0x05,
  DATETIME_LENGTH_DATETIME = 0x0C,
};
```
```cpp
// dlms_meter.cpp
if (plaintext[0] != DATA_NOTIFICATION) {
  ESP_LOGE(TAG, "OBIS: Packet was decrypted but data is invalid");
  abort_();
  return;
}

const uint8_t datetime_length = plaintext[5];
if (datetime_length != DATETIME_LENGTH_NONE && datetime_length != DATETIME_LENGTH_TIME && datetime_length != DATETIME_LENGTH_DATE && datetime_length != DATETIME_LENGTH_DATETIME {
  ESP_LOGE(TAG, "Invalid datetime length");
  abort_();
  return;
}

// Decoding

ESP_LOGV(TAG, "Decoding payload");

MeterData data{};
const int decoder_start_offset = 1 + INVOKE_ID_LENGTH + 1 + datetime_length;  // DATA_NOTIFICATION + INVOKE_ID_LENGTH + DateTimeLength + datetime_length
int current_position = decoder_start_offset;
```
and replace `DECODER_START_OFFSET` with `decoder_start_offset` and remove it from the `obis.h` file

2025-03-27 13:57 UTC, ximex approved these changes
i'm happy for now. extracting the logic into different files and support for IDF could get added later in other PRs

2025-03-27 14:22 UTC, swoboda1337 commented on esphome/components/dlms_meter/obis.h
> +static const int OBIS_F = 5;
Don't use int use int8_t int16_t etc etc

2025-03-27 14:22 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    log_packet_(this->receive_buffer_);
Should be using this->

2025-03-27 14:22 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        abort_();
this->

2025-03-27 14:22 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (mbus_payload.size() < 20)  // If the payload is too short we need to abort
Brackets

2025-03-27 14:22 UTC, swoboda1337 commented on esphome/components/dlms_meter/__init__.py
> +AUTO_LOAD = ["sensor", "text_sensor"]
Do not auto load these, you will want to refactor this to use subfolders for sensor and text_sensor

2025-03-27 14:22 UTC, swoboda1337 commented on esphome/components/dlms_meter/__init__.py
> +        cg.add_define("METER_PROVIDER", config[CONF_PROVIDER])
Do these have to be defines?

2025-03-27 14:22 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
IDF must be supported

2025-03-27 14:22 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (frame_offset >= this->receive_buffer_.size())  // No more data to read, exit loop
Why not make this the while condition instead of using while (true) and an extra if statement?

2025-03-27 14:22 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (mbus_payload[DLMS_CIPHER_OFFSET] != GLO_CIPHERING)  // Only general-glo-ciphering is supported (0xDB)
Brackets wrong

2025-03-27 14:51 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
@ximex I think you started with idf support. How far did you get?

2025-03-27 14:59 UTC, SimonFischer04 commented on esphome/components/dlms_meter/__init__.py
> +        cg.add_define("METER_PROVIDER", config[CONF_PROVIDER])
Could of course f.e. also just call a function that sets a variable value.
Then use that var in a normal runtime if condition.

Did it like this so it can be compile time optimized and requires less if checks during runtime.

Would you prefer the runtime check?

2025-03-27 15:11 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
@SimonFischer04 not so much. i stuck at the cipher lib import: https://github.com/ximex/esphome/tree/dlms-meter-idf
and this "fix" also looks a bit dirty: https://github.com/ximex/esphome/commit/b5ec67827bbf7798d6996668a86acbbcf111e10b

2025-03-27 15:52 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
> and this "fix" also looks a bit dirty: [ximex@b5ec678](https://github.com/ximex/esphome/commit/b5ec67827bbf7798d6996668a86acbbcf111e10b)

Yeah interesting "fix". Have you had problems with wrong timestamp values?

> https://github.com/ximex/esphome/tree/dlms-meter-idf

So basically you just reverted the patch i added during your review and then got stuck compiling in mbedtls?

2025-03-27 16:14 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
the "fix" was only to keep the linter happy afair.
yes. i tried to import this: https://github.com/espressif/esp-idf/tree/v5.3.1/components/mbedtls
my C++ knowledge is to less for that. if someone helps me with that i could try to continue with the IDF implementation

2025-03-27 16:21 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
> the "fix" was only to keep the linter happy afair. yes. i tried to import this: https://github.com/espressif/esp-idf/tree/v5.3.1/components/mbedtls my C++ knowledge is to less for that. if someone helps me with that i could try to continue with the IDF implementation

What error do you get it? Is it reproducible on that branch?

2025-03-27 17:36 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
> the "fix" was only to keep the linter happy afair. yes. i tried to import this: https://github.com/espressif/esp-idf/tree/v5.3.1/components/mbedtls my C++ knowledge is to less for that. if someone helps me with that i could try to continue with the IDF implementation

You can't use this api? Works in IDF: https://github.com/esphome/esphome/blob/dev/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp#L744-L757

2025-03-27 17:45 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
Another example https://github.com/esphome/esphome/blob/dev/esphome/components/xiaomi_ble/xiaomi_ble.cpp#L290-L301

2025-03-27 17:57 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
Not sure why the aes and ccm apis work and link but not the gcm ones.

2025-03-27 18:09 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
Give this a try:
```
#if defined(USE_ESP32)
#include "mbedtls/esp_config.h"
#include "mbedtls/gcm.h"
#endif
```
In esp_config.h it has the important define MBEDTLS_GCM_ALT which gcm.h needs:
```
#ifdef CONFIG_MBEDTLS_HARDWARE_AES
#define MBEDTLS_GCM_ALT
#endif
```

2025-03-27 21:21 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
> Give this a try:
> 
> ```
> #if defined(USE_ESP32)
> #include "mbedtls/esp_config.h"
> #include "mbedtls/gcm.h"
> #endif
> ```

Didn't think idf support would be that easy, but apparently (if you know the right include) it is.
This worked perfectly. (also flashed it to my esp and everything seems to still work)
Thanks.

2025-03-27 21:27 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
lol it was this line. this cost me about 6-8 hours...
my ESP32-C6-DevKitC1 is working... also the normal ESP32 is working with IDF

2025-03-27 21:27 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
Don't forget to add some IDF tests

2025-03-27 21:28 UTC, ximex commented
Most of the requested changes and some more are here: https://github.com/ximex/esphome/commits/dlms-meter-idf/
@SimonFischer04 you could merge/cherry-pick etc my commits into your branch

2025-03-27 21:28 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
On it

2025-03-27 21:30 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (mbus_payload[DLMS_CIPHER_OFFSET] != GLO_CIPHERING)  // Only general-glo-ciphering is supported (0xDB)
fixed in my branch

2025-03-27 21:30 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (frame_offset >= this->receive_buffer_.size())  // No more data to read, exit loop
fixed in my branch

2025-03-27 21:30 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
fixed in my branch

2025-03-27 21:30 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (mbus_payload.size() < 20)  // If the payload is too short we need to abort
fixed in my branch

2025-03-27 21:30 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        abort_();
fixed in my branch

2025-03-27 21:30 UTC, ximex commented on esphome/components/dlms_meter/obis.h
> +static const int OBIS_F = 5;
fixed in my branch

2025-03-27 21:30 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    log_packet_(this->receive_buffer_);
fixed in my branch

2025-03-27 21:31 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
Should i just add generic -idf tests or also specific ones for (-c3, -c6, -s3)?

2025-03-27 21:33 UTC, SimonFischer04 commented on esphome/components/dlms_meter/__init__.py
> +AUTO_LOAD = ["sensor", "text_sensor"]
Please explain this a bit more of how it should be.
I'm not that deep into esphome internals.
I based this of how other components do it: https://github.com/esphome/esphome/blob/dev/esphome/components/dsmr/__init__.py#L12

2025-03-27 21:35 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
> fixed in my branch

Also already fixed in mine 😀

2025-03-27 21:39 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (mbus_payload[DLMS_CIPHER_OFFSET] != GLO_CIPHERING)  // Only general-glo-ciphering is supported (0xDB)
there are many instances of this I just didn't comment on all of them

2025-03-27 21:39 UTC, SimonFischer04 commented
> Most of the requested changes and some more are here: https://github.com/ximex/esphome/commits/dlms-meter-idf/ @SimonFischer04 you could merge/cherry-pick etc my commits into your branch

Want to make a pr against my branch so I don't have to cherry-pick them individually? 😀

2025-03-27 21:40 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
esp32-idf is the original esp32 variant, not really generic, doesn't hurt to add a few more

2025-03-27 21:41 UTC, swoboda1337 commented on esphome/components/dlms_meter/__init__.py
> +        cg.add_define("METER_PROVIDER", config[CONF_PROVIDER])
I think a runtime check is better. Maybe you want to have two of these components in the same build. Ifdefs cant work then.

2025-03-27 21:42 UTC, swoboda1337 commented on esphome/components/dlms_meter/__init__.py
> +AUTO_LOAD = ["sensor", "text_sensor"]
If you look at other components this is typically how it is done: 
https://github.com/esphome/esphome/tree/dev/esphome/components/ld2420

2025-03-27 21:44 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    if (mbus_payload[DLMS_CIPHER_OFFSET] != GLO_CIPHERING)  // Only general-glo-ciphering is supported (0xDB)
I thought this came from running esphome-lint so I did not change it. 
Anyways, @ximex thanks for fixing it.

2025-03-27 21:48 UTC, ximex commented
@SimonFischer04 good idea. Done: https://github.com/SimonFischer04/esphome/pull/2

2025-03-27 21:56 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
https://github.com/esphome/esphome/actions/runs/14117390959/job/39550795465?pr=8009#step:5:185
means c6 is not yet supported by testing framework?

2025-03-27 22:12 UTC, SimonFischer04 commented
> Most of the requested changes and some more are here: https://github.com/ximex/esphome/commits/dlms-meter-idf/ @SimonFischer04 you could merge/cherry-pick etc my commits into your branch

From the remaining few requested changes. Anything you are already working on / still want to do?
So we don't do duplicate changes again.

2025-03-27 22:13 UTC, ximex commented
@SimonFischer04 no currently not working on anything of the other changes

2025-03-27 22:29 UTC, SimonFischer04 commented on esphome/components/dlms_meter/__init__.py
> +        cg.add_define("METER_PROVIDER", config[CONF_PROVIDER])
In the context of this component I would really question the usecase of two components in one build.
1) you have to have two smartmeters in physical range of one esp.
2) especially the context of this setting. it defines your energy provider / grid operator.  The only special option is netznoe. Which is one of them operating only here in lower austria. So if you live here, you have netznoe. If you live in another state you have a different on. So if 1) would apply, you would still have the same provider, so no problem.

2025-03-27 22:33 UTC, swoboda1337 commented on esphome/components/dlms_meter/__init__.py
> +        cg.add_define("METER_PROVIDER", config[CONF_PROVIDER])
In general though ifdefs are discouraged unless you need them.

2025-03-27 22:59 UTC, SimonFischer04 commented on esphome/components/dlms_meter/__init__.py
> +AUTO_LOAD = ["sensor", "text_sensor"]
Thanks, fixed now.

2025-03-28 00:01 UTC, SimonFischer04 commented on esphome/components/dlms_meter/__init__.py
> +        cg.add_define("METER_PROVIDER", config[CONF_PROVIDER])
I don't agree with wasting performance and memory on low powered devices. 
But ok, if that's how esphome code standards are, then I'm fine with this change.

Implemented in latest commit.

2025-03-28 00:19 UTC, SimonFischer04 commented on esphome/components/dlms_meter/obis.h
> +static const int OBIS_F = 5;
@swoboda1337 ci does not like that:

```
src/esphome/components/dlms_meter/dlms.h:84:14: error: 'uint8_t' does not name a type
 static const uint8_t NETZ_NOE_EXPECTED_SECURITY_CONTROL_BYTE = 0x20;
```

https://github.com/esphome/esphome/actions/runs/14119101681/job/39555899770?pr=8009#step:6:1047

2025-03-28 00:19 UTC, SimonFischer04 commented on esphome/components/dlms_meter/obis.h
> +static const int OBIS_F = 5;
Locally everything compiles fine

2025-03-28 00:21 UTC, swoboda1337 commented on esphome/components/dlms_meter/obis.h
> +static const int OBIS_F = 5;
You haven't induced any headers to define the types.

2025-03-28 00:29 UTC, SimonFischer04 commented on esphome/components/dlms_meter/obis.h
> +static const int OBIS_F = 5;
What headers do I need for this, isn't uint8_t a standard type? I have used uint8_t in main dlms_meter.cpp already but have not had to include any header.

2025-03-28 00:42 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
c6 tests are now removed again

2025-03-28 00:45 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#error "Invalid Platform"
Yeah it's fine to remove c6 as it's not officially supported yet

2025-03-28 00:53 UTC, ximex requested changes
it's possible to dig deeper and deeper and you will always find more^^
maybe adding also some default icons in the python file?
like:
- https://pictogrammers.com/library/mdi/icon/lightning-bolt/
- https://pictogrammers.com/library/mdi/icon/current-ac/
- https://pictogrammers.com/library/mdi/icon/sine-wave/

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +  ESP_LOGCONFIG(TAG, "read_timeout: %ld", this->read_timeout_);
do we have to use `%ld` and `%d` depending on the build? (ESP32 vs ESP8266)

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +  while (available()) {  // Read while data is available
overlooked a missing `this->available()` here

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.h
> +#endif
```cpp
#if defined(USE_ESP8266_FRAMEWORK_ARDUINO)
#include <bearssl/bearssl.h>
#elif defined(USE_ESP32)
#include "mbedtls/esp_config.h"
#include "mbedtls/gcm.h"
#endif
```

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +          if (timestampFound == true) {
simplify to `if (timestampFound) {`?

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +          } else if (meterNumberFound == true) {
simplify to `if (meterNumberFound) {`?

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      bool timestampFound = false;
rename to `timestamp_found`?

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      bool meterNumberFound = false;
rename to `meter_number_found`?

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    mbedtls_gcm_init(&this->aes_);
move the class property `aes_` in here as local variable? it's not used anywhere else. and maybe also rename to `gcm_ctx` like in line 190

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    uint8_t c;
better variable naming?

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.h
> +#endif
remove here and use as local variable?

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.h
> +static const uint8_t PROVIDER_NETZNOE = 1;
maybe as enum?

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.h
> +static const char *const DLMS_METER_VERSION = "0.9.1";
update version to 1.0.0 before merge

2025-03-28 00:53 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +            char meterNumber[13];  // 121110284568
rename to `meter_number`?

2025-03-28 00:53 UTC, SimonFischer04 commented on esphome/components/dlms_meter/obis.h
> +static const int OBIS_F = 5;
Other compoenents also use uint8_t without any includes
https://github.com/esphome/esphome/blob/dev/esphome/components/ili9xxx/ili9xxx_defines.h

So any idea what could be wrong?

2025-03-28 00:59 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    uint8_t c;
it's really not that hard to find out that this is just one character read from uart in this 5 line loop.
Naming things is hard ... better suggestions?

2025-03-28 01:16 UTC, SimonFischer04 commented
> it's possible to dig deeper and deeper and you will always find more^^
> 
> maybe adding also some default icons in the python file? like:
> 
> * https://pictogrammers.com/library/mdi/icon/lightning-bolt/
> * https://pictogrammers.com/library/mdi/icon/current-ac/
> * https://pictogrammers.com/library/mdi/icon/sine-wave/
> 
> and should we use `vec.at(...) instead of `vec[...]` to access the vector?

Yes ...
If we are now discussing about icons for the webserver ... (not a lot of components have them either)
Can we just get the basics working first and also not change everything now so @swoboda1337 don't has to re-review all the files already checked.

2025-03-28 01:33 UTC, SimonFischer04 commented
@swoboda1337 requested changes implemented.
only thing left i think is the ci fail -  any idea?

2025-03-28 02:26 UTC, swoboda1337 commented
> @swoboda1337 requested changes implemented. only thing left i think is the ci fail - any idea?

Yes include <cstdint> where those are defined.

2025-03-28 02:30 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    mbedtls_gcm_init(&this->aes_);
Agreed, can also move the mbed includes into the c++ file too.

2025-03-28 22:20 UTC, SimonFischer04 commented
> > @swoboda1337 requested changes implemented. only thing left i think is the ci fail - any idea?
> 
> Yes include `<cstdint>` where those are defined.


@swoboda1337 

Thanks, implemented.
All checks pass now.
mbedtls_gcm_context move to cpp also done.

Anything left here?

2025-04-01 06:07 UTC, pos-ei-don commented
[SimonFischer04](https://github.com/SimonFischer04)
> Anything left here?

My EPS8266 which worked, stopped working with the last changes. 
The compilation and OTA Update ist good, but no Data ist deliverwd after booting, and No Log exept the Boot Log below ist awailable.
I am not seeing any debug-log information, the serial logger just shows this.

The code i included this is

```
external_components:
  - source: github://pr#8009   # see https://github.com/esphome/esphome/pull/8009
    components: [ dlms_meter ]
#    refresh: 0s

```


```
[08:02:40]
[08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[08:02:40]
[08:02:40]load 0x4010f000, len 3424, room 16 
[08:02:40]tail 0
[08:02:40]chksum 0x2e
[08:02:40]load 0x3fff20b8, len 40, room 8 
[08:02:40]tail 0
[08:02:40]chksum 0x2b
[08:02:40]csum 0x2b
[08:02:40]v0008eb60
[08:02:40]~ld
[08:02:40]����g�;��o|�$�l`b��|{�d�n��'�d`��`;�l�d��
[08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[08:02:40]
[08:02:40]load 0x4010f000, len 3424, room 16 
[08:02:40]tail 0
[08:02:40]chksum 0x2e
[08:02:40]load 0x3fff20b8, len 40, room 8 
[08:02:40]tail 0
[08:02:40]chksum 0x2b
[08:02:40]csum 0x2b
[08:02:40]v0008eb60
[08:02:40]~ld
[08:02:40]����g�s��g|�l�d`c��<;�$�g��o�l �� s�$�l��
[08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[08:02:40]
[08:02:40]load 0x4010f000, len 3424, room 16 
[08:02:40]tail 0
[08:02:40]chksum 0x2e
[08:02:40]load 0x3fff20b8, len 40, room 8 
[08:02:40]tail 0
[08:02:40]chksum 0x2b
[08:02:40]csum 0x2b
[08:02:40]v0008eb60
[08:02:40]~ld
[08:02:40]����g�r��o|�l�d`c��<;�$�g��o�$ ��{�$�l��
[08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[08:02:40]
[08:02:40]load 0x4010f000, len 3424, room 16 
[08:02:40]tail 0
[08:02:40]chksum 0x2e
[08:02:40]load 0x3fff20b8, len 40, room 8 
[08:02:40]tail 0
[08:02:40]chksum 0x2b
[08:02:40]csum 0x2b
[08:02:40]v0008eb60
[08:02:40]~ld
[08:02:40]����n��{��'<�d�l #��|s�l�'��'�l`��;�l�l��
[08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[08:02:40]
[08:02:40]load 0x4010f000, len 3424, room 16 
[08:02:40]tail 0
[08:02:40]chksum 0x2e
[08:02:40]load 0x3fff20b8, len 40, room 8 
[08:02:40]tail 0
[08:02:40]chksum 0x2b
[08:02:40]csum 0x2b
[08:02:40]v0008eb60
[08:02:40]~ld
[08:02:40]����n��{��'|�l�$ c��|;�l�g��g�l`��{�$�l��
[08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[08:02:40]
[08:02:40]load 0x4010f000, len 3424, room 16 
[08:02:40]tail 0
[08:02:40]chksum 0x2e
[08:02:40]load 0x3fff20b8, len 40, room 8 
[08:02:40]tail 0
[08:02:40]chksum 0x2b
[08:02:40]csum 0x2b
[08:02:40]v0008eb60
[08:02:40]~ld
[08:02:40]����'�s��g|�l�d`c��|{�d�n��'�d`��;�l�d��
[08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[08:02:40]
[08:02:40]load 0x4010f000, len 3424, room 16 
[08:02:40]tail 0
[08:02:40]chksum 0x2e
[08:02:40]load 0x3fff20b8, len 40, room 8 
[08:02:40]tail 0
[08:02:40]chksum 0x2b
[08:02:40]csum 0x2b
[08:02:40]v0008eb60
[08:02:40]~ld
[08:02:40]����'��s��'<�d�l`b��|{�$�o��o�$ ��s�d�$��
[08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[08:02:40]
[08:02:40]load 0x4010f000, len 3424, room 16 
[08:02:40]tail 0
[08:02:40]chksum 0x2e
[08:02:40]load 0x3fff20b8, len 40, room 8 
[08:02:40]tail 0
[08:02:40]chksum 0x2b
[08:02:40]csum 0x2b
[08:02:40]v0008eb60
[08:02:40]~ld
[08:02:40]����'�s��g|�l�$ c��|r�l�g��g�l ��{�$�l��
[08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[08:02:40]
[08:02:40]load 0x4010f000, len 3424, room 16 
[08:02:40]tail 0
[08:02:40]chksum 0x2e
[08:02:40]load 0x3fff20b8, len 40, room 8 
[08:02:40]tail 0
[08:02:40]chksum 0x2b
[08:02:40]csum 0x2b
[08:02:40]v0008eb60
[08:02:40]~ld
[08:02:40]����n��{��'<�d�l #��|s�l�'��g�l`��;�l�l��
[08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[08:02:40]
[08:02:40]load 0x4010f000, len 3424, room 16 
[08:02:40]tail 0
[08:02:40]chksum 0x2e
[08:02:40]load 0x3fff20b8, len 40, room 8 
[08:02:40]tail 0
[08:02:40]chksum 0x2b
[08:02:40]csum 0x2b
[08:02:40]v0008eb60
[08:02:40]~ld
[08:02:40]����'��{��'<�d�l`#��|s�l�'��'�d`��`s�d�$��
[08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
[08:02:40]
[08:02:40]load 0x4010f000, len 3424, room 16 
[08:02:40]tail 0
[08:02:40]chksum 0x2e
[08:02:40]load 0x3fff20b8, len 40, room 8 
[08:02:40]tail 0
[08:02:40]chksum 0x2b
[08:02:40]csum 0x2b
[08:02:40]v0008eb60
[08:02:40]~ld
```

2025-04-03 07:09 UTC, SimonFischer04 commented
> [SimonFischer04](https://github.com/SimonFischer04)
> 
> > Anything left here?
> 
> My EPS8266 which worked, stopped working with the last changes. The compilation and OTA Update ist good, but no Data ist deliverwd after booting, and No Log exept the Boot Log below ist awailable. I am not seeing any debug-log information, the serial logger just shows this.
> 
> The code i included this is
> 
> ```
> external_components:
>   - source: github://pr#8009   # see https://github.com/esphome/esphome/pull/8009
>     components: [ dlms_meter ]
> #    refresh: 0s
> ```
> 
> ```
> [08:02:40]
> [08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> [08:02:40]
> [08:02:40]load 0x4010f000, len 3424, room 16 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2e
> [08:02:40]load 0x3fff20b8, len 40, room 8 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2b
> [08:02:40]csum 0x2b
> [08:02:40]v0008eb60
> [08:02:40]~ld
> [08:02:40]������g�;��o|�$���l`��b�����|�{��d�n��'��d`���`;�l�d����
> [08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> [08:02:40]
> [08:02:40]load 0x4010f000, len 3424, room 16 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2e
> [08:02:40]load 0x3fff20b8, len 40, room 8 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2b
> [08:02:40]csum 0x2b
> [08:02:40]v0008eb60
> [08:02:40]~ld
> [08:02:40]������g�s��g|��l��d`��c����<�;��$�g���o�l ��� s�$�l�����
> [08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> [08:02:40]
> [08:02:40]load 0x4010f000, len 3424, room 16 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2e
> [08:02:40]load 0x3fff20b8, len 40, room 8 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2b
> [08:02:40]csum 0x2b
> [08:02:40]v0008eb60
> [08:02:40]~ld
> [08:02:40]������g�r��o|�l���d`��c�����<�;��$�g��o�$ ���{�$�l����
> [08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> [08:02:40]
> [08:02:40]load 0x4010f000, len 3424, room 16 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2e
> [08:02:40]load 0x3fff20b8, len 40, room 8 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2b
> [08:02:40]csum 0x2b
> [08:02:40]v0008eb60
> [08:02:40]~ld
> [08:02:40]������n��{��'<��d��l ��#�����|�s��l�'���'��l`���;�l�l�����
> [08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> [08:02:40]
> [08:02:40]load 0x4010f000, len 3424, room 16 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2e
> [08:02:40]load 0x3fff20b8, len 40, room 8 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2b
> [08:02:40]csum 0x2b
> [08:02:40]v0008eb60
> [08:02:40]~ld
> [08:02:40]������n��{��'|��l�$ ��c����|�;��l�g���g��l`���{�$�l����
> [08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> [08:02:40]
> [08:02:40]load 0x4010f000, len 3424, room 16 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2e
> [08:02:40]load 0x3fff20b8, len 40, room 8 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2b
> [08:02:40]csum 0x2b
> [08:02:40]v0008eb60
> [08:02:40]~ld
> [08:02:40]������'�s��g|��l���d`��c�����|�{��d�n��'��d`���;�l�d����
> [08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> [08:02:40]
> [08:02:40]load 0x4010f000, len 3424, room 16 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2e
> [08:02:40]load 0x3fff20b8, len 40, room 8 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2b
> [08:02:40]csum 0x2b
> [08:02:40]v0008eb60
> [08:02:40]~ld
> [08:02:40]������'��s��'<��d��l`��b�����|�{��$�o��o�$ ���s�d�$�����
> [08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> [08:02:40]
> [08:02:40]load 0x4010f000, len 3424, room 16 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2e
> [08:02:40]load 0x3fff20b8, len 40, room 8 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2b
> [08:02:40]csum 0x2b
> [08:02:40]v0008eb60
> [08:02:40]~ld
> [08:02:40]������'�s��g|��l��$ ��c����|�r��l�g���g��l ���{�$�l�����
> [08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> [08:02:40]
> [08:02:40]load 0x4010f000, len 3424, room 16 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2e
> [08:02:40]load 0x3fff20b8, len 40, room 8 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2b
> [08:02:40]csum 0x2b
> [08:02:40]v0008eb60
> [08:02:40]~ld
> [08:02:40]������n��{��'<��d��l ��#�����|�s��l�'���g��l`���;�l�l�����
> [08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> [08:02:40]
> [08:02:40]load 0x4010f000, len 3424, room 16 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2e
> [08:02:40]load 0x3fff20b8, len 40, room 8 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2b
> [08:02:40]csum 0x2b
> [08:02:40]v0008eb60
> [08:02:40]~ld
> [08:02:40]������'��{��'<��d��l`��#�����|�s��l�'���'��d`���`s�d�$�����
> [08:02:40] ets Jan  8 2013,rst cause:2, boot mode:(3,6)
> [08:02:40]
> [08:02:40]load 0x4010f000, len 3424, room 16 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2e
> [08:02:40]load 0x3fff20b8, len 40, room 8 
> [08:02:40]tail 0
> [08:02:40]chksum 0x2b
> [08:02:40]csum 0x2b
> [08:02:40]v0008eb60
> [08:02:40]~ld
> ```

Seems like some more severe boot problem. 
please (binary-search) the commit where it broke for you.
```
external_components:
  source:
    type: git
    url: https://github.com/SimonFischer04/esphome
    ref: c2a219b162c91d421fb31a5a1fbd46482fa67115
  components: [ dlms_meter ]
```

2025-04-03 11:16 UTC, pos-ei-don commented
[SimonFischer04](https://github.com/SimonFischer04)

Thank you!!! I did test this.

> Seems like some more severe boot problem. please (binary-search) the commit where it broke for you.
> 
> ```
> external_components:
>   source:
>     type: git
>     url: https://github.com/SimonFischer04/esphome
>     ref: c2a219b162c91d421fb31a5a1fbd46482fa67115
>   components: [ dlms_meter ]
> ```

This works
* 'c2a219b162c91d421fb31a5a1fbd46482fa67115 # works
* 'd3d346c51d555496b383cf2dd1718b8def8e9f50 # this next one aswell
* '6a94324b6042d7676329ddfc89089e0479301930 # stopped working

2025-04-03 11:22 UTC, ximex commented
@pos-ei-don there are 7 more commits in between of `d3d346c51d555496b383cf2dd1718b8def8e9f50` and `6a94324b6042d7676329ddfc89089e0479301930`
see here: https://github.com/esphome/esphome/pull/8009/commits

2025-04-03 11:44 UTC, pos-ei-don commented
@ximex, I cannot see them?!? Please explain.

![grafik](https://github.com/user-attachments/assets/85b0b95a-4e0c-45de-9973-c3afc88e8861)

2025-04-03 13:08 UTC, ximex commented
@pos-ei-don did you click my link?
for me it looks like this (bottom of the page)
![grafik](https://github.com/user-attachments/assets/660b9248-8e3e-407e-af5f-40607326269a)

2025-04-03 13:09 UTC, ximex commented
@pos-ei-don sorry my fault. misslooked another commit id

2025-04-04 20:08 UTC, SimonFischer04 commented
@pos-ei-don what does the ram/flash usage say at the end of compile?
```
RAM:   [=         ]  13.3% (used 43712 bytes from 327680 bytes)
Flash: [======    ]  56.5% (used 1037541 bytes from 1835008 bytes)
========================= [SUCCESS] Took 6.92 seconds =========================
```

unlikely but maybe this few more overloaded the esp8266.

2025-04-04 20:51 UTC, pos-ei-don commented
@SimonFischer04   here is the output.
```
Linking .pioenvs/smartmeter-v3b/firmware.elf
RAM:   [======    ]  56.8% (used 46540 bytes from 81920 bytes)
Flash: [======    ]  55.9% (used 584033 bytes from 1044464 bytes)
Building .pioenvs/smartmeter-v3b/firmware.bin
esp8266_copy_factory_bin([".pioenvs/smartmeter-v3b/firmware.bin"], [".pioenvs/smartmeter-v3b/firmware.elf"])
esp8266_copy_ota_bin([".pioenvs/smartmeter-v3b/firmware.bin"], [".pioenvs/smartmeter-v3b/firmware.elf"])
========================= [SUCCESS] Took 18.53 seconds =========================
INFO Successfully compiled program.
```

for comparison, the working d3d346c51d555496b383cf2dd1718b8def8e9f50 shows
```
Linking .pioenvs/smartmeter-v3b/firmware.elf
RAM:   [======    ]  56.7% (used 46476 bytes from 81920 bytes)
Flash: [======    ]  55.9% (used 583569 bytes from 1044464 bytes)
```
in my config is mqtt added/in use.

2025-04-10 21:53 UTC, SimonFischer04 commented
@pos-ei-don please try again, should be fixed.

I have no idea why but using uint32_t instead of uint8_t for the provider variable fixed it. (also tested with uint16_t - also broken).

While on it, I change to an enum, like @ximex requested before.

2025-04-11 07:15 UTC, pos-ei-don commented
[SimonFischer04](https://github.com/SimonFischer04) @SimonFischer04
thank you very much!!! Tested it, it works like a charme

I invested some AI Time to search for a reason, after 10 minutes of Mainframe-time the best suggestion
is that converting between uint8_t  and uint32_t is known for errors when done directly tand not encapsulated
using the registers. I don't know it this helps.

I just wanted to add this to be complete.
Again, Thank you a lot for digging into this DLMS component!!!


```
Linking .pioenvs/smartmeter-v3b/firmware.elf
RAM:   [======    ]  56.8% (used 46540 bytes from 81920 bytes)
Flash: [======    ]  55.9% (used 584065 bytes from 1044464 bytes)
```

2025-04-11 08:13 UTC, SimonFischer04 commented
> [SimonFischer04](https://github.com/SimonFischer04) @SimonFischer04 thank you very much!!! Tested it, it works like a charme
> 
> I invested some AI Time to search for a reason, after 10 minutes of Mainframe-time the best suggestion is that converting between uint8_t and uint32_t is known for errors when done directly tand not encapsulated using the registers. I don't know it this helps.
> 
> I just wanted to add this to be complete. Again, Thank you a lot for digging into this DLMS component!!!
> 
> ```
> Linking .pioenvs/smartmeter-v3b/firmware.elf
> RAM:   [======    ]  56.8% (used 46540 bytes from 81920 bytes)
> Flash: [======    ]  55.9% (used 584065 bytes from 1044464 bytes)
> ```

I don't know what wonderful AI ia halucinating here again ...
I'm not converting between (assign one to the other) them.
Just using either uint8_8 OR uint32_t .

Anyway, great to here it works again for you.

2025-04-11 08:16 UTC, SimonFischer04 commented
So we have confirmed:
Esp8266 works again.
Esp32 works, even with idf.

@swoboda1337 anything left todo here?

2025-04-23 20:04 UTC, SimonFischer04 commented
So ready to merge @swoboda1337?
Or is someone else responsible for that? @jesserockz please review and merge

2025-05-05 05:27 UTC, ximex approved these changes

2025-05-21 12:07 UTC, ximex commented
@SimonFischer04 could you merge dev (includes 2025.5.0) in this PR again than we do a retest and hope that it get merged than

2025-05-21 19:27 UTC, pos-ei-don commented
Please try to get this in esphome, as it fixes some other older code fragments which stopped working months ago! We really need this component for our smartmeters.

2025-05-21 20:01 UTC, swoboda1337 commented
> Please try to get this in esphome, as it fixes some other older code fragments which stopped working months ago! We really need this component for our smartmeters.

You can use it right now as an external component:
```
external_components:
  - source: github://pr#8009
    components: [ dlms_meter ]
```

2025-05-21 20:42 UTC, Augar approved these changes

2025-05-23 21:53 UTC, SimonFischer04 commented
> @SimonFischer04 could you merge dev (includes 2025.5.0) in this PR again than we do a retest and hope that it get merged than

Done, let's see.

Is final merging really all up to @jesserockz or does esphome have more maintainers?

2025-06-01 13:04 UTC, ximex commented
@SimonFischer04 is it still working for you with the latest merge?
i got strange logs. looks like my smart meter is sending wrong data or what do you think?
see the missing length between the `68.68`.
```
[14:22:42][V][dlms_meter:529]: 68.68.01.67.08.46.9B.C7.F8.20.5B.32.4C.45.CD.02.32.67.CB.EF.23.2A.B6.0D.4A.8A.BA.26.DC.FD.F2.86.29.D3.D6.9E.97.C1.F2.38.8A.62.BC.2A.B0.15.3E.8C.BC.25.9E.7F.6D.E3.20.98.0E.08.7F.89.E6.F2.9D.AE.67.7F.A8.91.20.DC.94.32.4C.02.2F.9E.7A.BA.F7.3B.4C.2A.3E.6B.16.0B.16.62.DC.5B.CB.75.7A.AB.54.BA.E9.CB.73.4F.04.7F.9B.FB.13.0D.64.07.1C.7C.54.6B.7F.B5.2F.B0.BA.43.62.45.70.3D.46.49.67.61.4F.92.2C.16.91.16.68.68.01.67.34.02.16.BA.86.52.16 (143)
[14:22:42][V][dlms_meter:052]: Parsing M-Bus frames
[14:22:42][V][dlms_meter:058]: MBUS: Parsing frame
[14:22:42][E][dlms_meter:063]: MBUS: Start bytes do not match
```

2025-06-10 05:55 UTC, madmat17 commented
@SimonFischer04, I'm running your dlsm-meter component (currently compiled as external component via your repo github://SimonFischer04/esphome@dlms-meter) and it is running like charm!

M-Bus converter: DIY board
Microcontroller: ESP32-WROOM-32D (using the template `board: nodemcu-32s`)
Grid provider: Netz-Niederoesterreich
Smart meter: KAIFA MA309M

Thanks for the effort!

2025-06-11 21:23 UTC, SimonFischer04 commented
> @SimonFischer04 is it still working for you with the latest merge? i got strange logs. looks like my smart meter is sending wrong data or what do you think? see the missing length between the `68.68`.
> 
> ```
> [14:22:42][V][dlms_meter:529]: 68.68.01.67.08.46.9B.C7.F8.20.5B.32.4C.45.CD.02.32.67.CB.EF.23.2A.B6.0D.4A.8A.BA.26.DC.FD.F2.86.29.D3.D6.9E.97.C1.F2.38.8A.62.BC.2A.B0.15.3E.8C.BC.25.9E.7F.6D.E3.20.98.0E.08.7F.89.E6.F2.9D.AE.67.7F.A8.91.20.DC.94.32.4C.02.2F.9E.7A.BA.F7.3B.4C.2A.3E.6B.16.0B.16.62.DC.5B.CB.75.7A.AB.54.BA.E9.CB.73.4F.04.7F.9B.FB.13.0D.64.07.1C.7C.54.6B.7F.B5.2F.B0.BA.43.62.45.70.3D.46.49.67.61.4F.92.2C.16.91.16.68.68.01.67.34.02.16.BA.86.52.16 (143)
> [14:22:42][V][dlms_meter:052]: Parsing M-Bus frames
> [14:22:42][V][dlms_meter:058]: MBUS: Parsing frame
> [14:22:42][E][dlms_meter:063]: MBUS: Start bytes do not match
> ```

@ximex Yes,
just tested.
Everything still works for me fine.

2025-06-11 21:37 UTC, pos-ei-don commented
Works for me aswell.

2025-06-24 04:45 UTC, benehuber commented
Compiled Version is running like charm!
Grid provider: TINETZ
Smart meter: KAIFA MA309M

2025-06-28 10:11 UTC, karllinder commented
Hi

Sorry for jumping into this, but would really like to have a support for this format in ESPHome.
Here in Sweden some of the local company's do also use DLMS/COSEM in HDLC format.
Some difference is that this units do not have encryption, and maybe a different format?
Maker is Aidon 64xx models

See for specification
https://aidon.com/wp-content/uploads/2023/06/[AIDONFD_RJ45_HAN_Interface_EN.pdf](https://aidon.com/wp-content/uploads/2023/06/AIDONFD_RJ45_HAN_Interface_EN.pdf)

My config is straight copy from this this PR, running IDF and ESPHome 2025.6.2
With decryption key set to
```
dlms_meter:
    decryption_key: "00000000000000000000000000000000"
```
have also tried "FFF..."

Do someone have time to look into this?
I would guess removing the decryption function would be the first step?

```
ESPHome version 2025.6.2 compiled on Jun 28 2025, 11:39:07
[11:40:01][D][uart_debug:114]: <<< A1:08:83:13:E6:40:01:0D:02:02:01:01:02:0B:49:4F:31:02:02:01:10:37:32:31:38:31:02:02:01:07:04:34:02:01:01:07:02:02:16:02:01:02:07:02:02:16:02:01:07:02:02:16:02:01:04:07:02:02:16:02:01:1F:07:10:02:02:02:16:02:01:07:10:02:02:16:02:01:07:10:07:02:02:16:02:01:20:07:08:02:02:16:23:02:01:34:07:08:F2:02:02:16:23:02:01:07:04:02:02:16:23:68:FD
[11:40:02][V][dlms_meter:529]: A1.08.83.13.E6.40.01.0D.02.02.01.01.02.0B.49.4F.31.02.02.01.10.37.32.31.38.31.02.02.01.07.04.34.02.01.01.07.02.02.16.02.01.02.07.02.02.16.02.01.07.02.02.16.02.01.04.07.02.02.16.02.01.1F.07.10.02.02.02.16.02.01.07.10.02.02.16.02.01.07.10.07.02.02.16.02.01.20.07.08.02.02.16.23.02.01.34.07.08.F2.02.02.16.23.02.01.07.04.02.02.16.23.68.FD (112)
[11:40:02][V][dlms_meter:052]: Parsing M-Bus frames
[11:40:02][V][dlms_meter:058]: MBUS: Parsing frame
[11:40:02][E][dlms_meter:063]: MBUS: Start bytes do not match
[11:40:02][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:02:02:16:43
[11:40:03][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.02.02.16.43 (18)
[11:40:03][V][dlms_meter:052]: Parsing M-Bus frames
[11:40:03][V][dlms_meter:058]: MBUS: Parsing frame
[11:40:03][E][dlms_meter:063]: MBUS: Start bytes do not match
[11:40:05][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:02:02:16:43
[11:40:06][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.02.02.16.43 (18)
[11:40:06][V][dlms_meter:052]: Parsing M-Bus frames
[11:40:06][V][dlms_meter:058]: MBUS: Parsing frame
[11:40:06][E][dlms_meter:063]: MBUS: Start bytes do not match
[11:40:07][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:02:02:16:43
[11:40:08][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.02.02.16.43 (18)
[11:40:08][V][dlms_meter:052]: Parsing M-Bus frames
[11:40:08][V][dlms_meter:058]: MBUS: Parsing frame
[11:40:08][E][dlms_meter:063]: MBUS: Start bytes do not match
[11:40:11][D][uart_debug:114]: <<< A1:08:83:13:E6:40:01:0D:02:02:01:01:02:0B:49:4F:31:02:02:01:10:37:32:31:38:31:02:02:01:07:04:34:02:01:01:07:02:02:16:02:01:02:07:02:02:16:02:01:07:02:02:16:02:01:04:07:02:02:16:02:01:1F:07:10:02:02:02:16:02:01:07:10:02:02:16:02:01:07:10:07:02:02:16:02:01:20:07:08:02:02:16:23:02:01:34:07:08:02:02:16:23:02:01:07:02:02:16:23:52:49
[11:40:12][V][dlms_meter:529]: A1.08.83.13.E6.40.01.0D.02.02.01.01.02.0B.49.4F.31.02.02.01.10.37.32.31.38.31.02.02.01.07.04.34.02.01.01.07.02.02.16.02.01.02.07.02.02.16.02.01.07.02.02.16.02.01.04.07.02.02.16.02.01.1F.07.10.02.02.02.16.02.01.07.10.02.02.16.02.01.07.10.07.02.02.16.02.01.20.07.08.02.02.16.23.02.01.34.07.08.02.02.16.23.02.01.07.02.02.16.23.52.49 (110)

[11:40:21][D][uart_debug:114]: <<< A1:08:83:13:E6:40:01:0D:02:02:01:01:02:0B:49:4F:31:02:02:01:10:37:32:31:38:31:02:02:01:07:04:34:02:01:01:07:98:02:02:16:02:01:02:07:02:02:16:02:01:07:02:02:16:02:01:04:07:02:02:16:02:01:1F:07:10:02:02:02:16:02:01:07:10:02:02:16:02:01:07:10:07:02:02:16:02:01:20:07:08:02:02:16:23:02:01:34:07:08:F4:02:02:16:23:02:01:07:04:02:02:16:23:F2
[11:40:22][V][dlms_meter:529]: A1.08.83.13.E6.40.01.0D.02.02.01.01.02.0B.49.4F.31.02.02.01.10.37.32.31.38.31.02.02.01.07.04.34.02.01.01.07.98.02.02.16.02.01.02.07.02.02.16.02.01.07.02.02.16.02.01.04.07.02.02.16.02.01.1F.07.10.02.02.02.16.02.01.07.10.02.02.16.02.01.07.10.07.02.02.16.02.01.20.07.08.02.02.16.23.02.01.34.07.08.F4.02.02.16.23.02.01.07.04.02.02.16.23.F2 (112)
[11:40:22][V][dlms_meter:052]: Parsing M-Bus frames
[11:40:22][V][dlms_meter:058]: MBUS: Parsing frame
[11:40:22][E][dlms_meter:063]: MBUS: Start bytes do not match
[11:40:22][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:98:02:02:16
[11:40:23][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.98.02.02.16 (18)
[11:40:23][V][dlms_meter:052]: Parsing M-Bus frames
[11:40:23][V][dlms_meter:058]: MBUS: Parsing frame
[11:40:23][E][dlms_meter:063]: MBUS: Start bytes do not match
[11:40:25][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:9B:02:02:16:F8:62
[11:40:26][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.9B.02.02.16.F8.62 (20)
[11:40:26][V][dlms_meter:052]: Parsing M-Bus frames
[11:40:26][V][dlms_meter:058]: MBUS: Parsing frame
[11:40:26][E][dlms_meter:063]: MBUS: Start bytes do not match
[11:40:27][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:9B:02:02:16:F8:62
[11:40:28][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.9B.02.02.16.F8.62 (20)
[11:40:28][V][dlms_meter:052]: Parsing M-Bus frames
[11:40:28][V][dlms_meter:058]: MBUS: Parsing frame
[11:40:28][E][dlms_meter:063]: MBUS: Start bytes do not match
[11:40:31][D][uart_debug:114]: <<< A1:08:83:13:E6:40:01:0D:02:02:01:01:02:0B:49:4F:31:02:02:01:10:37:32:31:38:31:02:02:01:07:04:34:02:01:01:07:02:02:16:02:01:02:07:02:02:16:02:01:07:02:02:16:02:01:04:07:A2:02:02:16:02:01:1F:07:10:02:02:02:16:02:01:07:10:02:02:16:02:01:07:10:07:02:02:16:02:01:20:07:08:02:02:16:23:02:01:34:07:08:02:02:16:23:02:01:07:08:02:02:16:23:0D:0E
[11:40:32][V][dlms_meter:529]: A1.08.83.13.E6.40.01.0D.02.02.01.01.02.0B.49.4F.31.02.02.01.10.37.32.31.38.31.02.02.01.07.04.34.02.01.01.07.02.02.16.02.01.02.07.02.02.16.02.01.07.02.02.16.02.01.04.07.A2.02.02.16.02.01.1F.07.10.02.02.02.16.02.01.07.10.02.02.16.02.01.07.10.07.02.02.16.02.01.20.07.08.02.02.16.23.02.01.34.07.08.02.02.16.23.02.01.07.08.02.02.16.23.0D.0E (112)
[
[11:41:31][D][uart_debug:114]: <<< A1:08:83:13:E6:40:01:0D:02:02:01:01:02:0B:49:4F:31:02:02:01:10:37:32:31:38:31:02:02:01:07:04:34:02:01:01:07:02:02:16:02:01:02:07:02:02:16:02:01:07:02:02:16:02:01:04:07:02:02:16:02:01:1F:07:10:02:02:02:16:02:01:07:10:02:02:16:02:01:07:10:02:02:16:02:01:20:07:08:02:02:16:23:02:01:34:07:02:02:02:16:23:02:01:07:01:02:02:16:23
[11:41:32][V][dlms_meter:529]: A1.08.83.13.E6.40.01.0D.02.02.01.01.02.0B.49.4F.31.02.02.01.10.37.32.31.38.31.02.02.01.07.04.34.02.01.01.07.02.02.16.02.01.02.07.02.02.16.02.01.07.02.02.16.02.01.04.07.02.02.16.02.01.1F.07.10.02.02.02.16.02.01.07.10.02.02.16.02.01.07.10.02.02.16.02.01.20.07.08.02.02.16.23.02.01.34.07.02.02.02.16.23.02.01.07.01.02.02.16.23 (108)

```

2025-06-28 19:50 UTC, SimonFischer04 commented
> Hi
> 
> Sorry for jumping into this, but would really like to have a support for this format in ESPHome. Here in Sweden some of the local company's do also use DLMS/COSEM in HDLC format. Some difference is that this units do not have encryption, and maybe a different format? Maker is Aidon 64xx models
> 
> See for specification [https://aidon.com/wp-content/uploads/2023/06/[AIDONFD_RJ45_HAN_Interface_EN.pdf](https://aidon.com/wp-content/uploads/2023/06/AIDONFD_RJ45_HAN_Interface_EN.pdf)](https://aidon.com/wp-content/uploads/2023/06/%5BAIDONFD_RJ45_HAN_Interface_EN.pdf%5D(https://aidon.com/wp-content/uploads/2023/06/AIDONFD_RJ45_HAN_Interface_EN.pdf))
> 
> My config is straight copy from this this PR, running IDF and ESPHome 2025.6.2 With decryption key set to
> 
> ```
> dlms_meter:
>     decryption_key: "00000000000000000000000000000000"
> ```
> 
> have also tried "FFF..."
> 
> Do someone have time to look into this? I would guess removing the decryption function would be the first step?
> 
> ```
> ESPHome version 2025.6.2 compiled on Jun 28 2025, 11:39:07
> [11:40:01][D][uart_debug:114]: <<< A1:08:83:13:E6:40:01:0D:02:02:01:01:02:0B:49:4F:31:02:02:01:10:37:32:31:38:31:02:02:01:07:04:34:02:01:01:07:02:02:16:02:01:02:07:02:02:16:02:01:07:02:02:16:02:01:04:07:02:02:16:02:01:1F:07:10:02:02:02:16:02:01:07:10:02:02:16:02:01:07:10:07:02:02:16:02:01:20:07:08:02:02:16:23:02:01:34:07:08:F2:02:02:16:23:02:01:07:04:02:02:16:23:68:FD
> [11:40:02][V][dlms_meter:529]: A1.08.83.13.E6.40.01.0D.02.02.01.01.02.0B.49.4F.31.02.02.01.10.37.32.31.38.31.02.02.01.07.04.34.02.01.01.07.02.02.16.02.01.02.07.02.02.16.02.01.07.02.02.16.02.01.04.07.02.02.16.02.01.1F.07.10.02.02.02.16.02.01.07.10.02.02.16.02.01.07.10.07.02.02.16.02.01.20.07.08.02.02.16.23.02.01.34.07.08.F2.02.02.16.23.02.01.07.04.02.02.16.23.68.FD (112)
> [11:40:02][V][dlms_meter:052]: Parsing M-Bus frames
> [11:40:02][V][dlms_meter:058]: MBUS: Parsing frame
> [11:40:02][E][dlms_meter:063]: MBUS: Start bytes do not match
> [11:40:02][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:02:02:16:43
> [11:40:03][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.02.02.16.43 (18)
> [11:40:03][V][dlms_meter:052]: Parsing M-Bus frames
> [11:40:03][V][dlms_meter:058]: MBUS: Parsing frame
> [11:40:03][E][dlms_meter:063]: MBUS: Start bytes do not match
> [11:40:05][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:02:02:16:43
> [11:40:06][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.02.02.16.43 (18)
> [11:40:06][V][dlms_meter:052]: Parsing M-Bus frames
> [11:40:06][V][dlms_meter:058]: MBUS: Parsing frame
> [11:40:06][E][dlms_meter:063]: MBUS: Start bytes do not match
> [11:40:07][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:02:02:16:43
> [11:40:08][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.02.02.16.43 (18)
> [11:40:08][V][dlms_meter:052]: Parsing M-Bus frames
> [11:40:08][V][dlms_meter:058]: MBUS: Parsing frame
> [11:40:08][E][dlms_meter:063]: MBUS: Start bytes do not match
> [11:40:11][D][uart_debug:114]: <<< A1:08:83:13:E6:40:01:0D:02:02:01:01:02:0B:49:4F:31:02:02:01:10:37:32:31:38:31:02:02:01:07:04:34:02:01:01:07:02:02:16:02:01:02:07:02:02:16:02:01:07:02:02:16:02:01:04:07:02:02:16:02:01:1F:07:10:02:02:02:16:02:01:07:10:02:02:16:02:01:07:10:07:02:02:16:02:01:20:07:08:02:02:16:23:02:01:34:07:08:02:02:16:23:02:01:07:02:02:16:23:52:49
> [11:40:12][V][dlms_meter:529]: A1.08.83.13.E6.40.01.0D.02.02.01.01.02.0B.49.4F.31.02.02.01.10.37.32.31.38.31.02.02.01.07.04.34.02.01.01.07.02.02.16.02.01.02.07.02.02.16.02.01.07.02.02.16.02.01.04.07.02.02.16.02.01.1F.07.10.02.02.02.16.02.01.07.10.02.02.16.02.01.07.10.07.02.02.16.02.01.20.07.08.02.02.16.23.02.01.34.07.08.02.02.16.23.02.01.07.02.02.16.23.52.49 (110)
> 
> [11:40:21][D][uart_debug:114]: <<< A1:08:83:13:E6:40:01:0D:02:02:01:01:02:0B:49:4F:31:02:02:01:10:37:32:31:38:31:02:02:01:07:04:34:02:01:01:07:98:02:02:16:02:01:02:07:02:02:16:02:01:07:02:02:16:02:01:04:07:02:02:16:02:01:1F:07:10:02:02:02:16:02:01:07:10:02:02:16:02:01:07:10:07:02:02:16:02:01:20:07:08:02:02:16:23:02:01:34:07:08:F4:02:02:16:23:02:01:07:04:02:02:16:23:F2
> [11:40:22][V][dlms_meter:529]: A1.08.83.13.E6.40.01.0D.02.02.01.01.02.0B.49.4F.31.02.02.01.10.37.32.31.38.31.02.02.01.07.04.34.02.01.01.07.98.02.02.16.02.01.02.07.02.02.16.02.01.07.02.02.16.02.01.04.07.02.02.16.02.01.1F.07.10.02.02.02.16.02.01.07.10.02.02.16.02.01.07.10.07.02.02.16.02.01.20.07.08.02.02.16.23.02.01.34.07.08.F4.02.02.16.23.02.01.07.04.02.02.16.23.F2 (112)
> [11:40:22][V][dlms_meter:052]: Parsing M-Bus frames
> [11:40:22][V][dlms_meter:058]: MBUS: Parsing frame
> [11:40:22][E][dlms_meter:063]: MBUS: Start bytes do not match
> [11:40:22][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:98:02:02:16
> [11:40:23][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.98.02.02.16 (18)
> [11:40:23][V][dlms_meter:052]: Parsing M-Bus frames
> [11:40:23][V][dlms_meter:058]: MBUS: Parsing frame
> [11:40:23][E][dlms_meter:063]: MBUS: Start bytes do not match
> [11:40:25][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:9B:02:02:16:F8:62
> [11:40:26][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.9B.02.02.16.F8.62 (20)
> [11:40:26][V][dlms_meter:052]: Parsing M-Bus frames
> [11:40:26][V][dlms_meter:058]: MBUS: Parsing frame
> [11:40:26][E][dlms_meter:063]: MBUS: Start bytes do not match
> [11:40:27][D][uart_debug:114]: <<< 2A:08:83:13:04:13:E6:40:01:01:02:01:01:07:9B:02:02:16:F8:62
> [11:40:28][V][dlms_meter:529]: 2A.08.83.13.04.13.E6.40.01.01.02.01.01.07.9B.02.02.16.F8.62 (20)
> [11:40:28][V][dlms_meter:052]: Parsing M-Bus frames
> [11:40:28][V][dlms_meter:058]: MBUS: Parsing frame
> [11:40:28][E][dlms_meter:063]: MBUS: Start bytes do not match
> [11:40:31][D][uart_debug:114]: <<< A1:08:83:13:E6:40:01:0D:02:02:01:01:02:0B:49:4F:31:02:02:01:10:37:32:31:38:31:02:02:01:07:04:34:02:01:01:07:02:02:16:02:01:02:07:02:02:16:02:01:07:02:02:16:02:01:04:07:A2:02:02:16:02:01:1F:07:10:02:02:02:16:02:01:07:10:02:02:16:02:01:07:10:07:02:02:16:02:01:20:07:08:02:02:16:23:02:01:34:07:08:02:02:16:23:02:01:07:08:02:02:16:23:0D:0E
> [11:40:32][V][dlms_meter:529]: A1.08.83.13.E6.40.01.0D.02.02.01.01.02.0B.49.4F.31.02.02.01.10.37.32.31.38.31.02.02.01.07.04.34.02.01.01.07.02.02.16.02.01.02.07.02.02.16.02.01.07.02.02.16.02.01.04.07.A2.02.02.16.02.01.1F.07.10.02.02.02.16.02.01.07.10.02.02.16.02.01.07.10.07.02.02.16.02.01.20.07.08.02.02.16.23.02.01.34.07.08.02.02.16.23.02.01.07.08.02.02.16.23.0D.0E (112)
> [
> [11:41:31][D][uart_debug:114]: <<< A1:08:83:13:E6:40:01:0D:02:02:01:01:02:0B:49:4F:31:02:02:01:10:37:32:31:38:31:02:02:01:07:04:34:02:01:01:07:02:02:16:02:01:02:07:02:02:16:02:01:07:02:02:16:02:01:04:07:02:02:16:02:01:1F:07:10:02:02:02:16:02:01:07:10:02:02:16:02:01:07:10:02:02:16:02:01:20:07:08:02:02:16:23:02:01:34:07:02:02:02:16:23:02:01:07:01:02:02:16:23
> [11:41:32][V][dlms_meter:529]: A1.08.83.13.E6.40.01.0D.02.02.01.01.02.0B.49.4F.31.02.02.01.10.37.32.31.38.31.02.02.01.07.04.34.02.01.01.07.02.02.16.02.01.02.07.02.02.16.02.01.07.02.02.16.02.01.04.07.02.02.16.02.01.1F.07.10.02.02.02.16.02.01.07.10.02.02.16.02.01.07.10.02.02.16.02.01.20.07.08.02.02.16.23.02.01.34.07.02.02.02.16.23.02.01.07.01.02.02.16.23 (108)
> ```

At first look the protocol seems different. In the component here each mbus message starts with 68. Your output starts with A1, but according to the docs you sent it's still mbus transport. Do you have any more specifications / docs? The provided one does not really help / give me a clue how the protocol works there.

But please create an issue for this in my repo: https://github.com/SimonFischer04/esphome, to discuss further if this can also be supported. Let's keep the pr here focused on review. It already has a lot of comments anyways.

2025-08-24 07:22 UTC, mikemhlnr commented
Hallo guys,

Posted in another thread [https://github.com/SimonFischer04/esphome/issues/1](url) since the last update of esphome 2025.8.0 the old code no longer works.

So i tried to "update" it, but i run in some issues, also because i dont know much about the code or how it is put together.

At this point it looks like this.

`captive_portal:

# Enable logging
logger:
  level: VERBOSE
  tx_buffer_size: 2048

external_components:
  source:
    type: git
    url: https://github.com/SimonFischer04/esphome
    ref: c2a219b162c91d421fb31a5a1fbd46482fa67115
  components: [ dlms_meter ]

uart:
  rx_pin: GPIO1 # change this to the pin where you connected the mbus adapter board
  tx_pin: GPIO3
  baud_rate: 2400
  rx_buffer_size: 2048 # Needed to receive the large packets send by the smart meter
  data_bits: 8
  stop_bits: 1
  id: mbus

dlms_meter:
  decryption_key: "xxxKEYxxx" # change this to your decryption key!
  provider: netznoe # (optional) key - only set if using evn

sensor:
  - platform: dlms_meter
    voltage_l1:
      name: "Voltage L1"
    voltage_l2:
      name: "Voltage L2"
    voltage_l3:
      name: "Voltage L3"
    current_l1:
      name: "Current L1"
    current_l2:
      name: "Current L2"
    current_l3:
      name: "Current L3"
    active_power_plus:
      name: "Active power taken from grid"
    active_power_minus:
      name: "Active power put into grid"
    active_energy_plus:
      name: "Active energy taken from grid"
    active_energy_minus:
      name: "Active energy put into grid"
    # EVN
    power_factor:
      name: "Power Factor"

text_sensor:
  - platform: dlms_meter
    timestamp:
      name: "timestamp"
    # EVN
    meternumber:
      name: "meterNumber"`

and the log shows something like this

`[18:56:43][V][dlms_meter:529]: 39.7B.38.6C.A8 (5)
[18:56:43][V][dlms_meter:052]: Parsing M-Bus frames
[18:56:43][V][dlms_meter:058]: MBUS: Parsing frame
[18:56:43][E][dlms_meter:063]: MBUS: Start bytes do not match
[18:56:44][V][dlms_meter:529]: 39.5B.89.28.6C (5)
[18:56:44][V][dlms_meter:052]: Parsing M-Bus frames
[18:56:44][V][dlms_meter:058]: MBUS: Parsing frame
[18:56:44][E][dlms_meter:063]: MBUS: Start bytes do not match
[18:56:45][V][dlms_meter:529]: 19.7F.11.32.08 (5)
[18:56:45][V][dlms_meter:052]: Parsing M-Bus frames
[18:56:45][V][dlms_meter:058]: MBUS: Parsing frame
[18:56:45][E][dlms_meter:063]: MBUS: Start bytes do not match`

Would be nice if anyone can give me some advice, what i am doing wrong.

best regards 
mike

2025-08-24 07:30 UTC, pos-ei-don commented
Your link is dead.
It works herefor me perfectly.

2025-08-24 07:42 UTC, mikemhlnr commented
Updated the link.

I also switched the buffer size from stock 1024 to 2048 and tried some old settings from the domistyle code.
nothing works... :(

2025-09-05 17:50 UTC, evlo commented
Would this also work for meter that says is DLMS and jsut pushes packet to the rs485 interface that look like this
0F 00 00 00 03 00 02 02 16 01 01 16 02 02 00 01 00 00 60 01 01 FF 02 09 0A
31 32 33 34 35 36 37 38 39 30 02 02 00 46 00 00 60 03 0A
03 16 01 02 02 00 47 00 00 11 00 00 FF 03 06 00 00 00 00 02 02 00 46 00 01 60 03 0A
FF 03 16 01 02 02 00 46 00 02 60 03 0A
FF 03 16 00 02 02 00 46 00 03 60 03 0A
FF 03 16 01 02 02 00 46 00 04 60 03 0A
FF 03 16 00 02 02 00 01 00 00 60 0E 00 FF 02 09 02 54 32 02 02 00 03 01 00 01 07 00 FF 02 06 00 00 01 69 02 02 00 03 01 00 15 07 00 FF 02 06 00 00 00 0B 02 02 00 03 01 00 29 07 00 FF 02 06 00 00 01 4A 02 02 00 03 01 00 3D 07 00 FF 02 06 00 00 00 14 02 02 00 03 01 00 02 07 00 FF 02 06 00 00 00 00 02 02 00 03 01 00 16 07 00 FF 02 06 00 00 00 00 02 02 00 03 01 00 2A 07 00 FF 02 06 00
00 00 00 02 02 00 03 01 00 3E 07 00 FF 02 06 00 00 00 00 02 02 00 03 01 00 01 08 00 FF 02 06 00 00 51 52 02 02 00 03 01 00 01 08 01 FF 02 06 00 00 21 67 02 02 00 03 01 00 01 08 02 FF 02 06 00 00 2F EA 02 02 00 03 01 00 01 08 03 FF 02 06 00 00 00 00 02 02 00 03 01 00 01 08 04 FF 02 06 00 00 00 00 02 02 00 03 01 00 02 08 00 FF 02 06 00 00 09 03

2025-10-09 18:43 UTC, SimonFischer04 commented
@swoboda1337 
Unfortunately, there is nothing to split about this PR for the component.
https://developers.esphome.io/contributing/submitting-your-work/#how-to-approach-large-submissions does not help either.

This is already only the "base".
I don't think it makes sense to just submit half of the code as another PR, where the first one is useless alone?

Secondly, a lot of the additions are tests, constants and protocol information / comments.
Furthermore, haven't you already reviewed months ago?

Would really appreciate some guidance on how to proceed. How to split the PR, if that's really required.

2025-10-11 06:17 UTC, PolarGoose commented
> This PR is too large with 1202 line changes (excluding tests). Please consider breaking it down into smaller, focused PRs to make review easier and reduce the risk of conflicts.

@SimonFischer04,
You can do the same trick that the DSMR EspHome component does:
Split all the receiving state machine and parsing logic into a PlatformIO library. Cover it with tests.
(Note: the receiving state machine is currently part of the ESPHome DSMR component, but it doesn't need to be this way)

You can look at the [arduino-dsmr-2](https://github.com/PolarGoose/arduino-dsmr-2) as a reference.
In the same way, you can separate DLMS parsing and receiving logic from the ESPHome codebase.

2025-10-11 07:13 UTC, SimonFischer04 commented
> Split all the receiving state machine and parsing logic into a PlatformIO library.

@PolarGoose 
Yeah, good idea, but they don't want this.

https://developers.esphome.io/contributing/code/#use-of-external-libraries

```
In general, we try to avoid use of external libraries.

If the component you're developing has a simple communication interface, please consider implementing it natively in ESPHome.

...
```

Also, this does not change anything about review.
Just moving code parts somewhere else means they need to review it somewhere else ...
(or not review it at all and have untrusted external dependencies ...  - which need to be kept up to date, ...)

2025-10-11 20:48 UTC, PolarGoose commented
@SimonFischer04,

> Yeah, good idea, but they don't want this.

Ok, sorry, I didn't know that.

By the way, I looked into the code. You say it fixes [DSMR - Polish meters #6500
](https://github.com/esphome/issues/issues/6500), but the packet mentioned there starts with `2F` and ends with `0A`. However, in your implementation, I see that you use different start and stop bytes:
```
static const uint8_t START_BYTE_LONG_FRAME = 0x68;
static const uint8_t STOP_BYTE = 0x16;
```

Also, what reference documents did you use that describe this protocol?

2025-10-11 21:49 UTC, PolarGoose commented
Sorry, another question:
What is the difference between this implementation and another project [latonita/esphome-dlms-cosem](https://github.com/latonita/esphome-dlms-cosem) ?

2025-10-12 07:49 UTC, SimonFischer04 commented
> Sorry, another question: What is the difference between this implementation and another project [latonita/esphome-dlms-cosem](https://github.com/latonita/esphome-dlms-cosem) ?

@PolarGoose 
please, let's leave other discussion out of this PR.
Keep the discussion here focused about review, already long enough this thread ...

Head over to my repo, if you want to discuss other things.

But TLDR: better to ask there why one should use theirs. This component did exist before that one and is way simpler to use and the other does not support the meters supported here.

2025-10-30 13:28 UTC, SimonFischer04 commented
@swoboda1337 sry to ask again, but anything still missing here for this to get merged?

2025-10-30 22:50 UTC, swoboda1337 requested changes
Here are the critical issues from Claude's review, many nitpicks too if you ask it: 
  1. C++ Implementation (dlms_meter.cpp/h)

  Critical Issues:

  🔴 Memory Safety - Fixed-size buffers with dynamic data (dlms_meter.cpp:~453):
  char timestamp[27];  // 0000-00-00T00:00:00Z
  This is adequate for ISO 8601 format, but worth checking bounds.

  🔴 Unchecked vector access (line 159+):
  uint8_t frame_length = this->receive_buffer_[frame_offset + MBUS_LENGTH1_OFFSET];
  - No bounds checking before vector access
  - Could crash if malformed data received
  - Recommendation: Use .at() for bounds-checked access or add explicit size checks

  🔴 Recent ESP8266 Boot Loop Issue (from comments):
  - User @pos-ei-don reported ESP8266 stopped working after recent changes
  - Continuous reset loop suggests stack overflow or memory corruption
  - Need to investigate if recent refactoring introduced memory issues

  Medium Priority:

  🟡 Large loop() function (~500 lines):
  - Monolithic parsing logic in single function
  - @ximex suggested splitting into: parse_mbus(), parse_dlms(), decrypt(), decode_obis()
  - Would improve testability and maintainability

  🟡 Error handling inconsistency:
  - Most errors call abort_() which just clears buffer
  - No status indication to user when errors occur repeatedly
  - Should use status_set_warning() for persistent issues

  🟡 Hardcoded magic numbers:
  current_position += 4;  // EVN specific
  current_position += 6;  // Generic
  Should use named constants

2025-10-30 22:50 UTC, swoboda1337 commented on tests/components/dlms_meter/common.yaml
> +  rx_buffer_size: 1024   # Needed to receive the large packets send by the smart meter
Tests need to be updated to use the common bus stuff.

2025-10-30 22:50 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +          this->receive_buffer_[frame_offset + MBUS_START2_OFFSET] != START_BYTE_LONG_FRAME) {
No bounds checks needed here? Or in the following lines? The while loop check only guarantees one byte.

2025-10-30 22:50 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (this->receive_buffer_.size() - frame_offset < frame_length + 3) {
why +3?

2025-10-30 22:50 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +            sprintf(timestamp, "%04u-%02u-%02uT%02u:%02u:%02uZ", year, month, day, hour, minute, second);
If year is 65000 will it overrun the buffer? Need to add a bounds check maybe use snprintf too? It is possible for this to be 27 characters plus one for the null which is 28

2025-10-30 23:10 UTC, swoboda1337 requested changes

2025-10-30 23:10 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms.h
> +static const uint8_t TIMESTAMP_DATETIME = 0x0C;
Why not use constexpr?

2025-10-30 23:10 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +  ESP_LOGCONFIG(TAG, "read_timeout: %u", this->read_timeout_);
Dump config should follow the existing components. Need to use a single print

2025-10-30 23:10 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +}
Loop is too long maybe create some functions to make it easier to read?

2025-10-31 03:54 UTC, pos-ei-don commented
> * User @pos-ei-don reported ESP8266 stopped working after recent changes

No Problem here, I had this with an earlier Version, but my problem hot fixed! I highly need this Module, it worka perfekt stable for my MBus-meter .

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#include <bearssl/bearssl.h>
Why not use `mbedtls` everywhere?

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#if defined(USE_ESP8266_FRAMEWORK_ARDUINO)
The decryption doesn't use the auth key and the tag.
The CRC or checksum is not "cryptographically safe", or something. Thus, the idea is to check the checksum and the tag.

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (this->receive_buffer_[frame_offset + MBUS_START1_OFFSET] != START_BYTE_LONG_FRAME ||
I guess if you receive only 1 or 2 bytes, you will get an out-of-bounds error.

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    this->last_read_ = current_time;
This is probably not what you want.
You save time when the `loop()` method starts.
It should be `this->last_read_ = millis()`

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (this->receive_buffer_.size() - frame_offset < frame_length + 3) {
This check is incorrect. You check that you get at least `frame_length + 3` bytes. But below you have
`this->receive_buffer_[frame_offset + frame_length + MBUS_HEADER_INTRO_LENGTH + MBUS_FOOTER_LENGTH - 1]`
It accesses bytes beyond the limit that was checked.

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +              4;  // Skip additional data and additional break; this will jump out of bounds on last frame
> this will jump out of bounds on last frame

Hey what? :)

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +              ESP_LOGE("DLMS", "Invalid timestamp values: %04u-%02u-%02uT%02u:%02u:%02uZ", year, month, day, hour,
"DLMS" -> TAG

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    this->publish_sensors(data);
If some fields are not present, you will still publish 0 or `""`.

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms.h
> +        Encrypted Payload
The last 12 bytes of `Encrypted Payload` is a TAG for `AES-128-GCM` encryption.

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/mbus.h
> +|                      Checksum                      |  \
`8-bit additive checksum`

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    this->receive_buffer_.push_back(c);
This will cause an `out of memory` crash if there is noise on the line. In that case, you will constantly receive garbage and never detect the end of a packet.

2025-11-03 10:55 UTC, PolarGoose commented on esphome/components/dlms_meter/mbus.h
> + * This component currently only uses Long Frame.
Are we sure that Smart meters don't use short frames or any other frames?

2025-11-03 11:20 UTC, PolarGoose commented on esphome/components/dlms_meter/mbus.h
> +|               Start Character [0x68]               |  \
What document is this structure taken from?

2025-11-03 11:20 UTC, PolarGoose commented on esphome/components/dlms_meter/obis.h
> +  NULL_DATA = 0x00,
What document describes these values and how data is packed inside the DLMS payload?

2025-11-03 14:01 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#include <bearssl/bearssl.h>
This is 8266 does it have the same mbedtls headers?

2025-11-03 14:48 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#include <bearssl/bearssl.h>
@swoboda1337,

You are correct. I made a wrong assumption. 8266 uses `platformio/framework-arduinoespressif8266`. It doesn't include `mbedtls` but contains `bearssl` instead.
It is problematic because it will require running tests on at least one `8266` and one `ESP32` board.

From all EspHome supported boards, 8266 is the only one whose SDK doesn't have `mbedtls`. Maybe it can be fixed by explicitly adding `mbedtls` as a dependency to 8266 boards?

2025-11-03 14:55 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#include <bearssl/bearssl.h>
Another option is to use `polargoose/Crypto-no-arduino` that is used in this pull request: 

https://github.com/esphome/esphome/pull/11036

Then the implementation will be the same for all boards.

2025-11-03 15:01 UTC, SimonFischer04 commented
@PolarGoose @swoboda1337 thanks for your personal reviews.
Will probably take a bit to go through everything and implement suggested changes where appropriate.

2025-11-03 15:16 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#include <bearssl/bearssl.h>
This is outside of the scope of this PR. I do not want to use external libraries, would rather use bearssl on 8266.

2025-11-03 16:00 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#include <bearssl/bearssl.h>
Ok, then it's probably better to create a separate class `Aes128GcmDecryptor` and keep the `ifdef` stuff there.

2025-11-03 16:03 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#include <bearssl/bearssl.h>
This is the implementation using Mbedtls:
```
class MbedTlsAes128GcmDecryptor final : NonCopyableAndNonMovable {
    mbedtls_gcm_context gcm;

  public:
    MbedTlsAes128GcmDecryptor() { mbedtls_gcm_init(&gcm); }

    bool set_encryption_key(const std::span<const uint8_t> key) { return mbedtls_gcm_setkey(&gcm, MBEDTLS_CIPHER_ID_AES, key.data(), 128) == 0; }

    bool decrypt(std::span<const uint8_t> iv, std::span<const uint8_t> ciphertext, std::span<const uint8_t> tag, std::span<char> decrypted_output_buffer) {
      // aad = AdditionalAuthenticatedData = SecurityControlField + AuthenticationKey.
      //   SecurityControlField is always 0x30.
      //   AuthenticationKey = "00112233445566778899AABBCCDDEEFF". It is hardcoded and is the same for all DSMR devices.
      constexpr uint8_t aad[] = {0x30, 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF};

      const auto& res = mbedtls_gcm_auth_decrypt(&gcm, ciphertext.size(), iv.data(), iv.size(), aad, std::size(aad), tag.data(), tag.size(), ciphertext.data(),
                                                 reinterpret_cast<unsigned char*>(decrypted_output_buffer.data()));
      return res == 0;
    }

    ~MbedTlsAes128GcmDecryptor() { mbedtls_gcm_free(&gcm); }
  };
```

2025-11-03 16:13 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#include <bearssl/bearssl.h>
It's only one ifdef, I am fine this for now. 

If something is added in core or in another component it can be moved to use that at a later point.

2025-11-03 16:22 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#include <bearssl/bearssl.h>
@swoboda1337,

Ok, I don't mean you need to change the EspHome source code. I meant, just moving the encryption into a separate "function" inside the `dlms_meter` component. The code is easier to read this way. But it needs to be a class then, because it is nice to have a destructor for exception safety.

2025-11-03 16:24 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#include <bearssl/bearssl.h>
Ok, yeah for sure, should be moved to a separate function at least. 

I already requested the loop to be broken up as its way too long.

2025-11-04 10:14 UTC, PolarGoose commented
@SimonFischer04,

You have resolved many of my review remarks without any comment or code changes.

2025-11-04 10:50 UTC, SimonFischer04 commented
> @SimonFischer04,
> 
> You have resolved many of my review remarks without any comment or code changes.

All of the resolved ones should have comments.?

2025-11-04 10:55 UTC, PolarGoose commented
For example, this remark is resolved without any comment:
<img width="1546" height="490" alt="image" src="https://github.com/user-attachments/assets/714c936a-c550-409c-a679-3f96a7a19dee" />

2025-11-04 13:55 UTC, PolarGoose commented
Just in case you need some reference code:
I have implemented a decryption of DLMS packets in [esphome-libs/dsmr_parser](https://github.com/esphome-libs/dsmr_parser/tree/main/src/dsmr_parser) files: `dlms_packet_decryptor.h`, `aes128gcm_mbedtls.h`, and `aes128gcm_bearssl.h`.
It supports MbedTLS and BearSSL.

I suspect that the DLMS packet in this `dlms_meter` component is exactly the same as in the DSMR protocol. The only difference is that here the decrypted data is binary, but in DSMR, it is text.

2025-11-04 14:27 UTC, SimonFischer04 commented
> For example, this remark is resolved without any comment:
> <img width="1546" height="490" alt="image" src="https://github.com/user-attachments/assets/714c936a-c550-409c-a679-3f96a7a19dee" />
> 

Hm, interesting.
Maybe i have posted them as review comments and forgot to submit review.

Sorry, will look at it later when i'm home

2025-11-04 14:59 UTC, PolarGoose commented
> Maybe i have posted them as review comments and forgot to submit review.

Yes, it is a strange thing with Github, a lot of people are angry about it for many years [Make it clear that "PENDING" comments have to be submitted #10369](https://github.com/orgs/community/discussions/10369)

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.h
> +static const uint8_t PROVIDER_NETZNOE = 1;
Haven't figured out how to properly work with codegen and enums.
But all the other constants are also uint8_t so i kept it simple.

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.h
> +#endif
fixed

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +  while (available()) {  // Read while data is available
fixed

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      bool meterNumberFound = false;
fixed

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      bool timestampFound = false;
fixed

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    mbedtls_gcm_init(&this->aes_);
fixed. 
moved mbedtls_gcm_context to cpp and renamed

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/mbus.h
> +|               Start Character [0x68]               |  \
The ascii image as such was contributed by someone else to my repo.

Unfortunately the publically available resources aren't the best.
Most information was scrambled together from multiple grid provider docs:
- https://www.netz-noe.at/Download-(1)/Smart-Meter/218_9_SmartMeter_Kundenschnittstelle_lektoriert_14.aspx
- https://www.tinetz.at/uploads/tx_bh/101/tinetz_smart-meter_beschreibung-kundenschnittstelle_001.pdf
- https://www.salzburgnetz.at/content/dam/salzburgnetz/dokumente/stromnetz/Technische-Beschreibung-Kundenschnittstelle.pdf

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/obis.h
> +  NULL_DATA = 0x00,
The definition came from the initial custom component implemention from DomiStyle: https://github.com/DomiStyle/esphome-dlms-meter/blob/master/espdm_obis.h

But a quick google search f.e. shows up page 16: https://www.cs.ru.nl/~marko/onderwijs/bss/SmartMeter/Excerpt_BB7.pdf

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/mbus.h
> + * This component currently only uses Long Frame.
Haven't seen any so far.
With the PR already being so big and also recently lots of optimizations to esphome, I would like to avoid blowing up this pr even more and wasting flash space + cpu cycles and increasing maintenance effort for implementing unnecessary features.

If smartmeters are found that require it, it can always be implemented later in another pr.

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +              4;  // Skip additional data and additional break; this will jump out of bounds on last frame
Yes,
and therefore cancel the loop to not loop indefinitely:
while (current_position < message_length) {

:D

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/mbus.h
> +|                      Checksum                      |  \
checksum was already discussed above.

Checksum is a bit tricky, if you want, feel free to send a follow-up pr.

There are already lots of checks in here, so should be fine for now.

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms.h
> +        Encrypted Payload
Authentication data isn't used by the smartmeters here, so we pass NULL to:
mbedtls_gcm_auth_decrypt(&gcm_ctx, message_length, iv, sizeof(iv), NULL, 0, NULL, 0,
                             &mbus_payload[header_offset + DLMS_PAYLOAD_OFFSET], plaintext);

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    this->publish_sensors(data);
Actually prefer it this way:
smartmeters have a defined set of fields they should ALWAYS send.
If one is missing in (one) frame you can notice and complain to your provider.

Just not publishing data will let you have values that could be long outdated and possibly make wrong automation decisions based on your "current" power consumption.

On the other hand, if you smartmeter is per spec missing one field, you can just remove the sensor from the yaml and it will newer publish. (actually not even compile in the sensors and save flash space).
That's the whole idea behind the dynamic code templating from config. (inspired by the dsmr component)

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +#if defined(USE_ESP8266_FRAMEWORK_ARDUINO)
already mentioned on the other review threads about auth key and checksum

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +              ESP_LOGE("DLMS", "Invalid timestamp values: %04u-%02u-%02uT%02u:%02u:%02uZ", year, month, day, hour,
Good catch, thanks.
Fixed

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    this->last_read_ = current_time;
fixed

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    this->receive_buffer_.push_back(c);
We are still talking about UART, not an analog input here.

And it's still "while (this->available()". So while data still in the esps uart buffer.
It's not a loop like "until mbus bytes found".

If the smartmeter is really sending garbage faster than the esp can read and put it into this buffer, then i think there are bigger issues and you won't get useful data anyway (random bytes trying to be interpreted as mbus, ...). 
If this happens please tell your provider: WTF, fix your shit.

For normal read issues, this is exactly why there is a read_timeout_ bellow.

Also: lots of other components are just doing while (this->available()) {.
This seems basically like the standard how its done.

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +  ESP_LOGCONFIG(TAG, "read_timeout: %u", this->read_timeout_);
When I started with the component over a year ago, I did look at other components how its done.
Apparently this changed now: https://github.com/esphome/esphome/pull/9026
Sry, didn't know that until now.

Changed now, thanks for the info.

2025-11-04 17:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +  ESP_LOGCONFIG(TAG, "read_timeout: %u", this->read_timeout_);
the one other ESP_LOGVV is still required, as it uses another loglevel than ESP_LOGCONFIG

2025-11-04 18:16 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +            sprintf(timestamp, "%04u-%02u-%02uT%02u:%02u:%02uZ", year, month, day, hour, minute, second);
the if check was meant for exactly that, to prevent the overflow.

but forgot the abort and return.

Fixed now

2025-11-04 19:23 UTC, SimonFischer04 commented on tests/components/dlms_meter/common.yaml
> +  rx_buffer_size: 1024   # Needed to receive the large packets send by the smart meter
done.

While on it, I also re-added the c6 tests removed earlier. Because looks like c6 is now supported by esphome test framework

2025-11-04 19:53 UTC, pos-ei-don commented
The current version still works as expected, using esphome 2025.10.4 on esp8266.

2025-11-04 20:01 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms.h
> +static const uint8_t TIMESTAMP_DATETIME = 0x0C;
https://github.com/DomiStyle/esphome-dlms-meter/blob/master/espdm_dlms.h already defined everything as static const int.
After one review here, I changed it to static const uint8_t - also no complaints about using constexpr back then.

While creating the component i checked how other components are doing it and at the time not a single component did use constexpr uint8_t. (very few have changed now)

So I did not think about changing anything (and I'm not that deep into c++ to know if that actually gives any benefit that the compiler cant optimise anyway because its const).

---

Anyways, changed now.

2025-11-04 20:20 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (this->receive_buffer_[frame_offset + MBUS_START1_OFFSET] != START_BYTE_LONG_FRAME ||
fixed

2025-11-04 20:23 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +          this->receive_buffer_[frame_offset + MBUS_START2_OFFSET] != START_BYTE_LONG_FRAME) {
added a bound check.
1 is check fine also for the following lines, because: MBUS_HEADER_INTRO_LENGTH = 4
The imbus intro consists of (start+length+length+start). Or in constants:
MBUS_START1_OFFSET = 0
MBUS_LENGTH1_OFFSET = 1
MBUS_LENGTH2_OFFSET = 2
MBUS_START2_OFFSET = 3

So min length 4 check covers all the bounds for the buffer accesses.

2025-11-04 20:42 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    this->receive_buffer_.push_back(c);
> If this happens please tell your provider: WTF, fix your shit.

Ha!
Ok. But there is still an issue:

Imagine there is a noise on the line. A user could connect the UART improperly, for example. The code below the `while (this->available())` loop checks `millis() - this->last_read_ > this->read_timeout_`. This condition will never be satisfied because there will never be a time gap. The while loop will be constantly reentered, continuously pushing bytes into the buffer and crashing the board.

Instead, allocate a static buffer, say 4000 bytes, and add the following code into the while loop:
```
while (uart.available()) {
    // reset buffer if overflow.
    if (dlms_packet_buffer_position >= dlms_packet_buffer.size()) {
      dlms_packet_buffer_position = 0;
      log_error("buffer overflow. Probably garbage on the line");
    }
```

2025-11-04 20:42 UTC, PolarGoose commented on esphome/components/dlms_meter/mbus.h
> +|               Start Character [0x68]               |  \
Scheiße, it is all in German :)

Could you mention these links in the documentation? Maybe just here in the code's comments?

2025-11-04 20:42 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms.h
> +        Encrypted Payload
> Authentication data isn't used by the smartmeters here

Ok, I checked the documents you gave. Indeed, the authentication is not used.

2025-11-04 20:59 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    this->receive_buffer_.push_back(c);
> Imagine there is a noise on the line. A user could connect the UART improperly

Then the user should notice and fix the connection.
If they connect it, I think they want data from the smartmeter and not just an esp wasting power.

> Instead, allocate a static buffer, say 4000 bytes, 

Sorry but no.
Why waste tons of ram space?
And it simply can't be allocated statically, because the packets are dynamic.

Please check the codebase, this seems to be the de-factor standard. JUst some examples of (i think quite popular components):
 - https://github.com/esphome/esphome/blob/dev/esphome/components/modbus/modbus.cpp#L19
 - https://github.com/esphome/esphome/blob/dev/esphome/components/shelly_dimmer/shelly_dimmer.cpp#L362
 - even the clear would "constantly break" according to logic: https://github.com/esphome/esphome/blob/dev/esphome/components/shelly_dimmer/shelly_dimmer.cpp#L489
 - https://github.com/esphome/esphome/blob/dev/esphome/components/zwave_proxy/zwave_proxy.cpp#L85

2025-11-04 21:02 UTC, SimonFischer04 commented on esphome/components/dlms_meter/mbus.h
> +|               Start Character [0x68]               |  \
No, because non of them clearly describes one of the structures.
Ideal would be fe. the mbus, dlms, ... specs.
But the are not public.

And i don't want to link to "random" sites where the link may change / dissappear at any time. (Already changed a few times since I started with the component)

2025-11-04 21:08 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (this->receive_buffer_.size() - frame_offset < frame_length + 3) {
also added comment in code: length field inside packet does not account for second start- + checksum- + stop- byte

2025-11-04 21:17 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      if (this->receive_buffer_.size() - frame_offset < frame_length + 3) {
the frame_length + 3 check was not meant as a check of the access bellow.
it is to compare frame_length (extracted from mbus header field) matches with the buffer size.

Added another bounds check now before accessing this->receive_buffer_[frame_offset + frame_length + MBUS_HEADER_INTRO_LENGTH + MBUS_FOOTER_LENGTH - 1]

2025-11-04 21:57 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +}
split into functions like suggested: parse_mbus(), parse_dlms(), decrypt(), decode_obis()

2025-11-04 22:04 UTC, SimonFischer04 commented
Thanks again for your reviews @swoboda1337 @PolarGoose.
I hope I got everything.

PR is therefore now ready to be reviewed again from my side.

2025-11-05 10:25 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    this->receive_buffer_.push_back(c);
@SimonFischer04,

Don't discard this idea prematurely. Crashing on noise on the line is not a `the de-factor standard`, and this is not what the code that you provided as examples does.

* `modbus.cpp` - it doesn't blindly add bytes to the buffer. It parses the packet on the fly, and thus, it will not accumulate bytes forever. ChatGpt says there is only one very unlikely scenario where the noise would crash the code. It is still bad.
* `shelly_dimmer.cpp` - it does exactly what I propose to do:
```
  if ((4 + payload_len + 3) > SHELLY_DIMMER_BUFFER_SIZE) {
    return -1;
  }
```
* `zwave_proxy.cpp` - there are no boundary checks, but the buffer they allocate is 257 bytes long. And the length field coming from the UART is one byte. Thus, the overflow will never occur.

2025-11-05 10:31 UTC, PolarGoose commented
Does this pull request actually fix [DSMR - Polish meters #6500
](https://github.com/esphome/issues/issues/6500)?

2025-11-05 13:49 UTC, PolarGoose commented
Just in case, I'm not a blocking reviewer. I just pointed out some issues I see based on my experience with the ESPHome DSMR component. You don't have to fix all of my comments, I'm ok with it.

Thanks for taking my comments into account.

2025-11-05 13:57 UTC, PolarGoose commented
In the future, maybe @jesserockz's approach with [dsmr_parser](https://github.com/esphome-libs/dsmr_parser) is a better alternative. The code can be isolated into a separate library, covered with tests, and have all relevant documentation and testing data. Then introducing changes is much easier, and the code quality is better this way. You can compile it with different compilers and sanitizers for testing.

2025-11-12 17:17 UTC, SimonFischer04 commented
> Does this pull request actually fix [DSMR - Polish meters #6500 ](https://github.com/esphome/issues/issues/6500)?

They discussed binary (dsmr is text) dlms encrypted data. So I though so. 
Not that deep into the exact details.

Removed the fixes now, just in case.

2025-11-20 09:32 UTC, pos-ei-don commented
Compatibility confirmed with ESPHome 2025.11.0. We're excited for this update to be merged soon, bringing this great solution and feature support to all users.

2025-11-23 14:02 UTC, SimonFischer04 commented
@swoboda1337 anything still missing here?
I think I implemented all your requested changes.

Sorry for the huge diff in the dlms_meter.cpp. 
That was because of the requested split of the loop function.
No logic should have changed. Just split it into multiple functions (and added parameters / return values accordingly) .

Pushed all the requested changes in separate commits, so it can hopefully be reviewed better.

2025-12-02 23:31 UTC, makerwolf commented
I just noticed that compilation fails if I decide not to include the timestamp text sensor (I see no use for it): 

```Compiling .pioenvs/smartmeter/src/esphome/components/uart/uart_component_esp_idf.cpp.o
In file included from src/esphome/components/dlms_meter/dlms_meter.cpp:1:
src/esphome/components/dlms_meter/dlms_meter.h:7:10: fatal error: esphome/components/text_sensor/text_sensor.h: No such file or directory
    7 | #include "esphome/components/text_sensor/text_sensor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/smartmeter/src/esphome/components/dlms_meter/dlms_meter.cpp.o] Error 1
In file included from src/esphome.h:21,
                 from src/esphome-dlms-meter/espdm.h:1,
                 from src/esphome-dlms-meter/espdm.cpp:1:
src/esphome/components/dlms_meter/dlms_meter.h:7:10: fatal error: esphome/components/text_sensor/text_sensor.h: No such file or directory
    7 | #include "esphome/components/text_sensor/text_sensor.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/smartmeter/src/esphome-dlms-meter/espdm.cpp.o] Error 1```

thanks for your effort by the way! Epic to see this PR, very very useful!

2025-12-07 21:10 UTC, SimonFischer04 commented
> I just noticed that compilation fails if I decide not to include the timestamp text sensor (I see no use for it):
> 
> ```
> In file included from src/esphome/components/dlms_meter/dlms_meter.cpp:1:
> src/esphome/components/dlms_meter/dlms_meter.h:7:10: fatal error: esphome/components/text_sensor/text_sensor.h: No such file or directory
>     7 | #include "esphome/components/text_sensor/text_sensor.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> *** [.pioenvs/smartmeter/src/esphome/components/dlms_meter/dlms_meter.cpp.o] Error 1
> In file included from src/esphome.h:21,
>                  from src/esphome-dlms-meter/espdm.h:1,
>                  from src/esphome-dlms-meter/espdm.cpp:1:
> src/esphome/components/dlms_meter/dlms_meter.h:7:10: fatal error: esphome/components/text_sensor/text_sensor.h: No such file or directory
>     7 | #include "esphome/components/text_sensor/text_sensor.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> *** [.pioenvs/smartmeter/src/esphome-dlms-meter/espdm.cpp.o] Error 1```
> 
> thanks for your effort by the way! Epic to see this PR, very very useful! 
> ```

Thanks for the info.
I don't think this is blocking, can try to deal with that in a later pr.

Let's start by getting a first implementation merged so the PR does not change even more and needs to be re-reviewed.

2025-12-07 21:13 UTC, SimonFischer04 commented
@swoboda1337 Sorry to bother again.
As you have already reviewed and I implemented the requested changes.

Anything still missing for merge?

2025-12-07 21:27 UTC, swoboda1337 commented
I will have to look at this again sorry. I haven't forgotten about it.

2025-12-08 02:03 UTC, ximex commented
@SimonFischer04 pls update the namespace syntax to the new default from:
```cpp
namespace esphome {
namespace dlms_meter {
```
to:
```cpp
namespace esphome::dlms_meter {
```

2025-12-09 09:00 UTC, SimonFischer04 commented
> @SimonFischer04 pls update the namespace syntax to the new default from:
> 
> ```c++
> namespace esphome {
> namespace dlms_meter {
> ```
> 
> to:
> 
> ```c++
> namespace esphome::dlms_meter {
> ```

@ximex I would in theory be fine with this change.
But all (except very few core ones) components are using exactly this syntax:
```
namespace esphome {
namespace dlms_meter {
```
While implementing this component, I tried to follow this project's standards.

If asked to, I can change it.
But also would like to avoid complicating review even more with little nitpick changes that require re-review.

2025-12-09 10:02 UTC, ximex commented
i have no problem to keep the old syntax for now. the transition to the new syntax is currently in progress for one component after the other. so i thought we should directly use the new one.
see: 
https://developers.esphome.io/architecture/components/#minimal-component-example
i recently updated the developer docs for that ;-)
https://github.com/esphome/developers.esphome.io/pull/73

2025-12-17 07:09 UTC, pos-ei-don commented
@swoboda1337 
Confirmed that this still works with ESPHome 2025.12.0. It is a bit frustrating for me as an end user that this hasn't been included yet.

2026-01-03 21:29 UTC, ximex commented
@swoboda1337 pls review if you have time

2026-01-05 17:47 UTC, swoboda1337 requested changes
Other potential nits, this one is AI generated so some may not be valid:
```
● Additional Nitpicks:

  1. __init__.py:45 - CONF_PROVIDER default should use default= not positional:
  cv.Optional(CONF_PROVIDER, "generic")  # positional
  cv.Optional(CONF_PROVIDER, default="generic")  # preferred
  2. __init__.py:64 - Redundant check, CONF_PROVIDER always exists due to default:
  if CONF_PROVIDER in config:
  4. dlms_meter.h:20 - DLMS_METER_VERSION unused except in one log statement - remove it.
  5. dlms_meter.cpp:430 - Timestamp buffer size 27 but format only needs 21 (0000-00-00T00:00:00Z\0).
  6. obis.h - Arrays should have explicit size:
  static constexpr uint8_t ESPDM_VOLTAGE_L1[]{0x20, 0x07};  // implicit
  static constexpr uint8_t ESPDM_VOLTAGE_L1[2] = {0x20, 0x07};  // explicit
  7. dlms_meter.cpp:185 - Inconsistent ESP_LOGE vs ESP_LOGW for similar "unsupported" conditions.
  8. mbus.h:63-64 - Redundant constants:
  static constexpr uint8_t START_BYTE_CONTROL_FRAME = 0x68;
  static constexpr uint8_t START_BYTE_LONG_FRAME = 0x68;  // same value
  9. sensor/__init__.py - Missing UNIT_VOLT_AMPS_REACTIVE_HOURS for reactive energy (uses UNIT_WATT_HOURS which is technically incorrect for var·h).
  10. dlms_meter.cpp:292 - Empty else blocks with just warnings for unsupported codes could be consolidated.
  11. dlms_meter.h:89 - Comment says "DLMS_METER_**_LIST generated by ESPHome" but it's generated by the component's own to_code, not ESPHome core.
  12. Trailing underscore inconsistency - read_timeout_ has no setter, should either have one or be const.
  ```

2026-01-05 17:47 UTC, swoboda1337 commented on tests/components/dlms_meter/test_generic.esp32-ard.yaml
Way too many tests, lets get this down to 4 or 5? Test a single variant and do we need esp32 ard tests? Maybe test netzone on one and generic on the other?

2026-01-05 17:47 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    uint8_t plaintext[message_length];
This is not valid C++, should allocate fixed sized arrays, just allocate the max. Same for obis_code.

2026-01-05 17:47 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +  message_length = mbus_payload[DLMS_LENGTH_OFFSET];
Should valid the message_length?

2026-01-05 17:47 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.h
> +static constexpr const char *TAG = "dlms_meter";
Move to cpp

2026-01-05 17:47 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.h
> +namespace dlms_meter {
```suggestion
namespace esphome::dlms_meter {
```
Change all of them

2026-01-05 17:47 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +  MeterData data{};
maybe memset this to 0? Or add initialization values in the struct?

2026-01-05 17:47 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +          sprintf(timestamp, "%04u-%02u-%02uT%02u:%02u:%02uZ", year, month, day, hour, minute, second);
Can use snprintf for safety.

2026-01-05 17:47 UTC, swoboda1337 commented on tests/components/dlms_meter/test_netznoe.esp8266-ard.yaml
> +  uart: !include ../../test_build_components/common/uart/8266-ard.yaml
```suggestion
  uart: !include ../../test_build_components/common/uart/esp8266-ard.yaml
```

2026-01-05 17:47 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +void DlmsMeterComponent::setup() { ESP_LOGI(TAG, "DLMS smart meter component v%s started", DLMS_METER_VERSION); }
```suggestion
```
Remove setup and the version id

2026-01-05 17:47 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    this->receive_buffer_.push_back(c);
We need to add a bounds check here

2026-01-06 21:29 UTC, SimonFischer04 commented on tests/components/dlms_meter/test_netznoe.esp8266-ard.yaml
> +  uart: !include ../../test_build_components/common/uart/8266-ard.yaml
fixed

2026-01-06 21:38 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.h
> +namespace dlms_meter {
fixed

2026-01-06 21:41 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +void DlmsMeterComponent::setup() { ESP_LOGI(TAG, "DLMS smart meter component v%s started", DLMS_METER_VERSION); }
done

2026-01-06 21:42 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.h
> +static constexpr const char *TAG = "dlms_meter";
fixed

2026-01-06 21:44 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +          sprintf(timestamp, "%04u-%02u-%02uT%02u:%02u:%02uZ", year, month, day, hour, minute, second);
done

2026-01-06 21:52 UTC, SimonFischer04 commented on tests/components/dlms_meter/test_generic.esp32-ard.yaml
reduced it down to 6 now.
for each variant: esp32-idf, esp32-ard and 8266.

"do we need esp32 ard tests"?
Why not? Isn't that exactly what tests are for to ensure it also works with arduino like other components do it as well?

And I don't think it make sense to one test 1 variant with 1 framework and the other with the other. Then there could still be undetected broken combinations.

are you fine with that?

2026-01-06 21:54 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +  MeterData data{};
done

2026-01-06 22:29 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +  message_length = mbus_payload[DLMS_LENGTH_OFFSET];
done

2026-01-06 22:29 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    uint8_t plaintext[message_length];
done

2026-01-06 22:31 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +    this->receive_buffer_.push_back(c);
done

2026-01-06 22:44 UTC, SimonFischer04 commented
@swoboda1337 all requested changes implemented, please re-review

2026-01-07 06:47 UTC, pos-ei-don commented
@SimonFischer04
esp8266 is now broken with the last changes, it compiles, but does not connect to the api andlog does not show any values.
last working commit is 1edb34ec0bf18988bba5dbd8472c22d5e25c9bd8.

2026-01-07 08:23 UTC, SimonFischer04 commented
> @SimonFischer04
> esp8266 is now broken with the last changes, it compiles, but does not connect to the api andlog does not show any values.
> Last working commit is: 2d9d2947b9b0842ce72b1ae09e008f0eb4fa2642
> 
> Edit1: changed last known version to 2d9d2947b9b0842ce72b1ae09e008f0eb4fa2642. got an api timeout at the first time, but started to work later.
> Commit 2015fb2a1e7eaecf5891279f36248b0f60f28f6a does not compile.
> The next commits like f35b6655306a863d8193cc8d6309d6ba2b51c0b7 stop working, but i do not get any logs nor any values in HA from my smartmeter. Just this connection error (over wifi, usb is not connected).
> 
> `WARNING Can't connect to ESPHome API for smartmeter: Timeout while connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.17.7', port=6053))] (TimeoutAPIError)
> `
> 
> Edit2 (just for reference) :
> 
> It does not work when i compile it like this
> ```
> external_components:
>   - source: github://pr#8009   # see https://github.com/esphome/esphome/pull/8009
>     components: [ dlms_meter ]
>     refresh: 0s #1 days #0s #fetch most current additions 
> ```
> 
> but it works if i compile it like this
> 
> ```
> external_components:
>   - source:
>       type: git
>       url: https://github.com/esphome/esphome
>       ref: 2d9d2947b9b0842ce72b1ae09e008f0eb4fa2642
>     components: [ dlms_meter ]
>     refresh: 0s
> ```

Any errors / values visible when directly checking the webserver on the esp?

2026-01-07 08:35 UTC, SimonFischer04 commented
But my guess would be that since we are now always allocating the max array for message.
Which is size 0xFFFF.
 The 8266 just cant handle that and crashes.

@swoboda1337 how to deal with that?

2026-01-07 09:14 UTC, pos-ei-don commented
@SimonFischer04
> Any errors / values visible when directly checking the webserver on the esp?

Had to recompile with webserver.
Webserver works with 2d9d2947b9b0842ce72b1ae09e008f0eb4fa2642
but does timeout with 54ee88471d7e54cfdd7517feb688ccf8dd372b18.

however, OTA still works!

2026-01-07 12:49 UTC, swoboda1337 commented
> @swoboda1337 how to deal with that?

The default stack size on esp32 is 8k and cant handle 64k either, I will take a look again later today:
```
                cv.Optional(CONF_LOOP_TASK_STACK_SIZE, default=8192): cv.int_range(
                    min=8192, max=32768
                ),
```

2026-01-07 14:08 UTC, PolarGoose commented
> But my guess would be that since we are now always allocating the max array for message. Which is size 0xFFFF. The 8266 just cant handle that and crashes.
> 
> @swoboda1337 how to deal with that?

I guess not allocating a 32kb array on the stack is a good starting point :)

Why don't you decrypt in place? You don't need to allocate a separate buffer for the decrypted result.

2026-01-07 14:14 UTC, swoboda1337 commented
Yes do in place if you can. Secondly 64k is really the max size? Should dig into that and see if if that is the real max because that is significant. Hopefully can limit that to something smaller.

2026-01-07 14:31 UTC, swoboda1337 commented
BTW `message_length = mbus_payload[DLMS_LENGTH_OFFSET];` mbus_payload is an int8_t which has a max size of 0xFF or 255. Is the max size really 0xFFFF?

2026-01-07 14:34 UTC, swoboda1337 commented
Sorry there is this as well `memcpy(&message_length, &mbus_payload[DLMS_LENGTH_OFFSET + 1], 2);`. If 64k really is the max size it may be difficult to make this component usable unless you process the data as you receive it.

2026-01-07 17:23 UTC, SimonFischer04 commented
> I guess not allocating a 32kb array on the stack is a good starting point :)

That's why I did it dynamically initially.

2026-01-07 17:25 UTC, swoboda1337 commented
> > I guess not allocating a 32kb array on the stack is a good starting point :)
> 
> That's why I did it dynamically initially.

That is not any better, if someone got a large packet that will blow the stack. Still a massive problem

2026-01-07 17:32 UTC, SimonFischer04 commented
> > > I guess not allocating a 32kb array on the stack is a good starting point :)
> > 
> > 
> > That's why I did it dynamically initially.
> 
> That is not any better, if someone got a large packet that will blow the stack. Still a massive problem

I don't think it would actually be that big. Probably only a bit above 0xFF, but with 2 bytes 0xFFFF would technically be a valid paket. (that I don't think is realistic in practice. Haven't checked, but this may not even be technically possible to send 64k every 5s with 2400 baud)
But yes, agreed.

Decrypting in place is also hard because I need to wait for footer / end bytes.

How about limiting it to 0xFF for now and adding error if we get bigger paket?
0xF8 is the biggest now seen so far. If we actually find meters with bigger messages this could be improved later on.

2026-01-07 17:36 UTC, swoboda1337 commented
Yes limiting the packet size sounds like a good idea. Can even do 512 bytes, no issue there

2026-01-07 17:49 UTC, SimonFischer04 commented
> Yes limiting the packet size sounds like a good idea. Can even do 512 bytes, no issue there

Done, did decrease the limit to 512.
Bounds check with error message was already added before.

@pos-ei-don please test if it works again for you.

2026-01-07 18:01 UTC, pos-ei-don commented
@SimonFischer04 It looks good again! Thank you!!
It compiles and it recives correct values.

Just to note, I got these two lines in the log right after the startup.

```
[18:53:34.288][E][dlms_meter:133]: MBUS: Invalid stop byte
[18:53:34.298][E][dlms_meter:148]: MBUS: Invalid checksum: c7 != c5
```

2026-01-07 18:03 UTC, SimonFischer04 commented
> @SimonFischer04 It looks good again! Thank you!! It compiles and it recives correct values.
> 
> Just to note, I got these two lines in the log right after the startup.
> 
> ```
> [18:53:34.288][E][dlms_meter:133]: MBUS: Invalid stop byte
> [18:53:34.298][E][dlms_meter:148]: MBUS: Invalid checksum: c7 != c5
> ```

@pos-ei-don 
These errors are very likely just because the esp restarted in the middle of the smartmeter sending data -> paket can't be valid.

Good to hear, then everything should be good to go and ready to merge from my side.

2026-01-07 18:56 UTC, PolarGoose commented
> Decrypting in place is also hard because I need to wait for footer / end bytes.

Why don't you receive the entire packet first, then decrypt it?

2026-01-07 19:05 UTC, SimonFischer04 commented
> > Decrypting in place is also hard because I need to wait for footer / end bytes.
> 
> Why don't you receive the entire packet first, then decrypt it?

this is what I'm doing currently. with the issue of the potentially stack overflowing pakets

2026-01-07 19:32 UTC, PolarGoose commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      ESP_LOGW(TAG, "Receive buffer full, dropping byte");
you need to reset the buffer here

2026-01-07 19:34 UTC, PolarGoose commented
> > > Decrypting in place is also hard because I need to wait for footer / end bytes.
> > 
> > 
> > Why don't you receive the entire packet first, then decrypt it?
> 
> this is what I'm doing currently. with the issue of the potentially stack overflowing pakets

Why can't you decrypt in place if you receive the whole packet? Your `std::vector<uint8_t> mbus_payload` variable contains whole encrypted message

2026-01-07 19:47 UTC, SimonFischer04 commented
> > > > Decrypting in place is also hard because I need to wait for footer / end bytes.
> > > 
> > > 
> > > Why don't you receive the entire packet first, then decrypt it?
> > 
> > 
> > this is what I'm doing currently. with the issue of the potentially stack overflowing pakets
> 
> Why can't you decrypt in place if you receive the whole packet? Your `std::vector<uint8_t> mbus_payload` variable contains whole encrypted message

1. mbedtls wants an array. not an std::vector
2.  how would that solve the core ssue? like swoboda pointet out the packet received can still be big.
64k in any buffer would probably blow up the memory.

2026-01-07 19:57 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      ESP_LOGW(TAG, "Receive buffer full, dropping byte");
or just break

2026-01-07 20:01 UTC, swoboda1337 commented
> 1. mbedtls wants an array. not an std::vector
> 2. how would that solve the core ssue? like swoboda pointet out the packet received can still be big.
>    64k in any buffer would probably blow up the memory.

You can call .data() on a vector and get a pointer to the array
You don't need the plaintext buffer  as you just copy it anyways `memcpy(plaintext, &mbus_payload[header_offset + DLMS_PAYLOAD_OFFSET], message_length);`

Still cant support 64k messages but at least one buffer is gone

2026-01-07 20:05 UTC, PolarGoose commented
Just in case, I implemented in-place decryption for the dsmr parser library. You can implement something similar:
[aes128gcm_mbedtls.h](https://github.com/esphome-libs/dsmr_parser/blob/main/src/dsmr_parser/aes128gcm_mbedtls.h)
[aes128gcm_bearssl.h](https://github.com/esphome-libs/dsmr_parser/blob/main/src/dsmr_parser/aes128gcm_bearssl.h)

2026-01-07 23:13 UTC, SimonFischer04 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      ESP_LOGW(TAG, "Receive buffer full, dropping byte");
done

2026-01-07 23:26 UTC, SimonFischer04 commented
done, 
decryption now implemented inplace and break added.

2026-01-08 03:54 UTC, pos-ei-don commented
Tested in 8266, thank you!!

2026-01-16 10:50 UTC, SimonFischer04 commented
@swoboda1337 anything still missing here?

2026-01-20 03:28 UTC, swoboda1337 commented on tests/components/dlms_meter/test_generic.esp32-ard.yaml
For ESP32 if there are no Arduino ifdefs then it should be the identical to IDF. Especially now that we use Arduino as an IDF component. However 6 test is probably ok.

2026-01-20 03:30 UTC, swoboda1337 commented on tests/components/dlms_meter/test_generic.esp32-ard.yaml
Some background, running the full test suite used to take over 12 hours. We worked hard to get that down to something more reasonable.

2026-01-20 18:57 UTC, SimonFischer04 commented on tests/components/dlms_meter/test_generic.esp32-ard.yaml
Ok, 
Thx for the info.

2026-01-20 20:50 UTC, ximex commented on esphome/components/dlms_meter/dlms_meter.cpp
> +                "  Decryption Key: %s",
should we really log the decryption key by default?

2026-01-21 06:52 UTC, pos-ei-don commented
Sucessfully tested with New esphome 2026.1.0 on 8266

2026-01-22 17:04 UTC, cococheaf commented
This is not compiling right with the pr set as external component.

```
INFO ESPHome 2026.1.0
INFO Reading configuration /config/esphome/smartmeter.yaml...
Failed config

external_components: [source /config/esphome/smartmeter.yaml:54]
  - source: github://pr#8009
    components: 
      
      Could not find __init__.py file for component dlms_meter. Please check the component is defined by this source (search path: /data/external_components/138b9362/esphome/components/dlms_meter/__init__.py).
      - dlms_meter
```

Something changed after ESPHome
2026.1

2026-01-22 17:41 UTC, ximex commented
@cococheaf which esp variant do you have? for my esp32-c6 it successfully builds

2026-01-22 17:45 UTC, cococheaf commented
> @cococheaf which esp variant do you have? for my esp32-c6 it successfully builds

Hi, i have a NodeMCU ESP-WROOM (esp32-dev).

Here is my yaml:

```
esphome:
  name: smartmeter
  comment: "'NodeMCU ESP32 Dev' mit MikroE-MBUS-SlaveClick an Kaifa MA309M Stromzähler"
  friendly_name: Stromzähler

esp32:
  board: esp32dev
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  fast_connect: true
  manual_ip:
    static_ip: w.x.y.z
    gateway: w.x.y.z
    subnet: w.x.y.z
    dns1: 1w.x.y.z
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password

captive_portal:

logger:

web_server:
  port: 80
  version: 2
  local: true

ota:
  - platform: esphome
    password: !secret ota_password
  - platform: web_server

uart:
  rx_pin: GPIO33
  tx_pin: GPIO32
  baud_rate: 2400
  data_bits: 8
  stop_bits: 1
  rx_buffer_size: 2048
  id: mbus

external_components:
  - source: github://pr#8009
    components: [ dlms_meter ]

dlms_meter:
  decryption_key: "my-secret-key"

sensor:
  - platform: dlms_meter
    voltage_l1:
      name: "smartmeter_voltage_l1"
    voltage_l2:
      name: "smartmeter_voltage_l2"
    voltage_l3:
      name: "smartmeter_voltage_l3"
    current_l1:
      name: "smartmeter_current_l1"
    current_l2:
      name: "smartmeter_current_l2"
    current_l3:
      name: "smartmeter_current_l3"
    active_power_plus:
      name: "smartmeter_active_power_plus"
    active_power_minus:
      name: "smartmeter_active_power_minus"
    active_energy_plus:
      name: "smartmeter_active_energy_plus"
    active_energy_minus:
      name: "smartmeter_active_energy_minus"
    reactive_energy_plus:
      name: "smartmeter_reactive_energy_plus"
    reactive_energy_minus:
      name: "smartmeter_reactive_energy_minus"

text_sensor:
  - platform: dlms_meter
    timestamp:
      name: "smartmeter_timestamp"
```

2026-01-22 17:46 UTC, pos-ei-don commented
>       Could not find __init__.py file for component dlms_meter. Please check the component is defined by this source (search path: /data/external_components/138b9362/esphome/components/dlms_meter/__init__.py).
>       - dlms_meter
> ```

I think that thia is Just corrupt build Cache. 

Can you try to clean IT?

2026-01-22 17:49 UTC, cococheaf commented
> > ```
> >   Could not find __init__.py file for component dlms_meter. Please check the component is defined by this source (search path: /data/external_components/138b9362/esphome/components/dlms_meter/__init__.py).
> >   - dlms_meter
> > ```
> 
> I think that thia is Just corrupt build Cache.
> 
> Can you try to clean IT?

Have tried that first. same error

![IMG_3297](https://github.com/user-attachments/assets/9cf15d51-a626-4edb-b09e-d0e538f429e1)

2026-01-22 17:56 UTC, swoboda1337 commented
> Can you try to clean IT?

Do `Clean All` (which is beside `Update All`)

2026-01-22 18:04 UTC, cococheaf commented
> > Can you try to clean IT?
> 
> Do `Clean All` (which is beside `Update All`)

Cleaned All, compiled fine this time, but no luck with the readings. Key is correct, triple checked with provider.

![IMG_3298](https://github.com/user-attachments/assets/8c02ef18-f4c0-45b4-b0a8-c0fb2008d317)

2026-01-22 18:13 UTC, RocketSience commented
Here it compiles, but decryption is not working anymore: in 2026.01

yaml


 
```
esphome:
  name: "meter01"
  comment: "'NodeMCU ESP32 Dev' mit MikroE-MBUS-SlaveClick an Kaifa MA309M Stromzähler"
  friendly_name: Smartmeter_Haus

esp32:
  board: esp32dev
  framework:
    type: arduino


ota:
 - platform: esphome
   password: "xxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: false
  manual_ip:
    static_ip: 192.168.0.210
    gateway: 192.168.0.253
    subnet: 255.255.255.0
    dns1: 192.168.0.253
  ap:
    ssid: "Smartmeter-Haus Fallback Hotspot"
    password: xxxxx

mqtt:
  broker: 192.168.0.36
  id: mqtt_broker
  topic_prefix: "haus/zaehler/meter01"

captive_portal:

logger:
  level: DEBUG

web_server:
  port: 80
  version: 2
  local: true

external_components:
  - source: github://pr#8009   # see https://github.com/esphome/esphome/pull/8009
    components: [ dlms_meter ]

uart:
  rx_pin: GPIO16
  baud_rate: 2400
  rx_buffer_size: 2048
  id: mbus

dlms_meter:
  decryption_key: xxxxx

sensor:
  - platform: dlms_meter
    voltage_l1:
      name: "meter01_voltage_l1"
    voltage_l2:
      name: "meter01_voltage_l2"
    voltage_l3:
      name: "meter01_voltage_l3"
    current_l1:
      name: "meter01_current_l1"
    current_l2:
      name: "meter01_current_l2"
    current_l3:
      name: "meter01_current_l3"
    active_power_plus:
      name: "meter01_active_power_plus"
    active_power_minus:
      name: "meter01_active_power_minus"
    active_energy_plus:
      name: "meter01_active_energy_plus"
    active_energy_minus:
      name: "meter01_active_energy_minus"
    reactive_energy_plus:
      name: "meter01_reactive_energy_plus"
    reactive_energy_minus:
      name: "meter01_reactive_energy_minus"


text_sensor:
  - platform: dlms_meter
    timestamp:
      name: "meter01_timestamp"      
```


Result:

```
INFO ESPHome 2026.1.0
INFO Reading configuration /config/esphome/meter01.yaml...
INFO Generating C++ source...
INFO Setting CONFIG_LWIP_MAX_SOCKETS to 12 (registered: captive_portal=4, mdns=2, mqtt=1, ota=1, socket.wake_loop_threadsafe=1, web_server=3)
INFO Compiling app... Build path: /data/build/meter01
Processing meter01 (board: esp32dev; framework: arduino, espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - contrib-piohome @ 3.4.4 
 - framework-arduinoespressif32 @ 3.3.5 
 - framework-arduinoespressif32-libs @ 5.5.0+sha.9bb7aa84fe 
 - framework-espidf @ 3.50502.0 (5.5.2) 
 - tool-cmake @ 4.0.3 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.1.0 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20251107
Reading CMake configuration...
Dependency Graph
|-- Networking @ 3.3.5
|-- ArduinoJson @ 7.4.2
RAM:   [=         ]  12.0% (used 39432 bytes from 327680 bytes)
Flash: [======    ]  56.0% (used 1026743 bytes from 1835008 bytes)
========================= [SUCCESS] Took 11.15 seconds =========================
INFO Build Info: config_hash=0x824ef39e build_time_str=2026-01-21 21:34:29 +0100
INFO Successfully compiled program.
INFO Starting looking for IP in topic esphome/discover/meter01
INFO Connected to MQTT broker!
INFO Send discover via MQTT broker topic: esphome/ping/meter01
INFO Found IP: ['192.168.0.210']
INFO Connecting to 192.168.0.210 port 3232...
INFO Connected to 192.168.0.210
INFO Uploading /data/build/meter01/.pioenvs/meter01/firmware.bin (1027152 bytes)
Uploading: [============================================================] 100% Done...

INFO Upload took 5.78 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from haus/zaehler/meter01/debug
INFO Connected to MQTT broker!
[18:58:15][I][app:258]: Rebooting safely
[18:58:20][W][component:426]: mqtt cleared Warning flag
[18:58:20][I][mqtt:318]: Connected
[18:58:20][W][component:543]: mqtt took a long time for an operation (111 ms)
[18:58:20][W][component:546]: Components should block for at most 30 ms
[18:58:24][E][dlms_meter:236]: Decryption failed with error: -20
[18:58:39][E][dlms_meter:236]: Decryption failed with error: -20
```

2026-01-22 19:09 UTC, swoboda1337 commented
EDIT: 2026.1 moved to IDF 5.5.2 which moved to a new version of mbed tls... not sure if that changed anything.

2026-01-22 19:30 UTC, swoboda1337 commented
Pretty sure it failed because the tag was not specified can you try again with this, make sure you have a refresh:
```
external_components:
  - source: github://pr#8009
    components: [ dlms_meter ]
    refresh: always
```

2026-01-22 19:37 UTC, cococheaf commented
> Pretty sure it failed because the tag was not specified can you try again with this, make sure you have a refresh:
> 
> ```
> external_components:
>   - source: github://pr#8009
>     components: [ dlms_meter ]
>     refresh: always
> ```

It works!! Thank you all for your support!!!

2026-01-22 19:59 UTC, ximex commented
@swoboda1337 is there anything missing here now to get it merged? (except wait for some more who confirm that it works with 2026.1.0 - i will test the next days)

2026-01-22 20:03 UTC, RocketSience commented
it works

2026-01-22 20:04 UTC, swoboda1337 commented
> @swoboda1337 is there anything missing here now to get it merged? (except wait for some more who confirm that it works with 2026.1.0 - i will test the next days)

Yeah needs a bit more clean up, getting there though.

2026-01-22 21:44 UTC, SimonFischer04 commented
> > @swoboda1337 is there anything missing here now to get it merged? (except wait for some more who confirm that it works with 2026.1.0 - i will test the next days)
> 
> Yeah needs a bit more clean up, getting there though.
> 

Thanks for taking the time to review and even recently committing cleanups and fixes yourself 👍.

I'm not that familiar with c++/esphome code gen system/... to understand all the differences  in detail - you know c++ way better.
Changes seem fine to me so far mostly.

If there is anything I should change please tell.

Only thing I'm not so sure about (other than the decryption key logging already mentioned by @ximex ) is if we should really remove all the packet logging. It was only logged as verbose and was already helpful many times debugging issues with user setups.

2026-01-23 00:58 UTC, swoboda1337 commented
For the key can log with LOG_SECRET like wifi etc does or just remove it? Can add some of the packet logging back.

2026-01-23 02:57 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> -
Easier just to compare uint16_ts and remove the extra enum

2026-01-23 13:10 UTC, SimonFischer04 commented
> For the key can log with LOG_SECRET like wifi etc does or just remove it? 

Didnt know LOG_SECRET existed, so I went with vv logging.
Technically still a configuration of the component so i guess dump_config should log it.
If there is this nice method indended for these kinds of credential logging, why not use it.

> Can add some of the packet logging back. 

Would be nice.

2026-01-23 18:28 UTC, swoboda1337 requested changes
I think the clean up is done just this one remaining question/bug

2026-01-23 18:28 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        current_position += 2;
There seems to be issues here. At the end you only increment 2 bytes `current_position += 2;` but you are reading + 5?
```
        if (plaintext[current_position + 5] == Accuracy::SINGLE_DIGIT) {
          value = raw_value / 10.0f;
        } else if (plaintext[current_position + 5] == Accuracy::DOUBLE_DIGIT) {
          value = raw_value / 100.0f;
        } else {
          value = raw_value;
        }
```
Is this type 6 bytes or 2? If it is 2 why are you reading + 5?

2026-01-27 14:28 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +        current_position += 2;
Ok I think I see what is going on. Let me clean this up

2026-01-27 14:46 UTC, pos-ei-don commented
Just ran through the latest updates and it’s all working smoothly! Huge thanks for all the progress lately.

2026-01-27 17:52 UTC, swoboda1337 commented
Ok looks better. Please take a look and give it a test. Thanks

2026-01-27 17:58 UTC, swoboda1337 commented on esphome/components/dlms_meter/dlms_meter.cpp
> +      } else if (current_position != DECODER_START_OFFSET && plaintext[current_position - 1] == 0xFF) {
It is odd to do a -1 here. Can we detect this on the previous iteration? Does this always follow the timestamp?

2026-01-27 21:27 UTC, swoboda1337 commented
Ok that was the last fix, claude caught it. Please test and let me know.

2026-01-28 07:03 UTC, pos-ei-don commented
@swoboda1337
> Ok that was the last fix, claude caught it. Please test and let me know.

The code compiles successfully for the ESP8266 using ESPHome version 2026.1.1. The integration functions as intended, receiving all sensor data. The reported values align perfectly with the smart meter's on-screen display.

2026-01-30 19:51 UTC, swoboda1337 commented
@SimonFischer04 did you get a chance to review the changes?

2026-01-30 21:20 UTC, ximex commented
my tests with latest version went well

2026-01-30 23:00 UTC, SimonFischer04 commented
> @SimonFischer04 did you get a chance to review the changes?

Sorry was quite a busy last week. Only got around to finish reviewing the changes now.

why didn't you went with LOG_SECRET for the decryption key like suggested and instead just removed the logging? No problem, fine like this as well - just curious.

Otherwise, LGTM.
Also did a quick test on my esp32 using 2026.1.1 and all data is still reported fine.

thx

2026-01-31 14:42 UTC, swoboda1337 approved these changes

2026-01-31 15:31 UTC, ximex approved these changes

2026-01-31 15:48 UTC, merged

2026-01-31 15:48 UTC, swoboda1337 commented
Thanks

2026-01-31 16:01 UTC, SimonFischer04 commented
Thanks @swoboda1337 for review and merge.

And everyone else for testing, review, ...

2026-03-13 13:19 UTC, swoboda1337 commented
Hi, There are a bunch of new dlms_meter prs, could someone help test them: https://github.com/esphome/esphome/pull/14750

Thanks!