Add: Human Presence and Target Count to the Seeed Studio MR60BHA2
OttoWinter/esphomeyaml pull request #8010
Opened 2024-12-25 01:32 UTC by limengdu

# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
substitutions:
  name: "seeedstudio-mr60bha2-kit"
  friendly_name: "Seeed Studio MR60BHA2 Kit"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "seeedstudio.mr60bha2_kit"
    version: "2.0"
  platformio_options:
    board_upload.maximum_size: 4194304
  min_version: "2024.3.2" # Fix logger compile error on ESP32-C6 esphome#6323

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB # upload.flash_size
  framework:
    type: esp-idf

external_components:
  - source:
      type: git
      url: https://github.com/limengdu/MR60BHA2_ESPHome_external_components
      ref: main
    components: [ seeed_mr60bha2 ]
    refresh: 0s

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "seeedstudio-mr60bha2"

captive_portal:

# For XIAO ESP32C6 Onboard LED
# light:
#   - platform: status_led
#     name: "Switch state"
#     pin: GPIO15

light:
  - platform: esp32_rmt_led_strip
    id: led_ring
    name: "Seeed MR60BHA2 RGB Light"
    pin: GPIO1
    num_leds: 1
    rmt_channel: 0
    rgb_order: GRB
    chipset: ws2812

i2c:
  sda: GPIO22
  scl: GPIO23
  scan: true
  id: bus_a

uart:
  id: uart_bus
  baud_rate: 115200
  rx_pin: 17
  tx_pin: 16
  parity: NONE
  stop_bits: 1

seeed_mr60bha2:
  id: my_seeed_mr60bha2

binary_sensor:
  - platform: seeed_mr60bha2
    people_exist:
      name: "Person Information"

sensor:
  - platform: bh1750
    name: "Seeed MR60BHA2 Illuminance"
    address: 0x23
    update_interval: 1s
  - platform: seeed_mr60bha2
    breath_rate:
      name: "Real-time respiratory rate"
    heart_rate:
      name: "Real-time heart rate"
    distance:
      name: "Distance to detection object"
    target_num:
      name: "Target Number"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2025-01-07 13:26 UTC, DFINITYManu approved these changes

2025-01-11 18:13 UTC, Rudd-O commented
Not yet merged?  This fixes many important issues with the device.

2025-01-13 04:05 UTC, jesserockz requested changes

2025-01-13 04:05 UTC, jesserockz commented on esphome/components/seeed_mr60bha2/binary_sensor.py
> +    cv.Optional(CONF_PEOPLE_EXIST): binary_sensor.binary_sensor_schema(
"has_target" is used by other mmwave sensors (including `mr24hpc1`) and might be a better key for this binary sensor.
```suggestion
    cv.Optional(CONF_HAS_TARGET): binary_sensor.binary_sensor_schema(
```

2025-01-13 04:05 UTC, jesserockz commented on esphome/components/seeed_mr60bha2/sensor.py
> +        cv.Optional(CONF_TARGET_NUM): sensor.sensor_schema(
I feel this should be the other way around
```suggestion
        cv.Optional(CONF_NUM_TARGETS): sensor.sensor_schema(
```

2025-01-21 03:21 UTC, jesserockz commented on esphome/components/seeed_mr60bha2/seeed_mr60bha2.cpp
> +        if (this->distance_sensor_ != nullptr && length >= 4) {
Why is this changed to `4`? The line below gets data from `data[7]`, so it needs to be at least length 8?

2025-01-22 00:00 UTC, jesserockz approved these changes

2025-01-22 00:01 UTC, merged