[http_request] Bugfix: run update function in a task
OttoWinter/esphomeyaml pull request #8018
Opened 2024-12-26 19:36 UTC by kahrendt

# What does this implement/fix?

If the update function can't open the manifest url due to a bad/blocked internet connection, the device crashes with a watchdog timeout. This PR moves the update function into its own task to avoid the crash. This allows it to yield to the main task, giving the ``esp_http_client`` enough time to return with an error.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes esphome/home-assistant-voice-pe/issues/241

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** not applicable

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

ota:
  - platform: http_request
    id: ota_http_request

http_request:

update:
  - platform: http_request
    name: None
    id: update_http_request
    source: https://firmware.esphome.io/home-assistant-voice-pe/home-assistant-voice/manifest.json

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2025-01-08 21:42 UTC, tjhorner commented
Thought I would flag this potential issue here when using the Arduino framework: https://github.com/espressif/arduino-esp32/issues/8804

I modified an external component of mine to run HTTP requests in a separate task, using this PR as a model. I ran into the issue in the issue linked above. After 16 requests, the requests start failing and the node actually entirely stops responding on the network.

2025-01-10 05:37 UTC, kbx81 requested changes, later dismissed
I've confirmed that this change results in a memory leak, which seams to eat roughly 800 bytes with each HTTP request. I played around a bit to see if I could work out a fix, but no luck -- the discussion on Discord mentioned above might shed some light.

2025-01-16 16:18 UTC, kahrendt commented
Thanks for raising the issue @kbx81 and @tjhorner.

Variables declared on the stack get freed just fine when ending a FreeRTOS task. C++ objects on the heap do not. The memory leak here was due to the ``std::string`` never deallocating. I just moved the code using the strings into their ``{}`` brackets, so they will automatically be deallocated when falling out of scope. This fixed the memory leak on my end!

2025-01-16 19:50 UTC, jesserockz commented on esphome/components/http_request/update/http_request_update.cpp
> +  container.reset();  // Release ownership of the container's shared_ptr
`container->content_length` is used 7 lines below this? Isnt that gonna cause an issue?

2025-01-16 19:58 UTC, kahrendt commented on esphome/components/http_request/update/http_request_update.cpp
> +  container.reset();  // Release ownership of the container's shared_ptr
I'm surprised it didn't actually cause a problem! I adjusted it. Thanks.

2025-01-16 21:42 UTC, jesserockz approved these changes

2025-01-16 21:43 UTC, merged