add bus voltage over limit for ina2xx sensors
OttoWinter/esphomeyaml pull request #8020
Opened 2024-12-27 04:49 UTC by asssaf

# What does this implement/fix?

INA228/229 have the ability to set a threshold that triggers the alert pin when the bus voltage exceeds the provided limit.
This change adds the ability to set the threshold.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: ina2xx_i2c
    id: my_charge_sensor
    i2c_id: bus_a
    model: INA228
    address: 0x40
    shunt_resistance: 0.015 ohm
    max_current: 10 A
    adc_range: 0
    adc_averaging: 1
    adc_time: 1052us
    update_interval: 1s
    current: 
      name: "INA228 Current"
      id: current
    bus_voltage: 
      name: "INA228 Bus Voltage"
      id: bus_voltage
    charge: 
      name: "INA228 Charge"
      id: charge
    energy: 
      name: "INA228 Energy"
      id: energy
    power:
      name: "INA228 Power"
      id: power
    shunt_voltage:
      name: "INA228 Shunt Voltage"
      id: shunt_voltage
      unit_of_measurement: "mV"
    temperature:
      name: "INA228 Temperature"
      id: temperature
    bus_voltage_over_limit: 3v

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-12-27 14:02 UTC, DjordjeMandic commented on esphome/components/ina2xx_base/ina2xx_base.cpp
> +  return true;
IMO i would return false here but rest of the code already does the same. idk why

2024-12-28 20:06 UTC, asssaf commented on esphome/components/ina2xx_base/ina2xx_base.cpp
> +  return true;
this is my first ESPHome PR so i'm not sure about the conventions. My guess is that it returns true because this setting is not relevant, so is just being ignored (validation is done at the schema level)?

2025-01-03 12:20 UTC, DjordjeMandic commented on esphome/components/ina2xx_base/ina2xx_base.cpp
> +  return true;
> My guess is that it returns true because this setting is not relevant

Might be, anyways it will work

2025-01-03 21:21 UTC, latonita commented
@asssaf looks okay to me

2025-01-13 03:44 UTC, jesserockz requested changes

2025-01-13 03:44 UTC, jesserockz commented on esphome/components/ina2xx_base/ina2xx_base.cpp
> +bool INA2XX::configure_bovl_() {
Should it be bvol everywhere instead? The acronym doesnt match the config string.

2025-01-17 06:27 UTC, asssaf commented on esphome/components/ina2xx_base/ina2xx_base.cpp
> +bool INA2XX::configure_bovl_() {
This is an inconsistency from the [data sheet](https://www.ti.com/lit/ds/symlink/ina228.pdf). The registers are called [BOVL](https://github.com/esphome/esphome/blob/9e40d4cf45269e052bd62a78a5619ad8dc863594/esphome/components/ina2xx_base/ina2xx_base.h#L24), BUVL, SOVL, SUVL.
I'll jut rename it to the full name to avoid confusion.

2025-01-18 19:59 UTC, DjordjeMandic commented on esphome/components/ina2xx_base/ina2xx_base.cpp
> +bool INA2XX::configure_bovl_() {
That could be mentioned in doxygen comment

2025-02-02 08:07 UTC, latonita commented on esphome/components/ina2xx_base/ina2xx_base.cpp
> +bool INA2XX::configure_bovl_() {
@asssaf at another look - there is undervoltage and overvoltage conditions
in my world it would make senesto rename all the functions and variables properly.
from `configure_bus_voltage_over_limit_` to `configure_bus_over_voltage_limit_` and so on.
its not 'voltage over' but it is 'over voltage'

2025-10-03 00:50 UTC, closed without merging