MQTT: fan direction control added
OttoWinter/esphomeyaml pull request #8022
Opened 2024-12-27 14:24 UTC by mbronk

# What does this implement/fix?

Adds support for fan **direction** setting via MQTT (direction was already supported, but previously only accessible via API/UI).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
fan:
  - platform: ble_adv_controller
    ble_adv_controller_id: hallway_ceiling_fan_lamp_controller
    id: device_fan
    name: $name_fanlamp_hallway Fan
    speed_count: 6
    use_direction: true
    direction_state_topic: some/topic/direction/state  #new
    direction_command_topic: some/topic/direction/command #new
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2025-01-13 03:36 UTC, jesserockz requested changes

2025-01-13 03:36 UTC, jesserockz commented on esphome/components/fan/__init__.py
> +                cv.requires_component("mqtt"), cv.subscribe_topic
```suggestion
                cv.requires_component("mqtt"), cv.publish_topic
```

2025-02-04 20:12 UTC, mbronk commented
@jesserockz just a ping 😀

2025-05-11 21:52 UTC, mbronk commented
@jesserockz are you still planning to review this? 
If not, can you at least ***remove your vote*** so that another maintainer may be more interested in taking a look ❓ 

----

I realize everyone is busy and long wait times are not atypical, but it's been awaiting a re-review _(after feedback has been applied)_ for 5 months now, and the relevant PR in docs: https://github.com/esphome/esphome-docs/pull/4540 just went `stale->closed` b/c of no activity 😞

2025-05-11 22:26 UTC, jesserockz approved these changes

2025-05-11 22:28 UTC, merged