[uptime] Add text_sensor
OttoWinter/esphomeyaml pull request #8028
Opened 2024-12-31 11:05 UTC by clydebarrow

# What does this implement/fix?

Adds a text sensor for human readable uptime. This can replace the boilerplate code often seen in yaml.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
text_sensor:
  - platform: uptime
    name: "Uptime"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2024-12-31 18:02 UTC, tomaszduda23 commented on esphome/components/uptime/uptime_text_sensor.cpp
> +  const uint32_t delta = (now - this->last_ms_) / 1000;
millis can roll over after ~49.7 days. https://github.com/esphome/esphome/blob/387bde665e3ae5d4b8d5a68299abd6032c4291b8/esphome/components/uptime/uptime_seconds_sensor.cpp#L16 this handle this already.

2024-12-31 19:16 UTC, clydebarrow commented on esphome/components/uptime/uptime_text_sensor.cpp
> +  const uint32_t delta = (now - this->last_ms_) / 1000;
Yes, but the difference is still correct after the subtraction providing the time between updates is less than half the rollover time.

2025-01-12 18:59 UTC, jesserockz requested changes

2025-01-12 18:59 UTC, jesserockz commented on esphome/components/uptime/uptime_seconds_sensor.h
> +#ifdef USE_SENSOR
Each of the `sensor` and `text_sensor` related files should be in a folder, then this can be avoided as only the platforms loaded in yaml will be copied to the project

2025-01-13 03:10 UTC, jesserockz requested changes

2025-01-13 03:10 UTC, jesserockz commented on esphome/components/uptime/text_sensor/__init__.py
> +    device_class=DEVICE_CLASS_DURATION,
While this feels like it should be correct, I believe HA will throw a warning/error in the logs as it expects a `duration` to be just a number with a supported unit of measurement (which text_sensors do not do)

2025-01-13 03:10 UTC, jesserockz commented on esphome/components/uptime/text_sensor/uptime_text_sensor.cpp
> +std::string UptimeTextSensor::unique_id() { return get_mac_address() + "-uptime-text"; }
This should not be added to new components/classes. The API doesnt use these anymore, they have only be left in existing places for mqtt unique ids.
```suggestion
```

2025-01-13 03:10 UTC, jesserockz commented on esphome/components/uptime/text_sensor/uptime_text_sensor.h
> +#ifdef USE_TEXT_SENSOR
Not required since files are now in sub folder
```suggestion
```

2025-01-13 03:10 UTC, jesserockz commented on esphome/components/uptime/text_sensor/uptime_text_sensor.h
> +#endif  // USE_TEXT_SENSOR
```suggestion
```

2025-01-13 03:10 UTC, jesserockz commented on esphome/components/uptime/text_sensor/uptime_text_sensor.cpp
> +#endif  // USE_TEXT_SENSOR
```suggestion
```

2025-01-13 03:10 UTC, jesserockz commented on esphome/components/uptime/text_sensor/uptime_text_sensor.cpp
> +#ifdef USE_TEXT_SENSOR
```suggestion
```

2025-01-14 22:26 UTC, jesserockz approved these changes

2025-01-14 22:27 UTC, merged