Updated Color change commands
OttoWinter/esphomeyaml pull request #912
Opened 2019-12-10 08:15 UTC by carlos-sarmiento

The current syntax of the commands for changing color on Nextion Displays was wrong. It's not supposed to be submitted as a string, but as a number.

## Description:
The quoted strings in the command was wrong. This PR fixes that issue

**Related issue (if applicable):** fixes esphome/issues#915

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** Not Applicable

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2019-12-10 09:57 UTC, OttoWinter requested changes
The current code is correct for CSS code strings (for example `red`)

You are right that it doesn't work with HEX codes though. But for that please create an overload of these functions that accepts an uint32_t

You will probably also have to change the signature on `const char *` to `std::string` because C++ might cast ints to pointers (not 100% sure about that though).

2020-01-09 21:29 UTC, brandond commented
@carlos-sarmiento are you willing to fix this as requested?

2020-01-10 04:47 UTC, carlos-sarmiento commented
Will fix

2020-01-23 21:12 UTC, carlos-sarmiento commented
I've been a bit full right now, but still plan to take care of this

2020-03-30 22:16 UTC, closed without merging