Added tmp102 temperature sensor support
OttoWinter/esphomeyaml pull request #929
Opened 2019-12-29 06:14 UTC by timsavage

## Description:
Added support for the TMP102 temperature sensor. 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#451

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-03-23 22:50 UTC, timsavage commented
Not sure why Travis is still pending. All builds have completed successfully.

2020-04-20 00:15 UTC, glmnet commented
> Not sure why Travis is still pending. All builds have completed successfully.

It sometimes just can't tell GitHub the outcome, I fix it by re triggering the build, but I believe you need some kind of permission for that

2020-04-20 01:07 UTC, glmnet requested changes

2020-04-20 01:07 UTC, glmnet commented on esphome/components/tmp102/tmp102.cpp
> +    this->status_set_warning();
if you ever call set_warning you should call status_clear_warning at the end

2020-04-20 01:07 UTC, glmnet commented on esphome/components/tmp102/sensor.py
> +        cg.add(var.set_temperature(sens))
this is not needed

2020-09-22 23:18 UTC, jesserockz commented on esphome/components/tmp102/tmp102.cpp
> +    this->status_set_warning();
@timsavage Please follow up on this. Either remove the `status_set_warning` and just create a log with `ESP_LOGW` or clear the status once it is working.

2020-09-23 04:02 UTC, timsavage commented on esphome/components/tmp102/tmp102.cpp
> +    this->status_set_warning();
I'll be free to have a look mid October.

2020-10-02 09:12 UTC, jesserockz commented on esphome/components/tmp102/tmp102.cpp
> +}
```suggestion
  this->publish_state(temperature);
  this->status_clear_warning();
}
```

2020-10-05 23:30 UTC, glmnet approved these changes
LGTM!

2020-10-08 23:17 UTC, timsavage commented
Change looks good.

2020-10-26 18:00 UTC, merged