http_request unsecure fix
OttoWinter/esphomeyaml pull request #980
Opened 2020-02-11 08:25 UTC by Anonym-tsk

## Description:
Fixed HTTP requests

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/1040

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

2020-02-19 13:14 UTC, Anonym-tsk commented
@OttoWinter

2020-03-09 03:47 UTC, mnoorenberghe requested changes

2020-03-09 03:47 UTC, mnoorenberghe commented on esphome/components/http_request/__init__.py
> +    cg.add(var.set_secure(template_.startswith('https:')))
Hello, I thought I would try out your patch as I'm wanting to use `http_request`…

I found that this line doesn't work with lambdas:
> AttributeError: 'LambdaExpression' object has no attribute 'startswith'

2020-03-10 13:19 UTC, Anonym-tsk commented on esphome/components/http_request/__init__.py
> +    cg.add(var.set_secure(template_.startswith('https:')))
Thank you for this. I fixed this case

2020-03-12 00:26 UTC, brandond commented
LGTM

2020-03-12 00:27 UTC, merged